#+TITLE:       Main Google calendar entries
#+AUTHOR:      Eric S Fraga
#+EMAIL:       e.fraga@ucl.ac.uk
#+DESCRIPTION: converted using the ical2org awk script
#+CATEGORY:    google
#+STARTUP:     hidestars
#+STARTUP:     overview

* COMMENT original iCal preamble

* 66ers vs. Giants
<2018-04-05 Thu 21:05>--<2018-04-06 Fri 00:05>
:PROPERTIES:
:ID:       HvXXqrhZU3jvn2RuAL06CrIu@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

66ers vs. Giants 66ers vs. Giants

Follow on MiLB First Pitch  https //stza.co/+y0yU-B

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:66ers vs. Giants
END:VALARM
DTSTART:20180406T020500Z
DTEND:20180406T050500Z
UID:HvXXqrhZU3jvn2RuAL06CrIu@stanza.co
SUMMARY:66ers vs. Giants
DESCRIPTION:66ers vs. Giants\n\nFollow on MiLB First Pitch: https://stza.co/+y0yU-B\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144534Z
LAST-MODIFIED:20180213T144534Z
TRANSP:OPAQUE
END:VEVENT
* 66ers vs. Giants
<2018-04-06 Fri 21:05>--<2018-04-07 Sat 00:05>
:PROPERTIES:
:ID:       YY8O9YKXxLrDmV7FdJ-3b1yB@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

66ers vs. Giants 66ers vs. Giants

Follow on MiLB First Pitch  https //stza.co/+y0yW-2L

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:66ers vs. Giants
END:VALARM
DTSTART:20180407T020500Z
DTEND:20180407T050500Z
UID:YY8O9YKXxLrDmV7FdJ-3b1yB@stanza.co
SUMMARY:66ers vs. Giants
DESCRIPTION:66ers vs. Giants\n\nFollow on MiLB First Pitch: https://stza.co/+y0yW-2L\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144534Z
LAST-MODIFIED:20180213T144534Z
TRANSP:OPAQUE
END:VEVENT
* 66ers vs. Giants
<2018-04-07 Sat 20:05-23:05>
:PROPERTIES:
:ID:       iwx0wZhLAsRw23w5Qh_42XgQ@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

66ers vs. Giants 66ers vs. Giants

Follow on MiLB First Pitch  https //stza.co/+y0yY-2U

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:66ers vs. Giants
END:VALARM
DTSTART:20180408T010500Z
DTEND:20180408T040500Z
UID:iwx0wZhLAsRw23w5Qh_42XgQ@stanza.co
SUMMARY:66ers vs. Giants
DESCRIPTION:66ers vs. Giants\n\nFollow on MiLB First Pitch: https://stza.co/+y0yY-2U\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144534Z
LAST-MODIFIED:20180213T144534Z
TRANSP:OPAQUE
END:VEVENT
* 66ers vs. Giants
<2018-04-08 Sun 16:05-19:05>
:PROPERTIES:
:ID:       vKIaXqWXarJt7M9_WX-CRDkd@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

66ers vs. Giants 66ers vs. Giants

Follow on MiLB First Pitch  https //stza.co/+y0y$-26

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:66ers vs. Giants
END:VALARM
DTSTART:20180408T210500Z
DTEND:20180409T000500Z
UID:vKIaXqWXarJt7M9_WX-CRDkd@stanza.co
SUMMARY:66ers vs. Giants
DESCRIPTION:66ers vs. Giants\n\nFollow on MiLB First Pitch: https://stza.co/+y0y$-26\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144534Z
LAST-MODIFIED:20180213T144534Z
TRANSP:OPAQUE
END:VEVENT
* 66ers vs. Nuts
<2018-04-09 Mon 21:05>--<2018-04-10 Tue 00:05>
:PROPERTIES:
:ID:       m7H8-rV_13l8SOrM5PUEJEMD@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

66ers vs. Nuts 66ers vs. Nuts

Follow on MiLB First Pitch  https //stza.co/+y0z3-1M

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:66ers vs. Nuts
END:VALARM
DTSTART:20180410T020500Z
DTEND:20180410T050500Z
UID:m7H8-rV_13l8SOrM5PUEJEMD@stanza.co
SUMMARY:66ers vs. Nuts
DESCRIPTION:66ers vs. Nuts\n\nFollow on MiLB First Pitch: https://stza.co/+y0z3-1M\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144534Z
LAST-MODIFIED:20180213T144534Z
TRANSP:OPAQUE
END:VEVENT
* 66ers vs. Nuts
<2018-04-10 Tue 21:05>--<2018-04-11 Wed 00:05>
:PROPERTIES:
:ID:       O8jq553lM_-1A3qc2LnU3l-b@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

66ers vs. Nuts 66ers vs. Nuts

Follow on MiLB First Pitch  https //stza.co/+y0z5-c

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:66ers vs. Nuts
END:VALARM
DTSTART:20180411T020500Z
DTEND:20180411T050500Z
UID:O8jq553lM_-1A3qc2LnU3l-b@stanza.co
SUMMARY:66ers vs. Nuts
DESCRIPTION:66ers vs. Nuts\n\nFollow on MiLB First Pitch: https://stza.co/+y0z5-c\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144534Z
LAST-MODIFIED:20180213T144534Z
TRANSP:OPAQUE
END:VEVENT
* 66ers vs. Nuts
<2018-04-11 Wed 12:30-15:30>
:PROPERTIES:
:ID:       PWgOW07CydNxsZxMtRt00wws@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

66ers vs. Nuts 66ers vs. Nuts

Follow on MiLB First Pitch  https //stza.co/+y0z7-23

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:66ers vs. Nuts
END:VALARM
DTSTART:20180411T173000Z
DTEND:20180411T203000Z
UID:PWgOW07CydNxsZxMtRt00wws@stanza.co
SUMMARY:66ers vs. Nuts
DESCRIPTION:66ers vs. Nuts\n\nFollow on MiLB First Pitch: https://stza.co/+y0z7-23\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144534Z
LAST-MODIFIED:20180213T144534Z
TRANSP:OPAQUE
END:VEVENT
* 66ers @ Quakes
<2018-04-12 Thu 21:05>--<2018-04-13 Fri 00:05>
:PROPERTIES:
:ID:       SnGq776vLsAAKNZbKmwiRM2m@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

66ers @ Quakes 66ers @ Quakes

Follow on MiLB First Pitch  https //stza.co/+xAKm-1h

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:66ers @ Quakes
END:VALARM
DTSTART:20180413T020500Z
DTEND:20180413T050500Z
UID:SnGq776vLsAAKNZbKmwiRM2m@stanza.co
SUMMARY:66ers @ Quakes
DESCRIPTION:66ers @ Quakes\n\nFollow on MiLB First Pitch: https://stza.co/+xAKm-1h\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144534Z
LAST-MODIFIED:20180213T144534Z
TRANSP:OPAQUE
END:VEVENT
* 66ers @ Quakes
<2018-04-13 Fri 21:05>--<2018-04-14 Sat 00:05>
:PROPERTIES:
:ID:       NpGtSlsHwkODaj3P1KDtkLjb@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

66ers @ Quakes 66ers @ Quakes

Follow on MiLB First Pitch  https //stza.co/+xAKn-3n

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:66ers @ Quakes
END:VALARM
DTSTART:20180414T020500Z
DTEND:20180414T050500Z
UID:NpGtSlsHwkODaj3P1KDtkLjb@stanza.co
SUMMARY:66ers @ Quakes
DESCRIPTION:66ers @ Quakes\n\nFollow on MiLB First Pitch: https://stza.co/+xAKn-3n\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144534Z
LAST-MODIFIED:20180213T144534Z
TRANSP:OPAQUE
END:VEVENT
* 66ers @ Quakes
<2018-04-14 Sat 21:05>--<2018-04-15 Sun 00:05>
:PROPERTIES:
:ID:       sEZABnJ_A5DbgZt_p2UXcfKH@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

66ers @ Quakes 66ers @ Quakes

Follow on MiLB First Pitch  https //stza.co/+xAKo-3G

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:66ers @ Quakes
END:VALARM
DTSTART:20180415T020500Z
DTEND:20180415T050500Z
UID:sEZABnJ_A5DbgZt_p2UXcfKH@stanza.co
SUMMARY:66ers @ Quakes
DESCRIPTION:66ers @ Quakes\n\nFollow on MiLB First Pitch: https://stza.co/+xAKo-3G\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144534Z
LAST-MODIFIED:20180213T144534Z
TRANSP:OPAQUE
END:VEVENT
* 66ers @ Quakes
<2018-04-15 Sun 16:05-19:05>
:PROPERTIES:
:ID:       4qcMjY-xAKIFysDQYqc7kQMt@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

66ers @ Quakes 66ers @ Quakes

Follow on MiLB First Pitch  https //stza.co/+xAKq-v

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:66ers @ Quakes
END:VALARM
DTSTART:20180415T210500Z
DTEND:20180416T000500Z
UID:4qcMjY-xAKIFysDQYqc7kQMt@stanza.co
SUMMARY:66ers @ Quakes
DESCRIPTION:66ers @ Quakes\n\nFollow on MiLB First Pitch: https://stza.co/+xAKq-v\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144534Z
LAST-MODIFIED:20180213T144534Z
TRANSP:OPAQUE
END:VEVENT
* 66ers @ Storm
<2018-04-16 Mon 20:00-23:00>
:PROPERTIES:
:ID:       6McPbWQnGSsh6_lTrLO0FH9V@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

66ers @ Storm 66ers @ Storm

Follow on MiLB First Pitch  https //stza.co/+xAJS-3P

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:66ers @ Storm
END:VALARM
DTSTART:20180417T010000Z
DTEND:20180417T040000Z
UID:6McPbWQnGSsh6_lTrLO0FH9V@stanza.co
SUMMARY:66ers @ Storm
DESCRIPTION:66ers @ Storm\n\nFollow on MiLB First Pitch: https://stza.co/+xAJS-3P\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144534Z
LAST-MODIFIED:20180213T144534Z
TRANSP:OPAQUE
END:VEVENT
* 66ers @ Storm
<2018-04-17 Tue 20:00-23:00>
:PROPERTIES:
:ID:       p-suJPEmDbkzjJy1KoyDjczY@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

66ers @ Storm 66ers @ Storm

Follow on MiLB First Pitch  https //stza.co/+xAJT-3y

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:66ers @ Storm
END:VALARM
DTSTART:20180418T010000Z
DTEND:20180418T040000Z
UID:p-suJPEmDbkzjJy1KoyDjczY@stanza.co
SUMMARY:66ers @ Storm
DESCRIPTION:66ers @ Storm\n\nFollow on MiLB First Pitch: https://stza.co/+xAJT-3y\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144534Z
LAST-MODIFIED:20180213T144534Z
TRANSP:OPAQUE
END:VEVENT
* 66ers @ Storm
<2018-04-18 Wed 20:00-23:00>
:PROPERTIES:
:ID:       jFhJFTPcCLl_QKlCLFyI4nri@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

66ers @ Storm 66ers @ Storm

Follow on MiLB First Pitch  https //stza.co/+xAJV-L

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:66ers @ Storm
END:VALARM
DTSTART:20180419T010000Z
DTEND:20180419T040000Z
UID:jFhJFTPcCLl_QKlCLFyI4nri@stanza.co
SUMMARY:66ers @ Storm
DESCRIPTION:66ers @ Storm\n\nFollow on MiLB First Pitch: https://stza.co/+xAJV-L\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144534Z
LAST-MODIFIED:20180213T144534Z
TRANSP:OPAQUE
END:VEVENT
* 66ers vs. JetHawks
<2018-04-19 Thu 21:05>--<2018-04-20 Fri 00:05>
:PROPERTIES:
:ID:       TizlEdKPbgrMDio48hoyw1re@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

66ers vs. JetHawks 66ers vs. JetHawks

Follow on MiLB First Pitch  https //stza.co/+y0za-2i

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:66ers vs. JetHawks
END:VALARM
DTSTART:20180420T020500Z
DTEND:20180420T050500Z
UID:TizlEdKPbgrMDio48hoyw1re@stanza.co
SUMMARY:66ers vs. JetHawks
DESCRIPTION:66ers vs. JetHawks\n\nFollow on MiLB First Pitch: https://stza.co/+y0za-2i\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144534Z
LAST-MODIFIED:20180213T144534Z
TRANSP:OPAQUE
END:VEVENT
* 66ers vs. JetHawks
<2018-04-20 Fri 21:05>--<2018-04-21 Sat 00:05>
:PROPERTIES:
:ID:       YyoT15CDIfnSr-Ai3bPNw5Z4@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

66ers vs. JetHawks 66ers vs. JetHawks

Follow on MiLB First Pitch  https //stza.co/+y0zb-1h

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:66ers vs. JetHawks
END:VALARM
DTSTART:20180421T020500Z
DTEND:20180421T050500Z
UID:YyoT15CDIfnSr-Ai3bPNw5Z4@stanza.co
SUMMARY:66ers vs. JetHawks
DESCRIPTION:66ers vs. JetHawks\n\nFollow on MiLB First Pitch: https://stza.co/+y0zb-1h\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144534Z
LAST-MODIFIED:20180213T144534Z
TRANSP:OPAQUE
END:VEVENT
* 66ers vs. JetHawks
<2018-04-21 Sat 20:05-23:05>
:PROPERTIES:
:ID:       gKyG-ROIEP2cM5TqKoo86N-b@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

66ers vs. JetHawks 66ers vs. JetHawks

Follow on MiLB First Pitch  https //stza.co/+y0zd-2R

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:66ers vs. JetHawks
END:VALARM
DTSTART:20180422T010500Z
DTEND:20180422T040500Z
UID:gKyG-ROIEP2cM5TqKoo86N-b@stanza.co
SUMMARY:66ers vs. JetHawks
DESCRIPTION:66ers vs. JetHawks\n\nFollow on MiLB First Pitch: https://stza.co/+y0zd-2R\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144534Z
LAST-MODIFIED:20180213T144534Z
TRANSP:OPAQUE
END:VEVENT
* 66ers vs. JetHawks
<2018-04-22 Sun 16:05-19:05>
:PROPERTIES:
:ID:       0BHcEEQwsuk2ZA1TYlEURuhO@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

66ers vs. JetHawks 66ers vs. JetHawks

Follow on MiLB First Pitch  https //stza.co/+y0zf-11

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:66ers vs. JetHawks
END:VALARM
DTSTART:20180422T210500Z
DTEND:20180423T000500Z
UID:0BHcEEQwsuk2ZA1TYlEURuhO@stanza.co
SUMMARY:66ers vs. JetHawks
DESCRIPTION:66ers vs. JetHawks\n\nFollow on MiLB First Pitch: https://stza.co/+y0zf-11\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144534Z
LAST-MODIFIED:20180213T144534Z
TRANSP:OPAQUE
END:VEVENT
* 66ers @ Nuts
<2018-04-24 Tue 21:05>--<2018-04-25 Wed 00:05>
:PROPERTIES:
:ID:       iZJEi0PuhLl28c7vIqtSCx4T@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

66ers @ Nuts 66ers @ Nuts

Follow on MiLB First Pitch  https //stza.co/+xAKe-3g

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:66ers @ Nuts
END:VALARM
DTSTART:20180425T020500Z
DTEND:20180425T050500Z
UID:iZJEi0PuhLl28c7vIqtSCx4T@stanza.co
SUMMARY:66ers @ Nuts
DESCRIPTION:66ers @ Nuts\n\nFollow on MiLB First Pitch: https://stza.co/+xAKe-3g\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144534Z
LAST-MODIFIED:20180213T144534Z
TRANSP:OPAQUE
END:VEVENT
* 66ers @ Nuts
<2018-04-25 Wed 21:05>--<2018-04-26 Thu 00:05>
:PROPERTIES:
:ID:       StoYJ3BMCb3OkHxJW72y-ZPg@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

66ers @ Nuts 66ers @ Nuts

Follow on MiLB First Pitch  https //stza.co/+xAKf-C

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:66ers @ Nuts
END:VALARM
DTSTART:20180426T020500Z
DTEND:20180426T050500Z
UID:StoYJ3BMCb3OkHxJW72y-ZPg@stanza.co
SUMMARY:66ers @ Nuts
DESCRIPTION:66ers @ Nuts\n\nFollow on MiLB First Pitch: https://stza.co/+xAKf-C\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144534Z
LAST-MODIFIED:20180213T144534Z
TRANSP:OPAQUE
END:VEVENT
* 66ers @ Nuts
<2018-04-26 Thu 21:05>--<2018-04-27 Fri 00:05>
:PROPERTIES:
:ID:       1OYnZFnLA2n-yepOBe7NFdr2@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

66ers @ Nuts 66ers @ Nuts

Follow on MiLB First Pitch  https //stza.co/+xAKg-3d

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:66ers @ Nuts
END:VALARM
DTSTART:20180427T020500Z
DTEND:20180427T050500Z
UID:1OYnZFnLA2n-yepOBe7NFdr2@stanza.co
SUMMARY:66ers @ Nuts
DESCRIPTION:66ers @ Nuts\n\nFollow on MiLB First Pitch: https://stza.co/+xAKg-3d\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144534Z
LAST-MODIFIED:20180213T144534Z
TRANSP:OPAQUE
END:VEVENT
* 66ers @ Rawhide
<2018-04-27 Fri>--<2018-04-26 Thu>
:PROPERTIES:
:ID:       UWSjpZoUmarEXHmhiDpNuUaz@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

66ers @ Rawhide 66ers @ Rawhide

Follow on MiLB First Pitch  https //stza.co/+vLZ6-3B

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:66ers @ Rawhide
END:VALARM
DTSTART;VALUE=DATE:20180427
DTEND;VALUE=DATE:20180427
UID:UWSjpZoUmarEXHmhiDpNuUaz@stanza.co
SUMMARY:66ers @ Rawhide
DESCRIPTION:66ers @ Rawhide\n\nFollow on MiLB First Pitch: https://stza.co/+vLZ6-3B\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144534Z
LAST-MODIFIED:20180213T144534Z
TRANSP:OPAQUE
END:VEVENT
* 66ers @ Rawhide
<2018-04-28 Sat>--<2018-04-27 Fri>
:PROPERTIES:
:ID:       aOAexqNL-J9xLWrNUIecSz3p@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

66ers @ Rawhide 66ers @ Rawhide

Follow on MiLB First Pitch  https //stza.co/+vLZ7-1e

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:66ers @ Rawhide
END:VALARM
DTSTART;VALUE=DATE:20180428
DTEND;VALUE=DATE:20180428
UID:aOAexqNL-J9xLWrNUIecSz3p@stanza.co
SUMMARY:66ers @ Rawhide
DESCRIPTION:66ers @ Rawhide\n\nFollow on MiLB First Pitch: https://stza.co/+vLZ7-1e\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144534Z
LAST-MODIFIED:20180213T144534Z
TRANSP:OPAQUE
END:VEVENT
* 66ers @ Rawhide
<2018-04-29 Sun>--<2018-04-28 Sat>
:PROPERTIES:
:ID:       L-yV2_ukkzwLK_yjEU03wsQt@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

66ers @ Rawhide 66ers @ Rawhide

Follow on MiLB First Pitch  https //stza.co/+vLZ8-3

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:66ers @ Rawhide
END:VALARM
DTSTART;VALUE=DATE:20180429
DTEND;VALUE=DATE:20180429
UID:L-yV2_ukkzwLK_yjEU03wsQt@stanza.co
SUMMARY:66ers @ Rawhide
DESCRIPTION:66ers @ Rawhide\n\nFollow on MiLB First Pitch: https://stza.co/+vLZ8-3\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144534Z
LAST-MODIFIED:20180213T144534Z
TRANSP:OPAQUE
END:VEVENT
* 66ers vs. Storm
<2018-04-30 Mon 21:05>--<2018-05-01 Tue 00:05>
:PROPERTIES:
:ID:       x5bZVl8gureQbkhqyZJ--iXA@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

66ers vs. Storm 66ers vs. Storm

Follow on MiLB First Pitch  https //stza.co/+y0zi-P

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:66ers vs. Storm
END:VALARM
DTSTART:20180501T020500Z
DTEND:20180501T050500Z
UID:x5bZVl8gureQbkhqyZJ--iXA@stanza.co
SUMMARY:66ers vs. Storm
DESCRIPTION:66ers vs. Storm\n\nFollow on MiLB First Pitch: https://stza.co/+y0zi-P\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144534Z
LAST-MODIFIED:20180213T144534Z
TRANSP:OPAQUE
END:VEVENT
* 66ers vs. Storm
<2018-05-01 Tue 21:05>--<2018-05-02 Wed 00:05>
:PROPERTIES:
:ID:       3CsaafX0rpuCxWPtdWnX2ftY@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

66ers vs. Storm 66ers vs. Storm

Follow on MiLB First Pitch  https //stza.co/+y0zj-3M

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:66ers vs. Storm
END:VALARM
DTSTART:20180502T020500Z
DTEND:20180502T050500Z
UID:3CsaafX0rpuCxWPtdWnX2ftY@stanza.co
SUMMARY:66ers vs. Storm
DESCRIPTION:66ers vs. Storm\n\nFollow on MiLB First Pitch: https://stza.co/+y0zj-3M\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144534Z
LAST-MODIFIED:20180213T144534Z
TRANSP:OPAQUE
END:VEVENT
* 66ers vs. Storm
<2018-05-02 Wed 21:05>--<2018-05-03 Thu 00:05>
:PROPERTIES:
:ID:       tjo50y1xJOOcO6DqCxuOaxiH@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

66ers vs. Storm 66ers vs. Storm

Follow on MiLB First Pitch  https //stza.co/+y0zl-3O

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:66ers vs. Storm
END:VALARM
DTSTART:20180503T020500Z
DTEND:20180503T050500Z
UID:tjo50y1xJOOcO6DqCxuOaxiH@stanza.co
SUMMARY:66ers vs. Storm
DESCRIPTION:66ers vs. Storm\n\nFollow on MiLB First Pitch: https://stza.co/+y0zl-3O\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144534Z
LAST-MODIFIED:20180213T144534Z
TRANSP:OPAQUE
END:VEVENT
* 66ers vs. Storm
<2018-05-03 Thu 21:05>--<2018-05-04 Fri 00:05>
:PROPERTIES:
:ID:       39dyNdvqpm-IApR7KIgO-Cbj@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

66ers vs. Storm 66ers vs. Storm

Follow on MiLB First Pitch  https //stza.co/+y0zo-3J

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:66ers vs. Storm
END:VALARM
DTSTART:20180504T020500Z
DTEND:20180504T050500Z
UID:39dyNdvqpm-IApR7KIgO-Cbj@stanza.co
SUMMARY:66ers vs. Storm
DESCRIPTION:66ers vs. Storm\n\nFollow on MiLB First Pitch: https://stza.co/+y0zo-3J\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144534Z
LAST-MODIFIED:20180213T144534Z
TRANSP:OPAQUE
END:VEVENT
* 66ers @ Ports
<2018-05-04 Fri 21:10>--<2018-05-05 Sat 00:10>
:PROPERTIES:
:ID:       FqS27IBhFQPcllspSlW13y6N@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

66ers @ Ports 66ers @ Ports

Follow on MiLB First Pitch  https //stza.co/+vLZ0-3I

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:66ers @ Ports
END:VALARM
DTSTART:20180505T021000Z
DTEND:20180505T051000Z
UID:FqS27IBhFQPcllspSlW13y6N@stanza.co
SUMMARY:66ers @ Ports
DESCRIPTION:66ers @ Ports\n\nFollow on MiLB First Pitch: https://stza.co/+vLZ0-3I\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144534Z
LAST-MODIFIED:20180213T144534Z
TRANSP:OPAQUE
END:VEVENT
* 66ers @ Ports
<2018-05-05 Sat 21:10>--<2018-05-06 Sun 00:10>
:PROPERTIES:
:ID:       6geK1aj_0S8JlC2WFxY1YBoF@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

66ers @ Ports 66ers @ Ports

Follow on MiLB First Pitch  https //stza.co/+vLZ1-2j

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:66ers @ Ports
END:VALARM
DTSTART:20180506T021000Z
DTEND:20180506T051000Z
UID:6geK1aj_0S8JlC2WFxY1YBoF@stanza.co
SUMMARY:66ers @ Ports
DESCRIPTION:66ers @ Ports\n\nFollow on MiLB First Pitch: https://stza.co/+vLZ1-2j\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144534Z
LAST-MODIFIED:20180213T144534Z
TRANSP:OPAQUE
END:VEVENT
* 66ers @ Ports
<2018-05-06 Sun 16:09-19:09>
:PROPERTIES:
:ID:       g7ublpQZ_Xy4eJufHmXH2AER@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

66ers @ Ports 66ers @ Ports

Follow on MiLB First Pitch  https //stza.co/+vLZ2-1m

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:66ers @ Ports
END:VALARM
DTSTART:20180506T210900Z
DTEND:20180507T000900Z
UID:g7ublpQZ_Xy4eJufHmXH2AER@stanza.co
SUMMARY:66ers @ Ports
DESCRIPTION:66ers @ Ports\n\nFollow on MiLB First Pitch: https://stza.co/+vLZ2-1m\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144534Z
LAST-MODIFIED:20180213T144534Z
TRANSP:OPAQUE
END:VEVENT
* 66ers @ JetHawks
<2018-05-08 Tue 20:35-23:35>
:PROPERTIES:
:ID:       OgqaXOOXsncTqt9u-wGv7qLJ@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

66ers @ JetHawks 66ers @ JetHawks

Follow on MiLB First Pitch  https //stza.co/+vfdG-3

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:66ers @ JetHawks
END:VALARM
DTSTART:20180509T013500Z
DTEND:20180509T043500Z
UID:OgqaXOOXsncTqt9u-wGv7qLJ@stanza.co
SUMMARY:66ers @ JetHawks
DESCRIPTION:66ers @ JetHawks\n\nFollow on MiLB First Pitch: https://stza.co/+vfdG-3\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144534Z
LAST-MODIFIED:20180213T144534Z
TRANSP:OPAQUE
END:VEVENT
* 66ers @ JetHawks
<2018-05-09 Wed 20:35-23:35>
:PROPERTIES:
:ID:       GiXBBrqtjVTWFZ0FFgfUimkT@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

66ers @ JetHawks 66ers @ JetHawks

Follow on MiLB First Pitch  https //stza.co/+vfdS-19

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:66ers @ JetHawks
END:VALARM
DTSTART:20180510T013500Z
DTEND:20180510T043500Z
UID:GiXBBrqtjVTWFZ0FFgfUimkT@stanza.co
SUMMARY:66ers @ JetHawks
DESCRIPTION:66ers @ JetHawks\n\nFollow on MiLB First Pitch: https://stza.co/+vfdS-19\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144534Z
LAST-MODIFIED:20180213T144534Z
TRANSP:OPAQUE
END:VEVENT
* 66ers @ JetHawks
<2018-05-10 Thu 20:35-23:35>
:PROPERTIES:
:ID:       V3YcYjdwbRTH4kO1lmxet0Yu@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

66ers @ JetHawks 66ers @ JetHawks

Follow on MiLB First Pitch  https //stza.co/+vfdY-P

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:66ers @ JetHawks
END:VALARM
DTSTART:20180511T013500Z
DTEND:20180511T043500Z
UID:V3YcYjdwbRTH4kO1lmxet0Yu@stanza.co
SUMMARY:66ers @ JetHawks
DESCRIPTION:66ers @ JetHawks\n\nFollow on MiLB First Pitch: https://stza.co/+vfdY-P\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144534Z
LAST-MODIFIED:20180213T144534Z
TRANSP:OPAQUE
END:VEVENT
* 66ers vs. Ports
<2018-05-11 Fri 21:05>--<2018-05-12 Sat 00:05>
:PROPERTIES:
:ID:       ighWVcYya9P0_AqFMtCnqbSd@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

66ers vs. Ports 66ers vs. Ports

Follow on MiLB First Pitch  https //stza.co/+y0zq-2l

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:66ers vs. Ports
END:VALARM
DTSTART:20180512T020500Z
DTEND:20180512T050500Z
UID:ighWVcYya9P0_AqFMtCnqbSd@stanza.co
SUMMARY:66ers vs. Ports
DESCRIPTION:66ers vs. Ports\n\nFollow on MiLB First Pitch: https://stza.co/+y0zq-2l\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144534Z
LAST-MODIFIED:20180213T144534Z
TRANSP:OPAQUE
END:VEVENT
* 66ers vs. Ports
<2018-05-12 Sat 20:05-23:05>
:PROPERTIES:
:ID:       2-UKrGr52oSlgDeKe_3zv8A8@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

66ers vs. Ports 66ers vs. Ports

Follow on MiLB First Pitch  https //stza.co/+y0zs-1L

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:66ers vs. Ports
END:VALARM
DTSTART:20180513T010500Z
DTEND:20180513T040500Z
UID:2-UKrGr52oSlgDeKe_3zv8A8@stanza.co
SUMMARY:66ers vs. Ports
DESCRIPTION:66ers vs. Ports\n\nFollow on MiLB First Pitch: https://stza.co/+y0zs-1L\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144534Z
LAST-MODIFIED:20180213T144534Z
TRANSP:OPAQUE
END:VEVENT
* 66ers vs. Ports
<2018-05-13 Sun 16:05-19:05>
:PROPERTIES:
:ID:       0arlp0bJ0I9EByPRRKQXPntY@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

66ers vs. Ports 66ers vs. Ports

Follow on MiLB First Pitch  https //stza.co/+y0zu-n

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:66ers vs. Ports
END:VALARM
DTSTART:20180513T210500Z
DTEND:20180514T000500Z
UID:0arlp0bJ0I9EByPRRKQXPntY@stanza.co
SUMMARY:66ers vs. Ports
DESCRIPTION:66ers vs. Ports\n\nFollow on MiLB First Pitch: https://stza.co/+y0zu-n\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144534Z
LAST-MODIFIED:20180213T144534Z
TRANSP:OPAQUE
END:VEVENT
* 66ers vs. Ports
<2018-05-14 Mon 17:00-20:00>
:PROPERTIES:
:ID:       IeDFUlbkUPxFLbDGkZPNsBLb@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

66ers vs. Ports 66ers vs. Ports

Follow on MiLB First Pitch  https //stza.co/+y0zw-23

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:66ers vs. Ports
END:VALARM
DTSTART:20180514T220000Z
DTEND:20180515T010000Z
UID:IeDFUlbkUPxFLbDGkZPNsBLb@stanza.co
SUMMARY:66ers vs. Ports
DESCRIPTION:66ers vs. Ports\n\nFollow on MiLB First Pitch: https://stza.co/+y0zw-23\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144534Z
LAST-MODIFIED:20180213T144534Z
TRANSP:OPAQUE
END:VEVENT
* 66ers @ Storm
<2018-05-15 Tue 20:00-23:00>
:PROPERTIES:
:ID:       lNxBvtpNcGN9xIZA5iVe7r1E@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

66ers @ Storm 66ers @ Storm

Follow on MiLB First Pitch  https //stza.co/+xAJX-X

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:66ers @ Storm
END:VALARM
DTSTART:20180516T010000Z
DTEND:20180516T040000Z
UID:lNxBvtpNcGN9xIZA5iVe7r1E@stanza.co
SUMMARY:66ers @ Storm
DESCRIPTION:66ers @ Storm\n\nFollow on MiLB First Pitch: https://stza.co/+xAJX-X\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144534Z
LAST-MODIFIED:20180213T144534Z
TRANSP:OPAQUE
END:VEVENT
* 66ers @ Storm
<2018-05-16 Wed 20:00-23:00>
:PROPERTIES:
:ID:       6WYcWwxSAB0-vUujrmcsjNGt@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

66ers @ Storm 66ers @ Storm

Follow on MiLB First Pitch  https //stza.co/+xAJZ-1e

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:66ers @ Storm
END:VALARM
DTSTART:20180517T010000Z
DTEND:20180517T040000Z
UID:6WYcWwxSAB0-vUujrmcsjNGt@stanza.co
SUMMARY:66ers @ Storm
DESCRIPTION:66ers @ Storm\n\nFollow on MiLB First Pitch: https://stza.co/+xAJZ-1e\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144534Z
LAST-MODIFIED:20180213T144534Z
TRANSP:OPAQUE
END:VEVENT
* 66ers @ Storm
<2018-05-17 Thu 21:00>--<2018-05-18 Fri 00:00>
:PROPERTIES:
:ID:       AYYy3SOggytnNO0jrYIvTP2R@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

66ers @ Storm 66ers @ Storm

Follow on MiLB First Pitch  https //stza.co/+xAJ$-3w

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:66ers @ Storm
END:VALARM
DTSTART:20180518T020000Z
DTEND:20180518T050000Z
UID:AYYy3SOggytnNO0jrYIvTP2R@stanza.co
SUMMARY:66ers @ Storm
DESCRIPTION:66ers @ Storm\n\nFollow on MiLB First Pitch: https://stza.co/+xAJ$-3w\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144534Z
LAST-MODIFIED:20180213T144534Z
TRANSP:OPAQUE
END:VEVENT
* 66ers vs. JetHawks
<2018-05-18 Fri 21:05>--<2018-05-19 Sat 00:05>
:PROPERTIES:
:ID:       15NLsZ8vSYxPbcv0Z0fNgk7l@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

66ers vs. JetHawks 66ers vs. JetHawks

Follow on MiLB First Pitch  https //stza.co/+y0zx-d

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:66ers vs. JetHawks
END:VALARM
DTSTART:20180519T020500Z
DTEND:20180519T050500Z
UID:15NLsZ8vSYxPbcv0Z0fNgk7l@stanza.co
SUMMARY:66ers vs. JetHawks
DESCRIPTION:66ers vs. JetHawks\n\nFollow on MiLB First Pitch: https://stza.co/+y0zx-d\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144534Z
LAST-MODIFIED:20180213T144534Z
TRANSP:OPAQUE
END:VEVENT
* 66ers vs. JetHawks
<2018-05-19 Sat 20:05-23:05>
:PROPERTIES:
:ID:       _CfPqxR1HyO6UjJIw8J6BMK5@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

66ers vs. JetHawks 66ers vs. JetHawks

Follow on MiLB First Pitch  https //stza.co/+y0zB-1y

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:66ers vs. JetHawks
END:VALARM
DTSTART:20180520T010500Z
DTEND:20180520T040500Z
UID:_CfPqxR1HyO6UjJIw8J6BMK5@stanza.co
SUMMARY:66ers vs. JetHawks
DESCRIPTION:66ers vs. JetHawks\n\nFollow on MiLB First Pitch: https://stza.co/+y0zB-1y\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144534Z
LAST-MODIFIED:20180213T144534Z
TRANSP:OPAQUE
END:VEVENT
* 66ers vs. JetHawks
<2018-05-20 Sun 16:05-19:05>
:PROPERTIES:
:ID:       o5gEo_7v2GQQ6AyAVPiuzSyw@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

66ers vs. JetHawks 66ers vs. JetHawks

Follow on MiLB First Pitch  https //stza.co/+y0zD-2B

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:66ers vs. JetHawks
END:VALARM
DTSTART:20180520T210500Z
DTEND:20180521T000500Z
UID:o5gEo_7v2GQQ6AyAVPiuzSyw@stanza.co
SUMMARY:66ers vs. JetHawks
DESCRIPTION:66ers vs. JetHawks\n\nFollow on MiLB First Pitch: https://stza.co/+y0zD-2B\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144534Z
LAST-MODIFIED:20180213T144534Z
TRANSP:OPAQUE
END:VEVENT
* 66ers @ Rawhide
<2018-05-22 Tue>--<2018-05-21 Mon>
:PROPERTIES:
:ID:       nW-ImaWhRCtZTDR53daM0hQN@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

66ers @ Rawhide 66ers @ Rawhide

Follow on MiLB First Pitch  https //stza.co/+vLZ9-1B

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:66ers @ Rawhide
END:VALARM
DTSTART;VALUE=DATE:20180522
DTEND;VALUE=DATE:20180522
UID:nW-ImaWhRCtZTDR53daM0hQN@stanza.co
SUMMARY:66ers @ Rawhide
DESCRIPTION:66ers @ Rawhide\n\nFollow on MiLB First Pitch: https://stza.co/+vLZ9-1B\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144534Z
LAST-MODIFIED:20180213T144534Z
TRANSP:OPAQUE
END:VEVENT
* 66ers @ Rawhide
<2018-05-23 Wed>--<2018-05-22 Tue>
:PROPERTIES:
:ID:       YUyfOsLxrgYW6omdn4bbKUr6@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

66ers @ Rawhide 66ers @ Rawhide

Follow on MiLB First Pitch  https //stza.co/+vLZa-2P

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:66ers @ Rawhide
END:VALARM
DTSTART;VALUE=DATE:20180523
DTEND;VALUE=DATE:20180523
UID:YUyfOsLxrgYW6omdn4bbKUr6@stanza.co
SUMMARY:66ers @ Rawhide
DESCRIPTION:66ers @ Rawhide\n\nFollow on MiLB First Pitch: https://stza.co/+vLZa-2P\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144534Z
LAST-MODIFIED:20180213T144534Z
TRANSP:OPAQUE
END:VEVENT
* 66ers @ Rawhide
<2018-05-24 Thu>--<2018-05-23 Wed>
:PROPERTIES:
:ID:       wiE5bIYE481Tb_VhB5n5R_1v@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

66ers @ Rawhide 66ers @ Rawhide

Follow on MiLB First Pitch  https //stza.co/+vLZb-3b

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:66ers @ Rawhide
END:VALARM
DTSTART;VALUE=DATE:20180524
DTEND;VALUE=DATE:20180524
UID:wiE5bIYE481Tb_VhB5n5R_1v@stanza.co
SUMMARY:66ers @ Rawhide
DESCRIPTION:66ers @ Rawhide\n\nFollow on MiLB First Pitch: https://stza.co/+vLZb-3b\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144534Z
LAST-MODIFIED:20180213T144534Z
TRANSP:OPAQUE
END:VEVENT
* 66ers vs. Quakes
<2018-05-25 Fri 21:05>--<2018-05-26 Sat 00:05>
:PROPERTIES:
:ID:       qEtbbf4NpesOxbKk67kNdfd9@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

66ers vs. Quakes 66ers vs. Quakes

Follow on MiLB First Pitch  https //stza.co/+y0zH-36

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:66ers vs. Quakes
END:VALARM
DTSTART:20180526T020500Z
DTEND:20180526T050500Z
UID:qEtbbf4NpesOxbKk67kNdfd9@stanza.co
SUMMARY:66ers vs. Quakes
DESCRIPTION:66ers vs. Quakes\n\nFollow on MiLB First Pitch: https://stza.co/+y0zH-36\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144534Z
LAST-MODIFIED:20180213T144534Z
TRANSP:OPAQUE
END:VEVENT
* 66ers vs. Quakes
<2018-05-26 Sat 20:05-23:05>
:PROPERTIES:
:ID:       S-Xo5x_6x65NFOWAtlf0HiZH@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

66ers vs. Quakes 66ers vs. Quakes

Follow on MiLB First Pitch  https //stza.co/+y0zK-o

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:66ers vs. Quakes
END:VALARM
DTSTART:20180527T010500Z
DTEND:20180527T040500Z
UID:S-Xo5x_6x65NFOWAtlf0HiZH@stanza.co
SUMMARY:66ers vs. Quakes
DESCRIPTION:66ers vs. Quakes\n\nFollow on MiLB First Pitch: https://stza.co/+y0zK-o\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144534Z
LAST-MODIFIED:20180213T144534Z
TRANSP:OPAQUE
END:VEVENT
* 66ers vs. Quakes
<2018-05-27 Sun 16:05-19:05>
:PROPERTIES:
:ID:       qZ434AyXmwxZDlcrgRSBhVVA@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

66ers vs. Quakes 66ers vs. Quakes

Follow on MiLB First Pitch  https //stza.co/+y0zM-2B

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:66ers vs. Quakes
END:VALARM
DTSTART:20180527T210500Z
DTEND:20180528T000500Z
UID:qZ434AyXmwxZDlcrgRSBhVVA@stanza.co
SUMMARY:66ers vs. Quakes
DESCRIPTION:66ers vs. Quakes\n\nFollow on MiLB First Pitch: https://stza.co/+y0zM-2B\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144534Z
LAST-MODIFIED:20180213T144534Z
TRANSP:OPAQUE
END:VEVENT
* 66ers @ JetHawks
<2018-05-28 Mon 16:05-19:05>
:PROPERTIES:
:ID:       HF4PPp1qHmxTqrEg451uFi7m@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

66ers @ JetHawks 66ers @ JetHawks

Follow on MiLB First Pitch  https //stza.co/+vfe4-3S

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:66ers @ JetHawks
END:VALARM
DTSTART:20180528T210500Z
DTEND:20180529T000500Z
UID:HF4PPp1qHmxTqrEg451uFi7m@stanza.co
SUMMARY:66ers @ JetHawks
DESCRIPTION:66ers @ JetHawks\n\nFollow on MiLB First Pitch: https://stza.co/+vfe4-3S\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144534Z
LAST-MODIFIED:20180213T144534Z
TRANSP:OPAQUE
END:VEVENT
* 66ers @ JetHawks
<2018-05-29 Tue 20:35-23:35>
:PROPERTIES:
:ID:       P4BuEvHITjgki1plQMkRmEt1@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

66ers @ JetHawks 66ers @ JetHawks

Follow on MiLB First Pitch  https //stza.co/+vfeh-3d

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:66ers @ JetHawks
END:VALARM
DTSTART:20180530T013500Z
DTEND:20180530T043500Z
UID:P4BuEvHITjgki1plQMkRmEt1@stanza.co
SUMMARY:66ers @ JetHawks
DESCRIPTION:66ers @ JetHawks\n\nFollow on MiLB First Pitch: https://stza.co/+vfeh-3d\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144534Z
LAST-MODIFIED:20180213T144534Z
TRANSP:OPAQUE
END:VEVENT
* 66ers @ JetHawks
<2018-05-30 Wed 20:35-23:35>
:PROPERTIES:
:ID:       4jkqgxIKFxk8tlCog1EInCqx@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

66ers @ JetHawks 66ers @ JetHawks

Follow on MiLB First Pitch  https //stza.co/+vfeo-2y

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:66ers @ JetHawks
END:VALARM
DTSTART:20180531T013500Z
DTEND:20180531T043500Z
UID:4jkqgxIKFxk8tlCog1EInCqx@stanza.co
SUMMARY:66ers @ JetHawks
DESCRIPTION:66ers @ JetHawks\n\nFollow on MiLB First Pitch: https://stza.co/+vfeo-2y\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144534Z
LAST-MODIFIED:20180213T144534Z
TRANSP:OPAQUE
END:VEVENT
* 66ers @ JetHawks
<2018-05-31 Thu 20:35-23:35>
:PROPERTIES:
:ID:       396SZAF4pSwnsyskyALBkDSD@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

66ers @ JetHawks 66ers @ JetHawks

Follow on MiLB First Pitch  https //stza.co/+vfex-t

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:66ers @ JetHawks
END:VALARM
DTSTART:20180601T013500Z
DTEND:20180601T043500Z
UID:396SZAF4pSwnsyskyALBkDSD@stanza.co
SUMMARY:66ers @ JetHawks
DESCRIPTION:66ers @ JetHawks\n\nFollow on MiLB First Pitch: https://stza.co/+vfex-t\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144534Z
LAST-MODIFIED:20180213T144534Z
TRANSP:OPAQUE
END:VEVENT
* 66ers @ Storm
<2018-06-01 Fri 21:00>--<2018-06-02 Sat 00:00>
:PROPERTIES:
:ID:       Tufi97a3ujvW7o0fiW6K8MkN@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

66ers @ Storm 66ers @ Storm

Follow on MiLB First Pitch  https //stza.co/+xAK0-I

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:66ers @ Storm
END:VALARM
DTSTART:20180602T020000Z
DTEND:20180602T050000Z
UID:Tufi97a3ujvW7o0fiW6K8MkN@stanza.co
SUMMARY:66ers @ Storm
DESCRIPTION:66ers @ Storm\n\nFollow on MiLB First Pitch: https://stza.co/+xAK0-I\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144534Z
LAST-MODIFIED:20180213T144534Z
TRANSP:OPAQUE
END:VEVENT
* 66ers @ Storm
<2018-06-02 Sat 20:00-23:00>
:PROPERTIES:
:ID:       4RPNfaDtEMgdHcn_XcIg9n4n@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

66ers @ Storm 66ers @ Storm

Follow on MiLB First Pitch  https //stza.co/+xAK3-x

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:66ers @ Storm
END:VALARM
DTSTART:20180603T010000Z
DTEND:20180603T040000Z
UID:4RPNfaDtEMgdHcn_XcIg9n4n@stanza.co
SUMMARY:66ers @ Storm
DESCRIPTION:66ers @ Storm\n\nFollow on MiLB First Pitch: https://stza.co/+xAK3-x\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144534Z
LAST-MODIFIED:20180213T144534Z
TRANSP:OPAQUE
END:VEVENT
* 66ers @ Storm
<2018-06-03 Sun>--<2018-06-02 Sat>
:PROPERTIES:
:ID:       sqaLbIiB0sh0_cTuIYZdKz9o@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

66ers @ Storm 66ers @ Storm

Follow on MiLB First Pitch  https //stza.co/+vfcM-2x

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:66ers @ Storm
END:VALARM
DTSTART;VALUE=DATE:20180603
DTEND;VALUE=DATE:20180603
UID:sqaLbIiB0sh0_cTuIYZdKz9o@stanza.co
SUMMARY:66ers @ Storm
DESCRIPTION:66ers @ Storm\n\nFollow on MiLB First Pitch: https://stza.co/+vfcM-2x\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144534Z
LAST-MODIFIED:20180213T144534Z
TRANSP:OPAQUE
END:VEVENT
* 66ers vs. Storm
<2018-06-05 Tue 21:05>--<2018-06-06 Wed 00:05>
:PROPERTIES:
:ID:       rGjMyWXRVUfj16dO07A0Kh0F@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

66ers vs. Storm 66ers vs. Storm

Follow on MiLB First Pitch  https //stza.co/+y0zP-1N

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:66ers vs. Storm
END:VALARM
DTSTART:20180606T020500Z
DTEND:20180606T050500Z
UID:rGjMyWXRVUfj16dO07A0Kh0F@stanza.co
SUMMARY:66ers vs. Storm
DESCRIPTION:66ers vs. Storm\n\nFollow on MiLB First Pitch: https://stza.co/+y0zP-1N\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144534Z
LAST-MODIFIED:20180213T144534Z
TRANSP:OPAQUE
END:VEVENT
* 66ers vs. Storm
<2018-06-06 Wed 21:05>--<2018-06-07 Thu 00:05>
:PROPERTIES:
:ID:       Ozxf_izsyMz-bky3W5l7ae-K@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

66ers vs. Storm 66ers vs. Storm

Follow on MiLB First Pitch  https //stza.co/+y0zT-D

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:66ers vs. Storm
END:VALARM
DTSTART:20180607T020500Z
DTEND:20180607T050500Z
UID:Ozxf_izsyMz-bky3W5l7ae-K@stanza.co
SUMMARY:66ers vs. Storm
DESCRIPTION:66ers vs. Storm\n\nFollow on MiLB First Pitch: https://stza.co/+y0zT-D\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144534Z
LAST-MODIFIED:20180213T144534Z
TRANSP:OPAQUE
END:VEVENT
* 66ers vs. Storm
<2018-06-07 Thu 21:05>--<2018-06-08 Fri 00:05>
:PROPERTIES:
:ID:       g6TxU0K3TRpL0hznFPaSK7Dn@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

66ers vs. Storm 66ers vs. Storm

Follow on MiLB First Pitch  https //stza.co/+y0zV-3c

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:66ers vs. Storm
END:VALARM
DTSTART:20180608T020500Z
DTEND:20180608T050500Z
UID:g6TxU0K3TRpL0hznFPaSK7Dn@stanza.co
SUMMARY:66ers vs. Storm
DESCRIPTION:66ers vs. Storm\n\nFollow on MiLB First Pitch: https://stza.co/+y0zV-3c\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144534Z
LAST-MODIFIED:20180213T144534Z
TRANSP:OPAQUE
END:VEVENT
* 66ers @ Quakes
<2018-06-08 Fri 21:05>--<2018-06-09 Sat 00:05>
:PROPERTIES:
:ID:       SmUhVn-KqCB0_BCqjp1a_Zcr@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

66ers @ Quakes 66ers @ Quakes

Follow on MiLB First Pitch  https //stza.co/+xAKr-3s

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:66ers @ Quakes
END:VALARM
DTSTART:20180609T020500Z
DTEND:20180609T050500Z
UID:SmUhVn-KqCB0_BCqjp1a_Zcr@stanza.co
SUMMARY:66ers @ Quakes
DESCRIPTION:66ers @ Quakes\n\nFollow on MiLB First Pitch: https://stza.co/+xAKr-3s\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144534Z
LAST-MODIFIED:20180213T144534Z
TRANSP:OPAQUE
END:VEVENT
* 66ers @ Quakes
<2018-06-09 Sat 21:05>--<2018-06-10 Sun 00:05>
:PROPERTIES:
:ID:       uBlg8P6_W-axlJTczvdHOplI@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

66ers @ Quakes 66ers @ Quakes

Follow on MiLB First Pitch  https //stza.co/+xAKs-n

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:66ers @ Quakes
END:VALARM
DTSTART:20180610T020500Z
DTEND:20180610T050500Z
UID:uBlg8P6_W-axlJTczvdHOplI@stanza.co
SUMMARY:66ers @ Quakes
DESCRIPTION:66ers @ Quakes\n\nFollow on MiLB First Pitch: https://stza.co/+xAKs-n\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144534Z
LAST-MODIFIED:20180213T144534Z
TRANSP:OPAQUE
END:VEVENT
* 66ers @ Quakes
<2018-06-10 Sun 16:05-19:05>
:PROPERTIES:
:ID:       lF7JYIA0FB7AaZdgSlmlVTLS@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

66ers @ Quakes 66ers @ Quakes

Follow on MiLB First Pitch  https //stza.co/+xAKt-7

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:66ers @ Quakes
END:VALARM
DTSTART:20180610T210500Z
DTEND:20180611T000500Z
UID:lF7JYIA0FB7AaZdgSlmlVTLS@stanza.co
SUMMARY:66ers @ Quakes
DESCRIPTION:66ers @ Quakes\n\nFollow on MiLB First Pitch: https://stza.co/+xAKt-7\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144534Z
LAST-MODIFIED:20180213T144534Z
TRANSP:OPAQUE
END:VEVENT
* 66ers vs. JetHawks
<2018-06-11 Mon 21:05>--<2018-06-12 Tue 00:05>
:PROPERTIES:
:ID:       LWF4tpzXRNJNggJ1sXJN2z4j@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

66ers vs. JetHawks 66ers vs. JetHawks

Follow on MiLB First Pitch  https //stza.co/+y0zX-1t

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:66ers vs. JetHawks
END:VALARM
DTSTART:20180612T020500Z
DTEND:20180612T050500Z
UID:LWF4tpzXRNJNggJ1sXJN2z4j@stanza.co
SUMMARY:66ers vs. JetHawks
DESCRIPTION:66ers vs. JetHawks\n\nFollow on MiLB First Pitch: https://stza.co/+y0zX-1t\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144534Z
LAST-MODIFIED:20180213T144534Z
TRANSP:OPAQUE
END:VEVENT
* 66ers vs. JetHawks
<2018-06-12 Tue 21:05>--<2018-06-13 Wed 00:05>
:PROPERTIES:
:ID:       cjbIaAzfWG3V_BpwQWPPOzC6@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

66ers vs. JetHawks 66ers vs. JetHawks

Follow on MiLB First Pitch  https //stza.co/+y0zY-6

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:66ers vs. JetHawks
END:VALARM
DTSTART:20180613T020500Z
DTEND:20180613T050500Z
UID:cjbIaAzfWG3V_BpwQWPPOzC6@stanza.co
SUMMARY:66ers vs. JetHawks
DESCRIPTION:66ers vs. JetHawks\n\nFollow on MiLB First Pitch: https://stza.co/+y0zY-6\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144534Z
LAST-MODIFIED:20180213T144534Z
TRANSP:OPAQUE
END:VEVENT
* 66ers vs. JetHawks
<2018-06-13 Wed 21:05>--<2018-06-14 Thu 00:05>
:PROPERTIES:
:ID:       ZN61FADQfMv0oEUfAHnk6p2f@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

66ers vs. JetHawks 66ers vs. JetHawks

Follow on MiLB First Pitch  https //stza.co/+y0z$-23

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:66ers vs. JetHawks
END:VALARM
DTSTART:20180614T020500Z
DTEND:20180614T050500Z
UID:ZN61FADQfMv0oEUfAHnk6p2f@stanza.co
SUMMARY:66ers vs. JetHawks
DESCRIPTION:66ers vs. JetHawks\n\nFollow on MiLB First Pitch: https://stza.co/+y0z$-23\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144534Z
LAST-MODIFIED:20180213T144534Z
TRANSP:OPAQUE
END:VEVENT
* 66ers vs. JetHawks
<2018-06-14 Thu 21:05>--<2018-06-15 Fri 00:05>
:PROPERTIES:
:ID:       m8F3MnoNmR1wngF4nVfcRyOQ@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

66ers vs. JetHawks 66ers vs. JetHawks

Follow on MiLB First Pitch  https //stza.co/+y0A1-17

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:66ers vs. JetHawks
END:VALARM
DTSTART:20180615T020500Z
DTEND:20180615T050500Z
UID:m8F3MnoNmR1wngF4nVfcRyOQ@stanza.co
SUMMARY:66ers vs. JetHawks
DESCRIPTION:66ers vs. JetHawks\n\nFollow on MiLB First Pitch: https://stza.co/+y0A1-17\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144534Z
LAST-MODIFIED:20180213T144534Z
TRANSP:OPAQUE
END:VEVENT
* 66ers vs. Quakes
<2018-06-15 Fri 21:05>--<2018-06-16 Sat 00:05>
:PROPERTIES:
:ID:       nOGTns2AvWh60u03aRhR7m58@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

66ers vs. Quakes 66ers vs. Quakes

Follow on MiLB First Pitch  https //stza.co/+y0A3-3M

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:66ers vs. Quakes
END:VALARM
DTSTART:20180616T020500Z
DTEND:20180616T050500Z
UID:nOGTns2AvWh60u03aRhR7m58@stanza.co
SUMMARY:66ers vs. Quakes
DESCRIPTION:66ers vs. Quakes\n\nFollow on MiLB First Pitch: https://stza.co/+y0A3-3M\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144534Z
LAST-MODIFIED:20180213T144534Z
TRANSP:OPAQUE
END:VEVENT
* 66ers vs. Quakes
<2018-06-16 Sat 20:05-23:05>
:PROPERTIES:
:ID:       jp75kLHHcilx_AjPnHJslfoQ@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

66ers vs. Quakes 66ers vs. Quakes

Follow on MiLB First Pitch  https //stza.co/+y0A4-1Y

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:66ers vs. Quakes
END:VALARM
DTSTART:20180617T010500Z
DTEND:20180617T040500Z
UID:jp75kLHHcilx_AjPnHJslfoQ@stanza.co
SUMMARY:66ers vs. Quakes
DESCRIPTION:66ers vs. Quakes\n\nFollow on MiLB First Pitch: https://stza.co/+y0A4-1Y\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144534Z
LAST-MODIFIED:20180213T144534Z
TRANSP:OPAQUE
END:VEVENT
* 66ers vs. Quakes
<2018-06-17 Sun 16:05-19:05>
:PROPERTIES:
:ID:       e-WZC78pu0WvUvs-DlXBrjkf@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

66ers vs. Quakes 66ers vs. Quakes

Follow on MiLB First Pitch  https //stza.co/+y0A7-1p

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:66ers vs. Quakes
END:VALARM
DTSTART:20180617T210500Z
DTEND:20180618T000500Z
UID:e-WZC78pu0WvUvs-DlXBrjkf@stanza.co
SUMMARY:66ers vs. Quakes
DESCRIPTION:66ers vs. Quakes\n\nFollow on MiLB First Pitch: https://stza.co/+y0A7-1p\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144534Z
LAST-MODIFIED:20180213T144534Z
TRANSP:OPAQUE
END:VEVENT
* 66ers @ JetHawks
<2018-06-21 Thu 20:35-23:35>
:PROPERTIES:
:ID:       mzcDCBvktCdj8kL3MqPLuNNP@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

66ers @ JetHawks 66ers @ JetHawks

Follow on MiLB First Pitch  https //stza.co/+vfeE-3D

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:66ers @ JetHawks
END:VALARM
DTSTART:20180622T013500Z
DTEND:20180622T043500Z
UID:mzcDCBvktCdj8kL3MqPLuNNP@stanza.co
SUMMARY:66ers @ JetHawks
DESCRIPTION:66ers @ JetHawks\n\nFollow on MiLB First Pitch: https://stza.co/+vfeE-3D\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144534Z
LAST-MODIFIED:20180213T144534Z
TRANSP:OPAQUE
END:VEVENT
* 66ers @ JetHawks
<2018-06-22 Fri 20:35-23:35>
:PROPERTIES:
:ID:       5HE-xDL37fnIMidk0qikNb9H@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

66ers @ JetHawks 66ers @ JetHawks

Follow on MiLB First Pitch  https //stza.co/+vfeQ-39

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:66ers @ JetHawks
END:VALARM
DTSTART:20180623T013500Z
DTEND:20180623T043500Z
UID:5HE-xDL37fnIMidk0qikNb9H@stanza.co
SUMMARY:66ers @ JetHawks
DESCRIPTION:66ers @ JetHawks\n\nFollow on MiLB First Pitch: https://stza.co/+vfeQ-39\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144534Z
LAST-MODIFIED:20180213T144534Z
TRANSP:OPAQUE
END:VEVENT
* 66ers @ JetHawks
<2018-06-23 Sat 20:05-23:05>
:PROPERTIES:
:ID:       XoomeYmyZcPjkerhcXND30Hb@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

66ers @ JetHawks 66ers @ JetHawks

Follow on MiLB First Pitch  https //stza.co/+vfeV-4

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:66ers @ JetHawks
END:VALARM
DTSTART:20180624T010500Z
DTEND:20180624T040500Z
UID:XoomeYmyZcPjkerhcXND30Hb@stanza.co
SUMMARY:66ers @ JetHawks
DESCRIPTION:66ers @ JetHawks\n\nFollow on MiLB First Pitch: https://stza.co/+vfeV-4\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144534Z
LAST-MODIFIED:20180213T144534Z
TRANSP:OPAQUE
END:VEVENT
* 66ers @ JetHawks
<2018-06-24 Sun>--<2018-06-23 Sat>
:PROPERTIES:
:ID:       Lu9g3T0wC79GeC-PCrcONrkL@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

66ers @ JetHawks 66ers @ JetHawks

Follow on MiLB First Pitch  https //stza.co/+vff2-2G

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:66ers @ JetHawks
END:VALARM
DTSTART;VALUE=DATE:20180624
DTEND;VALUE=DATE:20180624
UID:Lu9g3T0wC79GeC-PCrcONrkL@stanza.co
SUMMARY:66ers @ JetHawks
DESCRIPTION:66ers @ JetHawks\n\nFollow on MiLB First Pitch: https://stza.co/+vff2-2G\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144534Z
LAST-MODIFIED:20180213T144534Z
TRANSP:OPAQUE
END:VEVENT
* 66ers vs. Rawhide
<2018-06-25 Mon 21:05>--<2018-06-26 Tue 00:05>
:PROPERTIES:
:ID:       BZiGYV6tgAc3F-DFMHYA4PFs@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

66ers vs. Rawhide 66ers vs. Rawhide

Follow on MiLB First Pitch  https //stza.co/+y0A9-N

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:66ers vs. Rawhide
END:VALARM
DTSTART:20180626T020500Z
DTEND:20180626T050500Z
UID:BZiGYV6tgAc3F-DFMHYA4PFs@stanza.co
SUMMARY:66ers vs. Rawhide
DESCRIPTION:66ers vs. Rawhide\n\nFollow on MiLB First Pitch: https://stza.co/+y0A9-N\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144534Z
LAST-MODIFIED:20180213T144534Z
TRANSP:OPAQUE
END:VEVENT
* 66ers vs. Rawhide
<2018-06-26 Tue 21:05>--<2018-06-27 Wed 00:05>
:PROPERTIES:
:ID:       Ft_5-Ogz8k7jt5mFVYmh0FxS@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

66ers vs. Rawhide 66ers vs. Rawhide

Follow on MiLB First Pitch  https //stza.co/+y0Aa-C

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:66ers vs. Rawhide
END:VALARM
DTSTART:20180627T020500Z
DTEND:20180627T050500Z
UID:Ft_5-Ogz8k7jt5mFVYmh0FxS@stanza.co
SUMMARY:66ers vs. Rawhide
DESCRIPTION:66ers vs. Rawhide\n\nFollow on MiLB First Pitch: https://stza.co/+y0Aa-C\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144534Z
LAST-MODIFIED:20180213T144534Z
TRANSP:OPAQUE
END:VEVENT
* 66ers vs. Rawhide
<2018-06-27 Wed 13:00-16:00>
:PROPERTIES:
:ID:       qVk5FWkAk5LaCZpqg9BWF05B@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

66ers vs. Rawhide 66ers vs. Rawhide

Follow on MiLB First Pitch  https //stza.co/+y0Ac-3a

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:66ers vs. Rawhide
END:VALARM
DTSTART:20180627T180000Z
DTEND:20180627T210000Z
UID:qVk5FWkAk5LaCZpqg9BWF05B@stanza.co
SUMMARY:66ers vs. Rawhide
DESCRIPTION:66ers vs. Rawhide\n\nFollow on MiLB First Pitch: https://stza.co/+y0Ac-3a\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144534Z
LAST-MODIFIED:20180213T144534Z
TRANSP:OPAQUE
END:VEVENT
* 66ers vs. Rawhide
<2018-06-28 Thu 21:05>--<2018-06-29 Fri 00:05>
:PROPERTIES:
:ID:       RTz-s54sN5581-MbhzkwtRZh@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

66ers vs. Rawhide 66ers vs. Rawhide

Follow on MiLB First Pitch  https //stza.co/+y0Af-25

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:66ers vs. Rawhide
END:VALARM
DTSTART:20180629T020500Z
DTEND:20180629T050500Z
UID:RTz-s54sN5581-MbhzkwtRZh@stanza.co
SUMMARY:66ers vs. Rawhide
DESCRIPTION:66ers vs. Rawhide\n\nFollow on MiLB First Pitch: https://stza.co/+y0Af-25\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144534Z
LAST-MODIFIED:20180213T144534Z
TRANSP:OPAQUE
END:VEVENT
* 66ers @ Quakes
<2018-06-29 Fri 21:05>--<2018-06-30 Sat 00:05>
:PROPERTIES:
:ID:       xsWdjnOESR-6g1NWkUtRPIfB@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

66ers @ Quakes 66ers @ Quakes

Follow on MiLB First Pitch  https //stza.co/+xAKu-j

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:66ers @ Quakes
END:VALARM
DTSTART:20180630T020500Z
DTEND:20180630T050500Z
UID:xsWdjnOESR-6g1NWkUtRPIfB@stanza.co
SUMMARY:66ers @ Quakes
DESCRIPTION:66ers @ Quakes\n\nFollow on MiLB First Pitch: https://stza.co/+xAKu-j\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144534Z
LAST-MODIFIED:20180213T144534Z
TRANSP:OPAQUE
END:VEVENT
* 66ers @ Quakes
<2018-06-30 Sat 21:05>--<2018-07-01 Sun 00:05>
:PROPERTIES:
:ID:       HcCh0dvaFrbwV5LVaWnOj75T@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

66ers @ Quakes 66ers @ Quakes

Follow on MiLB First Pitch  https //stza.co/+xAKv-1f

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:66ers @ Quakes
END:VALARM
DTSTART:20180701T020500Z
DTEND:20180701T050500Z
UID:HcCh0dvaFrbwV5LVaWnOj75T@stanza.co
SUMMARY:66ers @ Quakes
DESCRIPTION:66ers @ Quakes\n\nFollow on MiLB First Pitch: https://stza.co/+xAKv-1f\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144534Z
LAST-MODIFIED:20180213T144534Z
TRANSP:OPAQUE
END:VEVENT
* 66ers @ Quakes
<2018-07-01 Sun 16:05-19:05>
:PROPERTIES:
:ID:       WIFSyZS0SvWVYoETjUuY8pRA@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

66ers @ Quakes 66ers @ Quakes

Follow on MiLB First Pitch  https //stza.co/+xAKw-18

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:66ers @ Quakes
END:VALARM
DTSTART:20180701T210500Z
DTEND:20180702T000500Z
UID:WIFSyZS0SvWVYoETjUuY8pRA@stanza.co
SUMMARY:66ers @ Quakes
DESCRIPTION:66ers @ Quakes\n\nFollow on MiLB First Pitch: https://stza.co/+xAKw-18\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144534Z
LAST-MODIFIED:20180213T144534Z
TRANSP:OPAQUE
END:VEVENT
* 66ers @ Quakes
<2018-07-02 Mon 21:05>--<2018-07-03 Tue 00:05>
:PROPERTIES:
:ID:       ZERrQ1VoNgGFN9vLyZ02ExY7@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

66ers @ Quakes 66ers @ Quakes

Follow on MiLB First Pitch  https //stza.co/+xAKx-$

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:66ers @ Quakes
END:VALARM
DTSTART:20180703T020500Z
DTEND:20180703T050500Z
UID:ZERrQ1VoNgGFN9vLyZ02ExY7@stanza.co
SUMMARY:66ers @ Quakes
DESCRIPTION:66ers @ Quakes\n\nFollow on MiLB First Pitch: https://stza.co/+xAKx-$\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144534Z
LAST-MODIFIED:20180213T144534Z
TRANSP:OPAQUE
END:VEVENT
* 66ers @ Quakes
<2018-07-03 Tue 21:05>--<2018-07-04 Wed 00:05>
:PROPERTIES:
:ID:       4C-GRTJa8MuOuGaBO1QvqPIE@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

66ers @ Quakes 66ers @ Quakes

Follow on MiLB First Pitch  https //stza.co/+xAKy-1d

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:66ers @ Quakes
END:VALARM
DTSTART:20180704T020500Z
DTEND:20180704T050500Z
UID:4C-GRTJa8MuOuGaBO1QvqPIE@stanza.co
SUMMARY:66ers @ Quakes
DESCRIPTION:66ers @ Quakes\n\nFollow on MiLB First Pitch: https://stza.co/+xAKy-1d\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144534Z
LAST-MODIFIED:20180213T144534Z
TRANSP:OPAQUE
END:VEVENT
* 66ers vs. Ports
<2018-07-04 Wed 21:05>--<2018-07-05 Thu 00:05>
:PROPERTIES:
:ID:       DVr720KWOQ9MU1Ijx0S_SI_7@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

66ers vs. Ports 66ers vs. Ports

Follow on MiLB First Pitch  https //stza.co/+y0Ah-1S

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:66ers vs. Ports
END:VALARM
DTSTART:20180705T020500Z
DTEND:20180705T050500Z
UID:DVr720KWOQ9MU1Ijx0S_SI_7@stanza.co
SUMMARY:66ers vs. Ports
DESCRIPTION:66ers vs. Ports\n\nFollow on MiLB First Pitch: https://stza.co/+y0Ah-1S\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144534Z
LAST-MODIFIED:20180213T144534Z
TRANSP:OPAQUE
END:VEVENT
* 66ers vs. Ports
<2018-07-05 Thu 21:05>--<2018-07-06 Fri 00:05>
:PROPERTIES:
:ID:       Cf6Hp6pED4hGV-xZkRa7xAhz@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

66ers vs. Ports 66ers vs. Ports

Follow on MiLB First Pitch  https //stza.co/+y0Aj-Y

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:66ers vs. Ports
END:VALARM
DTSTART:20180706T020500Z
DTEND:20180706T050500Z
UID:Cf6Hp6pED4hGV-xZkRa7xAhz@stanza.co
SUMMARY:66ers vs. Ports
DESCRIPTION:66ers vs. Ports\n\nFollow on MiLB First Pitch: https://stza.co/+y0Aj-Y\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144534Z
LAST-MODIFIED:20180213T144534Z
TRANSP:OPAQUE
END:VEVENT
* 66ers vs. Ports
<2018-07-06 Fri 21:05>--<2018-07-07 Sat 00:05>
:PROPERTIES:
:ID:       RPXu9CiTPkScfLqVCsqFl1ll@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

66ers vs. Ports 66ers vs. Ports

Follow on MiLB First Pitch  https //stza.co/+y0Am-3G

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:66ers vs. Ports
END:VALARM
DTSTART:20180707T020500Z
DTEND:20180707T050500Z
UID:RPXu9CiTPkScfLqVCsqFl1ll@stanza.co
SUMMARY:66ers vs. Ports
DESCRIPTION:66ers vs. Ports\n\nFollow on MiLB First Pitch: https://stza.co/+y0Am-3G\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144534Z
LAST-MODIFIED:20180213T144534Z
TRANSP:OPAQUE
END:VEVENT
* 66ers vs. Ports
<2018-07-07 Sat 20:05-23:05>
:PROPERTIES:
:ID:       xPLOhul1etRiWajlgqjLS-tW@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

66ers vs. Ports 66ers vs. Ports

Follow on MiLB First Pitch  https //stza.co/+y0Ao-1q

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:66ers vs. Ports
END:VALARM
DTSTART:20180708T010500Z
DTEND:20180708T040500Z
UID:xPLOhul1etRiWajlgqjLS-tW@stanza.co
SUMMARY:66ers vs. Ports
DESCRIPTION:66ers vs. Ports\n\nFollow on MiLB First Pitch: https://stza.co/+y0Ao-1q\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144534Z
LAST-MODIFIED:20180213T144534Z
TRANSP:OPAQUE
END:VEVENT
* 66ers vs. Ports
<2018-07-08 Sun 19:35-22:35>
:PROPERTIES:
:ID:       __qaZkY52qaTsrIiWSrEsXrT@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

66ers vs. Ports 66ers vs. Ports

Follow on MiLB First Pitch  https //stza.co/+y0Ar-U

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:66ers vs. Ports
END:VALARM
DTSTART:20180709T003500Z
DTEND:20180709T033500Z
UID:__qaZkY52qaTsrIiWSrEsXrT@stanza.co
SUMMARY:66ers vs. Ports
DESCRIPTION:66ers vs. Ports\n\nFollow on MiLB First Pitch: https://stza.co/+y0Ar-U\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144534Z
LAST-MODIFIED:20180213T144534Z
TRANSP:OPAQUE
END:VEVENT
* 66ers @ Storm
<2018-07-09 Mon 20:00-23:00>
:PROPERTIES:
:ID:       6Rw4cEVs1b7e9r1lHo-4I0Z8@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

66ers @ Storm 66ers @ Storm

Follow on MiLB First Pitch  https //stza.co/+xAK5-2O

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:66ers @ Storm
END:VALARM
DTSTART:20180710T010000Z
DTEND:20180710T040000Z
UID:6Rw4cEVs1b7e9r1lHo-4I0Z8@stanza.co
SUMMARY:66ers @ Storm
DESCRIPTION:66ers @ Storm\n\nFollow on MiLB First Pitch: https://stza.co/+xAK5-2O\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144534Z
LAST-MODIFIED:20180213T144534Z
TRANSP:OPAQUE
END:VEVENT
* 66ers @ Storm
<2018-07-10 Tue 20:00-23:00>
:PROPERTIES:
:ID:       yKVm_mvr5u5K1qsyJ8EhpyWg@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

66ers @ Storm 66ers @ Storm

Follow on MiLB First Pitch  https //stza.co/+xAK6-1Y

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:66ers @ Storm
END:VALARM
DTSTART:20180711T010000Z
DTEND:20180711T040000Z
UID:yKVm_mvr5u5K1qsyJ8EhpyWg@stanza.co
SUMMARY:66ers @ Storm
DESCRIPTION:66ers @ Storm\n\nFollow on MiLB First Pitch: https://stza.co/+xAK6-1Y\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144534Z
LAST-MODIFIED:20180213T144534Z
TRANSP:OPAQUE
END:VEVENT
* 66ers @ Storm
<2018-07-11 Wed 20:00-23:00>
:PROPERTIES:
:ID:       R2JAJRsdmjHy3k36BuJItLhe@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

66ers @ Storm 66ers @ Storm

Follow on MiLB First Pitch  https //stza.co/+xAK7-2Q

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:66ers @ Storm
END:VALARM
DTSTART:20180712T010000Z
DTEND:20180712T040000Z
UID:R2JAJRsdmjHy3k36BuJItLhe@stanza.co
SUMMARY:66ers @ Storm
DESCRIPTION:66ers @ Storm\n\nFollow on MiLB First Pitch: https://stza.co/+xAK7-2Q\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144534Z
LAST-MODIFIED:20180213T144534Z
TRANSP:OPAQUE
END:VEVENT
* 66ers @ Storm
<2018-07-12 Thu 21:00>--<2018-07-13 Fri 00:00>
:PROPERTIES:
:ID:       x64BhTVmb-0YQTdxkM6ehxXq@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

66ers @ Storm 66ers @ Storm

Follow on MiLB First Pitch  https //stza.co/+xAKa-1c

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:66ers @ Storm
END:VALARM
DTSTART:20180713T020000Z
DTEND:20180713T050000Z
UID:x64BhTVmb-0YQTdxkM6ehxXq@stanza.co
SUMMARY:66ers @ Storm
DESCRIPTION:66ers @ Storm\n\nFollow on MiLB First Pitch: https://stza.co/+xAKa-1c\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144534Z
LAST-MODIFIED:20180213T144534Z
TRANSP:OPAQUE
END:VEVENT
* 66ers vs. Quakes
<2018-07-13 Fri 21:05>--<2018-07-14 Sat 00:05>
:PROPERTIES:
:ID:       W3-iczugn6K4D7oyc8cQkYIO@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

66ers vs. Quakes 66ers vs. Quakes

Follow on MiLB First Pitch  https //stza.co/+y0Au-z

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:66ers vs. Quakes
END:VALARM
DTSTART:20180714T020500Z
DTEND:20180714T050500Z
UID:W3-iczugn6K4D7oyc8cQkYIO@stanza.co
SUMMARY:66ers vs. Quakes
DESCRIPTION:66ers vs. Quakes\n\nFollow on MiLB First Pitch: https://stza.co/+y0Au-z\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144534Z
LAST-MODIFIED:20180213T144534Z
TRANSP:OPAQUE
END:VEVENT
* 66ers vs. Quakes
<2018-07-14 Sat 20:05-23:05>
:PROPERTIES:
:ID:       doYwlZoaCCBGnuwZRR0Ss2cc@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

66ers vs. Quakes 66ers vs. Quakes

Follow on MiLB First Pitch  https //stza.co/+y0Aw-o

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:66ers vs. Quakes
END:VALARM
DTSTART:20180715T010500Z
DTEND:20180715T040500Z
UID:doYwlZoaCCBGnuwZRR0Ss2cc@stanza.co
SUMMARY:66ers vs. Quakes
DESCRIPTION:66ers vs. Quakes\n\nFollow on MiLB First Pitch: https://stza.co/+y0Aw-o\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144534Z
LAST-MODIFIED:20180213T144534Z
TRANSP:OPAQUE
END:VEVENT
* 66ers vs. Quakes
<2018-07-15 Sun 19:35-22:35>
:PROPERTIES:
:ID:       Wgr7t5V0I_4Zw58Uba5PzNzs@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

66ers vs. Quakes 66ers vs. Quakes

Follow on MiLB First Pitch  https //stza.co/+y0Ax-A

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:66ers vs. Quakes
END:VALARM
DTSTART:20180716T003500Z
DTEND:20180716T033500Z
UID:Wgr7t5V0I_4Zw58Uba5PzNzs@stanza.co
SUMMARY:66ers vs. Quakes
DESCRIPTION:66ers vs. Quakes\n\nFollow on MiLB First Pitch: https://stza.co/+y0Ax-A\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144534Z
LAST-MODIFIED:20180213T144534Z
TRANSP:OPAQUE
END:VEVENT
* 66ers vs. Quakes
<2018-07-16 Mon 21:05>--<2018-07-17 Tue 00:05>
:PROPERTIES:
:ID:       9qw-LOqZZAsihYwdZ5Kaw15I@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

66ers vs. Quakes 66ers vs. Quakes

Follow on MiLB First Pitch  https //stza.co/+y0AA-2P

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:66ers vs. Quakes
END:VALARM
DTSTART:20180717T020500Z
DTEND:20180717T050500Z
UID:9qw-LOqZZAsihYwdZ5Kaw15I@stanza.co
SUMMARY:66ers vs. Quakes
DESCRIPTION:66ers vs. Quakes\n\nFollow on MiLB First Pitch: https://stza.co/+y0AA-2P\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144534Z
LAST-MODIFIED:20180213T144534Z
TRANSP:OPAQUE
END:VEVENT
* 66ers @ Rawhide
<2018-07-18 Wed>--<2018-07-17 Tue>
:PROPERTIES:
:ID:       jtYozP25THYKxB62gFBYKIob@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

66ers @ Rawhide 66ers @ Rawhide

Follow on MiLB First Pitch  https //stza.co/+vLZc-3i

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:66ers @ Rawhide
END:VALARM
DTSTART;VALUE=DATE:20180718
DTEND;VALUE=DATE:20180718
UID:jtYozP25THYKxB62gFBYKIob@stanza.co
SUMMARY:66ers @ Rawhide
DESCRIPTION:66ers @ Rawhide\n\nFollow on MiLB First Pitch: https://stza.co/+vLZc-3i\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144534Z
LAST-MODIFIED:20180213T144534Z
TRANSP:OPAQUE
END:VEVENT
* 66ers @ Rawhide
<2018-07-19 Thu>--<2018-07-18 Wed>
:PROPERTIES:
:ID:       RV2P-QVmJ_TmuM_w4LK3qOY3@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

66ers @ Rawhide 66ers @ Rawhide

Follow on MiLB First Pitch  https //stza.co/+vLZd-3F

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:66ers @ Rawhide
END:VALARM
DTSTART;VALUE=DATE:20180719
DTEND;VALUE=DATE:20180719
UID:RV2P-QVmJ_TmuM_w4LK3qOY3@stanza.co
SUMMARY:66ers @ Rawhide
DESCRIPTION:66ers @ Rawhide\n\nFollow on MiLB First Pitch: https://stza.co/+vLZd-3F\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144534Z
LAST-MODIFIED:20180213T144534Z
TRANSP:OPAQUE
END:VEVENT
* 66ers @ Rawhide
<2018-07-20 Fri>--<2018-07-19 Thu>
:PROPERTIES:
:ID:       OT2gdSX0iDLRhAchUzMx_OWA@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

66ers @ Rawhide 66ers @ Rawhide

Follow on MiLB First Pitch  https //stza.co/+vfrG-p

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:66ers @ Rawhide
END:VALARM
DTSTART;VALUE=DATE:20180720
DTEND;VALUE=DATE:20180720
UID:OT2gdSX0iDLRhAchUzMx_OWA@stanza.co
SUMMARY:66ers @ Rawhide
DESCRIPTION:66ers @ Rawhide\n\nFollow on MiLB First Pitch: https://stza.co/+vfrG-p\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144534Z
LAST-MODIFIED:20180213T144534Z
TRANSP:OPAQUE
END:VEVENT
* 66ers @ Ports
<2018-07-21 Sat 21:10>--<2018-07-22 Sun 00:10>
:PROPERTIES:
:ID:       vGb2r0_OlplqYT3O6qXbRd0s@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

66ers @ Ports 66ers @ Ports

Follow on MiLB First Pitch  https //stza.co/+vLZ3-19

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:66ers @ Ports
END:VALARM
DTSTART:20180722T021000Z
DTEND:20180722T051000Z
UID:vGb2r0_OlplqYT3O6qXbRd0s@stanza.co
SUMMARY:66ers @ Ports
DESCRIPTION:66ers @ Ports\n\nFollow on MiLB First Pitch: https://stza.co/+vLZ3-19\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144534Z
LAST-MODIFIED:20180213T144534Z
TRANSP:OPAQUE
END:VEVENT
* 66ers @ Ports
<2018-07-22 Sun 20:10-23:10>
:PROPERTIES:
:ID:       Id-A3vB3OIMb_ETjJ7PXW9wO@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

66ers @ Ports 66ers @ Ports

Follow on MiLB First Pitch  https //stza.co/+vLZ4-1L

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:66ers @ Ports
END:VALARM
DTSTART:20180723T011000Z
DTEND:20180723T041000Z
UID:Id-A3vB3OIMb_ETjJ7PXW9wO@stanza.co
SUMMARY:66ers @ Ports
DESCRIPTION:66ers @ Ports\n\nFollow on MiLB First Pitch: https://stza.co/+vLZ4-1L\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144534Z
LAST-MODIFIED:20180213T144534Z
TRANSP:OPAQUE
END:VEVENT
* 66ers @ Ports
<2018-07-23 Mon 21:10>--<2018-07-24 Tue 00:10>
:PROPERTIES:
:ID:       UChpNrgQwdf-31X18S6EqiSZ@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

66ers @ Ports 66ers @ Ports

Follow on MiLB First Pitch  https //stza.co/+vLZ5-30

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:66ers @ Ports
END:VALARM
DTSTART:20180724T021000Z
DTEND:20180724T051000Z
UID:UChpNrgQwdf-31X18S6EqiSZ@stanza.co
SUMMARY:66ers @ Ports
DESCRIPTION:66ers @ Ports\n\nFollow on MiLB First Pitch: https://stza.co/+vLZ5-30\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144534Z
LAST-MODIFIED:20180213T144534Z
TRANSP:OPAQUE
END:VEVENT
* 66ers vs. Rawhide
<2018-07-24 Tue 21:05>--<2018-07-25 Wed 00:05>
:PROPERTIES:
:ID:       dbCog0CTd8KYqPwxiUfXRkhP@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

66ers vs. Rawhide 66ers vs. Rawhide

Follow on MiLB First Pitch  https //stza.co/+y0AB-e

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:66ers vs. Rawhide
END:VALARM
DTSTART:20180725T020500Z
DTEND:20180725T050500Z
UID:dbCog0CTd8KYqPwxiUfXRkhP@stanza.co
SUMMARY:66ers vs. Rawhide
DESCRIPTION:66ers vs. Rawhide\n\nFollow on MiLB First Pitch: https://stza.co/+y0AB-e\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144534Z
LAST-MODIFIED:20180213T144534Z
TRANSP:OPAQUE
END:VEVENT
* 66ers vs. Rawhide
<2018-07-25 Wed 21:05>--<2018-07-26 Thu 00:05>
:PROPERTIES:
:ID:       a3aDn3At26DMmbXzrQKyF_-U@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

66ers vs. Rawhide 66ers vs. Rawhide

Follow on MiLB First Pitch  https //stza.co/+y0AD-6

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:66ers vs. Rawhide
END:VALARM
DTSTART:20180726T020500Z
DTEND:20180726T050500Z
UID:a3aDn3At26DMmbXzrQKyF_-U@stanza.co
SUMMARY:66ers vs. Rawhide
DESCRIPTION:66ers vs. Rawhide\n\nFollow on MiLB First Pitch: https://stza.co/+y0AD-6\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144534Z
LAST-MODIFIED:20180213T144534Z
TRANSP:OPAQUE
END:VEVENT
* 66ers vs. Rawhide
<2018-07-26 Thu 21:05>--<2018-07-27 Fri 00:05>
:PROPERTIES:
:ID:       s_2-lJrVPtGyoftrbDAxgaJU@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

66ers vs. Rawhide 66ers vs. Rawhide

Follow on MiLB First Pitch  https //stza.co/+y0AG-3Q

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:66ers vs. Rawhide
END:VALARM
DTSTART:20180727T020500Z
DTEND:20180727T050500Z
UID:s_2-lJrVPtGyoftrbDAxgaJU@stanza.co
SUMMARY:66ers vs. Rawhide
DESCRIPTION:66ers vs. Rawhide\n\nFollow on MiLB First Pitch: https://stza.co/+y0AG-3Q\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144534Z
LAST-MODIFIED:20180213T144534Z
TRANSP:OPAQUE
END:VEVENT
* 66ers @ Giants
<2018-07-27 Fri 21:00>--<2018-07-28 Sat 00:00>
:PROPERTIES:
:ID:       v6M0G6bXOhcJPQ_wPbNVEIyY@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

66ers @ Giants 66ers @ Giants

Follow on MiLB First Pitch  https //stza.co/+xEVM-1E

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:66ers @ Giants
END:VALARM
DTSTART:20180728T020000Z
DTEND:20180728T050000Z
UID:v6M0G6bXOhcJPQ_wPbNVEIyY@stanza.co
SUMMARY:66ers @ Giants
DESCRIPTION:66ers @ Giants\n\nFollow on MiLB First Pitch: https://stza.co/+xEVM-1E\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144534Z
LAST-MODIFIED:20180213T144534Z
TRANSP:OPAQUE
END:VEVENT
* 66ers @ Giants
<2018-07-28 Sat 20:00-23:00>
:PROPERTIES:
:ID:       gUiXGH8cAa-10Cr_mwk1154i@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

66ers @ Giants 66ers @ Giants

Follow on MiLB First Pitch  https //stza.co/+xEVN-8

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:66ers @ Giants
END:VALARM
DTSTART:20180729T010000Z
DTEND:20180729T040000Z
UID:gUiXGH8cAa-10Cr_mwk1154i@stanza.co
SUMMARY:66ers @ Giants
DESCRIPTION:66ers @ Giants\n\nFollow on MiLB First Pitch: https://stza.co/+xEVN-8\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144534Z
LAST-MODIFIED:20180213T144534Z
TRANSP:OPAQUE
END:VEVENT
* 66ers @ Giants
<2018-07-29 Sun 19:00-22:00>
:PROPERTIES:
:ID:       os2bSbN-rou8P0T1wzrnbCEy@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

66ers @ Giants 66ers @ Giants

Follow on MiLB First Pitch  https //stza.co/+xEVO-1P

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:66ers @ Giants
END:VALARM
DTSTART:20180730T000000Z
DTEND:20180730T030000Z
UID:os2bSbN-rou8P0T1wzrnbCEy@stanza.co
SUMMARY:66ers @ Giants
DESCRIPTION:66ers @ Giants\n\nFollow on MiLB First Pitch: https://stza.co/+xEVO-1P\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144534Z
LAST-MODIFIED:20180213T144534Z
TRANSP:OPAQUE
END:VEVENT
* 66ers vs. JetHawks
<2018-07-31 Tue 21:05>--<2018-08-01 Wed 00:05>
:PROPERTIES:
:ID:       rypcHVkXk5D54ClJpnhBnpsw@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

66ers vs. JetHawks 66ers vs. JetHawks

Follow on MiLB First Pitch  https //stza.co/+y0AH-C

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:66ers vs. JetHawks
END:VALARM
DTSTART:20180801T020500Z
DTEND:20180801T050500Z
UID:rypcHVkXk5D54ClJpnhBnpsw@stanza.co
SUMMARY:66ers vs. JetHawks
DESCRIPTION:66ers vs. JetHawks\n\nFollow on MiLB First Pitch: https://stza.co/+y0AH-C\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144534Z
LAST-MODIFIED:20180213T144534Z
TRANSP:OPAQUE
END:VEVENT
* 66ers vs. JetHawks
<2018-08-01 Wed 21:05>--<2018-08-02 Thu 00:05>
:PROPERTIES:
:ID:       ravBQTFujWS4h2_3ZZtOzinQ@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

66ers vs. JetHawks 66ers vs. JetHawks

Follow on MiLB First Pitch  https //stza.co/+y0AK-2V

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:66ers vs. JetHawks
END:VALARM
DTSTART:20180802T020500Z
DTEND:20180802T050500Z
UID:ravBQTFujWS4h2_3ZZtOzinQ@stanza.co
SUMMARY:66ers vs. JetHawks
DESCRIPTION:66ers vs. JetHawks\n\nFollow on MiLB First Pitch: https://stza.co/+y0AK-2V\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144534Z
LAST-MODIFIED:20180213T144534Z
TRANSP:OPAQUE
END:VEVENT
* 66ers vs. JetHawks
<2018-08-02 Thu 21:05>--<2018-08-03 Fri 00:05>
:PROPERTIES:
:ID:       8-7XQyLpm_yuhTkqNNhOiLE-@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

66ers vs. JetHawks 66ers vs. JetHawks

Follow on MiLB First Pitch  https //stza.co/+y0AM-2S

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:66ers vs. JetHawks
END:VALARM
DTSTART:20180803T020500Z
DTEND:20180803T050500Z
UID:8-7XQyLpm_yuhTkqNNhOiLE-@stanza.co
SUMMARY:66ers vs. JetHawks
DESCRIPTION:66ers vs. JetHawks\n\nFollow on MiLB First Pitch: https://stza.co/+y0AM-2S\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144534Z
LAST-MODIFIED:20180213T144534Z
TRANSP:OPAQUE
END:VEVENT
* 66ers vs. Nuts
<2018-08-03 Fri 21:05>--<2018-08-04 Sat 00:05>
:PROPERTIES:
:ID:       TnzUOgY7-TEPLgkAhIoudVdX@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

66ers vs. Nuts 66ers vs. Nuts

Follow on MiLB First Pitch  https //stza.co/+y0AO-11

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:66ers vs. Nuts
END:VALARM
DTSTART:20180804T020500Z
DTEND:20180804T050500Z
UID:TnzUOgY7-TEPLgkAhIoudVdX@stanza.co
SUMMARY:66ers vs. Nuts
DESCRIPTION:66ers vs. Nuts\n\nFollow on MiLB First Pitch: https://stza.co/+y0AO-11\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144534Z
LAST-MODIFIED:20180213T144534Z
TRANSP:OPAQUE
END:VEVENT
* 66ers vs. Nuts
<2018-08-04 Sat 20:05-23:05>
:PROPERTIES:
:ID:       p8uETqRnN8wN1r3QQAHOGdQq@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

66ers vs. Nuts 66ers vs. Nuts

Follow on MiLB First Pitch  https //stza.co/+y0AQ-3x

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:66ers vs. Nuts
END:VALARM
DTSTART:20180805T010500Z
DTEND:20180805T040500Z
UID:p8uETqRnN8wN1r3QQAHOGdQq@stanza.co
SUMMARY:66ers vs. Nuts
DESCRIPTION:66ers vs. Nuts\n\nFollow on MiLB First Pitch: https://stza.co/+y0AQ-3x\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144534Z
LAST-MODIFIED:20180213T144534Z
TRANSP:OPAQUE
END:VEVENT
* 66ers vs. Nuts
<2018-08-05 Sun 19:35-22:35>
:PROPERTIES:
:ID:       zhoFqGldjFn-MuYJkuY4sm8L@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

66ers vs. Nuts 66ers vs. Nuts

Follow on MiLB First Pitch  https //stza.co/+y0AR-9

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:66ers vs. Nuts
END:VALARM
DTSTART:20180806T003500Z
DTEND:20180806T033500Z
UID:zhoFqGldjFn-MuYJkuY4sm8L@stanza.co
SUMMARY:66ers vs. Nuts
DESCRIPTION:66ers vs. Nuts\n\nFollow on MiLB First Pitch: https://stza.co/+y0AR-9\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144534Z
LAST-MODIFIED:20180213T144534Z
TRANSP:OPAQUE
END:VEVENT
* 66ers @ JetHawks
<2018-08-07 Tue 20:35-23:35>
:PROPERTIES:
:ID:       kmGLSS_IS89TKePpghMOneJi@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

66ers @ JetHawks 66ers @ JetHawks

Follow on MiLB First Pitch  https //stza.co/+vLYA-3v

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:66ers @ JetHawks
END:VALARM
DTSTART:20180808T013500Z
DTEND:20180808T043500Z
UID:kmGLSS_IS89TKePpghMOneJi@stanza.co
SUMMARY:66ers @ JetHawks
DESCRIPTION:66ers @ JetHawks\n\nFollow on MiLB First Pitch: https://stza.co/+vLYA-3v\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144534Z
LAST-MODIFIED:20180213T144534Z
TRANSP:OPAQUE
END:VEVENT
* 66ers @ JetHawks
<2018-08-08 Wed 20:35-23:35>
:PROPERTIES:
:ID:       PA_X9UjW_L6AFCcDlMGNwmhZ@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

66ers @ JetHawks 66ers @ JetHawks

Follow on MiLB First Pitch  https //stza.co/+vLYB-2D

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:66ers @ JetHawks
END:VALARM
DTSTART:20180809T013500Z
DTEND:20180809T043500Z
UID:PA_X9UjW_L6AFCcDlMGNwmhZ@stanza.co
SUMMARY:66ers @ JetHawks
DESCRIPTION:66ers @ JetHawks\n\nFollow on MiLB First Pitch: https://stza.co/+vLYB-2D\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144534Z
LAST-MODIFIED:20180213T144534Z
TRANSP:OPAQUE
END:VEVENT
* 66ers @ JetHawks
<2018-08-09 Thu 20:35-23:35>
:PROPERTIES:
:ID:       _6l1uePNFDLDIwfqhSP3emqQ@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

66ers @ JetHawks 66ers @ JetHawks

Follow on MiLB First Pitch  https //stza.co/+vLYC-3p

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:66ers @ JetHawks
END:VALARM
DTSTART:20180810T013500Z
DTEND:20180810T043500Z
UID:_6l1uePNFDLDIwfqhSP3emqQ@stanza.co
SUMMARY:66ers @ JetHawks
DESCRIPTION:66ers @ JetHawks\n\nFollow on MiLB First Pitch: https://stza.co/+vLYC-3p\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144534Z
LAST-MODIFIED:20180213T144534Z
TRANSP:OPAQUE
END:VEVENT
* 66ers vs. Storm
<2018-08-10 Fri 21:05>--<2018-08-11 Sat 00:05>
:PROPERTIES:
:ID:       0H7r98ZUUOL3Z0RRHrGwHR8k@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

66ers vs. Storm 66ers vs. Storm

Follow on MiLB First Pitch  https //stza.co/+y0AU-2q

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:66ers vs. Storm
END:VALARM
DTSTART:20180811T020500Z
DTEND:20180811T050500Z
UID:0H7r98ZUUOL3Z0RRHrGwHR8k@stanza.co
SUMMARY:66ers vs. Storm
DESCRIPTION:66ers vs. Storm\n\nFollow on MiLB First Pitch: https://stza.co/+y0AU-2q\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144534Z
LAST-MODIFIED:20180213T144534Z
TRANSP:OPAQUE
END:VEVENT
* 66ers vs. Storm
<2018-08-11 Sat 20:05-23:05>
:PROPERTIES:
:ID:       jY9vFAabnI9Nb2wQPvkIDxzi@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

66ers vs. Storm 66ers vs. Storm

Follow on MiLB First Pitch  https //stza.co/+y0AV-1l

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:66ers vs. Storm
END:VALARM
DTSTART:20180812T010500Z
DTEND:20180812T040500Z
UID:jY9vFAabnI9Nb2wQPvkIDxzi@stanza.co
SUMMARY:66ers vs. Storm
DESCRIPTION:66ers vs. Storm\n\nFollow on MiLB First Pitch: https://stza.co/+y0AV-1l\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144534Z
LAST-MODIFIED:20180213T144534Z
TRANSP:OPAQUE
END:VEVENT
* 66ers vs. Storm
<2018-08-12 Sun 19:35-22:35>
:PROPERTIES:
:ID:       VSYf60aDnzRGS_PHPEYAegGg@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

66ers vs. Storm 66ers vs. Storm

Follow on MiLB First Pitch  https //stza.co/+y0AX-3s

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:66ers vs. Storm
END:VALARM
DTSTART:20180813T003500Z
DTEND:20180813T033500Z
UID:VSYf60aDnzRGS_PHPEYAegGg@stanza.co
SUMMARY:66ers vs. Storm
DESCRIPTION:66ers vs. Storm\n\nFollow on MiLB First Pitch: https://stza.co/+y0AX-3s\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144534Z
LAST-MODIFIED:20180213T144534Z
TRANSP:OPAQUE
END:VEVENT
* 66ers vs. Giants
<2018-08-13 Mon 21:05>--<2018-08-14 Tue 00:05>
:PROPERTIES:
:ID:       6o3tkFuFJD0imrMLRWC7EUSx@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

66ers vs. Giants 66ers vs. Giants

Follow on MiLB First Pitch  https //stza.co/+y0A_-X

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:66ers vs. Giants
END:VALARM
DTSTART:20180814T020500Z
DTEND:20180814T050500Z
UID:6o3tkFuFJD0imrMLRWC7EUSx@stanza.co
SUMMARY:66ers vs. Giants
DESCRIPTION:66ers vs. Giants\n\nFollow on MiLB First Pitch: https://stza.co/+y0A_-X\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144534Z
LAST-MODIFIED:20180213T144534Z
TRANSP:OPAQUE
END:VEVENT
* 66ers vs. Giants
<2018-08-14 Tue 21:05>--<2018-08-15 Wed 00:05>
:PROPERTIES:
:ID:       53wZ26NmRamt6b_1F5Tz9AlU@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

66ers vs. Giants 66ers vs. Giants

Follow on MiLB First Pitch  https //stza.co/+y0B1-1P

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:66ers vs. Giants
END:VALARM
DTSTART:20180815T020500Z
DTEND:20180815T050500Z
UID:53wZ26NmRamt6b_1F5Tz9AlU@stanza.co
SUMMARY:66ers vs. Giants
DESCRIPTION:66ers vs. Giants\n\nFollow on MiLB First Pitch: https://stza.co/+y0B1-1P\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144534Z
LAST-MODIFIED:20180213T144534Z
TRANSP:OPAQUE
END:VEVENT
* 66ers vs. Giants
<2018-08-15 Wed 21:05>--<2018-08-16 Thu 00:05>
:PROPERTIES:
:ID:       VRM1Sc6D7xtcJdj3RQFui_TP@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

66ers vs. Giants 66ers vs. Giants

Follow on MiLB First Pitch  https //stza.co/+y0B3-1W

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:66ers vs. Giants
END:VALARM
DTSTART:20180816T020500Z
DTEND:20180816T050500Z
UID:VRM1Sc6D7xtcJdj3RQFui_TP@stanza.co
SUMMARY:66ers vs. Giants
DESCRIPTION:66ers vs. Giants\n\nFollow on MiLB First Pitch: https://stza.co/+y0B3-1W\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144534Z
LAST-MODIFIED:20180213T144534Z
TRANSP:OPAQUE
END:VEVENT
* 66ers @ Nuts
<2018-08-17 Fri 21:05>--<2018-08-18 Sat 00:05>
:PROPERTIES:
:ID:       BbqROb6UgTptGGvaA7TpT2g0@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

66ers @ Nuts 66ers @ Nuts

Follow on MiLB First Pitch  https //stza.co/+xAKi-2$

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:66ers @ Nuts
END:VALARM
DTSTART:20180818T020500Z
DTEND:20180818T050500Z
UID:BbqROb6UgTptGGvaA7TpT2g0@stanza.co
SUMMARY:66ers @ Nuts
DESCRIPTION:66ers @ Nuts\n\nFollow on MiLB First Pitch: https://stza.co/+xAKi-2$\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144534Z
LAST-MODIFIED:20180213T144534Z
TRANSP:OPAQUE
END:VEVENT
* 66ers @ Nuts
<2018-08-18 Sat 21:05>--<2018-08-19 Sun 00:05>
:PROPERTIES:
:ID:       hD9BUJHwQ12EoXfgu1ZFLiR5@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

66ers @ Nuts 66ers @ Nuts

Follow on MiLB First Pitch  https //stza.co/+xAKk-3z

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:66ers @ Nuts
END:VALARM
DTSTART:20180819T020500Z
DTEND:20180819T050500Z
UID:hD9BUJHwQ12EoXfgu1ZFLiR5@stanza.co
SUMMARY:66ers @ Nuts
DESCRIPTION:66ers @ Nuts\n\nFollow on MiLB First Pitch: https://stza.co/+xAKk-3z\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144534Z
LAST-MODIFIED:20180213T144534Z
TRANSP:OPAQUE
END:VEVENT
* 66ers @ Nuts
<2018-08-19 Sun 20:05-23:05>
:PROPERTIES:
:ID:       BZJk_9UwcKd2m90eR9kgVYIL@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

66ers @ Nuts 66ers @ Nuts

Follow on MiLB First Pitch  https //stza.co/+xAKl-3w

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:66ers @ Nuts
END:VALARM
DTSTART:20180820T010500Z
DTEND:20180820T040500Z
UID:BZJk_9UwcKd2m90eR9kgVYIL@stanza.co
SUMMARY:66ers @ Nuts
DESCRIPTION:66ers @ Nuts\n\nFollow on MiLB First Pitch: https://stza.co/+xAKl-3w\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144534Z
LAST-MODIFIED:20180213T144534Z
TRANSP:OPAQUE
END:VEVENT
* 66ers @ Storm
<2018-08-21 Tue 20:00-23:00>
:PROPERTIES:
:ID:       MCs4mvVN6wKkduNdIcA3-Kkv@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

66ers @ Storm 66ers @ Storm

Follow on MiLB First Pitch  https //stza.co/+xAKb-2g

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:66ers @ Storm
END:VALARM
DTSTART:20180822T010000Z
DTEND:20180822T040000Z
UID:MCs4mvVN6wKkduNdIcA3-Kkv@stanza.co
SUMMARY:66ers @ Storm
DESCRIPTION:66ers @ Storm\n\nFollow on MiLB First Pitch: https://stza.co/+xAKb-2g\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144534Z
LAST-MODIFIED:20180213T144534Z
TRANSP:OPAQUE
END:VEVENT
* 66ers @ Storm
<2018-08-22 Wed 20:00-23:00>
:PROPERTIES:
:ID:       QPeA1CyWKG9KaMdwk6yz5Cm-@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

66ers @ Storm 66ers @ Storm

Follow on MiLB First Pitch  https //stza.co/+xAKc-1n

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:66ers @ Storm
END:VALARM
DTSTART:20180823T010000Z
DTEND:20180823T040000Z
UID:QPeA1CyWKG9KaMdwk6yz5Cm-@stanza.co
SUMMARY:66ers @ Storm
DESCRIPTION:66ers @ Storm\n\nFollow on MiLB First Pitch: https://stza.co/+xAKc-1n\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144534Z
LAST-MODIFIED:20180213T144534Z
TRANSP:OPAQUE
END:VEVENT
* 66ers @ Storm
<2018-08-23 Thu 21:00>--<2018-08-24 Fri 00:00>
:PROPERTIES:
:ID:       _0LTFevSUREyJ84iIq7uShF6@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

66ers @ Storm 66ers @ Storm

Follow on MiLB First Pitch  https //stza.co/+xAKd-3H

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:66ers @ Storm
END:VALARM
DTSTART:20180824T020000Z
DTEND:20180824T050000Z
UID:_0LTFevSUREyJ84iIq7uShF6@stanza.co
SUMMARY:66ers @ Storm
DESCRIPTION:66ers @ Storm\n\nFollow on MiLB First Pitch: https://stza.co/+xAKd-3H\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144534Z
LAST-MODIFIED:20180213T144534Z
TRANSP:OPAQUE
END:VEVENT
* 66ers vs. Quakes
<2018-08-24 Fri 21:05>--<2018-08-25 Sat 00:05>
:PROPERTIES:
:ID:       PgYoFvs8GhZJK4SGsvGO6Dsk@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

66ers vs. Quakes 66ers vs. Quakes

Follow on MiLB First Pitch  https //stza.co/+y0B5-2B

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:66ers vs. Quakes
END:VALARM
DTSTART:20180825T020500Z
DTEND:20180825T050500Z
UID:PgYoFvs8GhZJK4SGsvGO6Dsk@stanza.co
SUMMARY:66ers vs. Quakes
DESCRIPTION:66ers vs. Quakes\n\nFollow on MiLB First Pitch: https://stza.co/+y0B5-2B\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144534Z
LAST-MODIFIED:20180213T144534Z
TRANSP:OPAQUE
END:VEVENT
* 66ers vs. Quakes
<2018-08-25 Sat 20:05-23:05>
:PROPERTIES:
:ID:       GQ8OirQPNkgFzPCYtSPniQbI@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

66ers vs. Quakes 66ers vs. Quakes

Follow on MiLB First Pitch  https //stza.co/+y0B6-G

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:66ers vs. Quakes
END:VALARM
DTSTART:20180826T010500Z
DTEND:20180826T040500Z
UID:GQ8OirQPNkgFzPCYtSPniQbI@stanza.co
SUMMARY:66ers vs. Quakes
DESCRIPTION:66ers vs. Quakes\n\nFollow on MiLB First Pitch: https://stza.co/+y0B6-G\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144534Z
LAST-MODIFIED:20180213T144534Z
TRANSP:OPAQUE
END:VEVENT
* 66ers vs. Quakes
<2018-08-26 Sun 19:35-22:35>
:PROPERTIES:
:ID:       ZEnRHO5mcSXIIvT2oDJHpICL@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

66ers vs. Quakes 66ers vs. Quakes

Follow on MiLB First Pitch  https //stza.co/+y0B8-1v

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:66ers vs. Quakes
END:VALARM
DTSTART:20180827T003500Z
DTEND:20180827T033500Z
UID:ZEnRHO5mcSXIIvT2oDJHpICL@stanza.co
SUMMARY:66ers vs. Quakes
DESCRIPTION:66ers vs. Quakes\n\nFollow on MiLB First Pitch: https://stza.co/+y0B8-1v\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144534Z
LAST-MODIFIED:20180213T144534Z
TRANSP:OPAQUE
END:VEVENT
* 66ers vs. Quakes
<2018-08-27 Mon 21:05>--<2018-08-28 Tue 00:05>
:PROPERTIES:
:ID:       uUoj2fPPsp6kP7_X2eMKhk9o@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

66ers vs. Quakes 66ers vs. Quakes

Follow on MiLB First Pitch  https //stza.co/+y0Bb-V

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:66ers vs. Quakes
END:VALARM
DTSTART:20180828T020500Z
DTEND:20180828T050500Z
UID:uUoj2fPPsp6kP7_X2eMKhk9o@stanza.co
SUMMARY:66ers vs. Quakes
DESCRIPTION:66ers vs. Quakes\n\nFollow on MiLB First Pitch: https://stza.co/+y0Bb-V\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144534Z
LAST-MODIFIED:20180213T144534Z
TRANSP:OPAQUE
END:VEVENT
* 66ers vs. Storm
<2018-08-28 Tue 21:05>--<2018-08-29 Wed 00:05>
:PROPERTIES:
:ID:       9OMhAs53JHZRmQtZKAL39ypD@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

66ers vs. Storm 66ers vs. Storm

Follow on MiLB First Pitch  https //stza.co/+y0Bc-_

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:66ers vs. Storm
END:VALARM
DTSTART:20180829T020500Z
DTEND:20180829T050500Z
UID:9OMhAs53JHZRmQtZKAL39ypD@stanza.co
SUMMARY:66ers vs. Storm
DESCRIPTION:66ers vs. Storm\n\nFollow on MiLB First Pitch: https://stza.co/+y0Bc-_\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144534Z
LAST-MODIFIED:20180213T144534Z
TRANSP:OPAQUE
END:VEVENT
* 66ers vs. Storm
<2018-08-29 Wed 21:05>--<2018-08-30 Thu 00:05>
:PROPERTIES:
:ID:       cagSZujBp0Zwl7dFyX89GRJk@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

66ers vs. Storm 66ers vs. Storm

Follow on MiLB First Pitch  https //stza.co/+y0Be-1h

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:66ers vs. Storm
END:VALARM
DTSTART:20180830T020500Z
DTEND:20180830T050500Z
UID:cagSZujBp0Zwl7dFyX89GRJk@stanza.co
SUMMARY:66ers vs. Storm
DESCRIPTION:66ers vs. Storm\n\nFollow on MiLB First Pitch: https://stza.co/+y0Be-1h\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144534Z
LAST-MODIFIED:20180213T144534Z
TRANSP:OPAQUE
END:VEVENT
* 66ers vs. Storm
<2018-08-30 Thu 21:05>--<2018-08-31 Fri 00:05>
:PROPERTIES:
:ID:       Jn2abWcOFkGeswCPD0kBsPIJ@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

66ers vs. Storm 66ers vs. Storm

Follow on MiLB First Pitch  https //stza.co/+y0Bg-3a

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:66ers vs. Storm
END:VALARM
DTSTART:20180831T020500Z
DTEND:20180831T050500Z
UID:Jn2abWcOFkGeswCPD0kBsPIJ@stanza.co
SUMMARY:66ers vs. Storm
DESCRIPTION:66ers vs. Storm\n\nFollow on MiLB First Pitch: https://stza.co/+y0Bg-3a\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144534Z
LAST-MODIFIED:20180213T144534Z
TRANSP:OPAQUE
END:VEVENT
* 66ers @ Quakes
<2018-08-31 Fri 21:05>--<2018-09-01 Sat 00:05>
:PROPERTIES:
:ID:       R_UVnRMSh0bVYjOHUTVOsh1h@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

66ers @ Quakes 66ers @ Quakes

Follow on MiLB First Pitch  https //stza.co/+xAKz-3O

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:66ers @ Quakes
END:VALARM
DTSTART:20180901T020500Z
DTEND:20180901T050500Z
UID:R_UVnRMSh0bVYjOHUTVOsh1h@stanza.co
SUMMARY:66ers @ Quakes
DESCRIPTION:66ers @ Quakes\n\nFollow on MiLB First Pitch: https://stza.co/+xAKz-3O\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144534Z
LAST-MODIFIED:20180213T144534Z
TRANSP:OPAQUE
END:VEVENT
* 66ers @ Quakes
<2018-09-01 Sat 21:05>--<2018-09-02 Sun 00:05>
:PROPERTIES:
:ID:       zr3uBg8lSm8YOMt9Z8-wPD9Z@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

66ers @ Quakes 66ers @ Quakes

Follow on MiLB First Pitch  https //stza.co/+xAKA-3F

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:66ers @ Quakes
END:VALARM
DTSTART:20180902T020500Z
DTEND:20180902T050500Z
UID:zr3uBg8lSm8YOMt9Z8-wPD9Z@stanza.co
SUMMARY:66ers @ Quakes
DESCRIPTION:66ers @ Quakes\n\nFollow on MiLB First Pitch: https://stza.co/+xAKA-3F\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144534Z
LAST-MODIFIED:20180213T144534Z
TRANSP:OPAQUE
END:VEVENT
* 66ers @ Quakes
<2018-09-02 Sun 16:05-19:05>
:PROPERTIES:
:ID:       ZHh3CPWTsr1XgpERiuWz6T6x@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

66ers @ Quakes 66ers @ Quakes

Follow on MiLB First Pitch  https //stza.co/+xAKB-2l

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:66ers @ Quakes
END:VALARM
DTSTART:20180902T210500Z
DTEND:20180903T000500Z
UID:ZHh3CPWTsr1XgpERiuWz6T6x@stanza.co
SUMMARY:66ers @ Quakes
DESCRIPTION:66ers @ Quakes\n\nFollow on MiLB First Pitch: https://stza.co/+xAKB-2l\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144534Z
LAST-MODIFIED:20180213T144534Z
TRANSP:OPAQUE
END:VEVENT
* 66ers @ Quakes
<2018-09-03 Mon 16:05-19:05>
:PROPERTIES:
:ID:       wmt3xE2VeHzA7o_UbNpQtBfy@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

66ers @ Quakes 66ers @ Quakes

Follow on MiLB First Pitch  https //stza.co/+xAKF-B

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:66ers @ Quakes
END:VALARM
DTSTART:20180903T210500Z
DTEND:20180904T000500Z
UID:wmt3xE2VeHzA7o_UbNpQtBfy@stanza.co
SUMMARY:66ers @ Quakes
DESCRIPTION:66ers @ Quakes\n\nFollow on MiLB First Pitch: https://stza.co/+xAKF-B\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144534Z
LAST-MODIFIED:20180213T144534Z
TRANSP:OPAQUE
END:VEVENT
