#+TITLE:       Main Google calendar entries
#+AUTHOR:      Eric S Fraga
#+EMAIL:       e.fraga@ucl.ac.uk
#+DESCRIPTION: converted using the ical2org awk script
#+CATEGORY:    google
#+STARTUP:     hidestars
#+STARTUP:     overview

* COMMENT original iCal preamble

* RockHounds vs. Cardinals
<2018-04-05 Thu 19:00-22:00>
:PROPERTIES:
:ID:       zMkCrpM1Er2wTEa00QVviaPa@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

RockHounds vs. Cardinals RockHounds vs. Cardinals

Follow on MiLB First Pitch  https //stza.co/+wX1Y-3l

Shop  https //stza.co/+wX1Y-3p

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:RockHounds vs. Cardinals
END:VALARM
DTSTART:20180406T000000Z
DTEND:20180406T030000Z
UID:zMkCrpM1Er2wTEa00QVviaPa@stanza.co
SUMMARY:RockHounds vs. Cardinals
DESCRIPTION:RockHounds vs. Cardinals\n\nFollow on MiLB First Pitch: https://stza.co/+wX1Y-3l\n\nShop: https://stza.co/+wX1Y-3p\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144543Z
LAST-MODIFIED:20180213T144543Z
TRANSP:OPAQUE
END:VEVENT
* RockHounds vs. Cardinals
<2018-04-06 Fri 19:00-22:00>
:PROPERTIES:
:ID:       JNXDjXRtbWnRHiYJO0ZDyKQe@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

RockHounds vs. Cardinals RockHounds vs. Cardinals

Follow on MiLB First Pitch  https //stza.co/+wX1_-4

Shop  https //stza.co/+wX1_-7

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:RockHounds vs. Cardinals
END:VALARM
DTSTART:20180407T000000Z
DTEND:20180407T030000Z
UID:JNXDjXRtbWnRHiYJO0ZDyKQe@stanza.co
SUMMARY:RockHounds vs. Cardinals
DESCRIPTION:RockHounds vs. Cardinals\n\nFollow on MiLB First Pitch: https://stza.co/+wX1_-4\n\nShop: https://stza.co/+wX1_-7\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144543Z
LAST-MODIFIED:20180213T144543Z
TRANSP:OPAQUE
END:VEVENT
* RockHounds vs. Cardinals
<2018-04-07 Sat 19:00-22:00>
:PROPERTIES:
:ID:       AT8-zDFbqyIkHqKLkTomTVeC@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

RockHounds vs. Cardinals RockHounds vs. Cardinals

Follow on MiLB First Pitch  https //stza.co/+wX2b-1U

Shop  https //stza.co/+wX2b-1g

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:RockHounds vs. Cardinals
END:VALARM
DTSTART:20180408T000000Z
DTEND:20180408T030000Z
UID:AT8-zDFbqyIkHqKLkTomTVeC@stanza.co
SUMMARY:RockHounds vs. Cardinals
DESCRIPTION:RockHounds vs. Cardinals\n\nFollow on MiLB First Pitch: https://stza.co/+wX2b-1U\n\nShop: https://stza.co/+wX2b-1g\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144543Z
LAST-MODIFIED:20180213T144543Z
TRANSP:OPAQUE
END:VEVENT
* RockHounds vs. Drillers
<2018-04-08 Sun 16:00-19:00>
:PROPERTIES:
:ID:       gR1Z8e8pyJELJSSKiaIYHHdY@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

RockHounds vs. Drillers RockHounds vs. Drillers

Follow on MiLB First Pitch  https //stza.co/+wX2n-2E

Shop  https //stza.co/+wX2n-23

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:RockHounds vs. Drillers
END:VALARM
DTSTART:20180408T210000Z
DTEND:20180409T000000Z
UID:gR1Z8e8pyJELJSSKiaIYHHdY@stanza.co
SUMMARY:RockHounds vs. Drillers
DESCRIPTION:RockHounds vs. Drillers\n\nFollow on MiLB First Pitch: https://stza.co/+wX2n-2E\n\nShop: https://stza.co/+wX2n-23\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144543Z
LAST-MODIFIED:20180213T144543Z
TRANSP:OPAQUE
END:VEVENT
* RockHounds vs. Drillers
<2018-04-09 Mon 18:30-21:30>
:PROPERTIES:
:ID:       r9F3hhUU2XyvsFwYXMynrtGb@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

RockHounds vs. Drillers RockHounds vs. Drillers

Follow on MiLB First Pitch  https //stza.co/+wX2x-2f

Shop  https //stza.co/+wX2x-3q

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:RockHounds vs. Drillers
END:VALARM
DTSTART:20180409T233000Z
DTEND:20180410T023000Z
UID:r9F3hhUU2XyvsFwYXMynrtGb@stanza.co
SUMMARY:RockHounds vs. Drillers
DESCRIPTION:RockHounds vs. Drillers\n\nFollow on MiLB First Pitch: https://stza.co/+wX2x-2f\n\nShop: https://stza.co/+wX2x-3q\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144543Z
LAST-MODIFIED:20180213T144543Z
TRANSP:OPAQUE
END:VEVENT
* RockHounds vs. Drillers
<2018-04-10 Tue 18:30-21:30>
:PROPERTIES:
:ID:       ev8phW84HLR_6tnUCT7wPM7X@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

RockHounds vs. Drillers RockHounds vs. Drillers

Follow on MiLB First Pitch  https //stza.co/+wX2y-3D

Shop  https //stza.co/+wX2y-2G

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:RockHounds vs. Drillers
END:VALARM
DTSTART:20180410T233000Z
DTEND:20180411T023000Z
UID:ev8phW84HLR_6tnUCT7wPM7X@stanza.co
SUMMARY:RockHounds vs. Drillers
DESCRIPTION:RockHounds vs. Drillers\n\nFollow on MiLB First Pitch: https://stza.co/+wX2y-3D\n\nShop: https://stza.co/+wX2y-2G\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144543Z
LAST-MODIFIED:20180213T144543Z
TRANSP:OPAQUE
END:VEVENT
* RockHounds @ Cardinals
<2018-04-12 Thu 19:10-22:10>
:PROPERTIES:
:ID:       tDOVcMXsmtb7qIuYI8ehLeDQ@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

RockHounds @ Cardinals RockHounds @ Cardinals

Follow on MiLB First Pitch  https //stza.co/+wPMY-3B

Shop  https //stza.co/+wPMY-2J

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:RockHounds @ Cardinals
END:VALARM
DTSTART:20180413T001000Z
DTEND:20180413T031000Z
UID:tDOVcMXsmtb7qIuYI8ehLeDQ@stanza.co
SUMMARY:RockHounds @ Cardinals
DESCRIPTION:RockHounds @ Cardinals\n\nFollow on MiLB First Pitch: https://stza.co/+wPMY-3B\n\nShop: https://stza.co/+wPMY-2J\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144543Z
LAST-MODIFIED:20180213T144543Z
TRANSP:OPAQUE
END:VEVENT
* RockHounds @ Cardinals
<2018-04-13 Fri 19:10-22:10>
:PROPERTIES:
:ID:       AtQNxavKZSHltW0Jpjj1I7Za@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

RockHounds @ Cardinals RockHounds @ Cardinals

Follow on MiLB First Pitch  https //stza.co/+wPMZ-x

Shop  https //stza.co/+wPMZ-P

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:RockHounds @ Cardinals
END:VALARM
DTSTART:20180414T001000Z
DTEND:20180414T031000Z
UID:AtQNxavKZSHltW0Jpjj1I7Za@stanza.co
SUMMARY:RockHounds @ Cardinals
DESCRIPTION:RockHounds @ Cardinals\n\nFollow on MiLB First Pitch: https://stza.co/+wPMZ-x\n\nShop: https://stza.co/+wPMZ-P\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144543Z
LAST-MODIFIED:20180213T144543Z
TRANSP:OPAQUE
END:VEVENT
* RockHounds @ Cardinals
<2018-04-14 Sat 14:10-17:10>
:PROPERTIES:
:ID:       3jyMf9_l10tepvPWm7Xstwgz@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

RockHounds @ Cardinals RockHounds @ Cardinals

Follow on MiLB First Pitch  https //stza.co/+wPM$-3z

Shop  https //stza.co/+wPM$-3G

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:RockHounds @ Cardinals
END:VALARM
DTSTART:20180414T191000Z
DTEND:20180414T221000Z
UID:3jyMf9_l10tepvPWm7Xstwgz@stanza.co
SUMMARY:RockHounds @ Cardinals
DESCRIPTION:RockHounds @ Cardinals\n\nFollow on MiLB First Pitch: https://stza.co/+wPM$-3z\n\nShop: https://stza.co/+wPM$-3G\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144543Z
LAST-MODIFIED:20180213T144543Z
TRANSP:OPAQUE
END:VEVENT
* RockHounds @ Drillers
<2018-04-15 Sun 16:05-19:05>
:PROPERTIES:
:ID:       GRiZJJ5XXqFc1oZuO39Kmaeo@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

RockHounds @ Drillers RockHounds @ Drillers

Follow on MiLB First Pitch  https //stza.co/+w03E-R

Shop  https //stza.co/+w03E-2x

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:RockHounds @ Drillers
END:VALARM
DTSTART:20180415T210500Z
DTEND:20180416T000500Z
UID:GRiZJJ5XXqFc1oZuO39Kmaeo@stanza.co
SUMMARY:RockHounds @ Drillers
DESCRIPTION:RockHounds @ Drillers\n\nFollow on MiLB First Pitch: https://stza.co/+w03E-R\n\nShop: https://stza.co/+w03E-2x\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144543Z
LAST-MODIFIED:20180213T144543Z
TRANSP:OPAQUE
END:VEVENT
* RockHounds @ Drillers
<2018-04-16 Mon 16:05-19:05>
:PROPERTIES:
:ID:       BdI4AIF-kOTnK0ysw9jbuY-C@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

RockHounds @ Drillers RockHounds @ Drillers

Follow on MiLB First Pitch  https //stza.co/+w03F-2V

Shop  https //stza.co/+w03F-1x

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:RockHounds @ Drillers
END:VALARM
DTSTART:20180416T210500Z
DTEND:20180417T000500Z
UID:BdI4AIF-kOTnK0ysw9jbuY-C@stanza.co
SUMMARY:RockHounds @ Drillers
DESCRIPTION:RockHounds @ Drillers\n\nFollow on MiLB First Pitch: https://stza.co/+w03F-2V\n\nShop: https://stza.co/+w03F-1x\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144543Z
LAST-MODIFIED:20180213T144543Z
TRANSP:OPAQUE
END:VEVENT
* RockHounds @ Drillers
<2018-04-17 Tue 19:05-22:05>
:PROPERTIES:
:ID:       6GLnMIEIOPzJfFNUGinl17hF@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

RockHounds @ Drillers RockHounds @ Drillers

Follow on MiLB First Pitch  https //stza.co/+w03G-3X

Shop  https //stza.co/+w03G-2d

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:RockHounds @ Drillers
END:VALARM
DTSTART:20180418T000500Z
DTEND:20180418T030500Z
UID:6GLnMIEIOPzJfFNUGinl17hF@stanza.co
SUMMARY:RockHounds @ Drillers
DESCRIPTION:RockHounds @ Drillers\n\nFollow on MiLB First Pitch: https://stza.co/+w03G-3X\n\nShop: https://stza.co/+w03G-2d\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144543Z
LAST-MODIFIED:20180213T144543Z
TRANSP:OPAQUE
END:VEVENT
* RockHounds vs. Missions
<2018-04-19 Thu 19:00-22:00>
:PROPERTIES:
:ID:       yusM0N7EB1IEYh09ajF7cksN@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

RockHounds vs. Missions RockHounds vs. Missions

Follow on MiLB First Pitch  https //stza.co/+wX2A-23

Shop  https //stza.co/+wX2A-3o

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:RockHounds vs. Missions
END:VALARM
DTSTART:20180420T000000Z
DTEND:20180420T030000Z
UID:yusM0N7EB1IEYh09ajF7cksN@stanza.co
SUMMARY:RockHounds vs. Missions
DESCRIPTION:RockHounds vs. Missions\n\nFollow on MiLB First Pitch: https://stza.co/+wX2A-23\n\nShop: https://stza.co/+wX2A-3o\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144543Z
LAST-MODIFIED:20180213T144543Z
TRANSP:OPAQUE
END:VEVENT
* RockHounds vs. Missions
<2018-04-20 Fri 19:00-22:00>
:PROPERTIES:
:ID:       kkzTfvsBAHaxZ1HV3Sjv3g3a@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

RockHounds vs. Missions RockHounds vs. Missions

Follow on MiLB First Pitch  https //stza.co/+wX2D-2R

Shop  https //stza.co/+wX2D-37

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:RockHounds vs. Missions
END:VALARM
DTSTART:20180421T000000Z
DTEND:20180421T030000Z
UID:kkzTfvsBAHaxZ1HV3Sjv3g3a@stanza.co
SUMMARY:RockHounds vs. Missions
DESCRIPTION:RockHounds vs. Missions\n\nFollow on MiLB First Pitch: https://stza.co/+wX2D-2R\n\nShop: https://stza.co/+wX2D-37\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144543Z
LAST-MODIFIED:20180213T144543Z
TRANSP:OPAQUE
END:VEVENT
* RockHounds vs. Missions
<2018-04-21 Sat 19:00-22:00>
:PROPERTIES:
:ID:       B-ZPEZt0vyzTpwoamkSGDKk1@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

RockHounds vs. Missions RockHounds vs. Missions

Follow on MiLB First Pitch  https //stza.co/+wX2F-2J

Shop  https //stza.co/+wX2F-F

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:RockHounds vs. Missions
END:VALARM
DTSTART:20180422T000000Z
DTEND:20180422T030000Z
UID:B-ZPEZt0vyzTpwoamkSGDKk1@stanza.co
SUMMARY:RockHounds vs. Missions
DESCRIPTION:RockHounds vs. Missions\n\nFollow on MiLB First Pitch: https://stza.co/+wX2F-2J\n\nShop: https://stza.co/+wX2F-F\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144543Z
LAST-MODIFIED:20180213T144543Z
TRANSP:OPAQUE
END:VEVENT
* RockHounds vs. Missions
<2018-04-22 Sun 14:00-17:00>
:PROPERTIES:
:ID:       3yJTBTXK5M4FzC-eaqOWDmv0@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

RockHounds vs. Missions RockHounds vs. Missions

Follow on MiLB First Pitch  https //stza.co/+wX2H-2N

Shop  https //stza.co/+wX2H-2H

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:RockHounds vs. Missions
END:VALARM
DTSTART:20180422T190000Z
DTEND:20180422T220000Z
UID:3yJTBTXK5M4FzC-eaqOWDmv0@stanza.co
SUMMARY:RockHounds vs. Missions
DESCRIPTION:RockHounds vs. Missions\n\nFollow on MiLB First Pitch: https://stza.co/+wX2H-2N\n\nShop: https://stza.co/+wX2H-2H\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144543Z
LAST-MODIFIED:20180213T144543Z
TRANSP:OPAQUE
END:VEVENT
* RockHounds @ Hooks
<2018-04-23 Mon 19:05-22:05>
:PROPERTIES:
:ID:       wNB24-zxd0dZ06dsErK1OZlR@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

RockHounds @ Hooks RockHounds @ Hooks

Follow on MiLB First Pitch  https //stza.co/+xzHz-3v

Shop  https //stza.co/+xzHz-2g

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:RockHounds @ Hooks
END:VALARM
DTSTART:20180424T000500Z
DTEND:20180424T030500Z
UID:wNB24-zxd0dZ06dsErK1OZlR@stanza.co
SUMMARY:RockHounds @ Hooks
DESCRIPTION:RockHounds @ Hooks\n\nFollow on MiLB First Pitch: https://stza.co/+xzHz-3v\n\nShop: https://stza.co/+xzHz-2g\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144543Z
LAST-MODIFIED:20180213T144543Z
TRANSP:OPAQUE
END:VEVENT
* RockHounds @ Hooks
<2018-04-24 Tue 19:05-22:05>
:PROPERTIES:
:ID:       0Te2GH5pBR_h43MYH0YlBJUQ@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

RockHounds @ Hooks RockHounds @ Hooks

Follow on MiLB First Pitch  https //stza.co/+xzHA-2v

Shop  https //stza.co/+xzHA-22

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:RockHounds @ Hooks
END:VALARM
DTSTART:20180425T000500Z
DTEND:20180425T030500Z
UID:0Te2GH5pBR_h43MYH0YlBJUQ@stanza.co
SUMMARY:RockHounds @ Hooks
DESCRIPTION:RockHounds @ Hooks\n\nFollow on MiLB First Pitch: https://stza.co/+xzHA-2v\n\nShop: https://stza.co/+xzHA-22\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144543Z
LAST-MODIFIED:20180213T144543Z
TRANSP:OPAQUE
END:VEVENT
* RockHounds @ Hooks
<2018-04-25 Wed 19:05-22:05>
:PROPERTIES:
:ID:       QNgyY_-BwPzg04JHX2cd5mso@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

RockHounds @ Hooks RockHounds @ Hooks

Follow on MiLB First Pitch  https //stza.co/+xzHB-3R

Shop  https //stza.co/+xzHB-1S

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:RockHounds @ Hooks
END:VALARM
DTSTART:20180426T000500Z
DTEND:20180426T030500Z
UID:QNgyY_-BwPzg04JHX2cd5mso@stanza.co
SUMMARY:RockHounds @ Hooks
DESCRIPTION:RockHounds @ Hooks\n\nFollow on MiLB First Pitch: https://stza.co/+xzHB-3R\n\nShop: https://stza.co/+xzHB-1S\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144543Z
LAST-MODIFIED:20180213T144543Z
TRANSP:OPAQUE
END:VEVENT
* RockHounds @ Hooks
<2018-04-26 Thu 19:05-22:05>
:PROPERTIES:
:ID:       OiBNX2jSmyNU-aGIO2jza7r0@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

RockHounds @ Hooks RockHounds @ Hooks

Follow on MiLB First Pitch  https //stza.co/+xzHC-Z

Shop  https //stza.co/+xzHC-X

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:RockHounds @ Hooks
END:VALARM
DTSTART:20180427T000500Z
DTEND:20180427T030500Z
UID:OiBNX2jSmyNU-aGIO2jza7r0@stanza.co
SUMMARY:RockHounds @ Hooks
DESCRIPTION:RockHounds @ Hooks\n\nFollow on MiLB First Pitch: https://stza.co/+xzHC-Z\n\nShop: https://stza.co/+xzHC-X\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144543Z
LAST-MODIFIED:20180213T144543Z
TRANSP:OPAQUE
END:VEVENT
* RockHounds @ Missions
<2018-04-27 Fri 19:05-22:05>
:PROPERTIES:
:ID:       M9VK3rvBZJqUzwUjLIr-Q7HI@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

RockHounds @ Missions RockHounds @ Missions

Follow on MiLB First Pitch  https //stza.co/+wMuH-3d

Shop  https //stza.co/+wMuH-13

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:RockHounds @ Missions
END:VALARM
DTSTART:20180428T000500Z
DTEND:20180428T030500Z
UID:M9VK3rvBZJqUzwUjLIr-Q7HI@stanza.co
SUMMARY:RockHounds @ Missions
DESCRIPTION:RockHounds @ Missions\n\nFollow on MiLB First Pitch: https://stza.co/+wMuH-3d\n\nShop: https://stza.co/+wMuH-13\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144543Z
LAST-MODIFIED:20180213T144543Z
TRANSP:OPAQUE
END:VEVENT
* RockHounds @ Missions
<2018-04-28 Sat 19:05-22:05>
:PROPERTIES:
:ID:       zZmXo4kTu318CR8oN-WGbLl9@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

RockHounds @ Missions RockHounds @ Missions

Follow on MiLB First Pitch  https //stza.co/+wMuI-13

Shop  https //stza.co/+wMuI-10

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:RockHounds @ Missions
END:VALARM
DTSTART:20180429T000500Z
DTEND:20180429T030500Z
UID:zZmXo4kTu318CR8oN-WGbLl9@stanza.co
SUMMARY:RockHounds @ Missions
DESCRIPTION:RockHounds @ Missions\n\nFollow on MiLB First Pitch: https://stza.co/+wMuI-13\n\nShop: https://stza.co/+wMuI-10\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144543Z
LAST-MODIFIED:20180213T144543Z
TRANSP:OPAQUE
END:VEVENT
* RockHounds @ Missions
<2018-04-29 Sun 14:05-17:05>
:PROPERTIES:
:ID:       LsMPG80Q64-MkPuxogsN8TdW@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

RockHounds @ Missions RockHounds @ Missions

Follow on MiLB First Pitch  https //stza.co/+wMuJ-3M

Shop  https //stza.co/+wMuJ-3t

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:RockHounds @ Missions
END:VALARM
DTSTART:20180429T190500Z
DTEND:20180429T220500Z
UID:LsMPG80Q64-MkPuxogsN8TdW@stanza.co
SUMMARY:RockHounds @ Missions
DESCRIPTION:RockHounds @ Missions\n\nFollow on MiLB First Pitch: https://stza.co/+wMuJ-3M\n\nShop: https://stza.co/+wMuJ-3t\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144543Z
LAST-MODIFIED:20180213T144543Z
TRANSP:OPAQUE
END:VEVENT
* RockHounds @ Missions
<2018-04-30 Mon 11:05-14:05>
:PROPERTIES:
:ID:       Bv-554e0HJPIcB3kfNWigc_4@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

RockHounds @ Missions RockHounds @ Missions

Follow on MiLB First Pitch  https //stza.co/+wMuK-C

Shop  https //stza.co/+wMuK-

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:RockHounds @ Missions
END:VALARM
DTSTART:20180430T160500Z
DTEND:20180430T190500Z
UID:Bv-554e0HJPIcB3kfNWigc_4@stanza.co
SUMMARY:RockHounds @ Missions
DESCRIPTION:RockHounds @ Missions\n\nFollow on MiLB First Pitch: https://stza.co/+wMuK-C\n\nShop: https://stza.co/+wMuK-\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144543Z
LAST-MODIFIED:20180213T144543Z
TRANSP:OPAQUE
END:VEVENT
* RockHounds vs. Hooks
<2018-05-01 Tue 18:30-21:30>
:PROPERTIES:
:ID:       OxLcc8upRe1qZP2S7HPj4ZkV@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

RockHounds vs. Hooks RockHounds vs. Hooks

Follow on MiLB First Pitch  https //stza.co/+wX2I-2M

Shop  https //stza.co/+wX2I-1n

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:RockHounds vs. Hooks
END:VALARM
DTSTART:20180501T233000Z
DTEND:20180502T023000Z
UID:OxLcc8upRe1qZP2S7HPj4ZkV@stanza.co
SUMMARY:RockHounds vs. Hooks
DESCRIPTION:RockHounds vs. Hooks\n\nFollow on MiLB First Pitch: https://stza.co/+wX2I-2M\n\nShop: https://stza.co/+wX2I-1n\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144543Z
LAST-MODIFIED:20180213T144543Z
TRANSP:OPAQUE
END:VEVENT
* RockHounds vs. Hooks
<2018-05-02 Wed 11:00-14:00>
:PROPERTIES:
:ID:       vBxRHVtQ80w9YFBnfKDVljwF@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

RockHounds vs. Hooks RockHounds vs. Hooks

Follow on MiLB First Pitch  https //stza.co/+wX2K-2

Shop  https //stza.co/+wX2K-k

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:RockHounds vs. Hooks
END:VALARM
DTSTART:20180502T160000Z
DTEND:20180502T190000Z
UID:vBxRHVtQ80w9YFBnfKDVljwF@stanza.co
SUMMARY:RockHounds vs. Hooks
DESCRIPTION:RockHounds vs. Hooks\n\nFollow on MiLB First Pitch: https://stza.co/+wX2K-2\n\nShop: https://stza.co/+wX2K-k\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144543Z
LAST-MODIFIED:20180213T144543Z
TRANSP:OPAQUE
END:VEVENT
* RockHounds vs. Hooks
<2018-05-03 Thu 19:00-22:00>
:PROPERTIES:
:ID:       55O61Cqrv0wC34uDGn8Unh6A@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

RockHounds vs. Hooks RockHounds vs. Hooks

Follow on MiLB First Pitch  https //stza.co/+wX2M-O

Shop  https //stza.co/+wX2M-z

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:RockHounds vs. Hooks
END:VALARM
DTSTART:20180504T000000Z
DTEND:20180504T030000Z
UID:55O61Cqrv0wC34uDGn8Unh6A@stanza.co
SUMMARY:RockHounds vs. Hooks
DESCRIPTION:RockHounds vs. Hooks\n\nFollow on MiLB First Pitch: https://stza.co/+wX2M-O\n\nShop: https://stza.co/+wX2M-z\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144543Z
LAST-MODIFIED:20180213T144543Z
TRANSP:OPAQUE
END:VEVENT
* RockHounds vs. Hooks
<2018-05-04 Fri 19:00-22:00>
:PROPERTIES:
:ID:       J0s--QHPfayMSAzgpUGxVCNA@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

RockHounds vs. Hooks RockHounds vs. Hooks

Follow on MiLB First Pitch  https //stza.co/+wX2O-2J

Shop  https //stza.co/+wX2O-3B

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:RockHounds vs. Hooks
END:VALARM
DTSTART:20180505T000000Z
DTEND:20180505T030000Z
UID:J0s--QHPfayMSAzgpUGxVCNA@stanza.co
SUMMARY:RockHounds vs. Hooks
DESCRIPTION:RockHounds vs. Hooks\n\nFollow on MiLB First Pitch: https://stza.co/+wX2O-2J\n\nShop: https://stza.co/+wX2O-3B\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144543Z
LAST-MODIFIED:20180213T144543Z
TRANSP:OPAQUE
END:VEVENT
* RockHounds @ RoughRiders
<2018-05-05 Sat 19:05-22:05>
:PROPERTIES:
:ID:       YNiHUFCMEngScXTgSKHtOQlJ@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

RockHounds @ RoughRiders RockHounds @ RoughRiders

Follow on MiLB First Pitch  https //stza.co/+wYaw-3t

Shop  https //stza.co/+wYaw-C

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:RockHounds @ RoughRiders
END:VALARM
DTSTART:20180506T000500Z
DTEND:20180506T030500Z
UID:YNiHUFCMEngScXTgSKHtOQlJ@stanza.co
SUMMARY:RockHounds @ RoughRiders
DESCRIPTION:RockHounds @ RoughRiders\n\nFollow on MiLB First Pitch: https://stza.co/+wYaw-3t\n\nShop: https://stza.co/+wYaw-C\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144543Z
LAST-MODIFIED:20180213T144543Z
TRANSP:OPAQUE
END:VEVENT
* RockHounds @ RoughRiders
<2018-05-06 Sun 16:05-19:05>
:PROPERTIES:
:ID:       sHbcMbTDbdjBPm6t1Mrx5vEv@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

RockHounds @ RoughRiders RockHounds @ RoughRiders

Follow on MiLB First Pitch  https //stza.co/+wYay-34

Shop  https //stza.co/+wYay-2R

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:RockHounds @ RoughRiders
END:VALARM
DTSTART:20180506T210500Z
DTEND:20180507T000500Z
UID:sHbcMbTDbdjBPm6t1Mrx5vEv@stanza.co
SUMMARY:RockHounds @ RoughRiders
DESCRIPTION:RockHounds @ RoughRiders\n\nFollow on MiLB First Pitch: https://stza.co/+wYay-34\n\nShop: https://stza.co/+wYay-2R\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144543Z
LAST-MODIFIED:20180213T144543Z
TRANSP:OPAQUE
END:VEVENT
* RockHounds @ RoughRiders
<2018-05-07 Mon 19:05-22:05>
:PROPERTIES:
:ID:       Z2C-YAsRqGdF6qJfC1WOkmNw@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

RockHounds @ RoughRiders RockHounds @ RoughRiders

Follow on MiLB First Pitch  https //stza.co/+wYaB-1Q

Shop  https //stza.co/+wYaB-1s

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:RockHounds @ RoughRiders
END:VALARM
DTSTART:20180508T000500Z
DTEND:20180508T030500Z
UID:Z2C-YAsRqGdF6qJfC1WOkmNw@stanza.co
SUMMARY:RockHounds @ RoughRiders
DESCRIPTION:RockHounds @ RoughRiders\n\nFollow on MiLB First Pitch: https://stza.co/+wYaB-1Q\n\nShop: https://stza.co/+wYaB-1s\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144543Z
LAST-MODIFIED:20180213T144543Z
TRANSP:OPAQUE
END:VEVENT
* RockHounds @ RoughRiders
<2018-05-08 Tue 11:05-14:05>
:PROPERTIES:
:ID:       qFZ2yQ9qzf3KmUeErQ5rDeZw@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

RockHounds @ RoughRiders RockHounds @ RoughRiders

Follow on MiLB First Pitch  https //stza.co/+wYaD-2e

Shop  https //stza.co/+wYaD-2L

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:RockHounds @ RoughRiders
END:VALARM
DTSTART:20180508T160500Z
DTEND:20180508T190500Z
UID:qFZ2yQ9qzf3KmUeErQ5rDeZw@stanza.co
SUMMARY:RockHounds @ RoughRiders
DESCRIPTION:RockHounds @ RoughRiders\n\nFollow on MiLB First Pitch: https://stza.co/+wYaD-2e\n\nShop: https://stza.co/+wYaD-2L\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144543Z
LAST-MODIFIED:20180213T144543Z
TRANSP:OPAQUE
END:VEVENT
* RockHounds @ Hooks
<2018-05-10 Thu 19:05-22:05>
:PROPERTIES:
:ID:       IILArGEP0SGcIXjMXiuMrjq5@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

RockHounds @ Hooks RockHounds @ Hooks

Follow on MiLB First Pitch  https //stza.co/+xzHE-

Shop  https //stza.co/+xzHE-1G

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:RockHounds @ Hooks
END:VALARM
DTSTART:20180511T000500Z
DTEND:20180511T030500Z
UID:IILArGEP0SGcIXjMXiuMrjq5@stanza.co
SUMMARY:RockHounds @ Hooks
DESCRIPTION:RockHounds @ Hooks\n\nFollow on MiLB First Pitch: https://stza.co/+xzHE-\n\nShop: https://stza.co/+xzHE-1G\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144543Z
LAST-MODIFIED:20180213T144543Z
TRANSP:OPAQUE
END:VEVENT
* RockHounds @ Hooks
<2018-05-11 Fri 19:05-22:05>
:PROPERTIES:
:ID:       0_nMcCe02pwWSGdxdxOEMtpB@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

RockHounds @ Hooks RockHounds @ Hooks

Follow on MiLB First Pitch  https //stza.co/+xzHF-1Q

Shop  https //stza.co/+xzHF-W

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:RockHounds @ Hooks
END:VALARM
DTSTART:20180512T000500Z
DTEND:20180512T030500Z
UID:0_nMcCe02pwWSGdxdxOEMtpB@stanza.co
SUMMARY:RockHounds @ Hooks
DESCRIPTION:RockHounds @ Hooks\n\nFollow on MiLB First Pitch: https://stza.co/+xzHF-1Q\n\nShop: https://stza.co/+xzHF-W\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144543Z
LAST-MODIFIED:20180213T144543Z
TRANSP:OPAQUE
END:VEVENT
* RockHounds @ Hooks
<2018-05-12 Sat 19:05-22:05>
:PROPERTIES:
:ID:       GLk4cOq6Y6RiEAeVxUDJTyCE@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

RockHounds @ Hooks RockHounds @ Hooks

Follow on MiLB First Pitch  https //stza.co/+xzHG-2S

Shop  https //stza.co/+xzHG-10

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:RockHounds @ Hooks
END:VALARM
DTSTART:20180513T000500Z
DTEND:20180513T030500Z
UID:GLk4cOq6Y6RiEAeVxUDJTyCE@stanza.co
SUMMARY:RockHounds @ Hooks
DESCRIPTION:RockHounds @ Hooks\n\nFollow on MiLB First Pitch: https://stza.co/+xzHG-2S\n\nShop: https://stza.co/+xzHG-10\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144543Z
LAST-MODIFIED:20180213T144543Z
TRANSP:OPAQUE
END:VEVENT
* RockHounds @ Hooks
<2018-05-13 Sun 14:05-17:05>
:PROPERTIES:
:ID:       -VFPPV60pRt6-pyAGM0vX62e@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

RockHounds @ Hooks RockHounds @ Hooks

Follow on MiLB First Pitch  https //stza.co/+xzHH-M

Shop  https //stza.co/+xzHH-j

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:RockHounds @ Hooks
END:VALARM
DTSTART:20180513T190500Z
DTEND:20180513T220500Z
UID:-VFPPV60pRt6-pyAGM0vX62e@stanza.co
SUMMARY:RockHounds @ Hooks
DESCRIPTION:RockHounds @ Hooks\n\nFollow on MiLB First Pitch: https://stza.co/+xzHH-M\n\nShop: https://stza.co/+xzHH-j\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144543Z
LAST-MODIFIED:20180213T144543Z
TRANSP:OPAQUE
END:VEVENT
* RockHounds vs. RoughRiders
<2018-05-14 Mon 18:30-21:30>
:PROPERTIES:
:ID:       krLFHOhFim8Xvg_nznIGrvjr@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

RockHounds vs. RoughRiders RockHounds vs. RoughRiders

Follow on MiLB First Pitch  https //stza.co/+wX2R-3b

Shop  https //stza.co/+wX2R-2r

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:RockHounds vs. RoughRiders
END:VALARM
DTSTART:20180514T233000Z
DTEND:20180515T023000Z
UID:krLFHOhFim8Xvg_nznIGrvjr@stanza.co
SUMMARY:RockHounds vs. RoughRiders
DESCRIPTION:RockHounds vs. RoughRiders\n\nFollow on MiLB First Pitch: https://stza.co/+wX2R-3b\n\nShop: https://stza.co/+wX2R-2r\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144543Z
LAST-MODIFIED:20180213T144543Z
TRANSP:OPAQUE
END:VEVENT
* RockHounds vs. RoughRiders
<2018-05-15 Tue 18:30-21:30>
:PROPERTIES:
:ID:       uEq7st5usWGV5pc_hDM-zF0w@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

RockHounds vs. RoughRiders RockHounds vs. RoughRiders

Follow on MiLB First Pitch  https //stza.co/+wX2T-1H

Shop  https //stza.co/+wX2T-_

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:RockHounds vs. RoughRiders
END:VALARM
DTSTART:20180515T233000Z
DTEND:20180516T023000Z
UID:uEq7st5usWGV5pc_hDM-zF0w@stanza.co
SUMMARY:RockHounds vs. RoughRiders
DESCRIPTION:RockHounds vs. RoughRiders\n\nFollow on MiLB First Pitch: https://stza.co/+wX2T-1H\n\nShop: https://stza.co/+wX2T-_\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144543Z
LAST-MODIFIED:20180213T144543Z
TRANSP:OPAQUE
END:VEVENT
* RockHounds vs. RoughRiders
<2018-05-16 Wed 18:30-21:30>
:PROPERTIES:
:ID:       4n5b590i8joF0CNT6zE2X95r@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

RockHounds vs. RoughRiders RockHounds vs. RoughRiders

Follow on MiLB First Pitch  https //stza.co/+wX2V-2R

Shop  https //stza.co/+wX2V-l

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:RockHounds vs. RoughRiders
END:VALARM
DTSTART:20180516T233000Z
DTEND:20180517T023000Z
UID:4n5b590i8joF0CNT6zE2X95r@stanza.co
SUMMARY:RockHounds vs. RoughRiders
DESCRIPTION:RockHounds vs. RoughRiders\n\nFollow on MiLB First Pitch: https://stza.co/+wX2V-2R\n\nShop: https://stza.co/+wX2V-l\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144543Z
LAST-MODIFIED:20180213T144543Z
TRANSP:OPAQUE
END:VEVENT
* RockHounds vs. RoughRiders
<2018-05-17 Thu 19:00-22:00>
:PROPERTIES:
:ID:       NjBZuA9stOyusVidWUb8uIfM@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

RockHounds vs. RoughRiders RockHounds vs. RoughRiders

Follow on MiLB First Pitch  https //stza.co/+wX2W-1w

Shop  https //stza.co/+wX2W-W

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:RockHounds vs. RoughRiders
END:VALARM
DTSTART:20180518T000000Z
DTEND:20180518T030000Z
UID:NjBZuA9stOyusVidWUb8uIfM@stanza.co
SUMMARY:RockHounds vs. RoughRiders
DESCRIPTION:RockHounds vs. RoughRiders\n\nFollow on MiLB First Pitch: https://stza.co/+wX2W-1w\n\nShop: https://stza.co/+wX2W-W\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144543Z
LAST-MODIFIED:20180213T144543Z
TRANSP:OPAQUE
END:VEVENT
* RockHounds vs. Missions
<2018-05-18 Fri 19:00-22:00>
:PROPERTIES:
:ID:       Qx0sVBjIp0ez-xrv6HKPdQZr@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

RockHounds vs. Missions RockHounds vs. Missions

Follow on MiLB First Pitch  https //stza.co/+wX2Z-J

Shop  https //stza.co/+wX2Z-2p

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:RockHounds vs. Missions
END:VALARM
DTSTART:20180519T000000Z
DTEND:20180519T030000Z
UID:Qx0sVBjIp0ez-xrv6HKPdQZr@stanza.co
SUMMARY:RockHounds vs. Missions
DESCRIPTION:RockHounds vs. Missions\n\nFollow on MiLB First Pitch: https://stza.co/+wX2Z-J\n\nShop: https://stza.co/+wX2Z-2p\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144543Z
LAST-MODIFIED:20180213T144543Z
TRANSP:OPAQUE
END:VEVENT
* RockHounds vs. Missions
<2018-05-19 Sat 19:00-22:00>
:PROPERTIES:
:ID:       yjoQc4kRm0MyCvalXkXNmcQg@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

RockHounds vs. Missions RockHounds vs. Missions

Follow on MiLB First Pitch  https //stza.co/+wX2$-32

Shop  https //stza.co/+wX2$-J

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:RockHounds vs. Missions
END:VALARM
DTSTART:20180520T000000Z
DTEND:20180520T030000Z
UID:yjoQc4kRm0MyCvalXkXNmcQg@stanza.co
SUMMARY:RockHounds vs. Missions
DESCRIPTION:RockHounds vs. Missions\n\nFollow on MiLB First Pitch: https://stza.co/+wX2$-32\n\nShop: https://stza.co/+wX2$-J\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144543Z
LAST-MODIFIED:20180213T144543Z
TRANSP:OPAQUE
END:VEVENT
* RockHounds vs. Missions
<2018-05-20 Sun 14:00-17:00>
:PROPERTIES:
:ID:       Lb78wUxTtKRYGIkATTc-oPpY@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

RockHounds vs. Missions RockHounds vs. Missions

Follow on MiLB First Pitch  https //stza.co/+wX32-32

Shop  https //stza.co/+wX32-1Y

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:RockHounds vs. Missions
END:VALARM
DTSTART:20180520T190000Z
DTEND:20180520T220000Z
UID:Lb78wUxTtKRYGIkATTc-oPpY@stanza.co
SUMMARY:RockHounds vs. Missions
DESCRIPTION:RockHounds vs. Missions\n\nFollow on MiLB First Pitch: https://stza.co/+wX32-32\n\nShop: https://stza.co/+wX32-1Y\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144543Z
LAST-MODIFIED:20180213T144543Z
TRANSP:OPAQUE
END:VEVENT
* RockHounds vs. Missions
<2018-05-21 Mon 11:00-14:00>
:PROPERTIES:
:ID:       1803FhGeRbvpnRrPlpgPcB3Y@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

RockHounds vs. Missions RockHounds vs. Missions

Follow on MiLB First Pitch  https //stza.co/+wX33-25

Shop  https //stza.co/+wX33-Z

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:RockHounds vs. Missions
END:VALARM
DTSTART:20180521T160000Z
DTEND:20180521T190000Z
UID:1803FhGeRbvpnRrPlpgPcB3Y@stanza.co
SUMMARY:RockHounds vs. Missions
DESCRIPTION:RockHounds vs. Missions\n\nFollow on MiLB First Pitch: https://stza.co/+wX33-25\n\nShop: https://stza.co/+wX33-Z\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144543Z
LAST-MODIFIED:20180213T144543Z
TRANSP:OPAQUE
END:VEVENT
* RockHounds @ Travelers
<2018-05-22 Tue 19:10-22:10>
:PROPERTIES:
:ID:       wNRhcYTaxjyG8pZMEy9PY_-1@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

RockHounds @ Travelers RockHounds @ Travelers

Follow on MiLB First Pitch  https //stza.co/+w00s-q

Shop  https //stza.co/+w00s-1p

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:RockHounds @ Travelers
END:VALARM
DTSTART:20180523T001000Z
DTEND:20180523T031000Z
UID:wNRhcYTaxjyG8pZMEy9PY_-1@stanza.co
SUMMARY:RockHounds @ Travelers
DESCRIPTION:RockHounds @ Travelers\n\nFollow on MiLB First Pitch: https://stza.co/+w00s-q\n\nShop: https://stza.co/+w00s-1p\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144543Z
LAST-MODIFIED:20180213T144543Z
TRANSP:OPAQUE
END:VEVENT
* RockHounds @ Travelers
<2018-05-23 Wed 19:10-22:10>
:PROPERTIES:
:ID:       odU_77XhktVahfl0P4dfN4GI@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

RockHounds @ Travelers RockHounds @ Travelers

Follow on MiLB First Pitch  https //stza.co/+w00t-V

Shop  https //stza.co/+w00t-W

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:RockHounds @ Travelers
END:VALARM
DTSTART:20180524T001000Z
DTEND:20180524T031000Z
UID:odU_77XhktVahfl0P4dfN4GI@stanza.co
SUMMARY:RockHounds @ Travelers
DESCRIPTION:RockHounds @ Travelers\n\nFollow on MiLB First Pitch: https://stza.co/+w00t-V\n\nShop: https://stza.co/+w00t-W\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144543Z
LAST-MODIFIED:20180213T144543Z
TRANSP:OPAQUE
END:VEVENT
* RockHounds @ Travelers
<2018-05-24 Thu 19:10-22:10>
:PROPERTIES:
:ID:       EXlihAD-IbLO2hz_NHT_TdUX@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

RockHounds @ Travelers RockHounds @ Travelers

Follow on MiLB First Pitch  https //stza.co/+w00u-1k

Shop  https //stza.co/+w00u-1v

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:RockHounds @ Travelers
END:VALARM
DTSTART:20180525T001000Z
DTEND:20180525T031000Z
UID:EXlihAD-IbLO2hz_NHT_TdUX@stanza.co
SUMMARY:RockHounds @ Travelers
DESCRIPTION:RockHounds @ Travelers\n\nFollow on MiLB First Pitch: https://stza.co/+w00u-1k\n\nShop: https://stza.co/+w00u-1v\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144543Z
LAST-MODIFIED:20180213T144543Z
TRANSP:OPAQUE
END:VEVENT
* RockHounds @ Naturals
<2018-05-25 Fri 19:05-22:05>
:PROPERTIES:
:ID:       oh0y-vKoZ4B2Pm666KwcZ2MQ@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

RockHounds @ Naturals RockHounds @ Naturals

Follow on MiLB First Pitch  https //stza.co/+wi0t-2j

Shop  https //stza.co/+wi0t-P

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:RockHounds @ Naturals
END:VALARM
DTSTART:20180526T000500Z
DTEND:20180526T030500Z
UID:oh0y-vKoZ4B2Pm666KwcZ2MQ@stanza.co
SUMMARY:RockHounds @ Naturals
DESCRIPTION:RockHounds @ Naturals\n\nFollow on MiLB First Pitch: https://stza.co/+wi0t-2j\n\nShop: https://stza.co/+wi0t-P\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144543Z
LAST-MODIFIED:20180213T144543Z
TRANSP:OPAQUE
END:VEVENT
* RockHounds @ Naturals
<2018-05-26 Sat 18:05-21:05>
:PROPERTIES:
:ID:       eMotFiKqy8FEOUbADCtKE584@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

RockHounds @ Naturals RockHounds @ Naturals

Follow on MiLB First Pitch  https //stza.co/+wi0u-18

Shop  https //stza.co/+wi0u-27

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:RockHounds @ Naturals
END:VALARM
DTSTART:20180526T230500Z
DTEND:20180527T020500Z
UID:eMotFiKqy8FEOUbADCtKE584@stanza.co
SUMMARY:RockHounds @ Naturals
DESCRIPTION:RockHounds @ Naturals\n\nFollow on MiLB First Pitch: https://stza.co/+wi0u-18\n\nShop: https://stza.co/+wi0u-27\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144543Z
LAST-MODIFIED:20180213T144543Z
TRANSP:OPAQUE
END:VEVENT
* RockHounds @ Naturals
<2018-05-27 Sun 18:35-21:35>
:PROPERTIES:
:ID:       grmkOU5sSDIxPh-XfGQu4k73@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

RockHounds @ Naturals RockHounds @ Naturals

Follow on MiLB First Pitch  https //stza.co/+wi0v-A

Shop  https //stza.co/+wi0v-o

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:RockHounds @ Naturals
END:VALARM
DTSTART:20180527T233500Z
DTEND:20180528T023500Z
UID:grmkOU5sSDIxPh-XfGQu4k73@stanza.co
SUMMARY:RockHounds @ Naturals
DESCRIPTION:RockHounds @ Naturals\n\nFollow on MiLB First Pitch: https://stza.co/+wi0v-A\n\nShop: https://stza.co/+wi0v-o\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144543Z
LAST-MODIFIED:20180213T144543Z
TRANSP:OPAQUE
END:VEVENT
* RockHounds vs. Travelers
<2018-05-29 Tue 18:30-21:30>
:PROPERTIES:
:ID:       vfeYVJyrQhnZkafJ-vKR_w-1@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

RockHounds vs. Travelers RockHounds vs. Travelers

Follow on MiLB First Pitch  https //stza.co/+wX36-

Shop  https //stza.co/+wX36-2e

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:RockHounds vs. Travelers
END:VALARM
DTSTART:20180529T233000Z
DTEND:20180530T023000Z
UID:vfeYVJyrQhnZkafJ-vKR_w-1@stanza.co
SUMMARY:RockHounds vs. Travelers
DESCRIPTION:RockHounds vs. Travelers\n\nFollow on MiLB First Pitch: https://stza.co/+wX36-\n\nShop: https://stza.co/+wX36-2e\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144543Z
LAST-MODIFIED:20180213T144543Z
TRANSP:OPAQUE
END:VEVENT
* RockHounds vs. Travelers
<2018-05-30 Wed 18:30-21:30>
:PROPERTIES:
:ID:       N5lcLOJDj16Z_gh7cSTH7x6b@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

RockHounds vs. Travelers RockHounds vs. Travelers

Follow on MiLB First Pitch  https //stza.co/+wX38-3x

Shop  https //stza.co/+wX38-1e

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:RockHounds vs. Travelers
END:VALARM
DTSTART:20180530T233000Z
DTEND:20180531T023000Z
UID:N5lcLOJDj16Z_gh7cSTH7x6b@stanza.co
SUMMARY:RockHounds vs. Travelers
DESCRIPTION:RockHounds vs. Travelers\n\nFollow on MiLB First Pitch: https://stza.co/+wX38-3x\n\nShop: https://stza.co/+wX38-1e\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144543Z
LAST-MODIFIED:20180213T144543Z
TRANSP:OPAQUE
END:VEVENT
* RockHounds vs. Travelers
<2018-05-31 Thu 19:00-22:00>
:PROPERTIES:
:ID:       7nJ1YQrFSJ39lc6dI9bVGcNb@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

RockHounds vs. Travelers RockHounds vs. Travelers

Follow on MiLB First Pitch  https //stza.co/+wX3a-1l

Shop  https //stza.co/+wX3a-Z

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:RockHounds vs. Travelers
END:VALARM
DTSTART:20180601T000000Z
DTEND:20180601T030000Z
UID:7nJ1YQrFSJ39lc6dI9bVGcNb@stanza.co
SUMMARY:RockHounds vs. Travelers
DESCRIPTION:RockHounds vs. Travelers\n\nFollow on MiLB First Pitch: https://stza.co/+wX3a-1l\n\nShop: https://stza.co/+wX3a-Z\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144543Z
LAST-MODIFIED:20180213T144543Z
TRANSP:OPAQUE
END:VEVENT
* RockHounds vs. Naturals
<2018-06-01 Fri 19:00-22:00>
:PROPERTIES:
:ID:       Nez3usWbTLMpWRQ8rvsAC2Lz@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

RockHounds vs. Naturals RockHounds vs. Naturals

Follow on MiLB First Pitch  https //stza.co/+wX3d-1o

Shop  https //stza.co/+wX3d-18

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:RockHounds vs. Naturals
END:VALARM
DTSTART:20180602T000000Z
DTEND:20180602T030000Z
UID:Nez3usWbTLMpWRQ8rvsAC2Lz@stanza.co
SUMMARY:RockHounds vs. Naturals
DESCRIPTION:RockHounds vs. Naturals\n\nFollow on MiLB First Pitch: https://stza.co/+wX3d-1o\n\nShop: https://stza.co/+wX3d-18\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144543Z
LAST-MODIFIED:20180213T144543Z
TRANSP:OPAQUE
END:VEVENT
* RockHounds vs. Naturals
<2018-06-02 Sat 19:00-22:00>
:PROPERTIES:
:ID:       nLIXg9Kh-zkMfO004ClrmAcB@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

RockHounds vs. Naturals RockHounds vs. Naturals

Follow on MiLB First Pitch  https //stza.co/+wX3e-1T

Shop  https //stza.co/+wX3e-3

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:RockHounds vs. Naturals
END:VALARM
DTSTART:20180603T000000Z
DTEND:20180603T030000Z
UID:nLIXg9Kh-zkMfO004ClrmAcB@stanza.co
SUMMARY:RockHounds vs. Naturals
DESCRIPTION:RockHounds vs. Naturals\n\nFollow on MiLB First Pitch: https://stza.co/+wX3e-1T\n\nShop: https://stza.co/+wX3e-3\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144543Z
LAST-MODIFIED:20180213T144543Z
TRANSP:OPAQUE
END:VEVENT
* RockHounds vs. Naturals
<2018-06-03 Sun 14:00-17:00>
:PROPERTIES:
:ID:       B4gaom_Wk9wxYfuvBFNydkFY@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

RockHounds vs. Naturals RockHounds vs. Naturals

Follow on MiLB First Pitch  https //stza.co/+wX3h-2V

Shop  https //stza.co/+wX3h-1Y

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:RockHounds vs. Naturals
END:VALARM
DTSTART:20180603T190000Z
DTEND:20180603T220000Z
UID:B4gaom_Wk9wxYfuvBFNydkFY@stanza.co
SUMMARY:RockHounds vs. Naturals
DESCRIPTION:RockHounds vs. Naturals\n\nFollow on MiLB First Pitch: https://stza.co/+wX3h-2V\n\nShop: https://stza.co/+wX3h-1Y\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144543Z
LAST-MODIFIED:20180213T144543Z
TRANSP:OPAQUE
END:VEVENT
* RockHounds @ Missions
<2018-06-05 Tue 19:05-22:05>
:PROPERTIES:
:ID:       9d8cP481MhGAW3pLwjb_H_Kw@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

RockHounds @ Missions RockHounds @ Missions

Follow on MiLB First Pitch  https //stza.co/+wMuL-27

Shop  https //stza.co/+wMuL-23

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:RockHounds @ Missions
END:VALARM
DTSTART:20180606T000500Z
DTEND:20180606T030500Z
UID:9d8cP481MhGAW3pLwjb_H_Kw@stanza.co
SUMMARY:RockHounds @ Missions
DESCRIPTION:RockHounds @ Missions\n\nFollow on MiLB First Pitch: https://stza.co/+wMuL-27\n\nShop: https://stza.co/+wMuL-23\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144543Z
LAST-MODIFIED:20180213T144543Z
TRANSP:OPAQUE
END:VEVENT
* RockHounds @ Missions
<2018-06-06 Wed 19:05-22:05>
:PROPERTIES:
:ID:       m_gD-DwhonreNWnZ64QYBT_1@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

RockHounds @ Missions RockHounds @ Missions

Follow on MiLB First Pitch  https //stza.co/+wMuN-3u

Shop  https //stza.co/+wMuN-2k

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:RockHounds @ Missions
END:VALARM
DTSTART:20180607T000500Z
DTEND:20180607T030500Z
UID:m_gD-DwhonreNWnZ64QYBT_1@stanza.co
SUMMARY:RockHounds @ Missions
DESCRIPTION:RockHounds @ Missions\n\nFollow on MiLB First Pitch: https://stza.co/+wMuN-3u\n\nShop: https://stza.co/+wMuN-2k\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144543Z
LAST-MODIFIED:20180213T144543Z
TRANSP:OPAQUE
END:VEVENT
* RockHounds @ Missions
<2018-06-07 Thu 19:05-22:05>
:PROPERTIES:
:ID:       6USkB-bNEfvNDAFbXBwJYDDV@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

RockHounds @ Missions RockHounds @ Missions

Follow on MiLB First Pitch  https //stza.co/+wMuO-3r

Shop  https //stza.co/+wMuO-3z

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:RockHounds @ Missions
END:VALARM
DTSTART:20180608T000500Z
DTEND:20180608T030500Z
UID:6USkB-bNEfvNDAFbXBwJYDDV@stanza.co
SUMMARY:RockHounds @ Missions
DESCRIPTION:RockHounds @ Missions\n\nFollow on MiLB First Pitch: https://stza.co/+wMuO-3r\n\nShop: https://stza.co/+wMuO-3z\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144543Z
LAST-MODIFIED:20180213T144543Z
TRANSP:OPAQUE
END:VEVENT
* RockHounds @ Missions
<2018-06-08 Fri 19:05-22:05>
:PROPERTIES:
:ID:       LqsS49juM0WTSKmHqB5KhiJr@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

RockHounds @ Missions RockHounds @ Missions

Follow on MiLB First Pitch  https //stza.co/+wMuP-2H

Shop  https //stza.co/+wMuP-1w

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:RockHounds @ Missions
END:VALARM
DTSTART:20180609T000500Z
DTEND:20180609T030500Z
UID:LqsS49juM0WTSKmHqB5KhiJr@stanza.co
SUMMARY:RockHounds @ Missions
DESCRIPTION:RockHounds @ Missions\n\nFollow on MiLB First Pitch: https://stza.co/+wMuP-2H\n\nShop: https://stza.co/+wMuP-1w\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144543Z
LAST-MODIFIED:20180213T144543Z
TRANSP:OPAQUE
END:VEVENT
* RockHounds @ RoughRiders
<2018-06-09 Sat 19:05-22:05>
:PROPERTIES:
:ID:       9KHGAwIERIfhevGmrDinCBy-@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

RockHounds @ RoughRiders RockHounds @ RoughRiders

Follow on MiLB First Pitch  https //stza.co/+wYaG-2O

Shop  https //stza.co/+wYaG-2B

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:RockHounds @ RoughRiders
END:VALARM
DTSTART:20180610T000500Z
DTEND:20180610T030500Z
UID:9KHGAwIERIfhevGmrDinCBy-@stanza.co
SUMMARY:RockHounds @ RoughRiders
DESCRIPTION:RockHounds @ RoughRiders\n\nFollow on MiLB First Pitch: https://stza.co/+wYaG-2O\n\nShop: https://stza.co/+wYaG-2B\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144543Z
LAST-MODIFIED:20180213T144543Z
TRANSP:OPAQUE
END:VEVENT
* RockHounds @ RoughRiders
<2018-06-10 Sun 19:05-22:05>
:PROPERTIES:
:ID:       0nTkfHihZZoZhFGge1ivVsdS@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

RockHounds @ RoughRiders RockHounds @ RoughRiders

Follow on MiLB First Pitch  https //stza.co/+wYaI-1V

Shop  https //stza.co/+wYaI-3M

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:RockHounds @ RoughRiders
END:VALARM
DTSTART:20180611T000500Z
DTEND:20180611T030500Z
UID:0nTkfHihZZoZhFGge1ivVsdS@stanza.co
SUMMARY:RockHounds @ RoughRiders
DESCRIPTION:RockHounds @ RoughRiders\n\nFollow on MiLB First Pitch: https://stza.co/+wYaI-1V\n\nShop: https://stza.co/+wYaI-3M\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144543Z
LAST-MODIFIED:20180213T144543Z
TRANSP:OPAQUE
END:VEVENT
* RockHounds @ RoughRiders
<2018-06-11 Mon 19:05-22:05>
:PROPERTIES:
:ID:       iMJkt4oTY-F5H3TexVUUWSYj@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

RockHounds @ RoughRiders RockHounds @ RoughRiders

Follow on MiLB First Pitch  https //stza.co/+wYaK-1J

Shop  https //stza.co/+wYaK-3U

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:RockHounds @ RoughRiders
END:VALARM
DTSTART:20180612T000500Z
DTEND:20180612T030500Z
UID:iMJkt4oTY-F5H3TexVUUWSYj@stanza.co
SUMMARY:RockHounds @ RoughRiders
DESCRIPTION:RockHounds @ RoughRiders\n\nFollow on MiLB First Pitch: https://stza.co/+wYaK-1J\n\nShop: https://stza.co/+wYaK-3U\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144543Z
LAST-MODIFIED:20180213T144543Z
TRANSP:OPAQUE
END:VEVENT
* RockHounds @ RoughRiders
<2018-06-12 Tue 11:05-14:05>
:PROPERTIES:
:ID:       QhIg6dzUKlqtq8a-jEzEXfcc@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

RockHounds @ RoughRiders RockHounds @ RoughRiders

Follow on MiLB First Pitch  https //stza.co/+wYaL-1M

Shop  https //stza.co/+wYaL-1T

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:RockHounds @ RoughRiders
END:VALARM
DTSTART:20180612T160500Z
DTEND:20180612T190500Z
UID:QhIg6dzUKlqtq8a-jEzEXfcc@stanza.co
SUMMARY:RockHounds @ RoughRiders
DESCRIPTION:RockHounds @ RoughRiders\n\nFollow on MiLB First Pitch: https://stza.co/+wYaL-1M\n\nShop: https://stza.co/+wYaL-1T\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144543Z
LAST-MODIFIED:20180213T144543Z
TRANSP:OPAQUE
END:VEVENT
* RockHounds vs. Hooks
<2018-06-13 Wed 18:30-21:30>
:PROPERTIES:
:ID:       v-eeq17nLXYrflONIHHn8bbi@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

RockHounds vs. Hooks RockHounds vs. Hooks

Follow on MiLB First Pitch  https //stza.co/+wX3i-3o

Shop  https //stza.co/+wX3i-15

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:RockHounds vs. Hooks
END:VALARM
DTSTART:20180613T233000Z
DTEND:20180614T023000Z
UID:v-eeq17nLXYrflONIHHn8bbi@stanza.co
SUMMARY:RockHounds vs. Hooks
DESCRIPTION:RockHounds vs. Hooks\n\nFollow on MiLB First Pitch: https://stza.co/+wX3i-3o\n\nShop: https://stza.co/+wX3i-15\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144543Z
LAST-MODIFIED:20180213T144543Z
TRANSP:OPAQUE
END:VEVENT
* RockHounds vs. Hooks
<2018-06-14 Thu 19:00-22:00>
:PROPERTIES:
:ID:       Jp6gKhUjCNkZwnQS0BfCxnfW@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

RockHounds vs. Hooks RockHounds vs. Hooks

Follow on MiLB First Pitch  https //stza.co/+wX3k-3r

Shop  https //stza.co/+wX3k-L

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:RockHounds vs. Hooks
END:VALARM
DTSTART:20180615T000000Z
DTEND:20180615T030000Z
UID:Jp6gKhUjCNkZwnQS0BfCxnfW@stanza.co
SUMMARY:RockHounds vs. Hooks
DESCRIPTION:RockHounds vs. Hooks\n\nFollow on MiLB First Pitch: https://stza.co/+wX3k-3r\n\nShop: https://stza.co/+wX3k-L\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144543Z
LAST-MODIFIED:20180213T144543Z
TRANSP:OPAQUE
END:VEVENT
* RockHounds vs. Hooks
<2018-06-15 Fri 19:00-22:00>
:PROPERTIES:
:ID:       OKdJVaimk8Kwgp1oeobAGChB@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

RockHounds vs. Hooks RockHounds vs. Hooks

Follow on MiLB First Pitch  https //stza.co/+wX3o-3T

Shop  https //stza.co/+wX3o-29

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:RockHounds vs. Hooks
END:VALARM
DTSTART:20180616T000000Z
DTEND:20180616T030000Z
UID:OKdJVaimk8Kwgp1oeobAGChB@stanza.co
SUMMARY:RockHounds vs. Hooks
DESCRIPTION:RockHounds vs. Hooks\n\nFollow on MiLB First Pitch: https://stza.co/+wX3o-3T\n\nShop: https://stza.co/+wX3o-29\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144543Z
LAST-MODIFIED:20180213T144543Z
TRANSP:OPAQUE
END:VEVENT
* RockHounds vs. Hooks
<2018-06-16 Sat 19:00-22:00>
:PROPERTIES:
:ID:       _sAo4Z6NcAt1Xkk7U4F8RCb3@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

RockHounds vs. Hooks RockHounds vs. Hooks

Follow on MiLB First Pitch  https //stza.co/+wX3p-P

Shop  https //stza.co/+wX3p-30

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:RockHounds vs. Hooks
END:VALARM
DTSTART:20180617T000000Z
DTEND:20180617T030000Z
UID:_sAo4Z6NcAt1Xkk7U4F8RCb3@stanza.co
SUMMARY:RockHounds vs. Hooks
DESCRIPTION:RockHounds vs. Hooks\n\nFollow on MiLB First Pitch: https://stza.co/+wX3p-P\n\nShop: https://stza.co/+wX3p-30\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144543Z
LAST-MODIFIED:20180213T144543Z
TRANSP:OPAQUE
END:VEVENT
* RockHounds vs. RoughRiders
<2018-06-17 Sun 16:00-19:00>
:PROPERTIES:
:ID:       q1-LLs07lbFQuRtKj3U184tZ@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

RockHounds vs. RoughRiders RockHounds vs. RoughRiders

Follow on MiLB First Pitch  https //stza.co/+wX3s-1v

Shop  https //stza.co/+wX3s-14

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:RockHounds vs. RoughRiders
END:VALARM
DTSTART:20180617T210000Z
DTEND:20180618T000000Z
UID:q1-LLs07lbFQuRtKj3U184tZ@stanza.co
SUMMARY:RockHounds vs. RoughRiders
DESCRIPTION:RockHounds vs. RoughRiders\n\nFollow on MiLB First Pitch: https://stza.co/+wX3s-1v\n\nShop: https://stza.co/+wX3s-14\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144543Z
LAST-MODIFIED:20180213T144543Z
TRANSP:OPAQUE
END:VEVENT
* RockHounds vs. RoughRiders
<2018-06-18 Mon 18:30-21:30>
:PROPERTIES:
:ID:       1wZAjK9JlPOEY1QrA2Kxj578@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

RockHounds vs. RoughRiders RockHounds vs. RoughRiders

Follow on MiLB First Pitch  https //stza.co/+wX3v-2N

Shop  https //stza.co/+wX3v-j

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:RockHounds vs. RoughRiders
END:VALARM
DTSTART:20180618T233000Z
DTEND:20180619T023000Z
UID:1wZAjK9JlPOEY1QrA2Kxj578@stanza.co
SUMMARY:RockHounds vs. RoughRiders
DESCRIPTION:RockHounds vs. RoughRiders\n\nFollow on MiLB First Pitch: https://stza.co/+wX3v-2N\n\nShop: https://stza.co/+wX3v-j\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144543Z
LAST-MODIFIED:20180213T144543Z
TRANSP:OPAQUE
END:VEVENT
* RockHounds vs. RoughRiders
<2018-06-19 Tue 18:30-21:30>
:PROPERTIES:
:ID:       dDKLrqMWnq9ArZkRRtJy1LH2@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

RockHounds vs. RoughRiders RockHounds vs. RoughRiders

Follow on MiLB First Pitch  https //stza.co/+wX3w-2V

Shop  https //stza.co/+wX3w-2n

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:RockHounds vs. RoughRiders
END:VALARM
DTSTART:20180619T233000Z
DTEND:20180620T023000Z
UID:dDKLrqMWnq9ArZkRRtJy1LH2@stanza.co
SUMMARY:RockHounds vs. RoughRiders
DESCRIPTION:RockHounds vs. RoughRiders\n\nFollow on MiLB First Pitch: https://stza.co/+wX3w-2V\n\nShop: https://stza.co/+wX3w-2n\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144543Z
LAST-MODIFIED:20180213T144543Z
TRANSP:OPAQUE
END:VEVENT
* RockHounds vs. RoughRiders
<2018-06-20 Wed 18:30-21:30>
:PROPERTIES:
:ID:       CL8YEOHlPZt1fUuPUHVgXqDj@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

RockHounds vs. RoughRiders RockHounds vs. RoughRiders

Follow on MiLB First Pitch  https //stza.co/+wX3z-S

Shop  https //stza.co/+wX3z-A

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:RockHounds vs. RoughRiders
END:VALARM
DTSTART:20180620T233000Z
DTEND:20180621T023000Z
UID:CL8YEOHlPZt1fUuPUHVgXqDj@stanza.co
SUMMARY:RockHounds vs. RoughRiders
DESCRIPTION:RockHounds vs. RoughRiders\n\nFollow on MiLB First Pitch: https://stza.co/+wX3z-S\n\nShop: https://stza.co/+wX3z-A\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144543Z
LAST-MODIFIED:20180213T144543Z
TRANSP:OPAQUE
END:VEVENT
* RockHounds @ Missions
<2018-06-21 Thu 19:05-22:05>
:PROPERTIES:
:ID:       Pl2BtwRBeofoyJZnPLrUApJJ@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

RockHounds @ Missions RockHounds @ Missions

Follow on MiLB First Pitch  https //stza.co/+wMuQ-2d

Shop  https //stza.co/+wMuQ-1C

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:RockHounds @ Missions
END:VALARM
DTSTART:20180622T000500Z
DTEND:20180622T030500Z
UID:Pl2BtwRBeofoyJZnPLrUApJJ@stanza.co
SUMMARY:RockHounds @ Missions
DESCRIPTION:RockHounds @ Missions\n\nFollow on MiLB First Pitch: https://stza.co/+wMuQ-2d\n\nShop: https://stza.co/+wMuQ-1C\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144543Z
LAST-MODIFIED:20180213T144543Z
TRANSP:OPAQUE
END:VEVENT
* RockHounds @ Missions
<2018-06-22 Fri 19:05-22:05>
:PROPERTIES:
:ID:       TkKv7tNMLb9h4TwXlMiipNat@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

RockHounds @ Missions RockHounds @ Missions

Follow on MiLB First Pitch  https //stza.co/+wMuR-34

Shop  https //stza.co/+wMuR-2i

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:RockHounds @ Missions
END:VALARM
DTSTART:20180623T000500Z
DTEND:20180623T030500Z
UID:TkKv7tNMLb9h4TwXlMiipNat@stanza.co
SUMMARY:RockHounds @ Missions
DESCRIPTION:RockHounds @ Missions\n\nFollow on MiLB First Pitch: https://stza.co/+wMuR-34\n\nShop: https://stza.co/+wMuR-2i\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144543Z
LAST-MODIFIED:20180213T144543Z
TRANSP:OPAQUE
END:VEVENT
* RockHounds @ Missions
<2018-06-23 Sat 19:05-22:05>
:PROPERTIES:
:ID:       xENdZClNrrdt-OdbnfWnroP9@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

RockHounds @ Missions RockHounds @ Missions

Follow on MiLB First Pitch  https //stza.co/+wMuS-30

Shop  https //stza.co/+wMuS-n

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:RockHounds @ Missions
END:VALARM
DTSTART:20180624T000500Z
DTEND:20180624T030500Z
UID:xENdZClNrrdt-OdbnfWnroP9@stanza.co
SUMMARY:RockHounds @ Missions
DESCRIPTION:RockHounds @ Missions\n\nFollow on MiLB First Pitch: https://stza.co/+wMuS-30\n\nShop: https://stza.co/+wMuS-n\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144543Z
LAST-MODIFIED:20180213T144543Z
TRANSP:OPAQUE
END:VEVENT
* RockHounds @ Missions
<2018-06-24 Sun 19:05-22:05>
:PROPERTIES:
:ID:       9At8UpOwSYoPjZ8F0aOlU5BD@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

RockHounds @ Missions RockHounds @ Missions

Follow on MiLB First Pitch  https //stza.co/+wMuT-1P

Shop  https //stza.co/+wMuT-2F

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:RockHounds @ Missions
END:VALARM
DTSTART:20180625T000500Z
DTEND:20180625T030500Z
UID:9At8UpOwSYoPjZ8F0aOlU5BD@stanza.co
SUMMARY:RockHounds @ Missions
DESCRIPTION:RockHounds @ Missions\n\nFollow on MiLB First Pitch: https://stza.co/+wMuT-1P\n\nShop: https://stza.co/+wMuT-2F\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144543Z
LAST-MODIFIED:20180213T144543Z
TRANSP:OPAQUE
END:VEVENT
* RockHounds vs. Drillers
<2018-06-28 Thu 19:00-22:00>
:PROPERTIES:
:ID:       p5SA9qc3XdT-6KcCK0Dll6EU@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

RockHounds vs. Drillers RockHounds vs. Drillers

Follow on MiLB First Pitch  https //stza.co/+wX3A-2t

Shop  https //stza.co/+wX3A-16

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:RockHounds vs. Drillers
END:VALARM
DTSTART:20180629T000000Z
DTEND:20180629T030000Z
UID:p5SA9qc3XdT-6KcCK0Dll6EU@stanza.co
SUMMARY:RockHounds vs. Drillers
DESCRIPTION:RockHounds vs. Drillers\n\nFollow on MiLB First Pitch: https://stza.co/+wX3A-2t\n\nShop: https://stza.co/+wX3A-16\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144543Z
LAST-MODIFIED:20180213T144543Z
TRANSP:OPAQUE
END:VEVENT
* RockHounds vs. Drillers
<2018-06-29 Fri 19:00-22:00>
:PROPERTIES:
:ID:       2L8wwsmEWvkp_B9yqy7nXtmM@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

RockHounds vs. Drillers RockHounds vs. Drillers

Follow on MiLB First Pitch  https //stza.co/+wX3D-Q

Shop  https //stza.co/+wX3D-3n

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:RockHounds vs. Drillers
END:VALARM
DTSTART:20180630T000000Z
DTEND:20180630T030000Z
UID:2L8wwsmEWvkp_B9yqy7nXtmM@stanza.co
SUMMARY:RockHounds vs. Drillers
DESCRIPTION:RockHounds vs. Drillers\n\nFollow on MiLB First Pitch: https://stza.co/+wX3D-Q\n\nShop: https://stza.co/+wX3D-3n\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144543Z
LAST-MODIFIED:20180213T144543Z
TRANSP:OPAQUE
END:VEVENT
* RockHounds vs. Drillers
<2018-06-30 Sat 19:00-22:00>
:PROPERTIES:
:ID:       ieI-oAs9WHlvgAAcLg7kfEqq@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

RockHounds vs. Drillers RockHounds vs. Drillers

Follow on MiLB First Pitch  https //stza.co/+wX3F-3Y

Shop  https //stza.co/+wX3F-2b

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:RockHounds vs. Drillers
END:VALARM
DTSTART:20180701T000000Z
DTEND:20180701T030000Z
UID:ieI-oAs9WHlvgAAcLg7kfEqq@stanza.co
SUMMARY:RockHounds vs. Drillers
DESCRIPTION:RockHounds vs. Drillers\n\nFollow on MiLB First Pitch: https://stza.co/+wX3F-3Y\n\nShop: https://stza.co/+wX3F-2b\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144543Z
LAST-MODIFIED:20180213T144543Z
TRANSP:OPAQUE
END:VEVENT
* RockHounds vs. Cardinals
<2018-07-01 Sun 16:00-19:00>
:PROPERTIES:
:ID:       kPeVu0ASECG0E8bdRYIieX-m@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

RockHounds vs. Cardinals RockHounds vs. Cardinals

Follow on MiLB First Pitch  https //stza.co/+wX3H-3v

Shop  https //stza.co/+wX3H-$

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:RockHounds vs. Cardinals
END:VALARM
DTSTART:20180701T210000Z
DTEND:20180702T000000Z
UID:kPeVu0ASECG0E8bdRYIieX-m@stanza.co
SUMMARY:RockHounds vs. Cardinals
DESCRIPTION:RockHounds vs. Cardinals\n\nFollow on MiLB First Pitch: https://stza.co/+wX3H-3v\n\nShop: https://stza.co/+wX3H-$\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144543Z
LAST-MODIFIED:20180213T144543Z
TRANSP:OPAQUE
END:VEVENT
* RockHounds vs. Cardinals
<2018-07-02 Mon 18:30-21:30>
:PROPERTIES:
:ID:       oF4oYkuhPCZKcyYQ3mmgSYX0@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

RockHounds vs. Cardinals RockHounds vs. Cardinals

Follow on MiLB First Pitch  https //stza.co/+wX3J-3m

Shop  https //stza.co/+wX3J-2d

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:RockHounds vs. Cardinals
END:VALARM
DTSTART:20180702T233000Z
DTEND:20180703T023000Z
UID:oF4oYkuhPCZKcyYQ3mmgSYX0@stanza.co
SUMMARY:RockHounds vs. Cardinals
DESCRIPTION:RockHounds vs. Cardinals\n\nFollow on MiLB First Pitch: https://stza.co/+wX3J-3m\n\nShop: https://stza.co/+wX3J-2d\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144543Z
LAST-MODIFIED:20180213T144543Z
TRANSP:OPAQUE
END:VEVENT
* RockHounds vs. Cardinals
<2018-07-03 Tue 18:30-21:30>
:PROPERTIES:
:ID:       czvB8iUeXc9EQ5JIZG_1w-yO@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

RockHounds vs. Cardinals RockHounds vs. Cardinals

Follow on MiLB First Pitch  https //stza.co/+wX3M-28

Shop  https //stza.co/+wX3M-3Y

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:RockHounds vs. Cardinals
END:VALARM
DTSTART:20180703T233000Z
DTEND:20180704T023000Z
UID:czvB8iUeXc9EQ5JIZG_1w-yO@stanza.co
SUMMARY:RockHounds vs. Cardinals
DESCRIPTION:RockHounds vs. Cardinals\n\nFollow on MiLB First Pitch: https://stza.co/+wX3M-28\n\nShop: https://stza.co/+wX3M-3Y\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144543Z
LAST-MODIFIED:20180213T144543Z
TRANSP:OPAQUE
END:VEVENT
* RockHounds @ Drillers
<2018-07-04 Wed 19:05-22:05>
:PROPERTIES:
:ID:       xrW_LZDyK0QgMJaix7fXHj0B@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

RockHounds @ Drillers RockHounds @ Drillers

Follow on MiLB First Pitch  https //stza.co/+w03H-2

Shop  https //stza.co/+w03H-2$

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:RockHounds @ Drillers
END:VALARM
DTSTART:20180705T000500Z
DTEND:20180705T030500Z
UID:xrW_LZDyK0QgMJaix7fXHj0B@stanza.co
SUMMARY:RockHounds @ Drillers
DESCRIPTION:RockHounds @ Drillers\n\nFollow on MiLB First Pitch: https://stza.co/+w03H-2\n\nShop: https://stza.co/+w03H-2$\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144543Z
LAST-MODIFIED:20180213T144543Z
TRANSP:OPAQUE
END:VEVENT
* RockHounds @ Drillers
<2018-07-05 Thu 19:05-22:05>
:PROPERTIES:
:ID:       snDYsBKDX9SYrmmzzK9qpuEJ@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

RockHounds @ Drillers RockHounds @ Drillers

Follow on MiLB First Pitch  https //stza.co/+w03I-3y

Shop  https //stza.co/+w03I-3_

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:RockHounds @ Drillers
END:VALARM
DTSTART:20180706T000500Z
DTEND:20180706T030500Z
UID:snDYsBKDX9SYrmmzzK9qpuEJ@stanza.co
SUMMARY:RockHounds @ Drillers
DESCRIPTION:RockHounds @ Drillers\n\nFollow on MiLB First Pitch: https://stza.co/+w03I-3y\n\nShop: https://stza.co/+w03I-3_\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144543Z
LAST-MODIFIED:20180213T144543Z
TRANSP:OPAQUE
END:VEVENT
* RockHounds @ Drillers
<2018-07-06 Fri 19:05-22:05>
:PROPERTIES:
:ID:       j4YwjjwfeJ82a4D9w8uXY1Qv@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

RockHounds @ Drillers RockHounds @ Drillers

Follow on MiLB First Pitch  https //stza.co/+w03J-1l

Shop  https //stza.co/+w03J-1e

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:RockHounds @ Drillers
END:VALARM
DTSTART:20180707T000500Z
DTEND:20180707T030500Z
UID:j4YwjjwfeJ82a4D9w8uXY1Qv@stanza.co
SUMMARY:RockHounds @ Drillers
DESCRIPTION:RockHounds @ Drillers\n\nFollow on MiLB First Pitch: https://stza.co/+w03J-1l\n\nShop: https://stza.co/+w03J-1e\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144543Z
LAST-MODIFIED:20180213T144543Z
TRANSP:OPAQUE
END:VEVENT
* RockHounds @ Cardinals
<2018-07-07 Sat 18:10-21:10>
:PROPERTIES:
:ID:       6jzZ2md-yu9ADyLPuWboeboZ@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

RockHounds @ Cardinals RockHounds @ Cardinals

Follow on MiLB First Pitch  https //stza.co/+wPN0-17

Shop  https //stza.co/+wPN0-1_

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:RockHounds @ Cardinals
END:VALARM
DTSTART:20180707T231000Z
DTEND:20180708T021000Z
UID:6jzZ2md-yu9ADyLPuWboeboZ@stanza.co
SUMMARY:RockHounds @ Cardinals
DESCRIPTION:RockHounds @ Cardinals\n\nFollow on MiLB First Pitch: https://stza.co/+wPN0-17\n\nShop: https://stza.co/+wPN0-1_\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144543Z
LAST-MODIFIED:20180213T144543Z
TRANSP:OPAQUE
END:VEVENT
* RockHounds @ Cardinals
<2018-07-08 Sun 18:10-21:10>
:PROPERTIES:
:ID:       R4bfASbiZPMAbt97U8Qhea2c@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

RockHounds @ Cardinals RockHounds @ Cardinals

Follow on MiLB First Pitch  https //stza.co/+wPN1-31

Shop  https //stza.co/+wPN1-1I

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:RockHounds @ Cardinals
END:VALARM
DTSTART:20180708T231000Z
DTEND:20180709T021000Z
UID:R4bfASbiZPMAbt97U8Qhea2c@stanza.co
SUMMARY:RockHounds @ Cardinals
DESCRIPTION:RockHounds @ Cardinals\n\nFollow on MiLB First Pitch: https://stza.co/+wPN1-31\n\nShop: https://stza.co/+wPN1-1I\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144543Z
LAST-MODIFIED:20180213T144543Z
TRANSP:OPAQUE
END:VEVENT
* RockHounds @ Cardinals
<2018-07-09 Mon 18:30-21:30>
:PROPERTIES:
:ID:       j7eW5bIbdU7ESL1l4W9k6Ky5@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

RockHounds @ Cardinals RockHounds @ Cardinals

Follow on MiLB First Pitch  https //stza.co/+wPN2-D

Shop  https //stza.co/+wPN2-1U

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:RockHounds @ Cardinals
END:VALARM
DTSTART:20180709T233000Z
DTEND:20180710T023000Z
UID:j7eW5bIbdU7ESL1l4W9k6Ky5@stanza.co
SUMMARY:RockHounds @ Cardinals
DESCRIPTION:RockHounds @ Cardinals\n\nFollow on MiLB First Pitch: https://stza.co/+wPN2-D\n\nShop: https://stza.co/+wPN2-1U\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144543Z
LAST-MODIFIED:20180213T144543Z
TRANSP:OPAQUE
END:VEVENT
* RockHounds vs. Hooks
<2018-07-11 Wed 18:30-21:30>
:PROPERTIES:
:ID:       kMPnT8KKMzOEWm8BUFGudWhx@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

RockHounds vs. Hooks RockHounds vs. Hooks

Follow on MiLB First Pitch  https //stza.co/+wX3N-2p

Shop  https //stza.co/+wX3N-w

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:RockHounds vs. Hooks
END:VALARM
DTSTART:20180711T233000Z
DTEND:20180712T023000Z
UID:kMPnT8KKMzOEWm8BUFGudWhx@stanza.co
SUMMARY:RockHounds vs. Hooks
DESCRIPTION:RockHounds vs. Hooks\n\nFollow on MiLB First Pitch: https://stza.co/+wX3N-2p\n\nShop: https://stza.co/+wX3N-w\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144543Z
LAST-MODIFIED:20180213T144543Z
TRANSP:OPAQUE
END:VEVENT
* RockHounds vs. Hooks
<2018-07-12 Thu 19:00-22:00>
:PROPERTIES:
:ID:       7QuT58COaqdBsIdEFpDTuZ2i@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

RockHounds vs. Hooks RockHounds vs. Hooks

Follow on MiLB First Pitch  https //stza.co/+wX3Q-1d

Shop  https //stza.co/+wX3Q-3V

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:RockHounds vs. Hooks
END:VALARM
DTSTART:20180713T000000Z
DTEND:20180713T030000Z
UID:7QuT58COaqdBsIdEFpDTuZ2i@stanza.co
SUMMARY:RockHounds vs. Hooks
DESCRIPTION:RockHounds vs. Hooks\n\nFollow on MiLB First Pitch: https://stza.co/+wX3Q-1d\n\nShop: https://stza.co/+wX3Q-3V\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144543Z
LAST-MODIFIED:20180213T144543Z
TRANSP:OPAQUE
END:VEVENT
* RockHounds vs. Hooks
<2018-07-13 Fri 19:00-22:00>
:PROPERTIES:
:ID:       4PDtluifefVHT9y0r8UZJf16@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

RockHounds vs. Hooks RockHounds vs. Hooks

Follow on MiLB First Pitch  https //stza.co/+wX3S-D

Shop  https //stza.co/+wX3S-C

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:RockHounds vs. Hooks
END:VALARM
DTSTART:20180714T000000Z
DTEND:20180714T030000Z
UID:4PDtluifefVHT9y0r8UZJf16@stanza.co
SUMMARY:RockHounds vs. Hooks
DESCRIPTION:RockHounds vs. Hooks\n\nFollow on MiLB First Pitch: https://stza.co/+wX3S-D\n\nShop: https://stza.co/+wX3S-C\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144543Z
LAST-MODIFIED:20180213T144543Z
TRANSP:OPAQUE
END:VEVENT
* RockHounds vs. Hooks
<2018-07-14 Sat 19:00-22:00>
:PROPERTIES:
:ID:       4FjN03lO9CP5L30PFqKdQpyb@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

RockHounds vs. Hooks RockHounds vs. Hooks

Follow on MiLB First Pitch  https //stza.co/+wX3T-3b

Shop  https //stza.co/+wX3T-_

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:RockHounds vs. Hooks
END:VALARM
DTSTART:20180715T000000Z
DTEND:20180715T030000Z
UID:4FjN03lO9CP5L30PFqKdQpyb@stanza.co
SUMMARY:RockHounds vs. Hooks
DESCRIPTION:RockHounds vs. Hooks\n\nFollow on MiLB First Pitch: https://stza.co/+wX3T-3b\n\nShop: https://stza.co/+wX3T-_\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144543Z
LAST-MODIFIED:20180213T144543Z
TRANSP:OPAQUE
END:VEVENT
* RockHounds @ Missions
<2018-07-15 Sun 18:05-21:05>
:PROPERTIES:
:ID:       ToHNi068rOD6GrPtv4KqpLZ3@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

RockHounds @ Missions RockHounds @ Missions

Follow on MiLB First Pitch  https //stza.co/+wMuV-2g

Shop  https //stza.co/+wMuV-1M

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:RockHounds @ Missions
END:VALARM
DTSTART:20180715T230500Z
DTEND:20180716T020500Z
UID:ToHNi068rOD6GrPtv4KqpLZ3@stanza.co
SUMMARY:RockHounds @ Missions
DESCRIPTION:RockHounds @ Missions\n\nFollow on MiLB First Pitch: https://stza.co/+wMuV-2g\n\nShop: https://stza.co/+wMuV-1M\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144543Z
LAST-MODIFIED:20180213T144543Z
TRANSP:OPAQUE
END:VEVENT
* RockHounds @ Missions
<2018-07-16 Mon 11:05-14:05>
:PROPERTIES:
:ID:       LuAdUffn56WMchhrts3ZXD4Z@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

RockHounds @ Missions RockHounds @ Missions

Follow on MiLB First Pitch  https //stza.co/+wMuW-1U

Shop  https //stza.co/+wMuW-H

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:RockHounds @ Missions
END:VALARM
DTSTART:20180716T160500Z
DTEND:20180716T190500Z
UID:LuAdUffn56WMchhrts3ZXD4Z@stanza.co
SUMMARY:RockHounds @ Missions
DESCRIPTION:RockHounds @ Missions\n\nFollow on MiLB First Pitch: https://stza.co/+wMuW-1U\n\nShop: https://stza.co/+wMuW-H\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144543Z
LAST-MODIFIED:20180213T144543Z
TRANSP:OPAQUE
END:VEVENT
* RockHounds @ Missions
<2018-07-17 Tue 19:05-22:05>
:PROPERTIES:
:ID:       jbkZ7a8TzJRHPUKkZ7QJr1aY@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

RockHounds @ Missions RockHounds @ Missions

Follow on MiLB First Pitch  https //stza.co/+wMuX-3k

Shop  https //stza.co/+wMuX-1V

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:RockHounds @ Missions
END:VALARM
DTSTART:20180718T000500Z
DTEND:20180718T030500Z
UID:jbkZ7a8TzJRHPUKkZ7QJr1aY@stanza.co
SUMMARY:RockHounds @ Missions
DESCRIPTION:RockHounds @ Missions\n\nFollow on MiLB First Pitch: https://stza.co/+wMuX-3k\n\nShop: https://stza.co/+wMuX-1V\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144543Z
LAST-MODIFIED:20180213T144543Z
TRANSP:OPAQUE
END:VEVENT
* RockHounds @ Missions
<2018-07-18 Wed 19:05-22:05>
:PROPERTIES:
:ID:       s-wu1xMbXydhtbjcm5vwBTR7@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

RockHounds @ Missions RockHounds @ Missions

Follow on MiLB First Pitch  https //stza.co/+wMuY-j

Shop  https //stza.co/+wMuY-22

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:RockHounds @ Missions
END:VALARM
DTSTART:20180719T000500Z
DTEND:20180719T030500Z
UID:s-wu1xMbXydhtbjcm5vwBTR7@stanza.co
SUMMARY:RockHounds @ Missions
DESCRIPTION:RockHounds @ Missions\n\nFollow on MiLB First Pitch: https://stza.co/+wMuY-j\n\nShop: https://stza.co/+wMuY-22\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144543Z
LAST-MODIFIED:20180213T144543Z
TRANSP:OPAQUE
END:VEVENT
* RockHounds vs. Hooks
<2018-07-19 Thu 19:00-22:00>
:PROPERTIES:
:ID:       Sjfqlc6UxI9ywqHT7y4GWMZJ@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

RockHounds vs. Hooks RockHounds vs. Hooks

Follow on MiLB First Pitch  https //stza.co/+wX3X-13

Shop  https //stza.co/+wX3X-2o

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:RockHounds vs. Hooks
END:VALARM
DTSTART:20180720T000000Z
DTEND:20180720T030000Z
UID:Sjfqlc6UxI9ywqHT7y4GWMZJ@stanza.co
SUMMARY:RockHounds vs. Hooks
DESCRIPTION:RockHounds vs. Hooks\n\nFollow on MiLB First Pitch: https://stza.co/+wX3X-13\n\nShop: https://stza.co/+wX3X-2o\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144543Z
LAST-MODIFIED:20180213T144543Z
TRANSP:OPAQUE
END:VEVENT
* RockHounds vs. Hooks
<2018-07-20 Fri 19:00-22:00>
:PROPERTIES:
:ID:       noz4yKKlfO6uG8fFUfLLOJ80@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

RockHounds vs. Hooks RockHounds vs. Hooks

Follow on MiLB First Pitch  https //stza.co/+wX3Y-25

Shop  https //stza.co/+wX3Y-2v

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:RockHounds vs. Hooks
END:VALARM
DTSTART:20180721T000000Z
DTEND:20180721T030000Z
UID:noz4yKKlfO6uG8fFUfLLOJ80@stanza.co
SUMMARY:RockHounds vs. Hooks
DESCRIPTION:RockHounds vs. Hooks\n\nFollow on MiLB First Pitch: https://stza.co/+wX3Y-25\n\nShop: https://stza.co/+wX3Y-2v\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144543Z
LAST-MODIFIED:20180213T144543Z
TRANSP:OPAQUE
END:VEVENT
* RockHounds vs. Hooks
<2018-07-21 Sat 19:00-22:00>
:PROPERTIES:
:ID:       OZgfKkcUqRbl6JwhUKHhA4rj@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

RockHounds vs. Hooks RockHounds vs. Hooks

Follow on MiLB First Pitch  https //stza.co/+wX3_-1u

Shop  https //stza.co/+wX3_-1g

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:RockHounds vs. Hooks
END:VALARM
DTSTART:20180722T000000Z
DTEND:20180722T030000Z
UID:OZgfKkcUqRbl6JwhUKHhA4rj@stanza.co
SUMMARY:RockHounds vs. Hooks
DESCRIPTION:RockHounds vs. Hooks\n\nFollow on MiLB First Pitch: https://stza.co/+wX3_-1u\n\nShop: https://stza.co/+wX3_-1g\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144543Z
LAST-MODIFIED:20180213T144543Z
TRANSP:OPAQUE
END:VEVENT
* RockHounds vs. Hooks
<2018-07-22 Sun 14:00-17:00>
:PROPERTIES:
:ID:       1DGPXd6HlgLj2UCmftMOkRhv@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

RockHounds vs. Hooks RockHounds vs. Hooks

Follow on MiLB First Pitch  https //stza.co/+wX42-2R

Shop  https //stza.co/+wX42-c

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:RockHounds vs. Hooks
END:VALARM
DTSTART:20180722T190000Z
DTEND:20180722T220000Z
UID:1DGPXd6HlgLj2UCmftMOkRhv@stanza.co
SUMMARY:RockHounds vs. Hooks
DESCRIPTION:RockHounds vs. Hooks\n\nFollow on MiLB First Pitch: https://stza.co/+wX42-2R\n\nShop: https://stza.co/+wX42-c\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144543Z
LAST-MODIFIED:20180213T144543Z
TRANSP:OPAQUE
END:VEVENT
* RockHounds @ RoughRiders
<2018-07-23 Mon 19:05-22:05>
:PROPERTIES:
:ID:       j6Pp1HHZpl8pNYgS4pn0QUim@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

RockHounds @ RoughRiders RockHounds @ RoughRiders

Follow on MiLB First Pitch  https //stza.co/+wYaM-2S

Shop  https //stza.co/+wYaM-20

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:RockHounds @ RoughRiders
END:VALARM
DTSTART:20180724T000500Z
DTEND:20180724T030500Z
UID:j6Pp1HHZpl8pNYgS4pn0QUim@stanza.co
SUMMARY:RockHounds @ RoughRiders
DESCRIPTION:RockHounds @ RoughRiders\n\nFollow on MiLB First Pitch: https://stza.co/+wYaM-2S\n\nShop: https://stza.co/+wYaM-20\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144543Z
LAST-MODIFIED:20180213T144543Z
TRANSP:OPAQUE
END:VEVENT
* RockHounds @ RoughRiders
<2018-07-24 Tue 19:05-22:05>
:PROPERTIES:
:ID:       8BmqqMjVzTnTXzAkbf5HbAEJ@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

RockHounds @ RoughRiders RockHounds @ RoughRiders

Follow on MiLB First Pitch  https //stza.co/+wYaN-3N

Shop  https //stza.co/+wYaN-1M

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:RockHounds @ RoughRiders
END:VALARM
DTSTART:20180725T000500Z
DTEND:20180725T030500Z
UID:8BmqqMjVzTnTXzAkbf5HbAEJ@stanza.co
SUMMARY:RockHounds @ RoughRiders
DESCRIPTION:RockHounds @ RoughRiders\n\nFollow on MiLB First Pitch: https://stza.co/+wYaN-3N\n\nShop: https://stza.co/+wYaN-1M\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144543Z
LAST-MODIFIED:20180213T144543Z
TRANSP:OPAQUE
END:VEVENT
* RockHounds @ RoughRiders
<2018-07-25 Wed 19:05-22:05>
:PROPERTIES:
:ID:       LZJXeRWc5jlFe0xEgtKlYOk8@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

RockHounds @ RoughRiders RockHounds @ RoughRiders

Follow on MiLB First Pitch  https //stza.co/+wYaP-3Q

Shop  https //stza.co/+wYaP-3V

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:RockHounds @ RoughRiders
END:VALARM
DTSTART:20180726T000500Z
DTEND:20180726T030500Z
UID:LZJXeRWc5jlFe0xEgtKlYOk8@stanza.co
SUMMARY:RockHounds @ RoughRiders
DESCRIPTION:RockHounds @ RoughRiders\n\nFollow on MiLB First Pitch: https://stza.co/+wYaP-3Q\n\nShop: https://stza.co/+wYaP-3V\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144543Z
LAST-MODIFIED:20180213T144543Z
TRANSP:OPAQUE
END:VEVENT
* RockHounds @ Hooks
<2018-07-26 Thu 19:05-22:05>
:PROPERTIES:
:ID:       TpjsLiR80mtkqZgAQ_iYvssT@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

RockHounds @ Hooks RockHounds @ Hooks

Follow on MiLB First Pitch  https //stza.co/+xzHI-1U

Shop  https //stza.co/+xzHI-R

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:RockHounds @ Hooks
END:VALARM
DTSTART:20180727T000500Z
DTEND:20180727T030500Z
UID:TpjsLiR80mtkqZgAQ_iYvssT@stanza.co
SUMMARY:RockHounds @ Hooks
DESCRIPTION:RockHounds @ Hooks\n\nFollow on MiLB First Pitch: https://stza.co/+xzHI-1U\n\nShop: https://stza.co/+xzHI-R\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144543Z
LAST-MODIFIED:20180213T144543Z
TRANSP:OPAQUE
END:VEVENT
* RockHounds @ Hooks
<2018-07-27 Fri 19:05-22:05>
:PROPERTIES:
:ID:       8vHaQwECDeH9QzNQCYr_ab3i@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

RockHounds @ Hooks RockHounds @ Hooks

Follow on MiLB First Pitch  https //stza.co/+xzHJ-3M

Shop  https //stza.co/+xzHJ-W

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:RockHounds @ Hooks
END:VALARM
DTSTART:20180728T000500Z
DTEND:20180728T030500Z
UID:8vHaQwECDeH9QzNQCYr_ab3i@stanza.co
SUMMARY:RockHounds @ Hooks
DESCRIPTION:RockHounds @ Hooks\n\nFollow on MiLB First Pitch: https://stza.co/+xzHJ-3M\n\nShop: https://stza.co/+xzHJ-W\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144543Z
LAST-MODIFIED:20180213T144543Z
TRANSP:OPAQUE
END:VEVENT
* RockHounds @ Hooks
<2018-07-28 Sat 19:05-22:05>
:PROPERTIES:
:ID:       8pG_xb7cbIgzQ5pMnlcr8Ov2@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

RockHounds @ Hooks RockHounds @ Hooks

Follow on MiLB First Pitch  https //stza.co/+xzHK-E

Shop  https //stza.co/+xzHK-B

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:RockHounds @ Hooks
END:VALARM
DTSTART:20180729T000500Z
DTEND:20180729T030500Z
UID:8pG_xb7cbIgzQ5pMnlcr8Ov2@stanza.co
SUMMARY:RockHounds @ Hooks
DESCRIPTION:RockHounds @ Hooks\n\nFollow on MiLB First Pitch: https://stza.co/+xzHK-E\n\nShop: https://stza.co/+xzHK-B\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144543Z
LAST-MODIFIED:20180213T144543Z
TRANSP:OPAQUE
END:VEVENT
* RockHounds @ Hooks
<2018-07-29 Sun 18:05-21:05>
:PROPERTIES:
:ID:       rR4ocQpFACuufrbH4D8venOG@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

RockHounds @ Hooks RockHounds @ Hooks

Follow on MiLB First Pitch  https //stza.co/+xzHL-3A

Shop  https //stza.co/+xzHL-3F

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:RockHounds @ Hooks
END:VALARM
DTSTART:20180729T230500Z
DTEND:20180730T020500Z
UID:rR4ocQpFACuufrbH4D8venOG@stanza.co
SUMMARY:RockHounds @ Hooks
DESCRIPTION:RockHounds @ Hooks\n\nFollow on MiLB First Pitch: https://stza.co/+xzHL-3A\n\nShop: https://stza.co/+xzHL-3F\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144543Z
LAST-MODIFIED:20180213T144543Z
TRANSP:OPAQUE
END:VEVENT
* RockHounds vs. RoughRiders
<2018-07-30 Mon 18:30-21:30>
:PROPERTIES:
:ID:       V8TnkCyQZUv4QuzvSrAFNv3Z@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

RockHounds vs. RoughRiders RockHounds vs. RoughRiders

Follow on MiLB First Pitch  https //stza.co/+wX45-G

Shop  https //stza.co/+wX45-2y

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:RockHounds vs. RoughRiders
END:VALARM
DTSTART:20180730T233000Z
DTEND:20180731T023000Z
UID:V8TnkCyQZUv4QuzvSrAFNv3Z@stanza.co
SUMMARY:RockHounds vs. RoughRiders
DESCRIPTION:RockHounds vs. RoughRiders\n\nFollow on MiLB First Pitch: https://stza.co/+wX45-G\n\nShop: https://stza.co/+wX45-2y\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144543Z
LAST-MODIFIED:20180213T144543Z
TRANSP:OPAQUE
END:VEVENT
* RockHounds vs. RoughRiders
<2018-07-31 Tue 18:30-21:30>
:PROPERTIES:
:ID:       K8tiIWYsGYdzYnnoXnZRgfEg@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

RockHounds vs. RoughRiders RockHounds vs. RoughRiders

Follow on MiLB First Pitch  https //stza.co/+wX47-3E

Shop  https //stza.co/+wX47-g

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:RockHounds vs. RoughRiders
END:VALARM
DTSTART:20180731T233000Z
DTEND:20180801T023000Z
UID:K8tiIWYsGYdzYnnoXnZRgfEg@stanza.co
SUMMARY:RockHounds vs. RoughRiders
DESCRIPTION:RockHounds vs. RoughRiders\n\nFollow on MiLB First Pitch: https://stza.co/+wX47-3E\n\nShop: https://stza.co/+wX47-g\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144543Z
LAST-MODIFIED:20180213T144543Z
TRANSP:OPAQUE
END:VEVENT
* RockHounds vs. RoughRiders
<2018-08-01 Wed 18:30-21:30>
:PROPERTIES:
:ID:       rTXV9Bo1AeeclnNQaQ1fKcuy@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

RockHounds vs. RoughRiders RockHounds vs. RoughRiders

Follow on MiLB First Pitch  https //stza.co/+wX48-O

Shop  https //stza.co/+wX48-2u

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:RockHounds vs. RoughRiders
END:VALARM
DTSTART:20180801T233000Z
DTEND:20180802T023000Z
UID:rTXV9Bo1AeeclnNQaQ1fKcuy@stanza.co
SUMMARY:RockHounds vs. RoughRiders
DESCRIPTION:RockHounds vs. RoughRiders\n\nFollow on MiLB First Pitch: https://stza.co/+wX48-O\n\nShop: https://stza.co/+wX48-2u\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144543Z
LAST-MODIFIED:20180213T144543Z
TRANSP:OPAQUE
END:VEVENT
* RockHounds vs. Missions
<2018-08-02 Thu 19:00-22:00>
:PROPERTIES:
:ID:       83HQCYCpM4ap2ZhLvrCwN7pw@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

RockHounds vs. Missions RockHounds vs. Missions

Follow on MiLB First Pitch  https //stza.co/+wX4b-3u

Shop  https //stza.co/+wX4b-3O

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:RockHounds vs. Missions
END:VALARM
DTSTART:20180803T000000Z
DTEND:20180803T030000Z
UID:83HQCYCpM4ap2ZhLvrCwN7pw@stanza.co
SUMMARY:RockHounds vs. Missions
DESCRIPTION:RockHounds vs. Missions\n\nFollow on MiLB First Pitch: https://stza.co/+wX4b-3u\n\nShop: https://stza.co/+wX4b-3O\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144543Z
LAST-MODIFIED:20180213T144543Z
TRANSP:OPAQUE
END:VEVENT
* RockHounds vs. Missions
<2018-08-03 Fri 19:00-22:00>
:PROPERTIES:
:ID:       rrCsUiVdcSfbjWPivVb2ZWY-@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

RockHounds vs. Missions RockHounds vs. Missions

Follow on MiLB First Pitch  https //stza.co/+wX4c-M

Shop  https //stza.co/+wX4c-3L

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:RockHounds vs. Missions
END:VALARM
DTSTART:20180804T000000Z
DTEND:20180804T030000Z
UID:rrCsUiVdcSfbjWPivVb2ZWY-@stanza.co
SUMMARY:RockHounds vs. Missions
DESCRIPTION:RockHounds vs. Missions\n\nFollow on MiLB First Pitch: https://stza.co/+wX4c-M\n\nShop: https://stza.co/+wX4c-3L\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144543Z
LAST-MODIFIED:20180213T144543Z
TRANSP:OPAQUE
END:VEVENT
* RockHounds vs. Missions
<2018-08-04 Sat 19:00-22:00>
:PROPERTIES:
:ID:       68WrnfpHLAy2G11gFGxP6ooO@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

RockHounds vs. Missions RockHounds vs. Missions

Follow on MiLB First Pitch  https //stza.co/+wX4f-2o

Shop  https //stza.co/+wX4f-B

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:RockHounds vs. Missions
END:VALARM
DTSTART:20180805T000000Z
DTEND:20180805T030000Z
UID:68WrnfpHLAy2G11gFGxP6ooO@stanza.co
SUMMARY:RockHounds vs. Missions
DESCRIPTION:RockHounds vs. Missions\n\nFollow on MiLB First Pitch: https://stza.co/+wX4f-2o\n\nShop: https://stza.co/+wX4f-B\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144543Z
LAST-MODIFIED:20180213T144543Z
TRANSP:OPAQUE
END:VEVENT
* RockHounds vs. Missions
<2018-08-05 Sun 14:00-17:00>
:PROPERTIES:
:ID:       nVDfDieMPFvmRUnPXTE3vgJc@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

RockHounds vs. Missions RockHounds vs. Missions

Follow on MiLB First Pitch  https //stza.co/+wX4h-2K

Shop  https //stza.co/+wX4h-3Q

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:RockHounds vs. Missions
END:VALARM
DTSTART:20180805T190000Z
DTEND:20180805T220000Z
UID:nVDfDieMPFvmRUnPXTE3vgJc@stanza.co
SUMMARY:RockHounds vs. Missions
DESCRIPTION:RockHounds vs. Missions\n\nFollow on MiLB First Pitch: https://stza.co/+wX4h-2K\n\nShop: https://stza.co/+wX4h-3Q\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144543Z
LAST-MODIFIED:20180213T144543Z
TRANSP:OPAQUE
END:VEVENT
* RockHounds @ Naturals
<2018-08-07 Tue 19:05-22:05>
:PROPERTIES:
:ID:       PxWhokqKt77Sw6aLZwfZjdzA@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

RockHounds @ Naturals RockHounds @ Naturals

Follow on MiLB First Pitch  https //stza.co/+wi0w-i

Shop  https //stza.co/+wi0w-1h

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:RockHounds @ Naturals
END:VALARM
DTSTART:20180808T000500Z
DTEND:20180808T030500Z
UID:PxWhokqKt77Sw6aLZwfZjdzA@stanza.co
SUMMARY:RockHounds @ Naturals
DESCRIPTION:RockHounds @ Naturals\n\nFollow on MiLB First Pitch: https://stza.co/+wi0w-i\n\nShop: https://stza.co/+wi0w-1h\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144543Z
LAST-MODIFIED:20180213T144543Z
TRANSP:OPAQUE
END:VEVENT
* RockHounds @ Naturals
<2018-08-08 Wed 19:05-22:05>
:PROPERTIES:
:ID:       sSprm2TncL8PWcFuD8HIidpl@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

RockHounds @ Naturals RockHounds @ Naturals

Follow on MiLB First Pitch  https //stza.co/+wi0x-21

Shop  https //stza.co/+wi0x-1Z

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:RockHounds @ Naturals
END:VALARM
DTSTART:20180809T000500Z
DTEND:20180809T030500Z
UID:sSprm2TncL8PWcFuD8HIidpl@stanza.co
SUMMARY:RockHounds @ Naturals
DESCRIPTION:RockHounds @ Naturals\n\nFollow on MiLB First Pitch: https://stza.co/+wi0x-21\n\nShop: https://stza.co/+wi0x-1Z\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144543Z
LAST-MODIFIED:20180213T144543Z
TRANSP:OPAQUE
END:VEVENT
* RockHounds @ Naturals
<2018-08-09 Thu 19:05-22:05>
:PROPERTIES:
:ID:       dInCrKaU1KxuY0mgLS2Q6kjg@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

RockHounds @ Naturals RockHounds @ Naturals

Follow on MiLB First Pitch  https //stza.co/+wi0y-1x

Shop  https //stza.co/+wi0y-2u

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:RockHounds @ Naturals
END:VALARM
DTSTART:20180810T000500Z
DTEND:20180810T030500Z
UID:dInCrKaU1KxuY0mgLS2Q6kjg@stanza.co
SUMMARY:RockHounds @ Naturals
DESCRIPTION:RockHounds @ Naturals\n\nFollow on MiLB First Pitch: https://stza.co/+wi0y-1x\n\nShop: https://stza.co/+wi0y-2u\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144543Z
LAST-MODIFIED:20180213T144543Z
TRANSP:OPAQUE
END:VEVENT
* RockHounds @ Travelers
<2018-08-10 Fri 19:10-22:10>
:PROPERTIES:
:ID:       QP-J10kJ0mRpjJLN_pZbaOfV@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

RockHounds @ Travelers RockHounds @ Travelers

Follow on MiLB First Pitch  https //stza.co/+w00v-3l

Shop  https //stza.co/+w00v-3z

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:RockHounds @ Travelers
END:VALARM
DTSTART:20180811T001000Z
DTEND:20180811T031000Z
UID:QP-J10kJ0mRpjJLN_pZbaOfV@stanza.co
SUMMARY:RockHounds @ Travelers
DESCRIPTION:RockHounds @ Travelers\n\nFollow on MiLB First Pitch: https://stza.co/+w00v-3l\n\nShop: https://stza.co/+w00v-3z\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144543Z
LAST-MODIFIED:20180213T144543Z
TRANSP:OPAQUE
END:VEVENT
* RockHounds @ Travelers
<2018-08-11 Sat 18:10-21:10>
:PROPERTIES:
:ID:       aTcTIO4KvH5hpN3g2I62xTHc@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

RockHounds @ Travelers RockHounds @ Travelers

Follow on MiLB First Pitch  https //stza.co/+w00w-1c

Shop  https //stza.co/+w00w-18

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:RockHounds @ Travelers
END:VALARM
DTSTART:20180811T231000Z
DTEND:20180812T021000Z
UID:aTcTIO4KvH5hpN3g2I62xTHc@stanza.co
SUMMARY:RockHounds @ Travelers
DESCRIPTION:RockHounds @ Travelers\n\nFollow on MiLB First Pitch: https://stza.co/+w00w-1c\n\nShop: https://stza.co/+w00w-18\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144543Z
LAST-MODIFIED:20180213T144543Z
TRANSP:OPAQUE
END:VEVENT
* RockHounds @ Travelers
<2018-08-12 Sun 14:10-17:10>
:PROPERTIES:
:ID:       xkzkXK0_h8HwJHXMoEFrHt7P@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

RockHounds @ Travelers RockHounds @ Travelers

Follow on MiLB First Pitch  https //stza.co/+w00x-2v

Shop  https //stza.co/+w00x-2w

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:RockHounds @ Travelers
END:VALARM
DTSTART:20180812T191000Z
DTEND:20180812T221000Z
UID:xkzkXK0_h8HwJHXMoEFrHt7P@stanza.co
SUMMARY:RockHounds @ Travelers
DESCRIPTION:RockHounds @ Travelers\n\nFollow on MiLB First Pitch: https://stza.co/+w00x-2v\n\nShop: https://stza.co/+w00x-2w\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144543Z
LAST-MODIFIED:20180213T144543Z
TRANSP:OPAQUE
END:VEVENT
* RockHounds vs. Naturals
<2018-08-14 Tue 18:30-21:30>
:PROPERTIES:
:ID:       LmluIwen3IgXzYXQwJdq0Mb3@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

RockHounds vs. Naturals RockHounds vs. Naturals

Follow on MiLB First Pitch  https //stza.co/+wX4l-3w

Shop  https //stza.co/+wX4l-2U

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:RockHounds vs. Naturals
END:VALARM
DTSTART:20180814T233000Z
DTEND:20180815T023000Z
UID:LmluIwen3IgXzYXQwJdq0Mb3@stanza.co
SUMMARY:RockHounds vs. Naturals
DESCRIPTION:RockHounds vs. Naturals\n\nFollow on MiLB First Pitch: https://stza.co/+wX4l-3w\n\nShop: https://stza.co/+wX4l-2U\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144543Z
LAST-MODIFIED:20180213T144543Z
TRANSP:OPAQUE
END:VEVENT
* RockHounds vs. Naturals
<2018-08-15 Wed 18:30-21:30>
:PROPERTIES:
:ID:       SnOj3hnPGXBGRfNBNnS1uzir@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

RockHounds vs. Naturals RockHounds vs. Naturals

Follow on MiLB First Pitch  https //stza.co/+wX4m-2y

Shop  https //stza.co/+wX4m-1K

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:RockHounds vs. Naturals
END:VALARM
DTSTART:20180815T233000Z
DTEND:20180816T023000Z
UID:SnOj3hnPGXBGRfNBNnS1uzir@stanza.co
SUMMARY:RockHounds vs. Naturals
DESCRIPTION:RockHounds vs. Naturals\n\nFollow on MiLB First Pitch: https://stza.co/+wX4m-2y\n\nShop: https://stza.co/+wX4m-1K\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144543Z
LAST-MODIFIED:20180213T144543Z
TRANSP:OPAQUE
END:VEVENT
* RockHounds vs. Naturals
<2018-08-16 Thu 19:00-22:00>
:PROPERTIES:
:ID:       q2TF6fT1GCmrSfpsM7eTNt23@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

RockHounds vs. Naturals RockHounds vs. Naturals

Follow on MiLB First Pitch  https //stza.co/+wX4q-2I

Shop  https //stza.co/+wX4q-3Z

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:RockHounds vs. Naturals
END:VALARM
DTSTART:20180817T000000Z
DTEND:20180817T030000Z
UID:q2TF6fT1GCmrSfpsM7eTNt23@stanza.co
SUMMARY:RockHounds vs. Naturals
DESCRIPTION:RockHounds vs. Naturals\n\nFollow on MiLB First Pitch: https://stza.co/+wX4q-2I\n\nShop: https://stza.co/+wX4q-3Z\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144543Z
LAST-MODIFIED:20180213T144543Z
TRANSP:OPAQUE
END:VEVENT
* RockHounds vs. Travelers
<2018-08-17 Fri 19:00-22:00>
:PROPERTIES:
:ID:       rqjLgN1QdiVUqCs6q0qYI6s2@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

RockHounds vs. Travelers RockHounds vs. Travelers

Follow on MiLB First Pitch  https //stza.co/+wX4r-1l

Shop  https //stza.co/+wX4r-30

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:RockHounds vs. Travelers
END:VALARM
DTSTART:20180818T000000Z
DTEND:20180818T030000Z
UID:rqjLgN1QdiVUqCs6q0qYI6s2@stanza.co
SUMMARY:RockHounds vs. Travelers
DESCRIPTION:RockHounds vs. Travelers\n\nFollow on MiLB First Pitch: https://stza.co/+wX4r-1l\n\nShop: https://stza.co/+wX4r-30\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144543Z
LAST-MODIFIED:20180213T144543Z
TRANSP:OPAQUE
END:VEVENT
* RockHounds vs. Travelers
<2018-08-18 Sat 19:00-22:00>
:PROPERTIES:
:ID:       Pc3Uk1SpchAkLZlyHSTzBKNM@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

RockHounds vs. Travelers RockHounds vs. Travelers

Follow on MiLB First Pitch  https //stza.co/+wX4u-2F

Shop  https //stza.co/+wX4u-2m

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:RockHounds vs. Travelers
END:VALARM
DTSTART:20180819T000000Z
DTEND:20180819T030000Z
UID:Pc3Uk1SpchAkLZlyHSTzBKNM@stanza.co
SUMMARY:RockHounds vs. Travelers
DESCRIPTION:RockHounds vs. Travelers\n\nFollow on MiLB First Pitch: https://stza.co/+wX4u-2F\n\nShop: https://stza.co/+wX4u-2m\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144543Z
LAST-MODIFIED:20180213T144543Z
TRANSP:OPAQUE
END:VEVENT
* RockHounds vs. Travelers
<2018-08-19 Sun 14:00-17:00>
:PROPERTIES:
:ID:       ywul0FioU2GV8k6O54Q9ppT3@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

RockHounds vs. Travelers RockHounds vs. Travelers

Follow on MiLB First Pitch  https //stza.co/+wX4v-1T

Shop  https //stza.co/+wX4v-G

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:RockHounds vs. Travelers
END:VALARM
DTSTART:20180819T190000Z
DTEND:20180819T220000Z
UID:ywul0FioU2GV8k6O54Q9ppT3@stanza.co
SUMMARY:RockHounds vs. Travelers
DESCRIPTION:RockHounds vs. Travelers\n\nFollow on MiLB First Pitch: https://stza.co/+wX4v-1T\n\nShop: https://stza.co/+wX4v-G\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144543Z
LAST-MODIFIED:20180213T144543Z
TRANSP:OPAQUE
END:VEVENT
* RockHounds @ Hooks
<2018-08-21 Tue 19:05-22:05>
:PROPERTIES:
:ID:       _UUl4KRN3ZqYTggsRBTMXBWI@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

RockHounds @ Hooks RockHounds @ Hooks

Follow on MiLB First Pitch  https //stza.co/+xzHM-1J

Shop  https //stza.co/+xzHM-I

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:RockHounds @ Hooks
END:VALARM
DTSTART:20180822T000500Z
DTEND:20180822T030500Z
UID:_UUl4KRN3ZqYTggsRBTMXBWI@stanza.co
SUMMARY:RockHounds @ Hooks
DESCRIPTION:RockHounds @ Hooks\n\nFollow on MiLB First Pitch: https://stza.co/+xzHM-1J\n\nShop: https://stza.co/+xzHM-I\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144543Z
LAST-MODIFIED:20180213T144543Z
TRANSP:OPAQUE
END:VEVENT
* RockHounds @ Hooks
<2018-08-22 Wed 19:05-22:05>
:PROPERTIES:
:ID:       XD5fTsMC3Zg6t6Rx8fvyhllg@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

RockHounds @ Hooks RockHounds @ Hooks

Follow on MiLB First Pitch  https //stza.co/+xzHN-t

Shop  https //stza.co/+xzHN-3S

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:RockHounds @ Hooks
END:VALARM
DTSTART:20180823T000500Z
DTEND:20180823T030500Z
UID:XD5fTsMC3Zg6t6Rx8fvyhllg@stanza.co
SUMMARY:RockHounds @ Hooks
DESCRIPTION:RockHounds @ Hooks\n\nFollow on MiLB First Pitch: https://stza.co/+xzHN-t\n\nShop: https://stza.co/+xzHN-3S\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144543Z
LAST-MODIFIED:20180213T144543Z
TRANSP:OPAQUE
END:VEVENT
* RockHounds @ Hooks
<2018-08-23 Thu 19:05-22:05>
:PROPERTIES:
:ID:       3AFxw2UUTCB49zvtN3mFnc0l@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

RockHounds @ Hooks RockHounds @ Hooks

Follow on MiLB First Pitch  https //stza.co/+xzHO-14

Shop  https //stza.co/+xzHO-p

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:RockHounds @ Hooks
END:VALARM
DTSTART:20180824T000500Z
DTEND:20180824T030500Z
UID:3AFxw2UUTCB49zvtN3mFnc0l@stanza.co
SUMMARY:RockHounds @ Hooks
DESCRIPTION:RockHounds @ Hooks\n\nFollow on MiLB First Pitch: https://stza.co/+xzHO-14\n\nShop: https://stza.co/+xzHO-p\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144543Z
LAST-MODIFIED:20180213T144543Z
TRANSP:OPAQUE
END:VEVENT
* RockHounds @ Hooks
<2018-08-24 Fri 19:05-22:05>
:PROPERTIES:
:ID:       N4iWv7fRYSFwzFS3d4rBf-YA@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

RockHounds @ Hooks RockHounds @ Hooks

Follow on MiLB First Pitch  https //stza.co/+xzHP-2$

Shop  https //stza.co/+xzHP-1v

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:RockHounds @ Hooks
END:VALARM
DTSTART:20180825T000500Z
DTEND:20180825T030500Z
UID:N4iWv7fRYSFwzFS3d4rBf-YA@stanza.co
SUMMARY:RockHounds @ Hooks
DESCRIPTION:RockHounds @ Hooks\n\nFollow on MiLB First Pitch: https://stza.co/+xzHP-2$\n\nShop: https://stza.co/+xzHP-1v\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144543Z
LAST-MODIFIED:20180213T144543Z
TRANSP:OPAQUE
END:VEVENT
* RockHounds @ RoughRiders
<2018-08-25 Sat 19:05-22:05>
:PROPERTIES:
:ID:       rotieoWr5aBu1ZrLyG2DXecZ@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

RockHounds @ RoughRiders RockHounds @ RoughRiders

Follow on MiLB First Pitch  https //stza.co/+wYaQ-2l

Shop  https //stza.co/+wYaQ-21

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:RockHounds @ RoughRiders
END:VALARM
DTSTART:20180826T000500Z
DTEND:20180826T030500Z
UID:rotieoWr5aBu1ZrLyG2DXecZ@stanza.co
SUMMARY:RockHounds @ RoughRiders
DESCRIPTION:RockHounds @ RoughRiders\n\nFollow on MiLB First Pitch: https://stza.co/+wYaQ-2l\n\nShop: https://stza.co/+wYaQ-21\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144543Z
LAST-MODIFIED:20180213T144543Z
TRANSP:OPAQUE
END:VEVENT
* RockHounds @ RoughRiders
<2018-08-26 Sun 19:05-22:05>
:PROPERTIES:
:ID:       GnKbs-5hyHYRCdgsgW48S1Yp@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

RockHounds @ RoughRiders RockHounds @ RoughRiders

Follow on MiLB First Pitch  https //stza.co/+wYaS-1

Shop  https //stza.co/+wYaS-2d

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:RockHounds @ RoughRiders
END:VALARM
DTSTART:20180827T000500Z
DTEND:20180827T030500Z
UID:GnKbs-5hyHYRCdgsgW48S1Yp@stanza.co
SUMMARY:RockHounds @ RoughRiders
DESCRIPTION:RockHounds @ RoughRiders\n\nFollow on MiLB First Pitch: https://stza.co/+wYaS-1\n\nShop: https://stza.co/+wYaS-2d\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144543Z
LAST-MODIFIED:20180213T144543Z
TRANSP:OPAQUE
END:VEVENT
* RockHounds @ RoughRiders
<2018-08-27 Mon 19:05-22:05>
:PROPERTIES:
:ID:       cM-FTvlRemwFBherk7a4k1Am@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

RockHounds @ RoughRiders RockHounds @ RoughRiders

Follow on MiLB First Pitch  https //stza.co/+wYaT-10

Shop  https //stza.co/+wYaT-15

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:RockHounds @ RoughRiders
END:VALARM
DTSTART:20180828T000500Z
DTEND:20180828T030500Z
UID:cM-FTvlRemwFBherk7a4k1Am@stanza.co
SUMMARY:RockHounds @ RoughRiders
DESCRIPTION:RockHounds @ RoughRiders\n\nFollow on MiLB First Pitch: https://stza.co/+wYaT-10\n\nShop: https://stza.co/+wYaT-15\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144543Z
LAST-MODIFIED:20180213T144543Z
TRANSP:OPAQUE
END:VEVENT
* RockHounds vs. Missions
<2018-08-28 Tue 18:30-21:30>
:PROPERTIES:
:ID:       dU7FeMsjWF24375xjpQhCiRz@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

RockHounds vs. Missions RockHounds vs. Missions

Follow on MiLB First Pitch  https //stza.co/+wX4y-B

Shop  https //stza.co/+wX4y-W

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:RockHounds vs. Missions
END:VALARM
DTSTART:20180828T233000Z
DTEND:20180829T023000Z
UID:dU7FeMsjWF24375xjpQhCiRz@stanza.co
SUMMARY:RockHounds vs. Missions
DESCRIPTION:RockHounds vs. Missions\n\nFollow on MiLB First Pitch: https://stza.co/+wX4y-B\n\nShop: https://stza.co/+wX4y-W\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144543Z
LAST-MODIFIED:20180213T144543Z
TRANSP:OPAQUE
END:VEVENT
* RockHounds vs. Missions
<2018-08-29 Wed 18:30-21:30>
:PROPERTIES:
:ID:       AXE86S3IQWReGnWiutXF9xGA@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

RockHounds vs. Missions RockHounds vs. Missions

Follow on MiLB First Pitch  https //stza.co/+wX4A-3x

Shop  https //stza.co/+wX4A-V

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:RockHounds vs. Missions
END:VALARM
DTSTART:20180829T233000Z
DTEND:20180830T023000Z
UID:AXE86S3IQWReGnWiutXF9xGA@stanza.co
SUMMARY:RockHounds vs. Missions
DESCRIPTION:RockHounds vs. Missions\n\nFollow on MiLB First Pitch: https://stza.co/+wX4A-3x\n\nShop: https://stza.co/+wX4A-V\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144543Z
LAST-MODIFIED:20180213T144543Z
TRANSP:OPAQUE
END:VEVENT
* RockHounds vs. Missions
<2018-08-30 Thu 19:00-22:00>
:PROPERTIES:
:ID:       1MyHSaO7lrg_qq_cgy02tdcf@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

RockHounds vs. Missions RockHounds vs. Missions

Follow on MiLB First Pitch  https //stza.co/+wX4D-I

Shop  https //stza.co/+wX4D-35

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:RockHounds vs. Missions
END:VALARM
DTSTART:20180831T000000Z
DTEND:20180831T030000Z
UID:1MyHSaO7lrg_qq_cgy02tdcf@stanza.co
SUMMARY:RockHounds vs. Missions
DESCRIPTION:RockHounds vs. Missions\n\nFollow on MiLB First Pitch: https://stza.co/+wX4D-I\n\nShop: https://stza.co/+wX4D-35\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144543Z
LAST-MODIFIED:20180213T144543Z
TRANSP:OPAQUE
END:VEVENT
* RockHounds vs. Missions
<2018-08-31 Fri 19:00-22:00>
:PROPERTIES:
:ID:       2xWXvZEw1ojxmAfhu01nQgLf@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

RockHounds vs. Missions RockHounds vs. Missions

Follow on MiLB First Pitch  https //stza.co/+wX4F-B

Shop  https //stza.co/+wX4F-2Y

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:RockHounds vs. Missions
END:VALARM
DTSTART:20180901T000000Z
DTEND:20180901T030000Z
UID:2xWXvZEw1ojxmAfhu01nQgLf@stanza.co
SUMMARY:RockHounds vs. Missions
DESCRIPTION:RockHounds vs. Missions\n\nFollow on MiLB First Pitch: https://stza.co/+wX4F-B\n\nShop: https://stza.co/+wX4F-2Y\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144543Z
LAST-MODIFIED:20180213T144543Z
TRANSP:OPAQUE
END:VEVENT
* RockHounds vs. RoughRiders
<2018-09-01 Sat 19:00-22:00>
:PROPERTIES:
:ID:       yE9mqQPDIectub1yv-I107Sp@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

RockHounds vs. RoughRiders RockHounds vs. RoughRiders

Follow on MiLB First Pitch  https //stza.co/+wX4H-r

Shop  https //stza.co/+wX4H-f

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:RockHounds vs. RoughRiders
END:VALARM
DTSTART:20180902T000000Z
DTEND:20180902T030000Z
UID:yE9mqQPDIectub1yv-I107Sp@stanza.co
SUMMARY:RockHounds vs. RoughRiders
DESCRIPTION:RockHounds vs. RoughRiders\n\nFollow on MiLB First Pitch: https://stza.co/+wX4H-r\n\nShop: https://stza.co/+wX4H-f\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144543Z
LAST-MODIFIED:20180213T144543Z
TRANSP:OPAQUE
END:VEVENT
* RockHounds vs. RoughRiders
<2018-09-02 Sun 14:00-17:00>
:PROPERTIES:
:ID:       eV5_5LpWl4nNhXhvhYNRlDd9@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

RockHounds vs. RoughRiders RockHounds vs. RoughRiders

Follow on MiLB First Pitch  https //stza.co/+wX4J-3C

Shop  https //stza.co/+wX4J-34

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:RockHounds vs. RoughRiders
END:VALARM
DTSTART:20180902T190000Z
DTEND:20180902T220000Z
UID:eV5_5LpWl4nNhXhvhYNRlDd9@stanza.co
SUMMARY:RockHounds vs. RoughRiders
DESCRIPTION:RockHounds vs. RoughRiders\n\nFollow on MiLB First Pitch: https://stza.co/+wX4J-3C\n\nShop: https://stza.co/+wX4J-34\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144543Z
LAST-MODIFIED:20180213T144543Z
TRANSP:OPAQUE
END:VEVENT
* RockHounds vs. RoughRiders
<2018-09-03 Mon 14:00-17:00>
:PROPERTIES:
:ID:       iW25PmMTLJREracthnmsT9oN@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

RockHounds vs. RoughRiders RockHounds vs. RoughRiders

Follow on MiLB First Pitch  https //stza.co/+wX4N-1g

Shop  https //stza.co/+wX4N-2B

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:RockHounds vs. RoughRiders
END:VALARM
DTSTART:20180903T190000Z
DTEND:20180903T220000Z
UID:iW25PmMTLJREracthnmsT9oN@stanza.co
SUMMARY:RockHounds vs. RoughRiders
DESCRIPTION:RockHounds vs. RoughRiders\n\nFollow on MiLB First Pitch: https://stza.co/+wX4N-1g\n\nShop: https://stza.co/+wX4N-2B\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144543Z
LAST-MODIFIED:20180213T144543Z
TRANSP:OPAQUE
END:VEVENT
