#+TITLE:       Main Google calendar entries
#+AUTHOR:      Eric S Fraga
#+EMAIL:       e.fraga@ucl.ac.uk
#+DESCRIPTION: converted using the ical2org awk script
#+CATEGORY:    google
#+STARTUP:     hidestars
#+STARTUP:     overview

* COMMENT original iCal preamble

* Tourists @ Shorebirds
<2018-04-05 Thu 18:05-21:05>
:PROPERTIES:
:ID:       8eEbHJgEdy6jiuEGn0VwFSEM@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Tourists @ Shorebirds Tourists @ Shorebirds

Follow on MiLB First Pitch  https //stza.co/+wHLi-3X

Shop  https //stza.co/+wHLi-3Y

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Tourists @ Shorebirds
END:VALARM
DTSTART:20180405T230500Z
DTEND:20180406T020500Z
UID:8eEbHJgEdy6jiuEGn0VwFSEM@stanza.co
SUMMARY:Tourists @ Shorebirds
DESCRIPTION:Tourists @ Shorebirds\n\nFollow on MiLB First Pitch: https://stza.co/+wHLi-3X\n\nShop: https://stza.co/+wHLi-3Y\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144502Z
LAST-MODIFIED:20180213T144502Z
TRANSP:OPAQUE
END:VEVENT
* Tourists @ Shorebirds
<2018-04-06 Fri 18:05-21:05>
:PROPERTIES:
:ID:       4_mI9yJTSN62OjAw56wBckcp@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Tourists @ Shorebirds Tourists @ Shorebirds

Follow on MiLB First Pitch  https //stza.co/+wHFM-1Y

Shop  https //stza.co/+wHFM-3l

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Tourists @ Shorebirds
END:VALARM
DTSTART:20180406T230500Z
DTEND:20180407T020500Z
UID:4_mI9yJTSN62OjAw56wBckcp@stanza.co
SUMMARY:Tourists @ Shorebirds
DESCRIPTION:Tourists @ Shorebirds\n\nFollow on MiLB First Pitch: https://stza.co/+wHFM-1Y\n\nShop: https://stza.co/+wHFM-3l\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144502Z
LAST-MODIFIED:20180213T144502Z
TRANSP:OPAQUE
END:VEVENT
* Tourists @ Shorebirds
<2018-04-07 Sat 18:05-21:05>
:PROPERTIES:
:ID:       t_y1wQwfWMQG2_0m0RokgVtD@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Tourists @ Shorebirds Tourists @ Shorebirds

Follow on MiLB First Pitch  https //stza.co/+wHFN-I

Shop  https //stza.co/+wHFN-1$

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Tourists @ Shorebirds
END:VALARM
DTSTART:20180407T230500Z
DTEND:20180408T020500Z
UID:t_y1wQwfWMQG2_0m0RokgVtD@stanza.co
SUMMARY:Tourists @ Shorebirds
DESCRIPTION:Tourists @ Shorebirds\n\nFollow on MiLB First Pitch: https://stza.co/+wHFN-I\n\nShop: https://stza.co/+wHFN-1$\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144502Z
LAST-MODIFIED:20180213T144502Z
TRANSP:OPAQUE
END:VEVENT
* Tourists @ Shorebirds
<2018-04-08 Sun 13:05-16:05>
:PROPERTIES:
:ID:       Y_8pC-GE5VQFOzP2QNwiIVPc@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Tourists @ Shorebirds Tourists @ Shorebirds

Follow on MiLB First Pitch  https //stza.co/+wHFO-1T

Shop  https //stza.co/+wHFO-1c

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Tourists @ Shorebirds
END:VALARM
DTSTART:20180408T180500Z
DTEND:20180408T210500Z
UID:Y_8pC-GE5VQFOzP2QNwiIVPc@stanza.co
SUMMARY:Tourists @ Shorebirds
DESCRIPTION:Tourists @ Shorebirds\n\nFollow on MiLB First Pitch: https://stza.co/+wHFO-1T\n\nShop: https://stza.co/+wHFO-1c\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144502Z
LAST-MODIFIED:20180213T144502Z
TRANSP:OPAQUE
END:VEVENT
* Tourists @ Intimidators
<2018-04-09 Mon 17:35-20:35>
:PROPERTIES:
:ID:       Ggbmg8U_KM9TRvcn2kzII3sK@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Tourists @ Intimidators Tourists @ Intimidators

Follow on MiLB First Pitch  https //stza.co/+wIAb-1D

Shop  https //stza.co/+wIAb-2w

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Tourists @ Intimidators
END:VALARM
DTSTART:20180409T223500Z
DTEND:20180410T013500Z
UID:Ggbmg8U_KM9TRvcn2kzII3sK@stanza.co
SUMMARY:Tourists @ Intimidators
DESCRIPTION:Tourists @ Intimidators\n\nFollow on MiLB First Pitch: https://stza.co/+wIAb-1D\n\nShop: https://stza.co/+wIAb-2w\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144502Z
LAST-MODIFIED:20180213T144502Z
TRANSP:OPAQUE
END:VEVENT
* Tourists @ Intimidators
<2018-04-10 Tue 17:35-20:35>
:PROPERTIES:
:ID:       5pVBQ4VuH84aX-aju4YEeSUk@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Tourists @ Intimidators Tourists @ Intimidators

Follow on MiLB First Pitch  https //stza.co/+wIAc-2

Shop  https //stza.co/+wIAc-2B

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Tourists @ Intimidators
END:VALARM
DTSTART:20180410T223500Z
DTEND:20180411T013500Z
UID:5pVBQ4VuH84aX-aju4YEeSUk@stanza.co
SUMMARY:Tourists @ Intimidators
DESCRIPTION:Tourists @ Intimidators\n\nFollow on MiLB First Pitch: https://stza.co/+wIAc-2\n\nShop: https://stza.co/+wIAc-2B\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144502Z
LAST-MODIFIED:20180213T144502Z
TRANSP:OPAQUE
END:VEVENT
* Tourists @ Intimidators
<2018-04-11 Wed 09:05-12:05>
:PROPERTIES:
:ID:       ozDBkWzTXrjF2q_SRpqO5oCr@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Tourists @ Intimidators Tourists @ Intimidators

Follow on MiLB First Pitch  https //stza.co/+wIAd-x

Shop  https //stza.co/+wIAd-3d

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Tourists @ Intimidators
END:VALARM
DTSTART:20180411T140500Z
DTEND:20180411T170500Z
UID:ozDBkWzTXrjF2q_SRpqO5oCr@stanza.co
SUMMARY:Tourists @ Intimidators
DESCRIPTION:Tourists @ Intimidators\n\nFollow on MiLB First Pitch: https://stza.co/+wIAd-x\n\nShop: https://stza.co/+wIAd-3d\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144502Z
LAST-MODIFIED:20180213T144502Z
TRANSP:OPAQUE
END:VEVENT
* Tourists vs. Fireflies
<2018-04-12 Thu 18:05-21:05>
:PROPERTIES:
:ID:       dAKJFXVjH6Ll9dz-hgUpPWEO@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Tourists vs. Fireflies Tourists vs. Fireflies

Follow on MiLB First Pitch  https //stza.co/+vNsG-1T

Shop  https //stza.co/+vNsG-2o

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Tourists vs. Fireflies
END:VALARM
DTSTART:20180412T230500Z
DTEND:20180413T020500Z
UID:dAKJFXVjH6Ll9dz-hgUpPWEO@stanza.co
SUMMARY:Tourists vs. Fireflies
DESCRIPTION:Tourists vs. Fireflies\n\nFollow on MiLB First Pitch: https://stza.co/+vNsG-1T\n\nShop: https://stza.co/+vNsG-2o\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144502Z
LAST-MODIFIED:20180213T144502Z
TRANSP:OPAQUE
END:VEVENT
* Tourists vs. Fireflies
<2018-04-13 Fri 18:05-21:05>
:PROPERTIES:
:ID:       IRLelQqPlzxjPfydJaxkQXr_@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Tourists vs. Fireflies Tourists vs. Fireflies

Follow on MiLB First Pitch  https //stza.co/+vNsH-2P

Shop  https //stza.co/+vNsH-2$

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Tourists vs. Fireflies
END:VALARM
DTSTART:20180413T230500Z
DTEND:20180414T020500Z
UID:IRLelQqPlzxjPfydJaxkQXr_@stanza.co
SUMMARY:Tourists vs. Fireflies
DESCRIPTION:Tourists vs. Fireflies\n\nFollow on MiLB First Pitch: https://stza.co/+vNsH-2P\n\nShop: https://stza.co/+vNsH-2$\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144502Z
LAST-MODIFIED:20180213T144502Z
TRANSP:OPAQUE
END:VEVENT
* Tourists vs. Fireflies
<2018-04-14 Sat 17:05-20:05>
:PROPERTIES:
:ID:       33pesGFNaaSj-D7mDi-eqbLA@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Tourists vs. Fireflies Tourists vs. Fireflies

Follow on MiLB First Pitch  https //stza.co/+vNsK-3T

Shop  https //stza.co/+vNsK-18

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Tourists vs. Fireflies
END:VALARM
DTSTART:20180414T220500Z
DTEND:20180415T010500Z
UID:33pesGFNaaSj-D7mDi-eqbLA@stanza.co
SUMMARY:Tourists vs. Fireflies
DESCRIPTION:Tourists vs. Fireflies\n\nFollow on MiLB First Pitch: https://stza.co/+vNsK-3T\n\nShop: https://stza.co/+vNsK-18\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144502Z
LAST-MODIFIED:20180213T144502Z
TRANSP:OPAQUE
END:VEVENT
* Tourists vs. Fireflies
<2018-04-15 Sun 13:05-16:05>
:PROPERTIES:
:ID:       88ZvCFqKb4bs9mhc0SeHWJya@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Tourists vs. Fireflies Tourists vs. Fireflies

Follow on MiLB First Pitch  https //stza.co/+vNsM-F

Shop  https //stza.co/+vNsM-1q

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Tourists vs. Fireflies
END:VALARM
DTSTART:20180415T180500Z
DTEND:20180415T210500Z
UID:88ZvCFqKb4bs9mhc0SeHWJya@stanza.co
SUMMARY:Tourists vs. Fireflies
DESCRIPTION:Tourists vs. Fireflies\n\nFollow on MiLB First Pitch: https://stza.co/+vNsM-F\n\nShop: https://stza.co/+vNsM-1q\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144502Z
LAST-MODIFIED:20180213T144502Z
TRANSP:OPAQUE
END:VEVENT
* Tourists vs. Braves
<2018-04-16 Mon 18:05-21:05>
:PROPERTIES:
:ID:       2arqYtBX81yFn1IAiXsLIKcS@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Tourists vs. Braves Tourists vs. Braves

Follow on MiLB First Pitch  https //stza.co/+vNsN-6

Shop  https //stza.co/+vNsN-3E

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Tourists vs. Braves
END:VALARM
DTSTART:20180416T230500Z
DTEND:20180417T020500Z
UID:2arqYtBX81yFn1IAiXsLIKcS@stanza.co
SUMMARY:Tourists vs. Braves
DESCRIPTION:Tourists vs. Braves\n\nFollow on MiLB First Pitch: https://stza.co/+vNsN-6\n\nShop: https://stza.co/+vNsN-3E\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144502Z
LAST-MODIFIED:20180213T144502Z
TRANSP:OPAQUE
END:VEVENT
* Tourists vs. Braves
<2018-04-17 Tue 18:05-21:05>
:PROPERTIES:
:ID:       mmQqYLhoMCe-Qg2_qyBncvpc@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Tourists vs. Braves Tourists vs. Braves

Follow on MiLB First Pitch  https //stza.co/+vNsP-E

Shop  https //stza.co/+vNsP-C

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Tourists vs. Braves
END:VALARM
DTSTART:20180417T230500Z
DTEND:20180418T020500Z
UID:mmQqYLhoMCe-Qg2_qyBncvpc@stanza.co
SUMMARY:Tourists vs. Braves
DESCRIPTION:Tourists vs. Braves\n\nFollow on MiLB First Pitch: https://stza.co/+vNsP-E\n\nShop: https://stza.co/+vNsP-C\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144502Z
LAST-MODIFIED:20180213T144502Z
TRANSP:OPAQUE
END:VEVENT
* Tourists vs. Braves
<2018-04-18 Wed 18:05-21:05>
:PROPERTIES:
:ID:       qYjZMv2lP3OSnSCjkeQ7KYZX@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Tourists vs. Braves Tourists vs. Braves

Follow on MiLB First Pitch  https //stza.co/+vNsS-3w

Shop  https //stza.co/+vNsS-1t

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Tourists vs. Braves
END:VALARM
DTSTART:20180418T230500Z
DTEND:20180419T020500Z
UID:qYjZMv2lP3OSnSCjkeQ7KYZX@stanza.co
SUMMARY:Tourists vs. Braves
DESCRIPTION:Tourists vs. Braves\n\nFollow on MiLB First Pitch: https://stza.co/+vNsS-3w\n\nShop: https://stza.co/+vNsS-1t\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144502Z
LAST-MODIFIED:20180213T144502Z
TRANSP:OPAQUE
END:VEVENT
* Tourists @ Power
<2018-04-19 Thu 18:05-21:05>
:PROPERTIES:
:ID:       HoJJlBnRWUxtY49GMAY5bcpT@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Tourists @ Power Tourists @ Power

Follow on MiLB First Pitch  https //stza.co/+xJ3k-3m

Shop  https //stza.co/+xJ3k-2z

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Tourists @ Power
END:VALARM
DTSTART:20180419T230500Z
DTEND:20180420T020500Z
UID:HoJJlBnRWUxtY49GMAY5bcpT@stanza.co
SUMMARY:Tourists @ Power
DESCRIPTION:Tourists @ Power\n\nFollow on MiLB First Pitch: https://stza.co/+xJ3k-3m\n\nShop: https://stza.co/+xJ3k-2z\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144502Z
LAST-MODIFIED:20180213T144502Z
TRANSP:OPAQUE
END:VEVENT
* Tourists @ Power
<2018-04-20 Fri 18:05-21:05>
:PROPERTIES:
:ID:       _zLSK8fWmVb9tpQ6wWhe250p@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Tourists @ Power Tourists @ Power

Follow on MiLB First Pitch  https //stza.co/+xJ3l-p

Shop  https //stza.co/+xJ3l-q

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Tourists @ Power
END:VALARM
DTSTART:20180420T230500Z
DTEND:20180421T020500Z
UID:_zLSK8fWmVb9tpQ6wWhe250p@stanza.co
SUMMARY:Tourists @ Power
DESCRIPTION:Tourists @ Power\n\nFollow on MiLB First Pitch: https://stza.co/+xJ3l-p\n\nShop: https://stza.co/+xJ3l-q\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144502Z
LAST-MODIFIED:20180213T144502Z
TRANSP:OPAQUE
END:VEVENT
* Tourists @ Power
<2018-04-21 Sat 13:05-16:05>
:PROPERTIES:
:ID:       EIltUaF8kX2beltKhf1xYREy@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Tourists @ Power Tourists @ Power

Follow on MiLB First Pitch  https //stza.co/+xJ3m-2k

Shop  https //stza.co/+xJ3m-1s

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Tourists @ Power
END:VALARM
DTSTART:20180421T180500Z
DTEND:20180421T210500Z
UID:EIltUaF8kX2beltKhf1xYREy@stanza.co
SUMMARY:Tourists @ Power
DESCRIPTION:Tourists @ Power\n\nFollow on MiLB First Pitch: https://stza.co/+xJ3m-2k\n\nShop: https://stza.co/+xJ3m-1s\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144502Z
LAST-MODIFIED:20180213T144502Z
TRANSP:OPAQUE
END:VEVENT
* Tourists @ Power
<2018-04-22 Sun 13:05-16:05>
:PROPERTIES:
:ID:       -t6K-D_MROWMoPOkS2iMVVLB@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Tourists @ Power Tourists @ Power

Follow on MiLB First Pitch  https //stza.co/+xJ3n-1j

Shop  https //stza.co/+xJ3n-m

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Tourists @ Power
END:VALARM
DTSTART:20180422T180500Z
DTEND:20180422T210500Z
UID:-t6K-D_MROWMoPOkS2iMVVLB@stanza.co
SUMMARY:Tourists @ Power
DESCRIPTION:Tourists @ Power\n\nFollow on MiLB First Pitch: https://stza.co/+xJ3n-1j\n\nShop: https://stza.co/+xJ3n-m\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144502Z
LAST-MODIFIED:20180213T144502Z
TRANSP:OPAQUE
END:VEVENT
* Tourists vs. Legends
<2018-04-23 Mon 18:05-21:05>
:PROPERTIES:
:ID:       iHMIlzAIzj8vogrVnNbk33Ik@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Tourists vs. Legends Tourists vs. Legends

Follow on MiLB First Pitch  https //stza.co/+vNsU-3C

Shop  https //stza.co/+vNsU-12

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Tourists vs. Legends
END:VALARM
DTSTART:20180423T230500Z
DTEND:20180424T020500Z
UID:iHMIlzAIzj8vogrVnNbk33Ik@stanza.co
SUMMARY:Tourists vs. Legends
DESCRIPTION:Tourists vs. Legends\n\nFollow on MiLB First Pitch: https://stza.co/+vNsU-3C\n\nShop: https://stza.co/+vNsU-12\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144502Z
LAST-MODIFIED:20180213T144502Z
TRANSP:OPAQUE
END:VEVENT
* Tourists vs. Legends
<2018-04-24 Tue 18:05-21:05>
:PROPERTIES:
:ID:       -G2HX9s1JTJVpGbormuChfBd@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Tourists vs. Legends Tourists vs. Legends

Follow on MiLB First Pitch  https //stza.co/+vNsW-2o

Shop  https //stza.co/+vNsW-1f

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Tourists vs. Legends
END:VALARM
DTSTART:20180424T230500Z
DTEND:20180425T020500Z
UID:-G2HX9s1JTJVpGbormuChfBd@stanza.co
SUMMARY:Tourists vs. Legends
DESCRIPTION:Tourists vs. Legends\n\nFollow on MiLB First Pitch: https://stza.co/+vNsW-2o\n\nShop: https://stza.co/+vNsW-1f\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144502Z
LAST-MODIFIED:20180213T144502Z
TRANSP:OPAQUE
END:VEVENT
* Tourists vs. Legends
<2018-04-25 Wed 18:05-21:05>
:PROPERTIES:
:ID:       Sv6Wa-0lspI9yT14K6m6k12I@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Tourists vs. Legends Tourists vs. Legends

Follow on MiLB First Pitch  https //stza.co/+vNsY-2Y

Shop  https //stza.co/+vNsY-B

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Tourists vs. Legends
END:VALARM
DTSTART:20180425T230500Z
DTEND:20180426T020500Z
UID:Sv6Wa-0lspI9yT14K6m6k12I@stanza.co
SUMMARY:Tourists vs. Legends
DESCRIPTION:Tourists vs. Legends\n\nFollow on MiLB First Pitch: https://stza.co/+vNsY-2Y\n\nShop: https://stza.co/+vNsY-B\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144502Z
LAST-MODIFIED:20180213T144502Z
TRANSP:OPAQUE
END:VEVENT
* Tourists vs. Legends
<2018-04-26 Thu 18:05-21:05>
:PROPERTIES:
:ID:       QQ5DjF0PvMYgqdGZ4bqDTDN-@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Tourists vs. Legends Tourists vs. Legends

Follow on MiLB First Pitch  https //stza.co/+vNs_-3t

Shop  https //stza.co/+vNs_-3Y

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Tourists vs. Legends
END:VALARM
DTSTART:20180426T230500Z
DTEND:20180427T020500Z
UID:QQ5DjF0PvMYgqdGZ4bqDTDN-@stanza.co
SUMMARY:Tourists vs. Legends
DESCRIPTION:Tourists vs. Legends\n\nFollow on MiLB First Pitch: https://stza.co/+vNs_-3t\n\nShop: https://stza.co/+vNs_-3Y\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144502Z
LAST-MODIFIED:20180213T144502Z
TRANSP:OPAQUE
END:VEVENT
* Tourists vs. Grasshoppers
<2018-04-27 Fri 18:05-21:05>
:PROPERTIES:
:ID:       AX5velEQ0xl5REa1_1c7Q2rn@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Tourists vs. Grasshoppers Tourists vs. Grasshoppers

Follow on MiLB First Pitch  https //stza.co/+vNt0-1S

Shop  https //stza.co/+vNt0-z

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Tourists vs. Grasshoppers
END:VALARM
DTSTART:20180427T230500Z
DTEND:20180428T020500Z
UID:AX5velEQ0xl5REa1_1c7Q2rn@stanza.co
SUMMARY:Tourists vs. Grasshoppers
DESCRIPTION:Tourists vs. Grasshoppers\n\nFollow on MiLB First Pitch: https://stza.co/+vNt0-1S\n\nShop: https://stza.co/+vNt0-z\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144502Z
LAST-MODIFIED:20180213T144502Z
TRANSP:OPAQUE
END:VEVENT
* Tourists vs. Grasshoppers
<2018-04-28 Sat 17:05-20:05>
:PROPERTIES:
:ID:       pDMsIDf2FyjbzzF9Hm_MTgh0@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Tourists vs. Grasshoppers Tourists vs. Grasshoppers

Follow on MiLB First Pitch  https //stza.co/+vNt2-1q

Shop  https //stza.co/+vNt2-J

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Tourists vs. Grasshoppers
END:VALARM
DTSTART:20180428T220500Z
DTEND:20180429T010500Z
UID:pDMsIDf2FyjbzzF9Hm_MTgh0@stanza.co
SUMMARY:Tourists vs. Grasshoppers
DESCRIPTION:Tourists vs. Grasshoppers\n\nFollow on MiLB First Pitch: https://stza.co/+vNt2-1q\n\nShop: https://stza.co/+vNt2-J\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144502Z
LAST-MODIFIED:20180213T144502Z
TRANSP:OPAQUE
END:VEVENT
* Tourists vs. Grasshoppers
<2018-04-29 Sun 13:05-16:05>
:PROPERTIES:
:ID:       gSFX6kPgHHnqCJbVOrK_XoKv@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Tourists vs. Grasshoppers Tourists vs. Grasshoppers

Follow on MiLB First Pitch  https //stza.co/+vNt4-F

Shop  https //stza.co/+vNt4-1S

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Tourists vs. Grasshoppers
END:VALARM
DTSTART:20180429T180500Z
DTEND:20180429T210500Z
UID:gSFX6kPgHHnqCJbVOrK_XoKv@stanza.co
SUMMARY:Tourists vs. Grasshoppers
DESCRIPTION:Tourists vs. Grasshoppers\n\nFollow on MiLB First Pitch: https://stza.co/+vNt4-F\n\nShop: https://stza.co/+vNt4-1S\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144502Z
LAST-MODIFIED:20180213T144502Z
TRANSP:OPAQUE
END:VEVENT
* Tourists @ RiverDogs
<2018-05-01 Tue 18:05-21:05>
:PROPERTIES:
:ID:       Ss2iQHHvwgTqWq6X0hqO1i-P@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Tourists @ RiverDogs Tourists @ RiverDogs

Follow on MiLB First Pitch  https //stza.co/+vNuR-1L

Shop  https //stza.co/+vNuR-2i

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Tourists @ RiverDogs
END:VALARM
DTSTART:20180501T230500Z
DTEND:20180502T020500Z
UID:Ss2iQHHvwgTqWq6X0hqO1i-P@stanza.co
SUMMARY:Tourists @ RiverDogs
DESCRIPTION:Tourists @ RiverDogs\n\nFollow on MiLB First Pitch: https://stza.co/+vNuR-1L\n\nShop: https://stza.co/+vNuR-2i\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144502Z
LAST-MODIFIED:20180213T144502Z
TRANSP:OPAQUE
END:VEVENT
* Tourists @ RiverDogs
<2018-05-02 Wed 18:05-21:05>
:PROPERTIES:
:ID:       tMutoXFrFh96QsGU-8HqSr1B@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Tourists @ RiverDogs Tourists @ RiverDogs

Follow on MiLB First Pitch  https //stza.co/+vNuS-3r

Shop  https //stza.co/+vNuS-3K

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Tourists @ RiverDogs
END:VALARM
DTSTART:20180502T230500Z
DTEND:20180503T020500Z
UID:tMutoXFrFh96QsGU-8HqSr1B@stanza.co
SUMMARY:Tourists @ RiverDogs
DESCRIPTION:Tourists @ RiverDogs\n\nFollow on MiLB First Pitch: https://stza.co/+vNuS-3r\n\nShop: https://stza.co/+vNuS-3K\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144502Z
LAST-MODIFIED:20180213T144502Z
TRANSP:OPAQUE
END:VEVENT
* Tourists @ RiverDogs
<2018-05-03 Thu 18:05-21:05>
:PROPERTIES:
:ID:       tYANdDkjqUorYYgfOKHKYBRw@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Tourists @ RiverDogs Tourists @ RiverDogs

Follow on MiLB First Pitch  https //stza.co/+vNuT-36

Shop  https //stza.co/+vNuT-3T

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Tourists @ RiverDogs
END:VALARM
DTSTART:20180503T230500Z
DTEND:20180504T020500Z
UID:tYANdDkjqUorYYgfOKHKYBRw@stanza.co
SUMMARY:Tourists @ RiverDogs
DESCRIPTION:Tourists @ RiverDogs\n\nFollow on MiLB First Pitch: https://stza.co/+vNuT-36\n\nShop: https://stza.co/+vNuT-3T\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144502Z
LAST-MODIFIED:20180213T144502Z
TRANSP:OPAQUE
END:VEVENT
* Tourists @ Braves
<2018-05-04 Fri 18:00-21:00>
:PROPERTIES:
:ID:       HjOuz3kkEisxwHH_fgdcDGa6@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Tourists @ Braves Tourists @ Braves

Follow on MiLB First Pitch  https //stza.co/+vNvF-3a

Shop  https //stza.co/+vNvF-C

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Tourists @ Braves
END:VALARM
DTSTART:20180504T230000Z
DTEND:20180505T020000Z
UID:HjOuz3kkEisxwHH_fgdcDGa6@stanza.co
SUMMARY:Tourists @ Braves
DESCRIPTION:Tourists @ Braves\n\nFollow on MiLB First Pitch: https://stza.co/+vNvF-3a\n\nShop: https://stza.co/+vNvF-C\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144502Z
LAST-MODIFIED:20180213T144502Z
TRANSP:OPAQUE
END:VEVENT
* Tourists @ Braves
<2018-05-05 Sat 17:00-20:00>
:PROPERTIES:
:ID:       190wu9Hgf0Osxfj0C65Z0tMC@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Tourists @ Braves Tourists @ Braves

Follow on MiLB First Pitch  https //stza.co/+vNvG-3C

Shop  https //stza.co/+vNvG-1j

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Tourists @ Braves
END:VALARM
DTSTART:20180505T220000Z
DTEND:20180506T010000Z
UID:190wu9Hgf0Osxfj0C65Z0tMC@stanza.co
SUMMARY:Tourists @ Braves
DESCRIPTION:Tourists @ Braves\n\nFollow on MiLB First Pitch: https://stza.co/+vNvG-3C\n\nShop: https://stza.co/+vNvG-1j\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144502Z
LAST-MODIFIED:20180213T144502Z
TRANSP:OPAQUE
END:VEVENT
* Tourists @ Braves
<2018-05-06 Sun 13:00-16:00>
:PROPERTIES:
:ID:       gdp64ygtq-Hb1_t9BAQ7CQR9@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Tourists @ Braves Tourists @ Braves

Follow on MiLB First Pitch  https //stza.co/+vNvH-3Z

Shop  https //stza.co/+vNvH-2D

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Tourists @ Braves
END:VALARM
DTSTART:20180506T180000Z
DTEND:20180506T210000Z
UID:gdp64ygtq-Hb1_t9BAQ7CQR9@stanza.co
SUMMARY:Tourists @ Braves
DESCRIPTION:Tourists @ Braves\n\nFollow on MiLB First Pitch: https://stza.co/+vNvH-3Z\n\nShop: https://stza.co/+vNvH-2D\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144502Z
LAST-MODIFIED:20180213T144502Z
TRANSP:OPAQUE
END:VEVENT
* Tourists @ Braves
<2018-05-07 Mon 09:30-12:30>
:PROPERTIES:
:ID:       KCVXEfZ14-_-2HGaWF2qWU3c@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Tourists @ Braves Tourists @ Braves

Follow on MiLB First Pitch  https //stza.co/+vNvI-1K

Shop  https //stza.co/+vNvI-E

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Tourists @ Braves
END:VALARM
DTSTART:20180507T143000Z
DTEND:20180507T173000Z
UID:KCVXEfZ14-_-2HGaWF2qWU3c@stanza.co
SUMMARY:Tourists @ Braves
DESCRIPTION:Tourists @ Braves\n\nFollow on MiLB First Pitch: https://stza.co/+vNvI-1K\n\nShop: https://stza.co/+vNvI-E\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144502Z
LAST-MODIFIED:20180213T144502Z
TRANSP:OPAQUE
END:VEVENT
* Tourists vs. Grasshoppers
<2018-05-09 Wed 18:05-21:05>
:PROPERTIES:
:ID:       7BGH4KZBoQ_8NbL_B04gM2rz@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Tourists vs. Grasshoppers Tourists vs. Grasshoppers

Follow on MiLB First Pitch  https //stza.co/+vNt5-3T

Shop  https //stza.co/+vNt5-3b

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Tourists vs. Grasshoppers
END:VALARM
DTSTART:20180509T230500Z
DTEND:20180510T020500Z
UID:7BGH4KZBoQ_8NbL_B04gM2rz@stanza.co
SUMMARY:Tourists vs. Grasshoppers
DESCRIPTION:Tourists vs. Grasshoppers\n\nFollow on MiLB First Pitch: https://stza.co/+vNt5-3T\n\nShop: https://stza.co/+vNt5-3b\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144502Z
LAST-MODIFIED:20180213T144502Z
TRANSP:OPAQUE
END:VEVENT
* Tourists vs. Grasshoppers
<2018-05-10 Thu 18:05-21:05>
:PROPERTIES:
:ID:       xmaBkTNVM0yQB7A-FSFnqek_@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Tourists vs. Grasshoppers Tourists vs. Grasshoppers

Follow on MiLB First Pitch  https //stza.co/+vNt7-2W

Shop  https //stza.co/+vNt7-6

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Tourists vs. Grasshoppers
END:VALARM
DTSTART:20180510T230500Z
DTEND:20180511T020500Z
UID:xmaBkTNVM0yQB7A-FSFnqek_@stanza.co
SUMMARY:Tourists vs. Grasshoppers
DESCRIPTION:Tourists vs. Grasshoppers\n\nFollow on MiLB First Pitch: https://stza.co/+vNt7-2W\n\nShop: https://stza.co/+vNt7-6\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144502Z
LAST-MODIFIED:20180213T144502Z
TRANSP:OPAQUE
END:VEVENT
* Tourists vs. Grasshoppers
<2018-05-11 Fri 18:05-21:05>
:PROPERTIES:
:ID:       4XVuhw4VDqlPMBZx_VddIAtZ@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Tourists vs. Grasshoppers Tourists vs. Grasshoppers

Follow on MiLB First Pitch  https //stza.co/+vNt9-g

Shop  https //stza.co/+vNt9-3o

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Tourists vs. Grasshoppers
END:VALARM
DTSTART:20180511T230500Z
DTEND:20180512T020500Z
UID:4XVuhw4VDqlPMBZx_VddIAtZ@stanza.co
SUMMARY:Tourists vs. Grasshoppers
DESCRIPTION:Tourists vs. Grasshoppers\n\nFollow on MiLB First Pitch: https://stza.co/+vNt9-g\n\nShop: https://stza.co/+vNt9-3o\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144502Z
LAST-MODIFIED:20180213T144502Z
TRANSP:OPAQUE
END:VEVENT
* Tourists vs. Intimidators
<2018-05-12 Sat 17:05-20:05>
:PROPERTIES:
:ID:       ThXUHNKCZ2JWSn-rnhpSH1O8@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Tourists vs. Intimidators Tourists vs. Intimidators

Follow on MiLB First Pitch  https //stza.co/+vNtb-17

Shop  https //stza.co/+vNtb-$

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Tourists vs. Intimidators
END:VALARM
DTSTART:20180512T220500Z
DTEND:20180513T010500Z
UID:ThXUHNKCZ2JWSn-rnhpSH1O8@stanza.co
SUMMARY:Tourists vs. Intimidators
DESCRIPTION:Tourists vs. Intimidators\n\nFollow on MiLB First Pitch: https://stza.co/+vNtb-17\n\nShop: https://stza.co/+vNtb-$\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144502Z
LAST-MODIFIED:20180213T144502Z
TRANSP:OPAQUE
END:VEVENT
* Tourists vs. Intimidators
<2018-05-13 Sun 13:05-16:05>
:PROPERTIES:
:ID:       AN4DtMC-uvBrRX_YwiLmG0tI@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Tourists vs. Intimidators Tourists vs. Intimidators

Follow on MiLB First Pitch  https //stza.co/+vNte-30

Shop  https //stza.co/+vNte-1u

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Tourists vs. Intimidators
END:VALARM
DTSTART:20180513T180500Z
DTEND:20180513T210500Z
UID:AN4DtMC-uvBrRX_YwiLmG0tI@stanza.co
SUMMARY:Tourists vs. Intimidators
DESCRIPTION:Tourists vs. Intimidators\n\nFollow on MiLB First Pitch: https://stza.co/+vNte-30\n\nShop: https://stza.co/+vNte-1u\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144502Z
LAST-MODIFIED:20180213T144502Z
TRANSP:OPAQUE
END:VEVENT
* Tourists vs. Intimidators
<2018-05-14 Mon 18:05-21:05>
:PROPERTIES:
:ID:       WuAFhln987__EPW1aYHqPkGY@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Tourists vs. Intimidators Tourists vs. Intimidators

Follow on MiLB First Pitch  https //stza.co/+vNtf-25

Shop  https //stza.co/+vNtf-P

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Tourists vs. Intimidators
END:VALARM
DTSTART:20180514T230500Z
DTEND:20180515T020500Z
UID:WuAFhln987__EPW1aYHqPkGY@stanza.co
SUMMARY:Tourists vs. Intimidators
DESCRIPTION:Tourists vs. Intimidators\n\nFollow on MiLB First Pitch: https://stza.co/+vNtf-25\n\nShop: https://stza.co/+vNtf-P\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144502Z
LAST-MODIFIED:20180213T144502Z
TRANSP:OPAQUE
END:VEVENT
* Tourists vs. Intimidators
<2018-05-15 Tue 09:35-12:35>
:PROPERTIES:
:ID:       N9g4CPNiBpDpjs9XMo3FXBU8@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Tourists vs. Intimidators Tourists vs. Intimidators

Follow on MiLB First Pitch  https //stza.co/+vNth-1p

Shop  https //stza.co/+vNth-1T

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Tourists vs. Intimidators
END:VALARM
DTSTART:20180515T143500Z
DTEND:20180515T173500Z
UID:N9g4CPNiBpDpjs9XMo3FXBU8@stanza.co
SUMMARY:Tourists vs. Intimidators
DESCRIPTION:Tourists vs. Intimidators\n\nFollow on MiLB First Pitch: https://stza.co/+vNth-1p\n\nShop: https://stza.co/+vNth-1T\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144502Z
LAST-MODIFIED:20180213T144502Z
TRANSP:OPAQUE
END:VEVENT
* Tourists @ Braves
<2018-05-17 Thu 18:00-21:00>
:PROPERTIES:
:ID:       H_9kBvBkQGjVQS1Zd3zIMzTq@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Tourists @ Braves Tourists @ Braves

Follow on MiLB First Pitch  https //stza.co/+vNvJ-2D

Shop  https //stza.co/+vNvJ-1b

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Tourists @ Braves
END:VALARM
DTSTART:20180517T230000Z
DTEND:20180518T020000Z
UID:H_9kBvBkQGjVQS1Zd3zIMzTq@stanza.co
SUMMARY:Tourists @ Braves
DESCRIPTION:Tourists @ Braves\n\nFollow on MiLB First Pitch: https://stza.co/+vNvJ-2D\n\nShop: https://stza.co/+vNvJ-1b\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144502Z
LAST-MODIFIED:20180213T144502Z
TRANSP:OPAQUE
END:VEVENT
* Tourists @ Braves
<2018-05-18 Fri 18:00-21:00>
:PROPERTIES:
:ID:       NF_TxAParuLx5C2fYVKPyq_e@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Tourists @ Braves Tourists @ Braves

Follow on MiLB First Pitch  https //stza.co/+vNvK-2J

Shop  https //stza.co/+vNvK-7

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Tourists @ Braves
END:VALARM
DTSTART:20180518T230000Z
DTEND:20180519T020000Z
UID:NF_TxAParuLx5C2fYVKPyq_e@stanza.co
SUMMARY:Tourists @ Braves
DESCRIPTION:Tourists @ Braves\n\nFollow on MiLB First Pitch: https://stza.co/+vNvK-2J\n\nShop: https://stza.co/+vNvK-7\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144502Z
LAST-MODIFIED:20180213T144502Z
TRANSP:OPAQUE
END:VEVENT
* Tourists @ Braves
<2018-05-19 Sat 17:00-20:00>
:PROPERTIES:
:ID:       jnRbDkgcX1vE8ZnOGWdzie_r@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Tourists @ Braves Tourists @ Braves

Follow on MiLB First Pitch  https //stza.co/+vNvL-3D

Shop  https //stza.co/+vNvL-26

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Tourists @ Braves
END:VALARM
DTSTART:20180519T220000Z
DTEND:20180520T010000Z
UID:jnRbDkgcX1vE8ZnOGWdzie_r@stanza.co
SUMMARY:Tourists @ Braves
DESCRIPTION:Tourists @ Braves\n\nFollow on MiLB First Pitch: https://stza.co/+vNvL-3D\n\nShop: https://stza.co/+vNvL-26\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144502Z
LAST-MODIFIED:20180213T144502Z
TRANSP:OPAQUE
END:VEVENT
* Tourists @ Braves
<2018-05-20 Sun 13:00-16:00>
:PROPERTIES:
:ID:       eaVG_yTR9X3F1xUVZHnLp9bZ@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Tourists @ Braves Tourists @ Braves

Follow on MiLB First Pitch  https //stza.co/+vNvM-1u

Shop  https //stza.co/+vNvM-22

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Tourists @ Braves
END:VALARM
DTSTART:20180520T180000Z
DTEND:20180520T210000Z
UID:eaVG_yTR9X3F1xUVZHnLp9bZ@stanza.co
SUMMARY:Tourists @ Braves
DESCRIPTION:Tourists @ Braves\n\nFollow on MiLB First Pitch: https://stza.co/+vNvM-1u\n\nShop: https://stza.co/+vNvM-22\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144502Z
LAST-MODIFIED:20180213T144502Z
TRANSP:OPAQUE
END:VEVENT
* Tourists vs. Drive
<2018-05-21 Mon 18:05-21:05>
:PROPERTIES:
:ID:       je2lZxArOWg48hQUKlZQN_f8@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Tourists vs. Drive Tourists vs. Drive

Follow on MiLB First Pitch  https //stza.co/+vNtk-r

Shop  https //stza.co/+vNtk-33

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Tourists vs. Drive
END:VALARM
DTSTART:20180521T230500Z
DTEND:20180522T020500Z
UID:je2lZxArOWg48hQUKlZQN_f8@stanza.co
SUMMARY:Tourists vs. Drive
DESCRIPTION:Tourists vs. Drive\n\nFollow on MiLB First Pitch: https://stza.co/+vNtk-r\n\nShop: https://stza.co/+vNtk-33\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144502Z
LAST-MODIFIED:20180213T144502Z
TRANSP:OPAQUE
END:VEVENT
* Tourists vs. Drive
<2018-05-22 Tue 18:05-21:05>
:PROPERTIES:
:ID:       qyyIwlL9BjaonQ-UEEpkDDIe@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Tourists vs. Drive Tourists vs. Drive

Follow on MiLB First Pitch  https //stza.co/+vNtm-2E

Shop  https //stza.co/+vNtm-3p

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Tourists vs. Drive
END:VALARM
DTSTART:20180522T230500Z
DTEND:20180523T020500Z
UID:qyyIwlL9BjaonQ-UEEpkDDIe@stanza.co
SUMMARY:Tourists vs. Drive
DESCRIPTION:Tourists vs. Drive\n\nFollow on MiLB First Pitch: https://stza.co/+vNtm-2E\n\nShop: https://stza.co/+vNtm-3p\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144502Z
LAST-MODIFIED:20180213T144502Z
TRANSP:OPAQUE
END:VEVENT
* Tourists vs. Drive
<2018-05-23 Wed 09:35-12:35>
:PROPERTIES:
:ID:       kqvLmxKtgO0d_zoR025c92zP@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Tourists vs. Drive Tourists vs. Drive

Follow on MiLB First Pitch  https //stza.co/+vNtn-3T

Shop  https //stza.co/+vNtn-3Z

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Tourists vs. Drive
END:VALARM
DTSTART:20180523T143500Z
DTEND:20180523T173500Z
UID:kqvLmxKtgO0d_zoR025c92zP@stanza.co
SUMMARY:Tourists vs. Drive
DESCRIPTION:Tourists vs. Drive\n\nFollow on MiLB First Pitch: https://stza.co/+vNtn-3T\n\nShop: https://stza.co/+vNtn-3Z\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144502Z
LAST-MODIFIED:20180213T144502Z
TRANSP:OPAQUE
END:VEVENT
* Tourists vs. Drive
<2018-05-24 Thu 18:05-21:05>
:PROPERTIES:
:ID:       0-MMC-AUMEczqlova0Lu2Gdw@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Tourists vs. Drive Tourists vs. Drive

Follow on MiLB First Pitch  https //stza.co/+vNtp-3r

Shop  https //stza.co/+vNtp-

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Tourists vs. Drive
END:VALARM
DTSTART:20180524T230500Z
DTEND:20180525T020500Z
UID:0-MMC-AUMEczqlova0Lu2Gdw@stanza.co
SUMMARY:Tourists vs. Drive
DESCRIPTION:Tourists vs. Drive\n\nFollow on MiLB First Pitch: https://stza.co/+vNtp-3r\n\nShop: https://stza.co/+vNtp-\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144502Z
LAST-MODIFIED:20180213T144502Z
TRANSP:OPAQUE
END:VEVENT
* Tourists vs. Legends
<2018-05-25 Fri 18:05-21:05>
:PROPERTIES:
:ID:       TEyY8bYoQEJCgToSZXPce8Sp@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Tourists vs. Legends Tourists vs. Legends

Follow on MiLB First Pitch  https //stza.co/+vNtr-1i

Shop  https //stza.co/+vNtr-1E

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Tourists vs. Legends
END:VALARM
DTSTART:20180525T230500Z
DTEND:20180526T020500Z
UID:TEyY8bYoQEJCgToSZXPce8Sp@stanza.co
SUMMARY:Tourists vs. Legends
DESCRIPTION:Tourists vs. Legends\n\nFollow on MiLB First Pitch: https://stza.co/+vNtr-1i\n\nShop: https://stza.co/+vNtr-1E\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144502Z
LAST-MODIFIED:20180213T144502Z
TRANSP:OPAQUE
END:VEVENT
* Tourists vs. Legends
<2018-05-26 Sat 17:05-20:05>
:PROPERTIES:
:ID:       c3x8EC3jbMfd54LMoHAtj0ND@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Tourists vs. Legends Tourists vs. Legends

Follow on MiLB First Pitch  https //stza.co/+vNtu-35

Shop  https //stza.co/+vNtu-1$

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Tourists vs. Legends
END:VALARM
DTSTART:20180526T220500Z
DTEND:20180527T010500Z
UID:c3x8EC3jbMfd54LMoHAtj0ND@stanza.co
SUMMARY:Tourists vs. Legends
DESCRIPTION:Tourists vs. Legends\n\nFollow on MiLB First Pitch: https://stza.co/+vNtu-35\n\nShop: https://stza.co/+vNtu-1$\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144502Z
LAST-MODIFIED:20180213T144502Z
TRANSP:OPAQUE
END:VEVENT
* Tourists vs. Legends
<2018-05-27 Sun 18:05-21:05>
:PROPERTIES:
:ID:       UdlCK11wXht5RHpROE-PIqX7@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Tourists vs. Legends Tourists vs. Legends

Follow on MiLB First Pitch  https //stza.co/+vNtv-3k

Shop  https //stza.co/+vNtv-2f

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Tourists vs. Legends
END:VALARM
DTSTART:20180527T230500Z
DTEND:20180528T020500Z
UID:UdlCK11wXht5RHpROE-PIqX7@stanza.co
SUMMARY:Tourists vs. Legends
DESCRIPTION:Tourists vs. Legends\n\nFollow on MiLB First Pitch: https://stza.co/+vNtv-3k\n\nShop: https://stza.co/+vNtv-2f\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144502Z
LAST-MODIFIED:20180213T144502Z
TRANSP:OPAQUE
END:VEVENT
* Tourists vs. Legends
<2018-05-28 Mon 12:05-15:05>
:PROPERTIES:
:ID:       rEyk9LFNEP3m1ro_q4KPGZmC@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Tourists vs. Legends Tourists vs. Legends

Follow on MiLB First Pitch  https //stza.co/+vNtx-3T

Shop  https //stza.co/+vNtx-1d

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Tourists vs. Legends
END:VALARM
DTSTART:20180528T170500Z
DTEND:20180528T200500Z
UID:rEyk9LFNEP3m1ro_q4KPGZmC@stanza.co
SUMMARY:Tourists vs. Legends
DESCRIPTION:Tourists vs. Legends\n\nFollow on MiLB First Pitch: https://stza.co/+vNtx-3T\n\nShop: https://stza.co/+vNtx-1d\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144502Z
LAST-MODIFIED:20180213T144502Z
TRANSP:OPAQUE
END:VEVENT
* Tourists @ Braves
<2018-05-29 Tue 18:00-21:00>
:PROPERTIES:
:ID:       hapUDDCdF72gSSLuFRNYEOlq@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Tourists @ Braves Tourists @ Braves

Follow on MiLB First Pitch  https //stza.co/+vNvN-2T

Shop  https //stza.co/+vNvN-2g

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Tourists @ Braves
END:VALARM
DTSTART:20180529T230000Z
DTEND:20180530T020000Z
UID:hapUDDCdF72gSSLuFRNYEOlq@stanza.co
SUMMARY:Tourists @ Braves
DESCRIPTION:Tourists @ Braves\n\nFollow on MiLB First Pitch: https://stza.co/+vNvN-2T\n\nShop: https://stza.co/+vNvN-2g\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144502Z
LAST-MODIFIED:20180213T144502Z
TRANSP:OPAQUE
END:VEVENT
* Tourists @ Braves
<2018-05-30 Wed 12:00-15:00>
:PROPERTIES:
:ID:       lnefdrp6B3JnlheJSYWf0dE-@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Tourists @ Braves Tourists @ Braves

Follow on MiLB First Pitch  https //stza.co/+vNvO-2C

Shop  https //stza.co/+vNvO-22

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Tourists @ Braves
END:VALARM
DTSTART:20180530T170000Z
DTEND:20180530T200000Z
UID:lnefdrp6B3JnlheJSYWf0dE-@stanza.co
SUMMARY:Tourists @ Braves
DESCRIPTION:Tourists @ Braves\n\nFollow on MiLB First Pitch: https://stza.co/+vNvO-2C\n\nShop: https://stza.co/+vNvO-22\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144502Z
LAST-MODIFIED:20180213T144502Z
TRANSP:OPAQUE
END:VEVENT
* Tourists @ Braves
<2018-05-31 Thu 18:00-21:00>
:PROPERTIES:
:ID:       8EYw-MiwY4QGqsbGYZ-DXREz@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Tourists @ Braves Tourists @ Braves

Follow on MiLB First Pitch  https //stza.co/+vNvP-1A

Shop  https //stza.co/+vNvP-2d

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Tourists @ Braves
END:VALARM
DTSTART:20180531T230000Z
DTEND:20180601T020000Z
UID:8EYw-MiwY4QGqsbGYZ-DXREz@stanza.co
SUMMARY:Tourists @ Braves
DESCRIPTION:Tourists @ Braves\n\nFollow on MiLB First Pitch: https://stza.co/+vNvP-1A\n\nShop: https://stza.co/+vNvP-2d\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144502Z
LAST-MODIFIED:20180213T144502Z
TRANSP:OPAQUE
END:VEVENT
* Tourists @ Drive
<2018-06-01 Fri 18:05-21:05>
:PROPERTIES:
:ID:       EZCjzfZlyhkHyYKGWizb-et8@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Tourists @ Drive Tourists @ Drive

Follow on MiLB First Pitch  https //stza.co/+xEZd-28

Shop  https //stza.co/+xEZd-29

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Tourists @ Drive
END:VALARM
DTSTART:20180601T230500Z
DTEND:20180602T020500Z
UID:EZCjzfZlyhkHyYKGWizb-et8@stanza.co
SUMMARY:Tourists @ Drive
DESCRIPTION:Tourists @ Drive\n\nFollow on MiLB First Pitch: https://stza.co/+xEZd-28\n\nShop: https://stza.co/+xEZd-29\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144502Z
LAST-MODIFIED:20180213T144502Z
TRANSP:OPAQUE
END:VEVENT
* Tourists @ Drive
<2018-06-02 Sat 18:05-21:05>
:PROPERTIES:
:ID:       CN2pqRxE5DHoR9prEHLzfsWz@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Tourists @ Drive Tourists @ Drive

Follow on MiLB First Pitch  https //stza.co/+xEZe-2z

Shop  https //stza.co/+xEZe-6

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Tourists @ Drive
END:VALARM
DTSTART:20180602T230500Z
DTEND:20180603T020500Z
UID:CN2pqRxE5DHoR9prEHLzfsWz@stanza.co
SUMMARY:Tourists @ Drive
DESCRIPTION:Tourists @ Drive\n\nFollow on MiLB First Pitch: https://stza.co/+xEZe-2z\n\nShop: https://stza.co/+xEZe-6\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144502Z
LAST-MODIFIED:20180213T144502Z
TRANSP:OPAQUE
END:VEVENT
* Tourists @ Drive
<2018-06-03 Sun 15:05-18:05>
:PROPERTIES:
:ID:       GUbiuhxRHucrUuKhLLfIqNHb@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Tourists @ Drive Tourists @ Drive

Follow on MiLB First Pitch  https //stza.co/+xEZf-g

Shop  https //stza.co/+xEZf-3A

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Tourists @ Drive
END:VALARM
DTSTART:20180603T200500Z
DTEND:20180603T230500Z
UID:GUbiuhxRHucrUuKhLLfIqNHb@stanza.co
SUMMARY:Tourists @ Drive
DESCRIPTION:Tourists @ Drive\n\nFollow on MiLB First Pitch: https://stza.co/+xEZf-g\n\nShop: https://stza.co/+xEZf-3A\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144502Z
LAST-MODIFIED:20180213T144502Z
TRANSP:OPAQUE
END:VEVENT
* Tourists vs. Braves
<2018-06-05 Tue 18:05-21:05>
:PROPERTIES:
:ID:       eLoy-xRvIttn957FQCXWtfxf@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Tourists vs. Braves Tourists vs. Braves

Follow on MiLB First Pitch  https //stza.co/+vNtz-3m

Shop  https //stza.co/+vNtz-3H

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Tourists vs. Braves
END:VALARM
DTSTART:20180605T230500Z
DTEND:20180606T020500Z
UID:eLoy-xRvIttn957FQCXWtfxf@stanza.co
SUMMARY:Tourists vs. Braves
DESCRIPTION:Tourists vs. Braves\n\nFollow on MiLB First Pitch: https://stza.co/+vNtz-3m\n\nShop: https://stza.co/+vNtz-3H\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144502Z
LAST-MODIFIED:20180213T144502Z
TRANSP:OPAQUE
END:VEVENT
* Tourists vs. Braves
<2018-06-06 Wed 18:05-21:05>
:PROPERTIES:
:ID:       gRfEko7WJjVbluY0OU0uCXke@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Tourists vs. Braves Tourists vs. Braves

Follow on MiLB First Pitch  https //stza.co/+vNtB-X

Shop  https //stza.co/+vNtB-3q

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Tourists vs. Braves
END:VALARM
DTSTART:20180606T230500Z
DTEND:20180607T020500Z
UID:gRfEko7WJjVbluY0OU0uCXke@stanza.co
SUMMARY:Tourists vs. Braves
DESCRIPTION:Tourists vs. Braves\n\nFollow on MiLB First Pitch: https://stza.co/+vNtB-X\n\nShop: https://stza.co/+vNtB-3q\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144502Z
LAST-MODIFIED:20180213T144502Z
TRANSP:OPAQUE
END:VEVENT
* Tourists vs. Braves
<2018-06-07 Thu 18:05-21:05>
:PROPERTIES:
:ID:       WUbel_cLHQXvQr_oar4F1XT3@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Tourists vs. Braves Tourists vs. Braves

Follow on MiLB First Pitch  https //stza.co/+vNtE-3Y

Shop  https //stza.co/+vNtE-1M

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Tourists vs. Braves
END:VALARM
DTSTART:20180607T230500Z
DTEND:20180608T020500Z
UID:WUbel_cLHQXvQr_oar4F1XT3@stanza.co
SUMMARY:Tourists vs. Braves
DESCRIPTION:Tourists vs. Braves\n\nFollow on MiLB First Pitch: https://stza.co/+vNtE-3Y\n\nShop: https://stza.co/+vNtE-1M\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144502Z
LAST-MODIFIED:20180213T144502Z
TRANSP:OPAQUE
END:VEVENT
* Tourists vs. Legends
<2018-06-08 Fri 18:05-21:05>
:PROPERTIES:
:ID:       22IZerP1BQBw1bNDR6cdEtfO@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Tourists vs. Legends Tourists vs. Legends

Follow on MiLB First Pitch  https //stza.co/+vNtG-2L

Shop  https //stza.co/+vNtG-2F

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Tourists vs. Legends
END:VALARM
DTSTART:20180608T230500Z
DTEND:20180609T020500Z
UID:22IZerP1BQBw1bNDR6cdEtfO@stanza.co
SUMMARY:Tourists vs. Legends
DESCRIPTION:Tourists vs. Legends\n\nFollow on MiLB First Pitch: https://stza.co/+vNtG-2L\n\nShop: https://stza.co/+vNtG-2F\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144502Z
LAST-MODIFIED:20180213T144502Z
TRANSP:OPAQUE
END:VEVENT
* Tourists vs. Legends
<2018-06-09 Sat 17:05-20:05>
:PROPERTIES:
:ID:       07mc5yK8nI6X-cbbM4IfKJzs@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Tourists vs. Legends Tourists vs. Legends

Follow on MiLB First Pitch  https //stza.co/+vNtH-3I

Shop  https //stza.co/+vNtH-3D

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Tourists vs. Legends
END:VALARM
DTSTART:20180609T220500Z
DTEND:20180610T010500Z
UID:07mc5yK8nI6X-cbbM4IfKJzs@stanza.co
SUMMARY:Tourists vs. Legends
DESCRIPTION:Tourists vs. Legends\n\nFollow on MiLB First Pitch: https://stza.co/+vNtH-3I\n\nShop: https://stza.co/+vNtH-3D\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144502Z
LAST-MODIFIED:20180213T144502Z
TRANSP:OPAQUE
END:VEVENT
* Tourists vs. Legends
<2018-06-10 Sun 13:05-16:05>
:PROPERTIES:
:ID:       ozZJYBqjlW6zF2tf3aTTgP9g@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Tourists vs. Legends Tourists vs. Legends

Follow on MiLB First Pitch  https //stza.co/+vNtK-1v

Shop  https //stza.co/+vNtK-2w

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Tourists vs. Legends
END:VALARM
DTSTART:20180610T180500Z
DTEND:20180610T210500Z
UID:ozZJYBqjlW6zF2tf3aTTgP9g@stanza.co
SUMMARY:Tourists vs. Legends
DESCRIPTION:Tourists vs. Legends\n\nFollow on MiLB First Pitch: https://stza.co/+vNtK-1v\n\nShop: https://stza.co/+vNtK-2w\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144502Z
LAST-MODIFIED:20180213T144502Z
TRANSP:OPAQUE
END:VEVENT
* Tourists @ RiverDogs
<2018-06-11 Mon 18:05-21:05>
:PROPERTIES:
:ID:       5HoJCSHXJFTffPF-vsLiRVjH@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Tourists @ RiverDogs Tourists @ RiverDogs

Follow on MiLB First Pitch  https //stza.co/+vNuU-2M

Shop  https //stza.co/+vNuU-22

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Tourists @ RiverDogs
END:VALARM
DTSTART:20180611T230500Z
DTEND:20180612T020500Z
UID:5HoJCSHXJFTffPF-vsLiRVjH@stanza.co
SUMMARY:Tourists @ RiverDogs
DESCRIPTION:Tourists @ RiverDogs\n\nFollow on MiLB First Pitch: https://stza.co/+vNuU-2M\n\nShop: https://stza.co/+vNuU-22\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144502Z
LAST-MODIFIED:20180213T144502Z
TRANSP:OPAQUE
END:VEVENT
* Tourists @ RiverDogs
<2018-06-12 Tue 18:05-21:05>
:PROPERTIES:
:ID:       xrKdP86EYXNedKSFX1IldSng@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Tourists @ RiverDogs Tourists @ RiverDogs

Follow on MiLB First Pitch  https //stza.co/+vNuV-3p

Shop  https //stza.co/+vNuV-15

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Tourists @ RiverDogs
END:VALARM
DTSTART:20180612T230500Z
DTEND:20180613T020500Z
UID:xrKdP86EYXNedKSFX1IldSng@stanza.co
SUMMARY:Tourists @ RiverDogs
DESCRIPTION:Tourists @ RiverDogs\n\nFollow on MiLB First Pitch: https://stza.co/+vNuV-3p\n\nShop: https://stza.co/+vNuV-15\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144502Z
LAST-MODIFIED:20180213T144502Z
TRANSP:OPAQUE
END:VEVENT
* Tourists @ RiverDogs
<2018-06-13 Wed 18:05-21:05>
:PROPERTIES:
:ID:       tEd_Bp_IcTJQ9T9BOmP8pIqw@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Tourists @ RiverDogs Tourists @ RiverDogs

Follow on MiLB First Pitch  https //stza.co/+vNuW-33

Shop  https //stza.co/+vNuW-1v

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Tourists @ RiverDogs
END:VALARM
DTSTART:20180613T230500Z
DTEND:20180614T020500Z
UID:tEd_Bp_IcTJQ9T9BOmP8pIqw@stanza.co
SUMMARY:Tourists @ RiverDogs
DESCRIPTION:Tourists @ RiverDogs\n\nFollow on MiLB First Pitch: https://stza.co/+vNuW-33\n\nShop: https://stza.co/+vNuW-1v\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144502Z
LAST-MODIFIED:20180213T144502Z
TRANSP:OPAQUE
END:VEVENT
* Tourists @ RiverDogs
<2018-06-14 Thu 18:05-21:05>
:PROPERTIES:
:ID:       9CNFwgtHbI7LIs1S_Le0So6d@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Tourists @ RiverDogs Tourists @ RiverDogs

Follow on MiLB First Pitch  https //stza.co/+vNuX-2

Shop  https //stza.co/+vNuX-u

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Tourists @ RiverDogs
END:VALARM
DTSTART:20180614T230500Z
DTEND:20180615T020500Z
UID:9CNFwgtHbI7LIs1S_Le0So6d@stanza.co
SUMMARY:Tourists @ RiverDogs
DESCRIPTION:Tourists @ RiverDogs\n\nFollow on MiLB First Pitch: https://stza.co/+vNuX-2\n\nShop: https://stza.co/+vNuX-u\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144502Z
LAST-MODIFIED:20180213T144502Z
TRANSP:OPAQUE
END:VEVENT
* Tourists vs. GreenJackets
<2018-06-15 Fri 18:05-21:05>
:PROPERTIES:
:ID:       VnKyF8vLNxqn0mMtlpW5i3Nr@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Tourists vs. GreenJackets Tourists vs. GreenJackets

Follow on MiLB First Pitch  https //stza.co/+vNtL-1T

Shop  https //stza.co/+vNtL-3o

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Tourists vs. GreenJackets
END:VALARM
DTSTART:20180615T230500Z
DTEND:20180616T020500Z
UID:VnKyF8vLNxqn0mMtlpW5i3Nr@stanza.co
SUMMARY:Tourists vs. GreenJackets
DESCRIPTION:Tourists vs. GreenJackets\n\nFollow on MiLB First Pitch: https://stza.co/+vNtL-1T\n\nShop: https://stza.co/+vNtL-3o\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144502Z
LAST-MODIFIED:20180213T144502Z
TRANSP:OPAQUE
END:VEVENT
* Tourists vs. GreenJackets
<2018-06-16 Sat 17:05-20:05>
:PROPERTIES:
:ID:       c_HiE10iIQWsErn3yOBwARdl@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Tourists vs. GreenJackets Tourists vs. GreenJackets

Follow on MiLB First Pitch  https //stza.co/+vNtO-1q

Shop  https //stza.co/+vNtO-2n

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Tourists vs. GreenJackets
END:VALARM
DTSTART:20180616T220500Z
DTEND:20180617T010500Z
UID:c_HiE10iIQWsErn3yOBwARdl@stanza.co
SUMMARY:Tourists vs. GreenJackets
DESCRIPTION:Tourists vs. GreenJackets\n\nFollow on MiLB First Pitch: https://stza.co/+vNtO-1q\n\nShop: https://stza.co/+vNtO-2n\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144502Z
LAST-MODIFIED:20180213T144502Z
TRANSP:OPAQUE
END:VEVENT
* Tourists vs. GreenJackets
<2018-06-17 Sun 13:05-16:05>
:PROPERTIES:
:ID:       Gb9J1XJtSpb7m8fhqvlnGA4z@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Tourists vs. GreenJackets Tourists vs. GreenJackets

Follow on MiLB First Pitch  https //stza.co/+vNtP-3T

Shop  https //stza.co/+vNtP-1C

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Tourists vs. GreenJackets
END:VALARM
DTSTART:20180617T180500Z
DTEND:20180617T210500Z
UID:Gb9J1XJtSpb7m8fhqvlnGA4z@stanza.co
SUMMARY:Tourists vs. GreenJackets
DESCRIPTION:Tourists vs. GreenJackets\n\nFollow on MiLB First Pitch: https://stza.co/+vNtP-3T\n\nShop: https://stza.co/+vNtP-1C\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144502Z
LAST-MODIFIED:20180213T144502Z
TRANSP:OPAQUE
END:VEVENT
* Tourists @ Drive
<2018-06-21 Thu 18:05-21:05>
:PROPERTIES:
:ID:       vGYYLVjAH7Xo1ktBMfM94YMb@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Tourists @ Drive Tourists @ Drive

Follow on MiLB First Pitch  https //stza.co/+xEZg-12

Shop  https //stza.co/+xEZg-t

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Tourists @ Drive
END:VALARM
DTSTART:20180621T230500Z
DTEND:20180622T020500Z
UID:vGYYLVjAH7Xo1ktBMfM94YMb@stanza.co
SUMMARY:Tourists @ Drive
DESCRIPTION:Tourists @ Drive\n\nFollow on MiLB First Pitch: https://stza.co/+xEZg-12\n\nShop: https://stza.co/+xEZg-t\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144502Z
LAST-MODIFIED:20180213T144502Z
TRANSP:OPAQUE
END:VEVENT
* Tourists @ Drive
<2018-06-22 Fri 18:05-21:05>
:PROPERTIES:
:ID:       as4PxQYKLr7FJIPj89OgbZAC@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Tourists @ Drive Tourists @ Drive

Follow on MiLB First Pitch  https //stza.co/+xEZh-2R

Shop  https //stza.co/+xEZh-2_

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Tourists @ Drive
END:VALARM
DTSTART:20180622T230500Z
DTEND:20180623T020500Z
UID:as4PxQYKLr7FJIPj89OgbZAC@stanza.co
SUMMARY:Tourists @ Drive
DESCRIPTION:Tourists @ Drive\n\nFollow on MiLB First Pitch: https://stza.co/+xEZh-2R\n\nShop: https://stza.co/+xEZh-2_\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144502Z
LAST-MODIFIED:20180213T144502Z
TRANSP:OPAQUE
END:VEVENT
* Tourists @ Drive
<2018-06-23 Sat 18:05-21:05>
:PROPERTIES:
:ID:       AJ_Qt_N0NrnyB9rvtnOXrRwx@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Tourists @ Drive Tourists @ Drive

Follow on MiLB First Pitch  https //stza.co/+xEZi-2u

Shop  https //stza.co/+xEZi-15

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Tourists @ Drive
END:VALARM
DTSTART:20180623T230500Z
DTEND:20180624T020500Z
UID:AJ_Qt_N0NrnyB9rvtnOXrRwx@stanza.co
SUMMARY:Tourists @ Drive
DESCRIPTION:Tourists @ Drive\n\nFollow on MiLB First Pitch: https://stza.co/+xEZi-2u\n\nShop: https://stza.co/+xEZi-15\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144502Z
LAST-MODIFIED:20180213T144502Z
TRANSP:OPAQUE
END:VEVENT
* Tourists vs. RiverDogs
<2018-06-24 Sun 15:05-18:05>
:PROPERTIES:
:ID:       aF0SIFZv0SksIh52I9d_lDXe@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Tourists vs. RiverDogs Tourists vs. RiverDogs

Follow on MiLB First Pitch  https //stza.co/+vNtR-2z

Shop  https //stza.co/+vNtR-3t

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Tourists vs. RiverDogs
END:VALARM
DTSTART:20180624T200500Z
DTEND:20180624T230500Z
UID:aF0SIFZv0SksIh52I9d_lDXe@stanza.co
SUMMARY:Tourists vs. RiverDogs
DESCRIPTION:Tourists vs. RiverDogs\n\nFollow on MiLB First Pitch: https://stza.co/+vNtR-2z\n\nShop: https://stza.co/+vNtR-3t\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144502Z
LAST-MODIFIED:20180213T144502Z
TRANSP:OPAQUE
END:VEVENT
* Tourists vs. RiverDogs
<2018-06-25 Mon 18:05-21:05>
:PROPERTIES:
:ID:       YsYf2f4Wv4Ihc4tr7NZ7Nny4@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Tourists vs. RiverDogs Tourists vs. RiverDogs

Follow on MiLB First Pitch  https //stza.co/+vNtU-31

Shop  https //stza.co/+vNtU-3s

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Tourists vs. RiverDogs
END:VALARM
DTSTART:20180625T230500Z
DTEND:20180626T020500Z
UID:YsYf2f4Wv4Ihc4tr7NZ7Nny4@stanza.co
SUMMARY:Tourists vs. RiverDogs
DESCRIPTION:Tourists vs. RiverDogs\n\nFollow on MiLB First Pitch: https://stza.co/+vNtU-31\n\nShop: https://stza.co/+vNtU-3s\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144502Z
LAST-MODIFIED:20180213T144502Z
TRANSP:OPAQUE
END:VEVENT
* Tourists vs. RiverDogs
<2018-06-26 Tue 18:05-21:05>
:PROPERTIES:
:ID:       QxM4plYVK_6PXNFyS50Oei1r@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Tourists vs. RiverDogs Tourists vs. RiverDogs

Follow on MiLB First Pitch  https //stza.co/+vNtV-38

Shop  https //stza.co/+vNtV-2E

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Tourists vs. RiverDogs
END:VALARM
DTSTART:20180626T230500Z
DTEND:20180627T020500Z
UID:QxM4plYVK_6PXNFyS50Oei1r@stanza.co
SUMMARY:Tourists vs. RiverDogs
DESCRIPTION:Tourists vs. RiverDogs\n\nFollow on MiLB First Pitch: https://stza.co/+vNtV-38\n\nShop: https://stza.co/+vNtV-2E\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144502Z
LAST-MODIFIED:20180213T144502Z
TRANSP:OPAQUE
END:VEVENT
* Tourists @ Fireflies
<2018-06-27 Wed 18:05-21:05>
:PROPERTIES:
:ID:       G-hYsq9DW99P8a_DEFv8pOpj@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Tourists @ Fireflies Tourists @ Fireflies

Follow on MiLB First Pitch  https //stza.co/+xBFx-3t

Shop  https //stza.co/+xBFx-3Q

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Tourists @ Fireflies
END:VALARM
DTSTART:20180627T230500Z
DTEND:20180628T020500Z
UID:G-hYsq9DW99P8a_DEFv8pOpj@stanza.co
SUMMARY:Tourists @ Fireflies
DESCRIPTION:Tourists @ Fireflies\n\nFollow on MiLB First Pitch: https://stza.co/+xBFx-3t\n\nShop: https://stza.co/+xBFx-3Q\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144502Z
LAST-MODIFIED:20180213T144502Z
TRANSP:OPAQUE
END:VEVENT
* Tourists @ Fireflies
<2018-06-28 Thu 18:05-21:05>
:PROPERTIES:
:ID:       SpvydtLSb9eygSJO7ETSgr81@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Tourists @ Fireflies Tourists @ Fireflies

Follow on MiLB First Pitch  https //stza.co/+xBFy-2x

Shop  https //stza.co/+xBFy-3H

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Tourists @ Fireflies
END:VALARM
DTSTART:20180628T230500Z
DTEND:20180629T020500Z
UID:SpvydtLSb9eygSJO7ETSgr81@stanza.co
SUMMARY:Tourists @ Fireflies
DESCRIPTION:Tourists @ Fireflies\n\nFollow on MiLB First Pitch: https://stza.co/+xBFy-2x\n\nShop: https://stza.co/+xBFy-3H\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144502Z
LAST-MODIFIED:20180213T144502Z
TRANSP:OPAQUE
END:VEVENT
* Tourists @ Fireflies
<2018-06-29 Fri 18:05-21:05>
:PROPERTIES:
:ID:       WL_TolARO0j7VoEWNmmDFkhF@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Tourists @ Fireflies Tourists @ Fireflies

Follow on MiLB First Pitch  https //stza.co/+xBFA-1b

Shop  https //stza.co/+xBFA-8

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Tourists @ Fireflies
END:VALARM
DTSTART:20180629T230500Z
DTEND:20180630T020500Z
UID:WL_TolARO0j7VoEWNmmDFkhF@stanza.co
SUMMARY:Tourists @ Fireflies
DESCRIPTION:Tourists @ Fireflies\n\nFollow on MiLB First Pitch: https://stza.co/+xBFA-1b\n\nShop: https://stza.co/+xBFA-8\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144502Z
LAST-MODIFIED:20180213T144502Z
TRANSP:OPAQUE
END:VEVENT
* Tourists @ Legends
<2018-06-30 Sat 17:35-20:35>
:PROPERTIES:
:ID:       rmCDpcdxFG2A7ocxHf5_FRIU@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Tourists @ Legends Tourists @ Legends

Follow on MiLB First Pitch  https //stza.co/+xAPv-n

Shop  https //stza.co/+xAPv-3Y

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Tourists @ Legends
END:VALARM
DTSTART:20180630T223500Z
DTEND:20180701T013500Z
UID:rmCDpcdxFG2A7ocxHf5_FRIU@stanza.co
SUMMARY:Tourists @ Legends
DESCRIPTION:Tourists @ Legends\n\nFollow on MiLB First Pitch: https://stza.co/+xAPv-n\n\nShop: https://stza.co/+xAPv-3Y\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144502Z
LAST-MODIFIED:20180213T144502Z
TRANSP:OPAQUE
END:VEVENT
* Tourists @ Legends
<2018-07-01 Sun 13:05-16:05>
:PROPERTIES:
:ID:       dZJ7ELsWwxiuizaJ65Op7cY-@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Tourists @ Legends Tourists @ Legends

Follow on MiLB First Pitch  https //stza.co/+xAPw-1N

Shop  https //stza.co/+xAPw-1$

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Tourists @ Legends
END:VALARM
DTSTART:20180701T180500Z
DTEND:20180701T210500Z
UID:dZJ7ELsWwxiuizaJ65Op7cY-@stanza.co
SUMMARY:Tourists @ Legends
DESCRIPTION:Tourists @ Legends\n\nFollow on MiLB First Pitch: https://stza.co/+xAPw-1N\n\nShop: https://stza.co/+xAPw-1$\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144502Z
LAST-MODIFIED:20180213T144502Z
TRANSP:OPAQUE
END:VEVENT
* Tourists @ Legends
<2018-07-02 Mon 18:05-21:05>
:PROPERTIES:
:ID:       DYxFZiDamxDkggokX_7lmDGH@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Tourists @ Legends Tourists @ Legends

Follow on MiLB First Pitch  https //stza.co/+xAPx-3r

Shop  https //stza.co/+xAPx-1C

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Tourists @ Legends
END:VALARM
DTSTART:20180702T230500Z
DTEND:20180703T020500Z
UID:DYxFZiDamxDkggokX_7lmDGH@stanza.co
SUMMARY:Tourists @ Legends
DESCRIPTION:Tourists @ Legends\n\nFollow on MiLB First Pitch: https://stza.co/+xAPx-3r\n\nShop: https://stza.co/+xAPx-1C\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144502Z
LAST-MODIFIED:20180213T144502Z
TRANSP:OPAQUE
END:VEVENT
* Tourists @ Legends
<2018-07-03 Tue 18:05-21:05>
:PROPERTIES:
:ID:       9HXh2AsGCUjqUYFgpk9vjlOk@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Tourists @ Legends Tourists @ Legends

Follow on MiLB First Pitch  https //stza.co/+xAPy-t

Shop  https //stza.co/+xAPy-21

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Tourists @ Legends
END:VALARM
DTSTART:20180703T230500Z
DTEND:20180704T020500Z
UID:9HXh2AsGCUjqUYFgpk9vjlOk@stanza.co
SUMMARY:Tourists @ Legends
DESCRIPTION:Tourists @ Legends\n\nFollow on MiLB First Pitch: https://stza.co/+xAPy-t\n\nShop: https://stza.co/+xAPy-21\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144502Z
LAST-MODIFIED:20180213T144502Z
TRANSP:OPAQUE
END:VEVENT
* Tourists vs. Braves
<2018-07-04 Wed 18:05-21:05>
:PROPERTIES:
:ID:       eYOnWrWPfUOrtqqHNjRjVFnq@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Tourists vs. Braves Tourists vs. Braves

Follow on MiLB First Pitch  https //stza.co/+vNtY-1O

Shop  https //stza.co/+vNtY-3

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Tourists vs. Braves
END:VALARM
DTSTART:20180704T230500Z
DTEND:20180705T020500Z
UID:eYOnWrWPfUOrtqqHNjRjVFnq@stanza.co
SUMMARY:Tourists vs. Braves
DESCRIPTION:Tourists vs. Braves\n\nFollow on MiLB First Pitch: https://stza.co/+vNtY-1O\n\nShop: https://stza.co/+vNtY-3\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144502Z
LAST-MODIFIED:20180213T144502Z
TRANSP:OPAQUE
END:VEVENT
* Tourists vs. Braves
<2018-07-05 Thu 18:05-21:05>
:PROPERTIES:
:ID:       ltsnNCj272wB8pRD4_xeTWPK@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Tourists vs. Braves Tourists vs. Braves

Follow on MiLB First Pitch  https //stza.co/+vNtZ-2K

Shop  https //stza.co/+vNtZ-1c

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Tourists vs. Braves
END:VALARM
DTSTART:20180705T230500Z
DTEND:20180706T020500Z
UID:ltsnNCj272wB8pRD4_xeTWPK@stanza.co
SUMMARY:Tourists vs. Braves
DESCRIPTION:Tourists vs. Braves\n\nFollow on MiLB First Pitch: https://stza.co/+vNtZ-2K\n\nShop: https://stza.co/+vNtZ-1c\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144502Z
LAST-MODIFIED:20180213T144502Z
TRANSP:OPAQUE
END:VEVENT
* Tourists vs. Braves
<2018-07-06 Fri 18:05-21:05>
:PROPERTIES:
:ID:       McrAyw92QCMofx29276yozYq@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Tourists vs. Braves Tourists vs. Braves

Follow on MiLB First Pitch  https //stza.co/+vNt$-1r

Shop  https //stza.co/+vNt$-2_

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Tourists vs. Braves
END:VALARM
DTSTART:20180706T230500Z
DTEND:20180707T020500Z
UID:McrAyw92QCMofx29276yozYq@stanza.co
SUMMARY:Tourists vs. Braves
DESCRIPTION:Tourists vs. Braves\n\nFollow on MiLB First Pitch: https://stza.co/+vNt$-1r\n\nShop: https://stza.co/+vNt$-2_\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144502Z
LAST-MODIFIED:20180213T144502Z
TRANSP:OPAQUE
END:VEVENT
* Tourists vs. Drive
<2018-07-07 Sat 17:05-20:05>
:PROPERTIES:
:ID:       22lFuTqhJ14_NUxcmDYq_62P@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Tourists vs. Drive Tourists vs. Drive

Follow on MiLB First Pitch  https //stza.co/+vNu2-1t

Shop  https //stza.co/+vNu2-x

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Tourists vs. Drive
END:VALARM
DTSTART:20180707T220500Z
DTEND:20180708T010500Z
UID:22lFuTqhJ14_NUxcmDYq_62P@stanza.co
SUMMARY:Tourists vs. Drive
DESCRIPTION:Tourists vs. Drive\n\nFollow on MiLB First Pitch: https://stza.co/+vNu2-1t\n\nShop: https://stza.co/+vNu2-x\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144502Z
LAST-MODIFIED:20180213T144502Z
TRANSP:OPAQUE
END:VEVENT
* Tourists vs. Drive
<2018-07-08 Sun 13:05-16:05>
:PROPERTIES:
:ID:       wFgmb75TSeaQhhK2TaeuwWwo@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Tourists vs. Drive Tourists vs. Drive

Follow on MiLB First Pitch  https //stza.co/+vNu3-2F

Shop  https //stza.co/+vNu3-2Z

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Tourists vs. Drive
END:VALARM
DTSTART:20180708T180500Z
DTEND:20180708T210500Z
UID:wFgmb75TSeaQhhK2TaeuwWwo@stanza.co
SUMMARY:Tourists vs. Drive
DESCRIPTION:Tourists vs. Drive\n\nFollow on MiLB First Pitch: https://stza.co/+vNu3-2F\n\nShop: https://stza.co/+vNu3-2Z\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144502Z
LAST-MODIFIED:20180213T144502Z
TRANSP:OPAQUE
END:VEVENT
* Tourists vs. Drive
<2018-07-09 Mon 18:05-21:05>
:PROPERTIES:
:ID:       OYbRASWMp2ZwJ2sjqvf4e_1S@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Tourists vs. Drive Tourists vs. Drive

Follow on MiLB First Pitch  https //stza.co/+vNu6-17

Shop  https //stza.co/+vNu6-k

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Tourists vs. Drive
END:VALARM
DTSTART:20180709T230500Z
DTEND:20180710T020500Z
UID:OYbRASWMp2ZwJ2sjqvf4e_1S@stanza.co
SUMMARY:Tourists vs. Drive
DESCRIPTION:Tourists vs. Drive\n\nFollow on MiLB First Pitch: https://stza.co/+vNu6-17\n\nShop: https://stza.co/+vNu6-k\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144502Z
LAST-MODIFIED:20180213T144502Z
TRANSP:OPAQUE
END:VEVENT
* Tourists @ BlueClaws
<2018-07-11 Wed 18:05-21:05>
:PROPERTIES:
:ID:       GMNzfHQAyRaWQmFUj67U_lAW@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Tourists @ BlueClaws Tourists @ BlueClaws

Follow on MiLB First Pitch  https //stza.co/+vNvv-b

Shop  https //stza.co/+vNvv-1x

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Tourists @ BlueClaws
END:VALARM
DTSTART:20180711T230500Z
DTEND:20180712T020500Z
UID:GMNzfHQAyRaWQmFUj67U_lAW@stanza.co
SUMMARY:Tourists @ BlueClaws
DESCRIPTION:Tourists @ BlueClaws\n\nFollow on MiLB First Pitch: https://stza.co/+vNvv-b\n\nShop: https://stza.co/+vNvv-1x\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144502Z
LAST-MODIFIED:20180213T144502Z
TRANSP:OPAQUE
END:VEVENT
* Tourists @ BlueClaws
<2018-07-12 Thu 18:05-21:05>
:PROPERTIES:
:ID:       jAa01XmeK9Lr-KG8hT8v6nu4@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Tourists @ BlueClaws Tourists @ BlueClaws

Follow on MiLB First Pitch  https //stza.co/+vNvw-3X

Shop  https //stza.co/+vNvw-3t

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Tourists @ BlueClaws
END:VALARM
DTSTART:20180712T230500Z
DTEND:20180713T020500Z
UID:jAa01XmeK9Lr-KG8hT8v6nu4@stanza.co
SUMMARY:Tourists @ BlueClaws
DESCRIPTION:Tourists @ BlueClaws\n\nFollow on MiLB First Pitch: https://stza.co/+vNvw-3X\n\nShop: https://stza.co/+vNvw-3t\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144502Z
LAST-MODIFIED:20180213T144502Z
TRANSP:OPAQUE
END:VEVENT
* Tourists @ BlueClaws
<2018-07-13 Fri 18:05-21:05>
:PROPERTIES:
:ID:       ZA9zbJvTaoFe9Rn2XYDJMy-C@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Tourists @ BlueClaws Tourists @ BlueClaws

Follow on MiLB First Pitch  https //stza.co/+vNvx-2n

Shop  https //stza.co/+vNvx-2$

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Tourists @ BlueClaws
END:VALARM
DTSTART:20180713T230500Z
DTEND:20180714T020500Z
UID:ZA9zbJvTaoFe9Rn2XYDJMy-C@stanza.co
SUMMARY:Tourists @ BlueClaws
DESCRIPTION:Tourists @ BlueClaws\n\nFollow on MiLB First Pitch: https://stza.co/+vNvx-2n\n\nShop: https://stza.co/+vNvx-2$\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144502Z
LAST-MODIFIED:20180213T144502Z
TRANSP:OPAQUE
END:VEVENT
* Tourists @ Grasshoppers
<2018-07-14 Sat 18:00-21:00>
:PROPERTIES:
:ID:       gB_Kn_Swu9OgRBmSQyKE7iXb@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Tourists @ Grasshoppers Tourists @ Grasshoppers

Follow on MiLB First Pitch  https //stza.co/+wiwt-J

Shop  https //stza.co/+wiwt-2V

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Tourists @ Grasshoppers
END:VALARM
DTSTART:20180714T230000Z
DTEND:20180715T020000Z
UID:gB_Kn_Swu9OgRBmSQyKE7iXb@stanza.co
SUMMARY:Tourists @ Grasshoppers
DESCRIPTION:Tourists @ Grasshoppers\n\nFollow on MiLB First Pitch: https://stza.co/+wiwt-J\n\nShop: https://stza.co/+wiwt-2V\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144502Z
LAST-MODIFIED:20180213T144502Z
TRANSP:OPAQUE
END:VEVENT
* Tourists @ Grasshoppers
<2018-07-15 Sun 15:00-18:00>
:PROPERTIES:
:ID:       z6Qm1VP7D8sPaCzhYH8ohkq7@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Tourists @ Grasshoppers Tourists @ Grasshoppers

Follow on MiLB First Pitch  https //stza.co/+wiwu-2L

Shop  https //stza.co/+wiwu-1J

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Tourists @ Grasshoppers
END:VALARM
DTSTART:20180715T200000Z
DTEND:20180715T230000Z
UID:z6Qm1VP7D8sPaCzhYH8ohkq7@stanza.co
SUMMARY:Tourists @ Grasshoppers
DESCRIPTION:Tourists @ Grasshoppers\n\nFollow on MiLB First Pitch: https://stza.co/+wiwu-2L\n\nShop: https://stza.co/+wiwu-1J\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144502Z
LAST-MODIFIED:20180213T144502Z
TRANSP:OPAQUE
END:VEVENT
* Tourists @ Grasshoppers
<2018-07-16 Mon 18:00-21:00>
:PROPERTIES:
:ID:       zfPRJNTXdEcv-qGosRDYnPOM@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Tourists @ Grasshoppers Tourists @ Grasshoppers

Follow on MiLB First Pitch  https //stza.co/+wiwv-F

Shop  https //stza.co/+wiwv-1t

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Tourists @ Grasshoppers
END:VALARM
DTSTART:20180716T230000Z
DTEND:20180717T020000Z
UID:zfPRJNTXdEcv-qGosRDYnPOM@stanza.co
SUMMARY:Tourists @ Grasshoppers
DESCRIPTION:Tourists @ Grasshoppers\n\nFollow on MiLB First Pitch: https://stza.co/+wiwv-F\n\nShop: https://stza.co/+wiwv-1t\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144502Z
LAST-MODIFIED:20180213T144502Z
TRANSP:OPAQUE
END:VEVENT
* Tourists @ Grasshoppers
<2018-07-17 Tue 11:00-14:00>
:PROPERTIES:
:ID:       wZyGQ11HikUa-mZnChPw6x_x@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Tourists @ Grasshoppers Tourists @ Grasshoppers

Follow on MiLB First Pitch  https //stza.co/+wiww-17

Shop  https //stza.co/+wiww-3f

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Tourists @ Grasshoppers
END:VALARM
DTSTART:20180717T160000Z
DTEND:20180717T190000Z
UID:wZyGQ11HikUa-mZnChPw6x_x@stanza.co
SUMMARY:Tourists @ Grasshoppers
DESCRIPTION:Tourists @ Grasshoppers\n\nFollow on MiLB First Pitch: https://stza.co/+wiww-17\n\nShop: https://stza.co/+wiww-3f\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144502Z
LAST-MODIFIED:20180213T144502Z
TRANSP:OPAQUE
END:VEVENT
* Tourists vs. Drive
<2018-07-19 Thu 18:05-21:05>
:PROPERTIES:
:ID:       BN8WnUOGz5LCtM6xEAyggxcx@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Tourists vs. Drive Tourists vs. Drive

Follow on MiLB First Pitch  https //stza.co/+vNu8-3Y

Shop  https //stza.co/+vNu8-3O

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Tourists vs. Drive
END:VALARM
DTSTART:20180719T230500Z
DTEND:20180720T020500Z
UID:BN8WnUOGz5LCtM6xEAyggxcx@stanza.co
SUMMARY:Tourists vs. Drive
DESCRIPTION:Tourists vs. Drive\n\nFollow on MiLB First Pitch: https://stza.co/+vNu8-3Y\n\nShop: https://stza.co/+vNu8-3O\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144502Z
LAST-MODIFIED:20180213T144502Z
TRANSP:OPAQUE
END:VEVENT
* Tourists vs. Drive
<2018-07-20 Fri 18:05-21:05>
:PROPERTIES:
:ID:       12oDrs3fy-50A-3WtAHRB9eX@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Tourists vs. Drive Tourists vs. Drive

Follow on MiLB First Pitch  https //stza.co/+vNu9-3w

Shop  https //stza.co/+vNu9-1g

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Tourists vs. Drive
END:VALARM
DTSTART:20180720T230500Z
DTEND:20180721T020500Z
UID:12oDrs3fy-50A-3WtAHRB9eX@stanza.co
SUMMARY:Tourists vs. Drive
DESCRIPTION:Tourists vs. Drive\n\nFollow on MiLB First Pitch: https://stza.co/+vNu9-3w\n\nShop: https://stza.co/+vNu9-1g\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144502Z
LAST-MODIFIED:20180213T144502Z
TRANSP:OPAQUE
END:VEVENT
* Tourists vs. Drive
<2018-07-21 Sat 17:05-20:05>
:PROPERTIES:
:ID:       o61iLLPP0NuoIIw8lAaEvitp@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Tourists vs. Drive Tourists vs. Drive

Follow on MiLB First Pitch  https //stza.co/+vNub-2X

Shop  https //stza.co/+vNub-1f

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Tourists vs. Drive
END:VALARM
DTSTART:20180721T220500Z
DTEND:20180722T010500Z
UID:o61iLLPP0NuoIIw8lAaEvitp@stanza.co
SUMMARY:Tourists vs. Drive
DESCRIPTION:Tourists vs. Drive\n\nFollow on MiLB First Pitch: https://stza.co/+vNub-2X\n\nShop: https://stza.co/+vNub-1f\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144502Z
LAST-MODIFIED:20180213T144502Z
TRANSP:OPAQUE
END:VEVENT
* Tourists vs. Drive
<2018-07-22 Sun 13:05-16:05>
:PROPERTIES:
:ID:       QiZc6x6yYRGdGnS-ueYbr5dZ@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Tourists vs. Drive Tourists vs. Drive

Follow on MiLB First Pitch  https //stza.co/+vNue-2b

Shop  https //stza.co/+vNue-2t

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Tourists vs. Drive
END:VALARM
DTSTART:20180722T180500Z
DTEND:20180722T210500Z
UID:QiZc6x6yYRGdGnS-ueYbr5dZ@stanza.co
SUMMARY:Tourists vs. Drive
DESCRIPTION:Tourists vs. Drive\n\nFollow on MiLB First Pitch: https://stza.co/+vNue-2b\n\nShop: https://stza.co/+vNue-2t\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144502Z
LAST-MODIFIED:20180213T144502Z
TRANSP:OPAQUE
END:VEVENT
* Tourists vs. Legends
<2018-07-23 Mon 18:05-21:05>
:PROPERTIES:
:ID:       T0KlJ--0DhariAaExu4A9UmZ@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Tourists vs. Legends Tourists vs. Legends

Follow on MiLB First Pitch  https //stza.co/+vNuf-2k

Shop  https //stza.co/+vNuf-1S

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Tourists vs. Legends
END:VALARM
DTSTART:20180723T230500Z
DTEND:20180724T020500Z
UID:T0KlJ--0DhariAaExu4A9UmZ@stanza.co
SUMMARY:Tourists vs. Legends
DESCRIPTION:Tourists vs. Legends\n\nFollow on MiLB First Pitch: https://stza.co/+vNuf-2k\n\nShop: https://stza.co/+vNuf-1S\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144502Z
LAST-MODIFIED:20180213T144502Z
TRANSP:OPAQUE
END:VEVENT
* Tourists vs. Legends
<2018-07-24 Tue 18:05-21:05>
:PROPERTIES:
:ID:       4eUgOcllcOvsHPo4MvgETG__@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Tourists vs. Legends Tourists vs. Legends

Follow on MiLB First Pitch  https //stza.co/+vNui-19

Shop  https //stza.co/+vNui-3e

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Tourists vs. Legends
END:VALARM
DTSTART:20180724T230500Z
DTEND:20180725T020500Z
UID:4eUgOcllcOvsHPo4MvgETG__@stanza.co
SUMMARY:Tourists vs. Legends
DESCRIPTION:Tourists vs. Legends\n\nFollow on MiLB First Pitch: https://stza.co/+vNui-19\n\nShop: https://stza.co/+vNui-3e\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144502Z
LAST-MODIFIED:20180213T144502Z
TRANSP:OPAQUE
END:VEVENT
* Tourists vs. Legends
<2018-07-25 Wed 18:05-21:05>
:PROPERTIES:
:ID:       AUetwKJiA43bJIl6nJQkKNRf@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Tourists vs. Legends Tourists vs. Legends

Follow on MiLB First Pitch  https //stza.co/+vNuk-V

Shop  https //stza.co/+vNuk-2e

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Tourists vs. Legends
END:VALARM
DTSTART:20180725T230500Z
DTEND:20180726T020500Z
UID:AUetwKJiA43bJIl6nJQkKNRf@stanza.co
SUMMARY:Tourists vs. Legends
DESCRIPTION:Tourists vs. Legends\n\nFollow on MiLB First Pitch: https://stza.co/+vNuk-V\n\nShop: https://stza.co/+vNuk-2e\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144502Z
LAST-MODIFIED:20180213T144502Z
TRANSP:OPAQUE
END:VEVENT
* Tourists vs. Legends
<2018-07-26 Thu 18:05-21:05>
:PROPERTIES:
:ID:       LFhMn36dF5_mM1h4TZ6nN_bw@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Tourists vs. Legends Tourists vs. Legends

Follow on MiLB First Pitch  https //stza.co/+vNum-2z

Shop  https //stza.co/+vNum-1v

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Tourists vs. Legends
END:VALARM
DTSTART:20180726T230500Z
DTEND:20180727T020500Z
UID:LFhMn36dF5_mM1h4TZ6nN_bw@stanza.co
SUMMARY:Tourists vs. Legends
DESCRIPTION:Tourists vs. Legends\n\nFollow on MiLB First Pitch: https://stza.co/+vNum-2z\n\nShop: https://stza.co/+vNum-1v\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144502Z
LAST-MODIFIED:20180213T144502Z
TRANSP:OPAQUE
END:VEVENT
* Tourists @ Power
<2018-07-27 Fri 18:05-21:05>
:PROPERTIES:
:ID:       IdxXxQjPwrwRylZBbxq01NHC@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Tourists @ Power Tourists @ Power

Follow on MiLB First Pitch  https //stza.co/+xJ3o-2E

Shop  https //stza.co/+xJ3o-2D

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Tourists @ Power
END:VALARM
DTSTART:20180727T230500Z
DTEND:20180728T020500Z
UID:IdxXxQjPwrwRylZBbxq01NHC@stanza.co
SUMMARY:Tourists @ Power
DESCRIPTION:Tourists @ Power\n\nFollow on MiLB First Pitch: https://stza.co/+xJ3o-2E\n\nShop: https://stza.co/+xJ3o-2D\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144502Z
LAST-MODIFIED:20180213T144502Z
TRANSP:OPAQUE
END:VEVENT
* Tourists @ Power
<2018-07-28 Sat 17:05-20:05>
:PROPERTIES:
:ID:       tOJByB-AepRlqyHzve6RYjiW@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Tourists @ Power Tourists @ Power

Follow on MiLB First Pitch  https //stza.co/+xJ3p-2x

Shop  https //stza.co/+xJ3p-12

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Tourists @ Power
END:VALARM
DTSTART:20180728T220500Z
DTEND:20180729T010500Z
UID:tOJByB-AepRlqyHzve6RYjiW@stanza.co
SUMMARY:Tourists @ Power
DESCRIPTION:Tourists @ Power\n\nFollow on MiLB First Pitch: https://stza.co/+xJ3p-2x\n\nShop: https://stza.co/+xJ3p-12\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144502Z
LAST-MODIFIED:20180213T144502Z
TRANSP:OPAQUE
END:VEVENT
* Tourists @ Power
<2018-07-29 Sun 13:05-16:05>
:PROPERTIES:
:ID:       p0_nVv-7HlUfv0riSX2sP0Wx@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Tourists @ Power Tourists @ Power

Follow on MiLB First Pitch  https //stza.co/+xJ3q-7

Shop  https //stza.co/+xJ3q-2t

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Tourists @ Power
END:VALARM
DTSTART:20180729T180500Z
DTEND:20180729T210500Z
UID:p0_nVv-7HlUfv0riSX2sP0Wx@stanza.co
SUMMARY:Tourists @ Power
DESCRIPTION:Tourists @ Power\n\nFollow on MiLB First Pitch: https://stza.co/+xJ3q-7\n\nShop: https://stza.co/+xJ3q-2t\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144502Z
LAST-MODIFIED:20180213T144502Z
TRANSP:OPAQUE
END:VEVENT
* Tourists @ Drive
<2018-07-30 Mon 18:05-21:05>
:PROPERTIES:
:ID:       ujIoB4WdFHn_tW2XRWGd3v21@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Tourists @ Drive Tourists @ Drive

Follow on MiLB First Pitch  https //stza.co/+xEZj-1P

Shop  https //stza.co/+xEZj-3k

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Tourists @ Drive
END:VALARM
DTSTART:20180730T230500Z
DTEND:20180731T020500Z
UID:ujIoB4WdFHn_tW2XRWGd3v21@stanza.co
SUMMARY:Tourists @ Drive
DESCRIPTION:Tourists @ Drive\n\nFollow on MiLB First Pitch: https://stza.co/+xEZj-1P\n\nShop: https://stza.co/+xEZj-3k\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144502Z
LAST-MODIFIED:20180213T144502Z
TRANSP:OPAQUE
END:VEVENT
* Tourists @ Drive
<2018-07-31 Tue 18:05-21:05>
:PROPERTIES:
:ID:       DoHDHL942q7KBEVIRLrPfead@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Tourists @ Drive Tourists @ Drive

Follow on MiLB First Pitch  https //stza.co/+xEZk-s

Shop  https //stza.co/+xEZk-3I

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Tourists @ Drive
END:VALARM
DTSTART:20180731T230500Z
DTEND:20180801T020500Z
UID:DoHDHL942q7KBEVIRLrPfead@stanza.co
SUMMARY:Tourists @ Drive
DESCRIPTION:Tourists @ Drive\n\nFollow on MiLB First Pitch: https://stza.co/+xEZk-s\n\nShop: https://stza.co/+xEZk-3I\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144502Z
LAST-MODIFIED:20180213T144502Z
TRANSP:OPAQUE
END:VEVENT
* Tourists @ Drive
<2018-08-01 Wed 18:05-21:05>
:PROPERTIES:
:ID:       hyDlOHFt2EMstNHXzsnrrykZ@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Tourists @ Drive Tourists @ Drive

Follow on MiLB First Pitch  https //stza.co/+xEZl-2q

Shop  https //stza.co/+xEZl-3Q

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Tourists @ Drive
END:VALARM
DTSTART:20180801T230500Z
DTEND:20180802T020500Z
UID:hyDlOHFt2EMstNHXzsnrrykZ@stanza.co
SUMMARY:Tourists @ Drive
DESCRIPTION:Tourists @ Drive\n\nFollow on MiLB First Pitch: https://stza.co/+xEZl-2q\n\nShop: https://stza.co/+xEZl-3Q\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144502Z
LAST-MODIFIED:20180213T144502Z
TRANSP:OPAQUE
END:VEVENT
* Tourists vs. Fireflies
<2018-08-02 Thu 18:05-21:05>
:PROPERTIES:
:ID:       C_nvExhXheKKc_bskGZFw4NN@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Tourists vs. Fireflies Tourists vs. Fireflies

Follow on MiLB First Pitch  https //stza.co/+vNun-g

Shop  https //stza.co/+vNun-e

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Tourists vs. Fireflies
END:VALARM
DTSTART:20180802T230500Z
DTEND:20180803T020500Z
UID:C_nvExhXheKKc_bskGZFw4NN@stanza.co
SUMMARY:Tourists vs. Fireflies
DESCRIPTION:Tourists vs. Fireflies\n\nFollow on MiLB First Pitch: https://stza.co/+vNun-g\n\nShop: https://stza.co/+vNun-e\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144502Z
LAST-MODIFIED:20180213T144502Z
TRANSP:OPAQUE
END:VEVENT
* Tourists vs. Fireflies
<2018-08-03 Fri 18:05-21:05>
:PROPERTIES:
:ID:       cTPk9geB89nRtTFwFV3u_PBs@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Tourists vs. Fireflies Tourists vs. Fireflies

Follow on MiLB First Pitch  https //stza.co/+vNuq-1Z

Shop  https //stza.co/+vNuq-2V

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Tourists vs. Fireflies
END:VALARM
DTSTART:20180803T230500Z
DTEND:20180804T020500Z
UID:cTPk9geB89nRtTFwFV3u_PBs@stanza.co
SUMMARY:Tourists vs. Fireflies
DESCRIPTION:Tourists vs. Fireflies\n\nFollow on MiLB First Pitch: https://stza.co/+vNuq-1Z\n\nShop: https://stza.co/+vNuq-2V\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144502Z
LAST-MODIFIED:20180213T144502Z
TRANSP:OPAQUE
END:VEVENT
* Tourists vs. Fireflies
<2018-08-04 Sat 17:05-20:05>
:PROPERTIES:
:ID:       P8MC1ph1tPyVhfFrXCf0VUy0@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Tourists vs. Fireflies Tourists vs. Fireflies

Follow on MiLB First Pitch  https //stza.co/+vNus-D

Shop  https //stza.co/+vNus-3Z

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Tourists vs. Fireflies
END:VALARM
DTSTART:20180804T220500Z
DTEND:20180805T010500Z
UID:P8MC1ph1tPyVhfFrXCf0VUy0@stanza.co
SUMMARY:Tourists vs. Fireflies
DESCRIPTION:Tourists vs. Fireflies\n\nFollow on MiLB First Pitch: https://stza.co/+vNus-D\n\nShop: https://stza.co/+vNus-3Z\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144502Z
LAST-MODIFIED:20180213T144502Z
TRANSP:OPAQUE
END:VEVENT
* Tourists vs. Fireflies
<2018-08-05 Sun 13:05-16:05>
:PROPERTIES:
:ID:       RJ_JDQAQOn5uUebOiJ8KZSGl@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Tourists vs. Fireflies Tourists vs. Fireflies

Follow on MiLB First Pitch  https //stza.co/+vNut-3J

Shop  https //stza.co/+vNut-1S

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Tourists vs. Fireflies
END:VALARM
DTSTART:20180805T180500Z
DTEND:20180805T210500Z
UID:RJ_JDQAQOn5uUebOiJ8KZSGl@stanza.co
SUMMARY:Tourists vs. Fireflies
DESCRIPTION:Tourists vs. Fireflies\n\nFollow on MiLB First Pitch: https://stza.co/+vNut-3J\n\nShop: https://stza.co/+vNut-1S\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144502Z
LAST-MODIFIED:20180213T144502Z
TRANSP:OPAQUE
END:VEVENT
* Tourists @ Legends
<2018-08-07 Tue 18:05-21:05>
:PROPERTIES:
:ID:       slkg4nGf1KqeRAtirU0aTBFm@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Tourists @ Legends Tourists @ Legends

Follow on MiLB First Pitch  https //stza.co/+xAPz-3t

Shop  https //stza.co/+xAPz-u

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Tourists @ Legends
END:VALARM
DTSTART:20180807T230500Z
DTEND:20180808T020500Z
UID:slkg4nGf1KqeRAtirU0aTBFm@stanza.co
SUMMARY:Tourists @ Legends
DESCRIPTION:Tourists @ Legends\n\nFollow on MiLB First Pitch: https://stza.co/+xAPz-3t\n\nShop: https://stza.co/+xAPz-u\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144502Z
LAST-MODIFIED:20180213T144502Z
TRANSP:OPAQUE
END:VEVENT
* Tourists @ Legends
<2018-08-08 Wed 12:05-15:05>
:PROPERTIES:
:ID:       RalvkCGboUzISEQkpS4P07RI@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Tourists @ Legends Tourists @ Legends

Follow on MiLB First Pitch  https //stza.co/+xAPC-16

Shop  https //stza.co/+xAPC-1_

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Tourists @ Legends
END:VALARM
DTSTART:20180808T170500Z
DTEND:20180808T200500Z
UID:RalvkCGboUzISEQkpS4P07RI@stanza.co
SUMMARY:Tourists @ Legends
DESCRIPTION:Tourists @ Legends\n\nFollow on MiLB First Pitch: https://stza.co/+xAPC-16\n\nShop: https://stza.co/+xAPC-1_\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144502Z
LAST-MODIFIED:20180213T144502Z
TRANSP:OPAQUE
END:VEVENT
* Tourists @ Legends
<2018-08-09 Thu 18:05-21:05>
:PROPERTIES:
:ID:       -G8VPXYhzeKBzVcc9lqsD8Or@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Tourists @ Legends Tourists @ Legends

Follow on MiLB First Pitch  https //stza.co/+xAPD-d

Shop  https //stza.co/+xAPD-3b

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Tourists @ Legends
END:VALARM
DTSTART:20180809T230500Z
DTEND:20180810T020500Z
UID:-G8VPXYhzeKBzVcc9lqsD8Or@stanza.co
SUMMARY:Tourists @ Legends
DESCRIPTION:Tourists @ Legends\n\nFollow on MiLB First Pitch: https://stza.co/+xAPD-d\n\nShop: https://stza.co/+xAPD-3b\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144502Z
LAST-MODIFIED:20180213T144502Z
TRANSP:OPAQUE
END:VEVENT
* Tourists @ Grasshoppers
<2018-08-10 Fri 18:00-21:00>
:PROPERTIES:
:ID:       yJoeWpRbs8qG2Pe7u6bdf_yc@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Tourists @ Grasshoppers Tourists @ Grasshoppers

Follow on MiLB First Pitch  https //stza.co/+wiwx-$

Shop  https //stza.co/+wiwx-2e

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Tourists @ Grasshoppers
END:VALARM
DTSTART:20180810T230000Z
DTEND:20180811T020000Z
UID:yJoeWpRbs8qG2Pe7u6bdf_yc@stanza.co
SUMMARY:Tourists @ Grasshoppers
DESCRIPTION:Tourists @ Grasshoppers\n\nFollow on MiLB First Pitch: https://stza.co/+wiwx-$\n\nShop: https://stza.co/+wiwx-2e\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144502Z
LAST-MODIFIED:20180213T144502Z
TRANSP:OPAQUE
END:VEVENT
* Tourists @ Grasshoppers
<2018-08-11 Sat 18:00-21:00>
:PROPERTIES:
:ID:       HPn97GhzmI3Dh619PT_ir9sj@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Tourists @ Grasshoppers Tourists @ Grasshoppers

Follow on MiLB First Pitch  https //stza.co/+wiwy-V

Shop  https //stza.co/+wiwy-3B

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Tourists @ Grasshoppers
END:VALARM
DTSTART:20180811T230000Z
DTEND:20180812T020000Z
UID:HPn97GhzmI3Dh619PT_ir9sj@stanza.co
SUMMARY:Tourists @ Grasshoppers
DESCRIPTION:Tourists @ Grasshoppers\n\nFollow on MiLB First Pitch: https://stza.co/+wiwy-V\n\nShop: https://stza.co/+wiwy-3B\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144502Z
LAST-MODIFIED:20180213T144502Z
TRANSP:OPAQUE
END:VEVENT
* Tourists @ Grasshoppers
<2018-08-12 Sun 15:00-18:00>
:PROPERTIES:
:ID:       yCNCs3bpqzzCzq1UzuIor5Nh@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Tourists @ Grasshoppers Tourists @ Grasshoppers

Follow on MiLB First Pitch  https //stza.co/+wiwz-n

Shop  https //stza.co/+wiwz-x

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Tourists @ Grasshoppers
END:VALARM
DTSTART:20180812T200000Z
DTEND:20180812T230000Z
UID:yCNCs3bpqzzCzq1UzuIor5Nh@stanza.co
SUMMARY:Tourists @ Grasshoppers
DESCRIPTION:Tourists @ Grasshoppers\n\nFollow on MiLB First Pitch: https://stza.co/+wiwz-n\n\nShop: https://stza.co/+wiwz-x\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144502Z
LAST-MODIFIED:20180213T144502Z
TRANSP:OPAQUE
END:VEVENT
* Tourists @ Grasshoppers
<2018-08-13 Mon 11:00-14:00>
:PROPERTIES:
:ID:       r54n3Eja8Mrjoo1yxou0ua3c@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Tourists @ Grasshoppers Tourists @ Grasshoppers

Follow on MiLB First Pitch  https //stza.co/+wiwA-5

Shop  https //stza.co/+wiwA-3e

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Tourists @ Grasshoppers
END:VALARM
DTSTART:20180813T160000Z
DTEND:20180813T190000Z
UID:r54n3Eja8Mrjoo1yxou0ua3c@stanza.co
SUMMARY:Tourists @ Grasshoppers
DESCRIPTION:Tourists @ Grasshoppers\n\nFollow on MiLB First Pitch: https://stza.co/+wiwA-5\n\nShop: https://stza.co/+wiwA-3e\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144502Z
LAST-MODIFIED:20180213T144502Z
TRANSP:OPAQUE
END:VEVENT
* Tourists vs. Crawdads
<2018-08-15 Wed 18:05-21:05>
:PROPERTIES:
:ID:       8PvfTv9zpayO9hvNHHiab7pd@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Tourists vs. Crawdads Tourists vs. Crawdads

Follow on MiLB First Pitch  https //stza.co/+vNuw-21

Shop  https //stza.co/+vNuw-2y

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Tourists vs. Crawdads
END:VALARM
DTSTART:20180815T230500Z
DTEND:20180816T020500Z
UID:8PvfTv9zpayO9hvNHHiab7pd@stanza.co
SUMMARY:Tourists vs. Crawdads
DESCRIPTION:Tourists vs. Crawdads\n\nFollow on MiLB First Pitch: https://stza.co/+vNuw-21\n\nShop: https://stza.co/+vNuw-2y\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144502Z
LAST-MODIFIED:20180213T144502Z
TRANSP:OPAQUE
END:VEVENT
* Tourists vs. Crawdads
<2018-08-16 Thu 18:05-21:05>
:PROPERTIES:
:ID:       jKUY0mNZkX_mN502GsGfi91g@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Tourists vs. Crawdads Tourists vs. Crawdads

Follow on MiLB First Pitch  https //stza.co/+vNuy-n

Shop  https //stza.co/+vNuy-3u

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Tourists vs. Crawdads
END:VALARM
DTSTART:20180816T230500Z
DTEND:20180817T020500Z
UID:jKUY0mNZkX_mN502GsGfi91g@stanza.co
SUMMARY:Tourists vs. Crawdads
DESCRIPTION:Tourists vs. Crawdads\n\nFollow on MiLB First Pitch: https://stza.co/+vNuy-n\n\nShop: https://stza.co/+vNuy-3u\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144502Z
LAST-MODIFIED:20180213T144502Z
TRANSP:OPAQUE
END:VEVENT
* Tourists vs. Crawdads
<2018-08-17 Fri 18:05-21:05>
:PROPERTIES:
:ID:       wF7lU23WlaghhiF2gKNKL7YW@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Tourists vs. Crawdads Tourists vs. Crawdads

Follow on MiLB First Pitch  https //stza.co/+vNuA-d

Shop  https //stza.co/+vNuA-2Q

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Tourists vs. Crawdads
END:VALARM
DTSTART:20180817T230500Z
DTEND:20180818T020500Z
UID:wF7lU23WlaghhiF2gKNKL7YW@stanza.co
SUMMARY:Tourists vs. Crawdads
DESCRIPTION:Tourists vs. Crawdads\n\nFollow on MiLB First Pitch: https://stza.co/+vNuA-d\n\nShop: https://stza.co/+vNuA-2Q\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144502Z
LAST-MODIFIED:20180213T144502Z
TRANSP:OPAQUE
END:VEVENT
* Tourists vs. GreenJackets
<2018-08-18 Sat 17:05-20:05>
:PROPERTIES:
:ID:       ugUvICq0dRoRtB7bBWFceTh-@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Tourists vs. GreenJackets Tourists vs. GreenJackets

Follow on MiLB First Pitch  https //stza.co/+vNuB-3t

Shop  https //stza.co/+vNuB-1W

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Tourists vs. GreenJackets
END:VALARM
DTSTART:20180818T220500Z
DTEND:20180819T010500Z
UID:ugUvICq0dRoRtB7bBWFceTh-@stanza.co
SUMMARY:Tourists vs. GreenJackets
DESCRIPTION:Tourists vs. GreenJackets\n\nFollow on MiLB First Pitch: https://stza.co/+vNuB-3t\n\nShop: https://stza.co/+vNuB-1W\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144502Z
LAST-MODIFIED:20180213T144502Z
TRANSP:OPAQUE
END:VEVENT
* Tourists vs. GreenJackets
<2018-08-19 Sun 13:05-16:05>
:PROPERTIES:
:ID:       5cBx2yii9W6DH4dcXZJn4dVN@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Tourists vs. GreenJackets Tourists vs. GreenJackets

Follow on MiLB First Pitch  https //stza.co/+vNuE-2X

Shop  https //stza.co/+vNuE-2w

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Tourists vs. GreenJackets
END:VALARM
DTSTART:20180819T180500Z
DTEND:20180819T210500Z
UID:5cBx2yii9W6DH4dcXZJn4dVN@stanza.co
SUMMARY:Tourists vs. GreenJackets
DESCRIPTION:Tourists vs. GreenJackets\n\nFollow on MiLB First Pitch: https://stza.co/+vNuE-2X\n\nShop: https://stza.co/+vNuE-2w\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144502Z
LAST-MODIFIED:20180213T144502Z
TRANSP:OPAQUE
END:VEVENT
* Tourists vs. GreenJackets
<2018-08-20 Mon 18:05-21:05>
:PROPERTIES:
:ID:       AK4hZbIuCGWb8usS1jc_aX8Q@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Tourists vs. GreenJackets Tourists vs. GreenJackets

Follow on MiLB First Pitch  https //stza.co/+vNuF-d

Shop  https //stza.co/+vNuF-3h

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Tourists vs. GreenJackets
END:VALARM
DTSTART:20180820T230500Z
DTEND:20180821T020500Z
UID:AK4hZbIuCGWb8usS1jc_aX8Q@stanza.co
SUMMARY:Tourists vs. GreenJackets
DESCRIPTION:Tourists vs. GreenJackets\n\nFollow on MiLB First Pitch: https://stza.co/+vNuF-d\n\nShop: https://stza.co/+vNuF-3h\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144502Z
LAST-MODIFIED:20180213T144502Z
TRANSP:OPAQUE
END:VEVENT
* Tourists vs. GreenJackets
<2018-08-21 Tue 18:05-21:05>
:PROPERTIES:
:ID:       FfVoNSSst4A-x6KuqRd24imm@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Tourists vs. GreenJackets Tourists vs. GreenJackets

Follow on MiLB First Pitch  https //stza.co/+vNuI-3n

Shop  https //stza.co/+vNuI-R

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Tourists vs. GreenJackets
END:VALARM
DTSTART:20180821T230500Z
DTEND:20180822T020500Z
UID:FfVoNSSst4A-x6KuqRd24imm@stanza.co
SUMMARY:Tourists vs. GreenJackets
DESCRIPTION:Tourists vs. GreenJackets\n\nFollow on MiLB First Pitch: https://stza.co/+vNuI-3n\n\nShop: https://stza.co/+vNuI-R\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144502Z
LAST-MODIFIED:20180213T144502Z
TRANSP:OPAQUE
END:VEVENT
* Tourists @ Fireflies
<2018-08-23 Thu 18:05-21:05>
:PROPERTIES:
:ID:       r6Fkdu4ubZIFxfj8lYxK3MUg@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Tourists @ Fireflies Tourists @ Fireflies

Follow on MiLB First Pitch  https //stza.co/+xBFB-1N

Shop  https //stza.co/+xBFB-y

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Tourists @ Fireflies
END:VALARM
DTSTART:20180823T230500Z
DTEND:20180824T020500Z
UID:r6Fkdu4ubZIFxfj8lYxK3MUg@stanza.co
SUMMARY:Tourists @ Fireflies
DESCRIPTION:Tourists @ Fireflies\n\nFollow on MiLB First Pitch: https://stza.co/+xBFB-1N\n\nShop: https://stza.co/+xBFB-y\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144502Z
LAST-MODIFIED:20180213T144502Z
TRANSP:OPAQUE
END:VEVENT
* Tourists @ Fireflies
<2018-08-24 Fri 18:05-21:05>
:PROPERTIES:
:ID:       0C8Qky5bqnN9r-hyBO29r_KD@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Tourists @ Fireflies Tourists @ Fireflies

Follow on MiLB First Pitch  https //stza.co/+xBFC-c

Shop  https //stza.co/+xBFC-U

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Tourists @ Fireflies
END:VALARM
DTSTART:20180824T230500Z
DTEND:20180825T020500Z
UID:0C8Qky5bqnN9r-hyBO29r_KD@stanza.co
SUMMARY:Tourists @ Fireflies
DESCRIPTION:Tourists @ Fireflies\n\nFollow on MiLB First Pitch: https://stza.co/+xBFC-c\n\nShop: https://stza.co/+xBFC-U\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144502Z
LAST-MODIFIED:20180213T144502Z
TRANSP:OPAQUE
END:VEVENT
* Tourists @ Fireflies
<2018-08-25 Sat 17:05-20:05>
:PROPERTIES:
:ID:       sYcj0wNtZy5WbrKHnouEt0nf@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Tourists @ Fireflies Tourists @ Fireflies

Follow on MiLB First Pitch  https //stza.co/+xBFE-3p

Shop  https //stza.co/+xBFE-3V

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Tourists @ Fireflies
END:VALARM
DTSTART:20180825T220500Z
DTEND:20180826T010500Z
UID:sYcj0wNtZy5WbrKHnouEt0nf@stanza.co
SUMMARY:Tourists @ Fireflies
DESCRIPTION:Tourists @ Fireflies\n\nFollow on MiLB First Pitch: https://stza.co/+xBFE-3p\n\nShop: https://stza.co/+xBFE-3V\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144502Z
LAST-MODIFIED:20180213T144502Z
TRANSP:OPAQUE
END:VEVENT
* Tourists @ Fireflies
<2018-08-26 Sun 13:05-16:05>
:PROPERTIES:
:ID:       R5MS0xdT3UMbuVWMbVNy0Xz9@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Tourists @ Fireflies Tourists @ Fireflies

Follow on MiLB First Pitch  https //stza.co/+xBFF-2C

Shop  https //stza.co/+xBFF-3a

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Tourists @ Fireflies
END:VALARM
DTSTART:20180826T180500Z
DTEND:20180826T210500Z
UID:R5MS0xdT3UMbuVWMbVNy0Xz9@stanza.co
SUMMARY:Tourists @ Fireflies
DESCRIPTION:Tourists @ Fireflies\n\nFollow on MiLB First Pitch: https://stza.co/+xBFF-2C\n\nShop: https://stza.co/+xBFF-3a\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144502Z
LAST-MODIFIED:20180213T144502Z
TRANSP:OPAQUE
END:VEVENT
* Tourists @ Intimidators
<2018-08-27 Mon 18:05-21:05>
:PROPERTIES:
:ID:       30ESo_i9YcXSSCYLYWd_Kjt6@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Tourists @ Intimidators Tourists @ Intimidators

Follow on MiLB First Pitch  https //stza.co/+wIAe-3x

Shop  https //stza.co/+wIAe-3T

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Tourists @ Intimidators
END:VALARM
DTSTART:20180827T230500Z
DTEND:20180828T020500Z
UID:30ESo_i9YcXSSCYLYWd_Kjt6@stanza.co
SUMMARY:Tourists @ Intimidators
DESCRIPTION:Tourists @ Intimidators\n\nFollow on MiLB First Pitch: https://stza.co/+wIAe-3x\n\nShop: https://stza.co/+wIAe-3T\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144502Z
LAST-MODIFIED:20180213T144502Z
TRANSP:OPAQUE
END:VEVENT
* Tourists @ Intimidators
<2018-08-28 Tue 18:05-21:05>
:PROPERTIES:
:ID:       LsOMcmAAAn1vzvwPMminWZT7@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Tourists @ Intimidators Tourists @ Intimidators

Follow on MiLB First Pitch  https //stza.co/+wIAf-2W

Shop  https //stza.co/+wIAf-a

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Tourists @ Intimidators
END:VALARM
DTSTART:20180828T230500Z
DTEND:20180829T020500Z
UID:LsOMcmAAAn1vzvwPMminWZT7@stanza.co
SUMMARY:Tourists @ Intimidators
DESCRIPTION:Tourists @ Intimidators\n\nFollow on MiLB First Pitch: https://stza.co/+wIAf-2W\n\nShop: https://stza.co/+wIAf-a\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144502Z
LAST-MODIFIED:20180213T144502Z
TRANSP:OPAQUE
END:VEVENT
* Tourists @ Intimidators
<2018-08-29 Wed 18:05-21:05>
:PROPERTIES:
:ID:       kCl2Nc0rAh9Kq5jAL1EbghIx@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Tourists @ Intimidators Tourists @ Intimidators

Follow on MiLB First Pitch  https //stza.co/+wIAg-22

Shop  https //stza.co/+wIAg-3W

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Tourists @ Intimidators
END:VALARM
DTSTART:20180829T230500Z
DTEND:20180830T020500Z
UID:kCl2Nc0rAh9Kq5jAL1EbghIx@stanza.co
SUMMARY:Tourists @ Intimidators
DESCRIPTION:Tourists @ Intimidators\n\nFollow on MiLB First Pitch: https://stza.co/+wIAg-22\n\nShop: https://stza.co/+wIAg-3W\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144502Z
LAST-MODIFIED:20180213T144502Z
TRANSP:OPAQUE
END:VEVENT
* Tourists @ Intimidators
<2018-08-30 Thu 18:05-21:05>
:PROPERTIES:
:ID:       NFHDKVTbrcAiKzrr0J7Mn427@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Tourists @ Intimidators Tourists @ Intimidators

Follow on MiLB First Pitch  https //stza.co/+wIAh-1F

Shop  https //stza.co/+wIAh-c

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Tourists @ Intimidators
END:VALARM
DTSTART:20180830T230500Z
DTEND:20180831T020500Z
UID:NFHDKVTbrcAiKzrr0J7Mn427@stanza.co
SUMMARY:Tourists @ Intimidators
DESCRIPTION:Tourists @ Intimidators\n\nFollow on MiLB First Pitch: https://stza.co/+wIAh-1F\n\nShop: https://stza.co/+wIAh-c\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144502Z
LAST-MODIFIED:20180213T144502Z
TRANSP:OPAQUE
END:VEVENT
* Tourists vs. Braves
<2018-08-31 Fri 18:05-21:05>
:PROPERTIES:
:ID:       8PXLLM8QgHcU0g6_5lpnNMy4@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Tourists vs. Braves Tourists vs. Braves

Follow on MiLB First Pitch  https //stza.co/+vNuJ-l

Shop  https //stza.co/+vNuJ-2U

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Tourists vs. Braves
END:VALARM
DTSTART:20180831T230500Z
DTEND:20180901T020500Z
UID:8PXLLM8QgHcU0g6_5lpnNMy4@stanza.co
SUMMARY:Tourists vs. Braves
DESCRIPTION:Tourists vs. Braves\n\nFollow on MiLB First Pitch: https://stza.co/+vNuJ-l\n\nShop: https://stza.co/+vNuJ-2U\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144502Z
LAST-MODIFIED:20180213T144502Z
TRANSP:OPAQUE
END:VEVENT
* Tourists vs. Braves
<2018-09-01 Sat 17:05-20:05>
:PROPERTIES:
:ID:       WXGeFhGu5I2lUNuNd3_4FEGz@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Tourists vs. Braves Tourists vs. Braves

Follow on MiLB First Pitch  https //stza.co/+vNuL-1O

Shop  https //stza.co/+vNuL-4

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Tourists vs. Braves
END:VALARM
DTSTART:20180901T220500Z
DTEND:20180902T010500Z
UID:WXGeFhGu5I2lUNuNd3_4FEGz@stanza.co
SUMMARY:Tourists vs. Braves
DESCRIPTION:Tourists vs. Braves\n\nFollow on MiLB First Pitch: https://stza.co/+vNuL-1O\n\nShop: https://stza.co/+vNuL-4\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144502Z
LAST-MODIFIED:20180213T144502Z
TRANSP:OPAQUE
END:VEVENT
* Tourists vs. Braves
<2018-09-02 Sun 18:05-21:05>
:PROPERTIES:
:ID:       2f1LlI5N-oCPk0EFLm4xyMl7@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Tourists vs. Braves Tourists vs. Braves

Follow on MiLB First Pitch  https //stza.co/+xBFt-2Z

Shop  https //stza.co/+xBFt-k

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Tourists vs. Braves
END:VALARM
DTSTART:20180902T230500Z
DTEND:20180903T020500Z
UID:2f1LlI5N-oCPk0EFLm4xyMl7@stanza.co
SUMMARY:Tourists vs. Braves
DESCRIPTION:Tourists vs. Braves\n\nFollow on MiLB First Pitch: https://stza.co/+xBFt-2Z\n\nShop: https://stza.co/+xBFt-k\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144502Z
LAST-MODIFIED:20180213T144502Z
TRANSP:OPAQUE
END:VEVENT
* Tourists vs. Braves
<2018-09-03 Mon 12:05-15:05>
:PROPERTIES:
:ID:       5hpUWDrSc1l0pPm--E0VZAH8@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Tourists vs. Braves Tourists vs. Braves

Follow on MiLB First Pitch  https //stza.co/+xBFu-3M

Shop  https //stza.co/+xBFu-3

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Tourists vs. Braves
END:VALARM
DTSTART:20180903T170500Z
DTEND:20180903T200500Z
UID:5hpUWDrSc1l0pPm--E0VZAH8@stanza.co
SUMMARY:Tourists vs. Braves
DESCRIPTION:Tourists vs. Braves\n\nFollow on MiLB First Pitch: https://stza.co/+xBFu-3M\n\nShop: https://stza.co/+xBFu-3\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144502Z
LAST-MODIFIED:20180213T144502Z
TRANSP:OPAQUE
END:VEVENT
