#+TITLE:       Main Google calendar entries
#+AUTHOR:      Eric S Fraga
#+EMAIL:       e.fraga@ucl.ac.uk
#+DESCRIPTION: converted using the ical2org awk script
#+CATEGORY:    google
#+STARTUP:     hidestars
#+STARTUP:     overview

* COMMENT original iCal preamble

* River Bandits vs. Kernels
<2018-04-05 Thu 18:35-21:35>
:PROPERTIES:
:ID:       TrsKDsWo4zb8najEnTUd6UJF@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

River Bandits vs. Kernels River Bandits vs. Kernels

Follow on MiLB First Pitch  https //stza.co/+wxqr-2d

Shop  https //stza.co/+wxqr-3T

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:River Bandits vs. Kernels
END:VALARM
DTSTART:20180405T233500Z
DTEND:20180406T023500Z
UID:TrsKDsWo4zb8najEnTUd6UJF@stanza.co
SUMMARY:River Bandits vs. Kernels
DESCRIPTION:River Bandits vs. Kernels\n\nFollow on MiLB First Pitch: https://stza.co/+wxqr-2d\n\nShop: https://stza.co/+wxqr-3T\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144552Z
LAST-MODIFIED:20180213T144552Z
TRANSP:OPAQUE
END:VEVENT
* River Bandits vs. Kernels
<2018-04-06 Fri 18:35-21:35>
:PROPERTIES:
:ID:       xiDTzs5t64mPohFpWZQ_u-Tp@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

River Bandits vs. Kernels River Bandits vs. Kernels

Follow on MiLB First Pitch  https //stza.co/+wxqu-3z

Shop  https //stza.co/+wxqu-4

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:River Bandits vs. Kernels
END:VALARM
DTSTART:20180406T233500Z
DTEND:20180407T023500Z
UID:xiDTzs5t64mPohFpWZQ_u-Tp@stanza.co
SUMMARY:River Bandits vs. Kernels
DESCRIPTION:River Bandits vs. Kernels\n\nFollow on MiLB First Pitch: https://stza.co/+wxqu-3z\n\nShop: https://stza.co/+wxqu-4\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144552Z
LAST-MODIFIED:20180213T144552Z
TRANSP:OPAQUE
END:VEVENT
* River Bandits @ Kernels
<2018-04-07 Sat 17:05-20:05>
:PROPERTIES:
:ID:       L3BA6EsaF93_YHFXg0hmjmLF@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

River Bandits @ Kernels River Bandits @ Kernels

Buy tickets here  https //stza.co/~vNfZ

Follow on MiLB First Pitch  https //stza.co/+vNfZ-27

Shop  https //stza.co/+vNfZ-2C

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:River Bandits @ Kernels
END:VALARM
DTSTART:20180407T220500Z
DTEND:20180408T010500Z
UID:L3BA6EsaF93_YHFXg0hmjmLF@stanza.co
SUMMARY:River Bandits @ Kernels
DESCRIPTION:River Bandits @ Kernels\n\nBuy tickets here: https://stza.co/~vNfZ\n\nFollow on MiLB First Pitch: https://stza.co/+vNfZ-27\n\nShop: https://stza.co/+vNfZ-2C\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144552Z
LAST-MODIFIED:20180213T144552Z
TRANSP:OPAQUE
END:VEVENT
* River Bandits @ Kernels
<2018-04-08 Sun 14:05-17:05>
:PROPERTIES:
:ID:       EtUROknz74c8rlLfX8ro0o3A@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

River Bandits @ Kernels River Bandits @ Kernels

Buy tickets here  https //stza.co/~vNf_

Follow on MiLB First Pitch  https //stza.co/+vNf_-W

Shop  https //stza.co/+vNf_-1k

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:River Bandits @ Kernels
END:VALARM
DTSTART:20180408T190500Z
DTEND:20180408T220500Z
UID:EtUROknz74c8rlLfX8ro0o3A@stanza.co
SUMMARY:River Bandits @ Kernels
DESCRIPTION:River Bandits @ Kernels\n\nBuy tickets here: https://stza.co/~vNf_\n\nFollow on MiLB First Pitch: https://stza.co/+vNf_-W\n\nShop: https://stza.co/+vNf_-1k\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144552Z
LAST-MODIFIED:20180213T144552Z
TRANSP:OPAQUE
END:VEVENT
* River Bandits vs. Cougars
<2018-04-09 Mon 18:35-21:35>
:PROPERTIES:
:ID:       mRL65yfLQBTHTq3yPPs4Zxnd@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

River Bandits vs. Cougars River Bandits vs. Cougars

Follow on MiLB First Pitch  https //stza.co/+wxqw-2q

Shop  https //stza.co/+wxqw-1p

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:River Bandits vs. Cougars
END:VALARM
DTSTART:20180409T233500Z
DTEND:20180410T023500Z
UID:mRL65yfLQBTHTq3yPPs4Zxnd@stanza.co
SUMMARY:River Bandits vs. Cougars
DESCRIPTION:River Bandits vs. Cougars\n\nFollow on MiLB First Pitch: https://stza.co/+wxqw-2q\n\nShop: https://stza.co/+wxqw-1p\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144552Z
LAST-MODIFIED:20180213T144552Z
TRANSP:OPAQUE
END:VEVENT
* River Bandits vs. Cougars
<2018-04-10 Tue 18:35-21:35>
:PROPERTIES:
:ID:       my6BiHiB1CVX38fT_su-TNr9@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

River Bandits vs. Cougars River Bandits vs. Cougars

Follow on MiLB First Pitch  https //stza.co/+wxqz-V

Shop  https //stza.co/+wxqz-3D

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:River Bandits vs. Cougars
END:VALARM
DTSTART:20180410T233500Z
DTEND:20180411T023500Z
UID:my6BiHiB1CVX38fT_su-TNr9@stanza.co
SUMMARY:River Bandits vs. Cougars
DESCRIPTION:River Bandits vs. Cougars\n\nFollow on MiLB First Pitch: https://stza.co/+wxqz-V\n\nShop: https://stza.co/+wxqz-3D\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144552Z
LAST-MODIFIED:20180213T144552Z
TRANSP:OPAQUE
END:VEVENT
* River Bandits vs. Cougars
<2018-04-11 Wed 18:35-21:35>
:PROPERTIES:
:ID:       QJY9FgNLnHLrGz14UWg4uRGT@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

River Bandits vs. Cougars River Bandits vs. Cougars

Follow on MiLB First Pitch  https //stza.co/+wxqB-y

Shop  https //stza.co/+wxqB-1O

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:River Bandits vs. Cougars
END:VALARM
DTSTART:20180411T233500Z
DTEND:20180412T023500Z
UID:QJY9FgNLnHLrGz14UWg4uRGT@stanza.co
SUMMARY:River Bandits vs. Cougars
DESCRIPTION:River Bandits vs. Cougars\n\nFollow on MiLB First Pitch: https://stza.co/+wxqB-y\n\nShop: https://stza.co/+wxqB-1O\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144552Z
LAST-MODIFIED:20180213T144552Z
TRANSP:OPAQUE
END:VEVENT
* River Bandits vs. Cougars
<2018-04-12 Thu 18:35-21:35>
:PROPERTIES:
:ID:       3nU0BcTDPcIkWgv4M0rek8JV@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

River Bandits vs. Cougars River Bandits vs. Cougars

Follow on MiLB First Pitch  https //stza.co/+wxqC-32

Shop  https //stza.co/+wxqC-29

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:River Bandits vs. Cougars
END:VALARM
DTSTART:20180412T233500Z
DTEND:20180413T023500Z
UID:3nU0BcTDPcIkWgv4M0rek8JV@stanza.co
SUMMARY:River Bandits vs. Cougars
DESCRIPTION:River Bandits vs. Cougars\n\nFollow on MiLB First Pitch: https://stza.co/+wxqC-32\n\nShop: https://stza.co/+wxqC-29\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144552Z
LAST-MODIFIED:20180213T144552Z
TRANSP:OPAQUE
END:VEVENT
* River Bandits @ Bees
<2018-04-13 Fri 18:30-21:30>
:PROPERTIES:
:ID:       CK1fr2QqGH3eFzM6CqxHzp2u@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

River Bandits @ Bees River Bandits @ Bees

Follow on MiLB First Pitch  https //stza.co/+xAI2-1X

Shop  https //stza.co/+xAI2-m

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:River Bandits @ Bees
END:VALARM
DTSTART:20180413T233000Z
DTEND:20180414T023000Z
UID:CK1fr2QqGH3eFzM6CqxHzp2u@stanza.co
SUMMARY:River Bandits @ Bees
DESCRIPTION:River Bandits @ Bees\n\nFollow on MiLB First Pitch: https://stza.co/+xAI2-1X\n\nShop: https://stza.co/+xAI2-m\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144552Z
LAST-MODIFIED:20180213T144552Z
TRANSP:OPAQUE
END:VEVENT
* River Bandits @ Bees
<2018-04-14 Sat 17:00-20:00>
:PROPERTIES:
:ID:       WNAylOzXH5la-Z_NXuJSIBAo@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

River Bandits @ Bees River Bandits @ Bees

Follow on MiLB First Pitch  https //stza.co/+xAI4-3C

Shop  https //stza.co/+xAI4-3q

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:River Bandits @ Bees
END:VALARM
DTSTART:20180414T220000Z
DTEND:20180415T010000Z
UID:WNAylOzXH5la-Z_NXuJSIBAo@stanza.co
SUMMARY:River Bandits @ Bees
DESCRIPTION:River Bandits @ Bees\n\nFollow on MiLB First Pitch: https://stza.co/+xAI4-3C\n\nShop: https://stza.co/+xAI4-3q\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144552Z
LAST-MODIFIED:20180213T144552Z
TRANSP:OPAQUE
END:VEVENT
* River Bandits @ Bees
<2018-04-15 Sun 14:00-17:00>
:PROPERTIES:
:ID:       ZngTnMCLjfjntdr9D1b4vFfn@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

River Bandits @ Bees River Bandits @ Bees

Follow on MiLB First Pitch  https //stza.co/+xAI7-2G

Shop  https //stza.co/+xAI7-C

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:River Bandits @ Bees
END:VALARM
DTSTART:20180415T190000Z
DTEND:20180415T220000Z
UID:ZngTnMCLjfjntdr9D1b4vFfn@stanza.co
SUMMARY:River Bandits @ Bees
DESCRIPTION:River Bandits @ Bees\n\nFollow on MiLB First Pitch: https://stza.co/+xAI7-2G\n\nShop: https://stza.co/+xAI7-C\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144552Z
LAST-MODIFIED:20180213T144552Z
TRANSP:OPAQUE
END:VEVENT
* River Bandits vs. Chiefs
<2018-04-17 Tue 18:35-21:35>
:PROPERTIES:
:ID:       RPoxjWRUwVuvNAlpC7CX8U_P@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

River Bandits vs. Chiefs River Bandits vs. Chiefs

Follow on MiLB First Pitch  https //stza.co/+wxqF-19

Shop  https //stza.co/+wxqF-O

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:River Bandits vs. Chiefs
END:VALARM
DTSTART:20180417T233500Z
DTEND:20180418T023500Z
UID:RPoxjWRUwVuvNAlpC7CX8U_P@stanza.co
SUMMARY:River Bandits vs. Chiefs
DESCRIPTION:River Bandits vs. Chiefs\n\nFollow on MiLB First Pitch: https://stza.co/+wxqF-19\n\nShop: https://stza.co/+wxqF-O\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144552Z
LAST-MODIFIED:20180213T144552Z
TRANSP:OPAQUE
END:VEVENT
* River Bandits vs. Chiefs
<2018-04-18 Wed 18:35-21:35>
:PROPERTIES:
:ID:       OVL2oDBgjOPUJhyhekoljYKo@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

River Bandits vs. Chiefs River Bandits vs. Chiefs

Follow on MiLB First Pitch  https //stza.co/+wxqH-s

Shop  https //stza.co/+wxqH-V

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:River Bandits vs. Chiefs
END:VALARM
DTSTART:20180418T233500Z
DTEND:20180419T023500Z
UID:OVL2oDBgjOPUJhyhekoljYKo@stanza.co
SUMMARY:River Bandits vs. Chiefs
DESCRIPTION:River Bandits vs. Chiefs\n\nFollow on MiLB First Pitch: https://stza.co/+wxqH-s\n\nShop: https://stza.co/+wxqH-V\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144552Z
LAST-MODIFIED:20180213T144552Z
TRANSP:OPAQUE
END:VEVENT
* River Bandits vs. Chiefs
<2018-04-19 Thu 18:35-21:35>
:PROPERTIES:
:ID:       zN5lIdLv7lhYxxHa-PHFgnsM@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

River Bandits vs. Chiefs River Bandits vs. Chiefs

Follow on MiLB First Pitch  https //stza.co/+wxqJ-2u

Shop  https //stza.co/+wxqJ-1b

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:River Bandits vs. Chiefs
END:VALARM
DTSTART:20180419T233500Z
DTEND:20180420T023500Z
UID:zN5lIdLv7lhYxxHa-PHFgnsM@stanza.co
SUMMARY:River Bandits vs. Chiefs
DESCRIPTION:River Bandits vs. Chiefs\n\nFollow on MiLB First Pitch: https://stza.co/+wxqJ-2u\n\nShop: https://stza.co/+wxqJ-1b\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144552Z
LAST-MODIFIED:20180213T144552Z
TRANSP:OPAQUE
END:VEVENT
* River Bandits @ Bees
<2018-04-20 Fri 11:30-14:30>
:PROPERTIES:
:ID:       dFOHDb1aZYP9Umlz1d1DjUdD@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

River Bandits @ Bees River Bandits @ Bees

Follow on MiLB First Pitch  https //stza.co/+xAI8-2a

Shop  https //stza.co/+xAI8-2c

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:River Bandits @ Bees
END:VALARM
DTSTART:20180420T163000Z
DTEND:20180420T193000Z
UID:dFOHDb1aZYP9Umlz1d1DjUdD@stanza.co
SUMMARY:River Bandits @ Bees
DESCRIPTION:River Bandits @ Bees\n\nFollow on MiLB First Pitch: https://stza.co/+xAI8-2a\n\nShop: https://stza.co/+xAI8-2c\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144552Z
LAST-MODIFIED:20180213T144552Z
TRANSP:OPAQUE
END:VEVENT
* River Bandits @ Bees
<2018-04-21 Sat 17:00-20:00>
:PROPERTIES:
:ID:       3YfLo3dO8SXfCXw1PlJVyctQ@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

River Bandits @ Bees River Bandits @ Bees

Follow on MiLB First Pitch  https //stza.co/+xAI9-3f

Shop  https //stza.co/+xAI9-1Q

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:River Bandits @ Bees
END:VALARM
DTSTART:20180421T220000Z
DTEND:20180422T010000Z
UID:3YfLo3dO8SXfCXw1PlJVyctQ@stanza.co
SUMMARY:River Bandits @ Bees
DESCRIPTION:River Bandits @ Bees\n\nFollow on MiLB First Pitch: https://stza.co/+xAI9-3f\n\nShop: https://stza.co/+xAI9-1Q\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144552Z
LAST-MODIFIED:20180213T144552Z
TRANSP:OPAQUE
END:VEVENT
* River Bandits @ Bees
<2018-04-22 Sun 14:00-17:00>
:PROPERTIES:
:ID:       hC5pSfun3xqkdA5gTap9Ptsp@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

River Bandits @ Bees River Bandits @ Bees

Follow on MiLB First Pitch  https //stza.co/+xAIa-p

Shop  https //stza.co/+xAIa-3t

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:River Bandits @ Bees
END:VALARM
DTSTART:20180422T190000Z
DTEND:20180422T220000Z
UID:hC5pSfun3xqkdA5gTap9Ptsp@stanza.co
SUMMARY:River Bandits @ Bees
DESCRIPTION:River Bandits @ Bees\n\nFollow on MiLB First Pitch: https://stza.co/+xAIa-p\n\nShop: https://stza.co/+xAIa-3t\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144552Z
LAST-MODIFIED:20180213T144552Z
TRANSP:OPAQUE
END:VEVENT
* River Bandits @ Cougars
<2018-04-23 Mon 18:30-21:30>
:PROPERTIES:
:ID:       p4Pp6uMnfbSBGzZ5N_tlX9Zy@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

River Bandits @ Cougars River Bandits @ Cougars

Follow on MiLB First Pitch  https //stza.co/+xAIn-2N

Shop  https //stza.co/+xAIn-3L

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:River Bandits @ Cougars
END:VALARM
DTSTART:20180423T233000Z
DTEND:20180424T023000Z
UID:p4Pp6uMnfbSBGzZ5N_tlX9Zy@stanza.co
SUMMARY:River Bandits @ Cougars
DESCRIPTION:River Bandits @ Cougars\n\nFollow on MiLB First Pitch: https://stza.co/+xAIn-2N\n\nShop: https://stza.co/+xAIn-3L\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144552Z
LAST-MODIFIED:20180213T144552Z
TRANSP:OPAQUE
END:VEVENT
* River Bandits @ Cougars
<2018-04-24 Tue 12:00-15:00>
:PROPERTIES:
:ID:       ZDup1hCHvr9-jd5gFwLhnqz7@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

River Bandits @ Cougars River Bandits @ Cougars

Follow on MiLB First Pitch  https //stza.co/+xAIq-2V

Shop  https //stza.co/+xAIq-2

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:River Bandits @ Cougars
END:VALARM
DTSTART:20180424T170000Z
DTEND:20180424T200000Z
UID:ZDup1hCHvr9-jd5gFwLhnqz7@stanza.co
SUMMARY:River Bandits @ Cougars
DESCRIPTION:River Bandits @ Cougars\n\nFollow on MiLB First Pitch: https://stza.co/+xAIq-2V\n\nShop: https://stza.co/+xAIq-2\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144552Z
LAST-MODIFIED:20180213T144552Z
TRANSP:OPAQUE
END:VEVENT
* River Bandits @ Cougars
<2018-04-25 Wed 11:00-14:00>
:PROPERTIES:
:ID:       ESB08N3s2HB99MfBU0_E3dyE@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

River Bandits @ Cougars River Bandits @ Cougars

Follow on MiLB First Pitch  https //stza.co/+xAIr-1O

Shop  https //stza.co/+xAIr-3D

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:River Bandits @ Cougars
END:VALARM
DTSTART:20180425T160000Z
DTEND:20180425T190000Z
UID:ESB08N3s2HB99MfBU0_E3dyE@stanza.co
SUMMARY:River Bandits @ Cougars
DESCRIPTION:River Bandits @ Cougars\n\nFollow on MiLB First Pitch: https://stza.co/+xAIr-1O\n\nShop: https://stza.co/+xAIr-3D\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144552Z
LAST-MODIFIED:20180213T144552Z
TRANSP:OPAQUE
END:VEVENT
* River Bandits @ Cougars
<2018-04-26 Thu 18:30-21:30>
:PROPERTIES:
:ID:       U1XOe5DAXkF8fzSAWSRDM5AK@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

River Bandits @ Cougars River Bandits @ Cougars

Follow on MiLB First Pitch  https //stza.co/+xAIs-g

Shop  https //stza.co/+xAIs-1c

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:River Bandits @ Cougars
END:VALARM
DTSTART:20180426T233000Z
DTEND:20180427T023000Z
UID:U1XOe5DAXkF8fzSAWSRDM5AK@stanza.co
SUMMARY:River Bandits @ Cougars
DESCRIPTION:River Bandits @ Cougars\n\nFollow on MiLB First Pitch: https://stza.co/+xAIs-g\n\nShop: https://stza.co/+xAIs-1c\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144552Z
LAST-MODIFIED:20180213T144552Z
TRANSP:OPAQUE
END:VEVENT
* River Bandits vs. Kernels
<2018-04-27 Fri 18:35-21:35>
:PROPERTIES:
:ID:       sIh_Y-VPUbLYY9-URcIpbiQ4@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

River Bandits vs. Kernels River Bandits vs. Kernels

Follow on MiLB First Pitch  https //stza.co/+wxqL-33

Shop  https //stza.co/+wxqL-h

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:River Bandits vs. Kernels
END:VALARM
DTSTART:20180427T233500Z
DTEND:20180428T023500Z
UID:sIh_Y-VPUbLYY9-URcIpbiQ4@stanza.co
SUMMARY:River Bandits vs. Kernels
DESCRIPTION:River Bandits vs. Kernels\n\nFollow on MiLB First Pitch: https://stza.co/+wxqL-33\n\nShop: https://stza.co/+wxqL-h\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144552Z
LAST-MODIFIED:20180213T144552Z
TRANSP:OPAQUE
END:VEVENT
* River Bandits vs. Kernels
<2018-04-28 Sat 13:15-16:15>
:PROPERTIES:
:ID:       3yh5NFree5LPG1KHOKTxYn2N@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

River Bandits vs. Kernels River Bandits vs. Kernels

Follow on MiLB First Pitch  https //stza.co/+wxqN-2z

Shop  https //stza.co/+wxqN-u

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:River Bandits vs. Kernels
END:VALARM
DTSTART:20180428T181500Z
DTEND:20180428T211500Z
UID:3yh5NFree5LPG1KHOKTxYn2N@stanza.co
SUMMARY:River Bandits vs. Kernels
DESCRIPTION:River Bandits vs. Kernels\n\nFollow on MiLB First Pitch: https://stza.co/+wxqN-2z\n\nShop: https://stza.co/+wxqN-u\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144552Z
LAST-MODIFIED:20180213T144552Z
TRANSP:OPAQUE
END:VEVENT
* River Bandits vs. Kernels
<2018-04-29 Sun 13:15-16:15>
:PROPERTIES:
:ID:       Oju7y4t5RednhZ9DyUBLeEC7@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

River Bandits vs. Kernels River Bandits vs. Kernels

Follow on MiLB First Pitch  https //stza.co/+wxqO-2C

Shop  https //stza.co/+wxqO-1Y

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:River Bandits vs. Kernels
END:VALARM
DTSTART:20180429T181500Z
DTEND:20180429T211500Z
UID:Oju7y4t5RednhZ9DyUBLeEC7@stanza.co
SUMMARY:River Bandits vs. Kernels
DESCRIPTION:River Bandits vs. Kernels\n\nFollow on MiLB First Pitch: https://stza.co/+wxqO-2C\n\nShop: https://stza.co/+wxqO-1Y\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144552Z
LAST-MODIFIED:20180213T144552Z
TRANSP:OPAQUE
END:VEVENT
* River Bandits @ Loons
<2018-05-01 Tue 18:05-21:05>
:PROPERTIES:
:ID:       7tXavWjkYaQ1lc2YzIURZ_6T@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

River Bandits @ Loons River Bandits @ Loons

Follow on MiLB First Pitch  https //stza.co/+vNgg-x

Shop  https //stza.co/+vNgg-3_

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:River Bandits @ Loons
END:VALARM
DTSTART:20180501T230500Z
DTEND:20180502T020500Z
UID:7tXavWjkYaQ1lc2YzIURZ_6T@stanza.co
SUMMARY:River Bandits @ Loons
DESCRIPTION:River Bandits @ Loons\n\nFollow on MiLB First Pitch: https://stza.co/+vNgg-x\n\nShop: https://stza.co/+vNgg-3_\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144552Z
LAST-MODIFIED:20180213T144552Z
TRANSP:OPAQUE
END:VEVENT
* River Bandits @ Loons
<2018-05-02 Wed 18:05-21:05>
:PROPERTIES:
:ID:       TTKV86MxzPD3QLjkKcZyj_xB@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

River Bandits @ Loons River Bandits @ Loons

Follow on MiLB First Pitch  https //stza.co/+vNgh-1B

Shop  https //stza.co/+vNgh-3

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:River Bandits @ Loons
END:VALARM
DTSTART:20180502T230500Z
DTEND:20180503T020500Z
UID:TTKV86MxzPD3QLjkKcZyj_xB@stanza.co
SUMMARY:River Bandits @ Loons
DESCRIPTION:River Bandits @ Loons\n\nFollow on MiLB First Pitch: https://stza.co/+vNgh-1B\n\nShop: https://stza.co/+vNgh-3\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144552Z
LAST-MODIFIED:20180213T144552Z
TRANSP:OPAQUE
END:VEVENT
* River Bandits @ Loons
<2018-05-03 Thu 18:05-21:05>
:PROPERTIES:
:ID:       cX57tI9KbgkVSkcnYBUjdgPI@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

River Bandits @ Loons River Bandits @ Loons

Follow on MiLB First Pitch  https //stza.co/+vNgi-11

Shop  https //stza.co/+vNgi-1L

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:River Bandits @ Loons
END:VALARM
DTSTART:20180503T230500Z
DTEND:20180504T020500Z
UID:cX57tI9KbgkVSkcnYBUjdgPI@stanza.co
SUMMARY:River Bandits @ Loons
DESCRIPTION:River Bandits @ Loons\n\nFollow on MiLB First Pitch: https://stza.co/+vNgi-11\n\nShop: https://stza.co/+vNgi-1L\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144552Z
LAST-MODIFIED:20180213T144552Z
TRANSP:OPAQUE
END:VEVENT
* River Bandits @ Lugnuts
<2018-05-04 Fri 18:05-21:05>
:PROPERTIES:
:ID:       nvOmCzIBDa0NiVtU4Uvx3wzj@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

River Bandits @ Lugnuts River Bandits @ Lugnuts

Follow on MiLB First Pitch  https //stza.co/+vNgr-3Q

Shop  https //stza.co/+vNgr-q

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:River Bandits @ Lugnuts
END:VALARM
DTSTART:20180504T230500Z
DTEND:20180505T020500Z
UID:nvOmCzIBDa0NiVtU4Uvx3wzj@stanza.co
SUMMARY:River Bandits @ Lugnuts
DESCRIPTION:River Bandits @ Lugnuts\n\nFollow on MiLB First Pitch: https://stza.co/+vNgr-3Q\n\nShop: https://stza.co/+vNgr-q\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144552Z
LAST-MODIFIED:20180213T144552Z
TRANSP:OPAQUE
END:VEVENT
* River Bandits @ Lugnuts
<2018-05-05 Sat 18:05-21:05>
:PROPERTIES:
:ID:       HkFND3pXC9rnkXhvBez0LYXF@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

River Bandits @ Lugnuts River Bandits @ Lugnuts

Follow on MiLB First Pitch  https //stza.co/+vNgs-1C

Shop  https //stza.co/+vNgs-2n

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:River Bandits @ Lugnuts
END:VALARM
DTSTART:20180505T230500Z
DTEND:20180506T020500Z
UID:HkFND3pXC9rnkXhvBez0LYXF@stanza.co
SUMMARY:River Bandits @ Lugnuts
DESCRIPTION:River Bandits @ Lugnuts\n\nFollow on MiLB First Pitch: https://stza.co/+vNgs-1C\n\nShop: https://stza.co/+vNgs-2n\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144552Z
LAST-MODIFIED:20180213T144552Z
TRANSP:OPAQUE
END:VEVENT
* River Bandits @ Lugnuts
<2018-05-06 Sun 12:05-15:05>
:PROPERTIES:
:ID:       IZmDCyTlLXO57bFQ5sogrnZ_@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

River Bandits @ Lugnuts River Bandits @ Lugnuts

Follow on MiLB First Pitch  https //stza.co/+vNgt-w

Shop  https //stza.co/+vNgt-22

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:River Bandits @ Lugnuts
END:VALARM
DTSTART:20180506T170500Z
DTEND:20180506T200500Z
UID:IZmDCyTlLXO57bFQ5sogrnZ_@stanza.co
SUMMARY:River Bandits @ Lugnuts
DESCRIPTION:River Bandits @ Lugnuts\n\nFollow on MiLB First Pitch: https://stza.co/+vNgt-w\n\nShop: https://stza.co/+vNgt-22\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144552Z
LAST-MODIFIED:20180213T144552Z
TRANSP:OPAQUE
END:VEVENT
* River Bandits vs. TinCaps
<2018-05-07 Mon 18:35-21:35>
:PROPERTIES:
:ID:       DdSXaVkZ_OeY-opJs_-BrTnE@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

River Bandits vs. TinCaps River Bandits vs. TinCaps

Follow on MiLB First Pitch  https //stza.co/+wxqR-1C

Shop  https //stza.co/+wxqR-N

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:River Bandits vs. TinCaps
END:VALARM
DTSTART:20180507T233500Z
DTEND:20180508T023500Z
UID:DdSXaVkZ_OeY-opJs_-BrTnE@stanza.co
SUMMARY:River Bandits vs. TinCaps
DESCRIPTION:River Bandits vs. TinCaps\n\nFollow on MiLB First Pitch: https://stza.co/+wxqR-1C\n\nShop: https://stza.co/+wxqR-N\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144552Z
LAST-MODIFIED:20180213T144552Z
TRANSP:OPAQUE
END:VEVENT
* River Bandits vs. TinCaps
<2018-05-08 Tue 11:00-14:00>
:PROPERTIES:
:ID:       VkZu4XD485gWA8s2ESPPtZ0C@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

River Bandits vs. TinCaps River Bandits vs. TinCaps

Follow on MiLB First Pitch  https //stza.co/+wxqS-1S

Shop  https //stza.co/+wxqS-24

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:River Bandits vs. TinCaps
END:VALARM
DTSTART:20180508T160000Z
DTEND:20180508T190000Z
UID:VkZu4XD485gWA8s2ESPPtZ0C@stanza.co
SUMMARY:River Bandits vs. TinCaps
DESCRIPTION:River Bandits vs. TinCaps\n\nFollow on MiLB First Pitch: https://stza.co/+wxqS-1S\n\nShop: https://stza.co/+wxqS-24\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144552Z
LAST-MODIFIED:20180213T144552Z
TRANSP:OPAQUE
END:VEVENT
* River Bandits vs. TinCaps
<2018-05-09 Wed 11:00-14:00>
:PROPERTIES:
:ID:       5dHKPLjnHJfnSuaCrMiLjnMb@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

River Bandits vs. TinCaps River Bandits vs. TinCaps

Follow on MiLB First Pitch  https //stza.co/+wxqV-3B

Shop  https //stza.co/+wxqV-1a

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:River Bandits vs. TinCaps
END:VALARM
DTSTART:20180509T160000Z
DTEND:20180509T190000Z
UID:5dHKPLjnHJfnSuaCrMiLjnMb@stanza.co
SUMMARY:River Bandits vs. TinCaps
DESCRIPTION:River Bandits vs. TinCaps\n\nFollow on MiLB First Pitch: https://stza.co/+wxqV-3B\n\nShop: https://stza.co/+wxqV-1a\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144552Z
LAST-MODIFIED:20180213T144552Z
TRANSP:OPAQUE
END:VEVENT
* River Bandits vs. Captains
<2018-05-10 Thu 18:35-21:35>
:PROPERTIES:
:ID:       zYurF7B6j03i4pMNLlP0mABK@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

River Bandits vs. Captains River Bandits vs. Captains

Follow on MiLB First Pitch  https //stza.co/+wxqW-A

Shop  https //stza.co/+wxqW-3u

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:River Bandits vs. Captains
END:VALARM
DTSTART:20180510T233500Z
DTEND:20180511T023500Z
UID:zYurF7B6j03i4pMNLlP0mABK@stanza.co
SUMMARY:River Bandits vs. Captains
DESCRIPTION:River Bandits vs. Captains\n\nFollow on MiLB First Pitch: https://stza.co/+wxqW-A\n\nShop: https://stza.co/+wxqW-3u\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144552Z
LAST-MODIFIED:20180213T144552Z
TRANSP:OPAQUE
END:VEVENT
* River Bandits vs. Captains
<2018-05-11 Fri 18:35-21:35>
:PROPERTIES:
:ID:       Q95Atx7M7fp1K6ItcRS8FXlx@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

River Bandits vs. Captains River Bandits vs. Captains

Follow on MiLB First Pitch  https //stza.co/+wxqY-1l

Shop  https //stza.co/+wxqY-3U

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:River Bandits vs. Captains
END:VALARM
DTSTART:20180511T233500Z
DTEND:20180512T023500Z
UID:Q95Atx7M7fp1K6ItcRS8FXlx@stanza.co
SUMMARY:River Bandits vs. Captains
DESCRIPTION:River Bandits vs. Captains\n\nFollow on MiLB First Pitch: https://stza.co/+wxqY-1l\n\nShop: https://stza.co/+wxqY-3U\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144552Z
LAST-MODIFIED:20180213T144552Z
TRANSP:OPAQUE
END:VEVENT
* River Bandits vs. Captains
<2018-05-12 Sat 18:35-21:35>
:PROPERTIES:
:ID:       ELKfnx-iNan1q_So1Q4zpyh5@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

River Bandits vs. Captains River Bandits vs. Captains

Follow on MiLB First Pitch  https //stza.co/+wxq_-z

Shop  https //stza.co/+wxq_-15

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:River Bandits vs. Captains
END:VALARM
DTSTART:20180512T233500Z
DTEND:20180513T023500Z
UID:ELKfnx-iNan1q_So1Q4zpyh5@stanza.co
SUMMARY:River Bandits vs. Captains
DESCRIPTION:River Bandits vs. Captains\n\nFollow on MiLB First Pitch: https://stza.co/+wxq_-z\n\nShop: https://stza.co/+wxq_-15\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144552Z
LAST-MODIFIED:20180213T144552Z
TRANSP:OPAQUE
END:VEVENT
* River Bandits @ Kernels
<2018-05-14 Mon 18:35-21:35>
:PROPERTIES:
:ID:       qU0VjL58UOwvzdkPmqZvwnKb@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

River Bandits @ Kernels River Bandits @ Kernels

Buy tickets here  https //stza.co/~vNf$

Follow on MiLB First Pitch  https //stza.co/+vNf$-3c

Shop  https //stza.co/+vNf$-1c

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:River Bandits @ Kernels
END:VALARM
DTSTART:20180514T233500Z
DTEND:20180515T023500Z
UID:qU0VjL58UOwvzdkPmqZvwnKb@stanza.co
SUMMARY:River Bandits @ Kernels
DESCRIPTION:River Bandits @ Kernels\n\nBuy tickets here: https://stza.co/~vNf$\n\nFollow on MiLB First Pitch: https://stza.co/+vNf$-3c\n\nShop: https://stza.co/+vNf$-1c\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144552Z
LAST-MODIFIED:20180213T144552Z
TRANSP:OPAQUE
END:VEVENT
* River Bandits @ Kernels
<2018-05-15 Tue 18:35-21:35>
:PROPERTIES:
:ID:       2qP2gAVmCQQ-Cddws7MsNech@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

River Bandits @ Kernels River Bandits @ Kernels

Buy tickets here  https //stza.co/~vNg0

Follow on MiLB First Pitch  https //stza.co/+vNg0-S

Shop  https //stza.co/+vNg0-2o

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:River Bandits @ Kernels
END:VALARM
DTSTART:20180515T233500Z
DTEND:20180516T023500Z
UID:2qP2gAVmCQQ-Cddws7MsNech@stanza.co
SUMMARY:River Bandits @ Kernels
DESCRIPTION:River Bandits @ Kernels\n\nBuy tickets here: https://stza.co/~vNg0\n\nFollow on MiLB First Pitch: https://stza.co/+vNg0-S\n\nShop: https://stza.co/+vNg0-2o\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144552Z
LAST-MODIFIED:20180213T144552Z
TRANSP:OPAQUE
END:VEVENT
* River Bandits @ Kernels
<2018-05-16 Wed 00:05-03:05>
:PROPERTIES:
:ID:       veA12e5dTQ5z2RadqxSo8HSq@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

River Bandits @ Kernels River Bandits @ Kernels

Buy tickets here  https //stza.co/~w0O1

Follow on MiLB First Pitch  https //stza.co/+w0O1-3Q

Shop  https //stza.co/+w0O1-1j

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:River Bandits @ Kernels
END:VALARM
DTSTART:20180516T050500Z
DTEND:20180516T080500Z
UID:veA12e5dTQ5z2RadqxSo8HSq@stanza.co
SUMMARY:River Bandits @ Kernels
DESCRIPTION:River Bandits @ Kernels\n\nBuy tickets here: https://stza.co/~w0O1\n\nFollow on MiLB First Pitch: https://stza.co/+w0O1-3Q\n\nShop: https://stza.co/+w0O1-1j\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144552Z
LAST-MODIFIED:20180213T144552Z
TRANSP:OPAQUE
END:VEVENT
* River Bandits @ Kernels
<2018-05-17 Thu 18:35-21:35>
:PROPERTIES:
:ID:       JBzWkA2xj42bOvC42Zk0HFGJ@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

River Bandits @ Kernels River Bandits @ Kernels

Buy tickets here  https //stza.co/~w0O2

Follow on MiLB First Pitch  https //stza.co/+w0O2-29

Shop  https //stza.co/+w0O2-3F

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:River Bandits @ Kernels
END:VALARM
DTSTART:20180517T233500Z
DTEND:20180518T023500Z
UID:JBzWkA2xj42bOvC42Zk0HFGJ@stanza.co
SUMMARY:River Bandits @ Kernels
DESCRIPTION:River Bandits @ Kernels\n\nBuy tickets here: https://stza.co/~w0O2\n\nFollow on MiLB First Pitch: https://stza.co/+w0O2-29\n\nShop: https://stza.co/+w0O2-3F\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144552Z
LAST-MODIFIED:20180213T144552Z
TRANSP:OPAQUE
END:VEVENT
* River Bandits @ Snappers
<2018-05-18 Fri 18:30-21:30>
:PROPERTIES:
:ID:       VF7yRr1Bv2FhK4-bMrK4IWC9@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

River Bandits @ Snappers River Bandits @ Snappers

Follow on MiLB First Pitch  https //stza.co/+wSNT-$

Shop  https //stza.co/+wSNT-2x

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:River Bandits @ Snappers
END:VALARM
DTSTART:20180518T233000Z
DTEND:20180519T023000Z
UID:VF7yRr1Bv2FhK4-bMrK4IWC9@stanza.co
SUMMARY:River Bandits @ Snappers
DESCRIPTION:River Bandits @ Snappers\n\nFollow on MiLB First Pitch: https://stza.co/+wSNT-$\n\nShop: https://stza.co/+wSNT-2x\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144552Z
LAST-MODIFIED:20180213T144552Z
TRANSP:OPAQUE
END:VEVENT
* River Bandits @ Snappers
<2018-05-19 Sat 16:00-19:00>
:PROPERTIES:
:ID:       b4G6qmPRskIGV6t_TFj5MK9u@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

River Bandits @ Snappers River Bandits @ Snappers

Follow on MiLB First Pitch  https //stza.co/+wSNU-3R

Shop  https //stza.co/+wSNU-1n

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:River Bandits @ Snappers
END:VALARM
DTSTART:20180519T210000Z
DTEND:20180520T000000Z
UID:b4G6qmPRskIGV6t_TFj5MK9u@stanza.co
SUMMARY:River Bandits @ Snappers
DESCRIPTION:River Bandits @ Snappers\n\nFollow on MiLB First Pitch: https://stza.co/+wSNU-3R\n\nShop: https://stza.co/+wSNU-1n\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144552Z
LAST-MODIFIED:20180213T144552Z
TRANSP:OPAQUE
END:VEVENT
* River Bandits @ Snappers
<2018-05-20 Sun 14:00-17:00>
:PROPERTIES:
:ID:       4i-MzysEBjBCb7KCbW6gWTiy@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

River Bandits @ Snappers River Bandits @ Snappers

Follow on MiLB First Pitch  https //stza.co/+wSNV-l

Shop  https //stza.co/+wSNV-2i

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:River Bandits @ Snappers
END:VALARM
DTSTART:20180520T190000Z
DTEND:20180520T220000Z
UID:4i-MzysEBjBCb7KCbW6gWTiy@stanza.co
SUMMARY:River Bandits @ Snappers
DESCRIPTION:River Bandits @ Snappers\n\nFollow on MiLB First Pitch: https://stza.co/+wSNV-l\n\nShop: https://stza.co/+wSNV-2i\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144552Z
LAST-MODIFIED:20180213T144552Z
TRANSP:OPAQUE
END:VEVENT
* River Bandits vs. Timber Rattlers
<2018-05-21 Mon 18:35-21:35>
:PROPERTIES:
:ID:       e-ViHbBQSiQIuzGH9DS9H8Zr@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

River Bandits vs. Timber Rattlers River Bandits vs. Timber Rattlers

Follow on MiLB First Pitch  https //stza.co/+wxr1-16

Shop  https //stza.co/+wxr1-3i

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:River Bandits vs. Timber Rattlers
END:VALARM
DTSTART:20180521T233500Z
DTEND:20180522T023500Z
UID:e-ViHbBQSiQIuzGH9DS9H8Zr@stanza.co
SUMMARY:River Bandits vs. Timber Rattlers
DESCRIPTION:River Bandits vs. Timber Rattlers\n\nFollow on MiLB First Pitch: https://stza.co/+wxr1-16\n\nShop: https://stza.co/+wxr1-3i\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144552Z
LAST-MODIFIED:20180213T144552Z
TRANSP:OPAQUE
END:VEVENT
* River Bandits vs. Timber Rattlers
<2018-05-22 Tue 11:00-14:00>
:PROPERTIES:
:ID:       0g1baF8CbH51Lk9alwpXNUkt@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

River Bandits vs. Timber Rattlers River Bandits vs. Timber Rattlers

Follow on MiLB First Pitch  https //stza.co/+wxr4-2v

Shop  https //stza.co/+wxr4-3C

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:River Bandits vs. Timber Rattlers
END:VALARM
DTSTART:20180522T160000Z
DTEND:20180522T190000Z
UID:0g1baF8CbH51Lk9alwpXNUkt@stanza.co
SUMMARY:River Bandits vs. Timber Rattlers
DESCRIPTION:River Bandits vs. Timber Rattlers\n\nFollow on MiLB First Pitch: https://stza.co/+wxr4-2v\n\nShop: https://stza.co/+wxr4-3C\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144552Z
LAST-MODIFIED:20180213T144552Z
TRANSP:OPAQUE
END:VEVENT
* River Bandits vs. Timber Rattlers
<2018-05-23 Wed 18:35-21:35>
:PROPERTIES:
:ID:       uR78tLiab4GTP2MLHsageLo8@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

River Bandits vs. Timber Rattlers River Bandits vs. Timber Rattlers

Follow on MiLB First Pitch  https //stza.co/+wxr7-24

Shop  https //stza.co/+wxr7-3w

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:River Bandits vs. Timber Rattlers
END:VALARM
DTSTART:20180523T233500Z
DTEND:20180524T023500Z
UID:uR78tLiab4GTP2MLHsageLo8@stanza.co
SUMMARY:River Bandits vs. Timber Rattlers
DESCRIPTION:River Bandits vs. Timber Rattlers\n\nFollow on MiLB First Pitch: https://stza.co/+wxr7-24\n\nShop: https://stza.co/+wxr7-3w\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144552Z
LAST-MODIFIED:20180213T144552Z
TRANSP:OPAQUE
END:VEVENT
* River Bandits vs. Timber Rattlers
<2018-05-24 Thu 18:35-21:35>
:PROPERTIES:
:ID:       aXqcL69Je76oGJP8bzD4_Vw6@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

River Bandits vs. Timber Rattlers River Bandits vs. Timber Rattlers

Follow on MiLB First Pitch  https //stza.co/+wxr9-i

Shop  https //stza.co/+wxr9-1N

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:River Bandits vs. Timber Rattlers
END:VALARM
DTSTART:20180524T233500Z
DTEND:20180525T023500Z
UID:aXqcL69Je76oGJP8bzD4_Vw6@stanza.co
SUMMARY:River Bandits vs. Timber Rattlers
DESCRIPTION:River Bandits vs. Timber Rattlers\n\nFollow on MiLB First Pitch: https://stza.co/+wxr9-i\n\nShop: https://stza.co/+wxr9-1N\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144552Z
LAST-MODIFIED:20180213T144552Z
TRANSP:OPAQUE
END:VEVENT
* River Bandits vs. Chiefs
<2018-05-25 Fri 18:35-21:35>
:PROPERTIES:
:ID:       qnqLYfslLJv90-aqbuFRuWwb@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

River Bandits vs. Chiefs River Bandits vs. Chiefs

Follow on MiLB First Pitch  https //stza.co/+wxra-38

Shop  https //stza.co/+wxra-2b

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:River Bandits vs. Chiefs
END:VALARM
DTSTART:20180525T233500Z
DTEND:20180526T023500Z
UID:qnqLYfslLJv90-aqbuFRuWwb@stanza.co
SUMMARY:River Bandits vs. Chiefs
DESCRIPTION:River Bandits vs. Chiefs\n\nFollow on MiLB First Pitch: https://stza.co/+wxra-38\n\nShop: https://stza.co/+wxra-2b\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144552Z
LAST-MODIFIED:20180213T144552Z
TRANSP:OPAQUE
END:VEVENT
* River Bandits vs. Chiefs
<2018-05-26 Sat 18:35-21:35>
:PROPERTIES:
:ID:       oQKrV_0g5pH9Txcf6IldBz3P@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

River Bandits vs. Chiefs River Bandits vs. Chiefs

Follow on MiLB First Pitch  https //stza.co/+wxrc-1_

Shop  https //stza.co/+wxrc-25

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:River Bandits vs. Chiefs
END:VALARM
DTSTART:20180526T233500Z
DTEND:20180527T023500Z
UID:oQKrV_0g5pH9Txcf6IldBz3P@stanza.co
SUMMARY:River Bandits vs. Chiefs
DESCRIPTION:River Bandits vs. Chiefs\n\nFollow on MiLB First Pitch: https://stza.co/+wxrc-1_\n\nShop: https://stza.co/+wxrc-25\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144552Z
LAST-MODIFIED:20180213T144552Z
TRANSP:OPAQUE
END:VEVENT
* River Bandits vs. Chiefs
<2018-05-27 Sun 17:15-20:15>
:PROPERTIES:
:ID:       yMFnvlP-6fgxeIztaRewrEH1@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

River Bandits vs. Chiefs River Bandits vs. Chiefs

Follow on MiLB First Pitch  https //stza.co/+wxrf-Y

Shop  https //stza.co/+wxrf-2v

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:River Bandits vs. Chiefs
END:VALARM
DTSTART:20180527T221500Z
DTEND:20180528T011500Z
UID:yMFnvlP-6fgxeIztaRewrEH1@stanza.co
SUMMARY:River Bandits vs. Chiefs
DESCRIPTION:River Bandits vs. Chiefs\n\nFollow on MiLB First Pitch: https://stza.co/+wxrf-Y\n\nShop: https://stza.co/+wxrf-2v\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144552Z
LAST-MODIFIED:20180213T144552Z
TRANSP:OPAQUE
END:VEVENT
* River Bandits vs. Chiefs
<2018-05-28 Mon 17:15-20:15>
:PROPERTIES:
:ID:       kA8BO-zliB-wZkE6i0J1tEuK@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

River Bandits vs. Chiefs River Bandits vs. Chiefs

Follow on MiLB First Pitch  https //stza.co/+wxrg-P

Shop  https //stza.co/+wxrg-F

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:River Bandits vs. Chiefs
END:VALARM
DTSTART:20180528T221500Z
DTEND:20180529T011500Z
UID:kA8BO-zliB-wZkE6i0J1tEuK@stanza.co
SUMMARY:River Bandits vs. Chiefs
DESCRIPTION:River Bandits vs. Chiefs\n\nFollow on MiLB First Pitch: https://stza.co/+wxrg-P\n\nShop: https://stza.co/+wxrg-F\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144552Z
LAST-MODIFIED:20180213T144552Z
TRANSP:OPAQUE
END:VEVENT
* River Bandits @ LumberKings
<2018-05-29 Tue 18:30-21:30>
:PROPERTIES:
:ID:       SUZQ8hjaafdQzRsqLRO3cZyA@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

River Bandits @ LumberKings River Bandits @ LumberKings

Follow on MiLB First Pitch  https //stza.co/+vNg7-y

Shop  https //stza.co/+vNg7-1

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:River Bandits @ LumberKings
END:VALARM
DTSTART:20180529T233000Z
DTEND:20180530T023000Z
UID:SUZQ8hjaafdQzRsqLRO3cZyA@stanza.co
SUMMARY:River Bandits @ LumberKings
DESCRIPTION:River Bandits @ LumberKings\n\nFollow on MiLB First Pitch: https://stza.co/+vNg7-y\n\nShop: https://stza.co/+vNg7-1\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144552Z
LAST-MODIFIED:20180213T144552Z
TRANSP:OPAQUE
END:VEVENT
* River Bandits @ LumberKings
<2018-05-30 Wed 18:30-21:30>
:PROPERTIES:
:ID:       P3SyC-0VVPioAuhqiVkkoF90@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

River Bandits @ LumberKings River Bandits @ LumberKings

Follow on MiLB First Pitch  https //stza.co/+vNg8-5

Shop  https //stza.co/+vNg8-o

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:River Bandits @ LumberKings
END:VALARM
DTSTART:20180530T233000Z
DTEND:20180531T023000Z
UID:P3SyC-0VVPioAuhqiVkkoF90@stanza.co
SUMMARY:River Bandits @ LumberKings
DESCRIPTION:River Bandits @ LumberKings\n\nFollow on MiLB First Pitch: https://stza.co/+vNg8-5\n\nShop: https://stza.co/+vNg8-o\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144552Z
LAST-MODIFIED:20180213T144552Z
TRANSP:OPAQUE
END:VEVENT
* River Bandits @ LumberKings
<2018-05-31 Thu 18:30-21:30>
:PROPERTIES:
:ID:       MR2WhSP5TQJcWyNfa5mcey0x@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

River Bandits @ LumberKings River Bandits @ LumberKings

Follow on MiLB First Pitch  https //stza.co/+vNg9-1Q

Shop  https //stza.co/+vNg9-1q

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:River Bandits @ LumberKings
END:VALARM
DTSTART:20180531T233000Z
DTEND:20180601T023000Z
UID:MR2WhSP5TQJcWyNfa5mcey0x@stanza.co
SUMMARY:River Bandits @ LumberKings
DESCRIPTION:River Bandits @ LumberKings\n\nFollow on MiLB First Pitch: https://stza.co/+vNg9-1Q\n\nShop: https://stza.co/+vNg9-1q\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144552Z
LAST-MODIFIED:20180213T144552Z
TRANSP:OPAQUE
END:VEVENT
* River Bandits vs. Snappers
<2018-06-01 Fri 18:35-21:35>
:PROPERTIES:
:ID:       DnGo51Fqbg3XITRvxl5GCCW5@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

River Bandits vs. Snappers River Bandits vs. Snappers

Follow on MiLB First Pitch  https //stza.co/+wxri-2H

Shop  https //stza.co/+wxri-1_

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:River Bandits vs. Snappers
END:VALARM
DTSTART:20180601T233500Z
DTEND:20180602T023500Z
UID:DnGo51Fqbg3XITRvxl5GCCW5@stanza.co
SUMMARY:River Bandits vs. Snappers
DESCRIPTION:River Bandits vs. Snappers\n\nFollow on MiLB First Pitch: https://stza.co/+wxri-2H\n\nShop: https://stza.co/+wxri-1_\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144552Z
LAST-MODIFIED:20180213T144552Z
TRANSP:OPAQUE
END:VEVENT
* River Bandits vs. Snappers
<2018-06-02 Sat 18:35-21:35>
:PROPERTIES:
:ID:       B5Fn2WzDjMbUYP14n6nl6o65@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

River Bandits vs. Snappers River Bandits vs. Snappers

Follow on MiLB First Pitch  https //stza.co/+wxrm-3H

Shop  https //stza.co/+wxrm-3a

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:River Bandits vs. Snappers
END:VALARM
DTSTART:20180602T233500Z
DTEND:20180603T023500Z
UID:B5Fn2WzDjMbUYP14n6nl6o65@stanza.co
SUMMARY:River Bandits vs. Snappers
DESCRIPTION:River Bandits vs. Snappers\n\nFollow on MiLB First Pitch: https://stza.co/+wxrm-3H\n\nShop: https://stza.co/+wxrm-3a\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144552Z
LAST-MODIFIED:20180213T144552Z
TRANSP:OPAQUE
END:VEVENT
* River Bandits vs. Snappers
<2018-06-03 Sun 13:15-16:15>
:PROPERTIES:
:ID:       IdEEALEQeVT7LoLHmH5SP1mw@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

River Bandits vs. Snappers River Bandits vs. Snappers

Follow on MiLB First Pitch  https //stza.co/+wxrp-2E

Shop  https //stza.co/+wxrp-3F

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:River Bandits vs. Snappers
END:VALARM
DTSTART:20180603T181500Z
DTEND:20180603T211500Z
UID:IdEEALEQeVT7LoLHmH5SP1mw@stanza.co
SUMMARY:River Bandits vs. Snappers
DESCRIPTION:River Bandits vs. Snappers\n\nFollow on MiLB First Pitch: https://stza.co/+wxrp-2E\n\nShop: https://stza.co/+wxrp-3F\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144552Z
LAST-MODIFIED:20180213T144552Z
TRANSP:OPAQUE
END:VEVENT
* River Bandits @ Timber Rattlers
<2018-06-05 Tue 19:05-22:05>
:PROPERTIES:
:ID:       Tv-33BjqsYycybYLtPjVNkNB@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

River Bandits @ Timber Rattlers River Bandits @ Timber Rattlers

Follow on MiLB First Pitch  https //stza.co/+vNiN-3X

Shop  https //stza.co/+vNiN-1D

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:River Bandits @ Timber Rattlers
END:VALARM
DTSTART:20180606T000500Z
DTEND:20180606T030500Z
UID:Tv-33BjqsYycybYLtPjVNkNB@stanza.co
SUMMARY:River Bandits @ Timber Rattlers
DESCRIPTION:River Bandits @ Timber Rattlers\n\nFollow on MiLB First Pitch: https://stza.co/+vNiN-3X\n\nShop: https://stza.co/+vNiN-1D\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144552Z
LAST-MODIFIED:20180213T144552Z
TRANSP:OPAQUE
END:VEVENT
* River Bandits @ Timber Rattlers
<2018-06-06 Wed 19:05-22:05>
:PROPERTIES:
:ID:       k4fRB_LSVe7JGLwUwt3zsyjW@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

River Bandits @ Timber Rattlers River Bandits @ Timber Rattlers

Follow on MiLB First Pitch  https //stza.co/+vNiO-1l

Shop  https //stza.co/+vNiO-2H

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:River Bandits @ Timber Rattlers
END:VALARM
DTSTART:20180607T000500Z
DTEND:20180607T030500Z
UID:k4fRB_LSVe7JGLwUwt3zsyjW@stanza.co
SUMMARY:River Bandits @ Timber Rattlers
DESCRIPTION:River Bandits @ Timber Rattlers\n\nFollow on MiLB First Pitch: https://stza.co/+vNiO-1l\n\nShop: https://stza.co/+vNiO-2H\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144552Z
LAST-MODIFIED:20180213T144552Z
TRANSP:OPAQUE
END:VEVENT
* River Bandits @ Timber Rattlers
<2018-06-07 Thu 19:05-22:05>
:PROPERTIES:
:ID:       0DIuMWiJUVC6s8yy1sCHIIwR@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

River Bandits @ Timber Rattlers River Bandits @ Timber Rattlers

Follow on MiLB First Pitch  https //stza.co/+vNiP-19

Shop  https //stza.co/+vNiP-33

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:River Bandits @ Timber Rattlers
END:VALARM
DTSTART:20180608T000500Z
DTEND:20180608T030500Z
UID:0DIuMWiJUVC6s8yy1sCHIIwR@stanza.co
SUMMARY:River Bandits @ Timber Rattlers
DESCRIPTION:River Bandits @ Timber Rattlers\n\nFollow on MiLB First Pitch: https://stza.co/+vNiP-19\n\nShop: https://stza.co/+vNiP-33\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144552Z
LAST-MODIFIED:20180213T144552Z
TRANSP:OPAQUE
END:VEVENT
* River Bandits @ Chiefs
<2018-06-08 Fri 19:00-22:00>
:PROPERTIES:
:ID:       jxv6MOsAET75M2AfY6ZLfw58@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

River Bandits @ Chiefs River Bandits @ Chiefs

Follow on MiLB First Pitch  https //stza.co/+xAIB-3i

Shop  https //stza.co/+xAIB-_

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:River Bandits @ Chiefs
END:VALARM
DTSTART:20180609T000000Z
DTEND:20180609T030000Z
UID:jxv6MOsAET75M2AfY6ZLfw58@stanza.co
SUMMARY:River Bandits @ Chiefs
DESCRIPTION:River Bandits @ Chiefs\n\nFollow on MiLB First Pitch: https://stza.co/+xAIB-3i\n\nShop: https://stza.co/+xAIB-_\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144552Z
LAST-MODIFIED:20180213T144552Z
TRANSP:OPAQUE
END:VEVENT
* River Bandits @ Chiefs
<2018-06-09 Sat 18:30-21:30>
:PROPERTIES:
:ID:       Q8qfxUeGZGMea4u_q7HOlMdb@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

River Bandits @ Chiefs River Bandits @ Chiefs

Follow on MiLB First Pitch  https //stza.co/+xAIC-1_

Shop  https //stza.co/+xAIC-3d

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:River Bandits @ Chiefs
END:VALARM
DTSTART:20180609T233000Z
DTEND:20180610T023000Z
UID:Q8qfxUeGZGMea4u_q7HOlMdb@stanza.co
SUMMARY:River Bandits @ Chiefs
DESCRIPTION:River Bandits @ Chiefs\n\nFollow on MiLB First Pitch: https://stza.co/+xAIC-1_\n\nShop: https://stza.co/+xAIC-3d\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144552Z
LAST-MODIFIED:20180213T144552Z
TRANSP:OPAQUE
END:VEVENT
* River Bandits @ Chiefs
<2018-06-10 Sun 14:00-17:00>
:PROPERTIES:
:ID:       xTYocnUPXCnm4JOgAi760g6C@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

River Bandits @ Chiefs River Bandits @ Chiefs

Follow on MiLB First Pitch  https //stza.co/+xAID-23

Shop  https //stza.co/+xAID-3V

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:River Bandits @ Chiefs
END:VALARM
DTSTART:20180610T190000Z
DTEND:20180610T220000Z
UID:xTYocnUPXCnm4JOgAi760g6C@stanza.co
SUMMARY:River Bandits @ Chiefs
DESCRIPTION:River Bandits @ Chiefs\n\nFollow on MiLB First Pitch: https://stza.co/+xAID-23\n\nShop: https://stza.co/+xAID-3V\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144552Z
LAST-MODIFIED:20180213T144552Z
TRANSP:OPAQUE
END:VEVENT
* River Bandits @ Chiefs
<2018-06-11 Mon 12:00-15:00>
:PROPERTIES:
:ID:       WKck2P5afxYsdAN9yfuOs1SX@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

River Bandits @ Chiefs River Bandits @ Chiefs

Follow on MiLB First Pitch  https //stza.co/+xAIE-3q

Shop  https //stza.co/+xAIE-3n

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:River Bandits @ Chiefs
END:VALARM
DTSTART:20180611T170000Z
DTEND:20180611T200000Z
UID:WKck2P5afxYsdAN9yfuOs1SX@stanza.co
SUMMARY:River Bandits @ Chiefs
DESCRIPTION:River Bandits @ Chiefs\n\nFollow on MiLB First Pitch: https://stza.co/+xAIE-3q\n\nShop: https://stza.co/+xAIE-3n\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144552Z
LAST-MODIFIED:20180213T144552Z
TRANSP:OPAQUE
END:VEVENT
* River Bandits vs. LumberKings
<2018-06-12 Tue 18:35-21:35>
:PROPERTIES:
:ID:       DtxrrXqKmX0ojUsfAM6WFTHG@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

River Bandits vs. LumberKings River Bandits vs. LumberKings

Follow on MiLB First Pitch  https //stza.co/+wxrq-2

Shop  https //stza.co/+wxrq-3Q

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:River Bandits vs. LumberKings
END:VALARM
DTSTART:20180612T233500Z
DTEND:20180613T023500Z
UID:DtxrrXqKmX0ojUsfAM6WFTHG@stanza.co
SUMMARY:River Bandits vs. LumberKings
DESCRIPTION:River Bandits vs. LumberKings\n\nFollow on MiLB First Pitch: https://stza.co/+wxrq-2\n\nShop: https://stza.co/+wxrq-3Q\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144552Z
LAST-MODIFIED:20180213T144552Z
TRANSP:OPAQUE
END:VEVENT
* River Bandits vs. LumberKings
<2018-06-13 Wed 18:35-21:35>
:PROPERTIES:
:ID:       JLUXj2JSHxEramnunNnGM31r@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

River Bandits vs. LumberKings River Bandits vs. LumberKings

Follow on MiLB First Pitch  https //stza.co/+wxrs-36

Shop  https //stza.co/+wxrs-3n

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:River Bandits vs. LumberKings
END:VALARM
DTSTART:20180613T233500Z
DTEND:20180614T023500Z
UID:JLUXj2JSHxEramnunNnGM31r@stanza.co
SUMMARY:River Bandits vs. LumberKings
DESCRIPTION:River Bandits vs. LumberKings\n\nFollow on MiLB First Pitch: https://stza.co/+wxrs-36\n\nShop: https://stza.co/+wxrs-3n\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144552Z
LAST-MODIFIED:20180213T144552Z
TRANSP:OPAQUE
END:VEVENT
* River Bandits vs. LumberKings
<2018-06-14 Thu 18:35-21:35>
:PROPERTIES:
:ID:       ITKcQOObTitZ0De9mRT_QEp4@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

River Bandits vs. LumberKings River Bandits vs. LumberKings

Follow on MiLB First Pitch  https //stza.co/+wxru-1A

Shop  https //stza.co/+wxru-2O

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:River Bandits vs. LumberKings
END:VALARM
DTSTART:20180614T233500Z
DTEND:20180615T023500Z
UID:ITKcQOObTitZ0De9mRT_QEp4@stanza.co
SUMMARY:River Bandits vs. LumberKings
DESCRIPTION:River Bandits vs. LumberKings\n\nFollow on MiLB First Pitch: https://stza.co/+wxru-1A\n\nShop: https://stza.co/+wxru-2O\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144552Z
LAST-MODIFIED:20180213T144552Z
TRANSP:OPAQUE
END:VEVENT
* River Bandits vs. Bees
<2018-06-15 Fri 18:35-21:35>
:PROPERTIES:
:ID:       tvJXbUDGh5jEQwDshyqNJ2Pk@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

River Bandits vs. Bees River Bandits vs. Bees

Follow on MiLB First Pitch  https //stza.co/+wxrw-1n

Shop  https //stza.co/+wxrw-1X

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:River Bandits vs. Bees
END:VALARM
DTSTART:20180615T233500Z
DTEND:20180616T023500Z
UID:tvJXbUDGh5jEQwDshyqNJ2Pk@stanza.co
SUMMARY:River Bandits vs. Bees
DESCRIPTION:River Bandits vs. Bees\n\nFollow on MiLB First Pitch: https://stza.co/+wxrw-1n\n\nShop: https://stza.co/+wxrw-1X\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144552Z
LAST-MODIFIED:20180213T144552Z
TRANSP:OPAQUE
END:VEVENT
* River Bandits vs. Bees
<2018-06-16 Sat 18:35-21:35>
:PROPERTIES:
:ID:       heh33PsruyCo8ap7lXFr2iO1@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

River Bandits vs. Bees River Bandits vs. Bees

Follow on MiLB First Pitch  https //stza.co/+wxrz-3P

Shop  https //stza.co/+wxrz-2_

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:River Bandits vs. Bees
END:VALARM
DTSTART:20180616T233500Z
DTEND:20180617T023500Z
UID:heh33PsruyCo8ap7lXFr2iO1@stanza.co
SUMMARY:River Bandits vs. Bees
DESCRIPTION:River Bandits vs. Bees\n\nFollow on MiLB First Pitch: https://stza.co/+wxrz-3P\n\nShop: https://stza.co/+wxrz-2_\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144552Z
LAST-MODIFIED:20180213T144552Z
TRANSP:OPAQUE
END:VEVENT
* River Bandits vs. Bees
<2018-06-17 Sun 13:15-16:15>
:PROPERTIES:
:ID:       1bUI1XbWwemnUpTuMml5MorM@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

River Bandits vs. Bees River Bandits vs. Bees

Follow on MiLB First Pitch  https //stza.co/+wxrB-1H

Shop  https //stza.co/+wxrB-2t

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:River Bandits vs. Bees
END:VALARM
DTSTART:20180617T181500Z
DTEND:20180617T211500Z
UID:1bUI1XbWwemnUpTuMml5MorM@stanza.co
SUMMARY:River Bandits vs. Bees
DESCRIPTION:River Bandits vs. Bees\n\nFollow on MiLB First Pitch: https://stza.co/+wxrB-1H\n\nShop: https://stza.co/+wxrB-2t\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144552Z
LAST-MODIFIED:20180213T144552Z
TRANSP:OPAQUE
END:VEVENT
* River Bandits vs. Snappers
<2018-06-21 Thu 18:35-21:35>
:PROPERTIES:
:ID:       PYCJrxDJfPzIEy-uQ1TbHWhP@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

River Bandits vs. Snappers River Bandits vs. Snappers

Follow on MiLB First Pitch  https //stza.co/+wxrC-2Q

Shop  https //stza.co/+wxrC-1p

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:River Bandits vs. Snappers
END:VALARM
DTSTART:20180621T233500Z
DTEND:20180622T023500Z
UID:PYCJrxDJfPzIEy-uQ1TbHWhP@stanza.co
SUMMARY:River Bandits vs. Snappers
DESCRIPTION:River Bandits vs. Snappers\n\nFollow on MiLB First Pitch: https://stza.co/+wxrC-2Q\n\nShop: https://stza.co/+wxrC-1p\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144552Z
LAST-MODIFIED:20180213T144552Z
TRANSP:OPAQUE
END:VEVENT
* River Bandits vs. Snappers
<2018-06-22 Fri 18:35-21:35>
:PROPERTIES:
:ID:       tiTzOMxX6YUVXr936wBvPlWM@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

River Bandits vs. Snappers River Bandits vs. Snappers

Follow on MiLB First Pitch  https //stza.co/+wxrE-i

Shop  https //stza.co/+wxrE-1f

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:River Bandits vs. Snappers
END:VALARM
DTSTART:20180622T233500Z
DTEND:20180623T023500Z
UID:tiTzOMxX6YUVXr936wBvPlWM@stanza.co
SUMMARY:River Bandits vs. Snappers
DESCRIPTION:River Bandits vs. Snappers\n\nFollow on MiLB First Pitch: https://stza.co/+wxrE-i\n\nShop: https://stza.co/+wxrE-1f\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144552Z
LAST-MODIFIED:20180213T144552Z
TRANSP:OPAQUE
END:VEVENT
* River Bandits vs. Snappers
<2018-06-23 Sat 18:35-21:35>
:PROPERTIES:
:ID:       FakKDFG1Z3zDrzfEIPdwCngk@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

River Bandits vs. Snappers River Bandits vs. Snappers

Follow on MiLB First Pitch  https //stza.co/+wxrG-r

Shop  https //stza.co/+wxrG-3G

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:River Bandits vs. Snappers
END:VALARM
DTSTART:20180623T233500Z
DTEND:20180624T023500Z
UID:FakKDFG1Z3zDrzfEIPdwCngk@stanza.co
SUMMARY:River Bandits vs. Snappers
DESCRIPTION:River Bandits vs. Snappers\n\nFollow on MiLB First Pitch: https://stza.co/+wxrG-r\n\nShop: https://stza.co/+wxrG-3G\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144552Z
LAST-MODIFIED:20180213T144552Z
TRANSP:OPAQUE
END:VEVENT
* River Bandits vs. Snappers
<2018-06-24 Sun 17:15-20:15>
:PROPERTIES:
:ID:       8GUMLjTE7HIX_bAEcC4F7bv4@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

River Bandits vs. Snappers River Bandits vs. Snappers

Follow on MiLB First Pitch  https //stza.co/+wxrI-24

Shop  https //stza.co/+wxrI-5

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:River Bandits vs. Snappers
END:VALARM
DTSTART:20180624T221500Z
DTEND:20180625T011500Z
UID:8GUMLjTE7HIX_bAEcC4F7bv4@stanza.co
SUMMARY:River Bandits vs. Snappers
DESCRIPTION:River Bandits vs. Snappers\n\nFollow on MiLB First Pitch: https://stza.co/+wxrI-24\n\nShop: https://stza.co/+wxrI-5\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144552Z
LAST-MODIFIED:20180213T144552Z
TRANSP:OPAQUE
END:VEVENT
* River Bandits vs. Timber Rattlers
<2018-06-25 Mon 18:35-21:35>
:PROPERTIES:
:ID:       vo-6dRw8VnhuQYQh7bwdSHVG@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

River Bandits vs. Timber Rattlers River Bandits vs. Timber Rattlers

Follow on MiLB First Pitch  https //stza.co/+wxrL-1X

Shop  https //stza.co/+wxrL-C

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:River Bandits vs. Timber Rattlers
END:VALARM
DTSTART:20180625T233500Z
DTEND:20180626T023500Z
UID:vo-6dRw8VnhuQYQh7bwdSHVG@stanza.co
SUMMARY:River Bandits vs. Timber Rattlers
DESCRIPTION:River Bandits vs. Timber Rattlers\n\nFollow on MiLB First Pitch: https://stza.co/+wxrL-1X\n\nShop: https://stza.co/+wxrL-C\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144552Z
LAST-MODIFIED:20180213T144552Z
TRANSP:OPAQUE
END:VEVENT
* River Bandits vs. Timber Rattlers
<2018-06-26 Tue 18:35-21:35>
:PROPERTIES:
:ID:       KJkwyVMfvyMnyX0f2ZCjSnzB@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

River Bandits vs. Timber Rattlers River Bandits vs. Timber Rattlers

Follow on MiLB First Pitch  https //stza.co/+wxrN-3c

Shop  https //stza.co/+wxrN-1o

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:River Bandits vs. Timber Rattlers
END:VALARM
DTSTART:20180626T233500Z
DTEND:20180627T023500Z
UID:KJkwyVMfvyMnyX0f2ZCjSnzB@stanza.co
SUMMARY:River Bandits vs. Timber Rattlers
DESCRIPTION:River Bandits vs. Timber Rattlers\n\nFollow on MiLB First Pitch: https://stza.co/+wxrN-3c\n\nShop: https://stza.co/+wxrN-1o\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144552Z
LAST-MODIFIED:20180213T144552Z
TRANSP:OPAQUE
END:VEVENT
* River Bandits vs. Timber Rattlers
<2018-06-27 Wed 18:35-21:35>
:PROPERTIES:
:ID:       xWT2Ca2ke1M3GJI1R_dSyiRZ@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

River Bandits vs. Timber Rattlers River Bandits vs. Timber Rattlers

Follow on MiLB First Pitch  https //stza.co/+wxrP-1E

Shop  https //stza.co/+wxrP-21

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:River Bandits vs. Timber Rattlers
END:VALARM
DTSTART:20180627T233500Z
DTEND:20180628T023500Z
UID:xWT2Ca2ke1M3GJI1R_dSyiRZ@stanza.co
SUMMARY:River Bandits vs. Timber Rattlers
DESCRIPTION:River Bandits vs. Timber Rattlers\n\nFollow on MiLB First Pitch: https://stza.co/+wxrP-1E\n\nShop: https://stza.co/+wxrP-21\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144552Z
LAST-MODIFIED:20180213T144552Z
TRANSP:OPAQUE
END:VEVENT
* River Bandits @ Cougars
<2018-06-28 Thu 18:30-21:30>
:PROPERTIES:
:ID:       JYkRo2Ywm2U5-6qiHe9DyH90@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

River Bandits @ Cougars River Bandits @ Cougars

Follow on MiLB First Pitch  https //stza.co/+xAIt-2F

Shop  https //stza.co/+xAIt-2l

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:River Bandits @ Cougars
END:VALARM
DTSTART:20180628T233000Z
DTEND:20180629T023000Z
UID:JYkRo2Ywm2U5-6qiHe9DyH90@stanza.co
SUMMARY:River Bandits @ Cougars
DESCRIPTION:River Bandits @ Cougars\n\nFollow on MiLB First Pitch: https://stza.co/+xAIt-2F\n\nShop: https://stza.co/+xAIt-2l\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144552Z
LAST-MODIFIED:20180213T144552Z
TRANSP:OPAQUE
END:VEVENT
* River Bandits @ Cougars
<2018-06-29 Fri 18:30-21:30>
:PROPERTIES:
:ID:       jxiyCwbbOmt9ecqxWZTKvVkl@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

River Bandits @ Cougars River Bandits @ Cougars

Follow on MiLB First Pitch  https //stza.co/+xAIv-3g

Shop  https //stza.co/+xAIv-1$

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:River Bandits @ Cougars
END:VALARM
DTSTART:20180629T233000Z
DTEND:20180630T023000Z
UID:jxiyCwbbOmt9ecqxWZTKvVkl@stanza.co
SUMMARY:River Bandits @ Cougars
DESCRIPTION:River Bandits @ Cougars\n\nFollow on MiLB First Pitch: https://stza.co/+xAIv-3g\n\nShop: https://stza.co/+xAIv-1$\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144552Z
LAST-MODIFIED:20180213T144552Z
TRANSP:OPAQUE
END:VEVENT
* River Bandits @ Cougars
<2018-06-30 Sat 18:30-21:30>
:PROPERTIES:
:ID:       v_XiE-8I8xNXjdd_yz6ghgSb@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

River Bandits @ Cougars River Bandits @ Cougars

Follow on MiLB First Pitch  https //stza.co/+xAIw-11

Shop  https //stza.co/+xAIw-3j

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:River Bandits @ Cougars
END:VALARM
DTSTART:20180630T233000Z
DTEND:20180701T023000Z
UID:v_XiE-8I8xNXjdd_yz6ghgSb@stanza.co
SUMMARY:River Bandits @ Cougars
DESCRIPTION:River Bandits @ Cougars\n\nFollow on MiLB First Pitch: https://stza.co/+xAIw-11\n\nShop: https://stza.co/+xAIw-3j\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144552Z
LAST-MODIFIED:20180213T144552Z
TRANSP:OPAQUE
END:VEVENT
* River Bandits @ Cougars
<2018-07-01 Sun 13:00-16:00>
:PROPERTIES:
:ID:       NkGdv5mleHGZM5yU3aAjt1Xi@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

River Bandits @ Cougars River Bandits @ Cougars

Follow on MiLB First Pitch  https //stza.co/+xAIA-2K

Shop  https //stza.co/+xAIA-1A

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:River Bandits @ Cougars
END:VALARM
DTSTART:20180701T180000Z
DTEND:20180701T210000Z
UID:NkGdv5mleHGZM5yU3aAjt1Xi@stanza.co
SUMMARY:River Bandits @ Cougars
DESCRIPTION:River Bandits @ Cougars\n\nFollow on MiLB First Pitch: https://stza.co/+xAIA-2K\n\nShop: https://stza.co/+xAIA-1A\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144552Z
LAST-MODIFIED:20180213T144552Z
TRANSP:OPAQUE
END:VEVENT
* River Bandits @ Snappers
<2018-07-02 Mon 19:00-22:00>
:PROPERTIES:
:ID:       BiLea7Pvwm8PEX6KypUkz1GP@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

River Bandits @ Snappers River Bandits @ Snappers

Follow on MiLB First Pitch  https //stza.co/+wSNW-3o

Shop  https //stza.co/+wSNW-2R

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:River Bandits @ Snappers
END:VALARM
DTSTART:20180703T000000Z
DTEND:20180703T030000Z
UID:BiLea7Pvwm8PEX6KypUkz1GP@stanza.co
SUMMARY:River Bandits @ Snappers
DESCRIPTION:River Bandits @ Snappers\n\nFollow on MiLB First Pitch: https://stza.co/+wSNW-3o\n\nShop: https://stza.co/+wSNW-2R\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144552Z
LAST-MODIFIED:20180213T144552Z
TRANSP:OPAQUE
END:VEVENT
* River Bandits @ Snappers
<2018-07-03 Tue 19:00-22:00>
:PROPERTIES:
:ID:       rfKWVc5lKFoPRBPYqN_bKB1i@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

River Bandits @ Snappers River Bandits @ Snappers

Follow on MiLB First Pitch  https //stza.co/+wSNX-3S

Shop  https //stza.co/+wSNX-3D

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:River Bandits @ Snappers
END:VALARM
DTSTART:20180704T000000Z
DTEND:20180704T030000Z
UID:rfKWVc5lKFoPRBPYqN_bKB1i@stanza.co
SUMMARY:River Bandits @ Snappers
DESCRIPTION:River Bandits @ Snappers\n\nFollow on MiLB First Pitch: https://stza.co/+wSNX-3S\n\nShop: https://stza.co/+wSNX-3D\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144552Z
LAST-MODIFIED:20180213T144552Z
TRANSP:OPAQUE
END:VEVENT
* River Bandits vs. Snappers
<2018-07-04 Wed 18:35-21:35>
:PROPERTIES:
:ID:       1OsehxtnD0mml8Q3xPEaTP-6@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

River Bandits vs. Snappers River Bandits vs. Snappers

Follow on MiLB First Pitch  https //stza.co/+wxrR-1v

Shop  https //stza.co/+wxrR-2p

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:River Bandits vs. Snappers
END:VALARM
DTSTART:20180704T233500Z
DTEND:20180705T023500Z
UID:1OsehxtnD0mml8Q3xPEaTP-6@stanza.co
SUMMARY:River Bandits vs. Snappers
DESCRIPTION:River Bandits vs. Snappers\n\nFollow on MiLB First Pitch: https://stza.co/+wxrR-1v\n\nShop: https://stza.co/+wxrR-2p\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144552Z
LAST-MODIFIED:20180213T144552Z
TRANSP:OPAQUE
END:VEVENT
* River Bandits vs. Snappers
<2018-07-05 Thu 18:35-21:35>
:PROPERTIES:
:ID:       kOryrJKNpovmmxFMHazdHXHB@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

River Bandits vs. Snappers River Bandits vs. Snappers

Follow on MiLB First Pitch  https //stza.co/+wxrT-1n

Shop  https //stza.co/+wxrT-a

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:River Bandits vs. Snappers
END:VALARM
DTSTART:20180705T233500Z
DTEND:20180706T023500Z
UID:kOryrJKNpovmmxFMHazdHXHB@stanza.co
SUMMARY:River Bandits vs. Snappers
DESCRIPTION:River Bandits vs. Snappers\n\nFollow on MiLB First Pitch: https://stza.co/+wxrT-1n\n\nShop: https://stza.co/+wxrT-a\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144552Z
LAST-MODIFIED:20180213T144552Z
TRANSP:OPAQUE
END:VEVENT
* River Bandits vs. Bees
<2018-07-06 Fri 18:35-21:35>
:PROPERTIES:
:ID:       Jb4ZA0LekQJj8PcKQ9y7dXBI@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

River Bandits vs. Bees River Bandits vs. Bees

Follow on MiLB First Pitch  https //stza.co/+wxrV-28

Shop  https //stza.co/+wxrV-w

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:River Bandits vs. Bees
END:VALARM
DTSTART:20180706T233500Z
DTEND:20180707T023500Z
UID:Jb4ZA0LekQJj8PcKQ9y7dXBI@stanza.co
SUMMARY:River Bandits vs. Bees
DESCRIPTION:River Bandits vs. Bees\n\nFollow on MiLB First Pitch: https://stza.co/+wxrV-28\n\nShop: https://stza.co/+wxrV-w\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144552Z
LAST-MODIFIED:20180213T144552Z
TRANSP:OPAQUE
END:VEVENT
* River Bandits vs. Bees
<2018-07-07 Sat 18:35-21:35>
:PROPERTIES:
:ID:       _fQgjpWICgobhD5k4h-nrmLW@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

River Bandits vs. Bees River Bandits vs. Bees

Follow on MiLB First Pitch  https //stza.co/+wxrX-2m

Shop  https //stza.co/+wxrX-2v

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:River Bandits vs. Bees
END:VALARM
DTSTART:20180707T233500Z
DTEND:20180708T023500Z
UID:_fQgjpWICgobhD5k4h-nrmLW@stanza.co
SUMMARY:River Bandits vs. Bees
DESCRIPTION:River Bandits vs. Bees\n\nFollow on MiLB First Pitch: https://stza.co/+wxrX-2m\n\nShop: https://stza.co/+wxrX-2v\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144552Z
LAST-MODIFIED:20180213T144552Z
TRANSP:OPAQUE
END:VEVENT
* River Bandits vs. Bees
<2018-07-08 Sun 17:15-20:15>
:PROPERTIES:
:ID:       LJ-apsp53SZw4qS7YUpzt8a7@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

River Bandits vs. Bees River Bandits vs. Bees

Follow on MiLB First Pitch  https //stza.co/+wxrZ-3c

Shop  https //stza.co/+wxrZ-1

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:River Bandits vs. Bees
END:VALARM
DTSTART:20180708T221500Z
DTEND:20180709T011500Z
UID:LJ-apsp53SZw4qS7YUpzt8a7@stanza.co
SUMMARY:River Bandits vs. Bees
DESCRIPTION:River Bandits vs. Bees\n\nFollow on MiLB First Pitch: https://stza.co/+wxrZ-3c\n\nShop: https://stza.co/+wxrZ-1\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144552Z
LAST-MODIFIED:20180213T144552Z
TRANSP:OPAQUE
END:VEVENT
* River Bandits vs. Bees
<2018-07-09 Mon 18:35-21:35>
:PROPERTIES:
:ID:       bKG20WVde4TtB4x5xdN0z8TQ@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

River Bandits vs. Bees River Bandits vs. Bees

Follow on MiLB First Pitch  https //stza.co/+wxr_-29

Shop  https //stza.co/+wxr_-2z

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:River Bandits vs. Bees
END:VALARM
DTSTART:20180709T233500Z
DTEND:20180710T023500Z
UID:bKG20WVde4TtB4x5xdN0z8TQ@stanza.co
SUMMARY:River Bandits vs. Bees
DESCRIPTION:River Bandits vs. Bees\n\nFollow on MiLB First Pitch: https://stza.co/+wxr_-29\n\nShop: https://stza.co/+wxr_-2z\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144552Z
LAST-MODIFIED:20180213T144552Z
TRANSP:OPAQUE
END:VEVENT
* River Bandits @ Dragons
<2018-07-11 Wed 18:00-21:00>
:PROPERTIES:
:ID:       nac9sE3huC1hy8Fjs5QxQgEI@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

River Bandits @ Dragons River Bandits @ Dragons

Follow on MiLB First Pitch  https //stza.co/+vNgd-3Z

Shop  https //stza.co/+vNgd-1I

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:River Bandits @ Dragons
END:VALARM
DTSTART:20180711T230000Z
DTEND:20180712T020000Z
UID:nac9sE3huC1hy8Fjs5QxQgEI@stanza.co
SUMMARY:River Bandits @ Dragons
DESCRIPTION:River Bandits @ Dragons\n\nFollow on MiLB First Pitch: https://stza.co/+vNgd-3Z\n\nShop: https://stza.co/+vNgd-1I\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144552Z
LAST-MODIFIED:20180213T144552Z
TRANSP:OPAQUE
END:VEVENT
* River Bandits @ Dragons
<2018-07-12 Thu 18:00-21:00>
:PROPERTIES:
:ID:       OWqleUaOUFN2F2uPRJZTfLx1@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

River Bandits @ Dragons River Bandits @ Dragons

Follow on MiLB First Pitch  https //stza.co/+vNge-b

Shop  https //stza.co/+vNge-31

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:River Bandits @ Dragons
END:VALARM
DTSTART:20180712T230000Z
DTEND:20180713T020000Z
UID:OWqleUaOUFN2F2uPRJZTfLx1@stanza.co
SUMMARY:River Bandits @ Dragons
DESCRIPTION:River Bandits @ Dragons\n\nFollow on MiLB First Pitch: https://stza.co/+vNge-b\n\nShop: https://stza.co/+vNge-31\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144552Z
LAST-MODIFIED:20180213T144552Z
TRANSP:OPAQUE
END:VEVENT
* River Bandits @ Dragons
<2018-07-13 Fri 18:00-21:00>
:PROPERTIES:
:ID:       Bu9bdUQrSC79IAaTA8BV2Fe0@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

River Bandits @ Dragons River Bandits @ Dragons

Follow on MiLB First Pitch  https //stza.co/+vNgf-26

Shop  https //stza.co/+vNgf-1F

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:River Bandits @ Dragons
END:VALARM
DTSTART:20180713T230000Z
DTEND:20180714T020000Z
UID:Bu9bdUQrSC79IAaTA8BV2Fe0@stanza.co
SUMMARY:River Bandits @ Dragons
DESCRIPTION:River Bandits @ Dragons\n\nFollow on MiLB First Pitch: https://stza.co/+vNgf-26\n\nShop: https://stza.co/+vNgf-1F\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144552Z
LAST-MODIFIED:20180213T144552Z
TRANSP:OPAQUE
END:VEVENT
* River Bandits @ Hot Rods
<2018-07-14 Sat 18:35-21:35>
:PROPERTIES:
:ID:       nzYOhdWwbZUCf7aaVdGyN2qW@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

River Bandits @ Hot Rods River Bandits @ Hot Rods

Follow on MiLB First Pitch  https //stza.co/+vNfJ-1n

Shop  https //stza.co/+vNfJ-1G

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:River Bandits @ Hot Rods
END:VALARM
DTSTART:20180714T233500Z
DTEND:20180715T023500Z
UID:nzYOhdWwbZUCf7aaVdGyN2qW@stanza.co
SUMMARY:River Bandits @ Hot Rods
DESCRIPTION:River Bandits @ Hot Rods\n\nFollow on MiLB First Pitch: https://stza.co/+vNfJ-1n\n\nShop: https://stza.co/+vNfJ-1G\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144552Z
LAST-MODIFIED:20180213T144552Z
TRANSP:OPAQUE
END:VEVENT
* River Bandits @ Hot Rods
<2018-07-15 Sun 14:05-17:05>
:PROPERTIES:
:ID:       BJKVbWX2wZ5yJ1caFo-E4Lx2@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

River Bandits @ Hot Rods River Bandits @ Hot Rods

Follow on MiLB First Pitch  https //stza.co/+vNfK-1e

Shop  https //stza.co/+vNfK-11

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:River Bandits @ Hot Rods
END:VALARM
DTSTART:20180715T190500Z
DTEND:20180715T220500Z
UID:BJKVbWX2wZ5yJ1caFo-E4Lx2@stanza.co
SUMMARY:River Bandits @ Hot Rods
DESCRIPTION:River Bandits @ Hot Rods\n\nFollow on MiLB First Pitch: https://stza.co/+vNfK-1e\n\nShop: https://stza.co/+vNfK-11\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144552Z
LAST-MODIFIED:20180213T144552Z
TRANSP:OPAQUE
END:VEVENT
* River Bandits @ Hot Rods
<2018-07-16 Mon 12:05-15:05>
:PROPERTIES:
:ID:       RDN23UhG_8iyfqisapR2JgxE@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

River Bandits @ Hot Rods River Bandits @ Hot Rods

Follow on MiLB First Pitch  https //stza.co/+vNfL-3D

Shop  https //stza.co/+vNfL-3V

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:River Bandits @ Hot Rods
END:VALARM
DTSTART:20180716T170500Z
DTEND:20180716T200500Z
UID:RDN23UhG_8iyfqisapR2JgxE@stanza.co
SUMMARY:River Bandits @ Hot Rods
DESCRIPTION:River Bandits @ Hot Rods\n\nFollow on MiLB First Pitch: https://stza.co/+vNfL-3D\n\nShop: https://stza.co/+vNfL-3V\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144552Z
LAST-MODIFIED:20180213T144552Z
TRANSP:OPAQUE
END:VEVENT
* River Bandits vs. Cubs
<2018-07-18 Wed 18:35-21:35>
:PROPERTIES:
:ID:       9fXBCT1P0hQuJ2VQK_5tvQYh@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

River Bandits vs. Cubs River Bandits vs. Cubs

Follow on MiLB First Pitch  https //stza.co/+wxs0-W

Shop  https //stza.co/+wxs0-3i

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:River Bandits vs. Cubs
END:VALARM
DTSTART:20180718T233500Z
DTEND:20180719T023500Z
UID:9fXBCT1P0hQuJ2VQK_5tvQYh@stanza.co
SUMMARY:River Bandits vs. Cubs
DESCRIPTION:River Bandits vs. Cubs\n\nFollow on MiLB First Pitch: https://stza.co/+wxs0-W\n\nShop: https://stza.co/+wxs0-3i\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144552Z
LAST-MODIFIED:20180213T144552Z
TRANSP:OPAQUE
END:VEVENT
* River Bandits vs. Cubs
<2018-07-19 Thu 18:35-21:35>
:PROPERTIES:
:ID:       jJ1F6spEFiab_6zBIqTAWizL@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

River Bandits vs. Cubs River Bandits vs. Cubs

Follow on MiLB First Pitch  https //stza.co/+wxs3-2n

Shop  https //stza.co/+wxs3-11

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:River Bandits vs. Cubs
END:VALARM
DTSTART:20180719T233500Z
DTEND:20180720T023500Z
UID:jJ1F6spEFiab_6zBIqTAWizL@stanza.co
SUMMARY:River Bandits vs. Cubs
DESCRIPTION:River Bandits vs. Cubs\n\nFollow on MiLB First Pitch: https://stza.co/+wxs3-2n\n\nShop: https://stza.co/+wxs3-11\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144552Z
LAST-MODIFIED:20180213T144552Z
TRANSP:OPAQUE
END:VEVENT
* River Bandits vs. Cubs
<2018-07-20 Fri 18:35-21:35>
:PROPERTIES:
:ID:       aMr5gRBwgNpUSTzjVSAl-vKi@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

River Bandits vs. Cubs River Bandits vs. Cubs

Follow on MiLB First Pitch  https //stza.co/+wxs5-2a

Shop  https //stza.co/+wxs5-K

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:River Bandits vs. Cubs
END:VALARM
DTSTART:20180720T233500Z
DTEND:20180721T023500Z
UID:aMr5gRBwgNpUSTzjVSAl-vKi@stanza.co
SUMMARY:River Bandits vs. Cubs
DESCRIPTION:River Bandits vs. Cubs\n\nFollow on MiLB First Pitch: https://stza.co/+wxs5-2a\n\nShop: https://stza.co/+wxs5-K\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144552Z
LAST-MODIFIED:20180213T144552Z
TRANSP:OPAQUE
END:VEVENT
* River Bandits vs. Whitecaps
<2018-07-21 Sat 18:35-21:35>
:PROPERTIES:
:ID:       AZnzG0MpKQrONCtZUbw77kS3@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

River Bandits vs. Whitecaps River Bandits vs. Whitecaps

Follow on MiLB First Pitch  https //stza.co/+wxs6-2m

Shop  https //stza.co/+wxs6-1s

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:River Bandits vs. Whitecaps
END:VALARM
DTSTART:20180721T233500Z
DTEND:20180722T023500Z
UID:AZnzG0MpKQrONCtZUbw77kS3@stanza.co
SUMMARY:River Bandits vs. Whitecaps
DESCRIPTION:River Bandits vs. Whitecaps\n\nFollow on MiLB First Pitch: https://stza.co/+wxs6-2m\n\nShop: https://stza.co/+wxs6-1s\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144552Z
LAST-MODIFIED:20180213T144552Z
TRANSP:OPAQUE
END:VEVENT
* River Bandits vs. Whitecaps
<2018-07-22 Sun 17:15-20:15>
:PROPERTIES:
:ID:       ZUyGj-2Xcw62ey30HxzOta1O@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

River Bandits vs. Whitecaps River Bandits vs. Whitecaps

Follow on MiLB First Pitch  https //stza.co/+wxs9-1k

Shop  https //stza.co/+wxs9-3g

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:River Bandits vs. Whitecaps
END:VALARM
DTSTART:20180722T221500Z
DTEND:20180723T011500Z
UID:ZUyGj-2Xcw62ey30HxzOta1O@stanza.co
SUMMARY:River Bandits vs. Whitecaps
DESCRIPTION:River Bandits vs. Whitecaps\n\nFollow on MiLB First Pitch: https://stza.co/+wxs9-1k\n\nShop: https://stza.co/+wxs9-3g\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144552Z
LAST-MODIFIED:20180213T144552Z
TRANSP:OPAQUE
END:VEVENT
* River Bandits vs. Whitecaps
<2018-07-23 Mon 13:15-16:15>
:PROPERTIES:
:ID:       XHZOmqDviLm5kycMXpVpBbES@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

River Bandits vs. Whitecaps River Bandits vs. Whitecaps

Follow on MiLB First Pitch  https //stza.co/+wxsa-2Y

Shop  https //stza.co/+wxsa-1X

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:River Bandits vs. Whitecaps
END:VALARM
DTSTART:20180723T181500Z
DTEND:20180723T211500Z
UID:XHZOmqDviLm5kycMXpVpBbES@stanza.co
SUMMARY:River Bandits vs. Whitecaps
DESCRIPTION:River Bandits vs. Whitecaps\n\nFollow on MiLB First Pitch: https://stza.co/+wxsa-2Y\n\nShop: https://stza.co/+wxsa-1X\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144552Z
LAST-MODIFIED:20180213T144552Z
TRANSP:OPAQUE
END:VEVENT
* River Bandits @ Bees
<2018-07-25 Wed 18:30-21:30>
:PROPERTIES:
:ID:       jLkJikOrL9xLg4Pyr2zfrDYl@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

River Bandits @ Bees River Bandits @ Bees

Follow on MiLB First Pitch  https //stza.co/+xAIb-2m

Shop  https //stza.co/+xAIb-3r

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:River Bandits @ Bees
END:VALARM
DTSTART:20180725T233000Z
DTEND:20180726T023000Z
UID:jLkJikOrL9xLg4Pyr2zfrDYl@stanza.co
SUMMARY:River Bandits @ Bees
DESCRIPTION:River Bandits @ Bees\n\nFollow on MiLB First Pitch: https://stza.co/+xAIb-2m\n\nShop: https://stza.co/+xAIb-3r\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144552Z
LAST-MODIFIED:20180213T144552Z
TRANSP:OPAQUE
END:VEVENT
* River Bandits @ Bees
<2018-07-26 Thu 18:30-21:30>
:PROPERTIES:
:ID:       0puea25Zh9oL8uc76kxBEoRo@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

River Bandits @ Bees River Bandits @ Bees

Follow on MiLB First Pitch  https //stza.co/+xAIe-2b

Shop  https //stza.co/+xAIe-1s

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:River Bandits @ Bees
END:VALARM
DTSTART:20180726T233000Z
DTEND:20180727T023000Z
UID:0puea25Zh9oL8uc76kxBEoRo@stanza.co
SUMMARY:River Bandits @ Bees
DESCRIPTION:River Bandits @ Bees\n\nFollow on MiLB First Pitch: https://stza.co/+xAIe-2b\n\nShop: https://stza.co/+xAIe-1s\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144552Z
LAST-MODIFIED:20180213T144552Z
TRANSP:OPAQUE
END:VEVENT
* River Bandits @ Bees
<2018-07-27 Fri 18:30-21:30>
:PROPERTIES:
:ID:       QFUGnwQIoZQ-wjXiIbVUa9Il@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

River Bandits @ Bees River Bandits @ Bees

Follow on MiLB First Pitch  https //stza.co/+xAIf-j

Shop  https //stza.co/+xAIf-3Y

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:River Bandits @ Bees
END:VALARM
DTSTART:20180727T233000Z
DTEND:20180728T023000Z
UID:QFUGnwQIoZQ-wjXiIbVUa9Il@stanza.co
SUMMARY:River Bandits @ Bees
DESCRIPTION:River Bandits @ Bees\n\nFollow on MiLB First Pitch: https://stza.co/+xAIf-j\n\nShop: https://stza.co/+xAIf-3Y\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144552Z
LAST-MODIFIED:20180213T144552Z
TRANSP:OPAQUE
END:VEVENT
* River Bandits @ Kernels
<2018-07-28 Sat 18:35-21:35>
:PROPERTIES:
:ID:       bCt_qznVIDm0PvhZYkasOS29@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

River Bandits @ Kernels River Bandits @ Kernels

Buy tickets here  https //stza.co/~vNg3

Follow on MiLB First Pitch  https //stza.co/+vNg3-3U

Shop  https //stza.co/+vNg3-1t

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:River Bandits @ Kernels
END:VALARM
DTSTART:20180728T233500Z
DTEND:20180729T023500Z
UID:bCt_qznVIDm0PvhZYkasOS29@stanza.co
SUMMARY:River Bandits @ Kernels
DESCRIPTION:River Bandits @ Kernels\n\nBuy tickets here: https://stza.co/~vNg3\n\nFollow on MiLB First Pitch: https://stza.co/+vNg3-3U\n\nShop: https://stza.co/+vNg3-1t\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144552Z
LAST-MODIFIED:20180213T144552Z
TRANSP:OPAQUE
END:VEVENT
* River Bandits @ Kernels
<2018-07-29 Sun 14:05-17:05>
:PROPERTIES:
:ID:       xvY7RQMXZ93x_AQeVQklhQTu@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

River Bandits @ Kernels River Bandits @ Kernels

Buy tickets here  https //stza.co/~vNg4

Follow on MiLB First Pitch  https //stza.co/+vNg4-32

Shop  https //stza.co/+vNg4-3U

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:River Bandits @ Kernels
END:VALARM
DTSTART:20180729T190500Z
DTEND:20180729T220500Z
UID:xvY7RQMXZ93x_AQeVQklhQTu@stanza.co
SUMMARY:River Bandits @ Kernels
DESCRIPTION:River Bandits @ Kernels\n\nBuy tickets here: https://stza.co/~vNg4\n\nFollow on MiLB First Pitch: https://stza.co/+vNg4-32\n\nShop: https://stza.co/+vNg4-3U\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144552Z
LAST-MODIFIED:20180213T144552Z
TRANSP:OPAQUE
END:VEVENT
* River Bandits vs. Kernels
<2018-07-30 Mon 18:35-21:35>
:PROPERTIES:
:ID:       QSFwJrDEoirYPe3NHxUiqZeY@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

River Bandits vs. Kernels River Bandits vs. Kernels

Follow on MiLB First Pitch  https //stza.co/+wxsd-2M

Shop  https //stza.co/+wxsd-1V

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:River Bandits vs. Kernels
END:VALARM
DTSTART:20180730T233500Z
DTEND:20180731T023500Z
UID:QSFwJrDEoirYPe3NHxUiqZeY@stanza.co
SUMMARY:River Bandits vs. Kernels
DESCRIPTION:River Bandits vs. Kernels\n\nFollow on MiLB First Pitch: https://stza.co/+wxsd-2M\n\nShop: https://stza.co/+wxsd-1V\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144552Z
LAST-MODIFIED:20180213T144552Z
TRANSP:OPAQUE
END:VEVENT
* River Bandits vs. Kernels
<2018-07-31 Tue 18:35-21:35>
:PROPERTIES:
:ID:       xRqQrybb5w5PoKKpkYEj159m@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

River Bandits vs. Kernels River Bandits vs. Kernels

Follow on MiLB First Pitch  https //stza.co/+wxsf-3x

Shop  https //stza.co/+wxsf-S

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:River Bandits vs. Kernels
END:VALARM
DTSTART:20180731T233500Z
DTEND:20180801T023500Z
UID:xRqQrybb5w5PoKKpkYEj159m@stanza.co
SUMMARY:River Bandits vs. Kernels
DESCRIPTION:River Bandits vs. Kernels\n\nFollow on MiLB First Pitch: https://stza.co/+wxsf-3x\n\nShop: https://stza.co/+wxsf-S\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144552Z
LAST-MODIFIED:20180213T144552Z
TRANSP:OPAQUE
END:VEVENT
* River Bandits vs. LumberKings
<2018-08-01 Wed 18:35-21:35>
:PROPERTIES:
:ID:       XCDQ06-M9Mh7AMRxRsSZGo6X@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

River Bandits vs. LumberKings River Bandits vs. LumberKings

Follow on MiLB First Pitch  https //stza.co/+wxsg-1p

Shop  https //stza.co/+wxsg-3Y

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:River Bandits vs. LumberKings
END:VALARM
DTSTART:20180801T233500Z
DTEND:20180802T023500Z
UID:XCDQ06-M9Mh7AMRxRsSZGo6X@stanza.co
SUMMARY:River Bandits vs. LumberKings
DESCRIPTION:River Bandits vs. LumberKings\n\nFollow on MiLB First Pitch: https://stza.co/+wxsg-1p\n\nShop: https://stza.co/+wxsg-3Y\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144552Z
LAST-MODIFIED:20180213T144552Z
TRANSP:OPAQUE
END:VEVENT
* River Bandits vs. LumberKings
<2018-08-02 Thu 18:35-21:35>
:PROPERTIES:
:ID:       nL1UYs-fdedeV1hRlMGPh03G@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

River Bandits vs. LumberKings River Bandits vs. LumberKings

Follow on MiLB First Pitch  https //stza.co/+wxsj-3D

Shop  https //stza.co/+wxsj-e

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:River Bandits vs. LumberKings
END:VALARM
DTSTART:20180802T233500Z
DTEND:20180803T023500Z
UID:nL1UYs-fdedeV1hRlMGPh03G@stanza.co
SUMMARY:River Bandits vs. LumberKings
DESCRIPTION:River Bandits vs. LumberKings\n\nFollow on MiLB First Pitch: https://stza.co/+wxsj-3D\n\nShop: https://stza.co/+wxsj-e\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144552Z
LAST-MODIFIED:20180213T144552Z
TRANSP:OPAQUE
END:VEVENT
* River Bandits vs. LumberKings
<2018-08-03 Fri 18:35-21:35>
:PROPERTIES:
:ID:       O-nJvgMLsztQNQDSesrIW6Ks@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

River Bandits vs. LumberKings River Bandits vs. LumberKings

Follow on MiLB First Pitch  https //stza.co/+wxsl-1f

Shop  https //stza.co/+wxsl-3h

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:River Bandits vs. LumberKings
END:VALARM
DTSTART:20180803T233500Z
DTEND:20180804T023500Z
UID:O-nJvgMLsztQNQDSesrIW6Ks@stanza.co
SUMMARY:River Bandits vs. LumberKings
DESCRIPTION:River Bandits vs. LumberKings\n\nFollow on MiLB First Pitch: https://stza.co/+wxsl-1f\n\nShop: https://stza.co/+wxsl-3h\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144552Z
LAST-MODIFIED:20180213T144552Z
TRANSP:OPAQUE
END:VEVENT
* River Bandits @ Chiefs
<2018-08-04 Sat 18:30-21:30>
:PROPERTIES:
:ID:       Flmfb6wyM2qEsFByPxmCIFPW@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

River Bandits @ Chiefs River Bandits @ Chiefs

Follow on MiLB First Pitch  https //stza.co/+xAIH-2R

Shop  https //stza.co/+xAIH-1v

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:River Bandits @ Chiefs
END:VALARM
DTSTART:20180804T233000Z
DTEND:20180805T023000Z
UID:Flmfb6wyM2qEsFByPxmCIFPW@stanza.co
SUMMARY:River Bandits @ Chiefs
DESCRIPTION:River Bandits @ Chiefs\n\nFollow on MiLB First Pitch: https://stza.co/+xAIH-2R\n\nShop: https://stza.co/+xAIH-1v\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144552Z
LAST-MODIFIED:20180213T144552Z
TRANSP:OPAQUE
END:VEVENT
* River Bandits @ Chiefs
<2018-08-05 Sun 14:00-17:00>
:PROPERTIES:
:ID:       uXiULobnpfrojsO9xvIesNla@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

River Bandits @ Chiefs River Bandits @ Chiefs

Follow on MiLB First Pitch  https //stza.co/+xAII-15

Shop  https //stza.co/+xAII-39

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:River Bandits @ Chiefs
END:VALARM
DTSTART:20180805T190000Z
DTEND:20180805T220000Z
UID:uXiULobnpfrojsO9xvIesNla@stanza.co
SUMMARY:River Bandits @ Chiefs
DESCRIPTION:River Bandits @ Chiefs\n\nFollow on MiLB First Pitch: https://stza.co/+xAII-15\n\nShop: https://stza.co/+xAII-39\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144552Z
LAST-MODIFIED:20180213T144552Z
TRANSP:OPAQUE
END:VEVENT
* River Bandits @ Chiefs
<2018-08-06 Mon 19:00-22:00>
:PROPERTIES:
:ID:       6Qd5NO9s3TeT-toRPqyrUqgI@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

River Bandits @ Chiefs River Bandits @ Chiefs

Follow on MiLB First Pitch  https //stza.co/+xAIJ-15

Shop  https //stza.co/+xAIJ-3v

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:River Bandits @ Chiefs
END:VALARM
DTSTART:20180807T000000Z
DTEND:20180807T030000Z
UID:6Qd5NO9s3TeT-toRPqyrUqgI@stanza.co
SUMMARY:River Bandits @ Chiefs
DESCRIPTION:River Bandits @ Chiefs\n\nFollow on MiLB First Pitch: https://stza.co/+xAIJ-15\n\nShop: https://stza.co/+xAIJ-3v\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144552Z
LAST-MODIFIED:20180213T144552Z
TRANSP:OPAQUE
END:VEVENT
* River Bandits @ Snappers
<2018-08-08 Wed 19:00-22:00>
:PROPERTIES:
:ID:       GfQ_L890yq6jiPIq7xFThvJD@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

River Bandits @ Snappers River Bandits @ Snappers

Follow on MiLB First Pitch  https //stza.co/+wSNZ-F

Shop  https //stza.co/+wSNZ-2v

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:River Bandits @ Snappers
END:VALARM
DTSTART:20180809T000000Z
DTEND:20180809T030000Z
UID:GfQ_L890yq6jiPIq7xFThvJD@stanza.co
SUMMARY:River Bandits @ Snappers
DESCRIPTION:River Bandits @ Snappers\n\nFollow on MiLB First Pitch: https://stza.co/+wSNZ-F\n\nShop: https://stza.co/+wSNZ-2v\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144552Z
LAST-MODIFIED:20180213T144552Z
TRANSP:OPAQUE
END:VEVENT
* River Bandits @ Snappers
<2018-08-09 Thu 19:00-22:00>
:PROPERTIES:
:ID:       xABXWSuADSjreMhsRDkTDsrm@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

River Bandits @ Snappers River Bandits @ Snappers

Follow on MiLB First Pitch  https //stza.co/+wSN_-3q

Shop  https //stza.co/+wSN_-3m

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:River Bandits @ Snappers
END:VALARM
DTSTART:20180810T000000Z
DTEND:20180810T030000Z
UID:xABXWSuADSjreMhsRDkTDsrm@stanza.co
SUMMARY:River Bandits @ Snappers
DESCRIPTION:River Bandits @ Snappers\n\nFollow on MiLB First Pitch: https://stza.co/+wSN_-3q\n\nShop: https://stza.co/+wSN_-3m\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144552Z
LAST-MODIFIED:20180213T144552Z
TRANSP:OPAQUE
END:VEVENT
* River Bandits @ Snappers
<2018-08-10 Fri 19:00-22:00>
:PROPERTIES:
:ID:       akSYlZrVpnWjNrDqQJqIDNqa@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

River Bandits @ Snappers River Bandits @ Snappers

Follow on MiLB First Pitch  https //stza.co/+wSN$-

Shop  https //stza.co/+wSN$-3h

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:River Bandits @ Snappers
END:VALARM
DTSTART:20180811T000000Z
DTEND:20180811T030000Z
UID:akSYlZrVpnWjNrDqQJqIDNqa@stanza.co
SUMMARY:River Bandits @ Snappers
DESCRIPTION:River Bandits @ Snappers\n\nFollow on MiLB First Pitch: https://stza.co/+wSN$-\n\nShop: https://stza.co/+wSN$-3h\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144552Z
LAST-MODIFIED:20180213T144552Z
TRANSP:OPAQUE
END:VEVENT
* River Bandits vs. Kernels
<2018-08-11 Sat 18:35-21:35>
:PROPERTIES:
:ID:       XfbmaRr4l-_qV665oMaYxbzo@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

River Bandits vs. Kernels River Bandits vs. Kernels

Follow on MiLB First Pitch  https //stza.co/+wxso-3x

Shop  https //stza.co/+wxso-2j

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:River Bandits vs. Kernels
END:VALARM
DTSTART:20180811T233500Z
DTEND:20180812T023500Z
UID:XfbmaRr4l-_qV665oMaYxbzo@stanza.co
SUMMARY:River Bandits vs. Kernels
DESCRIPTION:River Bandits vs. Kernels\n\nFollow on MiLB First Pitch: https://stza.co/+wxso-3x\n\nShop: https://stza.co/+wxso-2j\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144552Z
LAST-MODIFIED:20180213T144552Z
TRANSP:OPAQUE
END:VEVENT
* River Bandits vs. Kernels
<2018-08-12 Sun 17:15-20:15>
:PROPERTIES:
:ID:       gJQtK7Srk_HvFw7iPW5ojZjJ@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

River Bandits vs. Kernels River Bandits vs. Kernels

Follow on MiLB First Pitch  https //stza.co/+wxsr-j

Shop  https //stza.co/+wxsr-39

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:River Bandits vs. Kernels
END:VALARM
DTSTART:20180812T221500Z
DTEND:20180813T011500Z
UID:gJQtK7Srk_HvFw7iPW5ojZjJ@stanza.co
SUMMARY:River Bandits vs. Kernels
DESCRIPTION:River Bandits vs. Kernels\n\nFollow on MiLB First Pitch: https://stza.co/+wxsr-j\n\nShop: https://stza.co/+wxsr-39\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144552Z
LAST-MODIFIED:20180213T144552Z
TRANSP:OPAQUE
END:VEVENT
* River Bandits @ Kernels
<2018-08-13 Mon 18:35-21:35>
:PROPERTIES:
:ID:       9a1o32NkFHSRV8KwMyG-sTBG@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

River Bandits @ Kernels River Bandits @ Kernels

Buy tickets here  https //stza.co/~vNg5

Follow on MiLB First Pitch  https //stza.co/+vNg5-2j

Shop  https //stza.co/+vNg5-1U

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:River Bandits @ Kernels
END:VALARM
DTSTART:20180813T233500Z
DTEND:20180814T023500Z
UID:9a1o32NkFHSRV8KwMyG-sTBG@stanza.co
SUMMARY:River Bandits @ Kernels
DESCRIPTION:River Bandits @ Kernels\n\nBuy tickets here: https://stza.co/~vNg5\n\nFollow on MiLB First Pitch: https://stza.co/+vNg5-2j\n\nShop: https://stza.co/+vNg5-1U\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144552Z
LAST-MODIFIED:20180213T144552Z
TRANSP:OPAQUE
END:VEVENT
* River Bandits @ Kernels
<2018-08-14 Tue 18:35-21:35>
:PROPERTIES:
:ID:       _Biax4LjdjA8RrriOmCz22RM@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

River Bandits @ Kernels River Bandits @ Kernels

Buy tickets here  https //stza.co/~vNg6

Follow on MiLB First Pitch  https //stza.co/+vNg6-3T

Shop  https //stza.co/+vNg6-24

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:River Bandits @ Kernels
END:VALARM
DTSTART:20180814T233500Z
DTEND:20180815T023500Z
UID:_Biax4LjdjA8RrriOmCz22RM@stanza.co
SUMMARY:River Bandits @ Kernels
DESCRIPTION:River Bandits @ Kernels\n\nBuy tickets here: https://stza.co/~vNg6\n\nFollow on MiLB First Pitch: https://stza.co/+vNg6-3T\n\nShop: https://stza.co/+vNg6-24\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144552Z
LAST-MODIFIED:20180213T144552Z
TRANSP:OPAQUE
END:VEVENT
* River Bandits vs. Cougars
<2018-08-15 Wed 18:35-21:35>
:PROPERTIES:
:ID:       -4wWanQvrBpCpO-KO_N5f_21@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

River Bandits vs. Cougars River Bandits vs. Cougars

Follow on MiLB First Pitch  https //stza.co/+wxss-3T

Shop  https //stza.co/+wxss-1g

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:River Bandits vs. Cougars
END:VALARM
DTSTART:20180815T233500Z
DTEND:20180816T023500Z
UID:-4wWanQvrBpCpO-KO_N5f_21@stanza.co
SUMMARY:River Bandits vs. Cougars
DESCRIPTION:River Bandits vs. Cougars\n\nFollow on MiLB First Pitch: https://stza.co/+wxss-3T\n\nShop: https://stza.co/+wxss-1g\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144552Z
LAST-MODIFIED:20180213T144552Z
TRANSP:OPAQUE
END:VEVENT
* River Bandits vs. Cougars
<2018-08-16 Thu 18:35-21:35>
:PROPERTIES:
:ID:       e3iCs5thWGrixinnENwSPAsK@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

River Bandits vs. Cougars River Bandits vs. Cougars

Follow on MiLB First Pitch  https //stza.co/+wxsv-1P

Shop  https //stza.co/+wxsv-3b

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:River Bandits vs. Cougars
END:VALARM
DTSTART:20180816T233500Z
DTEND:20180817T023500Z
UID:e3iCs5thWGrixinnENwSPAsK@stanza.co
SUMMARY:River Bandits vs. Cougars
DESCRIPTION:River Bandits vs. Cougars\n\nFollow on MiLB First Pitch: https://stza.co/+wxsv-1P\n\nShop: https://stza.co/+wxsv-3b\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144552Z
LAST-MODIFIED:20180213T144552Z
TRANSP:OPAQUE
END:VEVENT
* River Bandits vs. Cougars
<2018-08-17 Fri 18:35-21:35>
:PROPERTIES:
:ID:       CtGR47jDpEmvADzqKq3L5nxJ@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

River Bandits vs. Cougars River Bandits vs. Cougars

Follow on MiLB First Pitch  https //stza.co/+wxsx-2c

Shop  https //stza.co/+wxsx-3A

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:River Bandits vs. Cougars
END:VALARM
DTSTART:20180817T233500Z
DTEND:20180818T023500Z
UID:CtGR47jDpEmvADzqKq3L5nxJ@stanza.co
SUMMARY:River Bandits vs. Cougars
DESCRIPTION:River Bandits vs. Cougars\n\nFollow on MiLB First Pitch: https://stza.co/+wxsx-2c\n\nShop: https://stza.co/+wxsx-3A\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144552Z
LAST-MODIFIED:20180213T144552Z
TRANSP:OPAQUE
END:VEVENT
* River Bandits vs. Chiefs
<2018-08-18 Sat 18:35-21:35>
:PROPERTIES:
:ID:       6BhnWSuCq6HC8G3HwKGjE42Y@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

River Bandits vs. Chiefs River Bandits vs. Chiefs

Follow on MiLB First Pitch  https //stza.co/+wxsy-3U

Shop  https //stza.co/+wxsy-36

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:River Bandits vs. Chiefs
END:VALARM
DTSTART:20180818T233500Z
DTEND:20180819T023500Z
UID:6BhnWSuCq6HC8G3HwKGjE42Y@stanza.co
SUMMARY:River Bandits vs. Chiefs
DESCRIPTION:River Bandits vs. Chiefs\n\nFollow on MiLB First Pitch: https://stza.co/+wxsy-3U\n\nShop: https://stza.co/+wxsy-36\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144552Z
LAST-MODIFIED:20180213T144552Z
TRANSP:OPAQUE
END:VEVENT
* River Bandits vs. Chiefs
<2018-08-19 Sun 17:15-20:15>
:PROPERTIES:
:ID:       mTtXM9-yGbDm6s4XsABUzWeD@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

River Bandits vs. Chiefs River Bandits vs. Chiefs

Follow on MiLB First Pitch  https //stza.co/+wxsA-2F

Shop  https //stza.co/+wxsA-12

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:River Bandits vs. Chiefs
END:VALARM
DTSTART:20180819T221500Z
DTEND:20180820T011500Z
UID:mTtXM9-yGbDm6s4XsABUzWeD@stanza.co
SUMMARY:River Bandits vs. Chiefs
DESCRIPTION:River Bandits vs. Chiefs\n\nFollow on MiLB First Pitch: https://stza.co/+wxsA-2F\n\nShop: https://stza.co/+wxsA-12\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144552Z
LAST-MODIFIED:20180213T144552Z
TRANSP:OPAQUE
END:VEVENT
* River Bandits vs. Chiefs
<2018-08-20 Mon 18:35-21:35>
:PROPERTIES:
:ID:       eT4hfvd2Tx1DvdxCTFjNEsL6@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

River Bandits vs. Chiefs River Bandits vs. Chiefs

Follow on MiLB First Pitch  https //stza.co/+wxsD-e

Shop  https //stza.co/+wxsD-3O

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:River Bandits vs. Chiefs
END:VALARM
DTSTART:20180820T233500Z
DTEND:20180821T023500Z
UID:eT4hfvd2Tx1DvdxCTFjNEsL6@stanza.co
SUMMARY:River Bandits vs. Chiefs
DESCRIPTION:River Bandits vs. Chiefs\n\nFollow on MiLB First Pitch: https://stza.co/+wxsD-e\n\nShop: https://stza.co/+wxsD-3O\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144552Z
LAST-MODIFIED:20180213T144552Z
TRANSP:OPAQUE
END:VEVENT
* River Bandits @ Timber Rattlers
<2018-08-21 Tue 19:05-22:05>
:PROPERTIES:
:ID:       YPM3FYT8feVh4bJsJ7c6nHy8@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

River Bandits @ Timber Rattlers River Bandits @ Timber Rattlers

Follow on MiLB First Pitch  https //stza.co/+vNiQ-3V

Shop  https //stza.co/+vNiQ-13

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:River Bandits @ Timber Rattlers
END:VALARM
DTSTART:20180822T000500Z
DTEND:20180822T030500Z
UID:YPM3FYT8feVh4bJsJ7c6nHy8@stanza.co
SUMMARY:River Bandits @ Timber Rattlers
DESCRIPTION:River Bandits @ Timber Rattlers\n\nFollow on MiLB First Pitch: https://stza.co/+vNiQ-3V\n\nShop: https://stza.co/+vNiQ-13\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144552Z
LAST-MODIFIED:20180213T144552Z
TRANSP:OPAQUE
END:VEVENT
* River Bandits @ Timber Rattlers
<2018-08-22 Wed 19:05-22:05>
:PROPERTIES:
:ID:       UMdZRKVhVf55YBllf9HTJmJZ@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

River Bandits @ Timber Rattlers River Bandits @ Timber Rattlers

Follow on MiLB First Pitch  https //stza.co/+vt9c-2y

Shop  https //stza.co/+vt9c-1u

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:River Bandits @ Timber Rattlers
END:VALARM
DTSTART:20180823T000500Z
DTEND:20180823T030500Z
UID:UMdZRKVhVf55YBllf9HTJmJZ@stanza.co
SUMMARY:River Bandits @ Timber Rattlers
DESCRIPTION:River Bandits @ Timber Rattlers\n\nFollow on MiLB First Pitch: https://stza.co/+vt9c-2y\n\nShop: https://stza.co/+vt9c-1u\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144552Z
LAST-MODIFIED:20180213T144552Z
TRANSP:OPAQUE
END:VEVENT
* River Bandits @ Timber Rattlers
<2018-08-23 Thu 19:05-22:05>
:PROPERTIES:
:ID:       Xq7vN7btiee6ue0jrbjEOSFE@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

River Bandits @ Timber Rattlers River Bandits @ Timber Rattlers

Follow on MiLB First Pitch  https //stza.co/+vt9d-1E

Shop  https //stza.co/+vt9d-3k

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:River Bandits @ Timber Rattlers
END:VALARM
DTSTART:20180824T000500Z
DTEND:20180824T030500Z
UID:Xq7vN7btiee6ue0jrbjEOSFE@stanza.co
SUMMARY:River Bandits @ Timber Rattlers
DESCRIPTION:River Bandits @ Timber Rattlers\n\nFollow on MiLB First Pitch: https://stza.co/+vt9d-1E\n\nShop: https://stza.co/+vt9d-3k\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144552Z
LAST-MODIFIED:20180213T144552Z
TRANSP:OPAQUE
END:VEVENT
* River Bandits @ Bees
<2018-08-24 Fri 18:30-21:30>
:PROPERTIES:
:ID:       kp7oFO-DXTLcqAxSkpomfNpa@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

River Bandits @ Bees River Bandits @ Bees

Follow on MiLB First Pitch  https //stza.co/+xAIg-1D

Shop  https //stza.co/+xAIg-G

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:River Bandits @ Bees
END:VALARM
DTSTART:20180824T233000Z
DTEND:20180825T023000Z
UID:kp7oFO-DXTLcqAxSkpomfNpa@stanza.co
SUMMARY:River Bandits @ Bees
DESCRIPTION:River Bandits @ Bees\n\nFollow on MiLB First Pitch: https://stza.co/+xAIg-1D\n\nShop: https://stza.co/+xAIg-G\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144552Z
LAST-MODIFIED:20180213T144552Z
TRANSP:OPAQUE
END:VEVENT
* River Bandits @ Bees
<2018-08-25 Sat 18:30-21:30>
:PROPERTIES:
:ID:       RFRC45qgkdkKomxXpP8AmovZ@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

River Bandits @ Bees River Bandits @ Bees

Follow on MiLB First Pitch  https //stza.co/+xAIh-3I

Shop  https //stza.co/+xAIh-1p

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:River Bandits @ Bees
END:VALARM
DTSTART:20180825T233000Z
DTEND:20180826T023000Z
UID:RFRC45qgkdkKomxXpP8AmovZ@stanza.co
SUMMARY:River Bandits @ Bees
DESCRIPTION:River Bandits @ Bees\n\nFollow on MiLB First Pitch: https://stza.co/+xAIh-3I\n\nShop: https://stza.co/+xAIh-1p\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144552Z
LAST-MODIFIED:20180213T144552Z
TRANSP:OPAQUE
END:VEVENT
* River Bandits @ Bees
<2018-08-26 Sun 14:00-17:00>
:PROPERTIES:
:ID:       Jnw_gTyTWGvuSbKQSqFI_DyB@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

River Bandits @ Bees River Bandits @ Bees

Follow on MiLB First Pitch  https //stza.co/+xAIk-a

Shop  https //stza.co/+xAIk-2v

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:River Bandits @ Bees
END:VALARM
DTSTART:20180826T190000Z
DTEND:20180826T220000Z
UID:Jnw_gTyTWGvuSbKQSqFI_DyB@stanza.co
SUMMARY:River Bandits @ Bees
DESCRIPTION:River Bandits @ Bees\n\nFollow on MiLB First Pitch: https://stza.co/+xAIk-a\n\nShop: https://stza.co/+xAIk-2v\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144552Z
LAST-MODIFIED:20180213T144552Z
TRANSP:OPAQUE
END:VEVENT
* River Bandits @ Bees
<2018-08-27 Mon 18:30-21:30>
:PROPERTIES:
:ID:       uK4--2uOJGfxwkGJelfDK1HL@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

River Bandits @ Bees River Bandits @ Bees

Follow on MiLB First Pitch  https //stza.co/+xAIm-s

Shop  https //stza.co/+xAIm-B

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:River Bandits @ Bees
END:VALARM
DTSTART:20180827T233000Z
DTEND:20180828T023000Z
UID:uK4--2uOJGfxwkGJelfDK1HL@stanza.co
SUMMARY:River Bandits @ Bees
DESCRIPTION:River Bandits @ Bees\n\nFollow on MiLB First Pitch: https://stza.co/+xAIm-s\n\nShop: https://stza.co/+xAIm-B\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144552Z
LAST-MODIFIED:20180213T144552Z
TRANSP:OPAQUE
END:VEVENT
* River Bandits @ LumberKings
<2018-08-29 Wed 18:30-21:30>
:PROPERTIES:
:ID:       Lgb3NuUyA1-R-nf6f3EI0QMH@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

River Bandits @ LumberKings River Bandits @ LumberKings

Follow on MiLB First Pitch  https //stza.co/+vNga-1J

Shop  https //stza.co/+vNga-2O

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:River Bandits @ LumberKings
END:VALARM
DTSTART:20180829T233000Z
DTEND:20180830T023000Z
UID:Lgb3NuUyA1-R-nf6f3EI0QMH@stanza.co
SUMMARY:River Bandits @ LumberKings
DESCRIPTION:River Bandits @ LumberKings\n\nFollow on MiLB First Pitch: https://stza.co/+vNga-1J\n\nShop: https://stza.co/+vNga-2O\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144552Z
LAST-MODIFIED:20180213T144552Z
TRANSP:OPAQUE
END:VEVENT
* River Bandits @ LumberKings
<2018-08-30 Thu 18:30-21:30>
:PROPERTIES:
:ID:       TqGTx1NJvUMIJ18miysbrovw@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

River Bandits @ LumberKings River Bandits @ LumberKings

Follow on MiLB First Pitch  https //stza.co/+vNgb-X

Shop  https //stza.co/+vNgb-2k

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:River Bandits @ LumberKings
END:VALARM
DTSTART:20180830T233000Z
DTEND:20180831T023000Z
UID:TqGTx1NJvUMIJ18miysbrovw@stanza.co
SUMMARY:River Bandits @ LumberKings
DESCRIPTION:River Bandits @ LumberKings\n\nFollow on MiLB First Pitch: https://stza.co/+vNgb-X\n\nShop: https://stza.co/+vNgb-2k\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144552Z
LAST-MODIFIED:20180213T144552Z
TRANSP:OPAQUE
END:VEVENT
* River Bandits @ LumberKings
<2018-08-31 Fri 18:30-21:30>
:PROPERTIES:
:ID:       he4upjxZBhnMtX3VkJ3NthTc@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

River Bandits @ LumberKings River Bandits @ LumberKings

Follow on MiLB First Pitch  https //stza.co/+vNgc-A

Shop  https //stza.co/+vNgc-3m

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:River Bandits @ LumberKings
END:VALARM
DTSTART:20180831T233000Z
DTEND:20180901T023000Z
UID:he4upjxZBhnMtX3VkJ3NthTc@stanza.co
SUMMARY:River Bandits @ LumberKings
DESCRIPTION:River Bandits @ LumberKings\n\nFollow on MiLB First Pitch: https://stza.co/+vNgc-A\n\nShop: https://stza.co/+vNgc-3m\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144552Z
LAST-MODIFIED:20180213T144552Z
TRANSP:OPAQUE
END:VEVENT
* River Bandits vs. Chiefs
<2018-09-01 Sat 18:35-21:35>
:PROPERTIES:
:ID:       xjVBQjshErqgVPCr6nM2Feio@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

River Bandits vs. Chiefs River Bandits vs. Chiefs

Follow on MiLB First Pitch  https //stza.co/+wxsE-19

Shop  https //stza.co/+wxsE-1y

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:River Bandits vs. Chiefs
END:VALARM
DTSTART:20180901T233500Z
DTEND:20180902T023500Z
UID:xjVBQjshErqgVPCr6nM2Feio@stanza.co
SUMMARY:River Bandits vs. Chiefs
DESCRIPTION:River Bandits vs. Chiefs\n\nFollow on MiLB First Pitch: https://stza.co/+wxsE-19\n\nShop: https://stza.co/+wxsE-1y\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144552Z
LAST-MODIFIED:20180213T144552Z
TRANSP:OPAQUE
END:VEVENT
* River Bandits vs. Chiefs
<2018-09-02 Sun 13:15-16:15>
:PROPERTIES:
:ID:       wpzqf0wpmOQC1QYNfnx-hevC@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

River Bandits vs. Chiefs River Bandits vs. Chiefs

Follow on MiLB First Pitch  https //stza.co/+wxsG-_

Shop  https //stza.co/+wxsG-Y

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:River Bandits vs. Chiefs
END:VALARM
DTSTART:20180902T181500Z
DTEND:20180902T211500Z
UID:wpzqf0wpmOQC1QYNfnx-hevC@stanza.co
SUMMARY:River Bandits vs. Chiefs
DESCRIPTION:River Bandits vs. Chiefs\n\nFollow on MiLB First Pitch: https://stza.co/+wxsG-_\n\nShop: https://stza.co/+wxsG-Y\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144552Z
LAST-MODIFIED:20180213T144552Z
TRANSP:OPAQUE
END:VEVENT
* River Bandits vs. Chiefs
<2018-09-03 Mon 13:15-16:15>
:PROPERTIES:
:ID:       rERkirE5LSTJm592kQ-UdFbm@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

River Bandits vs. Chiefs River Bandits vs. Chiefs

Follow on MiLB First Pitch  https //stza.co/+wxsI-1H

Shop  https //stza.co/+wxsI-3Y

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:River Bandits vs. Chiefs
END:VALARM
DTSTART:20180903T181500Z
DTEND:20180903T211500Z
UID:rERkirE5LSTJm592kQ-UdFbm@stanza.co
SUMMARY:River Bandits vs. Chiefs
DESCRIPTION:River Bandits vs. Chiefs\n\nFollow on MiLB First Pitch: https://stza.co/+wxsI-1H\n\nShop: https://stza.co/+wxsI-3Y\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144552Z
LAST-MODIFIED:20180213T144552Z
TRANSP:OPAQUE
END:VEVENT
