#+TITLE:       Main Google calendar entries
#+AUTHOR:      Eric S Fraga
#+EMAIL:       e.fraga@ucl.ac.uk
#+DESCRIPTION: converted using the ical2org awk script
#+CATEGORY:    google
#+STARTUP:     hidestars
#+STARTUP:     overview

* COMMENT original iCal preamble

* IronBirds vs. Renegades
<2018-06-15 Fri 18:05-21:05>
:PROPERTIES:
:ID:       nE054MTGitWzTwQ38jw1qRtB@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

IronBirds vs. Renegades IronBirds vs. Renegades

Follow on MiLB First Pitch  https //stza.co/+xXSx-C

Shop  https //stza.co/+xXSx-3U

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:IronBirds vs. Renegades
END:VALARM
DTSTART:20180615T230500Z
DTEND:20180616T020500Z
UID:nE054MTGitWzTwQ38jw1qRtB@stanza.co
SUMMARY:IronBirds vs. Renegades
DESCRIPTION:IronBirds vs. Renegades\n\nFollow on MiLB First Pitch: https://stza.co/+xXSx-C\n\nShop: https://stza.co/+xXSx-3U\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144459Z
LAST-MODIFIED:20180213T144459Z
TRANSP:OPAQUE
END:VEVENT
* IronBirds vs. Renegades
<2018-06-16 Sat 17:05-20:05>
:PROPERTIES:
:ID:       S-U6I_bhhTKv8WQE93BcmZd5@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

IronBirds vs. Renegades IronBirds vs. Renegades

Follow on MiLB First Pitch  https //stza.co/+xXSz-21

Shop  https //stza.co/+xXSz-4

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:IronBirds vs. Renegades
END:VALARM
DTSTART:20180616T220500Z
DTEND:20180617T010500Z
UID:S-U6I_bhhTKv8WQE93BcmZd5@stanza.co
SUMMARY:IronBirds vs. Renegades
DESCRIPTION:IronBirds vs. Renegades\n\nFollow on MiLB First Pitch: https://stza.co/+xXSz-21\n\nShop: https://stza.co/+xXSz-4\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144459Z
LAST-MODIFIED:20180213T144459Z
TRANSP:OPAQUE
END:VEVENT
* IronBirds vs. Renegades
<2018-06-17 Sun 15:05-18:05>
:PROPERTIES:
:ID:       O3r-LL9rYPh7RxWZAfYxQnrN@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

IronBirds vs. Renegades IronBirds vs. Renegades

Follow on MiLB First Pitch  https //stza.co/+xXSB-2s

Shop  https //stza.co/+xXSB-3S

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:IronBirds vs. Renegades
END:VALARM
DTSTART:20180617T200500Z
DTEND:20180617T230500Z
UID:O3r-LL9rYPh7RxWZAfYxQnrN@stanza.co
SUMMARY:IronBirds vs. Renegades
DESCRIPTION:IronBirds vs. Renegades\n\nFollow on MiLB First Pitch: https://stza.co/+xXSB-2s\n\nShop: https://stza.co/+xXSB-3S\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144459Z
LAST-MODIFIED:20180213T144459Z
TRANSP:OPAQUE
END:VEVENT
* IronBirds vs. ValleyCats
<2018-06-18 Mon 18:05-21:05>
:PROPERTIES:
:ID:       tyGz9okSCOwS71-g2zNHMR-X@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

IronBirds vs. ValleyCats IronBirds vs. ValleyCats

Follow on MiLB First Pitch  https //stza.co/+xXSE-Y

Shop  https //stza.co/+xXSE-k

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:IronBirds vs. ValleyCats
END:VALARM
DTSTART:20180618T230500Z
DTEND:20180619T020500Z
UID:tyGz9okSCOwS71-g2zNHMR-X@stanza.co
SUMMARY:IronBirds vs. ValleyCats
DESCRIPTION:IronBirds vs. ValleyCats\n\nFollow on MiLB First Pitch: https://stza.co/+xXSE-Y\n\nShop: https://stza.co/+xXSE-k\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144459Z
LAST-MODIFIED:20180213T144459Z
TRANSP:OPAQUE
END:VEVENT
* IronBirds vs. ValleyCats
<2018-06-19 Tue 18:05-21:05>
:PROPERTIES:
:ID:       XBrflOyzmA1eVylKVTzOjtvr@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

IronBirds vs. ValleyCats IronBirds vs. ValleyCats

Follow on MiLB First Pitch  https //stza.co/+xXSG-3w

Shop  https //stza.co/+xXSG-30

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:IronBirds vs. ValleyCats
END:VALARM
DTSTART:20180619T230500Z
DTEND:20180620T020500Z
UID:XBrflOyzmA1eVylKVTzOjtvr@stanza.co
SUMMARY:IronBirds vs. ValleyCats
DESCRIPTION:IronBirds vs. ValleyCats\n\nFollow on MiLB First Pitch: https://stza.co/+xXSG-3w\n\nShop: https://stza.co/+xXSG-30\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144459Z
LAST-MODIFIED:20180213T144459Z
TRANSP:OPAQUE
END:VEVENT
* IronBirds vs. ValleyCats
<2018-06-20 Wed 18:05-21:05>
:PROPERTIES:
:ID:       vGP_HdtHEz5xryMQvlxaq92X@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

IronBirds vs. ValleyCats IronBirds vs. ValleyCats

Follow on MiLB First Pitch  https //stza.co/+xXSH-2X

Shop  https //stza.co/+xXSH-34

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:IronBirds vs. ValleyCats
END:VALARM
DTSTART:20180620T230500Z
DTEND:20180621T020500Z
UID:vGP_HdtHEz5xryMQvlxaq92X@stanza.co
SUMMARY:IronBirds vs. ValleyCats
DESCRIPTION:IronBirds vs. ValleyCats\n\nFollow on MiLB First Pitch: https://stza.co/+xXSH-2X\n\nShop: https://stza.co/+xXSH-34\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144459Z
LAST-MODIFIED:20180213T144459Z
TRANSP:OPAQUE
END:VEVENT
* IronBirds @ Yankees
<2018-06-21 Thu>--<2018-06-20 Wed>
:PROPERTIES:
:ID:       6e_mRe719e3ruZh9TRysB0EW@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

IronBirds @ Yankees IronBirds @ Yankees

Follow on MiLB First Pitch  https //stza.co/+xMfe-3d

Shop  https //stza.co/+xMfe-1Q

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:IronBirds @ Yankees
END:VALARM
DTSTART;VALUE=DATE:20180621
DTEND;VALUE=DATE:20180621
UID:6e_mRe719e3ruZh9TRysB0EW@stanza.co
SUMMARY:IronBirds @ Yankees
DESCRIPTION:IronBirds @ Yankees\n\nFollow on MiLB First Pitch: https://stza.co/+xMfe-3d\n\nShop: https://stza.co/+xMfe-1Q\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144459Z
LAST-MODIFIED:20180213T144459Z
TRANSP:OPAQUE
END:VEVENT
* IronBirds @ Yankees
<2018-06-22 Fri>--<2018-06-21 Thu>
:PROPERTIES:
:ID:       8GbPQrQ8Xk0EHJ_ENrWfVzm5@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

IronBirds @ Yankees IronBirds @ Yankees

Follow on MiLB First Pitch  https //stza.co/+xMff-v

Shop  https //stza.co/+xMff-3U

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:IronBirds @ Yankees
END:VALARM
DTSTART;VALUE=DATE:20180622
DTEND;VALUE=DATE:20180622
UID:8GbPQrQ8Xk0EHJ_ENrWfVzm5@stanza.co
SUMMARY:IronBirds @ Yankees
DESCRIPTION:IronBirds @ Yankees\n\nFollow on MiLB First Pitch: https://stza.co/+xMff-v\n\nShop: https://stza.co/+xMff-3U\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144459Z
LAST-MODIFIED:20180213T144459Z
TRANSP:OPAQUE
END:VEVENT
* IronBirds @ Yankees
<2018-06-23 Sat>--<2018-06-22 Fri>
:PROPERTIES:
:ID:       Ew7JdxcnHDXSuTdjIQ2cClX8@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

IronBirds @ Yankees IronBirds @ Yankees

Follow on MiLB First Pitch  https //stza.co/+xMfg-26

Shop  https //stza.co/+xMfg-1Q

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:IronBirds @ Yankees
END:VALARM
DTSTART;VALUE=DATE:20180623
DTEND;VALUE=DATE:20180623
UID:Ew7JdxcnHDXSuTdjIQ2cClX8@stanza.co
SUMMARY:IronBirds @ Yankees
DESCRIPTION:IronBirds @ Yankees\n\nFollow on MiLB First Pitch: https://stza.co/+xMfg-26\n\nShop: https://stza.co/+xMfg-1Q\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144459Z
LAST-MODIFIED:20180213T144459Z
TRANSP:OPAQUE
END:VEVENT
* IronBirds vs. Lake Monsters
<2018-06-24 Sun 15:05-18:05>
:PROPERTIES:
:ID:       UJb14HDaeN91Rjtv8MkhI9nI@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

IronBirds vs. Lake Monsters IronBirds vs. Lake Monsters

Follow on MiLB First Pitch  https //stza.co/+xXSK-1J

Shop  https //stza.co/+xXSK-$

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:IronBirds vs. Lake Monsters
END:VALARM
DTSTART:20180624T200500Z
DTEND:20180624T230500Z
UID:UJb14HDaeN91Rjtv8MkhI9nI@stanza.co
SUMMARY:IronBirds vs. Lake Monsters
DESCRIPTION:IronBirds vs. Lake Monsters\n\nFollow on MiLB First Pitch: https://stza.co/+xXSK-1J\n\nShop: https://stza.co/+xXSK-$\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144459Z
LAST-MODIFIED:20180213T144459Z
TRANSP:OPAQUE
END:VEVENT
* IronBirds vs. Lake Monsters
<2018-06-25 Mon 18:05-21:05>
:PROPERTIES:
:ID:       bpqVnsJjldZ9sAsCagPVXJrV@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

IronBirds vs. Lake Monsters IronBirds vs. Lake Monsters

Follow on MiLB First Pitch  https //stza.co/+xXSM-P

Shop  https //stza.co/+xXSM-v

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:IronBirds vs. Lake Monsters
END:VALARM
DTSTART:20180625T230500Z
DTEND:20180626T020500Z
UID:bpqVnsJjldZ9sAsCagPVXJrV@stanza.co
SUMMARY:IronBirds vs. Lake Monsters
DESCRIPTION:IronBirds vs. Lake Monsters\n\nFollow on MiLB First Pitch: https://stza.co/+xXSM-P\n\nShop: https://stza.co/+xXSM-v\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144459Z
LAST-MODIFIED:20180213T144459Z
TRANSP:OPAQUE
END:VEVENT
* IronBirds vs. Lake Monsters
<2018-06-26 Tue 18:05-21:05>
:PROPERTIES:
:ID:       vGkKoy6pA0-Z70CRZZgIihoS@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

IronBirds vs. Lake Monsters IronBirds vs. Lake Monsters

Follow on MiLB First Pitch  https //stza.co/+xXSN-3W

Shop  https //stza.co/+xXSN-2_

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:IronBirds vs. Lake Monsters
END:VALARM
DTSTART:20180626T230500Z
DTEND:20180627T020500Z
UID:vGkKoy6pA0-Z70CRZZgIihoS@stanza.co
SUMMARY:IronBirds vs. Lake Monsters
DESCRIPTION:IronBirds vs. Lake Monsters\n\nFollow on MiLB First Pitch: https://stza.co/+xXSN-3W\n\nShop: https://stza.co/+xXSN-2_\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144459Z
LAST-MODIFIED:20180213T144459Z
TRANSP:OPAQUE
END:VEVENT
* IronBirds @ Spinners
<2018-06-28 Thu>--<2018-06-27 Wed>
:PROPERTIES:
:ID:       yk-G1vSgoE-iKnwSl9eBqUQH@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

IronBirds @ Spinners IronBirds @ Spinners

Follow on MiLB First Pitch  https //stza.co/+xMf8-2Y

Shop  https //stza.co/+xMf8-1p

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:IronBirds @ Spinners
END:VALARM
DTSTART;VALUE=DATE:20180628
DTEND;VALUE=DATE:20180628
UID:yk-G1vSgoE-iKnwSl9eBqUQH@stanza.co
SUMMARY:IronBirds @ Spinners
DESCRIPTION:IronBirds @ Spinners\n\nFollow on MiLB First Pitch: https://stza.co/+xMf8-2Y\n\nShop: https://stza.co/+xMf8-1p\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144459Z
LAST-MODIFIED:20180213T144459Z
TRANSP:OPAQUE
END:VEVENT
* IronBirds @ Spinners
<2018-06-29 Fri>--<2018-06-28 Thu>
:PROPERTIES:
:ID:       XGeifbXJPL8V0gbGpf4FFzHL@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

IronBirds @ Spinners IronBirds @ Spinners

Follow on MiLB First Pitch  https //stza.co/+xMf9-3H

Shop  https //stza.co/+xMf9-r

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:IronBirds @ Spinners
END:VALARM
DTSTART;VALUE=DATE:20180629
DTEND;VALUE=DATE:20180629
UID:XGeifbXJPL8V0gbGpf4FFzHL@stanza.co
SUMMARY:IronBirds @ Spinners
DESCRIPTION:IronBirds @ Spinners\n\nFollow on MiLB First Pitch: https://stza.co/+xMf9-3H\n\nShop: https://stza.co/+xMf9-r\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144459Z
LAST-MODIFIED:20180213T144459Z
TRANSP:OPAQUE
END:VEVENT
* IronBirds @ Spinners
<2018-06-30 Sat>--<2018-06-29 Fri>
:PROPERTIES:
:ID:       FS-n9P-9sBsaHj_iyMOU1oVr@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

IronBirds @ Spinners IronBirds @ Spinners

Follow on MiLB First Pitch  https //stza.co/+xMfa-D

Shop  https //stza.co/+xMfa-29

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:IronBirds @ Spinners
END:VALARM
DTSTART;VALUE=DATE:20180630
DTEND;VALUE=DATE:20180630
UID:FS-n9P-9sBsaHj_iyMOU1oVr@stanza.co
SUMMARY:IronBirds @ Spinners
DESCRIPTION:IronBirds @ Spinners\n\nFollow on MiLB First Pitch: https://stza.co/+xMfa-D\n\nShop: https://stza.co/+xMfa-29\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144459Z
LAST-MODIFIED:20180213T144459Z
TRANSP:OPAQUE
END:VEVENT
* IronBirds vs. Renegades
<2018-07-01 Sun 15:05-18:05>
:PROPERTIES:
:ID:       OIh0z-5-c163XBPJwvJJ0dM2@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

IronBirds vs. Renegades IronBirds vs. Renegades

Follow on MiLB First Pitch  https //stza.co/+xXSQ-2W

Shop  https //stza.co/+xXSQ-D

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:IronBirds vs. Renegades
END:VALARM
DTSTART:20180701T200500Z
DTEND:20180701T230500Z
UID:OIh0z-5-c163XBPJwvJJ0dM2@stanza.co
SUMMARY:IronBirds vs. Renegades
DESCRIPTION:IronBirds vs. Renegades\n\nFollow on MiLB First Pitch: https://stza.co/+xXSQ-2W\n\nShop: https://stza.co/+xXSQ-D\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144459Z
LAST-MODIFIED:20180213T144459Z
TRANSP:OPAQUE
END:VEVENT
* IronBirds vs. Renegades
<2018-07-02 Mon 18:05-21:05>
:PROPERTIES:
:ID:       ocaI-oO3n57ZDZbf-FTgNYZl@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

IronBirds vs. Renegades IronBirds vs. Renegades

Follow on MiLB First Pitch  https //stza.co/+xXSR-2i

Shop  https //stza.co/+xXSR-3J

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:IronBirds vs. Renegades
END:VALARM
DTSTART:20180702T230500Z
DTEND:20180703T020500Z
UID:ocaI-oO3n57ZDZbf-FTgNYZl@stanza.co
SUMMARY:IronBirds vs. Renegades
DESCRIPTION:IronBirds vs. Renegades\n\nFollow on MiLB First Pitch: https://stza.co/+xXSR-2i\n\nShop: https://stza.co/+xXSR-3J\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144459Z
LAST-MODIFIED:20180213T144459Z
TRANSP:OPAQUE
END:VEVENT
* IronBirds vs. Renegades
<2018-07-03 Tue 18:05-21:05>
:PROPERTIES:
:ID:       Py1c6VYGXgkZXydUq1p6gJyk@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

IronBirds vs. Renegades IronBirds vs. Renegades

Follow on MiLB First Pitch  https //stza.co/+xXST-29

Shop  https //stza.co/+xXST-2v

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:IronBirds vs. Renegades
END:VALARM
DTSTART:20180703T230500Z
DTEND:20180704T020500Z
UID:Py1c6VYGXgkZXydUq1p6gJyk@stanza.co
SUMMARY:IronBirds vs. Renegades
DESCRIPTION:IronBirds vs. Renegades\n\nFollow on MiLB First Pitch: https://stza.co/+xXST-29\n\nShop: https://stza.co/+xXST-2v\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144459Z
LAST-MODIFIED:20180213T144459Z
TRANSP:OPAQUE
END:VEVENT
* IronBirds @ Cyclones
<2018-07-04 Wed>--<2018-07-03 Tue>
:PROPERTIES:
:ID:       RUCX7C097PnzseFJ_mLwtnK6@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

IronBirds @ Cyclones IronBirds @ Cyclones

Follow on MiLB First Pitch  https //stza.co/+xMeW-3S

Shop  https //stza.co/+xMeW-2G

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:IronBirds @ Cyclones
END:VALARM
DTSTART;VALUE=DATE:20180704
DTEND;VALUE=DATE:20180704
UID:RUCX7C097PnzseFJ_mLwtnK6@stanza.co
SUMMARY:IronBirds @ Cyclones
DESCRIPTION:IronBirds @ Cyclones\n\nFollow on MiLB First Pitch: https://stza.co/+xMeW-3S\n\nShop: https://stza.co/+xMeW-2G\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144459Z
LAST-MODIFIED:20180213T144459Z
TRANSP:OPAQUE
END:VEVENT
* IronBirds @ Cyclones
<2018-07-05 Thu>--<2018-07-04 Wed>
:PROPERTIES:
:ID:       U32LoT15ODLUbtmhwN7NNTM1@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

IronBirds @ Cyclones IronBirds @ Cyclones

Follow on MiLB First Pitch  https //stza.co/+xMeX-4

Shop  https //stza.co/+xMeX-1g

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:IronBirds @ Cyclones
END:VALARM
DTSTART;VALUE=DATE:20180705
DTEND;VALUE=DATE:20180705
UID:U32LoT15ODLUbtmhwN7NNTM1@stanza.co
SUMMARY:IronBirds @ Cyclones
DESCRIPTION:IronBirds @ Cyclones\n\nFollow on MiLB First Pitch: https://stza.co/+xMeX-4\n\nShop: https://stza.co/+xMeX-1g\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144459Z
LAST-MODIFIED:20180213T144459Z
TRANSP:OPAQUE
END:VEVENT
* IronBirds @ Cyclones
<2018-07-06 Fri>--<2018-07-05 Thu>
:PROPERTIES:
:ID:       oMG4f7J_xjeZ6-ZlpFlnjTVO@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

IronBirds @ Cyclones IronBirds @ Cyclones

Follow on MiLB First Pitch  https //stza.co/+xMeY-2

Shop  https //stza.co/+xMeY-M

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:IronBirds @ Cyclones
END:VALARM
DTSTART;VALUE=DATE:20180706
DTEND;VALUE=DATE:20180706
UID:oMG4f7J_xjeZ6-ZlpFlnjTVO@stanza.co
SUMMARY:IronBirds @ Cyclones
DESCRIPTION:IronBirds @ Cyclones\n\nFollow on MiLB First Pitch: https://stza.co/+xMeY-2\n\nShop: https://stza.co/+xMeY-M\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144459Z
LAST-MODIFIED:20180213T144459Z
TRANSP:OPAQUE
END:VEVENT
* IronBirds @ ValleyCats
<2018-07-07 Sat>--<2018-07-06 Fri>
:PROPERTIES:
:ID:       vg4fuJRkNDer1gXgM5AM6Wjf@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

IronBirds @ ValleyCats IronBirds @ ValleyCats

Follow on MiLB First Pitch  https //stza.co/+xMfk-v

Shop  https //stza.co/+xMfk-3O

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:IronBirds @ ValleyCats
END:VALARM
DTSTART;VALUE=DATE:20180707
DTEND;VALUE=DATE:20180707
UID:vg4fuJRkNDer1gXgM5AM6Wjf@stanza.co
SUMMARY:IronBirds @ ValleyCats
DESCRIPTION:IronBirds @ ValleyCats\n\nFollow on MiLB First Pitch: https://stza.co/+xMfk-v\n\nShop: https://stza.co/+xMfk-3O\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144459Z
LAST-MODIFIED:20180213T144459Z
TRANSP:OPAQUE
END:VEVENT
* IronBirds @ ValleyCats
<2018-07-08 Sun>--<2018-07-07 Sat>
:PROPERTIES:
:ID:       I0t2zW8JX4PWVsqfKau7-OdZ@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

IronBirds @ ValleyCats IronBirds @ ValleyCats

Follow on MiLB First Pitch  https //stza.co/+xMfl-2

Shop  https //stza.co/+xMfl-3N

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:IronBirds @ ValleyCats
END:VALARM
DTSTART;VALUE=DATE:20180708
DTEND;VALUE=DATE:20180708
UID:I0t2zW8JX4PWVsqfKau7-OdZ@stanza.co
SUMMARY:IronBirds @ ValleyCats
DESCRIPTION:IronBirds @ ValleyCats\n\nFollow on MiLB First Pitch: https://stza.co/+xMfl-2\n\nShop: https://stza.co/+xMfl-3N\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144459Z
LAST-MODIFIED:20180213T144459Z
TRANSP:OPAQUE
END:VEVENT
* IronBirds @ ValleyCats
<2018-07-09 Mon>--<2018-07-08 Sun>
:PROPERTIES:
:ID:       cirmHCbynVQmc8445ufJq-rG@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

IronBirds @ ValleyCats IronBirds @ ValleyCats

Follow on MiLB First Pitch  https //stza.co/+xMfm-e

Shop  https //stza.co/+xMfm-3t

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:IronBirds @ ValleyCats
END:VALARM
DTSTART;VALUE=DATE:20180709
DTEND;VALUE=DATE:20180709
UID:cirmHCbynVQmc8445ufJq-rG@stanza.co
SUMMARY:IronBirds @ ValleyCats
DESCRIPTION:IronBirds @ ValleyCats\n\nFollow on MiLB First Pitch: https://stza.co/+xMfm-e\n\nShop: https://stza.co/+xMfm-3t\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144459Z
LAST-MODIFIED:20180213T144459Z
TRANSP:OPAQUE
END:VEVENT
* IronBirds vs. Cyclones
<2018-07-11 Wed 18:05-21:05>
:PROPERTIES:
:ID:       iiK4inxqWZo96DVKLYbIdt_F@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

IronBirds vs. Cyclones IronBirds vs. Cyclones

Follow on MiLB First Pitch  https //stza.co/+xXSV-_

Shop  https //stza.co/+xXSV-6

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:IronBirds vs. Cyclones
END:VALARM
DTSTART:20180711T230500Z
DTEND:20180712T020500Z
UID:iiK4inxqWZo96DVKLYbIdt_F@stanza.co
SUMMARY:IronBirds vs. Cyclones
DESCRIPTION:IronBirds vs. Cyclones\n\nFollow on MiLB First Pitch: https://stza.co/+xXSV-_\n\nShop: https://stza.co/+xXSV-6\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144459Z
LAST-MODIFIED:20180213T144459Z
TRANSP:OPAQUE
END:VEVENT
* IronBirds vs. Cyclones
<2018-07-12 Thu 18:05-21:05>
:PROPERTIES:
:ID:       aaQ_KzacILcEQxi6875CtX89@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

IronBirds vs. Cyclones IronBirds vs. Cyclones

Follow on MiLB First Pitch  https //stza.co/+xXSX-1U

Shop  https //stza.co/+xXSX-1c

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:IronBirds vs. Cyclones
END:VALARM
DTSTART:20180712T230500Z
DTEND:20180713T020500Z
UID:aaQ_KzacILcEQxi6875CtX89@stanza.co
SUMMARY:IronBirds vs. Cyclones
DESCRIPTION:IronBirds vs. Cyclones\n\nFollow on MiLB First Pitch: https://stza.co/+xXSX-1U\n\nShop: https://stza.co/+xXSX-1c\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144459Z
LAST-MODIFIED:20180213T144459Z
TRANSP:OPAQUE
END:VEVENT
* IronBirds vs. Cyclones
<2018-07-13 Fri 18:05-21:05>
:PROPERTIES:
:ID:       tGH0IDtdgkapoMjGN5RAzecQ@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

IronBirds vs. Cyclones IronBirds vs. Cyclones

Follow on MiLB First Pitch  https //stza.co/+xXSZ-2F

Shop  https //stza.co/+xXSZ-b

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:IronBirds vs. Cyclones
END:VALARM
DTSTART:20180713T230500Z
DTEND:20180714T020500Z
UID:tGH0IDtdgkapoMjGN5RAzecQ@stanza.co
SUMMARY:IronBirds vs. Cyclones
DESCRIPTION:IronBirds vs. Cyclones\n\nFollow on MiLB First Pitch: https://stza.co/+xXSZ-2F\n\nShop: https://stza.co/+xXSZ-b\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144459Z
LAST-MODIFIED:20180213T144459Z
TRANSP:OPAQUE
END:VEVENT
* IronBirds vs. Doubledays
<2018-07-14 Sat 17:05-20:05>
:PROPERTIES:
:ID:       UClxppGg1rB2vAS5d-5Mq4wG@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

IronBirds vs. Doubledays IronBirds vs. Doubledays

Follow on MiLB First Pitch  https //stza.co/+xXT0-13

Shop  https //stza.co/+xXT0-1L

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:IronBirds vs. Doubledays
END:VALARM
DTSTART:20180714T220500Z
DTEND:20180715T010500Z
UID:UClxppGg1rB2vAS5d-5Mq4wG@stanza.co
SUMMARY:IronBirds vs. Doubledays
DESCRIPTION:IronBirds vs. Doubledays\n\nFollow on MiLB First Pitch: https://stza.co/+xXT0-13\n\nShop: https://stza.co/+xXT0-1L\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144459Z
LAST-MODIFIED:20180213T144459Z
TRANSP:OPAQUE
END:VEVENT
* IronBirds vs. Doubledays
<2018-07-15 Sun 15:05-18:05>
:PROPERTIES:
:ID:       K8iB3cnge9S_W3CmFZObrRTQ@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

IronBirds vs. Doubledays IronBirds vs. Doubledays

Follow on MiLB First Pitch  https //stza.co/+xXT2-2t

Shop  https //stza.co/+xXT2-I

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:IronBirds vs. Doubledays
END:VALARM
DTSTART:20180715T200500Z
DTEND:20180715T230500Z
UID:K8iB3cnge9S_W3CmFZObrRTQ@stanza.co
SUMMARY:IronBirds vs. Doubledays
DESCRIPTION:IronBirds vs. Doubledays\n\nFollow on MiLB First Pitch: https://stza.co/+xXT2-2t\n\nShop: https://stza.co/+xXT2-I\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144459Z
LAST-MODIFIED:20180213T144459Z
TRANSP:OPAQUE
END:VEVENT
* IronBirds vs. Doubledays
<2018-07-16 Mon 10:05-13:05>
:PROPERTIES:
:ID:       2VBTzN3aCAD5ZG1_77Lp9IsR@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

IronBirds vs. Doubledays IronBirds vs. Doubledays

Follow on MiLB First Pitch  https //stza.co/+xXT5-F

Shop  https //stza.co/+xXT5-2B

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:IronBirds vs. Doubledays
END:VALARM
DTSTART:20180716T150500Z
DTEND:20180716T180500Z
UID:2VBTzN3aCAD5ZG1_77Lp9IsR@stanza.co
SUMMARY:IronBirds vs. Doubledays
DESCRIPTION:IronBirds vs. Doubledays\n\nFollow on MiLB First Pitch: https://stza.co/+xXT5-F\n\nShop: https://stza.co/+xXT5-2B\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144459Z
LAST-MODIFIED:20180213T144459Z
TRANSP:OPAQUE
END:VEVENT
* IronBirds @ Spinners
<2018-07-17 Tue>--<2018-07-16 Mon>
:PROPERTIES:
:ID:       QkSJEo0FeBrMoh2ZzzI3G4Wv@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

IronBirds @ Spinners IronBirds @ Spinners

Follow on MiLB First Pitch  https //stza.co/+xMfb-2Z

Shop  https //stza.co/+xMfb-W

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:IronBirds @ Spinners
END:VALARM
DTSTART;VALUE=DATE:20180717
DTEND;VALUE=DATE:20180717
UID:QkSJEo0FeBrMoh2ZzzI3G4Wv@stanza.co
SUMMARY:IronBirds @ Spinners
DESCRIPTION:IronBirds @ Spinners\n\nFollow on MiLB First Pitch: https://stza.co/+xMfb-2Z\n\nShop: https://stza.co/+xMfb-W\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144459Z
LAST-MODIFIED:20180213T144459Z
TRANSP:OPAQUE
END:VEVENT
* IronBirds @ Spinners
<2018-07-18 Wed>--<2018-07-17 Tue>
:PROPERTIES:
:ID:       cOKbWX-iu9LPS4Pp9IAbfmNy@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

IronBirds @ Spinners IronBirds @ Spinners

Follow on MiLB First Pitch  https //stza.co/+xMfc-2O

Shop  https //stza.co/+xMfc-2b

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:IronBirds @ Spinners
END:VALARM
DTSTART;VALUE=DATE:20180718
DTEND;VALUE=DATE:20180718
UID:cOKbWX-iu9LPS4Pp9IAbfmNy@stanza.co
SUMMARY:IronBirds @ Spinners
DESCRIPTION:IronBirds @ Spinners\n\nFollow on MiLB First Pitch: https://stza.co/+xMfc-2O\n\nShop: https://stza.co/+xMfc-2b\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144459Z
LAST-MODIFIED:20180213T144459Z
TRANSP:OPAQUE
END:VEVENT
* IronBirds @ Spinners
<2018-07-19 Thu>--<2018-07-18 Wed>
:PROPERTIES:
:ID:       5qrlvqK-tj6_V7WSwnDRmEdK@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

IronBirds @ Spinners IronBirds @ Spinners

Follow on MiLB First Pitch  https //stza.co/+xMfd-3p

Shop  https //stza.co/+xMfd-2X

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:IronBirds @ Spinners
END:VALARM
DTSTART;VALUE=DATE:20180719
DTEND;VALUE=DATE:20180719
UID:5qrlvqK-tj6_V7WSwnDRmEdK@stanza.co
SUMMARY:IronBirds @ Spinners
DESCRIPTION:IronBirds @ Spinners\n\nFollow on MiLB First Pitch: https://stza.co/+xMfd-3p\n\nShop: https://stza.co/+xMfd-2X\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144459Z
LAST-MODIFIED:20180213T144459Z
TRANSP:OPAQUE
END:VEVENT
* IronBirds vs. Tigers
<2018-07-20 Fri 18:05-21:05>
:PROPERTIES:
:ID:       kVH0SdAj0bM9Dnxp5a141C06@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

IronBirds vs. Tigers IronBirds vs. Tigers

Follow on MiLB First Pitch  https //stza.co/+xXT6-2k

Shop  https //stza.co/+xXT6-1o

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:IronBirds vs. Tigers
END:VALARM
DTSTART:20180720T230500Z
DTEND:20180721T020500Z
UID:kVH0SdAj0bM9Dnxp5a141C06@stanza.co
SUMMARY:IronBirds vs. Tigers
DESCRIPTION:IronBirds vs. Tigers\n\nFollow on MiLB First Pitch: https://stza.co/+xXT6-2k\n\nShop: https://stza.co/+xXT6-1o\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144459Z
LAST-MODIFIED:20180213T144459Z
TRANSP:OPAQUE
END:VEVENT
* IronBirds vs. Tigers
<2018-07-21 Sat 17:05-20:05>
:PROPERTIES:
:ID:       HpMuFNui7QJ6BcQqZh9Tw-kh@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

IronBirds vs. Tigers IronBirds vs. Tigers

Follow on MiLB First Pitch  https //stza.co/+xXT9-2U

Shop  https //stza.co/+xXT9-2N

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:IronBirds vs. Tigers
END:VALARM
DTSTART:20180721T220500Z
DTEND:20180722T010500Z
UID:HpMuFNui7QJ6BcQqZh9Tw-kh@stanza.co
SUMMARY:IronBirds vs. Tigers
DESCRIPTION:IronBirds vs. Tigers\n\nFollow on MiLB First Pitch: https://stza.co/+xXT9-2U\n\nShop: https://stza.co/+xXT9-2N\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144459Z
LAST-MODIFIED:20180213T144459Z
TRANSP:OPAQUE
END:VEVENT
* IronBirds vs. Tigers
<2018-07-22 Sun 15:05-18:05>
:PROPERTIES:
:ID:       -OVpyguIt0OTu6oASa5iYPtV@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

IronBirds vs. Tigers IronBirds vs. Tigers

Follow on MiLB First Pitch  https //stza.co/+xXTa-39

Shop  https //stza.co/+xXTa-1N

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:IronBirds vs. Tigers
END:VALARM
DTSTART:20180722T200500Z
DTEND:20180722T230500Z
UID:-OVpyguIt0OTu6oASa5iYPtV@stanza.co
SUMMARY:IronBirds vs. Tigers
DESCRIPTION:IronBirds vs. Tigers\n\nFollow on MiLB First Pitch: https://stza.co/+xXTa-39\n\nShop: https://stza.co/+xXTa-1N\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144459Z
LAST-MODIFIED:20180213T144459Z
TRANSP:OPAQUE
END:VEVENT
* IronBirds @ Black Bears
<2018-07-24 Tue 18:05-21:05>
:PROPERTIES:
:ID:       qUQhBc-aBEQ2E3l75GaBQoe_@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

IronBirds @ Black Bears IronBirds @ Black Bears

Follow on MiLB First Pitch  https //stza.co/+xVYQ-n

Shop  https //stza.co/+xVYQ-V

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:IronBirds @ Black Bears
END:VALARM
DTSTART:20180724T230500Z
DTEND:20180725T020500Z
UID:qUQhBc-aBEQ2E3l75GaBQoe_@stanza.co
SUMMARY:IronBirds @ Black Bears
DESCRIPTION:IronBirds @ Black Bears\n\nFollow on MiLB First Pitch: https://stza.co/+xVYQ-n\n\nShop: https://stza.co/+xVYQ-V\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144459Z
LAST-MODIFIED:20180213T144459Z
TRANSP:OPAQUE
END:VEVENT
* IronBirds @ Black Bears
<2018-07-25 Wed 18:05-21:05>
:PROPERTIES:
:ID:       j-Jq10i_1eBYqECLN2DqrYNC@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

IronBirds @ Black Bears IronBirds @ Black Bears

Follow on MiLB First Pitch  https //stza.co/+xVYR-3W

Shop  https //stza.co/+xVYR-2B

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:IronBirds @ Black Bears
END:VALARM
DTSTART:20180725T230500Z
DTEND:20180726T020500Z
UID:j-Jq10i_1eBYqECLN2DqrYNC@stanza.co
SUMMARY:IronBirds @ Black Bears
DESCRIPTION:IronBirds @ Black Bears\n\nFollow on MiLB First Pitch: https://stza.co/+xVYR-3W\n\nShop: https://stza.co/+xVYR-2B\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144459Z
LAST-MODIFIED:20180213T144459Z
TRANSP:OPAQUE
END:VEVENT
* IronBirds @ Black Bears
<2018-07-26 Thu 18:05-21:05>
:PROPERTIES:
:ID:       QyIri6vUP5R9jDh0W5u863ig@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

IronBirds @ Black Bears IronBirds @ Black Bears

Follow on MiLB First Pitch  https //stza.co/+xVYS-3P

Shop  https //stza.co/+xVYS-3T

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:IronBirds @ Black Bears
END:VALARM
DTSTART:20180726T230500Z
DTEND:20180727T020500Z
UID:QyIri6vUP5R9jDh0W5u863ig@stanza.co
SUMMARY:IronBirds @ Black Bears
DESCRIPTION:IronBirds @ Black Bears\n\nFollow on MiLB First Pitch: https://stza.co/+xVYS-3P\n\nShop: https://stza.co/+xVYS-3T\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144459Z
LAST-MODIFIED:20180213T144459Z
TRANSP:OPAQUE
END:VEVENT
* IronBirds vs. Scrappers
<2018-07-27 Fri 18:05-21:05>
:PROPERTIES:
:ID:       uoB5kOw9GAAP_31kfSkV098Z@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

IronBirds vs. Scrappers IronBirds vs. Scrappers

Follow on MiLB First Pitch  https //stza.co/+xXTd-h

Shop  https //stza.co/+xXTd-1y

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:IronBirds vs. Scrappers
END:VALARM
DTSTART:20180727T230500Z
DTEND:20180728T020500Z
UID:uoB5kOw9GAAP_31kfSkV098Z@stanza.co
SUMMARY:IronBirds vs. Scrappers
DESCRIPTION:IronBirds vs. Scrappers\n\nFollow on MiLB First Pitch: https://stza.co/+xXTd-h\n\nShop: https://stza.co/+xXTd-1y\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144459Z
LAST-MODIFIED:20180213T144459Z
TRANSP:OPAQUE
END:VEVENT
* IronBirds vs. Scrappers
<2018-07-28 Sat 17:05-20:05>
:PROPERTIES:
:ID:       UgFjWrBSxLHldsMvoHaA1tAj@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

IronBirds vs. Scrappers IronBirds vs. Scrappers

Follow on MiLB First Pitch  https //stza.co/+xXTe-10

Shop  https //stza.co/+xXTe-16

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:IronBirds vs. Scrappers
END:VALARM
DTSTART:20180728T220500Z
DTEND:20180729T010500Z
UID:UgFjWrBSxLHldsMvoHaA1tAj@stanza.co
SUMMARY:IronBirds vs. Scrappers
DESCRIPTION:IronBirds vs. Scrappers\n\nFollow on MiLB First Pitch: https://stza.co/+xXTe-10\n\nShop: https://stza.co/+xXTe-16\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144459Z
LAST-MODIFIED:20180213T144459Z
TRANSP:OPAQUE
END:VEVENT
* IronBirds vs. Scrappers
<2018-07-29 Sun 15:05-18:05>
:PROPERTIES:
:ID:       wsVX4adgX6el7xhbDMZIOYZh@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

IronBirds vs. Scrappers IronBirds vs. Scrappers

Follow on MiLB First Pitch  https //stza.co/+xXTh-P

Shop  https //stza.co/+xXTh-36

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:IronBirds vs. Scrappers
END:VALARM
DTSTART:20180729T200500Z
DTEND:20180729T230500Z
UID:wsVX4adgX6el7xhbDMZIOYZh@stanza.co
SUMMARY:IronBirds vs. Scrappers
DESCRIPTION:IronBirds vs. Scrappers\n\nFollow on MiLB First Pitch: https://stza.co/+xXTh-P\n\nShop: https://stza.co/+xXTh-36\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144459Z
LAST-MODIFIED:20180213T144459Z
TRANSP:OPAQUE
END:VEVENT
* IronBirds @ Yankees
<2018-07-30 Mon>--<2018-07-29 Sun>
:PROPERTIES:
:ID:       HbyjBFVjO9l3YnbCVO1RhOVX@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

IronBirds @ Yankees IronBirds @ Yankees

Follow on MiLB First Pitch  https //stza.co/+xMfh-2x

Shop  https //stza.co/+xMfh-2C

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:IronBirds @ Yankees
END:VALARM
DTSTART;VALUE=DATE:20180730
DTEND;VALUE=DATE:20180730
UID:HbyjBFVjO9l3YnbCVO1RhOVX@stanza.co
SUMMARY:IronBirds @ Yankees
DESCRIPTION:IronBirds @ Yankees\n\nFollow on MiLB First Pitch: https://stza.co/+xMfh-2x\n\nShop: https://stza.co/+xMfh-2C\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144459Z
LAST-MODIFIED:20180213T144459Z
TRANSP:OPAQUE
END:VEVENT
* IronBirds @ Yankees
<2018-07-31 Tue>--<2018-07-30 Mon>
:PROPERTIES:
:ID:       wiyTzzmilb_KoXzkVvAvgGEs@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

IronBirds @ Yankees IronBirds @ Yankees

Follow on MiLB First Pitch  https //stza.co/+xMfi-3G

Shop  https //stza.co/+xMfi-3p

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:IronBirds @ Yankees
END:VALARM
DTSTART;VALUE=DATE:20180731
DTEND;VALUE=DATE:20180731
UID:wiyTzzmilb_KoXzkVvAvgGEs@stanza.co
SUMMARY:IronBirds @ Yankees
DESCRIPTION:IronBirds @ Yankees\n\nFollow on MiLB First Pitch: https://stza.co/+xMfi-3G\n\nShop: https://stza.co/+xMfi-3p\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144459Z
LAST-MODIFIED:20180213T144459Z
TRANSP:OPAQUE
END:VEVENT
* IronBirds @ Yankees
<2018-08-01 Wed>--<2018-07-31 Tue>
:PROPERTIES:
:ID:       GPSD-XLyosqjt5Tco3GX_Fkd@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

IronBirds @ Yankees IronBirds @ Yankees

Follow on MiLB First Pitch  https //stza.co/+xMfj-1p

Shop  https //stza.co/+xMfj-1F

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:IronBirds @ Yankees
END:VALARM
DTSTART;VALUE=DATE:20180801
DTEND;VALUE=DATE:20180801
UID:GPSD-XLyosqjt5Tco3GX_Fkd@stanza.co
SUMMARY:IronBirds @ Yankees
DESCRIPTION:IronBirds @ Yankees\n\nFollow on MiLB First Pitch: https://stza.co/+xMfj-1p\n\nShop: https://stza.co/+xMfj-1F\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144459Z
LAST-MODIFIED:20180213T144459Z
TRANSP:OPAQUE
END:VEVENT
* IronBirds @ Cyclones
<2018-08-02 Thu>--<2018-08-01 Wed>
:PROPERTIES:
:ID:       syo2VHb7o74KjhX-dnvdwXJx@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

IronBirds @ Cyclones IronBirds @ Cyclones

Follow on MiLB First Pitch  https //stza.co/+xMeZ-2D

Shop  https //stza.co/+xMeZ-21

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:IronBirds @ Cyclones
END:VALARM
DTSTART;VALUE=DATE:20180802
DTEND;VALUE=DATE:20180802
UID:syo2VHb7o74KjhX-dnvdwXJx@stanza.co
SUMMARY:IronBirds @ Cyclones
DESCRIPTION:IronBirds @ Cyclones\n\nFollow on MiLB First Pitch: https://stza.co/+xMeZ-2D\n\nShop: https://stza.co/+xMeZ-21\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144459Z
LAST-MODIFIED:20180213T144459Z
TRANSP:OPAQUE
END:VEVENT
* IronBirds @ Cyclones
<2018-08-03 Fri>--<2018-08-02 Thu>
:PROPERTIES:
:ID:       QBjVnlHCSZr2jWGruK_bmDHz@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

IronBirds @ Cyclones IronBirds @ Cyclones

Follow on MiLB First Pitch  https //stza.co/+xMe_-1O

Shop  https //stza.co/+xMe_-1H

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:IronBirds @ Cyclones
END:VALARM
DTSTART;VALUE=DATE:20180803
DTEND;VALUE=DATE:20180803
UID:QBjVnlHCSZr2jWGruK_bmDHz@stanza.co
SUMMARY:IronBirds @ Cyclones
DESCRIPTION:IronBirds @ Cyclones\n\nFollow on MiLB First Pitch: https://stza.co/+xMe_-1O\n\nShop: https://stza.co/+xMe_-1H\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144459Z
LAST-MODIFIED:20180213T144459Z
TRANSP:OPAQUE
END:VEVENT
* IronBirds @ Cyclones
<2018-08-04 Sat>--<2018-08-03 Fri>
:PROPERTIES:
:ID:       siaXIAKHSetdo4t5hQ9Jz2yo@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

IronBirds @ Cyclones IronBirds @ Cyclones

Follow on MiLB First Pitch  https //stza.co/+xMe$-2N

Shop  https //stza.co/+xMe$-2G

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:IronBirds @ Cyclones
END:VALARM
DTSTART;VALUE=DATE:20180804
DTEND;VALUE=DATE:20180804
UID:siaXIAKHSetdo4t5hQ9Jz2yo@stanza.co
SUMMARY:IronBirds @ Cyclones
DESCRIPTION:IronBirds @ Cyclones\n\nFollow on MiLB First Pitch: https://stza.co/+xMe$-2N\n\nShop: https://stza.co/+xMe$-2G\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144459Z
LAST-MODIFIED:20180213T144459Z
TRANSP:OPAQUE
END:VEVENT
* IronBirds vs. Yankees
<2018-08-05 Sun 15:05-18:05>
:PROPERTIES:
:ID:       D8FrSg2140QcqEn35DcZREgl@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

IronBirds vs. Yankees IronBirds vs. Yankees

Follow on MiLB First Pitch  https //stza.co/+xXTj-K

Shop  https //stza.co/+xXTj-1l

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:IronBirds vs. Yankees
END:VALARM
DTSTART:20180805T200500Z
DTEND:20180805T230500Z
UID:D8FrSg2140QcqEn35DcZREgl@stanza.co
SUMMARY:IronBirds vs. Yankees
DESCRIPTION:IronBirds vs. Yankees\n\nFollow on MiLB First Pitch: https://stza.co/+xXTj-K\n\nShop: https://stza.co/+xXTj-1l\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144459Z
LAST-MODIFIED:20180213T144459Z
TRANSP:OPAQUE
END:VEVENT
* IronBirds vs. Yankees
<2018-08-06 Mon 18:05-21:05>
:PROPERTIES:
:ID:       CYMf5p2m8yuW4hc7udBdnPjK@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

IronBirds vs. Yankees IronBirds vs. Yankees

Follow on MiLB First Pitch  https //stza.co/+xXTk-3q

Shop  https //stza.co/+xXTk-i

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:IronBirds vs. Yankees
END:VALARM
DTSTART:20180806T230500Z
DTEND:20180807T020500Z
UID:CYMf5p2m8yuW4hc7udBdnPjK@stanza.co
SUMMARY:IronBirds vs. Yankees
DESCRIPTION:IronBirds vs. Yankees\n\nFollow on MiLB First Pitch: https://stza.co/+xXTk-3q\n\nShop: https://stza.co/+xXTk-i\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144459Z
LAST-MODIFIED:20180213T144459Z
TRANSP:OPAQUE
END:VEVENT
* IronBirds vs. Yankees
<2018-08-07 Tue 18:05-21:05>
:PROPERTIES:
:ID:       AnGV2tzlsAx-AUE77AbKsOhk@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

IronBirds vs. Yankees IronBirds vs. Yankees

Follow on MiLB First Pitch  https //stza.co/+xXTn-1c

Shop  https //stza.co/+xXTn-1t

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:IronBirds vs. Yankees
END:VALARM
DTSTART:20180807T230500Z
DTEND:20180808T020500Z
UID:AnGV2tzlsAx-AUE77AbKsOhk@stanza.co
SUMMARY:IronBirds vs. Yankees
DESCRIPTION:IronBirds vs. Yankees\n\nFollow on MiLB First Pitch: https://stza.co/+xXTn-1c\n\nShop: https://stza.co/+xXTn-1t\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144459Z
LAST-MODIFIED:20180213T144459Z
TRANSP:OPAQUE
END:VEVENT
* IronBirds vs. Lake Monsters
<2018-08-08 Wed 18:05-21:05>
:PROPERTIES:
:ID:       VFCHhCmxxJO5aD4cjynfeHUV@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

IronBirds vs. Lake Monsters IronBirds vs. Lake Monsters

Follow on MiLB First Pitch  https //stza.co/+xXTp-34

Shop  https //stza.co/+xXTp-1r

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:IronBirds vs. Lake Monsters
END:VALARM
DTSTART:20180808T230500Z
DTEND:20180809T020500Z
UID:VFCHhCmxxJO5aD4cjynfeHUV@stanza.co
SUMMARY:IronBirds vs. Lake Monsters
DESCRIPTION:IronBirds vs. Lake Monsters\n\nFollow on MiLB First Pitch: https://stza.co/+xXTp-34\n\nShop: https://stza.co/+xXTp-1r\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144459Z
LAST-MODIFIED:20180213T144459Z
TRANSP:OPAQUE
END:VEVENT
* IronBirds vs. Lake Monsters
<2018-08-09 Thu 18:05-21:05>
:PROPERTIES:
:ID:       8mfBVfaY0uBBky_VzvmkoT6m@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

IronBirds vs. Lake Monsters IronBirds vs. Lake Monsters

Follow on MiLB First Pitch  https //stza.co/+xXTq-w

Shop  https //stza.co/+xXTq-3m

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:IronBirds vs. Lake Monsters
END:VALARM
DTSTART:20180809T230500Z
DTEND:20180810T020500Z
UID:8mfBVfaY0uBBky_VzvmkoT6m@stanza.co
SUMMARY:IronBirds vs. Lake Monsters
DESCRIPTION:IronBirds vs. Lake Monsters\n\nFollow on MiLB First Pitch: https://stza.co/+xXTq-w\n\nShop: https://stza.co/+xXTq-3m\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144459Z
LAST-MODIFIED:20180213T144459Z
TRANSP:OPAQUE
END:VEVENT
* IronBirds vs. Lake Monsters
<2018-08-10 Fri 18:05-21:05>
:PROPERTIES:
:ID:       iVNr6vsR-9b83Ozzlzp8yPHL@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

IronBirds vs. Lake Monsters IronBirds vs. Lake Monsters

Follow on MiLB First Pitch  https //stza.co/+xXTt-a

Shop  https //stza.co/+xXTt-10

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:IronBirds vs. Lake Monsters
END:VALARM
DTSTART:20180810T230500Z
DTEND:20180811T020500Z
UID:iVNr6vsR-9b83Ozzlzp8yPHL@stanza.co
SUMMARY:IronBirds vs. Lake Monsters
DESCRIPTION:IronBirds vs. Lake Monsters\n\nFollow on MiLB First Pitch: https://stza.co/+xXTt-a\n\nShop: https://stza.co/+xXTt-10\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144459Z
LAST-MODIFIED:20180213T144459Z
TRANSP:OPAQUE
END:VEVENT
* IronBirds @ Renegades
<2018-08-11 Sat 17:05-20:05>
:PROPERTIES:
:ID:       iP9EFe04NdcuJu_7CkYsQF6i@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

IronBirds @ Renegades IronBirds @ Renegades

Follow on MiLB First Pitch  https //stza.co/+xVYL-37

Shop  https //stza.co/+xVYL-1l

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:IronBirds @ Renegades
END:VALARM
DTSTART:20180811T220500Z
DTEND:20180812T010500Z
UID:iP9EFe04NdcuJu_7CkYsQF6i@stanza.co
SUMMARY:IronBirds @ Renegades
DESCRIPTION:IronBirds @ Renegades\n\nFollow on MiLB First Pitch: https://stza.co/+xVYL-37\n\nShop: https://stza.co/+xVYL-1l\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144459Z
LAST-MODIFIED:20180213T144459Z
TRANSP:OPAQUE
END:VEVENT
* IronBirds @ Renegades
<2018-08-12 Sun 16:05-19:05>
:PROPERTIES:
:ID:       jHlZF_w-VHpQAjpuWTt-JSO_@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

IronBirds @ Renegades IronBirds @ Renegades

Follow on MiLB First Pitch  https //stza.co/+xVYM-27

Shop  https //stza.co/+xVYM-2G

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:IronBirds @ Renegades
END:VALARM
DTSTART:20180812T210500Z
DTEND:20180813T000500Z
UID:jHlZF_w-VHpQAjpuWTt-JSO_@stanza.co
SUMMARY:IronBirds @ Renegades
DESCRIPTION:IronBirds @ Renegades\n\nFollow on MiLB First Pitch: https://stza.co/+xVYM-27\n\nShop: https://stza.co/+xVYM-2G\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144459Z
LAST-MODIFIED:20180213T144459Z
TRANSP:OPAQUE
END:VEVENT
* IronBirds vs. Spinners
<2018-08-15 Wed 18:05-21:05>
:PROPERTIES:
:ID:       XFf8nQtIwh8rva2dRLQb90vO@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

IronBirds vs. Spinners IronBirds vs. Spinners

Follow on MiLB First Pitch  https //stza.co/+xXTu-3O

Shop  https //stza.co/+xXTu-2a

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:IronBirds vs. Spinners
END:VALARM
DTSTART:20180815T230500Z
DTEND:20180816T020500Z
UID:XFf8nQtIwh8rva2dRLQb90vO@stanza.co
SUMMARY:IronBirds vs. Spinners
DESCRIPTION:IronBirds vs. Spinners\n\nFollow on MiLB First Pitch: https://stza.co/+xXTu-3O\n\nShop: https://stza.co/+xXTu-2a\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144459Z
LAST-MODIFIED:20180213T144459Z
TRANSP:OPAQUE
END:VEVENT
* IronBirds vs. Spinners
<2018-08-16 Thu 18:05-21:05>
:PROPERTIES:
:ID:       OBbXMV0TvFXyEXI74o1maX44@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

IronBirds vs. Spinners IronBirds vs. Spinners

Follow on MiLB First Pitch  https //stza.co/+xXTw-1U

Shop  https //stza.co/+xXTw-18

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:IronBirds vs. Spinners
END:VALARM
DTSTART:20180816T230500Z
DTEND:20180817T020500Z
UID:OBbXMV0TvFXyEXI74o1maX44@stanza.co
SUMMARY:IronBirds vs. Spinners
DESCRIPTION:IronBirds vs. Spinners\n\nFollow on MiLB First Pitch: https://stza.co/+xXTw-1U\n\nShop: https://stza.co/+xXTw-18\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144459Z
LAST-MODIFIED:20180213T144459Z
TRANSP:OPAQUE
END:VEVENT
* IronBirds @ Tigers
<2018-08-17 Fri>--<2018-08-16 Thu>
:PROPERTIES:
:ID:       z09UcGq4YukEcqQZx9GXmxwH@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

IronBirds @ Tigers IronBirds @ Tigers

Follow on MiLB First Pitch  https //stza.co/+xMf0-1C

Shop  https //stza.co/+xMf0-1l

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:IronBirds @ Tigers
END:VALARM
DTSTART;VALUE=DATE:20180817
DTEND;VALUE=DATE:20180817
UID:z09UcGq4YukEcqQZx9GXmxwH@stanza.co
SUMMARY:IronBirds @ Tigers
DESCRIPTION:IronBirds @ Tigers\n\nFollow on MiLB First Pitch: https://stza.co/+xMf0-1C\n\nShop: https://stza.co/+xMf0-1l\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144459Z
LAST-MODIFIED:20180213T144459Z
TRANSP:OPAQUE
END:VEVENT
* IronBirds @ Tigers
<2018-08-18 Sat>--<2018-08-17 Fri>
:PROPERTIES:
:ID:       YxfKpigY14gMqEmxFYI1EvLQ@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

IronBirds @ Tigers IronBirds @ Tigers

Follow on MiLB First Pitch  https //stza.co/+xMf1-1$

Shop  https //stza.co/+xMf1-2f

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:IronBirds @ Tigers
END:VALARM
DTSTART;VALUE=DATE:20180818
DTEND;VALUE=DATE:20180818
UID:YxfKpigY14gMqEmxFYI1EvLQ@stanza.co
SUMMARY:IronBirds @ Tigers
DESCRIPTION:IronBirds @ Tigers\n\nFollow on MiLB First Pitch: https://stza.co/+xMf1-1$\n\nShop: https://stza.co/+xMf1-2f\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144459Z
LAST-MODIFIED:20180213T144459Z
TRANSP:OPAQUE
END:VEVENT
* IronBirds @ Tigers
<2018-08-19 Sun>--<2018-08-18 Sat>
:PROPERTIES:
:ID:       GPwGZt6mu9A9702ckxlMdnt6@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

IronBirds @ Tigers IronBirds @ Tigers

Follow on MiLB First Pitch  https //stza.co/+xMf2-3W

Shop  https //stza.co/+xMf2-n

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:IronBirds @ Tigers
END:VALARM
DTSTART;VALUE=DATE:20180819
DTEND;VALUE=DATE:20180819
UID:GPwGZt6mu9A9702ckxlMdnt6@stanza.co
SUMMARY:IronBirds @ Tigers
DESCRIPTION:IronBirds @ Tigers\n\nFollow on MiLB First Pitch: https://stza.co/+xMf2-3W\n\nShop: https://stza.co/+xMf2-n\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144459Z
LAST-MODIFIED:20180213T144459Z
TRANSP:OPAQUE
END:VEVENT
* IronBirds @ Lake Monsters
<2018-08-20 Mon>--<2018-08-19 Sun>
:PROPERTIES:
:ID:       zXB_WvqgosB0QoyfWW31Eogq@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

IronBirds @ Lake Monsters IronBirds @ Lake Monsters

Follow on MiLB First Pitch  https //stza.co/+xMfq-v

Shop  https //stza.co/+xMfq-3J

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:IronBirds @ Lake Monsters
END:VALARM
DTSTART;VALUE=DATE:20180820
DTEND;VALUE=DATE:20180820
UID:zXB_WvqgosB0QoyfWW31Eogq@stanza.co
SUMMARY:IronBirds @ Lake Monsters
DESCRIPTION:IronBirds @ Lake Monsters\n\nFollow on MiLB First Pitch: https://stza.co/+xMfq-v\n\nShop: https://stza.co/+xMfq-3J\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144459Z
LAST-MODIFIED:20180213T144459Z
TRANSP:OPAQUE
END:VEVENT
* IronBirds @ Lake Monsters
<2018-08-21 Tue>--<2018-08-20 Mon>
:PROPERTIES:
:ID:       QmLvD7gsFbPpDE2etwz7lUB3@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

IronBirds @ Lake Monsters IronBirds @ Lake Monsters

Follow on MiLB First Pitch  https //stza.co/+xMfr-k

Shop  https //stza.co/+xMfr-2v

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:IronBirds @ Lake Monsters
END:VALARM
DTSTART;VALUE=DATE:20180821
DTEND;VALUE=DATE:20180821
UID:QmLvD7gsFbPpDE2etwz7lUB3@stanza.co
SUMMARY:IronBirds @ Lake Monsters
DESCRIPTION:IronBirds @ Lake Monsters\n\nFollow on MiLB First Pitch: https://stza.co/+xMfr-k\n\nShop: https://stza.co/+xMfr-2v\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144459Z
LAST-MODIFIED:20180213T144459Z
TRANSP:OPAQUE
END:VEVENT
* IronBirds @ Lake Monsters
<2018-08-22 Wed>--<2018-08-21 Tue>
:PROPERTIES:
:ID:       sP5kdFA3Ly29uKULgALBMox4@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

IronBirds @ Lake Monsters IronBirds @ Lake Monsters

Follow on MiLB First Pitch  https //stza.co/+xMfs-G

Shop  https //stza.co/+xMfs-23

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:IronBirds @ Lake Monsters
END:VALARM
DTSTART;VALUE=DATE:20180822
DTEND;VALUE=DATE:20180822
UID:sP5kdFA3Ly29uKULgALBMox4@stanza.co
SUMMARY:IronBirds @ Lake Monsters
DESCRIPTION:IronBirds @ Lake Monsters\n\nFollow on MiLB First Pitch: https://stza.co/+xMfs-G\n\nShop: https://stza.co/+xMfs-23\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144459Z
LAST-MODIFIED:20180213T144459Z
TRANSP:OPAQUE
END:VEVENT
* IronBirds vs. Yankees
<2018-08-23 Thu 18:05-21:05>
:PROPERTIES:
:ID:       ey8B6pO5F03Ubb_DfCXjQ2-y@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

IronBirds vs. Yankees IronBirds vs. Yankees

Follow on MiLB First Pitch  https //stza.co/+xXTz-k

Shop  https //stza.co/+xXTz-3s

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:IronBirds vs. Yankees
END:VALARM
DTSTART:20180823T230500Z
DTEND:20180824T020500Z
UID:ey8B6pO5F03Ubb_DfCXjQ2-y@stanza.co
SUMMARY:IronBirds vs. Yankees
DESCRIPTION:IronBirds vs. Yankees\n\nFollow on MiLB First Pitch: https://stza.co/+xXTz-k\n\nShop: https://stza.co/+xXTz-3s\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144459Z
LAST-MODIFIED:20180213T144459Z
TRANSP:OPAQUE
END:VEVENT
* IronBirds vs. Yankees
<2018-08-24 Fri 18:05-21:05>
:PROPERTIES:
:ID:       ZSCdh863Vuo2I7rQ-ZFo2hDo@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

IronBirds vs. Yankees IronBirds vs. Yankees

Follow on MiLB First Pitch  https //stza.co/+xXTA-1a

Shop  https //stza.co/+xXTA-2v

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:IronBirds vs. Yankees
END:VALARM
DTSTART:20180824T230500Z
DTEND:20180825T020500Z
UID:ZSCdh863Vuo2I7rQ-ZFo2hDo@stanza.co
SUMMARY:IronBirds vs. Yankees
DESCRIPTION:IronBirds vs. Yankees\n\nFollow on MiLB First Pitch: https://stza.co/+xXTA-1a\n\nShop: https://stza.co/+xXTA-2v\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144459Z
LAST-MODIFIED:20180213T144459Z
TRANSP:OPAQUE
END:VEVENT
* IronBirds vs. Yankees
<2018-08-25 Sat 17:05-20:05>
:PROPERTIES:
:ID:       MRQSRQGmd7Yaxuc3lAnOyVN9@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

IronBirds vs. Yankees IronBirds vs. Yankees

Follow on MiLB First Pitch  https //stza.co/+xXTC-2y

Shop  https //stza.co/+xXTC-2w

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:IronBirds vs. Yankees
END:VALARM
DTSTART:20180825T220500Z
DTEND:20180826T010500Z
UID:MRQSRQGmd7Yaxuc3lAnOyVN9@stanza.co
SUMMARY:IronBirds vs. Yankees
DESCRIPTION:IronBirds vs. Yankees\n\nFollow on MiLB First Pitch: https://stza.co/+xXTC-2y\n\nShop: https://stza.co/+xXTC-2w\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144459Z
LAST-MODIFIED:20180213T144459Z
TRANSP:OPAQUE
END:VEVENT
* IronBirds @ ValleyCats
<2018-08-26 Sun>--<2018-08-25 Sat>
:PROPERTIES:
:ID:       3gH-6zOhxPkj6Z0Q7fvruV97@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

IronBirds @ ValleyCats IronBirds @ ValleyCats

Follow on MiLB First Pitch  https //stza.co/+xMfn-38

Shop  https //stza.co/+xMfn-K

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:IronBirds @ ValleyCats
END:VALARM
DTSTART;VALUE=DATE:20180826
DTEND;VALUE=DATE:20180826
UID:3gH-6zOhxPkj6Z0Q7fvruV97@stanza.co
SUMMARY:IronBirds @ ValleyCats
DESCRIPTION:IronBirds @ ValleyCats\n\nFollow on MiLB First Pitch: https://stza.co/+xMfn-38\n\nShop: https://stza.co/+xMfn-K\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144459Z
LAST-MODIFIED:20180213T144459Z
TRANSP:OPAQUE
END:VEVENT
* IronBirds @ ValleyCats
<2018-08-27 Mon>--<2018-08-26 Sun>
:PROPERTIES:
:ID:       qxb7YDeTjz2i_yUBPiGSC32P@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

IronBirds @ ValleyCats IronBirds @ ValleyCats

Follow on MiLB First Pitch  https //stza.co/+xMfo-1c

Shop  https //stza.co/+xMfo-31

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:IronBirds @ ValleyCats
END:VALARM
DTSTART;VALUE=DATE:20180827
DTEND;VALUE=DATE:20180827
UID:qxb7YDeTjz2i_yUBPiGSC32P@stanza.co
SUMMARY:IronBirds @ ValleyCats
DESCRIPTION:IronBirds @ ValleyCats\n\nFollow on MiLB First Pitch: https://stza.co/+xMfo-1c\n\nShop: https://stza.co/+xMfo-31\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144459Z
LAST-MODIFIED:20180213T144459Z
TRANSP:OPAQUE
END:VEVENT
* IronBirds @ ValleyCats
<2018-08-28 Tue>--<2018-08-27 Mon>
:PROPERTIES:
:ID:       8t4ZL0JnnGmu3M1t7mK4bQll@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

IronBirds @ ValleyCats IronBirds @ ValleyCats

Follow on MiLB First Pitch  https //stza.co/+xMfp-2H

Shop  https //stza.co/+xMfp-G

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:IronBirds @ ValleyCats
END:VALARM
DTSTART;VALUE=DATE:20180828
DTEND;VALUE=DATE:20180828
UID:8t4ZL0JnnGmu3M1t7mK4bQll@stanza.co
SUMMARY:IronBirds @ ValleyCats
DESCRIPTION:IronBirds @ ValleyCats\n\nFollow on MiLB First Pitch: https://stza.co/+xMfp-2H\n\nShop: https://stza.co/+xMfp-G\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144459Z
LAST-MODIFIED:20180213T144459Z
TRANSP:OPAQUE
END:VEVENT
* IronBirds vs. Tigers
<2018-08-29 Wed 18:05-21:05>
:PROPERTIES:
:ID:       aMqNwR0ey7Np1IsUera580ow@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

IronBirds vs. Tigers IronBirds vs. Tigers

Follow on MiLB First Pitch  https //stza.co/+xXTE-3y

Shop  https //stza.co/+xXTE-2f

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:IronBirds vs. Tigers
END:VALARM
DTSTART:20180829T230500Z
DTEND:20180830T020500Z
UID:aMqNwR0ey7Np1IsUera580ow@stanza.co
SUMMARY:IronBirds vs. Tigers
DESCRIPTION:IronBirds vs. Tigers\n\nFollow on MiLB First Pitch: https://stza.co/+xXTE-3y\n\nShop: https://stza.co/+xXTE-2f\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144459Z
LAST-MODIFIED:20180213T144459Z
TRANSP:OPAQUE
END:VEVENT
* IronBirds vs. Tigers
<2018-08-30 Thu 18:05-21:05>
:PROPERTIES:
:ID:       zD0i_bpFH0g0DmWcVC77XVOo@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

IronBirds vs. Tigers IronBirds vs. Tigers

Follow on MiLB First Pitch  https //stza.co/+xXTH-2O

Shop  https //stza.co/+xXTH-f

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:IronBirds vs. Tigers
END:VALARM
DTSTART:20180830T230500Z
DTEND:20180831T020500Z
UID:zD0i_bpFH0g0DmWcVC77XVOo@stanza.co
SUMMARY:IronBirds vs. Tigers
DESCRIPTION:IronBirds vs. Tigers\n\nFollow on MiLB First Pitch: https://stza.co/+xXTH-2O\n\nShop: https://stza.co/+xXTH-f\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144459Z
LAST-MODIFIED:20180213T144459Z
TRANSP:OPAQUE
END:VEVENT
* IronBirds vs. Tigers
<2018-08-31 Fri 18:05-21:05>
:PROPERTIES:
:ID:       gJim8vjhfz8-xKxJLTs22e4b@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

IronBirds vs. Tigers IronBirds vs. Tigers

Follow on MiLB First Pitch  https //stza.co/+xXTJ-C

Shop  https //stza.co/+xXTJ-2W

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:IronBirds vs. Tigers
END:VALARM
DTSTART:20180831T230500Z
DTEND:20180901T020500Z
UID:gJim8vjhfz8-xKxJLTs22e4b@stanza.co
SUMMARY:IronBirds vs. Tigers
DESCRIPTION:IronBirds vs. Tigers\n\nFollow on MiLB First Pitch: https://stza.co/+xXTJ-C\n\nShop: https://stza.co/+xXTJ-2W\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144459Z
LAST-MODIFIED:20180213T144459Z
TRANSP:OPAQUE
END:VEVENT
* IronBirds @ Renegades
<2018-09-01 Sat 17:05-20:05>
:PROPERTIES:
:ID:       MJGbuSSNxK8_FtCbjvG2F52l@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

IronBirds @ Renegades IronBirds @ Renegades

Follow on MiLB First Pitch  https //stza.co/+xVYN-2f

Shop  https //stza.co/+xVYN-2G

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:IronBirds @ Renegades
END:VALARM
DTSTART:20180901T220500Z
DTEND:20180902T010500Z
UID:MJGbuSSNxK8_FtCbjvG2F52l@stanza.co
SUMMARY:IronBirds @ Renegades
DESCRIPTION:IronBirds @ Renegades\n\nFollow on MiLB First Pitch: https://stza.co/+xVYN-2f\n\nShop: https://stza.co/+xVYN-2G\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144459Z
LAST-MODIFIED:20180213T144459Z
TRANSP:OPAQUE
END:VEVENT
* IronBirds @ Renegades
<2018-09-02 Sun 16:05-19:05>
:PROPERTIES:
:ID:       g16V6PQd08krTZiHIdIX-4e7@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

IronBirds @ Renegades IronBirds @ Renegades

Follow on MiLB First Pitch  https //stza.co/+xVYO-a

Shop  https //stza.co/+xVYO-c

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:IronBirds @ Renegades
END:VALARM
DTSTART:20180902T210500Z
DTEND:20180903T000500Z
UID:g16V6PQd08krTZiHIdIX-4e7@stanza.co
SUMMARY:IronBirds @ Renegades
DESCRIPTION:IronBirds @ Renegades\n\nFollow on MiLB First Pitch: https://stza.co/+xVYO-a\n\nShop: https://stza.co/+xVYO-c\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144459Z
LAST-MODIFIED:20180213T144459Z
TRANSP:OPAQUE
END:VEVENT
* IronBirds @ Renegades
<2018-09-03 Mon 18:05-21:05>
:PROPERTIES:
:ID:       bRke78uxoTsqeH5nWaakAnXF@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

IronBirds @ Renegades IronBirds @ Renegades

Follow on MiLB First Pitch  https //stza.co/+xVYP-u

Shop  https //stza.co/+xVYP-J

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:IronBirds @ Renegades
END:VALARM
DTSTART:20180903T230500Z
DTEND:20180904T020500Z
UID:bRke78uxoTsqeH5nWaakAnXF@stanza.co
SUMMARY:IronBirds @ Renegades
DESCRIPTION:IronBirds @ Renegades\n\nFollow on MiLB First Pitch: https://stza.co/+xVYP-u\n\nShop: https://stza.co/+xVYP-J\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144459Z
LAST-MODIFIED:20180213T144459Z
TRANSP:OPAQUE
END:VEVENT
