#+TITLE:       Main Google calendar entries
#+AUTHOR:      Eric S Fraga
#+EMAIL:       e.fraga@ucl.ac.uk
#+DESCRIPTION: converted using the ical2org awk script
#+CATEGORY:    google
#+STARTUP:     hidestars
#+STARTUP:     overview

* COMMENT original iCal preamble

* Wood Ducks @ Hillcats
<2018-04-05 Thu 17:30-20:30>
:PROPERTIES:
:ID:       jza14qUBD5rqRrFCDLdy6VPZ@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Wood Ducks @ Hillcats Wood Ducks @ Hillcats

Buy tickets here  https //stza.co/~y3Tn

Follow on MiLB First Pitch  https //stza.co/+y3Tn-3w

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Wood Ducks @ Hillcats
END:VALARM
DTSTART:20180405T223000Z
DTEND:20180406T013000Z
UID:jza14qUBD5rqRrFCDLdy6VPZ@stanza.co
SUMMARY:Wood Ducks @ Hillcats
DESCRIPTION:Wood Ducks @ Hillcats\n\nBuy tickets here: https://stza.co/~y3Tn\n\nFollow on MiLB First Pitch: https://stza.co/+y3Tn-3w\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144520Z
LAST-MODIFIED:20180213T144520Z
TRANSP:OPAQUE
END:VEVENT
* Wood Ducks @ Hillcats
<2018-04-06 Fri 17:30-20:30>
:PROPERTIES:
:ID:       7HGi14UI8kJiZGwktLnXREqF@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Wood Ducks @ Hillcats Wood Ducks @ Hillcats

Buy tickets here  https //stza.co/~y3To

Follow on MiLB First Pitch  https //stza.co/+y3To-e

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Wood Ducks @ Hillcats
END:VALARM
DTSTART:20180406T223000Z
DTEND:20180407T013000Z
UID:7HGi14UI8kJiZGwktLnXREqF@stanza.co
SUMMARY:Wood Ducks @ Hillcats
DESCRIPTION:Wood Ducks @ Hillcats\n\nBuy tickets here: https://stza.co/~y3To\n\nFollow on MiLB First Pitch: https://stza.co/+y3To-e\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144520Z
LAST-MODIFIED:20180213T144520Z
TRANSP:OPAQUE
END:VEVENT
* Wood Ducks @ Hillcats
<2018-04-07 Sat 17:00-20:00>
:PROPERTIES:
:ID:       OZ1xysW0HdE5c17PQw3bH1IZ@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Wood Ducks @ Hillcats Wood Ducks @ Hillcats

Buy tickets here  https //stza.co/~y3Tp

Follow on MiLB First Pitch  https //stza.co/+y3Tp-1I

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Wood Ducks @ Hillcats
END:VALARM
DTSTART:20180407T220000Z
DTEND:20180408T010000Z
UID:OZ1xysW0HdE5c17PQw3bH1IZ@stanza.co
SUMMARY:Wood Ducks @ Hillcats
DESCRIPTION:Wood Ducks @ Hillcats\n\nBuy tickets here: https://stza.co/~y3Tp\n\nFollow on MiLB First Pitch: https://stza.co/+y3Tp-1I\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144520Z
LAST-MODIFIED:20180213T144520Z
TRANSP:OPAQUE
END:VEVENT
* Wood Ducks @ Hillcats
<2018-04-08 Sun 13:00-16:00>
:PROPERTIES:
:ID:       _V866lxIKqG-c5A1w6iZIheS@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Wood Ducks @ Hillcats Wood Ducks @ Hillcats

Buy tickets here  https //stza.co/~y3Tq

Follow on MiLB First Pitch  https //stza.co/+y3Tq-3A

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Wood Ducks @ Hillcats
END:VALARM
DTSTART:20180408T180000Z
DTEND:20180408T210000Z
UID:_V866lxIKqG-c5A1w6iZIheS@stanza.co
SUMMARY:Wood Ducks @ Hillcats
DESCRIPTION:Wood Ducks @ Hillcats\n\nBuy tickets here: https://stza.co/~y3Tq\n\nFollow on MiLB First Pitch: https://stza.co/+y3Tq-3A\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144520Z
LAST-MODIFIED:20180213T144520Z
TRANSP:OPAQUE
END:VEVENT
* Wood Ducks @ Nationals
<2018-04-09 Mon 18:05-21:05>
:PROPERTIES:
:ID:       pdhCYEVWL51fQIXFgNI6n4L1@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Wood Ducks @ Nationals Wood Ducks @ Nationals

Follow on MiLB First Pitch  https //stza.co/+xA2n-1E

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Wood Ducks @ Nationals
END:VALARM
DTSTART:20180409T230500Z
DTEND:20180410T020500Z
UID:pdhCYEVWL51fQIXFgNI6n4L1@stanza.co
SUMMARY:Wood Ducks @ Nationals
DESCRIPTION:Wood Ducks @ Nationals\n\nFollow on MiLB First Pitch: https://stza.co/+xA2n-1E\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144520Z
LAST-MODIFIED:20180213T144520Z
TRANSP:OPAQUE
END:VEVENT
* Wood Ducks @ Nationals
<2018-04-10 Tue 18:05-21:05>
:PROPERTIES:
:ID:       zXUyfN4nDXrZgHVl6AJBAwrA@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Wood Ducks @ Nationals Wood Ducks @ Nationals

Follow on MiLB First Pitch  https //stza.co/+xA2o-1s

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Wood Ducks @ Nationals
END:VALARM
DTSTART:20180410T230500Z
DTEND:20180411T020500Z
UID:zXUyfN4nDXrZgHVl6AJBAwrA@stanza.co
SUMMARY:Wood Ducks @ Nationals
DESCRIPTION:Wood Ducks @ Nationals\n\nFollow on MiLB First Pitch: https://stza.co/+xA2o-1s\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144520Z
LAST-MODIFIED:20180213T144520Z
TRANSP:OPAQUE
END:VEVENT
* Wood Ducks @ Nationals
<2018-04-11 Wed 09:35-12:35>
:PROPERTIES:
:ID:       G-jVP2YkDy6P_WpTyXCA64UY@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Wood Ducks @ Nationals Wood Ducks @ Nationals

Follow on MiLB First Pitch  https //stza.co/+xA2p-i

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Wood Ducks @ Nationals
END:VALARM
DTSTART:20180411T143500Z
DTEND:20180411T173500Z
UID:G-jVP2YkDy6P_WpTyXCA64UY@stanza.co
SUMMARY:Wood Ducks @ Nationals
DESCRIPTION:Wood Ducks @ Nationals\n\nFollow on MiLB First Pitch: https://stza.co/+xA2p-i\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144520Z
LAST-MODIFIED:20180213T144520Z
TRANSP:OPAQUE
END:VEVENT
* Wood Ducks vs. Pelicans
<2018-04-12 Thu 18:00-21:00>
:PROPERTIES:
:ID:       nCxDe7ALB04PcsKZ7OB_X94L@stanza.co
:LOCATION: Bojangles Schedule Magnet Giveaway
:STATUS:   CONFIRMED
:END:

Wood Ducks vs. Pelicans Fans in the gate will receive a schedule magnet on behalf of Bojangles.

We will have a big celebration in honor of baseball being back for the season! Music, food and baseball nobody will want to miss out. 

Special Fireworks show for Opening day. Schedule Magnet Giveaway at the gate upon entry.

Follow on MiLB First Pitch  https //stza.co/+w0nT-2$

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Wood Ducks vs. Pelicans
END:VALARM
DTSTART:20180412T230000Z
DTEND:20180413T020000Z
UID:nCxDe7ALB04PcsKZ7OB_X94L@stanza.co
SUMMARY:Wood Ducks vs. Pelicans
DESCRIPTION:Fans in the gate will receive a schedule magnet on behalf of Bojangles.\n\nWe will have a big celebration in honor of baseball being back for the season! Music, food and baseball nobody will want to miss out. \n\nSpecial Fireworks show for Opening day. Schedule Magnet Giveaway at the gate upon entry.\n\nFollow on MiLB First Pitch: https://stza.co/+w0nT-2$\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Bojangles Schedule Magnet Giveaway
STATUS:CONFIRMED
CREATED:20180213T144520Z
LAST-MODIFIED:20180213T144520Z
TRANSP:OPAQUE
END:VEVENT
* Wood Ducks vs. Pelicans
<2018-04-13 Fri 18:00-21:00>
:PROPERTIES:
:ID:       aOEqERqrhwaZEUA98x0xNc6J@stanza.co
:LOCATION: Food Truck Fridays
:STATUS:   CONFIRMED
:END:

Wood Ducks vs. Pelicans A fan favorite is returning for a second year. Fridays we will be having food trucks from all over  eastern north Carolina here at the ballpark so you can get a taste of something different.

We will have a big celebration in honor of baseball being back for the season! Music, food and baseball nobody will want to miss out. 



Follow on MiLB First Pitch  https //stza.co/+w0nW-1y

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Wood Ducks vs. Pelicans
END:VALARM
DTSTART:20180413T230000Z
DTEND:20180414T020000Z
UID:aOEqERqrhwaZEUA98x0xNc6J@stanza.co
SUMMARY:Wood Ducks vs. Pelicans
DESCRIPTION:A fan favorite is returning for a second year. Fridays we will be having food trucks from all over  eastern north Carolina here at the ballpark so you can get a taste of something different.\n\nWe will have a big celebration in honor of baseball being back for the season! Music, food and baseball nobody will want to miss out. \n\n\n\nFollow on MiLB First Pitch: https://stza.co/+w0nW-1y\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Food Truck Fridays
STATUS:CONFIRMED
CREATED:20180213T144520Z
LAST-MODIFIED:20180213T144520Z
TRANSP:OPAQUE
END:VEVENT
* Wood Ducks vs. Pelicans
<2018-04-14 Sat 17:00-20:00>
:PROPERTIES:
:ID:       IN7NDop3zvUzanfVR8ZtZSK6@stanza.co
:LOCATION: Champions T-shirt Giveaway
:STATUS:   CONFIRMED
:END:

Wood Ducks vs. Pelicans Be one of the first 1,000 fans and receive a Championship Tshirt on behalf of Pepsi.

Get to the game early to enjoy a live performance from Country singer, Bryan Mayer.

We will have a big celebration in honor of baseball being back for the season! Music, food and baseball nobody will want to miss out. 

Bring an empty Pepsi can and receive $3 off a game ticket. This offer is only available at the box office on the day of the game.Premium Giveaways on every Saturday game this year. Get here early in order to be the first to receive the giveaway.

Follow on MiLB First Pitch  https //stza.co/+w0nY-j

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Wood Ducks vs. Pelicans
END:VALARM
DTSTART:20180414T220000Z
DTEND:20180415T010000Z
UID:IN7NDop3zvUzanfVR8ZtZSK6@stanza.co
SUMMARY:Wood Ducks vs. Pelicans
DESCRIPTION:Be one of the first 1,000 fans and receive a Championship Tshirt on behalf of Pepsi.\n\nGet to the game early to enjoy a live performance from Country singer, Bryan Mayer.\n\nWe will have a big celebration in honor of baseball being back for the season! Music, food and baseball nobody will want to miss out. \n\nBring an empty Pepsi can and receive $3 off a game ticket. This offer is only available at the box office on the day of the game.Premium Giveaways on every Saturday game this year. Get here early in order to be the first to receive the giveaway.\n\nFollow on MiLB First Pitch: https://stza.co/+w0nY-j\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Champions T-shirt Giveaway
STATUS:CONFIRMED
CREATED:20180213T144520Z
LAST-MODIFIED:20180213T144520Z
TRANSP:OPAQUE
END:VEVENT
* Wood Ducks vs. Pelicans
<2018-04-15 Sun 13:00-16:00>
:PROPERTIES:
:ID:       rKcjz8aAOmjas9Q4FWGEHuoq@stanza.co
:LOCATION: Sunday Funday
:STATUS:   CONFIRMED
:END:

Wood Ducks vs. Pelicans Pre game Autograph signing from Wood Ducks players and post game run the bases presented by Cricket Wireless of Kinston. All Lil DEWD club members get in for free.

Follow on MiLB First Pitch  https //stza.co/+w0nZ-2E

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Wood Ducks vs. Pelicans
END:VALARM
DTSTART:20180415T180000Z
DTEND:20180415T210000Z
UID:rKcjz8aAOmjas9Q4FWGEHuoq@stanza.co
SUMMARY:Wood Ducks vs. Pelicans
DESCRIPTION:Pre game Autograph signing from Wood Ducks players and post game run the bases presented by Cricket Wireless of Kinston. All Lil DEWD club members get in for free.\n\nFollow on MiLB First Pitch: https://stza.co/+w0nZ-2E\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Sunday Funday
STATUS:CONFIRMED
CREATED:20180213T144520Z
LAST-MODIFIED:20180213T144520Z
TRANSP:OPAQUE
END:VEVENT
* Wood Ducks vs. Dash
<2018-04-16 Mon 18:00-21:00>
:PROPERTIES:
:ID:       J-4zJRDB0FiuwtFkJxM17dlh@stanza.co
:LOCATION: Dollar Hot Dog Night
:STATUS:   CONFIRMED
:END:

Wood Ducks vs. Dash Hot dogs all night long will be one dollar.

Kids under 12 receive free admission with a paying adult. One child per paying adult.

Follow on MiLB First Pitch  https //stza.co/+w0n$-1_

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Wood Ducks vs. Dash
END:VALARM
DTSTART:20180416T230000Z
DTEND:20180417T020000Z
UID:J-4zJRDB0FiuwtFkJxM17dlh@stanza.co
SUMMARY:Wood Ducks vs. Dash
DESCRIPTION:Hot dogs all night long will be one dollar.\n\nKids under 12 receive free admission with a paying adult. One child per paying adult.\n\nFollow on MiLB First Pitch: https://stza.co/+w0n$-1_\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Dollar Hot Dog Night
STATUS:CONFIRMED
CREATED:20180213T144520Z
LAST-MODIFIED:20180213T144520Z
TRANSP:OPAQUE
END:VEVENT
* Wood Ducks vs. Dash
<2018-04-17 Tue 18:00-21:00>
:PROPERTIES:
:ID:       stpEcN-8lKdLD-qMbzOV0phs@stanza.co
:LOCATION: Dollar Taco Night
:STATUS:   CONFIRMED
:END:

Wood Ducks vs. Dash 

With your food lion MVP card you can receive our BOGO ticket offer on Tuesdays except July 3.

Follow on MiLB First Pitch  https //stza.co/+w0o1-16

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Wood Ducks vs. Dash
END:VALARM
DTSTART:20180417T230000Z
DTEND:20180418T020000Z
UID:stpEcN-8lKdLD-qMbzOV0phs@stanza.co
SUMMARY:Wood Ducks vs. Dash
DESCRIPTION:\n\nWith your food lion MVP card you can receive our BOGO ticket offer on Tuesdays except July 3.\n\nFollow on MiLB First Pitch: https://stza.co/+w0o1-16\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Dollar Taco Night
STATUS:CONFIRMED
CREATED:20180213T144520Z
LAST-MODIFIED:20180213T144520Z
TRANSP:OPAQUE
END:VEVENT
* Wood Ducks vs. Dash
<2018-04-18 Wed 10:00-13:00>
:PROPERTIES:
:ID:       ZGqrY4AhajX9K-Q3nCARUX3o@stanza.co
:LOCATION: Education Day
:STATUS:   CONFIRMED
:END:

Wood Ducks vs. Dash Special 11 am start.

Follow on MiLB First Pitch  https //stza.co/+w0o4-N

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Wood Ducks vs. Dash
END:VALARM
DTSTART:20180418T150000Z
DTEND:20180418T180000Z
UID:ZGqrY4AhajX9K-Q3nCARUX3o@stanza.co
SUMMARY:Wood Ducks vs. Dash
DESCRIPTION:Special 11 am start.\n\nFollow on MiLB First Pitch: https://stza.co/+w0o4-N\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Education Day
STATUS:CONFIRMED
CREATED:20180213T144520Z
LAST-MODIFIED:20180213T144520Z
TRANSP:OPAQUE
END:VEVENT
* Wood Ducks @ Pelicans
<2018-04-19 Thu>--<2018-04-18 Wed>
:PROPERTIES:
:ID:       kIH8BBbtqNImyqYbxNqETfPS@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Wood Ducks @ Pelicans Wood Ducks @ Pelicans

Follow on MiLB First Pitch  https //stza.co/+w0qh-1p

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Wood Ducks @ Pelicans
END:VALARM
DTSTART;VALUE=DATE:20180419
DTEND;VALUE=DATE:20180419
UID:kIH8BBbtqNImyqYbxNqETfPS@stanza.co
SUMMARY:Wood Ducks @ Pelicans
DESCRIPTION:Wood Ducks @ Pelicans\n\nFollow on MiLB First Pitch: https://stza.co/+w0qh-1p\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144520Z
LAST-MODIFIED:20180213T144520Z
TRANSP:OPAQUE
END:VEVENT
* Wood Ducks @ Pelicans
<2018-04-20 Fri>--<2018-04-19 Thu>
:PROPERTIES:
:ID:       8Y4P_R7JC-8ZAFfThW1dYQFc@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Wood Ducks @ Pelicans Wood Ducks @ Pelicans

Follow on MiLB First Pitch  https //stza.co/+w0qi-T

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Wood Ducks @ Pelicans
END:VALARM
DTSTART;VALUE=DATE:20180420
DTEND;VALUE=DATE:20180420
UID:8Y4P_R7JC-8ZAFfThW1dYQFc@stanza.co
SUMMARY:Wood Ducks @ Pelicans
DESCRIPTION:Wood Ducks @ Pelicans\n\nFollow on MiLB First Pitch: https://stza.co/+w0qi-T\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144520Z
LAST-MODIFIED:20180213T144520Z
TRANSP:OPAQUE
END:VEVENT
* Wood Ducks @ Pelicans
<2018-04-21 Sat>--<2018-04-20 Fri>
:PROPERTIES:
:ID:       LHpZfs0REE-0q6pf0Dm5lfyj@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Wood Ducks @ Pelicans Wood Ducks @ Pelicans

Follow on MiLB First Pitch  https //stza.co/+w0qj-23

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Wood Ducks @ Pelicans
END:VALARM
DTSTART;VALUE=DATE:20180421
DTEND;VALUE=DATE:20180421
UID:LHpZfs0REE-0q6pf0Dm5lfyj@stanza.co
SUMMARY:Wood Ducks @ Pelicans
DESCRIPTION:Wood Ducks @ Pelicans\n\nFollow on MiLB First Pitch: https://stza.co/+w0qj-23\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144520Z
LAST-MODIFIED:20180213T144520Z
TRANSP:OPAQUE
END:VEVENT
* Wood Ducks @ Pelicans
<2018-04-22 Sun>--<2018-04-21 Sat>
:PROPERTIES:
:ID:       WLv3A_KLBZkqrjtXYhViQ-5-@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Wood Ducks @ Pelicans Wood Ducks @ Pelicans

Follow on MiLB First Pitch  https //stza.co/+w0qk-2q

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Wood Ducks @ Pelicans
END:VALARM
DTSTART;VALUE=DATE:20180422
DTEND;VALUE=DATE:20180422
UID:WLv3A_KLBZkqrjtXYhViQ-5-@stanza.co
SUMMARY:Wood Ducks @ Pelicans
DESCRIPTION:Wood Ducks @ Pelicans\n\nFollow on MiLB First Pitch: https://stza.co/+w0qk-2q\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144520Z
LAST-MODIFIED:20180213T144520Z
TRANSP:OPAQUE
END:VEVENT
* Wood Ducks @ Astros
<2018-04-24 Tue 18:00-21:00>
:PROPERTIES:
:ID:       3y1t5rMINwuxNCn37Rzxrd7J@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Wood Ducks @ Astros Wood Ducks @ Astros

Follow on MiLB First Pitch  https //stza.co/+xM8V-d

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Wood Ducks @ Astros
END:VALARM
DTSTART:20180424T230000Z
DTEND:20180425T020000Z
UID:3y1t5rMINwuxNCn37Rzxrd7J@stanza.co
SUMMARY:Wood Ducks @ Astros
DESCRIPTION:Wood Ducks @ Astros\n\nFollow on MiLB First Pitch: https://stza.co/+xM8V-d\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144520Z
LAST-MODIFIED:20180213T144520Z
TRANSP:OPAQUE
END:VEVENT
* Wood Ducks @ Astros
<2018-04-25 Wed 18:00-21:00>
:PROPERTIES:
:ID:       vD1pVJpZt9XSvwnhxzYbhAdN@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Wood Ducks @ Astros Wood Ducks @ Astros

Follow on MiLB First Pitch  https //stza.co/+xM8W-2k

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Wood Ducks @ Astros
END:VALARM
DTSTART:20180425T230000Z
DTEND:20180426T020000Z
UID:vD1pVJpZt9XSvwnhxzYbhAdN@stanza.co
SUMMARY:Wood Ducks @ Astros
DESCRIPTION:Wood Ducks @ Astros\n\nFollow on MiLB First Pitch: https://stza.co/+xM8W-2k\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144520Z
LAST-MODIFIED:20180213T144520Z
TRANSP:OPAQUE
END:VEVENT
* Wood Ducks @ Astros
<2018-04-26 Thu 18:00-21:00>
:PROPERTIES:
:ID:       N5swx13XSKreiKKyxndCUs4W@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Wood Ducks @ Astros Wood Ducks @ Astros

Follow on MiLB First Pitch  https //stza.co/+xM8X-1Q

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Wood Ducks @ Astros
END:VALARM
DTSTART:20180426T230000Z
DTEND:20180427T020000Z
UID:N5swx13XSKreiKKyxndCUs4W@stanza.co
SUMMARY:Wood Ducks @ Astros
DESCRIPTION:Wood Ducks @ Astros\n\nFollow on MiLB First Pitch: https://stza.co/+xM8X-1Q\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144520Z
LAST-MODIFIED:20180213T144520Z
TRANSP:OPAQUE
END:VEVENT
* Wood Ducks vs. Mudcats
<2018-04-27 Fri 18:00-21:00>
:PROPERTIES:
:ID:       p0iYB-p-cvr6spXxc1GW0PKV@stanza.co
:LOCATION: Mother Earth Friday
:STATUS:   CONFIRMED
:END:

Wood Ducks vs. Mudcats $3 Mother Earth Drafts.$3 off a game ticket at the box office with beer can.

A fan favorite is returning for a second year. Fridays we will be having food trucks from all over  eastern north Carolina here at the ballpark so you can get a taste of something different.

Pregame parade and camp out in the ballpark after the game.

Follow on MiLB First Pitch  https //stza.co/+w0o5-Q

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Wood Ducks vs. Mudcats
END:VALARM
DTSTART:20180427T230000Z
DTEND:20180428T020000Z
UID:p0iYB-p-cvr6spXxc1GW0PKV@stanza.co
SUMMARY:Wood Ducks vs. Mudcats
DESCRIPTION:$3 Mother Earth Drafts.$3 off a game ticket at the box office with beer can.\n\nA fan favorite is returning for a second year. Fridays we will be having food trucks from all over  eastern north Carolina here at the ballpark so you can get a taste of something different.\n\nPregame parade and camp out in the ballpark after the game.\n\nFollow on MiLB First Pitch: https://stza.co/+w0o5-Q\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Mother Earth Friday
STATUS:CONFIRMED
CREATED:20180213T144520Z
LAST-MODIFIED:20180213T144520Z
TRANSP:OPAQUE
END:VEVENT
* Wood Ducks vs. Mudcats
<2018-04-28 Sat 17:00-20:00>
:PROPERTIES:
:ID:       XSXcUNy6vnQWxyWwBrZUTHdo@stanza.co
:LOCATION: Tote Bag Giveaway
:STATUS:   CONFIRMED
:END:

Wood Ducks vs. Mudcats The first 1,000 will receive a complimentary Wood Ducks Tote Bag on behalf of Piggly Wiggly Fresh Buy & Pet Ice Cream.

Bring an empty Pepsi can and receive $3 off a game ticket. This offer is only available at the box office on the day of the game.Premium Giveaways on every Saturday game this year. Get here early in order to be the first to receive the giveaway.

Follow on MiLB First Pitch  https //stza.co/+w0o7-N

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Wood Ducks vs. Mudcats
END:VALARM
DTSTART:20180428T220000Z
DTEND:20180429T010000Z
UID:XSXcUNy6vnQWxyWwBrZUTHdo@stanza.co
SUMMARY:Wood Ducks vs. Mudcats
DESCRIPTION:The first 1,000 will receive a complimentary Wood Ducks Tote Bag on behalf of Piggly Wiggly Fresh Buy & Pet Ice Cream.\n\nBring an empty Pepsi can and receive $3 off a game ticket. This offer is only available at the box office on the day of the game.Premium Giveaways on every Saturday game this year. Get here early in order to be the first to receive the giveaway.\n\nFollow on MiLB First Pitch: https://stza.co/+w0o7-N\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Tote Bag Giveaway
STATUS:CONFIRMED
CREATED:20180213T144520Z
LAST-MODIFIED:20180213T144520Z
TRANSP:OPAQUE
END:VEVENT
* Wood Ducks vs. Mudcats
<2018-04-29 Sun 13:00-16:00>
:PROPERTIES:
:ID:       9v4oUd5QpPGHM26vs28Odv7p@stanza.co
:LOCATION: Sunday Funday
:STATUS:   CONFIRMED
:END:

Wood Ducks vs. Mudcats Pre game Autograph signing from Wood Ducks players and post game run the bases presented by Cricket Wireless of Kinston. All Lil DEWD club members get in for free.

Follow on MiLB First Pitch  https //stza.co/+w0oa-2o

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Wood Ducks vs. Mudcats
END:VALARM
DTSTART:20180429T180000Z
DTEND:20180429T210000Z
UID:9v4oUd5QpPGHM26vs28Odv7p@stanza.co
SUMMARY:Wood Ducks vs. Mudcats
DESCRIPTION:Pre game Autograph signing from Wood Ducks players and post game run the bases presented by Cricket Wireless of Kinston. All Lil DEWD club members get in for free.\n\nFollow on MiLB First Pitch: https://stza.co/+w0oa-2o\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Sunday Funday
STATUS:CONFIRMED
CREATED:20180213T144520Z
LAST-MODIFIED:20180213T144520Z
TRANSP:OPAQUE
END:VEVENT
* Wood Ducks vs. Astros
<2018-05-01 Tue 18:00-21:00>
:PROPERTIES:
:ID:       7weYtOGdH7NQmYNQk1oupKHl@stanza.co
:LOCATION: Dollar Taco Night
:STATUS:   CONFIRMED
:END:

Wood Ducks vs. Astros 

With your food lion MVP card you can receive our BOGO ticket offer on Tuesdays except July 3.

Follow on MiLB First Pitch  https //stza.co/+w0ob-2o

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Wood Ducks vs. Astros
END:VALARM
DTSTART:20180501T230000Z
DTEND:20180502T020000Z
UID:7weYtOGdH7NQmYNQk1oupKHl@stanza.co
SUMMARY:Wood Ducks vs. Astros
DESCRIPTION:\n\nWith your food lion MVP card you can receive our BOGO ticket offer on Tuesdays except July 3.\n\nFollow on MiLB First Pitch: https://stza.co/+w0ob-2o\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Dollar Taco Night
STATUS:CONFIRMED
CREATED:20180213T144520Z
LAST-MODIFIED:20180213T144520Z
TRANSP:OPAQUE
END:VEVENT
* Wood Ducks vs. Astros
<2018-05-02 Wed 10:00-13:00>
:PROPERTIES:
:ID:       JFCKCvn3g1nyd2lgwKpRW3W2@stanza.co
:LOCATION: Education Day
:STATUS:   CONFIRMED
:END:

Wood Ducks vs. Astros Special 11 am start.

Follow on MiLB First Pitch  https //stza.co/+w0oe-3C

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Wood Ducks vs. Astros
END:VALARM
DTSTART:20180502T150000Z
DTEND:20180502T180000Z
UID:JFCKCvn3g1nyd2lgwKpRW3W2@stanza.co
SUMMARY:Wood Ducks vs. Astros
DESCRIPTION:Special 11 am start.\n\nFollow on MiLB First Pitch: https://stza.co/+w0oe-3C\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Education Day
STATUS:CONFIRMED
CREATED:20180213T144520Z
LAST-MODIFIED:20180213T144520Z
TRANSP:OPAQUE
END:VEVENT
* Wood Ducks vs. Astros
<2018-05-03 Thu 18:00-21:00>
:PROPERTIES:
:ID:       uljv2SWXV0JpLKgQH09lyHz_@stanza.co
:LOCATION: Throwback Thursday Dollar Beer Special
:STATUS:   CONFIRMED
:END:

Wood Ducks vs. Astros To go with our Throwback Thursday Nights we will also we offering $1 beer and pepsi products.

We are turning back the clock every Thursday this season.The players will be wearing Kinston Indians Jerseys,Game tickets will be $5 and we have $1 beer and Pepsi products.

Follow on MiLB First Pitch  https //stza.co/+w0of-2t

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Wood Ducks vs. Astros
END:VALARM
DTSTART:20180503T230000Z
DTEND:20180504T020000Z
UID:uljv2SWXV0JpLKgQH09lyHz_@stanza.co
SUMMARY:Wood Ducks vs. Astros
DESCRIPTION:To go with our Throwback Thursday Nights we will also we offering $1 beer and pepsi products.\n\nWe are turning back the clock every Thursday this season.The players will be wearing Kinston Indians Jerseys,Game tickets will be $5 and we have $1 beer and Pepsi products.\n\nFollow on MiLB First Pitch: https://stza.co/+w0of-2t\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Throwback Thursday Dollar Beer Special
STATUS:CONFIRMED
CREATED:20180213T144520Z
LAST-MODIFIED:20180213T144520Z
TRANSP:OPAQUE
END:VEVENT
* Wood Ducks @ Mudcats
<2018-05-04 Fri 18:00-21:00>
:PROPERTIES:
:ID:       WSqKfiJnzEQr8TCerIps_wgu@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Wood Ducks @ Mudcats Wood Ducks @ Mudcats

Buy tickets here  https //stza.co/~w0nF

Follow on MiLB First Pitch  https //stza.co/+w0nF-1f

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Wood Ducks @ Mudcats
END:VALARM
DTSTART:20180504T230000Z
DTEND:20180505T020000Z
UID:WSqKfiJnzEQr8TCerIps_wgu@stanza.co
SUMMARY:Wood Ducks @ Mudcats
DESCRIPTION:Wood Ducks @ Mudcats\n\nBuy tickets here: https://stza.co/~w0nF\n\nFollow on MiLB First Pitch: https://stza.co/+w0nF-1f\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144520Z
LAST-MODIFIED:20180213T144520Z
TRANSP:OPAQUE
END:VEVENT
* Wood Ducks @ Mudcats
<2018-05-05 Sat 16:00-19:00>
:PROPERTIES:
:ID:       tf4-Clwovv_I7XcXC9xDJN9B@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Wood Ducks @ Mudcats Wood Ducks @ Mudcats

Buy tickets here  https //stza.co/~w0nG

Follow on MiLB First Pitch  https //stza.co/+w0nG-1Q

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Wood Ducks @ Mudcats
END:VALARM
DTSTART:20180505T210000Z
DTEND:20180506T000000Z
UID:tf4-Clwovv_I7XcXC9xDJN9B@stanza.co
SUMMARY:Wood Ducks @ Mudcats
DESCRIPTION:Wood Ducks @ Mudcats\n\nBuy tickets here: https://stza.co/~w0nG\n\nFollow on MiLB First Pitch: https://stza.co/+w0nG-1Q\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144520Z
LAST-MODIFIED:20180213T144520Z
TRANSP:OPAQUE
END:VEVENT
* Wood Ducks @ Mudcats
<2018-05-06 Sun 13:00-16:00>
:PROPERTIES:
:ID:       fBkziNYn7x6xY4IaA_S-ivhV@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Wood Ducks @ Mudcats Wood Ducks @ Mudcats

Buy tickets here  https //stza.co/~w0nH

Follow on MiLB First Pitch  https //stza.co/+w0nH-2X

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Wood Ducks @ Mudcats
END:VALARM
DTSTART:20180506T180000Z
DTEND:20180506T210000Z
UID:fBkziNYn7x6xY4IaA_S-ivhV@stanza.co
SUMMARY:Wood Ducks @ Mudcats
DESCRIPTION:Wood Ducks @ Mudcats\n\nBuy tickets here: https://stza.co/~w0nH\n\nFollow on MiLB First Pitch: https://stza.co/+w0nH-2X\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144520Z
LAST-MODIFIED:20180213T144520Z
TRANSP:OPAQUE
END:VEVENT
* Wood Ducks vs. Pelicans
<2018-05-07 Mon 18:00-21:00>
:PROPERTIES:
:ID:       UVJ_AltlYHFnHUuQzrk7TgBz@stanza.co
:LOCATION: Dollar Hot Dog Night
:STATUS:   CONFIRMED
:END:

Wood Ducks vs. Pelicans Hot dogs all night long will be one dollar.

Kids under 12 receive free admission with a paying adult. One child per paying adult.

Follow on MiLB First Pitch  https //stza.co/+w0oh-3U

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Wood Ducks vs. Pelicans
END:VALARM
DTSTART:20180507T230000Z
DTEND:20180508T020000Z
UID:UVJ_AltlYHFnHUuQzrk7TgBz@stanza.co
SUMMARY:Wood Ducks vs. Pelicans
DESCRIPTION:Hot dogs all night long will be one dollar.\n\nKids under 12 receive free admission with a paying adult. One child per paying adult.\n\nFollow on MiLB First Pitch: https://stza.co/+w0oh-3U\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Dollar Hot Dog Night
STATUS:CONFIRMED
CREATED:20180213T144520Z
LAST-MODIFIED:20180213T144520Z
TRANSP:OPAQUE
END:VEVENT
* Wood Ducks vs. Pelicans
<2018-05-08 Tue 18:00-21:00>
:PROPERTIES:
:ID:       GQ5RAAgSrm-7HxJe73J8S1Wy@stanza.co
:LOCATION: Dollar Taco Night
:STATUS:   CONFIRMED
:END:

Wood Ducks vs. Pelicans 

With your food lion MVP card you can receive our BOGO ticket offer on Tuesdays except July 3.

Follow on MiLB First Pitch  https //stza.co/+w0ok-1w

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Wood Ducks vs. Pelicans
END:VALARM
DTSTART:20180508T230000Z
DTEND:20180509T020000Z
UID:GQ5RAAgSrm-7HxJe73J8S1Wy@stanza.co
SUMMARY:Wood Ducks vs. Pelicans
DESCRIPTION:\n\nWith your food lion MVP card you can receive our BOGO ticket offer on Tuesdays except July 3.\n\nFollow on MiLB First Pitch: https://stza.co/+w0ok-1w\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Dollar Taco Night
STATUS:CONFIRMED
CREATED:20180213T144520Z
LAST-MODIFIED:20180213T144520Z
TRANSP:OPAQUE
END:VEVENT
* Wood Ducks vs. Pelicans
<2018-05-09 Wed 10:00-13:00>
:PROPERTIES:
:ID:       csKwydQF-W5AHen34ycPAU91@stanza.co
:LOCATION: Education Day
:STATUS:   CONFIRMED
:END:

Wood Ducks vs. Pelicans Special 11 am start.

Follow on MiLB First Pitch  https //stza.co/+w0ol-2d

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Wood Ducks vs. Pelicans
END:VALARM
DTSTART:20180509T150000Z
DTEND:20180509T180000Z
UID:csKwydQF-W5AHen34ycPAU91@stanza.co
SUMMARY:Wood Ducks vs. Pelicans
DESCRIPTION:Special 11 am start.\n\nFollow on MiLB First Pitch: https://stza.co/+w0ol-2d\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Education Day
STATUS:CONFIRMED
CREATED:20180213T144520Z
LAST-MODIFIED:20180213T144520Z
TRANSP:OPAQUE
END:VEVENT
* Wood Ducks @ Dash
<2018-05-10 Thu 18:00-21:00>
:PROPERTIES:
:ID:       PgddzLNG4-nnOhfk5ksJqNMZ@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Wood Ducks @ Dash Wood Ducks @ Dash

Buy tickets here  https //stza.co/~w0qA

Follow on MiLB First Pitch  https //stza.co/+w0qA-2T

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Wood Ducks @ Dash
END:VALARM
DTSTART:20180510T230000Z
DTEND:20180511T020000Z
UID:PgddzLNG4-nnOhfk5ksJqNMZ@stanza.co
SUMMARY:Wood Ducks @ Dash
DESCRIPTION:Wood Ducks @ Dash\n\nBuy tickets here: https://stza.co/~w0qA\n\nFollow on MiLB First Pitch: https://stza.co/+w0qA-2T\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144520Z
LAST-MODIFIED:20180213T144520Z
TRANSP:OPAQUE
END:VEVENT
* Wood Ducks @ Dash
<2018-05-11 Fri 18:00-21:00>
:PROPERTIES:
:ID:       PaJt2i7X_sXCpShTGOTtrTll@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Wood Ducks @ Dash Wood Ducks @ Dash

Buy tickets here  https //stza.co/~w0qB

Follow on MiLB First Pitch  https //stza.co/+w0qB-u

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Wood Ducks @ Dash
END:VALARM
DTSTART:20180511T230000Z
DTEND:20180512T020000Z
UID:PaJt2i7X_sXCpShTGOTtrTll@stanza.co
SUMMARY:Wood Ducks @ Dash
DESCRIPTION:Wood Ducks @ Dash\n\nBuy tickets here: https://stza.co/~w0qB\n\nFollow on MiLB First Pitch: https://stza.co/+w0qB-u\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144520Z
LAST-MODIFIED:20180213T144520Z
TRANSP:OPAQUE
END:VEVENT
* Wood Ducks @ Dash
<2018-05-12 Sat 17:00-20:00>
:PROPERTIES:
:ID:       S_rvBsh-FrKLDttKUDcJVgHo@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Wood Ducks @ Dash Wood Ducks @ Dash

Buy tickets here  https //stza.co/~w0qC

Follow on MiLB First Pitch  https //stza.co/+w0qC-2g

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Wood Ducks @ Dash
END:VALARM
DTSTART:20180512T220000Z
DTEND:20180513T010000Z
UID:S_rvBsh-FrKLDttKUDcJVgHo@stanza.co
SUMMARY:Wood Ducks @ Dash
DESCRIPTION:Wood Ducks @ Dash\n\nBuy tickets here: https://stza.co/~w0qC\n\nFollow on MiLB First Pitch: https://stza.co/+w0qC-2g\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144520Z
LAST-MODIFIED:20180213T144520Z
TRANSP:OPAQUE
END:VEVENT
* Wood Ducks @ Dash
<2018-05-13 Sun 13:00-16:00>
:PROPERTIES:
:ID:       7PkzSdUW25wrYAqbfbR4lW78@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Wood Ducks @ Dash Wood Ducks @ Dash

Buy tickets here  https //stza.co/~w0qD

Follow on MiLB First Pitch  https //stza.co/+w0qD-C

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Wood Ducks @ Dash
END:VALARM
DTSTART:20180513T180000Z
DTEND:20180513T210000Z
UID:7PkzSdUW25wrYAqbfbR4lW78@stanza.co
SUMMARY:Wood Ducks @ Dash
DESCRIPTION:Wood Ducks @ Dash\n\nBuy tickets here: https://stza.co/~w0qD\n\nFollow on MiLB First Pitch: https://stza.co/+w0qD-C\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144520Z
LAST-MODIFIED:20180213T144520Z
TRANSP:OPAQUE
END:VEVENT
* Wood Ducks vs. Mudcats
<2018-05-15 Tue 18:00-21:00>
:PROPERTIES:
:ID:       QaGK3LCQeKrIUr6cLQCz1pOp@stanza.co
:LOCATION: Dollar Taco Night
:STATUS:   CONFIRMED
:END:

Wood Ducks vs. Mudcats 

With your food lion MVP card you can receive our BOGO ticket offer on Tuesdays except July 3.

Follow on MiLB First Pitch  https //stza.co/+w0on-33

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Wood Ducks vs. Mudcats
END:VALARM
DTSTART:20180515T230000Z
DTEND:20180516T020000Z
UID:QaGK3LCQeKrIUr6cLQCz1pOp@stanza.co
SUMMARY:Wood Ducks vs. Mudcats
DESCRIPTION:\n\nWith your food lion MVP card you can receive our BOGO ticket offer on Tuesdays except July 3.\n\nFollow on MiLB First Pitch: https://stza.co/+w0on-33\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Dollar Taco Night
STATUS:CONFIRMED
CREATED:20180213T144520Z
LAST-MODIFIED:20180213T144520Z
TRANSP:OPAQUE
END:VEVENT
* Wood Ducks vs. Mudcats
<2018-05-16 Wed 18:00-21:00>
:PROPERTIES:
:ID:       17W6DY-G7_YP-It8aBvlhE7Z@stanza.co
:LOCATION: Second Annual Bark in the Park
:STATUS:   CONFIRMED
:END:

Wood Ducks vs. Mudcats Bring your dogs out for a night out at the ballpark. All dogs must be on a leash but can enjoy our pregame parade and more fun things to announce.



Follow on MiLB First Pitch  https //stza.co/+w0oq-2k

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Wood Ducks vs. Mudcats
END:VALARM
DTSTART:20180516T230000Z
DTEND:20180517T020000Z
UID:17W6DY-G7_YP-It8aBvlhE7Z@stanza.co
SUMMARY:Wood Ducks vs. Mudcats
DESCRIPTION:Bring your dogs out for a night out at the ballpark. All dogs must be on a leash but can enjoy our pregame parade and more fun things to announce.\n\n\n\nFollow on MiLB First Pitch: https://stza.co/+w0oq-2k\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Second Annual Bark in the Park
STATUS:CONFIRMED
CREATED:20180213T144520Z
LAST-MODIFIED:20180213T144520Z
TRANSP:OPAQUE
END:VEVENT
* Wood Ducks vs. Mudcats
<2018-05-17 Thu 18:00-21:00>
:PROPERTIES:
:ID:       dPZHP2_OkWvlTFXqStwPOPfa@stanza.co
:LOCATION: Throwback Thursday Dollar Beer Special
:STATUS:   CONFIRMED
:END:

Wood Ducks vs. Mudcats To go with our Throwback Thursday Nights we will also we offering $1 beer and pepsi products.

We are turning back the clock every Thursday this season.The players will be wearing Kinston Indians Jerseys,Game tickets will be $5 and we have $1 beer and Pepsi products.

Follow on MiLB First Pitch  https //stza.co/+w0os-y

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Wood Ducks vs. Mudcats
END:VALARM
DTSTART:20180517T230000Z
DTEND:20180518T020000Z
UID:dPZHP2_OkWvlTFXqStwPOPfa@stanza.co
SUMMARY:Wood Ducks vs. Mudcats
DESCRIPTION:To go with our Throwback Thursday Nights we will also we offering $1 beer and pepsi products.\n\nWe are turning back the clock every Thursday this season.The players will be wearing Kinston Indians Jerseys,Game tickets will be $5 and we have $1 beer and Pepsi products.\n\nFollow on MiLB First Pitch: https://stza.co/+w0os-y\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Throwback Thursday Dollar Beer Special
STATUS:CONFIRMED
CREATED:20180213T144520Z
LAST-MODIFIED:20180213T144520Z
TRANSP:OPAQUE
END:VEVENT
* Wood Ducks vs. Dash
<2018-05-18 Fri 18:00-21:00>
:PROPERTIES:
:ID:       lGZbLROCbW6BE7dpuGCkzKCT@stanza.co
:LOCATION: Post Game Fireworks Show
:STATUS:   CONFIRMED
:END:

Wood Ducks vs. Dash 

$3 Mother Earth Drafts.$3 off a game ticket at the box office with beer can.

A fan favorite is returning for a second year. Fridays we will be having food trucks from all over  eastern north Carolina here at the ballpark so you can get a taste of something different.

Pregame parade and camp out in the ballpark after the game.

Follow on MiLB First Pitch  https //stza.co/+w0ou-1L

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Wood Ducks vs. Dash
END:VALARM
DTSTART:20180518T230000Z
DTEND:20180519T020000Z
UID:lGZbLROCbW6BE7dpuGCkzKCT@stanza.co
SUMMARY:Wood Ducks vs. Dash
DESCRIPTION:\n\n$3 Mother Earth Drafts.$3 off a game ticket at the box office with beer can.\n\nA fan favorite is returning for a second year. Fridays we will be having food trucks from all over  eastern north Carolina here at the ballpark so you can get a taste of something different.\n\nPregame parade and camp out in the ballpark after the game.\n\nFollow on MiLB First Pitch: https://stza.co/+w0ou-1L\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Post Game Fireworks Show
STATUS:CONFIRMED
CREATED:20180213T144520Z
LAST-MODIFIED:20180213T144520Z
TRANSP:OPAQUE
END:VEVENT
* Wood Ducks vs. Dash
<2018-05-19 Sat 17:00-20:00>
:PROPERTIES:
:ID:       uwUbwBsYk9YwPU95nBw2NiIs@stanza.co
:LOCATION: Seat Cushion Giveaway
:STATUS:   CONFIRMED
:END:

Wood Ducks vs. Dash The first 1,000 will receive a complimentary Wood Ducks Seat Cushion on behalf of MedSource Pharmacy.

Only 200 tickets available in the NEW Mother Earth Pavilion so get them while you can. They will sell out fast.

Bring an empty Pepsi can and receive $3 off a game ticket. This offer is only available at the box office on the day of the game.Premium Giveaways on every Saturday game this year. Get here early in order to be the first to receive the giveaway.

Follow on MiLB First Pitch  https //stza.co/+w0ow-3Z

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Wood Ducks vs. Dash
END:VALARM
DTSTART:20180519T220000Z
DTEND:20180520T010000Z
UID:uwUbwBsYk9YwPU95nBw2NiIs@stanza.co
SUMMARY:Wood Ducks vs. Dash
DESCRIPTION:The first 1,000 will receive a complimentary Wood Ducks Seat Cushion on behalf of MedSource Pharmacy.\n\nOnly 200 tickets available in the NEW Mother Earth Pavilion so get them while you can. They will sell out fast.\n\nBring an empty Pepsi can and receive $3 off a game ticket. This offer is only available at the box office on the day of the game.Premium Giveaways on every Saturday game this year. Get here early in order to be the first to receive the giveaway.\n\nFollow on MiLB First Pitch: https://stza.co/+w0ow-3Z\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Seat Cushion Giveaway
STATUS:CONFIRMED
CREATED:20180213T144520Z
LAST-MODIFIED:20180213T144520Z
TRANSP:OPAQUE
END:VEVENT
* Wood Ducks vs. Dash
<2018-05-20 Sun 13:00-16:00>
:PROPERTIES:
:ID:       gOtv9U_4SLKa-5Q3ISHUQ0Iz@stanza.co
:LOCATION: Sunday Funday
:STATUS:   CONFIRMED
:END:

Wood Ducks vs. Dash Pre game Autograph signing from Wood Ducks players and post game run the bases presented by Cricket Wireless of Kinston. All Lil DEWD club members get in for free.

Follow on MiLB First Pitch  https //stza.co/+w0oy-38

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Wood Ducks vs. Dash
END:VALARM
DTSTART:20180520T180000Z
DTEND:20180520T210000Z
UID:gOtv9U_4SLKa-5Q3ISHUQ0Iz@stanza.co
SUMMARY:Wood Ducks vs. Dash
DESCRIPTION:Pre game Autograph signing from Wood Ducks players and post game run the bases presented by Cricket Wireless of Kinston. All Lil DEWD club members get in for free.\n\nFollow on MiLB First Pitch: https://stza.co/+w0oy-38\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Sunday Funday
STATUS:CONFIRMED
CREATED:20180213T144520Z
LAST-MODIFIED:20180213T144520Z
TRANSP:OPAQUE
END:VEVENT
* Wood Ducks @ Mudcats
<2018-05-21 Mon 18:00-21:00>
:PROPERTIES:
:ID:       HLXG_qoS-msiVwP8zmkzlAH3@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Wood Ducks @ Mudcats Wood Ducks @ Mudcats

Buy tickets here  https //stza.co/~w0nI

Follow on MiLB First Pitch  https //stza.co/+w0nI-g

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Wood Ducks @ Mudcats
END:VALARM
DTSTART:20180521T230000Z
DTEND:20180522T020000Z
UID:HLXG_qoS-msiVwP8zmkzlAH3@stanza.co
SUMMARY:Wood Ducks @ Mudcats
DESCRIPTION:Wood Ducks @ Mudcats\n\nBuy tickets here: https://stza.co/~w0nI\n\nFollow on MiLB First Pitch: https://stza.co/+w0nI-g\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144520Z
LAST-MODIFIED:20180213T144520Z
TRANSP:OPAQUE
END:VEVENT
* Wood Ducks @ Mudcats
<2018-05-22 Tue 18:00-21:00>
:PROPERTIES:
:ID:       fBZ-oQgbSmsvPEknBGCfAXSV@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Wood Ducks @ Mudcats Wood Ducks @ Mudcats

Buy tickets here  https //stza.co/~w0nJ

Follow on MiLB First Pitch  https //stza.co/+w0nJ-1Y

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Wood Ducks @ Mudcats
END:VALARM
DTSTART:20180522T230000Z
DTEND:20180523T020000Z
UID:fBZ-oQgbSmsvPEknBGCfAXSV@stanza.co
SUMMARY:Wood Ducks @ Mudcats
DESCRIPTION:Wood Ducks @ Mudcats\n\nBuy tickets here: https://stza.co/~w0nJ\n\nFollow on MiLB First Pitch: https://stza.co/+w0nJ-1Y\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144520Z
LAST-MODIFIED:20180213T144520Z
TRANSP:OPAQUE
END:VEVENT
* Wood Ducks @ Mudcats
<2018-05-23 Wed 10:00-13:00>
:PROPERTIES:
:ID:       RVavbIl67pzEJixR1RY5vAsV@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Wood Ducks @ Mudcats Wood Ducks @ Mudcats

Buy tickets here  https //stza.co/~w0nK

Follow on MiLB First Pitch  https //stza.co/+w0nK-2K

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Wood Ducks @ Mudcats
END:VALARM
DTSTART:20180523T150000Z
DTEND:20180523T180000Z
UID:RVavbIl67pzEJixR1RY5vAsV@stanza.co
SUMMARY:Wood Ducks @ Mudcats
DESCRIPTION:Wood Ducks @ Mudcats\n\nBuy tickets here: https://stza.co/~w0nK\n\nFollow on MiLB First Pitch: https://stza.co/+w0nK-2K\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144520Z
LAST-MODIFIED:20180213T144520Z
TRANSP:OPAQUE
END:VEVENT
* Wood Ducks @ Mudcats
<2018-05-24 Thu 18:00-21:00>
:PROPERTIES:
:ID:       pJzwJBZCP9UBc7ejBhhYFxYs@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Wood Ducks @ Mudcats Wood Ducks @ Mudcats

Buy tickets here  https //stza.co/~w0nL

Follow on MiLB First Pitch  https //stza.co/+w0nL-1w

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Wood Ducks @ Mudcats
END:VALARM
DTSTART:20180524T230000Z
DTEND:20180525T020000Z
UID:pJzwJBZCP9UBc7ejBhhYFxYs@stanza.co
SUMMARY:Wood Ducks @ Mudcats
DESCRIPTION:Wood Ducks @ Mudcats\n\nBuy tickets here: https://stza.co/~w0nL\n\nFollow on MiLB First Pitch: https://stza.co/+w0nL-1w\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144520Z
LAST-MODIFIED:20180213T144520Z
TRANSP:OPAQUE
END:VEVENT
* Wood Ducks vs. Keys
<2018-05-25 Fri 18:00-21:00>
:PROPERTIES:
:ID:       Chr3yYteqDo6be-bmVK4J2oN@stanza.co
:LOCATION: Post Game Fireworks Show
:STATUS:   CONFIRMED
:END:

Wood Ducks vs. Keys 

$3 Mother Earth Drafts.$3 off a game ticket at the box office with beer can.

A fan favorite is returning for a second year. Fridays we will be having food trucks from all over  eastern north Carolina here at the ballpark so you can get a taste of something different.

Follow on MiLB First Pitch  https //stza.co/+w0oz-3T

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Wood Ducks vs. Keys
END:VALARM
DTSTART:20180525T230000Z
DTEND:20180526T020000Z
UID:Chr3yYteqDo6be-bmVK4J2oN@stanza.co
SUMMARY:Wood Ducks vs. Keys
DESCRIPTION:\n\n$3 Mother Earth Drafts.$3 off a game ticket at the box office with beer can.\n\nA fan favorite is returning for a second year. Fridays we will be having food trucks from all over  eastern north Carolina here at the ballpark so you can get a taste of something different.\n\nFollow on MiLB First Pitch: https://stza.co/+w0oz-3T\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Post Game Fireworks Show
STATUS:CONFIRMED
CREATED:20180213T144520Z
LAST-MODIFIED:20180213T144520Z
TRANSP:OPAQUE
END:VEVENT
* Wood Ducks vs. Keys
<2018-05-26 Sat 17:00-20:00>
:PROPERTIES:
:ID:       tcaN3Re67JckHGnYdYpbek7O@stanza.co
:LOCATION: Camo Cap Giveaway
:STATUS:   CONFIRMED
:END:

Wood Ducks vs. Keys Be one of the first 1,000 fans and receive a Camo cap on behalf of Stallings Plumbing, Heating & Air Conditioning

Bring an empty Pepsi can and receive $3 off a game ticket. This offer is only available at the box office on the day of the game.Premium Giveaways on every Saturday game this year. Get here early in order to be the first to receive the giveaway.

Follow on MiLB First Pitch  https //stza.co/+w0oB-v

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Wood Ducks vs. Keys
END:VALARM
DTSTART:20180526T220000Z
DTEND:20180527T010000Z
UID:tcaN3Re67JckHGnYdYpbek7O@stanza.co
SUMMARY:Wood Ducks vs. Keys
DESCRIPTION:Be one of the first 1,000 fans and receive a Camo cap on behalf of Stallings Plumbing, Heating & Air Conditioning\n\nBring an empty Pepsi can and receive $3 off a game ticket. This offer is only available at the box office on the day of the game.Premium Giveaways on every Saturday game this year. Get here early in order to be the first to receive the giveaway.\n\nFollow on MiLB First Pitch: https://stza.co/+w0oB-v\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Camo Cap Giveaway
STATUS:CONFIRMED
CREATED:20180213T144520Z
LAST-MODIFIED:20180213T144520Z
TRANSP:OPAQUE
END:VEVENT
* Wood Ducks vs. Keys
<2018-05-27 Sun 13:00-16:00>
:PROPERTIES:
:ID:       -hCXfCwj1EgBOfZx-DzmZb0o@stanza.co
:LOCATION: Sunday Funday
:STATUS:   CONFIRMED
:END:

Wood Ducks vs. Keys Pre game Autograph signing from Wood Ducks players and post game run the bases presented by Cricket Wireless of Kinston. All Lil DEWD club members get in for free.

Follow on MiLB First Pitch  https //stza.co/+w0oE-i

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Wood Ducks vs. Keys
END:VALARM
DTSTART:20180527T180000Z
DTEND:20180527T210000Z
UID:-hCXfCwj1EgBOfZx-DzmZb0o@stanza.co
SUMMARY:Wood Ducks vs. Keys
DESCRIPTION:Pre game Autograph signing from Wood Ducks players and post game run the bases presented by Cricket Wireless of Kinston. All Lil DEWD club members get in for free.\n\nFollow on MiLB First Pitch: https://stza.co/+w0oE-i\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Sunday Funday
STATUS:CONFIRMED
CREATED:20180213T144520Z
LAST-MODIFIED:20180213T144520Z
TRANSP:OPAQUE
END:VEVENT
* Wood Ducks vs. Keys
<2018-05-28 Mon 15:00-18:00>
:PROPERTIES:
:ID:       8_tcvZIiGqe1F6PN4Onh21cc@stanza.co
:LOCATION: Dollar Hot Dog Night
:STATUS:   CONFIRMED
:END:

Wood Ducks vs. Keys Hot dogs all night long will be one dollar.

Kids under 12 receive free admission with a paying adult. One child per paying adult.

Follow on MiLB First Pitch  https //stza.co/+w0oG-24

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Wood Ducks vs. Keys
END:VALARM
DTSTART:20180528T200000Z
DTEND:20180528T230000Z
UID:8_tcvZIiGqe1F6PN4Onh21cc@stanza.co
SUMMARY:Wood Ducks vs. Keys
DESCRIPTION:Hot dogs all night long will be one dollar.\n\nKids under 12 receive free admission with a paying adult. One child per paying adult.\n\nFollow on MiLB First Pitch: https://stza.co/+w0oG-24\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Dollar Hot Dog Night
STATUS:CONFIRMED
CREATED:20180213T144520Z
LAST-MODIFIED:20180213T144520Z
TRANSP:OPAQUE
END:VEVENT
* Wood Ducks vs. Astros
<2018-05-29 Tue 18:00-21:00>
:PROPERTIES:
:ID:       gXgTcJoMhrTJjwMjIVTlA7_U@stanza.co
:LOCATION: Dollar Taco Night
:STATUS:   CONFIRMED
:END:

Wood Ducks vs. Astros 

With your food lion MVP card you can receive our BOGO ticket offer on Tuesdays except July 3.

Follow on MiLB First Pitch  https //stza.co/+w0oI-1L

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Wood Ducks vs. Astros
END:VALARM
DTSTART:20180529T230000Z
DTEND:20180530T020000Z
UID:gXgTcJoMhrTJjwMjIVTlA7_U@stanza.co
SUMMARY:Wood Ducks vs. Astros
DESCRIPTION:\n\nWith your food lion MVP card you can receive our BOGO ticket offer on Tuesdays except July 3.\n\nFollow on MiLB First Pitch: https://stza.co/+w0oI-1L\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Dollar Taco Night
STATUS:CONFIRMED
CREATED:20180213T144520Z
LAST-MODIFIED:20180213T144520Z
TRANSP:OPAQUE
END:VEVENT
* Wood Ducks vs. Astros
<2018-05-30 Wed 18:00-21:00>
:PROPERTIES:
:ID:       T6Akxc4s1TsZS6tdIri3baSB@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Wood Ducks vs. Astros Wood Ducks vs. Astros

Follow on MiLB First Pitch  https //stza.co/+w0oK-26

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Wood Ducks vs. Astros
END:VALARM
DTSTART:20180530T230000Z
DTEND:20180531T020000Z
UID:T6Akxc4s1TsZS6tdIri3baSB@stanza.co
SUMMARY:Wood Ducks vs. Astros
DESCRIPTION:Wood Ducks vs. Astros\n\nFollow on MiLB First Pitch: https://stza.co/+w0oK-26\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144520Z
LAST-MODIFIED:20180213T144520Z
TRANSP:OPAQUE
END:VEVENT
* Wood Ducks vs. Astros
<2018-05-31 Thu 18:00-21:00>
:PROPERTIES:
:ID:       TRRNu9pZ0aqC9TSEs7zA-vau@stanza.co
:LOCATION: Throwback Thursday Dollar Beer Special
:STATUS:   CONFIRMED
:END:

Wood Ducks vs. Astros To go with our Throwback Thursday Nights we will also we offering $1 beer and pepsi products.

We are turning back the clock every Thursday this season.The players will be wearing Kinston Indians Jerseys,Game tickets will be $5 and we have $1 beer and Pepsi products.

Follow on MiLB First Pitch  https //stza.co/+w0oM-3C

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Wood Ducks vs. Astros
END:VALARM
DTSTART:20180531T230000Z
DTEND:20180601T020000Z
UID:TRRNu9pZ0aqC9TSEs7zA-vau@stanza.co
SUMMARY:Wood Ducks vs. Astros
DESCRIPTION:To go with our Throwback Thursday Nights we will also we offering $1 beer and pepsi products.\n\nWe are turning back the clock every Thursday this season.The players will be wearing Kinston Indians Jerseys,Game tickets will be $5 and we have $1 beer and Pepsi products.\n\nFollow on MiLB First Pitch: https://stza.co/+w0oM-3C\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Throwback Thursday Dollar Beer Special
STATUS:CONFIRMED
CREATED:20180213T144520Z
LAST-MODIFIED:20180213T144520Z
TRANSP:OPAQUE
END:VEVENT
* Wood Ducks @ Pelicans
<2018-06-01 Fri>--<2018-05-31 Thu>
:PROPERTIES:
:ID:       u2I6zfwT4rCMsIl4o-xfOVFd@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Wood Ducks @ Pelicans Wood Ducks @ Pelicans

Follow on MiLB First Pitch  https //stza.co/+w0ql-1w

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Wood Ducks @ Pelicans
END:VALARM
DTSTART;VALUE=DATE:20180601
DTEND;VALUE=DATE:20180601
UID:u2I6zfwT4rCMsIl4o-xfOVFd@stanza.co
SUMMARY:Wood Ducks @ Pelicans
DESCRIPTION:Wood Ducks @ Pelicans\n\nFollow on MiLB First Pitch: https://stza.co/+w0ql-1w\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144520Z
LAST-MODIFIED:20180213T144520Z
TRANSP:OPAQUE
END:VEVENT
* Wood Ducks @ Pelicans
<2018-06-02 Sat>--<2018-06-01 Fri>
:PROPERTIES:
:ID:       MLEqBIsA50W1gWTZaRF5scPx@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Wood Ducks @ Pelicans Wood Ducks @ Pelicans

Follow on MiLB First Pitch  https //stza.co/+w0qm-29

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Wood Ducks @ Pelicans
END:VALARM
DTSTART;VALUE=DATE:20180602
DTEND;VALUE=DATE:20180602
UID:MLEqBIsA50W1gWTZaRF5scPx@stanza.co
SUMMARY:Wood Ducks @ Pelicans
DESCRIPTION:Wood Ducks @ Pelicans\n\nFollow on MiLB First Pitch: https://stza.co/+w0qm-29\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144520Z
LAST-MODIFIED:20180213T144520Z
TRANSP:OPAQUE
END:VEVENT
* Wood Ducks @ Pelicans
<2018-06-03 Sun>--<2018-06-02 Sat>
:PROPERTIES:
:ID:       HAOUuhYKfczlJP1nznsDVK73@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Wood Ducks @ Pelicans Wood Ducks @ Pelicans

Follow on MiLB First Pitch  https //stza.co/+w0qn-h

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Wood Ducks @ Pelicans
END:VALARM
DTSTART;VALUE=DATE:20180603
DTEND;VALUE=DATE:20180603
UID:HAOUuhYKfczlJP1nznsDVK73@stanza.co
SUMMARY:Wood Ducks @ Pelicans
DESCRIPTION:Wood Ducks @ Pelicans\n\nFollow on MiLB First Pitch: https://stza.co/+w0qn-h\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144520Z
LAST-MODIFIED:20180213T144520Z
TRANSP:OPAQUE
END:VEVENT
* Wood Ducks @ Mudcats
<2018-06-05 Tue 18:00-21:00>
:PROPERTIES:
:ID:       _CJbCCcWH7F7Ja6G1sGXjAnc@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Wood Ducks @ Mudcats Wood Ducks @ Mudcats

Buy tickets here  https //stza.co/~w0nM

Follow on MiLB First Pitch  https //stza.co/+w0nM-

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Wood Ducks @ Mudcats
END:VALARM
DTSTART:20180605T230000Z
DTEND:20180606T020000Z
UID:_CJbCCcWH7F7Ja6G1sGXjAnc@stanza.co
SUMMARY:Wood Ducks @ Mudcats
DESCRIPTION:Wood Ducks @ Mudcats\n\nBuy tickets here: https://stza.co/~w0nM\n\nFollow on MiLB First Pitch: https://stza.co/+w0nM-\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144520Z
LAST-MODIFIED:20180213T144520Z
TRANSP:OPAQUE
END:VEVENT
* Wood Ducks @ Mudcats
<2018-06-06 Wed 18:00-21:00>
:PROPERTIES:
:ID:       0wHkhv5bZo--NIRsa_n5Vgrg@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Wood Ducks @ Mudcats Wood Ducks @ Mudcats

Buy tickets here  https //stza.co/~w0nN

Follow on MiLB First Pitch  https //stza.co/+w0nN-3t

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Wood Ducks @ Mudcats
END:VALARM
DTSTART:20180606T230000Z
DTEND:20180607T020000Z
UID:0wHkhv5bZo--NIRsa_n5Vgrg@stanza.co
SUMMARY:Wood Ducks @ Mudcats
DESCRIPTION:Wood Ducks @ Mudcats\n\nBuy tickets here: https://stza.co/~w0nN\n\nFollow on MiLB First Pitch: https://stza.co/+w0nN-3t\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144520Z
LAST-MODIFIED:20180213T144520Z
TRANSP:OPAQUE
END:VEVENT
* Wood Ducks @ Mudcats
<2018-06-07 Thu 18:00-21:00>
:PROPERTIES:
:ID:       EGYh3D1gftG6W7LfX7LBlkMu@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Wood Ducks @ Mudcats Wood Ducks @ Mudcats

Buy tickets here  https //stza.co/~w0nO

Follow on MiLB First Pitch  https //stza.co/+w0nO-3_

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Wood Ducks @ Mudcats
END:VALARM
DTSTART:20180607T230000Z
DTEND:20180608T020000Z
UID:EGYh3D1gftG6W7LfX7LBlkMu@stanza.co
SUMMARY:Wood Ducks @ Mudcats
DESCRIPTION:Wood Ducks @ Mudcats\n\nBuy tickets here: https://stza.co/~w0nO\n\nFollow on MiLB First Pitch: https://stza.co/+w0nO-3_\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144520Z
LAST-MODIFIED:20180213T144520Z
TRANSP:OPAQUE
END:VEVENT
* Wood Ducks vs. Astros
<2018-06-08 Fri 18:00-21:00>
:PROPERTIES:
:ID:       a2x4tMGhiT9Ke0s-xXvpARj7@stanza.co
:LOCATION: Salute to Agriculture Appreciation Day
:STATUS:   CONFIRMED
:END:

Wood Ducks vs. Astros 



$3 Mother Earth Drafts.$3 off a game ticket at the box office with beer can.

We will be recognizing graduating seniors of Lenoir County on 6/8.  Complimentary ticket for any graduating Lenoir County student with purchase of a paid ticket by accompanying adult.  

A fan favorite is returning for a second year. Fridays we will be having food trucks from all over  eastern north Carolina here at the ballpark so you can get a taste of something different.

Follow on MiLB First Pitch  https //stza.co/+w0oN-29

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Wood Ducks vs. Astros
END:VALARM
DTSTART:20180608T230000Z
DTEND:20180609T020000Z
UID:a2x4tMGhiT9Ke0s-xXvpARj7@stanza.co
SUMMARY:Wood Ducks vs. Astros
DESCRIPTION:\n\n\n\n$3 Mother Earth Drafts.$3 off a game ticket at the box office with beer can.\n\nWe will be recognizing graduating seniors of Lenoir County on 6/8.  Complimentary ticket for any graduating Lenoir County student with purchase of a paid ticket by accompanying adult.  \n\nA fan favorite is returning for a second year. Fridays we will be having food trucks from all over  eastern north Carolina here at the ballpark so you can get a taste of something different.\n\nFollow on MiLB First Pitch: https://stza.co/+w0oN-29\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Salute to Agriculture Appreciation Day
STATUS:CONFIRMED
CREATED:20180213T144520Z
LAST-MODIFIED:20180213T144520Z
TRANSP:OPAQUE
END:VEVENT
* Wood Ducks vs. Astros
<2018-06-09 Sat 17:00-20:00>
:PROPERTIES:
:ID:       0i3NaL-k8_3s0w7UQZBBCdwN@stanza.co
:LOCATION: Trucker Hat Giveaway
:STATUS:   CONFIRMED
:END:

Wood Ducks vs. Astros The first 1,000 will receive a complimentary Wood Ducks Trucker Hat on behalf of Lenoir Community College.

Bring an empty Pepsi can and receive $3 off a game ticket. This offer is only available at the box office on the day of the game.Premium Giveaways on every Saturday game this year. Get here early in order to be the first to receive the giveaway.

Follow on MiLB First Pitch  https //stza.co/+w0oP-S

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Wood Ducks vs. Astros
END:VALARM
DTSTART:20180609T220000Z
DTEND:20180610T010000Z
UID:0i3NaL-k8_3s0w7UQZBBCdwN@stanza.co
SUMMARY:Wood Ducks vs. Astros
DESCRIPTION:The first 1,000 will receive a complimentary Wood Ducks Trucker Hat on behalf of Lenoir Community College.\n\nBring an empty Pepsi can and receive $3 off a game ticket. This offer is only available at the box office on the day of the game.Premium Giveaways on every Saturday game this year. Get here early in order to be the first to receive the giveaway.\n\nFollow on MiLB First Pitch: https://stza.co/+w0oP-S\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Trucker Hat Giveaway
STATUS:CONFIRMED
CREATED:20180213T144520Z
LAST-MODIFIED:20180213T144520Z
TRANSP:OPAQUE
END:VEVENT
* Wood Ducks vs. Astros
<2018-06-10 Sun 15:00-18:00>
:PROPERTIES:
:ID:       5dsHEmbUnUE-LN41MCbAJVjG@stanza.co
:LOCATION: Sunday Funday
:STATUS:   CONFIRMED
:END:

Wood Ducks vs. Astros Pre game Autograph signing from Wood Ducks players and post game run the bases presented by Cricket Wireless of Kinston. All Lil DEWD club members get in for free.

Follow on MiLB First Pitch  https //stza.co/+w0oS-1a

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Wood Ducks vs. Astros
END:VALARM
DTSTART:20180610T200000Z
DTEND:20180610T230000Z
UID:5dsHEmbUnUE-LN41MCbAJVjG@stanza.co
SUMMARY:Wood Ducks vs. Astros
DESCRIPTION:Pre game Autograph signing from Wood Ducks players and post game run the bases presented by Cricket Wireless of Kinston. All Lil DEWD club members get in for free.\n\nFollow on MiLB First Pitch: https://stza.co/+w0oS-1a\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Sunday Funday
STATUS:CONFIRMED
CREATED:20180213T144520Z
LAST-MODIFIED:20180213T144520Z
TRANSP:OPAQUE
END:VEVENT
* Wood Ducks vs. Blue Rocks
<2018-06-11 Mon 18:00-21:00>
:PROPERTIES:
:ID:       Flm5DHcjd7evdhSDv7Z1RuWT@stanza.co
:LOCATION: Dollar Hot Dog Night
:STATUS:   CONFIRMED
:END:

Wood Ducks vs. Blue Rocks Hot dogs all night long will be one dollar.

Kids under 12 receive free admission with a paying adult. One child per paying adult.

Follow on MiLB First Pitch  https //stza.co/+w0oT-3J

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Wood Ducks vs. Blue Rocks
END:VALARM
DTSTART:20180611T230000Z
DTEND:20180612T020000Z
UID:Flm5DHcjd7evdhSDv7Z1RuWT@stanza.co
SUMMARY:Wood Ducks vs. Blue Rocks
DESCRIPTION:Hot dogs all night long will be one dollar.\n\nKids under 12 receive free admission with a paying adult. One child per paying adult.\n\nFollow on MiLB First Pitch: https://stza.co/+w0oT-3J\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Dollar Hot Dog Night
STATUS:CONFIRMED
CREATED:20180213T144520Z
LAST-MODIFIED:20180213T144520Z
TRANSP:OPAQUE
END:VEVENT
* Wood Ducks vs. Blue Rocks
<2018-06-12 Tue 18:00-21:00>
:PROPERTIES:
:ID:       l50ZnNhoIyCFWrDreF6FvfzE@stanza.co
:LOCATION: Dollar Taco Night
:STATUS:   CONFIRMED
:END:

Wood Ducks vs. Blue Rocks 

With your food lion MVP card you can receive our BOGO ticket offer on Tuesdays except July 3.

Follow on MiLB First Pitch  https //stza.co/+w0oW-1t

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Wood Ducks vs. Blue Rocks
END:VALARM
DTSTART:20180612T230000Z
DTEND:20180613T020000Z
UID:l50ZnNhoIyCFWrDreF6FvfzE@stanza.co
SUMMARY:Wood Ducks vs. Blue Rocks
DESCRIPTION:\n\nWith your food lion MVP card you can receive our BOGO ticket offer on Tuesdays except July 3.\n\nFollow on MiLB First Pitch: https://stza.co/+w0oW-1t\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Dollar Taco Night
STATUS:CONFIRMED
CREATED:20180213T144520Z
LAST-MODIFIED:20180213T144520Z
TRANSP:OPAQUE
END:VEVENT
* Wood Ducks vs. Blue Rocks
<2018-06-13 Wed 11:05-14:05>
:PROPERTIES:
:ID:       PXs6SeRRyP5DXyD81VktIwkC@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Wood Ducks vs. Blue Rocks Wood Ducks vs. Blue Rocks

Follow on MiLB First Pitch  https //stza.co/+w0oX-12

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Wood Ducks vs. Blue Rocks
END:VALARM
DTSTART:20180613T160500Z
DTEND:20180613T190500Z
UID:PXs6SeRRyP5DXyD81VktIwkC@stanza.co
SUMMARY:Wood Ducks vs. Blue Rocks
DESCRIPTION:Wood Ducks vs. Blue Rocks\n\nFollow on MiLB First Pitch: https://stza.co/+w0oX-12\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144520Z
LAST-MODIFIED:20180213T144520Z
TRANSP:OPAQUE
END:VEVENT
* Wood Ducks @ Keys
<2018-06-14 Thu 18:00-21:00>
:PROPERTIES:
:ID:       bObZHRcPyNe5ZhhPkYaLpLra@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Wood Ducks @ Keys Wood Ducks @ Keys

Follow on MiLB First Pitch  https //stza.co/+wg9k-1q

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Wood Ducks @ Keys
END:VALARM
DTSTART:20180614T230000Z
DTEND:20180615T020000Z
UID:bObZHRcPyNe5ZhhPkYaLpLra@stanza.co
SUMMARY:Wood Ducks @ Keys
DESCRIPTION:Wood Ducks @ Keys\n\nFollow on MiLB First Pitch: https://stza.co/+wg9k-1q\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144520Z
LAST-MODIFIED:20180213T144520Z
TRANSP:OPAQUE
END:VEVENT
* Wood Ducks @ Keys
<2018-06-15 Fri 18:00-21:00>
:PROPERTIES:
:ID:       7kEID_ZZKbo1BuL8VdvKrHgE@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Wood Ducks @ Keys Wood Ducks @ Keys

Follow on MiLB First Pitch  https //stza.co/+wg9l-m

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Wood Ducks @ Keys
END:VALARM
DTSTART:20180615T230000Z
DTEND:20180616T020000Z
UID:7kEID_ZZKbo1BuL8VdvKrHgE@stanza.co
SUMMARY:Wood Ducks @ Keys
DESCRIPTION:Wood Ducks @ Keys\n\nFollow on MiLB First Pitch: https://stza.co/+wg9l-m\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144520Z
LAST-MODIFIED:20180213T144520Z
TRANSP:OPAQUE
END:VEVENT
* Wood Ducks @ Keys
<2018-06-16 Sat 17:00-20:00>
:PROPERTIES:
:ID:       24B8lHLVJ-o8vW0fgFRGXCAU@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Wood Ducks @ Keys Wood Ducks @ Keys

Follow on MiLB First Pitch  https //stza.co/+wg9m-C

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Wood Ducks @ Keys
END:VALARM
DTSTART:20180616T220000Z
DTEND:20180617T010000Z
UID:24B8lHLVJ-o8vW0fgFRGXCAU@stanza.co
SUMMARY:Wood Ducks @ Keys
DESCRIPTION:Wood Ducks @ Keys\n\nFollow on MiLB First Pitch: https://stza.co/+wg9m-C\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144520Z
LAST-MODIFIED:20180213T144520Z
TRANSP:OPAQUE
END:VEVENT
* Wood Ducks @ Keys
<2018-06-17 Sun 13:00-16:00>
:PROPERTIES:
:ID:       JlZ7RawYJabOKxsTmN8Q0YQv@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Wood Ducks @ Keys Wood Ducks @ Keys

Follow on MiLB First Pitch  https //stza.co/+wg9n-2

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Wood Ducks @ Keys
END:VALARM
DTSTART:20180617T180000Z
DTEND:20180617T210000Z
UID:JlZ7RawYJabOKxsTmN8Q0YQv@stanza.co
SUMMARY:Wood Ducks @ Keys
DESCRIPTION:Wood Ducks @ Keys\n\nFollow on MiLB First Pitch: https://stza.co/+wg9n-2\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144520Z
LAST-MODIFIED:20180213T144520Z
TRANSP:OPAQUE
END:VEVENT
* Wood Ducks @ Dash
<2018-06-21 Thu 18:00-21:00>
:PROPERTIES:
:ID:       lncWoDY_XANx8SCYPe6vf-9L@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Wood Ducks @ Dash Wood Ducks @ Dash

Buy tickets here  https //stza.co/~w0qE

Follow on MiLB First Pitch  https //stza.co/+w0qE-2J

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Wood Ducks @ Dash
END:VALARM
DTSTART:20180621T230000Z
DTEND:20180622T020000Z
UID:lncWoDY_XANx8SCYPe6vf-9L@stanza.co
SUMMARY:Wood Ducks @ Dash
DESCRIPTION:Wood Ducks @ Dash\n\nBuy tickets here: https://stza.co/~w0qE\n\nFollow on MiLB First Pitch: https://stza.co/+w0qE-2J\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144520Z
LAST-MODIFIED:20180213T144520Z
TRANSP:OPAQUE
END:VEVENT
* Wood Ducks @ Dash
<2018-06-22 Fri 18:00-21:00>
:PROPERTIES:
:ID:       zLJAsHRijpnFVlbP6FIK0XY7@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Wood Ducks @ Dash Wood Ducks @ Dash

Buy tickets here  https //stza.co/~w0qF

Follow on MiLB First Pitch  https //stza.co/+w0qF-$

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Wood Ducks @ Dash
END:VALARM
DTSTART:20180622T230000Z
DTEND:20180623T020000Z
UID:zLJAsHRijpnFVlbP6FIK0XY7@stanza.co
SUMMARY:Wood Ducks @ Dash
DESCRIPTION:Wood Ducks @ Dash\n\nBuy tickets here: https://stza.co/~w0qF\n\nFollow on MiLB First Pitch: https://stza.co/+w0qF-$\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144520Z
LAST-MODIFIED:20180213T144520Z
TRANSP:OPAQUE
END:VEVENT
* Wood Ducks @ Dash
<2018-06-23 Sat 15:00-18:00>
:PROPERTIES:
:ID:       1cQ6NrZ8O93-Sz7RKy-Cz7mC@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Wood Ducks @ Dash Wood Ducks @ Dash

Buy tickets here  https //stza.co/~w0qG

Follow on MiLB First Pitch  https //stza.co/+w0qG-2T

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Wood Ducks @ Dash
END:VALARM
DTSTART:20180623T200000Z
DTEND:20180623T230000Z
UID:1cQ6NrZ8O93-Sz7RKy-Cz7mC@stanza.co
SUMMARY:Wood Ducks @ Dash
DESCRIPTION:Wood Ducks @ Dash\n\nBuy tickets here: https://stza.co/~w0qG\n\nFollow on MiLB First Pitch: https://stza.co/+w0qG-2T\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144520Z
LAST-MODIFIED:20180213T144520Z
TRANSP:OPAQUE
END:VEVENT
* Wood Ducks @ Dash
<2018-06-24 Sun 13:00-16:00>
:PROPERTIES:
:ID:       n6qf7ACxkieLZbbyxSc0-jm5@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Wood Ducks @ Dash Wood Ducks @ Dash

Buy tickets here  https //stza.co/~w0qH

Follow on MiLB First Pitch  https //stza.co/+w0qH-3s

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Wood Ducks @ Dash
END:VALARM
DTSTART:20180624T180000Z
DTEND:20180624T210000Z
UID:n6qf7ACxkieLZbbyxSc0-jm5@stanza.co
SUMMARY:Wood Ducks @ Dash
DESCRIPTION:Wood Ducks @ Dash\n\nBuy tickets here: https://stza.co/~w0qH\n\nFollow on MiLB First Pitch: https://stza.co/+w0qH-3s\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144520Z
LAST-MODIFIED:20180213T144520Z
TRANSP:OPAQUE
END:VEVENT
* Wood Ducks vs. Nationals
<2018-06-25 Mon 18:00-21:00>
:PROPERTIES:
:ID:       R4wi8x1PNI_4iqymnk7AExo5@stanza.co
:LOCATION: Dollar Hot Dog Night
:STATUS:   CONFIRMED
:END:

Wood Ducks vs. Nationals Hot dogs all night long will be one dollar.

Kids under 12 receive free admission with a paying adult. One child per paying adult.

Follow on MiLB First Pitch  https //stza.co/+w0oZ-2e

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Wood Ducks vs. Nationals
END:VALARM
DTSTART:20180625T230000Z
DTEND:20180626T020000Z
UID:R4wi8x1PNI_4iqymnk7AExo5@stanza.co
SUMMARY:Wood Ducks vs. Nationals
DESCRIPTION:Hot dogs all night long will be one dollar.\n\nKids under 12 receive free admission with a paying adult. One child per paying adult.\n\nFollow on MiLB First Pitch: https://stza.co/+w0oZ-2e\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Dollar Hot Dog Night
STATUS:CONFIRMED
CREATED:20180213T144520Z
LAST-MODIFIED:20180213T144520Z
TRANSP:OPAQUE
END:VEVENT
* Wood Ducks vs. Nationals
<2018-06-26 Tue 18:00-21:00>
:PROPERTIES:
:ID:       RlrfWXwbkPEBpXVyRCP9KJkV@stanza.co
:LOCATION: Dollar Taco Night
:STATUS:   CONFIRMED
:END:

Wood Ducks vs. Nationals 

With your food lion MVP card you can receive our BOGO ticket offer on Tuesdays except July 3.

Follow on MiLB First Pitch  https //stza.co/+w0o$-3P

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Wood Ducks vs. Nationals
END:VALARM
DTSTART:20180626T230000Z
DTEND:20180627T020000Z
UID:RlrfWXwbkPEBpXVyRCP9KJkV@stanza.co
SUMMARY:Wood Ducks vs. Nationals
DESCRIPTION:\n\nWith your food lion MVP card you can receive our BOGO ticket offer on Tuesdays except July 3.\n\nFollow on MiLB First Pitch: https://stza.co/+w0o$-3P\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Dollar Taco Night
STATUS:CONFIRMED
CREATED:20180213T144520Z
LAST-MODIFIED:20180213T144520Z
TRANSP:OPAQUE
END:VEVENT
* Wood Ducks vs. Nationals
<2018-06-27 Wed 10:00-13:00>
:PROPERTIES:
:ID:       AQ3kf4GO6XWkxxsmCVm1HC5l@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Wood Ducks vs. Nationals Wood Ducks vs. Nationals

Follow on MiLB First Pitch  https //stza.co/+w0p2-3U

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Wood Ducks vs. Nationals
END:VALARM
DTSTART:20180627T150000Z
DTEND:20180627T180000Z
UID:AQ3kf4GO6XWkxxsmCVm1HC5l@stanza.co
SUMMARY:Wood Ducks vs. Nationals
DESCRIPTION:Wood Ducks vs. Nationals\n\nFollow on MiLB First Pitch: https://stza.co/+w0p2-3U\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144520Z
LAST-MODIFIED:20180213T144520Z
TRANSP:OPAQUE
END:VEVENT
* Wood Ducks vs. Nationals
<2018-06-28 Thu 18:00-21:00>
:PROPERTIES:
:ID:       0VP-zfvdjn5T16Ysv9TK1cLg@stanza.co
:LOCATION: Throwback Thursday Dollar Beer Special
:STATUS:   CONFIRMED
:END:

Wood Ducks vs. Nationals To go with our Throwback Thursday Nights we will also we offering $1 beer and pepsi products.

We are turning back the clock every Thursday this season.The players will be wearing Kinston Indians Jerseys,Game tickets will be $5 and we have $1 beer and Pepsi products.

Follow on MiLB First Pitch  https //stza.co/+w0p4-2b

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Wood Ducks vs. Nationals
END:VALARM
DTSTART:20180628T230000Z
DTEND:20180629T020000Z
UID:0VP-zfvdjn5T16Ysv9TK1cLg@stanza.co
SUMMARY:Wood Ducks vs. Nationals
DESCRIPTION:To go with our Throwback Thursday Nights we will also we offering $1 beer and pepsi products.\n\nWe are turning back the clock every Thursday this season.The players will be wearing Kinston Indians Jerseys,Game tickets will be $5 and we have $1 beer and Pepsi products.\n\nFollow on MiLB First Pitch: https://stza.co/+w0p4-2b\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Throwback Thursday Dollar Beer Special
STATUS:CONFIRMED
CREATED:20180213T144520Z
LAST-MODIFIED:20180213T144520Z
TRANSP:OPAQUE
END:VEVENT
* Wood Ducks vs. Nationals
<2018-06-29 Fri 18:00-21:00>
:PROPERTIES:
:ID:       yzy6tGAX-9s1p3YeruIoWBd0@stanza.co
:LOCATION: Post Game Fireworks Show
:STATUS:   CONFIRMED
:END:

Wood Ducks vs. Nationals 

$3 Mother Earth Drafts.$3 off a game ticket at the box office with beer can.

A fan favorite is returning for a second year. Fridays we will be having food trucks from all over  eastern north Carolina here at the ballpark so you can get a taste of something different.

Follow on MiLB First Pitch  https //stza.co/+w0p6-2y

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Wood Ducks vs. Nationals
END:VALARM
DTSTART:20180629T230000Z
DTEND:20180630T020000Z
UID:yzy6tGAX-9s1p3YeruIoWBd0@stanza.co
SUMMARY:Wood Ducks vs. Nationals
DESCRIPTION:\n\n$3 Mother Earth Drafts.$3 off a game ticket at the box office with beer can.\n\nA fan favorite is returning for a second year. Fridays we will be having food trucks from all over  eastern north Carolina here at the ballpark so you can get a taste of something different.\n\nFollow on MiLB First Pitch: https://stza.co/+w0p6-2y\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Post Game Fireworks Show
STATUS:CONFIRMED
CREATED:20180213T144520Z
LAST-MODIFIED:20180213T144520Z
TRANSP:OPAQUE
END:VEVENT
* Wood Ducks vs. Red Sox
<2018-06-30 Sat 17:00-20:00>
:PROPERTIES:
:ID:       cM0JnqaxeAbboQiXvsrVzwx2@stanza.co
:LOCATION: Patriotic Jersey Giveaway
:STATUS:   CONFIRMED
:END:

Wood Ducks vs. Red Sox The first 1,000 will receive a complimentary Wood Ducks Patriotic Jersey on behalf of Spirit AeroSystems.

Get to the game early to enjoy a Live performance from a local band at the Mother Earth Pavilion.

Bring an empty Pepsi can and receive $3 off a game ticket. This offer is only available at the box office on the day of the game.Premium Giveaways on every Saturday game this year. Get here early in order to be the first to receive the giveaway.

Follow on MiLB First Pitch  https //stza.co/+w0p8-2A

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Wood Ducks vs. Red Sox
END:VALARM
DTSTART:20180630T220000Z
DTEND:20180701T010000Z
UID:cM0JnqaxeAbboQiXvsrVzwx2@stanza.co
SUMMARY:Wood Ducks vs. Red Sox
DESCRIPTION:The first 1,000 will receive a complimentary Wood Ducks Patriotic Jersey on behalf of Spirit AeroSystems.\n\nGet to the game early to enjoy a Live performance from a local band at the Mother Earth Pavilion.\n\nBring an empty Pepsi can and receive $3 off a game ticket. This offer is only available at the box office on the day of the game.Premium Giveaways on every Saturday game this year. Get here early in order to be the first to receive the giveaway.\n\nFollow on MiLB First Pitch: https://stza.co/+w0p8-2A\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Patriotic Jersey Giveaway
STATUS:CONFIRMED
CREATED:20180213T144520Z
LAST-MODIFIED:20180213T144520Z
TRANSP:OPAQUE
END:VEVENT
* Wood Ducks vs. Red Sox
<2018-07-01 Sun 15:00-18:00>
:PROPERTIES:
:ID:       HkS4LjZ1MA615RHFpQqoxCdP@stanza.co
:LOCATION: Sunday Funday
:STATUS:   CONFIRMED
:END:

Wood Ducks vs. Red Sox Pre game Autograph signing from Wood Ducks players and post game run the bases presented by Cricket Wireless of Kinston. All Lil DEWD club members get in for free.

Follow on MiLB First Pitch  https //stza.co/+w0p9-36

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Wood Ducks vs. Red Sox
END:VALARM
DTSTART:20180701T200000Z
DTEND:20180701T230000Z
UID:HkS4LjZ1MA615RHFpQqoxCdP@stanza.co
SUMMARY:Wood Ducks vs. Red Sox
DESCRIPTION:Pre game Autograph signing from Wood Ducks players and post game run the bases presented by Cricket Wireless of Kinston. All Lil DEWD club members get in for free.\n\nFollow on MiLB First Pitch: https://stza.co/+w0p9-36\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Sunday Funday
STATUS:CONFIRMED
CREATED:20180213T144520Z
LAST-MODIFIED:20180213T144520Z
TRANSP:OPAQUE
END:VEVENT
* Wood Ducks vs. Red Sox
<2018-07-02 Mon 18:00-21:00>
:PROPERTIES:
:ID:       n7ATP1K0jXViNMbsJ2ESpcV7@stanza.co
:LOCATION: Dollar Hot Dog Night
:STATUS:   CONFIRMED
:END:

Wood Ducks vs. Red Sox Hot dogs all night long will be one dollar.

Kids under 12 receive free admission with a paying adult. One child per paying adult.

Follow on MiLB First Pitch  https //stza.co/+w0pb-1N

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Wood Ducks vs. Red Sox
END:VALARM
DTSTART:20180702T230000Z
DTEND:20180703T020000Z
UID:n7ATP1K0jXViNMbsJ2ESpcV7@stanza.co
SUMMARY:Wood Ducks vs. Red Sox
DESCRIPTION:Hot dogs all night long will be one dollar.\n\nKids under 12 receive free admission with a paying adult. One child per paying adult.\n\nFollow on MiLB First Pitch: https://stza.co/+w0pb-1N\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Dollar Hot Dog Night
STATUS:CONFIRMED
CREATED:20180213T144520Z
LAST-MODIFIED:20180213T144520Z
TRANSP:OPAQUE
END:VEVENT
* Wood Ducks vs. Red Sox
<2018-07-03 Tue 18:00-21:00>
:PROPERTIES:
:ID:       _C1bkeddyCI-_qhLSwzOMfYg@stanza.co
:LOCATION: Dollar Taco Night
:STATUS:   CONFIRMED
:END:

Wood Ducks vs. Red Sox 



Follow on MiLB First Pitch  https //stza.co/+w0pe-17

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Wood Ducks vs. Red Sox
END:VALARM
DTSTART:20180703T230000Z
DTEND:20180704T020000Z
UID:_C1bkeddyCI-_qhLSwzOMfYg@stanza.co
SUMMARY:Wood Ducks vs. Red Sox
DESCRIPTION:\n\n\n\nFollow on MiLB First Pitch: https://stza.co/+w0pe-17\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Dollar Taco Night
STATUS:CONFIRMED
CREATED:20180213T144520Z
LAST-MODIFIED:20180213T144520Z
TRANSP:OPAQUE
END:VEVENT
* Wood Ducks @ Dash
<2018-07-04 Wed 17:30-20:30>
:PROPERTIES:
:ID:       aznInX42GIjqPZtvySqN3IXP@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Wood Ducks @ Dash Wood Ducks @ Dash

Buy tickets here  https //stza.co/~w0qI

Follow on MiLB First Pitch  https //stza.co/+w0qI-1G

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Wood Ducks @ Dash
END:VALARM
DTSTART:20180704T223000Z
DTEND:20180705T013000Z
UID:aznInX42GIjqPZtvySqN3IXP@stanza.co
SUMMARY:Wood Ducks @ Dash
DESCRIPTION:Wood Ducks @ Dash\n\nBuy tickets here: https://stza.co/~w0qI\n\nFollow on MiLB First Pitch: https://stza.co/+w0qI-1G\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144520Z
LAST-MODIFIED:20180213T144520Z
TRANSP:OPAQUE
END:VEVENT
* Wood Ducks @ Dash
<2018-07-05 Thu 18:00-21:00>
:PROPERTIES:
:ID:       wu1Sx-YXtthqEJSXImiT5c5I@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Wood Ducks @ Dash Wood Ducks @ Dash

Buy tickets here  https //stza.co/~w0qJ

Follow on MiLB First Pitch  https //stza.co/+w0qJ-2u

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Wood Ducks @ Dash
END:VALARM
DTSTART:20180705T230000Z
DTEND:20180706T020000Z
UID:wu1Sx-YXtthqEJSXImiT5c5I@stanza.co
SUMMARY:Wood Ducks @ Dash
DESCRIPTION:Wood Ducks @ Dash\n\nBuy tickets here: https://stza.co/~w0qJ\n\nFollow on MiLB First Pitch: https://stza.co/+w0qJ-2u\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144520Z
LAST-MODIFIED:20180213T144520Z
TRANSP:OPAQUE
END:VEVENT
* Wood Ducks @ Dash
<2018-07-06 Fri 18:00-21:00>
:PROPERTIES:
:ID:       rZwusIh8VMLJQeGiSeMtb_k_@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Wood Ducks @ Dash Wood Ducks @ Dash

Buy tickets here  https //stza.co/~w0qK

Follow on MiLB First Pitch  https //stza.co/+w0qK-2z

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Wood Ducks @ Dash
END:VALARM
DTSTART:20180706T230000Z
DTEND:20180707T020000Z
UID:rZwusIh8VMLJQeGiSeMtb_k_@stanza.co
SUMMARY:Wood Ducks @ Dash
DESCRIPTION:Wood Ducks @ Dash\n\nBuy tickets here: https://stza.co/~w0qK\n\nFollow on MiLB First Pitch: https://stza.co/+w0qK-2z\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144520Z
LAST-MODIFIED:20180213T144520Z
TRANSP:OPAQUE
END:VEVENT
* Wood Ducks @ Dash
<2018-07-07 Sat 17:00-20:00>
:PROPERTIES:
:ID:       mYwO0afzBwT5jHGwlt4Cg06c@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Wood Ducks @ Dash Wood Ducks @ Dash

Buy tickets here  https //stza.co/~w0qL

Follow on MiLB First Pitch  https //stza.co/+w0qL-24

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Wood Ducks @ Dash
END:VALARM
DTSTART:20180707T220000Z
DTEND:20180708T010000Z
UID:mYwO0afzBwT5jHGwlt4Cg06c@stanza.co
SUMMARY:Wood Ducks @ Dash
DESCRIPTION:Wood Ducks @ Dash\n\nBuy tickets here: https://stza.co/~w0qL\n\nFollow on MiLB First Pitch: https://stza.co/+w0qL-24\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144520Z
LAST-MODIFIED:20180213T144520Z
TRANSP:OPAQUE
END:VEVENT
* Wood Ducks @ Dash
<2018-07-08 Sun 13:00-16:00>
:PROPERTIES:
:ID:       Hohz61DUk-WeKb9DFnBLig3W@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Wood Ducks @ Dash Wood Ducks @ Dash

Buy tickets here  https //stza.co/~w0qM

Follow on MiLB First Pitch  https //stza.co/+w0qM-3P

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Wood Ducks @ Dash
END:VALARM
DTSTART:20180708T180000Z
DTEND:20180708T210000Z
UID:Hohz61DUk-WeKb9DFnBLig3W@stanza.co
SUMMARY:Wood Ducks @ Dash
DESCRIPTION:Wood Ducks @ Dash\n\nBuy tickets here: https://stza.co/~w0qM\n\nFollow on MiLB First Pitch: https://stza.co/+w0qM-3P\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144520Z
LAST-MODIFIED:20180213T144520Z
TRANSP:OPAQUE
END:VEVENT
* Wood Ducks @ Astros
<2018-07-09 Mon 18:00-21:00>
:PROPERTIES:
:ID:       RXB8OMhGcQ4iMeYmuQM1lKGM@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Wood Ducks @ Astros Wood Ducks @ Astros

Follow on MiLB First Pitch  https //stza.co/+xM8Y-1K

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Wood Ducks @ Astros
END:VALARM
DTSTART:20180709T230000Z
DTEND:20180710T020000Z
UID:RXB8OMhGcQ4iMeYmuQM1lKGM@stanza.co
SUMMARY:Wood Ducks @ Astros
DESCRIPTION:Wood Ducks @ Astros\n\nFollow on MiLB First Pitch: https://stza.co/+xM8Y-1K\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144520Z
LAST-MODIFIED:20180213T144520Z
TRANSP:OPAQUE
END:VEVENT
* Wood Ducks @ Astros
<2018-07-10 Tue 18:00-21:00>
:PROPERTIES:
:ID:       TOCe3QKhXuZUabbGkwkQK8U5@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Wood Ducks @ Astros Wood Ducks @ Astros

Follow on MiLB First Pitch  https //stza.co/+xM8Z-2u

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Wood Ducks @ Astros
END:VALARM
DTSTART:20180710T230000Z
DTEND:20180711T020000Z
UID:TOCe3QKhXuZUabbGkwkQK8U5@stanza.co
SUMMARY:Wood Ducks @ Astros
DESCRIPTION:Wood Ducks @ Astros\n\nFollow on MiLB First Pitch: https://stza.co/+xM8Z-2u\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144520Z
LAST-MODIFIED:20180213T144520Z
TRANSP:OPAQUE
END:VEVENT
* Wood Ducks @ Astros
<2018-07-11 Wed 18:00-21:00>
:PROPERTIES:
:ID:       EvB1DVt8yPhh6V8pa0xgtKbF@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Wood Ducks @ Astros Wood Ducks @ Astros

Follow on MiLB First Pitch  https //stza.co/+xM8_-31

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Wood Ducks @ Astros
END:VALARM
DTSTART:20180711T230000Z
DTEND:20180712T020000Z
UID:EvB1DVt8yPhh6V8pa0xgtKbF@stanza.co
SUMMARY:Wood Ducks @ Astros
DESCRIPTION:Wood Ducks @ Astros\n\nFollow on MiLB First Pitch: https://stza.co/+xM8_-31\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144520Z
LAST-MODIFIED:20180213T144520Z
TRANSP:OPAQUE
END:VEVENT
* Wood Ducks @ Astros
<2018-07-12 Thu 18:00-21:00>
:PROPERTIES:
:ID:       pqTYCFEDNtVmJPRBLcPyoZb2@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Wood Ducks @ Astros Wood Ducks @ Astros

Follow on MiLB First Pitch  https //stza.co/+xM8$-9

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Wood Ducks @ Astros
END:VALARM
DTSTART:20180712T230000Z
DTEND:20180713T020000Z
UID:pqTYCFEDNtVmJPRBLcPyoZb2@stanza.co
SUMMARY:Wood Ducks @ Astros
DESCRIPTION:Wood Ducks @ Astros\n\nFollow on MiLB First Pitch: https://stza.co/+xM8$-9\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144520Z
LAST-MODIFIED:20180213T144520Z
TRANSP:OPAQUE
END:VEVENT
* Wood Ducks vs. Pelicans
<2018-07-13 Fri 18:00-21:00>
:PROPERTIES:
:ID:       _vIxiZxNV85fLihEjFHLVZFU@stanza.co
:LOCATION: Mother Earth Friday
:STATUS:   CONFIRMED
:END:

Wood Ducks vs. Pelicans $3 Mother Earth Drafts.$3 off a game ticket at the box office with beer can.

A fan favorite is returning for a second year. Fridays we will be having food trucks from all over  eastern north Carolina here at the ballpark so you can get a taste of something different.



Follow on MiLB First Pitch  https //stza.co/+w0pg-q

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Wood Ducks vs. Pelicans
END:VALARM
DTSTART:20180713T230000Z
DTEND:20180714T020000Z
UID:_vIxiZxNV85fLihEjFHLVZFU@stanza.co
SUMMARY:Wood Ducks vs. Pelicans
DESCRIPTION:$3 Mother Earth Drafts.$3 off a game ticket at the box office with beer can.\n\nA fan favorite is returning for a second year. Fridays we will be having food trucks from all over  eastern north Carolina here at the ballpark so you can get a taste of something different.\n\n\n\nFollow on MiLB First Pitch: https://stza.co/+w0pg-q\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Mother Earth Friday
STATUS:CONFIRMED
CREATED:20180213T144520Z
LAST-MODIFIED:20180213T144520Z
TRANSP:OPAQUE
END:VEVENT
* Wood Ducks vs. Pelicans
<2018-07-14 Sat 17:00-20:00>
:PROPERTIES:
:ID:       PiTHyeJsjD8uY2L4zQdxMEHO@stanza.co
:LOCATION: Christmas Ornament Giveaway
:STATUS:   CONFIRMED
:END:

Wood Ducks vs. Pelicans Be one of the first 1,000 fans and receive a Christmas Ornament on behalf of Piggly Wiggly Fresh Buy & Bush's Beans.

We will be wearing Tacky Christmas Sweater Jerseys and auctioning them off after the game.

Only 200 tickets available in the NEW Mother Earth Pavilion so get them while you can. They will sell out fast.

Bring an empty Pepsi can and receive $3 off a game ticket. This offer is only available at the box office on the day of the game.Premium Giveaways on every Saturday game this year. Get here early in order to be the first to receive the giveaway.

Follow on MiLB First Pitch  https //stza.co/+w0ph-q

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Wood Ducks vs. Pelicans
END:VALARM
DTSTART:20180714T220000Z
DTEND:20180715T010000Z
UID:PiTHyeJsjD8uY2L4zQdxMEHO@stanza.co
SUMMARY:Wood Ducks vs. Pelicans
DESCRIPTION:Be one of the first 1,000 fans and receive a Christmas Ornament on behalf of Piggly Wiggly Fresh Buy & Bush's Beans.\n\nWe will be wearing Tacky Christmas Sweater Jerseys and auctioning them off after the game.\n\nOnly 200 tickets available in the NEW Mother Earth Pavilion so get them while you can. They will sell out fast.\n\nBring an empty Pepsi can and receive $3 off a game ticket. This offer is only available at the box office on the day of the game.Premium Giveaways on every Saturday game this year. Get here early in order to be the first to receive the giveaway.\n\nFollow on MiLB First Pitch: https://stza.co/+w0ph-q\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Christmas Ornament Giveaway
STATUS:CONFIRMED
CREATED:20180213T144520Z
LAST-MODIFIED:20180213T144520Z
TRANSP:OPAQUE
END:VEVENT
* Wood Ducks vs. Pelicans
<2018-07-15 Sun 15:00-18:00>
:PROPERTIES:
:ID:       xvS6NTdDH7hzFfjZXqLScJJl@stanza.co
:LOCATION: Sunday Funday
:STATUS:   CONFIRMED
:END:

Wood Ducks vs. Pelicans Pre game Autograph signing from Wood Ducks players and post game run the bases presented by Cricket Wireless of Kinston. All Lil DEWD club members get in for free.

Follow on MiLB First Pitch  https //stza.co/+w0pk-1T

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Wood Ducks vs. Pelicans
END:VALARM
DTSTART:20180715T200000Z
DTEND:20180715T230000Z
UID:xvS6NTdDH7hzFfjZXqLScJJl@stanza.co
SUMMARY:Wood Ducks vs. Pelicans
DESCRIPTION:Pre game Autograph signing from Wood Ducks players and post game run the bases presented by Cricket Wireless of Kinston. All Lil DEWD club members get in for free.\n\nFollow on MiLB First Pitch: https://stza.co/+w0pk-1T\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Sunday Funday
STATUS:CONFIRMED
CREATED:20180213T144520Z
LAST-MODIFIED:20180213T144520Z
TRANSP:OPAQUE
END:VEVENT
* Wood Ducks vs. Pelicans
<2018-07-16 Mon 18:00-21:00>
:PROPERTIES:
:ID:       ZtioUshLUj1Ay-fw-qfwxk2B@stanza.co
:LOCATION: Dollar Hot Dog Night
:STATUS:   CONFIRMED
:END:

Wood Ducks vs. Pelicans Hot dogs all night long will be one dollar.

Kids under 12 receive free admission with a paying adult. One child per paying adult.

Follow on MiLB First Pitch  https //stza.co/+w0pm-2H

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Wood Ducks vs. Pelicans
END:VALARM
DTSTART:20180716T230000Z
DTEND:20180717T020000Z
UID:ZtioUshLUj1Ay-fw-qfwxk2B@stanza.co
SUMMARY:Wood Ducks vs. Pelicans
DESCRIPTION:Hot dogs all night long will be one dollar.\n\nKids under 12 receive free admission with a paying adult. One child per paying adult.\n\nFollow on MiLB First Pitch: https://stza.co/+w0pm-2H\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Dollar Hot Dog Night
STATUS:CONFIRMED
CREATED:20180213T144520Z
LAST-MODIFIED:20180213T144520Z
TRANSP:OPAQUE
END:VEVENT
* Wood Ducks @ Keys
<2018-07-18 Wed 18:00-21:00>
:PROPERTIES:
:ID:       UEFqmO5WtOAy6epyXZ9khTN1@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Wood Ducks @ Keys Wood Ducks @ Keys

Follow on MiLB First Pitch  https //stza.co/+wg9o-3_

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Wood Ducks @ Keys
END:VALARM
DTSTART:20180718T230000Z
DTEND:20180719T020000Z
UID:UEFqmO5WtOAy6epyXZ9khTN1@stanza.co
SUMMARY:Wood Ducks @ Keys
DESCRIPTION:Wood Ducks @ Keys\n\nFollow on MiLB First Pitch: https://stza.co/+wg9o-3_\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144520Z
LAST-MODIFIED:20180213T144520Z
TRANSP:OPAQUE
END:VEVENT
* Wood Ducks @ Keys
<2018-07-19 Thu 18:00-21:00>
:PROPERTIES:
:ID:       cqbRoy0ofPh7la1_k54M2YPg@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Wood Ducks @ Keys Wood Ducks @ Keys

Follow on MiLB First Pitch  https //stza.co/+wg9p-Y

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Wood Ducks @ Keys
END:VALARM
DTSTART:20180719T230000Z
DTEND:20180720T020000Z
UID:cqbRoy0ofPh7la1_k54M2YPg@stanza.co
SUMMARY:Wood Ducks @ Keys
DESCRIPTION:Wood Ducks @ Keys\n\nFollow on MiLB First Pitch: https://stza.co/+wg9p-Y\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144520Z
LAST-MODIFIED:20180213T144520Z
TRANSP:OPAQUE
END:VEVENT
* Wood Ducks @ Keys
<2018-07-20 Fri 18:00-21:00>
:PROPERTIES:
:ID:       iSQETAS570RHVawDdeGfMvib@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Wood Ducks @ Keys Wood Ducks @ Keys

Follow on MiLB First Pitch  https //stza.co/+wg9q-b

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Wood Ducks @ Keys
END:VALARM
DTSTART:20180720T230000Z
DTEND:20180721T020000Z
UID:iSQETAS570RHVawDdeGfMvib@stanza.co
SUMMARY:Wood Ducks @ Keys
DESCRIPTION:Wood Ducks @ Keys\n\nFollow on MiLB First Pitch: https://stza.co/+wg9q-b\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144520Z
LAST-MODIFIED:20180213T144520Z
TRANSP:OPAQUE
END:VEVENT
* Wood Ducks @ Astros
<2018-07-21 Sat 17:00-20:00>
:PROPERTIES:
:ID:       D3ratti53cUfIfJiXKvtc9Kk@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Wood Ducks @ Astros Wood Ducks @ Astros

Follow on MiLB First Pitch  https //stza.co/+xM90-y

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Wood Ducks @ Astros
END:VALARM
DTSTART:20180721T220000Z
DTEND:20180722T010000Z
UID:D3ratti53cUfIfJiXKvtc9Kk@stanza.co
SUMMARY:Wood Ducks @ Astros
DESCRIPTION:Wood Ducks @ Astros\n\nFollow on MiLB First Pitch: https://stza.co/+xM90-y\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144520Z
LAST-MODIFIED:20180213T144520Z
TRANSP:OPAQUE
END:VEVENT
* Wood Ducks @ Astros
<2018-07-22 Sun 13:00-16:00>
:PROPERTIES:
:ID:       ARvyyWNfmMzXGWmFPCag40bs@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Wood Ducks @ Astros Wood Ducks @ Astros

Follow on MiLB First Pitch  https //stza.co/+xM91-1g

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Wood Ducks @ Astros
END:VALARM
DTSTART:20180722T180000Z
DTEND:20180722T210000Z
UID:ARvyyWNfmMzXGWmFPCag40bs@stanza.co
SUMMARY:Wood Ducks @ Astros
DESCRIPTION:Wood Ducks @ Astros\n\nFollow on MiLB First Pitch: https://stza.co/+xM91-1g\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144520Z
LAST-MODIFIED:20180213T144520Z
TRANSP:OPAQUE
END:VEVENT
* Wood Ducks @ Astros
<2018-07-23 Mon 18:00-21:00>
:PROPERTIES:
:ID:       US1TDTaWFp9xwzIeIruK74se@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Wood Ducks @ Astros Wood Ducks @ Astros

Follow on MiLB First Pitch  https //stza.co/+xM92-1t

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Wood Ducks @ Astros
END:VALARM
DTSTART:20180723T230000Z
DTEND:20180724T020000Z
UID:US1TDTaWFp9xwzIeIruK74se@stanza.co
SUMMARY:Wood Ducks @ Astros
DESCRIPTION:Wood Ducks @ Astros\n\nFollow on MiLB First Pitch: https://stza.co/+xM92-1t\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144520Z
LAST-MODIFIED:20180213T144520Z
TRANSP:OPAQUE
END:VEVENT
* Wood Ducks vs. Hillcats
<2018-07-24 Tue 18:00-21:00>
:PROPERTIES:
:ID:       sYmDJss2EvVYkTVN1cfHvGSV@stanza.co
:LOCATION: Dollar Taco Night
:STATUS:   CONFIRMED
:END:

Wood Ducks vs. Hillcats 

With your food lion MVP card you can receive our BOGO ticket offer on Tuesdays except July 3.

Follow on MiLB First Pitch  https //stza.co/+w0pn-38

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Wood Ducks vs. Hillcats
END:VALARM
DTSTART:20180724T230000Z
DTEND:20180725T020000Z
UID:sYmDJss2EvVYkTVN1cfHvGSV@stanza.co
SUMMARY:Wood Ducks vs. Hillcats
DESCRIPTION:\n\nWith your food lion MVP card you can receive our BOGO ticket offer on Tuesdays except July 3.\n\nFollow on MiLB First Pitch: https://stza.co/+w0pn-38\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Dollar Taco Night
STATUS:CONFIRMED
CREATED:20180213T144520Z
LAST-MODIFIED:20180213T144520Z
TRANSP:OPAQUE
END:VEVENT
* Wood Ducks vs. Hillcats
<2018-07-25 Wed 11:05-14:05>
:PROPERTIES:
:ID:       biIdMA5ENk4AVUgU48QmBOYN@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Wood Ducks vs. Hillcats Wood Ducks vs. Hillcats

Follow on MiLB First Pitch  https //stza.co/+w0pq-d

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Wood Ducks vs. Hillcats
END:VALARM
DTSTART:20180725T160500Z
DTEND:20180725T190500Z
UID:biIdMA5ENk4AVUgU48QmBOYN@stanza.co
SUMMARY:Wood Ducks vs. Hillcats
DESCRIPTION:Wood Ducks vs. Hillcats\n\nFollow on MiLB First Pitch: https://stza.co/+w0pq-d\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144520Z
LAST-MODIFIED:20180213T144520Z
TRANSP:OPAQUE
END:VEVENT
* Wood Ducks vs. Hillcats
<2018-07-26 Thu 18:00-21:00>
:PROPERTIES:
:ID:       sGWFp8W64ARcH04udD_hBVKC@stanza.co
:LOCATION: Throwback Thursday Dollar Beer Special
:STATUS:   CONFIRMED
:END:

Wood Ducks vs. Hillcats To go with our Throwback Thursday Nights we will also we offering $1 beer and pepsi products.

We are turning back the clock every Thursday this season.The players will be wearing Kinston Indians Jerseys,Game tickets will be $5 and we have $1 beer and Pepsi products.

Follow on MiLB First Pitch  https //stza.co/+w0pr-2x

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Wood Ducks vs. Hillcats
END:VALARM
DTSTART:20180726T230000Z
DTEND:20180727T020000Z
UID:sGWFp8W64ARcH04udD_hBVKC@stanza.co
SUMMARY:Wood Ducks vs. Hillcats
DESCRIPTION:To go with our Throwback Thursday Nights we will also we offering $1 beer and pepsi products.\n\nWe are turning back the clock every Thursday this season.The players will be wearing Kinston Indians Jerseys,Game tickets will be $5 and we have $1 beer and Pepsi products.\n\nFollow on MiLB First Pitch: https://stza.co/+w0pr-2x\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Throwback Thursday Dollar Beer Special
STATUS:CONFIRMED
CREATED:20180213T144520Z
LAST-MODIFIED:20180213T144520Z
TRANSP:OPAQUE
END:VEVENT
* Wood Ducks vs. Keys
<2018-07-27 Fri 18:00-21:00>
:PROPERTIES:
:ID:       AN4TGbFgo7b-eOG-f_-zF_By@stanza.co
:LOCATION: Post Game Fireworks Show
:STATUS:   CONFIRMED
:END:

Wood Ducks vs. Keys 

$3 Mother Earth Drafts.$3 off a game ticket at the box office with beer can.

A fan favorite is returning for a second year. Fridays we will be having food trucks from all over  eastern north Carolina here at the ballpark so you can get a taste of something different.

Follow on MiLB First Pitch  https //stza.co/+w0pu-3f

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Wood Ducks vs. Keys
END:VALARM
DTSTART:20180727T230000Z
DTEND:20180728T020000Z
UID:AN4TGbFgo7b-eOG-f_-zF_By@stanza.co
SUMMARY:Wood Ducks vs. Keys
DESCRIPTION:\n\n$3 Mother Earth Drafts.$3 off a game ticket at the box office with beer can.\n\nA fan favorite is returning for a second year. Fridays we will be having food trucks from all over  eastern north Carolina here at the ballpark so you can get a taste of something different.\n\nFollow on MiLB First Pitch: https://stza.co/+w0pu-3f\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Post Game Fireworks Show
STATUS:CONFIRMED
CREATED:20180213T144520Z
LAST-MODIFIED:20180213T144520Z
TRANSP:OPAQUE
END:VEVENT
* Wood Ducks vs. Keys
<2018-07-28 Sat 17:00-20:00>
:PROPERTIES:
:ID:       NVbf-nRS3G9Tv02hZ1qMu8xe@stanza.co
:LOCATION: Camo Jersey Giveaway
:STATUS:   CONFIRMED
:END:

Wood Ducks vs. Keys Be one of the first 1,000 fans and receive a Camo Jersey on behalf of Mountain Dew.

Bring an empty Pepsi can and receive $3 off a game ticket. This offer is only available at the box office on the day of the game.Premium Giveaways on every Saturday game this year. Get here early in order to be the first to receive the giveaway.

Follow on MiLB First Pitch  https //stza.co/+w0pv-16

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Wood Ducks vs. Keys
END:VALARM
DTSTART:20180728T220000Z
DTEND:20180729T010000Z
UID:NVbf-nRS3G9Tv02hZ1qMu8xe@stanza.co
SUMMARY:Wood Ducks vs. Keys
DESCRIPTION:Be one of the first 1,000 fans and receive a Camo Jersey on behalf of Mountain Dew.\n\nBring an empty Pepsi can and receive $3 off a game ticket. This offer is only available at the box office on the day of the game.Premium Giveaways on every Saturday game this year. Get here early in order to be the first to receive the giveaway.\n\nFollow on MiLB First Pitch: https://stza.co/+w0pv-16\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Camo Jersey Giveaway
STATUS:CONFIRMED
CREATED:20180213T144520Z
LAST-MODIFIED:20180213T144520Z
TRANSP:OPAQUE
END:VEVENT
* Wood Ducks vs. Keys
<2018-07-29 Sun 15:00-18:00>
:PROPERTIES:
:ID:       Oqzy9DVjFkqWvD0QFvZgHYup@stanza.co
:LOCATION: Sunday Funday
:STATUS:   CONFIRMED
:END:

Wood Ducks vs. Keys Pre game Autograph signing from Wood Ducks players and post game run the bases presented by Cricket Wireless of Kinston. All Lil DEWD club members get in for free.

Follow on MiLB First Pitch  https //stza.co/+w0py-3F

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Wood Ducks vs. Keys
END:VALARM
DTSTART:20180729T200000Z
DTEND:20180729T230000Z
UID:Oqzy9DVjFkqWvD0QFvZgHYup@stanza.co
SUMMARY:Wood Ducks vs. Keys
DESCRIPTION:Pre game Autograph signing from Wood Ducks players and post game run the bases presented by Cricket Wireless of Kinston. All Lil DEWD club members get in for free.\n\nFollow on MiLB First Pitch: https://stza.co/+w0py-3F\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Sunday Funday
STATUS:CONFIRMED
CREATED:20180213T144520Z
LAST-MODIFIED:20180213T144520Z
TRANSP:OPAQUE
END:VEVENT
* Wood Ducks @ Pelicans
<2018-07-31 Tue>--<2018-07-30 Mon>
:PROPERTIES:
:ID:       QPYmm13_PbAaa7d6gZFDVK5S@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Wood Ducks @ Pelicans Wood Ducks @ Pelicans

Follow on MiLB First Pitch  https //stza.co/+w0qo-l

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Wood Ducks @ Pelicans
END:VALARM
DTSTART;VALUE=DATE:20180731
DTEND;VALUE=DATE:20180731
UID:QPYmm13_PbAaa7d6gZFDVK5S@stanza.co
SUMMARY:Wood Ducks @ Pelicans
DESCRIPTION:Wood Ducks @ Pelicans\n\nFollow on MiLB First Pitch: https://stza.co/+w0qo-l\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144520Z
LAST-MODIFIED:20180213T144520Z
TRANSP:OPAQUE
END:VEVENT
* Wood Ducks @ Pelicans
<2018-08-01 Wed>--<2018-07-31 Tue>
:PROPERTIES:
:ID:       eyIDFxozqrZGciSCOFvlwTUS@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Wood Ducks @ Pelicans Wood Ducks @ Pelicans

Follow on MiLB First Pitch  https //stza.co/+w0qp-S

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Wood Ducks @ Pelicans
END:VALARM
DTSTART;VALUE=DATE:20180801
DTEND;VALUE=DATE:20180801
UID:eyIDFxozqrZGciSCOFvlwTUS@stanza.co
SUMMARY:Wood Ducks @ Pelicans
DESCRIPTION:Wood Ducks @ Pelicans\n\nFollow on MiLB First Pitch: https://stza.co/+w0qp-S\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144520Z
LAST-MODIFIED:20180213T144520Z
TRANSP:OPAQUE
END:VEVENT
* Wood Ducks @ Pelicans
<2018-08-02 Thu>--<2018-08-01 Wed>
:PROPERTIES:
:ID:       hpxkRiuh_Xc1Nkt-N-e1Fik3@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Wood Ducks @ Pelicans Wood Ducks @ Pelicans

Follow on MiLB First Pitch  https //stza.co/+w0qq-2G

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Wood Ducks @ Pelicans
END:VALARM
DTSTART;VALUE=DATE:20180802
DTEND;VALUE=DATE:20180802
UID:hpxkRiuh_Xc1Nkt-N-e1Fik3@stanza.co
SUMMARY:Wood Ducks @ Pelicans
DESCRIPTION:Wood Ducks @ Pelicans\n\nFollow on MiLB First Pitch: https://stza.co/+w0qq-2G\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144520Z
LAST-MODIFIED:20180213T144520Z
TRANSP:OPAQUE
END:VEVENT
* Wood Ducks vs. Dash
<2018-08-03 Fri 18:00-21:00>
:PROPERTIES:
:ID:       umWIjg3ni7YDTGZt5-Umoiej@stanza.co
:LOCATION: Post Game Fireworks Show
:STATUS:   CONFIRMED
:END:

Wood Ducks vs. Dash 

$3 Mother Earth Drafts.$3 off a game ticket at the box office with beer can.

A fan favorite is returning for a second year. Fridays we will be having food trucks from all over  eastern north Carolina here at the ballpark so you can get a taste of something different.

Follow on MiLB First Pitch  https //stza.co/+w0pz-1t

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Wood Ducks vs. Dash
END:VALARM
DTSTART:20180803T230000Z
DTEND:20180804T020000Z
UID:umWIjg3ni7YDTGZt5-Umoiej@stanza.co
SUMMARY:Wood Ducks vs. Dash
DESCRIPTION:\n\n$3 Mother Earth Drafts.$3 off a game ticket at the box office with beer can.\n\nA fan favorite is returning for a second year. Fridays we will be having food trucks from all over  eastern north Carolina here at the ballpark so you can get a taste of something different.\n\nFollow on MiLB First Pitch: https://stza.co/+w0pz-1t\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Post Game Fireworks Show
STATUS:CONFIRMED
CREATED:20180213T144520Z
LAST-MODIFIED:20180213T144520Z
TRANSP:OPAQUE
END:VEVENT
* Wood Ducks vs. Dash
<2018-08-04 Sat 17:00-20:00>
:PROPERTIES:
:ID:       iv7m6ZEC6kmz0vBPu7gB6NM-@stanza.co
:LOCATION: Youth Sock Giveaway
:STATUS:   CONFIRMED
:END:

Wood Ducks vs. Dash The first 500 youth 12 years and younger will receive a complimentary pair of Wood Duck socks on behalf of Piggly Wiggly Fresh Buy & Sweet Baby Rays.

Bring an empty Pepsi can and receive $3 off a game ticket. This offer is only available at the box office on the day of the game.Premium Giveaways on every Saturday game this year. Get here early in order to be the first to receive the giveaway.

Follow on MiLB First Pitch  https //stza.co/+w0pB-3D

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Wood Ducks vs. Dash
END:VALARM
DTSTART:20180804T220000Z
DTEND:20180805T010000Z
UID:iv7m6ZEC6kmz0vBPu7gB6NM-@stanza.co
SUMMARY:Wood Ducks vs. Dash
DESCRIPTION:The first 500 youth 12 years and younger will receive a complimentary pair of Wood Duck socks on behalf of Piggly Wiggly Fresh Buy & Sweet Baby Rays.\n\nBring an empty Pepsi can and receive $3 off a game ticket. This offer is only available at the box office on the day of the game.Premium Giveaways on every Saturday game this year. Get here early in order to be the first to receive the giveaway.\n\nFollow on MiLB First Pitch: https://stza.co/+w0pB-3D\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Youth Sock Giveaway
STATUS:CONFIRMED
CREATED:20180213T144520Z
LAST-MODIFIED:20180213T144520Z
TRANSP:OPAQUE
END:VEVENT
* Wood Ducks vs. Dash
<2018-08-05 Sun 13:00-16:00>
:PROPERTIES:
:ID:       B-yVZ2Wyg1maBAJhD-1J0Htu@stanza.co
:LOCATION: Sunday Funday
:STATUS:   CONFIRMED
:END:

Wood Ducks vs. Dash Pre game Autograph signing from Wood Ducks players and post game run the bases presented by Cricket Wireless of Kinston. All Lil DEWD club members get in for free.

Follow on MiLB First Pitch  https //stza.co/+w0pD-1X

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Wood Ducks vs. Dash
END:VALARM
DTSTART:20180805T180000Z
DTEND:20180805T210000Z
UID:B-yVZ2Wyg1maBAJhD-1J0Htu@stanza.co
SUMMARY:Wood Ducks vs. Dash
DESCRIPTION:Pre game Autograph signing from Wood Ducks players and post game run the bases presented by Cricket Wireless of Kinston. All Lil DEWD club members get in for free.\n\nFollow on MiLB First Pitch: https://stza.co/+w0pD-1X\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Sunday Funday
STATUS:CONFIRMED
CREATED:20180213T144520Z
LAST-MODIFIED:20180213T144520Z
TRANSP:OPAQUE
END:VEVENT
* Wood Ducks vs. Astros
<2018-08-07 Tue 18:00-21:00>
:PROPERTIES:
:ID:       wX3To4XCt9u7_5yCr9yj93Db@stanza.co
:LOCATION: Dollar Taco Night
:STATUS:   CONFIRMED
:END:

Wood Ducks vs. Astros 

With your food lion MVP card you can receive our BOGO ticket offer on Tuesdays except July 3.

Follow on MiLB First Pitch  https //stza.co/+w0pG-4

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Wood Ducks vs. Astros
END:VALARM
DTSTART:20180807T230000Z
DTEND:20180808T020000Z
UID:wX3To4XCt9u7_5yCr9yj93Db@stanza.co
SUMMARY:Wood Ducks vs. Astros
DESCRIPTION:\n\nWith your food lion MVP card you can receive our BOGO ticket offer on Tuesdays except July 3.\n\nFollow on MiLB First Pitch: https://stza.co/+w0pG-4\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Dollar Taco Night
STATUS:CONFIRMED
CREATED:20180213T144520Z
LAST-MODIFIED:20180213T144520Z
TRANSP:OPAQUE
END:VEVENT
* Wood Ducks vs. Astros
<2018-08-08 Wed 18:00-21:00>
:PROPERTIES:
:ID:       v_ardL16CcuGGOqH6WAnBpQ1@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Wood Ducks vs. Astros Wood Ducks vs. Astros

Follow on MiLB First Pitch  https //stza.co/+w0pH-3A

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Wood Ducks vs. Astros
END:VALARM
DTSTART:20180808T230000Z
DTEND:20180809T020000Z
UID:v_ardL16CcuGGOqH6WAnBpQ1@stanza.co
SUMMARY:Wood Ducks vs. Astros
DESCRIPTION:Wood Ducks vs. Astros\n\nFollow on MiLB First Pitch: https://stza.co/+w0pH-3A\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144520Z
LAST-MODIFIED:20180213T144520Z
TRANSP:OPAQUE
END:VEVENT
* Wood Ducks vs. Astros
<2018-08-09 Thu 18:00-21:00>
:PROPERTIES:
:ID:       k5z1nihAlfybht7wB8XVO9zK@stanza.co
:LOCATION: Throwback Thursday Dollar Beer Special
:STATUS:   CONFIRMED
:END:

Wood Ducks vs. Astros To go with our Throwback Thursday Nights we will also we offering $1 beer and pepsi products.

We are turning back the clock every Thursday this season.The players will be wearing Kinston Indians Jerseys,Game tickets will be $5 and we have $1 beer and Pepsi products.

Follow on MiLB First Pitch  https //stza.co/+w0pK-_

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Wood Ducks vs. Astros
END:VALARM
DTSTART:20180809T230000Z
DTEND:20180810T020000Z
UID:k5z1nihAlfybht7wB8XVO9zK@stanza.co
SUMMARY:Wood Ducks vs. Astros
DESCRIPTION:To go with our Throwback Thursday Nights we will also we offering $1 beer and pepsi products.\n\nWe are turning back the clock every Thursday this season.The players will be wearing Kinston Indians Jerseys,Game tickets will be $5 and we have $1 beer and Pepsi products.\n\nFollow on MiLB First Pitch: https://stza.co/+w0pK-_\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Throwback Thursday Dollar Beer Special
STATUS:CONFIRMED
CREATED:20180213T144520Z
LAST-MODIFIED:20180213T144520Z
TRANSP:OPAQUE
END:VEVENT
* Wood Ducks @ Hillcats
<2018-08-10 Fri 17:30-20:30>
:PROPERTIES:
:ID:       XKLtTLLhb2-lkilyEDoO6rET@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Wood Ducks @ Hillcats Wood Ducks @ Hillcats

Buy tickets here  https //stza.co/~y3Tr

Follow on MiLB First Pitch  https //stza.co/+y3Tr-1h

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Wood Ducks @ Hillcats
END:VALARM
DTSTART:20180810T223000Z
DTEND:20180811T013000Z
UID:XKLtTLLhb2-lkilyEDoO6rET@stanza.co
SUMMARY:Wood Ducks @ Hillcats
DESCRIPTION:Wood Ducks @ Hillcats\n\nBuy tickets here: https://stza.co/~y3Tr\n\nFollow on MiLB First Pitch: https://stza.co/+y3Tr-1h\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144520Z
LAST-MODIFIED:20180213T144520Z
TRANSP:OPAQUE
END:VEVENT
* Wood Ducks @ Hillcats
<2018-08-11 Sat 17:00-20:00>
:PROPERTIES:
:ID:       s3haUOqcn-bVFronfNVQFPkS@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Wood Ducks @ Hillcats Wood Ducks @ Hillcats

Buy tickets here  https //stza.co/~y3Ts

Follow on MiLB First Pitch  https //stza.co/+y3Ts-E

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Wood Ducks @ Hillcats
END:VALARM
DTSTART:20180811T220000Z
DTEND:20180812T010000Z
UID:s3haUOqcn-bVFronfNVQFPkS@stanza.co
SUMMARY:Wood Ducks @ Hillcats
DESCRIPTION:Wood Ducks @ Hillcats\n\nBuy tickets here: https://stza.co/~y3Ts\n\nFollow on MiLB First Pitch: https://stza.co/+y3Ts-E\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144520Z
LAST-MODIFIED:20180213T144520Z
TRANSP:OPAQUE
END:VEVENT
* Wood Ducks @ Hillcats
<2018-08-12 Sun 16:00-19:00>
:PROPERTIES:
:ID:       nnYi8x7UQ6LAdWYAWTfPMewg@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Wood Ducks @ Hillcats Wood Ducks @ Hillcats

Buy tickets here  https //stza.co/~y3Tt

Follow on MiLB First Pitch  https //stza.co/+y3Tt-1E

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Wood Ducks @ Hillcats
END:VALARM
DTSTART:20180812T210000Z
DTEND:20180813T000000Z
UID:nnYi8x7UQ6LAdWYAWTfPMewg@stanza.co
SUMMARY:Wood Ducks @ Hillcats
DESCRIPTION:Wood Ducks @ Hillcats\n\nBuy tickets here: https://stza.co/~y3Tt\n\nFollow on MiLB First Pitch: https://stza.co/+y3Tt-1E\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144520Z
LAST-MODIFIED:20180213T144520Z
TRANSP:OPAQUE
END:VEVENT
* Wood Ducks vs. Mudcats
<2018-08-14 Tue 18:00-21:00>
:PROPERTIES:
:ID:       5S7HjLnJj1Ki2Wh9C8iH8ok0@stanza.co
:LOCATION: Dollar Taco Night
:STATUS:   CONFIRMED
:END:

Wood Ducks vs. Mudcats 

With your food lion MVP card you can receive our BOGO ticket offer on Tuesdays except July 3.

Follow on MiLB First Pitch  https //stza.co/+w0pM-27

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Wood Ducks vs. Mudcats
END:VALARM
DTSTART:20180814T230000Z
DTEND:20180815T020000Z
UID:5S7HjLnJj1Ki2Wh9C8iH8ok0@stanza.co
SUMMARY:Wood Ducks vs. Mudcats
DESCRIPTION:\n\nWith your food lion MVP card you can receive our BOGO ticket offer on Tuesdays except July 3.\n\nFollow on MiLB First Pitch: https://stza.co/+w0pM-27\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Dollar Taco Night
STATUS:CONFIRMED
CREATED:20180213T144520Z
LAST-MODIFIED:20180213T144520Z
TRANSP:OPAQUE
END:VEVENT
* Wood Ducks vs. Mudcats
<2018-08-15 Wed 18:00-21:00>
:PROPERTIES:
:ID:       VWnw8mPJxBzxTvbs7vg3laDn@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Wood Ducks vs. Mudcats Wood Ducks vs. Mudcats

Follow on MiLB First Pitch  https //stza.co/+w0pN-1G

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Wood Ducks vs. Mudcats
END:VALARM
DTSTART:20180815T230000Z
DTEND:20180816T020000Z
UID:VWnw8mPJxBzxTvbs7vg3laDn@stanza.co
SUMMARY:Wood Ducks vs. Mudcats
DESCRIPTION:Wood Ducks vs. Mudcats\n\nFollow on MiLB First Pitch: https://stza.co/+w0pN-1G\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144520Z
LAST-MODIFIED:20180213T144520Z
TRANSP:OPAQUE
END:VEVENT
* Wood Ducks vs. Mudcats
<2018-08-16 Thu 18:00-21:00>
:PROPERTIES:
:ID:       RXvB1RDHCuw5Y8TP9nkNVgrg@stanza.co
:LOCATION: Throwback Thursday Dollar Beer Special
:STATUS:   CONFIRMED
:END:

Wood Ducks vs. Mudcats To go with our Throwback Thursday Nights we will also we offering $1 beer and pepsi products.

We are turning back the clock every Thursday this season.The players will be wearing Kinston Indians Jerseys,Game tickets will be $5 and we have $1 beer and Pepsi products.

Follow on MiLB First Pitch  https //stza.co/+w0pQ-3o

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Wood Ducks vs. Mudcats
END:VALARM
DTSTART:20180816T230000Z
DTEND:20180817T020000Z
UID:RXvB1RDHCuw5Y8TP9nkNVgrg@stanza.co
SUMMARY:Wood Ducks vs. Mudcats
DESCRIPTION:To go with our Throwback Thursday Nights we will also we offering $1 beer and pepsi products.\n\nWe are turning back the clock every Thursday this season.The players will be wearing Kinston Indians Jerseys,Game tickets will be $5 and we have $1 beer and Pepsi products.\n\nFollow on MiLB First Pitch: https://stza.co/+w0pQ-3o\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Throwback Thursday Dollar Beer Special
STATUS:CONFIRMED
CREATED:20180213T144520Z
LAST-MODIFIED:20180213T144520Z
TRANSP:OPAQUE
END:VEVENT
* Wood Ducks @ Red Sox
<2018-08-17 Fri>--<2018-08-16 Thu>
:PROPERTIES:
:ID:       C2jpym2kaXeKCe8QmRCXncub@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Wood Ducks @ Red Sox Wood Ducks @ Red Sox

Follow on MiLB First Pitch  https //stza.co/+w0qu-31

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Wood Ducks @ Red Sox
END:VALARM
DTSTART;VALUE=DATE:20180817
DTEND;VALUE=DATE:20180817
UID:C2jpym2kaXeKCe8QmRCXncub@stanza.co
SUMMARY:Wood Ducks @ Red Sox
DESCRIPTION:Wood Ducks @ Red Sox\n\nFollow on MiLB First Pitch: https://stza.co/+w0qu-31\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144520Z
LAST-MODIFIED:20180213T144520Z
TRANSP:OPAQUE
END:VEVENT
* Wood Ducks @ Red Sox
<2018-08-18 Sat>--<2018-08-17 Fri>
:PROPERTIES:
:ID:       IPgqpRHZItcE7rSXPzFXiY_J@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Wood Ducks @ Red Sox Wood Ducks @ Red Sox

Follow on MiLB First Pitch  https //stza.co/+w0qv-2v

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Wood Ducks @ Red Sox
END:VALARM
DTSTART;VALUE=DATE:20180818
DTEND;VALUE=DATE:20180818
UID:IPgqpRHZItcE7rSXPzFXiY_J@stanza.co
SUMMARY:Wood Ducks @ Red Sox
DESCRIPTION:Wood Ducks @ Red Sox\n\nFollow on MiLB First Pitch: https://stza.co/+w0qv-2v\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144520Z
LAST-MODIFIED:20180213T144520Z
TRANSP:OPAQUE
END:VEVENT
* Wood Ducks @ Red Sox
<2018-08-19 Sun>--<2018-08-18 Sat>
:PROPERTIES:
:ID:       ku6X7t9g-oexapp94G8jH7cY@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Wood Ducks @ Red Sox Wood Ducks @ Red Sox

Follow on MiLB First Pitch  https //stza.co/+w0qw-F

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Wood Ducks @ Red Sox
END:VALARM
DTSTART;VALUE=DATE:20180819
DTEND;VALUE=DATE:20180819
UID:ku6X7t9g-oexapp94G8jH7cY@stanza.co
SUMMARY:Wood Ducks @ Red Sox
DESCRIPTION:Wood Ducks @ Red Sox\n\nFollow on MiLB First Pitch: https://stza.co/+w0qw-F\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144520Z
LAST-MODIFIED:20180213T144520Z
TRANSP:OPAQUE
END:VEVENT
* Wood Ducks @ Blue Rocks
<2018-08-20 Mon 17:35-20:35>
:PROPERTIES:
:ID:       WbuTS54wSfv2R5_yN6nNhnqg@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Wood Ducks @ Blue Rocks Wood Ducks @ Blue Rocks

Follow on MiLB First Pitch  https //stza.co/+wX7K-2H

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Wood Ducks @ Blue Rocks
END:VALARM
DTSTART:20180820T223500Z
DTEND:20180821T013500Z
UID:WbuTS54wSfv2R5_yN6nNhnqg@stanza.co
SUMMARY:Wood Ducks @ Blue Rocks
DESCRIPTION:Wood Ducks @ Blue Rocks\n\nFollow on MiLB First Pitch: https://stza.co/+wX7K-2H\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144520Z
LAST-MODIFIED:20180213T144520Z
TRANSP:OPAQUE
END:VEVENT
* Wood Ducks @ Blue Rocks
<2018-08-21 Tue 17:35-20:35>
:PROPERTIES:
:ID:       bNxp4FZpsqQWT-mWXhDEI9NU@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Wood Ducks @ Blue Rocks Wood Ducks @ Blue Rocks

Follow on MiLB First Pitch  https //stza.co/+wX7L-3I

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Wood Ducks @ Blue Rocks
END:VALARM
DTSTART:20180821T223500Z
DTEND:20180822T013500Z
UID:bNxp4FZpsqQWT-mWXhDEI9NU@stanza.co
SUMMARY:Wood Ducks @ Blue Rocks
DESCRIPTION:Wood Ducks @ Blue Rocks\n\nFollow on MiLB First Pitch: https://stza.co/+wX7L-3I\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144520Z
LAST-MODIFIED:20180213T144520Z
TRANSP:OPAQUE
END:VEVENT
* Wood Ducks @ Blue Rocks
<2018-08-22 Wed 17:35-20:35>
:PROPERTIES:
:ID:       ZpiIpYUKP1NbNrdHHbhYVIqr@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Wood Ducks @ Blue Rocks Wood Ducks @ Blue Rocks

Follow on MiLB First Pitch  https //stza.co/+wX7M-y

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Wood Ducks @ Blue Rocks
END:VALARM
DTSTART:20180822T223500Z
DTEND:20180823T013500Z
UID:ZpiIpYUKP1NbNrdHHbhYVIqr@stanza.co
SUMMARY:Wood Ducks @ Blue Rocks
DESCRIPTION:Wood Ducks @ Blue Rocks\n\nFollow on MiLB First Pitch: https://stza.co/+wX7M-y\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144520Z
LAST-MODIFIED:20180213T144520Z
TRANSP:OPAQUE
END:VEVENT
* Wood Ducks vs. Pelicans
<2018-08-24 Fri 18:00-21:00>
:PROPERTIES:
:ID:       tt1Jj1WOmXDJ53_z3Drpu-mE@stanza.co
:LOCATION: Post Game Fireworks Show
:STATUS:   CONFIRMED
:END:

Wood Ducks vs. Pelicans 

$3 Mother Earth Drafts.$3 off a game ticket at the box office with beer can.

A fan favorite is returning for a second year. Fridays we will be having food trucks from all over  eastern north Carolina here at the ballpark so you can get a taste of something different.

Follow on MiLB First Pitch  https //stza.co/+w0pS-1h

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Wood Ducks vs. Pelicans
END:VALARM
DTSTART:20180824T230000Z
DTEND:20180825T020000Z
UID:tt1Jj1WOmXDJ53_z3Drpu-mE@stanza.co
SUMMARY:Wood Ducks vs. Pelicans
DESCRIPTION:\n\n$3 Mother Earth Drafts.$3 off a game ticket at the box office with beer can.\n\nA fan favorite is returning for a second year. Fridays we will be having food trucks from all over  eastern north Carolina here at the ballpark so you can get a taste of something different.\n\nFollow on MiLB First Pitch: https://stza.co/+w0pS-1h\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Post Game Fireworks Show
STATUS:CONFIRMED
CREATED:20180213T144520Z
LAST-MODIFIED:20180213T144520Z
TRANSP:OPAQUE
END:VEVENT
* Wood Ducks vs. Pelicans
<2018-08-25 Sat 17:00-20:00>
:PROPERTIES:
:ID:       iTa_vnOjOClTjjK9FE8qdV2g@stanza.co
:LOCATION: Commemorative Pennant Giveaway
:STATUS:   CONFIRMED
:END:

Wood Ducks vs. Pelicans Be one of the first 1,000 fans and receive a commemorative 70th anniversary of Grainger Stadium pennant.  

Bring an empty Pepsi can and receive $3 off a game ticket. This offer is only available at the box office on the day of the game.Premium Giveaways on every Saturday game this year. Get here early in order to be the first to receive the giveaway.

Follow on MiLB First Pitch  https //stza.co/+w0pU-2R

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Wood Ducks vs. Pelicans
END:VALARM
DTSTART:20180825T220000Z
DTEND:20180826T010000Z
UID:iTa_vnOjOClTjjK9FE8qdV2g@stanza.co
SUMMARY:Wood Ducks vs. Pelicans
DESCRIPTION:Be one of the first 1,000 fans and receive a commemorative 70th anniversary of Grainger Stadium pennant.  \n\nBring an empty Pepsi can and receive $3 off a game ticket. This offer is only available at the box office on the day of the game.Premium Giveaways on every Saturday game this year. Get here early in order to be the first to receive the giveaway.\n\nFollow on MiLB First Pitch: https://stza.co/+w0pU-2R\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Commemorative Pennant Giveaway
STATUS:CONFIRMED
CREATED:20180213T144520Z
LAST-MODIFIED:20180213T144520Z
TRANSP:OPAQUE
END:VEVENT
* Wood Ducks vs. Pelicans
<2018-08-26 Sun 13:00-16:00>
:PROPERTIES:
:ID:       uIeWKBqE9mKUjOfXpDTh-pUV@stanza.co
:LOCATION: Sunday Funday
:STATUS:   CONFIRMED
:END:

Wood Ducks vs. Pelicans Pre game Autograph signing from Wood Ducks players and post game run the bases presented by Cricket Wireless of Kinston. All Lil DEWD club members get in for free.

Follow on MiLB First Pitch  https //stza.co/+w0pV-3l

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Wood Ducks vs. Pelicans
END:VALARM
DTSTART:20180826T180000Z
DTEND:20180826T210000Z
UID:uIeWKBqE9mKUjOfXpDTh-pUV@stanza.co
SUMMARY:Wood Ducks vs. Pelicans
DESCRIPTION:Pre game Autograph signing from Wood Ducks players and post game run the bases presented by Cricket Wireless of Kinston. All Lil DEWD club members get in for free.\n\nFollow on MiLB First Pitch: https://stza.co/+w0pV-3l\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Sunday Funday
STATUS:CONFIRMED
CREATED:20180213T144520Z
LAST-MODIFIED:20180213T144520Z
TRANSP:OPAQUE
END:VEVENT
* Wood Ducks @ Mudcats
<2018-08-27 Mon 18:00-21:00>
:PROPERTIES:
:ID:       QyAOAwPXCnigyyemz5L7Y_AR@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Wood Ducks @ Mudcats Wood Ducks @ Mudcats

Buy tickets here  https //stza.co/~w0nP

Follow on MiLB First Pitch  https //stza.co/+w0nP-S

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Wood Ducks @ Mudcats
END:VALARM
DTSTART:20180827T230000Z
DTEND:20180828T020000Z
UID:QyAOAwPXCnigyyemz5L7Y_AR@stanza.co
SUMMARY:Wood Ducks @ Mudcats
DESCRIPTION:Wood Ducks @ Mudcats\n\nBuy tickets here: https://stza.co/~w0nP\n\nFollow on MiLB First Pitch: https://stza.co/+w0nP-S\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144520Z
LAST-MODIFIED:20180213T144520Z
TRANSP:OPAQUE
END:VEVENT
* Wood Ducks @ Mudcats
<2018-08-28 Tue 18:00-21:00>
:PROPERTIES:
:ID:       bYXwNtTg5a_IaVRNdY6yPWAv@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Wood Ducks @ Mudcats Wood Ducks @ Mudcats

Buy tickets here  https //stza.co/~w0nQ

Follow on MiLB First Pitch  https //stza.co/+w0nQ-3e

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Wood Ducks @ Mudcats
END:VALARM
DTSTART:20180828T230000Z
DTEND:20180829T020000Z
UID:bYXwNtTg5a_IaVRNdY6yPWAv@stanza.co
SUMMARY:Wood Ducks @ Mudcats
DESCRIPTION:Wood Ducks @ Mudcats\n\nBuy tickets here: https://stza.co/~w0nQ\n\nFollow on MiLB First Pitch: https://stza.co/+w0nQ-3e\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144520Z
LAST-MODIFIED:20180213T144520Z
TRANSP:OPAQUE
END:VEVENT
* Wood Ducks @ Mudcats
<2018-08-29 Wed 18:00-21:00>
:PROPERTIES:
:ID:       G-aehhuWCgiZ7rdUC0HZ2Td5@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Wood Ducks @ Mudcats Wood Ducks @ Mudcats

Buy tickets here  https //stza.co/~w0nR

Follow on MiLB First Pitch  https //stza.co/+w0nR-19

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Wood Ducks @ Mudcats
END:VALARM
DTSTART:20180829T230000Z
DTEND:20180830T020000Z
UID:G-aehhuWCgiZ7rdUC0HZ2Td5@stanza.co
SUMMARY:Wood Ducks @ Mudcats
DESCRIPTION:Wood Ducks @ Mudcats\n\nBuy tickets here: https://stza.co/~w0nR\n\nFollow on MiLB First Pitch: https://stza.co/+w0nR-19\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144520Z
LAST-MODIFIED:20180213T144520Z
TRANSP:OPAQUE
END:VEVENT
* Wood Ducks @ Mudcats
<2018-08-30 Thu 18:00-21:00>
:PROPERTIES:
:ID:       20njyX2ZiiqFkXi9FYPNO0Y3@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Wood Ducks @ Mudcats Wood Ducks @ Mudcats

Buy tickets here  https //stza.co/~w0nS

Follow on MiLB First Pitch  https //stza.co/+w0nS-j

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Wood Ducks @ Mudcats
END:VALARM
DTSTART:20180830T230000Z
DTEND:20180831T020000Z
UID:20njyX2ZiiqFkXi9FYPNO0Y3@stanza.co
SUMMARY:Wood Ducks @ Mudcats
DESCRIPTION:Wood Ducks @ Mudcats\n\nBuy tickets here: https://stza.co/~w0nS\n\nFollow on MiLB First Pitch: https://stza.co/+w0nS-j\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144520Z
LAST-MODIFIED:20180213T144520Z
TRANSP:OPAQUE
END:VEVENT
* Wood Ducks vs. Dash
<2018-08-31 Fri 18:00-21:00>
:PROPERTIES:
:ID:       kba188oHV1QKmRdtqguCP65b@stanza.co
:LOCATION: Post Game Fireworks Show
:STATUS:   CONFIRMED
:END:

Wood Ducks vs. Dash 

$3 Mother Earth Drafts.$3 off a game ticket at the box office with beer can.

A fan favorite is returning for a second year. Fridays we will be having food trucks from all over  eastern north Carolina here at the ballpark so you can get a taste of something different.

Follow on MiLB First Pitch  https //stza.co/+w0pY-1p

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Wood Ducks vs. Dash
END:VALARM
DTSTART:20180831T230000Z
DTEND:20180901T020000Z
UID:kba188oHV1QKmRdtqguCP65b@stanza.co
SUMMARY:Wood Ducks vs. Dash
DESCRIPTION:\n\n$3 Mother Earth Drafts.$3 off a game ticket at the box office with beer can.\n\nA fan favorite is returning for a second year. Fridays we will be having food trucks from all over  eastern north Carolina here at the ballpark so you can get a taste of something different.\n\nFollow on MiLB First Pitch: https://stza.co/+w0pY-1p\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Post Game Fireworks Show
STATUS:CONFIRMED
CREATED:20180213T144520Z
LAST-MODIFIED:20180213T144520Z
TRANSP:OPAQUE
END:VEVENT
* Wood Ducks vs. Dash
<2018-09-01 Sat 18:00-21:00>
:PROPERTIES:
:ID:       YFHAKTSSc9ZqYsIEOjUxETi-@stanza.co
:LOCATION: Team Photo
:STATUS:   CONFIRMED
:END:

Wood Ducks vs. Dash The first 2,500 will receive a complimentary Wood Ducks Team Photo. 

Bring an empty Pepsi can and receive $3 off a game ticket. This offer is only available at the box office on the day of the game.Premium Giveaways on every Saturday game this year. Get here early in order to be the first to receive the giveaway.

Follow on MiLB First Pitch  https //stza.co/+w0p_-2Q

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Wood Ducks vs. Dash
END:VALARM
DTSTART:20180901T230000Z
DTEND:20180902T020000Z
UID:YFHAKTSSc9ZqYsIEOjUxETi-@stanza.co
SUMMARY:Wood Ducks vs. Dash
DESCRIPTION:The first 2,500 will receive a complimentary Wood Ducks Team Photo. \n\nBring an empty Pepsi can and receive $3 off a game ticket. This offer is only available at the box office on the day of the game.Premium Giveaways on every Saturday game this year. Get here early in order to be the first to receive the giveaway.\n\nFollow on MiLB First Pitch: https://stza.co/+w0p_-2Q\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Team Photo
STATUS:CONFIRMED
CREATED:20180213T144520Z
LAST-MODIFIED:20180213T144520Z
TRANSP:OPAQUE
END:VEVENT
* Wood Ducks vs. Dash
<2018-09-02 Sun 13:00-16:00>
:PROPERTIES:
:ID:       AVYNS937hFDuV9BI0ycwTiVM@stanza.co
:LOCATION: Sunday Funday
:STATUS:   CONFIRMED
:END:

Wood Ducks vs. Dash Pre game Autograph signing from Wood Ducks players and post game run the bases presented by Cricket Wireless of Kinston. All Lil DEWD club members get in for free.

Follow on MiLB First Pitch  https //stza.co/+w0p$-3c

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Wood Ducks vs. Dash
END:VALARM
DTSTART:20180902T180000Z
DTEND:20180902T210000Z
UID:AVYNS937hFDuV9BI0ycwTiVM@stanza.co
SUMMARY:Wood Ducks vs. Dash
DESCRIPTION:Pre game Autograph signing from Wood Ducks players and post game run the bases presented by Cricket Wireless of Kinston. All Lil DEWD club members get in for free.\n\nFollow on MiLB First Pitch: https://stza.co/+w0p$-3c\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Sunday Funday
STATUS:CONFIRMED
CREATED:20180213T144520Z
LAST-MODIFIED:20180213T144520Z
TRANSP:OPAQUE
END:VEVENT
* Wood Ducks vs. Dash
<2018-09-03 Mon 11:05-14:05>
:PROPERTIES:
:ID:       MfXkYjyE9nMfE3fq6FhHBHQw@stanza.co
:LOCATION: Dollar Hot Dog Night
:STATUS:   CONFIRMED
:END:

Wood Ducks vs. Dash Hot dogs all night long will be one dollar.

Kids under 12 receive free admission with a paying adult. One child per paying adult.

Follow on MiLB First Pitch  https //stza.co/+w0q1-3z

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Wood Ducks vs. Dash
END:VALARM
DTSTART:20180903T160500Z
DTEND:20180903T190500Z
UID:MfXkYjyE9nMfE3fq6FhHBHQw@stanza.co
SUMMARY:Wood Ducks vs. Dash
DESCRIPTION:Hot dogs all night long will be one dollar.\n\nKids under 12 receive free admission with a paying adult. One child per paying adult.\n\nFollow on MiLB First Pitch: https://stza.co/+w0q1-3z\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Dollar Hot Dog Night
STATUS:CONFIRMED
CREATED:20180213T144520Z
LAST-MODIFIED:20180213T144520Z
TRANSP:OPAQUE
END:VEVENT
