#+TITLE:       Main Google calendar entries
#+AUTHOR:      Eric S Fraga
#+EMAIL:       e.fraga@ucl.ac.uk
#+DESCRIPTION: converted using the ical2org awk script
#+CATEGORY:    google
#+STARTUP:     hidestars
#+STARTUP:     overview

* COMMENT original iCal preamble

* Tortugas vs. Fire Frogs
<2018-04-05 Thu 18:05-21:05>
:PROPERTIES:
:ID:       faFbj5FMBqXRSUH0jgGPWVhM@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Tortugas vs. Fire Frogs Tortugas vs. Fire Frogs

Follow on MiLB First Pitch  https //stza.co/+vMhF-2Y

Shop  https //stza.co/+vMhF-1e

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Tortugas vs. Fire Frogs
END:VALARM
DTSTART:20180405T230500Z
DTEND:20180406T020500Z
UID:faFbj5FMBqXRSUH0jgGPWVhM@stanza.co
SUMMARY:Tortugas vs. Fire Frogs
DESCRIPTION:Tortugas vs. Fire Frogs\n\nFollow on MiLB First Pitch: https://stza.co/+vMhF-2Y\n\nShop: https://stza.co/+vMhF-1e\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144518Z
LAST-MODIFIED:20180213T144518Z
TRANSP:OPAQUE
END:VEVENT
* Tortugas vs. Fire Frogs
<2018-04-06 Fri 18:05-21:05>
:PROPERTIES:
:ID:       o6I7QZqzpHAr96O3oHwAO2fp@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Tortugas vs. Fire Frogs Tortugas vs. Fire Frogs

Follow on MiLB First Pitch  https //stza.co/+vMhG-1I

Shop  https //stza.co/+vMhG-1g

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Tortugas vs. Fire Frogs
END:VALARM
DTSTART:20180406T230500Z
DTEND:20180407T020500Z
UID:o6I7QZqzpHAr96O3oHwAO2fp@stanza.co
SUMMARY:Tortugas vs. Fire Frogs
DESCRIPTION:Tortugas vs. Fire Frogs\n\nFollow on MiLB First Pitch: https://stza.co/+vMhG-1I\n\nShop: https://stza.co/+vMhG-1g\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144518Z
LAST-MODIFIED:20180213T144518Z
TRANSP:OPAQUE
END:VEVENT
* Tortugas @ Fire Frogs
<2018-04-07 Sat 15:00-18:00>
:PROPERTIES:
:ID:       irTGSOV_nb2hTDdKwqvbRljd@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Tortugas @ Fire Frogs Tortugas @ Fire Frogs

Buy tickets here  https //stza.co/~xWKD

Follow on MiLB First Pitch  https //stza.co/+xWKD-l

Shop  https //stza.co/+xWKD-3N

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Tortugas @ Fire Frogs
END:VALARM
DTSTART:20180407T200000Z
DTEND:20180407T230000Z
UID:irTGSOV_nb2hTDdKwqvbRljd@stanza.co
SUMMARY:Tortugas @ Fire Frogs
DESCRIPTION:Tortugas @ Fire Frogs\n\nBuy tickets here: https://stza.co/~xWKD\n\nFollow on MiLB First Pitch: https://stza.co/+xWKD-l\n\nShop: https://stza.co/+xWKD-3N\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144518Z
LAST-MODIFIED:20180213T144518Z
TRANSP:OPAQUE
END:VEVENT
* Tortugas @ Fire Frogs
<2018-04-08 Sun 10:00-13:00>
:PROPERTIES:
:ID:       ZruMhJvTgGg_ZkIuTofqtqVF@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Tortugas @ Fire Frogs Tortugas @ Fire Frogs

Buy tickets here  https //stza.co/~xWKE

Follow on MiLB First Pitch  https //stza.co/+xWKE-2N

Shop  https //stza.co/+xWKE-3U

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Tortugas @ Fire Frogs
END:VALARM
DTSTART:20180408T150000Z
DTEND:20180408T180000Z
UID:ZruMhJvTgGg_ZkIuTofqtqVF@stanza.co
SUMMARY:Tortugas @ Fire Frogs
DESCRIPTION:Tortugas @ Fire Frogs\n\nBuy tickets here: https://stza.co/~xWKE\n\nFollow on MiLB First Pitch: https://stza.co/+xWKE-2N\n\nShop: https://stza.co/+xWKE-3U\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144518Z
LAST-MODIFIED:20180213T144518Z
TRANSP:OPAQUE
END:VEVENT
* Tortugas vs. Stone Crabs
<2018-04-09 Mon 18:05-21:05>
:PROPERTIES:
:ID:       MbgNPxABMv6USK_WTe44xd53@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Tortugas vs. Stone Crabs Tortugas vs. Stone Crabs

Follow on MiLB First Pitch  https //stza.co/+vMhJ-3u

Shop  https //stza.co/+vMhJ-1B

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Tortugas vs. Stone Crabs
END:VALARM
DTSTART:20180409T230500Z
DTEND:20180410T020500Z
UID:MbgNPxABMv6USK_WTe44xd53@stanza.co
SUMMARY:Tortugas vs. Stone Crabs
DESCRIPTION:Tortugas vs. Stone Crabs\n\nFollow on MiLB First Pitch: https://stza.co/+vMhJ-3u\n\nShop: https://stza.co/+vMhJ-1B\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144518Z
LAST-MODIFIED:20180213T144518Z
TRANSP:OPAQUE
END:VEVENT
* Tortugas vs. Stone Crabs
<2018-04-10 Tue 18:05-21:05>
:PROPERTIES:
:ID:       07oAGDRfL4vRkx51Dv7oLFwJ@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Tortugas vs. Stone Crabs Tortugas vs. Stone Crabs

Follow on MiLB First Pitch  https //stza.co/+vMhL-2O

Shop  https //stza.co/+vMhL-1M

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Tortugas vs. Stone Crabs
END:VALARM
DTSTART:20180410T230500Z
DTEND:20180411T020500Z
UID:07oAGDRfL4vRkx51Dv7oLFwJ@stanza.co
SUMMARY:Tortugas vs. Stone Crabs
DESCRIPTION:Tortugas vs. Stone Crabs\n\nFollow on MiLB First Pitch: https://stza.co/+vMhL-2O\n\nShop: https://stza.co/+vMhL-1M\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144518Z
LAST-MODIFIED:20180213T144518Z
TRANSP:OPAQUE
END:VEVENT
* Tortugas vs. Stone Crabs
<2018-04-11 Wed 18:05-21:05>
:PROPERTIES:
:ID:       3A_FwOqIyscRp9Z_q5VjWuev@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Tortugas vs. Stone Crabs Tortugas vs. Stone Crabs

Follow on MiLB First Pitch  https //stza.co/+vMhN-2r

Shop  https //stza.co/+vMhN-1s

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Tortugas vs. Stone Crabs
END:VALARM
DTSTART:20180411T230500Z
DTEND:20180412T020500Z
UID:3A_FwOqIyscRp9Z_q5VjWuev@stanza.co
SUMMARY:Tortugas vs. Stone Crabs
DESCRIPTION:Tortugas vs. Stone Crabs\n\nFollow on MiLB First Pitch: https://stza.co/+vMhN-2r\n\nShop: https://stza.co/+vMhN-1s\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144518Z
LAST-MODIFIED:20180213T144518Z
TRANSP:OPAQUE
END:VEVENT
* Tortugas vs. Stone Crabs
<2018-04-12 Thu 18:05-21:05>
:PROPERTIES:
:ID:       fYE3lcukJwF3HLCkUwThVIn6@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Tortugas vs. Stone Crabs Tortugas vs. Stone Crabs

Follow on MiLB First Pitch  https //stza.co/+vMhO-W

Shop  https //stza.co/+vMhO-3e

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Tortugas vs. Stone Crabs
END:VALARM
DTSTART:20180412T230500Z
DTEND:20180413T020500Z
UID:fYE3lcukJwF3HLCkUwThVIn6@stanza.co
SUMMARY:Tortugas vs. Stone Crabs
DESCRIPTION:Tortugas vs. Stone Crabs\n\nFollow on MiLB First Pitch: https://stza.co/+vMhO-W\n\nShop: https://stza.co/+vMhO-3e\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144518Z
LAST-MODIFIED:20180213T144518Z
TRANSP:OPAQUE
END:VEVENT
* Tortugas vs. Hammerheads
<2018-04-13 Fri 18:05-21:05>
:PROPERTIES:
:ID:       0GG8IrHbhWuVIAWkjs098wDP@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Tortugas vs. Hammerheads Tortugas vs. Hammerheads

Follow on MiLB First Pitch  https //stza.co/+vMhR-1i

Shop  https //stza.co/+vMhR-3E

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Tortugas vs. Hammerheads
END:VALARM
DTSTART:20180413T230500Z
DTEND:20180414T020500Z
UID:0GG8IrHbhWuVIAWkjs098wDP@stanza.co
SUMMARY:Tortugas vs. Hammerheads
DESCRIPTION:Tortugas vs. Hammerheads\n\nFollow on MiLB First Pitch: https://stza.co/+vMhR-1i\n\nShop: https://stza.co/+vMhR-3E\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144518Z
LAST-MODIFIED:20180213T144518Z
TRANSP:OPAQUE
END:VEVENT
* Tortugas vs. Hammerheads
<2018-04-14 Sat 18:05-21:05>
:PROPERTIES:
:ID:       V51o8ub7AGIT4b4_3pKumJJm@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Tortugas vs. Hammerheads Tortugas vs. Hammerheads

Follow on MiLB First Pitch  https //stza.co/+vMhT-2l

Shop  https //stza.co/+vMhT-2_

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Tortugas vs. Hammerheads
END:VALARM
DTSTART:20180414T230500Z
DTEND:20180415T020500Z
UID:V51o8ub7AGIT4b4_3pKumJJm@stanza.co
SUMMARY:Tortugas vs. Hammerheads
DESCRIPTION:Tortugas vs. Hammerheads\n\nFollow on MiLB First Pitch: https://stza.co/+vMhT-2l\n\nShop: https://stza.co/+vMhT-2_\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144518Z
LAST-MODIFIED:20180213T144518Z
TRANSP:OPAQUE
END:VEVENT
* Tortugas vs. Hammerheads
<2018-04-15 Sun 16:35-19:35>
:PROPERTIES:
:ID:       bwglJRxSY0p3h3vW6icLUzHP@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Tortugas vs. Hammerheads Tortugas vs. Hammerheads

Follow on MiLB First Pitch  https //stza.co/+vMhV-3O

Shop  https //stza.co/+vMhV-17

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Tortugas vs. Hammerheads
END:VALARM
DTSTART:20180415T213500Z
DTEND:20180416T003500Z
UID:bwglJRxSY0p3h3vW6icLUzHP@stanza.co
SUMMARY:Tortugas vs. Hammerheads
DESCRIPTION:Tortugas vs. Hammerheads\n\nFollow on MiLB First Pitch: https://stza.co/+vMhV-3O\n\nShop: https://stza.co/+vMhV-17\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144518Z
LAST-MODIFIED:20180213T144518Z
TRANSP:OPAQUE
END:VEVENT
* Tortugas @ Tarpons
<2018-04-17 Tue>--<2018-04-16 Mon>
:PROPERTIES:
:ID:       F1quJq3CMUjNXjExWv4JxepV@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Tortugas @ Tarpons Tortugas @ Tarpons

Follow on MiLB First Pitch  https //stza.co/+vMkz-B

Shop  https //stza.co/+vMkz-1F

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Tortugas @ Tarpons
END:VALARM
DTSTART;VALUE=DATE:20180417
DTEND;VALUE=DATE:20180417
UID:F1quJq3CMUjNXjExWv4JxepV@stanza.co
SUMMARY:Tortugas @ Tarpons
DESCRIPTION:Tortugas @ Tarpons\n\nFollow on MiLB First Pitch: https://stza.co/+vMkz-B\n\nShop: https://stza.co/+vMkz-1F\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144518Z
LAST-MODIFIED:20180213T144518Z
TRANSP:OPAQUE
END:VEVENT
* Tortugas @ Tarpons
<2018-04-18 Wed>--<2018-04-17 Tue>
:PROPERTIES:
:ID:       5IP5S9Ybg16xO0kzo1jbjBQX@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Tortugas @ Tarpons Tortugas @ Tarpons

Follow on MiLB First Pitch  https //stza.co/+vMkA-1w

Shop  https //stza.co/+vMkA-s

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Tortugas @ Tarpons
END:VALARM
DTSTART;VALUE=DATE:20180418
DTEND;VALUE=DATE:20180418
UID:5IP5S9Ybg16xO0kzo1jbjBQX@stanza.co
SUMMARY:Tortugas @ Tarpons
DESCRIPTION:Tortugas @ Tarpons\n\nFollow on MiLB First Pitch: https://stza.co/+vMkA-1w\n\nShop: https://stza.co/+vMkA-s\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144518Z
LAST-MODIFIED:20180213T144518Z
TRANSP:OPAQUE
END:VEVENT
* Tortugas @ Tarpons
<2018-04-19 Thu>--<2018-04-18 Wed>
:PROPERTIES:
:ID:       6q-jQf-iQh5T5RP2gmFwzo1l@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Tortugas @ Tarpons Tortugas @ Tarpons

Follow on MiLB First Pitch  https //stza.co/+vMkB-3j

Shop  https //stza.co/+vMkB-B

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Tortugas @ Tarpons
END:VALARM
DTSTART;VALUE=DATE:20180419
DTEND;VALUE=DATE:20180419
UID:6q-jQf-iQh5T5RP2gmFwzo1l@stanza.co
SUMMARY:Tortugas @ Tarpons
DESCRIPTION:Tortugas @ Tarpons\n\nFollow on MiLB First Pitch: https://stza.co/+vMkB-3j\n\nShop: https://stza.co/+vMkB-B\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144518Z
LAST-MODIFIED:20180213T144518Z
TRANSP:OPAQUE
END:VEVENT
* Tortugas @ Blue Jays
<2018-04-20 Fri 17:30-20:30>
:PROPERTIES:
:ID:       VNwHP-T-dolgfqdmHj1QjB40@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Tortugas @ Blue Jays Tortugas @ Blue Jays

Follow on MiLB First Pitch  https //stza.co/+y0GE-1A

Shop  https //stza.co/+y0GE-1a

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Tortugas @ Blue Jays
END:VALARM
DTSTART:20180420T223000Z
DTEND:20180421T013000Z
UID:VNwHP-T-dolgfqdmHj1QjB40@stanza.co
SUMMARY:Tortugas @ Blue Jays
DESCRIPTION:Tortugas @ Blue Jays\n\nFollow on MiLB First Pitch: https://stza.co/+y0GE-1A\n\nShop: https://stza.co/+y0GE-1a\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144518Z
LAST-MODIFIED:20180213T144518Z
TRANSP:OPAQUE
END:VEVENT
* Tortugas @ Blue Jays
<2018-04-21 Sat 17:30-20:30>
:PROPERTIES:
:ID:       RmynK3XmxqKatN42iPARVn5C@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Tortugas @ Blue Jays Tortugas @ Blue Jays

Follow on MiLB First Pitch  https //stza.co/+y0GF-1U

Shop  https //stza.co/+y0GF-1P

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Tortugas @ Blue Jays
END:VALARM
DTSTART:20180421T223000Z
DTEND:20180422T013000Z
UID:RmynK3XmxqKatN42iPARVn5C@stanza.co
SUMMARY:Tortugas @ Blue Jays
DESCRIPTION:Tortugas @ Blue Jays\n\nFollow on MiLB First Pitch: https://stza.co/+y0GF-1U\n\nShop: https://stza.co/+y0GF-1P\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144518Z
LAST-MODIFIED:20180213T144518Z
TRANSP:OPAQUE
END:VEVENT
* Tortugas @ Blue Jays
<2018-04-22 Sun 12:00-15:00>
:PROPERTIES:
:ID:       Ix-oqwSW5oo09twKJ12ZBH8H@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Tortugas @ Blue Jays Tortugas @ Blue Jays

Follow on MiLB First Pitch  https //stza.co/+y0GG-14

Shop  https //stza.co/+y0GG-A

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Tortugas @ Blue Jays
END:VALARM
DTSTART:20180422T170000Z
DTEND:20180422T200000Z
UID:Ix-oqwSW5oo09twKJ12ZBH8H@stanza.co
SUMMARY:Tortugas @ Blue Jays
DESCRIPTION:Tortugas @ Blue Jays\n\nFollow on MiLB First Pitch: https://stza.co/+y0GG-14\n\nShop: https://stza.co/+y0GG-A\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144518Z
LAST-MODIFIED:20180213T144518Z
TRANSP:OPAQUE
END:VEVENT
* Tortugas vs. Fire Frogs
<2018-04-23 Mon 18:05-21:05>
:PROPERTIES:
:ID:       _EMBljQ0tWaqqwvitXfBD7KJ@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Tortugas vs. Fire Frogs Tortugas vs. Fire Frogs

Follow on MiLB First Pitch  https //stza.co/+vMhW-1n

Shop  https //stza.co/+vMhW-5

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Tortugas vs. Fire Frogs
END:VALARM
DTSTART:20180423T230500Z
DTEND:20180424T020500Z
UID:_EMBljQ0tWaqqwvitXfBD7KJ@stanza.co
SUMMARY:Tortugas vs. Fire Frogs
DESCRIPTION:Tortugas vs. Fire Frogs\n\nFollow on MiLB First Pitch: https://stza.co/+vMhW-1n\n\nShop: https://stza.co/+vMhW-5\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144518Z
LAST-MODIFIED:20180213T144518Z
TRANSP:OPAQUE
END:VEVENT
* Tortugas vs. Fire Frogs
<2018-04-24 Tue 18:05-21:05>
:PROPERTIES:
:ID:       K02eUhyOChyBBq_faHvuWcpO@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Tortugas vs. Fire Frogs Tortugas vs. Fire Frogs

Follow on MiLB First Pitch  https //stza.co/+vMhY-3A

Shop  https //stza.co/+vMhY-8

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Tortugas vs. Fire Frogs
END:VALARM
DTSTART:20180424T230500Z
DTEND:20180425T020500Z
UID:K02eUhyOChyBBq_faHvuWcpO@stanza.co
SUMMARY:Tortugas vs. Fire Frogs
DESCRIPTION:Tortugas vs. Fire Frogs\n\nFollow on MiLB First Pitch: https://stza.co/+vMhY-3A\n\nShop: https://stza.co/+vMhY-8\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144518Z
LAST-MODIFIED:20180213T144518Z
TRANSP:OPAQUE
END:VEVENT
* Tortugas vs. Fire Frogs
<2018-04-25 Wed 18:05-21:05>
:PROPERTIES:
:ID:       xIjYwA_PZ-OmAtrdBz9yFp6_@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Tortugas vs. Fire Frogs Tortugas vs. Fire Frogs

Follow on MiLB First Pitch  https //stza.co/+vMh$-14

Shop  https //stza.co/+vMh$-3y

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Tortugas vs. Fire Frogs
END:VALARM
DTSTART:20180425T230500Z
DTEND:20180426T020500Z
UID:xIjYwA_PZ-OmAtrdBz9yFp6_@stanza.co
SUMMARY:Tortugas vs. Fire Frogs
DESCRIPTION:Tortugas vs. Fire Frogs\n\nFollow on MiLB First Pitch: https://stza.co/+vMh$-14\n\nShop: https://stza.co/+vMh$-3y\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144518Z
LAST-MODIFIED:20180213T144518Z
TRANSP:OPAQUE
END:VEVENT
* Tortugas @ Miracle
<2018-04-26 Thu 18:00-21:00>
:PROPERTIES:
:ID:       97N3MH95dLP8k4XAIMe8FVtS@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Tortugas @ Miracle Tortugas @ Miracle

Follow on MiLB First Pitch  https //stza.co/+xMau-1p

Shop  https //stza.co/+xMau-3d

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Tortugas @ Miracle
END:VALARM
DTSTART:20180426T230000Z
DTEND:20180427T020000Z
UID:97N3MH95dLP8k4XAIMe8FVtS@stanza.co
SUMMARY:Tortugas @ Miracle
DESCRIPTION:Tortugas @ Miracle\n\nFollow on MiLB First Pitch: https://stza.co/+xMau-1p\n\nShop: https://stza.co/+xMau-3d\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144518Z
LAST-MODIFIED:20180213T144518Z
TRANSP:OPAQUE
END:VEVENT
* Tortugas @ Miracle
<2018-04-27 Fri 18:00-21:00>
:PROPERTIES:
:ID:       ifZefqFpk-Rz8oxCfKq6hjqY@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Tortugas @ Miracle Tortugas @ Miracle

Follow on MiLB First Pitch  https //stza.co/+xMav-P

Shop  https //stza.co/+xMav-2H

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Tortugas @ Miracle
END:VALARM
DTSTART:20180427T230000Z
DTEND:20180428T020000Z
UID:ifZefqFpk-Rz8oxCfKq6hjqY@stanza.co
SUMMARY:Tortugas @ Miracle
DESCRIPTION:Tortugas @ Miracle\n\nFollow on MiLB First Pitch: https://stza.co/+xMav-P\n\nShop: https://stza.co/+xMav-2H\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144518Z
LAST-MODIFIED:20180213T144518Z
TRANSP:OPAQUE
END:VEVENT
* Tortugas @ Miracle
<2018-04-28 Sat 17:00-20:00>
:PROPERTIES:
:ID:       nzRhJDAu0vRT4ijpMZm_D_dW@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Tortugas @ Miracle Tortugas @ Miracle

Follow on MiLB First Pitch  https //stza.co/+xMaw-h

Shop  https //stza.co/+xMaw-2K

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Tortugas @ Miracle
END:VALARM
DTSTART:20180428T220000Z
DTEND:20180429T010000Z
UID:nzRhJDAu0vRT4ijpMZm_D_dW@stanza.co
SUMMARY:Tortugas @ Miracle
DESCRIPTION:Tortugas @ Miracle\n\nFollow on MiLB First Pitch: https://stza.co/+xMaw-h\n\nShop: https://stza.co/+xMaw-2K\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144518Z
LAST-MODIFIED:20180213T144518Z
TRANSP:OPAQUE
END:VEVENT
* Tortugas @ Miracle
<2018-04-29 Sun 15:00-18:00>
:PROPERTIES:
:ID:       yOQVrm1eDRfqmEPmoe4DJRlH@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Tortugas @ Miracle Tortugas @ Miracle

Follow on MiLB First Pitch  https //stza.co/+xMax-3F

Shop  https //stza.co/+xMax-1I

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Tortugas @ Miracle
END:VALARM
DTSTART:20180429T200000Z
DTEND:20180429T230000Z
UID:yOQVrm1eDRfqmEPmoe4DJRlH@stanza.co
SUMMARY:Tortugas @ Miracle
DESCRIPTION:Tortugas @ Miracle\n\nFollow on MiLB First Pitch: https://stza.co/+xMax-3F\n\nShop: https://stza.co/+xMax-1I\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144518Z
LAST-MODIFIED:20180213T144518Z
TRANSP:OPAQUE
END:VEVENT
* Tortugas @ Hammerheads
<2018-05-01 Tue>--<2018-04-30 Mon>
:PROPERTIES:
:ID:       ZEbZcxJSuUnuJIzcXSytkP4I@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Tortugas @ Hammerheads Tortugas @ Hammerheads

Buy tickets here  https //stza.co/~vMk7

Follow on MiLB First Pitch  https //stza.co/+vMk7-2h

Shop  https //stza.co/+vMk7-5

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Tortugas @ Hammerheads
END:VALARM
DTSTART;VALUE=DATE:20180501
DTEND;VALUE=DATE:20180501
UID:ZEbZcxJSuUnuJIzcXSytkP4I@stanza.co
SUMMARY:Tortugas @ Hammerheads
DESCRIPTION:Tortugas @ Hammerheads\n\nBuy tickets here: https://stza.co/~vMk7\n\nFollow on MiLB First Pitch: https://stza.co/+vMk7-2h\n\nShop: https://stza.co/+vMk7-5\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144518Z
LAST-MODIFIED:20180213T144518Z
TRANSP:OPAQUE
END:VEVENT
* Tortugas @ Hammerheads
<2018-05-02 Wed>--<2018-05-01 Tue>
:PROPERTIES:
:ID:       RpG2q90bK13t2uP3m8gVmZ0x@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Tortugas @ Hammerheads Tortugas @ Hammerheads

Buy tickets here  https //stza.co/~vMk8

Follow on MiLB First Pitch  https //stza.co/+vMk8-s

Shop  https //stza.co/+vMk8-32

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Tortugas @ Hammerheads
END:VALARM
DTSTART;VALUE=DATE:20180502
DTEND;VALUE=DATE:20180502
UID:RpG2q90bK13t2uP3m8gVmZ0x@stanza.co
SUMMARY:Tortugas @ Hammerheads
DESCRIPTION:Tortugas @ Hammerheads\n\nBuy tickets here: https://stza.co/~vMk8\n\nFollow on MiLB First Pitch: https://stza.co/+vMk8-s\n\nShop: https://stza.co/+vMk8-32\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144518Z
LAST-MODIFIED:20180213T144518Z
TRANSP:OPAQUE
END:VEVENT
* Tortugas @ Hammerheads
<2018-05-03 Thu>--<2018-05-02 Wed>
:PROPERTIES:
:ID:       dstNQFwLx8S4Ar-CHVwVIFNl@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Tortugas @ Hammerheads Tortugas @ Hammerheads

Buy tickets here  https //stza.co/~vMk9

Follow on MiLB First Pitch  https //stza.co/+vMk9-2V

Shop  https //stza.co/+vMk9-2_

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Tortugas @ Hammerheads
END:VALARM
DTSTART;VALUE=DATE:20180503
DTEND;VALUE=DATE:20180503
UID:dstNQFwLx8S4Ar-CHVwVIFNl@stanza.co
SUMMARY:Tortugas @ Hammerheads
DESCRIPTION:Tortugas @ Hammerheads\n\nBuy tickets here: https://stza.co/~vMk9\n\nFollow on MiLB First Pitch: https://stza.co/+vMk9-2V\n\nShop: https://stza.co/+vMk9-2_\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144518Z
LAST-MODIFIED:20180213T144518Z
TRANSP:OPAQUE
END:VEVENT
* Tortugas vs. Flying Tigers
<2018-05-04 Fri 18:05-21:05>
:PROPERTIES:
:ID:       t6rFCZaItfpP7eBK80cX3BRZ@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Tortugas vs. Flying Tigers Tortugas vs. Flying Tigers

Follow on MiLB First Pitch  https //stza.co/+vMi0-1h

Shop  https //stza.co/+vMi0-27

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Tortugas vs. Flying Tigers
END:VALARM
DTSTART:20180504T230500Z
DTEND:20180505T020500Z
UID:t6rFCZaItfpP7eBK80cX3BRZ@stanza.co
SUMMARY:Tortugas vs. Flying Tigers
DESCRIPTION:Tortugas vs. Flying Tigers\n\nFollow on MiLB First Pitch: https://stza.co/+vMi0-1h\n\nShop: https://stza.co/+vMi0-27\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144518Z
LAST-MODIFIED:20180213T144518Z
TRANSP:OPAQUE
END:VEVENT
* Tortugas vs. Flying Tigers
<2018-05-05 Sat 18:05-21:05>
:PROPERTIES:
:ID:       Ch-u9fhACFSj6J078cEjfWol@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Tortugas vs. Flying Tigers Tortugas vs. Flying Tigers

Follow on MiLB First Pitch  https //stza.co/+vMi2-1w

Shop  https //stza.co/+vMi2-3J

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Tortugas vs. Flying Tigers
END:VALARM
DTSTART:20180505T230500Z
DTEND:20180506T020500Z
UID:Ch-u9fhACFSj6J078cEjfWol@stanza.co
SUMMARY:Tortugas vs. Flying Tigers
DESCRIPTION:Tortugas vs. Flying Tigers\n\nFollow on MiLB First Pitch: https://stza.co/+vMi2-1w\n\nShop: https://stza.co/+vMi2-3J\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144518Z
LAST-MODIFIED:20180213T144518Z
TRANSP:OPAQUE
END:VEVENT
* Tortugas vs. Flying Tigers
<2018-05-06 Sun 16:35-19:35>
:PROPERTIES:
:ID:       pW8oMlVVFKRRRrzg4H_ywt7v@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Tortugas vs. Flying Tigers Tortugas vs. Flying Tigers

Follow on MiLB First Pitch  https //stza.co/+vMi5-1m

Shop  https //stza.co/+vMi5-33

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Tortugas vs. Flying Tigers
END:VALARM
DTSTART:20180506T213500Z
DTEND:20180507T003500Z
UID:pW8oMlVVFKRRRrzg4H_ywt7v@stanza.co
SUMMARY:Tortugas vs. Flying Tigers
DESCRIPTION:Tortugas vs. Flying Tigers\n\nFollow on MiLB First Pitch: https://stza.co/+vMi5-1m\n\nShop: https://stza.co/+vMi5-33\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144518Z
LAST-MODIFIED:20180213T144518Z
TRANSP:OPAQUE
END:VEVENT
* Tortugas vs. Tarpons
<2018-05-07 Mon 18:05-21:05>
:PROPERTIES:
:ID:       Pd1QAWReX4265wQibOV1zkv3@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Tortugas vs. Tarpons Tortugas vs. Tarpons

Follow on MiLB First Pitch  https //stza.co/+vMi6-35

Shop  https //stza.co/+vMi6-f

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Tortugas vs. Tarpons
END:VALARM
DTSTART:20180507T230500Z
DTEND:20180508T020500Z
UID:Pd1QAWReX4265wQibOV1zkv3@stanza.co
SUMMARY:Tortugas vs. Tarpons
DESCRIPTION:Tortugas vs. Tarpons\n\nFollow on MiLB First Pitch: https://stza.co/+vMi6-35\n\nShop: https://stza.co/+vMi6-f\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144518Z
LAST-MODIFIED:20180213T144518Z
TRANSP:OPAQUE
END:VEVENT
* Tortugas vs. Tarpons
<2018-05-08 Tue 18:05-21:05>
:PROPERTIES:
:ID:       yooyUjaY5LGubUioP45sm36R@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Tortugas vs. Tarpons Tortugas vs. Tarpons

Follow on MiLB First Pitch  https //stza.co/+vMi9-2Z

Shop  https //stza.co/+vMi9-f

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Tortugas vs. Tarpons
END:VALARM
DTSTART:20180508T230500Z
DTEND:20180509T020500Z
UID:yooyUjaY5LGubUioP45sm36R@stanza.co
SUMMARY:Tortugas vs. Tarpons
DESCRIPTION:Tortugas vs. Tarpons\n\nFollow on MiLB First Pitch: https://stza.co/+vMi9-2Z\n\nShop: https://stza.co/+vMi9-f\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144518Z
LAST-MODIFIED:20180213T144518Z
TRANSP:OPAQUE
END:VEVENT
* Tortugas vs. Tarpons
<2018-05-09 Wed 09:35-12:35>
:PROPERTIES:
:ID:       CoH_ixlgkzcERcoLYdjWe8Cn@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Tortugas vs. Tarpons Tortugas vs. Tarpons

Follow on MiLB First Pitch  https //stza.co/+vMib-2f

Shop  https //stza.co/+vMib-1Q

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Tortugas vs. Tarpons
END:VALARM
DTSTART:20180509T143500Z
DTEND:20180509T173500Z
UID:CoH_ixlgkzcERcoLYdjWe8Cn@stanza.co
SUMMARY:Tortugas vs. Tarpons
DESCRIPTION:Tortugas vs. Tarpons\n\nFollow on MiLB First Pitch: https://stza.co/+vMib-2f\n\nShop: https://stza.co/+vMib-1Q\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144518Z
LAST-MODIFIED:20180213T144518Z
TRANSP:OPAQUE
END:VEVENT
* Tortugas @ Threshers
<2018-05-10 Thu 18:00-21:00>
:PROPERTIES:
:ID:       41VcWG8-39mnlrEB3wE9N1Ax@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Tortugas @ Threshers Tortugas @ Threshers

Follow on MiLB First Pitch  https //stza.co/+xBcz-2X

Shop  https //stza.co/+xBcz-b

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Tortugas @ Threshers
END:VALARM
DTSTART:20180510T230000Z
DTEND:20180511T020000Z
UID:41VcWG8-39mnlrEB3wE9N1Ax@stanza.co
SUMMARY:Tortugas @ Threshers
DESCRIPTION:Tortugas @ Threshers\n\nFollow on MiLB First Pitch: https://stza.co/+xBcz-2X\n\nShop: https://stza.co/+xBcz-b\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144518Z
LAST-MODIFIED:20180213T144518Z
TRANSP:OPAQUE
END:VEVENT
* Tortugas @ Threshers
<2018-05-11 Fri 17:15-20:15>
:PROPERTIES:
:ID:       e7t6it7V7J29fXLln2bjXsbo@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Tortugas @ Threshers Tortugas @ Threshers

Follow on MiLB First Pitch  https //stza.co/+xBcC-1R

Shop  https //stza.co/+xBcC-d

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Tortugas @ Threshers
END:VALARM
DTSTART:20180511T221500Z
DTEND:20180512T011500Z
UID:e7t6it7V7J29fXLln2bjXsbo@stanza.co
SUMMARY:Tortugas @ Threshers
DESCRIPTION:Tortugas @ Threshers\n\nFollow on MiLB First Pitch: https://stza.co/+xBcC-1R\n\nShop: https://stza.co/+xBcC-d\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144518Z
LAST-MODIFIED:20180213T144518Z
TRANSP:OPAQUE
END:VEVENT
* Tortugas @ Threshers
<2018-05-12 Sat 17:15-20:15>
:PROPERTIES:
:ID:       mtV3mEaAYopVCXw0L2UxHnMJ@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Tortugas @ Threshers Tortugas @ Threshers

Follow on MiLB First Pitch  https //stza.co/+xBcF-1

Shop  https //stza.co/+xBcF-26

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Tortugas @ Threshers
END:VALARM
DTSTART:20180512T221500Z
DTEND:20180513T011500Z
UID:mtV3mEaAYopVCXw0L2UxHnMJ@stanza.co
SUMMARY:Tortugas @ Threshers
DESCRIPTION:Tortugas @ Threshers\n\nFollow on MiLB First Pitch: https://stza.co/+xBcF-1\n\nShop: https://stza.co/+xBcF-26\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144518Z
LAST-MODIFIED:20180213T144518Z
TRANSP:OPAQUE
END:VEVENT
* Tortugas @ Marauders
<2018-05-14 Mon 17:30-20:30>
:PROPERTIES:
:ID:       b2kZYvi_uscn1Q9adw0EVEF3@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Tortugas @ Marauders Tortugas @ Marauders

Follow on MiLB First Pitch  https //stza.co/+vMhn-1V

Shop  https //stza.co/+vMhn-D

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Tortugas @ Marauders
END:VALARM
DTSTART:20180514T223000Z
DTEND:20180515T013000Z
UID:b2kZYvi_uscn1Q9adw0EVEF3@stanza.co
SUMMARY:Tortugas @ Marauders
DESCRIPTION:Tortugas @ Marauders\n\nFollow on MiLB First Pitch: https://stza.co/+vMhn-1V\n\nShop: https://stza.co/+vMhn-D\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144518Z
LAST-MODIFIED:20180213T144518Z
TRANSP:OPAQUE
END:VEVENT
* Tortugas @ Marauders
<2018-05-15 Tue 17:30-20:30>
:PROPERTIES:
:ID:       MWZHYY1PtPzGtKFoWmMPr3uD@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Tortugas @ Marauders Tortugas @ Marauders

Follow on MiLB First Pitch  https //stza.co/+vMho-2o

Shop  https //stza.co/+vMho-1N

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Tortugas @ Marauders
END:VALARM
DTSTART:20180515T223000Z
DTEND:20180516T013000Z
UID:MWZHYY1PtPzGtKFoWmMPr3uD@stanza.co
SUMMARY:Tortugas @ Marauders
DESCRIPTION:Tortugas @ Marauders\n\nFollow on MiLB First Pitch: https://stza.co/+vMho-2o\n\nShop: https://stza.co/+vMho-1N\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144518Z
LAST-MODIFIED:20180213T144518Z
TRANSP:OPAQUE
END:VEVENT
* Tortugas @ Marauders
<2018-05-16 Wed 09:30-12:30>
:PROPERTIES:
:ID:       uii7X36xAcxUgazobikEz3tn@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Tortugas @ Marauders Tortugas @ Marauders

Follow on MiLB First Pitch  https //stza.co/+vMhp-1k

Shop  https //stza.co/+vMhp-1D

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Tortugas @ Marauders
END:VALARM
DTSTART:20180516T143000Z
DTEND:20180516T173000Z
UID:uii7X36xAcxUgazobikEz3tn@stanza.co
SUMMARY:Tortugas @ Marauders
DESCRIPTION:Tortugas @ Marauders\n\nFollow on MiLB First Pitch: https://stza.co/+vMhp-1k\n\nShop: https://stza.co/+vMhp-1D\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144518Z
LAST-MODIFIED:20180213T144518Z
TRANSP:OPAQUE
END:VEVENT
* Tortugas @ Marauders
<2018-05-17 Thu 17:30-20:30>
:PROPERTIES:
:ID:       9xNSvdj_7E8mwkEpjRaJXhT-@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Tortugas @ Marauders Tortugas @ Marauders

Follow on MiLB First Pitch  https //stza.co/+vMhq-Z

Shop  https //stza.co/+vMhq-8

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Tortugas @ Marauders
END:VALARM
DTSTART:20180517T223000Z
DTEND:20180518T013000Z
UID:9xNSvdj_7E8mwkEpjRaJXhT-@stanza.co
SUMMARY:Tortugas @ Marauders
DESCRIPTION:Tortugas @ Marauders\n\nFollow on MiLB First Pitch: https://stza.co/+vMhq-Z\n\nShop: https://stza.co/+vMhq-8\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144518Z
LAST-MODIFIED:20180213T144518Z
TRANSP:OPAQUE
END:VEVENT
* Tortugas vs. Blue Jays
<2018-05-18 Fri 18:05-21:05>
:PROPERTIES:
:ID:       sD72CzEJvXqcgL4CB_719FX4@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Tortugas vs. Blue Jays Tortugas vs. Blue Jays

Follow on MiLB First Pitch  https //stza.co/+vMid-2T

Shop  https //stza.co/+vMid-3C

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Tortugas vs. Blue Jays
END:VALARM
DTSTART:20180518T230500Z
DTEND:20180519T020500Z
UID:sD72CzEJvXqcgL4CB_719FX4@stanza.co
SUMMARY:Tortugas vs. Blue Jays
DESCRIPTION:Tortugas vs. Blue Jays\n\nFollow on MiLB First Pitch: https://stza.co/+vMid-2T\n\nShop: https://stza.co/+vMid-3C\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144518Z
LAST-MODIFIED:20180213T144518Z
TRANSP:OPAQUE
END:VEVENT
* Tortugas vs. Blue Jays
<2018-05-19 Sat 18:05-21:05>
:PROPERTIES:
:ID:       cKYtaOwDzcgrp1ntaXzdZGC6@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Tortugas vs. Blue Jays Tortugas vs. Blue Jays

Follow on MiLB First Pitch  https //stza.co/+vMie-h

Shop  https //stza.co/+vMie-P

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Tortugas vs. Blue Jays
END:VALARM
DTSTART:20180519T230500Z
DTEND:20180520T020500Z
UID:cKYtaOwDzcgrp1ntaXzdZGC6@stanza.co
SUMMARY:Tortugas vs. Blue Jays
DESCRIPTION:Tortugas vs. Blue Jays\n\nFollow on MiLB First Pitch: https://stza.co/+vMie-h\n\nShop: https://stza.co/+vMie-P\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144518Z
LAST-MODIFIED:20180213T144518Z
TRANSP:OPAQUE
END:VEVENT
* Tortugas vs. Blue Jays
<2018-05-20 Sun 16:35-19:35>
:PROPERTIES:
:ID:       eEyMbIzPBjhyxj-lWzHo6tqy@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Tortugas vs. Blue Jays Tortugas vs. Blue Jays

Follow on MiLB First Pitch  https //stza.co/+vMig-3R

Shop  https //stza.co/+vMig-25

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Tortugas vs. Blue Jays
END:VALARM
DTSTART:20180520T213500Z
DTEND:20180521T003500Z
UID:eEyMbIzPBjhyxj-lWzHo6tqy@stanza.co
SUMMARY:Tortugas vs. Blue Jays
DESCRIPTION:Tortugas vs. Blue Jays\n\nFollow on MiLB First Pitch: https://stza.co/+vMig-3R\n\nShop: https://stza.co/+vMig-25\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144518Z
LAST-MODIFIED:20180213T144518Z
TRANSP:OPAQUE
END:VEVENT
* Tortugas @ Hammerheads
<2018-05-21 Mon>--<2018-05-20 Sun>
:PROPERTIES:
:ID:       WL4E_YEe43-dPP6QL13N_rNz@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Tortugas @ Hammerheads Tortugas @ Hammerheads

Buy tickets here  https //stza.co/~vMka

Follow on MiLB First Pitch  https //stza.co/+vMka-2Z

Shop  https //stza.co/+vMka-F

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Tortugas @ Hammerheads
END:VALARM
DTSTART;VALUE=DATE:20180521
DTEND;VALUE=DATE:20180521
UID:WL4E_YEe43-dPP6QL13N_rNz@stanza.co
SUMMARY:Tortugas @ Hammerheads
DESCRIPTION:Tortugas @ Hammerheads\n\nBuy tickets here: https://stza.co/~vMka\n\nFollow on MiLB First Pitch: https://stza.co/+vMka-2Z\n\nShop: https://stza.co/+vMka-F\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144518Z
LAST-MODIFIED:20180213T144518Z
TRANSP:OPAQUE
END:VEVENT
* Tortugas @ Hammerheads
<2018-05-22 Tue>--<2018-05-21 Mon>
:PROPERTIES:
:ID:       HkQY1ybkxEtUTxkNaPozM6yM@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Tortugas @ Hammerheads Tortugas @ Hammerheads

Buy tickets here  https //stza.co/~vMkb

Follow on MiLB First Pitch  https //stza.co/+vMkb-2Z

Shop  https //stza.co/+vMkb-9

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Tortugas @ Hammerheads
END:VALARM
DTSTART;VALUE=DATE:20180522
DTEND;VALUE=DATE:20180522
UID:HkQY1ybkxEtUTxkNaPozM6yM@stanza.co
SUMMARY:Tortugas @ Hammerheads
DESCRIPTION:Tortugas @ Hammerheads\n\nBuy tickets here: https://stza.co/~vMkb\n\nFollow on MiLB First Pitch: https://stza.co/+vMkb-2Z\n\nShop: https://stza.co/+vMkb-9\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144518Z
LAST-MODIFIED:20180213T144518Z
TRANSP:OPAQUE
END:VEVENT
* Tortugas @ Hammerheads
<2018-05-23 Wed>--<2018-05-22 Tue>
:PROPERTIES:
:ID:       ZeguqYLH4a6IElrZy4hEG8FU@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Tortugas @ Hammerheads Tortugas @ Hammerheads

Buy tickets here  https //stza.co/~vMkc

Follow on MiLB First Pitch  https //stza.co/+vMkc-3m

Shop  https //stza.co/+vMkc-W

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Tortugas @ Hammerheads
END:VALARM
DTSTART;VALUE=DATE:20180523
DTEND;VALUE=DATE:20180523
UID:ZeguqYLH4a6IElrZy4hEG8FU@stanza.co
SUMMARY:Tortugas @ Hammerheads
DESCRIPTION:Tortugas @ Hammerheads\n\nBuy tickets here: https://stza.co/~vMkc\n\nFollow on MiLB First Pitch: https://stza.co/+vMkc-3m\n\nShop: https://stza.co/+vMkc-W\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144518Z
LAST-MODIFIED:20180213T144518Z
TRANSP:OPAQUE
END:VEVENT
* Tortugas vs. Mets
<2018-05-24 Thu 18:05-21:05>
:PROPERTIES:
:ID:       k_dFDfc0lRtzZScdv--JDqW6@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Tortugas vs. Mets Tortugas vs. Mets

Follow on MiLB First Pitch  https //stza.co/+vMii-2X

Shop  https //stza.co/+vMii-3g

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Tortugas vs. Mets
END:VALARM
DTSTART:20180524T230500Z
DTEND:20180525T020500Z
UID:k_dFDfc0lRtzZScdv--JDqW6@stanza.co
SUMMARY:Tortugas vs. Mets
DESCRIPTION:Tortugas vs. Mets\n\nFollow on MiLB First Pitch: https://stza.co/+vMii-2X\n\nShop: https://stza.co/+vMii-3g\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144518Z
LAST-MODIFIED:20180213T144518Z
TRANSP:OPAQUE
END:VEVENT
* Tortugas vs. Mets
<2018-05-25 Fri 18:05-21:05>
:PROPERTIES:
:ID:       3o8FUNMj0JTBZZOCI8CFUW6s@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Tortugas vs. Mets Tortugas vs. Mets

Follow on MiLB First Pitch  https //stza.co/+vMik-36

Shop  https //stza.co/+vMik-c

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Tortugas vs. Mets
END:VALARM
DTSTART:20180525T230500Z
DTEND:20180526T020500Z
UID:3o8FUNMj0JTBZZOCI8CFUW6s@stanza.co
SUMMARY:Tortugas vs. Mets
DESCRIPTION:Tortugas vs. Mets\n\nFollow on MiLB First Pitch: https://stza.co/+vMik-36\n\nShop: https://stza.co/+vMik-c\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144518Z
LAST-MODIFIED:20180213T144518Z
TRANSP:OPAQUE
END:VEVENT
* Tortugas vs. Mets
<2018-05-26 Sat 18:05-21:05>
:PROPERTIES:
:ID:       l7viRQ-FPDUF43Us55hnNBRF@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Tortugas vs. Mets Tortugas vs. Mets

Follow on MiLB First Pitch  https //stza.co/+vMim-4

Shop  https //stza.co/+vMim-m

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Tortugas vs. Mets
END:VALARM
DTSTART:20180526T230500Z
DTEND:20180527T020500Z
UID:l7viRQ-FPDUF43Us55hnNBRF@stanza.co
SUMMARY:Tortugas vs. Mets
DESCRIPTION:Tortugas vs. Mets\n\nFollow on MiLB First Pitch: https://stza.co/+vMim-4\n\nShop: https://stza.co/+vMim-m\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144518Z
LAST-MODIFIED:20180213T144518Z
TRANSP:OPAQUE
END:VEVENT
* Tortugas vs. Mets
<2018-05-27 Sun 17:35-20:35>
:PROPERTIES:
:ID:       Da_PZwJi8hYI0agtnlPzMxLH@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Tortugas vs. Mets Tortugas vs. Mets

Follow on MiLB First Pitch  https //stza.co/+vMip-2N

Shop  https //stza.co/+vMip-3N

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Tortugas vs. Mets
END:VALARM
DTSTART:20180527T223500Z
DTEND:20180528T013500Z
UID:Da_PZwJi8hYI0agtnlPzMxLH@stanza.co
SUMMARY:Tortugas vs. Mets
DESCRIPTION:Tortugas vs. Mets\n\nFollow on MiLB First Pitch: https://stza.co/+vMip-2N\n\nShop: https://stza.co/+vMip-3N\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144518Z
LAST-MODIFIED:20180213T144518Z
TRANSP:OPAQUE
END:VEVENT
* Tortugas vs. Marauders
<2018-05-29 Tue 18:05-21:05>
:PROPERTIES:
:ID:       cNvk21K0Tsn36uY_rqv6ZyR6@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Tortugas vs. Marauders Tortugas vs. Marauders

Follow on MiLB First Pitch  https //stza.co/+vMir-6

Shop  https //stza.co/+vMir-23

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Tortugas vs. Marauders
END:VALARM
DTSTART:20180529T230500Z
DTEND:20180530T020500Z
UID:cNvk21K0Tsn36uY_rqv6ZyR6@stanza.co
SUMMARY:Tortugas vs. Marauders
DESCRIPTION:Tortugas vs. Marauders\n\nFollow on MiLB First Pitch: https://stza.co/+vMir-6\n\nShop: https://stza.co/+vMir-23\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144518Z
LAST-MODIFIED:20180213T144518Z
TRANSP:OPAQUE
END:VEVENT
* Tortugas vs. Marauders
<2018-05-30 Wed 18:05-21:05>
:PROPERTIES:
:ID:       DhzL4RzvCg_AAt4YAEK_4RtI@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Tortugas vs. Marauders Tortugas vs. Marauders

Follow on MiLB First Pitch  https //stza.co/+vMis-p

Shop  https //stza.co/+vMis-2O

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Tortugas vs. Marauders
END:VALARM
DTSTART:20180530T230500Z
DTEND:20180531T020500Z
UID:DhzL4RzvCg_AAt4YAEK_4RtI@stanza.co
SUMMARY:Tortugas vs. Marauders
DESCRIPTION:Tortugas vs. Marauders\n\nFollow on MiLB First Pitch: https://stza.co/+vMis-p\n\nShop: https://stza.co/+vMis-2O\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144518Z
LAST-MODIFIED:20180213T144518Z
TRANSP:OPAQUE
END:VEVENT
* Tortugas vs. Marauders
<2018-05-31 Thu 18:05-21:05>
:PROPERTIES:
:ID:       KY_4agRy_V2JTxTFqBZ2ZrlQ@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Tortugas vs. Marauders Tortugas vs. Marauders

Follow on MiLB First Pitch  https //stza.co/+vMiv-i

Shop  https //stza.co/+vMiv-12

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Tortugas vs. Marauders
END:VALARM
DTSTART:20180531T230500Z
DTEND:20180601T020500Z
UID:KY_4agRy_V2JTxTFqBZ2ZrlQ@stanza.co
SUMMARY:Tortugas vs. Marauders
DESCRIPTION:Tortugas vs. Marauders\n\nFollow on MiLB First Pitch: https://stza.co/+vMiv-i\n\nShop: https://stza.co/+vMiv-12\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144518Z
LAST-MODIFIED:20180213T144518Z
TRANSP:OPAQUE
END:VEVENT
* Tortugas @ Flying Tigers
<2018-06-01 Fri 17:30-20:30>
:PROPERTIES:
:ID:       eYOK2qdqE3KpmoDRLILx-aUU@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Tortugas @ Flying Tigers Tortugas @ Flying Tigers

Follow on MiLB First Pitch  https //stza.co/+wKMk-1M

Shop  https //stza.co/+wKMk-l

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Tortugas @ Flying Tigers
END:VALARM
DTSTART:20180601T223000Z
DTEND:20180602T013000Z
UID:eYOK2qdqE3KpmoDRLILx-aUU@stanza.co
SUMMARY:Tortugas @ Flying Tigers
DESCRIPTION:Tortugas @ Flying Tigers\n\nFollow on MiLB First Pitch: https://stza.co/+wKMk-1M\n\nShop: https://stza.co/+wKMk-l\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144518Z
LAST-MODIFIED:20180213T144518Z
TRANSP:OPAQUE
END:VEVENT
* Tortugas @ Flying Tigers
<2018-06-02 Sat 17:00-20:00>
:PROPERTIES:
:ID:       XS_-r0DmYtrf7GNhgSDLdQaG@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Tortugas @ Flying Tigers Tortugas @ Flying Tigers

Follow on MiLB First Pitch  https //stza.co/+wKMl-2N

Shop  https //stza.co/+wKMl-3X

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Tortugas @ Flying Tigers
END:VALARM
DTSTART:20180602T220000Z
DTEND:20180603T010000Z
UID:XS_-r0DmYtrf7GNhgSDLdQaG@stanza.co
SUMMARY:Tortugas @ Flying Tigers
DESCRIPTION:Tortugas @ Flying Tigers\n\nFollow on MiLB First Pitch: https://stza.co/+wKMl-2N\n\nShop: https://stza.co/+wKMl-3X\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144518Z
LAST-MODIFIED:20180213T144518Z
TRANSP:OPAQUE
END:VEVENT
* Tortugas @ Flying Tigers
<2018-06-03 Sun 12:00-15:00>
:PROPERTIES:
:ID:       IRr3h7FukAdiYpA2lAti4EFf@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Tortugas @ Flying Tigers Tortugas @ Flying Tigers

Follow on MiLB First Pitch  https //stza.co/+wKMm-2p

Shop  https //stza.co/+wKMm-27

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Tortugas @ Flying Tigers
END:VALARM
DTSTART:20180603T170000Z
DTEND:20180603T200000Z
UID:IRr3h7FukAdiYpA2lAti4EFf@stanza.co
SUMMARY:Tortugas @ Flying Tigers
DESCRIPTION:Tortugas @ Flying Tigers\n\nFollow on MiLB First Pitch: https://stza.co/+wKMm-2p\n\nShop: https://stza.co/+wKMm-27\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144518Z
LAST-MODIFIED:20180213T144518Z
TRANSP:OPAQUE
END:VEVENT
* Tortugas vs. Threshers
<2018-06-04 Mon 18:05-21:05>
:PROPERTIES:
:ID:       HMLbXa3Pad4pph4H0kYeibjO@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Tortugas vs. Threshers Tortugas vs. Threshers

Follow on MiLB First Pitch  https //stza.co/+vMix-3e

Shop  https //stza.co/+vMix-1t

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Tortugas vs. Threshers
END:VALARM
DTSTART:20180604T230500Z
DTEND:20180605T020500Z
UID:HMLbXa3Pad4pph4H0kYeibjO@stanza.co
SUMMARY:Tortugas vs. Threshers
DESCRIPTION:Tortugas vs. Threshers\n\nFollow on MiLB First Pitch: https://stza.co/+vMix-3e\n\nShop: https://stza.co/+vMix-1t\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144518Z
LAST-MODIFIED:20180213T144518Z
TRANSP:OPAQUE
END:VEVENT
* Tortugas vs. Threshers
<2018-06-05 Tue 18:05-21:05>
:PROPERTIES:
:ID:       vqVN9YrjWT073ykG9oAzm6qi@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Tortugas vs. Threshers Tortugas vs. Threshers

Follow on MiLB First Pitch  https //stza.co/+vMiy-F

Shop  https //stza.co/+vMiy-2i

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Tortugas vs. Threshers
END:VALARM
DTSTART:20180605T230500Z
DTEND:20180606T020500Z
UID:vqVN9YrjWT073ykG9oAzm6qi@stanza.co
SUMMARY:Tortugas vs. Threshers
DESCRIPTION:Tortugas vs. Threshers\n\nFollow on MiLB First Pitch: https://stza.co/+vMiy-F\n\nShop: https://stza.co/+vMiy-2i\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144518Z
LAST-MODIFIED:20180213T144518Z
TRANSP:OPAQUE
END:VEVENT
* Tortugas vs. Threshers
<2018-06-06 Wed 18:05-21:05>
:PROPERTIES:
:ID:       upLR-wec5rWrMFWPUJKjb5GM@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Tortugas vs. Threshers Tortugas vs. Threshers

Follow on MiLB First Pitch  https //stza.co/+vMiA-22

Shop  https //stza.co/+vMiA-K

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Tortugas vs. Threshers
END:VALARM
DTSTART:20180606T230500Z
DTEND:20180607T020500Z
UID:upLR-wec5rWrMFWPUJKjb5GM@stanza.co
SUMMARY:Tortugas vs. Threshers
DESCRIPTION:Tortugas vs. Threshers\n\nFollow on MiLB First Pitch: https://stza.co/+vMiA-22\n\nShop: https://stza.co/+vMiA-K\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144518Z
LAST-MODIFIED:20180213T144518Z
TRANSP:OPAQUE
END:VEVENT
* Tortugas vs. Threshers
<2018-06-07 Thu 18:05-21:05>
:PROPERTIES:
:ID:       tRq8T4WmCUqUeIEevQIT7QXs@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Tortugas vs. Threshers Tortugas vs. Threshers

Follow on MiLB First Pitch  https //stza.co/+vMiD-2$

Shop  https //stza.co/+vMiD-3P

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Tortugas vs. Threshers
END:VALARM
DTSTART:20180607T230500Z
DTEND:20180608T020500Z
UID:tRq8T4WmCUqUeIEevQIT7QXs@stanza.co
SUMMARY:Tortugas vs. Threshers
DESCRIPTION:Tortugas vs. Threshers\n\nFollow on MiLB First Pitch: https://stza.co/+vMiD-2$\n\nShop: https://stza.co/+vMiD-3P\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144518Z
LAST-MODIFIED:20180213T144518Z
TRANSP:OPAQUE
END:VEVENT
* Tortugas @ Cardinals
<2018-06-08 Fri>--<2018-06-07 Thu>
:PROPERTIES:
:ID:       389MiDkb7SANyZMEoryNCjh_@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Tortugas @ Cardinals Tortugas @ Cardinals

Buy tickets here  https //stza.co/~vMkk

Follow on MiLB First Pitch  https //stza.co/+vMkk-1M

Shop  https //stza.co/+vMkk-q

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Tortugas @ Cardinals
END:VALARM
DTSTART;VALUE=DATE:20180608
DTEND;VALUE=DATE:20180608
UID:389MiDkb7SANyZMEoryNCjh_@stanza.co
SUMMARY:Tortugas @ Cardinals
DESCRIPTION:Tortugas @ Cardinals\n\nBuy tickets here: https://stza.co/~vMkk\n\nFollow on MiLB First Pitch: https://stza.co/+vMkk-1M\n\nShop: https://stza.co/+vMkk-q\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144518Z
LAST-MODIFIED:20180213T144518Z
TRANSP:OPAQUE
END:VEVENT
* Tortugas @ Cardinals
<2018-06-09 Sat>--<2018-06-08 Fri>
:PROPERTIES:
:ID:       Z9h6-02rMCGj69fAaqiGuMvz@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Tortugas @ Cardinals Tortugas @ Cardinals

Buy tickets here  https //stza.co/~vMkl

Follow on MiLB First Pitch  https //stza.co/+vMkl-T

Shop  https //stza.co/+vMkl-1I

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Tortugas @ Cardinals
END:VALARM
DTSTART;VALUE=DATE:20180609
DTEND;VALUE=DATE:20180609
UID:Z9h6-02rMCGj69fAaqiGuMvz@stanza.co
SUMMARY:Tortugas @ Cardinals
DESCRIPTION:Tortugas @ Cardinals\n\nBuy tickets here: https://stza.co/~vMkl\n\nFollow on MiLB First Pitch: https://stza.co/+vMkl-T\n\nShop: https://stza.co/+vMkl-1I\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144518Z
LAST-MODIFIED:20180213T144518Z
TRANSP:OPAQUE
END:VEVENT
* Tortugas @ Cardinals
<2018-06-10 Sun>--<2018-06-09 Sat>
:PROPERTIES:
:ID:       nqvoOb0Fgw6ttCxKf5DDo4Fu@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Tortugas @ Cardinals Tortugas @ Cardinals

Buy tickets here  https //stza.co/~vMkm

Follow on MiLB First Pitch  https //stza.co/+vMkm-2V

Shop  https //stza.co/+vMkm-1q

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Tortugas @ Cardinals
END:VALARM
DTSTART;VALUE=DATE:20180610
DTEND;VALUE=DATE:20180610
UID:nqvoOb0Fgw6ttCxKf5DDo4Fu@stanza.co
SUMMARY:Tortugas @ Cardinals
DESCRIPTION:Tortugas @ Cardinals\n\nBuy tickets here: https://stza.co/~vMkm\n\nFollow on MiLB First Pitch: https://stza.co/+vMkm-2V\n\nShop: https://stza.co/+vMkm-1q\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144518Z
LAST-MODIFIED:20180213T144518Z
TRANSP:OPAQUE
END:VEVENT
* Tortugas @ Mets
<2018-06-11 Mon 17:30-20:30>
:PROPERTIES:
:ID:       KOuWzUyWXtl0TuuQU82Pkje-@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Tortugas @ Mets Tortugas @ Mets

Follow on MiLB First Pitch  https //stza.co/+vMks-P

Shop  https //stza.co/+vMks-9

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Tortugas @ Mets
END:VALARM
DTSTART:20180611T223000Z
DTEND:20180612T013000Z
UID:KOuWzUyWXtl0TuuQU82Pkje-@stanza.co
SUMMARY:Tortugas @ Mets
DESCRIPTION:Tortugas @ Mets\n\nFollow on MiLB First Pitch: https://stza.co/+vMks-P\n\nShop: https://stza.co/+vMks-9\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144518Z
LAST-MODIFIED:20180213T144518Z
TRANSP:OPAQUE
END:VEVENT
* Tortugas @ Mets
<2018-06-12 Tue 17:30-20:30>
:PROPERTIES:
:ID:       ov8gcapFTizIim9229bHscoE@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Tortugas @ Mets Tortugas @ Mets

Follow on MiLB First Pitch  https //stza.co/+vMkt-3p

Shop  https //stza.co/+vMkt-3_

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Tortugas @ Mets
END:VALARM
DTSTART:20180612T223000Z
DTEND:20180613T013000Z
UID:ov8gcapFTizIim9229bHscoE@stanza.co
SUMMARY:Tortugas @ Mets
DESCRIPTION:Tortugas @ Mets\n\nFollow on MiLB First Pitch: https://stza.co/+vMkt-3p\n\nShop: https://stza.co/+vMkt-3_\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144518Z
LAST-MODIFIED:20180213T144518Z
TRANSP:OPAQUE
END:VEVENT
* Tortugas @ Mets
<2018-06-13 Wed 17:30-20:30>
:PROPERTIES:
:ID:       Ib6GUF3qT6m6LrIdKvZk3q_E@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Tortugas @ Mets Tortugas @ Mets

Follow on MiLB First Pitch  https //stza.co/+vMku-1h

Shop  https //stza.co/+vMku-24

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Tortugas @ Mets
END:VALARM
DTSTART:20180613T223000Z
DTEND:20180614T013000Z
UID:Ib6GUF3qT6m6LrIdKvZk3q_E@stanza.co
SUMMARY:Tortugas @ Mets
DESCRIPTION:Tortugas @ Mets\n\nFollow on MiLB First Pitch: https://stza.co/+vMku-1h\n\nShop: https://stza.co/+vMku-24\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144518Z
LAST-MODIFIED:20180213T144518Z
TRANSP:OPAQUE
END:VEVENT
* Tortugas @ Mets
<2018-06-14 Thu 17:30-20:30>
:PROPERTIES:
:ID:       AHmKVSvyn_cxKzg87JeOTen5@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Tortugas @ Mets Tortugas @ Mets

Follow on MiLB First Pitch  https //stza.co/+vMkv-2L

Shop  https //stza.co/+vMkv-2r

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Tortugas @ Mets
END:VALARM
DTSTART:20180614T223000Z
DTEND:20180615T013000Z
UID:AHmKVSvyn_cxKzg87JeOTen5@stanza.co
SUMMARY:Tortugas @ Mets
DESCRIPTION:Tortugas @ Mets\n\nFollow on MiLB First Pitch: https://stza.co/+vMkv-2L\n\nShop: https://stza.co/+vMkv-2r\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144518Z
LAST-MODIFIED:20180213T144518Z
TRANSP:OPAQUE
END:VEVENT
* Tortugas vs. Cardinals
<2018-06-18 Mon 18:05-21:05>
:PROPERTIES:
:ID:       B_n-nbY8hV4wlNeV7yVpbFEj@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Tortugas vs. Cardinals Tortugas vs. Cardinals

Follow on MiLB First Pitch  https //stza.co/+vMiF-c

Shop  https //stza.co/+vMiF-25

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Tortugas vs. Cardinals
END:VALARM
DTSTART:20180618T230500Z
DTEND:20180619T020500Z
UID:B_n-nbY8hV4wlNeV7yVpbFEj@stanza.co
SUMMARY:Tortugas vs. Cardinals
DESCRIPTION:Tortugas vs. Cardinals\n\nFollow on MiLB First Pitch: https://stza.co/+vMiF-c\n\nShop: https://stza.co/+vMiF-25\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144518Z
LAST-MODIFIED:20180213T144518Z
TRANSP:OPAQUE
END:VEVENT
* Tortugas vs. Cardinals
<2018-06-19 Tue 18:05-21:05>
:PROPERTIES:
:ID:       J3rTZfQWRxwPAy1Cd2YV8i5l@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Tortugas vs. Cardinals Tortugas vs. Cardinals

Follow on MiLB First Pitch  https //stza.co/+vMiG-1w

Shop  https //stza.co/+vMiG-3s

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Tortugas vs. Cardinals
END:VALARM
DTSTART:20180619T230500Z
DTEND:20180620T020500Z
UID:J3rTZfQWRxwPAy1Cd2YV8i5l@stanza.co
SUMMARY:Tortugas vs. Cardinals
DESCRIPTION:Tortugas vs. Cardinals\n\nFollow on MiLB First Pitch: https://stza.co/+vMiG-1w\n\nShop: https://stza.co/+vMiG-3s\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144518Z
LAST-MODIFIED:20180213T144518Z
TRANSP:OPAQUE
END:VEVENT
* Tortugas vs. Cardinals
<2018-06-20 Wed 09:35-12:35>
:PROPERTIES:
:ID:       lVV-d5ApyqB05Gbucu9gMIRs@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Tortugas vs. Cardinals Tortugas vs. Cardinals

Follow on MiLB First Pitch  https //stza.co/+vMiJ-1Z

Shop  https //stza.co/+vMiJ-33

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Tortugas vs. Cardinals
END:VALARM
DTSTART:20180620T143500Z
DTEND:20180620T173500Z
UID:lVV-d5ApyqB05Gbucu9gMIRs@stanza.co
SUMMARY:Tortugas vs. Cardinals
DESCRIPTION:Tortugas vs. Cardinals\n\nFollow on MiLB First Pitch: https://stza.co/+vMiJ-1Z\n\nShop: https://stza.co/+vMiJ-33\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144518Z
LAST-MODIFIED:20180213T144518Z
TRANSP:OPAQUE
END:VEVENT
* Tortugas vs. Fire Frogs
<2018-06-21 Thu 18:05-21:05>
:PROPERTIES:
:ID:       558bpf0DDUg6fELq2lItvXcO@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Tortugas vs. Fire Frogs Tortugas vs. Fire Frogs

Follow on MiLB First Pitch  https //stza.co/+vMiL-X

Shop  https //stza.co/+vMiL-3v

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Tortugas vs. Fire Frogs
END:VALARM
DTSTART:20180621T230500Z
DTEND:20180622T020500Z
UID:558bpf0DDUg6fELq2lItvXcO@stanza.co
SUMMARY:Tortugas vs. Fire Frogs
DESCRIPTION:Tortugas vs. Fire Frogs\n\nFollow on MiLB First Pitch: https://stza.co/+vMiL-X\n\nShop: https://stza.co/+vMiL-3v\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144518Z
LAST-MODIFIED:20180213T144518Z
TRANSP:OPAQUE
END:VEVENT
* Tortugas vs. Fire Frogs
<2018-06-22 Fri 18:05-21:05>
:PROPERTIES:
:ID:       l75gTVU6aIkFH8WM441bK6FX@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Tortugas vs. Fire Frogs Tortugas vs. Fire Frogs

Follow on MiLB First Pitch  https //stza.co/+vMiN-3C

Shop  https //stza.co/+vMiN-1X

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Tortugas vs. Fire Frogs
END:VALARM
DTSTART:20180622T230500Z
DTEND:20180623T020500Z
UID:l75gTVU6aIkFH8WM441bK6FX@stanza.co
SUMMARY:Tortugas vs. Fire Frogs
DESCRIPTION:Tortugas vs. Fire Frogs\n\nFollow on MiLB First Pitch: https://stza.co/+vMiN-3C\n\nShop: https://stza.co/+vMiN-1X\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144518Z
LAST-MODIFIED:20180213T144518Z
TRANSP:OPAQUE
END:VEVENT
* Tortugas vs. Fire Frogs
<2018-06-23 Sat 18:05-21:05>
:PROPERTIES:
:ID:       zttgiUOskzOqp0Z7FWkgpNhU@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Tortugas vs. Fire Frogs Tortugas vs. Fire Frogs

Follow on MiLB First Pitch  https //stza.co/+vMiP-1P

Shop  https //stza.co/+vMiP-17

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Tortugas vs. Fire Frogs
END:VALARM
DTSTART:20180623T230500Z
DTEND:20180624T020500Z
UID:zttgiUOskzOqp0Z7FWkgpNhU@stanza.co
SUMMARY:Tortugas vs. Fire Frogs
DESCRIPTION:Tortugas vs. Fire Frogs\n\nFollow on MiLB First Pitch: https://stza.co/+vMiP-1P\n\nShop: https://stza.co/+vMiP-17\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144518Z
LAST-MODIFIED:20180213T144518Z
TRANSP:OPAQUE
END:VEVENT
* Tortugas vs. Fire Frogs
<2018-06-24 Sun 16:35-19:35>
:PROPERTIES:
:ID:       Ibl2ys1AyjtfuozsvVt00Ohh@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Tortugas vs. Fire Frogs Tortugas vs. Fire Frogs

Follow on MiLB First Pitch  https //stza.co/+vMiR-6

Shop  https //stza.co/+vMiR-h

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Tortugas vs. Fire Frogs
END:VALARM
DTSTART:20180624T213500Z
DTEND:20180625T003500Z
UID:Ibl2ys1AyjtfuozsvVt00Ohh@stanza.co
SUMMARY:Tortugas vs. Fire Frogs
DESCRIPTION:Tortugas vs. Fire Frogs\n\nFollow on MiLB First Pitch: https://stza.co/+vMiR-6\n\nShop: https://stza.co/+vMiR-h\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144518Z
LAST-MODIFIED:20180213T144518Z
TRANSP:OPAQUE
END:VEVENT
* Tortugas vs. Threshers
<2018-06-26 Tue 18:05-21:05>
:PROPERTIES:
:ID:       f31jaM1cOuIlJkeC7oUN8Tm_@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Tortugas vs. Threshers Tortugas vs. Threshers

Follow on MiLB First Pitch  https //stza.co/+vMiT-24

Shop  https //stza.co/+vMiT-1r

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Tortugas vs. Threshers
END:VALARM
DTSTART:20180626T230500Z
DTEND:20180627T020500Z
UID:f31jaM1cOuIlJkeC7oUN8Tm_@stanza.co
SUMMARY:Tortugas vs. Threshers
DESCRIPTION:Tortugas vs. Threshers\n\nFollow on MiLB First Pitch: https://stza.co/+vMiT-24\n\nShop: https://stza.co/+vMiT-1r\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144518Z
LAST-MODIFIED:20180213T144518Z
TRANSP:OPAQUE
END:VEVENT
* Tortugas vs. Threshers
<2018-06-27 Wed 09:35-12:35>
:PROPERTIES:
:ID:       r3CFfARw9zWm_dzVuLQcF8Nd@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Tortugas vs. Threshers Tortugas vs. Threshers

Follow on MiLB First Pitch  https //stza.co/+vMiV-N

Shop  https //stza.co/+vMiV-1m

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Tortugas vs. Threshers
END:VALARM
DTSTART:20180627T143500Z
DTEND:20180627T173500Z
UID:r3CFfARw9zWm_dzVuLQcF8Nd@stanza.co
SUMMARY:Tortugas vs. Threshers
DESCRIPTION:Tortugas vs. Threshers\n\nFollow on MiLB First Pitch: https://stza.co/+vMiV-N\n\nShop: https://stza.co/+vMiV-1m\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144518Z
LAST-MODIFIED:20180213T144518Z
TRANSP:OPAQUE
END:VEVENT
* Tortugas vs. Threshers
<2018-06-28 Thu 18:05-21:05>
:PROPERTIES:
:ID:       8sdUWpq4YQHggj5my66IT2Mh@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Tortugas vs. Threshers Tortugas vs. Threshers

Follow on MiLB First Pitch  https //stza.co/+vMiX-3

Shop  https //stza.co/+vMiX-m

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Tortugas vs. Threshers
END:VALARM
DTSTART:20180628T230500Z
DTEND:20180629T020500Z
UID:8sdUWpq4YQHggj5my66IT2Mh@stanza.co
SUMMARY:Tortugas vs. Threshers
DESCRIPTION:Tortugas vs. Threshers\n\nFollow on MiLB First Pitch: https://stza.co/+vMiX-3\n\nShop: https://stza.co/+vMiX-m\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144518Z
LAST-MODIFIED:20180213T144518Z
TRANSP:OPAQUE
END:VEVENT
* Tortugas @ Fire Frogs
<2018-06-29 Fri 17:31-20:31>
:PROPERTIES:
:ID:       jCVS6oxFQzAl8DrOwRIwIMa0@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Tortugas @ Fire Frogs Tortugas @ Fire Frogs

Buy tickets here  https //stza.co/~xWKF

Follow on MiLB First Pitch  https //stza.co/+xWKF-1C

Shop  https //stza.co/+xWKF-3x

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Tortugas @ Fire Frogs
END:VALARM
DTSTART:20180629T223100Z
DTEND:20180630T013100Z
UID:jCVS6oxFQzAl8DrOwRIwIMa0@stanza.co
SUMMARY:Tortugas @ Fire Frogs
DESCRIPTION:Tortugas @ Fire Frogs\n\nBuy tickets here: https://stza.co/~xWKF\n\nFollow on MiLB First Pitch: https://stza.co/+xWKF-1C\n\nShop: https://stza.co/+xWKF-3x\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144518Z
LAST-MODIFIED:20180213T144518Z
TRANSP:OPAQUE
END:VEVENT
* Tortugas @ Fire Frogs
<2018-06-30 Sat 17:31-20:31>
:PROPERTIES:
:ID:       IcXOs7afn2wDIwu9svmjrTKx@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Tortugas @ Fire Frogs Tortugas @ Fire Frogs

Buy tickets here  https //stza.co/~xWKG

Follow on MiLB First Pitch  https //stza.co/+xWKG-2B

Shop  https //stza.co/+xWKG-2I

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Tortugas @ Fire Frogs
END:VALARM
DTSTART:20180630T223100Z
DTEND:20180701T013100Z
UID:IcXOs7afn2wDIwu9svmjrTKx@stanza.co
SUMMARY:Tortugas @ Fire Frogs
DESCRIPTION:Tortugas @ Fire Frogs\n\nBuy tickets here: https://stza.co/~xWKG\n\nFollow on MiLB First Pitch: https://stza.co/+xWKG-2B\n\nShop: https://stza.co/+xWKG-2I\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144518Z
LAST-MODIFIED:20180213T144518Z
TRANSP:OPAQUE
END:VEVENT
* Tortugas @ Fire Frogs
<2018-07-01 Sun 10:00-13:00>
:PROPERTIES:
:ID:       q3REQ8x7BOHWDU8nlH4uMDsU@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Tortugas @ Fire Frogs Tortugas @ Fire Frogs

Buy tickets here  https //stza.co/~xWKH

Follow on MiLB First Pitch  https //stza.co/+xWKH-2q

Shop  https //stza.co/+xWKH-3S

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Tortugas @ Fire Frogs
END:VALARM
DTSTART:20180701T150000Z
DTEND:20180701T180000Z
UID:q3REQ8x7BOHWDU8nlH4uMDsU@stanza.co
SUMMARY:Tortugas @ Fire Frogs
DESCRIPTION:Tortugas @ Fire Frogs\n\nBuy tickets here: https://stza.co/~xWKH\n\nFollow on MiLB First Pitch: https://stza.co/+xWKH-2q\n\nShop: https://stza.co/+xWKH-3S\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144518Z
LAST-MODIFIED:20180213T144518Z
TRANSP:OPAQUE
END:VEVENT
* Tortugas vs. Mets
<2018-07-02 Mon 18:05-21:05>
:PROPERTIES:
:ID:       lqK0gNZvG9NjcqyZ17yJZM1c@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Tortugas vs. Mets Tortugas vs. Mets

Follow on MiLB First Pitch  https //stza.co/+vMiZ-2m

Shop  https //stza.co/+vMiZ-3E

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Tortugas vs. Mets
END:VALARM
DTSTART:20180702T230500Z
DTEND:20180703T020500Z
UID:lqK0gNZvG9NjcqyZ17yJZM1c@stanza.co
SUMMARY:Tortugas vs. Mets
DESCRIPTION:Tortugas vs. Mets\n\nFollow on MiLB First Pitch: https://stza.co/+vMiZ-2m\n\nShop: https://stza.co/+vMiZ-3E\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144518Z
LAST-MODIFIED:20180213T144518Z
TRANSP:OPAQUE
END:VEVENT
* Tortugas vs. Mets
<2018-07-03 Tue 18:05-21:05>
:PROPERTIES:
:ID:       zYyq5u0M8ykZcEReoKiNAmH9@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Tortugas vs. Mets Tortugas vs. Mets

Follow on MiLB First Pitch  https //stza.co/+vMi$-3n

Shop  https //stza.co/+vMi$-2W

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Tortugas vs. Mets
END:VALARM
DTSTART:20180703T230500Z
DTEND:20180704T020500Z
UID:zYyq5u0M8ykZcEReoKiNAmH9@stanza.co
SUMMARY:Tortugas vs. Mets
DESCRIPTION:Tortugas vs. Mets\n\nFollow on MiLB First Pitch: https://stza.co/+vMi$-3n\n\nShop: https://stza.co/+vMi$-2W\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144518Z
LAST-MODIFIED:20180213T144518Z
TRANSP:OPAQUE
END:VEVENT
* Tortugas @ Cardinals
<2018-07-04 Wed>--<2018-07-03 Tue>
:PROPERTIES:
:ID:       TFS0hfrus-EiIUItZuUc5yjm@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Tortugas @ Cardinals Tortugas @ Cardinals

Buy tickets here  https //stza.co/~vMkn

Follow on MiLB First Pitch  https //stza.co/+vMkn-2u

Shop  https //stza.co/+vMkn-v

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Tortugas @ Cardinals
END:VALARM
DTSTART;VALUE=DATE:20180704
DTEND;VALUE=DATE:20180704
UID:TFS0hfrus-EiIUItZuUc5yjm@stanza.co
SUMMARY:Tortugas @ Cardinals
DESCRIPTION:Tortugas @ Cardinals\n\nBuy tickets here: https://stza.co/~vMkn\n\nFollow on MiLB First Pitch: https://stza.co/+vMkn-2u\n\nShop: https://stza.co/+vMkn-v\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144518Z
LAST-MODIFIED:20180213T144518Z
TRANSP:OPAQUE
END:VEVENT
* Tortugas @ Cardinals
<2018-07-05 Thu>--<2018-07-04 Wed>
:PROPERTIES:
:ID:       HGASab-9AdgoNzQU2-tXZ_Dh@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Tortugas @ Cardinals Tortugas @ Cardinals

Buy tickets here  https //stza.co/~vMko

Follow on MiLB First Pitch  https //stza.co/+vMko-1V

Shop  https //stza.co/+vMko-1G

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Tortugas @ Cardinals
END:VALARM
DTSTART;VALUE=DATE:20180705
DTEND;VALUE=DATE:20180705
UID:HGASab-9AdgoNzQU2-tXZ_Dh@stanza.co
SUMMARY:Tortugas @ Cardinals
DESCRIPTION:Tortugas @ Cardinals\n\nBuy tickets here: https://stza.co/~vMko\n\nFollow on MiLB First Pitch: https://stza.co/+vMko-1V\n\nShop: https://stza.co/+vMko-1G\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144518Z
LAST-MODIFIED:20180213T144518Z
TRANSP:OPAQUE
END:VEVENT
* Tortugas vs. Hammerheads
<2018-07-06 Fri 18:05-21:05>
:PROPERTIES:
:ID:       sbFC-3ZpXaVPU__PZEqGRSVX@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Tortugas vs. Hammerheads Tortugas vs. Hammerheads

Follow on MiLB First Pitch  https //stza.co/+vMj0-3K

Shop  https //stza.co/+vMj0-5

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Tortugas vs. Hammerheads
END:VALARM
DTSTART:20180706T230500Z
DTEND:20180707T020500Z
UID:sbFC-3ZpXaVPU__PZEqGRSVX@stanza.co
SUMMARY:Tortugas vs. Hammerheads
DESCRIPTION:Tortugas vs. Hammerheads\n\nFollow on MiLB First Pitch: https://stza.co/+vMj0-3K\n\nShop: https://stza.co/+vMj0-5\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144518Z
LAST-MODIFIED:20180213T144518Z
TRANSP:OPAQUE
END:VEVENT
* Tortugas vs. Hammerheads
<2018-07-07 Sat 11:35-14:35>
:PROPERTIES:
:ID:       w_yyp9hcnJp222QLpLIgcsK_@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Tortugas vs. Hammerheads Tortugas vs. Hammerheads

Follow on MiLB First Pitch  https //stza.co/+xBdc-3u

Shop  https //stza.co/+xBdc-2U

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Tortugas vs. Hammerheads
END:VALARM
DTSTART:20180707T163500Z
DTEND:20180707T193500Z
UID:w_yyp9hcnJp222QLpLIgcsK_@stanza.co
SUMMARY:Tortugas vs. Hammerheads
DESCRIPTION:Tortugas vs. Hammerheads\n\nFollow on MiLB First Pitch: https://stza.co/+xBdc-3u\n\nShop: https://stza.co/+xBdc-2U\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144518Z
LAST-MODIFIED:20180213T144518Z
TRANSP:OPAQUE
END:VEVENT
* Tortugas vs. Hammerheads
<2018-07-08 Sun 16:35-19:35>
:PROPERTIES:
:ID:       loWj1ezhN1zydXKQoC2bE4_O@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Tortugas vs. Hammerheads Tortugas vs. Hammerheads

Follow on MiLB First Pitch  https //stza.co/+vMj4-3O

Shop  https //stza.co/+vMj4-1T

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Tortugas vs. Hammerheads
END:VALARM
DTSTART:20180708T213500Z
DTEND:20180709T003500Z
UID:loWj1ezhN1zydXKQoC2bE4_O@stanza.co
SUMMARY:Tortugas vs. Hammerheads
DESCRIPTION:Tortugas vs. Hammerheads\n\nFollow on MiLB First Pitch: https://stza.co/+vMj4-3O\n\nShop: https://stza.co/+vMj4-1T\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144518Z
LAST-MODIFIED:20180213T144518Z
TRANSP:OPAQUE
END:VEVENT
* Tortugas @ Fire Frogs
<2018-07-09 Mon 17:31-20:31>
:PROPERTIES:
:ID:       TXWmIpTmSUSNEUpJAyHBNbCI@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Tortugas @ Fire Frogs Tortugas @ Fire Frogs

Buy tickets here  https //stza.co/~xWKI

Follow on MiLB First Pitch  https //stza.co/+xWKI-1A

Shop  https //stza.co/+xWKI-1S

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Tortugas @ Fire Frogs
END:VALARM
DTSTART:20180709T223100Z
DTEND:20180710T013100Z
UID:TXWmIpTmSUSNEUpJAyHBNbCI@stanza.co
SUMMARY:Tortugas @ Fire Frogs
DESCRIPTION:Tortugas @ Fire Frogs\n\nBuy tickets here: https://stza.co/~xWKI\n\nFollow on MiLB First Pitch: https://stza.co/+xWKI-1A\n\nShop: https://stza.co/+xWKI-1S\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144518Z
LAST-MODIFIED:20180213T144518Z
TRANSP:OPAQUE
END:VEVENT
* Tortugas @ Fire Frogs
<2018-07-10 Tue 17:31-20:31>
:PROPERTIES:
:ID:       AaOeHDdVi39mYCCOPWx8kdFv@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Tortugas @ Fire Frogs Tortugas @ Fire Frogs

Buy tickets here  https //stza.co/~xWKJ

Follow on MiLB First Pitch  https //stza.co/+xWKJ-2U

Shop  https //stza.co/+xWKJ-26

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Tortugas @ Fire Frogs
END:VALARM
DTSTART:20180710T223100Z
DTEND:20180711T013100Z
UID:AaOeHDdVi39mYCCOPWx8kdFv@stanza.co
SUMMARY:Tortugas @ Fire Frogs
DESCRIPTION:Tortugas @ Fire Frogs\n\nBuy tickets here: https://stza.co/~xWKJ\n\nFollow on MiLB First Pitch: https://stza.co/+xWKJ-2U\n\nShop: https://stza.co/+xWKJ-26\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144518Z
LAST-MODIFIED:20180213T144518Z
TRANSP:OPAQUE
END:VEVENT
* Tortugas @ Fire Frogs
<2018-07-11 Wed 17:31-20:31>
:PROPERTIES:
:ID:       vpZ-fco9SAfY2er0CXtU-gBG@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Tortugas @ Fire Frogs Tortugas @ Fire Frogs

Buy tickets here  https //stza.co/~xWKK

Follow on MiLB First Pitch  https //stza.co/+xWKK-3T

Shop  https //stza.co/+xWKK-3M

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Tortugas @ Fire Frogs
END:VALARM
DTSTART:20180711T223100Z
DTEND:20180712T013100Z
UID:vpZ-fco9SAfY2er0CXtU-gBG@stanza.co
SUMMARY:Tortugas @ Fire Frogs
DESCRIPTION:Tortugas @ Fire Frogs\n\nBuy tickets here: https://stza.co/~xWKK\n\nFollow on MiLB First Pitch: https://stza.co/+xWKK-3T\n\nShop: https://stza.co/+xWKK-3M\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144518Z
LAST-MODIFIED:20180213T144518Z
TRANSP:OPAQUE
END:VEVENT
* Tortugas @ Fire Frogs
<2018-07-12 Thu 17:31-20:31>
:PROPERTIES:
:ID:       fXdgh-QfTYNYQRy9p8P0-YEP@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Tortugas @ Fire Frogs Tortugas @ Fire Frogs

Buy tickets here  https //stza.co/~xWKL

Follow on MiLB First Pitch  https //stza.co/+xWKL-3z

Shop  https //stza.co/+xWKL-2x

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Tortugas @ Fire Frogs
END:VALARM
DTSTART:20180712T223100Z
DTEND:20180713T013100Z
UID:fXdgh-QfTYNYQRy9p8P0-YEP@stanza.co
SUMMARY:Tortugas @ Fire Frogs
DESCRIPTION:Tortugas @ Fire Frogs\n\nBuy tickets here: https://stza.co/~xWKL\n\nFollow on MiLB First Pitch: https://stza.co/+xWKL-3z\n\nShop: https://stza.co/+xWKL-2x\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144518Z
LAST-MODIFIED:20180213T144518Z
TRANSP:OPAQUE
END:VEVENT
* Tortugas vs. Marauders
<2018-07-13 Fri 18:05-21:05>
:PROPERTIES:
:ID:       IakBB8BqyKbCEYWYCXbdTd9i@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Tortugas vs. Marauders Tortugas vs. Marauders

Follow on MiLB First Pitch  https //stza.co/+vMj7-3i

Shop  https //stza.co/+vMj7-3

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Tortugas vs. Marauders
END:VALARM
DTSTART:20180713T230500Z
DTEND:20180714T020500Z
UID:IakBB8BqyKbCEYWYCXbdTd9i@stanza.co
SUMMARY:Tortugas vs. Marauders
DESCRIPTION:Tortugas vs. Marauders\n\nFollow on MiLB First Pitch: https://stza.co/+vMj7-3i\n\nShop: https://stza.co/+vMj7-3\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144518Z
LAST-MODIFIED:20180213T144518Z
TRANSP:OPAQUE
END:VEVENT
* Tortugas vs. Marauders
<2018-07-14 Sat 18:05-21:05>
:PROPERTIES:
:ID:       dFoyDlqYv_PcOPzRvSuGSSCC@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Tortugas vs. Marauders Tortugas vs. Marauders

Follow on MiLB First Pitch  https //stza.co/+vMj8-1Z

Shop  https //stza.co/+vMj8-3n

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Tortugas vs. Marauders
END:VALARM
DTSTART:20180714T230500Z
DTEND:20180715T020500Z
UID:dFoyDlqYv_PcOPzRvSuGSSCC@stanza.co
SUMMARY:Tortugas vs. Marauders
DESCRIPTION:Tortugas vs. Marauders\n\nFollow on MiLB First Pitch: https://stza.co/+vMj8-1Z\n\nShop: https://stza.co/+vMj8-3n\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144518Z
LAST-MODIFIED:20180213T144518Z
TRANSP:OPAQUE
END:VEVENT
* Tortugas vs. Marauders
<2018-07-15 Sun 16:35-19:35>
:PROPERTIES:
:ID:       _xl3tkj1FJfS04CiEXsJn_Ki@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Tortugas vs. Marauders Tortugas vs. Marauders

Follow on MiLB First Pitch  https //stza.co/+vMja-1F

Shop  https //stza.co/+vMja-S

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Tortugas vs. Marauders
END:VALARM
DTSTART:20180715T213500Z
DTEND:20180716T003500Z
UID:_xl3tkj1FJfS04CiEXsJn_Ki@stanza.co
SUMMARY:Tortugas vs. Marauders
DESCRIPTION:Tortugas vs. Marauders\n\nFollow on MiLB First Pitch: https://stza.co/+vMja-1F\n\nShop: https://stza.co/+vMja-S\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144518Z
LAST-MODIFIED:20180213T144518Z
TRANSP:OPAQUE
END:VEVENT
* Tortugas @ Threshers
<2018-07-16 Mon 18:00-21:00>
:PROPERTIES:
:ID:       IXcfl0hozv8eHmJgmgE_kyWj@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Tortugas @ Threshers Tortugas @ Threshers

Follow on MiLB First Pitch  https //stza.co/+xBcJ-3k

Shop  https //stza.co/+xBcJ-1z

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Tortugas @ Threshers
END:VALARM
DTSTART:20180716T230000Z
DTEND:20180717T020000Z
UID:IXcfl0hozv8eHmJgmgE_kyWj@stanza.co
SUMMARY:Tortugas @ Threshers
DESCRIPTION:Tortugas @ Threshers\n\nFollow on MiLB First Pitch: https://stza.co/+xBcJ-3k\n\nShop: https://stza.co/+xBcJ-1z\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144518Z
LAST-MODIFIED:20180213T144518Z
TRANSP:OPAQUE
END:VEVENT
* Tortugas @ Threshers
<2018-07-17 Tue 18:00-21:00>
:PROPERTIES:
:ID:       A58iZCMnPNmL82Er0Su2eyAQ@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Tortugas @ Threshers Tortugas @ Threshers

Follow on MiLB First Pitch  https //stza.co/+xBcM-2C

Shop  https //stza.co/+xBcM-1M

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Tortugas @ Threshers
END:VALARM
DTSTART:20180717T230000Z
DTEND:20180718T020000Z
UID:A58iZCMnPNmL82Er0Su2eyAQ@stanza.co
SUMMARY:Tortugas @ Threshers
DESCRIPTION:Tortugas @ Threshers\n\nFollow on MiLB First Pitch: https://stza.co/+xBcM-2C\n\nShop: https://stza.co/+xBcM-1M\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144518Z
LAST-MODIFIED:20180213T144518Z
TRANSP:OPAQUE
END:VEVENT
* Tortugas @ Threshers
<2018-07-18 Wed 18:00-21:00>
:PROPERTIES:
:ID:       8ojp4ibebd8E6U2H6huNSioD@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Tortugas @ Threshers Tortugas @ Threshers

Follow on MiLB First Pitch  https //stza.co/+xBcP-1F

Shop  https //stza.co/+xBcP-38

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Tortugas @ Threshers
END:VALARM
DTSTART:20180718T230000Z
DTEND:20180719T020000Z
UID:8ojp4ibebd8E6U2H6huNSioD@stanza.co
SUMMARY:Tortugas @ Threshers
DESCRIPTION:Tortugas @ Threshers\n\nFollow on MiLB First Pitch: https://stza.co/+xBcP-1F\n\nShop: https://stza.co/+xBcP-38\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144518Z
LAST-MODIFIED:20180213T144518Z
TRANSP:OPAQUE
END:VEVENT
* Tortugas @ Marauders
<2018-07-19 Thu 17:30-20:30>
:PROPERTIES:
:ID:       3T-NfABVSAhlGvgZSfr8AzGB@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Tortugas @ Marauders Tortugas @ Marauders

Follow on MiLB First Pitch  https //stza.co/+vMhr-3K

Shop  https //stza.co/+vMhr-A

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Tortugas @ Marauders
END:VALARM
DTSTART:20180719T223000Z
DTEND:20180720T013000Z
UID:3T-NfABVSAhlGvgZSfr8AzGB@stanza.co
SUMMARY:Tortugas @ Marauders
DESCRIPTION:Tortugas @ Marauders\n\nFollow on MiLB First Pitch: https://stza.co/+vMhr-3K\n\nShop: https://stza.co/+vMhr-A\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144518Z
LAST-MODIFIED:20180213T144518Z
TRANSP:OPAQUE
END:VEVENT
* Tortugas @ Marauders
<2018-07-20 Fri 17:30-20:30>
:PROPERTIES:
:ID:       8zcFizHVR6Qh6b4oPV5WxkwH@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Tortugas @ Marauders Tortugas @ Marauders

Follow on MiLB First Pitch  https //stza.co/+vMhs-1B

Shop  https //stza.co/+vMhs-2_

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Tortugas @ Marauders
END:VALARM
DTSTART:20180720T223000Z
DTEND:20180721T013000Z
UID:8zcFizHVR6Qh6b4oPV5WxkwH@stanza.co
SUMMARY:Tortugas @ Marauders
DESCRIPTION:Tortugas @ Marauders\n\nFollow on MiLB First Pitch: https://stza.co/+vMhs-1B\n\nShop: https://stza.co/+vMhs-2_\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144518Z
LAST-MODIFIED:20180213T144518Z
TRANSP:OPAQUE
END:VEVENT
* Tortugas @ Marauders
<2018-07-21 Sat 17:30-20:30>
:PROPERTIES:
:ID:       QCuEpkHGVpv_pOtY_Tc9qTC0@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Tortugas @ Marauders Tortugas @ Marauders

Follow on MiLB First Pitch  https //stza.co/+vMht-3Z

Shop  https //stza.co/+vMht-9

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Tortugas @ Marauders
END:VALARM
DTSTART:20180721T223000Z
DTEND:20180722T013000Z
UID:QCuEpkHGVpv_pOtY_Tc9qTC0@stanza.co
SUMMARY:Tortugas @ Marauders
DESCRIPTION:Tortugas @ Marauders\n\nFollow on MiLB First Pitch: https://stza.co/+vMht-3Z\n\nShop: https://stza.co/+vMht-9\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144518Z
LAST-MODIFIED:20180213T144518Z
TRANSP:OPAQUE
END:VEVENT
* Tortugas vs. Cardinals
<2018-07-23 Mon 18:05-21:05>
:PROPERTIES:
:ID:       HauUlSd_q07fGuookTLR0913@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Tortugas vs. Cardinals Tortugas vs. Cardinals

Follow on MiLB First Pitch  https //stza.co/+vMjd-m

Shop  https //stza.co/+vMjd-1M

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Tortugas vs. Cardinals
END:VALARM
DTSTART:20180723T230500Z
DTEND:20180724T020500Z
UID:HauUlSd_q07fGuookTLR0913@stanza.co
SUMMARY:Tortugas vs. Cardinals
DESCRIPTION:Tortugas vs. Cardinals\n\nFollow on MiLB First Pitch: https://stza.co/+vMjd-m\n\nShop: https://stza.co/+vMjd-1M\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144518Z
LAST-MODIFIED:20180213T144518Z
TRANSP:OPAQUE
END:VEVENT
* Tortugas vs. Cardinals
<2018-07-24 Tue 18:05-21:05>
:PROPERTIES:
:ID:       GpCuZKk-PHr1iG0rGTugXe1O@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Tortugas vs. Cardinals Tortugas vs. Cardinals

Follow on MiLB First Pitch  https //stza.co/+vMje-x

Shop  https //stza.co/+vMje-39

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Tortugas vs. Cardinals
END:VALARM
DTSTART:20180724T230500Z
DTEND:20180725T020500Z
UID:GpCuZKk-PHr1iG0rGTugXe1O@stanza.co
SUMMARY:Tortugas vs. Cardinals
DESCRIPTION:Tortugas vs. Cardinals\n\nFollow on MiLB First Pitch: https://stza.co/+vMje-x\n\nShop: https://stza.co/+vMje-39\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144518Z
LAST-MODIFIED:20180213T144518Z
TRANSP:OPAQUE
END:VEVENT
* Tortugas vs. Cardinals
<2018-07-25 Wed 18:05-21:05>
:PROPERTIES:
:ID:       F6lNI1AqQuR5XlvBhIsgx2rd@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Tortugas vs. Cardinals Tortugas vs. Cardinals

Follow on MiLB First Pitch  https //stza.co/+vMjg-T

Shop  https //stza.co/+vMjg-3D

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Tortugas vs. Cardinals
END:VALARM
DTSTART:20180725T230500Z
DTEND:20180726T020500Z
UID:F6lNI1AqQuR5XlvBhIsgx2rd@stanza.co
SUMMARY:Tortugas vs. Cardinals
DESCRIPTION:Tortugas vs. Cardinals\n\nFollow on MiLB First Pitch: https://stza.co/+vMjg-T\n\nShop: https://stza.co/+vMjg-3D\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144518Z
LAST-MODIFIED:20180213T144518Z
TRANSP:OPAQUE
END:VEVENT
* Tortugas vs. Miracle
<2018-07-26 Thu 18:05-21:05>
:PROPERTIES:
:ID:       tgyTGGp6f1j8NnQjg-Fjd4JJ@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Tortugas vs. Miracle Tortugas vs. Miracle

Follow on MiLB First Pitch  https //stza.co/+vMji-2s

Shop  https //stza.co/+vMji-B

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Tortugas vs. Miracle
END:VALARM
DTSTART:20180726T230500Z
DTEND:20180727T020500Z
UID:tgyTGGp6f1j8NnQjg-Fjd4JJ@stanza.co
SUMMARY:Tortugas vs. Miracle
DESCRIPTION:Tortugas vs. Miracle\n\nFollow on MiLB First Pitch: https://stza.co/+vMji-2s\n\nShop: https://stza.co/+vMji-B\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144518Z
LAST-MODIFIED:20180213T144518Z
TRANSP:OPAQUE
END:VEVENT
* Tortugas vs. Miracle
<2018-07-27 Fri 18:05-21:05>
:PROPERTIES:
:ID:       vdpSQR8Og2PgbBw1Bm4p3cgb@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Tortugas vs. Miracle Tortugas vs. Miracle

Follow on MiLB First Pitch  https //stza.co/+vMjk-3F

Shop  https //stza.co/+vMjk-3Y

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Tortugas vs. Miracle
END:VALARM
DTSTART:20180727T230500Z
DTEND:20180728T020500Z
UID:vdpSQR8Og2PgbBw1Bm4p3cgb@stanza.co
SUMMARY:Tortugas vs. Miracle
DESCRIPTION:Tortugas vs. Miracle\n\nFollow on MiLB First Pitch: https://stza.co/+vMjk-3F\n\nShop: https://stza.co/+vMjk-3Y\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144518Z
LAST-MODIFIED:20180213T144518Z
TRANSP:OPAQUE
END:VEVENT
* Tortugas vs. Miracle
<2018-07-28 Sat 18:05-21:05>
:PROPERTIES:
:ID:       _CO0BRk87MLsaHi4LBKgb_G-@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Tortugas vs. Miracle Tortugas vs. Miracle

Follow on MiLB First Pitch  https //stza.co/+vMjn-1D

Shop  https //stza.co/+vMjn-3n

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Tortugas vs. Miracle
END:VALARM
DTSTART:20180728T230500Z
DTEND:20180729T020500Z
UID:_CO0BRk87MLsaHi4LBKgb_G-@stanza.co
SUMMARY:Tortugas vs. Miracle
DESCRIPTION:Tortugas vs. Miracle\n\nFollow on MiLB First Pitch: https://stza.co/+vMjn-1D\n\nShop: https://stza.co/+vMjn-3n\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144518Z
LAST-MODIFIED:20180213T144518Z
TRANSP:OPAQUE
END:VEVENT
* Tortugas vs. Miracle
<2018-07-29 Sun 16:35-19:35>
:PROPERTIES:
:ID:       FamGx-6LMMp-iZF-ULDgPv-C@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Tortugas vs. Miracle Tortugas vs. Miracle

Follow on MiLB First Pitch  https //stza.co/+vMjo-1N

Shop  https //stza.co/+vMjo-1O

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Tortugas vs. Miracle
END:VALARM
DTSTART:20180729T213500Z
DTEND:20180730T003500Z
UID:FamGx-6LMMp-iZF-ULDgPv-C@stanza.co
SUMMARY:Tortugas vs. Miracle
DESCRIPTION:Tortugas vs. Miracle\n\nFollow on MiLB First Pitch: https://stza.co/+vMjo-1N\n\nShop: https://stza.co/+vMjo-1O\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144518Z
LAST-MODIFIED:20180213T144518Z
TRANSP:OPAQUE
END:VEVENT
* Tortugas @ Cardinals
<2018-07-31 Tue>--<2018-07-30 Mon>
:PROPERTIES:
:ID:       MsjZd5bx6oyXPeTWq8i8qolT@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Tortugas @ Cardinals Tortugas @ Cardinals

Buy tickets here  https //stza.co/~vMkp

Follow on MiLB First Pitch  https //stza.co/+vMkp-2c

Shop  https //stza.co/+vMkp-1u

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Tortugas @ Cardinals
END:VALARM
DTSTART;VALUE=DATE:20180731
DTEND;VALUE=DATE:20180731
UID:MsjZd5bx6oyXPeTWq8i8qolT@stanza.co
SUMMARY:Tortugas @ Cardinals
DESCRIPTION:Tortugas @ Cardinals\n\nBuy tickets here: https://stza.co/~vMkp\n\nFollow on MiLB First Pitch: https://stza.co/+vMkp-2c\n\nShop: https://stza.co/+vMkp-1u\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144518Z
LAST-MODIFIED:20180213T144518Z
TRANSP:OPAQUE
END:VEVENT
* Tortugas @ Cardinals
<2018-08-01 Wed>--<2018-07-31 Tue>
:PROPERTIES:
:ID:       dbixL8QN_sdcqjIx-UMHli61@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Tortugas @ Cardinals Tortugas @ Cardinals

Buy tickets here  https //stza.co/~vMkq

Follow on MiLB First Pitch  https //stza.co/+vMkq-v

Shop  https //stza.co/+vMkq-2c

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Tortugas @ Cardinals
END:VALARM
DTSTART;VALUE=DATE:20180801
DTEND;VALUE=DATE:20180801
UID:dbixL8QN_sdcqjIx-UMHli61@stanza.co
SUMMARY:Tortugas @ Cardinals
DESCRIPTION:Tortugas @ Cardinals\n\nBuy tickets here: https://stza.co/~vMkq\n\nFollow on MiLB First Pitch: https://stza.co/+vMkq-v\n\nShop: https://stza.co/+vMkq-2c\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144518Z
LAST-MODIFIED:20180213T144518Z
TRANSP:OPAQUE
END:VEVENT
* Tortugas @ Cardinals
<2018-08-02 Thu>--<2018-08-01 Wed>
:PROPERTIES:
:ID:       mKsJBbBMvNIKmKDvhQu-LG5C@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Tortugas @ Cardinals Tortugas @ Cardinals

Buy tickets here  https //stza.co/~vMkr

Follow on MiLB First Pitch  https //stza.co/+vMkr-T

Shop  https //stza.co/+vMkr-1V

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Tortugas @ Cardinals
END:VALARM
DTSTART;VALUE=DATE:20180802
DTEND;VALUE=DATE:20180802
UID:mKsJBbBMvNIKmKDvhQu-LG5C@stanza.co
SUMMARY:Tortugas @ Cardinals
DESCRIPTION:Tortugas @ Cardinals\n\nBuy tickets here: https://stza.co/~vMkr\n\nFollow on MiLB First Pitch: https://stza.co/+vMkr-T\n\nShop: https://stza.co/+vMkr-1V\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144518Z
LAST-MODIFIED:20180213T144518Z
TRANSP:OPAQUE
END:VEVENT
* Tortugas @ Mets
<2018-08-03 Fri 17:30-20:30>
:PROPERTIES:
:ID:       51USdQ-NKS9vB4dKgZPu5f_j@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Tortugas @ Mets Tortugas @ Mets

Follow on MiLB First Pitch  https //stza.co/+vMkw-19

Shop  https //stza.co/+vMkw-w

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Tortugas @ Mets
END:VALARM
DTSTART:20180803T223000Z
DTEND:20180804T013000Z
UID:51USdQ-NKS9vB4dKgZPu5f_j@stanza.co
SUMMARY:Tortugas @ Mets
DESCRIPTION:Tortugas @ Mets\n\nFollow on MiLB First Pitch: https://stza.co/+vMkw-19\n\nShop: https://stza.co/+vMkw-w\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144518Z
LAST-MODIFIED:20180213T144518Z
TRANSP:OPAQUE
END:VEVENT
* Tortugas @ Mets
<2018-08-04 Sat 17:30-20:30>
:PROPERTIES:
:ID:       NP0QWneWn17EBOy7lY0n1V7z@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Tortugas @ Mets Tortugas @ Mets

Follow on MiLB First Pitch  https //stza.co/+vMkx-1H

Shop  https //stza.co/+vMkx-3d

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Tortugas @ Mets
END:VALARM
DTSTART:20180804T223000Z
DTEND:20180805T013000Z
UID:NP0QWneWn17EBOy7lY0n1V7z@stanza.co
SUMMARY:Tortugas @ Mets
DESCRIPTION:Tortugas @ Mets\n\nFollow on MiLB First Pitch: https://stza.co/+vMkx-1H\n\nShop: https://stza.co/+vMkx-3d\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144518Z
LAST-MODIFIED:20180213T144518Z
TRANSP:OPAQUE
END:VEVENT
* Tortugas @ Mets
<2018-08-05 Sun 11:00-14:00>
:PROPERTIES:
:ID:       Rz2i1wnt7o555mmqpiumbIlE@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Tortugas @ Mets Tortugas @ Mets

Follow on MiLB First Pitch  https //stza.co/+vMky-2G

Shop  https //stza.co/+vMky-x

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Tortugas @ Mets
END:VALARM
DTSTART:20180805T160000Z
DTEND:20180805T190000Z
UID:Rz2i1wnt7o555mmqpiumbIlE@stanza.co
SUMMARY:Tortugas @ Mets
DESCRIPTION:Tortugas @ Mets\n\nFollow on MiLB First Pitch: https://stza.co/+vMky-2G\n\nShop: https://stza.co/+vMky-x\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144518Z
LAST-MODIFIED:20180213T144518Z
TRANSP:OPAQUE
END:VEVENT
* Tortugas vs. Blue Jays
<2018-08-06 Mon 18:05-21:05>
:PROPERTIES:
:ID:       pFB60kXOUbREDQruhC0Rwrs-@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Tortugas vs. Blue Jays Tortugas vs. Blue Jays

Follow on MiLB First Pitch  https //stza.co/+vMjr-34

Shop  https //stza.co/+vMjr-3j

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Tortugas vs. Blue Jays
END:VALARM
DTSTART:20180806T230500Z
DTEND:20180807T020500Z
UID:pFB60kXOUbREDQruhC0Rwrs-@stanza.co
SUMMARY:Tortugas vs. Blue Jays
DESCRIPTION:Tortugas vs. Blue Jays\n\nFollow on MiLB First Pitch: https://stza.co/+vMjr-34\n\nShop: https://stza.co/+vMjr-3j\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144518Z
LAST-MODIFIED:20180213T144518Z
TRANSP:OPAQUE
END:VEVENT
* Tortugas vs. Blue Jays
<2018-08-07 Tue 18:05-21:05>
:PROPERTIES:
:ID:       psxao74vS8FEG1H3rwpdczQ3@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Tortugas vs. Blue Jays Tortugas vs. Blue Jays

Follow on MiLB First Pitch  https //stza.co/+vMjs-m

Shop  https //stza.co/+vMjs-3o

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Tortugas vs. Blue Jays
END:VALARM
DTSTART:20180807T230500Z
DTEND:20180808T020500Z
UID:psxao74vS8FEG1H3rwpdczQ3@stanza.co
SUMMARY:Tortugas vs. Blue Jays
DESCRIPTION:Tortugas vs. Blue Jays\n\nFollow on MiLB First Pitch: https://stza.co/+vMjs-m\n\nShop: https://stza.co/+vMjs-3o\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144518Z
LAST-MODIFIED:20180213T144518Z
TRANSP:OPAQUE
END:VEVENT
* Tortugas vs. Blue Jays
<2018-08-08 Wed 18:05-21:05>
:PROPERTIES:
:ID:       lskTMRmZOgnYvEh7AQBWlk5J@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Tortugas vs. Blue Jays Tortugas vs. Blue Jays

Follow on MiLB First Pitch  https //stza.co/+vMjv-o

Shop  https //stza.co/+vMjv-P

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Tortugas vs. Blue Jays
END:VALARM
DTSTART:20180808T230500Z
DTEND:20180809T020500Z
UID:lskTMRmZOgnYvEh7AQBWlk5J@stanza.co
SUMMARY:Tortugas vs. Blue Jays
DESCRIPTION:Tortugas vs. Blue Jays\n\nFollow on MiLB First Pitch: https://stza.co/+vMjv-o\n\nShop: https://stza.co/+vMjv-P\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144518Z
LAST-MODIFIED:20180213T144518Z
TRANSP:OPAQUE
END:VEVENT
* Tortugas vs. Hammerheads
<2018-08-09 Thu 18:05-21:05>
:PROPERTIES:
:ID:       0JriFEDybXq57CwrvObJgQ_n@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Tortugas vs. Hammerheads Tortugas vs. Hammerheads

Follow on MiLB First Pitch  https //stza.co/+vMjw-19

Shop  https //stza.co/+vMjw-3H

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Tortugas vs. Hammerheads
END:VALARM
DTSTART:20180809T230500Z
DTEND:20180810T020500Z
UID:0JriFEDybXq57CwrvObJgQ_n@stanza.co
SUMMARY:Tortugas vs. Hammerheads
DESCRIPTION:Tortugas vs. Hammerheads\n\nFollow on MiLB First Pitch: https://stza.co/+vMjw-19\n\nShop: https://stza.co/+vMjw-3H\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144518Z
LAST-MODIFIED:20180213T144518Z
TRANSP:OPAQUE
END:VEVENT
* Tortugas vs. Hammerheads
<2018-08-10 Fri 18:05-21:05>
:PROPERTIES:
:ID:       Uo93_pF9R2nOIxSu9Fkojyvz@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Tortugas vs. Hammerheads Tortugas vs. Hammerheads

Follow on MiLB First Pitch  https //stza.co/+vMjz-2C

Shop  https //stza.co/+vMjz-25

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Tortugas vs. Hammerheads
END:VALARM
DTSTART:20180810T230500Z
DTEND:20180811T020500Z
UID:Uo93_pF9R2nOIxSu9Fkojyvz@stanza.co
SUMMARY:Tortugas vs. Hammerheads
DESCRIPTION:Tortugas vs. Hammerheads\n\nFollow on MiLB First Pitch: https://stza.co/+vMjz-2C\n\nShop: https://stza.co/+vMjz-25\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144518Z
LAST-MODIFIED:20180213T144518Z
TRANSP:OPAQUE
END:VEVENT
* Tortugas vs. Hammerheads
<2018-08-11 Sat 18:05-21:05>
:PROPERTIES:
:ID:       17-gxtEigEQPoHK76P-sws3o@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Tortugas vs. Hammerheads Tortugas vs. Hammerheads

Follow on MiLB First Pitch  https //stza.co/+vMjB-3s

Shop  https //stza.co/+vMjB-3o

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Tortugas vs. Hammerheads
END:VALARM
DTSTART:20180811T230500Z
DTEND:20180812T020500Z
UID:17-gxtEigEQPoHK76P-sws3o@stanza.co
SUMMARY:Tortugas vs. Hammerheads
DESCRIPTION:Tortugas vs. Hammerheads\n\nFollow on MiLB First Pitch: https://stza.co/+vMjB-3s\n\nShop: https://stza.co/+vMjB-3o\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144518Z
LAST-MODIFIED:20180213T144518Z
TRANSP:OPAQUE
END:VEVENT
* Tortugas vs. Hammerheads
<2018-08-12 Sun 16:35-19:35>
:PROPERTIES:
:ID:       ERE_rf5AMPLni271Q-09Ospl@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Tortugas vs. Hammerheads Tortugas vs. Hammerheads

Follow on MiLB First Pitch  https //stza.co/+vMjD-P

Shop  https //stza.co/+vMjD-3f

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Tortugas vs. Hammerheads
END:VALARM
DTSTART:20180812T213500Z
DTEND:20180813T003500Z
UID:ERE_rf5AMPLni271Q-09Ospl@stanza.co
SUMMARY:Tortugas vs. Hammerheads
DESCRIPTION:Tortugas vs. Hammerheads\n\nFollow on MiLB First Pitch: https://stza.co/+vMjD-P\n\nShop: https://stza.co/+vMjD-3f\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144518Z
LAST-MODIFIED:20180213T144518Z
TRANSP:OPAQUE
END:VEVENT
* Tortugas @ Flying Tigers
<2018-08-13 Mon 17:30-20:30>
:PROPERTIES:
:ID:       67y5lcUj2c2of-GEpgp3w6tu@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Tortugas @ Flying Tigers Tortugas @ Flying Tigers

Follow on MiLB First Pitch  https //stza.co/+wKMo-13

Shop  https //stza.co/+wKMo-2Q

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Tortugas @ Flying Tigers
END:VALARM
DTSTART:20180813T223000Z
DTEND:20180814T013000Z
UID:67y5lcUj2c2of-GEpgp3w6tu@stanza.co
SUMMARY:Tortugas @ Flying Tigers
DESCRIPTION:Tortugas @ Flying Tigers\n\nFollow on MiLB First Pitch: https://stza.co/+wKMo-13\n\nShop: https://stza.co/+wKMo-2Q\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144518Z
LAST-MODIFIED:20180213T144518Z
TRANSP:OPAQUE
END:VEVENT
* Tortugas @ Flying Tigers
<2018-08-14 Tue 17:30-20:30>
:PROPERTIES:
:ID:       1379Mg0vEzEhDydrJaTKC5q6@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Tortugas @ Flying Tigers Tortugas @ Flying Tigers

Follow on MiLB First Pitch  https //stza.co/+wKMp-u

Shop  https //stza.co/+wKMp-R

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Tortugas @ Flying Tigers
END:VALARM
DTSTART:20180814T223000Z
DTEND:20180815T013000Z
UID:1379Mg0vEzEhDydrJaTKC5q6@stanza.co
SUMMARY:Tortugas @ Flying Tigers
DESCRIPTION:Tortugas @ Flying Tigers\n\nFollow on MiLB First Pitch: https://stza.co/+wKMp-u\n\nShop: https://stza.co/+wKMp-R\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144518Z
LAST-MODIFIED:20180213T144518Z
TRANSP:OPAQUE
END:VEVENT
* Tortugas @ Flying Tigers
<2018-08-15 Wed 17:30-20:30>
:PROPERTIES:
:ID:       RHbCExLzWd7fH088yEG5q7ir@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Tortugas @ Flying Tigers Tortugas @ Flying Tigers

Follow on MiLB First Pitch  https //stza.co/+wKMq-3I

Shop  https //stza.co/+wKMq-1

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Tortugas @ Flying Tigers
END:VALARM
DTSTART:20180815T223000Z
DTEND:20180816T013000Z
UID:RHbCExLzWd7fH088yEG5q7ir@stanza.co
SUMMARY:Tortugas @ Flying Tigers
DESCRIPTION:Tortugas @ Flying Tigers\n\nFollow on MiLB First Pitch: https://stza.co/+wKMq-3I\n\nShop: https://stza.co/+wKMq-1\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144518Z
LAST-MODIFIED:20180213T144518Z
TRANSP:OPAQUE
END:VEVENT
* Tortugas @ Flying Tigers
<2018-08-16 Thu 17:30-20:30>
:PROPERTIES:
:ID:       IS0eh2yiQAS1Y3hDtKzifsyh@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Tortugas @ Flying Tigers Tortugas @ Flying Tigers

Follow on MiLB First Pitch  https //stza.co/+wKMr-2b

Shop  https //stza.co/+wKMr-G

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Tortugas @ Flying Tigers
END:VALARM
DTSTART:20180816T223000Z
DTEND:20180817T013000Z
UID:IS0eh2yiQAS1Y3hDtKzifsyh@stanza.co
SUMMARY:Tortugas @ Flying Tigers
DESCRIPTION:Tortugas @ Flying Tigers\n\nFollow on MiLB First Pitch: https://stza.co/+wKMr-2b\n\nShop: https://stza.co/+wKMr-G\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144518Z
LAST-MODIFIED:20180213T144518Z
TRANSP:OPAQUE
END:VEVENT
* Tortugas @ Tarpons
<2018-08-17 Fri>--<2018-08-16 Thu>
:PROPERTIES:
:ID:       RQCAK-aBakAPgpdvlVtbdA9W@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Tortugas @ Tarpons Tortugas @ Tarpons

Follow on MiLB First Pitch  https //stza.co/+vjdB-1F

Shop  https //stza.co/+vjdB-2k

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Tortugas @ Tarpons
END:VALARM
DTSTART;VALUE=DATE:20180817
DTEND;VALUE=DATE:20180817
UID:RQCAK-aBakAPgpdvlVtbdA9W@stanza.co
SUMMARY:Tortugas @ Tarpons
DESCRIPTION:Tortugas @ Tarpons\n\nFollow on MiLB First Pitch: https://stza.co/+vjdB-1F\n\nShop: https://stza.co/+vjdB-2k\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144518Z
LAST-MODIFIED:20180213T144518Z
TRANSP:OPAQUE
END:VEVENT
* Tortugas @ Tarpons
<2018-08-18 Sat>--<2018-08-17 Fri>
:PROPERTIES:
:ID:       wt0A0DRKknGjYOznCMqdJYfu@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Tortugas @ Tarpons Tortugas @ Tarpons

Follow on MiLB First Pitch  https //stza.co/+vjdE-32

Shop  https //stza.co/+vjdE-3v

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Tortugas @ Tarpons
END:VALARM
DTSTART;VALUE=DATE:20180818
DTEND;VALUE=DATE:20180818
UID:wt0A0DRKknGjYOznCMqdJYfu@stanza.co
SUMMARY:Tortugas @ Tarpons
DESCRIPTION:Tortugas @ Tarpons\n\nFollow on MiLB First Pitch: https://stza.co/+vjdE-32\n\nShop: https://stza.co/+vjdE-3v\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144518Z
LAST-MODIFIED:20180213T144518Z
TRANSP:OPAQUE
END:VEVENT
* Tortugas @ Tarpons
<2018-08-19 Sun>--<2018-08-18 Sat>
:PROPERTIES:
:ID:       KIZd_yrepz4jn4OyS1rqbym7@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Tortugas @ Tarpons Tortugas @ Tarpons

Follow on MiLB First Pitch  https //stza.co/+vibN-1W

Shop  https //stza.co/+vibN-1Y

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Tortugas @ Tarpons
END:VALARM
DTSTART;VALUE=DATE:20180819
DTEND;VALUE=DATE:20180819
UID:KIZd_yrepz4jn4OyS1rqbym7@stanza.co
SUMMARY:Tortugas @ Tarpons
DESCRIPTION:Tortugas @ Tarpons\n\nFollow on MiLB First Pitch: https://stza.co/+vibN-1W\n\nShop: https://stza.co/+vibN-1Y\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144518Z
LAST-MODIFIED:20180213T144518Z
TRANSP:OPAQUE
END:VEVENT
* Tortugas vs. Flying Tigers
<2018-08-21 Tue 18:05-21:05>
:PROPERTIES:
:ID:       lWpBno2I67dvF4MsWPGu5y9p@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Tortugas vs. Flying Tigers Tortugas vs. Flying Tigers

Follow on MiLB First Pitch  https //stza.co/+vMjF-h

Shop  https //stza.co/+vMjF-1N

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Tortugas vs. Flying Tigers
END:VALARM
DTSTART:20180821T230500Z
DTEND:20180822T020500Z
UID:lWpBno2I67dvF4MsWPGu5y9p@stanza.co
SUMMARY:Tortugas vs. Flying Tigers
DESCRIPTION:Tortugas vs. Flying Tigers\n\nFollow on MiLB First Pitch: https://stza.co/+vMjF-h\n\nShop: https://stza.co/+vMjF-1N\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144518Z
LAST-MODIFIED:20180213T144518Z
TRANSP:OPAQUE
END:VEVENT
* Tortugas vs. Flying Tigers
<2018-08-22 Wed 18:05-21:05>
:PROPERTIES:
:ID:       R9nUOUs-580b3Umim13nz6I3@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Tortugas vs. Flying Tigers Tortugas vs. Flying Tigers

Follow on MiLB First Pitch  https //stza.co/+vMjG-1B

Shop  https //stza.co/+vMjG-39

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Tortugas vs. Flying Tigers
END:VALARM
DTSTART:20180822T230500Z
DTEND:20180823T020500Z
UID:R9nUOUs-580b3Umim13nz6I3@stanza.co
SUMMARY:Tortugas vs. Flying Tigers
DESCRIPTION:Tortugas vs. Flying Tigers\n\nFollow on MiLB First Pitch: https://stza.co/+vMjG-1B\n\nShop: https://stza.co/+vMjG-39\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144518Z
LAST-MODIFIED:20180213T144518Z
TRANSP:OPAQUE
END:VEVENT
* Tortugas vs. Flying Tigers
<2018-08-23 Thu 18:05-21:05>
:PROPERTIES:
:ID:       HISG5ckNymu5RamNv7c8H43Z@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Tortugas vs. Flying Tigers Tortugas vs. Flying Tigers

Follow on MiLB First Pitch  https //stza.co/+vMjJ-2X

Shop  https //stza.co/+vMjJ-2S

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Tortugas vs. Flying Tigers
END:VALARM
DTSTART:20180823T230500Z
DTEND:20180824T020500Z
UID:HISG5ckNymu5RamNv7c8H43Z@stanza.co
SUMMARY:Tortugas vs. Flying Tigers
DESCRIPTION:Tortugas vs. Flying Tigers\n\nFollow on MiLB First Pitch: https://stza.co/+vMjJ-2X\n\nShop: https://stza.co/+vMjJ-2S\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144518Z
LAST-MODIFIED:20180213T144518Z
TRANSP:OPAQUE
END:VEVENT
* Tortugas vs. Tarpons
<2018-08-24 Fri 18:05-21:05>
:PROPERTIES:
:ID:       ltRgu972MqTAV4i7xxGpfLgN@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Tortugas vs. Tarpons Tortugas vs. Tarpons

Follow on MiLB First Pitch  https //stza.co/+vMjL-T

Shop  https //stza.co/+vMjL-2m

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Tortugas vs. Tarpons
END:VALARM
DTSTART:20180824T230500Z
DTEND:20180825T020500Z
UID:ltRgu972MqTAV4i7xxGpfLgN@stanza.co
SUMMARY:Tortugas vs. Tarpons
DESCRIPTION:Tortugas vs. Tarpons\n\nFollow on MiLB First Pitch: https://stza.co/+vMjL-T\n\nShop: https://stza.co/+vMjL-2m\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144518Z
LAST-MODIFIED:20180213T144518Z
TRANSP:OPAQUE
END:VEVENT
* Tortugas vs. Tarpons
<2018-08-25 Sat 18:05-21:05>
:PROPERTIES:
:ID:       Fb1fckACHptsfpbYFn3GslR9@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Tortugas vs. Tarpons Tortugas vs. Tarpons

Follow on MiLB First Pitch  https //stza.co/+vMjM-R

Shop  https //stza.co/+vMjM-2B

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Tortugas vs. Tarpons
END:VALARM
DTSTART:20180825T230500Z
DTEND:20180826T020500Z
UID:Fb1fckACHptsfpbYFn3GslR9@stanza.co
SUMMARY:Tortugas vs. Tarpons
DESCRIPTION:Tortugas vs. Tarpons\n\nFollow on MiLB First Pitch: https://stza.co/+vMjM-R\n\nShop: https://stza.co/+vMjM-2B\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144518Z
LAST-MODIFIED:20180213T144518Z
TRANSP:OPAQUE
END:VEVENT
* Tortugas vs. Tarpons
<2018-08-26 Sun 16:35-19:35>
:PROPERTIES:
:ID:       gwoo1qTChcp_dPndzERNOjLQ@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Tortugas vs. Tarpons Tortugas vs. Tarpons

Follow on MiLB First Pitch  https //stza.co/+vMjO-2C

Shop  https //stza.co/+vMjO-2X

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Tortugas vs. Tarpons
END:VALARM
DTSTART:20180826T213500Z
DTEND:20180827T003500Z
UID:gwoo1qTChcp_dPndzERNOjLQ@stanza.co
SUMMARY:Tortugas vs. Tarpons
DESCRIPTION:Tortugas vs. Tarpons\n\nFollow on MiLB First Pitch: https://stza.co/+vMjO-2C\n\nShop: https://stza.co/+vMjO-2X\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144518Z
LAST-MODIFIED:20180213T144518Z
TRANSP:OPAQUE
END:VEVENT
* Tortugas @ Stone Crabs
<2018-08-27 Mon 17:35-20:35>
:PROPERTIES:
:ID:       ZrpL3ZbLu9GwXykyP-BulyES@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Tortugas @ Stone Crabs Tortugas @ Stone Crabs

Follow on MiLB First Pitch  https //stza.co/+wYmL-3T

Shop  https //stza.co/+wYmL-1u

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Tortugas @ Stone Crabs
END:VALARM
DTSTART:20180827T223500Z
DTEND:20180828T013500Z
UID:ZrpL3ZbLu9GwXykyP-BulyES@stanza.co
SUMMARY:Tortugas @ Stone Crabs
DESCRIPTION:Tortugas @ Stone Crabs\n\nFollow on MiLB First Pitch: https://stza.co/+wYmL-3T\n\nShop: https://stza.co/+wYmL-1u\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144518Z
LAST-MODIFIED:20180213T144518Z
TRANSP:OPAQUE
END:VEVENT
* Tortugas @ Stone Crabs
<2018-08-28 Tue 17:35-20:35>
:PROPERTIES:
:ID:       HVIXTJ2VQ4F9NlCx1JKZuKFI@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Tortugas @ Stone Crabs Tortugas @ Stone Crabs

Follow on MiLB First Pitch  https //stza.co/+wYmN-21

Shop  https //stza.co/+wYmN-2L

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Tortugas @ Stone Crabs
END:VALARM
DTSTART:20180828T223500Z
DTEND:20180829T013500Z
UID:HVIXTJ2VQ4F9NlCx1JKZuKFI@stanza.co
SUMMARY:Tortugas @ Stone Crabs
DESCRIPTION:Tortugas @ Stone Crabs\n\nFollow on MiLB First Pitch: https://stza.co/+wYmN-21\n\nShop: https://stza.co/+wYmN-2L\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144518Z
LAST-MODIFIED:20180213T144518Z
TRANSP:OPAQUE
END:VEVENT
* Tortugas @ Stone Crabs
<2018-08-29 Wed 17:35-20:35>
:PROPERTIES:
:ID:       WSWeMvQNndKsKT6ze-su39hh@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Tortugas @ Stone Crabs Tortugas @ Stone Crabs

Follow on MiLB First Pitch  https //stza.co/+wYmQ-P

Shop  https //stza.co/+wYmQ-14

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Tortugas @ Stone Crabs
END:VALARM
DTSTART:20180829T223500Z
DTEND:20180830T013500Z
UID:WSWeMvQNndKsKT6ze-su39hh@stanza.co
SUMMARY:Tortugas @ Stone Crabs
DESCRIPTION:Tortugas @ Stone Crabs\n\nFollow on MiLB First Pitch: https://stza.co/+wYmQ-P\n\nShop: https://stza.co/+wYmQ-14\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144518Z
LAST-MODIFIED:20180213T144518Z
TRANSP:OPAQUE
END:VEVENT
* Tortugas @ Stone Crabs
<2018-08-30 Thu 17:35-20:35>
:PROPERTIES:
:ID:       rdFMRiuAXO5RiMiU5poC0-eO@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Tortugas @ Stone Crabs Tortugas @ Stone Crabs

Follow on MiLB First Pitch  https //stza.co/+wYmR-2S

Shop  https //stza.co/+wYmR-n

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Tortugas @ Stone Crabs
END:VALARM
DTSTART:20180830T223500Z
DTEND:20180831T013500Z
UID:rdFMRiuAXO5RiMiU5poC0-eO@stanza.co
SUMMARY:Tortugas @ Stone Crabs
DESCRIPTION:Tortugas @ Stone Crabs\n\nFollow on MiLB First Pitch: https://stza.co/+wYmR-2S\n\nShop: https://stza.co/+wYmR-n\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144518Z
LAST-MODIFIED:20180213T144518Z
TRANSP:OPAQUE
END:VEVENT
* Tortugas @ Blue Jays
<2018-08-31 Fri 17:30-20:30>
:PROPERTIES:
:ID:       4zJjASjWABzInHq9QRGmMvtc@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Tortugas @ Blue Jays Tortugas @ Blue Jays

Follow on MiLB First Pitch  https //stza.co/+y0GH-2P

Shop  https //stza.co/+y0GH-_

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Tortugas @ Blue Jays
END:VALARM
DTSTART:20180831T223000Z
DTEND:20180901T013000Z
UID:4zJjASjWABzInHq9QRGmMvtc@stanza.co
SUMMARY:Tortugas @ Blue Jays
DESCRIPTION:Tortugas @ Blue Jays\n\nFollow on MiLB First Pitch: https://stza.co/+y0GH-2P\n\nShop: https://stza.co/+y0GH-_\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144518Z
LAST-MODIFIED:20180213T144518Z
TRANSP:OPAQUE
END:VEVENT
* Tortugas @ Blue Jays
<2018-09-01 Sat 17:30-20:30>
:PROPERTIES:
:ID:       4YinWb9134qpfqWUfKd98JL0@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Tortugas @ Blue Jays Tortugas @ Blue Jays

Follow on MiLB First Pitch  https //stza.co/+y0GI-L

Shop  https //stza.co/+y0GI-1k

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Tortugas @ Blue Jays
END:VALARM
DTSTART:20180901T223000Z
DTEND:20180902T013000Z
UID:4YinWb9134qpfqWUfKd98JL0@stanza.co
SUMMARY:Tortugas @ Blue Jays
DESCRIPTION:Tortugas @ Blue Jays\n\nFollow on MiLB First Pitch: https://stza.co/+y0GI-L\n\nShop: https://stza.co/+y0GI-1k\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144518Z
LAST-MODIFIED:20180213T144518Z
TRANSP:OPAQUE
END:VEVENT
* Tortugas @ Blue Jays
<2018-09-02 Sun 11:00-14:00>
:PROPERTIES:
:ID:       p64SX1fTKb7WB8AIzZrzM4Ou@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Tortugas @ Blue Jays Tortugas @ Blue Jays

Follow on MiLB First Pitch  https //stza.co/+y0GJ-f

Shop  https //stza.co/+y0GJ-2c

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Tortugas @ Blue Jays
END:VALARM
DTSTART:20180902T160000Z
DTEND:20180902T190000Z
UID:p64SX1fTKb7WB8AIzZrzM4Ou@stanza.co
SUMMARY:Tortugas @ Blue Jays
DESCRIPTION:Tortugas @ Blue Jays\n\nFollow on MiLB First Pitch: https://stza.co/+y0GJ-f\n\nShop: https://stza.co/+y0GJ-2c\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144518Z
LAST-MODIFIED:20180213T144518Z
TRANSP:OPAQUE
END:VEVENT
