#+TITLE:       Main Google calendar entries
#+AUTHOR:      Eric S Fraga
#+EMAIL:       e.fraga@ucl.ac.uk
#+DESCRIPTION: converted using the ical2org awk script
#+CATEGORY:    google
#+STARTUP:     hidestars
#+STARTUP:     overview

* COMMENT original iCal preamble

* Hawks @ Indians
<2018-06-15 Fri 20:30-23:30>
:PROPERTIES:
:ID:       dZTH8X3bDPJDYwdB3b8y5vEj@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Hawks @ Indians Hawks @ Indians

Follow on MiLB First Pitch  https //stza.co/+xC5F-1T

Shop  https //stza.co/+xC5F-3g

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Hawks @ Indians
END:VALARM
DTSTART:20180616T013000Z
DTEND:20180616T043000Z
UID:dZTH8X3bDPJDYwdB3b8y5vEj@stanza.co
SUMMARY:Hawks @ Indians
DESCRIPTION:Hawks @ Indians\n\nFollow on MiLB First Pitch: https://stza.co/+xC5F-1T\n\nShop: https://stza.co/+xC5F-3g\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144507Z
LAST-MODIFIED:20180213T144507Z
TRANSP:OPAQUE
END:VEVENT
* Hawks @ Indians
<2018-06-16 Sat 20:30-23:30>
:PROPERTIES:
:ID:       TZIY_6uchFcpsR0pei1mm3n4@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Hawks @ Indians Hawks @ Indians

Follow on MiLB First Pitch  https //stza.co/+xC5J-h

Shop  https //stza.co/+xC5J-$

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Hawks @ Indians
END:VALARM
DTSTART:20180617T013000Z
DTEND:20180617T043000Z
UID:TZIY_6uchFcpsR0pei1mm3n4@stanza.co
SUMMARY:Hawks @ Indians
DESCRIPTION:Hawks @ Indians\n\nFollow on MiLB First Pitch: https://stza.co/+xC5J-h\n\nShop: https://stza.co/+xC5J-$\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144507Z
LAST-MODIFIED:20180213T144507Z
TRANSP:OPAQUE
END:VEVENT
* Hawks @ Indians
<2018-06-17 Sun 17:30-20:30>
:PROPERTIES:
:ID:       pFteKCvEDfG3LfTr6hQMCxdI@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Hawks @ Indians Hawks @ Indians

Follow on MiLB First Pitch  https //stza.co/+xC5O-3h

Shop  https //stza.co/+xC5O-11

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Hawks @ Indians
END:VALARM
DTSTART:20180617T223000Z
DTEND:20180618T013000Z
UID:pFteKCvEDfG3LfTr6hQMCxdI@stanza.co
SUMMARY:Hawks @ Indians
DESCRIPTION:Hawks @ Indians\n\nFollow on MiLB First Pitch: https://stza.co/+xC5O-3h\n\nShop: https://stza.co/+xC5O-11\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144507Z
LAST-MODIFIED:20180213T144507Z
TRANSP:OPAQUE
END:VEVENT
* Hawks @ Indians
<2018-06-18 Mon 20:30-23:30>
:PROPERTIES:
:ID:       IIjfdTdJrNhNeXvsVF2cWL_O@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Hawks @ Indians Hawks @ Indians

Follow on MiLB First Pitch  https //stza.co/+xC5Q-2_

Shop  https //stza.co/+xC5Q-1R

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Hawks @ Indians
END:VALARM
DTSTART:20180619T013000Z
DTEND:20180619T043000Z
UID:IIjfdTdJrNhNeXvsVF2cWL_O@stanza.co
SUMMARY:Hawks @ Indians
DESCRIPTION:Hawks @ Indians\n\nFollow on MiLB First Pitch: https://stza.co/+xC5Q-2_\n\nShop: https://stza.co/+xC5Q-1R\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144507Z
LAST-MODIFIED:20180213T144507Z
TRANSP:OPAQUE
END:VEVENT
* Hawks @ Indians
<2018-06-19 Tue 20:30-23:30>
:PROPERTIES:
:ID:       EMGRtgxEes9NSK_PiN6i8Z7A@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Hawks @ Indians Hawks @ Indians

Follow on MiLB First Pitch  https //stza.co/+xBh8-E

Shop  https //stza.co/+xBh8-3z

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Hawks @ Indians
END:VALARM
DTSTART:20180620T013000Z
DTEND:20180620T043000Z
UID:EMGRtgxEes9NSK_PiN6i8Z7A@stanza.co
SUMMARY:Hawks @ Indians
DESCRIPTION:Hawks @ Indians\n\nFollow on MiLB First Pitch: https://stza.co/+xBh8-E\n\nShop: https://stza.co/+xBh8-3z\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144507Z
LAST-MODIFIED:20180213T144507Z
TRANSP:OPAQUE
END:VEVENT
* Hawks vs. Volcanoes
<2018-06-20 Wed 20:15-23:15>
:PROPERTIES:
:ID:       06VPoi6zVZnC07zXkcKZjTNR@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Hawks vs. Volcanoes Hawks vs. Volcanoes

Follow on MiLB First Pitch  https //stza.co/+xC2k-21

Shop  https //stza.co/+xC2k-16

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Hawks vs. Volcanoes
END:VALARM
DTSTART:20180621T011500Z
DTEND:20180621T041500Z
UID:06VPoi6zVZnC07zXkcKZjTNR@stanza.co
SUMMARY:Hawks vs. Volcanoes
DESCRIPTION:Hawks vs. Volcanoes\n\nFollow on MiLB First Pitch: https://stza.co/+xC2k-21\n\nShop: https://stza.co/+xC2k-16\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144507Z
LAST-MODIFIED:20180213T144507Z
TRANSP:OPAQUE
END:VEVENT
* Hawks vs. Volcanoes
<2018-06-21 Thu 20:15-23:15>
:PROPERTIES:
:ID:       3ZVGf04c20MVKpN31a-fj21o@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Hawks vs. Volcanoes Hawks vs. Volcanoes

Follow on MiLB First Pitch  https //stza.co/+xC2o-r

Shop  https //stza.co/+xC2o-2G

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Hawks vs. Volcanoes
END:VALARM
DTSTART:20180622T011500Z
DTEND:20180622T041500Z
UID:3ZVGf04c20MVKpN31a-fj21o@stanza.co
SUMMARY:Hawks vs. Volcanoes
DESCRIPTION:Hawks vs. Volcanoes\n\nFollow on MiLB First Pitch: https://stza.co/+xC2o-r\n\nShop: https://stza.co/+xC2o-2G\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144507Z
LAST-MODIFIED:20180213T144507Z
TRANSP:OPAQUE
END:VEVENT
* Hawks vs. Volcanoes
<2018-06-22 Fri 20:15-23:15>
:PROPERTIES:
:ID:       rn3TWz3V3ij3ejDmVzo_VW8F@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Hawks vs. Volcanoes Hawks vs. Volcanoes

Follow on MiLB First Pitch  https //stza.co/+xC2t-21

Shop  https //stza.co/+xC2t-1H

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Hawks vs. Volcanoes
END:VALARM
DTSTART:20180623T011500Z
DTEND:20180623T041500Z
UID:rn3TWz3V3ij3ejDmVzo_VW8F@stanza.co
SUMMARY:Hawks vs. Volcanoes
DESCRIPTION:Hawks vs. Volcanoes\n\nFollow on MiLB First Pitch: https://stza.co/+xC2t-21\n\nShop: https://stza.co/+xC2t-1H\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144507Z
LAST-MODIFIED:20180213T144507Z
TRANSP:OPAQUE
END:VEVENT
* Hawks @ Emeralds
<2018-06-23 Sat 21:05>--<2018-06-24 Sun 00:05>
:PROPERTIES:
:ID:       ZUAgW8jf3XuK8jqxPvagP-Io@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Hawks @ Emeralds Hawks @ Emeralds

Follow on MiLB First Pitch  https //stza.co/+xWNZ-y

Shop  https //stza.co/+xWNZ-25

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Hawks @ Emeralds
END:VALARM
DTSTART:20180624T020500Z
DTEND:20180624T050500Z
UID:ZUAgW8jf3XuK8jqxPvagP-Io@stanza.co
SUMMARY:Hawks @ Emeralds
DESCRIPTION:Hawks @ Emeralds\n\nFollow on MiLB First Pitch: https://stza.co/+xWNZ-y\n\nShop: https://stza.co/+xWNZ-25\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144507Z
LAST-MODIFIED:20180213T144507Z
TRANSP:OPAQUE
END:VEVENT
* Hawks @ Emeralds
<2018-06-24 Sun 21:05>--<2018-06-25 Mon 00:05>
:PROPERTIES:
:ID:       -1BFjaW4LXW57-5saTPXWoJ5@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Hawks @ Emeralds Hawks @ Emeralds

Follow on MiLB First Pitch  https //stza.co/+xWN_-1K

Shop  https //stza.co/+xWN_-3n

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Hawks @ Emeralds
END:VALARM
DTSTART:20180625T020500Z
DTEND:20180625T050500Z
UID:-1BFjaW4LXW57-5saTPXWoJ5@stanza.co
SUMMARY:Hawks @ Emeralds
DESCRIPTION:Hawks @ Emeralds\n\nFollow on MiLB First Pitch: https://stza.co/+xWN_-1K\n\nShop: https://stza.co/+xWN_-3n\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144507Z
LAST-MODIFIED:20180213T144507Z
TRANSP:OPAQUE
END:VEVENT
* Hawks @ Emeralds
<2018-06-25 Mon 21:05>--<2018-06-26 Tue 00:05>
:PROPERTIES:
:ID:       dRKLUxdhZeImyKi8jbx2vqFK@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Hawks @ Emeralds Hawks @ Emeralds

Follow on MiLB First Pitch  https //stza.co/+xWN$-30

Shop  https //stza.co/+xWN$-1r

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Hawks @ Emeralds
END:VALARM
DTSTART:20180626T020500Z
DTEND:20180626T050500Z
UID:dRKLUxdhZeImyKi8jbx2vqFK@stanza.co
SUMMARY:Hawks @ Emeralds
DESCRIPTION:Hawks @ Emeralds\n\nFollow on MiLB First Pitch: https://stza.co/+xWN$-30\n\nShop: https://stza.co/+xWN$-1r\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144507Z
LAST-MODIFIED:20180213T144507Z
TRANSP:OPAQUE
END:VEVENT
* Hawks vs. Hops
<2018-06-26 Tue 20:15-23:15>
:PROPERTIES:
:ID:       c86KYP5vPeaegAkJrQu0qaiV@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Hawks vs. Hops Hawks vs. Hops

Follow on MiLB First Pitch  https //stza.co/+xC2y-2Y

Shop  https //stza.co/+xC2y-1Q

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Hawks vs. Hops
END:VALARM
DTSTART:20180627T011500Z
DTEND:20180627T041500Z
UID:c86KYP5vPeaegAkJrQu0qaiV@stanza.co
SUMMARY:Hawks vs. Hops
DESCRIPTION:Hawks vs. Hops\n\nFollow on MiLB First Pitch: https://stza.co/+xC2y-2Y\n\nShop: https://stza.co/+xC2y-1Q\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144507Z
LAST-MODIFIED:20180213T144507Z
TRANSP:OPAQUE
END:VEVENT
* Hawks vs. Hops
<2018-06-27 Wed 20:15-23:15>
:PROPERTIES:
:ID:       JleHSjViGi1nHmRaK1OOWXZW@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Hawks vs. Hops Hawks vs. Hops

Follow on MiLB First Pitch  https //stza.co/+xC2D-1Z

Shop  https //stza.co/+xC2D-Q

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Hawks vs. Hops
END:VALARM
DTSTART:20180628T011500Z
DTEND:20180628T041500Z
UID:JleHSjViGi1nHmRaK1OOWXZW@stanza.co
SUMMARY:Hawks vs. Hops
DESCRIPTION:Hawks vs. Hops\n\nFollow on MiLB First Pitch: https://stza.co/+xC2D-1Z\n\nShop: https://stza.co/+xC2D-Q\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144507Z
LAST-MODIFIED:20180213T144507Z
TRANSP:OPAQUE
END:VEVENT
* Hawks vs. Hops
<2018-06-28 Thu 20:15-23:15>
:PROPERTIES:
:ID:       _mYX_s4zBofbW4JShJHdB3jE@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Hawks vs. Hops Hawks vs. Hops

Follow on MiLB First Pitch  https //stza.co/+xC2I-w

Shop  https //stza.co/+xC2I-1a

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Hawks vs. Hops
END:VALARM
DTSTART:20180629T011500Z
DTEND:20180629T041500Z
UID:_mYX_s4zBofbW4JShJHdB3jE@stanza.co
SUMMARY:Hawks vs. Hops
DESCRIPTION:Hawks vs. Hops\n\nFollow on MiLB First Pitch: https://stza.co/+xC2I-w\n\nShop: https://stza.co/+xC2I-1a\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144507Z
LAST-MODIFIED:20180213T144507Z
TRANSP:OPAQUE
END:VEVENT
* Hawks @ Dust Devils
<2018-06-29 Fri 21:15>--<2018-06-30 Sat 00:15>
:PROPERTIES:
:ID:       Gf4EnynNIcjuQrQprAbmHvdC@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Hawks @ Dust Devils Hawks @ Dust Devils

Follow on MiLB First Pitch  https //stza.co/+vO5s-3G

Shop  https //stza.co/+vO5s-2n

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Hawks @ Dust Devils
END:VALARM
DTSTART:20180630T021500Z
DTEND:20180630T051500Z
UID:Gf4EnynNIcjuQrQprAbmHvdC@stanza.co
SUMMARY:Hawks @ Dust Devils
DESCRIPTION:Hawks @ Dust Devils\n\nFollow on MiLB First Pitch: https://stza.co/+vO5s-3G\n\nShop: https://stza.co/+vO5s-2n\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144507Z
LAST-MODIFIED:20180213T144507Z
TRANSP:OPAQUE
END:VEVENT
* Hawks @ Dust Devils
<2018-06-30 Sat 21:15>--<2018-07-01 Sun 00:15>
:PROPERTIES:
:ID:       hMXbVLD8QDuZ4mwCnV6IAAGC@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Hawks @ Dust Devils Hawks @ Dust Devils

Follow on MiLB First Pitch  https //stza.co/+vO5t-19

Shop  https //stza.co/+vO5t-2Y

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Hawks @ Dust Devils
END:VALARM
DTSTART:20180701T021500Z
DTEND:20180701T051500Z
UID:hMXbVLD8QDuZ4mwCnV6IAAGC@stanza.co
SUMMARY:Hawks @ Dust Devils
DESCRIPTION:Hawks @ Dust Devils\n\nFollow on MiLB First Pitch: https://stza.co/+vO5t-19\n\nShop: https://stza.co/+vO5t-2Y\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144507Z
LAST-MODIFIED:20180213T144507Z
TRANSP:OPAQUE
END:VEVENT
* Hawks @ Dust Devils
<2018-07-01 Sun 21:15>--<2018-07-02 Mon 00:15>
:PROPERTIES:
:ID:       LooKKBfs81CnScygW7lOnUNW@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Hawks @ Dust Devils Hawks @ Dust Devils

Follow on MiLB First Pitch  https //stza.co/+vO5u-20

Shop  https //stza.co/+vO5u-3q

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Hawks @ Dust Devils
END:VALARM
DTSTART:20180702T021500Z
DTEND:20180702T051500Z
UID:LooKKBfs81CnScygW7lOnUNW@stanza.co
SUMMARY:Hawks @ Dust Devils
DESCRIPTION:Hawks @ Dust Devils\n\nFollow on MiLB First Pitch: https://stza.co/+vO5u-20\n\nShop: https://stza.co/+vO5u-3q\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144507Z
LAST-MODIFIED:20180213T144507Z
TRANSP:OPAQUE
END:VEVENT
* Hawks @ Dust Devils
<2018-07-02 Mon 21:15>--<2018-07-03 Tue 00:15>
:PROPERTIES:
:ID:       UKlP9t1F4osAl_1KBJrAxuM3@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Hawks @ Dust Devils Hawks @ Dust Devils

Follow on MiLB First Pitch  https //stza.co/+vO5v-m

Shop  https //stza.co/+vO5v-1_

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Hawks @ Dust Devils
END:VALARM
DTSTART:20180703T021500Z
DTEND:20180703T051500Z
UID:UKlP9t1F4osAl_1KBJrAxuM3@stanza.co
SUMMARY:Hawks @ Dust Devils
DESCRIPTION:Hawks @ Dust Devils\n\nFollow on MiLB First Pitch: https://stza.co/+vO5v-m\n\nShop: https://stza.co/+vO5v-1_\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144507Z
LAST-MODIFIED:20180213T144507Z
TRANSP:OPAQUE
END:VEVENT
* Hawks @ Dust Devils
<2018-07-03 Tue 21:15>--<2018-07-04 Wed 00:15>
:PROPERTIES:
:ID:       CUl5P4Iq6oih2Nn_mx3Ojtz0@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Hawks @ Dust Devils Hawks @ Dust Devils

Follow on MiLB First Pitch  https //stza.co/+vO5w-3a

Shop  https //stza.co/+vO5w-39

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Hawks @ Dust Devils
END:VALARM
DTSTART:20180704T021500Z
DTEND:20180704T051500Z
UID:CUl5P4Iq6oih2Nn_mx3Ojtz0@stanza.co
SUMMARY:Hawks @ Dust Devils
DESCRIPTION:Hawks @ Dust Devils\n\nFollow on MiLB First Pitch: https://stza.co/+vO5w-3a\n\nShop: https://stza.co/+vO5w-39\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144507Z
LAST-MODIFIED:20180213T144507Z
TRANSP:OPAQUE
END:VEVENT
* Hawks vs. Emeralds
<2018-07-04 Wed 20:15-23:15>
:PROPERTIES:
:ID:       g3GpzKJuGVlmoqrM72VZSu27@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Hawks vs. Emeralds Hawks vs. Emeralds

Follow on MiLB First Pitch  https //stza.co/+xC2O-1h

Shop  https //stza.co/+xC2O-1X

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Hawks vs. Emeralds
END:VALARM
DTSTART:20180705T011500Z
DTEND:20180705T041500Z
UID:g3GpzKJuGVlmoqrM72VZSu27@stanza.co
SUMMARY:Hawks vs. Emeralds
DESCRIPTION:Hawks vs. Emeralds\n\nFollow on MiLB First Pitch: https://stza.co/+xC2O-1h\n\nShop: https://stza.co/+xC2O-1X\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144507Z
LAST-MODIFIED:20180213T144507Z
TRANSP:OPAQUE
END:VEVENT
* Hawks vs. Emeralds
<2018-07-05 Thu 20:15-23:15>
:PROPERTIES:
:ID:       TpElvlXkHDEqfckCyZ2ap16y@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Hawks vs. Emeralds Hawks vs. Emeralds

Follow on MiLB First Pitch  https //stza.co/+xC2V-6

Shop  https //stza.co/+xC2V-1V

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Hawks vs. Emeralds
END:VALARM
DTSTART:20180706T011500Z
DTEND:20180706T041500Z
UID:TpElvlXkHDEqfckCyZ2ap16y@stanza.co
SUMMARY:Hawks vs. Emeralds
DESCRIPTION:Hawks vs. Emeralds\n\nFollow on MiLB First Pitch: https://stza.co/+xC2V-6\n\nShop: https://stza.co/+xC2V-1V\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144507Z
LAST-MODIFIED:20180213T144507Z
TRANSP:OPAQUE
END:VEVENT
* Hawks vs. Emeralds
<2018-07-06 Fri 20:15-23:15>
:PROPERTIES:
:ID:       UsSsElOJBBI6cT6iN1XS8LFn@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Hawks vs. Emeralds Hawks vs. Emeralds

Follow on MiLB First Pitch  https //stza.co/+xC2$-1g

Shop  https //stza.co/+xC2$-3W

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Hawks vs. Emeralds
END:VALARM
DTSTART:20180707T011500Z
DTEND:20180707T041500Z
UID:UsSsElOJBBI6cT6iN1XS8LFn@stanza.co
SUMMARY:Hawks vs. Emeralds
DESCRIPTION:Hawks vs. Emeralds\n\nFollow on MiLB First Pitch: https://stza.co/+xC2$-1g\n\nShop: https://stza.co/+xC2$-3W\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144507Z
LAST-MODIFIED:20180213T144507Z
TRANSP:OPAQUE
END:VEVENT
* Hawks @ Volcanoes
<2018-07-07 Sat>--<2018-07-06 Fri>
:PROPERTIES:
:ID:       uGx8ObsFitX18DReq0ELLwnE@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Hawks @ Volcanoes Hawks @ Volcanoes

Follow on MiLB First Pitch  https //stza.co/+vO5h-3B

Shop  https //stza.co/+vO5h-3N

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Hawks @ Volcanoes
END:VALARM
DTSTART;VALUE=DATE:20180707
DTEND;VALUE=DATE:20180707
UID:uGx8ObsFitX18DReq0ELLwnE@stanza.co
SUMMARY:Hawks @ Volcanoes
DESCRIPTION:Hawks @ Volcanoes\n\nFollow on MiLB First Pitch: https://stza.co/+vO5h-3B\n\nShop: https://stza.co/+vO5h-3N\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144507Z
LAST-MODIFIED:20180213T144507Z
TRANSP:OPAQUE
END:VEVENT
* Hawks @ Volcanoes
<2018-07-08 Sun>--<2018-07-07 Sat>
:PROPERTIES:
:ID:       L2Z5F-Sv98AtHjk-RY5l_eUe@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Hawks @ Volcanoes Hawks @ Volcanoes

Follow on MiLB First Pitch  https //stza.co/+vO5i-1h

Shop  https //stza.co/+vO5i-R

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Hawks @ Volcanoes
END:VALARM
DTSTART;VALUE=DATE:20180708
DTEND;VALUE=DATE:20180708
UID:L2Z5F-Sv98AtHjk-RY5l_eUe@stanza.co
SUMMARY:Hawks @ Volcanoes
DESCRIPTION:Hawks @ Volcanoes\n\nFollow on MiLB First Pitch: https://stza.co/+vO5i-1h\n\nShop: https://stza.co/+vO5i-R\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144507Z
LAST-MODIFIED:20180213T144507Z
TRANSP:OPAQUE
END:VEVENT
* Hawks @ Volcanoes
<2018-07-09 Mon>--<2018-07-08 Sun>
:PROPERTIES:
:ID:       kWTS4uJNBRcmhtlrJt3FvJl-@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Hawks @ Volcanoes Hawks @ Volcanoes

Follow on MiLB First Pitch  https //stza.co/+vO5j-b

Shop  https //stza.co/+vO5j-2m

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Hawks @ Volcanoes
END:VALARM
DTSTART;VALUE=DATE:20180709
DTEND;VALUE=DATE:20180709
UID:kWTS4uJNBRcmhtlrJt3FvJl-@stanza.co
SUMMARY:Hawks @ Volcanoes
DESCRIPTION:Hawks @ Volcanoes\n\nFollow on MiLB First Pitch: https://stza.co/+vO5j-b\n\nShop: https://stza.co/+vO5j-2m\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144507Z
LAST-MODIFIED:20180213T144507Z
TRANSP:OPAQUE
END:VEVENT
* Hawks vs. Canadians
<2018-07-11 Wed 20:15-23:15>
:PROPERTIES:
:ID:       LHqR71Bby3tiYw8dhOT11au3@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Hawks vs. Canadians Hawks vs. Canadians

Follow on MiLB First Pitch  https //stza.co/+xC35-2F

Shop  https //stza.co/+xC35-2w

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Hawks vs. Canadians
END:VALARM
DTSTART:20180712T011500Z
DTEND:20180712T041500Z
UID:LHqR71Bby3tiYw8dhOT11au3@stanza.co
SUMMARY:Hawks vs. Canadians
DESCRIPTION:Hawks vs. Canadians\n\nFollow on MiLB First Pitch: https://stza.co/+xC35-2F\n\nShop: https://stza.co/+xC35-2w\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144507Z
LAST-MODIFIED:20180213T144507Z
TRANSP:OPAQUE
END:VEVENT
* Hawks vs. Canadians
<2018-07-12 Thu 20:15-23:15>
:PROPERTIES:
:ID:       yTQTRjVV30pMH0GL09i4NP8a@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Hawks vs. Canadians Hawks vs. Canadians

Follow on MiLB First Pitch  https //stza.co/+xC3e-3n

Shop  https //stza.co/+xC3e-39

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Hawks vs. Canadians
END:VALARM
DTSTART:20180713T011500Z
DTEND:20180713T041500Z
UID:yTQTRjVV30pMH0GL09i4NP8a@stanza.co
SUMMARY:Hawks vs. Canadians
DESCRIPTION:Hawks vs. Canadians\n\nFollow on MiLB First Pitch: https://stza.co/+xC3e-3n\n\nShop: https://stza.co/+xC3e-39\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144507Z
LAST-MODIFIED:20180213T144507Z
TRANSP:OPAQUE
END:VEVENT
* Hawks vs. Canadians
<2018-07-13 Fri 20:15-23:15>
:PROPERTIES:
:ID:       vxNmt54pk2yYWJf__AoDw2Hc@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Hawks vs. Canadians Hawks vs. Canadians

Follow on MiLB First Pitch  https //stza.co/+xC3j-1z

Shop  https //stza.co/+xC3j-2l

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Hawks vs. Canadians
END:VALARM
DTSTART:20180714T011500Z
DTEND:20180714T041500Z
UID:vxNmt54pk2yYWJf__AoDw2Hc@stanza.co
SUMMARY:Hawks vs. Canadians
DESCRIPTION:Hawks vs. Canadians\n\nFollow on MiLB First Pitch: https://stza.co/+xC3j-1z\n\nShop: https://stza.co/+xC3j-2l\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144507Z
LAST-MODIFIED:20180213T144507Z
TRANSP:OPAQUE
END:VEVENT
* Hawks vs. Canadians
<2018-07-14 Sat 20:15-23:15>
:PROPERTIES:
:ID:       f8qMS2X-FzQw9tbn5JxSdklv@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Hawks vs. Canadians Hawks vs. Canadians

Follow on MiLB First Pitch  https //stza.co/+xC3o-3f

Shop  https //stza.co/+xC3o-l

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Hawks vs. Canadians
END:VALARM
DTSTART:20180715T011500Z
DTEND:20180715T041500Z
UID:f8qMS2X-FzQw9tbn5JxSdklv@stanza.co
SUMMARY:Hawks vs. Canadians
DESCRIPTION:Hawks vs. Canadians\n\nFollow on MiLB First Pitch: https://stza.co/+xC3o-3f\n\nShop: https://stza.co/+xC3o-l\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144507Z
LAST-MODIFIED:20180213T144507Z
TRANSP:OPAQUE
END:VEVENT
* Hawks vs. Canadians
<2018-07-15 Sun 18:15-21:15>
:PROPERTIES:
:ID:       0LNguW-OwH5KdOmdbdMJf8Y7@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Hawks vs. Canadians Hawks vs. Canadians

Follow on MiLB First Pitch  https //stza.co/+xC3r-t

Shop  https //stza.co/+xC3r-l

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Hawks vs. Canadians
END:VALARM
DTSTART:20180715T231500Z
DTEND:20180716T021500Z
UID:0LNguW-OwH5KdOmdbdMJf8Y7@stanza.co
SUMMARY:Hawks vs. Canadians
DESCRIPTION:Hawks vs. Canadians\n\nFollow on MiLB First Pitch: https://stza.co/+xC3r-t\n\nShop: https://stza.co/+xC3r-l\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144507Z
LAST-MODIFIED:20180213T144507Z
TRANSP:OPAQUE
END:VEVENT
* Hawks @ Hops
<2018-07-16 Mon 21:05>--<2018-07-17 Tue 00:05>
:PROPERTIES:
:ID:       byqfSvZfjkcItPE6VQwLrHe2@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Hawks @ Hops Hawks @ Hops

Follow on MiLB First Pitch  https //stza.co/+vO5b-2x

Shop  https //stza.co/+vO5b-2v

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Hawks @ Hops
END:VALARM
DTSTART:20180717T020500Z
DTEND:20180717T050500Z
UID:byqfSvZfjkcItPE6VQwLrHe2@stanza.co
SUMMARY:Hawks @ Hops
DESCRIPTION:Hawks @ Hops\n\nFollow on MiLB First Pitch: https://stza.co/+vO5b-2x\n\nShop: https://stza.co/+vO5b-2v\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144507Z
LAST-MODIFIED:20180213T144507Z
TRANSP:OPAQUE
END:VEVENT
* Hawks @ Hops
<2018-07-17 Tue 21:05>--<2018-07-18 Wed 00:05>
:PROPERTIES:
:ID:       hPkIdWuydF8Gy1UpZF1sQL3C@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Hawks @ Hops Hawks @ Hops

Follow on MiLB First Pitch  https //stza.co/+vO5c-2U

Shop  https //stza.co/+vO5c-10

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Hawks @ Hops
END:VALARM
DTSTART:20180718T020500Z
DTEND:20180718T050500Z
UID:hPkIdWuydF8Gy1UpZF1sQL3C@stanza.co
SUMMARY:Hawks @ Hops
DESCRIPTION:Hawks @ Hops\n\nFollow on MiLB First Pitch: https://stza.co/+vO5c-2U\n\nShop: https://stza.co/+vO5c-10\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144507Z
LAST-MODIFIED:20180213T144507Z
TRANSP:OPAQUE
END:VEVENT
* Hawks @ Hops
<2018-07-18 Wed 15:05-18:05>
:PROPERTIES:
:ID:       29NdDAx95BUqo0NRwgFyPN2p@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Hawks @ Hops Hawks @ Hops

Follow on MiLB First Pitch  https //stza.co/+vO5d-a

Shop  https //stza.co/+vO5d-2c

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Hawks @ Hops
END:VALARM
DTSTART:20180718T200500Z
DTEND:20180718T230500Z
UID:29NdDAx95BUqo0NRwgFyPN2p@stanza.co
SUMMARY:Hawks @ Hops
DESCRIPTION:Hawks @ Hops\n\nFollow on MiLB First Pitch: https://stza.co/+vO5d-a\n\nShop: https://stza.co/+vO5d-2c\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144507Z
LAST-MODIFIED:20180213T144507Z
TRANSP:OPAQUE
END:VEVENT
* Hawks vs. AquaSox
<2018-07-19 Thu 20:15-23:15>
:PROPERTIES:
:ID:       ob6747DOM9JEg89ISYBmAW9U@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Hawks vs. AquaSox Hawks vs. AquaSox

Follow on MiLB First Pitch  https //stza.co/+xC3x-1A

Shop  https //stza.co/+xC3x-2u

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Hawks vs. AquaSox
END:VALARM
DTSTART:20180720T011500Z
DTEND:20180720T041500Z
UID:ob6747DOM9JEg89ISYBmAW9U@stanza.co
SUMMARY:Hawks vs. AquaSox
DESCRIPTION:Hawks vs. AquaSox\n\nFollow on MiLB First Pitch: https://stza.co/+xC3x-1A\n\nShop: https://stza.co/+xC3x-2u\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144507Z
LAST-MODIFIED:20180213T144507Z
TRANSP:OPAQUE
END:VEVENT
* Hawks vs. AquaSox
<2018-07-20 Fri 20:15-23:15>
:PROPERTIES:
:ID:       IUoGP1EKeX4ffizFlt7QFuLH@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Hawks vs. AquaSox Hawks vs. AquaSox

Follow on MiLB First Pitch  https //stza.co/+xC3D-18

Shop  https //stza.co/+xC3D-u

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Hawks vs. AquaSox
END:VALARM
DTSTART:20180721T011500Z
DTEND:20180721T041500Z
UID:IUoGP1EKeX4ffizFlt7QFuLH@stanza.co
SUMMARY:Hawks vs. AquaSox
DESCRIPTION:Hawks vs. AquaSox\n\nFollow on MiLB First Pitch: https://stza.co/+xC3D-18\n\nShop: https://stza.co/+xC3D-u\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144507Z
LAST-MODIFIED:20180213T144507Z
TRANSP:OPAQUE
END:VEVENT
* Hawks vs. AquaSox
<2018-07-21 Sat 20:15-23:15>
:PROPERTIES:
:ID:       ScccOelLpnq6bcpM7iCI575V@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Hawks vs. AquaSox Hawks vs. AquaSox

Follow on MiLB First Pitch  https //stza.co/+xC3J-1P

Shop  https //stza.co/+xC3J-W

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Hawks vs. AquaSox
END:VALARM
DTSTART:20180722T011500Z
DTEND:20180722T041500Z
UID:ScccOelLpnq6bcpM7iCI575V@stanza.co
SUMMARY:Hawks vs. AquaSox
DESCRIPTION:Hawks vs. AquaSox\n\nFollow on MiLB First Pitch: https://stza.co/+xC3J-1P\n\nShop: https://stza.co/+xC3J-W\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144507Z
LAST-MODIFIED:20180213T144507Z
TRANSP:OPAQUE
END:VEVENT
* Hawks vs. AquaSox
<2018-07-22 Sun 18:15-21:15>
:PROPERTIES:
:ID:       WQN2hv5NIlAHXbV3K1E7EXby@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Hawks vs. AquaSox Hawks vs. AquaSox

Follow on MiLB First Pitch  https //stza.co/+xC3P-2J

Shop  https //stza.co/+xC3P-12

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Hawks vs. AquaSox
END:VALARM
DTSTART:20180722T231500Z
DTEND:20180723T021500Z
UID:WQN2hv5NIlAHXbV3K1E7EXby@stanza.co
SUMMARY:Hawks vs. AquaSox
DESCRIPTION:Hawks vs. AquaSox\n\nFollow on MiLB First Pitch: https://stza.co/+xC3P-2J\n\nShop: https://stza.co/+xC3P-12\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144507Z
LAST-MODIFIED:20180213T144507Z
TRANSP:OPAQUE
END:VEVENT
* Hawks vs. AquaSox
<2018-07-23 Mon 20:15-23:15>
:PROPERTIES:
:ID:       ckyQg2b6-m0LdIH3vYFgsrJM@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Hawks vs. AquaSox Hawks vs. AquaSox

Follow on MiLB First Pitch  https //stza.co/+xC3V-w

Shop  https //stza.co/+xC3V-N

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Hawks vs. AquaSox
END:VALARM
DTSTART:20180724T011500Z
DTEND:20180724T041500Z
UID:ckyQg2b6-m0LdIH3vYFgsrJM@stanza.co
SUMMARY:Hawks vs. AquaSox
DESCRIPTION:Hawks vs. AquaSox\n\nFollow on MiLB First Pitch: https://stza.co/+xC3V-w\n\nShop: https://stza.co/+xC3V-N\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144507Z
LAST-MODIFIED:20180213T144507Z
TRANSP:OPAQUE
END:VEVENT
* Hawks @ Hops
<2018-07-24 Tue 21:05>--<2018-07-25 Wed 00:05>
:PROPERTIES:
:ID:       0lvjoV9Ok_FLDNZAaqc7FLep@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Hawks @ Hops Hawks @ Hops

Follow on MiLB First Pitch  https //stza.co/+vO5e-2D

Shop  https //stza.co/+vO5e-W

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Hawks @ Hops
END:VALARM
DTSTART:20180725T020500Z
DTEND:20180725T050500Z
UID:0lvjoV9Ok_FLDNZAaqc7FLep@stanza.co
SUMMARY:Hawks @ Hops
DESCRIPTION:Hawks @ Hops\n\nFollow on MiLB First Pitch: https://stza.co/+vO5e-2D\n\nShop: https://stza.co/+vO5e-W\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144507Z
LAST-MODIFIED:20180213T144507Z
TRANSP:OPAQUE
END:VEVENT
* Hawks @ Hops
<2018-07-25 Wed 21:05>--<2018-07-26 Thu 00:05>
:PROPERTIES:
:ID:       CNm6CqhEy_mT0WhA-Y3s5KI_@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Hawks @ Hops Hawks @ Hops

Follow on MiLB First Pitch  https //stza.co/+vO5f-W

Shop  https //stza.co/+vO5f-2R

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Hawks @ Hops
END:VALARM
DTSTART:20180726T020500Z
DTEND:20180726T050500Z
UID:CNm6CqhEy_mT0WhA-Y3s5KI_@stanza.co
SUMMARY:Hawks @ Hops
DESCRIPTION:Hawks @ Hops\n\nFollow on MiLB First Pitch: https://stza.co/+vO5f-W\n\nShop: https://stza.co/+vO5f-2R\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144507Z
LAST-MODIFIED:20180213T144507Z
TRANSP:OPAQUE
END:VEVENT
* Hawks @ Hops
<2018-07-26 Thu 21:05>--<2018-07-27 Fri 00:05>
:PROPERTIES:
:ID:       ENF1X_cEyd-81PxwSt888_Z6@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Hawks @ Hops Hawks @ Hops

Follow on MiLB First Pitch  https //stza.co/+vO5g-3C

Shop  https //stza.co/+vO5g-2$

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Hawks @ Hops
END:VALARM
DTSTART:20180727T020500Z
DTEND:20180727T050500Z
UID:ENF1X_cEyd-81PxwSt888_Z6@stanza.co
SUMMARY:Hawks @ Hops
DESCRIPTION:Hawks @ Hops\n\nFollow on MiLB First Pitch: https://stza.co/+vO5g-3C\n\nShop: https://stza.co/+vO5g-2$\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144507Z
LAST-MODIFIED:20180213T144507Z
TRANSP:OPAQUE
END:VEVENT
* Hawks vs. Dust Devils
<2018-07-27 Fri 20:15-23:15>
:PROPERTIES:
:ID:       DZzhxRt9xvtrCYHyR-mnhiaQ@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Hawks vs. Dust Devils Hawks vs. Dust Devils

Follow on MiLB First Pitch  https //stza.co/+xC3$-1q

Shop  https //stza.co/+xC3$-18

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Hawks vs. Dust Devils
END:VALARM
DTSTART:20180728T011500Z
DTEND:20180728T041500Z
UID:DZzhxRt9xvtrCYHyR-mnhiaQ@stanza.co
SUMMARY:Hawks vs. Dust Devils
DESCRIPTION:Hawks vs. Dust Devils\n\nFollow on MiLB First Pitch: https://stza.co/+xC3$-1q\n\nShop: https://stza.co/+xC3$-18\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144507Z
LAST-MODIFIED:20180213T144507Z
TRANSP:OPAQUE
END:VEVENT
* Hawks vs. Dust Devils
<2018-07-28 Sat 20:15-23:15>
:PROPERTIES:
:ID:       MNLJg9Y-b0kNpeCxRFyvY_qm@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Hawks vs. Dust Devils Hawks vs. Dust Devils

Follow on MiLB First Pitch  https //stza.co/+xC45-v

Shop  https //stza.co/+xC45-23

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Hawks vs. Dust Devils
END:VALARM
DTSTART:20180729T011500Z
DTEND:20180729T041500Z
UID:MNLJg9Y-b0kNpeCxRFyvY_qm@stanza.co
SUMMARY:Hawks vs. Dust Devils
DESCRIPTION:Hawks vs. Dust Devils\n\nFollow on MiLB First Pitch: https://stza.co/+xC45-v\n\nShop: https://stza.co/+xC45-23\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144507Z
LAST-MODIFIED:20180213T144507Z
TRANSP:OPAQUE
END:VEVENT
* Hawks vs. Dust Devils
<2018-07-29 Sun 18:15-21:15>
:PROPERTIES:
:ID:       DJzCdHoITnE6MFigDBfuJurB@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Hawks vs. Dust Devils Hawks vs. Dust Devils

Follow on MiLB First Pitch  https //stza.co/+xC49-1

Shop  https //stza.co/+xC49-24

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Hawks vs. Dust Devils
END:VALARM
DTSTART:20180729T231500Z
DTEND:20180730T021500Z
UID:DJzCdHoITnE6MFigDBfuJurB@stanza.co
SUMMARY:Hawks vs. Dust Devils
DESCRIPTION:Hawks vs. Dust Devils\n\nFollow on MiLB First Pitch: https://stza.co/+xC49-1\n\nShop: https://stza.co/+xC49-24\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144507Z
LAST-MODIFIED:20180213T144507Z
TRANSP:OPAQUE
END:VEVENT
* Hawks vs. Dust Devils
<2018-07-30 Mon 20:15-23:15>
:PROPERTIES:
:ID:       DAdL4mWHa5XkFZdkKUKMD7KE@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Hawks vs. Dust Devils Hawks vs. Dust Devils

Follow on MiLB First Pitch  https //stza.co/+xC4e-1d

Shop  https //stza.co/+xC4e-5

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Hawks vs. Dust Devils
END:VALARM
DTSTART:20180731T011500Z
DTEND:20180731T041500Z
UID:DAdL4mWHa5XkFZdkKUKMD7KE@stanza.co
SUMMARY:Hawks vs. Dust Devils
DESCRIPTION:Hawks vs. Dust Devils\n\nFollow on MiLB First Pitch: https://stza.co/+xC4e-1d\n\nShop: https://stza.co/+xC4e-5\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144507Z
LAST-MODIFIED:20180213T144507Z
TRANSP:OPAQUE
END:VEVENT
* Hawks vs. Dust Devils
<2018-07-31 Tue 20:15-23:15>
:PROPERTIES:
:ID:       YQraq09VxrDCAXvq9vdewkKH@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Hawks vs. Dust Devils Hawks vs. Dust Devils

Follow on MiLB First Pitch  https //stza.co/+xC4i-2s

Shop  https //stza.co/+xC4i-1I

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Hawks vs. Dust Devils
END:VALARM
DTSTART:20180801T011500Z
DTEND:20180801T041500Z
UID:YQraq09VxrDCAXvq9vdewkKH@stanza.co
SUMMARY:Hawks vs. Dust Devils
DESCRIPTION:Hawks vs. Dust Devils\n\nFollow on MiLB First Pitch: https://stza.co/+xC4i-2s\n\nShop: https://stza.co/+xC4i-1I\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144507Z
LAST-MODIFIED:20180213T144507Z
TRANSP:OPAQUE
END:VEVENT
* Hawks @ AquaSox
<2018-08-01 Wed 21:05>--<2018-08-02 Thu 00:05>
:PROPERTIES:
:ID:       elUz_GmTQi_1lZrwBngZnspP@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Hawks @ AquaSox Hawks @ AquaSox

Follow on MiLB First Pitch  https //stza.co/+vO56-2M

Shop  https //stza.co/+vO56-20

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Hawks @ AquaSox
END:VALARM
DTSTART:20180802T020500Z
DTEND:20180802T050500Z
UID:elUz_GmTQi_1lZrwBngZnspP@stanza.co
SUMMARY:Hawks @ AquaSox
DESCRIPTION:Hawks @ AquaSox\n\nFollow on MiLB First Pitch: https://stza.co/+vO56-2M\n\nShop: https://stza.co/+vO56-20\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144507Z
LAST-MODIFIED:20180213T144507Z
TRANSP:OPAQUE
END:VEVENT
* Hawks @ AquaSox
<2018-08-02 Thu 21:05>--<2018-08-03 Fri 00:05>
:PROPERTIES:
:ID:       g0npnUVqN4aE7APUqc_DA8p3@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Hawks @ AquaSox Hawks @ AquaSox

Follow on MiLB First Pitch  https //stza.co/+vO57-2a

Shop  https //stza.co/+vO57-3Q

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Hawks @ AquaSox
END:VALARM
DTSTART:20180803T020500Z
DTEND:20180803T050500Z
UID:g0npnUVqN4aE7APUqc_DA8p3@stanza.co
SUMMARY:Hawks @ AquaSox
DESCRIPTION:Hawks @ AquaSox\n\nFollow on MiLB First Pitch: https://stza.co/+vO57-2a\n\nShop: https://stza.co/+vO57-3Q\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144507Z
LAST-MODIFIED:20180213T144507Z
TRANSP:OPAQUE
END:VEVENT
* Hawks @ AquaSox
<2018-08-03 Fri 21:05>--<2018-08-04 Sat 00:05>
:PROPERTIES:
:ID:       nAIf6v8ZRPfDaBxsfD-NaGjn@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Hawks @ AquaSox Hawks @ AquaSox

Follow on MiLB First Pitch  https //stza.co/+vO58-3s

Shop  https //stza.co/+vO58-1P

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Hawks @ AquaSox
END:VALARM
DTSTART:20180804T020500Z
DTEND:20180804T050500Z
UID:nAIf6v8ZRPfDaBxsfD-NaGjn@stanza.co
SUMMARY:Hawks @ AquaSox
DESCRIPTION:Hawks @ AquaSox\n\nFollow on MiLB First Pitch: https://stza.co/+vO58-3s\n\nShop: https://stza.co/+vO58-1P\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144507Z
LAST-MODIFIED:20180213T144507Z
TRANSP:OPAQUE
END:VEVENT
* Hawks @ AquaSox
<2018-08-04 Sat 21:05>--<2018-08-05 Sun 00:05>
:PROPERTIES:
:ID:       b8fdE9d_xjBxxWL4vbfQ3Utj@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Hawks @ AquaSox Hawks @ AquaSox

Follow on MiLB First Pitch  https //stza.co/+vO59-v

Shop  https //stza.co/+vO59-1Q

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Hawks @ AquaSox
END:VALARM
DTSTART:20180805T020500Z
DTEND:20180805T050500Z
UID:b8fdE9d_xjBxxWL4vbfQ3Utj@stanza.co
SUMMARY:Hawks @ AquaSox
DESCRIPTION:Hawks @ AquaSox\n\nFollow on MiLB First Pitch: https://stza.co/+vO59-v\n\nShop: https://stza.co/+vO59-1Q\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144507Z
LAST-MODIFIED:20180213T144507Z
TRANSP:OPAQUE
END:VEVENT
* Hawks @ AquaSox
<2018-08-05 Sun 18:05-21:05>
:PROPERTIES:
:ID:       LvZaEPAgH3VQs0QcDzd2rY-N@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Hawks @ AquaSox Hawks @ AquaSox

Follow on MiLB First Pitch  https //stza.co/+vO5a-3X

Shop  https //stza.co/+vO5a-T

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Hawks @ AquaSox
END:VALARM
DTSTART:20180805T230500Z
DTEND:20180806T020500Z
UID:LvZaEPAgH3VQs0QcDzd2rY-N@stanza.co
SUMMARY:Hawks @ AquaSox
DESCRIPTION:Hawks @ AquaSox\n\nFollow on MiLB First Pitch: https://stza.co/+vO5a-3X\n\nShop: https://stza.co/+vO5a-T\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144507Z
LAST-MODIFIED:20180213T144507Z
TRANSP:OPAQUE
END:VEVENT
* Hawks vs. Indians
<2018-08-09 Thu 20:15-23:15>
:PROPERTIES:
:ID:       1g5SjQh1F6-87HQez-Qw4Shu@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Hawks vs. Indians Hawks vs. Indians

Follow on MiLB First Pitch  https //stza.co/+xC4n-1w

Shop  https //stza.co/+xC4n-1Q

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Hawks vs. Indians
END:VALARM
DTSTART:20180810T011500Z
DTEND:20180810T041500Z
UID:1g5SjQh1F6-87HQez-Qw4Shu@stanza.co
SUMMARY:Hawks vs. Indians
DESCRIPTION:Hawks vs. Indians\n\nFollow on MiLB First Pitch: https://stza.co/+xC4n-1w\n\nShop: https://stza.co/+xC4n-1Q\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144507Z
LAST-MODIFIED:20180213T144507Z
TRANSP:OPAQUE
END:VEVENT
* Hawks vs. Indians
<2018-08-10 Fri 20:15-23:15>
:PROPERTIES:
:ID:       iggy4V1zotu_loJ5AYGkrWHT@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Hawks vs. Indians Hawks vs. Indians

Follow on MiLB First Pitch  https //stza.co/+xC4s-1r

Shop  https //stza.co/+xC4s-1V

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Hawks vs. Indians
END:VALARM
DTSTART:20180811T011500Z
DTEND:20180811T041500Z
UID:iggy4V1zotu_loJ5AYGkrWHT@stanza.co
SUMMARY:Hawks vs. Indians
DESCRIPTION:Hawks vs. Indians\n\nFollow on MiLB First Pitch: https://stza.co/+xC4s-1r\n\nShop: https://stza.co/+xC4s-1V\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144507Z
LAST-MODIFIED:20180213T144507Z
TRANSP:OPAQUE
END:VEVENT
* Hawks vs. Indians
<2018-08-11 Sat 20:15-23:15>
:PROPERTIES:
:ID:       qDD7CilwR9_Ws9UjSc7SNctP@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Hawks vs. Indians Hawks vs. Indians

Follow on MiLB First Pitch  https //stza.co/+xC4x-2J

Shop  https //stza.co/+xC4x-27

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Hawks vs. Indians
END:VALARM
DTSTART:20180812T011500Z
DTEND:20180812T041500Z
UID:qDD7CilwR9_Ws9UjSc7SNctP@stanza.co
SUMMARY:Hawks vs. Indians
DESCRIPTION:Hawks vs. Indians\n\nFollow on MiLB First Pitch: https://stza.co/+xC4x-2J\n\nShop: https://stza.co/+xC4x-27\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144507Z
LAST-MODIFIED:20180213T144507Z
TRANSP:OPAQUE
END:VEVENT
* Hawks vs. Indians
<2018-08-12 Sun 18:15-21:15>
:PROPERTIES:
:ID:       p08Vq9vVwL2GsQ9vWvv1JOkS@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Hawks vs. Indians Hawks vs. Indians

Follow on MiLB First Pitch  https //stza.co/+xC4D-3Y

Shop  https //stza.co/+xC4D-l

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Hawks vs. Indians
END:VALARM
DTSTART:20180812T231500Z
DTEND:20180813T021500Z
UID:p08Vq9vVwL2GsQ9vWvv1JOkS@stanza.co
SUMMARY:Hawks vs. Indians
DESCRIPTION:Hawks vs. Indians\n\nFollow on MiLB First Pitch: https://stza.co/+xC4D-3Y\n\nShop: https://stza.co/+xC4D-l\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144507Z
LAST-MODIFIED:20180213T144507Z
TRANSP:OPAQUE
END:VEVENT
* Hawks vs. Indians
<2018-08-13 Mon 20:15-23:15>
:PROPERTIES:
:ID:       5ORXLGJ2Z8Cdc_81wzyrqH28@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Hawks vs. Indians Hawks vs. Indians

Follow on MiLB First Pitch  https //stza.co/+xC4J-1i

Shop  https //stza.co/+xC4J-3I

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Hawks vs. Indians
END:VALARM
DTSTART:20180814T011500Z
DTEND:20180814T041500Z
UID:5ORXLGJ2Z8Cdc_81wzyrqH28@stanza.co
SUMMARY:Hawks vs. Indians
DESCRIPTION:Hawks vs. Indians\n\nFollow on MiLB First Pitch: https://stza.co/+xC4J-1i\n\nShop: https://stza.co/+xC4J-3I\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144507Z
LAST-MODIFIED:20180213T144507Z
TRANSP:OPAQUE
END:VEVENT
* Hawks vs. Volcanoes
<2018-08-14 Tue 20:15-23:15>
:PROPERTIES:
:ID:       52o_RtcalGfxCSwxAmID1yJt@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Hawks vs. Volcanoes Hawks vs. Volcanoes

Follow on MiLB First Pitch  https //stza.co/+xC4M-37

Shop  https //stza.co/+xC4M-1e

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Hawks vs. Volcanoes
END:VALARM
DTSTART:20180815T011500Z
DTEND:20180815T041500Z
UID:52o_RtcalGfxCSwxAmID1yJt@stanza.co
SUMMARY:Hawks vs. Volcanoes
DESCRIPTION:Hawks vs. Volcanoes\n\nFollow on MiLB First Pitch: https://stza.co/+xC4M-37\n\nShop: https://stza.co/+xC4M-1e\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144507Z
LAST-MODIFIED:20180213T144507Z
TRANSP:OPAQUE
END:VEVENT
* Hawks vs. Volcanoes
<2018-08-15 Wed 20:15-23:15>
:PROPERTIES:
:ID:       L2bBZqoJCOayuM_VT59Xx_Ma@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Hawks vs. Volcanoes Hawks vs. Volcanoes

Follow on MiLB First Pitch  https //stza.co/+xC4R-14

Shop  https //stza.co/+xC4R-3A

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Hawks vs. Volcanoes
END:VALARM
DTSTART:20180816T011500Z
DTEND:20180816T041500Z
UID:L2bBZqoJCOayuM_VT59Xx_Ma@stanza.co
SUMMARY:Hawks vs. Volcanoes
DESCRIPTION:Hawks vs. Volcanoes\n\nFollow on MiLB First Pitch: https://stza.co/+xC4R-14\n\nShop: https://stza.co/+xC4R-3A\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144507Z
LAST-MODIFIED:20180213T144507Z
TRANSP:OPAQUE
END:VEVENT
* Hawks vs. Volcanoes
<2018-08-16 Thu 20:15-23:15>
:PROPERTIES:
:ID:       Es3p2O_Mhe9LpG67Y_MnRKtz@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Hawks vs. Volcanoes Hawks vs. Volcanoes

Follow on MiLB First Pitch  https //stza.co/+xC4W-3E

Shop  https //stza.co/+xC4W-1_

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Hawks vs. Volcanoes
END:VALARM
DTSTART:20180817T011500Z
DTEND:20180817T041500Z
UID:Es3p2O_Mhe9LpG67Y_MnRKtz@stanza.co
SUMMARY:Hawks vs. Volcanoes
DESCRIPTION:Hawks vs. Volcanoes\n\nFollow on MiLB First Pitch: https://stza.co/+xC4W-3E\n\nShop: https://stza.co/+xC4W-1_\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144507Z
LAST-MODIFIED:20180213T144507Z
TRANSP:OPAQUE
END:VEVENT
* Hawks @ Emeralds
<2018-08-17 Fri 21:05>--<2018-08-18 Sat 00:05>
:PROPERTIES:
:ID:       QhO4PzjfvgP1A_iLddqrgrVq@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Hawks @ Emeralds Hawks @ Emeralds

Follow on MiLB First Pitch  https //stza.co/+xWO0-33

Shop  https //stza.co/+xWO0-25

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Hawks @ Emeralds
END:VALARM
DTSTART:20180818T020500Z
DTEND:20180818T050500Z
UID:QhO4PzjfvgP1A_iLddqrgrVq@stanza.co
SUMMARY:Hawks @ Emeralds
DESCRIPTION:Hawks @ Emeralds\n\nFollow on MiLB First Pitch: https://stza.co/+xWO0-33\n\nShop: https://stza.co/+xWO0-25\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144507Z
LAST-MODIFIED:20180213T144507Z
TRANSP:OPAQUE
END:VEVENT
* Hawks @ Emeralds
<2018-08-18 Sat 21:05>--<2018-08-19 Sun 00:05>
:PROPERTIES:
:ID:       wEMHkSqBEpk7iTYT3R9Zr97R@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Hawks @ Emeralds Hawks @ Emeralds

Follow on MiLB First Pitch  https //stza.co/+xWO1-Z

Shop  https //stza.co/+xWO1-1I

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Hawks @ Emeralds
END:VALARM
DTSTART:20180819T020500Z
DTEND:20180819T050500Z
UID:wEMHkSqBEpk7iTYT3R9Zr97R@stanza.co
SUMMARY:Hawks @ Emeralds
DESCRIPTION:Hawks @ Emeralds\n\nFollow on MiLB First Pitch: https://stza.co/+xWO1-Z\n\nShop: https://stza.co/+xWO1-1I\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144507Z
LAST-MODIFIED:20180213T144507Z
TRANSP:OPAQUE
END:VEVENT
* Hawks @ Emeralds
<2018-08-19 Sun 19:05-22:05>
:PROPERTIES:
:ID:       L4JmwepOwYwdDVnP4K2wGMYR@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Hawks @ Emeralds Hawks @ Emeralds

Follow on MiLB First Pitch  https //stza.co/+xWO2-1v

Shop  https //stza.co/+xWO2-26

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Hawks @ Emeralds
END:VALARM
DTSTART:20180820T000500Z
DTEND:20180820T030500Z
UID:L4JmwepOwYwdDVnP4K2wGMYR@stanza.co
SUMMARY:Hawks @ Emeralds
DESCRIPTION:Hawks @ Emeralds\n\nFollow on MiLB First Pitch: https://stza.co/+xWO2-1v\n\nShop: https://stza.co/+xWO2-26\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144507Z
LAST-MODIFIED:20180213T144507Z
TRANSP:OPAQUE
END:VEVENT
* Hawks @ Volcanoes
<2018-08-20 Mon>--<2018-08-19 Sun>
:PROPERTIES:
:ID:       5GGUhcAKiPUYsh80J-ifPdx0@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Hawks @ Volcanoes Hawks @ Volcanoes

Follow on MiLB First Pitch  https //stza.co/+vO5k-1b

Shop  https //stza.co/+vO5k-3d

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Hawks @ Volcanoes
END:VALARM
DTSTART;VALUE=DATE:20180820
DTEND;VALUE=DATE:20180820
UID:5GGUhcAKiPUYsh80J-ifPdx0@stanza.co
SUMMARY:Hawks @ Volcanoes
DESCRIPTION:Hawks @ Volcanoes\n\nFollow on MiLB First Pitch: https://stza.co/+vO5k-1b\n\nShop: https://stza.co/+vO5k-3d\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144507Z
LAST-MODIFIED:20180213T144507Z
TRANSP:OPAQUE
END:VEVENT
* Hawks @ Volcanoes
<2018-08-21 Tue>--<2018-08-20 Mon>
:PROPERTIES:
:ID:       YN1AYpTY5CXI-sSZcS8Uza5Y@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Hawks @ Volcanoes Hawks @ Volcanoes

Follow on MiLB First Pitch  https //stza.co/+vO5l-2b

Shop  https //stza.co/+vO5l-2K

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Hawks @ Volcanoes
END:VALARM
DTSTART;VALUE=DATE:20180821
DTEND;VALUE=DATE:20180821
UID:YN1AYpTY5CXI-sSZcS8Uza5Y@stanza.co
SUMMARY:Hawks @ Volcanoes
DESCRIPTION:Hawks @ Volcanoes\n\nFollow on MiLB First Pitch: https://stza.co/+vO5l-2b\n\nShop: https://stza.co/+vO5l-2K\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144507Z
LAST-MODIFIED:20180213T144507Z
TRANSP:OPAQUE
END:VEVENT
* Hawks @ Volcanoes
<2018-08-22 Wed>--<2018-08-21 Tue>
:PROPERTIES:
:ID:       i35Vhd0VxF7kROy9SNRMsSB0@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Hawks @ Volcanoes Hawks @ Volcanoes

Follow on MiLB First Pitch  https //stza.co/+vO5m-2c

Shop  https //stza.co/+vO5m-3W

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Hawks @ Volcanoes
END:VALARM
DTSTART;VALUE=DATE:20180822
DTEND;VALUE=DATE:20180822
UID:i35Vhd0VxF7kROy9SNRMsSB0@stanza.co
SUMMARY:Hawks @ Volcanoes
DESCRIPTION:Hawks @ Volcanoes\n\nFollow on MiLB First Pitch: https://stza.co/+vO5m-2c\n\nShop: https://stza.co/+vO5m-3W\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144507Z
LAST-MODIFIED:20180213T144507Z
TRANSP:OPAQUE
END:VEVENT
* Hawks @ Canadians
<2018-08-23 Thu 21:05>--<2018-08-24 Fri 00:05>
:PROPERTIES:
:ID:       ohlhiQ0INEsMIgHH5KjfkhMP@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Hawks @ Canadians Hawks @ Canadians

Follow on MiLB First Pitch  https //stza.co/+xXUx-2j

Shop  https //stza.co/+xXUx-B

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Hawks @ Canadians
END:VALARM
DTSTART:20180824T020500Z
DTEND:20180824T050500Z
UID:ohlhiQ0INEsMIgHH5KjfkhMP@stanza.co
SUMMARY:Hawks @ Canadians
DESCRIPTION:Hawks @ Canadians\n\nFollow on MiLB First Pitch: https://stza.co/+xXUx-2j\n\nShop: https://stza.co/+xXUx-B\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144507Z
LAST-MODIFIED:20180213T144507Z
TRANSP:OPAQUE
END:VEVENT
* Hawks @ Canadians
<2018-08-24 Fri 15:05-18:05>
:PROPERTIES:
:ID:       KCJXFsi4bT1oaVs3dRc4Ka7U@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Hawks @ Canadians Hawks @ Canadians

Follow on MiLB First Pitch  https //stza.co/+xXUy-32

Shop  https //stza.co/+xXUy-37

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Hawks @ Canadians
END:VALARM
DTSTART:20180824T200500Z
DTEND:20180824T230500Z
UID:KCJXFsi4bT1oaVs3dRc4Ka7U@stanza.co
SUMMARY:Hawks @ Canadians
DESCRIPTION:Hawks @ Canadians\n\nFollow on MiLB First Pitch: https://stza.co/+xXUy-32\n\nShop: https://stza.co/+xXUy-37\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144507Z
LAST-MODIFIED:20180213T144507Z
TRANSP:OPAQUE
END:VEVENT
* Hawks @ Canadians
<2018-08-25 Sat 21:05>--<2018-08-26 Sun 00:05>
:PROPERTIES:
:ID:       IYEKsheq2SGW90eD_veEYeiQ@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Hawks @ Canadians Hawks @ Canadians

Follow on MiLB First Pitch  https //stza.co/+xXUz-r

Shop  https //stza.co/+xXUz-W

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Hawks @ Canadians
END:VALARM
DTSTART:20180826T020500Z
DTEND:20180826T050500Z
UID:IYEKsheq2SGW90eD_veEYeiQ@stanza.co
SUMMARY:Hawks @ Canadians
DESCRIPTION:Hawks @ Canadians\n\nFollow on MiLB First Pitch: https://stza.co/+xXUz-r\n\nShop: https://stza.co/+xXUz-W\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144507Z
LAST-MODIFIED:20180213T144507Z
TRANSP:OPAQUE
END:VEVENT
* Hawks @ Canadians
<2018-08-26 Sun 15:05-18:05>
:PROPERTIES:
:ID:       H8WWCpiYbhLwaQSZehUcjRws@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Hawks @ Canadians Hawks @ Canadians

Follow on MiLB First Pitch  https //stza.co/+xXUA-1_

Shop  https //stza.co/+xXUA-3H

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Hawks @ Canadians
END:VALARM
DTSTART:20180826T200500Z
DTEND:20180826T230500Z
UID:H8WWCpiYbhLwaQSZehUcjRws@stanza.co
SUMMARY:Hawks @ Canadians
DESCRIPTION:Hawks @ Canadians\n\nFollow on MiLB First Pitch: https://stza.co/+xXUA-1_\n\nShop: https://stza.co/+xXUA-3H\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144507Z
LAST-MODIFIED:20180213T144507Z
TRANSP:OPAQUE
END:VEVENT
* Hawks @ Canadians
<2018-08-27 Mon 21:05>--<2018-08-28 Tue 00:05>
:PROPERTIES:
:ID:       _pRqr_511hpPKwllW6CB1VvQ@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Hawks @ Canadians Hawks @ Canadians

Follow on MiLB First Pitch  https //stza.co/+xXUB-27

Shop  https //stza.co/+xXUB-14

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Hawks @ Canadians
END:VALARM
DTSTART:20180828T020500Z
DTEND:20180828T050500Z
UID:_pRqr_511hpPKwllW6CB1VvQ@stanza.co
SUMMARY:Hawks @ Canadians
DESCRIPTION:Hawks @ Canadians\n\nFollow on MiLB First Pitch: https://stza.co/+xXUB-27\n\nShop: https://stza.co/+xXUB-14\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144507Z
LAST-MODIFIED:20180213T144507Z
TRANSP:OPAQUE
END:VEVENT
* Hawks vs. Hops
<2018-08-29 Wed 20:15-23:15>
:PROPERTIES:
:ID:       awU3DpCnGuNJ2CK1WYTHrOy0@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Hawks vs. Hops Hawks vs. Hops

Follow on MiLB First Pitch  https //stza.co/+xC50-2E

Shop  https //stza.co/+xC50-2z

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Hawks vs. Hops
END:VALARM
DTSTART:20180830T011500Z
DTEND:20180830T041500Z
UID:awU3DpCnGuNJ2CK1WYTHrOy0@stanza.co
SUMMARY:Hawks vs. Hops
DESCRIPTION:Hawks vs. Hops\n\nFollow on MiLB First Pitch: https://stza.co/+xC50-2E\n\nShop: https://stza.co/+xC50-2z\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144507Z
LAST-MODIFIED:20180213T144507Z
TRANSP:OPAQUE
END:VEVENT
* Hawks vs. Hops
<2018-08-30 Thu 20:15-23:15>
:PROPERTIES:
:ID:       g5Ntt4CmIVWAHbom6T9yOMMA@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Hawks vs. Hops Hawks vs. Hops

Follow on MiLB First Pitch  https //stza.co/+xC56-2S

Shop  https //stza.co/+xC56-1q

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Hawks vs. Hops
END:VALARM
DTSTART:20180831T011500Z
DTEND:20180831T041500Z
UID:g5Ntt4CmIVWAHbom6T9yOMMA@stanza.co
SUMMARY:Hawks vs. Hops
DESCRIPTION:Hawks vs. Hops\n\nFollow on MiLB First Pitch: https://stza.co/+xC56-2S\n\nShop: https://stza.co/+xC56-1q\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144507Z
LAST-MODIFIED:20180213T144507Z
TRANSP:OPAQUE
END:VEVENT
* Hawks vs. Hops
<2018-08-31 Fri 20:15-23:15>
:PROPERTIES:
:ID:       TdNltYcLmxXkboQfqp4_RYTW@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Hawks vs. Hops Hawks vs. Hops

Follow on MiLB First Pitch  https //stza.co/+xC5d-X

Shop  https //stza.co/+xC5d-2M

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Hawks vs. Hops
END:VALARM
DTSTART:20180901T011500Z
DTEND:20180901T041500Z
UID:TdNltYcLmxXkboQfqp4_RYTW@stanza.co
SUMMARY:Hawks vs. Hops
DESCRIPTION:Hawks vs. Hops\n\nFollow on MiLB First Pitch: https://stza.co/+xC5d-X\n\nShop: https://stza.co/+xC5d-2M\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144507Z
LAST-MODIFIED:20180213T144507Z
TRANSP:OPAQUE
END:VEVENT
* Hawks vs. Emeralds
<2018-09-01 Sat 20:15-23:15>
:PROPERTIES:
:ID:       kHqbQDohyNRQkSEREoKpZmwM@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Hawks vs. Emeralds Hawks vs. Emeralds

Follow on MiLB First Pitch  https //stza.co/+xC5k-1U

Shop  https //stza.co/+xC5k-1o

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Hawks vs. Emeralds
END:VALARM
DTSTART:20180902T011500Z
DTEND:20180902T041500Z
UID:kHqbQDohyNRQkSEREoKpZmwM@stanza.co
SUMMARY:Hawks vs. Emeralds
DESCRIPTION:Hawks vs. Emeralds\n\nFollow on MiLB First Pitch: https://stza.co/+xC5k-1U\n\nShop: https://stza.co/+xC5k-1o\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144507Z
LAST-MODIFIED:20180213T144507Z
TRANSP:OPAQUE
END:VEVENT
* Hawks vs. Emeralds
<2018-09-02 Sun 20:15-23:15>
:PROPERTIES:
:ID:       -vztpXGQSMERNB12Umh4zgiV@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Hawks vs. Emeralds Hawks vs. Emeralds

Follow on MiLB First Pitch  https //stza.co/+xC5r-3i

Shop  https //stza.co/+xC5r-1y

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Hawks vs. Emeralds
END:VALARM
DTSTART:20180903T011500Z
DTEND:20180903T041500Z
UID:-vztpXGQSMERNB12Umh4zgiV@stanza.co
SUMMARY:Hawks vs. Emeralds
DESCRIPTION:Hawks vs. Emeralds\n\nFollow on MiLB First Pitch: https://stza.co/+xC5r-3i\n\nShop: https://stza.co/+xC5r-1y\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144507Z
LAST-MODIFIED:20180213T144507Z
TRANSP:OPAQUE
END:VEVENT
* Hawks vs. Emeralds
<2018-09-03 Mon 18:15-21:15>
:PROPERTIES:
:ID:       dBrfm-ahgxkKkHrSRHwMukUs@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Hawks vs. Emeralds Hawks vs. Emeralds

Follow on MiLB First Pitch  https //stza.co/+xC5u-2p

Shop  https //stza.co/+xC5u-2N

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Hawks vs. Emeralds
END:VALARM
DTSTART:20180903T231500Z
DTEND:20180904T021500Z
UID:dBrfm-ahgxkKkHrSRHwMukUs@stanza.co
SUMMARY:Hawks vs. Emeralds
DESCRIPTION:Hawks vs. Emeralds\n\nFollow on MiLB First Pitch: https://stza.co/+xC5u-2p\n\nShop: https://stza.co/+xC5u-2N\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144507Z
LAST-MODIFIED:20180213T144507Z
TRANSP:OPAQUE
END:VEVENT
