#+TITLE:       Main Google calendar entries
#+AUTHOR:      Eric S Fraga
#+EMAIL:       e.fraga@ucl.ac.uk
#+DESCRIPTION: converted using the ical2org awk script
#+CATEGORY:    google
#+STARTUP:     hidestars
#+STARTUP:     overview

* COMMENT original iCal preamble

* Suns @ Braves
<2018-04-05 Thu 18:00-21:00>
:PROPERTIES:
:ID:       c8afdXrjlwmKoGQsjpxWWJd6@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Suns @ Braves Suns @ Braves

Follow on MiLB First Pitch  https //stza.co/+vNM4-1z

Shop  https //stza.co/+vNM4-1_

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Suns @ Braves
END:VALARM
DTSTART:20180405T230000Z
DTEND:20180406T020000Z
UID:c8afdXrjlwmKoGQsjpxWWJd6@stanza.co
SUMMARY:Suns @ Braves
DESCRIPTION:Suns @ Braves\n\nFollow on MiLB First Pitch: https://stza.co/+vNM4-1z\n\nShop: https://stza.co/+vNM4-1_\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144530Z
LAST-MODIFIED:20180213T144530Z
TRANSP:OPAQUE
END:VEVENT
* Suns @ Braves
<2018-04-06 Fri 18:00-21:00>
:PROPERTIES:
:ID:       aGr0ykWimbQJX_fHzmsaHmmJ@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Suns @ Braves Suns @ Braves

Follow on MiLB First Pitch  https //stza.co/+vNM5-37

Shop  https //stza.co/+vNM5-3t

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Suns @ Braves
END:VALARM
DTSTART:20180406T230000Z
DTEND:20180407T020000Z
UID:aGr0ykWimbQJX_fHzmsaHmmJ@stanza.co
SUMMARY:Suns @ Braves
DESCRIPTION:Suns @ Braves\n\nFollow on MiLB First Pitch: https://stza.co/+vNM5-37\n\nShop: https://stza.co/+vNM5-3t\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144530Z
LAST-MODIFIED:20180213T144530Z
TRANSP:OPAQUE
END:VEVENT
* Suns @ Braves
<2018-04-07 Sat 17:00-20:00>
:PROPERTIES:
:ID:       oF_9LEBIgzGaiNkLRTvGSEBK@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Suns @ Braves Suns @ Braves

Follow on MiLB First Pitch  https //stza.co/+vNM6-1m

Shop  https //stza.co/+vNM6-22

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Suns @ Braves
END:VALARM
DTSTART:20180407T220000Z
DTEND:20180408T010000Z
UID:oF_9LEBIgzGaiNkLRTvGSEBK@stanza.co
SUMMARY:Suns @ Braves
DESCRIPTION:Suns @ Braves\n\nFollow on MiLB First Pitch: https://stza.co/+vNM6-1m\n\nShop: https://stza.co/+vNM6-22\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144530Z
LAST-MODIFIED:20180213T144530Z
TRANSP:OPAQUE
END:VEVENT
* Suns @ Braves
<2018-04-08 Sun 13:00-16:00>
:PROPERTIES:
:ID:       st9KoiCHWFNEe0eMp91F5cFG@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Suns @ Braves Suns @ Braves

Follow on MiLB First Pitch  https //stza.co/+vNM7-18

Shop  https //stza.co/+vNM7-3e

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Suns @ Braves
END:VALARM
DTSTART:20180408T180000Z
DTEND:20180408T210000Z
UID:st9KoiCHWFNEe0eMp91F5cFG@stanza.co
SUMMARY:Suns @ Braves
DESCRIPTION:Suns @ Braves\n\nFollow on MiLB First Pitch: https://stza.co/+vNM7-18\n\nShop: https://stza.co/+vNM7-3e\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144530Z
LAST-MODIFIED:20180213T144530Z
TRANSP:OPAQUE
END:VEVENT
* Suns @ Fireflies
<2018-04-09 Mon 18:05-21:05>
:PROPERTIES:
:ID:       _z0I6hGN7tMFUmSbUyB8JeVr@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Suns @ Fireflies Suns @ Fireflies

Follow on MiLB First Pitch  https //stza.co/+xB3U-2c

Shop  https //stza.co/+xB3U-3V

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Suns @ Fireflies
END:VALARM
DTSTART:20180409T230500Z
DTEND:20180410T020500Z
UID:_z0I6hGN7tMFUmSbUyB8JeVr@stanza.co
SUMMARY:Suns @ Fireflies
DESCRIPTION:Suns @ Fireflies\n\nFollow on MiLB First Pitch: https://stza.co/+xB3U-2c\n\nShop: https://stza.co/+xB3U-3V\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144530Z
LAST-MODIFIED:20180213T144530Z
TRANSP:OPAQUE
END:VEVENT
* Suns @ Fireflies
<2018-04-10 Tue 18:05-21:05>
:PROPERTIES:
:ID:       McZtefqZFjVr3y3ctLEkOSqw@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Suns @ Fireflies Suns @ Fireflies

Follow on MiLB First Pitch  https //stza.co/+xB3V-27

Shop  https //stza.co/+xB3V-2

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Suns @ Fireflies
END:VALARM
DTSTART:20180410T230500Z
DTEND:20180411T020500Z
UID:McZtefqZFjVr3y3ctLEkOSqw@stanza.co
SUMMARY:Suns @ Fireflies
DESCRIPTION:Suns @ Fireflies\n\nFollow on MiLB First Pitch: https://stza.co/+xB3V-27\n\nShop: https://stza.co/+xB3V-2\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144530Z
LAST-MODIFIED:20180213T144530Z
TRANSP:OPAQUE
END:VEVENT
* Suns @ Fireflies
<2018-04-11 Wed 18:05-21:05>
:PROPERTIES:
:ID:       Fx-NDzM2vPUh2qv8rwxhqLiV@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Suns @ Fireflies Suns @ Fireflies

Follow on MiLB First Pitch  https //stza.co/+xB3W-a

Shop  https //stza.co/+xB3W-C

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Suns @ Fireflies
END:VALARM
DTSTART:20180411T230500Z
DTEND:20180412T020500Z
UID:Fx-NDzM2vPUh2qv8rwxhqLiV@stanza.co
SUMMARY:Suns @ Fireflies
DESCRIPTION:Suns @ Fireflies\n\nFollow on MiLB First Pitch: https://stza.co/+xB3W-a\n\nShop: https://stza.co/+xB3W-C\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144530Z
LAST-MODIFIED:20180213T144530Z
TRANSP:OPAQUE
END:VEVENT
* Suns vs. Grasshoppers
<2018-04-12 Thu 17:05-20:05>
:PROPERTIES:
:ID:       ZyA_qdQZVlZd8BTOsRAqokmO@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Suns vs. Grasshoppers Suns vs. Grasshoppers

Follow on MiLB First Pitch  https //stza.co/+xGDH-3h

Shop  https //stza.co/+xGDH-1C

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Suns vs. Grasshoppers
END:VALARM
DTSTART:20180412T220500Z
DTEND:20180413T010500Z
UID:ZyA_qdQZVlZd8BTOsRAqokmO@stanza.co
SUMMARY:Suns vs. Grasshoppers
DESCRIPTION:Suns vs. Grasshoppers\n\nFollow on MiLB First Pitch: https://stza.co/+xGDH-3h\n\nShop: https://stza.co/+xGDH-1C\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144530Z
LAST-MODIFIED:20180213T144530Z
TRANSP:OPAQUE
END:VEVENT
* Suns vs. Grasshoppers
<2018-04-13 Fri 17:05-20:05>
:PROPERTIES:
:ID:       Cp1_rTDqRzDZnRRggsaHrLxA@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Suns vs. Grasshoppers Suns vs. Grasshoppers

Follow on MiLB First Pitch  https //stza.co/+xGDJ-3P

Shop  https //stza.co/+xGDJ-3c

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Suns vs. Grasshoppers
END:VALARM
DTSTART:20180413T220500Z
DTEND:20180414T010500Z
UID:Cp1_rTDqRzDZnRRggsaHrLxA@stanza.co
SUMMARY:Suns vs. Grasshoppers
DESCRIPTION:Suns vs. Grasshoppers\n\nFollow on MiLB First Pitch: https://stza.co/+xGDJ-3P\n\nShop: https://stza.co/+xGDJ-3c\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144530Z
LAST-MODIFIED:20180213T144530Z
TRANSP:OPAQUE
END:VEVENT
* Suns vs. Grasshoppers
<2018-04-14 Sat 17:05-20:05>
:PROPERTIES:
:ID:       72Dt_GGoEhKKThI2Ge_5teCY@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Suns vs. Grasshoppers Suns vs. Grasshoppers

Follow on MiLB First Pitch  https //stza.co/+xGDL-S

Shop  https //stza.co/+xGDL-3p

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Suns vs. Grasshoppers
END:VALARM
DTSTART:20180414T220500Z
DTEND:20180415T010500Z
UID:72Dt_GGoEhKKThI2Ge_5teCY@stanza.co
SUMMARY:Suns vs. Grasshoppers
DESCRIPTION:Suns vs. Grasshoppers\n\nFollow on MiLB First Pitch: https://stza.co/+xGDL-S\n\nShop: https://stza.co/+xGDL-3p\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144530Z
LAST-MODIFIED:20180213T144530Z
TRANSP:OPAQUE
END:VEVENT
* Suns vs. Grasshoppers
<2018-04-15 Sun 13:05-16:05>
:PROPERTIES:
:ID:       DKfB6XwU41OhxYZWAZN7ldlQ@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Suns vs. Grasshoppers Suns vs. Grasshoppers

Follow on MiLB First Pitch  https //stza.co/+xGDN-1D

Shop  https //stza.co/+xGDN-H

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Suns vs. Grasshoppers
END:VALARM
DTSTART:20180415T180500Z
DTEND:20180415T210500Z
UID:DKfB6XwU41OhxYZWAZN7ldlQ@stanza.co
SUMMARY:Suns vs. Grasshoppers
DESCRIPTION:Suns vs. Grasshoppers\n\nFollow on MiLB First Pitch: https://stza.co/+xGDN-1D\n\nShop: https://stza.co/+xGDN-H\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144530Z
LAST-MODIFIED:20180213T144530Z
TRANSP:OPAQUE
END:VEVENT
* Suns vs. Shorebirds
<2018-04-16 Mon 17:05-20:05>
:PROPERTIES:
:ID:       MESL7Oismh3KA4lORRf7b8EG@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Suns vs. Shorebirds Suns vs. Shorebirds

Follow on MiLB First Pitch  https //stza.co/+xGDP-1R

Shop  https //stza.co/+xGDP-2b

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Suns vs. Shorebirds
END:VALARM
DTSTART:20180416T220500Z
DTEND:20180417T010500Z
UID:MESL7Oismh3KA4lORRf7b8EG@stanza.co
SUMMARY:Suns vs. Shorebirds
DESCRIPTION:Suns vs. Shorebirds\n\nFollow on MiLB First Pitch: https://stza.co/+xGDP-1R\n\nShop: https://stza.co/+xGDP-2b\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144530Z
LAST-MODIFIED:20180213T144530Z
TRANSP:OPAQUE
END:VEVENT
* Suns vs. Shorebirds
<2018-04-17 Tue 17:05-20:05>
:PROPERTIES:
:ID:       JLKwekHEFUd9Sn6UFP4A2u0C@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Suns vs. Shorebirds Suns vs. Shorebirds

Follow on MiLB First Pitch  https //stza.co/+xGDS-v

Shop  https //stza.co/+xGDS-1G

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Suns vs. Shorebirds
END:VALARM
DTSTART:20180417T220500Z
DTEND:20180418T010500Z
UID:JLKwekHEFUd9Sn6UFP4A2u0C@stanza.co
SUMMARY:Suns vs. Shorebirds
DESCRIPTION:Suns vs. Shorebirds\n\nFollow on MiLB First Pitch: https://stza.co/+xGDS-v\n\nShop: https://stza.co/+xGDS-1G\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144530Z
LAST-MODIFIED:20180213T144530Z
TRANSP:OPAQUE
END:VEVENT
* Suns vs. Shorebirds
<2018-04-18 Wed 09:35-12:35>
:PROPERTIES:
:ID:       9jxND2abqaJMq2k2xV2T_M2T@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Suns vs. Shorebirds Suns vs. Shorebirds

Follow on MiLB First Pitch  https //stza.co/+xGDU-b

Shop  https //stza.co/+xGDU-_

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Suns vs. Shorebirds
END:VALARM
DTSTART:20180418T143500Z
DTEND:20180418T173500Z
UID:9jxND2abqaJMq2k2xV2T_M2T@stanza.co
SUMMARY:Suns vs. Shorebirds
DESCRIPTION:Suns vs. Shorebirds\n\nFollow on MiLB First Pitch: https://stza.co/+xGDU-b\n\nShop: https://stza.co/+xGDU-_\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144530Z
LAST-MODIFIED:20180213T144530Z
TRANSP:OPAQUE
END:VEVENT
* Suns @ Legends
<2018-04-19 Thu 18:05-21:05>
:PROPERTIES:
:ID:       Uo_YktBQnNb3AWJP4RhiAD9M@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Suns @ Legends Suns @ Legends

Follow on MiLB First Pitch  https //stza.co/+xB4d-2W

Shop  https //stza.co/+xB4d-1M

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Suns @ Legends
END:VALARM
DTSTART:20180419T230500Z
DTEND:20180420T020500Z
UID:Uo_YktBQnNb3AWJP4RhiAD9M@stanza.co
SUMMARY:Suns @ Legends
DESCRIPTION:Suns @ Legends\n\nFollow on MiLB First Pitch: https://stza.co/+xB4d-2W\n\nShop: https://stza.co/+xB4d-1M\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144530Z
LAST-MODIFIED:20180213T144530Z
TRANSP:OPAQUE
END:VEVENT
* Suns @ Legends
<2018-04-20 Fri 18:05-21:05>
:PROPERTIES:
:ID:       Rceu-6S8i9zXH4zZr5lKewhu@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Suns @ Legends Suns @ Legends

Follow on MiLB First Pitch  https //stza.co/+xB4e-1I

Shop  https //stza.co/+xB4e-1U

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Suns @ Legends
END:VALARM
DTSTART:20180420T230500Z
DTEND:20180421T020500Z
UID:Rceu-6S8i9zXH4zZr5lKewhu@stanza.co
SUMMARY:Suns @ Legends
DESCRIPTION:Suns @ Legends\n\nFollow on MiLB First Pitch: https://stza.co/+xB4e-1I\n\nShop: https://stza.co/+xB4e-1U\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144530Z
LAST-MODIFIED:20180213T144530Z
TRANSP:OPAQUE
END:VEVENT
* Suns @ Legends
<2018-04-21 Sat 17:35-20:35>
:PROPERTIES:
:ID:       6FL58v3RXqzzXGYBEkwR1n3J@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Suns @ Legends Suns @ Legends

Follow on MiLB First Pitch  https //stza.co/+xB4f-3p

Shop  https //stza.co/+xB4f-K

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Suns @ Legends
END:VALARM
DTSTART:20180421T223500Z
DTEND:20180422T013500Z
UID:6FL58v3RXqzzXGYBEkwR1n3J@stanza.co
SUMMARY:Suns @ Legends
DESCRIPTION:Suns @ Legends\n\nFollow on MiLB First Pitch: https://stza.co/+xB4f-3p\n\nShop: https://stza.co/+xB4f-K\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144530Z
LAST-MODIFIED:20180213T144530Z
TRANSP:OPAQUE
END:VEVENT
* Suns @ Legends
<2018-04-22 Sun 13:05-16:05>
:PROPERTIES:
:ID:       dFOGFqERvOa0VbJ-7UnGo5oU@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Suns @ Legends Suns @ Legends

Follow on MiLB First Pitch  https //stza.co/+xB4g-3P

Shop  https //stza.co/+xB4g-1M

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Suns @ Legends
END:VALARM
DTSTART:20180422T180500Z
DTEND:20180422T210500Z
UID:dFOGFqERvOa0VbJ-7UnGo5oU@stanza.co
SUMMARY:Suns @ Legends
DESCRIPTION:Suns @ Legends\n\nFollow on MiLB First Pitch: https://stza.co/+xB4g-3P\n\nShop: https://stza.co/+xB4g-1M\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144530Z
LAST-MODIFIED:20180213T144530Z
TRANSP:OPAQUE
END:VEVENT
* Suns vs. BlueClaws
<2018-04-23 Mon 17:05-20:05>
:PROPERTIES:
:ID:       fDfyJX87oXAyuy6dHKnrFRCo@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Suns vs. BlueClaws Suns vs. BlueClaws

Follow on MiLB First Pitch  https //stza.co/+xGDW-R

Shop  https //stza.co/+xGDW-1F

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Suns vs. BlueClaws
END:VALARM
DTSTART:20180423T220500Z
DTEND:20180424T010500Z
UID:fDfyJX87oXAyuy6dHKnrFRCo@stanza.co
SUMMARY:Suns vs. BlueClaws
DESCRIPTION:Suns vs. BlueClaws\n\nFollow on MiLB First Pitch: https://stza.co/+xGDW-R\n\nShop: https://stza.co/+xGDW-1F\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144530Z
LAST-MODIFIED:20180213T144530Z
TRANSP:OPAQUE
END:VEVENT
* Suns vs. BlueClaws
<2018-04-24 Tue 17:05-20:05>
:PROPERTIES:
:ID:       1Q-oL_SS5VrfaGjJLe-pTVAA@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Suns vs. BlueClaws Suns vs. BlueClaws

Follow on MiLB First Pitch  https //stza.co/+xGDY-1c

Shop  https //stza.co/+xGDY-1q

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Suns vs. BlueClaws
END:VALARM
DTSTART:20180424T220500Z
DTEND:20180425T010500Z
UID:1Q-oL_SS5VrfaGjJLe-pTVAA@stanza.co
SUMMARY:Suns vs. BlueClaws
DESCRIPTION:Suns vs. BlueClaws\n\nFollow on MiLB First Pitch: https://stza.co/+xGDY-1c\n\nShop: https://stza.co/+xGDY-1q\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144530Z
LAST-MODIFIED:20180213T144530Z
TRANSP:OPAQUE
END:VEVENT
* Suns vs. BlueClaws
<2018-04-25 Wed 17:05-20:05>
:PROPERTIES:
:ID:       QuThVMPRpt2gpNLktVt9wgBO@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Suns vs. BlueClaws Suns vs. BlueClaws

Follow on MiLB First Pitch  https //stza.co/+xGD$-u

Shop  https //stza.co/+xGD$-2m

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Suns vs. BlueClaws
END:VALARM
DTSTART:20180425T220500Z
DTEND:20180426T010500Z
UID:QuThVMPRpt2gpNLktVt9wgBO@stanza.co
SUMMARY:Suns vs. BlueClaws
DESCRIPTION:Suns vs. BlueClaws\n\nFollow on MiLB First Pitch: https://stza.co/+xGD$-u\n\nShop: https://stza.co/+xGD$-2m\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144530Z
LAST-MODIFIED:20180213T144530Z
TRANSP:OPAQUE
END:VEVENT
* Suns vs. BlueClaws
<2018-04-26 Thu 17:05-20:05>
:PROPERTIES:
:ID:       2W8dzI9Y_56N_Czn2v1aW1bh@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Suns vs. BlueClaws Suns vs. BlueClaws

Follow on MiLB First Pitch  https //stza.co/+xGE0-1t

Shop  https //stza.co/+xGE0-13

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Suns vs. BlueClaws
END:VALARM
DTSTART:20180426T220500Z
DTEND:20180427T010500Z
UID:2W8dzI9Y_56N_Czn2v1aW1bh@stanza.co
SUMMARY:Suns vs. BlueClaws
DESCRIPTION:Suns vs. BlueClaws\n\nFollow on MiLB First Pitch: https://stza.co/+xGE0-1t\n\nShop: https://stza.co/+xGE0-13\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144530Z
LAST-MODIFIED:20180213T144530Z
TRANSP:OPAQUE
END:VEVENT
* Suns vs. Braves
<2018-04-27 Fri 17:05-20:05>
:PROPERTIES:
:ID:       DToRgAmJmNqnq3k_yEVhfLwY@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Suns vs. Braves Suns vs. Braves

Follow on MiLB First Pitch  https //stza.co/+xGE3-8

Shop  https //stza.co/+xGE3-3t

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Suns vs. Braves
END:VALARM
DTSTART:20180427T220500Z
DTEND:20180428T010500Z
UID:DToRgAmJmNqnq3k_yEVhfLwY@stanza.co
SUMMARY:Suns vs. Braves
DESCRIPTION:Suns vs. Braves\n\nFollow on MiLB First Pitch: https://stza.co/+xGE3-8\n\nShop: https://stza.co/+xGE3-3t\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144530Z
LAST-MODIFIED:20180213T144530Z
TRANSP:OPAQUE
END:VEVENT
* Suns vs. Braves
<2018-04-28 Sat 17:05-20:05>
:PROPERTIES:
:ID:       VbiZtRESEvWGKtPnRunpdz-n@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Suns vs. Braves Suns vs. Braves

Follow on MiLB First Pitch  https //stza.co/+xGE4-I

Shop  https //stza.co/+xGE4-2r

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Suns vs. Braves
END:VALARM
DTSTART:20180428T220500Z
DTEND:20180429T010500Z
UID:VbiZtRESEvWGKtPnRunpdz-n@stanza.co
SUMMARY:Suns vs. Braves
DESCRIPTION:Suns vs. Braves\n\nFollow on MiLB First Pitch: https://stza.co/+xGE4-I\n\nShop: https://stza.co/+xGE4-2r\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144530Z
LAST-MODIFIED:20180213T144530Z
TRANSP:OPAQUE
END:VEVENT
* Suns vs. Braves
<2018-04-29 Sun 13:05-16:05>
:PROPERTIES:
:ID:       ah1GWo54huBAN9Pz4zzIwzI_@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Suns vs. Braves Suns vs. Braves

Follow on MiLB First Pitch  https //stza.co/+xGE7-1v

Shop  https //stza.co/+xGE7-1s

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Suns vs. Braves
END:VALARM
DTSTART:20180429T180500Z
DTEND:20180429T210500Z
UID:ah1GWo54huBAN9Pz4zzIwzI_@stanza.co
SUMMARY:Suns vs. Braves
DESCRIPTION:Suns vs. Braves\n\nFollow on MiLB First Pitch: https://stza.co/+xGE7-1v\n\nShop: https://stza.co/+xGE7-1s\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144530Z
LAST-MODIFIED:20180213T144530Z
TRANSP:OPAQUE
END:VEVENT
* Suns @ Grasshoppers
<2018-05-01 Tue 18:00-21:00>
:PROPERTIES:
:ID:       TbyRbPVPChlrHyf65RFJVibV@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Suns @ Grasshoppers Suns @ Grasshoppers

Follow on MiLB First Pitch  https //stza.co/+wizh-O

Shop  https //stza.co/+wizh-3z

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Suns @ Grasshoppers
END:VALARM
DTSTART:20180501T230000Z
DTEND:20180502T020000Z
UID:TbyRbPVPChlrHyf65RFJVibV@stanza.co
SUMMARY:Suns @ Grasshoppers
DESCRIPTION:Suns @ Grasshoppers\n\nFollow on MiLB First Pitch: https://stza.co/+wizh-O\n\nShop: https://stza.co/+wizh-3z\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144530Z
LAST-MODIFIED:20180213T144530Z
TRANSP:OPAQUE
END:VEVENT
* Suns @ Grasshoppers
<2018-05-02 Wed 11:00-14:00>
:PROPERTIES:
:ID:       37mzO7CRNq6A2FsdDzwpMzCR@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Suns @ Grasshoppers Suns @ Grasshoppers

Follow on MiLB First Pitch  https //stza.co/+wizi-1

Shop  https //stza.co/+wizi-K

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Suns @ Grasshoppers
END:VALARM
DTSTART:20180502T160000Z
DTEND:20180502T190000Z
UID:37mzO7CRNq6A2FsdDzwpMzCR@stanza.co
SUMMARY:Suns @ Grasshoppers
DESCRIPTION:Suns @ Grasshoppers\n\nFollow on MiLB First Pitch: https://stza.co/+wizi-1\n\nShop: https://stza.co/+wizi-K\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144530Z
LAST-MODIFIED:20180213T144530Z
TRANSP:OPAQUE
END:VEVENT
* Suns @ Grasshoppers
<2018-05-03 Thu 18:00-21:00>
:PROPERTIES:
:ID:       fgw8c3-9kpC81beKx9z5Mpgu@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Suns @ Grasshoppers Suns @ Grasshoppers

Follow on MiLB First Pitch  https //stza.co/+wizj-1u

Shop  https //stza.co/+wizj-2a

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Suns @ Grasshoppers
END:VALARM
DTSTART:20180503T230000Z
DTEND:20180504T020000Z
UID:fgw8c3-9kpC81beKx9z5Mpgu@stanza.co
SUMMARY:Suns @ Grasshoppers
DESCRIPTION:Suns @ Grasshoppers\n\nFollow on MiLB First Pitch: https://stza.co/+wizj-1u\n\nShop: https://stza.co/+wizj-2a\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144530Z
LAST-MODIFIED:20180213T144530Z
TRANSP:OPAQUE
END:VEVENT
* Suns @ Intimidators
<2018-05-04 Fri 18:05-21:05>
:PROPERTIES:
:ID:       1BKsucoKOYmLxlDY2doYxSey@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Suns @ Intimidators Suns @ Intimidators

Follow on MiLB First Pitch  https //stza.co/+wICA-2F

Shop  https //stza.co/+wICA-Z

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Suns @ Intimidators
END:VALARM
DTSTART:20180504T230500Z
DTEND:20180505T020500Z
UID:1BKsucoKOYmLxlDY2doYxSey@stanza.co
SUMMARY:Suns @ Intimidators
DESCRIPTION:Suns @ Intimidators\n\nFollow on MiLB First Pitch: https://stza.co/+wICA-2F\n\nShop: https://stza.co/+wICA-Z\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144530Z
LAST-MODIFIED:20180213T144530Z
TRANSP:OPAQUE
END:VEVENT
* Suns @ Intimidators
<2018-05-05 Sat 18:05-21:05>
:PROPERTIES:
:ID:       RA2F4G9FihLtu8YkTMMQrFJw@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Suns @ Intimidators Suns @ Intimidators

Follow on MiLB First Pitch  https //stza.co/+wICB-2s

Shop  https //stza.co/+wICB-T

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Suns @ Intimidators
END:VALARM
DTSTART:20180505T230500Z
DTEND:20180506T020500Z
UID:RA2F4G9FihLtu8YkTMMQrFJw@stanza.co
SUMMARY:Suns @ Intimidators
DESCRIPTION:Suns @ Intimidators\n\nFollow on MiLB First Pitch: https://stza.co/+wICB-2s\n\nShop: https://stza.co/+wICB-T\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144530Z
LAST-MODIFIED:20180213T144530Z
TRANSP:OPAQUE
END:VEVENT
* Suns @ Intimidators
<2018-05-06 Sun 14:35-17:35>
:PROPERTIES:
:ID:       WOpKg12MNVtF7kB_JnItTUdd@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Suns @ Intimidators Suns @ Intimidators

Follow on MiLB First Pitch  https //stza.co/+wICC-3u

Shop  https //stza.co/+wICC-3k

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Suns @ Intimidators
END:VALARM
DTSTART:20180506T193500Z
DTEND:20180506T223500Z
UID:WOpKg12MNVtF7kB_JnItTUdd@stanza.co
SUMMARY:Suns @ Intimidators
DESCRIPTION:Suns @ Intimidators\n\nFollow on MiLB First Pitch: https://stza.co/+wICC-3u\n\nShop: https://stza.co/+wICC-3k\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144530Z
LAST-MODIFIED:20180213T144530Z
TRANSP:OPAQUE
END:VEVENT
* Suns @ Intimidators
<2018-05-07 Mon 09:05-12:05>
:PROPERTIES:
:ID:       cKOVJ1D0KYuyElOGugmsAEhO@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Suns @ Intimidators Suns @ Intimidators

Follow on MiLB First Pitch  https //stza.co/+wICD-5

Shop  https //stza.co/+wICD-1A

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Suns @ Intimidators
END:VALARM
DTSTART:20180507T140500Z
DTEND:20180507T170500Z
UID:cKOVJ1D0KYuyElOGugmsAEhO@stanza.co
SUMMARY:Suns @ Intimidators
DESCRIPTION:Suns @ Intimidators\n\nFollow on MiLB First Pitch: https://stza.co/+wICD-5\n\nShop: https://stza.co/+wICD-1A\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144530Z
LAST-MODIFIED:20180213T144530Z
TRANSP:OPAQUE
END:VEVENT
* Suns vs. Power
<2018-05-09 Wed 18:05-21:05>
:PROPERTIES:
:ID:       b7vkq2MeBtoxpBhtOKXnETiP@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Suns vs. Power Suns vs. Power

Follow on MiLB First Pitch  https //stza.co/+xGE8-1X

Shop  https //stza.co/+xGE8-3p

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Suns vs. Power
END:VALARM
DTSTART:20180509T230500Z
DTEND:20180510T020500Z
UID:b7vkq2MeBtoxpBhtOKXnETiP@stanza.co
SUMMARY:Suns vs. Power
DESCRIPTION:Suns vs. Power\n\nFollow on MiLB First Pitch: https://stza.co/+xGE8-1X\n\nShop: https://stza.co/+xGE8-3p\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144530Z
LAST-MODIFIED:20180213T144530Z
TRANSP:OPAQUE
END:VEVENT
* Suns vs. Power
<2018-05-10 Thu 18:05-21:05>
:PROPERTIES:
:ID:       XOnxDdIO69mxATNuBRn4FE9f@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Suns vs. Power Suns vs. Power

Follow on MiLB First Pitch  https //stza.co/+xGEb-2j

Shop  https //stza.co/+xGEb-S

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Suns vs. Power
END:VALARM
DTSTART:20180510T230500Z
DTEND:20180511T020500Z
UID:XOnxDdIO69mxATNuBRn4FE9f@stanza.co
SUMMARY:Suns vs. Power
DESCRIPTION:Suns vs. Power\n\nFollow on MiLB First Pitch: https://stza.co/+xGEb-2j\n\nShop: https://stza.co/+xGEb-S\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144530Z
LAST-MODIFIED:20180213T144530Z
TRANSP:OPAQUE
END:VEVENT
* Suns vs. Power
<2018-05-11 Fri 18:05-21:05>
:PROPERTIES:
:ID:       4hrdwp3DZ4N1JtZprmtO2o5m@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Suns vs. Power Suns vs. Power

Follow on MiLB First Pitch  https //stza.co/+xGEc-M

Shop  https //stza.co/+xGEc-38

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Suns vs. Power
END:VALARM
DTSTART:20180511T230500Z
DTEND:20180512T020500Z
UID:4hrdwp3DZ4N1JtZprmtO2o5m@stanza.co
SUMMARY:Suns vs. Power
DESCRIPTION:Suns vs. Power\n\nFollow on MiLB First Pitch: https://stza.co/+xGEc-M\n\nShop: https://stza.co/+xGEc-38\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144530Z
LAST-MODIFIED:20180213T144530Z
TRANSP:OPAQUE
END:VEVENT
* Suns vs. RiverDogs
<2018-05-12 Sat 17:05-20:05>
:PROPERTIES:
:ID:       ZpjiR2Oxz_ZfltXACLdrIac4@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Suns vs. RiverDogs Suns vs. RiverDogs

Follow on MiLB First Pitch  https //stza.co/+xGEf-1v

Shop  https //stza.co/+xGEf-2T

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Suns vs. RiverDogs
END:VALARM
DTSTART:20180512T220500Z
DTEND:20180513T010500Z
UID:ZpjiR2Oxz_ZfltXACLdrIac4@stanza.co
SUMMARY:Suns vs. RiverDogs
DESCRIPTION:Suns vs. RiverDogs\n\nFollow on MiLB First Pitch: https://stza.co/+xGEf-1v\n\nShop: https://stza.co/+xGEf-2T\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144530Z
LAST-MODIFIED:20180213T144530Z
TRANSP:OPAQUE
END:VEVENT
* Suns vs. RiverDogs
<2018-05-13 Sun 13:05-16:05>
:PROPERTIES:
:ID:       lRcLJKg5XH_4XrTjd1tfQLH9@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Suns vs. RiverDogs Suns vs. RiverDogs

Follow on MiLB First Pitch  https //stza.co/+xGEh-2_

Shop  https //stza.co/+xGEh-1Q

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Suns vs. RiverDogs
END:VALARM
DTSTART:20180513T180500Z
DTEND:20180513T210500Z
UID:lRcLJKg5XH_4XrTjd1tfQLH9@stanza.co
SUMMARY:Suns vs. RiverDogs
DESCRIPTION:Suns vs. RiverDogs\n\nFollow on MiLB First Pitch: https://stza.co/+xGEh-2_\n\nShop: https://stza.co/+xGEh-1Q\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144530Z
LAST-MODIFIED:20180213T144530Z
TRANSP:OPAQUE
END:VEVENT
* Suns vs. RiverDogs
<2018-05-14 Mon 18:05-21:05>
:PROPERTIES:
:ID:       xXjAjSYPYQaYPOjDskBsf3iF@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Suns vs. RiverDogs Suns vs. RiverDogs

Follow on MiLB First Pitch  https //stza.co/+xGEj-1

Shop  https //stza.co/+xGEj-M

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Suns vs. RiverDogs
END:VALARM
DTSTART:20180514T230500Z
DTEND:20180515T020500Z
UID:xXjAjSYPYQaYPOjDskBsf3iF@stanza.co
SUMMARY:Suns vs. RiverDogs
DESCRIPTION:Suns vs. RiverDogs\n\nFollow on MiLB First Pitch: https://stza.co/+xGEj-1\n\nShop: https://stza.co/+xGEj-M\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144530Z
LAST-MODIFIED:20180213T144530Z
TRANSP:OPAQUE
END:VEVENT
* Suns vs. RiverDogs
<2018-05-15 Tue 09:35-12:35>
:PROPERTIES:
:ID:       p3JPm-muPJtXMeeHF0mfa-j4@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Suns vs. RiverDogs Suns vs. RiverDogs

Follow on MiLB First Pitch  https //stza.co/+xGEk-B

Shop  https //stza.co/+xGEk-1B

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Suns vs. RiverDogs
END:VALARM
DTSTART:20180515T143500Z
DTEND:20180515T173500Z
UID:p3JPm-muPJtXMeeHF0mfa-j4@stanza.co
SUMMARY:Suns vs. RiverDogs
DESCRIPTION:Suns vs. RiverDogs\n\nFollow on MiLB First Pitch: https://stza.co/+xGEk-B\n\nShop: https://stza.co/+xGEk-1B\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144530Z
LAST-MODIFIED:20180213T144530Z
TRANSP:OPAQUE
END:VEVENT
* Suns @ Shorebirds
<2018-05-17 Thu 18:05-21:05>
:PROPERTIES:
:ID:       ikvNOGkuM9ljCXlGkL0ktRuI@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Suns @ Shorebirds Suns @ Shorebirds

Follow on MiLB First Pitch  https //stza.co/+wHS1-F

Shop  https //stza.co/+wHS1-1i

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Suns @ Shorebirds
END:VALARM
DTSTART:20180517T230500Z
DTEND:20180518T020500Z
UID:ikvNOGkuM9ljCXlGkL0ktRuI@stanza.co
SUMMARY:Suns @ Shorebirds
DESCRIPTION:Suns @ Shorebirds\n\nFollow on MiLB First Pitch: https://stza.co/+wHS1-F\n\nShop: https://stza.co/+wHS1-1i\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144530Z
LAST-MODIFIED:20180213T144530Z
TRANSP:OPAQUE
END:VEVENT
* Suns @ Shorebirds
<2018-05-18 Fri 18:05-21:05>
:PROPERTIES:
:ID:       8NOohL-5FIk0JZ3-vgmW1ZEF@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Suns @ Shorebirds Suns @ Shorebirds

Follow on MiLB First Pitch  https //stza.co/+wHS2-1r

Shop  https //stza.co/+wHS2-1i

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Suns @ Shorebirds
END:VALARM
DTSTART:20180518T230500Z
DTEND:20180519T020500Z
UID:8NOohL-5FIk0JZ3-vgmW1ZEF@stanza.co
SUMMARY:Suns @ Shorebirds
DESCRIPTION:Suns @ Shorebirds\n\nFollow on MiLB First Pitch: https://stza.co/+wHS2-1r\n\nShop: https://stza.co/+wHS2-1i\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144530Z
LAST-MODIFIED:20180213T144530Z
TRANSP:OPAQUE
END:VEVENT
* Suns @ Shorebirds
<2018-05-19 Sat 18:05-21:05>
:PROPERTIES:
:ID:       xziybI5wQHNpFxkpgnMsCziO@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Suns @ Shorebirds Suns @ Shorebirds

Follow on MiLB First Pitch  https //stza.co/+wHS3-1e

Shop  https //stza.co/+wHS3-19

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Suns @ Shorebirds
END:VALARM
DTSTART:20180519T230500Z
DTEND:20180520T020500Z
UID:xziybI5wQHNpFxkpgnMsCziO@stanza.co
SUMMARY:Suns @ Shorebirds
DESCRIPTION:Suns @ Shorebirds\n\nFollow on MiLB First Pitch: https://stza.co/+wHS3-1e\n\nShop: https://stza.co/+wHS3-19\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144530Z
LAST-MODIFIED:20180213T144530Z
TRANSP:OPAQUE
END:VEVENT
* Suns @ Shorebirds
<2018-05-20 Sun 13:05-16:05>
:PROPERTIES:
:ID:       XEJLwww434m68BMxLAc8cxdb@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Suns @ Shorebirds Suns @ Shorebirds

Follow on MiLB First Pitch  https //stza.co/+wHS4-2o

Shop  https //stza.co/+wHS4-m

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Suns @ Shorebirds
END:VALARM
DTSTART:20180520T180500Z
DTEND:20180520T210500Z
UID:XEJLwww434m68BMxLAc8cxdb@stanza.co
SUMMARY:Suns @ Shorebirds
DESCRIPTION:Suns @ Shorebirds\n\nFollow on MiLB First Pitch: https://stza.co/+wHS4-2o\n\nShop: https://stza.co/+wHS4-m\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144530Z
LAST-MODIFIED:20180213T144530Z
TRANSP:OPAQUE
END:VEVENT
* Suns @ BlueClaws
<2018-05-21 Mon 17:35-20:35>
:PROPERTIES:
:ID:       E5OpOxJSlgdAQM3lP90_7N2A@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Suns @ BlueClaws Suns @ BlueClaws

Follow on MiLB First Pitch  https //stza.co/+vNLK-H

Shop  https //stza.co/+vNLK-j

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Suns @ BlueClaws
END:VALARM
DTSTART:20180521T223500Z
DTEND:20180522T013500Z
UID:E5OpOxJSlgdAQM3lP90_7N2A@stanza.co
SUMMARY:Suns @ BlueClaws
DESCRIPTION:Suns @ BlueClaws\n\nFollow on MiLB First Pitch: https://stza.co/+vNLK-H\n\nShop: https://stza.co/+vNLK-j\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144530Z
LAST-MODIFIED:20180213T144530Z
TRANSP:OPAQUE
END:VEVENT
* Suns @ BlueClaws
<2018-05-22 Tue 17:35-20:35>
:PROPERTIES:
:ID:       OAsAnA5EgaB0VMQXBSfq6b0j@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Suns @ BlueClaws Suns @ BlueClaws

Follow on MiLB First Pitch  https //stza.co/+vNLL-A

Shop  https //stza.co/+vNLL-2O

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Suns @ BlueClaws
END:VALARM
DTSTART:20180522T223500Z
DTEND:20180523T013500Z
UID:OAsAnA5EgaB0VMQXBSfq6b0j@stanza.co
SUMMARY:Suns @ BlueClaws
DESCRIPTION:Suns @ BlueClaws\n\nFollow on MiLB First Pitch: https://stza.co/+vNLL-A\n\nShop: https://stza.co/+vNLL-2O\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144530Z
LAST-MODIFIED:20180213T144530Z
TRANSP:OPAQUE
END:VEVENT
* Suns @ BlueClaws
<2018-05-23 Wed 10:05-13:05>
:PROPERTIES:
:ID:       GkRwsKcYHHuyEfvoqn0RXv7A@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Suns @ BlueClaws Suns @ BlueClaws

Follow on MiLB First Pitch  https //stza.co/+vNLM-2v

Shop  https //stza.co/+vNLM-17

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Suns @ BlueClaws
END:VALARM
DTSTART:20180523T150500Z
DTEND:20180523T180500Z
UID:GkRwsKcYHHuyEfvoqn0RXv7A@stanza.co
SUMMARY:Suns @ BlueClaws
DESCRIPTION:Suns @ BlueClaws\n\nFollow on MiLB First Pitch: https://stza.co/+vNLM-2v\n\nShop: https://stza.co/+vNLM-17\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144530Z
LAST-MODIFIED:20180213T144530Z
TRANSP:OPAQUE
END:VEVENT
* Suns @ BlueClaws
<2018-05-24 Thu 17:35-20:35>
:PROPERTIES:
:ID:       _gxiRi2MdDHg1To9xtA88vPS@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Suns @ BlueClaws Suns @ BlueClaws

Follow on MiLB First Pitch  https //stza.co/+vNLN-X

Shop  https //stza.co/+vNLN-

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Suns @ BlueClaws
END:VALARM
DTSTART:20180524T223500Z
DTEND:20180525T013500Z
UID:_gxiRi2MdDHg1To9xtA88vPS@stanza.co
SUMMARY:Suns @ BlueClaws
DESCRIPTION:Suns @ BlueClaws\n\nFollow on MiLB First Pitch: https://stza.co/+vNLN-X\n\nShop: https://stza.co/+vNLN-\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144530Z
LAST-MODIFIED:20180213T144530Z
TRANSP:OPAQUE
END:VEVENT
* Suns vs. Grasshoppers
<2018-05-25 Fri 18:05-21:05>
:PROPERTIES:
:ID:       tUevef_VSt0sSvKoaYFmJ05m@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Suns vs. Grasshoppers Suns vs. Grasshoppers

Follow on MiLB First Pitch  https //stza.co/+xGEn-1R

Shop  https //stza.co/+xGEn-2f

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Suns vs. Grasshoppers
END:VALARM
DTSTART:20180525T230500Z
DTEND:20180526T020500Z
UID:tUevef_VSt0sSvKoaYFmJ05m@stanza.co
SUMMARY:Suns vs. Grasshoppers
DESCRIPTION:Suns vs. Grasshoppers\n\nFollow on MiLB First Pitch: https://stza.co/+xGEn-1R\n\nShop: https://stza.co/+xGEn-2f\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144530Z
LAST-MODIFIED:20180213T144530Z
TRANSP:OPAQUE
END:VEVENT
* Suns vs. Grasshoppers
<2018-05-26 Sat 17:05-20:05>
:PROPERTIES:
:ID:       rsLpu-uVqa1igVvjuPGeYU__@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Suns vs. Grasshoppers Suns vs. Grasshoppers

Follow on MiLB First Pitch  https //stza.co/+xGEp-2E

Shop  https //stza.co/+xGEp-22

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Suns vs. Grasshoppers
END:VALARM
DTSTART:20180526T220500Z
DTEND:20180527T010500Z
UID:rsLpu-uVqa1igVvjuPGeYU__@stanza.co
SUMMARY:Suns vs. Grasshoppers
DESCRIPTION:Suns vs. Grasshoppers\n\nFollow on MiLB First Pitch: https://stza.co/+xGEp-2E\n\nShop: https://stza.co/+xGEp-22\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144530Z
LAST-MODIFIED:20180213T144530Z
TRANSP:OPAQUE
END:VEVENT
* Suns vs. Grasshoppers
<2018-05-27 Sun 13:05-16:05>
:PROPERTIES:
:ID:       zifnVP5ebOMkSegE0bkfkfs_@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Suns vs. Grasshoppers Suns vs. Grasshoppers

Follow on MiLB First Pitch  https //stza.co/+xGEr-I

Shop  https //stza.co/+xGEr-1h

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Suns vs. Grasshoppers
END:VALARM
DTSTART:20180527T180500Z
DTEND:20180527T210500Z
UID:zifnVP5ebOMkSegE0bkfkfs_@stanza.co
SUMMARY:Suns vs. Grasshoppers
DESCRIPTION:Suns vs. Grasshoppers\n\nFollow on MiLB First Pitch: https://stza.co/+xGEr-I\n\nShop: https://stza.co/+xGEr-1h\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144530Z
LAST-MODIFIED:20180213T144530Z
TRANSP:OPAQUE
END:VEVENT
* Suns vs. Grasshoppers
<2018-05-28 Mon 13:05-16:05>
:PROPERTIES:
:ID:       pKT3boTgOkJTI-uPd-zxvLlo@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Suns vs. Grasshoppers Suns vs. Grasshoppers

Follow on MiLB First Pitch  https //stza.co/+xGEs-x

Shop  https //stza.co/+xGEs-3l

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Suns vs. Grasshoppers
END:VALARM
DTSTART:20180528T180500Z
DTEND:20180528T210500Z
UID:pKT3boTgOkJTI-uPd-zxvLlo@stanza.co
SUMMARY:Suns vs. Grasshoppers
DESCRIPTION:Suns vs. Grasshoppers\n\nFollow on MiLB First Pitch: https://stza.co/+xGEs-x\n\nShop: https://stza.co/+xGEs-3l\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144530Z
LAST-MODIFIED:20180213T144530Z
TRANSP:OPAQUE
END:VEVENT
* Suns vs. Crawdads
<2018-05-29 Tue 18:05-21:05>
:PROPERTIES:
:ID:       Vy8Zcbc4uTfklvu8AMyO7t1z@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Suns vs. Crawdads Suns vs. Crawdads

Follow on MiLB First Pitch  https //stza.co/+xGEv-29

Shop  https //stza.co/+xGEv-2j

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Suns vs. Crawdads
END:VALARM
DTSTART:20180529T230500Z
DTEND:20180530T020500Z
UID:Vy8Zcbc4uTfklvu8AMyO7t1z@stanza.co
SUMMARY:Suns vs. Crawdads
DESCRIPTION:Suns vs. Crawdads\n\nFollow on MiLB First Pitch: https://stza.co/+xGEv-29\n\nShop: https://stza.co/+xGEv-2j\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144530Z
LAST-MODIFIED:20180213T144530Z
TRANSP:OPAQUE
END:VEVENT
* Suns vs. Crawdads
<2018-05-30 Wed 18:05-21:05>
:PROPERTIES:
:ID:       eXP3Vp2FbXgevNsQknJF5ubJ@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Suns vs. Crawdads Suns vs. Crawdads

Follow on MiLB First Pitch  https //stza.co/+xGEx-K

Shop  https //stza.co/+xGEx-1_

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Suns vs. Crawdads
END:VALARM
DTSTART:20180530T230500Z
DTEND:20180531T020500Z
UID:eXP3Vp2FbXgevNsQknJF5ubJ@stanza.co
SUMMARY:Suns vs. Crawdads
DESCRIPTION:Suns vs. Crawdads\n\nFollow on MiLB First Pitch: https://stza.co/+xGEx-K\n\nShop: https://stza.co/+xGEx-1_\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144530Z
LAST-MODIFIED:20180213T144530Z
TRANSP:OPAQUE
END:VEVENT
* Suns vs. Crawdads
<2018-05-31 Thu 18:05-21:05>
:PROPERTIES:
:ID:       Gcxr9ojOPHW_F8BKUmNkHjp8@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Suns vs. Crawdads Suns vs. Crawdads

Follow on MiLB First Pitch  https //stza.co/+xGEz-9

Shop  https //stza.co/+xGEz-3b

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Suns vs. Crawdads
END:VALARM
DTSTART:20180531T230500Z
DTEND:20180601T020500Z
UID:Gcxr9ojOPHW_F8BKUmNkHjp8@stanza.co
SUMMARY:Suns vs. Crawdads
DESCRIPTION:Suns vs. Crawdads\n\nFollow on MiLB First Pitch: https://stza.co/+xGEz-9\n\nShop: https://stza.co/+xGEz-3b\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144530Z
LAST-MODIFIED:20180213T144530Z
TRANSP:OPAQUE
END:VEVENT
* Suns @ Intimidators
<2018-06-01 Fri 18:05-21:05>
:PROPERTIES:
:ID:       cy697TaKMbFRTfkGeXhSmTcO@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Suns @ Intimidators Suns @ Intimidators

Follow on MiLB First Pitch  https //stza.co/+wICE-1z

Shop  https //stza.co/+wICE-3T

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Suns @ Intimidators
END:VALARM
DTSTART:20180601T230500Z
DTEND:20180602T020500Z
UID:cy697TaKMbFRTfkGeXhSmTcO@stanza.co
SUMMARY:Suns @ Intimidators
DESCRIPTION:Suns @ Intimidators\n\nFollow on MiLB First Pitch: https://stza.co/+wICE-1z\n\nShop: https://stza.co/+wICE-3T\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144530Z
LAST-MODIFIED:20180213T144530Z
TRANSP:OPAQUE
END:VEVENT
* Suns @ Intimidators
<2018-06-02 Sat 18:05-21:05>
:PROPERTIES:
:ID:       SLfY_JsUSMWALylyDjxRE1KM@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Suns @ Intimidators Suns @ Intimidators

Follow on MiLB First Pitch  https //stza.co/+wICF-3r

Shop  https //stza.co/+wICF-3H

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Suns @ Intimidators
END:VALARM
DTSTART:20180602T230500Z
DTEND:20180603T020500Z
UID:SLfY_JsUSMWALylyDjxRE1KM@stanza.co
SUMMARY:Suns @ Intimidators
DESCRIPTION:Suns @ Intimidators\n\nFollow on MiLB First Pitch: https://stza.co/+wICF-3r\n\nShop: https://stza.co/+wICF-3H\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144530Z
LAST-MODIFIED:20180213T144530Z
TRANSP:OPAQUE
END:VEVENT
* Suns @ Intimidators
<2018-06-03 Sun 16:05-19:05>
:PROPERTIES:
:ID:       x4Se7F4_iA9TVOjQc1dyFw2J@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Suns @ Intimidators Suns @ Intimidators

Follow on MiLB First Pitch  https //stza.co/+wICG-1V

Shop  https //stza.co/+wICG-2i

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Suns @ Intimidators
END:VALARM
DTSTART:20180603T210500Z
DTEND:20180604T000500Z
UID:x4Se7F4_iA9TVOjQc1dyFw2J@stanza.co
SUMMARY:Suns @ Intimidators
DESCRIPTION:Suns @ Intimidators\n\nFollow on MiLB First Pitch: https://stza.co/+wICG-1V\n\nShop: https://stza.co/+wICG-2i\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144530Z
LAST-MODIFIED:20180213T144530Z
TRANSP:OPAQUE
END:VEVENT
* Suns vs. BlueClaws
<2018-06-05 Tue 18:05-21:05>
:PROPERTIES:
:ID:       SOstdjLyXiP7M7Eh5i3LbMAe@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Suns vs. BlueClaws Suns vs. BlueClaws

Follow on MiLB First Pitch  https //stza.co/+xGEA-P

Shop  https //stza.co/+xGEA-3p

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Suns vs. BlueClaws
END:VALARM
DTSTART:20180605T230500Z
DTEND:20180606T020500Z
UID:SOstdjLyXiP7M7Eh5i3LbMAe@stanza.co
SUMMARY:Suns vs. BlueClaws
DESCRIPTION:Suns vs. BlueClaws\n\nFollow on MiLB First Pitch: https://stza.co/+xGEA-P\n\nShop: https://stza.co/+xGEA-3p\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144530Z
LAST-MODIFIED:20180213T144530Z
TRANSP:OPAQUE
END:VEVENT
* Suns vs. BlueClaws
<2018-06-06 Wed 18:05-21:05>
:PROPERTIES:
:ID:       z1Dspp2DgBd62aXhVWVoz0Qx@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Suns vs. BlueClaws Suns vs. BlueClaws

Follow on MiLB First Pitch  https //stza.co/+xGED-15

Shop  https //stza.co/+xGED-2K

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Suns vs. BlueClaws
END:VALARM
DTSTART:20180606T230500Z
DTEND:20180607T020500Z
UID:z1Dspp2DgBd62aXhVWVoz0Qx@stanza.co
SUMMARY:Suns vs. BlueClaws
DESCRIPTION:Suns vs. BlueClaws\n\nFollow on MiLB First Pitch: https://stza.co/+xGED-15\n\nShop: https://stza.co/+xGED-2K\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144530Z
LAST-MODIFIED:20180213T144530Z
TRANSP:OPAQUE
END:VEVENT
* Suns vs. BlueClaws
<2018-06-07 Thu 18:05-21:05>
:PROPERTIES:
:ID:       VTQzf1FTykh3Hne0V39qv9i5@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Suns vs. BlueClaws Suns vs. BlueClaws

Follow on MiLB First Pitch  https //stza.co/+xGEF-1a

Shop  https //stza.co/+xGEF-P

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Suns vs. BlueClaws
END:VALARM
DTSTART:20180607T230500Z
DTEND:20180608T020500Z
UID:VTQzf1FTykh3Hne0V39qv9i5@stanza.co
SUMMARY:Suns vs. BlueClaws
DESCRIPTION:Suns vs. BlueClaws\n\nFollow on MiLB First Pitch: https://stza.co/+xGEF-1a\n\nShop: https://stza.co/+xGEF-P\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144530Z
LAST-MODIFIED:20180213T144530Z
TRANSP:OPAQUE
END:VEVENT
* Suns @ Shorebirds
<2018-06-08 Fri 18:05-21:05>
:PROPERTIES:
:ID:       q2YYqQcoIVnzK1PA9N2lR8vx@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Suns @ Shorebirds Suns @ Shorebirds

Follow on MiLB First Pitch  https //stza.co/+wHS5-2X

Shop  https //stza.co/+wHS5-3c

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Suns @ Shorebirds
END:VALARM
DTSTART:20180608T230500Z
DTEND:20180609T020500Z
UID:q2YYqQcoIVnzK1PA9N2lR8vx@stanza.co
SUMMARY:Suns @ Shorebirds
DESCRIPTION:Suns @ Shorebirds\n\nFollow on MiLB First Pitch: https://stza.co/+wHS5-2X\n\nShop: https://stza.co/+wHS5-3c\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144530Z
LAST-MODIFIED:20180213T144530Z
TRANSP:OPAQUE
END:VEVENT
* Suns @ Shorebirds
<2018-06-09 Sat 17:35-20:35>
:PROPERTIES:
:ID:       zmniLTU2VRk2tQxl8iZCRPqW@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Suns @ Shorebirds Suns @ Shorebirds

Follow on MiLB First Pitch  https //stza.co/+wHS6-u

Shop  https //stza.co/+wHS6-3l

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Suns @ Shorebirds
END:VALARM
DTSTART:20180609T223500Z
DTEND:20180610T013500Z
UID:zmniLTU2VRk2tQxl8iZCRPqW@stanza.co
SUMMARY:Suns @ Shorebirds
DESCRIPTION:Suns @ Shorebirds\n\nFollow on MiLB First Pitch: https://stza.co/+wHS6-u\n\nShop: https://stza.co/+wHS6-3l\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144530Z
LAST-MODIFIED:20180213T144530Z
TRANSP:OPAQUE
END:VEVENT
* Suns @ Shorebirds
<2018-06-10 Sun 13:05-16:05>
:PROPERTIES:
:ID:       IVSz1dxh_hXJx4dSExM3Enkh@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Suns @ Shorebirds Suns @ Shorebirds

Follow on MiLB First Pitch  https //stza.co/+wHS7-3g

Shop  https //stza.co/+wHS7-3L

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Suns @ Shorebirds
END:VALARM
DTSTART:20180610T180500Z
DTEND:20180610T210500Z
UID:IVSz1dxh_hXJx4dSExM3Enkh@stanza.co
SUMMARY:Suns @ Shorebirds
DESCRIPTION:Suns @ Shorebirds\n\nFollow on MiLB First Pitch: https://stza.co/+wHS7-3g\n\nShop: https://stza.co/+wHS7-3L\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144530Z
LAST-MODIFIED:20180213T144530Z
TRANSP:OPAQUE
END:VEVENT
* Suns @ BlueClaws
<2018-06-11 Mon 18:05-21:05>
:PROPERTIES:
:ID:       vLjN9c3Aa78ALUaNuekQG1LC@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Suns @ BlueClaws Suns @ BlueClaws

Follow on MiLB First Pitch  https //stza.co/+vNLO-T

Shop  https //stza.co/+vNLO-k

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Suns @ BlueClaws
END:VALARM
DTSTART:20180611T230500Z
DTEND:20180612T020500Z
UID:vLjN9c3Aa78ALUaNuekQG1LC@stanza.co
SUMMARY:Suns @ BlueClaws
DESCRIPTION:Suns @ BlueClaws\n\nFollow on MiLB First Pitch: https://stza.co/+vNLO-T\n\nShop: https://stza.co/+vNLO-k\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144530Z
LAST-MODIFIED:20180213T144530Z
TRANSP:OPAQUE
END:VEVENT
* Suns @ BlueClaws
<2018-06-12 Tue 18:05-21:05>
:PROPERTIES:
:ID:       JhEPdJYpJBeziaLulRCWHm1U@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Suns @ BlueClaws Suns @ BlueClaws

Follow on MiLB First Pitch  https //stza.co/+vNLP-1l

Shop  https //stza.co/+vNLP-2U

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Suns @ BlueClaws
END:VALARM
DTSTART:20180612T230500Z
DTEND:20180613T020500Z
UID:JhEPdJYpJBeziaLulRCWHm1U@stanza.co
SUMMARY:Suns @ BlueClaws
DESCRIPTION:Suns @ BlueClaws\n\nFollow on MiLB First Pitch: https://stza.co/+vNLP-1l\n\nShop: https://stza.co/+vNLP-2U\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144530Z
LAST-MODIFIED:20180213T144530Z
TRANSP:OPAQUE
END:VEVENT
* Suns @ BlueClaws
<2018-06-13 Wed 18:05-21:05>
:PROPERTIES:
:ID:       EhcxTamV5HW2whNupw18kjDw@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Suns @ BlueClaws Suns @ BlueClaws

Follow on MiLB First Pitch  https //stza.co/+vNLQ-K

Shop  https //stza.co/+vNLQ-16

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Suns @ BlueClaws
END:VALARM
DTSTART:20180613T230500Z
DTEND:20180614T020500Z
UID:EhcxTamV5HW2whNupw18kjDw@stanza.co
SUMMARY:Suns @ BlueClaws
DESCRIPTION:Suns @ BlueClaws\n\nFollow on MiLB First Pitch: https://stza.co/+vNLQ-K\n\nShop: https://stza.co/+vNLQ-16\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144530Z
LAST-MODIFIED:20180213T144530Z
TRANSP:OPAQUE
END:VEVENT
* Suns @ BlueClaws
<2018-06-14 Thu 18:05-21:05>
:PROPERTIES:
:ID:       ku7Iubj0ZaFN9H0HrywJz0ZU@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Suns @ BlueClaws Suns @ BlueClaws

Follow on MiLB First Pitch  https //stza.co/+vNLR-3b

Shop  https //stza.co/+vNLR-E

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Suns @ BlueClaws
END:VALARM
DTSTART:20180614T230500Z
DTEND:20180615T020500Z
UID:ku7Iubj0ZaFN9H0HrywJz0ZU@stanza.co
SUMMARY:Suns @ BlueClaws
DESCRIPTION:Suns @ BlueClaws\n\nFollow on MiLB First Pitch: https://stza.co/+vNLR-3b\n\nShop: https://stza.co/+vNLR-E\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144530Z
LAST-MODIFIED:20180213T144530Z
TRANSP:OPAQUE
END:VEVENT
* Suns vs. Fireflies
<2018-06-15 Fri 18:05-21:05>
:PROPERTIES:
:ID:       9XnRph355VMZyEb7lDL0St6E@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Suns vs. Fireflies Suns vs. Fireflies

Follow on MiLB First Pitch  https //stza.co/+xGEH-1A

Shop  https //stza.co/+xGEH-2t

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Suns vs. Fireflies
END:VALARM
DTSTART:20180615T230500Z
DTEND:20180616T020500Z
UID:9XnRph355VMZyEb7lDL0St6E@stanza.co
SUMMARY:Suns vs. Fireflies
DESCRIPTION:Suns vs. Fireflies\n\nFollow on MiLB First Pitch: https://stza.co/+xGEH-1A\n\nShop: https://stza.co/+xGEH-2t\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144530Z
LAST-MODIFIED:20180213T144530Z
TRANSP:OPAQUE
END:VEVENT
* Suns vs. Fireflies
<2018-06-16 Sat 17:05-20:05>
:PROPERTIES:
:ID:       xpa5KUuWxkDZ1KCLTeeicbmJ@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Suns vs. Fireflies Suns vs. Fireflies

Follow on MiLB First Pitch  https //stza.co/+xGEI-3j

Shop  https //stza.co/+xGEI-12

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Suns vs. Fireflies
END:VALARM
DTSTART:20180616T220500Z
DTEND:20180617T010500Z
UID:xpa5KUuWxkDZ1KCLTeeicbmJ@stanza.co
SUMMARY:Suns vs. Fireflies
DESCRIPTION:Suns vs. Fireflies\n\nFollow on MiLB First Pitch: https://stza.co/+xGEI-3j\n\nShop: https://stza.co/+xGEI-12\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144530Z
LAST-MODIFIED:20180213T144530Z
TRANSP:OPAQUE
END:VEVENT
* Suns vs. Fireflies
<2018-06-17 Sun 13:05-16:05>
:PROPERTIES:
:ID:       njB9mYJoge3bkNZmmvPzUI3w@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Suns vs. Fireflies Suns vs. Fireflies

Follow on MiLB First Pitch  https //stza.co/+xGEL-1S

Shop  https //stza.co/+xGEL-21

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Suns vs. Fireflies
END:VALARM
DTSTART:20180617T180500Z
DTEND:20180617T210500Z
UID:njB9mYJoge3bkNZmmvPzUI3w@stanza.co
SUMMARY:Suns vs. Fireflies
DESCRIPTION:Suns vs. Fireflies\n\nFollow on MiLB First Pitch: https://stza.co/+xGEL-1S\n\nShop: https://stza.co/+xGEL-21\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144530Z
LAST-MODIFIED:20180213T144530Z
TRANSP:OPAQUE
END:VEVENT
* Suns vs. Grasshoppers
<2018-06-21 Thu 18:05-21:05>
:PROPERTIES:
:ID:       SOqBPy-jaaHwc1c8ZNpCMMYX@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Suns vs. Grasshoppers Suns vs. Grasshoppers

Follow on MiLB First Pitch  https //stza.co/+xGEN-Z

Shop  https //stza.co/+xGEN-3K

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Suns vs. Grasshoppers
END:VALARM
DTSTART:20180621T230500Z
DTEND:20180622T020500Z
UID:SOqBPy-jaaHwc1c8ZNpCMMYX@stanza.co
SUMMARY:Suns vs. Grasshoppers
DESCRIPTION:Suns vs. Grasshoppers\n\nFollow on MiLB First Pitch: https://stza.co/+xGEN-Z\n\nShop: https://stza.co/+xGEN-3K\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144530Z
LAST-MODIFIED:20180213T144530Z
TRANSP:OPAQUE
END:VEVENT
* Suns vs. Grasshoppers
<2018-06-22 Fri 18:05-21:05>
:PROPERTIES:
:ID:       1dLxoVnJfyV-018-LwNWutBD@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Suns vs. Grasshoppers Suns vs. Grasshoppers

Follow on MiLB First Pitch  https //stza.co/+xGEO-1T

Shop  https //stza.co/+xGEO-3p

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Suns vs. Grasshoppers
END:VALARM
DTSTART:20180622T230500Z
DTEND:20180623T020500Z
UID:1dLxoVnJfyV-018-LwNWutBD@stanza.co
SUMMARY:Suns vs. Grasshoppers
DESCRIPTION:Suns vs. Grasshoppers\n\nFollow on MiLB First Pitch: https://stza.co/+xGEO-1T\n\nShop: https://stza.co/+xGEO-3p\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144530Z
LAST-MODIFIED:20180213T144530Z
TRANSP:OPAQUE
END:VEVENT
* Suns vs. Grasshoppers
<2018-06-23 Sat 17:05-20:05>
:PROPERTIES:
:ID:       0Mnw_VM5Zbs1SIoYV8yqDPkS@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Suns vs. Grasshoppers Suns vs. Grasshoppers

Follow on MiLB First Pitch  https //stza.co/+xGEQ-$

Shop  https //stza.co/+xGEQ-28

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Suns vs. Grasshoppers
END:VALARM
DTSTART:20180623T220500Z
DTEND:20180624T010500Z
UID:0Mnw_VM5Zbs1SIoYV8yqDPkS@stanza.co
SUMMARY:Suns vs. Grasshoppers
DESCRIPTION:Suns vs. Grasshoppers\n\nFollow on MiLB First Pitch: https://stza.co/+xGEQ-$\n\nShop: https://stza.co/+xGEQ-28\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144530Z
LAST-MODIFIED:20180213T144530Z
TRANSP:OPAQUE
END:VEVENT
* Suns @ Shorebirds
<2018-06-24 Sun 13:05-16:05>
:PROPERTIES:
:ID:       5Jrb4lBn9t3WyvNQnKI9a0GV@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Suns @ Shorebirds Suns @ Shorebirds

Follow on MiLB First Pitch  https //stza.co/+wHS8-X

Shop  https //stza.co/+wHS8-1b

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Suns @ Shorebirds
END:VALARM
DTSTART:20180624T180500Z
DTEND:20180624T210500Z
UID:5Jrb4lBn9t3WyvNQnKI9a0GV@stanza.co
SUMMARY:Suns @ Shorebirds
DESCRIPTION:Suns @ Shorebirds\n\nFollow on MiLB First Pitch: https://stza.co/+wHS8-X\n\nShop: https://stza.co/+wHS8-1b\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144530Z
LAST-MODIFIED:20180213T144530Z
TRANSP:OPAQUE
END:VEVENT
* Suns @ Shorebirds
<2018-06-25 Mon 18:05-21:05>
:PROPERTIES:
:ID:       -7k6v2VyOALpoZbmg0MqqqFV@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Suns @ Shorebirds Suns @ Shorebirds

Follow on MiLB First Pitch  https //stza.co/+wHS9-2S

Shop  https //stza.co/+wHS9-3X

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Suns @ Shorebirds
END:VALARM
DTSTART:20180625T230500Z
DTEND:20180626T020500Z
UID:-7k6v2VyOALpoZbmg0MqqqFV@stanza.co
SUMMARY:Suns @ Shorebirds
DESCRIPTION:Suns @ Shorebirds\n\nFollow on MiLB First Pitch: https://stza.co/+wHS9-2S\n\nShop: https://stza.co/+wHS9-3X\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144530Z
LAST-MODIFIED:20180213T144530Z
TRANSP:OPAQUE
END:VEVENT
* Suns @ Shorebirds
<2018-06-26 Tue 18:05-21:05>
:PROPERTIES:
:ID:       q9KRmV8rez9YuwcTbMrwOXHp@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Suns @ Shorebirds Suns @ Shorebirds

Follow on MiLB First Pitch  https //stza.co/+wHSa-S

Shop  https //stza.co/+wHSa-3w

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Suns @ Shorebirds
END:VALARM
DTSTART:20180626T230500Z
DTEND:20180627T020500Z
UID:q9KRmV8rez9YuwcTbMrwOXHp@stanza.co
SUMMARY:Suns @ Shorebirds
DESCRIPTION:Suns @ Shorebirds\n\nFollow on MiLB First Pitch: https://stza.co/+wHSa-S\n\nShop: https://stza.co/+wHSa-3w\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144530Z
LAST-MODIFIED:20180213T144530Z
TRANSP:OPAQUE
END:VEVENT
* Suns @ BlueClaws
<2018-06-27 Wed 18:05-21:05>
:PROPERTIES:
:ID:       fwvvP26RJMWL_Mh5s0WJH7VR@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Suns @ BlueClaws Suns @ BlueClaws

Follow on MiLB First Pitch  https //stza.co/+vNLS-2a

Shop  https //stza.co/+vNLS-35

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Suns @ BlueClaws
END:VALARM
DTSTART:20180627T230500Z
DTEND:20180628T020500Z
UID:fwvvP26RJMWL_Mh5s0WJH7VR@stanza.co
SUMMARY:Suns @ BlueClaws
DESCRIPTION:Suns @ BlueClaws\n\nFollow on MiLB First Pitch: https://stza.co/+vNLS-2a\n\nShop: https://stza.co/+vNLS-35\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144530Z
LAST-MODIFIED:20180213T144530Z
TRANSP:OPAQUE
END:VEVENT
* Suns @ BlueClaws
<2018-06-28 Thu 18:05-21:05>
:PROPERTIES:
:ID:       6vtZ8Lenx-1y75RNV-77CnsG@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Suns @ BlueClaws Suns @ BlueClaws

Follow on MiLB First Pitch  https //stza.co/+vNLT-1n

Shop  https //stza.co/+vNLT-3B

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Suns @ BlueClaws
END:VALARM
DTSTART:20180628T230500Z
DTEND:20180629T020500Z
UID:6vtZ8Lenx-1y75RNV-77CnsG@stanza.co
SUMMARY:Suns @ BlueClaws
DESCRIPTION:Suns @ BlueClaws\n\nFollow on MiLB First Pitch: https://stza.co/+vNLT-1n\n\nShop: https://stza.co/+vNLT-3B\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144530Z
LAST-MODIFIED:20180213T144530Z
TRANSP:OPAQUE
END:VEVENT
* Suns @ BlueClaws
<2018-06-29 Fri 18:05-21:05>
:PROPERTIES:
:ID:       JhEt73vpRgHnr7RfrgWRlhLM@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Suns @ BlueClaws Suns @ BlueClaws

Follow on MiLB First Pitch  https //stza.co/+vNLU-1w

Shop  https //stza.co/+vNLU-3V

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Suns @ BlueClaws
END:VALARM
DTSTART:20180629T230500Z
DTEND:20180630T020500Z
UID:JhEt73vpRgHnr7RfrgWRlhLM@stanza.co
SUMMARY:Suns @ BlueClaws
DESCRIPTION:Suns @ BlueClaws\n\nFollow on MiLB First Pitch: https://stza.co/+vNLU-1w\n\nShop: https://stza.co/+vNLU-3V\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144530Z
LAST-MODIFIED:20180213T144530Z
TRANSP:OPAQUE
END:VEVENT
* Suns vs. Power
<2018-06-30 Sat 17:05-20:05>
:PROPERTIES:
:ID:       uu4RYnh9mhEV0txCrXhrN-MW@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Suns vs. Power Suns vs. Power

Follow on MiLB First Pitch  https //stza.co/+xGET-t

Shop  https //stza.co/+xGET-36

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Suns vs. Power
END:VALARM
DTSTART:20180630T220500Z
DTEND:20180701T010500Z
UID:uu4RYnh9mhEV0txCrXhrN-MW@stanza.co
SUMMARY:Suns vs. Power
DESCRIPTION:Suns vs. Power\n\nFollow on MiLB First Pitch: https://stza.co/+xGET-t\n\nShop: https://stza.co/+xGET-36\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144530Z
LAST-MODIFIED:20180213T144530Z
TRANSP:OPAQUE
END:VEVENT
* Suns vs. Power
<2018-07-01 Sun 13:05-16:05>
:PROPERTIES:
:ID:       bxdQFwM5G6d9Goy3UILT0uXU@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Suns vs. Power Suns vs. Power

Follow on MiLB First Pitch  https //stza.co/+xGEV-1_

Shop  https //stza.co/+xGEV-1E

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Suns vs. Power
END:VALARM
DTSTART:20180701T180500Z
DTEND:20180701T210500Z
UID:bxdQFwM5G6d9Goy3UILT0uXU@stanza.co
SUMMARY:Suns vs. Power
DESCRIPTION:Suns vs. Power\n\nFollow on MiLB First Pitch: https://stza.co/+xGEV-1_\n\nShop: https://stza.co/+xGEV-1E\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144530Z
LAST-MODIFIED:20180213T144530Z
TRANSP:OPAQUE
END:VEVENT
* Suns vs. Power
<2018-07-02 Mon 18:05-21:05>
:PROPERTIES:
:ID:       t4RVnDfAXvRzXzwq0TI62Pk0@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Suns vs. Power Suns vs. Power

Follow on MiLB First Pitch  https //stza.co/+xGEX-2r

Shop  https //stza.co/+xGEX-1Y

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Suns vs. Power
END:VALARM
DTSTART:20180702T230500Z
DTEND:20180703T020500Z
UID:t4RVnDfAXvRzXzwq0TI62Pk0@stanza.co
SUMMARY:Suns vs. Power
DESCRIPTION:Suns vs. Power\n\nFollow on MiLB First Pitch: https://stza.co/+xGEX-2r\n\nShop: https://stza.co/+xGEX-1Y\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144530Z
LAST-MODIFIED:20180213T144530Z
TRANSP:OPAQUE
END:VEVENT
* Suns vs. Power
<2018-07-03 Tue 18:05-21:05>
:PROPERTIES:
:ID:       fZ_E7FckuCWhfr0BsuFdiT1c@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Suns vs. Power Suns vs. Power

Follow on MiLB First Pitch  https //stza.co/+xGEZ-2d

Shop  https //stza.co/+xGEZ-Q

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Suns vs. Power
END:VALARM
DTSTART:20180703T230500Z
DTEND:20180704T020500Z
UID:fZ_E7FckuCWhfr0BsuFdiT1c@stanza.co
SUMMARY:Suns vs. Power
DESCRIPTION:Suns vs. Power\n\nFollow on MiLB First Pitch: https://stza.co/+xGEZ-2d\n\nShop: https://stza.co/+xGEZ-Q\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144530Z
LAST-MODIFIED:20180213T144530Z
TRANSP:OPAQUE
END:VEVENT
* Suns @ Shorebirds
<2018-07-04 Wed 17:05-20:05>
:PROPERTIES:
:ID:       P3QX1CyYDvYqlGL5mWb_mezC@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Suns @ Shorebirds Suns @ Shorebirds

Follow on MiLB First Pitch  https //stza.co/+wHSb-2f

Shop  https //stza.co/+wHSb-36

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Suns @ Shorebirds
END:VALARM
DTSTART:20180704T220500Z
DTEND:20180705T010500Z
UID:P3QX1CyYDvYqlGL5mWb_mezC@stanza.co
SUMMARY:Suns @ Shorebirds
DESCRIPTION:Suns @ Shorebirds\n\nFollow on MiLB First Pitch: https://stza.co/+wHSb-2f\n\nShop: https://stza.co/+wHSb-36\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144530Z
LAST-MODIFIED:20180213T144530Z
TRANSP:OPAQUE
END:VEVENT
* Suns @ Shorebirds
<2018-07-05 Thu 18:05-21:05>
:PROPERTIES:
:ID:       iW---KA46G_X2SKUK2ZpaneT@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Suns @ Shorebirds Suns @ Shorebirds

Follow on MiLB First Pitch  https //stza.co/+wHSc-2r

Shop  https //stza.co/+wHSc-3D

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Suns @ Shorebirds
END:VALARM
DTSTART:20180705T230500Z
DTEND:20180706T020500Z
UID:iW---KA46G_X2SKUK2ZpaneT@stanza.co
SUMMARY:Suns @ Shorebirds
DESCRIPTION:Suns @ Shorebirds\n\nFollow on MiLB First Pitch: https://stza.co/+wHSc-2r\n\nShop: https://stza.co/+wHSc-3D\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144530Z
LAST-MODIFIED:20180213T144530Z
TRANSP:OPAQUE
END:VEVENT
* Suns @ Shorebirds
<2018-07-06 Fri 18:05-21:05>
:PROPERTIES:
:ID:       bpH7y5z-4pSLmKB2M4eA-vgu@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Suns @ Shorebirds Suns @ Shorebirds

Follow on MiLB First Pitch  https //stza.co/+wHOo-1m

Shop  https //stza.co/+wHOo-1e

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Suns @ Shorebirds
END:VALARM
DTSTART:20180706T230500Z
DTEND:20180707T020500Z
UID:bpH7y5z-4pSLmKB2M4eA-vgu@stanza.co
SUMMARY:Suns @ Shorebirds
DESCRIPTION:Suns @ Shorebirds\n\nFollow on MiLB First Pitch: https://stza.co/+wHOo-1m\n\nShop: https://stza.co/+wHOo-1e\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144530Z
LAST-MODIFIED:20180213T144530Z
TRANSP:OPAQUE
END:VEVENT
* Suns @ Power
<2018-07-07 Sat 17:05-20:05>
:PROPERTIES:
:ID:       JkSPsDPduRwYazRf2gkW2JPe@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Suns @ Power Suns @ Power

Follow on MiLB First Pitch  https //stza.co/+xJ3Q-V

Shop  https //stza.co/+xJ3Q-2T

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Suns @ Power
END:VALARM
DTSTART:20180707T220500Z
DTEND:20180708T010500Z
UID:JkSPsDPduRwYazRf2gkW2JPe@stanza.co
SUMMARY:Suns @ Power
DESCRIPTION:Suns @ Power\n\nFollow on MiLB First Pitch: https://stza.co/+xJ3Q-V\n\nShop: https://stza.co/+xJ3Q-2T\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144530Z
LAST-MODIFIED:20180213T144530Z
TRANSP:OPAQUE
END:VEVENT
* Suns @ Power
<2018-07-08 Sun 13:05-16:05>
:PROPERTIES:
:ID:       VzxtxY4IaFKAHOecbU7UlNeU@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Suns @ Power Suns @ Power

Follow on MiLB First Pitch  https //stza.co/+xJ3R-3u

Shop  https //stza.co/+xJ3R-3f

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Suns @ Power
END:VALARM
DTSTART:20180708T180500Z
DTEND:20180708T210500Z
UID:VzxtxY4IaFKAHOecbU7UlNeU@stanza.co
SUMMARY:Suns @ Power
DESCRIPTION:Suns @ Power\n\nFollow on MiLB First Pitch: https://stza.co/+xJ3R-3u\n\nShop: https://stza.co/+xJ3R-3f\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144530Z
LAST-MODIFIED:20180213T144530Z
TRANSP:OPAQUE
END:VEVENT
* Suns @ Power
<2018-07-09 Mon 18:05-21:05>
:PROPERTIES:
:ID:       Gvx30fKdQr4h7dohJ6SdUhwd@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Suns @ Power Suns @ Power

Follow on MiLB First Pitch  https //stza.co/+xJ3S-3L

Shop  https //stza.co/+xJ3S-3t

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Suns @ Power
END:VALARM
DTSTART:20180709T230500Z
DTEND:20180710T020500Z
UID:Gvx30fKdQr4h7dohJ6SdUhwd@stanza.co
SUMMARY:Suns @ Power
DESCRIPTION:Suns @ Power\n\nFollow on MiLB First Pitch: https://stza.co/+xJ3S-3L\n\nShop: https://stza.co/+xJ3S-3t\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144530Z
LAST-MODIFIED:20180213T144530Z
TRANSP:OPAQUE
END:VEVENT
* Suns vs. Fireflies
<2018-07-11 Wed 18:05-21:05>
:PROPERTIES:
:ID:       gcNLhSEidu_O5Y_65f5eZilt@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Suns vs. Fireflies Suns vs. Fireflies

Follow on MiLB First Pitch  https //stza.co/+xGE_-p

Shop  https //stza.co/+xGE_-3R

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Suns vs. Fireflies
END:VALARM
DTSTART:20180711T230500Z
DTEND:20180712T020500Z
UID:gcNLhSEidu_O5Y_65f5eZilt@stanza.co
SUMMARY:Suns vs. Fireflies
DESCRIPTION:Suns vs. Fireflies\n\nFollow on MiLB First Pitch: https://stza.co/+xGE_-p\n\nShop: https://stza.co/+xGE_-3R\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144530Z
LAST-MODIFIED:20180213T144530Z
TRANSP:OPAQUE
END:VEVENT
* Suns vs. Fireflies
<2018-07-12 Thu 18:05-21:05>
:PROPERTIES:
:ID:       fDVrEpp_0eBSrAPyf_2VXrXb@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Suns vs. Fireflies Suns vs. Fireflies

Follow on MiLB First Pitch  https //stza.co/+xGF1-V

Shop  https //stza.co/+xGF1-3Y

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Suns vs. Fireflies
END:VALARM
DTSTART:20180712T230500Z
DTEND:20180713T020500Z
UID:fDVrEpp_0eBSrAPyf_2VXrXb@stanza.co
SUMMARY:Suns vs. Fireflies
DESCRIPTION:Suns vs. Fireflies\n\nFollow on MiLB First Pitch: https://stza.co/+xGF1-V\n\nShop: https://stza.co/+xGF1-3Y\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144530Z
LAST-MODIFIED:20180213T144530Z
TRANSP:OPAQUE
END:VEVENT
* Suns vs. Fireflies
<2018-07-13 Fri 18:05-21:05>
:PROPERTIES:
:ID:       RakeuOdwMsbPrlDOoFCg8NuA@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Suns vs. Fireflies Suns vs. Fireflies

Follow on MiLB First Pitch  https //stza.co/+xGF3-3L

Shop  https //stza.co/+xGF3-O

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Suns vs. Fireflies
END:VALARM
DTSTART:20180713T230500Z
DTEND:20180714T020500Z
UID:RakeuOdwMsbPrlDOoFCg8NuA@stanza.co
SUMMARY:Suns vs. Fireflies
DESCRIPTION:Suns vs. Fireflies\n\nFollow on MiLB First Pitch: https://stza.co/+xGF3-3L\n\nShop: https://stza.co/+xGF3-O\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144530Z
LAST-MODIFIED:20180213T144530Z
TRANSP:OPAQUE
END:VEVENT
* Suns @ Intimidators
<2018-07-14 Sat 18:05-21:05>
:PROPERTIES:
:ID:       DPQR5A0zrj71r_fhkWoetnu5@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Suns @ Intimidators Suns @ Intimidators

Follow on MiLB First Pitch  https //stza.co/+wICH-1J

Shop  https //stza.co/+wICH-A

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Suns @ Intimidators
END:VALARM
DTSTART:20180714T230500Z
DTEND:20180715T020500Z
UID:DPQR5A0zrj71r_fhkWoetnu5@stanza.co
SUMMARY:Suns @ Intimidators
DESCRIPTION:Suns @ Intimidators\n\nFollow on MiLB First Pitch: https://stza.co/+wICH-1J\n\nShop: https://stza.co/+wICH-A\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144530Z
LAST-MODIFIED:20180213T144530Z
TRANSP:OPAQUE
END:VEVENT
* Suns @ Intimidators
<2018-07-15 Sun 16:05-19:05>
:PROPERTIES:
:ID:       lxu5SZALTI0eJBRc3klFLxxx@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Suns @ Intimidators Suns @ Intimidators

Follow on MiLB First Pitch  https //stza.co/+wICI-22

Shop  https //stza.co/+wICI-3F

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Suns @ Intimidators
END:VALARM
DTSTART:20180715T210500Z
DTEND:20180716T000500Z
UID:lxu5SZALTI0eJBRc3klFLxxx@stanza.co
SUMMARY:Suns @ Intimidators
DESCRIPTION:Suns @ Intimidators\n\nFollow on MiLB First Pitch: https://stza.co/+wICI-22\n\nShop: https://stza.co/+wICI-3F\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144530Z
LAST-MODIFIED:20180213T144530Z
TRANSP:OPAQUE
END:VEVENT
* Suns @ Intimidators
<2018-07-16 Mon 18:05-21:05>
:PROPERTIES:
:ID:       yOSVXJTdtdEmPPOKdyticwv2@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Suns @ Intimidators Suns @ Intimidators

Follow on MiLB First Pitch  https //stza.co/+wICJ-18

Shop  https //stza.co/+wICJ-3f

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Suns @ Intimidators
END:VALARM
DTSTART:20180716T230500Z
DTEND:20180717T020500Z
UID:yOSVXJTdtdEmPPOKdyticwv2@stanza.co
SUMMARY:Suns @ Intimidators
DESCRIPTION:Suns @ Intimidators\n\nFollow on MiLB First Pitch: https://stza.co/+wICJ-18\n\nShop: https://stza.co/+wICJ-3f\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144530Z
LAST-MODIFIED:20180213T144530Z
TRANSP:OPAQUE
END:VEVENT
* Suns @ Intimidators
<2018-07-17 Tue 11:05-14:05>
:PROPERTIES:
:ID:       JLZ4Jfe9Zo0DvA2zDbO0V2-L@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Suns @ Intimidators Suns @ Intimidators

Follow on MiLB First Pitch  https //stza.co/+wRH$-32

Shop  https //stza.co/+wRH$-13

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Suns @ Intimidators
END:VALARM
DTSTART:20180717T160500Z
DTEND:20180717T190500Z
UID:JLZ4Jfe9Zo0DvA2zDbO0V2-L@stanza.co
SUMMARY:Suns @ Intimidators
DESCRIPTION:Suns @ Intimidators\n\nFollow on MiLB First Pitch: https://stza.co/+wRH$-32\n\nShop: https://stza.co/+wRH$-13\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144530Z
LAST-MODIFIED:20180213T144530Z
TRANSP:OPAQUE
END:VEVENT
* Suns vs. BlueClaws
<2018-07-19 Thu 18:05-21:05>
:PROPERTIES:
:ID:       -uDeJkGEPjkZ-YCz_qhURWjE@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Suns vs. BlueClaws Suns vs. BlueClaws

Follow on MiLB First Pitch  https //stza.co/+xGF5-21

Shop  https //stza.co/+xGF5-1Z

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Suns vs. BlueClaws
END:VALARM
DTSTART:20180719T230500Z
DTEND:20180720T020500Z
UID:-uDeJkGEPjkZ-YCz_qhURWjE@stanza.co
SUMMARY:Suns vs. BlueClaws
DESCRIPTION:Suns vs. BlueClaws\n\nFollow on MiLB First Pitch: https://stza.co/+xGF5-21\n\nShop: https://stza.co/+xGF5-1Z\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144530Z
LAST-MODIFIED:20180213T144530Z
TRANSP:OPAQUE
END:VEVENT
* Suns vs. BlueClaws
<2018-07-20 Fri 18:05-21:05>
:PROPERTIES:
:ID:       QgR99P4erRnC9fVwdhsMKhG2@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Suns vs. BlueClaws Suns vs. BlueClaws

Follow on MiLB First Pitch  https //stza.co/+xGF6-c

Shop  https //stza.co/+xGF6-30

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Suns vs. BlueClaws
END:VALARM
DTSTART:20180720T230500Z
DTEND:20180721T020500Z
UID:QgR99P4erRnC9fVwdhsMKhG2@stanza.co
SUMMARY:Suns vs. BlueClaws
DESCRIPTION:Suns vs. BlueClaws\n\nFollow on MiLB First Pitch: https://stza.co/+xGF6-c\n\nShop: https://stza.co/+xGF6-30\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144530Z
LAST-MODIFIED:20180213T144530Z
TRANSP:OPAQUE
END:VEVENT
* Suns vs. BlueClaws
<2018-07-21 Sat 17:05-20:05>
:PROPERTIES:
:ID:       JdMPwmy17WVVzhQ6AHLZqvSX@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Suns vs. BlueClaws Suns vs. BlueClaws

Follow on MiLB First Pitch  https //stza.co/+xGF9-3U

Shop  https //stza.co/+xGF9-i

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Suns vs. BlueClaws
END:VALARM
DTSTART:20180721T220500Z
DTEND:20180722T010500Z
UID:JdMPwmy17WVVzhQ6AHLZqvSX@stanza.co
SUMMARY:Suns vs. BlueClaws
DESCRIPTION:Suns vs. BlueClaws\n\nFollow on MiLB First Pitch: https://stza.co/+xGF9-3U\n\nShop: https://stza.co/+xGF9-i\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144530Z
LAST-MODIFIED:20180213T144530Z
TRANSP:OPAQUE
END:VEVENT
* Suns vs. BlueClaws
<2018-07-22 Sun 13:05-16:05>
:PROPERTIES:
:ID:       AIcmIoNvQ3Dd1LT7LOw2G0p8@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Suns vs. BlueClaws Suns vs. BlueClaws

Follow on MiLB First Pitch  https //stza.co/+xGFc-S

Shop  https //stza.co/+xGFc-3r

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Suns vs. BlueClaws
END:VALARM
DTSTART:20180722T180500Z
DTEND:20180722T210500Z
UID:AIcmIoNvQ3Dd1LT7LOw2G0p8@stanza.co
SUMMARY:Suns vs. BlueClaws
DESCRIPTION:Suns vs. BlueClaws\n\nFollow on MiLB First Pitch: https://stza.co/+xGFc-S\n\nShop: https://stza.co/+xGFc-3r\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144530Z
LAST-MODIFIED:20180213T144530Z
TRANSP:OPAQUE
END:VEVENT
* Suns vs. Shorebirds
<2018-07-23 Mon 18:05-21:05>
:PROPERTIES:
:ID:       DRR-EYvtiS2lBz5TpYAGHYFU@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Suns vs. Shorebirds Suns vs. Shorebirds

Follow on MiLB First Pitch  https //stza.co/+xGFd-2S

Shop  https //stza.co/+xGFd-7

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Suns vs. Shorebirds
END:VALARM
DTSTART:20180723T230500Z
DTEND:20180724T020500Z
UID:DRR-EYvtiS2lBz5TpYAGHYFU@stanza.co
SUMMARY:Suns vs. Shorebirds
DESCRIPTION:Suns vs. Shorebirds\n\nFollow on MiLB First Pitch: https://stza.co/+xGFd-2S\n\nShop: https://stza.co/+xGFd-7\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144530Z
LAST-MODIFIED:20180213T144530Z
TRANSP:OPAQUE
END:VEVENT
* Suns vs. Shorebirds
<2018-07-24 Tue 18:05-21:05>
:PROPERTIES:
:ID:       zJz2kFv8dTg_hYxiGqvks3xv@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Suns vs. Shorebirds Suns vs. Shorebirds

Follow on MiLB First Pitch  https //stza.co/+xGFg-o

Shop  https //stza.co/+xGFg-q

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Suns vs. Shorebirds
END:VALARM
DTSTART:20180724T230500Z
DTEND:20180725T020500Z
UID:zJz2kFv8dTg_hYxiGqvks3xv@stanza.co
SUMMARY:Suns vs. Shorebirds
DESCRIPTION:Suns vs. Shorebirds\n\nFollow on MiLB First Pitch: https://stza.co/+xGFg-o\n\nShop: https://stza.co/+xGFg-q\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144530Z
LAST-MODIFIED:20180213T144530Z
TRANSP:OPAQUE
END:VEVENT
* Suns vs. Shorebirds
<2018-07-25 Wed 18:05-21:05>
:PROPERTIES:
:ID:       U0BeTPMiV12qvAxUdkSy6t0V@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Suns vs. Shorebirds Suns vs. Shorebirds

Follow on MiLB First Pitch  https //stza.co/+xGFi-1k

Shop  https //stza.co/+xGFi-1s

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Suns vs. Shorebirds
END:VALARM
DTSTART:20180725T230500Z
DTEND:20180726T020500Z
UID:U0BeTPMiV12qvAxUdkSy6t0V@stanza.co
SUMMARY:Suns vs. Shorebirds
DESCRIPTION:Suns vs. Shorebirds\n\nFollow on MiLB First Pitch: https://stza.co/+xGFi-1k\n\nShop: https://stza.co/+xGFi-1s\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144530Z
LAST-MODIFIED:20180213T144530Z
TRANSP:OPAQUE
END:VEVENT
* Suns vs. Shorebirds
<2018-07-26 Thu 18:05-21:05>
:PROPERTIES:
:ID:       Ye7JPhjrh858gPT3bJL0bKeu@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Suns vs. Shorebirds Suns vs. Shorebirds

Follow on MiLB First Pitch  https //stza.co/+xGFj-11

Shop  https //stza.co/+xGFj-2b

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Suns vs. Shorebirds
END:VALARM
DTSTART:20180726T230500Z
DTEND:20180727T020500Z
UID:Ye7JPhjrh858gPT3bJL0bKeu@stanza.co
SUMMARY:Suns vs. Shorebirds
DESCRIPTION:Suns vs. Shorebirds\n\nFollow on MiLB First Pitch: https://stza.co/+xGFj-11\n\nShop: https://stza.co/+xGFj-2b\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144530Z
LAST-MODIFIED:20180213T144530Z
TRANSP:OPAQUE
END:VEVENT
* Suns @ BlueClaws
<2018-07-27 Fri 18:05-21:05>
:PROPERTIES:
:ID:       5SWtVdWu3nFW0O82uaBjmf6G@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Suns @ BlueClaws Suns @ BlueClaws

Follow on MiLB First Pitch  https //stza.co/+vNLV-12

Shop  https //stza.co/+vNLV-3p

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Suns @ BlueClaws
END:VALARM
DTSTART:20180727T230500Z
DTEND:20180728T020500Z
UID:5SWtVdWu3nFW0O82uaBjmf6G@stanza.co
SUMMARY:Suns @ BlueClaws
DESCRIPTION:Suns @ BlueClaws\n\nFollow on MiLB First Pitch: https://stza.co/+vNLV-12\n\nShop: https://stza.co/+vNLV-3p\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144530Z
LAST-MODIFIED:20180213T144530Z
TRANSP:OPAQUE
END:VEVENT
* Suns @ BlueClaws
<2018-07-28 Sat 18:05-21:05>
:PROPERTIES:
:ID:       Fzji_CXsej_YrNQX8VTyjobe@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Suns @ BlueClaws Suns @ BlueClaws

Follow on MiLB First Pitch  https //stza.co/+vNLW-2C

Shop  https //stza.co/+vNLW-2v

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Suns @ BlueClaws
END:VALARM
DTSTART:20180728T230500Z
DTEND:20180729T020500Z
UID:Fzji_CXsej_YrNQX8VTyjobe@stanza.co
SUMMARY:Suns @ BlueClaws
DESCRIPTION:Suns @ BlueClaws\n\nFollow on MiLB First Pitch: https://stza.co/+vNLW-2C\n\nShop: https://stza.co/+vNLW-2v\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144530Z
LAST-MODIFIED:20180213T144530Z
TRANSP:OPAQUE
END:VEVENT
* Suns @ BlueClaws
<2018-07-29 Sun 12:05-15:05>
:PROPERTIES:
:ID:       kXKeQ-g6pFSAfkUHn6Zmg3OI@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Suns @ BlueClaws Suns @ BlueClaws

Follow on MiLB First Pitch  https //stza.co/+vNLX-1W

Shop  https //stza.co/+vNLX-2O

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Suns @ BlueClaws
END:VALARM
DTSTART:20180729T170500Z
DTEND:20180729T200500Z
UID:kXKeQ-g6pFSAfkUHn6Zmg3OI@stanza.co
SUMMARY:Suns @ BlueClaws
DESCRIPTION:Suns @ BlueClaws\n\nFollow on MiLB First Pitch: https://stza.co/+vNLX-1W\n\nShop: https://stza.co/+vNLX-2O\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144530Z
LAST-MODIFIED:20180213T144530Z
TRANSP:OPAQUE
END:VEVENT
* Suns vs. Legends
<2018-07-30 Mon 18:05-21:05>
:PROPERTIES:
:ID:       slOoN8LJnf7xEu-q5O08eA-J@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Suns vs. Legends Suns vs. Legends

Follow on MiLB First Pitch  https //stza.co/+xGFm-B

Shop  https //stza.co/+xGFm-3a

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Suns vs. Legends
END:VALARM
DTSTART:20180730T230500Z
DTEND:20180731T020500Z
UID:slOoN8LJnf7xEu-q5O08eA-J@stanza.co
SUMMARY:Suns vs. Legends
DESCRIPTION:Suns vs. Legends\n\nFollow on MiLB First Pitch: https://stza.co/+xGFm-B\n\nShop: https://stza.co/+xGFm-3a\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144530Z
LAST-MODIFIED:20180213T144530Z
TRANSP:OPAQUE
END:VEVENT
* Suns vs. Legends
<2018-07-31 Tue 18:05-21:05>
:PROPERTIES:
:ID:       cRWRKxVZB9j4Xe5eVZV4k3Kq@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Suns vs. Legends Suns vs. Legends

Follow on MiLB First Pitch  https //stza.co/+xGFo-2G

Shop  https //stza.co/+xGFo-30

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Suns vs. Legends
END:VALARM
DTSTART:20180731T230500Z
DTEND:20180801T020500Z
UID:cRWRKxVZB9j4Xe5eVZV4k3Kq@stanza.co
SUMMARY:Suns vs. Legends
DESCRIPTION:Suns vs. Legends\n\nFollow on MiLB First Pitch: https://stza.co/+xGFo-2G\n\nShop: https://stza.co/+xGFo-30\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144530Z
LAST-MODIFIED:20180213T144530Z
TRANSP:OPAQUE
END:VEVENT
* Suns vs. Legends
<2018-08-01 Wed 09:35-12:35>
:PROPERTIES:
:ID:       -ozVoQmI5BpaKtGavdRF9UW1@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Suns vs. Legends Suns vs. Legends

Follow on MiLB First Pitch  https //stza.co/+xGFq-D

Shop  https //stza.co/+xGFq-1K

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Suns vs. Legends
END:VALARM
DTSTART:20180801T143500Z
DTEND:20180801T173500Z
UID:-ozVoQmI5BpaKtGavdRF9UW1@stanza.co
SUMMARY:Suns vs. Legends
DESCRIPTION:Suns vs. Legends\n\nFollow on MiLB First Pitch: https://stza.co/+xGFq-D\n\nShop: https://stza.co/+xGFq-1K\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144530Z
LAST-MODIFIED:20180213T144530Z
TRANSP:OPAQUE
END:VEVENT
* Suns vs. Crawdads
<2018-08-02 Thu 18:05-21:05>
:PROPERTIES:
:ID:       3Q3a-ySQrLTmIljejOIzQHbf@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Suns vs. Crawdads Suns vs. Crawdads

Follow on MiLB First Pitch  https //stza.co/+xGFs-3W

Shop  https //stza.co/+xGFs-35

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Suns vs. Crawdads
END:VALARM
DTSTART:20180802T230500Z
DTEND:20180803T020500Z
UID:3Q3a-ySQrLTmIljejOIzQHbf@stanza.co
SUMMARY:Suns vs. Crawdads
DESCRIPTION:Suns vs. Crawdads\n\nFollow on MiLB First Pitch: https://stza.co/+xGFs-3W\n\nShop: https://stza.co/+xGFs-35\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144530Z
LAST-MODIFIED:20180213T144530Z
TRANSP:OPAQUE
END:VEVENT
* Suns vs. Crawdads
<2018-08-03 Fri 18:05-21:05>
:PROPERTIES:
:ID:       2896gl3cCSyLr2OhaGYk6uto@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Suns vs. Crawdads Suns vs. Crawdads

Follow on MiLB First Pitch  https //stza.co/+xGFt-9

Shop  https //stza.co/+xGFt-14

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Suns vs. Crawdads
END:VALARM
DTSTART:20180803T230500Z
DTEND:20180804T020500Z
UID:2896gl3cCSyLr2OhaGYk6uto@stanza.co
SUMMARY:Suns vs. Crawdads
DESCRIPTION:Suns vs. Crawdads\n\nFollow on MiLB First Pitch: https://stza.co/+xGFt-9\n\nShop: https://stza.co/+xGFt-14\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144530Z
LAST-MODIFIED:20180213T144530Z
TRANSP:OPAQUE
END:VEVENT
* Suns vs. Crawdads
<2018-08-04 Sat 17:05-20:05>
:PROPERTIES:
:ID:       AEn2rqKlo9BaWhT8700prPUS@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Suns vs. Crawdads Suns vs. Crawdads

Follow on MiLB First Pitch  https //stza.co/+xGFv-2c

Shop  https //stza.co/+xGFv-3h

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Suns vs. Crawdads
END:VALARM
DTSTART:20180804T220500Z
DTEND:20180805T010500Z
UID:AEn2rqKlo9BaWhT8700prPUS@stanza.co
SUMMARY:Suns vs. Crawdads
DESCRIPTION:Suns vs. Crawdads\n\nFollow on MiLB First Pitch: https://stza.co/+xGFv-2c\n\nShop: https://stza.co/+xGFv-3h\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144530Z
LAST-MODIFIED:20180213T144530Z
TRANSP:OPAQUE
END:VEVENT
* Suns vs. Crawdads
<2018-08-05 Sun 13:05-16:05>
:PROPERTIES:
:ID:       Yp_n2KQF9E9hZcx6WbWp1IXG@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Suns vs. Crawdads Suns vs. Crawdads

Follow on MiLB First Pitch  https //stza.co/+xGFx-26

Shop  https //stza.co/+xGFx-3Z

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Suns vs. Crawdads
END:VALARM
DTSTART:20180805T180500Z
DTEND:20180805T210500Z
UID:Yp_n2KQF9E9hZcx6WbWp1IXG@stanza.co
SUMMARY:Suns vs. Crawdads
DESCRIPTION:Suns vs. Crawdads\n\nFollow on MiLB First Pitch: https://stza.co/+xGFx-26\n\nShop: https://stza.co/+xGFx-3Z\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144530Z
LAST-MODIFIED:20180213T144530Z
TRANSP:OPAQUE
END:VEVENT
* Suns @ GreenJackets
<2018-08-07 Tue 18:05-21:05>
:PROPERTIES:
:ID:       kY44EMf3bMigoiYzE6JM1KYM@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Suns @ GreenJackets Suns @ GreenJackets

Follow on MiLB First Pitch  https //stza.co/+xB3Q-3i

Shop  https //stza.co/+xB3Q-3z

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Suns @ GreenJackets
END:VALARM
DTSTART:20180807T230500Z
DTEND:20180808T020500Z
UID:kY44EMf3bMigoiYzE6JM1KYM@stanza.co
SUMMARY:Suns @ GreenJackets
DESCRIPTION:Suns @ GreenJackets\n\nFollow on MiLB First Pitch: https://stza.co/+xB3Q-3i\n\nShop: https://stza.co/+xB3Q-3z\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144530Z
LAST-MODIFIED:20180213T144530Z
TRANSP:OPAQUE
END:VEVENT
* Suns @ GreenJackets
<2018-08-08 Wed 18:05-21:05>
:PROPERTIES:
:ID:       TW4ftB4hVwW3MBADjuPQR8z4@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Suns @ GreenJackets Suns @ GreenJackets

Follow on MiLB First Pitch  https //stza.co/+xB3R-3l

Shop  https //stza.co/+xB3R-H

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Suns @ GreenJackets
END:VALARM
DTSTART:20180808T230500Z
DTEND:20180809T020500Z
UID:TW4ftB4hVwW3MBADjuPQR8z4@stanza.co
SUMMARY:Suns @ GreenJackets
DESCRIPTION:Suns @ GreenJackets\n\nFollow on MiLB First Pitch: https://stza.co/+xB3R-3l\n\nShop: https://stza.co/+xB3R-H\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144530Z
LAST-MODIFIED:20180213T144530Z
TRANSP:OPAQUE
END:VEVENT
* Suns @ GreenJackets
<2018-08-09 Thu 18:05-21:05>
:PROPERTIES:
:ID:       LSmv2zKIeVKhkC7uhtUbr_AS@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Suns @ GreenJackets Suns @ GreenJackets

Follow on MiLB First Pitch  https //stza.co/+xB3S-3

Shop  https //stza.co/+xB3S-1O

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Suns @ GreenJackets
END:VALARM
DTSTART:20180809T230500Z
DTEND:20180810T020500Z
UID:LSmv2zKIeVKhkC7uhtUbr_AS@stanza.co
SUMMARY:Suns @ GreenJackets
DESCRIPTION:Suns @ GreenJackets\n\nFollow on MiLB First Pitch: https://stza.co/+xB3S-3\n\nShop: https://stza.co/+xB3S-1O\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144530Z
LAST-MODIFIED:20180213T144530Z
TRANSP:OPAQUE
END:VEVENT
* Suns @ RiverDogs
<2018-08-10 Fri 18:05-21:05>
:PROPERTIES:
:ID:       HM0GqHgr6DVz__3c1jhBIcV5@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Suns @ RiverDogs Suns @ RiverDogs

Follow on MiLB First Pitch  https //stza.co/+vNJ0-3v

Shop  https //stza.co/+vNJ0-3F

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Suns @ RiverDogs
END:VALARM
DTSTART:20180810T230500Z
DTEND:20180811T020500Z
UID:HM0GqHgr6DVz__3c1jhBIcV5@stanza.co
SUMMARY:Suns @ RiverDogs
DESCRIPTION:Suns @ RiverDogs\n\nFollow on MiLB First Pitch: https://stza.co/+vNJ0-3v\n\nShop: https://stza.co/+vNJ0-3F\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144530Z
LAST-MODIFIED:20180213T144530Z
TRANSP:OPAQUE
END:VEVENT
* Suns @ RiverDogs
<2018-08-11 Sat 17:05-20:05>
:PROPERTIES:
:ID:       4dqZYUhNOiDz7coyNm5MYxnq@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Suns @ RiverDogs Suns @ RiverDogs

Follow on MiLB First Pitch  https //stza.co/+vNJ1-8

Shop  https //stza.co/+vNJ1-16

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Suns @ RiverDogs
END:VALARM
DTSTART:20180811T220500Z
DTEND:20180812T010500Z
UID:4dqZYUhNOiDz7coyNm5MYxnq@stanza.co
SUMMARY:Suns @ RiverDogs
DESCRIPTION:Suns @ RiverDogs\n\nFollow on MiLB First Pitch: https://stza.co/+vNJ1-8\n\nShop: https://stza.co/+vNJ1-16\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144530Z
LAST-MODIFIED:20180213T144530Z
TRANSP:OPAQUE
END:VEVENT
* Suns @ RiverDogs
<2018-08-12 Sun 16:05-19:05>
:PROPERTIES:
:ID:       ZnTeoADzYPkPCFqwSctUAaNq@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Suns @ RiverDogs Suns @ RiverDogs

Follow on MiLB First Pitch  https //stza.co/+vNJ2-$

Shop  https //stza.co/+vNJ2-3R

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Suns @ RiverDogs
END:VALARM
DTSTART:20180812T210500Z
DTEND:20180813T000500Z
UID:ZnTeoADzYPkPCFqwSctUAaNq@stanza.co
SUMMARY:Suns @ RiverDogs
DESCRIPTION:Suns @ RiverDogs\n\nFollow on MiLB First Pitch: https://stza.co/+vNJ2-$\n\nShop: https://stza.co/+vNJ2-3R\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144530Z
LAST-MODIFIED:20180213T144530Z
TRANSP:OPAQUE
END:VEVENT
* Suns @ RiverDogs
<2018-08-13 Mon 18:05-21:05>
:PROPERTIES:
:ID:       K4aC2p2xfWLx8Akbsz2rvGjs@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Suns @ RiverDogs Suns @ RiverDogs

Follow on MiLB First Pitch  https //stza.co/+vNJ3-2S

Shop  https //stza.co/+vNJ3-28

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Suns @ RiverDogs
END:VALARM
DTSTART:20180813T230500Z
DTEND:20180814T020500Z
UID:K4aC2p2xfWLx8Akbsz2rvGjs@stanza.co
SUMMARY:Suns @ RiverDogs
DESCRIPTION:Suns @ RiverDogs\n\nFollow on MiLB First Pitch: https://stza.co/+vNJ3-2S\n\nShop: https://stza.co/+vNJ3-28\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144530Z
LAST-MODIFIED:20180213T144530Z
TRANSP:OPAQUE
END:VEVENT
* Suns vs. Legends
<2018-08-15 Wed 18:05-21:05>
:PROPERTIES:
:ID:       TS_NGoEncvTGBDVmiinLW6kj@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Suns vs. Legends Suns vs. Legends

Follow on MiLB First Pitch  https //stza.co/+xGFA-1E

Shop  https //stza.co/+xGFA-3d

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Suns vs. Legends
END:VALARM
DTSTART:20180815T230500Z
DTEND:20180816T020500Z
UID:TS_NGoEncvTGBDVmiinLW6kj@stanza.co
SUMMARY:Suns vs. Legends
DESCRIPTION:Suns vs. Legends\n\nFollow on MiLB First Pitch: https://stza.co/+xGFA-1E\n\nShop: https://stza.co/+xGFA-3d\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144530Z
LAST-MODIFIED:20180213T144530Z
TRANSP:OPAQUE
END:VEVENT
* Suns vs. Legends
<2018-08-16 Thu 18:05-21:05>
:PROPERTIES:
:ID:       ZjIlKmoFLr9uUrFuvIggxhHA@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Suns vs. Legends Suns vs. Legends

Follow on MiLB First Pitch  https //stza.co/+xGFC-2X

Shop  https //stza.co/+xGFC-3Q

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Suns vs. Legends
END:VALARM
DTSTART:20180816T230500Z
DTEND:20180817T020500Z
UID:ZjIlKmoFLr9uUrFuvIggxhHA@stanza.co
SUMMARY:Suns vs. Legends
DESCRIPTION:Suns vs. Legends\n\nFollow on MiLB First Pitch: https://stza.co/+xGFC-2X\n\nShop: https://stza.co/+xGFC-3Q\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144530Z
LAST-MODIFIED:20180213T144530Z
TRANSP:OPAQUE
END:VEVENT
* Suns vs. Legends
<2018-08-17 Fri 18:05-21:05>
:PROPERTIES:
:ID:       pKepzmQx-SphV7EKOeorJvf2@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Suns vs. Legends Suns vs. Legends

Follow on MiLB First Pitch  https //stza.co/+xGFF-3E

Shop  https //stza.co/+xGFF-3v

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Suns vs. Legends
END:VALARM
DTSTART:20180817T230500Z
DTEND:20180818T020500Z
UID:pKepzmQx-SphV7EKOeorJvf2@stanza.co
SUMMARY:Suns vs. Legends
DESCRIPTION:Suns vs. Legends\n\nFollow on MiLB First Pitch: https://stza.co/+xGFF-3E\n\nShop: https://stza.co/+xGFF-3v\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144530Z
LAST-MODIFIED:20180213T144530Z
TRANSP:OPAQUE
END:VEVENT
* Suns vs. Fireflies
<2018-08-18 Sat 17:05-20:05>
:PROPERTIES:
:ID:       UpaiQwVHDSA5q_vuVAxt-Uoj@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Suns vs. Fireflies Suns vs. Fireflies

Follow on MiLB First Pitch  https //stza.co/+xGFG-F

Shop  https //stza.co/+xGFG-J

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Suns vs. Fireflies
END:VALARM
DTSTART:20180818T220500Z
DTEND:20180819T010500Z
UID:UpaiQwVHDSA5q_vuVAxt-Uoj@stanza.co
SUMMARY:Suns vs. Fireflies
DESCRIPTION:Suns vs. Fireflies\n\nFollow on MiLB First Pitch: https://stza.co/+xGFG-F\n\nShop: https://stza.co/+xGFG-J\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144530Z
LAST-MODIFIED:20180213T144530Z
TRANSP:OPAQUE
END:VEVENT
* Suns vs. Fireflies
<2018-08-19 Sun 13:05-16:05>
:PROPERTIES:
:ID:       SR-tcvEaIQL3LBBCmpl4KoYr@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Suns vs. Fireflies Suns vs. Fireflies

Follow on MiLB First Pitch  https //stza.co/+xGFI-3J

Shop  https //stza.co/+xGFI-1u

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Suns vs. Fireflies
END:VALARM
DTSTART:20180819T180500Z
DTEND:20180819T210500Z
UID:SR-tcvEaIQL3LBBCmpl4KoYr@stanza.co
SUMMARY:Suns vs. Fireflies
DESCRIPTION:Suns vs. Fireflies\n\nFollow on MiLB First Pitch: https://stza.co/+xGFI-3J\n\nShop: https://stza.co/+xGFI-1u\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144530Z
LAST-MODIFIED:20180213T144530Z
TRANSP:OPAQUE
END:VEVENT
* Suns vs. Fireflies
<2018-08-20 Mon 18:05-21:05>
:PROPERTIES:
:ID:       8sS4J02QVqmwMr3u5YvLN6UE@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Suns vs. Fireflies Suns vs. Fireflies

Follow on MiLB First Pitch  https //stza.co/+xGFK-3B

Shop  https //stza.co/+xGFK-3i

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Suns vs. Fireflies
END:VALARM
DTSTART:20180820T230500Z
DTEND:20180821T020500Z
UID:8sS4J02QVqmwMr3u5YvLN6UE@stanza.co
SUMMARY:Suns vs. Fireflies
DESCRIPTION:Suns vs. Fireflies\n\nFollow on MiLB First Pitch: https://stza.co/+xGFK-3B\n\nShop: https://stza.co/+xGFK-3i\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144530Z
LAST-MODIFIED:20180213T144530Z
TRANSP:OPAQUE
END:VEVENT
* Suns vs. Fireflies
<2018-08-21 Tue 13:05-16:05>
:PROPERTIES:
:ID:       HCoKGYI0lSI8weZCQBXKIIoD@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Suns vs. Fireflies Suns vs. Fireflies

Follow on MiLB First Pitch  https //stza.co/+xGFM-2E

Shop  https //stza.co/+xGFM-1k

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Suns vs. Fireflies
END:VALARM
DTSTART:20180821T180500Z
DTEND:20180821T210500Z
UID:HCoKGYI0lSI8weZCQBXKIIoD@stanza.co
SUMMARY:Suns vs. Fireflies
DESCRIPTION:Suns vs. Fireflies\n\nFollow on MiLB First Pitch: https://stza.co/+xGFM-2E\n\nShop: https://stza.co/+xGFM-1k\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144530Z
LAST-MODIFIED:20180213T144530Z
TRANSP:OPAQUE
END:VEVENT
* Suns @ Legends
<2018-08-23 Thu 18:05-21:05>
:PROPERTIES:
:ID:       FP3k-TNMiyqW0TOSmoLHi4A8@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Suns @ Legends Suns @ Legends

Follow on MiLB First Pitch  https //stza.co/+xB4h-C

Shop  https //stza.co/+xB4h-1C

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Suns @ Legends
END:VALARM
DTSTART:20180823T230500Z
DTEND:20180824T020500Z
UID:FP3k-TNMiyqW0TOSmoLHi4A8@stanza.co
SUMMARY:Suns @ Legends
DESCRIPTION:Suns @ Legends\n\nFollow on MiLB First Pitch: https://stza.co/+xB4h-C\n\nShop: https://stza.co/+xB4h-1C\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144530Z
LAST-MODIFIED:20180213T144530Z
TRANSP:OPAQUE
END:VEVENT
* Suns @ Legends
<2018-08-24 Fri 18:05-21:05>
:PROPERTIES:
:ID:       rc-gwx6to57uRh8JvJUuucIR@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Suns @ Legends Suns @ Legends

Follow on MiLB First Pitch  https //stza.co/+xB4i-19

Shop  https //stza.co/+xB4i-35

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Suns @ Legends
END:VALARM
DTSTART:20180824T230500Z
DTEND:20180825T020500Z
UID:rc-gwx6to57uRh8JvJUuucIR@stanza.co
SUMMARY:Suns @ Legends
DESCRIPTION:Suns @ Legends\n\nFollow on MiLB First Pitch: https://stza.co/+xB4i-19\n\nShop: https://stza.co/+xB4i-35\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144530Z
LAST-MODIFIED:20180213T144530Z
TRANSP:OPAQUE
END:VEVENT
* Suns @ Legends
<2018-08-25 Sat 17:35-20:35>
:PROPERTIES:
:ID:       Uu3OVhP4G00495NKytyqdUrl@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Suns @ Legends Suns @ Legends

Follow on MiLB First Pitch  https //stza.co/+xB4j-2P

Shop  https //stza.co/+xB4j-E

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Suns @ Legends
END:VALARM
DTSTART:20180825T223500Z
DTEND:20180826T013500Z
UID:Uu3OVhP4G00495NKytyqdUrl@stanza.co
SUMMARY:Suns @ Legends
DESCRIPTION:Suns @ Legends\n\nFollow on MiLB First Pitch: https://stza.co/+xB4j-2P\n\nShop: https://stza.co/+xB4j-E\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144530Z
LAST-MODIFIED:20180213T144530Z
TRANSP:OPAQUE
END:VEVENT
* Suns @ Legends
<2018-08-26 Sun 13:05-16:05>
:PROPERTIES:
:ID:       EAveyzfE_mNUrK9juf7mmLFv@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Suns @ Legends Suns @ Legends

Follow on MiLB First Pitch  https //stza.co/+xB4k-37

Shop  https //stza.co/+xB4k-1c

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Suns @ Legends
END:VALARM
DTSTART:20180826T180500Z
DTEND:20180826T210500Z
UID:EAveyzfE_mNUrK9juf7mmLFv@stanza.co
SUMMARY:Suns @ Legends
DESCRIPTION:Suns @ Legends\n\nFollow on MiLB First Pitch: https://stza.co/+xB4k-37\n\nShop: https://stza.co/+xB4k-1c\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144530Z
LAST-MODIFIED:20180213T144530Z
TRANSP:OPAQUE
END:VEVENT
* Suns @ Power
<2018-08-27 Mon 18:05-21:05>
:PROPERTIES:
:ID:       69x4Sk_GbzB23VzbdmN57yYm@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Suns @ Power Suns @ Power

Follow on MiLB First Pitch  https //stza.co/+xJ3T-2o

Shop  https //stza.co/+xJ3T-1_

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Suns @ Power
END:VALARM
DTSTART:20180827T230500Z
DTEND:20180828T020500Z
UID:69x4Sk_GbzB23VzbdmN57yYm@stanza.co
SUMMARY:Suns @ Power
DESCRIPTION:Suns @ Power\n\nFollow on MiLB First Pitch: https://stza.co/+xJ3T-2o\n\nShop: https://stza.co/+xJ3T-1_\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144530Z
LAST-MODIFIED:20180213T144530Z
TRANSP:OPAQUE
END:VEVENT
* Suns @ Power
<2018-08-28 Tue 18:05-21:05>
:PROPERTIES:
:ID:       f0J_5oxZjkckxqsyd9hAYscq@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Suns @ Power Suns @ Power

Follow on MiLB First Pitch  https //stza.co/+xJ3U-Z

Shop  https //stza.co/+xJ3U-3T

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Suns @ Power
END:VALARM
DTSTART:20180828T230500Z
DTEND:20180829T020500Z
UID:f0J_5oxZjkckxqsyd9hAYscq@stanza.co
SUMMARY:Suns @ Power
DESCRIPTION:Suns @ Power\n\nFollow on MiLB First Pitch: https://stza.co/+xJ3U-Z\n\nShop: https://stza.co/+xJ3U-3T\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144530Z
LAST-MODIFIED:20180213T144530Z
TRANSP:OPAQUE
END:VEVENT
* Suns @ Power
<2018-08-29 Wed 18:05-21:05>
:PROPERTIES:
:ID:       fbEmQP0tYnuIR5NmsDpoBWlo@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Suns @ Power Suns @ Power

Follow on MiLB First Pitch  https //stza.co/+xJ3V-2l

Shop  https //stza.co/+xJ3V-2v

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Suns @ Power
END:VALARM
DTSTART:20180829T230500Z
DTEND:20180830T020500Z
UID:fbEmQP0tYnuIR5NmsDpoBWlo@stanza.co
SUMMARY:Suns @ Power
DESCRIPTION:Suns @ Power\n\nFollow on MiLB First Pitch: https://stza.co/+xJ3V-2l\n\nShop: https://stza.co/+xJ3V-2v\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144530Z
LAST-MODIFIED:20180213T144530Z
TRANSP:OPAQUE
END:VEVENT
* Suns @ Power
<2018-08-30 Thu 18:05-21:05>
:PROPERTIES:
:ID:       tbXDFBBjtfLY0diMwdCrN0Qm@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Suns @ Power Suns @ Power

Follow on MiLB First Pitch  https //stza.co/+xJ3W-2K

Shop  https //stza.co/+xJ3W-j

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Suns @ Power
END:VALARM
DTSTART:20180830T230500Z
DTEND:20180831T020500Z
UID:tbXDFBBjtfLY0diMwdCrN0Qm@stanza.co
SUMMARY:Suns @ Power
DESCRIPTION:Suns @ Power\n\nFollow on MiLB First Pitch: https://stza.co/+xJ3W-2K\n\nShop: https://stza.co/+xJ3W-j\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144530Z
LAST-MODIFIED:20180213T144530Z
TRANSP:OPAQUE
END:VEVENT
* Suns vs. Intimidators
<2018-08-31 Fri 18:05-21:05>
:PROPERTIES:
:ID:       Sg9VdkTjrbVjOMTrlNKAc4R6@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Suns vs. Intimidators Suns vs. Intimidators

Follow on MiLB First Pitch  https //stza.co/+xF75-3E

Shop  https //stza.co/+xF75-2i

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Suns vs. Intimidators
END:VALARM
DTSTART:20180831T230500Z
DTEND:20180901T020500Z
UID:Sg9VdkTjrbVjOMTrlNKAc4R6@stanza.co
SUMMARY:Suns vs. Intimidators
DESCRIPTION:Suns vs. Intimidators\n\nFollow on MiLB First Pitch: https://stza.co/+xF75-3E\n\nShop: https://stza.co/+xF75-2i\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144530Z
LAST-MODIFIED:20180213T144530Z
TRANSP:OPAQUE
END:VEVENT
* Suns vs. Intimidators
<2018-09-01 Sat 17:05-20:05>
:PROPERTIES:
:ID:       y3xr6LuUkV_KnnDPL_-iBag5@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Suns vs. Intimidators Suns vs. Intimidators

Follow on MiLB First Pitch  https //stza.co/+xF76-2B

Shop  https //stza.co/+xF76-1f

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Suns vs. Intimidators
END:VALARM
DTSTART:20180901T220500Z
DTEND:20180902T010500Z
UID:y3xr6LuUkV_KnnDPL_-iBag5@stanza.co
SUMMARY:Suns vs. Intimidators
DESCRIPTION:Suns vs. Intimidators\n\nFollow on MiLB First Pitch: https://stza.co/+xF76-2B\n\nShop: https://stza.co/+xF76-1f\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144530Z
LAST-MODIFIED:20180213T144530Z
TRANSP:OPAQUE
END:VEVENT
* Suns vs. Intimidators
<2018-09-02 Sun 13:05-16:05>
:PROPERTIES:
:ID:       byJnmkmJVY0wo5hHBkNjIhOx@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Suns vs. Intimidators Suns vs. Intimidators

Follow on MiLB First Pitch  https //stza.co/+xF79-1f

Shop  https //stza.co/+xF79-29

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Suns vs. Intimidators
END:VALARM
DTSTART:20180902T180500Z
DTEND:20180902T210500Z
UID:byJnmkmJVY0wo5hHBkNjIhOx@stanza.co
SUMMARY:Suns vs. Intimidators
DESCRIPTION:Suns vs. Intimidators\n\nFollow on MiLB First Pitch: https://stza.co/+xF79-1f\n\nShop: https://stza.co/+xF79-29\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144530Z
LAST-MODIFIED:20180213T144530Z
TRANSP:OPAQUE
END:VEVENT
* Suns vs. Intimidators
<2018-09-03 Mon 13:05-16:05>
:PROPERTIES:
:ID:       aNyjRzvM82dA2ufAZrui68dJ@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Suns vs. Intimidators Suns vs. Intimidators

Follow on MiLB First Pitch  https //stza.co/+xF7b-c

Shop  https //stza.co/+xF7b-1l

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Suns vs. Intimidators
END:VALARM
DTSTART:20180903T180500Z
DTEND:20180903T210500Z
UID:aNyjRzvM82dA2ufAZrui68dJ@stanza.co
SUMMARY:Suns vs. Intimidators
DESCRIPTION:Suns vs. Intimidators\n\nFollow on MiLB First Pitch: https://stza.co/+xF7b-c\n\nShop: https://stza.co/+xF7b-1l\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144530Z
LAST-MODIFIED:20180213T144530Z
TRANSP:OPAQUE
END:VEVENT
