#+TITLE:       Main Google calendar entries
#+AUTHOR:      Eric S Fraga
#+EMAIL:       e.fraga@ucl.ac.uk
#+DESCRIPTION: converted using the ical2org awk script
#+CATEGORY:    google
#+STARTUP:     hidestars
#+STARTUP:     overview

* COMMENT original iCal preamble

* RoughRiders vs. Drillers
<2018-04-05 Thu 19:05-22:05>
:PROPERTIES:
:ID:       mlgzWNVHxgUM-FowoLVHG13-@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

RoughRiders vs. Drillers RoughRiders vs. Drillers

Follow on MiLB First Pitch  https //stza.co/+wY7V-w

Shop  https //stza.co/+wY7V-k

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:RoughRiders vs. Drillers
END:VALARM
DTSTART:20180406T000500Z
DTEND:20180406T030500Z
UID:mlgzWNVHxgUM-FowoLVHG13-@stanza.co
SUMMARY:RoughRiders vs. Drillers
DESCRIPTION:RoughRiders vs. Drillers\n\nFollow on MiLB First Pitch: https://stza.co/+wY7V-w\n\nShop: https://stza.co/+wY7V-k\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144527Z
LAST-MODIFIED:20180213T144527Z
TRANSP:OPAQUE
END:VEVENT
* RoughRiders vs. Drillers
<2018-04-06 Fri 19:05-22:05>
:PROPERTIES:
:ID:       dmJgJ4SMyq4Jf6PbTuSFXSIc@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

RoughRiders vs. Drillers RoughRiders vs. Drillers

Follow on MiLB First Pitch  https //stza.co/+wY7X-3Y

Shop  https //stza.co/+wY7X-B

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:RoughRiders vs. Drillers
END:VALARM
DTSTART:20180407T000500Z
DTEND:20180407T030500Z
UID:dmJgJ4SMyq4Jf6PbTuSFXSIc@stanza.co
SUMMARY:RoughRiders vs. Drillers
DESCRIPTION:RoughRiders vs. Drillers\n\nFollow on MiLB First Pitch: https://stza.co/+wY7X-3Y\n\nShop: https://stza.co/+wY7X-B\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144527Z
LAST-MODIFIED:20180213T144527Z
TRANSP:OPAQUE
END:VEVENT
* RoughRiders vs. Drillers
<2018-04-07 Sat 19:05-22:05>
:PROPERTIES:
:ID:       6ttVSTra5ngYNkUes5khEeT4@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

RoughRiders vs. Drillers RoughRiders vs. Drillers

Follow on MiLB First Pitch  https //stza.co/+wY7Z-27

Shop  https //stza.co/+wY7Z-3w

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:RoughRiders vs. Drillers
END:VALARM
DTSTART:20180408T000500Z
DTEND:20180408T030500Z
UID:6ttVSTra5ngYNkUes5khEeT4@stanza.co
SUMMARY:RoughRiders vs. Drillers
DESCRIPTION:RoughRiders vs. Drillers\n\nFollow on MiLB First Pitch: https://stza.co/+wY7Z-27\n\nShop: https://stza.co/+wY7Z-3w\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144527Z
LAST-MODIFIED:20180213T144527Z
TRANSP:OPAQUE
END:VEVENT
* RoughRiders vs. Cardinals
<2018-04-08 Sun 16:05-19:05>
:PROPERTIES:
:ID:       kTpPZRoSlz2M4XehydCrZQ7v@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

RoughRiders vs. Cardinals RoughRiders vs. Cardinals

Follow on MiLB First Pitch  https //stza.co/+wY7$-w

Shop  https //stza.co/+wY7$-3l

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:RoughRiders vs. Cardinals
END:VALARM
DTSTART:20180408T210500Z
DTEND:20180409T000500Z
UID:kTpPZRoSlz2M4XehydCrZQ7v@stanza.co
SUMMARY:RoughRiders vs. Cardinals
DESCRIPTION:RoughRiders vs. Cardinals\n\nFollow on MiLB First Pitch: https://stza.co/+wY7$-w\n\nShop: https://stza.co/+wY7$-3l\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144527Z
LAST-MODIFIED:20180213T144527Z
TRANSP:OPAQUE
END:VEVENT
* RoughRiders vs. Cardinals
<2018-04-09 Mon 19:05-22:05>
:PROPERTIES:
:ID:       _hLRYmLZwIXH1ruvgdYzwgw-@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

RoughRiders vs. Cardinals RoughRiders vs. Cardinals

Follow on MiLB First Pitch  https //stza.co/+wY82-2c

Shop  https //stza.co/+wY82-2R

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:RoughRiders vs. Cardinals
END:VALARM
DTSTART:20180410T000500Z
DTEND:20180410T030500Z
UID:_hLRYmLZwIXH1ruvgdYzwgw-@stanza.co
SUMMARY:RoughRiders vs. Cardinals
DESCRIPTION:RoughRiders vs. Cardinals\n\nFollow on MiLB First Pitch: https://stza.co/+wY82-2c\n\nShop: https://stza.co/+wY82-2R\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144527Z
LAST-MODIFIED:20180213T144527Z
TRANSP:OPAQUE
END:VEVENT
* RoughRiders vs. Cardinals
<2018-04-10 Tue 19:05-22:05>
:PROPERTIES:
:ID:       5sfOtSKDQzMz_6F0Fa6hcN9k@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

RoughRiders vs. Cardinals RoughRiders vs. Cardinals

Follow on MiLB First Pitch  https //stza.co/+wY83-1o

Shop  https //stza.co/+wY83-3I

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:RoughRiders vs. Cardinals
END:VALARM
DTSTART:20180411T000500Z
DTEND:20180411T030500Z
UID:5sfOtSKDQzMz_6F0Fa6hcN9k@stanza.co
SUMMARY:RoughRiders vs. Cardinals
DESCRIPTION:RoughRiders vs. Cardinals\n\nFollow on MiLB First Pitch: https://stza.co/+wY83-1o\n\nShop: https://stza.co/+wY83-3I\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144527Z
LAST-MODIFIED:20180213T144527Z
TRANSP:OPAQUE
END:VEVENT
* RoughRiders @ Drillers
<2018-04-12 Thu 19:05-22:05>
:PROPERTIES:
:ID:       sFSb9AwLGr8_Nm1HXo8G_qWA@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

RoughRiders @ Drillers RoughRiders @ Drillers

Follow on MiLB First Pitch  https //stza.co/+w00m-1Q

Shop  https //stza.co/+w00m-1L

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:RoughRiders @ Drillers
END:VALARM
DTSTART:20180413T000500Z
DTEND:20180413T030500Z
UID:sFSb9AwLGr8_Nm1HXo8G_qWA@stanza.co
SUMMARY:RoughRiders @ Drillers
DESCRIPTION:RoughRiders @ Drillers\n\nFollow on MiLB First Pitch: https://stza.co/+w00m-1Q\n\nShop: https://stza.co/+w00m-1L\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144527Z
LAST-MODIFIED:20180213T144527Z
TRANSP:OPAQUE
END:VEVENT
* RoughRiders @ Drillers
<2018-04-13 Fri 19:05-22:05>
:PROPERTIES:
:ID:       UtxGSG0rT8UAc364Sc7Kxx3k@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

RoughRiders @ Drillers RoughRiders @ Drillers

Follow on MiLB First Pitch  https //stza.co/+w00n-u

Shop  https //stza.co/+w00n-17

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:RoughRiders @ Drillers
END:VALARM
DTSTART:20180414T000500Z
DTEND:20180414T030500Z
UID:UtxGSG0rT8UAc364Sc7Kxx3k@stanza.co
SUMMARY:RoughRiders @ Drillers
DESCRIPTION:RoughRiders @ Drillers\n\nFollow on MiLB First Pitch: https://stza.co/+w00n-u\n\nShop: https://stza.co/+w00n-17\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144527Z
LAST-MODIFIED:20180213T144527Z
TRANSP:OPAQUE
END:VEVENT
* RoughRiders @ Drillers
<2018-04-14 Sat 19:05-22:05>
:PROPERTIES:
:ID:       5eRxShGKXgvCXvaKiCg5fyCX@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

RoughRiders @ Drillers RoughRiders @ Drillers

Follow on MiLB First Pitch  https //stza.co/+w00o-2r

Shop  https //stza.co/+w00o-31

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:RoughRiders @ Drillers
END:VALARM
DTSTART:20180415T000500Z
DTEND:20180415T030500Z
UID:5eRxShGKXgvCXvaKiCg5fyCX@stanza.co
SUMMARY:RoughRiders @ Drillers
DESCRIPTION:RoughRiders @ Drillers\n\nFollow on MiLB First Pitch: https://stza.co/+w00o-2r\n\nShop: https://stza.co/+w00o-31\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144527Z
LAST-MODIFIED:20180213T144527Z
TRANSP:OPAQUE
END:VEVENT
* RoughRiders @ Cardinals
<2018-04-15 Sun 17:10-20:10>
:PROPERTIES:
:ID:       Ujzw4sOjuW7QlHra2EiDifDW@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

RoughRiders @ Cardinals RoughRiders @ Cardinals

Follow on MiLB First Pitch  https //stza.co/+wPMP-F

Shop  https //stza.co/+wPMP-e

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:RoughRiders @ Cardinals
END:VALARM
DTSTART:20180415T221000Z
DTEND:20180416T011000Z
UID:Ujzw4sOjuW7QlHra2EiDifDW@stanza.co
SUMMARY:RoughRiders @ Cardinals
DESCRIPTION:RoughRiders @ Cardinals\n\nFollow on MiLB First Pitch: https://stza.co/+wPMP-F\n\nShop: https://stza.co/+wPMP-e\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144527Z
LAST-MODIFIED:20180213T144527Z
TRANSP:OPAQUE
END:VEVENT
* RoughRiders @ Cardinals
<2018-04-16 Mon 11:10-14:10>
:PROPERTIES:
:ID:       8T_qFfLIf2voq7rbiG-pQ9Y0@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

RoughRiders @ Cardinals RoughRiders @ Cardinals

Follow on MiLB First Pitch  https //stza.co/+wPMQ-2

Shop  https //stza.co/+wPMQ-4

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:RoughRiders @ Cardinals
END:VALARM
DTSTART:20180416T161000Z
DTEND:20180416T191000Z
UID:8T_qFfLIf2voq7rbiG-pQ9Y0@stanza.co
SUMMARY:RoughRiders @ Cardinals
DESCRIPTION:RoughRiders @ Cardinals\n\nFollow on MiLB First Pitch: https://stza.co/+wPMQ-2\n\nShop: https://stza.co/+wPMQ-4\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144527Z
LAST-MODIFIED:20180213T144527Z
TRANSP:OPAQUE
END:VEVENT
* RoughRiders @ Cardinals
<2018-04-17 Tue 11:10-14:10>
:PROPERTIES:
:ID:       qb0j29UCkrhIEILWz5hDgqpx@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

RoughRiders @ Cardinals RoughRiders @ Cardinals

Follow on MiLB First Pitch  https //stza.co/+wPMR-1h

Shop  https //stza.co/+wPMR-1l

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:RoughRiders @ Cardinals
END:VALARM
DTSTART:20180417T161000Z
DTEND:20180417T191000Z
UID:qb0j29UCkrhIEILWz5hDgqpx@stanza.co
SUMMARY:RoughRiders @ Cardinals
DESCRIPTION:RoughRiders @ Cardinals\n\nFollow on MiLB First Pitch: https://stza.co/+wPMR-1h\n\nShop: https://stza.co/+wPMR-1l\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144527Z
LAST-MODIFIED:20180213T144527Z
TRANSP:OPAQUE
END:VEVENT
* RoughRiders vs. Hooks
<2018-04-19 Thu 19:05-22:05>
:PROPERTIES:
:ID:       Uh2vvQhf0LiyfF9KuBOxGckA@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

RoughRiders vs. Hooks RoughRiders vs. Hooks

Follow on MiLB First Pitch  https //stza.co/+wY85-2U

Shop  https //stza.co/+wY85-2N

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:RoughRiders vs. Hooks
END:VALARM
DTSTART:20180420T000500Z
DTEND:20180420T030500Z
UID:Uh2vvQhf0LiyfF9KuBOxGckA@stanza.co
SUMMARY:RoughRiders vs. Hooks
DESCRIPTION:RoughRiders vs. Hooks\n\nFollow on MiLB First Pitch: https://stza.co/+wY85-2U\n\nShop: https://stza.co/+wY85-2N\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144527Z
LAST-MODIFIED:20180213T144527Z
TRANSP:OPAQUE
END:VEVENT
* RoughRiders vs. Hooks
<2018-04-20 Fri 19:05-22:05>
:PROPERTIES:
:ID:       EObC6w-XdS5XX-jtzWcqrlyg@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

RoughRiders vs. Hooks RoughRiders vs. Hooks

Follow on MiLB First Pitch  https //stza.co/+wY88-3q

Shop  https //stza.co/+wY88-1Z

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:RoughRiders vs. Hooks
END:VALARM
DTSTART:20180421T000500Z
DTEND:20180421T030500Z
UID:EObC6w-XdS5XX-jtzWcqrlyg@stanza.co
SUMMARY:RoughRiders vs. Hooks
DESCRIPTION:RoughRiders vs. Hooks\n\nFollow on MiLB First Pitch: https://stza.co/+wY88-3q\n\nShop: https://stza.co/+wY88-1Z\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144527Z
LAST-MODIFIED:20180213T144527Z
TRANSP:OPAQUE
END:VEVENT
* RoughRiders vs. Hooks
<2018-04-21 Sat 19:05-22:05>
:PROPERTIES:
:ID:       yj7aO9-PbS1obt0Lg8MGlIpf@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

RoughRiders vs. Hooks RoughRiders vs. Hooks

Follow on MiLB First Pitch  https //stza.co/+wY8a-28

Shop  https //stza.co/+wY8a-2m

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:RoughRiders vs. Hooks
END:VALARM
DTSTART:20180422T000500Z
DTEND:20180422T030500Z
UID:yj7aO9-PbS1obt0Lg8MGlIpf@stanza.co
SUMMARY:RoughRiders vs. Hooks
DESCRIPTION:RoughRiders vs. Hooks\n\nFollow on MiLB First Pitch: https://stza.co/+wY8a-28\n\nShop: https://stza.co/+wY8a-2m\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144527Z
LAST-MODIFIED:20180213T144527Z
TRANSP:OPAQUE
END:VEVENT
* RoughRiders vs. Hooks
<2018-04-22 Sun 16:05-19:05>
:PROPERTIES:
:ID:       CaLT9ol6MJ4YzV4qqAwQHmVp@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

RoughRiders vs. Hooks RoughRiders vs. Hooks

Follow on MiLB First Pitch  https //stza.co/+wY8c-1h

Shop  https //stza.co/+wY8c-H

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:RoughRiders vs. Hooks
END:VALARM
DTSTART:20180422T210500Z
DTEND:20180423T000500Z
UID:CaLT9ol6MJ4YzV4qqAwQHmVp@stanza.co
SUMMARY:RoughRiders vs. Hooks
DESCRIPTION:RoughRiders vs. Hooks\n\nFollow on MiLB First Pitch: https://stza.co/+wY8c-1h\n\nShop: https://stza.co/+wY8c-H\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144527Z
LAST-MODIFIED:20180213T144527Z
TRANSP:OPAQUE
END:VEVENT
* RoughRiders @ Missions
<2018-04-23 Mon 19:05-22:05>
:PROPERTIES:
:ID:       9IG1c5GsnHYqc7MwjHav9-Zf@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

RoughRiders @ Missions RoughRiders @ Missions

Follow on MiLB First Pitch  https //stza.co/+wMu3-1h

Shop  https //stza.co/+wMu3-6

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:RoughRiders @ Missions
END:VALARM
DTSTART:20180424T000500Z
DTEND:20180424T030500Z
UID:9IG1c5GsnHYqc7MwjHav9-Zf@stanza.co
SUMMARY:RoughRiders @ Missions
DESCRIPTION:RoughRiders @ Missions\n\nFollow on MiLB First Pitch: https://stza.co/+wMu3-1h\n\nShop: https://stza.co/+wMu3-6\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144527Z
LAST-MODIFIED:20180213T144527Z
TRANSP:OPAQUE
END:VEVENT
* RoughRiders @ Missions
<2018-04-24 Tue 19:05-22:05>
:PROPERTIES:
:ID:       hXOfUELQe_Z1z9rl87QskcvQ@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

RoughRiders @ Missions RoughRiders @ Missions

Follow on MiLB First Pitch  https //stza.co/+wMu4-1i

Shop  https //stza.co/+wMu4-2b

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:RoughRiders @ Missions
END:VALARM
DTSTART:20180425T000500Z
DTEND:20180425T030500Z
UID:hXOfUELQe_Z1z9rl87QskcvQ@stanza.co
SUMMARY:RoughRiders @ Missions
DESCRIPTION:RoughRiders @ Missions\n\nFollow on MiLB First Pitch: https://stza.co/+wMu4-1i\n\nShop: https://stza.co/+wMu4-2b\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144527Z
LAST-MODIFIED:20180213T144527Z
TRANSP:OPAQUE
END:VEVENT
* RoughRiders @ Missions
<2018-04-25 Wed 19:05-22:05>
:PROPERTIES:
:ID:       Vvm3PGovOcmjKIAsAjfXLr3u@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

RoughRiders @ Missions RoughRiders @ Missions

Follow on MiLB First Pitch  https //stza.co/+wMu5-m

Shop  https //stza.co/+wMu5-a

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:RoughRiders @ Missions
END:VALARM
DTSTART:20180426T000500Z
DTEND:20180426T030500Z
UID:Vvm3PGovOcmjKIAsAjfXLr3u@stanza.co
SUMMARY:RoughRiders @ Missions
DESCRIPTION:RoughRiders @ Missions\n\nFollow on MiLB First Pitch: https://stza.co/+wMu5-m\n\nShop: https://stza.co/+wMu5-a\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144527Z
LAST-MODIFIED:20180213T144527Z
TRANSP:OPAQUE
END:VEVENT
* RoughRiders @ Missions
<2018-04-26 Thu 19:05-22:05>
:PROPERTIES:
:ID:       arrcbybgW0PgrIo6ZL7fwQHM@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

RoughRiders @ Missions RoughRiders @ Missions

Follow on MiLB First Pitch  https //stza.co/+wMu6-3q

Shop  https //stza.co/+wMu6-1N

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:RoughRiders @ Missions
END:VALARM
DTSTART:20180427T000500Z
DTEND:20180427T030500Z
UID:arrcbybgW0PgrIo6ZL7fwQHM@stanza.co
SUMMARY:RoughRiders @ Missions
DESCRIPTION:RoughRiders @ Missions\n\nFollow on MiLB First Pitch: https://stza.co/+wMu6-3q\n\nShop: https://stza.co/+wMu6-1N\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144527Z
LAST-MODIFIED:20180213T144527Z
TRANSP:OPAQUE
END:VEVENT
* RoughRiders @ Hooks
<2018-04-27 Fri 19:05-22:05>
:PROPERTIES:
:ID:       yUdnbRmzUU9oYELWNxaK5uZs@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

RoughRiders @ Hooks RoughRiders @ Hooks

Follow on MiLB First Pitch  https //stza.co/+xzHc-P

Shop  https //stza.co/+xzHc-2D

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:RoughRiders @ Hooks
END:VALARM
DTSTART:20180428T000500Z
DTEND:20180428T030500Z
UID:yUdnbRmzUU9oYELWNxaK5uZs@stanza.co
SUMMARY:RoughRiders @ Hooks
DESCRIPTION:RoughRiders @ Hooks\n\nFollow on MiLB First Pitch: https://stza.co/+xzHc-P\n\nShop: https://stza.co/+xzHc-2D\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144527Z
LAST-MODIFIED:20180213T144527Z
TRANSP:OPAQUE
END:VEVENT
* RoughRiders @ Hooks
<2018-04-28 Sat 19:05-22:05>
:PROPERTIES:
:ID:       BwpHfJKAu3bzAczoUz0fEj9a@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

RoughRiders @ Hooks RoughRiders @ Hooks

Follow on MiLB First Pitch  https //stza.co/+xzHd-1D

Shop  https //stza.co/+xzHd-2P

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:RoughRiders @ Hooks
END:VALARM
DTSTART:20180429T000500Z
DTEND:20180429T030500Z
UID:BwpHfJKAu3bzAczoUz0fEj9a@stanza.co
SUMMARY:RoughRiders @ Hooks
DESCRIPTION:RoughRiders @ Hooks\n\nFollow on MiLB First Pitch: https://stza.co/+xzHd-1D\n\nShop: https://stza.co/+xzHd-2P\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144527Z
LAST-MODIFIED:20180213T144527Z
TRANSP:OPAQUE
END:VEVENT
* RoughRiders @ Hooks
<2018-04-29 Sun 14:05-17:05>
:PROPERTIES:
:ID:       RLJGeLxbq7JYVJ5AaXX1wlwk@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

RoughRiders @ Hooks RoughRiders @ Hooks

Follow on MiLB First Pitch  https //stza.co/+xzHe-1o

Shop  https //stza.co/+xzHe-2k

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:RoughRiders @ Hooks
END:VALARM
DTSTART:20180429T190500Z
DTEND:20180429T220500Z
UID:RLJGeLxbq7JYVJ5AaXX1wlwk@stanza.co
SUMMARY:RoughRiders @ Hooks
DESCRIPTION:RoughRiders @ Hooks\n\nFollow on MiLB First Pitch: https://stza.co/+xzHe-1o\n\nShop: https://stza.co/+xzHe-2k\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144527Z
LAST-MODIFIED:20180213T144527Z
TRANSP:OPAQUE
END:VEVENT
* RoughRiders @ Hooks
<2018-04-30 Mon 19:05-22:05>
:PROPERTIES:
:ID:       d9PIayqJa_GHwFOh-H3_ZLPE@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

RoughRiders @ Hooks RoughRiders @ Hooks

Follow on MiLB First Pitch  https //stza.co/+xzHg-5

Shop  https //stza.co/+xzHg-28

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:RoughRiders @ Hooks
END:VALARM
DTSTART:20180501T000500Z
DTEND:20180501T030500Z
UID:d9PIayqJa_GHwFOh-H3_ZLPE@stanza.co
SUMMARY:RoughRiders @ Hooks
DESCRIPTION:RoughRiders @ Hooks\n\nFollow on MiLB First Pitch: https://stza.co/+xzHg-5\n\nShop: https://stza.co/+xzHg-28\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144527Z
LAST-MODIFIED:20180213T144527Z
TRANSP:OPAQUE
END:VEVENT
* RoughRiders vs. Missions
<2018-05-01 Tue 19:05-22:05>
:PROPERTIES:
:ID:       FZX_EMyj3Z1vR7MuWqUEQf0e@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

RoughRiders vs. Missions RoughRiders vs. Missions

Follow on MiLB First Pitch  https //stza.co/+wY8e-2$

Shop  https //stza.co/+wY8e-16

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:RoughRiders vs. Missions
END:VALARM
DTSTART:20180502T000500Z
DTEND:20180502T030500Z
UID:FZX_EMyj3Z1vR7MuWqUEQf0e@stanza.co
SUMMARY:RoughRiders vs. Missions
DESCRIPTION:RoughRiders vs. Missions\n\nFollow on MiLB First Pitch: https://stza.co/+wY8e-2$\n\nShop: https://stza.co/+wY8e-16\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144527Z
LAST-MODIFIED:20180213T144527Z
TRANSP:OPAQUE
END:VEVENT
* RoughRiders vs. Missions
<2018-05-02 Wed 11:05-14:05>
:PROPERTIES:
:ID:       -LRy7h2Z1-bslNuLPosQV3lL@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

RoughRiders vs. Missions RoughRiders vs. Missions

Follow on MiLB First Pitch  https //stza.co/+wY8f-3f

Shop  https //stza.co/+wY8f-1S

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:RoughRiders vs. Missions
END:VALARM
DTSTART:20180502T160500Z
DTEND:20180502T190500Z
UID:-LRy7h2Z1-bslNuLPosQV3lL@stanza.co
SUMMARY:RoughRiders vs. Missions
DESCRIPTION:RoughRiders vs. Missions\n\nFollow on MiLB First Pitch: https://stza.co/+wY8f-3f\n\nShop: https://stza.co/+wY8f-1S\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144527Z
LAST-MODIFIED:20180213T144527Z
TRANSP:OPAQUE
END:VEVENT
* RoughRiders vs. Missions
<2018-05-03 Thu 19:05-22:05>
:PROPERTIES:
:ID:       rnnqvlJgt8esRVorMqDFlYOr@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

RoughRiders vs. Missions RoughRiders vs. Missions

Follow on MiLB First Pitch  https //stza.co/+wY8h-21

Shop  https //stza.co/+wY8h-2$

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:RoughRiders vs. Missions
END:VALARM
DTSTART:20180504T000500Z
DTEND:20180504T030500Z
UID:rnnqvlJgt8esRVorMqDFlYOr@stanza.co
SUMMARY:RoughRiders vs. Missions
DESCRIPTION:RoughRiders vs. Missions\n\nFollow on MiLB First Pitch: https://stza.co/+wY8h-21\n\nShop: https://stza.co/+wY8h-2$\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144527Z
LAST-MODIFIED:20180213T144527Z
TRANSP:OPAQUE
END:VEVENT
* RoughRiders vs. Missions
<2018-05-04 Fri 19:05-22:05>
:PROPERTIES:
:ID:       xfxDRSm2Yz6_-IL3vMaVaVSo@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

RoughRiders vs. Missions RoughRiders vs. Missions

Follow on MiLB First Pitch  https //stza.co/+wY8j-h

Shop  https //stza.co/+wY8j-1

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:RoughRiders vs. Missions
END:VALARM
DTSTART:20180505T000500Z
DTEND:20180505T030500Z
UID:xfxDRSm2Yz6_-IL3vMaVaVSo@stanza.co
SUMMARY:RoughRiders vs. Missions
DESCRIPTION:RoughRiders vs. Missions\n\nFollow on MiLB First Pitch: https://stza.co/+wY8j-h\n\nShop: https://stza.co/+wY8j-1\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144527Z
LAST-MODIFIED:20180213T144527Z
TRANSP:OPAQUE
END:VEVENT
* RoughRiders vs. RockHounds
<2018-05-05 Sat 19:05-22:05>
:PROPERTIES:
:ID:       MWKhFPsOT7CNHqF9qAN_tt4C@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

RoughRiders vs. RockHounds RoughRiders vs. RockHounds

Follow on MiLB First Pitch  https //stza.co/+wY8m-3u

Shop  https //stza.co/+wY8m-A

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:RoughRiders vs. RockHounds
END:VALARM
DTSTART:20180506T000500Z
DTEND:20180506T030500Z
UID:MWKhFPsOT7CNHqF9qAN_tt4C@stanza.co
SUMMARY:RoughRiders vs. RockHounds
DESCRIPTION:RoughRiders vs. RockHounds\n\nFollow on MiLB First Pitch: https://stza.co/+wY8m-3u\n\nShop: https://stza.co/+wY8m-A\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144527Z
LAST-MODIFIED:20180213T144527Z
TRANSP:OPAQUE
END:VEVENT
* RoughRiders vs. RockHounds
<2018-05-06 Sun 16:05-19:05>
:PROPERTIES:
:ID:       TkRhJyP_iK-PRFu7c5KK9cj8@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

RoughRiders vs. RockHounds RoughRiders vs. RockHounds

Follow on MiLB First Pitch  https //stza.co/+wY8q-3Z

Shop  https //stza.co/+wY8q-33

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:RoughRiders vs. RockHounds
END:VALARM
DTSTART:20180506T210500Z
DTEND:20180507T000500Z
UID:TkRhJyP_iK-PRFu7c5KK9cj8@stanza.co
SUMMARY:RoughRiders vs. RockHounds
DESCRIPTION:RoughRiders vs. RockHounds\n\nFollow on MiLB First Pitch: https://stza.co/+wY8q-3Z\n\nShop: https://stza.co/+wY8q-33\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144527Z
LAST-MODIFIED:20180213T144527Z
TRANSP:OPAQUE
END:VEVENT
* RoughRiders vs. RockHounds
<2018-05-07 Mon 19:05-22:05>
:PROPERTIES:
:ID:       lbs5_Hwl08HlNh8yrbw3HBk4@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

RoughRiders vs. RockHounds RoughRiders vs. RockHounds

Follow on MiLB First Pitch  https //stza.co/+wY8s-2B

Shop  https //stza.co/+wY8s-27

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:RoughRiders vs. RockHounds
END:VALARM
DTSTART:20180508T000500Z
DTEND:20180508T030500Z
UID:lbs5_Hwl08HlNh8yrbw3HBk4@stanza.co
SUMMARY:RoughRiders vs. RockHounds
DESCRIPTION:RoughRiders vs. RockHounds\n\nFollow on MiLB First Pitch: https://stza.co/+wY8s-2B\n\nShop: https://stza.co/+wY8s-27\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144527Z
LAST-MODIFIED:20180213T144527Z
TRANSP:OPAQUE
END:VEVENT
* RoughRiders vs. RockHounds
<2018-05-08 Tue 11:05-14:05>
:PROPERTIES:
:ID:       GKpwiqBhqSFLvJU7iCRi_62W@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

RoughRiders vs. RockHounds RoughRiders vs. RockHounds

Follow on MiLB First Pitch  https //stza.co/+wY8t-u

Shop  https //stza.co/+wY8t-2I

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:RoughRiders vs. RockHounds
END:VALARM
DTSTART:20180508T160500Z
DTEND:20180508T190500Z
UID:GKpwiqBhqSFLvJU7iCRi_62W@stanza.co
SUMMARY:RoughRiders vs. RockHounds
DESCRIPTION:RoughRiders vs. RockHounds\n\nFollow on MiLB First Pitch: https://stza.co/+wY8t-u\n\nShop: https://stza.co/+wY8t-2I\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144527Z
LAST-MODIFIED:20180213T144527Z
TRANSP:OPAQUE
END:VEVENT
* RoughRiders @ Missions
<2018-05-10 Thu 19:05-22:05>
:PROPERTIES:
:ID:       K2C5i2ZI9gq0YgCOb4aVBLgF@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

RoughRiders @ Missions RoughRiders @ Missions

Follow on MiLB First Pitch  https //stza.co/+wMu7-1G

Shop  https //stza.co/+wMu7-3Z

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:RoughRiders @ Missions
END:VALARM
DTSTART:20180511T000500Z
DTEND:20180511T030500Z
UID:K2C5i2ZI9gq0YgCOb4aVBLgF@stanza.co
SUMMARY:RoughRiders @ Missions
DESCRIPTION:RoughRiders @ Missions\n\nFollow on MiLB First Pitch: https://stza.co/+wMu7-1G\n\nShop: https://stza.co/+wMu7-3Z\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144527Z
LAST-MODIFIED:20180213T144527Z
TRANSP:OPAQUE
END:VEVENT
* RoughRiders @ Missions
<2018-05-11 Fri 19:05-22:05>
:PROPERTIES:
:ID:       QjiEeitKO6s3U7tSqWK9q-tn@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

RoughRiders @ Missions RoughRiders @ Missions

Follow on MiLB First Pitch  https //stza.co/+wMu8-3a

Shop  https //stza.co/+wMu8-1x

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:RoughRiders @ Missions
END:VALARM
DTSTART:20180512T000500Z
DTEND:20180512T030500Z
UID:QjiEeitKO6s3U7tSqWK9q-tn@stanza.co
SUMMARY:RoughRiders @ Missions
DESCRIPTION:RoughRiders @ Missions\n\nFollow on MiLB First Pitch: https://stza.co/+wMu8-3a\n\nShop: https://stza.co/+wMu8-1x\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144527Z
LAST-MODIFIED:20180213T144527Z
TRANSP:OPAQUE
END:VEVENT
* RoughRiders @ Missions
<2018-05-12 Sat 19:05-22:05>
:PROPERTIES:
:ID:       UTN-3jZEuO_GBrFWbIyccw7O@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

RoughRiders @ Missions RoughRiders @ Missions

Follow on MiLB First Pitch  https //stza.co/+wMu9-35

Shop  https //stza.co/+wMu9-2c

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:RoughRiders @ Missions
END:VALARM
DTSTART:20180513T000500Z
DTEND:20180513T030500Z
UID:UTN-3jZEuO_GBrFWbIyccw7O@stanza.co
SUMMARY:RoughRiders @ Missions
DESCRIPTION:RoughRiders @ Missions\n\nFollow on MiLB First Pitch: https://stza.co/+wMu9-35\n\nShop: https://stza.co/+wMu9-2c\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144527Z
LAST-MODIFIED:20180213T144527Z
TRANSP:OPAQUE
END:VEVENT
* RoughRiders @ Missions
<2018-05-13 Sun 14:05-17:05>
:PROPERTIES:
:ID:       btJk2xfFgapkC35jgqk5CMkJ@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

RoughRiders @ Missions RoughRiders @ Missions

Follow on MiLB First Pitch  https //stza.co/+wMua-36

Shop  https //stza.co/+wMua-32

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:RoughRiders @ Missions
END:VALARM
DTSTART:20180513T190500Z
DTEND:20180513T220500Z
UID:btJk2xfFgapkC35jgqk5CMkJ@stanza.co
SUMMARY:RoughRiders @ Missions
DESCRIPTION:RoughRiders @ Missions\n\nFollow on MiLB First Pitch: https://stza.co/+wMua-36\n\nShop: https://stza.co/+wMua-32\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144527Z
LAST-MODIFIED:20180213T144527Z
TRANSP:OPAQUE
END:VEVENT
* RoughRiders @ RockHounds
<2018-05-14 Mon 18:30-21:30>
:PROPERTIES:
:ID:       W7ZOKgQPud_Zjwjs53WlofvN@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

RoughRiders @ RockHounds RoughRiders @ RockHounds

Follow on MiLB First Pitch  https //stza.co/+wX1C-3s

Shop  https //stza.co/+wX1C-36

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:RoughRiders @ RockHounds
END:VALARM
DTSTART:20180514T233000Z
DTEND:20180515T023000Z
UID:W7ZOKgQPud_Zjwjs53WlofvN@stanza.co
SUMMARY:RoughRiders @ RockHounds
DESCRIPTION:RoughRiders @ RockHounds\n\nFollow on MiLB First Pitch: https://stza.co/+wX1C-3s\n\nShop: https://stza.co/+wX1C-36\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144527Z
LAST-MODIFIED:20180213T144527Z
TRANSP:OPAQUE
END:VEVENT
* RoughRiders @ RockHounds
<2018-05-15 Tue 18:30-21:30>
:PROPERTIES:
:ID:       2sU3XMU0zDrxBl6jevBzlvVu@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

RoughRiders @ RockHounds RoughRiders @ RockHounds

Follow on MiLB First Pitch  https //stza.co/+wX1D-O

Shop  https //stza.co/+wX1D-11

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:RoughRiders @ RockHounds
END:VALARM
DTSTART:20180515T233000Z
DTEND:20180516T023000Z
UID:2sU3XMU0zDrxBl6jevBzlvVu@stanza.co
SUMMARY:RoughRiders @ RockHounds
DESCRIPTION:RoughRiders @ RockHounds\n\nFollow on MiLB First Pitch: https://stza.co/+wX1D-O\n\nShop: https://stza.co/+wX1D-11\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144527Z
LAST-MODIFIED:20180213T144527Z
TRANSP:OPAQUE
END:VEVENT
* RoughRiders @ RockHounds
<2018-05-16 Wed 18:30-21:30>
:PROPERTIES:
:ID:       8pYsUYQtL05ASZjSMQZ_joEq@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

RoughRiders @ RockHounds RoughRiders @ RockHounds

Follow on MiLB First Pitch  https //stza.co/+wX1E-F

Shop  https //stza.co/+wX1E-1A

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:RoughRiders @ RockHounds
END:VALARM
DTSTART:20180516T233000Z
DTEND:20180517T023000Z
UID:8pYsUYQtL05ASZjSMQZ_joEq@stanza.co
SUMMARY:RoughRiders @ RockHounds
DESCRIPTION:RoughRiders @ RockHounds\n\nFollow on MiLB First Pitch: https://stza.co/+wX1E-F\n\nShop: https://stza.co/+wX1E-1A\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144527Z
LAST-MODIFIED:20180213T144527Z
TRANSP:OPAQUE
END:VEVENT
* RoughRiders @ RockHounds
<2018-05-17 Thu 19:00-22:00>
:PROPERTIES:
:ID:       yy7tzj4EfA02uTPBrSnKWzlN@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

RoughRiders @ RockHounds RoughRiders @ RockHounds

Follow on MiLB First Pitch  https //stza.co/+wX1F-2Z

Shop  https //stza.co/+wX1F-2Q

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:RoughRiders @ RockHounds
END:VALARM
DTSTART:20180518T000000Z
DTEND:20180518T030000Z
UID:yy7tzj4EfA02uTPBrSnKWzlN@stanza.co
SUMMARY:RoughRiders @ RockHounds
DESCRIPTION:RoughRiders @ RockHounds\n\nFollow on MiLB First Pitch: https://stza.co/+wX1F-2Z\n\nShop: https://stza.co/+wX1F-2Q\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144527Z
LAST-MODIFIED:20180213T144527Z
TRANSP:OPAQUE
END:VEVENT
* RoughRiders vs. Hooks
<2018-05-18 Fri 19:05-22:05>
:PROPERTIES:
:ID:       MXoJ-eEfxHLJbcrRlyC7xwBb@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

RoughRiders vs. Hooks RoughRiders vs. Hooks

Follow on MiLB First Pitch  https //stza.co/+wY8v-2S

Shop  https //stza.co/+wY8v-2A

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:RoughRiders vs. Hooks
END:VALARM
DTSTART:20180519T000500Z
DTEND:20180519T030500Z
UID:MXoJ-eEfxHLJbcrRlyC7xwBb@stanza.co
SUMMARY:RoughRiders vs. Hooks
DESCRIPTION:RoughRiders vs. Hooks\n\nFollow on MiLB First Pitch: https://stza.co/+wY8v-2S\n\nShop: https://stza.co/+wY8v-2A\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144527Z
LAST-MODIFIED:20180213T144527Z
TRANSP:OPAQUE
END:VEVENT
* RoughRiders vs. Hooks
<2018-05-19 Sat 19:05-22:05>
:PROPERTIES:
:ID:       2SpV-EvYPslCIZneUAtcMt6e@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

RoughRiders vs. Hooks RoughRiders vs. Hooks

Follow on MiLB First Pitch  https //stza.co/+wY8z-2w

Shop  https //stza.co/+wY8z-3h

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:RoughRiders vs. Hooks
END:VALARM
DTSTART:20180520T000500Z
DTEND:20180520T030500Z
UID:2SpV-EvYPslCIZneUAtcMt6e@stanza.co
SUMMARY:RoughRiders vs. Hooks
DESCRIPTION:RoughRiders vs. Hooks\n\nFollow on MiLB First Pitch: https://stza.co/+wY8z-2w\n\nShop: https://stza.co/+wY8z-3h\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144527Z
LAST-MODIFIED:20180213T144527Z
TRANSP:OPAQUE
END:VEVENT
* RoughRiders vs. Hooks
<2018-05-20 Sun 16:05-19:05>
:PROPERTIES:
:ID:       Qh2sh10wVZej1kRscBqKXYx1@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

RoughRiders vs. Hooks RoughRiders vs. Hooks

Follow on MiLB First Pitch  https //stza.co/+wY8B-w

Shop  https //stza.co/+wY8B-Q

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:RoughRiders vs. Hooks
END:VALARM
DTSTART:20180520T210500Z
DTEND:20180521T000500Z
UID:Qh2sh10wVZej1kRscBqKXYx1@stanza.co
SUMMARY:RoughRiders vs. Hooks
DESCRIPTION:RoughRiders vs. Hooks\n\nFollow on MiLB First Pitch: https://stza.co/+wY8B-w\n\nShop: https://stza.co/+wY8B-Q\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144527Z
LAST-MODIFIED:20180213T144527Z
TRANSP:OPAQUE
END:VEVENT
* RoughRiders vs. Hooks
<2018-05-21 Mon 11:05-14:05>
:PROPERTIES:
:ID:       zMWnH3TUNDEqjc9GItR2PLYJ@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

RoughRiders vs. Hooks RoughRiders vs. Hooks

Follow on MiLB First Pitch  https //stza.co/+wY8C-2T

Shop  https //stza.co/+wY8C-1U

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:RoughRiders vs. Hooks
END:VALARM
DTSTART:20180521T160500Z
DTEND:20180521T190500Z
UID:zMWnH3TUNDEqjc9GItR2PLYJ@stanza.co
SUMMARY:RoughRiders vs. Hooks
DESCRIPTION:RoughRiders vs. Hooks\n\nFollow on MiLB First Pitch: https://stza.co/+wY8C-2T\n\nShop: https://stza.co/+wY8C-1U\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144527Z
LAST-MODIFIED:20180213T144527Z
TRANSP:OPAQUE
END:VEVENT
* RoughRiders @ Naturals
<2018-05-22 Tue 19:05-22:05>
:PROPERTIES:
:ID:       NKP-NZZD6_OC6QclwADVSeIR@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

RoughRiders @ Naturals RoughRiders @ Naturals

Follow on MiLB First Pitch  https //stza.co/+wi0g-3q

Shop  https //stza.co/+wi0g-1o

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:RoughRiders @ Naturals
END:VALARM
DTSTART:20180523T000500Z
DTEND:20180523T030500Z
UID:NKP-NZZD6_OC6QclwADVSeIR@stanza.co
SUMMARY:RoughRiders @ Naturals
DESCRIPTION:RoughRiders @ Naturals\n\nFollow on MiLB First Pitch: https://stza.co/+wi0g-3q\n\nShop: https://stza.co/+wi0g-1o\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144527Z
LAST-MODIFIED:20180213T144527Z
TRANSP:OPAQUE
END:VEVENT
* RoughRiders @ Naturals
<2018-05-23 Wed 19:05-22:05>
:PROPERTIES:
:ID:       I_9wma8Mv-Whro1IpeyCFXH2@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

RoughRiders @ Naturals RoughRiders @ Naturals

Follow on MiLB First Pitch  https //stza.co/+wi0h-J

Shop  https //stza.co/+wi0h-2K

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:RoughRiders @ Naturals
END:VALARM
DTSTART:20180524T000500Z
DTEND:20180524T030500Z
UID:I_9wma8Mv-Whro1IpeyCFXH2@stanza.co
SUMMARY:RoughRiders @ Naturals
DESCRIPTION:RoughRiders @ Naturals\n\nFollow on MiLB First Pitch: https://stza.co/+wi0h-J\n\nShop: https://stza.co/+wi0h-2K\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144527Z
LAST-MODIFIED:20180213T144527Z
TRANSP:OPAQUE
END:VEVENT
* RoughRiders @ Naturals
<2018-05-24 Thu 19:05-22:05>
:PROPERTIES:
:ID:       OD1Lb4FlhCB3RGHQgIydSMbe@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

RoughRiders @ Naturals RoughRiders @ Naturals

Follow on MiLB First Pitch  https //stza.co/+wi0i-30

Shop  https //stza.co/+wi0i-2X

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:RoughRiders @ Naturals
END:VALARM
DTSTART:20180525T000500Z
DTEND:20180525T030500Z
UID:OD1Lb4FlhCB3RGHQgIydSMbe@stanza.co
SUMMARY:RoughRiders @ Naturals
DESCRIPTION:RoughRiders @ Naturals\n\nFollow on MiLB First Pitch: https://stza.co/+wi0i-30\n\nShop: https://stza.co/+wi0i-2X\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144527Z
LAST-MODIFIED:20180213T144527Z
TRANSP:OPAQUE
END:VEVENT
* RoughRiders @ Travelers
<2018-05-25 Fri 19:10-22:10>
:PROPERTIES:
:ID:       Gt06IAjc85KZY7Yme2OJwAoY@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

RoughRiders @ Travelers RoughRiders @ Travelers

Follow on MiLB First Pitch  https //stza.co/+v$Za-3F

Shop  https //stza.co/+v$Za-19

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:RoughRiders @ Travelers
END:VALARM
DTSTART:20180526T001000Z
DTEND:20180526T031000Z
UID:Gt06IAjc85KZY7Yme2OJwAoY@stanza.co
SUMMARY:RoughRiders @ Travelers
DESCRIPTION:RoughRiders @ Travelers\n\nFollow on MiLB First Pitch: https://stza.co/+v$Za-3F\n\nShop: https://stza.co/+v$Za-19\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144527Z
LAST-MODIFIED:20180213T144527Z
TRANSP:OPAQUE
END:VEVENT
* RoughRiders @ Travelers
<2018-05-26 Sat 18:10-21:10>
:PROPERTIES:
:ID:       _zBvjry7G1YJgviqdLCLwvig@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

RoughRiders @ Travelers RoughRiders @ Travelers

Follow on MiLB First Pitch  https //stza.co/+v$Zb-1Q

Shop  https //stza.co/+v$Zb-3o

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:RoughRiders @ Travelers
END:VALARM
DTSTART:20180526T231000Z
DTEND:20180527T021000Z
UID:_zBvjry7G1YJgviqdLCLwvig@stanza.co
SUMMARY:RoughRiders @ Travelers
DESCRIPTION:RoughRiders @ Travelers\n\nFollow on MiLB First Pitch: https://stza.co/+v$Zb-1Q\n\nShop: https://stza.co/+v$Zb-3o\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144527Z
LAST-MODIFIED:20180213T144527Z
TRANSP:OPAQUE
END:VEVENT
* RoughRiders @ Travelers
<2018-05-27 Sun 14:10-17:10>
:PROPERTIES:
:ID:       CQFJn7XQGUIGsYzFKA4ZyWZ0@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

RoughRiders @ Travelers RoughRiders @ Travelers

Follow on MiLB First Pitch  https //stza.co/+v$Zc-x

Shop  https //stza.co/+v$Zc-1Q

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:RoughRiders @ Travelers
END:VALARM
DTSTART:20180527T191000Z
DTEND:20180527T221000Z
UID:CQFJn7XQGUIGsYzFKA4ZyWZ0@stanza.co
SUMMARY:RoughRiders @ Travelers
DESCRIPTION:RoughRiders @ Travelers\n\nFollow on MiLB First Pitch: https://stza.co/+v$Zc-x\n\nShop: https://stza.co/+v$Zc-1Q\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144527Z
LAST-MODIFIED:20180213T144527Z
TRANSP:OPAQUE
END:VEVENT
* RoughRiders vs. Naturals
<2018-05-29 Tue 19:05-22:05>
:PROPERTIES:
:ID:       rP3w0YQqr9Qt12YiuyqgA5iT@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

RoughRiders vs. Naturals RoughRiders vs. Naturals

Follow on MiLB First Pitch  https //stza.co/+wY8F-3y

Shop  https //stza.co/+wY8F-3M

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:RoughRiders vs. Naturals
END:VALARM
DTSTART:20180530T000500Z
DTEND:20180530T030500Z
UID:rP3w0YQqr9Qt12YiuyqgA5iT@stanza.co
SUMMARY:RoughRiders vs. Naturals
DESCRIPTION:RoughRiders vs. Naturals\n\nFollow on MiLB First Pitch: https://stza.co/+wY8F-3y\n\nShop: https://stza.co/+wY8F-3M\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144527Z
LAST-MODIFIED:20180213T144527Z
TRANSP:OPAQUE
END:VEVENT
* RoughRiders vs. Naturals
<2018-05-30 Wed 19:05-22:05>
:PROPERTIES:
:ID:       tWOC1JMuCIg5qzJ8_E9ufwFL@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

RoughRiders vs. Naturals RoughRiders vs. Naturals

Follow on MiLB First Pitch  https //stza.co/+wY8G-1e

Shop  https //stza.co/+wY8G-c

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:RoughRiders vs. Naturals
END:VALARM
DTSTART:20180531T000500Z
DTEND:20180531T030500Z
UID:tWOC1JMuCIg5qzJ8_E9ufwFL@stanza.co
SUMMARY:RoughRiders vs. Naturals
DESCRIPTION:RoughRiders vs. Naturals\n\nFollow on MiLB First Pitch: https://stza.co/+wY8G-1e\n\nShop: https://stza.co/+wY8G-c\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144527Z
LAST-MODIFIED:20180213T144527Z
TRANSP:OPAQUE
END:VEVENT
* RoughRiders vs. Naturals
<2018-05-31 Thu 19:05-22:05>
:PROPERTIES:
:ID:       P6AOHoJWjqZVLW43BIYdrwVB@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

RoughRiders vs. Naturals RoughRiders vs. Naturals

Follow on MiLB First Pitch  https //stza.co/+wY8I-2X

Shop  https //stza.co/+wY8I-2m

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:RoughRiders vs. Naturals
END:VALARM
DTSTART:20180601T000500Z
DTEND:20180601T030500Z
UID:P6AOHoJWjqZVLW43BIYdrwVB@stanza.co
SUMMARY:RoughRiders vs. Naturals
DESCRIPTION:RoughRiders vs. Naturals\n\nFollow on MiLB First Pitch: https://stza.co/+wY8I-2X\n\nShop: https://stza.co/+wY8I-2m\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144527Z
LAST-MODIFIED:20180213T144527Z
TRANSP:OPAQUE
END:VEVENT
* RoughRiders vs. Travelers
<2018-06-01 Fri 19:05-22:05>
:PROPERTIES:
:ID:       Xm8kta2xfqH-gk3AmQ1QxTzo@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

RoughRiders vs. Travelers RoughRiders vs. Travelers

Follow on MiLB First Pitch  https //stza.co/+wY8L-3M

Shop  https //stza.co/+wY8L-k

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:RoughRiders vs. Travelers
END:VALARM
DTSTART:20180602T000500Z
DTEND:20180602T030500Z
UID:Xm8kta2xfqH-gk3AmQ1QxTzo@stanza.co
SUMMARY:RoughRiders vs. Travelers
DESCRIPTION:RoughRiders vs. Travelers\n\nFollow on MiLB First Pitch: https://stza.co/+wY8L-3M\n\nShop: https://stza.co/+wY8L-k\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144527Z
LAST-MODIFIED:20180213T144527Z
TRANSP:OPAQUE
END:VEVENT
* RoughRiders vs. Travelers
<2018-06-02 Sat 19:05-22:05>
:PROPERTIES:
:ID:       iRG-_UI3fu2jdB9mJ3WLd00a@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

RoughRiders vs. Travelers RoughRiders vs. Travelers

Follow on MiLB First Pitch  https //stza.co/+wY8O-1p

Shop  https //stza.co/+wY8O-3M

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:RoughRiders vs. Travelers
END:VALARM
DTSTART:20180603T000500Z
DTEND:20180603T030500Z
UID:iRG-_UI3fu2jdB9mJ3WLd00a@stanza.co
SUMMARY:RoughRiders vs. Travelers
DESCRIPTION:RoughRiders vs. Travelers\n\nFollow on MiLB First Pitch: https://stza.co/+wY8O-1p\n\nShop: https://stza.co/+wY8O-3M\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144527Z
LAST-MODIFIED:20180213T144527Z
TRANSP:OPAQUE
END:VEVENT
* RoughRiders vs. Travelers
<2018-06-03 Sun 19:05-22:05>
:PROPERTIES:
:ID:       -uF_kfDSXrLt8vedNNGCX0u_@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

RoughRiders vs. Travelers RoughRiders vs. Travelers

Follow on MiLB First Pitch  https //stza.co/+wY8Q-3T

Shop  https //stza.co/+wY8Q-2T

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:RoughRiders vs. Travelers
END:VALARM
DTSTART:20180604T000500Z
DTEND:20180604T030500Z
UID:-uF_kfDSXrLt8vedNNGCX0u_@stanza.co
SUMMARY:RoughRiders vs. Travelers
DESCRIPTION:RoughRiders vs. Travelers\n\nFollow on MiLB First Pitch: https://stza.co/+wY8Q-3T\n\nShop: https://stza.co/+wY8Q-2T\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144527Z
LAST-MODIFIED:20180213T144527Z
TRANSP:OPAQUE
END:VEVENT
* RoughRiders @ Hooks
<2018-06-05 Tue 19:05-22:05>
:PROPERTIES:
:ID:       NOD0lk5mGYEYRAkpGIb_ygvJ@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

RoughRiders @ Hooks RoughRiders @ Hooks

Follow on MiLB First Pitch  https //stza.co/+xzHh-1Y

Shop  https //stza.co/+xzHh-3j

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:RoughRiders @ Hooks
END:VALARM
DTSTART:20180606T000500Z
DTEND:20180606T030500Z
UID:NOD0lk5mGYEYRAkpGIb_ygvJ@stanza.co
SUMMARY:RoughRiders @ Hooks
DESCRIPTION:RoughRiders @ Hooks\n\nFollow on MiLB First Pitch: https://stza.co/+xzHh-1Y\n\nShop: https://stza.co/+xzHh-3j\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144527Z
LAST-MODIFIED:20180213T144527Z
TRANSP:OPAQUE
END:VEVENT
* RoughRiders @ Hooks
<2018-06-06 Wed 19:05-22:05>
:PROPERTIES:
:ID:       Z6ZiZAdGkCKyygxR9nuncIyg@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

RoughRiders @ Hooks RoughRiders @ Hooks

Follow on MiLB First Pitch  https //stza.co/+xzHj-1I

Shop  https //stza.co/+xzHj-$

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:RoughRiders @ Hooks
END:VALARM
DTSTART:20180607T000500Z
DTEND:20180607T030500Z
UID:Z6ZiZAdGkCKyygxR9nuncIyg@stanza.co
SUMMARY:RoughRiders @ Hooks
DESCRIPTION:RoughRiders @ Hooks\n\nFollow on MiLB First Pitch: https://stza.co/+xzHj-1I\n\nShop: https://stza.co/+xzHj-$\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144527Z
LAST-MODIFIED:20180213T144527Z
TRANSP:OPAQUE
END:VEVENT
* RoughRiders @ Hooks
<2018-06-07 Thu 19:05-22:05>
:PROPERTIES:
:ID:       vy1HihTHkwjzPASj46h3ZHb6@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

RoughRiders @ Hooks RoughRiders @ Hooks

Follow on MiLB First Pitch  https //stza.co/+xzHk-3k

Shop  https //stza.co/+xzHk-1t

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:RoughRiders @ Hooks
END:VALARM
DTSTART:20180608T000500Z
DTEND:20180608T030500Z
UID:vy1HihTHkwjzPASj46h3ZHb6@stanza.co
SUMMARY:RoughRiders @ Hooks
DESCRIPTION:RoughRiders @ Hooks\n\nFollow on MiLB First Pitch: https://stza.co/+xzHk-3k\n\nShop: https://stza.co/+xzHk-1t\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144527Z
LAST-MODIFIED:20180213T144527Z
TRANSP:OPAQUE
END:VEVENT
* RoughRiders @ Hooks
<2018-06-08 Fri 19:05-22:05>
:PROPERTIES:
:ID:       4oLYF967ofHOlJc5BXpiyQXy@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

RoughRiders @ Hooks RoughRiders @ Hooks

Follow on MiLB First Pitch  https //stza.co/+xzHl-3R

Shop  https //stza.co/+xzHl-z

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:RoughRiders @ Hooks
END:VALARM
DTSTART:20180609T000500Z
DTEND:20180609T030500Z
UID:4oLYF967ofHOlJc5BXpiyQXy@stanza.co
SUMMARY:RoughRiders @ Hooks
DESCRIPTION:RoughRiders @ Hooks\n\nFollow on MiLB First Pitch: https://stza.co/+xzHl-3R\n\nShop: https://stza.co/+xzHl-z\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144527Z
LAST-MODIFIED:20180213T144527Z
TRANSP:OPAQUE
END:VEVENT
* RoughRiders vs. RockHounds
<2018-06-09 Sat 19:05-22:05>
:PROPERTIES:
:ID:       5JVUvk2TiPXCvtfIjdcDnT13@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

RoughRiders vs. RockHounds RoughRiders vs. RockHounds

Follow on MiLB First Pitch  https //stza.co/+wY8R-3V

Shop  https //stza.co/+wY8R-1H

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:RoughRiders vs. RockHounds
END:VALARM
DTSTART:20180610T000500Z
DTEND:20180610T030500Z
UID:5JVUvk2TiPXCvtfIjdcDnT13@stanza.co
SUMMARY:RoughRiders vs. RockHounds
DESCRIPTION:RoughRiders vs. RockHounds\n\nFollow on MiLB First Pitch: https://stza.co/+wY8R-3V\n\nShop: https://stza.co/+wY8R-1H\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144527Z
LAST-MODIFIED:20180213T144527Z
TRANSP:OPAQUE
END:VEVENT
* RoughRiders vs. RockHounds
<2018-06-10 Sun 19:05-22:05>
:PROPERTIES:
:ID:       RaZbmieCRKdyjyOuOx5vIs5Q@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

RoughRiders vs. RockHounds RoughRiders vs. RockHounds

Follow on MiLB First Pitch  https //stza.co/+wY8U-1L

Shop  https //stza.co/+wY8U-1T

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:RoughRiders vs. RockHounds
END:VALARM
DTSTART:20180611T000500Z
DTEND:20180611T030500Z
UID:RaZbmieCRKdyjyOuOx5vIs5Q@stanza.co
SUMMARY:RoughRiders vs. RockHounds
DESCRIPTION:RoughRiders vs. RockHounds\n\nFollow on MiLB First Pitch: https://stza.co/+wY8U-1L\n\nShop: https://stza.co/+wY8U-1T\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144527Z
LAST-MODIFIED:20180213T144527Z
TRANSP:OPAQUE
END:VEVENT
* RoughRiders vs. RockHounds
<2018-06-11 Mon 19:05-22:05>
:PROPERTIES:
:ID:       J23HFGVrmY1czLwp_eZr1Rta@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

RoughRiders vs. RockHounds RoughRiders vs. RockHounds

Follow on MiLB First Pitch  https //stza.co/+wY8W-1F

Shop  https //stza.co/+wY8W-H

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:RoughRiders vs. RockHounds
END:VALARM
DTSTART:20180612T000500Z
DTEND:20180612T030500Z
UID:J23HFGVrmY1czLwp_eZr1Rta@stanza.co
SUMMARY:RoughRiders vs. RockHounds
DESCRIPTION:RoughRiders vs. RockHounds\n\nFollow on MiLB First Pitch: https://stza.co/+wY8W-1F\n\nShop: https://stza.co/+wY8W-H\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144527Z
LAST-MODIFIED:20180213T144527Z
TRANSP:OPAQUE
END:VEVENT
* RoughRiders vs. RockHounds
<2018-06-12 Tue 11:05-14:05>
:PROPERTIES:
:ID:       e4GArwaj2-kjH0O8sEK7VaX5@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

RoughRiders vs. RockHounds RoughRiders vs. RockHounds

Follow on MiLB First Pitch  https //stza.co/+wY8Y-2j

Shop  https //stza.co/+wY8Y-t

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:RoughRiders vs. RockHounds
END:VALARM
DTSTART:20180612T160500Z
DTEND:20180612T190500Z
UID:e4GArwaj2-kjH0O8sEK7VaX5@stanza.co
SUMMARY:RoughRiders vs. RockHounds
DESCRIPTION:RoughRiders vs. RockHounds\n\nFollow on MiLB First Pitch: https://stza.co/+wY8Y-2j\n\nShop: https://stza.co/+wY8Y-t\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144527Z
LAST-MODIFIED:20180213T144527Z
TRANSP:OPAQUE
END:VEVENT
* RoughRiders vs. Missions
<2018-06-13 Wed 19:05-22:05>
:PROPERTIES:
:ID:       5uMjUmRe2xOwo0QfbYKr__0_@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

RoughRiders vs. Missions RoughRiders vs. Missions

Follow on MiLB First Pitch  https //stza.co/+wY8Z-2o

Shop  https //stza.co/+wY8Z-2v

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:RoughRiders vs. Missions
END:VALARM
DTSTART:20180614T000500Z
DTEND:20180614T030500Z
UID:5uMjUmRe2xOwo0QfbYKr__0_@stanza.co
SUMMARY:RoughRiders vs. Missions
DESCRIPTION:RoughRiders vs. Missions\n\nFollow on MiLB First Pitch: https://stza.co/+wY8Z-2o\n\nShop: https://stza.co/+wY8Z-2v\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144527Z
LAST-MODIFIED:20180213T144527Z
TRANSP:OPAQUE
END:VEVENT
* RoughRiders vs. Missions
<2018-06-14 Thu 19:05-22:05>
:PROPERTIES:
:ID:       GsdsqihS53B-KKnTk5L0q9Se@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

RoughRiders vs. Missions RoughRiders vs. Missions

Follow on MiLB First Pitch  https //stza.co/+wY90-3u

Shop  https //stza.co/+wY90-3x

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:RoughRiders vs. Missions
END:VALARM
DTSTART:20180615T000500Z
DTEND:20180615T030500Z
UID:GsdsqihS53B-KKnTk5L0q9Se@stanza.co
SUMMARY:RoughRiders vs. Missions
DESCRIPTION:RoughRiders vs. Missions\n\nFollow on MiLB First Pitch: https://stza.co/+wY90-3u\n\nShop: https://stza.co/+wY90-3x\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144527Z
LAST-MODIFIED:20180213T144527Z
TRANSP:OPAQUE
END:VEVENT
* RoughRiders vs. Missions
<2018-06-15 Fri 19:05-22:05>
:PROPERTIES:
:ID:       rboJa-lxNXCKaCGO6Un-NXcs@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

RoughRiders vs. Missions RoughRiders vs. Missions

Follow on MiLB First Pitch  https //stza.co/+wY92-1Q

Shop  https //stza.co/+wY92-3N

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:RoughRiders vs. Missions
END:VALARM
DTSTART:20180616T000500Z
DTEND:20180616T030500Z
UID:rboJa-lxNXCKaCGO6Un-NXcs@stanza.co
SUMMARY:RoughRiders vs. Missions
DESCRIPTION:RoughRiders vs. Missions\n\nFollow on MiLB First Pitch: https://stza.co/+wY92-1Q\n\nShop: https://stza.co/+wY92-3N\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144527Z
LAST-MODIFIED:20180213T144527Z
TRANSP:OPAQUE
END:VEVENT
* RoughRiders vs. Missions
<2018-06-16 Sat 19:05-22:05>
:PROPERTIES:
:ID:       aW8ZGfEoCYNHUYAr5l41ZLTB@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

RoughRiders vs. Missions RoughRiders vs. Missions

Follow on MiLB First Pitch  https //stza.co/+wY94-2M

Shop  https //stza.co/+wY94-2a

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:RoughRiders vs. Missions
END:VALARM
DTSTART:20180617T000500Z
DTEND:20180617T030500Z
UID:aW8ZGfEoCYNHUYAr5l41ZLTB@stanza.co
SUMMARY:RoughRiders vs. Missions
DESCRIPTION:RoughRiders vs. Missions\n\nFollow on MiLB First Pitch: https://stza.co/+wY94-2M\n\nShop: https://stza.co/+wY94-2a\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144527Z
LAST-MODIFIED:20180213T144527Z
TRANSP:OPAQUE
END:VEVENT
* RoughRiders @ RockHounds
<2018-06-17 Sun 16:00-19:00>
:PROPERTIES:
:ID:       _ZkVkivkeA_3mPmJ3yrVKjfY@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

RoughRiders @ RockHounds RoughRiders @ RockHounds

Follow on MiLB First Pitch  https //stza.co/+wX1G-1s

Shop  https //stza.co/+wX1G-f

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:RoughRiders @ RockHounds
END:VALARM
DTSTART:20180617T210000Z
DTEND:20180618T000000Z
UID:_ZkVkivkeA_3mPmJ3yrVKjfY@stanza.co
SUMMARY:RoughRiders @ RockHounds
DESCRIPTION:RoughRiders @ RockHounds\n\nFollow on MiLB First Pitch: https://stza.co/+wX1G-1s\n\nShop: https://stza.co/+wX1G-f\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144527Z
LAST-MODIFIED:20180213T144527Z
TRANSP:OPAQUE
END:VEVENT
* RoughRiders @ RockHounds
<2018-06-18 Mon 18:30-21:30>
:PROPERTIES:
:ID:       ft_xYl-FCNoqXiYeRusNEq4N@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

RoughRiders @ RockHounds RoughRiders @ RockHounds

Follow on MiLB First Pitch  https //stza.co/+wX1H-1y

Shop  https //stza.co/+wX1H-35

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:RoughRiders @ RockHounds
END:VALARM
DTSTART:20180618T233000Z
DTEND:20180619T023000Z
UID:ft_xYl-FCNoqXiYeRusNEq4N@stanza.co
SUMMARY:RoughRiders @ RockHounds
DESCRIPTION:RoughRiders @ RockHounds\n\nFollow on MiLB First Pitch: https://stza.co/+wX1H-1y\n\nShop: https://stza.co/+wX1H-35\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144527Z
LAST-MODIFIED:20180213T144527Z
TRANSP:OPAQUE
END:VEVENT
* RoughRiders @ RockHounds
<2018-06-19 Tue 18:30-21:30>
:PROPERTIES:
:ID:       sKW4VePLGBxvmoWxYZKMiN7G@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

RoughRiders @ RockHounds RoughRiders @ RockHounds

Follow on MiLB First Pitch  https //stza.co/+wX1I-2b

Shop  https //stza.co/+wX1I-7

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:RoughRiders @ RockHounds
END:VALARM
DTSTART:20180619T233000Z
DTEND:20180620T023000Z
UID:sKW4VePLGBxvmoWxYZKMiN7G@stanza.co
SUMMARY:RoughRiders @ RockHounds
DESCRIPTION:RoughRiders @ RockHounds\n\nFollow on MiLB First Pitch: https://stza.co/+wX1I-2b\n\nShop: https://stza.co/+wX1I-7\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144527Z
LAST-MODIFIED:20180213T144527Z
TRANSP:OPAQUE
END:VEVENT
* RoughRiders @ RockHounds
<2018-06-20 Wed 18:30-21:30>
:PROPERTIES:
:ID:       DE-qa62_M0t_wp9tdPYkgj_n@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

RoughRiders @ RockHounds RoughRiders @ RockHounds

Follow on MiLB First Pitch  https //stza.co/+wX1J-1h

Shop  https //stza.co/+wX1J-Z

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:RoughRiders @ RockHounds
END:VALARM
DTSTART:20180620T233000Z
DTEND:20180621T023000Z
UID:DE-qa62_M0t_wp9tdPYkgj_n@stanza.co
SUMMARY:RoughRiders @ RockHounds
DESCRIPTION:RoughRiders @ RockHounds\n\nFollow on MiLB First Pitch: https://stza.co/+wX1J-1h\n\nShop: https://stza.co/+wX1J-Z\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144527Z
LAST-MODIFIED:20180213T144527Z
TRANSP:OPAQUE
END:VEVENT
* RoughRiders @ Hooks
<2018-06-21 Thu 19:05-22:05>
:PROPERTIES:
:ID:       RlFPYSWLVJv3xmgR2iydZspA@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

RoughRiders @ Hooks RoughRiders @ Hooks

Follow on MiLB First Pitch  https //stza.co/+xzHm-1V

Shop  https //stza.co/+xzHm-f

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:RoughRiders @ Hooks
END:VALARM
DTSTART:20180622T000500Z
DTEND:20180622T030500Z
UID:RlFPYSWLVJv3xmgR2iydZspA@stanza.co
SUMMARY:RoughRiders @ Hooks
DESCRIPTION:RoughRiders @ Hooks\n\nFollow on MiLB First Pitch: https://stza.co/+xzHm-1V\n\nShop: https://stza.co/+xzHm-f\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144527Z
LAST-MODIFIED:20180213T144527Z
TRANSP:OPAQUE
END:VEVENT
* RoughRiders @ Hooks
<2018-06-22 Fri 19:05-22:05>
:PROPERTIES:
:ID:       TX_hpxrNsVpNHLGrAS0DAdim@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

RoughRiders @ Hooks RoughRiders @ Hooks

Follow on MiLB First Pitch  https //stza.co/+xzHn-2k

Shop  https //stza.co/+xzHn-3s

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:RoughRiders @ Hooks
END:VALARM
DTSTART:20180623T000500Z
DTEND:20180623T030500Z
UID:TX_hpxrNsVpNHLGrAS0DAdim@stanza.co
SUMMARY:RoughRiders @ Hooks
DESCRIPTION:RoughRiders @ Hooks\n\nFollow on MiLB First Pitch: https://stza.co/+xzHn-2k\n\nShop: https://stza.co/+xzHn-3s\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144527Z
LAST-MODIFIED:20180213T144527Z
TRANSP:OPAQUE
END:VEVENT
* RoughRiders @ Hooks
<2018-06-23 Sat 19:05-22:05>
:PROPERTIES:
:ID:       qWIYbfsKB2r24cdWIztYtxx6@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

RoughRiders @ Hooks RoughRiders @ Hooks

Follow on MiLB First Pitch  https //stza.co/+xzHo-3M

Shop  https //stza.co/+xzHo-30

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:RoughRiders @ Hooks
END:VALARM
DTSTART:20180624T000500Z
DTEND:20180624T030500Z
UID:qWIYbfsKB2r24cdWIztYtxx6@stanza.co
SUMMARY:RoughRiders @ Hooks
DESCRIPTION:RoughRiders @ Hooks\n\nFollow on MiLB First Pitch: https://stza.co/+xzHo-3M\n\nShop: https://stza.co/+xzHo-30\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144527Z
LAST-MODIFIED:20180213T144527Z
TRANSP:OPAQUE
END:VEVENT
* RoughRiders @ Hooks
<2018-06-24 Sun 18:05-21:05>
:PROPERTIES:
:ID:       8C9MG_dCAICpupqjXYYfcQrs@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

RoughRiders @ Hooks RoughRiders @ Hooks

Follow on MiLB First Pitch  https //stza.co/+xzHp-6

Shop  https //stza.co/+xzHp-2C

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:RoughRiders @ Hooks
END:VALARM
DTSTART:20180624T230500Z
DTEND:20180625T020500Z
UID:8C9MG_dCAICpupqjXYYfcQrs@stanza.co
SUMMARY:RoughRiders @ Hooks
DESCRIPTION:RoughRiders @ Hooks\n\nFollow on MiLB First Pitch: https://stza.co/+xzHp-6\n\nShop: https://stza.co/+xzHp-2C\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144527Z
LAST-MODIFIED:20180213T144527Z
TRANSP:OPAQUE
END:VEVENT
* RoughRiders vs. Cardinals
<2018-06-28 Thu 19:05-22:05>
:PROPERTIES:
:ID:       TlpGen3nVKNzm25EBHmPzAo9@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

RoughRiders vs. Cardinals RoughRiders vs. Cardinals

Follow on MiLB First Pitch  https //stza.co/+wY97-G

Shop  https //stza.co/+wY97-36

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:RoughRiders vs. Cardinals
END:VALARM
DTSTART:20180629T000500Z
DTEND:20180629T030500Z
UID:TlpGen3nVKNzm25EBHmPzAo9@stanza.co
SUMMARY:RoughRiders vs. Cardinals
DESCRIPTION:RoughRiders vs. Cardinals\n\nFollow on MiLB First Pitch: https://stza.co/+wY97-G\n\nShop: https://stza.co/+wY97-36\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144527Z
LAST-MODIFIED:20180213T144527Z
TRANSP:OPAQUE
END:VEVENT
* RoughRiders vs. Cardinals
<2018-06-29 Fri 19:05-22:05>
:PROPERTIES:
:ID:       yhR9CVrcXWQWnQ9gEpmVrCYZ@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

RoughRiders vs. Cardinals RoughRiders vs. Cardinals

Follow on MiLB First Pitch  https //stza.co/+wY98-I

Shop  https //stza.co/+wY98-3W

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:RoughRiders vs. Cardinals
END:VALARM
DTSTART:20180630T000500Z
DTEND:20180630T030500Z
UID:yhR9CVrcXWQWnQ9gEpmVrCYZ@stanza.co
SUMMARY:RoughRiders vs. Cardinals
DESCRIPTION:RoughRiders vs. Cardinals\n\nFollow on MiLB First Pitch: https://stza.co/+wY98-I\n\nShop: https://stza.co/+wY98-3W\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144527Z
LAST-MODIFIED:20180213T144527Z
TRANSP:OPAQUE
END:VEVENT
* RoughRiders vs. Cardinals
<2018-06-30 Sat 19:05-22:05>
:PROPERTIES:
:ID:       zuE0Ely-ED5GaJdy47S02uHg@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

RoughRiders vs. Cardinals RoughRiders vs. Cardinals

Follow on MiLB First Pitch  https //stza.co/+wY9c-2D

Shop  https //stza.co/+wY9c-3K

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:RoughRiders vs. Cardinals
END:VALARM
DTSTART:20180701T000500Z
DTEND:20180701T030500Z
UID:zuE0Ely-ED5GaJdy47S02uHg@stanza.co
SUMMARY:RoughRiders vs. Cardinals
DESCRIPTION:RoughRiders vs. Cardinals\n\nFollow on MiLB First Pitch: https://stza.co/+wY9c-2D\n\nShop: https://stza.co/+wY9c-3K\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144527Z
LAST-MODIFIED:20180213T144527Z
TRANSP:OPAQUE
END:VEVENT
* RoughRiders vs. Drillers
<2018-07-01 Sun 19:05-22:05>
:PROPERTIES:
:ID:       SM8xDJhy4Xa0ZQhy5dTugZpi@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

RoughRiders vs. Drillers RoughRiders vs. Drillers

Follow on MiLB First Pitch  https //stza.co/+wY9e-Q

Shop  https //stza.co/+wY9e-1o

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:RoughRiders vs. Drillers
END:VALARM
DTSTART:20180702T000500Z
DTEND:20180702T030500Z
UID:SM8xDJhy4Xa0ZQhy5dTugZpi@stanza.co
SUMMARY:RoughRiders vs. Drillers
DESCRIPTION:RoughRiders vs. Drillers\n\nFollow on MiLB First Pitch: https://stza.co/+wY9e-Q\n\nShop: https://stza.co/+wY9e-1o\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144527Z
LAST-MODIFIED:20180213T144527Z
TRANSP:OPAQUE
END:VEVENT
* RoughRiders vs. Drillers
<2018-07-02 Mon 19:05-22:05>
:PROPERTIES:
:ID:       jEbHRKdTh3RWjKQJKgrdjyv8@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

RoughRiders vs. Drillers RoughRiders vs. Drillers

Follow on MiLB First Pitch  https //stza.co/+wY9g-38

Shop  https //stza.co/+wY9g-1Q

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:RoughRiders vs. Drillers
END:VALARM
DTSTART:20180703T000500Z
DTEND:20180703T030500Z
UID:jEbHRKdTh3RWjKQJKgrdjyv8@stanza.co
SUMMARY:RoughRiders vs. Drillers
DESCRIPTION:RoughRiders vs. Drillers\n\nFollow on MiLB First Pitch: https://stza.co/+wY9g-38\n\nShop: https://stza.co/+wY9g-1Q\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144527Z
LAST-MODIFIED:20180213T144527Z
TRANSP:OPAQUE
END:VEVENT
* RoughRiders vs. Drillers
<2018-07-03 Tue 19:05-22:05>
:PROPERTIES:
:ID:       1PjJeKGbM13lhDi3Q71bflWl@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

RoughRiders vs. Drillers RoughRiders vs. Drillers

Follow on MiLB First Pitch  https //stza.co/+wY9i-8

Shop  https //stza.co/+wY9i-1o

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:RoughRiders vs. Drillers
END:VALARM
DTSTART:20180704T000500Z
DTEND:20180704T030500Z
UID:1PjJeKGbM13lhDi3Q71bflWl@stanza.co
SUMMARY:RoughRiders vs. Drillers
DESCRIPTION:RoughRiders vs. Drillers\n\nFollow on MiLB First Pitch: https://stza.co/+wY9i-8\n\nShop: https://stza.co/+wY9i-1o\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144527Z
LAST-MODIFIED:20180213T144527Z
TRANSP:OPAQUE
END:VEVENT
* RoughRiders @ Cardinals
<2018-07-04 Wed 18:30-21:30>
:PROPERTIES:
:ID:       VtJcLbJoMPTiv1oDhyHzsUlX@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

RoughRiders @ Cardinals RoughRiders @ Cardinals

Follow on MiLB First Pitch  https //stza.co/+wPMS-l

Shop  https //stza.co/+wPMS-t

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:RoughRiders @ Cardinals
END:VALARM
DTSTART:20180704T233000Z
DTEND:20180705T023000Z
UID:VtJcLbJoMPTiv1oDhyHzsUlX@stanza.co
SUMMARY:RoughRiders @ Cardinals
DESCRIPTION:RoughRiders @ Cardinals\n\nFollow on MiLB First Pitch: https://stza.co/+wPMS-l\n\nShop: https://stza.co/+wPMS-t\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144527Z
LAST-MODIFIED:20180213T144527Z
TRANSP:OPAQUE
END:VEVENT
* RoughRiders @ Cardinals
<2018-07-05 Thu 19:10-22:10>
:PROPERTIES:
:ID:       GgAN-Tsk5ZYuu8EZQwkW1aNN@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

RoughRiders @ Cardinals RoughRiders @ Cardinals

Follow on MiLB First Pitch  https //stza.co/+wPMT-_

Shop  https //stza.co/+wPMT-3n

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:RoughRiders @ Cardinals
END:VALARM
DTSTART:20180706T001000Z
DTEND:20180706T031000Z
UID:GgAN-Tsk5ZYuu8EZQwkW1aNN@stanza.co
SUMMARY:RoughRiders @ Cardinals
DESCRIPTION:RoughRiders @ Cardinals\n\nFollow on MiLB First Pitch: https://stza.co/+wPMT-_\n\nShop: https://stza.co/+wPMT-3n\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144527Z
LAST-MODIFIED:20180213T144527Z
TRANSP:OPAQUE
END:VEVENT
* RoughRiders @ Cardinals
<2018-07-06 Fri 19:10-22:10>
:PROPERTIES:
:ID:       OyUk4vBRuTHXBmb3Tp9JaBq8@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

RoughRiders @ Cardinals RoughRiders @ Cardinals

Follow on MiLB First Pitch  https //stza.co/+wPMU-3y

Shop  https //stza.co/+wPMU-2c

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:RoughRiders @ Cardinals
END:VALARM
DTSTART:20180707T001000Z
DTEND:20180707T031000Z
UID:OyUk4vBRuTHXBmb3Tp9JaBq8@stanza.co
SUMMARY:RoughRiders @ Cardinals
DESCRIPTION:RoughRiders @ Cardinals\n\nFollow on MiLB First Pitch: https://stza.co/+wPMU-3y\n\nShop: https://stza.co/+wPMU-2c\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144527Z
LAST-MODIFIED:20180213T144527Z
TRANSP:OPAQUE
END:VEVENT
* RoughRiders @ Drillers
<2018-07-07 Sat 19:05-22:05>
:PROPERTIES:
:ID:       q8WtOo35wBk2mM_nUqOj80sO@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

RoughRiders @ Drillers RoughRiders @ Drillers

Follow on MiLB First Pitch  https //stza.co/+w00p-$

Shop  https //stza.co/+w00p-1Y

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:RoughRiders @ Drillers
END:VALARM
DTSTART:20180708T000500Z
DTEND:20180708T030500Z
UID:q8WtOo35wBk2mM_nUqOj80sO@stanza.co
SUMMARY:RoughRiders @ Drillers
DESCRIPTION:RoughRiders @ Drillers\n\nFollow on MiLB First Pitch: https://stza.co/+w00p-$\n\nShop: https://stza.co/+w00p-1Y\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144527Z
LAST-MODIFIED:20180213T144527Z
TRANSP:OPAQUE
END:VEVENT
* RoughRiders @ Drillers
<2018-07-08 Sun 19:05-22:05>
:PROPERTIES:
:ID:       BvDDRvZrRl_SGumunG06E9em@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

RoughRiders @ Drillers RoughRiders @ Drillers

Follow on MiLB First Pitch  https //stza.co/+w00q-3W

Shop  https //stza.co/+w00q-2X

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:RoughRiders @ Drillers
END:VALARM
DTSTART:20180709T000500Z
DTEND:20180709T030500Z
UID:BvDDRvZrRl_SGumunG06E9em@stanza.co
SUMMARY:RoughRiders @ Drillers
DESCRIPTION:RoughRiders @ Drillers\n\nFollow on MiLB First Pitch: https://stza.co/+w00q-3W\n\nShop: https://stza.co/+w00q-2X\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144527Z
LAST-MODIFIED:20180213T144527Z
TRANSP:OPAQUE
END:VEVENT
* RoughRiders @ Drillers
<2018-07-09 Mon 19:05-22:05>
:PROPERTIES:
:ID:       NfgioUS7E_C9CSHtaiv33x2u@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

RoughRiders @ Drillers RoughRiders @ Drillers

Follow on MiLB First Pitch  https //stza.co/+w00r-1y

Shop  https //stza.co/+w00r-1d

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:RoughRiders @ Drillers
END:VALARM
DTSTART:20180710T000500Z
DTEND:20180710T030500Z
UID:NfgioUS7E_C9CSHtaiv33x2u@stanza.co
SUMMARY:RoughRiders @ Drillers
DESCRIPTION:RoughRiders @ Drillers\n\nFollow on MiLB First Pitch: https://stza.co/+w00r-1y\n\nShop: https://stza.co/+w00r-1d\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144527Z
LAST-MODIFIED:20180213T144527Z
TRANSP:OPAQUE
END:VEVENT
* RoughRiders vs. Missions
<2018-07-11 Wed 19:05-22:05>
:PROPERTIES:
:ID:       buT6RMuqDnlbBNsvy_omOy9p@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

RoughRiders vs. Missions RoughRiders vs. Missions

Follow on MiLB First Pitch  https //stza.co/+wY9l-r

Shop  https //stza.co/+wY9l-2K

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:RoughRiders vs. Missions
END:VALARM
DTSTART:20180712T000500Z
DTEND:20180712T030500Z
UID:buT6RMuqDnlbBNsvy_omOy9p@stanza.co
SUMMARY:RoughRiders vs. Missions
DESCRIPTION:RoughRiders vs. Missions\n\nFollow on MiLB First Pitch: https://stza.co/+wY9l-r\n\nShop: https://stza.co/+wY9l-2K\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144527Z
LAST-MODIFIED:20180213T144527Z
TRANSP:OPAQUE
END:VEVENT
* RoughRiders vs. Missions
<2018-07-12 Thu 19:05-22:05>
:PROPERTIES:
:ID:       e4Mu8uUToca8u9luDkfq1dpJ@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

RoughRiders vs. Missions RoughRiders vs. Missions

Follow on MiLB First Pitch  https //stza.co/+wY9n-Y

Shop  https //stza.co/+wY9n-2L

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:RoughRiders vs. Missions
END:VALARM
DTSTART:20180713T000500Z
DTEND:20180713T030500Z
UID:e4Mu8uUToca8u9luDkfq1dpJ@stanza.co
SUMMARY:RoughRiders vs. Missions
DESCRIPTION:RoughRiders vs. Missions\n\nFollow on MiLB First Pitch: https://stza.co/+wY9n-Y\n\nShop: https://stza.co/+wY9n-2L\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144527Z
LAST-MODIFIED:20180213T144527Z
TRANSP:OPAQUE
END:VEVENT
* RoughRiders vs. Missions
<2018-07-13 Fri 19:05-22:05>
:PROPERTIES:
:ID:       1MZpCxClZs4kNcDcslgJq70D@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

RoughRiders vs. Missions RoughRiders vs. Missions

Follow on MiLB First Pitch  https //stza.co/+wY9q-o

Shop  https //stza.co/+wY9q-2R

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:RoughRiders vs. Missions
END:VALARM
DTSTART:20180714T000500Z
DTEND:20180714T030500Z
UID:1MZpCxClZs4kNcDcslgJq70D@stanza.co
SUMMARY:RoughRiders vs. Missions
DESCRIPTION:RoughRiders vs. Missions\n\nFollow on MiLB First Pitch: https://stza.co/+wY9q-o\n\nShop: https://stza.co/+wY9q-2R\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144527Z
LAST-MODIFIED:20180213T144527Z
TRANSP:OPAQUE
END:VEVENT
* RoughRiders vs. Missions
<2018-07-14 Sat 19:05-22:05>
:PROPERTIES:
:ID:       mWwsVDEbHODMQIvUJwimSnNz@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

RoughRiders vs. Missions RoughRiders vs. Missions

Follow on MiLB First Pitch  https //stza.co/+wY9r-1t

Shop  https //stza.co/+wY9r-2A

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:RoughRiders vs. Missions
END:VALARM
DTSTART:20180715T000500Z
DTEND:20180715T030500Z
UID:mWwsVDEbHODMQIvUJwimSnNz@stanza.co
SUMMARY:RoughRiders vs. Missions
DESCRIPTION:RoughRiders vs. Missions\n\nFollow on MiLB First Pitch: https://stza.co/+wY9r-1t\n\nShop: https://stza.co/+wY9r-2A\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144527Z
LAST-MODIFIED:20180213T144527Z
TRANSP:OPAQUE
END:VEVENT
* RoughRiders @ Hooks
<2018-07-15 Sun 18:05-21:05>
:PROPERTIES:
:ID:       3QGvbhMWCys8P-1UmTqjC3vQ@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

RoughRiders @ Hooks RoughRiders @ Hooks

Follow on MiLB First Pitch  https //stza.co/+xzHq-1n

Shop  https //stza.co/+xzHq-3p

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:RoughRiders @ Hooks
END:VALARM
DTSTART:20180715T230500Z
DTEND:20180716T020500Z
UID:3QGvbhMWCys8P-1UmTqjC3vQ@stanza.co
SUMMARY:RoughRiders @ Hooks
DESCRIPTION:RoughRiders @ Hooks\n\nFollow on MiLB First Pitch: https://stza.co/+xzHq-1n\n\nShop: https://stza.co/+xzHq-3p\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144527Z
LAST-MODIFIED:20180213T144527Z
TRANSP:OPAQUE
END:VEVENT
* RoughRiders @ Hooks
<2018-07-16 Mon 19:05-22:05>
:PROPERTIES:
:ID:       Wj5e3ZcUZSqGuzOF0ZAlnQMn@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

RoughRiders @ Hooks RoughRiders @ Hooks

Follow on MiLB First Pitch  https //stza.co/+xzHr-3W

Shop  https //stza.co/+xzHr-2

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:RoughRiders @ Hooks
END:VALARM
DTSTART:20180717T000500Z
DTEND:20180717T030500Z
UID:Wj5e3ZcUZSqGuzOF0ZAlnQMn@stanza.co
SUMMARY:RoughRiders @ Hooks
DESCRIPTION:RoughRiders @ Hooks\n\nFollow on MiLB First Pitch: https://stza.co/+xzHr-3W\n\nShop: https://stza.co/+xzHr-2\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144527Z
LAST-MODIFIED:20180213T144527Z
TRANSP:OPAQUE
END:VEVENT
* RoughRiders @ Hooks
<2018-07-17 Tue 19:05-22:05>
:PROPERTIES:
:ID:       kFTE-1cYfWcOsstH486cd5Lu@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

RoughRiders @ Hooks RoughRiders @ Hooks

Follow on MiLB First Pitch  https //stza.co/+xzHs-2J

Shop  https //stza.co/+xzHs-1_

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:RoughRiders @ Hooks
END:VALARM
DTSTART:20180718T000500Z
DTEND:20180718T030500Z
UID:kFTE-1cYfWcOsstH486cd5Lu@stanza.co
SUMMARY:RoughRiders @ Hooks
DESCRIPTION:RoughRiders @ Hooks\n\nFollow on MiLB First Pitch: https://stza.co/+xzHs-2J\n\nShop: https://stza.co/+xzHs-1_\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144527Z
LAST-MODIFIED:20180213T144527Z
TRANSP:OPAQUE
END:VEVENT
* RoughRiders @ Hooks
<2018-07-18 Wed 19:05-22:05>
:PROPERTIES:
:ID:       r2HBB5s7ghO7Z3i5POVVhfgf@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

RoughRiders @ Hooks RoughRiders @ Hooks

Follow on MiLB First Pitch  https //stza.co/+xzHt-d

Shop  https //stza.co/+xzHt-2e

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:RoughRiders @ Hooks
END:VALARM
DTSTART:20180719T000500Z
DTEND:20180719T030500Z
UID:r2HBB5s7ghO7Z3i5POVVhfgf@stanza.co
SUMMARY:RoughRiders @ Hooks
DESCRIPTION:RoughRiders @ Hooks\n\nFollow on MiLB First Pitch: https://stza.co/+xzHt-d\n\nShop: https://stza.co/+xzHt-2e\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144527Z
LAST-MODIFIED:20180213T144527Z
TRANSP:OPAQUE
END:VEVENT
* RoughRiders vs. Missions
<2018-07-19 Thu 19:05-22:05>
:PROPERTIES:
:ID:       5MHnBtlEL7gqAcWCPKjICcpy@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

RoughRiders vs. Missions RoughRiders vs. Missions

Follow on MiLB First Pitch  https //stza.co/+wY9u-S

Shop  https //stza.co/+wY9u-2L

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:RoughRiders vs. Missions
END:VALARM
DTSTART:20180720T000500Z
DTEND:20180720T030500Z
UID:5MHnBtlEL7gqAcWCPKjICcpy@stanza.co
SUMMARY:RoughRiders vs. Missions
DESCRIPTION:RoughRiders vs. Missions\n\nFollow on MiLB First Pitch: https://stza.co/+wY9u-S\n\nShop: https://stza.co/+wY9u-2L\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144527Z
LAST-MODIFIED:20180213T144527Z
TRANSP:OPAQUE
END:VEVENT
* RoughRiders vs. Missions
<2018-07-20 Fri 19:05-22:05>
:PROPERTIES:
:ID:       6z11Nfe1jpYMcy1Q1IuL_MG7@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

RoughRiders vs. Missions RoughRiders vs. Missions

Follow on MiLB First Pitch  https //stza.co/+wY9w-L

Shop  https //stza.co/+wY9w-36

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:RoughRiders vs. Missions
END:VALARM
DTSTART:20180721T000500Z
DTEND:20180721T030500Z
UID:6z11Nfe1jpYMcy1Q1IuL_MG7@stanza.co
SUMMARY:RoughRiders vs. Missions
DESCRIPTION:RoughRiders vs. Missions\n\nFollow on MiLB First Pitch: https://stza.co/+wY9w-L\n\nShop: https://stza.co/+wY9w-36\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144527Z
LAST-MODIFIED:20180213T144527Z
TRANSP:OPAQUE
END:VEVENT
* RoughRiders vs. Missions
<2018-07-21 Sat 19:05-22:05>
:PROPERTIES:
:ID:       Bd0WK2_E4tumG7TBZMFOxx9_@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

RoughRiders vs. Missions RoughRiders vs. Missions

Follow on MiLB First Pitch  https //stza.co/+wY9y-3Z

Shop  https //stza.co/+wY9y-3g

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:RoughRiders vs. Missions
END:VALARM
DTSTART:20180722T000500Z
DTEND:20180722T030500Z
UID:Bd0WK2_E4tumG7TBZMFOxx9_@stanza.co
SUMMARY:RoughRiders vs. Missions
DESCRIPTION:RoughRiders vs. Missions\n\nFollow on MiLB First Pitch: https://stza.co/+wY9y-3Z\n\nShop: https://stza.co/+wY9y-3g\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144527Z
LAST-MODIFIED:20180213T144527Z
TRANSP:OPAQUE
END:VEVENT
* RoughRiders vs. Missions
<2018-07-22 Sun 19:05-22:05>
:PROPERTIES:
:ID:       yH_RrNg3WIi-Un0jBoST5Ksz@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

RoughRiders vs. Missions RoughRiders vs. Missions

Follow on MiLB First Pitch  https //stza.co/+wY9A-1v

Shop  https //stza.co/+wY9A-3A

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:RoughRiders vs. Missions
END:VALARM
DTSTART:20180723T000500Z
DTEND:20180723T030500Z
UID:yH_RrNg3WIi-Un0jBoST5Ksz@stanza.co
SUMMARY:RoughRiders vs. Missions
DESCRIPTION:RoughRiders vs. Missions\n\nFollow on MiLB First Pitch: https://stza.co/+wY9A-1v\n\nShop: https://stza.co/+wY9A-3A\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144527Z
LAST-MODIFIED:20180213T144527Z
TRANSP:OPAQUE
END:VEVENT
* RoughRiders vs. RockHounds
<2018-07-23 Mon 19:05-22:05>
:PROPERTIES:
:ID:       SQw8Q98qb-sjK6-ybw3MqWdj@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

RoughRiders vs. RockHounds RoughRiders vs. RockHounds

Follow on MiLB First Pitch  https //stza.co/+wY9C-3f

Shop  https //stza.co/+wY9C-1$

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:RoughRiders vs. RockHounds
END:VALARM
DTSTART:20180724T000500Z
DTEND:20180724T030500Z
UID:SQw8Q98qb-sjK6-ybw3MqWdj@stanza.co
SUMMARY:RoughRiders vs. RockHounds
DESCRIPTION:RoughRiders vs. RockHounds\n\nFollow on MiLB First Pitch: https://stza.co/+wY9C-3f\n\nShop: https://stza.co/+wY9C-1$\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144527Z
LAST-MODIFIED:20180213T144527Z
TRANSP:OPAQUE
END:VEVENT
* RoughRiders vs. RockHounds
<2018-07-24 Tue 19:05-22:05>
:PROPERTIES:
:ID:       3aai7BoVPOIunR67bSPv14x6@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

RoughRiders vs. RockHounds RoughRiders vs. RockHounds

Follow on MiLB First Pitch  https //stza.co/+wY9F-1Z

Shop  https //stza.co/+wY9F-26

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:RoughRiders vs. RockHounds
END:VALARM
DTSTART:20180725T000500Z
DTEND:20180725T030500Z
UID:3aai7BoVPOIunR67bSPv14x6@stanza.co
SUMMARY:RoughRiders vs. RockHounds
DESCRIPTION:RoughRiders vs. RockHounds\n\nFollow on MiLB First Pitch: https://stza.co/+wY9F-1Z\n\nShop: https://stza.co/+wY9F-26\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144527Z
LAST-MODIFIED:20180213T144527Z
TRANSP:OPAQUE
END:VEVENT
* RoughRiders vs. RockHounds
<2018-07-25 Wed 19:05-22:05>
:PROPERTIES:
:ID:       vQ-8-aSlu8bsuy1eT5gbfGZb@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

RoughRiders vs. RockHounds RoughRiders vs. RockHounds

Follow on MiLB First Pitch  https //stza.co/+wY9G-39

Shop  https //stza.co/+wY9G-2e

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:RoughRiders vs. RockHounds
END:VALARM
DTSTART:20180726T000500Z
DTEND:20180726T030500Z
UID:vQ-8-aSlu8bsuy1eT5gbfGZb@stanza.co
SUMMARY:RoughRiders vs. RockHounds
DESCRIPTION:RoughRiders vs. RockHounds\n\nFollow on MiLB First Pitch: https://stza.co/+wY9G-39\n\nShop: https://stza.co/+wY9G-2e\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144527Z
LAST-MODIFIED:20180213T144527Z
TRANSP:OPAQUE
END:VEVENT
* RoughRiders @ Missions
<2018-07-26 Thu 19:05-22:05>
:PROPERTIES:
:ID:       fJ6tOcdW6c14u3NMfrQ6RrG5@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

RoughRiders @ Missions RoughRiders @ Missions

Follow on MiLB First Pitch  https //stza.co/+wMub-3p

Shop  https //stza.co/+wMub-28

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:RoughRiders @ Missions
END:VALARM
DTSTART:20180727T000500Z
DTEND:20180727T030500Z
UID:fJ6tOcdW6c14u3NMfrQ6RrG5@stanza.co
SUMMARY:RoughRiders @ Missions
DESCRIPTION:RoughRiders @ Missions\n\nFollow on MiLB First Pitch: https://stza.co/+wMub-3p\n\nShop: https://stza.co/+wMub-28\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144527Z
LAST-MODIFIED:20180213T144527Z
TRANSP:OPAQUE
END:VEVENT
* RoughRiders @ Missions
<2018-07-27 Fri 19:05-22:05>
:PROPERTIES:
:ID:       fTx58EL1RtkdJNWU8-LpQ_ZW@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

RoughRiders @ Missions RoughRiders @ Missions

Follow on MiLB First Pitch  https //stza.co/+wMuc-2E

Shop  https //stza.co/+wMuc-3_

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:RoughRiders @ Missions
END:VALARM
DTSTART:20180728T000500Z
DTEND:20180728T030500Z
UID:fTx58EL1RtkdJNWU8-LpQ_ZW@stanza.co
SUMMARY:RoughRiders @ Missions
DESCRIPTION:RoughRiders @ Missions\n\nFollow on MiLB First Pitch: https://stza.co/+wMuc-2E\n\nShop: https://stza.co/+wMuc-3_\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144527Z
LAST-MODIFIED:20180213T144527Z
TRANSP:OPAQUE
END:VEVENT
* RoughRiders @ Missions
<2018-07-28 Sat 19:05-22:05>
:PROPERTIES:
:ID:       5bQV9MQ6niHTGZg4iCbUjCNp@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

RoughRiders @ Missions RoughRiders @ Missions

Follow on MiLB First Pitch  https //stza.co/+wMue-r

Shop  https //stza.co/+wMue-1M

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:RoughRiders @ Missions
END:VALARM
DTSTART:20180729T000500Z
DTEND:20180729T030500Z
UID:5bQV9MQ6niHTGZg4iCbUjCNp@stanza.co
SUMMARY:RoughRiders @ Missions
DESCRIPTION:RoughRiders @ Missions\n\nFollow on MiLB First Pitch: https://stza.co/+wMue-r\n\nShop: https://stza.co/+wMue-1M\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144527Z
LAST-MODIFIED:20180213T144527Z
TRANSP:OPAQUE
END:VEVENT
* RoughRiders @ Missions
<2018-07-29 Sun 18:05-21:05>
:PROPERTIES:
:ID:       DVjYPbn645SB-VjNRM2PV207@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

RoughRiders @ Missions RoughRiders @ Missions

Follow on MiLB First Pitch  https //stza.co/+wMuf-3C

Shop  https //stza.co/+wMuf-18

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:RoughRiders @ Missions
END:VALARM
DTSTART:20180729T230500Z
DTEND:20180730T020500Z
UID:DVjYPbn645SB-VjNRM2PV207@stanza.co
SUMMARY:RoughRiders @ Missions
DESCRIPTION:RoughRiders @ Missions\n\nFollow on MiLB First Pitch: https://stza.co/+wMuf-3C\n\nShop: https://stza.co/+wMuf-18\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144527Z
LAST-MODIFIED:20180213T144527Z
TRANSP:OPAQUE
END:VEVENT
* RoughRiders @ RockHounds
<2018-07-30 Mon 18:30-21:30>
:PROPERTIES:
:ID:       mkRKiwnvG_OBVT9V_9Gw05jR@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

RoughRiders @ RockHounds RoughRiders @ RockHounds

Follow on MiLB First Pitch  https //stza.co/+wX1K-2l

Shop  https //stza.co/+wX1K-3P

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:RoughRiders @ RockHounds
END:VALARM
DTSTART:20180730T233000Z
DTEND:20180731T023000Z
UID:mkRKiwnvG_OBVT9V_9Gw05jR@stanza.co
SUMMARY:RoughRiders @ RockHounds
DESCRIPTION:RoughRiders @ RockHounds\n\nFollow on MiLB First Pitch: https://stza.co/+wX1K-2l\n\nShop: https://stza.co/+wX1K-3P\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144527Z
LAST-MODIFIED:20180213T144527Z
TRANSP:OPAQUE
END:VEVENT
* RoughRiders @ RockHounds
<2018-07-31 Tue 18:30-21:30>
:PROPERTIES:
:ID:       uNRP559eblX7M5HyeNp7JgF_@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

RoughRiders @ RockHounds RoughRiders @ RockHounds

Follow on MiLB First Pitch  https //stza.co/+wX1M-3O

Shop  https //stza.co/+wX1M-3v

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:RoughRiders @ RockHounds
END:VALARM
DTSTART:20180731T233000Z
DTEND:20180801T023000Z
UID:uNRP559eblX7M5HyeNp7JgF_@stanza.co
SUMMARY:RoughRiders @ RockHounds
DESCRIPTION:RoughRiders @ RockHounds\n\nFollow on MiLB First Pitch: https://stza.co/+wX1M-3O\n\nShop: https://stza.co/+wX1M-3v\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144527Z
LAST-MODIFIED:20180213T144527Z
TRANSP:OPAQUE
END:VEVENT
* RoughRiders @ RockHounds
<2018-08-01 Wed 18:30-21:30>
:PROPERTIES:
:ID:       pHoMRpl8ajccka8_j2fou1m5@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

RoughRiders @ RockHounds RoughRiders @ RockHounds

Follow on MiLB First Pitch  https //stza.co/+wX1N-3h

Shop  https //stza.co/+wX1N-x

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:RoughRiders @ RockHounds
END:VALARM
DTSTART:20180801T233000Z
DTEND:20180802T023000Z
UID:pHoMRpl8ajccka8_j2fou1m5@stanza.co
SUMMARY:RoughRiders @ RockHounds
DESCRIPTION:RoughRiders @ RockHounds\n\nFollow on MiLB First Pitch: https://stza.co/+wX1N-3h\n\nShop: https://stza.co/+wX1N-x\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144527Z
LAST-MODIFIED:20180213T144527Z
TRANSP:OPAQUE
END:VEVENT
* RoughRiders vs. Hooks
<2018-08-02 Thu 19:05-22:05>
:PROPERTIES:
:ID:       oMt2vjtCpdLYQSgddzVceX7k@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

RoughRiders vs. Hooks RoughRiders vs. Hooks

Follow on MiLB First Pitch  https //stza.co/+wY9I-1w

Shop  https //stza.co/+wY9I-2B

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:RoughRiders vs. Hooks
END:VALARM
DTSTART:20180803T000500Z
DTEND:20180803T030500Z
UID:oMt2vjtCpdLYQSgddzVceX7k@stanza.co
SUMMARY:RoughRiders vs. Hooks
DESCRIPTION:RoughRiders vs. Hooks\n\nFollow on MiLB First Pitch: https://stza.co/+wY9I-1w\n\nShop: https://stza.co/+wY9I-2B\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144527Z
LAST-MODIFIED:20180213T144527Z
TRANSP:OPAQUE
END:VEVENT
* RoughRiders vs. Hooks
<2018-08-03 Fri 19:05-22:05>
:PROPERTIES:
:ID:       vigmNISncl6UvVZBWwNo5RoE@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

RoughRiders vs. Hooks RoughRiders vs. Hooks

Follow on MiLB First Pitch  https //stza.co/+wY9K-U

Shop  https //stza.co/+wY9K-1Z

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:RoughRiders vs. Hooks
END:VALARM
DTSTART:20180804T000500Z
DTEND:20180804T030500Z
UID:vigmNISncl6UvVZBWwNo5RoE@stanza.co
SUMMARY:RoughRiders vs. Hooks
DESCRIPTION:RoughRiders vs. Hooks\n\nFollow on MiLB First Pitch: https://stza.co/+wY9K-U\n\nShop: https://stza.co/+wY9K-1Z\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144527Z
LAST-MODIFIED:20180213T144527Z
TRANSP:OPAQUE
END:VEVENT
* RoughRiders vs. Hooks
<2018-08-04 Sat 19:05-22:05>
:PROPERTIES:
:ID:       p4r8WogYEJ13MYhtnfrbfPI5@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

RoughRiders vs. Hooks RoughRiders vs. Hooks

Follow on MiLB First Pitch  https //stza.co/+wY9N-1O

Shop  https //stza.co/+wY9N-1P

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:RoughRiders vs. Hooks
END:VALARM
DTSTART:20180805T000500Z
DTEND:20180805T030500Z
UID:p4r8WogYEJ13MYhtnfrbfPI5@stanza.co
SUMMARY:RoughRiders vs. Hooks
DESCRIPTION:RoughRiders vs. Hooks\n\nFollow on MiLB First Pitch: https://stza.co/+wY9N-1O\n\nShop: https://stza.co/+wY9N-1P\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144527Z
LAST-MODIFIED:20180213T144527Z
TRANSP:OPAQUE
END:VEVENT
* RoughRiders vs. Hooks
<2018-08-05 Sun 19:05-22:05>
:PROPERTIES:
:ID:       sH4tQIRsrp1Iciy43Jeatdls@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

RoughRiders vs. Hooks RoughRiders vs. Hooks

Follow on MiLB First Pitch  https //stza.co/+wY9P-18

Shop  https //stza.co/+wY9P-d

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:RoughRiders vs. Hooks
END:VALARM
DTSTART:20180806T000500Z
DTEND:20180806T030500Z
UID:sH4tQIRsrp1Iciy43Jeatdls@stanza.co
SUMMARY:RoughRiders vs. Hooks
DESCRIPTION:RoughRiders vs. Hooks\n\nFollow on MiLB First Pitch: https://stza.co/+wY9P-18\n\nShop: https://stza.co/+wY9P-d\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144527Z
LAST-MODIFIED:20180213T144527Z
TRANSP:OPAQUE
END:VEVENT
* RoughRiders @ Travelers
<2018-08-07 Tue 19:10-22:10>
:PROPERTIES:
:ID:       Qppv0gD75WYvDZK-zVJJEQPw@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

RoughRiders @ Travelers RoughRiders @ Travelers

Follow on MiLB First Pitch  https //stza.co/+v$Zd-2R

Shop  https //stza.co/+v$Zd-24

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:RoughRiders @ Travelers
END:VALARM
DTSTART:20180808T001000Z
DTEND:20180808T031000Z
UID:Qppv0gD75WYvDZK-zVJJEQPw@stanza.co
SUMMARY:RoughRiders @ Travelers
DESCRIPTION:RoughRiders @ Travelers\n\nFollow on MiLB First Pitch: https://stza.co/+v$Zd-2R\n\nShop: https://stza.co/+v$Zd-24\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144527Z
LAST-MODIFIED:20180213T144527Z
TRANSP:OPAQUE
END:VEVENT
* RoughRiders @ Travelers
<2018-08-08 Wed 19:10-22:10>
:PROPERTIES:
:ID:       AlqFTGP0J-lZzXD4pCLYduVm@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

RoughRiders @ Travelers RoughRiders @ Travelers

Follow on MiLB First Pitch  https //stza.co/+v$Ze-2b

Shop  https //stza.co/+v$Ze-f

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:RoughRiders @ Travelers
END:VALARM
DTSTART:20180809T001000Z
DTEND:20180809T031000Z
UID:AlqFTGP0J-lZzXD4pCLYduVm@stanza.co
SUMMARY:RoughRiders @ Travelers
DESCRIPTION:RoughRiders @ Travelers\n\nFollow on MiLB First Pitch: https://stza.co/+v$Ze-2b\n\nShop: https://stza.co/+v$Ze-f\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144527Z
LAST-MODIFIED:20180213T144527Z
TRANSP:OPAQUE
END:VEVENT
* RoughRiders @ Travelers
<2018-08-09 Thu 19:10-22:10>
:PROPERTIES:
:ID:       0fGpTC8sIeTRn2NKJIUKiPB_@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

RoughRiders @ Travelers RoughRiders @ Travelers

Follow on MiLB First Pitch  https //stza.co/+v$Zf-1W

Shop  https //stza.co/+v$Zf-2C

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:RoughRiders @ Travelers
END:VALARM
DTSTART:20180810T001000Z
DTEND:20180810T031000Z
UID:0fGpTC8sIeTRn2NKJIUKiPB_@stanza.co
SUMMARY:RoughRiders @ Travelers
DESCRIPTION:RoughRiders @ Travelers\n\nFollow on MiLB First Pitch: https://stza.co/+v$Zf-1W\n\nShop: https://stza.co/+v$Zf-2C\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144527Z
LAST-MODIFIED:20180213T144527Z
TRANSP:OPAQUE
END:VEVENT
* RoughRiders @ Naturals
<2018-08-10 Fri 19:15-22:15>
:PROPERTIES:
:ID:       SgtQPZxdaz9yiqLQ2HhTM4yD@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

RoughRiders @ Naturals RoughRiders @ Naturals

Follow on MiLB First Pitch  https //stza.co/+wi0j-2W

Shop  https //stza.co/+wi0j-1N

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:RoughRiders @ Naturals
END:VALARM
DTSTART:20180811T001500Z
DTEND:20180811T031500Z
UID:SgtQPZxdaz9yiqLQ2HhTM4yD@stanza.co
SUMMARY:RoughRiders @ Naturals
DESCRIPTION:RoughRiders @ Naturals\n\nFollow on MiLB First Pitch: https://stza.co/+wi0j-2W\n\nShop: https://stza.co/+wi0j-1N\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144527Z
LAST-MODIFIED:20180213T144527Z
TRANSP:OPAQUE
END:VEVENT
* RoughRiders @ Naturals
<2018-08-11 Sat 18:05-21:05>
:PROPERTIES:
:ID:       4Qjj-vpkr6y_V6Bl34g2wtT5@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

RoughRiders @ Naturals RoughRiders @ Naturals

Follow on MiLB First Pitch  https //stza.co/+wi0k-2q

Shop  https //stza.co/+wi0k-3i

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:RoughRiders @ Naturals
END:VALARM
DTSTART:20180811T230500Z
DTEND:20180812T020500Z
UID:4Qjj-vpkr6y_V6Bl34g2wtT5@stanza.co
SUMMARY:RoughRiders @ Naturals
DESCRIPTION:RoughRiders @ Naturals\n\nFollow on MiLB First Pitch: https://stza.co/+wi0k-2q\n\nShop: https://stza.co/+wi0k-3i\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144527Z
LAST-MODIFIED:20180213T144527Z
TRANSP:OPAQUE
END:VEVENT
* RoughRiders @ Naturals
<2018-08-12 Sun 14:05-17:05>
:PROPERTIES:
:ID:       K3YHRt8kEqMpcxxTh7ZDcCIC@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

RoughRiders @ Naturals RoughRiders @ Naturals

Follow on MiLB First Pitch  https //stza.co/+wi0l-2M

Shop  https //stza.co/+wi0l-K

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:RoughRiders @ Naturals
END:VALARM
DTSTART:20180812T190500Z
DTEND:20180812T220500Z
UID:K3YHRt8kEqMpcxxTh7ZDcCIC@stanza.co
SUMMARY:RoughRiders @ Naturals
DESCRIPTION:RoughRiders @ Naturals\n\nFollow on MiLB First Pitch: https://stza.co/+wi0l-2M\n\nShop: https://stza.co/+wi0l-K\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144527Z
LAST-MODIFIED:20180213T144527Z
TRANSP:OPAQUE
END:VEVENT
* RoughRiders vs. Travelers
<2018-08-14 Tue 19:05-22:05>
:PROPERTIES:
:ID:       M3G7TnPDuuy4eQwTh_IAQhiS@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

RoughRiders vs. Travelers RoughRiders vs. Travelers

Follow on MiLB First Pitch  https //stza.co/+wY9Q-l

Shop  https //stza.co/+wY9Q-d

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:RoughRiders vs. Travelers
END:VALARM
DTSTART:20180815T000500Z
DTEND:20180815T030500Z
UID:M3G7TnPDuuy4eQwTh_IAQhiS@stanza.co
SUMMARY:RoughRiders vs. Travelers
DESCRIPTION:RoughRiders vs. Travelers\n\nFollow on MiLB First Pitch: https://stza.co/+wY9Q-l\n\nShop: https://stza.co/+wY9Q-d\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144527Z
LAST-MODIFIED:20180213T144527Z
TRANSP:OPAQUE
END:VEVENT
* RoughRiders vs. Travelers
<2018-08-15 Wed 19:05-22:05>
:PROPERTIES:
:ID:       dOG3KNdePT5Qt9ldhe5aDV3E@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

RoughRiders vs. Travelers RoughRiders vs. Travelers

Follow on MiLB First Pitch  https //stza.co/+wY9U-2G

Shop  https //stza.co/+wY9U-21

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:RoughRiders vs. Travelers
END:VALARM
DTSTART:20180816T000500Z
DTEND:20180816T030500Z
UID:dOG3KNdePT5Qt9ldhe5aDV3E@stanza.co
SUMMARY:RoughRiders vs. Travelers
DESCRIPTION:RoughRiders vs. Travelers\n\nFollow on MiLB First Pitch: https://stza.co/+wY9U-2G\n\nShop: https://stza.co/+wY9U-21\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144527Z
LAST-MODIFIED:20180213T144527Z
TRANSP:OPAQUE
END:VEVENT
* RoughRiders vs. Travelers
<2018-08-16 Thu 19:05-22:05>
:PROPERTIES:
:ID:       u-HxUTkJOkCmz1NLiOx43SD1@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

RoughRiders vs. Travelers RoughRiders vs. Travelers

Follow on MiLB First Pitch  https //stza.co/+wY9W-2f

Shop  https //stza.co/+wY9W-2A

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:RoughRiders vs. Travelers
END:VALARM
DTSTART:20180817T000500Z
DTEND:20180817T030500Z
UID:u-HxUTkJOkCmz1NLiOx43SD1@stanza.co
SUMMARY:RoughRiders vs. Travelers
DESCRIPTION:RoughRiders vs. Travelers\n\nFollow on MiLB First Pitch: https://stza.co/+wY9W-2f\n\nShop: https://stza.co/+wY9W-2A\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144527Z
LAST-MODIFIED:20180213T144527Z
TRANSP:OPAQUE
END:VEVENT
* RoughRiders vs. Naturals
<2018-08-17 Fri 19:05-22:05>
:PROPERTIES:
:ID:       ZgpfPCIev5DQNb2HMHttYttk@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

RoughRiders vs. Naturals RoughRiders vs. Naturals

Follow on MiLB First Pitch  https //stza.co/+wY9Z-1u

Shop  https //stza.co/+wY9Z-3T

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:RoughRiders vs. Naturals
END:VALARM
DTSTART:20180818T000500Z
DTEND:20180818T030500Z
UID:ZgpfPCIev5DQNb2HMHttYttk@stanza.co
SUMMARY:RoughRiders vs. Naturals
DESCRIPTION:RoughRiders vs. Naturals\n\nFollow on MiLB First Pitch: https://stza.co/+wY9Z-1u\n\nShop: https://stza.co/+wY9Z-3T\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144527Z
LAST-MODIFIED:20180213T144527Z
TRANSP:OPAQUE
END:VEVENT
* RoughRiders vs. Naturals
<2018-08-18 Sat 19:05-22:05>
:PROPERTIES:
:ID:       P6FwUgAMkwI-Q_nVoq-qXbPg@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

RoughRiders vs. Naturals RoughRiders vs. Naturals

Follow on MiLB First Pitch  https //stza.co/+wY9$-2W

Shop  https //stza.co/+wY9$-3w

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:RoughRiders vs. Naturals
END:VALARM
DTSTART:20180819T000500Z
DTEND:20180819T030500Z
UID:P6FwUgAMkwI-Q_nVoq-qXbPg@stanza.co
SUMMARY:RoughRiders vs. Naturals
DESCRIPTION:RoughRiders vs. Naturals\n\nFollow on MiLB First Pitch: https://stza.co/+wY9$-2W\n\nShop: https://stza.co/+wY9$-3w\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144527Z
LAST-MODIFIED:20180213T144527Z
TRANSP:OPAQUE
END:VEVENT
* RoughRiders vs. Naturals
<2018-08-19 Sun 19:05-22:05>
:PROPERTIES:
:ID:       QO4b6NGoF0T9gHk2YQWO86Mb@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

RoughRiders vs. Naturals RoughRiders vs. Naturals

Follow on MiLB First Pitch  https //stza.co/+wYa1-28

Shop  https //stza.co/+wYa1-v

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:RoughRiders vs. Naturals
END:VALARM
DTSTART:20180820T000500Z
DTEND:20180820T030500Z
UID:QO4b6NGoF0T9gHk2YQWO86Mb@stanza.co
SUMMARY:RoughRiders vs. Naturals
DESCRIPTION:RoughRiders vs. Naturals\n\nFollow on MiLB First Pitch: https://stza.co/+wYa1-28\n\nShop: https://stza.co/+wYa1-v\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144527Z
LAST-MODIFIED:20180213T144527Z
TRANSP:OPAQUE
END:VEVENT
* RoughRiders @ Missions
<2018-08-21 Tue 19:05-22:05>
:PROPERTIES:
:ID:       -9u8I8U6FN9jrgekMaoRwHZQ@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

RoughRiders @ Missions RoughRiders @ Missions

Follow on MiLB First Pitch  https //stza.co/+wMug-3

Shop  https //stza.co/+wMug-1T

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:RoughRiders @ Missions
END:VALARM
DTSTART:20180822T000500Z
DTEND:20180822T030500Z
UID:-9u8I8U6FN9jrgekMaoRwHZQ@stanza.co
SUMMARY:RoughRiders @ Missions
DESCRIPTION:RoughRiders @ Missions\n\nFollow on MiLB First Pitch: https://stza.co/+wMug-3\n\nShop: https://stza.co/+wMug-1T\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144527Z
LAST-MODIFIED:20180213T144527Z
TRANSP:OPAQUE
END:VEVENT
* RoughRiders @ Missions
<2018-08-22 Wed 19:05-22:05>
:PROPERTIES:
:ID:       c4j63FnbavHmoyZQQyOmuFHl@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

RoughRiders @ Missions RoughRiders @ Missions

Follow on MiLB First Pitch  https //stza.co/+wMuh-y

Shop  https //stza.co/+wMuh-W

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:RoughRiders @ Missions
END:VALARM
DTSTART:20180823T000500Z
DTEND:20180823T030500Z
UID:c4j63FnbavHmoyZQQyOmuFHl@stanza.co
SUMMARY:RoughRiders @ Missions
DESCRIPTION:RoughRiders @ Missions\n\nFollow on MiLB First Pitch: https://stza.co/+wMuh-y\n\nShop: https://stza.co/+wMuh-W\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144527Z
LAST-MODIFIED:20180213T144527Z
TRANSP:OPAQUE
END:VEVENT
* RoughRiders @ Missions
<2018-08-23 Thu 19:05-22:05>
:PROPERTIES:
:ID:       nwrOeJPUxk81U2nZ579Oi39F@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

RoughRiders @ Missions RoughRiders @ Missions

Follow on MiLB First Pitch  https //stza.co/+wMui-3G

Shop  https //stza.co/+wMui-2y

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:RoughRiders @ Missions
END:VALARM
DTSTART:20180824T000500Z
DTEND:20180824T030500Z
UID:nwrOeJPUxk81U2nZ579Oi39F@stanza.co
SUMMARY:RoughRiders @ Missions
DESCRIPTION:RoughRiders @ Missions\n\nFollow on MiLB First Pitch: https://stza.co/+wMui-3G\n\nShop: https://stza.co/+wMui-2y\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144527Z
LAST-MODIFIED:20180213T144527Z
TRANSP:OPAQUE
END:VEVENT
* RoughRiders @ Missions
<2018-08-24 Fri 19:05-22:05>
:PROPERTIES:
:ID:       SvOkvoNa_W3mI-tBF2f7Q9nd@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

RoughRiders @ Missions RoughRiders @ Missions

Follow on MiLB First Pitch  https //stza.co/+wMuj-3c

Shop  https //stza.co/+wMuj-v

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:RoughRiders @ Missions
END:VALARM
DTSTART:20180825T000500Z
DTEND:20180825T030500Z
UID:SvOkvoNa_W3mI-tBF2f7Q9nd@stanza.co
SUMMARY:RoughRiders @ Missions
DESCRIPTION:RoughRiders @ Missions\n\nFollow on MiLB First Pitch: https://stza.co/+wMuj-3c\n\nShop: https://stza.co/+wMuj-v\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144527Z
LAST-MODIFIED:20180213T144527Z
TRANSP:OPAQUE
END:VEVENT
* RoughRiders vs. RockHounds
<2018-08-25 Sat 19:05-22:05>
:PROPERTIES:
:ID:       mv1wYctOfj3CoS1-LXhWYD4c@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

RoughRiders vs. RockHounds RoughRiders vs. RockHounds

Follow on MiLB First Pitch  https //stza.co/+wYa3-3f

Shop  https //stza.co/+wYa3-2s

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:RoughRiders vs. RockHounds
END:VALARM
DTSTART:20180826T000500Z
DTEND:20180826T030500Z
UID:mv1wYctOfj3CoS1-LXhWYD4c@stanza.co
SUMMARY:RoughRiders vs. RockHounds
DESCRIPTION:RoughRiders vs. RockHounds\n\nFollow on MiLB First Pitch: https://stza.co/+wYa3-3f\n\nShop: https://stza.co/+wYa3-2s\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144527Z
LAST-MODIFIED:20180213T144527Z
TRANSP:OPAQUE
END:VEVENT
* RoughRiders vs. RockHounds
<2018-08-26 Sun 19:05-22:05>
:PROPERTIES:
:ID:       pNoiLXU594Q_E-C-cYdAFDe8@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

RoughRiders vs. RockHounds RoughRiders vs. RockHounds

Follow on MiLB First Pitch  https //stza.co/+wYa5-1i

Shop  https //stza.co/+wYa5-3k

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:RoughRiders vs. RockHounds
END:VALARM
DTSTART:20180827T000500Z
DTEND:20180827T030500Z
UID:pNoiLXU594Q_E-C-cYdAFDe8@stanza.co
SUMMARY:RoughRiders vs. RockHounds
DESCRIPTION:RoughRiders vs. RockHounds\n\nFollow on MiLB First Pitch: https://stza.co/+wYa5-1i\n\nShop: https://stza.co/+wYa5-3k\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144527Z
LAST-MODIFIED:20180213T144527Z
TRANSP:OPAQUE
END:VEVENT
* RoughRiders vs. RockHounds
<2018-08-27 Mon 19:05-22:05>
:PROPERTIES:
:ID:       mk6pD5bxPbxRJKmdxwh7hEA3@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

RoughRiders vs. RockHounds RoughRiders vs. RockHounds

Follow on MiLB First Pitch  https //stza.co/+wYa9-2Z

Shop  https //stza.co/+wYa9-L

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:RoughRiders vs. RockHounds
END:VALARM
DTSTART:20180828T000500Z
DTEND:20180828T030500Z
UID:mk6pD5bxPbxRJKmdxwh7hEA3@stanza.co
SUMMARY:RoughRiders vs. RockHounds
DESCRIPTION:RoughRiders vs. RockHounds\n\nFollow on MiLB First Pitch: https://stza.co/+wYa9-2Z\n\nShop: https://stza.co/+wYa9-L\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144527Z
LAST-MODIFIED:20180213T144527Z
TRANSP:OPAQUE
END:VEVENT
* RoughRiders vs. Hooks
<2018-08-28 Tue 19:05-22:05>
:PROPERTIES:
:ID:       vkQgG_QzNUfs2-EhMENIwv1N@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

RoughRiders vs. Hooks RoughRiders vs. Hooks

Follow on MiLB First Pitch  https //stza.co/+wYaa-z

Shop  https //stza.co/+wYaa-H

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:RoughRiders vs. Hooks
END:VALARM
DTSTART:20180829T000500Z
DTEND:20180829T030500Z
UID:vkQgG_QzNUfs2-EhMENIwv1N@stanza.co
SUMMARY:RoughRiders vs. Hooks
DESCRIPTION:RoughRiders vs. Hooks\n\nFollow on MiLB First Pitch: https://stza.co/+wYaa-z\n\nShop: https://stza.co/+wYaa-H\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144527Z
LAST-MODIFIED:20180213T144527Z
TRANSP:OPAQUE
END:VEVENT
* RoughRiders vs. Hooks
<2018-08-29 Wed 19:05-22:05>
:PROPERTIES:
:ID:       mJ-JIy-dbzVvgqt6pwNI90ZJ@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

RoughRiders vs. Hooks RoughRiders vs. Hooks

Follow on MiLB First Pitch  https //stza.co/+wYad-3r

Shop  https //stza.co/+wYad-3Z

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:RoughRiders vs. Hooks
END:VALARM
DTSTART:20180830T000500Z
DTEND:20180830T030500Z
UID:mJ-JIy-dbzVvgqt6pwNI90ZJ@stanza.co
SUMMARY:RoughRiders vs. Hooks
DESCRIPTION:RoughRiders vs. Hooks\n\nFollow on MiLB First Pitch: https://stza.co/+wYad-3r\n\nShop: https://stza.co/+wYad-3Z\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144527Z
LAST-MODIFIED:20180213T144527Z
TRANSP:OPAQUE
END:VEVENT
* RoughRiders vs. Hooks
<2018-08-30 Thu 19:05-22:05>
:PROPERTIES:
:ID:       s48fYyHaoX4G6wUOsDO67t-u@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

RoughRiders vs. Hooks RoughRiders vs. Hooks

Follow on MiLB First Pitch  https //stza.co/+wYaf-18

Shop  https //stza.co/+wYaf-M

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:RoughRiders vs. Hooks
END:VALARM
DTSTART:20180831T000500Z
DTEND:20180831T030500Z
UID:s48fYyHaoX4G6wUOsDO67t-u@stanza.co
SUMMARY:RoughRiders vs. Hooks
DESCRIPTION:RoughRiders vs. Hooks\n\nFollow on MiLB First Pitch: https://stza.co/+wYaf-18\n\nShop: https://stza.co/+wYaf-M\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144527Z
LAST-MODIFIED:20180213T144527Z
TRANSP:OPAQUE
END:VEVENT
* RoughRiders vs. Hooks
<2018-08-31 Fri 19:05-22:05>
:PROPERTIES:
:ID:       PLfg0Y1Ba_1tRMQypEhV4_j-@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

RoughRiders vs. Hooks RoughRiders vs. Hooks

Follow on MiLB First Pitch  https //stza.co/+wYag-3B

Shop  https //stza.co/+wYag-2y

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:RoughRiders vs. Hooks
END:VALARM
DTSTART:20180901T000500Z
DTEND:20180901T030500Z
UID:PLfg0Y1Ba_1tRMQypEhV4_j-@stanza.co
SUMMARY:RoughRiders vs. Hooks
DESCRIPTION:RoughRiders vs. Hooks\n\nFollow on MiLB First Pitch: https://stza.co/+wYag-3B\n\nShop: https://stza.co/+wYag-2y\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144527Z
LAST-MODIFIED:20180213T144527Z
TRANSP:OPAQUE
END:VEVENT
* RoughRiders @ RockHounds
<2018-09-01 Sat 19:00-22:00>
:PROPERTIES:
:ID:       r4b9edLsxWLroKR-NdkNS1RP@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

RoughRiders @ RockHounds RoughRiders @ RockHounds

Follow on MiLB First Pitch  https //stza.co/+wX1O-z

Shop  https //stza.co/+wX1O-3P

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:RoughRiders @ RockHounds
END:VALARM
DTSTART:20180902T000000Z
DTEND:20180902T030000Z
UID:r4b9edLsxWLroKR-NdkNS1RP@stanza.co
SUMMARY:RoughRiders @ RockHounds
DESCRIPTION:RoughRiders @ RockHounds\n\nFollow on MiLB First Pitch: https://stza.co/+wX1O-z\n\nShop: https://stza.co/+wX1O-3P\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144527Z
LAST-MODIFIED:20180213T144527Z
TRANSP:OPAQUE
END:VEVENT
* RoughRiders @ RockHounds
<2018-09-02 Sun 14:00-17:00>
:PROPERTIES:
:ID:       YxI5iZ6eKLydMHDHJLCChv2z@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

RoughRiders @ RockHounds RoughRiders @ RockHounds

Follow on MiLB First Pitch  https //stza.co/+wX1P-D

Shop  https //stza.co/+wX1P-V

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:RoughRiders @ RockHounds
END:VALARM
DTSTART:20180902T190000Z
DTEND:20180902T220000Z
UID:YxI5iZ6eKLydMHDHJLCChv2z@stanza.co
SUMMARY:RoughRiders @ RockHounds
DESCRIPTION:RoughRiders @ RockHounds\n\nFollow on MiLB First Pitch: https://stza.co/+wX1P-D\n\nShop: https://stza.co/+wX1P-V\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144527Z
LAST-MODIFIED:20180213T144527Z
TRANSP:OPAQUE
END:VEVENT
* RoughRiders @ RockHounds
<2018-09-03 Mon 14:00-17:00>
:PROPERTIES:
:ID:       DxJC6UTNMyUoLLisWGigLMwv@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

RoughRiders @ RockHounds RoughRiders @ RockHounds

Follow on MiLB First Pitch  https //stza.co/+wX1Q-1N

Shop  https //stza.co/+wX1Q-14

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:RoughRiders @ RockHounds
END:VALARM
DTSTART:20180903T190000Z
DTEND:20180903T220000Z
UID:DxJC6UTNMyUoLLisWGigLMwv@stanza.co
SUMMARY:RoughRiders @ RockHounds
DESCRIPTION:RoughRiders @ RockHounds\n\nFollow on MiLB First Pitch: https://stza.co/+wX1Q-1N\n\nShop: https://stza.co/+wX1Q-14\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144527Z
LAST-MODIFIED:20180213T144527Z
TRANSP:OPAQUE
END:VEVENT
