#+TITLE:       Main Google calendar entries
#+AUTHOR:      Eric S Fraga
#+EMAIL:       e.fraga@ucl.ac.uk
#+DESCRIPTION: converted using the ical2org awk script
#+CATEGORY:    google
#+STARTUP:     hidestars
#+STARTUP:     overview

* COMMENT original iCal preamble

* Pelicans vs. Keys
<2018-04-05 Thu>--<2018-04-04 Wed>
:PROPERTIES:
:ID:       2BoluGV97pRACrLX3YHrRX-a@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Pelicans vs. Keys Pelicans vs. Keys

Follow on MiLB First Pitch  https //stza.co/+w0y6-1N

Shop  https //stza.co/+w0y6-2i

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Pelicans vs. Keys
END:VALARM
DTSTART;VALUE=DATE:20180405
DTEND;VALUE=DATE:20180405
UID:2BoluGV97pRACrLX3YHrRX-a@stanza.co
SUMMARY:Pelicans vs. Keys
DESCRIPTION:Pelicans vs. Keys\n\nFollow on MiLB First Pitch: https://stza.co/+w0y6-1N\n\nShop: https://stza.co/+w0y6-2i\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Pelicans vs. Keys
<2018-04-06 Fri>--<2018-04-05 Thu>
:PROPERTIES:
:ID:       huRTmG-1vd-vJEv2W6mfH6qG@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Pelicans vs. Keys Pelicans vs. Keys

Follow on MiLB First Pitch  https //stza.co/+w0y9-2U

Shop  https //stza.co/+w0y9-m

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Pelicans vs. Keys
END:VALARM
DTSTART;VALUE=DATE:20180406
DTEND;VALUE=DATE:20180406
UID:huRTmG-1vd-vJEv2W6mfH6qG@stanza.co
SUMMARY:Pelicans vs. Keys
DESCRIPTION:Pelicans vs. Keys\n\nFollow on MiLB First Pitch: https://stza.co/+w0y9-2U\n\nShop: https://stza.co/+w0y9-m\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Pelicans vs. Keys
<2018-04-07 Sat>--<2018-04-06 Fri>
:PROPERTIES:
:ID:       top0VWKDObzqVf4qeRs7V6cF@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Pelicans vs. Keys Pelicans vs. Keys

Follow on MiLB First Pitch  https //stza.co/+w0ya-1Y

Shop  https //stza.co/+w0ya-1E

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Pelicans vs. Keys
END:VALARM
DTSTART;VALUE=DATE:20180407
DTEND;VALUE=DATE:20180407
UID:top0VWKDObzqVf4qeRs7V6cF@stanza.co
SUMMARY:Pelicans vs. Keys
DESCRIPTION:Pelicans vs. Keys\n\nFollow on MiLB First Pitch: https://stza.co/+w0ya-1Y\n\nShop: https://stza.co/+w0ya-1E\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Pelicans vs. Keys
<2018-04-08 Sun>--<2018-04-07 Sat>
:PROPERTIES:
:ID:       TE4Wvk5mccq1iGLBbcRXfpE5@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Pelicans vs. Keys Pelicans vs. Keys

Follow on MiLB First Pitch  https //stza.co/+w0yc-1y

Shop  https //stza.co/+w0yc-3N

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Pelicans vs. Keys
END:VALARM
DTSTART;VALUE=DATE:20180408
DTEND;VALUE=DATE:20180408
UID:TE4Wvk5mccq1iGLBbcRXfpE5@stanza.co
SUMMARY:Pelicans vs. Keys
DESCRIPTION:Pelicans vs. Keys\n\nFollow on MiLB First Pitch: https://stza.co/+w0yc-1y\n\nShop: https://stza.co/+w0yc-3N\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Pelicans vs. Dash
<2018-04-09 Mon>--<2018-04-08 Sun>
:PROPERTIES:
:ID:       EoRkbCDEgB9Fwp3pVi3M7jMs@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Pelicans vs. Dash Pelicans vs. Dash

Follow on MiLB First Pitch  https //stza.co/+w0yf-U

Shop  https //stza.co/+w0yf-2_

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Pelicans vs. Dash
END:VALARM
DTSTART;VALUE=DATE:20180409
DTEND;VALUE=DATE:20180409
UID:EoRkbCDEgB9Fwp3pVi3M7jMs@stanza.co
SUMMARY:Pelicans vs. Dash
DESCRIPTION:Pelicans vs. Dash\n\nFollow on MiLB First Pitch: https://stza.co/+w0yf-U\n\nShop: https://stza.co/+w0yf-2_\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Pelicans vs. Dash
<2018-04-10 Tue>--<2018-04-09 Mon>
:PROPERTIES:
:ID:       nOcqxQjQfeFbSXwexZGmMR-k@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Pelicans vs. Dash Pelicans vs. Dash

Follow on MiLB First Pitch  https //stza.co/+w0yg-1i

Shop  https //stza.co/+w0yg-h

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Pelicans vs. Dash
END:VALARM
DTSTART;VALUE=DATE:20180410
DTEND;VALUE=DATE:20180410
UID:nOcqxQjQfeFbSXwexZGmMR-k@stanza.co
SUMMARY:Pelicans vs. Dash
DESCRIPTION:Pelicans vs. Dash\n\nFollow on MiLB First Pitch: https://stza.co/+w0yg-1i\n\nShop: https://stza.co/+w0yg-h\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Pelicans vs. Dash
<2018-04-11 Wed>--<2018-04-10 Tue>
:PROPERTIES:
:ID:       Eg2bvPGmxEwSsfnDwjYUe4Ia@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Pelicans vs. Dash Pelicans vs. Dash

Follow on MiLB First Pitch  https //stza.co/+w0yj-1R

Shop  https //stza.co/+w0yj-H

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Pelicans vs. Dash
END:VALARM
DTSTART;VALUE=DATE:20180411
DTEND;VALUE=DATE:20180411
UID:Eg2bvPGmxEwSsfnDwjYUe4Ia@stanza.co
SUMMARY:Pelicans vs. Dash
DESCRIPTION:Pelicans vs. Dash\n\nFollow on MiLB First Pitch: https://stza.co/+w0yj-1R\n\nShop: https://stza.co/+w0yj-H\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Pelicans @ Wood Ducks
<2018-04-12 Thu 18:00-21:00>
:PROPERTIES:
:ID:       ZcoH48UVXiQpLcWiY9y2h4ql@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Pelicans @ Wood Ducks Pelicans @ Wood Ducks

Follow on MiLB First Pitch  https //stza.co/+w0xG-2g

Shop  https //stza.co/+w0xG-3u

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Pelicans @ Wood Ducks
END:VALARM
DTSTART:20180412T230000Z
DTEND:20180413T020000Z
UID:ZcoH48UVXiQpLcWiY9y2h4ql@stanza.co
SUMMARY:Pelicans @ Wood Ducks
DESCRIPTION:Pelicans @ Wood Ducks\n\nFollow on MiLB First Pitch: https://stza.co/+w0xG-2g\n\nShop: https://stza.co/+w0xG-3u\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Pelicans @ Wood Ducks
<2018-04-13 Fri 18:00-21:00>
:PROPERTIES:
:ID:       xaKh75X6fzUV7BZ3adeQXI09@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Pelicans @ Wood Ducks Pelicans @ Wood Ducks

Follow on MiLB First Pitch  https //stza.co/+w0xH-3s

Shop  https //stza.co/+w0xH-2B

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Pelicans @ Wood Ducks
END:VALARM
DTSTART:20180413T230000Z
DTEND:20180414T020000Z
UID:xaKh75X6fzUV7BZ3adeQXI09@stanza.co
SUMMARY:Pelicans @ Wood Ducks
DESCRIPTION:Pelicans @ Wood Ducks\n\nFollow on MiLB First Pitch: https://stza.co/+w0xH-3s\n\nShop: https://stza.co/+w0xH-2B\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Pelicans @ Wood Ducks
<2018-04-14 Sat 17:00-20:00>
:PROPERTIES:
:ID:       uQcpUX8EQwFUjEsZcozZJs7c@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Pelicans @ Wood Ducks Pelicans @ Wood Ducks

Follow on MiLB First Pitch  https //stza.co/+w0xI-b

Shop  https //stza.co/+w0xI-1K

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Pelicans @ Wood Ducks
END:VALARM
DTSTART:20180414T220000Z
DTEND:20180415T010000Z
UID:uQcpUX8EQwFUjEsZcozZJs7c@stanza.co
SUMMARY:Pelicans @ Wood Ducks
DESCRIPTION:Pelicans @ Wood Ducks\n\nFollow on MiLB First Pitch: https://stza.co/+w0xI-b\n\nShop: https://stza.co/+w0xI-1K\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Pelicans @ Wood Ducks
<2018-04-15 Sun 13:00-16:00>
:PROPERTIES:
:ID:       ovcx0sY9822iFS8PPBRBx9AH@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Pelicans @ Wood Ducks Pelicans @ Wood Ducks

Follow on MiLB First Pitch  https //stza.co/+w0xJ-2S

Shop  https //stza.co/+w0xJ-l

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Pelicans @ Wood Ducks
END:VALARM
DTSTART:20180415T180000Z
DTEND:20180415T210000Z
UID:ovcx0sY9822iFS8PPBRBx9AH@stanza.co
SUMMARY:Pelicans @ Wood Ducks
DESCRIPTION:Pelicans @ Wood Ducks\n\nFollow on MiLB First Pitch: https://stza.co/+w0xJ-2S\n\nShop: https://stza.co/+w0xJ-l\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Pelicans @ Astros
<2018-04-16 Mon 18:00-21:00>
:PROPERTIES:
:ID:       ASZHOBbKxQSl5nHYnRoQ26dw@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Pelicans @ Astros Pelicans @ Astros

Follow on MiLB First Pitch  https //stza.co/+xM9j-15

Shop  https //stza.co/+xM9j-1p

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Pelicans @ Astros
END:VALARM
DTSTART:20180416T230000Z
DTEND:20180417T020000Z
UID:ASZHOBbKxQSl5nHYnRoQ26dw@stanza.co
SUMMARY:Pelicans @ Astros
DESCRIPTION:Pelicans @ Astros\n\nFollow on MiLB First Pitch: https://stza.co/+xM9j-15\n\nShop: https://stza.co/+xM9j-1p\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Pelicans @ Astros
<2018-04-17 Tue 18:00-21:00>
:PROPERTIES:
:ID:       eOIMl1irJpJFuNLFJwdrPM1z@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Pelicans @ Astros Pelicans @ Astros

Follow on MiLB First Pitch  https //stza.co/+xM9k-X

Shop  https //stza.co/+xM9k-1h

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Pelicans @ Astros
END:VALARM
DTSTART:20180417T230000Z
DTEND:20180418T020000Z
UID:eOIMl1irJpJFuNLFJwdrPM1z@stanza.co
SUMMARY:Pelicans @ Astros
DESCRIPTION:Pelicans @ Astros\n\nFollow on MiLB First Pitch: https://stza.co/+xM9k-X\n\nShop: https://stza.co/+xM9k-1h\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Pelicans @ Astros
<2018-04-18 Wed 18:00-21:00>
:PROPERTIES:
:ID:       MXOi8dWl2NNFl9d5xypSyL_4@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Pelicans @ Astros Pelicans @ Astros

Follow on MiLB First Pitch  https //stza.co/+xM9l-2F

Shop  https //stza.co/+xM9l-1D

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Pelicans @ Astros
END:VALARM
DTSTART:20180418T230000Z
DTEND:20180419T020000Z
UID:MXOi8dWl2NNFl9d5xypSyL_4@stanza.co
SUMMARY:Pelicans @ Astros
DESCRIPTION:Pelicans @ Astros\n\nFollow on MiLB First Pitch: https://stza.co/+xM9l-2F\n\nShop: https://stza.co/+xM9l-1D\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Pelicans vs. Wood Ducks
<2018-04-19 Thu>--<2018-04-18 Wed>
:PROPERTIES:
:ID:       MFxFUrYbdNKhu84suYc3Wrjd@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Pelicans vs. Wood Ducks Pelicans vs. Wood Ducks

Follow on MiLB First Pitch  https //stza.co/+w0yk-E

Shop  https //stza.co/+w0yk-2o

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Pelicans vs. Wood Ducks
END:VALARM
DTSTART;VALUE=DATE:20180419
DTEND;VALUE=DATE:20180419
UID:MFxFUrYbdNKhu84suYc3Wrjd@stanza.co
SUMMARY:Pelicans vs. Wood Ducks
DESCRIPTION:Pelicans vs. Wood Ducks\n\nFollow on MiLB First Pitch: https://stza.co/+w0yk-E\n\nShop: https://stza.co/+w0yk-2o\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Pelicans vs. Wood Ducks
<2018-04-20 Fri>--<2018-04-19 Thu>
:PROPERTIES:
:ID:       Te97CZO_0Qe81MPIEGJ5lasC@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Pelicans vs. Wood Ducks Pelicans vs. Wood Ducks

Follow on MiLB First Pitch  https //stza.co/+w0yn-m

Shop  https //stza.co/+w0yn-1T

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Pelicans vs. Wood Ducks
END:VALARM
DTSTART;VALUE=DATE:20180420
DTEND;VALUE=DATE:20180420
UID:Te97CZO_0Qe81MPIEGJ5lasC@stanza.co
SUMMARY:Pelicans vs. Wood Ducks
DESCRIPTION:Pelicans vs. Wood Ducks\n\nFollow on MiLB First Pitch: https://stza.co/+w0yn-m\n\nShop: https://stza.co/+w0yn-1T\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Pelicans vs. Wood Ducks
<2018-04-21 Sat>--<2018-04-20 Fri>
:PROPERTIES:
:ID:       LObm6D-4Ph8XWU_2zixD2nw8@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Pelicans vs. Wood Ducks Pelicans vs. Wood Ducks

Follow on MiLB First Pitch  https //stza.co/+w0yo-2A

Shop  https //stza.co/+w0yo-N

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Pelicans vs. Wood Ducks
END:VALARM
DTSTART;VALUE=DATE:20180421
DTEND;VALUE=DATE:20180421
UID:LObm6D-4Ph8XWU_2zixD2nw8@stanza.co
SUMMARY:Pelicans vs. Wood Ducks
DESCRIPTION:Pelicans vs. Wood Ducks\n\nFollow on MiLB First Pitch: https://stza.co/+w0yo-2A\n\nShop: https://stza.co/+w0yo-N\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Pelicans vs. Wood Ducks
<2018-04-22 Sun>--<2018-04-21 Sat>
:PROPERTIES:
:ID:       FLM5Xkqk4386W8MzWIVLvfP9@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Pelicans vs. Wood Ducks Pelicans vs. Wood Ducks

Follow on MiLB First Pitch  https //stza.co/+w0yr-2N

Shop  https //stza.co/+w0yr-33

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Pelicans vs. Wood Ducks
END:VALARM
DTSTART;VALUE=DATE:20180422
DTEND;VALUE=DATE:20180422
UID:FLM5Xkqk4386W8MzWIVLvfP9@stanza.co
SUMMARY:Pelicans vs. Wood Ducks
DESCRIPTION:Pelicans vs. Wood Ducks\n\nFollow on MiLB First Pitch: https://stza.co/+w0yr-2N\n\nShop: https://stza.co/+w0yr-33\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Pelicans @ Mudcats
<2018-04-24 Tue 18:00-21:00>
:PROPERTIES:
:ID:       _83J5DyLGno4Sk748Ophyrzm@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Pelicans @ Mudcats Pelicans @ Mudcats

Buy tickets here  https //stza.co/~w0xw

Follow on MiLB First Pitch  https //stza.co/+w0xw-2G

Shop  https //stza.co/+w0xw-3

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Pelicans @ Mudcats
END:VALARM
DTSTART:20180424T230000Z
DTEND:20180425T020000Z
UID:_83J5DyLGno4Sk748Ophyrzm@stanza.co
SUMMARY:Pelicans @ Mudcats
DESCRIPTION:Pelicans @ Mudcats\n\nBuy tickets here: https://stza.co/~w0xw\n\nFollow on MiLB First Pitch: https://stza.co/+w0xw-2G\n\nShop: https://stza.co/+w0xw-3\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Pelicans @ Mudcats
<2018-04-25 Wed 10:00-13:00>
:PROPERTIES:
:ID:       IacL_qcC0F7bVrxW2LD6w8rs@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Pelicans @ Mudcats Pelicans @ Mudcats

Buy tickets here  https //stza.co/~xVXk

Follow on MiLB First Pitch  https //stza.co/+xVXk-

Shop  https //stza.co/+xVXk-2y

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Pelicans @ Mudcats
END:VALARM
DTSTART:20180425T150000Z
DTEND:20180425T180000Z
UID:IacL_qcC0F7bVrxW2LD6w8rs@stanza.co
SUMMARY:Pelicans @ Mudcats
DESCRIPTION:Pelicans @ Mudcats\n\nBuy tickets here: https://stza.co/~xVXk\n\nFollow on MiLB First Pitch: https://stza.co/+xVXk-\n\nShop: https://stza.co/+xVXk-2y\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Pelicans @ Mudcats
<2018-04-26 Thu 18:00-21:00>
:PROPERTIES:
:ID:       IIJwMYeq6ZWOXKAOSwvsubjS@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Pelicans @ Mudcats Pelicans @ Mudcats

Buy tickets here  https //stza.co/~w0xy

Follow on MiLB First Pitch  https //stza.co/+w0xy-Z

Shop  https //stza.co/+w0xy-3d

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Pelicans @ Mudcats
END:VALARM
DTSTART:20180426T230000Z
DTEND:20180427T020000Z
UID:IIJwMYeq6ZWOXKAOSwvsubjS@stanza.co
SUMMARY:Pelicans @ Mudcats
DESCRIPTION:Pelicans @ Mudcats\n\nBuy tickets here: https://stza.co/~w0xy\n\nFollow on MiLB First Pitch: https://stza.co/+w0xy-Z\n\nShop: https://stza.co/+w0xy-3d\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Pelicans @ Red Sox
<2018-04-27 Fri>--<2018-04-26 Thu>
:PROPERTIES:
:ID:       PJUxww14-4hSq9wtbo4FKg52@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Pelicans @ Red Sox Pelicans @ Red Sox

Follow on MiLB First Pitch  https //stza.co/+w0Ao-3j

Shop  https //stza.co/+w0Ao-1o

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Pelicans @ Red Sox
END:VALARM
DTSTART;VALUE=DATE:20180427
DTEND;VALUE=DATE:20180427
UID:PJUxww14-4hSq9wtbo4FKg52@stanza.co
SUMMARY:Pelicans @ Red Sox
DESCRIPTION:Pelicans @ Red Sox\n\nFollow on MiLB First Pitch: https://stza.co/+w0Ao-3j\n\nShop: https://stza.co/+w0Ao-1o\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Pelicans @ Red Sox
<2018-04-28 Sat>--<2018-04-27 Fri>
:PROPERTIES:
:ID:       EOQQzxjnXTeK2Pc-yHo1SJJs@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Pelicans @ Red Sox Pelicans @ Red Sox

Follow on MiLB First Pitch  https //stza.co/+w0Ap-1M

Shop  https //stza.co/+w0Ap-3b

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Pelicans @ Red Sox
END:VALARM
DTSTART;VALUE=DATE:20180428
DTEND;VALUE=DATE:20180428
UID:EOQQzxjnXTeK2Pc-yHo1SJJs@stanza.co
SUMMARY:Pelicans @ Red Sox
DESCRIPTION:Pelicans @ Red Sox\n\nFollow on MiLB First Pitch: https://stza.co/+w0Ap-1M\n\nShop: https://stza.co/+w0Ap-3b\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Pelicans @ Red Sox
<2018-04-29 Sun>--<2018-04-28 Sat>
:PROPERTIES:
:ID:       LTAE3XaM6XwZcLwAH4DlmGXe@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Pelicans @ Red Sox Pelicans @ Red Sox

Follow on MiLB First Pitch  https //stza.co/+w0Aq-3B

Shop  https //stza.co/+w0Aq-3N

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Pelicans @ Red Sox
END:VALARM
DTSTART;VALUE=DATE:20180429
DTEND;VALUE=DATE:20180429
UID:LTAE3XaM6XwZcLwAH4DlmGXe@stanza.co
SUMMARY:Pelicans @ Red Sox
DESCRIPTION:Pelicans @ Red Sox\n\nFollow on MiLB First Pitch: https://stza.co/+w0Aq-3B\n\nShop: https://stza.co/+w0Aq-3N\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Pelicans vs. Mudcats
<2018-05-01 Tue>--<2018-04-30 Mon>
:PROPERTIES:
:ID:       -OW-7y63YsiblH6gcstmLDHL@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Pelicans vs. Mudcats Pelicans vs. Mudcats

Follow on MiLB First Pitch  https //stza.co/+w0yt-2a

Shop  https //stza.co/+w0yt-3w

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Pelicans vs. Mudcats
END:VALARM
DTSTART;VALUE=DATE:20180501
DTEND;VALUE=DATE:20180501
UID:-OW-7y63YsiblH6gcstmLDHL@stanza.co
SUMMARY:Pelicans vs. Mudcats
DESCRIPTION:Pelicans vs. Mudcats\n\nFollow on MiLB First Pitch: https://stza.co/+w0yt-2a\n\nShop: https://stza.co/+w0yt-3w\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Pelicans vs. Mudcats
<2018-05-02 Wed>--<2018-05-01 Tue>
:PROPERTIES:
:ID:       Ps5vuPwbdn9mBeQ_PxTV7r4g@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Pelicans vs. Mudcats Pelicans vs. Mudcats

Follow on MiLB First Pitch  https //stza.co/+w0yu-1G

Shop  https //stza.co/+w0yu-4

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Pelicans vs. Mudcats
END:VALARM
DTSTART;VALUE=DATE:20180502
DTEND;VALUE=DATE:20180502
UID:Ps5vuPwbdn9mBeQ_PxTV7r4g@stanza.co
SUMMARY:Pelicans vs. Mudcats
DESCRIPTION:Pelicans vs. Mudcats\n\nFollow on MiLB First Pitch: https://stza.co/+w0yu-1G\n\nShop: https://stza.co/+w0yu-4\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Pelicans vs. Mudcats
<2018-05-03 Thu>--<2018-05-02 Wed>
:PROPERTIES:
:ID:       7ReziH-4vAF_22kkcYMZbS_C@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Pelicans vs. Mudcats Pelicans vs. Mudcats

Follow on MiLB First Pitch  https //stza.co/+w0yx-2

Shop  https //stza.co/+w0yx-3Q

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Pelicans vs. Mudcats
END:VALARM
DTSTART;VALUE=DATE:20180503
DTEND;VALUE=DATE:20180503
UID:7ReziH-4vAF_22kkcYMZbS_C@stanza.co
SUMMARY:Pelicans vs. Mudcats
DESCRIPTION:Pelicans vs. Mudcats\n\nFollow on MiLB First Pitch: https://stza.co/+w0yx-2\n\nShop: https://stza.co/+w0yx-3Q\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Pelicans @ Hillcats
<2018-05-04 Fri 17:30-20:30>
:PROPERTIES:
:ID:       cs7thrOyNqn_W9FyIH3yc6nd@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Pelicans @ Hillcats Pelicans @ Hillcats

Buy tickets here  https //stza.co/~y3VP

Follow on MiLB First Pitch  https //stza.co/+y3VP-1K

Shop  https //stza.co/+y3VP-Z

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Pelicans @ Hillcats
END:VALARM
DTSTART:20180504T223000Z
DTEND:20180505T013000Z
UID:cs7thrOyNqn_W9FyIH3yc6nd@stanza.co
SUMMARY:Pelicans @ Hillcats
DESCRIPTION:Pelicans @ Hillcats\n\nBuy tickets here: https://stza.co/~y3VP\n\nFollow on MiLB First Pitch: https://stza.co/+y3VP-1K\n\nShop: https://stza.co/+y3VP-Z\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Pelicans @ Hillcats
<2018-05-05 Sat 17:00-20:00>
:PROPERTIES:
:ID:       i1QiLkHaG8a-KWwjHRKLmKji@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Pelicans @ Hillcats Pelicans @ Hillcats

Buy tickets here  https //stza.co/~y3VQ

Follow on MiLB First Pitch  https //stza.co/+y3VQ-1e

Shop  https //stza.co/+y3VQ-1T

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Pelicans @ Hillcats
END:VALARM
DTSTART:20180505T220000Z
DTEND:20180506T010000Z
UID:i1QiLkHaG8a-KWwjHRKLmKji@stanza.co
SUMMARY:Pelicans @ Hillcats
DESCRIPTION:Pelicans @ Hillcats\n\nBuy tickets here: https://stza.co/~y3VQ\n\nFollow on MiLB First Pitch: https://stza.co/+y3VQ-1e\n\nShop: https://stza.co/+y3VQ-1T\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Pelicans @ Hillcats
<2018-05-06 Sun 13:00-16:00>
:PROPERTIES:
:ID:       lGgdYFexJCu6nwUFwFc3Amrr@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Pelicans @ Hillcats Pelicans @ Hillcats

Buy tickets here  https //stza.co/~y3VR

Follow on MiLB First Pitch  https //stza.co/+y3VR-3y

Shop  https //stza.co/+y3VR-A

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Pelicans @ Hillcats
END:VALARM
DTSTART:20180506T180000Z
DTEND:20180506T210000Z
UID:lGgdYFexJCu6nwUFwFc3Amrr@stanza.co
SUMMARY:Pelicans @ Hillcats
DESCRIPTION:Pelicans @ Hillcats\n\nBuy tickets here: https://stza.co/~y3VR\n\nFollow on MiLB First Pitch: https://stza.co/+y3VR-3y\n\nShop: https://stza.co/+y3VR-A\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Pelicans @ Wood Ducks
<2018-05-07 Mon 18:00-21:00>
:PROPERTIES:
:ID:       zXrt2bSuMK0RjoHDkvApl2Q2@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Pelicans @ Wood Ducks Pelicans @ Wood Ducks

Follow on MiLB First Pitch  https //stza.co/+w0xK-3o

Shop  https //stza.co/+w0xK-2b

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Pelicans @ Wood Ducks
END:VALARM
DTSTART:20180507T230000Z
DTEND:20180508T020000Z
UID:zXrt2bSuMK0RjoHDkvApl2Q2@stanza.co
SUMMARY:Pelicans @ Wood Ducks
DESCRIPTION:Pelicans @ Wood Ducks\n\nFollow on MiLB First Pitch: https://stza.co/+w0xK-3o\n\nShop: https://stza.co/+w0xK-2b\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Pelicans @ Wood Ducks
<2018-05-08 Tue 18:00-21:00>
:PROPERTIES:
:ID:       3QFrfmVXSMr6EuheHCjyE44n@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Pelicans @ Wood Ducks Pelicans @ Wood Ducks

Follow on MiLB First Pitch  https //stza.co/+w0xL-2X

Shop  https //stza.co/+w0xL-h

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Pelicans @ Wood Ducks
END:VALARM
DTSTART:20180508T230000Z
DTEND:20180509T020000Z
UID:3QFrfmVXSMr6EuheHCjyE44n@stanza.co
SUMMARY:Pelicans @ Wood Ducks
DESCRIPTION:Pelicans @ Wood Ducks\n\nFollow on MiLB First Pitch: https://stza.co/+w0xL-2X\n\nShop: https://stza.co/+w0xL-h\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Pelicans @ Wood Ducks
<2018-05-09 Wed 10:00-13:00>
:PROPERTIES:
:ID:       dXKni7dXr1Mn38wrfPnGKKWh@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Pelicans @ Wood Ducks Pelicans @ Wood Ducks

Follow on MiLB First Pitch  https //stza.co/+w0xM-2U

Shop  https //stza.co/+w0xM-1C

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Pelicans @ Wood Ducks
END:VALARM
DTSTART:20180509T150000Z
DTEND:20180509T180000Z
UID:dXKni7dXr1Mn38wrfPnGKKWh@stanza.co
SUMMARY:Pelicans @ Wood Ducks
DESCRIPTION:Pelicans @ Wood Ducks\n\nFollow on MiLB First Pitch: https://stza.co/+w0xM-2U\n\nShop: https://stza.co/+w0xM-1C\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Pelicans vs. Astros
<2018-05-10 Thu>--<2018-05-09 Wed>
:PROPERTIES:
:ID:       4bv-TBqdDbzgicyP67Mx22Sw@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Pelicans vs. Astros Pelicans vs. Astros

Follow on MiLB First Pitch  https //stza.co/+w0yz-5

Shop  https //stza.co/+w0yz-2t

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Pelicans vs. Astros
END:VALARM
DTSTART;VALUE=DATE:20180510
DTEND;VALUE=DATE:20180510
UID:4bv-TBqdDbzgicyP67Mx22Sw@stanza.co
SUMMARY:Pelicans vs. Astros
DESCRIPTION:Pelicans vs. Astros\n\nFollow on MiLB First Pitch: https://stza.co/+w0yz-5\n\nShop: https://stza.co/+w0yz-2t\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Pelicans vs. Astros
<2018-05-11 Fri>--<2018-05-10 Thu>
:PROPERTIES:
:ID:       dfBIjoVEdm65M82Ovt-4m1-3@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Pelicans vs. Astros Pelicans vs. Astros

Follow on MiLB First Pitch  https //stza.co/+w0yA-26

Shop  https //stza.co/+w0yA-3Z

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Pelicans vs. Astros
END:VALARM
DTSTART;VALUE=DATE:20180511
DTEND;VALUE=DATE:20180511
UID:dfBIjoVEdm65M82Ovt-4m1-3@stanza.co
SUMMARY:Pelicans vs. Astros
DESCRIPTION:Pelicans vs. Astros\n\nFollow on MiLB First Pitch: https://stza.co/+w0yA-26\n\nShop: https://stza.co/+w0yA-3Z\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Pelicans vs. Astros
<2018-05-12 Sat>--<2018-05-11 Fri>
:PROPERTIES:
:ID:       iiiCvj3YlJZU83YDvt9Bv-lK@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Pelicans vs. Astros Pelicans vs. Astros

Follow on MiLB First Pitch  https //stza.co/+w0yC-2l

Shop  https //stza.co/+w0yC-1z

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Pelicans vs. Astros
END:VALARM
DTSTART;VALUE=DATE:20180512
DTEND;VALUE=DATE:20180512
UID:iiiCvj3YlJZU83YDvt9Bv-lK@stanza.co
SUMMARY:Pelicans vs. Astros
DESCRIPTION:Pelicans vs. Astros\n\nFollow on MiLB First Pitch: https://stza.co/+w0yC-2l\n\nShop: https://stza.co/+w0yC-1z\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Pelicans vs. Astros
<2018-05-13 Sun>--<2018-05-12 Sat>
:PROPERTIES:
:ID:       fTMKNw2HBUYJOI8SkwlMLqWr@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Pelicans vs. Astros Pelicans vs. Astros

Follow on MiLB First Pitch  https //stza.co/+w0yE-1M

Shop  https //stza.co/+w0yE-29

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Pelicans vs. Astros
END:VALARM
DTSTART;VALUE=DATE:20180513
DTEND;VALUE=DATE:20180513
UID:fTMKNw2HBUYJOI8SkwlMLqWr@stanza.co
SUMMARY:Pelicans vs. Astros
DESCRIPTION:Pelicans vs. Astros\n\nFollow on MiLB First Pitch: https://stza.co/+w0yE-1M\n\nShop: https://stza.co/+w0yE-29\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Pelicans @ Blue Rocks
<2018-05-15 Tue 17:35-20:35>
:PROPERTIES:
:ID:       LBfHPo5LysHsbBQQnpK3UvTU@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Pelicans @ Blue Rocks Pelicans @ Blue Rocks

Follow on MiLB First Pitch  https //stza.co/+wX93-38

Shop  https //stza.co/+wX93-1E

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Pelicans @ Blue Rocks
END:VALARM
DTSTART:20180515T223500Z
DTEND:20180516T013500Z
UID:LBfHPo5LysHsbBQQnpK3UvTU@stanza.co
SUMMARY:Pelicans @ Blue Rocks
DESCRIPTION:Pelicans @ Blue Rocks\n\nFollow on MiLB First Pitch: https://stza.co/+wX93-38\n\nShop: https://stza.co/+wX93-1E\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Pelicans @ Blue Rocks
<2018-05-16 Wed 09:35-12:35>
:PROPERTIES:
:ID:       Zev7lBEkFhHaDood607DcDpY@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Pelicans @ Blue Rocks Pelicans @ Blue Rocks

Follow on MiLB First Pitch  https //stza.co/+wX94-2P

Shop  https //stza.co/+wX94-22

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Pelicans @ Blue Rocks
END:VALARM
DTSTART:20180516T143500Z
DTEND:20180516T173500Z
UID:Zev7lBEkFhHaDood607DcDpY@stanza.co
SUMMARY:Pelicans @ Blue Rocks
DESCRIPTION:Pelicans @ Blue Rocks\n\nFollow on MiLB First Pitch: https://stza.co/+wX94-2P\n\nShop: https://stza.co/+wX94-22\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Pelicans @ Blue Rocks
<2018-05-17 Thu 17:35-20:35>
:PROPERTIES:
:ID:       PpzBlZZRPhN_Z-cj-k9asiN9@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Pelicans @ Blue Rocks Pelicans @ Blue Rocks

Follow on MiLB First Pitch  https //stza.co/+wX95-3c

Shop  https //stza.co/+wX95-16

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Pelicans @ Blue Rocks
END:VALARM
DTSTART:20180517T223500Z
DTEND:20180518T013500Z
UID:PpzBlZZRPhN_Z-cj-k9asiN9@stanza.co
SUMMARY:Pelicans @ Blue Rocks
DESCRIPTION:Pelicans @ Blue Rocks\n\nFollow on MiLB First Pitch: https://stza.co/+wX95-3c\n\nShop: https://stza.co/+wX95-16\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Pelicans @ Keys
<2018-05-18 Fri 18:00-21:00>
:PROPERTIES:
:ID:       BY0L7XrzLDyBsUc4ij6P06Wd@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Pelicans @ Keys Pelicans @ Keys

Follow on MiLB First Pitch  https //stza.co/+wiae-$

Shop  https //stza.co/+wiae-11

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Pelicans @ Keys
END:VALARM
DTSTART:20180518T230000Z
DTEND:20180519T020000Z
UID:BY0L7XrzLDyBsUc4ij6P06Wd@stanza.co
SUMMARY:Pelicans @ Keys
DESCRIPTION:Pelicans @ Keys\n\nFollow on MiLB First Pitch: https://stza.co/+wiae-$\n\nShop: https://stza.co/+wiae-11\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Pelicans @ Keys
<2018-05-19 Sat 17:00-20:00>
:PROPERTIES:
:ID:       5JVHcb8z4UNB0RFOboV2xMGp@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Pelicans @ Keys Pelicans @ Keys

Follow on MiLB First Pitch  https //stza.co/+wiaf-29

Shop  https //stza.co/+wiaf-38

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Pelicans @ Keys
END:VALARM
DTSTART:20180519T220000Z
DTEND:20180520T010000Z
UID:5JVHcb8z4UNB0RFOboV2xMGp@stanza.co
SUMMARY:Pelicans @ Keys
DESCRIPTION:Pelicans @ Keys\n\nFollow on MiLB First Pitch: https://stza.co/+wiaf-29\n\nShop: https://stza.co/+wiaf-38\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Pelicans @ Keys
<2018-05-20 Sun 13:00-16:00>
:PROPERTIES:
:ID:       R3ljtd1W_UBYD9rsWjUy7JsD@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Pelicans @ Keys Pelicans @ Keys

Follow on MiLB First Pitch  https //stza.co/+wiag-1W

Shop  https //stza.co/+wiag-3T

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Pelicans @ Keys
END:VALARM
DTSTART:20180520T180000Z
DTEND:20180520T210000Z
UID:R3ljtd1W_UBYD9rsWjUy7JsD@stanza.co
SUMMARY:Pelicans @ Keys
DESCRIPTION:Pelicans @ Keys\n\nFollow on MiLB First Pitch: https://stza.co/+wiag-1W\n\nShop: https://stza.co/+wiag-3T\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Pelicans vs. Hillcats
<2018-05-21 Mon>--<2018-05-20 Sun>
:PROPERTIES:
:ID:       zB-d59LWanRoMADN_ew_d-eq@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Pelicans vs. Hillcats Pelicans vs. Hillcats

Follow on MiLB First Pitch  https //stza.co/+w0yH-g

Shop  https //stza.co/+w0yH-z

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Pelicans vs. Hillcats
END:VALARM
DTSTART;VALUE=DATE:20180521
DTEND;VALUE=DATE:20180521
UID:zB-d59LWanRoMADN_ew_d-eq@stanza.co
SUMMARY:Pelicans vs. Hillcats
DESCRIPTION:Pelicans vs. Hillcats\n\nFollow on MiLB First Pitch: https://stza.co/+w0yH-g\n\nShop: https://stza.co/+w0yH-z\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Pelicans vs. Hillcats
<2018-05-22 Tue>--<2018-05-21 Mon>
:PROPERTIES:
:ID:       0UKBzF6yBq7BPNNiCKDBhfQc@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Pelicans vs. Hillcats Pelicans vs. Hillcats

Follow on MiLB First Pitch  https //stza.co/+w0yJ-W

Shop  https //stza.co/+w0yJ-1B

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Pelicans vs. Hillcats
END:VALARM
DTSTART;VALUE=DATE:20180522
DTEND;VALUE=DATE:20180522
UID:0UKBzF6yBq7BPNNiCKDBhfQc@stanza.co
SUMMARY:Pelicans vs. Hillcats
DESCRIPTION:Pelicans vs. Hillcats\n\nFollow on MiLB First Pitch: https://stza.co/+w0yJ-W\n\nShop: https://stza.co/+w0yJ-1B\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Pelicans vs. Hillcats
<2018-05-23 Wed>--<2018-05-22 Tue>
:PROPERTIES:
:ID:       Mg6sMgcyWoaT2yn4SDJuQ2uf@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Pelicans vs. Hillcats Pelicans vs. Hillcats

Follow on MiLB First Pitch  https //stza.co/+w0yL-E

Shop  https //stza.co/+w0yL-b

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Pelicans vs. Hillcats
END:VALARM
DTSTART;VALUE=DATE:20180523
DTEND;VALUE=DATE:20180523
UID:Mg6sMgcyWoaT2yn4SDJuQ2uf@stanza.co
SUMMARY:Pelicans vs. Hillcats
DESCRIPTION:Pelicans vs. Hillcats\n\nFollow on MiLB First Pitch: https://stza.co/+w0yL-E\n\nShop: https://stza.co/+w0yL-b\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Pelicans vs. Hillcats
<2018-05-24 Thu>--<2018-05-23 Wed>
:PROPERTIES:
:ID:       yudYf1nmOz0ta6N-95D_TMhh@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Pelicans vs. Hillcats Pelicans vs. Hillcats

Follow on MiLB First Pitch  https //stza.co/+w0yN-2n

Shop  https //stza.co/+w0yN-1h

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Pelicans vs. Hillcats
END:VALARM
DTSTART;VALUE=DATE:20180524
DTEND;VALUE=DATE:20180524
UID:yudYf1nmOz0ta6N-95D_TMhh@stanza.co
SUMMARY:Pelicans vs. Hillcats
DESCRIPTION:Pelicans vs. Hillcats\n\nFollow on MiLB First Pitch: https://stza.co/+w0yN-2n\n\nShop: https://stza.co/+w0yN-1h\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Pelicans @ Mudcats
<2018-05-25 Fri 18:00-21:00>
:PROPERTIES:
:ID:       bXGaeoCzkc20hCt4szg-lv3-@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Pelicans @ Mudcats Pelicans @ Mudcats

Buy tickets here  https //stza.co/~w0xz

Follow on MiLB First Pitch  https //stza.co/+w0xz-3F

Shop  https //stza.co/+w0xz-2Z

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Pelicans @ Mudcats
END:VALARM
DTSTART:20180525T230000Z
DTEND:20180526T020000Z
UID:bXGaeoCzkc20hCt4szg-lv3-@stanza.co
SUMMARY:Pelicans @ Mudcats
DESCRIPTION:Pelicans @ Mudcats\n\nBuy tickets here: https://stza.co/~w0xz\n\nFollow on MiLB First Pitch: https://stza.co/+w0xz-3F\n\nShop: https://stza.co/+w0xz-2Z\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Pelicans @ Mudcats
<2018-05-26 Sat 16:00-19:00>
:PROPERTIES:
:ID:       etg2CE_XasRZ219Ql9kBWrCM@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Pelicans @ Mudcats Pelicans @ Mudcats

Buy tickets here  https //stza.co/~w0xA

Follow on MiLB First Pitch  https //stza.co/+w0xA-2C

Shop  https //stza.co/+w0xA-1z

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Pelicans @ Mudcats
END:VALARM
DTSTART:20180526T210000Z
DTEND:20180527T000000Z
UID:etg2CE_XasRZ219Ql9kBWrCM@stanza.co
SUMMARY:Pelicans @ Mudcats
DESCRIPTION:Pelicans @ Mudcats\n\nBuy tickets here: https://stza.co/~w0xA\n\nFollow on MiLB First Pitch: https://stza.co/+w0xA-2C\n\nShop: https://stza.co/+w0xA-1z\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Pelicans @ Mudcats
<2018-05-27 Sun 17:00-20:00>
:PROPERTIES:
:ID:       vWDtWaJiMFGliPcwvXMvmMyV@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Pelicans @ Mudcats Pelicans @ Mudcats

Buy tickets here  https //stza.co/~w0xB

Follow on MiLB First Pitch  https //stza.co/+w0xB-3d

Shop  https //stza.co/+w0xB-1x

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Pelicans @ Mudcats
END:VALARM
DTSTART:20180527T220000Z
DTEND:20180528T010000Z
UID:vWDtWaJiMFGliPcwvXMvmMyV@stanza.co
SUMMARY:Pelicans @ Mudcats
DESCRIPTION:Pelicans @ Mudcats\n\nBuy tickets here: https://stza.co/~w0xB\n\nFollow on MiLB First Pitch: https://stza.co/+w0xB-3d\n\nShop: https://stza.co/+w0xB-1x\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Pelicans @ Mudcats
<2018-05-28 Mon 11:00-14:00>
:PROPERTIES:
:ID:       LPtwUMIXwMRs7ZyMPep85xfZ@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Pelicans @ Mudcats Pelicans @ Mudcats

Buy tickets here  https //stza.co/~w0xC

Follow on MiLB First Pitch  https //stza.co/+w0xC-2k

Shop  https //stza.co/+w0xC-r

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Pelicans @ Mudcats
END:VALARM
DTSTART:20180528T160000Z
DTEND:20180528T190000Z
UID:LPtwUMIXwMRs7ZyMPep85xfZ@stanza.co
SUMMARY:Pelicans @ Mudcats
DESCRIPTION:Pelicans @ Mudcats\n\nBuy tickets here: https://stza.co/~w0xC\n\nFollow on MiLB First Pitch: https://stza.co/+w0xC-2k\n\nShop: https://stza.co/+w0xC-r\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Pelicans vs. Dash
<2018-05-29 Tue>--<2018-05-28 Mon>
:PROPERTIES:
:ID:       3DIOl-QUMPZ8CoyaE_bBq8Mx@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Pelicans vs. Dash Pelicans vs. Dash

Follow on MiLB First Pitch  https //stza.co/+w0yP-2l

Shop  https //stza.co/+w0yP-1V

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Pelicans vs. Dash
END:VALARM
DTSTART;VALUE=DATE:20180529
DTEND;VALUE=DATE:20180529
UID:3DIOl-QUMPZ8CoyaE_bBq8Mx@stanza.co
SUMMARY:Pelicans vs. Dash
DESCRIPTION:Pelicans vs. Dash\n\nFollow on MiLB First Pitch: https://stza.co/+w0yP-2l\n\nShop: https://stza.co/+w0yP-1V\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Pelicans vs. Dash
<2018-05-30 Wed>--<2018-05-29 Tue>
:PROPERTIES:
:ID:       0_hzNKt8iruK49vidCaSTpMa@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Pelicans vs. Dash Pelicans vs. Dash

Follow on MiLB First Pitch  https //stza.co/+w0yR-34

Shop  https //stza.co/+w0yR-1T

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Pelicans vs. Dash
END:VALARM
DTSTART;VALUE=DATE:20180530
DTEND;VALUE=DATE:20180530
UID:0_hzNKt8iruK49vidCaSTpMa@stanza.co
SUMMARY:Pelicans vs. Dash
DESCRIPTION:Pelicans vs. Dash\n\nFollow on MiLB First Pitch: https://stza.co/+w0yR-34\n\nShop: https://stza.co/+w0yR-1T\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Pelicans vs. Dash
<2018-05-31 Thu>--<2018-05-30 Wed>
:PROPERTIES:
:ID:       YrUt0Az4WJVW4OBCqsg-gdT7@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Pelicans vs. Dash Pelicans vs. Dash

Follow on MiLB First Pitch  https //stza.co/+w0yT-3c

Shop  https //stza.co/+w0yT-1b

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Pelicans vs. Dash
END:VALARM
DTSTART;VALUE=DATE:20180531
DTEND;VALUE=DATE:20180531
UID:YrUt0Az4WJVW4OBCqsg-gdT7@stanza.co
SUMMARY:Pelicans vs. Dash
DESCRIPTION:Pelicans vs. Dash\n\nFollow on MiLB First Pitch: https://stza.co/+w0yT-3c\n\nShop: https://stza.co/+w0yT-1b\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Pelicans vs. Wood Ducks
<2018-06-01 Fri>--<2018-05-31 Thu>
:PROPERTIES:
:ID:       BUDbKuLzaH-Js9dj7A00pHv0@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Pelicans vs. Wood Ducks Pelicans vs. Wood Ducks

Follow on MiLB First Pitch  https //stza.co/+w0yU-1g

Shop  https //stza.co/+w0yU-25

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Pelicans vs. Wood Ducks
END:VALARM
DTSTART;VALUE=DATE:20180601
DTEND;VALUE=DATE:20180601
UID:BUDbKuLzaH-Js9dj7A00pHv0@stanza.co
SUMMARY:Pelicans vs. Wood Ducks
DESCRIPTION:Pelicans vs. Wood Ducks\n\nFollow on MiLB First Pitch: https://stza.co/+w0yU-1g\n\nShop: https://stza.co/+w0yU-25\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Pelicans vs. Wood Ducks
<2018-06-02 Sat>--<2018-06-01 Fri>
:PROPERTIES:
:ID:       prqH2n4O_YFO6aA0soR8lvkN@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Pelicans vs. Wood Ducks Pelicans vs. Wood Ducks

Follow on MiLB First Pitch  https //stza.co/+w0yX-2y

Shop  https //stza.co/+w0yX-t

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Pelicans vs. Wood Ducks
END:VALARM
DTSTART;VALUE=DATE:20180602
DTEND;VALUE=DATE:20180602
UID:prqH2n4O_YFO6aA0soR8lvkN@stanza.co
SUMMARY:Pelicans vs. Wood Ducks
DESCRIPTION:Pelicans vs. Wood Ducks\n\nFollow on MiLB First Pitch: https://stza.co/+w0yX-2y\n\nShop: https://stza.co/+w0yX-t\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Pelicans vs. Wood Ducks
<2018-06-03 Sun>--<2018-06-02 Sat>
:PROPERTIES:
:ID:       Nkc9EhyhKf6i8mGXBYdAr2qK@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Pelicans vs. Wood Ducks Pelicans vs. Wood Ducks

Follow on MiLB First Pitch  https //stza.co/+w0yZ-3B

Shop  https //stza.co/+w0yZ-2C

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Pelicans vs. Wood Ducks
END:VALARM
DTSTART;VALUE=DATE:20180603
DTEND;VALUE=DATE:20180603
UID:Nkc9EhyhKf6i8mGXBYdAr2qK@stanza.co
SUMMARY:Pelicans vs. Wood Ducks
DESCRIPTION:Pelicans vs. Wood Ducks\n\nFollow on MiLB First Pitch: https://stza.co/+w0yZ-3B\n\nShop: https://stza.co/+w0yZ-2C\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Pelicans @ Astros
<2018-06-05 Tue 18:00-21:00>
:PROPERTIES:
:ID:       IZMovd7LLEcnGZ21LjtBTLBI@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Pelicans @ Astros Pelicans @ Astros

Follow on MiLB First Pitch  https //stza.co/+xM9n-28

Shop  https //stza.co/+xM9n-2d

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Pelicans @ Astros
END:VALARM
DTSTART:20180605T230000Z
DTEND:20180606T020000Z
UID:IZMovd7LLEcnGZ21LjtBTLBI@stanza.co
SUMMARY:Pelicans @ Astros
DESCRIPTION:Pelicans @ Astros\n\nFollow on MiLB First Pitch: https://stza.co/+xM9n-28\n\nShop: https://stza.co/+xM9n-2d\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Pelicans @ Astros
<2018-06-06 Wed 18:00-21:00>
:PROPERTIES:
:ID:       HjSQ9CjLqMY4MwPo2xkR3RTs@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Pelicans @ Astros Pelicans @ Astros

Follow on MiLB First Pitch  https //stza.co/+xM9o-2q

Shop  https //stza.co/+xM9o-3

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Pelicans @ Astros
END:VALARM
DTSTART:20180606T230000Z
DTEND:20180607T020000Z
UID:HjSQ9CjLqMY4MwPo2xkR3RTs@stanza.co
SUMMARY:Pelicans @ Astros
DESCRIPTION:Pelicans @ Astros\n\nFollow on MiLB First Pitch: https://stza.co/+xM9o-2q\n\nShop: https://stza.co/+xM9o-3\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Pelicans @ Astros
<2018-06-07 Thu 18:00-21:00>
:PROPERTIES:
:ID:       FuSh7i3PInPjN2NeuG4PAGmu@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Pelicans @ Astros Pelicans @ Astros

Follow on MiLB First Pitch  https //stza.co/+xM9p-h

Shop  https //stza.co/+xM9p-1K

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Pelicans @ Astros
END:VALARM
DTSTART:20180607T230000Z
DTEND:20180608T020000Z
UID:FuSh7i3PInPjN2NeuG4PAGmu@stanza.co
SUMMARY:Pelicans @ Astros
DESCRIPTION:Pelicans @ Astros\n\nFollow on MiLB First Pitch: https://stza.co/+xM9p-h\n\nShop: https://stza.co/+xM9p-1K\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Pelicans vs. Red Sox
<2018-06-08 Fri>--<2018-06-07 Thu>
:PROPERTIES:
:ID:       m7D7M4xtXXG65iTU3-Cw_Ejq@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Pelicans vs. Red Sox Pelicans vs. Red Sox

Follow on MiLB First Pitch  https //stza.co/+w0y$-1l

Shop  https //stza.co/+w0y$-1K

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Pelicans vs. Red Sox
END:VALARM
DTSTART;VALUE=DATE:20180608
DTEND;VALUE=DATE:20180608
UID:m7D7M4xtXXG65iTU3-Cw_Ejq@stanza.co
SUMMARY:Pelicans vs. Red Sox
DESCRIPTION:Pelicans vs. Red Sox\n\nFollow on MiLB First Pitch: https://stza.co/+w0y$-1l\n\nShop: https://stza.co/+w0y$-1K\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Pelicans vs. Red Sox
<2018-06-09 Sat>--<2018-06-08 Fri>
:PROPERTIES:
:ID:       Lp630M4mQbnz2x46v1HGDsje@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Pelicans vs. Red Sox Pelicans vs. Red Sox

Follow on MiLB First Pitch  https //stza.co/+w0z0-E

Shop  https //stza.co/+w0z0-3L

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Pelicans vs. Red Sox
END:VALARM
DTSTART;VALUE=DATE:20180609
DTEND;VALUE=DATE:20180609
UID:Lp630M4mQbnz2x46v1HGDsje@stanza.co
SUMMARY:Pelicans vs. Red Sox
DESCRIPTION:Pelicans vs. Red Sox\n\nFollow on MiLB First Pitch: https://stza.co/+w0z0-E\n\nShop: https://stza.co/+w0z0-3L\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Pelicans vs. Red Sox
<2018-06-10 Sun>--<2018-06-09 Sat>
:PROPERTIES:
:ID:       c5oer0l87DZZOqKOsPbCdKvo@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Pelicans vs. Red Sox Pelicans vs. Red Sox

Follow on MiLB First Pitch  https //stza.co/+w0z2-c

Shop  https //stza.co/+w0z2-1W

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Pelicans vs. Red Sox
END:VALARM
DTSTART;VALUE=DATE:20180610
DTEND;VALUE=DATE:20180610
UID:c5oer0l87DZZOqKOsPbCdKvo@stanza.co
SUMMARY:Pelicans vs. Red Sox
DESCRIPTION:Pelicans vs. Red Sox\n\nFollow on MiLB First Pitch: https://stza.co/+w0z2-c\n\nShop: https://stza.co/+w0z2-1W\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Pelicans @ Dash
<2018-06-11 Mon 18:00-21:00>
:PROPERTIES:
:ID:       drS-LsG7vO_B5u1mgC1fkPIG@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Pelicans @ Dash Pelicans @ Dash

Buy tickets here  https //stza.co/~w0Au

Follow on MiLB First Pitch  https //stza.co/+w0Au-3l

Shop  https //stza.co/+w0Au-2k

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Pelicans @ Dash
END:VALARM
DTSTART:20180611T230000Z
DTEND:20180612T020000Z
UID:drS-LsG7vO_B5u1mgC1fkPIG@stanza.co
SUMMARY:Pelicans @ Dash
DESCRIPTION:Pelicans @ Dash\n\nBuy tickets here: https://stza.co/~w0Au\n\nFollow on MiLB First Pitch: https://stza.co/+w0Au-3l\n\nShop: https://stza.co/+w0Au-2k\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Pelicans @ Dash
<2018-06-12 Tue 18:00-21:00>
:PROPERTIES:
:ID:       e_m-VtITCYCfNq6IGuUBlSVr@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Pelicans @ Dash Pelicans @ Dash

Buy tickets here  https //stza.co/~w0Av

Follow on MiLB First Pitch  https //stza.co/+w0Av-2t

Shop  https //stza.co/+w0Av-3o

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Pelicans @ Dash
END:VALARM
DTSTART:20180612T230000Z
DTEND:20180613T020000Z
UID:e_m-VtITCYCfNq6IGuUBlSVr@stanza.co
SUMMARY:Pelicans @ Dash
DESCRIPTION:Pelicans @ Dash\n\nBuy tickets here: https://stza.co/~w0Av\n\nFollow on MiLB First Pitch: https://stza.co/+w0Av-2t\n\nShop: https://stza.co/+w0Av-3o\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Pelicans @ Dash
<2018-06-13 Wed 18:00-21:00>
:PROPERTIES:
:ID:       qBkhyEY27V7FDWTW_Ut2nIQA@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Pelicans @ Dash Pelicans @ Dash

Buy tickets here  https //stza.co/~w0Aw

Follow on MiLB First Pitch  https //stza.co/+w0Aw-2v

Shop  https //stza.co/+w0Aw-1r

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Pelicans @ Dash
END:VALARM
DTSTART:20180613T230000Z
DTEND:20180614T020000Z
UID:qBkhyEY27V7FDWTW_Ut2nIQA@stanza.co
SUMMARY:Pelicans @ Dash
DESCRIPTION:Pelicans @ Dash\n\nBuy tickets here: https://stza.co/~w0Aw\n\nFollow on MiLB First Pitch: https://stza.co/+w0Aw-2v\n\nShop: https://stza.co/+w0Aw-1r\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Pelicans vs. Mudcats
<2018-06-14 Thu>--<2018-06-13 Wed>
:PROPERTIES:
:ID:       vw6dATeEAZ1Dbv85UJkE-iP2@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Pelicans vs. Mudcats Pelicans vs. Mudcats

Follow on MiLB First Pitch  https //stza.co/+w0z4-3L

Shop  https //stza.co/+w0z4-29

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Pelicans vs. Mudcats
END:VALARM
DTSTART;VALUE=DATE:20180614
DTEND;VALUE=DATE:20180614
UID:vw6dATeEAZ1Dbv85UJkE-iP2@stanza.co
SUMMARY:Pelicans vs. Mudcats
DESCRIPTION:Pelicans vs. Mudcats\n\nFollow on MiLB First Pitch: https://stza.co/+w0z4-3L\n\nShop: https://stza.co/+w0z4-29\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Pelicans vs. Mudcats
<2018-06-15 Fri>--<2018-06-14 Thu>
:PROPERTIES:
:ID:       emAsoGtmr7vic5JI1zSCHJNm@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Pelicans vs. Mudcats Pelicans vs. Mudcats

Follow on MiLB First Pitch  https //stza.co/+w0z6-2N

Shop  https //stza.co/+w0z6-2R

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Pelicans vs. Mudcats
END:VALARM
DTSTART;VALUE=DATE:20180615
DTEND;VALUE=DATE:20180615
UID:emAsoGtmr7vic5JI1zSCHJNm@stanza.co
SUMMARY:Pelicans vs. Mudcats
DESCRIPTION:Pelicans vs. Mudcats\n\nFollow on MiLB First Pitch: https://stza.co/+w0z6-2N\n\nShop: https://stza.co/+w0z6-2R\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Pelicans vs. Mudcats
<2018-06-16 Sat>--<2018-06-15 Fri>
:PROPERTIES:
:ID:       m31_rHCB4tOlgqFzlJq8nFUm@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Pelicans vs. Mudcats Pelicans vs. Mudcats

Follow on MiLB First Pitch  https //stza.co/+w0z9-K

Shop  https //stza.co/+w0z9-l

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Pelicans vs. Mudcats
END:VALARM
DTSTART;VALUE=DATE:20180616
DTEND;VALUE=DATE:20180616
UID:m31_rHCB4tOlgqFzlJq8nFUm@stanza.co
SUMMARY:Pelicans vs. Mudcats
DESCRIPTION:Pelicans vs. Mudcats\n\nFollow on MiLB First Pitch: https://stza.co/+w0z9-K\n\nShop: https://stza.co/+w0z9-l\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Pelicans vs. Mudcats
<2018-06-17 Sun>--<2018-06-16 Sat>
:PROPERTIES:
:ID:       HdnGavfQTVYAci_ItR-eQe4P@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Pelicans vs. Mudcats Pelicans vs. Mudcats

Follow on MiLB First Pitch  https //stza.co/+w0zb-G

Shop  https //stza.co/+w0zb-3G

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Pelicans vs. Mudcats
END:VALARM
DTSTART;VALUE=DATE:20180617
DTEND;VALUE=DATE:20180617
UID:HdnGavfQTVYAci_ItR-eQe4P@stanza.co
SUMMARY:Pelicans vs. Mudcats
DESCRIPTION:Pelicans vs. Mudcats\n\nFollow on MiLB First Pitch: https://stza.co/+w0zb-G\n\nShop: https://stza.co/+w0zb-3G\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Pelicans @ Hillcats
<2018-06-21 Thu 17:30-20:30>
:PROPERTIES:
:ID:       8OuHFoyTXTCmZwSaYvz22c2a@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Pelicans @ Hillcats Pelicans @ Hillcats

Buy tickets here  https //stza.co/~y3VS

Follow on MiLB First Pitch  https //stza.co/+y3VS-B

Shop  https //stza.co/+y3VS-2L

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Pelicans @ Hillcats
END:VALARM
DTSTART:20180621T223000Z
DTEND:20180622T013000Z
UID:8OuHFoyTXTCmZwSaYvz22c2a@stanza.co
SUMMARY:Pelicans @ Hillcats
DESCRIPTION:Pelicans @ Hillcats\n\nBuy tickets here: https://stza.co/~y3VS\n\nFollow on MiLB First Pitch: https://stza.co/+y3VS-B\n\nShop: https://stza.co/+y3VS-2L\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Pelicans @ Hillcats
<2018-06-22 Fri 17:30-20:30>
:PROPERTIES:
:ID:       uLWVtstrtOzO5BqyS2kifVEF@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Pelicans @ Hillcats Pelicans @ Hillcats

Buy tickets here  https //stza.co/~y3VT

Follow on MiLB First Pitch  https //stza.co/+y3VT-3g

Shop  https //stza.co/+y3VT-37

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Pelicans @ Hillcats
END:VALARM
DTSTART:20180622T223000Z
DTEND:20180623T013000Z
UID:uLWVtstrtOzO5BqyS2kifVEF@stanza.co
SUMMARY:Pelicans @ Hillcats
DESCRIPTION:Pelicans @ Hillcats\n\nBuy tickets here: https://stza.co/~y3VT\n\nFollow on MiLB First Pitch: https://stza.co/+y3VT-3g\n\nShop: https://stza.co/+y3VT-37\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Pelicans @ Hillcats
<2018-06-23 Sat 17:00-20:00>
:PROPERTIES:
:ID:       WM11Sp-kjLd11RxuF_hrgavh@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Pelicans @ Hillcats Pelicans @ Hillcats

Buy tickets here  https //stza.co/~y3VU

Follow on MiLB First Pitch  https //stza.co/+y3VU-d

Shop  https //stza.co/+y3VU-A

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Pelicans @ Hillcats
END:VALARM
DTSTART:20180623T220000Z
DTEND:20180624T010000Z
UID:WM11Sp-kjLd11RxuF_hrgavh@stanza.co
SUMMARY:Pelicans @ Hillcats
DESCRIPTION:Pelicans @ Hillcats\n\nBuy tickets here: https://stza.co/~y3VU\n\nFollow on MiLB First Pitch: https://stza.co/+y3VU-d\n\nShop: https://stza.co/+y3VU-A\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Pelicans @ Hillcats
<2018-06-24 Sun 16:00-19:00>
:PROPERTIES:
:ID:       GXSzogGSuuygvBtpMqWNWBbk@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Pelicans @ Hillcats Pelicans @ Hillcats

Buy tickets here  https //stza.co/~y3VV

Follow on MiLB First Pitch  https //stza.co/+y3VV-3J

Shop  https //stza.co/+y3VV-2h

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Pelicans @ Hillcats
END:VALARM
DTSTART:20180624T210000Z
DTEND:20180625T000000Z
UID:GXSzogGSuuygvBtpMqWNWBbk@stanza.co
SUMMARY:Pelicans @ Hillcats
DESCRIPTION:Pelicans @ Hillcats\n\nBuy tickets here: https://stza.co/~y3VV\n\nFollow on MiLB First Pitch: https://stza.co/+y3VV-3J\n\nShop: https://stza.co/+y3VV-2h\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Pelicans vs. Astros
<2018-06-25 Mon>--<2018-06-24 Sun>
:PROPERTIES:
:ID:       dfO0bxcLX8jqkfcfV_e1HLYc@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Pelicans vs. Astros Pelicans vs. Astros

Follow on MiLB First Pitch  https //stza.co/+w0zd-1d

Shop  https //stza.co/+w0zd-U

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Pelicans vs. Astros
END:VALARM
DTSTART;VALUE=DATE:20180625
DTEND;VALUE=DATE:20180625
UID:dfO0bxcLX8jqkfcfV_e1HLYc@stanza.co
SUMMARY:Pelicans vs. Astros
DESCRIPTION:Pelicans vs. Astros\n\nFollow on MiLB First Pitch: https://stza.co/+w0zd-1d\n\nShop: https://stza.co/+w0zd-U\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Pelicans vs. Astros
<2018-06-26 Tue>--<2018-06-25 Mon>
:PROPERTIES:
:ID:       YdGAQzoxkSZfllc0kWQXb30L@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Pelicans vs. Astros Pelicans vs. Astros

Follow on MiLB First Pitch  https //stza.co/+w0zf-2V

Shop  https //stza.co/+w0zf-o

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Pelicans vs. Astros
END:VALARM
DTSTART;VALUE=DATE:20180626
DTEND;VALUE=DATE:20180626
UID:YdGAQzoxkSZfllc0kWQXb30L@stanza.co
SUMMARY:Pelicans vs. Astros
DESCRIPTION:Pelicans vs. Astros\n\nFollow on MiLB First Pitch: https://stza.co/+w0zf-2V\n\nShop: https://stza.co/+w0zf-o\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Pelicans vs. Astros
<2018-06-27 Wed>--<2018-06-26 Tue>
:PROPERTIES:
:ID:       o9Y5zFLqYQpwUf20wlj2C2EQ@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Pelicans vs. Astros Pelicans vs. Astros

Follow on MiLB First Pitch  https //stza.co/+w0zh-c

Shop  https //stza.co/+w0zh-1R

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Pelicans vs. Astros
END:VALARM
DTSTART;VALUE=DATE:20180627
DTEND;VALUE=DATE:20180627
UID:o9Y5zFLqYQpwUf20wlj2C2EQ@stanza.co
SUMMARY:Pelicans vs. Astros
DESCRIPTION:Pelicans vs. Astros\n\nFollow on MiLB First Pitch: https://stza.co/+w0zh-c\n\nShop: https://stza.co/+w0zh-1R\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Pelicans vs. Astros
<2018-06-28 Thu>--<2018-06-27 Wed>
:PROPERTIES:
:ID:       rxM34E3RBppsK6oXusgjuFeS@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Pelicans vs. Astros Pelicans vs. Astros

Follow on MiLB First Pitch  https //stza.co/+w0zj-1G

Shop  https //stza.co/+w0zj-J

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Pelicans vs. Astros
END:VALARM
DTSTART;VALUE=DATE:20180628
DTEND;VALUE=DATE:20180628
UID:rxM34E3RBppsK6oXusgjuFeS@stanza.co
SUMMARY:Pelicans vs. Astros
DESCRIPTION:Pelicans vs. Astros\n\nFollow on MiLB First Pitch: https://stza.co/+w0zj-1G\n\nShop: https://stza.co/+w0zj-J\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Pelicans vs. Astros
<2018-06-29 Fri>--<2018-06-28 Thu>
:PROPERTIES:
:ID:       dS4UvRxEdyJjvbHit4SADZ_X@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Pelicans vs. Astros Pelicans vs. Astros

Follow on MiLB First Pitch  https //stza.co/+w0zk-1K

Shop  https //stza.co/+w0zk-3q

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Pelicans vs. Astros
END:VALARM
DTSTART;VALUE=DATE:20180629
DTEND;VALUE=DATE:20180629
UID:dS4UvRxEdyJjvbHit4SADZ_X@stanza.co
SUMMARY:Pelicans vs. Astros
DESCRIPTION:Pelicans vs. Astros\n\nFollow on MiLB First Pitch: https://stza.co/+w0zk-1K\n\nShop: https://stza.co/+w0zk-3q\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Pelicans vs. Nationals
<2018-06-30 Sat>--<2018-06-29 Fri>
:PROPERTIES:
:ID:       JAEnWXp3jb_OpDb6wqCh0akt@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Pelicans vs. Nationals Pelicans vs. Nationals

Follow on MiLB First Pitch  https //stza.co/+w0zn-1D

Shop  https //stza.co/+w0zn-2s

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Pelicans vs. Nationals
END:VALARM
DTSTART;VALUE=DATE:20180630
DTEND;VALUE=DATE:20180630
UID:JAEnWXp3jb_OpDb6wqCh0akt@stanza.co
SUMMARY:Pelicans vs. Nationals
DESCRIPTION:Pelicans vs. Nationals\n\nFollow on MiLB First Pitch: https://stza.co/+w0zn-1D\n\nShop: https://stza.co/+w0zn-2s\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Pelicans vs. Nationals
<2018-07-01 Sun>--<2018-06-30 Sat>
:PROPERTIES:
:ID:       THYn1lvPahz_lY1k_rpOTwFd@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Pelicans vs. Nationals Pelicans vs. Nationals

Follow on MiLB First Pitch  https //stza.co/+w0zp-h

Shop  https //stza.co/+w0zp-1y

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Pelicans vs. Nationals
END:VALARM
DTSTART;VALUE=DATE:20180701
DTEND;VALUE=DATE:20180701
UID:THYn1lvPahz_lY1k_rpOTwFd@stanza.co
SUMMARY:Pelicans vs. Nationals
DESCRIPTION:Pelicans vs. Nationals\n\nFollow on MiLB First Pitch: https://stza.co/+w0zp-h\n\nShop: https://stza.co/+w0zp-1y\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Pelicans vs. Nationals
<2018-07-02 Mon>--<2018-07-01 Sun>
:PROPERTIES:
:ID:       -TK2bBfh6HpkXEwgiP9ZVZCt@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Pelicans vs. Nationals Pelicans vs. Nationals

Follow on MiLB First Pitch  https //stza.co/+w0zq-2W

Shop  https //stza.co/+w0zq-y

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Pelicans vs. Nationals
END:VALARM
DTSTART;VALUE=DATE:20180702
DTEND;VALUE=DATE:20180702
UID:-TK2bBfh6HpkXEwgiP9ZVZCt@stanza.co
SUMMARY:Pelicans vs. Nationals
DESCRIPTION:Pelicans vs. Nationals\n\nFollow on MiLB First Pitch: https://stza.co/+w0zq-2W\n\nShop: https://stza.co/+w0zq-y\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Pelicans vs. Nationals
<2018-07-03 Tue>--<2018-07-02 Mon>
:PROPERTIES:
:ID:       gOglSKHYFu3FgdUV6PlNgYHu@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Pelicans vs. Nationals Pelicans vs. Nationals

Follow on MiLB First Pitch  https //stza.co/+w0zt-37

Shop  https //stza.co/+w0zt-2s

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Pelicans vs. Nationals
END:VALARM
DTSTART;VALUE=DATE:20180703
DTEND;VALUE=DATE:20180703
UID:gOglSKHYFu3FgdUV6PlNgYHu@stanza.co
SUMMARY:Pelicans vs. Nationals
DESCRIPTION:Pelicans vs. Nationals\n\nFollow on MiLB First Pitch: https://stza.co/+w0zt-37\n\nShop: https://stza.co/+w0zt-2s\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Pelicans @ Astros
<2018-07-04 Wed 18:00-21:00>
:PROPERTIES:
:ID:       C4C6WBjNlUTAixKW3vhO3wBx@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Pelicans @ Astros Pelicans @ Astros

Follow on MiLB First Pitch  https //stza.co/+xM9q-2p

Shop  https //stza.co/+xM9q-k

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Pelicans @ Astros
END:VALARM
DTSTART:20180704T230000Z
DTEND:20180705T020000Z
UID:C4C6WBjNlUTAixKW3vhO3wBx@stanza.co
SUMMARY:Pelicans @ Astros
DESCRIPTION:Pelicans @ Astros\n\nFollow on MiLB First Pitch: https://stza.co/+xM9q-2p\n\nShop: https://stza.co/+xM9q-k\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Pelicans @ Astros
<2018-07-05 Thu 18:00-21:00>
:PROPERTIES:
:ID:       3BLiUKwM81CuD8F19jMi54vn@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Pelicans @ Astros Pelicans @ Astros

Follow on MiLB First Pitch  https //stza.co/+xM9r-1a

Shop  https //stza.co/+xM9r-O

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Pelicans @ Astros
END:VALARM
DTSTART:20180705T230000Z
DTEND:20180706T020000Z
UID:3BLiUKwM81CuD8F19jMi54vn@stanza.co
SUMMARY:Pelicans @ Astros
DESCRIPTION:Pelicans @ Astros\n\nFollow on MiLB First Pitch: https://stza.co/+xM9r-1a\n\nShop: https://stza.co/+xM9r-O\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Pelicans @ Astros
<2018-07-06 Fri 18:00-21:00>
:PROPERTIES:
:ID:       UpRy4YWjaFrNDEXnSx9A6DA1@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Pelicans @ Astros Pelicans @ Astros

Follow on MiLB First Pitch  https //stza.co/+xM9s-35

Shop  https //stza.co/+xM9s-1v

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Pelicans @ Astros
END:VALARM
DTSTART:20180706T230000Z
DTEND:20180707T020000Z
UID:UpRy4YWjaFrNDEXnSx9A6DA1@stanza.co
SUMMARY:Pelicans @ Astros
DESCRIPTION:Pelicans @ Astros\n\nFollow on MiLB First Pitch: https://stza.co/+xM9s-35\n\nShop: https://stza.co/+xM9s-1v\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Pelicans @ Astros
<2018-07-07 Sat 17:00-20:00>
:PROPERTIES:
:ID:       33t2gcqpqBCMT3PwW4NeHOVf@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Pelicans @ Astros Pelicans @ Astros

Follow on MiLB First Pitch  https //stza.co/+xM9t-1A

Shop  https //stza.co/+xM9t-T

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Pelicans @ Astros
END:VALARM
DTSTART:20180707T220000Z
DTEND:20180708T010000Z
UID:33t2gcqpqBCMT3PwW4NeHOVf@stanza.co
SUMMARY:Pelicans @ Astros
DESCRIPTION:Pelicans @ Astros\n\nFollow on MiLB First Pitch: https://stza.co/+xM9t-1A\n\nShop: https://stza.co/+xM9t-T\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Pelicans @ Astros
<2018-07-08 Sun 13:00-16:00>
:PROPERTIES:
:ID:       8eNE7H98Cx6DuXKU2WkJWkHH@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Pelicans @ Astros Pelicans @ Astros

Follow on MiLB First Pitch  https //stza.co/+xM9u-m

Shop  https //stza.co/+xM9u-2z

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Pelicans @ Astros
END:VALARM
DTSTART:20180708T180000Z
DTEND:20180708T210000Z
UID:8eNE7H98Cx6DuXKU2WkJWkHH@stanza.co
SUMMARY:Pelicans @ Astros
DESCRIPTION:Pelicans @ Astros\n\nFollow on MiLB First Pitch: https://stza.co/+xM9u-m\n\nShop: https://stza.co/+xM9u-2z\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Pelicans vs. Mudcats
<2018-07-09 Mon>--<2018-07-08 Sun>
:PROPERTIES:
:ID:       cUI34BP1-ez8B586K0iqk_bv@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Pelicans vs. Mudcats Pelicans vs. Mudcats

Follow on MiLB First Pitch  https //stza.co/+w0zv-3k

Shop  https //stza.co/+w0zv-1T

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Pelicans vs. Mudcats
END:VALARM
DTSTART;VALUE=DATE:20180709
DTEND;VALUE=DATE:20180709
UID:cUI34BP1-ez8B586K0iqk_bv@stanza.co
SUMMARY:Pelicans vs. Mudcats
DESCRIPTION:Pelicans vs. Mudcats\n\nFollow on MiLB First Pitch: https://stza.co/+w0zv-3k\n\nShop: https://stza.co/+w0zv-1T\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Pelicans vs. Mudcats
<2018-07-10 Tue>--<2018-07-09 Mon>
:PROPERTIES:
:ID:       WEgBvPZkS1-RIUh0MJ28OOgZ@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Pelicans vs. Mudcats Pelicans vs. Mudcats

Follow on MiLB First Pitch  https //stza.co/+w0zw-2Q

Shop  https //stza.co/+w0zw-3A

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Pelicans vs. Mudcats
END:VALARM
DTSTART;VALUE=DATE:20180710
DTEND;VALUE=DATE:20180710
UID:WEgBvPZkS1-RIUh0MJ28OOgZ@stanza.co
SUMMARY:Pelicans vs. Mudcats
DESCRIPTION:Pelicans vs. Mudcats\n\nFollow on MiLB First Pitch: https://stza.co/+w0zw-2Q\n\nShop: https://stza.co/+w0zw-3A\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Pelicans vs. Mudcats
<2018-07-11 Wed>--<2018-07-10 Tue>
:PROPERTIES:
:ID:       SFD_iRX8aP4XtVruHmtQLUZh@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Pelicans vs. Mudcats Pelicans vs. Mudcats

Follow on MiLB First Pitch  https //stza.co/+w0zz-2d

Shop  https //stza.co/+w0zz-3t

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Pelicans vs. Mudcats
END:VALARM
DTSTART;VALUE=DATE:20180711
DTEND;VALUE=DATE:20180711
UID:SFD_iRX8aP4XtVruHmtQLUZh@stanza.co
SUMMARY:Pelicans vs. Mudcats
DESCRIPTION:Pelicans vs. Mudcats\n\nFollow on MiLB First Pitch: https://stza.co/+w0zz-2d\n\nShop: https://stza.co/+w0zz-3t\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Pelicans vs. Mudcats
<2018-07-12 Thu>--<2018-07-11 Wed>
:PROPERTIES:
:ID:       7kZ-CRNwXZ9IshAshg2fPhBQ@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Pelicans vs. Mudcats Pelicans vs. Mudcats

Follow on MiLB First Pitch  https //stza.co/+w0zA-1D

Shop  https //stza.co/+w0zA-1l

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Pelicans vs. Mudcats
END:VALARM
DTSTART;VALUE=DATE:20180712
DTEND;VALUE=DATE:20180712
UID:7kZ-CRNwXZ9IshAshg2fPhBQ@stanza.co
SUMMARY:Pelicans vs. Mudcats
DESCRIPTION:Pelicans vs. Mudcats\n\nFollow on MiLB First Pitch: https://stza.co/+w0zA-1D\n\nShop: https://stza.co/+w0zA-1l\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Pelicans @ Wood Ducks
<2018-07-13 Fri 18:00-21:00>
:PROPERTIES:
:ID:       ybu7nwmBzStGO8wlUUNTT9wT@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Pelicans @ Wood Ducks Pelicans @ Wood Ducks

Follow on MiLB First Pitch  https //stza.co/+w0xN-2x

Shop  https //stza.co/+w0xN-2K

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Pelicans @ Wood Ducks
END:VALARM
DTSTART:20180713T230000Z
DTEND:20180714T020000Z
UID:ybu7nwmBzStGO8wlUUNTT9wT@stanza.co
SUMMARY:Pelicans @ Wood Ducks
DESCRIPTION:Pelicans @ Wood Ducks\n\nFollow on MiLB First Pitch: https://stza.co/+w0xN-2x\n\nShop: https://stza.co/+w0xN-2K\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Pelicans @ Wood Ducks
<2018-07-14 Sat 17:00-20:00>
:PROPERTIES:
:ID:       oPn_vPQ6sV-737iCLIZumWH0@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Pelicans @ Wood Ducks Pelicans @ Wood Ducks

Follow on MiLB First Pitch  https //stza.co/+w0xO-2q

Shop  https //stza.co/+w0xO-25

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Pelicans @ Wood Ducks
END:VALARM
DTSTART:20180714T220000Z
DTEND:20180715T010000Z
UID:oPn_vPQ6sV-737iCLIZumWH0@stanza.co
SUMMARY:Pelicans @ Wood Ducks
DESCRIPTION:Pelicans @ Wood Ducks\n\nFollow on MiLB First Pitch: https://stza.co/+w0xO-2q\n\nShop: https://stza.co/+w0xO-25\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Pelicans @ Wood Ducks
<2018-07-15 Sun 15:00-18:00>
:PROPERTIES:
:ID:       9DerXzJpDZ-tXSRRchRvCMN0@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Pelicans @ Wood Ducks Pelicans @ Wood Ducks

Follow on MiLB First Pitch  https //stza.co/+w0xP-2G

Shop  https //stza.co/+w0xP-1S

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Pelicans @ Wood Ducks
END:VALARM
DTSTART:20180715T200000Z
DTEND:20180715T230000Z
UID:9DerXzJpDZ-tXSRRchRvCMN0@stanza.co
SUMMARY:Pelicans @ Wood Ducks
DESCRIPTION:Pelicans @ Wood Ducks\n\nFollow on MiLB First Pitch: https://stza.co/+w0xP-2G\n\nShop: https://stza.co/+w0xP-1S\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Pelicans @ Wood Ducks
<2018-07-16 Mon 18:00-21:00>
:PROPERTIES:
:ID:       d-u8-l0kHZji5pxGAtCMO9I2@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Pelicans @ Wood Ducks Pelicans @ Wood Ducks

Follow on MiLB First Pitch  https //stza.co/+w0xQ-1z

Shop  https //stza.co/+w0xQ-1v

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Pelicans @ Wood Ducks
END:VALARM
DTSTART:20180716T230000Z
DTEND:20180717T020000Z
UID:d-u8-l0kHZji5pxGAtCMO9I2@stanza.co
SUMMARY:Pelicans @ Wood Ducks
DESCRIPTION:Pelicans @ Wood Ducks\n\nFollow on MiLB First Pitch: https://stza.co/+w0xQ-1z\n\nShop: https://stza.co/+w0xQ-1v\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Pelicans vs. Nationals
<2018-07-18 Wed>--<2018-07-17 Tue>
:PROPERTIES:
:ID:       qGnkKtUEzcOQ9GVEpxFzOaLZ@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Pelicans vs. Nationals Pelicans vs. Nationals

Follow on MiLB First Pitch  https //stza.co/+w0zD-3U

Shop  https //stza.co/+w0zD-20

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Pelicans vs. Nationals
END:VALARM
DTSTART;VALUE=DATE:20180718
DTEND;VALUE=DATE:20180718
UID:qGnkKtUEzcOQ9GVEpxFzOaLZ@stanza.co
SUMMARY:Pelicans vs. Nationals
DESCRIPTION:Pelicans vs. Nationals\n\nFollow on MiLB First Pitch: https://stza.co/+w0zD-3U\n\nShop: https://stza.co/+w0zD-20\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Pelicans vs. Nationals
<2018-07-19 Thu>--<2018-07-18 Wed>
:PROPERTIES:
:ID:       9keEpWLbptxuU5NS9LzIJdMd@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Pelicans vs. Nationals Pelicans vs. Nationals

Follow on MiLB First Pitch  https //stza.co/+w0zF-36

Shop  https //stza.co/+w0zF-1v

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Pelicans vs. Nationals
END:VALARM
DTSTART;VALUE=DATE:20180719
DTEND;VALUE=DATE:20180719
UID:9keEpWLbptxuU5NS9LzIJdMd@stanza.co
SUMMARY:Pelicans vs. Nationals
DESCRIPTION:Pelicans vs. Nationals\n\nFollow on MiLB First Pitch: https://stza.co/+w0zF-36\n\nShop: https://stza.co/+w0zF-1v\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Pelicans vs. Nationals
<2018-07-20 Fri>--<2018-07-19 Thu>
:PROPERTIES:
:ID:       WH5Gn4BGzO3969dlL8cIzO6n@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Pelicans vs. Nationals Pelicans vs. Nationals

Follow on MiLB First Pitch  https //stza.co/+w0zH-2I

Shop  https //stza.co/+w0zH-2_

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Pelicans vs. Nationals
END:VALARM
DTSTART;VALUE=DATE:20180720
DTEND;VALUE=DATE:20180720
UID:WH5Gn4BGzO3969dlL8cIzO6n@stanza.co
SUMMARY:Pelicans vs. Nationals
DESCRIPTION:Pelicans vs. Nationals\n\nFollow on MiLB First Pitch: https://stza.co/+w0zH-2I\n\nShop: https://stza.co/+w0zH-2_\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Pelicans vs. Dash
<2018-07-21 Sat>--<2018-07-20 Fri>
:PROPERTIES:
:ID:       srBQxySmlX2xsrnAcYSSmXIF@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Pelicans vs. Dash Pelicans vs. Dash

Follow on MiLB First Pitch  https //stza.co/+w0zI-22

Shop  https //stza.co/+w0zI-3Y

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Pelicans vs. Dash
END:VALARM
DTSTART;VALUE=DATE:20180721
DTEND;VALUE=DATE:20180721
UID:srBQxySmlX2xsrnAcYSSmXIF@stanza.co
SUMMARY:Pelicans vs. Dash
DESCRIPTION:Pelicans vs. Dash\n\nFollow on MiLB First Pitch: https://stza.co/+w0zI-22\n\nShop: https://stza.co/+w0zI-3Y\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Pelicans vs. Dash
<2018-07-22 Sun>--<2018-07-21 Sat>
:PROPERTIES:
:ID:       hoTntYfaAhh0uFtcR4VbfX3x@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Pelicans vs. Dash Pelicans vs. Dash

Follow on MiLB First Pitch  https //stza.co/+w0zL-10

Shop  https //stza.co/+w0zL-3b

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Pelicans vs. Dash
END:VALARM
DTSTART;VALUE=DATE:20180722
DTEND;VALUE=DATE:20180722
UID:hoTntYfaAhh0uFtcR4VbfX3x@stanza.co
SUMMARY:Pelicans vs. Dash
DESCRIPTION:Pelicans vs. Dash\n\nFollow on MiLB First Pitch: https://stza.co/+w0zL-10\n\nShop: https://stza.co/+w0zL-3b\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Pelicans vs. Dash
<2018-07-23 Mon>--<2018-07-22 Sun>
:PROPERTIES:
:ID:       Soo0eS4u-fcJyIwCT0ZUpDjF@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Pelicans vs. Dash Pelicans vs. Dash

Follow on MiLB First Pitch  https //stza.co/+w0zN-37

Shop  https //stza.co/+w0zN-32

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Pelicans vs. Dash
END:VALARM
DTSTART;VALUE=DATE:20180723
DTEND;VALUE=DATE:20180723
UID:Soo0eS4u-fcJyIwCT0ZUpDjF@stanza.co
SUMMARY:Pelicans vs. Dash
DESCRIPTION:Pelicans vs. Dash\n\nFollow on MiLB First Pitch: https://stza.co/+w0zN-37\n\nShop: https://stza.co/+w0zN-32\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Pelicans @ Mudcats
<2018-07-24 Tue 18:00-21:00>
:PROPERTIES:
:ID:       Fqk7mojnLpchbVmdHZsi0YOh@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Pelicans @ Mudcats Pelicans @ Mudcats

Buy tickets here  https //stza.co/~w0xD

Follow on MiLB First Pitch  https //stza.co/+w0xD-1u

Shop  https //stza.co/+w0xD-3Y

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Pelicans @ Mudcats
END:VALARM
DTSTART:20180724T230000Z
DTEND:20180725T020000Z
UID:Fqk7mojnLpchbVmdHZsi0YOh@stanza.co
SUMMARY:Pelicans @ Mudcats
DESCRIPTION:Pelicans @ Mudcats\n\nBuy tickets here: https://stza.co/~w0xD\n\nFollow on MiLB First Pitch: https://stza.co/+w0xD-1u\n\nShop: https://stza.co/+w0xD-3Y\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Pelicans @ Mudcats
<2018-07-25 Wed 10:00-13:00>
:PROPERTIES:
:ID:       NPpvBDeq2BJaSD6jGBP-ziTd@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Pelicans @ Mudcats Pelicans @ Mudcats

Buy tickets here  https //stza.co/~w0xE

Follow on MiLB First Pitch  https //stza.co/+w0xE-1U

Shop  https //stza.co/+w0xE-3z

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Pelicans @ Mudcats
END:VALARM
DTSTART:20180725T150000Z
DTEND:20180725T180000Z
UID:NPpvBDeq2BJaSD6jGBP-ziTd@stanza.co
SUMMARY:Pelicans @ Mudcats
DESCRIPTION:Pelicans @ Mudcats\n\nBuy tickets here: https://stza.co/~w0xE\n\nFollow on MiLB First Pitch: https://stza.co/+w0xE-1U\n\nShop: https://stza.co/+w0xE-3z\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Pelicans @ Mudcats
<2018-07-26 Thu 18:00-21:00>
:PROPERTIES:
:ID:       SolcF3VAZomURl8TA23pqiYq@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Pelicans @ Mudcats Pelicans @ Mudcats

Buy tickets here  https //stza.co/~w0xF

Follow on MiLB First Pitch  https //stza.co/+w0xF-2l

Shop  https //stza.co/+w0xF-K

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Pelicans @ Mudcats
END:VALARM
DTSTART:20180726T230000Z
DTEND:20180727T020000Z
UID:SolcF3VAZomURl8TA23pqiYq@stanza.co
SUMMARY:Pelicans @ Mudcats
DESCRIPTION:Pelicans @ Mudcats\n\nBuy tickets here: https://stza.co/~w0xF\n\nFollow on MiLB First Pitch: https://stza.co/+w0xF-2l\n\nShop: https://stza.co/+w0xF-K\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Pelicans vs. Hillcats
<2018-07-27 Fri>--<2018-07-26 Thu>
:PROPERTIES:
:ID:       3TZfyDZh2xA-6Kp0TXcEQsqe@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Pelicans vs. Hillcats Pelicans vs. Hillcats

Follow on MiLB First Pitch  https //stza.co/+w0zO-t

Shop  https //stza.co/+w0zO-q

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Pelicans vs. Hillcats
END:VALARM
DTSTART;VALUE=DATE:20180727
DTEND;VALUE=DATE:20180727
UID:3TZfyDZh2xA-6Kp0TXcEQsqe@stanza.co
SUMMARY:Pelicans vs. Hillcats
DESCRIPTION:Pelicans vs. Hillcats\n\nFollow on MiLB First Pitch: https://stza.co/+w0zO-t\n\nShop: https://stza.co/+w0zO-q\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Pelicans vs. Hillcats
<2018-07-28 Sat>--<2018-07-27 Fri>
:PROPERTIES:
:ID:       wBng_s-J3KWuxdD9LH-qWn04@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Pelicans vs. Hillcats Pelicans vs. Hillcats

Follow on MiLB First Pitch  https //stza.co/+w0zR-13

Shop  https //stza.co/+w0zR-3e

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Pelicans vs. Hillcats
END:VALARM
DTSTART;VALUE=DATE:20180728
DTEND;VALUE=DATE:20180728
UID:wBng_s-J3KWuxdD9LH-qWn04@stanza.co
SUMMARY:Pelicans vs. Hillcats
DESCRIPTION:Pelicans vs. Hillcats\n\nFollow on MiLB First Pitch: https://stza.co/+w0zR-13\n\nShop: https://stza.co/+w0zR-3e\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Pelicans vs. Hillcats
<2018-07-29 Sun>--<2018-07-28 Sat>
:PROPERTIES:
:ID:       0wUhQH75OMH5XdaFlhJ416QK@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Pelicans vs. Hillcats Pelicans vs. Hillcats

Follow on MiLB First Pitch  https //stza.co/+w0zS-28

Shop  https //stza.co/+w0zS-1H

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Pelicans vs. Hillcats
END:VALARM
DTSTART;VALUE=DATE:20180729
DTEND;VALUE=DATE:20180729
UID:0wUhQH75OMH5XdaFlhJ416QK@stanza.co
SUMMARY:Pelicans vs. Hillcats
DESCRIPTION:Pelicans vs. Hillcats\n\nFollow on MiLB First Pitch: https://stza.co/+w0zS-28\n\nShop: https://stza.co/+w0zS-1H\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Pelicans vs. Wood Ducks
<2018-07-31 Tue>--<2018-07-30 Mon>
:PROPERTIES:
:ID:       xq96GC5-lQdoX6WdjhTwWvjp@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Pelicans vs. Wood Ducks Pelicans vs. Wood Ducks

Follow on MiLB First Pitch  https //stza.co/+w0zV-2W

Shop  https //stza.co/+w0zV-$

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Pelicans vs. Wood Ducks
END:VALARM
DTSTART;VALUE=DATE:20180731
DTEND;VALUE=DATE:20180731
UID:xq96GC5-lQdoX6WdjhTwWvjp@stanza.co
SUMMARY:Pelicans vs. Wood Ducks
DESCRIPTION:Pelicans vs. Wood Ducks\n\nFollow on MiLB First Pitch: https://stza.co/+w0zV-2W\n\nShop: https://stza.co/+w0zV-$\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Pelicans vs. Wood Ducks
<2018-08-01 Wed>--<2018-07-31 Tue>
:PROPERTIES:
:ID:       lP1Rq2HkdwU9LltVzXbWgJYG@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Pelicans vs. Wood Ducks Pelicans vs. Wood Ducks

Follow on MiLB First Pitch  https //stza.co/+w0zX-3k

Shop  https //stza.co/+w0zX-2N

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Pelicans vs. Wood Ducks
END:VALARM
DTSTART;VALUE=DATE:20180801
DTEND;VALUE=DATE:20180801
UID:lP1Rq2HkdwU9LltVzXbWgJYG@stanza.co
SUMMARY:Pelicans vs. Wood Ducks
DESCRIPTION:Pelicans vs. Wood Ducks\n\nFollow on MiLB First Pitch: https://stza.co/+w0zX-3k\n\nShop: https://stza.co/+w0zX-2N\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Pelicans vs. Wood Ducks
<2018-08-02 Thu>--<2018-08-01 Wed>
:PROPERTIES:
:ID:       u6a7ZpOgXUewlF7mvstbIFQn@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Pelicans vs. Wood Ducks Pelicans vs. Wood Ducks

Follow on MiLB First Pitch  https //stza.co/+w0zZ-3o

Shop  https //stza.co/+w0zZ-1_

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Pelicans vs. Wood Ducks
END:VALARM
DTSTART;VALUE=DATE:20180802
DTEND;VALUE=DATE:20180802
UID:u6a7ZpOgXUewlF7mvstbIFQn@stanza.co
SUMMARY:Pelicans vs. Wood Ducks
DESCRIPTION:Pelicans vs. Wood Ducks\n\nFollow on MiLB First Pitch: https://stza.co/+w0zZ-3o\n\nShop: https://stza.co/+w0zZ-1_\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Pelicans @ Nationals
<2018-08-03 Fri 18:05-21:05>
:PROPERTIES:
:ID:       T7L6l0xUQ-VcODCRMzX9qMJF@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Pelicans @ Nationals Pelicans @ Nationals

Follow on MiLB First Pitch  https //stza.co/+xB5b-h

Shop  https //stza.co/+xB5b-3x

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Pelicans @ Nationals
END:VALARM
DTSTART:20180803T230500Z
DTEND:20180804T020500Z
UID:T7L6l0xUQ-VcODCRMzX9qMJF@stanza.co
SUMMARY:Pelicans @ Nationals
DESCRIPTION:Pelicans @ Nationals\n\nFollow on MiLB First Pitch: https://stza.co/+xB5b-h\n\nShop: https://stza.co/+xB5b-3x\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Pelicans @ Nationals
<2018-08-04 Sat 17:35-20:35>
:PROPERTIES:
:ID:       dmOf5--qQpJ3UDpi-Y3DMdyx@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Pelicans @ Nationals Pelicans @ Nationals

Follow on MiLB First Pitch  https //stza.co/+xB5c-2E

Shop  https //stza.co/+xB5c-2A

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Pelicans @ Nationals
END:VALARM
DTSTART:20180804T223500Z
DTEND:20180805T013500Z
UID:dmOf5--qQpJ3UDpi-Y3DMdyx@stanza.co
SUMMARY:Pelicans @ Nationals
DESCRIPTION:Pelicans @ Nationals\n\nFollow on MiLB First Pitch: https://stza.co/+xB5c-2E\n\nShop: https://stza.co/+xB5c-2A\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Pelicans @ Nationals
<2018-08-05 Sun 12:05-15:05>
:PROPERTIES:
:ID:       lw_BnQ81jeQBQ39SkJxvh6iu@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Pelicans @ Nationals Pelicans @ Nationals

Follow on MiLB First Pitch  https //stza.co/+xB5d-2U

Shop  https //stza.co/+xB5d-20

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Pelicans @ Nationals
END:VALARM
DTSTART:20180805T170500Z
DTEND:20180805T200500Z
UID:lw_BnQ81jeQBQ39SkJxvh6iu@stanza.co
SUMMARY:Pelicans @ Nationals
DESCRIPTION:Pelicans @ Nationals\n\nFollow on MiLB First Pitch: https://stza.co/+xB5d-2U\n\nShop: https://stza.co/+xB5d-20\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Pelicans @ Dash
<2018-08-06 Mon 18:00-21:00>
:PROPERTIES:
:ID:       C_tE_xyDfbq2K1BNzINYNirg@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Pelicans @ Dash Pelicans @ Dash

Buy tickets here  https //stza.co/~w0Ax

Follow on MiLB First Pitch  https //stza.co/+w0Ax-m

Shop  https //stza.co/+w0Ax-32

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Pelicans @ Dash
END:VALARM
DTSTART:20180806T230000Z
DTEND:20180807T020000Z
UID:C_tE_xyDfbq2K1BNzINYNirg@stanza.co
SUMMARY:Pelicans @ Dash
DESCRIPTION:Pelicans @ Dash\n\nBuy tickets here: https://stza.co/~w0Ax\n\nFollow on MiLB First Pitch: https://stza.co/+w0Ax-m\n\nShop: https://stza.co/+w0Ax-32\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Pelicans @ Dash
<2018-08-07 Tue 18:00-21:00>
:PROPERTIES:
:ID:       pX0TYNeNDkOs8fG5SBTJE9nA@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Pelicans @ Dash Pelicans @ Dash

Buy tickets here  https //stza.co/~w0Ay

Follow on MiLB First Pitch  https //stza.co/+w0Ay-1n

Shop  https //stza.co/+w0Ay-y

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Pelicans @ Dash
END:VALARM
DTSTART:20180807T230000Z
DTEND:20180808T020000Z
UID:pX0TYNeNDkOs8fG5SBTJE9nA@stanza.co
SUMMARY:Pelicans @ Dash
DESCRIPTION:Pelicans @ Dash\n\nBuy tickets here: https://stza.co/~w0Ay\n\nFollow on MiLB First Pitch: https://stza.co/+w0Ay-1n\n\nShop: https://stza.co/+w0Ay-y\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Pelicans @ Dash
<2018-08-08 Wed 18:00-21:00>
:PROPERTIES:
:ID:       3n4xkqb6viTl09ZunOWK2ZJe@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Pelicans @ Dash Pelicans @ Dash

Buy tickets here  https //stza.co/~w0Az

Follow on MiLB First Pitch  https //stza.co/+w0Az-2f

Shop  https //stza.co/+w0Az-2$

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Pelicans @ Dash
END:VALARM
DTSTART:20180808T230000Z
DTEND:20180809T020000Z
UID:3n4xkqb6viTl09ZunOWK2ZJe@stanza.co
SUMMARY:Pelicans @ Dash
DESCRIPTION:Pelicans @ Dash\n\nBuy tickets here: https://stza.co/~w0Az\n\nFollow on MiLB First Pitch: https://stza.co/+w0Az-2f\n\nShop: https://stza.co/+w0Az-2$\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Pelicans vs. Blue Rocks
<2018-08-10 Fri>--<2018-08-09 Thu>
:PROPERTIES:
:ID:       rb5b5HD0o9OoQzOVE0LDGZ2U@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Pelicans vs. Blue Rocks Pelicans vs. Blue Rocks

Follow on MiLB First Pitch  https //stza.co/+w0z$-25

Shop  https //stza.co/+w0z$-A

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Pelicans vs. Blue Rocks
END:VALARM
DTSTART;VALUE=DATE:20180810
DTEND;VALUE=DATE:20180810
UID:rb5b5HD0o9OoQzOVE0LDGZ2U@stanza.co
SUMMARY:Pelicans vs. Blue Rocks
DESCRIPTION:Pelicans vs. Blue Rocks\n\nFollow on MiLB First Pitch: https://stza.co/+w0z$-25\n\nShop: https://stza.co/+w0z$-A\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Pelicans vs. Blue Rocks
<2018-08-11 Sat>--<2018-08-10 Fri>
:PROPERTIES:
:ID:       hs1dOJbU-HIvjiGpFpng7Umj@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Pelicans vs. Blue Rocks Pelicans vs. Blue Rocks

Follow on MiLB First Pitch  https //stza.co/+w0A1-1L

Shop  https //stza.co/+w0A1-3v

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Pelicans vs. Blue Rocks
END:VALARM
DTSTART;VALUE=DATE:20180811
DTEND;VALUE=DATE:20180811
UID:hs1dOJbU-HIvjiGpFpng7Umj@stanza.co
SUMMARY:Pelicans vs. Blue Rocks
DESCRIPTION:Pelicans vs. Blue Rocks\n\nFollow on MiLB First Pitch: https://stza.co/+w0A1-1L\n\nShop: https://stza.co/+w0A1-3v\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Pelicans vs. Blue Rocks
<2018-08-12 Sun>--<2018-08-11 Sat>
:PROPERTIES:
:ID:       HWKDsmg64kjLlQFD2KalQ3ei@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Pelicans vs. Blue Rocks Pelicans vs. Blue Rocks

Follow on MiLB First Pitch  https //stza.co/+w0A2-1H

Shop  https //stza.co/+w0A2-1O

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Pelicans vs. Blue Rocks
END:VALARM
DTSTART;VALUE=DATE:20180812
DTEND;VALUE=DATE:20180812
UID:HWKDsmg64kjLlQFD2KalQ3ei@stanza.co
SUMMARY:Pelicans vs. Blue Rocks
DESCRIPTION:Pelicans vs. Blue Rocks\n\nFollow on MiLB First Pitch: https://stza.co/+w0A2-1H\n\nShop: https://stza.co/+w0A2-1O\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Pelicans @ Nationals
<2018-08-14 Tue 18:05-21:05>
:PROPERTIES:
:ID:       1IRm1ELday9ODZBeGecWU82R@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Pelicans @ Nationals Pelicans @ Nationals

Follow on MiLB First Pitch  https //stza.co/+xB5f-9

Shop  https //stza.co/+xB5f-2Q

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Pelicans @ Nationals
END:VALARM
DTSTART:20180814T230500Z
DTEND:20180815T020500Z
UID:1IRm1ELday9ODZBeGecWU82R@stanza.co
SUMMARY:Pelicans @ Nationals
DESCRIPTION:Pelicans @ Nationals\n\nFollow on MiLB First Pitch: https://stza.co/+xB5f-9\n\nShop: https://stza.co/+xB5f-2Q\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Pelicans @ Nationals
<2018-08-15 Wed 18:05-21:05>
:PROPERTIES:
:ID:       SfvSI7Chm3kfmcxfKbB3e0re@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Pelicans @ Nationals Pelicans @ Nationals

Follow on MiLB First Pitch  https //stza.co/+xB5g-1G

Shop  https //stza.co/+xB5g-35

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Pelicans @ Nationals
END:VALARM
DTSTART:20180815T230500Z
DTEND:20180816T020500Z
UID:SfvSI7Chm3kfmcxfKbB3e0re@stanza.co
SUMMARY:Pelicans @ Nationals
DESCRIPTION:Pelicans @ Nationals\n\nFollow on MiLB First Pitch: https://stza.co/+xB5g-1G\n\nShop: https://stza.co/+xB5g-35\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Pelicans @ Nationals
<2018-08-16 Thu 11:05-14:05>
:PROPERTIES:
:ID:       lCCDFGca6q1zzm7PZJBgbG2G@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Pelicans @ Nationals Pelicans @ Nationals

Follow on MiLB First Pitch  https //stza.co/+xB5i-5

Shop  https //stza.co/+xB5i-3t

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Pelicans @ Nationals
END:VALARM
DTSTART:20180816T160500Z
DTEND:20180816T190500Z
UID:lCCDFGca6q1zzm7PZJBgbG2G@stanza.co
SUMMARY:Pelicans @ Nationals
DESCRIPTION:Pelicans @ Nationals\n\nFollow on MiLB First Pitch: https://stza.co/+xB5i-5\n\nShop: https://stza.co/+xB5i-3t\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Pelicans vs. Astros
<2018-08-17 Fri>--<2018-08-16 Thu>
:PROPERTIES:
:ID:       X9IRpZPuG31iJpSqQ8dLDr54@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Pelicans vs. Astros Pelicans vs. Astros

Follow on MiLB First Pitch  https //stza.co/+w0A5-1m

Shop  https //stza.co/+w0A5-2K

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Pelicans vs. Astros
END:VALARM
DTSTART;VALUE=DATE:20180817
DTEND;VALUE=DATE:20180817
UID:X9IRpZPuG31iJpSqQ8dLDr54@stanza.co
SUMMARY:Pelicans vs. Astros
DESCRIPTION:Pelicans vs. Astros\n\nFollow on MiLB First Pitch: https://stza.co/+w0A5-1m\n\nShop: https://stza.co/+w0A5-2K\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Pelicans vs. Astros
<2018-08-18 Sat>--<2018-08-17 Fri>
:PROPERTIES:
:ID:       ztwLecaqkO69QMxxlDUHaq3Q@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Pelicans vs. Astros Pelicans vs. Astros

Follow on MiLB First Pitch  https //stza.co/+w0A7-2f

Shop  https //stza.co/+w0A7-B

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Pelicans vs. Astros
END:VALARM
DTSTART;VALUE=DATE:20180818
DTEND;VALUE=DATE:20180818
UID:ztwLecaqkO69QMxxlDUHaq3Q@stanza.co
SUMMARY:Pelicans vs. Astros
DESCRIPTION:Pelicans vs. Astros\n\nFollow on MiLB First Pitch: https://stza.co/+w0A7-2f\n\nShop: https://stza.co/+w0A7-B\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Pelicans vs. Astros
<2018-08-19 Sun>--<2018-08-18 Sat>
:PROPERTIES:
:ID:       zJqg9z75fVTWybOzs1AZJmxA@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Pelicans vs. Astros Pelicans vs. Astros

Follow on MiLB First Pitch  https //stza.co/+w0A9-3l

Shop  https //stza.co/+w0A9-3T

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Pelicans vs. Astros
END:VALARM
DTSTART;VALUE=DATE:20180819
DTEND;VALUE=DATE:20180819
UID:zJqg9z75fVTWybOzs1AZJmxA@stanza.co
SUMMARY:Pelicans vs. Astros
DESCRIPTION:Pelicans vs. Astros\n\nFollow on MiLB First Pitch: https://stza.co/+w0A9-3l\n\nShop: https://stza.co/+w0A9-3T\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Pelicans @ Dash
<2018-08-21 Tue 18:00-21:00>
:PROPERTIES:
:ID:       KnA66oZx8ViJGMeySwqZVoC-@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Pelicans @ Dash Pelicans @ Dash

Buy tickets here  https //stza.co/~w0AA

Follow on MiLB First Pitch  https //stza.co/+w0AA-1_

Shop  https //stza.co/+w0AA-2A

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Pelicans @ Dash
END:VALARM
DTSTART:20180821T230000Z
DTEND:20180822T020000Z
UID:KnA66oZx8ViJGMeySwqZVoC-@stanza.co
SUMMARY:Pelicans @ Dash
DESCRIPTION:Pelicans @ Dash\n\nBuy tickets here: https://stza.co/~w0AA\n\nFollow on MiLB First Pitch: https://stza.co/+w0AA-1_\n\nShop: https://stza.co/+w0AA-2A\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Pelicans @ Dash
<2018-08-22 Wed 18:00-21:00>
:PROPERTIES:
:ID:       paj6vgmxcXvGD1fC9T6MHLTc@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Pelicans @ Dash Pelicans @ Dash

Buy tickets here  https //stza.co/~w0AB

Follow on MiLB First Pitch  https //stza.co/+w0AB-2Y

Shop  https //stza.co/+w0AB-3e

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Pelicans @ Dash
END:VALARM
DTSTART:20180822T230000Z
DTEND:20180823T020000Z
UID:paj6vgmxcXvGD1fC9T6MHLTc@stanza.co
SUMMARY:Pelicans @ Dash
DESCRIPTION:Pelicans @ Dash\n\nBuy tickets here: https://stza.co/~w0AB\n\nFollow on MiLB First Pitch: https://stza.co/+w0AB-2Y\n\nShop: https://stza.co/+w0AB-3e\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Pelicans @ Dash
<2018-08-23 Thu 18:00-21:00>
:PROPERTIES:
:ID:       _ZUcpQy4Re2I9qhKwtBB1epy@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Pelicans @ Dash Pelicans @ Dash

Buy tickets here  https //stza.co/~w0AC

Follow on MiLB First Pitch  https //stza.co/+w0AC-2J

Shop  https //stza.co/+w0AC-18

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Pelicans @ Dash
END:VALARM
DTSTART:20180823T230000Z
DTEND:20180824T020000Z
UID:_ZUcpQy4Re2I9qhKwtBB1epy@stanza.co
SUMMARY:Pelicans @ Dash
DESCRIPTION:Pelicans @ Dash\n\nBuy tickets here: https://stza.co/~w0AC\n\nFollow on MiLB First Pitch: https://stza.co/+w0AC-2J\n\nShop: https://stza.co/+w0AC-18\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Pelicans @ Wood Ducks
<2018-08-24 Fri 18:00-21:00>
:PROPERTIES:
:ID:       Yz6PUuje2qWACseVzTbf_xK9@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Pelicans @ Wood Ducks Pelicans @ Wood Ducks

Follow on MiLB First Pitch  https //stza.co/+w0xR-2v

Shop  https //stza.co/+w0xR-2P

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Pelicans @ Wood Ducks
END:VALARM
DTSTART:20180824T230000Z
DTEND:20180825T020000Z
UID:Yz6PUuje2qWACseVzTbf_xK9@stanza.co
SUMMARY:Pelicans @ Wood Ducks
DESCRIPTION:Pelicans @ Wood Ducks\n\nFollow on MiLB First Pitch: https://stza.co/+w0xR-2v\n\nShop: https://stza.co/+w0xR-2P\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Pelicans @ Wood Ducks
<2018-08-25 Sat 17:00-20:00>
:PROPERTIES:
:ID:       DMSpdYFSvVsHHCgdJpKenX_U@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Pelicans @ Wood Ducks Pelicans @ Wood Ducks

Follow on MiLB First Pitch  https //stza.co/+w0xS-3w

Shop  https //stza.co/+w0xS-S

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Pelicans @ Wood Ducks
END:VALARM
DTSTART:20180825T220000Z
DTEND:20180826T010000Z
UID:DMSpdYFSvVsHHCgdJpKenX_U@stanza.co
SUMMARY:Pelicans @ Wood Ducks
DESCRIPTION:Pelicans @ Wood Ducks\n\nFollow on MiLB First Pitch: https://stza.co/+w0xS-3w\n\nShop: https://stza.co/+w0xS-S\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Pelicans @ Wood Ducks
<2018-08-26 Sun 13:00-16:00>
:PROPERTIES:
:ID:       OCaF1N3dY0MiFuKCOurrft3Z@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Pelicans @ Wood Ducks Pelicans @ Wood Ducks

Follow on MiLB First Pitch  https //stza.co/+w0xT-2L

Shop  https //stza.co/+w0xT-3v

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Pelicans @ Wood Ducks
END:VALARM
DTSTART:20180826T180000Z
DTEND:20180826T210000Z
UID:OCaF1N3dY0MiFuKCOurrft3Z@stanza.co
SUMMARY:Pelicans @ Wood Ducks
DESCRIPTION:Pelicans @ Wood Ducks\n\nFollow on MiLB First Pitch: https://stza.co/+w0xT-2L\n\nShop: https://stza.co/+w0xT-3v\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Pelicans vs. Astros
<2018-08-27 Mon>--<2018-08-26 Sun>
:PROPERTIES:
:ID:       ShMtjjIHkdHVYpPPi1nTClKM@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Pelicans vs. Astros Pelicans vs. Astros

Follow on MiLB First Pitch  https //stza.co/+w0Ab-O

Shop  https //stza.co/+w0Ab-1A

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Pelicans vs. Astros
END:VALARM
DTSTART;VALUE=DATE:20180827
DTEND;VALUE=DATE:20180827
UID:ShMtjjIHkdHVYpPPi1nTClKM@stanza.co
SUMMARY:Pelicans vs. Astros
DESCRIPTION:Pelicans vs. Astros\n\nFollow on MiLB First Pitch: https://stza.co/+w0Ab-O\n\nShop: https://stza.co/+w0Ab-1A\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Pelicans vs. Astros
<2018-08-28 Tue>--<2018-08-27 Mon>
:PROPERTIES:
:ID:       h8QhLv8Lcv40G4qslEh3zZAz@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Pelicans vs. Astros Pelicans vs. Astros

Follow on MiLB First Pitch  https //stza.co/+w0Ac-3y

Shop  https //stza.co/+w0Ac-2O

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Pelicans vs. Astros
END:VALARM
DTSTART;VALUE=DATE:20180828
DTEND;VALUE=DATE:20180828
UID:h8QhLv8Lcv40G4qslEh3zZAz@stanza.co
SUMMARY:Pelicans vs. Astros
DESCRIPTION:Pelicans vs. Astros\n\nFollow on MiLB First Pitch: https://stza.co/+w0Ac-3y\n\nShop: https://stza.co/+w0Ac-2O\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Pelicans vs. Astros
<2018-08-29 Wed>--<2018-08-28 Tue>
:PROPERTIES:
:ID:       caR_8Orr26GsoNmtV2fkFDGL@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Pelicans vs. Astros Pelicans vs. Astros

Follow on MiLB First Pitch  https //stza.co/+w0Af-p

Shop  https //stza.co/+w0Af-2Q

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Pelicans vs. Astros
END:VALARM
DTSTART;VALUE=DATE:20180829
DTEND;VALUE=DATE:20180829
UID:caR_8Orr26GsoNmtV2fkFDGL@stanza.co
SUMMARY:Pelicans vs. Astros
DESCRIPTION:Pelicans vs. Astros\n\nFollow on MiLB First Pitch: https://stza.co/+w0Af-p\n\nShop: https://stza.co/+w0Af-2Q\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Pelicans vs. Astros
<2018-08-30 Thu>--<2018-08-29 Wed>
:PROPERTIES:
:ID:       p64IIMY0B0g3f9eeuQt0bGSj@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Pelicans vs. Astros Pelicans vs. Astros

Follow on MiLB First Pitch  https //stza.co/+w0Ah-1C

Shop  https //stza.co/+w0Ah-30

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Pelicans vs. Astros
END:VALARM
DTSTART;VALUE=DATE:20180830
DTEND;VALUE=DATE:20180830
UID:p64IIMY0B0g3f9eeuQt0bGSj@stanza.co
SUMMARY:Pelicans vs. Astros
DESCRIPTION:Pelicans vs. Astros\n\nFollow on MiLB First Pitch: https://stza.co/+w0Ah-1C\n\nShop: https://stza.co/+w0Ah-30\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Pelicans @ Keys
<2018-08-31 Fri 18:00-21:00>
:PROPERTIES:
:ID:       1LYGS08eEPrW_a3tF2Us6eaO@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Pelicans @ Keys Pelicans @ Keys

Follow on MiLB First Pitch  https //stza.co/+wiah-30

Shop  https //stza.co/+wiah-2L

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Pelicans @ Keys
END:VALARM
DTSTART:20180831T230000Z
DTEND:20180901T020000Z
UID:1LYGS08eEPrW_a3tF2Us6eaO@stanza.co
SUMMARY:Pelicans @ Keys
DESCRIPTION:Pelicans @ Keys\n\nFollow on MiLB First Pitch: https://stza.co/+wiah-30\n\nShop: https://stza.co/+wiah-2L\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Pelicans @ Keys
<2018-09-01 Sat 17:00-20:00>
:PROPERTIES:
:ID:       v3ZoAKGmNBTO5jO-KOLmu1N7@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Pelicans @ Keys Pelicans @ Keys

Follow on MiLB First Pitch  https //stza.co/+wiai-2G

Shop  https //stza.co/+wiai-3V

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Pelicans @ Keys
END:VALARM
DTSTART:20180901T220000Z
DTEND:20180902T010000Z
UID:v3ZoAKGmNBTO5jO-KOLmu1N7@stanza.co
SUMMARY:Pelicans @ Keys
DESCRIPTION:Pelicans @ Keys\n\nFollow on MiLB First Pitch: https://stza.co/+wiai-2G\n\nShop: https://stza.co/+wiai-3V\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Pelicans @ Keys
<2018-09-02 Sun 17:00-20:00>
:PROPERTIES:
:ID:       BVbSPRE6b_mHQQxl7L7cxjv_@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Pelicans @ Keys Pelicans @ Keys

Follow on MiLB First Pitch  https //stza.co/+wiaj-39

Shop  https //stza.co/+wiaj-3A

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Pelicans @ Keys
END:VALARM
DTSTART:20180902T220000Z
DTEND:20180903T010000Z
UID:BVbSPRE6b_mHQQxl7L7cxjv_@stanza.co
SUMMARY:Pelicans @ Keys
DESCRIPTION:Pelicans @ Keys\n\nFollow on MiLB First Pitch: https://stza.co/+wiaj-39\n\nShop: https://stza.co/+wiaj-3A\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Pelicans @ Keys
<2018-09-03 Mon 13:00-16:00>
:PROPERTIES:
:ID:       zLFz87JNMEd4stSQD7jEBsBo@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Pelicans @ Keys Pelicans @ Keys

Follow on MiLB First Pitch  https //stza.co/+wiak-S

Shop  https //stza.co/+wiak-g

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Pelicans @ Keys
END:VALARM
DTSTART:20180903T180000Z
DTEND:20180903T210000Z
UID:zLFz87JNMEd4stSQD7jEBsBo@stanza.co
SUMMARY:Pelicans @ Keys
DESCRIPTION:Pelicans @ Keys\n\nFollow on MiLB First Pitch: https://stza.co/+wiak-S\n\nShop: https://stza.co/+wiak-g\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
