#+TITLE:       Main Google calendar entries
#+AUTHOR:      Eric S Fraga
#+EMAIL:       e.fraga@ucl.ac.uk
#+DESCRIPTION: converted using the ical2org awk script
#+CATEGORY:    google
#+STARTUP:     hidestars
#+STARTUP:     overview

* COMMENT original iCal preamble

* Hooks @ Naturals
<2018-04-05 Thu 18:25-21:25>
:PROPERTIES:
:ID:       Np6-SplTGP0nvtW12yK8Hm7J@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Hooks @ Naturals Hooks @ Naturals

Follow on MiLB First Pitch  https //stza.co/+wh$V-U

Shop  https //stza.co/+wh$V-N

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Hooks @ Naturals
END:VALARM
DTSTART:20180405T232500Z
DTEND:20180406T022500Z
UID:Np6-SplTGP0nvtW12yK8Hm7J@stanza.co
SUMMARY:Hooks @ Naturals
DESCRIPTION:Hooks @ Naturals\n\nFollow on MiLB First Pitch: https://stza.co/+wh$V-U\n\nShop: https://stza.co/+wh$V-N\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144517Z
LAST-MODIFIED:20180213T144517Z
TRANSP:OPAQUE
END:VEVENT
* Hooks @ Naturals
<2018-04-06 Fri 19:05-22:05>
:PROPERTIES:
:ID:       hpTAU8uq6zJf9zxjHZeDBhjs@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Hooks @ Naturals Hooks @ Naturals

Follow on MiLB First Pitch  https //stza.co/+wh$W-14

Shop  https //stza.co/+wh$W-3v

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Hooks @ Naturals
END:VALARM
DTSTART:20180407T000500Z
DTEND:20180407T030500Z
UID:hpTAU8uq6zJf9zxjHZeDBhjs@stanza.co
SUMMARY:Hooks @ Naturals
DESCRIPTION:Hooks @ Naturals\n\nFollow on MiLB First Pitch: https://stza.co/+wh$W-14\n\nShop: https://stza.co/+wh$W-3v\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144517Z
LAST-MODIFIED:20180213T144517Z
TRANSP:OPAQUE
END:VEVENT
* Hooks @ Naturals
<2018-04-07 Sat 18:05-21:05>
:PROPERTIES:
:ID:       qItW3AOAbd14aTav5XH69DrE@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Hooks @ Naturals Hooks @ Naturals

Follow on MiLB First Pitch  https //stza.co/+wh$X-q

Shop  https //stza.co/+wh$X-3O

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Hooks @ Naturals
END:VALARM
DTSTART:20180407T230500Z
DTEND:20180408T020500Z
UID:qItW3AOAbd14aTav5XH69DrE@stanza.co
SUMMARY:Hooks @ Naturals
DESCRIPTION:Hooks @ Naturals\n\nFollow on MiLB First Pitch: https://stza.co/+wh$X-q\n\nShop: https://stza.co/+wh$X-3O\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144517Z
LAST-MODIFIED:20180213T144517Z
TRANSP:OPAQUE
END:VEVENT
* Hooks @ Travelers
<2018-04-08 Sun 14:10-17:10>
:PROPERTIES:
:ID:       K0VX-aL0Hq4xiU1p6khn5gRV@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Hooks @ Travelers Hooks @ Travelers

Follow on MiLB First Pitch  https //stza.co/+v$VU-13

Shop  https //stza.co/+v$VU-3x

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Hooks @ Travelers
END:VALARM
DTSTART:20180408T191000Z
DTEND:20180408T221000Z
UID:K0VX-aL0Hq4xiU1p6khn5gRV@stanza.co
SUMMARY:Hooks @ Travelers
DESCRIPTION:Hooks @ Travelers\n\nFollow on MiLB First Pitch: https://stza.co/+v$VU-13\n\nShop: https://stza.co/+v$VU-3x\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144517Z
LAST-MODIFIED:20180213T144517Z
TRANSP:OPAQUE
END:VEVENT
* Hooks @ Travelers
<2018-04-09 Mon 19:10-22:10>
:PROPERTIES:
:ID:       i3yQOoh0mqQOxsKmo_TdnUYy@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Hooks @ Travelers Hooks @ Travelers

Follow on MiLB First Pitch  https //stza.co/+v$VV-1H

Shop  https //stza.co/+v$VV-1J

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Hooks @ Travelers
END:VALARM
DTSTART:20180410T001000Z
DTEND:20180410T031000Z
UID:i3yQOoh0mqQOxsKmo_TdnUYy@stanza.co
SUMMARY:Hooks @ Travelers
DESCRIPTION:Hooks @ Travelers\n\nFollow on MiLB First Pitch: https://stza.co/+v$VV-1H\n\nShop: https://stza.co/+v$VV-1J\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144517Z
LAST-MODIFIED:20180213T144517Z
TRANSP:OPAQUE
END:VEVENT
* Hooks @ Travelers
<2018-04-10 Tue 11:00-14:00>
:PROPERTIES:
:ID:       2vzD11FCO6H4XFk2HYFIy0Vj@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Hooks @ Travelers Hooks @ Travelers

Follow on MiLB First Pitch  https //stza.co/+v$VW-1Z

Shop  https //stza.co/+v$VW-1l

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Hooks @ Travelers
END:VALARM
DTSTART:20180410T160000Z
DTEND:20180410T190000Z
UID:2vzD11FCO6H4XFk2HYFIy0Vj@stanza.co
SUMMARY:Hooks @ Travelers
DESCRIPTION:Hooks @ Travelers\n\nFollow on MiLB First Pitch: https://stza.co/+v$VW-1Z\n\nShop: https://stza.co/+v$VW-1l\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144517Z
LAST-MODIFIED:20180213T144517Z
TRANSP:OPAQUE
END:VEVENT
* Hooks vs. Naturals
<2018-04-12 Thu 19:05-22:05>
:PROPERTIES:
:ID:       hY41BI5lScalnf26WSptOm9W@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Hooks vs. Naturals Hooks vs. Naturals

Follow on MiLB First Pitch  https //stza.co/+xzER-2m

Shop  https //stza.co/+xzER-3m

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Hooks vs. Naturals
END:VALARM
DTSTART:20180413T000500Z
DTEND:20180413T030500Z
UID:hY41BI5lScalnf26WSptOm9W@stanza.co
SUMMARY:Hooks vs. Naturals
DESCRIPTION:Hooks vs. Naturals\n\nFollow on MiLB First Pitch: https://stza.co/+xzER-2m\n\nShop: https://stza.co/+xzER-3m\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144517Z
LAST-MODIFIED:20180213T144517Z
TRANSP:OPAQUE
END:VEVENT
* Hooks vs. Naturals
<2018-04-13 Fri 19:05-22:05>
:PROPERTIES:
:ID:       0M49NTM2anOaKihbr6H2dGKB@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Hooks vs. Naturals Hooks vs. Naturals

Follow on MiLB First Pitch  https //stza.co/+xzET-15

Shop  https //stza.co/+xzET-3r

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Hooks vs. Naturals
END:VALARM
DTSTART:20180414T000500Z
DTEND:20180414T030500Z
UID:0M49NTM2anOaKihbr6H2dGKB@stanza.co
SUMMARY:Hooks vs. Naturals
DESCRIPTION:Hooks vs. Naturals\n\nFollow on MiLB First Pitch: https://stza.co/+xzET-15\n\nShop: https://stza.co/+xzET-3r\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144517Z
LAST-MODIFIED:20180213T144517Z
TRANSP:OPAQUE
END:VEVENT
* Hooks vs. Naturals
<2018-04-14 Sat 19:05-22:05>
:PROPERTIES:
:ID:       mqdkuEwgfF3GyGP3ftEJQTNY@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Hooks vs. Naturals Hooks vs. Naturals

Follow on MiLB First Pitch  https //stza.co/+xzEU-2_

Shop  https //stza.co/+xzEU-2z

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Hooks vs. Naturals
END:VALARM
DTSTART:20180415T000500Z
DTEND:20180415T030500Z
UID:mqdkuEwgfF3GyGP3ftEJQTNY@stanza.co
SUMMARY:Hooks vs. Naturals
DESCRIPTION:Hooks vs. Naturals\n\nFollow on MiLB First Pitch: https://stza.co/+xzEU-2_\n\nShop: https://stza.co/+xzEU-2z\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144517Z
LAST-MODIFIED:20180213T144517Z
TRANSP:OPAQUE
END:VEVENT
* Hooks vs. Travelers
<2018-04-15 Sun 14:05-17:05>
:PROPERTIES:
:ID:       QlJcpnNAfGyxAA291HYp25GK@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Hooks vs. Travelers Hooks vs. Travelers

Follow on MiLB First Pitch  https //stza.co/+xzEX-2U

Shop  https //stza.co/+xzEX-3c

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Hooks vs. Travelers
END:VALARM
DTSTART:20180415T190500Z
DTEND:20180415T220500Z
UID:QlJcpnNAfGyxAA291HYp25GK@stanza.co
SUMMARY:Hooks vs. Travelers
DESCRIPTION:Hooks vs. Travelers\n\nFollow on MiLB First Pitch: https://stza.co/+xzEX-2U\n\nShop: https://stza.co/+xzEX-3c\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144517Z
LAST-MODIFIED:20180213T144517Z
TRANSP:OPAQUE
END:VEVENT
* Hooks vs. Travelers
<2018-04-16 Mon 19:05-22:05>
:PROPERTIES:
:ID:       Z9Jk7Oa3SFS_bAPS0Z4DOSGM@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Hooks vs. Travelers Hooks vs. Travelers

Follow on MiLB First Pitch  https //stza.co/+xzEZ-l

Shop  https //stza.co/+xzEZ-m

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Hooks vs. Travelers
END:VALARM
DTSTART:20180417T000500Z
DTEND:20180417T030500Z
UID:Z9Jk7Oa3SFS_bAPS0Z4DOSGM@stanza.co
SUMMARY:Hooks vs. Travelers
DESCRIPTION:Hooks vs. Travelers\n\nFollow on MiLB First Pitch: https://stza.co/+xzEZ-l\n\nShop: https://stza.co/+xzEZ-m\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144517Z
LAST-MODIFIED:20180213T144517Z
TRANSP:OPAQUE
END:VEVENT
* Hooks vs. Travelers
<2018-04-17 Tue 19:05-22:05>
:PROPERTIES:
:ID:       H_WUPhFiSliOOOedhGR7IEVF@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Hooks vs. Travelers Hooks vs. Travelers

Follow on MiLB First Pitch  https //stza.co/+xzE$-2

Shop  https //stza.co/+xzE$-3y

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Hooks vs. Travelers
END:VALARM
DTSTART:20180418T000500Z
DTEND:20180418T030500Z
UID:H_WUPhFiSliOOOedhGR7IEVF@stanza.co
SUMMARY:Hooks vs. Travelers
DESCRIPTION:Hooks vs. Travelers\n\nFollow on MiLB First Pitch: https://stza.co/+xzE$-2\n\nShop: https://stza.co/+xzE$-3y\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144517Z
LAST-MODIFIED:20180213T144517Z
TRANSP:OPAQUE
END:VEVENT
* Hooks @ RoughRiders
<2018-04-19 Thu 19:05-22:05>
:PROPERTIES:
:ID:       MbnWTphE9tXve_XQTmB9s2oZ@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Hooks @ RoughRiders Hooks @ RoughRiders

Follow on MiLB First Pitch  https //stza.co/+wY7j-O

Shop  https //stza.co/+wY7j-1

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Hooks @ RoughRiders
END:VALARM
DTSTART:20180420T000500Z
DTEND:20180420T030500Z
UID:MbnWTphE9tXve_XQTmB9s2oZ@stanza.co
SUMMARY:Hooks @ RoughRiders
DESCRIPTION:Hooks @ RoughRiders\n\nFollow on MiLB First Pitch: https://stza.co/+wY7j-O\n\nShop: https://stza.co/+wY7j-1\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144517Z
LAST-MODIFIED:20180213T144517Z
TRANSP:OPAQUE
END:VEVENT
* Hooks @ RoughRiders
<2018-04-20 Fri 19:05-22:05>
:PROPERTIES:
:ID:       TNbw9JzMGvLswIfN8MEqmzEO@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Hooks @ RoughRiders Hooks @ RoughRiders

Follow on MiLB First Pitch  https //stza.co/+wY7k-S

Shop  https //stza.co/+wY7k-r

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Hooks @ RoughRiders
END:VALARM
DTSTART:20180421T000500Z
DTEND:20180421T030500Z
UID:TNbw9JzMGvLswIfN8MEqmzEO@stanza.co
SUMMARY:Hooks @ RoughRiders
DESCRIPTION:Hooks @ RoughRiders\n\nFollow on MiLB First Pitch: https://stza.co/+wY7k-S\n\nShop: https://stza.co/+wY7k-r\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144517Z
LAST-MODIFIED:20180213T144517Z
TRANSP:OPAQUE
END:VEVENT
* Hooks @ RoughRiders
<2018-04-21 Sat 19:05-22:05>
:PROPERTIES:
:ID:       nE9xbAwVHX0EO9xTJeCMr8ee@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Hooks @ RoughRiders Hooks @ RoughRiders

Follow on MiLB First Pitch  https //stza.co/+wY7l-3k

Shop  https //stza.co/+wY7l-22

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Hooks @ RoughRiders
END:VALARM
DTSTART:20180422T000500Z
DTEND:20180422T030500Z
UID:nE9xbAwVHX0EO9xTJeCMr8ee@stanza.co
SUMMARY:Hooks @ RoughRiders
DESCRIPTION:Hooks @ RoughRiders\n\nFollow on MiLB First Pitch: https://stza.co/+wY7l-3k\n\nShop: https://stza.co/+wY7l-22\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144517Z
LAST-MODIFIED:20180213T144517Z
TRANSP:OPAQUE
END:VEVENT
* Hooks @ RoughRiders
<2018-04-22 Sun 16:05-19:05>
:PROPERTIES:
:ID:       2KOK1Oy_NfrvfF78FIvhnUua@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Hooks @ RoughRiders Hooks @ RoughRiders

Follow on MiLB First Pitch  https //stza.co/+wY7m-22

Shop  https //stza.co/+wY7m-_

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Hooks @ RoughRiders
END:VALARM
DTSTART:20180422T210500Z
DTEND:20180423T000500Z
UID:2KOK1Oy_NfrvfF78FIvhnUua@stanza.co
SUMMARY:Hooks @ RoughRiders
DESCRIPTION:Hooks @ RoughRiders\n\nFollow on MiLB First Pitch: https://stza.co/+wY7m-22\n\nShop: https://stza.co/+wY7m-_\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144517Z
LAST-MODIFIED:20180213T144517Z
TRANSP:OPAQUE
END:VEVENT
* Hooks vs. RockHounds
<2018-04-23 Mon 19:05-22:05>
:PROPERTIES:
:ID:       Tcyukd3JGWVk4HzuaDVE9EpV@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Hooks vs. RockHounds Hooks vs. RockHounds

Follow on MiLB First Pitch  https //stza.co/+xzF0-3y

Shop  https //stza.co/+xzF0-l

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Hooks vs. RockHounds
END:VALARM
DTSTART:20180424T000500Z
DTEND:20180424T030500Z
UID:Tcyukd3JGWVk4HzuaDVE9EpV@stanza.co
SUMMARY:Hooks vs. RockHounds
DESCRIPTION:Hooks vs. RockHounds\n\nFollow on MiLB First Pitch: https://stza.co/+xzF0-3y\n\nShop: https://stza.co/+xzF0-l\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144517Z
LAST-MODIFIED:20180213T144517Z
TRANSP:OPAQUE
END:VEVENT
* Hooks vs. RockHounds
<2018-04-24 Tue 19:05-22:05>
:PROPERTIES:
:ID:       bP7o0obXNvJk1pMRfjfsmHIw@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Hooks vs. RockHounds Hooks vs. RockHounds

Follow on MiLB First Pitch  https //stza.co/+xzF3-1F

Shop  https //stza.co/+xzF3-2F

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Hooks vs. RockHounds
END:VALARM
DTSTART:20180425T000500Z
DTEND:20180425T030500Z
UID:bP7o0obXNvJk1pMRfjfsmHIw@stanza.co
SUMMARY:Hooks vs. RockHounds
DESCRIPTION:Hooks vs. RockHounds\n\nFollow on MiLB First Pitch: https://stza.co/+xzF3-1F\n\nShop: https://stza.co/+xzF3-2F\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144517Z
LAST-MODIFIED:20180213T144517Z
TRANSP:OPAQUE
END:VEVENT
* Hooks vs. RockHounds
<2018-04-25 Wed 19:05-22:05>
:PROPERTIES:
:ID:       49uj_B-TzRRI1OXqtymEAbSC@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Hooks vs. RockHounds Hooks vs. RockHounds

Follow on MiLB First Pitch  https //stza.co/+xzF5-3k

Shop  https //stza.co/+xzF5-K

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Hooks vs. RockHounds
END:VALARM
DTSTART:20180426T000500Z
DTEND:20180426T030500Z
UID:49uj_B-TzRRI1OXqtymEAbSC@stanza.co
SUMMARY:Hooks vs. RockHounds
DESCRIPTION:Hooks vs. RockHounds\n\nFollow on MiLB First Pitch: https://stza.co/+xzF5-3k\n\nShop: https://stza.co/+xzF5-K\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144517Z
LAST-MODIFIED:20180213T144517Z
TRANSP:OPAQUE
END:VEVENT
* Hooks vs. RockHounds
<2018-04-26 Thu 19:05-22:05>
:PROPERTIES:
:ID:       C-zQFciAVA0J3anyMuYSj6Fd@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Hooks vs. RockHounds Hooks vs. RockHounds

Follow on MiLB First Pitch  https //stza.co/+xzF7-1Z

Shop  https //stza.co/+xzF7-3X

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Hooks vs. RockHounds
END:VALARM
DTSTART:20180427T000500Z
DTEND:20180427T030500Z
UID:C-zQFciAVA0J3anyMuYSj6Fd@stanza.co
SUMMARY:Hooks vs. RockHounds
DESCRIPTION:Hooks vs. RockHounds\n\nFollow on MiLB First Pitch: https://stza.co/+xzF7-1Z\n\nShop: https://stza.co/+xzF7-3X\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144517Z
LAST-MODIFIED:20180213T144517Z
TRANSP:OPAQUE
END:VEVENT
* Hooks vs. RoughRiders
<2018-04-27 Fri 19:05-22:05>
:PROPERTIES:
:ID:       tHit5jnJvvtLIUmcI7OmvkkE@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Hooks vs. RoughRiders Hooks vs. RoughRiders

Follow on MiLB First Pitch  https //stza.co/+xzFa-1k

Shop  https //stza.co/+xzFa-3E

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Hooks vs. RoughRiders
END:VALARM
DTSTART:20180428T000500Z
DTEND:20180428T030500Z
UID:tHit5jnJvvtLIUmcI7OmvkkE@stanza.co
SUMMARY:Hooks vs. RoughRiders
DESCRIPTION:Hooks vs. RoughRiders\n\nFollow on MiLB First Pitch: https://stza.co/+xzFa-1k\n\nShop: https://stza.co/+xzFa-3E\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144517Z
LAST-MODIFIED:20180213T144517Z
TRANSP:OPAQUE
END:VEVENT
* Hooks vs. RoughRiders
<2018-04-28 Sat 19:05-22:05>
:PROPERTIES:
:ID:       Glh8YunprFgry8N3ODfldFfx@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Hooks vs. RoughRiders Hooks vs. RoughRiders

Follow on MiLB First Pitch  https //stza.co/+xzFc-2W

Shop  https //stza.co/+xzFc-3L

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Hooks vs. RoughRiders
END:VALARM
DTSTART:20180429T000500Z
DTEND:20180429T030500Z
UID:Glh8YunprFgry8N3ODfldFfx@stanza.co
SUMMARY:Hooks vs. RoughRiders
DESCRIPTION:Hooks vs. RoughRiders\n\nFollow on MiLB First Pitch: https://stza.co/+xzFc-2W\n\nShop: https://stza.co/+xzFc-3L\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144517Z
LAST-MODIFIED:20180213T144517Z
TRANSP:OPAQUE
END:VEVENT
* Hooks vs. RoughRiders
<2018-04-29 Sun 14:05-17:05>
:PROPERTIES:
:ID:       97AvXPUHUVjd0MmzIxuWT2yW@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Hooks vs. RoughRiders Hooks vs. RoughRiders

Follow on MiLB First Pitch  https //stza.co/+xzFe-1d

Shop  https //stza.co/+xzFe-1S

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Hooks vs. RoughRiders
END:VALARM
DTSTART:20180429T190500Z
DTEND:20180429T220500Z
UID:97AvXPUHUVjd0MmzIxuWT2yW@stanza.co
SUMMARY:Hooks vs. RoughRiders
DESCRIPTION:Hooks vs. RoughRiders\n\nFollow on MiLB First Pitch: https://stza.co/+xzFe-1d\n\nShop: https://stza.co/+xzFe-1S\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144517Z
LAST-MODIFIED:20180213T144517Z
TRANSP:OPAQUE
END:VEVENT
* Hooks vs. RoughRiders
<2018-04-30 Mon 19:05-22:05>
:PROPERTIES:
:ID:       biQvUF4MTv8JGxZLrWBsy9hH@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Hooks vs. RoughRiders Hooks vs. RoughRiders

Follow on MiLB First Pitch  https //stza.co/+xzFg-3R

Shop  https //stza.co/+xzFg-3Y

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Hooks vs. RoughRiders
END:VALARM
DTSTART:20180501T000500Z
DTEND:20180501T030500Z
UID:biQvUF4MTv8JGxZLrWBsy9hH@stanza.co
SUMMARY:Hooks vs. RoughRiders
DESCRIPTION:Hooks vs. RoughRiders\n\nFollow on MiLB First Pitch: https://stza.co/+xzFg-3R\n\nShop: https://stza.co/+xzFg-3Y\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144517Z
LAST-MODIFIED:20180213T144517Z
TRANSP:OPAQUE
END:VEVENT
* Hooks @ RockHounds
<2018-05-01 Tue 18:30-21:30>
:PROPERTIES:
:ID:       eT3LVx_I1fdp0u5adOeM_BiU@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Hooks @ RockHounds Hooks @ RockHounds

Follow on MiLB First Pitch  https //stza.co/+wX1a-1d

Shop  https //stza.co/+wX1a-3l

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Hooks @ RockHounds
END:VALARM
DTSTART:20180501T233000Z
DTEND:20180502T023000Z
UID:eT3LVx_I1fdp0u5adOeM_BiU@stanza.co
SUMMARY:Hooks @ RockHounds
DESCRIPTION:Hooks @ RockHounds\n\nFollow on MiLB First Pitch: https://stza.co/+wX1a-1d\n\nShop: https://stza.co/+wX1a-3l\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144517Z
LAST-MODIFIED:20180213T144517Z
TRANSP:OPAQUE
END:VEVENT
* Hooks @ RockHounds
<2018-05-02 Wed 11:00-14:00>
:PROPERTIES:
:ID:       DkP_laqJChzWcskFMkzj5XoG@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Hooks @ RockHounds Hooks @ RockHounds

Follow on MiLB First Pitch  https //stza.co/+wX1b-q

Shop  https //stza.co/+wX1b-1r

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Hooks @ RockHounds
END:VALARM
DTSTART:20180502T160000Z
DTEND:20180502T190000Z
UID:DkP_laqJChzWcskFMkzj5XoG@stanza.co
SUMMARY:Hooks @ RockHounds
DESCRIPTION:Hooks @ RockHounds\n\nFollow on MiLB First Pitch: https://stza.co/+wX1b-q\n\nShop: https://stza.co/+wX1b-1r\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144517Z
LAST-MODIFIED:20180213T144517Z
TRANSP:OPAQUE
END:VEVENT
* Hooks @ RockHounds
<2018-05-03 Thu 19:00-22:00>
:PROPERTIES:
:ID:       U3PlSLHHqLo4XWsRlMW24owL@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Hooks @ RockHounds Hooks @ RockHounds

Follow on MiLB First Pitch  https //stza.co/+wX1c-2j

Shop  https //stza.co/+wX1c-2L

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Hooks @ RockHounds
END:VALARM
DTSTART:20180504T000000Z
DTEND:20180504T030000Z
UID:U3PlSLHHqLo4XWsRlMW24owL@stanza.co
SUMMARY:Hooks @ RockHounds
DESCRIPTION:Hooks @ RockHounds\n\nFollow on MiLB First Pitch: https://stza.co/+wX1c-2j\n\nShop: https://stza.co/+wX1c-2L\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144517Z
LAST-MODIFIED:20180213T144517Z
TRANSP:OPAQUE
END:VEVENT
* Hooks @ RockHounds
<2018-05-04 Fri 19:00-22:00>
:PROPERTIES:
:ID:       NX3qWbo5-beStxKQyew6LB1V@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Hooks @ RockHounds Hooks @ RockHounds

Follow on MiLB First Pitch  https //stza.co/+wX1d-3O

Shop  https //stza.co/+wX1d-11

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Hooks @ RockHounds
END:VALARM
DTSTART:20180505T000000Z
DTEND:20180505T030000Z
UID:NX3qWbo5-beStxKQyew6LB1V@stanza.co
SUMMARY:Hooks @ RockHounds
DESCRIPTION:Hooks @ RockHounds\n\nFollow on MiLB First Pitch: https://stza.co/+wX1d-3O\n\nShop: https://stza.co/+wX1d-11\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144517Z
LAST-MODIFIED:20180213T144517Z
TRANSP:OPAQUE
END:VEVENT
* Hooks @ Missions
<2018-05-05 Sat 19:05-22:05>
:PROPERTIES:
:ID:       n1_KR0AL-zE04OGCWDDTWwbz@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Hooks @ Missions Hooks @ Missions

Follow on MiLB First Pitch  https //stza.co/+wMtC-2C

Shop  https //stza.co/+wMtC-H

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Hooks @ Missions
END:VALARM
DTSTART:20180506T000500Z
DTEND:20180506T030500Z
UID:n1_KR0AL-zE04OGCWDDTWwbz@stanza.co
SUMMARY:Hooks @ Missions
DESCRIPTION:Hooks @ Missions\n\nFollow on MiLB First Pitch: https://stza.co/+wMtC-2C\n\nShop: https://stza.co/+wMtC-H\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144517Z
LAST-MODIFIED:20180213T144517Z
TRANSP:OPAQUE
END:VEVENT
* Hooks @ Missions
<2018-05-06 Sun 14:05-17:05>
:PROPERTIES:
:ID:       AZRJrgZDD4HdVkoUE4RG2uA-@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Hooks @ Missions Hooks @ Missions

Follow on MiLB First Pitch  https //stza.co/+wMtD-2Z

Shop  https //stza.co/+wMtD-2o

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Hooks @ Missions
END:VALARM
DTSTART:20180506T190500Z
DTEND:20180506T220500Z
UID:AZRJrgZDD4HdVkoUE4RG2uA-@stanza.co
SUMMARY:Hooks @ Missions
DESCRIPTION:Hooks @ Missions\n\nFollow on MiLB First Pitch: https://stza.co/+wMtD-2Z\n\nShop: https://stza.co/+wMtD-2o\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144517Z
LAST-MODIFIED:20180213T144517Z
TRANSP:OPAQUE
END:VEVENT
* Hooks @ Missions
<2018-05-07 Mon 19:05-22:05>
:PROPERTIES:
:ID:       B0aFgfosQgYCud2LDk3e9zHL@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Hooks @ Missions Hooks @ Missions

Follow on MiLB First Pitch  https //stza.co/+wMtE-1y

Shop  https //stza.co/+wMtE-3L

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Hooks @ Missions
END:VALARM
DTSTART:20180508T000500Z
DTEND:20180508T030500Z
UID:B0aFgfosQgYCud2LDk3e9zHL@stanza.co
SUMMARY:Hooks @ Missions
DESCRIPTION:Hooks @ Missions\n\nFollow on MiLB First Pitch: https://stza.co/+wMtE-1y\n\nShop: https://stza.co/+wMtE-3L\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144517Z
LAST-MODIFIED:20180213T144517Z
TRANSP:OPAQUE
END:VEVENT
* Hooks @ Missions
<2018-05-08 Tue 19:05-22:05>
:PROPERTIES:
:ID:       Og76CUrZ2ljJ34r847lK4Yk7@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Hooks @ Missions Hooks @ Missions

Follow on MiLB First Pitch  https //stza.co/+wMtF-H

Shop  https //stza.co/+wMtF-3M

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Hooks @ Missions
END:VALARM
DTSTART:20180509T000500Z
DTEND:20180509T030500Z
UID:Og76CUrZ2ljJ34r847lK4Yk7@stanza.co
SUMMARY:Hooks @ Missions
DESCRIPTION:Hooks @ Missions\n\nFollow on MiLB First Pitch: https://stza.co/+wMtF-H\n\nShop: https://stza.co/+wMtF-3M\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144517Z
LAST-MODIFIED:20180213T144517Z
TRANSP:OPAQUE
END:VEVENT
* Hooks vs. RockHounds
<2018-05-10 Thu 19:05-22:05>
:PROPERTIES:
:ID:       owcK1--A9pDmqM_sNDlWnlMO@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Hooks vs. RockHounds Hooks vs. RockHounds

Follow on MiLB First Pitch  https //stza.co/+xzFj-3L

Shop  https //stza.co/+xzFj-P

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Hooks vs. RockHounds
END:VALARM
DTSTART:20180511T000500Z
DTEND:20180511T030500Z
UID:owcK1--A9pDmqM_sNDlWnlMO@stanza.co
SUMMARY:Hooks vs. RockHounds
DESCRIPTION:Hooks vs. RockHounds\n\nFollow on MiLB First Pitch: https://stza.co/+xzFj-3L\n\nShop: https://stza.co/+xzFj-P\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144517Z
LAST-MODIFIED:20180213T144517Z
TRANSP:OPAQUE
END:VEVENT
* Hooks vs. RockHounds
<2018-05-11 Fri 19:05-22:05>
:PROPERTIES:
:ID:       _VrhpnIiojZN_you6Wy4YJxH@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Hooks vs. RockHounds Hooks vs. RockHounds

Follow on MiLB First Pitch  https //stza.co/+xzFl-2k

Shop  https //stza.co/+xzFl-3M

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Hooks vs. RockHounds
END:VALARM
DTSTART:20180512T000500Z
DTEND:20180512T030500Z
UID:_VrhpnIiojZN_you6Wy4YJxH@stanza.co
SUMMARY:Hooks vs. RockHounds
DESCRIPTION:Hooks vs. RockHounds\n\nFollow on MiLB First Pitch: https://stza.co/+xzFl-2k\n\nShop: https://stza.co/+xzFl-3M\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144517Z
LAST-MODIFIED:20180213T144517Z
TRANSP:OPAQUE
END:VEVENT
* Hooks vs. RockHounds
<2018-05-12 Sat 19:05-22:05>
:PROPERTIES:
:ID:       NU5xWyBaas3f6PjiCNCmgm1e@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Hooks vs. RockHounds Hooks vs. RockHounds

Follow on MiLB First Pitch  https //stza.co/+xzFn-3A

Shop  https //stza.co/+xzFn-2H

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Hooks vs. RockHounds
END:VALARM
DTSTART:20180513T000500Z
DTEND:20180513T030500Z
UID:NU5xWyBaas3f6PjiCNCmgm1e@stanza.co
SUMMARY:Hooks vs. RockHounds
DESCRIPTION:Hooks vs. RockHounds\n\nFollow on MiLB First Pitch: https://stza.co/+xzFn-3A\n\nShop: https://stza.co/+xzFn-2H\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144517Z
LAST-MODIFIED:20180213T144517Z
TRANSP:OPAQUE
END:VEVENT
* Hooks vs. RockHounds
<2018-05-13 Sun 14:05-17:05>
:PROPERTIES:
:ID:       ATVZ53ijOkjgN3l6k0cg2jbn@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Hooks vs. RockHounds Hooks vs. RockHounds

Follow on MiLB First Pitch  https //stza.co/+xzFo-3K

Shop  https //stza.co/+xzFo-i

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Hooks vs. RockHounds
END:VALARM
DTSTART:20180513T190500Z
DTEND:20180513T220500Z
UID:ATVZ53ijOkjgN3l6k0cg2jbn@stanza.co
SUMMARY:Hooks vs. RockHounds
DESCRIPTION:Hooks vs. RockHounds\n\nFollow on MiLB First Pitch: https://stza.co/+xzFo-3K\n\nShop: https://stza.co/+xzFo-i\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144517Z
LAST-MODIFIED:20180213T144517Z
TRANSP:OPAQUE
END:VEVENT
* Hooks vs. Missions
<2018-05-14 Mon 19:05-22:05>
:PROPERTIES:
:ID:       3MKKLimyMHRvXdkEM-L_vmJG@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Hooks vs. Missions Hooks vs. Missions

Follow on MiLB First Pitch  https //stza.co/+xzFr-1n

Shop  https //stza.co/+xzFr-1_

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Hooks vs. Missions
END:VALARM
DTSTART:20180515T000500Z
DTEND:20180515T030500Z
UID:3MKKLimyMHRvXdkEM-L_vmJG@stanza.co
SUMMARY:Hooks vs. Missions
DESCRIPTION:Hooks vs. Missions\n\nFollow on MiLB First Pitch: https://stza.co/+xzFr-1n\n\nShop: https://stza.co/+xzFr-1_\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144517Z
LAST-MODIFIED:20180213T144517Z
TRANSP:OPAQUE
END:VEVENT
* Hooks vs. Missions
<2018-05-15 Tue 19:05-22:05>
:PROPERTIES:
:ID:       b-MOw78O26a3zxipeb46F9Ac@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Hooks vs. Missions Hooks vs. Missions

Follow on MiLB First Pitch  https //stza.co/+xzFu-2c

Shop  https //stza.co/+xzFu-3J

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Hooks vs. Missions
END:VALARM
DTSTART:20180516T000500Z
DTEND:20180516T030500Z
UID:b-MOw78O26a3zxipeb46F9Ac@stanza.co
SUMMARY:Hooks vs. Missions
DESCRIPTION:Hooks vs. Missions\n\nFollow on MiLB First Pitch: https://stza.co/+xzFu-2c\n\nShop: https://stza.co/+xzFu-3J\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144517Z
LAST-MODIFIED:20180213T144517Z
TRANSP:OPAQUE
END:VEVENT
* Hooks vs. Missions
<2018-05-16 Wed 19:05-22:05>
:PROPERTIES:
:ID:       ala3EJRHi05yxmtdSNJBYxLm@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Hooks vs. Missions Hooks vs. Missions

Follow on MiLB First Pitch  https //stza.co/+xzFw-1E

Shop  https //stza.co/+xzFw-11

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Hooks vs. Missions
END:VALARM
DTSTART:20180517T000500Z
DTEND:20180517T030500Z
UID:ala3EJRHi05yxmtdSNJBYxLm@stanza.co
SUMMARY:Hooks vs. Missions
DESCRIPTION:Hooks vs. Missions\n\nFollow on MiLB First Pitch: https://stza.co/+xzFw-1E\n\nShop: https://stza.co/+xzFw-11\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144517Z
LAST-MODIFIED:20180213T144517Z
TRANSP:OPAQUE
END:VEVENT
* Hooks vs. Missions
<2018-05-17 Thu 19:05-22:05>
:PROPERTIES:
:ID:       P3h4X3XzVQKQ6SAFxbP7vHrL@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Hooks vs. Missions Hooks vs. Missions

Follow on MiLB First Pitch  https //stza.co/+xzFx-1K

Shop  https //stza.co/+xzFx-3A

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Hooks vs. Missions
END:VALARM
DTSTART:20180518T000500Z
DTEND:20180518T030500Z
UID:P3h4X3XzVQKQ6SAFxbP7vHrL@stanza.co
SUMMARY:Hooks vs. Missions
DESCRIPTION:Hooks vs. Missions\n\nFollow on MiLB First Pitch: https://stza.co/+xzFx-1K\n\nShop: https://stza.co/+xzFx-3A\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144517Z
LAST-MODIFIED:20180213T144517Z
TRANSP:OPAQUE
END:VEVENT
* Hooks @ RoughRiders
<2018-05-18 Fri 19:05-22:05>
:PROPERTIES:
:ID:       EKV3iFd1006tocsqPMxy-GE6@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Hooks @ RoughRiders Hooks @ RoughRiders

Follow on MiLB First Pitch  https //stza.co/+wY7n-19

Shop  https //stza.co/+wY7n-1z

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Hooks @ RoughRiders
END:VALARM
DTSTART:20180519T000500Z
DTEND:20180519T030500Z
UID:EKV3iFd1006tocsqPMxy-GE6@stanza.co
SUMMARY:Hooks @ RoughRiders
DESCRIPTION:Hooks @ RoughRiders\n\nFollow on MiLB First Pitch: https://stza.co/+wY7n-19\n\nShop: https://stza.co/+wY7n-1z\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144517Z
LAST-MODIFIED:20180213T144517Z
TRANSP:OPAQUE
END:VEVENT
* Hooks @ RoughRiders
<2018-05-19 Sat 19:05-22:05>
:PROPERTIES:
:ID:       7AyXqx-Q41lqkRvzoGEQzG78@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Hooks @ RoughRiders Hooks @ RoughRiders

Follow on MiLB First Pitch  https //stza.co/+wY7o-1R

Shop  https //stza.co/+wY7o-$

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Hooks @ RoughRiders
END:VALARM
DTSTART:20180520T000500Z
DTEND:20180520T030500Z
UID:7AyXqx-Q41lqkRvzoGEQzG78@stanza.co
SUMMARY:Hooks @ RoughRiders
DESCRIPTION:Hooks @ RoughRiders\n\nFollow on MiLB First Pitch: https://stza.co/+wY7o-1R\n\nShop: https://stza.co/+wY7o-$\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144517Z
LAST-MODIFIED:20180213T144517Z
TRANSP:OPAQUE
END:VEVENT
* Hooks @ RoughRiders
<2018-05-20 Sun 16:05-19:05>
:PROPERTIES:
:ID:       Y6WgGx4HUNoBMn_tW2hRm4Ls@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Hooks @ RoughRiders Hooks @ RoughRiders

Follow on MiLB First Pitch  https //stza.co/+wY7q-2O

Shop  https //stza.co/+wY7q-3A

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Hooks @ RoughRiders
END:VALARM
DTSTART:20180520T210500Z
DTEND:20180521T000500Z
UID:Y6WgGx4HUNoBMn_tW2hRm4Ls@stanza.co
SUMMARY:Hooks @ RoughRiders
DESCRIPTION:Hooks @ RoughRiders\n\nFollow on MiLB First Pitch: https://stza.co/+wY7q-2O\n\nShop: https://stza.co/+wY7q-3A\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144517Z
LAST-MODIFIED:20180213T144517Z
TRANSP:OPAQUE
END:VEVENT
* Hooks @ RoughRiders
<2018-05-21 Mon 11:05-14:05>
:PROPERTIES:
:ID:       IHya1LDxzG6rsJyS21iVqgXD@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Hooks @ RoughRiders Hooks @ RoughRiders

Follow on MiLB First Pitch  https //stza.co/+wY7r-z

Shop  https //stza.co/+wY7r-B

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Hooks @ RoughRiders
END:VALARM
DTSTART:20180521T160500Z
DTEND:20180521T190500Z
UID:IHya1LDxzG6rsJyS21iVqgXD@stanza.co
SUMMARY:Hooks @ RoughRiders
DESCRIPTION:Hooks @ RoughRiders\n\nFollow on MiLB First Pitch: https://stza.co/+wY7r-z\n\nShop: https://stza.co/+wY7r-B\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144517Z
LAST-MODIFIED:20180213T144517Z
TRANSP:OPAQUE
END:VEVENT
* Hooks vs. Cardinals
<2018-05-22 Tue 19:05-22:05>
:PROPERTIES:
:ID:       944sqr9lz9-AmkhPUsBlNTsx@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Hooks vs. Cardinals Hooks vs. Cardinals

Follow on MiLB First Pitch  https //stza.co/+xzFA-2$

Shop  https //stza.co/+xzFA-3o

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Hooks vs. Cardinals
END:VALARM
DTSTART:20180523T000500Z
DTEND:20180523T030500Z
UID:944sqr9lz9-AmkhPUsBlNTsx@stanza.co
SUMMARY:Hooks vs. Cardinals
DESCRIPTION:Hooks vs. Cardinals\n\nFollow on MiLB First Pitch: https://stza.co/+xzFA-2$\n\nShop: https://stza.co/+xzFA-3o\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144517Z
LAST-MODIFIED:20180213T144517Z
TRANSP:OPAQUE
END:VEVENT
* Hooks vs. Cardinals
<2018-05-23 Wed 19:05-22:05>
:PROPERTIES:
:ID:       I1tXkSjnvi3IQPKRe9VA8JLF@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Hooks vs. Cardinals Hooks vs. Cardinals

Follow on MiLB First Pitch  https //stza.co/+xzFC-1M

Shop  https //stza.co/+xzFC-W

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Hooks vs. Cardinals
END:VALARM
DTSTART:20180524T000500Z
DTEND:20180524T030500Z
UID:I1tXkSjnvi3IQPKRe9VA8JLF@stanza.co
SUMMARY:Hooks vs. Cardinals
DESCRIPTION:Hooks vs. Cardinals\n\nFollow on MiLB First Pitch: https://stza.co/+xzFC-1M\n\nShop: https://stza.co/+xzFC-W\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144517Z
LAST-MODIFIED:20180213T144517Z
TRANSP:OPAQUE
END:VEVENT
* Hooks vs. Cardinals
<2018-05-24 Thu 19:05-22:05>
:PROPERTIES:
:ID:       gfph3CsUqLmFbTy0fag2HwLI@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Hooks vs. Cardinals Hooks vs. Cardinals

Follow on MiLB First Pitch  https //stza.co/+xzFD-H

Shop  https //stza.co/+xzFD-b

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Hooks vs. Cardinals
END:VALARM
DTSTART:20180525T000500Z
DTEND:20180525T030500Z
UID:gfph3CsUqLmFbTy0fag2HwLI@stanza.co
SUMMARY:Hooks vs. Cardinals
DESCRIPTION:Hooks vs. Cardinals\n\nFollow on MiLB First Pitch: https://stza.co/+xzFD-H\n\nShop: https://stza.co/+xzFD-b\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144517Z
LAST-MODIFIED:20180213T144517Z
TRANSP:OPAQUE
END:VEVENT
* Hooks vs. Drillers
<2018-05-25 Fri 19:05-22:05>
:PROPERTIES:
:ID:       lzG1eVkCM9I39lyR0h-PTZWD@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Hooks vs. Drillers Hooks vs. Drillers

Follow on MiLB First Pitch  https //stza.co/+xzFG-3y

Shop  https //stza.co/+xzFG-3l

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Hooks vs. Drillers
END:VALARM
DTSTART:20180526T000500Z
DTEND:20180526T030500Z
UID:lzG1eVkCM9I39lyR0h-PTZWD@stanza.co
SUMMARY:Hooks vs. Drillers
DESCRIPTION:Hooks vs. Drillers\n\nFollow on MiLB First Pitch: https://stza.co/+xzFG-3y\n\nShop: https://stza.co/+xzFG-3l\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144517Z
LAST-MODIFIED:20180213T144517Z
TRANSP:OPAQUE
END:VEVENT
* Hooks vs. Drillers
<2018-05-26 Sat 19:05-22:05>
:PROPERTIES:
:ID:       M3A19GpCUbeDns6aASgRepa1@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Hooks vs. Drillers Hooks vs. Drillers

Follow on MiLB First Pitch  https //stza.co/+xzFI-2J

Shop  https //stza.co/+xzFI-1m

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Hooks vs. Drillers
END:VALARM
DTSTART:20180527T000500Z
DTEND:20180527T030500Z
UID:M3A19GpCUbeDns6aASgRepa1@stanza.co
SUMMARY:Hooks vs. Drillers
DESCRIPTION:Hooks vs. Drillers\n\nFollow on MiLB First Pitch: https://stza.co/+xzFI-2J\n\nShop: https://stza.co/+xzFI-1m\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144517Z
LAST-MODIFIED:20180213T144517Z
TRANSP:OPAQUE
END:VEVENT
* Hooks vs. Drillers
<2018-05-27 Sun 18:05-21:05>
:PROPERTIES:
:ID:       g3pXAr1DtTqA8ceF-8eJ2DF2@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Hooks vs. Drillers Hooks vs. Drillers

Follow on MiLB First Pitch  https //stza.co/+xzFK-2U

Shop  https //stza.co/+xzFK-1p

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Hooks vs. Drillers
END:VALARM
DTSTART:20180527T230500Z
DTEND:20180528T020500Z
UID:g3pXAr1DtTqA8ceF-8eJ2DF2@stanza.co
SUMMARY:Hooks vs. Drillers
DESCRIPTION:Hooks vs. Drillers\n\nFollow on MiLB First Pitch: https://stza.co/+xzFK-2U\n\nShop: https://stza.co/+xzFK-1p\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144517Z
LAST-MODIFIED:20180213T144517Z
TRANSP:OPAQUE
END:VEVENT
* Hooks @ Cardinals
<2018-05-29 Tue 18:30-21:30>
:PROPERTIES:
:ID:       odED49GSUB4cBInAuEltWaX_@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Hooks @ Cardinals Hooks @ Cardinals

Follow on MiLB First Pitch  https //stza.co/+wPMv-11

Shop  https //stza.co/+wPMv-d

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Hooks @ Cardinals
END:VALARM
DTSTART:20180529T233000Z
DTEND:20180530T023000Z
UID:odED49GSUB4cBInAuEltWaX_@stanza.co
SUMMARY:Hooks @ Cardinals
DESCRIPTION:Hooks @ Cardinals\n\nFollow on MiLB First Pitch: https://stza.co/+wPMv-11\n\nShop: https://stza.co/+wPMv-d\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144517Z
LAST-MODIFIED:20180213T144517Z
TRANSP:OPAQUE
END:VEVENT
* Hooks @ Cardinals
<2018-05-30 Wed 18:30-21:30>
:PROPERTIES:
:ID:       _LGNtIos-Zw62l_b4luvy5Qm@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Hooks @ Cardinals Hooks @ Cardinals

Follow on MiLB First Pitch  https //stza.co/+wPMx-1n

Shop  https //stza.co/+wPMx-3K

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Hooks @ Cardinals
END:VALARM
DTSTART:20180530T233000Z
DTEND:20180531T023000Z
UID:_LGNtIos-Zw62l_b4luvy5Qm@stanza.co
SUMMARY:Hooks @ Cardinals
DESCRIPTION:Hooks @ Cardinals\n\nFollow on MiLB First Pitch: https://stza.co/+wPMx-1n\n\nShop: https://stza.co/+wPMx-3K\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144517Z
LAST-MODIFIED:20180213T144517Z
TRANSP:OPAQUE
END:VEVENT
* Hooks @ Cardinals
<2018-05-31 Thu 19:10-22:10>
:PROPERTIES:
:ID:       nvTuu_IcL0We2p4r6thvLB81@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Hooks @ Cardinals Hooks @ Cardinals

Follow on MiLB First Pitch  https //stza.co/+wPMy-2T

Shop  https //stza.co/+wPMy-3y

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Hooks @ Cardinals
END:VALARM
DTSTART:20180601T001000Z
DTEND:20180601T031000Z
UID:nvTuu_IcL0We2p4r6thvLB81@stanza.co
SUMMARY:Hooks @ Cardinals
DESCRIPTION:Hooks @ Cardinals\n\nFollow on MiLB First Pitch: https://stza.co/+wPMy-2T\n\nShop: https://stza.co/+wPMy-3y\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144517Z
LAST-MODIFIED:20180213T144517Z
TRANSP:OPAQUE
END:VEVENT
* Hooks @ Drillers
<2018-06-01 Fri 19:05-22:05>
:PROPERTIES:
:ID:       1YflZE6GFqIwnF5S6r-Si1oo@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Hooks @ Drillers Hooks @ Drillers

Follow on MiLB First Pitch  https //stza.co/+v$Z4-1O

Shop  https //stza.co/+v$Z4-2z

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Hooks @ Drillers
END:VALARM
DTSTART:20180602T000500Z
DTEND:20180602T030500Z
UID:1YflZE6GFqIwnF5S6r-Si1oo@stanza.co
SUMMARY:Hooks @ Drillers
DESCRIPTION:Hooks @ Drillers\n\nFollow on MiLB First Pitch: https://stza.co/+v$Z4-1O\n\nShop: https://stza.co/+v$Z4-2z\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144517Z
LAST-MODIFIED:20180213T144517Z
TRANSP:OPAQUE
END:VEVENT
* Hooks @ Drillers
<2018-06-02 Sat 19:05-22:05>
:PROPERTIES:
:ID:       -fhOR7awSsl6UpquBCeU_YP_@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Hooks @ Drillers Hooks @ Drillers

Follow on MiLB First Pitch  https //stza.co/+v$Z5-n

Shop  https //stza.co/+v$Z5-w

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Hooks @ Drillers
END:VALARM
DTSTART:20180603T000500Z
DTEND:20180603T030500Z
UID:-fhOR7awSsl6UpquBCeU_YP_@stanza.co
SUMMARY:Hooks @ Drillers
DESCRIPTION:Hooks @ Drillers\n\nFollow on MiLB First Pitch: https://stza.co/+v$Z5-n\n\nShop: https://stza.co/+v$Z5-w\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144517Z
LAST-MODIFIED:20180213T144517Z
TRANSP:OPAQUE
END:VEVENT
* Hooks @ Drillers
<2018-06-03 Sun 13:05-16:05>
:PROPERTIES:
:ID:       BNLwm4JJfWvjPcOpkU2Jfp67@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Hooks @ Drillers Hooks @ Drillers

Follow on MiLB First Pitch  https //stza.co/+v$Z6-B

Shop  https //stza.co/+v$Z6-2x

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Hooks @ Drillers
END:VALARM
DTSTART:20180603T180500Z
DTEND:20180603T210500Z
UID:BNLwm4JJfWvjPcOpkU2Jfp67@stanza.co
SUMMARY:Hooks @ Drillers
DESCRIPTION:Hooks @ Drillers\n\nFollow on MiLB First Pitch: https://stza.co/+v$Z6-B\n\nShop: https://stza.co/+v$Z6-2x\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144517Z
LAST-MODIFIED:20180213T144517Z
TRANSP:OPAQUE
END:VEVENT
* Hooks vs. RoughRiders
<2018-06-05 Tue 19:05-22:05>
:PROPERTIES:
:ID:       jctttXUi6lABlA1EGloKavBT@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Hooks vs. RoughRiders Hooks vs. RoughRiders

Follow on MiLB First Pitch  https //stza.co/+xzFL-21

Shop  https //stza.co/+xzFL-3c

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Hooks vs. RoughRiders
END:VALARM
DTSTART:20180606T000500Z
DTEND:20180606T030500Z
UID:jctttXUi6lABlA1EGloKavBT@stanza.co
SUMMARY:Hooks vs. RoughRiders
DESCRIPTION:Hooks vs. RoughRiders\n\nFollow on MiLB First Pitch: https://stza.co/+xzFL-21\n\nShop: https://stza.co/+xzFL-3c\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144517Z
LAST-MODIFIED:20180213T144517Z
TRANSP:OPAQUE
END:VEVENT
* Hooks vs. RoughRiders
<2018-06-06 Wed 19:05-22:05>
:PROPERTIES:
:ID:       jl2xtS8fuPhrP-MI2IxXY1w9@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Hooks vs. RoughRiders Hooks vs. RoughRiders

Follow on MiLB First Pitch  https //stza.co/+xzFN-2Y

Shop  https //stza.co/+xzFN-c

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Hooks vs. RoughRiders
END:VALARM
DTSTART:20180607T000500Z
DTEND:20180607T030500Z
UID:jl2xtS8fuPhrP-MI2IxXY1w9@stanza.co
SUMMARY:Hooks vs. RoughRiders
DESCRIPTION:Hooks vs. RoughRiders\n\nFollow on MiLB First Pitch: https://stza.co/+xzFN-2Y\n\nShop: https://stza.co/+xzFN-c\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144517Z
LAST-MODIFIED:20180213T144517Z
TRANSP:OPAQUE
END:VEVENT
* Hooks vs. RoughRiders
<2018-06-07 Thu 19:05-22:05>
:PROPERTIES:
:ID:       cNLaLmZPqxihtgEL0NW0z-aE@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Hooks vs. RoughRiders Hooks vs. RoughRiders

Follow on MiLB First Pitch  https //stza.co/+xzFP-G

Shop  https //stza.co/+xzFP-d

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Hooks vs. RoughRiders
END:VALARM
DTSTART:20180608T000500Z
DTEND:20180608T030500Z
UID:cNLaLmZPqxihtgEL0NW0z-aE@stanza.co
SUMMARY:Hooks vs. RoughRiders
DESCRIPTION:Hooks vs. RoughRiders\n\nFollow on MiLB First Pitch: https://stza.co/+xzFP-G\n\nShop: https://stza.co/+xzFP-d\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144517Z
LAST-MODIFIED:20180213T144517Z
TRANSP:OPAQUE
END:VEVENT
* Hooks vs. RoughRiders
<2018-06-08 Fri 19:05-22:05>
:PROPERTIES:
:ID:       IXGrLhuyCVasXunHT4atuqaD@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Hooks vs. RoughRiders Hooks vs. RoughRiders

Follow on MiLB First Pitch  https //stza.co/+xzFS-2D

Shop  https //stza.co/+xzFS-q

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Hooks vs. RoughRiders
END:VALARM
DTSTART:20180609T000500Z
DTEND:20180609T030500Z
UID:IXGrLhuyCVasXunHT4atuqaD@stanza.co
SUMMARY:Hooks vs. RoughRiders
DESCRIPTION:Hooks vs. RoughRiders\n\nFollow on MiLB First Pitch: https://stza.co/+xzFS-2D\n\nShop: https://stza.co/+xzFS-q\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144517Z
LAST-MODIFIED:20180213T144517Z
TRANSP:OPAQUE
END:VEVENT
* Hooks vs. Missions
<2018-06-09 Sat 19:05-22:05>
:PROPERTIES:
:ID:       NFFs5AiYt56rEPkmJCE78ZA9@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Hooks vs. Missions Hooks vs. Missions

Follow on MiLB First Pitch  https //stza.co/+xzFU-3i

Shop  https //stza.co/+xzFU-V

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Hooks vs. Missions
END:VALARM
DTSTART:20180610T000500Z
DTEND:20180610T030500Z
UID:NFFs5AiYt56rEPkmJCE78ZA9@stanza.co
SUMMARY:Hooks vs. Missions
DESCRIPTION:Hooks vs. Missions\n\nFollow on MiLB First Pitch: https://stza.co/+xzFU-3i\n\nShop: https://stza.co/+xzFU-V\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144517Z
LAST-MODIFIED:20180213T144517Z
TRANSP:OPAQUE
END:VEVENT
* Hooks vs. Missions
<2018-06-10 Sun 18:05-21:05>
:PROPERTIES:
:ID:       eU6-JvS5XWyK4zjAvqC0jAUB@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Hooks vs. Missions Hooks vs. Missions

Follow on MiLB First Pitch  https //stza.co/+xzFV-X

Shop  https //stza.co/+xzFV-10

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Hooks vs. Missions
END:VALARM
DTSTART:20180610T230500Z
DTEND:20180611T020500Z
UID:eU6-JvS5XWyK4zjAvqC0jAUB@stanza.co
SUMMARY:Hooks vs. Missions
DESCRIPTION:Hooks vs. Missions\n\nFollow on MiLB First Pitch: https://stza.co/+xzFV-X\n\nShop: https://stza.co/+xzFV-10\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144517Z
LAST-MODIFIED:20180213T144517Z
TRANSP:OPAQUE
END:VEVENT
* Hooks vs. Missions
<2018-06-11 Mon 19:05-22:05>
:PROPERTIES:
:ID:       AGBlu2ubPm7GKZz_myFOLe_x@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Hooks vs. Missions Hooks vs. Missions

Follow on MiLB First Pitch  https //stza.co/+xzFX-s

Shop  https //stza.co/+xzFX-3

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Hooks vs. Missions
END:VALARM
DTSTART:20180612T000500Z
DTEND:20180612T030500Z
UID:AGBlu2ubPm7GKZz_myFOLe_x@stanza.co
SUMMARY:Hooks vs. Missions
DESCRIPTION:Hooks vs. Missions\n\nFollow on MiLB First Pitch: https://stza.co/+xzFX-s\n\nShop: https://stza.co/+xzFX-3\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144517Z
LAST-MODIFIED:20180213T144517Z
TRANSP:OPAQUE
END:VEVENT
* Hooks vs. Missions
<2018-06-12 Tue 19:05-22:05>
:PROPERTIES:
:ID:       BxaHv5G4fmNCn9dPJrz2Rj1D@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Hooks vs. Missions Hooks vs. Missions

Follow on MiLB First Pitch  https //stza.co/+xzF_-1G

Shop  https //stza.co/+xzF_-3e

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Hooks vs. Missions
END:VALARM
DTSTART:20180613T000500Z
DTEND:20180613T030500Z
UID:BxaHv5G4fmNCn9dPJrz2Rj1D@stanza.co
SUMMARY:Hooks vs. Missions
DESCRIPTION:Hooks vs. Missions\n\nFollow on MiLB First Pitch: https://stza.co/+xzF_-1G\n\nShop: https://stza.co/+xzF_-3e\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144517Z
LAST-MODIFIED:20180213T144517Z
TRANSP:OPAQUE
END:VEVENT
* Hooks @ RockHounds
<2018-06-13 Wed 18:30-21:30>
:PROPERTIES:
:ID:       jqGz8dtTDjcbPxQMf_zmsnKi@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Hooks @ RockHounds Hooks @ RockHounds

Follow on MiLB First Pitch  https //stza.co/+wX1e-3s

Shop  https //stza.co/+wX1e-1v

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Hooks @ RockHounds
END:VALARM
DTSTART:20180613T233000Z
DTEND:20180614T023000Z
UID:jqGz8dtTDjcbPxQMf_zmsnKi@stanza.co
SUMMARY:Hooks @ RockHounds
DESCRIPTION:Hooks @ RockHounds\n\nFollow on MiLB First Pitch: https://stza.co/+wX1e-3s\n\nShop: https://stza.co/+wX1e-1v\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144517Z
LAST-MODIFIED:20180213T144517Z
TRANSP:OPAQUE
END:VEVENT
* Hooks @ RockHounds
<2018-06-14 Thu 19:00-22:00>
:PROPERTIES:
:ID:       -GNc76HQ3PKox1iVk65y0fA8@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Hooks @ RockHounds Hooks @ RockHounds

Follow on MiLB First Pitch  https //stza.co/+wX1f-3j

Shop  https //stza.co/+wX1f-1G

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Hooks @ RockHounds
END:VALARM
DTSTART:20180615T000000Z
DTEND:20180615T030000Z
UID:-GNc76HQ3PKox1iVk65y0fA8@stanza.co
SUMMARY:Hooks @ RockHounds
DESCRIPTION:Hooks @ RockHounds\n\nFollow on MiLB First Pitch: https://stza.co/+wX1f-3j\n\nShop: https://stza.co/+wX1f-1G\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144517Z
LAST-MODIFIED:20180213T144517Z
TRANSP:OPAQUE
END:VEVENT
* Hooks @ RockHounds
<2018-06-15 Fri 19:00-22:00>
:PROPERTIES:
:ID:       5afjDUb-WzoHOYaFPsFgXl73@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Hooks @ RockHounds Hooks @ RockHounds

Follow on MiLB First Pitch  https //stza.co/+wX1g-3h

Shop  https //stza.co/+wX1g-3i

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Hooks @ RockHounds
END:VALARM
DTSTART:20180616T000000Z
DTEND:20180616T030000Z
UID:5afjDUb-WzoHOYaFPsFgXl73@stanza.co
SUMMARY:Hooks @ RockHounds
DESCRIPTION:Hooks @ RockHounds\n\nFollow on MiLB First Pitch: https://stza.co/+wX1g-3h\n\nShop: https://stza.co/+wX1g-3i\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144517Z
LAST-MODIFIED:20180213T144517Z
TRANSP:OPAQUE
END:VEVENT
* Hooks @ RockHounds
<2018-06-16 Sat 19:00-22:00>
:PROPERTIES:
:ID:       QspwPeGjKzgQS_oKnl-5R1Sn@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Hooks @ RockHounds Hooks @ RockHounds

Follow on MiLB First Pitch  https //stza.co/+wX1h-1k

Shop  https //stza.co/+wX1h-V

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Hooks @ RockHounds
END:VALARM
DTSTART:20180617T000000Z
DTEND:20180617T030000Z
UID:QspwPeGjKzgQS_oKnl-5R1Sn@stanza.co
SUMMARY:Hooks @ RockHounds
DESCRIPTION:Hooks @ RockHounds\n\nFollow on MiLB First Pitch: https://stza.co/+wX1h-1k\n\nShop: https://stza.co/+wX1h-V\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144517Z
LAST-MODIFIED:20180213T144517Z
TRANSP:OPAQUE
END:VEVENT
* Hooks @ Missions
<2018-06-17 Sun 16:05-19:05>
:PROPERTIES:
:ID:       xJ2h_HzRRg3fOj5V0np91ZQR@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Hooks @ Missions Hooks @ Missions

Follow on MiLB First Pitch  https //stza.co/+wMtG-21

Shop  https //stza.co/+wMtG-25

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Hooks @ Missions
END:VALARM
DTSTART:20180617T210500Z
DTEND:20180618T000500Z
UID:xJ2h_HzRRg3fOj5V0np91ZQR@stanza.co
SUMMARY:Hooks @ Missions
DESCRIPTION:Hooks @ Missions\n\nFollow on MiLB First Pitch: https://stza.co/+wMtG-21\n\nShop: https://stza.co/+wMtG-25\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144517Z
LAST-MODIFIED:20180213T144517Z
TRANSP:OPAQUE
END:VEVENT
* Hooks @ Missions
<2018-06-18 Mon 19:05-22:05>
:PROPERTIES:
:ID:       S_Yt4i-lI7ktXIr5Vkn-ykn9@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Hooks @ Missions Hooks @ Missions

Follow on MiLB First Pitch  https //stza.co/+wMtH-w

Shop  https //stza.co/+wMtH-2q

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Hooks @ Missions
END:VALARM
DTSTART:20180619T000500Z
DTEND:20180619T030500Z
UID:S_Yt4i-lI7ktXIr5Vkn-ykn9@stanza.co
SUMMARY:Hooks @ Missions
DESCRIPTION:Hooks @ Missions\n\nFollow on MiLB First Pitch: https://stza.co/+wMtH-w\n\nShop: https://stza.co/+wMtH-2q\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144517Z
LAST-MODIFIED:20180213T144517Z
TRANSP:OPAQUE
END:VEVENT
* Hooks @ Missions
<2018-06-19 Tue 19:05-22:05>
:PROPERTIES:
:ID:       NOzQQAH07mcWzPCro4PK5wOr@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Hooks @ Missions Hooks @ Missions

Follow on MiLB First Pitch  https //stza.co/+wMtI-1y

Shop  https //stza.co/+wMtI-3U

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Hooks @ Missions
END:VALARM
DTSTART:20180620T000500Z
DTEND:20180620T030500Z
UID:NOzQQAH07mcWzPCro4PK5wOr@stanza.co
SUMMARY:Hooks @ Missions
DESCRIPTION:Hooks @ Missions\n\nFollow on MiLB First Pitch: https://stza.co/+wMtI-1y\n\nShop: https://stza.co/+wMtI-3U\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144517Z
LAST-MODIFIED:20180213T144517Z
TRANSP:OPAQUE
END:VEVENT
* Hooks @ Missions
<2018-06-20 Wed 19:05-22:05>
:PROPERTIES:
:ID:       Jdvb-NM40tSsgKHJcssvHvpP@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Hooks @ Missions Hooks @ Missions

Follow on MiLB First Pitch  https //stza.co/+wMtJ-2_

Shop  https //stza.co/+wMtJ-3C

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Hooks @ Missions
END:VALARM
DTSTART:20180621T000500Z
DTEND:20180621T030500Z
UID:Jdvb-NM40tSsgKHJcssvHvpP@stanza.co
SUMMARY:Hooks @ Missions
DESCRIPTION:Hooks @ Missions\n\nFollow on MiLB First Pitch: https://stza.co/+wMtJ-2_\n\nShop: https://stza.co/+wMtJ-3C\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144517Z
LAST-MODIFIED:20180213T144517Z
TRANSP:OPAQUE
END:VEVENT
* Hooks vs. RoughRiders
<2018-06-21 Thu 19:05-22:05>
:PROPERTIES:
:ID:       gy_e6AZ00LK7_mC62AZhJa7-@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Hooks vs. RoughRiders Hooks vs. RoughRiders

Follow on MiLB First Pitch  https //stza.co/+xzF$-p

Shop  https //stza.co/+xzF$-X

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Hooks vs. RoughRiders
END:VALARM
DTSTART:20180622T000500Z
DTEND:20180622T030500Z
UID:gy_e6AZ00LK7_mC62AZhJa7-@stanza.co
SUMMARY:Hooks vs. RoughRiders
DESCRIPTION:Hooks vs. RoughRiders\n\nFollow on MiLB First Pitch: https://stza.co/+xzF$-p\n\nShop: https://stza.co/+xzF$-X\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144517Z
LAST-MODIFIED:20180213T144517Z
TRANSP:OPAQUE
END:VEVENT
* Hooks vs. RoughRiders
<2018-06-22 Fri 19:05-22:05>
:PROPERTIES:
:ID:       wVezv1W5T9PZvNJ5jke0TXaX@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Hooks vs. RoughRiders Hooks vs. RoughRiders

Follow on MiLB First Pitch  https //stza.co/+xzG3-f

Shop  https //stza.co/+xzG3-1x

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Hooks vs. RoughRiders
END:VALARM
DTSTART:20180623T000500Z
DTEND:20180623T030500Z
UID:wVezv1W5T9PZvNJ5jke0TXaX@stanza.co
SUMMARY:Hooks vs. RoughRiders
DESCRIPTION:Hooks vs. RoughRiders\n\nFollow on MiLB First Pitch: https://stza.co/+xzG3-f\n\nShop: https://stza.co/+xzG3-1x\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144517Z
LAST-MODIFIED:20180213T144517Z
TRANSP:OPAQUE
END:VEVENT
* Hooks vs. RoughRiders
<2018-06-23 Sat 19:05-22:05>
:PROPERTIES:
:ID:       xTSLOoORogw6EHojgYlBOGcb@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Hooks vs. RoughRiders Hooks vs. RoughRiders

Follow on MiLB First Pitch  https //stza.co/+xzG5-1U

Shop  https //stza.co/+xzG5-14

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Hooks vs. RoughRiders
END:VALARM
DTSTART:20180624T000500Z
DTEND:20180624T030500Z
UID:xTSLOoORogw6EHojgYlBOGcb@stanza.co
SUMMARY:Hooks vs. RoughRiders
DESCRIPTION:Hooks vs. RoughRiders\n\nFollow on MiLB First Pitch: https://stza.co/+xzG5-1U\n\nShop: https://stza.co/+xzG5-14\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144517Z
LAST-MODIFIED:20180213T144517Z
TRANSP:OPAQUE
END:VEVENT
* Hooks vs. RoughRiders
<2018-06-24 Sun 18:05-21:05>
:PROPERTIES:
:ID:       X5-2Gk24QgzYFV-8lxH2wVEQ@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Hooks vs. RoughRiders Hooks vs. RoughRiders

Follow on MiLB First Pitch  https //stza.co/+xzG6-2s

Shop  https //stza.co/+xzG6-39

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Hooks vs. RoughRiders
END:VALARM
DTSTART:20180624T230500Z
DTEND:20180625T020500Z
UID:X5-2Gk24QgzYFV-8lxH2wVEQ@stanza.co
SUMMARY:Hooks vs. RoughRiders
DESCRIPTION:Hooks vs. RoughRiders\n\nFollow on MiLB First Pitch: https://stza.co/+xzG6-2s\n\nShop: https://stza.co/+xzG6-39\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144517Z
LAST-MODIFIED:20180213T144517Z
TRANSP:OPAQUE
END:VEVENT
* Hooks @ Travelers
<2018-06-28 Thu 19:10-22:10>
:PROPERTIES:
:ID:       LYt18LAMfCEDahv8pbF6XDRg@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Hooks @ Travelers Hooks @ Travelers

Follow on MiLB First Pitch  https //stza.co/+v$VX-16

Shop  https //stza.co/+v$VX-3R

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Hooks @ Travelers
END:VALARM
DTSTART:20180629T001000Z
DTEND:20180629T031000Z
UID:LYt18LAMfCEDahv8pbF6XDRg@stanza.co
SUMMARY:Hooks @ Travelers
DESCRIPTION:Hooks @ Travelers\n\nFollow on MiLB First Pitch: https://stza.co/+v$VX-16\n\nShop: https://stza.co/+v$VX-3R\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144517Z
LAST-MODIFIED:20180213T144517Z
TRANSP:OPAQUE
END:VEVENT
* Hooks @ Travelers
<2018-06-29 Fri 19:10-22:10>
:PROPERTIES:
:ID:       iOUY-tnq_IMQvpz3T71WE0Qd@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Hooks @ Travelers Hooks @ Travelers

Follow on MiLB First Pitch  https //stza.co/+v$VY-3T

Shop  https //stza.co/+v$VY-3B

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Hooks @ Travelers
END:VALARM
DTSTART:20180630T001000Z
DTEND:20180630T031000Z
UID:iOUY-tnq_IMQvpz3T71WE0Qd@stanza.co
SUMMARY:Hooks @ Travelers
DESCRIPTION:Hooks @ Travelers\n\nFollow on MiLB First Pitch: https://stza.co/+v$VY-3T\n\nShop: https://stza.co/+v$VY-3B\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144517Z
LAST-MODIFIED:20180213T144517Z
TRANSP:OPAQUE
END:VEVENT
* Hooks @ Travelers
<2018-06-30 Sat 18:10-21:10>
:PROPERTIES:
:ID:       fpwFbhyYJOv-wi9KzIjfbZsG@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Hooks @ Travelers Hooks @ Travelers

Follow on MiLB First Pitch  https //stza.co/+v$VZ-d

Shop  https //stza.co/+v$VZ-1i

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Hooks @ Travelers
END:VALARM
DTSTART:20180630T231000Z
DTEND:20180701T021000Z
UID:fpwFbhyYJOv-wi9KzIjfbZsG@stanza.co
SUMMARY:Hooks @ Travelers
DESCRIPTION:Hooks @ Travelers\n\nFollow on MiLB First Pitch: https://stza.co/+v$VZ-d\n\nShop: https://stza.co/+v$VZ-1i\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144517Z
LAST-MODIFIED:20180213T144517Z
TRANSP:OPAQUE
END:VEVENT
* Hooks @ Naturals
<2018-07-01 Sun 16:05-19:05>
:PROPERTIES:
:ID:       u_lY5G1mBVZNbnc0nSnl0eUR@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Hooks @ Naturals Hooks @ Naturals

Follow on MiLB First Pitch  https //stza.co/+wh$Y-2H

Shop  https //stza.co/+wh$Y-3R

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Hooks @ Naturals
END:VALARM
DTSTART:20180701T210500Z
DTEND:20180702T000500Z
UID:u_lY5G1mBVZNbnc0nSnl0eUR@stanza.co
SUMMARY:Hooks @ Naturals
DESCRIPTION:Hooks @ Naturals\n\nFollow on MiLB First Pitch: https://stza.co/+wh$Y-2H\n\nShop: https://stza.co/+wh$Y-3R\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144517Z
LAST-MODIFIED:20180213T144517Z
TRANSP:OPAQUE
END:VEVENT
* Hooks @ Naturals
<2018-07-02 Mon 18:35-21:35>
:PROPERTIES:
:ID:       oK86otB9kkpNrWxYTyqai6Mk@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Hooks @ Naturals Hooks @ Naturals

Follow on MiLB First Pitch  https //stza.co/+wh$Z-2C

Shop  https //stza.co/+wh$Z-3P

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Hooks @ Naturals
END:VALARM
DTSTART:20180702T233500Z
DTEND:20180703T023500Z
UID:oK86otB9kkpNrWxYTyqai6Mk@stanza.co
SUMMARY:Hooks @ Naturals
DESCRIPTION:Hooks @ Naturals\n\nFollow on MiLB First Pitch: https://stza.co/+wh$Z-2C\n\nShop: https://stza.co/+wh$Z-3P\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144517Z
LAST-MODIFIED:20180213T144517Z
TRANSP:OPAQUE
END:VEVENT
* Hooks @ Naturals
<2018-07-03 Tue 18:35-21:35>
:PROPERTIES:
:ID:       mDRgsvkeGYonYouKMreT7MiV@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Hooks @ Naturals Hooks @ Naturals

Follow on MiLB First Pitch  https //stza.co/+wi00-38

Shop  https //stza.co/+wi00-i

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Hooks @ Naturals
END:VALARM
DTSTART:20180703T233500Z
DTEND:20180704T023500Z
UID:mDRgsvkeGYonYouKMreT7MiV@stanza.co
SUMMARY:Hooks @ Naturals
DESCRIPTION:Hooks @ Naturals\n\nFollow on MiLB First Pitch: https://stza.co/+wi00-38\n\nShop: https://stza.co/+wi00-i\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144517Z
LAST-MODIFIED:20180213T144517Z
TRANSP:OPAQUE
END:VEVENT
* Hooks vs. Travelers
<2018-07-04 Wed 19:05-22:05>
:PROPERTIES:
:ID:       b3Rzs161fbW2B_VzaFovieK4@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Hooks vs. Travelers Hooks vs. Travelers

Follow on MiLB First Pitch  https //stza.co/+xzG9-1o

Shop  https //stza.co/+xzG9-X

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Hooks vs. Travelers
END:VALARM
DTSTART:20180705T000500Z
DTEND:20180705T030500Z
UID:b3Rzs161fbW2B_VzaFovieK4@stanza.co
SUMMARY:Hooks vs. Travelers
DESCRIPTION:Hooks vs. Travelers\n\nFollow on MiLB First Pitch: https://stza.co/+xzG9-1o\n\nShop: https://stza.co/+xzG9-X\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144517Z
LAST-MODIFIED:20180213T144517Z
TRANSP:OPAQUE
END:VEVENT
* Hooks vs. Travelers
<2018-07-05 Thu 19:05-22:05>
:PROPERTIES:
:ID:       SsBa4I31ndmYyAikbNh_UAKq@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Hooks vs. Travelers Hooks vs. Travelers

Follow on MiLB First Pitch  https //stza.co/+xzGb-18

Shop  https //stza.co/+xzGb-38

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Hooks vs. Travelers
END:VALARM
DTSTART:20180706T000500Z
DTEND:20180706T030500Z
UID:SsBa4I31ndmYyAikbNh_UAKq@stanza.co
SUMMARY:Hooks vs. Travelers
DESCRIPTION:Hooks vs. Travelers\n\nFollow on MiLB First Pitch: https://stza.co/+xzGb-18\n\nShop: https://stza.co/+xzGb-38\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144517Z
LAST-MODIFIED:20180213T144517Z
TRANSP:OPAQUE
END:VEVENT
* Hooks vs. Travelers
<2018-07-06 Fri 19:05-22:05>
:PROPERTIES:
:ID:       Ez2mPJXP7Wn4LeQH7wQTXKq8@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Hooks vs. Travelers Hooks vs. Travelers

Follow on MiLB First Pitch  https //stza.co/+xzGe-x

Shop  https //stza.co/+xzGe-q

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Hooks vs. Travelers
END:VALARM
DTSTART:20180707T000500Z
DTEND:20180707T030500Z
UID:Ez2mPJXP7Wn4LeQH7wQTXKq8@stanza.co
SUMMARY:Hooks vs. Travelers
DESCRIPTION:Hooks vs. Travelers\n\nFollow on MiLB First Pitch: https://stza.co/+xzGe-x\n\nShop: https://stza.co/+xzGe-q\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144517Z
LAST-MODIFIED:20180213T144517Z
TRANSP:OPAQUE
END:VEVENT
* Hooks vs. Naturals
<2018-07-07 Sat 19:05-22:05>
:PROPERTIES:
:ID:       Ja1cpKh2KDBMVM6v5F9_GuaU@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Hooks vs. Naturals Hooks vs. Naturals

Follow on MiLB First Pitch  https //stza.co/+xzGf-2s

Shop  https //stza.co/+xzGf-23

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Hooks vs. Naturals
END:VALARM
DTSTART:20180708T000500Z
DTEND:20180708T030500Z
UID:Ja1cpKh2KDBMVM6v5F9_GuaU@stanza.co
SUMMARY:Hooks vs. Naturals
DESCRIPTION:Hooks vs. Naturals\n\nFollow on MiLB First Pitch: https://stza.co/+xzGf-2s\n\nShop: https://stza.co/+xzGf-23\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144517Z
LAST-MODIFIED:20180213T144517Z
TRANSP:OPAQUE
END:VEVENT
* Hooks vs. Naturals
<2018-07-08 Sun 18:05-21:05>
:PROPERTIES:
:ID:       xCGnGXP3TCEzMSU3_mXPc7Qt@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Hooks vs. Naturals Hooks vs. Naturals

Follow on MiLB First Pitch  https //stza.co/+xzGi-E

Shop  https //stza.co/+xzGi-2q

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Hooks vs. Naturals
END:VALARM
DTSTART:20180708T230500Z
DTEND:20180709T020500Z
UID:xCGnGXP3TCEzMSU3_mXPc7Qt@stanza.co
SUMMARY:Hooks vs. Naturals
DESCRIPTION:Hooks vs. Naturals\n\nFollow on MiLB First Pitch: https://stza.co/+xzGi-E\n\nShop: https://stza.co/+xzGi-2q\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144517Z
LAST-MODIFIED:20180213T144517Z
TRANSP:OPAQUE
END:VEVENT
* Hooks vs. Naturals
<2018-07-09 Mon 19:05-22:05>
:PROPERTIES:
:ID:       d9A3MrlofculyGxf8qwJtygl@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Hooks vs. Naturals Hooks vs. Naturals

Follow on MiLB First Pitch  https //stza.co/+xzGj-1p

Shop  https //stza.co/+xzGj-2k

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Hooks vs. Naturals
END:VALARM
DTSTART:20180710T000500Z
DTEND:20180710T030500Z
UID:d9A3MrlofculyGxf8qwJtygl@stanza.co
SUMMARY:Hooks vs. Naturals
DESCRIPTION:Hooks vs. Naturals\n\nFollow on MiLB First Pitch: https://stza.co/+xzGj-1p\n\nShop: https://stza.co/+xzGj-2k\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144517Z
LAST-MODIFIED:20180213T144517Z
TRANSP:OPAQUE
END:VEVENT
* Hooks @ RockHounds
<2018-07-11 Wed 18:30-21:30>
:PROPERTIES:
:ID:       y37_Kpo-uoo4ZC53pbshdRCM@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Hooks @ RockHounds Hooks @ RockHounds

Follow on MiLB First Pitch  https //stza.co/+wX1i-1L

Shop  https //stza.co/+wX1i-P

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Hooks @ RockHounds
END:VALARM
DTSTART:20180711T233000Z
DTEND:20180712T023000Z
UID:y37_Kpo-uoo4ZC53pbshdRCM@stanza.co
SUMMARY:Hooks @ RockHounds
DESCRIPTION:Hooks @ RockHounds\n\nFollow on MiLB First Pitch: https://stza.co/+wX1i-1L\n\nShop: https://stza.co/+wX1i-P\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144517Z
LAST-MODIFIED:20180213T144517Z
TRANSP:OPAQUE
END:VEVENT
* Hooks @ RockHounds
<2018-07-12 Thu 19:00-22:00>
:PROPERTIES:
:ID:       6ofrZBhDJOMsp5xoH6Ob7yNU@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Hooks @ RockHounds Hooks @ RockHounds

Follow on MiLB First Pitch  https //stza.co/+wX1j-1N

Shop  https //stza.co/+wX1j-3f

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Hooks @ RockHounds
END:VALARM
DTSTART:20180713T000000Z
DTEND:20180713T030000Z
UID:6ofrZBhDJOMsp5xoH6Ob7yNU@stanza.co
SUMMARY:Hooks @ RockHounds
DESCRIPTION:Hooks @ RockHounds\n\nFollow on MiLB First Pitch: https://stza.co/+wX1j-1N\n\nShop: https://stza.co/+wX1j-3f\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144517Z
LAST-MODIFIED:20180213T144517Z
TRANSP:OPAQUE
END:VEVENT
* Hooks @ RockHounds
<2018-07-13 Fri 19:00-22:00>
:PROPERTIES:
:ID:       W15c95DvESG--S6jlXE5Biw6@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Hooks @ RockHounds Hooks @ RockHounds

Follow on MiLB First Pitch  https //stza.co/+wX1k-2o

Shop  https //stza.co/+wX1k-h

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Hooks @ RockHounds
END:VALARM
DTSTART:20180714T000000Z
DTEND:20180714T030000Z
UID:W15c95DvESG--S6jlXE5Biw6@stanza.co
SUMMARY:Hooks @ RockHounds
DESCRIPTION:Hooks @ RockHounds\n\nFollow on MiLB First Pitch: https://stza.co/+wX1k-2o\n\nShop: https://stza.co/+wX1k-h\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144517Z
LAST-MODIFIED:20180213T144517Z
TRANSP:OPAQUE
END:VEVENT
* Hooks @ RockHounds
<2018-07-14 Sat 19:00-22:00>
:PROPERTIES:
:ID:       TPBgW7VkBiyFvJ3B5R_gros0@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Hooks @ RockHounds Hooks @ RockHounds

Follow on MiLB First Pitch  https //stza.co/+wX1l-Z

Shop  https //stza.co/+wX1l-3S

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Hooks @ RockHounds
END:VALARM
DTSTART:20180715T000000Z
DTEND:20180715T030000Z
UID:TPBgW7VkBiyFvJ3B5R_gros0@stanza.co
SUMMARY:Hooks @ RockHounds
DESCRIPTION:Hooks @ RockHounds\n\nFollow on MiLB First Pitch: https://stza.co/+wX1l-Z\n\nShop: https://stza.co/+wX1l-3S\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144517Z
LAST-MODIFIED:20180213T144517Z
TRANSP:OPAQUE
END:VEVENT
* Hooks vs. RoughRiders
<2018-07-15 Sun 18:05-21:05>
:PROPERTIES:
:ID:       BBKd_9vxQ5TOIQUswr2OBVUs@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Hooks vs. RoughRiders Hooks vs. RoughRiders

Follow on MiLB First Pitch  https //stza.co/+xzGm-3U

Shop  https //stza.co/+xzGm-2v

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Hooks vs. RoughRiders
END:VALARM
DTSTART:20180715T230500Z
DTEND:20180716T020500Z
UID:BBKd_9vxQ5TOIQUswr2OBVUs@stanza.co
SUMMARY:Hooks vs. RoughRiders
DESCRIPTION:Hooks vs. RoughRiders\n\nFollow on MiLB First Pitch: https://stza.co/+xzGm-3U\n\nShop: https://stza.co/+xzGm-2v\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144517Z
LAST-MODIFIED:20180213T144517Z
TRANSP:OPAQUE
END:VEVENT
* Hooks vs. RoughRiders
<2018-07-16 Mon 19:05-22:05>
:PROPERTIES:
:ID:       tf7lqJT3yYL0yxRjf8pR7G1F@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Hooks vs. RoughRiders Hooks vs. RoughRiders

Follow on MiLB First Pitch  https //stza.co/+xzGn-3m

Shop  https //stza.co/+xzGn-_

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Hooks vs. RoughRiders
END:VALARM
DTSTART:20180717T000500Z
DTEND:20180717T030500Z
UID:tf7lqJT3yYL0yxRjf8pR7G1F@stanza.co
SUMMARY:Hooks vs. RoughRiders
DESCRIPTION:Hooks vs. RoughRiders\n\nFollow on MiLB First Pitch: https://stza.co/+xzGn-3m\n\nShop: https://stza.co/+xzGn-_\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144517Z
LAST-MODIFIED:20180213T144517Z
TRANSP:OPAQUE
END:VEVENT
* Hooks vs. RoughRiders
<2018-07-17 Tue 19:05-22:05>
:PROPERTIES:
:ID:       _cEGew11WFZq9PN-j43NQj50@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Hooks vs. RoughRiders Hooks vs. RoughRiders

Follow on MiLB First Pitch  https //stza.co/+xzGq-3E

Shop  https //stza.co/+xzGq-1W

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Hooks vs. RoughRiders
END:VALARM
DTSTART:20180718T000500Z
DTEND:20180718T030500Z
UID:_cEGew11WFZq9PN-j43NQj50@stanza.co
SUMMARY:Hooks vs. RoughRiders
DESCRIPTION:Hooks vs. RoughRiders\n\nFollow on MiLB First Pitch: https://stza.co/+xzGq-3E\n\nShop: https://stza.co/+xzGq-1W\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144517Z
LAST-MODIFIED:20180213T144517Z
TRANSP:OPAQUE
END:VEVENT
* Hooks vs. RoughRiders
<2018-07-18 Wed 19:05-22:05>
:PROPERTIES:
:ID:       5c4eor8b1eO4rw05k-sP-4UD@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Hooks vs. RoughRiders Hooks vs. RoughRiders

Follow on MiLB First Pitch  https //stza.co/+xzGs-2C

Shop  https //stza.co/+xzGs-3M

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Hooks vs. RoughRiders
END:VALARM
DTSTART:20180719T000500Z
DTEND:20180719T030500Z
UID:5c4eor8b1eO4rw05k-sP-4UD@stanza.co
SUMMARY:Hooks vs. RoughRiders
DESCRIPTION:Hooks vs. RoughRiders\n\nFollow on MiLB First Pitch: https://stza.co/+xzGs-2C\n\nShop: https://stza.co/+xzGs-3M\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144517Z
LAST-MODIFIED:20180213T144517Z
TRANSP:OPAQUE
END:VEVENT
* Hooks @ RockHounds
<2018-07-19 Thu 19:00-22:00>
:PROPERTIES:
:ID:       q0j_0FbJBlGWwVpwb0tFw_Wv@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Hooks @ RockHounds Hooks @ RockHounds

Follow on MiLB First Pitch  https //stza.co/+wX1m-7

Shop  https //stza.co/+wX1m-3H

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Hooks @ RockHounds
END:VALARM
DTSTART:20180720T000000Z
DTEND:20180720T030000Z
UID:q0j_0FbJBlGWwVpwb0tFw_Wv@stanza.co
SUMMARY:Hooks @ RockHounds
DESCRIPTION:Hooks @ RockHounds\n\nFollow on MiLB First Pitch: https://stza.co/+wX1m-7\n\nShop: https://stza.co/+wX1m-3H\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144517Z
LAST-MODIFIED:20180213T144517Z
TRANSP:OPAQUE
END:VEVENT
* Hooks @ RockHounds
<2018-07-20 Fri 19:00-22:00>
:PROPERTIES:
:ID:       yJ-Ji3lNM-vE-CW_fGk379-o@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Hooks @ RockHounds Hooks @ RockHounds

Follow on MiLB First Pitch  https //stza.co/+wX1o-3p

Shop  https //stza.co/+wX1o-3z

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Hooks @ RockHounds
END:VALARM
DTSTART:20180721T000000Z
DTEND:20180721T030000Z
UID:yJ-Ji3lNM-vE-CW_fGk379-o@stanza.co
SUMMARY:Hooks @ RockHounds
DESCRIPTION:Hooks @ RockHounds\n\nFollow on MiLB First Pitch: https://stza.co/+wX1o-3p\n\nShop: https://stza.co/+wX1o-3z\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144517Z
LAST-MODIFIED:20180213T144517Z
TRANSP:OPAQUE
END:VEVENT
* Hooks @ RockHounds
<2018-07-21 Sat 19:00-22:00>
:PROPERTIES:
:ID:       nNvUoZjUpjcMUdyMGToA313Y@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Hooks @ RockHounds Hooks @ RockHounds

Follow on MiLB First Pitch  https //stza.co/+wX1p-13

Shop  https //stza.co/+wX1p-f

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Hooks @ RockHounds
END:VALARM
DTSTART:20180722T000000Z
DTEND:20180722T030000Z
UID:nNvUoZjUpjcMUdyMGToA313Y@stanza.co
SUMMARY:Hooks @ RockHounds
DESCRIPTION:Hooks @ RockHounds\n\nFollow on MiLB First Pitch: https://stza.co/+wX1p-13\n\nShop: https://stza.co/+wX1p-f\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144517Z
LAST-MODIFIED:20180213T144517Z
TRANSP:OPAQUE
END:VEVENT
* Hooks @ RockHounds
<2018-07-22 Sun 14:00-17:00>
:PROPERTIES:
:ID:       XVFWK0idZ0uKrWLJNpd9_4oF@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Hooks @ RockHounds Hooks @ RockHounds

Follow on MiLB First Pitch  https //stza.co/+wX1q-20

Shop  https //stza.co/+wX1q-j

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Hooks @ RockHounds
END:VALARM
DTSTART:20180722T190000Z
DTEND:20180722T220000Z
UID:XVFWK0idZ0uKrWLJNpd9_4oF@stanza.co
SUMMARY:Hooks @ RockHounds
DESCRIPTION:Hooks @ RockHounds\n\nFollow on MiLB First Pitch: https://stza.co/+wX1q-20\n\nShop: https://stza.co/+wX1q-j\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144517Z
LAST-MODIFIED:20180213T144517Z
TRANSP:OPAQUE
END:VEVENT
* Hooks @ Missions
<2018-07-23 Mon 19:05-22:05>
:PROPERTIES:
:ID:       xNqcsXLC6B13ieLhPIO95Hv2@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Hooks @ Missions Hooks @ Missions

Follow on MiLB First Pitch  https //stza.co/+wMtK-1d

Shop  https //stza.co/+wMtK-1P

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Hooks @ Missions
END:VALARM
DTSTART:20180724T000500Z
DTEND:20180724T030500Z
UID:xNqcsXLC6B13ieLhPIO95Hv2@stanza.co
SUMMARY:Hooks @ Missions
DESCRIPTION:Hooks @ Missions\n\nFollow on MiLB First Pitch: https://stza.co/+wMtK-1d\n\nShop: https://stza.co/+wMtK-1P\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144517Z
LAST-MODIFIED:20180213T144517Z
TRANSP:OPAQUE
END:VEVENT
* Hooks @ Missions
<2018-07-24 Tue 19:05-22:05>
:PROPERTIES:
:ID:       wrBJLwc1dCJtDptBcRQ9nTqT@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Hooks @ Missions Hooks @ Missions

Follow on MiLB First Pitch  https //stza.co/+wMtL-2y

Shop  https //stza.co/+wMtL-2R

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Hooks @ Missions
END:VALARM
DTSTART:20180725T000500Z
DTEND:20180725T030500Z
UID:wrBJLwc1dCJtDptBcRQ9nTqT@stanza.co
SUMMARY:Hooks @ Missions
DESCRIPTION:Hooks @ Missions\n\nFollow on MiLB First Pitch: https://stza.co/+wMtL-2y\n\nShop: https://stza.co/+wMtL-2R\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144517Z
LAST-MODIFIED:20180213T144517Z
TRANSP:OPAQUE
END:VEVENT
* Hooks @ Missions
<2018-07-25 Wed 19:05-22:05>
:PROPERTIES:
:ID:       Sz49AKYfJ11G9Z3iZKmSME1L@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Hooks @ Missions Hooks @ Missions

Follow on MiLB First Pitch  https //stza.co/+wMtM-1E

Shop  https //stza.co/+wMtM-N

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Hooks @ Missions
END:VALARM
DTSTART:20180726T000500Z
DTEND:20180726T030500Z
UID:Sz49AKYfJ11G9Z3iZKmSME1L@stanza.co
SUMMARY:Hooks @ Missions
DESCRIPTION:Hooks @ Missions\n\nFollow on MiLB First Pitch: https://stza.co/+wMtM-1E\n\nShop: https://stza.co/+wMtM-N\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144517Z
LAST-MODIFIED:20180213T144517Z
TRANSP:OPAQUE
END:VEVENT
* Hooks vs. RockHounds
<2018-07-26 Thu 19:05-22:05>
:PROPERTIES:
:ID:       blTdPKYm8LrUmIJoLHUBnPYg@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Hooks vs. RockHounds Hooks vs. RockHounds

Follow on MiLB First Pitch  https //stza.co/+xzGv-a

Shop  https //stza.co/+xzGv-2H

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Hooks vs. RockHounds
END:VALARM
DTSTART:20180727T000500Z
DTEND:20180727T030500Z
UID:blTdPKYm8LrUmIJoLHUBnPYg@stanza.co
SUMMARY:Hooks vs. RockHounds
DESCRIPTION:Hooks vs. RockHounds\n\nFollow on MiLB First Pitch: https://stza.co/+xzGv-a\n\nShop: https://stza.co/+xzGv-2H\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144517Z
LAST-MODIFIED:20180213T144517Z
TRANSP:OPAQUE
END:VEVENT
* Hooks vs. RockHounds
<2018-07-27 Fri 19:05-22:05>
:PROPERTIES:
:ID:       -EwzE35DvbVHBD_X_-WBu3nY@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Hooks vs. RockHounds Hooks vs. RockHounds

Follow on MiLB First Pitch  https //stza.co/+xzGy-1_

Shop  https //stza.co/+xzGy-1t

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Hooks vs. RockHounds
END:VALARM
DTSTART:20180728T000500Z
DTEND:20180728T030500Z
UID:-EwzE35DvbVHBD_X_-WBu3nY@stanza.co
SUMMARY:Hooks vs. RockHounds
DESCRIPTION:Hooks vs. RockHounds\n\nFollow on MiLB First Pitch: https://stza.co/+xzGy-1_\n\nShop: https://stza.co/+xzGy-1t\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144517Z
LAST-MODIFIED:20180213T144517Z
TRANSP:OPAQUE
END:VEVENT
* Hooks vs. RockHounds
<2018-07-28 Sat 19:05-22:05>
:PROPERTIES:
:ID:       WVNEBcwTf_uxs2GzJwVFpV71@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Hooks vs. RockHounds Hooks vs. RockHounds

Follow on MiLB First Pitch  https //stza.co/+xzGz-3d

Shop  https //stza.co/+xzGz-1H

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Hooks vs. RockHounds
END:VALARM
DTSTART:20180729T000500Z
DTEND:20180729T030500Z
UID:WVNEBcwTf_uxs2GzJwVFpV71@stanza.co
SUMMARY:Hooks vs. RockHounds
DESCRIPTION:Hooks vs. RockHounds\n\nFollow on MiLB First Pitch: https://stza.co/+xzGz-3d\n\nShop: https://stza.co/+xzGz-1H\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144517Z
LAST-MODIFIED:20180213T144517Z
TRANSP:OPAQUE
END:VEVENT
* Hooks vs. RockHounds
<2018-07-29 Sun 18:05-21:05>
:PROPERTIES:
:ID:       lwd1sbHYww2qKKpauO-soQ28@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Hooks vs. RockHounds Hooks vs. RockHounds

Follow on MiLB First Pitch  https //stza.co/+xzGC-W

Shop  https //stza.co/+xzGC-X

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Hooks vs. RockHounds
END:VALARM
DTSTART:20180729T230500Z
DTEND:20180730T020500Z
UID:lwd1sbHYww2qKKpauO-soQ28@stanza.co
SUMMARY:Hooks vs. RockHounds
DESCRIPTION:Hooks vs. RockHounds\n\nFollow on MiLB First Pitch: https://stza.co/+xzGC-W\n\nShop: https://stza.co/+xzGC-X\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144517Z
LAST-MODIFIED:20180213T144517Z
TRANSP:OPAQUE
END:VEVENT
* Hooks vs. Missions
<2018-07-30 Mon 19:05-22:05>
:PROPERTIES:
:ID:       FBz6yn0Qe3YH_Fl5fdj99tbD@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Hooks vs. Missions Hooks vs. Missions

Follow on MiLB First Pitch  https //stza.co/+xzGE-2r

Shop  https //stza.co/+xzGE-2A

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Hooks vs. Missions
END:VALARM
DTSTART:20180731T000500Z
DTEND:20180731T030500Z
UID:FBz6yn0Qe3YH_Fl5fdj99tbD@stanza.co
SUMMARY:Hooks vs. Missions
DESCRIPTION:Hooks vs. Missions\n\nFollow on MiLB First Pitch: https://stza.co/+xzGE-2r\n\nShop: https://stza.co/+xzGE-2A\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144517Z
LAST-MODIFIED:20180213T144517Z
TRANSP:OPAQUE
END:VEVENT
* Hooks vs. Missions
<2018-07-31 Tue 19:05-22:05>
:PROPERTIES:
:ID:       HC8DpnoF1yFnF_0IJ1tE7Tgb@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Hooks vs. Missions Hooks vs. Missions

Follow on MiLB First Pitch  https //stza.co/+xzGF-2g

Shop  https //stza.co/+xzGF-z

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Hooks vs. Missions
END:VALARM
DTSTART:20180801T000500Z
DTEND:20180801T030500Z
UID:HC8DpnoF1yFnF_0IJ1tE7Tgb@stanza.co
SUMMARY:Hooks vs. Missions
DESCRIPTION:Hooks vs. Missions\n\nFollow on MiLB First Pitch: https://stza.co/+xzGF-2g\n\nShop: https://stza.co/+xzGF-z\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144517Z
LAST-MODIFIED:20180213T144517Z
TRANSP:OPAQUE
END:VEVENT
* Hooks vs. Missions
<2018-08-01 Wed 19:05-22:05>
:PROPERTIES:
:ID:       -3iJr9xl685a8QnxwJi7fa9_@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Hooks vs. Missions Hooks vs. Missions

Follow on MiLB First Pitch  https //stza.co/+xzGH-1L

Shop  https //stza.co/+xzGH-e

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Hooks vs. Missions
END:VALARM
DTSTART:20180802T000500Z
DTEND:20180802T030500Z
UID:-3iJr9xl685a8QnxwJi7fa9_@stanza.co
SUMMARY:Hooks vs. Missions
DESCRIPTION:Hooks vs. Missions\n\nFollow on MiLB First Pitch: https://stza.co/+xzGH-1L\n\nShop: https://stza.co/+xzGH-e\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144517Z
LAST-MODIFIED:20180213T144517Z
TRANSP:OPAQUE
END:VEVENT
* Hooks @ RoughRiders
<2018-08-02 Thu 19:05-22:05>
:PROPERTIES:
:ID:       5tOx603e-tirYiv9_fwVRNqm@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Hooks @ RoughRiders Hooks @ RoughRiders

Follow on MiLB First Pitch  https //stza.co/+wY7t-2E

Shop  https //stza.co/+wY7t-36

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Hooks @ RoughRiders
END:VALARM
DTSTART:20180803T000500Z
DTEND:20180803T030500Z
UID:5tOx603e-tirYiv9_fwVRNqm@stanza.co
SUMMARY:Hooks @ RoughRiders
DESCRIPTION:Hooks @ RoughRiders\n\nFollow on MiLB First Pitch: https://stza.co/+wY7t-2E\n\nShop: https://stza.co/+wY7t-36\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144517Z
LAST-MODIFIED:20180213T144517Z
TRANSP:OPAQUE
END:VEVENT
* Hooks @ RoughRiders
<2018-08-03 Fri 19:05-22:05>
:PROPERTIES:
:ID:       -Ld_W4DOY_8ui4u2UFBcaC5J@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Hooks @ RoughRiders Hooks @ RoughRiders

Follow on MiLB First Pitch  https //stza.co/+wY7u-3b

Shop  https //stza.co/+wY7u-1Y

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Hooks @ RoughRiders
END:VALARM
DTSTART:20180804T000500Z
DTEND:20180804T030500Z
UID:-Ld_W4DOY_8ui4u2UFBcaC5J@stanza.co
SUMMARY:Hooks @ RoughRiders
DESCRIPTION:Hooks @ RoughRiders\n\nFollow on MiLB First Pitch: https://stza.co/+wY7u-3b\n\nShop: https://stza.co/+wY7u-1Y\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144517Z
LAST-MODIFIED:20180213T144517Z
TRANSP:OPAQUE
END:VEVENT
* Hooks @ RoughRiders
<2018-08-04 Sat 19:05-22:05>
:PROPERTIES:
:ID:       mLF0FOEIP0Y4UmBKG-7L4swI@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Hooks @ RoughRiders Hooks @ RoughRiders

Follow on MiLB First Pitch  https //stza.co/+wY7v-3I

Shop  https //stza.co/+wY7v-3a

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Hooks @ RoughRiders
END:VALARM
DTSTART:20180805T000500Z
DTEND:20180805T030500Z
UID:mLF0FOEIP0Y4UmBKG-7L4swI@stanza.co
SUMMARY:Hooks @ RoughRiders
DESCRIPTION:Hooks @ RoughRiders\n\nFollow on MiLB First Pitch: https://stza.co/+wY7v-3I\n\nShop: https://stza.co/+wY7v-3a\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144517Z
LAST-MODIFIED:20180213T144517Z
TRANSP:OPAQUE
END:VEVENT
* Hooks @ RoughRiders
<2018-08-05 Sun 19:05-22:05>
:PROPERTIES:
:ID:       _OL9VtcRNdblroLpdAw89xoj@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Hooks @ RoughRiders Hooks @ RoughRiders

Follow on MiLB First Pitch  https //stza.co/+wY7w-2m

Shop  https //stza.co/+wY7w-3K

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Hooks @ RoughRiders
END:VALARM
DTSTART:20180806T000500Z
DTEND:20180806T030500Z
UID:_OL9VtcRNdblroLpdAw89xoj@stanza.co
SUMMARY:Hooks @ RoughRiders
DESCRIPTION:Hooks @ RoughRiders\n\nFollow on MiLB First Pitch: https://stza.co/+wY7w-2m\n\nShop: https://stza.co/+wY7w-3K\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144517Z
LAST-MODIFIED:20180213T144517Z
TRANSP:OPAQUE
END:VEVENT
* Hooks vs. Drillers
<2018-08-07 Tue 19:05-22:05>
:PROPERTIES:
:ID:       NGdoKIOAqKOgic8Z0P0Zbfb_@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Hooks vs. Drillers Hooks vs. Drillers

Follow on MiLB First Pitch  https //stza.co/+xzGK-12

Shop  https //stza.co/+xzGK-1Y

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Hooks vs. Drillers
END:VALARM
DTSTART:20180808T000500Z
DTEND:20180808T030500Z
UID:NGdoKIOAqKOgic8Z0P0Zbfb_@stanza.co
SUMMARY:Hooks vs. Drillers
DESCRIPTION:Hooks vs. Drillers\n\nFollow on MiLB First Pitch: https://stza.co/+xzGK-12\n\nShop: https://stza.co/+xzGK-1Y\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144517Z
LAST-MODIFIED:20180213T144517Z
TRANSP:OPAQUE
END:VEVENT
* Hooks vs. Drillers
<2018-08-08 Wed 19:05-22:05>
:PROPERTIES:
:ID:       vGiKM-GLFOgs1zTnD9WDMEH7@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Hooks vs. Drillers Hooks vs. Drillers

Follow on MiLB First Pitch  https //stza.co/+xzGL-1p

Shop  https //stza.co/+xzGL-2Z

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Hooks vs. Drillers
END:VALARM
DTSTART:20180809T000500Z
DTEND:20180809T030500Z
UID:vGiKM-GLFOgs1zTnD9WDMEH7@stanza.co
SUMMARY:Hooks vs. Drillers
DESCRIPTION:Hooks vs. Drillers\n\nFollow on MiLB First Pitch: https://stza.co/+xzGL-1p\n\nShop: https://stza.co/+xzGL-2Z\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144517Z
LAST-MODIFIED:20180213T144517Z
TRANSP:OPAQUE
END:VEVENT
* Hooks vs. Drillers
<2018-08-09 Thu 19:05-22:05>
:PROPERTIES:
:ID:       y3vK1f-uaPR_yYQdhWQKdhZr@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Hooks vs. Drillers Hooks vs. Drillers

Follow on MiLB First Pitch  https //stza.co/+xzGN-3Q

Shop  https //stza.co/+xzGN-6

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Hooks vs. Drillers
END:VALARM
DTSTART:20180810T000500Z
DTEND:20180810T030500Z
UID:y3vK1f-uaPR_yYQdhWQKdhZr@stanza.co
SUMMARY:Hooks vs. Drillers
DESCRIPTION:Hooks vs. Drillers\n\nFollow on MiLB First Pitch: https://stza.co/+xzGN-3Q\n\nShop: https://stza.co/+xzGN-6\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144517Z
LAST-MODIFIED:20180213T144517Z
TRANSP:OPAQUE
END:VEVENT
* Hooks vs. Cardinals
<2018-08-10 Fri 19:05-22:05>
:PROPERTIES:
:ID:       I-WtYr2E8vU0A4cSsnhSlHha@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Hooks vs. Cardinals Hooks vs. Cardinals

Follow on MiLB First Pitch  https //stza.co/+xzGQ-1U

Shop  https //stza.co/+xzGQ-3i

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Hooks vs. Cardinals
END:VALARM
DTSTART:20180811T000500Z
DTEND:20180811T030500Z
UID:I-WtYr2E8vU0A4cSsnhSlHha@stanza.co
SUMMARY:Hooks vs. Cardinals
DESCRIPTION:Hooks vs. Cardinals\n\nFollow on MiLB First Pitch: https://stza.co/+xzGQ-1U\n\nShop: https://stza.co/+xzGQ-3i\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144517Z
LAST-MODIFIED:20180213T144517Z
TRANSP:OPAQUE
END:VEVENT
* Hooks vs. Cardinals
<2018-08-11 Sat 19:05-22:05>
:PROPERTIES:
:ID:       UzP-c3hrvhAA8pGeWGln4K6y@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Hooks vs. Cardinals Hooks vs. Cardinals

Follow on MiLB First Pitch  https //stza.co/+xzGS-Y

Shop  https //stza.co/+xzGS-1q

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Hooks vs. Cardinals
END:VALARM
DTSTART:20180812T000500Z
DTEND:20180812T030500Z
UID:UzP-c3hrvhAA8pGeWGln4K6y@stanza.co
SUMMARY:Hooks vs. Cardinals
DESCRIPTION:Hooks vs. Cardinals\n\nFollow on MiLB First Pitch: https://stza.co/+xzGS-Y\n\nShop: https://stza.co/+xzGS-1q\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144517Z
LAST-MODIFIED:20180213T144517Z
TRANSP:OPAQUE
END:VEVENT
* Hooks vs. Cardinals
<2018-08-12 Sun 18:05-21:05>
:PROPERTIES:
:ID:       r3PHvlYbUL9uvEcltKxrBXbF@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Hooks vs. Cardinals Hooks vs. Cardinals

Follow on MiLB First Pitch  https //stza.co/+xzGT-2n

Shop  https //stza.co/+xzGT-2P

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Hooks vs. Cardinals
END:VALARM
DTSTART:20180812T230500Z
DTEND:20180813T020500Z
UID:r3PHvlYbUL9uvEcltKxrBXbF@stanza.co
SUMMARY:Hooks vs. Cardinals
DESCRIPTION:Hooks vs. Cardinals\n\nFollow on MiLB First Pitch: https://stza.co/+xzGT-2n\n\nShop: https://stza.co/+xzGT-2P\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144517Z
LAST-MODIFIED:20180213T144517Z
TRANSP:OPAQUE
END:VEVENT
* Hooks @ Drillers
<2018-08-14 Tue 19:05-22:05>
:PROPERTIES:
:ID:       BpX-o7lOxUGGob965wyLCp9_@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Hooks @ Drillers Hooks @ Drillers

Follow on MiLB First Pitch  https //stza.co/+v$Z7-12

Shop  https //stza.co/+v$Z7-1a

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Hooks @ Drillers
END:VALARM
DTSTART:20180815T000500Z
DTEND:20180815T030500Z
UID:BpX-o7lOxUGGob965wyLCp9_@stanza.co
SUMMARY:Hooks @ Drillers
DESCRIPTION:Hooks @ Drillers\n\nFollow on MiLB First Pitch: https://stza.co/+v$Z7-12\n\nShop: https://stza.co/+v$Z7-1a\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144517Z
LAST-MODIFIED:20180213T144517Z
TRANSP:OPAQUE
END:VEVENT
* Hooks @ Drillers
<2018-08-15 Wed 19:05-22:05>
:PROPERTIES:
:ID:       zGcU1MkIddtB1BkZ9vQjVwnk@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Hooks @ Drillers Hooks @ Drillers

Follow on MiLB First Pitch  https //stza.co/+v$Z8-3R

Shop  https //stza.co/+v$Z8-1w

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Hooks @ Drillers
END:VALARM
DTSTART:20180816T000500Z
DTEND:20180816T030500Z
UID:zGcU1MkIddtB1BkZ9vQjVwnk@stanza.co
SUMMARY:Hooks @ Drillers
DESCRIPTION:Hooks @ Drillers\n\nFollow on MiLB First Pitch: https://stza.co/+v$Z8-3R\n\nShop: https://stza.co/+v$Z8-1w\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144517Z
LAST-MODIFIED:20180213T144517Z
TRANSP:OPAQUE
END:VEVENT
* Hooks @ Drillers
<2018-08-16 Thu 19:05-22:05>
:PROPERTIES:
:ID:       iVkwsaRFxQGf_P2mLboWi-3r@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Hooks @ Drillers Hooks @ Drillers

Follow on MiLB First Pitch  https //stza.co/+v$Z9-2m

Shop  https //stza.co/+v$Z9-3u

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Hooks @ Drillers
END:VALARM
DTSTART:20180817T000500Z
DTEND:20180817T030500Z
UID:iVkwsaRFxQGf_P2mLboWi-3r@stanza.co
SUMMARY:Hooks @ Drillers
DESCRIPTION:Hooks @ Drillers\n\nFollow on MiLB First Pitch: https://stza.co/+v$Z9-2m\n\nShop: https://stza.co/+v$Z9-3u\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144517Z
LAST-MODIFIED:20180213T144517Z
TRANSP:OPAQUE
END:VEVENT
* Hooks @ Cardinals
<2018-08-17 Fri 19:10-22:10>
:PROPERTIES:
:ID:       TOxsZGURIthHObSIPek0JsO7@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Hooks @ Cardinals Hooks @ Cardinals

Follow on MiLB First Pitch  https //stza.co/+wPMz-2j

Shop  https //stza.co/+wPMz-35

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Hooks @ Cardinals
END:VALARM
DTSTART:20180818T001000Z
DTEND:20180818T031000Z
UID:TOxsZGURIthHObSIPek0JsO7@stanza.co
SUMMARY:Hooks @ Cardinals
DESCRIPTION:Hooks @ Cardinals\n\nFollow on MiLB First Pitch: https://stza.co/+wPMz-2j\n\nShop: https://stza.co/+wPMz-35\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144517Z
LAST-MODIFIED:20180213T144517Z
TRANSP:OPAQUE
END:VEVENT
* Hooks @ Cardinals
<2018-08-18 Sat 18:10-21:10>
:PROPERTIES:
:ID:       sBaKVHxi2Bw8P7JBTeXq7qWf@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Hooks @ Cardinals Hooks @ Cardinals

Follow on MiLB First Pitch  https //stza.co/+wPMA-1e

Shop  https //stza.co/+wPMA-2X

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Hooks @ Cardinals
END:VALARM
DTSTART:20180818T231000Z
DTEND:20180819T021000Z
UID:sBaKVHxi2Bw8P7JBTeXq7qWf@stanza.co
SUMMARY:Hooks @ Cardinals
DESCRIPTION:Hooks @ Cardinals\n\nFollow on MiLB First Pitch: https://stza.co/+wPMA-1e\n\nShop: https://stza.co/+wPMA-2X\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144517Z
LAST-MODIFIED:20180213T144517Z
TRANSP:OPAQUE
END:VEVENT
* Hooks @ Cardinals
<2018-08-19 Sun 16:10-19:10>
:PROPERTIES:
:ID:       IqdAD_-IKXW3ooJDYKCpo7CM@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Hooks @ Cardinals Hooks @ Cardinals

Follow on MiLB First Pitch  https //stza.co/+wPMB-3m

Shop  https //stza.co/+wPMB-3r

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Hooks @ Cardinals
END:VALARM
DTSTART:20180819T211000Z
DTEND:20180820T001000Z
UID:IqdAD_-IKXW3ooJDYKCpo7CM@stanza.co
SUMMARY:Hooks @ Cardinals
DESCRIPTION:Hooks @ Cardinals\n\nFollow on MiLB First Pitch: https://stza.co/+wPMB-3m\n\nShop: https://stza.co/+wPMB-3r\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144517Z
LAST-MODIFIED:20180213T144517Z
TRANSP:OPAQUE
END:VEVENT
* Hooks vs. RockHounds
<2018-08-21 Tue 19:05-22:05>
:PROPERTIES:
:ID:       iMwy3vv0u7QEH13jXqSqmz0V@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Hooks vs. RockHounds Hooks vs. RockHounds

Follow on MiLB First Pitch  https //stza.co/+xzGX-H

Shop  https //stza.co/+xzGX-2F

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Hooks vs. RockHounds
END:VALARM
DTSTART:20180822T000500Z
DTEND:20180822T030500Z
UID:iMwy3vv0u7QEH13jXqSqmz0V@stanza.co
SUMMARY:Hooks vs. RockHounds
DESCRIPTION:Hooks vs. RockHounds\n\nFollow on MiLB First Pitch: https://stza.co/+xzGX-H\n\nShop: https://stza.co/+xzGX-2F\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144517Z
LAST-MODIFIED:20180213T144517Z
TRANSP:OPAQUE
END:VEVENT
* Hooks vs. RockHounds
<2018-08-22 Wed 19:05-22:05>
:PROPERTIES:
:ID:       U-S63dh0y20fgS6yAid9C17R@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Hooks vs. RockHounds Hooks vs. RockHounds

Follow on MiLB First Pitch  https //stza.co/+xzGY-W

Shop  https //stza.co/+xzGY-2U

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Hooks vs. RockHounds
END:VALARM
DTSTART:20180823T000500Z
DTEND:20180823T030500Z
UID:U-S63dh0y20fgS6yAid9C17R@stanza.co
SUMMARY:Hooks vs. RockHounds
DESCRIPTION:Hooks vs. RockHounds\n\nFollow on MiLB First Pitch: https://stza.co/+xzGY-W\n\nShop: https://stza.co/+xzGY-2U\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144517Z
LAST-MODIFIED:20180213T144517Z
TRANSP:OPAQUE
END:VEVENT
* Hooks vs. RockHounds
<2018-08-23 Thu 19:05-22:05>
:PROPERTIES:
:ID:       y72f5BuirbqTT2ee3esMv5D5@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Hooks vs. RockHounds Hooks vs. RockHounds

Follow on MiLB First Pitch  https //stza.co/+xzG_-3e

Shop  https //stza.co/+xzG_-1Z

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Hooks vs. RockHounds
END:VALARM
DTSTART:20180824T000500Z
DTEND:20180824T030500Z
UID:y72f5BuirbqTT2ee3esMv5D5@stanza.co
SUMMARY:Hooks vs. RockHounds
DESCRIPTION:Hooks vs. RockHounds\n\nFollow on MiLB First Pitch: https://stza.co/+xzG_-3e\n\nShop: https://stza.co/+xzG_-1Z\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144517Z
LAST-MODIFIED:20180213T144517Z
TRANSP:OPAQUE
END:VEVENT
* Hooks vs. RockHounds
<2018-08-24 Fri 19:05-22:05>
:PROPERTIES:
:ID:       -eDFr0DpFOlI4vADj_iEbHAe@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Hooks vs. RockHounds Hooks vs. RockHounds

Follow on MiLB First Pitch  https //stza.co/+xzH1-V

Shop  https //stza.co/+xzH1-1R

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Hooks vs. RockHounds
END:VALARM
DTSTART:20180825T000500Z
DTEND:20180825T030500Z
UID:-eDFr0DpFOlI4vADj_iEbHAe@stanza.co
SUMMARY:Hooks vs. RockHounds
DESCRIPTION:Hooks vs. RockHounds\n\nFollow on MiLB First Pitch: https://stza.co/+xzH1-V\n\nShop: https://stza.co/+xzH1-1R\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144517Z
LAST-MODIFIED:20180213T144517Z
TRANSP:OPAQUE
END:VEVENT
* Hooks vs. Missions
<2018-08-25 Sat 19:05-22:05>
:PROPERTIES:
:ID:       m66VcH9VE2Pplvk79qvTjBPT@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Hooks vs. Missions Hooks vs. Missions

Follow on MiLB First Pitch  https //stza.co/+xzH3-1H

Shop  https //stza.co/+xzH3-3H

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Hooks vs. Missions
END:VALARM
DTSTART:20180826T000500Z
DTEND:20180826T030500Z
UID:m66VcH9VE2Pplvk79qvTjBPT@stanza.co
SUMMARY:Hooks vs. Missions
DESCRIPTION:Hooks vs. Missions\n\nFollow on MiLB First Pitch: https://stza.co/+xzH3-1H\n\nShop: https://stza.co/+xzH3-3H\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144517Z
LAST-MODIFIED:20180213T144517Z
TRANSP:OPAQUE
END:VEVENT
* Hooks vs. Missions
<2018-08-26 Sun 18:05-21:05>
:PROPERTIES:
:ID:       AgOwVIgtb-YRgItwt0cntZlz@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Hooks vs. Missions Hooks vs. Missions

Follow on MiLB First Pitch  https //stza.co/+xzH5-3n

Shop  https //stza.co/+xzH5-1_

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Hooks vs. Missions
END:VALARM
DTSTART:20180826T230500Z
DTEND:20180827T020500Z
UID:AgOwVIgtb-YRgItwt0cntZlz@stanza.co
SUMMARY:Hooks vs. Missions
DESCRIPTION:Hooks vs. Missions\n\nFollow on MiLB First Pitch: https://stza.co/+xzH5-3n\n\nShop: https://stza.co/+xzH5-1_\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144517Z
LAST-MODIFIED:20180213T144517Z
TRANSP:OPAQUE
END:VEVENT
* Hooks vs. Missions
<2018-08-27 Mon 19:05-22:05>
:PROPERTIES:
:ID:       0oyGo4WreIPC7WzjBcGb4Mun@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Hooks vs. Missions Hooks vs. Missions

Follow on MiLB First Pitch  https //stza.co/+xzH8-1o

Shop  https //stza.co/+xzH8-26

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Hooks vs. Missions
END:VALARM
DTSTART:20180828T000500Z
DTEND:20180828T030500Z
UID:0oyGo4WreIPC7WzjBcGb4Mun@stanza.co
SUMMARY:Hooks vs. Missions
DESCRIPTION:Hooks vs. Missions\n\nFollow on MiLB First Pitch: https://stza.co/+xzH8-1o\n\nShop: https://stza.co/+xzH8-26\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144517Z
LAST-MODIFIED:20180213T144517Z
TRANSP:OPAQUE
END:VEVENT
* Hooks @ RoughRiders
<2018-08-28 Tue 19:05-22:05>
:PROPERTIES:
:ID:       JivPrUW60UUR_0zccjmLdMOY@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Hooks @ RoughRiders Hooks @ RoughRiders

Follow on MiLB First Pitch  https //stza.co/+wY7x-1K

Shop  https //stza.co/+wY7x-1x

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Hooks @ RoughRiders
END:VALARM
DTSTART:20180829T000500Z
DTEND:20180829T030500Z
UID:JivPrUW60UUR_0zccjmLdMOY@stanza.co
SUMMARY:Hooks @ RoughRiders
DESCRIPTION:Hooks @ RoughRiders\n\nFollow on MiLB First Pitch: https://stza.co/+wY7x-1K\n\nShop: https://stza.co/+wY7x-1x\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144517Z
LAST-MODIFIED:20180213T144517Z
TRANSP:OPAQUE
END:VEVENT
* Hooks @ RoughRiders
<2018-08-29 Wed 19:05-22:05>
:PROPERTIES:
:ID:       Ze466PLnfjrd_Dp0VLYKsYeb@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Hooks @ RoughRiders Hooks @ RoughRiders

Follow on MiLB First Pitch  https //stza.co/+wY7y-1q

Shop  https //stza.co/+wY7y-q

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Hooks @ RoughRiders
END:VALARM
DTSTART:20180830T000500Z
DTEND:20180830T030500Z
UID:Ze466PLnfjrd_Dp0VLYKsYeb@stanza.co
SUMMARY:Hooks @ RoughRiders
DESCRIPTION:Hooks @ RoughRiders\n\nFollow on MiLB First Pitch: https://stza.co/+wY7y-1q\n\nShop: https://stza.co/+wY7y-q\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144517Z
LAST-MODIFIED:20180213T144517Z
TRANSP:OPAQUE
END:VEVENT
* Hooks @ RoughRiders
<2018-08-30 Thu 19:05-22:05>
:PROPERTIES:
:ID:       iNcznUboKujzibmfiNmbBrrw@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Hooks @ RoughRiders Hooks @ RoughRiders

Follow on MiLB First Pitch  https //stza.co/+wY7z-7

Shop  https //stza.co/+wY7z-3I

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Hooks @ RoughRiders
END:VALARM
DTSTART:20180831T000500Z
DTEND:20180831T030500Z
UID:iNcznUboKujzibmfiNmbBrrw@stanza.co
SUMMARY:Hooks @ RoughRiders
DESCRIPTION:Hooks @ RoughRiders\n\nFollow on MiLB First Pitch: https://stza.co/+wY7z-7\n\nShop: https://stza.co/+wY7z-3I\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144517Z
LAST-MODIFIED:20180213T144517Z
TRANSP:OPAQUE
END:VEVENT
* Hooks @ RoughRiders
<2018-08-31 Fri 19:05-22:05>
:PROPERTIES:
:ID:       p2FmF_wAq5r2KRx1rqJXanRI@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Hooks @ RoughRiders Hooks @ RoughRiders

Follow on MiLB First Pitch  https //stza.co/+wY7B-i

Shop  https //stza.co/+wY7B-12

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Hooks @ RoughRiders
END:VALARM
DTSTART:20180901T000500Z
DTEND:20180901T030500Z
UID:p2FmF_wAq5r2KRx1rqJXanRI@stanza.co
SUMMARY:Hooks @ RoughRiders
DESCRIPTION:Hooks @ RoughRiders\n\nFollow on MiLB First Pitch: https://stza.co/+wY7B-i\n\nShop: https://stza.co/+wY7B-12\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144517Z
LAST-MODIFIED:20180213T144517Z
TRANSP:OPAQUE
END:VEVENT
* Hooks @ Missions
<2018-09-01 Sat 19:05-22:05>
:PROPERTIES:
:ID:       yCEWzK8Mw6aOgwXrR6asQpcm@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Hooks @ Missions Hooks @ Missions

Follow on MiLB First Pitch  https //stza.co/+wMtN-X

Shop  https //stza.co/+wMtN-c

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Hooks @ Missions
END:VALARM
DTSTART:20180902T000500Z
DTEND:20180902T030500Z
UID:yCEWzK8Mw6aOgwXrR6asQpcm@stanza.co
SUMMARY:Hooks @ Missions
DESCRIPTION:Hooks @ Missions\n\nFollow on MiLB First Pitch: https://stza.co/+wMtN-X\n\nShop: https://stza.co/+wMtN-c\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144517Z
LAST-MODIFIED:20180213T144517Z
TRANSP:OPAQUE
END:VEVENT
* Hooks @ Missions
<2018-09-02 Sun 18:05-21:05>
:PROPERTIES:
:ID:       WrKIVyeDLsZxnnaZ1csv02N_@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Hooks @ Missions Hooks @ Missions

Follow on MiLB First Pitch  https //stza.co/+wMtO-2N

Shop  https //stza.co/+wMtO-2e

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Hooks @ Missions
END:VALARM
DTSTART:20180902T230500Z
DTEND:20180903T020500Z
UID:WrKIVyeDLsZxnnaZ1csv02N_@stanza.co
SUMMARY:Hooks @ Missions
DESCRIPTION:Hooks @ Missions\n\nFollow on MiLB First Pitch: https://stza.co/+wMtO-2N\n\nShop: https://stza.co/+wMtO-2e\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144517Z
LAST-MODIFIED:20180213T144517Z
TRANSP:OPAQUE
END:VEVENT
* Hooks @ Missions
<2018-09-03 Mon 14:05-17:05>
:PROPERTIES:
:ID:       miXM41kEzNqnqiqLGmJLiDKq@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Hooks @ Missions Hooks @ Missions

Follow on MiLB First Pitch  https //stza.co/+wMtQ-1h

Shop  https //stza.co/+wMtQ-1D

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Hooks @ Missions
END:VALARM
DTSTART:20180903T190500Z
DTEND:20180903T220500Z
UID:miXM41kEzNqnqiqLGmJLiDKq@stanza.co
SUMMARY:Hooks @ Missions
DESCRIPTION:Hooks @ Missions\n\nFollow on MiLB First Pitch: https://stza.co/+wMtQ-1h\n\nShop: https://stza.co/+wMtQ-1D\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144517Z
LAST-MODIFIED:20180213T144517Z
TRANSP:OPAQUE
END:VEVENT
