#+TITLE:       Main Google calendar entries
#+AUTHOR:      Eric S Fraga
#+EMAIL:       e.fraga@ucl.ac.uk
#+DESCRIPTION: converted using the ical2org awk script
#+CATEGORY:    google
#+STARTUP:     hidestars
#+STARTUP:     overview

* COMMENT original iCal preamble

* Cubs vs. Dodgers
<2018-04-05 Thu 15:08-18:08>
:PROPERTIES:
:ID:       H0yH0F7feRaLD8GpzRvg3fNJ@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Cubs vs. Dodgers Cubs vs. Dodgers

Follow on MiLB First Pitch  https //stza.co/+vKCw-1L

Shop  https //stza.co/+vKCw-Q

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Cubs vs. Dodgers
END:VALARM
DTSTART:20180405T200800Z
DTEND:20180405T230800Z
UID:H0yH0F7feRaLD8GpzRvg3fNJ@stanza.co
SUMMARY:Cubs vs. Dodgers
DESCRIPTION:Cubs vs. Dodgers\n\nFollow on MiLB First Pitch: https://stza.co/+vKCw-1L\n\nShop: https://stza.co/+vKCw-Q\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144535Z
LAST-MODIFIED:20180213T144535Z
TRANSP:OPAQUE
END:VEVENT
* Cubs vs. Dodgers
<2018-04-06 Fri 19:08-22:08>
:PROPERTIES:
:ID:       7800F_u5xLzj8G2iUqh7WpVf@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Cubs vs. Dodgers Cubs vs. Dodgers

Follow on MiLB First Pitch  https //stza.co/+vKCy-3j

Shop  https //stza.co/+vKCy-3z

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Cubs vs. Dodgers
END:VALARM
DTSTART:20180407T000800Z
DTEND:20180407T030800Z
UID:7800F_u5xLzj8G2iUqh7WpVf@stanza.co
SUMMARY:Cubs vs. Dodgers
DESCRIPTION:Cubs vs. Dodgers\n\nFollow on MiLB First Pitch: https://stza.co/+vKCy-3j\n\nShop: https://stza.co/+vKCy-3z\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144535Z
LAST-MODIFIED:20180213T144535Z
TRANSP:OPAQUE
END:VEVENT
* Cubs vs. Dodgers
<2018-04-07 Sat 19:08-22:08>
:PROPERTIES:
:ID:       5_Eyj2rBneZqS3xyfU2mtUcx@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Cubs vs. Dodgers Cubs vs. Dodgers

Follow on MiLB First Pitch  https //stza.co/+vKCA-F

Shop  https //stza.co/+vKCA-24

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Cubs vs. Dodgers
END:VALARM
DTSTART:20180408T000800Z
DTEND:20180408T030800Z
UID:5_Eyj2rBneZqS3xyfU2mtUcx@stanza.co
SUMMARY:Cubs vs. Dodgers
DESCRIPTION:Cubs vs. Dodgers\n\nFollow on MiLB First Pitch: https://stza.co/+vKCA-F\n\nShop: https://stza.co/+vKCA-24\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144535Z
LAST-MODIFIED:20180213T144535Z
TRANSP:OPAQUE
END:VEVENT
* Cubs vs. Dodgers
<2018-04-08 Sun 13:08-16:08>
:PROPERTIES:
:ID:       bLi1AvU7x1lzNA2BRPk8MjJo@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Cubs vs. Dodgers Cubs vs. Dodgers

Follow on MiLB First Pitch  https //stza.co/+vKCC-2R

Shop  https //stza.co/+vKCC-2I

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Cubs vs. Dodgers
END:VALARM
DTSTART:20180408T180800Z
DTEND:20180408T210800Z
UID:bLi1AvU7x1lzNA2BRPk8MjJo@stanza.co
SUMMARY:Cubs vs. Dodgers
DESCRIPTION:Cubs vs. Dodgers\n\nFollow on MiLB First Pitch: https://stza.co/+vKCC-2R\n\nShop: https://stza.co/+vKCC-2I\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144535Z
LAST-MODIFIED:20180213T144535Z
TRANSP:OPAQUE
END:VEVENT
* Cubs vs. Dodgers
<2018-04-09 Mon 12:08-15:08>
:PROPERTIES:
:ID:       DO5sPOdXtdm0ve9QNB5_514x@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Cubs vs. Dodgers Cubs vs. Dodgers

Follow on MiLB First Pitch  https //stza.co/+vKCD-1Q

Shop  https //stza.co/+vKCD-t

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Cubs vs. Dodgers
END:VALARM
DTSTART:20180409T170800Z
DTEND:20180409T200800Z
UID:DO5sPOdXtdm0ve9QNB5_514x@stanza.co
SUMMARY:Cubs vs. Dodgers
DESCRIPTION:Cubs vs. Dodgers\n\nFollow on MiLB First Pitch: https://stza.co/+vKCD-1Q\n\nShop: https://stza.co/+vKCD-t\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144535Z
LAST-MODIFIED:20180213T144535Z
TRANSP:OPAQUE
END:VEVENT
* Cubs @ Sounds
<2018-04-10 Tue 18:35-21:35>
:PROPERTIES:
:ID:       RggFNpRQYlpBAb2_YdH7lKP5@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Cubs @ Sounds Cubs @ Sounds

Follow on MiLB First Pitch  https //stza.co/+whE6-3

Shop  https //stza.co/+whE6-1t

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Cubs @ Sounds
END:VALARM
DTSTART:20180410T233500Z
DTEND:20180411T023500Z
UID:RggFNpRQYlpBAb2_YdH7lKP5@stanza.co
SUMMARY:Cubs @ Sounds
DESCRIPTION:Cubs @ Sounds\n\nFollow on MiLB First Pitch: https://stza.co/+whE6-3\n\nShop: https://stza.co/+whE6-1t\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144535Z
LAST-MODIFIED:20180213T144535Z
TRANSP:OPAQUE
END:VEVENT
* Cubs @ Sounds
<2018-04-11 Wed 18:35-21:35>
:PROPERTIES:
:ID:       zQlFXjtpdGCdjrbp0KKUlCZL@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Cubs @ Sounds Cubs @ Sounds

Follow on MiLB First Pitch  https //stza.co/+whE7-1_

Shop  https //stza.co/+whE7-3n

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Cubs @ Sounds
END:VALARM
DTSTART:20180411T233500Z
DTEND:20180412T023500Z
UID:zQlFXjtpdGCdjrbp0KKUlCZL@stanza.co
SUMMARY:Cubs @ Sounds
DESCRIPTION:Cubs @ Sounds\n\nFollow on MiLB First Pitch: https://stza.co/+whE7-1_\n\nShop: https://stza.co/+whE7-3n\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144535Z
LAST-MODIFIED:20180213T144535Z
TRANSP:OPAQUE
END:VEVENT
* Cubs @ Sounds
<2018-04-12 Thu 18:35-21:35>
:PROPERTIES:
:ID:       dBSpBybkO-uWlPnniXeqNlmk@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Cubs @ Sounds Cubs @ Sounds

Follow on MiLB First Pitch  https //stza.co/+whE8-3r

Shop  https //stza.co/+whE8-2_

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Cubs @ Sounds
END:VALARM
DTSTART:20180412T233500Z
DTEND:20180413T023500Z
UID:dBSpBybkO-uWlPnniXeqNlmk@stanza.co
SUMMARY:Cubs @ Sounds
DESCRIPTION:Cubs @ Sounds\n\nFollow on MiLB First Pitch: https://stza.co/+whE8-3r\n\nShop: https://stza.co/+whE8-2_\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144535Z
LAST-MODIFIED:20180213T144535Z
TRANSP:OPAQUE
END:VEVENT
* Cubs @ Redbirds
<2018-04-13 Fri 19:05-22:05>
:PROPERTIES:
:ID:       nd6sIFPedx4KM4Nz8A76F5sZ@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Cubs @ Redbirds Cubs @ Redbirds

Follow on MiLB First Pitch  https //stza.co/+wmCW-11

Shop  https //stza.co/+wmCW-2c

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Cubs @ Redbirds
END:VALARM
DTSTART:20180414T000500Z
DTEND:20180414T030500Z
UID:nd6sIFPedx4KM4Nz8A76F5sZ@stanza.co
SUMMARY:Cubs @ Redbirds
DESCRIPTION:Cubs @ Redbirds\n\nFollow on MiLB First Pitch: https://stza.co/+wmCW-11\n\nShop: https://stza.co/+wmCW-2c\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144535Z
LAST-MODIFIED:20180213T144535Z
TRANSP:OPAQUE
END:VEVENT
* Cubs @ Redbirds
<2018-04-14 Sat 18:35-21:35>
:PROPERTIES:
:ID:       SkxTjEzqN3LvWFwOCivDfdjF@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Cubs @ Redbirds Cubs @ Redbirds

Follow on MiLB First Pitch  https //stza.co/+wmCX-32

Shop  https //stza.co/+wmCX-3y

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Cubs @ Redbirds
END:VALARM
DTSTART:20180414T233500Z
DTEND:20180415T023500Z
UID:SkxTjEzqN3LvWFwOCivDfdjF@stanza.co
SUMMARY:Cubs @ Redbirds
DESCRIPTION:Cubs @ Redbirds\n\nFollow on MiLB First Pitch: https://stza.co/+wmCX-32\n\nShop: https://stza.co/+wmCX-3y\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144535Z
LAST-MODIFIED:20180213T144535Z
TRANSP:OPAQUE
END:VEVENT
* Cubs @ Redbirds
<2018-04-15 Sun 14:05-17:05>
:PROPERTIES:
:ID:       4USpIjRyd09dDYryzCHXtWOg@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Cubs @ Redbirds Cubs @ Redbirds

Follow on MiLB First Pitch  https //stza.co/+wmCY-R

Shop  https //stza.co/+wmCY-3s

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Cubs @ Redbirds
END:VALARM
DTSTART:20180415T190500Z
DTEND:20180415T220500Z
UID:4USpIjRyd09dDYryzCHXtWOg@stanza.co
SUMMARY:Cubs @ Redbirds
DESCRIPTION:Cubs @ Redbirds\n\nFollow on MiLB First Pitch: https://stza.co/+wmCY-R\n\nShop: https://stza.co/+wmCY-3s\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144535Z
LAST-MODIFIED:20180213T144535Z
TRANSP:OPAQUE
END:VEVENT
* Cubs @ Redbirds
<2018-04-16 Mon 11:05-14:05>
:PROPERTIES:
:ID:       DReXarrptlUIKbGBsyTY5sCv@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Cubs @ Redbirds Cubs @ Redbirds

Follow on MiLB First Pitch  https //stza.co/+wmCZ-3y

Shop  https //stza.co/+wmCZ-2x

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Cubs @ Redbirds
END:VALARM
DTSTART:20180416T160500Z
DTEND:20180416T190500Z
UID:DReXarrptlUIKbGBsyTY5sCv@stanza.co
SUMMARY:Cubs @ Redbirds
DESCRIPTION:Cubs @ Redbirds\n\nFollow on MiLB First Pitch: https://stza.co/+wmCZ-3y\n\nShop: https://stza.co/+wmCZ-2x\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144535Z
LAST-MODIFIED:20180213T144535Z
TRANSP:OPAQUE
END:VEVENT
* Cubs vs. Sounds
<2018-04-17 Tue 18:38-21:38>
:PROPERTIES:
:ID:       IEyw8P5VAe5EwQCw948SNLPj@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Cubs vs. Sounds Cubs vs. Sounds

Follow on MiLB First Pitch  https //stza.co/+vKCG-2l

Shop  https //stza.co/+vKCG-2Z

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Cubs vs. Sounds
END:VALARM
DTSTART:20180417T233800Z
DTEND:20180418T023800Z
UID:IEyw8P5VAe5EwQCw948SNLPj@stanza.co
SUMMARY:Cubs vs. Sounds
DESCRIPTION:Cubs vs. Sounds\n\nFollow on MiLB First Pitch: https://stza.co/+vKCG-2l\n\nShop: https://stza.co/+vKCG-2Z\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144535Z
LAST-MODIFIED:20180213T144535Z
TRANSP:OPAQUE
END:VEVENT
* Cubs vs. Sounds
<2018-04-18 Wed 12:08-15:08>
:PROPERTIES:
:ID:       ZhLvQYAZq3gAuZW4sm_j3DnY@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Cubs vs. Sounds Cubs vs. Sounds

Follow on MiLB First Pitch  https //stza.co/+vKCH-1W

Shop  https //stza.co/+vKCH-2V

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Cubs vs. Sounds
END:VALARM
DTSTART:20180418T170800Z
DTEND:20180418T200800Z
UID:ZhLvQYAZq3gAuZW4sm_j3DnY@stanza.co
SUMMARY:Cubs vs. Sounds
DESCRIPTION:Cubs vs. Sounds\n\nFollow on MiLB First Pitch: https://stza.co/+vKCH-1W\n\nShop: https://stza.co/+vKCH-2V\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144535Z
LAST-MODIFIED:20180213T144535Z
TRANSP:OPAQUE
END:VEVENT
* Cubs vs. Sounds
<2018-04-19 Thu 18:38-21:38>
:PROPERTIES:
:ID:       W8Vrp7qxsOrOgmf5nWAj0UOt@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Cubs vs. Sounds Cubs vs. Sounds

Follow on MiLB First Pitch  https //stza.co/+vKCJ-1j

Shop  https //stza.co/+vKCJ-F

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Cubs vs. Sounds
END:VALARM
DTSTART:20180419T233800Z
DTEND:20180420T023800Z
UID:W8Vrp7qxsOrOgmf5nWAj0UOt@stanza.co
SUMMARY:Cubs vs. Sounds
DESCRIPTION:Cubs vs. Sounds\n\nFollow on MiLB First Pitch: https://stza.co/+vKCJ-1j\n\nShop: https://stza.co/+vKCJ-F\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144535Z
LAST-MODIFIED:20180213T144535Z
TRANSP:OPAQUE
END:VEVENT
* Cubs vs. Sounds
<2018-04-20 Fri 19:08-22:08>
:PROPERTIES:
:ID:       ZwYMczo8zzTZXYaQsHqnHQNe@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Cubs vs. Sounds Cubs vs. Sounds

Follow on MiLB First Pitch  https //stza.co/+vKCM-3_

Shop  https //stza.co/+vKCM-2M

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Cubs vs. Sounds
END:VALARM
DTSTART:20180421T000800Z
DTEND:20180421T030800Z
UID:ZwYMczo8zzTZXYaQsHqnHQNe@stanza.co
SUMMARY:Cubs vs. Sounds
DESCRIPTION:Cubs vs. Sounds\n\nFollow on MiLB First Pitch: https://stza.co/+vKCM-3_\n\nShop: https://stza.co/+vKCM-2M\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144535Z
LAST-MODIFIED:20180213T144535Z
TRANSP:OPAQUE
END:VEVENT
* Cubs vs. Redbirds
<2018-04-21 Sat 19:08-22:08>
:PROPERTIES:
:ID:       1NXJIplYfDgkr3LL_lvJ0wTl@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Cubs vs. Redbirds Cubs vs. Redbirds

Follow on MiLB First Pitch  https //stza.co/+vKCO-3e

Shop  https //stza.co/+vKCO-3q

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Cubs vs. Redbirds
END:VALARM
DTSTART:20180422T000800Z
DTEND:20180422T030800Z
UID:1NXJIplYfDgkr3LL_lvJ0wTl@stanza.co
SUMMARY:Cubs vs. Redbirds
DESCRIPTION:Cubs vs. Redbirds\n\nFollow on MiLB First Pitch: https://stza.co/+vKCO-3e\n\nShop: https://stza.co/+vKCO-3q\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144535Z
LAST-MODIFIED:20180213T144535Z
TRANSP:OPAQUE
END:VEVENT
* Cubs vs. Redbirds
<2018-04-22 Sun 13:08-16:08>
:PROPERTIES:
:ID:       a3vtDwjpmrgk4KhBInR0sg05@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Cubs vs. Redbirds Cubs vs. Redbirds

Follow on MiLB First Pitch  https //stza.co/+vKCQ-b

Shop  https //stza.co/+vKCQ-3O

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Cubs vs. Redbirds
END:VALARM
DTSTART:20180422T180800Z
DTEND:20180422T210800Z
UID:a3vtDwjpmrgk4KhBInR0sg05@stanza.co
SUMMARY:Cubs vs. Redbirds
DESCRIPTION:Cubs vs. Redbirds\n\nFollow on MiLB First Pitch: https://stza.co/+vKCQ-b\n\nShop: https://stza.co/+vKCQ-3O\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144535Z
LAST-MODIFIED:20180213T144535Z
TRANSP:OPAQUE
END:VEVENT
* Cubs vs. Redbirds
<2018-04-23 Mon 12:08-15:08>
:PROPERTIES:
:ID:       8igE2gduAzdjEoosNgktQJNI@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Cubs vs. Redbirds Cubs vs. Redbirds

Follow on MiLB First Pitch  https //stza.co/+vKCR-F

Shop  https //stza.co/+vKCR-1F

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Cubs vs. Redbirds
END:VALARM
DTSTART:20180423T170800Z
DTEND:20180423T200800Z
UID:8igE2gduAzdjEoosNgktQJNI@stanza.co
SUMMARY:Cubs vs. Redbirds
DESCRIPTION:Cubs vs. Redbirds\n\nFollow on MiLB First Pitch: https://stza.co/+vKCR-F\n\nShop: https://stza.co/+vKCR-1F\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144535Z
LAST-MODIFIED:20180213T144535Z
TRANSP:OPAQUE
END:VEVENT
* Cubs @ Dodgers
<2018-04-25 Wed 19:05-22:05>
:PROPERTIES:
:ID:       Pk33V_U-BF-aL83QISzrEzrd@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Cubs @ Dodgers Cubs @ Dodgers

Follow on MiLB First Pitch  https //stza.co/+v$Mh-1Y

Shop  https //stza.co/+v$Mh-3E

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Cubs @ Dodgers
END:VALARM
DTSTART:20180426T000500Z
DTEND:20180426T030500Z
UID:Pk33V_U-BF-aL83QISzrEzrd@stanza.co
SUMMARY:Cubs @ Dodgers
DESCRIPTION:Cubs @ Dodgers\n\nFollow on MiLB First Pitch: https://stza.co/+v$Mh-1Y\n\nShop: https://stza.co/+v$Mh-3E\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144535Z
LAST-MODIFIED:20180213T144535Z
TRANSP:OPAQUE
END:VEVENT
* Cubs @ Dodgers
<2018-04-26 Thu 19:05-22:05>
:PROPERTIES:
:ID:       GJaXFFzwqXQIXm1ZbcxVdDWj@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Cubs @ Dodgers Cubs @ Dodgers

Follow on MiLB First Pitch  https //stza.co/+v$Mi-3U

Shop  https //stza.co/+v$Mi-12

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Cubs @ Dodgers
END:VALARM
DTSTART:20180427T000500Z
DTEND:20180427T030500Z
UID:GJaXFFzwqXQIXm1ZbcxVdDWj@stanza.co
SUMMARY:Cubs @ Dodgers
DESCRIPTION:Cubs @ Dodgers\n\nFollow on MiLB First Pitch: https://stza.co/+v$Mi-3U\n\nShop: https://stza.co/+v$Mi-12\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144535Z
LAST-MODIFIED:20180213T144535Z
TRANSP:OPAQUE
END:VEVENT
* Cubs @ Dodgers
<2018-04-27 Fri 19:05-22:05>
:PROPERTIES:
:ID:       vYxJWJQvFgsqkJGz-Dk931hj@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Cubs @ Dodgers Cubs @ Dodgers

Follow on MiLB First Pitch  https //stza.co/+v$Mj-3O

Shop  https //stza.co/+v$Mj-3x

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Cubs @ Dodgers
END:VALARM
DTSTART:20180428T000500Z
DTEND:20180428T030500Z
UID:vYxJWJQvFgsqkJGz-Dk931hj@stanza.co
SUMMARY:Cubs @ Dodgers
DESCRIPTION:Cubs @ Dodgers\n\nFollow on MiLB First Pitch: https://stza.co/+v$Mj-3O\n\nShop: https://stza.co/+v$Mj-3x\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144535Z
LAST-MODIFIED:20180213T144535Z
TRANSP:OPAQUE
END:VEVENT
* Cubs @ Dodgers
<2018-04-28 Sat 19:05-22:05>
:PROPERTIES:
:ID:       vvn17MoM4iBWfi4W-GeNbcCa@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Cubs @ Dodgers Cubs @ Dodgers

Follow on MiLB First Pitch  https //stza.co/+v$Mk-3N

Shop  https //stza.co/+v$Mk-g

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Cubs @ Dodgers
END:VALARM
DTSTART:20180429T000500Z
DTEND:20180429T030500Z
UID:vvn17MoM4iBWfi4W-GeNbcCa@stanza.co
SUMMARY:Cubs @ Dodgers
DESCRIPTION:Cubs @ Dodgers\n\nFollow on MiLB First Pitch: https://stza.co/+v$Mk-3N\n\nShop: https://stza.co/+v$Mk-g\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144535Z
LAST-MODIFIED:20180213T144535Z
TRANSP:OPAQUE
END:VEVENT
* Cubs @ Dodgers
<2018-04-29 Sun 14:05-17:05>
:PROPERTIES:
:ID:       NDthKSZCZFVIKq3BnELAk44W@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Cubs @ Dodgers Cubs @ Dodgers

Follow on MiLB First Pitch  https //stza.co/+v$Ml-2Y

Shop  https //stza.co/+v$Ml-3D

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Cubs @ Dodgers
END:VALARM
DTSTART:20180429T190500Z
DTEND:20180429T220500Z
UID:NDthKSZCZFVIKq3BnELAk44W@stanza.co
SUMMARY:Cubs @ Dodgers
DESCRIPTION:Cubs @ Dodgers\n\nFollow on MiLB First Pitch: https://stza.co/+v$Ml-2Y\n\nShop: https://stza.co/+v$Ml-3D\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144535Z
LAST-MODIFIED:20180213T144535Z
TRANSP:OPAQUE
END:VEVENT
* Cubs vs. Storm Chasers
<2018-04-30 Mon 18:38-21:38>
:PROPERTIES:
:ID:       8NNO9a0ddv90391B7XXQ3Aeq@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Cubs vs. Storm Chasers Cubs vs. Storm Chasers

Follow on MiLB First Pitch  https //stza.co/+vKCT-3g

Shop  https //stza.co/+vKCT-3R

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Cubs vs. Storm Chasers
END:VALARM
DTSTART:20180430T233800Z
DTEND:20180501T023800Z
UID:8NNO9a0ddv90391B7XXQ3Aeq@stanza.co
SUMMARY:Cubs vs. Storm Chasers
DESCRIPTION:Cubs vs. Storm Chasers\n\nFollow on MiLB First Pitch: https://stza.co/+vKCT-3g\n\nShop: https://stza.co/+vKCT-3R\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144535Z
LAST-MODIFIED:20180213T144535Z
TRANSP:OPAQUE
END:VEVENT
* Cubs vs. Storm Chasers
<2018-05-01 Tue 18:38-21:38>
:PROPERTIES:
:ID:       mEhr-A_NRhWkfNo0NFeggz8f@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Cubs vs. Storm Chasers Cubs vs. Storm Chasers

Follow on MiLB First Pitch  https //stza.co/+wHrw-D

Shop  https //stza.co/+wHrw-1D

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Cubs vs. Storm Chasers
END:VALARM
DTSTART:20180501T233800Z
DTEND:20180502T023800Z
UID:mEhr-A_NRhWkfNo0NFeggz8f@stanza.co
SUMMARY:Cubs vs. Storm Chasers
DESCRIPTION:Cubs vs. Storm Chasers\n\nFollow on MiLB First Pitch: https://stza.co/+wHrw-D\n\nShop: https://stza.co/+wHrw-1D\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144535Z
LAST-MODIFIED:20180213T144535Z
TRANSP:OPAQUE
END:VEVENT
* Cubs vs. Storm Chasers
<2018-05-02 Wed 12:08-15:08>
:PROPERTIES:
:ID:       yAEO57mBkUwTzrT40SXRmBrW@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Cubs vs. Storm Chasers Cubs vs. Storm Chasers

Follow on MiLB First Pitch  https //stza.co/+vKCX-2g

Shop  https //stza.co/+vKCX-2y

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Cubs vs. Storm Chasers
END:VALARM
DTSTART:20180502T170800Z
DTEND:20180502T200800Z
UID:yAEO57mBkUwTzrT40SXRmBrW@stanza.co
SUMMARY:Cubs vs. Storm Chasers
DESCRIPTION:Cubs vs. Storm Chasers\n\nFollow on MiLB First Pitch: https://stza.co/+vKCX-2g\n\nShop: https://stza.co/+vKCX-2y\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144535Z
LAST-MODIFIED:20180213T144535Z
TRANSP:OPAQUE
END:VEVENT
* Cubs vs. Storm Chasers
<2018-05-03 Thu 12:08-15:08>
:PROPERTIES:
:ID:       HAhbxXAonB9rg5gJuGUmV03Z@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Cubs vs. Storm Chasers Cubs vs. Storm Chasers

Follow on MiLB First Pitch  https //stza.co/+vKC_-l

Shop  https //stza.co/+vKC_-3P

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Cubs vs. Storm Chasers
END:VALARM
DTSTART:20180503T170800Z
DTEND:20180503T200800Z
UID:HAhbxXAonB9rg5gJuGUmV03Z@stanza.co
SUMMARY:Cubs vs. Storm Chasers
DESCRIPTION:Cubs vs. Storm Chasers\n\nFollow on MiLB First Pitch: https://stza.co/+vKC_-l\n\nShop: https://stza.co/+vKC_-3P\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144535Z
LAST-MODIFIED:20180213T144535Z
TRANSP:OPAQUE
END:VEVENT
* Cubs @ Express
<2018-05-04 Fri 19:05-22:05>
:PROPERTIES:
:ID:       bOCflSm-_Bl_qDNLBhg1qqLQ@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Cubs @ Express Cubs @ Express

Follow on MiLB First Pitch  https //stza.co/+vKFm-3f

Shop  https //stza.co/+vKFm-U

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Cubs @ Express
END:VALARM
DTSTART:20180505T000500Z
DTEND:20180505T030500Z
UID:bOCflSm-_Bl_qDNLBhg1qqLQ@stanza.co
SUMMARY:Cubs @ Express
DESCRIPTION:Cubs @ Express\n\nFollow on MiLB First Pitch: https://stza.co/+vKFm-3f\n\nShop: https://stza.co/+vKFm-U\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144535Z
LAST-MODIFIED:20180213T144535Z
TRANSP:OPAQUE
END:VEVENT
* Cubs @ Express
<2018-05-05 Sat 18:05-21:05>
:PROPERTIES:
:ID:       0LyqM9xshAYuQqX6NSY8nt9T@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Cubs @ Express Cubs @ Express

Follow on MiLB First Pitch  https //stza.co/+vKFn-Q

Shop  https //stza.co/+vKFn-3j

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Cubs @ Express
END:VALARM
DTSTART:20180505T230500Z
DTEND:20180506T020500Z
UID:0LyqM9xshAYuQqX6NSY8nt9T@stanza.co
SUMMARY:Cubs @ Express
DESCRIPTION:Cubs @ Express\n\nFollow on MiLB First Pitch: https://stza.co/+vKFn-Q\n\nShop: https://stza.co/+vKFn-3j\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144535Z
LAST-MODIFIED:20180213T144535Z
TRANSP:OPAQUE
END:VEVENT
* Cubs @ Express
<2018-05-06 Sun 13:05-16:05>
:PROPERTIES:
:ID:       q8u1sA0AALbBhTqYv-hya-I2@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Cubs @ Express Cubs @ Express

Follow on MiLB First Pitch  https //stza.co/+vKFo-3c

Shop  https //stza.co/+vKFo-1M

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Cubs @ Express
END:VALARM
DTSTART:20180506T180500Z
DTEND:20180506T210500Z
UID:q8u1sA0AALbBhTqYv-hya-I2@stanza.co
SUMMARY:Cubs @ Express
DESCRIPTION:Cubs @ Express\n\nFollow on MiLB First Pitch: https://stza.co/+vKFo-3c\n\nShop: https://stza.co/+vKFo-1M\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144535Z
LAST-MODIFIED:20180213T144535Z
TRANSP:OPAQUE
END:VEVENT
* Cubs @ Express
<2018-05-07 Mon 19:05-22:05>
:PROPERTIES:
:ID:       MSn2YzsF6I3NyR5X7NAc-T5g@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Cubs @ Express Cubs @ Express

Follow on MiLB First Pitch  https //stza.co/+vKFp-3z

Shop  https //stza.co/+vKFp-g

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Cubs @ Express
END:VALARM
DTSTART:20180508T000500Z
DTEND:20180508T030500Z
UID:MSn2YzsF6I3NyR5X7NAc-T5g@stanza.co
SUMMARY:Cubs @ Express
DESCRIPTION:Cubs @ Express\n\nFollow on MiLB First Pitch: https://stza.co/+vKFp-3z\n\nShop: https://stza.co/+vKFp-g\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144535Z
LAST-MODIFIED:20180213T144535Z
TRANSP:OPAQUE
END:VEVENT
* Cubs @ Storm Chasers
<2018-05-08 Tue 18:35-21:35>
:PROPERTIES:
:ID:       e0pQZJqllsCmpCCG-9otCUjv@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Cubs @ Storm Chasers Cubs @ Storm Chasers

Follow on MiLB First Pitch  https //stza.co/+whEo-V

Shop  https //stza.co/+whEo-C

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Cubs @ Storm Chasers
END:VALARM
DTSTART:20180508T233500Z
DTEND:20180509T023500Z
UID:e0pQZJqllsCmpCCG-9otCUjv@stanza.co
SUMMARY:Cubs @ Storm Chasers
DESCRIPTION:Cubs @ Storm Chasers\n\nFollow on MiLB First Pitch: https://stza.co/+whEo-V\n\nShop: https://stza.co/+whEo-C\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144535Z
LAST-MODIFIED:20180213T144535Z
TRANSP:OPAQUE
END:VEVENT
* Cubs @ Storm Chasers
<2018-05-09 Wed 11:05-14:05>
:PROPERTIES:
:ID:       vij5p9TYod-T1aBfqlSr-HkO@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Cubs @ Storm Chasers Cubs @ Storm Chasers

Follow on MiLB First Pitch  https //stza.co/+whEp-1m

Shop  https //stza.co/+whEp-2E

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Cubs @ Storm Chasers
END:VALARM
DTSTART:20180509T160500Z
DTEND:20180509T190500Z
UID:vij5p9TYod-T1aBfqlSr-HkO@stanza.co
SUMMARY:Cubs @ Storm Chasers
DESCRIPTION:Cubs @ Storm Chasers\n\nFollow on MiLB First Pitch: https://stza.co/+whEp-1m\n\nShop: https://stza.co/+whEp-2E\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144535Z
LAST-MODIFIED:20180213T144535Z
TRANSP:OPAQUE
END:VEVENT
* Cubs @ Storm Chasers
<2018-05-10 Thu 18:35-21:35>
:PROPERTIES:
:ID:       rB3mfJ2TeGYNHUklldR2qsyZ@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Cubs @ Storm Chasers Cubs @ Storm Chasers

Follow on MiLB First Pitch  https //stza.co/+whEq-2H

Shop  https //stza.co/+whEq-3E

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Cubs @ Storm Chasers
END:VALARM
DTSTART:20180510T233500Z
DTEND:20180511T023500Z
UID:rB3mfJ2TeGYNHUklldR2qsyZ@stanza.co
SUMMARY:Cubs @ Storm Chasers
DESCRIPTION:Cubs @ Storm Chasers\n\nFollow on MiLB First Pitch: https://stza.co/+whEq-2H\n\nShop: https://stza.co/+whEq-3E\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144535Z
LAST-MODIFIED:20180213T144535Z
TRANSP:OPAQUE
END:VEVENT
* Cubs @ Storm Chasers
<2018-05-11 Fri 19:05-22:05>
:PROPERTIES:
:ID:       ek0U90Z7whpUP5L1h0tDtWZq@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Cubs @ Storm Chasers Cubs @ Storm Chasers

Follow on MiLB First Pitch  https //stza.co/+whEr-2k

Shop  https //stza.co/+whEr-

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Cubs @ Storm Chasers
END:VALARM
DTSTART:20180512T000500Z
DTEND:20180512T030500Z
UID:ek0U90Z7whpUP5L1h0tDtWZq@stanza.co
SUMMARY:Cubs @ Storm Chasers
DESCRIPTION:Cubs @ Storm Chasers\n\nFollow on MiLB First Pitch: https://stza.co/+whEr-2k\n\nShop: https://stza.co/+whEr-\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144535Z
LAST-MODIFIED:20180213T144535Z
TRANSP:OPAQUE
END:VEVENT
* Cubs vs. Express
<2018-05-12 Sat 19:08-22:08>
:PROPERTIES:
:ID:       wx5jcwkMzXBV3T3FjOHYdz1u@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Cubs vs. Express Cubs vs. Express

Follow on MiLB First Pitch  https //stza.co/+vKC$-1T

Shop  https //stza.co/+vKC$-2L

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Cubs vs. Express
END:VALARM
DTSTART:20180513T000800Z
DTEND:20180513T030800Z
UID:wx5jcwkMzXBV3T3FjOHYdz1u@stanza.co
SUMMARY:Cubs vs. Express
DESCRIPTION:Cubs vs. Express\n\nFollow on MiLB First Pitch: https://stza.co/+vKC$-1T\n\nShop: https://stza.co/+vKC$-2L\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144535Z
LAST-MODIFIED:20180213T144535Z
TRANSP:OPAQUE
END:VEVENT
* Cubs vs. Express
<2018-05-13 Sun 13:08-16:08>
:PROPERTIES:
:ID:       ggp1Mx3IKFiqjNwYUKs4MfKg@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Cubs vs. Express Cubs vs. Express

Follow on MiLB First Pitch  https //stza.co/+vKD1-2E

Shop  https //stza.co/+vKD1-3Y

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Cubs vs. Express
END:VALARM
DTSTART:20180513T180800Z
DTEND:20180513T210800Z
UID:ggp1Mx3IKFiqjNwYUKs4MfKg@stanza.co
SUMMARY:Cubs vs. Express
DESCRIPTION:Cubs vs. Express\n\nFollow on MiLB First Pitch: https://stza.co/+vKD1-2E\n\nShop: https://stza.co/+vKD1-3Y\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144535Z
LAST-MODIFIED:20180213T144535Z
TRANSP:OPAQUE
END:VEVENT
* Cubs vs. Express
<2018-05-14 Mon 12:08-15:08>
:PROPERTIES:
:ID:       7WNzt5bB8eCrk-dijfGfVzu-@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Cubs vs. Express Cubs vs. Express

Follow on MiLB First Pitch  https //stza.co/+vKD4-36

Shop  https //stza.co/+vKD4-2q

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Cubs vs. Express
END:VALARM
DTSTART:20180514T170800Z
DTEND:20180514T200800Z
UID:7WNzt5bB8eCrk-dijfGfVzu-@stanza.co
SUMMARY:Cubs vs. Express
DESCRIPTION:Cubs vs. Express\n\nFollow on MiLB First Pitch: https://stza.co/+vKD4-36\n\nShop: https://stza.co/+vKD4-2q\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144535Z
LAST-MODIFIED:20180213T144535Z
TRANSP:OPAQUE
END:VEVENT
* Cubs vs. Express
<2018-05-15 Tue 12:08-15:08>
:PROPERTIES:
:ID:       E3ul2RBNIaS6-8b671n6hETj@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Cubs vs. Express Cubs vs. Express

Follow on MiLB First Pitch  https //stza.co/+vKD6-3d

Shop  https //stza.co/+vKD6-3u

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Cubs vs. Express
END:VALARM
DTSTART:20180515T170800Z
DTEND:20180515T200800Z
UID:E3ul2RBNIaS6-8b671n6hETj@stanza.co
SUMMARY:Cubs vs. Express
DESCRIPTION:Cubs vs. Express\n\nFollow on MiLB First Pitch: https://stza.co/+vKD6-3d\n\nShop: https://stza.co/+vKD6-3u\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144535Z
LAST-MODIFIED:20180213T144535Z
TRANSP:OPAQUE
END:VEVENT
* Cubs vs. Storm Chasers
<2018-05-17 Thu 18:38-21:38>
:PROPERTIES:
:ID:       NAgm8sdiFKAP2VHMpU2KHQp6@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Cubs vs. Storm Chasers Cubs vs. Storm Chasers

Follow on MiLB First Pitch  https //stza.co/+vKD8-1R

Shop  https //stza.co/+vKD8-3U

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Cubs vs. Storm Chasers
END:VALARM
DTSTART:20180517T233800Z
DTEND:20180518T023800Z
UID:NAgm8sdiFKAP2VHMpU2KHQp6@stanza.co
SUMMARY:Cubs vs. Storm Chasers
DESCRIPTION:Cubs vs. Storm Chasers\n\nFollow on MiLB First Pitch: https://stza.co/+vKD8-1R\n\nShop: https://stza.co/+vKD8-3U\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144535Z
LAST-MODIFIED:20180213T144535Z
TRANSP:OPAQUE
END:VEVENT
* Cubs vs. Storm Chasers
<2018-05-18 Fri 19:08-22:08>
:PROPERTIES:
:ID:       yq7v5nzrYaVBekz9fdoDWjDT@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Cubs vs. Storm Chasers Cubs vs. Storm Chasers

Follow on MiLB First Pitch  https //stza.co/+vKD9-1m

Shop  https //stza.co/+vKD9-1R

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Cubs vs. Storm Chasers
END:VALARM
DTSTART:20180519T000800Z
DTEND:20180519T030800Z
UID:yq7v5nzrYaVBekz9fdoDWjDT@stanza.co
SUMMARY:Cubs vs. Storm Chasers
DESCRIPTION:Cubs vs. Storm Chasers\n\nFollow on MiLB First Pitch: https://stza.co/+vKD9-1m\n\nShop: https://stza.co/+vKD9-1R\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144535Z
LAST-MODIFIED:20180213T144535Z
TRANSP:OPAQUE
END:VEVENT
* Cubs vs. Storm Chasers
<2018-05-19 Sat 19:08-22:08>
:PROPERTIES:
:ID:       bLJKxSh1ot7F3CxUihMJxzE4@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Cubs vs. Storm Chasers Cubs vs. Storm Chasers

Follow on MiLB First Pitch  https //stza.co/+vKDc-2G

Shop  https //stza.co/+vKDc-1a

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Cubs vs. Storm Chasers
END:VALARM
DTSTART:20180520T000800Z
DTEND:20180520T030800Z
UID:bLJKxSh1ot7F3CxUihMJxzE4@stanza.co
SUMMARY:Cubs vs. Storm Chasers
DESCRIPTION:Cubs vs. Storm Chasers\n\nFollow on MiLB First Pitch: https://stza.co/+vKDc-2G\n\nShop: https://stza.co/+vKDc-1a\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144535Z
LAST-MODIFIED:20180213T144535Z
TRANSP:OPAQUE
END:VEVENT
* Cubs vs. Storm Chasers
<2018-05-20 Sun 13:08-16:08>
:PROPERTIES:
:ID:       5Tzt5rmKGmyb7Yxfs8wlRJ07@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Cubs vs. Storm Chasers Cubs vs. Storm Chasers

Follow on MiLB First Pitch  https //stza.co/+vKDe-3X

Shop  https //stza.co/+vKDe-2v

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Cubs vs. Storm Chasers
END:VALARM
DTSTART:20180520T180800Z
DTEND:20180520T210800Z
UID:5Tzt5rmKGmyb7Yxfs8wlRJ07@stanza.co
SUMMARY:Cubs vs. Storm Chasers
DESCRIPTION:Cubs vs. Storm Chasers\n\nFollow on MiLB First Pitch: https://stza.co/+vKDe-3X\n\nShop: https://stza.co/+vKDe-2v\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144535Z
LAST-MODIFIED:20180213T144535Z
TRANSP:OPAQUE
END:VEVENT
* Cubs @ Express
<2018-05-21 Mon 19:05-22:05>
:PROPERTIES:
:ID:       4ICYr5IgOjnHUJwmEyYx9RdX@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Cubs @ Express Cubs @ Express

Follow on MiLB First Pitch  https //stza.co/+vKFq-33

Shop  https //stza.co/+vKFq-2o

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Cubs @ Express
END:VALARM
DTSTART:20180522T000500Z
DTEND:20180522T030500Z
UID:4ICYr5IgOjnHUJwmEyYx9RdX@stanza.co
SUMMARY:Cubs @ Express
DESCRIPTION:Cubs @ Express\n\nFollow on MiLB First Pitch: https://stza.co/+vKFq-33\n\nShop: https://stza.co/+vKFq-2o\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144535Z
LAST-MODIFIED:20180213T144535Z
TRANSP:OPAQUE
END:VEVENT
* Cubs @ Express
<2018-05-22 Tue 19:05-22:05>
:PROPERTIES:
:ID:       sV7EcPVGzuvODLdf1wOAVTKg@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Cubs @ Express Cubs @ Express

Follow on MiLB First Pitch  https //stza.co/+vKFr-2T

Shop  https //stza.co/+vKFr-g

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Cubs @ Express
END:VALARM
DTSTART:20180523T000500Z
DTEND:20180523T030500Z
UID:sV7EcPVGzuvODLdf1wOAVTKg@stanza.co
SUMMARY:Cubs @ Express
DESCRIPTION:Cubs @ Express\n\nFollow on MiLB First Pitch: https://stza.co/+vKFr-2T\n\nShop: https://stza.co/+vKFr-g\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144535Z
LAST-MODIFIED:20180213T144535Z
TRANSP:OPAQUE
END:VEVENT
* Cubs @ Express
<2018-05-23 Wed 19:05-22:05>
:PROPERTIES:
:ID:       sxKyEKcDobdChAaH08e-rFYL@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Cubs @ Express Cubs @ Express

Follow on MiLB First Pitch  https //stza.co/+vKFs-1c

Shop  https //stza.co/+vKFs-1A

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Cubs @ Express
END:VALARM
DTSTART:20180524T000500Z
DTEND:20180524T030500Z
UID:sxKyEKcDobdChAaH08e-rFYL@stanza.co
SUMMARY:Cubs @ Express
DESCRIPTION:Cubs @ Express\n\nFollow on MiLB First Pitch: https://stza.co/+vKFs-1c\n\nShop: https://stza.co/+vKFs-1A\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144535Z
LAST-MODIFIED:20180213T144535Z
TRANSP:OPAQUE
END:VEVENT
* Cubs @ Express
<2018-05-24 Thu 19:05-22:05>
:PROPERTIES:
:ID:       W_eT8qh8FhOmdLnyE1_-n7Zi@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Cubs @ Express Cubs @ Express

Follow on MiLB First Pitch  https //stza.co/+vKFt-1r

Shop  https //stza.co/+vKFt-39

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Cubs @ Express
END:VALARM
DTSTART:20180525T000500Z
DTEND:20180525T030500Z
UID:W_eT8qh8FhOmdLnyE1_-n7Zi@stanza.co
SUMMARY:Cubs @ Express
DESCRIPTION:Cubs @ Express\n\nFollow on MiLB First Pitch: https://stza.co/+vKFt-1r\n\nShop: https://stza.co/+vKFt-39\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144535Z
LAST-MODIFIED:20180213T144535Z
TRANSP:OPAQUE
END:VEVENT
* Cubs vs. Baby Cakes
<2018-05-25 Fri 19:08-22:08>
:PROPERTIES:
:ID:       sq_O0Lr-tv9rJoIpKmj0GD94@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Cubs vs. Baby Cakes Cubs vs. Baby Cakes

Follow on MiLB First Pitch  https //stza.co/+vKDg-2_

Shop  https //stza.co/+vKDg-3b

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Cubs vs. Baby Cakes
END:VALARM
DTSTART:20180526T000800Z
DTEND:20180526T030800Z
UID:sq_O0Lr-tv9rJoIpKmj0GD94@stanza.co
SUMMARY:Cubs vs. Baby Cakes
DESCRIPTION:Cubs vs. Baby Cakes\n\nFollow on MiLB First Pitch: https://stza.co/+vKDg-2_\n\nShop: https://stza.co/+vKDg-3b\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144535Z
LAST-MODIFIED:20180213T144535Z
TRANSP:OPAQUE
END:VEVENT
* Cubs vs. Baby Cakes
<2018-05-26 Sat 19:08-22:08>
:PROPERTIES:
:ID:       sx1CgVLapXZI3o07BvKDrY6b@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Cubs vs. Baby Cakes Cubs vs. Baby Cakes

Follow on MiLB First Pitch  https //stza.co/+vKDi-2H

Shop  https //stza.co/+vKDi-2B

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Cubs vs. Baby Cakes
END:VALARM
DTSTART:20180527T000800Z
DTEND:20180527T030800Z
UID:sx1CgVLapXZI3o07BvKDrY6b@stanza.co
SUMMARY:Cubs vs. Baby Cakes
DESCRIPTION:Cubs vs. Baby Cakes\n\nFollow on MiLB First Pitch: https://stza.co/+vKDi-2H\n\nShop: https://stza.co/+vKDi-2B\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144535Z
LAST-MODIFIED:20180213T144535Z
TRANSP:OPAQUE
END:VEVENT
* Cubs vs. Baby Cakes
<2018-05-27 Sun 13:08-16:08>
:PROPERTIES:
:ID:       4Kj2YXbjZmbuZg3_k8Y3-rhT@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Cubs vs. Baby Cakes Cubs vs. Baby Cakes

Follow on MiLB First Pitch  https //stza.co/+vKDk-2_

Shop  https //stza.co/+vKDk-3Z

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Cubs vs. Baby Cakes
END:VALARM
DTSTART:20180527T180800Z
DTEND:20180527T210800Z
UID:4Kj2YXbjZmbuZg3_k8Y3-rhT@stanza.co
SUMMARY:Cubs vs. Baby Cakes
DESCRIPTION:Cubs vs. Baby Cakes\n\nFollow on MiLB First Pitch: https://stza.co/+vKDk-2_\n\nShop: https://stza.co/+vKDk-3Z\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144535Z
LAST-MODIFIED:20180213T144535Z
TRANSP:OPAQUE
END:VEVENT
* Cubs vs. Baby Cakes
<2018-05-28 Mon 13:08-16:08>
:PROPERTIES:
:ID:       ldp00CSSUOgYyhn-gX5-p-4T@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Cubs vs. Baby Cakes Cubs vs. Baby Cakes

Follow on MiLB First Pitch  https //stza.co/+vKDm-1h

Shop  https //stza.co/+vKDm-M

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Cubs vs. Baby Cakes
END:VALARM
DTSTART:20180528T180800Z
DTEND:20180528T210800Z
UID:ldp00CSSUOgYyhn-gX5-p-4T@stanza.co
SUMMARY:Cubs vs. Baby Cakes
DESCRIPTION:Cubs vs. Baby Cakes\n\nFollow on MiLB First Pitch: https://stza.co/+vKDm-1h\n\nShop: https://stza.co/+vKDm-M\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144535Z
LAST-MODIFIED:20180213T144535Z
TRANSP:OPAQUE
END:VEVENT
* Cubs vs. Baby Cakes
<2018-05-29 Tue 12:08-15:08>
:PROPERTIES:
:ID:       DJQGclNoKnFdYF5bYBZkCbLN@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Cubs vs. Baby Cakes Cubs vs. Baby Cakes

Follow on MiLB First Pitch  https //stza.co/+vKDn-8

Shop  https //stza.co/+vKDn-2$

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Cubs vs. Baby Cakes
END:VALARM
DTSTART:20180529T170800Z
DTEND:20180529T200800Z
UID:DJQGclNoKnFdYF5bYBZkCbLN@stanza.co
SUMMARY:Cubs vs. Baby Cakes
DESCRIPTION:Cubs vs. Baby Cakes\n\nFollow on MiLB First Pitch: https://stza.co/+vKDn-8\n\nShop: https://stza.co/+vKDn-2$\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144535Z
LAST-MODIFIED:20180213T144535Z
TRANSP:OPAQUE
END:VEVENT
* Cubs @ Sky Sox
<2018-05-30 Wed 19:40-22:40>
:PROPERTIES:
:ID:       bgYig0bXuZeBb22eKaq_M1os@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Cubs @ Sky Sox Cubs @ Sky Sox

Follow on MiLB First Pitch  https //stza.co/+wmCN-2i

Shop  https //stza.co/+wmCN-1F

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Cubs @ Sky Sox
END:VALARM
DTSTART:20180531T004000Z
DTEND:20180531T034000Z
UID:bgYig0bXuZeBb22eKaq_M1os@stanza.co
SUMMARY:Cubs @ Sky Sox
DESCRIPTION:Cubs @ Sky Sox\n\nFollow on MiLB First Pitch: https://stza.co/+wmCN-2i\n\nShop: https://stza.co/+wmCN-1F\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144535Z
LAST-MODIFIED:20180213T144535Z
TRANSP:OPAQUE
END:VEVENT
* Cubs @ Sky Sox
<2018-05-31 Thu 19:40-22:40>
:PROPERTIES:
:ID:       ou0rTjRqBDC4En6QZ0Pyjwp7@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Cubs @ Sky Sox Cubs @ Sky Sox

Follow on MiLB First Pitch  https //stza.co/+wmCO-E

Shop  https //stza.co/+wmCO-2N

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Cubs @ Sky Sox
END:VALARM
DTSTART:20180601T004000Z
DTEND:20180601T034000Z
UID:ou0rTjRqBDC4En6QZ0Pyjwp7@stanza.co
SUMMARY:Cubs @ Sky Sox
DESCRIPTION:Cubs @ Sky Sox\n\nFollow on MiLB First Pitch: https://stza.co/+wmCO-E\n\nShop: https://stza.co/+wmCO-2N\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144535Z
LAST-MODIFIED:20180213T144535Z
TRANSP:OPAQUE
END:VEVENT
* Cubs @ Sky Sox
<2018-06-01 Fri 19:40-22:40>
:PROPERTIES:
:ID:       ked1pD7vQ0MvnQuT1IOXPllb@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Cubs @ Sky Sox Cubs @ Sky Sox

Follow on MiLB First Pitch  https //stza.co/+wmCP-3k

Shop  https //stza.co/+wmCP-3s

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Cubs @ Sky Sox
END:VALARM
DTSTART:20180602T004000Z
DTEND:20180602T034000Z
UID:ked1pD7vQ0MvnQuT1IOXPllb@stanza.co
SUMMARY:Cubs @ Sky Sox
DESCRIPTION:Cubs @ Sky Sox\n\nFollow on MiLB First Pitch: https://stza.co/+wmCP-3k\n\nShop: https://stza.co/+wmCP-3s\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144535Z
LAST-MODIFIED:20180213T144535Z
TRANSP:OPAQUE
END:VEVENT
* Cubs @ Sky Sox
<2018-06-02 Sat 19:00-22:00>
:PROPERTIES:
:ID:       Khgu3p2iEumwbECD-asP1rzH@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Cubs @ Sky Sox Cubs @ Sky Sox

Follow on MiLB First Pitch  https //stza.co/+wmCQ-3q

Shop  https //stza.co/+wmCQ-2$

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Cubs @ Sky Sox
END:VALARM
DTSTART:20180603T000000Z
DTEND:20180603T030000Z
UID:Khgu3p2iEumwbECD-asP1rzH@stanza.co
SUMMARY:Cubs @ Sky Sox
DESCRIPTION:Cubs @ Sky Sox\n\nFollow on MiLB First Pitch: https://stza.co/+wmCQ-3q\n\nShop: https://stza.co/+wmCQ-2$\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144535Z
LAST-MODIFIED:20180213T144535Z
TRANSP:OPAQUE
END:VEVENT
* Cubs @ Sky Sox
<2018-06-03 Sun 14:00-17:00>
:PROPERTIES:
:ID:       j4INg81fPA-UTLLKKAEMZPTY@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Cubs @ Sky Sox Cubs @ Sky Sox

Follow on MiLB First Pitch  https //stza.co/+xZT$-1u

Shop  https //stza.co/+xZT$-J

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Cubs @ Sky Sox
END:VALARM
DTSTART:20180603T190000Z
DTEND:20180603T220000Z
UID:j4INg81fPA-UTLLKKAEMZPTY@stanza.co
SUMMARY:Cubs @ Sky Sox
DESCRIPTION:Cubs @ Sky Sox\n\nFollow on MiLB First Pitch: https://stza.co/+xZT$-1u\n\nShop: https://stza.co/+xZT$-J\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144535Z
LAST-MODIFIED:20180213T144535Z
TRANSP:OPAQUE
END:VEVENT
* Cubs vs. Isotopes
<2018-06-05 Tue 19:08-22:08>
:PROPERTIES:
:ID:       dt-IPrO2ptPMao8vxEemDwlv@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Cubs vs. Isotopes Cubs vs. Isotopes

Follow on MiLB First Pitch  https //stza.co/+vKDq-2T

Shop  https //stza.co/+vKDq-3w

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Cubs vs. Isotopes
END:VALARM
DTSTART:20180606T000800Z
DTEND:20180606T030800Z
UID:dt-IPrO2ptPMao8vxEemDwlv@stanza.co
SUMMARY:Cubs vs. Isotopes
DESCRIPTION:Cubs vs. Isotopes\n\nFollow on MiLB First Pitch: https://stza.co/+vKDq-2T\n\nShop: https://stza.co/+vKDq-3w\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144535Z
LAST-MODIFIED:20180213T144535Z
TRANSP:OPAQUE
END:VEVENT
* Cubs vs. Isotopes
<2018-06-06 Wed 12:08-15:08>
:PROPERTIES:
:ID:       _NBO-6k8S9n4cW3hdYXo8w_3@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Cubs vs. Isotopes Cubs vs. Isotopes

Follow on MiLB First Pitch  https //stza.co/+vKDs-3Z

Shop  https //stza.co/+vKDs-3U

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Cubs vs. Isotopes
END:VALARM
DTSTART:20180606T170800Z
DTEND:20180606T200800Z
UID:_NBO-6k8S9n4cW3hdYXo8w_3@stanza.co
SUMMARY:Cubs vs. Isotopes
DESCRIPTION:Cubs vs. Isotopes\n\nFollow on MiLB First Pitch: https://stza.co/+vKDs-3Z\n\nShop: https://stza.co/+vKDs-3U\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144535Z
LAST-MODIFIED:20180213T144535Z
TRANSP:OPAQUE
END:VEVENT
* Cubs vs. Isotopes
<2018-06-07 Thu 19:08-22:08>
:PROPERTIES:
:ID:       B9iEn5sJ3SZVciM4iGcfjaQR@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Cubs vs. Isotopes Cubs vs. Isotopes

Follow on MiLB First Pitch  https //stza.co/+vKDu-3p

Shop  https //stza.co/+vKDu-2h

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Cubs vs. Isotopes
END:VALARM
DTSTART:20180608T000800Z
DTEND:20180608T030800Z
UID:B9iEn5sJ3SZVciM4iGcfjaQR@stanza.co
SUMMARY:Cubs vs. Isotopes
DESCRIPTION:Cubs vs. Isotopes\n\nFollow on MiLB First Pitch: https://stza.co/+vKDu-3p\n\nShop: https://stza.co/+vKDu-2h\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144535Z
LAST-MODIFIED:20180213T144535Z
TRANSP:OPAQUE
END:VEVENT
* Cubs vs. Chihuahuas
<2018-06-08 Fri 19:08-22:08>
:PROPERTIES:
:ID:       04lnseEhmOp2U5DMCGAyPJ9g@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Cubs vs. Chihuahuas Cubs vs. Chihuahuas

Follow on MiLB First Pitch  https //stza.co/+vKDw-Q

Shop  https //stza.co/+vKDw-2G

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Cubs vs. Chihuahuas
END:VALARM
DTSTART:20180609T000800Z
DTEND:20180609T030800Z
UID:04lnseEhmOp2U5DMCGAyPJ9g@stanza.co
SUMMARY:Cubs vs. Chihuahuas
DESCRIPTION:Cubs vs. Chihuahuas\n\nFollow on MiLB First Pitch: https://stza.co/+vKDw-Q\n\nShop: https://stza.co/+vKDw-2G\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144535Z
LAST-MODIFIED:20180213T144535Z
TRANSP:OPAQUE
END:VEVENT
* Cubs vs. Chihuahuas
<2018-06-09 Sat 19:08-22:08>
:PROPERTIES:
:ID:       i-gN03aoYSYd4PQw16aJgRlp@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Cubs vs. Chihuahuas Cubs vs. Chihuahuas

Follow on MiLB First Pitch  https //stza.co/+vKDx-2l

Shop  https //stza.co/+vKDx-v

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Cubs vs. Chihuahuas
END:VALARM
DTSTART:20180610T000800Z
DTEND:20180610T030800Z
UID:i-gN03aoYSYd4PQw16aJgRlp@stanza.co
SUMMARY:Cubs vs. Chihuahuas
DESCRIPTION:Cubs vs. Chihuahuas\n\nFollow on MiLB First Pitch: https://stza.co/+vKDx-2l\n\nShop: https://stza.co/+vKDx-v\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144535Z
LAST-MODIFIED:20180213T144535Z
TRANSP:OPAQUE
END:VEVENT
* Cubs vs. Chihuahuas
<2018-06-10 Sun 13:08-16:08>
:PROPERTIES:
:ID:       QhdzQLHItBd1BDEK4jFa7gvy@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Cubs vs. Chihuahuas Cubs vs. Chihuahuas

Follow on MiLB First Pitch  https //stza.co/+xDLr-2b

Shop  https //stza.co/+xDLr-m

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Cubs vs. Chihuahuas
END:VALARM
DTSTART:20180610T180800Z
DTEND:20180610T210800Z
UID:QhdzQLHItBd1BDEK4jFa7gvy@stanza.co
SUMMARY:Cubs vs. Chihuahuas
DESCRIPTION:Cubs vs. Chihuahuas\n\nFollow on MiLB First Pitch: https://stza.co/+xDLr-2b\n\nShop: https://stza.co/+xDLr-m\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144535Z
LAST-MODIFIED:20180213T144535Z
TRANSP:OPAQUE
END:VEVENT
* Cubs vs. Chihuahuas
<2018-06-11 Mon 12:08-15:08>
:PROPERTIES:
:ID:       rJNY4PvbcbsGNvU9BZxcbHSK@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Cubs vs. Chihuahuas Cubs vs. Chihuahuas

Follow on MiLB First Pitch  https //stza.co/+vKDC-y

Shop  https //stza.co/+vKDC-3u

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Cubs vs. Chihuahuas
END:VALARM
DTSTART:20180611T170800Z
DTEND:20180611T200800Z
UID:rJNY4PvbcbsGNvU9BZxcbHSK@stanza.co
SUMMARY:Cubs vs. Chihuahuas
DESCRIPTION:Cubs vs. Chihuahuas\n\nFollow on MiLB First Pitch: https://stza.co/+vKDC-y\n\nShop: https://stza.co/+vKDC-3u\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144535Z
LAST-MODIFIED:20180213T144535Z
TRANSP:OPAQUE
END:VEVENT
* Cubs @ Aces
<2018-06-13 Wed 21:05>--<2018-06-14 Thu 00:05>
:PROPERTIES:
:ID:       11HXqV0PCBRjzQ8fc7pHfpvh@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Cubs @ Aces Cubs @ Aces

Follow on MiLB First Pitch  https //stza.co/+wjAM-

Shop  https //stza.co/+wjAM-3r

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Cubs @ Aces
END:VALARM
DTSTART:20180614T020500Z
DTEND:20180614T050500Z
UID:11HXqV0PCBRjzQ8fc7pHfpvh@stanza.co
SUMMARY:Cubs @ Aces
DESCRIPTION:Cubs @ Aces\n\nFollow on MiLB First Pitch: https://stza.co/+wjAM-\n\nShop: https://stza.co/+wjAM-3r\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144535Z
LAST-MODIFIED:20180213T144535Z
TRANSP:OPAQUE
END:VEVENT
* Cubs @ Aces
<2018-06-14 Thu 21:05>--<2018-06-15 Fri 00:05>
:PROPERTIES:
:ID:       IvqeE-tlt70mV6uN_-jThOGj@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Cubs @ Aces Cubs @ Aces

Follow on MiLB First Pitch  https //stza.co/+wjAN-33

Shop  https //stza.co/+wjAN-3W

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Cubs @ Aces
END:VALARM
DTSTART:20180615T020500Z
DTEND:20180615T050500Z
UID:IvqeE-tlt70mV6uN_-jThOGj@stanza.co
SUMMARY:Cubs @ Aces
DESCRIPTION:Cubs @ Aces\n\nFollow on MiLB First Pitch: https://stza.co/+wjAN-33\n\nShop: https://stza.co/+wjAN-3W\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144535Z
LAST-MODIFIED:20180213T144535Z
TRANSP:OPAQUE
END:VEVENT
* Cubs @ Aces
<2018-06-15 Fri 21:05>--<2018-06-16 Sat 00:05>
:PROPERTIES:
:ID:       y2zCeEs5iW8SknrtWZ8Ox9oJ@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Cubs @ Aces Cubs @ Aces

Follow on MiLB First Pitch  https //stza.co/+wjAO-2d

Shop  https //stza.co/+wjAO-29

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Cubs @ Aces
END:VALARM
DTSTART:20180616T020500Z
DTEND:20180616T050500Z
UID:y2zCeEs5iW8SknrtWZ8Ox9oJ@stanza.co
SUMMARY:Cubs @ Aces
DESCRIPTION:Cubs @ Aces\n\nFollow on MiLB First Pitch: https://stza.co/+wjAO-2d\n\nShop: https://stza.co/+wjAO-29\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144535Z
LAST-MODIFIED:20180213T144535Z
TRANSP:OPAQUE
END:VEVENT
* Cubs @ Rainiers
<2018-06-16 Sat 19:05-22:05>
:PROPERTIES:
:ID:       u1VZaodHHpahuOpb2wCZFl2K@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Cubs @ Rainiers Cubs @ Rainiers

Follow on MiLB First Pitch  https //stza.co/+wjAT-5

Shop  https //stza.co/+wjAT-3c

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Cubs @ Rainiers
END:VALARM
DTSTART:20180617T000500Z
DTEND:20180617T030500Z
UID:u1VZaodHHpahuOpb2wCZFl2K@stanza.co
SUMMARY:Cubs @ Rainiers
DESCRIPTION:Cubs @ Rainiers\n\nFollow on MiLB First Pitch: https://stza.co/+wjAT-5\n\nShop: https://stza.co/+wjAT-3c\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144535Z
LAST-MODIFIED:20180213T144535Z
TRANSP:OPAQUE
END:VEVENT
* Cubs @ Rainiers
<2018-06-17 Sun 15:35-18:35>
:PROPERTIES:
:ID:       lxJGXMp0Trt2o0-_VVw2ho3Q@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Cubs @ Rainiers Cubs @ Rainiers

Follow on MiLB First Pitch  https //stza.co/+wjAU-1w

Shop  https //stza.co/+wjAU-26

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Cubs @ Rainiers
END:VALARM
DTSTART:20180617T203500Z
DTEND:20180617T233500Z
UID:lxJGXMp0Trt2o0-_VVw2ho3Q@stanza.co
SUMMARY:Cubs @ Rainiers
DESCRIPTION:Cubs @ Rainiers\n\nFollow on MiLB First Pitch: https://stza.co/+wjAU-1w\n\nShop: https://stza.co/+wjAU-26\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144535Z
LAST-MODIFIED:20180213T144535Z
TRANSP:OPAQUE
END:VEVENT
* Cubs @ Rainiers
<2018-06-18 Mon 20:05-23:05>
:PROPERTIES:
:ID:       FRCC64LptwBFFQx2tW4GXwdi@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Cubs @ Rainiers Cubs @ Rainiers

Follow on MiLB First Pitch  https //stza.co/+wjAV-1w

Shop  https //stza.co/+wjAV-C

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Cubs @ Rainiers
END:VALARM
DTSTART:20180619T010500Z
DTEND:20180619T040500Z
UID:FRCC64LptwBFFQx2tW4GXwdi@stanza.co
SUMMARY:Cubs @ Rainiers
DESCRIPTION:Cubs @ Rainiers\n\nFollow on MiLB First Pitch: https://stza.co/+wjAV-1w\n\nShop: https://stza.co/+wjAV-C\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144535Z
LAST-MODIFIED:20180213T144535Z
TRANSP:OPAQUE
END:VEVENT
* Cubs @ Rainiers
<2018-06-19 Tue 20:05-23:05>
:PROPERTIES:
:ID:       SSg8Ar6XxIhXvjKN9l03stna@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Cubs @ Rainiers Cubs @ Rainiers

Follow on MiLB First Pitch  https //stza.co/+wjAW-d

Shop  https //stza.co/+wjAW-1u

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Cubs @ Rainiers
END:VALARM
DTSTART:20180620T010500Z
DTEND:20180620T040500Z
UID:SSg8Ar6XxIhXvjKN9l03stna@stanza.co
SUMMARY:Cubs @ Rainiers
DESCRIPTION:Cubs @ Rainiers\n\nFollow on MiLB First Pitch: https://stza.co/+wjAW-d\n\nShop: https://stza.co/+wjAW-1u\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144535Z
LAST-MODIFIED:20180213T144535Z
TRANSP:OPAQUE
END:VEVENT
* Cubs vs. Sky Sox
<2018-06-21 Thu 19:08-22:08>
:PROPERTIES:
:ID:       LhX9hYbhh6ri8ekrj4zV0pdu@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Cubs vs. Sky Sox Cubs vs. Sky Sox

Follow on MiLB First Pitch  https //stza.co/+vKDE-2e

Shop  https //stza.co/+vKDE-37

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Cubs vs. Sky Sox
END:VALARM
DTSTART:20180622T000800Z
DTEND:20180622T030800Z
UID:LhX9hYbhh6ri8ekrj4zV0pdu@stanza.co
SUMMARY:Cubs vs. Sky Sox
DESCRIPTION:Cubs vs. Sky Sox\n\nFollow on MiLB First Pitch: https://stza.co/+vKDE-2e\n\nShop: https://stza.co/+vKDE-37\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144535Z
LAST-MODIFIED:20180213T144535Z
TRANSP:OPAQUE
END:VEVENT
* Cubs vs. Sky Sox
<2018-06-22 Fri 19:08-22:08>
:PROPERTIES:
:ID:       B6FWHNt5vd-v8wDkpD46z0k7@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Cubs vs. Sky Sox Cubs vs. Sky Sox

Follow on MiLB First Pitch  https //stza.co/+vKDG-3m

Shop  https //stza.co/+vKDG-M

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Cubs vs. Sky Sox
END:VALARM
DTSTART:20180623T000800Z
DTEND:20180623T030800Z
UID:B6FWHNt5vd-v8wDkpD46z0k7@stanza.co
SUMMARY:Cubs vs. Sky Sox
DESCRIPTION:Cubs vs. Sky Sox\n\nFollow on MiLB First Pitch: https://stza.co/+vKDG-3m\n\nShop: https://stza.co/+vKDG-M\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144535Z
LAST-MODIFIED:20180213T144535Z
TRANSP:OPAQUE
END:VEVENT
* Cubs vs. Sky Sox
<2018-06-23 Sat 12:08-15:08>
:PROPERTIES:
:ID:       5GYmmy4G8q6335r4iJm9NTww@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Cubs vs. Sky Sox Cubs vs. Sky Sox

Follow on MiLB First Pitch  https //stza.co/+xzzV-3h

Shop  https //stza.co/+xzzV-z

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Cubs vs. Sky Sox
END:VALARM
DTSTART:20180623T170800Z
DTEND:20180623T200800Z
UID:5GYmmy4G8q6335r4iJm9NTww@stanza.co
SUMMARY:Cubs vs. Sky Sox
DESCRIPTION:Cubs vs. Sky Sox\n\nFollow on MiLB First Pitch: https://stza.co/+xzzV-3h\n\nShop: https://stza.co/+xzzV-z\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144535Z
LAST-MODIFIED:20180213T144535Z
TRANSP:OPAQUE
END:VEVENT
* Cubs vs. Sky Sox
<2018-06-23 Sat 19:08-22:08>
:PROPERTIES:
:ID:       Be9BVNLPxFYo0uGAkLfgwE3C@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Cubs vs. Sky Sox Cubs vs. Sky Sox

Follow on MiLB First Pitch  https //stza.co/+xzzY-1M

Shop  https //stza.co/+xzzY-o

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Cubs vs. Sky Sox
END:VALARM
DTSTART:20180624T000800Z
DTEND:20180624T030800Z
UID:Be9BVNLPxFYo0uGAkLfgwE3C@stanza.co
SUMMARY:Cubs vs. Sky Sox
DESCRIPTION:Cubs vs. Sky Sox\n\nFollow on MiLB First Pitch: https://stza.co/+xzzY-1M\n\nShop: https://stza.co/+xzzY-o\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144535Z
LAST-MODIFIED:20180213T144535Z
TRANSP:OPAQUE
END:VEVENT
* Cubs vs. Sky Sox
<2018-06-24 Sun 13:08-16:08>
:PROPERTIES:
:ID:       T1gsP8WvJSIYUpdZUXgfGYOi@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Cubs vs. Sky Sox Cubs vs. Sky Sox

Follow on MiLB First Pitch  https //stza.co/+vKDM-3m

Shop  https //stza.co/+vKDM-N

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Cubs vs. Sky Sox
END:VALARM
DTSTART:20180624T180800Z
DTEND:20180624T210800Z
UID:T1gsP8WvJSIYUpdZUXgfGYOi@stanza.co
SUMMARY:Cubs vs. Sky Sox
DESCRIPTION:Cubs vs. Sky Sox\n\nFollow on MiLB First Pitch: https://stza.co/+vKDM-3m\n\nShop: https://stza.co/+vKDM-N\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144535Z
LAST-MODIFIED:20180213T144535Z
TRANSP:OPAQUE
END:VEVENT
* Cubs @ Baby Cakes
<2018-06-25 Mon 19:00-22:00>
:PROPERTIES:
:ID:       -iS9u1TtXUzx0FAPtS9MoBMn@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Cubs @ Baby Cakes Cubs @ Baby Cakes

Follow on MiLB First Pitch  https //stza.co/+whEf-2u

Shop  https //stza.co/+whEf-2m

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Cubs @ Baby Cakes
END:VALARM
DTSTART:20180626T000000Z
DTEND:20180626T030000Z
UID:-iS9u1TtXUzx0FAPtS9MoBMn@stanza.co
SUMMARY:Cubs @ Baby Cakes
DESCRIPTION:Cubs @ Baby Cakes\n\nFollow on MiLB First Pitch: https://stza.co/+whEf-2u\n\nShop: https://stza.co/+whEf-2m\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144535Z
LAST-MODIFIED:20180213T144535Z
TRANSP:OPAQUE
END:VEVENT
* Cubs @ Baby Cakes
<2018-06-26 Tue 19:00-22:00>
:PROPERTIES:
:ID:       9ZC6ehhDDiEdO1heelBV4VI2@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Cubs @ Baby Cakes Cubs @ Baby Cakes

Follow on MiLB First Pitch  https //stza.co/+whEg-J

Shop  https //stza.co/+whEg-1$

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Cubs @ Baby Cakes
END:VALARM
DTSTART:20180627T000000Z
DTEND:20180627T030000Z
UID:9ZC6ehhDDiEdO1heelBV4VI2@stanza.co
SUMMARY:Cubs @ Baby Cakes
DESCRIPTION:Cubs @ Baby Cakes\n\nFollow on MiLB First Pitch: https://stza.co/+whEg-J\n\nShop: https://stza.co/+whEg-1$\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144535Z
LAST-MODIFIED:20180213T144535Z
TRANSP:OPAQUE
END:VEVENT
* Cubs @ Baby Cakes
<2018-06-27 Wed 12:00-15:00>
:PROPERTIES:
:ID:       V1c64nVpSPJ1z51-retmdpqz@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Cubs @ Baby Cakes Cubs @ Baby Cakes

Follow on MiLB First Pitch  https //stza.co/+whEh-2U

Shop  https //stza.co/+whEh-e

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Cubs @ Baby Cakes
END:VALARM
DTSTART:20180627T170000Z
DTEND:20180627T200000Z
UID:V1c64nVpSPJ1z51-retmdpqz@stanza.co
SUMMARY:Cubs @ Baby Cakes
DESCRIPTION:Cubs @ Baby Cakes\n\nFollow on MiLB First Pitch: https://stza.co/+whEh-2U\n\nShop: https://stza.co/+whEh-e\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144535Z
LAST-MODIFIED:20180213T144535Z
TRANSP:OPAQUE
END:VEVENT
* Cubs @ Baby Cakes
<2018-06-28 Thu 19:00-22:00>
:PROPERTIES:
:ID:       b15OGVRC9q5qzvV9Lzr3zzey@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Cubs @ Baby Cakes Cubs @ Baby Cakes

Follow on MiLB First Pitch  https //stza.co/+whEi-10

Shop  https //stza.co/+whEi-9

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Cubs @ Baby Cakes
END:VALARM
DTSTART:20180629T000000Z
DTEND:20180629T030000Z
UID:b15OGVRC9q5qzvV9Lzr3zzey@stanza.co
SUMMARY:Cubs @ Baby Cakes
DESCRIPTION:Cubs @ Baby Cakes\n\nFollow on MiLB First Pitch: https://stza.co/+whEi-10\n\nShop: https://stza.co/+whEi-9\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144535Z
LAST-MODIFIED:20180213T144535Z
TRANSP:OPAQUE
END:VEVENT
* Cubs vs. Redbirds
<2018-06-29 Fri 19:08-22:08>
:PROPERTIES:
:ID:       xpZ0w05zvjTwWszXQoyFJSeg@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Cubs vs. Redbirds Cubs vs. Redbirds

Follow on MiLB First Pitch  https //stza.co/+vKDN-1b

Shop  https //stza.co/+vKDN-3S

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Cubs vs. Redbirds
END:VALARM
DTSTART:20180630T000800Z
DTEND:20180630T030800Z
UID:xpZ0w05zvjTwWszXQoyFJSeg@stanza.co
SUMMARY:Cubs vs. Redbirds
DESCRIPTION:Cubs vs. Redbirds\n\nFollow on MiLB First Pitch: https://stza.co/+vKDN-1b\n\nShop: https://stza.co/+vKDN-3S\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144535Z
LAST-MODIFIED:20180213T144535Z
TRANSP:OPAQUE
END:VEVENT
* Cubs vs. Redbirds
<2018-06-30 Sat 19:08-22:08>
:PROPERTIES:
:ID:       nuwGXHRBGWB1YxE6iJN-6B6b@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Cubs vs. Redbirds Cubs vs. Redbirds

Follow on MiLB First Pitch  https //stza.co/+vKDP-2k

Shop  https //stza.co/+vKDP-2K

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Cubs vs. Redbirds
END:VALARM
DTSTART:20180701T000800Z
DTEND:20180701T030800Z
UID:nuwGXHRBGWB1YxE6iJN-6B6b@stanza.co
SUMMARY:Cubs vs. Redbirds
DESCRIPTION:Cubs vs. Redbirds\n\nFollow on MiLB First Pitch: https://stza.co/+vKDP-2k\n\nShop: https://stza.co/+vKDP-2K\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144535Z
LAST-MODIFIED:20180213T144535Z
TRANSP:OPAQUE
END:VEVENT
* Cubs vs. Redbirds
<2018-07-01 Sun 13:08-16:08>
:PROPERTIES:
:ID:       wnxvZByArl5YO7LfMSgJypIQ@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Cubs vs. Redbirds Cubs vs. Redbirds

Follow on MiLB First Pitch  https //stza.co/+wHrF-n

Shop  https //stza.co/+wHrF-2j

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Cubs vs. Redbirds
END:VALARM
DTSTART:20180701T180800Z
DTEND:20180701T210800Z
UID:wnxvZByArl5YO7LfMSgJypIQ@stanza.co
SUMMARY:Cubs vs. Redbirds
DESCRIPTION:Cubs vs. Redbirds\n\nFollow on MiLB First Pitch: https://stza.co/+wHrF-n\n\nShop: https://stza.co/+wHrF-2j\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144535Z
LAST-MODIFIED:20180213T144535Z
TRANSP:OPAQUE
END:VEVENT
* Cubs vs. Redbirds
<2018-07-02 Mon 19:08-22:08>
:PROPERTIES:
:ID:       0gZgO4HWQoRgHP9KjXGvAgJh@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Cubs vs. Redbirds Cubs vs. Redbirds

Follow on MiLB First Pitch  https //stza.co/+vKDU-3p

Shop  https //stza.co/+vKDU-2n

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Cubs vs. Redbirds
END:VALARM
DTSTART:20180703T000800Z
DTEND:20180703T030800Z
UID:0gZgO4HWQoRgHP9KjXGvAgJh@stanza.co
SUMMARY:Cubs vs. Redbirds
DESCRIPTION:Cubs vs. Redbirds\n\nFollow on MiLB First Pitch: https://stza.co/+vKDU-3p\n\nShop: https://stza.co/+vKDU-2n\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144535Z
LAST-MODIFIED:20180213T144535Z
TRANSP:OPAQUE
END:VEVENT
* Cubs vs. Redbirds
<2018-07-03 Tue 19:08-22:08>
:PROPERTIES:
:ID:       10PMD13sgjlg8iXIdahjqzlC@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Cubs vs. Redbirds Cubs vs. Redbirds

Follow on MiLB First Pitch  https //stza.co/+vKDW-S

Shop  https //stza.co/+vKDW-1j

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Cubs vs. Redbirds
END:VALARM
DTSTART:20180704T000800Z
DTEND:20180704T030800Z
UID:10PMD13sgjlg8iXIdahjqzlC@stanza.co
SUMMARY:Cubs vs. Redbirds
DESCRIPTION:Cubs vs. Redbirds\n\nFollow on MiLB First Pitch: https://stza.co/+vKDW-S\n\nShop: https://stza.co/+vKDW-1j\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144535Z
LAST-MODIFIED:20180213T144535Z
TRANSP:OPAQUE
END:VEVENT
* Cubs @ Sounds
<2018-07-04 Wed 19:05-22:05>
:PROPERTIES:
:ID:       kq6L6UIKFhwlVu2PDL4t0P4E@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Cubs @ Sounds Cubs @ Sounds

Follow on MiLB First Pitch  https //stza.co/+whE9-1z

Shop  https //stza.co/+whE9-3a

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Cubs @ Sounds
END:VALARM
DTSTART:20180705T000500Z
DTEND:20180705T030500Z
UID:kq6L6UIKFhwlVu2PDL4t0P4E@stanza.co
SUMMARY:Cubs @ Sounds
DESCRIPTION:Cubs @ Sounds\n\nFollow on MiLB First Pitch: https://stza.co/+whE9-1z\n\nShop: https://stza.co/+whE9-3a\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144535Z
LAST-MODIFIED:20180213T144535Z
TRANSP:OPAQUE
END:VEVENT
* Cubs @ Sounds
<2018-07-05 Thu 19:05-22:05>
:PROPERTIES:
:ID:       cvI0f_9uHpNRuP4Yj5kv-mxj@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Cubs @ Sounds Cubs @ Sounds

Follow on MiLB First Pitch  https //stza.co/+whEb-3u

Shop  https //stza.co/+whEb-2m

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Cubs @ Sounds
END:VALARM
DTSTART:20180706T000500Z
DTEND:20180706T030500Z
UID:cvI0f_9uHpNRuP4Yj5kv-mxj@stanza.co
SUMMARY:Cubs @ Sounds
DESCRIPTION:Cubs @ Sounds\n\nFollow on MiLB First Pitch: https://stza.co/+whEb-3u\n\nShop: https://stza.co/+whEb-2m\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144535Z
LAST-MODIFIED:20180213T144535Z
TRANSP:OPAQUE
END:VEVENT
* Cubs @ Sounds
<2018-07-06 Fri 19:05-22:05>
:PROPERTIES:
:ID:       ZmM-3mXxy_0ZopERha1fO4pT@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Cubs @ Sounds Cubs @ Sounds

Follow on MiLB First Pitch  https //stza.co/+whEc-B

Shop  https //stza.co/+whEc-1G

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Cubs @ Sounds
END:VALARM
DTSTART:20180707T000500Z
DTEND:20180707T030500Z
UID:ZmM-3mXxy_0ZopERha1fO4pT@stanza.co
SUMMARY:Cubs @ Sounds
DESCRIPTION:Cubs @ Sounds\n\nFollow on MiLB First Pitch: https://stza.co/+whEc-B\n\nShop: https://stza.co/+whEc-1G\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144535Z
LAST-MODIFIED:20180213T144535Z
TRANSP:OPAQUE
END:VEVENT
* Cubs @ Sounds
<2018-07-07 Sat 19:05-22:05>
:PROPERTIES:
:ID:       KScY_gdhVVvHvH_KriptlTNc@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Cubs @ Sounds Cubs @ Sounds

Follow on MiLB First Pitch  https //stza.co/+whEd-8

Shop  https //stza.co/+whEd-1T

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Cubs @ Sounds
END:VALARM
DTSTART:20180708T000500Z
DTEND:20180708T030500Z
UID:KScY_gdhVVvHvH_KriptlTNc@stanza.co
SUMMARY:Cubs @ Sounds
DESCRIPTION:Cubs @ Sounds\n\nFollow on MiLB First Pitch: https://stza.co/+whEd-8\n\nShop: https://stza.co/+whEd-1T\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144535Z
LAST-MODIFIED:20180213T144535Z
TRANSP:OPAQUE
END:VEVENT
* Cubs @ Sounds
<2018-07-08 Sun 18:15-21:15>
:PROPERTIES:
:ID:       DwMZrC5n2JHsoPAsNjQ0CyqH@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Cubs @ Sounds Cubs @ Sounds

Follow on MiLB First Pitch  https //stza.co/+whEe-Z

Shop  https //stza.co/+whEe-2y

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Cubs @ Sounds
END:VALARM
DTSTART:20180708T231500Z
DTEND:20180709T021500Z
UID:DwMZrC5n2JHsoPAsNjQ0CyqH@stanza.co
SUMMARY:Cubs @ Sounds
DESCRIPTION:Cubs @ Sounds\n\nFollow on MiLB First Pitch: https://stza.co/+whEe-Z\n\nShop: https://stza.co/+whEe-2y\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144535Z
LAST-MODIFIED:20180213T144535Z
TRANSP:OPAQUE
END:VEVENT
* Cubs vs. Sounds
<2018-07-12 Thu 19:08-22:08>
:PROPERTIES:
:ID:       _4zx34Xp7-Ylz-3K2_5PExER@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Cubs vs. Sounds Cubs vs. Sounds

Follow on MiLB First Pitch  https //stza.co/+vKDX-21

Shop  https //stza.co/+vKDX-1t

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Cubs vs. Sounds
END:VALARM
DTSTART:20180713T000800Z
DTEND:20180713T030800Z
UID:_4zx34Xp7-Ylz-3K2_5PExER@stanza.co
SUMMARY:Cubs vs. Sounds
DESCRIPTION:Cubs vs. Sounds\n\nFollow on MiLB First Pitch: https://stza.co/+vKDX-21\n\nShop: https://stza.co/+vKDX-1t\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144535Z
LAST-MODIFIED:20180213T144535Z
TRANSP:OPAQUE
END:VEVENT
* Cubs vs. Sounds
<2018-07-13 Fri 19:08-22:08>
:PROPERTIES:
:ID:       v9VOuiUi6DIO9DImcpU6y72X@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Cubs vs. Sounds Cubs vs. Sounds

Follow on MiLB First Pitch  https //stza.co/+vKDZ-1f

Shop  https //stza.co/+vKDZ-15

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Cubs vs. Sounds
END:VALARM
DTSTART:20180714T000800Z
DTEND:20180714T030800Z
UID:v9VOuiUi6DIO9DImcpU6y72X@stanza.co
SUMMARY:Cubs vs. Sounds
DESCRIPTION:Cubs vs. Sounds\n\nFollow on MiLB First Pitch: https://stza.co/+vKDZ-1f\n\nShop: https://stza.co/+vKDZ-15\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144535Z
LAST-MODIFIED:20180213T144535Z
TRANSP:OPAQUE
END:VEVENT
* Cubs vs. Sounds
<2018-07-14 Sat 19:08-22:08>
:PROPERTIES:
:ID:       P1hGYUL2pfPT3FKxYiHofStZ@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Cubs vs. Sounds Cubs vs. Sounds

Follow on MiLB First Pitch  https //stza.co/+vKE0-N

Shop  https //stza.co/+vKE0-1e

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Cubs vs. Sounds
END:VALARM
DTSTART:20180715T000800Z
DTEND:20180715T030800Z
UID:P1hGYUL2pfPT3FKxYiHofStZ@stanza.co
SUMMARY:Cubs vs. Sounds
DESCRIPTION:Cubs vs. Sounds\n\nFollow on MiLB First Pitch: https://stza.co/+vKE0-N\n\nShop: https://stza.co/+vKE0-1e\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144535Z
LAST-MODIFIED:20180213T144535Z
TRANSP:OPAQUE
END:VEVENT
* Cubs vs. Sounds
<2018-07-15 Sun 13:08-16:08>
:PROPERTIES:
:ID:       N88jLRIPrAxwaZmjdQIZwfJo@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Cubs vs. Sounds Cubs vs. Sounds

Follow on MiLB First Pitch  https //stza.co/+vKE2-2r

Shop  https //stza.co/+vKE2-3c

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Cubs vs. Sounds
END:VALARM
DTSTART:20180715T180800Z
DTEND:20180715T210800Z
UID:N88jLRIPrAxwaZmjdQIZwfJo@stanza.co
SUMMARY:Cubs vs. Sounds
DESCRIPTION:Cubs vs. Sounds\n\nFollow on MiLB First Pitch: https://stza.co/+vKE2-2r\n\nShop: https://stza.co/+vKE2-3c\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144535Z
LAST-MODIFIED:20180213T144535Z
TRANSP:OPAQUE
END:VEVENT
* Cubs @ Redbirds
<2018-07-16 Mon 19:05-22:05>
:PROPERTIES:
:ID:       jfhGiJc_frLr4uNrc5DcmZHd@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Cubs @ Redbirds Cubs @ Redbirds

Follow on MiLB First Pitch  https //stza.co/+wmC_-1D

Shop  https //stza.co/+wmC_-e

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Cubs @ Redbirds
END:VALARM
DTSTART:20180717T000500Z
DTEND:20180717T030500Z
UID:jfhGiJc_frLr4uNrc5DcmZHd@stanza.co
SUMMARY:Cubs @ Redbirds
DESCRIPTION:Cubs @ Redbirds\n\nFollow on MiLB First Pitch: https://stza.co/+wmC_-1D\n\nShop: https://stza.co/+wmC_-e\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144535Z
LAST-MODIFIED:20180213T144535Z
TRANSP:OPAQUE
END:VEVENT
* Cubs @ Redbirds
<2018-07-17 Tue 19:05-22:05>
:PROPERTIES:
:ID:       LkXe39IlXdXc9yAfcGy2NuP3@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Cubs @ Redbirds Cubs @ Redbirds

Follow on MiLB First Pitch  https //stza.co/+wmC$-3A

Shop  https //stza.co/+wmC$-3z

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Cubs @ Redbirds
END:VALARM
DTSTART:20180718T000500Z
DTEND:20180718T030500Z
UID:LkXe39IlXdXc9yAfcGy2NuP3@stanza.co
SUMMARY:Cubs @ Redbirds
DESCRIPTION:Cubs @ Redbirds\n\nFollow on MiLB First Pitch: https://stza.co/+wmC$-3A\n\nShop: https://stza.co/+wmC$-3z\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144535Z
LAST-MODIFIED:20180213T144535Z
TRANSP:OPAQUE
END:VEVENT
* Cubs @ Redbirds
<2018-07-18 Wed 19:05-22:05>
:PROPERTIES:
:ID:       LOaCxm-KuCSSJilYWclmr0ue@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Cubs @ Redbirds Cubs @ Redbirds

Follow on MiLB First Pitch  https //stza.co/+wmD0-2K

Shop  https //stza.co/+wmD0-3B

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Cubs @ Redbirds
END:VALARM
DTSTART:20180719T000500Z
DTEND:20180719T030500Z
UID:LOaCxm-KuCSSJilYWclmr0ue@stanza.co
SUMMARY:Cubs @ Redbirds
DESCRIPTION:Cubs @ Redbirds\n\nFollow on MiLB First Pitch: https://stza.co/+wmD0-2K\n\nShop: https://stza.co/+wmD0-3B\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144535Z
LAST-MODIFIED:20180213T144535Z
TRANSP:OPAQUE
END:VEVENT
* Cubs @ Redbirds
<2018-07-19 Thu 19:05-22:05>
:PROPERTIES:
:ID:       rYG4vPG7muimGuTR0lBlBsAC@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Cubs @ Redbirds Cubs @ Redbirds

Follow on MiLB First Pitch  https //stza.co/+wmD1-1G

Shop  https //stza.co/+wmD1-3U

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Cubs @ Redbirds
END:VALARM
DTSTART:20180720T000500Z
DTEND:20180720T030500Z
UID:rYG4vPG7muimGuTR0lBlBsAC@stanza.co
SUMMARY:Cubs @ Redbirds
DESCRIPTION:Cubs @ Redbirds\n\nFollow on MiLB First Pitch: https://stza.co/+wmD1-1G\n\nShop: https://stza.co/+wmD1-3U\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144535Z
LAST-MODIFIED:20180213T144535Z
TRANSP:OPAQUE
END:VEVENT
* Cubs vs. Baby Cakes
<2018-07-20 Fri 19:08-22:08>
:PROPERTIES:
:ID:       kG5fNsudbV_OXneVWqo84W0I@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Cubs vs. Baby Cakes Cubs vs. Baby Cakes

Follow on MiLB First Pitch  https //stza.co/+vKE3-O

Shop  https //stza.co/+vKE3-1j

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Cubs vs. Baby Cakes
END:VALARM
DTSTART:20180721T000800Z
DTEND:20180721T030800Z
UID:kG5fNsudbV_OXneVWqo84W0I@stanza.co
SUMMARY:Cubs vs. Baby Cakes
DESCRIPTION:Cubs vs. Baby Cakes\n\nFollow on MiLB First Pitch: https://stza.co/+vKE3-O\n\nShop: https://stza.co/+vKE3-1j\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144535Z
LAST-MODIFIED:20180213T144535Z
TRANSP:OPAQUE
END:VEVENT
* Cubs vs. Baby Cakes
<2018-07-21 Sat 19:08-22:08>
:PROPERTIES:
:ID:       ONYrGs6FiLDknp0GGYnHOIiY@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Cubs vs. Baby Cakes Cubs vs. Baby Cakes

Follow on MiLB First Pitch  https //stza.co/+vKE5-2

Shop  https //stza.co/+vKE5-1t

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Cubs vs. Baby Cakes
END:VALARM
DTSTART:20180722T000800Z
DTEND:20180722T030800Z
UID:ONYrGs6FiLDknp0GGYnHOIiY@stanza.co
SUMMARY:Cubs vs. Baby Cakes
DESCRIPTION:Cubs vs. Baby Cakes\n\nFollow on MiLB First Pitch: https://stza.co/+vKE5-2\n\nShop: https://stza.co/+vKE5-1t\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144535Z
LAST-MODIFIED:20180213T144535Z
TRANSP:OPAQUE
END:VEVENT
* Cubs vs. Baby Cakes
<2018-07-22 Sun 13:08-16:08>
:PROPERTIES:
:ID:       KJPkVrlrn2zPQEOfmt0acSX0@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Cubs vs. Baby Cakes Cubs vs. Baby Cakes

Follow on MiLB First Pitch  https //stza.co/+vKE7-3D

Shop  https //stza.co/+vKE7-U

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Cubs vs. Baby Cakes
END:VALARM
DTSTART:20180722T180800Z
DTEND:20180722T210800Z
UID:KJPkVrlrn2zPQEOfmt0acSX0@stanza.co
SUMMARY:Cubs vs. Baby Cakes
DESCRIPTION:Cubs vs. Baby Cakes\n\nFollow on MiLB First Pitch: https://stza.co/+vKE7-3D\n\nShop: https://stza.co/+vKE7-U\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144535Z
LAST-MODIFIED:20180213T144535Z
TRANSP:OPAQUE
END:VEVENT
* Cubs @ Grizzlies
<2018-07-24 Tue 21:05>--<2018-07-25 Wed 00:05>
:PROPERTIES:
:ID:       2PzNQJiW-19JZeEX23KMAnVO@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Cubs @ Grizzlies Cubs @ Grizzlies

Follow on MiLB First Pitch  https //stza.co/+wjAI-P

Shop  https //stza.co/+wjAI-24

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Cubs @ Grizzlies
END:VALARM
DTSTART:20180725T020500Z
DTEND:20180725T050500Z
UID:2PzNQJiW-19JZeEX23KMAnVO@stanza.co
SUMMARY:Cubs @ Grizzlies
DESCRIPTION:Cubs @ Grizzlies\n\nFollow on MiLB First Pitch: https://stza.co/+wjAI-P\n\nShop: https://stza.co/+wjAI-24\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144535Z
LAST-MODIFIED:20180213T144535Z
TRANSP:OPAQUE
END:VEVENT
* Cubs @ Grizzlies
<2018-07-25 Wed 21:05>--<2018-07-26 Thu 00:05>
:PROPERTIES:
:ID:       qX_Nbd_9oz7XT-XvAHkBWC5U@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Cubs @ Grizzlies Cubs @ Grizzlies

Follow on MiLB First Pitch  https //stza.co/+wjAJ-28

Shop  https //stza.co/+wjAJ-39

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Cubs @ Grizzlies
END:VALARM
DTSTART:20180726T020500Z
DTEND:20180726T050500Z
UID:qX_Nbd_9oz7XT-XvAHkBWC5U@stanza.co
SUMMARY:Cubs @ Grizzlies
DESCRIPTION:Cubs @ Grizzlies\n\nFollow on MiLB First Pitch: https://stza.co/+wjAJ-28\n\nShop: https://stza.co/+wjAJ-39\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144535Z
LAST-MODIFIED:20180213T144535Z
TRANSP:OPAQUE
END:VEVENT
* Cubs @ Grizzlies
<2018-07-26 Thu 21:05>--<2018-07-27 Fri 00:05>
:PROPERTIES:
:ID:       9LQDtRWTnAdkFzP0jLT8muht@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Cubs @ Grizzlies Cubs @ Grizzlies

Follow on MiLB First Pitch  https //stza.co/+wjAK-3n

Shop  https //stza.co/+wjAK-D

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Cubs @ Grizzlies
END:VALARM
DTSTART:20180727T020500Z
DTEND:20180727T050500Z
UID:9LQDtRWTnAdkFzP0jLT8muht@stanza.co
SUMMARY:Cubs @ Grizzlies
DESCRIPTION:Cubs @ Grizzlies\n\nFollow on MiLB First Pitch: https://stza.co/+wjAK-3n\n\nShop: https://stza.co/+wjAK-D\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144535Z
LAST-MODIFIED:20180213T144535Z
TRANSP:OPAQUE
END:VEVENT
* Cubs @ River Cats
<2018-07-27 Fri 21:05>--<2018-07-28 Sat 00:05>
:PROPERTIES:
:ID:       ataSqqmUw2TyRS1GV7BGSom-@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Cubs @ River Cats Cubs @ River Cats

Follow on MiLB First Pitch  https //stza.co/+wjAP-3g

Shop  https //stza.co/+wjAP-2e

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Cubs @ River Cats
END:VALARM
DTSTART:20180728T020500Z
DTEND:20180728T050500Z
UID:ataSqqmUw2TyRS1GV7BGSom-@stanza.co
SUMMARY:Cubs @ River Cats
DESCRIPTION:Cubs @ River Cats\n\nFollow on MiLB First Pitch: https://stza.co/+wjAP-3g\n\nShop: https://stza.co/+wjAP-2e\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144535Z
LAST-MODIFIED:20180213T144535Z
TRANSP:OPAQUE
END:VEVENT
* Cubs @ River Cats
<2018-07-28 Sat 21:05>--<2018-07-29 Sun 00:05>
:PROPERTIES:
:ID:       5Jx7Yff9fGOVxN_lXds451yI@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Cubs @ River Cats Cubs @ River Cats

Follow on MiLB First Pitch  https //stza.co/+wjAQ-2m

Shop  https //stza.co/+wjAQ-2k

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Cubs @ River Cats
END:VALARM
DTSTART:20180729T020500Z
DTEND:20180729T050500Z
UID:5Jx7Yff9fGOVxN_lXds451yI@stanza.co
SUMMARY:Cubs @ River Cats
DESCRIPTION:Cubs @ River Cats\n\nFollow on MiLB First Pitch: https://stza.co/+wjAQ-2m\n\nShop: https://stza.co/+wjAQ-2k\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144535Z
LAST-MODIFIED:20180213T144535Z
TRANSP:OPAQUE
END:VEVENT
* Cubs @ River Cats
<2018-07-29 Sun 15:05-18:05>
:PROPERTIES:
:ID:       -ueiEwVeIeihYlN5PHJFxn-C@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Cubs @ River Cats Cubs @ River Cats

Follow on MiLB First Pitch  https //stza.co/+wjAR-1Q

Shop  https //stza.co/+wjAR-23

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Cubs @ River Cats
END:VALARM
DTSTART:20180729T200500Z
DTEND:20180729T230500Z
UID:-ueiEwVeIeihYlN5PHJFxn-C@stanza.co
SUMMARY:Cubs @ River Cats
DESCRIPTION:Cubs @ River Cats\n\nFollow on MiLB First Pitch: https://stza.co/+wjAR-1Q\n\nShop: https://stza.co/+wjAR-23\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144535Z
LAST-MODIFIED:20180213T144535Z
TRANSP:OPAQUE
END:VEVENT
* Cubs @ River Cats
<2018-07-30 Mon 14:05-17:05>
:PROPERTIES:
:ID:       jUVil2pShsei6jCntomrDXBf@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Cubs @ River Cats Cubs @ River Cats

Follow on MiLB First Pitch  https //stza.co/+wjAS-d

Shop  https //stza.co/+wjAS-2I

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Cubs @ River Cats
END:VALARM
DTSTART:20180730T190500Z
DTEND:20180730T220500Z
UID:jUVil2pShsei6jCntomrDXBf@stanza.co
SUMMARY:Cubs @ River Cats
DESCRIPTION:Cubs @ River Cats\n\nFollow on MiLB First Pitch: https://stza.co/+wjAS-d\n\nShop: https://stza.co/+wjAS-2I\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144535Z
LAST-MODIFIED:20180213T144535Z
TRANSP:OPAQUE
END:VEVENT
* Cubs vs. Bees
<2018-08-01 Wed 19:08-22:08>
:PROPERTIES:
:ID:       GT1AR8nYPHeoMso54ngUdu5r@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Cubs vs. Bees Cubs vs. Bees

Follow on MiLB First Pitch  https //stza.co/+vKE9-2X

Shop  https //stza.co/+vKE9-B

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Cubs vs. Bees
END:VALARM
DTSTART:20180802T000800Z
DTEND:20180802T030800Z
UID:GT1AR8nYPHeoMso54ngUdu5r@stanza.co
SUMMARY:Cubs vs. Bees
DESCRIPTION:Cubs vs. Bees\n\nFollow on MiLB First Pitch: https://stza.co/+vKE9-2X\n\nShop: https://stza.co/+vKE9-B\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144535Z
LAST-MODIFIED:20180213T144535Z
TRANSP:OPAQUE
END:VEVENT
* Cubs vs. Bees
<2018-08-02 Thu 19:08-22:08>
:PROPERTIES:
:ID:       Nyr6yJL3hXcy5a_4zS1y5-G8@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Cubs vs. Bees Cubs vs. Bees

Follow on MiLB First Pitch  https //stza.co/+vKEc-2

Shop  https //stza.co/+vKEc-O

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Cubs vs. Bees
END:VALARM
DTSTART:20180803T000800Z
DTEND:20180803T030800Z
UID:Nyr6yJL3hXcy5a_4zS1y5-G8@stanza.co
SUMMARY:Cubs vs. Bees
DESCRIPTION:Cubs vs. Bees\n\nFollow on MiLB First Pitch: https://stza.co/+vKEc-2\n\nShop: https://stza.co/+vKEc-O\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144535Z
LAST-MODIFIED:20180213T144535Z
TRANSP:OPAQUE
END:VEVENT
* Cubs vs. Bees
<2018-08-03 Fri 19:08-22:08>
:PROPERTIES:
:ID:       h9e4OiYMRrAI3w8viUFYFCip@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Cubs vs. Bees Cubs vs. Bees

Follow on MiLB First Pitch  https //stza.co/+vKEe-2e

Shop  https //stza.co/+vKEe-2d

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Cubs vs. Bees
END:VALARM
DTSTART:20180804T000800Z
DTEND:20180804T030800Z
UID:h9e4OiYMRrAI3w8viUFYFCip@stanza.co
SUMMARY:Cubs vs. Bees
DESCRIPTION:Cubs vs. Bees\n\nFollow on MiLB First Pitch: https://stza.co/+vKEe-2e\n\nShop: https://stza.co/+vKEe-2d\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144535Z
LAST-MODIFIED:20180213T144535Z
TRANSP:OPAQUE
END:VEVENT
* Cubs vs. 51s
<2018-08-04 Sat 19:08-22:08>
:PROPERTIES:
:ID:       tYX2rUiSekZ24Sdzjyof3UGQ@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Cubs vs. 51s Cubs vs. 51s

Follow on MiLB First Pitch  https //stza.co/+vKEg-K

Shop  https //stza.co/+vKEg-3H

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Cubs vs. 51s
END:VALARM
DTSTART:20180805T000800Z
DTEND:20180805T030800Z
UID:tYX2rUiSekZ24Sdzjyof3UGQ@stanza.co
SUMMARY:Cubs vs. 51s
DESCRIPTION:Cubs vs. 51s\n\nFollow on MiLB First Pitch: https://stza.co/+vKEg-K\n\nShop: https://stza.co/+vKEg-3H\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144535Z
LAST-MODIFIED:20180213T144535Z
TRANSP:OPAQUE
END:VEVENT
* Cubs vs. 51s
<2018-08-05 Sun 13:08-16:08>
:PROPERTIES:
:ID:       viSCaSZYxsHay0reGUYM6m_N@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Cubs vs. 51s Cubs vs. 51s

Follow on MiLB First Pitch  https //stza.co/+vKEh-1C

Shop  https //stza.co/+vKEh-1s

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Cubs vs. 51s
END:VALARM
DTSTART:20180805T180800Z
DTEND:20180805T210800Z
UID:viSCaSZYxsHay0reGUYM6m_N@stanza.co
SUMMARY:Cubs vs. 51s
DESCRIPTION:Cubs vs. 51s\n\nFollow on MiLB First Pitch: https://stza.co/+vKEh-1C\n\nShop: https://stza.co/+vKEh-1s\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144535Z
LAST-MODIFIED:20180213T144535Z
TRANSP:OPAQUE
END:VEVENT
* Cubs vs. 51s
<2018-08-06 Mon 19:08-22:08>
:PROPERTIES:
:ID:       07FzmsZjRU2u1qOsAqHIobrj@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Cubs vs. 51s Cubs vs. 51s

Follow on MiLB First Pitch  https //stza.co/+vKEj-3e

Shop  https //stza.co/+vKEj-1m

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Cubs vs. 51s
END:VALARM
DTSTART:20180807T000800Z
DTEND:20180807T030800Z
UID:07FzmsZjRU2u1qOsAqHIobrj@stanza.co
SUMMARY:Cubs vs. 51s
DESCRIPTION:Cubs vs. 51s\n\nFollow on MiLB First Pitch: https://stza.co/+vKEj-3e\n\nShop: https://stza.co/+vKEj-1m\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144535Z
LAST-MODIFIED:20180213T144535Z
TRANSP:OPAQUE
END:VEVENT
* Cubs vs. 51s
<2018-08-07 Tue 12:08-15:08>
:PROPERTIES:
:ID:       968KrnTuYvspq1Ydcq9ULJTE@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Cubs vs. 51s Cubs vs. 51s

Follow on MiLB First Pitch  https //stza.co/+vKEl-3l

Shop  https //stza.co/+vKEl-1U

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Cubs vs. 51s
END:VALARM
DTSTART:20180807T170800Z
DTEND:20180807T200800Z
UID:968KrnTuYvspq1Ydcq9ULJTE@stanza.co
SUMMARY:Cubs vs. 51s
DESCRIPTION:Cubs vs. 51s\n\nFollow on MiLB First Pitch: https://stza.co/+vKEl-3l\n\nShop: https://stza.co/+vKEl-1U\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144535Z
LAST-MODIFIED:20180213T144535Z
TRANSP:OPAQUE
END:VEVENT
* Cubs @ Baby Cakes
<2018-08-09 Thu 19:00-22:00>
:PROPERTIES:
:ID:       xeLsNNkEZV0sPCMs8IsXiJGD@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Cubs @ Baby Cakes Cubs @ Baby Cakes

Follow on MiLB First Pitch  https //stza.co/+whEj-1r

Shop  https //stza.co/+whEj-2_

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Cubs @ Baby Cakes
END:VALARM
DTSTART:20180810T000000Z
DTEND:20180810T030000Z
UID:xeLsNNkEZV0sPCMs8IsXiJGD@stanza.co
SUMMARY:Cubs @ Baby Cakes
DESCRIPTION:Cubs @ Baby Cakes\n\nFollow on MiLB First Pitch: https://stza.co/+whEj-1r\n\nShop: https://stza.co/+whEj-2_\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144535Z
LAST-MODIFIED:20180213T144535Z
TRANSP:OPAQUE
END:VEVENT
* Cubs @ Baby Cakes
<2018-08-10 Fri 19:00-22:00>
:PROPERTIES:
:ID:       SVfqxD7V9vm90TqKQrMED4XQ@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Cubs @ Baby Cakes Cubs @ Baby Cakes

Follow on MiLB First Pitch  https //stza.co/+whEl-2D

Shop  https //stza.co/+whEl-1A

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Cubs @ Baby Cakes
END:VALARM
DTSTART:20180811T000000Z
DTEND:20180811T030000Z
UID:SVfqxD7V9vm90TqKQrMED4XQ@stanza.co
SUMMARY:Cubs @ Baby Cakes
DESCRIPTION:Cubs @ Baby Cakes\n\nFollow on MiLB First Pitch: https://stza.co/+whEl-2D\n\nShop: https://stza.co/+whEl-1A\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144535Z
LAST-MODIFIED:20180213T144535Z
TRANSP:OPAQUE
END:VEVENT
* Cubs @ Baby Cakes
<2018-08-11 Sat 18:00-21:00>
:PROPERTIES:
:ID:       1MYf1a0as8Tf5VCreTop_tuA@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Cubs @ Baby Cakes Cubs @ Baby Cakes

Follow on MiLB First Pitch  https //stza.co/+whEm-F

Shop  https //stza.co/+whEm-1Q

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Cubs @ Baby Cakes
END:VALARM
DTSTART:20180811T230000Z
DTEND:20180812T020000Z
UID:1MYf1a0as8Tf5VCreTop_tuA@stanza.co
SUMMARY:Cubs @ Baby Cakes
DESCRIPTION:Cubs @ Baby Cakes\n\nFollow on MiLB First Pitch: https://stza.co/+whEm-F\n\nShop: https://stza.co/+whEm-1Q\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144535Z
LAST-MODIFIED:20180213T144535Z
TRANSP:OPAQUE
END:VEVENT
* Cubs @ Baby Cakes
<2018-08-12 Sun 13:00-16:00>
:PROPERTIES:
:ID:       WHL1BdgL6ZwhImUBqHnaRDNz@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Cubs @ Baby Cakes Cubs @ Baby Cakes

Follow on MiLB First Pitch  https //stza.co/+whEn-2o

Shop  https //stza.co/+whEn-10

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Cubs @ Baby Cakes
END:VALARM
DTSTART:20180812T180000Z
DTEND:20180812T210000Z
UID:WHL1BdgL6ZwhImUBqHnaRDNz@stanza.co
SUMMARY:Cubs @ Baby Cakes
DESCRIPTION:Cubs @ Baby Cakes\n\nFollow on MiLB First Pitch: https://stza.co/+whEn-2o\n\nShop: https://stza.co/+whEn-10\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144535Z
LAST-MODIFIED:20180213T144535Z
TRANSP:OPAQUE
END:VEVENT
* Cubs vs. Sky Sox
<2018-08-14 Tue 19:08-22:08>
:PROPERTIES:
:ID:       sJoqeuBXwBw002ZtORioKsuI@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Cubs vs. Sky Sox Cubs vs. Sky Sox

Follow on MiLB First Pitch  https //stza.co/+vKEo-3A

Shop  https //stza.co/+vKEo-2D

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Cubs vs. Sky Sox
END:VALARM
DTSTART:20180815T000800Z
DTEND:20180815T030800Z
UID:sJoqeuBXwBw002ZtORioKsuI@stanza.co
SUMMARY:Cubs vs. Sky Sox
DESCRIPTION:Cubs vs. Sky Sox\n\nFollow on MiLB First Pitch: https://stza.co/+vKEo-3A\n\nShop: https://stza.co/+vKEo-2D\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144535Z
LAST-MODIFIED:20180213T144535Z
TRANSP:OPAQUE
END:VEVENT
* Cubs vs. Sky Sox
<2018-08-15 Wed 19:08-22:08>
:PROPERTIES:
:ID:       3QXX2vi2eSZ5ZAHhZci_ef4Q@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Cubs vs. Sky Sox Cubs vs. Sky Sox

Follow on MiLB First Pitch  https //stza.co/+vKEq-2F

Shop  https //stza.co/+vKEq-3Q

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Cubs vs. Sky Sox
END:VALARM
DTSTART:20180816T000800Z
DTEND:20180816T030800Z
UID:3QXX2vi2eSZ5ZAHhZci_ef4Q@stanza.co
SUMMARY:Cubs vs. Sky Sox
DESCRIPTION:Cubs vs. Sky Sox\n\nFollow on MiLB First Pitch: https://stza.co/+vKEq-2F\n\nShop: https://stza.co/+vKEq-3Q\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144535Z
LAST-MODIFIED:20180213T144535Z
TRANSP:OPAQUE
END:VEVENT
* Cubs vs. Sky Sox
<2018-08-16 Thu 12:08-15:08>
:PROPERTIES:
:ID:       Ne-QQKn1IbQtUEnzUdtWvFrC@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Cubs vs. Sky Sox Cubs vs. Sky Sox

Follow on MiLB First Pitch  https //stza.co/+vKEs-23

Shop  https //stza.co/+vKEs-1T

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Cubs vs. Sky Sox
END:VALARM
DTSTART:20180816T170800Z
DTEND:20180816T200800Z
UID:Ne-QQKn1IbQtUEnzUdtWvFrC@stanza.co
SUMMARY:Cubs vs. Sky Sox
DESCRIPTION:Cubs vs. Sky Sox\n\nFollow on MiLB First Pitch: https://stza.co/+vKEs-23\n\nShop: https://stza.co/+vKEs-1T\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144535Z
LAST-MODIFIED:20180213T144535Z
TRANSP:OPAQUE
END:VEVENT
* Cubs @ Dodgers
<2018-08-17 Fri 19:05-22:05>
:PROPERTIES:
:ID:       E6S-R2w3v8QqbL3BbIrD9xGe@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Cubs @ Dodgers Cubs @ Dodgers

Follow on MiLB First Pitch  https //stza.co/+v$Mm-3W

Shop  https //stza.co/+v$Mm-2i

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Cubs @ Dodgers
END:VALARM
DTSTART:20180818T000500Z
DTEND:20180818T030500Z
UID:E6S-R2w3v8QqbL3BbIrD9xGe@stanza.co
SUMMARY:Cubs @ Dodgers
DESCRIPTION:Cubs @ Dodgers\n\nFollow on MiLB First Pitch: https://stza.co/+v$Mm-3W\n\nShop: https://stza.co/+v$Mm-2i\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144535Z
LAST-MODIFIED:20180213T144535Z
TRANSP:OPAQUE
END:VEVENT
* Cubs @ Dodgers
<2018-08-18 Sat 19:05-22:05>
:PROPERTIES:
:ID:       ydlflIyRIkg67e3D8woRG3We@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Cubs @ Dodgers Cubs @ Dodgers

Follow on MiLB First Pitch  https //stza.co/+v$Mn-1K

Shop  https //stza.co/+v$Mn-w

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Cubs @ Dodgers
END:VALARM
DTSTART:20180819T000500Z
DTEND:20180819T030500Z
UID:ydlflIyRIkg67e3D8woRG3We@stanza.co
SUMMARY:Cubs @ Dodgers
DESCRIPTION:Cubs @ Dodgers\n\nFollow on MiLB First Pitch: https://stza.co/+v$Mn-1K\n\nShop: https://stza.co/+v$Mn-w\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144535Z
LAST-MODIFIED:20180213T144535Z
TRANSP:OPAQUE
END:VEVENT
* Cubs @ Dodgers
<2018-08-19 Sun 18:05-21:05>
:PROPERTIES:
:ID:       ZkQah2WaQOQvaJk3tHYF-tfR@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Cubs @ Dodgers Cubs @ Dodgers

Follow on MiLB First Pitch  https //stza.co/+v$Mo-2H

Shop  https //stza.co/+v$Mo-1v

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Cubs @ Dodgers
END:VALARM
DTSTART:20180819T230500Z
DTEND:20180820T020500Z
UID:ZkQah2WaQOQvaJk3tHYF-tfR@stanza.co
SUMMARY:Cubs @ Dodgers
DESCRIPTION:Cubs @ Dodgers\n\nFollow on MiLB First Pitch: https://stza.co/+v$Mo-2H\n\nShop: https://stza.co/+v$Mo-1v\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144535Z
LAST-MODIFIED:20180213T144535Z
TRANSP:OPAQUE
END:VEVENT
* Cubs @ Sky Sox
<2018-08-21 Tue 19:40-22:40>
:PROPERTIES:
:ID:       a6hLP2_J5_kOSrLl9Jp1IBqq@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Cubs @ Sky Sox Cubs @ Sky Sox

Follow on MiLB First Pitch  https //stza.co/+wmCS-2I

Shop  https //stza.co/+wmCS-X

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Cubs @ Sky Sox
END:VALARM
DTSTART:20180822T004000Z
DTEND:20180822T034000Z
UID:a6hLP2_J5_kOSrLl9Jp1IBqq@stanza.co
SUMMARY:Cubs @ Sky Sox
DESCRIPTION:Cubs @ Sky Sox\n\nFollow on MiLB First Pitch: https://stza.co/+wmCS-2I\n\nShop: https://stza.co/+wmCS-X\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144535Z
LAST-MODIFIED:20180213T144535Z
TRANSP:OPAQUE
END:VEVENT
* Cubs @ Sky Sox
<2018-08-22 Wed 19:40-22:40>
:PROPERTIES:
:ID:       TkF98EO-p8GzCPoepwPLvu1e@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Cubs @ Sky Sox Cubs @ Sky Sox

Follow on MiLB First Pitch  https //stza.co/+wmCT-1w

Shop  https //stza.co/+wmCT-2u

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Cubs @ Sky Sox
END:VALARM
DTSTART:20180823T004000Z
DTEND:20180823T034000Z
UID:TkF98EO-p8GzCPoepwPLvu1e@stanza.co
SUMMARY:Cubs @ Sky Sox
DESCRIPTION:Cubs @ Sky Sox\n\nFollow on MiLB First Pitch: https://stza.co/+wmCT-1w\n\nShop: https://stza.co/+wmCT-2u\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144535Z
LAST-MODIFIED:20180213T144535Z
TRANSP:OPAQUE
END:VEVENT
* Cubs @ Sky Sox
<2018-08-23 Thu 19:40-22:40>
:PROPERTIES:
:ID:       dU6HYgR8TSxP_ZcAaFX4HzNy@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Cubs @ Sky Sox Cubs @ Sky Sox

Follow on MiLB First Pitch  https //stza.co/+wmCU-B

Shop  https //stza.co/+wmCU-2H

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Cubs @ Sky Sox
END:VALARM
DTSTART:20180824T004000Z
DTEND:20180824T034000Z
UID:dU6HYgR8TSxP_ZcAaFX4HzNy@stanza.co
SUMMARY:Cubs @ Sky Sox
DESCRIPTION:Cubs @ Sky Sox\n\nFollow on MiLB First Pitch: https://stza.co/+wmCU-B\n\nShop: https://stza.co/+wmCU-2H\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144535Z
LAST-MODIFIED:20180213T144535Z
TRANSP:OPAQUE
END:VEVENT
* Cubs @ Storm Chasers
<2018-08-24 Fri 19:05-22:05>
:PROPERTIES:
:ID:       fzqjrm7XmwcLUmtmvS8jEYqR@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Cubs @ Storm Chasers Cubs @ Storm Chasers

Follow on MiLB First Pitch  https //stza.co/+whEs-1G

Shop  https //stza.co/+whEs-1b

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Cubs @ Storm Chasers
END:VALARM
DTSTART:20180825T000500Z
DTEND:20180825T030500Z
UID:fzqjrm7XmwcLUmtmvS8jEYqR@stanza.co
SUMMARY:Cubs @ Storm Chasers
DESCRIPTION:Cubs @ Storm Chasers\n\nFollow on MiLB First Pitch: https://stza.co/+whEs-1G\n\nShop: https://stza.co/+whEs-1b\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144535Z
LAST-MODIFIED:20180213T144535Z
TRANSP:OPAQUE
END:VEVENT
* Cubs @ Storm Chasers
<2018-08-25 Sat 19:05-22:05>
:PROPERTIES:
:ID:       bGhrS-BFqaBQ8hUIRlnFAx1P@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Cubs @ Storm Chasers Cubs @ Storm Chasers

Follow on MiLB First Pitch  https //stza.co/+whEt-3F

Shop  https //stza.co/+whEt-r

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Cubs @ Storm Chasers
END:VALARM
DTSTART:20180826T000500Z
DTEND:20180826T030500Z
UID:bGhrS-BFqaBQ8hUIRlnFAx1P@stanza.co
SUMMARY:Cubs @ Storm Chasers
DESCRIPTION:Cubs @ Storm Chasers\n\nFollow on MiLB First Pitch: https://stza.co/+whEt-3F\n\nShop: https://stza.co/+whEt-r\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144535Z
LAST-MODIFIED:20180213T144535Z
TRANSP:OPAQUE
END:VEVENT
* Cubs @ Storm Chasers
<2018-08-26 Sun 14:05-17:05>
:PROPERTIES:
:ID:       KI0DAIvGH0c2rqyLvfGHGeDx@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Cubs @ Storm Chasers Cubs @ Storm Chasers

Follow on MiLB First Pitch  https //stza.co/+whEu-b

Shop  https //stza.co/+whEu-2M

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Cubs @ Storm Chasers
END:VALARM
DTSTART:20180826T190500Z
DTEND:20180826T220500Z
UID:KI0DAIvGH0c2rqyLvfGHGeDx@stanza.co
SUMMARY:Cubs @ Storm Chasers
DESCRIPTION:Cubs @ Storm Chasers\n\nFollow on MiLB First Pitch: https://stza.co/+whEu-b\n\nShop: https://stza.co/+whEu-2M\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144535Z
LAST-MODIFIED:20180213T144535Z
TRANSP:OPAQUE
END:VEVENT
* Cubs @ Storm Chasers
<2018-08-27 Mon 19:05-22:05>
:PROPERTIES:
:ID:       r4bFf2Zg4mwsg5b3G_5Te__9@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Cubs @ Storm Chasers Cubs @ Storm Chasers

Follow on MiLB First Pitch  https //stza.co/+whEv-29

Shop  https //stza.co/+whEv-3C

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Cubs @ Storm Chasers
END:VALARM
DTSTART:20180828T000500Z
DTEND:20180828T030500Z
UID:r4bFf2Zg4mwsg5b3G_5Te__9@stanza.co
SUMMARY:Cubs @ Storm Chasers
DESCRIPTION:Cubs @ Storm Chasers\n\nFollow on MiLB First Pitch: https://stza.co/+whEv-29\n\nShop: https://stza.co/+whEv-3C\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144535Z
LAST-MODIFIED:20180213T144535Z
TRANSP:OPAQUE
END:VEVENT
* Cubs vs. Dodgers
<2018-08-28 Tue 19:08-22:08>
:PROPERTIES:
:ID:       eNCH8FtlzNkfTwLF_7Pjv_p2@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Cubs vs. Dodgers Cubs vs. Dodgers

Follow on MiLB First Pitch  https //stza.co/+vKEu-22

Shop  https //stza.co/+vKEu-g

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Cubs vs. Dodgers
END:VALARM
DTSTART:20180829T000800Z
DTEND:20180829T030800Z
UID:eNCH8FtlzNkfTwLF_7Pjv_p2@stanza.co
SUMMARY:Cubs vs. Dodgers
DESCRIPTION:Cubs vs. Dodgers\n\nFollow on MiLB First Pitch: https://stza.co/+vKEu-22\n\nShop: https://stza.co/+vKEu-g\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144535Z
LAST-MODIFIED:20180213T144535Z
TRANSP:OPAQUE
END:VEVENT
* Cubs vs. Dodgers
<2018-08-29 Wed 19:08-22:08>
:PROPERTIES:
:ID:       NYkiTgmg7QNCOisj10J1E4y6@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Cubs vs. Dodgers Cubs vs. Dodgers

Follow on MiLB First Pitch  https //stza.co/+vKEv-2q

Shop  https //stza.co/+vKEv-3r

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Cubs vs. Dodgers
END:VALARM
DTSTART:20180830T000800Z
DTEND:20180830T030800Z
UID:NYkiTgmg7QNCOisj10J1E4y6@stanza.co
SUMMARY:Cubs vs. Dodgers
DESCRIPTION:Cubs vs. Dodgers\n\nFollow on MiLB First Pitch: https://stza.co/+vKEv-2q\n\nShop: https://stza.co/+vKEv-3r\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144535Z
LAST-MODIFIED:20180213T144535Z
TRANSP:OPAQUE
END:VEVENT
* Cubs vs. Dodgers
<2018-08-30 Thu 12:08-15:08>
:PROPERTIES:
:ID:       IjBUfc44krG8GNEh4asAj508@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Cubs vs. Dodgers Cubs vs. Dodgers

Follow on MiLB First Pitch  https //stza.co/+vKEx-E

Shop  https //stza.co/+vKEx-1e

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Cubs vs. Dodgers
END:VALARM
DTSTART:20180830T170800Z
DTEND:20180830T200800Z
UID:IjBUfc44krG8GNEh4asAj508@stanza.co
SUMMARY:Cubs vs. Dodgers
DESCRIPTION:Cubs vs. Dodgers\n\nFollow on MiLB First Pitch: https://stza.co/+vKEx-E\n\nShop: https://stza.co/+vKEx-1e\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144535Z
LAST-MODIFIED:20180213T144535Z
TRANSP:OPAQUE
END:VEVENT
* Cubs vs. Express
<2018-08-31 Fri 19:08-22:08>
:PROPERTIES:
:ID:       TK988D0rJ6BQSJsE-VDxXE5O@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Cubs vs. Express Cubs vs. Express

Follow on MiLB First Pitch  https //stza.co/+vKEA-36

Shop  https //stza.co/+vKEA-1P

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Cubs vs. Express
END:VALARM
DTSTART:20180901T000800Z
DTEND:20180901T030800Z
UID:TK988D0rJ6BQSJsE-VDxXE5O@stanza.co
SUMMARY:Cubs vs. Express
DESCRIPTION:Cubs vs. Express\n\nFollow on MiLB First Pitch: https://stza.co/+vKEA-36\n\nShop: https://stza.co/+vKEA-1P\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144535Z
LAST-MODIFIED:20180213T144535Z
TRANSP:OPAQUE
END:VEVENT
* Cubs vs. Express
<2018-09-01 Sat 19:08-22:08>
:PROPERTIES:
:ID:       PFZv7L5MdtvBIXpK4No1NAeC@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Cubs vs. Express Cubs vs. Express

Follow on MiLB First Pitch  https //stza.co/+vKEB-3r

Shop  https //stza.co/+vKEB-U

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Cubs vs. Express
END:VALARM
DTSTART:20180902T000800Z
DTEND:20180902T030800Z
UID:PFZv7L5MdtvBIXpK4No1NAeC@stanza.co
SUMMARY:Cubs vs. Express
DESCRIPTION:Cubs vs. Express\n\nFollow on MiLB First Pitch: https://stza.co/+vKEB-3r\n\nShop: https://stza.co/+vKEB-U\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144535Z
LAST-MODIFIED:20180213T144535Z
TRANSP:OPAQUE
END:VEVENT
* Cubs vs. Express
<2018-09-02 Sun 13:08-16:08>
:PROPERTIES:
:ID:       G_GhWCPOTVaB9mTr_iSbKhJ5@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Cubs vs. Express Cubs vs. Express

Follow on MiLB First Pitch  https //stza.co/+vKEE-2B

Shop  https //stza.co/+vKEE-y

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Cubs vs. Express
END:VALARM
DTSTART:20180902T180800Z
DTEND:20180902T210800Z
UID:G_GhWCPOTVaB9mTr_iSbKhJ5@stanza.co
SUMMARY:Cubs vs. Express
DESCRIPTION:Cubs vs. Express\n\nFollow on MiLB First Pitch: https://stza.co/+vKEE-2B\n\nShop: https://stza.co/+vKEE-y\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144535Z
LAST-MODIFIED:20180213T144535Z
TRANSP:OPAQUE
END:VEVENT
* Cubs vs. Express
<2018-09-03 Mon 12:08-15:08>
:PROPERTIES:
:ID:       Vw0T_PWz_xNpUH3tXf9xoMek@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Cubs vs. Express Cubs vs. Express

Follow on MiLB First Pitch  https //stza.co/+whE3-2c

Shop  https //stza.co/+whE3-O

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Cubs vs. Express
END:VALARM
DTSTART:20180903T170800Z
DTEND:20180903T200800Z
UID:Vw0T_PWz_xNpUH3tXf9xoMek@stanza.co
SUMMARY:Cubs vs. Express
DESCRIPTION:Cubs vs. Express\n\nFollow on MiLB First Pitch: https://stza.co/+whE3-2c\n\nShop: https://stza.co/+whE3-O\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144535Z
LAST-MODIFIED:20180213T144535Z
TRANSP:OPAQUE
END:VEVENT
