#+TITLE:       Main Google calendar entries
#+AUTHOR:      Eric S Fraga
#+EMAIL:       e.fraga@ucl.ac.uk
#+DESCRIPTION: converted using the ical2org awk script
#+CATEGORY:    google
#+STARTUP:     hidestars
#+STARTUP:     overview

* COMMENT original iCal preamble

* Timber Rattlers @ Snappers
<2018-04-05 Thu 18:30-21:30>
:PROPERTIES:
:ID:       DjJRi0Tf35l18gS5oMu3Dkpg@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Timber Rattlers @ Snappers Timber Rattlers @ Snappers

Follow on MiLB First Pitch  https //stza.co/+wSOB-2y

Shop  https //stza.co/+wSOB-1T

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Timber Rattlers @ Snappers
END:VALARM
DTSTART:20180405T233000Z
DTEND:20180406T023000Z
UID:DjJRi0Tf35l18gS5oMu3Dkpg@stanza.co
SUMMARY:Timber Rattlers @ Snappers
DESCRIPTION:Timber Rattlers @ Snappers\n\nFollow on MiLB First Pitch: https://stza.co/+wSOB-2y\n\nShop: https://stza.co/+wSOB-1T\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144607Z
LAST-MODIFIED:20180213T144607Z
TRANSP:OPAQUE
END:VEVENT
* Timber Rattlers @ Snappers
<2018-04-06 Fri 18:30-21:30>
:PROPERTIES:
:ID:       WI_c77EybA-TQCKFXKe14KeN@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Timber Rattlers @ Snappers Timber Rattlers @ Snappers

Follow on MiLB First Pitch  https //stza.co/+wSOC-2r

Shop  https //stza.co/+wSOC-1a

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Timber Rattlers @ Snappers
END:VALARM
DTSTART:20180406T233000Z
DTEND:20180407T023000Z
UID:WI_c77EybA-TQCKFXKe14KeN@stanza.co
SUMMARY:Timber Rattlers @ Snappers
DESCRIPTION:Timber Rattlers @ Snappers\n\nFollow on MiLB First Pitch: https://stza.co/+wSOC-2r\n\nShop: https://stza.co/+wSOC-1a\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144607Z
LAST-MODIFIED:20180213T144607Z
TRANSP:OPAQUE
END:VEVENT
* Timber Rattlers vs. Snappers
<2018-04-07 Sat 16:05-19:05>
:PROPERTIES:
:ID:       4HwXsUUwn0q9tZzgLPFJl1Pi@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Timber Rattlers vs. Snappers Timber Rattlers vs. Snappers

Follow on MiLB First Pitch  https //stza.co/+vNqu-3z

Shop  https //stza.co/+vNqu-2w

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Timber Rattlers vs. Snappers
END:VALARM
DTSTART:20180407T210500Z
DTEND:20180408T000500Z
UID:4HwXsUUwn0q9tZzgLPFJl1Pi@stanza.co
SUMMARY:Timber Rattlers vs. Snappers
DESCRIPTION:Timber Rattlers vs. Snappers\n\nFollow on MiLB First Pitch: https://stza.co/+vNqu-3z\n\nShop: https://stza.co/+vNqu-2w\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144607Z
LAST-MODIFIED:20180213T144607Z
TRANSP:OPAQUE
END:VEVENT
* Timber Rattlers vs. Snappers
<2018-04-08 Sun 13:05-16:05>
:PROPERTIES:
:ID:       PMe5h2szIX0L_jFRXJpeVdC5@stanza.co
:LOCATION: Brewers Sunday
:STATUS:   CONFIRMED
:END:

Timber Rattlers vs. Snappers Play catch on the field pre-game. Player autographs after the game. Brewers themed jerseys worn on field. Brewers Fan Makeover.

Follow on MiLB First Pitch  https //stza.co/+vNqw-2h

Shop  https //stza.co/+vNqw-W

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Timber Rattlers vs. Snappers
END:VALARM
DTSTART:20180408T180500Z
DTEND:20180408T210500Z
UID:PMe5h2szIX0L_jFRXJpeVdC5@stanza.co
SUMMARY:Timber Rattlers vs. Snappers
DESCRIPTION:Play catch on the field pre-game. Player autographs after the game. Brewers themed jerseys worn on field. Brewers Fan Makeover.\n\nFollow on MiLB First Pitch: https://stza.co/+vNqw-2h\n\nShop: https://stza.co/+vNqw-W\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Brewers Sunday
STATUS:CONFIRMED
CREATED:20180213T144607Z
LAST-MODIFIED:20180213T144607Z
TRANSP:OPAQUE
END:VEVENT
* Timber Rattlers @ LumberKings
<2018-04-09 Mon 18:30-21:30>
:PROPERTIES:
:ID:       2Wo5g6b3MwVHkZZh90KELJLv@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Timber Rattlers @ LumberKings Timber Rattlers @ LumberKings

Follow on MiLB First Pitch  https //stza.co/+vNpI-3g

Shop  https //stza.co/+vNpI-3Q

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Timber Rattlers @ LumberKings
END:VALARM
DTSTART:20180409T233000Z
DTEND:20180410T023000Z
UID:2Wo5g6b3MwVHkZZh90KELJLv@stanza.co
SUMMARY:Timber Rattlers @ LumberKings
DESCRIPTION:Timber Rattlers @ LumberKings\n\nFollow on MiLB First Pitch: https://stza.co/+vNpI-3g\n\nShop: https://stza.co/+vNpI-3Q\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144607Z
LAST-MODIFIED:20180213T144607Z
TRANSP:OPAQUE
END:VEVENT
* Timber Rattlers @ LumberKings
<2018-04-10 Tue>--<2018-04-09 Mon>
:PROPERTIES:
:ID:       g4Wqd4anIJHjm5MGEZpULD_W@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Timber Rattlers @ LumberKings Timber Rattlers @ LumberKings

Follow on MiLB First Pitch  https //stza.co/+vNpJ-3c

Shop  https //stza.co/+vNpJ-19

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Timber Rattlers @ LumberKings
END:VALARM
DTSTART;VALUE=DATE:20180410
DTEND;VALUE=DATE:20180410
UID:g4Wqd4anIJHjm5MGEZpULD_W@stanza.co
SUMMARY:Timber Rattlers @ LumberKings
DESCRIPTION:Timber Rattlers @ LumberKings\n\nFollow on MiLB First Pitch: https://stza.co/+vNpJ-3c\n\nShop: https://stza.co/+vNpJ-19\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144607Z
LAST-MODIFIED:20180213T144607Z
TRANSP:OPAQUE
END:VEVENT
* Timber Rattlers @ LumberKings
<2018-04-11 Wed>--<2018-04-10 Tue>
:PROPERTIES:
:ID:       x8FSoP2H1YQTDG0kOg7mK1yq@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Timber Rattlers @ LumberKings Timber Rattlers @ LumberKings

Follow on MiLB First Pitch  https //stza.co/+vNpK-1

Shop  https //stza.co/+vNpK-2A

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Timber Rattlers @ LumberKings
END:VALARM
DTSTART;VALUE=DATE:20180411
DTEND;VALUE=DATE:20180411
UID:x8FSoP2H1YQTDG0kOg7mK1yq@stanza.co
SUMMARY:Timber Rattlers @ LumberKings
DESCRIPTION:Timber Rattlers @ LumberKings\n\nFollow on MiLB First Pitch: https://stza.co/+vNpK-1\n\nShop: https://stza.co/+vNpK-2A\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144607Z
LAST-MODIFIED:20180213T144607Z
TRANSP:OPAQUE
END:VEVENT
* Timber Rattlers @ LumberKings
<2018-04-12 Thu 18:30-21:30>
:PROPERTIES:
:ID:       lAUgffwC5YudjSJvyC6OXbBN@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Timber Rattlers @ LumberKings Timber Rattlers @ LumberKings

Follow on MiLB First Pitch  https //stza.co/+xVYK-3o

Shop  https //stza.co/+xVYK-2o

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Timber Rattlers @ LumberKings
END:VALARM
DTSTART:20180412T233000Z
DTEND:20180413T023000Z
UID:lAUgffwC5YudjSJvyC6OXbBN@stanza.co
SUMMARY:Timber Rattlers @ LumberKings
DESCRIPTION:Timber Rattlers @ LumberKings\n\nFollow on MiLB First Pitch: https://stza.co/+xVYK-3o\n\nShop: https://stza.co/+xVYK-2o\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144607Z
LAST-MODIFIED:20180213T144607Z
TRANSP:OPAQUE
END:VEVENT
* Timber Rattlers @ Chiefs
<2018-04-13 Fri 18:30-21:30>
:PROPERTIES:
:ID:       QN5W_cxvv5VnTIHzQUc_ZeQL@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Timber Rattlers @ Chiefs Timber Rattlers @ Chiefs

Follow on MiLB First Pitch  https //stza.co/+xBD4-3x

Shop  https //stza.co/+xBD4-24

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Timber Rattlers @ Chiefs
END:VALARM
DTSTART:20180413T233000Z
DTEND:20180414T023000Z
UID:QN5W_cxvv5VnTIHzQUc_ZeQL@stanza.co
SUMMARY:Timber Rattlers @ Chiefs
DESCRIPTION:Timber Rattlers @ Chiefs\n\nFollow on MiLB First Pitch: https://stza.co/+xBD4-3x\n\nShop: https://stza.co/+xBD4-24\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144607Z
LAST-MODIFIED:20180213T144607Z
TRANSP:OPAQUE
END:VEVENT
* Timber Rattlers @ Chiefs
<2018-04-14 Sat 18:30-21:30>
:PROPERTIES:
:ID:       qi8AFo3HeTXmRAWWdjedfWjF@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Timber Rattlers @ Chiefs Timber Rattlers @ Chiefs

Follow on MiLB First Pitch  https //stza.co/+xBDb-3h

Shop  https //stza.co/+xBDb-2Z

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Timber Rattlers @ Chiefs
END:VALARM
DTSTART:20180414T233000Z
DTEND:20180415T023000Z
UID:qi8AFo3HeTXmRAWWdjedfWjF@stanza.co
SUMMARY:Timber Rattlers @ Chiefs
DESCRIPTION:Timber Rattlers @ Chiefs\n\nFollow on MiLB First Pitch: https://stza.co/+xBDb-3h\n\nShop: https://stza.co/+xBDb-2Z\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144607Z
LAST-MODIFIED:20180213T144607Z
TRANSP:OPAQUE
END:VEVENT
* Timber Rattlers @ Chiefs
<2018-04-15 Sun 14:00-17:00>
:PROPERTIES:
:ID:       bmB_UR-Nl1XA-TYYYU5OEOB0@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Timber Rattlers @ Chiefs Timber Rattlers @ Chiefs

Follow on MiLB First Pitch  https //stza.co/+xBDi-3u

Shop  https //stza.co/+xBDi-z

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Timber Rattlers @ Chiefs
END:VALARM
DTSTART:20180415T190000Z
DTEND:20180415T220000Z
UID:bmB_UR-Nl1XA-TYYYU5OEOB0@stanza.co
SUMMARY:Timber Rattlers @ Chiefs
DESCRIPTION:Timber Rattlers @ Chiefs\n\nFollow on MiLB First Pitch: https://stza.co/+xBDi-3u\n\nShop: https://stza.co/+xBDi-z\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144607Z
LAST-MODIFIED:20180213T144607Z
TRANSP:OPAQUE
END:VEVENT
* Timber Rattlers vs. Cougars
<2018-04-17 Tue 18:35-21:35>
:PROPERTIES:
:ID:       uDqyANBmRr0DHEBUJtMObT0K@stanza.co
:LOCATION: Baker Tilly Business Person Special
:STATUS:   CONFIRMED
:END:

Timber Rattlers vs. Cougars Business Persons that present business card, Military Personnel with ID and seniors with ID 55 & older receive a box seat ticket. Beverage & brat or hot dog for just $14.50.

Follow on MiLB First Pitch  https //stza.co/+vNqx-1o

Shop  https //stza.co/+vNqx-2J

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Timber Rattlers vs. Cougars
END:VALARM
DTSTART:20180417T233500Z
DTEND:20180418T023500Z
UID:uDqyANBmRr0DHEBUJtMObT0K@stanza.co
SUMMARY:Timber Rattlers vs. Cougars
DESCRIPTION:Business Persons that present business card, Military Personnel with ID and seniors with ID 55 & older receive a box seat ticket. Beverage & brat or hot dog for just $14.50.\n\nFollow on MiLB First Pitch: https://stza.co/+vNqx-1o\n\nShop: https://stza.co/+vNqx-2J\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Baker Tilly Business Person Special
STATUS:CONFIRMED
CREATED:20180213T144607Z
LAST-MODIFIED:20180213T144607Z
TRANSP:OPAQUE
END:VEVENT
* Timber Rattlers vs. Cougars
<2018-04-18 Wed 18:35-21:35>
:PROPERTIES:
:ID:       GxzyGHQBrtKpcEi0laId-SrC@stanza.co
:LOCATION: Bang For Your Buck
:STATUS:   CONFIRMED
:END:

Timber Rattlers vs. Cougars Enjoy Cher-Make hotdogs, sodas, and domestic beer for $1. A lucky fan will go home with two charter airfare tickets courtesy of AAA Travel and Funjet Vacations.

Follow on MiLB First Pitch  https //stza.co/+vNqz-3

Shop  https //stza.co/+vNqz-1_

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Timber Rattlers vs. Cougars
END:VALARM
DTSTART:20180418T233500Z
DTEND:20180419T023500Z
UID:GxzyGHQBrtKpcEi0laId-SrC@stanza.co
SUMMARY:Timber Rattlers vs. Cougars
DESCRIPTION:Enjoy Cher-Make hotdogs, sodas, and domestic beer for $1. A lucky fan will go home with two charter airfare tickets courtesy of AAA Travel and Funjet Vacations.\n\nFollow on MiLB First Pitch: https://stza.co/+vNqz-3\n\nShop: https://stza.co/+vNqz-1_\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Bang For Your Buck
STATUS:CONFIRMED
CREATED:20180213T144607Z
LAST-MODIFIED:20180213T144607Z
TRANSP:OPAQUE
END:VEVENT
* Timber Rattlers vs. Cougars
<2018-04-19 Thu 12:05-15:05>
:PROPERTIES:
:ID:       WyyGT2fRO5HuF81Ba3lD5ofW@stanza.co
:LOCATION: Craft Brews and Brats
:STATUS:   CONFIRMED
:END:

Timber Rattlers vs. Cougars Enjoy 12 oz craft beer and Cher-Make Brats for only $2. Present any Thursday game ticket at Wissota Taphouse for a free beer.

Follow on MiLB First Pitch  https //stza.co/+vNqB-36

Shop  https //stza.co/+vNqB-1x

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Timber Rattlers vs. Cougars
END:VALARM
DTSTART:20180419T170500Z
DTEND:20180419T200500Z
UID:WyyGT2fRO5HuF81Ba3lD5ofW@stanza.co
SUMMARY:Timber Rattlers vs. Cougars
DESCRIPTION:Enjoy 12 oz craft beer and Cher-Make Brats for only $2. Present any Thursday game ticket at Wissota Taphouse for a free beer.\n\nFollow on MiLB First Pitch: https://stza.co/+vNqB-36\n\nShop: https://stza.co/+vNqB-1x\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Craft Brews and Brats
STATUS:CONFIRMED
CREATED:20180213T144607Z
LAST-MODIFIED:20180213T144607Z
TRANSP:OPAQUE
END:VEVENT
* Timber Rattlers @ Chiefs
<2018-04-20 Fri 18:30-21:30>
:PROPERTIES:
:ID:       c36CW8k9ceIaMpoEKHa-85C5@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Timber Rattlers @ Chiefs Timber Rattlers @ Chiefs

Follow on MiLB First Pitch  https //stza.co/+xBDn-1V

Shop  https //stza.co/+xBDn-3V

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Timber Rattlers @ Chiefs
END:VALARM
DTSTART:20180420T233000Z
DTEND:20180421T023000Z
UID:c36CW8k9ceIaMpoEKHa-85C5@stanza.co
SUMMARY:Timber Rattlers @ Chiefs
DESCRIPTION:Timber Rattlers @ Chiefs\n\nFollow on MiLB First Pitch: https://stza.co/+xBDn-1V\n\nShop: https://stza.co/+xBDn-3V\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144607Z
LAST-MODIFIED:20180213T144607Z
TRANSP:OPAQUE
END:VEVENT
* Timber Rattlers @ Chiefs
<2018-04-21 Sat 18:30-21:30>
:PROPERTIES:
:ID:       8I-JcjC2G8J_Z2B0obzVwRGU@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Timber Rattlers @ Chiefs Timber Rattlers @ Chiefs

Follow on MiLB First Pitch  https //stza.co/+xBDs-3E

Shop  https //stza.co/+xBDs-1u

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Timber Rattlers @ Chiefs
END:VALARM
DTSTART:20180421T233000Z
DTEND:20180422T023000Z
UID:8I-JcjC2G8J_Z2B0obzVwRGU@stanza.co
SUMMARY:Timber Rattlers @ Chiefs
DESCRIPTION:Timber Rattlers @ Chiefs\n\nFollow on MiLB First Pitch: https://stza.co/+xBDs-3E\n\nShop: https://stza.co/+xBDs-1u\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144607Z
LAST-MODIFIED:20180213T144607Z
TRANSP:OPAQUE
END:VEVENT
* Timber Rattlers @ Chiefs
<2018-04-22 Sun 17:00-20:00>
:PROPERTIES:
:ID:       E32YqeuBmIEsyXzo1dPBvj-z@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Timber Rattlers @ Chiefs Timber Rattlers @ Chiefs

Follow on MiLB First Pitch  https //stza.co/+xBDx-Q

Shop  https //stza.co/+xBDx-1

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Timber Rattlers @ Chiefs
END:VALARM
DTSTART:20180422T220000Z
DTEND:20180423T010000Z
UID:E32YqeuBmIEsyXzo1dPBvj-z@stanza.co
SUMMARY:Timber Rattlers @ Chiefs
DESCRIPTION:Timber Rattlers @ Chiefs\n\nFollow on MiLB First Pitch: https://stza.co/+xBDx-Q\n\nShop: https://stza.co/+xBDx-1\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144607Z
LAST-MODIFIED:20180213T144607Z
TRANSP:OPAQUE
END:VEVENT
* Timber Rattlers vs. LumberKings
<2018-04-23 Mon 18:35-21:35>
:PROPERTIES:
:ID:       QgfNeNUnVDtolDpEk2SfPuI7@stanza.co
:LOCATION: Qdoba Q'Monday
:STATUS:   CONFIRMED
:END:

Timber Rattlers vs. LumberKings Purchase any Qdoba entree on any Monday game at any Appleton, Neenah, or Oshkosh location and receive a free Monday game ticket.

Follow on MiLB First Pitch  https //stza.co/+vNqE-u

Shop  https //stza.co/+vNqE-1v

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Timber Rattlers vs. LumberKings
END:VALARM
DTSTART:20180423T233500Z
DTEND:20180424T023500Z
UID:QgfNeNUnVDtolDpEk2SfPuI7@stanza.co
SUMMARY:Timber Rattlers vs. LumberKings
DESCRIPTION:Purchase any Qdoba entree on any Monday game at any Appleton, Neenah, or Oshkosh location and receive a free Monday game ticket.\n\nFollow on MiLB First Pitch: https://stza.co/+vNqE-u\n\nShop: https://stza.co/+vNqE-1v\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Qdoba Q'Monday
STATUS:CONFIRMED
CREATED:20180213T144607Z
LAST-MODIFIED:20180213T144607Z
TRANSP:OPAQUE
END:VEVENT
* Timber Rattlers vs. LumberKings
<2018-04-24 Tue 18:35-21:35>
:PROPERTIES:
:ID:       fwRiNsFGM229BKS2JahAFWy_@stanza.co
:LOCATION: Baker Tilly Business Person Special
:STATUS:   CONFIRMED
:END:

Timber Rattlers vs. LumberKings Business Persons that present business card, Military Personnel with ID and seniors with ID 55 & older receive a box seat ticket. Beverage & brat or hot dog for just $14.50.

Follow on MiLB First Pitch  https //stza.co/+vNqF-1F

Shop  https //stza.co/+vNqF-1v

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Timber Rattlers vs. LumberKings
END:VALARM
DTSTART:20180424T233500Z
DTEND:20180425T023500Z
UID:fwRiNsFGM229BKS2JahAFWy_@stanza.co
SUMMARY:Timber Rattlers vs. LumberKings
DESCRIPTION:Business Persons that present business card, Military Personnel with ID and seniors with ID 55 & older receive a box seat ticket. Beverage & brat or hot dog for just $14.50.\n\nFollow on MiLB First Pitch: https://stza.co/+vNqF-1F\n\nShop: https://stza.co/+vNqF-1v\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Baker Tilly Business Person Special
STATUS:CONFIRMED
CREATED:20180213T144607Z
LAST-MODIFIED:20180213T144607Z
TRANSP:OPAQUE
END:VEVENT
* Timber Rattlers vs. LumberKings
<2018-04-25 Wed 18:35-21:35>
:PROPERTIES:
:ID:       xfMu8LBI1m_kgQdyyaytldjU@stanza.co
:LOCATION: Bang For Your Buck
:STATUS:   CONFIRMED
:END:

Timber Rattlers vs. LumberKings Enjoy Cher-Make hotdogs, sodas, and domestic beer for $1. A lucky fan will go home with two charter airfare tickets courtesy of AAA Travel and Funjet Vacations.

Follow on MiLB First Pitch  https //stza.co/+vNqH-2Y

Shop  https //stza.co/+vNqH-1j

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Timber Rattlers vs. LumberKings
END:VALARM
DTSTART:20180425T233500Z
DTEND:20180426T023500Z
UID:xfMu8LBI1m_kgQdyyaytldjU@stanza.co
SUMMARY:Timber Rattlers vs. LumberKings
DESCRIPTION:Enjoy Cher-Make hotdogs, sodas, and domestic beer for $1. A lucky fan will go home with two charter airfare tickets courtesy of AAA Travel and Funjet Vacations.\n\nFollow on MiLB First Pitch: https://stza.co/+vNqH-2Y\n\nShop: https://stza.co/+vNqH-1j\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Bang For Your Buck
STATUS:CONFIRMED
CREATED:20180213T144607Z
LAST-MODIFIED:20180213T144607Z
TRANSP:OPAQUE
END:VEVENT
* Timber Rattlers vs. LumberKings
<2018-04-26 Thu 12:05-15:05>
:PROPERTIES:
:ID:       bd3PoTKhDMYgbwziyGVPBnwc@stanza.co
:LOCATION: Craft Brews and Brats
:STATUS:   CONFIRMED
:END:

Timber Rattlers vs. LumberKings Enjoy 12 oz craft beer and Cher-Make Brats for only $2. Present any Thursday game ticket at Wissota Taphouse for a free beer.

Follow on MiLB First Pitch  https //stza.co/+vNqK-1r

Shop  https //stza.co/+vNqK-1H

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Timber Rattlers vs. LumberKings
END:VALARM
DTSTART:20180426T170500Z
DTEND:20180426T200500Z
UID:bd3PoTKhDMYgbwziyGVPBnwc@stanza.co
SUMMARY:Timber Rattlers vs. LumberKings
DESCRIPTION:Enjoy 12 oz craft beer and Cher-Make Brats for only $2. Present any Thursday game ticket at Wissota Taphouse for a free beer.\n\nFollow on MiLB First Pitch: https://stza.co/+vNqK-1r\n\nShop: https://stza.co/+vNqK-1H\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Craft Brews and Brats
STATUS:CONFIRMED
CREATED:20180213T144607Z
LAST-MODIFIED:20180213T144607Z
TRANSP:OPAQUE
END:VEVENT
* Timber Rattlers vs. Chiefs
<2018-04-27 Fri 18:35-21:35>
:PROPERTIES:
:ID:       WXINETlBLpthkc-KpcglvxMA@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Timber Rattlers vs. Chiefs Timber Rattlers vs. Chiefs

Follow on MiLB First Pitch  https //stza.co/+vNqM-1c

Shop  https //stza.co/+vNqM-1d

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Timber Rattlers vs. Chiefs
END:VALARM
DTSTART:20180427T233500Z
DTEND:20180428T023500Z
UID:WXINETlBLpthkc-KpcglvxMA@stanza.co
SUMMARY:Timber Rattlers vs. Chiefs
DESCRIPTION:Timber Rattlers vs. Chiefs\n\nFollow on MiLB First Pitch: https://stza.co/+vNqM-1c\n\nShop: https://stza.co/+vNqM-1d\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144607Z
LAST-MODIFIED:20180213T144607Z
TRANSP:OPAQUE
END:VEVENT
* Timber Rattlers vs. Chiefs
<2018-04-28 Sat 13:05-16:05>
:PROPERTIES:
:ID:       HbRUCuW2XFTzCRkaY6pPeAZc@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Timber Rattlers vs. Chiefs Timber Rattlers vs. Chiefs

Follow on MiLB First Pitch  https //stza.co/+vNqO-f

Shop  https //stza.co/+vNqO-a

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Timber Rattlers vs. Chiefs
END:VALARM
DTSTART:20180428T180500Z
DTEND:20180428T210500Z
UID:HbRUCuW2XFTzCRkaY6pPeAZc@stanza.co
SUMMARY:Timber Rattlers vs. Chiefs
DESCRIPTION:Timber Rattlers vs. Chiefs\n\nFollow on MiLB First Pitch: https://stza.co/+vNqO-f\n\nShop: https://stza.co/+vNqO-a\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144607Z
LAST-MODIFIED:20180213T144607Z
TRANSP:OPAQUE
END:VEVENT
* Timber Rattlers vs. Chiefs
<2018-04-29 Sun 13:05-16:05>
:PROPERTIES:
:ID:       92OCwMrePqkQP5B1FVVAvzjC@stanza.co
:LOCATION: Brewers Sunday
:STATUS:   CONFIRMED
:END:

Timber Rattlers vs. Chiefs Play catch on the field pre-game. Player autographs after the game. Brewers themed jerseys worn on field. Brewers Fan Makeover.

Follow on MiLB First Pitch  https //stza.co/+vNqP-14

Shop  https //stza.co/+vNqP-1l

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Timber Rattlers vs. Chiefs
END:VALARM
DTSTART:20180429T180500Z
DTEND:20180429T210500Z
UID:92OCwMrePqkQP5B1FVVAvzjC@stanza.co
SUMMARY:Timber Rattlers vs. Chiefs
DESCRIPTION:Play catch on the field pre-game. Player autographs after the game. Brewers themed jerseys worn on field. Brewers Fan Makeover.\n\nFollow on MiLB First Pitch: https://stza.co/+vNqP-14\n\nShop: https://stza.co/+vNqP-1l\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Brewers Sunday
STATUS:CONFIRMED
CREATED:20180213T144607Z
LAST-MODIFIED:20180213T144607Z
TRANSP:OPAQUE
END:VEVENT
* Timber Rattlers @ Captains
<2018-05-01 Tue 17:30-20:30>
:PROPERTIES:
:ID:       x_Sdlga02Hp8MNQpfoyNUbH0@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Timber Rattlers @ Captains Timber Rattlers @ Captains

Follow on MiLB First Pitch  https //stza.co/+xBCU-S

Shop  https //stza.co/+xBCU-1K

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Timber Rattlers @ Captains
END:VALARM
DTSTART:20180501T223000Z
DTEND:20180502T013000Z
UID:x_Sdlga02Hp8MNQpfoyNUbH0@stanza.co
SUMMARY:Timber Rattlers @ Captains
DESCRIPTION:Timber Rattlers @ Captains\n\nFollow on MiLB First Pitch: https://stza.co/+xBCU-S\n\nShop: https://stza.co/+xBCU-1K\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144607Z
LAST-MODIFIED:20180213T144607Z
TRANSP:OPAQUE
END:VEVENT
* Timber Rattlers @ Captains
<2018-05-02 Wed 10:00-13:00>
:PROPERTIES:
:ID:       ncGsrTE7T5CYj5tF70Di5Crr@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Timber Rattlers @ Captains Timber Rattlers @ Captains

Follow on MiLB First Pitch  https //stza.co/+xBCX-Y

Shop  https //stza.co/+xBCX-y

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Timber Rattlers @ Captains
END:VALARM
DTSTART:20180502T150000Z
DTEND:20180502T180000Z
UID:ncGsrTE7T5CYj5tF70Di5Crr@stanza.co
SUMMARY:Timber Rattlers @ Captains
DESCRIPTION:Timber Rattlers @ Captains\n\nFollow on MiLB First Pitch: https://stza.co/+xBCX-Y\n\nShop: https://stza.co/+xBCX-y\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144607Z
LAST-MODIFIED:20180213T144607Z
TRANSP:OPAQUE
END:VEVENT
* Timber Rattlers @ Captains
<2018-05-03 Thu 17:30-20:30>
:PROPERTIES:
:ID:       4EW2Ap78UTZ0-aJLZiH0DxUn@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Timber Rattlers @ Captains Timber Rattlers @ Captains

Follow on MiLB First Pitch  https //stza.co/+xBD0-k

Shop  https //stza.co/+xBD0-3l

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Timber Rattlers @ Captains
END:VALARM
DTSTART:20180503T223000Z
DTEND:20180504T013000Z
UID:4EW2Ap78UTZ0-aJLZiH0DxUn@stanza.co
SUMMARY:Timber Rattlers @ Captains
DESCRIPTION:Timber Rattlers @ Captains\n\nFollow on MiLB First Pitch: https://stza.co/+xBD0-k\n\nShop: https://stza.co/+xBD0-3l\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144607Z
LAST-MODIFIED:20180213T144607Z
TRANSP:OPAQUE
END:VEVENT
* Timber Rattlers @ TinCaps
<2018-05-04 Fri 18:05-21:05>
:PROPERTIES:
:ID:       3A5nDKVPPCuwMr6AtTwxPTfH@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Timber Rattlers @ TinCaps Timber Rattlers @ TinCaps

Follow on MiLB First Pitch  https //stza.co/+vNpT-v

Shop  https //stza.co/+vNpT-38

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Timber Rattlers @ TinCaps
END:VALARM
DTSTART:20180504T230500Z
DTEND:20180505T020500Z
UID:3A5nDKVPPCuwMr6AtTwxPTfH@stanza.co
SUMMARY:Timber Rattlers @ TinCaps
DESCRIPTION:Timber Rattlers @ TinCaps\n\nFollow on MiLB First Pitch: https://stza.co/+vNpT-v\n\nShop: https://stza.co/+vNpT-38\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144607Z
LAST-MODIFIED:20180213T144607Z
TRANSP:OPAQUE
END:VEVENT
* Timber Rattlers @ TinCaps
<2018-05-05 Sat 18:05-21:05>
:PROPERTIES:
:ID:       Brlnsf78MakF2-z7C4WUZxHo@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Timber Rattlers @ TinCaps Timber Rattlers @ TinCaps

Follow on MiLB First Pitch  https //stza.co/+vNpU-D

Shop  https //stza.co/+vNpU-1w

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Timber Rattlers @ TinCaps
END:VALARM
DTSTART:20180505T230500Z
DTEND:20180506T020500Z
UID:Brlnsf78MakF2-z7C4WUZxHo@stanza.co
SUMMARY:Timber Rattlers @ TinCaps
DESCRIPTION:Timber Rattlers @ TinCaps\n\nFollow on MiLB First Pitch: https://stza.co/+vNpU-D\n\nShop: https://stza.co/+vNpU-1w\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144607Z
LAST-MODIFIED:20180213T144607Z
TRANSP:OPAQUE
END:VEVENT
* Timber Rattlers @ TinCaps
<2018-05-06 Sun 12:05-15:05>
:PROPERTIES:
:ID:       GPwd_0adob4l3EWYyFVzUEIb@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Timber Rattlers @ TinCaps Timber Rattlers @ TinCaps

Follow on MiLB First Pitch  https //stza.co/+vNpV-f

Shop  https //stza.co/+vNpV-1G

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Timber Rattlers @ TinCaps
END:VALARM
DTSTART:20180506T170500Z
DTEND:20180506T200500Z
UID:GPwd_0adob4l3EWYyFVzUEIb@stanza.co
SUMMARY:Timber Rattlers @ TinCaps
DESCRIPTION:Timber Rattlers @ TinCaps\n\nFollow on MiLB First Pitch: https://stza.co/+vNpV-f\n\nShop: https://stza.co/+vNpV-1G\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144607Z
LAST-MODIFIED:20180213T144607Z
TRANSP:OPAQUE
END:VEVENT
* Timber Rattlers vs. Lugnuts
<2018-05-07 Mon 18:35-21:35>
:PROPERTIES:
:ID:       glZbD05X8DDhq-RA8RBdODj5@stanza.co
:LOCATION: Qdoba Q'Monday
:STATUS:   CONFIRMED
:END:

Timber Rattlers vs. Lugnuts Purchase any Qdoba entree on any Monday game at any Appleton, Neenah, or Oshkosh location and receive a free Monday game ticket.

Follow on MiLB First Pitch  https //stza.co/+vNqS-o

Shop  https //stza.co/+vNqS-2

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Timber Rattlers vs. Lugnuts
END:VALARM
DTSTART:20180507T233500Z
DTEND:20180508T023500Z
UID:glZbD05X8DDhq-RA8RBdODj5@stanza.co
SUMMARY:Timber Rattlers vs. Lugnuts
DESCRIPTION:Purchase any Qdoba entree on any Monday game at any Appleton, Neenah, or Oshkosh location and receive a free Monday game ticket.\n\nFollow on MiLB First Pitch: https://stza.co/+vNqS-o\n\nShop: https://stza.co/+vNqS-2\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Qdoba Q'Monday
STATUS:CONFIRMED
CREATED:20180213T144607Z
LAST-MODIFIED:20180213T144607Z
TRANSP:OPAQUE
END:VEVENT
* Timber Rattlers vs. Lugnuts
<2018-05-08 Tue 12:05-15:05>
:PROPERTIES:
:ID:       9HQtPANR8Ku-wVAzLhMcCbZH@stanza.co
:LOCATION: Baker Tilly Business Person Special
:STATUS:   CONFIRMED
:END:

Timber Rattlers vs. Lugnuts Business Persons that present business card, Military Personnel with ID and seniors with ID 55 & older receive a box seat ticket. Beverage & brat or hot dog for just $14.50.

Follow on MiLB First Pitch  https //stza.co/+vNqU-3_

Shop  https //stza.co/+vNqU-8

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Timber Rattlers vs. Lugnuts
END:VALARM
DTSTART:20180508T170500Z
DTEND:20180508T200500Z
UID:9HQtPANR8Ku-wVAzLhMcCbZH@stanza.co
SUMMARY:Timber Rattlers vs. Lugnuts
DESCRIPTION:Business Persons that present business card, Military Personnel with ID and seniors with ID 55 & older receive a box seat ticket. Beverage & brat or hot dog for just $14.50.\n\nFollow on MiLB First Pitch: https://stza.co/+vNqU-3_\n\nShop: https://stza.co/+vNqU-8\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Baker Tilly Business Person Special
STATUS:CONFIRMED
CREATED:20180213T144607Z
LAST-MODIFIED:20180213T144607Z
TRANSP:OPAQUE
END:VEVENT
* Timber Rattlers vs. Lugnuts
<2018-05-09 Wed 18:35-21:35>
:PROPERTIES:
:ID:       Ghl3ADDL2UE6iePlkJMZif95@stanza.co
:LOCATION: Bang For Your Buck
:STATUS:   CONFIRMED
:END:

Timber Rattlers vs. Lugnuts Enjoy Cher-Make hotdogs, sodas, and domestic beer for $1. A lucky fan will go home with two charter airfare tickets courtesy of AAA Travel and Funjet Vacations.

Follow on MiLB First Pitch  https //stza.co/+vNqV-2n

Shop  https //stza.co/+vNqV-2k

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Timber Rattlers vs. Lugnuts
END:VALARM
DTSTART:20180509T233500Z
DTEND:20180510T023500Z
UID:Ghl3ADDL2UE6iePlkJMZif95@stanza.co
SUMMARY:Timber Rattlers vs. Lugnuts
DESCRIPTION:Enjoy Cher-Make hotdogs, sodas, and domestic beer for $1. A lucky fan will go home with two charter airfare tickets courtesy of AAA Travel and Funjet Vacations.\n\nFollow on MiLB First Pitch: https://stza.co/+vNqV-2n\n\nShop: https://stza.co/+vNqV-2k\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Bang For Your Buck
STATUS:CONFIRMED
CREATED:20180213T144607Z
LAST-MODIFIED:20180213T144607Z
TRANSP:OPAQUE
END:VEVENT
* Timber Rattlers vs. Loons
<2018-05-10 Thu 18:35-21:35>
:PROPERTIES:
:ID:       uhQweyWr63I8h8YmPC9qaPTl@stanza.co
:LOCATION: Craft Brews and Brats
:STATUS:   CONFIRMED
:END:

Timber Rattlers vs. Loons Enjoy 12 oz craft beer and Cher-Make Brats for only $2. Present any Thursday game ticket at Wissota Taphouse for a free beer.

Follow on MiLB First Pitch  https //stza.co/+vNqY-3z

Shop  https //stza.co/+vNqY-11

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Timber Rattlers vs. Loons
END:VALARM
DTSTART:20180510T233500Z
DTEND:20180511T023500Z
UID:uhQweyWr63I8h8YmPC9qaPTl@stanza.co
SUMMARY:Timber Rattlers vs. Loons
DESCRIPTION:Enjoy 12 oz craft beer and Cher-Make Brats for only $2. Present any Thursday game ticket at Wissota Taphouse for a free beer.\n\nFollow on MiLB First Pitch: https://stza.co/+vNqY-3z\n\nShop: https://stza.co/+vNqY-11\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Craft Brews and Brats
STATUS:CONFIRMED
CREATED:20180213T144607Z
LAST-MODIFIED:20180213T144607Z
TRANSP:OPAQUE
END:VEVENT
* Timber Rattlers vs. Loons
<2018-05-11 Fri 18:35-21:35>
:PROPERTIES:
:ID:       svNS3DfJdISEmxty3Vh4BuvT@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Timber Rattlers vs. Loons Timber Rattlers vs. Loons

Follow on MiLB First Pitch  https //stza.co/+vNq_-h

Shop  https //stza.co/+vNq_-2h

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Timber Rattlers vs. Loons
END:VALARM
DTSTART:20180511T233500Z
DTEND:20180512T023500Z
UID:svNS3DfJdISEmxty3Vh4BuvT@stanza.co
SUMMARY:Timber Rattlers vs. Loons
DESCRIPTION:Timber Rattlers vs. Loons\n\nFollow on MiLB First Pitch: https://stza.co/+vNq_-h\n\nShop: https://stza.co/+vNq_-2h\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144607Z
LAST-MODIFIED:20180213T144607Z
TRANSP:OPAQUE
END:VEVENT
* Timber Rattlers vs. Loons
<2018-05-12 Sat 13:05-16:05>
:PROPERTIES:
:ID:       EePZlZ9jLlY8pgnYEHDffhH3@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Timber Rattlers vs. Loons Timber Rattlers vs. Loons

Follow on MiLB First Pitch  https //stza.co/+vNq$-1Y

Shop  https //stza.co/+vNq$-K

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Timber Rattlers vs. Loons
END:VALARM
DTSTART:20180512T180500Z
DTEND:20180512T210500Z
UID:EePZlZ9jLlY8pgnYEHDffhH3@stanza.co
SUMMARY:Timber Rattlers vs. Loons
DESCRIPTION:Timber Rattlers vs. Loons\n\nFollow on MiLB First Pitch: https://stza.co/+vNq$-1Y\n\nShop: https://stza.co/+vNq$-K\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144607Z
LAST-MODIFIED:20180213T144607Z
TRANSP:OPAQUE
END:VEVENT
* Timber Rattlers vs. Snappers
<2018-05-14 Mon 18:35-21:35>
:PROPERTIES:
:ID:       Co44v9AnWAyIQrjmZCuSPUii@stanza.co
:LOCATION: Qdoba Q'Monday
:STATUS:   CONFIRMED
:END:

Timber Rattlers vs. Snappers Purchase any Qdoba entree on any Monday game at any Appleton, Neenah, or Oshkosh location and receive a free Monday game ticket.

Follow on MiLB First Pitch  https //stza.co/+vNr2-M

Shop  https //stza.co/+vNr2-3p

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Timber Rattlers vs. Snappers
END:VALARM
DTSTART:20180514T233500Z
DTEND:20180515T023500Z
UID:Co44v9AnWAyIQrjmZCuSPUii@stanza.co
SUMMARY:Timber Rattlers vs. Snappers
DESCRIPTION:Purchase any Qdoba entree on any Monday game at any Appleton, Neenah, or Oshkosh location and receive a free Monday game ticket.\n\nFollow on MiLB First Pitch: https://stza.co/+vNr2-M\n\nShop: https://stza.co/+vNr2-3p\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Qdoba Q'Monday
STATUS:CONFIRMED
CREATED:20180213T144607Z
LAST-MODIFIED:20180213T144607Z
TRANSP:OPAQUE
END:VEVENT
* Timber Rattlers vs. Snappers
<2018-05-15 Tue 12:05-15:05>
:PROPERTIES:
:ID:       laA_eJupNQT4eHOeGb1Qz2UJ@stanza.co
:LOCATION: Baker Tilly Business Person Special
:STATUS:   CONFIRMED
:END:

Timber Rattlers vs. Snappers Business Persons that present business card, Military Personnel with ID and seniors with ID 55 & older receive a box seat ticket. Beverage & brat or hot dog for just $14.50.

Follow on MiLB First Pitch  https //stza.co/+vNr4-3l

Shop  https //stza.co/+vNr4-h

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Timber Rattlers vs. Snappers
END:VALARM
DTSTART:20180515T170500Z
DTEND:20180515T200500Z
UID:laA_eJupNQT4eHOeGb1Qz2UJ@stanza.co
SUMMARY:Timber Rattlers vs. Snappers
DESCRIPTION:Business Persons that present business card, Military Personnel with ID and seniors with ID 55 & older receive a box seat ticket. Beverage & brat or hot dog for just $14.50.\n\nFollow on MiLB First Pitch: https://stza.co/+vNr4-3l\n\nShop: https://stza.co/+vNr4-h\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Baker Tilly Business Person Special
STATUS:CONFIRMED
CREATED:20180213T144607Z
LAST-MODIFIED:20180213T144607Z
TRANSP:OPAQUE
END:VEVENT
* Timber Rattlers vs. Snappers
<2018-05-16 Wed 18:35-21:35>
:PROPERTIES:
:ID:       H98vawW52HUKc5_L73-Yc51V@stanza.co
:LOCATION: Bang For Your Buck
:STATUS:   CONFIRMED
:END:

Timber Rattlers vs. Snappers Enjoy Cher-Make hotdogs, sodas, and domestic beer for $1. A lucky fan will go home with two charter airfare tickets courtesy of AAA Travel and Funjet Vacations.

Follow on MiLB First Pitch  https //stza.co/+vNr6-3T

Shop  https //stza.co/+vNr6-t

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Timber Rattlers vs. Snappers
END:VALARM
DTSTART:20180516T233500Z
DTEND:20180517T023500Z
UID:H98vawW52HUKc5_L73-Yc51V@stanza.co
SUMMARY:Timber Rattlers vs. Snappers
DESCRIPTION:Enjoy Cher-Make hotdogs, sodas, and domestic beer for $1. A lucky fan will go home with two charter airfare tickets courtesy of AAA Travel and Funjet Vacations.\n\nFollow on MiLB First Pitch: https://stza.co/+vNr6-3T\n\nShop: https://stza.co/+vNr6-t\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Bang For Your Buck
STATUS:CONFIRMED
CREATED:20180213T144607Z
LAST-MODIFIED:20180213T144607Z
TRANSP:OPAQUE
END:VEVENT
* Timber Rattlers vs. Snappers
<2018-05-17 Thu 18:35-21:35>
:PROPERTIES:
:ID:       4revEzWxr44InB9kaK0y4W9k@stanza.co
:LOCATION: Craft Brews and Brats
:STATUS:   CONFIRMED
:END:

Timber Rattlers vs. Snappers Enjoy 12 oz craft beer and Cher-Make Brats for only $2. Present any Thursday game ticket at Wissota Taphouse for a free beer.

Follow on MiLB First Pitch  https //stza.co/+vNr7-1V

Shop  https //stza.co/+vNr7-1b

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Timber Rattlers vs. Snappers
END:VALARM
DTSTART:20180517T233500Z
DTEND:20180518T023500Z
UID:4revEzWxr44InB9kaK0y4W9k@stanza.co
SUMMARY:Timber Rattlers vs. Snappers
DESCRIPTION:Enjoy 12 oz craft beer and Cher-Make Brats for only $2. Present any Thursday game ticket at Wissota Taphouse for a free beer.\n\nFollow on MiLB First Pitch: https://stza.co/+vNr7-1V\n\nShop: https://stza.co/+vNr7-1b\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Craft Brews and Brats
STATUS:CONFIRMED
CREATED:20180213T144607Z
LAST-MODIFIED:20180213T144607Z
TRANSP:OPAQUE
END:VEVENT
* Timber Rattlers vs. Bees
<2018-05-18 Fri 18:35-21:35>
:PROPERTIES:
:ID:       8sYgJUhi4T_a67aYffYRW2eP@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Timber Rattlers vs. Bees Timber Rattlers vs. Bees

Follow on MiLB First Pitch  https //stza.co/+vNra-K

Shop  https //stza.co/+vNra-3h

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Timber Rattlers vs. Bees
END:VALARM
DTSTART:20180518T233500Z
DTEND:20180519T023500Z
UID:8sYgJUhi4T_a67aYffYRW2eP@stanza.co
SUMMARY:Timber Rattlers vs. Bees
DESCRIPTION:Timber Rattlers vs. Bees\n\nFollow on MiLB First Pitch: https://stza.co/+vNra-K\n\nShop: https://stza.co/+vNra-3h\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144607Z
LAST-MODIFIED:20180213T144607Z
TRANSP:OPAQUE
END:VEVENT
* Timber Rattlers vs. Bees
<2018-05-19 Sat 13:05-16:05>
:PROPERTIES:
:ID:       VjZ8-7zpaYm-yQuSU1JbcI7-@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Timber Rattlers vs. Bees Timber Rattlers vs. Bees

Follow on MiLB First Pitch  https //stza.co/+vNrc-3G

Shop  https //stza.co/+vNrc-1_

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Timber Rattlers vs. Bees
END:VALARM
DTSTART:20180519T180500Z
DTEND:20180519T210500Z
UID:VjZ8-7zpaYm-yQuSU1JbcI7-@stanza.co
SUMMARY:Timber Rattlers vs. Bees
DESCRIPTION:Timber Rattlers vs. Bees\n\nFollow on MiLB First Pitch: https://stza.co/+vNrc-3G\n\nShop: https://stza.co/+vNrc-1_\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144607Z
LAST-MODIFIED:20180213T144607Z
TRANSP:OPAQUE
END:VEVENT
* Timber Rattlers vs. Bees
<2018-05-20 Sun 13:05-16:05>
:PROPERTIES:
:ID:       KMPsZm3OOpIDVVfCvcC4nWaF@stanza.co
:LOCATION: Brewers Sunday
:STATUS:   CONFIRMED
:END:

Timber Rattlers vs. Bees Play catch on the field pre-game. Player autographs after the game. Brewers themed jerseys worn on field. Brewers Fan Makeover.

Bark in the Park is back at Neuroscience Group Field in 2018! Don't miss this unique and fun experience, where dogs and their owners get the chance to enjoy the game from the left field berm. Dogs get in free and human tickets are $7 when purchased in advance, $8 day of game. In addition, your pup will receive a special giveaway upon entry! Buy your tickets now to share the excitement of America's favorite pastime with man's best friend.

Follow on MiLB First Pitch  https //stza.co/+vNre-2J

Shop  https //stza.co/+vNre-H

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Timber Rattlers vs. Bees
END:VALARM
DTSTART:20180520T180500Z
DTEND:20180520T210500Z
UID:KMPsZm3OOpIDVVfCvcC4nWaF@stanza.co
SUMMARY:Timber Rattlers vs. Bees
DESCRIPTION:Play catch on the field pre-game. Player autographs after the game. Brewers themed jerseys worn on field. Brewers Fan Makeover.\n\nBark in the Park is back at Neuroscience Group Field in 2018! Don't miss this unique and fun experience, where dogs and their owners get the chance to enjoy the game from the left field berm. Dogs get in free and human tickets are $7 when purchased in advance, $8 day of game. In addition, your pup will receive a special giveaway upon entry! Buy your tickets now to share the excitement of America's favorite pastime with man's best friend.\n\nFollow on MiLB First Pitch: https://stza.co/+vNre-2J\n\nShop: https://stza.co/+vNre-H\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Brewers Sunday
STATUS:CONFIRMED
CREATED:20180213T144607Z
LAST-MODIFIED:20180213T144607Z
TRANSP:OPAQUE
END:VEVENT
* Timber Rattlers @ River Bandits
<2018-05-21 Mon 18:35-21:35>
:PROPERTIES:
:ID:       dV80Mge7POMY1JeiUAustFXv@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Timber Rattlers @ River Bandits Timber Rattlers @ River Bandits

Follow on MiLB First Pitch  https //stza.co/+wxtP-24

Shop  https //stza.co/+wxtP-3F

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Timber Rattlers @ River Bandits
END:VALARM
DTSTART:20180521T233500Z
DTEND:20180522T023500Z
UID:dV80Mge7POMY1JeiUAustFXv@stanza.co
SUMMARY:Timber Rattlers @ River Bandits
DESCRIPTION:Timber Rattlers @ River Bandits\n\nFollow on MiLB First Pitch: https://stza.co/+wxtP-24\n\nShop: https://stza.co/+wxtP-3F\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144607Z
LAST-MODIFIED:20180213T144607Z
TRANSP:OPAQUE
END:VEVENT
* Timber Rattlers @ River Bandits
<2018-05-22 Tue 11:00-14:00>
:PROPERTIES:
:ID:       gg4fUfghNyY-HVGAtprDuUbX@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Timber Rattlers @ River Bandits Timber Rattlers @ River Bandits

Follow on MiLB First Pitch  https //stza.co/+wxtQ-3R

Shop  https //stza.co/+wxtQ-19

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Timber Rattlers @ River Bandits
END:VALARM
DTSTART:20180522T160000Z
DTEND:20180522T190000Z
UID:gg4fUfghNyY-HVGAtprDuUbX@stanza.co
SUMMARY:Timber Rattlers @ River Bandits
DESCRIPTION:Timber Rattlers @ River Bandits\n\nFollow on MiLB First Pitch: https://stza.co/+wxtQ-3R\n\nShop: https://stza.co/+wxtQ-19\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144607Z
LAST-MODIFIED:20180213T144607Z
TRANSP:OPAQUE
END:VEVENT
* Timber Rattlers @ River Bandits
<2018-05-23 Wed 18:35-21:35>
:PROPERTIES:
:ID:       d-nMYXeNH0wOSSJSh14nNecT@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Timber Rattlers @ River Bandits Timber Rattlers @ River Bandits

Follow on MiLB First Pitch  https //stza.co/+wxtW-1C

Shop  https //stza.co/+wxtW-3l

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Timber Rattlers @ River Bandits
END:VALARM
DTSTART:20180523T233500Z
DTEND:20180524T023500Z
UID:d-nMYXeNH0wOSSJSh14nNecT@stanza.co
SUMMARY:Timber Rattlers @ River Bandits
DESCRIPTION:Timber Rattlers @ River Bandits\n\nFollow on MiLB First Pitch: https://stza.co/+wxtW-1C\n\nShop: https://stza.co/+wxtW-3l\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144607Z
LAST-MODIFIED:20180213T144607Z
TRANSP:OPAQUE
END:VEVENT
* Timber Rattlers @ River Bandits
<2018-05-24 Thu 18:35-21:35>
:PROPERTIES:
:ID:       zCeUvfz8sbPSxl_qIKF870xX@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Timber Rattlers @ River Bandits Timber Rattlers @ River Bandits

Follow on MiLB First Pitch  https //stza.co/+wxt$-1t

Shop  https //stza.co/+wxt$-d

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Timber Rattlers @ River Bandits
END:VALARM
DTSTART:20180524T233500Z
DTEND:20180525T023500Z
UID:zCeUvfz8sbPSxl_qIKF870xX@stanza.co
SUMMARY:Timber Rattlers @ River Bandits
DESCRIPTION:Timber Rattlers @ River Bandits\n\nFollow on MiLB First Pitch: https://stza.co/+wxt$-1t\n\nShop: https://stza.co/+wxt$-d\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144607Z
LAST-MODIFIED:20180213T144607Z
TRANSP:OPAQUE
END:VEVENT
* Timber Rattlers @ Cougars
<2018-05-25 Fri 18:30-21:30>
:PROPERTIES:
:ID:       PhxsweIlCAP5ns2bydb1cJ9b@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Timber Rattlers @ Cougars Timber Rattlers @ Cougars

Follow on MiLB First Pitch  https //stza.co/+xBCu-H

Shop  https //stza.co/+xBCu-y

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Timber Rattlers @ Cougars
END:VALARM
DTSTART:20180525T233000Z
DTEND:20180526T023000Z
UID:PhxsweIlCAP5ns2bydb1cJ9b@stanza.co
SUMMARY:Timber Rattlers @ Cougars
DESCRIPTION:Timber Rattlers @ Cougars\n\nFollow on MiLB First Pitch: https://stza.co/+xBCu-H\n\nShop: https://stza.co/+xBCu-y\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144607Z
LAST-MODIFIED:20180213T144607Z
TRANSP:OPAQUE
END:VEVENT
* Timber Rattlers @ Cougars
<2018-05-26 Sat 18:30-21:30>
:PROPERTIES:
:ID:       FxMVEwugcmARwPL5Zeut_goj@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Timber Rattlers @ Cougars Timber Rattlers @ Cougars

Follow on MiLB First Pitch  https //stza.co/+xBCv-1C

Shop  https //stza.co/+xBCv-2c

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Timber Rattlers @ Cougars
END:VALARM
DTSTART:20180526T233000Z
DTEND:20180527T023000Z
UID:FxMVEwugcmARwPL5Zeut_goj@stanza.co
SUMMARY:Timber Rattlers @ Cougars
DESCRIPTION:Timber Rattlers @ Cougars\n\nFollow on MiLB First Pitch: https://stza.co/+xBCv-1C\n\nShop: https://stza.co/+xBCv-2c\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144607Z
LAST-MODIFIED:20180213T144607Z
TRANSP:OPAQUE
END:VEVENT
* Timber Rattlers @ Cougars
<2018-05-27 Sun 18:30-21:30>
:PROPERTIES:
:ID:       BbMYlFqMUj_gcj4MuSwywqit@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Timber Rattlers @ Cougars Timber Rattlers @ Cougars

Follow on MiLB First Pitch  https //stza.co/+xBCw-3o

Shop  https //stza.co/+xBCw-t

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Timber Rattlers @ Cougars
END:VALARM
DTSTART:20180527T233000Z
DTEND:20180528T023000Z
UID:BbMYlFqMUj_gcj4MuSwywqit@stanza.co
SUMMARY:Timber Rattlers @ Cougars
DESCRIPTION:Timber Rattlers @ Cougars\n\nFollow on MiLB First Pitch: https://stza.co/+xBCw-3o\n\nShop: https://stza.co/+xBCw-t\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144607Z
LAST-MODIFIED:20180213T144607Z
TRANSP:OPAQUE
END:VEVENT
* Timber Rattlers @ Cougars
<2018-05-28 Mon 13:00-16:00>
:PROPERTIES:
:ID:       LLf9m7hsV2ncLLTufWSaZLBy@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Timber Rattlers @ Cougars Timber Rattlers @ Cougars

Follow on MiLB First Pitch  https //stza.co/+xBCx-J

Shop  https //stza.co/+xBCx-2z

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Timber Rattlers @ Cougars
END:VALARM
DTSTART:20180528T180000Z
DTEND:20180528T210000Z
UID:LLf9m7hsV2ncLLTufWSaZLBy@stanza.co
SUMMARY:Timber Rattlers @ Cougars
DESCRIPTION:Timber Rattlers @ Cougars\n\nFollow on MiLB First Pitch: https://stza.co/+xBCx-J\n\nShop: https://stza.co/+xBCx-2z\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144607Z
LAST-MODIFIED:20180213T144607Z
TRANSP:OPAQUE
END:VEVENT
* Timber Rattlers @ Kernels
<2018-05-29 Tue 18:35-21:35>
:PROPERTIES:
:ID:       7syMqQotNQKfZ2Eu5nq2Q8nv@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Timber Rattlers @ Kernels Timber Rattlers @ Kernels

Buy tickets here  https //stza.co/~vNpz

Follow on MiLB First Pitch  https //stza.co/+vNpz-2r

Shop  https //stza.co/+vNpz-3d

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Timber Rattlers @ Kernels
END:VALARM
DTSTART:20180529T233500Z
DTEND:20180530T023500Z
UID:7syMqQotNQKfZ2Eu5nq2Q8nv@stanza.co
SUMMARY:Timber Rattlers @ Kernels
DESCRIPTION:Timber Rattlers @ Kernels\n\nBuy tickets here: https://stza.co/~vNpz\n\nFollow on MiLB First Pitch: https://stza.co/+vNpz-2r\n\nShop: https://stza.co/+vNpz-3d\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144607Z
LAST-MODIFIED:20180213T144607Z
TRANSP:OPAQUE
END:VEVENT
* Timber Rattlers @ Kernels
<2018-05-30 Wed 12:05-15:05>
:PROPERTIES:
:ID:       lkRN75TVHCMxA8GRvery9HKs@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Timber Rattlers @ Kernels Timber Rattlers @ Kernels

Buy tickets here  https //stza.co/~w0O3

Follow on MiLB First Pitch  https //stza.co/+w0O3-L

Shop  https //stza.co/+w0O3-F

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Timber Rattlers @ Kernels
END:VALARM
DTSTART:20180530T170500Z
DTEND:20180530T200500Z
UID:lkRN75TVHCMxA8GRvery9HKs@stanza.co
SUMMARY:Timber Rattlers @ Kernels
DESCRIPTION:Timber Rattlers @ Kernels\n\nBuy tickets here: https://stza.co/~w0O3\n\nFollow on MiLB First Pitch: https://stza.co/+w0O3-L\n\nShop: https://stza.co/+w0O3-F\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144607Z
LAST-MODIFIED:20180213T144607Z
TRANSP:OPAQUE
END:VEVENT
* Timber Rattlers @ Kernels
<2018-05-31 Thu 18:35-21:35>
:PROPERTIES:
:ID:       QHXLxqtg-twF_d2gAv9BO4Wx@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Timber Rattlers @ Kernels Timber Rattlers @ Kernels

Buy tickets here  https //stza.co/~vNpB

Follow on MiLB First Pitch  https //stza.co/+vNpB-h

Shop  https //stza.co/+vNpB-B

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Timber Rattlers @ Kernels
END:VALARM
DTSTART:20180531T233500Z
DTEND:20180601T023500Z
UID:QHXLxqtg-twF_d2gAv9BO4Wx@stanza.co
SUMMARY:Timber Rattlers @ Kernels
DESCRIPTION:Timber Rattlers @ Kernels\n\nBuy tickets here: https://stza.co/~vNpB\n\nFollow on MiLB First Pitch: https://stza.co/+vNpB-h\n\nShop: https://stza.co/+vNpB-B\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144607Z
LAST-MODIFIED:20180213T144607Z
TRANSP:OPAQUE
END:VEVENT
* Timber Rattlers vs. Cougars
<2018-06-01 Fri 19:05-22:05>
:PROPERTIES:
:ID:       Wh19WrtbJJFZr55ptQOBYhe9@stanza.co
:LOCATION: Pirate Night
:STATUS:   CONFIRMED
:END:

Timber Rattlers vs. Cougars Ahoy Mateys! Come out and join us for Pirate Night at the Ballpark! First 500 kids will receive a pirate themed giveaway. Make sure to stick around for Kids Run the Bases and the first Fireworks show of the season!

Follow on MiLB First Pitch  https //stza.co/+vNrf-j

Shop  https //stza.co/+vNrf-1D

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Timber Rattlers vs. Cougars
END:VALARM
DTSTART:20180602T000500Z
DTEND:20180602T030500Z
UID:Wh19WrtbJJFZr55ptQOBYhe9@stanza.co
SUMMARY:Timber Rattlers vs. Cougars
DESCRIPTION:Ahoy Mateys! Come out and join us for Pirate Night at the Ballpark! First 500 kids will receive a pirate themed giveaway. Make sure to stick around for Kids Run the Bases and the first Fireworks show of the season!\n\nFollow on MiLB First Pitch: https://stza.co/+vNrf-j\n\nShop: https://stza.co/+vNrf-1D\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Pirate Night
STATUS:CONFIRMED
CREATED:20180213T144607Z
LAST-MODIFIED:20180213T144607Z
TRANSP:OPAQUE
END:VEVENT
* Timber Rattlers vs. Cougars
<2018-06-02 Sat 19:05-22:05>
:PROPERTIES:
:ID:       eh8BpT8yv3QtqldPWkjXERC0@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Timber Rattlers vs. Cougars Timber Rattlers vs. Cougars

Follow on MiLB First Pitch  https //stza.co/+vNri-3O

Shop  https //stza.co/+vNri-31

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Timber Rattlers vs. Cougars
END:VALARM
DTSTART:20180603T000500Z
DTEND:20180603T030500Z
UID:eh8BpT8yv3QtqldPWkjXERC0@stanza.co
SUMMARY:Timber Rattlers vs. Cougars
DESCRIPTION:Timber Rattlers vs. Cougars\n\nFollow on MiLB First Pitch: https://stza.co/+vNri-3O\n\nShop: https://stza.co/+vNri-31\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144607Z
LAST-MODIFIED:20180213T144607Z
TRANSP:OPAQUE
END:VEVENT
* Timber Rattlers vs. Cougars
<2018-06-03 Sun 13:05-16:05>
:PROPERTIES:
:ID:       lNz_yEhxXeieJbJXLRAp_wT3@stanza.co
:LOCATION: Brewers Sunday
:STATUS:   CONFIRMED
:END:

Timber Rattlers vs. Cougars Play catch on the field pre-game. Player autographs after the game. Brewers themed jerseys worn on field. Brewers Fan Makeover.

Follow on MiLB First Pitch  https //stza.co/+vNrj-1f

Shop  https //stza.co/+vNrj-y

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Timber Rattlers vs. Cougars
END:VALARM
DTSTART:20180603T180500Z
DTEND:20180603T210500Z
UID:lNz_yEhxXeieJbJXLRAp_wT3@stanza.co
SUMMARY:Timber Rattlers vs. Cougars
DESCRIPTION:Play catch on the field pre-game. Player autographs after the game. Brewers themed jerseys worn on field. Brewers Fan Makeover.\n\nFollow on MiLB First Pitch: https://stza.co/+vNrj-1f\n\nShop: https://stza.co/+vNrj-y\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Brewers Sunday
STATUS:CONFIRMED
CREATED:20180213T144607Z
LAST-MODIFIED:20180213T144607Z
TRANSP:OPAQUE
END:VEVENT
* Timber Rattlers vs. River Bandits
<2018-06-05 Tue 19:05-22:05>
:PROPERTIES:
:ID:       sH_NnnxFnqLVDxHTvasZcQ7P@stanza.co
:LOCATION: Baker Tilly Business Person Special
:STATUS:   CONFIRMED
:END:

Timber Rattlers vs. River Bandits Business Persons that present business card, Military Personnel with ID and seniors with ID 55 & older receive a box seat ticket. Beverage & brat or hot dog for just $14.50.

Follow on MiLB First Pitch  https //stza.co/+vNrm-2y

Shop  https //stza.co/+vNrm-M

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Timber Rattlers vs. River Bandits
END:VALARM
DTSTART:20180606T000500Z
DTEND:20180606T030500Z
UID:sH_NnnxFnqLVDxHTvasZcQ7P@stanza.co
SUMMARY:Timber Rattlers vs. River Bandits
DESCRIPTION:Business Persons that present business card, Military Personnel with ID and seniors with ID 55 & older receive a box seat ticket. Beverage & brat or hot dog for just $14.50.\n\nFollow on MiLB First Pitch: https://stza.co/+vNrm-2y\n\nShop: https://stza.co/+vNrm-M\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Baker Tilly Business Person Special
STATUS:CONFIRMED
CREATED:20180213T144607Z
LAST-MODIFIED:20180213T144607Z
TRANSP:OPAQUE
END:VEVENT
* Timber Rattlers vs. River Bandits
<2018-06-06 Wed 19:05-22:05>
:PROPERTIES:
:ID:       8_Ib7i54aJTV0X9YSgmQXbGh@stanza.co
:LOCATION: Bang For Your Buck
:STATUS:   CONFIRMED
:END:

Timber Rattlers vs. River Bandits Enjoy Cher-Make hotdogs, sodas, and domestic beer for $1. A lucky fan will go home with two charter airfare tickets courtesy of AAA Travel and Funjet Vacations.

Follow on MiLB First Pitch  https //stza.co/+vNro-1u

Shop  https //stza.co/+vNro-2M

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Timber Rattlers vs. River Bandits
END:VALARM
DTSTART:20180607T000500Z
DTEND:20180607T030500Z
UID:8_Ib7i54aJTV0X9YSgmQXbGh@stanza.co
SUMMARY:Timber Rattlers vs. River Bandits
DESCRIPTION:Enjoy Cher-Make hotdogs, sodas, and domestic beer for $1. A lucky fan will go home with two charter airfare tickets courtesy of AAA Travel and Funjet Vacations.\n\nFollow on MiLB First Pitch: https://stza.co/+vNro-1u\n\nShop: https://stza.co/+vNro-2M\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Bang For Your Buck
STATUS:CONFIRMED
CREATED:20180213T144607Z
LAST-MODIFIED:20180213T144607Z
TRANSP:OPAQUE
END:VEVENT
* Timber Rattlers vs. River Bandits
<2018-06-07 Thu 19:05-22:05>
:PROPERTIES:
:ID:       2w0OWJGaJsNTXvaqnPFN6aFG@stanza.co
:LOCATION: Craft Brews and Brats
:STATUS:   CONFIRMED
:END:

Timber Rattlers vs. River Bandits Enjoy 12 oz craft beer and Cher-Make Brats for only $2. Present any Thursday game ticket at Wissota Taphouse for a free beer.

Giveaways, cheese samplings, milk mustaches, cow jerseys and of course.... actual cows! The first 1,000 fans through the gates will receive a special cow themed ice cream helmet bowl.

Follow on MiLB First Pitch  https //stza.co/+vNrp-1K

Shop  https //stza.co/+vNrp-3F

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Timber Rattlers vs. River Bandits
END:VALARM
DTSTART:20180608T000500Z
DTEND:20180608T030500Z
UID:2w0OWJGaJsNTXvaqnPFN6aFG@stanza.co
SUMMARY:Timber Rattlers vs. River Bandits
DESCRIPTION:Enjoy 12 oz craft beer and Cher-Make Brats for only $2. Present any Thursday game ticket at Wissota Taphouse for a free beer.\n\nGiveaways, cheese samplings, milk mustaches, cow jerseys and of course.... actual cows! The first 1,000 fans through the gates will receive a special cow themed ice cream helmet bowl.\n\nFollow on MiLB First Pitch: https://stza.co/+vNrp-1K\n\nShop: https://stza.co/+vNrp-3F\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Craft Brews and Brats
STATUS:CONFIRMED
CREATED:20180213T144607Z
LAST-MODIFIED:20180213T144607Z
TRANSP:OPAQUE
END:VEVENT
* Timber Rattlers vs. Kernels
<2018-06-08 Fri 19:05-22:05>
:PROPERTIES:
:ID:       A1bMGKcSj6gzTYnu-You98lK@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Timber Rattlers vs. Kernels Timber Rattlers vs. Kernels

Follow on MiLB First Pitch  https //stza.co/+vNrr-13

Shop  https //stza.co/+vNrr-3u

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Timber Rattlers vs. Kernels
END:VALARM
DTSTART:20180609T000500Z
DTEND:20180609T030500Z
UID:A1bMGKcSj6gzTYnu-You98lK@stanza.co
SUMMARY:Timber Rattlers vs. Kernels
DESCRIPTION:Timber Rattlers vs. Kernels\n\nFollow on MiLB First Pitch: https://stza.co/+vNrr-13\n\nShop: https://stza.co/+vNrr-3u\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144607Z
LAST-MODIFIED:20180213T144607Z
TRANSP:OPAQUE
END:VEVENT
* Timber Rattlers vs. Kernels
<2018-06-09 Sat 18:35-21:35>
:PROPERTIES:
:ID:       I1fEF40qrppb0liaQafwvJoq@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Timber Rattlers vs. Kernels Timber Rattlers vs. Kernels

Follow on MiLB First Pitch  https //stza.co/+vNrt-4

Shop  https //stza.co/+vNrt-z

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Timber Rattlers vs. Kernels
END:VALARM
DTSTART:20180609T233500Z
DTEND:20180610T023500Z
UID:I1fEF40qrppb0liaQafwvJoq@stanza.co
SUMMARY:Timber Rattlers vs. Kernels
DESCRIPTION:Timber Rattlers vs. Kernels\n\nFollow on MiLB First Pitch: https://stza.co/+vNrt-4\n\nShop: https://stza.co/+vNrt-z\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144607Z
LAST-MODIFIED:20180213T144607Z
TRANSP:OPAQUE
END:VEVENT
* Timber Rattlers vs. Kernels
<2018-06-10 Sun 13:05-16:05>
:PROPERTIES:
:ID:       rTzqNF0QaPuAWCCDfZpqYuu5@stanza.co
:LOCATION: Brewers Sunday
:STATUS:   CONFIRMED
:END:

Timber Rattlers vs. Kernels Play catch on the field pre-game. Player autographs after the game. Brewers themed jerseys worn on field. Brewers Fan Makeover.

Follow on MiLB First Pitch  https //stza.co/+vNrw-1V

Shop  https //stza.co/+vNrw-1W

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Timber Rattlers vs. Kernels
END:VALARM
DTSTART:20180610T180500Z
DTEND:20180610T210500Z
UID:rTzqNF0QaPuAWCCDfZpqYuu5@stanza.co
SUMMARY:Timber Rattlers vs. Kernels
DESCRIPTION:Play catch on the field pre-game. Player autographs after the game. Brewers themed jerseys worn on field. Brewers Fan Makeover.\n\nFollow on MiLB First Pitch: https://stza.co/+vNrw-1V\n\nShop: https://stza.co/+vNrw-1W\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Brewers Sunday
STATUS:CONFIRMED
CREATED:20180213T144607Z
LAST-MODIFIED:20180213T144607Z
TRANSP:OPAQUE
END:VEVENT
* Timber Rattlers vs. Kernels
<2018-06-11 Mon 12:05-15:05>
:PROPERTIES:
:ID:       1VqOsoB6765DnKcqIoT4uNIB@stanza.co
:LOCATION: Qdoba Q'Monday
:STATUS:   CONFIRMED
:END:

Timber Rattlers vs. Kernels Purchase any Qdoba entree on any Monday game at any Appleton, Neenah, or Oshkosh location and receive a free Monday game ticket.

Follow on MiLB First Pitch  https //stza.co/+vNry-2k

Shop  https //stza.co/+vNry-w

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Timber Rattlers vs. Kernels
END:VALARM
DTSTART:20180611T170500Z
DTEND:20180611T200500Z
UID:1VqOsoB6765DnKcqIoT4uNIB@stanza.co
SUMMARY:Timber Rattlers vs. Kernels
DESCRIPTION:Purchase any Qdoba entree on any Monday game at any Appleton, Neenah, or Oshkosh location and receive a free Monday game ticket.\n\nFollow on MiLB First Pitch: https://stza.co/+vNry-2k\n\nShop: https://stza.co/+vNry-w\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Qdoba Q'Monday
STATUS:CONFIRMED
CREATED:20180213T144607Z
LAST-MODIFIED:20180213T144607Z
TRANSP:OPAQUE
END:VEVENT
* Timber Rattlers @ Bees
<2018-06-12 Tue 18:30-21:30>
:PROPERTIES:
:ID:       SY1N4XpVLWGeFb8OOYk94fZR@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Timber Rattlers @ Bees Timber Rattlers @ Bees

Follow on MiLB First Pitch  https //stza.co/+xBCn-2Z

Shop  https //stza.co/+xBCn-1Z

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Timber Rattlers @ Bees
END:VALARM
DTSTART:20180612T233000Z
DTEND:20180613T023000Z
UID:SY1N4XpVLWGeFb8OOYk94fZR@stanza.co
SUMMARY:Timber Rattlers @ Bees
DESCRIPTION:Timber Rattlers @ Bees\n\nFollow on MiLB First Pitch: https://stza.co/+xBCn-2Z\n\nShop: https://stza.co/+xBCn-1Z\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144607Z
LAST-MODIFIED:20180213T144607Z
TRANSP:OPAQUE
END:VEVENT
* Timber Rattlers @ Bees
<2018-06-13 Wed 18:30-21:30>
:PROPERTIES:
:ID:       paFhE4c3bcU7E7mTwh_RTB4t@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Timber Rattlers @ Bees Timber Rattlers @ Bees

Follow on MiLB First Pitch  https //stza.co/+xBCo-19

Shop  https //stza.co/+xBCo-31

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Timber Rattlers @ Bees
END:VALARM
DTSTART:20180613T233000Z
DTEND:20180614T023000Z
UID:paFhE4c3bcU7E7mTwh_RTB4t@stanza.co
SUMMARY:Timber Rattlers @ Bees
DESCRIPTION:Timber Rattlers @ Bees\n\nFollow on MiLB First Pitch: https://stza.co/+xBCo-19\n\nShop: https://stza.co/+xBCo-31\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144607Z
LAST-MODIFIED:20180213T144607Z
TRANSP:OPAQUE
END:VEVENT
* Timber Rattlers @ Bees
<2018-06-14 Thu 18:30-21:30>
:PROPERTIES:
:ID:       9FFjP0nPVys6shwCu0AY3VXO@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Timber Rattlers @ Bees Timber Rattlers @ Bees

Follow on MiLB First Pitch  https //stza.co/+xBCq-31

Shop  https //stza.co/+xBCq-1G

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Timber Rattlers @ Bees
END:VALARM
DTSTART:20180614T233000Z
DTEND:20180615T023000Z
UID:9FFjP0nPVys6shwCu0AY3VXO@stanza.co
SUMMARY:Timber Rattlers @ Bees
DESCRIPTION:Timber Rattlers @ Bees\n\nFollow on MiLB First Pitch: https://stza.co/+xBCq-31\n\nShop: https://stza.co/+xBCq-1G\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144607Z
LAST-MODIFIED:20180213T144607Z
TRANSP:OPAQUE
END:VEVENT
* Timber Rattlers @ Cougars
<2018-06-15 Fri 18:30-21:30>
:PROPERTIES:
:ID:       GhS3YNgFQvcxfQl5BmBPeDL6@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Timber Rattlers @ Cougars Timber Rattlers @ Cougars

Follow on MiLB First Pitch  https //stza.co/+xBCy-2p

Shop  https //stza.co/+xBCy-3H

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Timber Rattlers @ Cougars
END:VALARM
DTSTART:20180615T233000Z
DTEND:20180616T023000Z
UID:GhS3YNgFQvcxfQl5BmBPeDL6@stanza.co
SUMMARY:Timber Rattlers @ Cougars
DESCRIPTION:Timber Rattlers @ Cougars\n\nFollow on MiLB First Pitch: https://stza.co/+xBCy-2p\n\nShop: https://stza.co/+xBCy-3H\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144607Z
LAST-MODIFIED:20180213T144607Z
TRANSP:OPAQUE
END:VEVENT
* Timber Rattlers @ Cougars
<2018-06-16 Sat 18:30-21:30>
:PROPERTIES:
:ID:       7A1DwVgzOXvkxHaaK1mOHQOD@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Timber Rattlers @ Cougars Timber Rattlers @ Cougars

Follow on MiLB First Pitch  https //stza.co/+xBCz-3z

Shop  https //stza.co/+xBCz-1Y

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Timber Rattlers @ Cougars
END:VALARM
DTSTART:20180616T233000Z
DTEND:20180617T023000Z
UID:7A1DwVgzOXvkxHaaK1mOHQOD@stanza.co
SUMMARY:Timber Rattlers @ Cougars
DESCRIPTION:Timber Rattlers @ Cougars\n\nFollow on MiLB First Pitch: https://stza.co/+xBCz-3z\n\nShop: https://stza.co/+xBCz-1Y\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144607Z
LAST-MODIFIED:20180213T144607Z
TRANSP:OPAQUE
END:VEVENT
* Timber Rattlers @ Cougars
<2018-06-17 Sun 13:00-16:00>
:PROPERTIES:
:ID:       FxGZ2Zw8niS7Zudj_vbZG5pe@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Timber Rattlers @ Cougars Timber Rattlers @ Cougars

Follow on MiLB First Pitch  https //stza.co/+xBCE-2H

Shop  https //stza.co/+xBCE-3y

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Timber Rattlers @ Cougars
END:VALARM
DTSTART:20180617T180000Z
DTEND:20180617T210000Z
UID:FxGZ2Zw8niS7Zudj_vbZG5pe@stanza.co
SUMMARY:Timber Rattlers @ Cougars
DESCRIPTION:Timber Rattlers @ Cougars\n\nFollow on MiLB First Pitch: https://stza.co/+xBCE-2H\n\nShop: https://stza.co/+xBCE-3y\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144607Z
LAST-MODIFIED:20180213T144607Z
TRANSP:OPAQUE
END:VEVENT
* Timber Rattlers @ Kernels
<2018-06-21 Thu 18:35-21:35>
:PROPERTIES:
:ID:       HKfk_KCoIpupOot9WaW25fH3@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Timber Rattlers @ Kernels Timber Rattlers @ Kernels

Buy tickets here  https //stza.co/~vNpC

Follow on MiLB First Pitch  https //stza.co/+vNpC-O

Shop  https //stza.co/+vNpC-1m

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Timber Rattlers @ Kernels
END:VALARM
DTSTART:20180621T233500Z
DTEND:20180622T023500Z
UID:HKfk_KCoIpupOot9WaW25fH3@stanza.co
SUMMARY:Timber Rattlers @ Kernels
DESCRIPTION:Timber Rattlers @ Kernels\n\nBuy tickets here: https://stza.co/~vNpC\n\nFollow on MiLB First Pitch: https://stza.co/+vNpC-O\n\nShop: https://stza.co/+vNpC-1m\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144607Z
LAST-MODIFIED:20180213T144607Z
TRANSP:OPAQUE
END:VEVENT
* Timber Rattlers @ Kernels
<2018-06-22 Fri 18:35-21:35>
:PROPERTIES:
:ID:       vD9OyROtjrB4VrwuXNIUORoy@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Timber Rattlers @ Kernels Timber Rattlers @ Kernels

Buy tickets here  https //stza.co/~vNpD

Follow on MiLB First Pitch  https //stza.co/+vNpD-17

Shop  https //stza.co/+vNpD-1C

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Timber Rattlers @ Kernels
END:VALARM
DTSTART:20180622T233500Z
DTEND:20180623T023500Z
UID:vD9OyROtjrB4VrwuXNIUORoy@stanza.co
SUMMARY:Timber Rattlers @ Kernels
DESCRIPTION:Timber Rattlers @ Kernels\n\nBuy tickets here: https://stza.co/~vNpD\n\nFollow on MiLB First Pitch: https://stza.co/+vNpD-17\n\nShop: https://stza.co/+vNpD-1C\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144607Z
LAST-MODIFIED:20180213T144607Z
TRANSP:OPAQUE
END:VEVENT
* Timber Rattlers @ Kernels
<2018-06-23 Sat 18:35-21:35>
:PROPERTIES:
:ID:       nQXv4Uy7rmFrrqY-eAKHDLgy@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Timber Rattlers @ Kernels Timber Rattlers @ Kernels

Buy tickets here  https //stza.co/~vNpE

Follow on MiLB First Pitch  https //stza.co/+vNpE-3N

Shop  https //stza.co/+vNpE-2U

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Timber Rattlers @ Kernels
END:VALARM
DTSTART:20180623T233500Z
DTEND:20180624T023500Z
UID:nQXv4Uy7rmFrrqY-eAKHDLgy@stanza.co
SUMMARY:Timber Rattlers @ Kernels
DESCRIPTION:Timber Rattlers @ Kernels\n\nBuy tickets here: https://stza.co/~vNpE\n\nFollow on MiLB First Pitch: https://stza.co/+vNpE-3N\n\nShop: https://stza.co/+vNpE-2U\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144607Z
LAST-MODIFIED:20180213T144607Z
TRANSP:OPAQUE
END:VEVENT
* Timber Rattlers @ Kernels
<2018-06-24 Sun 14:05-17:05>
:PROPERTIES:
:ID:       iqRjeCUMDi_xUychp6BkF7oP@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Timber Rattlers @ Kernels Timber Rattlers @ Kernels

Buy tickets here  https //stza.co/~vNpF

Follow on MiLB First Pitch  https //stza.co/+vNpF-1s

Shop  https //stza.co/+vNpF-3W

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Timber Rattlers @ Kernels
END:VALARM
DTSTART:20180624T190500Z
DTEND:20180624T220500Z
UID:iqRjeCUMDi_xUychp6BkF7oP@stanza.co
SUMMARY:Timber Rattlers @ Kernels
DESCRIPTION:Timber Rattlers @ Kernels\n\nBuy tickets here: https://stza.co/~vNpF\n\nFollow on MiLB First Pitch: https://stza.co/+vNpF-1s\n\nShop: https://stza.co/+vNpF-3W\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144607Z
LAST-MODIFIED:20180213T144607Z
TRANSP:OPAQUE
END:VEVENT
* Timber Rattlers @ River Bandits
<2018-06-25 Mon 18:35-21:35>
:PROPERTIES:
:ID:       3TBg8K-GLZgv-NxflNeP8--w@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Timber Rattlers @ River Bandits Timber Rattlers @ River Bandits

Follow on MiLB First Pitch  https //stza.co/+wxu3-3E

Shop  https //stza.co/+wxu3-2F

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Timber Rattlers @ River Bandits
END:VALARM
DTSTART:20180625T233500Z
DTEND:20180626T023500Z
UID:3TBg8K-GLZgv-NxflNeP8--w@stanza.co
SUMMARY:Timber Rattlers @ River Bandits
DESCRIPTION:Timber Rattlers @ River Bandits\n\nFollow on MiLB First Pitch: https://stza.co/+wxu3-3E\n\nShop: https://stza.co/+wxu3-2F\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144607Z
LAST-MODIFIED:20180213T144607Z
TRANSP:OPAQUE
END:VEVENT
* Timber Rattlers @ River Bandits
<2018-06-26 Tue 18:35-21:35>
:PROPERTIES:
:ID:       _dcHqv_p-9bSaoyawSH7s45T@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Timber Rattlers @ River Bandits Timber Rattlers @ River Bandits

Follow on MiLB First Pitch  https //stza.co/+wxu4-2i

Shop  https //stza.co/+wxu4-3V

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Timber Rattlers @ River Bandits
END:VALARM
DTSTART:20180626T233500Z
DTEND:20180627T023500Z
UID:_dcHqv_p-9bSaoyawSH7s45T@stanza.co
SUMMARY:Timber Rattlers @ River Bandits
DESCRIPTION:Timber Rattlers @ River Bandits\n\nFollow on MiLB First Pitch: https://stza.co/+wxu4-2i\n\nShop: https://stza.co/+wxu4-3V\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144607Z
LAST-MODIFIED:20180213T144607Z
TRANSP:OPAQUE
END:VEVENT
* Timber Rattlers @ River Bandits
<2018-06-27 Wed 18:35-21:35>
:PROPERTIES:
:ID:       0AHaKheUvghU0W2F5fYgYkbl@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Timber Rattlers @ River Bandits Timber Rattlers @ River Bandits

Follow on MiLB First Pitch  https //stza.co/+wxu5-2g

Shop  https //stza.co/+wxu5-$

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Timber Rattlers @ River Bandits
END:VALARM
DTSTART:20180627T233500Z
DTEND:20180628T023500Z
UID:0AHaKheUvghU0W2F5fYgYkbl@stanza.co
SUMMARY:Timber Rattlers @ River Bandits
DESCRIPTION:Timber Rattlers @ River Bandits\n\nFollow on MiLB First Pitch: https://stza.co/+wxu5-2g\n\nShop: https://stza.co/+wxu5-$\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144607Z
LAST-MODIFIED:20180213T144607Z
TRANSP:OPAQUE
END:VEVENT
* Timber Rattlers vs. LumberKings
<2018-06-28 Thu 19:05-22:05>
:PROPERTIES:
:ID:       DgJEMAv3xa76DhRUpnhLYFlw@stanza.co
:LOCATION: Craft Brews and Brats
:STATUS:   CONFIRMED
:END:

Timber Rattlers vs. LumberKings Enjoy 12 oz craft beer and Cher-Make Brats for only $2. Present any Thursday game ticket at Wissota Taphouse for a free beer.

A night where Dinosaurs rule the Ballpark! A giant Tyrannosaurus Rex will be walking around, see real fossils and learn from a Paleontologist Dig for bones in the Kids Zone beach and it is also Peanut Free night.

Follow on MiLB First Pitch  https //stza.co/+vNrA-25

Shop  https //stza.co/+vNrA-o

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Timber Rattlers vs. LumberKings
END:VALARM
DTSTART:20180629T000500Z
DTEND:20180629T030500Z
UID:DgJEMAv3xa76DhRUpnhLYFlw@stanza.co
SUMMARY:Timber Rattlers vs. LumberKings
DESCRIPTION:Enjoy 12 oz craft beer and Cher-Make Brats for only $2. Present any Thursday game ticket at Wissota Taphouse for a free beer.\n\nA night where Dinosaurs rule the Ballpark! A giant Tyrannosaurus Rex will be walking around, see real fossils and learn from a Paleontologist Dig for bones in the Kids Zone beach and it is also Peanut Free night.\n\nFollow on MiLB First Pitch: https://stza.co/+vNrA-25\n\nShop: https://stza.co/+vNrA-o\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Craft Brews and Brats
STATUS:CONFIRMED
CREATED:20180213T144607Z
LAST-MODIFIED:20180213T144607Z
TRANSP:OPAQUE
END:VEVENT
* Timber Rattlers vs. LumberKings
<2018-06-29 Fri 19:05-22:05>
:PROPERTIES:
:ID:       5KsaAsHu-3wPGPt__OW_Ebe-@stanza.co
:LOCATION: Harry Potter Night
:STATUS:   CONFIRMED
:END:

Timber Rattlers vs. LumberKings Join us as we turn the stadium into Hogwarts School of Witchcraft and Wizardry! The first 1,000 fans will receive a pair of Harry Potter themed socks!

Follow on MiLB First Pitch  https //stza.co/+vNrB-2k

Shop  https //stza.co/+vNrB-10

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Timber Rattlers vs. LumberKings
END:VALARM
DTSTART:20180630T000500Z
DTEND:20180630T030500Z
UID:5KsaAsHu-3wPGPt__OW_Ebe-@stanza.co
SUMMARY:Timber Rattlers vs. LumberKings
DESCRIPTION:Join us as we turn the stadium into Hogwarts School of Witchcraft and Wizardry! The first 1,000 fans will receive a pair of Harry Potter themed socks!\n\nFollow on MiLB First Pitch: https://stza.co/+vNrB-2k\n\nShop: https://stza.co/+vNrB-10\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Harry Potter Night
STATUS:CONFIRMED
CREATED:20180213T144607Z
LAST-MODIFIED:20180213T144607Z
TRANSP:OPAQUE
END:VEVENT
* Timber Rattlers vs. LumberKings
<2018-06-30 Sat 18:35-21:35>
:PROPERTIES:
:ID:       7l2U8w7NVd30q08q4SFTEIvb@stanza.co
:LOCATION: May the force be with you! Come check out Stars Wars Night at the park
:STATUS:   CONFIRMED
:END:

Timber Rattlers vs. LumberKings STAR WARS NIGHT returns! This is your chance to meet & greet with Star Wars characters and bid on brand new themed jerseys worn by the team that night. All proceeds from the jersey auction will benefit Make-A-Wish Wisconsin. Make sure to stick around for Kids Run the Bases and a fantastic post-game fireworks show!

Follow on MiLB First Pitch  https //stza.co/+vNrD-3n

Shop  https //stza.co/+vNrD-16

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Timber Rattlers vs. LumberKings
END:VALARM
DTSTART:20180630T233500Z
DTEND:20180701T023500Z
UID:7l2U8w7NVd30q08q4SFTEIvb@stanza.co
SUMMARY:Timber Rattlers vs. LumberKings
DESCRIPTION:STAR WARS NIGHT returns! This is your chance to meet & greet with Star Wars characters and bid on brand new themed jerseys worn by the team that night. All proceeds from the jersey auction will benefit Make-A-Wish Wisconsin. Make sure to stick around for Kids Run the Bases and a fantastic post-game fireworks show!\n\nFollow on MiLB First Pitch: https://stza.co/+vNrD-3n\n\nShop: https://stza.co/+vNrD-16\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:May the force be with you! Come check out Stars Wars Night at the park
STATUS:CONFIRMED
CREATED:20180213T144607Z
LAST-MODIFIED:20180213T144607Z
TRANSP:OPAQUE
END:VEVENT
* Timber Rattlers vs. LumberKings
<2018-07-01 Sun 13:05-16:05>
:PROPERTIES:
:ID:       UsTPvtkyyICJaS-9L6WqMg8b@stanza.co
:LOCATION: Brewers Sunday
:STATUS:   CONFIRMED
:END:

Timber Rattlers vs. LumberKings Play catch on the field pre-game. Player autographs after the game. Brewers themed jerseys worn on field. Brewers Fan Makeover.

Follow on MiLB First Pitch  https //stza.co/+vNrG-36

Shop  https //stza.co/+vNrG-1N

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Timber Rattlers vs. LumberKings
END:VALARM
DTSTART:20180701T180500Z
DTEND:20180701T210500Z
UID:UsTPvtkyyICJaS-9L6WqMg8b@stanza.co
SUMMARY:Timber Rattlers vs. LumberKings
DESCRIPTION:Play catch on the field pre-game. Player autographs after the game. Brewers themed jerseys worn on field. Brewers Fan Makeover.\n\nFollow on MiLB First Pitch: https://stza.co/+vNrG-36\n\nShop: https://stza.co/+vNrG-1N\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Brewers Sunday
STATUS:CONFIRMED
CREATED:20180213T144607Z
LAST-MODIFIED:20180213T144607Z
TRANSP:OPAQUE
END:VEVENT
* Timber Rattlers vs. Kernels
<2018-07-02 Mon 19:05-22:05>
:PROPERTIES:
:ID:       2AFj7i-jpwF4M41q6JXSqm9o@stanza.co
:LOCATION: Qdoba Q'Monday
:STATUS:   CONFIRMED
:END:

Timber Rattlers vs. Kernels Purchase any Qdoba entree on any Monday game at any Appleton, Neenah, or Oshkosh location and receive a free Monday game ticket.

Follow on MiLB First Pitch  https //stza.co/+vNrH-1u

Shop  https //stza.co/+vNrH-2P

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Timber Rattlers vs. Kernels
END:VALARM
DTSTART:20180703T000500Z
DTEND:20180703T030500Z
UID:2AFj7i-jpwF4M41q6JXSqm9o@stanza.co
SUMMARY:Timber Rattlers vs. Kernels
DESCRIPTION:Purchase any Qdoba entree on any Monday game at any Appleton, Neenah, or Oshkosh location and receive a free Monday game ticket.\n\nFollow on MiLB First Pitch: https://stza.co/+vNrH-1u\n\nShop: https://stza.co/+vNrH-2P\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Qdoba Q'Monday
STATUS:CONFIRMED
CREATED:20180213T144607Z
LAST-MODIFIED:20180213T144607Z
TRANSP:OPAQUE
END:VEVENT
* Timber Rattlers vs. Kernels
<2018-07-03 Tue 18:35-21:35>
:PROPERTIES:
:ID:       5i-HhIEAV7eVLs1VJwFHv7Fy@stanza.co
:LOCATION: Baker Tilly Business Person Special
:STATUS:   CONFIRMED
:END:

Timber Rattlers vs. Kernels Business Persons that present business card, Military Personnel with ID and seniors with ID 55 & older receive a box seat ticket. Beverage & brat or hot dog for just $14.50.

Follow on MiLB First Pitch  https //stza.co/+vNrJ-9

Shop  https //stza.co/+vNrJ-2z

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Timber Rattlers vs. Kernels
END:VALARM
DTSTART:20180703T233500Z
DTEND:20180704T023500Z
UID:5i-HhIEAV7eVLs1VJwFHv7Fy@stanza.co
SUMMARY:Timber Rattlers vs. Kernels
DESCRIPTION:Business Persons that present business card, Military Personnel with ID and seniors with ID 55 & older receive a box seat ticket. Beverage & brat or hot dog for just $14.50.\n\nFollow on MiLB First Pitch: https://stza.co/+vNrJ-9\n\nShop: https://stza.co/+vNrJ-2z\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Baker Tilly Business Person Special
STATUS:CONFIRMED
CREATED:20180213T144607Z
LAST-MODIFIED:20180213T144607Z
TRANSP:OPAQUE
END:VEVENT
* Timber Rattlers @ Kernels
<2018-07-04 Wed 17:05-20:05>
:PROPERTIES:
:ID:       EYOnFDjKPME91siwBbRFMLjo@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Timber Rattlers @ Kernels Timber Rattlers @ Kernels

Buy tickets here  https //stza.co/~vNpG

Follow on MiLB First Pitch  https //stza.co/+vNpG-3p

Shop  https //stza.co/+vNpG-3j

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Timber Rattlers @ Kernels
END:VALARM
DTSTART:20180704T220500Z
DTEND:20180705T010500Z
UID:EYOnFDjKPME91siwBbRFMLjo@stanza.co
SUMMARY:Timber Rattlers @ Kernels
DESCRIPTION:Timber Rattlers @ Kernels\n\nBuy tickets here: https://stza.co/~vNpG\n\nFollow on MiLB First Pitch: https://stza.co/+vNpG-3p\n\nShop: https://stza.co/+vNpG-3j\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144607Z
LAST-MODIFIED:20180213T144607Z
TRANSP:OPAQUE
END:VEVENT
* Timber Rattlers @ Kernels
<2018-07-05 Thu 18:35-21:35>
:PROPERTIES:
:ID:       j7IZpry03H-WD5DiiavLg1w2@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Timber Rattlers @ Kernels Timber Rattlers @ Kernels

Buy tickets here  https //stza.co/~vNpH

Follow on MiLB First Pitch  https //stza.co/+vNpH-37

Shop  https //stza.co/+vNpH-2$

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Timber Rattlers @ Kernels
END:VALARM
DTSTART:20180705T233500Z
DTEND:20180706T023500Z
UID:j7IZpry03H-WD5DiiavLg1w2@stanza.co
SUMMARY:Timber Rattlers @ Kernels
DESCRIPTION:Timber Rattlers @ Kernels\n\nBuy tickets here: https://stza.co/~vNpH\n\nFollow on MiLB First Pitch: https://stza.co/+vNpH-37\n\nShop: https://stza.co/+vNpH-2$\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144607Z
LAST-MODIFIED:20180213T144607Z
TRANSP:OPAQUE
END:VEVENT
* Timber Rattlers vs. Chiefs
<2018-07-06 Fri 19:05-22:05>
:PROPERTIES:
:ID:       gpYDqvcYG2zHTRVw26ZnItBt@stanza.co
:LOCATION: Margaritaville Night
:STATUS:   CONFIRMED
:END:

Timber Rattlers vs. Chiefs Join us as we turn the stadium into Margaritaville for the night! If you call yourself a true Parrothead then we have just the deal for you. The Parrot Porch Special! This not only includes a special seat on the Potawatomi Party Deck, turned Parrot Porch for the night, but also includes a very special Margaritaville themed t-shirt! Also, you do not want to miss our post-game Jimmy Buffett cover band, The Boat Drunks! Stay after for post-game Kids Run the Bases and Fireworks.

Follow on MiLB First Pitch  https //stza.co/+vNrM-3_

Shop  https //stza.co/+vNrM-38

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Timber Rattlers vs. Chiefs
END:VALARM
DTSTART:20180707T000500Z
DTEND:20180707T030500Z
UID:gpYDqvcYG2zHTRVw26ZnItBt@stanza.co
SUMMARY:Timber Rattlers vs. Chiefs
DESCRIPTION:Join us as we turn the stadium into Margaritaville for the night! If you call yourself a true Parrothead then we have just the deal for you. The Parrot Porch Special! This not only includes a special seat on the Potawatomi Party Deck, turned Parrot Porch for the night, but also includes a very special Margaritaville themed t-shirt! Also, you do not want to miss our post-game Jimmy Buffett cover band, The Boat Drunks! Stay after for post-game Kids Run the Bases and Fireworks.\n\nFollow on MiLB First Pitch: https://stza.co/+vNrM-3_\n\nShop: https://stza.co/+vNrM-38\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Margaritaville Night
STATUS:CONFIRMED
CREATED:20180213T144607Z
LAST-MODIFIED:20180213T144607Z
TRANSP:OPAQUE
END:VEVENT
* Timber Rattlers vs. Chiefs
<2018-07-07 Sat 18:35-21:35>
:PROPERTIES:
:ID:       sSiVZ5zFndoIp_IQJZtpAEvW@stanza.co
:LOCATION: Princess Night with VIP Tea Party
:STATUS:   CONFIRMED
:END:

Timber Rattlers vs. Chiefs Bring your princesses and princes out to meet Elsa, Ana, Moana, Ariel and Cinderella. The first 500 kids will receive a tiara as they enter the gates! Be part of the pre-game VIP Tea Party where you get a special meet and greet with the princesses upstairs in the The Fox Club. There will be princess themed snacks and beverages available along with plenty of picture taking opportunities! VIP Tea Party Tickets are limited availability, buy your tickets now!

Follow on MiLB First Pitch  https //stza.co/+vNrN-2Z

Shop  https //stza.co/+vNrN-3x

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Timber Rattlers vs. Chiefs
END:VALARM
DTSTART:20180707T233500Z
DTEND:20180708T023500Z
UID:sSiVZ5zFndoIp_IQJZtpAEvW@stanza.co
SUMMARY:Timber Rattlers vs. Chiefs
DESCRIPTION:Bring your princesses and princes out to meet Elsa, Ana, Moana, Ariel and Cinderella. The first 500 kids will receive a tiara as they enter the gates! Be part of the pre-game VIP Tea Party where you get a special meet and greet with the princesses upstairs in the The Fox Club. There will be princess themed snacks and beverages available along with plenty of picture taking opportunities! VIP Tea Party Tickets are limited availability, buy your tickets now!\n\nFollow on MiLB First Pitch: https://stza.co/+vNrN-2Z\n\nShop: https://stza.co/+vNrN-3x\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Princess Night with VIP Tea Party
STATUS:CONFIRMED
CREATED:20180213T144607Z
LAST-MODIFIED:20180213T144607Z
TRANSP:OPAQUE
END:VEVENT
* Timber Rattlers vs. Chiefs
<2018-07-08 Sun 13:05-16:05>
:PROPERTIES:
:ID:       XBCPMKRgQQrjGIvNX_uF0WVG@stanza.co
:LOCATION: Brewers Sunday
:STATUS:   CONFIRMED
:END:

Timber Rattlers vs. Chiefs Play catch on the field pre-game. Player autographs after the game. Brewers themed jerseys worn on field. Brewers Fan Makeover.

Follow on MiLB First Pitch  https //stza.co/+vNrQ-3M

Shop  https //stza.co/+vNrQ-3K

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Timber Rattlers vs. Chiefs
END:VALARM
DTSTART:20180708T180500Z
DTEND:20180708T210500Z
UID:XBCPMKRgQQrjGIvNX_uF0WVG@stanza.co
SUMMARY:Timber Rattlers vs. Chiefs
DESCRIPTION:Play catch on the field pre-game. Player autographs after the game. Brewers themed jerseys worn on field. Brewers Fan Makeover.\n\nFollow on MiLB First Pitch: https://stza.co/+vNrQ-3M\n\nShop: https://stza.co/+vNrQ-3K\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Brewers Sunday
STATUS:CONFIRMED
CREATED:20180213T144607Z
LAST-MODIFIED:20180213T144607Z
TRANSP:OPAQUE
END:VEVENT
* Timber Rattlers vs. Chiefs
<2018-07-09 Mon 12:05-15:05>
:PROPERTIES:
:ID:       Zy79E3jNT3b7i9cIAjoNXLzQ@stanza.co
:LOCATION: Qdoba Q'Monday
:STATUS:   CONFIRMED
:END:

Timber Rattlers vs. Chiefs Purchase any Qdoba entree on any Monday game at any Appleton, Neenah, or Oshkosh location and receive a free Monday game ticket.

Follow on MiLB First Pitch  https //stza.co/+vNrR-36

Shop  https //stza.co/+vNrR-2T

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Timber Rattlers vs. Chiefs
END:VALARM
DTSTART:20180709T170500Z
DTEND:20180709T200500Z
UID:Zy79E3jNT3b7i9cIAjoNXLzQ@stanza.co
SUMMARY:Timber Rattlers vs. Chiefs
DESCRIPTION:Purchase any Qdoba entree on any Monday game at any Appleton, Neenah, or Oshkosh location and receive a free Monday game ticket.\n\nFollow on MiLB First Pitch: https://stza.co/+vNrR-36\n\nShop: https://stza.co/+vNrR-2T\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Qdoba Q'Monday
STATUS:CONFIRMED
CREATED:20180213T144607Z
LAST-MODIFIED:20180213T144607Z
TRANSP:OPAQUE
END:VEVENT
* Timber Rattlers @ Whitecaps
<2018-07-11 Wed 18:05-21:05>
:PROPERTIES:
:ID:       Wu7TWDvRzA5rRdu5V9HaYWZw@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Timber Rattlers @ Whitecaps Timber Rattlers @ Whitecaps

Follow on MiLB First Pitch  https //stza.co/+vNqq-n

Shop  https //stza.co/+vNqq-2j

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Timber Rattlers @ Whitecaps
END:VALARM
DTSTART:20180711T230500Z
DTEND:20180712T020500Z
UID:Wu7TWDvRzA5rRdu5V9HaYWZw@stanza.co
SUMMARY:Timber Rattlers @ Whitecaps
DESCRIPTION:Timber Rattlers @ Whitecaps\n\nFollow on MiLB First Pitch: https://stza.co/+vNqq-n\n\nShop: https://stza.co/+vNqq-2j\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144607Z
LAST-MODIFIED:20180213T144607Z
TRANSP:OPAQUE
END:VEVENT
* Timber Rattlers @ Whitecaps
<2018-07-12 Thu 18:05-21:05>
:PROPERTIES:
:ID:       z0TRN8hMWUxkYbNqfbvMyJ0L@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Timber Rattlers @ Whitecaps Timber Rattlers @ Whitecaps

Follow on MiLB First Pitch  https //stza.co/+vNqr-3D

Shop  https //stza.co/+vNqr-2Q

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Timber Rattlers @ Whitecaps
END:VALARM
DTSTART:20180712T230500Z
DTEND:20180713T020500Z
UID:z0TRN8hMWUxkYbNqfbvMyJ0L@stanza.co
SUMMARY:Timber Rattlers @ Whitecaps
DESCRIPTION:Timber Rattlers @ Whitecaps\n\nFollow on MiLB First Pitch: https://stza.co/+vNqr-3D\n\nShop: https://stza.co/+vNqr-2Q\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144607Z
LAST-MODIFIED:20180213T144607Z
TRANSP:OPAQUE
END:VEVENT
* Timber Rattlers @ Whitecaps
<2018-07-13 Fri 18:05-21:05>
:PROPERTIES:
:ID:       PV-ePPtRxA4u7-O-bAswR_N2@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Timber Rattlers @ Whitecaps Timber Rattlers @ Whitecaps

Follow on MiLB First Pitch  https //stza.co/+vNqs-O

Shop  https //stza.co/+vNqs-1x

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Timber Rattlers @ Whitecaps
END:VALARM
DTSTART:20180713T230500Z
DTEND:20180714T020500Z
UID:PV-ePPtRxA4u7-O-bAswR_N2@stanza.co
SUMMARY:Timber Rattlers @ Whitecaps
DESCRIPTION:Timber Rattlers @ Whitecaps\n\nFollow on MiLB First Pitch: https://stza.co/+vNqs-O\n\nShop: https://stza.co/+vNqs-1x\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144607Z
LAST-MODIFIED:20180213T144607Z
TRANSP:OPAQUE
END:VEVENT
* Timber Rattlers @ Cubs
<2018-07-14 Sat 18:05-21:05>
:PROPERTIES:
:ID:       xWR79eFFY1bqC3SYmcTcersV@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Timber Rattlers @ Cubs Timber Rattlers @ Cubs

Follow on MiLB First Pitch  https //stza.co/+vNqn-i

Shop  https //stza.co/+vNqn-3q

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Timber Rattlers @ Cubs
END:VALARM
DTSTART:20180714T230500Z
DTEND:20180715T020500Z
UID:xWR79eFFY1bqC3SYmcTcersV@stanza.co
SUMMARY:Timber Rattlers @ Cubs
DESCRIPTION:Timber Rattlers @ Cubs\n\nFollow on MiLB First Pitch: https://stza.co/+vNqn-i\n\nShop: https://stza.co/+vNqn-3q\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144607Z
LAST-MODIFIED:20180213T144607Z
TRANSP:OPAQUE
END:VEVENT
* Timber Rattlers @ Cubs
<2018-07-15 Sun 13:05-16:05>
:PROPERTIES:
:ID:       BWqL-OsYZBpzTcfkvL0E2Des@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Timber Rattlers @ Cubs Timber Rattlers @ Cubs

Follow on MiLB First Pitch  https //stza.co/+vNqo-1E

Shop  https //stza.co/+vNqo-2b

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Timber Rattlers @ Cubs
END:VALARM
DTSTART:20180715T180500Z
DTEND:20180715T210500Z
UID:BWqL-OsYZBpzTcfkvL0E2Des@stanza.co
SUMMARY:Timber Rattlers @ Cubs
DESCRIPTION:Timber Rattlers @ Cubs\n\nFollow on MiLB First Pitch: https://stza.co/+vNqo-1E\n\nShop: https://stza.co/+vNqo-2b\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144607Z
LAST-MODIFIED:20180213T144607Z
TRANSP:OPAQUE
END:VEVENT
* Timber Rattlers @ Cubs
<2018-07-16 Mon 12:05-15:05>
:PROPERTIES:
:ID:       yeXi1zaCepr7pLeYwq2Ai0JI@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Timber Rattlers @ Cubs Timber Rattlers @ Cubs

Follow on MiLB First Pitch  https //stza.co/+vNqp-1e

Shop  https //stza.co/+vNqp-2H

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Timber Rattlers @ Cubs
END:VALARM
DTSTART:20180716T170500Z
DTEND:20180716T200500Z
UID:yeXi1zaCepr7pLeYwq2Ai0JI@stanza.co
SUMMARY:Timber Rattlers @ Cubs
DESCRIPTION:Timber Rattlers @ Cubs\n\nFollow on MiLB First Pitch: https://stza.co/+vNqp-1e\n\nShop: https://stza.co/+vNqp-2H\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144607Z
LAST-MODIFIED:20180213T144607Z
TRANSP:OPAQUE
END:VEVENT
* Timber Rattlers vs. Dragons
<2018-07-18 Wed 19:05-22:05>
:PROPERTIES:
:ID:       Db9to1zcBXW0LwRjM7pEyK17@stanza.co
:LOCATION: Bang For Your Buck
:STATUS:   CONFIRMED
:END:

Timber Rattlers vs. Dragons Enjoy Cher-Make hotdogs, sodas, and domestic beer for $1. A lucky fan will go home with two charter airfare tickets courtesy of AAA Travel and Funjet Vacations.

Follow on MiLB First Pitch  https //stza.co/+vNrT-3J

Shop  https //stza.co/+vNrT-3t

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Timber Rattlers vs. Dragons
END:VALARM
DTSTART:20180719T000500Z
DTEND:20180719T030500Z
UID:Db9to1zcBXW0LwRjM7pEyK17@stanza.co
SUMMARY:Timber Rattlers vs. Dragons
DESCRIPTION:Enjoy Cher-Make hotdogs, sodas, and domestic beer for $1. A lucky fan will go home with two charter airfare tickets courtesy of AAA Travel and Funjet Vacations.\n\nFollow on MiLB First Pitch: https://stza.co/+vNrT-3J\n\nShop: https://stza.co/+vNrT-3t\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Bang For Your Buck
STATUS:CONFIRMED
CREATED:20180213T144607Z
LAST-MODIFIED:20180213T144607Z
TRANSP:OPAQUE
END:VEVENT
* Timber Rattlers vs. Dragons
<2018-07-19 Thu 19:05-22:05>
:PROPERTIES:
:ID:       SiVbzuC_7oiC_adGQV3DI9uz@stanza.co
:LOCATION: Craft Brews and Brats
:STATUS:   CONFIRMED
:END:

Timber Rattlers vs. Dragons Enjoy 12 oz craft beer and Cher-Make Brats for only $2. Present any Thursday game ticket at Wissota Taphouse for a free beer.

Follow on MiLB First Pitch  https //stza.co/+vNrW-d

Shop  https //stza.co/+vNrW-l

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Timber Rattlers vs. Dragons
END:VALARM
DTSTART:20180720T000500Z
DTEND:20180720T030500Z
UID:SiVbzuC_7oiC_adGQV3DI9uz@stanza.co
SUMMARY:Timber Rattlers vs. Dragons
DESCRIPTION:Enjoy 12 oz craft beer and Cher-Make Brats for only $2. Present any Thursday game ticket at Wissota Taphouse for a free beer.\n\nFollow on MiLB First Pitch: https://stza.co/+vNrW-d\n\nShop: https://stza.co/+vNrW-l\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Craft Brews and Brats
STATUS:CONFIRMED
CREATED:20180213T144607Z
LAST-MODIFIED:20180213T144607Z
TRANSP:OPAQUE
END:VEVENT
* Timber Rattlers vs. Dragons
<2018-07-20 Fri 19:05-22:05>
:PROPERTIES:
:ID:       xkLv5T0c_hRDtnQ-YsAkW-U1@stanza.co
:LOCATION: Superhero Weekend with guest appearance
:STATUS:   CONFIRMED
:END:

Timber Rattlers vs. Dragons Superhero themed giveaway. CPR Night. Stick around for Kids Run the Bases and Fireworks!

Follow on MiLB First Pitch  https //stza.co/+vNrX-B

Shop  https //stza.co/+vNrX-i

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Timber Rattlers vs. Dragons
END:VALARM
DTSTART:20180721T000500Z
DTEND:20180721T030500Z
UID:xkLv5T0c_hRDtnQ-YsAkW-U1@stanza.co
SUMMARY:Timber Rattlers vs. Dragons
DESCRIPTION:Superhero themed giveaway. CPR Night. Stick around for Kids Run the Bases and Fireworks!\n\nFollow on MiLB First Pitch: https://stza.co/+vNrX-B\n\nShop: https://stza.co/+vNrX-i\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Superhero Weekend with guest appearance
STATUS:CONFIRMED
CREATED:20180213T144607Z
LAST-MODIFIED:20180213T144607Z
TRANSP:OPAQUE
END:VEVENT
* Timber Rattlers vs. Hot Rods
<2018-07-21 Sat 18:35-21:35>
:PROPERTIES:
:ID:       ydklc7IY7ObEkVrsSiPS3Dzm@stanza.co
:LOCATION: Superhero Weekend with Captain America & The Incredible Hulk
:STATUS:   CONFIRMED
:END:

Timber Rattlers vs. Hot Rods Captain America and The Incredible Hulk will be at the ballpark! Touch-A-Truck. Stick around for Kids Run the Bases and Fireworks!

Follow on MiLB First Pitch  https //stza.co/+vNr_-3f

Shop  https //stza.co/+vNr_-1E

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Timber Rattlers vs. Hot Rods
END:VALARM
DTSTART:20180721T233500Z
DTEND:20180722T023500Z
UID:ydklc7IY7ObEkVrsSiPS3Dzm@stanza.co
SUMMARY:Timber Rattlers vs. Hot Rods
DESCRIPTION:Captain America and The Incredible Hulk will be at the ballpark! Touch-A-Truck. Stick around for Kids Run the Bases and Fireworks!\n\nFollow on MiLB First Pitch: https://stza.co/+vNr_-3f\n\nShop: https://stza.co/+vNr_-1E\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Superhero Weekend with Captain America & The Incredible Hulk
STATUS:CONFIRMED
CREATED:20180213T144607Z
LAST-MODIFIED:20180213T144607Z
TRANSP:OPAQUE
END:VEVENT
* Timber Rattlers vs. Hot Rods
<2018-07-22 Sun 13:05-16:05>
:PROPERTIES:
:ID:       _U1dY_-Kuuef8oJpJv5QVsBC@stanza.co
:LOCATION: Brewers Sunday
:STATUS:   CONFIRMED
:END:

Timber Rattlers vs. Hot Rods Play catch on the field pre-game. Player autographs after the game. Brewers themed jerseys worn on field. Brewers Fan Makeover.

First 1,000 fans through the gates to receive a Superhero Fang Bobblehead.

Follow on MiLB First Pitch  https //stza.co/+vNs0-1V

Shop  https //stza.co/+vNs0-3f

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Timber Rattlers vs. Hot Rods
END:VALARM
DTSTART:20180722T180500Z
DTEND:20180722T210500Z
UID:_U1dY_-Kuuef8oJpJv5QVsBC@stanza.co
SUMMARY:Timber Rattlers vs. Hot Rods
DESCRIPTION:Play catch on the field pre-game. Player autographs after the game. Brewers themed jerseys worn on field. Brewers Fan Makeover.\n\nFirst 1,000 fans through the gates to receive a Superhero Fang Bobblehead.\n\nFollow on MiLB First Pitch: https://stza.co/+vNs0-1V\n\nShop: https://stza.co/+vNs0-3f\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Brewers Sunday
STATUS:CONFIRMED
CREATED:20180213T144607Z
LAST-MODIFIED:20180213T144607Z
TRANSP:OPAQUE
END:VEVENT
* Timber Rattlers vs. Hot Rods
<2018-07-23 Mon 12:05-15:05>
:PROPERTIES:
:ID:       BHqDjp_pPfI9hUAO0l5Kl3sj@stanza.co
:LOCATION: Qdoba Q'Monday
:STATUS:   CONFIRMED
:END:

Timber Rattlers vs. Hot Rods Purchase any Qdoba entree on any Monday game at any Appleton, Neenah, or Oshkosh location and receive a free Monday game ticket.

Follow on MiLB First Pitch  https //stza.co/+vNs1-2D

Shop  https //stza.co/+vNs1-11

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Timber Rattlers vs. Hot Rods
END:VALARM
DTSTART:20180723T170500Z
DTEND:20180723T200500Z
UID:BHqDjp_pPfI9hUAO0l5Kl3sj@stanza.co
SUMMARY:Timber Rattlers vs. Hot Rods
DESCRIPTION:Purchase any Qdoba entree on any Monday game at any Appleton, Neenah, or Oshkosh location and receive a free Monday game ticket.\n\nFollow on MiLB First Pitch: https://stza.co/+vNs1-2D\n\nShop: https://stza.co/+vNs1-11\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Qdoba Q'Monday
STATUS:CONFIRMED
CREATED:20180213T144607Z
LAST-MODIFIED:20180213T144607Z
TRANSP:OPAQUE
END:VEVENT
* Timber Rattlers @ Chiefs
<2018-07-25 Wed 19:00-22:00>
:PROPERTIES:
:ID:       8PZqMPrtmGf9lR32mmCLDpoD@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Timber Rattlers @ Chiefs Timber Rattlers @ Chiefs

Follow on MiLB First Pitch  https //stza.co/+xBDD-2$

Shop  https //stza.co/+xBDD-2D

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Timber Rattlers @ Chiefs
END:VALARM
DTSTART:20180726T000000Z
DTEND:20180726T030000Z
UID:8PZqMPrtmGf9lR32mmCLDpoD@stanza.co
SUMMARY:Timber Rattlers @ Chiefs
DESCRIPTION:Timber Rattlers @ Chiefs\n\nFollow on MiLB First Pitch: https://stza.co/+xBDD-2$\n\nShop: https://stza.co/+xBDD-2D\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144607Z
LAST-MODIFIED:20180213T144607Z
TRANSP:OPAQUE
END:VEVENT
* Timber Rattlers @ Chiefs
<2018-07-26 Thu 19:00-22:00>
:PROPERTIES:
:ID:       oprQaQDZQixaXladMT4l5xgx@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Timber Rattlers @ Chiefs Timber Rattlers @ Chiefs

Follow on MiLB First Pitch  https //stza.co/+xBDI-35

Shop  https //stza.co/+xBDI-3a

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Timber Rattlers @ Chiefs
END:VALARM
DTSTART:20180727T000000Z
DTEND:20180727T030000Z
UID:oprQaQDZQixaXladMT4l5xgx@stanza.co
SUMMARY:Timber Rattlers @ Chiefs
DESCRIPTION:Timber Rattlers @ Chiefs\n\nFollow on MiLB First Pitch: https://stza.co/+xBDI-35\n\nShop: https://stza.co/+xBDI-3a\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144607Z
LAST-MODIFIED:20180213T144607Z
TRANSP:OPAQUE
END:VEVENT
* Timber Rattlers @ Chiefs
<2018-07-27 Fri 19:00-22:00>
:PROPERTIES:
:ID:       eTwm86SGhF3PERowH6mKa_1B@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Timber Rattlers @ Chiefs Timber Rattlers @ Chiefs

Follow on MiLB First Pitch  https //stza.co/+xBDN-2$

Shop  https //stza.co/+xBDN-t

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Timber Rattlers @ Chiefs
END:VALARM
DTSTART:20180728T000000Z
DTEND:20180728T030000Z
UID:eTwm86SGhF3PERowH6mKa_1B@stanza.co
SUMMARY:Timber Rattlers @ Chiefs
DESCRIPTION:Timber Rattlers @ Chiefs\n\nFollow on MiLB First Pitch: https://stza.co/+xBDN-2$\n\nShop: https://stza.co/+xBDN-t\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144607Z
LAST-MODIFIED:20180213T144607Z
TRANSP:OPAQUE
END:VEVENT
* Timber Rattlers vs. Cougars
<2018-07-28 Sat 18:35-21:35>
:PROPERTIES:
:ID:       p_u2DTnxwqwksXvqBr9B1IUb@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Timber Rattlers vs. Cougars Timber Rattlers vs. Cougars

Follow on MiLB First Pitch  https //stza.co/+vNs3-1p

Shop  https //stza.co/+vNs3-2P

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Timber Rattlers vs. Cougars
END:VALARM
DTSTART:20180728T233500Z
DTEND:20180729T023500Z
UID:p_u2DTnxwqwksXvqBr9B1IUb@stanza.co
SUMMARY:Timber Rattlers vs. Cougars
DESCRIPTION:Timber Rattlers vs. Cougars\n\nFollow on MiLB First Pitch: https://stza.co/+vNs3-1p\n\nShop: https://stza.co/+vNs3-2P\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144607Z
LAST-MODIFIED:20180213T144607Z
TRANSP:OPAQUE
END:VEVENT
* Timber Rattlers vs. Cougars
<2018-07-29 Sun 13:05-16:05>
:PROPERTIES:
:ID:       M4XhrVZdrAO48GaU8y_XPoSJ@stanza.co
:LOCATION: Brewers Sunday
:STATUS:   CONFIRMED
:END:

Timber Rattlers vs. Cougars Play catch on the field pre-game. Player autographs after the game. Brewers themed jerseys worn on field. Brewers Fan Makeover.

Follow on MiLB First Pitch  https //stza.co/+vNs5-3k

Shop  https //stza.co/+vNs5-f

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Timber Rattlers vs. Cougars
END:VALARM
DTSTART:20180729T180500Z
DTEND:20180729T210500Z
UID:M4XhrVZdrAO48GaU8y_XPoSJ@stanza.co
SUMMARY:Timber Rattlers vs. Cougars
DESCRIPTION:Play catch on the field pre-game. Player autographs after the game. Brewers themed jerseys worn on field. Brewers Fan Makeover.\n\nFollow on MiLB First Pitch: https://stza.co/+vNs5-3k\n\nShop: https://stza.co/+vNs5-f\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Brewers Sunday
STATUS:CONFIRMED
CREATED:20180213T144607Z
LAST-MODIFIED:20180213T144607Z
TRANSP:OPAQUE
END:VEVENT
* Timber Rattlers vs. Cougars
<2018-07-30 Mon 19:05-22:05>
:PROPERTIES:
:ID:       c4wuVuy-h4GbfjDtzT55nQx9@stanza.co
:LOCATION: Qdoba Q'Monday
:STATUS:   CONFIRMED
:END:

Timber Rattlers vs. Cougars Purchase any Qdoba entree on any Monday game at any Appleton, Neenah, or Oshkosh location and receive a free Monday game ticket.

Follow on MiLB First Pitch  https //stza.co/+vNs8-1c

Shop  https //stza.co/+vNs8-3l

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Timber Rattlers vs. Cougars
END:VALARM
DTSTART:20180731T000500Z
DTEND:20180731T030500Z
UID:c4wuVuy-h4GbfjDtzT55nQx9@stanza.co
SUMMARY:Timber Rattlers vs. Cougars
DESCRIPTION:Purchase any Qdoba entree on any Monday game at any Appleton, Neenah, or Oshkosh location and receive a free Monday game ticket.\n\nFollow on MiLB First Pitch: https://stza.co/+vNs8-1c\n\nShop: https://stza.co/+vNs8-3l\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Qdoba Q'Monday
STATUS:CONFIRMED
CREATED:20180213T144607Z
LAST-MODIFIED:20180213T144607Z
TRANSP:OPAQUE
END:VEVENT
* Timber Rattlers vs. Cougars
<2018-07-31 Tue 19:05-22:05>
:PROPERTIES:
:ID:       _L2IwciPdapOCwTcEUyGY3b_@stanza.co
:LOCATION: Baker Tilly Business Person Special
:STATUS:   CONFIRMED
:END:

Timber Rattlers vs. Cougars Business Persons that present business card, Military Personnel with ID and seniors with ID 55 & older receive a box seat ticket. Beverage & brat or hot dog for just $14.50.

Follow on MiLB First Pitch  https //stza.co/+vNsa-3s

Shop  https //stza.co/+vNsa-1Q

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Timber Rattlers vs. Cougars
END:VALARM
DTSTART:20180801T000500Z
DTEND:20180801T030500Z
UID:_L2IwciPdapOCwTcEUyGY3b_@stanza.co
SUMMARY:Timber Rattlers vs. Cougars
DESCRIPTION:Business Persons that present business card, Military Personnel with ID and seniors with ID 55 & older receive a box seat ticket. Beverage & brat or hot dog for just $14.50.\n\nFollow on MiLB First Pitch: https://stza.co/+vNsa-3s\n\nShop: https://stza.co/+vNsa-1Q\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Baker Tilly Business Person Special
STATUS:CONFIRMED
CREATED:20180213T144607Z
LAST-MODIFIED:20180213T144607Z
TRANSP:OPAQUE
END:VEVENT
* Timber Rattlers vs. Bees
<2018-08-01 Wed 19:05-22:05>
:PROPERTIES:
:ID:       WHIq2SMxcgZPIQZmXPSD-ndc@stanza.co
:LOCATION: Bang For Your Buck
:STATUS:   CONFIRMED
:END:

Timber Rattlers vs. Bees Enjoy Cher-Make hotdogs, sodas, and domestic beer for $1. A lucky fan will go home with two charter airfare tickets courtesy of AAA Travel and Funjet Vacations.

Follow on MiLB First Pitch  https //stza.co/+vNsb-O

Shop  https //stza.co/+vNsb-3M

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Timber Rattlers vs. Bees
END:VALARM
DTSTART:20180802T000500Z
DTEND:20180802T030500Z
UID:WHIq2SMxcgZPIQZmXPSD-ndc@stanza.co
SUMMARY:Timber Rattlers vs. Bees
DESCRIPTION:Enjoy Cher-Make hotdogs, sodas, and domestic beer for $1. A lucky fan will go home with two charter airfare tickets courtesy of AAA Travel and Funjet Vacations.\n\nFollow on MiLB First Pitch: https://stza.co/+vNsb-O\n\nShop: https://stza.co/+vNsb-3M\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Bang For Your Buck
STATUS:CONFIRMED
CREATED:20180213T144607Z
LAST-MODIFIED:20180213T144607Z
TRANSP:OPAQUE
END:VEVENT
* Timber Rattlers vs. Bees
<2018-08-02 Thu 19:05-22:05>
:PROPERTIES:
:ID:       bHtjX8iWL39E_ihxXV7Sewu_@stanza.co
:LOCATION: Craft Brews and Brats
:STATUS:   CONFIRMED
:END:

Timber Rattlers vs. Bees Enjoy 12 oz craft beer and Cher-Make Brats for only $2. Present any Thursday game ticket at Wissota Taphouse for a free beer.

Follow on MiLB First Pitch  https //stza.co/+vNse-2X

Shop  https //stza.co/+vNse-2H

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Timber Rattlers vs. Bees
END:VALARM
DTSTART:20180803T000500Z
DTEND:20180803T030500Z
UID:bHtjX8iWL39E_ihxXV7Sewu_@stanza.co
SUMMARY:Timber Rattlers vs. Bees
DESCRIPTION:Enjoy 12 oz craft beer and Cher-Make Brats for only $2. Present any Thursday game ticket at Wissota Taphouse for a free beer.\n\nFollow on MiLB First Pitch: https://stza.co/+vNse-2X\n\nShop: https://stza.co/+vNse-2H\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Craft Brews and Brats
STATUS:CONFIRMED
CREATED:20180213T144607Z
LAST-MODIFIED:20180213T144607Z
TRANSP:OPAQUE
END:VEVENT
* Timber Rattlers vs. Bees
<2018-08-03 Fri 19:05-22:05>
:PROPERTIES:
:ID:       nz-pvnr8k6jUra8AkQixVYxj@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Timber Rattlers vs. Bees Timber Rattlers vs. Bees

Follow on MiLB First Pitch  https //stza.co/+vNsg-2y

Shop  https //stza.co/+vNsg-K

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Timber Rattlers vs. Bees
END:VALARM
DTSTART:20180804T000500Z
DTEND:20180804T030500Z
UID:nz-pvnr8k6jUra8AkQixVYxj@stanza.co
SUMMARY:Timber Rattlers vs. Bees
DESCRIPTION:Timber Rattlers vs. Bees\n\nFollow on MiLB First Pitch: https://stza.co/+vNsg-2y\n\nShop: https://stza.co/+vNsg-K\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144607Z
LAST-MODIFIED:20180213T144607Z
TRANSP:OPAQUE
END:VEVENT
* Timber Rattlers @ LumberKings
<2018-08-04 Sat 18:30-21:30>
:PROPERTIES:
:ID:       5_ZeIQz7OUd6PSwonnZsHAUA@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Timber Rattlers @ LumberKings Timber Rattlers @ LumberKings

Follow on MiLB First Pitch  https //stza.co/+vNpM-2j

Shop  https //stza.co/+vNpM-3x

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Timber Rattlers @ LumberKings
END:VALARM
DTSTART:20180804T233000Z
DTEND:20180805T023000Z
UID:5_ZeIQz7OUd6PSwonnZsHAUA@stanza.co
SUMMARY:Timber Rattlers @ LumberKings
DESCRIPTION:Timber Rattlers @ LumberKings\n\nFollow on MiLB First Pitch: https://stza.co/+vNpM-2j\n\nShop: https://stza.co/+vNpM-3x\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144607Z
LAST-MODIFIED:20180213T144607Z
TRANSP:OPAQUE
END:VEVENT
* Timber Rattlers @ LumberKings
<2018-08-05 Sun 14:00-17:00>
:PROPERTIES:
:ID:       ybipikcyf9iE3YuL2gN5A5k8@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Timber Rattlers @ LumberKings Timber Rattlers @ LumberKings

Follow on MiLB First Pitch  https //stza.co/+vNpN-1T

Shop  https //stza.co/+vNpN-i

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Timber Rattlers @ LumberKings
END:VALARM
DTSTART:20180805T190000Z
DTEND:20180805T220000Z
UID:ybipikcyf9iE3YuL2gN5A5k8@stanza.co
SUMMARY:Timber Rattlers @ LumberKings
DESCRIPTION:Timber Rattlers @ LumberKings\n\nFollow on MiLB First Pitch: https://stza.co/+vNpN-1T\n\nShop: https://stza.co/+vNpN-i\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144607Z
LAST-MODIFIED:20180213T144607Z
TRANSP:OPAQUE
END:VEVENT
* Timber Rattlers @ LumberKings
<2018-08-06 Mon 18:30-21:30>
:PROPERTIES:
:ID:       8ZqZ53sW8UHnWPd4Fkk-ykLu@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Timber Rattlers @ LumberKings Timber Rattlers @ LumberKings

Follow on MiLB First Pitch  https //stza.co/+vNpO-8

Shop  https //stza.co/+vNpO-W

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Timber Rattlers @ LumberKings
END:VALARM
DTSTART:20180806T233000Z
DTEND:20180807T023000Z
UID:8ZqZ53sW8UHnWPd4Fkk-ykLu@stanza.co
SUMMARY:Timber Rattlers @ LumberKings
DESCRIPTION:Timber Rattlers @ LumberKings\n\nFollow on MiLB First Pitch: https://stza.co/+vNpO-8\n\nShop: https://stza.co/+vNpO-W\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144607Z
LAST-MODIFIED:20180213T144607Z
TRANSP:OPAQUE
END:VEVENT
* Timber Rattlers vs. Bees
<2018-08-08 Wed 19:05-22:05>
:PROPERTIES:
:ID:       Z0OwXwIFPkNUrBNUiMQmhMZk@stanza.co
:LOCATION: Bang For Your Buck
:STATUS:   CONFIRMED
:END:

Timber Rattlers vs. Bees Enjoy Cher-Make hotdogs, sodas, and domestic beer for $1. A lucky fan will go home with two charter airfare tickets courtesy of AAA Travel and Funjet Vacations.

Follow on MiLB First Pitch  https //stza.co/+vNsh-e

Shop  https //stza.co/+vNsh-h

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Timber Rattlers vs. Bees
END:VALARM
DTSTART:20180809T000500Z
DTEND:20180809T030500Z
UID:Z0OwXwIFPkNUrBNUiMQmhMZk@stanza.co
SUMMARY:Timber Rattlers vs. Bees
DESCRIPTION:Enjoy Cher-Make hotdogs, sodas, and domestic beer for $1. A lucky fan will go home with two charter airfare tickets courtesy of AAA Travel and Funjet Vacations.\n\nFollow on MiLB First Pitch: https://stza.co/+vNsh-e\n\nShop: https://stza.co/+vNsh-h\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Bang For Your Buck
STATUS:CONFIRMED
CREATED:20180213T144607Z
LAST-MODIFIED:20180213T144607Z
TRANSP:OPAQUE
END:VEVENT
* Timber Rattlers vs. Bees
<2018-08-09 Thu 19:05-22:05>
:PROPERTIES:
:ID:       fNW8nNMYLrOq8-YKTCNnzvE3@stanza.co
:LOCATION: Craft Brews and Brats
:STATUS:   CONFIRMED
:END:

Timber Rattlers vs. Bees Enjoy 12 oz craft beer and Cher-Make Brats for only $2. Present any Thursday game ticket at Wissota Taphouse for a free beer.

Follow on MiLB First Pitch  https //stza.co/+vNsj-29

Shop  https //stza.co/+vNsj-3T

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Timber Rattlers vs. Bees
END:VALARM
DTSTART:20180810T000500Z
DTEND:20180810T030500Z
UID:fNW8nNMYLrOq8-YKTCNnzvE3@stanza.co
SUMMARY:Timber Rattlers vs. Bees
DESCRIPTION:Enjoy 12 oz craft beer and Cher-Make Brats for only $2. Present any Thursday game ticket at Wissota Taphouse for a free beer.\n\nFollow on MiLB First Pitch: https://stza.co/+vNsj-29\n\nShop: https://stza.co/+vNsj-3T\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Craft Brews and Brats
STATUS:CONFIRMED
CREATED:20180213T144607Z
LAST-MODIFIED:20180213T144607Z
TRANSP:OPAQUE
END:VEVENT
* Timber Rattlers vs. Bees
<2018-08-10 Fri 19:05-22:05>
:PROPERTIES:
:ID:       wv1904ovrziH4H2ptoMh_TRv@stanza.co
:LOCATION: Princess Night
:STATUS:   CONFIRMED
:END:

Timber Rattlers vs. Bees Join Sleeping Beauty, Tiana, Elena of Avalor and Snow White as we roll out the Red Carpet for Princess Night #2! The princesses will be available for pictures throughout the game starting when gates open at 5 30PM. Stick around afterwards for Post-Game Fireworks and Kids Run the Bases!

Follow on MiLB First Pitch  https //stza.co/+vNsm-3_

Shop  https //stza.co/+vNsm-1B

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Timber Rattlers vs. Bees
END:VALARM
DTSTART:20180811T000500Z
DTEND:20180811T030500Z
UID:wv1904ovrziH4H2ptoMh_TRv@stanza.co
SUMMARY:Timber Rattlers vs. Bees
DESCRIPTION:Join Sleeping Beauty, Tiana, Elena of Avalor and Snow White as we roll out the Red Carpet for Princess Night #2! The princesses will be available for pictures throughout the game starting when gates open at 5:30PM. Stick around afterwards for Post-Game Fireworks and Kids Run the Bases!\n\nFollow on MiLB First Pitch: https://stza.co/+vNsm-3_\n\nShop: https://stza.co/+vNsm-1B\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Princess Night
STATUS:CONFIRMED
CREATED:20180213T144607Z
LAST-MODIFIED:20180213T144607Z
TRANSP:OPAQUE
END:VEVENT
* Timber Rattlers @ Snappers
<2018-08-11 Sat 19:00-22:00>
:PROPERTIES:
:ID:       9eeq1Kd0EHDgOkHT2SPExVEP@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Timber Rattlers @ Snappers Timber Rattlers @ Snappers

Follow on MiLB First Pitch  https //stza.co/+wSOE-1j

Shop  https //stza.co/+wSOE-33

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Timber Rattlers @ Snappers
END:VALARM
DTSTART:20180812T000000Z
DTEND:20180812T030000Z
UID:9eeq1Kd0EHDgOkHT2SPExVEP@stanza.co
SUMMARY:Timber Rattlers @ Snappers
DESCRIPTION:Timber Rattlers @ Snappers\n\nFollow on MiLB First Pitch: https://stza.co/+wSOE-1j\n\nShop: https://stza.co/+wSOE-33\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144607Z
LAST-MODIFIED:20180213T144607Z
TRANSP:OPAQUE
END:VEVENT
* Timber Rattlers @ Snappers
<2018-08-12 Sun 14:00-17:00>
:PROPERTIES:
:ID:       jmHyNw9q_EUPyMmO6mdDFECe@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Timber Rattlers @ Snappers Timber Rattlers @ Snappers

Follow on MiLB First Pitch  https //stza.co/+wSOF-2Y

Shop  https //stza.co/+wSOF-K

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Timber Rattlers @ Snappers
END:VALARM
DTSTART:20180812T190000Z
DTEND:20180812T220000Z
UID:jmHyNw9q_EUPyMmO6mdDFECe@stanza.co
SUMMARY:Timber Rattlers @ Snappers
DESCRIPTION:Timber Rattlers @ Snappers\n\nFollow on MiLB First Pitch: https://stza.co/+wSOF-2Y\n\nShop: https://stza.co/+wSOF-K\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144607Z
LAST-MODIFIED:20180213T144607Z
TRANSP:OPAQUE
END:VEVENT
* Timber Rattlers @ Snappers
<2018-08-13 Mon 19:00-22:00>
:PROPERTIES:
:ID:       K_VqX78YhlFDR6p_WvtVdu7R@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Timber Rattlers @ Snappers Timber Rattlers @ Snappers

Follow on MiLB First Pitch  https //stza.co/+wSOG-3C

Shop  https //stza.co/+wSOG-3d

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Timber Rattlers @ Snappers
END:VALARM
DTSTART:20180814T000000Z
DTEND:20180814T030000Z
UID:K_VqX78YhlFDR6p_WvtVdu7R@stanza.co
SUMMARY:Timber Rattlers @ Snappers
DESCRIPTION:Timber Rattlers @ Snappers\n\nFollow on MiLB First Pitch: https://stza.co/+wSOG-3C\n\nShop: https://stza.co/+wSOG-3d\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144607Z
LAST-MODIFIED:20180213T144607Z
TRANSP:OPAQUE
END:VEVENT
* Timber Rattlers @ Snappers
<2018-08-14 Tue 19:00-22:00>
:PROPERTIES:
:ID:       VV-kB-2dHWT7a1Dpm0GRm5w4@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Timber Rattlers @ Snappers Timber Rattlers @ Snappers

Follow on MiLB First Pitch  https //stza.co/+wSOH-2S

Shop  https //stza.co/+wSOH-Z

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Timber Rattlers @ Snappers
END:VALARM
DTSTART:20180815T000000Z
DTEND:20180815T030000Z
UID:VV-kB-2dHWT7a1Dpm0GRm5w4@stanza.co
SUMMARY:Timber Rattlers @ Snappers
DESCRIPTION:Timber Rattlers @ Snappers\n\nFollow on MiLB First Pitch: https://stza.co/+wSOH-2S\n\nShop: https://stza.co/+wSOH-Z\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144607Z
LAST-MODIFIED:20180213T144607Z
TRANSP:OPAQUE
END:VEVENT
* Timber Rattlers @ Bees
<2018-08-15 Wed 18:30-21:30>
:PROPERTIES:
:ID:       MutuatLygK2yX_KYHVg2ZkIl@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Timber Rattlers @ Bees Timber Rattlers @ Bees

Follow on MiLB First Pitch  https //stza.co/+xBCr-38

Shop  https //stza.co/+xBCr-17

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Timber Rattlers @ Bees
END:VALARM
DTSTART:20180815T233000Z
DTEND:20180816T023000Z
UID:MutuatLygK2yX_KYHVg2ZkIl@stanza.co
SUMMARY:Timber Rattlers @ Bees
DESCRIPTION:Timber Rattlers @ Bees\n\nFollow on MiLB First Pitch: https://stza.co/+xBCr-38\n\nShop: https://stza.co/+xBCr-17\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144607Z
LAST-MODIFIED:20180213T144607Z
TRANSP:OPAQUE
END:VEVENT
* Timber Rattlers @ Bees
<2018-08-16 Thu 18:30-21:30>
:PROPERTIES:
:ID:       V07VNsASA6GxshTNlNDVtUpx@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Timber Rattlers @ Bees Timber Rattlers @ Bees

Follow on MiLB First Pitch  https //stza.co/+xBCs-3

Shop  https //stza.co/+xBCs-1F

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Timber Rattlers @ Bees
END:VALARM
DTSTART:20180816T233000Z
DTEND:20180817T023000Z
UID:V07VNsASA6GxshTNlNDVtUpx@stanza.co
SUMMARY:Timber Rattlers @ Bees
DESCRIPTION:Timber Rattlers @ Bees\n\nFollow on MiLB First Pitch: https://stza.co/+xBCs-3\n\nShop: https://stza.co/+xBCs-1F\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144607Z
LAST-MODIFIED:20180213T144607Z
TRANSP:OPAQUE
END:VEVENT
* Timber Rattlers @ Bees
<2018-08-17 Fri 18:30-21:30>
:PROPERTIES:
:ID:       rwd-Ohbg9nNgSNuL3zuA-hR0@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Timber Rattlers @ Bees Timber Rattlers @ Bees

Follow on MiLB First Pitch  https //stza.co/+xBCt-1m

Shop  https //stza.co/+xBCt-1Z

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Timber Rattlers @ Bees
END:VALARM
DTSTART:20180817T233000Z
DTEND:20180818T023000Z
UID:rwd-Ohbg9nNgSNuL3zuA-hR0@stanza.co
SUMMARY:Timber Rattlers @ Bees
DESCRIPTION:Timber Rattlers @ Bees\n\nFollow on MiLB First Pitch: https://stza.co/+xBCt-1m\n\nShop: https://stza.co/+xBCt-1Z\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144607Z
LAST-MODIFIED:20180213T144607Z
TRANSP:OPAQUE
END:VEVENT
* Timber Rattlers vs. Kernels
<2018-08-18 Sat 18:35-21:35>
:PROPERTIES:
:ID:       Eh_gJSiLnF1mvObm5n1H_d_x@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Timber Rattlers vs. Kernels Timber Rattlers vs. Kernels

Follow on MiLB First Pitch  https //stza.co/+vNso-1B

Shop  https //stza.co/+vNso-3q

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Timber Rattlers vs. Kernels
END:VALARM
DTSTART:20180818T233500Z
DTEND:20180819T023500Z
UID:Eh_gJSiLnF1mvObm5n1H_d_x@stanza.co
SUMMARY:Timber Rattlers vs. Kernels
DESCRIPTION:Timber Rattlers vs. Kernels\n\nFollow on MiLB First Pitch: https://stza.co/+vNso-1B\n\nShop: https://stza.co/+vNso-3q\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144607Z
LAST-MODIFIED:20180213T144607Z
TRANSP:OPAQUE
END:VEVENT
* Timber Rattlers vs. Kernels
<2018-08-19 Sun 13:05-16:05>
:PROPERTIES:
:ID:       BTJRwvn6AYqubWkR-TnNwk70@stanza.co
:LOCATION: Brewers Sunday
:STATUS:   CONFIRMED
:END:

Timber Rattlers vs. Kernels Play catch on the field pre-game. Player autographs after the game. Brewers themed jerseys worn on field. Brewers Fan Makeover.

Follow on MiLB First Pitch  https //stza.co/+vNsq-1s

Shop  https //stza.co/+vNsq-2R

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Timber Rattlers vs. Kernels
END:VALARM
DTSTART:20180819T180500Z
DTEND:20180819T210500Z
UID:BTJRwvn6AYqubWkR-TnNwk70@stanza.co
SUMMARY:Timber Rattlers vs. Kernels
DESCRIPTION:Play catch on the field pre-game. Player autographs after the game. Brewers themed jerseys worn on field. Brewers Fan Makeover.\n\nFollow on MiLB First Pitch: https://stza.co/+vNsq-1s\n\nShop: https://stza.co/+vNsq-2R\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Brewers Sunday
STATUS:CONFIRMED
CREATED:20180213T144607Z
LAST-MODIFIED:20180213T144607Z
TRANSP:OPAQUE
END:VEVENT
* Timber Rattlers vs. Kernels
<2018-08-20 Mon 12:05-15:05>
:PROPERTIES:
:ID:       pJVcpJgxjdZz864h7FvVmi5m@stanza.co
:LOCATION: Qdoba Q'Monday
:STATUS:   CONFIRMED
:END:

Timber Rattlers vs. Kernels Purchase any Qdoba entree on any Monday game at any Appleton, Neenah, or Oshkosh location and receive a free Monday game ticket.

Follow on MiLB First Pitch  https //stza.co/+vNsr-21

Shop  https //stza.co/+vNsr-29

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Timber Rattlers vs. Kernels
END:VALARM
DTSTART:20180820T170500Z
DTEND:20180820T200500Z
UID:pJVcpJgxjdZz864h7FvVmi5m@stanza.co
SUMMARY:Timber Rattlers vs. Kernels
DESCRIPTION:Purchase any Qdoba entree on any Monday game at any Appleton, Neenah, or Oshkosh location and receive a free Monday game ticket.\n\nFollow on MiLB First Pitch: https://stza.co/+vNsr-21\n\nShop: https://stza.co/+vNsr-29\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Qdoba Q'Monday
STATUS:CONFIRMED
CREATED:20180213T144607Z
LAST-MODIFIED:20180213T144607Z
TRANSP:OPAQUE
END:VEVENT
* Timber Rattlers vs. River Bandits
<2018-08-21 Tue 19:05-22:05>
:PROPERTIES:
:ID:       QdiLjYuvXxTkDKZ-XjAVY_pm@stanza.co
:LOCATION: Baker Tilly Business Person Special
:STATUS:   CONFIRMED
:END:

Timber Rattlers vs. River Bandits Business Persons that present business card, Military Personnel with ID and seniors with ID 55 & older receive a box seat ticket. Beverage & brat or hot dog for just $14.50.

Follow on MiLB First Pitch  https //stza.co/+vNst-K

Shop  https //stza.co/+vNst-9

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Timber Rattlers vs. River Bandits
END:VALARM
DTSTART:20180822T000500Z
DTEND:20180822T030500Z
UID:QdiLjYuvXxTkDKZ-XjAVY_pm@stanza.co
SUMMARY:Timber Rattlers vs. River Bandits
DESCRIPTION:Business Persons that present business card, Military Personnel with ID and seniors with ID 55 & older receive a box seat ticket. Beverage & brat or hot dog for just $14.50.\n\nFollow on MiLB First Pitch: https://stza.co/+vNst-K\n\nShop: https://stza.co/+vNst-9\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Baker Tilly Business Person Special
STATUS:CONFIRMED
CREATED:20180213T144607Z
LAST-MODIFIED:20180213T144607Z
TRANSP:OPAQUE
END:VEVENT
* Timber Rattlers vs. River Bandits
<2018-08-22 Wed 19:05-22:05>
:PROPERTIES:
:ID:       vkVf_-Gx6ehXlnvH4ufxHNCv@stanza.co
:LOCATION: Bang For Your Buck
:STATUS:   CONFIRMED
:END:

Timber Rattlers vs. River Bandits Enjoy Cher-Make hotdogs, sodas, and domestic beer for $1. A lucky fan will go home with two charter airfare tickets courtesy of AAA Travel and Funjet Vacations.

Follow on MiLB First Pitch  https //stza.co/+vNsv-3A

Shop  https //stza.co/+vNsv-3p

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Timber Rattlers vs. River Bandits
END:VALARM
DTSTART:20180823T000500Z
DTEND:20180823T030500Z
UID:vkVf_-Gx6ehXlnvH4ufxHNCv@stanza.co
SUMMARY:Timber Rattlers vs. River Bandits
DESCRIPTION:Enjoy Cher-Make hotdogs, sodas, and domestic beer for $1. A lucky fan will go home with two charter airfare tickets courtesy of AAA Travel and Funjet Vacations.\n\nFollow on MiLB First Pitch: https://stza.co/+vNsv-3A\n\nShop: https://stza.co/+vNsv-3p\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Bang For Your Buck
STATUS:CONFIRMED
CREATED:20180213T144607Z
LAST-MODIFIED:20180213T144607Z
TRANSP:OPAQUE
END:VEVENT
* Timber Rattlers vs. River Bandits
<2018-08-23 Thu 19:05-22:05>
:PROPERTIES:
:ID:       ahTThm2O6DqWXT59dDQHVarH@stanza.co
:LOCATION: Craft Brews and Brats
:STATUS:   CONFIRMED
:END:

Timber Rattlers vs. River Bandits Enjoy 12 oz craft beer and Cher-Make Brats for only $2. Present any Thursday game ticket at Wissota Taphouse for a free beer.

Follow on MiLB First Pitch  https //stza.co/+vNsx-12

Shop  https //stza.co/+vNsx-f

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Timber Rattlers vs. River Bandits
END:VALARM
DTSTART:20180824T000500Z
DTEND:20180824T030500Z
UID:ahTThm2O6DqWXT59dDQHVarH@stanza.co
SUMMARY:Timber Rattlers vs. River Bandits
DESCRIPTION:Enjoy 12 oz craft beer and Cher-Make Brats for only $2. Present any Thursday game ticket at Wissota Taphouse for a free beer.\n\nFollow on MiLB First Pitch: https://stza.co/+vNsx-12\n\nShop: https://stza.co/+vNsx-f\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Craft Brews and Brats
STATUS:CONFIRMED
CREATED:20180213T144607Z
LAST-MODIFIED:20180213T144607Z
TRANSP:OPAQUE
END:VEVENT
* Timber Rattlers @ LumberKings
<2018-08-24 Fri 18:30-21:30>
:PROPERTIES:
:ID:       HVMe-yGpq80vqM6zjc0MCCNc@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Timber Rattlers @ LumberKings Timber Rattlers @ LumberKings

Follow on MiLB First Pitch  https //stza.co/+vNpP-B

Shop  https //stza.co/+vNpP-I

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Timber Rattlers @ LumberKings
END:VALARM
DTSTART:20180824T233000Z
DTEND:20180825T023000Z
UID:HVMe-yGpq80vqM6zjc0MCCNc@stanza.co
SUMMARY:Timber Rattlers @ LumberKings
DESCRIPTION:Timber Rattlers @ LumberKings\n\nFollow on MiLB First Pitch: https://stza.co/+vNpP-B\n\nShop: https://stza.co/+vNpP-I\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144607Z
LAST-MODIFIED:20180213T144607Z
TRANSP:OPAQUE
END:VEVENT
* Timber Rattlers @ LumberKings
<2018-08-25 Sat 18:30-21:30>
:PROPERTIES:
:ID:       lmO8k38kKCALFnWsesGgqG9o@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Timber Rattlers @ LumberKings Timber Rattlers @ LumberKings

Follow on MiLB First Pitch  https //stza.co/+vNpQ-2v

Shop  https //stza.co/+vNpQ-1I

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Timber Rattlers @ LumberKings
END:VALARM
DTSTART:20180825T233000Z
DTEND:20180826T023000Z
UID:lmO8k38kKCALFnWsesGgqG9o@stanza.co
SUMMARY:Timber Rattlers @ LumberKings
DESCRIPTION:Timber Rattlers @ LumberKings\n\nFollow on MiLB First Pitch: https://stza.co/+vNpQ-2v\n\nShop: https://stza.co/+vNpQ-1I\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144607Z
LAST-MODIFIED:20180213T144607Z
TRANSP:OPAQUE
END:VEVENT
* Timber Rattlers @ LumberKings
<2018-08-26 Sun 14:00-17:00>
:PROPERTIES:
:ID:       Do6IeoiaP8hB6r2vvec839fJ@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Timber Rattlers @ LumberKings Timber Rattlers @ LumberKings

Follow on MiLB First Pitch  https //stza.co/+vNpR-Z

Shop  https //stza.co/+vNpR-3R

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Timber Rattlers @ LumberKings
END:VALARM
DTSTART:20180826T190000Z
DTEND:20180826T220000Z
UID:Do6IeoiaP8hB6r2vvec839fJ@stanza.co
SUMMARY:Timber Rattlers @ LumberKings
DESCRIPTION:Timber Rattlers @ LumberKings\n\nFollow on MiLB First Pitch: https://stza.co/+vNpR-Z\n\nShop: https://stza.co/+vNpR-3R\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144607Z
LAST-MODIFIED:20180213T144607Z
TRANSP:OPAQUE
END:VEVENT
* Timber Rattlers @ LumberKings
<2018-08-27 Mon 18:30-21:30>
:PROPERTIES:
:ID:       Z8v-MbcUOW6M0FOmeb0xFHCw@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Timber Rattlers @ LumberKings Timber Rattlers @ LumberKings

Follow on MiLB First Pitch  https //stza.co/+vNpS-2G

Shop  https //stza.co/+vNpS-P

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Timber Rattlers @ LumberKings
END:VALARM
DTSTART:20180827T233000Z
DTEND:20180828T023000Z
UID:Z8v-MbcUOW6M0FOmeb0xFHCw@stanza.co
SUMMARY:Timber Rattlers @ LumberKings
DESCRIPTION:Timber Rattlers @ LumberKings\n\nFollow on MiLB First Pitch: https://stza.co/+vNpS-2G\n\nShop: https://stza.co/+vNpS-P\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144607Z
LAST-MODIFIED:20180213T144607Z
TRANSP:OPAQUE
END:VEVENT
* Timber Rattlers vs. Snappers
<2018-08-29 Wed 19:05-22:05>
:PROPERTIES:
:ID:       vB0BPP-_qADDXB7aktbOahdi@stanza.co
:LOCATION: Bang For Your Buck
:STATUS:   CONFIRMED
:END:

Timber Rattlers vs. Snappers Enjoy Cher-Make hotdogs, sodas, and domestic beer for $1. A lucky fan will go home with two charter airfare tickets courtesy of AAA Travel and Funjet Vacations.

Follow on MiLB First Pitch  https //stza.co/+vNsz-s

Shop  https //stza.co/+vNsz-3V

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Timber Rattlers vs. Snappers
END:VALARM
DTSTART:20180830T000500Z
DTEND:20180830T030500Z
UID:vB0BPP-_qADDXB7aktbOahdi@stanza.co
SUMMARY:Timber Rattlers vs. Snappers
DESCRIPTION:Enjoy Cher-Make hotdogs, sodas, and domestic beer for $1. A lucky fan will go home with two charter airfare tickets courtesy of AAA Travel and Funjet Vacations.\n\nFollow on MiLB First Pitch: https://stza.co/+vNsz-s\n\nShop: https://stza.co/+vNsz-3V\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Bang For Your Buck
STATUS:CONFIRMED
CREATED:20180213T144607Z
LAST-MODIFIED:20180213T144607Z
TRANSP:OPAQUE
END:VEVENT
* Timber Rattlers vs. Snappers
<2018-08-30 Thu 19:05-22:05>
:PROPERTIES:
:ID:       ClNomEnXP5gp6iMbQZhg65HV@stanza.co
:LOCATION: Craft Brews and Brats
:STATUS:   CONFIRMED
:END:

Timber Rattlers vs. Snappers Enjoy 12 oz craft beer and Cher-Make Brats for only $2. Present any Thursday game ticket at Wissota Taphouse for a free beer.

Follow on MiLB First Pitch  https //stza.co/+vNsB-D

Shop  https //stza.co/+vNsB-R

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Timber Rattlers vs. Snappers
END:VALARM
DTSTART:20180831T000500Z
DTEND:20180831T030500Z
UID:ClNomEnXP5gp6iMbQZhg65HV@stanza.co
SUMMARY:Timber Rattlers vs. Snappers
DESCRIPTION:Enjoy 12 oz craft beer and Cher-Make Brats for only $2. Present any Thursday game ticket at Wissota Taphouse for a free beer.\n\nFollow on MiLB First Pitch: https://stza.co/+vNsB-D\n\nShop: https://stza.co/+vNsB-R\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Craft Brews and Brats
STATUS:CONFIRMED
CREATED:20180213T144607Z
LAST-MODIFIED:20180213T144607Z
TRANSP:OPAQUE
END:VEVENT
* Timber Rattlers vs. Snappers
<2018-08-31 Fri 19:05-22:05>
:PROPERTIES:
:ID:       dbdLwZSTqmWMAgIoNT0Q1iU2@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Timber Rattlers vs. Snappers Timber Rattlers vs. Snappers

Follow on MiLB First Pitch  https //stza.co/+vNsD-2o

Shop  https //stza.co/+vNsD-3D

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Timber Rattlers vs. Snappers
END:VALARM
DTSTART:20180901T000500Z
DTEND:20180901T030500Z
UID:dbdLwZSTqmWMAgIoNT0Q1iU2@stanza.co
SUMMARY:Timber Rattlers vs. Snappers
DESCRIPTION:Timber Rattlers vs. Snappers\n\nFollow on MiLB First Pitch: https://stza.co/+vNsD-2o\n\nShop: https://stza.co/+vNsD-3D\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144607Z
LAST-MODIFIED:20180213T144607Z
TRANSP:OPAQUE
END:VEVENT
* Timber Rattlers @ Cougars
<2018-09-01 Sat 18:30-21:30>
:PROPERTIES:
:ID:       wv5mo9bX9IVPA1vbL3Pt2OYw@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Timber Rattlers @ Cougars Timber Rattlers @ Cougars

Follow on MiLB First Pitch  https //stza.co/+xBCH-2r

Shop  https //stza.co/+xBCH-1W

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Timber Rattlers @ Cougars
END:VALARM
DTSTART:20180901T233000Z
DTEND:20180902T023000Z
UID:wv5mo9bX9IVPA1vbL3Pt2OYw@stanza.co
SUMMARY:Timber Rattlers @ Cougars
DESCRIPTION:Timber Rattlers @ Cougars\n\nFollow on MiLB First Pitch: https://stza.co/+xBCH-2r\n\nShop: https://stza.co/+xBCH-1W\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144607Z
LAST-MODIFIED:20180213T144607Z
TRANSP:OPAQUE
END:VEVENT
* Timber Rattlers @ Cougars
<2018-09-02 Sun 18:30-21:30>
:PROPERTIES:
:ID:       gjqCewGkeHuuik2HSmTWLoyp@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Timber Rattlers @ Cougars Timber Rattlers @ Cougars

Follow on MiLB First Pitch  https //stza.co/+xBCM-3S

Shop  https //stza.co/+xBCM-w

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Timber Rattlers @ Cougars
END:VALARM
DTSTART:20180902T233000Z
DTEND:20180903T023000Z
UID:gjqCewGkeHuuik2HSmTWLoyp@stanza.co
SUMMARY:Timber Rattlers @ Cougars
DESCRIPTION:Timber Rattlers @ Cougars\n\nFollow on MiLB First Pitch: https://stza.co/+xBCM-3S\n\nShop: https://stza.co/+xBCM-w\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144607Z
LAST-MODIFIED:20180213T144607Z
TRANSP:OPAQUE
END:VEVENT
* Timber Rattlers @ Cougars
<2018-09-03 Mon 13:00-16:00>
:PROPERTIES:
:ID:       dSkqd6rTaVvgjAUcpfjFrj0H@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Timber Rattlers @ Cougars Timber Rattlers @ Cougars

Follow on MiLB First Pitch  https //stza.co/+xBCQ-i

Shop  https //stza.co/+xBCQ-$

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Timber Rattlers @ Cougars
END:VALARM
DTSTART:20180903T180000Z
DTEND:20180903T210000Z
UID:dSkqd6rTaVvgjAUcpfjFrj0H@stanza.co
SUMMARY:Timber Rattlers @ Cougars
DESCRIPTION:Timber Rattlers @ Cougars\n\nFollow on MiLB First Pitch: https://stza.co/+xBCQ-i\n\nShop: https://stza.co/+xBCQ-$\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144607Z
LAST-MODIFIED:20180213T144607Z
TRANSP:OPAQUE
END:VEVENT
