#+TITLE:       Main Google calendar entries
#+AUTHOR:      Eric S Fraga
#+EMAIL:       e.fraga@ucl.ac.uk
#+DESCRIPTION: converted using the ical2org awk script
#+CATEGORY:    google
#+STARTUP:     hidestars
#+STARTUP:     overview

* COMMENT original iCal preamble

* Blue Wahoos @ BayBears
<2018-04-05 Thu 18:35-21:35>
:PROPERTIES:
:ID:       9mB3K2YWGHWPeLTesL5bxkvM@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Blue Wahoos @ BayBears Blue Wahoos @ BayBears

Follow on MiLB First Pitch  https //stza.co/+v$Sm-3y

Shop  https //stza.co/+v$Sm-2T

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Blue Wahoos @ BayBears
END:VALARM
DTSTART:20180405T233500Z
DTEND:20180406T023500Z
UID:9mB3K2YWGHWPeLTesL5bxkvM@stanza.co
SUMMARY:Blue Wahoos @ BayBears
DESCRIPTION:Blue Wahoos @ BayBears\n\nFollow on MiLB First Pitch: https://stza.co/+v$Sm-3y\n\nShop: https://stza.co/+v$Sm-2T\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144550Z
LAST-MODIFIED:20180213T144550Z
TRANSP:OPAQUE
END:VEVENT
* Blue Wahoos @ BayBears
<2018-04-06 Fri 19:05-22:05>
:PROPERTIES:
:ID:       rPpGpKJnk0bQaLC16nkgkDLA@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Blue Wahoos @ BayBears Blue Wahoos @ BayBears

Follow on MiLB First Pitch  https //stza.co/+v$Sn-30

Shop  https //stza.co/+v$Sn-24

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Blue Wahoos @ BayBears
END:VALARM
DTSTART:20180407T000500Z
DTEND:20180407T030500Z
UID:rPpGpKJnk0bQaLC16nkgkDLA@stanza.co
SUMMARY:Blue Wahoos @ BayBears
DESCRIPTION:Blue Wahoos @ BayBears\n\nFollow on MiLB First Pitch: https://stza.co/+v$Sn-30\n\nShop: https://stza.co/+v$Sn-24\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144550Z
LAST-MODIFIED:20180213T144550Z
TRANSP:OPAQUE
END:VEVENT
* Blue Wahoos @ BayBears
<2018-04-07 Sat 19:05-22:05>
:PROPERTIES:
:ID:       rhZx8OwOwopk0cw7qRrQpoAu@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Blue Wahoos @ BayBears Blue Wahoos @ BayBears

Follow on MiLB First Pitch  https //stza.co/+v$So-2H

Shop  https //stza.co/+v$So-20

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Blue Wahoos @ BayBears
END:VALARM
DTSTART:20180408T000500Z
DTEND:20180408T030500Z
UID:rhZx8OwOwopk0cw7qRrQpoAu@stanza.co
SUMMARY:Blue Wahoos @ BayBears
DESCRIPTION:Blue Wahoos @ BayBears\n\nFollow on MiLB First Pitch: https://stza.co/+v$So-2H\n\nShop: https://stza.co/+v$So-20\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144550Z
LAST-MODIFIED:20180213T144550Z
TRANSP:OPAQUE
END:VEVENT
* Blue Wahoos @ BayBears
<2018-04-08 Sun 14:05-17:05>
:PROPERTIES:
:ID:       388h2xt7vDzSPb-kf5YM_ykF@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Blue Wahoos @ BayBears Blue Wahoos @ BayBears

Follow on MiLB First Pitch  https //stza.co/+v$Sp-2h

Shop  https //stza.co/+v$Sp-1S

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Blue Wahoos @ BayBears
END:VALARM
DTSTART:20180408T190500Z
DTEND:20180408T220500Z
UID:388h2xt7vDzSPb-kf5YM_ykF@stanza.co
SUMMARY:Blue Wahoos @ BayBears
DESCRIPTION:Blue Wahoos @ BayBears\n\nFollow on MiLB First Pitch: https://stza.co/+v$Sp-2h\n\nShop: https://stza.co/+v$Sp-1S\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144550Z
LAST-MODIFIED:20180213T144550Z
TRANSP:OPAQUE
END:VEVENT
* Blue Wahoos @ BayBears
<2018-04-09 Mon 18:35-21:35>
:PROPERTIES:
:ID:       a4eVU4SZPLFyGaBLU9HPHfWd@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Blue Wahoos @ BayBears Blue Wahoos @ BayBears

Follow on MiLB First Pitch  https //stza.co/+v$Sq-1o

Shop  https //stza.co/+v$Sq-14

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Blue Wahoos @ BayBears
END:VALARM
DTSTART:20180409T233500Z
DTEND:20180410T023500Z
UID:a4eVU4SZPLFyGaBLU9HPHfWd@stanza.co
SUMMARY:Blue Wahoos @ BayBears
DESCRIPTION:Blue Wahoos @ BayBears\n\nFollow on MiLB First Pitch: https://stza.co/+v$Sq-1o\n\nShop: https://stza.co/+v$Sq-14\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144550Z
LAST-MODIFIED:20180213T144550Z
TRANSP:OPAQUE
END:VEVENT
* Blue Wahoos vs. Lookouts
<2018-04-11 Wed 18:35-21:35>
:PROPERTIES:
:ID:       a1ekt6v6RsMlfxSp9rYrxrFS@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Blue Wahoos vs. Lookouts Blue Wahoos vs. Lookouts

Follow on MiLB First Pitch  https //stza.co/+wx9W-3N

Shop  https //stza.co/+wx9W-10

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Blue Wahoos vs. Lookouts
END:VALARM
DTSTART:20180411T233500Z
DTEND:20180412T023500Z
UID:a1ekt6v6RsMlfxSp9rYrxrFS@stanza.co
SUMMARY:Blue Wahoos vs. Lookouts
DESCRIPTION:Blue Wahoos vs. Lookouts\n\nFollow on MiLB First Pitch: https://stza.co/+wx9W-3N\n\nShop: https://stza.co/+wx9W-10\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144550Z
LAST-MODIFIED:20180213T144550Z
TRANSP:OPAQUE
END:VEVENT
* Blue Wahoos vs. Lookouts
<2018-04-12 Thu 18:35-21:35>
:PROPERTIES:
:ID:       jVRxLW9cj1mf_7hLp_TtTook@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Blue Wahoos vs. Lookouts Blue Wahoos vs. Lookouts

Follow on MiLB First Pitch  https //stza.co/+wx9Y-F

Shop  https //stza.co/+wx9Y-2h

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Blue Wahoos vs. Lookouts
END:VALARM
DTSTART:20180412T233500Z
DTEND:20180413T023500Z
UID:jVRxLW9cj1mf_7hLp_TtTook@stanza.co
SUMMARY:Blue Wahoos vs. Lookouts
DESCRIPTION:Blue Wahoos vs. Lookouts\n\nFollow on MiLB First Pitch: https://stza.co/+wx9Y-F\n\nShop: https://stza.co/+wx9Y-2h\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144550Z
LAST-MODIFIED:20180213T144550Z
TRANSP:OPAQUE
END:VEVENT
* Blue Wahoos vs. Lookouts
<2018-04-13 Fri 18:35-21:35>
:PROPERTIES:
:ID:       HW4GafO_mIEE4oFevW4fuEV0@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Blue Wahoos vs. Lookouts Blue Wahoos vs. Lookouts

Follow on MiLB First Pitch  https //stza.co/+wx9_-3J

Shop  https //stza.co/+wx9_-1i

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Blue Wahoos vs. Lookouts
END:VALARM
DTSTART:20180413T233500Z
DTEND:20180414T023500Z
UID:HW4GafO_mIEE4oFevW4fuEV0@stanza.co
SUMMARY:Blue Wahoos vs. Lookouts
DESCRIPTION:Blue Wahoos vs. Lookouts\n\nFollow on MiLB First Pitch: https://stza.co/+wx9_-3J\n\nShop: https://stza.co/+wx9_-1i\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144550Z
LAST-MODIFIED:20180213T144550Z
TRANSP:OPAQUE
END:VEVENT
* Blue Wahoos vs. Lookouts
<2018-04-14 Sat 18:05-21:05>
:PROPERTIES:
:ID:       w8Qye2m2-bgSX44DWjn5AQez@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Blue Wahoos vs. Lookouts Blue Wahoos vs. Lookouts

Follow on MiLB First Pitch  https //stza.co/+wxa0-3S

Shop  https //stza.co/+wxa0-F

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Blue Wahoos vs. Lookouts
END:VALARM
DTSTART:20180414T230500Z
DTEND:20180415T020500Z
UID:w8Qye2m2-bgSX44DWjn5AQez@stanza.co
SUMMARY:Blue Wahoos vs. Lookouts
DESCRIPTION:Blue Wahoos vs. Lookouts\n\nFollow on MiLB First Pitch: https://stza.co/+wxa0-3S\n\nShop: https://stza.co/+wxa0-F\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144550Z
LAST-MODIFIED:20180213T144550Z
TRANSP:OPAQUE
END:VEVENT
* Blue Wahoos vs. Lookouts
<2018-04-15 Sun 13:05-16:05>
:PROPERTIES:
:ID:       XeDMB2nsygknZcpXMg0rRcjS@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Blue Wahoos vs. Lookouts Blue Wahoos vs. Lookouts

Follow on MiLB First Pitch  https //stza.co/+wxa1-R

Shop  https //stza.co/+wxa1-1j

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Blue Wahoos vs. Lookouts
END:VALARM
DTSTART:20180415T180500Z
DTEND:20180415T210500Z
UID:XeDMB2nsygknZcpXMg0rRcjS@stanza.co
SUMMARY:Blue Wahoos vs. Lookouts
DESCRIPTION:Blue Wahoos vs. Lookouts\n\nFollow on MiLB First Pitch: https://stza.co/+wxa1-R\n\nShop: https://stza.co/+wxa1-1j\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144550Z
LAST-MODIFIED:20180213T144550Z
TRANSP:OPAQUE
END:VEVENT
* Blue Wahoos @ Braves
<2018-04-16 Mon 19:00-22:00>
:PROPERTIES:
:ID:       VfSe9p-TZdc74cYkt4hMgxM9@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Blue Wahoos @ Braves Blue Wahoos @ Braves

Follow on MiLB First Pitch  https //stza.co/+vLSJ-2u

Shop  https //stza.co/+vLSJ-2$

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Blue Wahoos @ Braves
END:VALARM
DTSTART:20180417T000000Z
DTEND:20180417T030000Z
UID:VfSe9p-TZdc74cYkt4hMgxM9@stanza.co
SUMMARY:Blue Wahoos @ Braves
DESCRIPTION:Blue Wahoos @ Braves\n\nFollow on MiLB First Pitch: https://stza.co/+vLSJ-2u\n\nShop: https://stza.co/+vLSJ-2$\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144550Z
LAST-MODIFIED:20180213T144550Z
TRANSP:OPAQUE
END:VEVENT
* Blue Wahoos @ Braves
<2018-04-17 Tue 19:00-22:00>
:PROPERTIES:
:ID:       GwxSjeAUgeqCEgAQjqg_dsGl@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Blue Wahoos @ Braves Blue Wahoos @ Braves

Follow on MiLB First Pitch  https //stza.co/+vLSK-K

Shop  https //stza.co/+vLSK-15

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Blue Wahoos @ Braves
END:VALARM
DTSTART:20180418T000000Z
DTEND:20180418T030000Z
UID:GwxSjeAUgeqCEgAQjqg_dsGl@stanza.co
SUMMARY:Blue Wahoos @ Braves
DESCRIPTION:Blue Wahoos @ Braves\n\nFollow on MiLB First Pitch: https://stza.co/+vLSK-K\n\nShop: https://stza.co/+vLSK-15\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144550Z
LAST-MODIFIED:20180213T144550Z
TRANSP:OPAQUE
END:VEVENT
* Blue Wahoos @ Braves
<2018-04-18 Wed 10:35-13:35>
:PROPERTIES:
:ID:       w78HUBkPTb5wqyKaO7YZu_Xx@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Blue Wahoos @ Braves Blue Wahoos @ Braves

Follow on MiLB First Pitch  https //stza.co/+vLSL-3X

Shop  https //stza.co/+vLSL-3U

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Blue Wahoos @ Braves
END:VALARM
DTSTART:20180418T153500Z
DTEND:20180418T183500Z
UID:w78HUBkPTb5wqyKaO7YZu_Xx@stanza.co
SUMMARY:Blue Wahoos @ Braves
DESCRIPTION:Blue Wahoos @ Braves\n\nFollow on MiLB First Pitch: https://stza.co/+vLSL-3X\n\nShop: https://stza.co/+vLSL-3U\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144550Z
LAST-MODIFIED:20180213T144550Z
TRANSP:OPAQUE
END:VEVENT
* Blue Wahoos @ Braves
<2018-04-19 Thu 19:00-22:00>
:PROPERTIES:
:ID:       WLJNPDlNmbU8DMazT_qjZK6n@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Blue Wahoos @ Braves Blue Wahoos @ Braves

Follow on MiLB First Pitch  https //stza.co/+vLSM-3W

Shop  https //stza.co/+vLSM-3w

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Blue Wahoos @ Braves
END:VALARM
DTSTART:20180420T000000Z
DTEND:20180420T030000Z
UID:WLJNPDlNmbU8DMazT_qjZK6n@stanza.co
SUMMARY:Blue Wahoos @ Braves
DESCRIPTION:Blue Wahoos @ Braves\n\nFollow on MiLB First Pitch: https://stza.co/+vLSM-3W\n\nShop: https://stza.co/+vLSM-3w\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144550Z
LAST-MODIFIED:20180213T144550Z
TRANSP:OPAQUE
END:VEVENT
* Blue Wahoos @ Braves
<2018-04-20 Fri 19:00-22:00>
:PROPERTIES:
:ID:       bmmZvhOQOx4C_AUQWsS2Woeo@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Blue Wahoos @ Braves Blue Wahoos @ Braves

Follow on MiLB First Pitch  https //stza.co/+vLSN-3_

Shop  https //stza.co/+vLSN-m

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Blue Wahoos @ Braves
END:VALARM
DTSTART:20180421T000000Z
DTEND:20180421T030000Z
UID:bmmZvhOQOx4C_AUQWsS2Woeo@stanza.co
SUMMARY:Blue Wahoos @ Braves
DESCRIPTION:Blue Wahoos @ Braves\n\nFollow on MiLB First Pitch: https://stza.co/+vLSN-3_\n\nShop: https://stza.co/+vLSN-m\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144550Z
LAST-MODIFIED:20180213T144550Z
TRANSP:OPAQUE
END:VEVENT
* Blue Wahoos vs. Barons
<2018-04-21 Sat 18:05-21:05>
:PROPERTIES:
:ID:       2jPQ_6Nf0cQ7V_6V3Iv1uy1f@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Blue Wahoos vs. Barons Blue Wahoos vs. Barons

Follow on MiLB First Pitch  https //stza.co/+wxa4-1$

Shop  https //stza.co/+wxa4-h

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Blue Wahoos vs. Barons
END:VALARM
DTSTART:20180421T230500Z
DTEND:20180422T020500Z
UID:2jPQ_6Nf0cQ7V_6V3Iv1uy1f@stanza.co
SUMMARY:Blue Wahoos vs. Barons
DESCRIPTION:Blue Wahoos vs. Barons\n\nFollow on MiLB First Pitch: https://stza.co/+wxa4-1$\n\nShop: https://stza.co/+wxa4-h\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144550Z
LAST-MODIFIED:20180213T144550Z
TRANSP:OPAQUE
END:VEVENT
* Blue Wahoos vs. Barons
<2018-04-22 Sun 13:05-16:05>
:PROPERTIES:
:ID:       XHOLQfDHVea8nK4tdLFuG8Hy@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Blue Wahoos vs. Barons Blue Wahoos vs. Barons

Follow on MiLB First Pitch  https //stza.co/+wxa5-3M

Shop  https //stza.co/+wxa5-F

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Blue Wahoos vs. Barons
END:VALARM
DTSTART:20180422T180500Z
DTEND:20180422T210500Z
UID:XHOLQfDHVea8nK4tdLFuG8Hy@stanza.co
SUMMARY:Blue Wahoos vs. Barons
DESCRIPTION:Blue Wahoos vs. Barons\n\nFollow on MiLB First Pitch: https://stza.co/+wxa5-3M\n\nShop: https://stza.co/+wxa5-F\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144550Z
LAST-MODIFIED:20180213T144550Z
TRANSP:OPAQUE
END:VEVENT
* Blue Wahoos vs. Barons
<2018-04-23 Mon 18:35-21:35>
:PROPERTIES:
:ID:       S27nyQdySuUcnUyoju-aUfBD@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Blue Wahoos vs. Barons Blue Wahoos vs. Barons

Follow on MiLB First Pitch  https //stza.co/+wxa8-2e

Shop  https //stza.co/+wxa8-1B

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Blue Wahoos vs. Barons
END:VALARM
DTSTART:20180423T233500Z
DTEND:20180424T023500Z
UID:S27nyQdySuUcnUyoju-aUfBD@stanza.co
SUMMARY:Blue Wahoos vs. Barons
DESCRIPTION:Blue Wahoos vs. Barons\n\nFollow on MiLB First Pitch: https://stza.co/+wxa8-2e\n\nShop: https://stza.co/+wxa8-1B\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144550Z
LAST-MODIFIED:20180213T144550Z
TRANSP:OPAQUE
END:VEVENT
* Blue Wahoos vs. Barons
<2018-04-24 Tue 18:35-21:35>
:PROPERTIES:
:ID:       jhptu14vF1BhwC08Ned6WZzl@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Blue Wahoos vs. Barons Blue Wahoos vs. Barons

Follow on MiLB First Pitch  https //stza.co/+wxa9-S

Shop  https //stza.co/+wxa9-2T

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Blue Wahoos vs. Barons
END:VALARM
DTSTART:20180424T233500Z
DTEND:20180425T023500Z
UID:jhptu14vF1BhwC08Ned6WZzl@stanza.co
SUMMARY:Blue Wahoos vs. Barons
DESCRIPTION:Blue Wahoos vs. Barons\n\nFollow on MiLB First Pitch: https://stza.co/+wxa9-S\n\nShop: https://stza.co/+wxa9-2T\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144550Z
LAST-MODIFIED:20180213T144550Z
TRANSP:OPAQUE
END:VEVENT
* Blue Wahoos vs. Barons
<2018-04-25 Wed 18:35-21:35>
:PROPERTIES:
:ID:       KRDzJWJMt6t2foJ6ECql8dg4@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Blue Wahoos vs. Barons Blue Wahoos vs. Barons

Follow on MiLB First Pitch  https //stza.co/+wxab-30

Shop  https //stza.co/+wxab-z

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Blue Wahoos vs. Barons
END:VALARM
DTSTART:20180425T233500Z
DTEND:20180426T023500Z
UID:KRDzJWJMt6t2foJ6ECql8dg4@stanza.co
SUMMARY:Blue Wahoos vs. Barons
DESCRIPTION:Blue Wahoos vs. Barons\n\nFollow on MiLB First Pitch: https://stza.co/+wxab-30\n\nShop: https://stza.co/+wxab-z\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144550Z
LAST-MODIFIED:20180213T144550Z
TRANSP:OPAQUE
END:VEVENT
* Blue Wahoos @ Jumbo Shrimp
<2018-04-26 Thu 18:05-21:05>
:PROPERTIES:
:ID:       vDrqNwdyXXB7drbY9Eh1a-V5@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Blue Wahoos @ Jumbo Shrimp Blue Wahoos @ Jumbo Shrimp

Follow on MiLB First Pitch  https //stza.co/+vLSz-3n

Shop  https //stza.co/+vLSz-C

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Blue Wahoos @ Jumbo Shrimp
END:VALARM
DTSTART:20180426T230500Z
DTEND:20180427T020500Z
UID:vDrqNwdyXXB7drbY9Eh1a-V5@stanza.co
SUMMARY:Blue Wahoos @ Jumbo Shrimp
DESCRIPTION:Blue Wahoos @ Jumbo Shrimp\n\nFollow on MiLB First Pitch: https://stza.co/+vLSz-3n\n\nShop: https://stza.co/+vLSz-C\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144550Z
LAST-MODIFIED:20180213T144550Z
TRANSP:OPAQUE
END:VEVENT
* Blue Wahoos @ Jumbo Shrimp
<2018-04-27 Fri 18:05-21:05>
:PROPERTIES:
:ID:       wa8ykFPhaaBSABhDtNrNIOAJ@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Blue Wahoos @ Jumbo Shrimp Blue Wahoos @ Jumbo Shrimp

Follow on MiLB First Pitch  https //stza.co/+vLSA-1X

Shop  https //stza.co/+vLSA-2h

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Blue Wahoos @ Jumbo Shrimp
END:VALARM
DTSTART:20180427T230500Z
DTEND:20180428T020500Z
UID:wa8ykFPhaaBSABhDtNrNIOAJ@stanza.co
SUMMARY:Blue Wahoos @ Jumbo Shrimp
DESCRIPTION:Blue Wahoos @ Jumbo Shrimp\n\nFollow on MiLB First Pitch: https://stza.co/+vLSA-1X\n\nShop: https://stza.co/+vLSA-2h\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144550Z
LAST-MODIFIED:20180213T144550Z
TRANSP:OPAQUE
END:VEVENT
* Blue Wahoos @ Jumbo Shrimp
<2018-04-28 Sat 17:35-20:35>
:PROPERTIES:
:ID:       Obw-_8ztU_d7QFQGrfQDWy9M@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Blue Wahoos @ Jumbo Shrimp Blue Wahoos @ Jumbo Shrimp

Follow on MiLB First Pitch  https //stza.co/+vLSB-2k

Shop  https //stza.co/+vLSB-33

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Blue Wahoos @ Jumbo Shrimp
END:VALARM
DTSTART:20180428T223500Z
DTEND:20180429T013500Z
UID:Obw-_8ztU_d7QFQGrfQDWy9M@stanza.co
SUMMARY:Blue Wahoos @ Jumbo Shrimp
DESCRIPTION:Blue Wahoos @ Jumbo Shrimp\n\nFollow on MiLB First Pitch: https://stza.co/+vLSB-2k\n\nShop: https://stza.co/+vLSB-33\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144550Z
LAST-MODIFIED:20180213T144550Z
TRANSP:OPAQUE
END:VEVENT
* Blue Wahoos @ Jumbo Shrimp
<2018-04-29 Sun 14:05-17:05>
:PROPERTIES:
:ID:       K-xDqI3VV9JKZKA_DHldD3l5@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Blue Wahoos @ Jumbo Shrimp Blue Wahoos @ Jumbo Shrimp

Follow on MiLB First Pitch  https //stza.co/+vLSC-1K

Shop  https //stza.co/+vLSC-1m

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Blue Wahoos @ Jumbo Shrimp
END:VALARM
DTSTART:20180429T190500Z
DTEND:20180429T220500Z
UID:K-xDqI3VV9JKZKA_DHldD3l5@stanza.co
SUMMARY:Blue Wahoos @ Jumbo Shrimp
DESCRIPTION:Blue Wahoos @ Jumbo Shrimp\n\nFollow on MiLB First Pitch: https://stza.co/+vLSC-1K\n\nShop: https://stza.co/+vLSC-1m\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144550Z
LAST-MODIFIED:20180213T144550Z
TRANSP:OPAQUE
END:VEVENT
* Blue Wahoos @ Jumbo Shrimp
<2018-04-30 Mon 11:05-14:05>
:PROPERTIES:
:ID:       mC_rFjh8fRWu4XVzskZQg3T6@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Blue Wahoos @ Jumbo Shrimp Blue Wahoos @ Jumbo Shrimp

Follow on MiLB First Pitch  https //stza.co/+vLSD-3E

Shop  https //stza.co/+vLSD-f

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Blue Wahoos @ Jumbo Shrimp
END:VALARM
DTSTART:20180430T160500Z
DTEND:20180430T190500Z
UID:mC_rFjh8fRWu4XVzskZQg3T6@stanza.co
SUMMARY:Blue Wahoos @ Jumbo Shrimp
DESCRIPTION:Blue Wahoos @ Jumbo Shrimp\n\nFollow on MiLB First Pitch: https://stza.co/+vLSD-3E\n\nShop: https://stza.co/+vLSD-f\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144550Z
LAST-MODIFIED:20180213T144550Z
TRANSP:OPAQUE
END:VEVENT
* Blue Wahoos vs. Braves
<2018-05-02 Wed 18:35-21:35>
:PROPERTIES:
:ID:       EWb96TWu0QQmIDOFDGfDPZb0@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Blue Wahoos vs. Braves Blue Wahoos vs. Braves

Follow on MiLB First Pitch  https //stza.co/+wxae-2w

Shop  https //stza.co/+wxae-3g

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Blue Wahoos vs. Braves
END:VALARM
DTSTART:20180502T233500Z
DTEND:20180503T023500Z
UID:EWb96TWu0QQmIDOFDGfDPZb0@stanza.co
SUMMARY:Blue Wahoos vs. Braves
DESCRIPTION:Blue Wahoos vs. Braves\n\nFollow on MiLB First Pitch: https://stza.co/+wxae-2w\n\nShop: https://stza.co/+wxae-3g\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144550Z
LAST-MODIFIED:20180213T144550Z
TRANSP:OPAQUE
END:VEVENT
* Blue Wahoos vs. Braves
<2018-05-03 Thu 18:35-21:35>
:PROPERTIES:
:ID:       5blCKj8qSlG-_uKR67PaghRx@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Blue Wahoos vs. Braves Blue Wahoos vs. Braves

Follow on MiLB First Pitch  https //stza.co/+wxag-2c

Shop  https //stza.co/+wxag-c

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Blue Wahoos vs. Braves
END:VALARM
DTSTART:20180503T233500Z
DTEND:20180504T023500Z
UID:5blCKj8qSlG-_uKR67PaghRx@stanza.co
SUMMARY:Blue Wahoos vs. Braves
DESCRIPTION:Blue Wahoos vs. Braves\n\nFollow on MiLB First Pitch: https://stza.co/+wxag-2c\n\nShop: https://stza.co/+wxag-c\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144550Z
LAST-MODIFIED:20180213T144550Z
TRANSP:OPAQUE
END:VEVENT
* Blue Wahoos vs. Braves
<2018-05-04 Fri 18:35-21:35>
:PROPERTIES:
:ID:       BWx3rp0-ywqdEaxjz_uMSyks@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Blue Wahoos vs. Braves Blue Wahoos vs. Braves

Follow on MiLB First Pitch  https //stza.co/+wxah-27

Shop  https //stza.co/+wxah-Z

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Blue Wahoos vs. Braves
END:VALARM
DTSTART:20180504T233500Z
DTEND:20180505T023500Z
UID:BWx3rp0-ywqdEaxjz_uMSyks@stanza.co
SUMMARY:Blue Wahoos vs. Braves
DESCRIPTION:Blue Wahoos vs. Braves\n\nFollow on MiLB First Pitch: https://stza.co/+wxah-27\n\nShop: https://stza.co/+wxah-Z\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144550Z
LAST-MODIFIED:20180213T144550Z
TRANSP:OPAQUE
END:VEVENT
* Blue Wahoos vs. Braves
<2018-05-05 Sat 18:05-21:05>
:PROPERTIES:
:ID:       snw08teNNCmFs5rWZJy7s0cm@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Blue Wahoos vs. Braves Blue Wahoos vs. Braves

Follow on MiLB First Pitch  https //stza.co/+wxak-y

Shop  https //stza.co/+wxak-1J

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Blue Wahoos vs. Braves
END:VALARM
DTSTART:20180505T230500Z
DTEND:20180506T020500Z
UID:snw08teNNCmFs5rWZJy7s0cm@stanza.co
SUMMARY:Blue Wahoos vs. Braves
DESCRIPTION:Blue Wahoos vs. Braves\n\nFollow on MiLB First Pitch: https://stza.co/+wxak-y\n\nShop: https://stza.co/+wxak-1J\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144550Z
LAST-MODIFIED:20180213T144550Z
TRANSP:OPAQUE
END:VEVENT
* Blue Wahoos vs. Braves
<2018-05-06 Sun 13:05-16:05>
:PROPERTIES:
:ID:       N2y-OusIIMjAIVcYX4P7XQbb@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Blue Wahoos vs. Braves Blue Wahoos vs. Braves

Follow on MiLB First Pitch  https //stza.co/+wxal-5

Shop  https //stza.co/+wxal-R

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Blue Wahoos vs. Braves
END:VALARM
DTSTART:20180506T180500Z
DTEND:20180506T210500Z
UID:N2y-OusIIMjAIVcYX4P7XQbb@stanza.co
SUMMARY:Blue Wahoos vs. Braves
DESCRIPTION:Blue Wahoos vs. Braves\n\nFollow on MiLB First Pitch: https://stza.co/+wxal-5\n\nShop: https://stza.co/+wxal-R\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144550Z
LAST-MODIFIED:20180213T144550Z
TRANSP:OPAQUE
END:VEVENT
* Blue Wahoos @ Barons
<2018-05-07 Mon 19:05-22:05>
:PROPERTIES:
:ID:       gwAs2LILFLlX_Mkzr-8ZsO3Y@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Blue Wahoos @ Barons Blue Wahoos @ Barons

Follow on MiLB First Pitch  https //stza.co/+wFX_-1_

Shop  https //stza.co/+wFX_-1F

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Blue Wahoos @ Barons
END:VALARM
DTSTART:20180508T000500Z
DTEND:20180508T030500Z
UID:gwAs2LILFLlX_Mkzr-8ZsO3Y@stanza.co
SUMMARY:Blue Wahoos @ Barons
DESCRIPTION:Blue Wahoos @ Barons\n\nFollow on MiLB First Pitch: https://stza.co/+wFX_-1_\n\nShop: https://stza.co/+wFX_-1F\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144550Z
LAST-MODIFIED:20180213T144550Z
TRANSP:OPAQUE
END:VEVENT
* Blue Wahoos @ Barons
<2018-05-08 Tue 19:05-22:05>
:PROPERTIES:
:ID:       LTzEqzT88tFn3-BZYV-ocfNv@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Blue Wahoos @ Barons Blue Wahoos @ Barons

Follow on MiLB First Pitch  https //stza.co/+wFX$-2q

Shop  https //stza.co/+wFX$-P

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Blue Wahoos @ Barons
END:VALARM
DTSTART:20180509T000500Z
DTEND:20180509T030500Z
UID:LTzEqzT88tFn3-BZYV-ocfNv@stanza.co
SUMMARY:Blue Wahoos @ Barons
DESCRIPTION:Blue Wahoos @ Barons\n\nFollow on MiLB First Pitch: https://stza.co/+wFX$-2q\n\nShop: https://stza.co/+wFX$-P\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144550Z
LAST-MODIFIED:20180213T144550Z
TRANSP:OPAQUE
END:VEVENT
* Blue Wahoos @ Barons
<2018-05-09 Wed 11:30-14:30>
:PROPERTIES:
:ID:       lJ3eSZxWh4QfLZ5R8hW_zQBD@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Blue Wahoos @ Barons Blue Wahoos @ Barons

Follow on MiLB First Pitch  https //stza.co/+wFY0-3N

Shop  https //stza.co/+wFY0-2C

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Blue Wahoos @ Barons
END:VALARM
DTSTART:20180509T163000Z
DTEND:20180509T193000Z
UID:lJ3eSZxWh4QfLZ5R8hW_zQBD@stanza.co
SUMMARY:Blue Wahoos @ Barons
DESCRIPTION:Blue Wahoos @ Barons\n\nFollow on MiLB First Pitch: https://stza.co/+wFY0-3N\n\nShop: https://stza.co/+wFY0-2C\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144550Z
LAST-MODIFIED:20180213T144550Z
TRANSP:OPAQUE
END:VEVENT
* Blue Wahoos @ Barons
<2018-05-10 Thu 19:05-22:05>
:PROPERTIES:
:ID:       JQyvICN2sZQRCEN8e5gfDw3G@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Blue Wahoos @ Barons Blue Wahoos @ Barons

Follow on MiLB First Pitch  https //stza.co/+wFY1-B

Shop  https //stza.co/+wFY1-2Y

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Blue Wahoos @ Barons
END:VALARM
DTSTART:20180511T000500Z
DTEND:20180511T030500Z
UID:JQyvICN2sZQRCEN8e5gfDw3G@stanza.co
SUMMARY:Blue Wahoos @ Barons
DESCRIPTION:Blue Wahoos @ Barons\n\nFollow on MiLB First Pitch: https://stza.co/+wFY1-B\n\nShop: https://stza.co/+wFY1-2Y\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144550Z
LAST-MODIFIED:20180213T144550Z
TRANSP:OPAQUE
END:VEVENT
* Blue Wahoos @ Barons
<2018-05-11 Fri 19:05-22:05>
:PROPERTIES:
:ID:       G5VytuypwLJINc9X4NO7jDpA@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Blue Wahoos @ Barons Blue Wahoos @ Barons

Follow on MiLB First Pitch  https //stza.co/+wFY2-3f

Shop  https //stza.co/+wFY2-y

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Blue Wahoos @ Barons
END:VALARM
DTSTART:20180512T000500Z
DTEND:20180512T030500Z
UID:G5VytuypwLJINc9X4NO7jDpA@stanza.co
SUMMARY:Blue Wahoos @ Barons
DESCRIPTION:Blue Wahoos @ Barons\n\nFollow on MiLB First Pitch: https://stza.co/+wFY2-3f\n\nShop: https://stza.co/+wFY2-y\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144550Z
LAST-MODIFIED:20180213T144550Z
TRANSP:OPAQUE
END:VEVENT
* Blue Wahoos @ Shuckers
<2018-05-12 Sat 18:35-21:35>
:PROPERTIES:
:ID:       ZdyIDwz3w5MVaK99K8Cz_q5q@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Blue Wahoos @ Shuckers Blue Wahoos @ Shuckers

Follow on MiLB First Pitch  https //stza.co/+vLS9-3m

Shop  https //stza.co/+vLS9-3E

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Blue Wahoos @ Shuckers
END:VALARM
DTSTART:20180512T233500Z
DTEND:20180513T023500Z
UID:ZdyIDwz3w5MVaK99K8Cz_q5q@stanza.co
SUMMARY:Blue Wahoos @ Shuckers
DESCRIPTION:Blue Wahoos @ Shuckers\n\nFollow on MiLB First Pitch: https://stza.co/+vLS9-3m\n\nShop: https://stza.co/+vLS9-3E\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144550Z
LAST-MODIFIED:20180213T144550Z
TRANSP:OPAQUE
END:VEVENT
* Blue Wahoos @ Shuckers
<2018-05-13 Sun 14:05-17:05>
:PROPERTIES:
:ID:       d6mK_jLUoROMVpzLVn5J7N_U@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Blue Wahoos @ Shuckers Blue Wahoos @ Shuckers

Follow on MiLB First Pitch  https //stza.co/+vLSa-b

Shop  https //stza.co/+vLSa-3R

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Blue Wahoos @ Shuckers
END:VALARM
DTSTART:20180513T190500Z
DTEND:20180513T220500Z
UID:d6mK_jLUoROMVpzLVn5J7N_U@stanza.co
SUMMARY:Blue Wahoos @ Shuckers
DESCRIPTION:Blue Wahoos @ Shuckers\n\nFollow on MiLB First Pitch: https://stza.co/+vLSa-b\n\nShop: https://stza.co/+vLSa-3R\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144550Z
LAST-MODIFIED:20180213T144550Z
TRANSP:OPAQUE
END:VEVENT
* Blue Wahoos @ Shuckers
<2018-05-14 Mon 18:35-21:35>
:PROPERTIES:
:ID:       vOc_1oWatXro3WSzdlJnXr_3@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Blue Wahoos @ Shuckers Blue Wahoos @ Shuckers

Follow on MiLB First Pitch  https //stza.co/+vLSb-C

Shop  https //stza.co/+vLSb-10

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Blue Wahoos @ Shuckers
END:VALARM
DTSTART:20180514T233500Z
DTEND:20180515T023500Z
UID:vOc_1oWatXro3WSzdlJnXr_3@stanza.co
SUMMARY:Blue Wahoos @ Shuckers
DESCRIPTION:Blue Wahoos @ Shuckers\n\nFollow on MiLB First Pitch: https://stza.co/+vLSb-C\n\nShop: https://stza.co/+vLSb-10\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144550Z
LAST-MODIFIED:20180213T144550Z
TRANSP:OPAQUE
END:VEVENT
* Blue Wahoos @ Shuckers
<2018-05-15 Tue 18:35-21:35>
:PROPERTIES:
:ID:       bA7WHRL8nk-tdILOvru4UvEN@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Blue Wahoos @ Shuckers Blue Wahoos @ Shuckers

Follow on MiLB First Pitch  https //stza.co/+vLSc-A

Shop  https //stza.co/+vLSc-3f

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Blue Wahoos @ Shuckers
END:VALARM
DTSTART:20180515T233500Z
DTEND:20180516T023500Z
UID:bA7WHRL8nk-tdILOvru4UvEN@stanza.co
SUMMARY:Blue Wahoos @ Shuckers
DESCRIPTION:Blue Wahoos @ Shuckers\n\nFollow on MiLB First Pitch: https://stza.co/+vLSc-A\n\nShop: https://stza.co/+vLSc-3f\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144550Z
LAST-MODIFIED:20180213T144550Z
TRANSP:OPAQUE
END:VEVENT
* Blue Wahoos @ Shuckers
<2018-05-16 Wed 10:35-13:35>
:PROPERTIES:
:ID:       VWF0BIxwXdWUCcHETDqN795I@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Blue Wahoos @ Shuckers Blue Wahoos @ Shuckers

Follow on MiLB First Pitch  https //stza.co/+vLSd-1V

Shop  https //stza.co/+vLSd-A

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Blue Wahoos @ Shuckers
END:VALARM
DTSTART:20180516T153500Z
DTEND:20180516T183500Z
UID:VWF0BIxwXdWUCcHETDqN795I@stanza.co
SUMMARY:Blue Wahoos @ Shuckers
DESCRIPTION:Blue Wahoos @ Shuckers\n\nFollow on MiLB First Pitch: https://stza.co/+vLSd-1V\n\nShop: https://stza.co/+vLSd-A\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144550Z
LAST-MODIFIED:20180213T144550Z
TRANSP:OPAQUE
END:VEVENT
* Blue Wahoos vs. Generals
<2018-05-17 Thu 18:35-21:35>
:PROPERTIES:
:ID:       qKaMx04nYaVdjCodZ3jVXWLq@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Blue Wahoos vs. Generals Blue Wahoos vs. Generals

Follow on MiLB First Pitch  https //stza.co/+wxao-1F

Shop  https //stza.co/+wxao-2W

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Blue Wahoos vs. Generals
END:VALARM
DTSTART:20180517T233500Z
DTEND:20180518T023500Z
UID:qKaMx04nYaVdjCodZ3jVXWLq@stanza.co
SUMMARY:Blue Wahoos vs. Generals
DESCRIPTION:Blue Wahoos vs. Generals\n\nFollow on MiLB First Pitch: https://stza.co/+wxao-1F\n\nShop: https://stza.co/+wxao-2W\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144550Z
LAST-MODIFIED:20180213T144550Z
TRANSP:OPAQUE
END:VEVENT
* Blue Wahoos vs. Generals
<2018-05-18 Fri 18:35-21:35>
:PROPERTIES:
:ID:       gMJCH_pohiBOGqqkdBPh2vi4@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Blue Wahoos vs. Generals Blue Wahoos vs. Generals

Follow on MiLB First Pitch  https //stza.co/+wxaq-1f

Shop  https //stza.co/+wxaq-2t

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Blue Wahoos vs. Generals
END:VALARM
DTSTART:20180518T233500Z
DTEND:20180519T023500Z
UID:gMJCH_pohiBOGqqkdBPh2vi4@stanza.co
SUMMARY:Blue Wahoos vs. Generals
DESCRIPTION:Blue Wahoos vs. Generals\n\nFollow on MiLB First Pitch: https://stza.co/+wxaq-1f\n\nShop: https://stza.co/+wxaq-2t\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144550Z
LAST-MODIFIED:20180213T144550Z
TRANSP:OPAQUE
END:VEVENT
* Blue Wahoos vs. Generals
<2018-05-19 Sat 18:05-21:05>
:PROPERTIES:
:ID:       93c0UOkJMMQVJyZ_ErxD_Whn@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Blue Wahoos vs. Generals Blue Wahoos vs. Generals

Follow on MiLB First Pitch  https //stza.co/+wxas-11

Shop  https //stza.co/+wxas-K

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Blue Wahoos vs. Generals
END:VALARM
DTSTART:20180519T230500Z
DTEND:20180520T020500Z
UID:93c0UOkJMMQVJyZ_ErxD_Whn@stanza.co
SUMMARY:Blue Wahoos vs. Generals
DESCRIPTION:Blue Wahoos vs. Generals\n\nFollow on MiLB First Pitch: https://stza.co/+wxas-11\n\nShop: https://stza.co/+wxas-K\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144550Z
LAST-MODIFIED:20180213T144550Z
TRANSP:OPAQUE
END:VEVENT
* Blue Wahoos vs. Generals
<2018-05-20 Sun 17:05-20:05>
:PROPERTIES:
:ID:       15ZY0Rf9EdnkaCRb1JaKtMWE@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Blue Wahoos vs. Generals Blue Wahoos vs. Generals

Follow on MiLB First Pitch  https //stza.co/+wxat-A

Shop  https //stza.co/+wxat-3w

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Blue Wahoos vs. Generals
END:VALARM
DTSTART:20180520T220500Z
DTEND:20180521T010500Z
UID:15ZY0Rf9EdnkaCRb1JaKtMWE@stanza.co
SUMMARY:Blue Wahoos vs. Generals
DESCRIPTION:Blue Wahoos vs. Generals\n\nFollow on MiLB First Pitch: https://stza.co/+wxat-A\n\nShop: https://stza.co/+wxat-3w\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144550Z
LAST-MODIFIED:20180213T144550Z
TRANSP:OPAQUE
END:VEVENT
* Blue Wahoos vs. Generals
<2018-05-21 Mon 18:35-21:35>
:PROPERTIES:
:ID:       Ai7QhTwhIO10Bm_PCpsTkkon@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Blue Wahoos vs. Generals Blue Wahoos vs. Generals

Follow on MiLB First Pitch  https //stza.co/+wxav-3G

Shop  https //stza.co/+wxav-2U

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Blue Wahoos vs. Generals
END:VALARM
DTSTART:20180521T233500Z
DTEND:20180522T023500Z
UID:Ai7QhTwhIO10Bm_PCpsTkkon@stanza.co
SUMMARY:Blue Wahoos vs. Generals
DESCRIPTION:Blue Wahoos vs. Generals\n\nFollow on MiLB First Pitch: https://stza.co/+wxav-3G\n\nShop: https://stza.co/+wxav-2U\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144550Z
LAST-MODIFIED:20180213T144550Z
TRANSP:OPAQUE
END:VEVENT
* Blue Wahoos vs. Smokies
<2018-05-23 Wed 18:35-21:35>
:PROPERTIES:
:ID:       wcpmXEy7utevokhDQrsOV8I7@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Blue Wahoos vs. Smokies Blue Wahoos vs. Smokies

Follow on MiLB First Pitch  https //stza.co/+wxay-U

Shop  https //stza.co/+wxay-D

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Blue Wahoos vs. Smokies
END:VALARM
DTSTART:20180523T233500Z
DTEND:20180524T023500Z
UID:wcpmXEy7utevokhDQrsOV8I7@stanza.co
SUMMARY:Blue Wahoos vs. Smokies
DESCRIPTION:Blue Wahoos vs. Smokies\n\nFollow on MiLB First Pitch: https://stza.co/+wxay-U\n\nShop: https://stza.co/+wxay-D\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144550Z
LAST-MODIFIED:20180213T144550Z
TRANSP:OPAQUE
END:VEVENT
* Blue Wahoos vs. Smokies
<2018-05-24 Thu 18:35-21:35>
:PROPERTIES:
:ID:       63Ipr7Dq2bL1vaCOER9hcw2D@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Blue Wahoos vs. Smokies Blue Wahoos vs. Smokies

Follow on MiLB First Pitch  https //stza.co/+wxaz-1r

Shop  https //stza.co/+wxaz-m

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Blue Wahoos vs. Smokies
END:VALARM
DTSTART:20180524T233500Z
DTEND:20180525T023500Z
UID:63Ipr7Dq2bL1vaCOER9hcw2D@stanza.co
SUMMARY:Blue Wahoos vs. Smokies
DESCRIPTION:Blue Wahoos vs. Smokies\n\nFollow on MiLB First Pitch: https://stza.co/+wxaz-1r\n\nShop: https://stza.co/+wxaz-m\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144550Z
LAST-MODIFIED:20180213T144550Z
TRANSP:OPAQUE
END:VEVENT
* Blue Wahoos vs. Smokies
<2018-05-25 Fri 18:35-21:35>
:PROPERTIES:
:ID:       0_QHez4nXIdiKPWXDPIiHurA@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Blue Wahoos vs. Smokies Blue Wahoos vs. Smokies

Follow on MiLB First Pitch  https //stza.co/+wxaC-1r

Shop  https //stza.co/+wxaC-7

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Blue Wahoos vs. Smokies
END:VALARM
DTSTART:20180525T233500Z
DTEND:20180526T023500Z
UID:0_QHez4nXIdiKPWXDPIiHurA@stanza.co
SUMMARY:Blue Wahoos vs. Smokies
DESCRIPTION:Blue Wahoos vs. Smokies\n\nFollow on MiLB First Pitch: https://stza.co/+wxaC-1r\n\nShop: https://stza.co/+wxaC-7\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144550Z
LAST-MODIFIED:20180213T144550Z
TRANSP:OPAQUE
END:VEVENT
* Blue Wahoos vs. Smokies
<2018-05-26 Sat 18:05-21:05>
:PROPERTIES:
:ID:       11z5JFrVvnO3RYbN3w1hSAdy@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Blue Wahoos vs. Smokies Blue Wahoos vs. Smokies

Follow on MiLB First Pitch  https //stza.co/+wxaD-21

Shop  https //stza.co/+wxaD-2d

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Blue Wahoos vs. Smokies
END:VALARM
DTSTART:20180526T230500Z
DTEND:20180527T020500Z
UID:11z5JFrVvnO3RYbN3w1hSAdy@stanza.co
SUMMARY:Blue Wahoos vs. Smokies
DESCRIPTION:Blue Wahoos vs. Smokies\n\nFollow on MiLB First Pitch: https://stza.co/+wxaD-21\n\nShop: https://stza.co/+wxaD-2d\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144550Z
LAST-MODIFIED:20180213T144550Z
TRANSP:OPAQUE
END:VEVENT
* Blue Wahoos vs. Smokies
<2018-05-27 Sun 18:05-21:05>
:PROPERTIES:
:ID:       7Q93V4TAZZv7nTHG_6P0yLpv@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Blue Wahoos vs. Smokies Blue Wahoos vs. Smokies

Follow on MiLB First Pitch  https //stza.co/+wxaF-k

Shop  https //stza.co/+wxaF-3h

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Blue Wahoos vs. Smokies
END:VALARM
DTSTART:20180527T230500Z
DTEND:20180528T020500Z
UID:7Q93V4TAZZv7nTHG_6P0yLpv@stanza.co
SUMMARY:Blue Wahoos vs. Smokies
DESCRIPTION:Blue Wahoos vs. Smokies\n\nFollow on MiLB First Pitch: https://stza.co/+wxaF-k\n\nShop: https://stza.co/+wxaF-3h\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144550Z
LAST-MODIFIED:20180213T144550Z
TRANSP:OPAQUE
END:VEVENT
* Blue Wahoos @ Jumbo Shrimp
<2018-05-29 Tue 18:05-21:05>
:PROPERTIES:
:ID:       Z-VLSNN6DdihRnySx9PRaCtP@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Blue Wahoos @ Jumbo Shrimp Blue Wahoos @ Jumbo Shrimp

Follow on MiLB First Pitch  https //stza.co/+vLSE-N

Shop  https //stza.co/+vLSE-2G

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Blue Wahoos @ Jumbo Shrimp
END:VALARM
DTSTART:20180529T230500Z
DTEND:20180530T020500Z
UID:Z-VLSNN6DdihRnySx9PRaCtP@stanza.co
SUMMARY:Blue Wahoos @ Jumbo Shrimp
DESCRIPTION:Blue Wahoos @ Jumbo Shrimp\n\nFollow on MiLB First Pitch: https://stza.co/+vLSE-N\n\nShop: https://stza.co/+vLSE-2G\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144550Z
LAST-MODIFIED:20180213T144550Z
TRANSP:OPAQUE
END:VEVENT
* Blue Wahoos @ Jumbo Shrimp
<2018-05-30 Wed 18:05-21:05>
:PROPERTIES:
:ID:       A3wCTgTUGQIUN_pvciXjwZSW@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Blue Wahoos @ Jumbo Shrimp Blue Wahoos @ Jumbo Shrimp

Follow on MiLB First Pitch  https //stza.co/+vLSF-23

Shop  https //stza.co/+vLSF-1$

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Blue Wahoos @ Jumbo Shrimp
END:VALARM
DTSTART:20180530T230500Z
DTEND:20180531T020500Z
UID:A3wCTgTUGQIUN_pvciXjwZSW@stanza.co
SUMMARY:Blue Wahoos @ Jumbo Shrimp
DESCRIPTION:Blue Wahoos @ Jumbo Shrimp\n\nFollow on MiLB First Pitch: https://stza.co/+vLSF-23\n\nShop: https://stza.co/+vLSF-1$\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144550Z
LAST-MODIFIED:20180213T144550Z
TRANSP:OPAQUE
END:VEVENT
* Blue Wahoos @ Jumbo Shrimp
<2018-05-31 Thu 18:05-21:05>
:PROPERTIES:
:ID:       9jKFH3CGqRjJk9QiAQbz22g-@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Blue Wahoos @ Jumbo Shrimp Blue Wahoos @ Jumbo Shrimp

Follow on MiLB First Pitch  https //stza.co/+vLSG-2o

Shop  https //stza.co/+vLSG-21

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Blue Wahoos @ Jumbo Shrimp
END:VALARM
DTSTART:20180531T230500Z
DTEND:20180601T020500Z
UID:9jKFH3CGqRjJk9QiAQbz22g-@stanza.co
SUMMARY:Blue Wahoos @ Jumbo Shrimp
DESCRIPTION:Blue Wahoos @ Jumbo Shrimp\n\nFollow on MiLB First Pitch: https://stza.co/+vLSG-2o\n\nShop: https://stza.co/+vLSG-21\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144550Z
LAST-MODIFIED:20180213T144550Z
TRANSP:OPAQUE
END:VEVENT
* Blue Wahoos @ Jumbo Shrimp
<2018-06-01 Fri 18:05-21:05>
:PROPERTIES:
:ID:       fhTKZBsV3x1VPIt7G5ziDQ9x@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Blue Wahoos @ Jumbo Shrimp Blue Wahoos @ Jumbo Shrimp

Follow on MiLB First Pitch  https //stza.co/+vLSH-B

Shop  https //stza.co/+vLSH-23

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Blue Wahoos @ Jumbo Shrimp
END:VALARM
DTSTART:20180601T230500Z
DTEND:20180602T020500Z
UID:fhTKZBsV3x1VPIt7G5ziDQ9x@stanza.co
SUMMARY:Blue Wahoos @ Jumbo Shrimp
DESCRIPTION:Blue Wahoos @ Jumbo Shrimp\n\nFollow on MiLB First Pitch: https://stza.co/+vLSH-B\n\nShop: https://stza.co/+vLSH-23\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144550Z
LAST-MODIFIED:20180213T144550Z
TRANSP:OPAQUE
END:VEVENT
* Blue Wahoos @ Jumbo Shrimp
<2018-06-02 Sat 17:35-20:35>
:PROPERTIES:
:ID:       9_0q1OGZYe8oKrLbG_xVxuQM@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Blue Wahoos @ Jumbo Shrimp Blue Wahoos @ Jumbo Shrimp

Follow on MiLB First Pitch  https //stza.co/+vLSI-27

Shop  https //stza.co/+vLSI-3k

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Blue Wahoos @ Jumbo Shrimp
END:VALARM
DTSTART:20180602T223500Z
DTEND:20180603T013500Z
UID:9_0q1OGZYe8oKrLbG_xVxuQM@stanza.co
SUMMARY:Blue Wahoos @ Jumbo Shrimp
DESCRIPTION:Blue Wahoos @ Jumbo Shrimp\n\nFollow on MiLB First Pitch: https://stza.co/+vLSI-27\n\nShop: https://stza.co/+vLSI-3k\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144550Z
LAST-MODIFIED:20180213T144550Z
TRANSP:OPAQUE
END:VEVENT
* Blue Wahoos vs. Shuckers
<2018-06-03 Sun 17:05-20:05>
:PROPERTIES:
:ID:       p_NucgAVNPyOU0B_OvKxxQcj@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Blue Wahoos vs. Shuckers Blue Wahoos vs. Shuckers

Follow on MiLB First Pitch  https //stza.co/+wxaI-J

Shop  https //stza.co/+wxaI-1I

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Blue Wahoos vs. Shuckers
END:VALARM
DTSTART:20180603T220500Z
DTEND:20180604T010500Z
UID:p_NucgAVNPyOU0B_OvKxxQcj@stanza.co
SUMMARY:Blue Wahoos vs. Shuckers
DESCRIPTION:Blue Wahoos vs. Shuckers\n\nFollow on MiLB First Pitch: https://stza.co/+wxaI-J\n\nShop: https://stza.co/+wxaI-1I\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144550Z
LAST-MODIFIED:20180213T144550Z
TRANSP:OPAQUE
END:VEVENT
* Blue Wahoos vs. Shuckers
<2018-06-04 Mon 18:35-21:35>
:PROPERTIES:
:ID:       60ZWQPvAv2bOrWkSvnP4jIet@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Blue Wahoos vs. Shuckers Blue Wahoos vs. Shuckers

Follow on MiLB First Pitch  https //stza.co/+wxaK-2d

Shop  https //stza.co/+wxaK-2B

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Blue Wahoos vs. Shuckers
END:VALARM
DTSTART:20180604T233500Z
DTEND:20180605T023500Z
UID:60ZWQPvAv2bOrWkSvnP4jIet@stanza.co
SUMMARY:Blue Wahoos vs. Shuckers
DESCRIPTION:Blue Wahoos vs. Shuckers\n\nFollow on MiLB First Pitch: https://stza.co/+wxaK-2d\n\nShop: https://stza.co/+wxaK-2B\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144550Z
LAST-MODIFIED:20180213T144550Z
TRANSP:OPAQUE
END:VEVENT
* Blue Wahoos vs. Shuckers
<2018-06-05 Tue 18:35-21:35>
:PROPERTIES:
:ID:       3BQO9WeqpfKmalpQZjGYZpli@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Blue Wahoos vs. Shuckers Blue Wahoos vs. Shuckers

Follow on MiLB First Pitch  https //stza.co/+wxaN-w

Shop  https //stza.co/+wxaN-3X

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Blue Wahoos vs. Shuckers
END:VALARM
DTSTART:20180605T233500Z
DTEND:20180606T023500Z
UID:3BQO9WeqpfKmalpQZjGYZpli@stanza.co
SUMMARY:Blue Wahoos vs. Shuckers
DESCRIPTION:Blue Wahoos vs. Shuckers\n\nFollow on MiLB First Pitch: https://stza.co/+wxaN-w\n\nShop: https://stza.co/+wxaN-3X\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144550Z
LAST-MODIFIED:20180213T144550Z
TRANSP:OPAQUE
END:VEVENT
* Blue Wahoos vs. Shuckers
<2018-06-06 Wed 18:35-21:35>
:PROPERTIES:
:ID:       qhCnsRcvPMykLF9UXFoUElUa@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Blue Wahoos vs. Shuckers Blue Wahoos vs. Shuckers

Follow on MiLB First Pitch  https //stza.co/+wxaP-2j

Shop  https //stza.co/+wxaP-1S

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Blue Wahoos vs. Shuckers
END:VALARM
DTSTART:20180606T233500Z
DTEND:20180607T023500Z
UID:qhCnsRcvPMykLF9UXFoUElUa@stanza.co
SUMMARY:Blue Wahoos vs. Shuckers
DESCRIPTION:Blue Wahoos vs. Shuckers\n\nFollow on MiLB First Pitch: https://stza.co/+wxaP-2j\n\nShop: https://stza.co/+wxaP-1S\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144550Z
LAST-MODIFIED:20180213T144550Z
TRANSP:OPAQUE
END:VEVENT
* Blue Wahoos vs. Shuckers
<2018-06-07 Thu 18:35-21:35>
:PROPERTIES:
:ID:       ZmbCPljCkrd-GA3Amyco0mnQ@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Blue Wahoos vs. Shuckers Blue Wahoos vs. Shuckers

Follow on MiLB First Pitch  https //stza.co/+wxaR-h

Shop  https //stza.co/+wxaR-1x

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Blue Wahoos vs. Shuckers
END:VALARM
DTSTART:20180607T233500Z
DTEND:20180608T023500Z
UID:ZmbCPljCkrd-GA3Amyco0mnQ@stanza.co
SUMMARY:Blue Wahoos vs. Shuckers
DESCRIPTION:Blue Wahoos vs. Shuckers\n\nFollow on MiLB First Pitch: https://stza.co/+wxaR-h\n\nShop: https://stza.co/+wxaR-1x\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144550Z
LAST-MODIFIED:20180213T144550Z
TRANSP:OPAQUE
END:VEVENT
* Blue Wahoos @ Braves
<2018-06-08 Fri 19:00-22:00>
:PROPERTIES:
:ID:       YSSu2RbxB9BLit0y6RCuVIbI@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Blue Wahoos @ Braves Blue Wahoos @ Braves

Follow on MiLB First Pitch  https //stza.co/+vLSO-1k

Shop  https //stza.co/+vLSO-2I

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Blue Wahoos @ Braves
END:VALARM
DTSTART:20180609T000000Z
DTEND:20180609T030000Z
UID:YSSu2RbxB9BLit0y6RCuVIbI@stanza.co
SUMMARY:Blue Wahoos @ Braves
DESCRIPTION:Blue Wahoos @ Braves\n\nFollow on MiLB First Pitch: https://stza.co/+vLSO-1k\n\nShop: https://stza.co/+vLSO-2I\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144550Z
LAST-MODIFIED:20180213T144550Z
TRANSP:OPAQUE
END:VEVENT
* Blue Wahoos @ Braves
<2018-06-09 Sat 18:00-21:00>
:PROPERTIES:
:ID:       _X4Ppjr_cpCAHuYJkkQ97KTd@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Blue Wahoos @ Braves Blue Wahoos @ Braves

Follow on MiLB First Pitch  https //stza.co/+vLSP-2c

Shop  https //stza.co/+vLSP-2x

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Blue Wahoos @ Braves
END:VALARM
DTSTART:20180609T230000Z
DTEND:20180610T020000Z
UID:_X4Ppjr_cpCAHuYJkkQ97KTd@stanza.co
SUMMARY:Blue Wahoos @ Braves
DESCRIPTION:Blue Wahoos @ Braves\n\nFollow on MiLB First Pitch: https://stza.co/+vLSP-2c\n\nShop: https://stza.co/+vLSP-2x\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144550Z
LAST-MODIFIED:20180213T144550Z
TRANSP:OPAQUE
END:VEVENT
* Blue Wahoos @ Braves
<2018-06-10 Sun 17:00-20:00>
:PROPERTIES:
:ID:       1Go4dTjPoWHMVgwahbch9SZr@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Blue Wahoos @ Braves Blue Wahoos @ Braves

Follow on MiLB First Pitch  https //stza.co/+vLSQ-n

Shop  https //stza.co/+vLSQ-2C

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Blue Wahoos @ Braves
END:VALARM
DTSTART:20180610T220000Z
DTEND:20180611T010000Z
UID:1Go4dTjPoWHMVgwahbch9SZr@stanza.co
SUMMARY:Blue Wahoos @ Braves
DESCRIPTION:Blue Wahoos @ Braves\n\nFollow on MiLB First Pitch: https://stza.co/+vLSQ-n\n\nShop: https://stza.co/+vLSQ-2C\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144550Z
LAST-MODIFIED:20180213T144550Z
TRANSP:OPAQUE
END:VEVENT
* Blue Wahoos @ Braves
<2018-06-11 Mon 19:00-22:00>
:PROPERTIES:
:ID:       L4JPqBvo38Bpw5o8bVLyIoIJ@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Blue Wahoos @ Braves Blue Wahoos @ Braves

Follow on MiLB First Pitch  https //stza.co/+vLSR-28

Shop  https //stza.co/+vLSR-29

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Blue Wahoos @ Braves
END:VALARM
DTSTART:20180612T000000Z
DTEND:20180612T030000Z
UID:L4JPqBvo38Bpw5o8bVLyIoIJ@stanza.co
SUMMARY:Blue Wahoos @ Braves
DESCRIPTION:Blue Wahoos @ Braves\n\nFollow on MiLB First Pitch: https://stza.co/+vLSR-28\n\nShop: https://stza.co/+vLSR-29\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144550Z
LAST-MODIFIED:20180213T144550Z
TRANSP:OPAQUE
END:VEVENT
* Blue Wahoos @ Braves
<2018-06-12 Tue 19:00-22:00>
:PROPERTIES:
:ID:       02JKvXuxYB_iOsS5Q2Q1M-ab@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Blue Wahoos @ Braves Blue Wahoos @ Braves

Follow on MiLB First Pitch  https //stza.co/+vLSS-2K

Shop  https //stza.co/+vLSS-2$

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Blue Wahoos @ Braves
END:VALARM
DTSTART:20180613T000000Z
DTEND:20180613T030000Z
UID:02JKvXuxYB_iOsS5Q2Q1M-ab@stanza.co
SUMMARY:Blue Wahoos @ Braves
DESCRIPTION:Blue Wahoos @ Braves\n\nFollow on MiLB First Pitch: https://stza.co/+vLSS-2K\n\nShop: https://stza.co/+vLSS-2$\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144550Z
LAST-MODIFIED:20180213T144550Z
TRANSP:OPAQUE
END:VEVENT
* Blue Wahoos vs. BayBears
<2018-06-13 Wed 18:35-21:35>
:PROPERTIES:
:ID:       aRKDIVQV52URjA2KmlOZIPeu@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Blue Wahoos vs. BayBears Blue Wahoos vs. BayBears

Follow on MiLB First Pitch  https //stza.co/+wxaT-1a

Shop  https //stza.co/+wxaT-3U

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Blue Wahoos vs. BayBears
END:VALARM
DTSTART:20180613T233500Z
DTEND:20180614T023500Z
UID:aRKDIVQV52URjA2KmlOZIPeu@stanza.co
SUMMARY:Blue Wahoos vs. BayBears
DESCRIPTION:Blue Wahoos vs. BayBears\n\nFollow on MiLB First Pitch: https://stza.co/+wxaT-1a\n\nShop: https://stza.co/+wxaT-3U\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144550Z
LAST-MODIFIED:20180213T144550Z
TRANSP:OPAQUE
END:VEVENT
* Blue Wahoos vs. BayBears
<2018-06-14 Thu 18:35-21:35>
:PROPERTIES:
:ID:       dPgpTPvPYGetiWJijPMVCmq1@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Blue Wahoos vs. BayBears Blue Wahoos vs. BayBears

Follow on MiLB First Pitch  https //stza.co/+wxaV-3p

Shop  https //stza.co/+wxaV-1e

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Blue Wahoos vs. BayBears
END:VALARM
DTSTART:20180614T233500Z
DTEND:20180615T023500Z
UID:dPgpTPvPYGetiWJijPMVCmq1@stanza.co
SUMMARY:Blue Wahoos vs. BayBears
DESCRIPTION:Blue Wahoos vs. BayBears\n\nFollow on MiLB First Pitch: https://stza.co/+wxaV-3p\n\nShop: https://stza.co/+wxaV-1e\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144550Z
LAST-MODIFIED:20180213T144550Z
TRANSP:OPAQUE
END:VEVENT
* Blue Wahoos vs. BayBears
<2018-06-15 Fri 18:35-21:35>
:PROPERTIES:
:ID:       vUat3o-RvCOozrLAElSziZT3@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Blue Wahoos vs. BayBears Blue Wahoos vs. BayBears

Follow on MiLB First Pitch  https //stza.co/+wxaW-F

Shop  https //stza.co/+wxaW-o

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Blue Wahoos vs. BayBears
END:VALARM
DTSTART:20180615T233500Z
DTEND:20180616T023500Z
UID:vUat3o-RvCOozrLAElSziZT3@stanza.co
SUMMARY:Blue Wahoos vs. BayBears
DESCRIPTION:Blue Wahoos vs. BayBears\n\nFollow on MiLB First Pitch: https://stza.co/+wxaW-F\n\nShop: https://stza.co/+wxaW-o\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144550Z
LAST-MODIFIED:20180213T144550Z
TRANSP:OPAQUE
END:VEVENT
* Blue Wahoos vs. BayBears
<2018-06-16 Sat 18:05-21:05>
:PROPERTIES:
:ID:       TJsBb2CnAwfjQNI7l_4DUEUE@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Blue Wahoos vs. BayBears Blue Wahoos vs. BayBears

Follow on MiLB First Pitch  https //stza.co/+wxaY-4

Shop  https //stza.co/+wxaY-31

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Blue Wahoos vs. BayBears
END:VALARM
DTSTART:20180616T230500Z
DTEND:20180617T020500Z
UID:TJsBb2CnAwfjQNI7l_4DUEUE@stanza.co
SUMMARY:Blue Wahoos vs. BayBears
DESCRIPTION:Blue Wahoos vs. BayBears\n\nFollow on MiLB First Pitch: https://stza.co/+wxaY-4\n\nShop: https://stza.co/+wxaY-31\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144550Z
LAST-MODIFIED:20180213T144550Z
TRANSP:OPAQUE
END:VEVENT
* Blue Wahoos vs. BayBears
<2018-06-17 Sun 17:05-20:05>
:PROPERTIES:
:ID:       FzE7w7ujRKW3gil7ZvCHRqiq@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Blue Wahoos vs. BayBears Blue Wahoos vs. BayBears

Follow on MiLB First Pitch  https //stza.co/+wxa$-F

Shop  https //stza.co/+wxa$-K

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Blue Wahoos vs. BayBears
END:VALARM
DTSTART:20180617T220500Z
DTEND:20180618T010500Z
UID:FzE7w7ujRKW3gil7ZvCHRqiq@stanza.co
SUMMARY:Blue Wahoos vs. BayBears
DESCRIPTION:Blue Wahoos vs. BayBears\n\nFollow on MiLB First Pitch: https://stza.co/+wxa$-F\n\nShop: https://stza.co/+wxa$-K\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144550Z
LAST-MODIFIED:20180213T144550Z
TRANSP:OPAQUE
END:VEVENT
* Blue Wahoos @ Generals
<2018-06-21 Thu 18:05-21:05>
:PROPERTIES:
:ID:       zN-w1mElDdufWMbsBmoV-fEJ@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Blue Wahoos @ Generals Blue Wahoos @ Generals

Follow on MiLB First Pitch  https //stza.co/+wCSi-3n

Shop  https //stza.co/+wCSi-20

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Blue Wahoos @ Generals
END:VALARM
DTSTART:20180621T230500Z
DTEND:20180622T020500Z
UID:zN-w1mElDdufWMbsBmoV-fEJ@stanza.co
SUMMARY:Blue Wahoos @ Generals
DESCRIPTION:Blue Wahoos @ Generals\n\nFollow on MiLB First Pitch: https://stza.co/+wCSi-3n\n\nShop: https://stza.co/+wCSi-20\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144550Z
LAST-MODIFIED:20180213T144550Z
TRANSP:OPAQUE
END:VEVENT
* Blue Wahoos @ Generals
<2018-06-22 Fri 18:05-21:05>
:PROPERTIES:
:ID:       dALIoP4NqvCFenRJRfFFdSWE@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Blue Wahoos @ Generals Blue Wahoos @ Generals

Follow on MiLB First Pitch  https //stza.co/+wCSk-34

Shop  https //stza.co/+wCSk-1J

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Blue Wahoos @ Generals
END:VALARM
DTSTART:20180622T230500Z
DTEND:20180623T020500Z
UID:dALIoP4NqvCFenRJRfFFdSWE@stanza.co
SUMMARY:Blue Wahoos @ Generals
DESCRIPTION:Blue Wahoos @ Generals\n\nFollow on MiLB First Pitch: https://stza.co/+wCSk-34\n\nShop: https://stza.co/+wCSk-1J\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144550Z
LAST-MODIFIED:20180213T144550Z
TRANSP:OPAQUE
END:VEVENT
* Blue Wahoos @ Generals
<2018-06-23 Sat 18:05-21:05>
:PROPERTIES:
:ID:       J7coka9T1ccKpvG6yURbrbd6@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Blue Wahoos @ Generals Blue Wahoos @ Generals

Follow on MiLB First Pitch  https //stza.co/+wCSm-2

Shop  https //stza.co/+wCSm-R

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Blue Wahoos @ Generals
END:VALARM
DTSTART:20180623T230500Z
DTEND:20180624T020500Z
UID:J7coka9T1ccKpvG6yURbrbd6@stanza.co
SUMMARY:Blue Wahoos @ Generals
DESCRIPTION:Blue Wahoos @ Generals\n\nFollow on MiLB First Pitch: https://stza.co/+wCSm-2\n\nShop: https://stza.co/+wCSm-R\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144550Z
LAST-MODIFIED:20180213T144550Z
TRANSP:OPAQUE
END:VEVENT
* Blue Wahoos @ Generals
<2018-06-24 Sun 18:05-21:05>
:PROPERTIES:
:ID:       fuj6FBzfSDNA_fq00Ai_ljTk@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Blue Wahoos @ Generals Blue Wahoos @ Generals

Follow on MiLB First Pitch  https //stza.co/+wCSn-3B

Shop  https //stza.co/+wCSn-F

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Blue Wahoos @ Generals
END:VALARM
DTSTART:20180624T230500Z
DTEND:20180625T020500Z
UID:fuj6FBzfSDNA_fq00Ai_ljTk@stanza.co
SUMMARY:Blue Wahoos @ Generals
DESCRIPTION:Blue Wahoos @ Generals\n\nFollow on MiLB First Pitch: https://stza.co/+wCSn-3B\n\nShop: https://stza.co/+wCSn-F\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144550Z
LAST-MODIFIED:20180213T144550Z
TRANSP:OPAQUE
END:VEVENT
* Blue Wahoos @ Generals
<2018-06-25 Mon 18:05-21:05>
:PROPERTIES:
:ID:       aTVzhtEERRkLu7nLhIEnCQ6u@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Blue Wahoos @ Generals Blue Wahoos @ Generals

Follow on MiLB First Pitch  https //stza.co/+wCSo-1q

Shop  https //stza.co/+wCSo-2W

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Blue Wahoos @ Generals
END:VALARM
DTSTART:20180625T230500Z
DTEND:20180626T020500Z
UID:aTVzhtEERRkLu7nLhIEnCQ6u@stanza.co
SUMMARY:Blue Wahoos @ Generals
DESCRIPTION:Blue Wahoos @ Generals\n\nFollow on MiLB First Pitch: https://stza.co/+wCSo-1q\n\nShop: https://stza.co/+wCSo-2W\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144550Z
LAST-MODIFIED:20180213T144550Z
TRANSP:OPAQUE
END:VEVENT
* Blue Wahoos @ Generals
<2018-06-26 Tue 12:05-15:05>
:PROPERTIES:
:ID:       dzfoDx8ZCvVt9Md7d4tv4dnE@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Blue Wahoos @ Generals Blue Wahoos @ Generals

Follow on MiLB First Pitch  https //stza.co/+wCSp-28

Shop  https //stza.co/+wCSp-2a

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Blue Wahoos @ Generals
END:VALARM
DTSTART:20180626T170500Z
DTEND:20180626T200500Z
UID:dzfoDx8ZCvVt9Md7d4tv4dnE@stanza.co
SUMMARY:Blue Wahoos @ Generals
DESCRIPTION:Blue Wahoos @ Generals\n\nFollow on MiLB First Pitch: https://stza.co/+wCSp-28\n\nShop: https://stza.co/+wCSp-2a\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144550Z
LAST-MODIFIED:20180213T144550Z
TRANSP:OPAQUE
END:VEVENT
* Blue Wahoos vs. Braves
<2018-06-28 Thu 18:35-21:35>
:PROPERTIES:
:ID:       bFa4YUXkiYGhmOke5o90_4t6@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Blue Wahoos vs. Braves Blue Wahoos vs. Braves

Follow on MiLB First Pitch  https //stza.co/+wxb0-2c

Shop  https //stza.co/+wxb0-14

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Blue Wahoos vs. Braves
END:VALARM
DTSTART:20180628T233500Z
DTEND:20180629T023500Z
UID:bFa4YUXkiYGhmOke5o90_4t6@stanza.co
SUMMARY:Blue Wahoos vs. Braves
DESCRIPTION:Blue Wahoos vs. Braves\n\nFollow on MiLB First Pitch: https://stza.co/+wxb0-2c\n\nShop: https://stza.co/+wxb0-14\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144550Z
LAST-MODIFIED:20180213T144550Z
TRANSP:OPAQUE
END:VEVENT
* Blue Wahoos vs. Braves
<2018-06-29 Fri 18:35-21:35>
:PROPERTIES:
:ID:       7GNyYa6i7gGy2ztbR2nh_W7x@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Blue Wahoos vs. Braves Blue Wahoos vs. Braves

Follow on MiLB First Pitch  https //stza.co/+wxb3-2O

Shop  https //stza.co/+wxb3-3o

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Blue Wahoos vs. Braves
END:VALARM
DTSTART:20180629T233500Z
DTEND:20180630T023500Z
UID:7GNyYa6i7gGy2ztbR2nh_W7x@stanza.co
SUMMARY:Blue Wahoos vs. Braves
DESCRIPTION:Blue Wahoos vs. Braves\n\nFollow on MiLB First Pitch: https://stza.co/+wxb3-2O\n\nShop: https://stza.co/+wxb3-3o\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144550Z
LAST-MODIFIED:20180213T144550Z
TRANSP:OPAQUE
END:VEVENT
* Blue Wahoos vs. Braves
<2018-06-30 Sat 18:05-21:05>
:PROPERTIES:
:ID:       11mdrDtqrKZ0oJWA1ceEPBe4@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Blue Wahoos vs. Braves Blue Wahoos vs. Braves

Follow on MiLB First Pitch  https //stza.co/+wxb5-1U

Shop  https //stza.co/+wxb5-1T

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Blue Wahoos vs. Braves
END:VALARM
DTSTART:20180630T230500Z
DTEND:20180701T020500Z
UID:11mdrDtqrKZ0oJWA1ceEPBe4@stanza.co
SUMMARY:Blue Wahoos vs. Braves
DESCRIPTION:Blue Wahoos vs. Braves\n\nFollow on MiLB First Pitch: https://stza.co/+wxb5-1U\n\nShop: https://stza.co/+wxb5-1T\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144550Z
LAST-MODIFIED:20180213T144550Z
TRANSP:OPAQUE
END:VEVENT
* Blue Wahoos vs. Braves
<2018-07-01 Sun 17:05-20:05>
:PROPERTIES:
:ID:       r2pZrrjOCEJgORmxuvLssd-a@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Blue Wahoos vs. Braves Blue Wahoos vs. Braves

Follow on MiLB First Pitch  https //stza.co/+wxb9-E

Shop  https //stza.co/+wxb9-2m

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Blue Wahoos vs. Braves
END:VALARM
DTSTART:20180701T220500Z
DTEND:20180702T010500Z
UID:r2pZrrjOCEJgORmxuvLssd-a@stanza.co
SUMMARY:Blue Wahoos vs. Braves
DESCRIPTION:Blue Wahoos vs. Braves\n\nFollow on MiLB First Pitch: https://stza.co/+wxb9-E\n\nShop: https://stza.co/+wxb9-2m\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144550Z
LAST-MODIFIED:20180213T144550Z
TRANSP:OPAQUE
END:VEVENT
* Blue Wahoos vs. Braves
<2018-07-02 Mon 18:35-21:35>
:PROPERTIES:
:ID:       Hpn2pkMcyyHlmy8kShV6B98e@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Blue Wahoos vs. Braves Blue Wahoos vs. Braves

Follow on MiLB First Pitch  https //stza.co/+wxbb-1w

Shop  https //stza.co/+wxbb-2Y

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Blue Wahoos vs. Braves
END:VALARM
DTSTART:20180702T233500Z
DTEND:20180703T023500Z
UID:Hpn2pkMcyyHlmy8kShV6B98e@stanza.co
SUMMARY:Blue Wahoos vs. Braves
DESCRIPTION:Blue Wahoos vs. Braves\n\nFollow on MiLB First Pitch: https://stza.co/+wxbb-1w\n\nShop: https://stza.co/+wxbb-2Y\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144550Z
LAST-MODIFIED:20180213T144550Z
TRANSP:OPAQUE
END:VEVENT
* Blue Wahoos vs. Braves
<2018-07-03 Tue 18:35-21:35>
:PROPERTIES:
:ID:       dGPqYBlULb_sPjGHI6DuZpya@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Blue Wahoos vs. Braves Blue Wahoos vs. Braves

Follow on MiLB First Pitch  https //stza.co/+wxbd-39

Shop  https //stza.co/+wxbd-P

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Blue Wahoos vs. Braves
END:VALARM
DTSTART:20180703T233500Z
DTEND:20180704T023500Z
UID:dGPqYBlULb_sPjGHI6DuZpya@stanza.co
SUMMARY:Blue Wahoos vs. Braves
DESCRIPTION:Blue Wahoos vs. Braves\n\nFollow on MiLB First Pitch: https://stza.co/+wxbd-39\n\nShop: https://stza.co/+wxbd-P\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144550Z
LAST-MODIFIED:20180213T144550Z
TRANSP:OPAQUE
END:VEVENT
* Blue Wahoos @ Biscuits
<2018-07-04 Wed 18:35-21:35>
:PROPERTIES:
:ID:       0APZmYW-d0XJN8udQi5XoG6t@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Blue Wahoos @ Biscuits Blue Wahoos @ Biscuits

Follow on MiLB First Pitch  https //stza.co/+vLT6-3T

Shop  https //stza.co/+vLT6-1K

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Blue Wahoos @ Biscuits
END:VALARM
DTSTART:20180704T233500Z
DTEND:20180705T023500Z
UID:0APZmYW-d0XJN8udQi5XoG6t@stanza.co
SUMMARY:Blue Wahoos @ Biscuits
DESCRIPTION:Blue Wahoos @ Biscuits\n\nFollow on MiLB First Pitch: https://stza.co/+vLT6-3T\n\nShop: https://stza.co/+vLT6-1K\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144550Z
LAST-MODIFIED:20180213T144550Z
TRANSP:OPAQUE
END:VEVENT
* Blue Wahoos @ Biscuits
<2018-07-05 Thu 18:35-21:35>
:PROPERTIES:
:ID:       ecmh4OWbpLJkuoF_KmhYijM0@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Blue Wahoos @ Biscuits Blue Wahoos @ Biscuits

Follow on MiLB First Pitch  https //stza.co/+vLT7-2a

Shop  https //stza.co/+vLT7-3N

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Blue Wahoos @ Biscuits
END:VALARM
DTSTART:20180705T233500Z
DTEND:20180706T023500Z
UID:ecmh4OWbpLJkuoF_KmhYijM0@stanza.co
SUMMARY:Blue Wahoos @ Biscuits
DESCRIPTION:Blue Wahoos @ Biscuits\n\nFollow on MiLB First Pitch: https://stza.co/+vLT7-2a\n\nShop: https://stza.co/+vLT7-3N\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144550Z
LAST-MODIFIED:20180213T144550Z
TRANSP:OPAQUE
END:VEVENT
* Blue Wahoos @ Biscuits
<2018-07-06 Fri 18:35-21:35>
:PROPERTIES:
:ID:       q2bLEai-Ffgs49ND7fCR2Oy7@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Blue Wahoos @ Biscuits Blue Wahoos @ Biscuits

Follow on MiLB First Pitch  https //stza.co/+vLT8-a

Shop  https //stza.co/+vLT8-7

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Blue Wahoos @ Biscuits
END:VALARM
DTSTART:20180706T233500Z
DTEND:20180707T023500Z
UID:q2bLEai-Ffgs49ND7fCR2Oy7@stanza.co
SUMMARY:Blue Wahoos @ Biscuits
DESCRIPTION:Blue Wahoos @ Biscuits\n\nFollow on MiLB First Pitch: https://stza.co/+vLT8-a\n\nShop: https://stza.co/+vLT8-7\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144550Z
LAST-MODIFIED:20180213T144550Z
TRANSP:OPAQUE
END:VEVENT
* Blue Wahoos @ Biscuits
<2018-07-07 Sat 18:05-21:05>
:PROPERTIES:
:ID:       eRbCNm43Y5xV5GA6C-t_8DVO@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Blue Wahoos @ Biscuits Blue Wahoos @ Biscuits

Follow on MiLB First Pitch  https //stza.co/+vLT9-3X

Shop  https //stza.co/+vLT9-10

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Blue Wahoos @ Biscuits
END:VALARM
DTSTART:20180707T230500Z
DTEND:20180708T020500Z
UID:eRbCNm43Y5xV5GA6C-t_8DVO@stanza.co
SUMMARY:Blue Wahoos @ Biscuits
DESCRIPTION:Blue Wahoos @ Biscuits\n\nFollow on MiLB First Pitch: https://stza.co/+vLT9-3X\n\nShop: https://stza.co/+vLT9-10\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144550Z
LAST-MODIFIED:20180213T144550Z
TRANSP:OPAQUE
END:VEVENT
* Blue Wahoos vs. BayBears
<2018-07-08 Sun 17:05-20:05>
:PROPERTIES:
:ID:       stje3uNsriLu45LeSV9apko3@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Blue Wahoos vs. BayBears Blue Wahoos vs. BayBears

Follow on MiLB First Pitch  https //stza.co/+wxbe-3M

Shop  https //stza.co/+wxbe-2l

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Blue Wahoos vs. BayBears
END:VALARM
DTSTART:20180708T220500Z
DTEND:20180709T010500Z
UID:stje3uNsriLu45LeSV9apko3@stanza.co
SUMMARY:Blue Wahoos vs. BayBears
DESCRIPTION:Blue Wahoos vs. BayBears\n\nFollow on MiLB First Pitch: https://stza.co/+wxbe-3M\n\nShop: https://stza.co/+wxbe-2l\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144550Z
LAST-MODIFIED:20180213T144550Z
TRANSP:OPAQUE
END:VEVENT
* Blue Wahoos vs. BayBears
<2018-07-09 Mon 18:35-21:35>
:PROPERTIES:
:ID:       dzIuTD3fzYP4BcxpyMAtCMiR@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Blue Wahoos vs. BayBears Blue Wahoos vs. BayBears

Follow on MiLB First Pitch  https //stza.co/+wxbh-A

Shop  https //stza.co/+wxbh-3c

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Blue Wahoos vs. BayBears
END:VALARM
DTSTART:20180709T233500Z
DTEND:20180710T023500Z
UID:dzIuTD3fzYP4BcxpyMAtCMiR@stanza.co
SUMMARY:Blue Wahoos vs. BayBears
DESCRIPTION:Blue Wahoos vs. BayBears\n\nFollow on MiLB First Pitch: https://stza.co/+wxbh-A\n\nShop: https://stza.co/+wxbh-3c\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144550Z
LAST-MODIFIED:20180213T144550Z
TRANSP:OPAQUE
END:VEVENT
* Blue Wahoos vs. BayBears
<2018-07-10 Tue 18:35-21:35>
:PROPERTIES:
:ID:       HcUD4R_tqTola9qHN56b45CQ@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Blue Wahoos vs. BayBears Blue Wahoos vs. BayBears

Follow on MiLB First Pitch  https //stza.co/+wxbi-X

Shop  https //stza.co/+wxbi-3U

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Blue Wahoos vs. BayBears
END:VALARM
DTSTART:20180710T233500Z
DTEND:20180711T023500Z
UID:HcUD4R_tqTola9qHN56b45CQ@stanza.co
SUMMARY:Blue Wahoos vs. BayBears
DESCRIPTION:Blue Wahoos vs. BayBears\n\nFollow on MiLB First Pitch: https://stza.co/+wxbi-X\n\nShop: https://stza.co/+wxbi-3U\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144550Z
LAST-MODIFIED:20180213T144550Z
TRANSP:OPAQUE
END:VEVENT
* Blue Wahoos vs. BayBears
<2018-07-11 Wed 18:35-21:35>
:PROPERTIES:
:ID:       UZ4d4cPhB4Tkd-qmnayqa45A@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Blue Wahoos vs. BayBears Blue Wahoos vs. BayBears

Follow on MiLB First Pitch  https //stza.co/+wxbl-26

Shop  https //stza.co/+wxbl-2q

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Blue Wahoos vs. BayBears
END:VALARM
DTSTART:20180711T233500Z
DTEND:20180712T023500Z
UID:UZ4d4cPhB4Tkd-qmnayqa45A@stanza.co
SUMMARY:Blue Wahoos vs. BayBears
DESCRIPTION:Blue Wahoos vs. BayBears\n\nFollow on MiLB First Pitch: https://stza.co/+wxbl-26\n\nShop: https://stza.co/+wxbl-2q\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144550Z
LAST-MODIFIED:20180213T144550Z
TRANSP:OPAQUE
END:VEVENT
* Blue Wahoos @ Braves
<2018-07-12 Thu 19:00-22:00>
:PROPERTIES:
:ID:       Pyyhf7KFf8AHOVISNAZ0XLIa@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Blue Wahoos @ Braves Blue Wahoos @ Braves

Follow on MiLB First Pitch  https //stza.co/+vLST-1W

Shop  https //stza.co/+vLST-1$

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Blue Wahoos @ Braves
END:VALARM
DTSTART:20180713T000000Z
DTEND:20180713T030000Z
UID:Pyyhf7KFf8AHOVISNAZ0XLIa@stanza.co
SUMMARY:Blue Wahoos @ Braves
DESCRIPTION:Blue Wahoos @ Braves\n\nFollow on MiLB First Pitch: https://stza.co/+vLST-1W\n\nShop: https://stza.co/+vLST-1$\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144550Z
LAST-MODIFIED:20180213T144550Z
TRANSP:OPAQUE
END:VEVENT
* Blue Wahoos @ Braves
<2018-07-13 Fri 19:00-22:00>
:PROPERTIES:
:ID:       vUV77YnrvEp-FB2p5tn1Kv-V@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Blue Wahoos @ Braves Blue Wahoos @ Braves

Follow on MiLB First Pitch  https //stza.co/+vLSU-1P

Shop  https //stza.co/+vLSU-2K

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Blue Wahoos @ Braves
END:VALARM
DTSTART:20180714T000000Z
DTEND:20180714T030000Z
UID:vUV77YnrvEp-FB2p5tn1Kv-V@stanza.co
SUMMARY:Blue Wahoos @ Braves
DESCRIPTION:Blue Wahoos @ Braves\n\nFollow on MiLB First Pitch: https://stza.co/+vLSU-1P\n\nShop: https://stza.co/+vLSU-2K\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144550Z
LAST-MODIFIED:20180213T144550Z
TRANSP:OPAQUE
END:VEVENT
* Blue Wahoos @ Braves
<2018-07-14 Sat 18:00-21:00>
:PROPERTIES:
:ID:       fYchZKpTJNtUEVAU0UMHmZGl@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Blue Wahoos @ Braves Blue Wahoos @ Braves

Follow on MiLB First Pitch  https //stza.co/+vLSV-3J

Shop  https //stza.co/+vLSV-2D

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Blue Wahoos @ Braves
END:VALARM
DTSTART:20180714T230000Z
DTEND:20180715T020000Z
UID:fYchZKpTJNtUEVAU0UMHmZGl@stanza.co
SUMMARY:Blue Wahoos @ Braves
DESCRIPTION:Blue Wahoos @ Braves\n\nFollow on MiLB First Pitch: https://stza.co/+vLSV-3J\n\nShop: https://stza.co/+vLSV-2D\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144550Z
LAST-MODIFIED:20180213T144550Z
TRANSP:OPAQUE
END:VEVENT
* Blue Wahoos @ Braves
<2018-07-15 Sun 17:00-20:00>
:PROPERTIES:
:ID:       ER2LH7os0na7Puih46rqJJPS@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Blue Wahoos @ Braves Blue Wahoos @ Braves

Follow on MiLB First Pitch  https //stza.co/+vLSW-3w

Shop  https //stza.co/+vLSW-3h

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Blue Wahoos @ Braves
END:VALARM
DTSTART:20180715T220000Z
DTEND:20180716T010000Z
UID:ER2LH7os0na7Puih46rqJJPS@stanza.co
SUMMARY:Blue Wahoos @ Braves
DESCRIPTION:Blue Wahoos @ Braves\n\nFollow on MiLB First Pitch: https://stza.co/+vLSW-3w\n\nShop: https://stza.co/+vLSW-3h\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144550Z
LAST-MODIFIED:20180213T144550Z
TRANSP:OPAQUE
END:VEVENT
* Blue Wahoos @ Braves
<2018-07-16 Mon 19:00-22:00>
:PROPERTIES:
:ID:       o4r7RwUilXSm7BQVs-DU7ETc@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Blue Wahoos @ Braves Blue Wahoos @ Braves

Follow on MiLB First Pitch  https //stza.co/+vLSX-3t

Shop  https //stza.co/+vLSX-3E

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Blue Wahoos @ Braves
END:VALARM
DTSTART:20180717T000000Z
DTEND:20180717T030000Z
UID:o4r7RwUilXSm7BQVs-DU7ETc@stanza.co
SUMMARY:Blue Wahoos @ Braves
DESCRIPTION:Blue Wahoos @ Braves\n\nFollow on MiLB First Pitch: https://stza.co/+vLSX-3t\n\nShop: https://stza.co/+vLSX-3E\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144550Z
LAST-MODIFIED:20180213T144550Z
TRANSP:OPAQUE
END:VEVENT
* Blue Wahoos vs. Jumbo Shrimp
<2018-07-18 Wed 18:35-21:35>
:PROPERTIES:
:ID:       H9exvoC1LOLRgHeH-X1eS9-s@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Blue Wahoos vs. Jumbo Shrimp Blue Wahoos vs. Jumbo Shrimp

Follow on MiLB First Pitch  https //stza.co/+wxbm-2u

Shop  https //stza.co/+wxbm-14

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Blue Wahoos vs. Jumbo Shrimp
END:VALARM
DTSTART:20180718T233500Z
DTEND:20180719T023500Z
UID:H9exvoC1LOLRgHeH-X1eS9-s@stanza.co
SUMMARY:Blue Wahoos vs. Jumbo Shrimp
DESCRIPTION:Blue Wahoos vs. Jumbo Shrimp\n\nFollow on MiLB First Pitch: https://stza.co/+wxbm-2u\n\nShop: https://stza.co/+wxbm-14\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144550Z
LAST-MODIFIED:20180213T144550Z
TRANSP:OPAQUE
END:VEVENT
* Blue Wahoos vs. Jumbo Shrimp
<2018-07-19 Thu 18:35-21:35>
:PROPERTIES:
:ID:       ZHMPOF7DKnsNJ9tgvTUrNxY2@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Blue Wahoos vs. Jumbo Shrimp Blue Wahoos vs. Jumbo Shrimp

Follow on MiLB First Pitch  https //stza.co/+wxbo-1s

Shop  https //stza.co/+wxbo-x

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Blue Wahoos vs. Jumbo Shrimp
END:VALARM
DTSTART:20180719T233500Z
DTEND:20180720T023500Z
UID:ZHMPOF7DKnsNJ9tgvTUrNxY2@stanza.co
SUMMARY:Blue Wahoos vs. Jumbo Shrimp
DESCRIPTION:Blue Wahoos vs. Jumbo Shrimp\n\nFollow on MiLB First Pitch: https://stza.co/+wxbo-1s\n\nShop: https://stza.co/+wxbo-x\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144550Z
LAST-MODIFIED:20180213T144550Z
TRANSP:OPAQUE
END:VEVENT
* Blue Wahoos vs. Jumbo Shrimp
<2018-07-20 Fri 18:35-21:35>
:PROPERTIES:
:ID:       KybM_ryXzDITjWnYjxvKuG-T@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Blue Wahoos vs. Jumbo Shrimp Blue Wahoos vs. Jumbo Shrimp

Follow on MiLB First Pitch  https //stza.co/+wxbr-2u

Shop  https //stza.co/+wxbr-1u

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Blue Wahoos vs. Jumbo Shrimp
END:VALARM
DTSTART:20180720T233500Z
DTEND:20180721T023500Z
UID:KybM_ryXzDITjWnYjxvKuG-T@stanza.co
SUMMARY:Blue Wahoos vs. Jumbo Shrimp
DESCRIPTION:Blue Wahoos vs. Jumbo Shrimp\n\nFollow on MiLB First Pitch: https://stza.co/+wxbr-2u\n\nShop: https://stza.co/+wxbr-1u\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144550Z
LAST-MODIFIED:20180213T144550Z
TRANSP:OPAQUE
END:VEVENT
* Blue Wahoos vs. Jumbo Shrimp
<2018-07-21 Sat 18:05-21:05>
:PROPERTIES:
:ID:       wQbOQUHYbCyO0wpVrJ7hpKg_@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Blue Wahoos vs. Jumbo Shrimp Blue Wahoos vs. Jumbo Shrimp

Follow on MiLB First Pitch  https //stza.co/+wxbu-3P

Shop  https //stza.co/+wxbu-3t

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Blue Wahoos vs. Jumbo Shrimp
END:VALARM
DTSTART:20180721T230500Z
DTEND:20180722T020500Z
UID:wQbOQUHYbCyO0wpVrJ7hpKg_@stanza.co
SUMMARY:Blue Wahoos vs. Jumbo Shrimp
DESCRIPTION:Blue Wahoos vs. Jumbo Shrimp\n\nFollow on MiLB First Pitch: https://stza.co/+wxbu-3P\n\nShop: https://stza.co/+wxbu-3t\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144550Z
LAST-MODIFIED:20180213T144550Z
TRANSP:OPAQUE
END:VEVENT
* Blue Wahoos vs. Jumbo Shrimp
<2018-07-22 Sun 17:05-20:05>
:PROPERTIES:
:ID:       zwtGZcjkL8LIitSXYmEdosKl@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Blue Wahoos vs. Jumbo Shrimp Blue Wahoos vs. Jumbo Shrimp

Follow on MiLB First Pitch  https //stza.co/+wxbw-2q

Shop  https //stza.co/+wxbw-2K

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Blue Wahoos vs. Jumbo Shrimp
END:VALARM
DTSTART:20180722T220500Z
DTEND:20180723T010500Z
UID:zwtGZcjkL8LIitSXYmEdosKl@stanza.co
SUMMARY:Blue Wahoos vs. Jumbo Shrimp
DESCRIPTION:Blue Wahoos vs. Jumbo Shrimp\n\nFollow on MiLB First Pitch: https://stza.co/+wxbw-2q\n\nShop: https://stza.co/+wxbw-2K\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144550Z
LAST-MODIFIED:20180213T144550Z
TRANSP:OPAQUE
END:VEVENT
* Blue Wahoos @ Lookouts
<2018-07-23 Mon 18:15-21:15>
:PROPERTIES:
:ID:       TSlNCgeBT5CKREyb5FGUlUHI@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Blue Wahoos @ Lookouts Blue Wahoos @ Lookouts

Follow on MiLB First Pitch  https //stza.co/+wKG9-2N

Shop  https //stza.co/+wKG9-3m

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Blue Wahoos @ Lookouts
END:VALARM
DTSTART:20180723T231500Z
DTEND:20180724T021500Z
UID:TSlNCgeBT5CKREyb5FGUlUHI@stanza.co
SUMMARY:Blue Wahoos @ Lookouts
DESCRIPTION:Blue Wahoos @ Lookouts\n\nFollow on MiLB First Pitch: https://stza.co/+wKG9-2N\n\nShop: https://stza.co/+wKG9-3m\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144550Z
LAST-MODIFIED:20180213T144550Z
TRANSP:OPAQUE
END:VEVENT
* Blue Wahoos @ Lookouts
<2018-07-24 Tue 18:15-21:15>
:PROPERTIES:
:ID:       Yv7tyZEiYfl1csT2EByo40Hi@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Blue Wahoos @ Lookouts Blue Wahoos @ Lookouts

Follow on MiLB First Pitch  https //stza.co/+wKGa-2_

Shop  https //stza.co/+wKGa-1w

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Blue Wahoos @ Lookouts
END:VALARM
DTSTART:20180724T231500Z
DTEND:20180725T021500Z
UID:Yv7tyZEiYfl1csT2EByo40Hi@stanza.co
SUMMARY:Blue Wahoos @ Lookouts
DESCRIPTION:Blue Wahoos @ Lookouts\n\nFollow on MiLB First Pitch: https://stza.co/+wKGa-2_\n\nShop: https://stza.co/+wKGa-1w\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144550Z
LAST-MODIFIED:20180213T144550Z
TRANSP:OPAQUE
END:VEVENT
* Blue Wahoos @ Lookouts
<2018-07-25 Wed 10:15-13:15>
:PROPERTIES:
:ID:       lJTBLVyNk7CrO4Ong5iI3vaR@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Blue Wahoos @ Lookouts Blue Wahoos @ Lookouts

Follow on MiLB First Pitch  https //stza.co/+wKGb-2f

Shop  https //stza.co/+wKGb-E

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Blue Wahoos @ Lookouts
END:VALARM
DTSTART:20180725T151500Z
DTEND:20180725T181500Z
UID:lJTBLVyNk7CrO4Ong5iI3vaR@stanza.co
SUMMARY:Blue Wahoos @ Lookouts
DESCRIPTION:Blue Wahoos @ Lookouts\n\nFollow on MiLB First Pitch: https://stza.co/+wKGb-2f\n\nShop: https://stza.co/+wKGb-E\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144550Z
LAST-MODIFIED:20180213T144550Z
TRANSP:OPAQUE
END:VEVENT
* Blue Wahoos @ Lookouts
<2018-07-26 Thu 18:15-21:15>
:PROPERTIES:
:ID:       e77HIvYMo91bYyZxbqHax848@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Blue Wahoos @ Lookouts Blue Wahoos @ Lookouts

Follow on MiLB First Pitch  https //stza.co/+wKGc-1G

Shop  https //stza.co/+wKGc-1v

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Blue Wahoos @ Lookouts
END:VALARM
DTSTART:20180726T231500Z
DTEND:20180727T021500Z
UID:e77HIvYMo91bYyZxbqHax848@stanza.co
SUMMARY:Blue Wahoos @ Lookouts
DESCRIPTION:Blue Wahoos @ Lookouts\n\nFollow on MiLB First Pitch: https://stza.co/+wKGc-1G\n\nShop: https://stza.co/+wKGc-1v\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144550Z
LAST-MODIFIED:20180213T144550Z
TRANSP:OPAQUE
END:VEVENT
* Blue Wahoos @ Lookouts
<2018-07-27 Fri 18:15-21:15>
:PROPERTIES:
:ID:       1_1vgb5xZrEg2mPZCG7K7s9X@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Blue Wahoos @ Lookouts Blue Wahoos @ Lookouts

Follow on MiLB First Pitch  https //stza.co/+wKGd-2L

Shop  https //stza.co/+wKGd-2$

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Blue Wahoos @ Lookouts
END:VALARM
DTSTART:20180727T231500Z
DTEND:20180728T021500Z
UID:1_1vgb5xZrEg2mPZCG7K7s9X@stanza.co
SUMMARY:Blue Wahoos @ Lookouts
DESCRIPTION:Blue Wahoos @ Lookouts\n\nFollow on MiLB First Pitch: https://stza.co/+wKGd-2L\n\nShop: https://stza.co/+wKGd-2$\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144550Z
LAST-MODIFIED:20180213T144550Z
TRANSP:OPAQUE
END:VEVENT
* Blue Wahoos vs. Shuckers
<2018-07-28 Sat 18:05-21:05>
:PROPERTIES:
:ID:       k3uDSjJ2b0amnPHP-j92sXKe@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Blue Wahoos vs. Shuckers Blue Wahoos vs. Shuckers

Follow on MiLB First Pitch  https //stza.co/+wxbx-3f

Shop  https //stza.co/+wxbx-2Z

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Blue Wahoos vs. Shuckers
END:VALARM
DTSTART:20180728T230500Z
DTEND:20180729T020500Z
UID:k3uDSjJ2b0amnPHP-j92sXKe@stanza.co
SUMMARY:Blue Wahoos vs. Shuckers
DESCRIPTION:Blue Wahoos vs. Shuckers\n\nFollow on MiLB First Pitch: https://stza.co/+wxbx-3f\n\nShop: https://stza.co/+wxbx-2Z\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144550Z
LAST-MODIFIED:20180213T144550Z
TRANSP:OPAQUE
END:VEVENT
* Blue Wahoos vs. Shuckers
<2018-07-29 Sun 17:05-20:05>
:PROPERTIES:
:ID:       ufD4pD7MdvqhIxxlHKi2ZF5K@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Blue Wahoos vs. Shuckers Blue Wahoos vs. Shuckers

Follow on MiLB First Pitch  https //stza.co/+wxbz-2A

Shop  https //stza.co/+wxbz-d

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Blue Wahoos vs. Shuckers
END:VALARM
DTSTART:20180729T220500Z
DTEND:20180730T010500Z
UID:ufD4pD7MdvqhIxxlHKi2ZF5K@stanza.co
SUMMARY:Blue Wahoos vs. Shuckers
DESCRIPTION:Blue Wahoos vs. Shuckers\n\nFollow on MiLB First Pitch: https://stza.co/+wxbz-2A\n\nShop: https://stza.co/+wxbz-d\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144550Z
LAST-MODIFIED:20180213T144550Z
TRANSP:OPAQUE
END:VEVENT
* Blue Wahoos vs. Shuckers
<2018-07-30 Mon 18:35-21:35>
:PROPERTIES:
:ID:       XCpVro3Nntu92JGOZfgg2WrX@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Blue Wahoos vs. Shuckers Blue Wahoos vs. Shuckers

Follow on MiLB First Pitch  https //stza.co/+wxbB-2b

Shop  https //stza.co/+wxbB-3Q

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Blue Wahoos vs. Shuckers
END:VALARM
DTSTART:20180730T233500Z
DTEND:20180731T023500Z
UID:XCpVro3Nntu92JGOZfgg2WrX@stanza.co
SUMMARY:Blue Wahoos vs. Shuckers
DESCRIPTION:Blue Wahoos vs. Shuckers\n\nFollow on MiLB First Pitch: https://stza.co/+wxbB-2b\n\nShop: https://stza.co/+wxbB-3Q\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144550Z
LAST-MODIFIED:20180213T144550Z
TRANSP:OPAQUE
END:VEVENT
* Blue Wahoos vs. Shuckers
<2018-07-31 Tue 18:35-21:35>
:PROPERTIES:
:ID:       xR3VzS8LyzOvf1DMjIwKetpf@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Blue Wahoos vs. Shuckers Blue Wahoos vs. Shuckers

Follow on MiLB First Pitch  https //stza.co/+wxbE-2z

Shop  https //stza.co/+wxbE-29

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Blue Wahoos vs. Shuckers
END:VALARM
DTSTART:20180731T233500Z
DTEND:20180801T023500Z
UID:xR3VzS8LyzOvf1DMjIwKetpf@stanza.co
SUMMARY:Blue Wahoos vs. Shuckers
DESCRIPTION:Blue Wahoos vs. Shuckers\n\nFollow on MiLB First Pitch: https://stza.co/+wxbE-2z\n\nShop: https://stza.co/+wxbE-29\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144550Z
LAST-MODIFIED:20180213T144550Z
TRANSP:OPAQUE
END:VEVENT
* Blue Wahoos vs. Shuckers
<2018-08-01 Wed 18:35-21:35>
:PROPERTIES:
:ID:       fa3p-UUfrmC1HkElGtQYmcq5@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Blue Wahoos vs. Shuckers Blue Wahoos vs. Shuckers

Follow on MiLB First Pitch  https //stza.co/+wxbG-2B

Shop  https //stza.co/+wxbG-1f

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Blue Wahoos vs. Shuckers
END:VALARM
DTSTART:20180801T233500Z
DTEND:20180802T023500Z
UID:fa3p-UUfrmC1HkElGtQYmcq5@stanza.co
SUMMARY:Blue Wahoos vs. Shuckers
DESCRIPTION:Blue Wahoos vs. Shuckers\n\nFollow on MiLB First Pitch: https://stza.co/+wxbG-2B\n\nShop: https://stza.co/+wxbG-1f\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144550Z
LAST-MODIFIED:20180213T144550Z
TRANSP:OPAQUE
END:VEVENT
* Blue Wahoos vs. Biscuits
<2018-08-02 Thu 18:35-21:35>
:PROPERTIES:
:ID:       tW2SYT9HQeDp_WF96Jg0Aitp@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Blue Wahoos vs. Biscuits Blue Wahoos vs. Biscuits

Follow on MiLB First Pitch  https //stza.co/+wxbI-1d

Shop  https //stza.co/+wxbI-3G

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Blue Wahoos vs. Biscuits
END:VALARM
DTSTART:20180802T233500Z
DTEND:20180803T023500Z
UID:tW2SYT9HQeDp_WF96Jg0Aitp@stanza.co
SUMMARY:Blue Wahoos vs. Biscuits
DESCRIPTION:Blue Wahoos vs. Biscuits\n\nFollow on MiLB First Pitch: https://stza.co/+wxbI-1d\n\nShop: https://stza.co/+wxbI-3G\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144550Z
LAST-MODIFIED:20180213T144550Z
TRANSP:OPAQUE
END:VEVENT
* Blue Wahoos vs. Biscuits
<2018-08-03 Fri 18:35-21:35>
:PROPERTIES:
:ID:       RGdMDSpnky_hxAc_nqDn1B-j@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Blue Wahoos vs. Biscuits Blue Wahoos vs. Biscuits

Follow on MiLB First Pitch  https //stza.co/+wxbJ-2k

Shop  https //stza.co/+wxbJ-2I

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Blue Wahoos vs. Biscuits
END:VALARM
DTSTART:20180803T233500Z
DTEND:20180804T023500Z
UID:RGdMDSpnky_hxAc_nqDn1B-j@stanza.co
SUMMARY:Blue Wahoos vs. Biscuits
DESCRIPTION:Blue Wahoos vs. Biscuits\n\nFollow on MiLB First Pitch: https://stza.co/+wxbJ-2k\n\nShop: https://stza.co/+wxbJ-2I\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144550Z
LAST-MODIFIED:20180213T144550Z
TRANSP:OPAQUE
END:VEVENT
* Blue Wahoos vs. Biscuits
<2018-08-04 Sat 18:05-21:05>
:PROPERTIES:
:ID:       j3O7KdYPXAOo6JiQOKDFMoR6@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Blue Wahoos vs. Biscuits Blue Wahoos vs. Biscuits

Follow on MiLB First Pitch  https //stza.co/+wxbM-1d

Shop  https //stza.co/+wxbM-1t

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Blue Wahoos vs. Biscuits
END:VALARM
DTSTART:20180804T230500Z
DTEND:20180805T020500Z
UID:j3O7KdYPXAOo6JiQOKDFMoR6@stanza.co
SUMMARY:Blue Wahoos vs. Biscuits
DESCRIPTION:Blue Wahoos vs. Biscuits\n\nFollow on MiLB First Pitch: https://stza.co/+wxbM-1d\n\nShop: https://stza.co/+wxbM-1t\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144550Z
LAST-MODIFIED:20180213T144550Z
TRANSP:OPAQUE
END:VEVENT
* Blue Wahoos vs. Biscuits
<2018-08-05 Sun 17:05-20:05>
:PROPERTIES:
:ID:       FDx3t6xz8fgsPX6UpfLWEZa_@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Blue Wahoos vs. Biscuits Blue Wahoos vs. Biscuits

Follow on MiLB First Pitch  https //stza.co/+wxbO-1l

Shop  https //stza.co/+wxbO-1M

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Blue Wahoos vs. Biscuits
END:VALARM
DTSTART:20180805T220500Z
DTEND:20180806T010500Z
UID:FDx3t6xz8fgsPX6UpfLWEZa_@stanza.co
SUMMARY:Blue Wahoos vs. Biscuits
DESCRIPTION:Blue Wahoos vs. Biscuits\n\nFollow on MiLB First Pitch: https://stza.co/+wxbO-1l\n\nShop: https://stza.co/+wxbO-1M\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144550Z
LAST-MODIFIED:20180213T144550Z
TRANSP:OPAQUE
END:VEVENT
* Blue Wahoos vs. Biscuits
<2018-08-06 Mon 18:35-21:35>
:PROPERTIES:
:ID:       FrfY4Ew8Jy9hAOmiUGgw4oXK@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Blue Wahoos vs. Biscuits Blue Wahoos vs. Biscuits

Follow on MiLB First Pitch  https //stza.co/+wxbQ-3v

Shop  https //stza.co/+wxbQ-f

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Blue Wahoos vs. Biscuits
END:VALARM
DTSTART:20180806T233500Z
DTEND:20180807T023500Z
UID:FrfY4Ew8Jy9hAOmiUGgw4oXK@stanza.co
SUMMARY:Blue Wahoos vs. Biscuits
DESCRIPTION:Blue Wahoos vs. Biscuits\n\nFollow on MiLB First Pitch: https://stza.co/+wxbQ-3v\n\nShop: https://stza.co/+wxbQ-f\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144550Z
LAST-MODIFIED:20180213T144550Z
TRANSP:OPAQUE
END:VEVENT
* Blue Wahoos @ BayBears
<2018-08-08 Wed 18:35-21:35>
:PROPERTIES:
:ID:       ciX7NVX65bgh6wnjvBjBxkml@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Blue Wahoos @ BayBears Blue Wahoos @ BayBears

Follow on MiLB First Pitch  https //stza.co/+v$Sr-N

Shop  https //stza.co/+v$Sr-1V

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Blue Wahoos @ BayBears
END:VALARM
DTSTART:20180808T233500Z
DTEND:20180809T023500Z
UID:ciX7NVX65bgh6wnjvBjBxkml@stanza.co
SUMMARY:Blue Wahoos @ BayBears
DESCRIPTION:Blue Wahoos @ BayBears\n\nFollow on MiLB First Pitch: https://stza.co/+v$Sr-N\n\nShop: https://stza.co/+v$Sr-1V\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144550Z
LAST-MODIFIED:20180213T144550Z
TRANSP:OPAQUE
END:VEVENT
* Blue Wahoos @ BayBears
<2018-08-09 Thu 18:35-21:35>
:PROPERTIES:
:ID:       qULmh_XcSHITNfiF6l2AGrSh@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Blue Wahoos @ BayBears Blue Wahoos @ BayBears

Follow on MiLB First Pitch  https //stza.co/+v$Ss-1h

Shop  https //stza.co/+v$Ss-2A

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Blue Wahoos @ BayBears
END:VALARM
DTSTART:20180809T233500Z
DTEND:20180810T023500Z
UID:qULmh_XcSHITNfiF6l2AGrSh@stanza.co
SUMMARY:Blue Wahoos @ BayBears
DESCRIPTION:Blue Wahoos @ BayBears\n\nFollow on MiLB First Pitch: https://stza.co/+v$Ss-1h\n\nShop: https://stza.co/+v$Ss-2A\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144550Z
LAST-MODIFIED:20180213T144550Z
TRANSP:OPAQUE
END:VEVENT
* Blue Wahoos @ BayBears
<2018-08-10 Fri 19:05-22:05>
:PROPERTIES:
:ID:       Rm3bWWD8E8BaTE4wCpoQsr8t@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Blue Wahoos @ BayBears Blue Wahoos @ BayBears

Follow on MiLB First Pitch  https //stza.co/+v$St-3U

Shop  https //stza.co/+v$St-3K

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Blue Wahoos @ BayBears
END:VALARM
DTSTART:20180811T000500Z
DTEND:20180811T030500Z
UID:Rm3bWWD8E8BaTE4wCpoQsr8t@stanza.co
SUMMARY:Blue Wahoos @ BayBears
DESCRIPTION:Blue Wahoos @ BayBears\n\nFollow on MiLB First Pitch: https://stza.co/+v$St-3U\n\nShop: https://stza.co/+v$St-3K\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144550Z
LAST-MODIFIED:20180213T144550Z
TRANSP:OPAQUE
END:VEVENT
* Blue Wahoos @ BayBears
<2018-08-11 Sat 19:05-22:05>
:PROPERTIES:
:ID:       j6B39Kg0nJkseFI2WyLPXILZ@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Blue Wahoos @ BayBears Blue Wahoos @ BayBears

Follow on MiLB First Pitch  https //stza.co/+v$Su-3I

Shop  https //stza.co/+v$Su-32

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Blue Wahoos @ BayBears
END:VALARM
DTSTART:20180812T000500Z
DTEND:20180812T030500Z
UID:j6B39Kg0nJkseFI2WyLPXILZ@stanza.co
SUMMARY:Blue Wahoos @ BayBears
DESCRIPTION:Blue Wahoos @ BayBears\n\nFollow on MiLB First Pitch: https://stza.co/+v$Su-3I\n\nShop: https://stza.co/+v$Su-32\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144550Z
LAST-MODIFIED:20180213T144550Z
TRANSP:OPAQUE
END:VEVENT
* Blue Wahoos @ BayBears
<2018-08-12 Sun 17:05-20:05>
:PROPERTIES:
:ID:       A4vebSOG8joKMpfUP3Tfe7C1@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Blue Wahoos @ BayBears Blue Wahoos @ BayBears

Follow on MiLB First Pitch  https //stza.co/+v$Sv-3W

Shop  https //stza.co/+v$Sv-u

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Blue Wahoos @ BayBears
END:VALARM
DTSTART:20180812T220500Z
DTEND:20180813T010500Z
UID:A4vebSOG8joKMpfUP3Tfe7C1@stanza.co
SUMMARY:Blue Wahoos @ BayBears
DESCRIPTION:Blue Wahoos @ BayBears\n\nFollow on MiLB First Pitch: https://stza.co/+v$Sv-3W\n\nShop: https://stza.co/+v$Sv-u\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144550Z
LAST-MODIFIED:20180213T144550Z
TRANSP:OPAQUE
END:VEVENT
* Blue Wahoos vs. Jumbo Shrimp
<2018-08-14 Tue 18:35-21:35>
:PROPERTIES:
:ID:       jz2Ja8N0xqe9_THs4RRV_W8e@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Blue Wahoos vs. Jumbo Shrimp Blue Wahoos vs. Jumbo Shrimp

Follow on MiLB First Pitch  https //stza.co/+wxbS-x

Shop  https //stza.co/+wxbS-3K

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Blue Wahoos vs. Jumbo Shrimp
END:VALARM
DTSTART:20180814T233500Z
DTEND:20180815T023500Z
UID:jz2Ja8N0xqe9_THs4RRV_W8e@stanza.co
SUMMARY:Blue Wahoos vs. Jumbo Shrimp
DESCRIPTION:Blue Wahoos vs. Jumbo Shrimp\n\nFollow on MiLB First Pitch: https://stza.co/+wxbS-x\n\nShop: https://stza.co/+wxbS-3K\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144550Z
LAST-MODIFIED:20180213T144550Z
TRANSP:OPAQUE
END:VEVENT
* Blue Wahoos vs. Jumbo Shrimp
<2018-08-15 Wed 18:35-21:35>
:PROPERTIES:
:ID:       B89Yhmr4baqubyYyFyE6eV2c@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Blue Wahoos vs. Jumbo Shrimp Blue Wahoos vs. Jumbo Shrimp

Follow on MiLB First Pitch  https //stza.co/+wxbT-X

Shop  https //stza.co/+wxbT-2_

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Blue Wahoos vs. Jumbo Shrimp
END:VALARM
DTSTART:20180815T233500Z
DTEND:20180816T023500Z
UID:B89Yhmr4baqubyYyFyE6eV2c@stanza.co
SUMMARY:Blue Wahoos vs. Jumbo Shrimp
DESCRIPTION:Blue Wahoos vs. Jumbo Shrimp\n\nFollow on MiLB First Pitch: https://stza.co/+wxbT-X\n\nShop: https://stza.co/+wxbT-2_\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144550Z
LAST-MODIFIED:20180213T144550Z
TRANSP:OPAQUE
END:VEVENT
* Blue Wahoos vs. Jumbo Shrimp
<2018-08-16 Thu 18:35-21:35>
:PROPERTIES:
:ID:       _viEgVlIhyVdPKN2smme4cgS@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Blue Wahoos vs. Jumbo Shrimp Blue Wahoos vs. Jumbo Shrimp

Follow on MiLB First Pitch  https //stza.co/+wxbW-1Q

Shop  https //stza.co/+wxbW-2o

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Blue Wahoos vs. Jumbo Shrimp
END:VALARM
DTSTART:20180816T233500Z
DTEND:20180817T023500Z
UID:_viEgVlIhyVdPKN2smme4cgS@stanza.co
SUMMARY:Blue Wahoos vs. Jumbo Shrimp
DESCRIPTION:Blue Wahoos vs. Jumbo Shrimp\n\nFollow on MiLB First Pitch: https://stza.co/+wxbW-1Q\n\nShop: https://stza.co/+wxbW-2o\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144550Z
LAST-MODIFIED:20180213T144550Z
TRANSP:OPAQUE
END:VEVENT
* Blue Wahoos vs. Jumbo Shrimp
<2018-08-17 Fri 18:35-21:35>
:PROPERTIES:
:ID:       MF7a96q4MJ12vuV4_JbOEUlZ@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Blue Wahoos vs. Jumbo Shrimp Blue Wahoos vs. Jumbo Shrimp

Follow on MiLB First Pitch  https //stza.co/+wxbY-2s

Shop  https //stza.co/+wxbY-1u

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Blue Wahoos vs. Jumbo Shrimp
END:VALARM
DTSTART:20180817T233500Z
DTEND:20180818T023500Z
UID:MF7a96q4MJ12vuV4_JbOEUlZ@stanza.co
SUMMARY:Blue Wahoos vs. Jumbo Shrimp
DESCRIPTION:Blue Wahoos vs. Jumbo Shrimp\n\nFollow on MiLB First Pitch: https://stza.co/+wxbY-2s\n\nShop: https://stza.co/+wxbY-1u\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144550Z
LAST-MODIFIED:20180213T144550Z
TRANSP:OPAQUE
END:VEVENT
* Blue Wahoos vs. Jumbo Shrimp
<2018-08-18 Sat 18:05-21:05>
:PROPERTIES:
:ID:       kX0nu6Kuta6DivUZfGWxJ61t@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Blue Wahoos vs. Jumbo Shrimp Blue Wahoos vs. Jumbo Shrimp

Follow on MiLB First Pitch  https //stza.co/+wxb$-2h

Shop  https //stza.co/+wxb$-V

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Blue Wahoos vs. Jumbo Shrimp
END:VALARM
DTSTART:20180818T230500Z
DTEND:20180819T020500Z
UID:kX0nu6Kuta6DivUZfGWxJ61t@stanza.co
SUMMARY:Blue Wahoos vs. Jumbo Shrimp
DESCRIPTION:Blue Wahoos vs. Jumbo Shrimp\n\nFollow on MiLB First Pitch: https://stza.co/+wxb$-2h\n\nShop: https://stza.co/+wxb$-V\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144550Z
LAST-MODIFIED:20180213T144550Z
TRANSP:OPAQUE
END:VEVENT
* Blue Wahoos @ Shuckers
<2018-08-19 Sun 16:05-19:05>
:PROPERTIES:
:ID:       DVJPHSc1Lo-a7xjDLwYHgfzo@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Blue Wahoos @ Shuckers Blue Wahoos @ Shuckers

Follow on MiLB First Pitch  https //stza.co/+vLSe-13

Shop  https //stza.co/+vLSe-3Z

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Blue Wahoos @ Shuckers
END:VALARM
DTSTART:20180819T210500Z
DTEND:20180820T000500Z
UID:DVJPHSc1Lo-a7xjDLwYHgfzo@stanza.co
SUMMARY:Blue Wahoos @ Shuckers
DESCRIPTION:Blue Wahoos @ Shuckers\n\nFollow on MiLB First Pitch: https://stza.co/+vLSe-13\n\nShop: https://stza.co/+vLSe-3Z\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144550Z
LAST-MODIFIED:20180213T144550Z
TRANSP:OPAQUE
END:VEVENT
* Blue Wahoos @ Shuckers
<2018-08-20 Mon 18:35-21:35>
:PROPERTIES:
:ID:       Gum_l1-zlc7Pebq3kuxZ0lln@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Blue Wahoos @ Shuckers Blue Wahoos @ Shuckers

Follow on MiLB First Pitch  https //stza.co/+vLSf-2

Shop  https //stza.co/+vLSf-f

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Blue Wahoos @ Shuckers
END:VALARM
DTSTART:20180820T233500Z
DTEND:20180821T023500Z
UID:Gum_l1-zlc7Pebq3kuxZ0lln@stanza.co
SUMMARY:Blue Wahoos @ Shuckers
DESCRIPTION:Blue Wahoos @ Shuckers\n\nFollow on MiLB First Pitch: https://stza.co/+vLSf-2\n\nShop: https://stza.co/+vLSf-f\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144550Z
LAST-MODIFIED:20180213T144550Z
TRANSP:OPAQUE
END:VEVENT
* Blue Wahoos @ Shuckers
<2018-08-21 Tue 10:35-13:35>
:PROPERTIES:
:ID:       mMOhhrq5oh1ngRcatEVbaCP8@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Blue Wahoos @ Shuckers Blue Wahoos @ Shuckers

Follow on MiLB First Pitch  https //stza.co/+vLSg-3V

Shop  https //stza.co/+vLSg-3t

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Blue Wahoos @ Shuckers
END:VALARM
DTSTART:20180821T153500Z
DTEND:20180821T183500Z
UID:mMOhhrq5oh1ngRcatEVbaCP8@stanza.co
SUMMARY:Blue Wahoos @ Shuckers
DESCRIPTION:Blue Wahoos @ Shuckers\n\nFollow on MiLB First Pitch: https://stza.co/+vLSg-3V\n\nShop: https://stza.co/+vLSg-3t\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144550Z
LAST-MODIFIED:20180213T144550Z
TRANSP:OPAQUE
END:VEVENT
* Blue Wahoos @ Shuckers
<2018-08-22 Wed 18:35-21:35>
:PROPERTIES:
:ID:       a2C4VczdGaTfmAzqndscXAGL@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Blue Wahoos @ Shuckers Blue Wahoos @ Shuckers

Follow on MiLB First Pitch  https //stza.co/+vLSh-F

Shop  https //stza.co/+vLSh-L

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Blue Wahoos @ Shuckers
END:VALARM
DTSTART:20180822T233500Z
DTEND:20180823T023500Z
UID:a2C4VczdGaTfmAzqndscXAGL@stanza.co
SUMMARY:Blue Wahoos @ Shuckers
DESCRIPTION:Blue Wahoos @ Shuckers\n\nFollow on MiLB First Pitch: https://stza.co/+vLSh-F\n\nShop: https://stza.co/+vLSh-L\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144550Z
LAST-MODIFIED:20180213T144550Z
TRANSP:OPAQUE
END:VEVENT
* Blue Wahoos @ Shuckers
<2018-08-23 Thu 18:35-21:35>
:PROPERTIES:
:ID:       l9G1QJ2PQZjT48rVmFQEazC-@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Blue Wahoos @ Shuckers Blue Wahoos @ Shuckers

Follow on MiLB First Pitch  https //stza.co/+vLSi-3y

Shop  https //stza.co/+vLSi-2L

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Blue Wahoos @ Shuckers
END:VALARM
DTSTART:20180823T233500Z
DTEND:20180824T023500Z
UID:l9G1QJ2PQZjT48rVmFQEazC-@stanza.co
SUMMARY:Blue Wahoos @ Shuckers
DESCRIPTION:Blue Wahoos @ Shuckers\n\nFollow on MiLB First Pitch: https://stza.co/+vLSi-3y\n\nShop: https://stza.co/+vLSi-2L\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144550Z
LAST-MODIFIED:20180213T144550Z
TRANSP:OPAQUE
END:VEVENT
* Blue Wahoos vs. BayBears
<2018-08-24 Fri 18:35-21:35>
:PROPERTIES:
:ID:       767ILMR6zfejo1JRYOcEGZcs@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Blue Wahoos vs. BayBears Blue Wahoos vs. BayBears

Follow on MiLB First Pitch  https //stza.co/+wxc0-3j

Shop  https //stza.co/+wxc0-24

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Blue Wahoos vs. BayBears
END:VALARM
DTSTART:20180824T233500Z
DTEND:20180825T023500Z
UID:767ILMR6zfejo1JRYOcEGZcs@stanza.co
SUMMARY:Blue Wahoos vs. BayBears
DESCRIPTION:Blue Wahoos vs. BayBears\n\nFollow on MiLB First Pitch: https://stza.co/+wxc0-3j\n\nShop: https://stza.co/+wxc0-24\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144550Z
LAST-MODIFIED:20180213T144550Z
TRANSP:OPAQUE
END:VEVENT
* Blue Wahoos vs. BayBears
<2018-08-25 Sat 18:05-21:05>
:PROPERTIES:
:ID:       8TZwBm80M81gFOJVuy5sZAhc@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Blue Wahoos vs. BayBears Blue Wahoos vs. BayBears

Follow on MiLB First Pitch  https //stza.co/+wxc2-c

Shop  https //stza.co/+wxc2-3a

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Blue Wahoos vs. BayBears
END:VALARM
DTSTART:20180825T230500Z
DTEND:20180826T020500Z
UID:8TZwBm80M81gFOJVuy5sZAhc@stanza.co
SUMMARY:Blue Wahoos vs. BayBears
DESCRIPTION:Blue Wahoos vs. BayBears\n\nFollow on MiLB First Pitch: https://stza.co/+wxc2-c\n\nShop: https://stza.co/+wxc2-3a\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144550Z
LAST-MODIFIED:20180213T144550Z
TRANSP:OPAQUE
END:VEVENT
* Blue Wahoos vs. BayBears
<2018-08-26 Sun 17:05-20:05>
:PROPERTIES:
:ID:       XU4XCfCDeAuQAm71AdkmrvDg@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Blue Wahoos vs. BayBears Blue Wahoos vs. BayBears

Follow on MiLB First Pitch  https //stza.co/+wxc5-3m

Shop  https //stza.co/+wxc5-1A

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Blue Wahoos vs. BayBears
END:VALARM
DTSTART:20180826T220500Z
DTEND:20180827T010500Z
UID:XU4XCfCDeAuQAm71AdkmrvDg@stanza.co
SUMMARY:Blue Wahoos vs. BayBears
DESCRIPTION:Blue Wahoos vs. BayBears\n\nFollow on MiLB First Pitch: https://stza.co/+wxc5-3m\n\nShop: https://stza.co/+wxc5-1A\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144550Z
LAST-MODIFIED:20180213T144550Z
TRANSP:OPAQUE
END:VEVENT
* Blue Wahoos vs. BayBears
<2018-08-27 Mon 18:35-21:35>
:PROPERTIES:
:ID:       xYK2D3QuVAPeCpAQLZ4iF99S@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Blue Wahoos vs. BayBears Blue Wahoos vs. BayBears

Follow on MiLB First Pitch  https //stza.co/+wxc7-2b

Shop  https //stza.co/+wxc7-Z

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Blue Wahoos vs. BayBears
END:VALARM
DTSTART:20180827T233500Z
DTEND:20180828T023500Z
UID:xYK2D3QuVAPeCpAQLZ4iF99S@stanza.co
SUMMARY:Blue Wahoos vs. BayBears
DESCRIPTION:Blue Wahoos vs. BayBears\n\nFollow on MiLB First Pitch: https://stza.co/+wxc7-2b\n\nShop: https://stza.co/+wxc7-Z\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144550Z
LAST-MODIFIED:20180213T144550Z
TRANSP:OPAQUE
END:VEVENT
* Blue Wahoos vs. BayBears
<2018-08-28 Tue 18:35-21:35>
:PROPERTIES:
:ID:       PfgRncPYPB3_QjdiQAE87Owj@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Blue Wahoos vs. BayBears Blue Wahoos vs. BayBears

Follow on MiLB First Pitch  https //stza.co/+wxc9-3W

Shop  https //stza.co/+wxc9-1B

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Blue Wahoos vs. BayBears
END:VALARM
DTSTART:20180828T233500Z
DTEND:20180829T023500Z
UID:PfgRncPYPB3_QjdiQAE87Owj@stanza.co
SUMMARY:Blue Wahoos vs. BayBears
DESCRIPTION:Blue Wahoos vs. BayBears\n\nFollow on MiLB First Pitch: https://stza.co/+wxc9-3W\n\nShop: https://stza.co/+wxc9-1B\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144550Z
LAST-MODIFIED:20180213T144550Z
TRANSP:OPAQUE
END:VEVENT
* Blue Wahoos @ Smokies
<2018-08-30 Thu 18:00-21:00>
:PROPERTIES:
:ID:       2xxAJQTdhTjmcV8owVvU0sLn@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Blue Wahoos @ Smokies Blue Wahoos @ Smokies

Follow on MiLB First Pitch  https //stza.co/+xVTZ-2J

Shop  https //stza.co/+xVTZ-16

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Blue Wahoos @ Smokies
END:VALARM
DTSTART:20180830T230000Z
DTEND:20180831T020000Z
UID:2xxAJQTdhTjmcV8owVvU0sLn@stanza.co
SUMMARY:Blue Wahoos @ Smokies
DESCRIPTION:Blue Wahoos @ Smokies\n\nFollow on MiLB First Pitch: https://stza.co/+xVTZ-2J\n\nShop: https://stza.co/+xVTZ-16\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144550Z
LAST-MODIFIED:20180213T144550Z
TRANSP:OPAQUE
END:VEVENT
* Blue Wahoos @ Smokies
<2018-08-31 Fri 18:00-21:00>
:PROPERTIES:
:ID:       ixbHMLw7yfs5A9zjEmgGtZgs@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Blue Wahoos @ Smokies Blue Wahoos @ Smokies

Follow on MiLB First Pitch  https //stza.co/+xVT_-2R

Shop  https //stza.co/+xVT_-2p

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Blue Wahoos @ Smokies
END:VALARM
DTSTART:20180831T230000Z
DTEND:20180901T020000Z
UID:ixbHMLw7yfs5A9zjEmgGtZgs@stanza.co
SUMMARY:Blue Wahoos @ Smokies
DESCRIPTION:Blue Wahoos @ Smokies\n\nFollow on MiLB First Pitch: https://stza.co/+xVT_-2R\n\nShop: https://stza.co/+xVT_-2p\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144550Z
LAST-MODIFIED:20180213T144550Z
TRANSP:OPAQUE
END:VEVENT
* Blue Wahoos @ Smokies
<2018-09-01 Sat 18:00-21:00>
:PROPERTIES:
:ID:       ReWQbq24kVb0kMJdzwJ7jTX_@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Blue Wahoos @ Smokies Blue Wahoos @ Smokies

Follow on MiLB First Pitch  https //stza.co/+xVT$-2o

Shop  https //stza.co/+xVT$-30

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Blue Wahoos @ Smokies
END:VALARM
DTSTART:20180901T230000Z
DTEND:20180902T020000Z
UID:ReWQbq24kVb0kMJdzwJ7jTX_@stanza.co
SUMMARY:Blue Wahoos @ Smokies
DESCRIPTION:Blue Wahoos @ Smokies\n\nFollow on MiLB First Pitch: https://stza.co/+xVT$-2o\n\nShop: https://stza.co/+xVT$-30\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144550Z
LAST-MODIFIED:20180213T144550Z
TRANSP:OPAQUE
END:VEVENT
* Blue Wahoos @ Smokies
<2018-09-02 Sun 16:30-19:30>
:PROPERTIES:
:ID:       QYADk0OMZx8VtKFox-7nivwh@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Blue Wahoos @ Smokies Blue Wahoos @ Smokies

Follow on MiLB First Pitch  https //stza.co/+xVU0-2W

Shop  https //stza.co/+xVU0-3j

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Blue Wahoos @ Smokies
END:VALARM
DTSTART:20180902T213000Z
DTEND:20180903T003000Z
UID:QYADk0OMZx8VtKFox-7nivwh@stanza.co
SUMMARY:Blue Wahoos @ Smokies
DESCRIPTION:Blue Wahoos @ Smokies\n\nFollow on MiLB First Pitch: https://stza.co/+xVU0-2W\n\nShop: https://stza.co/+xVU0-3j\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144550Z
LAST-MODIFIED:20180213T144550Z
TRANSP:OPAQUE
END:VEVENT
* Blue Wahoos @ Smokies
<2018-09-03 Mon 11:00-14:00>
:PROPERTIES:
:ID:       htc0a1Pa5lFCaJacP9SJ5jtF@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Blue Wahoos @ Smokies Blue Wahoos @ Smokies

Follow on MiLB First Pitch  https //stza.co/+xVU1-z

Shop  https //stza.co/+xVU1-3c

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Blue Wahoos @ Smokies
END:VALARM
DTSTART:20180903T160000Z
DTEND:20180903T190000Z
UID:htc0a1Pa5lFCaJacP9SJ5jtF@stanza.co
SUMMARY:Blue Wahoos @ Smokies
DESCRIPTION:Blue Wahoos @ Smokies\n\nFollow on MiLB First Pitch: https://stza.co/+xVU1-z\n\nShop: https://stza.co/+xVU1-3c\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144550Z
LAST-MODIFIED:20180213T144550Z
TRANSP:OPAQUE
END:VEVENT
