#+TITLE:       Main Google calendar entries
#+AUTHOR:      Eric S Fraga
#+EMAIL:       e.fraga@ucl.ac.uk
#+DESCRIPTION: converted using the ical2org awk script
#+CATEGORY:    google
#+STARTUP:     hidestars
#+STARTUP:     overview

* COMMENT original iCal preamble

* Chiefs @ RailRiders
<2018-04-06 Fri 18:05-21:05>
:PROPERTIES:
:ID:       Jf-e-Hb-_QRfZWnsCl_-W6Y9@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Chiefs @ RailRiders Chiefs @ RailRiders

Follow on MiLB First Pitch  https //stza.co/+vKpb-N

Shop  https //stza.co/+vKpb-3d

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Chiefs @ RailRiders
END:VALARM
DTSTART:20180406T230500Z
DTEND:20180407T020500Z
UID:Jf-e-Hb-_QRfZWnsCl_-W6Y9@stanza.co
SUMMARY:Chiefs @ RailRiders
DESCRIPTION:Chiefs @ RailRiders\n\nFollow on MiLB First Pitch: https://stza.co/+vKpb-N\n\nShop: https://stza.co/+vKpb-3d\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144600Z
LAST-MODIFIED:20180213T144600Z
TRANSP:OPAQUE
END:VEVENT
* Chiefs @ RailRiders
<2018-04-07 Sat 15:05-18:05>
:PROPERTIES:
:ID:       qifNB3NI8ADKeeaETHEJQsv-@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Chiefs @ RailRiders Chiefs @ RailRiders

Follow on MiLB First Pitch  https //stza.co/+vKpc-3j

Shop  https //stza.co/+vKpc-C

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Chiefs @ RailRiders
END:VALARM
DTSTART:20180407T200500Z
DTEND:20180407T230500Z
UID:qifNB3NI8ADKeeaETHEJQsv-@stanza.co
SUMMARY:Chiefs @ RailRiders
DESCRIPTION:Chiefs @ RailRiders\n\nFollow on MiLB First Pitch: https://stza.co/+vKpc-3j\n\nShop: https://stza.co/+vKpc-C\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144600Z
LAST-MODIFIED:20180213T144600Z
TRANSP:OPAQUE
END:VEVENT
* Chiefs @ RailRiders
<2018-04-08 Sun 12:05-15:05>
:PROPERTIES:
:ID:       B9WV3sc0sl0gqtWGWRcR1xYg@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Chiefs @ RailRiders Chiefs @ RailRiders

Follow on MiLB First Pitch  https //stza.co/+vKpd-3V

Shop  https //stza.co/+vKpd-3D

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Chiefs @ RailRiders
END:VALARM
DTSTART:20180408T170500Z
DTEND:20180408T200500Z
UID:B9WV3sc0sl0gqtWGWRcR1xYg@stanza.co
SUMMARY:Chiefs @ RailRiders
DESCRIPTION:Chiefs @ RailRiders\n\nFollow on MiLB First Pitch: https://stza.co/+vKpd-3V\n\nShop: https://stza.co/+vKpd-3D\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144600Z
LAST-MODIFIED:20180213T144600Z
TRANSP:OPAQUE
END:VEVENT
* Chiefs @ Red Wings
<2018-04-09 Mon 17:35-20:35>
:PROPERTIES:
:ID:       vIvF4bmsQf0vrnRbE9Bp9dZV@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Chiefs @ Red Wings Chiefs @ Red Wings

Follow on MiLB First Pitch  https //stza.co/+vKp2-2Y

Shop  https //stza.co/+vKp2-n

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Chiefs @ Red Wings
END:VALARM
DTSTART:20180409T223500Z
DTEND:20180410T013500Z
UID:vIvF4bmsQf0vrnRbE9Bp9dZV@stanza.co
SUMMARY:Chiefs @ Red Wings
DESCRIPTION:Chiefs @ Red Wings\n\nFollow on MiLB First Pitch: https://stza.co/+vKp2-2Y\n\nShop: https://stza.co/+vKp2-n\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144600Z
LAST-MODIFIED:20180213T144600Z
TRANSP:OPAQUE
END:VEVENT
* Chiefs @ Red Wings
<2018-04-10 Tue 17:35-20:35>
:PROPERTIES:
:ID:       mCXR1wXd5VkPKPETwLJTmLIz@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Chiefs @ Red Wings Chiefs @ Red Wings

Follow on MiLB First Pitch  https //stza.co/+vKp3-3k

Shop  https //stza.co/+vKp3-11

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Chiefs @ Red Wings
END:VALARM
DTSTART:20180410T223500Z
DTEND:20180411T013500Z
UID:mCXR1wXd5VkPKPETwLJTmLIz@stanza.co
SUMMARY:Chiefs @ Red Wings
DESCRIPTION:Chiefs @ Red Wings\n\nFollow on MiLB First Pitch: https://stza.co/+vKp3-3k\n\nShop: https://stza.co/+vKp3-11\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144600Z
LAST-MODIFIED:20180213T144600Z
TRANSP:OPAQUE
END:VEVENT
* Chiefs @ Red Wings
<2018-04-11 Wed 11:35-14:35>
:PROPERTIES:
:ID:       omniEI3yRk1QpkLyrGmGFLPh@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Chiefs @ Red Wings Chiefs @ Red Wings

Follow on MiLB First Pitch  https //stza.co/+vKp4-2z

Shop  https //stza.co/+vKp4-14

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Chiefs @ Red Wings
END:VALARM
DTSTART:20180411T163500Z
DTEND:20180411T193500Z
UID:omniEI3yRk1QpkLyrGmGFLPh@stanza.co
SUMMARY:Chiefs @ Red Wings
DESCRIPTION:Chiefs @ Red Wings\n\nFollow on MiLB First Pitch: https://stza.co/+vKp4-2z\n\nShop: https://stza.co/+vKp4-14\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144600Z
LAST-MODIFIED:20180213T144600Z
TRANSP:OPAQUE
END:VEVENT
* Chiefs vs. Tides
<2018-04-12 Thu 13:05-16:05>
:PROPERTIES:
:ID:       rhsJvAmKqUJ4yoDyLAwTxTT6@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Chiefs vs. Tides Chiefs vs. Tides

Follow on MiLB First Pitch  https //stza.co/+vKpl-s

Shop  https //stza.co/+vKpl-2Y

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Chiefs vs. Tides
END:VALARM
DTSTART:20180412T180500Z
DTEND:20180412T210500Z
UID:rhsJvAmKqUJ4yoDyLAwTxTT6@stanza.co
SUMMARY:Chiefs vs. Tides
DESCRIPTION:Chiefs vs. Tides\n\nFollow on MiLB First Pitch: https://stza.co/+vKpl-s\n\nShop: https://stza.co/+vKpl-2Y\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144600Z
LAST-MODIFIED:20180213T144600Z
TRANSP:OPAQUE
END:VEVENT
* Chiefs vs. Tides
<2018-04-13 Fri 12:05-15:05>
:PROPERTIES:
:ID:       XnzVXvQT4bFMJmiJjYJuOrO9@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Chiefs vs. Tides Chiefs vs. Tides

Follow on MiLB First Pitch  https //stza.co/+y4zV-2S

Shop  https //stza.co/+y4zV-F

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Chiefs vs. Tides
END:VALARM
DTSTART:20180413T170500Z
DTEND:20180413T200500Z
UID:XnzVXvQT4bFMJmiJjYJuOrO9@stanza.co
SUMMARY:Chiefs vs. Tides
DESCRIPTION:Chiefs vs. Tides\n\nFollow on MiLB First Pitch: https://stza.co/+y4zV-2S\n\nShop: https://stza.co/+y4zV-F\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144600Z
LAST-MODIFIED:20180213T144600Z
TRANSP:OPAQUE
END:VEVENT
* Chiefs vs. Tides
<2018-04-14 Sat 12:05-15:05>
:PROPERTIES:
:ID:       Dmd9xTLX0kjPQshOYWFUfWJL@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Chiefs vs. Tides Chiefs vs. Tides

Follow on MiLB First Pitch  https //stza.co/+vKpp-1z

Shop  https //stza.co/+vKpp-w

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Chiefs vs. Tides
END:VALARM
DTSTART:20180414T170500Z
DTEND:20180414T200500Z
UID:Dmd9xTLX0kjPQshOYWFUfWJL@stanza.co
SUMMARY:Chiefs vs. Tides
DESCRIPTION:Chiefs vs. Tides\n\nFollow on MiLB First Pitch: https://stza.co/+vKpp-1z\n\nShop: https://stza.co/+vKpp-w\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144600Z
LAST-MODIFIED:20180213T144600Z
TRANSP:OPAQUE
END:VEVENT
* Chiefs vs. Tides
<2018-04-15 Sun 12:05-15:05>
:PROPERTIES:
:ID:       0PRDoyR19APtnYKT1YrJxtnN@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Chiefs vs. Tides Chiefs vs. Tides

Follow on MiLB First Pitch  https //stza.co/+vKps-3A

Shop  https //stza.co/+vKps-3y

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Chiefs vs. Tides
END:VALARM
DTSTART:20180415T170500Z
DTEND:20180415T200500Z
UID:0PRDoyR19APtnYKT1YrJxtnN@stanza.co
SUMMARY:Chiefs vs. Tides
DESCRIPTION:Chiefs vs. Tides\n\nFollow on MiLB First Pitch: https://stza.co/+vKps-3A\n\nShop: https://stza.co/+vKps-3y\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144600Z
LAST-MODIFIED:20180213T144600Z
TRANSP:OPAQUE
END:VEVENT
* Chiefs vs. Indians
<2018-04-16 Mon 17:35-20:35>
:PROPERTIES:
:ID:       UahZZ6beXM6q9ALfp8e__ecr@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Chiefs vs. Indians Chiefs vs. Indians

Follow on MiLB First Pitch  https //stza.co/+vKpt-1i

Shop  https //stza.co/+vKpt-2U

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Chiefs vs. Indians
END:VALARM
DTSTART:20180416T223500Z
DTEND:20180417T013500Z
UID:UahZZ6beXM6q9ALfp8e__ecr@stanza.co
SUMMARY:Chiefs vs. Indians
DESCRIPTION:Chiefs vs. Indians\n\nFollow on MiLB First Pitch: https://stza.co/+vKpt-1i\n\nShop: https://stza.co/+vKpt-2U\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144600Z
LAST-MODIFIED:20180213T144600Z
TRANSP:OPAQUE
END:VEVENT
* Chiefs vs. Indians
<2018-04-17 Tue 17:35-20:35>
:PROPERTIES:
:ID:       3xnb1AIlGuazSkDYkbob_AHz@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Chiefs vs. Indians Chiefs vs. Indians

Follow on MiLB First Pitch  https //stza.co/+vKpw-24

Shop  https //stza.co/+vKpw-3W

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Chiefs vs. Indians
END:VALARM
DTSTART:20180417T223500Z
DTEND:20180418T013500Z
UID:3xnb1AIlGuazSkDYkbob_AHz@stanza.co
SUMMARY:Chiefs vs. Indians
DESCRIPTION:Chiefs vs. Indians\n\nFollow on MiLB First Pitch: https://stza.co/+vKpw-24\n\nShop: https://stza.co/+vKpw-3W\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144600Z
LAST-MODIFIED:20180213T144600Z
TRANSP:OPAQUE
END:VEVENT
* Chiefs vs. Indians
<2018-04-18 Wed 09:30-12:30>
:PROPERTIES:
:ID:       XhalpLv917FOw3ijxSpaF6Fg@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Chiefs vs. Indians Chiefs vs. Indians

Follow on MiLB First Pitch  https //stza.co/+vKpx-2

Shop  https //stza.co/+vKpx-l

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Chiefs vs. Indians
END:VALARM
DTSTART:20180418T143000Z
DTEND:20180418T173000Z
UID:XhalpLv917FOw3ijxSpaF6Fg@stanza.co
SUMMARY:Chiefs vs. Indians
DESCRIPTION:Chiefs vs. Indians\n\nFollow on MiLB First Pitch: https://stza.co/+vKpx-2\n\nShop: https://stza.co/+vKpx-l\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144600Z
LAST-MODIFIED:20180213T144600Z
TRANSP:OPAQUE
END:VEVENT
* Chiefs @ Bats
<2018-04-20 Fri 18:00-21:00>
:PROPERTIES:
:ID:       -eI2ogAdVFnR0H-MXvMpaaMe@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Chiefs @ Bats Chiefs @ Bats

Buy tickets here  https //stza.co/~vKoR

Follow on MiLB First Pitch  https //stza.co/+vKoR-2n

Shop  https //stza.co/+vKoR-q

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Chiefs @ Bats
END:VALARM
DTSTART:20180420T230000Z
DTEND:20180421T020000Z
UID:-eI2ogAdVFnR0H-MXvMpaaMe@stanza.co
SUMMARY:Chiefs @ Bats
DESCRIPTION:Chiefs @ Bats\n\nBuy tickets here: https://stza.co/~vKoR\n\nFollow on MiLB First Pitch: https://stza.co/+vKoR-2n\n\nShop: https://stza.co/+vKoR-q\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144600Z
LAST-MODIFIED:20180213T144600Z
TRANSP:OPAQUE
END:VEVENT
* Chiefs @ Bats
<2018-04-21 Sat 13:00-16:00>
:PROPERTIES:
:ID:       wDx0p7r_g1wR7cnzGWG_g25l@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Chiefs @ Bats Chiefs @ Bats

Buy tickets here  https //stza.co/~vKoS

Follow on MiLB First Pitch  https //stza.co/+vKoS-1i

Shop  https //stza.co/+vKoS-z

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Chiefs @ Bats
END:VALARM
DTSTART:20180421T180000Z
DTEND:20180421T210000Z
UID:wDx0p7r_g1wR7cnzGWG_g25l@stanza.co
SUMMARY:Chiefs @ Bats
DESCRIPTION:Chiefs @ Bats\n\nBuy tickets here: https://stza.co/~vKoS\n\nFollow on MiLB First Pitch: https://stza.co/+vKoS-1i\n\nShop: https://stza.co/+vKoS-z\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144600Z
LAST-MODIFIED:20180213T144600Z
TRANSP:OPAQUE
END:VEVENT
* Chiefs @ Bats
<2018-04-22 Sun 13:00-16:00>
:PROPERTIES:
:ID:       hPG1XC4vyXd_62N7uK_CA5AT@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Chiefs @ Bats Chiefs @ Bats

Buy tickets here  https //stza.co/~vKoT

Follow on MiLB First Pitch  https //stza.co/+vKoT-18

Shop  https //stza.co/+vKoT-1p

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Chiefs @ Bats
END:VALARM
DTSTART:20180422T180000Z
DTEND:20180422T210000Z
UID:hPG1XC4vyXd_62N7uK_CA5AT@stanza.co
SUMMARY:Chiefs @ Bats
DESCRIPTION:Chiefs @ Bats\n\nBuy tickets here: https://stza.co/~vKoT\n\nFollow on MiLB First Pitch: https://stza.co/+vKoT-18\n\nShop: https://stza.co/+vKoT-1p\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144600Z
LAST-MODIFIED:20180213T144600Z
TRANSP:OPAQUE
END:VEVENT
* Chiefs @ Indians
<2018-04-23 Mon 18:05-21:05>
:PROPERTIES:
:ID:       jVHnZ2zHgmgf9r_VPKYXYTE0@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Chiefs @ Indians Chiefs @ Indians

Follow on MiLB First Pitch  https //stza.co/+vKoG-23

Shop  https //stza.co/+vKoG-2c

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Chiefs @ Indians
END:VALARM
DTSTART:20180423T230500Z
DTEND:20180424T020500Z
UID:jVHnZ2zHgmgf9r_VPKYXYTE0@stanza.co
SUMMARY:Chiefs @ Indians
DESCRIPTION:Chiefs @ Indians\n\nFollow on MiLB First Pitch: https://stza.co/+vKoG-23\n\nShop: https://stza.co/+vKoG-2c\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144600Z
LAST-MODIFIED:20180213T144600Z
TRANSP:OPAQUE
END:VEVENT
* Chiefs @ Indians
<2018-04-24 Tue 10:05-13:05>
:PROPERTIES:
:ID:       7dtZHfQaltc252-JZzWOm8wo@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Chiefs @ Indians Chiefs @ Indians

Follow on MiLB First Pitch  https //stza.co/+vKoH-6

Shop  https //stza.co/+vKoH-K

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Chiefs @ Indians
END:VALARM
DTSTART:20180424T150500Z
DTEND:20180424T180500Z
UID:7dtZHfQaltc252-JZzWOm8wo@stanza.co
SUMMARY:Chiefs @ Indians
DESCRIPTION:Chiefs @ Indians\n\nFollow on MiLB First Pitch: https://stza.co/+vKoH-6\n\nShop: https://stza.co/+vKoH-K\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144600Z
LAST-MODIFIED:20180213T144600Z
TRANSP:OPAQUE
END:VEVENT
* Chiefs @ Indians
<2018-04-25 Wed 12:35-15:35>
:PROPERTIES:
:ID:       sWhFEl4Ridt0zw7OCSIlDN5C@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Chiefs @ Indians Chiefs @ Indians

Follow on MiLB First Pitch  https //stza.co/+vKoI-3M

Shop  https //stza.co/+vKoI-3W

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Chiefs @ Indians
END:VALARM
DTSTART:20180425T173500Z
DTEND:20180425T203500Z
UID:sWhFEl4Ridt0zw7OCSIlDN5C@stanza.co
SUMMARY:Chiefs @ Indians
DESCRIPTION:Chiefs @ Indians\n\nFollow on MiLB First Pitch: https://stza.co/+vKoI-3M\n\nShop: https://stza.co/+vKoI-3W\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144600Z
LAST-MODIFIED:20180213T144600Z
TRANSP:OPAQUE
END:VEVENT
* Chiefs vs. Red Wings
<2018-04-27 Fri 17:35-20:35>
:PROPERTIES:
:ID:       4wv0hGC6t_6e2AbfjH5EKfAY@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Chiefs vs. Red Wings Chiefs vs. Red Wings

Follow on MiLB First Pitch  https //stza.co/+vKpA-1

Shop  https //stza.co/+vKpA-3B

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Chiefs vs. Red Wings
END:VALARM
DTSTART:20180427T223500Z
DTEND:20180428T013500Z
UID:4wv0hGC6t_6e2AbfjH5EKfAY@stanza.co
SUMMARY:Chiefs vs. Red Wings
DESCRIPTION:Chiefs vs. Red Wings\n\nFollow on MiLB First Pitch: https://stza.co/+vKpA-1\n\nShop: https://stza.co/+vKpA-3B\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144600Z
LAST-MODIFIED:20180213T144600Z
TRANSP:OPAQUE
END:VEVENT
* Chiefs vs. Red Wings
<2018-04-28 Sat 12:05-15:05>
:PROPERTIES:
:ID:       tzn1Jy3FOf-ll4kdCYARKre6@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Chiefs vs. Red Wings Chiefs vs. Red Wings

Follow on MiLB First Pitch  https //stza.co/+vKpC-2u

Shop  https //stza.co/+vKpC-H

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Chiefs vs. Red Wings
END:VALARM
DTSTART:20180428T170500Z
DTEND:20180428T200500Z
UID:tzn1Jy3FOf-ll4kdCYARKre6@stanza.co
SUMMARY:Chiefs vs. Red Wings
DESCRIPTION:Chiefs vs. Red Wings\n\nFollow on MiLB First Pitch: https://stza.co/+vKpC-2u\n\nShop: https://stza.co/+vKpC-H\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144600Z
LAST-MODIFIED:20180213T144600Z
TRANSP:OPAQUE
END:VEVENT
* Chiefs vs. Red Wings
<2018-04-29 Sun 12:05-15:05>
:PROPERTIES:
:ID:       NZz2YGKET_bAYjncb3s-DdpF@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Chiefs vs. Red Wings Chiefs vs. Red Wings

Follow on MiLB First Pitch  https //stza.co/+vKpE-2S

Shop  https //stza.co/+vKpE-3u

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Chiefs vs. Red Wings
END:VALARM
DTSTART:20180429T170500Z
DTEND:20180429T200500Z
UID:NZz2YGKET_bAYjncb3s-DdpF@stanza.co
SUMMARY:Chiefs vs. Red Wings
DESCRIPTION:Chiefs vs. Red Wings\n\nFollow on MiLB First Pitch: https://stza.co/+vKpE-2S\n\nShop: https://stza.co/+vKpE-3u\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144600Z
LAST-MODIFIED:20180213T144600Z
TRANSP:OPAQUE
END:VEVENT
* Chiefs @ IronPigs
<2018-04-30 Mon 18:05-21:05>
:PROPERTIES:
:ID:       WTvqePznWYn_5e9NFkOuGF1c@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Chiefs @ IronPigs Chiefs @ IronPigs

Follow on MiLB First Pitch  https //stza.co/+vKoJ-1h

Shop  https //stza.co/+vKoJ-D

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Chiefs @ IronPigs
END:VALARM
DTSTART:20180430T230500Z
DTEND:20180501T020500Z
UID:WTvqePznWYn_5e9NFkOuGF1c@stanza.co
SUMMARY:Chiefs @ IronPigs
DESCRIPTION:Chiefs @ IronPigs\n\nFollow on MiLB First Pitch: https://stza.co/+vKoJ-1h\n\nShop: https://stza.co/+vKoJ-D\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144600Z
LAST-MODIFIED:20180213T144600Z
TRANSP:OPAQUE
END:VEVENT
* Chiefs @ IronPigs
<2018-05-01 Tue 18:05-21:05>
:PROPERTIES:
:ID:       eA6tj2KS1UVHgNSLLTZhf_JY@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Chiefs @ IronPigs Chiefs @ IronPigs

Follow on MiLB First Pitch  https //stza.co/+vKoK-2y

Shop  https //stza.co/+vKoK-3N

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Chiefs @ IronPigs
END:VALARM
DTSTART:20180501T230500Z
DTEND:20180502T020500Z
UID:eA6tj2KS1UVHgNSLLTZhf_JY@stanza.co
SUMMARY:Chiefs @ IronPigs
DESCRIPTION:Chiefs @ IronPigs\n\nFollow on MiLB First Pitch: https://stza.co/+vKoK-2y\n\nShop: https://stza.co/+vKoK-3N\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144600Z
LAST-MODIFIED:20180213T144600Z
TRANSP:OPAQUE
END:VEVENT
* Chiefs @ IronPigs
<2018-05-02 Wed 09:35-12:35>
:PROPERTIES:
:ID:       Iw774gmjFs5FPVXojY2r85bB@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Chiefs @ IronPigs Chiefs @ IronPigs

Follow on MiLB First Pitch  https //stza.co/+vKoL-Y

Shop  https //stza.co/+vKoL-3m

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Chiefs @ IronPigs
END:VALARM
DTSTART:20180502T143500Z
DTEND:20180502T173500Z
UID:Iw774gmjFs5FPVXojY2r85bB@stanza.co
SUMMARY:Chiefs @ IronPigs
DESCRIPTION:Chiefs @ IronPigs\n\nFollow on MiLB First Pitch: https://stza.co/+vKoL-Y\n\nShop: https://stza.co/+vKoL-3m\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144600Z
LAST-MODIFIED:20180213T144600Z
TRANSP:OPAQUE
END:VEVENT
* Chiefs @ Bisons
<2018-05-03 Thu 17:05-20:05>
:PROPERTIES:
:ID:       ZcNzfaNI9sUxR4qrg06W1suL@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Chiefs @ Bisons Chiefs @ Bisons

Follow on MiLB First Pitch  https //stza.co/+vKoi-9

Shop  https //stza.co/+vKoi-k

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Chiefs @ Bisons
END:VALARM
DTSTART:20180503T220500Z
DTEND:20180504T010500Z
UID:ZcNzfaNI9sUxR4qrg06W1suL@stanza.co
SUMMARY:Chiefs @ Bisons
DESCRIPTION:Chiefs @ Bisons\n\nFollow on MiLB First Pitch: https://stza.co/+vKoi-9\n\nShop: https://stza.co/+vKoi-k\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144600Z
LAST-MODIFIED:20180213T144600Z
TRANSP:OPAQUE
END:VEVENT
* Chiefs @ Bisons
<2018-05-04 Fri 18:05-21:05>
:PROPERTIES:
:ID:       29iiu1FFqgrCyILHpaHcBpib@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Chiefs @ Bisons Chiefs @ Bisons

Follow on MiLB First Pitch  https //stza.co/+vKoj-1C

Shop  https //stza.co/+vKoj-V

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Chiefs @ Bisons
END:VALARM
DTSTART:20180504T230500Z
DTEND:20180505T020500Z
UID:29iiu1FFqgrCyILHpaHcBpib@stanza.co
SUMMARY:Chiefs @ Bisons
DESCRIPTION:Chiefs @ Bisons\n\nFollow on MiLB First Pitch: https://stza.co/+vKoj-1C\n\nShop: https://stza.co/+vKoj-V\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144600Z
LAST-MODIFIED:20180213T144600Z
TRANSP:OPAQUE
END:VEVENT
* Chiefs @ Bisons
<2018-05-05 Sat 12:05-15:05>
:PROPERTIES:
:ID:       PBLFwC2poEev_P-fPtiQnh_L@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Chiefs @ Bisons Chiefs @ Bisons

Follow on MiLB First Pitch  https //stza.co/+vKok-26

Shop  https //stza.co/+vKok-3u

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Chiefs @ Bisons
END:VALARM
DTSTART:20180505T170500Z
DTEND:20180505T200500Z
UID:PBLFwC2poEev_P-fPtiQnh_L@stanza.co
SUMMARY:Chiefs @ Bisons
DESCRIPTION:Chiefs @ Bisons\n\nFollow on MiLB First Pitch: https://stza.co/+vKok-26\n\nShop: https://stza.co/+vKok-3u\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144600Z
LAST-MODIFIED:20180213T144600Z
TRANSP:OPAQUE
END:VEVENT
* Chiefs @ Bisons
<2018-05-06 Sun 12:05-15:05>
:PROPERTIES:
:ID:       U8ErJc0bCjx6F648Ov3jH9dG@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Chiefs @ Bisons Chiefs @ Bisons

Follow on MiLB First Pitch  https //stza.co/+vKol-3q

Shop  https //stza.co/+vKol-2J

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Chiefs @ Bisons
END:VALARM
DTSTART:20180506T170500Z
DTEND:20180506T200500Z
UID:U8ErJc0bCjx6F648Ov3jH9dG@stanza.co
SUMMARY:Chiefs @ Bisons
DESCRIPTION:Chiefs @ Bisons\n\nFollow on MiLB First Pitch: https://stza.co/+vKol-3q\n\nShop: https://stza.co/+vKol-2J\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144600Z
LAST-MODIFIED:20180213T144600Z
TRANSP:OPAQUE
END:VEVENT
* Chiefs vs. RailRiders
<2018-05-07 Mon 17:35-20:35>
:PROPERTIES:
:ID:       aVepeNcH2IBTNb_sA0y9hWis@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Chiefs vs. RailRiders Chiefs vs. RailRiders

Follow on MiLB First Pitch  https //stza.co/+vKpG-34

Shop  https //stza.co/+vKpG-y

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Chiefs vs. RailRiders
END:VALARM
DTSTART:20180507T223500Z
DTEND:20180508T013500Z
UID:aVepeNcH2IBTNb_sA0y9hWis@stanza.co
SUMMARY:Chiefs vs. RailRiders
DESCRIPTION:Chiefs vs. RailRiders\n\nFollow on MiLB First Pitch: https://stza.co/+vKpG-34\n\nShop: https://stza.co/+vKpG-y\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144600Z
LAST-MODIFIED:20180213T144600Z
TRANSP:OPAQUE
END:VEVENT
* Chiefs vs. RailRiders
<2018-05-08 Tue 17:35-20:35>
:PROPERTIES:
:ID:       GVRF0Axijvw_pNS1K-juHrch@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Chiefs vs. RailRiders Chiefs vs. RailRiders

Follow on MiLB First Pitch  https //stza.co/+vKpH-M

Shop  https //stza.co/+vKpH-b

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Chiefs vs. RailRiders
END:VALARM
DTSTART:20180508T223500Z
DTEND:20180509T013500Z
UID:GVRF0Axijvw_pNS1K-juHrch@stanza.co
SUMMARY:Chiefs vs. RailRiders
DESCRIPTION:Chiefs vs. RailRiders\n\nFollow on MiLB First Pitch: https://stza.co/+vKpH-M\n\nShop: https://stza.co/+vKpH-b\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144600Z
LAST-MODIFIED:20180213T144600Z
TRANSP:OPAQUE
END:VEVENT
* Chiefs vs. RailRiders
<2018-05-09 Wed 17:35-20:35>
:PROPERTIES:
:ID:       3ZQlWGgn7gI5A8HOPk2f5PyP@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Chiefs vs. RailRiders Chiefs vs. RailRiders

Follow on MiLB First Pitch  https //stza.co/+vKpK-3m

Shop  https //stza.co/+vKpK-2A

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Chiefs vs. RailRiders
END:VALARM
DTSTART:20180509T223500Z
DTEND:20180510T013500Z
UID:3ZQlWGgn7gI5A8HOPk2f5PyP@stanza.co
SUMMARY:Chiefs vs. RailRiders
DESCRIPTION:Chiefs vs. RailRiders\n\nFollow on MiLB First Pitch: https://stza.co/+vKpK-3m\n\nShop: https://stza.co/+vKpK-2A\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144600Z
LAST-MODIFIED:20180213T144600Z
TRANSP:OPAQUE
END:VEVENT
* Chiefs vs. Red Sox
<2018-05-10 Thu 17:35-20:35>
:PROPERTIES:
:ID:       WM_yPdWfv0diXFWtyQNrq_qi@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Chiefs vs. Red Sox Chiefs vs. Red Sox

Follow on MiLB First Pitch  https //stza.co/+vKpL-3z

Shop  https //stza.co/+vKpL-1t

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Chiefs vs. Red Sox
END:VALARM
DTSTART:20180510T223500Z
DTEND:20180511T013500Z
UID:WM_yPdWfv0diXFWtyQNrq_qi@stanza.co
SUMMARY:Chiefs vs. Red Sox
DESCRIPTION:Chiefs vs. Red Sox\n\nFollow on MiLB First Pitch: https://stza.co/+vKpL-3z\n\nShop: https://stza.co/+vKpL-1t\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144600Z
LAST-MODIFIED:20180213T144600Z
TRANSP:OPAQUE
END:VEVENT
* Chiefs vs. Red Sox
<2018-05-11 Fri 17:35-20:35>
:PROPERTIES:
:ID:       ZYniks8G6uwB7-nex7meo1BW@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Chiefs vs. Red Sox Chiefs vs. Red Sox

Follow on MiLB First Pitch  https //stza.co/+vKpO-1x

Shop  https //stza.co/+vKpO-e

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Chiefs vs. Red Sox
END:VALARM
DTSTART:20180511T223500Z
DTEND:20180512T013500Z
UID:ZYniks8G6uwB7-nex7meo1BW@stanza.co
SUMMARY:Chiefs vs. Red Sox
DESCRIPTION:Chiefs vs. Red Sox\n\nFollow on MiLB First Pitch: https://stza.co/+vKpO-1x\n\nShop: https://stza.co/+vKpO-e\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144600Z
LAST-MODIFIED:20180213T144600Z
TRANSP:OPAQUE
END:VEVENT
* Chiefs vs. Red Sox
<2018-05-12 Sat 17:35-20:35>
:PROPERTIES:
:ID:       AQcGBuN3uRvwHxWqO4TAt5gg@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Chiefs vs. Red Sox Chiefs vs. Red Sox

Follow on MiLB First Pitch  https //stza.co/+vKpQ-3l

Shop  https //stza.co/+vKpQ-2D

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Chiefs vs. Red Sox
END:VALARM
DTSTART:20180512T223500Z
DTEND:20180513T013500Z
UID:AQcGBuN3uRvwHxWqO4TAt5gg@stanza.co
SUMMARY:Chiefs vs. Red Sox
DESCRIPTION:Chiefs vs. Red Sox\n\nFollow on MiLB First Pitch: https://stza.co/+vKpQ-3l\n\nShop: https://stza.co/+vKpQ-2D\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144600Z
LAST-MODIFIED:20180213T144600Z
TRANSP:OPAQUE
END:VEVENT
* Chiefs vs. Red Sox
<2018-05-13 Sun 12:05-15:05>
:PROPERTIES:
:ID:       51VvXKn0ERvqU9xbwVTAIFKR@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Chiefs vs. Red Sox Chiefs vs. Red Sox

Follow on MiLB First Pitch  https //stza.co/+vKpR-v

Shop  https //stza.co/+vKpR-3M

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Chiefs vs. Red Sox
END:VALARM
DTSTART:20180513T170500Z
DTEND:20180513T200500Z
UID:51VvXKn0ERvqU9xbwVTAIFKR@stanza.co
SUMMARY:Chiefs vs. Red Sox
DESCRIPTION:Chiefs vs. Red Sox\n\nFollow on MiLB First Pitch: https://stza.co/+vKpR-v\n\nShop: https://stza.co/+vKpR-3M\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144600Z
LAST-MODIFIED:20180213T144600Z
TRANSP:OPAQUE
END:VEVENT
* Chiefs @ Red Wings
<2018-05-15 Tue 18:05-21:05>
:PROPERTIES:
:ID:       JgKh-O-KFs6lA5SVOrkuAMLw@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Chiefs @ Red Wings Chiefs @ Red Wings

Follow on MiLB First Pitch  https //stza.co/+vKp5-1N

Shop  https //stza.co/+vKp5-1r

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Chiefs @ Red Wings
END:VALARM
DTSTART:20180515T230500Z
DTEND:20180516T020500Z
UID:JgKh-O-KFs6lA5SVOrkuAMLw@stanza.co
SUMMARY:Chiefs @ Red Wings
DESCRIPTION:Chiefs @ Red Wings\n\nFollow on MiLB First Pitch: https://stza.co/+vKp5-1N\n\nShop: https://stza.co/+vKp5-1r\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144600Z
LAST-MODIFIED:20180213T144600Z
TRANSP:OPAQUE
END:VEVENT
* Chiefs @ Red Wings
<2018-05-16 Wed 18:05-21:05>
:PROPERTIES:
:ID:       zz4Bs7TLMECI_t3fshlRflLh@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Chiefs @ Red Wings Chiefs @ Red Wings

Follow on MiLB First Pitch  https //stza.co/+vKp6-C

Shop  https //stza.co/+vKp6-Y

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Chiefs @ Red Wings
END:VALARM
DTSTART:20180516T230500Z
DTEND:20180517T020500Z
UID:zz4Bs7TLMECI_t3fshlRflLh@stanza.co
SUMMARY:Chiefs @ Red Wings
DESCRIPTION:Chiefs @ Red Wings\n\nFollow on MiLB First Pitch: https://stza.co/+vKp6-C\n\nShop: https://stza.co/+vKp6-Y\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144600Z
LAST-MODIFIED:20180213T144600Z
TRANSP:OPAQUE
END:VEVENT
* Chiefs @ Red Wings
<2018-05-17 Thu 10:05-13:05>
:PROPERTIES:
:ID:       NUkx6sAdTnW56KsHM6LLKX01@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Chiefs @ Red Wings Chiefs @ Red Wings

Follow on MiLB First Pitch  https //stza.co/+vKp7-3i

Shop  https //stza.co/+vKp7-3H

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Chiefs @ Red Wings
END:VALARM
DTSTART:20180517T150500Z
DTEND:20180517T180500Z
UID:NUkx6sAdTnW56KsHM6LLKX01@stanza.co
SUMMARY:Chiefs @ Red Wings
DESCRIPTION:Chiefs @ Red Wings\n\nFollow on MiLB First Pitch: https://stza.co/+vKp7-3i\n\nShop: https://stza.co/+vKp7-3H\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144600Z
LAST-MODIFIED:20180213T144600Z
TRANSP:OPAQUE
END:VEVENT
* Chiefs vs. IronPigs
<2018-05-18 Fri 17:35-20:35>
:PROPERTIES:
:ID:       X_bOHh3a_O1u1eviDxHiYHp6@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Chiefs vs. IronPigs Chiefs vs. IronPigs

Follow on MiLB First Pitch  https //stza.co/+vKpU-T

Shop  https //stza.co/+vKpU-3l

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Chiefs vs. IronPigs
END:VALARM
DTSTART:20180518T223500Z
DTEND:20180519T013500Z
UID:X_bOHh3a_O1u1eviDxHiYHp6@stanza.co
SUMMARY:Chiefs vs. IronPigs
DESCRIPTION:Chiefs vs. IronPigs\n\nFollow on MiLB First Pitch: https://stza.co/+vKpU-T\n\nShop: https://stza.co/+vKpU-3l\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144600Z
LAST-MODIFIED:20180213T144600Z
TRANSP:OPAQUE
END:VEVENT
* Chiefs vs. IronPigs
<2018-05-19 Sat 12:05-15:05>
:PROPERTIES:
:ID:       HsNPdqhXinLfpGTBt5xP3bjd@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Chiefs vs. IronPigs Chiefs vs. IronPigs

Follow on MiLB First Pitch  https //stza.co/+vKpW-3F

Shop  https //stza.co/+vKpW-j

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Chiefs vs. IronPigs
END:VALARM
DTSTART:20180519T170500Z
DTEND:20180519T200500Z
UID:HsNPdqhXinLfpGTBt5xP3bjd@stanza.co
SUMMARY:Chiefs vs. IronPigs
DESCRIPTION:Chiefs vs. IronPigs\n\nFollow on MiLB First Pitch: https://stza.co/+vKpW-3F\n\nShop: https://stza.co/+vKpW-j\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144600Z
LAST-MODIFIED:20180213T144600Z
TRANSP:OPAQUE
END:VEVENT
* Chiefs vs. IronPigs
<2018-05-20 Sun 12:05-15:05>
:PROPERTIES:
:ID:       jrUZfDJnbzYAPoERUs18b88t@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Chiefs vs. IronPigs Chiefs vs. IronPigs

Follow on MiLB First Pitch  https //stza.co/+vKpX-2H

Shop  https //stza.co/+vKpX-11

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Chiefs vs. IronPigs
END:VALARM
DTSTART:20180520T170500Z
DTEND:20180520T200500Z
UID:jrUZfDJnbzYAPoERUs18b88t@stanza.co
SUMMARY:Chiefs vs. IronPigs
DESCRIPTION:Chiefs vs. IronPigs\n\nFollow on MiLB First Pitch: https://stza.co/+vKpX-2H\n\nShop: https://stza.co/+vKpX-11\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144600Z
LAST-MODIFIED:20180213T144600Z
TRANSP:OPAQUE
END:VEVENT
* Chiefs @ Bisons
<2018-05-21 Mon 17:05-20:05>
:PROPERTIES:
:ID:       d35a0W-Roiumz-DurUL9MCIm@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Chiefs @ Bisons Chiefs @ Bisons

Follow on MiLB First Pitch  https //stza.co/+vKom-O

Shop  https //stza.co/+vKom-1k

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Chiefs @ Bisons
END:VALARM
DTSTART:20180521T220500Z
DTEND:20180522T010500Z
UID:d35a0W-Roiumz-DurUL9MCIm@stanza.co
SUMMARY:Chiefs @ Bisons
DESCRIPTION:Chiefs @ Bisons\n\nFollow on MiLB First Pitch: https://stza.co/+vKom-O\n\nShop: https://stza.co/+vKom-1k\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144600Z
LAST-MODIFIED:20180213T144600Z
TRANSP:OPAQUE
END:VEVENT
* Chiefs @ Bisons
<2018-05-22 Tue 17:05-20:05>
:PROPERTIES:
:ID:       XJYBhY1i9G2ovCJ1ZwCd6O3R@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Chiefs @ Bisons Chiefs @ Bisons

Follow on MiLB First Pitch  https //stza.co/+vKon-1g

Shop  https //stza.co/+vKon-16

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Chiefs @ Bisons
END:VALARM
DTSTART:20180522T220500Z
DTEND:20180523T010500Z
UID:XJYBhY1i9G2ovCJ1ZwCd6O3R@stanza.co
SUMMARY:Chiefs @ Bisons
DESCRIPTION:Chiefs @ Bisons\n\nFollow on MiLB First Pitch: https://stza.co/+vKon-1g\n\nShop: https://stza.co/+vKon-16\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144600Z
LAST-MODIFIED:20180213T144600Z
TRANSP:OPAQUE
END:VEVENT
* Chiefs @ Bisons
<2018-05-23 Wed 17:05-20:05>
:PROPERTIES:
:ID:       GPkgPtPEcAq_E9BPa5I_ctDP@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Chiefs @ Bisons Chiefs @ Bisons

Follow on MiLB First Pitch  https //stza.co/+vKoo-2$

Shop  https //stza.co/+vKoo-_

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Chiefs @ Bisons
END:VALARM
DTSTART:20180523T220500Z
DTEND:20180524T010500Z
UID:GPkgPtPEcAq_E9BPa5I_ctDP@stanza.co
SUMMARY:Chiefs @ Bisons
DESCRIPTION:Chiefs @ Bisons\n\nFollow on MiLB First Pitch: https://stza.co/+vKoo-2$\n\nShop: https://stza.co/+vKoo-_\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144600Z
LAST-MODIFIED:20180213T144600Z
TRANSP:OPAQUE
END:VEVENT
* Chiefs @ Bisons
<2018-05-24 Thu 12:05-15:05>
:PROPERTIES:
:ID:       JbN07ZDSkXC0jG9wgjv7ZVr3@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Chiefs @ Bisons Chiefs @ Bisons

Follow on MiLB First Pitch  https //stza.co/+vKop-3m

Shop  https //stza.co/+vKop-1M

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Chiefs @ Bisons
END:VALARM
DTSTART:20180524T170500Z
DTEND:20180524T200500Z
UID:JbN07ZDSkXC0jG9wgjv7ZVr3@stanza.co
SUMMARY:Chiefs @ Bisons
DESCRIPTION:Chiefs @ Bisons\n\nFollow on MiLB First Pitch: https://stza.co/+vKop-3m\n\nShop: https://stza.co/+vKop-1M\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144600Z
LAST-MODIFIED:20180213T144600Z
TRANSP:OPAQUE
END:VEVENT
* Chiefs @ RailRiders
<2018-05-25 Fri 17:35-20:35>
:PROPERTIES:
:ID:       flnjJove774q8N2YXpYtd4if@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Chiefs @ RailRiders Chiefs @ RailRiders

Follow on MiLB First Pitch  https //stza.co/+vKpe-3L

Shop  https //stza.co/+vKpe-3z

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Chiefs @ RailRiders
END:VALARM
DTSTART:20180525T223500Z
DTEND:20180526T013500Z
UID:flnjJove774q8N2YXpYtd4if@stanza.co
SUMMARY:Chiefs @ RailRiders
DESCRIPTION:Chiefs @ RailRiders\n\nFollow on MiLB First Pitch: https://stza.co/+vKpe-3L\n\nShop: https://stza.co/+vKpe-3z\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144600Z
LAST-MODIFIED:20180213T144600Z
TRANSP:OPAQUE
END:VEVENT
* Chiefs @ RailRiders
<2018-05-26 Sat 15:05-18:05>
:PROPERTIES:
:ID:       0vKQ1vvr0H1utHeV4Kt5uK8V@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Chiefs @ RailRiders Chiefs @ RailRiders

Follow on MiLB First Pitch  https //stza.co/+vKpf-2s

Shop  https //stza.co/+vKpf-f

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Chiefs @ RailRiders
END:VALARM
DTSTART:20180526T200500Z
DTEND:20180526T230500Z
UID:0vKQ1vvr0H1utHeV4Kt5uK8V@stanza.co
SUMMARY:Chiefs @ RailRiders
DESCRIPTION:Chiefs @ RailRiders\n\nFollow on MiLB First Pitch: https://stza.co/+vKpf-2s\n\nShop: https://stza.co/+vKpf-f\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144600Z
LAST-MODIFIED:20180213T144600Z
TRANSP:OPAQUE
END:VEVENT
* Chiefs @ RailRiders
<2018-05-27 Sun 12:05-15:05>
:PROPERTIES:
:ID:       luBYKBJZfldZBGZjpOEOwKMd@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Chiefs @ RailRiders Chiefs @ RailRiders

Follow on MiLB First Pitch  https //stza.co/+vKpg-3F

Shop  https //stza.co/+vKpg-34

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Chiefs @ RailRiders
END:VALARM
DTSTART:20180527T170500Z
DTEND:20180527T200500Z
UID:luBYKBJZfldZBGZjpOEOwKMd@stanza.co
SUMMARY:Chiefs @ RailRiders
DESCRIPTION:Chiefs @ RailRiders\n\nFollow on MiLB First Pitch: https://stza.co/+vKpg-3F\n\nShop: https://stza.co/+vKpg-34\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144600Z
LAST-MODIFIED:20180213T144600Z
TRANSP:OPAQUE
END:VEVENT
* Chiefs @ RailRiders
<2018-05-28 Mon 17:35-20:35>
:PROPERTIES:
:ID:       33C3xVgVKVliydB1KGSo73wI@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Chiefs @ RailRiders Chiefs @ RailRiders

Follow on MiLB First Pitch  https //stza.co/+vKph-1h

Shop  https //stza.co/+vKph-_

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Chiefs @ RailRiders
END:VALARM
DTSTART:20180528T223500Z
DTEND:20180529T013500Z
UID:33C3xVgVKVliydB1KGSo73wI@stanza.co
SUMMARY:Chiefs @ RailRiders
DESCRIPTION:Chiefs @ RailRiders\n\nFollow on MiLB First Pitch: https://stza.co/+vKph-1h\n\nShop: https://stza.co/+vKph-_\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144600Z
LAST-MODIFIED:20180213T144600Z
TRANSP:OPAQUE
END:VEVENT
* Chiefs vs. Mud Hens
<2018-05-29 Tue 17:35-20:35>
:PROPERTIES:
:ID:       9Ot-23erili3lZuPCNgi0PAE@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Chiefs vs. Mud Hens Chiefs vs. Mud Hens

Follow on MiLB First Pitch  https //stza.co/+vKpZ-1Z

Shop  https //stza.co/+vKpZ-2y

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Chiefs vs. Mud Hens
END:VALARM
DTSTART:20180529T223500Z
DTEND:20180530T013500Z
UID:9Ot-23erili3lZuPCNgi0PAE@stanza.co
SUMMARY:Chiefs vs. Mud Hens
DESCRIPTION:Chiefs vs. Mud Hens\n\nFollow on MiLB First Pitch: https://stza.co/+vKpZ-1Z\n\nShop: https://stza.co/+vKpZ-2y\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144600Z
LAST-MODIFIED:20180213T144600Z
TRANSP:OPAQUE
END:VEVENT
* Chiefs vs. Mud Hens
<2018-05-30 Wed 09:30-12:30>
:PROPERTIES:
:ID:       TWXxIN_9gOmUy722Nwe93i_u@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Chiefs vs. Mud Hens Chiefs vs. Mud Hens

Follow on MiLB First Pitch  https //stza.co/+vKq0-2J

Shop  https //stza.co/+vKq0-2L

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Chiefs vs. Mud Hens
END:VALARM
DTSTART:20180530T143000Z
DTEND:20180530T173000Z
UID:TWXxIN_9gOmUy722Nwe93i_u@stanza.co
SUMMARY:Chiefs vs. Mud Hens
DESCRIPTION:Chiefs vs. Mud Hens\n\nFollow on MiLB First Pitch: https://stza.co/+vKq0-2J\n\nShop: https://stza.co/+vKq0-2L\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144600Z
LAST-MODIFIED:20180213T144600Z
TRANSP:OPAQUE
END:VEVENT
* Chiefs vs. Mud Hens
<2018-05-31 Thu 17:35-20:35>
:PROPERTIES:
:ID:       rKrjh-ssYyZGywzM_kCSc7Lw@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Chiefs vs. Mud Hens Chiefs vs. Mud Hens

Follow on MiLB First Pitch  https //stza.co/+u_uP-2x

Shop  https //stza.co/+u_uP-2U

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Chiefs vs. Mud Hens
END:VALARM
DTSTART:20180531T223500Z
DTEND:20180601T013500Z
UID:rKrjh-ssYyZGywzM_kCSc7Lw@stanza.co
SUMMARY:Chiefs vs. Mud Hens
DESCRIPTION:Chiefs vs. Mud Hens\n\nFollow on MiLB First Pitch: https://stza.co/+u_uP-2x\n\nShop: https://stza.co/+u_uP-2U\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144600Z
LAST-MODIFIED:20180213T144600Z
TRANSP:OPAQUE
END:VEVENT
* Chiefs vs. Clippers
<2018-06-01 Fri 18:05-21:05>
:PROPERTIES:
:ID:       scVzh8KwNQU75JRYUuDL_9O1@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Chiefs vs. Clippers Chiefs vs. Clippers

Follow on MiLB First Pitch  https //stza.co/+u_uR-3F

Shop  https //stza.co/+u_uR-33

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Chiefs vs. Clippers
END:VALARM
DTSTART:20180601T230500Z
DTEND:20180602T020500Z
UID:scVzh8KwNQU75JRYUuDL_9O1@stanza.co
SUMMARY:Chiefs vs. Clippers
DESCRIPTION:Chiefs vs. Clippers\n\nFollow on MiLB First Pitch: https://stza.co/+u_uR-3F\n\nShop: https://stza.co/+u_uR-33\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144600Z
LAST-MODIFIED:20180213T144600Z
TRANSP:OPAQUE
END:VEVENT
* Chiefs vs. Clippers
<2018-06-02 Sat 18:05-21:05>
:PROPERTIES:
:ID:       2nTZ3gN0RjUi-ErXjemkHvtl@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Chiefs vs. Clippers Chiefs vs. Clippers

Follow on MiLB First Pitch  https //stza.co/+u_uT-3x

Shop  https //stza.co/+u_uT-1e

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Chiefs vs. Clippers
END:VALARM
DTSTART:20180602T230500Z
DTEND:20180603T020500Z
UID:2nTZ3gN0RjUi-ErXjemkHvtl@stanza.co
SUMMARY:Chiefs vs. Clippers
DESCRIPTION:Chiefs vs. Clippers\n\nFollow on MiLB First Pitch: https://stza.co/+u_uT-3x\n\nShop: https://stza.co/+u_uT-1e\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144600Z
LAST-MODIFIED:20180213T144600Z
TRANSP:OPAQUE
END:VEVENT
* Chiefs vs. Clippers
<2018-06-03 Sun 12:05-15:05>
:PROPERTIES:
:ID:       sTP5FipmD2mFj3Mq8338uFcY@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Chiefs vs. Clippers Chiefs vs. Clippers

Follow on MiLB First Pitch  https //stza.co/+u_uW-1k

Shop  https //stza.co/+u_uW-1b

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Chiefs vs. Clippers
END:VALARM
DTSTART:20180603T170500Z
DTEND:20180603T200500Z
UID:sTP5FipmD2mFj3Mq8338uFcY@stanza.co
SUMMARY:Chiefs vs. Clippers
DESCRIPTION:Chiefs vs. Clippers\n\nFollow on MiLB First Pitch: https://stza.co/+u_uW-1k\n\nShop: https://stza.co/+u_uW-1b\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144600Z
LAST-MODIFIED:20180213T144600Z
TRANSP:OPAQUE
END:VEVENT
* Chiefs @ Knights
<2018-06-05 Tue 18:04-21:04>
:PROPERTIES:
:ID:       CqvoGXoB_fx_lncXHqs0KpP3@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Chiefs @ Knights Chiefs @ Knights

Follow on MiLB First Pitch  https //stza.co/+xONP-20

Shop  https //stza.co/+xONP-e

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Chiefs @ Knights
END:VALARM
DTSTART:20180605T230400Z
DTEND:20180606T020400Z
UID:CqvoGXoB_fx_lncXHqs0KpP3@stanza.co
SUMMARY:Chiefs @ Knights
DESCRIPTION:Chiefs @ Knights\n\nFollow on MiLB First Pitch: https://stza.co/+xONP-20\n\nShop: https://stza.co/+xONP-e\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144600Z
LAST-MODIFIED:20180213T144600Z
TRANSP:OPAQUE
END:VEVENT
* Chiefs @ Knights
<2018-06-06 Wed 18:04-21:04>
:PROPERTIES:
:ID:       aTQJfl49DYl95u_hheBQNv5R@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Chiefs @ Knights Chiefs @ Knights

Follow on MiLB First Pitch  https //stza.co/+xONQ-1N

Shop  https //stza.co/+xONQ-2k

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Chiefs @ Knights
END:VALARM
DTSTART:20180606T230400Z
DTEND:20180607T020400Z
UID:aTQJfl49DYl95u_hheBQNv5R@stanza.co
SUMMARY:Chiefs @ Knights
DESCRIPTION:Chiefs @ Knights\n\nFollow on MiLB First Pitch: https://stza.co/+xONQ-1N\n\nShop: https://stza.co/+xONQ-2k\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144600Z
LAST-MODIFIED:20180213T144600Z
TRANSP:OPAQUE
END:VEVENT
* Chiefs @ Knights
<2018-06-07 Thu 18:04-21:04>
:PROPERTIES:
:ID:       n_uIGbZDP_oMoTD_lugHFWoe@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Chiefs @ Knights Chiefs @ Knights

Follow on MiLB First Pitch  https //stza.co/+xONR-1V

Shop  https //stza.co/+xONR-1

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Chiefs @ Knights
END:VALARM
DTSTART:20180607T230400Z
DTEND:20180608T020400Z
UID:n_uIGbZDP_oMoTD_lugHFWoe@stanza.co
SUMMARY:Chiefs @ Knights
DESCRIPTION:Chiefs @ Knights\n\nFollow on MiLB First Pitch: https://stza.co/+xONR-1V\n\nShop: https://stza.co/+xONR-1\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144600Z
LAST-MODIFIED:20180213T144600Z
TRANSP:OPAQUE
END:VEVENT
* Chiefs @ Stripers
<2018-06-08 Fri 18:05-21:05>
:PROPERTIES:
:ID:       Tyjy8U1JfQ2Elq8GOiZ6VpQG@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Chiefs @ Stripers Chiefs @ Stripers

Follow on MiLB First Pitch  https //stza.co/+vKoD-1d

Shop  https //stza.co/+vKoD-2t

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Chiefs @ Stripers
END:VALARM
DTSTART:20180608T230500Z
DTEND:20180609T020500Z
UID:Tyjy8U1JfQ2Elq8GOiZ6VpQG@stanza.co
SUMMARY:Chiefs @ Stripers
DESCRIPTION:Chiefs @ Stripers\n\nFollow on MiLB First Pitch: https://stza.co/+vKoD-1d\n\nShop: https://stza.co/+vKoD-2t\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144600Z
LAST-MODIFIED:20180213T144600Z
TRANSP:OPAQUE
END:VEVENT
* Chiefs @ Stripers
<2018-06-09 Sat 17:05-20:05>
:PROPERTIES:
:ID:       ONjgmejJUTLXffbV7VUMdntU@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Chiefs @ Stripers Chiefs @ Stripers

Follow on MiLB First Pitch  https //stza.co/+vKoE-g

Shop  https //stza.co/+vKoE-1T

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Chiefs @ Stripers
END:VALARM
DTSTART:20180609T220500Z
DTEND:20180610T010500Z
UID:ONjgmejJUTLXffbV7VUMdntU@stanza.co
SUMMARY:Chiefs @ Stripers
DESCRIPTION:Chiefs @ Stripers\n\nFollow on MiLB First Pitch: https://stza.co/+vKoE-g\n\nShop: https://stza.co/+vKoE-1T\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144600Z
LAST-MODIFIED:20180213T144600Z
TRANSP:OPAQUE
END:VEVENT
* Chiefs @ Stripers
<2018-06-10 Sun 12:05-15:05>
:PROPERTIES:
:ID:       zK4chkHhkTesbDx2IxQw9VyJ@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Chiefs @ Stripers Chiefs @ Stripers

Follow on MiLB First Pitch  https //stza.co/+vKoF-D

Shop  https //stza.co/+vKoF-i

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Chiefs @ Stripers
END:VALARM
DTSTART:20180610T170500Z
DTEND:20180610T200500Z
UID:zK4chkHhkTesbDx2IxQw9VyJ@stanza.co
SUMMARY:Chiefs @ Stripers
DESCRIPTION:Chiefs @ Stripers\n\nFollow on MiLB First Pitch: https://stza.co/+vKoF-D\n\nShop: https://stza.co/+vKoF-i\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144600Z
LAST-MODIFIED:20180213T144600Z
TRANSP:OPAQUE
END:VEVENT
* Chiefs vs. Red Sox
<2018-06-11 Mon 17:35-20:35>
:PROPERTIES:
:ID:       CY-68i2zeq8x91Xnz9t4qC62@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Chiefs vs. Red Sox Chiefs vs. Red Sox

Follow on MiLB First Pitch  https //stza.co/+u_uY-N

Shop  https //stza.co/+u_uY-e

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Chiefs vs. Red Sox
END:VALARM
DTSTART:20180611T223500Z
DTEND:20180612T013500Z
UID:CY-68i2zeq8x91Xnz9t4qC62@stanza.co
SUMMARY:Chiefs vs. Red Sox
DESCRIPTION:Chiefs vs. Red Sox\n\nFollow on MiLB First Pitch: https://stza.co/+u_uY-N\n\nShop: https://stza.co/+u_uY-e\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144600Z
LAST-MODIFIED:20180213T144600Z
TRANSP:OPAQUE
END:VEVENT
* Chiefs vs. Red Sox
<2018-06-12 Tue 17:35-20:35>
:PROPERTIES:
:ID:       kh6e0y_m_3qDuwAXLK7fV_c6@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Chiefs vs. Red Sox Chiefs vs. Red Sox

Follow on MiLB First Pitch  https //stza.co/+u_uZ-24

Shop  https //stza.co/+u_uZ-2K

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Chiefs vs. Red Sox
END:VALARM
DTSTART:20180612T223500Z
DTEND:20180613T013500Z
UID:kh6e0y_m_3qDuwAXLK7fV_c6@stanza.co
SUMMARY:Chiefs vs. Red Sox
DESCRIPTION:Chiefs vs. Red Sox\n\nFollow on MiLB First Pitch: https://stza.co/+u_uZ-24\n\nShop: https://stza.co/+u_uZ-2K\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144600Z
LAST-MODIFIED:20180213T144600Z
TRANSP:OPAQUE
END:VEVENT
* Chiefs vs. Red Sox
<2018-06-13 Wed 17:35-20:35>
:PROPERTIES:
:ID:       UHWnr8-9qKzw_5DkrgXMAQ29@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Chiefs vs. Red Sox Chiefs vs. Red Sox

Follow on MiLB First Pitch  https //stza.co/+u_u$-2I

Shop  https //stza.co/+u_u$-3Q

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Chiefs vs. Red Sox
END:VALARM
DTSTART:20180613T223500Z
DTEND:20180614T013500Z
UID:UHWnr8-9qKzw_5DkrgXMAQ29@stanza.co
SUMMARY:Chiefs vs. Red Sox
DESCRIPTION:Chiefs vs. Red Sox\n\nFollow on MiLB First Pitch: https://stza.co/+u_u$-2I\n\nShop: https://stza.co/+u_u$-3Q\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144600Z
LAST-MODIFIED:20180213T144600Z
TRANSP:OPAQUE
END:VEVENT
* Chiefs vs. RailRiders
<2018-06-14 Thu 17:35-20:35>
:PROPERTIES:
:ID:       3Ndu4POo7wGOZvDsUVpI_D_r@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Chiefs vs. RailRiders Chiefs vs. RailRiders

Follow on MiLB First Pitch  https //stza.co/+u_v1-2L

Shop  https //stza.co/+u_v1-2z

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Chiefs vs. RailRiders
END:VALARM
DTSTART:20180614T223500Z
DTEND:20180615T013500Z
UID:3Ndu4POo7wGOZvDsUVpI_D_r@stanza.co
SUMMARY:Chiefs vs. RailRiders
DESCRIPTION:Chiefs vs. RailRiders\n\nFollow on MiLB First Pitch: https://stza.co/+u_v1-2L\n\nShop: https://stza.co/+u_v1-2z\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144600Z
LAST-MODIFIED:20180213T144600Z
TRANSP:OPAQUE
END:VEVENT
* Chiefs vs. RailRiders
<2018-06-15 Fri 18:05-21:05>
:PROPERTIES:
:ID:       soFAUOkp2TVWfpUGG6lfUfm7@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Chiefs vs. RailRiders Chiefs vs. RailRiders

Follow on MiLB First Pitch  https //stza.co/+u_v4-3h

Shop  https //stza.co/+u_v4-1i

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Chiefs vs. RailRiders
END:VALARM
DTSTART:20180615T230500Z
DTEND:20180616T020500Z
UID:soFAUOkp2TVWfpUGG6lfUfm7@stanza.co
SUMMARY:Chiefs vs. RailRiders
DESCRIPTION:Chiefs vs. RailRiders\n\nFollow on MiLB First Pitch: https://stza.co/+u_v4-3h\n\nShop: https://stza.co/+u_v4-1i\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144600Z
LAST-MODIFIED:20180213T144600Z
TRANSP:OPAQUE
END:VEVENT
* Chiefs vs. RailRiders
<2018-06-16 Sat 18:05-21:05>
:PROPERTIES:
:ID:       KDDKg4K1698eQK5aJrPw13AL@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Chiefs vs. RailRiders Chiefs vs. RailRiders

Follow on MiLB First Pitch  https //stza.co/+u_v6-3C

Shop  https //stza.co/+u_v6-2W

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Chiefs vs. RailRiders
END:VALARM
DTSTART:20180616T230500Z
DTEND:20180617T020500Z
UID:KDDKg4K1698eQK5aJrPw13AL@stanza.co
SUMMARY:Chiefs vs. RailRiders
DESCRIPTION:Chiefs vs. RailRiders\n\nFollow on MiLB First Pitch: https://stza.co/+u_v6-3C\n\nShop: https://stza.co/+u_v6-2W\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144600Z
LAST-MODIFIED:20180213T144600Z
TRANSP:OPAQUE
END:VEVENT
* Chiefs vs. RailRiders
<2018-06-17 Sun 12:05-15:05>
:PROPERTIES:
:ID:       KK_olT5KgMmY67QcmQc9p1c0@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Chiefs vs. RailRiders Chiefs vs. RailRiders

Follow on MiLB First Pitch  https //stza.co/+u_v7-p

Shop  https //stza.co/+u_v7-O

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Chiefs vs. RailRiders
END:VALARM
DTSTART:20180617T170500Z
DTEND:20180617T200500Z
UID:KK_olT5KgMmY67QcmQc9p1c0@stanza.co
SUMMARY:Chiefs vs. RailRiders
DESCRIPTION:Chiefs vs. RailRiders\n\nFollow on MiLB First Pitch: https://stza.co/+u_v7-p\n\nShop: https://stza.co/+u_v7-O\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144600Z
LAST-MODIFIED:20180213T144600Z
TRANSP:OPAQUE
END:VEVENT
* Chiefs @ Red Wings
<2018-06-19 Tue 18:05-21:05>
:PROPERTIES:
:ID:       wAuVGwsIsLiZ6grwCTLAqPKr@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Chiefs @ Red Wings Chiefs @ Red Wings

Follow on MiLB First Pitch  https //stza.co/+vKp8-1l

Shop  https //stza.co/+vKp8-k

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Chiefs @ Red Wings
END:VALARM
DTSTART:20180619T230500Z
DTEND:20180620T020500Z
UID:wAuVGwsIsLiZ6grwCTLAqPKr@stanza.co
SUMMARY:Chiefs @ Red Wings
DESCRIPTION:Chiefs @ Red Wings\n\nFollow on MiLB First Pitch: https://stza.co/+vKp8-1l\n\nShop: https://stza.co/+vKp8-k\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144600Z
LAST-MODIFIED:20180213T144600Z
TRANSP:OPAQUE
END:VEVENT
* Chiefs @ Red Wings
<2018-06-20 Wed 11:35-14:35>
:PROPERTIES:
:ID:       1wifEBYGKr44awgeTFdmwsb4@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Chiefs @ Red Wings Chiefs @ Red Wings

Follow on MiLB First Pitch  https //stza.co/+vKp9-1U

Shop  https //stza.co/+vKp9-3j

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Chiefs @ Red Wings
END:VALARM
DTSTART:20180620T163500Z
DTEND:20180620T193500Z
UID:1wifEBYGKr44awgeTFdmwsb4@stanza.co
SUMMARY:Chiefs @ Red Wings
DESCRIPTION:Chiefs @ Red Wings\n\nFollow on MiLB First Pitch: https://stza.co/+vKp9-1U\n\nShop: https://stza.co/+vKp9-3j\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144600Z
LAST-MODIFIED:20180213T144600Z
TRANSP:OPAQUE
END:VEVENT
* Chiefs @ Red Wings
<2018-06-21 Thu 18:05-21:05>
:PROPERTIES:
:ID:       6dfdYuWez2EFaP2EysOws9IH@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Chiefs @ Red Wings Chiefs @ Red Wings

Follow on MiLB First Pitch  https //stza.co/+vKpa-2u

Shop  https //stza.co/+vKpa-B

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Chiefs @ Red Wings
END:VALARM
DTSTART:20180621T230500Z
DTEND:20180622T020500Z
UID:6dfdYuWez2EFaP2EysOws9IH@stanza.co
SUMMARY:Chiefs @ Red Wings
DESCRIPTION:Chiefs @ Red Wings\n\nFollow on MiLB First Pitch: https://stza.co/+vKpa-2u\n\nShop: https://stza.co/+vKpa-B\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144600Z
LAST-MODIFIED:20180213T144600Z
TRANSP:OPAQUE
END:VEVENT
* Chiefs @ Red Sox
<2018-06-22 Fri 18:05-21:05>
:PROPERTIES:
:ID:       hj4uj_8mBILmHIbyOtanFNSJ@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Chiefs @ Red Sox Chiefs @ Red Sox

Buy tickets here  https //stza.co/~vKoX

Follow on MiLB First Pitch  https //stza.co/+vKoX-b

Shop  https //stza.co/+vKoX-g

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Chiefs @ Red Sox
END:VALARM
DTSTART:20180622T230500Z
DTEND:20180623T020500Z
UID:hj4uj_8mBILmHIbyOtanFNSJ@stanza.co
SUMMARY:Chiefs @ Red Sox
DESCRIPTION:Chiefs @ Red Sox\n\nBuy tickets here: https://stza.co/~vKoX\n\nFollow on MiLB First Pitch: https://stza.co/+vKoX-b\n\nShop: https://stza.co/+vKoX-g\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144600Z
LAST-MODIFIED:20180213T144600Z
TRANSP:OPAQUE
END:VEVENT
* Chiefs @ Red Sox
<2018-06-23 Sat 17:15-20:15>
:PROPERTIES:
:ID:       fLI0pqerhkR5rTTdXQDGk9ln@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Chiefs @ Red Sox Chiefs @ Red Sox

Buy tickets here  https //stza.co/~vKoY

Follow on MiLB First Pitch  https //stza.co/+vKoY-3I

Shop  https //stza.co/+vKoY-M

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Chiefs @ Red Sox
END:VALARM
DTSTART:20180623T221500Z
DTEND:20180624T011500Z
UID:fLI0pqerhkR5rTTdXQDGk9ln@stanza.co
SUMMARY:Chiefs @ Red Sox
DESCRIPTION:Chiefs @ Red Sox\n\nBuy tickets here: https://stza.co/~vKoY\n\nFollow on MiLB First Pitch: https://stza.co/+vKoY-3I\n\nShop: https://stza.co/+vKoY-M\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144600Z
LAST-MODIFIED:20180213T144600Z
TRANSP:OPAQUE
END:VEVENT
* Chiefs @ Red Sox
<2018-06-24 Sun 12:35-15:35>
:PROPERTIES:
:ID:       XSvZZbvEA6XJjJyTOHIPFRDm@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Chiefs @ Red Sox Chiefs @ Red Sox

Buy tickets here  https //stza.co/~vKoZ

Follow on MiLB First Pitch  https //stza.co/+vKoZ-1s

Shop  https //stza.co/+vKoZ-2P

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Chiefs @ Red Sox
END:VALARM
DTSTART:20180624T173500Z
DTEND:20180624T203500Z
UID:XSvZZbvEA6XJjJyTOHIPFRDm@stanza.co
SUMMARY:Chiefs @ Red Sox
DESCRIPTION:Chiefs @ Red Sox\n\nBuy tickets here: https://stza.co/~vKoZ\n\nFollow on MiLB First Pitch: https://stza.co/+vKoZ-1s\n\nShop: https://stza.co/+vKoZ-2P\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144600Z
LAST-MODIFIED:20180213T144600Z
TRANSP:OPAQUE
END:VEVENT
* Chiefs vs. Red Wings
<2018-06-25 Mon 17:35-20:35>
:PROPERTIES:
:ID:       Abgjd8xznfEvnKJ7BX6AVXyp@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Chiefs vs. Red Wings Chiefs vs. Red Wings

Follow on MiLB First Pitch  https //stza.co/+u_va-1o

Shop  https //stza.co/+u_va-2e

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Chiefs vs. Red Wings
END:VALARM
DTSTART:20180625T223500Z
DTEND:20180626T013500Z
UID:Abgjd8xznfEvnKJ7BX6AVXyp@stanza.co
SUMMARY:Chiefs vs. Red Wings
DESCRIPTION:Chiefs vs. Red Wings\n\nFollow on MiLB First Pitch: https://stza.co/+u_va-1o\n\nShop: https://stza.co/+u_va-2e\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144600Z
LAST-MODIFIED:20180213T144600Z
TRANSP:OPAQUE
END:VEVENT
* Chiefs vs. Red Wings
<2018-06-26 Tue 17:35-20:35>
:PROPERTIES:
:ID:       VvxE44NHYl1jeIRv1AdLfVsY@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Chiefs vs. Red Wings Chiefs vs. Red Wings

Follow on MiLB First Pitch  https //stza.co/+u_vc-N

Shop  https //stza.co/+u_vc-O

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Chiefs vs. Red Wings
END:VALARM
DTSTART:20180626T223500Z
DTEND:20180627T013500Z
UID:VvxE44NHYl1jeIRv1AdLfVsY@stanza.co
SUMMARY:Chiefs vs. Red Wings
DESCRIPTION:Chiefs vs. Red Wings\n\nFollow on MiLB First Pitch: https://stza.co/+u_vc-N\n\nShop: https://stza.co/+u_vc-O\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144600Z
LAST-MODIFIED:20180213T144600Z
TRANSP:OPAQUE
END:VEVENT
* Chiefs vs. Red Wings
<2018-06-27 Wed 17:35-20:35>
:PROPERTIES:
:ID:       42iCXKH6GcOcUGzK7sASDUAa@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Chiefs vs. Red Wings Chiefs vs. Red Wings

Follow on MiLB First Pitch  https //stza.co/+u_ve-a

Shop  https //stza.co/+u_ve-1$

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Chiefs vs. Red Wings
END:VALARM
DTSTART:20180627T223500Z
DTEND:20180628T013500Z
UID:42iCXKH6GcOcUGzK7sASDUAa@stanza.co
SUMMARY:Chiefs vs. Red Wings
DESCRIPTION:Chiefs vs. Red Wings\n\nFollow on MiLB First Pitch: https://stza.co/+u_ve-a\n\nShop: https://stza.co/+u_ve-1$\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144600Z
LAST-MODIFIED:20180213T144600Z
TRANSP:OPAQUE
END:VEVENT
* Chiefs vs. Red Wings
<2018-06-28 Thu 17:35-20:35>
:PROPERTIES:
:ID:       _hiu5VX6bacSRP35qseUsuh3@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Chiefs vs. Red Wings Chiefs vs. Red Wings

Follow on MiLB First Pitch  https //stza.co/+u_vf-3u

Shop  https //stza.co/+u_vf-3g

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Chiefs vs. Red Wings
END:VALARM
DTSTART:20180628T223500Z
DTEND:20180629T013500Z
UID:_hiu5VX6bacSRP35qseUsuh3@stanza.co
SUMMARY:Chiefs vs. Red Wings
DESCRIPTION:Chiefs vs. Red Wings\n\nFollow on MiLB First Pitch: https://stza.co/+u_vf-3u\n\nShop: https://stza.co/+u_vf-3g\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144600Z
LAST-MODIFIED:20180213T144600Z
TRANSP:OPAQUE
END:VEVENT
* Chiefs vs. Bisons
<2018-06-29 Fri 18:05-21:05>
:PROPERTIES:
:ID:       jAFUtcoGPK-_kbe9FB0_pjIr@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Chiefs vs. Bisons Chiefs vs. Bisons

Follow on MiLB First Pitch  https //stza.co/+u_vh-O

Shop  https //stza.co/+u_vh-25

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Chiefs vs. Bisons
END:VALARM
DTSTART:20180629T230500Z
DTEND:20180630T020500Z
UID:jAFUtcoGPK-_kbe9FB0_pjIr@stanza.co
SUMMARY:Chiefs vs. Bisons
DESCRIPTION:Chiefs vs. Bisons\n\nFollow on MiLB First Pitch: https://stza.co/+u_vh-O\n\nShop: https://stza.co/+u_vh-25\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144600Z
LAST-MODIFIED:20180213T144600Z
TRANSP:OPAQUE
END:VEVENT
* Chiefs vs. Bisons
<2018-06-30 Sat 18:05-21:05>
:PROPERTIES:
:ID:       RGH2sasWrXsEFJTTmgLAxedZ@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Chiefs vs. Bisons Chiefs vs. Bisons

Follow on MiLB First Pitch  https //stza.co/+u_vk-3U

Shop  https //stza.co/+u_vk-3M

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Chiefs vs. Bisons
END:VALARM
DTSTART:20180630T230500Z
DTEND:20180701T020500Z
UID:RGH2sasWrXsEFJTTmgLAxedZ@stanza.co
SUMMARY:Chiefs vs. Bisons
DESCRIPTION:Chiefs vs. Bisons\n\nFollow on MiLB First Pitch: https://stza.co/+u_vk-3U\n\nShop: https://stza.co/+u_vk-3M\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144600Z
LAST-MODIFIED:20180213T144600Z
TRANSP:OPAQUE
END:VEVENT
* Chiefs vs. Bisons
<2018-07-01 Sun 12:05-15:05>
:PROPERTIES:
:ID:       PqRDTEbkqeWcxHHpCj7JR8Br@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Chiefs vs. Bisons Chiefs vs. Bisons

Follow on MiLB First Pitch  https //stza.co/+u_vm-1t

Shop  https //stza.co/+u_vm-3A

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Chiefs vs. Bisons
END:VALARM
DTSTART:20180701T170500Z
DTEND:20180701T200500Z
UID:PqRDTEbkqeWcxHHpCj7JR8Br@stanza.co
SUMMARY:Chiefs vs. Bisons
DESCRIPTION:Chiefs vs. Bisons\n\nFollow on MiLB First Pitch: https://stza.co/+u_vm-1t\n\nShop: https://stza.co/+u_vm-3A\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144600Z
LAST-MODIFIED:20180213T144600Z
TRANSP:OPAQUE
END:VEVENT
* Chiefs @ IronPigs
<2018-07-02 Mon 18:05-21:05>
:PROPERTIES:
:ID:       1_DqyglP2JwA4xqEQsb0JaN8@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Chiefs @ IronPigs Chiefs @ IronPigs

Follow on MiLB First Pitch  https //stza.co/+vKoM-2v

Shop  https //stza.co/+vKoM-2o

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Chiefs @ IronPigs
END:VALARM
DTSTART:20180702T230500Z
DTEND:20180703T020500Z
UID:1_DqyglP2JwA4xqEQsb0JaN8@stanza.co
SUMMARY:Chiefs @ IronPigs
DESCRIPTION:Chiefs @ IronPigs\n\nFollow on MiLB First Pitch: https://stza.co/+vKoM-2v\n\nShop: https://stza.co/+vKoM-2o\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144600Z
LAST-MODIFIED:20180213T144600Z
TRANSP:OPAQUE
END:VEVENT
* Chiefs @ IronPigs
<2018-07-03 Tue 18:05-21:05>
:PROPERTIES:
:ID:       o2__1aKeuSZwJlMzYENkpIlS@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Chiefs @ IronPigs Chiefs @ IronPigs

Follow on MiLB First Pitch  https //stza.co/+vKoN-R

Shop  https //stza.co/+vKoN-1

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Chiefs @ IronPigs
END:VALARM
DTSTART:20180703T230500Z
DTEND:20180704T020500Z
UID:o2__1aKeuSZwJlMzYENkpIlS@stanza.co
SUMMARY:Chiefs @ IronPigs
DESCRIPTION:Chiefs @ IronPigs\n\nFollow on MiLB First Pitch: https://stza.co/+vKoN-R\n\nShop: https://stza.co/+vKoN-1\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144600Z
LAST-MODIFIED:20180213T144600Z
TRANSP:OPAQUE
END:VEVENT
* Chiefs vs. IronPigs
<2018-07-04 Wed 18:05-21:05>
:PROPERTIES:
:ID:       -2uegBsqjKIhzxR6puzNy3pp@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Chiefs vs. IronPigs Chiefs vs. IronPigs

Follow on MiLB First Pitch  https //stza.co/+u_vo-1o

Shop  https //stza.co/+u_vo-2A

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Chiefs vs. IronPigs
END:VALARM
DTSTART:20180704T230500Z
DTEND:20180705T020500Z
UID:-2uegBsqjKIhzxR6puzNy3pp@stanza.co
SUMMARY:Chiefs vs. IronPigs
DESCRIPTION:Chiefs vs. IronPigs\n\nFollow on MiLB First Pitch: https://stza.co/+u_vo-1o\n\nShop: https://stza.co/+u_vo-2A\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144600Z
LAST-MODIFIED:20180213T144600Z
TRANSP:OPAQUE
END:VEVENT
* Chiefs vs. IronPigs
<2018-07-05 Thu 18:05-21:05>
:PROPERTIES:
:ID:       dcshUImyzcHUOyY49F0y9dTe@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Chiefs vs. IronPigs Chiefs vs. IronPigs

Follow on MiLB First Pitch  https //stza.co/+u_vq-3L

Shop  https //stza.co/+u_vq-3H

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Chiefs vs. IronPigs
END:VALARM
DTSTART:20180705T230500Z
DTEND:20180706T020500Z
UID:dcshUImyzcHUOyY49F0y9dTe@stanza.co
SUMMARY:Chiefs vs. IronPigs
DESCRIPTION:Chiefs vs. IronPigs\n\nFollow on MiLB First Pitch: https://stza.co/+u_vq-3L\n\nShop: https://stza.co/+u_vq-3H\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144600Z
LAST-MODIFIED:20180213T144600Z
TRANSP:OPAQUE
END:VEVENT
* Chiefs @ Bisons
<2018-07-06 Fri 18:05-21:05>
:PROPERTIES:
:ID:       j42IcJoBHIy8fRg1eRn8qa6w@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Chiefs @ Bisons Chiefs @ Bisons

Follow on MiLB First Pitch  https //stza.co/+vKoq-17

Shop  https //stza.co/+vKoq-2F

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Chiefs @ Bisons
END:VALARM
DTSTART:20180706T230500Z
DTEND:20180707T020500Z
UID:j42IcJoBHIy8fRg1eRn8qa6w@stanza.co
SUMMARY:Chiefs @ Bisons
DESCRIPTION:Chiefs @ Bisons\n\nFollow on MiLB First Pitch: https://stza.co/+vKoq-17\n\nShop: https://stza.co/+vKoq-2F\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144600Z
LAST-MODIFIED:20180213T144600Z
TRANSP:OPAQUE
END:VEVENT
* Chiefs @ Bisons
<2018-07-07 Sat 17:05-20:05>
:PROPERTIES:
:ID:       3myHiFXZK1_v4dt5YLwXNJeR@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Chiefs @ Bisons Chiefs @ Bisons

Follow on MiLB First Pitch  https //stza.co/+vKor-m

Shop  https //stza.co/+vKor-2E

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Chiefs @ Bisons
END:VALARM
DTSTART:20180707T220500Z
DTEND:20180708T010500Z
UID:3myHiFXZK1_v4dt5YLwXNJeR@stanza.co
SUMMARY:Chiefs @ Bisons
DESCRIPTION:Chiefs @ Bisons\n\nFollow on MiLB First Pitch: https://stza.co/+vKor-m\n\nShop: https://stza.co/+vKor-2E\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144600Z
LAST-MODIFIED:20180213T144600Z
TRANSP:OPAQUE
END:VEVENT
* Chiefs @ Bisons
<2018-07-08 Sun 12:05-15:05>
:PROPERTIES:
:ID:       HMuOyk4gk6QI9AWbSmdBFCRR@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Chiefs @ Bisons Chiefs @ Bisons

Follow on MiLB First Pitch  https //stza.co/+vKos-3k

Shop  https //stza.co/+vKos-W

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Chiefs @ Bisons
END:VALARM
DTSTART:20180708T170500Z
DTEND:20180708T200500Z
UID:HMuOyk4gk6QI9AWbSmdBFCRR@stanza.co
SUMMARY:Chiefs @ Bisons
DESCRIPTION:Chiefs @ Bisons\n\nFollow on MiLB First Pitch: https://stza.co/+vKos-3k\n\nShop: https://stza.co/+vKos-W\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144600Z
LAST-MODIFIED:20180213T144600Z
TRANSP:OPAQUE
END:VEVENT
* Chiefs @ Red Sox
<2018-07-12 Thu 18:05-21:05>
:PROPERTIES:
:ID:       bhYO8T0_q8acnu_ez3M8VR6b@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Chiefs @ Red Sox Chiefs @ Red Sox

Buy tickets here  https //stza.co/~vKo_

Follow on MiLB First Pitch  https //stza.co/+vKo_-3S

Shop  https //stza.co/+vKo_-b

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Chiefs @ Red Sox
END:VALARM
DTSTART:20180712T230500Z
DTEND:20180713T020500Z
UID:bhYO8T0_q8acnu_ez3M8VR6b@stanza.co
SUMMARY:Chiefs @ Red Sox
DESCRIPTION:Chiefs @ Red Sox\n\nBuy tickets here: https://stza.co/~vKo_\n\nFollow on MiLB First Pitch: https://stza.co/+vKo_-3S\n\nShop: https://stza.co/+vKo_-b\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144600Z
LAST-MODIFIED:20180213T144600Z
TRANSP:OPAQUE
END:VEVENT
* Chiefs @ Red Sox
<2018-07-13 Fri 18:05-21:05>
:PROPERTIES:
:ID:       qrlnpCk_S3_3rrCVruqAuPO2@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Chiefs @ Red Sox Chiefs @ Red Sox

Buy tickets here  https //stza.co/~vKo$

Follow on MiLB First Pitch  https //stza.co/+vKo$-E

Shop  https //stza.co/+vKo$-2Z

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Chiefs @ Red Sox
END:VALARM
DTSTART:20180713T230500Z
DTEND:20180714T020500Z
UID:qrlnpCk_S3_3rrCVruqAuPO2@stanza.co
SUMMARY:Chiefs @ Red Sox
DESCRIPTION:Chiefs @ Red Sox\n\nBuy tickets here: https://stza.co/~vKo$\n\nFollow on MiLB First Pitch: https://stza.co/+vKo$-E\n\nShop: https://stza.co/+vKo$-2Z\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144600Z
LAST-MODIFIED:20180213T144600Z
TRANSP:OPAQUE
END:VEVENT
* Chiefs @ Red Sox
<2018-07-14 Sat 17:15-20:15>
:PROPERTIES:
:ID:       Bt8JpHxGv1g1-RB-vjm2EUHP@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Chiefs @ Red Sox Chiefs @ Red Sox

Buy tickets here  https //stza.co/~vKp0

Follow on MiLB First Pitch  https //stza.co/+vKp0-1v

Shop  https //stza.co/+vKp0-3M

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Chiefs @ Red Sox
END:VALARM
DTSTART:20180714T221500Z
DTEND:20180715T011500Z
UID:Bt8JpHxGv1g1-RB-vjm2EUHP@stanza.co
SUMMARY:Chiefs @ Red Sox
DESCRIPTION:Chiefs @ Red Sox\n\nBuy tickets here: https://stza.co/~vKp0\n\nFollow on MiLB First Pitch: https://stza.co/+vKp0-1v\n\nShop: https://stza.co/+vKp0-3M\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144600Z
LAST-MODIFIED:20180213T144600Z
TRANSP:OPAQUE
END:VEVENT
* Chiefs @ Red Sox
<2018-07-15 Sun 12:35-15:35>
:PROPERTIES:
:ID:       7zSPy6B_pKtZwKhp9lPrLEOg@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Chiefs @ Red Sox Chiefs @ Red Sox

Buy tickets here  https //stza.co/~vKp1

Follow on MiLB First Pitch  https //stza.co/+vKp1-3A

Shop  https //stza.co/+vKp1-17

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Chiefs @ Red Sox
END:VALARM
DTSTART:20180715T173500Z
DTEND:20180715T203500Z
UID:7zSPy6B_pKtZwKhp9lPrLEOg@stanza.co
SUMMARY:Chiefs @ Red Sox
DESCRIPTION:Chiefs @ Red Sox\n\nBuy tickets here: https://stza.co/~vKp1\n\nFollow on MiLB First Pitch: https://stza.co/+vKp1-3A\n\nShop: https://stza.co/+vKp1-17\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144600Z
LAST-MODIFIED:20180213T144600Z
TRANSP:OPAQUE
END:VEVENT
* Chiefs vs. Bulls
<2018-07-16 Mon 17:35-20:35>
:PROPERTIES:
:ID:       77AtoRTKZRASkOG_OVY_9QBx@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Chiefs vs. Bulls Chiefs vs. Bulls

Follow on MiLB First Pitch  https //stza.co/+u_vs-L

Shop  https //stza.co/+u_vs-37

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Chiefs vs. Bulls
END:VALARM
DTSTART:20180716T223500Z
DTEND:20180717T013500Z
UID:77AtoRTKZRASkOG_OVY_9QBx@stanza.co
SUMMARY:Chiefs vs. Bulls
DESCRIPTION:Chiefs vs. Bulls\n\nFollow on MiLB First Pitch: https://stza.co/+u_vs-L\n\nShop: https://stza.co/+u_vs-37\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144600Z
LAST-MODIFIED:20180213T144600Z
TRANSP:OPAQUE
END:VEVENT
* Chiefs vs. Bulls
<2018-07-17 Tue 17:35-20:35>
:PROPERTIES:
:ID:       Z56Y8AF8lRaC3duOfZjjoTWl@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Chiefs vs. Bulls Chiefs vs. Bulls

Follow on MiLB First Pitch  https //stza.co/+u_vt-3H

Shop  https //stza.co/+u_vt-_

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Chiefs vs. Bulls
END:VALARM
DTSTART:20180717T223500Z
DTEND:20180718T013500Z
UID:Z56Y8AF8lRaC3duOfZjjoTWl@stanza.co
SUMMARY:Chiefs vs. Bulls
DESCRIPTION:Chiefs vs. Bulls\n\nFollow on MiLB First Pitch: https://stza.co/+u_vt-3H\n\nShop: https://stza.co/+u_vt-_\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144600Z
LAST-MODIFIED:20180213T144600Z
TRANSP:OPAQUE
END:VEVENT
* Chiefs vs. Bulls
<2018-07-18 Wed 11:00-14:00>
:PROPERTIES:
:ID:       9xpL7XFqWppkr9g2WGwbvM3B@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Chiefs vs. Bulls Chiefs vs. Bulls

Follow on MiLB First Pitch  https //stza.co/+y4zY-3k

Shop  https //stza.co/+y4zY-3J

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Chiefs vs. Bulls
END:VALARM
DTSTART:20180718T160000Z
DTEND:20180718T190000Z
UID:9xpL7XFqWppkr9g2WGwbvM3B@stanza.co
SUMMARY:Chiefs vs. Bulls
DESCRIPTION:Chiefs vs. Bulls\n\nFollow on MiLB First Pitch: https://stza.co/+y4zY-3k\n\nShop: https://stza.co/+y4zY-3J\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144600Z
LAST-MODIFIED:20180213T144600Z
TRANSP:OPAQUE
END:VEVENT
* Chiefs vs. Bats
<2018-07-19 Thu 17:35-20:35>
:PROPERTIES:
:ID:       z12OKPKCK34ePk0xg46-BEKB@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Chiefs vs. Bats Chiefs vs. Bats

Follow on MiLB First Pitch  https //stza.co/+u_vx-H

Shop  https //stza.co/+u_vx-B

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Chiefs vs. Bats
END:VALARM
DTSTART:20180719T223500Z
DTEND:20180720T013500Z
UID:z12OKPKCK34ePk0xg46-BEKB@stanza.co
SUMMARY:Chiefs vs. Bats
DESCRIPTION:Chiefs vs. Bats\n\nFollow on MiLB First Pitch: https://stza.co/+u_vx-H\n\nShop: https://stza.co/+u_vx-B\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144600Z
LAST-MODIFIED:20180213T144600Z
TRANSP:OPAQUE
END:VEVENT
* Chiefs vs. Bats
<2018-07-20 Fri 18:05-21:05>
:PROPERTIES:
:ID:       PeIFUdJEbA5YfENQ8Qy-dIsP@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Chiefs vs. Bats Chiefs vs. Bats

Follow on MiLB First Pitch  https //stza.co/+u_vz-1e

Shop  https //stza.co/+u_vz-V

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Chiefs vs. Bats
END:VALARM
DTSTART:20180720T230500Z
DTEND:20180721T020500Z
UID:PeIFUdJEbA5YfENQ8Qy-dIsP@stanza.co
SUMMARY:Chiefs vs. Bats
DESCRIPTION:Chiefs vs. Bats\n\nFollow on MiLB First Pitch: https://stza.co/+u_vz-1e\n\nShop: https://stza.co/+u_vz-V\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144600Z
LAST-MODIFIED:20180213T144600Z
TRANSP:OPAQUE
END:VEVENT
* Chiefs vs. Bats
<2018-07-21 Sat 18:05-21:05>
:PROPERTIES:
:ID:       zOVQFwItI5gfRNneHEE9YJom@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Chiefs vs. Bats Chiefs vs. Bats

Follow on MiLB First Pitch  https //stza.co/+u_vB-2$

Shop  https //stza.co/+u_vB-1K

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Chiefs vs. Bats
END:VALARM
DTSTART:20180721T230500Z
DTEND:20180722T020500Z
UID:zOVQFwItI5gfRNneHEE9YJom@stanza.co
SUMMARY:Chiefs vs. Bats
DESCRIPTION:Chiefs vs. Bats\n\nFollow on MiLB First Pitch: https://stza.co/+u_vB-2$\n\nShop: https://stza.co/+u_vB-1K\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144600Z
LAST-MODIFIED:20180213T144600Z
TRANSP:OPAQUE
END:VEVENT
* Chiefs vs. Bats
<2018-07-22 Sun 12:05-15:05>
:PROPERTIES:
:ID:       5F0opKivQpQBgqnXoTb4ddDJ@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Chiefs vs. Bats Chiefs vs. Bats

Follow on MiLB First Pitch  https //stza.co/+u_vE-3E

Shop  https //stza.co/+u_vE-3P

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Chiefs vs. Bats
END:VALARM
DTSTART:20180722T170500Z
DTEND:20180722T200500Z
UID:5F0opKivQpQBgqnXoTb4ddDJ@stanza.co
SUMMARY:Chiefs vs. Bats
DESCRIPTION:Chiefs vs. Bats\n\nFollow on MiLB First Pitch: https://stza.co/+u_vE-3E\n\nShop: https://stza.co/+u_vE-3P\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144600Z
LAST-MODIFIED:20180213T144600Z
TRANSP:OPAQUE
END:VEVENT
* Chiefs @ Tides
<2018-07-24 Tue 18:05-21:05>
:PROPERTIES:
:ID:       87EZpVnXi6cruO6lQQS_J-nw@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Chiefs @ Tides Chiefs @ Tides

Follow on MiLB First Pitch  https //stza.co/+vKoU-2F

Shop  https //stza.co/+vKoU-m

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Chiefs @ Tides
END:VALARM
DTSTART:20180724T230500Z
DTEND:20180725T020500Z
UID:87EZpVnXi6cruO6lQQS_J-nw@stanza.co
SUMMARY:Chiefs @ Tides
DESCRIPTION:Chiefs @ Tides\n\nFollow on MiLB First Pitch: https://stza.co/+vKoU-2F\n\nShop: https://stza.co/+vKoU-m\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144600Z
LAST-MODIFIED:20180213T144600Z
TRANSP:OPAQUE
END:VEVENT
* Chiefs @ Tides
<2018-07-25 Wed 18:05-21:05>
:PROPERTIES:
:ID:       Swj4p-l3fP-xeBRLvbMcavzV@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Chiefs @ Tides Chiefs @ Tides

Follow on MiLB First Pitch  https //stza.co/+vKoV-1z

Shop  https //stza.co/+vKoV-32

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Chiefs @ Tides
END:VALARM
DTSTART:20180725T230500Z
DTEND:20180726T020500Z
UID:Swj4p-l3fP-xeBRLvbMcavzV@stanza.co
SUMMARY:Chiefs @ Tides
DESCRIPTION:Chiefs @ Tides\n\nFollow on MiLB First Pitch: https://stza.co/+vKoV-1z\n\nShop: https://stza.co/+vKoV-32\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144600Z
LAST-MODIFIED:20180213T144600Z
TRANSP:OPAQUE
END:VEVENT
* Chiefs @ Tides
<2018-07-26 Thu 11:05-14:05>
:PROPERTIES:
:ID:       _LAdvGRw76cgUxGDmbrjhEXY@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Chiefs @ Tides Chiefs @ Tides

Follow on MiLB First Pitch  https //stza.co/+vKoW-21

Shop  https //stza.co/+vKoW-23

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Chiefs @ Tides
END:VALARM
DTSTART:20180726T160500Z
DTEND:20180726T190500Z
UID:_LAdvGRw76cgUxGDmbrjhEXY@stanza.co
SUMMARY:Chiefs @ Tides
DESCRIPTION:Chiefs @ Tides\n\nFollow on MiLB First Pitch: https://stza.co/+vKoW-21\n\nShop: https://stza.co/+vKoW-23\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144600Z
LAST-MODIFIED:20180213T144600Z
TRANSP:OPAQUE
END:VEVENT
* Chiefs @ Bulls
<2018-07-27 Fri 18:05-21:05>
:PROPERTIES:
:ID:       AgS-kQWW6aDsDLkmbhbLqOcv@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Chiefs @ Bulls Chiefs @ Bulls

Follow on MiLB First Pitch  https //stza.co/+vKoA-1x

Shop  https //stza.co/+vKoA-1Y

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Chiefs @ Bulls
END:VALARM
DTSTART:20180727T230500Z
DTEND:20180728T020500Z
UID:AgS-kQWW6aDsDLkmbhbLqOcv@stanza.co
SUMMARY:Chiefs @ Bulls
DESCRIPTION:Chiefs @ Bulls\n\nFollow on MiLB First Pitch: https://stza.co/+vKoA-1x\n\nShop: https://stza.co/+vKoA-1Y\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144600Z
LAST-MODIFIED:20180213T144600Z
TRANSP:OPAQUE
END:VEVENT
* Chiefs @ Bulls
<2018-07-28 Sat 17:35-20:35>
:PROPERTIES:
:ID:       yNqD1h-kOK38A_t-0Rz2yJAZ@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Chiefs @ Bulls Chiefs @ Bulls

Follow on MiLB First Pitch  https //stza.co/+vKoB-q

Shop  https //stza.co/+vKoB-L

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Chiefs @ Bulls
END:VALARM
DTSTART:20180728T223500Z
DTEND:20180729T013500Z
UID:yNqD1h-kOK38A_t-0Rz2yJAZ@stanza.co
SUMMARY:Chiefs @ Bulls
DESCRIPTION:Chiefs @ Bulls\n\nFollow on MiLB First Pitch: https://stza.co/+vKoB-q\n\nShop: https://stza.co/+vKoB-L\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144600Z
LAST-MODIFIED:20180213T144600Z
TRANSP:OPAQUE
END:VEVENT
* Chiefs @ Bulls
<2018-07-29 Sun 16:05-19:05>
:PROPERTIES:
:ID:       VPl5F2zs5pV8nmTk4MY0uoGq@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Chiefs @ Bulls Chiefs @ Bulls

Follow on MiLB First Pitch  https //stza.co/+vKoC-26

Shop  https //stza.co/+vKoC-3u

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Chiefs @ Bulls
END:VALARM
DTSTART:20180729T210500Z
DTEND:20180730T000500Z
UID:VPl5F2zs5pV8nmTk4MY0uoGq@stanza.co
SUMMARY:Chiefs @ Bulls
DESCRIPTION:Chiefs @ Bulls\n\nFollow on MiLB First Pitch: https://stza.co/+vKoC-26\n\nShop: https://stza.co/+vKoC-3u\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144600Z
LAST-MODIFIED:20180213T144600Z
TRANSP:OPAQUE
END:VEVENT
* Chiefs vs. Red Sox
<2018-07-30 Mon 17:35-20:35>
:PROPERTIES:
:ID:       ZE1dEeBa9x83gjUmQb12smme@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Chiefs vs. Red Sox Chiefs vs. Red Sox

Follow on MiLB First Pitch  https //stza.co/+u_vF-h

Shop  https //stza.co/+u_vF-3a

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Chiefs vs. Red Sox
END:VALARM
DTSTART:20180730T223500Z
DTEND:20180731T013500Z
UID:ZE1dEeBa9x83gjUmQb12smme@stanza.co
SUMMARY:Chiefs vs. Red Sox
DESCRIPTION:Chiefs vs. Red Sox\n\nFollow on MiLB First Pitch: https://stza.co/+u_vF-h\n\nShop: https://stza.co/+u_vF-3a\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144600Z
LAST-MODIFIED:20180213T144600Z
TRANSP:OPAQUE
END:VEVENT
* Chiefs vs. Red Sox
<2018-07-31 Tue 17:35-20:35>
:PROPERTIES:
:ID:       7zRekOE9fKkLl_DPr8wVPCcS@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Chiefs vs. Red Sox Chiefs vs. Red Sox

Follow on MiLB First Pitch  https //stza.co/+u_vI-12

Shop  https //stza.co/+u_vI-9

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Chiefs vs. Red Sox
END:VALARM
DTSTART:20180731T223500Z
DTEND:20180801T013500Z
UID:7zRekOE9fKkLl_DPr8wVPCcS@stanza.co
SUMMARY:Chiefs vs. Red Sox
DESCRIPTION:Chiefs vs. Red Sox\n\nFollow on MiLB First Pitch: https://stza.co/+u_vI-12\n\nShop: https://stza.co/+u_vI-9\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144600Z
LAST-MODIFIED:20180213T144600Z
TRANSP:OPAQUE
END:VEVENT
* Chiefs vs. Red Sox
<2018-08-01 Wed 17:35-20:35>
:PROPERTIES:
:ID:       K7X2XFjJHu4duYz_Y9DyMRtm@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Chiefs vs. Red Sox Chiefs vs. Red Sox

Follow on MiLB First Pitch  https //stza.co/+u_vJ-2

Shop  https //stza.co/+u_vJ-3q

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Chiefs vs. Red Sox
END:VALARM
DTSTART:20180801T223500Z
DTEND:20180802T013500Z
UID:K7X2XFjJHu4duYz_Y9DyMRtm@stanza.co
SUMMARY:Chiefs vs. Red Sox
DESCRIPTION:Chiefs vs. Red Sox\n\nFollow on MiLB First Pitch: https://stza.co/+u_vJ-2\n\nShop: https://stza.co/+u_vJ-3q\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144600Z
LAST-MODIFIED:20180213T144600Z
TRANSP:OPAQUE
END:VEVENT
* Chiefs vs. Red Sox
<2018-08-02 Thu 17:35-20:35>
:PROPERTIES:
:ID:       zalbJgeNk0pQYEQnwWaz9i4W@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Chiefs vs. Red Sox Chiefs vs. Red Sox

Follow on MiLB First Pitch  https //stza.co/+u_vM-s

Shop  https //stza.co/+u_vM-37

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Chiefs vs. Red Sox
END:VALARM
DTSTART:20180802T223500Z
DTEND:20180803T013500Z
UID:zalbJgeNk0pQYEQnwWaz9i4W@stanza.co
SUMMARY:Chiefs vs. Red Sox
DESCRIPTION:Chiefs vs. Red Sox\n\nFollow on MiLB First Pitch: https://stza.co/+u_vM-s\n\nShop: https://stza.co/+u_vM-37\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144600Z
LAST-MODIFIED:20180213T144600Z
TRANSP:OPAQUE
END:VEVENT
* Chiefs @ IronPigs
<2018-08-03 Fri 18:05-21:05>
:PROPERTIES:
:ID:       4HyyDwyxkPx0VVCIRDP1Yqcj@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Chiefs @ IronPigs Chiefs @ IronPigs

Follow on MiLB First Pitch  https //stza.co/+vKoO-O

Shop  https //stza.co/+vKoO-3D

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Chiefs @ IronPigs
END:VALARM
DTSTART:20180803T230500Z
DTEND:20180804T020500Z
UID:4HyyDwyxkPx0VVCIRDP1Yqcj@stanza.co
SUMMARY:Chiefs @ IronPigs
DESCRIPTION:Chiefs @ IronPigs\n\nFollow on MiLB First Pitch: https://stza.co/+vKoO-O\n\nShop: https://stza.co/+vKoO-3D\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144600Z
LAST-MODIFIED:20180213T144600Z
TRANSP:OPAQUE
END:VEVENT
* Chiefs @ IronPigs
<2018-08-04 Sat 17:35-20:35>
:PROPERTIES:
:ID:       pYiiFOrvovcCVI9oAfWiBeqG@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Chiefs @ IronPigs Chiefs @ IronPigs

Follow on MiLB First Pitch  https //stza.co/+vKoP-2s

Shop  https //stza.co/+vKoP-3C

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Chiefs @ IronPigs
END:VALARM
DTSTART:20180804T223500Z
DTEND:20180805T013500Z
UID:pYiiFOrvovcCVI9oAfWiBeqG@stanza.co
SUMMARY:Chiefs @ IronPigs
DESCRIPTION:Chiefs @ IronPigs\n\nFollow on MiLB First Pitch: https://stza.co/+vKoP-2s\n\nShop: https://stza.co/+vKoP-3C\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144600Z
LAST-MODIFIED:20180213T144600Z
TRANSP:OPAQUE
END:VEVENT
* Chiefs @ IronPigs
<2018-08-05 Sun 12:35-15:35>
:PROPERTIES:
:ID:       5lUFEWqZ6qwW1lXNvKTQSio0@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Chiefs @ IronPigs Chiefs @ IronPigs

Follow on MiLB First Pitch  https //stza.co/+vKoQ-1L

Shop  https //stza.co/+vKoQ-1x

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Chiefs @ IronPigs
END:VALARM
DTSTART:20180805T173500Z
DTEND:20180805T203500Z
UID:5lUFEWqZ6qwW1lXNvKTQSio0@stanza.co
SUMMARY:Chiefs @ IronPigs
DESCRIPTION:Chiefs @ IronPigs\n\nFollow on MiLB First Pitch: https://stza.co/+vKoQ-1L\n\nShop: https://stza.co/+vKoQ-1x\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144600Z
LAST-MODIFIED:20180213T144600Z
TRANSP:OPAQUE
END:VEVENT
* Chiefs vs. Knights
<2018-08-07 Tue 17:35-20:35>
:PROPERTIES:
:ID:       uT0tebrlR6xan8oyE1E2PvAG@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Chiefs vs. Knights Chiefs vs. Knights

Follow on MiLB First Pitch  https //stza.co/+u_vO-T

Shop  https //stza.co/+u_vO-3b

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Chiefs vs. Knights
END:VALARM
DTSTART:20180807T223500Z
DTEND:20180808T013500Z
UID:uT0tebrlR6xan8oyE1E2PvAG@stanza.co
SUMMARY:Chiefs vs. Knights
DESCRIPTION:Chiefs vs. Knights\n\nFollow on MiLB First Pitch: https://stza.co/+u_vO-T\n\nShop: https://stza.co/+u_vO-3b\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144600Z
LAST-MODIFIED:20180213T144600Z
TRANSP:OPAQUE
END:VEVENT
* Chiefs vs. Knights
<2018-08-08 Wed 17:35-20:35>
:PROPERTIES:
:ID:       ZAojYWVEbHu25WF0eGGfZLsB@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Chiefs vs. Knights Chiefs vs. Knights

Follow on MiLB First Pitch  https //stza.co/+u_vQ-2a

Shop  https //stza.co/+u_vQ-9

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Chiefs vs. Knights
END:VALARM
DTSTART:20180808T223500Z
DTEND:20180809T013500Z
UID:ZAojYWVEbHu25WF0eGGfZLsB@stanza.co
SUMMARY:Chiefs vs. Knights
DESCRIPTION:Chiefs vs. Knights\n\nFollow on MiLB First Pitch: https://stza.co/+u_vQ-2a\n\nShop: https://stza.co/+u_vQ-9\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144600Z
LAST-MODIFIED:20180213T144600Z
TRANSP:OPAQUE
END:VEVENT
* Chiefs vs. Knights
<2018-08-09 Thu 17:35-20:35>
:PROPERTIES:
:ID:       eA9LflsWjBPxwdLy2vqIsNMF@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Chiefs vs. Knights Chiefs vs. Knights

Follow on MiLB First Pitch  https //stza.co/+u_vR-1u

Shop  https //stza.co/+u_vR-14

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Chiefs vs. Knights
END:VALARM
DTSTART:20180809T223500Z
DTEND:20180810T013500Z
UID:eA9LflsWjBPxwdLy2vqIsNMF@stanza.co
SUMMARY:Chiefs vs. Knights
DESCRIPTION:Chiefs vs. Knights\n\nFollow on MiLB First Pitch: https://stza.co/+u_vR-1u\n\nShop: https://stza.co/+u_vR-14\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144600Z
LAST-MODIFIED:20180213T144600Z
TRANSP:OPAQUE
END:VEVENT
* Chiefs vs. Stripers
<2018-08-10 Fri 18:05-21:05>
:PROPERTIES:
:ID:       kvBp6oCmtyMVyHZKPLtln4gv@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Chiefs vs. Stripers Chiefs vs. Stripers

Follow on MiLB First Pitch  https //stza.co/+u_vT-3F

Shop  https //stza.co/+u_vT-O

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Chiefs vs. Stripers
END:VALARM
DTSTART:20180810T230500Z
DTEND:20180811T020500Z
UID:kvBp6oCmtyMVyHZKPLtln4gv@stanza.co
SUMMARY:Chiefs vs. Stripers
DESCRIPTION:Chiefs vs. Stripers\n\nFollow on MiLB First Pitch: https://stza.co/+u_vT-3F\n\nShop: https://stza.co/+u_vT-O\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144600Z
LAST-MODIFIED:20180213T144600Z
TRANSP:OPAQUE
END:VEVENT
* Chiefs vs. Stripers
<2018-08-11 Sat 18:05-21:05>
:PROPERTIES:
:ID:       I1J2k050n_IT8DBFXK-WGW7p@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Chiefs vs. Stripers Chiefs vs. Stripers

Follow on MiLB First Pitch  https //stza.co/+u_vV-_

Shop  https //stza.co/+u_vV-1F

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Chiefs vs. Stripers
END:VALARM
DTSTART:20180811T230500Z
DTEND:20180812T020500Z
UID:I1J2k050n_IT8DBFXK-WGW7p@stanza.co
SUMMARY:Chiefs vs. Stripers
DESCRIPTION:Chiefs vs. Stripers\n\nFollow on MiLB First Pitch: https://stza.co/+u_vV-_\n\nShop: https://stza.co/+u_vV-1F\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144600Z
LAST-MODIFIED:20180213T144600Z
TRANSP:OPAQUE
END:VEVENT
* Chiefs vs. Stripers
<2018-08-12 Sun 12:05-15:05>
:PROPERTIES:
:ID:       2eK-nd3Ko1uVXY9f27ML8eUb@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Chiefs vs. Stripers Chiefs vs. Stripers

Follow on MiLB First Pitch  https //stza.co/+u_vX-1O

Shop  https //stza.co/+u_vX-3

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Chiefs vs. Stripers
END:VALARM
DTSTART:20180812T170500Z
DTEND:20180812T200500Z
UID:2eK-nd3Ko1uVXY9f27ML8eUb@stanza.co
SUMMARY:Chiefs vs. Stripers
DESCRIPTION:Chiefs vs. Stripers\n\nFollow on MiLB First Pitch: https://stza.co/+u_vX-1O\n\nShop: https://stza.co/+u_vX-3\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144600Z
LAST-MODIFIED:20180213T144600Z
TRANSP:OPAQUE
END:VEVENT
* Chiefs @ Mud Hens
<2018-08-13 Mon 18:05-21:05>
:PROPERTIES:
:ID:       xiMQlaNVQoFb8CU_wY4Syw1w@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Chiefs @ Mud Hens Chiefs @ Mud Hens

Follow on MiLB First Pitch  https //stza.co/+u_wj-y

Shop  https //stza.co/+u_wj-d

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Chiefs @ Mud Hens
END:VALARM
DTSTART:20180813T230500Z
DTEND:20180814T020500Z
UID:xiMQlaNVQoFb8CU_wY4Syw1w@stanza.co
SUMMARY:Chiefs @ Mud Hens
DESCRIPTION:Chiefs @ Mud Hens\n\nFollow on MiLB First Pitch: https://stza.co/+u_wj-y\n\nShop: https://stza.co/+u_wj-d\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144600Z
LAST-MODIFIED:20180213T144600Z
TRANSP:OPAQUE
END:VEVENT
* Chiefs @ Mud Hens
<2018-08-14 Tue 18:05-21:05>
:PROPERTIES:
:ID:       ZMbeqAwxFg5Eb3MbVlBUpKy4@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Chiefs @ Mud Hens Chiefs @ Mud Hens

Follow on MiLB First Pitch  https //stza.co/+u_wk-3P

Shop  https //stza.co/+u_wk-1p

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Chiefs @ Mud Hens
END:VALARM
DTSTART:20180814T230500Z
DTEND:20180815T020500Z
UID:ZMbeqAwxFg5Eb3MbVlBUpKy4@stanza.co
SUMMARY:Chiefs @ Mud Hens
DESCRIPTION:Chiefs @ Mud Hens\n\nFollow on MiLB First Pitch: https://stza.co/+u_wk-3P\n\nShop: https://stza.co/+u_wk-1p\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144600Z
LAST-MODIFIED:20180213T144600Z
TRANSP:OPAQUE
END:VEVENT
* Chiefs @ Mud Hens
<2018-08-15 Wed 18:05-21:05>
:PROPERTIES:
:ID:       -NcmqmTd6lSH9lN95dpShlcR@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Chiefs @ Mud Hens Chiefs @ Mud Hens

Follow on MiLB First Pitch  https //stza.co/+u_wl-6

Shop  https //stza.co/+u_wl-3x

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Chiefs @ Mud Hens
END:VALARM
DTSTART:20180815T230500Z
DTEND:20180816T020500Z
UID:-NcmqmTd6lSH9lN95dpShlcR@stanza.co
SUMMARY:Chiefs @ Mud Hens
DESCRIPTION:Chiefs @ Mud Hens\n\nFollow on MiLB First Pitch: https://stza.co/+u_wl-6\n\nShop: https://stza.co/+u_wl-3x\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144600Z
LAST-MODIFIED:20180213T144600Z
TRANSP:OPAQUE
END:VEVENT
* Chiefs @ Clippers
<2018-08-16 Thu 18:05-21:05>
:PROPERTIES:
:ID:       _1ykYSmGJzM5nIr03h_78as5@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Chiefs @ Clippers Chiefs @ Clippers

Buy tickets here  https //stza.co/~vKow

Follow on MiLB First Pitch  https //stza.co/+vKow-_

Shop  https //stza.co/+vKow-2q

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Chiefs @ Clippers
END:VALARM
DTSTART:20180816T230500Z
DTEND:20180817T020500Z
UID:_1ykYSmGJzM5nIr03h_78as5@stanza.co
SUMMARY:Chiefs @ Clippers
DESCRIPTION:Chiefs @ Clippers\n\nBuy tickets here: https://stza.co/~vKow\n\nFollow on MiLB First Pitch: https://stza.co/+vKow-_\n\nShop: https://stza.co/+vKow-2q\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144600Z
LAST-MODIFIED:20180213T144600Z
TRANSP:OPAQUE
END:VEVENT
* Chiefs @ Clippers
<2018-08-17 Fri 18:15-21:15>
:PROPERTIES:
:ID:       7IfF9fLhOMryVhNOZVuYnfXR@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Chiefs @ Clippers Chiefs @ Clippers

Buy tickets here  https //stza.co/~vKox

Follow on MiLB First Pitch  https //stza.co/+vKox-2s

Shop  https //stza.co/+vKox-3g

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Chiefs @ Clippers
END:VALARM
DTSTART:20180817T231500Z
DTEND:20180818T021500Z
UID:7IfF9fLhOMryVhNOZVuYnfXR@stanza.co
SUMMARY:Chiefs @ Clippers
DESCRIPTION:Chiefs @ Clippers\n\nBuy tickets here: https://stza.co/~vKox\n\nFollow on MiLB First Pitch: https://stza.co/+vKox-2s\n\nShop: https://stza.co/+vKox-3g\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144600Z
LAST-MODIFIED:20180213T144600Z
TRANSP:OPAQUE
END:VEVENT
* Chiefs @ Clippers
<2018-08-18 Sat 18:15-21:15>
:PROPERTIES:
:ID:       bnjcWfBXmR1N8RJw5BdJvcr6@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Chiefs @ Clippers Chiefs @ Clippers

Buy tickets here  https //stza.co/~vKoy

Follow on MiLB First Pitch  https //stza.co/+vKoy-2F

Shop  https //stza.co/+vKoy-$

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Chiefs @ Clippers
END:VALARM
DTSTART:20180818T231500Z
DTEND:20180819T021500Z
UID:bnjcWfBXmR1N8RJw5BdJvcr6@stanza.co
SUMMARY:Chiefs @ Clippers
DESCRIPTION:Chiefs @ Clippers\n\nBuy tickets here: https://stza.co/~vKoy\n\nFollow on MiLB First Pitch: https://stza.co/+vKoy-2F\n\nShop: https://stza.co/+vKoy-$\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144600Z
LAST-MODIFIED:20180213T144600Z
TRANSP:OPAQUE
END:VEVENT
* Chiefs @ Clippers
<2018-08-19 Sun 15:05-18:05>
:PROPERTIES:
:ID:       d2ub9jIXU-1tgiq065dnIYMB@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Chiefs @ Clippers Chiefs @ Clippers

Buy tickets here  https //stza.co/~xzyZ

Follow on MiLB First Pitch  https //stza.co/+xzyZ-2w

Shop  https //stza.co/+xzyZ-3P

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Chiefs @ Clippers
END:VALARM
DTSTART:20180819T200500Z
DTEND:20180819T230500Z
UID:d2ub9jIXU-1tgiq065dnIYMB@stanza.co
SUMMARY:Chiefs @ Clippers
DESCRIPTION:Chiefs @ Clippers\n\nBuy tickets here: https://stza.co/~xzyZ\n\nFollow on MiLB First Pitch: https://stza.co/+xzyZ-2w\n\nShop: https://stza.co/+xzyZ-3P\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144600Z
LAST-MODIFIED:20180213T144600Z
TRANSP:OPAQUE
END:VEVENT
* Chiefs vs. IronPigs
<2018-08-21 Tue 17:35-20:35>
:PROPERTIES:
:ID:       oWfxKAXipw12wzfQWXhyduvY@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Chiefs vs. IronPigs Chiefs vs. IronPigs

Follow on MiLB First Pitch  https //stza.co/+u_v_-2T

Shop  https //stza.co/+u_v_-1L

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Chiefs vs. IronPigs
END:VALARM
DTSTART:20180821T223500Z
DTEND:20180822T013500Z
UID:oWfxKAXipw12wzfQWXhyduvY@stanza.co
SUMMARY:Chiefs vs. IronPigs
DESCRIPTION:Chiefs vs. IronPigs\n\nFollow on MiLB First Pitch: https://stza.co/+u_v_-2T\n\nShop: https://stza.co/+u_v_-1L\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144600Z
LAST-MODIFIED:20180213T144600Z
TRANSP:OPAQUE
END:VEVENT
* Chiefs vs. IronPigs
<2018-08-22 Wed 17:35-20:35>
:PROPERTIES:
:ID:       kK7H7wowdUXZtFCniwAfYinr@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Chiefs vs. IronPigs Chiefs vs. IronPigs

Follow on MiLB First Pitch  https //stza.co/+u_w0-2O

Shop  https //stza.co/+u_w0-3F

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Chiefs vs. IronPigs
END:VALARM
DTSTART:20180822T223500Z
DTEND:20180823T013500Z
UID:kK7H7wowdUXZtFCniwAfYinr@stanza.co
SUMMARY:Chiefs vs. IronPigs
DESCRIPTION:Chiefs vs. IronPigs\n\nFollow on MiLB First Pitch: https://stza.co/+u_w0-2O\n\nShop: https://stza.co/+u_w0-3F\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144600Z
LAST-MODIFIED:20180213T144600Z
TRANSP:OPAQUE
END:VEVENT
* Chiefs vs. IronPigs
<2018-08-23 Thu 17:35-20:35>
:PROPERTIES:
:ID:       nY0Uof2WHheO1tUiNiYB6dRA@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Chiefs vs. IronPigs Chiefs vs. IronPigs

Follow on MiLB First Pitch  https //stza.co/+u_w2-1$

Shop  https //stza.co/+u_w2-E

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Chiefs vs. IronPigs
END:VALARM
DTSTART:20180823T223500Z
DTEND:20180824T013500Z
UID:nY0Uof2WHheO1tUiNiYB6dRA@stanza.co
SUMMARY:Chiefs vs. IronPigs
DESCRIPTION:Chiefs vs. IronPigs\n\nFollow on MiLB First Pitch: https://stza.co/+u_w2-1$\n\nShop: https://stza.co/+u_w2-E\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144600Z
LAST-MODIFIED:20180213T144600Z
TRANSP:OPAQUE
END:VEVENT
* Chiefs vs. Red Wings
<2018-08-24 Fri 18:05-21:05>
:PROPERTIES:
:ID:       rAvVLogEWxnVa_rtGcNfhyg6@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Chiefs vs. Red Wings Chiefs vs. Red Wings

Follow on MiLB First Pitch  https //stza.co/+u_w4-3Y

Shop  https //stza.co/+u_w4-U

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Chiefs vs. Red Wings
END:VALARM
DTSTART:20180824T230500Z
DTEND:20180825T020500Z
UID:rAvVLogEWxnVa_rtGcNfhyg6@stanza.co
SUMMARY:Chiefs vs. Red Wings
DESCRIPTION:Chiefs vs. Red Wings\n\nFollow on MiLB First Pitch: https://stza.co/+u_w4-3Y\n\nShop: https://stza.co/+u_w4-U\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144600Z
LAST-MODIFIED:20180213T144600Z
TRANSP:OPAQUE
END:VEVENT
* Chiefs vs. Red Wings
<2018-08-25 Sat 18:05-21:05>
:PROPERTIES:
:ID:       O_-vlNfqzlPfWAD0QBf0L5U9@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Chiefs vs. Red Wings Chiefs vs. Red Wings

Follow on MiLB First Pitch  https //stza.co/+u_w5-15

Shop  https //stza.co/+u_w5-d

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Chiefs vs. Red Wings
END:VALARM
DTSTART:20180825T230500Z
DTEND:20180826T020500Z
UID:O_-vlNfqzlPfWAD0QBf0L5U9@stanza.co
SUMMARY:Chiefs vs. Red Wings
DESCRIPTION:Chiefs vs. Red Wings\n\nFollow on MiLB First Pitch: https://stza.co/+u_w5-15\n\nShop: https://stza.co/+u_w5-d\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144600Z
LAST-MODIFIED:20180213T144600Z
TRANSP:OPAQUE
END:VEVENT
* Chiefs vs. Red Wings
<2018-08-26 Sun 12:05-15:05>
:PROPERTIES:
:ID:       ClnUsq1AgAiz1kYetYqv1u2d@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Chiefs vs. Red Wings Chiefs vs. Red Wings

Follow on MiLB First Pitch  https //stza.co/+u_w8-3A

Shop  https //stza.co/+u_w8-1f

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Chiefs vs. Red Wings
END:VALARM
DTSTART:20180826T170500Z
DTEND:20180826T200500Z
UID:ClnUsq1AgAiz1kYetYqv1u2d@stanza.co
SUMMARY:Chiefs vs. Red Wings
DESCRIPTION:Chiefs vs. Red Wings\n\nFollow on MiLB First Pitch: https://stza.co/+u_w8-3A\n\nShop: https://stza.co/+u_w8-1f\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144600Z
LAST-MODIFIED:20180213T144600Z
TRANSP:OPAQUE
END:VEVENT
* Chiefs vs. Red Wings
<2018-08-27 Mon 17:35-20:35>
:PROPERTIES:
:ID:       G6WOO1P9dkVvIktR3gmUCpWu@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Chiefs vs. Red Wings Chiefs vs. Red Wings

Follow on MiLB First Pitch  https //stza.co/+u_w9-3o

Shop  https //stza.co/+u_w9-2R

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Chiefs vs. Red Wings
END:VALARM
DTSTART:20180827T223500Z
DTEND:20180828T013500Z
UID:G6WOO1P9dkVvIktR3gmUCpWu@stanza.co
SUMMARY:Chiefs vs. Red Wings
DESCRIPTION:Chiefs vs. Red Wings\n\nFollow on MiLB First Pitch: https://stza.co/+u_w9-3o\n\nShop: https://stza.co/+u_w9-2R\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144600Z
LAST-MODIFIED:20180213T144600Z
TRANSP:OPAQUE
END:VEVENT
* Chiefs @ RailRiders
<2018-08-28 Tue 18:05-21:05>
:PROPERTIES:
:ID:       i_z8QyARhTQH85GZInbPqMEj@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Chiefs @ RailRiders Chiefs @ RailRiders

Follow on MiLB First Pitch  https //stza.co/+vKpi-3x

Shop  https //stza.co/+vKpi-3r

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Chiefs @ RailRiders
END:VALARM
DTSTART:20180828T230500Z
DTEND:20180829T020500Z
UID:i_z8QyARhTQH85GZInbPqMEj@stanza.co
SUMMARY:Chiefs @ RailRiders
DESCRIPTION:Chiefs @ RailRiders\n\nFollow on MiLB First Pitch: https://stza.co/+vKpi-3x\n\nShop: https://stza.co/+vKpi-3r\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144600Z
LAST-MODIFIED:20180213T144600Z
TRANSP:OPAQUE
END:VEVENT
* Chiefs @ RailRiders
<2018-08-29 Wed 18:05-21:05>
:PROPERTIES:
:ID:       TyPc0So4Y6l2nDId7ITZHbcS@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Chiefs @ RailRiders Chiefs @ RailRiders

Follow on MiLB First Pitch  https //stza.co/+vKpj-24

Shop  https //stza.co/+vKpj-3B

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Chiefs @ RailRiders
END:VALARM
DTSTART:20180829T230500Z
DTEND:20180830T020500Z
UID:TyPc0So4Y6l2nDId7ITZHbcS@stanza.co
SUMMARY:Chiefs @ RailRiders
DESCRIPTION:Chiefs @ RailRiders\n\nFollow on MiLB First Pitch: https://stza.co/+vKpj-24\n\nShop: https://stza.co/+vKpj-3B\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144600Z
LAST-MODIFIED:20180213T144600Z
TRANSP:OPAQUE
END:VEVENT
* Chiefs @ RailRiders
<2018-08-30 Thu 18:05-21:05>
:PROPERTIES:
:ID:       ZjESxubnohfNW5nT-9z6R3SA@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Chiefs @ RailRiders Chiefs @ RailRiders

Follow on MiLB First Pitch  https //stza.co/+vKpk-5

Shop  https //stza.co/+vKpk-2y

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Chiefs @ RailRiders
END:VALARM
DTSTART:20180830T230500Z
DTEND:20180831T020500Z
UID:ZjESxubnohfNW5nT-9z6R3SA@stanza.co
SUMMARY:Chiefs @ RailRiders
DESCRIPTION:Chiefs @ RailRiders\n\nFollow on MiLB First Pitch: https://stza.co/+vKpk-5\n\nShop: https://stza.co/+vKpk-2y\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144600Z
LAST-MODIFIED:20180213T144600Z
TRANSP:OPAQUE
END:VEVENT
* Chiefs vs. Bisons
<2018-08-31 Fri 18:05-21:05>
:PROPERTIES:
:ID:       LF0NXHcjPqxCfTNxO_rC-R3B@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Chiefs vs. Bisons Chiefs vs. Bisons

Follow on MiLB First Pitch  https //stza.co/+u_wb-

Shop  https //stza.co/+u_wb-2r

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Chiefs vs. Bisons
END:VALARM
DTSTART:20180831T230500Z
DTEND:20180901T020500Z
UID:LF0NXHcjPqxCfTNxO_rC-R3B@stanza.co
SUMMARY:Chiefs vs. Bisons
DESCRIPTION:Chiefs vs. Bisons\n\nFollow on MiLB First Pitch: https://stza.co/+u_wb-\n\nShop: https://stza.co/+u_wb-2r\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144600Z
LAST-MODIFIED:20180213T144600Z
TRANSP:OPAQUE
END:VEVENT
* Chiefs vs. Bisons
<2018-09-01 Sat 18:05-21:05>
:PROPERTIES:
:ID:       psomv5xS3Bj2s097ybyXCkfU@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Chiefs vs. Bisons Chiefs vs. Bisons

Follow on MiLB First Pitch  https //stza.co/+u_wd-A

Shop  https //stza.co/+u_wd-36

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Chiefs vs. Bisons
END:VALARM
DTSTART:20180901T230500Z
DTEND:20180902T020500Z
UID:psomv5xS3Bj2s097ybyXCkfU@stanza.co
SUMMARY:Chiefs vs. Bisons
DESCRIPTION:Chiefs vs. Bisons\n\nFollow on MiLB First Pitch: https://stza.co/+u_wd-A\n\nShop: https://stza.co/+u_wd-36\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144600Z
LAST-MODIFIED:20180213T144600Z
TRANSP:OPAQUE
END:VEVENT
* Chiefs vs. Bisons
<2018-09-02 Sun 18:05-21:05>
:PROPERTIES:
:ID:       nvLHlTmbfHZVUOKze5XI9tRA@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Chiefs vs. Bisons Chiefs vs. Bisons

Follow on MiLB First Pitch  https //stza.co/+u_wf-Y

Shop  https //stza.co/+u_wf-2k

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Chiefs vs. Bisons
END:VALARM
DTSTART:20180902T230500Z
DTEND:20180903T020500Z
UID:nvLHlTmbfHZVUOKze5XI9tRA@stanza.co
SUMMARY:Chiefs vs. Bisons
DESCRIPTION:Chiefs vs. Bisons\n\nFollow on MiLB First Pitch: https://stza.co/+u_wf-Y\n\nShop: https://stza.co/+u_wf-2k\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144600Z
LAST-MODIFIED:20180213T144600Z
TRANSP:OPAQUE
END:VEVENT
* Chiefs vs. Bisons
<2018-09-03 Mon 12:05-15:05>
:PROPERTIES:
:ID:       XrWbxlX-QlK-ribPDwFUMMPt@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Chiefs vs. Bisons Chiefs vs. Bisons

Follow on MiLB First Pitch  https //stza.co/+u_wh-1C

Shop  https //stza.co/+u_wh-1t

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Chiefs vs. Bisons
END:VALARM
DTSTART:20180903T170500Z
DTEND:20180903T200500Z
UID:XrWbxlX-QlK-ribPDwFUMMPt@stanza.co
SUMMARY:Chiefs vs. Bisons
DESCRIPTION:Chiefs vs. Bisons\n\nFollow on MiLB First Pitch: https://stza.co/+u_wh-1C\n\nShop: https://stza.co/+u_wh-1t\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144600Z
LAST-MODIFIED:20180213T144600Z
TRANSP:OPAQUE
END:VEVENT
