#+TITLE:       Main Google calendar entries
#+AUTHOR:      Eric S Fraga
#+EMAIL:       e.fraga@ucl.ac.uk
#+DESCRIPTION: converted using the ical2org awk script
#+CATEGORY:    google
#+STARTUP:     hidestars
#+STARTUP:     overview

* COMMENT original iCal preamble

* Isotopes @ Bees
<2018-04-05 Thu 19:35-22:35>
:PROPERTIES:
:ID:       HnOhqDiPBdBoy0FGb1Ph6mwi@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Isotopes @ Bees Isotopes @ Bees

Follow on MiLB First Pitch  https //stza.co/+wmvp-3M

Shop  https //stza.co/+wmvp-d

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Isotopes @ Bees
END:VALARM
DTSTART:20180406T003500Z
DTEND:20180406T033500Z
UID:HnOhqDiPBdBoy0FGb1Ph6mwi@stanza.co
SUMMARY:Isotopes @ Bees
DESCRIPTION:Isotopes @ Bees\n\nFollow on MiLB First Pitch: https://stza.co/+wmvp-3M\n\nShop: https://stza.co/+wmvp-d\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144500Z
LAST-MODIFIED:20180213T144500Z
TRANSP:OPAQUE
END:VEVENT
* Isotopes @ Bees
<2018-04-06 Fri 19:35-22:35>
:PROPERTIES:
:ID:       S5XxbM7_JnYBjVFc9c5wM8iE@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Isotopes @ Bees Isotopes @ Bees

Follow on MiLB First Pitch  https //stza.co/+wmvs-3e

Shop  https //stza.co/+wmvs-1y

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Isotopes @ Bees
END:VALARM
DTSTART:20180407T003500Z
DTEND:20180407T033500Z
UID:S5XxbM7_JnYBjVFc9c5wM8iE@stanza.co
SUMMARY:Isotopes @ Bees
DESCRIPTION:Isotopes @ Bees\n\nFollow on MiLB First Pitch: https://stza.co/+wmvs-3e\n\nShop: https://stza.co/+wmvs-1y\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144500Z
LAST-MODIFIED:20180213T144500Z
TRANSP:OPAQUE
END:VEVENT
* Isotopes @ Bees
<2018-04-07 Sat 19:35-22:35>
:PROPERTIES:
:ID:       FFTbi1AQeZR-YUa4iBM8WotS@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Isotopes @ Bees Isotopes @ Bees

Follow on MiLB First Pitch  https //stza.co/+wmvt-2z

Shop  https //stza.co/+wmvt-1u

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Isotopes @ Bees
END:VALARM
DTSTART:20180408T003500Z
DTEND:20180408T033500Z
UID:FFTbi1AQeZR-YUa4iBM8WotS@stanza.co
SUMMARY:Isotopes @ Bees
DESCRIPTION:Isotopes @ Bees\n\nFollow on MiLB First Pitch: https://stza.co/+wmvt-2z\n\nShop: https://stza.co/+wmvt-1u\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144500Z
LAST-MODIFIED:20180213T144500Z
TRANSP:OPAQUE
END:VEVENT
* Isotopes @ Bees
<2018-04-08 Sun 14:05-17:05>
:PROPERTIES:
:ID:       0WAoF2MxyITh4FKJJ56ajQ2v@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Isotopes @ Bees Isotopes @ Bees

Follow on MiLB First Pitch  https //stza.co/+wmvu-2h

Shop  https //stza.co/+wmvu-2i

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Isotopes @ Bees
END:VALARM
DTSTART:20180408T190500Z
DTEND:20180408T220500Z
UID:0WAoF2MxyITh4FKJJ56ajQ2v@stanza.co
SUMMARY:Isotopes @ Bees
DESCRIPTION:Isotopes @ Bees\n\nFollow on MiLB First Pitch: https://stza.co/+wmvu-2h\n\nShop: https://stza.co/+wmvu-2i\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144500Z
LAST-MODIFIED:20180213T144500Z
TRANSP:OPAQUE
END:VEVENT
* Isotopes @ Bees
<2018-04-09 Mon 13:05-16:05>
:PROPERTIES:
:ID:       zCIbRD317o7KyiaT8qHNc_od@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Isotopes @ Bees Isotopes @ Bees

Follow on MiLB First Pitch  https //stza.co/+wmvv-S

Shop  https //stza.co/+wmvv-1C

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Isotopes @ Bees
END:VALARM
DTSTART:20180409T180500Z
DTEND:20180409T210500Z
UID:zCIbRD317o7KyiaT8qHNc_od@stanza.co
SUMMARY:Isotopes @ Bees
DESCRIPTION:Isotopes @ Bees\n\nFollow on MiLB First Pitch: https://stza.co/+wmvv-S\n\nShop: https://stza.co/+wmvv-1C\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144500Z
LAST-MODIFIED:20180213T144500Z
TRANSP:OPAQUE
END:VEVENT
* Isotopes vs. 51s
<2018-04-10 Tue 19:35-22:35>
:PROPERTIES:
:ID:       HBUvO9k90ICgsv9jo-QzkLMj@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Isotopes vs. 51s Isotopes vs. 51s

Follow on MiLB First Pitch  https //stza.co/+whzA-12

Shop  https //stza.co/+whzA-2X

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Isotopes vs. 51s
END:VALARM
DTSTART:20180411T003500Z
DTEND:20180411T033500Z
UID:HBUvO9k90ICgsv9jo-QzkLMj@stanza.co
SUMMARY:Isotopes vs. 51s
DESCRIPTION:Isotopes vs. 51s\n\nFollow on MiLB First Pitch: https://stza.co/+whzA-12\n\nShop: https://stza.co/+whzA-2X\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144500Z
LAST-MODIFIED:20180213T144500Z
TRANSP:OPAQUE
END:VEVENT
* Isotopes vs. 51s
<2018-04-11 Wed 19:35-22:35>
:PROPERTIES:
:ID:       U5ZgDYnPYdxhn7EgUoOV0fpG@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Isotopes vs. 51s Isotopes vs. 51s

Follow on MiLB First Pitch  https //stza.co/+whzF-Y

Shop  https //stza.co/+whzF-1R

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Isotopes vs. 51s
END:VALARM
DTSTART:20180412T003500Z
DTEND:20180412T033500Z
UID:U5ZgDYnPYdxhn7EgUoOV0fpG@stanza.co
SUMMARY:Isotopes vs. 51s
DESCRIPTION:Isotopes vs. 51s\n\nFollow on MiLB First Pitch: https://stza.co/+whzF-Y\n\nShop: https://stza.co/+whzF-1R\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144500Z
LAST-MODIFIED:20180213T144500Z
TRANSP:OPAQUE
END:VEVENT
* Isotopes vs. 51s
<2018-04-12 Thu 13:05-16:05>
:PROPERTIES:
:ID:       j59L_fWERnc9zxQyC7R_vrBe@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Isotopes vs. 51s Isotopes vs. 51s

Follow on MiLB First Pitch  https //stza.co/+whzI-3x

Shop  https //stza.co/+whzI-2O

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Isotopes vs. 51s
END:VALARM
DTSTART:20180412T180500Z
DTEND:20180412T210500Z
UID:j59L_fWERnc9zxQyC7R_vrBe@stanza.co
SUMMARY:Isotopes vs. 51s
DESCRIPTION:Isotopes vs. 51s\n\nFollow on MiLB First Pitch: https://stza.co/+whzI-3x\n\nShop: https://stza.co/+whzI-2O\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144500Z
LAST-MODIFIED:20180213T144500Z
TRANSP:OPAQUE
END:VEVENT
* Isotopes vs. Bees
<2018-04-13 Fri 19:35-22:35>
:PROPERTIES:
:ID:       rD2T_GfNWE4zqOf81wsgxZ6C@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Isotopes vs. Bees Isotopes vs. Bees

Follow on MiLB First Pitch  https //stza.co/+whzJ-2C

Shop  https //stza.co/+whzJ-q

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Isotopes vs. Bees
END:VALARM
DTSTART:20180414T003500Z
DTEND:20180414T033500Z
UID:rD2T_GfNWE4zqOf81wsgxZ6C@stanza.co
SUMMARY:Isotopes vs. Bees
DESCRIPTION:Isotopes vs. Bees\n\nFollow on MiLB First Pitch: https://stza.co/+whzJ-2C\n\nShop: https://stza.co/+whzJ-q\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144500Z
LAST-MODIFIED:20180213T144500Z
TRANSP:OPAQUE
END:VEVENT
* Isotopes vs. Bees
<2018-04-14 Sat 19:35-22:35>
:PROPERTIES:
:ID:       ZXVYlGaP1d71GGiere9xWmE1@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Isotopes vs. Bees Isotopes vs. Bees

Follow on MiLB First Pitch  https //stza.co/+whzM-1O

Shop  https //stza.co/+whzM-17

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Isotopes vs. Bees
END:VALARM
DTSTART:20180415T003500Z
DTEND:20180415T033500Z
UID:ZXVYlGaP1d71GGiere9xWmE1@stanza.co
SUMMARY:Isotopes vs. Bees
DESCRIPTION:Isotopes vs. Bees\n\nFollow on MiLB First Pitch: https://stza.co/+whzM-1O\n\nShop: https://stza.co/+whzM-17\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144500Z
LAST-MODIFIED:20180213T144500Z
TRANSP:OPAQUE
END:VEVENT
* Isotopes vs. Bees
<2018-04-15 Sun 14:35-17:35>
:PROPERTIES:
:ID:       6uUss17fqFd50RzzR7YG5ENw@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Isotopes vs. Bees Isotopes vs. Bees

Follow on MiLB First Pitch  https //stza.co/+whzN-2H

Shop  https //stza.co/+whzN-2P

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Isotopes vs. Bees
END:VALARM
DTSTART:20180415T193500Z
DTEND:20180415T223500Z
UID:6uUss17fqFd50RzzR7YG5ENw@stanza.co
SUMMARY:Isotopes vs. Bees
DESCRIPTION:Isotopes vs. Bees\n\nFollow on MiLB First Pitch: https://stza.co/+whzN-2H\n\nShop: https://stza.co/+whzN-2P\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144500Z
LAST-MODIFIED:20180213T144500Z
TRANSP:OPAQUE
END:VEVENT
* Isotopes vs. Bees
<2018-04-16 Mon 12:05-15:05>
:PROPERTIES:
:ID:       cx6vf1u5O-kEu8Yl071HASiQ@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Isotopes vs. Bees Isotopes vs. Bees

Follow on MiLB First Pitch  https //stza.co/+whzQ-36

Shop  https //stza.co/+whzQ-1i

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Isotopes vs. Bees
END:VALARM
DTSTART:20180416T170500Z
DTEND:20180416T200500Z
UID:cx6vf1u5O-kEu8Yl071HASiQ@stanza.co
SUMMARY:Isotopes vs. Bees
DESCRIPTION:Isotopes vs. Bees\n\nFollow on MiLB First Pitch: https://stza.co/+whzQ-36\n\nShop: https://stza.co/+whzQ-1i\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144500Z
LAST-MODIFIED:20180213T144500Z
TRANSP:OPAQUE
END:VEVENT
* Isotopes @ Rainiers
<2018-04-17 Tue 20:05-23:05>
:PROPERTIES:
:ID:       Hp0IC2nzPOaBOPyvzSxLEZ9D@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Isotopes @ Rainiers Isotopes @ Rainiers

Follow on MiLB First Pitch  https //stza.co/+wjww-M

Shop  https //stza.co/+wjww-3w

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Isotopes @ Rainiers
END:VALARM
DTSTART:20180418T010500Z
DTEND:20180418T040500Z
UID:Hp0IC2nzPOaBOPyvzSxLEZ9D@stanza.co
SUMMARY:Isotopes @ Rainiers
DESCRIPTION:Isotopes @ Rainiers\n\nFollow on MiLB First Pitch: https://stza.co/+wjww-M\n\nShop: https://stza.co/+wjww-3w\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144500Z
LAST-MODIFIED:20180213T144500Z
TRANSP:OPAQUE
END:VEVENT
* Isotopes @ Rainiers
<2018-04-18 Wed 21:05>--<2018-04-19 Thu 00:05>
:PROPERTIES:
:ID:       hs8h5cxDeQi8b-AO5v3kHtSO@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Isotopes @ Rainiers Isotopes @ Rainiers

Follow on MiLB First Pitch  https //stza.co/+wjwx-1P

Shop  https //stza.co/+wjwx-I

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Isotopes @ Rainiers
END:VALARM
DTSTART:20180419T020500Z
DTEND:20180419T050500Z
UID:hs8h5cxDeQi8b-AO5v3kHtSO@stanza.co
SUMMARY:Isotopes @ Rainiers
DESCRIPTION:Isotopes @ Rainiers\n\nFollow on MiLB First Pitch: https://stza.co/+wjwx-1P\n\nShop: https://stza.co/+wjwx-I\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144500Z
LAST-MODIFIED:20180213T144500Z
TRANSP:OPAQUE
END:VEVENT
* Isotopes @ Rainiers
<2018-04-19 Thu 21:05>--<2018-04-20 Fri 00:05>
:PROPERTIES:
:ID:       CcmUjv67_TEgpHJ8cbqcpEFg@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Isotopes @ Rainiers Isotopes @ Rainiers

Follow on MiLB First Pitch  https //stza.co/+wjwy-3I

Shop  https //stza.co/+wjwy-1u

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Isotopes @ Rainiers
END:VALARM
DTSTART:20180420T020500Z
DTEND:20180420T050500Z
UID:CcmUjv67_TEgpHJ8cbqcpEFg@stanza.co
SUMMARY:Isotopes @ Rainiers
DESCRIPTION:Isotopes @ Rainiers\n\nFollow on MiLB First Pitch: https://stza.co/+wjwy-3I\n\nShop: https://stza.co/+wjwy-1u\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144500Z
LAST-MODIFIED:20180213T144500Z
TRANSP:OPAQUE
END:VEVENT
* Isotopes @ Rainiers
<2018-04-20 Fri 21:05>--<2018-04-21 Sat 00:05>
:PROPERTIES:
:ID:       4dhiB2BjRDqwngwWI_TPHtFe@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Isotopes @ Rainiers Isotopes @ Rainiers

Follow on MiLB First Pitch  https //stza.co/+wjwz-2C

Shop  https //stza.co/+wjwz-5

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Isotopes @ Rainiers
END:VALARM
DTSTART:20180421T020500Z
DTEND:20180421T050500Z
UID:4dhiB2BjRDqwngwWI_TPHtFe@stanza.co
SUMMARY:Isotopes @ Rainiers
DESCRIPTION:Isotopes @ Rainiers\n\nFollow on MiLB First Pitch: https://stza.co/+wjwz-2C\n\nShop: https://stza.co/+wjwz-5\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144500Z
LAST-MODIFIED:20180213T144500Z
TRANSP:OPAQUE
END:VEVENT
* Isotopes @ Bees
<2018-04-21 Sat 19:35-22:35>
:PROPERTIES:
:ID:       EK9wQgALa4sUUS91hDLwWzAf@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Isotopes @ Bees Isotopes @ Bees

Follow on MiLB First Pitch  https //stza.co/+wmvw-1W

Shop  https //stza.co/+wmvw-1

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Isotopes @ Bees
END:VALARM
DTSTART:20180422T003500Z
DTEND:20180422T033500Z
UID:EK9wQgALa4sUUS91hDLwWzAf@stanza.co
SUMMARY:Isotopes @ Bees
DESCRIPTION:Isotopes @ Bees\n\nFollow on MiLB First Pitch: https://stza.co/+wmvw-1W\n\nShop: https://stza.co/+wmvw-1\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144500Z
LAST-MODIFIED:20180213T144500Z
TRANSP:OPAQUE
END:VEVENT
* Isotopes @ Bees
<2018-04-22 Sun 14:05-17:05>
:PROPERTIES:
:ID:       XO0BaTWNMJ4qBP3nyb5z0EmM@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Isotopes @ Bees Isotopes @ Bees

Follow on MiLB First Pitch  https //stza.co/+wmvx-1D

Shop  https //stza.co/+wmvx-2i

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Isotopes @ Bees
END:VALARM
DTSTART:20180422T190500Z
DTEND:20180422T220500Z
UID:XO0BaTWNMJ4qBP3nyb5z0EmM@stanza.co
SUMMARY:Isotopes @ Bees
DESCRIPTION:Isotopes @ Bees\n\nFollow on MiLB First Pitch: https://stza.co/+wmvx-1D\n\nShop: https://stza.co/+wmvx-2i\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144500Z
LAST-MODIFIED:20180213T144500Z
TRANSP:OPAQUE
END:VEVENT
* Isotopes @ Bees
<2018-04-23 Mon 19:35-22:35>
:PROPERTIES:
:ID:       qbv5pfDS3gvjptPg-JP3VBok@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Isotopes @ Bees Isotopes @ Bees

Follow on MiLB First Pitch  https //stza.co/+wmvy-1h

Shop  https //stza.co/+wmvy-3G

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Isotopes @ Bees
END:VALARM
DTSTART:20180424T003500Z
DTEND:20180424T033500Z
UID:qbv5pfDS3gvjptPg-JP3VBok@stanza.co
SUMMARY:Isotopes @ Bees
DESCRIPTION:Isotopes @ Bees\n\nFollow on MiLB First Pitch: https://stza.co/+wmvy-1h\n\nShop: https://stza.co/+wmvy-3G\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144500Z
LAST-MODIFIED:20180213T144500Z
TRANSP:OPAQUE
END:VEVENT
* Isotopes vs. 51s
<2018-04-25 Wed 19:35-22:35>
:PROPERTIES:
:ID:       OK10TDn2lJYsiresTnlAxdtX@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Isotopes vs. 51s Isotopes vs. 51s

Follow on MiLB First Pitch  https //stza.co/+whzT-U

Shop  https //stza.co/+whzT-3X

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Isotopes vs. 51s
END:VALARM
DTSTART:20180426T003500Z
DTEND:20180426T033500Z
UID:OK10TDn2lJYsiresTnlAxdtX@stanza.co
SUMMARY:Isotopes vs. 51s
DESCRIPTION:Isotopes vs. 51s\n\nFollow on MiLB First Pitch: https://stza.co/+whzT-U\n\nShop: https://stza.co/+whzT-3X\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144500Z
LAST-MODIFIED:20180213T144500Z
TRANSP:OPAQUE
END:VEVENT
* Isotopes vs. 51s
<2018-04-26 Thu 19:35-22:35>
:PROPERTIES:
:ID:       pwhEBs91mBT6X8NFGLOvj3Gr@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Isotopes vs. 51s Isotopes vs. 51s

Follow on MiLB First Pitch  https //stza.co/+whzV-3H

Shop  https //stza.co/+whzV-2I

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Isotopes vs. 51s
END:VALARM
DTSTART:20180427T003500Z
DTEND:20180427T033500Z
UID:pwhEBs91mBT6X8NFGLOvj3Gr@stanza.co
SUMMARY:Isotopes vs. 51s
DESCRIPTION:Isotopes vs. 51s\n\nFollow on MiLB First Pitch: https://stza.co/+whzV-3H\n\nShop: https://stza.co/+whzV-2I\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144500Z
LAST-MODIFIED:20180213T144500Z
TRANSP:OPAQUE
END:VEVENT
* Isotopes vs. 51s
<2018-04-27 Fri 19:35-22:35>
:PROPERTIES:
:ID:       wOTE3xKrzWOadS7LqK_kwjg2@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Isotopes vs. 51s Isotopes vs. 51s

Follow on MiLB First Pitch  https //stza.co/+whzX-2Y

Shop  https //stza.co/+whzX-1Q

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Isotopes vs. 51s
END:VALARM
DTSTART:20180428T003500Z
DTEND:20180428T033500Z
UID:wOTE3xKrzWOadS7LqK_kwjg2@stanza.co
SUMMARY:Isotopes vs. 51s
DESCRIPTION:Isotopes vs. 51s\n\nFollow on MiLB First Pitch: https://stza.co/+whzX-2Y\n\nShop: https://stza.co/+whzX-1Q\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144500Z
LAST-MODIFIED:20180213T144500Z
TRANSP:OPAQUE
END:VEVENT
* Isotopes vs. 51s
<2018-04-28 Sat 19:35-22:35>
:PROPERTIES:
:ID:       v4jQOqlEWnJLGr6xXrWE84HZ@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Isotopes vs. 51s Isotopes vs. 51s

Follow on MiLB First Pitch  https //stza.co/+whzY-7

Shop  https //stza.co/+whzY-L

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Isotopes vs. 51s
END:VALARM
DTSTART:20180429T003500Z
DTEND:20180429T033500Z
UID:v4jQOqlEWnJLGr6xXrWE84HZ@stanza.co
SUMMARY:Isotopes vs. 51s
DESCRIPTION:Isotopes vs. 51s\n\nFollow on MiLB First Pitch: https://stza.co/+whzY-7\n\nShop: https://stza.co/+whzY-L\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144500Z
LAST-MODIFIED:20180213T144500Z
TRANSP:OPAQUE
END:VEVENT
* Isotopes vs. 51s
<2018-04-29 Sun 14:35-17:35>
:PROPERTIES:
:ID:       VDlMaVkkYdxnZIQLGzTsOqRl@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Isotopes vs. 51s Isotopes vs. 51s

Follow on MiLB First Pitch  https //stza.co/+whz$-32

Shop  https //stza.co/+whz$-2c

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Isotopes vs. 51s
END:VALARM
DTSTART:20180429T193500Z
DTEND:20180429T223500Z
UID:VDlMaVkkYdxnZIQLGzTsOqRl@stanza.co
SUMMARY:Isotopes vs. 51s
DESCRIPTION:Isotopes vs. 51s\n\nFollow on MiLB First Pitch: https://stza.co/+whz$-32\n\nShop: https://stza.co/+whz$-2c\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144500Z
LAST-MODIFIED:20180213T144500Z
TRANSP:OPAQUE
END:VEVENT
* Isotopes @ Rainiers
<2018-04-30 Mon 20:05-23:05>
:PROPERTIES:
:ID:       osysqaXWmFHdWHUiy4TlEl7M@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Isotopes @ Rainiers Isotopes @ Rainiers

Follow on MiLB First Pitch  https //stza.co/+wjwA-3x

Shop  https //stza.co/+wjwA-25

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Isotopes @ Rainiers
END:VALARM
DTSTART:20180501T010500Z
DTEND:20180501T040500Z
UID:osysqaXWmFHdWHUiy4TlEl7M@stanza.co
SUMMARY:Isotopes @ Rainiers
DESCRIPTION:Isotopes @ Rainiers\n\nFollow on MiLB First Pitch: https://stza.co/+wjwA-3x\n\nShop: https://stza.co/+wjwA-25\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144500Z
LAST-MODIFIED:20180213T144500Z
TRANSP:OPAQUE
END:VEVENT
* Isotopes @ Rainiers
<2018-05-01 Tue 20:05-23:05>
:PROPERTIES:
:ID:       KjZ1rLZGQVnVhwXZE8DMEvzY@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Isotopes @ Rainiers Isotopes @ Rainiers

Follow on MiLB First Pitch  https //stza.co/+wjwB-s

Shop  https //stza.co/+wjwB-3r

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Isotopes @ Rainiers
END:VALARM
DTSTART:20180502T010500Z
DTEND:20180502T040500Z
UID:KjZ1rLZGQVnVhwXZE8DMEvzY@stanza.co
SUMMARY:Isotopes @ Rainiers
DESCRIPTION:Isotopes @ Rainiers\n\nFollow on MiLB First Pitch: https://stza.co/+wjwB-s\n\nShop: https://stza.co/+wjwB-3r\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144500Z
LAST-MODIFIED:20180213T144500Z
TRANSP:OPAQUE
END:VEVENT
* Isotopes @ Rainiers
<2018-05-02 Wed 21:05>--<2018-05-03 Thu 00:05>
:PROPERTIES:
:ID:       7kexFC8V9RbpoH5FYWQslMI6@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Isotopes @ Rainiers Isotopes @ Rainiers

Follow on MiLB First Pitch  https //stza.co/+wjwC-4

Shop  https //stza.co/+wjwC-2l

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Isotopes @ Rainiers
END:VALARM
DTSTART:20180503T020500Z
DTEND:20180503T050500Z
UID:7kexFC8V9RbpoH5FYWQslMI6@stanza.co
SUMMARY:Isotopes @ Rainiers
DESCRIPTION:Isotopes @ Rainiers\n\nFollow on MiLB First Pitch: https://stza.co/+wjwC-4\n\nShop: https://stza.co/+wjwC-2l\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144500Z
LAST-MODIFIED:20180213T144500Z
TRANSP:OPAQUE
END:VEVENT
* Isotopes @ Rainiers
<2018-05-03 Thu 21:05>--<2018-05-04 Fri 00:05>
:PROPERTIES:
:ID:       w2GL4Mnua5irum7t1Oprd0TS@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Isotopes @ Rainiers Isotopes @ Rainiers

Follow on MiLB First Pitch  https //stza.co/+wjwD-V

Shop  https //stza.co/+wjwD-6

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Isotopes @ Rainiers
END:VALARM
DTSTART:20180504T020500Z
DTEND:20180504T050500Z
UID:w2GL4Mnua5irum7t1Oprd0TS@stanza.co
SUMMARY:Isotopes @ Rainiers
DESCRIPTION:Isotopes @ Rainiers\n\nFollow on MiLB First Pitch: https://stza.co/+wjwD-V\n\nShop: https://stza.co/+wjwD-6\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144500Z
LAST-MODIFIED:20180213T144500Z
TRANSP:OPAQUE
END:VEVENT
* Isotopes vs. Chihuahuas
<2018-05-04 Fri 19:35-22:35>
:PROPERTIES:
:ID:       qbcJDN3BEZOULmr6A2JWwyD4@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Isotopes vs. Chihuahuas Isotopes vs. Chihuahuas

Follow on MiLB First Pitch  https //stza.co/+whA0-3D

Shop  https //stza.co/+whA0-3d

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Isotopes vs. Chihuahuas
END:VALARM
DTSTART:20180505T003500Z
DTEND:20180505T033500Z
UID:qbcJDN3BEZOULmr6A2JWwyD4@stanza.co
SUMMARY:Isotopes vs. Chihuahuas
DESCRIPTION:Isotopes vs. Chihuahuas\n\nFollow on MiLB First Pitch: https://stza.co/+whA0-3D\n\nShop: https://stza.co/+whA0-3d\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144500Z
LAST-MODIFIED:20180213T144500Z
TRANSP:OPAQUE
END:VEVENT
* Isotopes vs. Chihuahuas
<2018-05-05 Sat 19:35-22:35>
:PROPERTIES:
:ID:       YjMa8GZuXCQXDR4jxFthUXTm@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Isotopes vs. Chihuahuas Isotopes vs. Chihuahuas

Follow on MiLB First Pitch  https //stza.co/+whA3-2r

Shop  https //stza.co/+whA3-2O

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Isotopes vs. Chihuahuas
END:VALARM
DTSTART:20180506T003500Z
DTEND:20180506T033500Z
UID:YjMa8GZuXCQXDR4jxFthUXTm@stanza.co
SUMMARY:Isotopes vs. Chihuahuas
DESCRIPTION:Isotopes vs. Chihuahuas\n\nFollow on MiLB First Pitch: https://stza.co/+whA3-2r\n\nShop: https://stza.co/+whA3-2O\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144500Z
LAST-MODIFIED:20180213T144500Z
TRANSP:OPAQUE
END:VEVENT
* Isotopes vs. Chihuahuas
<2018-05-06 Sun 14:35-17:35>
:PROPERTIES:
:ID:       TzkhTXn1UPfXLieE9Ll7K2ZT@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Isotopes vs. Chihuahuas Isotopes vs. Chihuahuas

Follow on MiLB First Pitch  https //stza.co/+whA4-3j

Shop  https //stza.co/+whA4-3W

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Isotopes vs. Chihuahuas
END:VALARM
DTSTART:20180506T193500Z
DTEND:20180506T223500Z
UID:TzkhTXn1UPfXLieE9Ll7K2ZT@stanza.co
SUMMARY:Isotopes vs. Chihuahuas
DESCRIPTION:Isotopes vs. Chihuahuas\n\nFollow on MiLB First Pitch: https://stza.co/+whA4-3j\n\nShop: https://stza.co/+whA4-3W\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144500Z
LAST-MODIFIED:20180213T144500Z
TRANSP:OPAQUE
END:VEVENT
* Isotopes vs. Chihuahuas
<2018-05-07 Mon 12:05-15:05>
:PROPERTIES:
:ID:       B-Y-uyx6wKt5T_l1I7QcgWJY@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Isotopes vs. Chihuahuas Isotopes vs. Chihuahuas

Follow on MiLB First Pitch  https //stza.co/+whA6-3a

Shop  https //stza.co/+whA6-G

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Isotopes vs. Chihuahuas
END:VALARM
DTSTART:20180507T170500Z
DTEND:20180507T200500Z
UID:B-Y-uyx6wKt5T_l1I7QcgWJY@stanza.co
SUMMARY:Isotopes vs. Chihuahuas
DESCRIPTION:Isotopes vs. Chihuahuas\n\nFollow on MiLB First Pitch: https://stza.co/+whA6-3a\n\nShop: https://stza.co/+whA6-G\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144500Z
LAST-MODIFIED:20180213T144500Z
TRANSP:OPAQUE
END:VEVENT
* Isotopes @ Aces
<2018-05-08 Tue 20:35-23:35>
:PROPERTIES:
:ID:       YTtKfco59FMkS-M-k_Su-O6i@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Isotopes @ Aces Isotopes @ Aces

Follow on MiLB First Pitch  https //stza.co/+wjwg-3X

Shop  https //stza.co/+wjwg-d

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Isotopes @ Aces
END:VALARM
DTSTART:20180509T013500Z
DTEND:20180509T043500Z
UID:YTtKfco59FMkS-M-k_Su-O6i@stanza.co
SUMMARY:Isotopes @ Aces
DESCRIPTION:Isotopes @ Aces\n\nFollow on MiLB First Pitch: https://stza.co/+wjwg-3X\n\nShop: https://stza.co/+wjwg-d\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144500Z
LAST-MODIFIED:20180213T144500Z
TRANSP:OPAQUE
END:VEVENT
* Isotopes @ Aces
<2018-05-09 Wed 20:35-23:35>
:PROPERTIES:
:ID:       jMpH07SyYnajjEdjaErs7fRI@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Isotopes @ Aces Isotopes @ Aces

Follow on MiLB First Pitch  https //stza.co/+wjwh-31

Shop  https //stza.co/+wjwh-1b

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Isotopes @ Aces
END:VALARM
DTSTART:20180510T013500Z
DTEND:20180510T043500Z
UID:jMpH07SyYnajjEdjaErs7fRI@stanza.co
SUMMARY:Isotopes @ Aces
DESCRIPTION:Isotopes @ Aces\n\nFollow on MiLB First Pitch: https://stza.co/+wjwh-31\n\nShop: https://stza.co/+wjwh-1b\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144500Z
LAST-MODIFIED:20180213T144500Z
TRANSP:OPAQUE
END:VEVENT
* Isotopes @ Aces
<2018-05-10 Thu 20:35-23:35>
:PROPERTIES:
:ID:       r7gHxcWZp9wDky7xHXr37OZe@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Isotopes @ Aces Isotopes @ Aces

Follow on MiLB First Pitch  https //stza.co/+wjwi-_

Shop  https //stza.co/+wjwi-2d

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Isotopes @ Aces
END:VALARM
DTSTART:20180511T013500Z
DTEND:20180511T043500Z
UID:r7gHxcWZp9wDky7xHXr37OZe@stanza.co
SUMMARY:Isotopes @ Aces
DESCRIPTION:Isotopes @ Aces\n\nFollow on MiLB First Pitch: https://stza.co/+wjwi-_\n\nShop: https://stza.co/+wjwi-2d\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144500Z
LAST-MODIFIED:20180213T144500Z
TRANSP:OPAQUE
END:VEVENT
* Isotopes @ Aces
<2018-05-11 Fri 20:35-23:35>
:PROPERTIES:
:ID:       9nqp4CfJI7XGFNHwFuCg1Tbw@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Isotopes @ Aces Isotopes @ Aces

Follow on MiLB First Pitch  https //stza.co/+wjwj-d

Shop  https //stza.co/+wjwj-1P

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Isotopes @ Aces
END:VALARM
DTSTART:20180512T013500Z
DTEND:20180512T043500Z
UID:9nqp4CfJI7XGFNHwFuCg1Tbw@stanza.co
SUMMARY:Isotopes @ Aces
DESCRIPTION:Isotopes @ Aces\n\nFollow on MiLB First Pitch: https://stza.co/+wjwj-d\n\nShop: https://stza.co/+wjwj-1P\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144500Z
LAST-MODIFIED:20180213T144500Z
TRANSP:OPAQUE
END:VEVENT
* Isotopes @ 51s
<2018-05-12 Sat 21:05>--<2018-05-13 Sun 00:05>
:PROPERTIES:
:ID:       Bcm7qc05v8GMokrM3e8P4zTo@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Isotopes @ 51s Isotopes @ 51s

Follow on MiLB First Pitch  https //stza.co/+vKsz-35

Shop  https //stza.co/+vKsz-S

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Isotopes @ 51s
END:VALARM
DTSTART:20180513T020500Z
DTEND:20180513T050500Z
UID:Bcm7qc05v8GMokrM3e8P4zTo@stanza.co
SUMMARY:Isotopes @ 51s
DESCRIPTION:Isotopes @ 51s\n\nFollow on MiLB First Pitch: https://stza.co/+vKsz-35\n\nShop: https://stza.co/+vKsz-S\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144500Z
LAST-MODIFIED:20180213T144500Z
TRANSP:OPAQUE
END:VEVENT
* Isotopes @ 51s
<2018-05-13 Sun 14:05-17:05>
:PROPERTIES:
:ID:       aMAdD_xk0lky6EROPX-tV39R@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Isotopes @ 51s Isotopes @ 51s

Follow on MiLB First Pitch  https //stza.co/+u$2k-3

Shop  https //stza.co/+u$2k-f

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Isotopes @ 51s
END:VALARM
DTSTART:20180513T190500Z
DTEND:20180513T220500Z
UID:aMAdD_xk0lky6EROPX-tV39R@stanza.co
SUMMARY:Isotopes @ 51s
DESCRIPTION:Isotopes @ 51s\n\nFollow on MiLB First Pitch: https://stza.co/+u$2k-3\n\nShop: https://stza.co/+u$2k-f\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144500Z
LAST-MODIFIED:20180213T144500Z
TRANSP:OPAQUE
END:VEVENT
* Isotopes @ 51s
<2018-05-14 Mon 21:05>--<2018-05-15 Tue 00:05>
:PROPERTIES:
:ID:       wNuRCSB7FpcGNh7bxzZ7qva4@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Isotopes @ 51s Isotopes @ 51s

Follow on MiLB First Pitch  https //stza.co/+u$2l-1D

Shop  https //stza.co/+u$2l-p

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Isotopes @ 51s
END:VALARM
DTSTART:20180515T020500Z
DTEND:20180515T050500Z
UID:wNuRCSB7FpcGNh7bxzZ7qva4@stanza.co
SUMMARY:Isotopes @ 51s
DESCRIPTION:Isotopes @ 51s\n\nFollow on MiLB First Pitch: https://stza.co/+u$2l-1D\n\nShop: https://stza.co/+u$2l-p\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144500Z
LAST-MODIFIED:20180213T144500Z
TRANSP:OPAQUE
END:VEVENT
* Isotopes @ 51s
<2018-05-15 Tue 21:05>--<2018-05-16 Wed 00:05>
:PROPERTIES:
:ID:       REQ0eh5yIHpUf60KBjfU0jWY@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Isotopes @ 51s Isotopes @ 51s

Follow on MiLB First Pitch  https //stza.co/+u$2m-1K

Shop  https //stza.co/+u$2m-P

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Isotopes @ 51s
END:VALARM
DTSTART:20180516T020500Z
DTEND:20180516T050500Z
UID:REQ0eh5yIHpUf60KBjfU0jWY@stanza.co
SUMMARY:Isotopes @ 51s
DESCRIPTION:Isotopes @ 51s\n\nFollow on MiLB First Pitch: https://stza.co/+u$2m-1K\n\nShop: https://stza.co/+u$2m-P\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144500Z
LAST-MODIFIED:20180213T144500Z
TRANSP:OPAQUE
END:VEVENT
* Isotopes vs. Aces
<2018-05-17 Thu 19:35-22:35>
:PROPERTIES:
:ID:       KHeX80ate46cWOgB-hX6Vw56@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Isotopes vs. Aces Isotopes vs. Aces

Follow on MiLB First Pitch  https //stza.co/+whA9-26

Shop  https //stza.co/+whA9-3G

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Isotopes vs. Aces
END:VALARM
DTSTART:20180518T003500Z
DTEND:20180518T033500Z
UID:KHeX80ate46cWOgB-hX6Vw56@stanza.co
SUMMARY:Isotopes vs. Aces
DESCRIPTION:Isotopes vs. Aces\n\nFollow on MiLB First Pitch: https://stza.co/+whA9-26\n\nShop: https://stza.co/+whA9-3G\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144500Z
LAST-MODIFIED:20180213T144500Z
TRANSP:OPAQUE
END:VEVENT
* Isotopes vs. Aces
<2018-05-18 Fri 19:35-22:35>
:PROPERTIES:
:ID:       KXjLpbtoQmqzDF2JG9k6Ksfk@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Isotopes vs. Aces Isotopes vs. Aces

Follow on MiLB First Pitch  https //stza.co/+whAa-C

Shop  https //stza.co/+whAa-M

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Isotopes vs. Aces
END:VALARM
DTSTART:20180519T003500Z
DTEND:20180519T033500Z
UID:KXjLpbtoQmqzDF2JG9k6Ksfk@stanza.co
SUMMARY:Isotopes vs. Aces
DESCRIPTION:Isotopes vs. Aces\n\nFollow on MiLB First Pitch: https://stza.co/+whAa-C\n\nShop: https://stza.co/+whAa-M\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144500Z
LAST-MODIFIED:20180213T144500Z
TRANSP:OPAQUE
END:VEVENT
* Isotopes vs. Aces
<2018-05-19 Sat 19:35-22:35>
:PROPERTIES:
:ID:       yMbPPwamu_RqzSfzQsoxqebS@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Isotopes vs. Aces Isotopes vs. Aces

Follow on MiLB First Pitch  https //stza.co/+whAd-o

Shop  https //stza.co/+whAd-3

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Isotopes vs. Aces
END:VALARM
DTSTART:20180520T003500Z
DTEND:20180520T033500Z
UID:yMbPPwamu_RqzSfzQsoxqebS@stanza.co
SUMMARY:Isotopes vs. Aces
DESCRIPTION:Isotopes vs. Aces\n\nFollow on MiLB First Pitch: https://stza.co/+whAd-o\n\nShop: https://stza.co/+whAd-3\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144500Z
LAST-MODIFIED:20180213T144500Z
TRANSP:OPAQUE
END:VEVENT
* Isotopes vs. Aces
<2018-05-20 Sun 14:35-17:35>
:PROPERTIES:
:ID:       9LUqtu2w92cIlE1mOtquOGhk@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Isotopes vs. Aces Isotopes vs. Aces

Follow on MiLB First Pitch  https //stza.co/+whAf-1D

Shop  https //stza.co/+whAf-2B

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Isotopes vs. Aces
END:VALARM
DTSTART:20180520T193500Z
DTEND:20180520T223500Z
UID:9LUqtu2w92cIlE1mOtquOGhk@stanza.co
SUMMARY:Isotopes vs. Aces
DESCRIPTION:Isotopes vs. Aces\n\nFollow on MiLB First Pitch: https://stza.co/+whAf-1D\n\nShop: https://stza.co/+whAf-2B\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144500Z
LAST-MODIFIED:20180213T144500Z
TRANSP:OPAQUE
END:VEVENT
* Isotopes vs. Bees
<2018-05-21 Mon 19:35-22:35>
:PROPERTIES:
:ID:       0LzFsiEQlEQPe43pHmU-9pQe@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Isotopes vs. Bees Isotopes vs. Bees

Follow on MiLB First Pitch  https //stza.co/+whAh-Z

Shop  https //stza.co/+whAh-3n

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Isotopes vs. Bees
END:VALARM
DTSTART:20180522T003500Z
DTEND:20180522T033500Z
UID:0LzFsiEQlEQPe43pHmU-9pQe@stanza.co
SUMMARY:Isotopes vs. Bees
DESCRIPTION:Isotopes vs. Bees\n\nFollow on MiLB First Pitch: https://stza.co/+whAh-Z\n\nShop: https://stza.co/+whAh-3n\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144500Z
LAST-MODIFIED:20180213T144500Z
TRANSP:OPAQUE
END:VEVENT
* Isotopes vs. Bees
<2018-05-22 Tue 19:35-22:35>
:PROPERTIES:
:ID:       28J9s0tfCU-q23M6tkJfwurS@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Isotopes vs. Bees Isotopes vs. Bees

Follow on MiLB First Pitch  https //stza.co/+whAj-3C

Shop  https //stza.co/+whAj-1y

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Isotopes vs. Bees
END:VALARM
DTSTART:20180523T003500Z
DTEND:20180523T033500Z
UID:28J9s0tfCU-q23M6tkJfwurS@stanza.co
SUMMARY:Isotopes vs. Bees
DESCRIPTION:Isotopes vs. Bees\n\nFollow on MiLB First Pitch: https://stza.co/+whAj-3C\n\nShop: https://stza.co/+whAj-1y\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144500Z
LAST-MODIFIED:20180213T144500Z
TRANSP:OPAQUE
END:VEVENT
* Isotopes vs. Bees
<2018-05-23 Wed 19:35-22:35>
:PROPERTIES:
:ID:       vYQOS6A0E5rMCYkRqdNG2UmZ@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Isotopes vs. Bees Isotopes vs. Bees

Follow on MiLB First Pitch  https //stza.co/+whAm-2x

Shop  https //stza.co/+whAm-4

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Isotopes vs. Bees
END:VALARM
DTSTART:20180524T003500Z
DTEND:20180524T033500Z
UID:vYQOS6A0E5rMCYkRqdNG2UmZ@stanza.co
SUMMARY:Isotopes vs. Bees
DESCRIPTION:Isotopes vs. Bees\n\nFollow on MiLB First Pitch: https://stza.co/+whAm-2x\n\nShop: https://stza.co/+whAm-4\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144500Z
LAST-MODIFIED:20180213T144500Z
TRANSP:OPAQUE
END:VEVENT
* Isotopes vs. Bees
<2018-05-24 Thu 13:05-16:05>
:PROPERTIES:
:ID:       Dx0iVRcbmWcr6tfpLNZpq8pn@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Isotopes vs. Bees Isotopes vs. Bees

Follow on MiLB First Pitch  https //stza.co/+whAn-3k

Shop  https //stza.co/+whAn-2r

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Isotopes vs. Bees
END:VALARM
DTSTART:20180524T180500Z
DTEND:20180524T210500Z
UID:Dx0iVRcbmWcr6tfpLNZpq8pn@stanza.co
SUMMARY:Isotopes vs. Bees
DESCRIPTION:Isotopes vs. Bees\n\nFollow on MiLB First Pitch: https://stza.co/+whAn-3k\n\nShop: https://stza.co/+whAn-2r\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144500Z
LAST-MODIFIED:20180213T144500Z
TRANSP:OPAQUE
END:VEVENT
* Isotopes @ River Cats
<2018-05-25 Fri 21:05>--<2018-05-26 Sat 00:05>
:PROPERTIES:
:ID:       t2zwzFPfkFKLSWy-DpjDl3Lw@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Isotopes @ River Cats Isotopes @ River Cats

Follow on MiLB First Pitch  https //stza.co/+wjwo-3y

Shop  https //stza.co/+wjwo-2y

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Isotopes @ River Cats
END:VALARM
DTSTART:20180526T020500Z
DTEND:20180526T050500Z
UID:t2zwzFPfkFKLSWy-DpjDl3Lw@stanza.co
SUMMARY:Isotopes @ River Cats
DESCRIPTION:Isotopes @ River Cats\n\nFollow on MiLB First Pitch: https://stza.co/+wjwo-3y\n\nShop: https://stza.co/+wjwo-2y\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144500Z
LAST-MODIFIED:20180213T144500Z
TRANSP:OPAQUE
END:VEVENT
* Isotopes @ River Cats
<2018-05-26 Sat 21:05>--<2018-05-27 Sun 00:05>
:PROPERTIES:
:ID:       7Cm46p_CtVCuDwmL-l6-raqB@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Isotopes @ River Cats Isotopes @ River Cats

Follow on MiLB First Pitch  https //stza.co/+wjwp-3x

Shop  https //stza.co/+wjwp-2z

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Isotopes @ River Cats
END:VALARM
DTSTART:20180527T020500Z
DTEND:20180527T050500Z
UID:7Cm46p_CtVCuDwmL-l6-raqB@stanza.co
SUMMARY:Isotopes @ River Cats
DESCRIPTION:Isotopes @ River Cats\n\nFollow on MiLB First Pitch: https://stza.co/+wjwp-3x\n\nShop: https://stza.co/+wjwp-2z\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144500Z
LAST-MODIFIED:20180213T144500Z
TRANSP:OPAQUE
END:VEVENT
* Isotopes @ River Cats
<2018-05-27 Sun 19:05-22:05>
:PROPERTIES:
:ID:       SmYYhS32HccEFp8HKKY3SmbK@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Isotopes @ River Cats Isotopes @ River Cats

Follow on MiLB First Pitch  https //stza.co/+wjwq-l

Shop  https //stza.co/+wjwq-H

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Isotopes @ River Cats
END:VALARM
DTSTART:20180528T000500Z
DTEND:20180528T030500Z
UID:SmYYhS32HccEFp8HKKY3SmbK@stanza.co
SUMMARY:Isotopes @ River Cats
DESCRIPTION:Isotopes @ River Cats\n\nFollow on MiLB First Pitch: https://stza.co/+wjwq-l\n\nShop: https://stza.co/+wjwq-H\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144500Z
LAST-MODIFIED:20180213T144500Z
TRANSP:OPAQUE
END:VEVENT
* Isotopes @ River Cats
<2018-05-28 Mon 15:05-18:05>
:PROPERTIES:
:ID:       wFxdeAj_hEIIMqO19kkqvCHg@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Isotopes @ River Cats Isotopes @ River Cats

Follow on MiLB First Pitch  https //stza.co/+wjwr-a

Shop  https //stza.co/+wjwr-5

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Isotopes @ River Cats
END:VALARM
DTSTART:20180528T200500Z
DTEND:20180528T230500Z
UID:wFxdeAj_hEIIMqO19kkqvCHg@stanza.co
SUMMARY:Isotopes @ River Cats
DESCRIPTION:Isotopes @ River Cats\n\nFollow on MiLB First Pitch: https://stza.co/+wjwr-a\n\nShop: https://stza.co/+wjwr-5\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144500Z
LAST-MODIFIED:20180213T144500Z
TRANSP:OPAQUE
END:VEVENT
* Isotopes @ River Cats
<2018-05-29 Tue 14:05-17:05>
:PROPERTIES:
:ID:       t0caARFxQOyOMGGp2M7QbzmE@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Isotopes @ River Cats Isotopes @ River Cats

Follow on MiLB First Pitch  https //stza.co/+wjws-2X

Shop  https //stza.co/+wjws-G

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Isotopes @ River Cats
END:VALARM
DTSTART:20180529T190500Z
DTEND:20180529T220500Z
UID:t0caARFxQOyOMGGp2M7QbzmE@stanza.co
SUMMARY:Isotopes @ River Cats
DESCRIPTION:Isotopes @ River Cats\n\nFollow on MiLB First Pitch: https://stza.co/+wjws-2X\n\nShop: https://stza.co/+wjws-G\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144500Z
LAST-MODIFIED:20180213T144500Z
TRANSP:OPAQUE
END:VEVENT
* Isotopes vs. Grizzlies
<2018-05-30 Wed 19:35-22:35>
:PROPERTIES:
:ID:       snbBE1etS52E0KxwvGuHifka@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Isotopes vs. Grizzlies Isotopes vs. Grizzlies

Follow on MiLB First Pitch  https //stza.co/+whAp-3L

Shop  https //stza.co/+whAp-2V

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Isotopes vs. Grizzlies
END:VALARM
DTSTART:20180531T003500Z
DTEND:20180531T033500Z
UID:snbBE1etS52E0KxwvGuHifka@stanza.co
SUMMARY:Isotopes vs. Grizzlies
DESCRIPTION:Isotopes vs. Grizzlies\n\nFollow on MiLB First Pitch: https://stza.co/+whAp-3L\n\nShop: https://stza.co/+whAp-2V\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144500Z
LAST-MODIFIED:20180213T144500Z
TRANSP:OPAQUE
END:VEVENT
* Isotopes vs. Grizzlies
<2018-05-31 Thu 19:35-22:35>
:PROPERTIES:
:ID:       gHQ-h_Ih3hx0c_KSgQK4bpPd@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Isotopes vs. Grizzlies Isotopes vs. Grizzlies

Follow on MiLB First Pitch  https //stza.co/+whAs-1Q

Shop  https //stza.co/+whAs-A

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Isotopes vs. Grizzlies
END:VALARM
DTSTART:20180601T003500Z
DTEND:20180601T033500Z
UID:gHQ-h_Ih3hx0c_KSgQK4bpPd@stanza.co
SUMMARY:Isotopes vs. Grizzlies
DESCRIPTION:Isotopes vs. Grizzlies\n\nFollow on MiLB First Pitch: https://stza.co/+whAs-1Q\n\nShop: https://stza.co/+whAs-A\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144500Z
LAST-MODIFIED:20180213T144500Z
TRANSP:OPAQUE
END:VEVENT
* Isotopes vs. Grizzlies
<2018-06-01 Fri 19:35-22:35>
:PROPERTIES:
:ID:       zc86VEd3_v-KdJbSgS7uKF_l@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Isotopes vs. Grizzlies Isotopes vs. Grizzlies

Follow on MiLB First Pitch  https //stza.co/+whAt-3L

Shop  https //stza.co/+whAt-13

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Isotopes vs. Grizzlies
END:VALARM
DTSTART:20180602T003500Z
DTEND:20180602T033500Z
UID:zc86VEd3_v-KdJbSgS7uKF_l@stanza.co
SUMMARY:Isotopes vs. Grizzlies
DESCRIPTION:Isotopes vs. Grizzlies\n\nFollow on MiLB First Pitch: https://stza.co/+whAt-3L\n\nShop: https://stza.co/+whAt-13\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144500Z
LAST-MODIFIED:20180213T144500Z
TRANSP:OPAQUE
END:VEVENT
* Isotopes vs. Grizzlies
<2018-06-02 Sat 19:35-22:35>
:PROPERTIES:
:ID:       D6dJ4xDaRxcScbD-1Kt_NYu_@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Isotopes vs. Grizzlies Isotopes vs. Grizzlies

Follow on MiLB First Pitch  https //stza.co/+whAw-2e

Shop  https //stza.co/+whAw-v

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Isotopes vs. Grizzlies
END:VALARM
DTSTART:20180603T003500Z
DTEND:20180603T033500Z
UID:D6dJ4xDaRxcScbD-1Kt_NYu_@stanza.co
SUMMARY:Isotopes vs. Grizzlies
DESCRIPTION:Isotopes vs. Grizzlies\n\nFollow on MiLB First Pitch: https://stza.co/+whAw-2e\n\nShop: https://stza.co/+whAw-v\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144500Z
LAST-MODIFIED:20180213T144500Z
TRANSP:OPAQUE
END:VEVENT
* Isotopes vs. Grizzlies
<2018-06-03 Sun 14:35-17:35>
:PROPERTIES:
:ID:       -ZI5CgkfzlNV7Xfua5YqvDq-@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Isotopes vs. Grizzlies Isotopes vs. Grizzlies

Follow on MiLB First Pitch  https //stza.co/+whAy-9

Shop  https //stza.co/+whAy-3q

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Isotopes vs. Grizzlies
END:VALARM
DTSTART:20180603T193500Z
DTEND:20180603T223500Z
UID:-ZI5CgkfzlNV7Xfua5YqvDq-@stanza.co
SUMMARY:Isotopes vs. Grizzlies
DESCRIPTION:Isotopes vs. Grizzlies\n\nFollow on MiLB First Pitch: https://stza.co/+whAy-9\n\nShop: https://stza.co/+whAy-3q\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144500Z
LAST-MODIFIED:20180213T144500Z
TRANSP:OPAQUE
END:VEVENT
* Isotopes @ Cubs
<2018-06-05 Tue 19:08-22:08>
:PROPERTIES:
:ID:       vdC9DuloAMiR3W1IfGk_IUKO@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Isotopes @ Cubs Isotopes @ Cubs

Follow on MiLB First Pitch  https //stza.co/+vKsw-2B

Shop  https //stza.co/+vKsw-n

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Isotopes @ Cubs
END:VALARM
DTSTART:20180606T000800Z
DTEND:20180606T030800Z
UID:vdC9DuloAMiR3W1IfGk_IUKO@stanza.co
SUMMARY:Isotopes @ Cubs
DESCRIPTION:Isotopes @ Cubs\n\nFollow on MiLB First Pitch: https://stza.co/+vKsw-2B\n\nShop: https://stza.co/+vKsw-n\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144500Z
LAST-MODIFIED:20180213T144500Z
TRANSP:OPAQUE
END:VEVENT
* Isotopes @ Cubs
<2018-06-06 Wed 12:08-15:08>
:PROPERTIES:
:ID:       FSg6UU4D26lJ7Bjjcot30pD1@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Isotopes @ Cubs Isotopes @ Cubs

Follow on MiLB First Pitch  https //stza.co/+vKsx-21

Shop  https //stza.co/+vKsx-1A

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Isotopes @ Cubs
END:VALARM
DTSTART:20180606T170800Z
DTEND:20180606T200800Z
UID:FSg6UU4D26lJ7Bjjcot30pD1@stanza.co
SUMMARY:Isotopes @ Cubs
DESCRIPTION:Isotopes @ Cubs\n\nFollow on MiLB First Pitch: https://stza.co/+vKsx-21\n\nShop: https://stza.co/+vKsx-1A\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144500Z
LAST-MODIFIED:20180213T144500Z
TRANSP:OPAQUE
END:VEVENT
* Isotopes @ Cubs
<2018-06-07 Thu 19:08-22:08>
:PROPERTIES:
:ID:       quIMKTtS_av2Uew_TvU2fDck@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Isotopes @ Cubs Isotopes @ Cubs

Follow on MiLB First Pitch  https //stza.co/+vKsy-3S

Shop  https //stza.co/+vKsy-1C

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Isotopes @ Cubs
END:VALARM
DTSTART:20180608T000800Z
DTEND:20180608T030800Z
UID:quIMKTtS_av2Uew_TvU2fDck@stanza.co
SUMMARY:Isotopes @ Cubs
DESCRIPTION:Isotopes @ Cubs\n\nFollow on MiLB First Pitch: https://stza.co/+vKsy-3S\n\nShop: https://stza.co/+vKsy-1C\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144500Z
LAST-MODIFIED:20180213T144500Z
TRANSP:OPAQUE
END:VEVENT
* Isotopes @ Storm Chasers
<2018-06-08 Fri 19:05-22:05>
:PROPERTIES:
:ID:       6uR1K2nXM6oiQ0P0M1Mxw52m@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Isotopes @ Storm Chasers Isotopes @ Storm Chasers

Follow on MiLB First Pitch  https //stza.co/+whBV-g

Shop  https //stza.co/+whBV-2N

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Isotopes @ Storm Chasers
END:VALARM
DTSTART:20180609T000500Z
DTEND:20180609T030500Z
UID:6uR1K2nXM6oiQ0P0M1Mxw52m@stanza.co
SUMMARY:Isotopes @ Storm Chasers
DESCRIPTION:Isotopes @ Storm Chasers\n\nFollow on MiLB First Pitch: https://stza.co/+whBV-g\n\nShop: https://stza.co/+whBV-2N\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144500Z
LAST-MODIFIED:20180213T144500Z
TRANSP:OPAQUE
END:VEVENT
* Isotopes @ Storm Chasers
<2018-06-09 Sat 19:05-22:05>
:PROPERTIES:
:ID:       Rg72snSASTI2dHtKmieSycwh@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Isotopes @ Storm Chasers Isotopes @ Storm Chasers

Follow on MiLB First Pitch  https //stza.co/+whBW-3P

Shop  https //stza.co/+whBW-3H

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Isotopes @ Storm Chasers
END:VALARM
DTSTART:20180610T000500Z
DTEND:20180610T030500Z
UID:Rg72snSASTI2dHtKmieSycwh@stanza.co
SUMMARY:Isotopes @ Storm Chasers
DESCRIPTION:Isotopes @ Storm Chasers\n\nFollow on MiLB First Pitch: https://stza.co/+whBW-3P\n\nShop: https://stza.co/+whBW-3H\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144500Z
LAST-MODIFIED:20180213T144500Z
TRANSP:OPAQUE
END:VEVENT
* Isotopes @ Storm Chasers
<2018-06-10 Sun 14:05-17:05>
:PROPERTIES:
:ID:       vwqhzE9fvsH3wyA29KODFsvm@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Isotopes @ Storm Chasers Isotopes @ Storm Chasers

Follow on MiLB First Pitch  https //stza.co/+whBX-K

Shop  https //stza.co/+whBX-2v

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Isotopes @ Storm Chasers
END:VALARM
DTSTART:20180610T190500Z
DTEND:20180610T220500Z
UID:vwqhzE9fvsH3wyA29KODFsvm@stanza.co
SUMMARY:Isotopes @ Storm Chasers
DESCRIPTION:Isotopes @ Storm Chasers\n\nFollow on MiLB First Pitch: https://stza.co/+whBX-K\n\nShop: https://stza.co/+whBX-2v\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144500Z
LAST-MODIFIED:20180213T144500Z
TRANSP:OPAQUE
END:VEVENT
* Isotopes @ Storm Chasers
<2018-06-11 Mon 12:05-15:05>
:PROPERTIES:
:ID:       hT4U-eISCEa46mMzTjm_lzkD@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Isotopes @ Storm Chasers Isotopes @ Storm Chasers

Follow on MiLB First Pitch  https //stza.co/+whBY-3B

Shop  https //stza.co/+whBY-1j

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Isotopes @ Storm Chasers
END:VALARM
DTSTART:20180611T170500Z
DTEND:20180611T200500Z
UID:hT4U-eISCEa46mMzTjm_lzkD@stanza.co
SUMMARY:Isotopes @ Storm Chasers
DESCRIPTION:Isotopes @ Storm Chasers\n\nFollow on MiLB First Pitch: https://stza.co/+whBY-3B\n\nShop: https://stza.co/+whBY-1j\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144500Z
LAST-MODIFIED:20180213T144500Z
TRANSP:OPAQUE
END:VEVENT
* Isotopes vs. Redbirds
<2018-06-13 Wed 19:35-22:35>
:PROPERTIES:
:ID:       xn1TBIUhXc9uILlvnoHeYfJq@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Isotopes vs. Redbirds Isotopes vs. Redbirds

Follow on MiLB First Pitch  https //stza.co/+whAz-

Shop  https //stza.co/+whAz-2m

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Isotopes vs. Redbirds
END:VALARM
DTSTART:20180614T003500Z
DTEND:20180614T033500Z
UID:xn1TBIUhXc9uILlvnoHeYfJq@stanza.co
SUMMARY:Isotopes vs. Redbirds
DESCRIPTION:Isotopes vs. Redbirds\n\nFollow on MiLB First Pitch: https://stza.co/+whAz-\n\nShop: https://stza.co/+whAz-2m\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144500Z
LAST-MODIFIED:20180213T144500Z
TRANSP:OPAQUE
END:VEVENT
* Isotopes vs. Redbirds
<2018-06-14 Thu 19:35-22:35>
:PROPERTIES:
:ID:       8psZ4YNGuLgYvtF3xGxKFuC9@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Isotopes vs. Redbirds Isotopes vs. Redbirds

Follow on MiLB First Pitch  https //stza.co/+whAB-19

Shop  https //stza.co/+whAB-2t

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Isotopes vs. Redbirds
END:VALARM
DTSTART:20180615T003500Z
DTEND:20180615T033500Z
UID:8psZ4YNGuLgYvtF3xGxKFuC9@stanza.co
SUMMARY:Isotopes vs. Redbirds
DESCRIPTION:Isotopes vs. Redbirds\n\nFollow on MiLB First Pitch: https://stza.co/+whAB-19\n\nShop: https://stza.co/+whAB-2t\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144500Z
LAST-MODIFIED:20180213T144500Z
TRANSP:OPAQUE
END:VEVENT
* Isotopes vs. Redbirds
<2018-06-15 Fri 19:35-22:35>
:PROPERTIES:
:ID:       A1d4jfePJc60mHwaGj0-iPQD@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Isotopes vs. Redbirds Isotopes vs. Redbirds

Follow on MiLB First Pitch  https //stza.co/+whAD-3q

Shop  https //stza.co/+whAD-2D

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Isotopes vs. Redbirds
END:VALARM
DTSTART:20180616T003500Z
DTEND:20180616T033500Z
UID:A1d4jfePJc60mHwaGj0-iPQD@stanza.co
SUMMARY:Isotopes vs. Redbirds
DESCRIPTION:Isotopes vs. Redbirds\n\nFollow on MiLB First Pitch: https://stza.co/+whAD-3q\n\nShop: https://stza.co/+whAD-2D\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144500Z
LAST-MODIFIED:20180213T144500Z
TRANSP:OPAQUE
END:VEVENT
* Isotopes vs. Sounds
<2018-06-16 Sat 19:35-22:35>
:PROPERTIES:
:ID:       nsxOOCnpt8KXMAA80FX5RFi2@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Isotopes vs. Sounds Isotopes vs. Sounds

Follow on MiLB First Pitch  https //stza.co/+whAF-2l

Shop  https //stza.co/+whAF-P

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Isotopes vs. Sounds
END:VALARM
DTSTART:20180617T003500Z
DTEND:20180617T033500Z
UID:nsxOOCnpt8KXMAA80FX5RFi2@stanza.co
SUMMARY:Isotopes vs. Sounds
DESCRIPTION:Isotopes vs. Sounds\n\nFollow on MiLB First Pitch: https://stza.co/+whAF-2l\n\nShop: https://stza.co/+whAF-P\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144500Z
LAST-MODIFIED:20180213T144500Z
TRANSP:OPAQUE
END:VEVENT
* Isotopes vs. Sounds
<2018-06-17 Sun 19:05-22:05>
:PROPERTIES:
:ID:       J8LJwuRn5Y_62SBwp_wsWj6v@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Isotopes vs. Sounds Isotopes vs. Sounds

Follow on MiLB First Pitch  https //stza.co/+whAI-2g

Shop  https //stza.co/+whAI-1Y

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Isotopes vs. Sounds
END:VALARM
DTSTART:20180618T000500Z
DTEND:20180618T030500Z
UID:J8LJwuRn5Y_62SBwp_wsWj6v@stanza.co
SUMMARY:Isotopes vs. Sounds
DESCRIPTION:Isotopes vs. Sounds\n\nFollow on MiLB First Pitch: https://stza.co/+whAI-2g\n\nShop: https://stza.co/+whAI-1Y\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144500Z
LAST-MODIFIED:20180213T144500Z
TRANSP:OPAQUE
END:VEVENT
* Isotopes vs. Sounds
<2018-06-18 Mon 19:35-22:35>
:PROPERTIES:
:ID:       k3X0xx0OEHkyLI1Ciw52p20g@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Isotopes vs. Sounds Isotopes vs. Sounds

Follow on MiLB First Pitch  https //stza.co/+whAJ-3G

Shop  https //stza.co/+whAJ-2F

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Isotopes vs. Sounds
END:VALARM
DTSTART:20180619T003500Z
DTEND:20180619T033500Z
UID:k3X0xx0OEHkyLI1Ciw52p20g@stanza.co
SUMMARY:Isotopes vs. Sounds
DESCRIPTION:Isotopes vs. Sounds\n\nFollow on MiLB First Pitch: https://stza.co/+whAJ-3G\n\nShop: https://stza.co/+whAJ-2F\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144500Z
LAST-MODIFIED:20180213T144500Z
TRANSP:OPAQUE
END:VEVENT
* Isotopes vs. Sounds
<2018-06-19 Tue 13:05-16:05>
:PROPERTIES:
:ID:       rDy0QQ0lPKQA1DKM0Hy6tyPa@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Isotopes vs. Sounds Isotopes vs. Sounds

Follow on MiLB First Pitch  https //stza.co/+whAL-1G

Shop  https //stza.co/+whAL-1n

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Isotopes vs. Sounds
END:VALARM
DTSTART:20180619T180500Z
DTEND:20180619T210500Z
UID:rDy0QQ0lPKQA1DKM0Hy6tyPa@stanza.co
SUMMARY:Isotopes vs. Sounds
DESCRIPTION:Isotopes vs. Sounds\n\nFollow on MiLB First Pitch: https://stza.co/+whAL-1G\n\nShop: https://stza.co/+whAL-1n\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144500Z
LAST-MODIFIED:20180213T144500Z
TRANSP:OPAQUE
END:VEVENT
* Isotopes @ Grizzlies
<2018-06-21 Thu 21:05>--<2018-06-22 Fri 00:05>
:PROPERTIES:
:ID:       cAGwanYJSLp6x-dStiuRsmqa@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Isotopes @ Grizzlies Isotopes @ Grizzlies

Follow on MiLB First Pitch  https //stza.co/+wjw8-2H

Shop  https //stza.co/+wjw8-3J

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Isotopes @ Grizzlies
END:VALARM
DTSTART:20180622T020500Z
DTEND:20180622T050500Z
UID:cAGwanYJSLp6x-dStiuRsmqa@stanza.co
SUMMARY:Isotopes @ Grizzlies
DESCRIPTION:Isotopes @ Grizzlies\n\nFollow on MiLB First Pitch: https://stza.co/+wjw8-2H\n\nShop: https://stza.co/+wjw8-3J\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144500Z
LAST-MODIFIED:20180213T144500Z
TRANSP:OPAQUE
END:VEVENT
* Isotopes @ Grizzlies
<2018-06-22 Fri 21:05>--<2018-06-23 Sat 00:05>
:PROPERTIES:
:ID:       B5H68QSVi-b-uYyQnm1niVY1@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Isotopes @ Grizzlies Isotopes @ Grizzlies

Follow on MiLB First Pitch  https //stza.co/+wjw9-27

Shop  https //stza.co/+wjw9-D

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Isotopes @ Grizzlies
END:VALARM
DTSTART:20180623T020500Z
DTEND:20180623T050500Z
UID:B5H68QSVi-b-uYyQnm1niVY1@stanza.co
SUMMARY:Isotopes @ Grizzlies
DESCRIPTION:Isotopes @ Grizzlies\n\nFollow on MiLB First Pitch: https://stza.co/+wjw9-27\n\nShop: https://stza.co/+wjw9-D\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144500Z
LAST-MODIFIED:20180213T144500Z
TRANSP:OPAQUE
END:VEVENT
* Isotopes @ Grizzlies
<2018-06-23 Sat>--<2018-06-22 Fri>
:PROPERTIES:
:ID:       If98-8KWBKiG-Ig63Mcc6bIB@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Isotopes @ Grizzlies Isotopes @ Grizzlies

Follow on MiLB First Pitch  https //stza.co/+vKsr-1e

Shop  https //stza.co/+vKsr-1d

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Isotopes @ Grizzlies
END:VALARM
DTSTART;VALUE=DATE:20180623
DTEND;VALUE=DATE:20180623
UID:If98-8KWBKiG-Ig63Mcc6bIB@stanza.co
SUMMARY:Isotopes @ Grizzlies
DESCRIPTION:Isotopes @ Grizzlies\n\nFollow on MiLB First Pitch: https://stza.co/+vKsr-1e\n\nShop: https://stza.co/+vKsr-1d\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144500Z
LAST-MODIFIED:20180213T144500Z
TRANSP:OPAQUE
END:VEVENT
* Isotopes @ Grizzlies
<2018-06-23 Sat 19:05-22:05>
:PROPERTIES:
:ID:       yTDlbMc6-BqIiedd3i3iRGT7@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Isotopes @ Grizzlies Isotopes @ Grizzlies

Follow on MiLB First Pitch  https //stza.co/+wjwb-2D

Shop  https //stza.co/+wjwb-2n

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Isotopes @ Grizzlies
END:VALARM
DTSTART:20180624T000500Z
DTEND:20180624T030500Z
UID:yTDlbMc6-BqIiedd3i3iRGT7@stanza.co
SUMMARY:Isotopes @ Grizzlies
DESCRIPTION:Isotopes @ Grizzlies\n\nFollow on MiLB First Pitch: https://stza.co/+wjwb-2D\n\nShop: https://stza.co/+wjwb-2n\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144500Z
LAST-MODIFIED:20180213T144500Z
TRANSP:OPAQUE
END:VEVENT
* Isotopes vs. River Cats
<2018-06-25 Mon 19:35-22:35>
:PROPERTIES:
:ID:       ThDDFnIxy4va2tmewrjKU6yC@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Isotopes vs. River Cats Isotopes vs. River Cats

Follow on MiLB First Pitch  https //stza.co/+whAO-1i

Shop  https //stza.co/+whAO-2N

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Isotopes vs. River Cats
END:VALARM
DTSTART:20180626T003500Z
DTEND:20180626T033500Z
UID:ThDDFnIxy4va2tmewrjKU6yC@stanza.co
SUMMARY:Isotopes vs. River Cats
DESCRIPTION:Isotopes vs. River Cats\n\nFollow on MiLB First Pitch: https://stza.co/+whAO-1i\n\nShop: https://stza.co/+whAO-2N\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144500Z
LAST-MODIFIED:20180213T144500Z
TRANSP:OPAQUE
END:VEVENT
* Isotopes vs. River Cats
<2018-06-26 Tue 19:35-22:35>
:PROPERTIES:
:ID:       m-rLt9TaPwBGEzUpsRxNVuyJ@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Isotopes vs. River Cats Isotopes vs. River Cats

Follow on MiLB First Pitch  https //stza.co/+whAP-2w

Shop  https //stza.co/+whAP-1k

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Isotopes vs. River Cats
END:VALARM
DTSTART:20180627T003500Z
DTEND:20180627T033500Z
UID:m-rLt9TaPwBGEzUpsRxNVuyJ@stanza.co
SUMMARY:Isotopes vs. River Cats
DESCRIPTION:Isotopes vs. River Cats\n\nFollow on MiLB First Pitch: https://stza.co/+whAP-2w\n\nShop: https://stza.co/+whAP-1k\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144500Z
LAST-MODIFIED:20180213T144500Z
TRANSP:OPAQUE
END:VEVENT
* Isotopes vs. River Cats
<2018-06-27 Wed 19:35-22:35>
:PROPERTIES:
:ID:       XqlJG20hFVgYvVNXrv68u_l4@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Isotopes vs. River Cats Isotopes vs. River Cats

Follow on MiLB First Pitch  https //stza.co/+whAR-r

Shop  https //stza.co/+whAR-2L

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Isotopes vs. River Cats
END:VALARM
DTSTART:20180628T003500Z
DTEND:20180628T033500Z
UID:XqlJG20hFVgYvVNXrv68u_l4@stanza.co
SUMMARY:Isotopes vs. River Cats
DESCRIPTION:Isotopes vs. River Cats\n\nFollow on MiLB First Pitch: https://stza.co/+whAR-r\n\nShop: https://stza.co/+whAR-2L\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144500Z
LAST-MODIFIED:20180213T144500Z
TRANSP:OPAQUE
END:VEVENT
* Isotopes vs. River Cats
<2018-06-28 Thu 13:05-16:05>
:PROPERTIES:
:ID:       h9a0CpXtHvmosRmWeegGhz1N@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Isotopes vs. River Cats Isotopes vs. River Cats

Follow on MiLB First Pitch  https //stza.co/+whAT-1z

Shop  https //stza.co/+whAT-19

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Isotopes vs. River Cats
END:VALARM
DTSTART:20180628T180500Z
DTEND:20180628T210500Z
UID:h9a0CpXtHvmosRmWeegGhz1N@stanza.co
SUMMARY:Isotopes vs. River Cats
DESCRIPTION:Isotopes vs. River Cats\n\nFollow on MiLB First Pitch: https://stza.co/+whAT-1z\n\nShop: https://stza.co/+whAT-19\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144500Z
LAST-MODIFIED:20180213T144500Z
TRANSP:OPAQUE
END:VEVENT
* Isotopes @ Chihuahuas
<2018-06-29 Fri 20:05-23:05>
:PROPERTIES:
:ID:       7ahkUoV0AGloTDV7xcUs5esZ@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Isotopes @ Chihuahuas Isotopes @ Chihuahuas

Follow on MiLB First Pitch  https //stza.co/+wmve-3n

Shop  https //stza.co/+wmve-1H

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Isotopes @ Chihuahuas
END:VALARM
DTSTART:20180630T010500Z
DTEND:20180630T040500Z
UID:7ahkUoV0AGloTDV7xcUs5esZ@stanza.co
SUMMARY:Isotopes @ Chihuahuas
DESCRIPTION:Isotopes @ Chihuahuas\n\nFollow on MiLB First Pitch: https://stza.co/+wmve-3n\n\nShop: https://stza.co/+wmve-1H\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144500Z
LAST-MODIFIED:20180213T144500Z
TRANSP:OPAQUE
END:VEVENT
* Isotopes @ Chihuahuas
<2018-06-30 Sat 20:05-23:05>
:PROPERTIES:
:ID:       7Q0kHy9xz147w1Xp9n5JNCC-@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Isotopes @ Chihuahuas Isotopes @ Chihuahuas

Follow on MiLB First Pitch  https //stza.co/+wmvf-1l

Shop  https //stza.co/+wmvf-1c

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Isotopes @ Chihuahuas
END:VALARM
DTSTART:20180701T010500Z
DTEND:20180701T040500Z
UID:7Q0kHy9xz147w1Xp9n5JNCC-@stanza.co
SUMMARY:Isotopes @ Chihuahuas
DESCRIPTION:Isotopes @ Chihuahuas\n\nFollow on MiLB First Pitch: https://stza.co/+wmvf-1l\n\nShop: https://stza.co/+wmvf-1c\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144500Z
LAST-MODIFIED:20180213T144500Z
TRANSP:OPAQUE
END:VEVENT
* Isotopes @ Chihuahuas
<2018-07-01 Sun 19:05-22:05>
:PROPERTIES:
:ID:       xdhjDJEW7S8CXMaJ0jRIgvZe@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Isotopes @ Chihuahuas Isotopes @ Chihuahuas

Follow on MiLB First Pitch  https //stza.co/+wmvg-10

Shop  https //stza.co/+wmvg-1G

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Isotopes @ Chihuahuas
END:VALARM
DTSTART:20180702T000500Z
DTEND:20180702T030500Z
UID:xdhjDJEW7S8CXMaJ0jRIgvZe@stanza.co
SUMMARY:Isotopes @ Chihuahuas
DESCRIPTION:Isotopes @ Chihuahuas\n\nFollow on MiLB First Pitch: https://stza.co/+wmvg-10\n\nShop: https://stza.co/+wmvg-1G\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144500Z
LAST-MODIFIED:20180213T144500Z
TRANSP:OPAQUE
END:VEVENT
* Isotopes @ Chihuahuas
<2018-07-02 Mon 20:05-23:05>
:PROPERTIES:
:ID:       p108OMw4gtIiv2jPBLj4rTp1@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Isotopes @ Chihuahuas Isotopes @ Chihuahuas

Follow on MiLB First Pitch  https //stza.co/+wmvh-2p

Shop  https //stza.co/+wmvh-6

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Isotopes @ Chihuahuas
END:VALARM
DTSTART:20180703T010500Z
DTEND:20180703T040500Z
UID:p108OMw4gtIiv2jPBLj4rTp1@stanza.co
SUMMARY:Isotopes @ Chihuahuas
DESCRIPTION:Isotopes @ Chihuahuas\n\nFollow on MiLB First Pitch: https://stza.co/+wmvh-2p\n\nShop: https://stza.co/+wmvh-6\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144500Z
LAST-MODIFIED:20180213T144500Z
TRANSP:OPAQUE
END:VEVENT
* Isotopes @ Chihuahuas
<2018-07-03 Tue 20:05-23:05>
:PROPERTIES:
:ID:       4gOq8Xzs33gEHUH3SZraqRB6@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Isotopes @ Chihuahuas Isotopes @ Chihuahuas

Follow on MiLB First Pitch  https //stza.co/+wmvi-3M

Shop  https //stza.co/+wmvi-3

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Isotopes @ Chihuahuas
END:VALARM
DTSTART:20180704T010500Z
DTEND:20180704T040500Z
UID:4gOq8Xzs33gEHUH3SZraqRB6@stanza.co
SUMMARY:Isotopes @ Chihuahuas
DESCRIPTION:Isotopes @ Chihuahuas\n\nFollow on MiLB First Pitch: https://stza.co/+wmvi-3M\n\nShop: https://stza.co/+wmvi-3\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144500Z
LAST-MODIFIED:20180213T144500Z
TRANSP:OPAQUE
END:VEVENT
* Isotopes vs. Rainiers
<2018-07-04 Wed 19:35-22:35>
:PROPERTIES:
:ID:       jEtcMgjFA6pabt_Adz4A6aJV@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Isotopes vs. Rainiers Isotopes vs. Rainiers

Follow on MiLB First Pitch  https //stza.co/+whAW-2$

Shop  https //stza.co/+whAW-F

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Isotopes vs. Rainiers
END:VALARM
DTSTART:20180705T003500Z
DTEND:20180705T033500Z
UID:jEtcMgjFA6pabt_Adz4A6aJV@stanza.co
SUMMARY:Isotopes vs. Rainiers
DESCRIPTION:Isotopes vs. Rainiers\n\nFollow on MiLB First Pitch: https://stza.co/+whAW-2$\n\nShop: https://stza.co/+whAW-F\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144500Z
LAST-MODIFIED:20180213T144500Z
TRANSP:OPAQUE
END:VEVENT
* Isotopes vs. Rainiers
<2018-07-05 Thu 19:35-22:35>
:PROPERTIES:
:ID:       jfCFlIq8N4fepoeOv0pEkWJa@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Isotopes vs. Rainiers Isotopes vs. Rainiers

Follow on MiLB First Pitch  https //stza.co/+whAY-19

Shop  https //stza.co/+whAY-1c

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Isotopes vs. Rainiers
END:VALARM
DTSTART:20180706T003500Z
DTEND:20180706T033500Z
UID:jfCFlIq8N4fepoeOv0pEkWJa@stanza.co
SUMMARY:Isotopes vs. Rainiers
DESCRIPTION:Isotopes vs. Rainiers\n\nFollow on MiLB First Pitch: https://stza.co/+whAY-19\n\nShop: https://stza.co/+whAY-1c\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144500Z
LAST-MODIFIED:20180213T144500Z
TRANSP:OPAQUE
END:VEVENT
* Isotopes vs. Rainiers
<2018-07-06 Fri 19:35-22:35>
:PROPERTIES:
:ID:       3ojGjtJiBydYZb4S9BoZdqWG@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Isotopes vs. Rainiers Isotopes vs. Rainiers

Follow on MiLB First Pitch  https //stza.co/+whAZ-2h

Shop  https //stza.co/+whAZ-3_

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Isotopes vs. Rainiers
END:VALARM
DTSTART:20180707T003500Z
DTEND:20180707T033500Z
UID:3ojGjtJiBydYZb4S9BoZdqWG@stanza.co
SUMMARY:Isotopes vs. Rainiers
DESCRIPTION:Isotopes vs. Rainiers\n\nFollow on MiLB First Pitch: https://stza.co/+whAZ-2h\n\nShop: https://stza.co/+whAZ-3_\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144500Z
LAST-MODIFIED:20180213T144500Z
TRANSP:OPAQUE
END:VEVENT
* Isotopes vs. Rainiers
<2018-07-07 Sat 19:35-22:35>
:PROPERTIES:
:ID:       Egoabzi8fHOXfHHOcoM280On@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Isotopes vs. Rainiers Isotopes vs. Rainiers

Follow on MiLB First Pitch  https //stza.co/+whA$-o

Shop  https //stza.co/+whA$-1q

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Isotopes vs. Rainiers
END:VALARM
DTSTART:20180708T003500Z
DTEND:20180708T033500Z
UID:Egoabzi8fHOXfHHOcoM280On@stanza.co
SUMMARY:Isotopes vs. Rainiers
DESCRIPTION:Isotopes vs. Rainiers\n\nFollow on MiLB First Pitch: https://stza.co/+whA$-o\n\nShop: https://stza.co/+whA$-1q\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144500Z
LAST-MODIFIED:20180213T144500Z
TRANSP:OPAQUE
END:VEVENT
* Isotopes vs. Rainiers
<2018-07-08 Sun 19:05-22:05>
:PROPERTIES:
:ID:       1nsRe-y5Q6aDnDHQnY4Q6wOX@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Isotopes vs. Rainiers Isotopes vs. Rainiers

Follow on MiLB First Pitch  https //stza.co/+whB1-20

Shop  https //stza.co/+whB1-3L

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Isotopes vs. Rainiers
END:VALARM
DTSTART:20180709T000500Z
DTEND:20180709T030500Z
UID:1nsRe-y5Q6aDnDHQnY4Q6wOX@stanza.co
SUMMARY:Isotopes vs. Rainiers
DESCRIPTION:Isotopes vs. Rainiers\n\nFollow on MiLB First Pitch: https://stza.co/+whB1-20\n\nShop: https://stza.co/+whB1-3L\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144500Z
LAST-MODIFIED:20180213T144500Z
TRANSP:OPAQUE
END:VEVENT
* Isotopes @ 51s
<2018-07-12 Thu 21:05>--<2018-07-13 Fri 00:05>
:PROPERTIES:
:ID:       ovgkt7Sg5YFqIiLa-Vu-UsQo@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Isotopes @ 51s Isotopes @ 51s

Follow on MiLB First Pitch  https //stza.co/+u$2n-1T

Shop  https //stza.co/+u$2n-2v

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Isotopes @ 51s
END:VALARM
DTSTART:20180713T020500Z
DTEND:20180713T050500Z
UID:ovgkt7Sg5YFqIiLa-Vu-UsQo@stanza.co
SUMMARY:Isotopes @ 51s
DESCRIPTION:Isotopes @ 51s\n\nFollow on MiLB First Pitch: https://stza.co/+u$2n-1T\n\nShop: https://stza.co/+u$2n-2v\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144500Z
LAST-MODIFIED:20180213T144500Z
TRANSP:OPAQUE
END:VEVENT
* Isotopes @ 51s
<2018-07-13 Fri 21:05>--<2018-07-14 Sat 00:05>
:PROPERTIES:
:ID:       _TfReWNjk4khkhcAIYXwP2Ji@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Isotopes @ 51s Isotopes @ 51s

Follow on MiLB First Pitch  https //stza.co/+u$2o-2o

Shop  https //stza.co/+u$2o-v

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Isotopes @ 51s
END:VALARM
DTSTART:20180714T020500Z
DTEND:20180714T050500Z
UID:_TfReWNjk4khkhcAIYXwP2Ji@stanza.co
SUMMARY:Isotopes @ 51s
DESCRIPTION:Isotopes @ 51s\n\nFollow on MiLB First Pitch: https://stza.co/+u$2o-2o\n\nShop: https://stza.co/+u$2o-v\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144500Z
LAST-MODIFIED:20180213T144500Z
TRANSP:OPAQUE
END:VEVENT
* Isotopes @ 51s
<2018-07-14 Sat 21:05>--<2018-07-15 Sun 00:05>
:PROPERTIES:
:ID:       fyzJFQG8iIe6o4Poa7l7OHQv@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Isotopes @ 51s Isotopes @ 51s

Follow on MiLB First Pitch  https //stza.co/+u$2p-3t

Shop  https //stza.co/+u$2p-2A

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Isotopes @ 51s
END:VALARM
DTSTART:20180715T020500Z
DTEND:20180715T050500Z
UID:fyzJFQG8iIe6o4Poa7l7OHQv@stanza.co
SUMMARY:Isotopes @ 51s
DESCRIPTION:Isotopes @ 51s\n\nFollow on MiLB First Pitch: https://stza.co/+u$2p-3t\n\nShop: https://stza.co/+u$2p-2A\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144500Z
LAST-MODIFIED:20180213T144500Z
TRANSP:OPAQUE
END:VEVENT
* Isotopes @ 51s
<2018-07-15 Sun 21:05>--<2018-07-16 Mon 00:05>
:PROPERTIES:
:ID:       2JQyIMBwuWfJBC1lCDgaW0fL@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Isotopes @ 51s Isotopes @ 51s

Follow on MiLB First Pitch  https //stza.co/+u$2q-2K

Shop  https //stza.co/+u$2q-3g

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Isotopes @ 51s
END:VALARM
DTSTART:20180716T020500Z
DTEND:20180716T050500Z
UID:2JQyIMBwuWfJBC1lCDgaW0fL@stanza.co
SUMMARY:Isotopes @ 51s
DESCRIPTION:Isotopes @ 51s\n\nFollow on MiLB First Pitch: https://stza.co/+u$2q-2K\n\nShop: https://stza.co/+u$2q-3g\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144500Z
LAST-MODIFIED:20180213T144500Z
TRANSP:OPAQUE
END:VEVENT
* Isotopes vs. Chihuahuas
<2018-07-16 Mon 19:35-22:35>
:PROPERTIES:
:ID:       fw-NRYP78fk8RIiOP3GzBVzL@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Isotopes vs. Chihuahuas Isotopes vs. Chihuahuas

Follow on MiLB First Pitch  https //stza.co/+whB4-11

Shop  https //stza.co/+whB4-2x

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Isotopes vs. Chihuahuas
END:VALARM
DTSTART:20180717T003500Z
DTEND:20180717T033500Z
UID:fw-NRYP78fk8RIiOP3GzBVzL@stanza.co
SUMMARY:Isotopes vs. Chihuahuas
DESCRIPTION:Isotopes vs. Chihuahuas\n\nFollow on MiLB First Pitch: https://stza.co/+whB4-11\n\nShop: https://stza.co/+whB4-2x\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144500Z
LAST-MODIFIED:20180213T144500Z
TRANSP:OPAQUE
END:VEVENT
* Isotopes vs. Chihuahuas
<2018-07-17 Tue 19:35-22:35>
:PROPERTIES:
:ID:       YzbmpuA1-mmISSmDWPJxqrW5@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Isotopes vs. Chihuahuas Isotopes vs. Chihuahuas

Follow on MiLB First Pitch  https //stza.co/+whB5-1N

Shop  https //stza.co/+whB5-S

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Isotopes vs. Chihuahuas
END:VALARM
DTSTART:20180718T003500Z
DTEND:20180718T033500Z
UID:YzbmpuA1-mmISSmDWPJxqrW5@stanza.co
SUMMARY:Isotopes vs. Chihuahuas
DESCRIPTION:Isotopes vs. Chihuahuas\n\nFollow on MiLB First Pitch: https://stza.co/+whB5-1N\n\nShop: https://stza.co/+whB5-S\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144500Z
LAST-MODIFIED:20180213T144500Z
TRANSP:OPAQUE
END:VEVENT
* Isotopes vs. Chihuahuas
<2018-07-18 Wed 19:35-22:35>
:PROPERTIES:
:ID:       sLbe-jgACs8vPiLse5zPwPpz@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Isotopes vs. Chihuahuas Isotopes vs. Chihuahuas

Follow on MiLB First Pitch  https //stza.co/+whBa-2j

Shop  https //stza.co/+whBa-O

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Isotopes vs. Chihuahuas
END:VALARM
DTSTART:20180719T003500Z
DTEND:20180719T033500Z
UID:sLbe-jgACs8vPiLse5zPwPpz@stanza.co
SUMMARY:Isotopes vs. Chihuahuas
DESCRIPTION:Isotopes vs. Chihuahuas\n\nFollow on MiLB First Pitch: https://stza.co/+whBa-2j\n\nShop: https://stza.co/+whBa-O\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144500Z
LAST-MODIFIED:20180213T144500Z
TRANSP:OPAQUE
END:VEVENT
* Isotopes vs. Chihuahuas
<2018-07-19 Thu 13:05-16:05>
:PROPERTIES:
:ID:       CDf3LsizWWqDlXWC5P5wRkmn@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Isotopes vs. Chihuahuas Isotopes vs. Chihuahuas

Follow on MiLB First Pitch  https //stza.co/+whBc-1D

Shop  https //stza.co/+whBc-1s

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Isotopes vs. Chihuahuas
END:VALARM
DTSTART:20180719T180500Z
DTEND:20180719T210500Z
UID:CDf3LsizWWqDlXWC5P5wRkmn@stanza.co
SUMMARY:Isotopes vs. Chihuahuas
DESCRIPTION:Isotopes vs. Chihuahuas\n\nFollow on MiLB First Pitch: https://stza.co/+whBc-1D\n\nShop: https://stza.co/+whBc-1s\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144500Z
LAST-MODIFIED:20180213T144500Z
TRANSP:OPAQUE
END:VEVENT
* Isotopes vs. Grizzlies
<2018-07-20 Fri 19:35-22:35>
:PROPERTIES:
:ID:       OiZUwagF09HgarDITaVTADeP@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Isotopes vs. Grizzlies Isotopes vs. Grizzlies

Follow on MiLB First Pitch  https //stza.co/+whBe-3e

Shop  https //stza.co/+whBe-3k

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Isotopes vs. Grizzlies
END:VALARM
DTSTART:20180721T003500Z
DTEND:20180721T033500Z
UID:OiZUwagF09HgarDITaVTADeP@stanza.co
SUMMARY:Isotopes vs. Grizzlies
DESCRIPTION:Isotopes vs. Grizzlies\n\nFollow on MiLB First Pitch: https://stza.co/+whBe-3e\n\nShop: https://stza.co/+whBe-3k\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144500Z
LAST-MODIFIED:20180213T144500Z
TRANSP:OPAQUE
END:VEVENT
* Isotopes vs. Grizzlies
<2018-07-21 Sat 19:35-22:35>
:PROPERTIES:
:ID:       OZ4oYIo_xu-u7pzA4AKgMX4I@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Isotopes vs. Grizzlies Isotopes vs. Grizzlies

Follow on MiLB First Pitch  https //stza.co/+whBf-1D

Shop  https //stza.co/+whBf-v

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Isotopes vs. Grizzlies
END:VALARM
DTSTART:20180722T003500Z
DTEND:20180722T033500Z
UID:OZ4oYIo_xu-u7pzA4AKgMX4I@stanza.co
SUMMARY:Isotopes vs. Grizzlies
DESCRIPTION:Isotopes vs. Grizzlies\n\nFollow on MiLB First Pitch: https://stza.co/+whBf-1D\n\nShop: https://stza.co/+whBf-v\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144500Z
LAST-MODIFIED:20180213T144500Z
TRANSP:OPAQUE
END:VEVENT
* Isotopes vs. Grizzlies
<2018-07-22 Sun 19:05-22:05>
:PROPERTIES:
:ID:       MierQwvNv3vXMMrmEFJ5oWzW@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Isotopes vs. Grizzlies Isotopes vs. Grizzlies

Follow on MiLB First Pitch  https //stza.co/+whBh-2T

Shop  https //stza.co/+whBh-l

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Isotopes vs. Grizzlies
END:VALARM
DTSTART:20180723T000500Z
DTEND:20180723T030500Z
UID:MierQwvNv3vXMMrmEFJ5oWzW@stanza.co
SUMMARY:Isotopes vs. Grizzlies
DESCRIPTION:Isotopes vs. Grizzlies\n\nFollow on MiLB First Pitch: https://stza.co/+whBh-2T\n\nShop: https://stza.co/+whBh-l\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144500Z
LAST-MODIFIED:20180213T144500Z
TRANSP:OPAQUE
END:VEVENT
* Isotopes @ Dodgers
<2018-07-24 Tue 19:05-22:05>
:PROPERTIES:
:ID:       ruWNnMpv92XP170VBIxkOoFx@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Isotopes @ Dodgers Isotopes @ Dodgers

Follow on MiLB First Pitch  https //stza.co/+v$M2-3D

Shop  https //stza.co/+v$M2-g

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Isotopes @ Dodgers
END:VALARM
DTSTART:20180725T000500Z
DTEND:20180725T030500Z
UID:ruWNnMpv92XP170VBIxkOoFx@stanza.co
SUMMARY:Isotopes @ Dodgers
DESCRIPTION:Isotopes @ Dodgers\n\nFollow on MiLB First Pitch: https://stza.co/+v$M2-3D\n\nShop: https://stza.co/+v$M2-g\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144500Z
LAST-MODIFIED:20180213T144500Z
TRANSP:OPAQUE
END:VEVENT
* Isotopes @ Dodgers
<2018-07-25 Wed 19:05-22:05>
:PROPERTIES:
:ID:       e1U-Mf-EZ1BlxsEydGeWBFeb@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Isotopes @ Dodgers Isotopes @ Dodgers

Follow on MiLB First Pitch  https //stza.co/+v$M3-3E

Shop  https //stza.co/+v$M3-6

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Isotopes @ Dodgers
END:VALARM
DTSTART:20180726T000500Z
DTEND:20180726T030500Z
UID:e1U-Mf-EZ1BlxsEydGeWBFeb@stanza.co
SUMMARY:Isotopes @ Dodgers
DESCRIPTION:Isotopes @ Dodgers\n\nFollow on MiLB First Pitch: https://stza.co/+v$M3-3E\n\nShop: https://stza.co/+v$M3-6\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144500Z
LAST-MODIFIED:20180213T144500Z
TRANSP:OPAQUE
END:VEVENT
* Isotopes @ Dodgers
<2018-07-26 Thu 19:05-22:05>
:PROPERTIES:
:ID:       x12RlInQGeRzZJyNKM0FOGg5@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Isotopes @ Dodgers Isotopes @ Dodgers

Follow on MiLB First Pitch  https //stza.co/+v$M4-r

Shop  https //stza.co/+v$M4-15

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Isotopes @ Dodgers
END:VALARM
DTSTART:20180727T000500Z
DTEND:20180727T030500Z
UID:x12RlInQGeRzZJyNKM0FOGg5@stanza.co
SUMMARY:Isotopes @ Dodgers
DESCRIPTION:Isotopes @ Dodgers\n\nFollow on MiLB First Pitch: https://stza.co/+v$M4-r\n\nShop: https://stza.co/+v$M4-15\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144500Z
LAST-MODIFIED:20180213T144500Z
TRANSP:OPAQUE
END:VEVENT
* Isotopes @ Sky Sox
<2018-07-27 Fri 19:40-22:40>
:PROPERTIES:
:ID:       T_-ndu4WENs3BHIxuwfcuO1A@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Isotopes @ Sky Sox Isotopes @ Sky Sox

Follow on MiLB First Pitch  https //stza.co/+wmva-3l

Shop  https //stza.co/+wmva-3h

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Isotopes @ Sky Sox
END:VALARM
DTSTART:20180728T004000Z
DTEND:20180728T034000Z
UID:T_-ndu4WENs3BHIxuwfcuO1A@stanza.co
SUMMARY:Isotopes @ Sky Sox
DESCRIPTION:Isotopes @ Sky Sox\n\nFollow on MiLB First Pitch: https://stza.co/+wmva-3l\n\nShop: https://stza.co/+wmva-3h\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144500Z
LAST-MODIFIED:20180213T144500Z
TRANSP:OPAQUE
END:VEVENT
* Isotopes @ Sky Sox
<2018-07-28 Sat 19:00-22:00>
:PROPERTIES:
:ID:       KFAqS6UsgesRDjrkf1mwEaR-@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Isotopes @ Sky Sox Isotopes @ Sky Sox

Follow on MiLB First Pitch  https //stza.co/+wmvb-u

Shop  https //stza.co/+wmvb-G

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Isotopes @ Sky Sox
END:VALARM
DTSTART:20180729T000000Z
DTEND:20180729T030000Z
UID:KFAqS6UsgesRDjrkf1mwEaR-@stanza.co
SUMMARY:Isotopes @ Sky Sox
DESCRIPTION:Isotopes @ Sky Sox\n\nFollow on MiLB First Pitch: https://stza.co/+wmvb-u\n\nShop: https://stza.co/+wmvb-G\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144500Z
LAST-MODIFIED:20180213T144500Z
TRANSP:OPAQUE
END:VEVENT
* Isotopes @ Sky Sox
<2018-07-29 Sun 14:30-17:30>
:PROPERTIES:
:ID:       7rqNFE7isc-uPhB4VdD3kGkB@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Isotopes @ Sky Sox Isotopes @ Sky Sox

Follow on MiLB First Pitch  https //stza.co/+wmvc-3B

Shop  https //stza.co/+wmvc-c

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Isotopes @ Sky Sox
END:VALARM
DTSTART:20180729T193000Z
DTEND:20180729T223000Z
UID:7rqNFE7isc-uPhB4VdD3kGkB@stanza.co
SUMMARY:Isotopes @ Sky Sox
DESCRIPTION:Isotopes @ Sky Sox\n\nFollow on MiLB First Pitch: https://stza.co/+wmvc-3B\n\nShop: https://stza.co/+wmvc-c\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144500Z
LAST-MODIFIED:20180213T144500Z
TRANSP:OPAQUE
END:VEVENT
* Isotopes @ Sky Sox
<2018-07-30 Mon 19:40-22:40>
:PROPERTIES:
:ID:       YiDE2j0OOyzyE15bXPvFFxnr@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Isotopes @ Sky Sox Isotopes @ Sky Sox

Follow on MiLB First Pitch  https //stza.co/+wmvd-19

Shop  https //stza.co/+wmvd-3h

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Isotopes @ Sky Sox
END:VALARM
DTSTART:20180731T004000Z
DTEND:20180731T034000Z
UID:YiDE2j0OOyzyE15bXPvFFxnr@stanza.co
SUMMARY:Isotopes @ Sky Sox
DESCRIPTION:Isotopes @ Sky Sox\n\nFollow on MiLB First Pitch: https://stza.co/+wmvd-19\n\nShop: https://stza.co/+wmvd-3h\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144500Z
LAST-MODIFIED:20180213T144500Z
TRANSP:OPAQUE
END:VEVENT
* Isotopes vs. Express
<2018-08-01 Wed 19:35-22:35>
:PROPERTIES:
:ID:       lG4CFUyBydUOHFpXDeji7ys2@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Isotopes vs. Express Isotopes vs. Express

Follow on MiLB First Pitch  https //stza.co/+whBj-3B

Shop  https //stza.co/+whBj-3C

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Isotopes vs. Express
END:VALARM
DTSTART:20180802T003500Z
DTEND:20180802T033500Z
UID:lG4CFUyBydUOHFpXDeji7ys2@stanza.co
SUMMARY:Isotopes vs. Express
DESCRIPTION:Isotopes vs. Express\n\nFollow on MiLB First Pitch: https://stza.co/+whBj-3B\n\nShop: https://stza.co/+whBj-3C\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144500Z
LAST-MODIFIED:20180213T144500Z
TRANSP:OPAQUE
END:VEVENT
* Isotopes vs. Express
<2018-08-02 Thu 19:35-22:35>
:PROPERTIES:
:ID:       _AnOvJH2CidH_KjCPwXBxVqc@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Isotopes vs. Express Isotopes vs. Express

Follow on MiLB First Pitch  https //stza.co/+whBl-J

Shop  https //stza.co/+whBl-1$

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Isotopes vs. Express
END:VALARM
DTSTART:20180803T003500Z
DTEND:20180803T033500Z
UID:_AnOvJH2CidH_KjCPwXBxVqc@stanza.co
SUMMARY:Isotopes vs. Express
DESCRIPTION:Isotopes vs. Express\n\nFollow on MiLB First Pitch: https://stza.co/+whBl-J\n\nShop: https://stza.co/+whBl-1$\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144500Z
LAST-MODIFIED:20180213T144500Z
TRANSP:OPAQUE
END:VEVENT
* Isotopes vs. Express
<2018-08-03 Fri 19:35-22:35>
:PROPERTIES:
:ID:       GeM-ph6hOyEkXVaLujfe9vWz@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Isotopes vs. Express Isotopes vs. Express

Follow on MiLB First Pitch  https //stza.co/+whBo-R

Shop  https //stza.co/+whBo-1i

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Isotopes vs. Express
END:VALARM
DTSTART:20180804T003500Z
DTEND:20180804T033500Z
UID:GeM-ph6hOyEkXVaLujfe9vWz@stanza.co
SUMMARY:Isotopes vs. Express
DESCRIPTION:Isotopes vs. Express\n\nFollow on MiLB First Pitch: https://stza.co/+whBo-R\n\nShop: https://stza.co/+whBo-1i\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144500Z
LAST-MODIFIED:20180213T144500Z
TRANSP:OPAQUE
END:VEVENT
* Isotopes vs. Baby Cakes
<2018-08-04 Sat 19:35-22:35>
:PROPERTIES:
:ID:       XhJ3l9LwZsHBqTHy6XyMLDsC@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Isotopes vs. Baby Cakes Isotopes vs. Baby Cakes

Follow on MiLB First Pitch  https //stza.co/+whBq-3W

Shop  https //stza.co/+whBq-v

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Isotopes vs. Baby Cakes
END:VALARM
DTSTART:20180805T003500Z
DTEND:20180805T033500Z
UID:XhJ3l9LwZsHBqTHy6XyMLDsC@stanza.co
SUMMARY:Isotopes vs. Baby Cakes
DESCRIPTION:Isotopes vs. Baby Cakes\n\nFollow on MiLB First Pitch: https://stza.co/+whBq-3W\n\nShop: https://stza.co/+whBq-v\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144500Z
LAST-MODIFIED:20180213T144500Z
TRANSP:OPAQUE
END:VEVENT
* Isotopes vs. Baby Cakes
<2018-08-05 Sun 19:05-22:05>
:PROPERTIES:
:ID:       3SbbZ2A42MHc7Zd6qcuG7BJA@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Isotopes vs. Baby Cakes Isotopes vs. Baby Cakes

Follow on MiLB First Pitch  https //stza.co/+whBr-1N

Shop  https //stza.co/+whBr-3i

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Isotopes vs. Baby Cakes
END:VALARM
DTSTART:20180806T000500Z
DTEND:20180806T030500Z
UID:3SbbZ2A42MHc7Zd6qcuG7BJA@stanza.co
SUMMARY:Isotopes vs. Baby Cakes
DESCRIPTION:Isotopes vs. Baby Cakes\n\nFollow on MiLB First Pitch: https://stza.co/+whBr-1N\n\nShop: https://stza.co/+whBr-3i\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144500Z
LAST-MODIFIED:20180213T144500Z
TRANSP:OPAQUE
END:VEVENT
* Isotopes vs. Baby Cakes
<2018-08-06 Mon 19:35-22:35>
:PROPERTIES:
:ID:       hcS5IRtqwZRssBjyHTA4HNie@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Isotopes vs. Baby Cakes Isotopes vs. Baby Cakes

Follow on MiLB First Pitch  https //stza.co/+whBu-2F

Shop  https //stza.co/+whBu-1D

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Isotopes vs. Baby Cakes
END:VALARM
DTSTART:20180807T003500Z
DTEND:20180807T033500Z
UID:hcS5IRtqwZRssBjyHTA4HNie@stanza.co
SUMMARY:Isotopes vs. Baby Cakes
DESCRIPTION:Isotopes vs. Baby Cakes\n\nFollow on MiLB First Pitch: https://stza.co/+whBu-2F\n\nShop: https://stza.co/+whBu-1D\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144500Z
LAST-MODIFIED:20180213T144500Z
TRANSP:OPAQUE
END:VEVENT
* Isotopes vs. Baby Cakes
<2018-08-07 Tue 13:05-16:05>
:PROPERTIES:
:ID:       _yRP-cX8zzYCexhciwTm3hJF@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Isotopes vs. Baby Cakes Isotopes vs. Baby Cakes

Follow on MiLB First Pitch  https //stza.co/+whBv-1s

Shop  https //stza.co/+whBv-3T

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Isotopes vs. Baby Cakes
END:VALARM
DTSTART:20180807T180500Z
DTEND:20180807T210500Z
UID:_yRP-cX8zzYCexhciwTm3hJF@stanza.co
SUMMARY:Isotopes vs. Baby Cakes
DESCRIPTION:Isotopes vs. Baby Cakes\n\nFollow on MiLB First Pitch: https://stza.co/+whBv-1s\n\nShop: https://stza.co/+whBv-3T\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144500Z
LAST-MODIFIED:20180213T144500Z
TRANSP:OPAQUE
END:VEVENT
* Isotopes @ Grizzlies
<2018-08-09 Thu 21:05>--<2018-08-10 Fri 00:05>
:PROPERTIES:
:ID:       B1TsIWW_9kED9497QGlSTaAH@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Isotopes @ Grizzlies Isotopes @ Grizzlies

Follow on MiLB First Pitch  https //stza.co/+wjwc-3n

Shop  https //stza.co/+wjwc-2o

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Isotopes @ Grizzlies
END:VALARM
DTSTART:20180810T020500Z
DTEND:20180810T050500Z
UID:B1TsIWW_9kED9497QGlSTaAH@stanza.co
SUMMARY:Isotopes @ Grizzlies
DESCRIPTION:Isotopes @ Grizzlies\n\nFollow on MiLB First Pitch: https://stza.co/+wjwc-3n\n\nShop: https://stza.co/+wjwc-2o\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144500Z
LAST-MODIFIED:20180213T144500Z
TRANSP:OPAQUE
END:VEVENT
* Isotopes @ Grizzlies
<2018-08-10 Fri 21:05>--<2018-08-11 Sat 00:05>
:PROPERTIES:
:ID:       I-AesQDp5g_tsm_PYr-m_rUk@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Isotopes @ Grizzlies Isotopes @ Grizzlies

Follow on MiLB First Pitch  https //stza.co/+wjwd-q

Shop  https //stza.co/+wjwd-11

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Isotopes @ Grizzlies
END:VALARM
DTSTART:20180811T020500Z
DTEND:20180811T050500Z
UID:I-AesQDp5g_tsm_PYr-m_rUk@stanza.co
SUMMARY:Isotopes @ Grizzlies
DESCRIPTION:Isotopes @ Grizzlies\n\nFollow on MiLB First Pitch: https://stza.co/+wjwd-q\n\nShop: https://stza.co/+wjwd-11\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144500Z
LAST-MODIFIED:20180213T144500Z
TRANSP:OPAQUE
END:VEVENT
* Isotopes @ Grizzlies
<2018-08-11 Sat 21:05>--<2018-08-12 Sun 00:05>
:PROPERTIES:
:ID:       Z0mxHrNY7mVxnLSLH8MFFn7k@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Isotopes @ Grizzlies Isotopes @ Grizzlies

Follow on MiLB First Pitch  https //stza.co/+wjwe-1N

Shop  https //stza.co/+wjwe-1G

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Isotopes @ Grizzlies
END:VALARM
DTSTART:20180812T020500Z
DTEND:20180812T050500Z
UID:Z0mxHrNY7mVxnLSLH8MFFn7k@stanza.co
SUMMARY:Isotopes @ Grizzlies
DESCRIPTION:Isotopes @ Grizzlies\n\nFollow on MiLB First Pitch: https://stza.co/+wjwe-1N\n\nShop: https://stza.co/+wjwe-1G\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144500Z
LAST-MODIFIED:20180213T144500Z
TRANSP:OPAQUE
END:VEVENT
* Isotopes @ Grizzlies
<2018-08-12 Sun 19:05-22:05>
:PROPERTIES:
:ID:       XYK1xpnTZiSxn70uGeC6dyR5@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Isotopes @ Grizzlies Isotopes @ Grizzlies

Follow on MiLB First Pitch  https //stza.co/+wjwf-2F

Shop  https //stza.co/+wjwf-1I

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Isotopes @ Grizzlies
END:VALARM
DTSTART:20180813T000500Z
DTEND:20180813T030500Z
UID:XYK1xpnTZiSxn70uGeC6dyR5@stanza.co
SUMMARY:Isotopes @ Grizzlies
DESCRIPTION:Isotopes @ Grizzlies\n\nFollow on MiLB First Pitch: https://stza.co/+wjwf-2F\n\nShop: https://stza.co/+wjwf-1I\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144500Z
LAST-MODIFIED:20180213T144500Z
TRANSP:OPAQUE
END:VEVENT
* Isotopes vs. Rainiers
<2018-08-13 Mon 19:35-22:35>
:PROPERTIES:
:ID:       XYsi6x1fZC1m7d5w_qo0CiMZ@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Isotopes vs. Rainiers Isotopes vs. Rainiers

Follow on MiLB First Pitch  https //stza.co/+whBy-3Z

Shop  https //stza.co/+whBy-29

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Isotopes vs. Rainiers
END:VALARM
DTSTART:20180814T003500Z
DTEND:20180814T033500Z
UID:XYsi6x1fZC1m7d5w_qo0CiMZ@stanza.co
SUMMARY:Isotopes vs. Rainiers
DESCRIPTION:Isotopes vs. Rainiers\n\nFollow on MiLB First Pitch: https://stza.co/+whBy-3Z\n\nShop: https://stza.co/+whBy-29\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144500Z
LAST-MODIFIED:20180213T144500Z
TRANSP:OPAQUE
END:VEVENT
* Isotopes vs. Rainiers
<2018-08-14 Tue 19:35-22:35>
:PROPERTIES:
:ID:       MhXJ33S6LW8b3VA5OBhyaers@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Isotopes vs. Rainiers Isotopes vs. Rainiers

Follow on MiLB First Pitch  https //stza.co/+whBz-2C

Shop  https //stza.co/+whBz-2Z

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Isotopes vs. Rainiers
END:VALARM
DTSTART:20180815T003500Z
DTEND:20180815T033500Z
UID:MhXJ33S6LW8b3VA5OBhyaers@stanza.co
SUMMARY:Isotopes vs. Rainiers
DESCRIPTION:Isotopes vs. Rainiers\n\nFollow on MiLB First Pitch: https://stza.co/+whBz-2C\n\nShop: https://stza.co/+whBz-2Z\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144500Z
LAST-MODIFIED:20180213T144500Z
TRANSP:OPAQUE
END:VEVENT
* Isotopes vs. Rainiers
<2018-08-15 Wed 19:35-22:35>
:PROPERTIES:
:ID:       A3wScmvRbjnqwl_jZ4CEh8jZ@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Isotopes vs. Rainiers Isotopes vs. Rainiers

Follow on MiLB First Pitch  https //stza.co/+whBB-3J

Shop  https //stza.co/+whBB-1n

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Isotopes vs. Rainiers
END:VALARM
DTSTART:20180816T003500Z
DTEND:20180816T033500Z
UID:A3wScmvRbjnqwl_jZ4CEh8jZ@stanza.co
SUMMARY:Isotopes vs. Rainiers
DESCRIPTION:Isotopes vs. Rainiers\n\nFollow on MiLB First Pitch: https://stza.co/+whBB-3J\n\nShop: https://stza.co/+whBB-1n\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144500Z
LAST-MODIFIED:20180213T144500Z
TRANSP:OPAQUE
END:VEVENT
* Isotopes vs. River Cats
<2018-08-16 Thu 19:35-22:35>
:PROPERTIES:
:ID:       mXRcQHDpWT43ZEVWwRRi7zwA@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Isotopes vs. River Cats Isotopes vs. River Cats

Follow on MiLB First Pitch  https //stza.co/+whBF-2D

Shop  https //stza.co/+whBF-1n

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Isotopes vs. River Cats
END:VALARM
DTSTART:20180817T003500Z
DTEND:20180817T033500Z
UID:mXRcQHDpWT43ZEVWwRRi7zwA@stanza.co
SUMMARY:Isotopes vs. River Cats
DESCRIPTION:Isotopes vs. River Cats\n\nFollow on MiLB First Pitch: https://stza.co/+whBF-2D\n\nShop: https://stza.co/+whBF-1n\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144500Z
LAST-MODIFIED:20180213T144500Z
TRANSP:OPAQUE
END:VEVENT
* Isotopes vs. River Cats
<2018-08-17 Fri 19:35-22:35>
:PROPERTIES:
:ID:       XVHEDyghBxXOa4f2PHzi7EVq@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Isotopes vs. River Cats Isotopes vs. River Cats

Follow on MiLB First Pitch  https //stza.co/+whBH-1F

Shop  https //stza.co/+whBH-v

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Isotopes vs. River Cats
END:VALARM
DTSTART:20180818T003500Z
DTEND:20180818T033500Z
UID:XVHEDyghBxXOa4f2PHzi7EVq@stanza.co
SUMMARY:Isotopes vs. River Cats
DESCRIPTION:Isotopes vs. River Cats\n\nFollow on MiLB First Pitch: https://stza.co/+whBH-1F\n\nShop: https://stza.co/+whBH-v\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144500Z
LAST-MODIFIED:20180213T144500Z
TRANSP:OPAQUE
END:VEVENT
* Isotopes vs. River Cats
<2018-08-18 Sat 19:35-22:35>
:PROPERTIES:
:ID:       o5IzRNhbAsUIRqpUacCMxpz7@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Isotopes vs. River Cats Isotopes vs. River Cats

Follow on MiLB First Pitch  https //stza.co/+whBI-1B

Shop  https //stza.co/+whBI-3U

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Isotopes vs. River Cats
END:VALARM
DTSTART:20180819T003500Z
DTEND:20180819T033500Z
UID:o5IzRNhbAsUIRqpUacCMxpz7@stanza.co
SUMMARY:Isotopes vs. River Cats
DESCRIPTION:Isotopes vs. River Cats\n\nFollow on MiLB First Pitch: https://stza.co/+whBI-1B\n\nShop: https://stza.co/+whBI-3U\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144500Z
LAST-MODIFIED:20180213T144500Z
TRANSP:OPAQUE
END:VEVENT
* Isotopes vs. River Cats
<2018-08-19 Sun 19:05-22:05>
:PROPERTIES:
:ID:       g8unXMqb9_cAAiYGrV3P5nbV@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Isotopes vs. River Cats Isotopes vs. River Cats

Follow on MiLB First Pitch  https //stza.co/+whBL-3M

Shop  https //stza.co/+whBL-3x

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Isotopes vs. River Cats
END:VALARM
DTSTART:20180820T000500Z
DTEND:20180820T030500Z
UID:g8unXMqb9_cAAiYGrV3P5nbV@stanza.co
SUMMARY:Isotopes vs. River Cats
DESCRIPTION:Isotopes vs. River Cats\n\nFollow on MiLB First Pitch: https://stza.co/+whBL-3M\n\nShop: https://stza.co/+whBL-3x\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144500Z
LAST-MODIFIED:20180213T144500Z
TRANSP:OPAQUE
END:VEVENT
* Isotopes @ Chihuahuas
<2018-08-21 Tue 19:35-22:35>
:PROPERTIES:
:ID:       6co3aynlAZz1l_eCbMpxQ0yC@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Isotopes @ Chihuahuas Isotopes @ Chihuahuas

Follow on MiLB First Pitch  https //stza.co/+wmvk-Y

Shop  https //stza.co/+wmvk-f

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Isotopes @ Chihuahuas
END:VALARM
DTSTART:20180822T003500Z
DTEND:20180822T033500Z
UID:6co3aynlAZz1l_eCbMpxQ0yC@stanza.co
SUMMARY:Isotopes @ Chihuahuas
DESCRIPTION:Isotopes @ Chihuahuas\n\nFollow on MiLB First Pitch: https://stza.co/+wmvk-Y\n\nShop: https://stza.co/+wmvk-f\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144500Z
LAST-MODIFIED:20180213T144500Z
TRANSP:OPAQUE
END:VEVENT
* Isotopes @ Chihuahuas
<2018-08-22 Wed 19:35-22:35>
:PROPERTIES:
:ID:       tBpdujdjeLmb4kuGN5udDXiO@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Isotopes @ Chihuahuas Isotopes @ Chihuahuas

Follow on MiLB First Pitch  https //stza.co/+wmvl-1L

Shop  https //stza.co/+wmvl-14

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Isotopes @ Chihuahuas
END:VALARM
DTSTART:20180823T003500Z
DTEND:20180823T033500Z
UID:tBpdujdjeLmb4kuGN5udDXiO@stanza.co
SUMMARY:Isotopes @ Chihuahuas
DESCRIPTION:Isotopes @ Chihuahuas\n\nFollow on MiLB First Pitch: https://stza.co/+wmvl-1L\n\nShop: https://stza.co/+wmvl-14\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144500Z
LAST-MODIFIED:20180213T144500Z
TRANSP:OPAQUE
END:VEVENT
* Isotopes @ Chihuahuas
<2018-08-23 Thu 19:35-22:35>
:PROPERTIES:
:ID:       EQVCJfvwdFbqCTgMoFL9o0y1@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Isotopes @ Chihuahuas Isotopes @ Chihuahuas

Follow on MiLB First Pitch  https //stza.co/+wmvn-1g

Shop  https //stza.co/+wmvn-3j

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Isotopes @ Chihuahuas
END:VALARM
DTSTART:20180824T003500Z
DTEND:20180824T033500Z
UID:EQVCJfvwdFbqCTgMoFL9o0y1@stanza.co
SUMMARY:Isotopes @ Chihuahuas
DESCRIPTION:Isotopes @ Chihuahuas\n\nFollow on MiLB First Pitch: https://stza.co/+wmvn-1g\n\nShop: https://stza.co/+wmvn-3j\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144500Z
LAST-MODIFIED:20180213T144500Z
TRANSP:OPAQUE
END:VEVENT
* Isotopes vs. Aces
<2018-08-24 Fri 19:35-22:35>
:PROPERTIES:
:ID:       rmKWlIAXjd21rmbzHt0_aaTc@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Isotopes vs. Aces Isotopes vs. Aces

Follow on MiLB First Pitch  https //stza.co/+whBM-1M

Shop  https //stza.co/+whBM-3I

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Isotopes vs. Aces
END:VALARM
DTSTART:20180825T003500Z
DTEND:20180825T033500Z
UID:rmKWlIAXjd21rmbzHt0_aaTc@stanza.co
SUMMARY:Isotopes vs. Aces
DESCRIPTION:Isotopes vs. Aces\n\nFollow on MiLB First Pitch: https://stza.co/+whBM-1M\n\nShop: https://stza.co/+whBM-3I\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144500Z
LAST-MODIFIED:20180213T144500Z
TRANSP:OPAQUE
END:VEVENT
* Isotopes vs. Aces
<2018-08-25 Sat 19:35-22:35>
:PROPERTIES:
:ID:       qmJjUfL1-XMK03zXMTdNC0P1@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Isotopes vs. Aces Isotopes vs. Aces

Follow on MiLB First Pitch  https //stza.co/+whBO-1N

Shop  https //stza.co/+whBO-v

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Isotopes vs. Aces
END:VALARM
DTSTART:20180826T003500Z
DTEND:20180826T033500Z
UID:qmJjUfL1-XMK03zXMTdNC0P1@stanza.co
SUMMARY:Isotopes vs. Aces
DESCRIPTION:Isotopes vs. Aces\n\nFollow on MiLB First Pitch: https://stza.co/+whBO-1N\n\nShop: https://stza.co/+whBO-v\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144500Z
LAST-MODIFIED:20180213T144500Z
TRANSP:OPAQUE
END:VEVENT
* Isotopes vs. Aces
<2018-08-26 Sun 19:05-22:05>
:PROPERTIES:
:ID:       JerQYTtSf62l68OGyT4M2gW_@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Isotopes vs. Aces Isotopes vs. Aces

Follow on MiLB First Pitch  https //stza.co/+whBR-2l

Shop  https //stza.co/+whBR-z

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Isotopes vs. Aces
END:VALARM
DTSTART:20180827T000500Z
DTEND:20180827T030500Z
UID:JerQYTtSf62l68OGyT4M2gW_@stanza.co
SUMMARY:Isotopes vs. Aces
DESCRIPTION:Isotopes vs. Aces\n\nFollow on MiLB First Pitch: https://stza.co/+whBR-2l\n\nShop: https://stza.co/+whBR-z\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144500Z
LAST-MODIFIED:20180213T144500Z
TRANSP:OPAQUE
END:VEVENT
* Isotopes vs. Aces
<2018-08-27 Mon 19:35-22:35>
:PROPERTIES:
:ID:       4LDLDZHIapJNyWCRhSlSe9-a@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Isotopes vs. Aces Isotopes vs. Aces

Follow on MiLB First Pitch  https //stza.co/+whBT-1o

Shop  https //stza.co/+whBT-3x

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Isotopes vs. Aces
END:VALARM
DTSTART:20180828T003500Z
DTEND:20180828T033500Z
UID:4LDLDZHIapJNyWCRhSlSe9-a@stanza.co
SUMMARY:Isotopes vs. Aces
DESCRIPTION:Isotopes vs. Aces\n\nFollow on MiLB First Pitch: https://stza.co/+whBT-1o\n\nShop: https://stza.co/+whBT-3x\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144500Z
LAST-MODIFIED:20180213T144500Z
TRANSP:OPAQUE
END:VEVENT
* Isotopes @ River Cats
<2018-08-28 Tue 21:05>--<2018-08-29 Wed 00:05>
:PROPERTIES:
:ID:       mkbKCuSRfz0ENo9Xt57f097b@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Isotopes @ River Cats Isotopes @ River Cats

Follow on MiLB First Pitch  https //stza.co/+wjwt-1w

Shop  https //stza.co/+wjwt-19

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Isotopes @ River Cats
END:VALARM
DTSTART:20180829T020500Z
DTEND:20180829T050500Z
UID:mkbKCuSRfz0ENo9Xt57f097b@stanza.co
SUMMARY:Isotopes @ River Cats
DESCRIPTION:Isotopes @ River Cats\n\nFollow on MiLB First Pitch: https://stza.co/+wjwt-1w\n\nShop: https://stza.co/+wjwt-19\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144500Z
LAST-MODIFIED:20180213T144500Z
TRANSP:OPAQUE
END:VEVENT
* Isotopes @ River Cats
<2018-08-29 Wed 21:05>--<2018-08-30 Thu 00:05>
:PROPERTIES:
:ID:       yhRYi3WT5r3LTi4uZIzXWAlW@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Isotopes @ River Cats Isotopes @ River Cats

Follow on MiLB First Pitch  https //stza.co/+wjwu-3U

Shop  https //stza.co/+wjwu-11

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Isotopes @ River Cats
END:VALARM
DTSTART:20180830T020500Z
DTEND:20180830T050500Z
UID:yhRYi3WT5r3LTi4uZIzXWAlW@stanza.co
SUMMARY:Isotopes @ River Cats
DESCRIPTION:Isotopes @ River Cats\n\nFollow on MiLB First Pitch: https://stza.co/+wjwu-3U\n\nShop: https://stza.co/+wjwu-11\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144500Z
LAST-MODIFIED:20180213T144500Z
TRANSP:OPAQUE
END:VEVENT
* Isotopes @ River Cats
<2018-08-30 Thu 21:05>--<2018-08-31 Fri 00:05>
:PROPERTIES:
:ID:       GJvvJAhHm_GQgyKWAg6k6fJ1@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Isotopes @ River Cats Isotopes @ River Cats

Follow on MiLB First Pitch  https //stza.co/+wjwv-33

Shop  https //stza.co/+wjwv-1C

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Isotopes @ River Cats
END:VALARM
DTSTART:20180831T020500Z
DTEND:20180831T050500Z
UID:GJvvJAhHm_GQgyKWAg6k6fJ1@stanza.co
SUMMARY:Isotopes @ River Cats
DESCRIPTION:Isotopes @ River Cats\n\nFollow on MiLB First Pitch: https://stza.co/+wjwv-33\n\nShop: https://stza.co/+wjwv-1C\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144500Z
LAST-MODIFIED:20180213T144500Z
TRANSP:OPAQUE
END:VEVENT
* Isotopes @ Aces
<2018-08-31 Fri 21:05>--<2018-09-01 Sat 00:05>
:PROPERTIES:
:ID:       zItU2bK-r_F37CvxVAvHGyjC@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Isotopes @ Aces Isotopes @ Aces

Follow on MiLB First Pitch  https //stza.co/+wjwk-2K

Shop  https //stza.co/+wjwk-a

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Isotopes @ Aces
END:VALARM
DTSTART:20180901T020500Z
DTEND:20180901T050500Z
UID:zItU2bK-r_F37CvxVAvHGyjC@stanza.co
SUMMARY:Isotopes @ Aces
DESCRIPTION:Isotopes @ Aces\n\nFollow on MiLB First Pitch: https://stza.co/+wjwk-2K\n\nShop: https://stza.co/+wjwk-a\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144500Z
LAST-MODIFIED:20180213T144500Z
TRANSP:OPAQUE
END:VEVENT
* Isotopes @ Aces
<2018-09-01 Sat 21:05>--<2018-09-02 Sun 00:05>
:PROPERTIES:
:ID:       VbDYC2Wi7JpA40oZYS_wNpSC@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Isotopes @ Aces Isotopes @ Aces

Follow on MiLB First Pitch  https //stza.co/+wjwl-24

Shop  https //stza.co/+wjwl-x

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Isotopes @ Aces
END:VALARM
DTSTART:20180902T020500Z
DTEND:20180902T050500Z
UID:VbDYC2Wi7JpA40oZYS_wNpSC@stanza.co
SUMMARY:Isotopes @ Aces
DESCRIPTION:Isotopes @ Aces\n\nFollow on MiLB First Pitch: https://stza.co/+wjwl-24\n\nShop: https://stza.co/+wjwl-x\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144500Z
LAST-MODIFIED:20180213T144500Z
TRANSP:OPAQUE
END:VEVENT
* Isotopes @ Aces
<2018-09-02 Sun 20:05-23:05>
:PROPERTIES:
:ID:       gnXYwS09JkTbecXwuos3VAsV@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Isotopes @ Aces Isotopes @ Aces

Follow on MiLB First Pitch  https //stza.co/+wjwm-1y

Shop  https //stza.co/+wjwm-l

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Isotopes @ Aces
END:VALARM
DTSTART:20180903T010500Z
DTEND:20180903T040500Z
UID:gnXYwS09JkTbecXwuos3VAsV@stanza.co
SUMMARY:Isotopes @ Aces
DESCRIPTION:Isotopes @ Aces\n\nFollow on MiLB First Pitch: https://stza.co/+wjwm-1y\n\nShop: https://stza.co/+wjwm-l\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144500Z
LAST-MODIFIED:20180213T144500Z
TRANSP:OPAQUE
END:VEVENT
* Isotopes @ Aces
<2018-09-03 Mon 15:05-18:05>
:PROPERTIES:
:ID:       _iHQMIFusdZkeJV_glcyqtnA@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Isotopes @ Aces Isotopes @ Aces

Follow on MiLB First Pitch  https //stza.co/+wjwn-Q

Shop  https //stza.co/+wjwn-M

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Isotopes @ Aces
END:VALARM
DTSTART:20180903T200500Z
DTEND:20180903T230500Z
UID:_iHQMIFusdZkeJV_glcyqtnA@stanza.co
SUMMARY:Isotopes @ Aces
DESCRIPTION:Isotopes @ Aces\n\nFollow on MiLB First Pitch: https://stza.co/+wjwn-Q\n\nShop: https://stza.co/+wjwn-M\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144500Z
LAST-MODIFIED:20180213T144500Z
TRANSP:OPAQUE
END:VEVENT
