#+TITLE:       Main Google calendar entries
#+AUTHOR:      Eric S Fraga
#+EMAIL:       e.fraga@ucl.ac.uk
#+DESCRIPTION: converted using the ical2org awk script
#+CATEGORY:    google
#+STARTUP:     hidestars
#+STARTUP:     overview

* COMMENT original iCal preamble

* RiverDogs @ Legends
<2018-04-05 Thu 18:05-21:05>
:PROPERTIES:
:ID:       SLnYMHm3ZFRGWHIC-cLTlqip@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

RiverDogs @ Legends RiverDogs @ Legends

Follow on MiLB First Pitch  https //stza.co/+xAWi-2Q

Shop  https //stza.co/+xAWi-22

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:RiverDogs @ Legends
END:VALARM
DTSTART:20180405T230500Z
DTEND:20180406T020500Z
UID:SLnYMHm3ZFRGWHIC-cLTlqip@stanza.co
SUMMARY:RiverDogs @ Legends
DESCRIPTION:RiverDogs @ Legends\n\nFollow on MiLB First Pitch: https://stza.co/+xAWi-2Q\n\nShop: https://stza.co/+xAWi-22\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144512Z
LAST-MODIFIED:20180213T144512Z
TRANSP:OPAQUE
END:VEVENT
* RiverDogs @ Legends
<2018-04-06 Fri 18:05-21:05>
:PROPERTIES:
:ID:       JFHKgDFhneATe486x8GiLLO7@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

RiverDogs @ Legends RiverDogs @ Legends

Follow on MiLB First Pitch  https //stza.co/+xAWj-2D

Shop  https //stza.co/+xAWj-6

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:RiverDogs @ Legends
END:VALARM
DTSTART:20180406T230500Z
DTEND:20180407T020500Z
UID:JFHKgDFhneATe486x8GiLLO7@stanza.co
SUMMARY:RiverDogs @ Legends
DESCRIPTION:RiverDogs @ Legends\n\nFollow on MiLB First Pitch: https://stza.co/+xAWj-2D\n\nShop: https://stza.co/+xAWj-6\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144512Z
LAST-MODIFIED:20180213T144512Z
TRANSP:OPAQUE
END:VEVENT
* RiverDogs @ Legends
<2018-04-07 Sat 17:35-20:35>
:PROPERTIES:
:ID:       fXN9xrx1Se2K8mk0iBVhvKfu@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

RiverDogs @ Legends RiverDogs @ Legends

Follow on MiLB First Pitch  https //stza.co/+xAWk-P

Shop  https //stza.co/+xAWk-2E

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:RiverDogs @ Legends
END:VALARM
DTSTART:20180407T223500Z
DTEND:20180408T013500Z
UID:fXN9xrx1Se2K8mk0iBVhvKfu@stanza.co
SUMMARY:RiverDogs @ Legends
DESCRIPTION:RiverDogs @ Legends\n\nFollow on MiLB First Pitch: https://stza.co/+xAWk-P\n\nShop: https://stza.co/+xAWk-2E\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144512Z
LAST-MODIFIED:20180213T144512Z
TRANSP:OPAQUE
END:VEVENT
* RiverDogs @ Legends
<2018-04-08 Sun 13:05-16:05>
:PROPERTIES:
:ID:       OxXDLvkLVeqlMi-elQ5DRxsQ@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

RiverDogs @ Legends RiverDogs @ Legends

Follow on MiLB First Pitch  https //stza.co/+xAWl-3G

Shop  https //stza.co/+xAWl-1S

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:RiverDogs @ Legends
END:VALARM
DTSTART:20180408T180500Z
DTEND:20180408T210500Z
UID:OxXDLvkLVeqlMi-elQ5DRxsQ@stanza.co
SUMMARY:RiverDogs @ Legends
DESCRIPTION:RiverDogs @ Legends\n\nFollow on MiLB First Pitch: https://stza.co/+xAWl-3G\n\nShop: https://stza.co/+xAWl-1S\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144512Z
LAST-MODIFIED:20180213T144512Z
TRANSP:OPAQUE
END:VEVENT
* RiverDogs @ Braves
<2018-04-09 Mon 18:00-21:00>
:PROPERTIES:
:ID:       yDpI5TNrkKgp0FnFdTjfsDBM@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

RiverDogs @ Braves RiverDogs @ Braves

Follow on MiLB First Pitch  https //stza.co/+vNCe-3w

Shop  https //stza.co/+vNCe-3X

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:RiverDogs @ Braves
END:VALARM
DTSTART:20180409T230000Z
DTEND:20180410T020000Z
UID:yDpI5TNrkKgp0FnFdTjfsDBM@stanza.co
SUMMARY:RiverDogs @ Braves
DESCRIPTION:RiverDogs @ Braves\n\nFollow on MiLB First Pitch: https://stza.co/+vNCe-3w\n\nShop: https://stza.co/+vNCe-3X\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144512Z
LAST-MODIFIED:20180213T144512Z
TRANSP:OPAQUE
END:VEVENT
* RiverDogs @ Braves
<2018-04-10 Tue 09:30-12:30>
:PROPERTIES:
:ID:       OrpATuOcVDsOh47H-HLFZrHH@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

RiverDogs @ Braves RiverDogs @ Braves

Follow on MiLB First Pitch  https //stza.co/+vNCf-y

Shop  https //stza.co/+vNCf-2m

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:RiverDogs @ Braves
END:VALARM
DTSTART:20180410T143000Z
DTEND:20180410T173000Z
UID:OrpATuOcVDsOh47H-HLFZrHH@stanza.co
SUMMARY:RiverDogs @ Braves
DESCRIPTION:RiverDogs @ Braves\n\nFollow on MiLB First Pitch: https://stza.co/+vNCf-y\n\nShop: https://stza.co/+vNCf-2m\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144512Z
LAST-MODIFIED:20180213T144512Z
TRANSP:OPAQUE
END:VEVENT
* RiverDogs @ Braves
<2018-04-11 Wed 12:00-15:00>
:PROPERTIES:
:ID:       6g0YnwewhbTydDmOHxuj0YQN@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

RiverDogs @ Braves RiverDogs @ Braves

Follow on MiLB First Pitch  https //stza.co/+vNCg-3E

Shop  https //stza.co/+vNCg-2$

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:RiverDogs @ Braves
END:VALARM
DTSTART:20180411T170000Z
DTEND:20180411T200000Z
UID:6g0YnwewhbTydDmOHxuj0YQN@stanza.co
SUMMARY:RiverDogs @ Braves
DESCRIPTION:RiverDogs @ Braves\n\nFollow on MiLB First Pitch: https://stza.co/+vNCg-3E\n\nShop: https://stza.co/+vNCg-2$\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144512Z
LAST-MODIFIED:20180213T144512Z
TRANSP:OPAQUE
END:VEVENT
* RiverDogs vs. Intimidators
<2018-04-12 Thu 18:05-21:05>
:PROPERTIES:
:ID:       wZqPWTskQdJsC0dNgMuLF-ph@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

RiverDogs vs. Intimidators RiverDogs vs. Intimidators

Follow on MiLB First Pitch  https //stza.co/+vNze-2o

Shop  https //stza.co/+vNze-11

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:RiverDogs vs. Intimidators
END:VALARM
DTSTART:20180412T230500Z
DTEND:20180413T020500Z
UID:wZqPWTskQdJsC0dNgMuLF-ph@stanza.co
SUMMARY:RiverDogs vs. Intimidators
DESCRIPTION:RiverDogs vs. Intimidators\n\nFollow on MiLB First Pitch: https://stza.co/+vNze-2o\n\nShop: https://stza.co/+vNze-11\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144512Z
LAST-MODIFIED:20180213T144512Z
TRANSP:OPAQUE
END:VEVENT
* RiverDogs vs. Intimidators
<2018-04-13 Fri 18:05-21:05>
:PROPERTIES:
:ID:       XoGj-4NUgiqF0U1qEbfyrB2z@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

RiverDogs vs. Intimidators RiverDogs vs. Intimidators

Follow on MiLB First Pitch  https //stza.co/+vNzg-3f

Shop  https //stza.co/+vNzg-3Y

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:RiverDogs vs. Intimidators
END:VALARM
DTSTART:20180413T230500Z
DTEND:20180414T020500Z
UID:XoGj-4NUgiqF0U1qEbfyrB2z@stanza.co
SUMMARY:RiverDogs vs. Intimidators
DESCRIPTION:RiverDogs vs. Intimidators\n\nFollow on MiLB First Pitch: https://stza.co/+vNzg-3f\n\nShop: https://stza.co/+vNzg-3Y\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144512Z
LAST-MODIFIED:20180213T144512Z
TRANSP:OPAQUE
END:VEVENT
* RiverDogs vs. Intimidators
<2018-04-14 Sat 17:05-20:05>
:PROPERTIES:
:ID:       hRj-dSdmY7b_DH41qZG7XTyT@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

RiverDogs vs. Intimidators RiverDogs vs. Intimidators

Follow on MiLB First Pitch  https //stza.co/+vNzi-H

Shop  https //stza.co/+vNzi-3h

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:RiverDogs vs. Intimidators
END:VALARM
DTSTART:20180414T220500Z
DTEND:20180415T010500Z
UID:hRj-dSdmY7b_DH41qZG7XTyT@stanza.co
SUMMARY:RiverDogs vs. Intimidators
DESCRIPTION:RiverDogs vs. Intimidators\n\nFollow on MiLB First Pitch: https://stza.co/+vNzi-H\n\nShop: https://stza.co/+vNzi-3h\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144512Z
LAST-MODIFIED:20180213T144512Z
TRANSP:OPAQUE
END:VEVENT
* RiverDogs vs. Intimidators
<2018-04-15 Sun 16:05-19:05>
:PROPERTIES:
:ID:       YhpciYLrg4GBXy4s_a-W_XJY@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

RiverDogs vs. Intimidators RiverDogs vs. Intimidators

Follow on MiLB First Pitch  https //stza.co/+vNzl-2O

Shop  https //stza.co/+vNzl-3G

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:RiverDogs vs. Intimidators
END:VALARM
DTSTART:20180415T210500Z
DTEND:20180416T000500Z
UID:YhpciYLrg4GBXy4s_a-W_XJY@stanza.co
SUMMARY:RiverDogs vs. Intimidators
DESCRIPTION:RiverDogs vs. Intimidators\n\nFollow on MiLB First Pitch: https://stza.co/+vNzl-2O\n\nShop: https://stza.co/+vNzl-3G\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144512Z
LAST-MODIFIED:20180213T144512Z
TRANSP:OPAQUE
END:VEVENT
* RiverDogs vs. Power
<2018-04-16 Mon 18:05-21:05>
:PROPERTIES:
:ID:       gALpGkJkzXFCqPSUqMw8raxp@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

RiverDogs vs. Power RiverDogs vs. Power

Follow on MiLB First Pitch  https //stza.co/+vNzn-3I

Shop  https //stza.co/+vNzn-3J

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:RiverDogs vs. Power
END:VALARM
DTSTART:20180416T230500Z
DTEND:20180417T020500Z
UID:gALpGkJkzXFCqPSUqMw8raxp@stanza.co
SUMMARY:RiverDogs vs. Power
DESCRIPTION:RiverDogs vs. Power\n\nFollow on MiLB First Pitch: https://stza.co/+vNzn-3I\n\nShop: https://stza.co/+vNzn-3J\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144512Z
LAST-MODIFIED:20180213T144512Z
TRANSP:OPAQUE
END:VEVENT
* RiverDogs vs. Power
<2018-04-17 Tue 18:05-21:05>
:PROPERTIES:
:ID:       uxFAJhl4e2Pi0Uy6U2xifN2d@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

RiverDogs vs. Power RiverDogs vs. Power

Follow on MiLB First Pitch  https //stza.co/+vNzo-c

Shop  https //stza.co/+vNzo-3e

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:RiverDogs vs. Power
END:VALARM
DTSTART:20180417T230500Z
DTEND:20180418T020500Z
UID:uxFAJhl4e2Pi0Uy6U2xifN2d@stanza.co
SUMMARY:RiverDogs vs. Power
DESCRIPTION:RiverDogs vs. Power\n\nFollow on MiLB First Pitch: https://stza.co/+vNzo-c\n\nShop: https://stza.co/+vNzo-3e\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144512Z
LAST-MODIFIED:20180213T144512Z
TRANSP:OPAQUE
END:VEVENT
* RiverDogs vs. Power
<2018-04-18 Wed 10:05-13:05>
:PROPERTIES:
:ID:       kVWzV2LpAVGjoGf67rCdyPSn@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

RiverDogs vs. Power RiverDogs vs. Power

Follow on MiLB First Pitch  https //stza.co/+vNzq-3h

Shop  https //stza.co/+vNzq-F

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:RiverDogs vs. Power
END:VALARM
DTSTART:20180418T150500Z
DTEND:20180418T180500Z
UID:kVWzV2LpAVGjoGf67rCdyPSn@stanza.co
SUMMARY:RiverDogs vs. Power
DESCRIPTION:RiverDogs vs. Power\n\nFollow on MiLB First Pitch: https://stza.co/+vNzq-3h\n\nShop: https://stza.co/+vNzq-F\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144512Z
LAST-MODIFIED:20180213T144512Z
TRANSP:OPAQUE
END:VEVENT
* RiverDogs @ Grasshoppers
<2018-04-19 Thu 18:00-21:00>
:PROPERTIES:
:ID:       W5nylAPvp1bOQ39oVX5m__Jp@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

RiverDogs @ Grasshoppers RiverDogs @ Grasshoppers

Follow on MiLB First Pitch  https //stza.co/+wiwF-

Shop  https //stza.co/+wiwF-2j

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:RiverDogs @ Grasshoppers
END:VALARM
DTSTART:20180419T230000Z
DTEND:20180420T020000Z
UID:W5nylAPvp1bOQ39oVX5m__Jp@stanza.co
SUMMARY:RiverDogs @ Grasshoppers
DESCRIPTION:RiverDogs @ Grasshoppers\n\nFollow on MiLB First Pitch: https://stza.co/+wiwF-\n\nShop: https://stza.co/+wiwF-2j\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144512Z
LAST-MODIFIED:20180213T144512Z
TRANSP:OPAQUE
END:VEVENT
* RiverDogs @ Grasshoppers
<2018-04-20 Fri 18:00-21:00>
:PROPERTIES:
:ID:       viTl3mYinlEaBgf9pS-VaNF0@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

RiverDogs @ Grasshoppers RiverDogs @ Grasshoppers

Follow on MiLB First Pitch  https //stza.co/+wiwG-3S

Shop  https //stza.co/+wiwG-29

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:RiverDogs @ Grasshoppers
END:VALARM
DTSTART:20180420T230000Z
DTEND:20180421T020000Z
UID:viTl3mYinlEaBgf9pS-VaNF0@stanza.co
SUMMARY:RiverDogs @ Grasshoppers
DESCRIPTION:RiverDogs @ Grasshoppers\n\nFollow on MiLB First Pitch: https://stza.co/+wiwG-3S\n\nShop: https://stza.co/+wiwG-29\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144512Z
LAST-MODIFIED:20180213T144512Z
TRANSP:OPAQUE
END:VEVENT
* RiverDogs @ Grasshoppers
<2018-04-21 Sat 18:00-21:00>
:PROPERTIES:
:ID:       Tf9EXEvtJ_MYBue-DgGuz0sn@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

RiverDogs @ Grasshoppers RiverDogs @ Grasshoppers

Follow on MiLB First Pitch  https //stza.co/+wiwH-S

Shop  https //stza.co/+wiwH-1l

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:RiverDogs @ Grasshoppers
END:VALARM
DTSTART:20180421T230000Z
DTEND:20180422T020000Z
UID:Tf9EXEvtJ_MYBue-DgGuz0sn@stanza.co
SUMMARY:RiverDogs @ Grasshoppers
DESCRIPTION:RiverDogs @ Grasshoppers\n\nFollow on MiLB First Pitch: https://stza.co/+wiwH-S\n\nShop: https://stza.co/+wiwH-1l\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144512Z
LAST-MODIFIED:20180213T144512Z
TRANSP:OPAQUE
END:VEVENT
* RiverDogs @ Grasshoppers
<2018-04-22 Sun 13:00-16:00>
:PROPERTIES:
:ID:       4QdU8NiFqC1ja-e3FEPbBddX@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

RiverDogs @ Grasshoppers RiverDogs @ Grasshoppers

Follow on MiLB First Pitch  https //stza.co/+wiwI-5

Shop  https //stza.co/+wiwI-1Y

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:RiverDogs @ Grasshoppers
END:VALARM
DTSTART:20180422T180000Z
DTEND:20180422T210000Z
UID:4QdU8NiFqC1ja-e3FEPbBddX@stanza.co
SUMMARY:RiverDogs @ Grasshoppers
DESCRIPTION:RiverDogs @ Grasshoppers\n\nFollow on MiLB First Pitch: https://stza.co/+wiwI-5\n\nShop: https://stza.co/+wiwI-1Y\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144512Z
LAST-MODIFIED:20180213T144512Z
TRANSP:OPAQUE
END:VEVENT
* RiverDogs vs. Fireflies
<2018-04-23 Mon 18:05-21:05>
:PROPERTIES:
:ID:       7svNEyicSYESI88sCB7uKHDe@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

RiverDogs vs. Fireflies RiverDogs vs. Fireflies

Follow on MiLB First Pitch  https //stza.co/+vNzs-2c

Shop  https //stza.co/+vNzs-18

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:RiverDogs vs. Fireflies
END:VALARM
DTSTART:20180423T230500Z
DTEND:20180424T020500Z
UID:7svNEyicSYESI88sCB7uKHDe@stanza.co
SUMMARY:RiverDogs vs. Fireflies
DESCRIPTION:RiverDogs vs. Fireflies\n\nFollow on MiLB First Pitch: https://stza.co/+vNzs-2c\n\nShop: https://stza.co/+vNzs-18\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144512Z
LAST-MODIFIED:20180213T144512Z
TRANSP:OPAQUE
END:VEVENT
* RiverDogs vs. Fireflies
<2018-04-24 Tue 18:05-21:05>
:PROPERTIES:
:ID:       UwAjiUiT-uJgYR9MBvVsi5xt@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

RiverDogs vs. Fireflies RiverDogs vs. Fireflies

Follow on MiLB First Pitch  https //stza.co/+vNzv-2d

Shop  https //stza.co/+vNzv-3d

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:RiverDogs vs. Fireflies
END:VALARM
DTSTART:20180424T230500Z
DTEND:20180425T020500Z
UID:UwAjiUiT-uJgYR9MBvVsi5xt@stanza.co
SUMMARY:RiverDogs vs. Fireflies
DESCRIPTION:RiverDogs vs. Fireflies\n\nFollow on MiLB First Pitch: https://stza.co/+vNzv-2d\n\nShop: https://stza.co/+vNzv-3d\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144512Z
LAST-MODIFIED:20180213T144512Z
TRANSP:OPAQUE
END:VEVENT
* RiverDogs vs. Fireflies
<2018-04-25 Wed 18:05-21:05>
:PROPERTIES:
:ID:       zrk8eS2BDgt5e2u5gl4iaqsq@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

RiverDogs vs. Fireflies RiverDogs vs. Fireflies

Follow on MiLB First Pitch  https //stza.co/+vNzw-1g

Shop  https //stza.co/+vNzw-2J

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:RiverDogs vs. Fireflies
END:VALARM
DTSTART:20180425T230500Z
DTEND:20180426T020500Z
UID:zrk8eS2BDgt5e2u5gl4iaqsq@stanza.co
SUMMARY:RiverDogs vs. Fireflies
DESCRIPTION:RiverDogs vs. Fireflies\n\nFollow on MiLB First Pitch: https://stza.co/+vNzw-1g\n\nShop: https://stza.co/+vNzw-2J\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144512Z
LAST-MODIFIED:20180213T144512Z
TRANSP:OPAQUE
END:VEVENT
* RiverDogs vs. Fireflies
<2018-04-26 Thu 18:05-21:05>
:PROPERTIES:
:ID:       LbNRYEzThHdfeTCkn6XOdPKN@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

RiverDogs vs. Fireflies RiverDogs vs. Fireflies

Follow on MiLB First Pitch  https //stza.co/+vNzy-3p

Shop  https //stza.co/+vNzy-g

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:RiverDogs vs. Fireflies
END:VALARM
DTSTART:20180426T230500Z
DTEND:20180427T020500Z
UID:LbNRYEzThHdfeTCkn6XOdPKN@stanza.co
SUMMARY:RiverDogs vs. Fireflies
DESCRIPTION:RiverDogs vs. Fireflies\n\nFollow on MiLB First Pitch: https://stza.co/+vNzy-3p\n\nShop: https://stza.co/+vNzy-g\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144512Z
LAST-MODIFIED:20180213T144512Z
TRANSP:OPAQUE
END:VEVENT
* RiverDogs @ Drive
<2018-04-27 Fri 18:05-21:05>
:PROPERTIES:
:ID:       jo_V89InIG4e8NbC0R9_Lut0@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

RiverDogs @ Drive RiverDogs @ Drive

Follow on MiLB First Pitch  https //stza.co/+xEZx-2

Shop  https //stza.co/+xEZx-3

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:RiverDogs @ Drive
END:VALARM
DTSTART:20180427T230500Z
DTEND:20180428T020500Z
UID:jo_V89InIG4e8NbC0R9_Lut0@stanza.co
SUMMARY:RiverDogs @ Drive
DESCRIPTION:RiverDogs @ Drive\n\nFollow on MiLB First Pitch: https://stza.co/+xEZx-2\n\nShop: https://stza.co/+xEZx-3\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144512Z
LAST-MODIFIED:20180213T144512Z
TRANSP:OPAQUE
END:VEVENT
* RiverDogs @ Drive
<2018-04-28 Sat 18:05-21:05>
:PROPERTIES:
:ID:       mRfFpDk74bOyN1hDnVur4cN_@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

RiverDogs @ Drive RiverDogs @ Drive

Follow on MiLB First Pitch  https //stza.co/+xEZy-I

Shop  https //stza.co/+xEZy-1u

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:RiverDogs @ Drive
END:VALARM
DTSTART:20180428T230500Z
DTEND:20180429T020500Z
UID:mRfFpDk74bOyN1hDnVur4cN_@stanza.co
SUMMARY:RiverDogs @ Drive
DESCRIPTION:RiverDogs @ Drive\n\nFollow on MiLB First Pitch: https://stza.co/+xEZy-I\n\nShop: https://stza.co/+xEZy-1u\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144512Z
LAST-MODIFIED:20180213T144512Z
TRANSP:OPAQUE
END:VEVENT
* RiverDogs @ Drive
<2018-04-29 Sun 15:05-18:05>
:PROPERTIES:
:ID:       P_etThpwbhfkLSCjX-jQeukE@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

RiverDogs @ Drive RiverDogs @ Drive

Follow on MiLB First Pitch  https //stza.co/+xEZz-o

Shop  https //stza.co/+xEZz-2t

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:RiverDogs @ Drive
END:VALARM
DTSTART:20180429T200500Z
DTEND:20180429T230500Z
UID:P_etThpwbhfkLSCjX-jQeukE@stanza.co
SUMMARY:RiverDogs @ Drive
DESCRIPTION:RiverDogs @ Drive\n\nFollow on MiLB First Pitch: https://stza.co/+xEZz-o\n\nShop: https://stza.co/+xEZz-2t\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144512Z
LAST-MODIFIED:20180213T144512Z
TRANSP:OPAQUE
END:VEVENT
* RiverDogs vs. Tourists
<2018-05-01 Tue 18:05-21:05>
:PROPERTIES:
:ID:       uBFVnEhRjb4eLnroyPkjv1UW@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

RiverDogs vs. Tourists RiverDogs vs. Tourists

Follow on MiLB First Pitch  https //stza.co/+vNzB-3s

Shop  https //stza.co/+vNzB-1c

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:RiverDogs vs. Tourists
END:VALARM
DTSTART:20180501T230500Z
DTEND:20180502T020500Z
UID:uBFVnEhRjb4eLnroyPkjv1UW@stanza.co
SUMMARY:RiverDogs vs. Tourists
DESCRIPTION:RiverDogs vs. Tourists\n\nFollow on MiLB First Pitch: https://stza.co/+vNzB-3s\n\nShop: https://stza.co/+vNzB-1c\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144512Z
LAST-MODIFIED:20180213T144512Z
TRANSP:OPAQUE
END:VEVENT
* RiverDogs vs. Tourists
<2018-05-02 Wed 18:05-21:05>
:PROPERTIES:
:ID:       a2b4MvVhKn5n8AKglpPMrJko@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

RiverDogs vs. Tourists RiverDogs vs. Tourists

Follow on MiLB First Pitch  https //stza.co/+vNzC-3h

Shop  https //stza.co/+vNzC-F

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:RiverDogs vs. Tourists
END:VALARM
DTSTART:20180502T230500Z
DTEND:20180503T020500Z
UID:a2b4MvVhKn5n8AKglpPMrJko@stanza.co
SUMMARY:RiverDogs vs. Tourists
DESCRIPTION:RiverDogs vs. Tourists\n\nFollow on MiLB First Pitch: https://stza.co/+vNzC-3h\n\nShop: https://stza.co/+vNzC-F\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144512Z
LAST-MODIFIED:20180213T144512Z
TRANSP:OPAQUE
END:VEVENT
* RiverDogs vs. Tourists
<2018-05-03 Thu 18:05-21:05>
:PROPERTIES:
:ID:       p_eoO1hvURok9wosDfbueWEW@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

RiverDogs vs. Tourists RiverDogs vs. Tourists

Follow on MiLB First Pitch  https //stza.co/+vNzF-a

Shop  https //stza.co/+vNzF-8

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:RiverDogs vs. Tourists
END:VALARM
DTSTART:20180503T230500Z
DTEND:20180504T020500Z
UID:p_eoO1hvURok9wosDfbueWEW@stanza.co
SUMMARY:RiverDogs vs. Tourists
DESCRIPTION:RiverDogs vs. Tourists\n\nFollow on MiLB First Pitch: https://stza.co/+vNzF-a\n\nShop: https://stza.co/+vNzF-8\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144512Z
LAST-MODIFIED:20180213T144512Z
TRANSP:OPAQUE
END:VEVENT
* RiverDogs vs. Legends
<2018-05-04 Fri 18:05-21:05>
:PROPERTIES:
:ID:       GuHelQ_rxDqmjTeZXW28fx3q@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

RiverDogs vs. Legends RiverDogs vs. Legends

Follow on MiLB First Pitch  https //stza.co/+vNzG-1p

Shop  https //stza.co/+vNzG-3j

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:RiverDogs vs. Legends
END:VALARM
DTSTART:20180504T230500Z
DTEND:20180505T020500Z
UID:GuHelQ_rxDqmjTeZXW28fx3q@stanza.co
SUMMARY:RiverDogs vs. Legends
DESCRIPTION:RiverDogs vs. Legends\n\nFollow on MiLB First Pitch: https://stza.co/+vNzG-1p\n\nShop: https://stza.co/+vNzG-3j\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144512Z
LAST-MODIFIED:20180213T144512Z
TRANSP:OPAQUE
END:VEVENT
* RiverDogs vs. Legends
<2018-05-05 Sat 17:05-20:05>
:PROPERTIES:
:ID:       tTEOrzPV74XayxDJWAEpvmhb@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

RiverDogs vs. Legends RiverDogs vs. Legends

Follow on MiLB First Pitch  https //stza.co/+vNzI-d

Shop  https //stza.co/+vNzI-3s

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:RiverDogs vs. Legends
END:VALARM
DTSTART:20180505T220500Z
DTEND:20180506T010500Z
UID:tTEOrzPV74XayxDJWAEpvmhb@stanza.co
SUMMARY:RiverDogs vs. Legends
DESCRIPTION:RiverDogs vs. Legends\n\nFollow on MiLB First Pitch: https://stza.co/+vNzI-d\n\nShop: https://stza.co/+vNzI-3s\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144512Z
LAST-MODIFIED:20180213T144512Z
TRANSP:OPAQUE
END:VEVENT
* RiverDogs vs. Legends
<2018-05-06 Sun 16:05-19:05>
:PROPERTIES:
:ID:       nafacsDyoySv3U-c3_ZbXeVe@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

RiverDogs vs. Legends RiverDogs vs. Legends

Follow on MiLB First Pitch  https //stza.co/+vNzK-19

Shop  https //stza.co/+vNzK-1V

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:RiverDogs vs. Legends
END:VALARM
DTSTART:20180506T210500Z
DTEND:20180507T000500Z
UID:nafacsDyoySv3U-c3_ZbXeVe@stanza.co
SUMMARY:RiverDogs vs. Legends
DESCRIPTION:RiverDogs vs. Legends\n\nFollow on MiLB First Pitch: https://stza.co/+vNzK-19\n\nShop: https://stza.co/+vNzK-1V\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144512Z
LAST-MODIFIED:20180213T144512Z
TRANSP:OPAQUE
END:VEVENT
* RiverDogs vs. Legends
<2018-05-07 Mon 18:05-21:05>
:PROPERTIES:
:ID:       Y5dKcyYET5gBV3kbCfgUmRCC@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

RiverDogs vs. Legends RiverDogs vs. Legends

Follow on MiLB First Pitch  https //stza.co/+vNzN-1N

Shop  https //stza.co/+vNzN-3N

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:RiverDogs vs. Legends
END:VALARM
DTSTART:20180507T230500Z
DTEND:20180508T020500Z
UID:Y5dKcyYET5gBV3kbCfgUmRCC@stanza.co
SUMMARY:RiverDogs vs. Legends
DESCRIPTION:RiverDogs vs. Legends\n\nFollow on MiLB First Pitch: https://stza.co/+vNzN-1N\n\nShop: https://stza.co/+vNzN-3N\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144512Z
LAST-MODIFIED:20180213T144512Z
TRANSP:OPAQUE
END:VEVENT
* RiverDogs @ BlueClaws
<2018-05-09 Wed 17:35-20:35>
:PROPERTIES:
:ID:       Rg4pXw2g_DV74wi2yMa257xU@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

RiverDogs @ BlueClaws RiverDogs @ BlueClaws

Follow on MiLB First Pitch  https //stza.co/+vNC4-5

Shop  https //stza.co/+vNC4-3L

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:RiverDogs @ BlueClaws
END:VALARM
DTSTART:20180509T223500Z
DTEND:20180510T013500Z
UID:Rg4pXw2g_DV74wi2yMa257xU@stanza.co
SUMMARY:RiverDogs @ BlueClaws
DESCRIPTION:RiverDogs @ BlueClaws\n\nFollow on MiLB First Pitch: https://stza.co/+vNC4-5\n\nShop: https://stza.co/+vNC4-3L\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144512Z
LAST-MODIFIED:20180213T144512Z
TRANSP:OPAQUE
END:VEVENT
* RiverDogs @ BlueClaws
<2018-05-10 Thu 17:35-20:35>
:PROPERTIES:
:ID:       MjuHtcAMftzEXHkmP0xP_s8B@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

RiverDogs @ BlueClaws RiverDogs @ BlueClaws

Follow on MiLB First Pitch  https //stza.co/+vNC5-4

Shop  https //stza.co/+vNC5-3P

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:RiverDogs @ BlueClaws
END:VALARM
DTSTART:20180510T223500Z
DTEND:20180511T013500Z
UID:MjuHtcAMftzEXHkmP0xP_s8B@stanza.co
SUMMARY:RiverDogs @ BlueClaws
DESCRIPTION:RiverDogs @ BlueClaws\n\nFollow on MiLB First Pitch: https://stza.co/+vNC5-4\n\nShop: https://stza.co/+vNC5-3P\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144512Z
LAST-MODIFIED:20180213T144512Z
TRANSP:OPAQUE
END:VEVENT
* RiverDogs @ BlueClaws
<2018-05-11 Fri 18:05-21:05>
:PROPERTIES:
:ID:       672eeCDoRUGVRd5xfbZsVH4L@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

RiverDogs @ BlueClaws RiverDogs @ BlueClaws

Follow on MiLB First Pitch  https //stza.co/+vNC6-2K

Shop  https //stza.co/+vNC6-27

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:RiverDogs @ BlueClaws
END:VALARM
DTSTART:20180511T230500Z
DTEND:20180512T020500Z
UID:672eeCDoRUGVRd5xfbZsVH4L@stanza.co
SUMMARY:RiverDogs @ BlueClaws
DESCRIPTION:RiverDogs @ BlueClaws\n\nFollow on MiLB First Pitch: https://stza.co/+vNC6-2K\n\nShop: https://stza.co/+vNC6-27\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144512Z
LAST-MODIFIED:20180213T144512Z
TRANSP:OPAQUE
END:VEVENT
* RiverDogs @ Suns
<2018-05-12 Sat 17:05-20:05>
:PROPERTIES:
:ID:       ukJe4fFdd185xyr0rnnbkMk6@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

RiverDogs @ Suns RiverDogs @ Suns

Follow on MiLB First Pitch  https //stza.co/+xEZH-Y

Shop  https //stza.co/+xEZH-v

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:RiverDogs @ Suns
END:VALARM
DTSTART:20180512T220500Z
DTEND:20180513T010500Z
UID:ukJe4fFdd185xyr0rnnbkMk6@stanza.co
SUMMARY:RiverDogs @ Suns
DESCRIPTION:RiverDogs @ Suns\n\nFollow on MiLB First Pitch: https://stza.co/+xEZH-Y\n\nShop: https://stza.co/+xEZH-v\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144512Z
LAST-MODIFIED:20180213T144512Z
TRANSP:OPAQUE
END:VEVENT
* RiverDogs @ Suns
<2018-05-13 Sun 13:05-16:05>
:PROPERTIES:
:ID:       mbknKowpVC14DW_3Pw0xTQcm@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

RiverDogs @ Suns RiverDogs @ Suns

Follow on MiLB First Pitch  https //stza.co/+xEZI-6

Shop  https //stza.co/+xEZI-2d

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:RiverDogs @ Suns
END:VALARM
DTSTART:20180513T180500Z
DTEND:20180513T210500Z
UID:mbknKowpVC14DW_3Pw0xTQcm@stanza.co
SUMMARY:RiverDogs @ Suns
DESCRIPTION:RiverDogs @ Suns\n\nFollow on MiLB First Pitch: https://stza.co/+xEZI-6\n\nShop: https://stza.co/+xEZI-2d\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144512Z
LAST-MODIFIED:20180213T144512Z
TRANSP:OPAQUE
END:VEVENT
* RiverDogs @ Suns
<2018-05-14 Mon 18:05-21:05>
:PROPERTIES:
:ID:       16Qk-ErmLxRr8PUjxPrYOzxP@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

RiverDogs @ Suns RiverDogs @ Suns

Follow on MiLB First Pitch  https //stza.co/+xEZJ-3Z

Shop  https //stza.co/+xEZJ-3n

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:RiverDogs @ Suns
END:VALARM
DTSTART:20180514T230500Z
DTEND:20180515T020500Z
UID:16Qk-ErmLxRr8PUjxPrYOzxP@stanza.co
SUMMARY:RiverDogs @ Suns
DESCRIPTION:RiverDogs @ Suns\n\nFollow on MiLB First Pitch: https://stza.co/+xEZJ-3Z\n\nShop: https://stza.co/+xEZJ-3n\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144512Z
LAST-MODIFIED:20180213T144512Z
TRANSP:OPAQUE
END:VEVENT
* RiverDogs @ Suns
<2018-05-15 Tue 09:35-12:35>
:PROPERTIES:
:ID:       IuZ8wc6yQ28Q8kFrYtdgT6vf@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

RiverDogs @ Suns RiverDogs @ Suns

Follow on MiLB First Pitch  https //stza.co/+xEZK-d

Shop  https //stza.co/+xEZK-3j

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:RiverDogs @ Suns
END:VALARM
DTSTART:20180515T143500Z
DTEND:20180515T173500Z
UID:IuZ8wc6yQ28Q8kFrYtdgT6vf@stanza.co
SUMMARY:RiverDogs @ Suns
DESCRIPTION:RiverDogs @ Suns\n\nFollow on MiLB First Pitch: https://stza.co/+xEZK-d\n\nShop: https://stza.co/+xEZK-3j\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144512Z
LAST-MODIFIED:20180213T144512Z
TRANSP:OPAQUE
END:VEVENT
* RiverDogs vs. Fireflies
<2018-05-17 Thu 18:05-21:05>
:PROPERTIES:
:ID:       ahMUD8d9NIWrcvkQIHknW6Uv@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

RiverDogs vs. Fireflies RiverDogs vs. Fireflies

Follow on MiLB First Pitch  https //stza.co/+vNzO-3H

Shop  https //stza.co/+vNzO-2Y

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:RiverDogs vs. Fireflies
END:VALARM
DTSTART:20180517T230500Z
DTEND:20180518T020500Z
UID:ahMUD8d9NIWrcvkQIHknW6Uv@stanza.co
SUMMARY:RiverDogs vs. Fireflies
DESCRIPTION:RiverDogs vs. Fireflies\n\nFollow on MiLB First Pitch: https://stza.co/+vNzO-3H\n\nShop: https://stza.co/+vNzO-2Y\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144512Z
LAST-MODIFIED:20180213T144512Z
TRANSP:OPAQUE
END:VEVENT
* RiverDogs vs. Fireflies
<2018-05-18 Fri 18:05-21:05>
:PROPERTIES:
:ID:       2Gaa-kyew5COFcIDVe55jmH2@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

RiverDogs vs. Fireflies RiverDogs vs. Fireflies

Follow on MiLB First Pitch  https //stza.co/+vNzQ-3F

Shop  https //stza.co/+vNzQ-1p

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:RiverDogs vs. Fireflies
END:VALARM
DTSTART:20180518T230500Z
DTEND:20180519T020500Z
UID:2Gaa-kyew5COFcIDVe55jmH2@stanza.co
SUMMARY:RiverDogs vs. Fireflies
DESCRIPTION:RiverDogs vs. Fireflies\n\nFollow on MiLB First Pitch: https://stza.co/+vNzQ-3F\n\nShop: https://stza.co/+vNzQ-1p\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144512Z
LAST-MODIFIED:20180213T144512Z
TRANSP:OPAQUE
END:VEVENT
* RiverDogs vs. Fireflies
<2018-05-19 Sat 17:05-20:05>
:PROPERTIES:
:ID:       mFFsA98O3MA75uvqMxy_FlJ4@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

RiverDogs vs. Fireflies RiverDogs vs. Fireflies

Follow on MiLB First Pitch  https //stza.co/+vNzS-17

Shop  https //stza.co/+vNzS-2w

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:RiverDogs vs. Fireflies
END:VALARM
DTSTART:20180519T220500Z
DTEND:20180520T010500Z
UID:mFFsA98O3MA75uvqMxy_FlJ4@stanza.co
SUMMARY:RiverDogs vs. Fireflies
DESCRIPTION:RiverDogs vs. Fireflies\n\nFollow on MiLB First Pitch: https://stza.co/+vNzS-17\n\nShop: https://stza.co/+vNzS-2w\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144512Z
LAST-MODIFIED:20180213T144512Z
TRANSP:OPAQUE
END:VEVENT
* RiverDogs vs. Fireflies
<2018-05-20 Sun 16:05-19:05>
:PROPERTIES:
:ID:       hE2ADM-9OKFhfgqX8TH22enY@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

RiverDogs vs. Fireflies RiverDogs vs. Fireflies

Follow on MiLB First Pitch  https //stza.co/+vNzV-2O

Shop  https //stza.co/+vNzV-D

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:RiverDogs vs. Fireflies
END:VALARM
DTSTART:20180520T210500Z
DTEND:20180521T000500Z
UID:hE2ADM-9OKFhfgqX8TH22enY@stanza.co
SUMMARY:RiverDogs vs. Fireflies
DESCRIPTION:RiverDogs vs. Fireflies\n\nFollow on MiLB First Pitch: https://stza.co/+vNzV-2O\n\nShop: https://stza.co/+vNzV-D\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144512Z
LAST-MODIFIED:20180213T144512Z
TRANSP:OPAQUE
END:VEVENT
* RiverDogs @ GreenJackets
<2018-05-21 Mon 18:05-21:05>
:PROPERTIES:
:ID:       NgL4_aEdFU2sCjJJE5tekY_2@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

RiverDogs @ GreenJackets RiverDogs @ GreenJackets

Follow on MiLB First Pitch  https //stza.co/+xBLm-1q

Shop  https //stza.co/+xBLm-1y

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:RiverDogs @ GreenJackets
END:VALARM
DTSTART:20180521T230500Z
DTEND:20180522T020500Z
UID:NgL4_aEdFU2sCjJJE5tekY_2@stanza.co
SUMMARY:RiverDogs @ GreenJackets
DESCRIPTION:RiverDogs @ GreenJackets\n\nFollow on MiLB First Pitch: https://stza.co/+xBLm-1q\n\nShop: https://stza.co/+xBLm-1y\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144512Z
LAST-MODIFIED:20180213T144512Z
TRANSP:OPAQUE
END:VEVENT
* RiverDogs @ GreenJackets
<2018-05-22 Tue 18:05-21:05>
:PROPERTIES:
:ID:       j1HMNniHxWX9wVeSsgXzG_eZ@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

RiverDogs @ GreenJackets RiverDogs @ GreenJackets

Follow on MiLB First Pitch  https //stza.co/+xBLn-1w

Shop  https //stza.co/+xBLn-1k

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:RiverDogs @ GreenJackets
END:VALARM
DTSTART:20180522T230500Z
DTEND:20180523T020500Z
UID:j1HMNniHxWX9wVeSsgXzG_eZ@stanza.co
SUMMARY:RiverDogs @ GreenJackets
DESCRIPTION:RiverDogs @ GreenJackets\n\nFollow on MiLB First Pitch: https://stza.co/+xBLn-1w\n\nShop: https://stza.co/+xBLn-1k\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144512Z
LAST-MODIFIED:20180213T144512Z
TRANSP:OPAQUE
END:VEVENT
* RiverDogs @ GreenJackets
<2018-05-23 Wed 18:05-21:05>
:PROPERTIES:
:ID:       IBjJe5tYfgdGwSlLoow9QsZV@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

RiverDogs @ GreenJackets RiverDogs @ GreenJackets

Follow on MiLB First Pitch  https //stza.co/+xBLo-2a

Shop  https //stza.co/+xBLo-Z

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:RiverDogs @ GreenJackets
END:VALARM
DTSTART:20180523T230500Z
DTEND:20180524T020500Z
UID:IBjJe5tYfgdGwSlLoow9QsZV@stanza.co
SUMMARY:RiverDogs @ GreenJackets
DESCRIPTION:RiverDogs @ GreenJackets\n\nFollow on MiLB First Pitch: https://stza.co/+xBLo-2a\n\nShop: https://stza.co/+xBLo-Z\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144512Z
LAST-MODIFIED:20180213T144512Z
TRANSP:OPAQUE
END:VEVENT
* RiverDogs @ GreenJackets
<2018-05-24 Thu 18:05-21:05>
:PROPERTIES:
:ID:       taokGIObpp0l62NBJQ-peFOU@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

RiverDogs @ GreenJackets RiverDogs @ GreenJackets

Follow on MiLB First Pitch  https //stza.co/+xBLp-M

Shop  https //stza.co/+xBLp-3G

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:RiverDogs @ GreenJackets
END:VALARM
DTSTART:20180524T230500Z
DTEND:20180525T020500Z
UID:taokGIObpp0l62NBJQ-peFOU@stanza.co
SUMMARY:RiverDogs @ GreenJackets
DESCRIPTION:RiverDogs @ GreenJackets\n\nFollow on MiLB First Pitch: https://stza.co/+xBLp-M\n\nShop: https://stza.co/+xBLp-3G\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144512Z
LAST-MODIFIED:20180213T144512Z
TRANSP:OPAQUE
END:VEVENT
* RiverDogs @ Crawdads
<2018-05-25 Fri 18:00-21:00>
:PROPERTIES:
:ID:       Yd1WhHVstaX-rZiMxZ8mlRKf@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

RiverDogs @ Crawdads RiverDogs @ Crawdads

Follow on MiLB First Pitch  https //stza.co/+w0O7-2K

Shop  https //stza.co/+w0O7-3K

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:RiverDogs @ Crawdads
END:VALARM
DTSTART:20180525T230000Z
DTEND:20180526T020000Z
UID:Yd1WhHVstaX-rZiMxZ8mlRKf@stanza.co
SUMMARY:RiverDogs @ Crawdads
DESCRIPTION:RiverDogs @ Crawdads\n\nFollow on MiLB First Pitch: https://stza.co/+w0O7-2K\n\nShop: https://stza.co/+w0O7-3K\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144512Z
LAST-MODIFIED:20180213T144512Z
TRANSP:OPAQUE
END:VEVENT
* RiverDogs @ Crawdads
<2018-05-26 Sat 17:00-20:00>
:PROPERTIES:
:ID:       IKEXN57Nbg8HMKQWap_JF-dg@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

RiverDogs @ Crawdads RiverDogs @ Crawdads

Follow on MiLB First Pitch  https //stza.co/+w0O8-2u

Shop  https //stza.co/+w0O8-3D

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:RiverDogs @ Crawdads
END:VALARM
DTSTART:20180526T220000Z
DTEND:20180527T010000Z
UID:IKEXN57Nbg8HMKQWap_JF-dg@stanza.co
SUMMARY:RiverDogs @ Crawdads
DESCRIPTION:RiverDogs @ Crawdads\n\nFollow on MiLB First Pitch: https://stza.co/+w0O8-2u\n\nShop: https://stza.co/+w0O8-3D\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144512Z
LAST-MODIFIED:20180213T144512Z
TRANSP:OPAQUE
END:VEVENT
* RiverDogs @ Crawdads
<2018-05-27 Sun 14:00-17:00>
:PROPERTIES:
:ID:       X_O-iysuxH7-fffm6SL1Gs8n@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

RiverDogs @ Crawdads RiverDogs @ Crawdads

Follow on MiLB First Pitch  https //stza.co/+w0O9-1D

Shop  https //stza.co/+w0O9-3T

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:RiverDogs @ Crawdads
END:VALARM
DTSTART:20180527T190000Z
DTEND:20180527T220000Z
UID:X_O-iysuxH7-fffm6SL1Gs8n@stanza.co
SUMMARY:RiverDogs @ Crawdads
DESCRIPTION:RiverDogs @ Crawdads\n\nFollow on MiLB First Pitch: https://stza.co/+w0O9-1D\n\nShop: https://stza.co/+w0O9-3T\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144512Z
LAST-MODIFIED:20180213T144512Z
TRANSP:OPAQUE
END:VEVENT
* RiverDogs @ Crawdads
<2018-05-28 Mon 12:00-15:00>
:PROPERTIES:
:ID:       Uv8ABVK7FlqvPt9wdmvWa4n-@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

RiverDogs @ Crawdads RiverDogs @ Crawdads

Follow on MiLB First Pitch  https //stza.co/+w0Oa-2V

Shop  https //stza.co/+w0Oa-3o

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:RiverDogs @ Crawdads
END:VALARM
DTSTART:20180528T170000Z
DTEND:20180528T200000Z
UID:Uv8ABVK7FlqvPt9wdmvWa4n-@stanza.co
SUMMARY:RiverDogs @ Crawdads
DESCRIPTION:RiverDogs @ Crawdads\n\nFollow on MiLB First Pitch: https://stza.co/+w0Oa-2V\n\nShop: https://stza.co/+w0Oa-3o\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144512Z
LAST-MODIFIED:20180213T144512Z
TRANSP:OPAQUE
END:VEVENT
* RiverDogs vs. Fireflies
<2018-05-29 Tue 18:05-21:05>
:PROPERTIES:
:ID:       W0Su9SAE1d3I6Bpdxw0-ldKu@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

RiverDogs vs. Fireflies RiverDogs vs. Fireflies

Follow on MiLB First Pitch  https //stza.co/+vNzX-2n

Shop  https //stza.co/+vNzX-3X

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:RiverDogs vs. Fireflies
END:VALARM
DTSTART:20180529T230500Z
DTEND:20180530T020500Z
UID:W0Su9SAE1d3I6Bpdxw0-ldKu@stanza.co
SUMMARY:RiverDogs vs. Fireflies
DESCRIPTION:RiverDogs vs. Fireflies\n\nFollow on MiLB First Pitch: https://stza.co/+vNzX-2n\n\nShop: https://stza.co/+vNzX-3X\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144512Z
LAST-MODIFIED:20180213T144512Z
TRANSP:OPAQUE
END:VEVENT
* RiverDogs vs. Fireflies
<2018-05-30 Wed 10:05-13:05>
:PROPERTIES:
:ID:       y8NnlCeKe94phYOj3CuXafS1@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

RiverDogs vs. Fireflies RiverDogs vs. Fireflies

Follow on MiLB First Pitch  https //stza.co/+vNzZ-39

Shop  https //stza.co/+vNzZ-25

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:RiverDogs vs. Fireflies
END:VALARM
DTSTART:20180530T150500Z
DTEND:20180530T180500Z
UID:y8NnlCeKe94phYOj3CuXafS1@stanza.co
SUMMARY:RiverDogs vs. Fireflies
DESCRIPTION:RiverDogs vs. Fireflies\n\nFollow on MiLB First Pitch: https://stza.co/+vNzZ-39\n\nShop: https://stza.co/+vNzZ-25\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144512Z
LAST-MODIFIED:20180213T144512Z
TRANSP:OPAQUE
END:VEVENT
* RiverDogs vs. Fireflies
<2018-05-31 Thu 18:05-21:05>
:PROPERTIES:
:ID:       siQ1DFWgpKq4_J9nsgjZuSN5@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

RiverDogs vs. Fireflies RiverDogs vs. Fireflies

Follow on MiLB First Pitch  https //stza.co/+vNz$-2w

Shop  https //stza.co/+vNz$-13

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:RiverDogs vs. Fireflies
END:VALARM
DTSTART:20180531T230500Z
DTEND:20180601T020500Z
UID:siQ1DFWgpKq4_J9nsgjZuSN5@stanza.co
SUMMARY:RiverDogs vs. Fireflies
DESCRIPTION:RiverDogs vs. Fireflies\n\nFollow on MiLB First Pitch: https://stza.co/+vNz$-2w\n\nShop: https://stza.co/+vNz$-13\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144512Z
LAST-MODIFIED:20180213T144512Z
TRANSP:OPAQUE
END:VEVENT
* RiverDogs vs. Shorebirds
<2018-06-01 Fri 18:05-21:05>
:PROPERTIES:
:ID:       di9XVNJTMWWgQOqHJhEfbG3a@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

RiverDogs vs. Shorebirds RiverDogs vs. Shorebirds

Follow on MiLB First Pitch  https //stza.co/+vNA0-3k

Shop  https //stza.co/+vNA0-3l

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:RiverDogs vs. Shorebirds
END:VALARM
DTSTART:20180601T230500Z
DTEND:20180602T020500Z
UID:di9XVNJTMWWgQOqHJhEfbG3a@stanza.co
SUMMARY:RiverDogs vs. Shorebirds
DESCRIPTION:RiverDogs vs. Shorebirds\n\nFollow on MiLB First Pitch: https://stza.co/+vNA0-3k\n\nShop: https://stza.co/+vNA0-3l\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144512Z
LAST-MODIFIED:20180213T144512Z
TRANSP:OPAQUE
END:VEVENT
* RiverDogs vs. Shorebirds
<2018-06-02 Sat 17:05-20:05>
:PROPERTIES:
:ID:       D4JhHmRUCGcdxOfiM0CBXOtV@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

RiverDogs vs. Shorebirds RiverDogs vs. Shorebirds

Follow on MiLB First Pitch  https //stza.co/+vNA3-2Q

Shop  https //stza.co/+vNA3-2q

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:RiverDogs vs. Shorebirds
END:VALARM
DTSTART:20180602T220500Z
DTEND:20180603T010500Z
UID:D4JhHmRUCGcdxOfiM0CBXOtV@stanza.co
SUMMARY:RiverDogs vs. Shorebirds
DESCRIPTION:RiverDogs vs. Shorebirds\n\nFollow on MiLB First Pitch: https://stza.co/+vNA3-2Q\n\nShop: https://stza.co/+vNA3-2q\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144512Z
LAST-MODIFIED:20180213T144512Z
TRANSP:OPAQUE
END:VEVENT
* RiverDogs vs. Shorebirds
<2018-06-03 Sun 16:05-19:05>
:PROPERTIES:
:ID:       RDsifKkUr5XftD-_Sdz81eE4@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

RiverDogs vs. Shorebirds RiverDogs vs. Shorebirds

Follow on MiLB First Pitch  https //stza.co/+vNA4-2u

Shop  https //stza.co/+vNA4-2v

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:RiverDogs vs. Shorebirds
END:VALARM
DTSTART:20180603T210500Z
DTEND:20180604T000500Z
UID:RDsifKkUr5XftD-_Sdz81eE4@stanza.co
SUMMARY:RiverDogs vs. Shorebirds
DESCRIPTION:RiverDogs vs. Shorebirds\n\nFollow on MiLB First Pitch: https://stza.co/+vNA4-2u\n\nShop: https://stza.co/+vNA4-2v\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144512Z
LAST-MODIFIED:20180213T144512Z
TRANSP:OPAQUE
END:VEVENT
* RiverDogs @ Fireflies
<2018-06-05 Tue 18:05-21:05>
:PROPERTIES:
:ID:       qGjaBm37AS_d0C9ktVcL42aU@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

RiverDogs @ Fireflies RiverDogs @ Fireflies

Follow on MiLB First Pitch  https //stza.co/+xBLO-S

Shop  https //stza.co/+xBLO-2r

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:RiverDogs @ Fireflies
END:VALARM
DTSTART:20180605T230500Z
DTEND:20180606T020500Z
UID:qGjaBm37AS_d0C9ktVcL42aU@stanza.co
SUMMARY:RiverDogs @ Fireflies
DESCRIPTION:RiverDogs @ Fireflies\n\nFollow on MiLB First Pitch: https://stza.co/+xBLO-S\n\nShop: https://stza.co/+xBLO-2r\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144512Z
LAST-MODIFIED:20180213T144512Z
TRANSP:OPAQUE
END:VEVENT
* RiverDogs @ Fireflies
<2018-06-06 Wed 18:05-21:05>
:PROPERTIES:
:ID:       Ry9n6sluin-eAOgOLTWW2biO@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

RiverDogs @ Fireflies RiverDogs @ Fireflies

Follow on MiLB First Pitch  https //stza.co/+xBLR-2z

Shop  https //stza.co/+xBLR-15

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:RiverDogs @ Fireflies
END:VALARM
DTSTART:20180606T230500Z
DTEND:20180607T020500Z
UID:Ry9n6sluin-eAOgOLTWW2biO@stanza.co
SUMMARY:RiverDogs @ Fireflies
DESCRIPTION:RiverDogs @ Fireflies\n\nFollow on MiLB First Pitch: https://stza.co/+xBLR-2z\n\nShop: https://stza.co/+xBLR-15\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144512Z
LAST-MODIFIED:20180213T144512Z
TRANSP:OPAQUE
END:VEVENT
* RiverDogs @ Fireflies
<2018-06-07 Thu 18:05-21:05>
:PROPERTIES:
:ID:       TFVOsnUmhssuan5KRdDv45jx@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

RiverDogs @ Fireflies RiverDogs @ Fireflies

Follow on MiLB First Pitch  https //stza.co/+xBLV-3I

Shop  https //stza.co/+xBLV-1q

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:RiverDogs @ Fireflies
END:VALARM
DTSTART:20180607T230500Z
DTEND:20180608T020500Z
UID:TFVOsnUmhssuan5KRdDv45jx@stanza.co
SUMMARY:RiverDogs @ Fireflies
DESCRIPTION:RiverDogs @ Fireflies\n\nFollow on MiLB First Pitch: https://stza.co/+xBLV-3I\n\nShop: https://stza.co/+xBLV-1q\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144512Z
LAST-MODIFIED:20180213T144512Z
TRANSP:OPAQUE
END:VEVENT
* RiverDogs @ Drive
<2018-06-08 Fri 18:05-21:05>
:PROPERTIES:
:ID:       ekJTvo-r0DfFt9NmE9Gq_HT2@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

RiverDogs @ Drive RiverDogs @ Drive

Follow on MiLB First Pitch  https //stza.co/+xEZA-3p

Shop  https //stza.co/+xEZA-3K

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:RiverDogs @ Drive
END:VALARM
DTSTART:20180608T230500Z
DTEND:20180609T020500Z
UID:ekJTvo-r0DfFt9NmE9Gq_HT2@stanza.co
SUMMARY:RiverDogs @ Drive
DESCRIPTION:RiverDogs @ Drive\n\nFollow on MiLB First Pitch: https://stza.co/+xEZA-3p\n\nShop: https://stza.co/+xEZA-3K\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144512Z
LAST-MODIFIED:20180213T144512Z
TRANSP:OPAQUE
END:VEVENT
* RiverDogs @ Drive
<2018-06-09 Sat 18:05-21:05>
:PROPERTIES:
:ID:       FyDxCwavVwChIN5KaOV_fVxg@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

RiverDogs @ Drive RiverDogs @ Drive

Follow on MiLB First Pitch  https //stza.co/+xEZB-2t

Shop  https //stza.co/+xEZB-A

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:RiverDogs @ Drive
END:VALARM
DTSTART:20180609T230500Z
DTEND:20180610T020500Z
UID:FyDxCwavVwChIN5KaOV_fVxg@stanza.co
SUMMARY:RiverDogs @ Drive
DESCRIPTION:RiverDogs @ Drive\n\nFollow on MiLB First Pitch: https://stza.co/+xEZB-2t\n\nShop: https://stza.co/+xEZB-A\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144512Z
LAST-MODIFIED:20180213T144512Z
TRANSP:OPAQUE
END:VEVENT
* RiverDogs @ Drive
<2018-06-10 Sun 15:05-18:05>
:PROPERTIES:
:ID:       XrjA4ezga7ZdvuUpFl-NP_xd@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

RiverDogs @ Drive RiverDogs @ Drive

Follow on MiLB First Pitch  https //stza.co/+xEZC-3U

Shop  https //stza.co/+xEZC-2Y

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:RiverDogs @ Drive
END:VALARM
DTSTART:20180610T200500Z
DTEND:20180610T230500Z
UID:XrjA4ezga7ZdvuUpFl-NP_xd@stanza.co
SUMMARY:RiverDogs @ Drive
DESCRIPTION:RiverDogs @ Drive\n\nFollow on MiLB First Pitch: https://stza.co/+xEZC-3U\n\nShop: https://stza.co/+xEZC-2Y\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144512Z
LAST-MODIFIED:20180213T144512Z
TRANSP:OPAQUE
END:VEVENT
* RiverDogs vs. Tourists
<2018-06-11 Mon 18:05-21:05>
:PROPERTIES:
:ID:       q3mm_GHx4PrTQS5tCHfaAjb6@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

RiverDogs vs. Tourists RiverDogs vs. Tourists

Follow on MiLB First Pitch  https //stza.co/+vNA7-2b

Shop  https //stza.co/+vNA7-1K

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:RiverDogs vs. Tourists
END:VALARM
DTSTART:20180611T230500Z
DTEND:20180612T020500Z
UID:q3mm_GHx4PrTQS5tCHfaAjb6@stanza.co
SUMMARY:RiverDogs vs. Tourists
DESCRIPTION:RiverDogs vs. Tourists\n\nFollow on MiLB First Pitch: https://stza.co/+vNA7-2b\n\nShop: https://stza.co/+vNA7-1K\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144512Z
LAST-MODIFIED:20180213T144512Z
TRANSP:OPAQUE
END:VEVENT
* RiverDogs vs. Tourists
<2018-06-12 Tue 18:05-21:05>
:PROPERTIES:
:ID:       w3WfNgkM_Gg6LXa0kKBOOFzq@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

RiverDogs vs. Tourists RiverDogs vs. Tourists

Follow on MiLB First Pitch  https //stza.co/+vNA9-1B

Shop  https //stza.co/+vNA9-3k

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:RiverDogs vs. Tourists
END:VALARM
DTSTART:20180612T230500Z
DTEND:20180613T020500Z
UID:w3WfNgkM_Gg6LXa0kKBOOFzq@stanza.co
SUMMARY:RiverDogs vs. Tourists
DESCRIPTION:RiverDogs vs. Tourists\n\nFollow on MiLB First Pitch: https://stza.co/+vNA9-1B\n\nShop: https://stza.co/+vNA9-3k\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144512Z
LAST-MODIFIED:20180213T144512Z
TRANSP:OPAQUE
END:VEVENT
* RiverDogs vs. Tourists
<2018-06-13 Wed 18:05-21:05>
:PROPERTIES:
:ID:       ZeJKAiupg0nG1S81lXYlitTv@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

RiverDogs vs. Tourists RiverDogs vs. Tourists

Follow on MiLB First Pitch  https //stza.co/+vNAa-33

Shop  https //stza.co/+vNAa-2Z

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:RiverDogs vs. Tourists
END:VALARM
DTSTART:20180613T230500Z
DTEND:20180614T020500Z
UID:ZeJKAiupg0nG1S81lXYlitTv@stanza.co
SUMMARY:RiverDogs vs. Tourists
DESCRIPTION:RiverDogs vs. Tourists\n\nFollow on MiLB First Pitch: https://stza.co/+vNAa-33\n\nShop: https://stza.co/+vNAa-2Z\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144512Z
LAST-MODIFIED:20180213T144512Z
TRANSP:OPAQUE
END:VEVENT
* RiverDogs vs. Tourists
<2018-06-14 Thu 18:05-21:05>
:PROPERTIES:
:ID:       BayGNkfrf-lVs4r26HCP-aM8@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

RiverDogs vs. Tourists RiverDogs vs. Tourists

Follow on MiLB First Pitch  https //stza.co/+vNAd-2m

Shop  https //stza.co/+vNAd-k

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:RiverDogs vs. Tourists
END:VALARM
DTSTART:20180614T230500Z
DTEND:20180615T020500Z
UID:BayGNkfrf-lVs4r26HCP-aM8@stanza.co
SUMMARY:RiverDogs vs. Tourists
DESCRIPTION:RiverDogs vs. Tourists\n\nFollow on MiLB First Pitch: https://stza.co/+vNAd-2m\n\nShop: https://stza.co/+vNAd-k\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144512Z
LAST-MODIFIED:20180213T144512Z
TRANSP:OPAQUE
END:VEVENT
* RiverDogs vs. Drive
<2018-06-15 Fri 18:05-21:05>
:PROPERTIES:
:ID:       _mK1rmJ3rtKfcHW_1mXaskjN@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

RiverDogs vs. Drive RiverDogs vs. Drive

Follow on MiLB First Pitch  https //stza.co/+vNAf-1W

Shop  https //stza.co/+vNAf-3r

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:RiverDogs vs. Drive
END:VALARM
DTSTART:20180615T230500Z
DTEND:20180616T020500Z
UID:_mK1rmJ3rtKfcHW_1mXaskjN@stanza.co
SUMMARY:RiverDogs vs. Drive
DESCRIPTION:RiverDogs vs. Drive\n\nFollow on MiLB First Pitch: https://stza.co/+vNAf-1W\n\nShop: https://stza.co/+vNAf-3r\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144512Z
LAST-MODIFIED:20180213T144512Z
TRANSP:OPAQUE
END:VEVENT
* RiverDogs vs. Drive
<2018-06-16 Sat 17:05-20:05>
:PROPERTIES:
:ID:       dLcTaXwWme-T0oUvLW-Q3HE8@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

RiverDogs vs. Drive RiverDogs vs. Drive

Follow on MiLB First Pitch  https //stza.co/+vNAg-3Y

Shop  https //stza.co/+vNAg-29

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:RiverDogs vs. Drive
END:VALARM
DTSTART:20180616T220500Z
DTEND:20180617T010500Z
UID:dLcTaXwWme-T0oUvLW-Q3HE8@stanza.co
SUMMARY:RiverDogs vs. Drive
DESCRIPTION:RiverDogs vs. Drive\n\nFollow on MiLB First Pitch: https://stza.co/+vNAg-3Y\n\nShop: https://stza.co/+vNAg-29\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144512Z
LAST-MODIFIED:20180213T144512Z
TRANSP:OPAQUE
END:VEVENT
* RiverDogs vs. Drive
<2018-06-17 Sun 12:05-15:05>
:PROPERTIES:
:ID:       SOnlKSNLhlQ-aVAjV3I9Rkph@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

RiverDogs vs. Drive RiverDogs vs. Drive

Follow on MiLB First Pitch  https //stza.co/+vNAj-39

Shop  https //stza.co/+vNAj-1B

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:RiverDogs vs. Drive
END:VALARM
DTSTART:20180617T170500Z
DTEND:20180617T200500Z
UID:SOnlKSNLhlQ-aVAjV3I9Rkph@stanza.co
SUMMARY:RiverDogs vs. Drive
DESCRIPTION:RiverDogs vs. Drive\n\nFollow on MiLB First Pitch: https://stza.co/+vNAj-39\n\nShop: https://stza.co/+vNAj-1B\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144512Z
LAST-MODIFIED:20180213T144512Z
TRANSP:OPAQUE
END:VEVENT
* RiverDogs @ Legends
<2018-06-21 Thu 18:05-21:05>
:PROPERTIES:
:ID:       XbjG4ob3udOuvAje-aYMUs9i@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

RiverDogs @ Legends RiverDogs @ Legends

Follow on MiLB First Pitch  https //stza.co/+xAWm-2R

Shop  https //stza.co/+xAWm-15

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:RiverDogs @ Legends
END:VALARM
DTSTART:20180621T230500Z
DTEND:20180622T020500Z
UID:XbjG4ob3udOuvAje-aYMUs9i@stanza.co
SUMMARY:RiverDogs @ Legends
DESCRIPTION:RiverDogs @ Legends\n\nFollow on MiLB First Pitch: https://stza.co/+xAWm-2R\n\nShop: https://stza.co/+xAWm-15\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144512Z
LAST-MODIFIED:20180213T144512Z
TRANSP:OPAQUE
END:VEVENT
* RiverDogs @ Legends
<2018-06-22 Fri 18:05-21:05>
:PROPERTIES:
:ID:       VN0zxu6PqY755SJBhoxCLT0M@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

RiverDogs @ Legends RiverDogs @ Legends

Follow on MiLB First Pitch  https //stza.co/+xAWp-W

Shop  https //stza.co/+xAWp-3a

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:RiverDogs @ Legends
END:VALARM
DTSTART:20180622T230500Z
DTEND:20180623T020500Z
UID:VN0zxu6PqY755SJBhoxCLT0M@stanza.co
SUMMARY:RiverDogs @ Legends
DESCRIPTION:RiverDogs @ Legends\n\nFollow on MiLB First Pitch: https://stza.co/+xAWp-W\n\nShop: https://stza.co/+xAWp-3a\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144512Z
LAST-MODIFIED:20180213T144512Z
TRANSP:OPAQUE
END:VEVENT
* RiverDogs @ Legends
<2018-06-23 Sat 17:35-20:35>
:PROPERTIES:
:ID:       kJIy7NzcCYQu0RctWYSiCaKa@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

RiverDogs @ Legends RiverDogs @ Legends

Follow on MiLB First Pitch  https //stza.co/+xAWq-16

Shop  https //stza.co/+xAWq-2

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:RiverDogs @ Legends
END:VALARM
DTSTART:20180623T223500Z
DTEND:20180624T013500Z
UID:kJIy7NzcCYQu0RctWYSiCaKa@stanza.co
SUMMARY:RiverDogs @ Legends
DESCRIPTION:RiverDogs @ Legends\n\nFollow on MiLB First Pitch: https://stza.co/+xAWq-16\n\nShop: https://stza.co/+xAWq-2\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144512Z
LAST-MODIFIED:20180213T144512Z
TRANSP:OPAQUE
END:VEVENT
* RiverDogs @ Tourists
<2018-06-24 Sun 15:05-18:05>
:PROPERTIES:
:ID:       KsgR1ptbjS13Aq4j9bvKlB6m@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

RiverDogs @ Tourists RiverDogs @ Tourists

Follow on MiLB First Pitch  https //stza.co/+vNz7-3L

Shop  https //stza.co/+vNz7-2O

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:RiverDogs @ Tourists
END:VALARM
DTSTART:20180624T200500Z
DTEND:20180624T230500Z
UID:KsgR1ptbjS13Aq4j9bvKlB6m@stanza.co
SUMMARY:RiverDogs @ Tourists
DESCRIPTION:RiverDogs @ Tourists\n\nFollow on MiLB First Pitch: https://stza.co/+vNz7-3L\n\nShop: https://stza.co/+vNz7-2O\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144512Z
LAST-MODIFIED:20180213T144512Z
TRANSP:OPAQUE
END:VEVENT
* RiverDogs @ Tourists
<2018-06-25 Mon 18:05-21:05>
:PROPERTIES:
:ID:       vm7Mof-NGHazEGjiDcX1-xNb@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

RiverDogs @ Tourists RiverDogs @ Tourists

Follow on MiLB First Pitch  https //stza.co/+vNz8-2_

Shop  https //stza.co/+vNz8-2e

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:RiverDogs @ Tourists
END:VALARM
DTSTART:20180625T230500Z
DTEND:20180626T020500Z
UID:vm7Mof-NGHazEGjiDcX1-xNb@stanza.co
SUMMARY:RiverDogs @ Tourists
DESCRIPTION:RiverDogs @ Tourists\n\nFollow on MiLB First Pitch: https://stza.co/+vNz8-2_\n\nShop: https://stza.co/+vNz8-2e\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144512Z
LAST-MODIFIED:20180213T144512Z
TRANSP:OPAQUE
END:VEVENT
* RiverDogs @ Tourists
<2018-06-26 Tue 18:05-21:05>
:PROPERTIES:
:ID:       Ak33V3SLaCL68RxF_cIfkh1O@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

RiverDogs @ Tourists RiverDogs @ Tourists

Follow on MiLB First Pitch  https //stza.co/+vNz9-3_

Shop  https //stza.co/+vNz9-2U

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:RiverDogs @ Tourists
END:VALARM
DTSTART:20180626T230500Z
DTEND:20180627T020500Z
UID:Ak33V3SLaCL68RxF_cIfkh1O@stanza.co
SUMMARY:RiverDogs @ Tourists
DESCRIPTION:RiverDogs @ Tourists\n\nFollow on MiLB First Pitch: https://stza.co/+vNz9-3_\n\nShop: https://stza.co/+vNz9-2U\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144512Z
LAST-MODIFIED:20180213T144512Z
TRANSP:OPAQUE
END:VEVENT
* RiverDogs vs. Braves
<2018-06-27 Wed 18:05-21:05>
:PROPERTIES:
:ID:       aYfnYdHqo0qLnRytwTXXztfk@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

RiverDogs vs. Braves RiverDogs vs. Braves

Follow on MiLB First Pitch  https //stza.co/+vNAk-2s

Shop  https //stza.co/+vNAk-1C

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:RiverDogs vs. Braves
END:VALARM
DTSTART:20180627T230500Z
DTEND:20180628T020500Z
UID:aYfnYdHqo0qLnRytwTXXztfk@stanza.co
SUMMARY:RiverDogs vs. Braves
DESCRIPTION:RiverDogs vs. Braves\n\nFollow on MiLB First Pitch: https://stza.co/+vNAk-2s\n\nShop: https://stza.co/+vNAk-1C\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144512Z
LAST-MODIFIED:20180213T144512Z
TRANSP:OPAQUE
END:VEVENT
* RiverDogs vs. Braves
<2018-06-28 Thu 18:05-21:05>
:PROPERTIES:
:ID:       Xasg9C4_NQIvjHQAjDjTQmBP@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

RiverDogs vs. Braves RiverDogs vs. Braves

Follow on MiLB First Pitch  https //stza.co/+vNAn-3a

Shop  https //stza.co/+vNAn-1i

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:RiverDogs vs. Braves
END:VALARM
DTSTART:20180628T230500Z
DTEND:20180629T020500Z
UID:Xasg9C4_NQIvjHQAjDjTQmBP@stanza.co
SUMMARY:RiverDogs vs. Braves
DESCRIPTION:RiverDogs vs. Braves\n\nFollow on MiLB First Pitch: https://stza.co/+vNAn-3a\n\nShop: https://stza.co/+vNAn-1i\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144512Z
LAST-MODIFIED:20180213T144512Z
TRANSP:OPAQUE
END:VEVENT
* RiverDogs vs. Braves
<2018-06-29 Fri 18:05-21:05>
:PROPERTIES:
:ID:       ezy9_-T9kmV1vkx1aTtfYgMG@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

RiverDogs vs. Braves RiverDogs vs. Braves

Follow on MiLB First Pitch  https //stza.co/+vNAo-14

Shop  https //stza.co/+vNAo-37

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:RiverDogs vs. Braves
END:VALARM
DTSTART:20180629T230500Z
DTEND:20180630T020500Z
UID:ezy9_-T9kmV1vkx1aTtfYgMG@stanza.co
SUMMARY:RiverDogs vs. Braves
DESCRIPTION:RiverDogs vs. Braves\n\nFollow on MiLB First Pitch: https://stza.co/+vNAo-14\n\nShop: https://stza.co/+vNAo-37\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144512Z
LAST-MODIFIED:20180213T144512Z
TRANSP:OPAQUE
END:VEVENT
* RiverDogs @ Drive
<2018-06-30 Sat 18:05-21:05>
:PROPERTIES:
:ID:       7Fha3kVyi-fD2EbJNYVKBJcK@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

RiverDogs @ Drive RiverDogs @ Drive

Follow on MiLB First Pitch  https //stza.co/+xEZD-29

Shop  https //stza.co/+xEZD-2V

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:RiverDogs @ Drive
END:VALARM
DTSTART:20180630T230500Z
DTEND:20180701T020500Z
UID:7Fha3kVyi-fD2EbJNYVKBJcK@stanza.co
SUMMARY:RiverDogs @ Drive
DESCRIPTION:RiverDogs @ Drive\n\nFollow on MiLB First Pitch: https://stza.co/+xEZD-29\n\nShop: https://stza.co/+xEZD-2V\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144512Z
LAST-MODIFIED:20180213T144512Z
TRANSP:OPAQUE
END:VEVENT
* RiverDogs @ Drive
<2018-07-01 Sun 15:05-18:05>
:PROPERTIES:
:ID:       c9t_kOdKBU0KO2JuI6RZ2-7a@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

RiverDogs @ Drive RiverDogs @ Drive

Follow on MiLB First Pitch  https //stza.co/+xEZE-12

Shop  https //stza.co/+xEZE-38

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:RiverDogs @ Drive
END:VALARM
DTSTART:20180701T200500Z
DTEND:20180701T230500Z
UID:c9t_kOdKBU0KO2JuI6RZ2-7a@stanza.co
SUMMARY:RiverDogs @ Drive
DESCRIPTION:RiverDogs @ Drive\n\nFollow on MiLB First Pitch: https://stza.co/+xEZE-12\n\nShop: https://stza.co/+xEZE-38\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144512Z
LAST-MODIFIED:20180213T144512Z
TRANSP:OPAQUE
END:VEVENT
* RiverDogs @ Drive
<2018-07-02 Mon 18:05-21:05>
:PROPERTIES:
:ID:       P4hP18opjUk_FwrRGwYTt8jy@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

RiverDogs @ Drive RiverDogs @ Drive

Follow on MiLB First Pitch  https //stza.co/+xEZF-3U

Shop  https //stza.co/+xEZF-A

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:RiverDogs @ Drive
END:VALARM
DTSTART:20180702T230500Z
DTEND:20180703T020500Z
UID:P4hP18opjUk_FwrRGwYTt8jy@stanza.co
SUMMARY:RiverDogs @ Drive
DESCRIPTION:RiverDogs @ Drive\n\nFollow on MiLB First Pitch: https://stza.co/+xEZF-3U\n\nShop: https://stza.co/+xEZF-A\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144512Z
LAST-MODIFIED:20180213T144512Z
TRANSP:OPAQUE
END:VEVENT
* RiverDogs @ Drive
<2018-07-03 Tue 18:05-21:05>
:PROPERTIES:
:ID:       blagWvUmoQS5tlzgGFVwzNI_@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

RiverDogs @ Drive RiverDogs @ Drive

Follow on MiLB First Pitch  https //stza.co/+xEZG-3X

Shop  https //stza.co/+xEZG-1S

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:RiverDogs @ Drive
END:VALARM
DTSTART:20180703T230500Z
DTEND:20180704T020500Z
UID:blagWvUmoQS5tlzgGFVwzNI_@stanza.co
SUMMARY:RiverDogs @ Drive
DESCRIPTION:RiverDogs @ Drive\n\nFollow on MiLB First Pitch: https://stza.co/+xEZG-3X\n\nShop: https://stza.co/+xEZG-1S\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144512Z
LAST-MODIFIED:20180213T144512Z
TRANSP:OPAQUE
END:VEVENT
* RiverDogs vs. GreenJackets
<2018-07-04 Wed 17:35-20:35>
:PROPERTIES:
:ID:       p5nncbhlBxW5fWN8BzN4H3By@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

RiverDogs vs. GreenJackets RiverDogs vs. GreenJackets

Follow on MiLB First Pitch  https //stza.co/+vNAr-1z

Shop  https //stza.co/+vNAr-1j

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:RiverDogs vs. GreenJackets
END:VALARM
DTSTART:20180704T223500Z
DTEND:20180705T013500Z
UID:p5nncbhlBxW5fWN8BzN4H3By@stanza.co
SUMMARY:RiverDogs vs. GreenJackets
DESCRIPTION:RiverDogs vs. GreenJackets\n\nFollow on MiLB First Pitch: https://stza.co/+vNAr-1z\n\nShop: https://stza.co/+vNAr-1j\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144512Z
LAST-MODIFIED:20180213T144512Z
TRANSP:OPAQUE
END:VEVENT
* RiverDogs vs. GreenJackets
<2018-07-05 Thu 18:05-21:05>
:PROPERTIES:
:ID:       FhNuQyOlQrYn5lM5mujyZy_N@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

RiverDogs vs. GreenJackets RiverDogs vs. GreenJackets

Follow on MiLB First Pitch  https //stza.co/+vNAs-1Q

Shop  https //stza.co/+vNAs-2X

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:RiverDogs vs. GreenJackets
END:VALARM
DTSTART:20180705T230500Z
DTEND:20180706T020500Z
UID:FhNuQyOlQrYn5lM5mujyZy_N@stanza.co
SUMMARY:RiverDogs vs. GreenJackets
DESCRIPTION:RiverDogs vs. GreenJackets\n\nFollow on MiLB First Pitch: https://stza.co/+vNAs-1Q\n\nShop: https://stza.co/+vNAs-2X\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144512Z
LAST-MODIFIED:20180213T144512Z
TRANSP:OPAQUE
END:VEVENT
* RiverDogs vs. GreenJackets
<2018-07-06 Fri 18:05-21:05>
:PROPERTIES:
:ID:       nzOHyZTQ4_1or6rzA3Lm11rO@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

RiverDogs vs. GreenJackets RiverDogs vs. GreenJackets

Follow on MiLB First Pitch  https //stza.co/+vNAu-r

Shop  https //stza.co/+vNAu-1G

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:RiverDogs vs. GreenJackets
END:VALARM
DTSTART:20180706T230500Z
DTEND:20180707T020500Z
UID:nzOHyZTQ4_1or6rzA3Lm11rO@stanza.co
SUMMARY:RiverDogs vs. GreenJackets
DESCRIPTION:RiverDogs vs. GreenJackets\n\nFollow on MiLB First Pitch: https://stza.co/+vNAu-r\n\nShop: https://stza.co/+vNAu-1G\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144512Z
LAST-MODIFIED:20180213T144512Z
TRANSP:OPAQUE
END:VEVENT
* RiverDogs @ Fireflies
<2018-07-07 Sat 17:05-20:05>
:PROPERTIES:
:ID:       CTKN9Hkn3UgKxxEzRWiWEzni@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

RiverDogs @ Fireflies RiverDogs @ Fireflies

Follow on MiLB First Pitch  https //stza.co/+xBLZ-2b

Shop  https //stza.co/+xBLZ-2u

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:RiverDogs @ Fireflies
END:VALARM
DTSTART:20180707T220500Z
DTEND:20180708T010500Z
UID:CTKN9Hkn3UgKxxEzRWiWEzni@stanza.co
SUMMARY:RiverDogs @ Fireflies
DESCRIPTION:RiverDogs @ Fireflies\n\nFollow on MiLB First Pitch: https://stza.co/+xBLZ-2b\n\nShop: https://stza.co/+xBLZ-2u\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144512Z
LAST-MODIFIED:20180213T144512Z
TRANSP:OPAQUE
END:VEVENT
* RiverDogs @ Fireflies
<2018-07-08 Sun 13:05-16:05>
:PROPERTIES:
:ID:       0mIDAU1fa6Jnn2W7yX9FoSov@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

RiverDogs @ Fireflies RiverDogs @ Fireflies

Follow on MiLB First Pitch  https //stza.co/+xBM0-D

Shop  https //stza.co/+xBM0-3r

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:RiverDogs @ Fireflies
END:VALARM
DTSTART:20180708T180500Z
DTEND:20180708T210500Z
UID:0mIDAU1fa6Jnn2W7yX9FoSov@stanza.co
SUMMARY:RiverDogs @ Fireflies
DESCRIPTION:RiverDogs @ Fireflies\n\nFollow on MiLB First Pitch: https://stza.co/+xBM0-D\n\nShop: https://stza.co/+xBM0-3r\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144512Z
LAST-MODIFIED:20180213T144512Z
TRANSP:OPAQUE
END:VEVENT
* RiverDogs @ Fireflies
<2018-07-09 Mon 18:05-21:05>
:PROPERTIES:
:ID:       4_GgWRunKolfhanRudjgBr1b@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

RiverDogs @ Fireflies RiverDogs @ Fireflies

Follow on MiLB First Pitch  https //stza.co/+xBM3-38

Shop  https //stza.co/+xBM3-3M

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:RiverDogs @ Fireflies
END:VALARM
DTSTART:20180709T230500Z
DTEND:20180710T020500Z
UID:4_GgWRunKolfhanRudjgBr1b@stanza.co
SUMMARY:RiverDogs @ Fireflies
DESCRIPTION:RiverDogs @ Fireflies\n\nFollow on MiLB First Pitch: https://stza.co/+xBM3-38\n\nShop: https://stza.co/+xBM3-3M\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144512Z
LAST-MODIFIED:20180213T144512Z
TRANSP:OPAQUE
END:VEVENT
* RiverDogs vs. Shorebirds
<2018-07-11 Wed 18:05-21:05>
:PROPERTIES:
:ID:       sQ6MLovZcLQCrhF1fTe994Rs@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

RiverDogs vs. Shorebirds RiverDogs vs. Shorebirds

Follow on MiLB First Pitch  https //stza.co/+vNAx-3X

Shop  https //stza.co/+vNAx-1N

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:RiverDogs vs. Shorebirds
END:VALARM
DTSTART:20180711T230500Z
DTEND:20180712T020500Z
UID:sQ6MLovZcLQCrhF1fTe994Rs@stanza.co
SUMMARY:RiverDogs vs. Shorebirds
DESCRIPTION:RiverDogs vs. Shorebirds\n\nFollow on MiLB First Pitch: https://stza.co/+vNAx-3X\n\nShop: https://stza.co/+vNAx-1N\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144512Z
LAST-MODIFIED:20180213T144512Z
TRANSP:OPAQUE
END:VEVENT
* RiverDogs vs. Shorebirds
<2018-07-12 Thu 18:05-21:05>
:PROPERTIES:
:ID:       m4sKT5ivnrziUilFXr4YnGzF@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

RiverDogs vs. Shorebirds RiverDogs vs. Shorebirds

Follow on MiLB First Pitch  https //stza.co/+vNAz-z

Shop  https //stza.co/+vNAz-1n

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:RiverDogs vs. Shorebirds
END:VALARM
DTSTART:20180712T230500Z
DTEND:20180713T020500Z
UID:m4sKT5ivnrziUilFXr4YnGzF@stanza.co
SUMMARY:RiverDogs vs. Shorebirds
DESCRIPTION:RiverDogs vs. Shorebirds\n\nFollow on MiLB First Pitch: https://stza.co/+vNAz-z\n\nShop: https://stza.co/+vNAz-1n\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144512Z
LAST-MODIFIED:20180213T144512Z
TRANSP:OPAQUE
END:VEVENT
* RiverDogs vs. Shorebirds
<2018-07-13 Fri 18:05-21:05>
:PROPERTIES:
:ID:       iCRql40ig8I6PAtr0XJLnwRW@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

RiverDogs vs. Shorebirds RiverDogs vs. Shorebirds

Follow on MiLB First Pitch  https //stza.co/+vNAB-3w

Shop  https //stza.co/+vNAB-2y

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:RiverDogs vs. Shorebirds
END:VALARM
DTSTART:20180713T230500Z
DTEND:20180714T020500Z
UID:iCRql40ig8I6PAtr0XJLnwRW@stanza.co
SUMMARY:RiverDogs vs. Shorebirds
DESCRIPTION:RiverDogs vs. Shorebirds\n\nFollow on MiLB First Pitch: https://stza.co/+vNAB-3w\n\nShop: https://stza.co/+vNAB-2y\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144512Z
LAST-MODIFIED:20180213T144512Z
TRANSP:OPAQUE
END:VEVENT
* RiverDogs vs. Crawdads
<2018-07-14 Sat 17:05-20:05>
:PROPERTIES:
:ID:       dgdBWo-962K_7PsLaquEGUo9@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

RiverDogs vs. Crawdads RiverDogs vs. Crawdads

Follow on MiLB First Pitch  https //stza.co/+vNAD-V

Shop  https //stza.co/+vNAD-2L

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:RiverDogs vs. Crawdads
END:VALARM
DTSTART:20180714T220500Z
DTEND:20180715T010500Z
UID:dgdBWo-962K_7PsLaquEGUo9@stanza.co
SUMMARY:RiverDogs vs. Crawdads
DESCRIPTION:RiverDogs vs. Crawdads\n\nFollow on MiLB First Pitch: https://stza.co/+vNAD-V\n\nShop: https://stza.co/+vNAD-2L\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144512Z
LAST-MODIFIED:20180213T144512Z
TRANSP:OPAQUE
END:VEVENT
* RiverDogs vs. Crawdads
<2018-07-15 Sun 16:05-19:05>
:PROPERTIES:
:ID:       4S76Ehzrs2n7uwkDW8qhbWVG@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

RiverDogs vs. Crawdads RiverDogs vs. Crawdads

Follow on MiLB First Pitch  https //stza.co/+vNAF-1x

Shop  https //stza.co/+vNAF-3J

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:RiverDogs vs. Crawdads
END:VALARM
DTSTART:20180715T210500Z
DTEND:20180716T000500Z
UID:4S76Ehzrs2n7uwkDW8qhbWVG@stanza.co
SUMMARY:RiverDogs vs. Crawdads
DESCRIPTION:RiverDogs vs. Crawdads\n\nFollow on MiLB First Pitch: https://stza.co/+vNAF-1x\n\nShop: https://stza.co/+vNAF-3J\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144512Z
LAST-MODIFIED:20180213T144512Z
TRANSP:OPAQUE
END:VEVENT
* RiverDogs vs. Crawdads
<2018-07-16 Mon 18:05-21:05>
:PROPERTIES:
:ID:       v0s0H3JDRSxvrMA_meXA-zOu@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

RiverDogs vs. Crawdads RiverDogs vs. Crawdads

Follow on MiLB First Pitch  https //stza.co/+vNAG-I

Shop  https //stza.co/+vNAG-2W

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:RiverDogs vs. Crawdads
END:VALARM
DTSTART:20180716T230500Z
DTEND:20180717T020500Z
UID:v0s0H3JDRSxvrMA_meXA-zOu@stanza.co
SUMMARY:RiverDogs vs. Crawdads
DESCRIPTION:RiverDogs vs. Crawdads\n\nFollow on MiLB First Pitch: https://stza.co/+vNAG-I\n\nShop: https://stza.co/+vNAG-2W\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144512Z
LAST-MODIFIED:20180213T144512Z
TRANSP:OPAQUE
END:VEVENT
* RiverDogs vs. Crawdads
<2018-07-17 Tue 11:05-14:05>
:PROPERTIES:
:ID:       HF5USeg6xbYwhyBwbm02l-u3@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

RiverDogs vs. Crawdads RiverDogs vs. Crawdads

Follow on MiLB First Pitch  https //stza.co/+vNAJ-37

Shop  https //stza.co/+vNAJ-2R

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:RiverDogs vs. Crawdads
END:VALARM
DTSTART:20180717T160500Z
DTEND:20180717T190500Z
UID:HF5USeg6xbYwhyBwbm02l-u3@stanza.co
SUMMARY:RiverDogs vs. Crawdads
DESCRIPTION:RiverDogs vs. Crawdads\n\nFollow on MiLB First Pitch: https://stza.co/+vNAJ-37\n\nShop: https://stza.co/+vNAJ-2R\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144512Z
LAST-MODIFIED:20180213T144512Z
TRANSP:OPAQUE
END:VEVENT
* RiverDogs @ Braves
<2018-07-19 Thu 18:00-21:00>
:PROPERTIES:
:ID:       7iCrYizDD5MlNPQcdE4xQNo_@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

RiverDogs @ Braves RiverDogs @ Braves

Follow on MiLB First Pitch  https //stza.co/+vNCh-3i

Shop  https //stza.co/+vNCh-1D

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:RiverDogs @ Braves
END:VALARM
DTSTART:20180719T230000Z
DTEND:20180720T020000Z
UID:7iCrYizDD5MlNPQcdE4xQNo_@stanza.co
SUMMARY:RiverDogs @ Braves
DESCRIPTION:RiverDogs @ Braves\n\nFollow on MiLB First Pitch: https://stza.co/+vNCh-3i\n\nShop: https://stza.co/+vNCh-1D\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144512Z
LAST-MODIFIED:20180213T144512Z
TRANSP:OPAQUE
END:VEVENT
* RiverDogs @ Braves
<2018-07-20 Fri 18:00-21:00>
:PROPERTIES:
:ID:       _WURV140tZM5ysSHjb7TL_b3@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

RiverDogs @ Braves RiverDogs @ Braves

Follow on MiLB First Pitch  https //stza.co/+vNCi-3h

Shop  https //stza.co/+vNCi-1N

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:RiverDogs @ Braves
END:VALARM
DTSTART:20180720T230000Z
DTEND:20180721T020000Z
UID:_WURV140tZM5ysSHjb7TL_b3@stanza.co
SUMMARY:RiverDogs @ Braves
DESCRIPTION:RiverDogs @ Braves\n\nFollow on MiLB First Pitch: https://stza.co/+vNCi-3h\n\nShop: https://stza.co/+vNCi-1N\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144512Z
LAST-MODIFIED:20180213T144512Z
TRANSP:OPAQUE
END:VEVENT
* RiverDogs @ Braves
<2018-07-21 Sat 17:00-20:00>
:PROPERTIES:
:ID:       Oh3pLRgbhCz37Nf-AUeebIBz@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

RiverDogs @ Braves RiverDogs @ Braves

Follow on MiLB First Pitch  https //stza.co/+vNCj-3i

Shop  https //stza.co/+vNCj-M

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:RiverDogs @ Braves
END:VALARM
DTSTART:20180721T220000Z
DTEND:20180722T010000Z
UID:Oh3pLRgbhCz37Nf-AUeebIBz@stanza.co
SUMMARY:RiverDogs @ Braves
DESCRIPTION:RiverDogs @ Braves\n\nFollow on MiLB First Pitch: https://stza.co/+vNCj-3i\n\nShop: https://stza.co/+vNCj-M\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144512Z
LAST-MODIFIED:20180213T144512Z
TRANSP:OPAQUE
END:VEVENT
* RiverDogs @ Braves
<2018-07-22 Sun 13:00-16:00>
:PROPERTIES:
:ID:       A7PXEem8e-AW8UCbaalXd5Rl@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

RiverDogs @ Braves RiverDogs @ Braves

Follow on MiLB First Pitch  https //stza.co/+vNCk-26

Shop  https //stza.co/+vNCk-1d

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:RiverDogs @ Braves
END:VALARM
DTSTART:20180722T180000Z
DTEND:20180722T210000Z
UID:A7PXEem8e-AW8UCbaalXd5Rl@stanza.co
SUMMARY:RiverDogs @ Braves
DESCRIPTION:RiverDogs @ Braves\n\nFollow on MiLB First Pitch: https://stza.co/+vNCk-26\n\nShop: https://stza.co/+vNCk-1d\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144512Z
LAST-MODIFIED:20180213T144512Z
TRANSP:OPAQUE
END:VEVENT
* RiverDogs vs. GreenJackets
<2018-07-23 Mon 18:05-21:05>
:PROPERTIES:
:ID:       aAFVoFjyw7ZuyQQBJdqFHZIC@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

RiverDogs vs. GreenJackets RiverDogs vs. GreenJackets

Follow on MiLB First Pitch  https //stza.co/+vNAL-33

Shop  https //stza.co/+vNAL-1D

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:RiverDogs vs. GreenJackets
END:VALARM
DTSTART:20180723T230500Z
DTEND:20180724T020500Z
UID:aAFVoFjyw7ZuyQQBJdqFHZIC@stanza.co
SUMMARY:RiverDogs vs. GreenJackets
DESCRIPTION:RiverDogs vs. GreenJackets\n\nFollow on MiLB First Pitch: https://stza.co/+vNAL-33\n\nShop: https://stza.co/+vNAL-1D\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144512Z
LAST-MODIFIED:20180213T144512Z
TRANSP:OPAQUE
END:VEVENT
* RiverDogs vs. GreenJackets
<2018-07-24 Tue 18:05-21:05>
:PROPERTIES:
:ID:       IKk4jS0HrPVrm8JvX-JAaVjT@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

RiverDogs vs. GreenJackets RiverDogs vs. GreenJackets

Follow on MiLB First Pitch  https //stza.co/+vNAN-1L

Shop  https //stza.co/+vNAN-1M

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:RiverDogs vs. GreenJackets
END:VALARM
DTSTART:20180724T230500Z
DTEND:20180725T020500Z
UID:IKk4jS0HrPVrm8JvX-JAaVjT@stanza.co
SUMMARY:RiverDogs vs. GreenJackets
DESCRIPTION:RiverDogs vs. GreenJackets\n\nFollow on MiLB First Pitch: https://stza.co/+vNAN-1L\n\nShop: https://stza.co/+vNAN-1M\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144512Z
LAST-MODIFIED:20180213T144512Z
TRANSP:OPAQUE
END:VEVENT
* RiverDogs vs. GreenJackets
<2018-07-25 Wed 18:05-21:05>
:PROPERTIES:
:ID:       ChUBwOwsqWH1WPvSi7lS6fM6@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

RiverDogs vs. GreenJackets RiverDogs vs. GreenJackets

Follow on MiLB First Pitch  https //stza.co/+vNAO-g

Shop  https //stza.co/+vNAO-1H

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:RiverDogs vs. GreenJackets
END:VALARM
DTSTART:20180725T230500Z
DTEND:20180726T020500Z
UID:ChUBwOwsqWH1WPvSi7lS6fM6@stanza.co
SUMMARY:RiverDogs vs. GreenJackets
DESCRIPTION:RiverDogs vs. GreenJackets\n\nFollow on MiLB First Pitch: https://stza.co/+vNAO-g\n\nShop: https://stza.co/+vNAO-1H\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144512Z
LAST-MODIFIED:20180213T144512Z
TRANSP:OPAQUE
END:VEVENT
* RiverDogs vs. GreenJackets
<2018-07-26 Thu 18:05-21:05>
:PROPERTIES:
:ID:       ihcaKZ5qkAfysM8VrnXe3Gfo@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

RiverDogs vs. GreenJackets RiverDogs vs. GreenJackets

Follow on MiLB First Pitch  https //stza.co/+vNAR-w

Shop  https //stza.co/+vNAR-r

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:RiverDogs vs. GreenJackets
END:VALARM
DTSTART:20180726T230500Z
DTEND:20180727T020500Z
UID:ihcaKZ5qkAfysM8VrnXe3Gfo@stanza.co
SUMMARY:RiverDogs vs. GreenJackets
DESCRIPTION:RiverDogs vs. GreenJackets\n\nFollow on MiLB First Pitch: https://stza.co/+vNAR-w\n\nShop: https://stza.co/+vNAR-r\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144512Z
LAST-MODIFIED:20180213T144512Z
TRANSP:OPAQUE
END:VEVENT
* RiverDogs vs. Drive
<2018-07-27 Fri 18:05-21:05>
:PROPERTIES:
:ID:       yS41aI3rlsNMCvD1wZlLdyQW@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

RiverDogs vs. Drive RiverDogs vs. Drive

Follow on MiLB First Pitch  https //stza.co/+vNAT-2H

Shop  https //stza.co/+vNAT-26

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:RiverDogs vs. Drive
END:VALARM
DTSTART:20180727T230500Z
DTEND:20180728T020500Z
UID:yS41aI3rlsNMCvD1wZlLdyQW@stanza.co
SUMMARY:RiverDogs vs. Drive
DESCRIPTION:RiverDogs vs. Drive\n\nFollow on MiLB First Pitch: https://stza.co/+vNAT-2H\n\nShop: https://stza.co/+vNAT-26\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144512Z
LAST-MODIFIED:20180213T144512Z
TRANSP:OPAQUE
END:VEVENT
* RiverDogs vs. Drive
<2018-07-28 Sat 17:05-20:05>
:PROPERTIES:
:ID:       u_Zh3jBvBcADPe4UZFx0RY2l@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

RiverDogs vs. Drive RiverDogs vs. Drive

Follow on MiLB First Pitch  https //stza.co/+vNAV-2H

Shop  https //stza.co/+vNAV-1H

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:RiverDogs vs. Drive
END:VALARM
DTSTART:20180728T220500Z
DTEND:20180729T010500Z
UID:u_Zh3jBvBcADPe4UZFx0RY2l@stanza.co
SUMMARY:RiverDogs vs. Drive
DESCRIPTION:RiverDogs vs. Drive\n\nFollow on MiLB First Pitch: https://stza.co/+vNAV-2H\n\nShop: https://stza.co/+vNAV-1H\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144512Z
LAST-MODIFIED:20180213T144512Z
TRANSP:OPAQUE
END:VEVENT
* RiverDogs vs. Drive
<2018-07-29 Sun 16:05-19:05>
:PROPERTIES:
:ID:       B2j_1ID9Gwk_YCbEarKO7fOe@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

RiverDogs vs. Drive RiverDogs vs. Drive

Follow on MiLB First Pitch  https //stza.co/+vNAW-33

Shop  https //stza.co/+vNAW-3l

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:RiverDogs vs. Drive
END:VALARM
DTSTART:20180729T210500Z
DTEND:20180730T000500Z
UID:B2j_1ID9Gwk_YCbEarKO7fOe@stanza.co
SUMMARY:RiverDogs vs. Drive
DESCRIPTION:RiverDogs vs. Drive\n\nFollow on MiLB First Pitch: https://stza.co/+vNAW-33\n\nShop: https://stza.co/+vNAW-3l\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144512Z
LAST-MODIFIED:20180213T144512Z
TRANSP:OPAQUE
END:VEVENT
* RiverDogs @ Crawdads
<2018-07-30 Mon 18:00-21:00>
:PROPERTIES:
:ID:       xnF-WCnb_G57rr_rDR85caZx@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

RiverDogs @ Crawdads RiverDogs @ Crawdads

Follow on MiLB First Pitch  https //stza.co/+w0Ob-1b

Shop  https //stza.co/+w0Ob-2c

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:RiverDogs @ Crawdads
END:VALARM
DTSTART:20180730T230000Z
DTEND:20180731T020000Z
UID:xnF-WCnb_G57rr_rDR85caZx@stanza.co
SUMMARY:RiverDogs @ Crawdads
DESCRIPTION:RiverDogs @ Crawdads\n\nFollow on MiLB First Pitch: https://stza.co/+w0Ob-1b\n\nShop: https://stza.co/+w0Ob-2c\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144512Z
LAST-MODIFIED:20180213T144512Z
TRANSP:OPAQUE
END:VEVENT
* RiverDogs @ Crawdads
<2018-07-31 Tue 18:00-21:00>
:PROPERTIES:
:ID:       _vRTAfE0TI1S5cO_OtkRJMko@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

RiverDogs @ Crawdads RiverDogs @ Crawdads

Follow on MiLB First Pitch  https //stza.co/+w0Oc-3z

Shop  https //stza.co/+w0Oc-20

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:RiverDogs @ Crawdads
END:VALARM
DTSTART:20180731T230000Z
DTEND:20180801T020000Z
UID:_vRTAfE0TI1S5cO_OtkRJMko@stanza.co
SUMMARY:RiverDogs @ Crawdads
DESCRIPTION:RiverDogs @ Crawdads\n\nFollow on MiLB First Pitch: https://stza.co/+w0Oc-3z\n\nShop: https://stza.co/+w0Oc-20\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144512Z
LAST-MODIFIED:20180213T144512Z
TRANSP:OPAQUE
END:VEVENT
* RiverDogs @ Crawdads
<2018-08-01 Wed 11:00-14:00>
:PROPERTIES:
:ID:       UhWorCH38CPjx2z4mBz3Hhvr@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

RiverDogs @ Crawdads RiverDogs @ Crawdads

Follow on MiLB First Pitch  https //stza.co/+w0Od-3E

Shop  https //stza.co/+w0Od-Q

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:RiverDogs @ Crawdads
END:VALARM
DTSTART:20180801T160000Z
DTEND:20180801T190000Z
UID:UhWorCH38CPjx2z4mBz3Hhvr@stanza.co
SUMMARY:RiverDogs @ Crawdads
DESCRIPTION:RiverDogs @ Crawdads\n\nFollow on MiLB First Pitch: https://stza.co/+w0Od-3E\n\nShop: https://stza.co/+w0Od-Q\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144512Z
LAST-MODIFIED:20180213T144512Z
TRANSP:OPAQUE
END:VEVENT
* RiverDogs @ Shorebirds
<2018-08-02 Thu 18:05-21:05>
:PROPERTIES:
:ID:       FC52XnS2VckjFCfUsBoNa_-B@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

RiverDogs @ Shorebirds RiverDogs @ Shorebirds

Follow on MiLB First Pitch  https //stza.co/+wHLB-3E

Shop  https //stza.co/+wHLB-3b

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:RiverDogs @ Shorebirds
END:VALARM
DTSTART:20180802T230500Z
DTEND:20180803T020500Z
UID:FC52XnS2VckjFCfUsBoNa_-B@stanza.co
SUMMARY:RiverDogs @ Shorebirds
DESCRIPTION:RiverDogs @ Shorebirds\n\nFollow on MiLB First Pitch: https://stza.co/+wHLB-3E\n\nShop: https://stza.co/+wHLB-3b\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144512Z
LAST-MODIFIED:20180213T144512Z
TRANSP:OPAQUE
END:VEVENT
* RiverDogs @ Shorebirds
<2018-08-03 Fri 18:05-21:05>
:PROPERTIES:
:ID:       iew5ME-14BdmEcreIimS-uHZ@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

RiverDogs @ Shorebirds RiverDogs @ Shorebirds

Follow on MiLB First Pitch  https //stza.co/+wHLE-L

Shop  https //stza.co/+wHLE-3n

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:RiverDogs @ Shorebirds
END:VALARM
DTSTART:20180803T230500Z
DTEND:20180804T020500Z
UID:iew5ME-14BdmEcreIimS-uHZ@stanza.co
SUMMARY:RiverDogs @ Shorebirds
DESCRIPTION:RiverDogs @ Shorebirds\n\nFollow on MiLB First Pitch: https://stza.co/+wHLE-L\n\nShop: https://stza.co/+wHLE-3n\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144512Z
LAST-MODIFIED:20180213T144512Z
TRANSP:OPAQUE
END:VEVENT
* RiverDogs @ Shorebirds
<2018-08-04 Sat 18:05-21:05>
:PROPERTIES:
:ID:       q1mUqnMtM1rUyoUQ8E711xtz@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

RiverDogs @ Shorebirds RiverDogs @ Shorebirds

Follow on MiLB First Pitch  https //stza.co/+wHLH-1r

Shop  https //stza.co/+wHLH-D

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:RiverDogs @ Shorebirds
END:VALARM
DTSTART:20180804T230500Z
DTEND:20180805T020500Z
UID:q1mUqnMtM1rUyoUQ8E711xtz@stanza.co
SUMMARY:RiverDogs @ Shorebirds
DESCRIPTION:RiverDogs @ Shorebirds\n\nFollow on MiLB First Pitch: https://stza.co/+wHLH-1r\n\nShop: https://stza.co/+wHLH-D\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144512Z
LAST-MODIFIED:20180213T144512Z
TRANSP:OPAQUE
END:VEVENT
* RiverDogs @ Shorebirds
<2018-08-05 Sun 16:05-19:05>
:PROPERTIES:
:ID:       Z-tndKErPWFe3rG6UuW0UPO5@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

RiverDogs @ Shorebirds RiverDogs @ Shorebirds

Follow on MiLB First Pitch  https //stza.co/+wHLI-3w

Shop  https //stza.co/+wHLI-j

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:RiverDogs @ Shorebirds
END:VALARM
DTSTART:20180805T210500Z
DTEND:20180806T000500Z
UID:Z-tndKErPWFe3rG6UuW0UPO5@stanza.co
SUMMARY:RiverDogs @ Shorebirds
DESCRIPTION:RiverDogs @ Shorebirds\n\nFollow on MiLB First Pitch: https://stza.co/+wHLI-3w\n\nShop: https://stza.co/+wHLI-j\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144512Z
LAST-MODIFIED:20180213T144512Z
TRANSP:OPAQUE
END:VEVENT
* RiverDogs vs. BlueClaws
<2018-08-07 Tue 18:05-21:05>
:PROPERTIES:
:ID:       uXE2vADOf5MqMoN6VEhWeF-i@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

RiverDogs vs. BlueClaws RiverDogs vs. BlueClaws

Follow on MiLB First Pitch  https //stza.co/+vNAZ-1f

Shop  https //stza.co/+vNAZ-18

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:RiverDogs vs. BlueClaws
END:VALARM
DTSTART:20180807T230500Z
DTEND:20180808T020500Z
UID:uXE2vADOf5MqMoN6VEhWeF-i@stanza.co
SUMMARY:RiverDogs vs. BlueClaws
DESCRIPTION:RiverDogs vs. BlueClaws\n\nFollow on MiLB First Pitch: https://stza.co/+vNAZ-1f\n\nShop: https://stza.co/+vNAZ-18\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144512Z
LAST-MODIFIED:20180213T144512Z
TRANSP:OPAQUE
END:VEVENT
* RiverDogs vs. BlueClaws
<2018-08-08 Wed 18:05-21:05>
:PROPERTIES:
:ID:       w51Ox4Wsy1Q_RqnNb1fU80GY@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

RiverDogs vs. BlueClaws RiverDogs vs. BlueClaws

Follow on MiLB First Pitch  https //stza.co/+vNA$-1P

Shop  https //stza.co/+vNA$-Y

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:RiverDogs vs. BlueClaws
END:VALARM
DTSTART:20180808T230500Z
DTEND:20180809T020500Z
UID:w51Ox4Wsy1Q_RqnNb1fU80GY@stanza.co
SUMMARY:RiverDogs vs. BlueClaws
DESCRIPTION:RiverDogs vs. BlueClaws\n\nFollow on MiLB First Pitch: https://stza.co/+vNA$-1P\n\nShop: https://stza.co/+vNA$-Y\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144512Z
LAST-MODIFIED:20180213T144512Z
TRANSP:OPAQUE
END:VEVENT
* RiverDogs vs. BlueClaws
<2018-08-09 Thu 18:05-21:05>
:PROPERTIES:
:ID:       vh27rGx2aXUixk9PoIaG-mPN@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

RiverDogs vs. BlueClaws RiverDogs vs. BlueClaws

Follow on MiLB First Pitch  https //stza.co/+vNB1-1C

Shop  https //stza.co/+vNB1-Z

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:RiverDogs vs. BlueClaws
END:VALARM
DTSTART:20180809T230500Z
DTEND:20180810T020500Z
UID:vh27rGx2aXUixk9PoIaG-mPN@stanza.co
SUMMARY:RiverDogs vs. BlueClaws
DESCRIPTION:RiverDogs vs. BlueClaws\n\nFollow on MiLB First Pitch: https://stza.co/+vNB1-1C\n\nShop: https://stza.co/+vNB1-Z\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144512Z
LAST-MODIFIED:20180213T144512Z
TRANSP:OPAQUE
END:VEVENT
* RiverDogs vs. Suns
<2018-08-10 Fri 18:05-21:05>
:PROPERTIES:
:ID:       bti_aWR_-cxD1bTdum6zU5c6@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

RiverDogs vs. Suns RiverDogs vs. Suns

Follow on MiLB First Pitch  https //stza.co/+vNB3-3n

Shop  https //stza.co/+vNB3-1x

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:RiverDogs vs. Suns
END:VALARM
DTSTART:20180810T230500Z
DTEND:20180811T020500Z
UID:bti_aWR_-cxD1bTdum6zU5c6@stanza.co
SUMMARY:RiverDogs vs. Suns
DESCRIPTION:RiverDogs vs. Suns\n\nFollow on MiLB First Pitch: https://stza.co/+vNB3-3n\n\nShop: https://stza.co/+vNB3-1x\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144512Z
LAST-MODIFIED:20180213T144512Z
TRANSP:OPAQUE
END:VEVENT
* RiverDogs vs. Suns
<2018-08-11 Sat 17:05-20:05>
:PROPERTIES:
:ID:       Jno-MWjbg4AEqBu3guhmWBqt@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

RiverDogs vs. Suns RiverDogs vs. Suns

Follow on MiLB First Pitch  https //stza.co/+vNB4-16

Shop  https //stza.co/+vNB4-1L

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:RiverDogs vs. Suns
END:VALARM
DTSTART:20180811T220500Z
DTEND:20180812T010500Z
UID:Jno-MWjbg4AEqBu3guhmWBqt@stanza.co
SUMMARY:RiverDogs vs. Suns
DESCRIPTION:RiverDogs vs. Suns\n\nFollow on MiLB First Pitch: https://stza.co/+vNB4-16\n\nShop: https://stza.co/+vNB4-1L\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144512Z
LAST-MODIFIED:20180213T144512Z
TRANSP:OPAQUE
END:VEVENT
* RiverDogs vs. Suns
<2018-08-12 Sun 16:05-19:05>
:PROPERTIES:
:ID:       vn35Dm1I41WV2TWxb7a_imJQ@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

RiverDogs vs. Suns RiverDogs vs. Suns

Follow on MiLB First Pitch  https //stza.co/+vNB6-1N

Shop  https //stza.co/+vNB6-3q

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:RiverDogs vs. Suns
END:VALARM
DTSTART:20180812T210500Z
DTEND:20180813T000500Z
UID:vn35Dm1I41WV2TWxb7a_imJQ@stanza.co
SUMMARY:RiverDogs vs. Suns
DESCRIPTION:RiverDogs vs. Suns\n\nFollow on MiLB First Pitch: https://stza.co/+vNB6-1N\n\nShop: https://stza.co/+vNB6-3q\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144512Z
LAST-MODIFIED:20180213T144512Z
TRANSP:OPAQUE
END:VEVENT
* RiverDogs vs. Suns
<2018-08-13 Mon 18:05-21:05>
:PROPERTIES:
:ID:       J3H5iGq1y6DlDjTokL4ekO24@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

RiverDogs vs. Suns RiverDogs vs. Suns

Follow on MiLB First Pitch  https //stza.co/+vNB9-3D

Shop  https //stza.co/+vNB9-37

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:RiverDogs vs. Suns
END:VALARM
DTSTART:20180813T230500Z
DTEND:20180814T020500Z
UID:J3H5iGq1y6DlDjTokL4ekO24@stanza.co
SUMMARY:RiverDogs vs. Suns
DESCRIPTION:RiverDogs vs. Suns\n\nFollow on MiLB First Pitch: https://stza.co/+vNB9-3D\n\nShop: https://stza.co/+vNB9-37\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144512Z
LAST-MODIFIED:20180213T144512Z
TRANSP:OPAQUE
END:VEVENT
* RiverDogs @ Shorebirds
<2018-08-15 Wed 18:05-21:05>
:PROPERTIES:
:ID:       IlENI-4-MYQV_mFFBfXaAok6@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

RiverDogs @ Shorebirds RiverDogs @ Shorebirds

Follow on MiLB First Pitch  https //stza.co/+wHGb-1K

Shop  https //stza.co/+wHGb-2g

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:RiverDogs @ Shorebirds
END:VALARM
DTSTART:20180815T230500Z
DTEND:20180816T020500Z
UID:IlENI-4-MYQV_mFFBfXaAok6@stanza.co
SUMMARY:RiverDogs @ Shorebirds
DESCRIPTION:RiverDogs @ Shorebirds\n\nFollow on MiLB First Pitch: https://stza.co/+wHGb-1K\n\nShop: https://stza.co/+wHGb-2g\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144512Z
LAST-MODIFIED:20180213T144512Z
TRANSP:OPAQUE
END:VEVENT
* RiverDogs @ Shorebirds
<2018-08-16 Thu 18:05-21:05>
:PROPERTIES:
:ID:       LoiLUcdIIr60UoF-om0ugvZp@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

RiverDogs @ Shorebirds RiverDogs @ Shorebirds

Follow on MiLB First Pitch  https //stza.co/+wHGf-y

Shop  https //stza.co/+wHGf-1I

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:RiverDogs @ Shorebirds
END:VALARM
DTSTART:20180816T230500Z
DTEND:20180817T020500Z
UID:LoiLUcdIIr60UoF-om0ugvZp@stanza.co
SUMMARY:RiverDogs @ Shorebirds
DESCRIPTION:RiverDogs @ Shorebirds\n\nFollow on MiLB First Pitch: https://stza.co/+wHGf-y\n\nShop: https://stza.co/+wHGf-1I\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144512Z
LAST-MODIFIED:20180213T144512Z
TRANSP:OPAQUE
END:VEVENT
* RiverDogs @ Shorebirds
<2018-08-17 Fri 18:05-21:05>
:PROPERTIES:
:ID:       EGP8bSfckS1ja5mihBLVC10h@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

RiverDogs @ Shorebirds RiverDogs @ Shorebirds

Follow on MiLB First Pitch  https //stza.co/+wHGg-2O

Shop  https //stza.co/+wHGg-1k

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:RiverDogs @ Shorebirds
END:VALARM
DTSTART:20180817T230500Z
DTEND:20180818T020500Z
UID:EGP8bSfckS1ja5mihBLVC10h@stanza.co
SUMMARY:RiverDogs @ Shorebirds
DESCRIPTION:RiverDogs @ Shorebirds\n\nFollow on MiLB First Pitch: https://stza.co/+wHGg-2O\n\nShop: https://stza.co/+wHGg-1k\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144512Z
LAST-MODIFIED:20180213T144512Z
TRANSP:OPAQUE
END:VEVENT
* RiverDogs @ Power
<2018-08-18 Sat 17:05-20:05>
:PROPERTIES:
:ID:       gMOE9wuMuNtr-Oy-wPDt91wf@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

RiverDogs @ Power RiverDogs @ Power

Follow on MiLB First Pitch  https //stza.co/+xJ3y-3_

Shop  https //stza.co/+xJ3y-1x

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:RiverDogs @ Power
END:VALARM
DTSTART:20180818T220500Z
DTEND:20180819T010500Z
UID:gMOE9wuMuNtr-Oy-wPDt91wf@stanza.co
SUMMARY:RiverDogs @ Power
DESCRIPTION:RiverDogs @ Power\n\nFollow on MiLB First Pitch: https://stza.co/+xJ3y-3_\n\nShop: https://stza.co/+xJ3y-1x\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144512Z
LAST-MODIFIED:20180213T144512Z
TRANSP:OPAQUE
END:VEVENT
* RiverDogs @ Power
<2018-08-19 Sun 13:05-16:05>
:PROPERTIES:
:ID:       ShZtnD3lOQJXI6mw1MbJcvBC@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

RiverDogs @ Power RiverDogs @ Power

Follow on MiLB First Pitch  https //stza.co/+xJ3z-3l

Shop  https //stza.co/+xJ3z-_

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:RiverDogs @ Power
END:VALARM
DTSTART:20180819T180500Z
DTEND:20180819T210500Z
UID:ShZtnD3lOQJXI6mw1MbJcvBC@stanza.co
SUMMARY:RiverDogs @ Power
DESCRIPTION:RiverDogs @ Power\n\nFollow on MiLB First Pitch: https://stza.co/+xJ3z-3l\n\nShop: https://stza.co/+xJ3z-_\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144512Z
LAST-MODIFIED:20180213T144512Z
TRANSP:OPAQUE
END:VEVENT
* RiverDogs @ Power
<2018-08-20 Mon 18:05-21:05>
:PROPERTIES:
:ID:       wdU0zDYJ1CgtuMJsRyqoN2z2@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

RiverDogs @ Power RiverDogs @ Power

Follow on MiLB First Pitch  https //stza.co/+xJ3A-1m

Shop  https //stza.co/+xJ3A-r

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:RiverDogs @ Power
END:VALARM
DTSTART:20180820T230500Z
DTEND:20180821T020500Z
UID:wdU0zDYJ1CgtuMJsRyqoN2z2@stanza.co
SUMMARY:RiverDogs @ Power
DESCRIPTION:RiverDogs @ Power\n\nFollow on MiLB First Pitch: https://stza.co/+xJ3A-1m\n\nShop: https://stza.co/+xJ3A-r\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144512Z
LAST-MODIFIED:20180213T144512Z
TRANSP:OPAQUE
END:VEVENT
* RiverDogs @ Power
<2018-08-21 Tue 18:05-21:05>
:PROPERTIES:
:ID:       7yBCLJVrLWCHkBLmSrnPiPub@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

RiverDogs @ Power RiverDogs @ Power

Follow on MiLB First Pitch  https //stza.co/+xJ3B-3j

Shop  https //stza.co/+xJ3B-14

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:RiverDogs @ Power
END:VALARM
DTSTART:20180821T230500Z
DTEND:20180822T020500Z
UID:7yBCLJVrLWCHkBLmSrnPiPub@stanza.co
SUMMARY:RiverDogs @ Power
DESCRIPTION:RiverDogs @ Power\n\nFollow on MiLB First Pitch: https://stza.co/+xJ3B-3j\n\nShop: https://stza.co/+xJ3B-14\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144512Z
LAST-MODIFIED:20180213T144512Z
TRANSP:OPAQUE
END:VEVENT
* RiverDogs vs. Drive
<2018-08-23 Thu 18:05-21:05>
:PROPERTIES:
:ID:       yW-z78-_LFc_OgVnSoTYDODp@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

RiverDogs vs. Drive RiverDogs vs. Drive

Follow on MiLB First Pitch  https //stza.co/+vNBa-1s

Shop  https //stza.co/+vNBa-2g

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:RiverDogs vs. Drive
END:VALARM
DTSTART:20180823T230500Z
DTEND:20180824T020500Z
UID:yW-z78-_LFc_OgVnSoTYDODp@stanza.co
SUMMARY:RiverDogs vs. Drive
DESCRIPTION:RiverDogs vs. Drive\n\nFollow on MiLB First Pitch: https://stza.co/+vNBa-1s\n\nShop: https://stza.co/+vNBa-2g\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144512Z
LAST-MODIFIED:20180213T144512Z
TRANSP:OPAQUE
END:VEVENT
* RiverDogs vs. Drive
<2018-08-24 Fri 18:05-21:05>
:PROPERTIES:
:ID:       BRAEHCT5FwiIF73fAmup0J20@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

RiverDogs vs. Drive RiverDogs vs. Drive

Follow on MiLB First Pitch  https //stza.co/+vNBc-3o

Shop  https //stza.co/+vNBc-2E

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:RiverDogs vs. Drive
END:VALARM
DTSTART:20180824T230500Z
DTEND:20180825T020500Z
UID:BRAEHCT5FwiIF73fAmup0J20@stanza.co
SUMMARY:RiverDogs vs. Drive
DESCRIPTION:RiverDogs vs. Drive\n\nFollow on MiLB First Pitch: https://stza.co/+vNBc-3o\n\nShop: https://stza.co/+vNBc-2E\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144512Z
LAST-MODIFIED:20180213T144512Z
TRANSP:OPAQUE
END:VEVENT
* RiverDogs vs. Drive
<2018-08-25 Sat 17:05-20:05>
:PROPERTIES:
:ID:       P_KvZPYq3Lh5ByPC4TK-YETc@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

RiverDogs vs. Drive RiverDogs vs. Drive

Follow on MiLB First Pitch  https //stza.co/+vNBf-2y

Shop  https //stza.co/+vNBf-3r

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:RiverDogs vs. Drive
END:VALARM
DTSTART:20180825T220500Z
DTEND:20180826T010500Z
UID:P_KvZPYq3Lh5ByPC4TK-YETc@stanza.co
SUMMARY:RiverDogs vs. Drive
DESCRIPTION:RiverDogs vs. Drive\n\nFollow on MiLB First Pitch: https://stza.co/+vNBf-2y\n\nShop: https://stza.co/+vNBf-3r\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144512Z
LAST-MODIFIED:20180213T144512Z
TRANSP:OPAQUE
END:VEVENT
* RiverDogs vs. Drive
<2018-08-26 Sun 16:05-19:05>
:PROPERTIES:
:ID:       lDIAVt6yl_UtfN9i8JHMXFrj@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

RiverDogs vs. Drive RiverDogs vs. Drive

Follow on MiLB First Pitch  https //stza.co/+vNBh-1l

Shop  https //stza.co/+vNBh-1v

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:RiverDogs vs. Drive
END:VALARM
DTSTART:20180826T210500Z
DTEND:20180827T000500Z
UID:lDIAVt6yl_UtfN9i8JHMXFrj@stanza.co
SUMMARY:RiverDogs vs. Drive
DESCRIPTION:RiverDogs vs. Drive\n\nFollow on MiLB First Pitch: https://stza.co/+vNBh-1l\n\nShop: https://stza.co/+vNBh-1v\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144512Z
LAST-MODIFIED:20180213T144512Z
TRANSP:OPAQUE
END:VEVENT
* RiverDogs @ Fireflies
<2018-08-27 Mon 18:05-21:05>
:PROPERTIES:
:ID:       Wu0Lx0CoN75X43mB4xn3mZiy@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

RiverDogs @ Fireflies RiverDogs @ Fireflies

Follow on MiLB First Pitch  https //stza.co/+xBM6-3M

Shop  https //stza.co/+xBM6-q

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:RiverDogs @ Fireflies
END:VALARM
DTSTART:20180827T230500Z
DTEND:20180828T020500Z
UID:Wu0Lx0CoN75X43mB4xn3mZiy@stanza.co
SUMMARY:RiverDogs @ Fireflies
DESCRIPTION:RiverDogs @ Fireflies\n\nFollow on MiLB First Pitch: https://stza.co/+xBM6-3M\n\nShop: https://stza.co/+xBM6-q\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144512Z
LAST-MODIFIED:20180213T144512Z
TRANSP:OPAQUE
END:VEVENT
* RiverDogs @ Fireflies
<2018-08-28 Tue 18:05-21:05>
:PROPERTIES:
:ID:       Y-OvRGGRLnrv8Isas_yWlLoj@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

RiverDogs @ Fireflies RiverDogs @ Fireflies

Follow on MiLB First Pitch  https //stza.co/+xBMa-a

Shop  https //stza.co/+xBMa-2C

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:RiverDogs @ Fireflies
END:VALARM
DTSTART:20180828T230500Z
DTEND:20180829T020500Z
UID:Y-OvRGGRLnrv8Isas_yWlLoj@stanza.co
SUMMARY:RiverDogs @ Fireflies
DESCRIPTION:RiverDogs @ Fireflies\n\nFollow on MiLB First Pitch: https://stza.co/+xBMa-a\n\nShop: https://stza.co/+xBMa-2C\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144512Z
LAST-MODIFIED:20180213T144512Z
TRANSP:OPAQUE
END:VEVENT
* RiverDogs @ Fireflies
<2018-08-29 Wed 18:05-21:05>
:PROPERTIES:
:ID:       fcjKza3MVjUOomb_sJeYJQZv@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

RiverDogs @ Fireflies RiverDogs @ Fireflies

Follow on MiLB First Pitch  https //stza.co/+xBMd-f

Shop  https //stza.co/+xBMd-

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:RiverDogs @ Fireflies
END:VALARM
DTSTART:20180829T230500Z
DTEND:20180830T020500Z
UID:fcjKza3MVjUOomb_sJeYJQZv@stanza.co
SUMMARY:RiverDogs @ Fireflies
DESCRIPTION:RiverDogs @ Fireflies\n\nFollow on MiLB First Pitch: https://stza.co/+xBMd-f\n\nShop: https://stza.co/+xBMd-\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144512Z
LAST-MODIFIED:20180213T144512Z
TRANSP:OPAQUE
END:VEVENT
* RiverDogs @ Fireflies
<2018-08-30 Thu 18:05-21:05>
:PROPERTIES:
:ID:       5d75DVzmKBu_iKXalEWYXGrp@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

RiverDogs @ Fireflies RiverDogs @ Fireflies

Follow on MiLB First Pitch  https //stza.co/+xAWf-N

Shop  https //stza.co/+xAWf-1L

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:RiverDogs @ Fireflies
END:VALARM
DTSTART:20180830T230500Z
DTEND:20180831T020500Z
UID:5d75DVzmKBu_iKXalEWYXGrp@stanza.co
SUMMARY:RiverDogs @ Fireflies
DESCRIPTION:RiverDogs @ Fireflies\n\nFollow on MiLB First Pitch: https://stza.co/+xAWf-N\n\nShop: https://stza.co/+xAWf-1L\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144512Z
LAST-MODIFIED:20180213T144512Z
TRANSP:OPAQUE
END:VEVENT
* RiverDogs vs. Power
<2018-08-31 Fri 18:05-21:05>
:PROPERTIES:
:ID:       HkEtAPVTvvtH_drS8h-Lya1r@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

RiverDogs vs. Power RiverDogs vs. Power

Follow on MiLB First Pitch  https //stza.co/+vNBi-1b

Shop  https //stza.co/+vNBi-H

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:RiverDogs vs. Power
END:VALARM
DTSTART:20180831T230500Z
DTEND:20180901T020500Z
UID:HkEtAPVTvvtH_drS8h-Lya1r@stanza.co
SUMMARY:RiverDogs vs. Power
DESCRIPTION:RiverDogs vs. Power\n\nFollow on MiLB First Pitch: https://stza.co/+vNBi-1b\n\nShop: https://stza.co/+vNBi-H\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144512Z
LAST-MODIFIED:20180213T144512Z
TRANSP:OPAQUE
END:VEVENT
* RiverDogs vs. Power
<2018-09-01 Sat 17:05-20:05>
:PROPERTIES:
:ID:       KJHGvh9PyjyVpgCW4f3_3Wlx@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

RiverDogs vs. Power RiverDogs vs. Power

Follow on MiLB First Pitch  https //stza.co/+vNBk-2Y

Shop  https //stza.co/+vNBk-2c

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:RiverDogs vs. Power
END:VALARM
DTSTART:20180901T220500Z
DTEND:20180902T010500Z
UID:KJHGvh9PyjyVpgCW4f3_3Wlx@stanza.co
SUMMARY:RiverDogs vs. Power
DESCRIPTION:RiverDogs vs. Power\n\nFollow on MiLB First Pitch: https://stza.co/+vNBk-2Y\n\nShop: https://stza.co/+vNBk-2c\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144512Z
LAST-MODIFIED:20180213T144512Z
TRANSP:OPAQUE
END:VEVENT
* RiverDogs vs. Power
<2018-09-02 Sun 16:05-19:05>
:PROPERTIES:
:ID:       TbMlPG5Wog77DZ0jKC29999o@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

RiverDogs vs. Power RiverDogs vs. Power

Follow on MiLB First Pitch  https //stza.co/+vNBm-2d

Shop  https //stza.co/+vNBm-2Q

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:RiverDogs vs. Power
END:VALARM
DTSTART:20180902T210500Z
DTEND:20180903T000500Z
UID:TbMlPG5Wog77DZ0jKC29999o@stanza.co
SUMMARY:RiverDogs vs. Power
DESCRIPTION:RiverDogs vs. Power\n\nFollow on MiLB First Pitch: https://stza.co/+vNBm-2d\n\nShop: https://stza.co/+vNBm-2Q\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144512Z
LAST-MODIFIED:20180213T144512Z
TRANSP:OPAQUE
END:VEVENT
* RiverDogs vs. Power
<2018-09-03 Mon 13:05-16:05>
:PROPERTIES:
:ID:       P3jkLcZahLEvNMms649ZvRnU@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

RiverDogs vs. Power RiverDogs vs. Power

Follow on MiLB First Pitch  https //stza.co/+vNBo-2v

Shop  https //stza.co/+vNBo-1N

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:RiverDogs vs. Power
END:VALARM
DTSTART:20180903T180500Z
DTEND:20180903T210500Z
UID:P3jkLcZahLEvNMms649ZvRnU@stanza.co
SUMMARY:RiverDogs vs. Power
DESCRIPTION:RiverDogs vs. Power\n\nFollow on MiLB First Pitch: https://stza.co/+vNBo-2v\n\nShop: https://stza.co/+vNBo-1N\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144512Z
LAST-MODIFIED:20180213T144512Z
TRANSP:OPAQUE
END:VEVENT
