#+TITLE:       Main Google calendar entries
#+AUTHOR:      Eric S Fraga
#+EMAIL:       e.fraga@ucl.ac.uk
#+DESCRIPTION: converted using the ical2org awk script
#+CATEGORY:    google
#+STARTUP:     hidestars
#+STARTUP:     overview

* COMMENT original iCal preamble

* Express vs. Redbirds
<2018-04-05 Thu 19:05-22:05>
:PROPERTIES:
:ID:       1XEK5dvRLAP_XK3ZefS7GZil@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Express vs. Redbirds Express vs. Redbirds

Follow on MiLB First Pitch  https //stza.co/+vKWW-r

Shop  https //stza.co/+vKWW-1e

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Express vs. Redbirds
END:VALARM
DTSTART:20180406T000500Z
DTEND:20180406T030500Z
UID:1XEK5dvRLAP_XK3ZefS7GZil@stanza.co
SUMMARY:Express vs. Redbirds
DESCRIPTION:Express vs. Redbirds\n\nFollow on MiLB First Pitch: https://stza.co/+vKWW-r\n\nShop: https://stza.co/+vKWW-1e\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144555Z
LAST-MODIFIED:20180213T144555Z
TRANSP:OPAQUE
END:VEVENT
* Express vs. Redbirds
<2018-04-06 Fri 19:05-22:05>
:PROPERTIES:
:ID:       heFwDxcoo7ULzzXVREgsN8Aw@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Express vs. Redbirds Express vs. Redbirds

Follow on MiLB First Pitch  https //stza.co/+vKWY-w

Shop  https //stza.co/+vKWY-2K

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Express vs. Redbirds
END:VALARM
DTSTART:20180407T000500Z
DTEND:20180407T030500Z
UID:heFwDxcoo7ULzzXVREgsN8Aw@stanza.co
SUMMARY:Express vs. Redbirds
DESCRIPTION:Express vs. Redbirds\n\nFollow on MiLB First Pitch: https://stza.co/+vKWY-w\n\nShop: https://stza.co/+vKWY-2K\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144555Z
LAST-MODIFIED:20180213T144555Z
TRANSP:OPAQUE
END:VEVENT
* Express vs. Redbirds
<2018-04-07 Sat 18:05-21:05>
:PROPERTIES:
:ID:       kMQQ6ubdV6q_4yauaNCdn2uS@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Express vs. Redbirds Express vs. Redbirds

Follow on MiLB First Pitch  https //stza.co/+vKW_-P

Shop  https //stza.co/+vKW_-1s

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Express vs. Redbirds
END:VALARM
DTSTART:20180407T230500Z
DTEND:20180408T020500Z
UID:kMQQ6ubdV6q_4yauaNCdn2uS@stanza.co
SUMMARY:Express vs. Redbirds
DESCRIPTION:Express vs. Redbirds\n\nFollow on MiLB First Pitch: https://stza.co/+vKW_-P\n\nShop: https://stza.co/+vKW_-1s\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144555Z
LAST-MODIFIED:20180213T144555Z
TRANSP:OPAQUE
END:VEVENT
* Express vs. Redbirds
<2018-04-08 Sun 13:05-16:05>
:PROPERTIES:
:ID:       A1rPkqDAzsUGUb03lZmYchon@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Express vs. Redbirds Express vs. Redbirds

Follow on MiLB First Pitch  https //stza.co/+vKW$-1J

Shop  https //stza.co/+vKW$-2I

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Express vs. Redbirds
END:VALARM
DTSTART:20180408T180500Z
DTEND:20180408T210500Z
UID:A1rPkqDAzsUGUb03lZmYchon@stanza.co
SUMMARY:Express vs. Redbirds
DESCRIPTION:Express vs. Redbirds\n\nFollow on MiLB First Pitch: https://stza.co/+vKW$-1J\n\nShop: https://stza.co/+vKW$-2I\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144555Z
LAST-MODIFIED:20180213T144555Z
TRANSP:OPAQUE
END:VEVENT
* Express vs. Redbirds
<2018-04-09 Mon 19:05-22:05>
:PROPERTIES:
:ID:       zJFHiqYJsbjKWBFIqd8PRwrv@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Express vs. Redbirds Express vs. Redbirds

Follow on MiLB First Pitch  https //stza.co/+vKX2-3Q

Shop  https //stza.co/+vKX2-A

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Express vs. Redbirds
END:VALARM
DTSTART:20180410T000500Z
DTEND:20180410T030500Z
UID:zJFHiqYJsbjKWBFIqd8PRwrv@stanza.co
SUMMARY:Express vs. Redbirds
DESCRIPTION:Express vs. Redbirds\n\nFollow on MiLB First Pitch: https://stza.co/+vKX2-3Q\n\nShop: https://stza.co/+vKX2-A\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144555Z
LAST-MODIFIED:20180213T144555Z
TRANSP:OPAQUE
END:VEVENT
* Express @ Dodgers
<2018-04-10 Tue 19:05-22:05>
:PROPERTIES:
:ID:       c9wWliyA-VV_rsR22OKBVw9g@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Express @ Dodgers Express @ Dodgers

Follow on MiLB First Pitch  https //stza.co/+v$P9-h

Shop  https //stza.co/+v$P9-3e

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Express @ Dodgers
END:VALARM
DTSTART:20180411T000500Z
DTEND:20180411T030500Z
UID:c9wWliyA-VV_rsR22OKBVw9g@stanza.co
SUMMARY:Express @ Dodgers
DESCRIPTION:Express @ Dodgers\n\nFollow on MiLB First Pitch: https://stza.co/+v$P9-h\n\nShop: https://stza.co/+v$P9-3e\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144555Z
LAST-MODIFIED:20180213T144555Z
TRANSP:OPAQUE
END:VEVENT
* Express @ Dodgers
<2018-04-11 Wed 19:05-22:05>
:PROPERTIES:
:ID:       edzbYs1PjGhA04C-Jc1jsd9t@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Express @ Dodgers Express @ Dodgers

Follow on MiLB First Pitch  https //stza.co/+v$Pa-2O

Shop  https //stza.co/+v$Pa-1i

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Express @ Dodgers
END:VALARM
DTSTART:20180412T000500Z
DTEND:20180412T030500Z
UID:edzbYs1PjGhA04C-Jc1jsd9t@stanza.co
SUMMARY:Express @ Dodgers
DESCRIPTION:Express @ Dodgers\n\nFollow on MiLB First Pitch: https://stza.co/+v$Pa-2O\n\nShop: https://stza.co/+v$Pa-1i\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144555Z
LAST-MODIFIED:20180213T144555Z
TRANSP:OPAQUE
END:VEVENT
* Express @ Dodgers
<2018-04-12 Thu 19:05-22:05>
:PROPERTIES:
:ID:       9h9YchvKcQ9t1-mfXV12Rm-m@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Express @ Dodgers Express @ Dodgers

Follow on MiLB First Pitch  https //stza.co/+v$Pb-1S

Shop  https //stza.co/+v$Pb-1N

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Express @ Dodgers
END:VALARM
DTSTART:20180413T000500Z
DTEND:20180413T030500Z
UID:9h9YchvKcQ9t1-mfXV12Rm-m@stanza.co
SUMMARY:Express @ Dodgers
DESCRIPTION:Express @ Dodgers\n\nFollow on MiLB First Pitch: https://stza.co/+v$Pb-1S\n\nShop: https://stza.co/+v$Pb-1N\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144555Z
LAST-MODIFIED:20180213T144555Z
TRANSP:OPAQUE
END:VEVENT
* Express @ Sky Sox
<2018-04-13 Fri 19:40-22:40>
:PROPERTIES:
:ID:       x-Q8MkS6HKwt-1jVbLyTbcFq@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Express @ Sky Sox Express @ Sky Sox

Follow on MiLB First Pitch  https //stza.co/+wmLu-Q

Shop  https //stza.co/+wmLu-3v

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Express @ Sky Sox
END:VALARM
DTSTART:20180414T004000Z
DTEND:20180414T034000Z
UID:x-Q8MkS6HKwt-1jVbLyTbcFq@stanza.co
SUMMARY:Express @ Sky Sox
DESCRIPTION:Express @ Sky Sox\n\nFollow on MiLB First Pitch: https://stza.co/+wmLu-Q\n\nShop: https://stza.co/+wmLu-3v\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144555Z
LAST-MODIFIED:20180213T144555Z
TRANSP:OPAQUE
END:VEVENT
* Express @ Sky Sox
<2018-04-14 Sat 17:00-20:00>
:PROPERTIES:
:ID:       hi8TnSegbStlkeuW4Ueawth9@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Express @ Sky Sox Express @ Sky Sox

Follow on MiLB First Pitch  https //stza.co/+wmLv-S

Shop  https //stza.co/+wmLv-2Y

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Express @ Sky Sox
END:VALARM
DTSTART:20180414T220000Z
DTEND:20180415T010000Z
UID:hi8TnSegbStlkeuW4Ueawth9@stanza.co
SUMMARY:Express @ Sky Sox
DESCRIPTION:Express @ Sky Sox\n\nFollow on MiLB First Pitch: https://stza.co/+wmLv-S\n\nShop: https://stza.co/+wmLv-2Y\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144555Z
LAST-MODIFIED:20180213T144555Z
TRANSP:OPAQUE
END:VEVENT
* Express @ Sky Sox
<2018-04-15 Sun 14:30-17:30>
:PROPERTIES:
:ID:       KB-yEkVt41CtGbZz--4F6r1h@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Express @ Sky Sox Express @ Sky Sox

Follow on MiLB First Pitch  https //stza.co/+wmLw-z

Shop  https //stza.co/+wmLw-2S

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Express @ Sky Sox
END:VALARM
DTSTART:20180415T193000Z
DTEND:20180415T223000Z
UID:KB-yEkVt41CtGbZz--4F6r1h@stanza.co
SUMMARY:Express @ Sky Sox
DESCRIPTION:Express @ Sky Sox\n\nFollow on MiLB First Pitch: https://stza.co/+wmLw-z\n\nShop: https://stza.co/+wmLw-2S\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144555Z
LAST-MODIFIED:20180213T144555Z
TRANSP:OPAQUE
END:VEVENT
* Express @ Sky Sox
<2018-04-16 Mon 12:05-15:05>
:PROPERTIES:
:ID:       qNGXPs1UfhKh4hXMyDPmmqyH@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Express @ Sky Sox Express @ Sky Sox

Follow on MiLB First Pitch  https //stza.co/+wmLx-O

Shop  https //stza.co/+wmLx-1s

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Express @ Sky Sox
END:VALARM
DTSTART:20180416T170500Z
DTEND:20180416T200500Z
UID:qNGXPs1UfhKh4hXMyDPmmqyH@stanza.co
SUMMARY:Express @ Sky Sox
DESCRIPTION:Express @ Sky Sox\n\nFollow on MiLB First Pitch: https://stza.co/+wmLx-O\n\nShop: https://stza.co/+wmLx-1s\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144555Z
LAST-MODIFIED:20180213T144555Z
TRANSP:OPAQUE
END:VEVENT
* Express vs. Dodgers
<2018-04-17 Tue 19:05-22:05>
:PROPERTIES:
:ID:       3XML4R5eGaRYRNFdW4BSGVKx@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Express vs. Dodgers Express vs. Dodgers

Follow on MiLB First Pitch  https //stza.co/+vKX4-17

Shop  https //stza.co/+vKX4-1z

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Express vs. Dodgers
END:VALARM
DTSTART:20180418T000500Z
DTEND:20180418T030500Z
UID:3XML4R5eGaRYRNFdW4BSGVKx@stanza.co
SUMMARY:Express vs. Dodgers
DESCRIPTION:Express vs. Dodgers\n\nFollow on MiLB First Pitch: https://stza.co/+vKX4-17\n\nShop: https://stza.co/+vKX4-1z\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144555Z
LAST-MODIFIED:20180213T144555Z
TRANSP:OPAQUE
END:VEVENT
* Express vs. Dodgers
<2018-04-18 Wed 11:35-14:35>
:PROPERTIES:
:ID:       3otIXDGwUNhYgFGvDihwNELv@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Express vs. Dodgers Express vs. Dodgers

Follow on MiLB First Pitch  https //stza.co/+vKX5-33

Shop  https //stza.co/+vKX5-Y

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Express vs. Dodgers
END:VALARM
DTSTART:20180418T163500Z
DTEND:20180418T193500Z
UID:3otIXDGwUNhYgFGvDihwNELv@stanza.co
SUMMARY:Express vs. Dodgers
DESCRIPTION:Express vs. Dodgers\n\nFollow on MiLB First Pitch: https://stza.co/+vKX5-33\n\nShop: https://stza.co/+vKX5-Y\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144555Z
LAST-MODIFIED:20180213T144555Z
TRANSP:OPAQUE
END:VEVENT
* Express vs. Dodgers
<2018-04-19 Thu 19:05-22:05>
:PROPERTIES:
:ID:       YaZ0qFf51lVpjIP6hSOFR-4N@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Express vs. Dodgers Express vs. Dodgers

Follow on MiLB First Pitch  https //stza.co/+vKX8-T

Shop  https //stza.co/+vKX8-1j

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Express vs. Dodgers
END:VALARM
DTSTART:20180420T000500Z
DTEND:20180420T030500Z
UID:YaZ0qFf51lVpjIP6hSOFR-4N@stanza.co
SUMMARY:Express vs. Dodgers
DESCRIPTION:Express vs. Dodgers\n\nFollow on MiLB First Pitch: https://stza.co/+vKX8-T\n\nShop: https://stza.co/+vKX8-1j\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144555Z
LAST-MODIFIED:20180213T144555Z
TRANSP:OPAQUE
END:VEVENT
* Express vs. Dodgers
<2018-04-20 Fri 19:05-22:05>
:PROPERTIES:
:ID:       5ZomYgaV9LGUbYO0bKAV-L1F@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Express vs. Dodgers Express vs. Dodgers

Follow on MiLB First Pitch  https //stza.co/+vKXa-1a

Shop  https //stza.co/+vKXa-1k

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Express vs. Dodgers
END:VALARM
DTSTART:20180421T000500Z
DTEND:20180421T030500Z
UID:5ZomYgaV9LGUbYO0bKAV-L1F@stanza.co
SUMMARY:Express vs. Dodgers
DESCRIPTION:Express vs. Dodgers\n\nFollow on MiLB First Pitch: https://stza.co/+vKXa-1a\n\nShop: https://stza.co/+vKXa-1k\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144555Z
LAST-MODIFIED:20180213T144555Z
TRANSP:OPAQUE
END:VEVENT
* Express vs. Sky Sox
<2018-04-21 Sat 19:05-22:05>
:PROPERTIES:
:ID:       EBgMTBOoBNSNOQk3Ob63FTnR@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Express vs. Sky Sox Express vs. Sky Sox

Follow on MiLB First Pitch  https //stza.co/+vKXc-3L

Shop  https //stza.co/+vKXc-E

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Express vs. Sky Sox
END:VALARM
DTSTART:20180422T000500Z
DTEND:20180422T030500Z
UID:EBgMTBOoBNSNOQk3Ob63FTnR@stanza.co
SUMMARY:Express vs. Sky Sox
DESCRIPTION:Express vs. Sky Sox\n\nFollow on MiLB First Pitch: https://stza.co/+vKXc-3L\n\nShop: https://stza.co/+vKXc-E\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144555Z
LAST-MODIFIED:20180213T144555Z
TRANSP:OPAQUE
END:VEVENT
* Express vs. Sky Sox
<2018-04-22 Sun 13:05-16:05>
:PROPERTIES:
:ID:       Qd-d59KjBeE92U4ZD87hyeJG@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Express vs. Sky Sox Express vs. Sky Sox

Follow on MiLB First Pitch  https //stza.co/+vKXd-z

Shop  https //stza.co/+vKXd-2Z

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Express vs. Sky Sox
END:VALARM
DTSTART:20180422T180500Z
DTEND:20180422T210500Z
UID:Qd-d59KjBeE92U4ZD87hyeJG@stanza.co
SUMMARY:Express vs. Sky Sox
DESCRIPTION:Express vs. Sky Sox\n\nFollow on MiLB First Pitch: https://stza.co/+vKXd-z\n\nShop: https://stza.co/+vKXd-2Z\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144555Z
LAST-MODIFIED:20180213T144555Z
TRANSP:OPAQUE
END:VEVENT
* Express vs. Sky Sox
<2018-04-23 Mon 19:05-22:05>
:PROPERTIES:
:ID:       bSBU10CdaPD9el56sHXhhXyM@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Express vs. Sky Sox Express vs. Sky Sox

Follow on MiLB First Pitch  https //stza.co/+vKXg-8

Shop  https //stza.co/+vKXg-3X

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Express vs. Sky Sox
END:VALARM
DTSTART:20180424T000500Z
DTEND:20180424T030500Z
UID:bSBU10CdaPD9el56sHXhhXyM@stanza.co
SUMMARY:Express vs. Sky Sox
DESCRIPTION:Express vs. Sky Sox\n\nFollow on MiLB First Pitch: https://stza.co/+vKXg-8\n\nShop: https://stza.co/+vKXg-3X\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144555Z
LAST-MODIFIED:20180213T144555Z
TRANSP:OPAQUE
END:VEVENT
* Express @ Redbirds
<2018-04-25 Wed 18:35-21:35>
:PROPERTIES:
:ID:       kdZb4dldP3HxepaAHEgxoz9H@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Express @ Redbirds Express @ Redbirds

Follow on MiLB First Pitch  https //stza.co/+wmLG-C

Shop  https //stza.co/+wmLG-1C

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Express @ Redbirds
END:VALARM
DTSTART:20180425T233500Z
DTEND:20180426T023500Z
UID:kdZb4dldP3HxepaAHEgxoz9H@stanza.co
SUMMARY:Express @ Redbirds
DESCRIPTION:Express @ Redbirds\n\nFollow on MiLB First Pitch: https://stza.co/+wmLG-C\n\nShop: https://stza.co/+wmLG-1C\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144555Z
LAST-MODIFIED:20180213T144555Z
TRANSP:OPAQUE
END:VEVENT
* Express @ Redbirds
<2018-04-26 Thu 19:05-22:05>
:PROPERTIES:
:ID:       AzKu4VTeU0e30LJxxwU00ewV@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Express @ Redbirds Express @ Redbirds

Follow on MiLB First Pitch  https //stza.co/+wmLH-1c

Shop  https //stza.co/+wmLH-2v

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Express @ Redbirds
END:VALARM
DTSTART:20180427T000500Z
DTEND:20180427T030500Z
UID:AzKu4VTeU0e30LJxxwU00ewV@stanza.co
SUMMARY:Express @ Redbirds
DESCRIPTION:Express @ Redbirds\n\nFollow on MiLB First Pitch: https://stza.co/+wmLH-1c\n\nShop: https://stza.co/+wmLH-2v\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144555Z
LAST-MODIFIED:20180213T144555Z
TRANSP:OPAQUE
END:VEVENT
* Express @ Redbirds
<2018-04-27 Fri 19:05-22:05>
:PROPERTIES:
:ID:       ErIpN-e-M9b5sSQ54qb0yRze@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Express @ Redbirds Express @ Redbirds

Follow on MiLB First Pitch  https //stza.co/+wmLI-3T

Shop  https //stza.co/+wmLI-2o

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Express @ Redbirds
END:VALARM
DTSTART:20180428T000500Z
DTEND:20180428T030500Z
UID:ErIpN-e-M9b5sSQ54qb0yRze@stanza.co
SUMMARY:Express @ Redbirds
DESCRIPTION:Express @ Redbirds\n\nFollow on MiLB First Pitch: https://stza.co/+wmLI-3T\n\nShop: https://stza.co/+wmLI-2o\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144555Z
LAST-MODIFIED:20180213T144555Z
TRANSP:OPAQUE
END:VEVENT
* Express @ Redbirds
<2018-04-28 Sat 18:35-21:35>
:PROPERTIES:
:ID:       czxyK23LJ-M2ftUE95PYteGC@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Express @ Redbirds Express @ Redbirds

Follow on MiLB First Pitch  https //stza.co/+wmLJ-1a

Shop  https //stza.co/+wmLJ-1i

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Express @ Redbirds
END:VALARM
DTSTART:20180428T233500Z
DTEND:20180429T023500Z
UID:czxyK23LJ-M2ftUE95PYteGC@stanza.co
SUMMARY:Express @ Redbirds
DESCRIPTION:Express @ Redbirds\n\nFollow on MiLB First Pitch: https://stza.co/+wmLJ-1a\n\nShop: https://stza.co/+wmLJ-1i\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144555Z
LAST-MODIFIED:20180213T144555Z
TRANSP:OPAQUE
END:VEVENT
* Express @ Redbirds
<2018-04-29 Sun 14:05-17:05>
:PROPERTIES:
:ID:       ka61GNCq5vGEYCIgP5aazBOs@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Express @ Redbirds Express @ Redbirds

Follow on MiLB First Pitch  https //stza.co/+wmLK-2t

Shop  https //stza.co/+wmLK-2s

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Express @ Redbirds
END:VALARM
DTSTART:20180429T190500Z
DTEND:20180429T220500Z
UID:ka61GNCq5vGEYCIgP5aazBOs@stanza.co
SUMMARY:Express @ Redbirds
DESCRIPTION:Express @ Redbirds\n\nFollow on MiLB First Pitch: https://stza.co/+wmLK-2t\n\nShop: https://stza.co/+wmLK-2s\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144555Z
LAST-MODIFIED:20180213T144555Z
TRANSP:OPAQUE
END:VEVENT
* Express @ Baby Cakes
<2018-04-30 Mon 19:00-22:00>
:PROPERTIES:
:ID:       OtgOHz0qQnvDGic5F3FRhIgW@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Express @ Baby Cakes Express @ Baby Cakes

Follow on MiLB First Pitch  https //stza.co/+whQo-W

Shop  https //stza.co/+whQo-26

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Express @ Baby Cakes
END:VALARM
DTSTART:20180501T000000Z
DTEND:20180501T030000Z
UID:OtgOHz0qQnvDGic5F3FRhIgW@stanza.co
SUMMARY:Express @ Baby Cakes
DESCRIPTION:Express @ Baby Cakes\n\nFollow on MiLB First Pitch: https://stza.co/+whQo-W\n\nShop: https://stza.co/+whQo-26\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144555Z
LAST-MODIFIED:20180213T144555Z
TRANSP:OPAQUE
END:VEVENT
* Express @ Baby Cakes
<2018-05-01 Tue 19:00-22:00>
:PROPERTIES:
:ID:       LsBt6evLYYVJb2TkPcHuKkU7@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Express @ Baby Cakes Express @ Baby Cakes

Follow on MiLB First Pitch  https //stza.co/+whQp-3H

Shop  https //stza.co/+whQp-2A

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Express @ Baby Cakes
END:VALARM
DTSTART:20180502T000000Z
DTEND:20180502T030000Z
UID:LsBt6evLYYVJb2TkPcHuKkU7@stanza.co
SUMMARY:Express @ Baby Cakes
DESCRIPTION:Express @ Baby Cakes\n\nFollow on MiLB First Pitch: https://stza.co/+whQp-3H\n\nShop: https://stza.co/+whQp-2A\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144555Z
LAST-MODIFIED:20180213T144555Z
TRANSP:OPAQUE
END:VEVENT
* Express @ Baby Cakes
<2018-05-02 Wed 12:00-15:00>
:PROPERTIES:
:ID:       iXWJor9uaGc68WOXYN0afxOl@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Express @ Baby Cakes Express @ Baby Cakes

Follow on MiLB First Pitch  https //stza.co/+whQq-1B

Shop  https //stza.co/+whQq-3B

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Express @ Baby Cakes
END:VALARM
DTSTART:20180502T170000Z
DTEND:20180502T200000Z
UID:iXWJor9uaGc68WOXYN0afxOl@stanza.co
SUMMARY:Express @ Baby Cakes
DESCRIPTION:Express @ Baby Cakes\n\nFollow on MiLB First Pitch: https://stza.co/+whQq-1B\n\nShop: https://stza.co/+whQq-3B\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144555Z
LAST-MODIFIED:20180213T144555Z
TRANSP:OPAQUE
END:VEVENT
* Express @ Baby Cakes
<2018-05-03 Thu 19:00-22:00>
:PROPERTIES:
:ID:       2fyJK-s_wohskbidkcgcyDRO@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Express @ Baby Cakes Express @ Baby Cakes

Follow on MiLB First Pitch  https //stza.co/+whQr-X

Shop  https //stza.co/+whQr-B

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Express @ Baby Cakes
END:VALARM
DTSTART:20180504T000000Z
DTEND:20180504T030000Z
UID:2fyJK-s_wohskbidkcgcyDRO@stanza.co
SUMMARY:Express @ Baby Cakes
DESCRIPTION:Express @ Baby Cakes\n\nFollow on MiLB First Pitch: https://stza.co/+whQr-X\n\nShop: https://stza.co/+whQr-B\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144555Z
LAST-MODIFIED:20180213T144555Z
TRANSP:OPAQUE
END:VEVENT
* Express vs. Cubs
<2018-05-04 Fri 19:05-22:05>
:PROPERTIES:
:ID:       ueqM5ZXxElTJU3uzkyYVtZKE@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Express vs. Cubs Express vs. Cubs

Follow on MiLB First Pitch  https //stza.co/+vKXi-3N

Shop  https //stza.co/+vKXi-2F

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Express vs. Cubs
END:VALARM
DTSTART:20180505T000500Z
DTEND:20180505T030500Z
UID:ueqM5ZXxElTJU3uzkyYVtZKE@stanza.co
SUMMARY:Express vs. Cubs
DESCRIPTION:Express vs. Cubs\n\nFollow on MiLB First Pitch: https://stza.co/+vKXi-3N\n\nShop: https://stza.co/+vKXi-2F\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144555Z
LAST-MODIFIED:20180213T144555Z
TRANSP:OPAQUE
END:VEVENT
* Express vs. Cubs
<2018-05-05 Sat 18:05-21:05>
:PROPERTIES:
:ID:       v0qRCQ-yYeLMVguGJCVboloY@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Express vs. Cubs Express vs. Cubs

Follow on MiLB First Pitch  https //stza.co/+vKXk-2c

Shop  https //stza.co/+vKXk-1j

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Express vs. Cubs
END:VALARM
DTSTART:20180505T230500Z
DTEND:20180506T020500Z
UID:v0qRCQ-yYeLMVguGJCVboloY@stanza.co
SUMMARY:Express vs. Cubs
DESCRIPTION:Express vs. Cubs\n\nFollow on MiLB First Pitch: https://stza.co/+vKXk-2c\n\nShop: https://stza.co/+vKXk-1j\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144555Z
LAST-MODIFIED:20180213T144555Z
TRANSP:OPAQUE
END:VEVENT
* Express vs. Cubs
<2018-05-06 Sun 13:05-16:05>
:PROPERTIES:
:ID:       wCN914oKtKym7izzPhxOC_IY@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Express vs. Cubs Express vs. Cubs

Follow on MiLB First Pitch  https //stza.co/+vKXm-34

Shop  https //stza.co/+vKXm-1C

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Express vs. Cubs
END:VALARM
DTSTART:20180506T180500Z
DTEND:20180506T210500Z
UID:wCN914oKtKym7izzPhxOC_IY@stanza.co
SUMMARY:Express vs. Cubs
DESCRIPTION:Express vs. Cubs\n\nFollow on MiLB First Pitch: https://stza.co/+vKXm-34\n\nShop: https://stza.co/+vKXm-1C\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144555Z
LAST-MODIFIED:20180213T144555Z
TRANSP:OPAQUE
END:VEVENT
* Express vs. Cubs
<2018-05-07 Mon 19:05-22:05>
:PROPERTIES:
:ID:       Abf1EL1igumoACQ5IbgF-ARS@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Express vs. Cubs Express vs. Cubs

Follow on MiLB First Pitch  https //stza.co/+vKXo-3z

Shop  https //stza.co/+vKXo-2N

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Express vs. Cubs
END:VALARM
DTSTART:20180508T000500Z
DTEND:20180508T030500Z
UID:Abf1EL1igumoACQ5IbgF-ARS@stanza.co
SUMMARY:Express vs. Cubs
DESCRIPTION:Express vs. Cubs\n\nFollow on MiLB First Pitch: https://stza.co/+vKXo-3z\n\nShop: https://stza.co/+vKXo-2N\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144555Z
LAST-MODIFIED:20180213T144555Z
TRANSP:OPAQUE
END:VEVENT
* Express vs. Baby Cakes
<2018-05-08 Tue 19:05-22:05>
:PROPERTIES:
:ID:       atx2z7LLYiaGJ2XJI-qWlm9l@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Express vs. Baby Cakes Express vs. Baby Cakes

Follow on MiLB First Pitch  https //stza.co/+vKXp-2S

Shop  https //stza.co/+vKXp-3C

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Express vs. Baby Cakes
END:VALARM
DTSTART:20180509T000500Z
DTEND:20180509T030500Z
UID:atx2z7LLYiaGJ2XJI-qWlm9l@stanza.co
SUMMARY:Express vs. Baby Cakes
DESCRIPTION:Express vs. Baby Cakes\n\nFollow on MiLB First Pitch: https://stza.co/+vKXp-2S\n\nShop: https://stza.co/+vKXp-3C\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144555Z
LAST-MODIFIED:20180213T144555Z
TRANSP:OPAQUE
END:VEVENT
* Express vs. Baby Cakes
<2018-05-09 Wed 19:05-22:05>
:PROPERTIES:
:ID:       dlfDMOS1gfxM6ZKUhDp-2vxW@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Express vs. Baby Cakes Express vs. Baby Cakes

Follow on MiLB First Pitch  https //stza.co/+vKXr-2B

Shop  https //stza.co/+vKXr-y

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Express vs. Baby Cakes
END:VALARM
DTSTART:20180510T000500Z
DTEND:20180510T030500Z
UID:dlfDMOS1gfxM6ZKUhDp-2vxW@stanza.co
SUMMARY:Express vs. Baby Cakes
DESCRIPTION:Express vs. Baby Cakes\n\nFollow on MiLB First Pitch: https://stza.co/+vKXr-2B\n\nShop: https://stza.co/+vKXr-y\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144555Z
LAST-MODIFIED:20180213T144555Z
TRANSP:OPAQUE
END:VEVENT
* Express vs. Baby Cakes
<2018-05-10 Thu 19:05-22:05>
:PROPERTIES:
:ID:       4EZI427VI2T2UP45IFoUTpFp@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Express vs. Baby Cakes Express vs. Baby Cakes

Follow on MiLB First Pitch  https //stza.co/+vKXt-3A

Shop  https //stza.co/+vKXt-3N

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Express vs. Baby Cakes
END:VALARM
DTSTART:20180511T000500Z
DTEND:20180511T030500Z
UID:4EZI427VI2T2UP45IFoUTpFp@stanza.co
SUMMARY:Express vs. Baby Cakes
DESCRIPTION:Express vs. Baby Cakes\n\nFollow on MiLB First Pitch: https://stza.co/+vKXt-3A\n\nShop: https://stza.co/+vKXt-3N\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144555Z
LAST-MODIFIED:20180213T144555Z
TRANSP:OPAQUE
END:VEVENT
* Express vs. Baby Cakes
<2018-05-11 Fri 19:05-22:05>
:PROPERTIES:
:ID:       RiGg7r31EnQWjuPvsRbtMxkA@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Express vs. Baby Cakes Express vs. Baby Cakes

Follow on MiLB First Pitch  https //stza.co/+vKXw-2c

Shop  https //stza.co/+vKXw-3j

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Express vs. Baby Cakes
END:VALARM
DTSTART:20180512T000500Z
DTEND:20180512T030500Z
UID:RiGg7r31EnQWjuPvsRbtMxkA@stanza.co
SUMMARY:Express vs. Baby Cakes
DESCRIPTION:Express vs. Baby Cakes\n\nFollow on MiLB First Pitch: https://stza.co/+vKXw-2c\n\nShop: https://stza.co/+vKXw-3j\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144555Z
LAST-MODIFIED:20180213T144555Z
TRANSP:OPAQUE
END:VEVENT
* Express @ Cubs
<2018-05-12 Sat 19:08-22:08>
:PROPERTIES:
:ID:       olyjDU9w49WmpHKouwrMygB9@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Express @ Cubs Express @ Cubs

Follow on MiLB First Pitch  https //stza.co/+vKW5-2t

Shop  https //stza.co/+vKW5-3v

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Express @ Cubs
END:VALARM
DTSTART:20180513T000800Z
DTEND:20180513T030800Z
UID:olyjDU9w49WmpHKouwrMygB9@stanza.co
SUMMARY:Express @ Cubs
DESCRIPTION:Express @ Cubs\n\nFollow on MiLB First Pitch: https://stza.co/+vKW5-2t\n\nShop: https://stza.co/+vKW5-3v\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144555Z
LAST-MODIFIED:20180213T144555Z
TRANSP:OPAQUE
END:VEVENT
* Express @ Cubs
<2018-05-13 Sun 13:08-16:08>
:PROPERTIES:
:ID:       6LdqgNwFt35QyQi6Xht9njiQ@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Express @ Cubs Express @ Cubs

Follow on MiLB First Pitch  https //stza.co/+vKW6-1w

Shop  https //stza.co/+vKW6-h

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Express @ Cubs
END:VALARM
DTSTART:20180513T180800Z
DTEND:20180513T210800Z
UID:6LdqgNwFt35QyQi6Xht9njiQ@stanza.co
SUMMARY:Express @ Cubs
DESCRIPTION:Express @ Cubs\n\nFollow on MiLB First Pitch: https://stza.co/+vKW6-1w\n\nShop: https://stza.co/+vKW6-h\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144555Z
LAST-MODIFIED:20180213T144555Z
TRANSP:OPAQUE
END:VEVENT
* Express @ Cubs
<2018-05-14 Mon 12:08-15:08>
:PROPERTIES:
:ID:       MAteKxM-M1VwTinAooMshWwD@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Express @ Cubs Express @ Cubs

Follow on MiLB First Pitch  https //stza.co/+vKW7-2y

Shop  https //stza.co/+vKW7-1x

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Express @ Cubs
END:VALARM
DTSTART:20180514T170800Z
DTEND:20180514T200800Z
UID:MAteKxM-M1VwTinAooMshWwD@stanza.co
SUMMARY:Express @ Cubs
DESCRIPTION:Express @ Cubs\n\nFollow on MiLB First Pitch: https://stza.co/+vKW7-2y\n\nShop: https://stza.co/+vKW7-1x\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144555Z
LAST-MODIFIED:20180213T144555Z
TRANSP:OPAQUE
END:VEVENT
* Express @ Cubs
<2018-05-15 Tue 12:08-15:08>
:PROPERTIES:
:ID:       lS8WzyCcw0GdGm-DlvdoFk_-@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Express @ Cubs Express @ Cubs

Follow on MiLB First Pitch  https //stza.co/+vKW8-h

Shop  https //stza.co/+vKW8-1$

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Express @ Cubs
END:VALARM
DTSTART:20180515T170800Z
DTEND:20180515T200800Z
UID:lS8WzyCcw0GdGm-DlvdoFk_-@stanza.co
SUMMARY:Express @ Cubs
DESCRIPTION:Express @ Cubs\n\nFollow on MiLB First Pitch: https://stza.co/+vKW8-h\n\nShop: https://stza.co/+vKW8-1$\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144555Z
LAST-MODIFIED:20180213T144555Z
TRANSP:OPAQUE
END:VEVENT
* Express @ Baby Cakes
<2018-05-17 Thu 19:00-22:00>
:PROPERTIES:
:ID:       gyTf0nAb7kCwCuxd_aP6Epy7@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Express @ Baby Cakes Express @ Baby Cakes

Follow on MiLB First Pitch  https //stza.co/+whQs-2R

Shop  https //stza.co/+whQs-3t

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Express @ Baby Cakes
END:VALARM
DTSTART:20180518T000000Z
DTEND:20180518T030000Z
UID:gyTf0nAb7kCwCuxd_aP6Epy7@stanza.co
SUMMARY:Express @ Baby Cakes
DESCRIPTION:Express @ Baby Cakes\n\nFollow on MiLB First Pitch: https://stza.co/+whQs-2R\n\nShop: https://stza.co/+whQs-3t\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144555Z
LAST-MODIFIED:20180213T144555Z
TRANSP:OPAQUE
END:VEVENT
* Express @ Baby Cakes
<2018-05-18 Fri 19:00-22:00>
:PROPERTIES:
:ID:       jFMG8u1hmWzaiNqrXfVDd7Hm@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Express @ Baby Cakes Express @ Baby Cakes

Follow on MiLB First Pitch  https //stza.co/+whQt-S

Shop  https //stza.co/+whQt-3J

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Express @ Baby Cakes
END:VALARM
DTSTART:20180519T000000Z
DTEND:20180519T030000Z
UID:jFMG8u1hmWzaiNqrXfVDd7Hm@stanza.co
SUMMARY:Express @ Baby Cakes
DESCRIPTION:Express @ Baby Cakes\n\nFollow on MiLB First Pitch: https://stza.co/+whQt-S\n\nShop: https://stza.co/+whQt-3J\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144555Z
LAST-MODIFIED:20180213T144555Z
TRANSP:OPAQUE
END:VEVENT
* Express @ Baby Cakes
<2018-05-19 Sat 18:00-21:00>
:PROPERTIES:
:ID:       pQEA4vjZAKKZjo9Nu67qaS3M@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Express @ Baby Cakes Express @ Baby Cakes

Follow on MiLB First Pitch  https //stza.co/+whQu-1k

Shop  https //stza.co/+whQu-2w

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Express @ Baby Cakes
END:VALARM
DTSTART:20180519T230000Z
DTEND:20180520T020000Z
UID:pQEA4vjZAKKZjo9Nu67qaS3M@stanza.co
SUMMARY:Express @ Baby Cakes
DESCRIPTION:Express @ Baby Cakes\n\nFollow on MiLB First Pitch: https://stza.co/+whQu-1k\n\nShop: https://stza.co/+whQu-2w\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144555Z
LAST-MODIFIED:20180213T144555Z
TRANSP:OPAQUE
END:VEVENT
* Express @ Baby Cakes
<2018-05-20 Sun 13:00-16:00>
:PROPERTIES:
:ID:       8IHP7SwD68CvJqRUJXeuqEG1@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Express @ Baby Cakes Express @ Baby Cakes

Follow on MiLB First Pitch  https //stza.co/+whQv-Y

Shop  https //stza.co/+whQv-3F

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Express @ Baby Cakes
END:VALARM
DTSTART:20180520T180000Z
DTEND:20180520T210000Z
UID:8IHP7SwD68CvJqRUJXeuqEG1@stanza.co
SUMMARY:Express @ Baby Cakes
DESCRIPTION:Express @ Baby Cakes\n\nFollow on MiLB First Pitch: https://stza.co/+whQv-Y\n\nShop: https://stza.co/+whQv-3F\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144555Z
LAST-MODIFIED:20180213T144555Z
TRANSP:OPAQUE
END:VEVENT
* Express vs. Cubs
<2018-05-21 Mon 19:05-22:05>
:PROPERTIES:
:ID:       KXM5FOo9lHkw0aVNs6S4-rFS@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Express vs. Cubs Express vs. Cubs

Follow on MiLB First Pitch  https //stza.co/+vKXy-36

Shop  https //stza.co/+vKXy-2N

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Express vs. Cubs
END:VALARM
DTSTART:20180522T000500Z
DTEND:20180522T030500Z
UID:KXM5FOo9lHkw0aVNs6S4-rFS@stanza.co
SUMMARY:Express vs. Cubs
DESCRIPTION:Express vs. Cubs\n\nFollow on MiLB First Pitch: https://stza.co/+vKXy-36\n\nShop: https://stza.co/+vKXy-2N\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144555Z
LAST-MODIFIED:20180213T144555Z
TRANSP:OPAQUE
END:VEVENT
* Express vs. Cubs
<2018-05-22 Tue 19:05-22:05>
:PROPERTIES:
:ID:       9VL6IlK84xjzw3V-MZKumzFT@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Express vs. Cubs Express vs. Cubs

Follow on MiLB First Pitch  https //stza.co/+vKXz-2$

Shop  https //stza.co/+vKXz-c

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Express vs. Cubs
END:VALARM
DTSTART:20180523T000500Z
DTEND:20180523T030500Z
UID:9VL6IlK84xjzw3V-MZKumzFT@stanza.co
SUMMARY:Express vs. Cubs
DESCRIPTION:Express vs. Cubs\n\nFollow on MiLB First Pitch: https://stza.co/+vKXz-2$\n\nShop: https://stza.co/+vKXz-c\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144555Z
LAST-MODIFIED:20180213T144555Z
TRANSP:OPAQUE
END:VEVENT
* Express vs. Cubs
<2018-05-23 Wed 19:05-22:05>
:PROPERTIES:
:ID:       p-z2BmoW7B3R49DDD4CgZzgR@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Express vs. Cubs Express vs. Cubs

Follow on MiLB First Pitch  https //stza.co/+vKXC-1W

Shop  https //stza.co/+vKXC-33

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Express vs. Cubs
END:VALARM
DTSTART:20180524T000500Z
DTEND:20180524T030500Z
UID:p-z2BmoW7B3R49DDD4CgZzgR@stanza.co
SUMMARY:Express vs. Cubs
DESCRIPTION:Express vs. Cubs\n\nFollow on MiLB First Pitch: https://stza.co/+vKXC-1W\n\nShop: https://stza.co/+vKXC-33\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144555Z
LAST-MODIFIED:20180213T144555Z
TRANSP:OPAQUE
END:VEVENT
* Express vs. Cubs
<2018-05-24 Thu 19:05-22:05>
:PROPERTIES:
:ID:       HRjSyGqwejhMsfkfDylahRQ9@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Express vs. Cubs Express vs. Cubs

Follow on MiLB First Pitch  https //stza.co/+vKXE-J

Shop  https //stza.co/+vKXE-3z

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Express vs. Cubs
END:VALARM
DTSTART:20180525T000500Z
DTEND:20180525T030500Z
UID:HRjSyGqwejhMsfkfDylahRQ9@stanza.co
SUMMARY:Express vs. Cubs
DESCRIPTION:Express vs. Cubs\n\nFollow on MiLB First Pitch: https://stza.co/+vKXE-J\n\nShop: https://stza.co/+vKXE-3z\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144555Z
LAST-MODIFIED:20180213T144555Z
TRANSP:OPAQUE
END:VEVENT
* Express @ Storm Chasers
<2018-05-25 Fri 19:05-22:05>
:PROPERTIES:
:ID:       dLgbj2oO8kdTpZAvZRKxiOSa@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Express @ Storm Chasers Express @ Storm Chasers

Follow on MiLB First Pitch  https //stza.co/+whQw-1S

Shop  https //stza.co/+whQw-2s

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Express @ Storm Chasers
END:VALARM
DTSTART:20180526T000500Z
DTEND:20180526T030500Z
UID:dLgbj2oO8kdTpZAvZRKxiOSa@stanza.co
SUMMARY:Express @ Storm Chasers
DESCRIPTION:Express @ Storm Chasers\n\nFollow on MiLB First Pitch: https://stza.co/+whQw-1S\n\nShop: https://stza.co/+whQw-2s\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144555Z
LAST-MODIFIED:20180213T144555Z
TRANSP:OPAQUE
END:VEVENT
* Express @ Storm Chasers
<2018-05-26 Sat 19:05-22:05>
:PROPERTIES:
:ID:       cdKLL3IvST5-CcJbcsnQm2c8@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Express @ Storm Chasers Express @ Storm Chasers

Follow on MiLB First Pitch  https //stza.co/+whQx-n

Shop  https //stza.co/+whQx-1e

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Express @ Storm Chasers
END:VALARM
DTSTART:20180527T000500Z
DTEND:20180527T030500Z
UID:cdKLL3IvST5-CcJbcsnQm2c8@stanza.co
SUMMARY:Express @ Storm Chasers
DESCRIPTION:Express @ Storm Chasers\n\nFollow on MiLB First Pitch: https://stza.co/+whQx-n\n\nShop: https://stza.co/+whQx-1e\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144555Z
LAST-MODIFIED:20180213T144555Z
TRANSP:OPAQUE
END:VEVENT
* Express @ Storm Chasers
<2018-05-27 Sun 19:05-22:05>
:PROPERTIES:
:ID:       3x2yI9LFpqGbK5gIrxDMdeZs@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Express @ Storm Chasers Express @ Storm Chasers

Follow on MiLB First Pitch  https //stza.co/+whQy-1z

Shop  https //stza.co/+whQy-1x

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Express @ Storm Chasers
END:VALARM
DTSTART:20180528T000500Z
DTEND:20180528T030500Z
UID:3x2yI9LFpqGbK5gIrxDMdeZs@stanza.co
SUMMARY:Express @ Storm Chasers
DESCRIPTION:Express @ Storm Chasers\n\nFollow on MiLB First Pitch: https://stza.co/+whQy-1z\n\nShop: https://stza.co/+whQy-1x\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144555Z
LAST-MODIFIED:20180213T144555Z
TRANSP:OPAQUE
END:VEVENT
* Express @ Storm Chasers
<2018-05-28 Mon 12:05-15:05>
:PROPERTIES:
:ID:       bQ6s_Qs3dbeGLi-uR6c0uPUK@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Express @ Storm Chasers Express @ Storm Chasers

Follow on MiLB First Pitch  https //stza.co/+whQz-1B

Shop  https //stza.co/+whQz-1b

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Express @ Storm Chasers
END:VALARM
DTSTART:20180528T170500Z
DTEND:20180528T200500Z
UID:bQ6s_Qs3dbeGLi-uR6c0uPUK@stanza.co
SUMMARY:Express @ Storm Chasers
DESCRIPTION:Express @ Storm Chasers\n\nFollow on MiLB First Pitch: https://stza.co/+whQz-1B\n\nShop: https://stza.co/+whQz-1b\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144555Z
LAST-MODIFIED:20180213T144555Z
TRANSP:OPAQUE
END:VEVENT
* Express @ Storm Chasers
<2018-05-29 Tue 18:35-21:35>
:PROPERTIES:
:ID:       lQidi5V9y8FPSamoImNZuqXm@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Express @ Storm Chasers Express @ Storm Chasers

Follow on MiLB First Pitch  https //stza.co/+whQA-3m

Shop  https //stza.co/+whQA-L

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Express @ Storm Chasers
END:VALARM
DTSTART:20180529T233500Z
DTEND:20180530T023500Z
UID:lQidi5V9y8FPSamoImNZuqXm@stanza.co
SUMMARY:Express @ Storm Chasers
DESCRIPTION:Express @ Storm Chasers\n\nFollow on MiLB First Pitch: https://stza.co/+whQA-3m\n\nShop: https://stza.co/+whQA-L\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144555Z
LAST-MODIFIED:20180213T144555Z
TRANSP:OPAQUE
END:VEVENT
* Express vs. Sounds
<2018-05-30 Wed 19:05-22:05>
:PROPERTIES:
:ID:       DKJtpi5H1igIHoEtc69bk4HN@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Express vs. Sounds Express vs. Sounds

Follow on MiLB First Pitch  https //stza.co/+vKXF-33

Shop  https //stza.co/+vKXF-3O

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Express vs. Sounds
END:VALARM
DTSTART:20180531T000500Z
DTEND:20180531T030500Z
UID:DKJtpi5H1igIHoEtc69bk4HN@stanza.co
SUMMARY:Express vs. Sounds
DESCRIPTION:Express vs. Sounds\n\nFollow on MiLB First Pitch: https://stza.co/+vKXF-33\n\nShop: https://stza.co/+vKXF-3O\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144555Z
LAST-MODIFIED:20180213T144555Z
TRANSP:OPAQUE
END:VEVENT
* Express vs. Sounds
<2018-05-31 Thu 19:05-22:05>
:PROPERTIES:
:ID:       NuDHaz57-mV69rNMQ4DX-I53@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Express vs. Sounds Express vs. Sounds

Follow on MiLB First Pitch  https //stza.co/+vKXI-3t

Shop  https //stza.co/+vKXI-3D

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Express vs. Sounds
END:VALARM
DTSTART:20180601T000500Z
DTEND:20180601T030500Z
UID:NuDHaz57-mV69rNMQ4DX-I53@stanza.co
SUMMARY:Express vs. Sounds
DESCRIPTION:Express vs. Sounds\n\nFollow on MiLB First Pitch: https://stza.co/+vKXI-3t\n\nShop: https://stza.co/+vKXI-3D\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144555Z
LAST-MODIFIED:20180213T144555Z
TRANSP:OPAQUE
END:VEVENT
* Express vs. Sounds
<2018-06-01 Fri 19:05-22:05>
:PROPERTIES:
:ID:       lrVCB7EjAJsFbbhu8Zvi0Ny9@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Express vs. Sounds Express vs. Sounds

Follow on MiLB First Pitch  https //stza.co/+vKXK-25

Shop  https //stza.co/+vKXK-3f

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Express vs. Sounds
END:VALARM
DTSTART:20180602T000500Z
DTEND:20180602T030500Z
UID:lrVCB7EjAJsFbbhu8Zvi0Ny9@stanza.co
SUMMARY:Express vs. Sounds
DESCRIPTION:Express vs. Sounds\n\nFollow on MiLB First Pitch: https://stza.co/+vKXK-25\n\nShop: https://stza.co/+vKXK-3f\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144555Z
LAST-MODIFIED:20180213T144555Z
TRANSP:OPAQUE
END:VEVENT
* Express vs. Sounds
<2018-06-02 Sat 19:05-22:05>
:PROPERTIES:
:ID:       hBHH461_RUhH5viPKQ5Gwm8m@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Express vs. Sounds Express vs. Sounds

Follow on MiLB First Pitch  https //stza.co/+vKXM-1p

Shop  https //stza.co/+vKXM-32

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Express vs. Sounds
END:VALARM
DTSTART:20180603T000500Z
DTEND:20180603T030500Z
UID:hBHH461_RUhH5viPKQ5Gwm8m@stanza.co
SUMMARY:Express vs. Sounds
DESCRIPTION:Express vs. Sounds\n\nFollow on MiLB First Pitch: https://stza.co/+vKXM-1p\n\nShop: https://stza.co/+vKXM-32\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144555Z
LAST-MODIFIED:20180213T144555Z
TRANSP:OPAQUE
END:VEVENT
* Express vs. Sounds
<2018-06-03 Sun 13:05-16:05>
:PROPERTIES:
:ID:       jyZcvkxQEJAo1cyLn3onRuL8@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Express vs. Sounds Express vs. Sounds

Follow on MiLB First Pitch  https //stza.co/+vKXO-1T

Shop  https //stza.co/+vKXO-27

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Express vs. Sounds
END:VALARM
DTSTART:20180603T180500Z
DTEND:20180603T210500Z
UID:jyZcvkxQEJAo1cyLn3onRuL8@stanza.co
SUMMARY:Express vs. Sounds
DESCRIPTION:Express vs. Sounds\n\nFollow on MiLB First Pitch: https://stza.co/+vKXO-1T\n\nShop: https://stza.co/+vKXO-27\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144555Z
LAST-MODIFIED:20180213T144555Z
TRANSP:OPAQUE
END:VEVENT
* Express @ Bees
<2018-06-05 Tue 20:05-23:05>
:PROPERTIES:
:ID:       8XgLMmGuRtWOgvt31yo_2yfd@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Express @ Bees Express @ Bees

Follow on MiLB First Pitch  https //stza.co/+wmLQ-3X

Shop  https //stza.co/+wmLQ-3Y

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Express @ Bees
END:VALARM
DTSTART:20180606T010500Z
DTEND:20180606T040500Z
UID:8XgLMmGuRtWOgvt31yo_2yfd@stanza.co
SUMMARY:Express @ Bees
DESCRIPTION:Express @ Bees\n\nFollow on MiLB First Pitch: https://stza.co/+wmLQ-3X\n\nShop: https://stza.co/+wmLQ-3Y\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144555Z
LAST-MODIFIED:20180213T144555Z
TRANSP:OPAQUE
END:VEVENT
* Express @ Bees
<2018-06-06 Wed 20:05-23:05>
:PROPERTIES:
:ID:       1x8HZaZ9UAvmPOOBtbMemOCY@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Express @ Bees Express @ Bees

Follow on MiLB First Pitch  https //stza.co/+wmLR-18

Shop  https //stza.co/+wmLR-A

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Express @ Bees
END:VALARM
DTSTART:20180607T010500Z
DTEND:20180607T040500Z
UID:1x8HZaZ9UAvmPOOBtbMemOCY@stanza.co
SUMMARY:Express @ Bees
DESCRIPTION:Express @ Bees\n\nFollow on MiLB First Pitch: https://stza.co/+wmLR-18\n\nShop: https://stza.co/+wmLR-A\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144555Z
LAST-MODIFIED:20180213T144555Z
TRANSP:OPAQUE
END:VEVENT
* Express @ Bees
<2018-06-07 Thu 13:05-16:05>
:PROPERTIES:
:ID:       hAXmT50B1gN6LOVUtAZnYJZd@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Express @ Bees Express @ Bees

Follow on MiLB First Pitch  https //stza.co/+wmLS-3D

Shop  https //stza.co/+wmLS-3q

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Express @ Bees
END:VALARM
DTSTART:20180607T180500Z
DTEND:20180607T210500Z
UID:hAXmT50B1gN6LOVUtAZnYJZd@stanza.co
SUMMARY:Express @ Bees
DESCRIPTION:Express @ Bees\n\nFollow on MiLB First Pitch: https://stza.co/+wmLS-3D\n\nShop: https://stza.co/+wmLS-3q\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144555Z
LAST-MODIFIED:20180213T144555Z
TRANSP:OPAQUE
END:VEVENT
* Express @ 51s
<2018-06-08 Fri 21:05>--<2018-06-09 Sat 00:05>
:PROPERTIES:
:ID:       LrqlUKZuaSmrAp9XPhsygh5R@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Express @ 51s Express @ 51s

Follow on MiLB First Pitch  https //stza.co/+vKWd-R

Shop  https //stza.co/+vKWd-z

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Express @ 51s
END:VALARM
DTSTART:20180609T020500Z
DTEND:20180609T050500Z
UID:LrqlUKZuaSmrAp9XPhsygh5R@stanza.co
SUMMARY:Express @ 51s
DESCRIPTION:Express @ 51s\n\nFollow on MiLB First Pitch: https://stza.co/+vKWd-R\n\nShop: https://stza.co/+vKWd-z\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144555Z
LAST-MODIFIED:20180213T144555Z
TRANSP:OPAQUE
END:VEVENT
* Express @ 51s
<2018-06-09 Sat 21:05>--<2018-06-10 Sun 00:05>
:PROPERTIES:
:ID:       s6QXnN6t3l6ojZ470A8R6bzp@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Express @ 51s Express @ 51s

Follow on MiLB First Pitch  https //stza.co/+vKWe-F

Shop  https //stza.co/+vKWe-34

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Express @ 51s
END:VALARM
DTSTART:20180610T020500Z
DTEND:20180610T050500Z
UID:s6QXnN6t3l6ojZ470A8R6bzp@stanza.co
SUMMARY:Express @ 51s
DESCRIPTION:Express @ 51s\n\nFollow on MiLB First Pitch: https://stza.co/+vKWe-F\n\nShop: https://stza.co/+vKWe-34\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144555Z
LAST-MODIFIED:20180213T144555Z
TRANSP:OPAQUE
END:VEVENT
* Express @ 51s
<2018-06-10 Sun 14:05-17:05>
:PROPERTIES:
:ID:       GsANNsqiT-BioaSMF_4U-v3o@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Express @ 51s Express @ 51s

Follow on MiLB First Pitch  https //stza.co/+vKWf-2U

Shop  https //stza.co/+vKWf-3m

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Express @ 51s
END:VALARM
DTSTART:20180610T190500Z
DTEND:20180610T220500Z
UID:GsANNsqiT-BioaSMF_4U-v3o@stanza.co
SUMMARY:Express @ 51s
DESCRIPTION:Express @ 51s\n\nFollow on MiLB First Pitch: https://stza.co/+vKWf-2U\n\nShop: https://stza.co/+vKWf-3m\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144555Z
LAST-MODIFIED:20180213T144555Z
TRANSP:OPAQUE
END:VEVENT
* Express @ 51s
<2018-06-11 Mon 21:05>--<2018-06-12 Tue 00:05>
:PROPERTIES:
:ID:       oROudnC1cD1P3BRwjU2ganXQ@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Express @ 51s Express @ 51s

Follow on MiLB First Pitch  https //stza.co/+vKWg-1d

Shop  https //stza.co/+vKWg-Q

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Express @ 51s
END:VALARM
DTSTART:20180612T020500Z
DTEND:20180612T050500Z
UID:oROudnC1cD1P3BRwjU2ganXQ@stanza.co
SUMMARY:Express @ 51s
DESCRIPTION:Express @ 51s\n\nFollow on MiLB First Pitch: https://stza.co/+vKWg-1d\n\nShop: https://stza.co/+vKWg-Q\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144555Z
LAST-MODIFIED:20180213T144555Z
TRANSP:OPAQUE
END:VEVENT
* Express vs. River Cats
<2018-06-13 Wed 19:05-22:05>
:PROPERTIES:
:ID:       x4cY0BEjU3yU0fPkTQfp8c6C@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Express vs. River Cats Express vs. River Cats

Follow on MiLB First Pitch  https //stza.co/+vKXP-7

Shop  https //stza.co/+vKXP-29

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Express vs. River Cats
END:VALARM
DTSTART:20180614T000500Z
DTEND:20180614T030500Z
UID:x4cY0BEjU3yU0fPkTQfp8c6C@stanza.co
SUMMARY:Express vs. River Cats
DESCRIPTION:Express vs. River Cats\n\nFollow on MiLB First Pitch: https://stza.co/+vKXP-7\n\nShop: https://stza.co/+vKXP-29\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144555Z
LAST-MODIFIED:20180213T144555Z
TRANSP:OPAQUE
END:VEVENT
* Express vs. River Cats
<2018-06-14 Thu 19:05-22:05>
:PROPERTIES:
:ID:       uSHHREYB9wPa5Rr5qnIc5Pbu@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Express vs. River Cats Express vs. River Cats

Follow on MiLB First Pitch  https //stza.co/+vKXS-$

Shop  https //stza.co/+vKXS-2g

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Express vs. River Cats
END:VALARM
DTSTART:20180615T000500Z
DTEND:20180615T030500Z
UID:uSHHREYB9wPa5Rr5qnIc5Pbu@stanza.co
SUMMARY:Express vs. River Cats
DESCRIPTION:Express vs. River Cats\n\nFollow on MiLB First Pitch: https://stza.co/+vKXS-$\n\nShop: https://stza.co/+vKXS-2g\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144555Z
LAST-MODIFIED:20180213T144555Z
TRANSP:OPAQUE
END:VEVENT
* Express vs. River Cats
<2018-06-15 Fri 19:05-22:05>
:PROPERTIES:
:ID:       h6_3uckfZW9S-YNweRdjBcc1@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Express vs. River Cats Express vs. River Cats

Follow on MiLB First Pitch  https //stza.co/+vKXU-1b

Shop  https //stza.co/+vKXU-3A

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Express vs. River Cats
END:VALARM
DTSTART:20180616T000500Z
DTEND:20180616T030500Z
UID:h6_3uckfZW9S-YNweRdjBcc1@stanza.co
SUMMARY:Express vs. River Cats
DESCRIPTION:Express vs. River Cats\n\nFollow on MiLB First Pitch: https://stza.co/+vKXU-1b\n\nShop: https://stza.co/+vKXU-3A\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144555Z
LAST-MODIFIED:20180213T144555Z
TRANSP:OPAQUE
END:VEVENT
* Express vs. Grizzlies
<2018-06-16 Sat 18:05-21:05>
:PROPERTIES:
:ID:       I6Q6HYGUGa2W6jqBt9wTVeRr@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Express vs. Grizzlies Express vs. Grizzlies

Follow on MiLB First Pitch  https //stza.co/+vKXV-v

Shop  https //stza.co/+vKXV-H

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Express vs. Grizzlies
END:VALARM
DTSTART:20180616T230500Z
DTEND:20180617T020500Z
UID:I6Q6HYGUGa2W6jqBt9wTVeRr@stanza.co
SUMMARY:Express vs. Grizzlies
DESCRIPTION:Express vs. Grizzlies\n\nFollow on MiLB First Pitch: https://stza.co/+vKXV-v\n\nShop: https://stza.co/+vKXV-H\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144555Z
LAST-MODIFIED:20180213T144555Z
TRANSP:OPAQUE
END:VEVENT
* Express vs. Grizzlies
<2018-06-17 Sun 13:05-16:05>
:PROPERTIES:
:ID:       pQZF1uOhUtgFfa-hXqfJWzO0@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Express vs. Grizzlies Express vs. Grizzlies

Follow on MiLB First Pitch  https //stza.co/+whQF-O

Shop  https //stza.co/+whQF-1R

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Express vs. Grizzlies
END:VALARM
DTSTART:20180617T180500Z
DTEND:20180617T210500Z
UID:pQZF1uOhUtgFfa-hXqfJWzO0@stanza.co
SUMMARY:Express vs. Grizzlies
DESCRIPTION:Express vs. Grizzlies\n\nFollow on MiLB First Pitch: https://stza.co/+whQF-O\n\nShop: https://stza.co/+whQF-1R\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144555Z
LAST-MODIFIED:20180213T144555Z
TRANSP:OPAQUE
END:VEVENT
* Express vs. Grizzlies
<2018-06-18 Mon 19:05-22:05>
:PROPERTIES:
:ID:       7-5sOWpHaz9FGMeKFb2NYD_4@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Express vs. Grizzlies Express vs. Grizzlies

Follow on MiLB First Pitch  https //stza.co/+vKXZ-3Z

Shop  https //stza.co/+vKXZ-1P

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Express vs. Grizzlies
END:VALARM
DTSTART:20180619T000500Z
DTEND:20180619T030500Z
UID:7-5sOWpHaz9FGMeKFb2NYD_4@stanza.co
SUMMARY:Express vs. Grizzlies
DESCRIPTION:Express vs. Grizzlies\n\nFollow on MiLB First Pitch: https://stza.co/+vKXZ-3Z\n\nShop: https://stza.co/+vKXZ-1P\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144555Z
LAST-MODIFIED:20180213T144555Z
TRANSP:OPAQUE
END:VEVENT
* Express vs. Grizzlies
<2018-06-19 Tue 19:05-22:05>
:PROPERTIES:
:ID:       huCVlGzX3TdrU17RVO7gaGEd@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Express vs. Grizzlies Express vs. Grizzlies

Follow on MiLB First Pitch  https //stza.co/+vKX$-1y

Shop  https //stza.co/+vKX$-9

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Express vs. Grizzlies
END:VALARM
DTSTART:20180620T000500Z
DTEND:20180620T030500Z
UID:huCVlGzX3TdrU17RVO7gaGEd@stanza.co
SUMMARY:Express vs. Grizzlies
DESCRIPTION:Express vs. Grizzlies\n\nFollow on MiLB First Pitch: https://stza.co/+vKX$-1y\n\nShop: https://stza.co/+vKX$-9\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144555Z
LAST-MODIFIED:20180213T144555Z
TRANSP:OPAQUE
END:VEVENT
* Express @ Sounds
<2018-06-21 Thu 19:05-22:05>
:PROPERTIES:
:ID:       a2B2xuWCK850M-8cZjtOHgXs@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Express @ Sounds Express @ Sounds

Follow on MiLB First Pitch  https //stza.co/+whQf-3Q

Shop  https //stza.co/+whQf-G

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Express @ Sounds
END:VALARM
DTSTART:20180622T000500Z
DTEND:20180622T030500Z
UID:a2B2xuWCK850M-8cZjtOHgXs@stanza.co
SUMMARY:Express @ Sounds
DESCRIPTION:Express @ Sounds\n\nFollow on MiLB First Pitch: https://stza.co/+whQf-3Q\n\nShop: https://stza.co/+whQf-G\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144555Z
LAST-MODIFIED:20180213T144555Z
TRANSP:OPAQUE
END:VEVENT
* Express @ Sounds
<2018-06-22 Fri 19:05-22:05>
:PROPERTIES:
:ID:       hUclWqPSBReHhKzHzVNqOm7C@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Express @ Sounds Express @ Sounds

Follow on MiLB First Pitch  https //stza.co/+whQg-2w

Shop  https //stza.co/+whQg-1V

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Express @ Sounds
END:VALARM
DTSTART:20180623T000500Z
DTEND:20180623T030500Z
UID:hUclWqPSBReHhKzHzVNqOm7C@stanza.co
SUMMARY:Express @ Sounds
DESCRIPTION:Express @ Sounds\n\nFollow on MiLB First Pitch: https://stza.co/+whQg-2w\n\nShop: https://stza.co/+whQg-1V\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144555Z
LAST-MODIFIED:20180213T144555Z
TRANSP:OPAQUE
END:VEVENT
* Express @ Sounds
<2018-06-23 Sat 19:05-22:05>
:PROPERTIES:
:ID:       m7a31RB2LPllZJs8LNXedGeM@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Express @ Sounds Express @ Sounds

Follow on MiLB First Pitch  https //stza.co/+whQh-22

Shop  https //stza.co/+whQh-1P

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Express @ Sounds
END:VALARM
DTSTART:20180624T000500Z
DTEND:20180624T030500Z
UID:m7a31RB2LPllZJs8LNXedGeM@stanza.co
SUMMARY:Express @ Sounds
DESCRIPTION:Express @ Sounds\n\nFollow on MiLB First Pitch: https://stza.co/+whQh-22\n\nShop: https://stza.co/+whQh-1P\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144555Z
LAST-MODIFIED:20180213T144555Z
TRANSP:OPAQUE
END:VEVENT
* Express @ Sounds
<2018-06-24 Sun 18:15-21:15>
:PROPERTIES:
:ID:       OW_d8Iom07ABdW7n4uPx6R2X@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Express @ Sounds Express @ Sounds

Follow on MiLB First Pitch  https //stza.co/+whQj-1q

Shop  https //stza.co/+whQj-3e

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Express @ Sounds
END:VALARM
DTSTART:20180624T231500Z
DTEND:20180625T021500Z
UID:OW_d8Iom07ABdW7n4uPx6R2X@stanza.co
SUMMARY:Express @ Sounds
DESCRIPTION:Express @ Sounds\n\nFollow on MiLB First Pitch: https://stza.co/+whQj-1q\n\nShop: https://stza.co/+whQj-3e\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144555Z
LAST-MODIFIED:20180213T144555Z
TRANSP:OPAQUE
END:VEVENT
* Express vs. Storm Chasers
<2018-06-25 Mon 19:05-22:05>
:PROPERTIES:
:ID:       ia9Z1Ay3MThLI-C6kb3UGVqh@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Express vs. Storm Chasers Express vs. Storm Chasers

Follow on MiLB First Pitch  https //stza.co/+vKY2-2j

Shop  https //stza.co/+vKY2-1b

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Express vs. Storm Chasers
END:VALARM
DTSTART:20180626T000500Z
DTEND:20180626T030500Z
UID:ia9Z1Ay3MThLI-C6kb3UGVqh@stanza.co
SUMMARY:Express vs. Storm Chasers
DESCRIPTION:Express vs. Storm Chasers\n\nFollow on MiLB First Pitch: https://stza.co/+vKY2-2j\n\nShop: https://stza.co/+vKY2-1b\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144555Z
LAST-MODIFIED:20180213T144555Z
TRANSP:OPAQUE
END:VEVENT
* Express vs. Storm Chasers
<2018-06-26 Tue 19:05-22:05>
:PROPERTIES:
:ID:       P0gWhMbVMFHJRSqTuE9LVAd-@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Express vs. Storm Chasers Express vs. Storm Chasers

Follow on MiLB First Pitch  https //stza.co/+vKY3-P

Shop  https //stza.co/+vKY3-1o

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Express vs. Storm Chasers
END:VALARM
DTSTART:20180627T000500Z
DTEND:20180627T030500Z
UID:P0gWhMbVMFHJRSqTuE9LVAd-@stanza.co
SUMMARY:Express vs. Storm Chasers
DESCRIPTION:Express vs. Storm Chasers\n\nFollow on MiLB First Pitch: https://stza.co/+vKY3-P\n\nShop: https://stza.co/+vKY3-1o\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144555Z
LAST-MODIFIED:20180213T144555Z
TRANSP:OPAQUE
END:VEVENT
* Express vs. Storm Chasers
<2018-06-27 Wed 19:05-22:05>
:PROPERTIES:
:ID:       GZeja_AZeBeE_A65B6alJ6GM@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Express vs. Storm Chasers Express vs. Storm Chasers

Follow on MiLB First Pitch  https //stza.co/+vKY6-28

Shop  https //stza.co/+vKY6-19

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Express vs. Storm Chasers
END:VALARM
DTSTART:20180628T000500Z
DTEND:20180628T030500Z
UID:GZeja_AZeBeE_A65B6alJ6GM@stanza.co
SUMMARY:Express vs. Storm Chasers
DESCRIPTION:Express vs. Storm Chasers\n\nFollow on MiLB First Pitch: https://stza.co/+vKY6-28\n\nShop: https://stza.co/+vKY6-19\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144555Z
LAST-MODIFIED:20180213T144555Z
TRANSP:OPAQUE
END:VEVENT
* Express vs. Storm Chasers
<2018-06-28 Thu 19:05-22:05>
:PROPERTIES:
:ID:       xYB8TE1Ved_YekLB4Nnv-Q5R@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Express vs. Storm Chasers Express vs. Storm Chasers

Follow on MiLB First Pitch  https //stza.co/+vKY7-3g

Shop  https //stza.co/+vKY7-2

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Express vs. Storm Chasers
END:VALARM
DTSTART:20180629T000500Z
DTEND:20180629T030500Z
UID:xYB8TE1Ved_YekLB4Nnv-Q5R@stanza.co
SUMMARY:Express vs. Storm Chasers
DESCRIPTION:Express vs. Storm Chasers\n\nFollow on MiLB First Pitch: https://stza.co/+vKY7-3g\n\nShop: https://stza.co/+vKY7-2\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144555Z
LAST-MODIFIED:20180213T144555Z
TRANSP:OPAQUE
END:VEVENT
* Express vs. Sky Sox
<2018-06-29 Fri 19:05-22:05>
:PROPERTIES:
:ID:       vgUdrreeLX_yG4k6glNt51-M@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Express vs. Sky Sox Express vs. Sky Sox

Follow on MiLB First Pitch  https //stza.co/+vKYa-22

Shop  https //stza.co/+vKYa-2h

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Express vs. Sky Sox
END:VALARM
DTSTART:20180630T000500Z
DTEND:20180630T030500Z
UID:vgUdrreeLX_yG4k6glNt51-M@stanza.co
SUMMARY:Express vs. Sky Sox
DESCRIPTION:Express vs. Sky Sox\n\nFollow on MiLB First Pitch: https://stza.co/+vKYa-22\n\nShop: https://stza.co/+vKYa-2h\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144555Z
LAST-MODIFIED:20180213T144555Z
TRANSP:OPAQUE
END:VEVENT
* Express vs. Sky Sox
<2018-06-30 Sat 19:05-22:05>
:PROPERTIES:
:ID:       w9h5-G5yCyF4Gy10Jnqvg_in@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Express vs. Sky Sox Express vs. Sky Sox

Follow on MiLB First Pitch  https //stza.co/+vKYb-1V

Shop  https //stza.co/+vKYb-1y

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Express vs. Sky Sox
END:VALARM
DTSTART:20180701T000500Z
DTEND:20180701T030500Z
UID:w9h5-G5yCyF4Gy10Jnqvg_in@stanza.co
SUMMARY:Express vs. Sky Sox
DESCRIPTION:Express vs. Sky Sox\n\nFollow on MiLB First Pitch: https://stza.co/+vKYb-1V\n\nShop: https://stza.co/+vKYb-1y\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144555Z
LAST-MODIFIED:20180213T144555Z
TRANSP:OPAQUE
END:VEVENT
* Express vs. Sky Sox
<2018-07-01 Sun 18:05-21:05>
:PROPERTIES:
:ID:       c0iX5tWXynGVTF4A4WF85u8x@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Express vs. Sky Sox Express vs. Sky Sox

Follow on MiLB First Pitch  https //stza.co/+vKYd-1R

Shop  https //stza.co/+vKYd-s

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Express vs. Sky Sox
END:VALARM
DTSTART:20180701T230500Z
DTEND:20180702T020500Z
UID:c0iX5tWXynGVTF4A4WF85u8x@stanza.co
SUMMARY:Express vs. Sky Sox
DESCRIPTION:Express vs. Sky Sox\n\nFollow on MiLB First Pitch: https://stza.co/+vKYd-1R\n\nShop: https://stza.co/+vKYd-s\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144555Z
LAST-MODIFIED:20180213T144555Z
TRANSP:OPAQUE
END:VEVENT
* Express vs. Sky Sox
<2018-07-02 Mon 19:05-22:05>
:PROPERTIES:
:ID:       GiZlsX94vcSHP6ATyuV4708K@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Express vs. Sky Sox Express vs. Sky Sox

Follow on MiLB First Pitch  https //stza.co/+vKYf-1k

Shop  https //stza.co/+vKYf-2n

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Express vs. Sky Sox
END:VALARM
DTSTART:20180703T000500Z
DTEND:20180703T030500Z
UID:GiZlsX94vcSHP6ATyuV4708K@stanza.co
SUMMARY:Express vs. Sky Sox
DESCRIPTION:Express vs. Sky Sox\n\nFollow on MiLB First Pitch: https://stza.co/+vKYf-1k\n\nShop: https://stza.co/+vKYf-2n\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144555Z
LAST-MODIFIED:20180213T144555Z
TRANSP:OPAQUE
END:VEVENT
* Express vs. Sky Sox
<2018-07-03 Tue 19:05-22:05>
:PROPERTIES:
:ID:       UmLsNaJJ-62A1KgHf4caAdhQ@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Express vs. Sky Sox Express vs. Sky Sox

Follow on MiLB First Pitch  https //stza.co/+vKYh-3m

Shop  https //stza.co/+vKYh-1J

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Express vs. Sky Sox
END:VALARM
DTSTART:20180704T000500Z
DTEND:20180704T030500Z
UID:UmLsNaJJ-62A1KgHf4caAdhQ@stanza.co
SUMMARY:Express vs. Sky Sox
DESCRIPTION:Express vs. Sky Sox\n\nFollow on MiLB First Pitch: https://stza.co/+vKYh-3m\n\nShop: https://stza.co/+vKYh-1J\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144555Z
LAST-MODIFIED:20180213T144555Z
TRANSP:OPAQUE
END:VEVENT
* Express @ Dodgers
<2018-07-04 Wed 19:05-22:05>
:PROPERTIES:
:ID:       WcVnFrmuSIHiHyVIixdDIJi_@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Express @ Dodgers Express @ Dodgers

Follow on MiLB First Pitch  https //stza.co/+v$Pc-2o

Shop  https //stza.co/+v$Pc-3a

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Express @ Dodgers
END:VALARM
DTSTART:20180705T000500Z
DTEND:20180705T030500Z
UID:WcVnFrmuSIHiHyVIixdDIJi_@stanza.co
SUMMARY:Express @ Dodgers
DESCRIPTION:Express @ Dodgers\n\nFollow on MiLB First Pitch: https://stza.co/+v$Pc-2o\n\nShop: https://stza.co/+v$Pc-3a\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144555Z
LAST-MODIFIED:20180213T144555Z
TRANSP:OPAQUE
END:VEVENT
* Express @ Dodgers
<2018-07-05 Thu 19:05-22:05>
:PROPERTIES:
:ID:       fe44lNDTZQX7UKrDYJIgCQze@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Express @ Dodgers Express @ Dodgers

Follow on MiLB First Pitch  https //stza.co/+v$Pd-1x

Shop  https //stza.co/+v$Pd-i

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Express @ Dodgers
END:VALARM
DTSTART:20180706T000500Z
DTEND:20180706T030500Z
UID:fe44lNDTZQX7UKrDYJIgCQze@stanza.co
SUMMARY:Express @ Dodgers
DESCRIPTION:Express @ Dodgers\n\nFollow on MiLB First Pitch: https://stza.co/+v$Pd-1x\n\nShop: https://stza.co/+v$Pd-i\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144555Z
LAST-MODIFIED:20180213T144555Z
TRANSP:OPAQUE
END:VEVENT
* Express @ Dodgers
<2018-07-06 Fri 19:05-22:05>
:PROPERTIES:
:ID:       1LGAR5ICPAd58et_m8RLZVlv@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Express @ Dodgers Express @ Dodgers

Follow on MiLB First Pitch  https //stza.co/+v$Pe-1R

Shop  https //stza.co/+v$Pe-2J

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Express @ Dodgers
END:VALARM
DTSTART:20180707T000500Z
DTEND:20180707T030500Z
UID:1LGAR5ICPAd58et_m8RLZVlv@stanza.co
SUMMARY:Express @ Dodgers
DESCRIPTION:Express @ Dodgers\n\nFollow on MiLB First Pitch: https://stza.co/+v$Pe-1R\n\nShop: https://stza.co/+v$Pe-2J\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144555Z
LAST-MODIFIED:20180213T144555Z
TRANSP:OPAQUE
END:VEVENT
* Express @ Dodgers
<2018-07-07 Sat 19:05-22:05>
:PROPERTIES:
:ID:       sJIVeuPgQvAjVw79mmn7LVqv@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Express @ Dodgers Express @ Dodgers

Follow on MiLB First Pitch  https //stza.co/+v$Pf-V

Shop  https //stza.co/+v$Pf-3b

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Express @ Dodgers
END:VALARM
DTSTART:20180708T000500Z
DTEND:20180708T030500Z
UID:sJIVeuPgQvAjVw79mmn7LVqv@stanza.co
SUMMARY:Express @ Dodgers
DESCRIPTION:Express @ Dodgers\n\nFollow on MiLB First Pitch: https://stza.co/+v$Pf-V\n\nShop: https://stza.co/+v$Pf-3b\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144555Z
LAST-MODIFIED:20180213T144555Z
TRANSP:OPAQUE
END:VEVENT
* Express @ Dodgers
<2018-07-08 Sun 13:05-16:05>
:PROPERTIES:
:ID:       n9YUQHToduT3mlmorP9fU7Ch@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Express @ Dodgers Express @ Dodgers

Follow on MiLB First Pitch  https //stza.co/+v$Pg-2k

Shop  https //stza.co/+v$Pg-1V

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Express @ Dodgers
END:VALARM
DTSTART:20180708T180500Z
DTEND:20180708T210500Z
UID:n9YUQHToduT3mlmorP9fU7Ch@stanza.co
SUMMARY:Express @ Dodgers
DESCRIPTION:Express @ Dodgers\n\nFollow on MiLB First Pitch: https://stza.co/+v$Pg-2k\n\nShop: https://stza.co/+v$Pg-1V\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144555Z
LAST-MODIFIED:20180213T144555Z
TRANSP:OPAQUE
END:VEVENT
* Express vs. Dodgers
<2018-07-12 Thu 19:05-22:05>
:PROPERTIES:
:ID:       eKqpYnCOzClQ_9sA46mgty7u@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Express vs. Dodgers Express vs. Dodgers

Follow on MiLB First Pitch  https //stza.co/+vKYk-2G

Shop  https //stza.co/+vKYk-17

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Express vs. Dodgers
END:VALARM
DTSTART:20180713T000500Z
DTEND:20180713T030500Z
UID:eKqpYnCOzClQ_9sA46mgty7u@stanza.co
SUMMARY:Express vs. Dodgers
DESCRIPTION:Express vs. Dodgers\n\nFollow on MiLB First Pitch: https://stza.co/+vKYk-2G\n\nShop: https://stza.co/+vKYk-17\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144555Z
LAST-MODIFIED:20180213T144555Z
TRANSP:OPAQUE
END:VEVENT
* Express vs. Dodgers
<2018-07-13 Fri 19:05-22:05>
:PROPERTIES:
:ID:       W6V8WmbvxsPRHn0iG0Z8K5gL@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Express vs. Dodgers Express vs. Dodgers

Follow on MiLB First Pitch  https //stza.co/+vKYl-13

Shop  https //stza.co/+vKYl-b

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Express vs. Dodgers
END:VALARM
DTSTART:20180714T000500Z
DTEND:20180714T030500Z
UID:W6V8WmbvxsPRHn0iG0Z8K5gL@stanza.co
SUMMARY:Express vs. Dodgers
DESCRIPTION:Express vs. Dodgers\n\nFollow on MiLB First Pitch: https://stza.co/+vKYl-13\n\nShop: https://stza.co/+vKYl-b\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144555Z
LAST-MODIFIED:20180213T144555Z
TRANSP:OPAQUE
END:VEVENT
* Express vs. Dodgers
<2018-07-14 Sat 18:05-21:05>
:PROPERTIES:
:ID:       kmBk35TXW1Yh0xn_JIp5DtTy@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Express vs. Dodgers Express vs. Dodgers

Follow on MiLB First Pitch  https //stza.co/+vKYo-2Y

Shop  https //stza.co/+vKYo-3_

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Express vs. Dodgers
END:VALARM
DTSTART:20180714T230500Z
DTEND:20180715T020500Z
UID:kmBk35TXW1Yh0xn_JIp5DtTy@stanza.co
SUMMARY:Express vs. Dodgers
DESCRIPTION:Express vs. Dodgers\n\nFollow on MiLB First Pitch: https://stza.co/+vKYo-2Y\n\nShop: https://stza.co/+vKYo-3_\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144555Z
LAST-MODIFIED:20180213T144555Z
TRANSP:OPAQUE
END:VEVENT
* Express vs. Dodgers
<2018-07-15 Sun 18:05-21:05>
:PROPERTIES:
:ID:       fZy5F9IxdBczY7_xGvz-J2Tm@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Express vs. Dodgers Express vs. Dodgers

Follow on MiLB First Pitch  https //stza.co/+vKYp-3h

Shop  https //stza.co/+vKYp-3I

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Express vs. Dodgers
END:VALARM
DTSTART:20180715T230500Z
DTEND:20180716T020500Z
UID:fZy5F9IxdBczY7_xGvz-J2Tm@stanza.co
SUMMARY:Express vs. Dodgers
DESCRIPTION:Express vs. Dodgers\n\nFollow on MiLB First Pitch: https://stza.co/+vKYp-3h\n\nShop: https://stza.co/+vKYp-3I\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144555Z
LAST-MODIFIED:20180213T144555Z
TRANSP:OPAQUE
END:VEVENT
* Express @ Sky Sox
<2018-07-16 Mon 19:40-22:40>
:PROPERTIES:
:ID:       GaMEHIIya4VjzlD7UBM71p83@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Express @ Sky Sox Express @ Sky Sox

Follow on MiLB First Pitch  https //stza.co/+wmLy-1G

Shop  https //stza.co/+wmLy-W

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Express @ Sky Sox
END:VALARM
DTSTART:20180717T004000Z
DTEND:20180717T034000Z
UID:GaMEHIIya4VjzlD7UBM71p83@stanza.co
SUMMARY:Express @ Sky Sox
DESCRIPTION:Express @ Sky Sox\n\nFollow on MiLB First Pitch: https://stza.co/+wmLy-1G\n\nShop: https://stza.co/+wmLy-W\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144555Z
LAST-MODIFIED:20180213T144555Z
TRANSP:OPAQUE
END:VEVENT
* Express @ Sky Sox
<2018-07-17 Tue 19:40-22:40>
:PROPERTIES:
:ID:       TBTWVq_O7StjpZyvFXePIovI@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Express @ Sky Sox Express @ Sky Sox

Follow on MiLB First Pitch  https //stza.co/+wmLz-31

Shop  https //stza.co/+wmLz-s

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Express @ Sky Sox
END:VALARM
DTSTART:20180718T004000Z
DTEND:20180718T034000Z
UID:TBTWVq_O7StjpZyvFXePIovI@stanza.co
SUMMARY:Express @ Sky Sox
DESCRIPTION:Express @ Sky Sox\n\nFollow on MiLB First Pitch: https://stza.co/+wmLz-31\n\nShop: https://stza.co/+wmLz-s\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144555Z
LAST-MODIFIED:20180213T144555Z
TRANSP:OPAQUE
END:VEVENT
* Express @ Sky Sox
<2018-07-18 Wed 19:40-22:40>
:PROPERTIES:
:ID:       _A-MQjF74WmH4Se0lSYvkESK@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Express @ Sky Sox Express @ Sky Sox

Follow on MiLB First Pitch  https //stza.co/+wmLA-32

Shop  https //stza.co/+wmLA-1B

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Express @ Sky Sox
END:VALARM
DTSTART:20180719T004000Z
DTEND:20180719T034000Z
UID:_A-MQjF74WmH4Se0lSYvkESK@stanza.co
SUMMARY:Express @ Sky Sox
DESCRIPTION:Express @ Sky Sox\n\nFollow on MiLB First Pitch: https://stza.co/+wmLA-32\n\nShop: https://stza.co/+wmLA-1B\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144555Z
LAST-MODIFIED:20180213T144555Z
TRANSP:OPAQUE
END:VEVENT
* Express @ Sky Sox
<2018-07-19 Thu 19:40-22:40>
:PROPERTIES:
:ID:       EpRpLtb_dK0ZjtVfGMWCKfoF@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Express @ Sky Sox Express @ Sky Sox

Follow on MiLB First Pitch  https //stza.co/+wmLB-2p

Shop  https //stza.co/+wmLB-2C

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Express @ Sky Sox
END:VALARM
DTSTART:20180720T004000Z
DTEND:20180720T034000Z
UID:EpRpLtb_dK0ZjtVfGMWCKfoF@stanza.co
SUMMARY:Express @ Sky Sox
DESCRIPTION:Express @ Sky Sox\n\nFollow on MiLB First Pitch: https://stza.co/+wmLB-2p\n\nShop: https://stza.co/+wmLB-2C\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144555Z
LAST-MODIFIED:20180213T144555Z
TRANSP:OPAQUE
END:VEVENT
* Express @ Storm Chasers
<2018-07-20 Fri 19:05-22:05>
:PROPERTIES:
:ID:       KqupFpAze7F-Da9B0VRQqatJ@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Express @ Storm Chasers Express @ Storm Chasers

Follow on MiLB First Pitch  https //stza.co/+whQB-x

Shop  https //stza.co/+whQB-1z

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Express @ Storm Chasers
END:VALARM
DTSTART:20180721T000500Z
DTEND:20180721T030500Z
UID:KqupFpAze7F-Da9B0VRQqatJ@stanza.co
SUMMARY:Express @ Storm Chasers
DESCRIPTION:Express @ Storm Chasers\n\nFollow on MiLB First Pitch: https://stza.co/+whQB-x\n\nShop: https://stza.co/+whQB-1z\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144555Z
LAST-MODIFIED:20180213T144555Z
TRANSP:OPAQUE
END:VEVENT
* Express @ Storm Chasers
<2018-07-21 Sat 19:05-22:05>
:PROPERTIES:
:ID:       TpzE2YH5cFJC8SLZrOM_ognd@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Express @ Storm Chasers Express @ Storm Chasers

Follow on MiLB First Pitch  https //stza.co/+whQC-3o

Shop  https //stza.co/+whQC-18

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Express @ Storm Chasers
END:VALARM
DTSTART:20180722T000500Z
DTEND:20180722T030500Z
UID:TpzE2YH5cFJC8SLZrOM_ognd@stanza.co
SUMMARY:Express @ Storm Chasers
DESCRIPTION:Express @ Storm Chasers\n\nFollow on MiLB First Pitch: https://stza.co/+whQC-3o\n\nShop: https://stza.co/+whQC-18\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144555Z
LAST-MODIFIED:20180213T144555Z
TRANSP:OPAQUE
END:VEVENT
* Express @ Storm Chasers
<2018-07-22 Sun 14:05-17:05>
:PROPERTIES:
:ID:       rynya0xESuezPJQL4YrFcKQn@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Express @ Storm Chasers Express @ Storm Chasers

Follow on MiLB First Pitch  https //stza.co/+whQD-C

Shop  https //stza.co/+whQD-3d

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Express @ Storm Chasers
END:VALARM
DTSTART:20180722T190500Z
DTEND:20180722T220500Z
UID:rynya0xESuezPJQL4YrFcKQn@stanza.co
SUMMARY:Express @ Storm Chasers
DESCRIPTION:Express @ Storm Chasers\n\nFollow on MiLB First Pitch: https://stza.co/+whQD-C\n\nShop: https://stza.co/+whQD-3d\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144555Z
LAST-MODIFIED:20180213T144555Z
TRANSP:OPAQUE
END:VEVENT
* Express vs. Rainiers
<2018-07-24 Tue 19:05-22:05>
:PROPERTIES:
:ID:       TObOAmPTtISE-oOqTwyWPIbF@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Express vs. Rainiers Express vs. Rainiers

Follow on MiLB First Pitch  https //stza.co/+vKYs-B

Shop  https //stza.co/+vKYs-3J

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Express vs. Rainiers
END:VALARM
DTSTART:20180725T000500Z
DTEND:20180725T030500Z
UID:TObOAmPTtISE-oOqTwyWPIbF@stanza.co
SUMMARY:Express vs. Rainiers
DESCRIPTION:Express vs. Rainiers\n\nFollow on MiLB First Pitch: https://stza.co/+vKYs-B\n\nShop: https://stza.co/+vKYs-3J\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144555Z
LAST-MODIFIED:20180213T144555Z
TRANSP:OPAQUE
END:VEVENT
* Express vs. Rainiers
<2018-07-25 Wed 19:05-22:05>
:PROPERTIES:
:ID:       faybNzoRxyPHUuyzkR_EFTAG@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Express vs. Rainiers Express vs. Rainiers

Follow on MiLB First Pitch  https //stza.co/+vKYu-2V

Shop  https //stza.co/+vKYu-J

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Express vs. Rainiers
END:VALARM
DTSTART:20180726T000500Z
DTEND:20180726T030500Z
UID:faybNzoRxyPHUuyzkR_EFTAG@stanza.co
SUMMARY:Express vs. Rainiers
DESCRIPTION:Express vs. Rainiers\n\nFollow on MiLB First Pitch: https://stza.co/+vKYu-2V\n\nShop: https://stza.co/+vKYu-J\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144555Z
LAST-MODIFIED:20180213T144555Z
TRANSP:OPAQUE
END:VEVENT
* Express vs. Rainiers
<2018-07-26 Thu 19:05-22:05>
:PROPERTIES:
:ID:       JLZEzfmU2XudAb5ZUr3kHjuk@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Express vs. Rainiers Express vs. Rainiers

Follow on MiLB First Pitch  https //stza.co/+v4Ls-f

Shop  https //stza.co/+v4Ls-2h

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Express vs. Rainiers
END:VALARM
DTSTART:20180727T000500Z
DTEND:20180727T030500Z
UID:JLZEzfmU2XudAb5ZUr3kHjuk@stanza.co
SUMMARY:Express vs. Rainiers
DESCRIPTION:Express vs. Rainiers\n\nFollow on MiLB First Pitch: https://stza.co/+v4Ls-f\n\nShop: https://stza.co/+v4Ls-2h\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144555Z
LAST-MODIFIED:20180213T144555Z
TRANSP:OPAQUE
END:VEVENT
* Express vs. Aces
<2018-07-27 Fri 19:05-22:05>
:PROPERTIES:
:ID:       qR_6LFy9MtyWh7W8c86Z1zQ7@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Express vs. Aces Express vs. Aces

Follow on MiLB First Pitch  https //stza.co/+v4Lt-I

Shop  https //stza.co/+v4Lt-1X

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Express vs. Aces
END:VALARM
DTSTART:20180728T000500Z
DTEND:20180728T030500Z
UID:qR_6LFy9MtyWh7W8c86Z1zQ7@stanza.co
SUMMARY:Express vs. Aces
DESCRIPTION:Express vs. Aces\n\nFollow on MiLB First Pitch: https://stza.co/+v4Lt-I\n\nShop: https://stza.co/+v4Lt-1X\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144555Z
LAST-MODIFIED:20180213T144555Z
TRANSP:OPAQUE
END:VEVENT
* Express vs. Aces
<2018-07-28 Sat 19:05-22:05>
:PROPERTIES:
:ID:       H91IRVjVizh7NFK4YGdcFrO4@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Express vs. Aces Express vs. Aces

Follow on MiLB First Pitch  https //stza.co/+v4Lv-3N

Shop  https //stza.co/+v4Lv-2G

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Express vs. Aces
END:VALARM
DTSTART:20180729T000500Z
DTEND:20180729T030500Z
UID:H91IRVjVizh7NFK4YGdcFrO4@stanza.co
SUMMARY:Express vs. Aces
DESCRIPTION:Express vs. Aces\n\nFollow on MiLB First Pitch: https://stza.co/+v4Lv-3N\n\nShop: https://stza.co/+v4Lv-2G\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144555Z
LAST-MODIFIED:20180213T144555Z
TRANSP:OPAQUE
END:VEVENT
* Express vs. Aces
<2018-07-29 Sun 18:05-21:05>
:PROPERTIES:
:ID:       vXkJ4y3mWEFvESAq0wdNAAUM@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Express vs. Aces Express vs. Aces

Follow on MiLB First Pitch  https //stza.co/+v4Ly-1e

Shop  https //stza.co/+v4Ly-2R

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Express vs. Aces
END:VALARM
DTSTART:20180729T230500Z
DTEND:20180730T020500Z
UID:vXkJ4y3mWEFvESAq0wdNAAUM@stanza.co
SUMMARY:Express vs. Aces
DESCRIPTION:Express vs. Aces\n\nFollow on MiLB First Pitch: https://stza.co/+v4Ly-1e\n\nShop: https://stza.co/+v4Ly-2R\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144555Z
LAST-MODIFIED:20180213T144555Z
TRANSP:OPAQUE
END:VEVENT
* Express vs. Aces
<2018-07-30 Mon 19:05-22:05>
:PROPERTIES:
:ID:       zM5d4tiNV8JQ-uAJOUf8sk6E@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Express vs. Aces Express vs. Aces

Follow on MiLB First Pitch  https //stza.co/+v4LA-e

Shop  https //stza.co/+v4LA-H

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Express vs. Aces
END:VALARM
DTSTART:20180731T000500Z
DTEND:20180731T030500Z
UID:zM5d4tiNV8JQ-uAJOUf8sk6E@stanza.co
SUMMARY:Express vs. Aces
DESCRIPTION:Express vs. Aces\n\nFollow on MiLB First Pitch: https://stza.co/+v4LA-e\n\nShop: https://stza.co/+v4LA-H\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144555Z
LAST-MODIFIED:20180213T144555Z
TRANSP:OPAQUE
END:VEVENT
* Express @ Isotopes
<2018-08-01 Wed 19:35-22:35>
:PROPERTIES:
:ID:       MHq0mag6HrAAOa-yme1VxCO9@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Express @ Isotopes Express @ Isotopes

Follow on MiLB First Pitch  https //stza.co/+whQb-3G

Shop  https //stza.co/+whQb-1f

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Express @ Isotopes
END:VALARM
DTSTART:20180802T003500Z
DTEND:20180802T033500Z
UID:MHq0mag6HrAAOa-yme1VxCO9@stanza.co
SUMMARY:Express @ Isotopes
DESCRIPTION:Express @ Isotopes\n\nFollow on MiLB First Pitch: https://stza.co/+whQb-3G\n\nShop: https://stza.co/+whQb-1f\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144555Z
LAST-MODIFIED:20180213T144555Z
TRANSP:OPAQUE
END:VEVENT
* Express @ Isotopes
<2018-08-02 Thu 19:35-22:35>
:PROPERTIES:
:ID:       j8QRc1aP9cNE0GgLh4sudJN5@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Express @ Isotopes Express @ Isotopes

Follow on MiLB First Pitch  https //stza.co/+whQc-2i

Shop  https //stza.co/+whQc-3B

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Express @ Isotopes
END:VALARM
DTSTART:20180803T003500Z
DTEND:20180803T033500Z
UID:j8QRc1aP9cNE0GgLh4sudJN5@stanza.co
SUMMARY:Express @ Isotopes
DESCRIPTION:Express @ Isotopes\n\nFollow on MiLB First Pitch: https://stza.co/+whQc-2i\n\nShop: https://stza.co/+whQc-3B\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144555Z
LAST-MODIFIED:20180213T144555Z
TRANSP:OPAQUE
END:VEVENT
* Express @ Isotopes
<2018-08-03 Fri 19:35-22:35>
:PROPERTIES:
:ID:       DdCiO05mYFz0Kb8ZgTgNXTIb@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Express @ Isotopes Express @ Isotopes

Follow on MiLB First Pitch  https //stza.co/+whQd-X

Shop  https //stza.co/+whQd-f

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Express @ Isotopes
END:VALARM
DTSTART:20180804T003500Z
DTEND:20180804T033500Z
UID:DdCiO05mYFz0Kb8ZgTgNXTIb@stanza.co
SUMMARY:Express @ Isotopes
DESCRIPTION:Express @ Isotopes\n\nFollow on MiLB First Pitch: https://stza.co/+whQd-X\n\nShop: https://stza.co/+whQd-f\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144555Z
LAST-MODIFIED:20180213T144555Z
TRANSP:OPAQUE
END:VEVENT
* Express @ Chihuahuas
<2018-08-04 Sat 20:05-23:05>
:PROPERTIES:
:ID:       xPRDfk-io3Vdx3Np8AyNStcy@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Express @ Chihuahuas Express @ Chihuahuas

Follow on MiLB First Pitch  https //stza.co/+wmLC-5

Shop  https //stza.co/+wmLC-1i

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Express @ Chihuahuas
END:VALARM
DTSTART:20180805T010500Z
DTEND:20180805T040500Z
UID:xPRDfk-io3Vdx3Np8AyNStcy@stanza.co
SUMMARY:Express @ Chihuahuas
DESCRIPTION:Express @ Chihuahuas\n\nFollow on MiLB First Pitch: https://stza.co/+wmLC-5\n\nShop: https://stza.co/+wmLC-1i\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144555Z
LAST-MODIFIED:20180213T144555Z
TRANSP:OPAQUE
END:VEVENT
* Express @ Chihuahuas
<2018-08-05 Sun 19:05-22:05>
:PROPERTIES:
:ID:       k5nVFjPijpU5JxaGvucDSVoV@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Express @ Chihuahuas Express @ Chihuahuas

Follow on MiLB First Pitch  https //stza.co/+wmLD-3X

Shop  https //stza.co/+wmLD-3N

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Express @ Chihuahuas
END:VALARM
DTSTART:20180806T000500Z
DTEND:20180806T030500Z
UID:k5nVFjPijpU5JxaGvucDSVoV@stanza.co
SUMMARY:Express @ Chihuahuas
DESCRIPTION:Express @ Chihuahuas\n\nFollow on MiLB First Pitch: https://stza.co/+wmLD-3X\n\nShop: https://stza.co/+wmLD-3N\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144555Z
LAST-MODIFIED:20180213T144555Z
TRANSP:OPAQUE
END:VEVENT
* Express @ Chihuahuas
<2018-08-06 Mon 20:05-23:05>
:PROPERTIES:
:ID:       dpCJ8-MeCndaVPoKz-bxw6VN@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Express @ Chihuahuas Express @ Chihuahuas

Follow on MiLB First Pitch  https //stza.co/+wmLE-2r

Shop  https //stza.co/+wmLE-3K

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Express @ Chihuahuas
END:VALARM
DTSTART:20180807T010500Z
DTEND:20180807T040500Z
UID:dpCJ8-MeCndaVPoKz-bxw6VN@stanza.co
SUMMARY:Express @ Chihuahuas
DESCRIPTION:Express @ Chihuahuas\n\nFollow on MiLB First Pitch: https://stza.co/+wmLE-2r\n\nShop: https://stza.co/+wmLE-3K\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144555Z
LAST-MODIFIED:20180213T144555Z
TRANSP:OPAQUE
END:VEVENT
* Express @ Chihuahuas
<2018-08-07 Tue 20:05-23:05>
:PROPERTIES:
:ID:       aN_leVYC5Zzx-wFB9DqdXmVH@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Express @ Chihuahuas Express @ Chihuahuas

Follow on MiLB First Pitch  https //stza.co/+wmLF-2

Shop  https //stza.co/+wmLF-38

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Express @ Chihuahuas
END:VALARM
DTSTART:20180808T010500Z
DTEND:20180808T040500Z
UID:aN_leVYC5Zzx-wFB9DqdXmVH@stanza.co
SUMMARY:Express @ Chihuahuas
DESCRIPTION:Express @ Chihuahuas\n\nFollow on MiLB First Pitch: https://stza.co/+wmLF-2\n\nShop: https://stza.co/+wmLF-38\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144555Z
LAST-MODIFIED:20180213T144555Z
TRANSP:OPAQUE
END:VEVENT
* Express vs. Storm Chasers
<2018-08-09 Thu 19:05-22:05>
:PROPERTIES:
:ID:       FyQJW5em8OAPH57ySvqfAVD2@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Express vs. Storm Chasers Express vs. Storm Chasers

Follow on MiLB First Pitch  https //stza.co/+v4LB-1H

Shop  https //stza.co/+v4LB-2q

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Express vs. Storm Chasers
END:VALARM
DTSTART:20180810T000500Z
DTEND:20180810T030500Z
UID:FyQJW5em8OAPH57ySvqfAVD2@stanza.co
SUMMARY:Express vs. Storm Chasers
DESCRIPTION:Express vs. Storm Chasers\n\nFollow on MiLB First Pitch: https://stza.co/+v4LB-1H\n\nShop: https://stza.co/+v4LB-2q\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144555Z
LAST-MODIFIED:20180213T144555Z
TRANSP:OPAQUE
END:VEVENT
* Express vs. Storm Chasers
<2018-08-10 Fri 19:05-22:05>
:PROPERTIES:
:ID:       lrQmNykrJV3CAN9gpG5Bdaox@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Express vs. Storm Chasers Express vs. Storm Chasers

Follow on MiLB First Pitch  https //stza.co/+v4LE-2D

Shop  https //stza.co/+v4LE-3y

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Express vs. Storm Chasers
END:VALARM
DTSTART:20180811T000500Z
DTEND:20180811T030500Z
UID:lrQmNykrJV3CAN9gpG5Bdaox@stanza.co
SUMMARY:Express vs. Storm Chasers
DESCRIPTION:Express vs. Storm Chasers\n\nFollow on MiLB First Pitch: https://stza.co/+v4LE-2D\n\nShop: https://stza.co/+v4LE-3y\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144555Z
LAST-MODIFIED:20180213T144555Z
TRANSP:OPAQUE
END:VEVENT
* Express vs. Storm Chasers
<2018-08-11 Sat 18:05-21:05>
:PROPERTIES:
:ID:       nNdbFSmA2Ret6qE2jQRKzdQo@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Express vs. Storm Chasers Express vs. Storm Chasers

Follow on MiLB First Pitch  https //stza.co/+v4LG-1i

Shop  https //stza.co/+v4LG-2N

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Express vs. Storm Chasers
END:VALARM
DTSTART:20180811T230500Z
DTEND:20180812T020500Z
UID:nNdbFSmA2Ret6qE2jQRKzdQo@stanza.co
SUMMARY:Express vs. Storm Chasers
DESCRIPTION:Express vs. Storm Chasers\n\nFollow on MiLB First Pitch: https://stza.co/+v4LG-1i\n\nShop: https://stza.co/+v4LG-2N\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144555Z
LAST-MODIFIED:20180213T144555Z
TRANSP:OPAQUE
END:VEVENT
* Express vs. Storm Chasers
<2018-08-12 Sun 18:05-21:05>
:PROPERTIES:
:ID:       REuB4O8adEY_1t6zaPRrMTSg@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Express vs. Storm Chasers Express vs. Storm Chasers

Follow on MiLB First Pitch  https //stza.co/+v4LI-3U

Shop  https //stza.co/+v4LI-_

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Express vs. Storm Chasers
END:VALARM
DTSTART:20180812T230500Z
DTEND:20180813T020500Z
UID:REuB4O8adEY_1t6zaPRrMTSg@stanza.co
SUMMARY:Express vs. Storm Chasers
DESCRIPTION:Express vs. Storm Chasers\n\nFollow on MiLB First Pitch: https://stza.co/+v4LI-3U\n\nShop: https://stza.co/+v4LI-_\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144555Z
LAST-MODIFIED:20180213T144555Z
TRANSP:OPAQUE
END:VEVENT
* Express @ Sounds
<2018-08-13 Mon 19:05-22:05>
:PROPERTIES:
:ID:       4zqDCv7Gy1fbSudRNSOY7jop@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Express @ Sounds Express @ Sounds

Follow on MiLB First Pitch  https //stza.co/+whQk-15

Shop  https //stza.co/+whQk-2f

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Express @ Sounds
END:VALARM
DTSTART:20180814T000500Z
DTEND:20180814T030500Z
UID:4zqDCv7Gy1fbSudRNSOY7jop@stanza.co
SUMMARY:Express @ Sounds
DESCRIPTION:Express @ Sounds\n\nFollow on MiLB First Pitch: https://stza.co/+whQk-15\n\nShop: https://stza.co/+whQk-2f\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144555Z
LAST-MODIFIED:20180213T144555Z
TRANSP:OPAQUE
END:VEVENT
* Express @ Sounds
<2018-08-14 Tue 19:05-22:05>
:PROPERTIES:
:ID:       h6Px3DWNqnUknerd9SfmtKEl@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Express @ Sounds Express @ Sounds

Follow on MiLB First Pitch  https //stza.co/+whQl-_

Shop  https //stza.co/+whQl-3l

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Express @ Sounds
END:VALARM
DTSTART:20180815T000500Z
DTEND:20180815T030500Z
UID:h6Px3DWNqnUknerd9SfmtKEl@stanza.co
SUMMARY:Express @ Sounds
DESCRIPTION:Express @ Sounds\n\nFollow on MiLB First Pitch: https://stza.co/+whQl-_\n\nShop: https://stza.co/+whQl-3l\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144555Z
LAST-MODIFIED:20180213T144555Z
TRANSP:OPAQUE
END:VEVENT
* Express @ Sounds
<2018-08-15 Wed 19:05-22:05>
:PROPERTIES:
:ID:       N4BQVd2NOWW8-OQe2NRc0FML@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Express @ Sounds Express @ Sounds

Follow on MiLB First Pitch  https //stza.co/+whQm-2Z

Shop  https //stza.co/+whQm-2$

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Express @ Sounds
END:VALARM
DTSTART:20180816T000500Z
DTEND:20180816T030500Z
UID:N4BQVd2NOWW8-OQe2NRc0FML@stanza.co
SUMMARY:Express @ Sounds
DESCRIPTION:Express @ Sounds\n\nFollow on MiLB First Pitch: https://stza.co/+whQm-2Z\n\nShop: https://stza.co/+whQm-2$\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144555Z
LAST-MODIFIED:20180213T144555Z
TRANSP:OPAQUE
END:VEVENT
* Express @ Sounds
<2018-08-16 Thu 19:05-22:05>
:PROPERTIES:
:ID:       _OHcrT91k34Zv-5GCjkwNoDm@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Express @ Sounds Express @ Sounds

Follow on MiLB First Pitch  https //stza.co/+whQn-1u

Shop  https //stza.co/+whQn-2P

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Express @ Sounds
END:VALARM
DTSTART:20180817T000500Z
DTEND:20180817T030500Z
UID:_OHcrT91k34Zv-5GCjkwNoDm@stanza.co
SUMMARY:Express @ Sounds
DESCRIPTION:Express @ Sounds\n\nFollow on MiLB First Pitch: https://stza.co/+whQn-1u\n\nShop: https://stza.co/+whQn-2P\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144555Z
LAST-MODIFIED:20180213T144555Z
TRANSP:OPAQUE
END:VEVENT
* Express @ Redbirds
<2018-08-17 Fri 19:05-22:05>
:PROPERTIES:
:ID:       t0QHjmr_oYy6fmJDrjxlHb25@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Express @ Redbirds Express @ Redbirds

Follow on MiLB First Pitch  https //stza.co/+wmLL-28

Shop  https //stza.co/+wmLL-2C

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Express @ Redbirds
END:VALARM
DTSTART:20180818T000500Z
DTEND:20180818T030500Z
UID:t0QHjmr_oYy6fmJDrjxlHb25@stanza.co
SUMMARY:Express @ Redbirds
DESCRIPTION:Express @ Redbirds\n\nFollow on MiLB First Pitch: https://stza.co/+wmLL-28\n\nShop: https://stza.co/+wmLL-2C\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144555Z
LAST-MODIFIED:20180213T144555Z
TRANSP:OPAQUE
END:VEVENT
* Express @ Redbirds
<2018-08-18 Sat 18:35-21:35>
:PROPERTIES:
:ID:       Z0ZLrqEyh-D1lKQ8hMuCwwRA@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Express @ Redbirds Express @ Redbirds

Follow on MiLB First Pitch  https //stza.co/+wmLM-_

Shop  https //stza.co/+wmLM-W

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Express @ Redbirds
END:VALARM
DTSTART:20180818T233500Z
DTEND:20180819T023500Z
UID:Z0ZLrqEyh-D1lKQ8hMuCwwRA@stanza.co
SUMMARY:Express @ Redbirds
DESCRIPTION:Express @ Redbirds\n\nFollow on MiLB First Pitch: https://stza.co/+wmLM-_\n\nShop: https://stza.co/+wmLM-W\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144555Z
LAST-MODIFIED:20180213T144555Z
TRANSP:OPAQUE
END:VEVENT
* Express @ Redbirds
<2018-08-19 Sun 14:05-17:05>
:PROPERTIES:
:ID:       wCtjmlOEve0r19z3KE948rTb@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Express @ Redbirds Express @ Redbirds

Follow on MiLB First Pitch  https //stza.co/+wmLN-1B

Shop  https //stza.co/+wmLN-g

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Express @ Redbirds
END:VALARM
DTSTART:20180819T190500Z
DTEND:20180819T220500Z
UID:wCtjmlOEve0r19z3KE948rTb@stanza.co
SUMMARY:Express @ Redbirds
DESCRIPTION:Express @ Redbirds\n\nFollow on MiLB First Pitch: https://stza.co/+wmLN-1B\n\nShop: https://stza.co/+wmLN-g\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144555Z
LAST-MODIFIED:20180213T144555Z
TRANSP:OPAQUE
END:VEVENT
* Express vs. Sounds
<2018-08-21 Tue 19:05-22:05>
:PROPERTIES:
:ID:       QLrdPO3_Pc0V3ZPu5dMNElKt@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Express vs. Sounds Express vs. Sounds

Follow on MiLB First Pitch  https //stza.co/+v4LJ-3S

Shop  https //stza.co/+v4LJ-x

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Express vs. Sounds
END:VALARM
DTSTART:20180822T000500Z
DTEND:20180822T030500Z
UID:QLrdPO3_Pc0V3ZPu5dMNElKt@stanza.co
SUMMARY:Express vs. Sounds
DESCRIPTION:Express vs. Sounds\n\nFollow on MiLB First Pitch: https://stza.co/+v4LJ-3S\n\nShop: https://stza.co/+v4LJ-x\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144555Z
LAST-MODIFIED:20180213T144555Z
TRANSP:OPAQUE
END:VEVENT
* Express vs. Sounds
<2018-08-22 Wed 19:05-22:05>
:PROPERTIES:
:ID:       m6M5NolKo734XtN-SfuhNHAr@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Express vs. Sounds Express vs. Sounds

Follow on MiLB First Pitch  https //stza.co/+v4LL-3Y

Shop  https //stza.co/+v4LL-1q

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Express vs. Sounds
END:VALARM
DTSTART:20180823T000500Z
DTEND:20180823T030500Z
UID:m6M5NolKo734XtN-SfuhNHAr@stanza.co
SUMMARY:Express vs. Sounds
DESCRIPTION:Express vs. Sounds\n\nFollow on MiLB First Pitch: https://stza.co/+v4LL-3Y\n\nShop: https://stza.co/+v4LL-1q\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144555Z
LAST-MODIFIED:20180213T144555Z
TRANSP:OPAQUE
END:VEVENT
* Express vs. Sounds
<2018-08-23 Thu 19:05-22:05>
:PROPERTIES:
:ID:       TaJmoPncU7zN-k9Y8B2MPMdq@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Express vs. Sounds Express vs. Sounds

Follow on MiLB First Pitch  https //stza.co/+v4LO-3i

Shop  https //stza.co/+v4LO-14

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Express vs. Sounds
END:VALARM
DTSTART:20180824T000500Z
DTEND:20180824T030500Z
UID:TaJmoPncU7zN-k9Y8B2MPMdq@stanza.co
SUMMARY:Express vs. Sounds
DESCRIPTION:Express vs. Sounds\n\nFollow on MiLB First Pitch: https://stza.co/+v4LO-3i\n\nShop: https://stza.co/+v4LO-14\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144555Z
LAST-MODIFIED:20180213T144555Z
TRANSP:OPAQUE
END:VEVENT
* Express vs. Baby Cakes
<2018-08-24 Fri 19:05-22:05>
:PROPERTIES:
:ID:       cwywDigjNYXjGFMl-YCSVvCY@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Express vs. Baby Cakes Express vs. Baby Cakes

Follow on MiLB First Pitch  https //stza.co/+v4LP-9

Shop  https //stza.co/+v4LP-37

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Express vs. Baby Cakes
END:VALARM
DTSTART:20180825T000500Z
DTEND:20180825T030500Z
UID:cwywDigjNYXjGFMl-YCSVvCY@stanza.co
SUMMARY:Express vs. Baby Cakes
DESCRIPTION:Express vs. Baby Cakes\n\nFollow on MiLB First Pitch: https://stza.co/+v4LP-9\n\nShop: https://stza.co/+v4LP-37\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144555Z
LAST-MODIFIED:20180213T144555Z
TRANSP:OPAQUE
END:VEVENT
* Express vs. Baby Cakes
<2018-08-25 Sat 19:05-22:05>
:PROPERTIES:
:ID:       RY1t4PBY22c4pGlRFYEVKX2M@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Express vs. Baby Cakes Express vs. Baby Cakes

Follow on MiLB First Pitch  https //stza.co/+v4LS-1V

Shop  https //stza.co/+v4LS-1y

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Express vs. Baby Cakes
END:VALARM
DTSTART:20180826T000500Z
DTEND:20180826T030500Z
UID:RY1t4PBY22c4pGlRFYEVKX2M@stanza.co
SUMMARY:Express vs. Baby Cakes
DESCRIPTION:Express vs. Baby Cakes\n\nFollow on MiLB First Pitch: https://stza.co/+v4LS-1V\n\nShop: https://stza.co/+v4LS-1y\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144555Z
LAST-MODIFIED:20180213T144555Z
TRANSP:OPAQUE
END:VEVENT
* Express vs. Baby Cakes
<2018-08-26 Sun 18:05-21:05>
:PROPERTIES:
:ID:       JrTDf9d5h70GiY6RoA2rJEdX@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Express vs. Baby Cakes Express vs. Baby Cakes

Follow on MiLB First Pitch  https //stza.co/+v4LT-L

Shop  https //stza.co/+v4LT-N

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Express vs. Baby Cakes
END:VALARM
DTSTART:20180826T230500Z
DTEND:20180827T020500Z
UID:JrTDf9d5h70GiY6RoA2rJEdX@stanza.co
SUMMARY:Express vs. Baby Cakes
DESCRIPTION:Express vs. Baby Cakes\n\nFollow on MiLB First Pitch: https://stza.co/+v4LT-L\n\nShop: https://stza.co/+v4LT-N\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144555Z
LAST-MODIFIED:20180213T144555Z
TRANSP:OPAQUE
END:VEVENT
* Express vs. Baby Cakes
<2018-08-27 Mon 19:05-22:05>
:PROPERTIES:
:ID:       wOTWtMKqqL2yU9QnGz4uyhfp@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Express vs. Baby Cakes Express vs. Baby Cakes

Follow on MiLB First Pitch  https //stza.co/+v4LV-1u

Shop  https //stza.co/+v4LV-p

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Express vs. Baby Cakes
END:VALARM
DTSTART:20180828T000500Z
DTEND:20180828T030500Z
UID:wOTWtMKqqL2yU9QnGz4uyhfp@stanza.co
SUMMARY:Express vs. Baby Cakes
DESCRIPTION:Express vs. Baby Cakes\n\nFollow on MiLB First Pitch: https://stza.co/+v4LV-1u\n\nShop: https://stza.co/+v4LV-p\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144555Z
LAST-MODIFIED:20180213T144555Z
TRANSP:OPAQUE
END:VEVENT
* Express vs. Redbirds
<2018-08-28 Tue 19:05-22:05>
:PROPERTIES:
:ID:       05dR2rvDIomvtd64cybrjKfZ@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Express vs. Redbirds Express vs. Redbirds

Follow on MiLB First Pitch  https //stza.co/+v4LX-1z

Shop  https //stza.co/+v4LX-3o

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Express vs. Redbirds
END:VALARM
DTSTART:20180829T000500Z
DTEND:20180829T030500Z
UID:05dR2rvDIomvtd64cybrjKfZ@stanza.co
SUMMARY:Express vs. Redbirds
DESCRIPTION:Express vs. Redbirds\n\nFollow on MiLB First Pitch: https://stza.co/+v4LX-1z\n\nShop: https://stza.co/+v4LX-3o\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144555Z
LAST-MODIFIED:20180213T144555Z
TRANSP:OPAQUE
END:VEVENT
* Express vs. Redbirds
<2018-08-29 Wed 19:05-22:05>
:PROPERTIES:
:ID:       7pQ5CIV4foO3Tg0zwjK0nhuT@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Express vs. Redbirds Express vs. Redbirds

Follow on MiLB First Pitch  https //stza.co/+v4LZ-2g

Shop  https //stza.co/+v4LZ-3u

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Express vs. Redbirds
END:VALARM
DTSTART:20180830T000500Z
DTEND:20180830T030500Z
UID:7pQ5CIV4foO3Tg0zwjK0nhuT@stanza.co
SUMMARY:Express vs. Redbirds
DESCRIPTION:Express vs. Redbirds\n\nFollow on MiLB First Pitch: https://stza.co/+v4LZ-2g\n\nShop: https://stza.co/+v4LZ-3u\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144555Z
LAST-MODIFIED:20180213T144555Z
TRANSP:OPAQUE
END:VEVENT
* Express vs. Redbirds
<2018-08-30 Thu 19:05-22:05>
:PROPERTIES:
:ID:       g6fKYTFvQtKsKWI8Cfz9Va7q@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Express vs. Redbirds Express vs. Redbirds

Follow on MiLB First Pitch  https //stza.co/+v4M0-3A

Shop  https //stza.co/+v4M0-2n

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Express vs. Redbirds
END:VALARM
DTSTART:20180831T000500Z
DTEND:20180831T030500Z
UID:g6fKYTFvQtKsKWI8Cfz9Va7q@stanza.co
SUMMARY:Express vs. Redbirds
DESCRIPTION:Express vs. Redbirds\n\nFollow on MiLB First Pitch: https://stza.co/+v4M0-3A\n\nShop: https://stza.co/+v4M0-2n\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144555Z
LAST-MODIFIED:20180213T144555Z
TRANSP:OPAQUE
END:VEVENT
* Express @ Cubs
<2018-08-31 Fri 19:08-22:08>
:PROPERTIES:
:ID:       rKleetiDHYXM6Uw44T5AgDps@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Express @ Cubs Express @ Cubs

Follow on MiLB First Pitch  https //stza.co/+vKW9-23

Shop  https //stza.co/+vKW9-1d

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Express @ Cubs
END:VALARM
DTSTART:20180901T000800Z
DTEND:20180901T030800Z
UID:rKleetiDHYXM6Uw44T5AgDps@stanza.co
SUMMARY:Express @ Cubs
DESCRIPTION:Express @ Cubs\n\nFollow on MiLB First Pitch: https://stza.co/+vKW9-23\n\nShop: https://stza.co/+vKW9-1d\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144555Z
LAST-MODIFIED:20180213T144555Z
TRANSP:OPAQUE
END:VEVENT
* Express @ Cubs
<2018-09-01 Sat 19:08-22:08>
:PROPERTIES:
:ID:       DSq9oAeVaU7U5yiOF6xzVKPC@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Express @ Cubs Express @ Cubs

Follow on MiLB First Pitch  https //stza.co/+vKWa-I

Shop  https //stza.co/+vKWa-3Q

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Express @ Cubs
END:VALARM
DTSTART:20180902T000800Z
DTEND:20180902T030800Z
UID:DSq9oAeVaU7U5yiOF6xzVKPC@stanza.co
SUMMARY:Express @ Cubs
DESCRIPTION:Express @ Cubs\n\nFollow on MiLB First Pitch: https://stza.co/+vKWa-I\n\nShop: https://stza.co/+vKWa-3Q\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144555Z
LAST-MODIFIED:20180213T144555Z
TRANSP:OPAQUE
END:VEVENT
* Express @ Cubs
<2018-09-02 Sun 13:08-16:08>
:PROPERTIES:
:ID:       bVMobdg3i38byLtMIPshUjBb@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Express @ Cubs Express @ Cubs

Follow on MiLB First Pitch  https //stza.co/+vKWb-u

Shop  https //stza.co/+vKWb-12

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Express @ Cubs
END:VALARM
DTSTART:20180902T180800Z
DTEND:20180902T210800Z
UID:bVMobdg3i38byLtMIPshUjBb@stanza.co
SUMMARY:Express @ Cubs
DESCRIPTION:Express @ Cubs\n\nFollow on MiLB First Pitch: https://stza.co/+vKWb-u\n\nShop: https://stza.co/+vKWb-12\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144555Z
LAST-MODIFIED:20180213T144555Z
TRANSP:OPAQUE
END:VEVENT
* Express @ Cubs
<2018-09-03 Mon 12:08-15:08>
:PROPERTIES:
:ID:       _KUKEzkUrR7cLh23g5z148bs@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Express @ Cubs Express @ Cubs

Follow on MiLB First Pitch  https //stza.co/+whQe-1F

Shop  https //stza.co/+whQe-1a

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Express @ Cubs
END:VALARM
DTSTART:20180903T170800Z
DTEND:20180903T200800Z
UID:_KUKEzkUrR7cLh23g5z148bs@stanza.co
SUMMARY:Express @ Cubs
DESCRIPTION:Express @ Cubs\n\nFollow on MiLB First Pitch: https://stza.co/+whQe-1F\n\nShop: https://stza.co/+whQe-1a\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144555Z
LAST-MODIFIED:20180213T144555Z
TRANSP:OPAQUE
END:VEVENT
