#+TITLE:       Main Google calendar entries
#+AUTHOR:      Eric S Fraga
#+EMAIL:       e.fraga@ucl.ac.uk
#+DESCRIPTION: converted using the ical2org awk script
#+CATEGORY:    google
#+STARTUP:     hidestars
#+STARTUP:     overview

* COMMENT original iCal preamble

* Power vs. Drive
<2018-04-05 Thu 18:05-21:05>
:PROPERTIES:
:ID:       yLoglC6xwb5O0yjh069N6D8B@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Power vs. Drive Power vs. Drive

Follow on MiLB First Pitch  https //stza.co/+xJ4z-T

Shop  https //stza.co/+xJ4z-M

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Power vs. Drive
END:VALARM
DTSTART:20180405T230500Z
DTEND:20180406T020500Z
UID:yLoglC6xwb5O0yjh069N6D8B@stanza.co
SUMMARY:Power vs. Drive
DESCRIPTION:Power vs. Drive\n\nFollow on MiLB First Pitch: https://stza.co/+xJ4z-T\n\nShop: https://stza.co/+xJ4z-M\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144605Z
LAST-MODIFIED:20180213T144605Z
TRANSP:OPAQUE
END:VEVENT
* Power vs. Drive
<2018-04-06 Fri 18:05-21:05>
:PROPERTIES:
:ID:       hlh2GIFv7Imzlet0Hru-NzL9@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Power vs. Drive Power vs. Drive

Follow on MiLB First Pitch  https //stza.co/+xJ4C-1q

Shop  https //stza.co/+xJ4C-L

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Power vs. Drive
END:VALARM
DTSTART:20180406T230500Z
DTEND:20180407T020500Z
UID:hlh2GIFv7Imzlet0Hru-NzL9@stanza.co
SUMMARY:Power vs. Drive
DESCRIPTION:Power vs. Drive\n\nFollow on MiLB First Pitch: https://stza.co/+xJ4C-1q\n\nShop: https://stza.co/+xJ4C-L\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144605Z
LAST-MODIFIED:20180213T144605Z
TRANSP:OPAQUE
END:VEVENT
* Power vs. Drive
<2018-04-07 Sat 13:05-16:05>
:PROPERTIES:
:ID:       6jjI7cCD9tMcrZDUbmq3IIm-@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Power vs. Drive Power vs. Drive

Follow on MiLB First Pitch  https //stza.co/+xJ4E-2y

Shop  https //stza.co/+xJ4E-2$

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Power vs. Drive
END:VALARM
DTSTART:20180407T180500Z
DTEND:20180407T210500Z
UID:6jjI7cCD9tMcrZDUbmq3IIm-@stanza.co
SUMMARY:Power vs. Drive
DESCRIPTION:Power vs. Drive\n\nFollow on MiLB First Pitch: https://stza.co/+xJ4E-2y\n\nShop: https://stza.co/+xJ4E-2$\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144605Z
LAST-MODIFIED:20180213T144605Z
TRANSP:OPAQUE
END:VEVENT
* Power vs. Drive
<2018-04-08 Sun 13:05-16:05>
:PROPERTIES:
:ID:       5qW5oafQAnof6GtW33XHXP7I@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Power vs. Drive Power vs. Drive

Follow on MiLB First Pitch  https //stza.co/+xJ4F-3d

Shop  https //stza.co/+xJ4F-_

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Power vs. Drive
END:VALARM
DTSTART:20180408T180500Z
DTEND:20180408T210500Z
UID:5qW5oafQAnof6GtW33XHXP7I@stanza.co
SUMMARY:Power vs. Drive
DESCRIPTION:Power vs. Drive\n\nFollow on MiLB First Pitch: https://stza.co/+xJ4F-3d\n\nShop: https://stza.co/+xJ4F-_\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144605Z
LAST-MODIFIED:20180213T144605Z
TRANSP:OPAQUE
END:VEVENT
* Power vs. BlueClaws
<2018-04-09 Mon 18:05-21:05>
:PROPERTIES:
:ID:       mG-i7MDFB0HlDm1ImVOAUvj4@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Power vs. BlueClaws Power vs. BlueClaws

Follow on MiLB First Pitch  https //stza.co/+xJ4I-2K

Shop  https //stza.co/+xJ4I-2G

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Power vs. BlueClaws
END:VALARM
DTSTART:20180409T230500Z
DTEND:20180410T020500Z
UID:mG-i7MDFB0HlDm1ImVOAUvj4@stanza.co
SUMMARY:Power vs. BlueClaws
DESCRIPTION:Power vs. BlueClaws\n\nFollow on MiLB First Pitch: https://stza.co/+xJ4I-2K\n\nShop: https://stza.co/+xJ4I-2G\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144605Z
LAST-MODIFIED:20180213T144605Z
TRANSP:OPAQUE
END:VEVENT
* Power vs. BlueClaws
<2018-04-10 Tue 18:05-21:05>
:PROPERTIES:
:ID:       SnOssHIxcd1IsH6CfUTBZXR5@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Power vs. BlueClaws Power vs. BlueClaws

Follow on MiLB First Pitch  https //stza.co/+xJ4K-2o

Shop  https //stza.co/+xJ4K-3p

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Power vs. BlueClaws
END:VALARM
DTSTART:20180410T230500Z
DTEND:20180411T020500Z
UID:SnOssHIxcd1IsH6CfUTBZXR5@stanza.co
SUMMARY:Power vs. BlueClaws
DESCRIPTION:Power vs. BlueClaws\n\nFollow on MiLB First Pitch: https://stza.co/+xJ4K-2o\n\nShop: https://stza.co/+xJ4K-3p\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144605Z
LAST-MODIFIED:20180213T144605Z
TRANSP:OPAQUE
END:VEVENT
* Power vs. BlueClaws
<2018-04-11 Wed 09:35-12:35>
:PROPERTIES:
:ID:       lD8Wo2xhqbBTNVaBvXAttynf@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Power vs. BlueClaws Power vs. BlueClaws

Follow on MiLB First Pitch  https //stza.co/+xJ4L-I

Shop  https //stza.co/+xJ4L-C

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Power vs. BlueClaws
END:VALARM
DTSTART:20180411T143500Z
DTEND:20180411T173500Z
UID:lD8Wo2xhqbBTNVaBvXAttynf@stanza.co
SUMMARY:Power vs. BlueClaws
DESCRIPTION:Power vs. BlueClaws\n\nFollow on MiLB First Pitch: https://stza.co/+xJ4L-I\n\nShop: https://stza.co/+xJ4L-C\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144605Z
LAST-MODIFIED:20180213T144605Z
TRANSP:OPAQUE
END:VEVENT
* Power @ Crawdads
<2018-04-12 Thu 18:00-21:00>
:PROPERTIES:
:ID:       QVFsyH5uhHqFnafS9nhV_CIJ@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Power @ Crawdads Power @ Crawdads

Follow on MiLB First Pitch  https //stza.co/+w0R9-1D

Shop  https //stza.co/+w0R9-1M

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Power @ Crawdads
END:VALARM
DTSTART:20180412T230000Z
DTEND:20180413T020000Z
UID:QVFsyH5uhHqFnafS9nhV_CIJ@stanza.co
SUMMARY:Power @ Crawdads
DESCRIPTION:Power @ Crawdads\n\nFollow on MiLB First Pitch: https://stza.co/+w0R9-1D\n\nShop: https://stza.co/+w0R9-1M\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144605Z
LAST-MODIFIED:20180213T144605Z
TRANSP:OPAQUE
END:VEVENT
* Power @ Crawdads
<2018-04-13 Fri 18:00-21:00>
:PROPERTIES:
:ID:       vYboFNDSne-SNejGIk23Y6UL@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Power @ Crawdads Power @ Crawdads

Follow on MiLB First Pitch  https //stza.co/+w0Ra-3t

Shop  https //stza.co/+w0Ra-2l

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Power @ Crawdads
END:VALARM
DTSTART:20180413T230000Z
DTEND:20180414T020000Z
UID:vYboFNDSne-SNejGIk23Y6UL@stanza.co
SUMMARY:Power @ Crawdads
DESCRIPTION:Power @ Crawdads\n\nFollow on MiLB First Pitch: https://stza.co/+w0Ra-3t\n\nShop: https://stza.co/+w0Ra-2l\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144605Z
LAST-MODIFIED:20180213T144605Z
TRANSP:OPAQUE
END:VEVENT
* Power @ Crawdads
<2018-04-14 Sat 17:00-20:00>
:PROPERTIES:
:ID:       NrbR8eTCI_RQIuuasx9L2VMr@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Power @ Crawdads Power @ Crawdads

Follow on MiLB First Pitch  https //stza.co/+w0Rb-v

Shop  https //stza.co/+w0Rb-1z

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Power @ Crawdads
END:VALARM
DTSTART:20180414T220000Z
DTEND:20180415T010000Z
UID:NrbR8eTCI_RQIuuasx9L2VMr@stanza.co
SUMMARY:Power @ Crawdads
DESCRIPTION:Power @ Crawdads\n\nFollow on MiLB First Pitch: https://stza.co/+w0Rb-v\n\nShop: https://stza.co/+w0Rb-1z\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144605Z
LAST-MODIFIED:20180213T144605Z
TRANSP:OPAQUE
END:VEVENT
* Power @ Crawdads
<2018-04-15 Sun 14:00-17:00>
:PROPERTIES:
:ID:       dhOcwM4oOA39YLos2mcv4bit@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Power @ Crawdads Power @ Crawdads

Follow on MiLB First Pitch  https //stza.co/+w0Rc-2U

Shop  https //stza.co/+w0Rc-y

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Power @ Crawdads
END:VALARM
DTSTART:20180415T190000Z
DTEND:20180415T220000Z
UID:dhOcwM4oOA39YLos2mcv4bit@stanza.co
SUMMARY:Power @ Crawdads
DESCRIPTION:Power @ Crawdads\n\nFollow on MiLB First Pitch: https://stza.co/+w0Rc-2U\n\nShop: https://stza.co/+w0Rc-y\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144605Z
LAST-MODIFIED:20180213T144605Z
TRANSP:OPAQUE
END:VEVENT
* Power @ RiverDogs
<2018-04-16 Mon 18:05-21:05>
:PROPERTIES:
:ID:       REyRf8OWNFgc5tjBbnDfzUdJ@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Power @ RiverDogs Power @ RiverDogs

Follow on MiLB First Pitch  https //stza.co/+vO0C-1h

Shop  https //stza.co/+vO0C-34

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Power @ RiverDogs
END:VALARM
DTSTART:20180416T230500Z
DTEND:20180417T020500Z
UID:REyRf8OWNFgc5tjBbnDfzUdJ@stanza.co
SUMMARY:Power @ RiverDogs
DESCRIPTION:Power @ RiverDogs\n\nFollow on MiLB First Pitch: https://stza.co/+vO0C-1h\n\nShop: https://stza.co/+vO0C-34\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144605Z
LAST-MODIFIED:20180213T144605Z
TRANSP:OPAQUE
END:VEVENT
* Power @ RiverDogs
<2018-04-17 Tue 18:05-21:05>
:PROPERTIES:
:ID:       a8HmstELZWsHcb7UIr1xP8kz@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Power @ RiverDogs Power @ RiverDogs

Follow on MiLB First Pitch  https //stza.co/+vO0D-2s

Shop  https //stza.co/+vO0D-15

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Power @ RiverDogs
END:VALARM
DTSTART:20180417T230500Z
DTEND:20180418T020500Z
UID:a8HmstELZWsHcb7UIr1xP8kz@stanza.co
SUMMARY:Power @ RiverDogs
DESCRIPTION:Power @ RiverDogs\n\nFollow on MiLB First Pitch: https://stza.co/+vO0D-2s\n\nShop: https://stza.co/+vO0D-15\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144605Z
LAST-MODIFIED:20180213T144605Z
TRANSP:OPAQUE
END:VEVENT
* Power @ RiverDogs
<2018-04-18 Wed 10:05-13:05>
:PROPERTIES:
:ID:       -z19WrP2UhzhibFQcjj_YsCd@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Power @ RiverDogs Power @ RiverDogs

Follow on MiLB First Pitch  https //stza.co/+vO0E-1z

Shop  https //stza.co/+vO0E-1j

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Power @ RiverDogs
END:VALARM
DTSTART:20180418T150500Z
DTEND:20180418T180500Z
UID:-z19WrP2UhzhibFQcjj_YsCd@stanza.co
SUMMARY:Power @ RiverDogs
DESCRIPTION:Power @ RiverDogs\n\nFollow on MiLB First Pitch: https://stza.co/+vO0E-1z\n\nShop: https://stza.co/+vO0E-1j\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144605Z
LAST-MODIFIED:20180213T144605Z
TRANSP:OPAQUE
END:VEVENT
* Power vs. Tourists
<2018-04-19 Thu 18:05-21:05>
:PROPERTIES:
:ID:       GJMmwsOzmm9js3mPIdSBw7h0@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Power vs. Tourists Power vs. Tourists

Follow on MiLB First Pitch  https //stza.co/+xJ4N-7

Shop  https //stza.co/+xJ4N-2Q

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Power vs. Tourists
END:VALARM
DTSTART:20180419T230500Z
DTEND:20180420T020500Z
UID:GJMmwsOzmm9js3mPIdSBw7h0@stanza.co
SUMMARY:Power vs. Tourists
DESCRIPTION:Power vs. Tourists\n\nFollow on MiLB First Pitch: https://stza.co/+xJ4N-7\n\nShop: https://stza.co/+xJ4N-2Q\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144605Z
LAST-MODIFIED:20180213T144605Z
TRANSP:OPAQUE
END:VEVENT
* Power vs. Tourists
<2018-04-20 Fri 18:05-21:05>
:PROPERTIES:
:ID:       iq1PSBgUY-X_LA3d-6htBuAQ@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Power vs. Tourists Power vs. Tourists

Follow on MiLB First Pitch  https //stza.co/+xJ4P-28

Shop  https //stza.co/+xJ4P-2Y

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Power vs. Tourists
END:VALARM
DTSTART:20180420T230500Z
DTEND:20180421T020500Z
UID:iq1PSBgUY-X_LA3d-6htBuAQ@stanza.co
SUMMARY:Power vs. Tourists
DESCRIPTION:Power vs. Tourists\n\nFollow on MiLB First Pitch: https://stza.co/+xJ4P-28\n\nShop: https://stza.co/+xJ4P-2Y\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144605Z
LAST-MODIFIED:20180213T144605Z
TRANSP:OPAQUE
END:VEVENT
* Power vs. Tourists
<2018-04-21 Sat 13:05-16:05>
:PROPERTIES:
:ID:       1zbUjzB3nLy9jEPVRst0Pfqv@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Power vs. Tourists Power vs. Tourists

Follow on MiLB First Pitch  https //stza.co/+xJ4S-3z

Shop  https //stza.co/+xJ4S-t

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Power vs. Tourists
END:VALARM
DTSTART:20180421T180500Z
DTEND:20180421T210500Z
UID:1zbUjzB3nLy9jEPVRst0Pfqv@stanza.co
SUMMARY:Power vs. Tourists
DESCRIPTION:Power vs. Tourists\n\nFollow on MiLB First Pitch: https://stza.co/+xJ4S-3z\n\nShop: https://stza.co/+xJ4S-t\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144605Z
LAST-MODIFIED:20180213T144605Z
TRANSP:OPAQUE
END:VEVENT
* Power vs. Tourists
<2018-04-22 Sun 13:05-16:05>
:PROPERTIES:
:ID:       EOW0Q318KP1dxfNb1klT_YLx@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Power vs. Tourists Power vs. Tourists

Follow on MiLB First Pitch  https //stza.co/+xJ4T-35

Shop  https //stza.co/+xJ4T-y

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Power vs. Tourists
END:VALARM
DTSTART:20180422T180500Z
DTEND:20180422T210500Z
UID:EOW0Q318KP1dxfNb1klT_YLx@stanza.co
SUMMARY:Power vs. Tourists
DESCRIPTION:Power vs. Tourists\n\nFollow on MiLB First Pitch: https://stza.co/+xJ4T-35\n\nShop: https://stza.co/+xJ4T-y\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144605Z
LAST-MODIFIED:20180213T144605Z
TRANSP:OPAQUE
END:VEVENT
* Power vs. Braves
<2018-04-23 Mon 18:05-21:05>
:PROPERTIES:
:ID:       PyRT5NDfJLnseL7obBNobYld@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Power vs. Braves Power vs. Braves

Follow on MiLB First Pitch  https //stza.co/+xJ4W-s

Shop  https //stza.co/+xJ4W-3S

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Power vs. Braves
END:VALARM
DTSTART:20180423T230500Z
DTEND:20180424T020500Z
UID:PyRT5NDfJLnseL7obBNobYld@stanza.co
SUMMARY:Power vs. Braves
DESCRIPTION:Power vs. Braves\n\nFollow on MiLB First Pitch: https://stza.co/+xJ4W-s\n\nShop: https://stza.co/+xJ4W-3S\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144605Z
LAST-MODIFIED:20180213T144605Z
TRANSP:OPAQUE
END:VEVENT
* Power vs. Braves
<2018-04-24 Tue 09:35-12:35>
:PROPERTIES:
:ID:       h_7vwmq87t2j0XVeAupQl8It@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Power vs. Braves Power vs. Braves

Follow on MiLB First Pitch  https //stza.co/+xJ4Y-v

Shop  https //stza.co/+xJ4Y-2D

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Power vs. Braves
END:VALARM
DTSTART:20180424T143500Z
DTEND:20180424T173500Z
UID:h_7vwmq87t2j0XVeAupQl8It@stanza.co
SUMMARY:Power vs. Braves
DESCRIPTION:Power vs. Braves\n\nFollow on MiLB First Pitch: https://stza.co/+xJ4Y-v\n\nShop: https://stza.co/+xJ4Y-2D\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144605Z
LAST-MODIFIED:20180213T144605Z
TRANSP:OPAQUE
END:VEVENT
* Power vs. Braves
<2018-04-25 Wed 18:05-21:05>
:PROPERTIES:
:ID:       7Z_Eu3L7ybwRlX2inNPyjVAQ@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Power vs. Braves Power vs. Braves

Follow on MiLB First Pitch  https //stza.co/+xJ4Z-2y

Shop  https //stza.co/+xJ4Z-3d

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Power vs. Braves
END:VALARM
DTSTART:20180425T230500Z
DTEND:20180426T020500Z
UID:7Z_Eu3L7ybwRlX2inNPyjVAQ@stanza.co
SUMMARY:Power vs. Braves
DESCRIPTION:Power vs. Braves\n\nFollow on MiLB First Pitch: https://stza.co/+xJ4Z-2y\n\nShop: https://stza.co/+xJ4Z-3d\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144605Z
LAST-MODIFIED:20180213T144605Z
TRANSP:OPAQUE
END:VEVENT
* Power vs. Braves
<2018-04-26 Thu 18:05-21:05>
:PROPERTIES:
:ID:       jlp1Fumdc9Afzn7GJn58zs9A@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Power vs. Braves Power vs. Braves

Follow on MiLB First Pitch  https //stza.co/+xJ50-3u

Shop  https //stza.co/+xJ50-3T

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Power vs. Braves
END:VALARM
DTSTART:20180426T230500Z
DTEND:20180427T020500Z
UID:jlp1Fumdc9Afzn7GJn58zs9A@stanza.co
SUMMARY:Power vs. Braves
DESCRIPTION:Power vs. Braves\n\nFollow on MiLB First Pitch: https://stza.co/+xJ50-3u\n\nShop: https://stza.co/+xJ50-3T\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144605Z
LAST-MODIFIED:20180213T144605Z
TRANSP:OPAQUE
END:VEVENT
* Power @ Legends
<2018-04-27 Fri 18:05-21:05>
:PROPERTIES:
:ID:       oppWOnEgXpih1V36QgfN3sNr@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Power @ Legends Power @ Legends

Follow on MiLB First Pitch  https //stza.co/+xC1s-3r

Shop  https //stza.co/+xC1s-I

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Power @ Legends
END:VALARM
DTSTART:20180427T230500Z
DTEND:20180428T020500Z
UID:oppWOnEgXpih1V36QgfN3sNr@stanza.co
SUMMARY:Power @ Legends
DESCRIPTION:Power @ Legends\n\nFollow on MiLB First Pitch: https://stza.co/+xC1s-3r\n\nShop: https://stza.co/+xC1s-I\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144605Z
LAST-MODIFIED:20180213T144605Z
TRANSP:OPAQUE
END:VEVENT
* Power @ Legends
<2018-04-28 Sat 17:35-20:35>
:PROPERTIES:
:ID:       1Zs8tq1CHxD7ZXM_2eqesmuH@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Power @ Legends Power @ Legends

Follow on MiLB First Pitch  https //stza.co/+xC1w-34

Shop  https //stza.co/+xC1w-1l

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Power @ Legends
END:VALARM
DTSTART:20180428T223500Z
DTEND:20180429T013500Z
UID:1Zs8tq1CHxD7ZXM_2eqesmuH@stanza.co
SUMMARY:Power @ Legends
DESCRIPTION:Power @ Legends\n\nFollow on MiLB First Pitch: https://stza.co/+xC1w-34\n\nShop: https://stza.co/+xC1w-1l\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144605Z
LAST-MODIFIED:20180213T144605Z
TRANSP:OPAQUE
END:VEVENT
* Power @ Legends
<2018-04-29 Sun 13:05-16:05>
:PROPERTIES:
:ID:       9-MR7y_SBmxFaTSIpgvWsp-U@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Power @ Legends Power @ Legends

Follow on MiLB First Pitch  https //stza.co/+xC1A-2$

Shop  https //stza.co/+xC1A-2W

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Power @ Legends
END:VALARM
DTSTART:20180429T180500Z
DTEND:20180429T210500Z
UID:9-MR7y_SBmxFaTSIpgvWsp-U@stanza.co
SUMMARY:Power @ Legends
DESCRIPTION:Power @ Legends\n\nFollow on MiLB First Pitch: https://stza.co/+xC1A-2$\n\nShop: https://stza.co/+xC1A-2W\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144605Z
LAST-MODIFIED:20180213T144605Z
TRANSP:OPAQUE
END:VEVENT
* Power vs. GreenJackets
<2018-05-01 Tue 18:05-21:05>
:PROPERTIES:
:ID:       Wmdx51Z67MVw8ph2ADaBfObl@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Power vs. GreenJackets Power vs. GreenJackets

Follow on MiLB First Pitch  https //stza.co/+xJ52-C

Shop  https //stza.co/+xJ52-3o

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Power vs. GreenJackets
END:VALARM
DTSTART:20180501T230500Z
DTEND:20180502T020500Z
UID:Wmdx51Z67MVw8ph2ADaBfObl@stanza.co
SUMMARY:Power vs. GreenJackets
DESCRIPTION:Power vs. GreenJackets\n\nFollow on MiLB First Pitch: https://stza.co/+xJ52-C\n\nShop: https://stza.co/+xJ52-3o\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144605Z
LAST-MODIFIED:20180213T144605Z
TRANSP:OPAQUE
END:VEVENT
* Power vs. GreenJackets
<2018-05-02 Wed 18:05-21:05>
:PROPERTIES:
:ID:       9C3hxfow5frf32DhCGvKyUbB@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Power vs. GreenJackets Power vs. GreenJackets

Follow on MiLB First Pitch  https //stza.co/+xJ54-3O

Shop  https //stza.co/+xJ54-24

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Power vs. GreenJackets
END:VALARM
DTSTART:20180502T230500Z
DTEND:20180503T020500Z
UID:9C3hxfow5frf32DhCGvKyUbB@stanza.co
SUMMARY:Power vs. GreenJackets
DESCRIPTION:Power vs. GreenJackets\n\nFollow on MiLB First Pitch: https://stza.co/+xJ54-3O\n\nShop: https://stza.co/+xJ54-24\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144605Z
LAST-MODIFIED:20180213T144605Z
TRANSP:OPAQUE
END:VEVENT
* Power vs. GreenJackets
<2018-05-03 Thu 18:05-21:05>
:PROPERTIES:
:ID:       rjEBWCCHQFBVUyzdONdlUId1@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Power vs. GreenJackets Power vs. GreenJackets

Follow on MiLB First Pitch  https //stza.co/+xJ56-3G

Shop  https //stza.co/+xJ56-12

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Power vs. GreenJackets
END:VALARM
DTSTART:20180503T230500Z
DTEND:20180504T020500Z
UID:rjEBWCCHQFBVUyzdONdlUId1@stanza.co
SUMMARY:Power vs. GreenJackets
DESCRIPTION:Power vs. GreenJackets\n\nFollow on MiLB First Pitch: https://stza.co/+xJ56-3G\n\nShop: https://stza.co/+xJ56-12\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144605Z
LAST-MODIFIED:20180213T144605Z
TRANSP:OPAQUE
END:VEVENT
* Power vs. Crawdads
<2018-05-04 Fri 18:05-21:05>
:PROPERTIES:
:ID:       ZaWrkIdhdBtY1gJa-Le61G1W@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Power vs. Crawdads Power vs. Crawdads

Follow on MiLB First Pitch  https //stza.co/+xJ57-3U

Shop  https //stza.co/+xJ57-u

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Power vs. Crawdads
END:VALARM
DTSTART:20180504T230500Z
DTEND:20180505T020500Z
UID:ZaWrkIdhdBtY1gJa-Le61G1W@stanza.co
SUMMARY:Power vs. Crawdads
DESCRIPTION:Power vs. Crawdads\n\nFollow on MiLB First Pitch: https://stza.co/+xJ57-3U\n\nShop: https://stza.co/+xJ57-u\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144605Z
LAST-MODIFIED:20180213T144605Z
TRANSP:OPAQUE
END:VEVENT
* Power vs. Crawdads
<2018-05-05 Sat 17:05-20:05>
:PROPERTIES:
:ID:       h3oioNBZHrjSjAW_J6pZXyi4@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Power vs. Crawdads Power vs. Crawdads

Follow on MiLB First Pitch  https //stza.co/+xJ5a-34

Shop  https //stza.co/+xJ5a-3f

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Power vs. Crawdads
END:VALARM
DTSTART:20180505T220500Z
DTEND:20180506T010500Z
UID:h3oioNBZHrjSjAW_J6pZXyi4@stanza.co
SUMMARY:Power vs. Crawdads
DESCRIPTION:Power vs. Crawdads\n\nFollow on MiLB First Pitch: https://stza.co/+xJ5a-34\n\nShop: https://stza.co/+xJ5a-3f\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144605Z
LAST-MODIFIED:20180213T144605Z
TRANSP:OPAQUE
END:VEVENT
* Power vs. Crawdads
<2018-05-06 Sun 13:05-16:05>
:PROPERTIES:
:ID:       r_k2JY5AjPeJ-lP0nJtmoRFh@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Power vs. Crawdads Power vs. Crawdads

Follow on MiLB First Pitch  https //stza.co/+xJ5c-2a

Shop  https //stza.co/+xJ5c-V

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Power vs. Crawdads
END:VALARM
DTSTART:20180506T180500Z
DTEND:20180506T210500Z
UID:r_k2JY5AjPeJ-lP0nJtmoRFh@stanza.co
SUMMARY:Power vs. Crawdads
DESCRIPTION:Power vs. Crawdads\n\nFollow on MiLB First Pitch: https://stza.co/+xJ5c-2a\n\nShop: https://stza.co/+xJ5c-V\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144605Z
LAST-MODIFIED:20180213T144605Z
TRANSP:OPAQUE
END:VEVENT
* Power vs. Crawdads
<2018-05-07 Mon 18:05-21:05>
:PROPERTIES:
:ID:       8wsfAMDMyPefjaO1zvscZ71i@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Power vs. Crawdads Power vs. Crawdads

Follow on MiLB First Pitch  https //stza.co/+xJ5e-24

Shop  https //stza.co/+xJ5e-36

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Power vs. Crawdads
END:VALARM
DTSTART:20180507T230500Z
DTEND:20180508T020500Z
UID:8wsfAMDMyPefjaO1zvscZ71i@stanza.co
SUMMARY:Power vs. Crawdads
DESCRIPTION:Power vs. Crawdads\n\nFollow on MiLB First Pitch: https://stza.co/+xJ5e-24\n\nShop: https://stza.co/+xJ5e-36\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144605Z
LAST-MODIFIED:20180213T144605Z
TRANSP:OPAQUE
END:VEVENT
* Power @ Suns
<2018-05-09 Wed 18:05-21:05>
:PROPERTIES:
:ID:       F0OHY-QbCqswskWF3IJRj2Co@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Power @ Suns Power @ Suns

Follow on MiLB First Pitch  https //stza.co/+xGGj-u

Shop  https //stza.co/+xGGj-H

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Power @ Suns
END:VALARM
DTSTART:20180509T230500Z
DTEND:20180510T020500Z
UID:F0OHY-QbCqswskWF3IJRj2Co@stanza.co
SUMMARY:Power @ Suns
DESCRIPTION:Power @ Suns\n\nFollow on MiLB First Pitch: https://stza.co/+xGGj-u\n\nShop: https://stza.co/+xGGj-H\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144605Z
LAST-MODIFIED:20180213T144605Z
TRANSP:OPAQUE
END:VEVENT
* Power @ Suns
<2018-05-10 Thu 18:05-21:05>
:PROPERTIES:
:ID:       4rHvV2QYHSJJH-baPPoYMQsI@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Power @ Suns Power @ Suns

Follow on MiLB First Pitch  https //stza.co/+xGGk-3y

Shop  https //stza.co/+xGGk-3V

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Power @ Suns
END:VALARM
DTSTART:20180510T230500Z
DTEND:20180511T020500Z
UID:4rHvV2QYHSJJH-baPPoYMQsI@stanza.co
SUMMARY:Power @ Suns
DESCRIPTION:Power @ Suns\n\nFollow on MiLB First Pitch: https://stza.co/+xGGk-3y\n\nShop: https://stza.co/+xGGk-3V\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144605Z
LAST-MODIFIED:20180213T144605Z
TRANSP:OPAQUE
END:VEVENT
* Power @ Suns
<2018-05-11 Fri 18:05-21:05>
:PROPERTIES:
:ID:       ObT2QB5zhildEAJXyLi4qFup@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Power @ Suns Power @ Suns

Follow on MiLB First Pitch  https //stza.co/+xF9e-2k

Shop  https //stza.co/+xF9e-29

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Power @ Suns
END:VALARM
DTSTART:20180511T230500Z
DTEND:20180512T020500Z
UID:ObT2QB5zhildEAJXyLi4qFup@stanza.co
SUMMARY:Power @ Suns
DESCRIPTION:Power @ Suns\n\nFollow on MiLB First Pitch: https://stza.co/+xF9e-2k\n\nShop: https://stza.co/+xF9e-29\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144605Z
LAST-MODIFIED:20180213T144605Z
TRANSP:OPAQUE
END:VEVENT
* Power @ BlueClaws
<2018-05-12 Sat 15:05-18:05>
:PROPERTIES:
:ID:       3Yse70k6fE8ZvZTjY21akEaD@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Power @ BlueClaws Power @ BlueClaws

Follow on MiLB First Pitch  https //stza.co/+vO1i-2G

Shop  https //stza.co/+vO1i-2s

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Power @ BlueClaws
END:VALARM
DTSTART:20180512T200500Z
DTEND:20180512T230500Z
UID:3Yse70k6fE8ZvZTjY21akEaD@stanza.co
SUMMARY:Power @ BlueClaws
DESCRIPTION:Power @ BlueClaws\n\nFollow on MiLB First Pitch: https://stza.co/+vO1i-2G\n\nShop: https://stza.co/+vO1i-2s\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144605Z
LAST-MODIFIED:20180213T144605Z
TRANSP:OPAQUE
END:VEVENT
* Power @ BlueClaws
<2018-05-13 Sun 12:05-15:05>
:PROPERTIES:
:ID:       dbJmFH_FgyDCXDG0TLI86MtR@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Power @ BlueClaws Power @ BlueClaws

Follow on MiLB First Pitch  https //stza.co/+vO1j-14

Shop  https //stza.co/+vO1j-2W

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Power @ BlueClaws
END:VALARM
DTSTART:20180513T170500Z
DTEND:20180513T200500Z
UID:dbJmFH_FgyDCXDG0TLI86MtR@stanza.co
SUMMARY:Power @ BlueClaws
DESCRIPTION:Power @ BlueClaws\n\nFollow on MiLB First Pitch: https://stza.co/+vO1j-14\n\nShop: https://stza.co/+vO1j-2W\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144605Z
LAST-MODIFIED:20180213T144605Z
TRANSP:OPAQUE
END:VEVENT
* Power @ BlueClaws
<2018-05-14 Mon 17:35-20:35>
:PROPERTIES:
:ID:       HbLUH4Gu-ogdgierv-wAY6UJ@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Power @ BlueClaws Power @ BlueClaws

Follow on MiLB First Pitch  https //stza.co/+vO1k-2$

Shop  https //stza.co/+vO1k-2v

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Power @ BlueClaws
END:VALARM
DTSTART:20180514T223500Z
DTEND:20180515T013500Z
UID:HbLUH4Gu-ogdgierv-wAY6UJ@stanza.co
SUMMARY:Power @ BlueClaws
DESCRIPTION:Power @ BlueClaws\n\nFollow on MiLB First Pitch: https://stza.co/+vO1k-2$\n\nShop: https://stza.co/+vO1k-2v\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144605Z
LAST-MODIFIED:20180213T144605Z
TRANSP:OPAQUE
END:VEVENT
* Power @ BlueClaws
<2018-05-15 Tue 17:35-20:35>
:PROPERTIES:
:ID:       wEfkyyBYz6jd0Zp66ygRjTjf@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Power @ BlueClaws Power @ BlueClaws

Follow on MiLB First Pitch  https //stza.co/+vO1l-1X

Shop  https //stza.co/+vO1l-B

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Power @ BlueClaws
END:VALARM
DTSTART:20180515T223500Z
DTEND:20180516T013500Z
UID:wEfkyyBYz6jd0Zp66ygRjTjf@stanza.co
SUMMARY:Power @ BlueClaws
DESCRIPTION:Power @ BlueClaws\n\nFollow on MiLB First Pitch: https://stza.co/+vO1l-1X\n\nShop: https://stza.co/+vO1l-B\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144605Z
LAST-MODIFIED:20180213T144605Z
TRANSP:OPAQUE
END:VEVENT
* Power vs. Legends
<2018-05-17 Thu 18:05-21:05>
:PROPERTIES:
:ID:       2XcUQuTb3c9lCLMM9lSxcWIi@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Power vs. Legends Power vs. Legends

Follow on MiLB First Pitch  https //stza.co/+xJ5g-1b

Shop  https //stza.co/+xJ5g-3J

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Power vs. Legends
END:VALARM
DTSTART:20180517T230500Z
DTEND:20180518T020500Z
UID:2XcUQuTb3c9lCLMM9lSxcWIi@stanza.co
SUMMARY:Power vs. Legends
DESCRIPTION:Power vs. Legends\n\nFollow on MiLB First Pitch: https://stza.co/+xJ5g-1b\n\nShop: https://stza.co/+xJ5g-3J\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144605Z
LAST-MODIFIED:20180213T144605Z
TRANSP:OPAQUE
END:VEVENT
* Power vs. Legends
<2018-05-18 Fri 18:05-21:05>
:PROPERTIES:
:ID:       nGABFV5AGv3F8wfs_D3KS2rz@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Power vs. Legends Power vs. Legends

Follow on MiLB First Pitch  https //stza.co/+xJ5h-2C

Shop  https //stza.co/+xJ5h-b

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Power vs. Legends
END:VALARM
DTSTART:20180518T230500Z
DTEND:20180519T020500Z
UID:nGABFV5AGv3F8wfs_D3KS2rz@stanza.co
SUMMARY:Power vs. Legends
DESCRIPTION:Power vs. Legends\n\nFollow on MiLB First Pitch: https://stza.co/+xJ5h-2C\n\nShop: https://stza.co/+xJ5h-b\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144605Z
LAST-MODIFIED:20180213T144605Z
TRANSP:OPAQUE
END:VEVENT
* Power vs. Legends
<2018-05-19 Sat 17:05-20:05>
:PROPERTIES:
:ID:       U8h67-qYq7QHRBMmO4puPN2K@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Power vs. Legends Power vs. Legends

Follow on MiLB First Pitch  https //stza.co/+xJ5k-3i

Shop  https //stza.co/+xJ5k-z

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Power vs. Legends
END:VALARM
DTSTART:20180519T220500Z
DTEND:20180520T010500Z
UID:U8h67-qYq7QHRBMmO4puPN2K@stanza.co
SUMMARY:Power vs. Legends
DESCRIPTION:Power vs. Legends\n\nFollow on MiLB First Pitch: https://stza.co/+xJ5k-3i\n\nShop: https://stza.co/+xJ5k-z\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144605Z
LAST-MODIFIED:20180213T144605Z
TRANSP:OPAQUE
END:VEVENT
* Power vs. Legends
<2018-05-20 Sun 13:05-16:05>
:PROPERTIES:
:ID:       4xQOrG7F1VWzCiuK_tKwF2t7@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Power vs. Legends Power vs. Legends

Follow on MiLB First Pitch  https //stza.co/+xJ5l-2q

Shop  https //stza.co/+xJ5l-31

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Power vs. Legends
END:VALARM
DTSTART:20180520T180500Z
DTEND:20180520T210500Z
UID:4xQOrG7F1VWzCiuK_tKwF2t7@stanza.co
SUMMARY:Power vs. Legends
DESCRIPTION:Power vs. Legends\n\nFollow on MiLB First Pitch: https://stza.co/+xJ5l-2q\n\nShop: https://stza.co/+xJ5l-31\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144605Z
LAST-MODIFIED:20180213T144605Z
TRANSP:OPAQUE
END:VEVENT
* Power @ Fireflies
<2018-05-21 Mon 18:05-21:05>
:PROPERTIES:
:ID:       GmJ3w_OvOYeNR-diFBMnn_mP@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Power @ Fireflies Power @ Fireflies

Follow on MiLB First Pitch  https //stza.co/+xC0U-3c

Shop  https //stza.co/+xC0U-28

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Power @ Fireflies
END:VALARM
DTSTART:20180521T230500Z
DTEND:20180522T020500Z
UID:GmJ3w_OvOYeNR-diFBMnn_mP@stanza.co
SUMMARY:Power @ Fireflies
DESCRIPTION:Power @ Fireflies\n\nFollow on MiLB First Pitch: https://stza.co/+xC0U-3c\n\nShop: https://stza.co/+xC0U-28\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144605Z
LAST-MODIFIED:20180213T144605Z
TRANSP:OPAQUE
END:VEVENT
* Power @ Fireflies
<2018-05-22 Tue 18:05-21:05>
:PROPERTIES:
:ID:       9knedZrdg9RdqeC3B7t2I4Xr@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Power @ Fireflies Power @ Fireflies

Follow on MiLB First Pitch  https //stza.co/+xC0Y-1_

Shop  https //stza.co/+xC0Y-2$

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Power @ Fireflies
END:VALARM
DTSTART:20180522T230500Z
DTEND:20180523T020500Z
UID:9knedZrdg9RdqeC3B7t2I4Xr@stanza.co
SUMMARY:Power @ Fireflies
DESCRIPTION:Power @ Fireflies\n\nFollow on MiLB First Pitch: https://stza.co/+xC0Y-1_\n\nShop: https://stza.co/+xC0Y-2$\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144605Z
LAST-MODIFIED:20180213T144605Z
TRANSP:OPAQUE
END:VEVENT
* Power @ Fireflies
<2018-05-23 Wed 10:05-13:05>
:PROPERTIES:
:ID:       T0C4t5ABH2M1hKy0Uh3LOjrW@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Power @ Fireflies Power @ Fireflies

Follow on MiLB First Pitch  https //stza.co/+xC10-i

Shop  https //stza.co/+xC10-1N

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Power @ Fireflies
END:VALARM
DTSTART:20180523T150500Z
DTEND:20180523T180500Z
UID:T0C4t5ABH2M1hKy0Uh3LOjrW@stanza.co
SUMMARY:Power @ Fireflies
DESCRIPTION:Power @ Fireflies\n\nFollow on MiLB First Pitch: https://stza.co/+xC10-i\n\nShop: https://stza.co/+xC10-1N\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144605Z
LAST-MODIFIED:20180213T144605Z
TRANSP:OPAQUE
END:VEVENT
* Power @ Fireflies
<2018-05-24 Thu 18:05-21:05>
:PROPERTIES:
:ID:       M_vXtAkHGT3O2XZ5mVfJU5pY@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Power @ Fireflies Power @ Fireflies

Follow on MiLB First Pitch  https //stza.co/+xC14-2p

Shop  https //stza.co/+xC14-u

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Power @ Fireflies
END:VALARM
DTSTART:20180524T230500Z
DTEND:20180525T020500Z
UID:M_vXtAkHGT3O2XZ5mVfJU5pY@stanza.co
SUMMARY:Power @ Fireflies
DESCRIPTION:Power @ Fireflies\n\nFollow on MiLB First Pitch: https://stza.co/+xC14-2p\n\nShop: https://stza.co/+xC14-u\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144605Z
LAST-MODIFIED:20180213T144605Z
TRANSP:OPAQUE
END:VEVENT
* Power vs. Intimidators
<2018-05-25 Fri 18:05-21:05>
:PROPERTIES:
:ID:       lRZDC0p4S9WEgafdmeWlvA_c@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Power vs. Intimidators Power vs. Intimidators

Follow on MiLB First Pitch  https //stza.co/+xJ5n-W

Shop  https //stza.co/+xJ5n-2E

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Power vs. Intimidators
END:VALARM
DTSTART:20180525T230500Z
DTEND:20180526T020500Z
UID:lRZDC0p4S9WEgafdmeWlvA_c@stanza.co
SUMMARY:Power vs. Intimidators
DESCRIPTION:Power vs. Intimidators\n\nFollow on MiLB First Pitch: https://stza.co/+xJ5n-W\n\nShop: https://stza.co/+xJ5n-2E\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144605Z
LAST-MODIFIED:20180213T144605Z
TRANSP:OPAQUE
END:VEVENT
* Power vs. Intimidators
<2018-05-26 Sat 17:05-20:05>
:PROPERTIES:
:ID:       R6zZUfE1-vThssAWe6PhdRTi@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Power vs. Intimidators Power vs. Intimidators

Follow on MiLB First Pitch  https //stza.co/+xJ5q-2g

Shop  https //stza.co/+xJ5q-3i

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Power vs. Intimidators
END:VALARM
DTSTART:20180526T220500Z
DTEND:20180527T010500Z
UID:R6zZUfE1-vThssAWe6PhdRTi@stanza.co
SUMMARY:Power vs. Intimidators
DESCRIPTION:Power vs. Intimidators\n\nFollow on MiLB First Pitch: https://stza.co/+xJ5q-2g\n\nShop: https://stza.co/+xJ5q-3i\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144605Z
LAST-MODIFIED:20180213T144605Z
TRANSP:OPAQUE
END:VEVENT
* Power vs. Intimidators
<2018-05-27 Sun 13:05-16:05>
:PROPERTIES:
:ID:       LT_uoA3tkOdUsbfaJM5feMWU@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Power vs. Intimidators Power vs. Intimidators

Follow on MiLB First Pitch  https //stza.co/+xJ5r-1W

Shop  https //stza.co/+xJ5r-2L

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Power vs. Intimidators
END:VALARM
DTSTART:20180527T180500Z
DTEND:20180527T210500Z
UID:LT_uoA3tkOdUsbfaJM5feMWU@stanza.co
SUMMARY:Power vs. Intimidators
DESCRIPTION:Power vs. Intimidators\n\nFollow on MiLB First Pitch: https://stza.co/+xJ5r-1W\n\nShop: https://stza.co/+xJ5r-2L\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144605Z
LAST-MODIFIED:20180213T144605Z
TRANSP:OPAQUE
END:VEVENT
* Power vs. Intimidators
<2018-05-28 Mon 13:05-16:05>
:PROPERTIES:
:ID:       rgc3zERRU6TSRmY2IdQ7fEsL@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Power vs. Intimidators Power vs. Intimidators

Follow on MiLB First Pitch  https //stza.co/+xJ5u-3Y

Shop  https //stza.co/+xJ5u-28

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Power vs. Intimidators
END:VALARM
DTSTART:20180528T180500Z
DTEND:20180528T210500Z
UID:rgc3zERRU6TSRmY2IdQ7fEsL@stanza.co
SUMMARY:Power vs. Intimidators
DESCRIPTION:Power vs. Intimidators\n\nFollow on MiLB First Pitch: https://stza.co/+xJ5u-3Y\n\nShop: https://stza.co/+xJ5u-28\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144605Z
LAST-MODIFIED:20180213T144605Z
TRANSP:OPAQUE
END:VEVENT
* Power @ Legends
<2018-05-29 Tue 18:05-21:05>
:PROPERTIES:
:ID:       GzGj0foxMGYdk8Acsa0-0kbp@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Power @ Legends Power @ Legends

Follow on MiLB First Pitch  https //stza.co/+xC1C-3F

Shop  https //stza.co/+xC1C-19

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Power @ Legends
END:VALARM
DTSTART:20180529T230500Z
DTEND:20180530T020500Z
UID:GzGj0foxMGYdk8Acsa0-0kbp@stanza.co
SUMMARY:Power @ Legends
DESCRIPTION:Power @ Legends\n\nFollow on MiLB First Pitch: https://stza.co/+xC1C-3F\n\nShop: https://stza.co/+xC1C-19\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144605Z
LAST-MODIFIED:20180213T144605Z
TRANSP:OPAQUE
END:VEVENT
* Power @ Legends
<2018-05-30 Wed 12:05-15:05>
:PROPERTIES:
:ID:       5-s6Wytii6S_bImfxdq7d_Jp@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Power @ Legends Power @ Legends

Follow on MiLB First Pitch  https //stza.co/+xC1G-2$

Shop  https //stza.co/+xC1G-2s

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Power @ Legends
END:VALARM
DTSTART:20180530T170500Z
DTEND:20180530T200500Z
UID:5-s6Wytii6S_bImfxdq7d_Jp@stanza.co
SUMMARY:Power @ Legends
DESCRIPTION:Power @ Legends\n\nFollow on MiLB First Pitch: https://stza.co/+xC1G-2$\n\nShop: https://stza.co/+xC1G-2s\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144605Z
LAST-MODIFIED:20180213T144605Z
TRANSP:OPAQUE
END:VEVENT
* Power @ Legends
<2018-05-31 Thu 18:05-21:05>
:PROPERTIES:
:ID:       Z3r-OQMpSNoDtPtI05_ksUNH@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Power @ Legends Power @ Legends

Follow on MiLB First Pitch  https //stza.co/+xC1J-2q

Shop  https //stza.co/+xC1J-2t

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Power @ Legends
END:VALARM
DTSTART:20180531T230500Z
DTEND:20180601T020500Z
UID:Z3r-OQMpSNoDtPtI05_ksUNH@stanza.co
SUMMARY:Power @ Legends
DESCRIPTION:Power @ Legends\n\nFollow on MiLB First Pitch: https://stza.co/+xC1J-2q\n\nShop: https://stza.co/+xC1J-2t\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144605Z
LAST-MODIFIED:20180213T144605Z
TRANSP:OPAQUE
END:VEVENT
* Power @ Grasshoppers
<2018-06-01 Fri 18:00-21:00>
:PROPERTIES:
:ID:       ZjwB4pXRDonjZTSjk2E60uFC@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Power @ Grasshoppers Power @ Grasshoppers

Follow on MiLB First Pitch  https //stza.co/+wizX-37

Shop  https //stza.co/+wizX-1l

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Power @ Grasshoppers
END:VALARM
DTSTART:20180601T230000Z
DTEND:20180602T020000Z
UID:ZjwB4pXRDonjZTSjk2E60uFC@stanza.co
SUMMARY:Power @ Grasshoppers
DESCRIPTION:Power @ Grasshoppers\n\nFollow on MiLB First Pitch: https://stza.co/+wizX-37\n\nShop: https://stza.co/+wizX-1l\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144605Z
LAST-MODIFIED:20180213T144605Z
TRANSP:OPAQUE
END:VEVENT
* Power @ Grasshoppers
<2018-06-02 Sat 18:00-21:00>
:PROPERTIES:
:ID:       TimwRypux5mKrtu-RCSvDmR0@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Power @ Grasshoppers Power @ Grasshoppers

Follow on MiLB First Pitch  https //stza.co/+wizY-2A

Shop  https //stza.co/+wizY-K

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Power @ Grasshoppers
END:VALARM
DTSTART:20180602T230000Z
DTEND:20180603T020000Z
UID:TimwRypux5mKrtu-RCSvDmR0@stanza.co
SUMMARY:Power @ Grasshoppers
DESCRIPTION:Power @ Grasshoppers\n\nFollow on MiLB First Pitch: https://stza.co/+wizY-2A\n\nShop: https://stza.co/+wizY-K\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144605Z
LAST-MODIFIED:20180213T144605Z
TRANSP:OPAQUE
END:VEVENT
* Power @ Grasshoppers
<2018-06-03 Sun 13:00-16:00>
:PROPERTIES:
:ID:       Lqkk3G5WEOFCL4hkY5HLmdRf@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Power @ Grasshoppers Power @ Grasshoppers

Follow on MiLB First Pitch  https //stza.co/+wizZ-A

Shop  https //stza.co/+wizZ-R

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Power @ Grasshoppers
END:VALARM
DTSTART:20180603T180000Z
DTEND:20180603T210000Z
UID:Lqkk3G5WEOFCL4hkY5HLmdRf@stanza.co
SUMMARY:Power @ Grasshoppers
DESCRIPTION:Power @ Grasshoppers\n\nFollow on MiLB First Pitch: https://stza.co/+wizZ-A\n\nShop: https://stza.co/+wizZ-R\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144605Z
LAST-MODIFIED:20180213T144605Z
TRANSP:OPAQUE
END:VEVENT
* Power vs. Legends
<2018-06-05 Tue 18:05-21:05>
:PROPERTIES:
:ID:       gDxDntDE0mW-go6NB_WaMCSA@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Power vs. Legends Power vs. Legends

Follow on MiLB First Pitch  https //stza.co/+xJ5v-2U

Shop  https //stza.co/+xJ5v-34

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Power vs. Legends
END:VALARM
DTSTART:20180605T230500Z
DTEND:20180606T020500Z
UID:gDxDntDE0mW-go6NB_WaMCSA@stanza.co
SUMMARY:Power vs. Legends
DESCRIPTION:Power vs. Legends\n\nFollow on MiLB First Pitch: https://stza.co/+xJ5v-2U\n\nShop: https://stza.co/+xJ5v-34\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144605Z
LAST-MODIFIED:20180213T144605Z
TRANSP:OPAQUE
END:VEVENT
* Power vs. Legends
<2018-06-06 Wed 18:05-21:05>
:PROPERTIES:
:ID:       6fLlvQ1HHk33hoKopWu0Mn8Z@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Power vs. Legends Power vs. Legends

Follow on MiLB First Pitch  https //stza.co/+xJ5y-10

Shop  https //stza.co/+xJ5y-3c

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Power vs. Legends
END:VALARM
DTSTART:20180606T230500Z
DTEND:20180607T020500Z
UID:6fLlvQ1HHk33hoKopWu0Mn8Z@stanza.co
SUMMARY:Power vs. Legends
DESCRIPTION:Power vs. Legends\n\nFollow on MiLB First Pitch: https://stza.co/+xJ5y-10\n\nShop: https://stza.co/+xJ5y-3c\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144605Z
LAST-MODIFIED:20180213T144605Z
TRANSP:OPAQUE
END:VEVENT
* Power vs. Legends
<2018-06-07 Thu 18:05-21:05>
:PROPERTIES:
:ID:       GzDntQcVJ9rNr04uc0OvxFhs@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Power vs. Legends Power vs. Legends

Follow on MiLB First Pitch  https //stza.co/+xJ5A-3M

Shop  https //stza.co/+xJ5A-3d

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Power vs. Legends
END:VALARM
DTSTART:20180607T230500Z
DTEND:20180608T020500Z
UID:GzDntQcVJ9rNr04uc0OvxFhs@stanza.co
SUMMARY:Power vs. Legends
DESCRIPTION:Power vs. Legends\n\nFollow on MiLB First Pitch: https://stza.co/+xJ5A-3M\n\nShop: https://stza.co/+xJ5A-3d\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144605Z
LAST-MODIFIED:20180213T144605Z
TRANSP:OPAQUE
END:VEVENT
* Power @ Crawdads
<2018-06-08 Fri 18:00-21:00>
:PROPERTIES:
:ID:       ASytrnO36QM58CGRjhVRp2w9@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Power @ Crawdads Power @ Crawdads

Follow on MiLB First Pitch  https //stza.co/+w0Rd-b

Shop  https //stza.co/+w0Rd-3q

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Power @ Crawdads
END:VALARM
DTSTART:20180608T230000Z
DTEND:20180609T020000Z
UID:ASytrnO36QM58CGRjhVRp2w9@stanza.co
SUMMARY:Power @ Crawdads
DESCRIPTION:Power @ Crawdads\n\nFollow on MiLB First Pitch: https://stza.co/+w0Rd-b\n\nShop: https://stza.co/+w0Rd-3q\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144605Z
LAST-MODIFIED:20180213T144605Z
TRANSP:OPAQUE
END:VEVENT
* Power @ Crawdads
<2018-06-09 Sat 17:00-20:00>
:PROPERTIES:
:ID:       YV2Yd0zdsxcV2mkur6bbHxxm@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Power @ Crawdads Power @ Crawdads

Follow on MiLB First Pitch  https //stza.co/+w0Re-1F

Shop  https //stza.co/+w0Re-1s

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Power @ Crawdads
END:VALARM
DTSTART:20180609T220000Z
DTEND:20180610T010000Z
UID:YV2Yd0zdsxcV2mkur6bbHxxm@stanza.co
SUMMARY:Power @ Crawdads
DESCRIPTION:Power @ Crawdads\n\nFollow on MiLB First Pitch: https://stza.co/+w0Re-1F\n\nShop: https://stza.co/+w0Re-1s\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144605Z
LAST-MODIFIED:20180213T144605Z
TRANSP:OPAQUE
END:VEVENT
* Power @ Crawdads
<2018-06-10 Sun 14:00-17:00>
:PROPERTIES:
:ID:       O2OXrBSKSiyctjVck_nxz0L2@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Power @ Crawdads Power @ Crawdads

Follow on MiLB First Pitch  https //stza.co/+w0Rf-R

Shop  https //stza.co/+w0Rf-3y

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Power @ Crawdads
END:VALARM
DTSTART:20180610T190000Z
DTEND:20180610T220000Z
UID:O2OXrBSKSiyctjVck_nxz0L2@stanza.co
SUMMARY:Power @ Crawdads
DESCRIPTION:Power @ Crawdads\n\nFollow on MiLB First Pitch: https://stza.co/+w0Rf-R\n\nShop: https://stza.co/+w0Rf-3y\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144605Z
LAST-MODIFIED:20180213T144605Z
TRANSP:OPAQUE
END:VEVENT
* Power @ GreenJackets
<2018-06-11 Mon 18:05-21:05>
:PROPERTIES:
:ID:       ElzUG8RiPcxAeCXHXx5G_C1y@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Power @ GreenJackets Power @ GreenJackets

Follow on MiLB First Pitch  https //stza.co/+xC0C-34

Shop  https //stza.co/+xC0C-1V

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Power @ GreenJackets
END:VALARM
DTSTART:20180611T230500Z
DTEND:20180612T020500Z
UID:ElzUG8RiPcxAeCXHXx5G_C1y@stanza.co
SUMMARY:Power @ GreenJackets
DESCRIPTION:Power @ GreenJackets\n\nFollow on MiLB First Pitch: https://stza.co/+xC0C-34\n\nShop: https://stza.co/+xC0C-1V\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144605Z
LAST-MODIFIED:20180213T144605Z
TRANSP:OPAQUE
END:VEVENT
* Power @ GreenJackets
<2018-06-12 Tue 18:05-21:05>
:PROPERTIES:
:ID:       hTT5kuMKRmFYRN39Tk73CcUU@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Power @ GreenJackets Power @ GreenJackets

Follow on MiLB First Pitch  https //stza.co/+xC0I-2E

Shop  https //stza.co/+xC0I-2W

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Power @ GreenJackets
END:VALARM
DTSTART:20180612T230500Z
DTEND:20180613T020500Z
UID:hTT5kuMKRmFYRN39Tk73CcUU@stanza.co
SUMMARY:Power @ GreenJackets
DESCRIPTION:Power @ GreenJackets\n\nFollow on MiLB First Pitch: https://stza.co/+xC0I-2E\n\nShop: https://stza.co/+xC0I-2W\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144605Z
LAST-MODIFIED:20180213T144605Z
TRANSP:OPAQUE
END:VEVENT
* Power @ GreenJackets
<2018-06-13 Wed 18:05-21:05>
:PROPERTIES:
:ID:       dKuX6jwEE5J4iIZUNNdG5RIq@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Power @ GreenJackets Power @ GreenJackets

Follow on MiLB First Pitch  https //stza.co/+xC0M-3d

Shop  https //stza.co/+xC0M-3a

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Power @ GreenJackets
END:VALARM
DTSTART:20180613T230500Z
DTEND:20180614T020500Z
UID:dKuX6jwEE5J4iIZUNNdG5RIq@stanza.co
SUMMARY:Power @ GreenJackets
DESCRIPTION:Power @ GreenJackets\n\nFollow on MiLB First Pitch: https://stza.co/+xC0M-3d\n\nShop: https://stza.co/+xC0M-3a\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144605Z
LAST-MODIFIED:20180213T144605Z
TRANSP:OPAQUE
END:VEVENT
* Power @ GreenJackets
<2018-06-14 Thu 18:05-21:05>
:PROPERTIES:
:ID:       zvWeacBZRhs4bTk0SkLT0zJX@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Power @ GreenJackets Power @ GreenJackets

Follow on MiLB First Pitch  https //stza.co/+xC0Q-1U

Shop  https //stza.co/+xC0Q-3K

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Power @ GreenJackets
END:VALARM
DTSTART:20180614T230500Z
DTEND:20180615T020500Z
UID:zvWeacBZRhs4bTk0SkLT0zJX@stanza.co
SUMMARY:Power @ GreenJackets
DESCRIPTION:Power @ GreenJackets\n\nFollow on MiLB First Pitch: https://stza.co/+xC0Q-1U\n\nShop: https://stza.co/+xC0Q-3K\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144605Z
LAST-MODIFIED:20180213T144605Z
TRANSP:OPAQUE
END:VEVENT
* Power vs. Shorebirds
<2018-06-15 Fri 18:05-21:05>
:PROPERTIES:
:ID:       Sq0Hjf1d0QE-7Gav6rkqfsu_@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Power vs. Shorebirds Power vs. Shorebirds

Follow on MiLB First Pitch  https //stza.co/+xJ5C-X

Shop  https //stza.co/+xJ5C-1G

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Power vs. Shorebirds
END:VALARM
DTSTART:20180615T230500Z
DTEND:20180616T020500Z
UID:Sq0Hjf1d0QE-7Gav6rkqfsu_@stanza.co
SUMMARY:Power vs. Shorebirds
DESCRIPTION:Power vs. Shorebirds\n\nFollow on MiLB First Pitch: https://stza.co/+xJ5C-X\n\nShop: https://stza.co/+xJ5C-1G\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144605Z
LAST-MODIFIED:20180213T144605Z
TRANSP:OPAQUE
END:VEVENT
* Power vs. Shorebirds
<2018-06-16 Sat 17:05-20:05>
:PROPERTIES:
:ID:       ErLmmrKUhEY-cdIC3yL9xJWr@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Power vs. Shorebirds Power vs. Shorebirds

Follow on MiLB First Pitch  https //stza.co/+xJ5E-m

Shop  https //stza.co/+xJ5E-2_

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Power vs. Shorebirds
END:VALARM
DTSTART:20180616T220500Z
DTEND:20180617T010500Z
UID:ErLmmrKUhEY-cdIC3yL9xJWr@stanza.co
SUMMARY:Power vs. Shorebirds
DESCRIPTION:Power vs. Shorebirds\n\nFollow on MiLB First Pitch: https://stza.co/+xJ5E-m\n\nShop: https://stza.co/+xJ5E-2_\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144605Z
LAST-MODIFIED:20180213T144605Z
TRANSP:OPAQUE
END:VEVENT
* Power vs. Shorebirds
<2018-06-17 Sun 13:05-16:05>
:PROPERTIES:
:ID:       9kz6rEddY3AQMsVaxTtJqQOY@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Power vs. Shorebirds Power vs. Shorebirds

Follow on MiLB First Pitch  https //stza.co/+xJ5G-3d

Shop  https //stza.co/+xJ5G-1i

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Power vs. Shorebirds
END:VALARM
DTSTART:20180617T180500Z
DTEND:20180617T210500Z
UID:9kz6rEddY3AQMsVaxTtJqQOY@stanza.co
SUMMARY:Power vs. Shorebirds
DESCRIPTION:Power vs. Shorebirds\n\nFollow on MiLB First Pitch: https://stza.co/+xJ5G-3d\n\nShop: https://stza.co/+xJ5G-1i\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144605Z
LAST-MODIFIED:20180213T144605Z
TRANSP:OPAQUE
END:VEVENT
* Power @ Crawdads
<2018-06-21 Thu 18:00-21:00>
:PROPERTIES:
:ID:       wKItbWSWy8445xxQpwuysiRA@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Power @ Crawdads Power @ Crawdads

Follow on MiLB First Pitch  https //stza.co/+w0Rg-22

Shop  https //stza.co/+w0Rg-3Y

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Power @ Crawdads
END:VALARM
DTSTART:20180621T230000Z
DTEND:20180622T020000Z
UID:wKItbWSWy8445xxQpwuysiRA@stanza.co
SUMMARY:Power @ Crawdads
DESCRIPTION:Power @ Crawdads\n\nFollow on MiLB First Pitch: https://stza.co/+w0Rg-22\n\nShop: https://stza.co/+w0Rg-3Y\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144605Z
LAST-MODIFIED:20180213T144605Z
TRANSP:OPAQUE
END:VEVENT
* Power @ Crawdads
<2018-06-22 Fri 18:00-21:00>
:PROPERTIES:
:ID:       b6eW-luTbWtIrH4xtF31aYYB@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Power @ Crawdads Power @ Crawdads

Follow on MiLB First Pitch  https //stza.co/+w0Rh-2Q

Shop  https //stza.co/+w0Rh-2w

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Power @ Crawdads
END:VALARM
DTSTART:20180622T230000Z
DTEND:20180623T020000Z
UID:b6eW-luTbWtIrH4xtF31aYYB@stanza.co
SUMMARY:Power @ Crawdads
DESCRIPTION:Power @ Crawdads\n\nFollow on MiLB First Pitch: https://stza.co/+w0Rh-2Q\n\nShop: https://stza.co/+w0Rh-2w\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144605Z
LAST-MODIFIED:20180213T144605Z
TRANSP:OPAQUE
END:VEVENT
* Power @ Crawdads
<2018-06-23 Sat 18:00-21:00>
:PROPERTIES:
:ID:       JkahJxYNJv0nkXJacQbvYBHA@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Power @ Crawdads Power @ Crawdads

Follow on MiLB First Pitch  https //stza.co/+w0Ri-w

Shop  https //stza.co/+w0Ri-11

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Power @ Crawdads
END:VALARM
DTSTART:20180623T230000Z
DTEND:20180624T020000Z
UID:JkahJxYNJv0nkXJacQbvYBHA@stanza.co
SUMMARY:Power @ Crawdads
DESCRIPTION:Power @ Crawdads\n\nFollow on MiLB First Pitch: https://stza.co/+w0Ri-w\n\nShop: https://stza.co/+w0Ri-11\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144605Z
LAST-MODIFIED:20180213T144605Z
TRANSP:OPAQUE
END:VEVENT
* Power vs. BlueClaws
<2018-06-24 Sun 13:05-16:05>
:PROPERTIES:
:ID:       hpiJmQJwV7FSefV1Sa6dCULS@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Power vs. BlueClaws Power vs. BlueClaws

Follow on MiLB First Pitch  https //stza.co/+xJ5I-2O

Shop  https //stza.co/+xJ5I-A

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Power vs. BlueClaws
END:VALARM
DTSTART:20180624T180500Z
DTEND:20180624T210500Z
UID:hpiJmQJwV7FSefV1Sa6dCULS@stanza.co
SUMMARY:Power vs. BlueClaws
DESCRIPTION:Power vs. BlueClaws\n\nFollow on MiLB First Pitch: https://stza.co/+xJ5I-2O\n\nShop: https://stza.co/+xJ5I-A\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144605Z
LAST-MODIFIED:20180213T144605Z
TRANSP:OPAQUE
END:VEVENT
* Power vs. BlueClaws
<2018-06-25 Mon 18:05-21:05>
:PROPERTIES:
:ID:       mXCWN-qJ5MMh7GZ_2afBGpz6@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Power vs. BlueClaws Power vs. BlueClaws

Follow on MiLB First Pitch  https //stza.co/+xJ5J-18

Shop  https //stza.co/+xJ5J-n

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Power vs. BlueClaws
END:VALARM
DTSTART:20180625T230500Z
DTEND:20180626T020500Z
UID:mXCWN-qJ5MMh7GZ_2afBGpz6@stanza.co
SUMMARY:Power vs. BlueClaws
DESCRIPTION:Power vs. BlueClaws\n\nFollow on MiLB First Pitch: https://stza.co/+xJ5J-18\n\nShop: https://stza.co/+xJ5J-n\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144605Z
LAST-MODIFIED:20180213T144605Z
TRANSP:OPAQUE
END:VEVENT
* Power vs. BlueClaws
<2018-06-26 Tue 18:05-21:05>
:PROPERTIES:
:ID:       qzegB93nFIMp_-hYjhle9QJm@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Power vs. BlueClaws Power vs. BlueClaws

Follow on MiLB First Pitch  https //stza.co/+xJ5L-2E

Shop  https //stza.co/+xJ5L-3S

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Power vs. BlueClaws
END:VALARM
DTSTART:20180626T230500Z
DTEND:20180627T020500Z
UID:qzegB93nFIMp_-hYjhle9QJm@stanza.co
SUMMARY:Power vs. BlueClaws
DESCRIPTION:Power vs. BlueClaws\n\nFollow on MiLB First Pitch: https://stza.co/+xJ5L-2E\n\nShop: https://stza.co/+xJ5L-3S\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144605Z
LAST-MODIFIED:20180213T144605Z
TRANSP:OPAQUE
END:VEVENT
* Power vs. Crawdads
<2018-06-27 Wed 18:05-21:05>
:PROPERTIES:
:ID:       6ra6pEw8pMnJMHvGVdMzy7xK@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Power vs. Crawdads Power vs. Crawdads

Follow on MiLB First Pitch  https //stza.co/+xJ5N-M

Shop  https //stza.co/+xJ5N-r

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Power vs. Crawdads
END:VALARM
DTSTART:20180627T230500Z
DTEND:20180628T020500Z
UID:6ra6pEw8pMnJMHvGVdMzy7xK@stanza.co
SUMMARY:Power vs. Crawdads
DESCRIPTION:Power vs. Crawdads\n\nFollow on MiLB First Pitch: https://stza.co/+xJ5N-M\n\nShop: https://stza.co/+xJ5N-r\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144605Z
LAST-MODIFIED:20180213T144605Z
TRANSP:OPAQUE
END:VEVENT
* Power vs. Crawdads
<2018-06-28 Thu 18:05-21:05>
:PROPERTIES:
:ID:       xAQLYomvn-hBdqjk9KVqvFCK@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Power vs. Crawdads Power vs. Crawdads

Follow on MiLB First Pitch  https //stza.co/+xJ5Q-3w

Shop  https //stza.co/+xJ5Q-r

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Power vs. Crawdads
END:VALARM
DTSTART:20180628T230500Z
DTEND:20180629T020500Z
UID:xAQLYomvn-hBdqjk9KVqvFCK@stanza.co
SUMMARY:Power vs. Crawdads
DESCRIPTION:Power vs. Crawdads\n\nFollow on MiLB First Pitch: https://stza.co/+xJ5Q-3w\n\nShop: https://stza.co/+xJ5Q-r\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144605Z
LAST-MODIFIED:20180213T144605Z
TRANSP:OPAQUE
END:VEVENT
* Power vs. Crawdads
<2018-06-29 Fri 18:05-21:05>
:PROPERTIES:
:ID:       yseFrfrIafnFECRencPg6BXT@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Power vs. Crawdads Power vs. Crawdads

Follow on MiLB First Pitch  https //stza.co/+xJ5S-27

Shop  https //stza.co/+xJ5S-1d

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Power vs. Crawdads
END:VALARM
DTSTART:20180629T230500Z
DTEND:20180630T020500Z
UID:yseFrfrIafnFECRencPg6BXT@stanza.co
SUMMARY:Power vs. Crawdads
DESCRIPTION:Power vs. Crawdads\n\nFollow on MiLB First Pitch: https://stza.co/+xJ5S-27\n\nShop: https://stza.co/+xJ5S-1d\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144605Z
LAST-MODIFIED:20180213T144605Z
TRANSP:OPAQUE
END:VEVENT
* Power @ Suns
<2018-06-30 Sat 17:05-20:05>
:PROPERTIES:
:ID:       Ynt8Q18UgTNPWpawzjgFfbj0@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Power @ Suns Power @ Suns

Follow on MiLB First Pitch  https //stza.co/+xF9f-b

Shop  https //stza.co/+xF9f-1V

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Power @ Suns
END:VALARM
DTSTART:20180630T220500Z
DTEND:20180701T010500Z
UID:Ynt8Q18UgTNPWpawzjgFfbj0@stanza.co
SUMMARY:Power @ Suns
DESCRIPTION:Power @ Suns\n\nFollow on MiLB First Pitch: https://stza.co/+xF9f-b\n\nShop: https://stza.co/+xF9f-1V\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144605Z
LAST-MODIFIED:20180213T144605Z
TRANSP:OPAQUE
END:VEVENT
* Power @ Suns
<2018-07-01 Sun 13:05-16:05>
:PROPERTIES:
:ID:       Ddmlaruk-UyKMSrFEIWvBeER@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Power @ Suns Power @ Suns

Follow on MiLB First Pitch  https //stza.co/+xF9h-3H

Shop  https //stza.co/+xF9h-3E

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Power @ Suns
END:VALARM
DTSTART:20180701T180500Z
DTEND:20180701T210500Z
UID:Ddmlaruk-UyKMSrFEIWvBeER@stanza.co
SUMMARY:Power @ Suns
DESCRIPTION:Power @ Suns\n\nFollow on MiLB First Pitch: https://stza.co/+xF9h-3H\n\nShop: https://stza.co/+xF9h-3E\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144605Z
LAST-MODIFIED:20180213T144605Z
TRANSP:OPAQUE
END:VEVENT
* Power @ Suns
<2018-07-02 Mon 18:05-21:05>
:PROPERTIES:
:ID:       N757H24fPDhLfOYVl2cHABN3@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Power @ Suns Power @ Suns

Follow on MiLB First Pitch  https //stza.co/+xF9i-17

Shop  https //stza.co/+xF9i-1Y

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Power @ Suns
END:VALARM
DTSTART:20180702T230500Z
DTEND:20180703T020500Z
UID:N757H24fPDhLfOYVl2cHABN3@stanza.co
SUMMARY:Power @ Suns
DESCRIPTION:Power @ Suns\n\nFollow on MiLB First Pitch: https://stza.co/+xF9i-17\n\nShop: https://stza.co/+xF9i-1Y\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144605Z
LAST-MODIFIED:20180213T144605Z
TRANSP:OPAQUE
END:VEVENT
* Power @ Suns
<2018-07-03 Tue 18:05-21:05>
:PROPERTIES:
:ID:       xMb-7Byw6zlU_QqY7mL7Jj5Y@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Power @ Suns Power @ Suns

Follow on MiLB First Pitch  https //stza.co/+xF9j-D

Shop  https //stza.co/+xF9j-3D

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Power @ Suns
END:VALARM
DTSTART:20180703T230500Z
DTEND:20180704T020500Z
UID:xMb-7Byw6zlU_QqY7mL7Jj5Y@stanza.co
SUMMARY:Power @ Suns
DESCRIPTION:Power @ Suns\n\nFollow on MiLB First Pitch: https://stza.co/+xF9j-D\n\nShop: https://stza.co/+xF9j-3D\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144605Z
LAST-MODIFIED:20180213T144605Z
TRANSP:OPAQUE
END:VEVENT
* Power vs. Legends
<2018-07-04 Wed 18:05-21:05>
:PROPERTIES:
:ID:       94cfhwcsL9rc3vbZ7Lt-KsqA@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Power vs. Legends Power vs. Legends

Follow on MiLB First Pitch  https //stza.co/+xJ5U-M

Shop  https //stza.co/+xJ5U-1B

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Power vs. Legends
END:VALARM
DTSTART:20180704T230500Z
DTEND:20180705T020500Z
UID:94cfhwcsL9rc3vbZ7Lt-KsqA@stanza.co
SUMMARY:Power vs. Legends
DESCRIPTION:Power vs. Legends\n\nFollow on MiLB First Pitch: https://stza.co/+xJ5U-M\n\nShop: https://stza.co/+xJ5U-1B\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144605Z
LAST-MODIFIED:20180213T144605Z
TRANSP:OPAQUE
END:VEVENT
* Power vs. Legends
<2018-07-05 Thu 18:05-21:05>
:PROPERTIES:
:ID:       06dE6rinz5bKJIDKsEZZ7gzf@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Power vs. Legends Power vs. Legends

Follow on MiLB First Pitch  https //stza.co/+xJ5W-2w

Shop  https //stza.co/+xJ5W-3M

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Power vs. Legends
END:VALARM
DTSTART:20180705T230500Z
DTEND:20180706T020500Z
UID:06dE6rinz5bKJIDKsEZZ7gzf@stanza.co
SUMMARY:Power vs. Legends
DESCRIPTION:Power vs. Legends\n\nFollow on MiLB First Pitch: https://stza.co/+xJ5W-2w\n\nShop: https://stza.co/+xJ5W-3M\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144605Z
LAST-MODIFIED:20180213T144605Z
TRANSP:OPAQUE
END:VEVENT
* Power vs. Legends
<2018-07-06 Fri 18:05-21:05>
:PROPERTIES:
:ID:       vMwbZZFsZhxF9GOCtOiYT-XL@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Power vs. Legends Power vs. Legends

Follow on MiLB First Pitch  https //stza.co/+xJ5X-5

Shop  https //stza.co/+xJ5X-A

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Power vs. Legends
END:VALARM
DTSTART:20180706T230500Z
DTEND:20180707T020500Z
UID:vMwbZZFsZhxF9GOCtOiYT-XL@stanza.co
SUMMARY:Power vs. Legends
DESCRIPTION:Power vs. Legends\n\nFollow on MiLB First Pitch: https://stza.co/+xJ5X-5\n\nShop: https://stza.co/+xJ5X-A\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144605Z
LAST-MODIFIED:20180213T144605Z
TRANSP:OPAQUE
END:VEVENT
* Power vs. Suns
<2018-07-07 Sat 17:05-20:05>
:PROPERTIES:
:ID:       EAsRfxM5siNWP12ahYVs3ODk@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Power vs. Suns Power vs. Suns

Follow on MiLB First Pitch  https //stza.co/+xJ5Z-1t

Shop  https //stza.co/+xJ5Z-W

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Power vs. Suns
END:VALARM
DTSTART:20180707T220500Z
DTEND:20180708T010500Z
UID:EAsRfxM5siNWP12ahYVs3ODk@stanza.co
SUMMARY:Power vs. Suns
DESCRIPTION:Power vs. Suns\n\nFollow on MiLB First Pitch: https://stza.co/+xJ5Z-1t\n\nShop: https://stza.co/+xJ5Z-W\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144605Z
LAST-MODIFIED:20180213T144605Z
TRANSP:OPAQUE
END:VEVENT
* Power vs. Suns
<2018-07-08 Sun 13:05-16:05>
:PROPERTIES:
:ID:       Ku2Mz48K8CRIAEB6I8YigprK@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Power vs. Suns Power vs. Suns

Follow on MiLB First Pitch  https //stza.co/+xJ5$-1t

Shop  https //stza.co/+xJ5$-1E

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Power vs. Suns
END:VALARM
DTSTART:20180708T180500Z
DTEND:20180708T210500Z
UID:Ku2Mz48K8CRIAEB6I8YigprK@stanza.co
SUMMARY:Power vs. Suns
DESCRIPTION:Power vs. Suns\n\nFollow on MiLB First Pitch: https://stza.co/+xJ5$-1t\n\nShop: https://stza.co/+xJ5$-1E\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144605Z
LAST-MODIFIED:20180213T144605Z
TRANSP:OPAQUE
END:VEVENT
* Power vs. Suns
<2018-07-09 Mon 18:05-21:05>
:PROPERTIES:
:ID:       crqLKpUW-Pv0UI1rdmN9MbW9@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Power vs. Suns Power vs. Suns

Follow on MiLB First Pitch  https //stza.co/+xJ62-2x

Shop  https //stza.co/+xJ62-W

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Power vs. Suns
END:VALARM
DTSTART:20180709T230500Z
DTEND:20180710T020500Z
UID:crqLKpUW-Pv0UI1rdmN9MbW9@stanza.co
SUMMARY:Power vs. Suns
DESCRIPTION:Power vs. Suns\n\nFollow on MiLB First Pitch: https://stza.co/+xJ62-2x\n\nShop: https://stza.co/+xJ62-W\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144605Z
LAST-MODIFIED:20180213T144605Z
TRANSP:OPAQUE
END:VEVENT
* Power @ Crawdads
<2018-07-11 Wed 18:00-21:00>
:PROPERTIES:
:ID:       4LwVQ1w2sMAv4BLMA_i6Z9Rg@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Power @ Crawdads Power @ Crawdads

Follow on MiLB First Pitch  https //stza.co/+w0Rj-1N

Shop  https //stza.co/+w0Rj-K

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Power @ Crawdads
END:VALARM
DTSTART:20180711T230000Z
DTEND:20180712T020000Z
UID:4LwVQ1w2sMAv4BLMA_i6Z9Rg@stanza.co
SUMMARY:Power @ Crawdads
DESCRIPTION:Power @ Crawdads\n\nFollow on MiLB First Pitch: https://stza.co/+w0Rj-1N\n\nShop: https://stza.co/+w0Rj-K\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144605Z
LAST-MODIFIED:20180213T144605Z
TRANSP:OPAQUE
END:VEVENT
* Power @ Crawdads
<2018-07-12 Thu 18:00-21:00>
:PROPERTIES:
:ID:       6xlY9Zr6aMKb1_8GYzXIJosM@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Power @ Crawdads Power @ Crawdads

Follow on MiLB First Pitch  https //stza.co/+w0Rk-2A

Shop  https //stza.co/+w0Rk-X

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Power @ Crawdads
END:VALARM
DTSTART:20180712T230000Z
DTEND:20180713T020000Z
UID:6xlY9Zr6aMKb1_8GYzXIJosM@stanza.co
SUMMARY:Power @ Crawdads
DESCRIPTION:Power @ Crawdads\n\nFollow on MiLB First Pitch: https://stza.co/+w0Rk-2A\n\nShop: https://stza.co/+w0Rk-X\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144605Z
LAST-MODIFIED:20180213T144605Z
TRANSP:OPAQUE
END:VEVENT
* Power @ Crawdads
<2018-07-13 Fri 18:00-21:00>
:PROPERTIES:
:ID:       xEbWrTCEh6bFkwolz0RBzVER@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Power @ Crawdads Power @ Crawdads

Follow on MiLB First Pitch  https //stza.co/+w0Rl-J

Shop  https //stza.co/+w0Rl-1x

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Power @ Crawdads
END:VALARM
DTSTART:20180713T230000Z
DTEND:20180714T020000Z
UID:xEbWrTCEh6bFkwolz0RBzVER@stanza.co
SUMMARY:Power @ Crawdads
DESCRIPTION:Power @ Crawdads\n\nFollow on MiLB First Pitch: https://stza.co/+w0Rl-J\n\nShop: https://stza.co/+w0Rl-1x\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144605Z
LAST-MODIFIED:20180213T144605Z
TRANSP:OPAQUE
END:VEVENT
* Power vs. Shorebirds
<2018-07-14 Sat 17:05-20:05>
:PROPERTIES:
:ID:       t1s3Dqips1IYg4EFiHCnLRHY@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Power vs. Shorebirds Power vs. Shorebirds

Follow on MiLB First Pitch  https //stza.co/+xJ64-2K

Shop  https //stza.co/+xJ64-2f

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Power vs. Shorebirds
END:VALARM
DTSTART:20180714T220500Z
DTEND:20180715T010500Z
UID:t1s3Dqips1IYg4EFiHCnLRHY@stanza.co
SUMMARY:Power vs. Shorebirds
DESCRIPTION:Power vs. Shorebirds\n\nFollow on MiLB First Pitch: https://stza.co/+xJ64-2K\n\nShop: https://stza.co/+xJ64-2f\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144605Z
LAST-MODIFIED:20180213T144605Z
TRANSP:OPAQUE
END:VEVENT
* Power vs. Shorebirds
<2018-07-15 Sun 13:05-16:05>
:PROPERTIES:
:ID:       q2lVSIjp-jkAwXZ7yxOKvJMf@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Power vs. Shorebirds Power vs. Shorebirds

Follow on MiLB First Pitch  https //stza.co/+xJ65-1a

Shop  https //stza.co/+xJ65-3u

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Power vs. Shorebirds
END:VALARM
DTSTART:20180715T180500Z
DTEND:20180715T210500Z
UID:q2lVSIjp-jkAwXZ7yxOKvJMf@stanza.co
SUMMARY:Power vs. Shorebirds
DESCRIPTION:Power vs. Shorebirds\n\nFollow on MiLB First Pitch: https://stza.co/+xJ65-1a\n\nShop: https://stza.co/+xJ65-3u\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144605Z
LAST-MODIFIED:20180213T144605Z
TRANSP:OPAQUE
END:VEVENT
* Power vs. Shorebirds
<2018-07-16 Mon 18:05-21:05>
:PROPERTIES:
:ID:       4H9d_RhGZZPvGEsJyn0NfVOp@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Power vs. Shorebirds Power vs. Shorebirds

Follow on MiLB First Pitch  https //stza.co/+xJ67-2m

Shop  https //stza.co/+xJ67-3k

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Power vs. Shorebirds
END:VALARM
DTSTART:20180716T230500Z
DTEND:20180717T020500Z
UID:4H9d_RhGZZPvGEsJyn0NfVOp@stanza.co
SUMMARY:Power vs. Shorebirds
DESCRIPTION:Power vs. Shorebirds\n\nFollow on MiLB First Pitch: https://stza.co/+xJ67-2m\n\nShop: https://stza.co/+xJ67-3k\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144605Z
LAST-MODIFIED:20180213T144605Z
TRANSP:OPAQUE
END:VEVENT
* Power vs. Shorebirds
<2018-07-17 Tue 11:05-14:05>
:PROPERTIES:
:ID:       fVSo9KT59PquVlGvGjTWD8s-@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Power vs. Shorebirds Power vs. Shorebirds

Follow on MiLB First Pitch  https //stza.co/+xJ69-3M

Shop  https //stza.co/+xJ69-A

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Power vs. Shorebirds
END:VALARM
DTSTART:20180717T160500Z
DTEND:20180717T190500Z
UID:fVSo9KT59PquVlGvGjTWD8s-@stanza.co
SUMMARY:Power vs. Shorebirds
DESCRIPTION:Power vs. Shorebirds\n\nFollow on MiLB First Pitch: https://stza.co/+xJ69-3M\n\nShop: https://stza.co/+xJ69-A\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144605Z
LAST-MODIFIED:20180213T144605Z
TRANSP:OPAQUE
END:VEVENT
* Power @ Legends
<2018-07-19 Thu 18:05-21:05>
:PROPERTIES:
:ID:       FdaOraZ_ciHIVBNSJW3DriUQ@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Power @ Legends Power @ Legends

Follow on MiLB First Pitch  https //stza.co/+xC1L-3P

Shop  https //stza.co/+xC1L-1g

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Power @ Legends
END:VALARM
DTSTART:20180719T230500Z
DTEND:20180720T020500Z
UID:FdaOraZ_ciHIVBNSJW3DriUQ@stanza.co
SUMMARY:Power @ Legends
DESCRIPTION:Power @ Legends\n\nFollow on MiLB First Pitch: https://stza.co/+xC1L-3P\n\nShop: https://stza.co/+xC1L-1g\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144605Z
LAST-MODIFIED:20180213T144605Z
TRANSP:OPAQUE
END:VEVENT
* Power @ Legends
<2018-07-20 Fri 18:05-21:05>
:PROPERTIES:
:ID:       2PL7NFhn6EiF2U2pfqZQQDIp@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Power @ Legends Power @ Legends

Follow on MiLB First Pitch  https //stza.co/+xC1N-3c

Shop  https //stza.co/+xC1N-2k

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Power @ Legends
END:VALARM
DTSTART:20180720T230500Z
DTEND:20180721T020500Z
UID:2PL7NFhn6EiF2U2pfqZQQDIp@stanza.co
SUMMARY:Power @ Legends
DESCRIPTION:Power @ Legends\n\nFollow on MiLB First Pitch: https://stza.co/+xC1N-3c\n\nShop: https://stza.co/+xC1N-2k\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144605Z
LAST-MODIFIED:20180213T144605Z
TRANSP:OPAQUE
END:VEVENT
* Power @ Legends
<2018-07-21 Sat 17:35-20:35>
:PROPERTIES:
:ID:       zfhrqFiNdrZvk0xcA1Uju8Xt@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Power @ Legends Power @ Legends

Follow on MiLB First Pitch  https //stza.co/+xC1P-3y

Shop  https //stza.co/+xC1P-1J

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Power @ Legends
END:VALARM
DTSTART:20180721T223500Z
DTEND:20180722T013500Z
UID:zfhrqFiNdrZvk0xcA1Uju8Xt@stanza.co
SUMMARY:Power @ Legends
DESCRIPTION:Power @ Legends\n\nFollow on MiLB First Pitch: https://stza.co/+xC1P-3y\n\nShop: https://stza.co/+xC1P-1J\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144605Z
LAST-MODIFIED:20180213T144605Z
TRANSP:OPAQUE
END:VEVENT
* Power @ Legends
<2018-07-22 Sun 13:05-16:05>
:PROPERTIES:
:ID:       rugE7jLoNrIFjCG4Z_7i0HuI@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Power @ Legends Power @ Legends

Follow on MiLB First Pitch  https //stza.co/+xC1Q-3g

Shop  https //stza.co/+xC1Q-3O

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Power @ Legends
END:VALARM
DTSTART:20180722T180500Z
DTEND:20180722T210500Z
UID:rugE7jLoNrIFjCG4Z_7i0HuI@stanza.co
SUMMARY:Power @ Legends
DESCRIPTION:Power @ Legends\n\nFollow on MiLB First Pitch: https://stza.co/+xC1Q-3g\n\nShop: https://stza.co/+xC1Q-3O\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144605Z
LAST-MODIFIED:20180213T144605Z
TRANSP:OPAQUE
END:VEVENT
* Power @ Intimidators
<2018-07-23 Mon 18:05-21:05>
:PROPERTIES:
:ID:       MfGcVBnQqZCveaIHaFgfJ2WV@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Power @ Intimidators Power @ Intimidators

Follow on MiLB First Pitch  https //stza.co/+wIG7-2g

Shop  https //stza.co/+wIG7-1f

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Power @ Intimidators
END:VALARM
DTSTART:20180723T230500Z
DTEND:20180724T020500Z
UID:MfGcVBnQqZCveaIHaFgfJ2WV@stanza.co
SUMMARY:Power @ Intimidators
DESCRIPTION:Power @ Intimidators\n\nFollow on MiLB First Pitch: https://stza.co/+wIG7-2g\n\nShop: https://stza.co/+wIG7-1f\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144605Z
LAST-MODIFIED:20180213T144605Z
TRANSP:OPAQUE
END:VEVENT
* Power @ Intimidators
<2018-07-24 Tue 18:05-21:05>
:PROPERTIES:
:ID:       7VDSj5qOefehuYaDBjd3bxy5@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Power @ Intimidators Power @ Intimidators

Follow on MiLB First Pitch  https //stza.co/+wIG8-2p

Shop  https //stza.co/+wIG8-5

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Power @ Intimidators
END:VALARM
DTSTART:20180724T230500Z
DTEND:20180725T020500Z
UID:7VDSj5qOefehuYaDBjd3bxy5@stanza.co
SUMMARY:Power @ Intimidators
DESCRIPTION:Power @ Intimidators\n\nFollow on MiLB First Pitch: https://stza.co/+wIG8-2p\n\nShop: https://stza.co/+wIG8-5\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144605Z
LAST-MODIFIED:20180213T144605Z
TRANSP:OPAQUE
END:VEVENT
* Power @ Intimidators
<2018-07-25 Wed 18:05-21:05>
:PROPERTIES:
:ID:       eEFFDSMhGaYKs2TPpwHCBAHz@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Power @ Intimidators Power @ Intimidators

Follow on MiLB First Pitch  https //stza.co/+wIG9-j

Shop  https //stza.co/+wIG9-2

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Power @ Intimidators
END:VALARM
DTSTART:20180725T230500Z
DTEND:20180726T020500Z
UID:eEFFDSMhGaYKs2TPpwHCBAHz@stanza.co
SUMMARY:Power @ Intimidators
DESCRIPTION:Power @ Intimidators\n\nFollow on MiLB First Pitch: https://stza.co/+wIG9-j\n\nShop: https://stza.co/+wIG9-2\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144605Z
LAST-MODIFIED:20180213T144605Z
TRANSP:OPAQUE
END:VEVENT
* Power @ Intimidators
<2018-07-26 Thu 18:05-21:05>
:PROPERTIES:
:ID:       y8Ermk6Mfk0zD7ATjRMLjHaK@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Power @ Intimidators Power @ Intimidators

Follow on MiLB First Pitch  https //stza.co/+wIGa-25

Shop  https //stza.co/+wIGa-3R

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Power @ Intimidators
END:VALARM
DTSTART:20180726T230500Z
DTEND:20180727T020500Z
UID:y8Ermk6Mfk0zD7ATjRMLjHaK@stanza.co
SUMMARY:Power @ Intimidators
DESCRIPTION:Power @ Intimidators\n\nFollow on MiLB First Pitch: https://stza.co/+wIGa-25\n\nShop: https://stza.co/+wIGa-3R\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144605Z
LAST-MODIFIED:20180213T144605Z
TRANSP:OPAQUE
END:VEVENT
* Power vs. Tourists
<2018-07-27 Fri 18:05-21:05>
:PROPERTIES:
:ID:       Z1-15rK9o9ZFbJkDX-fBoift@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Power vs. Tourists Power vs. Tourists

Follow on MiLB First Pitch  https //stza.co/+xJ6b-35

Shop  https //stza.co/+xJ6b-2M

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Power vs. Tourists
END:VALARM
DTSTART:20180727T230500Z
DTEND:20180728T020500Z
UID:Z1-15rK9o9ZFbJkDX-fBoift@stanza.co
SUMMARY:Power vs. Tourists
DESCRIPTION:Power vs. Tourists\n\nFollow on MiLB First Pitch: https://stza.co/+xJ6b-35\n\nShop: https://stza.co/+xJ6b-2M\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144605Z
LAST-MODIFIED:20180213T144605Z
TRANSP:OPAQUE
END:VEVENT
* Power vs. Tourists
<2018-07-28 Sat 17:05-20:05>
:PROPERTIES:
:ID:       2Uw-TxeFaP0X9jD6bDJriSQo@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Power vs. Tourists Power vs. Tourists

Follow on MiLB First Pitch  https //stza.co/+xJ6d-5

Shop  https //stza.co/+xJ6d-3r

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Power vs. Tourists
END:VALARM
DTSTART:20180728T220500Z
DTEND:20180729T010500Z
UID:2Uw-TxeFaP0X9jD6bDJriSQo@stanza.co
SUMMARY:Power vs. Tourists
DESCRIPTION:Power vs. Tourists\n\nFollow on MiLB First Pitch: https://stza.co/+xJ6d-5\n\nShop: https://stza.co/+xJ6d-3r\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144605Z
LAST-MODIFIED:20180213T144605Z
TRANSP:OPAQUE
END:VEVENT
* Power vs. Tourists
<2018-07-29 Sun 13:05-16:05>
:PROPERTIES:
:ID:       ahPwwMbB4AOpZ4gwO5sR8rOs@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Power vs. Tourists Power vs. Tourists

Follow on MiLB First Pitch  https //stza.co/+xJ6f-D

Shop  https //stza.co/+xJ6f-3Y

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Power vs. Tourists
END:VALARM
DTSTART:20180729T180500Z
DTEND:20180729T210500Z
UID:ahPwwMbB4AOpZ4gwO5sR8rOs@stanza.co
SUMMARY:Power vs. Tourists
DESCRIPTION:Power vs. Tourists\n\nFollow on MiLB First Pitch: https://stza.co/+xJ6f-D\n\nShop: https://stza.co/+xJ6f-3Y\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144605Z
LAST-MODIFIED:20180213T144605Z
TRANSP:OPAQUE
END:VEVENT
* Power @ Fireflies
<2018-07-30 Mon 18:05-21:05>
:PROPERTIES:
:ID:       1LInK0mhyYNxY3uEP3nXLc59@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Power @ Fireflies Power @ Fireflies

Follow on MiLB First Pitch  https //stza.co/+xC18-3w

Shop  https //stza.co/+xC18-3S

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Power @ Fireflies
END:VALARM
DTSTART:20180730T230500Z
DTEND:20180731T020500Z
UID:1LInK0mhyYNxY3uEP3nXLc59@stanza.co
SUMMARY:Power @ Fireflies
DESCRIPTION:Power @ Fireflies\n\nFollow on MiLB First Pitch: https://stza.co/+xC18-3w\n\nShop: https://stza.co/+xC18-3S\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144605Z
LAST-MODIFIED:20180213T144605Z
TRANSP:OPAQUE
END:VEVENT
* Power @ Fireflies
<2018-07-31 Tue 18:05-21:05>
:PROPERTIES:
:ID:       kcxLaQCTc7Pk9fV-c3WN1ndF@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Power @ Fireflies Power @ Fireflies

Follow on MiLB First Pitch  https //stza.co/+xC1b-R

Shop  https //stza.co/+xC1b-2O

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Power @ Fireflies
END:VALARM
DTSTART:20180731T230500Z
DTEND:20180801T020500Z
UID:kcxLaQCTc7Pk9fV-c3WN1ndF@stanza.co
SUMMARY:Power @ Fireflies
DESCRIPTION:Power @ Fireflies\n\nFollow on MiLB First Pitch: https://stza.co/+xC1b-R\n\nShop: https://stza.co/+xC1b-2O\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144605Z
LAST-MODIFIED:20180213T144605Z
TRANSP:OPAQUE
END:VEVENT
* Power @ Fireflies
<2018-08-01 Wed 18:05-21:05>
:PROPERTIES:
:ID:       Z7yNylFgRJvAw8x5FnUdLv5a@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Power @ Fireflies Power @ Fireflies

Follow on MiLB First Pitch  https //stza.co/+xC1e-p

Shop  https //stza.co/+xC1e-3b

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Power @ Fireflies
END:VALARM
DTSTART:20180801T230500Z
DTEND:20180802T020500Z
UID:Z7yNylFgRJvAw8x5FnUdLv5a@stanza.co
SUMMARY:Power @ Fireflies
DESCRIPTION:Power @ Fireflies\n\nFollow on MiLB First Pitch: https://stza.co/+xC1e-p\n\nShop: https://stza.co/+xC1e-3b\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144605Z
LAST-MODIFIED:20180213T144605Z
TRANSP:OPAQUE
END:VEVENT
* Power vs. GreenJackets
<2018-08-02 Thu 18:05-21:05>
:PROPERTIES:
:ID:       c8G3cf0Mhpz9ve2aPS45ObI3@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Power vs. GreenJackets Power vs. GreenJackets

Follow on MiLB First Pitch  https //stza.co/+xJ6i-3t

Shop  https //stza.co/+xJ6i-1P

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Power vs. GreenJackets
END:VALARM
DTSTART:20180802T230500Z
DTEND:20180803T020500Z
UID:c8G3cf0Mhpz9ve2aPS45ObI3@stanza.co
SUMMARY:Power vs. GreenJackets
DESCRIPTION:Power vs. GreenJackets\n\nFollow on MiLB First Pitch: https://stza.co/+xJ6i-3t\n\nShop: https://stza.co/+xJ6i-1P\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144605Z
LAST-MODIFIED:20180213T144605Z
TRANSP:OPAQUE
END:VEVENT
* Power vs. GreenJackets
<2018-08-03 Fri 18:05-21:05>
:PROPERTIES:
:ID:       1IAakipCSP-fxYtTye1tf3iX@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Power vs. GreenJackets Power vs. GreenJackets

Follow on MiLB First Pitch  https //stza.co/+xJ6k-_

Shop  https //stza.co/+xJ6k-$

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Power vs. GreenJackets
END:VALARM
DTSTART:20180803T230500Z
DTEND:20180804T020500Z
UID:1IAakipCSP-fxYtTye1tf3iX@stanza.co
SUMMARY:Power vs. GreenJackets
DESCRIPTION:Power vs. GreenJackets\n\nFollow on MiLB First Pitch: https://stza.co/+xJ6k-_\n\nShop: https://stza.co/+xJ6k-$\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144605Z
LAST-MODIFIED:20180213T144605Z
TRANSP:OPAQUE
END:VEVENT
* Power vs. GreenJackets
<2018-08-04 Sat 17:05-20:05>
:PROPERTIES:
:ID:       Uwo5Y3xZvxfLsNjYT7c6uJX3@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Power vs. GreenJackets Power vs. GreenJackets

Follow on MiLB First Pitch  https //stza.co/+xJ6l-1a

Shop  https //stza.co/+xJ6l-3Q

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Power vs. GreenJackets
END:VALARM
DTSTART:20180804T220500Z
DTEND:20180805T010500Z
UID:Uwo5Y3xZvxfLsNjYT7c6uJX3@stanza.co
SUMMARY:Power vs. GreenJackets
DESCRIPTION:Power vs. GreenJackets\n\nFollow on MiLB First Pitch: https://stza.co/+xJ6l-1a\n\nShop: https://stza.co/+xJ6l-3Q\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144605Z
LAST-MODIFIED:20180213T144605Z
TRANSP:OPAQUE
END:VEVENT
* Power vs. GreenJackets
<2018-08-05 Sun 13:05-16:05>
:PROPERTIES:
:ID:       LqbLcb3Ai9Ot3cSxOj-QyzFI@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Power vs. GreenJackets Power vs. GreenJackets

Follow on MiLB First Pitch  https //stza.co/+xJ6o-2P

Shop  https //stza.co/+xJ6o-3x

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Power vs. GreenJackets
END:VALARM
DTSTART:20180805T180500Z
DTEND:20180805T210500Z
UID:LqbLcb3Ai9Ot3cSxOj-QyzFI@stanza.co
SUMMARY:Power vs. GreenJackets
DESCRIPTION:Power vs. GreenJackets\n\nFollow on MiLB First Pitch: https://stza.co/+xJ6o-2P\n\nShop: https://stza.co/+xJ6o-3x\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144605Z
LAST-MODIFIED:20180213T144605Z
TRANSP:OPAQUE
END:VEVENT
* Power @ Grasshoppers
<2018-08-07 Tue 18:00-21:00>
:PROPERTIES:
:ID:       4UeQEBIF0EqJOQn3GLp1kP-d@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Power @ Grasshoppers Power @ Grasshoppers

Follow on MiLB First Pitch  https //stza.co/+wiz_-1O

Shop  https //stza.co/+wiz_-1I

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Power @ Grasshoppers
END:VALARM
DTSTART:20180807T230000Z
DTEND:20180808T020000Z
UID:4UeQEBIF0EqJOQn3GLp1kP-d@stanza.co
SUMMARY:Power @ Grasshoppers
DESCRIPTION:Power @ Grasshoppers\n\nFollow on MiLB First Pitch: https://stza.co/+wiz_-1O\n\nShop: https://stza.co/+wiz_-1I\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144605Z
LAST-MODIFIED:20180213T144605Z
TRANSP:OPAQUE
END:VEVENT
* Power @ Grasshoppers
<2018-08-08 Wed 18:00-21:00>
:PROPERTIES:
:ID:       vSqdacNLRZGocLby2ryh2EUc@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Power @ Grasshoppers Power @ Grasshoppers

Follow on MiLB First Pitch  https //stza.co/+wiz$-1B

Shop  https //stza.co/+wiz$-30

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Power @ Grasshoppers
END:VALARM
DTSTART:20180808T230000Z
DTEND:20180809T020000Z
UID:vSqdacNLRZGocLby2ryh2EUc@stanza.co
SUMMARY:Power @ Grasshoppers
DESCRIPTION:Power @ Grasshoppers\n\nFollow on MiLB First Pitch: https://stza.co/+wiz$-1B\n\nShop: https://stza.co/+wiz$-30\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144605Z
LAST-MODIFIED:20180213T144605Z
TRANSP:OPAQUE
END:VEVENT
* Power @ Grasshoppers
<2018-08-09 Thu 18:00-21:00>
:PROPERTIES:
:ID:       c_9ogZX5tCtICdjajVYdrksV@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Power @ Grasshoppers Power @ Grasshoppers

Follow on MiLB First Pitch  https //stza.co/+wiA0-e

Shop  https //stza.co/+wiA0-2t

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Power @ Grasshoppers
END:VALARM
DTSTART:20180809T230000Z
DTEND:20180810T020000Z
UID:c_9ogZX5tCtICdjajVYdrksV@stanza.co
SUMMARY:Power @ Grasshoppers
DESCRIPTION:Power @ Grasshoppers\n\nFollow on MiLB First Pitch: https://stza.co/+wiA0-e\n\nShop: https://stza.co/+wiA0-2t\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144605Z
LAST-MODIFIED:20180213T144605Z
TRANSP:OPAQUE
END:VEVENT
* Power @ Braves
<2018-08-10 Fri 18:00-21:00>
:PROPERTIES:
:ID:       4FahMRyETaCddJrQ6FZnAKLP@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Power @ Braves Power @ Braves

Follow on MiLB First Pitch  https //stza.co/+vO1w-35

Shop  https //stza.co/+vO1w-3s

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Power @ Braves
END:VALARM
DTSTART:20180810T230000Z
DTEND:20180811T020000Z
UID:4FahMRyETaCddJrQ6FZnAKLP@stanza.co
SUMMARY:Power @ Braves
DESCRIPTION:Power @ Braves\n\nFollow on MiLB First Pitch: https://stza.co/+vO1w-35\n\nShop: https://stza.co/+vO1w-3s\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144605Z
LAST-MODIFIED:20180213T144605Z
TRANSP:OPAQUE
END:VEVENT
* Power @ Braves
<2018-08-11 Sat 17:00-20:00>
:PROPERTIES:
:ID:       K-xlJAmGmNsFi2r_c7brL2GJ@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Power @ Braves Power @ Braves

Follow on MiLB First Pitch  https //stza.co/+vO1x-1F

Shop  https //stza.co/+vO1x-N

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Power @ Braves
END:VALARM
DTSTART:20180811T220000Z
DTEND:20180812T010000Z
UID:K-xlJAmGmNsFi2r_c7brL2GJ@stanza.co
SUMMARY:Power @ Braves
DESCRIPTION:Power @ Braves\n\nFollow on MiLB First Pitch: https://stza.co/+vO1x-1F\n\nShop: https://stza.co/+vO1x-N\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144605Z
LAST-MODIFIED:20180213T144605Z
TRANSP:OPAQUE
END:VEVENT
* Power @ Braves
<2018-08-12 Sun 13:00-16:00>
:PROPERTIES:
:ID:       8IJle-bRs1PwmHwPlTaFnprT@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Power @ Braves Power @ Braves

Follow on MiLB First Pitch  https //stza.co/+vO1y-1H

Shop  https //stza.co/+vO1y-1W

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Power @ Braves
END:VALARM
DTSTART:20180812T180000Z
DTEND:20180812T210000Z
UID:8IJle-bRs1PwmHwPlTaFnprT@stanza.co
SUMMARY:Power @ Braves
DESCRIPTION:Power @ Braves\n\nFollow on MiLB First Pitch: https://stza.co/+vO1y-1H\n\nShop: https://stza.co/+vO1y-1W\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144605Z
LAST-MODIFIED:20180213T144605Z
TRANSP:OPAQUE
END:VEVENT
* Power @ Braves
<2018-08-13 Mon 18:00-21:00>
:PROPERTIES:
:ID:       EY-0ejWaOzmccZjEjvWUBHfm@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Power @ Braves Power @ Braves

Follow on MiLB First Pitch  https //stza.co/+vO1z-1F

Shop  https //stza.co/+vO1z-8

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Power @ Braves
END:VALARM
DTSTART:20180813T230000Z
DTEND:20180814T020000Z
UID:EY-0ejWaOzmccZjEjvWUBHfm@stanza.co
SUMMARY:Power @ Braves
DESCRIPTION:Power @ Braves\n\nFollow on MiLB First Pitch: https://stza.co/+vO1z-1F\n\nShop: https://stza.co/+vO1z-8\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144605Z
LAST-MODIFIED:20180213T144605Z
TRANSP:OPAQUE
END:VEVENT
* Power vs. Fireflies
<2018-08-15 Wed 18:05-21:05>
:PROPERTIES:
:ID:       JROlRT1q6R6SVAM4mSpjZor3@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Power vs. Fireflies Power vs. Fireflies

Follow on MiLB First Pitch  https //stza.co/+xJ6q-3N

Shop  https //stza.co/+xJ6q-c

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Power vs. Fireflies
END:VALARM
DTSTART:20180815T230500Z
DTEND:20180816T020500Z
UID:JROlRT1q6R6SVAM4mSpjZor3@stanza.co
SUMMARY:Power vs. Fireflies
DESCRIPTION:Power vs. Fireflies\n\nFollow on MiLB First Pitch: https://stza.co/+xJ6q-3N\n\nShop: https://stza.co/+xJ6q-c\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144605Z
LAST-MODIFIED:20180213T144605Z
TRANSP:OPAQUE
END:VEVENT
* Power vs. Fireflies
<2018-08-16 Thu 18:05-21:05>
:PROPERTIES:
:ID:       4RtJU6ucPbGAUUtWJFfherf7@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Power vs. Fireflies Power vs. Fireflies

Follow on MiLB First Pitch  https //stza.co/+xJ6s-6

Shop  https //stza.co/+xJ6s-p

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Power vs. Fireflies
END:VALARM
DTSTART:20180816T230500Z
DTEND:20180817T020500Z
UID:4RtJU6ucPbGAUUtWJFfherf7@stanza.co
SUMMARY:Power vs. Fireflies
DESCRIPTION:Power vs. Fireflies\n\nFollow on MiLB First Pitch: https://stza.co/+xJ6s-6\n\nShop: https://stza.co/+xJ6s-p\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144605Z
LAST-MODIFIED:20180213T144605Z
TRANSP:OPAQUE
END:VEVENT
* Power vs. Fireflies
<2018-08-17 Fri 18:05-21:05>
:PROPERTIES:
:ID:       abGNp_XApNOlfK8yU1XwRyYc@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Power vs. Fireflies Power vs. Fireflies

Follow on MiLB First Pitch  https //stza.co/+xJ6u-2h

Shop  https //stza.co/+xJ6u-3T

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Power vs. Fireflies
END:VALARM
DTSTART:20180817T230500Z
DTEND:20180818T020500Z
UID:abGNp_XApNOlfK8yU1XwRyYc@stanza.co
SUMMARY:Power vs. Fireflies
DESCRIPTION:Power vs. Fireflies\n\nFollow on MiLB First Pitch: https://stza.co/+xJ6u-2h\n\nShop: https://stza.co/+xJ6u-3T\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144605Z
LAST-MODIFIED:20180213T144605Z
TRANSP:OPAQUE
END:VEVENT
* Power vs. RiverDogs
<2018-08-18 Sat 17:05-20:05>
:PROPERTIES:
:ID:       557i6hAsoTf9xpyUhyMs02Sc@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Power vs. RiverDogs Power vs. RiverDogs

Follow on MiLB First Pitch  https //stza.co/+xJ6w-3d

Shop  https //stza.co/+xJ6w-D

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Power vs. RiverDogs
END:VALARM
DTSTART:20180818T220500Z
DTEND:20180819T010500Z
UID:557i6hAsoTf9xpyUhyMs02Sc@stanza.co
SUMMARY:Power vs. RiverDogs
DESCRIPTION:Power vs. RiverDogs\n\nFollow on MiLB First Pitch: https://stza.co/+xJ6w-3d\n\nShop: https://stza.co/+xJ6w-D\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144605Z
LAST-MODIFIED:20180213T144605Z
TRANSP:OPAQUE
END:VEVENT
* Power vs. RiverDogs
<2018-08-19 Sun 13:05-16:05>
:PROPERTIES:
:ID:       WjJZM4W7A-rsFCmarWJmud_c@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Power vs. RiverDogs Power vs. RiverDogs

Follow on MiLB First Pitch  https //stza.co/+xJ6x-1J

Shop  https //stza.co/+xJ6x-3e

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Power vs. RiverDogs
END:VALARM
DTSTART:20180819T180500Z
DTEND:20180819T210500Z
UID:WjJZM4W7A-rsFCmarWJmud_c@stanza.co
SUMMARY:Power vs. RiverDogs
DESCRIPTION:Power vs. RiverDogs\n\nFollow on MiLB First Pitch: https://stza.co/+xJ6x-1J\n\nShop: https://stza.co/+xJ6x-3e\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144605Z
LAST-MODIFIED:20180213T144605Z
TRANSP:OPAQUE
END:VEVENT
* Power vs. RiverDogs
<2018-08-20 Mon 18:05-21:05>
:PROPERTIES:
:ID:       Wx5-4XqzWUefW9BBYm5M4B4q@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Power vs. RiverDogs Power vs. RiverDogs

Follow on MiLB First Pitch  https //stza.co/+xJ6A-V

Shop  https //stza.co/+xJ6A-s

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Power vs. RiverDogs
END:VALARM
DTSTART:20180820T230500Z
DTEND:20180821T020500Z
UID:Wx5-4XqzWUefW9BBYm5M4B4q@stanza.co
SUMMARY:Power vs. RiverDogs
DESCRIPTION:Power vs. RiverDogs\n\nFollow on MiLB First Pitch: https://stza.co/+xJ6A-V\n\nShop: https://stza.co/+xJ6A-s\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144605Z
LAST-MODIFIED:20180213T144605Z
TRANSP:OPAQUE
END:VEVENT
* Power vs. RiverDogs
<2018-08-21 Tue 18:05-21:05>
:PROPERTIES:
:ID:       E_9wwgL1iPovX8rp47GB8dYe@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Power vs. RiverDogs Power vs. RiverDogs

Follow on MiLB First Pitch  https //stza.co/+xJ6B-_

Shop  https //stza.co/+xJ6B-O

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Power vs. RiverDogs
END:VALARM
DTSTART:20180821T230500Z
DTEND:20180822T020500Z
UID:E_9wwgL1iPovX8rp47GB8dYe@stanza.co
SUMMARY:Power vs. RiverDogs
DESCRIPTION:Power vs. RiverDogs\n\nFollow on MiLB First Pitch: https://stza.co/+xJ6B-_\n\nShop: https://stza.co/+xJ6B-O\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144605Z
LAST-MODIFIED:20180213T144605Z
TRANSP:OPAQUE
END:VEVENT
* Power @ Braves
<2018-08-23 Thu 18:00-21:00>
:PROPERTIES:
:ID:       WD2XxV7Kp87Rf0oPVvlbM944@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Power @ Braves Power @ Braves

Follow on MiLB First Pitch  https //stza.co/+vO1A-22

Shop  https //stza.co/+vO1A-1o

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Power @ Braves
END:VALARM
DTSTART:20180823T230000Z
DTEND:20180824T020000Z
UID:WD2XxV7Kp87Rf0oPVvlbM944@stanza.co
SUMMARY:Power @ Braves
DESCRIPTION:Power @ Braves\n\nFollow on MiLB First Pitch: https://stza.co/+vO1A-22\n\nShop: https://stza.co/+vO1A-1o\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144605Z
LAST-MODIFIED:20180213T144605Z
TRANSP:OPAQUE
END:VEVENT
* Power @ Braves
<2018-08-24 Fri 18:00-21:00>
:PROPERTIES:
:ID:       sP_YOXOTnMI8R5EPD9kiXn7A@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Power @ Braves Power @ Braves

Follow on MiLB First Pitch  https //stza.co/+vO1B-2I

Shop  https //stza.co/+vO1B-37

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Power @ Braves
END:VALARM
DTSTART:20180824T230000Z
DTEND:20180825T020000Z
UID:sP_YOXOTnMI8R5EPD9kiXn7A@stanza.co
SUMMARY:Power @ Braves
DESCRIPTION:Power @ Braves\n\nFollow on MiLB First Pitch: https://stza.co/+vO1B-2I\n\nShop: https://stza.co/+vO1B-37\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144605Z
LAST-MODIFIED:20180213T144605Z
TRANSP:OPAQUE
END:VEVENT
* Power @ Braves
<2018-08-25 Sat 17:00-20:00>
:PROPERTIES:
:ID:       JXU01arLWZ5kiFFq54v6GfQf@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Power @ Braves Power @ Braves

Follow on MiLB First Pitch  https //stza.co/+vO1C-2

Shop  https //stza.co/+vO1C-22

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Power @ Braves
END:VALARM
DTSTART:20180825T220000Z
DTEND:20180826T010000Z
UID:JXU01arLWZ5kiFFq54v6GfQf@stanza.co
SUMMARY:Power @ Braves
DESCRIPTION:Power @ Braves\n\nFollow on MiLB First Pitch: https://stza.co/+vO1C-2\n\nShop: https://stza.co/+vO1C-22\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144605Z
LAST-MODIFIED:20180213T144605Z
TRANSP:OPAQUE
END:VEVENT
* Power @ Braves
<2018-08-26 Sun 13:00-16:00>
:PROPERTIES:
:ID:       9n_4DG6WT8nQgdU2MTd0DmA2@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Power @ Braves Power @ Braves

Follow on MiLB First Pitch  https //stza.co/+vO1D-1P

Shop  https //stza.co/+vO1D-B

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Power @ Braves
END:VALARM
DTSTART:20180826T180000Z
DTEND:20180826T210000Z
UID:9n_4DG6WT8nQgdU2MTd0DmA2@stanza.co
SUMMARY:Power @ Braves
DESCRIPTION:Power @ Braves\n\nFollow on MiLB First Pitch: https://stza.co/+vO1D-1P\n\nShop: https://stza.co/+vO1D-B\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144605Z
LAST-MODIFIED:20180213T144605Z
TRANSP:OPAQUE
END:VEVENT
* Power vs. Suns
<2018-08-27 Mon 18:05-21:05>
:PROPERTIES:
:ID:       K5RqdmmRS6qI76VrbAd0rvbc@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Power vs. Suns Power vs. Suns

Follow on MiLB First Pitch  https //stza.co/+xJ6E-2S

Shop  https //stza.co/+xJ6E-26

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Power vs. Suns
END:VALARM
DTSTART:20180827T230500Z
DTEND:20180828T020500Z
UID:K5RqdmmRS6qI76VrbAd0rvbc@stanza.co
SUMMARY:Power vs. Suns
DESCRIPTION:Power vs. Suns\n\nFollow on MiLB First Pitch: https://stza.co/+xJ6E-2S\n\nShop: https://stza.co/+xJ6E-26\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144605Z
LAST-MODIFIED:20180213T144605Z
TRANSP:OPAQUE
END:VEVENT
* Power vs. Suns
<2018-08-28 Tue 18:05-21:05>
:PROPERTIES:
:ID:       j8EEkpOMKX5YIphqqXTHz_wA@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Power vs. Suns Power vs. Suns

Follow on MiLB First Pitch  https //stza.co/+xJ6F-3T

Shop  https //stza.co/+xJ6F-g

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Power vs. Suns
END:VALARM
DTSTART:20180828T230500Z
DTEND:20180829T020500Z
UID:j8EEkpOMKX5YIphqqXTHz_wA@stanza.co
SUMMARY:Power vs. Suns
DESCRIPTION:Power vs. Suns\n\nFollow on MiLB First Pitch: https://stza.co/+xJ6F-3T\n\nShop: https://stza.co/+xJ6F-g\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144605Z
LAST-MODIFIED:20180213T144605Z
TRANSP:OPAQUE
END:VEVENT
* Power vs. Suns
<2018-08-29 Wed 18:05-21:05>
:PROPERTIES:
:ID:       o6hZYa3pH4N5yZsNVr5gUHXM@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Power vs. Suns Power vs. Suns

Follow on MiLB First Pitch  https //stza.co/+xJ6H-z

Shop  https //stza.co/+xJ6H-37

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Power vs. Suns
END:VALARM
DTSTART:20180829T230500Z
DTEND:20180830T020500Z
UID:o6hZYa3pH4N5yZsNVr5gUHXM@stanza.co
SUMMARY:Power vs. Suns
DESCRIPTION:Power vs. Suns\n\nFollow on MiLB First Pitch: https://stza.co/+xJ6H-z\n\nShop: https://stza.co/+xJ6H-37\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144605Z
LAST-MODIFIED:20180213T144605Z
TRANSP:OPAQUE
END:VEVENT
* Power vs. Suns
<2018-08-30 Thu 18:05-21:05>
:PROPERTIES:
:ID:       mhyfAIRfQ2zaT5xOW5atvwHg@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Power vs. Suns Power vs. Suns

Follow on MiLB First Pitch  https //stza.co/+xJ6J-2U

Shop  https //stza.co/+xJ6J-2Y

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Power vs. Suns
END:VALARM
DTSTART:20180830T230500Z
DTEND:20180831T020500Z
UID:mhyfAIRfQ2zaT5xOW5atvwHg@stanza.co
SUMMARY:Power vs. Suns
DESCRIPTION:Power vs. Suns\n\nFollow on MiLB First Pitch: https://stza.co/+xJ6J-2U\n\nShop: https://stza.co/+xJ6J-2Y\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144605Z
LAST-MODIFIED:20180213T144605Z
TRANSP:OPAQUE
END:VEVENT
* Power @ RiverDogs
<2018-08-31 Fri 18:05-21:05>
:PROPERTIES:
:ID:       Fvl7DRl6tD581j-DLYIRGL7j@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Power @ RiverDogs Power @ RiverDogs

Follow on MiLB First Pitch  https //stza.co/+vO0F-

Shop  https //stza.co/+vO0F-1s

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Power @ RiverDogs
END:VALARM
DTSTART:20180831T230500Z
DTEND:20180901T020500Z
UID:Fvl7DRl6tD581j-DLYIRGL7j@stanza.co
SUMMARY:Power @ RiverDogs
DESCRIPTION:Power @ RiverDogs\n\nFollow on MiLB First Pitch: https://stza.co/+vO0F-\n\nShop: https://stza.co/+vO0F-1s\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144605Z
LAST-MODIFIED:20180213T144605Z
TRANSP:OPAQUE
END:VEVENT
* Power @ RiverDogs
<2018-09-01 Sat 17:05-20:05>
:PROPERTIES:
:ID:       33-zexVkyU633FLxX96BAila@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Power @ RiverDogs Power @ RiverDogs

Follow on MiLB First Pitch  https //stza.co/+vO0G-e

Shop  https //stza.co/+vO0G-3x

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Power @ RiverDogs
END:VALARM
DTSTART:20180901T220500Z
DTEND:20180902T010500Z
UID:33-zexVkyU633FLxX96BAila@stanza.co
SUMMARY:Power @ RiverDogs
DESCRIPTION:Power @ RiverDogs\n\nFollow on MiLB First Pitch: https://stza.co/+vO0G-e\n\nShop: https://stza.co/+vO0G-3x\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144605Z
LAST-MODIFIED:20180213T144605Z
TRANSP:OPAQUE
END:VEVENT
* Power @ RiverDogs
<2018-09-02 Sun 16:05-19:05>
:PROPERTIES:
:ID:       vk-7nSi7ykD2cHQKhKs75P3l@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Power @ RiverDogs Power @ RiverDogs

Follow on MiLB First Pitch  https //stza.co/+vO0H-1r

Shop  https //stza.co/+vO0H-2U

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Power @ RiverDogs
END:VALARM
DTSTART:20180902T210500Z
DTEND:20180903T000500Z
UID:vk-7nSi7ykD2cHQKhKs75P3l@stanza.co
SUMMARY:Power @ RiverDogs
DESCRIPTION:Power @ RiverDogs\n\nFollow on MiLB First Pitch: https://stza.co/+vO0H-1r\n\nShop: https://stza.co/+vO0H-2U\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144605Z
LAST-MODIFIED:20180213T144605Z
TRANSP:OPAQUE
END:VEVENT
* Power @ RiverDogs
<2018-09-03 Mon 13:05-16:05>
:PROPERTIES:
:ID:       QJthcKzV_zkiC09T8hc5ZaMT@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Power @ RiverDogs Power @ RiverDogs

Follow on MiLB First Pitch  https //stza.co/+vO0I-3p

Shop  https //stza.co/+vO0I-2

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Power @ RiverDogs
END:VALARM
DTSTART:20180903T180500Z
DTEND:20180903T210500Z
UID:QJthcKzV_zkiC09T8hc5ZaMT@stanza.co
SUMMARY:Power @ RiverDogs
DESCRIPTION:Power @ RiverDogs\n\nFollow on MiLB First Pitch: https://stza.co/+vO0I-3p\n\nShop: https://stza.co/+vO0I-2\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144605Z
LAST-MODIFIED:20180213T144605Z
TRANSP:OPAQUE
END:VEVENT
