#+TITLE:       Main Google calendar entries
#+AUTHOR:      Eric S Fraga
#+EMAIL:       e.fraga@ucl.ac.uk
#+DESCRIPTION: converted using the ical2org awk script
#+CATEGORY:    google
#+STARTUP:     hidestars
#+STARTUP:     overview

* COMMENT original iCal preamble

* Pirates @ Astros
<2018-06-19 Tue>--<2018-06-18 Mon>
:PROPERTIES:
:ID:       rZq5LVciEKEHK5kwOSDPo1tQ@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Pirates @ Astros Pirates @ Astros

Follow on MiLB First Pitch  https //stza.co/+xCGj-1E

Shop  https //stza.co/+xCGj-1K

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Pirates @ Astros
END:VALARM
DTSTART;VALUE=DATE:20180619
DTEND;VALUE=DATE:20180619
UID:rZq5LVciEKEHK5kwOSDPo1tQ@stanza.co
SUMMARY:Pirates @ Astros
DESCRIPTION:Pirates @ Astros\n\nFollow on MiLB First Pitch: https://stza.co/+xCGj-1E\n\nShop: https://stza.co/+xCGj-1K\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144509Z
LAST-MODIFIED:20180213T144509Z
TRANSP:OPAQUE
END:VEVENT
* Pirates @ Astros
<2018-06-20 Wed>--<2018-06-19 Tue>
:PROPERTIES:
:ID:       eAtO2zSpjbflQP39c7CCpyo8@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Pirates @ Astros Pirates @ Astros

Follow on MiLB First Pitch  https //stza.co/+xCGk-e

Shop  https //stza.co/+xCGk-_

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Pirates @ Astros
END:VALARM
DTSTART;VALUE=DATE:20180620
DTEND;VALUE=DATE:20180620
UID:eAtO2zSpjbflQP39c7CCpyo8@stanza.co
SUMMARY:Pirates @ Astros
DESCRIPTION:Pirates @ Astros\n\nFollow on MiLB First Pitch: https://stza.co/+xCGk-e\n\nShop: https://stza.co/+xCGk-_\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144509Z
LAST-MODIFIED:20180213T144509Z
TRANSP:OPAQUE
END:VEVENT
* Pirates @ Astros
<2018-06-21 Thu>--<2018-06-20 Wed>
:PROPERTIES:
:ID:       P8xhznpA95LIGs8VlyCigoV2@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Pirates @ Astros Pirates @ Astros

Follow on MiLB First Pitch  https //stza.co/+xCGl-3u

Shop  https //stza.co/+xCGl-3x

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Pirates @ Astros
END:VALARM
DTSTART;VALUE=DATE:20180621
DTEND;VALUE=DATE:20180621
UID:P8xhznpA95LIGs8VlyCigoV2@stanza.co
SUMMARY:Pirates @ Astros
DESCRIPTION:Pirates @ Astros\n\nFollow on MiLB First Pitch: https://stza.co/+xCGl-3u\n\nShop: https://stza.co/+xCGl-3x\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144509Z
LAST-MODIFIED:20180213T144509Z
TRANSP:OPAQUE
END:VEVENT
* Pirates vs. Twins
<2018-06-22 Fri>--<2018-06-21 Thu>
:PROPERTIES:
:ID:       VEbwVlweRK51s3e4aQfBcE0b@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Pirates vs. Twins Pirates vs. Twins

Follow on MiLB First Pitch  https //stza.co/+xCGn-1g

Shop  https //stza.co/+xCGn-2M

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Pirates vs. Twins
END:VALARM
DTSTART;VALUE=DATE:20180622
DTEND;VALUE=DATE:20180622
UID:VEbwVlweRK51s3e4aQfBcE0b@stanza.co
SUMMARY:Pirates vs. Twins
DESCRIPTION:Pirates vs. Twins\n\nFollow on MiLB First Pitch: https://stza.co/+xCGn-1g\n\nShop: https://stza.co/+xCGn-2M\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144509Z
LAST-MODIFIED:20180213T144509Z
TRANSP:OPAQUE
END:VEVENT
* Pirates vs. Twins
<2018-06-23 Sat>--<2018-06-22 Fri>
:PROPERTIES:
:ID:       iDpFmytRHc4deRwryYekqTI3@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Pirates vs. Twins Pirates vs. Twins

Follow on MiLB First Pitch  https //stza.co/+xCGo-H

Shop  https //stza.co/+xCGo-3z

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Pirates vs. Twins
END:VALARM
DTSTART;VALUE=DATE:20180623
DTEND;VALUE=DATE:20180623
UID:iDpFmytRHc4deRwryYekqTI3@stanza.co
SUMMARY:Pirates vs. Twins
DESCRIPTION:Pirates vs. Twins\n\nFollow on MiLB First Pitch: https://stza.co/+xCGo-H\n\nShop: https://stza.co/+xCGo-3z\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144509Z
LAST-MODIFIED:20180213T144509Z
TRANSP:OPAQUE
END:VEVENT
* Pirates vs. Twins
<2018-06-24 Sun>--<2018-06-23 Sat>
:PROPERTIES:
:ID:       02_1HBhY0-Vx4spDV13RZGyV@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Pirates vs. Twins Pirates vs. Twins

Follow on MiLB First Pitch  https //stza.co/+xCGq-1u

Shop  https //stza.co/+xCGq-3y

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Pirates vs. Twins
END:VALARM
DTSTART;VALUE=DATE:20180624
DTEND;VALUE=DATE:20180624
UID:02_1HBhY0-Vx4spDV13RZGyV@stanza.co
SUMMARY:Pirates vs. Twins
DESCRIPTION:Pirates vs. Twins\n\nFollow on MiLB First Pitch: https://stza.co/+xCGq-1u\n\nShop: https://stza.co/+xCGq-3y\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144509Z
LAST-MODIFIED:20180213T144509Z
TRANSP:OPAQUE
END:VEVENT
* Pirates vs. Yankees
<2018-06-25 Mon>--<2018-06-24 Sun>
:PROPERTIES:
:ID:       CTF4dXu4mTC1Ylkg7kasa1yj@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Pirates vs. Yankees Pirates vs. Yankees

Follow on MiLB First Pitch  https //stza.co/+xCGt-3b

Shop  https //stza.co/+xCGt-3n

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Pirates vs. Yankees
END:VALARM
DTSTART;VALUE=DATE:20180625
DTEND;VALUE=DATE:20180625
UID:CTF4dXu4mTC1Ylkg7kasa1yj@stanza.co
SUMMARY:Pirates vs. Yankees
DESCRIPTION:Pirates vs. Yankees\n\nFollow on MiLB First Pitch: https://stza.co/+xCGt-3b\n\nShop: https://stza.co/+xCGt-3n\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144509Z
LAST-MODIFIED:20180213T144509Z
TRANSP:OPAQUE
END:VEVENT
* Pirates vs. Yankees
<2018-06-26 Tue>--<2018-06-25 Mon>
:PROPERTIES:
:ID:       pNVLg30mRdB4MGyX2Wnu_9ox@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Pirates vs. Yankees Pirates vs. Yankees

Follow on MiLB First Pitch  https //stza.co/+xCGv-m

Shop  https //stza.co/+xCGv-1y

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Pirates vs. Yankees
END:VALARM
DTSTART;VALUE=DATE:20180626
DTEND;VALUE=DATE:20180626
UID:pNVLg30mRdB4MGyX2Wnu_9ox@stanza.co
SUMMARY:Pirates vs. Yankees
DESCRIPTION:Pirates vs. Yankees\n\nFollow on MiLB First Pitch: https://stza.co/+xCGv-m\n\nShop: https://stza.co/+xCGv-1y\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144509Z
LAST-MODIFIED:20180213T144509Z
TRANSP:OPAQUE
END:VEVENT
* Pirates @ Rays
<2018-06-28 Thu>--<2018-06-27 Wed>
:PROPERTIES:
:ID:       JEKR0uuHFBOSbjSBX1W5XNqW@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Pirates @ Rays Pirates @ Rays

Follow on MiLB First Pitch  https //stza.co/+xCGw-p

Shop  https //stza.co/+xCGw-2A

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Pirates @ Rays
END:VALARM
DTSTART;VALUE=DATE:20180628
DTEND;VALUE=DATE:20180628
UID:JEKR0uuHFBOSbjSBX1W5XNqW@stanza.co
SUMMARY:Pirates @ Rays
DESCRIPTION:Pirates @ Rays\n\nFollow on MiLB First Pitch: https://stza.co/+xCGw-p\n\nShop: https://stza.co/+xCGw-2A\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144509Z
LAST-MODIFIED:20180213T144509Z
TRANSP:OPAQUE
END:VEVENT
* Pirates @ Rays
<2018-06-29 Fri>--<2018-06-28 Thu>
:PROPERTIES:
:ID:       B2Kj7yjPqdqZ4KUIc7G1pvEE@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Pirates @ Rays Pirates @ Rays

Follow on MiLB First Pitch  https //stza.co/+xCGx-1T

Shop  https //stza.co/+xCGx-1F

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Pirates @ Rays
END:VALARM
DTSTART;VALUE=DATE:20180629
DTEND;VALUE=DATE:20180629
UID:B2Kj7yjPqdqZ4KUIc7G1pvEE@stanza.co
SUMMARY:Pirates @ Rays
DESCRIPTION:Pirates @ Rays\n\nFollow on MiLB First Pitch: https://stza.co/+xCGx-1T\n\nShop: https://stza.co/+xCGx-1F\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144509Z
LAST-MODIFIED:20180213T144509Z
TRANSP:OPAQUE
END:VEVENT
* Pirates @ Rays
<2018-06-30 Sat>--<2018-06-29 Fri>
:PROPERTIES:
:ID:       hzGJmeTGD9UQJSVn6NZcBHwv@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Pirates @ Rays Pirates @ Rays

Follow on MiLB First Pitch  https //stza.co/+xCGy-3V

Shop  https //stza.co/+xCGy-3A

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Pirates @ Rays
END:VALARM
DTSTART;VALUE=DATE:20180630
DTEND;VALUE=DATE:20180630
UID:hzGJmeTGD9UQJSVn6NZcBHwv@stanza.co
SUMMARY:Pirates @ Rays
DESCRIPTION:Pirates @ Rays\n\nFollow on MiLB First Pitch: https://stza.co/+xCGy-3V\n\nShop: https://stza.co/+xCGy-3A\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144509Z
LAST-MODIFIED:20180213T144509Z
TRANSP:OPAQUE
END:VEVENT
* Pirates @ Braves
<2018-07-01 Sun 15:00-18:00>
:PROPERTIES:
:ID:       XQlmEehMD4sJeg6TNWTesiAy@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Pirates @ Braves Pirates @ Braves

Follow on MiLB First Pitch  https //stza.co/+xDS7-D

Shop  https //stza.co/+xDS7-1t

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Pirates @ Braves
END:VALARM
DTSTART:20180701T200000Z
DTEND:20180701T230000Z
UID:XQlmEehMD4sJeg6TNWTesiAy@stanza.co
SUMMARY:Pirates @ Braves
DESCRIPTION:Pirates @ Braves\n\nFollow on MiLB First Pitch: https://stza.co/+xDS7-D\n\nShop: https://stza.co/+xDS7-1t\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144509Z
LAST-MODIFIED:20180213T144509Z
TRANSP:OPAQUE
END:VEVENT
* Pirates @ Braves
<2018-07-02 Mon 18:00-21:00>
:PROPERTIES:
:ID:       RGfD66MP6CxONMcYa7m1p0s6@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Pirates @ Braves Pirates @ Braves

Follow on MiLB First Pitch  https //stza.co/+xDS8-2X

Shop  https //stza.co/+xDS8-2j

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Pirates @ Braves
END:VALARM
DTSTART:20180702T230000Z
DTEND:20180703T020000Z
UID:RGfD66MP6CxONMcYa7m1p0s6@stanza.co
SUMMARY:Pirates @ Braves
DESCRIPTION:Pirates @ Braves\n\nFollow on MiLB First Pitch: https://stza.co/+xDS8-2X\n\nShop: https://stza.co/+xDS8-2j\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144509Z
LAST-MODIFIED:20180213T144509Z
TRANSP:OPAQUE
END:VEVENT
* Pirates @ Braves
<2018-07-03 Tue 18:00-21:00>
:PROPERTIES:
:ID:       J0yBocbpNw2L0MMEDTTTPdEX@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Pirates @ Braves Pirates @ Braves

Follow on MiLB First Pitch  https //stza.co/+xDS9-1n

Shop  https //stza.co/+xDS9-1u

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Pirates @ Braves
END:VALARM
DTSTART:20180703T230000Z
DTEND:20180704T020000Z
UID:J0yBocbpNw2L0MMEDTTTPdEX@stanza.co
SUMMARY:Pirates @ Braves
DESCRIPTION:Pirates @ Braves\n\nFollow on MiLB First Pitch: https://stza.co/+xDS9-1n\n\nShop: https://stza.co/+xDS9-1u\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144509Z
LAST-MODIFIED:20180213T144509Z
TRANSP:OPAQUE
END:VEVENT
* Pirates vs. Cardinals
<2018-07-04 Wed>--<2018-07-03 Tue>
:PROPERTIES:
:ID:       1z0_n9cne79u8-9ZVlPMFC1_@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Pirates vs. Cardinals Pirates vs. Cardinals

Follow on MiLB First Pitch  https //stza.co/+xCGD-2i

Shop  https //stza.co/+xCGD-1Z

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Pirates vs. Cardinals
END:VALARM
DTSTART;VALUE=DATE:20180704
DTEND;VALUE=DATE:20180704
UID:1z0_n9cne79u8-9ZVlPMFC1_@stanza.co
SUMMARY:Pirates vs. Cardinals
DESCRIPTION:Pirates vs. Cardinals\n\nFollow on MiLB First Pitch: https://stza.co/+xCGD-2i\n\nShop: https://stza.co/+xCGD-1Z\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144509Z
LAST-MODIFIED:20180213T144509Z
TRANSP:OPAQUE
END:VEVENT
* Pirates vs. Cardinals
<2018-07-05 Thu>--<2018-07-04 Wed>
:PROPERTIES:
:ID:       HkinNwF_1mHwACjkw3NhKodx@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Pirates vs. Cardinals Pirates vs. Cardinals

Follow on MiLB First Pitch  https //stza.co/+xCGE-M

Shop  https //stza.co/+xCGE-n

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Pirates vs. Cardinals
END:VALARM
DTSTART;VALUE=DATE:20180705
DTEND;VALUE=DATE:20180705
UID:HkinNwF_1mHwACjkw3NhKodx@stanza.co
SUMMARY:Pirates vs. Cardinals
DESCRIPTION:Pirates vs. Cardinals\n\nFollow on MiLB First Pitch: https://stza.co/+xCGE-M\n\nShop: https://stza.co/+xCGE-n\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144509Z
LAST-MODIFIED:20180213T144509Z
TRANSP:OPAQUE
END:VEVENT
* Pirates vs. Cardinals
<2018-07-06 Fri>--<2018-07-05 Thu>
:PROPERTIES:
:ID:       AmOR0xT18T5eYR-zJvZoRRMV@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Pirates vs. Cardinals Pirates vs. Cardinals

Follow on MiLB First Pitch  https //stza.co/+xCGH-2z

Shop  https //stza.co/+xCGH-O

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Pirates vs. Cardinals
END:VALARM
DTSTART;VALUE=DATE:20180706
DTEND;VALUE=DATE:20180706
UID:AmOR0xT18T5eYR-zJvZoRRMV@stanza.co
SUMMARY:Pirates vs. Cardinals
DESCRIPTION:Pirates vs. Cardinals\n\nFollow on MiLB First Pitch: https://stza.co/+xCGH-2z\n\nShop: https://stza.co/+xCGH-O\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144509Z
LAST-MODIFIED:20180213T144509Z
TRANSP:OPAQUE
END:VEVENT
* Pirates vs. Rays
<2018-07-07 Sat>--<2018-07-06 Fri>
:PROPERTIES:
:ID:       LOiXfGwP4-1G-Exy9AJcGv0r@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Pirates vs. Rays Pirates vs. Rays

Follow on MiLB First Pitch  https //stza.co/+xCGJ-1l

Shop  https //stza.co/+xCGJ-2m

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Pirates vs. Rays
END:VALARM
DTSTART;VALUE=DATE:20180707
DTEND;VALUE=DATE:20180707
UID:LOiXfGwP4-1G-Exy9AJcGv0r@stanza.co
SUMMARY:Pirates vs. Rays
DESCRIPTION:Pirates vs. Rays\n\nFollow on MiLB First Pitch: https://stza.co/+xCGJ-1l\n\nShop: https://stza.co/+xCGJ-2m\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144509Z
LAST-MODIFIED:20180213T144509Z
TRANSP:OPAQUE
END:VEVENT
* Pirates vs. Rays
<2018-07-08 Sun>--<2018-07-07 Sat>
:PROPERTIES:
:ID:       xDFRpeEhb_5z5IjtstSiX7oB@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Pirates vs. Rays Pirates vs. Rays

Follow on MiLB First Pitch  https //stza.co/+xCGL-3K

Shop  https //stza.co/+xCGL-2F

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Pirates vs. Rays
END:VALARM
DTSTART;VALUE=DATE:20180708
DTEND;VALUE=DATE:20180708
UID:xDFRpeEhb_5z5IjtstSiX7oB@stanza.co
SUMMARY:Pirates vs. Rays
DESCRIPTION:Pirates vs. Rays\n\nFollow on MiLB First Pitch: https://stza.co/+xCGL-3K\n\nShop: https://stza.co/+xCGL-2F\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144509Z
LAST-MODIFIED:20180213T144509Z
TRANSP:OPAQUE
END:VEVENT
* Pirates vs. Rays
<2018-07-09 Mon>--<2018-07-08 Sun>
:PROPERTIES:
:ID:       --9xK0ZG3ALcGX46WC2TBtlv@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Pirates vs. Rays Pirates vs. Rays

Follow on MiLB First Pitch  https //stza.co/+xCGM-K

Shop  https //stza.co/+xCGM-U

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Pirates vs. Rays
END:VALARM
DTSTART;VALUE=DATE:20180709
DTEND;VALUE=DATE:20180709
UID:--9xK0ZG3ALcGX46WC2TBtlv@stanza.co
SUMMARY:Pirates vs. Rays
DESCRIPTION:Pirates vs. Rays\n\nFollow on MiLB First Pitch: https://stza.co/+xCGM-K\n\nShop: https://stza.co/+xCGM-U\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144509Z
LAST-MODIFIED:20180213T144509Z
TRANSP:OPAQUE
END:VEVENT
* Pirates @ Yankees
<2018-07-10 Tue>--<2018-07-09 Mon>
:PROPERTIES:
:ID:       VyWXkXO2P4WdueQPm51yjaG0@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Pirates @ Yankees Pirates @ Yankees

Follow on MiLB First Pitch  https //stza.co/+xCGO-3O

Shop  https //stza.co/+xCGO-p

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Pirates @ Yankees
END:VALARM
DTSTART;VALUE=DATE:20180710
DTEND;VALUE=DATE:20180710
UID:VyWXkXO2P4WdueQPm51yjaG0@stanza.co
SUMMARY:Pirates @ Yankees
DESCRIPTION:Pirates @ Yankees\n\nFollow on MiLB First Pitch: https://stza.co/+xCGO-3O\n\nShop: https://stza.co/+xCGO-p\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144509Z
LAST-MODIFIED:20180213T144509Z
TRANSP:OPAQUE
END:VEVENT
* Pirates @ Yankees
<2018-07-11 Wed>--<2018-07-10 Tue>
:PROPERTIES:
:ID:       GicUULZFWFyDYn_jSmn9Y2o0@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Pirates @ Yankees Pirates @ Yankees

Follow on MiLB First Pitch  https //stza.co/+xCGP-2I

Shop  https //stza.co/+xCGP-3m

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Pirates @ Yankees
END:VALARM
DTSTART;VALUE=DATE:20180711
DTEND;VALUE=DATE:20180711
UID:GicUULZFWFyDYn_jSmn9Y2o0@stanza.co
SUMMARY:Pirates @ Yankees
DESCRIPTION:Pirates @ Yankees\n\nFollow on MiLB First Pitch: https://stza.co/+xCGP-2I\n\nShop: https://stza.co/+xCGP-3m\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144509Z
LAST-MODIFIED:20180213T144509Z
TRANSP:OPAQUE
END:VEVENT
* Pirates @ Yankees
<2018-07-12 Thu>--<2018-07-11 Wed>
:PROPERTIES:
:ID:       zRrIPlNnQAEtcAzthEpkZh7o@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Pirates @ Yankees Pirates @ Yankees

Follow on MiLB First Pitch  https //stza.co/+xCGQ-1m

Shop  https //stza.co/+xCGQ-2L

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Pirates @ Yankees
END:VALARM
DTSTART;VALUE=DATE:20180712
DTEND;VALUE=DATE:20180712
UID:zRrIPlNnQAEtcAzthEpkZh7o@stanza.co
SUMMARY:Pirates @ Yankees
DESCRIPTION:Pirates @ Yankees\n\nFollow on MiLB First Pitch: https://stza.co/+xCGQ-1m\n\nShop: https://stza.co/+xCGQ-2L\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144509Z
LAST-MODIFIED:20180213T144509Z
TRANSP:OPAQUE
END:VEVENT
* Pirates @ Yankees
<2018-07-13 Fri>--<2018-07-12 Thu>
:PROPERTIES:
:ID:       LqIyX3uIIuEu8j-yTyxIT6D_@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Pirates @ Yankees Pirates @ Yankees

Follow on MiLB First Pitch  https //stza.co/+xCGR-1V

Shop  https //stza.co/+xCGR-39

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Pirates @ Yankees
END:VALARM
DTSTART;VALUE=DATE:20180713
DTEND;VALUE=DATE:20180713
UID:LqIyX3uIIuEu8j-yTyxIT6D_@stanza.co
SUMMARY:Pirates @ Yankees
DESCRIPTION:Pirates @ Yankees\n\nFollow on MiLB First Pitch: https://stza.co/+xCGR-1V\n\nShop: https://stza.co/+xCGR-39\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144509Z
LAST-MODIFIED:20180213T144509Z
TRANSP:OPAQUE
END:VEVENT
* Pirates @ Astros
<2018-07-14 Sat>--<2018-07-13 Fri>
:PROPERTIES:
:ID:       nZWmEdrxyz4HUnek7Xd0T4aD@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Pirates @ Astros Pirates @ Astros

Follow on MiLB First Pitch  https //stza.co/+xCGS-2Y

Shop  https //stza.co/+xCGS-2O

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Pirates @ Astros
END:VALARM
DTSTART;VALUE=DATE:20180714
DTEND;VALUE=DATE:20180714
UID:nZWmEdrxyz4HUnek7Xd0T4aD@stanza.co
SUMMARY:Pirates @ Astros
DESCRIPTION:Pirates @ Astros\n\nFollow on MiLB First Pitch: https://stza.co/+xCGS-2Y\n\nShop: https://stza.co/+xCGS-2O\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144509Z
LAST-MODIFIED:20180213T144509Z
TRANSP:OPAQUE
END:VEVENT
* Pirates @ Astros
<2018-07-15 Sun>--<2018-07-14 Sat>
:PROPERTIES:
:ID:       x7Q37KxPN9cT9Tcjp89qPtQN@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Pirates @ Astros Pirates @ Astros

Follow on MiLB First Pitch  https //stza.co/+xCGT-3u

Shop  https //stza.co/+xCGT-$

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Pirates @ Astros
END:VALARM
DTSTART;VALUE=DATE:20180715
DTEND;VALUE=DATE:20180715
UID:x7Q37KxPN9cT9Tcjp89qPtQN@stanza.co
SUMMARY:Pirates @ Astros
DESCRIPTION:Pirates @ Astros\n\nFollow on MiLB First Pitch: https://stza.co/+xCGT-3u\n\nShop: https://stza.co/+xCGT-$\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144509Z
LAST-MODIFIED:20180213T144509Z
TRANSP:OPAQUE
END:VEVENT
* Pirates @ Astros
<2018-07-16 Mon>--<2018-07-15 Sun>
:PROPERTIES:
:ID:       wIYkxNGTkHFNLPzJl51SD17a@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Pirates @ Astros Pirates @ Astros

Follow on MiLB First Pitch  https //stza.co/+xCGU-3p

Shop  https //stza.co/+xCGU-2B

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Pirates @ Astros
END:VALARM
DTSTART;VALUE=DATE:20180716
DTEND;VALUE=DATE:20180716
UID:wIYkxNGTkHFNLPzJl51SD17a@stanza.co
SUMMARY:Pirates @ Astros
DESCRIPTION:Pirates @ Astros\n\nFollow on MiLB First Pitch: https://stza.co/+xCGU-3p\n\nShop: https://stza.co/+xCGU-2B\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144509Z
LAST-MODIFIED:20180213T144509Z
TRANSP:OPAQUE
END:VEVENT
* Pirates vs. Royals
<2018-07-18 Wed>--<2018-07-17 Tue>
:PROPERTIES:
:ID:       CZ-fReEefG3lwXK6TMEXx7M4@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Pirates vs. Royals Pirates vs. Royals

Follow on MiLB First Pitch  https //stza.co/+xCGV-36

Shop  https //stza.co/+xCGV-2f

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Pirates vs. Royals
END:VALARM
DTSTART;VALUE=DATE:20180718
DTEND;VALUE=DATE:20180718
UID:CZ-fReEefG3lwXK6TMEXx7M4@stanza.co
SUMMARY:Pirates vs. Royals
DESCRIPTION:Pirates vs. Royals\n\nFollow on MiLB First Pitch: https://stza.co/+xCGV-36\n\nShop: https://stza.co/+xCGV-2f\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144509Z
LAST-MODIFIED:20180213T144509Z
TRANSP:OPAQUE
END:VEVENT
* Pirates vs. Royals
<2018-07-19 Thu>--<2018-07-18 Wed>
:PROPERTIES:
:ID:       IHcwdGBWIv5EMDOoxYQMFUM7@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Pirates vs. Royals Pirates vs. Royals

Follow on MiLB First Pitch  https //stza.co/+xCGX-2c

Shop  https //stza.co/+xCGX-i

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Pirates vs. Royals
END:VALARM
DTSTART;VALUE=DATE:20180719
DTEND;VALUE=DATE:20180719
UID:IHcwdGBWIv5EMDOoxYQMFUM7@stanza.co
SUMMARY:Pirates vs. Royals
DESCRIPTION:Pirates vs. Royals\n\nFollow on MiLB First Pitch: https://stza.co/+xCGX-2c\n\nShop: https://stza.co/+xCGX-i\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144509Z
LAST-MODIFIED:20180213T144509Z
TRANSP:OPAQUE
END:VEVENT
* Pirates vs. Royals
<2018-07-20 Fri>--<2018-07-19 Thu>
:PROPERTIES:
:ID:       Zbu5Cueqj2yUXZm3i9FUK5-n@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Pirates vs. Royals Pirates vs. Royals

Follow on MiLB First Pitch  https //stza.co/+xCG_-1F

Shop  https //stza.co/+xCG_-24

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Pirates vs. Royals
END:VALARM
DTSTART;VALUE=DATE:20180720
DTEND;VALUE=DATE:20180720
UID:Zbu5Cueqj2yUXZm3i9FUK5-n@stanza.co
SUMMARY:Pirates vs. Royals
DESCRIPTION:Pirates vs. Royals\n\nFollow on MiLB First Pitch: https://stza.co/+xCG_-1F\n\nShop: https://stza.co/+xCG_-24\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144509Z
LAST-MODIFIED:20180213T144509Z
TRANSP:OPAQUE
END:VEVENT
* Pirates vs. Mets
<2018-07-21 Sat>--<2018-07-20 Fri>
:PROPERTIES:
:ID:       cakLWOP0oifmCPXqmgTizlKV@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Pirates vs. Mets Pirates vs. Mets

Follow on MiLB First Pitch  https //stza.co/+xCH0-1p

Shop  https //stza.co/+xCH0-1j

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Pirates vs. Mets
END:VALARM
DTSTART;VALUE=DATE:20180721
DTEND;VALUE=DATE:20180721
UID:cakLWOP0oifmCPXqmgTizlKV@stanza.co
SUMMARY:Pirates vs. Mets
DESCRIPTION:Pirates vs. Mets\n\nFollow on MiLB First Pitch: https://stza.co/+xCH0-1p\n\nShop: https://stza.co/+xCH0-1j\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144509Z
LAST-MODIFIED:20180213T144509Z
TRANSP:OPAQUE
END:VEVENT
* Pirates vs. Mets
<2018-07-22 Sun>--<2018-07-21 Sat>
:PROPERTIES:
:ID:       GstczG6Zq2qgB-NUKmwTGLgF@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Pirates vs. Mets Pirates vs. Mets

Follow on MiLB First Pitch  https //stza.co/+xCH2-1N

Shop  https //stza.co/+xCH2-3

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Pirates vs. Mets
END:VALARM
DTSTART;VALUE=DATE:20180722
DTEND;VALUE=DATE:20180722
UID:GstczG6Zq2qgB-NUKmwTGLgF@stanza.co
SUMMARY:Pirates vs. Mets
DESCRIPTION:Pirates vs. Mets\n\nFollow on MiLB First Pitch: https://stza.co/+xCH2-1N\n\nShop: https://stza.co/+xCH2-3\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144509Z
LAST-MODIFIED:20180213T144509Z
TRANSP:OPAQUE
END:VEVENT
* Pirates vs. Mets
<2018-07-23 Mon>--<2018-07-22 Sun>
:PROPERTIES:
:ID:       2idaOLl9BV-pE4LZZ-MSzifE@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Pirates vs. Mets Pirates vs. Mets

Follow on MiLB First Pitch  https //stza.co/+xCH4-Q

Shop  https //stza.co/+xCH4-9

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Pirates vs. Mets
END:VALARM
DTSTART;VALUE=DATE:20180723
DTEND;VALUE=DATE:20180723
UID:2idaOLl9BV-pE4LZZ-MSzifE@stanza.co
SUMMARY:Pirates vs. Mets
DESCRIPTION:Pirates vs. Mets\n\nFollow on MiLB First Pitch: https://stza.co/+xCH4-Q\n\nShop: https://stza.co/+xCH4-9\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144509Z
LAST-MODIFIED:20180213T144509Z
TRANSP:OPAQUE
END:VEVENT
* Pirates @ Blue Jays
<2018-07-24 Tue>--<2018-07-23 Mon>
:PROPERTIES:
:ID:       nwH72-9poFo0FjtP7R_X2isC@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Pirates @ Blue Jays Pirates @ Blue Jays

Follow on MiLB First Pitch  https //stza.co/+xCH6-2U

Shop  https //stza.co/+xCH6-2Y

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Pirates @ Blue Jays
END:VALARM
DTSTART;VALUE=DATE:20180724
DTEND;VALUE=DATE:20180724
UID:nwH72-9poFo0FjtP7R_X2isC@stanza.co
SUMMARY:Pirates @ Blue Jays
DESCRIPTION:Pirates @ Blue Jays\n\nFollow on MiLB First Pitch: https://stza.co/+xCH6-2U\n\nShop: https://stza.co/+xCH6-2Y\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144509Z
LAST-MODIFIED:20180213T144509Z
TRANSP:OPAQUE
END:VEVENT
* Pirates @ Blue Jays
<2018-07-25 Wed>--<2018-07-24 Tue>
:PROPERTIES:
:ID:       8WTkZVnk17BaABouMmJns3Mm@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Pirates @ Blue Jays Pirates @ Blue Jays

Follow on MiLB First Pitch  https //stza.co/+xCH7-2X

Shop  https //stza.co/+xCH7-3r

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Pirates @ Blue Jays
END:VALARM
DTSTART;VALUE=DATE:20180725
DTEND;VALUE=DATE:20180725
UID:8WTkZVnk17BaABouMmJns3Mm@stanza.co
SUMMARY:Pirates @ Blue Jays
DESCRIPTION:Pirates @ Blue Jays\n\nFollow on MiLB First Pitch: https://stza.co/+xCH7-2X\n\nShop: https://stza.co/+xCH7-3r\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144509Z
LAST-MODIFIED:20180213T144509Z
TRANSP:OPAQUE
END:VEVENT
* Pirates @ Blue Jays
<2018-07-26 Thu>--<2018-07-25 Wed>
:PROPERTIES:
:ID:       4HhnU_V4RIxz1SiceTeML2Gy@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Pirates @ Blue Jays Pirates @ Blue Jays

Follow on MiLB First Pitch  https //stza.co/+xCH9-_

Shop  https //stza.co/+xCH9-3j

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Pirates @ Blue Jays
END:VALARM
DTSTART;VALUE=DATE:20180726
DTEND;VALUE=DATE:20180726
UID:4HhnU_V4RIxz1SiceTeML2Gy@stanza.co
SUMMARY:Pirates @ Blue Jays
DESCRIPTION:Pirates @ Blue Jays\n\nFollow on MiLB First Pitch: https://stza.co/+xCH9-_\n\nShop: https://stza.co/+xCH9-3j\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144509Z
LAST-MODIFIED:20180213T144509Z
TRANSP:OPAQUE
END:VEVENT
* Pirates @ Twins
<2018-07-27 Fri>--<2018-07-26 Thu>
:PROPERTIES:
:ID:       veWe6-qAFQ3tW6Do_KInT85r@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Pirates @ Twins Pirates @ Twins

Follow on MiLB First Pitch  https //stza.co/+xCHa-2F

Shop  https //stza.co/+xCHa-J

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Pirates @ Twins
END:VALARM
DTSTART;VALUE=DATE:20180727
DTEND;VALUE=DATE:20180727
UID:veWe6-qAFQ3tW6Do_KInT85r@stanza.co
SUMMARY:Pirates @ Twins
DESCRIPTION:Pirates @ Twins\n\nFollow on MiLB First Pitch: https://stza.co/+xCHa-2F\n\nShop: https://stza.co/+xCHa-J\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144509Z
LAST-MODIFIED:20180213T144509Z
TRANSP:OPAQUE
END:VEVENT
* Pirates @ Twins
<2018-07-28 Sat>--<2018-07-27 Fri>
:PROPERTIES:
:ID:       HbeMQMAPf47XUCYf2MXpvm_h@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Pirates @ Twins Pirates @ Twins

Follow on MiLB First Pitch  https //stza.co/+xCHb-1s

Shop  https //stza.co/+xCHb-20

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Pirates @ Twins
END:VALARM
DTSTART;VALUE=DATE:20180728
DTEND;VALUE=DATE:20180728
UID:HbeMQMAPf47XUCYf2MXpvm_h@stanza.co
SUMMARY:Pirates @ Twins
DESCRIPTION:Pirates @ Twins\n\nFollow on MiLB First Pitch: https://stza.co/+xCHb-1s\n\nShop: https://stza.co/+xCHb-20\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144509Z
LAST-MODIFIED:20180213T144509Z
TRANSP:OPAQUE
END:VEVENT
* Pirates @ Twins
<2018-07-29 Sun>--<2018-07-28 Sat>
:PROPERTIES:
:ID:       h7HRoQymWjmWjn6rz_qX-R4o@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Pirates @ Twins Pirates @ Twins

Follow on MiLB First Pitch  https //stza.co/+xCHc-20

Shop  https //stza.co/+xCHc-1_

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Pirates @ Twins
END:VALARM
DTSTART;VALUE=DATE:20180729
DTEND;VALUE=DATE:20180729
UID:h7HRoQymWjmWjn6rz_qX-R4o@stanza.co
SUMMARY:Pirates @ Twins
DESCRIPTION:Pirates @ Twins\n\nFollow on MiLB First Pitch: https://stza.co/+xCHc-20\n\nShop: https://stza.co/+xCHc-1_\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144509Z
LAST-MODIFIED:20180213T144509Z
TRANSP:OPAQUE
END:VEVENT
* Pirates vs. Blue Jays
<2018-07-31 Tue>--<2018-07-30 Mon>
:PROPERTIES:
:ID:       ENy-mDq23-zHSfX9geNx2ERR@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Pirates vs. Blue Jays Pirates vs. Blue Jays

Follow on MiLB First Pitch  https //stza.co/+xCHe-3g

Shop  https //stza.co/+xCHe-27

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Pirates vs. Blue Jays
END:VALARM
DTSTART;VALUE=DATE:20180731
DTEND;VALUE=DATE:20180731
UID:ENy-mDq23-zHSfX9geNx2ERR@stanza.co
SUMMARY:Pirates vs. Blue Jays
DESCRIPTION:Pirates vs. Blue Jays\n\nFollow on MiLB First Pitch: https://stza.co/+xCHe-3g\n\nShop: https://stza.co/+xCHe-27\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144509Z
LAST-MODIFIED:20180213T144509Z
TRANSP:OPAQUE
END:VEVENT
* Pirates vs. Blue Jays
<2018-08-01 Wed>--<2018-07-31 Tue>
:PROPERTIES:
:ID:       ADZzbzKv45ugSmJsuxlN891B@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Pirates vs. Blue Jays Pirates vs. Blue Jays

Follow on MiLB First Pitch  https //stza.co/+xCHf-2$

Shop  https //stza.co/+xCHf-1x

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Pirates vs. Blue Jays
END:VALARM
DTSTART;VALUE=DATE:20180801
DTEND;VALUE=DATE:20180801
UID:ADZzbzKv45ugSmJsuxlN891B@stanza.co
SUMMARY:Pirates vs. Blue Jays
DESCRIPTION:Pirates vs. Blue Jays\n\nFollow on MiLB First Pitch: https://stza.co/+xCHf-2$\n\nShop: https://stza.co/+xCHf-1x\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144509Z
LAST-MODIFIED:20180213T144509Z
TRANSP:OPAQUE
END:VEVENT
* Pirates vs. Blue Jays
<2018-08-02 Thu>--<2018-08-01 Wed>
:PROPERTIES:
:ID:       MBMhcaL2sC6dYWwS5nDjdzsN@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Pirates vs. Blue Jays Pirates vs. Blue Jays

Follow on MiLB First Pitch  https //stza.co/+xCHh-1O

Shop  https //stza.co/+xCHh-_

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Pirates vs. Blue Jays
END:VALARM
DTSTART;VALUE=DATE:20180802
DTEND;VALUE=DATE:20180802
UID:MBMhcaL2sC6dYWwS5nDjdzsN@stanza.co
SUMMARY:Pirates vs. Blue Jays
DESCRIPTION:Pirates vs. Blue Jays\n\nFollow on MiLB First Pitch: https://stza.co/+xCHh-1O\n\nShop: https://stza.co/+xCHh-_\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144509Z
LAST-MODIFIED:20180213T144509Z
TRANSP:OPAQUE
END:VEVENT
* Pirates @ Mets
<2018-08-03 Fri>--<2018-08-02 Thu>
:PROPERTIES:
:ID:       xG_GCcIWvHYqI-AjJw-K4vxY@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Pirates @ Mets Pirates @ Mets

Follow on MiLB First Pitch  https //stza.co/+xCHk-1X

Shop  https //stza.co/+xCHk-2S

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Pirates @ Mets
END:VALARM
DTSTART;VALUE=DATE:20180803
DTEND;VALUE=DATE:20180803
UID:xG_GCcIWvHYqI-AjJw-K4vxY@stanza.co
SUMMARY:Pirates @ Mets
DESCRIPTION:Pirates @ Mets\n\nFollow on MiLB First Pitch: https://stza.co/+xCHk-1X\n\nShop: https://stza.co/+xCHk-2S\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144509Z
LAST-MODIFIED:20180213T144509Z
TRANSP:OPAQUE
END:VEVENT
* Pirates @ Mets
<2018-08-04 Sat>--<2018-08-03 Fri>
:PROPERTIES:
:ID:       EQWl5TcfRvKYHVDyLqG1Gy1B@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Pirates @ Mets Pirates @ Mets

Follow on MiLB First Pitch  https //stza.co/+xCHl-1F

Shop  https //stza.co/+xCHl-3m

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Pirates @ Mets
END:VALARM
DTSTART;VALUE=DATE:20180804
DTEND;VALUE=DATE:20180804
UID:EQWl5TcfRvKYHVDyLqG1Gy1B@stanza.co
SUMMARY:Pirates @ Mets
DESCRIPTION:Pirates @ Mets\n\nFollow on MiLB First Pitch: https://stza.co/+xCHl-1F\n\nShop: https://stza.co/+xCHl-3m\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144509Z
LAST-MODIFIED:20180213T144509Z
TRANSP:OPAQUE
END:VEVENT
* Pirates @ Mets
<2018-08-05 Sun>--<2018-08-04 Sat>
:PROPERTIES:
:ID:       5NG_qKzLarNRMEeFfEqELARK@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Pirates @ Mets Pirates @ Mets

Follow on MiLB First Pitch  https //stza.co/+xCHm-2d

Shop  https //stza.co/+xCHm-2L

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Pirates @ Mets
END:VALARM
DTSTART;VALUE=DATE:20180805
DTEND;VALUE=DATE:20180805
UID:5NG_qKzLarNRMEeFfEqELARK@stanza.co
SUMMARY:Pirates @ Mets
DESCRIPTION:Pirates @ Mets\n\nFollow on MiLB First Pitch: https://stza.co/+xCHm-2d\n\nShop: https://stza.co/+xCHm-2L\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144509Z
LAST-MODIFIED:20180213T144509Z
TRANSP:OPAQUE
END:VEVENT
* Pirates vs. Cardinals
<2018-08-06 Mon>--<2018-08-05 Sun>
:PROPERTIES:
:ID:       ZASnfQivFLLhkKG9xnQ-quwn@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Pirates vs. Cardinals Pirates vs. Cardinals

Follow on MiLB First Pitch  https //stza.co/+xCHo-34

Shop  https //stza.co/+xCHo-7

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Pirates vs. Cardinals
END:VALARM
DTSTART;VALUE=DATE:20180806
DTEND;VALUE=DATE:20180806
UID:ZASnfQivFLLhkKG9xnQ-quwn@stanza.co
SUMMARY:Pirates vs. Cardinals
DESCRIPTION:Pirates vs. Cardinals\n\nFollow on MiLB First Pitch: https://stza.co/+xCHo-34\n\nShop: https://stza.co/+xCHo-7\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144509Z
LAST-MODIFIED:20180213T144509Z
TRANSP:OPAQUE
END:VEVENT
* Pirates vs. Cardinals
<2018-08-07 Tue>--<2018-08-06 Mon>
:PROPERTIES:
:ID:       XaZUjfRGwchbVaxfG1fzEffi@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Pirates vs. Cardinals Pirates vs. Cardinals

Follow on MiLB First Pitch  https //stza.co/+xCHq-2k

Shop  https //stza.co/+xCHq-4

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Pirates vs. Cardinals
END:VALARM
DTSTART;VALUE=DATE:20180807
DTEND;VALUE=DATE:20180807
UID:XaZUjfRGwchbVaxfG1fzEffi@stanza.co
SUMMARY:Pirates vs. Cardinals
DESCRIPTION:Pirates vs. Cardinals\n\nFollow on MiLB First Pitch: https://stza.co/+xCHq-2k\n\nShop: https://stza.co/+xCHq-4\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144509Z
LAST-MODIFIED:20180213T144509Z
TRANSP:OPAQUE
END:VEVENT
* Pirates vs. Cardinals
<2018-08-08 Wed>--<2018-08-07 Tue>
:PROPERTIES:
:ID:       GaoQE3CY5C--Fh0yKeTjJNJV@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Pirates vs. Cardinals Pirates vs. Cardinals

Follow on MiLB First Pitch  https //stza.co/+xCHs-3y

Shop  https //stza.co/+xCHs-1m

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Pirates vs. Cardinals
END:VALARM
DTSTART;VALUE=DATE:20180808
DTEND;VALUE=DATE:20180808
UID:GaoQE3CY5C--Fh0yKeTjJNJV@stanza.co
SUMMARY:Pirates vs. Cardinals
DESCRIPTION:Pirates vs. Cardinals\n\nFollow on MiLB First Pitch: https://stza.co/+xCHs-3y\n\nShop: https://stza.co/+xCHs-1m\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144509Z
LAST-MODIFIED:20180213T144509Z
TRANSP:OPAQUE
END:VEVENT
* Pirates vs. Astros
<2018-08-09 Thu>--<2018-08-08 Wed>
:PROPERTIES:
:ID:       YGKVlxLWpCDgUITKrLs9icDX@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Pirates vs. Astros Pirates vs. Astros

Follow on MiLB First Pitch  https //stza.co/+xCHu-2u

Shop  https //stza.co/+xCHu-r

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Pirates vs. Astros
END:VALARM
DTSTART;VALUE=DATE:20180809
DTEND;VALUE=DATE:20180809
UID:YGKVlxLWpCDgUITKrLs9icDX@stanza.co
SUMMARY:Pirates vs. Astros
DESCRIPTION:Pirates vs. Astros\n\nFollow on MiLB First Pitch: https://stza.co/+xCHu-2u\n\nShop: https://stza.co/+xCHu-r\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144509Z
LAST-MODIFIED:20180213T144509Z
TRANSP:OPAQUE
END:VEVENT
* Pirates vs. Astros
<2018-08-10 Fri>--<2018-08-09 Thu>
:PROPERTIES:
:ID:       -FtHfy_Eszlb-Ox3fUb4cFGN@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Pirates vs. Astros Pirates vs. Astros

Follow on MiLB First Pitch  https //stza.co/+xCHv-1c

Shop  https //stza.co/+xCHv-37

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Pirates vs. Astros
END:VALARM
DTSTART;VALUE=DATE:20180810
DTEND;VALUE=DATE:20180810
UID:-FtHfy_Eszlb-Ox3fUb4cFGN@stanza.co
SUMMARY:Pirates vs. Astros
DESCRIPTION:Pirates vs. Astros\n\nFollow on MiLB First Pitch: https://stza.co/+xCHv-1c\n\nShop: https://stza.co/+xCHv-37\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144509Z
LAST-MODIFIED:20180213T144509Z
TRANSP:OPAQUE
END:VEVENT
* Pirates vs. Astros
<2018-08-11 Sat>--<2018-08-10 Fri>
:PROPERTIES:
:ID:       knuhWpP8wZiZ-1Tqkmc4WPoN@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Pirates vs. Astros Pirates vs. Astros

Follow on MiLB First Pitch  https //stza.co/+xCHy-2d

Shop  https //stza.co/+xCHy-29

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Pirates vs. Astros
END:VALARM
DTSTART;VALUE=DATE:20180811
DTEND;VALUE=DATE:20180811
UID:knuhWpP8wZiZ-1Tqkmc4WPoN@stanza.co
SUMMARY:Pirates vs. Astros
DESCRIPTION:Pirates vs. Astros\n\nFollow on MiLB First Pitch: https://stza.co/+xCHy-2d\n\nShop: https://stza.co/+xCHy-29\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144509Z
LAST-MODIFIED:20180213T144509Z
TRANSP:OPAQUE
END:VEVENT
* Pirates @ Cardinals
<2018-08-12 Sun>--<2018-08-11 Sat>
:PROPERTIES:
:ID:       a4hxXb3_CN3fQjGkfvL_6x79@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Pirates @ Cardinals Pirates @ Cardinals

Follow on MiLB First Pitch  https //stza.co/+xCHz-2D

Shop  https //stza.co/+xCHz-2v

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Pirates @ Cardinals
END:VALARM
DTSTART;VALUE=DATE:20180812
DTEND;VALUE=DATE:20180812
UID:a4hxXb3_CN3fQjGkfvL_6x79@stanza.co
SUMMARY:Pirates @ Cardinals
DESCRIPTION:Pirates @ Cardinals\n\nFollow on MiLB First Pitch: https://stza.co/+xCHz-2D\n\nShop: https://stza.co/+xCHz-2v\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144509Z
LAST-MODIFIED:20180213T144509Z
TRANSP:OPAQUE
END:VEVENT
* Pirates @ Cardinals
<2018-08-13 Mon>--<2018-08-12 Sun>
:PROPERTIES:
:ID:       s9lJ3LQ9y9GOMJ_TyBDo-vMZ@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Pirates @ Cardinals Pirates @ Cardinals

Follow on MiLB First Pitch  https //stza.co/+xCHA-2d

Shop  https //stza.co/+xCHA-O

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Pirates @ Cardinals
END:VALARM
DTSTART;VALUE=DATE:20180813
DTEND;VALUE=DATE:20180813
UID:s9lJ3LQ9y9GOMJ_TyBDo-vMZ@stanza.co
SUMMARY:Pirates @ Cardinals
DESCRIPTION:Pirates @ Cardinals\n\nFollow on MiLB First Pitch: https://stza.co/+xCHA-2d\n\nShop: https://stza.co/+xCHA-O\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144509Z
LAST-MODIFIED:20180213T144509Z
TRANSP:OPAQUE
END:VEVENT
* Pirates @ Cardinals
<2018-08-14 Tue>--<2018-08-13 Mon>
:PROPERTIES:
:ID:       -fGyYaHg5KuX9lxlfJJvhXPe@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Pirates @ Cardinals Pirates @ Cardinals

Follow on MiLB First Pitch  https //stza.co/+xCHB-26

Shop  https //stza.co/+xCHB-22

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Pirates @ Cardinals
END:VALARM
DTSTART;VALUE=DATE:20180814
DTEND;VALUE=DATE:20180814
UID:-fGyYaHg5KuX9lxlfJJvhXPe@stanza.co
SUMMARY:Pirates @ Cardinals
DESCRIPTION:Pirates @ Cardinals\n\nFollow on MiLB First Pitch: https://stza.co/+xCHB-26\n\nShop: https://stza.co/+xCHB-22\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144509Z
LAST-MODIFIED:20180213T144509Z
TRANSP:OPAQUE
END:VEVENT
* Pirates @ Royals
<2018-08-16 Thu>--<2018-08-15 Wed>
:PROPERTIES:
:ID:       XyWohzjHtYAmglI-1QSAN1D0@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Pirates @ Royals Pirates @ Royals

Follow on MiLB First Pitch  https //stza.co/+xCHC-Y

Shop  https //stza.co/+xCHC-W

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Pirates @ Royals
END:VALARM
DTSTART;VALUE=DATE:20180816
DTEND;VALUE=DATE:20180816
UID:XyWohzjHtYAmglI-1QSAN1D0@stanza.co
SUMMARY:Pirates @ Royals
DESCRIPTION:Pirates @ Royals\n\nFollow on MiLB First Pitch: https://stza.co/+xCHC-Y\n\nShop: https://stza.co/+xCHC-W\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144509Z
LAST-MODIFIED:20180213T144509Z
TRANSP:OPAQUE
END:VEVENT
* Pirates @ Royals
<2018-08-17 Fri>--<2018-08-16 Thu>
:PROPERTIES:
:ID:       7RwEyoC_VzvTWt64WPFRz3io@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Pirates @ Royals Pirates @ Royals

Follow on MiLB First Pitch  https //stza.co/+xCHD-k

Shop  https //stza.co/+xCHD-3P

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Pirates @ Royals
END:VALARM
DTSTART;VALUE=DATE:20180817
DTEND;VALUE=DATE:20180817
UID:7RwEyoC_VzvTWt64WPFRz3io@stanza.co
SUMMARY:Pirates @ Royals
DESCRIPTION:Pirates @ Royals\n\nFollow on MiLB First Pitch: https://stza.co/+xCHD-k\n\nShop: https://stza.co/+xCHD-3P\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144509Z
LAST-MODIFIED:20180213T144509Z
TRANSP:OPAQUE
END:VEVENT
* Pirates @ Royals
<2018-08-18 Sat>--<2018-08-17 Fri>
:PROPERTIES:
:ID:       rjweQkUreAB4od11YOYnbtj3@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Pirates @ Royals Pirates @ Royals

Follow on MiLB First Pitch  https //stza.co/+xCHE-1i

Shop  https //stza.co/+xCHE-3h

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Pirates @ Royals
END:VALARM
DTSTART;VALUE=DATE:20180818
DTEND;VALUE=DATE:20180818
UID:rjweQkUreAB4od11YOYnbtj3@stanza.co
SUMMARY:Pirates @ Royals
DESCRIPTION:Pirates @ Royals\n\nFollow on MiLB First Pitch: https://stza.co/+xCHE-1i\n\nShop: https://stza.co/+xCHE-3h\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144509Z
LAST-MODIFIED:20180213T144509Z
TRANSP:OPAQUE
END:VEVENT
* Pirates vs. Yankees
<2018-08-19 Sun>--<2018-08-18 Sat>
:PROPERTIES:
:ID:       96m-08u_Ves7BsQZny7HMK_C@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Pirates vs. Yankees Pirates vs. Yankees

Follow on MiLB First Pitch  https //stza.co/+xCHG-3n

Shop  https //stza.co/+xCHG-H

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Pirates vs. Yankees
END:VALARM
DTSTART;VALUE=DATE:20180819
DTEND;VALUE=DATE:20180819
UID:96m-08u_Ves7BsQZny7HMK_C@stanza.co
SUMMARY:Pirates vs. Yankees
DESCRIPTION:Pirates vs. Yankees\n\nFollow on MiLB First Pitch: https://stza.co/+xCHG-3n\n\nShop: https://stza.co/+xCHG-H\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144509Z
LAST-MODIFIED:20180213T144509Z
TRANSP:OPAQUE
END:VEVENT
* Pirates vs. Yankees
<2018-08-20 Mon>--<2018-08-19 Sun>
:PROPERTIES:
:ID:       rW3-v-AmGGae_0mrEwRSkz6o@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Pirates vs. Yankees Pirates vs. Yankees

Follow on MiLB First Pitch  https //stza.co/+xCHI-A

Shop  https //stza.co/+xCHI-2A

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Pirates vs. Yankees
END:VALARM
DTSTART;VALUE=DATE:20180820
DTEND;VALUE=DATE:20180820
UID:rW3-v-AmGGae_0mrEwRSkz6o@stanza.co
SUMMARY:Pirates vs. Yankees
DESCRIPTION:Pirates vs. Yankees\n\nFollow on MiLB First Pitch: https://stza.co/+xCHI-A\n\nShop: https://stza.co/+xCHI-2A\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144509Z
LAST-MODIFIED:20180213T144509Z
TRANSP:OPAQUE
END:VEVENT
* Pirates @ Mets
<2018-08-21 Tue>--<2018-08-20 Mon>
:PROPERTIES:
:ID:       4zSrxiSWayXL-uhhLynHTiZU@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Pirates @ Mets Pirates @ Mets

Follow on MiLB First Pitch  https //stza.co/+xCHJ-3K

Shop  https //stza.co/+xCHJ-3I

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Pirates @ Mets
END:VALARM
DTSTART;VALUE=DATE:20180821
DTEND;VALUE=DATE:20180821
UID:4zSrxiSWayXL-uhhLynHTiZU@stanza.co
SUMMARY:Pirates @ Mets
DESCRIPTION:Pirates @ Mets\n\nFollow on MiLB First Pitch: https://stza.co/+xCHJ-3K\n\nShop: https://stza.co/+xCHJ-3I\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144509Z
LAST-MODIFIED:20180213T144509Z
TRANSP:OPAQUE
END:VEVENT
* Pirates @ Mets
<2018-08-22 Wed>--<2018-08-21 Tue>
:PROPERTIES:
:ID:       zQKngShifQS0g3IqxUeUj3EA@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Pirates @ Mets Pirates @ Mets

Follow on MiLB First Pitch  https //stza.co/+xCHK-1r

Shop  https //stza.co/+xCHK-$

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Pirates @ Mets
END:VALARM
DTSTART;VALUE=DATE:20180822
DTEND;VALUE=DATE:20180822
UID:zQKngShifQS0g3IqxUeUj3EA@stanza.co
SUMMARY:Pirates @ Mets
DESCRIPTION:Pirates @ Mets\n\nFollow on MiLB First Pitch: https://stza.co/+xCHK-1r\n\nShop: https://stza.co/+xCHK-$\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144509Z
LAST-MODIFIED:20180213T144509Z
TRANSP:OPAQUE
END:VEVENT
* Pirates @ Mets
<2018-08-23 Thu>--<2018-08-22 Wed>
:PROPERTIES:
:ID:       HmzlXc5lCQ9_S_vh4LmiOe9Z@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Pirates @ Mets Pirates @ Mets

Follow on MiLB First Pitch  https //stza.co/+xCHL-1H

Shop  https //stza.co/+xCHL-1Y

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Pirates @ Mets
END:VALARM
DTSTART;VALUE=DATE:20180823
DTEND;VALUE=DATE:20180823
UID:HmzlXc5lCQ9_S_vh4LmiOe9Z@stanza.co
SUMMARY:Pirates @ Mets
DESCRIPTION:Pirates @ Mets\n\nFollow on MiLB First Pitch: https://stza.co/+xCHL-1H\n\nShop: https://stza.co/+xCHL-1Y\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144509Z
LAST-MODIFIED:20180213T144509Z
TRANSP:OPAQUE
END:VEVENT
* Pirates vs. Twins
<2018-08-24 Fri>--<2018-08-23 Thu>
:PROPERTIES:
:ID:       XXopB5kaS7Nd_wnCffgKvU-5@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Pirates vs. Twins Pirates vs. Twins

Follow on MiLB First Pitch  https //stza.co/+xCHM-2m

Shop  https //stza.co/+xCHM-3e

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Pirates vs. Twins
END:VALARM
DTSTART;VALUE=DATE:20180824
DTEND;VALUE=DATE:20180824
UID:XXopB5kaS7Nd_wnCffgKvU-5@stanza.co
SUMMARY:Pirates vs. Twins
DESCRIPTION:Pirates vs. Twins\n\nFollow on MiLB First Pitch: https://stza.co/+xCHM-2m\n\nShop: https://stza.co/+xCHM-3e\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144509Z
LAST-MODIFIED:20180213T144509Z
TRANSP:OPAQUE
END:VEVENT
* Pirates vs. Twins
<2018-08-25 Sat>--<2018-08-24 Fri>
:PROPERTIES:
:ID:       nXUREdEtPAfkBBjE5hPLE9Os@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Pirates vs. Twins Pirates vs. Twins

Follow on MiLB First Pitch  https //stza.co/+xCHO-2f

Shop  https //stza.co/+xCHO-x

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Pirates vs. Twins
END:VALARM
DTSTART;VALUE=DATE:20180825
DTEND;VALUE=DATE:20180825
UID:nXUREdEtPAfkBBjE5hPLE9Os@stanza.co
SUMMARY:Pirates vs. Twins
DESCRIPTION:Pirates vs. Twins\n\nFollow on MiLB First Pitch: https://stza.co/+xCHO-2f\n\nShop: https://stza.co/+xCHO-x\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144509Z
LAST-MODIFIED:20180213T144509Z
TRANSP:OPAQUE
END:VEVENT
* Pirates vs. Twins
<2018-08-26 Sun>--<2018-08-25 Sat>
:PROPERTIES:
:ID:       SxdjlPeIN3-d_2wLzgWcB-bG@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Pirates vs. Twins Pirates vs. Twins

Follow on MiLB First Pitch  https //stza.co/+xCHQ-3m

Shop  https //stza.co/+xCHQ-7

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Pirates vs. Twins
END:VALARM
DTSTART;VALUE=DATE:20180826
DTEND;VALUE=DATE:20180826
UID:SxdjlPeIN3-d_2wLzgWcB-bG@stanza.co
SUMMARY:Pirates vs. Twins
DESCRIPTION:Pirates vs. Twins\n\nFollow on MiLB First Pitch: https://stza.co/+xCHQ-3m\n\nShop: https://stza.co/+xCHQ-7\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144509Z
LAST-MODIFIED:20180213T144509Z
TRANSP:OPAQUE
END:VEVENT
* Pirates vs. Braves
<2018-08-27 Mon>--<2018-08-26 Sun>
:PROPERTIES:
:ID:       5e_lMA2fTGAJTIcO4G0jzyY_@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Pirates vs. Braves Pirates vs. Braves

Follow on MiLB First Pitch  https //stza.co/+xCHS-3W

Shop  https //stza.co/+xCHS-

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Pirates vs. Braves
END:VALARM
DTSTART;VALUE=DATE:20180827
DTEND;VALUE=DATE:20180827
UID:5e_lMA2fTGAJTIcO4G0jzyY_@stanza.co
SUMMARY:Pirates vs. Braves
DESCRIPTION:Pirates vs. Braves\n\nFollow on MiLB First Pitch: https://stza.co/+xCHS-3W\n\nShop: https://stza.co/+xCHS-\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144509Z
LAST-MODIFIED:20180213T144509Z
TRANSP:OPAQUE
END:VEVENT
* Pirates vs. Braves
<2018-08-28 Tue>--<2018-08-27 Mon>
:PROPERTIES:
:ID:       hr17VLqFZF0YvsXpDiW9P032@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Pirates vs. Braves Pirates vs. Braves

Follow on MiLB First Pitch  https //stza.co/+xCHV-T

Shop  https //stza.co/+xCHV-2t

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Pirates vs. Braves
END:VALARM
DTSTART;VALUE=DATE:20180828
DTEND;VALUE=DATE:20180828
UID:hr17VLqFZF0YvsXpDiW9P032@stanza.co
SUMMARY:Pirates vs. Braves
DESCRIPTION:Pirates vs. Braves\n\nFollow on MiLB First Pitch: https://stza.co/+xCHV-T\n\nShop: https://stza.co/+xCHV-2t\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144509Z
LAST-MODIFIED:20180213T144509Z
TRANSP:OPAQUE
END:VEVENT
* Pirates vs. Braves
<2018-08-29 Wed>--<2018-08-28 Tue>
:PROPERTIES:
:ID:       vj6kb_KnHqBFOkzytph860fq@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Pirates vs. Braves Pirates vs. Braves

Follow on MiLB First Pitch  https //stza.co/+xC6n-2J

Shop  https //stza.co/+xC6n-k

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Pirates vs. Braves
END:VALARM
DTSTART;VALUE=DATE:20180829
DTEND;VALUE=DATE:20180829
UID:vj6kb_KnHqBFOkzytph860fq@stanza.co
SUMMARY:Pirates vs. Braves
DESCRIPTION:Pirates vs. Braves\n\nFollow on MiLB First Pitch: https://stza.co/+xC6n-2J\n\nShop: https://stza.co/+xC6n-k\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144509Z
LAST-MODIFIED:20180213T144509Z
TRANSP:OPAQUE
END:VEVENT
