#+TITLE:       Main Google calendar entries
#+AUTHOR:      Eric S Fraga
#+EMAIL:       e.fraga@ucl.ac.uk
#+DESCRIPTION: converted using the ical2org awk script
#+CATEGORY:    google
#+STARTUP:     hidestars
#+STARTUP:     overview

* COMMENT original iCal preamble

* Snappers vs. Timber Rattlers
<2018-04-05 Thu 18:30-21:30>
:PROPERTIES:
:ID:       NthT8J3fh2vcnC5IK5Wbghgd@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Snappers vs. Timber Rattlers Snappers vs. Timber Rattlers

Follow on MiLB First Pitch  https //stza.co/+wSHS-8

Shop  https //stza.co/+wSHS-1R

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Snappers vs. Timber Rattlers
END:VALARM
DTSTART:20180405T233000Z
DTEND:20180406T023000Z
UID:NthT8J3fh2vcnC5IK5Wbghgd@stanza.co
SUMMARY:Snappers vs. Timber Rattlers
DESCRIPTION:Snappers vs. Timber Rattlers\n\nFollow on MiLB First Pitch: https://stza.co/+wSHS-8\n\nShop: https://stza.co/+wSHS-1R\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144504Z
LAST-MODIFIED:20180213T144504Z
TRANSP:OPAQUE
END:VEVENT
* Snappers vs. Timber Rattlers
<2018-04-06 Fri 18:30-21:30>
:PROPERTIES:
:ID:       3wUleFGQcR9lKR-2AwqSACcf@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Snappers vs. Timber Rattlers Snappers vs. Timber Rattlers

Follow on MiLB First Pitch  https //stza.co/+wSHU-2Y

Shop  https //stza.co/+wSHU-g

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Snappers vs. Timber Rattlers
END:VALARM
DTSTART:20180406T233000Z
DTEND:20180407T023000Z
UID:3wUleFGQcR9lKR-2AwqSACcf@stanza.co
SUMMARY:Snappers vs. Timber Rattlers
DESCRIPTION:Snappers vs. Timber Rattlers\n\nFollow on MiLB First Pitch: https://stza.co/+wSHU-2Y\n\nShop: https://stza.co/+wSHU-g\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144504Z
LAST-MODIFIED:20180213T144504Z
TRANSP:OPAQUE
END:VEVENT
* Snappers @ Timber Rattlers
<2018-04-07 Sat 16:05-19:05>
:PROPERTIES:
:ID:       XQ-0kibNlYu4zIopUchUOSjH@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Snappers @ Timber Rattlers Snappers @ Timber Rattlers

Follow on MiLB First Pitch  https //stza.co/+vMNu-1P

Shop  https //stza.co/+vMNu-3I

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Snappers @ Timber Rattlers
END:VALARM
DTSTART:20180407T210500Z
DTEND:20180408T000500Z
UID:XQ-0kibNlYu4zIopUchUOSjH@stanza.co
SUMMARY:Snappers @ Timber Rattlers
DESCRIPTION:Snappers @ Timber Rattlers\n\nFollow on MiLB First Pitch: https://stza.co/+vMNu-1P\n\nShop: https://stza.co/+vMNu-3I\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144504Z
LAST-MODIFIED:20180213T144504Z
TRANSP:OPAQUE
END:VEVENT
* Snappers @ Timber Rattlers
<2018-04-08 Sun 13:05-16:05>
:PROPERTIES:
:ID:       c4GdUAiRsmWUy0SsxBU6Pob5@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Snappers @ Timber Rattlers Snappers @ Timber Rattlers

Follow on MiLB First Pitch  https //stza.co/+vMNv-o

Shop  https //stza.co/+vMNv-K

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Snappers @ Timber Rattlers
END:VALARM
DTSTART:20180408T180500Z
DTEND:20180408T210500Z
UID:c4GdUAiRsmWUy0SsxBU6Pob5@stanza.co
SUMMARY:Snappers @ Timber Rattlers
DESCRIPTION:Snappers @ Timber Rattlers\n\nFollow on MiLB First Pitch: https://stza.co/+vMNv-o\n\nShop: https://stza.co/+vMNv-K\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144504Z
LAST-MODIFIED:20180213T144504Z
TRANSP:OPAQUE
END:VEVENT
* Snappers @ Bees
<2018-04-09 Mon 18:30-21:30>
:PROPERTIES:
:ID:       uCoKsJdNTIdgpVaM6lK9KfYI@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Snappers @ Bees Snappers @ Bees

Follow on MiLB First Pitch  https //stza.co/+xBia-1S

Shop  https //stza.co/+xBia-1i

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Snappers @ Bees
END:VALARM
DTSTART:20180409T233000Z
DTEND:20180410T023000Z
UID:uCoKsJdNTIdgpVaM6lK9KfYI@stanza.co
SUMMARY:Snappers @ Bees
DESCRIPTION:Snappers @ Bees\n\nFollow on MiLB First Pitch: https://stza.co/+xBia-1S\n\nShop: https://stza.co/+xBia-1i\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144504Z
LAST-MODIFIED:20180213T144504Z
TRANSP:OPAQUE
END:VEVENT
* Snappers @ Bees
<2018-04-10 Tue 18:30-21:30>
:PROPERTIES:
:ID:       IvYkNjWYTkjzkheHXNKMaHCW@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Snappers @ Bees Snappers @ Bees

Follow on MiLB First Pitch  https //stza.co/+xBik-3

Shop  https //stza.co/+xBik-2_

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Snappers @ Bees
END:VALARM
DTSTART:20180410T233000Z
DTEND:20180411T023000Z
UID:IvYkNjWYTkjzkheHXNKMaHCW@stanza.co
SUMMARY:Snappers @ Bees
DESCRIPTION:Snappers @ Bees\n\nFollow on MiLB First Pitch: https://stza.co/+xBik-3\n\nShop: https://stza.co/+xBik-2_\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144504Z
LAST-MODIFIED:20180213T144504Z
TRANSP:OPAQUE
END:VEVENT
* Snappers @ Bees
<2018-04-11 Wed 18:30-21:30>
:PROPERTIES:
:ID:       fZUUD_QG9QZZgoK7bEyQHrvW@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Snappers @ Bees Snappers @ Bees

Follow on MiLB First Pitch  https //stza.co/+xBim-P

Shop  https //stza.co/+xBim-3c

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Snappers @ Bees
END:VALARM
DTSTART:20180411T233000Z
DTEND:20180412T023000Z
UID:fZUUD_QG9QZZgoK7bEyQHrvW@stanza.co
SUMMARY:Snappers @ Bees
DESCRIPTION:Snappers @ Bees\n\nFollow on MiLB First Pitch: https://stza.co/+xBim-P\n\nShop: https://stza.co/+xBim-3c\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144504Z
LAST-MODIFIED:20180213T144504Z
TRANSP:OPAQUE
END:VEVENT
* Snappers @ Bees
<2018-04-12 Thu 11:30-14:30>
:PROPERTIES:
:ID:       F8RvGxCqRZahdmL_6KabYf4Q@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Snappers @ Bees Snappers @ Bees

Follow on MiLB First Pitch  https //stza.co/+xBin-1F

Shop  https //stza.co/+xBin-1w

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Snappers @ Bees
END:VALARM
DTSTART:20180412T163000Z
DTEND:20180412T193000Z
UID:F8RvGxCqRZahdmL_6KabYf4Q@stanza.co
SUMMARY:Snappers @ Bees
DESCRIPTION:Snappers @ Bees\n\nFollow on MiLB First Pitch: https://stza.co/+xBin-1F\n\nShop: https://stza.co/+xBin-1w\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144504Z
LAST-MODIFIED:20180213T144504Z
TRANSP:OPAQUE
END:VEVENT
* Snappers @ Cougars
<2018-04-13 Fri 18:30-21:30>
:PROPERTIES:
:ID:       95NHc-PFCDakWUfp5t-Dk2UX@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Snappers @ Cougars Snappers @ Cougars

Follow on MiLB First Pitch  https //stza.co/+xBix-3L

Shop  https //stza.co/+xBix-2w

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Snappers @ Cougars
END:VALARM
DTSTART:20180413T233000Z
DTEND:20180414T023000Z
UID:95NHc-PFCDakWUfp5t-Dk2UX@stanza.co
SUMMARY:Snappers @ Cougars
DESCRIPTION:Snappers @ Cougars\n\nFollow on MiLB First Pitch: https://stza.co/+xBix-3L\n\nShop: https://stza.co/+xBix-2w\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144504Z
LAST-MODIFIED:20180213T144504Z
TRANSP:OPAQUE
END:VEVENT
* Snappers @ Cougars
<2018-04-14 Sat 13:00-16:00>
:PROPERTIES:
:ID:       UEePS_-Kq8sxAph8W3mfxPqH@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Snappers @ Cougars Snappers @ Cougars

Follow on MiLB First Pitch  https //stza.co/+xBiA-21

Shop  https //stza.co/+xBiA-32

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Snappers @ Cougars
END:VALARM
DTSTART:20180414T180000Z
DTEND:20180414T210000Z
UID:UEePS_-Kq8sxAph8W3mfxPqH@stanza.co
SUMMARY:Snappers @ Cougars
DESCRIPTION:Snappers @ Cougars\n\nFollow on MiLB First Pitch: https://stza.co/+xBiA-21\n\nShop: https://stza.co/+xBiA-32\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144504Z
LAST-MODIFIED:20180213T144504Z
TRANSP:OPAQUE
END:VEVENT
* Snappers @ Cougars
<2018-04-15 Sun 13:00-16:00>
:PROPERTIES:
:ID:       d6d8n4HOKYQyuRmzlMfIgEik@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Snappers @ Cougars Snappers @ Cougars

Follow on MiLB First Pitch  https //stza.co/+xBiD-11

Shop  https //stza.co/+xBiD-3M

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Snappers @ Cougars
END:VALARM
DTSTART:20180415T180000Z
DTEND:20180415T210000Z
UID:d6d8n4HOKYQyuRmzlMfIgEik@stanza.co
SUMMARY:Snappers @ Cougars
DESCRIPTION:Snappers @ Cougars\n\nFollow on MiLB First Pitch: https://stza.co/+xBiD-11\n\nShop: https://stza.co/+xBiD-3M\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144504Z
LAST-MODIFIED:20180213T144504Z
TRANSP:OPAQUE
END:VEVENT
* Snappers vs. Kernels
<2018-04-17 Tue 18:30-21:30>
:PROPERTIES:
:ID:       PxqSjESUsXppjJHNkzlU1X6i@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Snappers vs. Kernels Snappers vs. Kernels

Follow on MiLB First Pitch  https //stza.co/+wSHX-2L

Shop  https //stza.co/+wSHX-1h

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Snappers vs. Kernels
END:VALARM
DTSTART:20180417T233000Z
DTEND:20180418T023000Z
UID:PxqSjESUsXppjJHNkzlU1X6i@stanza.co
SUMMARY:Snappers vs. Kernels
DESCRIPTION:Snappers vs. Kernels\n\nFollow on MiLB First Pitch: https://stza.co/+wSHX-2L\n\nShop: https://stza.co/+wSHX-1h\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144504Z
LAST-MODIFIED:20180213T144504Z
TRANSP:OPAQUE
END:VEVENT
* Snappers vs. Kernels
<2018-04-18 Wed 18:30-21:30>
:PROPERTIES:
:ID:       R8hlghe8qJ7fIPLXPkRu6BDi@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Snappers vs. Kernels Snappers vs. Kernels

Follow on MiLB First Pitch  https //stza.co/+wSH_-3D

Shop  https //stza.co/+wSH_-2O

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Snappers vs. Kernels
END:VALARM
DTSTART:20180418T233000Z
DTEND:20180419T023000Z
UID:R8hlghe8qJ7fIPLXPkRu6BDi@stanza.co
SUMMARY:Snappers vs. Kernels
DESCRIPTION:Snappers vs. Kernels\n\nFollow on MiLB First Pitch: https://stza.co/+wSH_-3D\n\nShop: https://stza.co/+wSH_-2O\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144504Z
LAST-MODIFIED:20180213T144504Z
TRANSP:OPAQUE
END:VEVENT
* Snappers vs. Kernels
<2018-04-19 Thu 18:30-21:30>
:PROPERTIES:
:ID:       u93Bp-kSu4u8NdTVRayk4XYd@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Snappers vs. Kernels Snappers vs. Kernels

Follow on MiLB First Pitch  https //stza.co/+wSH$-Z

Shop  https //stza.co/+wSH$-3i

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Snappers vs. Kernels
END:VALARM
DTSTART:20180419T233000Z
DTEND:20180420T023000Z
UID:u93Bp-kSu4u8NdTVRayk4XYd@stanza.co
SUMMARY:Snappers vs. Kernels
DESCRIPTION:Snappers vs. Kernels\n\nFollow on MiLB First Pitch: https://stza.co/+wSH$-Z\n\nShop: https://stza.co/+wSH$-3i\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144504Z
LAST-MODIFIED:20180213T144504Z
TRANSP:OPAQUE
END:VEVENT
* Snappers @ LumberKings
<2018-04-20 Fri 18:30-21:30>
:PROPERTIES:
:ID:       QgqdNKkTXSO2-b_vtbwfdb2t@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Snappers @ LumberKings Snappers @ LumberKings

Follow on MiLB First Pitch  https //stza.co/+vMMS-2J

Shop  https //stza.co/+vMMS-3n

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Snappers @ LumberKings
END:VALARM
DTSTART:20180420T233000Z
DTEND:20180421T023000Z
UID:QgqdNKkTXSO2-b_vtbwfdb2t@stanza.co
SUMMARY:Snappers @ LumberKings
DESCRIPTION:Snappers @ LumberKings\n\nFollow on MiLB First Pitch: https://stza.co/+vMMS-2J\n\nShop: https://stza.co/+vMMS-3n\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144504Z
LAST-MODIFIED:20180213T144504Z
TRANSP:OPAQUE
END:VEVENT
* Snappers @ LumberKings
<2018-04-21 Sat 18:30-21:30>
:PROPERTIES:
:ID:       _bny97U1y_rSE_RVxnPhmuXB@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Snappers @ LumberKings Snappers @ LumberKings

Follow on MiLB First Pitch  https //stza.co/+vMMT-2x

Shop  https //stza.co/+vMMT-3e

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Snappers @ LumberKings
END:VALARM
DTSTART:20180421T233000Z
DTEND:20180422T023000Z
UID:_bny97U1y_rSE_RVxnPhmuXB@stanza.co
SUMMARY:Snappers @ LumberKings
DESCRIPTION:Snappers @ LumberKings\n\nFollow on MiLB First Pitch: https://stza.co/+vMMT-2x\n\nShop: https://stza.co/+vMMT-3e\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144504Z
LAST-MODIFIED:20180213T144504Z
TRANSP:OPAQUE
END:VEVENT
* Snappers @ LumberKings
<2018-04-22 Sun 14:00-17:00>
:PROPERTIES:
:ID:       -l0ZkmMnRaQpVpTCcEtbJMMC@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Snappers @ LumberKings Snappers @ LumberKings

Follow on MiLB First Pitch  https //stza.co/+vMMU-1A

Shop  https //stza.co/+vMMU-3B

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Snappers @ LumberKings
END:VALARM
DTSTART:20180422T190000Z
DTEND:20180422T220000Z
UID:-l0ZkmMnRaQpVpTCcEtbJMMC@stanza.co
SUMMARY:Snappers @ LumberKings
DESCRIPTION:Snappers @ LumberKings\n\nFollow on MiLB First Pitch: https://stza.co/+vMMU-1A\n\nShop: https://stza.co/+vMMU-3B\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144504Z
LAST-MODIFIED:20180213T144504Z
TRANSP:OPAQUE
END:VEVENT
* Snappers vs. Chiefs
<2018-04-23 Mon 18:30-21:30>
:PROPERTIES:
:ID:       Vl_s3zkjoKvkpPuCqEevYCvR@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Snappers vs. Chiefs Snappers vs. Chiefs

Follow on MiLB First Pitch  https //stza.co/+wSI1-39

Shop  https //stza.co/+wSI1-1V

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Snappers vs. Chiefs
END:VALARM
DTSTART:20180423T233000Z
DTEND:20180424T023000Z
UID:Vl_s3zkjoKvkpPuCqEevYCvR@stanza.co
SUMMARY:Snappers vs. Chiefs
DESCRIPTION:Snappers vs. Chiefs\n\nFollow on MiLB First Pitch: https://stza.co/+wSI1-39\n\nShop: https://stza.co/+wSI1-1V\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144504Z
LAST-MODIFIED:20180213T144504Z
TRANSP:OPAQUE
END:VEVENT
* Snappers vs. Chiefs
<2018-04-24 Tue 18:30-21:30>
:PROPERTIES:
:ID:       Aa6-DQQmaFK8HcY2jVEAkhiq@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Snappers vs. Chiefs Snappers vs. Chiefs

Follow on MiLB First Pitch  https //stza.co/+wSI4-2H

Shop  https //stza.co/+wSI4-c

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Snappers vs. Chiefs
END:VALARM
DTSTART:20180424T233000Z
DTEND:20180425T023000Z
UID:Aa6-DQQmaFK8HcY2jVEAkhiq@stanza.co
SUMMARY:Snappers vs. Chiefs
DESCRIPTION:Snappers vs. Chiefs\n\nFollow on MiLB First Pitch: https://stza.co/+wSI4-2H\n\nShop: https://stza.co/+wSI4-c\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144504Z
LAST-MODIFIED:20180213T144504Z
TRANSP:OPAQUE
END:VEVENT
* Snappers vs. Chiefs
<2018-04-25 Wed 18:30-21:30>
:PROPERTIES:
:ID:       GaY4whTQJciHq_xNNdEyKE8D@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Snappers vs. Chiefs Snappers vs. Chiefs

Follow on MiLB First Pitch  https //stza.co/+wSI7-G

Shop  https //stza.co/+wSI7-1G

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Snappers vs. Chiefs
END:VALARM
DTSTART:20180425T233000Z
DTEND:20180426T023000Z
UID:GaY4whTQJciHq_xNNdEyKE8D@stanza.co
SUMMARY:Snappers vs. Chiefs
DESCRIPTION:Snappers vs. Chiefs\n\nFollow on MiLB First Pitch: https://stza.co/+wSI7-G\n\nShop: https://stza.co/+wSI7-1G\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144504Z
LAST-MODIFIED:20180213T144504Z
TRANSP:OPAQUE
END:VEVENT
* Snappers vs. Chiefs
<2018-04-26 Thu 18:30-21:30>
:PROPERTIES:
:ID:       sp9w7a5E61PXAahhNMutFtha@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Snappers vs. Chiefs Snappers vs. Chiefs

Follow on MiLB First Pitch  https //stza.co/+wSI8-7

Shop  https //stza.co/+wSI8-3f

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Snappers vs. Chiefs
END:VALARM
DTSTART:20180426T233000Z
DTEND:20180427T023000Z
UID:sp9w7a5E61PXAahhNMutFtha@stanza.co
SUMMARY:Snappers vs. Chiefs
DESCRIPTION:Snappers vs. Chiefs\n\nFollow on MiLB First Pitch: https://stza.co/+wSI8-7\n\nShop: https://stza.co/+wSI8-3f\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144504Z
LAST-MODIFIED:20180213T144504Z
TRANSP:OPAQUE
END:VEVENT
* Snappers vs. LumberKings
<2018-04-27 Fri 18:30-21:30>
:PROPERTIES:
:ID:       B1WwbR05AgdAFouTFmr8RMlx@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Snappers vs. LumberKings Snappers vs. LumberKings

Follow on MiLB First Pitch  https //stza.co/+wSIb-1p

Shop  https //stza.co/+wSIb-3k

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Snappers vs. LumberKings
END:VALARM
DTSTART:20180427T233000Z
DTEND:20180428T023000Z
UID:B1WwbR05AgdAFouTFmr8RMlx@stanza.co
SUMMARY:Snappers vs. LumberKings
DESCRIPTION:Snappers vs. LumberKings\n\nFollow on MiLB First Pitch: https://stza.co/+wSIb-1p\n\nShop: https://stza.co/+wSIb-3k\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144504Z
LAST-MODIFIED:20180213T144504Z
TRANSP:OPAQUE
END:VEVENT
* Snappers vs. LumberKings
<2018-04-28 Sat 16:00-19:00>
:PROPERTIES:
:ID:       9T90q9xgp21J7q2ZbDGlwfHQ@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Snappers vs. LumberKings Snappers vs. LumberKings

Follow on MiLB First Pitch  https //stza.co/+wSId-23

Shop  https //stza.co/+wSId-18

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Snappers vs. LumberKings
END:VALARM
DTSTART:20180428T210000Z
DTEND:20180429T000000Z
UID:9T90q9xgp21J7q2ZbDGlwfHQ@stanza.co
SUMMARY:Snappers vs. LumberKings
DESCRIPTION:Snappers vs. LumberKings\n\nFollow on MiLB First Pitch: https://stza.co/+wSId-23\n\nShop: https://stza.co/+wSId-18\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144504Z
LAST-MODIFIED:20180213T144504Z
TRANSP:OPAQUE
END:VEVENT
* Snappers vs. LumberKings
<2018-04-29 Sun 14:00-17:00>
:PROPERTIES:
:ID:       zeM6gZs9KC4IHjCiJMFqHrCP@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Snappers vs. LumberKings Snappers vs. LumberKings

Follow on MiLB First Pitch  https //stza.co/+wSIe-1s

Shop  https //stza.co/+wSIe-30

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Snappers vs. LumberKings
END:VALARM
DTSTART:20180429T190000Z
DTEND:20180429T220000Z
UID:zeM6gZs9KC4IHjCiJMFqHrCP@stanza.co
SUMMARY:Snappers vs. LumberKings
DESCRIPTION:Snappers vs. LumberKings\n\nFollow on MiLB First Pitch: https://stza.co/+wSIe-1s\n\nShop: https://stza.co/+wSIe-30\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144504Z
LAST-MODIFIED:20180213T144504Z
TRANSP:OPAQUE
END:VEVENT
* Snappers @ TinCaps
<2018-05-01 Tue 18:05-21:05>
:PROPERTIES:
:ID:       CXRGQelcjtZt0j0rn9lTUDLp@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Snappers @ TinCaps Snappers @ TinCaps

Follow on MiLB First Pitch  https //stza.co/+vMMY-2W

Shop  https //stza.co/+vMMY-20

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Snappers @ TinCaps
END:VALARM
DTSTART:20180501T230500Z
DTEND:20180502T020500Z
UID:CXRGQelcjtZt0j0rn9lTUDLp@stanza.co
SUMMARY:Snappers @ TinCaps
DESCRIPTION:Snappers @ TinCaps\n\nFollow on MiLB First Pitch: https://stza.co/+vMMY-2W\n\nShop: https://stza.co/+vMMY-20\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144504Z
LAST-MODIFIED:20180213T144504Z
TRANSP:OPAQUE
END:VEVENT
* Snappers @ TinCaps
<2018-05-02 Wed 10:05-13:05>
:PROPERTIES:
:ID:       EvO0_4O6KCkRR7IPCOSwlVtp@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Snappers @ TinCaps Snappers @ TinCaps

Follow on MiLB First Pitch  https //stza.co/+vMMZ-i

Shop  https //stza.co/+vMMZ-1_

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Snappers @ TinCaps
END:VALARM
DTSTART:20180502T150500Z
DTEND:20180502T180500Z
UID:EvO0_4O6KCkRR7IPCOSwlVtp@stanza.co
SUMMARY:Snappers @ TinCaps
DESCRIPTION:Snappers @ TinCaps\n\nFollow on MiLB First Pitch: https://stza.co/+vMMZ-i\n\nShop: https://stza.co/+vMMZ-1_\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144504Z
LAST-MODIFIED:20180213T144504Z
TRANSP:OPAQUE
END:VEVENT
* Snappers @ TinCaps
<2018-05-03 Thu 18:05-21:05>
:PROPERTIES:
:ID:       kLSMba8-Sb-fwynetaCmDSbn@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Snappers @ TinCaps Snappers @ TinCaps

Follow on MiLB First Pitch  https //stza.co/+vMM_-w

Shop  https //stza.co/+vMM_-2Y

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Snappers @ TinCaps
END:VALARM
DTSTART:20180503T230500Z
DTEND:20180504T020500Z
UID:kLSMba8-Sb-fwynetaCmDSbn@stanza.co
SUMMARY:Snappers @ TinCaps
DESCRIPTION:Snappers @ TinCaps\n\nFollow on MiLB First Pitch: https://stza.co/+vMM_-w\n\nShop: https://stza.co/+vMM_-2Y\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144504Z
LAST-MODIFIED:20180213T144504Z
TRANSP:OPAQUE
END:VEVENT
* Snappers @ Captains
<2018-05-04 Fri 17:30-20:30>
:PROPERTIES:
:ID:       Yx_VmnycEwmS2PUVoMN7J7aO@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Snappers @ Captains Snappers @ Captains

Follow on MiLB First Pitch  https //stza.co/+xBiO-1a

Shop  https //stza.co/+xBiO-1k

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Snappers @ Captains
END:VALARM
DTSTART:20180504T223000Z
DTEND:20180505T013000Z
UID:Yx_VmnycEwmS2PUVoMN7J7aO@stanza.co
SUMMARY:Snappers @ Captains
DESCRIPTION:Snappers @ Captains\n\nFollow on MiLB First Pitch: https://stza.co/+xBiO-1a\n\nShop: https://stza.co/+xBiO-1k\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144504Z
LAST-MODIFIED:20180213T144504Z
TRANSP:OPAQUE
END:VEVENT
* Snappers @ Captains
<2018-05-05 Sat 17:30-20:30>
:PROPERTIES:
:ID:       jhRGvToEXv_15OFq9_LOGCGy@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Snappers @ Captains Snappers @ Captains

Follow on MiLB First Pitch  https //stza.co/+xBiP-1I

Shop  https //stza.co/+xBiP-3h

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Snappers @ Captains
END:VALARM
DTSTART:20180505T223000Z
DTEND:20180506T013000Z
UID:jhRGvToEXv_15OFq9_LOGCGy@stanza.co
SUMMARY:Snappers @ Captains
DESCRIPTION:Snappers @ Captains\n\nFollow on MiLB First Pitch: https://stza.co/+xBiP-1I\n\nShop: https://stza.co/+xBiP-3h\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144504Z
LAST-MODIFIED:20180213T144504Z
TRANSP:OPAQUE
END:VEVENT
* Snappers @ Captains
<2018-05-06 Sun 12:30-15:30>
:PROPERTIES:
:ID:       W7LwUkTZPDnzBJZpZYWY5e8N@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Snappers @ Captains Snappers @ Captains

Follow on MiLB First Pitch  https //stza.co/+xBiQ-1y

Shop  https //stza.co/+xBiQ-2M

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Snappers @ Captains
END:VALARM
DTSTART:20180506T173000Z
DTEND:20180506T203000Z
UID:W7LwUkTZPDnzBJZpZYWY5e8N@stanza.co
SUMMARY:Snappers @ Captains
DESCRIPTION:Snappers @ Captains\n\nFollow on MiLB First Pitch: https://stza.co/+xBiQ-1y\n\nShop: https://stza.co/+xBiQ-2M\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144504Z
LAST-MODIFIED:20180213T144504Z
TRANSP:OPAQUE
END:VEVENT
* Snappers vs. Loons
<2018-05-07 Mon 18:30-21:30>
:PROPERTIES:
:ID:       HuVmUqyLTSkc4pdgQxqoybB7@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Snappers vs. Loons Snappers vs. Loons

Follow on MiLB First Pitch  https //stza.co/+wSIh-k

Shop  https //stza.co/+wSIh-m

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Snappers vs. Loons
END:VALARM
DTSTART:20180507T233000Z
DTEND:20180508T023000Z
UID:HuVmUqyLTSkc4pdgQxqoybB7@stanza.co
SUMMARY:Snappers vs. Loons
DESCRIPTION:Snappers vs. Loons\n\nFollow on MiLB First Pitch: https://stza.co/+wSIh-k\n\nShop: https://stza.co/+wSIh-m\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144504Z
LAST-MODIFIED:20180213T144504Z
TRANSP:OPAQUE
END:VEVENT
* Snappers vs. Loons
<2018-05-08 Tue 18:30-21:30>
:PROPERTIES:
:ID:       cl29XIKF6MPv0pRwraZStpSl@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Snappers vs. Loons Snappers vs. Loons

Follow on MiLB First Pitch  https //stza.co/+wSIi-3O

Shop  https //stza.co/+wSIi-12

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Snappers vs. Loons
END:VALARM
DTSTART:20180508T233000Z
DTEND:20180509T023000Z
UID:cl29XIKF6MPv0pRwraZStpSl@stanza.co
SUMMARY:Snappers vs. Loons
DESCRIPTION:Snappers vs. Loons\n\nFollow on MiLB First Pitch: https://stza.co/+wSIi-3O\n\nShop: https://stza.co/+wSIi-12\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144504Z
LAST-MODIFIED:20180213T144504Z
TRANSP:OPAQUE
END:VEVENT
* Snappers vs. Loons
<2018-05-09 Wed 11:00-14:00>
:PROPERTIES:
:ID:       d2_7fq4OcbtEqIZxAC3TH45J@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Snappers vs. Loons Snappers vs. Loons

Follow on MiLB First Pitch  https //stza.co/+wSIk-J

Shop  https //stza.co/+wSIk-b

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Snappers vs. Loons
END:VALARM
DTSTART:20180509T160000Z
DTEND:20180509T190000Z
UID:d2_7fq4OcbtEqIZxAC3TH45J@stanza.co
SUMMARY:Snappers vs. Loons
DESCRIPTION:Snappers vs. Loons\n\nFollow on MiLB First Pitch: https://stza.co/+wSIk-J\n\nShop: https://stza.co/+wSIk-b\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144504Z
LAST-MODIFIED:20180213T144504Z
TRANSP:OPAQUE
END:VEVENT
* Snappers vs. Lugnuts
<2018-05-10 Thu 18:30-21:30>
:PROPERTIES:
:ID:       OiPegF0manmfOb9xAJD9UphB@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Snappers vs. Lugnuts Snappers vs. Lugnuts

Follow on MiLB First Pitch  https //stza.co/+wSIn-R

Shop  https //stza.co/+wSIn-3j

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Snappers vs. Lugnuts
END:VALARM
DTSTART:20180510T233000Z
DTEND:20180511T023000Z
UID:OiPegF0manmfOb9xAJD9UphB@stanza.co
SUMMARY:Snappers vs. Lugnuts
DESCRIPTION:Snappers vs. Lugnuts\n\nFollow on MiLB First Pitch: https://stza.co/+wSIn-R\n\nShop: https://stza.co/+wSIn-3j\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144504Z
LAST-MODIFIED:20180213T144504Z
TRANSP:OPAQUE
END:VEVENT
* Snappers vs. Lugnuts
<2018-05-11 Fri 18:30-21:30>
:PROPERTIES:
:ID:       0b8q9kADivFzI-xZT6PtjMPg@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Snappers vs. Lugnuts Snappers vs. Lugnuts

Follow on MiLB First Pitch  https //stza.co/+wSIp-3q

Shop  https //stza.co/+wSIp-3G

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Snappers vs. Lugnuts
END:VALARM
DTSTART:20180511T233000Z
DTEND:20180512T023000Z
UID:0b8q9kADivFzI-xZT6PtjMPg@stanza.co
SUMMARY:Snappers vs. Lugnuts
DESCRIPTION:Snappers vs. Lugnuts\n\nFollow on MiLB First Pitch: https://stza.co/+wSIp-3q\n\nShop: https://stza.co/+wSIp-3G\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144504Z
LAST-MODIFIED:20180213T144504Z
TRANSP:OPAQUE
END:VEVENT
* Snappers vs. Lugnuts
<2018-05-12 Sat 16:00-19:00>
:PROPERTIES:
:ID:       2MHZ2lZyoXkgaj4TpmWNZ8j8@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Snappers vs. Lugnuts Snappers vs. Lugnuts

Follow on MiLB First Pitch  https //stza.co/+wSIq-D

Shop  https //stza.co/+wSIq-1v

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Snappers vs. Lugnuts
END:VALARM
DTSTART:20180512T210000Z
DTEND:20180513T000000Z
UID:2MHZ2lZyoXkgaj4TpmWNZ8j8@stanza.co
SUMMARY:Snappers vs. Lugnuts
DESCRIPTION:Snappers vs. Lugnuts\n\nFollow on MiLB First Pitch: https://stza.co/+wSIq-D\n\nShop: https://stza.co/+wSIq-1v\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144504Z
LAST-MODIFIED:20180213T144504Z
TRANSP:OPAQUE
END:VEVENT
* Snappers @ Timber Rattlers
<2018-05-14 Mon 18:35-21:35>
:PROPERTIES:
:ID:       q0Ae2JYmffH8H0bEJz-vgrJv@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Snappers @ Timber Rattlers Snappers @ Timber Rattlers

Follow on MiLB First Pitch  https //stza.co/+vMNw-s

Shop  https //stza.co/+vMNw-3Z

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Snappers @ Timber Rattlers
END:VALARM
DTSTART:20180514T233500Z
DTEND:20180515T023500Z
UID:q0Ae2JYmffH8H0bEJz-vgrJv@stanza.co
SUMMARY:Snappers @ Timber Rattlers
DESCRIPTION:Snappers @ Timber Rattlers\n\nFollow on MiLB First Pitch: https://stza.co/+vMNw-s\n\nShop: https://stza.co/+vMNw-3Z\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144504Z
LAST-MODIFIED:20180213T144504Z
TRANSP:OPAQUE
END:VEVENT
* Snappers @ Timber Rattlers
<2018-05-15 Tue 12:05-15:05>
:PROPERTIES:
:ID:       foBL7J7nh7opWwfJn0BTCyzG@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Snappers @ Timber Rattlers Snappers @ Timber Rattlers

Follow on MiLB First Pitch  https //stza.co/+vMNx-2V

Shop  https //stza.co/+vMNx-V

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Snappers @ Timber Rattlers
END:VALARM
DTSTART:20180515T170500Z
DTEND:20180515T200500Z
UID:foBL7J7nh7opWwfJn0BTCyzG@stanza.co
SUMMARY:Snappers @ Timber Rattlers
DESCRIPTION:Snappers @ Timber Rattlers\n\nFollow on MiLB First Pitch: https://stza.co/+vMNx-2V\n\nShop: https://stza.co/+vMNx-V\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144504Z
LAST-MODIFIED:20180213T144504Z
TRANSP:OPAQUE
END:VEVENT
* Snappers @ Timber Rattlers
<2018-05-16 Wed 18:35-21:35>
:PROPERTIES:
:ID:       tdfhYCkEF5wgoZDesI0wsB0e@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Snappers @ Timber Rattlers Snappers @ Timber Rattlers

Follow on MiLB First Pitch  https //stza.co/+vMNy-1_

Shop  https //stza.co/+vMNy-3B

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Snappers @ Timber Rattlers
END:VALARM
DTSTART:20180516T233500Z
DTEND:20180517T023500Z
UID:tdfhYCkEF5wgoZDesI0wsB0e@stanza.co
SUMMARY:Snappers @ Timber Rattlers
DESCRIPTION:Snappers @ Timber Rattlers\n\nFollow on MiLB First Pitch: https://stza.co/+vMNy-1_\n\nShop: https://stza.co/+vMNy-3B\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144504Z
LAST-MODIFIED:20180213T144504Z
TRANSP:OPAQUE
END:VEVENT
* Snappers @ Timber Rattlers
<2018-05-17 Thu 18:35-21:35>
:PROPERTIES:
:ID:       ezHJMJGLN7WNQpDzgPln8Q2W@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Snappers @ Timber Rattlers Snappers @ Timber Rattlers

Follow on MiLB First Pitch  https //stza.co/+vMNz-3P

Shop  https //stza.co/+vMNz-39

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Snappers @ Timber Rattlers
END:VALARM
DTSTART:20180517T233500Z
DTEND:20180518T023500Z
UID:ezHJMJGLN7WNQpDzgPln8Q2W@stanza.co
SUMMARY:Snappers @ Timber Rattlers
DESCRIPTION:Snappers @ Timber Rattlers\n\nFollow on MiLB First Pitch: https://stza.co/+vMNz-3P\n\nShop: https://stza.co/+vMNz-39\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144504Z
LAST-MODIFIED:20180213T144504Z
TRANSP:OPAQUE
END:VEVENT
* Snappers vs. River Bandits
<2018-05-18 Fri 18:30-21:30>
:PROPERTIES:
:ID:       wFzzfHF9lvPIXoRcHPUMnj8l@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Snappers vs. River Bandits Snappers vs. River Bandits

Follow on MiLB First Pitch  https //stza.co/+wSIt-1N

Shop  https //stza.co/+wSIt-2h

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Snappers vs. River Bandits
END:VALARM
DTSTART:20180518T233000Z
DTEND:20180519T023000Z
UID:wFzzfHF9lvPIXoRcHPUMnj8l@stanza.co
SUMMARY:Snappers vs. River Bandits
DESCRIPTION:Snappers vs. River Bandits\n\nFollow on MiLB First Pitch: https://stza.co/+wSIt-1N\n\nShop: https://stza.co/+wSIt-2h\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144504Z
LAST-MODIFIED:20180213T144504Z
TRANSP:OPAQUE
END:VEVENT
* Snappers vs. River Bandits
<2018-05-19 Sat 16:00-19:00>
:PROPERTIES:
:ID:       Fxf-t_ROgQf4quXjVCtp5F34@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Snappers vs. River Bandits Snappers vs. River Bandits

Follow on MiLB First Pitch  https //stza.co/+wSIv-2c

Shop  https //stza.co/+wSIv-3O

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Snappers vs. River Bandits
END:VALARM
DTSTART:20180519T210000Z
DTEND:20180520T000000Z
UID:Fxf-t_ROgQf4quXjVCtp5F34@stanza.co
SUMMARY:Snappers vs. River Bandits
DESCRIPTION:Snappers vs. River Bandits\n\nFollow on MiLB First Pitch: https://stza.co/+wSIv-2c\n\nShop: https://stza.co/+wSIv-3O\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144504Z
LAST-MODIFIED:20180213T144504Z
TRANSP:OPAQUE
END:VEVENT
* Snappers vs. River Bandits
<2018-05-20 Sun 14:00-17:00>
:PROPERTIES:
:ID:       luip-kDZt1Q4fkvCgC_SDFve@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Snappers vs. River Bandits Snappers vs. River Bandits

Follow on MiLB First Pitch  https //stza.co/+wSIy-1Y

Shop  https //stza.co/+wSIy-3a

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Snappers vs. River Bandits
END:VALARM
DTSTART:20180520T190000Z
DTEND:20180520T220000Z
UID:luip-kDZt1Q4fkvCgC_SDFve@stanza.co
SUMMARY:Snappers vs. River Bandits
DESCRIPTION:Snappers vs. River Bandits\n\nFollow on MiLB First Pitch: https://stza.co/+wSIy-1Y\n\nShop: https://stza.co/+wSIy-3a\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144504Z
LAST-MODIFIED:20180213T144504Z
TRANSP:OPAQUE
END:VEVENT
* Snappers vs. Chiefs
<2018-05-21 Mon 18:30-21:30>
:PROPERTIES:
:ID:       IYfdCbk4LL_tkablY2E9C5t_@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Snappers vs. Chiefs Snappers vs. Chiefs

Follow on MiLB First Pitch  https //stza.co/+wSIz-1h

Shop  https //stza.co/+wSIz-1M

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Snappers vs. Chiefs
END:VALARM
DTSTART:20180521T233000Z
DTEND:20180522T023000Z
UID:IYfdCbk4LL_tkablY2E9C5t_@stanza.co
SUMMARY:Snappers vs. Chiefs
DESCRIPTION:Snappers vs. Chiefs\n\nFollow on MiLB First Pitch: https://stza.co/+wSIz-1h\n\nShop: https://stza.co/+wSIz-1M\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144504Z
LAST-MODIFIED:20180213T144504Z
TRANSP:OPAQUE
END:VEVENT
* Snappers vs. Chiefs
<2018-05-22 Tue 11:00-14:00>
:PROPERTIES:
:ID:       ihx-iBHp_4vi_FtVC0rt3SNC@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Snappers vs. Chiefs Snappers vs. Chiefs

Follow on MiLB First Pitch  https //stza.co/+wSIB-2P

Shop  https //stza.co/+wSIB-2u

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Snappers vs. Chiefs
END:VALARM
DTSTART:20180522T160000Z
DTEND:20180522T190000Z
UID:ihx-iBHp_4vi_FtVC0rt3SNC@stanza.co
SUMMARY:Snappers vs. Chiefs
DESCRIPTION:Snappers vs. Chiefs\n\nFollow on MiLB First Pitch: https://stza.co/+wSIB-2P\n\nShop: https://stza.co/+wSIB-2u\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144504Z
LAST-MODIFIED:20180213T144504Z
TRANSP:OPAQUE
END:VEVENT
* Snappers vs. Chiefs
<2018-05-23 Wed 18:30-21:30>
:PROPERTIES:
:ID:       OMNgsICZrp1CFm4_zjXmcSNK@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Snappers vs. Chiefs Snappers vs. Chiefs

Follow on MiLB First Pitch  https //stza.co/+wSID-1b

Shop  https //stza.co/+wSID-1E

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Snappers vs. Chiefs
END:VALARM
DTSTART:20180523T233000Z
DTEND:20180524T023000Z
UID:OMNgsICZrp1CFm4_zjXmcSNK@stanza.co
SUMMARY:Snappers vs. Chiefs
DESCRIPTION:Snappers vs. Chiefs\n\nFollow on MiLB First Pitch: https://stza.co/+wSID-1b\n\nShop: https://stza.co/+wSID-1E\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144504Z
LAST-MODIFIED:20180213T144504Z
TRANSP:OPAQUE
END:VEVENT
* Snappers vs. Chiefs
<2018-05-24 Thu 18:30-21:30>
:PROPERTIES:
:ID:       i1If4UOYEqojqIZNtunx-it6@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Snappers vs. Chiefs Snappers vs. Chiefs

Follow on MiLB First Pitch  https //stza.co/+wSIF-21

Shop  https //stza.co/+wSIF-e

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Snappers vs. Chiefs
END:VALARM
DTSTART:20180524T233000Z
DTEND:20180525T023000Z
UID:i1If4UOYEqojqIZNtunx-it6@stanza.co
SUMMARY:Snappers vs. Chiefs
DESCRIPTION:Snappers vs. Chiefs\n\nFollow on MiLB First Pitch: https://stza.co/+wSIF-21\n\nShop: https://stza.co/+wSIF-e\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144504Z
LAST-MODIFIED:20180213T144504Z
TRANSP:OPAQUE
END:VEVENT
* Snappers @ Bees
<2018-05-25 Fri 18:30-21:30>
:PROPERTIES:
:ID:       -HKWSdLrXDWvBBvOTqz0-2Oc@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Snappers @ Bees Snappers @ Bees

Follow on MiLB First Pitch  https //stza.co/+xBio-2m

Shop  https //stza.co/+xBio-3K

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Snappers @ Bees
END:VALARM
DTSTART:20180525T233000Z
DTEND:20180526T023000Z
UID:-HKWSdLrXDWvBBvOTqz0-2Oc@stanza.co
SUMMARY:Snappers @ Bees
DESCRIPTION:Snappers @ Bees\n\nFollow on MiLB First Pitch: https://stza.co/+xBio-2m\n\nShop: https://stza.co/+xBio-3K\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144504Z
LAST-MODIFIED:20180213T144504Z
TRANSP:OPAQUE
END:VEVENT
* Snappers @ Bees
<2018-05-26 Sat 17:00-20:00>
:PROPERTIES:
:ID:       pDxOF_MBywTTLVC123j2l485@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Snappers @ Bees Snappers @ Bees

Follow on MiLB First Pitch  https //stza.co/+xBip-3G

Shop  https //stza.co/+xBip-2O

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Snappers @ Bees
END:VALARM
DTSTART:20180526T220000Z
DTEND:20180527T010000Z
UID:pDxOF_MBywTTLVC123j2l485@stanza.co
SUMMARY:Snappers @ Bees
DESCRIPTION:Snappers @ Bees\n\nFollow on MiLB First Pitch: https://stza.co/+xBip-3G\n\nShop: https://stza.co/+xBip-2O\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144504Z
LAST-MODIFIED:20180213T144504Z
TRANSP:OPAQUE
END:VEVENT
* Snappers @ Bees
<2018-05-27 Sun 14:00-17:00>
:PROPERTIES:
:ID:       Kh3RpUtyD5JikpB-u_JqCfor@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Snappers @ Bees Snappers @ Bees

Follow on MiLB First Pitch  https //stza.co/+xBiq-w

Shop  https //stza.co/+xBiq-K

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Snappers @ Bees
END:VALARM
DTSTART:20180527T190000Z
DTEND:20180527T220000Z
UID:Kh3RpUtyD5JikpB-u_JqCfor@stanza.co
SUMMARY:Snappers @ Bees
DESCRIPTION:Snappers @ Bees\n\nFollow on MiLB First Pitch: https://stza.co/+xBiq-w\n\nShop: https://stza.co/+xBiq-K\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144504Z
LAST-MODIFIED:20180213T144504Z
TRANSP:OPAQUE
END:VEVENT
* Snappers @ Bees
<2018-05-28 Mon 14:00-17:00>
:PROPERTIES:
:ID:       Go2BRxDo0iOJV-Zv1gwBpXq3@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Snappers @ Bees Snappers @ Bees

Follow on MiLB First Pitch  https //stza.co/+xBir-1Z

Shop  https //stza.co/+xBir-_

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Snappers @ Bees
END:VALARM
DTSTART:20180528T190000Z
DTEND:20180528T220000Z
UID:Go2BRxDo0iOJV-Zv1gwBpXq3@stanza.co
SUMMARY:Snappers @ Bees
DESCRIPTION:Snappers @ Bees\n\nFollow on MiLB First Pitch: https://stza.co/+xBir-1Z\n\nShop: https://stza.co/+xBir-_\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144504Z
LAST-MODIFIED:20180213T144504Z
TRANSP:OPAQUE
END:VEVENT
* Snappers vs. Cougars
<2018-05-29 Tue 18:30-21:30>
:PROPERTIES:
:ID:       rjIHRCl02s6WvOEVzbogi9lT@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Snappers vs. Cougars Snappers vs. Cougars

Follow on MiLB First Pitch  https //stza.co/+wSIH-1t

Shop  https //stza.co/+wSIH-3q

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Snappers vs. Cougars
END:VALARM
DTSTART:20180529T233000Z
DTEND:20180530T023000Z
UID:rjIHRCl02s6WvOEVzbogi9lT@stanza.co
SUMMARY:Snappers vs. Cougars
DESCRIPTION:Snappers vs. Cougars\n\nFollow on MiLB First Pitch: https://stza.co/+wSIH-1t\n\nShop: https://stza.co/+wSIH-3q\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144504Z
LAST-MODIFIED:20180213T144504Z
TRANSP:OPAQUE
END:VEVENT
* Snappers vs. Cougars
<2018-05-30 Wed 18:30-21:30>
:PROPERTIES:
:ID:       efBjehbSKZ3o0LX-yr8AYdc5@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Snappers vs. Cougars Snappers vs. Cougars

Follow on MiLB First Pitch  https //stza.co/+wSIK-1d

Shop  https //stza.co/+wSIK-36

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Snappers vs. Cougars
END:VALARM
DTSTART:20180530T233000Z
DTEND:20180531T023000Z
UID:efBjehbSKZ3o0LX-yr8AYdc5@stanza.co
SUMMARY:Snappers vs. Cougars
DESCRIPTION:Snappers vs. Cougars\n\nFollow on MiLB First Pitch: https://stza.co/+wSIK-1d\n\nShop: https://stza.co/+wSIK-36\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144504Z
LAST-MODIFIED:20180213T144504Z
TRANSP:OPAQUE
END:VEVENT
* Snappers vs. Cougars
<2018-05-31 Thu 18:30-21:30>
:PROPERTIES:
:ID:       r6roZJu3RceG16KiPSWHE_q5@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Snappers vs. Cougars Snappers vs. Cougars

Follow on MiLB First Pitch  https //stza.co/+wSIM-1k

Shop  https //stza.co/+wSIM-1b

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Snappers vs. Cougars
END:VALARM
DTSTART:20180531T233000Z
DTEND:20180601T023000Z
UID:r6roZJu3RceG16KiPSWHE_q5@stanza.co
SUMMARY:Snappers vs. Cougars
DESCRIPTION:Snappers vs. Cougars\n\nFollow on MiLB First Pitch: https://stza.co/+wSIM-1k\n\nShop: https://stza.co/+wSIM-1b\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144504Z
LAST-MODIFIED:20180213T144504Z
TRANSP:OPAQUE
END:VEVENT
* Snappers @ River Bandits
<2018-06-01 Fri 18:35-21:35>
:PROPERTIES:
:ID:       g3ydO3AbSYypWwjTXHESHg2S@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Snappers @ River Bandits Snappers @ River Bandits

Follow on MiLB First Pitch  https //stza.co/+wxlC-2E

Shop  https //stza.co/+wxlC-3E

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Snappers @ River Bandits
END:VALARM
DTSTART:20180601T233500Z
DTEND:20180602T023500Z
UID:g3ydO3AbSYypWwjTXHESHg2S@stanza.co
SUMMARY:Snappers @ River Bandits
DESCRIPTION:Snappers @ River Bandits\n\nFollow on MiLB First Pitch: https://stza.co/+wxlC-2E\n\nShop: https://stza.co/+wxlC-3E\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144504Z
LAST-MODIFIED:20180213T144504Z
TRANSP:OPAQUE
END:VEVENT
* Snappers @ River Bandits
<2018-06-02 Sat 18:35-21:35>
:PROPERTIES:
:ID:       iIToTFES9V2rWjpKHwQ1Jq23@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Snappers @ River Bandits Snappers @ River Bandits

Follow on MiLB First Pitch  https //stza.co/+wxlD-3f

Shop  https //stza.co/+wxlD-2H

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Snappers @ River Bandits
END:VALARM
DTSTART:20180602T233500Z
DTEND:20180603T023500Z
UID:iIToTFES9V2rWjpKHwQ1Jq23@stanza.co
SUMMARY:Snappers @ River Bandits
DESCRIPTION:Snappers @ River Bandits\n\nFollow on MiLB First Pitch: https://stza.co/+wxlD-3f\n\nShop: https://stza.co/+wxlD-2H\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144504Z
LAST-MODIFIED:20180213T144504Z
TRANSP:OPAQUE
END:VEVENT
* Snappers @ River Bandits
<2018-06-03 Sun 13:15-16:15>
:PROPERTIES:
:ID:       s8MKKnrHkCBNKYaGBHDlpTAI@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Snappers @ River Bandits Snappers @ River Bandits

Follow on MiLB First Pitch  https //stza.co/+wxlE-M

Shop  https //stza.co/+wxlE-14

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Snappers @ River Bandits
END:VALARM
DTSTART:20180603T181500Z
DTEND:20180603T211500Z
UID:s8MKKnrHkCBNKYaGBHDlpTAI@stanza.co
SUMMARY:Snappers @ River Bandits
DESCRIPTION:Snappers @ River Bandits\n\nFollow on MiLB First Pitch: https://stza.co/+wxlE-M\n\nShop: https://stza.co/+wxlE-14\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144504Z
LAST-MODIFIED:20180213T144504Z
TRANSP:OPAQUE
END:VEVENT
* Snappers @ Kernels
<2018-06-05 Tue 18:35-21:35>
:PROPERTIES:
:ID:       gCv_8j-CWcsTYSbt7R3d2Vsn@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Snappers @ Kernels Snappers @ Kernels

Buy tickets here  https //stza.co/~vMMJ

Follow on MiLB First Pitch  https //stza.co/+vMMJ-35

Shop  https //stza.co/+vMMJ-3Y

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Snappers @ Kernels
END:VALARM
DTSTART:20180605T233500Z
DTEND:20180606T023500Z
UID:gCv_8j-CWcsTYSbt7R3d2Vsn@stanza.co
SUMMARY:Snappers @ Kernels
DESCRIPTION:Snappers @ Kernels\n\nBuy tickets here: https://stza.co/~vMMJ\n\nFollow on MiLB First Pitch: https://stza.co/+vMMJ-35\n\nShop: https://stza.co/+vMMJ-3Y\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144504Z
LAST-MODIFIED:20180213T144504Z
TRANSP:OPAQUE
END:VEVENT
* Snappers @ Kernels
<2018-06-06 Wed 12:05-15:05>
:PROPERTIES:
:ID:       e8wR7gpUR3ubtLf038PVE25P@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Snappers @ Kernels Snappers @ Kernels

Buy tickets here  https //stza.co/~w0NL

Follow on MiLB First Pitch  https //stza.co/+w0NL-2w

Shop  https //stza.co/+w0NL-3D

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Snappers @ Kernels
END:VALARM
DTSTART:20180606T170500Z
DTEND:20180606T200500Z
UID:e8wR7gpUR3ubtLf038PVE25P@stanza.co
SUMMARY:Snappers @ Kernels
DESCRIPTION:Snappers @ Kernels\n\nBuy tickets here: https://stza.co/~w0NL\n\nFollow on MiLB First Pitch: https://stza.co/+w0NL-2w\n\nShop: https://stza.co/+w0NL-3D\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144504Z
LAST-MODIFIED:20180213T144504Z
TRANSP:OPAQUE
END:VEVENT
* Snappers @ Kernels
<2018-06-07 Thu 18:35-21:35>
:PROPERTIES:
:ID:       oEyXHUOoxlsi5psVW-d8B4rP@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Snappers @ Kernels Snappers @ Kernels

Buy tickets here  https //stza.co/~vMML

Follow on MiLB First Pitch  https //stza.co/+vMML-e

Shop  https //stza.co/+vMML-1n

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Snappers @ Kernels
END:VALARM
DTSTART:20180607T233500Z
DTEND:20180608T023500Z
UID:oEyXHUOoxlsi5psVW-d8B4rP@stanza.co
SUMMARY:Snappers @ Kernels
DESCRIPTION:Snappers @ Kernels\n\nBuy tickets here: https://stza.co/~vMML\n\nFollow on MiLB First Pitch: https://stza.co/+vMML-e\n\nShop: https://stza.co/+vMML-1n\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144504Z
LAST-MODIFIED:20180213T144504Z
TRANSP:OPAQUE
END:VEVENT
* Snappers vs. Bees
<2018-06-08 Fri 19:00-22:00>
:PROPERTIES:
:ID:       Rhhec470UhxxYowUCU69pUb9@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Snappers vs. Bees Snappers vs. Bees

Follow on MiLB First Pitch  https //stza.co/+wSIO-2D

Shop  https //stza.co/+wSIO-2I

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Snappers vs. Bees
END:VALARM
DTSTART:20180609T000000Z
DTEND:20180609T030000Z
UID:Rhhec470UhxxYowUCU69pUb9@stanza.co
SUMMARY:Snappers vs. Bees
DESCRIPTION:Snappers vs. Bees\n\nFollow on MiLB First Pitch: https://stza.co/+wSIO-2D\n\nShop: https://stza.co/+wSIO-2I\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144504Z
LAST-MODIFIED:20180213T144504Z
TRANSP:OPAQUE
END:VEVENT
* Snappers vs. Bees
<2018-06-09 Sat 19:00-22:00>
:PROPERTIES:
:ID:       LNcjdpnkwA7uMJDGXPbMI_um@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Snappers vs. Bees Snappers vs. Bees

Follow on MiLB First Pitch  https //stza.co/+wSIQ-2P

Shop  https //stza.co/+wSIQ-7

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Snappers vs. Bees
END:VALARM
DTSTART:20180610T000000Z
DTEND:20180610T030000Z
UID:LNcjdpnkwA7uMJDGXPbMI_um@stanza.co
SUMMARY:Snappers vs. Bees
DESCRIPTION:Snappers vs. Bees\n\nFollow on MiLB First Pitch: https://stza.co/+wSIQ-2P\n\nShop: https://stza.co/+wSIQ-7\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144504Z
LAST-MODIFIED:20180213T144504Z
TRANSP:OPAQUE
END:VEVENT
* Snappers vs. Bees
<2018-06-10 Sun 14:00-17:00>
:PROPERTIES:
:ID:       Pt7CtZAT04GOuTlb-BNwK42W@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Snappers vs. Bees Snappers vs. Bees

Follow on MiLB First Pitch  https //stza.co/+wSIS-O

Shop  https //stza.co/+wSIS-3g

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Snappers vs. Bees
END:VALARM
DTSTART:20180610T190000Z
DTEND:20180610T220000Z
UID:Pt7CtZAT04GOuTlb-BNwK42W@stanza.co
SUMMARY:Snappers vs. Bees
DESCRIPTION:Snappers vs. Bees\n\nFollow on MiLB First Pitch: https://stza.co/+wSIS-O\n\nShop: https://stza.co/+wSIS-3g\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144504Z
LAST-MODIFIED:20180213T144504Z
TRANSP:OPAQUE
END:VEVENT
* Snappers vs. Bees
<2018-06-11 Mon 19:00-22:00>
:PROPERTIES:
:ID:       BCOynL2Kk2WYJYvjOTqg8lWn@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Snappers vs. Bees Snappers vs. Bees

Follow on MiLB First Pitch  https //stza.co/+wSIU-1Y

Shop  https //stza.co/+wSIU-2O

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Snappers vs. Bees
END:VALARM
DTSTART:20180612T000000Z
DTEND:20180612T030000Z
UID:BCOynL2Kk2WYJYvjOTqg8lWn@stanza.co
SUMMARY:Snappers vs. Bees
DESCRIPTION:Snappers vs. Bees\n\nFollow on MiLB First Pitch: https://stza.co/+wSIU-1Y\n\nShop: https://stza.co/+wSIU-2O\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144504Z
LAST-MODIFIED:20180213T144504Z
TRANSP:OPAQUE
END:VEVENT
* Snappers @ Chiefs
<2018-06-12 Tue 19:00-22:00>
:PROPERTIES:
:ID:       84FFFqPB3558XXK1zRrznOI2@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Snappers @ Chiefs Snappers @ Chiefs

Follow on MiLB First Pitch  https //stza.co/+xAnP-e

Shop  https //stza.co/+xAnP-1X

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Snappers @ Chiefs
END:VALARM
DTSTART:20180613T000000Z
DTEND:20180613T030000Z
UID:84FFFqPB3558XXK1zRrznOI2@stanza.co
SUMMARY:Snappers @ Chiefs
DESCRIPTION:Snappers @ Chiefs\n\nFollow on MiLB First Pitch: https://stza.co/+xAnP-e\n\nShop: https://stza.co/+xAnP-1X\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144504Z
LAST-MODIFIED:20180213T144504Z
TRANSP:OPAQUE
END:VEVENT
* Snappers @ Chiefs
<2018-06-13 Wed 19:00-22:00>
:PROPERTIES:
:ID:       irLy23Xi1vsVaFSuubwxr1uP@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Snappers @ Chiefs Snappers @ Chiefs

Follow on MiLB First Pitch  https //stza.co/+xAnR-H

Shop  https //stza.co/+xAnR-3f

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Snappers @ Chiefs
END:VALARM
DTSTART:20180614T000000Z
DTEND:20180614T030000Z
UID:irLy23Xi1vsVaFSuubwxr1uP@stanza.co
SUMMARY:Snappers @ Chiefs
DESCRIPTION:Snappers @ Chiefs\n\nFollow on MiLB First Pitch: https://stza.co/+xAnR-H\n\nShop: https://stza.co/+xAnR-3f\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144504Z
LAST-MODIFIED:20180213T144504Z
TRANSP:OPAQUE
END:VEVENT
* Snappers @ Chiefs
<2018-06-14 Thu 19:00-22:00>
:PROPERTIES:
:ID:       vybJjkW3M8oka__4iQI-64_T@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Snappers @ Chiefs Snappers @ Chiefs

Follow on MiLB First Pitch  https //stza.co/+xAnS-2r

Shop  https //stza.co/+xAnS-22

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Snappers @ Chiefs
END:VALARM
DTSTART:20180615T000000Z
DTEND:20180615T030000Z
UID:vybJjkW3M8oka__4iQI-64_T@stanza.co
SUMMARY:Snappers @ Chiefs
DESCRIPTION:Snappers @ Chiefs\n\nFollow on MiLB First Pitch: https://stza.co/+xAnS-2r\n\nShop: https://stza.co/+xAnS-22\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144504Z
LAST-MODIFIED:20180213T144504Z
TRANSP:OPAQUE
END:VEVENT
* Snappers vs. LumberKings
<2018-06-15 Fri 19:00-22:00>
:PROPERTIES:
:ID:       Rp37zD_jSVcvcpbqf7oJXxI2@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Snappers vs. LumberKings Snappers vs. LumberKings

Follow on MiLB First Pitch  https //stza.co/+wSIW-3c

Shop  https //stza.co/+wSIW-a

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Snappers vs. LumberKings
END:VALARM
DTSTART:20180616T000000Z
DTEND:20180616T030000Z
UID:Rp37zD_jSVcvcpbqf7oJXxI2@stanza.co
SUMMARY:Snappers vs. LumberKings
DESCRIPTION:Snappers vs. LumberKings\n\nFollow on MiLB First Pitch: https://stza.co/+wSIW-3c\n\nShop: https://stza.co/+wSIW-a\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144504Z
LAST-MODIFIED:20180213T144504Z
TRANSP:OPAQUE
END:VEVENT
* Snappers vs. LumberKings
<2018-06-16 Sat 19:00-22:00>
:PROPERTIES:
:ID:       LEhZhkL2sVivYjgC31m0iWRS@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Snappers vs. LumberKings Snappers vs. LumberKings

Follow on MiLB First Pitch  https //stza.co/+wSIY-A

Shop  https //stza.co/+wSIY-u

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Snappers vs. LumberKings
END:VALARM
DTSTART:20180617T000000Z
DTEND:20180617T030000Z
UID:LEhZhkL2sVivYjgC31m0iWRS@stanza.co
SUMMARY:Snappers vs. LumberKings
DESCRIPTION:Snappers vs. LumberKings\n\nFollow on MiLB First Pitch: https://stza.co/+wSIY-A\n\nShop: https://stza.co/+wSIY-u\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144504Z
LAST-MODIFIED:20180213T144504Z
TRANSP:OPAQUE
END:VEVENT
* Snappers vs. LumberKings
<2018-06-17 Sun 14:00-17:00>
:PROPERTIES:
:ID:       7U4hj7vA5dBVUUcss9rjJpYo@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Snappers vs. LumberKings Snappers vs. LumberKings

Follow on MiLB First Pitch  https //stza.co/+wSI$-31

Shop  https //stza.co/+wSI$-2f

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Snappers vs. LumberKings
END:VALARM
DTSTART:20180617T190000Z
DTEND:20180617T220000Z
UID:7U4hj7vA5dBVUUcss9rjJpYo@stanza.co
SUMMARY:Snappers vs. LumberKings
DESCRIPTION:Snappers vs. LumberKings\n\nFollow on MiLB First Pitch: https://stza.co/+wSI$-31\n\nShop: https://stza.co/+wSI$-2f\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144504Z
LAST-MODIFIED:20180213T144504Z
TRANSP:OPAQUE
END:VEVENT
* Snappers @ River Bandits
<2018-06-21 Thu 18:35-21:35>
:PROPERTIES:
:ID:       4BgIV0qu1LkqthTvptln0YOc@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Snappers @ River Bandits Snappers @ River Bandits

Follow on MiLB First Pitch  https //stza.co/+wxlF-4

Shop  https //stza.co/+wxlF-v

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Snappers @ River Bandits
END:VALARM
DTSTART:20180621T233500Z
DTEND:20180622T023500Z
UID:4BgIV0qu1LkqthTvptln0YOc@stanza.co
SUMMARY:Snappers @ River Bandits
DESCRIPTION:Snappers @ River Bandits\n\nFollow on MiLB First Pitch: https://stza.co/+wxlF-4\n\nShop: https://stza.co/+wxlF-v\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144504Z
LAST-MODIFIED:20180213T144504Z
TRANSP:OPAQUE
END:VEVENT
* Snappers @ River Bandits
<2018-06-22 Fri 18:35-21:35>
:PROPERTIES:
:ID:       Siy4q3XbVKflxZpeCl3c22uf@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Snappers @ River Bandits Snappers @ River Bandits

Follow on MiLB First Pitch  https //stza.co/+wxlG-1U

Shop  https //stza.co/+wxlG-16

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Snappers @ River Bandits
END:VALARM
DTSTART:20180622T233500Z
DTEND:20180623T023500Z
UID:Siy4q3XbVKflxZpeCl3c22uf@stanza.co
SUMMARY:Snappers @ River Bandits
DESCRIPTION:Snappers @ River Bandits\n\nFollow on MiLB First Pitch: https://stza.co/+wxlG-1U\n\nShop: https://stza.co/+wxlG-16\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144504Z
LAST-MODIFIED:20180213T144504Z
TRANSP:OPAQUE
END:VEVENT
* Snappers @ River Bandits
<2018-06-23 Sat 18:35-21:35>
:PROPERTIES:
:ID:       V3AO9En42RmepdaleLprCtYz@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Snappers @ River Bandits Snappers @ River Bandits

Follow on MiLB First Pitch  https //stza.co/+wxlH-2A

Shop  https //stza.co/+wxlH-i

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Snappers @ River Bandits
END:VALARM
DTSTART:20180623T233500Z
DTEND:20180624T023500Z
UID:V3AO9En42RmepdaleLprCtYz@stanza.co
SUMMARY:Snappers @ River Bandits
DESCRIPTION:Snappers @ River Bandits\n\nFollow on MiLB First Pitch: https://stza.co/+wxlH-2A\n\nShop: https://stza.co/+wxlH-i\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144504Z
LAST-MODIFIED:20180213T144504Z
TRANSP:OPAQUE
END:VEVENT
* Snappers @ River Bandits
<2018-06-24 Sun 17:15-20:15>
:PROPERTIES:
:ID:       d__vaDppZPMZj00kXJh9B5nG@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Snappers @ River Bandits Snappers @ River Bandits

Follow on MiLB First Pitch  https //stza.co/+wxlI-2s

Shop  https //stza.co/+wxlI-2b

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Snappers @ River Bandits
END:VALARM
DTSTART:20180624T221500Z
DTEND:20180625T011500Z
UID:d__vaDppZPMZj00kXJh9B5nG@stanza.co
SUMMARY:Snappers @ River Bandits
DESCRIPTION:Snappers @ River Bandits\n\nFollow on MiLB First Pitch: https://stza.co/+wxlI-2s\n\nShop: https://stza.co/+wxlI-2b\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144504Z
LAST-MODIFIED:20180213T144504Z
TRANSP:OPAQUE
END:VEVENT
* Snappers @ Kernels
<2018-06-25 Mon 18:35-21:35>
:PROPERTIES:
:ID:       WsoqydWR9xyZpbLncp_OVLTT@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Snappers @ Kernels Snappers @ Kernels

Buy tickets here  https //stza.co/~vMMM

Follow on MiLB First Pitch  https //stza.co/+vMMM-1z

Shop  https //stza.co/+vMMM-2N

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Snappers @ Kernels
END:VALARM
DTSTART:20180625T233500Z
DTEND:20180626T023500Z
UID:WsoqydWR9xyZpbLncp_OVLTT@stanza.co
SUMMARY:Snappers @ Kernels
DESCRIPTION:Snappers @ Kernels\n\nBuy tickets here: https://stza.co/~vMMM\n\nFollow on MiLB First Pitch: https://stza.co/+vMMM-1z\n\nShop: https://stza.co/+vMMM-2N\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144504Z
LAST-MODIFIED:20180213T144504Z
TRANSP:OPAQUE
END:VEVENT
* Snappers @ Kernels
<2018-06-26 Tue 18:35-21:35>
:PROPERTIES:
:ID:       LrKA4weAI_6_dvXdbNykh_YW@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Snappers @ Kernels Snappers @ Kernels

Buy tickets here  https //stza.co/~vMMN

Follow on MiLB First Pitch  https //stza.co/+vMMN-p

Shop  https //stza.co/+vMMN-2G

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Snappers @ Kernels
END:VALARM
DTSTART:20180626T233500Z
DTEND:20180627T023500Z
UID:LrKA4weAI_6_dvXdbNykh_YW@stanza.co
SUMMARY:Snappers @ Kernels
DESCRIPTION:Snappers @ Kernels\n\nBuy tickets here: https://stza.co/~vMMN\n\nFollow on MiLB First Pitch: https://stza.co/+vMMN-p\n\nShop: https://stza.co/+vMMN-2G\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144504Z
LAST-MODIFIED:20180213T144504Z
TRANSP:OPAQUE
END:VEVENT
* Snappers @ Kernels
<2018-06-27 Wed 12:05-15:05>
:PROPERTIES:
:ID:       rKUDmbrNzu_mjancT-Syqgsq@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Snappers @ Kernels Snappers @ Kernels

Buy tickets here  https //stza.co/~w0NM

Follow on MiLB First Pitch  https //stza.co/+w0NM-2S

Shop  https //stza.co/+w0NM-2B

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Snappers @ Kernels
END:VALARM
DTSTART:20180627T170500Z
DTEND:20180627T200500Z
UID:rKUDmbrNzu_mjancT-Syqgsq@stanza.co
SUMMARY:Snappers @ Kernels
DESCRIPTION:Snappers @ Kernels\n\nBuy tickets here: https://stza.co/~w0NM\n\nFollow on MiLB First Pitch: https://stza.co/+w0NM-2S\n\nShop: https://stza.co/+w0NM-2B\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144504Z
LAST-MODIFIED:20180213T144504Z
TRANSP:OPAQUE
END:VEVENT
* Snappers vs. Chiefs
<2018-06-28 Thu 19:00-22:00>
:PROPERTIES:
:ID:       O-XFE6GPQyvWONu8AHIey28e@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Snappers vs. Chiefs Snappers vs. Chiefs

Follow on MiLB First Pitch  https //stza.co/+wSJ0-3m

Shop  https //stza.co/+wSJ0-1

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Snappers vs. Chiefs
END:VALARM
DTSTART:20180629T000000Z
DTEND:20180629T030000Z
UID:O-XFE6GPQyvWONu8AHIey28e@stanza.co
SUMMARY:Snappers vs. Chiefs
DESCRIPTION:Snappers vs. Chiefs\n\nFollow on MiLB First Pitch: https://stza.co/+wSJ0-3m\n\nShop: https://stza.co/+wSJ0-1\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144504Z
LAST-MODIFIED:20180213T144504Z
TRANSP:OPAQUE
END:VEVENT
* Snappers vs. Chiefs
<2018-06-29 Fri 19:00-22:00>
:PROPERTIES:
:ID:       hgwQclfdGHlw-odg7XYjE2uk@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Snappers vs. Chiefs Snappers vs. Chiefs

Follow on MiLB First Pitch  https //stza.co/+wSJ2-3d

Shop  https //stza.co/+wSJ2-v

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Snappers vs. Chiefs
END:VALARM
DTSTART:20180630T000000Z
DTEND:20180630T030000Z
UID:hgwQclfdGHlw-odg7XYjE2uk@stanza.co
SUMMARY:Snappers vs. Chiefs
DESCRIPTION:Snappers vs. Chiefs\n\nFollow on MiLB First Pitch: https://stza.co/+wSJ2-3d\n\nShop: https://stza.co/+wSJ2-v\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144504Z
LAST-MODIFIED:20180213T144504Z
TRANSP:OPAQUE
END:VEVENT
* Snappers vs. Chiefs
<2018-06-30 Sat 19:00-22:00>
:PROPERTIES:
:ID:       xeTrZNEx0SfQ8Hkc2U-nePPX@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Snappers vs. Chiefs Snappers vs. Chiefs

Follow on MiLB First Pitch  https //stza.co/+wSJ6-3t

Shop  https //stza.co/+wSJ6-2A

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Snappers vs. Chiefs
END:VALARM
DTSTART:20180701T000000Z
DTEND:20180701T030000Z
UID:xeTrZNEx0SfQ8Hkc2U-nePPX@stanza.co
SUMMARY:Snappers vs. Chiefs
DESCRIPTION:Snappers vs. Chiefs\n\nFollow on MiLB First Pitch: https://stza.co/+wSJ6-3t\n\nShop: https://stza.co/+wSJ6-2A\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144504Z
LAST-MODIFIED:20180213T144504Z
TRANSP:OPAQUE
END:VEVENT
* Snappers vs. Chiefs
<2018-07-01 Sun 14:00-17:00>
:PROPERTIES:
:ID:       2VXDfSO1j3cR96xqKmAjR_CY@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Snappers vs. Chiefs Snappers vs. Chiefs

Follow on MiLB First Pitch  https //stza.co/+wSJ8-17

Shop  https //stza.co/+wSJ8-1O

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Snappers vs. Chiefs
END:VALARM
DTSTART:20180701T190000Z
DTEND:20180701T220000Z
UID:2VXDfSO1j3cR96xqKmAjR_CY@stanza.co
SUMMARY:Snappers vs. Chiefs
DESCRIPTION:Snappers vs. Chiefs\n\nFollow on MiLB First Pitch: https://stza.co/+wSJ8-17\n\nShop: https://stza.co/+wSJ8-1O\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144504Z
LAST-MODIFIED:20180213T144504Z
TRANSP:OPAQUE
END:VEVENT
* Snappers vs. River Bandits
<2018-07-02 Mon 19:00-22:00>
:PROPERTIES:
:ID:       JDC1xG5Ng9t5vyk1bBHpxkPN@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Snappers vs. River Bandits Snappers vs. River Bandits

Follow on MiLB First Pitch  https //stza.co/+wSJb-3w

Shop  https //stza.co/+wSJb-

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Snappers vs. River Bandits
END:VALARM
DTSTART:20180703T000000Z
DTEND:20180703T030000Z
UID:JDC1xG5Ng9t5vyk1bBHpxkPN@stanza.co
SUMMARY:Snappers vs. River Bandits
DESCRIPTION:Snappers vs. River Bandits\n\nFollow on MiLB First Pitch: https://stza.co/+wSJb-3w\n\nShop: https://stza.co/+wSJb-\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144504Z
LAST-MODIFIED:20180213T144504Z
TRANSP:OPAQUE
END:VEVENT
* Snappers vs. River Bandits
<2018-07-03 Tue 19:00-22:00>
:PROPERTIES:
:ID:       IeSJvYBGFbKReTVlJr5A0zqL@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Snappers vs. River Bandits Snappers vs. River Bandits

Follow on MiLB First Pitch  https //stza.co/+wSJc-3C

Shop  https //stza.co/+wSJc-2G

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Snappers vs. River Bandits
END:VALARM
DTSTART:20180704T000000Z
DTEND:20180704T030000Z
UID:IeSJvYBGFbKReTVlJr5A0zqL@stanza.co
SUMMARY:Snappers vs. River Bandits
DESCRIPTION:Snappers vs. River Bandits\n\nFollow on MiLB First Pitch: https://stza.co/+wSJc-3C\n\nShop: https://stza.co/+wSJc-2G\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144504Z
LAST-MODIFIED:20180213T144504Z
TRANSP:OPAQUE
END:VEVENT
* Snappers @ River Bandits
<2018-07-04 Wed 18:35-21:35>
:PROPERTIES:
:ID:       Up6Obuq7dq3l84XkoDdZV7TQ@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Snappers @ River Bandits Snappers @ River Bandits

Follow on MiLB First Pitch  https //stza.co/+wxlJ-39

Shop  https //stza.co/+wxlJ-2F

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Snappers @ River Bandits
END:VALARM
DTSTART:20180704T233500Z
DTEND:20180705T023500Z
UID:Up6Obuq7dq3l84XkoDdZV7TQ@stanza.co
SUMMARY:Snappers @ River Bandits
DESCRIPTION:Snappers @ River Bandits\n\nFollow on MiLB First Pitch: https://stza.co/+wxlJ-39\n\nShop: https://stza.co/+wxlJ-2F\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144504Z
LAST-MODIFIED:20180213T144504Z
TRANSP:OPAQUE
END:VEVENT
* Snappers @ River Bandits
<2018-07-05 Thu 18:35-21:35>
:PROPERTIES:
:ID:       bNbkWNY1Zhg4WhgbPiYPmBl3@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Snappers @ River Bandits Snappers @ River Bandits

Follow on MiLB First Pitch  https //stza.co/+wxlK-2A

Shop  https //stza.co/+wxlK-n

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Snappers @ River Bandits
END:VALARM
DTSTART:20180705T233500Z
DTEND:20180706T023500Z
UID:bNbkWNY1Zhg4WhgbPiYPmBl3@stanza.co
SUMMARY:Snappers @ River Bandits
DESCRIPTION:Snappers @ River Bandits\n\nFollow on MiLB First Pitch: https://stza.co/+wxlK-2A\n\nShop: https://stza.co/+wxlK-n\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144504Z
LAST-MODIFIED:20180213T144504Z
TRANSP:OPAQUE
END:VEVENT
* Snappers vs. LumberKings
<2018-07-06 Fri 19:00-22:00>
:PROPERTIES:
:ID:       I4JUPA4ApPL4I1X90tzvyK3A@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Snappers vs. LumberKings Snappers vs. LumberKings

Follow on MiLB First Pitch  https //stza.co/+wSJe-t

Shop  https //stza.co/+wSJe-39

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Snappers vs. LumberKings
END:VALARM
DTSTART:20180707T000000Z
DTEND:20180707T030000Z
UID:I4JUPA4ApPL4I1X90tzvyK3A@stanza.co
SUMMARY:Snappers vs. LumberKings
DESCRIPTION:Snappers vs. LumberKings\n\nFollow on MiLB First Pitch: https://stza.co/+wSJe-t\n\nShop: https://stza.co/+wSJe-39\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144504Z
LAST-MODIFIED:20180213T144504Z
TRANSP:OPAQUE
END:VEVENT
* Snappers vs. LumberKings
<2018-07-07 Sat 19:00-22:00>
:PROPERTIES:
:ID:       ctlXQmX-SAwxwpSe4iWgrQPd@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Snappers vs. LumberKings Snappers vs. LumberKings

Follow on MiLB First Pitch  https //stza.co/+wSJh-29

Shop  https //stza.co/+wSJh-K

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Snappers vs. LumberKings
END:VALARM
DTSTART:20180708T000000Z
DTEND:20180708T030000Z
UID:ctlXQmX-SAwxwpSe4iWgrQPd@stanza.co
SUMMARY:Snappers vs. LumberKings
DESCRIPTION:Snappers vs. LumberKings\n\nFollow on MiLB First Pitch: https://stza.co/+wSJh-29\n\nShop: https://stza.co/+wSJh-K\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144504Z
LAST-MODIFIED:20180213T144504Z
TRANSP:OPAQUE
END:VEVENT
* Snappers vs. LumberKings
<2018-07-08 Sun 14:00-17:00>
:PROPERTIES:
:ID:       yzjCNRf3pMsaTzmG-qQxJ96M@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Snappers vs. LumberKings Snappers vs. LumberKings

Follow on MiLB First Pitch  https //stza.co/+wSJi-3c

Shop  https //stza.co/+wSJi-b

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Snappers vs. LumberKings
END:VALARM
DTSTART:20180708T190000Z
DTEND:20180708T220000Z
UID:yzjCNRf3pMsaTzmG-qQxJ96M@stanza.co
SUMMARY:Snappers vs. LumberKings
DESCRIPTION:Snappers vs. LumberKings\n\nFollow on MiLB First Pitch: https://stza.co/+wSJi-3c\n\nShop: https://stza.co/+wSJi-b\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144504Z
LAST-MODIFIED:20180213T144504Z
TRANSP:OPAQUE
END:VEVENT
* Snappers vs. LumberKings
<2018-07-09 Mon 19:00-22:00>
:PROPERTIES:
:ID:       pztUw3igMFQlYXc_7wVnjzRk@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Snappers vs. LumberKings Snappers vs. LumberKings

Follow on MiLB First Pitch  https //stza.co/+wSJl-1$

Shop  https //stza.co/+wSJl-c

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Snappers vs. LumberKings
END:VALARM
DTSTART:20180710T000000Z
DTEND:20180710T030000Z
UID:pztUw3igMFQlYXc_7wVnjzRk@stanza.co
SUMMARY:Snappers vs. LumberKings
DESCRIPTION:Snappers vs. LumberKings\n\nFollow on MiLB First Pitch: https://stza.co/+wSJl-1$\n\nShop: https://stza.co/+wSJl-c\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144504Z
LAST-MODIFIED:20180213T144504Z
TRANSP:OPAQUE
END:VEVENT
* Snappers @ Cubs
<2018-07-11 Wed 18:05-21:05>
:PROPERTIES:
:ID:       IlzUbsNf9y1bJH9S1tTENqcz@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Snappers @ Cubs Snappers @ Cubs

Follow on MiLB First Pitch  https //stza.co/+vMNo-H

Shop  https //stza.co/+vMNo-1U

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Snappers @ Cubs
END:VALARM
DTSTART:20180711T230500Z
DTEND:20180712T020500Z
UID:IlzUbsNf9y1bJH9S1tTENqcz@stanza.co
SUMMARY:Snappers @ Cubs
DESCRIPTION:Snappers @ Cubs\n\nFollow on MiLB First Pitch: https://stza.co/+vMNo-H\n\nShop: https://stza.co/+vMNo-1U\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144504Z
LAST-MODIFIED:20180213T144504Z
TRANSP:OPAQUE
END:VEVENT
* Snappers @ Cubs
<2018-07-12 Thu 18:05-21:05>
:PROPERTIES:
:ID:       wQojFhKpM3-dY53u2Q5ndGfX@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Snappers @ Cubs Snappers @ Cubs

Follow on MiLB First Pitch  https //stza.co/+vMNp-3y

Shop  https //stza.co/+vMNp-x

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Snappers @ Cubs
END:VALARM
DTSTART:20180712T230500Z
DTEND:20180713T020500Z
UID:wQojFhKpM3-dY53u2Q5ndGfX@stanza.co
SUMMARY:Snappers @ Cubs
DESCRIPTION:Snappers @ Cubs\n\nFollow on MiLB First Pitch: https://stza.co/+vMNp-3y\n\nShop: https://stza.co/+vMNp-x\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144504Z
LAST-MODIFIED:20180213T144504Z
TRANSP:OPAQUE
END:VEVENT
* Snappers @ Cubs
<2018-07-13 Fri 18:35-21:35>
:PROPERTIES:
:ID:       yN6vUg_29Oswl6BEjoelZ3So@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Snappers @ Cubs Snappers @ Cubs

Follow on MiLB First Pitch  https //stza.co/+vMNq-3u

Shop  https //stza.co/+vMNq-1f

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Snappers @ Cubs
END:VALARM
DTSTART:20180713T233500Z
DTEND:20180714T023500Z
UID:yN6vUg_29Oswl6BEjoelZ3So@stanza.co
SUMMARY:Snappers @ Cubs
DESCRIPTION:Snappers @ Cubs\n\nFollow on MiLB First Pitch: https://stza.co/+vMNq-3u\n\nShop: https://stza.co/+vMNq-1f\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144504Z
LAST-MODIFIED:20180213T144504Z
TRANSP:OPAQUE
END:VEVENT
* Snappers @ Whitecaps
<2018-07-14 Sat 18:05-21:05>
:PROPERTIES:
:ID:       nbXy3yCT0JZI_lhH44EUTuqv@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Snappers @ Whitecaps Snappers @ Whitecaps

Follow on MiLB First Pitch  https //stza.co/+vMNr-2f

Shop  https //stza.co/+vMNr-3y

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Snappers @ Whitecaps
END:VALARM
DTSTART:20180714T230500Z
DTEND:20180715T020500Z
UID:nbXy3yCT0JZI_lhH44EUTuqv@stanza.co
SUMMARY:Snappers @ Whitecaps
DESCRIPTION:Snappers @ Whitecaps\n\nFollow on MiLB First Pitch: https://stza.co/+vMNr-2f\n\nShop: https://stza.co/+vMNr-3y\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144504Z
LAST-MODIFIED:20180213T144504Z
TRANSP:OPAQUE
END:VEVENT
* Snappers @ Whitecaps
<2018-07-15 Sun 13:00-16:00>
:PROPERTIES:
:ID:       WV7VqxD8sT7J5jdMt7fQh2Ee@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Snappers @ Whitecaps Snappers @ Whitecaps

Follow on MiLB First Pitch  https //stza.co/+vMNs-1x

Shop  https //stza.co/+vMNs-2p

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Snappers @ Whitecaps
END:VALARM
DTSTART:20180715T180000Z
DTEND:20180715T210000Z
UID:WV7VqxD8sT7J5jdMt7fQh2Ee@stanza.co
SUMMARY:Snappers @ Whitecaps
DESCRIPTION:Snappers @ Whitecaps\n\nFollow on MiLB First Pitch: https://stza.co/+vMNs-1x\n\nShop: https://stza.co/+vMNs-2p\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144504Z
LAST-MODIFIED:20180213T144504Z
TRANSP:OPAQUE
END:VEVENT
* Snappers @ Whitecaps
<2018-07-16 Mon 18:05-21:05>
:PROPERTIES:
:ID:       kBOsfEmWXUMTJFWJmkwDPm1X@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Snappers @ Whitecaps Snappers @ Whitecaps

Follow on MiLB First Pitch  https //stza.co/+vMNt-3v

Shop  https //stza.co/+vMNt-1R

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Snappers @ Whitecaps
END:VALARM
DTSTART:20180716T230500Z
DTEND:20180717T020500Z
UID:kBOsfEmWXUMTJFWJmkwDPm1X@stanza.co
SUMMARY:Snappers @ Whitecaps
DESCRIPTION:Snappers @ Whitecaps\n\nFollow on MiLB First Pitch: https://stza.co/+vMNt-3v\n\nShop: https://stza.co/+vMNt-1R\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144504Z
LAST-MODIFIED:20180213T144504Z
TRANSP:OPAQUE
END:VEVENT
* Snappers vs. Hot Rods
<2018-07-18 Wed 19:00-22:00>
:PROPERTIES:
:ID:       oseFIwGLmZ5kochl5LKIkMcy@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Snappers vs. Hot Rods Snappers vs. Hot Rods

Follow on MiLB First Pitch  https //stza.co/+wSJn-1x

Shop  https //stza.co/+wSJn-E

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Snappers vs. Hot Rods
END:VALARM
DTSTART:20180719T000000Z
DTEND:20180719T030000Z
UID:oseFIwGLmZ5kochl5LKIkMcy@stanza.co
SUMMARY:Snappers vs. Hot Rods
DESCRIPTION:Snappers vs. Hot Rods\n\nFollow on MiLB First Pitch: https://stza.co/+wSJn-1x\n\nShop: https://stza.co/+wSJn-E\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144504Z
LAST-MODIFIED:20180213T144504Z
TRANSP:OPAQUE
END:VEVENT
* Snappers vs. Hot Rods
<2018-07-19 Thu 19:00-22:00>
:PROPERTIES:
:ID:       XqNXX4mhcz3KESoSvCL5BNgE@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Snappers vs. Hot Rods Snappers vs. Hot Rods

Follow on MiLB First Pitch  https //stza.co/+wSJo-3m

Shop  https //stza.co/+wSJo-2H

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Snappers vs. Hot Rods
END:VALARM
DTSTART:20180720T000000Z
DTEND:20180720T030000Z
UID:XqNXX4mhcz3KESoSvCL5BNgE@stanza.co
SUMMARY:Snappers vs. Hot Rods
DESCRIPTION:Snappers vs. Hot Rods\n\nFollow on MiLB First Pitch: https://stza.co/+wSJo-3m\n\nShop: https://stza.co/+wSJo-2H\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144504Z
LAST-MODIFIED:20180213T144504Z
TRANSP:OPAQUE
END:VEVENT
* Snappers vs. Hot Rods
<2018-07-20 Fri 19:00-22:00>
:PROPERTIES:
:ID:       sZwq4wGctMmaUSv0T_0fzD_V@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Snappers vs. Hot Rods Snappers vs. Hot Rods

Follow on MiLB First Pitch  https //stza.co/+wSJr-2H

Shop  https //stza.co/+wSJr-3y

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Snappers vs. Hot Rods
END:VALARM
DTSTART:20180721T000000Z
DTEND:20180721T030000Z
UID:sZwq4wGctMmaUSv0T_0fzD_V@stanza.co
SUMMARY:Snappers vs. Hot Rods
DESCRIPTION:Snappers vs. Hot Rods\n\nFollow on MiLB First Pitch: https://stza.co/+wSJr-2H\n\nShop: https://stza.co/+wSJr-3y\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144504Z
LAST-MODIFIED:20180213T144504Z
TRANSP:OPAQUE
END:VEVENT
* Snappers vs. Dragons
<2018-07-21 Sat 19:00-22:00>
:PROPERTIES:
:ID:       Njgc3w0PFMXEpoatWjGjhwIn@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Snappers vs. Dragons Snappers vs. Dragons

Follow on MiLB First Pitch  https //stza.co/+wSJt-1u

Shop  https //stza.co/+wSJt-2X

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Snappers vs. Dragons
END:VALARM
DTSTART:20180722T000000Z
DTEND:20180722T030000Z
UID:Njgc3w0PFMXEpoatWjGjhwIn@stanza.co
SUMMARY:Snappers vs. Dragons
DESCRIPTION:Snappers vs. Dragons\n\nFollow on MiLB First Pitch: https://stza.co/+wSJt-1u\n\nShop: https://stza.co/+wSJt-2X\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144504Z
LAST-MODIFIED:20180213T144504Z
TRANSP:OPAQUE
END:VEVENT
* Snappers vs. Dragons
<2018-07-22 Sun 14:00-17:00>
:PROPERTIES:
:ID:       hs9xn02ovjLhwSqUMYFLyxio@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Snappers vs. Dragons Snappers vs. Dragons

Follow on MiLB First Pitch  https //stza.co/+wSJv-1t

Shop  https //stza.co/+wSJv-1k

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Snappers vs. Dragons
END:VALARM
DTSTART:20180722T190000Z
DTEND:20180722T220000Z
UID:hs9xn02ovjLhwSqUMYFLyxio@stanza.co
SUMMARY:Snappers vs. Dragons
DESCRIPTION:Snappers vs. Dragons\n\nFollow on MiLB First Pitch: https://stza.co/+wSJv-1t\n\nShop: https://stza.co/+wSJv-1k\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144504Z
LAST-MODIFIED:20180213T144504Z
TRANSP:OPAQUE
END:VEVENT
* Snappers vs. Dragons
<2018-07-23 Mon 12:00-15:00>
:PROPERTIES:
:ID:       6rK8ZmZ8RKps3mXq0kKaJtDk@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Snappers vs. Dragons Snappers vs. Dragons

Follow on MiLB First Pitch  https //stza.co/+wSJx-1F

Shop  https //stza.co/+wSJx-1s

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Snappers vs. Dragons
END:VALARM
DTSTART:20180723T170000Z
DTEND:20180723T200000Z
UID:6rK8ZmZ8RKps3mXq0kKaJtDk@stanza.co
SUMMARY:Snappers vs. Dragons
DESCRIPTION:Snappers vs. Dragons\n\nFollow on MiLB First Pitch: https://stza.co/+wSJx-1F\n\nShop: https://stza.co/+wSJx-1s\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144504Z
LAST-MODIFIED:20180213T144504Z
TRANSP:OPAQUE
END:VEVENT
* Snappers @ Cougars
<2018-07-25 Wed 12:00-15:00>
:PROPERTIES:
:ID:       sWJKbHFSM35twHkl9T9V3Xou@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Snappers @ Cougars Snappers @ Cougars

Follow on MiLB First Pitch  https //stza.co/+xBiG-l

Shop  https //stza.co/+xBiG-J

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Snappers @ Cougars
END:VALARM
DTSTART:20180725T170000Z
DTEND:20180725T200000Z
UID:sWJKbHFSM35twHkl9T9V3Xou@stanza.co
SUMMARY:Snappers @ Cougars
DESCRIPTION:Snappers @ Cougars\n\nFollow on MiLB First Pitch: https://stza.co/+xBiG-l\n\nShop: https://stza.co/+xBiG-J\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144504Z
LAST-MODIFIED:20180213T144504Z
TRANSP:OPAQUE
END:VEVENT
* Snappers @ Cougars
<2018-07-26 Thu 18:30-21:30>
:PROPERTIES:
:ID:       2r1JRC9ZQ6oHi4WWGjhLDoSL@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Snappers @ Cougars Snappers @ Cougars

Follow on MiLB First Pitch  https //stza.co/+xBiJ-r

Shop  https //stza.co/+xBiJ-1R

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Snappers @ Cougars
END:VALARM
DTSTART:20180726T233000Z
DTEND:20180727T023000Z
UID:2r1JRC9ZQ6oHi4WWGjhLDoSL@stanza.co
SUMMARY:Snappers @ Cougars
DESCRIPTION:Snappers @ Cougars\n\nFollow on MiLB First Pitch: https://stza.co/+xBiJ-r\n\nShop: https://stza.co/+xBiJ-1R\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144504Z
LAST-MODIFIED:20180213T144504Z
TRANSP:OPAQUE
END:VEVENT
* Snappers @ Cougars
<2018-07-27 Fri 18:30-21:30>
:PROPERTIES:
:ID:       LQu1MhK4cVfb22cSWHcSBXPY@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Snappers @ Cougars Snappers @ Cougars

Follow on MiLB First Pitch  https //stza.co/+xBiM-y

Shop  https //stza.co/+xBiM-1

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Snappers @ Cougars
END:VALARM
DTSTART:20180727T233000Z
DTEND:20180728T023000Z
UID:LQu1MhK4cVfb22cSWHcSBXPY@stanza.co
SUMMARY:Snappers @ Cougars
DESCRIPTION:Snappers @ Cougars\n\nFollow on MiLB First Pitch: https://stza.co/+xBiM-y\n\nShop: https://stza.co/+xBiM-1\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144504Z
LAST-MODIFIED:20180213T144504Z
TRANSP:OPAQUE
END:VEVENT
* Snappers @ Bees
<2018-07-28 Sat 18:30-21:30>
:PROPERTIES:
:ID:       48rT8xKiqo1HDWJKgE9z-Gyb@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Snappers @ Bees Snappers @ Bees

Follow on MiLB First Pitch  https //stza.co/+xBis-2A

Shop  https //stza.co/+xBis-J

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Snappers @ Bees
END:VALARM
DTSTART:20180728T233000Z
DTEND:20180729T023000Z
UID:48rT8xKiqo1HDWJKgE9z-Gyb@stanza.co
SUMMARY:Snappers @ Bees
DESCRIPTION:Snappers @ Bees\n\nFollow on MiLB First Pitch: https://stza.co/+xBis-2A\n\nShop: https://stza.co/+xBis-J\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144504Z
LAST-MODIFIED:20180213T144504Z
TRANSP:OPAQUE
END:VEVENT
* Snappers @ Bees
<2018-07-29 Sun 14:00-17:00>
:PROPERTIES:
:ID:       aVLOXQm2owZs7_r6enmc3uTt@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Snappers @ Bees Snappers @ Bees

Follow on MiLB First Pitch  https //stza.co/+xBit-1y

Shop  https //stza.co/+xBit-1Q

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Snappers @ Bees
END:VALARM
DTSTART:20180729T190000Z
DTEND:20180729T220000Z
UID:aVLOXQm2owZs7_r6enmc3uTt@stanza.co
SUMMARY:Snappers @ Bees
DESCRIPTION:Snappers @ Bees\n\nFollow on MiLB First Pitch: https://stza.co/+xBit-1y\n\nShop: https://stza.co/+xBit-1Q\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144504Z
LAST-MODIFIED:20180213T144504Z
TRANSP:OPAQUE
END:VEVENT
* Snappers @ Bees
<2018-07-30 Mon 18:30-21:30>
:PROPERTIES:
:ID:       6-8KA-3d6thMyqhWlsW-ePMM@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Snappers @ Bees Snappers @ Bees

Follow on MiLB First Pitch  https //stza.co/+xBiu-16

Shop  https //stza.co/+xBiu-1l

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Snappers @ Bees
END:VALARM
DTSTART:20180730T233000Z
DTEND:20180731T023000Z
UID:6-8KA-3d6thMyqhWlsW-ePMM@stanza.co
SUMMARY:Snappers @ Bees
DESCRIPTION:Snappers @ Bees\n\nFollow on MiLB First Pitch: https://stza.co/+xBiu-16\n\nShop: https://stza.co/+xBiu-1l\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144504Z
LAST-MODIFIED:20180213T144504Z
TRANSP:OPAQUE
END:VEVENT
* Snappers @ Bees
<2018-07-31 Tue 18:30-21:30>
:PROPERTIES:
:ID:       d8sWRNeWXP11YLT-DlOxyHmR@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Snappers @ Bees Snappers @ Bees

Follow on MiLB First Pitch  https //stza.co/+xBiv-V

Shop  https //stza.co/+xBiv-37

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Snappers @ Bees
END:VALARM
DTSTART:20180731T233000Z
DTEND:20180801T023000Z
UID:d8sWRNeWXP11YLT-DlOxyHmR@stanza.co
SUMMARY:Snappers @ Bees
DESCRIPTION:Snappers @ Bees\n\nFollow on MiLB First Pitch: https://stza.co/+xBiv-V\n\nShop: https://stza.co/+xBiv-37\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144504Z
LAST-MODIFIED:20180213T144504Z
TRANSP:OPAQUE
END:VEVENT
* Snappers vs. Cougars
<2018-08-01 Wed 19:00-22:00>
:PROPERTIES:
:ID:       geUAh5pHQAodW1EUbPJ_ycmT@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Snappers vs. Cougars Snappers vs. Cougars

Follow on MiLB First Pitch  https //stza.co/+wSJA-1f

Shop  https //stza.co/+wSJA-1u

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Snappers vs. Cougars
END:VALARM
DTSTART:20180802T000000Z
DTEND:20180802T030000Z
UID:geUAh5pHQAodW1EUbPJ_ycmT@stanza.co
SUMMARY:Snappers vs. Cougars
DESCRIPTION:Snappers vs. Cougars\n\nFollow on MiLB First Pitch: https://stza.co/+wSJA-1f\n\nShop: https://stza.co/+wSJA-1u\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144504Z
LAST-MODIFIED:20180213T144504Z
TRANSP:OPAQUE
END:VEVENT
* Snappers vs. Cougars
<2018-08-02 Thu 19:00-22:00>
:PROPERTIES:
:ID:       twHGASebz_ryW_yJe-DBpcg2@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Snappers vs. Cougars Snappers vs. Cougars

Follow on MiLB First Pitch  https //stza.co/+wSJC-10

Shop  https //stza.co/+wSJC-3G

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Snappers vs. Cougars
END:VALARM
DTSTART:20180803T000000Z
DTEND:20180803T030000Z
UID:twHGASebz_ryW_yJe-DBpcg2@stanza.co
SUMMARY:Snappers vs. Cougars
DESCRIPTION:Snappers vs. Cougars\n\nFollow on MiLB First Pitch: https://stza.co/+wSJC-10\n\nShop: https://stza.co/+wSJC-3G\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144504Z
LAST-MODIFIED:20180213T144504Z
TRANSP:OPAQUE
END:VEVENT
* Snappers vs. Cougars
<2018-08-03 Fri 19:00-22:00>
:PROPERTIES:
:ID:       _ybhV-g-y0WI9t1Ew--JDADK@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Snappers vs. Cougars Snappers vs. Cougars

Follow on MiLB First Pitch  https //stza.co/+wSJE-3C

Shop  https //stza.co/+wSJE-2_

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Snappers vs. Cougars
END:VALARM
DTSTART:20180804T000000Z
DTEND:20180804T030000Z
UID:_ybhV-g-y0WI9t1Ew--JDADK@stanza.co
SUMMARY:Snappers vs. Cougars
DESCRIPTION:Snappers vs. Cougars\n\nFollow on MiLB First Pitch: https://stza.co/+wSJE-3C\n\nShop: https://stza.co/+wSJE-2_\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144504Z
LAST-MODIFIED:20180213T144504Z
TRANSP:OPAQUE
END:VEVENT
* Snappers @ Kernels
<2018-08-04 Sat 18:35-21:35>
:PROPERTIES:
:ID:       QB8SqzTLEqz9CuGYOiWY0J7V@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Snappers @ Kernels Snappers @ Kernels

Buy tickets here  https //stza.co/~vMMP

Follow on MiLB First Pitch  https //stza.co/+vMMP-3C

Shop  https //stza.co/+vMMP-1W

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Snappers @ Kernels
END:VALARM
DTSTART:20180804T233500Z
DTEND:20180805T023500Z
UID:QB8SqzTLEqz9CuGYOiWY0J7V@stanza.co
SUMMARY:Snappers @ Kernels
DESCRIPTION:Snappers @ Kernels\n\nBuy tickets here: https://stza.co/~vMMP\n\nFollow on MiLB First Pitch: https://stza.co/+vMMP-3C\n\nShop: https://stza.co/+vMMP-1W\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144504Z
LAST-MODIFIED:20180213T144504Z
TRANSP:OPAQUE
END:VEVENT
* Snappers @ Kernels
<2018-08-05 Sun 14:05-17:05>
:PROPERTIES:
:ID:       -EbSuaHZtkCelgzggK6tLNKU@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Snappers @ Kernels Snappers @ Kernels

Buy tickets here  https //stza.co/~vMMQ

Follow on MiLB First Pitch  https //stza.co/+vMMQ-7

Shop  https //stza.co/+vMMQ-5

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Snappers @ Kernels
END:VALARM
DTSTART:20180805T190500Z
DTEND:20180805T220500Z
UID:-EbSuaHZtkCelgzggK6tLNKU@stanza.co
SUMMARY:Snappers @ Kernels
DESCRIPTION:Snappers @ Kernels\n\nBuy tickets here: https://stza.co/~vMMQ\n\nFollow on MiLB First Pitch: https://stza.co/+vMMQ-7\n\nShop: https://stza.co/+vMMQ-5\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144504Z
LAST-MODIFIED:20180213T144504Z
TRANSP:OPAQUE
END:VEVENT
* Snappers @ Kernels
<2018-08-06 Mon 12:05-15:05>
:PROPERTIES:
:ID:       RMOy4tsQbJaFX5BYlENVOYFo@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Snappers @ Kernels Snappers @ Kernels

Buy tickets here  https //stza.co/~w0NN

Follow on MiLB First Pitch  https //stza.co/+w0NN-Z

Shop  https //stza.co/+w0NN-27

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Snappers @ Kernels
END:VALARM
DTSTART:20180806T170500Z
DTEND:20180806T200500Z
UID:RMOy4tsQbJaFX5BYlENVOYFo@stanza.co
SUMMARY:Snappers @ Kernels
DESCRIPTION:Snappers @ Kernels\n\nBuy tickets here: https://stza.co/~w0NN\n\nFollow on MiLB First Pitch: https://stza.co/+w0NN-Z\n\nShop: https://stza.co/+w0NN-27\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144504Z
LAST-MODIFIED:20180213T144504Z
TRANSP:OPAQUE
END:VEVENT
* Snappers vs. River Bandits
<2018-08-08 Wed 19:00-22:00>
:PROPERTIES:
:ID:       04wTSUk63-1AqjcK_QQBbbD0@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Snappers vs. River Bandits Snappers vs. River Bandits

Follow on MiLB First Pitch  https //stza.co/+wSJG-z

Shop  https //stza.co/+wSJG-_

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Snappers vs. River Bandits
END:VALARM
DTSTART:20180809T000000Z
DTEND:20180809T030000Z
UID:04wTSUk63-1AqjcK_QQBbbD0@stanza.co
SUMMARY:Snappers vs. River Bandits
DESCRIPTION:Snappers vs. River Bandits\n\nFollow on MiLB First Pitch: https://stza.co/+wSJG-z\n\nShop: https://stza.co/+wSJG-_\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144504Z
LAST-MODIFIED:20180213T144504Z
TRANSP:OPAQUE
END:VEVENT
* Snappers vs. River Bandits
<2018-08-09 Thu 19:00-22:00>
:PROPERTIES:
:ID:       ILhdM_dns3V1Ip9Is0WlPUnR@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Snappers vs. River Bandits Snappers vs. River Bandits

Follow on MiLB First Pitch  https //stza.co/+wSJH-1D

Shop  https //stza.co/+wSJH-X

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Snappers vs. River Bandits
END:VALARM
DTSTART:20180810T000000Z
DTEND:20180810T030000Z
UID:ILhdM_dns3V1Ip9Is0WlPUnR@stanza.co
SUMMARY:Snappers vs. River Bandits
DESCRIPTION:Snappers vs. River Bandits\n\nFollow on MiLB First Pitch: https://stza.co/+wSJH-1D\n\nShop: https://stza.co/+wSJH-X\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144504Z
LAST-MODIFIED:20180213T144504Z
TRANSP:OPAQUE
END:VEVENT
* Snappers vs. River Bandits
<2018-08-10 Fri 19:00-22:00>
:PROPERTIES:
:ID:       _Gj7YYD1e-wwYGh2L-ieLP5e@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Snappers vs. River Bandits Snappers vs. River Bandits

Follow on MiLB First Pitch  https //stza.co/+wSJJ-2r

Shop  https //stza.co/+wSJJ-3L

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Snappers vs. River Bandits
END:VALARM
DTSTART:20180811T000000Z
DTEND:20180811T030000Z
UID:_Gj7YYD1e-wwYGh2L-ieLP5e@stanza.co
SUMMARY:Snappers vs. River Bandits
DESCRIPTION:Snappers vs. River Bandits\n\nFollow on MiLB First Pitch: https://stza.co/+wSJJ-2r\n\nShop: https://stza.co/+wSJJ-3L\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144504Z
LAST-MODIFIED:20180213T144504Z
TRANSP:OPAQUE
END:VEVENT
* Snappers vs. Timber Rattlers
<2018-08-11 Sat 19:00-22:00>
:PROPERTIES:
:ID:       9lfC7rc9xbTD1CJNznXaJMdA@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Snappers vs. Timber Rattlers Snappers vs. Timber Rattlers

Follow on MiLB First Pitch  https //stza.co/+wSJL-3k

Shop  https //stza.co/+wSJL-M

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Snappers vs. Timber Rattlers
END:VALARM
DTSTART:20180812T000000Z
DTEND:20180812T030000Z
UID:9lfC7rc9xbTD1CJNznXaJMdA@stanza.co
SUMMARY:Snappers vs. Timber Rattlers
DESCRIPTION:Snappers vs. Timber Rattlers\n\nFollow on MiLB First Pitch: https://stza.co/+wSJL-3k\n\nShop: https://stza.co/+wSJL-M\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144504Z
LAST-MODIFIED:20180213T144504Z
TRANSP:OPAQUE
END:VEVENT
* Snappers vs. Timber Rattlers
<2018-08-12 Sun 14:00-17:00>
:PROPERTIES:
:ID:       kHfMZtf7x8jAluO4lMXnwNWf@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Snappers vs. Timber Rattlers Snappers vs. Timber Rattlers

Follow on MiLB First Pitch  https //stza.co/+wSJN-28

Shop  https //stza.co/+wSJN-2V

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Snappers vs. Timber Rattlers
END:VALARM
DTSTART:20180812T190000Z
DTEND:20180812T220000Z
UID:kHfMZtf7x8jAluO4lMXnwNWf@stanza.co
SUMMARY:Snappers vs. Timber Rattlers
DESCRIPTION:Snappers vs. Timber Rattlers\n\nFollow on MiLB First Pitch: https://stza.co/+wSJN-28\n\nShop: https://stza.co/+wSJN-2V\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144504Z
LAST-MODIFIED:20180213T144504Z
TRANSP:OPAQUE
END:VEVENT
* Snappers vs. Timber Rattlers
<2018-08-13 Mon 19:00-22:00>
:PROPERTIES:
:ID:       PeAit685FdRjSEFvKVXxNehf@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Snappers vs. Timber Rattlers Snappers vs. Timber Rattlers

Follow on MiLB First Pitch  https //stza.co/+wSJP-3u

Shop  https //stza.co/+wSJP-2g

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Snappers vs. Timber Rattlers
END:VALARM
DTSTART:20180814T000000Z
DTEND:20180814T030000Z
UID:PeAit685FdRjSEFvKVXxNehf@stanza.co
SUMMARY:Snappers vs. Timber Rattlers
DESCRIPTION:Snappers vs. Timber Rattlers\n\nFollow on MiLB First Pitch: https://stza.co/+wSJP-3u\n\nShop: https://stza.co/+wSJP-2g\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144504Z
LAST-MODIFIED:20180213T144504Z
TRANSP:OPAQUE
END:VEVENT
* Snappers vs. Timber Rattlers
<2018-08-14 Tue 19:00-22:00>
:PROPERTIES:
:ID:       JDsk3DFBvmtu5gXY1CIcF482@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Snappers vs. Timber Rattlers Snappers vs. Timber Rattlers

Follow on MiLB First Pitch  https //stza.co/+wSJS-1L

Shop  https //stza.co/+wSJS-3S

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Snappers vs. Timber Rattlers
END:VALARM
DTSTART:20180815T000000Z
DTEND:20180815T030000Z
UID:JDsk3DFBvmtu5gXY1CIcF482@stanza.co
SUMMARY:Snappers vs. Timber Rattlers
DESCRIPTION:Snappers vs. Timber Rattlers\n\nFollow on MiLB First Pitch: https://stza.co/+wSJS-1L\n\nShop: https://stza.co/+wSJS-3S\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144504Z
LAST-MODIFIED:20180213T144504Z
TRANSP:OPAQUE
END:VEVENT
* Snappers @ LumberKings
<2018-08-15 Wed 18:30-21:30>
:PROPERTIES:
:ID:       3g_ujlpApVWHsqLEwcpn_E6M@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Snappers @ LumberKings Snappers @ LumberKings

Follow on MiLB First Pitch  https //stza.co/+vMMV-2U

Shop  https //stza.co/+vMMV-3P

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Snappers @ LumberKings
END:VALARM
DTSTART:20180815T233000Z
DTEND:20180816T023000Z
UID:3g_ujlpApVWHsqLEwcpn_E6M@stanza.co
SUMMARY:Snappers @ LumberKings
DESCRIPTION:Snappers @ LumberKings\n\nFollow on MiLB First Pitch: https://stza.co/+vMMV-2U\n\nShop: https://stza.co/+vMMV-3P\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144504Z
LAST-MODIFIED:20180213T144504Z
TRANSP:OPAQUE
END:VEVENT
* Snappers @ LumberKings
<2018-08-16 Thu 18:30-21:30>
:PROPERTIES:
:ID:       TvLoWYu00MyP-08jDkFKcyTq@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Snappers @ LumberKings Snappers @ LumberKings

Follow on MiLB First Pitch  https //stza.co/+vMMW-Y

Shop  https //stza.co/+vMMW-3c

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Snappers @ LumberKings
END:VALARM
DTSTART:20180816T233000Z
DTEND:20180817T023000Z
UID:TvLoWYu00MyP-08jDkFKcyTq@stanza.co
SUMMARY:Snappers @ LumberKings
DESCRIPTION:Snappers @ LumberKings\n\nFollow on MiLB First Pitch: https://stza.co/+vMMW-Y\n\nShop: https://stza.co/+vMMW-3c\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144504Z
LAST-MODIFIED:20180213T144504Z
TRANSP:OPAQUE
END:VEVENT
* Snappers @ LumberKings
<2018-08-17 Fri 18:30-21:30>
:PROPERTIES:
:ID:       JvXE92lRZYNZivvpSOq2oM50@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Snappers @ LumberKings Snappers @ LumberKings

Follow on MiLB First Pitch  https //stza.co/+vMMX-3d

Shop  https //stza.co/+vMMX-1Y

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Snappers @ LumberKings
END:VALARM
DTSTART:20180817T233000Z
DTEND:20180818T023000Z
UID:JvXE92lRZYNZivvpSOq2oM50@stanza.co
SUMMARY:Snappers @ LumberKings
DESCRIPTION:Snappers @ LumberKings\n\nFollow on MiLB First Pitch: https://stza.co/+vMMX-3d\n\nShop: https://stza.co/+vMMX-1Y\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144504Z
LAST-MODIFIED:20180213T144504Z
TRANSP:OPAQUE
END:VEVENT
* Snappers vs. Bees
<2018-08-18 Sat 19:00-22:00>
:PROPERTIES:
:ID:       mzqZ8H8rsN79OGU-mVi_HGdc@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Snappers vs. Bees Snappers vs. Bees

Follow on MiLB First Pitch  https //stza.co/+wSJU-o

Shop  https //stza.co/+wSJU-3e

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Snappers vs. Bees
END:VALARM
DTSTART:20180819T000000Z
DTEND:20180819T030000Z
UID:mzqZ8H8rsN79OGU-mVi_HGdc@stanza.co
SUMMARY:Snappers vs. Bees
DESCRIPTION:Snappers vs. Bees\n\nFollow on MiLB First Pitch: https://stza.co/+wSJU-o\n\nShop: https://stza.co/+wSJU-3e\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144504Z
LAST-MODIFIED:20180213T144504Z
TRANSP:OPAQUE
END:VEVENT
* Snappers vs. Bees
<2018-08-19 Sun 14:00-17:00>
:PROPERTIES:
:ID:       b_doyUgDx6Fqqdlzh8QAXSls@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Snappers vs. Bees Snappers vs. Bees

Follow on MiLB First Pitch  https //stza.co/+wSJW-3v

Shop  https //stza.co/+wSJW-3Y

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Snappers vs. Bees
END:VALARM
DTSTART:20180819T190000Z
DTEND:20180819T220000Z
UID:b_doyUgDx6Fqqdlzh8QAXSls@stanza.co
SUMMARY:Snappers vs. Bees
DESCRIPTION:Snappers vs. Bees\n\nFollow on MiLB First Pitch: https://stza.co/+wSJW-3v\n\nShop: https://stza.co/+wSJW-3Y\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144504Z
LAST-MODIFIED:20180213T144504Z
TRANSP:OPAQUE
END:VEVENT
* Snappers vs. Bees
<2018-08-20 Mon 19:00-22:00>
:PROPERTIES:
:ID:       4e0ifHEkCWThRCchEf5l6pcn@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Snappers vs. Bees Snappers vs. Bees

Follow on MiLB First Pitch  https //stza.co/+wSJX-26

Shop  https //stza.co/+wSJX-1W

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Snappers vs. Bees
END:VALARM
DTSTART:20180821T000000Z
DTEND:20180821T030000Z
UID:4e0ifHEkCWThRCchEf5l6pcn@stanza.co
SUMMARY:Snappers vs. Bees
DESCRIPTION:Snappers vs. Bees\n\nFollow on MiLB First Pitch: https://stza.co/+wSJX-26\n\nShop: https://stza.co/+wSJX-1W\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144504Z
LAST-MODIFIED:20180213T144504Z
TRANSP:OPAQUE
END:VEVENT
* Snappers vs. Kernels
<2018-08-21 Tue 19:00-22:00>
:PROPERTIES:
:ID:       nSbymVd__INukHpskhEhrDMD@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Snappers vs. Kernels Snappers vs. Kernels

Follow on MiLB First Pitch  https //stza.co/+wSJ_-b

Shop  https //stza.co/+wSJ_-11

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Snappers vs. Kernels
END:VALARM
DTSTART:20180822T000000Z
DTEND:20180822T030000Z
UID:nSbymVd__INukHpskhEhrDMD@stanza.co
SUMMARY:Snappers vs. Kernels
DESCRIPTION:Snappers vs. Kernels\n\nFollow on MiLB First Pitch: https://stza.co/+wSJ_-b\n\nShop: https://stza.co/+wSJ_-11\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144504Z
LAST-MODIFIED:20180213T144504Z
TRANSP:OPAQUE
END:VEVENT
* Snappers vs. Kernels
<2018-08-22 Wed 19:00-22:00>
:PROPERTIES:
:ID:       uMJVLY1XBLxqHzQ9XpbvH1Fu@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Snappers vs. Kernels Snappers vs. Kernels

Follow on MiLB First Pitch  https //stza.co/+wSK0-1H

Shop  https //stza.co/+wSK0-21

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Snappers vs. Kernels
END:VALARM
DTSTART:20180823T000000Z
DTEND:20180823T030000Z
UID:uMJVLY1XBLxqHzQ9XpbvH1Fu@stanza.co
SUMMARY:Snappers vs. Kernels
DESCRIPTION:Snappers vs. Kernels\n\nFollow on MiLB First Pitch: https://stza.co/+wSK0-1H\n\nShop: https://stza.co/+wSK0-21\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144504Z
LAST-MODIFIED:20180213T144504Z
TRANSP:OPAQUE
END:VEVENT
* Snappers vs. Kernels
<2018-08-23 Thu 19:00-22:00>
:PROPERTIES:
:ID:       X7ShGGW3I7OMLEGcUF_z69Du@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Snappers vs. Kernels Snappers vs. Kernels

Follow on MiLB First Pitch  https //stza.co/+wSK2-3G

Shop  https //stza.co/+wSK2-3H

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Snappers vs. Kernels
END:VALARM
DTSTART:20180824T000000Z
DTEND:20180824T030000Z
UID:X7ShGGW3I7OMLEGcUF_z69Du@stanza.co
SUMMARY:Snappers vs. Kernels
DESCRIPTION:Snappers vs. Kernels\n\nFollow on MiLB First Pitch: https://stza.co/+wSK2-3G\n\nShop: https://stza.co/+wSK2-3H\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144504Z
LAST-MODIFIED:20180213T144504Z
TRANSP:OPAQUE
END:VEVENT
* Snappers @ Chiefs
<2018-08-24 Fri 18:30-21:30>
:PROPERTIES:
:ID:       T7dCml3bIdxWGprvdD-tDv9a@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Snappers @ Chiefs Snappers @ Chiefs

Follow on MiLB First Pitch  https //stza.co/+xAnT-34

Shop  https //stza.co/+xAnT-39

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Snappers @ Chiefs
END:VALARM
DTSTART:20180824T233000Z
DTEND:20180825T023000Z
UID:T7dCml3bIdxWGprvdD-tDv9a@stanza.co
SUMMARY:Snappers @ Chiefs
DESCRIPTION:Snappers @ Chiefs\n\nFollow on MiLB First Pitch: https://stza.co/+xAnT-34\n\nShop: https://stza.co/+xAnT-39\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144504Z
LAST-MODIFIED:20180213T144504Z
TRANSP:OPAQUE
END:VEVENT
* Snappers @ Chiefs
<2018-08-25 Sat 18:30-21:30>
:PROPERTIES:
:ID:       dV6uNPqTX9BlaZIAOeQjs8-d@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Snappers @ Chiefs Snappers @ Chiefs

Follow on MiLB First Pitch  https //stza.co/+xAnU-11

Shop  https //stza.co/+xAnU-31

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Snappers @ Chiefs
END:VALARM
DTSTART:20180825T233000Z
DTEND:20180826T023000Z
UID:dV6uNPqTX9BlaZIAOeQjs8-d@stanza.co
SUMMARY:Snappers @ Chiefs
DESCRIPTION:Snappers @ Chiefs\n\nFollow on MiLB First Pitch: https://stza.co/+xAnU-11\n\nShop: https://stza.co/+xAnU-31\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144504Z
LAST-MODIFIED:20180213T144504Z
TRANSP:OPAQUE
END:VEVENT
* Snappers @ Chiefs
<2018-08-26 Sun 14:00-17:00>
:PROPERTIES:
:ID:       dMWLhFDTRddPXmxkqcJqRpYY@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Snappers @ Chiefs Snappers @ Chiefs

Follow on MiLB First Pitch  https //stza.co/+xAnV-8

Shop  https //stza.co/+xAnV-X

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Snappers @ Chiefs
END:VALARM
DTSTART:20180826T190000Z
DTEND:20180826T220000Z
UID:dMWLhFDTRddPXmxkqcJqRpYY@stanza.co
SUMMARY:Snappers @ Chiefs
DESCRIPTION:Snappers @ Chiefs\n\nFollow on MiLB First Pitch: https://stza.co/+xAnV-8\n\nShop: https://stza.co/+xAnV-X\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144504Z
LAST-MODIFIED:20180213T144504Z
TRANSP:OPAQUE
END:VEVENT
* Snappers @ Chiefs
<2018-08-27 Mon 18:30-21:30>
:PROPERTIES:
:ID:       ecFLswxFIMUDOtYcgj6kqFde@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Snappers @ Chiefs Snappers @ Chiefs

Follow on MiLB First Pitch  https //stza.co/+xAnW-3J

Shop  https //stza.co/+xAnW-3w

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Snappers @ Chiefs
END:VALARM
DTSTART:20180827T233000Z
DTEND:20180828T023000Z
UID:ecFLswxFIMUDOtYcgj6kqFde@stanza.co
SUMMARY:Snappers @ Chiefs
DESCRIPTION:Snappers @ Chiefs\n\nFollow on MiLB First Pitch: https://stza.co/+xAnW-3J\n\nShop: https://stza.co/+xAnW-3w\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144504Z
LAST-MODIFIED:20180213T144504Z
TRANSP:OPAQUE
END:VEVENT
* Snappers @ Timber Rattlers
<2018-08-29 Wed 19:05-22:05>
:PROPERTIES:
:ID:       _S6UBfJgwrFYEkXrnWMcfY1c@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Snappers @ Timber Rattlers Snappers @ Timber Rattlers

Follow on MiLB First Pitch  https //stza.co/+vMNA-21

Shop  https //stza.co/+vMNA-g

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Snappers @ Timber Rattlers
END:VALARM
DTSTART:20180830T000500Z
DTEND:20180830T030500Z
UID:_S6UBfJgwrFYEkXrnWMcfY1c@stanza.co
SUMMARY:Snappers @ Timber Rattlers
DESCRIPTION:Snappers @ Timber Rattlers\n\nFollow on MiLB First Pitch: https://stza.co/+vMNA-21\n\nShop: https://stza.co/+vMNA-g\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144504Z
LAST-MODIFIED:20180213T144504Z
TRANSP:OPAQUE
END:VEVENT
* Snappers @ Timber Rattlers
<2018-08-30 Thu 19:05-22:05>
:PROPERTIES:
:ID:       0v34RnNhE0oZr_3XCM3uKXTf@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Snappers @ Timber Rattlers Snappers @ Timber Rattlers

Follow on MiLB First Pitch  https //stza.co/+vnG6-3y

Shop  https //stza.co/+vnG6-13

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Snappers @ Timber Rattlers
END:VALARM
DTSTART:20180831T000500Z
DTEND:20180831T030500Z
UID:0v34RnNhE0oZr_3XCM3uKXTf@stanza.co
SUMMARY:Snappers @ Timber Rattlers
DESCRIPTION:Snappers @ Timber Rattlers\n\nFollow on MiLB First Pitch: https://stza.co/+vnG6-3y\n\nShop: https://stza.co/+vnG6-13\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144504Z
LAST-MODIFIED:20180213T144504Z
TRANSP:OPAQUE
END:VEVENT
* Snappers @ Timber Rattlers
<2018-08-31 Fri 19:05-22:05>
:PROPERTIES:
:ID:       RHKLvW4W2zsv7t3OKRRMCVOK@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Snappers @ Timber Rattlers Snappers @ Timber Rattlers

Follow on MiLB First Pitch  https //stza.co/+vnGi-2E

Shop  https //stza.co/+vnGi-1e

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Snappers @ Timber Rattlers
END:VALARM
DTSTART:20180901T000500Z
DTEND:20180901T030500Z
UID:RHKLvW4W2zsv7t3OKRRMCVOK@stanza.co
SUMMARY:Snappers @ Timber Rattlers
DESCRIPTION:Snappers @ Timber Rattlers\n\nFollow on MiLB First Pitch: https://stza.co/+vnGi-2E\n\nShop: https://stza.co/+vnGi-1e\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144504Z
LAST-MODIFIED:20180213T144504Z
TRANSP:OPAQUE
END:VEVENT
* Snappers vs. Kernels
<2018-09-01 Sat 19:00-22:00>
:PROPERTIES:
:ID:       _zZ1UQK4AEJZ5DdyGt8gcb9w@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Snappers vs. Kernels Snappers vs. Kernels

Follow on MiLB First Pitch  https //stza.co/+wSK3-1h

Shop  https //stza.co/+wSK3-2A

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Snappers vs. Kernels
END:VALARM
DTSTART:20180902T000000Z
DTEND:20180902T030000Z
UID:_zZ1UQK4AEJZ5DdyGt8gcb9w@stanza.co
SUMMARY:Snappers vs. Kernels
DESCRIPTION:Snappers vs. Kernels\n\nFollow on MiLB First Pitch: https://stza.co/+wSK3-1h\n\nShop: https://stza.co/+wSK3-2A\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144504Z
LAST-MODIFIED:20180213T144504Z
TRANSP:OPAQUE
END:VEVENT
* Snappers vs. Kernels
<2018-09-02 Sun 14:00-17:00>
:PROPERTIES:
:ID:       mbF5R1vmSyGGolZUgbRpo2vj@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Snappers vs. Kernels Snappers vs. Kernels

Follow on MiLB First Pitch  https //stza.co/+wSK6-3P

Shop  https //stza.co/+wSK6-k

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Snappers vs. Kernels
END:VALARM
DTSTART:20180902T190000Z
DTEND:20180902T220000Z
UID:mbF5R1vmSyGGolZUgbRpo2vj@stanza.co
SUMMARY:Snappers vs. Kernels
DESCRIPTION:Snappers vs. Kernels\n\nFollow on MiLB First Pitch: https://stza.co/+wSK6-3P\n\nShop: https://stza.co/+wSK6-k\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144504Z
LAST-MODIFIED:20180213T144504Z
TRANSP:OPAQUE
END:VEVENT
* Snappers vs. Kernels
<2018-09-03 Mon 14:00-17:00>
:PROPERTIES:
:ID:       Mjm8Oxvyy778_n8kLfuvj6_9@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Snappers vs. Kernels Snappers vs. Kernels

Follow on MiLB First Pitch  https //stza.co/+wSK7-3l

Shop  https //stza.co/+wSK7-1n

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Snappers vs. Kernels
END:VALARM
DTSTART:20180903T190000Z
DTEND:20180903T220000Z
UID:Mjm8Oxvyy778_n8kLfuvj6_9@stanza.co
SUMMARY:Snappers vs. Kernels
DESCRIPTION:Snappers vs. Kernels\n\nFollow on MiLB First Pitch: https://stza.co/+wSK7-3l\n\nShop: https://stza.co/+wSK7-1n\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144504Z
LAST-MODIFIED:20180213T144504Z
TRANSP:OPAQUE
END:VEVENT
