#+TITLE:       Main Google calendar entries
#+AUTHOR:      Eric S Fraga
#+EMAIL:       e.fraga@ucl.ac.uk
#+DESCRIPTION: converted using the ical2org awk script
#+CATEGORY:    google
#+STARTUP:     hidestars
#+STARTUP:     overview

* COMMENT original iCal preamble

* Knights vs. White Sox
<2018-03-26 Mon 17:05-20:05>
:PROPERTIES:
:ID:       -884Uyzzjp3C1NoQWFip9fs7@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Knights vs. White Sox Knights vs. White Sox

Follow on MiLB First Pitch  https //stza.co/+wCB_-l

Shop  https //stza.co/+wCB_-1a

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Knights vs. White Sox
END:VALARM
DTSTART:20180326T220500Z
DTEND:20180327T010500Z
UID:-884Uyzzjp3C1NoQWFip9fs7@stanza.co
SUMMARY:Knights vs. White Sox
DESCRIPTION:Knights vs. White Sox\n\nFollow on MiLB First Pitch: https://stza.co/+wCB_-l\n\nShop: https://stza.co/+wCB_-1a\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144512Z
LAST-MODIFIED:20180213T144512Z
TRANSP:OPAQUE
END:VEVENT
* Knights @ Bulls
<2018-04-05 Thu 17:05-20:05>
:PROPERTIES:
:ID:       o3t8Xob8KAntOIb3eWa4wGqf@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Knights @ Bulls Knights @ Bulls

Follow on MiLB First Pitch  https //stza.co/+vK4Z-28

Shop  https //stza.co/+vK4Z-3v

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Knights @ Bulls
END:VALARM
DTSTART:20180405T220500Z
DTEND:20180406T010500Z
UID:o3t8Xob8KAntOIb3eWa4wGqf@stanza.co
SUMMARY:Knights @ Bulls
DESCRIPTION:Knights @ Bulls\n\nFollow on MiLB First Pitch: https://stza.co/+vK4Z-28\n\nShop: https://stza.co/+vK4Z-3v\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144512Z
LAST-MODIFIED:20180213T144512Z
TRANSP:OPAQUE
END:VEVENT
* Knights @ Bulls
<2018-04-06 Fri 18:05-21:05>
:PROPERTIES:
:ID:       onMAHn5pFCybncztX-N6HV5Q@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Knights @ Bulls Knights @ Bulls

Follow on MiLB First Pitch  https //stza.co/+vK4_-1o

Shop  https //stza.co/+vK4_-1E

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Knights @ Bulls
END:VALARM
DTSTART:20180406T230500Z
DTEND:20180407T020500Z
UID:onMAHn5pFCybncztX-N6HV5Q@stanza.co
SUMMARY:Knights @ Bulls
DESCRIPTION:Knights @ Bulls\n\nFollow on MiLB First Pitch: https://stza.co/+vK4_-1o\n\nShop: https://stza.co/+vK4_-1E\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144512Z
LAST-MODIFIED:20180213T144512Z
TRANSP:OPAQUE
END:VEVENT
* Knights @ Bulls
<2018-04-07 Sat 17:35-20:35>
:PROPERTIES:
:ID:       -Ct0DKKX97NMVYQ3-lkKAcEz@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Knights @ Bulls Knights @ Bulls

Follow on MiLB First Pitch  https //stza.co/+vK4$-14

Shop  https //stza.co/+vK4$-1T

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Knights @ Bulls
END:VALARM
DTSTART:20180407T223500Z
DTEND:20180408T013500Z
UID:-Ct0DKKX97NMVYQ3-lkKAcEz@stanza.co
SUMMARY:Knights @ Bulls
DESCRIPTION:Knights @ Bulls\n\nFollow on MiLB First Pitch: https://stza.co/+vK4$-14\n\nShop: https://stza.co/+vK4$-1T\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144512Z
LAST-MODIFIED:20180213T144512Z
TRANSP:OPAQUE
END:VEVENT
* Knights @ Bulls
<2018-04-08 Sun 16:05-19:05>
:PROPERTIES:
:ID:       q87vSHc08YL8Oa6IoiOp7Fx-@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Knights @ Bulls Knights @ Bulls

Follow on MiLB First Pitch  https //stza.co/+vK50-1g

Shop  https //stza.co/+vK50-2k

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Knights @ Bulls
END:VALARM
DTSTART:20180408T210500Z
DTEND:20180409T000500Z
UID:q87vSHc08YL8Oa6IoiOp7Fx-@stanza.co
SUMMARY:Knights @ Bulls
DESCRIPTION:Knights @ Bulls\n\nFollow on MiLB First Pitch: https://stza.co/+vK50-1g\n\nShop: https://stza.co/+vK50-2k\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144512Z
LAST-MODIFIED:20180213T144512Z
TRANSP:OPAQUE
END:VEVENT
* Knights @ Tides
<2018-04-09 Mon 17:35-20:35>
:PROPERTIES:
:ID:       f5HNbA_G17Eg6atDrdk59gNy@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Knights @ Tides Knights @ Tides

Follow on MiLB First Pitch  https //stza.co/+vK5u-2t

Shop  https //stza.co/+vK5u-3A

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Knights @ Tides
END:VALARM
DTSTART:20180409T223500Z
DTEND:20180410T013500Z
UID:f5HNbA_G17Eg6atDrdk59gNy@stanza.co
SUMMARY:Knights @ Tides
DESCRIPTION:Knights @ Tides\n\nFollow on MiLB First Pitch: https://stza.co/+vK5u-2t\n\nShop: https://stza.co/+vK5u-3A\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144512Z
LAST-MODIFIED:20180213T144512Z
TRANSP:OPAQUE
END:VEVENT
* Knights @ Tides
<2018-04-10 Tue 17:35-20:35>
:PROPERTIES:
:ID:       cx-dSwRJsZ60MiV9qMzkyu3C@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Knights @ Tides Knights @ Tides

Follow on MiLB First Pitch  https //stza.co/+vK5v-2U

Shop  https //stza.co/+vK5v-7

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Knights @ Tides
END:VALARM
DTSTART:20180410T223500Z
DTEND:20180411T013500Z
UID:cx-dSwRJsZ60MiV9qMzkyu3C@stanza.co
SUMMARY:Knights @ Tides
DESCRIPTION:Knights @ Tides\n\nFollow on MiLB First Pitch: https://stza.co/+vK5v-2U\n\nShop: https://stza.co/+vK5v-7\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144512Z
LAST-MODIFIED:20180213T144512Z
TRANSP:OPAQUE
END:VEVENT
* Knights @ Tides
<2018-04-11 Wed 11:05-14:05>
:PROPERTIES:
:ID:       PreTxkbt6IFT5SenLs3nXYkT@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Knights @ Tides Knights @ Tides

Follow on MiLB First Pitch  https //stza.co/+vK5w-30

Shop  https //stza.co/+vK5w-3X

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Knights @ Tides
END:VALARM
DTSTART:20180411T160500Z
DTEND:20180411T190500Z
UID:PreTxkbt6IFT5SenLs3nXYkT@stanza.co
SUMMARY:Knights @ Tides
DESCRIPTION:Knights @ Tides\n\nFollow on MiLB First Pitch: https://stza.co/+vK5w-30\n\nShop: https://stza.co/+vK5w-3X\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144512Z
LAST-MODIFIED:20180213T144512Z
TRANSP:OPAQUE
END:VEVENT
* Knights vs. RailRiders
<2018-04-12 Thu 18:04-21:04>
:PROPERTIES:
:ID:       oE1rc48u_Hjpd1dOcJHhvUEs@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Knights vs. RailRiders Knights vs. RailRiders

Follow on MiLB First Pitch  https //stza.co/+xOLc-2P

Shop  https //stza.co/+xOLc-3q

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Knights vs. RailRiders
END:VALARM
DTSTART:20180412T230400Z
DTEND:20180413T020400Z
UID:oE1rc48u_Hjpd1dOcJHhvUEs@stanza.co
SUMMARY:Knights vs. RailRiders
DESCRIPTION:Knights vs. RailRiders\n\nFollow on MiLB First Pitch: https://stza.co/+xOLc-2P\n\nShop: https://stza.co/+xOLc-3q\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144512Z
LAST-MODIFIED:20180213T144512Z
TRANSP:OPAQUE
END:VEVENT
* Knights vs. RailRiders
<2018-04-13 Fri 18:04-21:04>
:PROPERTIES:
:ID:       xW7Gcj_HFnemJsWcb4dY4I_6@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Knights vs. RailRiders Knights vs. RailRiders

Follow on MiLB First Pitch  https //stza.co/+xOLd-2l

Shop  https //stza.co/+xOLd-1f

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Knights vs. RailRiders
END:VALARM
DTSTART:20180413T230400Z
DTEND:20180414T020400Z
UID:xW7Gcj_HFnemJsWcb4dY4I_6@stanza.co
SUMMARY:Knights vs. RailRiders
DESCRIPTION:Knights vs. RailRiders\n\nFollow on MiLB First Pitch: https://stza.co/+xOLd-2l\n\nShop: https://stza.co/+xOLd-1f\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144512Z
LAST-MODIFIED:20180213T144512Z
TRANSP:OPAQUE
END:VEVENT
* Knights vs. RailRiders
<2018-04-14 Sat 18:04-21:04>
:PROPERTIES:
:ID:       K-17HZFatljtccHhEP1PJtQ6@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Knights vs. RailRiders Knights vs. RailRiders

Follow on MiLB First Pitch  https //stza.co/+xOLf-3y

Shop  https //stza.co/+xOLf-Y

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Knights vs. RailRiders
END:VALARM
DTSTART:20180414T230400Z
DTEND:20180415T020400Z
UID:K-17HZFatljtccHhEP1PJtQ6@stanza.co
SUMMARY:Knights vs. RailRiders
DESCRIPTION:Knights vs. RailRiders\n\nFollow on MiLB First Pitch: https://stza.co/+xOLf-3y\n\nShop: https://stza.co/+xOLf-Y\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144512Z
LAST-MODIFIED:20180213T144512Z
TRANSP:OPAQUE
END:VEVENT
* Knights vs. RailRiders
<2018-04-15 Sun 13:05-16:05>
:PROPERTIES:
:ID:       2jDZqVG69B9dhZwuDVoXKKh2@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Knights vs. RailRiders Knights vs. RailRiders

Follow on MiLB First Pitch  https //stza.co/+vK2N-1Y

Shop  https //stza.co/+vK2N-1J

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Knights vs. RailRiders
END:VALARM
DTSTART:20180415T180500Z
DTEND:20180415T210500Z
UID:2jDZqVG69B9dhZwuDVoXKKh2@stanza.co
SUMMARY:Knights vs. RailRiders
DESCRIPTION:Knights vs. RailRiders\n\nFollow on MiLB First Pitch: https://stza.co/+vK2N-1Y\n\nShop: https://stza.co/+vK2N-1J\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144512Z
LAST-MODIFIED:20180213T144512Z
TRANSP:OPAQUE
END:VEVENT
* Knights vs. Red Wings
<2018-04-16 Mon 18:04-21:04>
:PROPERTIES:
:ID:       QL-TjKx7iV-bpp4XowurvCRr@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Knights vs. Red Wings Knights vs. Red Wings

Follow on MiLB First Pitch  https //stza.co/+xOLi-23

Shop  https //stza.co/+xOLi-1R

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Knights vs. Red Wings
END:VALARM
DTSTART:20180416T230400Z
DTEND:20180417T020400Z
UID:QL-TjKx7iV-bpp4XowurvCRr@stanza.co
SUMMARY:Knights vs. Red Wings
DESCRIPTION:Knights vs. Red Wings\n\nFollow on MiLB First Pitch: https://stza.co/+xOLi-23\n\nShop: https://stza.co/+xOLi-1R\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144512Z
LAST-MODIFIED:20180213T144512Z
TRANSP:OPAQUE
END:VEVENT
* Knights vs. Red Wings
<2018-04-17 Tue 18:04-21:04>
:PROPERTIES:
:ID:       Bu685454uiI9_udis7-n7_4a@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Knights vs. Red Wings Knights vs. Red Wings

Follow on MiLB First Pitch  https //stza.co/+xOLj-25

Shop  https //stza.co/+xOLj-1F

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Knights vs. Red Wings
END:VALARM
DTSTART:20180417T230400Z
DTEND:20180418T020400Z
UID:Bu685454uiI9_udis7-n7_4a@stanza.co
SUMMARY:Knights vs. Red Wings
DESCRIPTION:Knights vs. Red Wings\n\nFollow on MiLB First Pitch: https://stza.co/+xOLj-25\n\nShop: https://stza.co/+xOLj-1F\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144512Z
LAST-MODIFIED:20180213T144512Z
TRANSP:OPAQUE
END:VEVENT
* Knights vs. Red Wings
<2018-04-18 Wed 18:04-21:04>
:PROPERTIES:
:ID:       kPEX9NklGfCUrB3irt7aUX_W@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Knights vs. Red Wings Knights vs. Red Wings

Follow on MiLB First Pitch  https //stza.co/+xOLl-g

Shop  https //stza.co/+xOLl-2Q

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Knights vs. Red Wings
END:VALARM
DTSTART:20180418T230400Z
DTEND:20180419T020400Z
UID:kPEX9NklGfCUrB3irt7aUX_W@stanza.co
SUMMARY:Knights vs. Red Wings
DESCRIPTION:Knights vs. Red Wings\n\nFollow on MiLB First Pitch: https://stza.co/+xOLl-g\n\nShop: https://stza.co/+xOLl-2Q\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144512Z
LAST-MODIFIED:20180213T144512Z
TRANSP:OPAQUE
END:VEVENT
* Knights @ Indians
<2018-04-20 Fri 18:15-21:15>
:PROPERTIES:
:ID:       JN9bSkRrpFg4Tc2sBt57_2T3@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Knights @ Indians Knights @ Indians

Follow on MiLB First Pitch  https //stza.co/+vK5l-3W

Shop  https //stza.co/+vK5l-22

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Knights @ Indians
END:VALARM
DTSTART:20180420T231500Z
DTEND:20180421T021500Z
UID:JN9bSkRrpFg4Tc2sBt57_2T3@stanza.co
SUMMARY:Knights @ Indians
DESCRIPTION:Knights @ Indians\n\nFollow on MiLB First Pitch: https://stza.co/+vK5l-3W\n\nShop: https://stza.co/+vK5l-22\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144512Z
LAST-MODIFIED:20180213T144512Z
TRANSP:OPAQUE
END:VEVENT
* Knights @ Indians
<2018-04-21 Sat 18:05-21:05>
:PROPERTIES:
:ID:       FNwlmW2DcpJ1UGS0aYxBxEGw@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Knights @ Indians Knights @ Indians

Follow on MiLB First Pitch  https //stza.co/+vK5m-t

Shop  https //stza.co/+vK5m-1b

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Knights @ Indians
END:VALARM
DTSTART:20180421T230500Z
DTEND:20180422T020500Z
UID:FNwlmW2DcpJ1UGS0aYxBxEGw@stanza.co
SUMMARY:Knights @ Indians
DESCRIPTION:Knights @ Indians\n\nFollow on MiLB First Pitch: https://stza.co/+vK5m-t\n\nShop: https://stza.co/+vK5m-1b\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144512Z
LAST-MODIFIED:20180213T144512Z
TRANSP:OPAQUE
END:VEVENT
* Knights @ Indians
<2018-04-22 Sun 12:35-15:35>
:PROPERTIES:
:ID:       FSjGyoX0PzromXqAxiPsC0ZB@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Knights @ Indians Knights @ Indians

Follow on MiLB First Pitch  https //stza.co/+vK5n-3g

Shop  https //stza.co/+vK5n-I

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Knights @ Indians
END:VALARM
DTSTART:20180422T173500Z
DTEND:20180422T203500Z
UID:FSjGyoX0PzromXqAxiPsC0ZB@stanza.co
SUMMARY:Knights @ Indians
DESCRIPTION:Knights @ Indians\n\nFollow on MiLB First Pitch: https://stza.co/+vK5n-3g\n\nShop: https://stza.co/+vK5n-I\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144512Z
LAST-MODIFIED:20180213T144512Z
TRANSP:OPAQUE
END:VEVENT
* Knights @ Bats
<2018-04-23 Mon 17:30-20:30>
:PROPERTIES:
:ID:       9hDWNRSh7_Ews5IGdloDPE8g@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Knights @ Bats Knights @ Bats

Buy tickets here  https //stza.co/~vK5r

Follow on MiLB First Pitch  https //stza.co/+vK5r-31

Shop  https //stza.co/+vK5r-30

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Knights @ Bats
END:VALARM
DTSTART:20180423T223000Z
DTEND:20180424T013000Z
UID:9hDWNRSh7_Ews5IGdloDPE8g@stanza.co
SUMMARY:Knights @ Bats
DESCRIPTION:Knights @ Bats\n\nBuy tickets here: https://stza.co/~vK5r\n\nFollow on MiLB First Pitch: https://stza.co/+vK5r-31\n\nShop: https://stza.co/+vK5r-30\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144512Z
LAST-MODIFIED:20180213T144512Z
TRANSP:OPAQUE
END:VEVENT
* Knights @ Bats
<2018-04-24 Tue 17:30-20:30>
:PROPERTIES:
:ID:       2Y-9wAyJzHSI7ySdMkXGPHcm@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Knights @ Bats Knights @ Bats

Buy tickets here  https //stza.co/~vK5s

Follow on MiLB First Pitch  https //stza.co/+vK5s-36

Shop  https //stza.co/+vK5s-3v

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Knights @ Bats
END:VALARM
DTSTART:20180424T223000Z
DTEND:20180425T013000Z
UID:2Y-9wAyJzHSI7ySdMkXGPHcm@stanza.co
SUMMARY:Knights @ Bats
DESCRIPTION:Knights @ Bats\n\nBuy tickets here: https://stza.co/~vK5s\n\nFollow on MiLB First Pitch: https://stza.co/+vK5s-36\n\nShop: https://stza.co/+vK5s-3v\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144512Z
LAST-MODIFIED:20180213T144512Z
TRANSP:OPAQUE
END:VEVENT
* Knights @ Bats
<2018-04-25 Wed 10:00-13:00>
:PROPERTIES:
:ID:       FIx4iqpWaq9YwBeGsoDkpalV@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Knights @ Bats Knights @ Bats

Buy tickets here  https //stza.co/~vK5t

Follow on MiLB First Pitch  https //stza.co/+vK5t-3w

Shop  https //stza.co/+vK5t-3l

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Knights @ Bats
END:VALARM
DTSTART:20180425T150000Z
DTEND:20180425T180000Z
UID:FIx4iqpWaq9YwBeGsoDkpalV@stanza.co
SUMMARY:Knights @ Bats
DESCRIPTION:Knights @ Bats\n\nBuy tickets here: https://stza.co/~vK5t\n\nFollow on MiLB First Pitch: https://stza.co/+vK5t-3w\n\nShop: https://stza.co/+vK5t-3l\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144512Z
LAST-MODIFIED:20180213T144512Z
TRANSP:OPAQUE
END:VEVENT
* Knights vs. Tides
<2018-04-27 Fri 18:04-21:04>
:PROPERTIES:
:ID:       wwFzPGkG_iVdbpB9Y8cg8apR@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Knights vs. Tides Knights vs. Tides

Follow on MiLB First Pitch  https //stza.co/+xOLo-39

Shop  https //stza.co/+xOLo-2E

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Knights vs. Tides
END:VALARM
DTSTART:20180427T230400Z
DTEND:20180428T020400Z
UID:wwFzPGkG_iVdbpB9Y8cg8apR@stanza.co
SUMMARY:Knights vs. Tides
DESCRIPTION:Knights vs. Tides\n\nFollow on MiLB First Pitch: https://stza.co/+xOLo-39\n\nShop: https://stza.co/+xOLo-2E\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144512Z
LAST-MODIFIED:20180213T144512Z
TRANSP:OPAQUE
END:VEVENT
* Knights vs. Tides
<2018-04-28 Sat 18:04-21:04>
:PROPERTIES:
:ID:       739QD3VXtehaVxBCMbKfOt0e@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Knights vs. Tides Knights vs. Tides

Follow on MiLB First Pitch  https //stza.co/+xOLq-3Q

Shop  https //stza.co/+xOLq-1G

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Knights vs. Tides
END:VALARM
DTSTART:20180428T230400Z
DTEND:20180429T020400Z
UID:739QD3VXtehaVxBCMbKfOt0e@stanza.co
SUMMARY:Knights vs. Tides
DESCRIPTION:Knights vs. Tides\n\nFollow on MiLB First Pitch: https://stza.co/+xOLq-3Q\n\nShop: https://stza.co/+xOLq-1G\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144512Z
LAST-MODIFIED:20180213T144512Z
TRANSP:OPAQUE
END:VEVENT
* Knights vs. Tides
<2018-04-29 Sun 13:05-16:05>
:PROPERTIES:
:ID:       7N9vxa4w-tzcQ0jpt1ZJd2sQ@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Knights vs. Tides Knights vs. Tides

Follow on MiLB First Pitch  https //stza.co/+vK2Z-2O

Shop  https //stza.co/+vK2Z-2H

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Knights vs. Tides
END:VALARM
DTSTART:20180429T180500Z
DTEND:20180429T210500Z
UID:7N9vxa4w-tzcQ0jpt1ZJd2sQ@stanza.co
SUMMARY:Knights vs. Tides
DESCRIPTION:Knights vs. Tides\n\nFollow on MiLB First Pitch: https://stza.co/+vK2Z-2O\n\nShop: https://stza.co/+vK2Z-2H\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144512Z
LAST-MODIFIED:20180213T144512Z
TRANSP:OPAQUE
END:VEVENT
* Knights vs. Stripers
<2018-04-30 Mon 18:04-21:04>
:PROPERTIES:
:ID:       lsVTziFeislg6er0mDAvJEl0@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Knights vs. Stripers Knights vs. Stripers

Follow on MiLB First Pitch  https //stza.co/+xOLs-17

Shop  https //stza.co/+xOLs-N

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Knights vs. Stripers
END:VALARM
DTSTART:20180430T230400Z
DTEND:20180501T020400Z
UID:lsVTziFeislg6er0mDAvJEl0@stanza.co
SUMMARY:Knights vs. Stripers
DESCRIPTION:Knights vs. Stripers\n\nFollow on MiLB First Pitch: https://stza.co/+xOLs-17\n\nShop: https://stza.co/+xOLs-N\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144512Z
LAST-MODIFIED:20180213T144512Z
TRANSP:OPAQUE
END:VEVENT
* Knights vs. Stripers
<2018-05-01 Tue 18:04-21:04>
:PROPERTIES:
:ID:       MIsiAYIGsZ6pgQkppuITKs4r@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Knights vs. Stripers Knights vs. Stripers

Follow on MiLB First Pitch  https //stza.co/+xOLu-g

Shop  https //stza.co/+xOLu-3d

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Knights vs. Stripers
END:VALARM
DTSTART:20180501T230400Z
DTEND:20180502T020400Z
UID:MIsiAYIGsZ6pgQkppuITKs4r@stanza.co
SUMMARY:Knights vs. Stripers
DESCRIPTION:Knights vs. Stripers\n\nFollow on MiLB First Pitch: https://stza.co/+xOLu-g\n\nShop: https://stza.co/+xOLu-3d\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144512Z
LAST-MODIFIED:20180213T144512Z
TRANSP:OPAQUE
END:VEVENT
* Knights vs. Stripers
<2018-05-02 Wed 10:05-13:05>
:PROPERTIES:
:ID:       sBXe0KtzchNKQdxJ0XfRLuL4@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Knights vs. Stripers Knights vs. Stripers

Follow on MiLB First Pitch  https //stza.co/+vK33-1j

Shop  https //stza.co/+vK33-1Z

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Knights vs. Stripers
END:VALARM
DTSTART:20180502T150500Z
DTEND:20180502T180500Z
UID:sBXe0KtzchNKQdxJ0XfRLuL4@stanza.co
SUMMARY:Knights vs. Stripers
DESCRIPTION:Knights vs. Stripers\n\nFollow on MiLB First Pitch: https://stza.co/+vK33-1j\n\nShop: https://stza.co/+vK33-1Z\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144512Z
LAST-MODIFIED:20180213T144512Z
TRANSP:OPAQUE
END:VEVENT
* Knights @ Clippers
<2018-05-03 Thu 17:35-20:35>
:PROPERTIES:
:ID:       Ak7ACbz5h-7UCEK4RPO11hiL@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Knights @ Clippers Knights @ Clippers

Buy tickets here  https //stza.co/~vK4S

Follow on MiLB First Pitch  https //stza.co/+vK4S-f

Shop  https //stza.co/+vK4S-3K

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Knights @ Clippers
END:VALARM
DTSTART:20180503T223500Z
DTEND:20180504T013500Z
UID:Ak7ACbz5h-7UCEK4RPO11hiL@stanza.co
SUMMARY:Knights @ Clippers
DESCRIPTION:Knights @ Clippers\n\nBuy tickets here: https://stza.co/~vK4S\n\nFollow on MiLB First Pitch: https://stza.co/+vK4S-f\n\nShop: https://stza.co/+vK4S-3K\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144512Z
LAST-MODIFIED:20180213T144512Z
TRANSP:OPAQUE
END:VEVENT
* Knights @ Clippers
<2018-05-04 Fri 18:15-21:15>
:PROPERTIES:
:ID:       F_ZMXaLBkS_elm_Xv6KAywWT@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Knights @ Clippers Knights @ Clippers

Buy tickets here  https //stza.co/~vK4T

Follow on MiLB First Pitch  https //stza.co/+vK4T-36

Shop  https //stza.co/+vK4T-3g

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Knights @ Clippers
END:VALARM
DTSTART:20180504T231500Z
DTEND:20180505T021500Z
UID:F_ZMXaLBkS_elm_Xv6KAywWT@stanza.co
SUMMARY:Knights @ Clippers
DESCRIPTION:Knights @ Clippers\n\nBuy tickets here: https://stza.co/~vK4T\n\nFollow on MiLB First Pitch: https://stza.co/+vK4T-36\n\nShop: https://stza.co/+vK4T-3g\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144512Z
LAST-MODIFIED:20180213T144512Z
TRANSP:OPAQUE
END:VEVENT
* Knights @ Clippers
<2018-05-05 Sat 18:15-21:15>
:PROPERTIES:
:ID:       UClUFjNs_RCBJpuAw5usOFtI@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Knights @ Clippers Knights @ Clippers

Buy tickets here  https //stza.co/~vK4U

Follow on MiLB First Pitch  https //stza.co/+vK4U-2z

Shop  https //stza.co/+vK4U-1l

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Knights @ Clippers
END:VALARM
DTSTART:20180505T231500Z
DTEND:20180506T021500Z
UID:UClUFjNs_RCBJpuAw5usOFtI@stanza.co
SUMMARY:Knights @ Clippers
DESCRIPTION:Knights @ Clippers\n\nBuy tickets here: https://stza.co/~vK4U\n\nFollow on MiLB First Pitch: https://stza.co/+vK4U-2z\n\nShop: https://stza.co/+vK4U-1l\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144512Z
LAST-MODIFIED:20180213T144512Z
TRANSP:OPAQUE
END:VEVENT
* Knights @ Clippers
<2018-05-06 Sun 13:05-16:05>
:PROPERTIES:
:ID:       adXuXenKxpiW50qBey_5wwPy@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Knights @ Clippers Knights @ Clippers

Buy tickets here  https //stza.co/~vK4V

Follow on MiLB First Pitch  https //stza.co/+vK4V-32

Shop  https //stza.co/+vK4V-2A

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Knights @ Clippers
END:VALARM
DTSTART:20180506T180500Z
DTEND:20180506T210500Z
UID:adXuXenKxpiW50qBey_5wwPy@stanza.co
SUMMARY:Knights @ Clippers
DESCRIPTION:Knights @ Clippers\n\nBuy tickets here: https://stza.co/~vK4V\n\nFollow on MiLB First Pitch: https://stza.co/+vK4V-32\n\nShop: https://stza.co/+vK4V-2A\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144512Z
LAST-MODIFIED:20180213T144512Z
TRANSP:OPAQUE
END:VEVENT
* Knights @ Stripers
<2018-05-07 Mon 18:05-21:05>
:PROPERTIES:
:ID:       7RE0ofqMXsUrJLBJfKUFRlhe@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Knights @ Stripers Knights @ Stripers

Follow on MiLB First Pitch  https //stza.co/+vK5a-r

Shop  https //stza.co/+vK5a-3C

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Knights @ Stripers
END:VALARM
DTSTART:20180507T230500Z
DTEND:20180508T020500Z
UID:7RE0ofqMXsUrJLBJfKUFRlhe@stanza.co
SUMMARY:Knights @ Stripers
DESCRIPTION:Knights @ Stripers\n\nFollow on MiLB First Pitch: https://stza.co/+vK5a-r\n\nShop: https://stza.co/+vK5a-3C\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144512Z
LAST-MODIFIED:20180213T144512Z
TRANSP:OPAQUE
END:VEVENT
* Knights @ Stripers
<2018-05-08 Tue 18:05-21:05>
:PROPERTIES:
:ID:       oKE6vVkQcytnWC-ihSTNjBiF@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Knights @ Stripers Knights @ Stripers

Follow on MiLB First Pitch  https //stza.co/+vK5b-33

Shop  https //stza.co/+vK5b-1n

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Knights @ Stripers
END:VALARM
DTSTART:20180508T230500Z
DTEND:20180509T020500Z
UID:oKE6vVkQcytnWC-ihSTNjBiF@stanza.co
SUMMARY:Knights @ Stripers
DESCRIPTION:Knights @ Stripers\n\nFollow on MiLB First Pitch: https://stza.co/+vK5b-33\n\nShop: https://stza.co/+vK5b-1n\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144512Z
LAST-MODIFIED:20180213T144512Z
TRANSP:OPAQUE
END:VEVENT
* Knights @ Stripers
<2018-05-09 Wed 09:35-12:35>
:PROPERTIES:
:ID:       brffDEnNOKYvTUluVZphqq78@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Knights @ Stripers Knights @ Stripers

Follow on MiLB First Pitch  https //stza.co/+vK5c-1G

Shop  https //stza.co/+vK5c-31

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Knights @ Stripers
END:VALARM
DTSTART:20180509T143500Z
DTEND:20180509T173500Z
UID:brffDEnNOKYvTUluVZphqq78@stanza.co
SUMMARY:Knights @ Stripers
DESCRIPTION:Knights @ Stripers\n\nFollow on MiLB First Pitch: https://stza.co/+vK5c-1G\n\nShop: https://stza.co/+vK5c-31\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144512Z
LAST-MODIFIED:20180213T144512Z
TRANSP:OPAQUE
END:VEVENT
* Knights @ Stripers
<2018-05-10 Thu 09:35-12:35>
:PROPERTIES:
:ID:       6pWA4qvjULs576MNRMypoAvn@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Knights @ Stripers Knights @ Stripers

Follow on MiLB First Pitch  https //stza.co/+vK5d-2s

Shop  https //stza.co/+vK5d-3N

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Knights @ Stripers
END:VALARM
DTSTART:20180510T143500Z
DTEND:20180510T173500Z
UID:6pWA4qvjULs576MNRMypoAvn@stanza.co
SUMMARY:Knights @ Stripers
DESCRIPTION:Knights @ Stripers\n\nFollow on MiLB First Pitch: https://stza.co/+vK5d-2s\n\nShop: https://stza.co/+vK5d-3N\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144512Z
LAST-MODIFIED:20180213T144512Z
TRANSP:OPAQUE
END:VEVENT
* Knights vs. Bulls
<2018-05-11 Fri 18:04-21:04>
:PROPERTIES:
:ID:       Ed1qUGrdtlsUsBcMXELXt0pT@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Knights vs. Bulls Knights vs. Bulls

Follow on MiLB First Pitch  https //stza.co/+xOLw-3O

Shop  https //stza.co/+xOLw-2w

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Knights vs. Bulls
END:VALARM
DTSTART:20180511T230400Z
DTEND:20180512T020400Z
UID:Ed1qUGrdtlsUsBcMXELXt0pT@stanza.co
SUMMARY:Knights vs. Bulls
DESCRIPTION:Knights vs. Bulls\n\nFollow on MiLB First Pitch: https://stza.co/+xOLw-3O\n\nShop: https://stza.co/+xOLw-2w\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144512Z
LAST-MODIFIED:20180213T144512Z
TRANSP:OPAQUE
END:VEVENT
* Knights vs. Bulls
<2018-05-12 Sat 18:04-21:04>
:PROPERTIES:
:ID:       g-xVN7H5pjJtlGSKXUxiZ0um@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Knights vs. Bulls Knights vs. Bulls

Follow on MiLB First Pitch  https //stza.co/+xOLx-26

Shop  https //stza.co/+xOLx-2v

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Knights vs. Bulls
END:VALARM
DTSTART:20180512T230400Z
DTEND:20180513T020400Z
UID:g-xVN7H5pjJtlGSKXUxiZ0um@stanza.co
SUMMARY:Knights vs. Bulls
DESCRIPTION:Knights vs. Bulls\n\nFollow on MiLB First Pitch: https://stza.co/+xOLx-26\n\nShop: https://stza.co/+xOLx-2v\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144512Z
LAST-MODIFIED:20180213T144512Z
TRANSP:OPAQUE
END:VEVENT
* Knights vs. Bulls
<2018-05-13 Sun 13:05-16:05>
:PROPERTIES:
:ID:       htKP3qMoRoCHfjCVB1M5-bzZ@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Knights vs. Bulls Knights vs. Bulls

Follow on MiLB First Pitch  https //stza.co/+vK39-3r

Shop  https //stza.co/+vK39-3V

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Knights vs. Bulls
END:VALARM
DTSTART:20180513T180500Z
DTEND:20180513T210500Z
UID:htKP3qMoRoCHfjCVB1M5-bzZ@stanza.co
SUMMARY:Knights vs. Bulls
DESCRIPTION:Knights vs. Bulls\n\nFollow on MiLB First Pitch: https://stza.co/+vK39-3r\n\nShop: https://stza.co/+vK39-3V\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144512Z
LAST-MODIFIED:20180213T144512Z
TRANSP:OPAQUE
END:VEVENT
* Knights @ Mud Hens
<2018-05-15 Tue 17:35-20:35>
:PROPERTIES:
:ID:       H4OYTW5To_AW7jujnR1r4blh@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Knights @ Mud Hens Knights @ Mud Hens

Follow on MiLB First Pitch  https //stza.co/+uWFs-1F

Shop  https //stza.co/+uWFs-1R

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Knights @ Mud Hens
END:VALARM
DTSTART:20180515T223500Z
DTEND:20180516T013500Z
UID:H4OYTW5To_AW7jujnR1r4blh@stanza.co
SUMMARY:Knights @ Mud Hens
DESCRIPTION:Knights @ Mud Hens\n\nFollow on MiLB First Pitch: https://stza.co/+uWFs-1F\n\nShop: https://stza.co/+uWFs-1R\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144512Z
LAST-MODIFIED:20180213T144512Z
TRANSP:OPAQUE
END:VEVENT
* Knights @ Mud Hens
<2018-05-16 Wed 09:35-12:35>
:PROPERTIES:
:ID:       1QSaKX3eAaeBzEHkheAXpmtk@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Knights @ Mud Hens Knights @ Mud Hens

Follow on MiLB First Pitch  https //stza.co/+uWFx-2u

Shop  https //stza.co/+uWFx-2p

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Knights @ Mud Hens
END:VALARM
DTSTART:20180516T143500Z
DTEND:20180516T173500Z
UID:1QSaKX3eAaeBzEHkheAXpmtk@stanza.co
SUMMARY:Knights @ Mud Hens
DESCRIPTION:Knights @ Mud Hens\n\nFollow on MiLB First Pitch: https://stza.co/+uWFx-2u\n\nShop: https://stza.co/+uWFx-2p\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144512Z
LAST-MODIFIED:20180213T144512Z
TRANSP:OPAQUE
END:VEVENT
* Knights @ Mud Hens
<2018-05-17 Thu 09:35-12:35>
:PROPERTIES:
:ID:       2TscRrTKCB7_iOhHy52rDoy1@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Knights @ Mud Hens Knights @ Mud Hens

Follow on MiLB First Pitch  https //stza.co/+uWFG-$

Shop  https //stza.co/+uWFG-2V

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Knights @ Mud Hens
END:VALARM
DTSTART:20180517T143500Z
DTEND:20180517T173500Z
UID:2TscRrTKCB7_iOhHy52rDoy1@stanza.co
SUMMARY:Knights @ Mud Hens
DESCRIPTION:Knights @ Mud Hens\n\nFollow on MiLB First Pitch: https://stza.co/+uWFG-$\n\nShop: https://stza.co/+uWFG-2V\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144512Z
LAST-MODIFIED:20180213T144512Z
TRANSP:OPAQUE
END:VEVENT
* Knights @ Clippers
<2018-05-18 Fri 18:15-21:15>
:PROPERTIES:
:ID:       KBWeYq5rKXeUGXW9w6d1pQov@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Knights @ Clippers Knights @ Clippers

Buy tickets here  https //stza.co/~vK4W

Follow on MiLB First Pitch  https //stza.co/+vK4W-2m

Shop  https //stza.co/+vK4W-3X

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Knights @ Clippers
END:VALARM
DTSTART:20180518T231500Z
DTEND:20180519T021500Z
UID:KBWeYq5rKXeUGXW9w6d1pQov@stanza.co
SUMMARY:Knights @ Clippers
DESCRIPTION:Knights @ Clippers\n\nBuy tickets here: https://stza.co/~vK4W\n\nFollow on MiLB First Pitch: https://stza.co/+vK4W-2m\n\nShop: https://stza.co/+vK4W-3X\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144512Z
LAST-MODIFIED:20180213T144512Z
TRANSP:OPAQUE
END:VEVENT
* Knights @ Clippers
<2018-05-19 Sat 18:15-21:15>
:PROPERTIES:
:ID:       WC5mxG2GH4OJ0XBhTi1ibjjg@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Knights @ Clippers Knights @ Clippers

Buy tickets here  https //stza.co/~vK4X

Follow on MiLB First Pitch  https //stza.co/+vK4X-1U

Shop  https //stza.co/+vK4X-2R

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Knights @ Clippers
END:VALARM
DTSTART:20180519T231500Z
DTEND:20180520T021500Z
UID:WC5mxG2GH4OJ0XBhTi1ibjjg@stanza.co
SUMMARY:Knights @ Clippers
DESCRIPTION:Knights @ Clippers\n\nBuy tickets here: https://stza.co/~vK4X\n\nFollow on MiLB First Pitch: https://stza.co/+vK4X-1U\n\nShop: https://stza.co/+vK4X-2R\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144512Z
LAST-MODIFIED:20180213T144512Z
TRANSP:OPAQUE
END:VEVENT
* Knights @ Clippers
<2018-05-20 Sun 13:05-16:05>
:PROPERTIES:
:ID:       LnkocReqHUZIjGAJgI61KuZ8@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Knights @ Clippers Knights @ Clippers

Buy tickets here  https //stza.co/~vK4Y

Follow on MiLB First Pitch  https //stza.co/+vK4Y-2E

Shop  https //stza.co/+vK4Y-w

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Knights @ Clippers
END:VALARM
DTSTART:20180520T180500Z
DTEND:20180520T210500Z
UID:LnkocReqHUZIjGAJgI61KuZ8@stanza.co
SUMMARY:Knights @ Clippers
DESCRIPTION:Knights @ Clippers\n\nBuy tickets here: https://stza.co/~vK4Y\n\nFollow on MiLB First Pitch: https://stza.co/+vK4Y-2E\n\nShop: https://stza.co/+vK4Y-w\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144512Z
LAST-MODIFIED:20180213T144512Z
TRANSP:OPAQUE
END:VEVENT
* Knights vs. Tides
<2018-05-21 Mon 18:04-21:04>
:PROPERTIES:
:ID:       VSJQB-PBa42gctgV33Qbl8f1@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Knights vs. Tides Knights vs. Tides

Follow on MiLB First Pitch  https //stza.co/+xOLz-Y

Shop  https //stza.co/+xOLz-1s

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Knights vs. Tides
END:VALARM
DTSTART:20180521T230400Z
DTEND:20180522T020400Z
UID:VSJQB-PBa42gctgV33Qbl8f1@stanza.co
SUMMARY:Knights vs. Tides
DESCRIPTION:Knights vs. Tides\n\nFollow on MiLB First Pitch: https://stza.co/+xOLz-Y\n\nShop: https://stza.co/+xOLz-1s\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144512Z
LAST-MODIFIED:20180213T144512Z
TRANSP:OPAQUE
END:VEVENT
* Knights vs. Tides
<2018-05-22 Tue 18:04-21:04>
:PROPERTIES:
:ID:       uKGVVNBwVTOqtr-sJbfaJfxu@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Knights vs. Tides Knights vs. Tides

Follow on MiLB First Pitch  https //stza.co/+xOLB-13

Shop  https //stza.co/+xOLB-2t

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Knights vs. Tides
END:VALARM
DTSTART:20180522T230400Z
DTEND:20180523T020400Z
UID:uKGVVNBwVTOqtr-sJbfaJfxu@stanza.co
SUMMARY:Knights vs. Tides
DESCRIPTION:Knights vs. Tides\n\nFollow on MiLB First Pitch: https://stza.co/+xOLB-13\n\nShop: https://stza.co/+xOLB-2t\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144512Z
LAST-MODIFIED:20180213T144512Z
TRANSP:OPAQUE
END:VEVENT
* Knights vs. Tides
<2018-05-23 Wed 18:04-21:04>
:PROPERTIES:
:ID:       K_C-cEDDD6gAe8EZSPC-PqNy@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Knights vs. Tides Knights vs. Tides

Follow on MiLB First Pitch  https //stza.co/+xOLE-U

Shop  https //stza.co/+xOLE-1o

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Knights vs. Tides
END:VALARM
DTSTART:20180523T230400Z
DTEND:20180524T020400Z
UID:K_C-cEDDD6gAe8EZSPC-PqNy@stanza.co
SUMMARY:Knights vs. Tides
DESCRIPTION:Knights vs. Tides\n\nFollow on MiLB First Pitch: https://stza.co/+xOLE-U\n\nShop: https://stza.co/+xOLE-1o\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144512Z
LAST-MODIFIED:20180213T144512Z
TRANSP:OPAQUE
END:VEVENT
* Knights vs. Tides
<2018-05-24 Thu 18:04-21:04>
:PROPERTIES:
:ID:       waSqRIOiTSnR4210dC9rxDRU@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Knights vs. Tides Knights vs. Tides

Follow on MiLB First Pitch  https //stza.co/+xOLF-3q

Shop  https //stza.co/+xOLF-3C

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Knights vs. Tides
END:VALARM
DTSTART:20180524T230400Z
DTEND:20180525T020400Z
UID:waSqRIOiTSnR4210dC9rxDRU@stanza.co
SUMMARY:Knights vs. Tides
DESCRIPTION:Knights vs. Tides\n\nFollow on MiLB First Pitch: https://stza.co/+xOLF-3q\n\nShop: https://stza.co/+xOLF-3C\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144512Z
LAST-MODIFIED:20180213T144512Z
TRANSP:OPAQUE
END:VEVENT
* Knights vs. Indians
<2018-05-25 Fri 18:04-21:04>
:PROPERTIES:
:ID:       jhI8dyuAceOn3PK4mUWuBiUQ@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Knights vs. Indians Knights vs. Indians

Follow on MiLB First Pitch  https //stza.co/+xOLH-T

Shop  https //stza.co/+xOLH-1$

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Knights vs. Indians
END:VALARM
DTSTART:20180525T230400Z
DTEND:20180526T020400Z
UID:jhI8dyuAceOn3PK4mUWuBiUQ@stanza.co
SUMMARY:Knights vs. Indians
DESCRIPTION:Knights vs. Indians\n\nFollow on MiLB First Pitch: https://stza.co/+xOLH-T\n\nShop: https://stza.co/+xOLH-1$\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144512Z
LAST-MODIFIED:20180213T144512Z
TRANSP:OPAQUE
END:VEVENT
* Knights vs. Indians
<2018-05-26 Sat 18:04-21:04>
:PROPERTIES:
:ID:       Up0zrq2x01dcXh8P7nEbQRg_@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Knights vs. Indians Knights vs. Indians

Follow on MiLB First Pitch  https //stza.co/+xOLK-3Z

Shop  https //stza.co/+xOLK-i

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Knights vs. Indians
END:VALARM
DTSTART:20180526T230400Z
DTEND:20180527T020400Z
UID:Up0zrq2x01dcXh8P7nEbQRg_@stanza.co
SUMMARY:Knights vs. Indians
DESCRIPTION:Knights vs. Indians\n\nFollow on MiLB First Pitch: https://stza.co/+xOLK-3Z\n\nShop: https://stza.co/+xOLK-i\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144512Z
LAST-MODIFIED:20180213T144512Z
TRANSP:OPAQUE
END:VEVENT
* Knights vs. Indians
<2018-05-27 Sun 18:04-21:04>
:PROPERTIES:
:ID:       68ckaBT_c19Gy-KSB4dpkxV6@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Knights vs. Indians Knights vs. Indians

Follow on MiLB First Pitch  https //stza.co/+xOLL-2u

Shop  https //stza.co/+xOLL-3k

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Knights vs. Indians
END:VALARM
DTSTART:20180527T230400Z
DTEND:20180528T020400Z
UID:68ckaBT_c19Gy-KSB4dpkxV6@stanza.co
SUMMARY:Knights vs. Indians
DESCRIPTION:Knights vs. Indians\n\nFollow on MiLB First Pitch: https://stza.co/+xOLL-2u\n\nShop: https://stza.co/+xOLL-3k\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144512Z
LAST-MODIFIED:20180213T144512Z
TRANSP:OPAQUE
END:VEVENT
* Knights vs. Indians
<2018-05-28 Mon 13:05-16:05>
:PROPERTIES:
:ID:       sFZYXzpef5lpxYpYLeArwBuh@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Knights vs. Indians Knights vs. Indians

Follow on MiLB First Pitch  https //stza.co/+vK3p-o

Shop  https //stza.co/+vK3p-2z

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Knights vs. Indians
END:VALARM
DTSTART:20180528T180500Z
DTEND:20180528T210500Z
UID:sFZYXzpef5lpxYpYLeArwBuh@stanza.co
SUMMARY:Knights vs. Indians
DESCRIPTION:Knights vs. Indians\n\nFollow on MiLB First Pitch: https://stza.co/+vK3p-o\n\nShop: https://stza.co/+vK3p-2z\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144512Z
LAST-MODIFIED:20180213T144512Z
TRANSP:OPAQUE
END:VEVENT
* Knights @ IronPigs
<2018-05-29 Tue 18:05-21:05>
:PROPERTIES:
:ID:       exTZOy5Hwg3HIv2Gh_E9lsyE@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Knights @ IronPigs Knights @ IronPigs

Follow on MiLB First Pitch  https //stza.co/+vK5o-3W

Shop  https //stza.co/+vK5o-2C

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Knights @ IronPigs
END:VALARM
DTSTART:20180529T230500Z
DTEND:20180530T020500Z
UID:exTZOy5Hwg3HIv2Gh_E9lsyE@stanza.co
SUMMARY:Knights @ IronPigs
DESCRIPTION:Knights @ IronPigs\n\nFollow on MiLB First Pitch: https://stza.co/+vK5o-3W\n\nShop: https://stza.co/+vK5o-2C\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144512Z
LAST-MODIFIED:20180213T144512Z
TRANSP:OPAQUE
END:VEVENT
* Knights @ IronPigs
<2018-05-30 Wed 18:05-21:05>
:PROPERTIES:
:ID:       1LV9wfkcKttJKqJpbueXHke5@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Knights @ IronPigs Knights @ IronPigs

Follow on MiLB First Pitch  https //stza.co/+vK5p-i

Shop  https //stza.co/+vK5p-3H

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Knights @ IronPigs
END:VALARM
DTSTART:20180530T230500Z
DTEND:20180531T020500Z
UID:1LV9wfkcKttJKqJpbueXHke5@stanza.co
SUMMARY:Knights @ IronPigs
DESCRIPTION:Knights @ IronPigs\n\nFollow on MiLB First Pitch: https://stza.co/+vK5p-i\n\nShop: https://stza.co/+vK5p-3H\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144512Z
LAST-MODIFIED:20180213T144512Z
TRANSP:OPAQUE
END:VEVENT
* Knights @ IronPigs
<2018-05-31 Thu 18:05-21:05>
:PROPERTIES:
:ID:       9T6WcSOu-aSCyB1pbkDiLHuf@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Knights @ IronPigs Knights @ IronPigs

Follow on MiLB First Pitch  https //stza.co/+vK5q-35

Shop  https //stza.co/+vK5q-O

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Knights @ IronPigs
END:VALARM
DTSTART:20180531T230500Z
DTEND:20180601T020500Z
UID:9T6WcSOu-aSCyB1pbkDiLHuf@stanza.co
SUMMARY:Knights @ IronPigs
DESCRIPTION:Knights @ IronPigs\n\nFollow on MiLB First Pitch: https://stza.co/+vK5q-35\n\nShop: https://stza.co/+vK5q-O\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144512Z
LAST-MODIFIED:20180213T144512Z
TRANSP:OPAQUE
END:VEVENT
* Knights @ Bisons
<2018-06-01 Fri 18:05-21:05>
:PROPERTIES:
:ID:       PRGz5such7MMzQOqdY025BlR@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Knights @ Bisons Knights @ Bisons

Follow on MiLB First Pitch  https //stza.co/+vK2D-1o

Shop  https //stza.co/+vK2D-2u

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Knights @ Bisons
END:VALARM
DTSTART:20180601T230500Z
DTEND:20180602T020500Z
UID:PRGz5such7MMzQOqdY025BlR@stanza.co
SUMMARY:Knights @ Bisons
DESCRIPTION:Knights @ Bisons\n\nFollow on MiLB First Pitch: https://stza.co/+vK2D-1o\n\nShop: https://stza.co/+vK2D-2u\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144512Z
LAST-MODIFIED:20180213T144512Z
TRANSP:OPAQUE
END:VEVENT
* Knights @ Bisons
<2018-06-02 Sat 17:05-20:05>
:PROPERTIES:
:ID:       bI2JY-Tr9gq4D_1bYj-J1nUZ@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Knights @ Bisons Knights @ Bisons

Follow on MiLB First Pitch  https //stza.co/+vK2E-3K

Shop  https //stza.co/+vK2E-1A

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Knights @ Bisons
END:VALARM
DTSTART:20180602T220500Z
DTEND:20180603T010500Z
UID:bI2JY-Tr9gq4D_1bYj-J1nUZ@stanza.co
SUMMARY:Knights @ Bisons
DESCRIPTION:Knights @ Bisons\n\nFollow on MiLB First Pitch: https://stza.co/+vK2E-3K\n\nShop: https://stza.co/+vK2E-1A\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144512Z
LAST-MODIFIED:20180213T144512Z
TRANSP:OPAQUE
END:VEVENT
* Knights @ Bisons
<2018-06-03 Sun 12:05-15:05>
:PROPERTIES:
:ID:       SXjWPzc2T-DatyUCEkLhwaPy@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Knights @ Bisons Knights @ Bisons

Follow on MiLB First Pitch  https //stza.co/+vK2F-3c

Shop  https //stza.co/+vK2F-3p

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Knights @ Bisons
END:VALARM
DTSTART:20180603T170500Z
DTEND:20180603T200500Z
UID:SXjWPzc2T-DatyUCEkLhwaPy@stanza.co
SUMMARY:Knights @ Bisons
DESCRIPTION:Knights @ Bisons\n\nFollow on MiLB First Pitch: https://stza.co/+vK2F-3c\n\nShop: https://stza.co/+vK2F-3p\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144512Z
LAST-MODIFIED:20180213T144512Z
TRANSP:OPAQUE
END:VEVENT
* Knights vs. Chiefs
<2018-06-05 Tue 18:04-21:04>
:PROPERTIES:
:ID:       waE2_cja60tELBgV0XphYPdv@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Knights vs. Chiefs Knights vs. Chiefs

Follow on MiLB First Pitch  https //stza.co/+xOLN-3b

Shop  https //stza.co/+xOLN-28

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Knights vs. Chiefs
END:VALARM
DTSTART:20180605T230400Z
DTEND:20180606T020400Z
UID:waE2_cja60tELBgV0XphYPdv@stanza.co
SUMMARY:Knights vs. Chiefs
DESCRIPTION:Knights vs. Chiefs\n\nFollow on MiLB First Pitch: https://stza.co/+xOLN-3b\n\nShop: https://stza.co/+xOLN-28\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144512Z
LAST-MODIFIED:20180213T144512Z
TRANSP:OPAQUE
END:VEVENT
* Knights vs. Chiefs
<2018-06-06 Wed 18:04-21:04>
:PROPERTIES:
:ID:       43h3ZUtYhfVsnzk8f1eyRX1-@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Knights vs. Chiefs Knights vs. Chiefs

Follow on MiLB First Pitch  https //stza.co/+xOLQ-3i

Shop  https //stza.co/+xOLQ-2d

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Knights vs. Chiefs
END:VALARM
DTSTART:20180606T230400Z
DTEND:20180607T020400Z
UID:43h3ZUtYhfVsnzk8f1eyRX1-@stanza.co
SUMMARY:Knights vs. Chiefs
DESCRIPTION:Knights vs. Chiefs\n\nFollow on MiLB First Pitch: https://stza.co/+xOLQ-3i\n\nShop: https://stza.co/+xOLQ-2d\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144512Z
LAST-MODIFIED:20180213T144512Z
TRANSP:OPAQUE
END:VEVENT
* Knights vs. Chiefs
<2018-06-07 Thu 18:04-21:04>
:PROPERTIES:
:ID:       sEFkzgAxPgZcwjN_Rlc63yZc@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Knights vs. Chiefs Knights vs. Chiefs

Follow on MiLB First Pitch  https //stza.co/+xOLS-2u

Shop  https //stza.co/+xOLS-1y

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Knights vs. Chiefs
END:VALARM
DTSTART:20180607T230400Z
DTEND:20180608T020400Z
UID:sEFkzgAxPgZcwjN_Rlc63yZc@stanza.co
SUMMARY:Knights vs. Chiefs
DESCRIPTION:Knights vs. Chiefs\n\nFollow on MiLB First Pitch: https://stza.co/+xOLS-2u\n\nShop: https://stza.co/+xOLS-1y\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144512Z
LAST-MODIFIED:20180213T144512Z
TRANSP:OPAQUE
END:VEVENT
* Knights vs. IronPigs
<2018-06-08 Fri 18:04-21:04>
:PROPERTIES:
:ID:       79imAaTJ5eKMrhWUoRuAHoT6@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Knights vs. IronPigs Knights vs. IronPigs

Follow on MiLB First Pitch  https //stza.co/+xOLT-3Y

Shop  https //stza.co/+xOLT-1b

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Knights vs. IronPigs
END:VALARM
DTSTART:20180608T230400Z
DTEND:20180609T020400Z
UID:79imAaTJ5eKMrhWUoRuAHoT6@stanza.co
SUMMARY:Knights vs. IronPigs
DESCRIPTION:Knights vs. IronPigs\n\nFollow on MiLB First Pitch: https://stza.co/+xOLT-3Y\n\nShop: https://stza.co/+xOLT-1b\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144512Z
LAST-MODIFIED:20180213T144512Z
TRANSP:OPAQUE
END:VEVENT
* Knights vs. IronPigs
<2018-06-09 Sat 18:04-21:04>
:PROPERTIES:
:ID:       qjEZtI95OASsJEhuczcPz3ht@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Knights vs. IronPigs Knights vs. IronPigs

Follow on MiLB First Pitch  https //stza.co/+xOLW-q

Shop  https //stza.co/+xOLW-2r

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Knights vs. IronPigs
END:VALARM
DTSTART:20180609T230400Z
DTEND:20180610T020400Z
UID:qjEZtI95OASsJEhuczcPz3ht@stanza.co
SUMMARY:Knights vs. IronPigs
DESCRIPTION:Knights vs. IronPigs\n\nFollow on MiLB First Pitch: https://stza.co/+xOLW-q\n\nShop: https://stza.co/+xOLW-2r\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144512Z
LAST-MODIFIED:20180213T144512Z
TRANSP:OPAQUE
END:VEVENT
* Knights vs. IronPigs
<2018-06-10 Sun 13:05-16:05>
:PROPERTIES:
:ID:       aTFoVoIKLAwAc1WruDK9aNhI@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Knights vs. IronPigs Knights vs. IronPigs

Follow on MiLB First Pitch  https //stza.co/+vK3B-3m

Shop  https //stza.co/+vK3B-3Y

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Knights vs. IronPigs
END:VALARM
DTSTART:20180610T180500Z
DTEND:20180610T210500Z
UID:aTFoVoIKLAwAc1WruDK9aNhI@stanza.co
SUMMARY:Knights vs. IronPigs
DESCRIPTION:Knights vs. IronPigs\n\nFollow on MiLB First Pitch: https://stza.co/+vK3B-3m\n\nShop: https://stza.co/+vK3B-3Y\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144512Z
LAST-MODIFIED:20180213T144512Z
TRANSP:OPAQUE
END:VEVENT
* Knights @ Bulls
<2018-06-12 Tue 18:05-21:05>
:PROPERTIES:
:ID:       tDWNYJzi6nW5I7UZQoNIG3ke@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Knights @ Bulls Knights @ Bulls

Follow on MiLB First Pitch  https //stza.co/+vK51-35

Shop  https //stza.co/+vK51-2M

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Knights @ Bulls
END:VALARM
DTSTART:20180612T230500Z
DTEND:20180613T020500Z
UID:tDWNYJzi6nW5I7UZQoNIG3ke@stanza.co
SUMMARY:Knights @ Bulls
DESCRIPTION:Knights @ Bulls\n\nFollow on MiLB First Pitch: https://stza.co/+vK51-35\n\nShop: https://stza.co/+vK51-2M\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144512Z
LAST-MODIFIED:20180213T144512Z
TRANSP:OPAQUE
END:VEVENT
* Knights @ Bulls
<2018-06-13 Wed 18:05-21:05>
:PROPERTIES:
:ID:       wvYG7JPt7kmUFxvElfiY1NtI@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Knights @ Bulls Knights @ Bulls

Follow on MiLB First Pitch  https //stza.co/+vK52-3O

Shop  https //stza.co/+vK52-1Q

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Knights @ Bulls
END:VALARM
DTSTART:20180613T230500Z
DTEND:20180614T020500Z
UID:wvYG7JPt7kmUFxvElfiY1NtI@stanza.co
SUMMARY:Knights @ Bulls
DESCRIPTION:Knights @ Bulls\n\nFollow on MiLB First Pitch: https://stza.co/+vK52-3O\n\nShop: https://stza.co/+vK52-1Q\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144512Z
LAST-MODIFIED:20180213T144512Z
TRANSP:OPAQUE
END:VEVENT
* Knights @ Tides
<2018-06-14 Thu 18:05-21:05>
:PROPERTIES:
:ID:       yhg2zV0qU02c6awE0OGOZM0f@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Knights @ Tides Knights @ Tides

Follow on MiLB First Pitch  https //stza.co/+vK5x-r

Shop  https //stza.co/+vK5x-2c

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Knights @ Tides
END:VALARM
DTSTART:20180614T230500Z
DTEND:20180615T020500Z
UID:yhg2zV0qU02c6awE0OGOZM0f@stanza.co
SUMMARY:Knights @ Tides
DESCRIPTION:Knights @ Tides\n\nFollow on MiLB First Pitch: https://stza.co/+vK5x-r\n\nShop: https://stza.co/+vK5x-2c\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144512Z
LAST-MODIFIED:20180213T144512Z
TRANSP:OPAQUE
END:VEVENT
* Knights @ Tides
<2018-06-15 Fri 18:05-21:05>
:PROPERTIES:
:ID:       fomeLHKydlirv-i2EnFJcCQM@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Knights @ Tides Knights @ Tides

Follow on MiLB First Pitch  https //stza.co/+vK5y-z

Shop  https //stza.co/+vK5y-3k

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Knights @ Tides
END:VALARM
DTSTART:20180615T230500Z
DTEND:20180616T020500Z
UID:fomeLHKydlirv-i2EnFJcCQM@stanza.co
SUMMARY:Knights @ Tides
DESCRIPTION:Knights @ Tides\n\nFollow on MiLB First Pitch: https://stza.co/+vK5y-z\n\nShop: https://stza.co/+vK5y-3k\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144512Z
LAST-MODIFIED:20180213T144512Z
TRANSP:OPAQUE
END:VEVENT
* Knights @ Tides
<2018-06-16 Sat 18:05-21:05>
:PROPERTIES:
:ID:       2-jQwOmGt0vIpY76TXhq3MIQ@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Knights @ Tides Knights @ Tides

Follow on MiLB First Pitch  https //stza.co/+vK5z-1f

Shop  https //stza.co/+vK5z-12

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Knights @ Tides
END:VALARM
DTSTART:20180616T230500Z
DTEND:20180617T020500Z
UID:2-jQwOmGt0vIpY76TXhq3MIQ@stanza.co
SUMMARY:Knights @ Tides
DESCRIPTION:Knights @ Tides\n\nFollow on MiLB First Pitch: https://stza.co/+vK5z-1f\n\nShop: https://stza.co/+vK5z-12\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144512Z
LAST-MODIFIED:20180213T144512Z
TRANSP:OPAQUE
END:VEVENT
* Knights @ Tides
<2018-06-17 Sun 12:05-15:05>
:PROPERTIES:
:ID:       ZpBDsG0ZY3YeA5ZAO0WDLXCJ@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Knights @ Tides Knights @ Tides

Follow on MiLB First Pitch  https //stza.co/+vK5A-J

Shop  https //stza.co/+vK5A-2h

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Knights @ Tides
END:VALARM
DTSTART:20180617T170500Z
DTEND:20180617T200500Z
UID:ZpBDsG0ZY3YeA5ZAO0WDLXCJ@stanza.co
SUMMARY:Knights @ Tides
DESCRIPTION:Knights @ Tides\n\nFollow on MiLB First Pitch: https://stza.co/+vK5A-J\n\nShop: https://stza.co/+vK5A-2h\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144512Z
LAST-MODIFIED:20180213T144512Z
TRANSP:OPAQUE
END:VEVENT
* Knights vs. Clippers
<2018-06-19 Tue 18:04-21:04>
:PROPERTIES:
:ID:       Gp1xpn8u7z93m04IassBfPUM@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Knights vs. Clippers Knights vs. Clippers

Follow on MiLB First Pitch  https //stza.co/+xOLX-o

Shop  https //stza.co/+xOLX-3R

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Knights vs. Clippers
END:VALARM
DTSTART:20180619T230400Z
DTEND:20180620T020400Z
UID:Gp1xpn8u7z93m04IassBfPUM@stanza.co
SUMMARY:Knights vs. Clippers
DESCRIPTION:Knights vs. Clippers\n\nFollow on MiLB First Pitch: https://stza.co/+xOLX-o\n\nShop: https://stza.co/+xOLX-3R\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144512Z
LAST-MODIFIED:20180213T144512Z
TRANSP:OPAQUE
END:VEVENT
* Knights vs. Clippers
<2018-06-20 Wed 18:04-21:04>
:PROPERTIES:
:ID:       83ruxva2mVfmuO-Y7_1rAS3h@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Knights vs. Clippers Knights vs. Clippers

Follow on MiLB First Pitch  https //stza.co/+xOL_-2q

Shop  https //stza.co/+xOL_-3e

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Knights vs. Clippers
END:VALARM
DTSTART:20180620T230400Z
DTEND:20180621T020400Z
UID:83ruxva2mVfmuO-Y7_1rAS3h@stanza.co
SUMMARY:Knights vs. Clippers
DESCRIPTION:Knights vs. Clippers\n\nFollow on MiLB First Pitch: https://stza.co/+xOL_-2q\n\nShop: https://stza.co/+xOL_-3e\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144512Z
LAST-MODIFIED:20180213T144512Z
TRANSP:OPAQUE
END:VEVENT
* Knights vs. Clippers
<2018-06-21 Thu 18:04-21:04>
:PROPERTIES:
:ID:       5szrHvbDHJ6vhJQS93oZOXt9@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Knights vs. Clippers Knights vs. Clippers

Follow on MiLB First Pitch  https //stza.co/+xOL$-2v

Shop  https //stza.co/+xOL$-N

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Knights vs. Clippers
END:VALARM
DTSTART:20180621T230400Z
DTEND:20180622T020400Z
UID:5szrHvbDHJ6vhJQS93oZOXt9@stanza.co
SUMMARY:Knights vs. Clippers
DESCRIPTION:Knights vs. Clippers\n\nFollow on MiLB First Pitch: https://stza.co/+xOL$-2v\n\nShop: https://stza.co/+xOL$-N\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144513Z
LAST-MODIFIED:20180213T144513Z
TRANSP:OPAQUE
END:VEVENT
* Knights vs. Mud Hens
<2018-06-22 Fri 18:04-21:04>
:PROPERTIES:
:ID:       YNy_gDYlhHvylbYBqyKRk3QQ@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Knights vs. Mud Hens Knights vs. Mud Hens

Follow on MiLB First Pitch  https //stza.co/+xOM1-1s

Shop  https //stza.co/+xOM1-3P

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Knights vs. Mud Hens
END:VALARM
DTSTART:20180622T230400Z
DTEND:20180623T020400Z
UID:YNy_gDYlhHvylbYBqyKRk3QQ@stanza.co
SUMMARY:Knights vs. Mud Hens
DESCRIPTION:Knights vs. Mud Hens\n\nFollow on MiLB First Pitch: https://stza.co/+xOM1-1s\n\nShop: https://stza.co/+xOM1-3P\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144513Z
LAST-MODIFIED:20180213T144513Z
TRANSP:OPAQUE
END:VEVENT
* Knights vs. Mud Hens
<2018-06-23 Sat 18:04-21:04>
:PROPERTIES:
:ID:       mT2RtiTxe5KFunWxhAs4gAcS@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Knights vs. Mud Hens Knights vs. Mud Hens

Follow on MiLB First Pitch  https //stza.co/+xOM4-2_

Shop  https //stza.co/+xOM4-2W

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Knights vs. Mud Hens
END:VALARM
DTSTART:20180623T230400Z
DTEND:20180624T020400Z
UID:mT2RtiTxe5KFunWxhAs4gAcS@stanza.co
SUMMARY:Knights vs. Mud Hens
DESCRIPTION:Knights vs. Mud Hens\n\nFollow on MiLB First Pitch: https://stza.co/+xOM4-2_\n\nShop: https://stza.co/+xOM4-2W\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144513Z
LAST-MODIFIED:20180213T144513Z
TRANSP:OPAQUE
END:VEVENT
* Knights vs. Mud Hens
<2018-06-24 Sun 13:05-16:05>
:PROPERTIES:
:ID:       PyJOlW_TzhVmsmSwBqlPN1Rg@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Knights vs. Mud Hens Knights vs. Mud Hens

Follow on MiLB First Pitch  https //stza.co/+vK3N-K

Shop  https //stza.co/+vK3N-2q

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Knights vs. Mud Hens
END:VALARM
DTSTART:20180624T180500Z
DTEND:20180624T210500Z
UID:PyJOlW_TzhVmsmSwBqlPN1Rg@stanza.co
SUMMARY:Knights vs. Mud Hens
DESCRIPTION:Knights vs. Mud Hens\n\nFollow on MiLB First Pitch: https://stza.co/+vK3N-K\n\nShop: https://stza.co/+vK3N-2q\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144513Z
LAST-MODIFIED:20180213T144513Z
TRANSP:OPAQUE
END:VEVENT
* Knights @ Bulls
<2018-06-25 Mon 18:05-21:05>
:PROPERTIES:
:ID:       a1OK8cdBnwp8aAT7gWMR4qUB@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Knights @ Bulls Knights @ Bulls

Follow on MiLB First Pitch  https //stza.co/+vK53-1D

Shop  https //stza.co/+vK53-2s

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Knights @ Bulls
END:VALARM
DTSTART:20180625T230500Z
DTEND:20180626T020500Z
UID:a1OK8cdBnwp8aAT7gWMR4qUB@stanza.co
SUMMARY:Knights @ Bulls
DESCRIPTION:Knights @ Bulls\n\nFollow on MiLB First Pitch: https://stza.co/+vK53-1D\n\nShop: https://stza.co/+vK53-2s\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144513Z
LAST-MODIFIED:20180213T144513Z
TRANSP:OPAQUE
END:VEVENT
* Knights @ Bulls
<2018-06-26 Tue 18:05-21:05>
:PROPERTIES:
:ID:       Sw5m8MBgACiQ4I8L-QnHqdm3@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Knights @ Bulls Knights @ Bulls

Follow on MiLB First Pitch  https //stza.co/+vK54-1C

Shop  https //stza.co/+vK54-r

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Knights @ Bulls
END:VALARM
DTSTART:20180626T230500Z
DTEND:20180627T020500Z
UID:Sw5m8MBgACiQ4I8L-QnHqdm3@stanza.co
SUMMARY:Knights @ Bulls
DESCRIPTION:Knights @ Bulls\n\nFollow on MiLB First Pitch: https://stza.co/+vK54-1C\n\nShop: https://stza.co/+vK54-r\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144513Z
LAST-MODIFIED:20180213T144513Z
TRANSP:OPAQUE
END:VEVENT
* Knights @ Bulls
<2018-06-27 Wed 12:05-15:05>
:PROPERTIES:
:ID:       vM3k5KEfCWmISWOxA40uoeDr@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Knights @ Bulls Knights @ Bulls

Follow on MiLB First Pitch  https //stza.co/+vK55-1w

Shop  https //stza.co/+vK55-J

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Knights @ Bulls
END:VALARM
DTSTART:20180627T170500Z
DTEND:20180627T200500Z
UID:vM3k5KEfCWmISWOxA40uoeDr@stanza.co
SUMMARY:Knights @ Bulls
DESCRIPTION:Knights @ Bulls\n\nFollow on MiLB First Pitch: https://stza.co/+vK55-1w\n\nShop: https://stza.co/+vK55-J\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144513Z
LAST-MODIFIED:20180213T144513Z
TRANSP:OPAQUE
END:VEVENT
* Knights vs. Stripers
<2018-06-28 Thu 18:04-21:04>
:PROPERTIES:
:ID:       fls8QJL893DSFgsyHJ_8ntAu@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Knights vs. Stripers Knights vs. Stripers

Follow on MiLB First Pitch  https //stza.co/+xOM6-1W

Shop  https //stza.co/+xOM6-3i

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Knights vs. Stripers
END:VALARM
DTSTART:20180628T230400Z
DTEND:20180629T020400Z
UID:fls8QJL893DSFgsyHJ_8ntAu@stanza.co
SUMMARY:Knights vs. Stripers
DESCRIPTION:Knights vs. Stripers\n\nFollow on MiLB First Pitch: https://stza.co/+xOM6-1W\n\nShop: https://stza.co/+xOM6-3i\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144513Z
LAST-MODIFIED:20180213T144513Z
TRANSP:OPAQUE
END:VEVENT
* Knights vs. Stripers
<2018-06-29 Fri 18:04-21:04>
:PROPERTIES:
:ID:       unXKrzexv2PEVqjUkJc-LAkE@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Knights vs. Stripers Knights vs. Stripers

Follow on MiLB First Pitch  https //stza.co/+xOM7-3A

Shop  https //stza.co/+xOM7-k

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Knights vs. Stripers
END:VALARM
DTSTART:20180629T230400Z
DTEND:20180630T020400Z
UID:unXKrzexv2PEVqjUkJc-LAkE@stanza.co
SUMMARY:Knights vs. Stripers
DESCRIPTION:Knights vs. Stripers\n\nFollow on MiLB First Pitch: https://stza.co/+xOM7-3A\n\nShop: https://stza.co/+xOM7-k\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144513Z
LAST-MODIFIED:20180213T144513Z
TRANSP:OPAQUE
END:VEVENT
* Knights vs. Stripers
<2018-06-30 Sat 18:04-21:04>
:PROPERTIES:
:ID:       OP-9-zCutkPSsckg8HocqDXW@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Knights vs. Stripers Knights vs. Stripers

Follow on MiLB First Pitch  https //stza.co/+xOM9-2I

Shop  https //stza.co/+xOM9-2E

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Knights vs. Stripers
END:VALARM
DTSTART:20180630T230400Z
DTEND:20180701T020400Z
UID:OP-9-zCutkPSsckg8HocqDXW@stanza.co
SUMMARY:Knights vs. Stripers
DESCRIPTION:Knights vs. Stripers\n\nFollow on MiLB First Pitch: https://stza.co/+xOM9-2I\n\nShop: https://stza.co/+xOM9-2E\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144513Z
LAST-MODIFIED:20180213T144513Z
TRANSP:OPAQUE
END:VEVENT
* Knights vs. Stripers
<2018-07-01 Sun 16:05-19:05>
:PROPERTIES:
:ID:       xQRfR9JxGWmQhr8xUHH_hqjm@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Knights vs. Stripers Knights vs. Stripers

Follow on MiLB First Pitch  https //stza.co/+vK3V-2k

Shop  https //stza.co/+vK3V-2Y

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Knights vs. Stripers
END:VALARM
DTSTART:20180701T210500Z
DTEND:20180702T000500Z
UID:xQRfR9JxGWmQhr8xUHH_hqjm@stanza.co
SUMMARY:Knights vs. Stripers
DESCRIPTION:Knights vs. Stripers\n\nFollow on MiLB First Pitch: https://stza.co/+vK3V-2k\n\nShop: https://stza.co/+vK3V-2Y\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144513Z
LAST-MODIFIED:20180213T144513Z
TRANSP:OPAQUE
END:VEVENT
* Knights @ Tides
<2018-07-02 Mon 18:05-21:05>
:PROPERTIES:
:ID:       iz1IaI9qNqliPbEf-7qhxzjL@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Knights @ Tides Knights @ Tides

Follow on MiLB First Pitch  https //stza.co/+vK5B-2y

Shop  https //stza.co/+vK5B-3r

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Knights @ Tides
END:VALARM
DTSTART:20180702T230500Z
DTEND:20180703T020500Z
UID:iz1IaI9qNqliPbEf-7qhxzjL@stanza.co
SUMMARY:Knights @ Tides
DESCRIPTION:Knights @ Tides\n\nFollow on MiLB First Pitch: https://stza.co/+vK5B-2y\n\nShop: https://stza.co/+vK5B-3r\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144513Z
LAST-MODIFIED:20180213T144513Z
TRANSP:OPAQUE
END:VEVENT
* Knights @ Tides
<2018-07-03 Tue 18:05-21:05>
:PROPERTIES:
:ID:       q9hrygDRmbtLiViVqPHMpdKA@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Knights @ Tides Knights @ Tides

Follow on MiLB First Pitch  https //stza.co/+vK5C-1w

Shop  https //stza.co/+vK5C-29

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Knights @ Tides
END:VALARM
DTSTART:20180703T230500Z
DTEND:20180704T020500Z
UID:q9hrygDRmbtLiViVqPHMpdKA@stanza.co
SUMMARY:Knights @ Tides
DESCRIPTION:Knights @ Tides\n\nFollow on MiLB First Pitch: https://stza.co/+vK5C-1w\n\nShop: https://stza.co/+vK5C-29\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144513Z
LAST-MODIFIED:20180213T144513Z
TRANSP:OPAQUE
END:VEVENT
* Knights vs. Bulls
<2018-07-04 Wed 17:05-20:05>
:PROPERTIES:
:ID:       A-gWICdUirHwx-Y4PsU51qhL@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Knights vs. Bulls Knights vs. Bulls

Follow on MiLB First Pitch  https //stza.co/+xOMc-3l

Shop  https //stza.co/+xOMc-1M

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Knights vs. Bulls
END:VALARM
DTSTART:20180704T220500Z
DTEND:20180705T010500Z
UID:A-gWICdUirHwx-Y4PsU51qhL@stanza.co
SUMMARY:Knights vs. Bulls
DESCRIPTION:Knights vs. Bulls\n\nFollow on MiLB First Pitch: https://stza.co/+xOMc-3l\n\nShop: https://stza.co/+xOMc-1M\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144513Z
LAST-MODIFIED:20180213T144513Z
TRANSP:OPAQUE
END:VEVENT
* Knights vs. Bulls
<2018-07-05 Thu 18:04-21:04>
:PROPERTIES:
:ID:       qxjd9H_2J9DRxHCmpZ2YFU98@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Knights vs. Bulls Knights vs. Bulls

Follow on MiLB First Pitch  https //stza.co/+xOMd-F

Shop  https //stza.co/+xOMd-1o

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Knights vs. Bulls
END:VALARM
DTSTART:20180705T230400Z
DTEND:20180706T020400Z
UID:qxjd9H_2J9DRxHCmpZ2YFU98@stanza.co
SUMMARY:Knights vs. Bulls
DESCRIPTION:Knights vs. Bulls\n\nFollow on MiLB First Pitch: https://stza.co/+xOMd-F\n\nShop: https://stza.co/+xOMd-1o\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144513Z
LAST-MODIFIED:20180213T144513Z
TRANSP:OPAQUE
END:VEVENT
* Knights @ Stripers
<2018-07-06 Fri 18:05-21:05>
:PROPERTIES:
:ID:       ZBuS7J2C6DQ71ooGkjfWeQ-M@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Knights @ Stripers Knights @ Stripers

Follow on MiLB First Pitch  https //stza.co/+vK5e-3k

Shop  https //stza.co/+vK5e-3

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Knights @ Stripers
END:VALARM
DTSTART:20180706T230500Z
DTEND:20180707T020500Z
UID:ZBuS7J2C6DQ71ooGkjfWeQ-M@stanza.co
SUMMARY:Knights @ Stripers
DESCRIPTION:Knights @ Stripers\n\nFollow on MiLB First Pitch: https://stza.co/+vK5e-3k\n\nShop: https://stza.co/+vK5e-3\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144513Z
LAST-MODIFIED:20180213T144513Z
TRANSP:OPAQUE
END:VEVENT
* Knights @ Stripers
<2018-07-07 Sat 17:05-20:05>
:PROPERTIES:
:ID:       ySp8A9YMTFgABvZTv8QiOjJU@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Knights @ Stripers Knights @ Stripers

Follow on MiLB First Pitch  https //stza.co/+vK5f-1s

Shop  https //stza.co/+vK5f-2o

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Knights @ Stripers
END:VALARM
DTSTART:20180707T220500Z
DTEND:20180708T010500Z
UID:ySp8A9YMTFgABvZTv8QiOjJU@stanza.co
SUMMARY:Knights @ Stripers
DESCRIPTION:Knights @ Stripers\n\nFollow on MiLB First Pitch: https://stza.co/+vK5f-1s\n\nShop: https://stza.co/+vK5f-2o\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144513Z
LAST-MODIFIED:20180213T144513Z
TRANSP:OPAQUE
END:VEVENT
* Knights @ Stripers
<2018-07-08 Sun 12:05-15:05>
:PROPERTIES:
:ID:       mSwLEcahnvtdXFg8zXjTiRmG@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Knights @ Stripers Knights @ Stripers

Follow on MiLB First Pitch  https //stza.co/+vK5g-2M

Shop  https //stza.co/+vK5g-3I

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Knights @ Stripers
END:VALARM
DTSTART:20180708T170500Z
DTEND:20180708T200500Z
UID:mSwLEcahnvtdXFg8zXjTiRmG@stanza.co
SUMMARY:Knights @ Stripers
DESCRIPTION:Knights @ Stripers\n\nFollow on MiLB First Pitch: https://stza.co/+vK5g-2M\n\nShop: https://stza.co/+vK5g-3I\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144513Z
LAST-MODIFIED:20180213T144513Z
TRANSP:OPAQUE
END:VEVENT
* Knights @ Bulls
<2018-07-12 Thu 18:05-21:05>
:PROPERTIES:
:ID:       n93tk8aP51Qlf8d7KQFBCdjJ@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Knights @ Bulls Knights @ Bulls

Follow on MiLB First Pitch  https //stza.co/+vK56-1x

Shop  https //stza.co/+vK56-1W

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Knights @ Bulls
END:VALARM
DTSTART:20180712T230500Z
DTEND:20180713T020500Z
UID:n93tk8aP51Qlf8d7KQFBCdjJ@stanza.co
SUMMARY:Knights @ Bulls
DESCRIPTION:Knights @ Bulls\n\nFollow on MiLB First Pitch: https://stza.co/+vK56-1x\n\nShop: https://stza.co/+vK56-1W\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144513Z
LAST-MODIFIED:20180213T144513Z
TRANSP:OPAQUE
END:VEVENT
* Knights @ Bulls
<2018-07-13 Fri 18:05-21:05>
:PROPERTIES:
:ID:       oJrMqkeAXG2vSHbFfTx3a2OJ@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Knights @ Bulls Knights @ Bulls

Follow on MiLB First Pitch  https //stza.co/+vK57-1Q

Shop  https //stza.co/+vK57-1u

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Knights @ Bulls
END:VALARM
DTSTART:20180713T230500Z
DTEND:20180714T020500Z
UID:oJrMqkeAXG2vSHbFfTx3a2OJ@stanza.co
SUMMARY:Knights @ Bulls
DESCRIPTION:Knights @ Bulls\n\nFollow on MiLB First Pitch: https://stza.co/+vK57-1Q\n\nShop: https://stza.co/+vK57-1u\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144513Z
LAST-MODIFIED:20180213T144513Z
TRANSP:OPAQUE
END:VEVENT
* Knights @ Bulls
<2018-07-14 Sat 17:35-20:35>
:PROPERTIES:
:ID:       OgCfN2sH9ZUh7G9fQGzXZWgX@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Knights @ Bulls Knights @ Bulls

Follow on MiLB First Pitch  https //stza.co/+vK58-3z

Shop  https //stza.co/+vK58-2A

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Knights @ Bulls
END:VALARM
DTSTART:20180714T223500Z
DTEND:20180715T013500Z
UID:OgCfN2sH9ZUh7G9fQGzXZWgX@stanza.co
SUMMARY:Knights @ Bulls
DESCRIPTION:Knights @ Bulls\n\nFollow on MiLB First Pitch: https://stza.co/+vK58-3z\n\nShop: https://stza.co/+vK58-2A\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144513Z
LAST-MODIFIED:20180213T144513Z
TRANSP:OPAQUE
END:VEVENT
* Knights @ Bulls
<2018-07-15 Sun 16:05-19:05>
:PROPERTIES:
:ID:       7pxQr0KI-e85L95Eb1DLlMJz@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Knights @ Bulls Knights @ Bulls

Follow on MiLB First Pitch  https //stza.co/+vK59-1l

Shop  https //stza.co/+vK59-1t

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Knights @ Bulls
END:VALARM
DTSTART:20180715T210500Z
DTEND:20180716T000500Z
UID:7pxQr0KI-e85L95Eb1DLlMJz@stanza.co
SUMMARY:Knights @ Bulls
DESCRIPTION:Knights @ Bulls\n\nFollow on MiLB First Pitch: https://stza.co/+vK59-1l\n\nShop: https://stza.co/+vK59-1t\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144513Z
LAST-MODIFIED:20180213T144513Z
TRANSP:OPAQUE
END:VEVENT
* Knights vs. Red Sox
<2018-07-16 Mon 18:04-21:04>
:PROPERTIES:
:ID:       M0RT84z1YutE7BJrGheqnJNL@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Knights vs. Red Sox Knights vs. Red Sox

Follow on MiLB First Pitch  https //stza.co/+xOMg-3G

Shop  https //stza.co/+xOMg-2k

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Knights vs. Red Sox
END:VALARM
DTSTART:20180716T230400Z
DTEND:20180717T020400Z
UID:M0RT84z1YutE7BJrGheqnJNL@stanza.co
SUMMARY:Knights vs. Red Sox
DESCRIPTION:Knights vs. Red Sox\n\nFollow on MiLB First Pitch: https://stza.co/+xOMg-3G\n\nShop: https://stza.co/+xOMg-2k\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144513Z
LAST-MODIFIED:20180213T144513Z
TRANSP:OPAQUE
END:VEVENT
* Knights vs. Red Sox
<2018-07-17 Tue 18:04-21:04>
:PROPERTIES:
:ID:       vs5eMvl09Fp8b17b4Fal_Q8l@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Knights vs. Red Sox Knights vs. Red Sox

Follow on MiLB First Pitch  https //stza.co/+xOMi-2k

Shop  https //stza.co/+xOMi-2D

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Knights vs. Red Sox
END:VALARM
DTSTART:20180717T230400Z
DTEND:20180718T020400Z
UID:vs5eMvl09Fp8b17b4Fal_Q8l@stanza.co
SUMMARY:Knights vs. Red Sox
DESCRIPTION:Knights vs. Red Sox\n\nFollow on MiLB First Pitch: https://stza.co/+xOMi-2k\n\nShop: https://stza.co/+xOMi-2D\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144513Z
LAST-MODIFIED:20180213T144513Z
TRANSP:OPAQUE
END:VEVENT
* Knights vs. Red Sox
<2018-07-18 Wed 18:04-21:04>
:PROPERTIES:
:ID:       L5Jr6-r_cS2cYVOBWaxr3hFK@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Knights vs. Red Sox Knights vs. Red Sox

Follow on MiLB First Pitch  https //stza.co/+xOMk-2i

Shop  https //stza.co/+xOMk-1x

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Knights vs. Red Sox
END:VALARM
DTSTART:20180718T230400Z
DTEND:20180719T020400Z
UID:L5Jr6-r_cS2cYVOBWaxr3hFK@stanza.co
SUMMARY:Knights vs. Red Sox
DESCRIPTION:Knights vs. Red Sox\n\nFollow on MiLB First Pitch: https://stza.co/+xOMk-2i\n\nShop: https://stza.co/+xOMk-1x\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144513Z
LAST-MODIFIED:20180213T144513Z
TRANSP:OPAQUE
END:VEVENT
* Knights vs. Red Sox
<2018-07-19 Thu 18:04-21:04>
:PROPERTIES:
:ID:       tEs7KMCQNFeLuvc77DtJ63xq@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Knights vs. Red Sox Knights vs. Red Sox

Follow on MiLB First Pitch  https //stza.co/+xOMm-1S

Shop  https //stza.co/+xOMm-3F

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Knights vs. Red Sox
END:VALARM
DTSTART:20180719T230400Z
DTEND:20180720T020400Z
UID:tEs7KMCQNFeLuvc77DtJ63xq@stanza.co
SUMMARY:Knights vs. Red Sox
DESCRIPTION:Knights vs. Red Sox\n\nFollow on MiLB First Pitch: https://stza.co/+xOMm-1S\n\nShop: https://stza.co/+xOMm-3F\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144513Z
LAST-MODIFIED:20180213T144513Z
TRANSP:OPAQUE
END:VEVENT
* Knights vs. Indians
<2018-07-20 Fri 18:04-21:04>
:PROPERTIES:
:ID:       mz34xa7udrAYZZltTKtuQRwz@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Knights vs. Indians Knights vs. Indians

Follow on MiLB First Pitch  https //stza.co/+xOMo-3q

Shop  https //stza.co/+xOMo-1Z

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Knights vs. Indians
END:VALARM
DTSTART:20180720T230400Z
DTEND:20180721T020400Z
UID:mz34xa7udrAYZZltTKtuQRwz@stanza.co
SUMMARY:Knights vs. Indians
DESCRIPTION:Knights vs. Indians\n\nFollow on MiLB First Pitch: https://stza.co/+xOMo-3q\n\nShop: https://stza.co/+xOMo-1Z\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144513Z
LAST-MODIFIED:20180213T144513Z
TRANSP:OPAQUE
END:VEVENT
* Knights vs. Indians
<2018-07-21 Sat 18:04-21:04>
:PROPERTIES:
:ID:       Rb3gklWixU_XgGCxonQcbcUU@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Knights vs. Indians Knights vs. Indians

Follow on MiLB First Pitch  https //stza.co/+xOMp-2h

Shop  https //stza.co/+xOMp-1n

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Knights vs. Indians
END:VALARM
DTSTART:20180721T230400Z
DTEND:20180722T020400Z
UID:Rb3gklWixU_XgGCxonQcbcUU@stanza.co
SUMMARY:Knights vs. Indians
DESCRIPTION:Knights vs. Indians\n\nFollow on MiLB First Pitch: https://stza.co/+xOMp-2h\n\nShop: https://stza.co/+xOMp-1n\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144513Z
LAST-MODIFIED:20180213T144513Z
TRANSP:OPAQUE
END:VEVENT
* Knights vs. Indians
<2018-07-22 Sun 16:05-19:05>
:PROPERTIES:
:ID:       g4-pyIfo59kqD_8hd8pRPvAr@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Knights vs. Indians Knights vs. Indians

Follow on MiLB First Pitch  https //stza.co/+vK4b-3X

Shop  https //stza.co/+vK4b-3K

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Knights vs. Indians
END:VALARM
DTSTART:20180722T210500Z
DTEND:20180723T000500Z
UID:g4-pyIfo59kqD_8hd8pRPvAr@stanza.co
SUMMARY:Knights vs. Indians
DESCRIPTION:Knights vs. Indians\n\nFollow on MiLB First Pitch: https://stza.co/+vK4b-3X\n\nShop: https://stza.co/+vK4b-3K\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144513Z
LAST-MODIFIED:20180213T144513Z
TRANSP:OPAQUE
END:VEVENT
* Knights @ RailRiders
<2018-07-24 Tue 18:05-21:05>
:PROPERTIES:
:ID:       aWIpfdho-LlCXFGaDKtr6Dmr@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Knights @ RailRiders Knights @ RailRiders

Follow on MiLB First Pitch  https //stza.co/+vK5M-2D

Shop  https //stza.co/+vK5M-1_

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Knights @ RailRiders
END:VALARM
DTSTART:20180724T230500Z
DTEND:20180725T020500Z
UID:aWIpfdho-LlCXFGaDKtr6Dmr@stanza.co
SUMMARY:Knights @ RailRiders
DESCRIPTION:Knights @ RailRiders\n\nFollow on MiLB First Pitch: https://stza.co/+vK5M-2D\n\nShop: https://stza.co/+vK5M-1_\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144513Z
LAST-MODIFIED:20180213T144513Z
TRANSP:OPAQUE
END:VEVENT
* Knights @ RailRiders
<2018-07-25 Wed 18:05-21:05>
:PROPERTIES:
:ID:       7IkC6K_lxxGr2AFicqpjh-il@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Knights @ RailRiders Knights @ RailRiders

Follow on MiLB First Pitch  https //stza.co/+vK5N-13

Shop  https //stza.co/+vK5N-3G

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Knights @ RailRiders
END:VALARM
DTSTART:20180725T230500Z
DTEND:20180726T020500Z
UID:7IkC6K_lxxGr2AFicqpjh-il@stanza.co
SUMMARY:Knights @ RailRiders
DESCRIPTION:Knights @ RailRiders\n\nFollow on MiLB First Pitch: https://stza.co/+vK5N-13\n\nShop: https://stza.co/+vK5N-3G\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144513Z
LAST-MODIFIED:20180213T144513Z
TRANSP:OPAQUE
END:VEVENT
* Knights @ RailRiders
<2018-07-26 Thu 11:05-14:05>
:PROPERTIES:
:ID:       8HkwfAt0xGUhswiWLu_SIu10@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Knights @ RailRiders Knights @ RailRiders

Follow on MiLB First Pitch  https //stza.co/+vK5O-2I

Shop  https //stza.co/+vK5O-1P

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Knights @ RailRiders
END:VALARM
DTSTART:20180726T160500Z
DTEND:20180726T190500Z
UID:8HkwfAt0xGUhswiWLu_SIu10@stanza.co
SUMMARY:Knights @ RailRiders
DESCRIPTION:Knights @ RailRiders\n\nFollow on MiLB First Pitch: https://stza.co/+vK5O-2I\n\nShop: https://stza.co/+vK5O-1P\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144513Z
LAST-MODIFIED:20180213T144513Z
TRANSP:OPAQUE
END:VEVENT
* Knights @ Red Sox
<2018-07-27 Fri 18:05-21:05>
:PROPERTIES:
:ID:       tYcX4KLUyNh4l6-gFmWXHA3b@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Knights @ Red Sox Knights @ Red Sox

Buy tickets here  https //stza.co/~vK5G

Follow on MiLB First Pitch  https //stza.co/+vK5G-3d

Shop  https //stza.co/+vK5G-14

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Knights @ Red Sox
END:VALARM
DTSTART:20180727T230500Z
DTEND:20180728T020500Z
UID:tYcX4KLUyNh4l6-gFmWXHA3b@stanza.co
SUMMARY:Knights @ Red Sox
DESCRIPTION:Knights @ Red Sox\n\nBuy tickets here: https://stza.co/~vK5G\n\nFollow on MiLB First Pitch: https://stza.co/+vK5G-3d\n\nShop: https://stza.co/+vK5G-14\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144513Z
LAST-MODIFIED:20180213T144513Z
TRANSP:OPAQUE
END:VEVENT
* Knights @ Red Sox
<2018-07-28 Sat 17:15-20:15>
:PROPERTIES:
:ID:       TeODYjkl2ER32T-xTv9fKjFs@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Knights @ Red Sox Knights @ Red Sox

Buy tickets here  https //stza.co/~vK5H

Follow on MiLB First Pitch  https //stza.co/+vK5H-2K

Shop  https //stza.co/+vK5H-3p

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Knights @ Red Sox
END:VALARM
DTSTART:20180728T221500Z
DTEND:20180729T011500Z
UID:TeODYjkl2ER32T-xTv9fKjFs@stanza.co
SUMMARY:Knights @ Red Sox
DESCRIPTION:Knights @ Red Sox\n\nBuy tickets here: https://stza.co/~vK5H\n\nFollow on MiLB First Pitch: https://stza.co/+vK5H-2K\n\nShop: https://stza.co/+vK5H-3p\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144513Z
LAST-MODIFIED:20180213T144513Z
TRANSP:OPAQUE
END:VEVENT
* Knights @ Red Sox
<2018-07-29 Sun 12:35-15:35>
:PROPERTIES:
:ID:       -wRzGtWexIIJe62OeQwoX1Uj@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Knights @ Red Sox Knights @ Red Sox

Buy tickets here  https //stza.co/~vK5I

Follow on MiLB First Pitch  https //stza.co/+vK5I-1l

Shop  https //stza.co/+vK5I-8

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Knights @ Red Sox
END:VALARM
DTSTART:20180729T173500Z
DTEND:20180729T203500Z
UID:-wRzGtWexIIJe62OeQwoX1Uj@stanza.co
SUMMARY:Knights @ Red Sox
DESCRIPTION:Knights @ Red Sox\n\nBuy tickets here: https://stza.co/~vK5I\n\nFollow on MiLB First Pitch: https://stza.co/+vK5I-1l\n\nShop: https://stza.co/+vK5I-8\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144513Z
LAST-MODIFIED:20180213T144513Z
TRANSP:OPAQUE
END:VEVENT
* Knights vs. Tides
<2018-07-30 Mon 18:04-21:04>
:PROPERTIES:
:ID:       ae7O58Wo_r7F92g-ibkvOAnS@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Knights vs. Tides Knights vs. Tides

Follow on MiLB First Pitch  https //stza.co/+xOMs-

Shop  https //stza.co/+xOMs-1f

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Knights vs. Tides
END:VALARM
DTSTART:20180730T230400Z
DTEND:20180731T020400Z
UID:ae7O58Wo_r7F92g-ibkvOAnS@stanza.co
SUMMARY:Knights vs. Tides
DESCRIPTION:Knights vs. Tides\n\nFollow on MiLB First Pitch: https://stza.co/+xOMs-\n\nShop: https://stza.co/+xOMs-1f\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144513Z
LAST-MODIFIED:20180213T144513Z
TRANSP:OPAQUE
END:VEVENT
* Knights vs. Tides
<2018-07-31 Tue 18:04-21:04>
:PROPERTIES:
:ID:       w6g8XcPz6sxtxYAnZrpVHFsD@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Knights vs. Tides Knights vs. Tides

Follow on MiLB First Pitch  https //stza.co/+xOMt-g

Shop  https //stza.co/+xOMt-_

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Knights vs. Tides
END:VALARM
DTSTART:20180731T230400Z
DTEND:20180801T020400Z
UID:w6g8XcPz6sxtxYAnZrpVHFsD@stanza.co
SUMMARY:Knights vs. Tides
DESCRIPTION:Knights vs. Tides\n\nFollow on MiLB First Pitch: https://stza.co/+xOMt-g\n\nShop: https://stza.co/+xOMt-_\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144513Z
LAST-MODIFIED:20180213T144513Z
TRANSP:OPAQUE
END:VEVENT
* Knights vs. Tides
<2018-08-01 Wed 18:04-21:04>
:PROPERTIES:
:ID:       efy4nUOoN3sziYvinswXTcp4@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Knights vs. Tides Knights vs. Tides

Follow on MiLB First Pitch  https //stza.co/+xOMv-1k

Shop  https //stza.co/+xOMv-3C

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Knights vs. Tides
END:VALARM
DTSTART:20180801T230400Z
DTEND:20180802T020400Z
UID:efy4nUOoN3sziYvinswXTcp4@stanza.co
SUMMARY:Knights vs. Tides
DESCRIPTION:Knights vs. Tides\n\nFollow on MiLB First Pitch: https://stza.co/+xOMv-1k\n\nShop: https://stza.co/+xOMv-3C\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144513Z
LAST-MODIFIED:20180213T144513Z
TRANSP:OPAQUE
END:VEVENT
* Knights vs. Tides
<2018-08-02 Thu 18:04-21:04>
:PROPERTIES:
:ID:       LaOkudKT1YZEzCrthqkTL9WH@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Knights vs. Tides Knights vs. Tides

Follow on MiLB First Pitch  https //stza.co/+xOMx-u

Shop  https //stza.co/+xOMx-3D

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Knights vs. Tides
END:VALARM
DTSTART:20180802T230400Z
DTEND:20180803T020400Z
UID:LaOkudKT1YZEzCrthqkTL9WH@stanza.co
SUMMARY:Knights vs. Tides
DESCRIPTION:Knights vs. Tides\n\nFollow on MiLB First Pitch: https://stza.co/+xOMx-u\n\nShop: https://stza.co/+xOMx-3D\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144513Z
LAST-MODIFIED:20180213T144513Z
TRANSP:OPAQUE
END:VEVENT
* Knights vs. Bulls
<2018-08-03 Fri 18:04-21:04>
:PROPERTIES:
:ID:       9wtYRkUYl_8Na8HN_79A-0iO@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Knights vs. Bulls Knights vs. Bulls

Follow on MiLB First Pitch  https //stza.co/+xOMz-2T

Shop  https //stza.co/+xOMz-2V

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Knights vs. Bulls
END:VALARM
DTSTART:20180803T230400Z
DTEND:20180804T020400Z
UID:9wtYRkUYl_8Na8HN_79A-0iO@stanza.co
SUMMARY:Knights vs. Bulls
DESCRIPTION:Knights vs. Bulls\n\nFollow on MiLB First Pitch: https://stza.co/+xOMz-2T\n\nShop: https://stza.co/+xOMz-2V\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144513Z
LAST-MODIFIED:20180213T144513Z
TRANSP:OPAQUE
END:VEVENT
* Knights vs. Bulls
<2018-08-04 Sat 18:04-21:04>
:PROPERTIES:
:ID:       zyHA-j8R-jp2QfoRxCPn_vKK@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Knights vs. Bulls Knights vs. Bulls

Follow on MiLB First Pitch  https //stza.co/+xOMC-1n

Shop  https //stza.co/+xOMC-G

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Knights vs. Bulls
END:VALARM
DTSTART:20180804T230400Z
DTEND:20180805T020400Z
UID:zyHA-j8R-jp2QfoRxCPn_vKK@stanza.co
SUMMARY:Knights vs. Bulls
DESCRIPTION:Knights vs. Bulls\n\nFollow on MiLB First Pitch: https://stza.co/+xOMC-1n\n\nShop: https://stza.co/+xOMC-G\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144513Z
LAST-MODIFIED:20180213T144513Z
TRANSP:OPAQUE
END:VEVENT
* Knights vs. Bulls
<2018-08-05 Sun 16:05-19:05>
:PROPERTIES:
:ID:       Mg7kidrNbhr0_ap09Q3cpQNm@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Knights vs. Bulls Knights vs. Bulls

Follow on MiLB First Pitch  https //stza.co/+vK4p-1W

Shop  https //stza.co/+vK4p-1Q

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Knights vs. Bulls
END:VALARM
DTSTART:20180805T210500Z
DTEND:20180806T000500Z
UID:Mg7kidrNbhr0_ap09Q3cpQNm@stanza.co
SUMMARY:Knights vs. Bulls
DESCRIPTION:Knights vs. Bulls\n\nFollow on MiLB First Pitch: https://stza.co/+vK4p-1W\n\nShop: https://stza.co/+vK4p-1Q\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144513Z
LAST-MODIFIED:20180213T144513Z
TRANSP:OPAQUE
END:VEVENT
* Knights @ Chiefs
<2018-08-07 Tue 17:35-20:35>
:PROPERTIES:
:ID:       lFu_3hf_TGgV40sAA3ibc2Jz@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Knights @ Chiefs Knights @ Chiefs

Follow on MiLB First Pitch  https //stza.co/+vK5P-3c

Shop  https //stza.co/+vK5P-3q

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Knights @ Chiefs
END:VALARM
DTSTART:20180807T223500Z
DTEND:20180808T013500Z
UID:lFu_3hf_TGgV40sAA3ibc2Jz@stanza.co
SUMMARY:Knights @ Chiefs
DESCRIPTION:Knights @ Chiefs\n\nFollow on MiLB First Pitch: https://stza.co/+vK5P-3c\n\nShop: https://stza.co/+vK5P-3q\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144513Z
LAST-MODIFIED:20180213T144513Z
TRANSP:OPAQUE
END:VEVENT
* Knights @ Chiefs
<2018-08-08 Wed 17:35-20:35>
:PROPERTIES:
:ID:       LJmV4r_4ouX1q9hXMvMCiJrX@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Knights @ Chiefs Knights @ Chiefs

Follow on MiLB First Pitch  https //stza.co/+uXmW-e

Shop  https //stza.co/+uXmW-T

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Knights @ Chiefs
END:VALARM
DTSTART:20180808T223500Z
DTEND:20180809T013500Z
UID:LJmV4r_4ouX1q9hXMvMCiJrX@stanza.co
SUMMARY:Knights @ Chiefs
DESCRIPTION:Knights @ Chiefs\n\nFollow on MiLB First Pitch: https://stza.co/+uXmW-e\n\nShop: https://stza.co/+uXmW-T\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144513Z
LAST-MODIFIED:20180213T144513Z
TRANSP:OPAQUE
END:VEVENT
* Knights @ Chiefs
<2018-08-09 Thu 17:35-20:35>
:PROPERTIES:
:ID:       Cq2QlUVAQ2sISnavbWhPXE_v@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Knights @ Chiefs Knights @ Chiefs

Follow on MiLB First Pitch  https //stza.co/+uWFm-2I

Shop  https //stza.co/+uWFm-3l

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Knights @ Chiefs
END:VALARM
DTSTART:20180809T223500Z
DTEND:20180810T013500Z
UID:Cq2QlUVAQ2sISnavbWhPXE_v@stanza.co
SUMMARY:Knights @ Chiefs
DESCRIPTION:Knights @ Chiefs\n\nFollow on MiLB First Pitch: https://stza.co/+uWFm-2I\n\nShop: https://stza.co/+uWFm-3l\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144513Z
LAST-MODIFIED:20180213T144513Z
TRANSP:OPAQUE
END:VEVENT
* Knights @ Red Wings
<2018-08-10 Fri 18:05-21:05>
:PROPERTIES:
:ID:       4iCHhFLIwe51MzTYezY76P4G@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Knights @ Red Wings Knights @ Red Wings

Follow on MiLB First Pitch  https //stza.co/+vK5J-2D

Shop  https //stza.co/+vK5J-3N

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Knights @ Red Wings
END:VALARM
DTSTART:20180810T230500Z
DTEND:20180811T020500Z
UID:4iCHhFLIwe51MzTYezY76P4G@stanza.co
SUMMARY:Knights @ Red Wings
DESCRIPTION:Knights @ Red Wings\n\nFollow on MiLB First Pitch: https://stza.co/+vK5J-2D\n\nShop: https://stza.co/+vK5J-3N\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144513Z
LAST-MODIFIED:20180213T144513Z
TRANSP:OPAQUE
END:VEVENT
* Knights @ Red Wings
<2018-08-11 Sat 18:05-21:05>
:PROPERTIES:
:ID:       JwCeKrvFuvuN3CalUPFHrknU@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Knights @ Red Wings Knights @ Red Wings

Follow on MiLB First Pitch  https //stza.co/+vK5K-3S

Shop  https //stza.co/+vK5K-2v

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Knights @ Red Wings
END:VALARM
DTSTART:20180811T230500Z
DTEND:20180812T020500Z
UID:JwCeKrvFuvuN3CalUPFHrknU@stanza.co
SUMMARY:Knights @ Red Wings
DESCRIPTION:Knights @ Red Wings\n\nFollow on MiLB First Pitch: https://stza.co/+vK5K-3S\n\nShop: https://stza.co/+vK5K-2v\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144513Z
LAST-MODIFIED:20180213T144513Z
TRANSP:OPAQUE
END:VEVENT
* Knights @ Red Wings
<2018-08-12 Sun 12:05-15:05>
:PROPERTIES:
:ID:       wnM5Im9IwL2vW5K7ABpEWI-v@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Knights @ Red Wings Knights @ Red Wings

Follow on MiLB First Pitch  https //stza.co/+vK5L-t

Shop  https //stza.co/+vK5L-o

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Knights @ Red Wings
END:VALARM
DTSTART:20180812T170500Z
DTEND:20180812T200500Z
UID:wnM5Im9IwL2vW5K7ABpEWI-v@stanza.co
SUMMARY:Knights @ Red Wings
DESCRIPTION:Knights @ Red Wings\n\nFollow on MiLB First Pitch: https://stza.co/+vK5L-t\n\nShop: https://stza.co/+vK5L-o\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144513Z
LAST-MODIFIED:20180213T144513Z
TRANSP:OPAQUE
END:VEVENT
* Knights vs. Bisons
<2018-08-13 Mon 18:04-21:04>
:PROPERTIES:
:ID:       6LagqBl46UcFY-8sq8bMq-_A@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Knights vs. Bisons Knights vs. Bisons

Follow on MiLB First Pitch  https //stza.co/+xOME-j

Shop  https //stza.co/+xOME-1E

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Knights vs. Bisons
END:VALARM
DTSTART:20180813T230400Z
DTEND:20180814T020400Z
UID:6LagqBl46UcFY-8sq8bMq-_A@stanza.co
SUMMARY:Knights vs. Bisons
DESCRIPTION:Knights vs. Bisons\n\nFollow on MiLB First Pitch: https://stza.co/+xOME-j\n\nShop: https://stza.co/+xOME-1E\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144513Z
LAST-MODIFIED:20180213T144513Z
TRANSP:OPAQUE
END:VEVENT
* Knights vs. Bisons
<2018-08-14 Tue 18:04-21:04>
:PROPERTIES:
:ID:       JQ9WsndniG95zaLK-OvTLWNe@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Knights vs. Bisons Knights vs. Bisons

Follow on MiLB First Pitch  https //stza.co/+xOMF-2O

Shop  https //stza.co/+xOMF-22

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Knights vs. Bisons
END:VALARM
DTSTART:20180814T230400Z
DTEND:20180815T020400Z
UID:JQ9WsndniG95zaLK-OvTLWNe@stanza.co
SUMMARY:Knights vs. Bisons
DESCRIPTION:Knights vs. Bisons\n\nFollow on MiLB First Pitch: https://stza.co/+xOMF-2O\n\nShop: https://stza.co/+xOMF-22\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144513Z
LAST-MODIFIED:20180213T144513Z
TRANSP:OPAQUE
END:VEVENT
* Knights vs. Bisons
<2018-08-15 Wed 18:04-21:04>
:PROPERTIES:
:ID:       RCOaaN2ClVi3BWsumZZ3u3rL@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Knights vs. Bisons Knights vs. Bisons

Follow on MiLB First Pitch  https //stza.co/+xOMH-2H

Shop  https //stza.co/+xOMH-Q

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Knights vs. Bisons
END:VALARM
DTSTART:20180815T230400Z
DTEND:20180816T020400Z
UID:RCOaaN2ClVi3BWsumZZ3u3rL@stanza.co
SUMMARY:Knights vs. Bisons
DESCRIPTION:Knights vs. Bisons\n\nFollow on MiLB First Pitch: https://stza.co/+xOMH-2H\n\nShop: https://stza.co/+xOMH-Q\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144513Z
LAST-MODIFIED:20180213T144513Z
TRANSP:OPAQUE
END:VEVENT
* Knights vs. Bats
<2018-08-16 Thu 18:04-21:04>
:PROPERTIES:
:ID:       QJbNN3FPvebDpHMWB70896ZF@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Knights vs. Bats Knights vs. Bats

Follow on MiLB First Pitch  https //stza.co/+xOMJ-j

Shop  https //stza.co/+xOMJ-3D

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Knights vs. Bats
END:VALARM
DTSTART:20180816T230400Z
DTEND:20180817T020400Z
UID:QJbNN3FPvebDpHMWB70896ZF@stanza.co
SUMMARY:Knights vs. Bats
DESCRIPTION:Knights vs. Bats\n\nFollow on MiLB First Pitch: https://stza.co/+xOMJ-j\n\nShop: https://stza.co/+xOMJ-3D\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144513Z
LAST-MODIFIED:20180213T144513Z
TRANSP:OPAQUE
END:VEVENT
* Knights vs. Bats
<2018-08-17 Fri 18:04-21:04>
:PROPERTIES:
:ID:       yi22EcmXSiQ4aAqD8dHRHGns@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Knights vs. Bats Knights vs. Bats

Follow on MiLB First Pitch  https //stza.co/+xOMM-1M

Shop  https //stza.co/+xOMM-29

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Knights vs. Bats
END:VALARM
DTSTART:20180817T230400Z
DTEND:20180818T020400Z
UID:yi22EcmXSiQ4aAqD8dHRHGns@stanza.co
SUMMARY:Knights vs. Bats
DESCRIPTION:Knights vs. Bats\n\nFollow on MiLB First Pitch: https://stza.co/+xOMM-1M\n\nShop: https://stza.co/+xOMM-29\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144513Z
LAST-MODIFIED:20180213T144513Z
TRANSP:OPAQUE
END:VEVENT
* Knights vs. Bats
<2018-08-18 Sat 18:04-21:04>
:PROPERTIES:
:ID:       9Mi5nf9CzPMnAChygRNtLhMD@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Knights vs. Bats Knights vs. Bats

Follow on MiLB First Pitch  https //stza.co/+xOMN-3q

Shop  https //stza.co/+xOMN-2m

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Knights vs. Bats
END:VALARM
DTSTART:20180818T230400Z
DTEND:20180819T020400Z
UID:9Mi5nf9CzPMnAChygRNtLhMD@stanza.co
SUMMARY:Knights vs. Bats
DESCRIPTION:Knights vs. Bats\n\nFollow on MiLB First Pitch: https://stza.co/+xOMN-3q\n\nShop: https://stza.co/+xOMN-2m\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144513Z
LAST-MODIFIED:20180213T144513Z
TRANSP:OPAQUE
END:VEVENT
* Knights vs. Bats
<2018-08-19 Sun 16:05-19:05>
:PROPERTIES:
:ID:       pnsHj8YdtTEEKMM-b0Z7dnzN@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Knights vs. Bats Knights vs. Bats

Follow on MiLB First Pitch  https //stza.co/+vK4D-12

Shop  https //stza.co/+vK4D-v

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Knights vs. Bats
END:VALARM
DTSTART:20180819T210500Z
DTEND:20180820T000500Z
UID:pnsHj8YdtTEEKMM-b0Z7dnzN@stanza.co
SUMMARY:Knights vs. Bats
DESCRIPTION:Knights vs. Bats\n\nFollow on MiLB First Pitch: https://stza.co/+vK4D-12\n\nShop: https://stza.co/+vK4D-v\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144513Z
LAST-MODIFIED:20180213T144513Z
TRANSP:OPAQUE
END:VEVENT
* Knights @ Tides
<2018-08-21 Tue 18:05-21:05>
:PROPERTIES:
:ID:       A4dPR_oANtJFWJ3z2Ag3HJyf@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Knights @ Tides Knights @ Tides

Follow on MiLB First Pitch  https //stza.co/+vK5D-e

Shop  https //stza.co/+vK5D-10

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Knights @ Tides
END:VALARM
DTSTART:20180821T230500Z
DTEND:20180822T020500Z
UID:A4dPR_oANtJFWJ3z2Ag3HJyf@stanza.co
SUMMARY:Knights @ Tides
DESCRIPTION:Knights @ Tides\n\nFollow on MiLB First Pitch: https://stza.co/+vK5D-e\n\nShop: https://stza.co/+vK5D-10\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144513Z
LAST-MODIFIED:20180213T144513Z
TRANSP:OPAQUE
END:VEVENT
* Knights @ Tides
<2018-08-22 Wed 18:05-21:05>
:PROPERTIES:
:ID:       ApLVJaKp_yePVmPQbSvbBw_D@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Knights @ Tides Knights @ Tides

Follow on MiLB First Pitch  https //stza.co/+vK5E-1v

Shop  https //stza.co/+vK5E-3W

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Knights @ Tides
END:VALARM
DTSTART:20180822T230500Z
DTEND:20180823T020500Z
UID:ApLVJaKp_yePVmPQbSvbBw_D@stanza.co
SUMMARY:Knights @ Tides
DESCRIPTION:Knights @ Tides\n\nFollow on MiLB First Pitch: https://stza.co/+vK5E-1v\n\nShop: https://stza.co/+vK5E-3W\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144513Z
LAST-MODIFIED:20180213T144513Z
TRANSP:OPAQUE
END:VEVENT
* Knights @ Tides
<2018-08-23 Thu 11:05-14:05>
:PROPERTIES:
:ID:       TvAGD-byqR4rT3PZgK4SDL7V@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Knights @ Tides Knights @ Tides

Follow on MiLB First Pitch  https //stza.co/+vK5F-1f

Shop  https //stza.co/+vK5F-33

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Knights @ Tides
END:VALARM
DTSTART:20180823T160500Z
DTEND:20180823T190500Z
UID:TvAGD-byqR4rT3PZgK4SDL7V@stanza.co
SUMMARY:Knights @ Tides
DESCRIPTION:Knights @ Tides\n\nFollow on MiLB First Pitch: https://stza.co/+vK5F-1f\n\nShop: https://stza.co/+vK5F-33\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144513Z
LAST-MODIFIED:20180213T144513Z
TRANSP:OPAQUE
END:VEVENT
* Knights vs. Stripers
<2018-08-24 Fri 18:04-21:04>
:PROPERTIES:
:ID:       l7VYQyM_Kama7EcaVjM-jmfs@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Knights vs. Stripers Knights vs. Stripers

Follow on MiLB First Pitch  https //stza.co/+xOMQ-1g

Shop  https //stza.co/+xOMQ-1u

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Knights vs. Stripers
END:VALARM
DTSTART:20180824T230400Z
DTEND:20180825T020400Z
UID:l7VYQyM_Kama7EcaVjM-jmfs@stanza.co
SUMMARY:Knights vs. Stripers
DESCRIPTION:Knights vs. Stripers\n\nFollow on MiLB First Pitch: https://stza.co/+xOMQ-1g\n\nShop: https://stza.co/+xOMQ-1u\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144513Z
LAST-MODIFIED:20180213T144513Z
TRANSP:OPAQUE
END:VEVENT
* Knights vs. Stripers
<2018-08-25 Sat 18:04-21:04>
:PROPERTIES:
:ID:       X_W9JMtwKrsVVppP5diW2IvX@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Knights vs. Stripers Knights vs. Stripers

Follow on MiLB First Pitch  https //stza.co/+xOMR-3b

Shop  https //stza.co/+xOMR-1Y

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Knights vs. Stripers
END:VALARM
DTSTART:20180825T230400Z
DTEND:20180826T020400Z
UID:X_W9JMtwKrsVVppP5diW2IvX@stanza.co
SUMMARY:Knights vs. Stripers
DESCRIPTION:Knights vs. Stripers\n\nFollow on MiLB First Pitch: https://stza.co/+xOMR-3b\n\nShop: https://stza.co/+xOMR-1Y\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144513Z
LAST-MODIFIED:20180213T144513Z
TRANSP:OPAQUE
END:VEVENT
* Knights vs. Stripers
<2018-08-26 Sun 16:05-19:05>
:PROPERTIES:
:ID:       JpvwMS9G7J3gkO4lI8iCgZQl@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Knights vs. Stripers Knights vs. Stripers

Follow on MiLB First Pitch  https //stza.co/+vK4J-3R

Shop  https //stza.co/+vK4J-m

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Knights vs. Stripers
END:VALARM
DTSTART:20180826T210500Z
DTEND:20180827T000500Z
UID:JpvwMS9G7J3gkO4lI8iCgZQl@stanza.co
SUMMARY:Knights vs. Stripers
DESCRIPTION:Knights vs. Stripers\n\nFollow on MiLB First Pitch: https://stza.co/+vK4J-3R\n\nShop: https://stza.co/+vK4J-m\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144513Z
LAST-MODIFIED:20180213T144513Z
TRANSP:OPAQUE
END:VEVENT
* Knights vs. Stripers
<2018-08-27 Mon 18:04-21:04>
:PROPERTIES:
:ID:       _F8yxWtsvDXLW2FQPDTJtPQ6@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Knights vs. Stripers Knights vs. Stripers

Follow on MiLB First Pitch  https //stza.co/+xOMU-2V

Shop  https //stza.co/+xOMU-2i

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Knights vs. Stripers
END:VALARM
DTSTART:20180827T230400Z
DTEND:20180828T020400Z
UID:_F8yxWtsvDXLW2FQPDTJtPQ6@stanza.co
SUMMARY:Knights vs. Stripers
DESCRIPTION:Knights vs. Stripers\n\nFollow on MiLB First Pitch: https://stza.co/+xOMU-2V\n\nShop: https://stza.co/+xOMU-2i\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144513Z
LAST-MODIFIED:20180213T144513Z
TRANSP:OPAQUE
END:VEVENT
* Knights vs. Bulls
<2018-08-28 Tue 18:04-21:04>
:PROPERTIES:
:ID:       hs0CSQANi28vArXexPnlFlFs@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Knights vs. Bulls Knights vs. Bulls

Follow on MiLB First Pitch  https //stza.co/+xOMW-Q

Shop  https //stza.co/+xOMW-2

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Knights vs. Bulls
END:VALARM
DTSTART:20180828T230400Z
DTEND:20180829T020400Z
UID:hs0CSQANi28vArXexPnlFlFs@stanza.co
SUMMARY:Knights vs. Bulls
DESCRIPTION:Knights vs. Bulls\n\nFollow on MiLB First Pitch: https://stza.co/+xOMW-Q\n\nShop: https://stza.co/+xOMW-2\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144513Z
LAST-MODIFIED:20180213T144513Z
TRANSP:OPAQUE
END:VEVENT
* Knights vs. Bulls
<2018-08-29 Wed 18:04-21:04>
:PROPERTIES:
:ID:       3D-E28AAkN0TIOQeGfajJfV3@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Knights vs. Bulls Knights vs. Bulls

Follow on MiLB First Pitch  https //stza.co/+xOMY-3V

Shop  https //stza.co/+xOMY-2i

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Knights vs. Bulls
END:VALARM
DTSTART:20180829T230400Z
DTEND:20180830T020400Z
UID:3D-E28AAkN0TIOQeGfajJfV3@stanza.co
SUMMARY:Knights vs. Bulls
DESCRIPTION:Knights vs. Bulls\n\nFollow on MiLB First Pitch: https://stza.co/+xOMY-3V\n\nShop: https://stza.co/+xOMY-2i\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144513Z
LAST-MODIFIED:20180213T144513Z
TRANSP:OPAQUE
END:VEVENT
* Knights vs. Bulls
<2018-08-30 Thu 18:04-21:04>
:PROPERTIES:
:ID:       gx_4UTZCtn_2n2nJG4vPkfmZ@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Knights vs. Bulls Knights vs. Bulls

Follow on MiLB First Pitch  https //stza.co/+xOMZ-1l

Shop  https //stza.co/+xOMZ-2c

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Knights vs. Bulls
END:VALARM
DTSTART:20180830T230400Z
DTEND:20180831T020400Z
UID:gx_4UTZCtn_2n2nJG4vPkfmZ@stanza.co
SUMMARY:Knights vs. Bulls
DESCRIPTION:Knights vs. Bulls\n\nFollow on MiLB First Pitch: https://stza.co/+xOMZ-1l\n\nShop: https://stza.co/+xOMZ-2c\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144513Z
LAST-MODIFIED:20180213T144513Z
TRANSP:OPAQUE
END:VEVENT
* Knights @ Stripers
<2018-08-31 Fri 18:05-21:05>
:PROPERTIES:
:ID:       -cTkqJw7k0HCx-iN7XujDcJU@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Knights @ Stripers Knights @ Stripers

Follow on MiLB First Pitch  https //stza.co/+vK5h-G

Shop  https //stza.co/+vK5h-16

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Knights @ Stripers
END:VALARM
DTSTART:20180831T230500Z
DTEND:20180901T020500Z
UID:-cTkqJw7k0HCx-iN7XujDcJU@stanza.co
SUMMARY:Knights @ Stripers
DESCRIPTION:Knights @ Stripers\n\nFollow on MiLB First Pitch: https://stza.co/+vK5h-G\n\nShop: https://stza.co/+vK5h-16\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144513Z
LAST-MODIFIED:20180213T144513Z
TRANSP:OPAQUE
END:VEVENT
* Knights @ Stripers
<2018-09-01 Sat 17:05-20:05>
:PROPERTIES:
:ID:       ZUDi5xU3mgsU-CGI3lpeaZHg@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Knights @ Stripers Knights @ Stripers

Follow on MiLB First Pitch  https //stza.co/+vK5i-2a

Shop  https //stza.co/+vK5i-29

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Knights @ Stripers
END:VALARM
DTSTART:20180901T220500Z
DTEND:20180902T010500Z
UID:ZUDi5xU3mgsU-CGI3lpeaZHg@stanza.co
SUMMARY:Knights @ Stripers
DESCRIPTION:Knights @ Stripers\n\nFollow on MiLB First Pitch: https://stza.co/+vK5i-2a\n\nShop: https://stza.co/+vK5i-29\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144513Z
LAST-MODIFIED:20180213T144513Z
TRANSP:OPAQUE
END:VEVENT
* Knights @ Stripers
<2018-09-02 Sun 12:05-15:05>
:PROPERTIES:
:ID:       S5MlIxdWEDTXWZRW03wGcSHD@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Knights @ Stripers Knights @ Stripers

Follow on MiLB First Pitch  https //stza.co/+vK5j-2j

Shop  https //stza.co/+vK5j-4

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Knights @ Stripers
END:VALARM
DTSTART:20180902T170500Z
DTEND:20180902T200500Z
UID:S5MlIxdWEDTXWZRW03wGcSHD@stanza.co
SUMMARY:Knights @ Stripers
DESCRIPTION:Knights @ Stripers\n\nFollow on MiLB First Pitch: https://stza.co/+vK5j-2j\n\nShop: https://stza.co/+vK5j-4\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144513Z
LAST-MODIFIED:20180213T144513Z
TRANSP:OPAQUE
END:VEVENT
* Knights @ Stripers
<2018-09-03 Mon 12:05-15:05>
:PROPERTIES:
:ID:       xC1QL0UqP87a24BzsFiuwiEv@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Knights @ Stripers Knights @ Stripers

Follow on MiLB First Pitch  https //stza.co/+vK5k-3S

Shop  https //stza.co/+vK5k-V

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Knights @ Stripers
END:VALARM
DTSTART:20180903T170500Z
DTEND:20180903T200500Z
UID:xC1QL0UqP87a24BzsFiuwiEv@stanza.co
SUMMARY:Knights @ Stripers
DESCRIPTION:Knights @ Stripers\n\nFollow on MiLB First Pitch: https://stza.co/+vK5k-3S\n\nShop: https://stza.co/+vK5k-V\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144513Z
LAST-MODIFIED:20180213T144513Z
TRANSP:OPAQUE
END:VEVENT
