#+TITLE:       Main Google calendar entries
#+AUTHOR:      Eric S Fraga
#+EMAIL:       e.fraga@ucl.ac.uk
#+DESCRIPTION: converted using the ical2org awk script
#+CATEGORY:    google
#+STARTUP:     hidestars
#+STARTUP:     overview

* COMMENT original iCal preamble

* Clippers @ Indians
<2018-04-06 Fri 18:15-21:15>
:PROPERTIES:
:ID:       Oxc7lS7biHZBo3XTMBrj6Exv@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Clippers @ Indians Clippers @ Indians

Follow on MiLB First Pitch  https //stza.co/+uWRU-1c

Shop  https //stza.co/+uWRU-3j

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Clippers @ Indians
END:VALARM
DTSTART:20180406T231500Z
DTEND:20180407T021500Z
UID:Oxc7lS7biHZBo3XTMBrj6Exv@stanza.co
SUMMARY:Clippers @ Indians
DESCRIPTION:Clippers @ Indians\n\nFollow on MiLB First Pitch: https://stza.co/+uWRU-1c\n\nShop: https://stza.co/+uWRU-3j\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144516Z
LAST-MODIFIED:20180213T144516Z
TRANSP:OPAQUE
END:VEVENT
* Clippers @ Indians
<2018-04-07 Sat 18:05-21:05>
:PROPERTIES:
:ID:       gDG-IehADtZGTdjMNziXUukX@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Clippers @ Indians Clippers @ Indians

Follow on MiLB First Pitch  https //stza.co/+uWS5-v

Shop  https //stza.co/+uWS5-1v

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Clippers @ Indians
END:VALARM
DTSTART:20180407T230500Z
DTEND:20180408T020500Z
UID:gDG-IehADtZGTdjMNziXUukX@stanza.co
SUMMARY:Clippers @ Indians
DESCRIPTION:Clippers @ Indians\n\nFollow on MiLB First Pitch: https://stza.co/+uWS5-v\n\nShop: https://stza.co/+uWS5-1v\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144516Z
LAST-MODIFIED:20180213T144516Z
TRANSP:OPAQUE
END:VEVENT
* Clippers @ Indians
<2018-04-08 Sun 12:35-15:35>
:PROPERTIES:
:ID:       MgghMY5fVESaEZ-DcMQmfiTj@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Clippers @ Indians Clippers @ Indians

Follow on MiLB First Pitch  https //stza.co/+uWSh-1x

Shop  https //stza.co/+uWSh-2v

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Clippers @ Indians
END:VALARM
DTSTART:20180408T173500Z
DTEND:20180408T203500Z
UID:MgghMY5fVESaEZ-DcMQmfiTj@stanza.co
SUMMARY:Clippers @ Indians
DESCRIPTION:Clippers @ Indians\n\nFollow on MiLB First Pitch: https://stza.co/+uWSh-1x\n\nShop: https://stza.co/+uWSh-2v\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144516Z
LAST-MODIFIED:20180213T144516Z
TRANSP:OPAQUE
END:VEVENT
* Clippers @ Bats
<2018-04-09 Mon 17:30-20:30>
:PROPERTIES:
:ID:       WLwcyCaldjwFI3aTILDMOQhu@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Clippers @ Bats Clippers @ Bats

Buy tickets here  https //stza.co/~uWU$

Follow on MiLB First Pitch  https //stza.co/+uWU$-3a

Shop  https //stza.co/+uWU$-1a

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Clippers @ Bats
END:VALARM
DTSTART:20180409T223000Z
DTEND:20180410T013000Z
UID:WLwcyCaldjwFI3aTILDMOQhu@stanza.co
SUMMARY:Clippers @ Bats
DESCRIPTION:Clippers @ Bats\n\nBuy tickets here: https://stza.co/~uWU$\n\nFollow on MiLB First Pitch: https://stza.co/+uWU$-3a\n\nShop: https://stza.co/+uWU$-1a\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144516Z
LAST-MODIFIED:20180213T144516Z
TRANSP:OPAQUE
END:VEVENT
* Clippers @ Bats
<2018-04-10 Tue 17:30-20:30>
:PROPERTIES:
:ID:       3AR7H55_7uFROdyqFvXNA4KD@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Clippers @ Bats Clippers @ Bats

Buy tickets here  https //stza.co/~uWVd

Follow on MiLB First Pitch  https //stza.co/+uWVd-d

Shop  https //stza.co/+uWVd-3k

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Clippers @ Bats
END:VALARM
DTSTART:20180410T223000Z
DTEND:20180411T013000Z
UID:3AR7H55_7uFROdyqFvXNA4KD@stanza.co
SUMMARY:Clippers @ Bats
DESCRIPTION:Clippers @ Bats\n\nBuy tickets here: https://stza.co/~uWVd\n\nFollow on MiLB First Pitch: https://stza.co/+uWVd-d\n\nShop: https://stza.co/+uWVd-3k\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144516Z
LAST-MODIFIED:20180213T144516Z
TRANSP:OPAQUE
END:VEVENT
* Clippers @ Bats
<2018-04-11 Wed 17:30-20:30>
:PROPERTIES:
:ID:       LLQek1cfw6qeD_Zom4wHM9jY@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Clippers @ Bats Clippers @ Bats

Buy tickets here  https //stza.co/~uWVs

Follow on MiLB First Pitch  https //stza.co/+uWVs-3J

Shop  https //stza.co/+uWVs-12

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Clippers @ Bats
END:VALARM
DTSTART:20180411T223000Z
DTEND:20180412T013000Z
UID:LLQek1cfw6qeD_Zom4wHM9jY@stanza.co
SUMMARY:Clippers @ Bats
DESCRIPTION:Clippers @ Bats\n\nBuy tickets here: https://stza.co/~uWVs\n\nFollow on MiLB First Pitch: https://stza.co/+uWVs-3J\n\nShop: https://stza.co/+uWVs-12\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144516Z
LAST-MODIFIED:20180213T144516Z
TRANSP:OPAQUE
END:VEVENT
* Clippers vs. Bulls
<2018-04-12 Thu 17:35-20:35>
:PROPERTIES:
:ID:       Tvu6_yqkYkr1-L4BAIHfwwzx@stanza.co
:LOCATION: Swipe to get tickets for the game tonight. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Clippers vs. Bulls Clippers vs. Bulls

Buy tickets here  https //stza.co/~uWIF

Follow on MiLB First Pitch  https //stza.co/+uWIF-F

Shop  https //stza.co/+uWIF-14

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Clippers vs. Bulls
END:VALARM
DTSTART:20180412T223500Z
DTEND:20180413T013500Z
UID:Tvu6_yqkYkr1-L4BAIHfwwzx@stanza.co
SUMMARY:Clippers vs. Bulls
DESCRIPTION:Clippers vs. Bulls\n\nBuy tickets here: https://stza.co/~uWIF\n\nFollow on MiLB First Pitch: https://stza.co/+uWIF-F\n\nShop: https://stza.co/+uWIF-14\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Swipe to get tickets for the game tonight. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144516Z
LAST-MODIFIED:20180213T144516Z
TRANSP:OPAQUE
END:VEVENT
* Clippers vs. Bulls
<2018-04-13 Fri 17:35-20:35>
:PROPERTIES:
:ID:       LcbVmQLmHlczwm4MkORs2fYl@stanza.co
:LOCATION: Swipe for last minute tickets for tonight's game. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Clippers vs. Bulls Clippers vs. Bulls

Buy tickets here  https //stza.co/~uWIJ

Follow on MiLB First Pitch  https //stza.co/+uWIJ-30

Shop  https //stza.co/+uWIJ-3B

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Clippers vs. Bulls
END:VALARM
DTSTART:20180413T223500Z
DTEND:20180414T013500Z
UID:LcbVmQLmHlczwm4MkORs2fYl@stanza.co
SUMMARY:Clippers vs. Bulls
DESCRIPTION:Clippers vs. Bulls\n\nBuy tickets here: https://stza.co/~uWIJ\n\nFollow on MiLB First Pitch: https://stza.co/+uWIJ-30\n\nShop: https://stza.co/+uWIJ-3B\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Swipe for last minute tickets for tonight's game. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144516Z
LAST-MODIFIED:20180213T144516Z
TRANSP:OPAQUE
END:VEVENT
* Clippers vs. Bulls
<2018-04-14 Sat 17:35-20:35>
:PROPERTIES:
:ID:       qQ0Uacf1ToVz2soo5sLfeEoj@stanza.co
:LOCATION: Ready for the game? Swipe for tickets and more information.
:STATUS:   CONFIRMED
:END:

Clippers vs. Bulls Clippers vs. Bulls

Buy tickets here  https //stza.co/~uWIR

Follow on MiLB First Pitch  https //stza.co/+uWIR-1

Shop  https //stza.co/+uWIR-3a

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Clippers vs. Bulls
END:VALARM
DTSTART:20180414T223500Z
DTEND:20180415T013500Z
UID:qQ0Uacf1ToVz2soo5sLfeEoj@stanza.co
SUMMARY:Clippers vs. Bulls
DESCRIPTION:Clippers vs. Bulls\n\nBuy tickets here: https://stza.co/~uWIR\n\nFollow on MiLB First Pitch: https://stza.co/+uWIR-1\n\nShop: https://stza.co/+uWIR-3a\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Swipe for tickets and more information.
STATUS:CONFIRMED
CREATED:20180213T144516Z
LAST-MODIFIED:20180213T144516Z
TRANSP:OPAQUE
END:VEVENT
* Clippers vs. Bulls
<2018-04-15 Sun 13:05-16:05>
:PROPERTIES:
:ID:       G5WtPztFS3biRUamre7jZ0RX@stanza.co
:LOCATION: Looking for something to do tonight? Get tickets here for tonight’s game and view promotions.
:STATUS:   CONFIRMED
:END:

Clippers vs. Bulls Clippers vs. Bulls

Buy tickets here  https //stza.co/~uWIW

Follow on MiLB First Pitch  https //stza.co/+uWIW-31

Shop  https //stza.co/+uWIW-3D

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Clippers vs. Bulls
END:VALARM
DTSTART:20180415T180500Z
DTEND:20180415T210500Z
UID:G5WtPztFS3biRUamre7jZ0RX@stanza.co
SUMMARY:Clippers vs. Bulls
DESCRIPTION:Clippers vs. Bulls\n\nBuy tickets here: https://stza.co/~uWIW\n\nFollow on MiLB First Pitch: https://stza.co/+uWIW-31\n\nShop: https://stza.co/+uWIW-3D\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Looking for something to do tonight? Get tickets here for tonight’s game and view promotions.
STATUS:CONFIRMED
CREATED:20180213T144516Z
LAST-MODIFIED:20180213T144516Z
TRANSP:OPAQUE
END:VEVENT
* Clippers vs. Red Sox
<2018-04-16 Mon 17:35-20:35>
:PROPERTIES:
:ID:       ce4JrSBHAm90uXv73HxxhXEk@stanza.co
:LOCATION: Great seats still available for tonight’s game. Purchase them here.
:STATUS:   CONFIRMED
:END:

Clippers vs. Red Sox Clippers vs. Red Sox

Buy tickets here  https //stza.co/~uWJ1

Follow on MiLB First Pitch  https //stza.co/+uWJ1-2E

Shop  https //stza.co/+uWJ1-1I

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Clippers vs. Red Sox
END:VALARM
DTSTART:20180416T223500Z
DTEND:20180417T013500Z
UID:ce4JrSBHAm90uXv73HxxhXEk@stanza.co
SUMMARY:Clippers vs. Red Sox
DESCRIPTION:Clippers vs. Red Sox\n\nBuy tickets here: https://stza.co/~uWJ1\n\nFollow on MiLB First Pitch: https://stza.co/+uWJ1-2E\n\nShop: https://stza.co/+uWJ1-1I\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Great seats still available for tonight’s game. Purchase them here.
STATUS:CONFIRMED
CREATED:20180213T144516Z
LAST-MODIFIED:20180213T144516Z
TRANSP:OPAQUE
END:VEVENT
* Clippers vs. Red Sox
<2018-04-17 Tue 17:35-20:35>
:PROPERTIES:
:ID:       sJEasfjkrrMXHKuE30sBMLJm@stanza.co
:LOCATION: Need something fun to do tonight? Get Clippers tickets here.
:STATUS:   CONFIRMED
:END:

Clippers vs. Red Sox Clippers vs. Red Sox

Buy tickets here  https //stza.co/~uWJb

Follow on MiLB First Pitch  https //stza.co/+uWJb-B

Shop  https //stza.co/+uWJb-2O

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Clippers vs. Red Sox
END:VALARM
DTSTART:20180417T223500Z
DTEND:20180418T013500Z
UID:sJEasfjkrrMXHKuE30sBMLJm@stanza.co
SUMMARY:Clippers vs. Red Sox
DESCRIPTION:Clippers vs. Red Sox\n\nBuy tickets here: https://stza.co/~uWJb\n\nFollow on MiLB First Pitch: https://stza.co/+uWJb-B\n\nShop: https://stza.co/+uWJb-2O\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Need something fun to do tonight? Get Clippers tickets here.
STATUS:CONFIRMED
CREATED:20180213T144516Z
LAST-MODIFIED:20180213T144516Z
TRANSP:OPAQUE
END:VEVENT
* Clippers vs. Red Sox
<2018-04-18 Wed 17:35-20:35>
:PROPERTIES:
:ID:       0aB0taPkKaS2W4CuXb7tc2rY@stanza.co
:LOCATION: Don’t miss out! Clippers tickets still available here.
:STATUS:   CONFIRMED
:END:

Clippers vs. Red Sox Clippers vs. Red Sox

Buy tickets here  https //stza.co/~uWJl

Follow on MiLB First Pitch  https //stza.co/+uWJl-20

Shop  https //stza.co/+uWJl-38

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Clippers vs. Red Sox
END:VALARM
DTSTART:20180418T223500Z
DTEND:20180419T013500Z
UID:0aB0taPkKaS2W4CuXb7tc2rY@stanza.co
SUMMARY:Clippers vs. Red Sox
DESCRIPTION:Clippers vs. Red Sox\n\nBuy tickets here: https://stza.co/~uWJl\n\nFollow on MiLB First Pitch: https://stza.co/+uWJl-20\n\nShop: https://stza.co/+uWJl-38\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don’t miss out! Clippers tickets still available here.
STATUS:CONFIRMED
CREATED:20180213T144516Z
LAST-MODIFIED:20180213T144516Z
TRANSP:OPAQUE
END:VEVENT
* Clippers @ Red Wings
<2018-04-20 Fri 17:35-20:35>
:PROPERTIES:
:ID:       0kqVPZEk1X8LC6jdh-ZXHk16@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Clippers @ Red Wings Clippers @ Red Wings

Follow on MiLB First Pitch  https //stza.co/+uWZ8-36

Shop  https //stza.co/+uWZ8-Y

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Clippers @ Red Wings
END:VALARM
DTSTART:20180420T223500Z
DTEND:20180421T013500Z
UID:0kqVPZEk1X8LC6jdh-ZXHk16@stanza.co
SUMMARY:Clippers @ Red Wings
DESCRIPTION:Clippers @ Red Wings\n\nFollow on MiLB First Pitch: https://stza.co/+uWZ8-36\n\nShop: https://stza.co/+uWZ8-Y\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144516Z
LAST-MODIFIED:20180213T144516Z
TRANSP:OPAQUE
END:VEVENT
* Clippers @ Red Wings
<2018-04-21 Sat 12:05-15:05>
:PROPERTIES:
:ID:       ErOvKzH6bBX_roymqzvcMDKN@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Clippers @ Red Wings Clippers @ Red Wings

Follow on MiLB First Pitch  https //stza.co/+vK5Q-g

Shop  https //stza.co/+vK5Q-1h

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Clippers @ Red Wings
END:VALARM
DTSTART:20180421T170500Z
DTEND:20180421T200500Z
UID:ErOvKzH6bBX_roymqzvcMDKN@stanza.co
SUMMARY:Clippers @ Red Wings
DESCRIPTION:Clippers @ Red Wings\n\nFollow on MiLB First Pitch: https://stza.co/+vK5Q-g\n\nShop: https://stza.co/+vK5Q-1h\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144516Z
LAST-MODIFIED:20180213T144516Z
TRANSP:OPAQUE
END:VEVENT
* Clippers @ Red Wings
<2018-04-22 Sun 12:05-15:05>
:PROPERTIES:
:ID:       L5KAIVU1uZgd1tqSmTMFBKkS@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Clippers @ Red Wings Clippers @ Red Wings

Follow on MiLB First Pitch  https //stza.co/+vK5R-1F

Shop  https //stza.co/+vK5R-11

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Clippers @ Red Wings
END:VALARM
DTSTART:20180422T170500Z
DTEND:20180422T200500Z
UID:L5KAIVU1uZgd1tqSmTMFBKkS@stanza.co
SUMMARY:Clippers @ Red Wings
DESCRIPTION:Clippers @ Red Wings\n\nFollow on MiLB First Pitch: https://stza.co/+vK5R-1F\n\nShop: https://stza.co/+vK5R-11\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144516Z
LAST-MODIFIED:20180213T144516Z
TRANSP:OPAQUE
END:VEVENT
* Clippers @ RailRiders
<2018-04-23 Mon 17:35-20:35>
:PROPERTIES:
:ID:       SPRqOAru8xsGE7KXubhJ8XJg@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Clippers @ RailRiders Clippers @ RailRiders

Follow on MiLB First Pitch  https //stza.co/+uWZL-2u

Shop  https //stza.co/+uWZL-1

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Clippers @ RailRiders
END:VALARM
DTSTART:20180423T223500Z
DTEND:20180424T013500Z
UID:SPRqOAru8xsGE7KXubhJ8XJg@stanza.co
SUMMARY:Clippers @ RailRiders
DESCRIPTION:Clippers @ RailRiders\n\nFollow on MiLB First Pitch: https://stza.co/+uWZL-2u\n\nShop: https://stza.co/+uWZL-1\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144516Z
LAST-MODIFIED:20180213T144516Z
TRANSP:OPAQUE
END:VEVENT
* Clippers @ RailRiders
<2018-04-24 Tue 17:35-20:35>
:PROPERTIES:
:ID:       67CS_gRM_ebzvrpsUItrbrFH@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Clippers @ RailRiders Clippers @ RailRiders

Follow on MiLB First Pitch  https //stza.co/+uWZZ-3P

Shop  https //stza.co/+uWZZ-3l

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Clippers @ RailRiders
END:VALARM
DTSTART:20180424T223500Z
DTEND:20180425T013500Z
UID:67CS_gRM_ebzvrpsUItrbrFH@stanza.co
SUMMARY:Clippers @ RailRiders
DESCRIPTION:Clippers @ RailRiders\n\nFollow on MiLB First Pitch: https://stza.co/+uWZZ-3P\n\nShop: https://stza.co/+uWZZ-3l\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144516Z
LAST-MODIFIED:20180213T144516Z
TRANSP:OPAQUE
END:VEVENT
* Clippers @ RailRiders
<2018-04-25 Wed 17:35-20:35>
:PROPERTIES:
:ID:       jfuSfBsZcvM3QSC89PNODZ-c@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Clippers @ RailRiders Clippers @ RailRiders

Follow on MiLB First Pitch  https //stza.co/+uW_8-2K

Shop  https //stza.co/+uW_8-3N

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Clippers @ RailRiders
END:VALARM
DTSTART:20180425T223500Z
DTEND:20180426T013500Z
UID:jfuSfBsZcvM3QSC89PNODZ-c@stanza.co
SUMMARY:Clippers @ RailRiders
DESCRIPTION:Clippers @ RailRiders\n\nFollow on MiLB First Pitch: https://stza.co/+uW_8-2K\n\nShop: https://stza.co/+uW_8-3N\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144516Z
LAST-MODIFIED:20180213T144516Z
TRANSP:OPAQUE
END:VEVENT
* Clippers vs. Indians
<2018-04-27 Fri 18:15-21:15>
:PROPERTIES:
:ID:       _UI4xg_NQP95UEn-H8AuY7nw@stanza.co
:LOCATION: Swipe to get tickets for the game tonight. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Clippers vs. Indians Clippers vs. Indians

Buy tickets here  https //stza.co/~uWJv

Follow on MiLB First Pitch  https //stza.co/+uWJv-2h

Shop  https //stza.co/+uWJv-3B

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Clippers vs. Indians
END:VALARM
DTSTART:20180427T231500Z
DTEND:20180428T021500Z
UID:_UI4xg_NQP95UEn-H8AuY7nw@stanza.co
SUMMARY:Clippers vs. Indians
DESCRIPTION:Clippers vs. Indians\n\nBuy tickets here: https://stza.co/~uWJv\n\nFollow on MiLB First Pitch: https://stza.co/+uWJv-2h\n\nShop: https://stza.co/+uWJv-3B\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Swipe to get tickets for the game tonight. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144516Z
LAST-MODIFIED:20180213T144516Z
TRANSP:OPAQUE
END:VEVENT
* Clippers vs. Indians
<2018-04-28 Sat 18:15-21:15>
:PROPERTIES:
:ID:       ISg30Y7bg4WIiMqhLJHJ1WbJ@stanza.co
:LOCATION: Swipe for last minute tickets for tonight's game. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Clippers vs. Indians Clippers vs. Indians

Buy tickets here  https //stza.co/~uWJF

Follow on MiLB First Pitch  https //stza.co/+uWJF-29

Shop  https //stza.co/+uWJF-C

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Clippers vs. Indians
END:VALARM
DTSTART:20180428T231500Z
DTEND:20180429T021500Z
UID:ISg30Y7bg4WIiMqhLJHJ1WbJ@stanza.co
SUMMARY:Clippers vs. Indians
DESCRIPTION:Clippers vs. Indians\n\nBuy tickets here: https://stza.co/~uWJF\n\nFollow on MiLB First Pitch: https://stza.co/+uWJF-29\n\nShop: https://stza.co/+uWJF-C\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Swipe for last minute tickets for tonight's game. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144516Z
LAST-MODIFIED:20180213T144516Z
TRANSP:OPAQUE
END:VEVENT
* Clippers vs. Indians
<2018-04-29 Sun 13:05-16:05>
:PROPERTIES:
:ID:       WnMAfK6daI2y4CJTzk5w-3gv@stanza.co
:LOCATION: Ready for the game? Swipe for tickets and more information.
:STATUS:   CONFIRMED
:END:

Clippers vs. Indians Clippers vs. Indians

Buy tickets here  https //stza.co/~uWJQ

Follow on MiLB First Pitch  https //stza.co/+uWJQ-2

Shop  https //stza.co/+uWJQ-1B

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Clippers vs. Indians
END:VALARM
DTSTART:20180429T180500Z
DTEND:20180429T210500Z
UID:WnMAfK6daI2y4CJTzk5w-3gv@stanza.co
SUMMARY:Clippers vs. Indians
DESCRIPTION:Clippers vs. Indians\n\nBuy tickets here: https://stza.co/~uWJQ\n\nFollow on MiLB First Pitch: https://stza.co/+uWJQ-2\n\nShop: https://stza.co/+uWJQ-1B\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Swipe for tickets and more information.
STATUS:CONFIRMED
CREATED:20180213T144516Z
LAST-MODIFIED:20180213T144516Z
TRANSP:OPAQUE
END:VEVENT
* Clippers @ Bats
<2018-04-30 Mon 17:30-20:30>
:PROPERTIES:
:ID:       _4Tb2YZxV9MRQtoqcPJ8ZBvc@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Clippers @ Bats Clippers @ Bats

Buy tickets here  https //stza.co/~uWVE

Follow on MiLB First Pitch  https //stza.co/+uWVE-2x

Shop  https //stza.co/+uWVE-1N

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Clippers @ Bats
END:VALARM
DTSTART:20180430T223000Z
DTEND:20180501T013000Z
UID:_4Tb2YZxV9MRQtoqcPJ8ZBvc@stanza.co
SUMMARY:Clippers @ Bats
DESCRIPTION:Clippers @ Bats\n\nBuy tickets here: https://stza.co/~uWVE\n\nFollow on MiLB First Pitch: https://stza.co/+uWVE-2x\n\nShop: https://stza.co/+uWVE-1N\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144516Z
LAST-MODIFIED:20180213T144516Z
TRANSP:OPAQUE
END:VEVENT
* Clippers @ Bats
<2018-05-01 Tue 17:30-20:30>
:PROPERTIES:
:ID:       VZ9P07AtNxxsS5Bj_3_S8PEp@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Clippers @ Bats Clippers @ Bats

Buy tickets here  https //stza.co/~uWVR

Follow on MiLB First Pitch  https //stza.co/+uWVR-1n

Shop  https //stza.co/+uWVR-1d

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Clippers @ Bats
END:VALARM
DTSTART:20180501T223000Z
DTEND:20180502T013000Z
UID:VZ9P07AtNxxsS5Bj_3_S8PEp@stanza.co
SUMMARY:Clippers @ Bats
DESCRIPTION:Clippers @ Bats\n\nBuy tickets here: https://stza.co/~uWVR\n\nFollow on MiLB First Pitch: https://stza.co/+uWVR-1n\n\nShop: https://stza.co/+uWVR-1d\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144516Z
LAST-MODIFIED:20180213T144516Z
TRANSP:OPAQUE
END:VEVENT
* Clippers @ Bats
<2018-05-02 Wed 10:00-13:00>
:PROPERTIES:
:ID:       zRxZigQ36AD733mFE9pXM27S@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Clippers @ Bats Clippers @ Bats

Buy tickets here  https //stza.co/~uWW3

Follow on MiLB First Pitch  https //stza.co/+uWW3-2v

Shop  https //stza.co/+uWW3-2d

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Clippers @ Bats
END:VALARM
DTSTART:20180502T150000Z
DTEND:20180502T180000Z
UID:zRxZigQ36AD733mFE9pXM27S@stanza.co
SUMMARY:Clippers @ Bats
DESCRIPTION:Clippers @ Bats\n\nBuy tickets here: https://stza.co/~uWW3\n\nFollow on MiLB First Pitch: https://stza.co/+uWW3-2v\n\nShop: https://stza.co/+uWW3-2d\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144516Z
LAST-MODIFIED:20180213T144516Z
TRANSP:OPAQUE
END:VEVENT
* Clippers vs. Knights
<2018-05-03 Thu 17:35-20:35>
:PROPERTIES:
:ID:       MkeNXilQpwvFrzVqn5lJboWK@stanza.co
:LOCATION: Looking for something to do tonight? Get tickets here for tonight’s game and view promotions.
:STATUS:   CONFIRMED
:END:

Clippers vs. Knights Clippers vs. Knights

Buy tickets here  https //stza.co/~uWJZ

Follow on MiLB First Pitch  https //stza.co/+uWJZ-1m

Shop  https //stza.co/+uWJZ-24

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Clippers vs. Knights
END:VALARM
DTSTART:20180503T223500Z
DTEND:20180504T013500Z
UID:MkeNXilQpwvFrzVqn5lJboWK@stanza.co
SUMMARY:Clippers vs. Knights
DESCRIPTION:Clippers vs. Knights\n\nBuy tickets here: https://stza.co/~uWJZ\n\nFollow on MiLB First Pitch: https://stza.co/+uWJZ-1m\n\nShop: https://stza.co/+uWJZ-24\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Looking for something to do tonight? Get tickets here for tonight’s game and view promotions.
STATUS:CONFIRMED
CREATED:20180213T144516Z
LAST-MODIFIED:20180213T144516Z
TRANSP:OPAQUE
END:VEVENT
* Clippers vs. Knights
<2018-05-04 Fri 18:15-21:15>
:PROPERTIES:
:ID:       UKQ4yEz5OejoEIoL8oRgnQ_5@stanza.co
:LOCATION: Great seats still available for tonight’s game. Purchase them here.
:STATUS:   CONFIRMED
:END:

Clippers vs. Knights Clippers vs. Knights

Buy tickets here  https //stza.co/~uWK7

Follow on MiLB First Pitch  https //stza.co/+uWK7-3_

Shop  https //stza.co/+uWK7-1C

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Clippers vs. Knights
END:VALARM
DTSTART:20180504T231500Z
DTEND:20180505T021500Z
UID:UKQ4yEz5OejoEIoL8oRgnQ_5@stanza.co
SUMMARY:Clippers vs. Knights
DESCRIPTION:Clippers vs. Knights\n\nBuy tickets here: https://stza.co/~uWK7\n\nFollow on MiLB First Pitch: https://stza.co/+uWK7-3_\n\nShop: https://stza.co/+uWK7-1C\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Great seats still available for tonight’s game. Purchase them here.
STATUS:CONFIRMED
CREATED:20180213T144516Z
LAST-MODIFIED:20180213T144516Z
TRANSP:OPAQUE
END:VEVENT
* Clippers vs. Knights
<2018-05-05 Sat 18:15-21:15>
:PROPERTIES:
:ID:       eOtpKSCjqMKi9w7XOLlrx3yL@stanza.co
:LOCATION: Need something fun to do tonight? Get Clippers tickets here.
:STATUS:   CONFIRMED
:END:

Clippers vs. Knights Clippers vs. Knights

Buy tickets here  https //stza.co/~uWKh

Follow on MiLB First Pitch  https //stza.co/+uWKh-h

Shop  https //stza.co/+uWKh-1y

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Clippers vs. Knights
END:VALARM
DTSTART:20180505T231500Z
DTEND:20180506T021500Z
UID:eOtpKSCjqMKi9w7XOLlrx3yL@stanza.co
SUMMARY:Clippers vs. Knights
DESCRIPTION:Clippers vs. Knights\n\nBuy tickets here: https://stza.co/~uWKh\n\nFollow on MiLB First Pitch: https://stza.co/+uWKh-h\n\nShop: https://stza.co/+uWKh-1y\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Need something fun to do tonight? Get Clippers tickets here.
STATUS:CONFIRMED
CREATED:20180213T144516Z
LAST-MODIFIED:20180213T144516Z
TRANSP:OPAQUE
END:VEVENT
* Clippers vs. Knights
<2018-05-06 Sun 13:05-16:05>
:PROPERTIES:
:ID:       0QYGL8O6vwXf3Fx3XoSVA0Ye@stanza.co
:LOCATION: Don’t miss out! Clippers tickets still available here.
:STATUS:   CONFIRMED
:END:

Clippers vs. Knights Clippers vs. Knights

Buy tickets here  https //stza.co/~uWKt

Follow on MiLB First Pitch  https //stza.co/+uWKt-L

Shop  https //stza.co/+uWKt-3j

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Clippers vs. Knights
END:VALARM
DTSTART:20180506T180500Z
DTEND:20180506T210500Z
UID:0QYGL8O6vwXf3Fx3XoSVA0Ye@stanza.co
SUMMARY:Clippers vs. Knights
DESCRIPTION:Clippers vs. Knights\n\nBuy tickets here: https://stza.co/~uWKt\n\nFollow on MiLB First Pitch: https://stza.co/+uWKt-L\n\nShop: https://stza.co/+uWKt-3j\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don’t miss out! Clippers tickets still available here.
STATUS:CONFIRMED
CREATED:20180213T144516Z
LAST-MODIFIED:20180213T144516Z
TRANSP:OPAQUE
END:VEVENT
* Clippers @ Mud Hens
<2018-05-07 Mon 17:35-20:35>
:PROPERTIES:
:ID:       lpiLjQH__tQodrgAowQru_u_@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Clippers @ Mud Hens Clippers @ Mud Hens

Follow on MiLB First Pitch  https //stza.co/+uW$0-L

Shop  https //stza.co/+uW$0-33

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Clippers @ Mud Hens
END:VALARM
DTSTART:20180507T223500Z
DTEND:20180508T013500Z
UID:lpiLjQH__tQodrgAowQru_u_@stanza.co
SUMMARY:Clippers @ Mud Hens
DESCRIPTION:Clippers @ Mud Hens\n\nFollow on MiLB First Pitch: https://stza.co/+uW$0-L\n\nShop: https://stza.co/+uW$0-33\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144516Z
LAST-MODIFIED:20180213T144516Z
TRANSP:OPAQUE
END:VEVENT
* Clippers @ Mud Hens
<2018-05-08 Tue 09:35-12:35>
:PROPERTIES:
:ID:       18q0cyKASYBbouoX-bUEP3eK@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Clippers @ Mud Hens Clippers @ Mud Hens

Follow on MiLB First Pitch  https //stza.co/+uW$g-2u

Shop  https //stza.co/+uW$g-2g

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Clippers @ Mud Hens
END:VALARM
DTSTART:20180508T143500Z
DTEND:20180508T173500Z
UID:18q0cyKASYBbouoX-bUEP3eK@stanza.co
SUMMARY:Clippers @ Mud Hens
DESCRIPTION:Clippers @ Mud Hens\n\nFollow on MiLB First Pitch: https://stza.co/+uW$g-2u\n\nShop: https://stza.co/+uW$g-2g\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144516Z
LAST-MODIFIED:20180213T144516Z
TRANSP:OPAQUE
END:VEVENT
* Clippers @ Mud Hens
<2018-05-09 Wed 17:35-20:35>
:PROPERTIES:
:ID:       V3vz73qdczlAKQS3lSqkED50@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Clippers @ Mud Hens Clippers @ Mud Hens

Follow on MiLB First Pitch  https //stza.co/+uW$y-3L

Shop  https //stza.co/+uW$y-p

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Clippers @ Mud Hens
END:VALARM
DTSTART:20180509T223500Z
DTEND:20180510T013500Z
UID:V3vz73qdczlAKQS3lSqkED50@stanza.co
SUMMARY:Clippers @ Mud Hens
DESCRIPTION:Clippers @ Mud Hens\n\nFollow on MiLB First Pitch: https://stza.co/+uW$y-3L\n\nShop: https://stza.co/+uW$y-p\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144516Z
LAST-MODIFIED:20180213T144516Z
TRANSP:OPAQUE
END:VEVENT
* Clippers @ Mud Hens
<2018-05-10 Thu 17:35-20:35>
:PROPERTIES:
:ID:       CBM--pcqxY50cs7nUmCq2tr0@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Clippers @ Mud Hens Clippers @ Mud Hens

Follow on MiLB First Pitch  https //stza.co/+uW$_-v

Shop  https //stza.co/+uW$_-2A

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Clippers @ Mud Hens
END:VALARM
DTSTART:20180510T223500Z
DTEND:20180511T013500Z
UID:CBM--pcqxY50cs7nUmCq2tr0@stanza.co
SUMMARY:Clippers @ Mud Hens
DESCRIPTION:Clippers @ Mud Hens\n\nFollow on MiLB First Pitch: https://stza.co/+uW$_-v\n\nShop: https://stza.co/+uW$_-2A\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144516Z
LAST-MODIFIED:20180213T144516Z
TRANSP:OPAQUE
END:VEVENT
* Clippers @ Indians
<2018-05-11 Fri 18:15-21:15>
:PROPERTIES:
:ID:       ovu-A3GRLOhSLLw94T4pgSVH@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Clippers @ Indians Clippers @ Indians

Follow on MiLB First Pitch  https //stza.co/+uWSu-3r

Shop  https //stza.co/+uWSu-I

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Clippers @ Indians
END:VALARM
DTSTART:20180511T231500Z
DTEND:20180512T021500Z
UID:ovu-A3GRLOhSLLw94T4pgSVH@stanza.co
SUMMARY:Clippers @ Indians
DESCRIPTION:Clippers @ Indians\n\nFollow on MiLB First Pitch: https://stza.co/+uWSu-3r\n\nShop: https://stza.co/+uWSu-I\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144516Z
LAST-MODIFIED:20180213T144516Z
TRANSP:OPAQUE
END:VEVENT
* Clippers @ Indians
<2018-05-12 Sat 18:05-21:05>
:PROPERTIES:
:ID:       ZXIIR1IrOGgLawtWty919toh@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Clippers @ Indians Clippers @ Indians

Follow on MiLB First Pitch  https //stza.co/+uWSH-2D

Shop  https //stza.co/+uWSH-N

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Clippers @ Indians
END:VALARM
DTSTART:20180512T230500Z
DTEND:20180513T020500Z
UID:ZXIIR1IrOGgLawtWty919toh@stanza.co
SUMMARY:Clippers @ Indians
DESCRIPTION:Clippers @ Indians\n\nFollow on MiLB First Pitch: https://stza.co/+uWSH-2D\n\nShop: https://stza.co/+uWSH-N\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144516Z
LAST-MODIFIED:20180213T144516Z
TRANSP:OPAQUE
END:VEVENT
* Clippers @ Indians
<2018-05-13 Sun 12:35-15:35>
:PROPERTIES:
:ID:       IkchMYYumI9VKW2YCcPAOElt@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Clippers @ Indians Clippers @ Indians

Follow on MiLB First Pitch  https //stza.co/+uWST-2y

Shop  https //stza.co/+uWST-1r

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Clippers @ Indians
END:VALARM
DTSTART:20180513T173500Z
DTEND:20180513T203500Z
UID:IkchMYYumI9VKW2YCcPAOElt@stanza.co
SUMMARY:Clippers @ Indians
DESCRIPTION:Clippers @ Indians\n\nFollow on MiLB First Pitch: https://stza.co/+uWST-2y\n\nShop: https://stza.co/+uWST-1r\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144516Z
LAST-MODIFIED:20180213T144516Z
TRANSP:OPAQUE
END:VEVENT
* Clippers vs. Stripers
<2018-05-15 Tue 17:35-20:35>
:PROPERTIES:
:ID:       EuUlk2NHwH-UqNZKFxXtedIg@stanza.co
:LOCATION: Swipe to get tickets for the game tonight. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Clippers vs. Stripers Clippers vs. Stripers

Buy tickets here  https //stza.co/~uWKD

Follow on MiLB First Pitch  https //stza.co/+uWKD-z

Shop  https //stza.co/+uWKD-

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Clippers vs. Stripers
END:VALARM
DTSTART:20180515T223500Z
DTEND:20180516T013500Z
UID:EuUlk2NHwH-UqNZKFxXtedIg@stanza.co
SUMMARY:Clippers vs. Stripers
DESCRIPTION:Clippers vs. Stripers\n\nBuy tickets here: https://stza.co/~uWKD\n\nFollow on MiLB First Pitch: https://stza.co/+uWKD-z\n\nShop: https://stza.co/+uWKD-\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Swipe to get tickets for the game tonight. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144516Z
LAST-MODIFIED:20180213T144516Z
TRANSP:OPAQUE
END:VEVENT
* Clippers vs. Stripers
<2018-05-16 Wed 17:35-20:35>
:PROPERTIES:
:ID:       ypl7rscw6RkNUDsisd8nagCG@stanza.co
:LOCATION: Swipe for last minute tickets for tonight's game. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Clippers vs. Stripers Clippers vs. Stripers

Buy tickets here  https //stza.co/~uWKL

Follow on MiLB First Pitch  https //stza.co/+uWKL-28

Shop  https //stza.co/+uWKL-g

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Clippers vs. Stripers
END:VALARM
DTSTART:20180516T223500Z
DTEND:20180517T013500Z
UID:ypl7rscw6RkNUDsisd8nagCG@stanza.co
SUMMARY:Clippers vs. Stripers
DESCRIPTION:Clippers vs. Stripers\n\nBuy tickets here: https://stza.co/~uWKL\n\nFollow on MiLB First Pitch: https://stza.co/+uWKL-28\n\nShop: https://stza.co/+uWKL-g\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Swipe for last minute tickets for tonight's game. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144516Z
LAST-MODIFIED:20180213T144516Z
TRANSP:OPAQUE
END:VEVENT
* Clippers vs. Stripers
<2018-05-17 Thu 10:05-13:05>
:PROPERTIES:
:ID:       R-9DghXhnPa8ZRNHfEXzaVtd@stanza.co
:LOCATION: Ready for the game? Swipe for tickets and more information.
:STATUS:   CONFIRMED
:END:

Clippers vs. Stripers Clippers vs. Stripers

Buy tickets here  https //stza.co/~uWKR

Follow on MiLB First Pitch  https //stza.co/+uWKR-2r

Shop  https //stza.co/+uWKR-1X

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Clippers vs. Stripers
END:VALARM
DTSTART:20180517T150500Z
DTEND:20180517T180500Z
UID:R-9DghXhnPa8ZRNHfEXzaVtd@stanza.co
SUMMARY:Clippers vs. Stripers
DESCRIPTION:Clippers vs. Stripers\n\nBuy tickets here: https://stza.co/~uWKR\n\nFollow on MiLB First Pitch: https://stza.co/+uWKR-2r\n\nShop: https://stza.co/+uWKR-1X\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Swipe for tickets and more information.
STATUS:CONFIRMED
CREATED:20180213T144516Z
LAST-MODIFIED:20180213T144516Z
TRANSP:OPAQUE
END:VEVENT
* Clippers vs. Knights
<2018-05-18 Fri 18:15-21:15>
:PROPERTIES:
:ID:       f3VLcAFy1C9f32G4gYPUHIzY@stanza.co
:LOCATION: Looking for something to do tonight? Get tickets here for tonight’s game and view promotions.
:STATUS:   CONFIRMED
:END:

Clippers vs. Knights Clippers vs. Knights

Buy tickets here  https //stza.co/~uWKZ

Follow on MiLB First Pitch  https //stza.co/+uWKZ-3G

Shop  https //stza.co/+uWKZ-1v

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Clippers vs. Knights
END:VALARM
DTSTART:20180518T231500Z
DTEND:20180519T021500Z
UID:f3VLcAFy1C9f32G4gYPUHIzY@stanza.co
SUMMARY:Clippers vs. Knights
DESCRIPTION:Clippers vs. Knights\n\nBuy tickets here: https://stza.co/~uWKZ\n\nFollow on MiLB First Pitch: https://stza.co/+uWKZ-3G\n\nShop: https://stza.co/+uWKZ-1v\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Looking for something to do tonight? Get tickets here for tonight’s game and view promotions.
STATUS:CONFIRMED
CREATED:20180213T144516Z
LAST-MODIFIED:20180213T144516Z
TRANSP:OPAQUE
END:VEVENT
* Clippers vs. Knights
<2018-05-19 Sat 18:15-21:15>
:PROPERTIES:
:ID:       e-9govgfOXFfWhNatkzHoX22@stanza.co
:LOCATION: Great seats still available for tonight’s game. Purchase them here.
:STATUS:   CONFIRMED
:END:

Clippers vs. Knights Clippers vs. Knights

Buy tickets here  https //stza.co/~uWLa

Follow on MiLB First Pitch  https //stza.co/+uWLa-32

Shop  https //stza.co/+uWLa-2V

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Clippers vs. Knights
END:VALARM
DTSTART:20180519T231500Z
DTEND:20180520T021500Z
UID:e-9govgfOXFfWhNatkzHoX22@stanza.co
SUMMARY:Clippers vs. Knights
DESCRIPTION:Clippers vs. Knights\n\nBuy tickets here: https://stza.co/~uWLa\n\nFollow on MiLB First Pitch: https://stza.co/+uWLa-32\n\nShop: https://stza.co/+uWLa-2V\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Great seats still available for tonight’s game. Purchase them here.
STATUS:CONFIRMED
CREATED:20180213T144516Z
LAST-MODIFIED:20180213T144516Z
TRANSP:OPAQUE
END:VEVENT
* Clippers vs. Knights
<2018-05-20 Sun 13:05-16:05>
:PROPERTIES:
:ID:       q8VqqSfBg17ECbFPamdvniqj@stanza.co
:LOCATION: Need something fun to do tonight? Get Clippers tickets here.
:STATUS:   CONFIRMED
:END:

Clippers vs. Knights Clippers vs. Knights

Buy tickets here  https //stza.co/~uWLf

Follow on MiLB First Pitch  https //stza.co/+uWLf-3i

Shop  https //stza.co/+uWLf-1B

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Clippers vs. Knights
END:VALARM
DTSTART:20180520T180500Z
DTEND:20180520T210500Z
UID:q8VqqSfBg17ECbFPamdvniqj@stanza.co
SUMMARY:Clippers vs. Knights
DESCRIPTION:Clippers vs. Knights\n\nBuy tickets here: https://stza.co/~uWLf\n\nFollow on MiLB First Pitch: https://stza.co/+uWLf-3i\n\nShop: https://stza.co/+uWLf-1B\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Need something fun to do tonight? Get Clippers tickets here.
STATUS:CONFIRMED
CREATED:20180213T144516Z
LAST-MODIFIED:20180213T144516Z
TRANSP:OPAQUE
END:VEVENT
* Clippers vs. Mud Hens
<2018-05-21 Mon 17:35-20:35>
:PROPERTIES:
:ID:       dBTNQaoxzeamK5YWAt5MtZ7z@stanza.co
:LOCATION: Don’t miss out! Clippers tickets still available here.
:STATUS:   CONFIRMED
:END:

Clippers vs. Mud Hens Clippers vs. Mud Hens

Buy tickets here  https //stza.co/~uWLm

Follow on MiLB First Pitch  https //stza.co/+uWLm-2v

Shop  https //stza.co/+uWLm-2j

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Clippers vs. Mud Hens
END:VALARM
DTSTART:20180521T223500Z
DTEND:20180522T013500Z
UID:dBTNQaoxzeamK5YWAt5MtZ7z@stanza.co
SUMMARY:Clippers vs. Mud Hens
DESCRIPTION:Clippers vs. Mud Hens\n\nBuy tickets here: https://stza.co/~uWLm\n\nFollow on MiLB First Pitch: https://stza.co/+uWLm-2v\n\nShop: https://stza.co/+uWLm-2j\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don’t miss out! Clippers tickets still available here.
STATUS:CONFIRMED
CREATED:20180213T144516Z
LAST-MODIFIED:20180213T144516Z
TRANSP:OPAQUE
END:VEVENT
* Clippers vs. Mud Hens
<2018-05-22 Tue 17:35-20:35>
:PROPERTIES:
:ID:       5gMO9XoMjmQccubV2FYOB4zj@stanza.co
:LOCATION: Swipe to get tickets for the game tonight. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Clippers vs. Mud Hens Clippers vs. Mud Hens

Buy tickets here  https //stza.co/~uWLw

Follow on MiLB First Pitch  https //stza.co/+uWLw-2U

Shop  https //stza.co/+uWLw-3q

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Clippers vs. Mud Hens
END:VALARM
DTSTART:20180522T223500Z
DTEND:20180523T013500Z
UID:5gMO9XoMjmQccubV2FYOB4zj@stanza.co
SUMMARY:Clippers vs. Mud Hens
DESCRIPTION:Clippers vs. Mud Hens\n\nBuy tickets here: https://stza.co/~uWLw\n\nFollow on MiLB First Pitch: https://stza.co/+uWLw-2U\n\nShop: https://stza.co/+uWLw-3q\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Swipe to get tickets for the game tonight. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144516Z
LAST-MODIFIED:20180213T144516Z
TRANSP:OPAQUE
END:VEVENT
* Clippers vs. Mud Hens
<2018-05-23 Wed 17:35-20:35>
:PROPERTIES:
:ID:       KeZSlCZAI9VHYLRK_6xGg-t-@stanza.co
:LOCATION: Swipe for last minute tickets for tonight's game. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Clippers vs. Mud Hens Clippers vs. Mud Hens

Buy tickets here  https //stza.co/~uWLF

Follow on MiLB First Pitch  https //stza.co/+uWLF-1b

Shop  https //stza.co/+uWLF-3z

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Clippers vs. Mud Hens
END:VALARM
DTSTART:20180523T223500Z
DTEND:20180524T013500Z
UID:KeZSlCZAI9VHYLRK_6xGg-t-@stanza.co
SUMMARY:Clippers vs. Mud Hens
DESCRIPTION:Clippers vs. Mud Hens\n\nBuy tickets here: https://stza.co/~uWLF\n\nFollow on MiLB First Pitch: https://stza.co/+uWLF-1b\n\nShop: https://stza.co/+uWLF-3z\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Swipe for last minute tickets for tonight's game. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144516Z
LAST-MODIFIED:20180213T144516Z
TRANSP:OPAQUE
END:VEVENT
* Clippers vs. Mud Hens
<2018-05-24 Thu 10:05-13:05>
:PROPERTIES:
:ID:       kEhDb9gIDcplA4XviHGPhx35@stanza.co
:LOCATION: Ready for the game? Swipe for tickets and more information.
:STATUS:   CONFIRMED
:END:

Clippers vs. Mud Hens Clippers vs. Mud Hens

Buy tickets here  https //stza.co/~uWLN

Follow on MiLB First Pitch  https //stza.co/+uWLN-3J

Shop  https //stza.co/+uWLN-F

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Clippers vs. Mud Hens
END:VALARM
DTSTART:20180524T150500Z
DTEND:20180524T180500Z
UID:kEhDb9gIDcplA4XviHGPhx35@stanza.co
SUMMARY:Clippers vs. Mud Hens
DESCRIPTION:Clippers vs. Mud Hens\n\nBuy tickets here: https://stza.co/~uWLN\n\nFollow on MiLB First Pitch: https://stza.co/+uWLN-3J\n\nShop: https://stza.co/+uWLN-F\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Swipe for tickets and more information.
STATUS:CONFIRMED
CREATED:20180213T144516Z
LAST-MODIFIED:20180213T144516Z
TRANSP:OPAQUE
END:VEVENT
* Clippers @ Stripers
<2018-05-25 Fri 18:05-21:05>
:PROPERTIES:
:ID:       oKTr5pU-To_ap9_nSE8LYepR@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Clippers @ Stripers Clippers @ Stripers

Follow on MiLB First Pitch  https //stza.co/+uWQw-1i

Shop  https //stza.co/+uWQw-P

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Clippers @ Stripers
END:VALARM
DTSTART:20180525T230500Z
DTEND:20180526T020500Z
UID:oKTr5pU-To_ap9_nSE8LYepR@stanza.co
SUMMARY:Clippers @ Stripers
DESCRIPTION:Clippers @ Stripers\n\nFollow on MiLB First Pitch: https://stza.co/+uWQw-1i\n\nShop: https://stza.co/+uWQw-P\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144516Z
LAST-MODIFIED:20180213T144516Z
TRANSP:OPAQUE
END:VEVENT
* Clippers @ Stripers
<2018-05-26 Sat 17:05-20:05>
:PROPERTIES:
:ID:       DaB7eiNOwv3rsobdtuj4klWr@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Clippers @ Stripers Clippers @ Stripers

Follow on MiLB First Pitch  https //stza.co/+uWQJ-3Y

Shop  https //stza.co/+uWQJ-2b

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Clippers @ Stripers
END:VALARM
DTSTART:20180526T220500Z
DTEND:20180527T010500Z
UID:DaB7eiNOwv3rsobdtuj4klWr@stanza.co
SUMMARY:Clippers @ Stripers
DESCRIPTION:Clippers @ Stripers\n\nFollow on MiLB First Pitch: https://stza.co/+uWQJ-3Y\n\nShop: https://stza.co/+uWQJ-2b\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144516Z
LAST-MODIFIED:20180213T144516Z
TRANSP:OPAQUE
END:VEVENT
* Clippers @ Stripers
<2018-05-27 Sun 12:05-15:05>
:PROPERTIES:
:ID:       s1I2zd4bL_frTw1SO19rHCt3@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Clippers @ Stripers Clippers @ Stripers

Follow on MiLB First Pitch  https //stza.co/+uWQ$-3f

Shop  https //stza.co/+uWQ$-1W

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Clippers @ Stripers
END:VALARM
DTSTART:20180527T170500Z
DTEND:20180527T200500Z
UID:s1I2zd4bL_frTw1SO19rHCt3@stanza.co
SUMMARY:Clippers @ Stripers
DESCRIPTION:Clippers @ Stripers\n\nFollow on MiLB First Pitch: https://stza.co/+uWQ$-3f\n\nShop: https://stza.co/+uWQ$-1W\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144516Z
LAST-MODIFIED:20180213T144516Z
TRANSP:OPAQUE
END:VEVENT
* Clippers @ Stripers
<2018-05-28 Mon 17:05-20:05>
:PROPERTIES:
:ID:       AMBbOhWZYuspJHrywrWqd0Wm@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Clippers @ Stripers Clippers @ Stripers

Follow on MiLB First Pitch  https //stza.co/+uWRf-3C

Shop  https //stza.co/+uWRf-2g

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Clippers @ Stripers
END:VALARM
DTSTART:20180528T220500Z
DTEND:20180529T010500Z
UID:AMBbOhWZYuspJHrywrWqd0Wm@stanza.co
SUMMARY:Clippers @ Stripers
DESCRIPTION:Clippers @ Stripers\n\nFollow on MiLB First Pitch: https://stza.co/+uWRf-3C\n\nShop: https://stza.co/+uWRf-2g\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144516Z
LAST-MODIFIED:20180213T144516Z
TRANSP:OPAQUE
END:VEVENT
* Clippers @ Bisons
<2018-05-29 Tue 17:05-20:05>
:PROPERTIES:
:ID:       Ef28MZ0ghZIR9m7jsv9XIJVc@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Clippers @ Bisons Clippers @ Bisons

Follow on MiLB First Pitch  https //stza.co/+uWI9-1O

Shop  https //stza.co/+uWI9-u

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Clippers @ Bisons
END:VALARM
DTSTART:20180529T220500Z
DTEND:20180530T010500Z
UID:Ef28MZ0ghZIR9m7jsv9XIJVc@stanza.co
SUMMARY:Clippers @ Bisons
DESCRIPTION:Clippers @ Bisons\n\nFollow on MiLB First Pitch: https://stza.co/+uWI9-1O\n\nShop: https://stza.co/+uWI9-u\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144516Z
LAST-MODIFIED:20180213T144516Z
TRANSP:OPAQUE
END:VEVENT
* Clippers @ Bisons
<2018-05-30 Wed 17:05-20:05>
:PROPERTIES:
:ID:       sVLmnDI2hdxofzfJxDDd86F-@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Clippers @ Bisons Clippers @ Bisons

Follow on MiLB First Pitch  https //stza.co/+uWIe-2f

Shop  https //stza.co/+uWIe-o

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Clippers @ Bisons
END:VALARM
DTSTART:20180530T220500Z
DTEND:20180531T010500Z
UID:sVLmnDI2hdxofzfJxDDd86F-@stanza.co
SUMMARY:Clippers @ Bisons
DESCRIPTION:Clippers @ Bisons\n\nFollow on MiLB First Pitch: https://stza.co/+uWIe-2f\n\nShop: https://stza.co/+uWIe-o\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144516Z
LAST-MODIFIED:20180213T144516Z
TRANSP:OPAQUE
END:VEVENT
* Clippers @ Bisons
<2018-05-31 Thu 09:35-12:35>
:PROPERTIES:
:ID:       UmiYH_g69N1tRu7sDd4BmOD7@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Clippers @ Bisons Clippers @ Bisons

Follow on MiLB First Pitch  https //stza.co/+uWIj-3V

Shop  https //stza.co/+uWIj-1f

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Clippers @ Bisons
END:VALARM
DTSTART:20180531T143500Z
DTEND:20180531T173500Z
UID:UmiYH_g69N1tRu7sDd4BmOD7@stanza.co
SUMMARY:Clippers @ Bisons
DESCRIPTION:Clippers @ Bisons\n\nFollow on MiLB First Pitch: https://stza.co/+uWIj-3V\n\nShop: https://stza.co/+uWIj-1f\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144516Z
LAST-MODIFIED:20180213T144516Z
TRANSP:OPAQUE
END:VEVENT
* Clippers @ Chiefs
<2018-06-01 Fri 18:05-21:05>
:PROPERTIES:
:ID:       TBO_ZAVInkyKLQq9Z4hKPIMB@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Clippers @ Chiefs Clippers @ Chiefs

Follow on MiLB First Pitch  https //stza.co/+uW_l-3J

Shop  https //stza.co/+uW_l-2k

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Clippers @ Chiefs
END:VALARM
DTSTART:20180601T230500Z
DTEND:20180602T020500Z
UID:TBO_ZAVInkyKLQq9Z4hKPIMB@stanza.co
SUMMARY:Clippers @ Chiefs
DESCRIPTION:Clippers @ Chiefs\n\nFollow on MiLB First Pitch: https://stza.co/+uW_l-3J\n\nShop: https://stza.co/+uW_l-2k\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144516Z
LAST-MODIFIED:20180213T144516Z
TRANSP:OPAQUE
END:VEVENT
* Clippers @ Chiefs
<2018-06-02 Sat 18:05-21:05>
:PROPERTIES:
:ID:       bpMf5z17MwdyaplHdAvth8j7@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Clippers @ Chiefs Clippers @ Chiefs

Follow on MiLB First Pitch  https //stza.co/+uW_x-W

Shop  https //stza.co/+uW_x-2a

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Clippers @ Chiefs
END:VALARM
DTSTART:20180602T230500Z
DTEND:20180603T020500Z
UID:bpMf5z17MwdyaplHdAvth8j7@stanza.co
SUMMARY:Clippers @ Chiefs
DESCRIPTION:Clippers @ Chiefs\n\nFollow on MiLB First Pitch: https://stza.co/+uW_x-W\n\nShop: https://stza.co/+uW_x-2a\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144516Z
LAST-MODIFIED:20180213T144516Z
TRANSP:OPAQUE
END:VEVENT
* Clippers @ Chiefs
<2018-06-03 Sun 12:05-15:05>
:PROPERTIES:
:ID:       hTTbheiNy5kaaTtWVaG_DzBN@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Clippers @ Chiefs Clippers @ Chiefs

Follow on MiLB First Pitch  https //stza.co/+uW_N-2R

Shop  https //stza.co/+uW_N-1J

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Clippers @ Chiefs
END:VALARM
DTSTART:20180603T170500Z
DTEND:20180603T200500Z
UID:hTTbheiNy5kaaTtWVaG_DzBN@stanza.co
SUMMARY:Clippers @ Chiefs
DESCRIPTION:Clippers @ Chiefs\n\nFollow on MiLB First Pitch: https://stza.co/+uW_N-2R\n\nShop: https://stza.co/+uW_N-1J\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144516Z
LAST-MODIFIED:20180213T144516Z
TRANSP:OPAQUE
END:VEVENT
* Clippers vs. Tides
<2018-06-05 Tue 18:05-21:05>
:PROPERTIES:
:ID:       YF6vtTZq7hx2MM4UXZh8aGYF@stanza.co
:LOCATION: Looking for something to do tonight? Get tickets here for tonight’s game and view promotions.
:STATUS:   CONFIRMED
:END:

Clippers vs. Tides Clippers vs. Tides

Buy tickets here  https //stza.co/~uWLU

Follow on MiLB First Pitch  https //stza.co/+uWLU-2B

Shop  https //stza.co/+uWLU-22

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Clippers vs. Tides
END:VALARM
DTSTART:20180605T230500Z
DTEND:20180606T020500Z
UID:YF6vtTZq7hx2MM4UXZh8aGYF@stanza.co
SUMMARY:Clippers vs. Tides
DESCRIPTION:Clippers vs. Tides\n\nBuy tickets here: https://stza.co/~uWLU\n\nFollow on MiLB First Pitch: https://stza.co/+uWLU-2B\n\nShop: https://stza.co/+uWLU-22\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Looking for something to do tonight? Get tickets here for tonight’s game and view promotions.
STATUS:CONFIRMED
CREATED:20180213T144516Z
LAST-MODIFIED:20180213T144516Z
TRANSP:OPAQUE
END:VEVENT
* Clippers vs. Tides
<2018-06-06 Wed 18:05-21:05>
:PROPERTIES:
:ID:       HxqqTb28kF5Qz0xaLA2D6yG1@stanza.co
:LOCATION: Great seats still available for tonight’s game. Purchase them here.
:STATUS:   CONFIRMED
:END:

Clippers vs. Tides Clippers vs. Tides

Buy tickets here  https //stza.co/~uWM1

Follow on MiLB First Pitch  https //stza.co/+uWM1-33

Shop  https //stza.co/+uWM1-2q

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Clippers vs. Tides
END:VALARM
DTSTART:20180606T230500Z
DTEND:20180607T020500Z
UID:HxqqTb28kF5Qz0xaLA2D6yG1@stanza.co
SUMMARY:Clippers vs. Tides
DESCRIPTION:Clippers vs. Tides\n\nBuy tickets here: https://stza.co/~uWM1\n\nFollow on MiLB First Pitch: https://stza.co/+uWM1-33\n\nShop: https://stza.co/+uWM1-2q\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Great seats still available for tonight’s game. Purchase them here.
STATUS:CONFIRMED
CREATED:20180213T144516Z
LAST-MODIFIED:20180213T144516Z
TRANSP:OPAQUE
END:VEVENT
* Clippers vs. Tides
<2018-06-07 Thu 11:05-14:05>
:PROPERTIES:
:ID:       M77viqpyL7W2_MPI-tm2fJ1O@stanza.co
:LOCATION: Need something fun to do tonight? Get Clippers tickets here.
:STATUS:   CONFIRMED
:END:

Clippers vs. Tides Clippers vs. Tides

Buy tickets here  https //stza.co/~uWM8

Follow on MiLB First Pitch  https //stza.co/+uWM8-1k

Shop  https //stza.co/+uWM8-1t

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Clippers vs. Tides
END:VALARM
DTSTART:20180607T160500Z
DTEND:20180607T190500Z
UID:M77viqpyL7W2_MPI-tm2fJ1O@stanza.co
SUMMARY:Clippers vs. Tides
DESCRIPTION:Clippers vs. Tides\n\nBuy tickets here: https://stza.co/~uWM8\n\nFollow on MiLB First Pitch: https://stza.co/+uWM8-1k\n\nShop: https://stza.co/+uWM8-1t\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Need something fun to do tonight? Get Clippers tickets here.
STATUS:CONFIRMED
CREATED:20180213T144516Z
LAST-MODIFIED:20180213T144516Z
TRANSP:OPAQUE
END:VEVENT
* Clippers vs. Bisons
<2018-06-08 Fri 18:15-21:15>
:PROPERTIES:
:ID:       oLK1rRtlHXLFOJbffcVXBq6I@stanza.co
:LOCATION: Don’t miss out! Clippers tickets still available here.
:STATUS:   CONFIRMED
:END:

Clippers vs. Bisons Clippers vs. Bisons

Buy tickets here  https //stza.co/~uWMh

Follow on MiLB First Pitch  https //stza.co/+uWMh-3T

Shop  https //stza.co/+uWMh-3Z

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Clippers vs. Bisons
END:VALARM
DTSTART:20180608T231500Z
DTEND:20180609T021500Z
UID:oLK1rRtlHXLFOJbffcVXBq6I@stanza.co
SUMMARY:Clippers vs. Bisons
DESCRIPTION:Clippers vs. Bisons\n\nBuy tickets here: https://stza.co/~uWMh\n\nFollow on MiLB First Pitch: https://stza.co/+uWMh-3T\n\nShop: https://stza.co/+uWMh-3Z\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don’t miss out! Clippers tickets still available here.
STATUS:CONFIRMED
CREATED:20180213T144516Z
LAST-MODIFIED:20180213T144516Z
TRANSP:OPAQUE
END:VEVENT
* Clippers vs. Bisons
<2018-06-09 Sat 18:15-21:15>
:PROPERTIES:
:ID:       nw8PbcOpRIP0W-q3jtrdJBD_@stanza.co
:LOCATION: Swipe to get tickets for the game tonight. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Clippers vs. Bisons Clippers vs. Bisons

Buy tickets here  https //stza.co/~uWMo

Follow on MiLB First Pitch  https //stza.co/+uWMo-2O

Shop  https //stza.co/+uWMo-1R

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Clippers vs. Bisons
END:VALARM
DTSTART:20180609T231500Z
DTEND:20180610T021500Z
UID:nw8PbcOpRIP0W-q3jtrdJBD_@stanza.co
SUMMARY:Clippers vs. Bisons
DESCRIPTION:Clippers vs. Bisons\n\nBuy tickets here: https://stza.co/~uWMo\n\nFollow on MiLB First Pitch: https://stza.co/+uWMo-2O\n\nShop: https://stza.co/+uWMo-1R\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Swipe to get tickets for the game tonight. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144516Z
LAST-MODIFIED:20180213T144516Z
TRANSP:OPAQUE
END:VEVENT
* Clippers vs. Bisons
<2018-06-10 Sun 13:05-16:05>
:PROPERTIES:
:ID:       bwNdaJX7eR9gGZR-2sBpUdsC@stanza.co
:LOCATION: Swipe for last minute tickets for tonight's game. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Clippers vs. Bisons Clippers vs. Bisons

Buy tickets here  https //stza.co/~uWMw

Follow on MiLB First Pitch  https //stza.co/+uWMw-22

Shop  https //stza.co/+uWMw-2Q

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Clippers vs. Bisons
END:VALARM
DTSTART:20180610T180500Z
DTEND:20180610T210500Z
UID:bwNdaJX7eR9gGZR-2sBpUdsC@stanza.co
SUMMARY:Clippers vs. Bisons
DESCRIPTION:Clippers vs. Bisons\n\nBuy tickets here: https://stza.co/~uWMw\n\nFollow on MiLB First Pitch: https://stza.co/+uWMw-22\n\nShop: https://stza.co/+uWMw-2Q\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Swipe for last minute tickets for tonight's game. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144516Z
LAST-MODIFIED:20180213T144516Z
TRANSP:OPAQUE
END:VEVENT
* Clippers @ Bats
<2018-06-11 Mon 18:00-21:00>
:PROPERTIES:
:ID:       CVZLbAUJl73p12WJUiuWk_pb@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Clippers @ Bats Clippers @ Bats

Buy tickets here  https //stza.co/~uWW9

Follow on MiLB First Pitch  https //stza.co/+uWW9-3B

Shop  https //stza.co/+uWW9-1

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Clippers @ Bats
END:VALARM
DTSTART:20180611T230000Z
DTEND:20180612T020000Z
UID:CVZLbAUJl73p12WJUiuWk_pb@stanza.co
SUMMARY:Clippers @ Bats
DESCRIPTION:Clippers @ Bats\n\nBuy tickets here: https://stza.co/~uWW9\n\nFollow on MiLB First Pitch: https://stza.co/+uWW9-3B\n\nShop: https://stza.co/+uWW9-1\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144516Z
LAST-MODIFIED:20180213T144516Z
TRANSP:OPAQUE
END:VEVENT
* Clippers @ Bats
<2018-06-12 Tue 18:00-21:00>
:PROPERTIES:
:ID:       dyvNF75ltJ49ATnTARosq_nK@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Clippers @ Bats Clippers @ Bats

Buy tickets here  https //stza.co/~uWWo

Follow on MiLB First Pitch  https //stza.co/+uWWo-2B

Shop  https //stza.co/+uWWo-1B

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Clippers @ Bats
END:VALARM
DTSTART:20180612T230000Z
DTEND:20180613T020000Z
UID:dyvNF75ltJ49ATnTARosq_nK@stanza.co
SUMMARY:Clippers @ Bats
DESCRIPTION:Clippers @ Bats\n\nBuy tickets here: https://stza.co/~uWWo\n\nFollow on MiLB First Pitch: https://stza.co/+uWWo-2B\n\nShop: https://stza.co/+uWWo-1B\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144516Z
LAST-MODIFIED:20180213T144516Z
TRANSP:OPAQUE
END:VEVENT
* Clippers @ Bats
<2018-06-13 Wed 18:00-21:00>
:PROPERTIES:
:ID:       ZHWF5sKjYmJFWwea_HmGkrWk@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Clippers @ Bats Clippers @ Bats

Buy tickets here  https //stza.co/~uWWE

Follow on MiLB First Pitch  https //stza.co/+uWWE-2i

Shop  https //stza.co/+uWWE-3g

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Clippers @ Bats
END:VALARM
DTSTART:20180613T230000Z
DTEND:20180614T020000Z
UID:ZHWF5sKjYmJFWwea_HmGkrWk@stanza.co
SUMMARY:Clippers @ Bats
DESCRIPTION:Clippers @ Bats\n\nBuy tickets here: https://stza.co/~uWWE\n\nFollow on MiLB First Pitch: https://stza.co/+uWWE-2i\n\nShop: https://stza.co/+uWWE-3g\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144516Z
LAST-MODIFIED:20180213T144516Z
TRANSP:OPAQUE
END:VEVENT
* Clippers @ Bats
<2018-06-14 Thu 18:00-21:00>
:PROPERTIES:
:ID:       IbglLNV_OLNnOKlYX5mz-cMh@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Clippers @ Bats Clippers @ Bats

Buy tickets here  https //stza.co/~uWWM

Follow on MiLB First Pitch  https //stza.co/+uWWM-c

Shop  https //stza.co/+uWWM-I

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Clippers @ Bats
END:VALARM
DTSTART:20180614T230000Z
DTEND:20180615T020000Z
UID:IbglLNV_OLNnOKlYX5mz-cMh@stanza.co
SUMMARY:Clippers @ Bats
DESCRIPTION:Clippers @ Bats\n\nBuy tickets here: https://stza.co/~uWWM\n\nFollow on MiLB First Pitch: https://stza.co/+uWWM-c\n\nShop: https://stza.co/+uWWM-I\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144516Z
LAST-MODIFIED:20180213T144516Z
TRANSP:OPAQUE
END:VEVENT
* Clippers vs. Indians
<2018-06-15 Fri 18:15-21:15>
:PROPERTIES:
:ID:       6VmfLzBIu4jQ6BSk_zzXbiKe@stanza.co
:LOCATION: Ready for the game? Swipe for tickets and more information.
:STATUS:   CONFIRMED
:END:

Clippers vs. Indians Clippers vs. Indians

Buy tickets here  https //stza.co/~uWME

Follow on MiLB First Pitch  https //stza.co/+uWME-1k

Shop  https //stza.co/+uWME-2r

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Clippers vs. Indians
END:VALARM
DTSTART:20180615T231500Z
DTEND:20180616T021500Z
UID:6VmfLzBIu4jQ6BSk_zzXbiKe@stanza.co
SUMMARY:Clippers vs. Indians
DESCRIPTION:Clippers vs. Indians\n\nBuy tickets here: https://stza.co/~uWME\n\nFollow on MiLB First Pitch: https://stza.co/+uWME-1k\n\nShop: https://stza.co/+uWME-2r\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Swipe for tickets and more information.
STATUS:CONFIRMED
CREATED:20180213T144516Z
LAST-MODIFIED:20180213T144516Z
TRANSP:OPAQUE
END:VEVENT
* Clippers vs. Indians
<2018-06-16 Sat 18:15-21:15>
:PROPERTIES:
:ID:       2077qFrN_QnFCPD29Q17u-y1@stanza.co
:LOCATION: Looking for something to do tonight? Get tickets here for tonight’s game and view promotions.
:STATUS:   CONFIRMED
:END:

Clippers vs. Indians Clippers vs. Indians

Buy tickets here  https //stza.co/~uWMN

Follow on MiLB First Pitch  https //stza.co/+uWMN-2_

Shop  https //stza.co/+uWMN-3y

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Clippers vs. Indians
END:VALARM
DTSTART:20180616T231500Z
DTEND:20180617T021500Z
UID:2077qFrN_QnFCPD29Q17u-y1@stanza.co
SUMMARY:Clippers vs. Indians
DESCRIPTION:Clippers vs. Indians\n\nBuy tickets here: https://stza.co/~uWMN\n\nFollow on MiLB First Pitch: https://stza.co/+uWMN-2_\n\nShop: https://stza.co/+uWMN-3y\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Looking for something to do tonight? Get tickets here for tonight’s game and view promotions.
STATUS:CONFIRMED
CREATED:20180213T144516Z
LAST-MODIFIED:20180213T144516Z
TRANSP:OPAQUE
END:VEVENT
* Clippers vs. Indians
<2018-06-17 Sun 13:05-16:05>
:PROPERTIES:
:ID:       DMUD24VIZQGo8qM2OPIgLsmR@stanza.co
:LOCATION: Great seats still available for tonight’s game. Purchase them here.
:STATUS:   CONFIRMED
:END:

Clippers vs. Indians Clippers vs. Indians

Buy tickets here  https //stza.co/~uWMU

Follow on MiLB First Pitch  https //stza.co/+uWMU-34

Shop  https //stza.co/+uWMU-1d

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Clippers vs. Indians
END:VALARM
DTSTART:20180617T180500Z
DTEND:20180617T210500Z
UID:DMUD24VIZQGo8qM2OPIgLsmR@stanza.co
SUMMARY:Clippers vs. Indians
DESCRIPTION:Clippers vs. Indians\n\nBuy tickets here: https://stza.co/~uWMU\n\nFollow on MiLB First Pitch: https://stza.co/+uWMU-34\n\nShop: https://stza.co/+uWMU-1d\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Great seats still available for tonight’s game. Purchase them here.
STATUS:CONFIRMED
CREATED:20180213T144516Z
LAST-MODIFIED:20180213T144516Z
TRANSP:OPAQUE
END:VEVENT
* Clippers @ Knights
<2018-06-19 Tue 18:04-21:04>
:PROPERTIES:
:ID:       r0LmK9P_FIcra5vVs34lf49y@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Clippers @ Knights Clippers @ Knights

Follow on MiLB First Pitch  https //stza.co/+xOM$-1i

Shop  https //stza.co/+xOM$-2F

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Clippers @ Knights
END:VALARM
DTSTART:20180619T230400Z
DTEND:20180620T020400Z
UID:r0LmK9P_FIcra5vVs34lf49y@stanza.co
SUMMARY:Clippers @ Knights
DESCRIPTION:Clippers @ Knights\n\nFollow on MiLB First Pitch: https://stza.co/+xOM$-1i\n\nShop: https://stza.co/+xOM$-2F\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144516Z
LAST-MODIFIED:20180213T144516Z
TRANSP:OPAQUE
END:VEVENT
* Clippers @ Knights
<2018-06-20 Wed 18:04-21:04>
:PROPERTIES:
:ID:       SWJBbhs2hf9cEzv1kx-W1PLu@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Clippers @ Knights Clippers @ Knights

Follow on MiLB First Pitch  https //stza.co/+xON0-2y

Shop  https //stza.co/+xON0-1i

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Clippers @ Knights
END:VALARM
DTSTART:20180620T230400Z
DTEND:20180621T020400Z
UID:SWJBbhs2hf9cEzv1kx-W1PLu@stanza.co
SUMMARY:Clippers @ Knights
DESCRIPTION:Clippers @ Knights\n\nFollow on MiLB First Pitch: https://stza.co/+xON0-2y\n\nShop: https://stza.co/+xON0-1i\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144516Z
LAST-MODIFIED:20180213T144516Z
TRANSP:OPAQUE
END:VEVENT
* Clippers @ Knights
<2018-06-21 Thu 18:04-21:04>
:PROPERTIES:
:ID:       2u3fPmqvhsk0Q0mLq78Ui8fZ@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Clippers @ Knights Clippers @ Knights

Follow on MiLB First Pitch  https //stza.co/+xON1-h

Shop  https //stza.co/+xON1-2h

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Clippers @ Knights
END:VALARM
DTSTART:20180621T230400Z
DTEND:20180622T020400Z
UID:2u3fPmqvhsk0Q0mLq78Ui8fZ@stanza.co
SUMMARY:Clippers @ Knights
DESCRIPTION:Clippers @ Knights\n\nFollow on MiLB First Pitch: https://stza.co/+xON1-h\n\nShop: https://stza.co/+xON1-2h\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144516Z
LAST-MODIFIED:20180213T144516Z
TRANSP:OPAQUE
END:VEVENT
* Clippers @ Stripers
<2018-06-22 Fri 18:05-21:05>
:PROPERTIES:
:ID:       lEkNoDN8I8_IcgSEV5aj8_tF@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Clippers @ Stripers Clippers @ Stripers

Follow on MiLB First Pitch  https //stza.co/+uWRk-3s

Shop  https //stza.co/+uWRk-1f

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Clippers @ Stripers
END:VALARM
DTSTART:20180622T230500Z
DTEND:20180623T020500Z
UID:lEkNoDN8I8_IcgSEV5aj8_tF@stanza.co
SUMMARY:Clippers @ Stripers
DESCRIPTION:Clippers @ Stripers\n\nFollow on MiLB First Pitch: https://stza.co/+uWRk-3s\n\nShop: https://stza.co/+uWRk-1f\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144516Z
LAST-MODIFIED:20180213T144516Z
TRANSP:OPAQUE
END:VEVENT
* Clippers @ Stripers
<2018-06-23 Sat 17:05-20:05>
:PROPERTIES:
:ID:       f7Gfd5MKVcUNvdttE0J6I-8a@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Clippers @ Stripers Clippers @ Stripers

Follow on MiLB First Pitch  https //stza.co/+uWRw-y

Shop  https //stza.co/+uWRw-3M

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Clippers @ Stripers
END:VALARM
DTSTART:20180623T220500Z
DTEND:20180624T010500Z
UID:f7Gfd5MKVcUNvdttE0J6I-8a@stanza.co
SUMMARY:Clippers @ Stripers
DESCRIPTION:Clippers @ Stripers\n\nFollow on MiLB First Pitch: https://stza.co/+uWRw-y\n\nShop: https://stza.co/+uWRw-3M\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144516Z
LAST-MODIFIED:20180213T144516Z
TRANSP:OPAQUE
END:VEVENT
* Clippers @ Stripers
<2018-06-24 Sun 12:05-15:05>
:PROPERTIES:
:ID:       rrjB7DM9z7dQxPEsMc7JwfFy@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Clippers @ Stripers Clippers @ Stripers

Follow on MiLB First Pitch  https //stza.co/+uWRI-38

Shop  https //stza.co/+uWRI-1p

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Clippers @ Stripers
END:VALARM
DTSTART:20180624T170500Z
DTEND:20180624T200500Z
UID:rrjB7DM9z7dQxPEsMc7JwfFy@stanza.co
SUMMARY:Clippers @ Stripers
DESCRIPTION:Clippers @ Stripers\n\nFollow on MiLB First Pitch: https://stza.co/+uWRI-38\n\nShop: https://stza.co/+uWRI-1p\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144516Z
LAST-MODIFIED:20180213T144516Z
TRANSP:OPAQUE
END:VEVENT
* Clippers vs. Bats
<2018-06-25 Mon 18:05-21:05>
:PROPERTIES:
:ID:       WpvcQ4M8uXHBe42Z99o7lcL3@stanza.co
:LOCATION: Need something fun to do tonight? Get Clippers tickets here.
:STATUS:   CONFIRMED
:END:

Clippers vs. Bats Clippers vs. Bats

Buy tickets here  https //stza.co/~uWN1

Follow on MiLB First Pitch  https //stza.co/+uWN1-1v

Shop  https //stza.co/+uWN1-2R

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Clippers vs. Bats
END:VALARM
DTSTART:20180625T230500Z
DTEND:20180626T020500Z
UID:WpvcQ4M8uXHBe42Z99o7lcL3@stanza.co
SUMMARY:Clippers vs. Bats
DESCRIPTION:Clippers vs. Bats\n\nBuy tickets here: https://stza.co/~uWN1\n\nFollow on MiLB First Pitch: https://stza.co/+uWN1-1v\n\nShop: https://stza.co/+uWN1-2R\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Need something fun to do tonight? Get Clippers tickets here.
STATUS:CONFIRMED
CREATED:20180213T144516Z
LAST-MODIFIED:20180213T144516Z
TRANSP:OPAQUE
END:VEVENT
* Clippers vs. Bats
<2018-06-26 Tue 18:05-21:05>
:PROPERTIES:
:ID:       3CeSlrPVxroCuOTtXjVZeyWZ@stanza.co
:LOCATION: Don’t miss out! Clippers tickets still available here.
:STATUS:   CONFIRMED
:END:

Clippers vs. Bats Clippers vs. Bats

Buy tickets here  https //stza.co/~uWN9

Follow on MiLB First Pitch  https //stza.co/+uWN9-15

Shop  https //stza.co/+uWN9-2f

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Clippers vs. Bats
END:VALARM
DTSTART:20180626T230500Z
DTEND:20180627T020500Z
UID:3CeSlrPVxroCuOTtXjVZeyWZ@stanza.co
SUMMARY:Clippers vs. Bats
DESCRIPTION:Clippers vs. Bats\n\nBuy tickets here: https://stza.co/~uWN9\n\nFollow on MiLB First Pitch: https://stza.co/+uWN9-15\n\nShop: https://stza.co/+uWN9-2f\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don’t miss out! Clippers tickets still available here.
STATUS:CONFIRMED
CREATED:20180213T144516Z
LAST-MODIFIED:20180213T144516Z
TRANSP:OPAQUE
END:VEVENT
* Clippers vs. Bats
<2018-06-27 Wed 18:05-21:05>
:PROPERTIES:
:ID:       qP6ZQaOmzF0dc9HiAlI3z89Q@stanza.co
:LOCATION: Swipe to get tickets for the game tonight. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Clippers vs. Bats Clippers vs. Bats

Buy tickets here  https //stza.co/~uWNg

Follow on MiLB First Pitch  https //stza.co/+uWNg-D

Shop  https //stza.co/+uWNg-25

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Clippers vs. Bats
END:VALARM
DTSTART:20180627T230500Z
DTEND:20180628T020500Z
UID:qP6ZQaOmzF0dc9HiAlI3z89Q@stanza.co
SUMMARY:Clippers vs. Bats
DESCRIPTION:Clippers vs. Bats\n\nBuy tickets here: https://stza.co/~uWNg\n\nFollow on MiLB First Pitch: https://stza.co/+uWNg-D\n\nShop: https://stza.co/+uWNg-25\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Swipe to get tickets for the game tonight. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144516Z
LAST-MODIFIED:20180213T144516Z
TRANSP:OPAQUE
END:VEVENT
* Clippers vs. Indians
<2018-06-28 Thu 18:05-21:05>
:PROPERTIES:
:ID:       bz4r7gmNmOp6jPHP_KBjSiGZ@stanza.co
:LOCATION: Swipe for last minute tickets for tonight's game. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Clippers vs. Indians Clippers vs. Indians

Buy tickets here  https //stza.co/~uWNm

Follow on MiLB First Pitch  https //stza.co/+uWNm-2$

Shop  https //stza.co/+uWNm-3G

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Clippers vs. Indians
END:VALARM
DTSTART:20180628T230500Z
DTEND:20180629T020500Z
UID:bz4r7gmNmOp6jPHP_KBjSiGZ@stanza.co
SUMMARY:Clippers vs. Indians
DESCRIPTION:Clippers vs. Indians\n\nBuy tickets here: https://stza.co/~uWNm\n\nFollow on MiLB First Pitch: https://stza.co/+uWNm-2$\n\nShop: https://stza.co/+uWNm-3G\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Swipe for last minute tickets for tonight's game. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144516Z
LAST-MODIFIED:20180213T144516Z
TRANSP:OPAQUE
END:VEVENT
* Clippers vs. Indians
<2018-06-29 Fri 18:15-21:15>
:PROPERTIES:
:ID:       oXBMR9h_SQsWdHICqaB2FPiH@stanza.co
:LOCATION: Ready for the game? Swipe for tickets and more information.
:STATUS:   CONFIRMED
:END:

Clippers vs. Indians Clippers vs. Indians

Buy tickets here  https //stza.co/~uWNt

Follow on MiLB First Pitch  https //stza.co/+uWNt-22

Shop  https //stza.co/+uWNt-15

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Clippers vs. Indians
END:VALARM
DTSTART:20180629T231500Z
DTEND:20180630T021500Z
UID:oXBMR9h_SQsWdHICqaB2FPiH@stanza.co
SUMMARY:Clippers vs. Indians
DESCRIPTION:Clippers vs. Indians\n\nBuy tickets here: https://stza.co/~uWNt\n\nFollow on MiLB First Pitch: https://stza.co/+uWNt-22\n\nShop: https://stza.co/+uWNt-15\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Swipe for tickets and more information.
STATUS:CONFIRMED
CREATED:20180213T144516Z
LAST-MODIFIED:20180213T144516Z
TRANSP:OPAQUE
END:VEVENT
* Clippers vs. Indians
<2018-06-30 Sat 18:15-21:15>
:PROPERTIES:
:ID:       XzoB6RmBs_vBMLYkTMiKig1G@stanza.co
:LOCATION: Looking for something to do tonight? Get tickets here for tonight’s game and view promotions.
:STATUS:   CONFIRMED
:END:

Clippers vs. Indians Clippers vs. Indians

Buy tickets here  https //stza.co/~uWNx

Follow on MiLB First Pitch  https //stza.co/+uWNx-H

Shop  https //stza.co/+uWNx-1m

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Clippers vs. Indians
END:VALARM
DTSTART:20180630T231500Z
DTEND:20180701T021500Z
UID:XzoB6RmBs_vBMLYkTMiKig1G@stanza.co
SUMMARY:Clippers vs. Indians
DESCRIPTION:Clippers vs. Indians\n\nBuy tickets here: https://stza.co/~uWNx\n\nFollow on MiLB First Pitch: https://stza.co/+uWNx-H\n\nShop: https://stza.co/+uWNx-1m\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Looking for something to do tonight? Get tickets here for tonight’s game and view promotions.
STATUS:CONFIRMED
CREATED:20180213T144516Z
LAST-MODIFIED:20180213T144516Z
TRANSP:OPAQUE
END:VEVENT
* Clippers vs. Indians
<2018-07-01 Sun 13:05-16:05>
:PROPERTIES:
:ID:       HNF7guv7Bl5sv6MXGIu1dZV-@stanza.co
:LOCATION: Great seats still available for tonight’s game. Purchase them here.
:STATUS:   CONFIRMED
:END:

Clippers vs. Indians Clippers vs. Indians

Buy tickets here  https //stza.co/~uWNA

Follow on MiLB First Pitch  https //stza.co/+uWNA-2v

Shop  https //stza.co/+uWNA-3w

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Clippers vs. Indians
END:VALARM
DTSTART:20180701T180500Z
DTEND:20180701T210500Z
UID:HNF7guv7Bl5sv6MXGIu1dZV-@stanza.co
SUMMARY:Clippers vs. Indians
DESCRIPTION:Clippers vs. Indians\n\nBuy tickets here: https://stza.co/~uWNA\n\nFollow on MiLB First Pitch: https://stza.co/+uWNA-2v\n\nShop: https://stza.co/+uWNA-3w\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Great seats still available for tonight’s game. Purchase them here.
STATUS:CONFIRMED
CREATED:20180213T144516Z
LAST-MODIFIED:20180213T144516Z
TRANSP:OPAQUE
END:VEVENT
* Clippers @ Mud Hens
<2018-07-02 Mon 18:05-21:05>
:PROPERTIES:
:ID:       uDblUk4rhi8wrGKEbr_kpRxF@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Clippers @ Mud Hens Clippers @ Mud Hens

Follow on MiLB First Pitch  https //stza.co/+uX0a-E

Shop  https //stza.co/+uX0a-13

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Clippers @ Mud Hens
END:VALARM
DTSTART:20180702T230500Z
DTEND:20180703T020500Z
UID:uDblUk4rhi8wrGKEbr_kpRxF@stanza.co
SUMMARY:Clippers @ Mud Hens
DESCRIPTION:Clippers @ Mud Hens\n\nFollow on MiLB First Pitch: https://stza.co/+uX0a-E\n\nShop: https://stza.co/+uX0a-13\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144516Z
LAST-MODIFIED:20180213T144516Z
TRANSP:OPAQUE
END:VEVENT
* Clippers @ Mud Hens
<2018-07-03 Tue 18:05-21:05>
:PROPERTIES:
:ID:       sGD0Ij489FrgV2wcBYZEzics@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Clippers @ Mud Hens Clippers @ Mud Hens

Follow on MiLB First Pitch  https //stza.co/+uX0q-1q

Shop  https //stza.co/+uX0q-3q

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Clippers @ Mud Hens
END:VALARM
DTSTART:20180703T230500Z
DTEND:20180704T020500Z
UID:sGD0Ij489FrgV2wcBYZEzics@stanza.co
SUMMARY:Clippers @ Mud Hens
DESCRIPTION:Clippers @ Mud Hens\n\nFollow on MiLB First Pitch: https://stza.co/+uX0q-1q\n\nShop: https://stza.co/+uX0q-3q\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144516Z
LAST-MODIFIED:20180213T144516Z
TRANSP:OPAQUE
END:VEVENT
* Clippers vs. Mud Hens
<2018-07-04 Wed 18:05-21:05>
:PROPERTIES:
:ID:       F3aMzy0dU3ImgByXdLZqyYmd@stanza.co
:LOCATION: Need something fun to do tonight? Get Clippers tickets here.
:STATUS:   CONFIRMED
:END:

Clippers vs. Mud Hens Clippers vs. Mud Hens

Buy tickets here  https //stza.co/~uWNE

Follow on MiLB First Pitch  https //stza.co/+uWNE-G

Shop  https //stza.co/+uWNE-j

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Clippers vs. Mud Hens
END:VALARM
DTSTART:20180704T230500Z
DTEND:20180705T020500Z
UID:F3aMzy0dU3ImgByXdLZqyYmd@stanza.co
SUMMARY:Clippers vs. Mud Hens
DESCRIPTION:Clippers vs. Mud Hens\n\nBuy tickets here: https://stza.co/~uWNE\n\nFollow on MiLB First Pitch: https://stza.co/+uWNE-G\n\nShop: https://stza.co/+uWNE-j\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Need something fun to do tonight? Get Clippers tickets here.
STATUS:CONFIRMED
CREATED:20180213T144516Z
LAST-MODIFIED:20180213T144516Z
TRANSP:OPAQUE
END:VEVENT
* Clippers vs. Mud Hens
<2018-07-05 Thu 18:05-21:05>
:PROPERTIES:
:ID:       uemDJPfvHVRZGrNOT1Rr3-ys@stanza.co
:LOCATION: Don’t miss out! Clippers tickets still available here.
:STATUS:   CONFIRMED
:END:

Clippers vs. Mud Hens Clippers vs. Mud Hens

Buy tickets here  https //stza.co/~uWNI

Follow on MiLB First Pitch  https //stza.co/+uWNI-3h

Shop  https //stza.co/+uWNI-2F

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Clippers vs. Mud Hens
END:VALARM
DTSTART:20180705T230500Z
DTEND:20180706T020500Z
UID:uemDJPfvHVRZGrNOT1Rr3-ys@stanza.co
SUMMARY:Clippers vs. Mud Hens
DESCRIPTION:Clippers vs. Mud Hens\n\nBuy tickets here: https://stza.co/~uWNI\n\nFollow on MiLB First Pitch: https://stza.co/+uWNI-3h\n\nShop: https://stza.co/+uWNI-2F\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don’t miss out! Clippers tickets still available here.
STATUS:CONFIRMED
CREATED:20180213T144516Z
LAST-MODIFIED:20180213T144516Z
TRANSP:OPAQUE
END:VEVENT
* Clippers @ Indians
<2018-07-06 Fri 18:15-21:15>
:PROPERTIES:
:ID:       Rf-Va-5-ofdlRzx7yMZwXv84@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Clippers @ Indians Clippers @ Indians

Follow on MiLB First Pitch  https //stza.co/+uWT4-O

Shop  https //stza.co/+uWT4-2R

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Clippers @ Indians
END:VALARM
DTSTART:20180706T231500Z
DTEND:20180707T021500Z
UID:Rf-Va-5-ofdlRzx7yMZwXv84@stanza.co
SUMMARY:Clippers @ Indians
DESCRIPTION:Clippers @ Indians\n\nFollow on MiLB First Pitch: https://stza.co/+uWT4-O\n\nShop: https://stza.co/+uWT4-2R\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144516Z
LAST-MODIFIED:20180213T144516Z
TRANSP:OPAQUE
END:VEVENT
* Clippers @ Indians
<2018-07-07 Sat 18:05-21:05>
:PROPERTIES:
:ID:       mnDznB9udA71ixlOCEus1vvA@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Clippers @ Indians Clippers @ Indians

Follow on MiLB First Pitch  https //stza.co/+uWTf-3K

Shop  https //stza.co/+uWTf-W

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Clippers @ Indians
END:VALARM
DTSTART:20180707T230500Z
DTEND:20180708T020500Z
UID:mnDznB9udA71ixlOCEus1vvA@stanza.co
SUMMARY:Clippers @ Indians
DESCRIPTION:Clippers @ Indians\n\nFollow on MiLB First Pitch: https://stza.co/+uWTf-3K\n\nShop: https://stza.co/+uWTf-W\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144516Z
LAST-MODIFIED:20180213T144516Z
TRANSP:OPAQUE
END:VEVENT
* Clippers @ Indians
<2018-07-08 Sun 12:35-15:35>
:PROPERTIES:
:ID:       nMbQqQAPZUOXIB-9uBtPEoAZ@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Clippers @ Indians Clippers @ Indians

Follow on MiLB First Pitch  https //stza.co/+uWTs-R

Shop  https //stza.co/+uWTs-x

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Clippers @ Indians
END:VALARM
DTSTART:20180708T173500Z
DTEND:20180708T203500Z
UID:nMbQqQAPZUOXIB-9uBtPEoAZ@stanza.co
SUMMARY:Clippers @ Indians
DESCRIPTION:Clippers @ Indians\n\nFollow on MiLB First Pitch: https://stza.co/+uWTs-R\n\nShop: https://stza.co/+uWTs-x\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144516Z
LAST-MODIFIED:20180213T144516Z
TRANSP:OPAQUE
END:VEVENT
* Clippers @ Bats
<2018-07-12 Thu 18:00-21:00>
:PROPERTIES:
:ID:       wCxNwulBy7QqnVQwysp7LXtB@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Clippers @ Bats Clippers @ Bats

Buy tickets here  https //stza.co/~uWX5

Follow on MiLB First Pitch  https //stza.co/+uWX5-2M

Shop  https //stza.co/+uWX5-d

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Clippers @ Bats
END:VALARM
DTSTART:20180712T230000Z
DTEND:20180713T020000Z
UID:wCxNwulBy7QqnVQwysp7LXtB@stanza.co
SUMMARY:Clippers @ Bats
DESCRIPTION:Clippers @ Bats\n\nBuy tickets here: https://stza.co/~uWX5\n\nFollow on MiLB First Pitch: https://stza.co/+uWX5-2M\n\nShop: https://stza.co/+uWX5-d\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144516Z
LAST-MODIFIED:20180213T144516Z
TRANSP:OPAQUE
END:VEVENT
* Clippers @ Bats
<2018-07-13 Fri 18:00-21:00>
:PROPERTIES:
:ID:       QW8uTQj-GmsMWb0XJIfCeP8L@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Clippers @ Bats Clippers @ Bats

Buy tickets here  https //stza.co/~uWXi

Follow on MiLB First Pitch  https //stza.co/+uWXi-2z

Shop  https //stza.co/+uWXi-21

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Clippers @ Bats
END:VALARM
DTSTART:20180713T230000Z
DTEND:20180714T020000Z
UID:QW8uTQj-GmsMWb0XJIfCeP8L@stanza.co
SUMMARY:Clippers @ Bats
DESCRIPTION:Clippers @ Bats\n\nBuy tickets here: https://stza.co/~uWXi\n\nFollow on MiLB First Pitch: https://stza.co/+uWXi-2z\n\nShop: https://stza.co/+uWXi-21\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144516Z
LAST-MODIFIED:20180213T144516Z
TRANSP:OPAQUE
END:VEVENT
* Clippers @ Bats
<2018-07-14 Sat 17:30-20:30>
:PROPERTIES:
:ID:       Ad0YFROzea9_8-rLzBFBkONU@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Clippers @ Bats Clippers @ Bats

Buy tickets here  https //stza.co/~uWXv

Follow on MiLB First Pitch  https //stza.co/+uWXv-33

Shop  https //stza.co/+uWXv-y

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Clippers @ Bats
END:VALARM
DTSTART:20180714T223000Z
DTEND:20180715T013000Z
UID:Ad0YFROzea9_8-rLzBFBkONU@stanza.co
SUMMARY:Clippers @ Bats
DESCRIPTION:Clippers @ Bats\n\nBuy tickets here: https://stza.co/~uWXv\n\nFollow on MiLB First Pitch: https://stza.co/+uWXv-33\n\nShop: https://stza.co/+uWXv-y\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144516Z
LAST-MODIFIED:20180213T144516Z
TRANSP:OPAQUE
END:VEVENT
* Clippers @ Bats
<2018-07-15 Sun 17:00-20:00>
:PROPERTIES:
:ID:       9yNBs5l3ftcU54gHTDEOg4p2@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Clippers @ Bats Clippers @ Bats

Buy tickets here  https //stza.co/~uWXI

Follow on MiLB First Pitch  https //stza.co/+uWXI-1O

Shop  https //stza.co/+uWXI-1v

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Clippers @ Bats
END:VALARM
DTSTART:20180715T220000Z
DTEND:20180716T010000Z
UID:9yNBs5l3ftcU54gHTDEOg4p2@stanza.co
SUMMARY:Clippers @ Bats
DESCRIPTION:Clippers @ Bats\n\nBuy tickets here: https://stza.co/~uWXI\n\nFollow on MiLB First Pitch: https://stza.co/+uWXI-1O\n\nShop: https://stza.co/+uWXI-1v\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144516Z
LAST-MODIFIED:20180213T144516Z
TRANSP:OPAQUE
END:VEVENT
* Clippers vs. IronPigs
<2018-07-16 Mon 18:05-21:05>
:PROPERTIES:
:ID:       uSH2j6w_g_WuYQPcqMhRk0Wq@stanza.co
:LOCATION: Swipe to get tickets for the game tonight. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Clippers vs. IronPigs Clippers vs. IronPigs

Buy tickets here  https //stza.co/~uWNN

Follow on MiLB First Pitch  https //stza.co/+uWNN-1G

Shop  https //stza.co/+uWNN-2Z

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Clippers vs. IronPigs
END:VALARM
DTSTART:20180716T230500Z
DTEND:20180717T020500Z
UID:uSH2j6w_g_WuYQPcqMhRk0Wq@stanza.co
SUMMARY:Clippers vs. IronPigs
DESCRIPTION:Clippers vs. IronPigs\n\nBuy tickets here: https://stza.co/~uWNN\n\nFollow on MiLB First Pitch: https://stza.co/+uWNN-1G\n\nShop: https://stza.co/+uWNN-2Z\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Swipe to get tickets for the game tonight. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144516Z
LAST-MODIFIED:20180213T144516Z
TRANSP:OPAQUE
END:VEVENT
* Clippers vs. IronPigs
<2018-07-17 Tue 11:05-14:05>
:PROPERTIES:
:ID:       BK2XKKGPqxMDGX6xhJ3Eb1LN@stanza.co
:LOCATION: Swipe for last minute tickets for tonight's game. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Clippers vs. IronPigs Clippers vs. IronPigs

Buy tickets here  https //stza.co/~uWNQ

Follow on MiLB First Pitch  https //stza.co/+uWNQ-3Z

Shop  https //stza.co/+uWNQ-3K

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Clippers vs. IronPigs
END:VALARM
DTSTART:20180717T160500Z
DTEND:20180717T190500Z
UID:BK2XKKGPqxMDGX6xhJ3Eb1LN@stanza.co
SUMMARY:Clippers vs. IronPigs
DESCRIPTION:Clippers vs. IronPigs\n\nBuy tickets here: https://stza.co/~uWNQ\n\nFollow on MiLB First Pitch: https://stza.co/+uWNQ-3Z\n\nShop: https://stza.co/+uWNQ-3K\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Swipe for last minute tickets for tonight's game. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144516Z
LAST-MODIFIED:20180213T144516Z
TRANSP:OPAQUE
END:VEVENT
* Clippers vs. IronPigs
<2018-07-18 Wed 18:05-21:05>
:PROPERTIES:
:ID:       HcKfTvo6e4IFahMDvTHLSopO@stanza.co
:LOCATION: Ready for the game? Swipe for tickets and more information.
:STATUS:   CONFIRMED
:END:

Clippers vs. IronPigs Clippers vs. IronPigs

Buy tickets here  https //stza.co/~uWNU

Follow on MiLB First Pitch  https //stza.co/+uWNU-m

Shop  https //stza.co/+uWNU-3Q

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Clippers vs. IronPigs
END:VALARM
DTSTART:20180718T230500Z
DTEND:20180719T020500Z
UID:HcKfTvo6e4IFahMDvTHLSopO@stanza.co
SUMMARY:Clippers vs. IronPigs
DESCRIPTION:Clippers vs. IronPigs\n\nBuy tickets here: https://stza.co/~uWNU\n\nFollow on MiLB First Pitch: https://stza.co/+uWNU-m\n\nShop: https://stza.co/+uWNU-3Q\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Swipe for tickets and more information.
STATUS:CONFIRMED
CREATED:20180213T144516Z
LAST-MODIFIED:20180213T144516Z
TRANSP:OPAQUE
END:VEVENT
* Clippers vs. RailRiders
<2018-07-19 Thu 18:05-21:05>
:PROPERTIES:
:ID:       yVUo5GsUsgeiGAJKh3OhefNA@stanza.co
:LOCATION: Looking for something to do tonight? Get tickets here for tonight’s game and view promotions.
:STATUS:   CONFIRMED
:END:

Clippers vs. RailRiders Clippers vs. RailRiders

Buy tickets here  https //stza.co/~uWNZ

Follow on MiLB First Pitch  https //stza.co/+uWNZ-34

Shop  https //stza.co/+uWNZ-2j

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Clippers vs. RailRiders
END:VALARM
DTSTART:20180719T230500Z
DTEND:20180720T020500Z
UID:yVUo5GsUsgeiGAJKh3OhefNA@stanza.co
SUMMARY:Clippers vs. RailRiders
DESCRIPTION:Clippers vs. RailRiders\n\nBuy tickets here: https://stza.co/~uWNZ\n\nFollow on MiLB First Pitch: https://stza.co/+uWNZ-34\n\nShop: https://stza.co/+uWNZ-2j\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Looking for something to do tonight? Get tickets here for tonight’s game and view promotions.
STATUS:CONFIRMED
CREATED:20180213T144516Z
LAST-MODIFIED:20180213T144516Z
TRANSP:OPAQUE
END:VEVENT
* Clippers vs. RailRiders
<2018-07-20 Fri 18:15-21:15>
:PROPERTIES:
:ID:       UaNMJJskeyhptkPaBIgdgonI@stanza.co
:LOCATION: Great seats still available for tonight’s game. Purchase them here.
:STATUS:   CONFIRMED
:END:

Clippers vs. RailRiders Clippers vs. RailRiders

Buy tickets here  https //stza.co/~uWO1

Follow on MiLB First Pitch  https //stza.co/+uWO1-1Y

Shop  https //stza.co/+uWO1-3F

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Clippers vs. RailRiders
END:VALARM
DTSTART:20180720T231500Z
DTEND:20180721T021500Z
UID:UaNMJJskeyhptkPaBIgdgonI@stanza.co
SUMMARY:Clippers vs. RailRiders
DESCRIPTION:Clippers vs. RailRiders\n\nBuy tickets here: https://stza.co/~uWO1\n\nFollow on MiLB First Pitch: https://stza.co/+uWO1-1Y\n\nShop: https://stza.co/+uWO1-3F\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Great seats still available for tonight’s game. Purchase them here.
STATUS:CONFIRMED
CREATED:20180213T144516Z
LAST-MODIFIED:20180213T144516Z
TRANSP:OPAQUE
END:VEVENT
* Clippers vs. RailRiders
<2018-07-21 Sat 18:15-21:15>
:PROPERTIES:
:ID:       u21PUT10UZlShrWCeubV4Vgr@stanza.co
:LOCATION: Need something fun to do tonight? Get Clippers tickets here.
:STATUS:   CONFIRMED
:END:

Clippers vs. RailRiders Clippers vs. RailRiders

Buy tickets here  https //stza.co/~uWO4

Follow on MiLB First Pitch  https //stza.co/+uWO4-1p

Shop  https //stza.co/+uWO4-j

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Clippers vs. RailRiders
END:VALARM
DTSTART:20180721T231500Z
DTEND:20180722T021500Z
UID:u21PUT10UZlShrWCeubV4Vgr@stanza.co
SUMMARY:Clippers vs. RailRiders
DESCRIPTION:Clippers vs. RailRiders\n\nBuy tickets here: https://stza.co/~uWO4\n\nFollow on MiLB First Pitch: https://stza.co/+uWO4-1p\n\nShop: https://stza.co/+uWO4-j\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Need something fun to do tonight? Get Clippers tickets here.
STATUS:CONFIRMED
CREATED:20180213T144516Z
LAST-MODIFIED:20180213T144516Z
TRANSP:OPAQUE
END:VEVENT
* Clippers vs. RailRiders
<2018-07-22 Sun 15:05-18:05>
:PROPERTIES:
:ID:       NkRAzBaoBH3Hk4NCnfioK5Zr@stanza.co
:LOCATION: Don’t miss out! Clippers tickets still available here.
:STATUS:   CONFIRMED
:END:

Clippers vs. RailRiders Clippers vs. RailRiders

Buy tickets here  https //stza.co/~uWO8

Follow on MiLB First Pitch  https //stza.co/+uWO8-2U

Shop  https //stza.co/+uWO8-11

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Clippers vs. RailRiders
END:VALARM
DTSTART:20180722T200500Z
DTEND:20180722T230500Z
UID:NkRAzBaoBH3Hk4NCnfioK5Zr@stanza.co
SUMMARY:Clippers vs. RailRiders
DESCRIPTION:Clippers vs. RailRiders\n\nBuy tickets here: https://stza.co/~uWO8\n\nFollow on MiLB First Pitch: https://stza.co/+uWO8-2U\n\nShop: https://stza.co/+uWO8-11\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don’t miss out! Clippers tickets still available here.
STATUS:CONFIRMED
CREATED:20180213T144516Z
LAST-MODIFIED:20180213T144516Z
TRANSP:OPAQUE
END:VEVENT
* Clippers @ Red Sox
<2018-07-24 Tue 18:05-21:05>
:PROPERTIES:
:ID:       cbUUZSvNNqQzsDSkIyAy3EGK@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Clippers @ Red Sox Clippers @ Red Sox

Buy tickets here  https //stza.co/~uWYw

Follow on MiLB First Pitch  https //stza.co/+uWYw-2N

Shop  https //stza.co/+uWYw-1I

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Clippers @ Red Sox
END:VALARM
DTSTART:20180724T230500Z
DTEND:20180725T020500Z
UID:cbUUZSvNNqQzsDSkIyAy3EGK@stanza.co
SUMMARY:Clippers @ Red Sox
DESCRIPTION:Clippers @ Red Sox\n\nBuy tickets here: https://stza.co/~uWYw\n\nFollow on MiLB First Pitch: https://stza.co/+uWYw-2N\n\nShop: https://stza.co/+uWYw-1I\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144516Z
LAST-MODIFIED:20180213T144516Z
TRANSP:OPAQUE
END:VEVENT
* Clippers @ Red Sox
<2018-07-25 Wed 18:05-21:05>
:PROPERTIES:
:ID:       LXzYocDyICKoDEKdBmxM6uq6@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Clippers @ Red Sox Clippers @ Red Sox

Buy tickets here  https //stza.co/~uWYK

Follow on MiLB First Pitch  https //stza.co/+uWYK-3Z

Shop  https //stza.co/+uWYK-3b

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Clippers @ Red Sox
END:VALARM
DTSTART:20180725T230500Z
DTEND:20180726T020500Z
UID:LXzYocDyICKoDEKdBmxM6uq6@stanza.co
SUMMARY:Clippers @ Red Sox
DESCRIPTION:Clippers @ Red Sox\n\nBuy tickets here: https://stza.co/~uWYK\n\nFollow on MiLB First Pitch: https://stza.co/+uWYK-3Z\n\nShop: https://stza.co/+uWYK-3b\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144516Z
LAST-MODIFIED:20180213T144516Z
TRANSP:OPAQUE
END:VEVENT
* Clippers @ Red Sox
<2018-07-26 Thu 10:05-13:05>
:PROPERTIES:
:ID:       CIizWUwEwUDYi90Z_MpLHDTj@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Clippers @ Red Sox Clippers @ Red Sox

Buy tickets here  https //stza.co/~uWYX

Follow on MiLB First Pitch  https //stza.co/+uWYX-3z

Shop  https //stza.co/+uWYX-3m

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Clippers @ Red Sox
END:VALARM
DTSTART:20180726T150500Z
DTEND:20180726T180500Z
UID:CIizWUwEwUDYi90Z_MpLHDTj@stanza.co
SUMMARY:Clippers @ Red Sox
DESCRIPTION:Clippers @ Red Sox\n\nBuy tickets here: https://stza.co/~uWYX\n\nFollow on MiLB First Pitch: https://stza.co/+uWYX-3z\n\nShop: https://stza.co/+uWYX-3m\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144516Z
LAST-MODIFIED:20180213T144516Z
TRANSP:OPAQUE
END:VEVENT
* Clippers @ IronPigs
<2018-07-27 Fri 18:05-21:05>
:PROPERTIES:
:ID:       i4_qmbS8zbp1b3zmbWHZ6KPI@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Clippers @ IronPigs Clippers @ IronPigs

Follow on MiLB First Pitch  https //stza.co/+uWUh-1Q

Shop  https //stza.co/+uWUh-3J

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Clippers @ IronPigs
END:VALARM
DTSTART:20180727T230500Z
DTEND:20180728T020500Z
UID:i4_qmbS8zbp1b3zmbWHZ6KPI@stanza.co
SUMMARY:Clippers @ IronPigs
DESCRIPTION:Clippers @ IronPigs\n\nFollow on MiLB First Pitch: https://stza.co/+uWUh-1Q\n\nShop: https://stza.co/+uWUh-3J\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144516Z
LAST-MODIFIED:20180213T144516Z
TRANSP:OPAQUE
END:VEVENT
* Clippers @ IronPigs
<2018-07-28 Sat 17:35-20:35>
:PROPERTIES:
:ID:       8UGM0NOS-9NhfYAEp-mV2hia@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Clippers @ IronPigs Clippers @ IronPigs

Follow on MiLB First Pitch  https //stza.co/+uWUw-1i

Shop  https //stza.co/+uWUw-d

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Clippers @ IronPigs
END:VALARM
DTSTART:20180728T223500Z
DTEND:20180729T013500Z
UID:8UGM0NOS-9NhfYAEp-mV2hia@stanza.co
SUMMARY:Clippers @ IronPigs
DESCRIPTION:Clippers @ IronPigs\n\nFollow on MiLB First Pitch: https://stza.co/+uWUw-1i\n\nShop: https://stza.co/+uWUw-d\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144516Z
LAST-MODIFIED:20180213T144516Z
TRANSP:OPAQUE
END:VEVENT
* Clippers @ IronPigs
<2018-07-29 Sun 12:35-15:35>
:PROPERTIES:
:ID:       x2tL1OX-PhwqUMPUPL_DKu40@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Clippers @ IronPigs Clippers @ IronPigs

Follow on MiLB First Pitch  https //stza.co/+uWUN-32

Shop  https //stza.co/+uWUN-U

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Clippers @ IronPigs
END:VALARM
DTSTART:20180729T173500Z
DTEND:20180729T203500Z
UID:x2tL1OX-PhwqUMPUPL_DKu40@stanza.co
SUMMARY:Clippers @ IronPigs
DESCRIPTION:Clippers @ IronPigs\n\nFollow on MiLB First Pitch: https://stza.co/+uWUN-32\n\nShop: https://stza.co/+uWUN-U\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144516Z
LAST-MODIFIED:20180213T144516Z
TRANSP:OPAQUE
END:VEVENT
* Clippers vs. Indians
<2018-07-30 Mon 18:05-21:05>
:PROPERTIES:
:ID:       nkcKp_9QZO11fV2TVgEQBbZe@stanza.co
:LOCATION: Swipe to get tickets for the game tonight. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Clippers vs. Indians Clippers vs. Indians

Buy tickets here  https //stza.co/~uWOc

Follow on MiLB First Pitch  https //stza.co/+uWOc-2z

Shop  https //stza.co/+uWOc-2v

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Clippers vs. Indians
END:VALARM
DTSTART:20180730T230500Z
DTEND:20180731T020500Z
UID:nkcKp_9QZO11fV2TVgEQBbZe@stanza.co
SUMMARY:Clippers vs. Indians
DESCRIPTION:Clippers vs. Indians\n\nBuy tickets here: https://stza.co/~uWOc\n\nFollow on MiLB First Pitch: https://stza.co/+uWOc-2z\n\nShop: https://stza.co/+uWOc-2v\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Swipe to get tickets for the game tonight. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144516Z
LAST-MODIFIED:20180213T144516Z
TRANSP:OPAQUE
END:VEVENT
* Clippers vs. Indians
<2018-07-31 Tue 18:05-21:05>
:PROPERTIES:
:ID:       wBYuRA4aFK3N6AKuSso3M3OB@stanza.co
:LOCATION: Swipe for last minute tickets for tonight's game. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Clippers vs. Indians Clippers vs. Indians

Buy tickets here  https //stza.co/~uWOi

Follow on MiLB First Pitch  https //stza.co/+uWOi-p

Shop  https //stza.co/+uWOi-3L

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Clippers vs. Indians
END:VALARM
DTSTART:20180731T230500Z
DTEND:20180801T020500Z
UID:wBYuRA4aFK3N6AKuSso3M3OB@stanza.co
SUMMARY:Clippers vs. Indians
DESCRIPTION:Clippers vs. Indians\n\nBuy tickets here: https://stza.co/~uWOi\n\nFollow on MiLB First Pitch: https://stza.co/+uWOi-p\n\nShop: https://stza.co/+uWOi-3L\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Swipe for last minute tickets for tonight's game. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144516Z
LAST-MODIFIED:20180213T144516Z
TRANSP:OPAQUE
END:VEVENT
* Clippers vs. Indians
<2018-08-01 Wed 18:05-21:05>
:PROPERTIES:
:ID:       ngctKxqV0_dPjNKDVBV0f2QD@stanza.co
:LOCATION: Ready for the game? Swipe for tickets and more information.
:STATUS:   CONFIRMED
:END:

Clippers vs. Indians Clippers vs. Indians

Buy tickets here  https //stza.co/~uWOn

Follow on MiLB First Pitch  https //stza.co/+uWOn-3U

Shop  https //stza.co/+uWOn-1L

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Clippers vs. Indians
END:VALARM
DTSTART:20180801T230500Z
DTEND:20180802T020500Z
UID:ngctKxqV0_dPjNKDVBV0f2QD@stanza.co
SUMMARY:Clippers vs. Indians
DESCRIPTION:Clippers vs. Indians\n\nBuy tickets here: https://stza.co/~uWOn\n\nFollow on MiLB First Pitch: https://stza.co/+uWOn-3U\n\nShop: https://stza.co/+uWOn-1L\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Swipe for tickets and more information.
STATUS:CONFIRMED
CREATED:20180213T144516Z
LAST-MODIFIED:20180213T144516Z
TRANSP:OPAQUE
END:VEVENT
* Clippers vs. Bats
<2018-08-02 Thu 18:05-21:05>
:PROPERTIES:
:ID:       TqB0cFwYD84vTcVZbSNpYchw@stanza.co
:LOCATION: Looking for something to do tonight? Get tickets here for tonight’s game and view promotions.
:STATUS:   CONFIRMED
:END:

Clippers vs. Bats Clippers vs. Bats

Buy tickets here  https //stza.co/~uWOt

Follow on MiLB First Pitch  https //stza.co/+uWOt-1C

Shop  https //stza.co/+uWOt-2e

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Clippers vs. Bats
END:VALARM
DTSTART:20180802T230500Z
DTEND:20180803T020500Z
UID:TqB0cFwYD84vTcVZbSNpYchw@stanza.co
SUMMARY:Clippers vs. Bats
DESCRIPTION:Clippers vs. Bats\n\nBuy tickets here: https://stza.co/~uWOt\n\nFollow on MiLB First Pitch: https://stza.co/+uWOt-1C\n\nShop: https://stza.co/+uWOt-2e\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Looking for something to do tonight? Get tickets here for tonight’s game and view promotions.
STATUS:CONFIRMED
CREATED:20180213T144516Z
LAST-MODIFIED:20180213T144516Z
TRANSP:OPAQUE
END:VEVENT
* Clippers vs. Bats
<2018-08-03 Fri 18:15-21:15>
:PROPERTIES:
:ID:       trZ0m2h3eXsvWo486b1WE9sa@stanza.co
:LOCATION: Great seats still available for tonight’s game. Purchase them here.
:STATUS:   CONFIRMED
:END:

Clippers vs. Bats Clippers vs. Bats

Buy tickets here  https //stza.co/~uWOz

Follow on MiLB First Pitch  https //stza.co/+uWOz-B

Shop  https //stza.co/+uWOz-2E

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Clippers vs. Bats
END:VALARM
DTSTART:20180803T231500Z
DTEND:20180804T021500Z
UID:trZ0m2h3eXsvWo486b1WE9sa@stanza.co
SUMMARY:Clippers vs. Bats
DESCRIPTION:Clippers vs. Bats\n\nBuy tickets here: https://stza.co/~uWOz\n\nFollow on MiLB First Pitch: https://stza.co/+uWOz-B\n\nShop: https://stza.co/+uWOz-2E\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Great seats still available for tonight’s game. Purchase them here.
STATUS:CONFIRMED
CREATED:20180213T144516Z
LAST-MODIFIED:20180213T144516Z
TRANSP:OPAQUE
END:VEVENT
* Clippers vs. Bats
<2018-08-04 Sat 18:15-21:15>
:PROPERTIES:
:ID:       SigYuGWrrjgFSxkkoiephqPK@stanza.co
:LOCATION: Need something fun to do tonight? Get Clippers tickets here.
:STATUS:   CONFIRMED
:END:

Clippers vs. Bats Clippers vs. Bats

Buy tickets here  https //stza.co/~uWOB

Follow on MiLB First Pitch  https //stza.co/+uWOB-18

Shop  https //stza.co/+uWOB-3S

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Clippers vs. Bats
END:VALARM
DTSTART:20180804T231500Z
DTEND:20180805T021500Z
UID:SigYuGWrrjgFSxkkoiephqPK@stanza.co
SUMMARY:Clippers vs. Bats
DESCRIPTION:Clippers vs. Bats\n\nBuy tickets here: https://stza.co/~uWOB\n\nFollow on MiLB First Pitch: https://stza.co/+uWOB-18\n\nShop: https://stza.co/+uWOB-3S\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Need something fun to do tonight? Get Clippers tickets here.
STATUS:CONFIRMED
CREATED:20180213T144516Z
LAST-MODIFIED:20180213T144516Z
TRANSP:OPAQUE
END:VEVENT
* Clippers vs. Bats
<2018-08-05 Sun 15:05-18:05>
:PROPERTIES:
:ID:       Wf5vTZnuNm_xBRG4rUhxAiwK@stanza.co
:LOCATION: Don’t miss out! Clippers tickets still available here.
:STATUS:   CONFIRMED
:END:

Clippers vs. Bats Clippers vs. Bats

Buy tickets here  https //stza.co/~uWOG

Follow on MiLB First Pitch  https //stza.co/+uWOG-u

Shop  https //stza.co/+uWOG-R

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Clippers vs. Bats
END:VALARM
DTSTART:20180805T200500Z
DTEND:20180805T230500Z
UID:Wf5vTZnuNm_xBRG4rUhxAiwK@stanza.co
SUMMARY:Clippers vs. Bats
DESCRIPTION:Clippers vs. Bats\n\nBuy tickets here: https://stza.co/~uWOG\n\nFollow on MiLB First Pitch: https://stza.co/+uWOG-u\n\nShop: https://stza.co/+uWOG-R\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don’t miss out! Clippers tickets still available here.
STATUS:CONFIRMED
CREATED:20180213T144516Z
LAST-MODIFIED:20180213T144516Z
TRANSP:OPAQUE
END:VEVENT
* Clippers @ Bulls
<2018-08-07 Tue 18:05-21:05>
:PROPERTIES:
:ID:       FhIvl7jZF6yF0soQeEADRmWx@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Clippers @ Bulls Clippers @ Bulls

Follow on MiLB First Pitch  https //stza.co/+uWP_-d

Shop  https //stza.co/+uWP_-1D

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Clippers @ Bulls
END:VALARM
DTSTART:20180807T230500Z
DTEND:20180808T020500Z
UID:FhIvl7jZF6yF0soQeEADRmWx@stanza.co
SUMMARY:Clippers @ Bulls
DESCRIPTION:Clippers @ Bulls\n\nFollow on MiLB First Pitch: https://stza.co/+uWP_-d\n\nShop: https://stza.co/+uWP_-1D\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144516Z
LAST-MODIFIED:20180213T144516Z
TRANSP:OPAQUE
END:VEVENT
* Clippers @ Bulls
<2018-08-08 Wed 18:05-21:05>
:PROPERTIES:
:ID:       QeaI-ge405zfbR4ydNqv2RUV@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Clippers @ Bulls Clippers @ Bulls

Follow on MiLB First Pitch  https //stza.co/+uWQ8-2Q

Shop  https //stza.co/+uWQ8-1X

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Clippers @ Bulls
END:VALARM
DTSTART:20180808T230500Z
DTEND:20180809T020500Z
UID:QeaI-ge405zfbR4ydNqv2RUV@stanza.co
SUMMARY:Clippers @ Bulls
DESCRIPTION:Clippers @ Bulls\n\nFollow on MiLB First Pitch: https://stza.co/+uWQ8-2Q\n\nShop: https://stza.co/+uWQ8-1X\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144516Z
LAST-MODIFIED:20180213T144516Z
TRANSP:OPAQUE
END:VEVENT
* Clippers @ Bulls
<2018-08-09 Thu 18:05-21:05>
:PROPERTIES:
:ID:       e-SVEoLlfN1TCAsiNZtSruNw@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Clippers @ Bulls Clippers @ Bulls

Follow on MiLB First Pitch  https //stza.co/+uWQj-1s

Shop  https //stza.co/+uWQj-2f

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Clippers @ Bulls
END:VALARM
DTSTART:20180809T230500Z
DTEND:20180810T020500Z
UID:e-SVEoLlfN1TCAsiNZtSruNw@stanza.co
SUMMARY:Clippers @ Bulls
DESCRIPTION:Clippers @ Bulls\n\nFollow on MiLB First Pitch: https://stza.co/+uWQj-1s\n\nShop: https://stza.co/+uWQj-2f\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144516Z
LAST-MODIFIED:20180213T144516Z
TRANSP:OPAQUE
END:VEVENT
* Clippers @ Tides
<2018-08-10 Fri 18:05-21:05>
:PROPERTIES:
:ID:       fUkQzcnZgw5rU6PrJWxre_tJ@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Clippers @ Tides Clippers @ Tides

Follow on MiLB First Pitch  https //stza.co/+uWXV-E

Shop  https //stza.co/+uWXV-2r

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Clippers @ Tides
END:VALARM
DTSTART:20180810T230500Z
DTEND:20180811T020500Z
UID:fUkQzcnZgw5rU6PrJWxre_tJ@stanza.co
SUMMARY:Clippers @ Tides
DESCRIPTION:Clippers @ Tides\n\nFollow on MiLB First Pitch: https://stza.co/+uWXV-E\n\nShop: https://stza.co/+uWXV-2r\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144516Z
LAST-MODIFIED:20180213T144516Z
TRANSP:OPAQUE
END:VEVENT
* Clippers @ Tides
<2018-08-11 Sat 18:05-21:05>
:PROPERTIES:
:ID:       Pt5esQigHmOFvJuBoPyYoR_R@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Clippers @ Tides Clippers @ Tides

Follow on MiLB First Pitch  https //stza.co/+uWY6-2I

Shop  https //stza.co/+uWY6-1R

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Clippers @ Tides
END:VALARM
DTSTART:20180811T230500Z
DTEND:20180812T020500Z
UID:Pt5esQigHmOFvJuBoPyYoR_R@stanza.co
SUMMARY:Clippers @ Tides
DESCRIPTION:Clippers @ Tides\n\nFollow on MiLB First Pitch: https://stza.co/+uWY6-2I\n\nShop: https://stza.co/+uWY6-1R\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144516Z
LAST-MODIFIED:20180213T144516Z
TRANSP:OPAQUE
END:VEVENT
* Clippers @ Tides
<2018-08-12 Sun 15:05-18:05>
:PROPERTIES:
:ID:       tR-VHiclxASFdI4jMufOPlNF@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Clippers @ Tides Clippers @ Tides

Follow on MiLB First Pitch  https //stza.co/+uWYj-r

Shop  https //stza.co/+uWYj-1C

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Clippers @ Tides
END:VALARM
DTSTART:20180812T200500Z
DTEND:20180812T230500Z
UID:tR-VHiclxASFdI4jMufOPlNF@stanza.co
SUMMARY:Clippers @ Tides
DESCRIPTION:Clippers @ Tides\n\nFollow on MiLB First Pitch: https://stza.co/+uWYj-r\n\nShop: https://stza.co/+uWYj-1C\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144516Z
LAST-MODIFIED:20180213T144516Z
TRANSP:OPAQUE
END:VEVENT
* Clippers vs. Red Wings
<2018-08-13 Mon 18:05-21:05>
:PROPERTIES:
:ID:       4pEdxdALjKvRJy9wwOPZvy9j@stanza.co
:LOCATION: Swipe to get tickets for the game tonight. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Clippers vs. Red Wings Clippers vs. Red Wings

Buy tickets here  https //stza.co/~uWOL

Follow on MiLB First Pitch  https //stza.co/+uWOL-3_

Shop  https //stza.co/+uWOL-1A

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Clippers vs. Red Wings
END:VALARM
DTSTART:20180813T230500Z
DTEND:20180814T020500Z
UID:4pEdxdALjKvRJy9wwOPZvy9j@stanza.co
SUMMARY:Clippers vs. Red Wings
DESCRIPTION:Clippers vs. Red Wings\n\nBuy tickets here: https://stza.co/~uWOL\n\nFollow on MiLB First Pitch: https://stza.co/+uWOL-3_\n\nShop: https://stza.co/+uWOL-1A\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Swipe to get tickets for the game tonight. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144516Z
LAST-MODIFIED:20180213T144516Z
TRANSP:OPAQUE
END:VEVENT
* Clippers vs. Red Wings
<2018-08-14 Tue 18:05-21:05>
:PROPERTIES:
:ID:       mQzofDbdUzPDxxWfS1wC_agL@stanza.co
:LOCATION: Swipe for last minute tickets for tonight's game. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Clippers vs. Red Wings Clippers vs. Red Wings

Buy tickets here  https //stza.co/~uWOR

Follow on MiLB First Pitch  https //stza.co/+uWOR-2Y

Shop  https //stza.co/+uWOR-2y

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Clippers vs. Red Wings
END:VALARM
DTSTART:20180814T230500Z
DTEND:20180815T020500Z
UID:mQzofDbdUzPDxxWfS1wC_agL@stanza.co
SUMMARY:Clippers vs. Red Wings
DESCRIPTION:Clippers vs. Red Wings\n\nBuy tickets here: https://stza.co/~uWOR\n\nFollow on MiLB First Pitch: https://stza.co/+uWOR-2Y\n\nShop: https://stza.co/+uWOR-2y\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Swipe for last minute tickets for tonight's game. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144516Z
LAST-MODIFIED:20180213T144516Z
TRANSP:OPAQUE
END:VEVENT
* Clippers vs. Red Wings
<2018-08-15 Wed 11:05-14:05>
:PROPERTIES:
:ID:       rpamPFFVIfJ05R7DD0M6M6qq@stanza.co
:LOCATION: Ready for the game? Swipe for tickets and more information.
:STATUS:   CONFIRMED
:END:

Clippers vs. Red Wings Clippers vs. Red Wings

Buy tickets here  https //stza.co/~uWOW

Follow on MiLB First Pitch  https //stza.co/+uWOW-1Q

Shop  https //stza.co/+uWOW-1o

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Clippers vs. Red Wings
END:VALARM
DTSTART:20180815T160500Z
DTEND:20180815T190500Z
UID:rpamPFFVIfJ05R7DD0M6M6qq@stanza.co
SUMMARY:Clippers vs. Red Wings
DESCRIPTION:Clippers vs. Red Wings\n\nBuy tickets here: https://stza.co/~uWOW\n\nFollow on MiLB First Pitch: https://stza.co/+uWOW-1Q\n\nShop: https://stza.co/+uWOW-1o\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Swipe for tickets and more information.
STATUS:CONFIRMED
CREATED:20180213T144516Z
LAST-MODIFIED:20180213T144516Z
TRANSP:OPAQUE
END:VEVENT
* Clippers vs. Chiefs
<2018-08-16 Thu 18:05-21:05>
:PROPERTIES:
:ID:       ATGff39zTv9UuCn1gKC00TrI@stanza.co
:LOCATION: Looking for something to do tonight? Get tickets here for tonight’s game and view promotions.
:STATUS:   CONFIRMED
:END:

Clippers vs. Chiefs Clippers vs. Chiefs

Buy tickets here  https //stza.co/~uWO_

Follow on MiLB First Pitch  https //stza.co/+uWO_-2M

Shop  https //stza.co/+uWO_-3H

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Clippers vs. Chiefs
END:VALARM
DTSTART:20180816T230500Z
DTEND:20180817T020500Z
UID:ATGff39zTv9UuCn1gKC00TrI@stanza.co
SUMMARY:Clippers vs. Chiefs
DESCRIPTION:Clippers vs. Chiefs\n\nBuy tickets here: https://stza.co/~uWO_\n\nFollow on MiLB First Pitch: https://stza.co/+uWO_-2M\n\nShop: https://stza.co/+uWO_-3H\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Looking for something to do tonight? Get tickets here for tonight’s game and view promotions.
STATUS:CONFIRMED
CREATED:20180213T144516Z
LAST-MODIFIED:20180213T144516Z
TRANSP:OPAQUE
END:VEVENT
* Clippers vs. Chiefs
<2018-08-17 Fri 18:15-21:15>
:PROPERTIES:
:ID:       7ojwOLv6-8bM_jpqWqGE_SIK@stanza.co
:LOCATION: Great seats still available for tonight’s game. Purchase them here.
:STATUS:   CONFIRMED
:END:

Clippers vs. Chiefs Clippers vs. Chiefs

Buy tickets here  https //stza.co/~uWP3

Follow on MiLB First Pitch  https //stza.co/+uWP3-r

Shop  https //stza.co/+uWP3-3G

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Clippers vs. Chiefs
END:VALARM
DTSTART:20180817T231500Z
DTEND:20180818T021500Z
UID:7ojwOLv6-8bM_jpqWqGE_SIK@stanza.co
SUMMARY:Clippers vs. Chiefs
DESCRIPTION:Clippers vs. Chiefs\n\nBuy tickets here: https://stza.co/~uWP3\n\nFollow on MiLB First Pitch: https://stza.co/+uWP3-r\n\nShop: https://stza.co/+uWP3-3G\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Great seats still available for tonight’s game. Purchase them here.
STATUS:CONFIRMED
CREATED:20180213T144516Z
LAST-MODIFIED:20180213T144516Z
TRANSP:OPAQUE
END:VEVENT
* Clippers vs. Chiefs
<2018-08-18 Sat 18:15-21:15>
:PROPERTIES:
:ID:       CfKVWB2GuH_HIDl4kKXiz2EL@stanza.co
:LOCATION: Need something fun to do tonight? Get Clippers tickets here.
:STATUS:   CONFIRMED
:END:

Clippers vs. Chiefs Clippers vs. Chiefs

Buy tickets here  https //stza.co/~uWP8

Follow on MiLB First Pitch  https //stza.co/+uWP8-3J

Shop  https //stza.co/+uWP8-e

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Clippers vs. Chiefs
END:VALARM
DTSTART:20180818T231500Z
DTEND:20180819T021500Z
UID:CfKVWB2GuH_HIDl4kKXiz2EL@stanza.co
SUMMARY:Clippers vs. Chiefs
DESCRIPTION:Clippers vs. Chiefs\n\nBuy tickets here: https://stza.co/~uWP8\n\nFollow on MiLB First Pitch: https://stza.co/+uWP8-3J\n\nShop: https://stza.co/+uWP8-e\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Need something fun to do tonight? Get Clippers tickets here.
STATUS:CONFIRMED
CREATED:20180213T144516Z
LAST-MODIFIED:20180213T144516Z
TRANSP:OPAQUE
END:VEVENT
* Clippers vs. Chiefs
<2018-08-19 Sun 15:05-18:05>
:PROPERTIES:
:ID:       p2gL2Drr9hz3sF7-Qin8oaBu@stanza.co
:LOCATION: Don’t miss out! Clippers tickets still available here.
:STATUS:   CONFIRMED
:END:

Clippers vs. Chiefs Clippers vs. Chiefs

Buy tickets here  https //stza.co/~xzsP

Follow on MiLB First Pitch  https //stza.co/+xzsP-2c

Shop  https //stza.co/+xzsP-29

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Clippers vs. Chiefs
END:VALARM
DTSTART:20180819T200500Z
DTEND:20180819T230500Z
UID:p2gL2Drr9hz3sF7-Qin8oaBu@stanza.co
SUMMARY:Clippers vs. Chiefs
DESCRIPTION:Clippers vs. Chiefs\n\nBuy tickets here: https://stza.co/~xzsP\n\nFollow on MiLB First Pitch: https://stza.co/+xzsP-2c\n\nShop: https://stza.co/+xzsP-29\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don’t miss out! Clippers tickets still available here.
STATUS:CONFIRMED
CREATED:20180213T144516Z
LAST-MODIFIED:20180213T144516Z
TRANSP:OPAQUE
END:VEVENT
* Clippers @ Indians
<2018-08-21 Tue 18:05-21:05>
:PROPERTIES:
:ID:       TUAFC3A4AinZriBk23xHheDx@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Clippers @ Indians Clippers @ Indians

Follow on MiLB First Pitch  https //stza.co/+uWTG-3j

Shop  https //stza.co/+uWTG-1x

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Clippers @ Indians
END:VALARM
DTSTART:20180821T230500Z
DTEND:20180822T020500Z
UID:TUAFC3A4AinZriBk23xHheDx@stanza.co
SUMMARY:Clippers @ Indians
DESCRIPTION:Clippers @ Indians\n\nFollow on MiLB First Pitch: https://stza.co/+uWTG-3j\n\nShop: https://stza.co/+uWTG-1x\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144516Z
LAST-MODIFIED:20180213T144516Z
TRANSP:OPAQUE
END:VEVENT
* Clippers @ Indians
<2018-08-22 Wed 18:05-21:05>
:PROPERTIES:
:ID:       _Wc_ah10brypOg5bB2bzkJTf@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Clippers @ Indians Clippers @ Indians

Follow on MiLB First Pitch  https //stza.co/+uWTS-1x

Shop  https //stza.co/+uWTS-c

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Clippers @ Indians
END:VALARM
DTSTART:20180822T230500Z
DTEND:20180823T020500Z
UID:_Wc_ah10brypOg5bB2bzkJTf@stanza.co
SUMMARY:Clippers @ Indians
DESCRIPTION:Clippers @ Indians\n\nFollow on MiLB First Pitch: https://stza.co/+uWTS-1x\n\nShop: https://stza.co/+uWTS-c\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144516Z
LAST-MODIFIED:20180213T144516Z
TRANSP:OPAQUE
END:VEVENT
* Clippers @ Indians
<2018-08-23 Thu 18:05-21:05>
:PROPERTIES:
:ID:       ppO93cCe3oVwdWn1H6R27VeN@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Clippers @ Indians Clippers @ Indians

Follow on MiLB First Pitch  https //stza.co/+uWU3-2W

Shop  https //stza.co/+uWU3-2O

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Clippers @ Indians
END:VALARM
DTSTART:20180823T230500Z
DTEND:20180824T020500Z
UID:ppO93cCe3oVwdWn1H6R27VeN@stanza.co
SUMMARY:Clippers @ Indians
DESCRIPTION:Clippers @ Indians\n\nFollow on MiLB First Pitch: https://stza.co/+uWU3-2W\n\nShop: https://stza.co/+uWU3-2O\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144516Z
LAST-MODIFIED:20180213T144516Z
TRANSP:OPAQUE
END:VEVENT
* Clippers @ Mud Hens
<2018-08-24 Fri 18:05-21:05>
:PROPERTIES:
:ID:       YjnwoQZiZ0xzxAbLiK3Z-DWq@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Clippers @ Mud Hens Clippers @ Mud Hens

Follow on MiLB First Pitch  https //stza.co/+uX0Q-1y

Shop  https //stza.co/+uX0Q-3L

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Clippers @ Mud Hens
END:VALARM
DTSTART:20180824T230500Z
DTEND:20180825T020500Z
UID:YjnwoQZiZ0xzxAbLiK3Z-DWq@stanza.co
SUMMARY:Clippers @ Mud Hens
DESCRIPTION:Clippers @ Mud Hens\n\nFollow on MiLB First Pitch: https://stza.co/+uX0Q-1y\n\nShop: https://stza.co/+uX0Q-3L\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144516Z
LAST-MODIFIED:20180213T144516Z
TRANSP:OPAQUE
END:VEVENT
* Clippers @ Mud Hens
<2018-08-25 Sat 18:05-21:05>
:PROPERTIES:
:ID:       7mhXMcdqAAXiJoiTl83zzi-v@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Clippers @ Mud Hens Clippers @ Mud Hens

Follow on MiLB First Pitch  https //stza.co/+uX0$-3e

Shop  https //stza.co/+uX0$-1z

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Clippers @ Mud Hens
END:VALARM
DTSTART:20180825T230500Z
DTEND:20180826T020500Z
UID:7mhXMcdqAAXiJoiTl83zzi-v@stanza.co
SUMMARY:Clippers @ Mud Hens
DESCRIPTION:Clippers @ Mud Hens\n\nFollow on MiLB First Pitch: https://stza.co/+uX0$-3e\n\nShop: https://stza.co/+uX0$-1z\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144516Z
LAST-MODIFIED:20180213T144516Z
TRANSP:OPAQUE
END:VEVENT
* Clippers @ Mud Hens
<2018-08-26 Sun 15:05-18:05>
:PROPERTIES:
:ID:       -Xl1J1YfhOupOmohSnmOBX0u@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Clippers @ Mud Hens Clippers @ Mud Hens

Follow on MiLB First Pitch  https //stza.co/+uX1e-1M

Shop  https //stza.co/+uX1e-2I

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Clippers @ Mud Hens
END:VALARM
DTSTART:20180826T200500Z
DTEND:20180826T230500Z
UID:-Xl1J1YfhOupOmohSnmOBX0u@stanza.co
SUMMARY:Clippers @ Mud Hens
DESCRIPTION:Clippers @ Mud Hens\n\nFollow on MiLB First Pitch: https://stza.co/+uX1e-1M\n\nShop: https://stza.co/+uX1e-2I\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144516Z
LAST-MODIFIED:20180213T144516Z
TRANSP:OPAQUE
END:VEVENT
* Clippers @ Mud Hens
<2018-08-27 Mon 17:35-20:35>
:PROPERTIES:
:ID:       bQIwnvj8ishnwAwUIoVZ5KKY@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Clippers @ Mud Hens Clippers @ Mud Hens

Follow on MiLB First Pitch  https //stza.co/+uX1v-28

Shop  https //stza.co/+uX1v-1Q

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Clippers @ Mud Hens
END:VALARM
DTSTART:20180827T223500Z
DTEND:20180828T013500Z
UID:bQIwnvj8ishnwAwUIoVZ5KKY@stanza.co
SUMMARY:Clippers @ Mud Hens
DESCRIPTION:Clippers @ Mud Hens\n\nFollow on MiLB First Pitch: https://stza.co/+uX1v-28\n\nShop: https://stza.co/+uX1v-1Q\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144516Z
LAST-MODIFIED:20180213T144516Z
TRANSP:OPAQUE
END:VEVENT
* Clippers vs. Bats
<2018-08-28 Tue 17:35-20:35>
:PROPERTIES:
:ID:       WZUz4A6Ov12GUuOZZ9EkdHkx@stanza.co
:LOCATION: Swipe to get tickets for the game tonight. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Clippers vs. Bats Clippers vs. Bats

Buy tickets here  https //stza.co/~uWPm

Follow on MiLB First Pitch  https //stza.co/+uWPm-9

Shop  https //stza.co/+uWPm-1o

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Clippers vs. Bats
END:VALARM
DTSTART:20180828T223500Z
DTEND:20180829T013500Z
UID:WZUz4A6Ov12GUuOZZ9EkdHkx@stanza.co
SUMMARY:Clippers vs. Bats
DESCRIPTION:Clippers vs. Bats\n\nBuy tickets here: https://stza.co/~uWPm\n\nFollow on MiLB First Pitch: https://stza.co/+uWPm-9\n\nShop: https://stza.co/+uWPm-1o\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Swipe to get tickets for the game tonight. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144516Z
LAST-MODIFIED:20180213T144516Z
TRANSP:OPAQUE
END:VEVENT
* Clippers vs. Bats
<2018-08-29 Wed 17:35-20:35>
:PROPERTIES:
:ID:       HrxlVe_F0_2mq7SzTGn7gf-j@stanza.co
:LOCATION: Swipe for last minute tickets for tonight's game. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Clippers vs. Bats Clippers vs. Bats

Buy tickets here  https //stza.co/~uWPq

Follow on MiLB First Pitch  https //stza.co/+uWPq-2N

Shop  https //stza.co/+uWPq-2H

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Clippers vs. Bats
END:VALARM
DTSTART:20180829T223500Z
DTEND:20180830T013500Z
UID:HrxlVe_F0_2mq7SzTGn7gf-j@stanza.co
SUMMARY:Clippers vs. Bats
DESCRIPTION:Clippers vs. Bats\n\nBuy tickets here: https://stza.co/~uWPq\n\nFollow on MiLB First Pitch: https://stza.co/+uWPq-2N\n\nShop: https://stza.co/+uWPq-2H\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Swipe for last minute tickets for tonight's game. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144516Z
LAST-MODIFIED:20180213T144516Z
TRANSP:OPAQUE
END:VEVENT
* Clippers vs. Bats
<2018-08-30 Thu 17:35-20:35>
:PROPERTIES:
:ID:       zpnYN5YMLgIgakw6MQQCPp0o@stanza.co
:LOCATION: Ready for the game? Swipe for tickets and more information.
:STATUS:   CONFIRMED
:END:

Clippers vs. Bats Clippers vs. Bats

Buy tickets here  https //stza.co/~uWPw

Follow on MiLB First Pitch  https //stza.co/+uWPw-e

Shop  https //stza.co/+uWPw-1x

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Clippers vs. Bats
END:VALARM
DTSTART:20180830T223500Z
DTEND:20180831T013500Z
UID:zpnYN5YMLgIgakw6MQQCPp0o@stanza.co
SUMMARY:Clippers vs. Bats
DESCRIPTION:Clippers vs. Bats\n\nBuy tickets here: https://stza.co/~uWPw\n\nFollow on MiLB First Pitch: https://stza.co/+uWPw-e\n\nShop: https://stza.co/+uWPw-1x\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Swipe for tickets and more information.
STATUS:CONFIRMED
CREATED:20180213T144516Z
LAST-MODIFIED:20180213T144516Z
TRANSP:OPAQUE
END:VEVENT
* Clippers vs. Mud Hens
<2018-08-31 Fri 18:15-21:15>
:PROPERTIES:
:ID:       TrD3vyCF8LwdK_0vpSYaiNRu@stanza.co
:LOCATION: Looking for something to do tonight? Get tickets here for tonight’s game and view promotions.
:STATUS:   CONFIRMED
:END:

Clippers vs. Mud Hens Clippers vs. Mud Hens

Buy tickets here  https //stza.co/~uWPy

Follow on MiLB First Pitch  https //stza.co/+uWPy-c

Shop  https //stza.co/+uWPy-3p

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Clippers vs. Mud Hens
END:VALARM
DTSTART:20180831T231500Z
DTEND:20180901T021500Z
UID:TrD3vyCF8LwdK_0vpSYaiNRu@stanza.co
SUMMARY:Clippers vs. Mud Hens
DESCRIPTION:Clippers vs. Mud Hens\n\nBuy tickets here: https://stza.co/~uWPy\n\nFollow on MiLB First Pitch: https://stza.co/+uWPy-c\n\nShop: https://stza.co/+uWPy-3p\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Looking for something to do tonight? Get tickets here for tonight’s game and view promotions.
STATUS:CONFIRMED
CREATED:20180213T144516Z
LAST-MODIFIED:20180213T144516Z
TRANSP:OPAQUE
END:VEVENT
* Clippers vs. Mud Hens
<2018-09-01 Sat 18:15-21:15>
:PROPERTIES:
:ID:       QtjpyORG6gbPn2jmf57lV0ss@stanza.co
:LOCATION: Great seats still available for tonight’s game. Purchase them here.
:STATUS:   CONFIRMED
:END:

Clippers vs. Mud Hens Clippers vs. Mud Hens

Buy tickets here  https //stza.co/~uWPF

Follow on MiLB First Pitch  https //stza.co/+uWPF-3P

Shop  https //stza.co/+uWPF-3Q

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Clippers vs. Mud Hens
END:VALARM
DTSTART:20180901T231500Z
DTEND:20180902T021500Z
UID:QtjpyORG6gbPn2jmf57lV0ss@stanza.co
SUMMARY:Clippers vs. Mud Hens
DESCRIPTION:Clippers vs. Mud Hens\n\nBuy tickets here: https://stza.co/~uWPF\n\nFollow on MiLB First Pitch: https://stza.co/+uWPF-3P\n\nShop: https://stza.co/+uWPF-3Q\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Great seats still available for tonight’s game. Purchase them here.
STATUS:CONFIRMED
CREATED:20180213T144516Z
LAST-MODIFIED:20180213T144516Z
TRANSP:OPAQUE
END:VEVENT
* Clippers vs. Mud Hens
<2018-09-02 Sun 15:05-18:05>
:PROPERTIES:
:ID:       zwrB3k1zcipPaILkS6Cg13xg@stanza.co
:LOCATION: Need something fun to do tonight? Get Clippers tickets here.
:STATUS:   CONFIRMED
:END:

Clippers vs. Mud Hens Clippers vs. Mud Hens

Buy tickets here  https //stza.co/~uWPL

Follow on MiLB First Pitch  https //stza.co/+uWPL-26

Shop  https //stza.co/+uWPL-2I

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Clippers vs. Mud Hens
END:VALARM
DTSTART:20180902T200500Z
DTEND:20180902T230500Z
UID:zwrB3k1zcipPaILkS6Cg13xg@stanza.co
SUMMARY:Clippers vs. Mud Hens
DESCRIPTION:Clippers vs. Mud Hens\n\nBuy tickets here: https://stza.co/~uWPL\n\nFollow on MiLB First Pitch: https://stza.co/+uWPL-26\n\nShop: https://stza.co/+uWPL-2I\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Need something fun to do tonight? Get Clippers tickets here.
STATUS:CONFIRMED
CREATED:20180213T144516Z
LAST-MODIFIED:20180213T144516Z
TRANSP:OPAQUE
END:VEVENT
* Clippers vs. Mud Hens
<2018-09-03 Mon 13:05-16:05>
:PROPERTIES:
:ID:       gE2dx3y8STgWIBpQA-QNbedz@stanza.co
:LOCATION: Don’t miss out! Clippers tickets still available here.
:STATUS:   CONFIRMED
:END:

Clippers vs. Mud Hens Clippers vs. Mud Hens

Buy tickets here  https //stza.co/~uWPQ

Follow on MiLB First Pitch  https //stza.co/+uWPQ-w

Shop  https //stza.co/+uWPQ-1A

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Clippers vs. Mud Hens
END:VALARM
DTSTART:20180903T180500Z
DTEND:20180903T210500Z
UID:gE2dx3y8STgWIBpQA-QNbedz@stanza.co
SUMMARY:Clippers vs. Mud Hens
DESCRIPTION:Clippers vs. Mud Hens\n\nBuy tickets here: https://stza.co/~uWPQ\n\nFollow on MiLB First Pitch: https://stza.co/+uWPQ-w\n\nShop: https://stza.co/+uWPQ-1A\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don’t miss out! Clippers tickets still available here.
STATUS:CONFIRMED
CREATED:20180213T144516Z
LAST-MODIFIED:20180213T144516Z
TRANSP:OPAQUE
END:VEVENT
