#+TITLE:       Main Google calendar entries
#+AUTHOR:      Eric S Fraga
#+EMAIL:       e.fraga@ucl.ac.uk
#+DESCRIPTION: converted using the ical2org awk script
#+CATEGORY:    google
#+STARTUP:     hidestars
#+STARTUP:     overview

* COMMENT original iCal preamble

* GreenJackets @ Fireflies
<2018-04-05 Thu 18:05-21:05>
:PROPERTIES:
:ID:       M38S-nu6bRJtJjyMVdCvD7JN@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

GreenJackets @ Fireflies GreenJackets @ Fireflies

Follow on MiLB First Pitch  https //stza.co/+xAUT-2i

Shop  https //stza.co/+xAUT-r

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:GreenJackets @ Fireflies
END:VALARM
DTSTART:20180405T230500Z
DTEND:20180406T020500Z
UID:M38S-nu6bRJtJjyMVdCvD7JN@stanza.co
SUMMARY:GreenJackets @ Fireflies
DESCRIPTION:GreenJackets @ Fireflies\n\nFollow on MiLB First Pitch: https://stza.co/+xAUT-2i\n\nShop: https://stza.co/+xAUT-r\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144503Z
LAST-MODIFIED:20180213T144503Z
TRANSP:OPAQUE
END:VEVENT
* GreenJackets @ Fireflies
<2018-04-06 Fri 18:05-21:05>
:PROPERTIES:
:ID:       hfL5BZ6Yf5qBykehCZ1qHpqp@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

GreenJackets @ Fireflies GreenJackets @ Fireflies

Follow on MiLB First Pitch  https //stza.co/+xAUW-36

Shop  https //stza.co/+xAUW-3N

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:GreenJackets @ Fireflies
END:VALARM
DTSTART:20180406T230500Z
DTEND:20180407T020500Z
UID:hfL5BZ6Yf5qBykehCZ1qHpqp@stanza.co
SUMMARY:GreenJackets @ Fireflies
DESCRIPTION:GreenJackets @ Fireflies\n\nFollow on MiLB First Pitch: https://stza.co/+xAUW-36\n\nShop: https://stza.co/+xAUW-3N\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144503Z
LAST-MODIFIED:20180213T144503Z
TRANSP:OPAQUE
END:VEVENT
* GreenJackets @ Fireflies
<2018-04-07 Sat 17:05-20:05>
:PROPERTIES:
:ID:       7m4ryM9rQDFpKU1OperKB5Fw@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

GreenJackets @ Fireflies GreenJackets @ Fireflies

Follow on MiLB First Pitch  https //stza.co/+xAUX-37

Shop  https //stza.co/+xAUX-9

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:GreenJackets @ Fireflies
END:VALARM
DTSTART:20180407T220500Z
DTEND:20180408T010500Z
UID:7m4ryM9rQDFpKU1OperKB5Fw@stanza.co
SUMMARY:GreenJackets @ Fireflies
DESCRIPTION:GreenJackets @ Fireflies\n\nFollow on MiLB First Pitch: https://stza.co/+xAUX-37\n\nShop: https://stza.co/+xAUX-9\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144503Z
LAST-MODIFIED:20180213T144503Z
TRANSP:OPAQUE
END:VEVENT
* GreenJackets @ Fireflies
<2018-04-08 Sun 13:05-16:05>
:PROPERTIES:
:ID:       cQaaANxQWlQiv2sCMy77kP-y@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

GreenJackets @ Fireflies GreenJackets @ Fireflies

Follow on MiLB First Pitch  https //stza.co/+xAUY-t

Shop  https //stza.co/+xAUY-i

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:GreenJackets @ Fireflies
END:VALARM
DTSTART:20180408T180500Z
DTEND:20180408T210500Z
UID:cQaaANxQWlQiv2sCMy77kP-y@stanza.co
SUMMARY:GreenJackets @ Fireflies
DESCRIPTION:GreenJackets @ Fireflies\n\nFollow on MiLB First Pitch: https://stza.co/+xAUY-t\n\nShop: https://stza.co/+xAUY-i\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144503Z
LAST-MODIFIED:20180213T144503Z
TRANSP:OPAQUE
END:VEVENT
* GreenJackets @ Grasshoppers
<2018-04-09 Mon 18:00-21:00>
:PROPERTIES:
:ID:       HXsGmv2dQ86CiUr1xVAvAKGG@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

GreenJackets @ Grasshoppers GreenJackets @ Grasshoppers

Follow on MiLB First Pitch  https //stza.co/+wgmA-2J

Shop  https //stza.co/+wgmA-15

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:GreenJackets @ Grasshoppers
END:VALARM
DTSTART:20180409T230000Z
DTEND:20180410T020000Z
UID:HXsGmv2dQ86CiUr1xVAvAKGG@stanza.co
SUMMARY:GreenJackets @ Grasshoppers
DESCRIPTION:GreenJackets @ Grasshoppers\n\nFollow on MiLB First Pitch: https://stza.co/+wgmA-2J\n\nShop: https://stza.co/+wgmA-15\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144503Z
LAST-MODIFIED:20180213T144503Z
TRANSP:OPAQUE
END:VEVENT
* GreenJackets @ Grasshoppers
<2018-04-10 Tue 18:00-21:00>
:PROPERTIES:
:ID:       v9p0xT39abp1Zrwsm4UNrM7b@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

GreenJackets @ Grasshoppers GreenJackets @ Grasshoppers

Follow on MiLB First Pitch  https //stza.co/+wgmB-1A

Shop  https //stza.co/+wgmB-30

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:GreenJackets @ Grasshoppers
END:VALARM
DTSTART:20180410T230000Z
DTEND:20180411T020000Z
UID:v9p0xT39abp1Zrwsm4UNrM7b@stanza.co
SUMMARY:GreenJackets @ Grasshoppers
DESCRIPTION:GreenJackets @ Grasshoppers\n\nFollow on MiLB First Pitch: https://stza.co/+wgmB-1A\n\nShop: https://stza.co/+wgmB-30\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144503Z
LAST-MODIFIED:20180213T144503Z
TRANSP:OPAQUE
END:VEVENT
* GreenJackets @ Grasshoppers
<2018-04-11 Wed 09:45-12:45>
:PROPERTIES:
:ID:       QpPhLs_wCon8fx0-1pcYuO0a@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

GreenJackets @ Grasshoppers GreenJackets @ Grasshoppers

Follow on MiLB First Pitch  https //stza.co/+wgmC-3x

Shop  https //stza.co/+wgmC-2F

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:GreenJackets @ Grasshoppers
END:VALARM
DTSTART:20180411T144500Z
DTEND:20180411T174500Z
UID:QpPhLs_wCon8fx0-1pcYuO0a@stanza.co
SUMMARY:GreenJackets @ Grasshoppers
DESCRIPTION:GreenJackets @ Grasshoppers\n\nFollow on MiLB First Pitch: https://stza.co/+wgmC-3x\n\nShop: https://stza.co/+wgmC-2F\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144503Z
LAST-MODIFIED:20180213T144503Z
TRANSP:OPAQUE
END:VEVENT
* GreenJackets vs. Legends
<2018-04-12 Thu 18:35-21:35>
:PROPERTIES:
:ID:       kOmCNME1_8G2904MQyBYOclH@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

GreenJackets vs. Legends GreenJackets vs. Legends

Follow on MiLB First Pitch  https //stza.co/+xBFL-g

Shop  https //stza.co/+xBFL-3m

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:GreenJackets vs. Legends
END:VALARM
DTSTART:20180412T233500Z
DTEND:20180413T023500Z
UID:kOmCNME1_8G2904MQyBYOclH@stanza.co
SUMMARY:GreenJackets vs. Legends
DESCRIPTION:GreenJackets vs. Legends\n\nFollow on MiLB First Pitch: https://stza.co/+xBFL-g\n\nShop: https://stza.co/+xBFL-3m\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144503Z
LAST-MODIFIED:20180213T144503Z
TRANSP:OPAQUE
END:VEVENT
* GreenJackets vs. Legends
<2018-04-13 Fri 18:05-21:05>
:PROPERTIES:
:ID:       RQMOe4u338cIjdGEjfAi9yyy@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

GreenJackets vs. Legends GreenJackets vs. Legends

Follow on MiLB First Pitch  https //stza.co/+xBFN-P

Shop  https //stza.co/+xBFN-1y

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:GreenJackets vs. Legends
END:VALARM
DTSTART:20180413T230500Z
DTEND:20180414T020500Z
UID:RQMOe4u338cIjdGEjfAi9yyy@stanza.co
SUMMARY:GreenJackets vs. Legends
DESCRIPTION:GreenJackets vs. Legends\n\nFollow on MiLB First Pitch: https://stza.co/+xBFN-P\n\nShop: https://stza.co/+xBFN-1y\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144503Z
LAST-MODIFIED:20180213T144503Z
TRANSP:OPAQUE
END:VEVENT
* GreenJackets vs. Legends
<2018-04-14 Sat 17:05-20:05>
:PROPERTIES:
:ID:       cc7GnnsNmOyaOeWSnI0KNz2t@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

GreenJackets vs. Legends GreenJackets vs. Legends

Follow on MiLB First Pitch  https //stza.co/+xBFR-m

Shop  https //stza.co/+xBFR-2N

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:GreenJackets vs. Legends
END:VALARM
DTSTART:20180414T220500Z
DTEND:20180415T010500Z
UID:cc7GnnsNmOyaOeWSnI0KNz2t@stanza.co
SUMMARY:GreenJackets vs. Legends
DESCRIPTION:GreenJackets vs. Legends\n\nFollow on MiLB First Pitch: https://stza.co/+xBFR-m\n\nShop: https://stza.co/+xBFR-2N\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144503Z
LAST-MODIFIED:20180213T144503Z
TRANSP:OPAQUE
END:VEVENT
* GreenJackets vs. Legends
<2018-04-15 Sun 13:05-16:05>
:PROPERTIES:
:ID:       qNn0un8s5ep028vg0Gc2IMxb@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

GreenJackets vs. Legends GreenJackets vs. Legends

Follow on MiLB First Pitch  https //stza.co/+xBFT-2M

Shop  https //stza.co/+xBFT-1j

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:GreenJackets vs. Legends
END:VALARM
DTSTART:20180415T180500Z
DTEND:20180415T210500Z
UID:qNn0un8s5ep028vg0Gc2IMxb@stanza.co
SUMMARY:GreenJackets vs. Legends
DESCRIPTION:GreenJackets vs. Legends\n\nFollow on MiLB First Pitch: https://stza.co/+xBFT-2M\n\nShop: https://stza.co/+xBFT-1j\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144503Z
LAST-MODIFIED:20180213T144503Z
TRANSP:OPAQUE
END:VEVENT
* GreenJackets vs. Intimidators
<2018-04-16 Mon 18:05-21:05>
:PROPERTIES:
:ID:       AeCUwOitPrEyjFFNl0cjRswG@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

GreenJackets vs. Intimidators GreenJackets vs. Intimidators

Follow on MiLB First Pitch  https //stza.co/+xBFU-2N

Shop  https //stza.co/+xBFU-1S

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:GreenJackets vs. Intimidators
END:VALARM
DTSTART:20180416T230500Z
DTEND:20180417T020500Z
UID:AeCUwOitPrEyjFFNl0cjRswG@stanza.co
SUMMARY:GreenJackets vs. Intimidators
DESCRIPTION:GreenJackets vs. Intimidators\n\nFollow on MiLB First Pitch: https://stza.co/+xBFU-2N\n\nShop: https://stza.co/+xBFU-1S\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144503Z
LAST-MODIFIED:20180213T144503Z
TRANSP:OPAQUE
END:VEVENT
* GreenJackets vs. Intimidators
<2018-04-17 Tue 18:05-21:05>
:PROPERTIES:
:ID:       QCwOiXtDRzYGOXnw5S1r27GB@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

GreenJackets vs. Intimidators GreenJackets vs. Intimidators

Follow on MiLB First Pitch  https //stza.co/+xBFX-3L

Shop  https //stza.co/+xBFX-16

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:GreenJackets vs. Intimidators
END:VALARM
DTSTART:20180417T230500Z
DTEND:20180418T020500Z
UID:QCwOiXtDRzYGOXnw5S1r27GB@stanza.co
SUMMARY:GreenJackets vs. Intimidators
DESCRIPTION:GreenJackets vs. Intimidators\n\nFollow on MiLB First Pitch: https://stza.co/+xBFX-3L\n\nShop: https://stza.co/+xBFX-16\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144503Z
LAST-MODIFIED:20180213T144503Z
TRANSP:OPAQUE
END:VEVENT
* GreenJackets vs. Intimidators
<2018-04-18 Wed 09:35-12:35>
:PROPERTIES:
:ID:       YBX8jaiJUriE8pQDbnWpKdsP@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

GreenJackets vs. Intimidators GreenJackets vs. Intimidators

Follow on MiLB First Pitch  https //stza.co/+xBF_-1U

Shop  https //stza.co/+xBF_-t

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:GreenJackets vs. Intimidators
END:VALARM
DTSTART:20180418T143500Z
DTEND:20180418T173500Z
UID:YBX8jaiJUriE8pQDbnWpKdsP@stanza.co
SUMMARY:GreenJackets vs. Intimidators
DESCRIPTION:GreenJackets vs. Intimidators\n\nFollow on MiLB First Pitch: https://stza.co/+xBF_-1U\n\nShop: https://stza.co/+xBF_-t\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144503Z
LAST-MODIFIED:20180213T144503Z
TRANSP:OPAQUE
END:VEVENT
* GreenJackets @ Braves
<2018-04-19 Thu 18:00-21:00>
:PROPERTIES:
:ID:       Ij3gpYG92XMABNZPlMsE6tp3@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

GreenJackets @ Braves GreenJackets @ Braves

Follow on MiLB First Pitch  https //stza.co/+vNyW-22

Shop  https //stza.co/+vNyW-1U

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:GreenJackets @ Braves
END:VALARM
DTSTART:20180419T230000Z
DTEND:20180420T020000Z
UID:Ij3gpYG92XMABNZPlMsE6tp3@stanza.co
SUMMARY:GreenJackets @ Braves
DESCRIPTION:GreenJackets @ Braves\n\nFollow on MiLB First Pitch: https://stza.co/+vNyW-22\n\nShop: https://stza.co/+vNyW-1U\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144503Z
LAST-MODIFIED:20180213T144503Z
TRANSP:OPAQUE
END:VEVENT
* GreenJackets @ Braves
<2018-04-20 Fri 18:00-21:00>
:PROPERTIES:
:ID:       vs3xzY-_QBGhRwY5QQ_jCOn2@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

GreenJackets @ Braves GreenJackets @ Braves

Follow on MiLB First Pitch  https //stza.co/+vNyX-T

Shop  https //stza.co/+vNyX-2t

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:GreenJackets @ Braves
END:VALARM
DTSTART:20180420T230000Z
DTEND:20180421T020000Z
UID:vs3xzY-_QBGhRwY5QQ_jCOn2@stanza.co
SUMMARY:GreenJackets @ Braves
DESCRIPTION:GreenJackets @ Braves\n\nFollow on MiLB First Pitch: https://stza.co/+vNyX-T\n\nShop: https://stza.co/+vNyX-2t\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144503Z
LAST-MODIFIED:20180213T144503Z
TRANSP:OPAQUE
END:VEVENT
* GreenJackets @ Braves
<2018-04-21 Sat 17:00-20:00>
:PROPERTIES:
:ID:       DJqEC4PPbSUCmI1FBNg1Dxy3@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

GreenJackets @ Braves GreenJackets @ Braves

Follow on MiLB First Pitch  https //stza.co/+vNyY-3x

Shop  https //stza.co/+vNyY-2g

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:GreenJackets @ Braves
END:VALARM
DTSTART:20180421T220000Z
DTEND:20180422T010000Z
UID:DJqEC4PPbSUCmI1FBNg1Dxy3@stanza.co
SUMMARY:GreenJackets @ Braves
DESCRIPTION:GreenJackets @ Braves\n\nFollow on MiLB First Pitch: https://stza.co/+vNyY-3x\n\nShop: https://stza.co/+vNyY-2g\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144503Z
LAST-MODIFIED:20180213T144503Z
TRANSP:OPAQUE
END:VEVENT
* GreenJackets @ Braves
<2018-04-22 Sun 13:00-16:00>
:PROPERTIES:
:ID:       gEN8lDGvtkajWycDuP80UURs@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

GreenJackets @ Braves GreenJackets @ Braves

Follow on MiLB First Pitch  https //stza.co/+vNyZ-1o

Shop  https //stza.co/+vNyZ-12

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:GreenJackets @ Braves
END:VALARM
DTSTART:20180422T180000Z
DTEND:20180422T210000Z
UID:gEN8lDGvtkajWycDuP80UURs@stanza.co
SUMMARY:GreenJackets @ Braves
DESCRIPTION:GreenJackets @ Braves\n\nFollow on MiLB First Pitch: https://stza.co/+vNyZ-1o\n\nShop: https://stza.co/+vNyZ-12\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144503Z
LAST-MODIFIED:20180213T144503Z
TRANSP:OPAQUE
END:VEVENT
* GreenJackets @ Drive
<2018-04-23 Mon 18:05-21:05>
:PROPERTIES:
:ID:       pTLqs0KL_Ih0hb3gpopwQGyg@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

GreenJackets @ Drive GreenJackets @ Drive

Follow on MiLB First Pitch  https //stza.co/+xEZm-g

Shop  https //stza.co/+xEZm-2Q

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:GreenJackets @ Drive
END:VALARM
DTSTART:20180423T230500Z
DTEND:20180424T020500Z
UID:pTLqs0KL_Ih0hb3gpopwQGyg@stanza.co
SUMMARY:GreenJackets @ Drive
DESCRIPTION:GreenJackets @ Drive\n\nFollow on MiLB First Pitch: https://stza.co/+xEZm-g\n\nShop: https://stza.co/+xEZm-2Q\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144503Z
LAST-MODIFIED:20180213T144503Z
TRANSP:OPAQUE
END:VEVENT
* GreenJackets @ Drive
<2018-04-24 Tue 13:05-16:05>
:PROPERTIES:
:ID:       MQmw196rntFd1jxRCm47hCMD@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

GreenJackets @ Drive GreenJackets @ Drive

Follow on MiLB First Pitch  https //stza.co/+xEZn-3G

Shop  https //stza.co/+xEZn-$

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:GreenJackets @ Drive
END:VALARM
DTSTART:20180424T180500Z
DTEND:20180424T210500Z
UID:MQmw196rntFd1jxRCm47hCMD@stanza.co
SUMMARY:GreenJackets @ Drive
DESCRIPTION:GreenJackets @ Drive\n\nFollow on MiLB First Pitch: https://stza.co/+xEZn-3G\n\nShop: https://stza.co/+xEZn-$\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144503Z
LAST-MODIFIED:20180213T144503Z
TRANSP:OPAQUE
END:VEVENT
* GreenJackets @ Drive
<2018-04-25 Wed 18:05-21:05>
:PROPERTIES:
:ID:       zT0a3qt4Lc4V-nwRQmgU1toj@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

GreenJackets @ Drive GreenJackets @ Drive

Follow on MiLB First Pitch  https //stza.co/+xEZo-2r

Shop  https //stza.co/+xEZo-2F

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:GreenJackets @ Drive
END:VALARM
DTSTART:20180425T230500Z
DTEND:20180426T020500Z
UID:zT0a3qt4Lc4V-nwRQmgU1toj@stanza.co
SUMMARY:GreenJackets @ Drive
DESCRIPTION:GreenJackets @ Drive\n\nFollow on MiLB First Pitch: https://stza.co/+xEZo-2r\n\nShop: https://stza.co/+xEZo-2F\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144503Z
LAST-MODIFIED:20180213T144503Z
TRANSP:OPAQUE
END:VEVENT
* GreenJackets @ Drive
<2018-04-26 Thu 18:05-21:05>
:PROPERTIES:
:ID:       Sy5kB1n3tHOXn8hncLlRx84q@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

GreenJackets @ Drive GreenJackets @ Drive

Follow on MiLB First Pitch  https //stza.co/+xEZp-Z

Shop  https //stza.co/+xEZp-2u

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:GreenJackets @ Drive
END:VALARM
DTSTART:20180426T230500Z
DTEND:20180427T020500Z
UID:Sy5kB1n3tHOXn8hncLlRx84q@stanza.co
SUMMARY:GreenJackets @ Drive
DESCRIPTION:GreenJackets @ Drive\n\nFollow on MiLB First Pitch: https://stza.co/+xEZp-Z\n\nShop: https://stza.co/+xEZp-2u\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144503Z
LAST-MODIFIED:20180213T144503Z
TRANSP:OPAQUE
END:VEVENT
* GreenJackets vs. Fireflies
<2018-04-27 Fri 18:05-21:05>
:PROPERTIES:
:ID:       R0mCVUuOM60MPhtqwqcfYqta@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

GreenJackets vs. Fireflies GreenJackets vs. Fireflies

Follow on MiLB First Pitch  https //stza.co/+xBG1-H

Shop  https //stza.co/+xBG1-1n

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:GreenJackets vs. Fireflies
END:VALARM
DTSTART:20180427T230500Z
DTEND:20180428T020500Z
UID:R0mCVUuOM60MPhtqwqcfYqta@stanza.co
SUMMARY:GreenJackets vs. Fireflies
DESCRIPTION:GreenJackets vs. Fireflies\n\nFollow on MiLB First Pitch: https://stza.co/+xBG1-H\n\nShop: https://stza.co/+xBG1-1n\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144503Z
LAST-MODIFIED:20180213T144503Z
TRANSP:OPAQUE
END:VEVENT
* GreenJackets vs. Fireflies
<2018-04-28 Sat 17:05-20:05>
:PROPERTIES:
:ID:       17Z2-KRZinlPo4D3YcY592Mh@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

GreenJackets vs. Fireflies GreenJackets vs. Fireflies

Follow on MiLB First Pitch  https //stza.co/+xBG4-A

Shop  https //stza.co/+xBG4-Z

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:GreenJackets vs. Fireflies
END:VALARM
DTSTART:20180428T220500Z
DTEND:20180429T010500Z
UID:17Z2-KRZinlPo4D3YcY592Mh@stanza.co
SUMMARY:GreenJackets vs. Fireflies
DESCRIPTION:GreenJackets vs. Fireflies\n\nFollow on MiLB First Pitch: https://stza.co/+xBG4-A\n\nShop: https://stza.co/+xBG4-Z\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144503Z
LAST-MODIFIED:20180213T144503Z
TRANSP:OPAQUE
END:VEVENT
* GreenJackets vs. Fireflies
<2018-04-29 Sun 13:05-16:05>
:PROPERTIES:
:ID:       0cviNt94XqFn1ZXM8eMZoKP5@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

GreenJackets vs. Fireflies GreenJackets vs. Fireflies

Follow on MiLB First Pitch  https //stza.co/+xBG7-T

Shop  https //stza.co/+xBG7-23

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:GreenJackets vs. Fireflies
END:VALARM
DTSTART:20180429T180500Z
DTEND:20180429T210500Z
UID:0cviNt94XqFn1ZXM8eMZoKP5@stanza.co
SUMMARY:GreenJackets vs. Fireflies
DESCRIPTION:GreenJackets vs. Fireflies\n\nFollow on MiLB First Pitch: https://stza.co/+xBG7-T\n\nShop: https://stza.co/+xBG7-23\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144503Z
LAST-MODIFIED:20180213T144503Z
TRANSP:OPAQUE
END:VEVENT
* GreenJackets @ Power
<2018-05-01 Tue 18:05-21:05>
:PROPERTIES:
:ID:       i_tpKVH03U-G8YJsfP6BqLgQ@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

GreenJackets @ Power GreenJackets @ Power

Follow on MiLB First Pitch  https //stza.co/+xJ3r-A

Shop  https //stza.co/+xJ3r-3C

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:GreenJackets @ Power
END:VALARM
DTSTART:20180501T230500Z
DTEND:20180502T020500Z
UID:i_tpKVH03U-G8YJsfP6BqLgQ@stanza.co
SUMMARY:GreenJackets @ Power
DESCRIPTION:GreenJackets @ Power\n\nFollow on MiLB First Pitch: https://stza.co/+xJ3r-A\n\nShop: https://stza.co/+xJ3r-3C\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144503Z
LAST-MODIFIED:20180213T144503Z
TRANSP:OPAQUE
END:VEVENT
* GreenJackets @ Power
<2018-05-02 Wed 18:05-21:05>
:PROPERTIES:
:ID:       fSjopwVA9leW95A9mls1hHFe@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

GreenJackets @ Power GreenJackets @ Power

Follow on MiLB First Pitch  https //stza.co/+xJ3s-3x

Shop  https //stza.co/+xJ3s-2f

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:GreenJackets @ Power
END:VALARM
DTSTART:20180502T230500Z
DTEND:20180503T020500Z
UID:fSjopwVA9leW95A9mls1hHFe@stanza.co
SUMMARY:GreenJackets @ Power
DESCRIPTION:GreenJackets @ Power\n\nFollow on MiLB First Pitch: https://stza.co/+xJ3s-3x\n\nShop: https://stza.co/+xJ3s-2f\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144503Z
LAST-MODIFIED:20180213T144503Z
TRANSP:OPAQUE
END:VEVENT
* GreenJackets @ Power
<2018-05-03 Thu 18:05-21:05>
:PROPERTIES:
:ID:       Xsq-zMXKwXLHiqo96RX35Yxy@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

GreenJackets @ Power GreenJackets @ Power

Follow on MiLB First Pitch  https //stza.co/+xJ3t-U

Shop  https //stza.co/+xJ3t-1B

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:GreenJackets @ Power
END:VALARM
DTSTART:20180503T230500Z
DTEND:20180504T020500Z
UID:Xsq-zMXKwXLHiqo96RX35Yxy@stanza.co
SUMMARY:GreenJackets @ Power
DESCRIPTION:GreenJackets @ Power\n\nFollow on MiLB First Pitch: https://stza.co/+xJ3t-U\n\nShop: https://stza.co/+xJ3t-1B\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144503Z
LAST-MODIFIED:20180213T144503Z
TRANSP:OPAQUE
END:VEVENT
* GreenJackets @ Shorebirds
<2018-05-04 Fri 18:05-21:05>
:PROPERTIES:
:ID:       KQZg80lrYm0j-mNScC4u_l7j@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

GreenJackets @ Shorebirds GreenJackets @ Shorebirds

Follow on MiLB First Pitch  https //stza.co/+wHLo-c

Shop  https //stza.co/+wHLo-3b

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:GreenJackets @ Shorebirds
END:VALARM
DTSTART:20180504T230500Z
DTEND:20180505T020500Z
UID:KQZg80lrYm0j-mNScC4u_l7j@stanza.co
SUMMARY:GreenJackets @ Shorebirds
DESCRIPTION:GreenJackets @ Shorebirds\n\nFollow on MiLB First Pitch: https://stza.co/+wHLo-c\n\nShop: https://stza.co/+wHLo-3b\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144503Z
LAST-MODIFIED:20180213T144503Z
TRANSP:OPAQUE
END:VEVENT
* GreenJackets @ Shorebirds
<2018-05-05 Sat 18:05-21:05>
:PROPERTIES:
:ID:       Z53-bKOsc4OX1KITHWx8fwST@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

GreenJackets @ Shorebirds GreenJackets @ Shorebirds

Follow on MiLB First Pitch  https //stza.co/+wHLr-3N

Shop  https //stza.co/+wHLr-3A

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:GreenJackets @ Shorebirds
END:VALARM
DTSTART:20180505T230500Z
DTEND:20180506T020500Z
UID:Z53-bKOsc4OX1KITHWx8fwST@stanza.co
SUMMARY:GreenJackets @ Shorebirds
DESCRIPTION:GreenJackets @ Shorebirds\n\nFollow on MiLB First Pitch: https://stza.co/+wHLr-3N\n\nShop: https://stza.co/+wHLr-3A\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144503Z
LAST-MODIFIED:20180213T144503Z
TRANSP:OPAQUE
END:VEVENT
* GreenJackets @ Shorebirds
<2018-05-06 Sun 13:05-16:05>
:PROPERTIES:
:ID:       JZX-xcBPkncWQwiFGsOScxqA@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

GreenJackets @ Shorebirds GreenJackets @ Shorebirds

Follow on MiLB First Pitch  https //stza.co/+wHFX-1y

Shop  https //stza.co/+wHFX-y

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:GreenJackets @ Shorebirds
END:VALARM
DTSTART:20180506T180500Z
DTEND:20180506T210500Z
UID:JZX-xcBPkncWQwiFGsOScxqA@stanza.co
SUMMARY:GreenJackets @ Shorebirds
DESCRIPTION:GreenJackets @ Shorebirds\n\nFollow on MiLB First Pitch: https://stza.co/+wHFX-1y\n\nShop: https://stza.co/+wHFX-y\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144503Z
LAST-MODIFIED:20180213T144503Z
TRANSP:OPAQUE
END:VEVENT
* GreenJackets @ Shorebirds
<2018-05-07 Mon 18:05-21:05>
:PROPERTIES:
:ID:       C9LCrs71R5frFNVyO3cRzPjM@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

GreenJackets @ Shorebirds GreenJackets @ Shorebirds

Follow on MiLB First Pitch  https //stza.co/+wHFY-3I

Shop  https //stza.co/+wHFY-W

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:GreenJackets @ Shorebirds
END:VALARM
DTSTART:20180507T230500Z
DTEND:20180508T020500Z
UID:C9LCrs71R5frFNVyO3cRzPjM@stanza.co
SUMMARY:GreenJackets @ Shorebirds
DESCRIPTION:GreenJackets @ Shorebirds\n\nFollow on MiLB First Pitch: https://stza.co/+wHFY-3I\n\nShop: https://stza.co/+wHFY-W\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144503Z
LAST-MODIFIED:20180213T144503Z
TRANSP:OPAQUE
END:VEVENT
* GreenJackets vs. Braves
<2018-05-09 Wed 18:05-21:05>
:PROPERTIES:
:ID:       rTiGC8skUVelg-DWOcqm-kx_@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

GreenJackets vs. Braves GreenJackets vs. Braves

Follow on MiLB First Pitch  https //stza.co/+xBGa-2b

Shop  https //stza.co/+xBGa-2$

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:GreenJackets vs. Braves
END:VALARM
DTSTART:20180509T230500Z
DTEND:20180510T020500Z
UID:rTiGC8skUVelg-DWOcqm-kx_@stanza.co
SUMMARY:GreenJackets vs. Braves
DESCRIPTION:GreenJackets vs. Braves\n\nFollow on MiLB First Pitch: https://stza.co/+xBGa-2b\n\nShop: https://stza.co/+xBGa-2$\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144503Z
LAST-MODIFIED:20180213T144503Z
TRANSP:OPAQUE
END:VEVENT
* GreenJackets vs. Braves
<2018-05-10 Thu 18:05-21:05>
:PROPERTIES:
:ID:       HSz7apWbIDFpQ3jVDEcqpYaK@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

GreenJackets vs. Braves GreenJackets vs. Braves

Follow on MiLB First Pitch  https //stza.co/+xBGh-2R

Shop  https //stza.co/+xBGh-j

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:GreenJackets vs. Braves
END:VALARM
DTSTART:20180510T230500Z
DTEND:20180511T020500Z
UID:HSz7apWbIDFpQ3jVDEcqpYaK@stanza.co
SUMMARY:GreenJackets vs. Braves
DESCRIPTION:GreenJackets vs. Braves\n\nFollow on MiLB First Pitch: https://stza.co/+xBGh-2R\n\nShop: https://stza.co/+xBGh-j\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144503Z
LAST-MODIFIED:20180213T144503Z
TRANSP:OPAQUE
END:VEVENT
* GreenJackets vs. Braves
<2018-05-11 Fri 18:05-21:05>
:PROPERTIES:
:ID:       H7MGDnhMHRm-49MRsfDtN9JC@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

GreenJackets vs. Braves GreenJackets vs. Braves

Follow on MiLB First Pitch  https //stza.co/+xBGl-2K

Shop  https //stza.co/+xBGl-a

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:GreenJackets vs. Braves
END:VALARM
DTSTART:20180511T230500Z
DTEND:20180512T020500Z
UID:H7MGDnhMHRm-49MRsfDtN9JC@stanza.co
SUMMARY:GreenJackets vs. Braves
DESCRIPTION:GreenJackets vs. Braves\n\nFollow on MiLB First Pitch: https://stza.co/+xBGl-2K\n\nShop: https://stza.co/+xBGl-a\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144503Z
LAST-MODIFIED:20180213T144503Z
TRANSP:OPAQUE
END:VEVENT
* GreenJackets vs. Grasshoppers
<2018-05-12 Sat 17:05-20:05>
:PROPERTIES:
:ID:       FA7htQ5WrVZS3UGyeoglAGR-@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

GreenJackets vs. Grasshoppers GreenJackets vs. Grasshoppers

Follow on MiLB First Pitch  https //stza.co/+xBGq-1o

Shop  https //stza.co/+xBGq-1Q

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:GreenJackets vs. Grasshoppers
END:VALARM
DTSTART:20180512T220500Z
DTEND:20180513T010500Z
UID:FA7htQ5WrVZS3UGyeoglAGR-@stanza.co
SUMMARY:GreenJackets vs. Grasshoppers
DESCRIPTION:GreenJackets vs. Grasshoppers\n\nFollow on MiLB First Pitch: https://stza.co/+xBGq-1o\n\nShop: https://stza.co/+xBGq-1Q\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144503Z
LAST-MODIFIED:20180213T144503Z
TRANSP:OPAQUE
END:VEVENT
* GreenJackets vs. Grasshoppers
<2018-05-13 Sun 13:05-16:05>
:PROPERTIES:
:ID:       ZZL1NOzsZDWgbVYruGQ2I-fl@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

GreenJackets vs. Grasshoppers GreenJackets vs. Grasshoppers

Follow on MiLB First Pitch  https //stza.co/+xBGt-2s

Shop  https //stza.co/+xBGt-B

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:GreenJackets vs. Grasshoppers
END:VALARM
DTSTART:20180513T180500Z
DTEND:20180513T210500Z
UID:ZZL1NOzsZDWgbVYruGQ2I-fl@stanza.co
SUMMARY:GreenJackets vs. Grasshoppers
DESCRIPTION:GreenJackets vs. Grasshoppers\n\nFollow on MiLB First Pitch: https://stza.co/+xBGt-2s\n\nShop: https://stza.co/+xBGt-B\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144503Z
LAST-MODIFIED:20180213T144503Z
TRANSP:OPAQUE
END:VEVENT
* GreenJackets vs. Grasshoppers
<2018-05-14 Mon 18:05-21:05>
:PROPERTIES:
:ID:       7vXJrw2phSgtVgconsYTL_oP@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

GreenJackets vs. Grasshoppers GreenJackets vs. Grasshoppers

Follow on MiLB First Pitch  https //stza.co/+xBGy-1c

Shop  https //stza.co/+xBGy-24

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:GreenJackets vs. Grasshoppers
END:VALARM
DTSTART:20180514T230500Z
DTEND:20180515T020500Z
UID:7vXJrw2phSgtVgconsYTL_oP@stanza.co
SUMMARY:GreenJackets vs. Grasshoppers
DESCRIPTION:GreenJackets vs. Grasshoppers\n\nFollow on MiLB First Pitch: https://stza.co/+xBGy-1c\n\nShop: https://stza.co/+xBGy-24\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144503Z
LAST-MODIFIED:20180213T144503Z
TRANSP:OPAQUE
END:VEVENT
* GreenJackets vs. Grasshoppers
<2018-05-15 Tue 09:35-12:35>
:PROPERTIES:
:ID:       0uJ4TMhh3Ub2fq1uz3Xq3nz3@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

GreenJackets vs. Grasshoppers GreenJackets vs. Grasshoppers

Follow on MiLB First Pitch  https //stza.co/+xBGD-3L

Shop  https //stza.co/+xBGD-2T

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:GreenJackets vs. Grasshoppers
END:VALARM
DTSTART:20180515T143500Z
DTEND:20180515T173500Z
UID:0uJ4TMhh3Ub2fq1uz3Xq3nz3@stanza.co
SUMMARY:GreenJackets vs. Grasshoppers
DESCRIPTION:GreenJackets vs. Grasshoppers\n\nFollow on MiLB First Pitch: https://stza.co/+xBGD-3L\n\nShop: https://stza.co/+xBGD-2T\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144503Z
LAST-MODIFIED:20180213T144503Z
TRANSP:OPAQUE
END:VEVENT
* GreenJackets @ Drive
<2018-05-17 Thu 18:05-21:05>
:PROPERTIES:
:ID:       QM-yCyCAnTiUEwCvy06Nodc8@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

GreenJackets @ Drive GreenJackets @ Drive

Follow on MiLB First Pitch  https //stza.co/+xEZq-16

Shop  https //stza.co/+xEZq-v

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:GreenJackets @ Drive
END:VALARM
DTSTART:20180517T230500Z
DTEND:20180518T020500Z
UID:QM-yCyCAnTiUEwCvy06Nodc8@stanza.co
SUMMARY:GreenJackets @ Drive
DESCRIPTION:GreenJackets @ Drive\n\nFollow on MiLB First Pitch: https://stza.co/+xEZq-16\n\nShop: https://stza.co/+xEZq-v\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144503Z
LAST-MODIFIED:20180213T144503Z
TRANSP:OPAQUE
END:VEVENT
* GreenJackets @ Drive
<2018-05-18 Fri 18:05-21:05>
:PROPERTIES:
:ID:       Ysg8tG7Hz-wxX3Ow0lsRY_AI@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

GreenJackets @ Drive GreenJackets @ Drive

Follow on MiLB First Pitch  https //stza.co/+xEZr-N

Shop  https //stza.co/+xEZr-y

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:GreenJackets @ Drive
END:VALARM
DTSTART:20180518T230500Z
DTEND:20180519T020500Z
UID:Ysg8tG7Hz-wxX3Ow0lsRY_AI@stanza.co
SUMMARY:GreenJackets @ Drive
DESCRIPTION:GreenJackets @ Drive\n\nFollow on MiLB First Pitch: https://stza.co/+xEZr-N\n\nShop: https://stza.co/+xEZr-y\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144503Z
LAST-MODIFIED:20180213T144503Z
TRANSP:OPAQUE
END:VEVENT
* GreenJackets @ Drive
<2018-05-19 Sat 18:05-21:05>
:PROPERTIES:
:ID:       XnWE0sYfnlP6d995DabdxMSW@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

GreenJackets @ Drive GreenJackets @ Drive

Follow on MiLB First Pitch  https //stza.co/+xEZs-3w

Shop  https //stza.co/+xEZs-3E

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:GreenJackets @ Drive
END:VALARM
DTSTART:20180519T230500Z
DTEND:20180520T020500Z
UID:XnWE0sYfnlP6d995DabdxMSW@stanza.co
SUMMARY:GreenJackets @ Drive
DESCRIPTION:GreenJackets @ Drive\n\nFollow on MiLB First Pitch: https://stza.co/+xEZs-3w\n\nShop: https://stza.co/+xEZs-3E\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144503Z
LAST-MODIFIED:20180213T144503Z
TRANSP:OPAQUE
END:VEVENT
* GreenJackets @ Drive
<2018-05-20 Sun 15:05-18:05>
:PROPERTIES:
:ID:       E2ZpYFam2hj2odjS2WTWrM0z@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

GreenJackets @ Drive GreenJackets @ Drive

Follow on MiLB First Pitch  https //stza.co/+xEZt-2N

Shop  https //stza.co/+xEZt-36

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:GreenJackets @ Drive
END:VALARM
DTSTART:20180520T200500Z
DTEND:20180520T230500Z
UID:E2ZpYFam2hj2odjS2WTWrM0z@stanza.co
SUMMARY:GreenJackets @ Drive
DESCRIPTION:GreenJackets @ Drive\n\nFollow on MiLB First Pitch: https://stza.co/+xEZt-2N\n\nShop: https://stza.co/+xEZt-36\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144503Z
LAST-MODIFIED:20180213T144503Z
TRANSP:OPAQUE
END:VEVENT
* GreenJackets vs. RiverDogs
<2018-05-21 Mon 18:05-21:05>
:PROPERTIES:
:ID:       GQbFfmU_LH_NToCWfWKs_zxG@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

GreenJackets vs. RiverDogs GreenJackets vs. RiverDogs

Follow on MiLB First Pitch  https //stza.co/+xBGH-1K

Shop  https //stza.co/+xBGH-2j

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:GreenJackets vs. RiverDogs
END:VALARM
DTSTART:20180521T230500Z
DTEND:20180522T020500Z
UID:GQbFfmU_LH_NToCWfWKs_zxG@stanza.co
SUMMARY:GreenJackets vs. RiverDogs
DESCRIPTION:GreenJackets vs. RiverDogs\n\nFollow on MiLB First Pitch: https://stza.co/+xBGH-1K\n\nShop: https://stza.co/+xBGH-2j\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144503Z
LAST-MODIFIED:20180213T144503Z
TRANSP:OPAQUE
END:VEVENT
* GreenJackets vs. RiverDogs
<2018-05-22 Tue 18:05-21:05>
:PROPERTIES:
:ID:       dtzex8ah8_6HdFKcvo5U681g@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

GreenJackets vs. RiverDogs GreenJackets vs. RiverDogs

Follow on MiLB First Pitch  https //stza.co/+xBGN-7

Shop  https //stza.co/+xBGN-1g

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:GreenJackets vs. RiverDogs
END:VALARM
DTSTART:20180522T230500Z
DTEND:20180523T020500Z
UID:dtzex8ah8_6HdFKcvo5U681g@stanza.co
SUMMARY:GreenJackets vs. RiverDogs
DESCRIPTION:GreenJackets vs. RiverDogs\n\nFollow on MiLB First Pitch: https://stza.co/+xBGN-7\n\nShop: https://stza.co/+xBGN-1g\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144503Z
LAST-MODIFIED:20180213T144503Z
TRANSP:OPAQUE
END:VEVENT
* GreenJackets vs. RiverDogs
<2018-05-23 Wed 18:05-21:05>
:PROPERTIES:
:ID:       2MflnJYEm11qRIxvsQTWIfr8@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

GreenJackets vs. RiverDogs GreenJackets vs. RiverDogs

Follow on MiLB First Pitch  https //stza.co/+xBGS-2M

Shop  https //stza.co/+xBGS-3o

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:GreenJackets vs. RiverDogs
END:VALARM
DTSTART:20180523T230500Z
DTEND:20180524T020500Z
UID:2MflnJYEm11qRIxvsQTWIfr8@stanza.co
SUMMARY:GreenJackets vs. RiverDogs
DESCRIPTION:GreenJackets vs. RiverDogs\n\nFollow on MiLB First Pitch: https://stza.co/+xBGS-2M\n\nShop: https://stza.co/+xBGS-3o\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144503Z
LAST-MODIFIED:20180213T144503Z
TRANSP:OPAQUE
END:VEVENT
* GreenJackets vs. RiverDogs
<2018-05-24 Thu 18:05-21:05>
:PROPERTIES:
:ID:       0cxrwG4hFDy2ObiU5psQgA-1@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

GreenJackets vs. RiverDogs GreenJackets vs. RiverDogs

Follow on MiLB First Pitch  https //stza.co/+xBGW-15

Shop  https //stza.co/+xBGW-3r

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:GreenJackets vs. RiverDogs
END:VALARM
DTSTART:20180524T230500Z
DTEND:20180525T020500Z
UID:0cxrwG4hFDy2ObiU5psQgA-1@stanza.co
SUMMARY:GreenJackets vs. RiverDogs
DESCRIPTION:GreenJackets vs. RiverDogs\n\nFollow on MiLB First Pitch: https://stza.co/+xBGW-15\n\nShop: https://stza.co/+xBGW-3r\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144503Z
LAST-MODIFIED:20180213T144503Z
TRANSP:OPAQUE
END:VEVENT
* GreenJackets vs. Braves
<2018-05-25 Fri 18:05-21:05>
:PROPERTIES:
:ID:       0wv-S7Ki79FX1KMBaAyQwZJR@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

GreenJackets vs. Braves GreenJackets vs. Braves

Follow on MiLB First Pitch  https //stza.co/+xBG_-1v

Shop  https //stza.co/+xBG_-3q

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:GreenJackets vs. Braves
END:VALARM
DTSTART:20180525T230500Z
DTEND:20180526T020500Z
UID:0wv-S7Ki79FX1KMBaAyQwZJR@stanza.co
SUMMARY:GreenJackets vs. Braves
DESCRIPTION:GreenJackets vs. Braves\n\nFollow on MiLB First Pitch: https://stza.co/+xBG_-1v\n\nShop: https://stza.co/+xBG_-3q\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144503Z
LAST-MODIFIED:20180213T144503Z
TRANSP:OPAQUE
END:VEVENT
* GreenJackets vs. Braves
<2018-05-26 Sat 17:05-20:05>
:PROPERTIES:
:ID:       V6H6iON4EhQOh9hl0ivYnPC-@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

GreenJackets vs. Braves GreenJackets vs. Braves

Follow on MiLB First Pitch  https //stza.co/+xBH3-3a

Shop  https //stza.co/+xBH3-18

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:GreenJackets vs. Braves
END:VALARM
DTSTART:20180526T220500Z
DTEND:20180527T010500Z
UID:V6H6iON4EhQOh9hl0ivYnPC-@stanza.co
SUMMARY:GreenJackets vs. Braves
DESCRIPTION:GreenJackets vs. Braves\n\nFollow on MiLB First Pitch: https://stza.co/+xBH3-3a\n\nShop: https://stza.co/+xBH3-18\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144503Z
LAST-MODIFIED:20180213T144503Z
TRANSP:OPAQUE
END:VEVENT
* GreenJackets vs. Braves
<2018-05-27 Sun 17:35-20:35>
:PROPERTIES:
:ID:       OX5NAKSxvuaPzavScZxYnNS-@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

GreenJackets vs. Braves GreenJackets vs. Braves

Follow on MiLB First Pitch  https //stza.co/+xBH7-11

Shop  https //stza.co/+xBH7-3G

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:GreenJackets vs. Braves
END:VALARM
DTSTART:20180527T223500Z
DTEND:20180528T013500Z
UID:OX5NAKSxvuaPzavScZxYnNS-@stanza.co
SUMMARY:GreenJackets vs. Braves
DESCRIPTION:GreenJackets vs. Braves\n\nFollow on MiLB First Pitch: https://stza.co/+xBH7-11\n\nShop: https://stza.co/+xBH7-3G\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144503Z
LAST-MODIFIED:20180213T144503Z
TRANSP:OPAQUE
END:VEVENT
* GreenJackets vs. Braves
<2018-05-28 Mon 13:05-16:05>
:PROPERTIES:
:ID:       bDXTe3IM1zrxkVLkBnBTzSAl@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

GreenJackets vs. Braves GreenJackets vs. Braves

Follow on MiLB First Pitch  https //stza.co/+xBHa-2o

Shop  https //stza.co/+xBHa-3p

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:GreenJackets vs. Braves
END:VALARM
DTSTART:20180528T180500Z
DTEND:20180528T210500Z
UID:bDXTe3IM1zrxkVLkBnBTzSAl@stanza.co
SUMMARY:GreenJackets vs. Braves
DESCRIPTION:GreenJackets vs. Braves\n\nFollow on MiLB First Pitch: https://stza.co/+xBHa-2o\n\nShop: https://stza.co/+xBHa-3p\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144503Z
LAST-MODIFIED:20180213T144503Z
TRANSP:OPAQUE
END:VEVENT
* GreenJackets @ Drive
<2018-05-29 Tue 18:05-21:05>
:PROPERTIES:
:ID:       u046UJ7GTzbhrRpIDlBhhlOe@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

GreenJackets @ Drive GreenJackets @ Drive

Follow on MiLB First Pitch  https //stza.co/+xEZu-13

Shop  https //stza.co/+xEZu-1G

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:GreenJackets @ Drive
END:VALARM
DTSTART:20180529T230500Z
DTEND:20180530T020500Z
UID:u046UJ7GTzbhrRpIDlBhhlOe@stanza.co
SUMMARY:GreenJackets @ Drive
DESCRIPTION:GreenJackets @ Drive\n\nFollow on MiLB First Pitch: https://stza.co/+xEZu-13\n\nShop: https://stza.co/+xEZu-1G\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144503Z
LAST-MODIFIED:20180213T144503Z
TRANSP:OPAQUE
END:VEVENT
* GreenJackets @ Drive
<2018-05-30 Wed 18:05-21:05>
:PROPERTIES:
:ID:       RVY1KcxQhPARFsY9rRpCx0Ql@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

GreenJackets @ Drive GreenJackets @ Drive

Follow on MiLB First Pitch  https //stza.co/+xEZv-1q

Shop  https //stza.co/+xEZv-3o

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:GreenJackets @ Drive
END:VALARM
DTSTART:20180530T230500Z
DTEND:20180531T020500Z
UID:RVY1KcxQhPARFsY9rRpCx0Ql@stanza.co
SUMMARY:GreenJackets @ Drive
DESCRIPTION:GreenJackets @ Drive\n\nFollow on MiLB First Pitch: https://stza.co/+xEZv-1q\n\nShop: https://stza.co/+xEZv-3o\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144503Z
LAST-MODIFIED:20180213T144503Z
TRANSP:OPAQUE
END:VEVENT
* GreenJackets @ Drive
<2018-05-31 Thu 18:05-21:05>
:PROPERTIES:
:ID:       FXCELkOXcLsuQEYWybMOUonm@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

GreenJackets @ Drive GreenJackets @ Drive

Follow on MiLB First Pitch  https //stza.co/+xEZw-1J

Shop  https //stza.co/+xEZw-2h

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:GreenJackets @ Drive
END:VALARM
DTSTART:20180531T230500Z
DTEND:20180601T020500Z
UID:FXCELkOXcLsuQEYWybMOUonm@stanza.co
SUMMARY:GreenJackets @ Drive
DESCRIPTION:GreenJackets @ Drive\n\nFollow on MiLB First Pitch: https://stza.co/+xEZw-1J\n\nShop: https://stza.co/+xEZw-2h\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144503Z
LAST-MODIFIED:20180213T144503Z
TRANSP:OPAQUE
END:VEVENT
* GreenJackets @ Legends
<2018-06-01 Fri 18:05-21:05>
:PROPERTIES:
:ID:       rjrILQPZ474hk7xgwbpVPbUZ@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

GreenJackets @ Legends GreenJackets @ Legends

Follow on MiLB First Pitch  https //stza.co/+xAV6-Y

Shop  https //stza.co/+xAV6-3o

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:GreenJackets @ Legends
END:VALARM
DTSTART:20180601T230500Z
DTEND:20180602T020500Z
UID:rjrILQPZ474hk7xgwbpVPbUZ@stanza.co
SUMMARY:GreenJackets @ Legends
DESCRIPTION:GreenJackets @ Legends\n\nFollow on MiLB First Pitch: https://stza.co/+xAV6-Y\n\nShop: https://stza.co/+xAV6-3o\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144503Z
LAST-MODIFIED:20180213T144503Z
TRANSP:OPAQUE
END:VEVENT
* GreenJackets @ Legends
<2018-06-02 Sat 17:35-20:35>
:PROPERTIES:
:ID:       ddi9zWgaOWpfSH8fPKvAhUAv@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

GreenJackets @ Legends GreenJackets @ Legends

Follow on MiLB First Pitch  https //stza.co/+xAV9-3u

Shop  https //stza.co/+xAV9-36

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:GreenJackets @ Legends
END:VALARM
DTSTART:20180602T223500Z
DTEND:20180603T013500Z
UID:ddi9zWgaOWpfSH8fPKvAhUAv@stanza.co
SUMMARY:GreenJackets @ Legends
DESCRIPTION:GreenJackets @ Legends\n\nFollow on MiLB First Pitch: https://stza.co/+xAV9-3u\n\nShop: https://stza.co/+xAV9-36\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144503Z
LAST-MODIFIED:20180213T144503Z
TRANSP:OPAQUE
END:VEVENT
* GreenJackets @ Legends
<2018-06-03 Sun 13:05-16:05>
:PROPERTIES:
:ID:       oa9B_FeF5NdNDsCeTB3_Ah2b@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

GreenJackets @ Legends GreenJackets @ Legends

Follow on MiLB First Pitch  https //stza.co/+xAVa-q

Shop  https //stza.co/+xAVa-2r

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:GreenJackets @ Legends
END:VALARM
DTSTART:20180603T180500Z
DTEND:20180603T210500Z
UID:oa9B_FeF5NdNDsCeTB3_Ah2b@stanza.co
SUMMARY:GreenJackets @ Legends
DESCRIPTION:GreenJackets @ Legends\n\nFollow on MiLB First Pitch: https://stza.co/+xAVa-q\n\nShop: https://stza.co/+xAVa-2r\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144503Z
LAST-MODIFIED:20180213T144503Z
TRANSP:OPAQUE
END:VEVENT
* GreenJackets vs. Drive
<2018-06-05 Tue 18:05-21:05>
:PROPERTIES:
:ID:       _evQdOhqJuJ2h3j0F9nc9nsp@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

GreenJackets vs. Drive GreenJackets vs. Drive

Follow on MiLB First Pitch  https //stza.co/+xBHg-3o

Shop  https //stza.co/+xBHg-I

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:GreenJackets vs. Drive
END:VALARM
DTSTART:20180605T230500Z
DTEND:20180606T020500Z
UID:_evQdOhqJuJ2h3j0F9nc9nsp@stanza.co
SUMMARY:GreenJackets vs. Drive
DESCRIPTION:GreenJackets vs. Drive\n\nFollow on MiLB First Pitch: https://stza.co/+xBHg-3o\n\nShop: https://stza.co/+xBHg-I\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144503Z
LAST-MODIFIED:20180213T144503Z
TRANSP:OPAQUE
END:VEVENT
* GreenJackets vs. Drive
<2018-06-06 Wed 18:05-21:05>
:PROPERTIES:
:ID:       phDcH91RL4d_MJE0NE-daDG5@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

GreenJackets vs. Drive GreenJackets vs. Drive

Follow on MiLB First Pitch  https //stza.co/+xBHl-B

Shop  https //stza.co/+xBHl-3h

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:GreenJackets vs. Drive
END:VALARM
DTSTART:20180606T230500Z
DTEND:20180607T020500Z
UID:phDcH91RL4d_MJE0NE-daDG5@stanza.co
SUMMARY:GreenJackets vs. Drive
DESCRIPTION:GreenJackets vs. Drive\n\nFollow on MiLB First Pitch: https://stza.co/+xBHl-B\n\nShop: https://stza.co/+xBHl-3h\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144503Z
LAST-MODIFIED:20180213T144503Z
TRANSP:OPAQUE
END:VEVENT
* GreenJackets vs. Drive
<2018-06-07 Thu 18:05-21:05>
:PROPERTIES:
:ID:       wtN1ChCW3h3vCQJU77s_UDpV@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

GreenJackets vs. Drive GreenJackets vs. Drive

Follow on MiLB First Pitch  https //stza.co/+xBHo-36

Shop  https //stza.co/+xBHo-B

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:GreenJackets vs. Drive
END:VALARM
DTSTART:20180607T230500Z
DTEND:20180608T020500Z
UID:wtN1ChCW3h3vCQJU77s_UDpV@stanza.co
SUMMARY:GreenJackets vs. Drive
DESCRIPTION:GreenJackets vs. Drive\n\nFollow on MiLB First Pitch: https://stza.co/+xBHo-36\n\nShop: https://stza.co/+xBHo-B\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144503Z
LAST-MODIFIED:20180213T144503Z
TRANSP:OPAQUE
END:VEVENT
* GreenJackets @ Fireflies
<2018-06-08 Fri 18:05-21:05>
:PROPERTIES:
:ID:       XWMpmppatD8mVTK2UZ2PfT4U@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

GreenJackets @ Fireflies GreenJackets @ Fireflies

Follow on MiLB First Pitch  https //stza.co/+xAUZ-3J

Shop  https //stza.co/+xAUZ-3n

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:GreenJackets @ Fireflies
END:VALARM
DTSTART:20180608T230500Z
DTEND:20180609T020500Z
UID:XWMpmppatD8mVTK2UZ2PfT4U@stanza.co
SUMMARY:GreenJackets @ Fireflies
DESCRIPTION:GreenJackets @ Fireflies\n\nFollow on MiLB First Pitch: https://stza.co/+xAUZ-3J\n\nShop: https://stza.co/+xAUZ-3n\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144503Z
LAST-MODIFIED:20180213T144503Z
TRANSP:OPAQUE
END:VEVENT
* GreenJackets @ Fireflies
<2018-06-09 Sat 17:05-20:05>
:PROPERTIES:
:ID:       h8CiJGggW8bjQ2MjNDXwqYbC@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

GreenJackets @ Fireflies GreenJackets @ Fireflies

Follow on MiLB First Pitch  https //stza.co/+xAU_-1c

Shop  https //stza.co/+xAU_-m

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:GreenJackets @ Fireflies
END:VALARM
DTSTART:20180609T220500Z
DTEND:20180610T010500Z
UID:h8CiJGggW8bjQ2MjNDXwqYbC@stanza.co
SUMMARY:GreenJackets @ Fireflies
DESCRIPTION:GreenJackets @ Fireflies\n\nFollow on MiLB First Pitch: https://stza.co/+xAU_-1c\n\nShop: https://stza.co/+xAU_-m\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144503Z
LAST-MODIFIED:20180213T144503Z
TRANSP:OPAQUE
END:VEVENT
* GreenJackets @ Fireflies
<2018-06-10 Sun 13:05-16:05>
:PROPERTIES:
:ID:       3hOywEFgQl6o5fUlqZEulgrM@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

GreenJackets @ Fireflies GreenJackets @ Fireflies

Follow on MiLB First Pitch  https //stza.co/+xAU$-2N

Shop  https //stza.co/+xAU$-1t

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:GreenJackets @ Fireflies
END:VALARM
DTSTART:20180610T180500Z
DTEND:20180610T210500Z
UID:3hOywEFgQl6o5fUlqZEulgrM@stanza.co
SUMMARY:GreenJackets @ Fireflies
DESCRIPTION:GreenJackets @ Fireflies\n\nFollow on MiLB First Pitch: https://stza.co/+xAU$-2N\n\nShop: https://stza.co/+xAU$-1t\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144503Z
LAST-MODIFIED:20180213T144503Z
TRANSP:OPAQUE
END:VEVENT
* GreenJackets vs. Power
<2018-06-11 Mon 18:05-21:05>
:PROPERTIES:
:ID:       Lh2_uScojASWDHBUyjeSbfjK@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

GreenJackets vs. Power GreenJackets vs. Power

Follow on MiLB First Pitch  https //stza.co/+xBHr-3P

Shop  https //stza.co/+xBHr-28

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:GreenJackets vs. Power
END:VALARM
DTSTART:20180611T230500Z
DTEND:20180612T020500Z
UID:Lh2_uScojASWDHBUyjeSbfjK@stanza.co
SUMMARY:GreenJackets vs. Power
DESCRIPTION:GreenJackets vs. Power\n\nFollow on MiLB First Pitch: https://stza.co/+xBHr-3P\n\nShop: https://stza.co/+xBHr-28\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144503Z
LAST-MODIFIED:20180213T144503Z
TRANSP:OPAQUE
END:VEVENT
* GreenJackets vs. Power
<2018-06-12 Tue 18:05-21:05>
:PROPERTIES:
:ID:       GUK8idFmASCYT1fA33azbku_@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

GreenJackets vs. Power GreenJackets vs. Power

Follow on MiLB First Pitch  https //stza.co/+xBHv-21

Shop  https //stza.co/+xBHv-s

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:GreenJackets vs. Power
END:VALARM
DTSTART:20180612T230500Z
DTEND:20180613T020500Z
UID:GUK8idFmASCYT1fA33azbku_@stanza.co
SUMMARY:GreenJackets vs. Power
DESCRIPTION:GreenJackets vs. Power\n\nFollow on MiLB First Pitch: https://stza.co/+xBHv-21\n\nShop: https://stza.co/+xBHv-s\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144503Z
LAST-MODIFIED:20180213T144503Z
TRANSP:OPAQUE
END:VEVENT
* GreenJackets vs. Power
<2018-06-13 Wed 18:05-21:05>
:PROPERTIES:
:ID:       SIFCNF56WFWlJxWiqgzyeiiK@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

GreenJackets vs. Power GreenJackets vs. Power

Follow on MiLB First Pitch  https //stza.co/+xBHx-2t

Shop  https //stza.co/+xBHx-34

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:GreenJackets vs. Power
END:VALARM
DTSTART:20180613T230500Z
DTEND:20180614T020500Z
UID:SIFCNF56WFWlJxWiqgzyeiiK@stanza.co
SUMMARY:GreenJackets vs. Power
DESCRIPTION:GreenJackets vs. Power\n\nFollow on MiLB First Pitch: https://stza.co/+xBHx-2t\n\nShop: https://stza.co/+xBHx-34\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144503Z
LAST-MODIFIED:20180213T144503Z
TRANSP:OPAQUE
END:VEVENT
* GreenJackets vs. Power
<2018-06-14 Thu 18:05-21:05>
:PROPERTIES:
:ID:       6AbqjYpB1_HQPo8Tmss47P5M@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

GreenJackets vs. Power GreenJackets vs. Power

Follow on MiLB First Pitch  https //stza.co/+xBHB-1Z

Shop  https //stza.co/+xBHB-2U

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:GreenJackets vs. Power
END:VALARM
DTSTART:20180614T230500Z
DTEND:20180615T020500Z
UID:6AbqjYpB1_HQPo8Tmss47P5M@stanza.co
SUMMARY:GreenJackets vs. Power
DESCRIPTION:GreenJackets vs. Power\n\nFollow on MiLB First Pitch: https://stza.co/+xBHB-1Z\n\nShop: https://stza.co/+xBHB-2U\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144503Z
LAST-MODIFIED:20180213T144503Z
TRANSP:OPAQUE
END:VEVENT
* GreenJackets @ Tourists
<2018-06-15 Fri 18:05-21:05>
:PROPERTIES:
:ID:       MkSW6-rw77xmGiZPZBqfvLO8@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

GreenJackets @ Tourists GreenJackets @ Tourists

Follow on MiLB First Pitch  https //stza.co/+vNvS-3v

Shop  https //stza.co/+vNvS-3F

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:GreenJackets @ Tourists
END:VALARM
DTSTART:20180615T230500Z
DTEND:20180616T020500Z
UID:MkSW6-rw77xmGiZPZBqfvLO8@stanza.co
SUMMARY:GreenJackets @ Tourists
DESCRIPTION:GreenJackets @ Tourists\n\nFollow on MiLB First Pitch: https://stza.co/+vNvS-3v\n\nShop: https://stza.co/+vNvS-3F\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144503Z
LAST-MODIFIED:20180213T144503Z
TRANSP:OPAQUE
END:VEVENT
* GreenJackets @ Tourists
<2018-06-16 Sat 17:05-20:05>
:PROPERTIES:
:ID:       ecPqoL4Wb_iiTTOVflJLlbg2@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

GreenJackets @ Tourists GreenJackets @ Tourists

Follow on MiLB First Pitch  https //stza.co/+vNvT-L

Shop  https //stza.co/+vNvT-3t

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:GreenJackets @ Tourists
END:VALARM
DTSTART:20180616T220500Z
DTEND:20180617T010500Z
UID:ecPqoL4Wb_iiTTOVflJLlbg2@stanza.co
SUMMARY:GreenJackets @ Tourists
DESCRIPTION:GreenJackets @ Tourists\n\nFollow on MiLB First Pitch: https://stza.co/+vNvT-L\n\nShop: https://stza.co/+vNvT-3t\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144503Z
LAST-MODIFIED:20180213T144503Z
TRANSP:OPAQUE
END:VEVENT
* GreenJackets @ Tourists
<2018-06-17 Sun 13:05-16:05>
:PROPERTIES:
:ID:       Ao8P0jFHt4SBDA_mgbSN-on_@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

GreenJackets @ Tourists GreenJackets @ Tourists

Follow on MiLB First Pitch  https //stza.co/+vNvU-

Shop  https //stza.co/+vNvU-2j

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:GreenJackets @ Tourists
END:VALARM
DTSTART:20180617T180500Z
DTEND:20180617T210500Z
UID:Ao8P0jFHt4SBDA_mgbSN-on_@stanza.co
SUMMARY:GreenJackets @ Tourists
DESCRIPTION:GreenJackets @ Tourists\n\nFollow on MiLB First Pitch: https://stza.co/+vNvU-\n\nShop: https://stza.co/+vNvU-2j\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144503Z
LAST-MODIFIED:20180213T144503Z
TRANSP:OPAQUE
END:VEVENT
* GreenJackets vs. Braves
<2018-06-21 Thu 18:05-21:05>
:PROPERTIES:
:ID:       BYlRlaNuB2GQt33ANwL6pu_W@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

GreenJackets vs. Braves GreenJackets vs. Braves

Follow on MiLB First Pitch  https //stza.co/+xBHD-15

Shop  https //stza.co/+xBHD-3Z

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:GreenJackets vs. Braves
END:VALARM
DTSTART:20180621T230500Z
DTEND:20180622T020500Z
UID:BYlRlaNuB2GQt33ANwL6pu_W@stanza.co
SUMMARY:GreenJackets vs. Braves
DESCRIPTION:GreenJackets vs. Braves\n\nFollow on MiLB First Pitch: https://stza.co/+xBHD-15\n\nShop: https://stza.co/+xBHD-3Z\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144503Z
LAST-MODIFIED:20180213T144503Z
TRANSP:OPAQUE
END:VEVENT
* GreenJackets vs. Braves
<2018-06-22 Fri 18:05-21:05>
:PROPERTIES:
:ID:       ft9H6uikG1eOBZU7RI7CPmJE@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

GreenJackets vs. Braves GreenJackets vs. Braves

Follow on MiLB First Pitch  https //stza.co/+xBHF-F

Shop  https //stza.co/+xBHF-1S

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:GreenJackets vs. Braves
END:VALARM
DTSTART:20180622T230500Z
DTEND:20180623T020500Z
UID:ft9H6uikG1eOBZU7RI7CPmJE@stanza.co
SUMMARY:GreenJackets vs. Braves
DESCRIPTION:GreenJackets vs. Braves\n\nFollow on MiLB First Pitch: https://stza.co/+xBHF-F\n\nShop: https://stza.co/+xBHF-1S\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144503Z
LAST-MODIFIED:20180213T144503Z
TRANSP:OPAQUE
END:VEVENT
* GreenJackets vs. Braves
<2018-06-23 Sat 17:05-20:05>
:PROPERTIES:
:ID:       tNIUu84yi77MKU4jl2AT6x-c@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

GreenJackets vs. Braves GreenJackets vs. Braves

Follow on MiLB First Pitch  https //stza.co/+xBHG-2$

Shop  https //stza.co/+xBHG-3t

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:GreenJackets vs. Braves
END:VALARM
DTSTART:20180623T220500Z
DTEND:20180624T010500Z
UID:tNIUu84yi77MKU4jl2AT6x-c@stanza.co
SUMMARY:GreenJackets vs. Braves
DESCRIPTION:GreenJackets vs. Braves\n\nFollow on MiLB First Pitch: https://stza.co/+xBHG-2$\n\nShop: https://stza.co/+xBHG-3t\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144503Z
LAST-MODIFIED:20180213T144503Z
TRANSP:OPAQUE
END:VEVENT
* GreenJackets @ Crawdads
<2018-06-24 Sun 16:00-19:00>
:PROPERTIES:
:ID:       nXfkM_YXjENr6axjJ_JAs_mB@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

GreenJackets @ Crawdads GreenJackets @ Crawdads

Follow on MiLB First Pitch  https //stza.co/+w0O4-2T

Shop  https //stza.co/+w0O4-2y

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:GreenJackets @ Crawdads
END:VALARM
DTSTART:20180624T210000Z
DTEND:20180625T000000Z
UID:nXfkM_YXjENr6axjJ_JAs_mB@stanza.co
SUMMARY:GreenJackets @ Crawdads
DESCRIPTION:GreenJackets @ Crawdads\n\nFollow on MiLB First Pitch: https://stza.co/+w0O4-2T\n\nShop: https://stza.co/+w0O4-2y\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144503Z
LAST-MODIFIED:20180213T144503Z
TRANSP:OPAQUE
END:VEVENT
* GreenJackets @ Crawdads
<2018-06-25 Mon 18:00-21:00>
:PROPERTIES:
:ID:       MdFT_tELL5I2wQqreUORFUrv@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

GreenJackets @ Crawdads GreenJackets @ Crawdads

Follow on MiLB First Pitch  https //stza.co/+w0O5-1q

Shop  https //stza.co/+w0O5-14

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:GreenJackets @ Crawdads
END:VALARM
DTSTART:20180625T230000Z
DTEND:20180626T020000Z
UID:MdFT_tELL5I2wQqreUORFUrv@stanza.co
SUMMARY:GreenJackets @ Crawdads
DESCRIPTION:GreenJackets @ Crawdads\n\nFollow on MiLB First Pitch: https://stza.co/+w0O5-1q\n\nShop: https://stza.co/+w0O5-14\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144503Z
LAST-MODIFIED:20180213T144503Z
TRANSP:OPAQUE
END:VEVENT
* GreenJackets @ Crawdads
<2018-06-26 Tue 11:00-14:00>
:PROPERTIES:
:ID:       D8VekjtQYXxinxLHIPAzaVdx@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

GreenJackets @ Crawdads GreenJackets @ Crawdads

Follow on MiLB First Pitch  https //stza.co/+w0O6-1l

Shop  https //stza.co/+w0O6-3U

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:GreenJackets @ Crawdads
END:VALARM
DTSTART:20180626T160000Z
DTEND:20180626T190000Z
UID:D8VekjtQYXxinxLHIPAzaVdx@stanza.co
SUMMARY:GreenJackets @ Crawdads
DESCRIPTION:GreenJackets @ Crawdads\n\nFollow on MiLB First Pitch: https://stza.co/+w0O6-1l\n\nShop: https://stza.co/+w0O6-3U\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144503Z
LAST-MODIFIED:20180213T144503Z
TRANSP:OPAQUE
END:VEVENT
* GreenJackets vs. Drive
<2018-06-27 Wed 18:05-21:05>
:PROPERTIES:
:ID:       UvEUUwz9_apzC9m1SOM2CzTG@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

GreenJackets vs. Drive GreenJackets vs. Drive

Follow on MiLB First Pitch  https //stza.co/+xBHJ-2p

Shop  https //stza.co/+xBHJ-2M

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:GreenJackets vs. Drive
END:VALARM
DTSTART:20180627T230500Z
DTEND:20180628T020500Z
UID:UvEUUwz9_apzC9m1SOM2CzTG@stanza.co
SUMMARY:GreenJackets vs. Drive
DESCRIPTION:GreenJackets vs. Drive\n\nFollow on MiLB First Pitch: https://stza.co/+xBHJ-2p\n\nShop: https://stza.co/+xBHJ-2M\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144503Z
LAST-MODIFIED:20180213T144503Z
TRANSP:OPAQUE
END:VEVENT
* GreenJackets vs. Drive
<2018-06-28 Thu 18:05-21:05>
:PROPERTIES:
:ID:       XNvmXww9zgXmd0PB_qO60YMX@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

GreenJackets vs. Drive GreenJackets vs. Drive

Follow on MiLB First Pitch  https //stza.co/+xBHK-1n

Shop  https //stza.co/+xBHK-1_

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:GreenJackets vs. Drive
END:VALARM
DTSTART:20180628T230500Z
DTEND:20180629T020500Z
UID:XNvmXww9zgXmd0PB_qO60YMX@stanza.co
SUMMARY:GreenJackets vs. Drive
DESCRIPTION:GreenJackets vs. Drive\n\nFollow on MiLB First Pitch: https://stza.co/+xBHK-1n\n\nShop: https://stza.co/+xBHK-1_\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144503Z
LAST-MODIFIED:20180213T144503Z
TRANSP:OPAQUE
END:VEVENT
* GreenJackets vs. Drive
<2018-06-29 Fri 18:05-21:05>
:PROPERTIES:
:ID:       KPBTbYKLExzPXhEsfEAilp8v@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

GreenJackets vs. Drive GreenJackets vs. Drive

Follow on MiLB First Pitch  https //stza.co/+xBHN-1F

Shop  https //stza.co/+xBHN-3Y

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:GreenJackets vs. Drive
END:VALARM
DTSTART:20180629T230500Z
DTEND:20180630T020500Z
UID:KPBTbYKLExzPXhEsfEAilp8v@stanza.co
SUMMARY:GreenJackets vs. Drive
DESCRIPTION:GreenJackets vs. Drive\n\nFollow on MiLB First Pitch: https://stza.co/+xBHN-1F\n\nShop: https://stza.co/+xBHN-3Y\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144503Z
LAST-MODIFIED:20180213T144503Z
TRANSP:OPAQUE
END:VEVENT
* GreenJackets vs. Fireflies
<2018-06-30 Sat 17:05-20:05>
:PROPERTIES:
:ID:       SIC2NWLpDgGp9pr5VWTS5oWK@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

GreenJackets vs. Fireflies GreenJackets vs. Fireflies

Follow on MiLB First Pitch  https //stza.co/+xBHO-1b

Shop  https //stza.co/+xBHO-F

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:GreenJackets vs. Fireflies
END:VALARM
DTSTART:20180630T220500Z
DTEND:20180701T010500Z
UID:SIC2NWLpDgGp9pr5VWTS5oWK@stanza.co
SUMMARY:GreenJackets vs. Fireflies
DESCRIPTION:GreenJackets vs. Fireflies\n\nFollow on MiLB First Pitch: https://stza.co/+xBHO-1b\n\nShop: https://stza.co/+xBHO-F\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144503Z
LAST-MODIFIED:20180213T144503Z
TRANSP:OPAQUE
END:VEVENT
* GreenJackets vs. Fireflies
<2018-07-01 Sun 16:05-19:05>
:PROPERTIES:
:ID:       RODG3vMoBZLpSUuZdpXUKnbj@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

GreenJackets vs. Fireflies GreenJackets vs. Fireflies

Follow on MiLB First Pitch  https //stza.co/+xBHR-2n

Shop  https //stza.co/+xBHR-35

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:GreenJackets vs. Fireflies
END:VALARM
DTSTART:20180701T210500Z
DTEND:20180702T000500Z
UID:RODG3vMoBZLpSUuZdpXUKnbj@stanza.co
SUMMARY:GreenJackets vs. Fireflies
DESCRIPTION:GreenJackets vs. Fireflies\n\nFollow on MiLB First Pitch: https://stza.co/+xBHR-2n\n\nShop: https://stza.co/+xBHR-35\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144503Z
LAST-MODIFIED:20180213T144503Z
TRANSP:OPAQUE
END:VEVENT
* GreenJackets vs. Fireflies
<2018-07-02 Mon 18:05-21:05>
:PROPERTIES:
:ID:       7rEFDF6JQmwXACu3nVPtznvt@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

GreenJackets vs. Fireflies GreenJackets vs. Fireflies

Follow on MiLB First Pitch  https //stza.co/+xBHV-Q

Shop  https //stza.co/+xBHV-12

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:GreenJackets vs. Fireflies
END:VALARM
DTSTART:20180702T230500Z
DTEND:20180703T020500Z
UID:7rEFDF6JQmwXACu3nVPtznvt@stanza.co
SUMMARY:GreenJackets vs. Fireflies
DESCRIPTION:GreenJackets vs. Fireflies\n\nFollow on MiLB First Pitch: https://stza.co/+xBHV-Q\n\nShop: https://stza.co/+xBHV-12\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144503Z
LAST-MODIFIED:20180213T144503Z
TRANSP:OPAQUE
END:VEVENT
* GreenJackets vs. Fireflies
<2018-07-03 Tue 17:35-20:35>
:PROPERTIES:
:ID:       nHtmzuvul9vAAP7MU3CTDwI8@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

GreenJackets vs. Fireflies GreenJackets vs. Fireflies

Follow on MiLB First Pitch  https //stza.co/+xBHX-1a

Shop  https //stza.co/+xBHX-3H

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:GreenJackets vs. Fireflies
END:VALARM
DTSTART:20180703T223500Z
DTEND:20180704T013500Z
UID:nHtmzuvul9vAAP7MU3CTDwI8@stanza.co
SUMMARY:GreenJackets vs. Fireflies
DESCRIPTION:GreenJackets vs. Fireflies\n\nFollow on MiLB First Pitch: https://stza.co/+xBHX-1a\n\nShop: https://stza.co/+xBHX-3H\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144503Z
LAST-MODIFIED:20180213T144503Z
TRANSP:OPAQUE
END:VEVENT
* GreenJackets @ RiverDogs
<2018-07-04 Wed 17:35-20:35>
:PROPERTIES:
:ID:       JURAya33XEFi-23UsJk6N1Pc@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

GreenJackets @ RiverDogs GreenJackets @ RiverDogs

Follow on MiLB First Pitch  https //stza.co/+vNy9-2P

Shop  https //stza.co/+vNy9-1U

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:GreenJackets @ RiverDogs
END:VALARM
DTSTART:20180704T223500Z
DTEND:20180705T013500Z
UID:JURAya33XEFi-23UsJk6N1Pc@stanza.co
SUMMARY:GreenJackets @ RiverDogs
DESCRIPTION:GreenJackets @ RiverDogs\n\nFollow on MiLB First Pitch: https://stza.co/+vNy9-2P\n\nShop: https://stza.co/+vNy9-1U\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144503Z
LAST-MODIFIED:20180213T144503Z
TRANSP:OPAQUE
END:VEVENT
* GreenJackets @ RiverDogs
<2018-07-05 Thu 18:05-21:05>
:PROPERTIES:
:ID:       DFHLSygfZ9tYf15js82duF2k@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

GreenJackets @ RiverDogs GreenJackets @ RiverDogs

Follow on MiLB First Pitch  https //stza.co/+vNya-1D

Shop  https //stza.co/+vNya-2g

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:GreenJackets @ RiverDogs
END:VALARM
DTSTART:20180705T230500Z
DTEND:20180706T020500Z
UID:DFHLSygfZ9tYf15js82duF2k@stanza.co
SUMMARY:GreenJackets @ RiverDogs
DESCRIPTION:GreenJackets @ RiverDogs\n\nFollow on MiLB First Pitch: https://stza.co/+vNya-1D\n\nShop: https://stza.co/+vNya-2g\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144503Z
LAST-MODIFIED:20180213T144503Z
TRANSP:OPAQUE
END:VEVENT
* GreenJackets @ RiverDogs
<2018-07-06 Fri 18:05-21:05>
:PROPERTIES:
:ID:       dBBz30IsuLMFqzucmf8ZNw6H@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

GreenJackets @ RiverDogs GreenJackets @ RiverDogs

Follow on MiLB First Pitch  https //stza.co/+vNyb-3q

Shop  https //stza.co/+vNyb-2T

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:GreenJackets @ RiverDogs
END:VALARM
DTSTART:20180706T230500Z
DTEND:20180707T020500Z
UID:dBBz30IsuLMFqzucmf8ZNw6H@stanza.co
SUMMARY:GreenJackets @ RiverDogs
DESCRIPTION:GreenJackets @ RiverDogs\n\nFollow on MiLB First Pitch: https://stza.co/+vNyb-3q\n\nShop: https://stza.co/+vNyb-2T\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144503Z
LAST-MODIFIED:20180213T144503Z
TRANSP:OPAQUE
END:VEVENT
* GreenJackets @ Braves
<2018-07-07 Sat 17:00-20:00>
:PROPERTIES:
:ID:       O54ktPvclYqXRVu0RtGD7SD0@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

GreenJackets @ Braves GreenJackets @ Braves

Follow on MiLB First Pitch  https //stza.co/+vNy_-2I

Shop  https //stza.co/+vNy_-2o

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:GreenJackets @ Braves
END:VALARM
DTSTART:20180707T220000Z
DTEND:20180708T010000Z
UID:O54ktPvclYqXRVu0RtGD7SD0@stanza.co
SUMMARY:GreenJackets @ Braves
DESCRIPTION:GreenJackets @ Braves\n\nFollow on MiLB First Pitch: https://stza.co/+vNy_-2I\n\nShop: https://stza.co/+vNy_-2o\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144503Z
LAST-MODIFIED:20180213T144503Z
TRANSP:OPAQUE
END:VEVENT
* GreenJackets @ Braves
<2018-07-08 Sun 13:00-16:00>
:PROPERTIES:
:ID:       ZXe1ARTx-I53L8FdsBoCYsKl@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

GreenJackets @ Braves GreenJackets @ Braves

Follow on MiLB First Pitch  https //stza.co/+vNy$-34

Shop  https //stza.co/+vNy$-2W

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:GreenJackets @ Braves
END:VALARM
DTSTART:20180708T180000Z
DTEND:20180708T210000Z
UID:ZXe1ARTx-I53L8FdsBoCYsKl@stanza.co
SUMMARY:GreenJackets @ Braves
DESCRIPTION:GreenJackets @ Braves\n\nFollow on MiLB First Pitch: https://stza.co/+vNy$-34\n\nShop: https://stza.co/+vNy$-2W\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144503Z
LAST-MODIFIED:20180213T144503Z
TRANSP:OPAQUE
END:VEVENT
* GreenJackets @ Braves
<2018-07-09 Mon 18:00-21:00>
:PROPERTIES:
:ID:       M7vxwt0SZ_4kqtDY-aTyHAu6@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

GreenJackets @ Braves GreenJackets @ Braves

Follow on MiLB First Pitch  https //stza.co/+vNz0-3h

Shop  https //stza.co/+vNz0-37

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:GreenJackets @ Braves
END:VALARM
DTSTART:20180709T230000Z
DTEND:20180710T020000Z
UID:M7vxwt0SZ_4kqtDY-aTyHAu6@stanza.co
SUMMARY:GreenJackets @ Braves
DESCRIPTION:GreenJackets @ Braves\n\nFollow on MiLB First Pitch: https://stza.co/+vNz0-3h\n\nShop: https://stza.co/+vNz0-37\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144503Z
LAST-MODIFIED:20180213T144503Z
TRANSP:OPAQUE
END:VEVENT
* GreenJackets vs. Legends
<2018-07-11 Wed 18:05-21:05>
:PROPERTIES:
:ID:       oxFWsLOLCL0F5rg31vxVLVe7@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

GreenJackets vs. Legends GreenJackets vs. Legends

Follow on MiLB First Pitch  https //stza.co/+xBHY-11

Shop  https //stza.co/+xBHY-z

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:GreenJackets vs. Legends
END:VALARM
DTSTART:20180711T230500Z
DTEND:20180712T020500Z
UID:oxFWsLOLCL0F5rg31vxVLVe7@stanza.co
SUMMARY:GreenJackets vs. Legends
DESCRIPTION:GreenJackets vs. Legends\n\nFollow on MiLB First Pitch: https://stza.co/+xBHY-11\n\nShop: https://stza.co/+xBHY-z\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144503Z
LAST-MODIFIED:20180213T144503Z
TRANSP:OPAQUE
END:VEVENT
* GreenJackets vs. Legends
<2018-07-12 Thu 18:05-21:05>
:PROPERTIES:
:ID:       RLSUCli4CYHGeo3RjkWCT8T0@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

GreenJackets vs. Legends GreenJackets vs. Legends

Follow on MiLB First Pitch  https //stza.co/+xBI2-Q

Shop  https //stza.co/+xBI2-H

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:GreenJackets vs. Legends
END:VALARM
DTSTART:20180712T230500Z
DTEND:20180713T020500Z
UID:RLSUCli4CYHGeo3RjkWCT8T0@stanza.co
SUMMARY:GreenJackets vs. Legends
DESCRIPTION:GreenJackets vs. Legends\n\nFollow on MiLB First Pitch: https://stza.co/+xBI2-Q\n\nShop: https://stza.co/+xBI2-H\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144503Z
LAST-MODIFIED:20180213T144503Z
TRANSP:OPAQUE
END:VEVENT
* GreenJackets vs. Legends
<2018-07-13 Fri 18:05-21:05>
:PROPERTIES:
:ID:       LkcBFj8-7XZisEX2iQkT8CWP@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

GreenJackets vs. Legends GreenJackets vs. Legends

Follow on MiLB First Pitch  https //stza.co/+xBI6-1T

Shop  https //stza.co/+xBI6-3P

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:GreenJackets vs. Legends
END:VALARM
DTSTART:20180713T230500Z
DTEND:20180714T020500Z
UID:LkcBFj8-7XZisEX2iQkT8CWP@stanza.co
SUMMARY:GreenJackets vs. Legends
DESCRIPTION:GreenJackets vs. Legends\n\nFollow on MiLB First Pitch: https://stza.co/+xBI6-1T\n\nShop: https://stza.co/+xBI6-3P\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144503Z
LAST-MODIFIED:20180213T144503Z
TRANSP:OPAQUE
END:VEVENT
* GreenJackets vs. Braves
<2018-07-14 Sat 17:05-20:05>
:PROPERTIES:
:ID:       SgA_BN8Y8Mbav_xccrLjcnsm@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

GreenJackets vs. Braves GreenJackets vs. Braves

Follow on MiLB First Pitch  https //stza.co/+xBIb-2f

Shop  https //stza.co/+xBIb-2h

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:GreenJackets vs. Braves
END:VALARM
DTSTART:20180714T220500Z
DTEND:20180715T010500Z
UID:SgA_BN8Y8Mbav_xccrLjcnsm@stanza.co
SUMMARY:GreenJackets vs. Braves
DESCRIPTION:GreenJackets vs. Braves\n\nFollow on MiLB First Pitch: https://stza.co/+xBIb-2f\n\nShop: https://stza.co/+xBIb-2h\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144503Z
LAST-MODIFIED:20180213T144503Z
TRANSP:OPAQUE
END:VEVENT
* GreenJackets vs. Braves
<2018-07-15 Sun 16:05-19:05>
:PROPERTIES:
:ID:       LLmBetM5WnFl7rHPPnvSIz8C@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

GreenJackets vs. Braves GreenJackets vs. Braves

Follow on MiLB First Pitch  https //stza.co/+xBIh-3x

Shop  https //stza.co/+xBIh-3v

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:GreenJackets vs. Braves
END:VALARM
DTSTART:20180715T210500Z
DTEND:20180716T000500Z
UID:LLmBetM5WnFl7rHPPnvSIz8C@stanza.co
SUMMARY:GreenJackets vs. Braves
DESCRIPTION:GreenJackets vs. Braves\n\nFollow on MiLB First Pitch: https://stza.co/+xBIh-3x\n\nShop: https://stza.co/+xBIh-3v\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144503Z
LAST-MODIFIED:20180213T144503Z
TRANSP:OPAQUE
END:VEVENT
* GreenJackets vs. Braves
<2018-07-16 Mon 18:05-21:05>
:PROPERTIES:
:ID:       pbBRZaGRg5d8BiYbW76PrMB_@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

GreenJackets vs. Braves GreenJackets vs. Braves

Follow on MiLB First Pitch  https //stza.co/+xBIm-3T

Shop  https //stza.co/+xBIm-2t

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:GreenJackets vs. Braves
END:VALARM
DTSTART:20180716T230500Z
DTEND:20180717T020500Z
UID:pbBRZaGRg5d8BiYbW76PrMB_@stanza.co
SUMMARY:GreenJackets vs. Braves
DESCRIPTION:GreenJackets vs. Braves\n\nFollow on MiLB First Pitch: https://stza.co/+xBIm-3T\n\nShop: https://stza.co/+xBIm-2t\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144503Z
LAST-MODIFIED:20180213T144503Z
TRANSP:OPAQUE
END:VEVENT
* GreenJackets vs. Braves
<2018-07-17 Tue 11:05-14:05>
:PROPERTIES:
:ID:       -Am3wP37IcyrvbU_zzid9yNK@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

GreenJackets vs. Braves GreenJackets vs. Braves

Follow on MiLB First Pitch  https //stza.co/+xBIs-17

Shop  https //stza.co/+xBIs-1A

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:GreenJackets vs. Braves
END:VALARM
DTSTART:20180717T160500Z
DTEND:20180717T190500Z
UID:-Am3wP37IcyrvbU_zzid9yNK@stanza.co
SUMMARY:GreenJackets vs. Braves
DESCRIPTION:GreenJackets vs. Braves\n\nFollow on MiLB First Pitch: https://stza.co/+xBIs-17\n\nShop: https://stza.co/+xBIs-1A\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144503Z
LAST-MODIFIED:20180213T144503Z
TRANSP:OPAQUE
END:VEVENT
* GreenJackets @ Fireflies
<2018-07-19 Thu 18:05-21:05>
:PROPERTIES:
:ID:       rYeN7bb85N5TTlocG8T-x8Gl@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

GreenJackets @ Fireflies GreenJackets @ Fireflies

Follow on MiLB First Pitch  https //stza.co/+xAV0-3D

Shop  https //stza.co/+xAV0-2H

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:GreenJackets @ Fireflies
END:VALARM
DTSTART:20180719T230500Z
DTEND:20180720T020500Z
UID:rYeN7bb85N5TTlocG8T-x8Gl@stanza.co
SUMMARY:GreenJackets @ Fireflies
DESCRIPTION:GreenJackets @ Fireflies\n\nFollow on MiLB First Pitch: https://stza.co/+xAV0-3D\n\nShop: https://stza.co/+xAV0-2H\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144503Z
LAST-MODIFIED:20180213T144503Z
TRANSP:OPAQUE
END:VEVENT
* GreenJackets @ Fireflies
<2018-07-20 Fri 18:05-21:05>
:PROPERTIES:
:ID:       eMCRYoBGFb1YsI7fWt--RIb-@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

GreenJackets @ Fireflies GreenJackets @ Fireflies

Follow on MiLB First Pitch  https //stza.co/+xAV3-t

Shop  https //stza.co/+xAV3-2u

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:GreenJackets @ Fireflies
END:VALARM
DTSTART:20180720T230500Z
DTEND:20180721T020500Z
UID:eMCRYoBGFb1YsI7fWt--RIb-@stanza.co
SUMMARY:GreenJackets @ Fireflies
DESCRIPTION:GreenJackets @ Fireflies\n\nFollow on MiLB First Pitch: https://stza.co/+xAV3-t\n\nShop: https://stza.co/+xAV3-2u\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144503Z
LAST-MODIFIED:20180213T144503Z
TRANSP:OPAQUE
END:VEVENT
* GreenJackets @ Fireflies
<2018-07-21 Sat 17:05-20:05>
:PROPERTIES:
:ID:       CqfrmaHI5oMacw8rP0Nay358@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

GreenJackets @ Fireflies GreenJackets @ Fireflies

Follow on MiLB First Pitch  https //stza.co/+xAV4-1u

Shop  https //stza.co/+xAV4-2v

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:GreenJackets @ Fireflies
END:VALARM
DTSTART:20180721T220500Z
DTEND:20180722T010500Z
UID:CqfrmaHI5oMacw8rP0Nay358@stanza.co
SUMMARY:GreenJackets @ Fireflies
DESCRIPTION:GreenJackets @ Fireflies\n\nFollow on MiLB First Pitch: https://stza.co/+xAV4-1u\n\nShop: https://stza.co/+xAV4-2v\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144503Z
LAST-MODIFIED:20180213T144503Z
TRANSP:OPAQUE
END:VEVENT
* GreenJackets @ Fireflies
<2018-07-22 Sun 13:05-16:05>
:PROPERTIES:
:ID:       zR7AL25F7o5N9TVsfPAZBwff@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

GreenJackets @ Fireflies GreenJackets @ Fireflies

Follow on MiLB First Pitch  https //stza.co/+xAV5-E

Shop  https //stza.co/+xAV5-

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:GreenJackets @ Fireflies
END:VALARM
DTSTART:20180722T180500Z
DTEND:20180722T210500Z
UID:zR7AL25F7o5N9TVsfPAZBwff@stanza.co
SUMMARY:GreenJackets @ Fireflies
DESCRIPTION:GreenJackets @ Fireflies\n\nFollow on MiLB First Pitch: https://stza.co/+xAV5-E\n\nShop: https://stza.co/+xAV5-\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144503Z
LAST-MODIFIED:20180213T144503Z
TRANSP:OPAQUE
END:VEVENT
* GreenJackets @ RiverDogs
<2018-07-23 Mon 18:05-21:05>
:PROPERTIES:
:ID:       7O-BjBiq10XRXJrhNpBHdC4M@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

GreenJackets @ RiverDogs GreenJackets @ RiverDogs

Follow on MiLB First Pitch  https //stza.co/+vNyc-3_

Shop  https //stza.co/+vNyc-w

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:GreenJackets @ RiverDogs
END:VALARM
DTSTART:20180723T230500Z
DTEND:20180724T020500Z
UID:7O-BjBiq10XRXJrhNpBHdC4M@stanza.co
SUMMARY:GreenJackets @ RiverDogs
DESCRIPTION:GreenJackets @ RiverDogs\n\nFollow on MiLB First Pitch: https://stza.co/+vNyc-3_\n\nShop: https://stza.co/+vNyc-w\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144503Z
LAST-MODIFIED:20180213T144503Z
TRANSP:OPAQUE
END:VEVENT
* GreenJackets @ RiverDogs
<2018-07-24 Tue 18:05-21:05>
:PROPERTIES:
:ID:       FE2vnCR-Zeev60pul5gVN16t@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

GreenJackets @ RiverDogs GreenJackets @ RiverDogs

Follow on MiLB First Pitch  https //stza.co/+vNyd-3A

Shop  https //stza.co/+vNyd-2l

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:GreenJackets @ RiverDogs
END:VALARM
DTSTART:20180724T230500Z
DTEND:20180725T020500Z
UID:FE2vnCR-Zeev60pul5gVN16t@stanza.co
SUMMARY:GreenJackets @ RiverDogs
DESCRIPTION:GreenJackets @ RiverDogs\n\nFollow on MiLB First Pitch: https://stza.co/+vNyd-3A\n\nShop: https://stza.co/+vNyd-2l\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144503Z
LAST-MODIFIED:20180213T144503Z
TRANSP:OPAQUE
END:VEVENT
* GreenJackets @ RiverDogs
<2018-07-25 Wed 18:05-21:05>
:PROPERTIES:
:ID:       4D0PVs9amfxTU-uwWCOX4xIw@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

GreenJackets @ RiverDogs GreenJackets @ RiverDogs

Follow on MiLB First Pitch  https //stza.co/+vNye-1r

Shop  https //stza.co/+vNye-1A

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:GreenJackets @ RiverDogs
END:VALARM
DTSTART:20180725T230500Z
DTEND:20180726T020500Z
UID:4D0PVs9amfxTU-uwWCOX4xIw@stanza.co
SUMMARY:GreenJackets @ RiverDogs
DESCRIPTION:GreenJackets @ RiverDogs\n\nFollow on MiLB First Pitch: https://stza.co/+vNye-1r\n\nShop: https://stza.co/+vNye-1A\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144503Z
LAST-MODIFIED:20180213T144503Z
TRANSP:OPAQUE
END:VEVENT
* GreenJackets @ RiverDogs
<2018-07-26 Thu 18:05-21:05>
:PROPERTIES:
:ID:       Womfz5dA7S3AAq_f9OnNR8Pf@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

GreenJackets @ RiverDogs GreenJackets @ RiverDogs

Follow on MiLB First Pitch  https //stza.co/+vNyf-21

Shop  https //stza.co/+vNyf-3q

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:GreenJackets @ RiverDogs
END:VALARM
DTSTART:20180726T230500Z
DTEND:20180727T020500Z
UID:Womfz5dA7S3AAq_f9OnNR8Pf@stanza.co
SUMMARY:GreenJackets @ RiverDogs
DESCRIPTION:GreenJackets @ RiverDogs\n\nFollow on MiLB First Pitch: https://stza.co/+vNyf-21\n\nShop: https://stza.co/+vNyf-3q\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144503Z
LAST-MODIFIED:20180213T144503Z
TRANSP:OPAQUE
END:VEVENT
* GreenJackets vs. Fireflies
<2018-07-27 Fri 18:05-21:05>
:PROPERTIES:
:ID:       j7cGAoj3I_CF2cK37EvlJEqT@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

GreenJackets vs. Fireflies GreenJackets vs. Fireflies

Follow on MiLB First Pitch  https //stza.co/+xBIx-3y

Shop  https //stza.co/+xBIx-1B

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:GreenJackets vs. Fireflies
END:VALARM
DTSTART:20180727T230500Z
DTEND:20180728T020500Z
UID:j7cGAoj3I_CF2cK37EvlJEqT@stanza.co
SUMMARY:GreenJackets vs. Fireflies
DESCRIPTION:GreenJackets vs. Fireflies\n\nFollow on MiLB First Pitch: https://stza.co/+xBIx-3y\n\nShop: https://stza.co/+xBIx-1B\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144503Z
LAST-MODIFIED:20180213T144503Z
TRANSP:OPAQUE
END:VEVENT
* GreenJackets vs. Fireflies
<2018-07-28 Sat 17:05-20:05>
:PROPERTIES:
:ID:       5Vg4r43spc2HV4uLKxK2sePT@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

GreenJackets vs. Fireflies GreenJackets vs. Fireflies

Follow on MiLB First Pitch  https //stza.co/+xBIE-2D

Shop  https //stza.co/+xBIE-D

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:GreenJackets vs. Fireflies
END:VALARM
DTSTART:20180728T220500Z
DTEND:20180729T010500Z
UID:5Vg4r43spc2HV4uLKxK2sePT@stanza.co
SUMMARY:GreenJackets vs. Fireflies
DESCRIPTION:GreenJackets vs. Fireflies\n\nFollow on MiLB First Pitch: https://stza.co/+xBIE-2D\n\nShop: https://stza.co/+xBIE-D\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144503Z
LAST-MODIFIED:20180213T144503Z
TRANSP:OPAQUE
END:VEVENT
* GreenJackets vs. Fireflies
<2018-07-29 Sun 16:05-19:05>
:PROPERTIES:
:ID:       XVmRwpNnpsvT3pZoF8K3qcxi@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

GreenJackets vs. Fireflies GreenJackets vs. Fireflies

Follow on MiLB First Pitch  https //stza.co/+xBIK-3l

Shop  https //stza.co/+xBIK-v

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:GreenJackets vs. Fireflies
END:VALARM
DTSTART:20180729T210500Z
DTEND:20180730T000500Z
UID:XVmRwpNnpsvT3pZoF8K3qcxi@stanza.co
SUMMARY:GreenJackets vs. Fireflies
DESCRIPTION:GreenJackets vs. Fireflies\n\nFollow on MiLB First Pitch: https://stza.co/+xBIK-3l\n\nShop: https://stza.co/+xBIK-v\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144503Z
LAST-MODIFIED:20180213T144503Z
TRANSP:OPAQUE
END:VEVENT
* GreenJackets vs. Intimidators
<2018-07-30 Mon 18:05-21:05>
:PROPERTIES:
:ID:       1osgofoWLnz4jilkhT3KJv_z@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

GreenJackets vs. Intimidators GreenJackets vs. Intimidators

Follow on MiLB First Pitch  https //stza.co/+xBIP-2E

Shop  https //stza.co/+xBIP-1z

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:GreenJackets vs. Intimidators
END:VALARM
DTSTART:20180730T230500Z
DTEND:20180731T020500Z
UID:1osgofoWLnz4jilkhT3KJv_z@stanza.co
SUMMARY:GreenJackets vs. Intimidators
DESCRIPTION:GreenJackets vs. Intimidators\n\nFollow on MiLB First Pitch: https://stza.co/+xBIP-2E\n\nShop: https://stza.co/+xBIP-1z\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144503Z
LAST-MODIFIED:20180213T144503Z
TRANSP:OPAQUE
END:VEVENT
* GreenJackets vs. Intimidators
<2018-07-31 Tue 18:05-21:05>
:PROPERTIES:
:ID:       QyisDqKNiTZEXaGDfujcu6dU@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

GreenJackets vs. Intimidators GreenJackets vs. Intimidators

Follow on MiLB First Pitch  https //stza.co/+xBIV-1W

Shop  https //stza.co/+xBIV-3r

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:GreenJackets vs. Intimidators
END:VALARM
DTSTART:20180731T230500Z
DTEND:20180801T020500Z
UID:QyisDqKNiTZEXaGDfujcu6dU@stanza.co
SUMMARY:GreenJackets vs. Intimidators
DESCRIPTION:GreenJackets vs. Intimidators\n\nFollow on MiLB First Pitch: https://stza.co/+xBIV-1W\n\nShop: https://stza.co/+xBIV-3r\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144503Z
LAST-MODIFIED:20180213T144503Z
TRANSP:OPAQUE
END:VEVENT
* GreenJackets vs. Intimidators
<2018-08-01 Wed 18:05-21:05>
:PROPERTIES:
:ID:       p1zMy85qyyE7BFwnNm-s6JBP@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

GreenJackets vs. Intimidators GreenJackets vs. Intimidators

Follow on MiLB First Pitch  https //stza.co/+xBJ3-1o

Shop  https //stza.co/+xBJ3-N

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:GreenJackets vs. Intimidators
END:VALARM
DTSTART:20180801T230500Z
DTEND:20180802T020500Z
UID:p1zMy85qyyE7BFwnNm-s6JBP@stanza.co
SUMMARY:GreenJackets vs. Intimidators
DESCRIPTION:GreenJackets vs. Intimidators\n\nFollow on MiLB First Pitch: https://stza.co/+xBJ3-1o\n\nShop: https://stza.co/+xBJ3-N\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144503Z
LAST-MODIFIED:20180213T144503Z
TRANSP:OPAQUE
END:VEVENT
* GreenJackets @ Power
<2018-08-02 Thu 18:05-21:05>
:PROPERTIES:
:ID:       ebffcmkRFLfr9T3w7XlS7ldQ@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

GreenJackets @ Power GreenJackets @ Power

Follow on MiLB First Pitch  https //stza.co/+xJ3u-9

Shop  https //stza.co/+xJ3u-3k

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:GreenJackets @ Power
END:VALARM
DTSTART:20180802T230500Z
DTEND:20180803T020500Z
UID:ebffcmkRFLfr9T3w7XlS7ldQ@stanza.co
SUMMARY:GreenJackets @ Power
DESCRIPTION:GreenJackets @ Power\n\nFollow on MiLB First Pitch: https://stza.co/+xJ3u-9\n\nShop: https://stza.co/+xJ3u-3k\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144503Z
LAST-MODIFIED:20180213T144503Z
TRANSP:OPAQUE
END:VEVENT
* GreenJackets @ Power
<2018-08-03 Fri 18:05-21:05>
:PROPERTIES:
:ID:       uDHqzUdvHie3XN_xCr5ixWsp@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

GreenJackets @ Power GreenJackets @ Power

Follow on MiLB First Pitch  https //stza.co/+xJ3v-3l

Shop  https //stza.co/+xJ3v-1t

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:GreenJackets @ Power
END:VALARM
DTSTART:20180803T230500Z
DTEND:20180804T020500Z
UID:uDHqzUdvHie3XN_xCr5ixWsp@stanza.co
SUMMARY:GreenJackets @ Power
DESCRIPTION:GreenJackets @ Power\n\nFollow on MiLB First Pitch: https://stza.co/+xJ3v-3l\n\nShop: https://stza.co/+xJ3v-1t\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144503Z
LAST-MODIFIED:20180213T144503Z
TRANSP:OPAQUE
END:VEVENT
* GreenJackets @ Power
<2018-08-04 Sat 17:05-20:05>
:PROPERTIES:
:ID:       1iDGJQcS0UvLHO1YjFbbnLL3@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

GreenJackets @ Power GreenJackets @ Power

Follow on MiLB First Pitch  https //stza.co/+xJ3w-24

Shop  https //stza.co/+xJ3w-2E

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:GreenJackets @ Power
END:VALARM
DTSTART:20180804T220500Z
DTEND:20180805T010500Z
UID:1iDGJQcS0UvLHO1YjFbbnLL3@stanza.co
SUMMARY:GreenJackets @ Power
DESCRIPTION:GreenJackets @ Power\n\nFollow on MiLB First Pitch: https://stza.co/+xJ3w-24\n\nShop: https://stza.co/+xJ3w-2E\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144503Z
LAST-MODIFIED:20180213T144503Z
TRANSP:OPAQUE
END:VEVENT
* GreenJackets @ Power
<2018-08-05 Sun 13:05-16:05>
:PROPERTIES:
:ID:       DD_Jfpj3LZyOioQr8cPSuPk_@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

GreenJackets @ Power GreenJackets @ Power

Follow on MiLB First Pitch  https //stza.co/+xJ3x-3p

Shop  https //stza.co/+xJ3x-3i

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:GreenJackets @ Power
END:VALARM
DTSTART:20180805T180500Z
DTEND:20180805T210500Z
UID:DD_Jfpj3LZyOioQr8cPSuPk_@stanza.co
SUMMARY:GreenJackets @ Power
DESCRIPTION:GreenJackets @ Power\n\nFollow on MiLB First Pitch: https://stza.co/+xJ3x-3p\n\nShop: https://stza.co/+xJ3x-3i\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144503Z
LAST-MODIFIED:20180213T144503Z
TRANSP:OPAQUE
END:VEVENT
* GreenJackets vs. Suns
<2018-08-07 Tue 18:05-21:05>
:PROPERTIES:
:ID:       x8FQ9cHisdTKeDX3TXP5_jgj@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

GreenJackets vs. Suns GreenJackets vs. Suns

Follow on MiLB First Pitch  https //stza.co/+xBJ8-3i

Shop  https //stza.co/+xBJ8-3A

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:GreenJackets vs. Suns
END:VALARM
DTSTART:20180807T230500Z
DTEND:20180808T020500Z
UID:x8FQ9cHisdTKeDX3TXP5_jgj@stanza.co
SUMMARY:GreenJackets vs. Suns
DESCRIPTION:GreenJackets vs. Suns\n\nFollow on MiLB First Pitch: https://stza.co/+xBJ8-3i\n\nShop: https://stza.co/+xBJ8-3A\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144503Z
LAST-MODIFIED:20180213T144503Z
TRANSP:OPAQUE
END:VEVENT
* GreenJackets vs. Suns
<2018-08-08 Wed 18:05-21:05>
:PROPERTIES:
:ID:       hhhsUwrWVimRODpwdcN5S6aE@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

GreenJackets vs. Suns GreenJackets vs. Suns

Follow on MiLB First Pitch  https //stza.co/+xBJf-2U

Shop  https //stza.co/+xBJf-2y

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:GreenJackets vs. Suns
END:VALARM
DTSTART:20180808T230500Z
DTEND:20180809T020500Z
UID:hhhsUwrWVimRODpwdcN5S6aE@stanza.co
SUMMARY:GreenJackets vs. Suns
DESCRIPTION:GreenJackets vs. Suns\n\nFollow on MiLB First Pitch: https://stza.co/+xBJf-2U\n\nShop: https://stza.co/+xBJf-2y\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144503Z
LAST-MODIFIED:20180213T144503Z
TRANSP:OPAQUE
END:VEVENT
* GreenJackets vs. Suns
<2018-08-09 Thu 18:05-21:05>
:PROPERTIES:
:ID:       5sCcHdb3--TDlHynKPWutkMF@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

GreenJackets vs. Suns GreenJackets vs. Suns

Follow on MiLB First Pitch  https //stza.co/+xBJl-3j

Shop  https //stza.co/+xBJl-2p

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:GreenJackets vs. Suns
END:VALARM
DTSTART:20180809T230500Z
DTEND:20180810T020500Z
UID:5sCcHdb3--TDlHynKPWutkMF@stanza.co
SUMMARY:GreenJackets vs. Suns
DESCRIPTION:GreenJackets vs. Suns\n\nFollow on MiLB First Pitch: https://stza.co/+xBJl-3j\n\nShop: https://stza.co/+xBJl-2p\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144503Z
LAST-MODIFIED:20180213T144503Z
TRANSP:OPAQUE
END:VEVENT
* GreenJackets vs. Drive
<2018-08-10 Fri 18:05-21:05>
:PROPERTIES:
:ID:       6iMtcK2hOoI--SIp956GzS-4@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

GreenJackets vs. Drive GreenJackets vs. Drive

Follow on MiLB First Pitch  https //stza.co/+xBJs-b

Shop  https //stza.co/+xBJs-y

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:GreenJackets vs. Drive
END:VALARM
DTSTART:20180810T230500Z
DTEND:20180811T020500Z
UID:6iMtcK2hOoI--SIp956GzS-4@stanza.co
SUMMARY:GreenJackets vs. Drive
DESCRIPTION:GreenJackets vs. Drive\n\nFollow on MiLB First Pitch: https://stza.co/+xBJs-b\n\nShop: https://stza.co/+xBJs-y\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144503Z
LAST-MODIFIED:20180213T144503Z
TRANSP:OPAQUE
END:VEVENT
* GreenJackets vs. Drive
<2018-08-11 Sat 17:05-20:05>
:PROPERTIES:
:ID:       kG_-P6V4e6A6VussFSmIdUV3@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

GreenJackets vs. Drive GreenJackets vs. Drive

Follow on MiLB First Pitch  https //stza.co/+xBJy-i

Shop  https //stza.co/+xBJy-2j

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:GreenJackets vs. Drive
END:VALARM
DTSTART:20180811T220500Z
DTEND:20180812T010500Z
UID:kG_-P6V4e6A6VussFSmIdUV3@stanza.co
SUMMARY:GreenJackets vs. Drive
DESCRIPTION:GreenJackets vs. Drive\n\nFollow on MiLB First Pitch: https://stza.co/+xBJy-i\n\nShop: https://stza.co/+xBJy-2j\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144503Z
LAST-MODIFIED:20180213T144503Z
TRANSP:OPAQUE
END:VEVENT
* GreenJackets vs. Drive
<2018-08-12 Sun 16:05-19:05>
:PROPERTIES:
:ID:       481tz0Ka-Sv_yr-qFSQ6Slfx@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

GreenJackets vs. Drive GreenJackets vs. Drive

Follow on MiLB First Pitch  https //stza.co/+xBJE-33

Shop  https //stza.co/+xBJE-2A

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:GreenJackets vs. Drive
END:VALARM
DTSTART:20180812T210500Z
DTEND:20180813T000500Z
UID:481tz0Ka-Sv_yr-qFSQ6Slfx@stanza.co
SUMMARY:GreenJackets vs. Drive
DESCRIPTION:GreenJackets vs. Drive\n\nFollow on MiLB First Pitch: https://stza.co/+xBJE-33\n\nShop: https://stza.co/+xBJE-2A\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144503Z
LAST-MODIFIED:20180213T144503Z
TRANSP:OPAQUE
END:VEVENT
* GreenJackets vs. Drive
<2018-08-13 Mon 18:05-21:05>
:PROPERTIES:
:ID:       Rz_2mzuJq35io2pO4wW_iEhE@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

GreenJackets vs. Drive GreenJackets vs. Drive

Follow on MiLB First Pitch  https //stza.co/+xBJK-34

Shop  https //stza.co/+xBJK-1d

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:GreenJackets vs. Drive
END:VALARM
DTSTART:20180813T230500Z
DTEND:20180814T020500Z
UID:Rz_2mzuJq35io2pO4wW_iEhE@stanza.co
SUMMARY:GreenJackets vs. Drive
DESCRIPTION:GreenJackets vs. Drive\n\nFollow on MiLB First Pitch: https://stza.co/+xBJK-34\n\nShop: https://stza.co/+xBJK-1d\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144503Z
LAST-MODIFIED:20180213T144503Z
TRANSP:OPAQUE
END:VEVENT
* GreenJackets @ Intimidators
<2018-08-15 Wed 18:05-21:05>
:PROPERTIES:
:ID:       sHMpI7eOsMbqv74zV_7i0GVa@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

GreenJackets @ Intimidators GreenJackets @ Intimidators

Follow on MiLB First Pitch  https //stza.co/+wIAA-M

Shop  https //stza.co/+wIAA-N

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:GreenJackets @ Intimidators
END:VALARM
DTSTART:20180815T230500Z
DTEND:20180816T020500Z
UID:sHMpI7eOsMbqv74zV_7i0GVa@stanza.co
SUMMARY:GreenJackets @ Intimidators
DESCRIPTION:GreenJackets @ Intimidators\n\nFollow on MiLB First Pitch: https://stza.co/+wIAA-M\n\nShop: https://stza.co/+wIAA-N\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144503Z
LAST-MODIFIED:20180213T144503Z
TRANSP:OPAQUE
END:VEVENT
* GreenJackets @ Intimidators
<2018-08-16 Thu 18:05-21:05>
:PROPERTIES:
:ID:       MninZY33CXVqOEwhA2AH_9-K@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

GreenJackets @ Intimidators GreenJackets @ Intimidators

Follow on MiLB First Pitch  https //stza.co/+wIAD-2x

Shop  https //stza.co/+wIAD-1g

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:GreenJackets @ Intimidators
END:VALARM
DTSTART:20180816T230500Z
DTEND:20180817T020500Z
UID:MninZY33CXVqOEwhA2AH_9-K@stanza.co
SUMMARY:GreenJackets @ Intimidators
DESCRIPTION:GreenJackets @ Intimidators\n\nFollow on MiLB First Pitch: https://stza.co/+wIAD-2x\n\nShop: https://stza.co/+wIAD-1g\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144503Z
LAST-MODIFIED:20180213T144503Z
TRANSP:OPAQUE
END:VEVENT
* GreenJackets @ Intimidators
<2018-08-17 Fri 18:05-21:05>
:PROPERTIES:
:ID:       QJ9bibHyi_bPmOthZLNm2UXZ@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

GreenJackets @ Intimidators GreenJackets @ Intimidators

Follow on MiLB First Pitch  https //stza.co/+wIAE-v

Shop  https //stza.co/+wIAE-1W

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:GreenJackets @ Intimidators
END:VALARM
DTSTART:20180817T230500Z
DTEND:20180818T020500Z
UID:QJ9bibHyi_bPmOthZLNm2UXZ@stanza.co
SUMMARY:GreenJackets @ Intimidators
DESCRIPTION:GreenJackets @ Intimidators\n\nFollow on MiLB First Pitch: https://stza.co/+wIAE-v\n\nShop: https://stza.co/+wIAE-1W\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144503Z
LAST-MODIFIED:20180213T144503Z
TRANSP:OPAQUE
END:VEVENT
* GreenJackets @ Tourists
<2018-08-18 Sat 17:05-20:05>
:PROPERTIES:
:ID:       UMt1m_WNutRu-4doczsi9sT9@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

GreenJackets @ Tourists GreenJackets @ Tourists

Follow on MiLB First Pitch  https //stza.co/+vNvV-2E

Shop  https //stza.co/+vNvV-2j

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:GreenJackets @ Tourists
END:VALARM
DTSTART:20180818T220500Z
DTEND:20180819T010500Z
UID:UMt1m_WNutRu-4doczsi9sT9@stanza.co
SUMMARY:GreenJackets @ Tourists
DESCRIPTION:GreenJackets @ Tourists\n\nFollow on MiLB First Pitch: https://stza.co/+vNvV-2E\n\nShop: https://stza.co/+vNvV-2j\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144503Z
LAST-MODIFIED:20180213T144503Z
TRANSP:OPAQUE
END:VEVENT
* GreenJackets @ Tourists
<2018-08-19 Sun 13:05-16:05>
:PROPERTIES:
:ID:       6JM3ntbP38aL-c3jDOW-H5Hl@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

GreenJackets @ Tourists GreenJackets @ Tourists

Follow on MiLB First Pitch  https //stza.co/+vNvW-3D

Shop  https //stza.co/+vNvW-1z

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:GreenJackets @ Tourists
END:VALARM
DTSTART:20180819T180500Z
DTEND:20180819T210500Z
UID:6JM3ntbP38aL-c3jDOW-H5Hl@stanza.co
SUMMARY:GreenJackets @ Tourists
DESCRIPTION:GreenJackets @ Tourists\n\nFollow on MiLB First Pitch: https://stza.co/+vNvW-3D\n\nShop: https://stza.co/+vNvW-1z\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144503Z
LAST-MODIFIED:20180213T144503Z
TRANSP:OPAQUE
END:VEVENT
* GreenJackets @ Tourists
<2018-08-20 Mon 18:05-21:05>
:PROPERTIES:
:ID:       ZnRjMMqHSWCoBkgIBVHFdHor@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

GreenJackets @ Tourists GreenJackets @ Tourists

Follow on MiLB First Pitch  https //stza.co/+vNvX-3t

Shop  https //stza.co/+vNvX-y

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:GreenJackets @ Tourists
END:VALARM
DTSTART:20180820T230500Z
DTEND:20180821T020500Z
UID:ZnRjMMqHSWCoBkgIBVHFdHor@stanza.co
SUMMARY:GreenJackets @ Tourists
DESCRIPTION:GreenJackets @ Tourists\n\nFollow on MiLB First Pitch: https://stza.co/+vNvX-3t\n\nShop: https://stza.co/+vNvX-y\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144503Z
LAST-MODIFIED:20180213T144503Z
TRANSP:OPAQUE
END:VEVENT
* GreenJackets @ Tourists
<2018-08-21 Tue 18:05-21:05>
:PROPERTIES:
:ID:       RUXzUMpAmfK_UOJYp07uCF48@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

GreenJackets @ Tourists GreenJackets @ Tourists

Follow on MiLB First Pitch  https //stza.co/+vNvY-2d

Shop  https //stza.co/+vNvY-1d

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:GreenJackets @ Tourists
END:VALARM
DTSTART:20180821T230500Z
DTEND:20180822T020500Z
UID:RUXzUMpAmfK_UOJYp07uCF48@stanza.co
SUMMARY:GreenJackets @ Tourists
DESCRIPTION:GreenJackets @ Tourists\n\nFollow on MiLB First Pitch: https://stza.co/+vNvY-2d\n\nShop: https://stza.co/+vNvY-1d\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144503Z
LAST-MODIFIED:20180213T144503Z
TRANSP:OPAQUE
END:VEVENT
* GreenJackets vs. Intimidators
<2018-08-23 Thu 18:05-21:05>
:PROPERTIES:
:ID:       posyFD9DPg9oNhSYi7f7YXXC@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

GreenJackets vs. Intimidators GreenJackets vs. Intimidators

Follow on MiLB First Pitch  https //stza.co/+xBJR-2O

Shop  https //stza.co/+xBJR-u

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:GreenJackets vs. Intimidators
END:VALARM
DTSTART:20180823T230500Z
DTEND:20180824T020500Z
UID:posyFD9DPg9oNhSYi7f7YXXC@stanza.co
SUMMARY:GreenJackets vs. Intimidators
DESCRIPTION:GreenJackets vs. Intimidators\n\nFollow on MiLB First Pitch: https://stza.co/+xBJR-2O\n\nShop: https://stza.co/+xBJR-u\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144503Z
LAST-MODIFIED:20180213T144503Z
TRANSP:OPAQUE
END:VEVENT
* GreenJackets vs. Intimidators
<2018-08-24 Fri 18:05-21:05>
:PROPERTIES:
:ID:       Jt4mJcZMAf-SlEZohe8vYnpX@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

GreenJackets vs. Intimidators GreenJackets vs. Intimidators

Follow on MiLB First Pitch  https //stza.co/+xBJX-1A

Shop  https //stza.co/+xBJX-3I

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:GreenJackets vs. Intimidators
END:VALARM
DTSTART:20180824T230500Z
DTEND:20180825T020500Z
UID:Jt4mJcZMAf-SlEZohe8vYnpX@stanza.co
SUMMARY:GreenJackets vs. Intimidators
DESCRIPTION:GreenJackets vs. Intimidators\n\nFollow on MiLB First Pitch: https://stza.co/+xBJX-1A\n\nShop: https://stza.co/+xBJX-3I\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144503Z
LAST-MODIFIED:20180213T144503Z
TRANSP:OPAQUE
END:VEVENT
* GreenJackets vs. Intimidators
<2018-08-25 Sat 17:05-20:05>
:PROPERTIES:
:ID:       ufmiWznK4QU8sqmSDbVKqF_9@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

GreenJackets vs. Intimidators GreenJackets vs. Intimidators

Follow on MiLB First Pitch  https //stza.co/+xBK2-1t

Shop  https //stza.co/+xBK2-N

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:GreenJackets vs. Intimidators
END:VALARM
DTSTART:20180825T220500Z
DTEND:20180826T010500Z
UID:ufmiWznK4QU8sqmSDbVKqF_9@stanza.co
SUMMARY:GreenJackets vs. Intimidators
DESCRIPTION:GreenJackets vs. Intimidators\n\nFollow on MiLB First Pitch: https://stza.co/+xBK2-1t\n\nShop: https://stza.co/+xBK2-N\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144503Z
LAST-MODIFIED:20180213T144503Z
TRANSP:OPAQUE
END:VEVENT
* GreenJackets vs. Intimidators
<2018-08-26 Sun 16:05-19:05>
:PROPERTIES:
:ID:       dxEVZ77OmAVYA61PQnSSe_S0@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

GreenJackets vs. Intimidators GreenJackets vs. Intimidators

Follow on MiLB First Pitch  https //stza.co/+xBK8-1f

Shop  https //stza.co/+xBK8-3g

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:GreenJackets vs. Intimidators
END:VALARM
DTSTART:20180826T210500Z
DTEND:20180827T000500Z
UID:dxEVZ77OmAVYA61PQnSSe_S0@stanza.co
SUMMARY:GreenJackets vs. Intimidators
DESCRIPTION:GreenJackets vs. Intimidators\n\nFollow on MiLB First Pitch: https://stza.co/+xBK8-1f\n\nShop: https://stza.co/+xBK8-3g\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144503Z
LAST-MODIFIED:20180213T144503Z
TRANSP:OPAQUE
END:VEVENT
* GreenJackets @ Legends
<2018-08-27 Mon 18:05-21:05>
:PROPERTIES:
:ID:       t8u9TG8iFykjtj8t--QGexXj@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

GreenJackets @ Legends GreenJackets @ Legends

Follow on MiLB First Pitch  https //stza.co/+xAVb-q

Shop  https //stza.co/+xAVb-3j

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:GreenJackets @ Legends
END:VALARM
DTSTART:20180827T230500Z
DTEND:20180828T020500Z
UID:t8u9TG8iFykjtj8t--QGexXj@stanza.co
SUMMARY:GreenJackets @ Legends
DESCRIPTION:GreenJackets @ Legends\n\nFollow on MiLB First Pitch: https://stza.co/+xAVb-q\n\nShop: https://stza.co/+xAVb-3j\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144503Z
LAST-MODIFIED:20180213T144503Z
TRANSP:OPAQUE
END:VEVENT
* GreenJackets @ Legends
<2018-08-28 Tue 18:05-21:05>
:PROPERTIES:
:ID:       aoR_gTEjWhJUBkJ4iAWg_d3d@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

GreenJackets @ Legends GreenJackets @ Legends

Follow on MiLB First Pitch  https //stza.co/+xAVc-M

Shop  https //stza.co/+xAVc-31

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:GreenJackets @ Legends
END:VALARM
DTSTART:20180828T230500Z
DTEND:20180829T020500Z
UID:aoR_gTEjWhJUBkJ4iAWg_d3d@stanza.co
SUMMARY:GreenJackets @ Legends
DESCRIPTION:GreenJackets @ Legends\n\nFollow on MiLB First Pitch: https://stza.co/+xAVc-M\n\nShop: https://stza.co/+xAVc-31\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144503Z
LAST-MODIFIED:20180213T144503Z
TRANSP:OPAQUE
END:VEVENT
* GreenJackets @ Legends
<2018-08-29 Wed 12:05-15:05>
:PROPERTIES:
:ID:       yKXWZs2gS9P-VjFr7NUC-Wlk@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

GreenJackets @ Legends GreenJackets @ Legends

Follow on MiLB First Pitch  https //stza.co/+xAVd-2X

Shop  https //stza.co/+xAVd-21

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:GreenJackets @ Legends
END:VALARM
DTSTART:20180829T170500Z
DTEND:20180829T200500Z
UID:yKXWZs2gS9P-VjFr7NUC-Wlk@stanza.co
SUMMARY:GreenJackets @ Legends
DESCRIPTION:GreenJackets @ Legends\n\nFollow on MiLB First Pitch: https://stza.co/+xAVd-2X\n\nShop: https://stza.co/+xAVd-21\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144503Z
LAST-MODIFIED:20180213T144503Z
TRANSP:OPAQUE
END:VEVENT
* GreenJackets @ Legends
<2018-08-30 Thu 18:05-21:05>
:PROPERTIES:
:ID:       HGrLgDKRQW86zS85BWXa71_l@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

GreenJackets @ Legends GreenJackets @ Legends

Follow on MiLB First Pitch  https //stza.co/+xAVe-1L

Shop  https //stza.co/+xAVe-13

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:GreenJackets @ Legends
END:VALARM
DTSTART:20180830T230500Z
DTEND:20180831T020500Z
UID:HGrLgDKRQW86zS85BWXa71_l@stanza.co
SUMMARY:GreenJackets @ Legends
DESCRIPTION:GreenJackets @ Legends\n\nFollow on MiLB First Pitch: https://stza.co/+xAVe-1L\n\nShop: https://stza.co/+xAVe-13\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144503Z
LAST-MODIFIED:20180213T144503Z
TRANSP:OPAQUE
END:VEVENT
* GreenJackets vs. Fireflies
<2018-08-31 Fri 18:05-21:05>
:PROPERTIES:
:ID:       yNlBmvLvoNANWwsE2XwmT-pu@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

GreenJackets vs. Fireflies GreenJackets vs. Fireflies

Follow on MiLB First Pitch  https //stza.co/+xBKe-2v

Shop  https //stza.co/+xBKe-2J

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:GreenJackets vs. Fireflies
END:VALARM
DTSTART:20180831T230500Z
DTEND:20180901T020500Z
UID:yNlBmvLvoNANWwsE2XwmT-pu@stanza.co
SUMMARY:GreenJackets vs. Fireflies
DESCRIPTION:GreenJackets vs. Fireflies\n\nFollow on MiLB First Pitch: https://stza.co/+xBKe-2v\n\nShop: https://stza.co/+xBKe-2J\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144503Z
LAST-MODIFIED:20180213T144503Z
TRANSP:OPAQUE
END:VEVENT
* GreenJackets vs. Fireflies
<2018-09-01 Sat 17:05-20:05>
:PROPERTIES:
:ID:       XN9yygGQfIeLOZ8Hf5vLyRqm@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

GreenJackets vs. Fireflies GreenJackets vs. Fireflies

Follow on MiLB First Pitch  https //stza.co/+xBKk-2E

Shop  https //stza.co/+xBKk-1b

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:GreenJackets vs. Fireflies
END:VALARM
DTSTART:20180901T220500Z
DTEND:20180902T010500Z
UID:XN9yygGQfIeLOZ8Hf5vLyRqm@stanza.co
SUMMARY:GreenJackets vs. Fireflies
DESCRIPTION:GreenJackets vs. Fireflies\n\nFollow on MiLB First Pitch: https://stza.co/+xBKk-2E\n\nShop: https://stza.co/+xBKk-1b\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144503Z
LAST-MODIFIED:20180213T144503Z
TRANSP:OPAQUE
END:VEVENT
* GreenJackets vs. Fireflies
<2018-09-02 Sun 17:35-20:35>
:PROPERTIES:
:ID:       K01hBvX4OgCdqH-4QbE7KGwu@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

GreenJackets vs. Fireflies GreenJackets vs. Fireflies

Follow on MiLB First Pitch  https //stza.co/+xBKq-B

Shop  https //stza.co/+xBKq-G

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:GreenJackets vs. Fireflies
END:VALARM
DTSTART:20180902T223500Z
DTEND:20180903T013500Z
UID:K01hBvX4OgCdqH-4QbE7KGwu@stanza.co
SUMMARY:GreenJackets vs. Fireflies
DESCRIPTION:GreenJackets vs. Fireflies\n\nFollow on MiLB First Pitch: https://stza.co/+xBKq-B\n\nShop: https://stza.co/+xBKq-G\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144503Z
LAST-MODIFIED:20180213T144503Z
TRANSP:OPAQUE
END:VEVENT
* GreenJackets vs. Fireflies
<2018-09-03 Mon 13:05-16:05>
:PROPERTIES:
:ID:       IYcXix7T3DMIrDQau3yXibfl@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

GreenJackets vs. Fireflies GreenJackets vs. Fireflies

Follow on MiLB First Pitch  https //stza.co/+xAUR-3T

Shop  https //stza.co/+xAUR-30

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:GreenJackets vs. Fireflies
END:VALARM
DTSTART:20180903T180500Z
DTEND:20180903T210500Z
UID:IYcXix7T3DMIrDQau3yXibfl@stanza.co
SUMMARY:GreenJackets vs. Fireflies
DESCRIPTION:GreenJackets vs. Fireflies\n\nFollow on MiLB First Pitch: https://stza.co/+xAUR-3T\n\nShop: https://stza.co/+xAUR-30\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144503Z
LAST-MODIFIED:20180213T144503Z
TRANSP:OPAQUE
END:VEVENT
