#+TITLE:       Main Google calendar entries
#+AUTHOR:      Eric S Fraga
#+EMAIL:       e.fraga@ucl.ac.uk
#+DESCRIPTION: converted using the ical2org awk script
#+CATEGORY:    google
#+STARTUP:     hidestars
#+STARTUP:     overview

* COMMENT original iCal preamble

* Drive @ Power
<2018-04-05 Thu 18:05-21:05>
:PROPERTIES:
:ID:       EJfwBr5Pe4euVW33Ha5-Ka8_@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Drive @ Power Drive @ Power

Follow on MiLB First Pitch  https //stza.co/+xJ3M-3q

Shop  https //stza.co/+xJ3M-s

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Drive @ Power
END:VALARM
DTSTART:20180405T230500Z
DTEND:20180406T020500Z
UID:EJfwBr5Pe4euVW33Ha5-Ka8_@stanza.co
SUMMARY:Drive @ Power
DESCRIPTION:Drive @ Power\n\nFollow on MiLB First Pitch: https://stza.co/+xJ3M-3q\n\nShop: https://stza.co/+xJ3M-s\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144530Z
LAST-MODIFIED:20180213T144530Z
TRANSP:OPAQUE
END:VEVENT
* Drive @ Power
<2018-04-06 Fri 18:05-21:05>
:PROPERTIES:
:ID:       Lu7e31P4GFpN0cYQT7uubIye@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Drive @ Power Drive @ Power

Follow on MiLB First Pitch  https //stza.co/+xJ3N-2j

Shop  https //stza.co/+xJ3N-f

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Drive @ Power
END:VALARM
DTSTART:20180406T230500Z
DTEND:20180407T020500Z
UID:Lu7e31P4GFpN0cYQT7uubIye@stanza.co
SUMMARY:Drive @ Power
DESCRIPTION:Drive @ Power\n\nFollow on MiLB First Pitch: https://stza.co/+xJ3N-2j\n\nShop: https://stza.co/+xJ3N-f\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144530Z
LAST-MODIFIED:20180213T144530Z
TRANSP:OPAQUE
END:VEVENT
* Drive @ Power
<2018-04-07 Sat 13:05-16:05>
:PROPERTIES:
:ID:       qIHYD4mVnS0qulbP_Y0ZXE6-@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Drive @ Power Drive @ Power

Follow on MiLB First Pitch  https //stza.co/+xJ3O-2e

Shop  https //stza.co/+xJ3O-3D

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Drive @ Power
END:VALARM
DTSTART:20180407T180500Z
DTEND:20180407T210500Z
UID:qIHYD4mVnS0qulbP_Y0ZXE6-@stanza.co
SUMMARY:Drive @ Power
DESCRIPTION:Drive @ Power\n\nFollow on MiLB First Pitch: https://stza.co/+xJ3O-2e\n\nShop: https://stza.co/+xJ3O-3D\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144530Z
LAST-MODIFIED:20180213T144530Z
TRANSP:OPAQUE
END:VEVENT
* Drive @ Power
<2018-04-08 Sun 13:05-16:05>
:PROPERTIES:
:ID:       6nv6gw2cHouhQXkklL507-o7@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Drive @ Power Drive @ Power

Follow on MiLB First Pitch  https //stza.co/+xJ3P-2q

Shop  https //stza.co/+xJ3P-i

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Drive @ Power
END:VALARM
DTSTART:20180408T180500Z
DTEND:20180408T210500Z
UID:6nv6gw2cHouhQXkklL507-o7@stanza.co
SUMMARY:Drive @ Power
DESCRIPTION:Drive @ Power\n\nFollow on MiLB First Pitch: https://stza.co/+xJ3P-2q\n\nShop: https://stza.co/+xJ3P-i\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144530Z
LAST-MODIFIED:20180213T144530Z
TRANSP:OPAQUE
END:VEVENT
* Drive @ Legends
<2018-04-09 Mon 18:05-21:05>
:PROPERTIES:
:ID:       GxjVwcr9xhoNzsM1uIKQUtxe@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Drive @ Legends Drive @ Legends

Follow on MiLB First Pitch  https //stza.co/+xB3K-16

Shop  https //stza.co/+xB3K-3f

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Drive @ Legends
END:VALARM
DTSTART:20180409T230500Z
DTEND:20180410T020500Z
UID:GxjVwcr9xhoNzsM1uIKQUtxe@stanza.co
SUMMARY:Drive @ Legends
DESCRIPTION:Drive @ Legends\n\nFollow on MiLB First Pitch: https://stza.co/+xB3K-16\n\nShop: https://stza.co/+xB3K-3f\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144530Z
LAST-MODIFIED:20180213T144530Z
TRANSP:OPAQUE
END:VEVENT
* Drive @ Legends
<2018-04-10 Tue 18:05-21:05>
:PROPERTIES:
:ID:       KXXqmSZZd07oxLT4LRIMTKU-@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Drive @ Legends Drive @ Legends

Follow on MiLB First Pitch  https //stza.co/+xB3L-2q

Shop  https //stza.co/+xB3L-H

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Drive @ Legends
END:VALARM
DTSTART:20180410T230500Z
DTEND:20180411T020500Z
UID:KXXqmSZZd07oxLT4LRIMTKU-@stanza.co
SUMMARY:Drive @ Legends
DESCRIPTION:Drive @ Legends\n\nFollow on MiLB First Pitch: https://stza.co/+xB3L-2q\n\nShop: https://stza.co/+xB3L-H\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144530Z
LAST-MODIFIED:20180213T144530Z
TRANSP:OPAQUE
END:VEVENT
* Drive @ Legends
<2018-04-11 Wed 09:35-12:35>
:PROPERTIES:
:ID:       6rlWYUOI_SNjyoeXWssokOQz@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Drive @ Legends Drive @ Legends

Follow on MiLB First Pitch  https //stza.co/+xB3M-2r

Shop  https //stza.co/+xB3M-6

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Drive @ Legends
END:VALARM
DTSTART:20180411T143500Z
DTEND:20180411T173500Z
UID:6rlWYUOI_SNjyoeXWssokOQz@stanza.co
SUMMARY:Drive @ Legends
DESCRIPTION:Drive @ Legends\n\nFollow on MiLB First Pitch: https://stza.co/+xB3M-2r\n\nShop: https://stza.co/+xB3M-6\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144530Z
LAST-MODIFIED:20180213T144530Z
TRANSP:OPAQUE
END:VEVENT
* Drive vs. Braves
<2018-04-12 Thu 18:05-21:05>
:PROPERTIES:
:ID:       ZKkwcgGzl1JQPKsq8G4ZL4PY@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Drive vs. Braves Drive vs. Braves

Follow on MiLB First Pitch  https //stza.co/+xGBv-1x

Shop  https //stza.co/+xGBv-f

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Drive vs. Braves
END:VALARM
DTSTART:20180412T230500Z
DTEND:20180413T020500Z
UID:ZKkwcgGzl1JQPKsq8G4ZL4PY@stanza.co
SUMMARY:Drive vs. Braves
DESCRIPTION:Drive vs. Braves\n\nFollow on MiLB First Pitch: https://stza.co/+xGBv-1x\n\nShop: https://stza.co/+xGBv-f\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144530Z
LAST-MODIFIED:20180213T144530Z
TRANSP:OPAQUE
END:VEVENT
* Drive vs. Braves
<2018-04-13 Fri 18:05-21:05>
:PROPERTIES:
:ID:       xoswOPu0j6JuEmL-6vRUmwGK@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Drive vs. Braves Drive vs. Braves

Follow on MiLB First Pitch  https //stza.co/+xGBw-2l

Shop  https //stza.co/+xGBw-1$

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Drive vs. Braves
END:VALARM
DTSTART:20180413T230500Z
DTEND:20180414T020500Z
UID:xoswOPu0j6JuEmL-6vRUmwGK@stanza.co
SUMMARY:Drive vs. Braves
DESCRIPTION:Drive vs. Braves\n\nFollow on MiLB First Pitch: https://stza.co/+xGBw-2l\n\nShop: https://stza.co/+xGBw-1$\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144530Z
LAST-MODIFIED:20180213T144530Z
TRANSP:OPAQUE
END:VEVENT
* Drive vs. Braves
<2018-04-14 Sat 18:05-21:05>
:PROPERTIES:
:ID:       YfVqhKVnGTv4JlrhAx6ZadiL@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Drive vs. Braves Drive vs. Braves

Follow on MiLB First Pitch  https //stza.co/+xGBz-2_

Shop  https //stza.co/+xGBz-2l

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Drive vs. Braves
END:VALARM
DTSTART:20180414T230500Z
DTEND:20180415T020500Z
UID:YfVqhKVnGTv4JlrhAx6ZadiL@stanza.co
SUMMARY:Drive vs. Braves
DESCRIPTION:Drive vs. Braves\n\nFollow on MiLB First Pitch: https://stza.co/+xGBz-2_\n\nShop: https://stza.co/+xGBz-2l\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144530Z
LAST-MODIFIED:20180213T144530Z
TRANSP:OPAQUE
END:VEVENT
* Drive vs. Braves
<2018-04-15 Sun 15:05-18:05>
:PROPERTIES:
:ID:       QsIqLsMATxaLCpI-NhUGHAaD@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Drive vs. Braves Drive vs. Braves

Follow on MiLB First Pitch  https //stza.co/+xGBA-V

Shop  https //stza.co/+xGBA-i

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Drive vs. Braves
END:VALARM
DTSTART:20180415T200500Z
DTEND:20180415T230500Z
UID:QsIqLsMATxaLCpI-NhUGHAaD@stanza.co
SUMMARY:Drive vs. Braves
DESCRIPTION:Drive vs. Braves\n\nFollow on MiLB First Pitch: https://stza.co/+xGBA-V\n\nShop: https://stza.co/+xGBA-i\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144530Z
LAST-MODIFIED:20180213T144530Z
TRANSP:OPAQUE
END:VEVENT
* Drive vs. Fireflies
<2018-04-16 Mon 18:05-21:05>
:PROPERTIES:
:ID:       unUmzMJjpLzvhPjbpsNQITS-@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Drive vs. Fireflies Drive vs. Fireflies

Follow on MiLB First Pitch  https //stza.co/+xGBD-1G

Shop  https //stza.co/+xGBD-1S

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Drive vs. Fireflies
END:VALARM
DTSTART:20180416T230500Z
DTEND:20180417T020500Z
UID:unUmzMJjpLzvhPjbpsNQITS-@stanza.co
SUMMARY:Drive vs. Fireflies
DESCRIPTION:Drive vs. Fireflies\n\nFollow on MiLB First Pitch: https://stza.co/+xGBD-1G\n\nShop: https://stza.co/+xGBD-1S\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144530Z
LAST-MODIFIED:20180213T144530Z
TRANSP:OPAQUE
END:VEVENT
* Drive vs. Fireflies
<2018-04-17 Tue 18:05-21:05>
:PROPERTIES:
:ID:       YjcPVzRhJv-US2RFgZZj0XUs@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Drive vs. Fireflies Drive vs. Fireflies

Follow on MiLB First Pitch  https //stza.co/+xGBG-v

Shop  https //stza.co/+xGBG-s

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Drive vs. Fireflies
END:VALARM
DTSTART:20180417T230500Z
DTEND:20180418T020500Z
UID:YjcPVzRhJv-US2RFgZZj0XUs@stanza.co
SUMMARY:Drive vs. Fireflies
DESCRIPTION:Drive vs. Fireflies\n\nFollow on MiLB First Pitch: https://stza.co/+xGBG-v\n\nShop: https://stza.co/+xGBG-s\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144530Z
LAST-MODIFIED:20180213T144530Z
TRANSP:OPAQUE
END:VEVENT
* Drive vs. Fireflies
<2018-04-18 Wed 18:05-21:05>
:PROPERTIES:
:ID:       kT6eOkzrBJaY2jZM_kZu2yBZ@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Drive vs. Fireflies Drive vs. Fireflies

Follow on MiLB First Pitch  https //stza.co/+xGBI-D

Shop  https //stza.co/+xGBI-32

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Drive vs. Fireflies
END:VALARM
DTSTART:20180418T230500Z
DTEND:20180419T020500Z
UID:kT6eOkzrBJaY2jZM_kZu2yBZ@stanza.co
SUMMARY:Drive vs. Fireflies
DESCRIPTION:Drive vs. Fireflies\n\nFollow on MiLB First Pitch: https://stza.co/+xGBI-D\n\nShop: https://stza.co/+xGBI-32\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144530Z
LAST-MODIFIED:20180213T144530Z
TRANSP:OPAQUE
END:VEVENT
* Drive @ Intimidators
<2018-04-19 Thu 17:35-20:35>
:PROPERTIES:
:ID:       8AEIsJF2v2-HrDVmyl3N9OwA@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Drive @ Intimidators Drive @ Intimidators

Follow on MiLB First Pitch  https //stza.co/+wICr-36

Shop  https //stza.co/+wICr-3b

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Drive @ Intimidators
END:VALARM
DTSTART:20180419T223500Z
DTEND:20180420T013500Z
UID:8AEIsJF2v2-HrDVmyl3N9OwA@stanza.co
SUMMARY:Drive @ Intimidators
DESCRIPTION:Drive @ Intimidators\n\nFollow on MiLB First Pitch: https://stza.co/+wICr-36\n\nShop: https://stza.co/+wICr-3b\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144530Z
LAST-MODIFIED:20180213T144530Z
TRANSP:OPAQUE
END:VEVENT
* Drive @ Intimidators
<2018-04-20 Fri 18:05-21:05>
:PROPERTIES:
:ID:       Q84NkSjlbN791KRiiGaSBE1B@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Drive @ Intimidators Drive @ Intimidators

Follow on MiLB First Pitch  https //stza.co/+wICs-3I

Shop  https //stza.co/+wICs-1

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Drive @ Intimidators
END:VALARM
DTSTART:20180420T230500Z
DTEND:20180421T020500Z
UID:Q84NkSjlbN791KRiiGaSBE1B@stanza.co
SUMMARY:Drive @ Intimidators
DESCRIPTION:Drive @ Intimidators\n\nFollow on MiLB First Pitch: https://stza.co/+wICs-3I\n\nShop: https://stza.co/+wICs-1\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144530Z
LAST-MODIFIED:20180213T144530Z
TRANSP:OPAQUE
END:VEVENT
* Drive @ Intimidators
<2018-04-21 Sat 18:05-21:05>
:PROPERTIES:
:ID:       D9qYsuwvtHpB8YvDAilzSHcv@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Drive @ Intimidators Drive @ Intimidators

Follow on MiLB First Pitch  https //stza.co/+wICt-15

Shop  https //stza.co/+wICt-2E

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Drive @ Intimidators
END:VALARM
DTSTART:20180421T230500Z
DTEND:20180422T020500Z
UID:D9qYsuwvtHpB8YvDAilzSHcv@stanza.co
SUMMARY:Drive @ Intimidators
DESCRIPTION:Drive @ Intimidators\n\nFollow on MiLB First Pitch: https://stza.co/+wICt-15\n\nShop: https://stza.co/+wICt-2E\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144530Z
LAST-MODIFIED:20180213T144530Z
TRANSP:OPAQUE
END:VEVENT
* Drive @ Intimidators
<2018-04-22 Sun 14:35-17:35>
:PROPERTIES:
:ID:       CN5JoZUW_yyQb8R_ltZEk5GI@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Drive @ Intimidators Drive @ Intimidators

Follow on MiLB First Pitch  https //stza.co/+wICu-3w

Shop  https //stza.co/+wICu-u

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Drive @ Intimidators
END:VALARM
DTSTART:20180422T193500Z
DTEND:20180422T223500Z
UID:CN5JoZUW_yyQb8R_ltZEk5GI@stanza.co
SUMMARY:Drive @ Intimidators
DESCRIPTION:Drive @ Intimidators\n\nFollow on MiLB First Pitch: https://stza.co/+wICu-3w\n\nShop: https://stza.co/+wICu-u\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144530Z
LAST-MODIFIED:20180213T144530Z
TRANSP:OPAQUE
END:VEVENT
* Drive vs. GreenJackets
<2018-04-23 Mon 18:05-21:05>
:PROPERTIES:
:ID:       zK93Ttc6XdBegUUGIv0OTlZ6@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Drive vs. GreenJackets Drive vs. GreenJackets

Follow on MiLB First Pitch  https //stza.co/+xGBK-3N

Shop  https //stza.co/+xGBK-1V

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Drive vs. GreenJackets
END:VALARM
DTSTART:20180423T230500Z
DTEND:20180424T020500Z
UID:zK93Ttc6XdBegUUGIv0OTlZ6@stanza.co
SUMMARY:Drive vs. GreenJackets
DESCRIPTION:Drive vs. GreenJackets\n\nFollow on MiLB First Pitch: https://stza.co/+xGBK-3N\n\nShop: https://stza.co/+xGBK-1V\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144530Z
LAST-MODIFIED:20180213T144530Z
TRANSP:OPAQUE
END:VEVENT
* Drive vs. GreenJackets
<2018-04-24 Tue 13:05-16:05>
:PROPERTIES:
:ID:       ga9WXysS_KhleqTGmHzGCRnw@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Drive vs. GreenJackets Drive vs. GreenJackets

Follow on MiLB First Pitch  https //stza.co/+xGBM-2a

Shop  https //stza.co/+xGBM-2e

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Drive vs. GreenJackets
END:VALARM
DTSTART:20180424T180500Z
DTEND:20180424T210500Z
UID:ga9WXysS_KhleqTGmHzGCRnw@stanza.co
SUMMARY:Drive vs. GreenJackets
DESCRIPTION:Drive vs. GreenJackets\n\nFollow on MiLB First Pitch: https://stza.co/+xGBM-2a\n\nShop: https://stza.co/+xGBM-2e\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144530Z
LAST-MODIFIED:20180213T144530Z
TRANSP:OPAQUE
END:VEVENT
* Drive vs. GreenJackets
<2018-04-25 Wed 18:05-21:05>
:PROPERTIES:
:ID:       HQ-priCsbb6BXn_vNqjPpddw@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Drive vs. GreenJackets Drive vs. GreenJackets

Follow on MiLB First Pitch  https //stza.co/+xGBO-1q

Shop  https //stza.co/+xGBO-T

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Drive vs. GreenJackets
END:VALARM
DTSTART:20180425T230500Z
DTEND:20180426T020500Z
UID:HQ-priCsbb6BXn_vNqjPpddw@stanza.co
SUMMARY:Drive vs. GreenJackets
DESCRIPTION:Drive vs. GreenJackets\n\nFollow on MiLB First Pitch: https://stza.co/+xGBO-1q\n\nShop: https://stza.co/+xGBO-T\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144530Z
LAST-MODIFIED:20180213T144530Z
TRANSP:OPAQUE
END:VEVENT
* Drive vs. GreenJackets
<2018-04-26 Thu 18:05-21:05>
:PROPERTIES:
:ID:       fvVLlZqzoMeOzA5inoNZTqC8@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Drive vs. GreenJackets Drive vs. GreenJackets

Follow on MiLB First Pitch  https //stza.co/+xGBQ-34

Shop  https //stza.co/+xGBQ-b

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Drive vs. GreenJackets
END:VALARM
DTSTART:20180426T230500Z
DTEND:20180427T020500Z
UID:fvVLlZqzoMeOzA5inoNZTqC8@stanza.co
SUMMARY:Drive vs. GreenJackets
DESCRIPTION:Drive vs. GreenJackets\n\nFollow on MiLB First Pitch: https://stza.co/+xGBQ-34\n\nShop: https://stza.co/+xGBQ-b\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144530Z
LAST-MODIFIED:20180213T144530Z
TRANSP:OPAQUE
END:VEVENT
* Drive vs. RiverDogs
<2018-04-27 Fri 18:05-21:05>
:PROPERTIES:
:ID:       T2c12_QmdTl0JEFU-iVi-ULT@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Drive vs. RiverDogs Drive vs. RiverDogs

Follow on MiLB First Pitch  https //stza.co/+xGBS-3J

Shop  https //stza.co/+xGBS-1Q

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Drive vs. RiverDogs
END:VALARM
DTSTART:20180427T230500Z
DTEND:20180428T020500Z
UID:T2c12_QmdTl0JEFU-iVi-ULT@stanza.co
SUMMARY:Drive vs. RiverDogs
DESCRIPTION:Drive vs. RiverDogs\n\nFollow on MiLB First Pitch: https://stza.co/+xGBS-3J\n\nShop: https://stza.co/+xGBS-1Q\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144530Z
LAST-MODIFIED:20180213T144530Z
TRANSP:OPAQUE
END:VEVENT
* Drive vs. RiverDogs
<2018-04-28 Sat 18:05-21:05>
:PROPERTIES:
:ID:       BXsyFwBI2kdtgDgBH6_fOTZk@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Drive vs. RiverDogs Drive vs. RiverDogs

Follow on MiLB First Pitch  https //stza.co/+xGBT-u

Shop  https //stza.co/+xGBT-3V

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Drive vs. RiverDogs
END:VALARM
DTSTART:20180428T230500Z
DTEND:20180429T020500Z
UID:BXsyFwBI2kdtgDgBH6_fOTZk@stanza.co
SUMMARY:Drive vs. RiverDogs
DESCRIPTION:Drive vs. RiverDogs\n\nFollow on MiLB First Pitch: https://stza.co/+xGBT-u\n\nShop: https://stza.co/+xGBT-3V\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144530Z
LAST-MODIFIED:20180213T144530Z
TRANSP:OPAQUE
END:VEVENT
* Drive vs. RiverDogs
<2018-04-29 Sun 15:05-18:05>
:PROPERTIES:
:ID:       k167bGvXU3LY_7sobSQezRFC@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Drive vs. RiverDogs Drive vs. RiverDogs

Follow on MiLB First Pitch  https //stza.co/+xGBW-K

Shop  https //stza.co/+xGBW-1L

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Drive vs. RiverDogs
END:VALARM
DTSTART:20180429T200500Z
DTEND:20180429T230500Z
UID:k167bGvXU3LY_7sobSQezRFC@stanza.co
SUMMARY:Drive vs. RiverDogs
DESCRIPTION:Drive vs. RiverDogs\n\nFollow on MiLB First Pitch: https://stza.co/+xGBW-K\n\nShop: https://stza.co/+xGBW-1L\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144530Z
LAST-MODIFIED:20180213T144530Z
TRANSP:OPAQUE
END:VEVENT
* Drive @ Shorebirds
<2018-05-01 Tue 18:05-21:05>
:PROPERTIES:
:ID:       SqjtVo7biQkOOJk3ZAI19fkt@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Drive @ Shorebirds Drive @ Shorebirds

Follow on MiLB First Pitch  https //stza.co/+wHS0-2B

Shop  https //stza.co/+wHS0-X

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Drive @ Shorebirds
END:VALARM
DTSTART:20180501T230500Z
DTEND:20180502T020500Z
UID:SqjtVo7biQkOOJk3ZAI19fkt@stanza.co
SUMMARY:Drive @ Shorebirds
DESCRIPTION:Drive @ Shorebirds\n\nFollow on MiLB First Pitch: https://stza.co/+wHS0-2B\n\nShop: https://stza.co/+wHS0-X\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144530Z
LAST-MODIFIED:20180213T144530Z
TRANSP:OPAQUE
END:VEVENT
* Drive @ Shorebirds
<2018-05-02 Wed 18:05-21:05>
:PROPERTIES:
:ID:       I9KrEwgaUoA0UdcZAtAUyCqq@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Drive @ Shorebirds Drive @ Shorebirds

Follow on MiLB First Pitch  https //stza.co/+wHM2-3G

Shop  https //stza.co/+wHM2-3i

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Drive @ Shorebirds
END:VALARM
DTSTART:20180502T230500Z
DTEND:20180503T020500Z
UID:I9KrEwgaUoA0UdcZAtAUyCqq@stanza.co
SUMMARY:Drive @ Shorebirds
DESCRIPTION:Drive @ Shorebirds\n\nFollow on MiLB First Pitch: https://stza.co/+wHM2-3G\n\nShop: https://stza.co/+wHM2-3i\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144530Z
LAST-MODIFIED:20180213T144530Z
TRANSP:OPAQUE
END:VEVENT
* Drive @ Shorebirds
<2018-05-03 Thu 09:35-12:35>
:PROPERTIES:
:ID:       6S8thpxb85UxF683l0WvCbvM@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Drive @ Shorebirds Drive @ Shorebirds

Follow on MiLB First Pitch  https //stza.co/+wHMj-3t

Shop  https //stza.co/+wHMj-3o

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Drive @ Shorebirds
END:VALARM
DTSTART:20180503T143500Z
DTEND:20180503T173500Z
UID:6S8thpxb85UxF683l0WvCbvM@stanza.co
SUMMARY:Drive @ Shorebirds
DESCRIPTION:Drive @ Shorebirds\n\nFollow on MiLB First Pitch: https://stza.co/+wHMj-3t\n\nShop: https://stza.co/+wHMj-3o\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144530Z
LAST-MODIFIED:20180213T144530Z
TRANSP:OPAQUE
END:VEVENT
* Drive @ Grasshoppers
<2018-05-04 Fri 18:00-21:00>
:PROPERTIES:
:ID:       WpPmpEGoUutlf_nAd9CwTDDy@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Drive @ Grasshoppers Drive @ Grasshoppers

Follow on MiLB First Pitch  https //stza.co/+wizd-p

Shop  https //stza.co/+wizd-4

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Drive @ Grasshoppers
END:VALARM
DTSTART:20180504T230000Z
DTEND:20180505T020000Z
UID:WpPmpEGoUutlf_nAd9CwTDDy@stanza.co
SUMMARY:Drive @ Grasshoppers
DESCRIPTION:Drive @ Grasshoppers\n\nFollow on MiLB First Pitch: https://stza.co/+wizd-p\n\nShop: https://stza.co/+wizd-4\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144530Z
LAST-MODIFIED:20180213T144530Z
TRANSP:OPAQUE
END:VEVENT
* Drive @ Grasshoppers
<2018-05-05 Sat 18:00-21:00>
:PROPERTIES:
:ID:       OanghD3P0Nwyyt8dwvNwVDDT@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Drive @ Grasshoppers Drive @ Grasshoppers

Follow on MiLB First Pitch  https //stza.co/+wize-2A

Shop  https //stza.co/+wize-1

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Drive @ Grasshoppers
END:VALARM
DTSTART:20180505T230000Z
DTEND:20180506T020000Z
UID:OanghD3P0Nwyyt8dwvNwVDDT@stanza.co
SUMMARY:Drive @ Grasshoppers
DESCRIPTION:Drive @ Grasshoppers\n\nFollow on MiLB First Pitch: https://stza.co/+wize-2A\n\nShop: https://stza.co/+wize-1\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144530Z
LAST-MODIFIED:20180213T144530Z
TRANSP:OPAQUE
END:VEVENT
* Drive @ Grasshoppers
<2018-05-06 Sun 13:00-16:00>
:PROPERTIES:
:ID:       2FNmC5Ilt7a8B_xHmRlRA10l@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Drive @ Grasshoppers Drive @ Grasshoppers

Follow on MiLB First Pitch  https //stza.co/+wizf-1x

Shop  https //stza.co/+wizf-g

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Drive @ Grasshoppers
END:VALARM
DTSTART:20180506T180000Z
DTEND:20180506T210000Z
UID:2FNmC5Ilt7a8B_xHmRlRA10l@stanza.co
SUMMARY:Drive @ Grasshoppers
DESCRIPTION:Drive @ Grasshoppers\n\nFollow on MiLB First Pitch: https://stza.co/+wizf-1x\n\nShop: https://stza.co/+wizf-g\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144530Z
LAST-MODIFIED:20180213T144530Z
TRANSP:OPAQUE
END:VEVENT
* Drive @ Grasshoppers
<2018-05-07 Mon 09:45-12:45>
:PROPERTIES:
:ID:       lBFakfA3txpsLDE4QtSD2CM8@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Drive @ Grasshoppers Drive @ Grasshoppers

Follow on MiLB First Pitch  https //stza.co/+wioJ-1Z

Shop  https //stza.co/+wioJ-3J

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Drive @ Grasshoppers
END:VALARM
DTSTART:20180507T144500Z
DTEND:20180507T174500Z
UID:lBFakfA3txpsLDE4QtSD2CM8@stanza.co
SUMMARY:Drive @ Grasshoppers
DESCRIPTION:Drive @ Grasshoppers\n\nFollow on MiLB First Pitch: https://stza.co/+wioJ-1Z\n\nShop: https://stza.co/+wioJ-3J\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144530Z
LAST-MODIFIED:20180213T144530Z
TRANSP:OPAQUE
END:VEVENT
* Drive vs. Intimidators
<2018-05-09 Wed 18:05-21:05>
:PROPERTIES:
:ID:       Jxzj9zHzc2XUApLnUdtiXnas@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Drive vs. Intimidators Drive vs. Intimidators

Follow on MiLB First Pitch  https //stza.co/+xGBY-5

Shop  https //stza.co/+xGBY-k

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Drive vs. Intimidators
END:VALARM
DTSTART:20180509T230500Z
DTEND:20180510T020500Z
UID:Jxzj9zHzc2XUApLnUdtiXnas@stanza.co
SUMMARY:Drive vs. Intimidators
DESCRIPTION:Drive vs. Intimidators\n\nFollow on MiLB First Pitch: https://stza.co/+xGBY-5\n\nShop: https://stza.co/+xGBY-k\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144530Z
LAST-MODIFIED:20180213T144530Z
TRANSP:OPAQUE
END:VEVENT
* Drive vs. Intimidators
<2018-05-10 Thu 18:05-21:05>
:PROPERTIES:
:ID:       TAZs9VkXMtzR3XTkdW22--h4@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Drive vs. Intimidators Drive vs. Intimidators

Follow on MiLB First Pitch  https //stza.co/+xGBZ-x

Shop  https //stza.co/+xGBZ-25

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Drive vs. Intimidators
END:VALARM
DTSTART:20180510T230500Z
DTEND:20180511T020500Z
UID:TAZs9VkXMtzR3XTkdW22--h4@stanza.co
SUMMARY:Drive vs. Intimidators
DESCRIPTION:Drive vs. Intimidators\n\nFollow on MiLB First Pitch: https://stza.co/+xGBZ-x\n\nShop: https://stza.co/+xGBZ-25\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144530Z
LAST-MODIFIED:20180213T144530Z
TRANSP:OPAQUE
END:VEVENT
* Drive vs. Intimidators
<2018-05-11 Fri 18:05-21:05>
:PROPERTIES:
:ID:       GWx4e_qgYpNEb-kBKrHQ2IEM@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Drive vs. Intimidators Drive vs. Intimidators

Follow on MiLB First Pitch  https //stza.co/+xGC0-2c

Shop  https //stza.co/+xGC0-1r

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Drive vs. Intimidators
END:VALARM
DTSTART:20180511T230500Z
DTEND:20180512T020500Z
UID:GWx4e_qgYpNEb-kBKrHQ2IEM@stanza.co
SUMMARY:Drive vs. Intimidators
DESCRIPTION:Drive vs. Intimidators\n\nFollow on MiLB First Pitch: https://stza.co/+xGC0-2c\n\nShop: https://stza.co/+xGC0-1r\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144530Z
LAST-MODIFIED:20180213T144530Z
TRANSP:OPAQUE
END:VEVENT
* Drive @ Legends
<2018-05-12 Sat 17:35-20:35>
:PROPERTIES:
:ID:       W4cpVI0So_W-iKHMynMc8BSD@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Drive @ Legends Drive @ Legends

Follow on MiLB First Pitch  https //stza.co/+xB3O-v

Shop  https //stza.co/+xB3O-Y

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Drive @ Legends
END:VALARM
DTSTART:20180512T223500Z
DTEND:20180513T013500Z
UID:W4cpVI0So_W-iKHMynMc8BSD@stanza.co
SUMMARY:Drive @ Legends
DESCRIPTION:Drive @ Legends\n\nFollow on MiLB First Pitch: https://stza.co/+xB3O-v\n\nShop: https://stza.co/+xB3O-Y\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144530Z
LAST-MODIFIED:20180213T144530Z
TRANSP:OPAQUE
END:VEVENT
* Drive @ Legends
<2018-05-13 Sun 13:05-16:05>
:PROPERTIES:
:ID:       fOxfi2cpum8gZ09_qd1Sv_Se@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Drive @ Legends Drive @ Legends

Follow on MiLB First Pitch  https //stza.co/+xB3T-$

Shop  https //stza.co/+xB3T-2h

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Drive @ Legends
END:VALARM
DTSTART:20180513T180500Z
DTEND:20180513T210500Z
UID:fOxfi2cpum8gZ09_qd1Sv_Se@stanza.co
SUMMARY:Drive @ Legends
DESCRIPTION:Drive @ Legends\n\nFollow on MiLB First Pitch: https://stza.co/+xB3T-$\n\nShop: https://stza.co/+xB3T-2h\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144530Z
LAST-MODIFIED:20180213T144530Z
TRANSP:OPAQUE
END:VEVENT
* Drive @ Legends
<2018-05-14 Mon 18:05-21:05>
:PROPERTIES:
:ID:       W5c326sCLSSjhfGeU3Mw3TKJ@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Drive @ Legends Drive @ Legends

Follow on MiLB First Pitch  https //stza.co/+xB3X-19

Shop  https //stza.co/+xB3X-1a

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Drive @ Legends
END:VALARM
DTSTART:20180514T230500Z
DTEND:20180515T020500Z
UID:W5c326sCLSSjhfGeU3Mw3TKJ@stanza.co
SUMMARY:Drive @ Legends
DESCRIPTION:Drive @ Legends\n\nFollow on MiLB First Pitch: https://stza.co/+xB3X-19\n\nShop: https://stza.co/+xB3X-1a\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144530Z
LAST-MODIFIED:20180213T144530Z
TRANSP:OPAQUE
END:VEVENT
* Drive @ Legends
<2018-05-15 Tue 18:05-21:05>
:PROPERTIES:
:ID:       l_yQTi1ieofPQyEg7zsxUs9Z@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Drive @ Legends Drive @ Legends

Follow on MiLB First Pitch  https //stza.co/+xB3_-3h

Shop  https //stza.co/+xB3_-2U

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Drive @ Legends
END:VALARM
DTSTART:20180515T230500Z
DTEND:20180516T020500Z
UID:l_yQTi1ieofPQyEg7zsxUs9Z@stanza.co
SUMMARY:Drive @ Legends
DESCRIPTION:Drive @ Legends\n\nFollow on MiLB First Pitch: https://stza.co/+xB3_-3h\n\nShop: https://stza.co/+xB3_-2U\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144530Z
LAST-MODIFIED:20180213T144530Z
TRANSP:OPAQUE
END:VEVENT
* Drive vs. GreenJackets
<2018-05-17 Thu 18:05-21:05>
:PROPERTIES:
:ID:       t_zDxvVs5txnWHTa7O_-rR8O@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Drive vs. GreenJackets Drive vs. GreenJackets

Follow on MiLB First Pitch  https //stza.co/+xGC1-M

Shop  https //stza.co/+xGC1-3k

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Drive vs. GreenJackets
END:VALARM
DTSTART:20180517T230500Z
DTEND:20180518T020500Z
UID:t_zDxvVs5txnWHTa7O_-rR8O@stanza.co
SUMMARY:Drive vs. GreenJackets
DESCRIPTION:Drive vs. GreenJackets\n\nFollow on MiLB First Pitch: https://stza.co/+xGC1-M\n\nShop: https://stza.co/+xGC1-3k\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144530Z
LAST-MODIFIED:20180213T144530Z
TRANSP:OPAQUE
END:VEVENT
* Drive vs. GreenJackets
<2018-05-18 Fri 18:05-21:05>
:PROPERTIES:
:ID:       GPy6XTdMe1EzGT4-lEBKUqoa@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Drive vs. GreenJackets Drive vs. GreenJackets

Follow on MiLB First Pitch  https //stza.co/+xGC3-21

Shop  https //stza.co/+xGC3-X

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Drive vs. GreenJackets
END:VALARM
DTSTART:20180518T230500Z
DTEND:20180519T020500Z
UID:GPy6XTdMe1EzGT4-lEBKUqoa@stanza.co
SUMMARY:Drive vs. GreenJackets
DESCRIPTION:Drive vs. GreenJackets\n\nFollow on MiLB First Pitch: https://stza.co/+xGC3-21\n\nShop: https://stza.co/+xGC3-X\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144530Z
LAST-MODIFIED:20180213T144530Z
TRANSP:OPAQUE
END:VEVENT
* Drive vs. GreenJackets
<2018-05-19 Sat 18:05-21:05>
:PROPERTIES:
:ID:       TeGHfPcVMtMT_9H7Vhh6-lyM@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Drive vs. GreenJackets Drive vs. GreenJackets

Follow on MiLB First Pitch  https //stza.co/+xGC6-f

Shop  https //stza.co/+xGC6-36

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Drive vs. GreenJackets
END:VALARM
DTSTART:20180519T230500Z
DTEND:20180520T020500Z
UID:TeGHfPcVMtMT_9H7Vhh6-lyM@stanza.co
SUMMARY:Drive vs. GreenJackets
DESCRIPTION:Drive vs. GreenJackets\n\nFollow on MiLB First Pitch: https://stza.co/+xGC6-f\n\nShop: https://stza.co/+xGC6-36\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144530Z
LAST-MODIFIED:20180213T144530Z
TRANSP:OPAQUE
END:VEVENT
* Drive vs. GreenJackets
<2018-05-20 Sun 15:05-18:05>
:PROPERTIES:
:ID:       VI4YlCNBejXaPccV0-BLbzSV@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Drive vs. GreenJackets Drive vs. GreenJackets

Follow on MiLB First Pitch  https //stza.co/+xGC8-1Q

Shop  https //stza.co/+xGC8-h

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Drive vs. GreenJackets
END:VALARM
DTSTART:20180520T200500Z
DTEND:20180520T230500Z
UID:VI4YlCNBejXaPccV0-BLbzSV@stanza.co
SUMMARY:Drive vs. GreenJackets
DESCRIPTION:Drive vs. GreenJackets\n\nFollow on MiLB First Pitch: https://stza.co/+xGC8-1Q\n\nShop: https://stza.co/+xGC8-h\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144530Z
LAST-MODIFIED:20180213T144530Z
TRANSP:OPAQUE
END:VEVENT
* Drive @ Tourists
<2018-05-21 Mon 18:05-21:05>
:PROPERTIES:
:ID:       OhspWGXrtnmDDPacTYReG1gp@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Drive @ Tourists Drive @ Tourists

Follow on MiLB First Pitch  https //stza.co/+vxMy-2f

Shop  https //stza.co/+vxMy-N

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Drive @ Tourists
END:VALARM
DTSTART:20180521T230500Z
DTEND:20180522T020500Z
UID:OhspWGXrtnmDDPacTYReG1gp@stanza.co
SUMMARY:Drive @ Tourists
DESCRIPTION:Drive @ Tourists\n\nFollow on MiLB First Pitch: https://stza.co/+vxMy-2f\n\nShop: https://stza.co/+vxMy-N\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144530Z
LAST-MODIFIED:20180213T144530Z
TRANSP:OPAQUE
END:VEVENT
* Drive @ Tourists
<2018-05-22 Tue 18:05-21:05>
:PROPERTIES:
:ID:       h7eU0sqxFl4Ke4kmsivQ5Oj-@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Drive @ Tourists Drive @ Tourists

Follow on MiLB First Pitch  https //stza.co/+vxMz-c

Shop  https //stza.co/+vxMz-V

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Drive @ Tourists
END:VALARM
DTSTART:20180522T230500Z
DTEND:20180523T020500Z
UID:h7eU0sqxFl4Ke4kmsivQ5Oj-@stanza.co
SUMMARY:Drive @ Tourists
DESCRIPTION:Drive @ Tourists\n\nFollow on MiLB First Pitch: https://stza.co/+vxMz-c\n\nShop: https://stza.co/+vxMz-V\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144530Z
LAST-MODIFIED:20180213T144530Z
TRANSP:OPAQUE
END:VEVENT
* Drive @ Tourists
<2018-05-23 Wed 09:35-12:35>
:PROPERTIES:
:ID:       8nl9b-subkcz-2tCUQSKOkuU@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Drive @ Tourists Drive @ Tourists

Follow on MiLB First Pitch  https //stza.co/+vxMA-2J

Shop  https //stza.co/+vxMA-3l

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Drive @ Tourists
END:VALARM
DTSTART:20180523T143500Z
DTEND:20180523T173500Z
UID:8nl9b-subkcz-2tCUQSKOkuU@stanza.co
SUMMARY:Drive @ Tourists
DESCRIPTION:Drive @ Tourists\n\nFollow on MiLB First Pitch: https://stza.co/+vxMA-2J\n\nShop: https://stza.co/+vxMA-3l\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144530Z
LAST-MODIFIED:20180213T144530Z
TRANSP:OPAQUE
END:VEVENT
* Drive @ Tourists
<2018-05-24 Thu 18:05-21:05>
:PROPERTIES:
:ID:       OA02DusIdU-IurvrEE2YknaL@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Drive @ Tourists Drive @ Tourists

Follow on MiLB First Pitch  https //stza.co/+vxMB-2T

Shop  https //stza.co/+vxMB-1r

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Drive @ Tourists
END:VALARM
DTSTART:20180524T230500Z
DTEND:20180525T020500Z
UID:OA02DusIdU-IurvrEE2YknaL@stanza.co
SUMMARY:Drive @ Tourists
DESCRIPTION:Drive @ Tourists\n\nFollow on MiLB First Pitch: https://stza.co/+vxMB-2T\n\nShop: https://stza.co/+vxMB-1r\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144530Z
LAST-MODIFIED:20180213T144530Z
TRANSP:OPAQUE
END:VEVENT
* Drive @ Fireflies
<2018-05-25 Fri 18:05-21:05>
:PROPERTIES:
:ID:       BgO369iP8sBtpoTGF6QBB8Kq@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Drive @ Fireflies Drive @ Fireflies

Follow on MiLB First Pitch  https //stza.co/+xBSR-3b

Shop  https //stza.co/+xBSR-N

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Drive @ Fireflies
END:VALARM
DTSTART:20180525T230500Z
DTEND:20180526T020500Z
UID:BgO369iP8sBtpoTGF6QBB8Kq@stanza.co
SUMMARY:Drive @ Fireflies
DESCRIPTION:Drive @ Fireflies\n\nFollow on MiLB First Pitch: https://stza.co/+xBSR-3b\n\nShop: https://stza.co/+xBSR-N\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144530Z
LAST-MODIFIED:20180213T144530Z
TRANSP:OPAQUE
END:VEVENT
* Drive @ Fireflies
<2018-05-26 Sat 17:05-20:05>
:PROPERTIES:
:ID:       nVnq-_zwf97IgyaCIJPaS66X@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Drive @ Fireflies Drive @ Fireflies

Follow on MiLB First Pitch  https //stza.co/+xBSS-20

Shop  https //stza.co/+xBSS-3D

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Drive @ Fireflies
END:VALARM
DTSTART:20180526T220500Z
DTEND:20180527T010500Z
UID:nVnq-_zwf97IgyaCIJPaS66X@stanza.co
SUMMARY:Drive @ Fireflies
DESCRIPTION:Drive @ Fireflies\n\nFollow on MiLB First Pitch: https://stza.co/+xBSS-20\n\nShop: https://stza.co/+xBSS-3D\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144530Z
LAST-MODIFIED:20180213T144530Z
TRANSP:OPAQUE
END:VEVENT
* Drive @ Fireflies
<2018-05-27 Sun 17:05-20:05>
:PROPERTIES:
:ID:       iy_WVIm_FDBdoKiSQKQAddzM@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Drive @ Fireflies Drive @ Fireflies

Follow on MiLB First Pitch  https //stza.co/+xBST-3M

Shop  https //stza.co/+xBST-3V

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Drive @ Fireflies
END:VALARM
DTSTART:20180527T220500Z
DTEND:20180528T010500Z
UID:iy_WVIm_FDBdoKiSQKQAddzM@stanza.co
SUMMARY:Drive @ Fireflies
DESCRIPTION:Drive @ Fireflies\n\nFollow on MiLB First Pitch: https://stza.co/+xBST-3M\n\nShop: https://stza.co/+xBST-3V\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144530Z
LAST-MODIFIED:20180213T144530Z
TRANSP:OPAQUE
END:VEVENT
* Drive @ Fireflies
<2018-05-28 Mon 11:05-14:05>
:PROPERTIES:
:ID:       _LuAHycgXPeFWopOVMGsQD8z@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Drive @ Fireflies Drive @ Fireflies

Follow on MiLB First Pitch  https //stza.co/+xB3x-d

Shop  https //stza.co/+xB3x-3J

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Drive @ Fireflies
END:VALARM
DTSTART:20180528T160500Z
DTEND:20180528T190500Z
UID:_LuAHycgXPeFWopOVMGsQD8z@stanza.co
SUMMARY:Drive @ Fireflies
DESCRIPTION:Drive @ Fireflies\n\nFollow on MiLB First Pitch: https://stza.co/+xB3x-d\n\nShop: https://stza.co/+xB3x-3J\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144530Z
LAST-MODIFIED:20180213T144530Z
TRANSP:OPAQUE
END:VEVENT
* Drive vs. GreenJackets
<2018-05-29 Tue 18:05-21:05>
:PROPERTIES:
:ID:       OE3Y50mPvv3oM_qzJRgmQnXA@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Drive vs. GreenJackets Drive vs. GreenJackets

Follow on MiLB First Pitch  https //stza.co/+xGCb-14

Shop  https //stza.co/+xGCb-21

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Drive vs. GreenJackets
END:VALARM
DTSTART:20180529T230500Z
DTEND:20180530T020500Z
UID:OE3Y50mPvv3oM_qzJRgmQnXA@stanza.co
SUMMARY:Drive vs. GreenJackets
DESCRIPTION:Drive vs. GreenJackets\n\nFollow on MiLB First Pitch: https://stza.co/+xGCb-14\n\nShop: https://stza.co/+xGCb-21\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144530Z
LAST-MODIFIED:20180213T144530Z
TRANSP:OPAQUE
END:VEVENT
* Drive vs. GreenJackets
<2018-05-30 Wed 18:05-21:05>
:PROPERTIES:
:ID:       61UpogNjb8lyhWxAigbL5MPO@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Drive vs. GreenJackets Drive vs. GreenJackets

Follow on MiLB First Pitch  https //stza.co/+xGCd-x

Shop  https //stza.co/+xGCd-3C

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Drive vs. GreenJackets
END:VALARM
DTSTART:20180530T230500Z
DTEND:20180531T020500Z
UID:61UpogNjb8lyhWxAigbL5MPO@stanza.co
SUMMARY:Drive vs. GreenJackets
DESCRIPTION:Drive vs. GreenJackets\n\nFollow on MiLB First Pitch: https://stza.co/+xGCd-x\n\nShop: https://stza.co/+xGCd-3C\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144530Z
LAST-MODIFIED:20180213T144530Z
TRANSP:OPAQUE
END:VEVENT
* Drive vs. GreenJackets
<2018-05-31 Thu 18:05-21:05>
:PROPERTIES:
:ID:       aNoDw17wwg5KjidpwUJcr77h@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Drive vs. GreenJackets Drive vs. GreenJackets

Follow on MiLB First Pitch  https //stza.co/+xGCf-3b

Shop  https //stza.co/+xGCf-1d

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Drive vs. GreenJackets
END:VALARM
DTSTART:20180531T230500Z
DTEND:20180601T020500Z
UID:aNoDw17wwg5KjidpwUJcr77h@stanza.co
SUMMARY:Drive vs. GreenJackets
DESCRIPTION:Drive vs. GreenJackets\n\nFollow on MiLB First Pitch: https://stza.co/+xGCf-3b\n\nShop: https://stza.co/+xGCf-1d\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144530Z
LAST-MODIFIED:20180213T144530Z
TRANSP:OPAQUE
END:VEVENT
* Drive vs. Tourists
<2018-06-01 Fri 18:05-21:05>
:PROPERTIES:
:ID:       8ZxP61nvxgIbAKDaixDxluIR@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Drive vs. Tourists Drive vs. Tourists

Follow on MiLB First Pitch  https //stza.co/+xGCh-_

Shop  https //stza.co/+xGCh-3E

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Drive vs. Tourists
END:VALARM
DTSTART:20180601T230500Z
DTEND:20180602T020500Z
UID:8ZxP61nvxgIbAKDaixDxluIR@stanza.co
SUMMARY:Drive vs. Tourists
DESCRIPTION:Drive vs. Tourists\n\nFollow on MiLB First Pitch: https://stza.co/+xGCh-_\n\nShop: https://stza.co/+xGCh-3E\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144530Z
LAST-MODIFIED:20180213T144530Z
TRANSP:OPAQUE
END:VEVENT
* Drive vs. Tourists
<2018-06-02 Sat 18:05-21:05>
:PROPERTIES:
:ID:       tWxv0haOc5nn7HgazwSxPQoJ@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Drive vs. Tourists Drive vs. Tourists

Follow on MiLB First Pitch  https //stza.co/+xGCi-3

Shop  https //stza.co/+xGCi-D

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Drive vs. Tourists
END:VALARM
DTSTART:20180602T230500Z
DTEND:20180603T020500Z
UID:tWxv0haOc5nn7HgazwSxPQoJ@stanza.co
SUMMARY:Drive vs. Tourists
DESCRIPTION:Drive vs. Tourists\n\nFollow on MiLB First Pitch: https://stza.co/+xGCi-3\n\nShop: https://stza.co/+xGCi-D\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144530Z
LAST-MODIFIED:20180213T144530Z
TRANSP:OPAQUE
END:VEVENT
* Drive vs. Tourists
<2018-06-03 Sun 15:05-18:05>
:PROPERTIES:
:ID:       QsrNxaUK7n8fUMon6wDfABem@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Drive vs. Tourists Drive vs. Tourists

Follow on MiLB First Pitch  https //stza.co/+xGCl-6

Shop  https //stza.co/+xGCl-1J

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Drive vs. Tourists
END:VALARM
DTSTART:20180603T200500Z
DTEND:20180603T230500Z
UID:QsrNxaUK7n8fUMon6wDfABem@stanza.co
SUMMARY:Drive vs. Tourists
DESCRIPTION:Drive vs. Tourists\n\nFollow on MiLB First Pitch: https://stza.co/+xGCl-6\n\nShop: https://stza.co/+xGCl-1J\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144530Z
LAST-MODIFIED:20180213T144530Z
TRANSP:OPAQUE
END:VEVENT
* Drive @ GreenJackets
<2018-06-05 Tue 18:05-21:05>
:PROPERTIES:
:ID:       EyeCM0s38BTnz-mVOXP6y2G4@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Drive @ GreenJackets Drive @ GreenJackets

Follow on MiLB First Pitch  https //stza.co/+xB2W-36

Shop  https //stza.co/+xB2W-2y

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Drive @ GreenJackets
END:VALARM
DTSTART:20180605T230500Z
DTEND:20180606T020500Z
UID:EyeCM0s38BTnz-mVOXP6y2G4@stanza.co
SUMMARY:Drive @ GreenJackets
DESCRIPTION:Drive @ GreenJackets\n\nFollow on MiLB First Pitch: https://stza.co/+xB2W-36\n\nShop: https://stza.co/+xB2W-2y\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144530Z
LAST-MODIFIED:20180213T144530Z
TRANSP:OPAQUE
END:VEVENT
* Drive @ GreenJackets
<2018-06-06 Wed 18:05-21:05>
:PROPERTIES:
:ID:       yQ69NWNr-aTzPxI3khlZJFC9@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Drive @ GreenJackets Drive @ GreenJackets

Follow on MiLB First Pitch  https //stza.co/+xB2X-1g

Shop  https //stza.co/+xB2X-2Z

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Drive @ GreenJackets
END:VALARM
DTSTART:20180606T230500Z
DTEND:20180607T020500Z
UID:yQ69NWNr-aTzPxI3khlZJFC9@stanza.co
SUMMARY:Drive @ GreenJackets
DESCRIPTION:Drive @ GreenJackets\n\nFollow on MiLB First Pitch: https://stza.co/+xB2X-1g\n\nShop: https://stza.co/+xB2X-2Z\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144530Z
LAST-MODIFIED:20180213T144530Z
TRANSP:OPAQUE
END:VEVENT
* Drive @ GreenJackets
<2018-06-07 Thu 18:05-21:05>
:PROPERTIES:
:ID:       bZsywl_g3yanCi1attyD7fcz@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Drive @ GreenJackets Drive @ GreenJackets

Follow on MiLB First Pitch  https //stza.co/+xB2Y-1h

Shop  https //stza.co/+xB2Y-6

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Drive @ GreenJackets
END:VALARM
DTSTART:20180607T230500Z
DTEND:20180608T020500Z
UID:bZsywl_g3yanCi1attyD7fcz@stanza.co
SUMMARY:Drive @ GreenJackets
DESCRIPTION:Drive @ GreenJackets\n\nFollow on MiLB First Pitch: https://stza.co/+xB2Y-1h\n\nShop: https://stza.co/+xB2Y-6\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144530Z
LAST-MODIFIED:20180213T144530Z
TRANSP:OPAQUE
END:VEVENT
* Drive vs. RiverDogs
<2018-06-08 Fri 18:05-21:05>
:PROPERTIES:
:ID:       uKWzDbySwcKdbSczuRiJXhQ9@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Drive vs. RiverDogs Drive vs. RiverDogs

Follow on MiLB First Pitch  https //stza.co/+xGCn-1P

Shop  https //stza.co/+xGCn-2s

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Drive vs. RiverDogs
END:VALARM
DTSTART:20180608T230500Z
DTEND:20180609T020500Z
UID:uKWzDbySwcKdbSczuRiJXhQ9@stanza.co
SUMMARY:Drive vs. RiverDogs
DESCRIPTION:Drive vs. RiverDogs\n\nFollow on MiLB First Pitch: https://stza.co/+xGCn-1P\n\nShop: https://stza.co/+xGCn-2s\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144530Z
LAST-MODIFIED:20180213T144530Z
TRANSP:OPAQUE
END:VEVENT
* Drive vs. RiverDogs
<2018-06-09 Sat 18:05-21:05>
:PROPERTIES:
:ID:       zs76pPG8T8BOubstxxqqPj97@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Drive vs. RiverDogs Drive vs. RiverDogs

Follow on MiLB First Pitch  https //stza.co/+xGCo-28

Shop  https //stza.co/+xGCo-3O

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Drive vs. RiverDogs
END:VALARM
DTSTART:20180609T230500Z
DTEND:20180610T020500Z
UID:zs76pPG8T8BOubstxxqqPj97@stanza.co
SUMMARY:Drive vs. RiverDogs
DESCRIPTION:Drive vs. RiverDogs\n\nFollow on MiLB First Pitch: https://stza.co/+xGCo-28\n\nShop: https://stza.co/+xGCo-3O\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144530Z
LAST-MODIFIED:20180213T144530Z
TRANSP:OPAQUE
END:VEVENT
* Drive vs. RiverDogs
<2018-06-10 Sun 15:05-18:05>
:PROPERTIES:
:ID:       eSKdsHVImwSys_-xefAbwMyw@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Drive vs. RiverDogs Drive vs. RiverDogs

Follow on MiLB First Pitch  https //stza.co/+xGCr-2I

Shop  https //stza.co/+xGCr-26

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Drive vs. RiverDogs
END:VALARM
DTSTART:20180610T200500Z
DTEND:20180610T230500Z
UID:eSKdsHVImwSys_-xefAbwMyw@stanza.co
SUMMARY:Drive vs. RiverDogs
DESCRIPTION:Drive vs. RiverDogs\n\nFollow on MiLB First Pitch: https://stza.co/+xGCr-2I\n\nShop: https://stza.co/+xGCr-26\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144530Z
LAST-MODIFIED:20180213T144530Z
TRANSP:OPAQUE
END:VEVENT
* Drive vs. Braves
<2018-06-11 Mon 18:05-21:05>
:PROPERTIES:
:ID:       06CqPY7pm5zMGAwFZ9YoLI_G@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Drive vs. Braves Drive vs. Braves

Follow on MiLB First Pitch  https //stza.co/+xGCt-2d

Shop  https //stza.co/+xGCt-r

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Drive vs. Braves
END:VALARM
DTSTART:20180611T230500Z
DTEND:20180612T020500Z
UID:06CqPY7pm5zMGAwFZ9YoLI_G@stanza.co
SUMMARY:Drive vs. Braves
DESCRIPTION:Drive vs. Braves\n\nFollow on MiLB First Pitch: https://stza.co/+xGCt-2d\n\nShop: https://stza.co/+xGCt-r\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144530Z
LAST-MODIFIED:20180213T144530Z
TRANSP:OPAQUE
END:VEVENT
* Drive vs. Braves
<2018-06-12 Tue 18:05-21:05>
:PROPERTIES:
:ID:       RuXS3j-QKIVNseBWpvpvKl9Y@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Drive vs. Braves Drive vs. Braves

Follow on MiLB First Pitch  https //stza.co/+xGCu-2r

Shop  https //stza.co/+xGCu-2M

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Drive vs. Braves
END:VALARM
DTSTART:20180612T230500Z
DTEND:20180613T020500Z
UID:RuXS3j-QKIVNseBWpvpvKl9Y@stanza.co
SUMMARY:Drive vs. Braves
DESCRIPTION:Drive vs. Braves\n\nFollow on MiLB First Pitch: https://stza.co/+xGCu-2r\n\nShop: https://stza.co/+xGCu-2M\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144530Z
LAST-MODIFIED:20180213T144530Z
TRANSP:OPAQUE
END:VEVENT
* Drive vs. Braves
<2018-06-13 Wed 18:05-21:05>
:PROPERTIES:
:ID:       H0kgdn62vK2CYjkWGab5f_iG@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Drive vs. Braves Drive vs. Braves

Follow on MiLB First Pitch  https //stza.co/+xGCx-2H

Shop  https //stza.co/+xGCx-1e

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Drive vs. Braves
END:VALARM
DTSTART:20180613T230500Z
DTEND:20180614T020500Z
UID:H0kgdn62vK2CYjkWGab5f_iG@stanza.co
SUMMARY:Drive vs. Braves
DESCRIPTION:Drive vs. Braves\n\nFollow on MiLB First Pitch: https://stza.co/+xGCx-2H\n\nShop: https://stza.co/+xGCx-1e\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144530Z
LAST-MODIFIED:20180213T144530Z
TRANSP:OPAQUE
END:VEVENT
* Drive vs. Braves
<2018-06-14 Thu 18:05-21:05>
:PROPERTIES:
:ID:       ti7IVlmF7j5z1oUVILJucwWm@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Drive vs. Braves Drive vs. Braves

Follow on MiLB First Pitch  https //stza.co/+xGCz-P

Shop  https //stza.co/+xGCz-1u

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Drive vs. Braves
END:VALARM
DTSTART:20180614T230500Z
DTEND:20180615T020500Z
UID:ti7IVlmF7j5z1oUVILJucwWm@stanza.co
SUMMARY:Drive vs. Braves
DESCRIPTION:Drive vs. Braves\n\nFollow on MiLB First Pitch: https://stza.co/+xGCz-P\n\nShop: https://stza.co/+xGCz-1u\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144530Z
LAST-MODIFIED:20180213T144530Z
TRANSP:OPAQUE
END:VEVENT
* Drive @ RiverDogs
<2018-06-15 Fri 18:05-21:05>
:PROPERTIES:
:ID:       feUTTir_teogCIXUoG9_9WO8@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Drive @ RiverDogs Drive @ RiverDogs

Follow on MiLB First Pitch  https //stza.co/+vxMT-O

Shop  https //stza.co/+vxMT-1O

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Drive @ RiverDogs
END:VALARM
DTSTART:20180615T230500Z
DTEND:20180616T020500Z
UID:feUTTir_teogCIXUoG9_9WO8@stanza.co
SUMMARY:Drive @ RiverDogs
DESCRIPTION:Drive @ RiverDogs\n\nFollow on MiLB First Pitch: https://stza.co/+vxMT-O\n\nShop: https://stza.co/+vxMT-1O\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144530Z
LAST-MODIFIED:20180213T144530Z
TRANSP:OPAQUE
END:VEVENT
* Drive @ RiverDogs
<2018-06-16 Sat 17:05-20:05>
:PROPERTIES:
:ID:       MOf9lOz9SmQpxssgacmWsiyI@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Drive @ RiverDogs Drive @ RiverDogs

Follow on MiLB First Pitch  https //stza.co/+vxMU-D

Shop  https //stza.co/+vxMU-d

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Drive @ RiverDogs
END:VALARM
DTSTART:20180616T220500Z
DTEND:20180617T010500Z
UID:MOf9lOz9SmQpxssgacmWsiyI@stanza.co
SUMMARY:Drive @ RiverDogs
DESCRIPTION:Drive @ RiverDogs\n\nFollow on MiLB First Pitch: https://stza.co/+vxMU-D\n\nShop: https://stza.co/+vxMU-d\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144530Z
LAST-MODIFIED:20180213T144530Z
TRANSP:OPAQUE
END:VEVENT
* Drive @ RiverDogs
<2018-06-17 Sun 12:05-15:05>
:PROPERTIES:
:ID:       EMBWFfg_-JcHRdjTtlXikrBQ@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Drive @ RiverDogs Drive @ RiverDogs

Follow on MiLB First Pitch  https //stza.co/+vxMV-34

Shop  https //stza.co/+vxMV-1y

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Drive @ RiverDogs
END:VALARM
DTSTART:20180617T170500Z
DTEND:20180617T200500Z
UID:EMBWFfg_-JcHRdjTtlXikrBQ@stanza.co
SUMMARY:Drive @ RiverDogs
DESCRIPTION:Drive @ RiverDogs\n\nFollow on MiLB First Pitch: https://stza.co/+vxMV-34\n\nShop: https://stza.co/+vxMV-1y\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144530Z
LAST-MODIFIED:20180213T144530Z
TRANSP:OPAQUE
END:VEVENT
* Drive vs. Tourists
<2018-06-21 Thu 18:05-21:05>
:PROPERTIES:
:ID:       BVAwVPLgLLMTII_ys2RjXYA5@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Drive vs. Tourists Drive vs. Tourists

Follow on MiLB First Pitch  https //stza.co/+xGCB-15

Shop  https //stza.co/+xGCB-3e

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Drive vs. Tourists
END:VALARM
DTSTART:20180621T230500Z
DTEND:20180622T020500Z
UID:BVAwVPLgLLMTII_ys2RjXYA5@stanza.co
SUMMARY:Drive vs. Tourists
DESCRIPTION:Drive vs. Tourists\n\nFollow on MiLB First Pitch: https://stza.co/+xGCB-15\n\nShop: https://stza.co/+xGCB-3e\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144530Z
LAST-MODIFIED:20180213T144530Z
TRANSP:OPAQUE
END:VEVENT
* Drive vs. Tourists
<2018-06-22 Fri 18:05-21:05>
:PROPERTIES:
:ID:       l194og9k8g4MkWKgibv0Fn6i@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Drive vs. Tourists Drive vs. Tourists

Follow on MiLB First Pitch  https //stza.co/+xGCD-1S

Shop  https //stza.co/+xGCD-3W

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Drive vs. Tourists
END:VALARM
DTSTART:20180622T230500Z
DTEND:20180623T020500Z
UID:l194og9k8g4MkWKgibv0Fn6i@stanza.co
SUMMARY:Drive vs. Tourists
DESCRIPTION:Drive vs. Tourists\n\nFollow on MiLB First Pitch: https://stza.co/+xGCD-1S\n\nShop: https://stza.co/+xGCD-3W\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144530Z
LAST-MODIFIED:20180213T144530Z
TRANSP:OPAQUE
END:VEVENT
* Drive vs. Tourists
<2018-06-23 Sat 18:05-21:05>
:PROPERTIES:
:ID:       PsY7_xUg5vf7obk3EgXJO8Gc@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Drive vs. Tourists Drive vs. Tourists

Follow on MiLB First Pitch  https //stza.co/+xGCE-2X

Shop  https //stza.co/+xGCE-2Y

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Drive vs. Tourists
END:VALARM
DTSTART:20180623T230500Z
DTEND:20180624T020500Z
UID:PsY7_xUg5vf7obk3EgXJO8Gc@stanza.co
SUMMARY:Drive vs. Tourists
DESCRIPTION:Drive vs. Tourists\n\nFollow on MiLB First Pitch: https://stza.co/+xGCE-2X\n\nShop: https://stza.co/+xGCE-2Y\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144530Z
LAST-MODIFIED:20180213T144530Z
TRANSP:OPAQUE
END:VEVENT
* Drive @ Braves
<2018-06-24 Sun 13:00-16:00>
:PROPERTIES:
:ID:       ei1JgStGSjB77HWSlcB9QID4@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Drive @ Braves Drive @ Braves

Follow on MiLB First Pitch  https //stza.co/+vxSe-3N

Shop  https //stza.co/+vxSe-J

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Drive @ Braves
END:VALARM
DTSTART:20180624T180000Z
DTEND:20180624T210000Z
UID:ei1JgStGSjB77HWSlcB9QID4@stanza.co
SUMMARY:Drive @ Braves
DESCRIPTION:Drive @ Braves\n\nFollow on MiLB First Pitch: https://stza.co/+vxSe-3N\n\nShop: https://stza.co/+vxSe-J\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144530Z
LAST-MODIFIED:20180213T144530Z
TRANSP:OPAQUE
END:VEVENT
* Drive @ Braves
<2018-06-25 Mon 18:00-21:00>
:PROPERTIES:
:ID:       Ps8llXwO1pbzbAZKdhFxYZFb@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Drive @ Braves Drive @ Braves

Follow on MiLB First Pitch  https //stza.co/+vxSh-2a

Shop  https //stza.co/+vxSh-2b

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Drive @ Braves
END:VALARM
DTSTART:20180625T230000Z
DTEND:20180626T020000Z
UID:Ps8llXwO1pbzbAZKdhFxYZFb@stanza.co
SUMMARY:Drive @ Braves
DESCRIPTION:Drive @ Braves\n\nFollow on MiLB First Pitch: https://stza.co/+vxSh-2a\n\nShop: https://stza.co/+vxSh-2b\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144530Z
LAST-MODIFIED:20180213T144530Z
TRANSP:OPAQUE
END:VEVENT
* Drive @ Braves
<2018-06-26 Tue 12:00-15:00>
:PROPERTIES:
:ID:       EchgO7IHPH_h-PxN6xDecYV-@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Drive @ Braves Drive @ Braves

Follow on MiLB First Pitch  https //stza.co/+vxSl-1u

Shop  https //stza.co/+vxSl-$

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Drive @ Braves
END:VALARM
DTSTART:20180626T170000Z
DTEND:20180626T200000Z
UID:EchgO7IHPH_h-PxN6xDecYV-@stanza.co
SUMMARY:Drive @ Braves
DESCRIPTION:Drive @ Braves\n\nFollow on MiLB First Pitch: https://stza.co/+vxSl-1u\n\nShop: https://stza.co/+vxSl-$\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144530Z
LAST-MODIFIED:20180213T144530Z
TRANSP:OPAQUE
END:VEVENT
* Drive @ GreenJackets
<2018-06-27 Wed 18:05-21:05>
:PROPERTIES:
:ID:       4PbT0_A1P9OTbF4g8rWSSIXV@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Drive @ GreenJackets Drive @ GreenJackets

Follow on MiLB First Pitch  https //stza.co/+xB2_-M

Shop  https //stza.co/+xB2_-a

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Drive @ GreenJackets
END:VALARM
DTSTART:20180627T230500Z
DTEND:20180628T020500Z
UID:4PbT0_A1P9OTbF4g8rWSSIXV@stanza.co
SUMMARY:Drive @ GreenJackets
DESCRIPTION:Drive @ GreenJackets\n\nFollow on MiLB First Pitch: https://stza.co/+xB2_-M\n\nShop: https://stza.co/+xB2_-a\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144530Z
LAST-MODIFIED:20180213T144530Z
TRANSP:OPAQUE
END:VEVENT
* Drive @ GreenJackets
<2018-06-28 Thu 18:05-21:05>
:PROPERTIES:
:ID:       2zWQZyStqlqmXhukCB45xabm@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Drive @ GreenJackets Drive @ GreenJackets

Follow on MiLB First Pitch  https //stza.co/+xB2$-1

Shop  https //stza.co/+xB2$-q

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Drive @ GreenJackets
END:VALARM
DTSTART:20180628T230500Z
DTEND:20180629T020500Z
UID:2zWQZyStqlqmXhukCB45xabm@stanza.co
SUMMARY:Drive @ GreenJackets
DESCRIPTION:Drive @ GreenJackets\n\nFollow on MiLB First Pitch: https://stza.co/+xB2$-1\n\nShop: https://stza.co/+xB2$-q\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144530Z
LAST-MODIFIED:20180213T144530Z
TRANSP:OPAQUE
END:VEVENT
* Drive @ GreenJackets
<2018-06-29 Fri 18:05-21:05>
:PROPERTIES:
:ID:       cCXiWzHUiX0opb8Cg3_-eCab@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Drive @ GreenJackets Drive @ GreenJackets

Follow on MiLB First Pitch  https //stza.co/+xB30-2d

Shop  https //stza.co/+xB30-p

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Drive @ GreenJackets
END:VALARM
DTSTART:20180629T230500Z
DTEND:20180630T020500Z
UID:cCXiWzHUiX0opb8Cg3_-eCab@stanza.co
SUMMARY:Drive @ GreenJackets
DESCRIPTION:Drive @ GreenJackets\n\nFollow on MiLB First Pitch: https://stza.co/+xB30-2d\n\nShop: https://stza.co/+xB30-p\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144530Z
LAST-MODIFIED:20180213T144530Z
TRANSP:OPAQUE
END:VEVENT
* Drive vs. RiverDogs
<2018-06-30 Sat 18:05-21:05>
:PROPERTIES:
:ID:       HQ8hUeXbNlRYTbaRhNxnkLSL@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Drive vs. RiverDogs Drive vs. RiverDogs

Follow on MiLB First Pitch  https //stza.co/+xGCH-1w

Shop  https //stza.co/+xGCH-1V

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Drive vs. RiverDogs
END:VALARM
DTSTART:20180630T230500Z
DTEND:20180701T020500Z
UID:HQ8hUeXbNlRYTbaRhNxnkLSL@stanza.co
SUMMARY:Drive vs. RiverDogs
DESCRIPTION:Drive vs. RiverDogs\n\nFollow on MiLB First Pitch: https://stza.co/+xGCH-1w\n\nShop: https://stza.co/+xGCH-1V\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144530Z
LAST-MODIFIED:20180213T144530Z
TRANSP:OPAQUE
END:VEVENT
* Drive vs. RiverDogs
<2018-07-01 Sun 15:05-18:05>
:PROPERTIES:
:ID:       8FBZtZ9r_w3GPxDS_gKp0nPW@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Drive vs. RiverDogs Drive vs. RiverDogs

Follow on MiLB First Pitch  https //stza.co/+xGCJ-c

Shop  https //stza.co/+xGCJ-E

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Drive vs. RiverDogs
END:VALARM
DTSTART:20180701T200500Z
DTEND:20180701T230500Z
UID:8FBZtZ9r_w3GPxDS_gKp0nPW@stanza.co
SUMMARY:Drive vs. RiverDogs
DESCRIPTION:Drive vs. RiverDogs\n\nFollow on MiLB First Pitch: https://stza.co/+xGCJ-c\n\nShop: https://stza.co/+xGCJ-E\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144530Z
LAST-MODIFIED:20180213T144530Z
TRANSP:OPAQUE
END:VEVENT
* Drive vs. RiverDogs
<2018-07-02 Mon 18:05-21:05>
:PROPERTIES:
:ID:       oXQNK5TMHePGfDcwJ09hUH2X@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Drive vs. RiverDogs Drive vs. RiverDogs

Follow on MiLB First Pitch  https //stza.co/+xGCL-1T

Shop  https //stza.co/+xGCL-2L

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Drive vs. RiverDogs
END:VALARM
DTSTART:20180702T230500Z
DTEND:20180703T020500Z
UID:oXQNK5TMHePGfDcwJ09hUH2X@stanza.co
SUMMARY:Drive vs. RiverDogs
DESCRIPTION:Drive vs. RiverDogs\n\nFollow on MiLB First Pitch: https://stza.co/+xGCL-1T\n\nShop: https://stza.co/+xGCL-2L\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144530Z
LAST-MODIFIED:20180213T144530Z
TRANSP:OPAQUE
END:VEVENT
* Drive vs. RiverDogs
<2018-07-03 Tue 18:05-21:05>
:PROPERTIES:
:ID:       WXHl6XnUggmdzA8TpgW0BUoH@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Drive vs. RiverDogs Drive vs. RiverDogs

Follow on MiLB First Pitch  https //stza.co/+xGCM-1v

Shop  https //stza.co/+xGCM-W

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Drive vs. RiverDogs
END:VALARM
DTSTART:20180703T230500Z
DTEND:20180704T020500Z
UID:WXHl6XnUggmdzA8TpgW0BUoH@stanza.co
SUMMARY:Drive vs. RiverDogs
DESCRIPTION:Drive vs. RiverDogs\n\nFollow on MiLB First Pitch: https://stza.co/+xGCM-1v\n\nShop: https://stza.co/+xGCM-W\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144530Z
LAST-MODIFIED:20180213T144530Z
TRANSP:OPAQUE
END:VEVENT
* Drive @ Fireflies
<2018-07-04 Wed 17:05-20:05>
:PROPERTIES:
:ID:       X4-Rtfw4H2bdMd8TI6e0XDLJ@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Drive @ Fireflies Drive @ Fireflies

Follow on MiLB First Pitch  https //stza.co/+xB3z-3a

Shop  https //stza.co/+xB3z-2

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Drive @ Fireflies
END:VALARM
DTSTART:20180704T220500Z
DTEND:20180705T010500Z
UID:X4-Rtfw4H2bdMd8TI6e0XDLJ@stanza.co
SUMMARY:Drive @ Fireflies
DESCRIPTION:Drive @ Fireflies\n\nFollow on MiLB First Pitch: https://stza.co/+xB3z-3a\n\nShop: https://stza.co/+xB3z-2\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144530Z
LAST-MODIFIED:20180213T144530Z
TRANSP:OPAQUE
END:VEVENT
* Drive @ Fireflies
<2018-07-05 Thu 18:05-21:05>
:PROPERTIES:
:ID:       hJ-EwZPf7rEaAkzCBgivbRU9@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Drive @ Fireflies Drive @ Fireflies

Follow on MiLB First Pitch  https //stza.co/+xB3B-1f

Shop  https //stza.co/+xB3B-2u

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Drive @ Fireflies
END:VALARM
DTSTART:20180705T230500Z
DTEND:20180706T020500Z
UID:hJ-EwZPf7rEaAkzCBgivbRU9@stanza.co
SUMMARY:Drive @ Fireflies
DESCRIPTION:Drive @ Fireflies\n\nFollow on MiLB First Pitch: https://stza.co/+xB3B-1f\n\nShop: https://stza.co/+xB3B-2u\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144530Z
LAST-MODIFIED:20180213T144530Z
TRANSP:OPAQUE
END:VEVENT
* Drive @ Fireflies
<2018-07-06 Fri 18:05-21:05>
:PROPERTIES:
:ID:       9py2L9NaSiu1UfYTtY3FWE5W@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Drive @ Fireflies Drive @ Fireflies

Follow on MiLB First Pitch  https //stza.co/+xB3D-2B

Shop  https //stza.co/+xB3D-2v

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Drive @ Fireflies
END:VALARM
DTSTART:20180706T230500Z
DTEND:20180707T020500Z
UID:9py2L9NaSiu1UfYTtY3FWE5W@stanza.co
SUMMARY:Drive @ Fireflies
DESCRIPTION:Drive @ Fireflies\n\nFollow on MiLB First Pitch: https://stza.co/+xB3D-2B\n\nShop: https://stza.co/+xB3D-2v\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144530Z
LAST-MODIFIED:20180213T144530Z
TRANSP:OPAQUE
END:VEVENT
* Drive @ Tourists
<2018-07-07 Sat 17:05-20:05>
:PROPERTIES:
:ID:       9ilzNlDWlJku1A-czjHXr2g-@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Drive @ Tourists Drive @ Tourists

Follow on MiLB First Pitch  https //stza.co/+vxMC-2d

Shop  https //stza.co/+vxMC-3x

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Drive @ Tourists
END:VALARM
DTSTART:20180707T220500Z
DTEND:20180708T010500Z
UID:9ilzNlDWlJku1A-czjHXr2g-@stanza.co
SUMMARY:Drive @ Tourists
DESCRIPTION:Drive @ Tourists\n\nFollow on MiLB First Pitch: https://stza.co/+vxMC-2d\n\nShop: https://stza.co/+vxMC-3x\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144530Z
LAST-MODIFIED:20180213T144530Z
TRANSP:OPAQUE
END:VEVENT
* Drive @ Tourists
<2018-07-08 Sun 13:05-16:05>
:PROPERTIES:
:ID:       tSHRA0mP3BvmKQdnHhe9jkOO@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Drive @ Tourists Drive @ Tourists

Follow on MiLB First Pitch  https //stza.co/+vxMD-33

Shop  https //stza.co/+vxMD-2n

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Drive @ Tourists
END:VALARM
DTSTART:20180708T180500Z
DTEND:20180708T210500Z
UID:tSHRA0mP3BvmKQdnHhe9jkOO@stanza.co
SUMMARY:Drive @ Tourists
DESCRIPTION:Drive @ Tourists\n\nFollow on MiLB First Pitch: https://stza.co/+vxMD-33\n\nShop: https://stza.co/+vxMD-2n\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144530Z
LAST-MODIFIED:20180213T144530Z
TRANSP:OPAQUE
END:VEVENT
* Drive @ Tourists
<2018-07-09 Mon 18:05-21:05>
:PROPERTIES:
:ID:       cEQb6huscNXLt6ULibgQO-3y@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Drive @ Tourists Drive @ Tourists

Follow on MiLB First Pitch  https //stza.co/+vxME-2I

Shop  https //stza.co/+vxME-3b

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Drive @ Tourists
END:VALARM
DTSTART:20180709T230500Z
DTEND:20180710T020500Z
UID:cEQb6huscNXLt6ULibgQO-3y@stanza.co
SUMMARY:Drive @ Tourists
DESCRIPTION:Drive @ Tourists\n\nFollow on MiLB First Pitch: https://stza.co/+vxME-2I\n\nShop: https://stza.co/+vxME-3b\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144530Z
LAST-MODIFIED:20180213T144530Z
TRANSP:OPAQUE
END:VEVENT
* Drive vs. Braves
<2018-07-11 Wed 18:05-21:05>
:PROPERTIES:
:ID:       e4hwTR3W1YAFoP8C2sFNFZev@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Drive vs. Braves Drive vs. Braves

Follow on MiLB First Pitch  https //stza.co/+xGCP-2G

Shop  https //stza.co/+xGCP-q

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Drive vs. Braves
END:VALARM
DTSTART:20180711T230500Z
DTEND:20180712T020500Z
UID:e4hwTR3W1YAFoP8C2sFNFZev@stanza.co
SUMMARY:Drive vs. Braves
DESCRIPTION:Drive vs. Braves\n\nFollow on MiLB First Pitch: https://stza.co/+xGCP-2G\n\nShop: https://stza.co/+xGCP-q\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144530Z
LAST-MODIFIED:20180213T144530Z
TRANSP:OPAQUE
END:VEVENT
* Drive vs. Braves
<2018-07-12 Thu 18:05-21:05>
:PROPERTIES:
:ID:       b3H3sKwP3aJIjd_X0InMQROB@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Drive vs. Braves Drive vs. Braves

Follow on MiLB First Pitch  https //stza.co/+xGCR-t

Shop  https //stza.co/+xGCR-2g

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Drive vs. Braves
END:VALARM
DTSTART:20180712T230500Z
DTEND:20180713T020500Z
UID:b3H3sKwP3aJIjd_X0InMQROB@stanza.co
SUMMARY:Drive vs. Braves
DESCRIPTION:Drive vs. Braves\n\nFollow on MiLB First Pitch: https://stza.co/+xGCR-t\n\nShop: https://stza.co/+xGCR-2g\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144530Z
LAST-MODIFIED:20180213T144530Z
TRANSP:OPAQUE
END:VEVENT
* Drive vs. Braves
<2018-07-13 Fri 18:05-21:05>
:PROPERTIES:
:ID:       LhKNhALpzRXRvWWo9sgDJtgB@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Drive vs. Braves Drive vs. Braves

Follow on MiLB First Pitch  https //stza.co/+xGCT-q

Shop  https //stza.co/+xGCT-24

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Drive vs. Braves
END:VALARM
DTSTART:20180713T230500Z
DTEND:20180714T020500Z
UID:LhKNhALpzRXRvWWo9sgDJtgB@stanza.co
SUMMARY:Drive vs. Braves
DESCRIPTION:Drive vs. Braves\n\nFollow on MiLB First Pitch: https://stza.co/+xGCT-q\n\nShop: https://stza.co/+xGCT-24\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144530Z
LAST-MODIFIED:20180213T144530Z
TRANSP:OPAQUE
END:VEVENT
* Drive vs. Legends
<2018-07-14 Sat 18:05-21:05>
:PROPERTIES:
:ID:       DFDkHD_IVYPvNeCHuMuQl4Dr@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Drive vs. Legends Drive vs. Legends

Follow on MiLB First Pitch  https //stza.co/+xGCV-3e

Shop  https //stza.co/+xGCV-1e

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Drive vs. Legends
END:VALARM
DTSTART:20180714T230500Z
DTEND:20180715T020500Z
UID:DFDkHD_IVYPvNeCHuMuQl4Dr@stanza.co
SUMMARY:Drive vs. Legends
DESCRIPTION:Drive vs. Legends\n\nFollow on MiLB First Pitch: https://stza.co/+xGCV-3e\n\nShop: https://stza.co/+xGCV-1e\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144530Z
LAST-MODIFIED:20180213T144530Z
TRANSP:OPAQUE
END:VEVENT
* Drive vs. Legends
<2018-07-15 Sun 15:05-18:05>
:PROPERTIES:
:ID:       IEKtH7Boi5Gu8QBQXMAkAjyu@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Drive vs. Legends Drive vs. Legends

Follow on MiLB First Pitch  https //stza.co/+xGCW-2W

Shop  https //stza.co/+xGCW-2d

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Drive vs. Legends
END:VALARM
DTSTART:20180715T200500Z
DTEND:20180715T230500Z
UID:IEKtH7Boi5Gu8QBQXMAkAjyu@stanza.co
SUMMARY:Drive vs. Legends
DESCRIPTION:Drive vs. Legends\n\nFollow on MiLB First Pitch: https://stza.co/+xGCW-2W\n\nShop: https://stza.co/+xGCW-2d\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144530Z
LAST-MODIFIED:20180213T144530Z
TRANSP:OPAQUE
END:VEVENT
* Drive vs. Legends
<2018-07-16 Mon 18:05-21:05>
:PROPERTIES:
:ID:       HT-n_SWUoGBBq6y0aHveY7p5@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Drive vs. Legends Drive vs. Legends

Follow on MiLB First Pitch  https //stza.co/+xGCY-2a

Shop  https //stza.co/+xGCY-1H

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Drive vs. Legends
END:VALARM
DTSTART:20180716T230500Z
DTEND:20180717T020500Z
UID:HT-n_SWUoGBBq6y0aHveY7p5@stanza.co
SUMMARY:Drive vs. Legends
DESCRIPTION:Drive vs. Legends\n\nFollow on MiLB First Pitch: https://stza.co/+xGCY-2a\n\nShop: https://stza.co/+xGCY-1H\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144530Z
LAST-MODIFIED:20180213T144530Z
TRANSP:OPAQUE
END:VEVENT
* Drive vs. Legends
<2018-07-17 Tue 10:05-13:05>
:PROPERTIES:
:ID:       ptJaG5YSFS29T7HizxEZkUVP@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Drive vs. Legends Drive vs. Legends

Follow on MiLB First Pitch  https //stza.co/+xGC$-3s

Shop  https //stza.co/+xGC$-x

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Drive vs. Legends
END:VALARM
DTSTART:20180717T150500Z
DTEND:20180717T180500Z
UID:ptJaG5YSFS29T7HizxEZkUVP@stanza.co
SUMMARY:Drive vs. Legends
DESCRIPTION:Drive vs. Legends\n\nFollow on MiLB First Pitch: https://stza.co/+xGC$-3s\n\nShop: https://stza.co/+xGC$-x\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144530Z
LAST-MODIFIED:20180213T144530Z
TRANSP:OPAQUE
END:VEVENT
* Drive @ Tourists
<2018-07-19 Thu 18:05-21:05>
:PROPERTIES:
:ID:       _78IMZEE-hlNkEJ8Se4BUYw6@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Drive @ Tourists Drive @ Tourists

Follow on MiLB First Pitch  https //stza.co/+vxMF-16

Shop  https //stza.co/+vxMF-V

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Drive @ Tourists
END:VALARM
DTSTART:20180719T230500Z
DTEND:20180720T020500Z
UID:_78IMZEE-hlNkEJ8Se4BUYw6@stanza.co
SUMMARY:Drive @ Tourists
DESCRIPTION:Drive @ Tourists\n\nFollow on MiLB First Pitch: https://stza.co/+vxMF-16\n\nShop: https://stza.co/+vxMF-V\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144530Z
LAST-MODIFIED:20180213T144530Z
TRANSP:OPAQUE
END:VEVENT
* Drive @ Tourists
<2018-07-20 Fri 18:05-21:05>
:PROPERTIES:
:ID:       Y3QnqxmLb0pU7kqvFraBRFSe@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Drive @ Tourists Drive @ Tourists

Follow on MiLB First Pitch  https //stza.co/+vxMG-1Z

Shop  https //stza.co/+vxMG-31

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Drive @ Tourists
END:VALARM
DTSTART:20180720T230500Z
DTEND:20180721T020500Z
UID:Y3QnqxmLb0pU7kqvFraBRFSe@stanza.co
SUMMARY:Drive @ Tourists
DESCRIPTION:Drive @ Tourists\n\nFollow on MiLB First Pitch: https://stza.co/+vxMG-1Z\n\nShop: https://stza.co/+vxMG-31\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144530Z
LAST-MODIFIED:20180213T144530Z
TRANSP:OPAQUE
END:VEVENT
* Drive @ Tourists
<2018-07-21 Sat 17:05-20:05>
:PROPERTIES:
:ID:       TlYQgpquu2NVncojjcZ7wTz5@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Drive @ Tourists Drive @ Tourists

Follow on MiLB First Pitch  https //stza.co/+vxMH-1Z

Shop  https //stza.co/+vxMH-3s

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Drive @ Tourists
END:VALARM
DTSTART:20180721T220500Z
DTEND:20180722T010500Z
UID:TlYQgpquu2NVncojjcZ7wTz5@stanza.co
SUMMARY:Drive @ Tourists
DESCRIPTION:Drive @ Tourists\n\nFollow on MiLB First Pitch: https://stza.co/+vxMH-1Z\n\nShop: https://stza.co/+vxMH-3s\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144530Z
LAST-MODIFIED:20180213T144530Z
TRANSP:OPAQUE
END:VEVENT
* Drive @ Tourists
<2018-07-22 Sun 13:05-16:05>
:PROPERTIES:
:ID:       S5hkgAaZK5cS-Up6UwgplI0T@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Drive @ Tourists Drive @ Tourists

Follow on MiLB First Pitch  https //stza.co/+vxMI-2N

Shop  https //stza.co/+vxMI-17

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Drive @ Tourists
END:VALARM
DTSTART:20180722T180500Z
DTEND:20180722T210500Z
UID:S5hkgAaZK5cS-Up6UwgplI0T@stanza.co
SUMMARY:Drive @ Tourists
DESCRIPTION:Drive @ Tourists\n\nFollow on MiLB First Pitch: https://stza.co/+vxMI-2N\n\nShop: https://stza.co/+vxMI-17\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144530Z
LAST-MODIFIED:20180213T144530Z
TRANSP:OPAQUE
END:VEVENT
* Drive vs. Crawdads
<2018-07-23 Mon 18:05-21:05>
:PROPERTIES:
:ID:       tUXfRhvf5iARfFPE4oruIR7q@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Drive vs. Crawdads Drive vs. Crawdads

Follow on MiLB First Pitch  https //stza.co/+xGD1-22

Shop  https //stza.co/+xGD1-14

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Drive vs. Crawdads
END:VALARM
DTSTART:20180723T230500Z
DTEND:20180724T020500Z
UID:tUXfRhvf5iARfFPE4oruIR7q@stanza.co
SUMMARY:Drive vs. Crawdads
DESCRIPTION:Drive vs. Crawdads\n\nFollow on MiLB First Pitch: https://stza.co/+xGD1-22\n\nShop: https://stza.co/+xGD1-14\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144530Z
LAST-MODIFIED:20180213T144530Z
TRANSP:OPAQUE
END:VEVENT
* Drive vs. Crawdads
<2018-07-24 Tue 18:05-21:05>
:PROPERTIES:
:ID:       j9iVoN-cR9gQxkgWOMzdiPWr@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Drive vs. Crawdads Drive vs. Crawdads

Follow on MiLB First Pitch  https //stza.co/+xGD3-3b

Shop  https //stza.co/+xGD3-2r

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Drive vs. Crawdads
END:VALARM
DTSTART:20180724T230500Z
DTEND:20180725T020500Z
UID:j9iVoN-cR9gQxkgWOMzdiPWr@stanza.co
SUMMARY:Drive vs. Crawdads
DESCRIPTION:Drive vs. Crawdads\n\nFollow on MiLB First Pitch: https://stza.co/+xGD3-3b\n\nShop: https://stza.co/+xGD3-2r\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144530Z
LAST-MODIFIED:20180213T144530Z
TRANSP:OPAQUE
END:VEVENT
* Drive vs. Crawdads
<2018-07-25 Wed 18:05-21:05>
:PROPERTIES:
:ID:       rOL0y2yLwnj5ibaDRUf0LnN3@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Drive vs. Crawdads Drive vs. Crawdads

Follow on MiLB First Pitch  https //stza.co/+xGD5-39

Shop  https //stza.co/+xGD5-27

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Drive vs. Crawdads
END:VALARM
DTSTART:20180725T230500Z
DTEND:20180726T020500Z
UID:rOL0y2yLwnj5ibaDRUf0LnN3@stanza.co
SUMMARY:Drive vs. Crawdads
DESCRIPTION:Drive vs. Crawdads\n\nFollow on MiLB First Pitch: https://stza.co/+xGD5-39\n\nShop: https://stza.co/+xGD5-27\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144530Z
LAST-MODIFIED:20180213T144530Z
TRANSP:OPAQUE
END:VEVENT
* Drive vs. Crawdads
<2018-07-26 Thu 18:05-21:05>
:PROPERTIES:
:ID:       IhQ-47hXgVscRY94cDotudyC@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Drive vs. Crawdads Drive vs. Crawdads

Follow on MiLB First Pitch  https //stza.co/+xGD6-q

Shop  https //stza.co/+xGD6-2U

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Drive vs. Crawdads
END:VALARM
DTSTART:20180726T230500Z
DTEND:20180727T020500Z
UID:IhQ-47hXgVscRY94cDotudyC@stanza.co
SUMMARY:Drive vs. Crawdads
DESCRIPTION:Drive vs. Crawdads\n\nFollow on MiLB First Pitch: https://stza.co/+xGD6-q\n\nShop: https://stza.co/+xGD6-2U\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144530Z
LAST-MODIFIED:20180213T144530Z
TRANSP:OPAQUE
END:VEVENT
* Drive @ RiverDogs
<2018-07-27 Fri 18:05-21:05>
:PROPERTIES:
:ID:       LCwqxSN9bfTwj1I3t5UY9faT@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Drive @ RiverDogs Drive @ RiverDogs

Follow on MiLB First Pitch  https //stza.co/+vxMW-2_

Shop  https //stza.co/+vxMW-E

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Drive @ RiverDogs
END:VALARM
DTSTART:20180727T230500Z
DTEND:20180728T020500Z
UID:LCwqxSN9bfTwj1I3t5UY9faT@stanza.co
SUMMARY:Drive @ RiverDogs
DESCRIPTION:Drive @ RiverDogs\n\nFollow on MiLB First Pitch: https://stza.co/+vxMW-2_\n\nShop: https://stza.co/+vxMW-E\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144530Z
LAST-MODIFIED:20180213T144530Z
TRANSP:OPAQUE
END:VEVENT
* Drive @ RiverDogs
<2018-07-28 Sat 17:05-20:05>
:PROPERTIES:
:ID:       LnSRbO4S231MiO9gs7gpIpBF@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Drive @ RiverDogs Drive @ RiverDogs

Follow on MiLB First Pitch  https //stza.co/+vxMX-1Y

Shop  https //stza.co/+vxMX-1L

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Drive @ RiverDogs
END:VALARM
DTSTART:20180728T220500Z
DTEND:20180729T010500Z
UID:LnSRbO4S231MiO9gs7gpIpBF@stanza.co
SUMMARY:Drive @ RiverDogs
DESCRIPTION:Drive @ RiverDogs\n\nFollow on MiLB First Pitch: https://stza.co/+vxMX-1Y\n\nShop: https://stza.co/+vxMX-1L\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144530Z
LAST-MODIFIED:20180213T144530Z
TRANSP:OPAQUE
END:VEVENT
* Drive @ RiverDogs
<2018-07-29 Sun 16:05-19:05>
:PROPERTIES:
:ID:       kUBGNW0Sb1MOcyrihiXoHdu7@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Drive @ RiverDogs Drive @ RiverDogs

Follow on MiLB First Pitch  https //stza.co/+vxMY-2P

Shop  https //stza.co/+vxMY-27

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Drive @ RiverDogs
END:VALARM
DTSTART:20180729T210500Z
DTEND:20180730T000500Z
UID:kUBGNW0Sb1MOcyrihiXoHdu7@stanza.co
SUMMARY:Drive @ RiverDogs
DESCRIPTION:Drive @ RiverDogs\n\nFollow on MiLB First Pitch: https://stza.co/+vxMY-2P\n\nShop: https://stza.co/+vxMY-27\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144530Z
LAST-MODIFIED:20180213T144530Z
TRANSP:OPAQUE
END:VEVENT
* Drive vs. Tourists
<2018-07-30 Mon 18:05-21:05>
:PROPERTIES:
:ID:       HZmy08EmMxbEShrzzneeh8PQ@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Drive vs. Tourists Drive vs. Tourists

Follow on MiLB First Pitch  https //stza.co/+xGD8-3X

Shop  https //stza.co/+xGD8-x

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Drive vs. Tourists
END:VALARM
DTSTART:20180730T230500Z
DTEND:20180731T020500Z
UID:HZmy08EmMxbEShrzzneeh8PQ@stanza.co
SUMMARY:Drive vs. Tourists
DESCRIPTION:Drive vs. Tourists\n\nFollow on MiLB First Pitch: https://stza.co/+xGD8-3X\n\nShop: https://stza.co/+xGD8-x\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144530Z
LAST-MODIFIED:20180213T144530Z
TRANSP:OPAQUE
END:VEVENT
* Drive vs. Tourists
<2018-07-31 Tue 18:05-21:05>
:PROPERTIES:
:ID:       ESRDjBOWtUwasoW4UNTSv4r9@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Drive vs. Tourists Drive vs. Tourists

Follow on MiLB First Pitch  https //stza.co/+xGDa-2Y

Shop  https //stza.co/+xGDa-2P

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Drive vs. Tourists
END:VALARM
DTSTART:20180731T230500Z
DTEND:20180801T020500Z
UID:ESRDjBOWtUwasoW4UNTSv4r9@stanza.co
SUMMARY:Drive vs. Tourists
DESCRIPTION:Drive vs. Tourists\n\nFollow on MiLB First Pitch: https://stza.co/+xGDa-2Y\n\nShop: https://stza.co/+xGDa-2P\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144530Z
LAST-MODIFIED:20180213T144530Z
TRANSP:OPAQUE
END:VEVENT
* Drive vs. Tourists
<2018-08-01 Wed 18:05-21:05>
:PROPERTIES:
:ID:       apU-reeypDt_-3wSbGcALjsY@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Drive vs. Tourists Drive vs. Tourists

Follow on MiLB First Pitch  https //stza.co/+xGDc-1H

Shop  https //stza.co/+xGDc-4

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Drive vs. Tourists
END:VALARM
DTSTART:20180801T230500Z
DTEND:20180802T020500Z
UID:apU-reeypDt_-3wSbGcALjsY@stanza.co
SUMMARY:Drive vs. Tourists
DESCRIPTION:Drive vs. Tourists\n\nFollow on MiLB First Pitch: https://stza.co/+xGDc-1H\n\nShop: https://stza.co/+xGDc-4\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144530Z
LAST-MODIFIED:20180213T144530Z
TRANSP:OPAQUE
END:VEVENT
* Drive vs. Braves
<2018-08-02 Thu 18:05-21:05>
:PROPERTIES:
:ID:       ymeBWpndVQQPjquAYgxqPOdY@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Drive vs. Braves Drive vs. Braves

Follow on MiLB First Pitch  https //stza.co/+xGDe-1f

Shop  https //stza.co/+xGDe-M

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Drive vs. Braves
END:VALARM
DTSTART:20180802T230500Z
DTEND:20180803T020500Z
UID:ymeBWpndVQQPjquAYgxqPOdY@stanza.co
SUMMARY:Drive vs. Braves
DESCRIPTION:Drive vs. Braves\n\nFollow on MiLB First Pitch: https://stza.co/+xGDe-1f\n\nShop: https://stza.co/+xGDe-M\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144530Z
LAST-MODIFIED:20180213T144530Z
TRANSP:OPAQUE
END:VEVENT
* Drive vs. Braves
<2018-08-03 Fri 18:05-21:05>
:PROPERTIES:
:ID:       cSr0We1-il0gmhSkeW6MpuVP@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Drive vs. Braves Drive vs. Braves

Follow on MiLB First Pitch  https //stza.co/+xGDg-2Q

Shop  https //stza.co/+xGDg-1z

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Drive vs. Braves
END:VALARM
DTSTART:20180803T230500Z
DTEND:20180804T020500Z
UID:cSr0We1-il0gmhSkeW6MpuVP@stanza.co
SUMMARY:Drive vs. Braves
DESCRIPTION:Drive vs. Braves\n\nFollow on MiLB First Pitch: https://stza.co/+xGDg-2Q\n\nShop: https://stza.co/+xGDg-1z\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144530Z
LAST-MODIFIED:20180213T144530Z
TRANSP:OPAQUE
END:VEVENT
* Drive vs. Braves
<2018-08-04 Sat 18:05-21:05>
:PROPERTIES:
:ID:       AKUDfcoH4UyL3kNFN9pNMcGE@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Drive vs. Braves Drive vs. Braves

Follow on MiLB First Pitch  https //stza.co/+xGDj-25

Shop  https //stza.co/+xGDj-2

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Drive vs. Braves
END:VALARM
DTSTART:20180804T230500Z
DTEND:20180805T020500Z
UID:AKUDfcoH4UyL3kNFN9pNMcGE@stanza.co
SUMMARY:Drive vs. Braves
DESCRIPTION:Drive vs. Braves\n\nFollow on MiLB First Pitch: https://stza.co/+xGDj-25\n\nShop: https://stza.co/+xGDj-2\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144530Z
LAST-MODIFIED:20180213T144530Z
TRANSP:OPAQUE
END:VEVENT
* Drive vs. Braves
<2018-08-05 Sun 15:05-18:05>
:PROPERTIES:
:ID:       SLcwmfoZT9MoY1OG60L6x1Ba@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Drive vs. Braves Drive vs. Braves

Follow on MiLB First Pitch  https //stza.co/+xGDl-1b

Shop  https //stza.co/+xGDl-3S

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Drive vs. Braves
END:VALARM
DTSTART:20180805T200500Z
DTEND:20180805T230500Z
UID:SLcwmfoZT9MoY1OG60L6x1Ba@stanza.co
SUMMARY:Drive vs. Braves
DESCRIPTION:Drive vs. Braves\n\nFollow on MiLB First Pitch: https://stza.co/+xGDl-1b\n\nShop: https://stza.co/+xGDl-3S\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144530Z
LAST-MODIFIED:20180213T144530Z
TRANSP:OPAQUE
END:VEVENT
* Drive @ Fireflies
<2018-08-07 Tue 18:05-21:05>
:PROPERTIES:
:ID:       49T1QOmCtDIIk-iC9-XZTzlF@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Drive @ Fireflies Drive @ Fireflies

Follow on MiLB First Pitch  https //stza.co/+xB3E-3n

Shop  https //stza.co/+xB3E-2Y

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Drive @ Fireflies
END:VALARM
DTSTART:20180807T230500Z
DTEND:20180808T020500Z
UID:49T1QOmCtDIIk-iC9-XZTzlF@stanza.co
SUMMARY:Drive @ Fireflies
DESCRIPTION:Drive @ Fireflies\n\nFollow on MiLB First Pitch: https://stza.co/+xB3E-3n\n\nShop: https://stza.co/+xB3E-2Y\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144530Z
LAST-MODIFIED:20180213T144530Z
TRANSP:OPAQUE
END:VEVENT
* Drive @ Fireflies
<2018-08-08 Wed 18:05-21:05>
:PROPERTIES:
:ID:       vBooM--o8MGJXbmBy0Adtk-t@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Drive @ Fireflies Drive @ Fireflies

Follow on MiLB First Pitch  https //stza.co/+xB3G-o

Shop  https //stza.co/+xB3G-23

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Drive @ Fireflies
END:VALARM
DTSTART:20180808T230500Z
DTEND:20180809T020500Z
UID:vBooM--o8MGJXbmBy0Adtk-t@stanza.co
SUMMARY:Drive @ Fireflies
DESCRIPTION:Drive @ Fireflies\n\nFollow on MiLB First Pitch: https://stza.co/+xB3G-o\n\nShop: https://stza.co/+xB3G-23\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144530Z
LAST-MODIFIED:20180213T144530Z
TRANSP:OPAQUE
END:VEVENT
* Drive @ Fireflies
<2018-08-09 Thu 18:05-21:05>
:PROPERTIES:
:ID:       BPjPrMttNBvXy7FRcL5X8XQP@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Drive @ Fireflies Drive @ Fireflies

Follow on MiLB First Pitch  https //stza.co/+xB3I-3E

Shop  https //stza.co/+xB3I-1_

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Drive @ Fireflies
END:VALARM
DTSTART:20180809T230500Z
DTEND:20180810T020500Z
UID:BPjPrMttNBvXy7FRcL5X8XQP@stanza.co
SUMMARY:Drive @ Fireflies
DESCRIPTION:Drive @ Fireflies\n\nFollow on MiLB First Pitch: https://stza.co/+xB3I-3E\n\nShop: https://stza.co/+xB3I-1_\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144530Z
LAST-MODIFIED:20180213T144530Z
TRANSP:OPAQUE
END:VEVENT
* Drive @ GreenJackets
<2018-08-10 Fri 18:05-21:05>
:PROPERTIES:
:ID:       uQZEqqbq9SQ__rM058tb3Ujq@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Drive @ GreenJackets Drive @ GreenJackets

Follow on MiLB First Pitch  https //stza.co/+xB31-M

Shop  https //stza.co/+xB31-2Q

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Drive @ GreenJackets
END:VALARM
DTSTART:20180810T230500Z
DTEND:20180811T020500Z
UID:uQZEqqbq9SQ__rM058tb3Ujq@stanza.co
SUMMARY:Drive @ GreenJackets
DESCRIPTION:Drive @ GreenJackets\n\nFollow on MiLB First Pitch: https://stza.co/+xB31-M\n\nShop: https://stza.co/+xB31-2Q\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144530Z
LAST-MODIFIED:20180213T144530Z
TRANSP:OPAQUE
END:VEVENT
* Drive @ GreenJackets
<2018-08-11 Sat 17:05-20:05>
:PROPERTIES:
:ID:       bzOziO1gBWKNQg2Ez4FSkpVl@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Drive @ GreenJackets Drive @ GreenJackets

Follow on MiLB First Pitch  https //stza.co/+xB32-1Y

Shop  https //stza.co/+xB32-1$

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Drive @ GreenJackets
END:VALARM
DTSTART:20180811T220500Z
DTEND:20180812T010500Z
UID:bzOziO1gBWKNQg2Ez4FSkpVl@stanza.co
SUMMARY:Drive @ GreenJackets
DESCRIPTION:Drive @ GreenJackets\n\nFollow on MiLB First Pitch: https://stza.co/+xB32-1Y\n\nShop: https://stza.co/+xB32-1$\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144530Z
LAST-MODIFIED:20180213T144530Z
TRANSP:OPAQUE
END:VEVENT
* Drive @ GreenJackets
<2018-08-12 Sun 16:05-19:05>
:PROPERTIES:
:ID:       ezjOEQh-zy3vu684uHStNpWU@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Drive @ GreenJackets Drive @ GreenJackets

Follow on MiLB First Pitch  https //stza.co/+xBSO-1b

Shop  https //stza.co/+xBSO-1U

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Drive @ GreenJackets
END:VALARM
DTSTART:20180812T210500Z
DTEND:20180813T000500Z
UID:ezjOEQh-zy3vu684uHStNpWU@stanza.co
SUMMARY:Drive @ GreenJackets
DESCRIPTION:Drive @ GreenJackets\n\nFollow on MiLB First Pitch: https://stza.co/+xBSO-1b\n\nShop: https://stza.co/+xBSO-1U\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144530Z
LAST-MODIFIED:20180213T144530Z
TRANSP:OPAQUE
END:VEVENT
* Drive @ GreenJackets
<2018-08-13 Mon 18:05-21:05>
:PROPERTIES:
:ID:       VISNPFrkRFAlE6Bzii5bm8O4@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Drive @ GreenJackets Drive @ GreenJackets

Follow on MiLB First Pitch  https //stza.co/+xBSP-3u

Shop  https //stza.co/+xBSP-v

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Drive @ GreenJackets
END:VALARM
DTSTART:20180813T230500Z
DTEND:20180814T020500Z
UID:VISNPFrkRFAlE6Bzii5bm8O4@stanza.co
SUMMARY:Drive @ GreenJackets
DESCRIPTION:Drive @ GreenJackets\n\nFollow on MiLB First Pitch: https://stza.co/+xBSP-3u\n\nShop: https://stza.co/+xBSP-v\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144530Z
LAST-MODIFIED:20180213T144530Z
TRANSP:OPAQUE
END:VEVENT
* Drive vs. Grasshoppers
<2018-08-15 Wed 18:05-21:05>
:PROPERTIES:
:ID:       mZZxqoxmCJP6LFN8M5wSA-FT@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Drive vs. Grasshoppers Drive vs. Grasshoppers

Follow on MiLB First Pitch  https //stza.co/+xGDn-2Y

Shop  https //stza.co/+xGDn-2W

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Drive vs. Grasshoppers
END:VALARM
DTSTART:20180815T230500Z
DTEND:20180816T020500Z
UID:mZZxqoxmCJP6LFN8M5wSA-FT@stanza.co
SUMMARY:Drive vs. Grasshoppers
DESCRIPTION:Drive vs. Grasshoppers\n\nFollow on MiLB First Pitch: https://stza.co/+xGDn-2Y\n\nShop: https://stza.co/+xGDn-2W\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144530Z
LAST-MODIFIED:20180213T144530Z
TRANSP:OPAQUE
END:VEVENT
* Drive vs. Grasshoppers
<2018-08-16 Thu 18:05-21:05>
:PROPERTIES:
:ID:       b3XL9a_v1Hf3TiqbLv4E1gbx@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Drive vs. Grasshoppers Drive vs. Grasshoppers

Follow on MiLB First Pitch  https //stza.co/+xGDo-V

Shop  https //stza.co/+xGDo-3n

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Drive vs. Grasshoppers
END:VALARM
DTSTART:20180816T230500Z
DTEND:20180817T020500Z
UID:b3XL9a_v1Hf3TiqbLv4E1gbx@stanza.co
SUMMARY:Drive vs. Grasshoppers
DESCRIPTION:Drive vs. Grasshoppers\n\nFollow on MiLB First Pitch: https://stza.co/+xGDo-V\n\nShop: https://stza.co/+xGDo-3n\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144530Z
LAST-MODIFIED:20180213T144530Z
TRANSP:OPAQUE
END:VEVENT
* Drive vs. Grasshoppers
<2018-08-17 Fri 18:05-21:05>
:PROPERTIES:
:ID:       N_Yd_YadOfywruATZ2ANfpVl@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Drive vs. Grasshoppers Drive vs. Grasshoppers

Follow on MiLB First Pitch  https //stza.co/+xGDr-3O

Shop  https //stza.co/+xGDr-p

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Drive vs. Grasshoppers
END:VALARM
DTSTART:20180817T230500Z
DTEND:20180818T020500Z
UID:N_Yd_YadOfywruATZ2ANfpVl@stanza.co
SUMMARY:Drive vs. Grasshoppers
DESCRIPTION:Drive vs. Grasshoppers\n\nFollow on MiLB First Pitch: https://stza.co/+xGDr-3O\n\nShop: https://stza.co/+xGDr-p\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144530Z
LAST-MODIFIED:20180213T144530Z
TRANSP:OPAQUE
END:VEVENT
* Drive vs. Crawdads
<2018-08-18 Sat 18:05-21:05>
:PROPERTIES:
:ID:       BxGyGdWEVfR_zl5l_KPVAlu_@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Drive vs. Crawdads Drive vs. Crawdads

Follow on MiLB First Pitch  https //stza.co/+xGDs-3z

Shop  https //stza.co/+xGDs-1P

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Drive vs. Crawdads
END:VALARM
DTSTART:20180818T230500Z
DTEND:20180819T020500Z
UID:BxGyGdWEVfR_zl5l_KPVAlu_@stanza.co
SUMMARY:Drive vs. Crawdads
DESCRIPTION:Drive vs. Crawdads\n\nFollow on MiLB First Pitch: https://stza.co/+xGDs-3z\n\nShop: https://stza.co/+xGDs-1P\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144530Z
LAST-MODIFIED:20180213T144530Z
TRANSP:OPAQUE
END:VEVENT
* Drive vs. Crawdads
<2018-08-19 Sun 15:05-18:05>
:PROPERTIES:
:ID:       qhFF-p4_3ts54u_AtJWPzQf9@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Drive vs. Crawdads Drive vs. Crawdads

Follow on MiLB First Pitch  https //stza.co/+xGDv-27

Shop  https //stza.co/+xGDv-b

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Drive vs. Crawdads
END:VALARM
DTSTART:20180819T200500Z
DTEND:20180819T230500Z
UID:qhFF-p4_3ts54u_AtJWPzQf9@stanza.co
SUMMARY:Drive vs. Crawdads
DESCRIPTION:Drive vs. Crawdads\n\nFollow on MiLB First Pitch: https://stza.co/+xGDv-27\n\nShop: https://stza.co/+xGDv-b\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144530Z
LAST-MODIFIED:20180213T144530Z
TRANSP:OPAQUE
END:VEVENT
* Drive vs. Crawdads
<2018-08-20 Mon 18:05-21:05>
:PROPERTIES:
:ID:       D5D2QosXA13SPM16T8Q2w0tE@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Drive vs. Crawdads Drive vs. Crawdads

Follow on MiLB First Pitch  https //stza.co/+xGDw-3j

Shop  https //stza.co/+xGDw-3F

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Drive vs. Crawdads
END:VALARM
DTSTART:20180820T230500Z
DTEND:20180821T020500Z
UID:D5D2QosXA13SPM16T8Q2w0tE@stanza.co
SUMMARY:Drive vs. Crawdads
DESCRIPTION:Drive vs. Crawdads\n\nFollow on MiLB First Pitch: https://stza.co/+xGDw-3j\n\nShop: https://stza.co/+xGDw-3F\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144530Z
LAST-MODIFIED:20180213T144530Z
TRANSP:OPAQUE
END:VEVENT
* Drive vs. Crawdads
<2018-08-21 Tue 18:05-21:05>
:PROPERTIES:
:ID:       i5rgEwwPgKSwCQq4nfxWfMWA@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Drive vs. Crawdads Drive vs. Crawdads

Follow on MiLB First Pitch  https //stza.co/+xGDz-3d

Shop  https //stza.co/+xGDz-2W

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Drive vs. Crawdads
END:VALARM
DTSTART:20180821T230500Z
DTEND:20180822T020500Z
UID:i5rgEwwPgKSwCQq4nfxWfMWA@stanza.co
SUMMARY:Drive vs. Crawdads
DESCRIPTION:Drive vs. Crawdads\n\nFollow on MiLB First Pitch: https://stza.co/+xGDz-3d\n\nShop: https://stza.co/+xGDz-2W\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144530Z
LAST-MODIFIED:20180213T144530Z
TRANSP:OPAQUE
END:VEVENT
* Drive @ RiverDogs
<2018-08-23 Thu 18:05-21:05>
:PROPERTIES:
:ID:       C805VA3AJkCN4muzrUx0gh-9@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Drive @ RiverDogs Drive @ RiverDogs

Follow on MiLB First Pitch  https //stza.co/+vxMZ-w

Shop  https //stza.co/+vxMZ-3g

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Drive @ RiverDogs
END:VALARM
DTSTART:20180823T230500Z
DTEND:20180824T020500Z
UID:C805VA3AJkCN4muzrUx0gh-9@stanza.co
SUMMARY:Drive @ RiverDogs
DESCRIPTION:Drive @ RiverDogs\n\nFollow on MiLB First Pitch: https://stza.co/+vxMZ-w\n\nShop: https://stza.co/+vxMZ-3g\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144530Z
LAST-MODIFIED:20180213T144530Z
TRANSP:OPAQUE
END:VEVENT
* Drive @ RiverDogs
<2018-08-24 Fri 18:05-21:05>
:PROPERTIES:
:ID:       OBWH-NrPfwPYpADthJdELa8j@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Drive @ RiverDogs Drive @ RiverDogs

Follow on MiLB First Pitch  https //stza.co/+vxN4-2A

Shop  https //stza.co/+vxN4-3p

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Drive @ RiverDogs
END:VALARM
DTSTART:20180824T230500Z
DTEND:20180825T020500Z
UID:OBWH-NrPfwPYpADthJdELa8j@stanza.co
SUMMARY:Drive @ RiverDogs
DESCRIPTION:Drive @ RiverDogs\n\nFollow on MiLB First Pitch: https://stza.co/+vxN4-2A\n\nShop: https://stza.co/+vxN4-3p\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144530Z
LAST-MODIFIED:20180213T144530Z
TRANSP:OPAQUE
END:VEVENT
* Drive @ RiverDogs
<2018-08-25 Sat 17:05-20:05>
:PROPERTIES:
:ID:       QdAcl1xl6qPACyI2gfnv48Tj@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Drive @ RiverDogs Drive @ RiverDogs

Follow on MiLB First Pitch  https //stza.co/+vxNc-23

Shop  https //stza.co/+vxNc-1i

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Drive @ RiverDogs
END:VALARM
DTSTART:20180825T220500Z
DTEND:20180826T010500Z
UID:QdAcl1xl6qPACyI2gfnv48Tj@stanza.co
SUMMARY:Drive @ RiverDogs
DESCRIPTION:Drive @ RiverDogs\n\nFollow on MiLB First Pitch: https://stza.co/+vxNc-23\n\nShop: https://stza.co/+vxNc-1i\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144530Z
LAST-MODIFIED:20180213T144530Z
TRANSP:OPAQUE
END:VEVENT
* Drive @ RiverDogs
<2018-08-26 Sun 16:05-19:05>
:PROPERTIES:
:ID:       7adyLngE1Z9NyZ4c3n2lf7B3@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Drive @ RiverDogs Drive @ RiverDogs

Follow on MiLB First Pitch  https //stza.co/+vxNm-2e

Shop  https //stza.co/+vxNm-1b

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Drive @ RiverDogs
END:VALARM
DTSTART:20180826T210500Z
DTEND:20180827T000500Z
UID:7adyLngE1Z9NyZ4c3n2lf7B3@stanza.co
SUMMARY:Drive @ RiverDogs
DESCRIPTION:Drive @ RiverDogs\n\nFollow on MiLB First Pitch: https://stza.co/+vxNm-2e\n\nShop: https://stza.co/+vxNm-1b\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144530Z
LAST-MODIFIED:20180213T144530Z
TRANSP:OPAQUE
END:VEVENT
* Drive @ Braves
<2018-08-27 Mon 18:00-21:00>
:PROPERTIES:
:ID:       EYdKt5xlxoBYlpZpO507Wc7o@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Drive @ Braves Drive @ Braves

Follow on MiLB First Pitch  https //stza.co/+vxSn-1z

Shop  https //stza.co/+vxSn-3a

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Drive @ Braves
END:VALARM
DTSTART:20180827T230000Z
DTEND:20180828T020000Z
UID:EYdKt5xlxoBYlpZpO507Wc7o@stanza.co
SUMMARY:Drive @ Braves
DESCRIPTION:Drive @ Braves\n\nFollow on MiLB First Pitch: https://stza.co/+vxSn-1z\n\nShop: https://stza.co/+vxSn-3a\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144530Z
LAST-MODIFIED:20180213T144530Z
TRANSP:OPAQUE
END:VEVENT
* Drive @ Braves
<2018-08-28 Tue 18:00-21:00>
:PROPERTIES:
:ID:       Y3WBjrLw4WkQnU4XMGv-qkZG@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Drive @ Braves Drive @ Braves

Follow on MiLB First Pitch  https //stza.co/+vxSo-3_

Shop  https //stza.co/+vxSo-2c

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Drive @ Braves
END:VALARM
DTSTART:20180828T230000Z
DTEND:20180829T020000Z
UID:Y3WBjrLw4WkQnU4XMGv-qkZG@stanza.co
SUMMARY:Drive @ Braves
DESCRIPTION:Drive @ Braves\n\nFollow on MiLB First Pitch: https://stza.co/+vxSo-3_\n\nShop: https://stza.co/+vxSo-2c\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144530Z
LAST-MODIFIED:20180213T144530Z
TRANSP:OPAQUE
END:VEVENT
* Drive @ Braves
<2018-08-29 Wed 18:00-21:00>
:PROPERTIES:
:ID:       d08jtlhn6EhDUciqArvgobbR@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Drive @ Braves Drive @ Braves

Follow on MiLB First Pitch  https //stza.co/+vxSp-1K

Shop  https //stza.co/+vxSp-1h

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Drive @ Braves
END:VALARM
DTSTART:20180829T230000Z
DTEND:20180830T020000Z
UID:d08jtlhn6EhDUciqArvgobbR@stanza.co
SUMMARY:Drive @ Braves
DESCRIPTION:Drive @ Braves\n\nFollow on MiLB First Pitch: https://stza.co/+vxSp-1K\n\nShop: https://stza.co/+vxSp-1h\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144530Z
LAST-MODIFIED:20180213T144530Z
TRANSP:OPAQUE
END:VEVENT
* Drive @ Braves
<2018-08-30 Thu 18:00-21:00>
:PROPERTIES:
:ID:       L_QWQ2xpnV_AObK0gZuMw8hM@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Drive @ Braves Drive @ Braves

Follow on MiLB First Pitch  https //stza.co/+vxSq-2

Shop  https //stza.co/+vxSq-2E

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Drive @ Braves
END:VALARM
DTSTART:20180830T230000Z
DTEND:20180831T020000Z
UID:L_QWQ2xpnV_AObK0gZuMw8hM@stanza.co
SUMMARY:Drive @ Braves
DESCRIPTION:Drive @ Braves\n\nFollow on MiLB First Pitch: https://stza.co/+vxSq-2\n\nShop: https://stza.co/+vxSq-2E\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144530Z
LAST-MODIFIED:20180213T144530Z
TRANSP:OPAQUE
END:VEVENT
* Drive vs. Legends
<2018-08-31 Fri 18:05-21:05>
:PROPERTIES:
:ID:       IzI6WIlqly5a4JnIy6CuVvnt@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Drive vs. Legends Drive vs. Legends

Follow on MiLB First Pitch  https //stza.co/+xGDB-2g

Shop  https //stza.co/+xGDB-V

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Drive vs. Legends
END:VALARM
DTSTART:20180831T230500Z
DTEND:20180901T020500Z
UID:IzI6WIlqly5a4JnIy6CuVvnt@stanza.co
SUMMARY:Drive vs. Legends
DESCRIPTION:Drive vs. Legends\n\nFollow on MiLB First Pitch: https://stza.co/+xGDB-2g\n\nShop: https://stza.co/+xGDB-V\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144530Z
LAST-MODIFIED:20180213T144530Z
TRANSP:OPAQUE
END:VEVENT
* Drive vs. Legends
<2018-09-01 Sat 18:05-21:05>
:PROPERTIES:
:ID:       Hyn8WJ_RCM_xjVHgp2oT_JHE@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Drive vs. Legends Drive vs. Legends

Follow on MiLB First Pitch  https //stza.co/+xGDC-3q

Shop  https //stza.co/+xGDC-

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Drive vs. Legends
END:VALARM
DTSTART:20180901T230500Z
DTEND:20180902T020500Z
UID:Hyn8WJ_RCM_xjVHgp2oT_JHE@stanza.co
SUMMARY:Drive vs. Legends
DESCRIPTION:Drive vs. Legends\n\nFollow on MiLB First Pitch: https://stza.co/+xGDC-3q\n\nShop: https://stza.co/+xGDC-\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144530Z
LAST-MODIFIED:20180213T144530Z
TRANSP:OPAQUE
END:VEVENT
* Drive vs. Legends
<2018-09-02 Sun 15:05-18:05>
:PROPERTIES:
:ID:       ivUSQ6GapnBfJ0g3d_POLP3-@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Drive vs. Legends Drive vs. Legends

Follow on MiLB First Pitch  https //stza.co/+xF2L-1S

Shop  https //stza.co/+xF2L-2l

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Drive vs. Legends
END:VALARM
DTSTART:20180902T200500Z
DTEND:20180902T230500Z
UID:ivUSQ6GapnBfJ0g3d_POLP3-@stanza.co
SUMMARY:Drive vs. Legends
DESCRIPTION:Drive vs. Legends\n\nFollow on MiLB First Pitch: https://stza.co/+xF2L-1S\n\nShop: https://stza.co/+xF2L-2l\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144530Z
LAST-MODIFIED:20180213T144530Z
TRANSP:OPAQUE
END:VEVENT
* Drive vs. Legends
<2018-09-03 Mon 13:05-16:05>
:PROPERTIES:
:ID:       ZCjSnoJpCSrIQd92hkcevCRZ@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Drive vs. Legends Drive vs. Legends

Follow on MiLB First Pitch  https //stza.co/+xF2M-3p

Shop  https //stza.co/+xF2M-3o

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Drive vs. Legends
END:VALARM
DTSTART:20180903T180500Z
DTEND:20180903T210500Z
UID:ZCjSnoJpCSrIQd92hkcevCRZ@stanza.co
SUMMARY:Drive vs. Legends
DESCRIPTION:Drive vs. Legends\n\nFollow on MiLB First Pitch: https://stza.co/+xF2M-3p\n\nShop: https://stza.co/+xF2M-3o\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144530Z
LAST-MODIFIED:20180213T144530Z
TRANSP:OPAQUE
END:VEVENT
