#+TITLE:       Main Google calendar entries
#+AUTHOR:      Eric S Fraga
#+EMAIL:       e.fraga@ucl.ac.uk
#+DESCRIPTION: converted using the ical2org awk script
#+CATEGORY:    google
#+STARTUP:     hidestars
#+STARTUP:     overview

* COMMENT original iCal preamble

* Royals @ Twins
<2018-06-19 Tue>--<2018-06-18 Mon>
:PROPERTIES:
:ID:       JNsgmfvdgECv9hKjN9ym-yA3@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Royals @ Twins Royals @ Twins

Follow on MiLB First Pitch  https //stza.co/+xCHX-1C

Shop  https //stza.co/+xCHX-x

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Royals @ Twins
END:VALARM
DTSTART;VALUE=DATE:20180619
DTEND;VALUE=DATE:20180619
UID:JNsgmfvdgECv9hKjN9ym-yA3@stanza.co
SUMMARY:Royals @ Twins
DESCRIPTION:Royals @ Twins\n\nFollow on MiLB First Pitch: https://stza.co/+xCHX-1C\n\nShop: https://stza.co/+xCHX-x\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144511Z
LAST-MODIFIED:20180213T144511Z
TRANSP:OPAQUE
END:VEVENT
* Royals @ Twins
<2018-06-20 Wed>--<2018-06-19 Tue>
:PROPERTIES:
:ID:       FssUUI9Pe6WKr-tLlm--MwIK@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Royals @ Twins Royals @ Twins

Follow on MiLB First Pitch  https //stza.co/+xCHY-1p

Shop  https //stza.co/+xCHY-1m

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Royals @ Twins
END:VALARM
DTSTART;VALUE=DATE:20180620
DTEND;VALUE=DATE:20180620
UID:FssUUI9Pe6WKr-tLlm--MwIK@stanza.co
SUMMARY:Royals @ Twins
DESCRIPTION:Royals @ Twins\n\nFollow on MiLB First Pitch: https://stza.co/+xCHY-1p\n\nShop: https://stza.co/+xCHY-1m\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144511Z
LAST-MODIFIED:20180213T144511Z
TRANSP:OPAQUE
END:VEVENT
* Royals @ Twins
<2018-06-21 Thu>--<2018-06-20 Wed>
:PROPERTIES:
:ID:       rrNlZuRAw_DUjOqs_M8Af7En@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Royals @ Twins Royals @ Twins

Follow on MiLB First Pitch  https //stza.co/+xCHZ-1D

Shop  https //stza.co/+xCHZ-2X

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Royals @ Twins
END:VALARM
DTSTART;VALUE=DATE:20180621
DTEND;VALUE=DATE:20180621
UID:rrNlZuRAw_DUjOqs_M8Af7En@stanza.co
SUMMARY:Royals @ Twins
DESCRIPTION:Royals @ Twins\n\nFollow on MiLB First Pitch: https://stza.co/+xCHZ-1D\n\nShop: https://stza.co/+xCHZ-2X\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144511Z
LAST-MODIFIED:20180213T144511Z
TRANSP:OPAQUE
END:VEVENT
* Royals vs. Blue Jays
<2018-06-22 Fri>--<2018-06-21 Thu>
:PROPERTIES:
:ID:       KUaxoUnoGgitVh_6CBiQQIG4@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Royals vs. Blue Jays Royals vs. Blue Jays

Follow on MiLB First Pitch  https //stza.co/+xCH$-12

Shop  https //stza.co/+xCH$-3i

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Royals vs. Blue Jays
END:VALARM
DTSTART;VALUE=DATE:20180622
DTEND;VALUE=DATE:20180622
UID:KUaxoUnoGgitVh_6CBiQQIG4@stanza.co
SUMMARY:Royals vs. Blue Jays
DESCRIPTION:Royals vs. Blue Jays\n\nFollow on MiLB First Pitch: https://stza.co/+xCH$-12\n\nShop: https://stza.co/+xCH$-3i\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144511Z
LAST-MODIFIED:20180213T144511Z
TRANSP:OPAQUE
END:VEVENT
* Royals vs. Blue Jays
<2018-06-23 Sat>--<2018-06-22 Fri>
:PROPERTIES:
:ID:       JWEss-vkaJ6zjBHCfZnr02bS@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Royals vs. Blue Jays Royals vs. Blue Jays

Follow on MiLB First Pitch  https //stza.co/+xCI0-2x

Shop  https //stza.co/+xCI0-1b

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Royals vs. Blue Jays
END:VALARM
DTSTART;VALUE=DATE:20180623
DTEND;VALUE=DATE:20180623
UID:JWEss-vkaJ6zjBHCfZnr02bS@stanza.co
SUMMARY:Royals vs. Blue Jays
DESCRIPTION:Royals vs. Blue Jays\n\nFollow on MiLB First Pitch: https://stza.co/+xCI0-2x\n\nShop: https://stza.co/+xCI0-1b\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144511Z
LAST-MODIFIED:20180213T144511Z
TRANSP:OPAQUE
END:VEVENT
* Royals vs. Blue Jays
<2018-06-24 Sun>--<2018-06-23 Sat>
:PROPERTIES:
:ID:       qZFCEGlvfcFb9WZkiEbwOz2n@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Royals vs. Blue Jays Royals vs. Blue Jays

Follow on MiLB First Pitch  https //stza.co/+xCI3-t

Shop  https //stza.co/+xCI3-X

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Royals vs. Blue Jays
END:VALARM
DTSTART;VALUE=DATE:20180624
DTEND;VALUE=DATE:20180624
UID:qZFCEGlvfcFb9WZkiEbwOz2n@stanza.co
SUMMARY:Royals vs. Blue Jays
DESCRIPTION:Royals vs. Blue Jays\n\nFollow on MiLB First Pitch: https://stza.co/+xCI3-t\n\nShop: https://stza.co/+xCI3-X\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144511Z
LAST-MODIFIED:20180213T144511Z
TRANSP:OPAQUE
END:VEVENT
* Royals vs. Braves
<2018-06-25 Mon>--<2018-06-24 Sun>
:PROPERTIES:
:ID:       na_TPY2kIMmp8uClKSnZz1cb@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Royals vs. Braves Royals vs. Braves

Follow on MiLB First Pitch  https //stza.co/+xCI5-2d

Shop  https //stza.co/+xCI5-1T

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Royals vs. Braves
END:VALARM
DTSTART;VALUE=DATE:20180625
DTEND;VALUE=DATE:20180625
UID:na_TPY2kIMmp8uClKSnZz1cb@stanza.co
SUMMARY:Royals vs. Braves
DESCRIPTION:Royals vs. Braves\n\nFollow on MiLB First Pitch: https://stza.co/+xCI5-2d\n\nShop: https://stza.co/+xCI5-1T\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144511Z
LAST-MODIFIED:20180213T144511Z
TRANSP:OPAQUE
END:VEVENT
* Royals vs. Braves
<2018-06-26 Tue>--<2018-06-25 Mon>
:PROPERTIES:
:ID:       KFBWXwWN1a8y2q9HOjgQzZvm@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Royals vs. Braves Royals vs. Braves

Follow on MiLB First Pitch  https //stza.co/+xCI7-27

Shop  https //stza.co/+xCI7-1s

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Royals vs. Braves
END:VALARM
DTSTART;VALUE=DATE:20180626
DTEND;VALUE=DATE:20180626
UID:KFBWXwWN1a8y2q9HOjgQzZvm@stanza.co
SUMMARY:Royals vs. Braves
DESCRIPTION:Royals vs. Braves\n\nFollow on MiLB First Pitch: https://stza.co/+xCI7-27\n\nShop: https://stza.co/+xCI7-1s\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144511Z
LAST-MODIFIED:20180213T144511Z
TRANSP:OPAQUE
END:VEVENT
* Royals @ Yankees
<2018-06-28 Thu>--<2018-06-27 Wed>
:PROPERTIES:
:ID:       aqK9Xfbu5zP_3zeZKtGTF4Mn@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Royals @ Yankees Royals @ Yankees

Follow on MiLB First Pitch  https //stza.co/+xCI8-3a

Shop  https //stza.co/+xCI8-s

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Royals @ Yankees
END:VALARM
DTSTART;VALUE=DATE:20180628
DTEND;VALUE=DATE:20180628
UID:aqK9Xfbu5zP_3zeZKtGTF4Mn@stanza.co
SUMMARY:Royals @ Yankees
DESCRIPTION:Royals @ Yankees\n\nFollow on MiLB First Pitch: https://stza.co/+xCI8-3a\n\nShop: https://stza.co/+xCI8-s\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144511Z
LAST-MODIFIED:20180213T144511Z
TRANSP:OPAQUE
END:VEVENT
* Royals @ Yankees
<2018-06-29 Fri>--<2018-06-28 Thu>
:PROPERTIES:
:ID:       Fg20KkBxNFc12ELPDqr0Gm43@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Royals @ Yankees Royals @ Yankees

Follow on MiLB First Pitch  https //stza.co/+xCI9-2

Shop  https //stza.co/+xCI9-3P

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Royals @ Yankees
END:VALARM
DTSTART;VALUE=DATE:20180629
DTEND;VALUE=DATE:20180629
UID:Fg20KkBxNFc12ELPDqr0Gm43@stanza.co
SUMMARY:Royals @ Yankees
DESCRIPTION:Royals @ Yankees\n\nFollow on MiLB First Pitch: https://stza.co/+xCI9-2\n\nShop: https://stza.co/+xCI9-3P\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144511Z
LAST-MODIFIED:20180213T144511Z
TRANSP:OPAQUE
END:VEVENT
* Royals @ Yankees
<2018-06-30 Sat>--<2018-06-29 Fri>
:PROPERTIES:
:ID:       zbbFQLpEzVCe_vX7g19834er@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Royals @ Yankees Royals @ Yankees

Follow on MiLB First Pitch  https //stza.co/+xCIb-t

Shop  https //stza.co/+xCIb-2M

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Royals @ Yankees
END:VALARM
DTSTART;VALUE=DATE:20180630
DTEND;VALUE=DATE:20180630
UID:zbbFQLpEzVCe_vX7g19834er@stanza.co
SUMMARY:Royals @ Yankees
DESCRIPTION:Royals @ Yankees\n\nFollow on MiLB First Pitch: https://stza.co/+xCIb-t\n\nShop: https://stza.co/+xCIb-2M\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144511Z
LAST-MODIFIED:20180213T144511Z
TRANSP:OPAQUE
END:VEVENT
* Royals @ Blue Jays
<2018-07-01 Sun>--<2018-06-30 Sat>
:PROPERTIES:
:ID:       YWUPe5SiTQHWagEXP6FypWw6@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Royals @ Blue Jays Royals @ Blue Jays

Follow on MiLB First Pitch  https //stza.co/+xCIc-11

Shop  https //stza.co/+xCIc-1z

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Royals @ Blue Jays
END:VALARM
DTSTART;VALUE=DATE:20180701
DTEND;VALUE=DATE:20180701
UID:YWUPe5SiTQHWagEXP6FypWw6@stanza.co
SUMMARY:Royals @ Blue Jays
DESCRIPTION:Royals @ Blue Jays\n\nFollow on MiLB First Pitch: https://stza.co/+xCIc-11\n\nShop: https://stza.co/+xCIc-1z\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144511Z
LAST-MODIFIED:20180213T144511Z
TRANSP:OPAQUE
END:VEVENT
* Royals @ Blue Jays
<2018-07-02 Mon>--<2018-07-01 Sun>
:PROPERTIES:
:ID:       5bIk6d3SRqupRGGkpwxB1iTq@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Royals @ Blue Jays Royals @ Blue Jays

Follow on MiLB First Pitch  https //stza.co/+xCId-2l

Shop  https //stza.co/+xCId-q

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Royals @ Blue Jays
END:VALARM
DTSTART;VALUE=DATE:20180702
DTEND;VALUE=DATE:20180702
UID:5bIk6d3SRqupRGGkpwxB1iTq@stanza.co
SUMMARY:Royals @ Blue Jays
DESCRIPTION:Royals @ Blue Jays\n\nFollow on MiLB First Pitch: https://stza.co/+xCId-2l\n\nShop: https://stza.co/+xCId-q\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144511Z
LAST-MODIFIED:20180213T144511Z
TRANSP:OPAQUE
END:VEVENT
* Royals @ Blue Jays
<2018-07-03 Tue>--<2018-07-02 Mon>
:PROPERTIES:
:ID:       ruQi5dvGoIZozRvRv12N_Ojd@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Royals @ Blue Jays Royals @ Blue Jays

Follow on MiLB First Pitch  https //stza.co/+xCIe-3D

Shop  https //stza.co/+xCIe-2w

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Royals @ Blue Jays
END:VALARM
DTSTART;VALUE=DATE:20180703
DTEND;VALUE=DATE:20180703
UID:ruQi5dvGoIZozRvRv12N_Ojd@stanza.co
SUMMARY:Royals @ Blue Jays
DESCRIPTION:Royals @ Blue Jays\n\nFollow on MiLB First Pitch: https://stza.co/+xCIe-3D\n\nShop: https://stza.co/+xCIe-2w\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144511Z
LAST-MODIFIED:20180213T144511Z
TRANSP:OPAQUE
END:VEVENT
* Royals vs. Rays
<2018-07-04 Wed>--<2018-07-03 Tue>
:PROPERTIES:
:ID:       hzYRylW_MAcI0zRcrVifUA3g@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Royals vs. Rays Royals vs. Rays

Follow on MiLB First Pitch  https //stza.co/+xCIg-1a

Shop  https //stza.co/+xCIg-1X

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Royals vs. Rays
END:VALARM
DTSTART;VALUE=DATE:20180704
DTEND;VALUE=DATE:20180704
UID:hzYRylW_MAcI0zRcrVifUA3g@stanza.co
SUMMARY:Royals vs. Rays
DESCRIPTION:Royals vs. Rays\n\nFollow on MiLB First Pitch: https://stza.co/+xCIg-1a\n\nShop: https://stza.co/+xCIg-1X\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144511Z
LAST-MODIFIED:20180213T144511Z
TRANSP:OPAQUE
END:VEVENT
* Royals vs. Rays
<2018-07-05 Thu>--<2018-07-04 Wed>
:PROPERTIES:
:ID:       kTkRUu0DzS8Z77ZJqwQ3Kw_2@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Royals vs. Rays Royals vs. Rays

Follow on MiLB First Pitch  https //stza.co/+xCIj-2m

Shop  https //stza.co/+xCIj-3r

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Royals vs. Rays
END:VALARM
DTSTART;VALUE=DATE:20180705
DTEND;VALUE=DATE:20180705
UID:kTkRUu0DzS8Z77ZJqwQ3Kw_2@stanza.co
SUMMARY:Royals vs. Rays
DESCRIPTION:Royals vs. Rays\n\nFollow on MiLB First Pitch: https://stza.co/+xCIj-2m\n\nShop: https://stza.co/+xCIj-3r\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144511Z
LAST-MODIFIED:20180213T144511Z
TRANSP:OPAQUE
END:VEVENT
* Royals vs. Rays
<2018-07-06 Fri>--<2018-07-05 Thu>
:PROPERTIES:
:ID:       5_X870kQs2aIWWfnPxPHIWja@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Royals vs. Rays Royals vs. Rays

Follow on MiLB First Pitch  https //stza.co/+xCIk-2h

Shop  https //stza.co/+xCIk-i

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Royals vs. Rays
END:VALARM
DTSTART;VALUE=DATE:20180706
DTEND;VALUE=DATE:20180706
UID:5_X870kQs2aIWWfnPxPHIWja@stanza.co
SUMMARY:Royals vs. Rays
DESCRIPTION:Royals vs. Rays\n\nFollow on MiLB First Pitch: https://stza.co/+xCIk-2h\n\nShop: https://stza.co/+xCIk-i\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144511Z
LAST-MODIFIED:20180213T144511Z
TRANSP:OPAQUE
END:VEVENT
* Royals vs. Astros
<2018-07-07 Sat>--<2018-07-06 Fri>
:PROPERTIES:
:ID:       r2ivXAdKYQ6caD6gL_wuaGns@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Royals vs. Astros Royals vs. Astros

Follow on MiLB First Pitch  https //stza.co/+xCIn-3k

Shop  https //stza.co/+xCIn-22

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Royals vs. Astros
END:VALARM
DTSTART;VALUE=DATE:20180707
DTEND;VALUE=DATE:20180707
UID:r2ivXAdKYQ6caD6gL_wuaGns@stanza.co
SUMMARY:Royals vs. Astros
DESCRIPTION:Royals vs. Astros\n\nFollow on MiLB First Pitch: https://stza.co/+xCIn-3k\n\nShop: https://stza.co/+xCIn-22\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144511Z
LAST-MODIFIED:20180213T144511Z
TRANSP:OPAQUE
END:VEVENT
* Royals vs. Astros
<2018-07-08 Sun>--<2018-07-07 Sat>
:PROPERTIES:
:ID:       qxz8auvkRwgpyorYkpnW6Alm@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Royals vs. Astros Royals vs. Astros

Follow on MiLB First Pitch  https //stza.co/+xCIp-3D

Shop  https //stza.co/+xCIp-K

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Royals vs. Astros
END:VALARM
DTSTART;VALUE=DATE:20180708
DTEND;VALUE=DATE:20180708
UID:qxz8auvkRwgpyorYkpnW6Alm@stanza.co
SUMMARY:Royals vs. Astros
DESCRIPTION:Royals vs. Astros\n\nFollow on MiLB First Pitch: https://stza.co/+xCIp-3D\n\nShop: https://stza.co/+xCIp-K\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144511Z
LAST-MODIFIED:20180213T144511Z
TRANSP:OPAQUE
END:VEVENT
* Royals vs. Astros
<2018-07-09 Mon>--<2018-07-08 Sun>
:PROPERTIES:
:ID:       QLF82eFubyRDINEoy11_xh1z@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Royals vs. Astros Royals vs. Astros

Follow on MiLB First Pitch  https //stza.co/+xCIr-2d

Shop  https //stza.co/+xCIr-A

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Royals vs. Astros
END:VALARM
DTSTART;VALUE=DATE:20180709
DTEND;VALUE=DATE:20180709
UID:QLF82eFubyRDINEoy11_xh1z@stanza.co
SUMMARY:Royals vs. Astros
DESCRIPTION:Royals vs. Astros\n\nFollow on MiLB First Pitch: https://stza.co/+xCIr-2d\n\nShop: https://stza.co/+xCIr-A\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144511Z
LAST-MODIFIED:20180213T144511Z
TRANSP:OPAQUE
END:VEVENT
* Royals @ Braves
<2018-07-10 Tue 18:00-21:00>
:PROPERTIES:
:ID:       B8wU7ObGvnmnqmYGKcytqhqk@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Royals @ Braves Royals @ Braves

Follow on MiLB First Pitch  https //stza.co/+xDSe-3b

Shop  https //stza.co/+xDSe-22

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Royals @ Braves
END:VALARM
DTSTART:20180710T230000Z
DTEND:20180711T020000Z
UID:B8wU7ObGvnmnqmYGKcytqhqk@stanza.co
SUMMARY:Royals @ Braves
DESCRIPTION:Royals @ Braves\n\nFollow on MiLB First Pitch: https://stza.co/+xDSe-3b\n\nShop: https://stza.co/+xDSe-22\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144511Z
LAST-MODIFIED:20180213T144511Z
TRANSP:OPAQUE
END:VEVENT
* Royals @ Braves
<2018-07-11 Wed 18:00-21:00>
:PROPERTIES:
:ID:       ZJ7w4mrJBz8HI1Ky9syt80Hx@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Royals @ Braves Royals @ Braves

Follow on MiLB First Pitch  https //stza.co/+xDSf-2p

Shop  https //stza.co/+xDSf-1o

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Royals @ Braves
END:VALARM
DTSTART:20180711T230000Z
DTEND:20180712T020000Z
UID:ZJ7w4mrJBz8HI1Ky9syt80Hx@stanza.co
SUMMARY:Royals @ Braves
DESCRIPTION:Royals @ Braves\n\nFollow on MiLB First Pitch: https://stza.co/+xDSf-2p\n\nShop: https://stza.co/+xDSf-1o\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144511Z
LAST-MODIFIED:20180213T144511Z
TRANSP:OPAQUE
END:VEVENT
* Royals @ Braves
<2018-07-12 Thu 18:00-21:00>
:PROPERTIES:
:ID:       IcP2U9CNcIYYSwfHvoouWxw5@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Royals @ Braves Royals @ Braves

Follow on MiLB First Pitch  https //stza.co/+xDSh-27

Shop  https //stza.co/+xDSh-3b

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Royals @ Braves
END:VALARM
DTSTART:20180712T230000Z
DTEND:20180713T020000Z
UID:IcP2U9CNcIYYSwfHvoouWxw5@stanza.co
SUMMARY:Royals @ Braves
DESCRIPTION:Royals @ Braves\n\nFollow on MiLB First Pitch: https://stza.co/+xDSh-27\n\nShop: https://stza.co/+xDSh-3b\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144511Z
LAST-MODIFIED:20180213T144511Z
TRANSP:OPAQUE
END:VEVENT
* Royals @ Braves
<2018-07-13 Fri 18:00-21:00>
:PROPERTIES:
:ID:       068rqDucfI8wmQolIBZ9s1sA@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Royals @ Braves Royals @ Braves

Follow on MiLB First Pitch  https //stza.co/+xDSi-2E

Shop  https //stza.co/+xDSi-2e

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Royals @ Braves
END:VALARM
DTSTART:20180713T230000Z
DTEND:20180714T020000Z
UID:068rqDucfI8wmQolIBZ9s1sA@stanza.co
SUMMARY:Royals @ Braves
DESCRIPTION:Royals @ Braves\n\nFollow on MiLB First Pitch: https://stza.co/+xDSi-2E\n\nShop: https://stza.co/+xDSi-2e\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144511Z
LAST-MODIFIED:20180213T144511Z
TRANSP:OPAQUE
END:VEVENT
* Royals vs. Cardinals
<2018-07-14 Sat>--<2018-07-13 Fri>
:PROPERTIES:
:ID:       M9Rp5JHE2TcVhT79fhsbBzfk@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Royals vs. Cardinals Royals vs. Cardinals

Follow on MiLB First Pitch  https //stza.co/+xCIy-L

Shop  https //stza.co/+xCIy-5

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Royals vs. Cardinals
END:VALARM
DTSTART;VALUE=DATE:20180714
DTEND;VALUE=DATE:20180714
UID:M9Rp5JHE2TcVhT79fhsbBzfk@stanza.co
SUMMARY:Royals vs. Cardinals
DESCRIPTION:Royals vs. Cardinals\n\nFollow on MiLB First Pitch: https://stza.co/+xCIy-L\n\nShop: https://stza.co/+xCIy-5\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144511Z
LAST-MODIFIED:20180213T144511Z
TRANSP:OPAQUE
END:VEVENT
* Royals vs. Cardinals
<2018-07-15 Sun>--<2018-07-14 Sat>
:PROPERTIES:
:ID:       zxfoBB8phz3VRhUBMq8l3WNQ@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Royals vs. Cardinals Royals vs. Cardinals

Follow on MiLB First Pitch  https //stza.co/+xCIA-3I

Shop  https //stza.co/+xCIA-g

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Royals vs. Cardinals
END:VALARM
DTSTART;VALUE=DATE:20180715
DTEND;VALUE=DATE:20180715
UID:zxfoBB8phz3VRhUBMq8l3WNQ@stanza.co
SUMMARY:Royals vs. Cardinals
DESCRIPTION:Royals vs. Cardinals\n\nFollow on MiLB First Pitch: https://stza.co/+xCIA-3I\n\nShop: https://stza.co/+xCIA-g\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144511Z
LAST-MODIFIED:20180213T144511Z
TRANSP:OPAQUE
END:VEVENT
* Royals vs. Cardinals
<2018-07-16 Mon>--<2018-07-15 Sun>
:PROPERTIES:
:ID:       wwsbq6KweBw3E-JJEMbHLPmO@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Royals vs. Cardinals Royals vs. Cardinals

Follow on MiLB First Pitch  https //stza.co/+xCID-29

Shop  https //stza.co/+xCID-O

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Royals vs. Cardinals
END:VALARM
DTSTART;VALUE=DATE:20180716
DTEND;VALUE=DATE:20180716
UID:wwsbq6KweBw3E-JJEMbHLPmO@stanza.co
SUMMARY:Royals vs. Cardinals
DESCRIPTION:Royals vs. Cardinals\n\nFollow on MiLB First Pitch: https://stza.co/+xCID-29\n\nShop: https://stza.co/+xCID-O\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144511Z
LAST-MODIFIED:20180213T144511Z
TRANSP:OPAQUE
END:VEVENT
* Royals @ Pirates
<2018-07-18 Wed>--<2018-07-17 Tue>
:PROPERTIES:
:ID:       i9_wC_krANMw2xxtzxz5RM7F@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Royals @ Pirates Royals @ Pirates

Follow on MiLB First Pitch  https //stza.co/+xCIE-2z

Shop  https //stza.co/+xCIE-$

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Royals @ Pirates
END:VALARM
DTSTART;VALUE=DATE:20180718
DTEND;VALUE=DATE:20180718
UID:i9_wC_krANMw2xxtzxz5RM7F@stanza.co
SUMMARY:Royals @ Pirates
DESCRIPTION:Royals @ Pirates\n\nFollow on MiLB First Pitch: https://stza.co/+xCIE-2z\n\nShop: https://stza.co/+xCIE-$\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144511Z
LAST-MODIFIED:20180213T144511Z
TRANSP:OPAQUE
END:VEVENT
* Royals @ Pirates
<2018-07-19 Thu>--<2018-07-18 Wed>
:PROPERTIES:
:ID:       lSLnYm73PI8RdT25N2BIkhju@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Royals @ Pirates Royals @ Pirates

Follow on MiLB First Pitch  https //stza.co/+xCIG-3d

Shop  https //stza.co/+xCIG-28

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Royals @ Pirates
END:VALARM
DTSTART;VALUE=DATE:20180719
DTEND;VALUE=DATE:20180719
UID:lSLnYm73PI8RdT25N2BIkhju@stanza.co
SUMMARY:Royals @ Pirates
DESCRIPTION:Royals @ Pirates\n\nFollow on MiLB First Pitch: https://stza.co/+xCIG-3d\n\nShop: https://stza.co/+xCIG-28\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144511Z
LAST-MODIFIED:20180213T144511Z
TRANSP:OPAQUE
END:VEVENT
* Royals @ Pirates
<2018-07-20 Fri>--<2018-07-19 Thu>
:PROPERTIES:
:ID:       rphRn3dBDMUk9xxrGtvUj_ij@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Royals @ Pirates Royals @ Pirates

Follow on MiLB First Pitch  https //stza.co/+xCIH-2s

Shop  https //stza.co/+xCIH-17

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Royals @ Pirates
END:VALARM
DTSTART;VALUE=DATE:20180720
DTEND;VALUE=DATE:20180720
UID:rphRn3dBDMUk9xxrGtvUj_ij@stanza.co
SUMMARY:Royals @ Pirates
DESCRIPTION:Royals @ Pirates\n\nFollow on MiLB First Pitch: https://stza.co/+xCIH-2s\n\nShop: https://stza.co/+xCIH-17\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144511Z
LAST-MODIFIED:20180213T144511Z
TRANSP:OPAQUE
END:VEVENT
* Royals @ Astros
<2018-07-21 Sat>--<2018-07-20 Fri>
:PROPERTIES:
:ID:       366vRSAGWtnBK1XJ4GK4SO9X@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Royals @ Astros Royals @ Astros

Follow on MiLB First Pitch  https //stza.co/+xCII-1c

Shop  https //stza.co/+xCII-1V

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Royals @ Astros
END:VALARM
DTSTART;VALUE=DATE:20180721
DTEND;VALUE=DATE:20180721
UID:366vRSAGWtnBK1XJ4GK4SO9X@stanza.co
SUMMARY:Royals @ Astros
DESCRIPTION:Royals @ Astros\n\nFollow on MiLB First Pitch: https://stza.co/+xCII-1c\n\nShop: https://stza.co/+xCII-1V\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144511Z
LAST-MODIFIED:20180213T144511Z
TRANSP:OPAQUE
END:VEVENT
* Royals @ Astros
<2018-07-22 Sun>--<2018-07-21 Sat>
:PROPERTIES:
:ID:       cAvdE6iLQbsngtByscChqCj1@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Royals @ Astros Royals @ Astros

Follow on MiLB First Pitch  https //stza.co/+xCIJ-16

Shop  https //stza.co/+xCIJ-1N

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Royals @ Astros
END:VALARM
DTSTART;VALUE=DATE:20180722
DTEND;VALUE=DATE:20180722
UID:cAvdE6iLQbsngtByscChqCj1@stanza.co
SUMMARY:Royals @ Astros
DESCRIPTION:Royals @ Astros\n\nFollow on MiLB First Pitch: https://stza.co/+xCIJ-16\n\nShop: https://stza.co/+xCIJ-1N\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144511Z
LAST-MODIFIED:20180213T144511Z
TRANSP:OPAQUE
END:VEVENT
* Royals @ Astros
<2018-07-23 Mon>--<2018-07-22 Sun>
:PROPERTIES:
:ID:       mXbl4RL6HSN7EdJaOspNBHgr@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Royals @ Astros Royals @ Astros

Follow on MiLB First Pitch  https //stza.co/+xCIK-3

Shop  https //stza.co/+xCIK-3e

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Royals @ Astros
END:VALARM
DTSTART;VALUE=DATE:20180723
DTEND;VALUE=DATE:20180723
UID:mXbl4RL6HSN7EdJaOspNBHgr@stanza.co
SUMMARY:Royals @ Astros
DESCRIPTION:Royals @ Astros\n\nFollow on MiLB First Pitch: https://stza.co/+xCIK-3\n\nShop: https://stza.co/+xCIK-3e\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144511Z
LAST-MODIFIED:20180213T144511Z
TRANSP:OPAQUE
END:VEVENT
* Royals vs. Twins
<2018-07-24 Tue>--<2018-07-23 Mon>
:PROPERTIES:
:ID:       2B7vWfObupz-KJ2M0dYdDBqH@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Royals vs. Twins Royals vs. Twins

Follow on MiLB First Pitch  https //stza.co/+xCIN-1D

Shop  https //stza.co/+xCIN-2t

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Royals vs. Twins
END:VALARM
DTSTART;VALUE=DATE:20180724
DTEND;VALUE=DATE:20180724
UID:2B7vWfObupz-KJ2M0dYdDBqH@stanza.co
SUMMARY:Royals vs. Twins
DESCRIPTION:Royals vs. Twins\n\nFollow on MiLB First Pitch: https://stza.co/+xCIN-1D\n\nShop: https://stza.co/+xCIN-2t\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144511Z
LAST-MODIFIED:20180213T144511Z
TRANSP:OPAQUE
END:VEVENT
* Royals vs. Twins
<2018-07-25 Wed>--<2018-07-24 Tue>
:PROPERTIES:
:ID:       ZmKV5tM9pMrpUgMY1_ptI8qc@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Royals vs. Twins Royals vs. Twins

Follow on MiLB First Pitch  https //stza.co/+xCIP-1Y

Shop  https //stza.co/+xCIP-2f

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Royals vs. Twins
END:VALARM
DTSTART;VALUE=DATE:20180725
DTEND;VALUE=DATE:20180725
UID:ZmKV5tM9pMrpUgMY1_ptI8qc@stanza.co
SUMMARY:Royals vs. Twins
DESCRIPTION:Royals vs. Twins\n\nFollow on MiLB First Pitch: https://stza.co/+xCIP-1Y\n\nShop: https://stza.co/+xCIP-2f\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144511Z
LAST-MODIFIED:20180213T144511Z
TRANSP:OPAQUE
END:VEVENT
* Royals vs. Twins
<2018-07-26 Thu>--<2018-07-25 Wed>
:PROPERTIES:
:ID:       c4uCfD4RCsv-vmf2abFzy-eE@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Royals vs. Twins Royals vs. Twins

Follow on MiLB First Pitch  https //stza.co/+xCIQ-1a

Shop  https //stza.co/+xCIQ-K

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Royals vs. Twins
END:VALARM
DTSTART;VALUE=DATE:20180726
DTEND;VALUE=DATE:20180726
UID:c4uCfD4RCsv-vmf2abFzy-eE@stanza.co
SUMMARY:Royals vs. Twins
DESCRIPTION:Royals vs. Twins\n\nFollow on MiLB First Pitch: https://stza.co/+xCIQ-1a\n\nShop: https://stza.co/+xCIQ-K\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144511Z
LAST-MODIFIED:20180213T144511Z
TRANSP:OPAQUE
END:VEVENT
* Royals vs. Mets
<2018-07-27 Fri>--<2018-07-26 Thu>
:PROPERTIES:
:ID:       JU54lvGMc4xaNWSqM_Fy5fs9@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Royals vs. Mets Royals vs. Mets

Follow on MiLB First Pitch  https //stza.co/+xCIS-3R

Shop  https //stza.co/+xCIS-2_

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Royals vs. Mets
END:VALARM
DTSTART;VALUE=DATE:20180727
DTEND;VALUE=DATE:20180727
UID:JU54lvGMc4xaNWSqM_Fy5fs9@stanza.co
SUMMARY:Royals vs. Mets
DESCRIPTION:Royals vs. Mets\n\nFollow on MiLB First Pitch: https://stza.co/+xCIS-3R\n\nShop: https://stza.co/+xCIS-2_\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144511Z
LAST-MODIFIED:20180213T144511Z
TRANSP:OPAQUE
END:VEVENT
* Royals vs. Mets
<2018-07-28 Sat>--<2018-07-27 Fri>
:PROPERTIES:
:ID:       stoRBivfJt9MDmlO_9u2Fe5k@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Royals vs. Mets Royals vs. Mets

Follow on MiLB First Pitch  https //stza.co/+xCIW-3L

Shop  https //stza.co/+xCIW-_

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Royals vs. Mets
END:VALARM
DTSTART;VALUE=DATE:20180728
DTEND;VALUE=DATE:20180728
UID:stoRBivfJt9MDmlO_9u2Fe5k@stanza.co
SUMMARY:Royals vs. Mets
DESCRIPTION:Royals vs. Mets\n\nFollow on MiLB First Pitch: https://stza.co/+xCIW-3L\n\nShop: https://stza.co/+xCIW-_\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144511Z
LAST-MODIFIED:20180213T144511Z
TRANSP:OPAQUE
END:VEVENT
* Royals vs. Mets
<2018-07-29 Sun>--<2018-07-28 Sat>
:PROPERTIES:
:ID:       vhgj05mYABSJ30CnDpd8VQfc@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Royals vs. Mets Royals vs. Mets

Follow on MiLB First Pitch  https //stza.co/+xCIY-3K

Shop  https //stza.co/+xCIY-$

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Royals vs. Mets
END:VALARM
DTSTART;VALUE=DATE:20180729
DTEND;VALUE=DATE:20180729
UID:vhgj05mYABSJ30CnDpd8VQfc@stanza.co
SUMMARY:Royals vs. Mets
DESCRIPTION:Royals vs. Mets\n\nFollow on MiLB First Pitch: https://stza.co/+xCIY-3K\n\nShop: https://stza.co/+xCIY-$\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144511Z
LAST-MODIFIED:20180213T144511Z
TRANSP:OPAQUE
END:VEVENT
* Royals @ Yankees
<2018-07-31 Tue>--<2018-07-30 Mon>
:PROPERTIES:
:ID:       Jb7IkmrSwPfsa20BY-UCYwNL@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Royals @ Yankees Royals @ Yankees

Follow on MiLB First Pitch  https //stza.co/+xCIZ-1P

Shop  https //stza.co/+xCIZ-2T

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Royals @ Yankees
END:VALARM
DTSTART;VALUE=DATE:20180731
DTEND;VALUE=DATE:20180731
UID:Jb7IkmrSwPfsa20BY-UCYwNL@stanza.co
SUMMARY:Royals @ Yankees
DESCRIPTION:Royals @ Yankees\n\nFollow on MiLB First Pitch: https://stza.co/+xCIZ-1P\n\nShop: https://stza.co/+xCIZ-2T\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144511Z
LAST-MODIFIED:20180213T144511Z
TRANSP:OPAQUE
END:VEVENT
* Royals @ Yankees
<2018-08-01 Wed>--<2018-07-31 Tue>
:PROPERTIES:
:ID:       _BI2K6DU4jU2_EEX3tjDX-Pr@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Royals @ Yankees Royals @ Yankees

Follow on MiLB First Pitch  https //stza.co/+xCI$-27

Shop  https //stza.co/+xCI$-1o

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Royals @ Yankees
END:VALARM
DTSTART;VALUE=DATE:20180801
DTEND;VALUE=DATE:20180801
UID:_BI2K6DU4jU2_EEX3tjDX-Pr@stanza.co
SUMMARY:Royals @ Yankees
DESCRIPTION:Royals @ Yankees\n\nFollow on MiLB First Pitch: https://stza.co/+xCI$-27\n\nShop: https://stza.co/+xCI$-1o\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144511Z
LAST-MODIFIED:20180213T144511Z
TRANSP:OPAQUE
END:VEVENT
* Royals @ Yankees
<2018-08-02 Thu>--<2018-08-01 Wed>
:PROPERTIES:
:ID:       oFySHaATwYF8oQ8hfuFr2pj_@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Royals @ Yankees Royals @ Yankees

Follow on MiLB First Pitch  https //stza.co/+xCJ0-1$

Shop  https //stza.co/+xCJ0-1

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Royals @ Yankees
END:VALARM
DTSTART;VALUE=DATE:20180802
DTEND;VALUE=DATE:20180802
UID:oFySHaATwYF8oQ8hfuFr2pj_@stanza.co
SUMMARY:Royals @ Yankees
DESCRIPTION:Royals @ Yankees\n\nFollow on MiLB First Pitch: https://stza.co/+xCJ0-1$\n\nShop: https://stza.co/+xCJ0-1\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144511Z
LAST-MODIFIED:20180213T144511Z
TRANSP:OPAQUE
END:VEVENT
* Royals vs. Rays
<2018-08-03 Fri>--<2018-08-02 Thu>
:PROPERTIES:
:ID:       YBTWbnhoULki_NdzdBdjzR_E@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Royals vs. Rays Royals vs. Rays

Follow on MiLB First Pitch  https //stza.co/+xCJ2-2c

Shop  https //stza.co/+xCJ2-2y

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Royals vs. Rays
END:VALARM
DTSTART;VALUE=DATE:20180803
DTEND;VALUE=DATE:20180803
UID:YBTWbnhoULki_NdzdBdjzR_E@stanza.co
SUMMARY:Royals vs. Rays
DESCRIPTION:Royals vs. Rays\n\nFollow on MiLB First Pitch: https://stza.co/+xCJ2-2c\n\nShop: https://stza.co/+xCJ2-2y\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144511Z
LAST-MODIFIED:20180213T144511Z
TRANSP:OPAQUE
END:VEVENT
* Royals vs. Rays
<2018-08-04 Sat>--<2018-08-03 Fri>
:PROPERTIES:
:ID:       lHbtRDzcZLy0ytAFF0JMywT4@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Royals vs. Rays Royals vs. Rays

Follow on MiLB First Pitch  https //stza.co/+xCJ3-2O

Shop  https //stza.co/+xCJ3-1z

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Royals vs. Rays
END:VALARM
DTSTART;VALUE=DATE:20180804
DTEND;VALUE=DATE:20180804
UID:lHbtRDzcZLy0ytAFF0JMywT4@stanza.co
SUMMARY:Royals vs. Rays
DESCRIPTION:Royals vs. Rays\n\nFollow on MiLB First Pitch: https://stza.co/+xCJ3-2O\n\nShop: https://stza.co/+xCJ3-1z\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144511Z
LAST-MODIFIED:20180213T144511Z
TRANSP:OPAQUE
END:VEVENT
* Royals vs. Rays
<2018-08-05 Sun>--<2018-08-04 Sat>
:PROPERTIES:
:ID:       1Hyv24v8SnOLbuwljjj9xj-7@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Royals vs. Rays Royals vs. Rays

Follow on MiLB First Pitch  https //stza.co/+xCJ5-3J

Shop  https //stza.co/+xCJ5-3x

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Royals vs. Rays
END:VALARM
DTSTART;VALUE=DATE:20180805
DTEND;VALUE=DATE:20180805
UID:1Hyv24v8SnOLbuwljjj9xj-7@stanza.co
SUMMARY:Royals vs. Rays
DESCRIPTION:Royals vs. Rays\n\nFollow on MiLB First Pitch: https://stza.co/+xCJ5-3J\n\nShop: https://stza.co/+xCJ5-3x\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144511Z
LAST-MODIFIED:20180213T144511Z
TRANSP:OPAQUE
END:VEVENT
* Royals @ Braves
<2018-08-06 Mon 18:00-21:00>
:PROPERTIES:
:ID:       QMs59EoE8eEyDC82tMBs8CwT@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Royals @ Braves Royals @ Braves

Follow on MiLB First Pitch  https //stza.co/+xDSj-20

Shop  https //stza.co/+xDSj-1f

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Royals @ Braves
END:VALARM
DTSTART:20180806T230000Z
DTEND:20180807T020000Z
UID:QMs59EoE8eEyDC82tMBs8CwT@stanza.co
SUMMARY:Royals @ Braves
DESCRIPTION:Royals @ Braves\n\nFollow on MiLB First Pitch: https://stza.co/+xDSj-20\n\nShop: https://stza.co/+xDSj-1f\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144511Z
LAST-MODIFIED:20180213T144511Z
TRANSP:OPAQUE
END:VEVENT
* Royals @ Braves
<2018-08-07 Tue 18:00-21:00>
:PROPERTIES:
:ID:       Dk8p1NnrCeayKJwFufEeaEdv@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Royals @ Braves Royals @ Braves

Follow on MiLB First Pitch  https //stza.co/+xDSk-2g

Shop  https //stza.co/+xDSk-2l

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Royals @ Braves
END:VALARM
DTSTART:20180807T230000Z
DTEND:20180808T020000Z
UID:Dk8p1NnrCeayKJwFufEeaEdv@stanza.co
SUMMARY:Royals @ Braves
DESCRIPTION:Royals @ Braves\n\nFollow on MiLB First Pitch: https://stza.co/+xDSk-2g\n\nShop: https://stza.co/+xDSk-2l\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144511Z
LAST-MODIFIED:20180213T144511Z
TRANSP:OPAQUE
END:VEVENT
* Royals @ Braves
<2018-08-08 Wed 18:00-21:00>
:PROPERTIES:
:ID:       6Gf3iPoHuTvrwI6SPjGKn-xn@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Royals @ Braves Royals @ Braves

Follow on MiLB First Pitch  https //stza.co/+xDSl-1B

Shop  https //stza.co/+xDSl-h

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Royals @ Braves
END:VALARM
DTSTART:20180808T230000Z
DTEND:20180809T020000Z
UID:6Gf3iPoHuTvrwI6SPjGKn-xn@stanza.co
SUMMARY:Royals @ Braves
DESCRIPTION:Royals @ Braves\n\nFollow on MiLB First Pitch: https://stza.co/+xDSl-1B\n\nShop: https://stza.co/+xDSl-h\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144511Z
LAST-MODIFIED:20180213T144511Z
TRANSP:OPAQUE
END:VEVENT
* Royals vs. Yankees
<2018-08-09 Thu>--<2018-08-08 Wed>
:PROPERTIES:
:ID:       wqVFRMYosQIuw4sFrhKTyPlk@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Royals vs. Yankees Royals vs. Yankees

Follow on MiLB First Pitch  https //stza.co/+xCJb-p

Shop  https //stza.co/+xCJb-36

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Royals vs. Yankees
END:VALARM
DTSTART;VALUE=DATE:20180809
DTEND;VALUE=DATE:20180809
UID:wqVFRMYosQIuw4sFrhKTyPlk@stanza.co
SUMMARY:Royals vs. Yankees
DESCRIPTION:Royals vs. Yankees\n\nFollow on MiLB First Pitch: https://stza.co/+xCJb-p\n\nShop: https://stza.co/+xCJb-36\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144511Z
LAST-MODIFIED:20180213T144511Z
TRANSP:OPAQUE
END:VEVENT
* Royals vs. Yankees
<2018-08-10 Fri>--<2018-08-09 Thu>
:PROPERTIES:
:ID:       aYm4LVERBOP1FV9Cf9ZR29m3@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Royals vs. Yankees Royals vs. Yankees

Follow on MiLB First Pitch  https //stza.co/+xCJc-3d

Shop  https //stza.co/+xCJc-2l

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Royals vs. Yankees
END:VALARM
DTSTART;VALUE=DATE:20180810
DTEND;VALUE=DATE:20180810
UID:aYm4LVERBOP1FV9Cf9ZR29m3@stanza.co
SUMMARY:Royals vs. Yankees
DESCRIPTION:Royals vs. Yankees\n\nFollow on MiLB First Pitch: https://stza.co/+xCJc-3d\n\nShop: https://stza.co/+xCJc-2l\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144511Z
LAST-MODIFIED:20180213T144511Z
TRANSP:OPAQUE
END:VEVENT
* Royals vs. Yankees
<2018-08-11 Sat>--<2018-08-10 Fri>
:PROPERTIES:
:ID:       KcbWqD0ktjGm0T_Z2zu2vPU6@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Royals vs. Yankees Royals vs. Yankees

Follow on MiLB First Pitch  https //stza.co/+xCJf-7

Shop  https //stza.co/+xCJf-35

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Royals vs. Yankees
END:VALARM
DTSTART;VALUE=DATE:20180811
DTEND;VALUE=DATE:20180811
UID:KcbWqD0ktjGm0T_Z2zu2vPU6@stanza.co
SUMMARY:Royals vs. Yankees
DESCRIPTION:Royals vs. Yankees\n\nFollow on MiLB First Pitch: https://stza.co/+xCJf-7\n\nShop: https://stza.co/+xCJf-35\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144511Z
LAST-MODIFIED:20180213T144511Z
TRANSP:OPAQUE
END:VEVENT
* Royals @ Rays
<2018-08-12 Sun>--<2018-08-11 Sat>
:PROPERTIES:
:ID:       oj7xeUPqCTgMesK0j9Z_XTR2@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Royals @ Rays Royals @ Rays

Follow on MiLB First Pitch  https //stza.co/+xCJg-1_

Shop  https //stza.co/+xCJg-X

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Royals @ Rays
END:VALARM
DTSTART;VALUE=DATE:20180812
DTEND;VALUE=DATE:20180812
UID:oj7xeUPqCTgMesK0j9Z_XTR2@stanza.co
SUMMARY:Royals @ Rays
DESCRIPTION:Royals @ Rays\n\nFollow on MiLB First Pitch: https://stza.co/+xCJg-1_\n\nShop: https://stza.co/+xCJg-X\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144511Z
LAST-MODIFIED:20180213T144511Z
TRANSP:OPAQUE
END:VEVENT
* Royals @ Rays
<2018-08-13 Mon>--<2018-08-12 Sun>
:PROPERTIES:
:ID:       Pov2ghjkhdbPV2Ek4DkKVB1Y@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Royals @ Rays Royals @ Rays

Follow on MiLB First Pitch  https //stza.co/+xCJh-2q

Shop  https //stza.co/+xCJh-3n

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Royals @ Rays
END:VALARM
DTSTART;VALUE=DATE:20180813
DTEND;VALUE=DATE:20180813
UID:Pov2ghjkhdbPV2Ek4DkKVB1Y@stanza.co
SUMMARY:Royals @ Rays
DESCRIPTION:Royals @ Rays\n\nFollow on MiLB First Pitch: https://stza.co/+xCJh-2q\n\nShop: https://stza.co/+xCJh-3n\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144511Z
LAST-MODIFIED:20180213T144511Z
TRANSP:OPAQUE
END:VEVENT
* Royals @ Rays
<2018-08-14 Tue>--<2018-08-13 Mon>
:PROPERTIES:
:ID:       6jLSHOA4AzOglhlENjgpDedB@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Royals @ Rays Royals @ Rays

Follow on MiLB First Pitch  https //stza.co/+xCJi-2A

Shop  https //stza.co/+xCJi-1f

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Royals @ Rays
END:VALARM
DTSTART;VALUE=DATE:20180814
DTEND;VALUE=DATE:20180814
UID:6jLSHOA4AzOglhlENjgpDedB@stanza.co
SUMMARY:Royals @ Rays
DESCRIPTION:Royals @ Rays\n\nFollow on MiLB First Pitch: https://stza.co/+xCJi-2A\n\nShop: https://stza.co/+xCJi-1f\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144511Z
LAST-MODIFIED:20180213T144511Z
TRANSP:OPAQUE
END:VEVENT
* Royals vs. Pirates
<2018-08-16 Thu>--<2018-08-15 Wed>
:PROPERTIES:
:ID:       0gIPfwXG0TTYDYD3AjaEFRxZ@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Royals vs. Pirates Royals vs. Pirates

Follow on MiLB First Pitch  https //stza.co/+xCJk-17

Shop  https //stza.co/+xCJk-w

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Royals vs. Pirates
END:VALARM
DTSTART;VALUE=DATE:20180816
DTEND;VALUE=DATE:20180816
UID:0gIPfwXG0TTYDYD3AjaEFRxZ@stanza.co
SUMMARY:Royals vs. Pirates
DESCRIPTION:Royals vs. Pirates\n\nFollow on MiLB First Pitch: https://stza.co/+xCJk-17\n\nShop: https://stza.co/+xCJk-w\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144511Z
LAST-MODIFIED:20180213T144511Z
TRANSP:OPAQUE
END:VEVENT
* Royals vs. Pirates
<2018-08-17 Fri>--<2018-08-16 Thu>
:PROPERTIES:
:ID:       iiA1keSPIageodqIk1NtEnsT@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Royals vs. Pirates Royals vs. Pirates

Follow on MiLB First Pitch  https //stza.co/+xCJl-q

Shop  https //stza.co/+xCJl-2H

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Royals vs. Pirates
END:VALARM
DTSTART;VALUE=DATE:20180817
DTEND;VALUE=DATE:20180817
UID:iiA1keSPIageodqIk1NtEnsT@stanza.co
SUMMARY:Royals vs. Pirates
DESCRIPTION:Royals vs. Pirates\n\nFollow on MiLB First Pitch: https://stza.co/+xCJl-q\n\nShop: https://stza.co/+xCJl-2H\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144511Z
LAST-MODIFIED:20180213T144511Z
TRANSP:OPAQUE
END:VEVENT
* Royals vs. Pirates
<2018-08-18 Sat>--<2018-08-17 Fri>
:PROPERTIES:
:ID:       lunsiLtTnHedIBzT2fMWzL-H@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Royals vs. Pirates Royals vs. Pirates

Follow on MiLB First Pitch  https //stza.co/+xCJn-1y

Shop  https //stza.co/+xCJn-w

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Royals vs. Pirates
END:VALARM
DTSTART;VALUE=DATE:20180818
DTEND;VALUE=DATE:20180818
UID:lunsiLtTnHedIBzT2fMWzL-H@stanza.co
SUMMARY:Royals vs. Pirates
DESCRIPTION:Royals vs. Pirates\n\nFollow on MiLB First Pitch: https://stza.co/+xCJn-1y\n\nShop: https://stza.co/+xCJn-w\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144511Z
LAST-MODIFIED:20180213T144511Z
TRANSP:OPAQUE
END:VEVENT
* Royals vs. Braves
<2018-08-19 Sun>--<2018-08-18 Sat>
:PROPERTIES:
:ID:       6IGLXyxc9Cse4RIBNyCJacIg@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Royals vs. Braves Royals vs. Braves

Follow on MiLB First Pitch  https //stza.co/+xCJq-2H

Shop  https //stza.co/+xCJq-2m

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Royals vs. Braves
END:VALARM
DTSTART;VALUE=DATE:20180819
DTEND;VALUE=DATE:20180819
UID:6IGLXyxc9Cse4RIBNyCJacIg@stanza.co
SUMMARY:Royals vs. Braves
DESCRIPTION:Royals vs. Braves\n\nFollow on MiLB First Pitch: https://stza.co/+xCJq-2H\n\nShop: https://stza.co/+xCJq-2m\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144511Z
LAST-MODIFIED:20180213T144511Z
TRANSP:OPAQUE
END:VEVENT
* Royals vs. Braves
<2018-08-20 Mon>--<2018-08-19 Sun>
:PROPERTIES:
:ID:       YqzriFwrc1fieMhjwJkeF22y@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Royals vs. Braves Royals vs. Braves

Follow on MiLB First Pitch  https //stza.co/+xCJr-3U

Shop  https //stza.co/+xCJr-9

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Royals vs. Braves
END:VALARM
DTSTART;VALUE=DATE:20180820
DTEND;VALUE=DATE:20180820
UID:YqzriFwrc1fieMhjwJkeF22y@stanza.co
SUMMARY:Royals vs. Braves
DESCRIPTION:Royals vs. Braves\n\nFollow on MiLB First Pitch: https://stza.co/+xCJr-3U\n\nShop: https://stza.co/+xCJr-9\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144511Z
LAST-MODIFIED:20180213T144511Z
TRANSP:OPAQUE
END:VEVENT
* Royals @ Cardinals
<2018-08-21 Tue>--<2018-08-20 Mon>
:PROPERTIES:
:ID:       oZHve_f5QXeZEMDRRB88vWB5@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Royals @ Cardinals Royals @ Cardinals

Follow on MiLB First Pitch  https //stza.co/+xCJt-1Y

Shop  https //stza.co/+xCJt-Q

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Royals @ Cardinals
END:VALARM
DTSTART;VALUE=DATE:20180821
DTEND;VALUE=DATE:20180821
UID:oZHve_f5QXeZEMDRRB88vWB5@stanza.co
SUMMARY:Royals @ Cardinals
DESCRIPTION:Royals @ Cardinals\n\nFollow on MiLB First Pitch: https://stza.co/+xCJt-1Y\n\nShop: https://stza.co/+xCJt-Q\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144511Z
LAST-MODIFIED:20180213T144511Z
TRANSP:OPAQUE
END:VEVENT
* Royals @ Cardinals
<2018-08-22 Wed>--<2018-08-21 Tue>
:PROPERTIES:
:ID:       ndGJqUmPFA6Cmm7ej7dFDDfN@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Royals @ Cardinals Royals @ Cardinals

Follow on MiLB First Pitch  https //stza.co/+xCJu-o

Shop  https //stza.co/+xCJu-1c

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Royals @ Cardinals
END:VALARM
DTSTART;VALUE=DATE:20180822
DTEND;VALUE=DATE:20180822
UID:ndGJqUmPFA6Cmm7ej7dFDDfN@stanza.co
SUMMARY:Royals @ Cardinals
DESCRIPTION:Royals @ Cardinals\n\nFollow on MiLB First Pitch: https://stza.co/+xCJu-o\n\nShop: https://stza.co/+xCJu-1c\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144511Z
LAST-MODIFIED:20180213T144511Z
TRANSP:OPAQUE
END:VEVENT
* Royals @ Cardinals
<2018-08-23 Thu>--<2018-08-22 Wed>
:PROPERTIES:
:ID:       Yix_LnZpf7y2gBsPsDAFgkh4@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Royals @ Cardinals Royals @ Cardinals

Follow on MiLB First Pitch  https //stza.co/+xC9X-2c

Shop  https //stza.co/+xC9X-3C

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Royals @ Cardinals
END:VALARM
DTSTART;VALUE=DATE:20180823
DTEND;VALUE=DATE:20180823
UID:Yix_LnZpf7y2gBsPsDAFgkh4@stanza.co
SUMMARY:Royals @ Cardinals
DESCRIPTION:Royals @ Cardinals\n\nFollow on MiLB First Pitch: https://stza.co/+xC9X-2c\n\nShop: https://stza.co/+xC9X-3C\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144511Z
LAST-MODIFIED:20180213T144511Z
TRANSP:OPAQUE
END:VEVENT
* Royals @ Mets
<2018-08-24 Fri>--<2018-08-23 Thu>
:PROPERTIES:
:ID:       Q-QG354H_iCbNfwv1rrzWJD6@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Royals @ Mets Royals @ Mets

Follow on MiLB First Pitch  https //stza.co/+xC9Y-34

Shop  https //stza.co/+xC9Y-2f

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Royals @ Mets
END:VALARM
DTSTART;VALUE=DATE:20180824
DTEND;VALUE=DATE:20180824
UID:Q-QG354H_iCbNfwv1rrzWJD6@stanza.co
SUMMARY:Royals @ Mets
DESCRIPTION:Royals @ Mets\n\nFollow on MiLB First Pitch: https://stza.co/+xC9Y-34\n\nShop: https://stza.co/+xC9Y-2f\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144511Z
LAST-MODIFIED:20180213T144511Z
TRANSP:OPAQUE
END:VEVENT
* Royals @ Mets
<2018-08-25 Sat>--<2018-08-24 Fri>
:PROPERTIES:
:ID:       _dTJeREHEHStPUUimhHdFEvF@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Royals @ Mets Royals @ Mets

Follow on MiLB First Pitch  https //stza.co/+xC9Z-3Q

Shop  https //stza.co/+xC9Z-1

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Royals @ Mets
END:VALARM
DTSTART;VALUE=DATE:20180825
DTEND;VALUE=DATE:20180825
UID:_dTJeREHEHStPUUimhHdFEvF@stanza.co
SUMMARY:Royals @ Mets
DESCRIPTION:Royals @ Mets\n\nFollow on MiLB First Pitch: https://stza.co/+xC9Z-3Q\n\nShop: https://stza.co/+xC9Z-1\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144511Z
LAST-MODIFIED:20180213T144511Z
TRANSP:OPAQUE
END:VEVENT
* Royals @ Mets
<2018-08-26 Sun>--<2018-08-25 Sat>
:PROPERTIES:
:ID:       yaGVZ8zJOgDZaA4WeLyfOkI7@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Royals @ Mets Royals @ Mets

Follow on MiLB First Pitch  https //stza.co/+xC9_-24

Shop  https //stza.co/+xC9_-1N

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Royals @ Mets
END:VALARM
DTSTART;VALUE=DATE:20180826
DTEND;VALUE=DATE:20180826
UID:yaGVZ8zJOgDZaA4WeLyfOkI7@stanza.co
SUMMARY:Royals @ Mets
DESCRIPTION:Royals @ Mets\n\nFollow on MiLB First Pitch: https://stza.co/+xC9_-24\n\nShop: https://stza.co/+xC9_-1N\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144511Z
LAST-MODIFIED:20180213T144511Z
TRANSP:OPAQUE
END:VEVENT
* Royals vs. Blue Jays
<2018-08-27 Mon>--<2018-08-26 Sun>
:PROPERTIES:
:ID:       9RzkTYXunx6I5WWCaPCkACDq@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Royals vs. Blue Jays Royals vs. Blue Jays

Follow on MiLB First Pitch  https //stza.co/+xCa0-T

Shop  https //stza.co/+xCa0-3U

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Royals vs. Blue Jays
END:VALARM
DTSTART;VALUE=DATE:20180827
DTEND;VALUE=DATE:20180827
UID:9RzkTYXunx6I5WWCaPCkACDq@stanza.co
SUMMARY:Royals vs. Blue Jays
DESCRIPTION:Royals vs. Blue Jays\n\nFollow on MiLB First Pitch: https://stza.co/+xCa0-T\n\nShop: https://stza.co/+xCa0-3U\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144511Z
LAST-MODIFIED:20180213T144511Z
TRANSP:OPAQUE
END:VEVENT
* Royals vs. Blue Jays
<2018-08-28 Tue>--<2018-08-27 Mon>
:PROPERTIES:
:ID:       835oao1Mljv2Ql2TgUdjxmy7@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Royals vs. Blue Jays Royals vs. Blue Jays

Follow on MiLB First Pitch  https //stza.co/+xCa3-2N

Shop  https //stza.co/+xCa3-2c

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Royals vs. Blue Jays
END:VALARM
DTSTART;VALUE=DATE:20180828
DTEND;VALUE=DATE:20180828
UID:835oao1Mljv2Ql2TgUdjxmy7@stanza.co
SUMMARY:Royals vs. Blue Jays
DESCRIPTION:Royals vs. Blue Jays\n\nFollow on MiLB First Pitch: https://stza.co/+xCa3-2N\n\nShop: https://stza.co/+xCa3-2c\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144511Z
LAST-MODIFIED:20180213T144511Z
TRANSP:OPAQUE
END:VEVENT
* Royals vs. Blue Jays
<2018-08-29 Wed>--<2018-08-28 Tue>
:PROPERTIES:
:ID:       L1Th9GqOv1FuZue7g3ggbvHE@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Royals vs. Blue Jays Royals vs. Blue Jays

Follow on MiLB First Pitch  https //stza.co/+xCa5-1D

Shop  https //stza.co/+xCa5-2H

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Royals vs. Blue Jays
END:VALARM
DTSTART;VALUE=DATE:20180829
DTEND;VALUE=DATE:20180829
UID:L1Th9GqOv1FuZue7g3ggbvHE@stanza.co
SUMMARY:Royals vs. Blue Jays
DESCRIPTION:Royals vs. Blue Jays\n\nFollow on MiLB First Pitch: https://stza.co/+xCa5-1D\n\nShop: https://stza.co/+xCa5-2H\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144511Z
LAST-MODIFIED:20180213T144511Z
TRANSP:OPAQUE
END:VEVENT
