#+TITLE:       Main Google calendar entries
#+AUTHOR:      Eric S Fraga
#+EMAIL:       e.fraga@ucl.ac.uk
#+DESCRIPTION: converted using the ical2org awk script
#+CATEGORY:    google
#+STARTUP:     hidestars
#+STARTUP:     overview

* COMMENT original iCal preamble

* Renegades @ IronBirds
<2018-06-15 Fri 18:05-21:05>
:PROPERTIES:
:ID:       wEuSx-CiGsF1iZaPISfM6246@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Renegades @ IronBirds Renegades @ IronBirds

Follow on MiLB First Pitch  https //stza.co/+xXT_-2r

Shop  https //stza.co/+xXT_-1t

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Renegades @ IronBirds
END:VALARM
DTSTART:20180615T230500Z
DTEND:20180616T020500Z
UID:wEuSx-CiGsF1iZaPISfM6246@stanza.co
SUMMARY:Renegades @ IronBirds
DESCRIPTION:Renegades @ IronBirds\n\nFollow on MiLB First Pitch: https://stza.co/+xXT_-2r\n\nShop: https://stza.co/+xXT_-1t\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144533Z
LAST-MODIFIED:20180213T144533Z
TRANSP:OPAQUE
END:VEVENT
* Renegades @ IronBirds
<2018-06-16 Sat 17:05-20:05>
:PROPERTIES:
:ID:       9epKoqtJ2fSbQkWgJLnciYqU@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Renegades @ IronBirds Renegades @ IronBirds

Follow on MiLB First Pitch  https //stza.co/+xXT$-1q

Shop  https //stza.co/+xXT$-1_

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Renegades @ IronBirds
END:VALARM
DTSTART:20180616T220500Z
DTEND:20180617T010500Z
UID:9epKoqtJ2fSbQkWgJLnciYqU@stanza.co
SUMMARY:Renegades @ IronBirds
DESCRIPTION:Renegades @ IronBirds\n\nFollow on MiLB First Pitch: https://stza.co/+xXT$-1q\n\nShop: https://stza.co/+xXT$-1_\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144533Z
LAST-MODIFIED:20180213T144533Z
TRANSP:OPAQUE
END:VEVENT
* Renegades @ IronBirds
<2018-06-17 Sun 15:05-18:05>
:PROPERTIES:
:ID:       fMpesyhIJHQpsNxjaS7P-ALF@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Renegades @ IronBirds Renegades @ IronBirds

Follow on MiLB First Pitch  https //stza.co/+xXU0-V

Shop  https //stza.co/+xXU0-l

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Renegades @ IronBirds
END:VALARM
DTSTART:20180617T200500Z
DTEND:20180617T230500Z
UID:fMpesyhIJHQpsNxjaS7P-ALF@stanza.co
SUMMARY:Renegades @ IronBirds
DESCRIPTION:Renegades @ IronBirds\n\nFollow on MiLB First Pitch: https://stza.co/+xXU0-V\n\nShop: https://stza.co/+xXU0-l\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144533Z
LAST-MODIFIED:20180213T144533Z
TRANSP:OPAQUE
END:VEVENT
* Renegades @ Cyclones
<2018-06-18 Mon>--<2018-06-17 Sun>
:PROPERTIES:
:ID:       dyexSR446y22MlJvDQALvRwR@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Renegades @ Cyclones Renegades @ Cyclones

Follow on MiLB First Pitch  https //stza.co/+xMmK-2T

Shop  https //stza.co/+xMmK-A

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Renegades @ Cyclones
END:VALARM
DTSTART;VALUE=DATE:20180618
DTEND;VALUE=DATE:20180618
UID:dyexSR446y22MlJvDQALvRwR@stanza.co
SUMMARY:Renegades @ Cyclones
DESCRIPTION:Renegades @ Cyclones\n\nFollow on MiLB First Pitch: https://stza.co/+xMmK-2T\n\nShop: https://stza.co/+xMmK-A\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144533Z
LAST-MODIFIED:20180213T144533Z
TRANSP:OPAQUE
END:VEVENT
* Renegades @ Cyclones
<2018-06-19 Tue>--<2018-06-18 Mon>
:PROPERTIES:
:ID:       orG60KAboKI8yS4wh3ticO6Y@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Renegades @ Cyclones Renegades @ Cyclones

Follow on MiLB First Pitch  https //stza.co/+xMmL-s

Shop  https //stza.co/+xMmL-16

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Renegades @ Cyclones
END:VALARM
DTSTART;VALUE=DATE:20180619
DTEND;VALUE=DATE:20180619
UID:orG60KAboKI8yS4wh3ticO6Y@stanza.co
SUMMARY:Renegades @ Cyclones
DESCRIPTION:Renegades @ Cyclones\n\nFollow on MiLB First Pitch: https://stza.co/+xMmL-s\n\nShop: https://stza.co/+xMmL-16\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144533Z
LAST-MODIFIED:20180213T144533Z
TRANSP:OPAQUE
END:VEVENT
* Renegades @ Cyclones
<2018-06-20 Wed>--<2018-06-19 Tue>
:PROPERTIES:
:ID:       0EZYyCSWFTLnECsDWK21HD_5@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Renegades @ Cyclones Renegades @ Cyclones

Follow on MiLB First Pitch  https //stza.co/+xMmM-W

Shop  https //stza.co/+xMmM-34

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Renegades @ Cyclones
END:VALARM
DTSTART;VALUE=DATE:20180620
DTEND;VALUE=DATE:20180620
UID:0EZYyCSWFTLnECsDWK21HD_5@stanza.co
SUMMARY:Renegades @ Cyclones
DESCRIPTION:Renegades @ Cyclones\n\nFollow on MiLB First Pitch: https://stza.co/+xMmM-W\n\nShop: https://stza.co/+xMmM-34\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144533Z
LAST-MODIFIED:20180213T144533Z
TRANSP:OPAQUE
END:VEVENT
* Renegades vs. Lake Monsters
<2018-06-21 Thu 18:05-21:05>
:PROPERTIES:
:ID:       clvx_un3VpqJEIEtmlRz1dqC@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Renegades vs. Lake Monsters Renegades vs. Lake Monsters

Follow on MiLB First Pitch  https //stza.co/+xV_G-A

Shop  https //stza.co/+xV_G-n

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Renegades vs. Lake Monsters
END:VALARM
DTSTART:20180621T230500Z
DTEND:20180622T020500Z
UID:clvx_un3VpqJEIEtmlRz1dqC@stanza.co
SUMMARY:Renegades vs. Lake Monsters
DESCRIPTION:Renegades vs. Lake Monsters\n\nFollow on MiLB First Pitch: https://stza.co/+xV_G-A\n\nShop: https://stza.co/+xV_G-n\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144533Z
LAST-MODIFIED:20180213T144533Z
TRANSP:OPAQUE
END:VEVENT
* Renegades vs. Lake Monsters
<2018-06-22 Fri 18:05-21:05>
:PROPERTIES:
:ID:       bppGyyFnCOI6f6nYeNd15xZK@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Renegades vs. Lake Monsters Renegades vs. Lake Monsters

Follow on MiLB First Pitch  https //stza.co/+xV_I-j

Shop  https //stza.co/+xV_I-3j

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Renegades vs. Lake Monsters
END:VALARM
DTSTART:20180622T230500Z
DTEND:20180623T020500Z
UID:bppGyyFnCOI6f6nYeNd15xZK@stanza.co
SUMMARY:Renegades vs. Lake Monsters
DESCRIPTION:Renegades vs. Lake Monsters\n\nFollow on MiLB First Pitch: https://stza.co/+xV_I-j\n\nShop: https://stza.co/+xV_I-3j\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144533Z
LAST-MODIFIED:20180213T144533Z
TRANSP:OPAQUE
END:VEVENT
* Renegades vs. Lake Monsters
<2018-06-23 Sat 18:05-21:05>
:PROPERTIES:
:ID:       Ib3i1lozeu2vFpm6bLEyhtoQ@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Renegades vs. Lake Monsters Renegades vs. Lake Monsters

Follow on MiLB First Pitch  https //stza.co/+xV_K-2b

Shop  https //stza.co/+xV_K-3b

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Renegades vs. Lake Monsters
END:VALARM
DTSTART:20180623T230500Z
DTEND:20180624T020500Z
UID:Ib3i1lozeu2vFpm6bLEyhtoQ@stanza.co
SUMMARY:Renegades vs. Lake Monsters
DESCRIPTION:Renegades vs. Lake Monsters\n\nFollow on MiLB First Pitch: https://stza.co/+xV_K-2b\n\nShop: https://stza.co/+xV_K-3b\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144533Z
LAST-MODIFIED:20180213T144533Z
TRANSP:OPAQUE
END:VEVENT
* Renegades vs. Tigers
<2018-06-24 Sun 16:05-19:05>
:PROPERTIES:
:ID:       vTcw7rnAlEdJ2tj3RKVk_Q9H@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Renegades vs. Tigers Renegades vs. Tigers

Follow on MiLB First Pitch  https //stza.co/+xV_M-N

Shop  https //stza.co/+xV_M-1y

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Renegades vs. Tigers
END:VALARM
DTSTART:20180624T210500Z
DTEND:20180625T000500Z
UID:vTcw7rnAlEdJ2tj3RKVk_Q9H@stanza.co
SUMMARY:Renegades vs. Tigers
DESCRIPTION:Renegades vs. Tigers\n\nFollow on MiLB First Pitch: https://stza.co/+xV_M-N\n\nShop: https://stza.co/+xV_M-1y\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144533Z
LAST-MODIFIED:20180213T144533Z
TRANSP:OPAQUE
END:VEVENT
* Renegades vs. Tigers
<2018-06-25 Mon 18:05-21:05>
:PROPERTIES:
:ID:       i57e1qWgKk_Pf2RQaM1CU49Q@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Renegades vs. Tigers Renegades vs. Tigers

Follow on MiLB First Pitch  https //stza.co/+xV_O-26

Shop  https //stza.co/+xV_O-1i

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Renegades vs. Tigers
END:VALARM
DTSTART:20180625T230500Z
DTEND:20180626T020500Z
UID:i57e1qWgKk_Pf2RQaM1CU49Q@stanza.co
SUMMARY:Renegades vs. Tigers
DESCRIPTION:Renegades vs. Tigers\n\nFollow on MiLB First Pitch: https://stza.co/+xV_O-26\n\nShop: https://stza.co/+xV_O-1i\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144533Z
LAST-MODIFIED:20180213T144533Z
TRANSP:OPAQUE
END:VEVENT
* Renegades vs. Tigers
<2018-06-26 Tue 18:05-21:05>
:PROPERTIES:
:ID:       MFR8Y8wpi9ou_qX4QuTkPm1C@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Renegades vs. Tigers Renegades vs. Tigers

Follow on MiLB First Pitch  https //stza.co/+xV_Q-1l

Shop  https //stza.co/+xV_Q-u

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Renegades vs. Tigers
END:VALARM
DTSTART:20180626T230500Z
DTEND:20180627T020500Z
UID:MFR8Y8wpi9ou_qX4QuTkPm1C@stanza.co
SUMMARY:Renegades vs. Tigers
DESCRIPTION:Renegades vs. Tigers\n\nFollow on MiLB First Pitch: https://stza.co/+xV_Q-1l\n\nShop: https://stza.co/+xV_Q-u\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144533Z
LAST-MODIFIED:20180213T144533Z
TRANSP:OPAQUE
END:VEVENT
* Renegades @ ValleyCats
<2018-06-28 Thu>--<2018-06-27 Wed>
:PROPERTIES:
:ID:       RqLjof5o6rJ7jM49D3tTSIVW@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Renegades @ ValleyCats Renegades @ ValleyCats

Follow on MiLB First Pitch  https //stza.co/+xMoe-v

Shop  https //stza.co/+xMoe-1H

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Renegades @ ValleyCats
END:VALARM
DTSTART;VALUE=DATE:20180628
DTEND;VALUE=DATE:20180628
UID:RqLjof5o6rJ7jM49D3tTSIVW@stanza.co
SUMMARY:Renegades @ ValleyCats
DESCRIPTION:Renegades @ ValleyCats\n\nFollow on MiLB First Pitch: https://stza.co/+xMoe-v\n\nShop: https://stza.co/+xMoe-1H\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144533Z
LAST-MODIFIED:20180213T144533Z
TRANSP:OPAQUE
END:VEVENT
* Renegades @ ValleyCats
<2018-06-29 Fri>--<2018-06-28 Thu>
:PROPERTIES:
:ID:       ldzagWrwu_WMhd1Ha2wyaZQb@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Renegades @ ValleyCats Renegades @ ValleyCats

Follow on MiLB First Pitch  https //stza.co/+xMof-3U

Shop  https //stza.co/+xMof-24

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Renegades @ ValleyCats
END:VALARM
DTSTART;VALUE=DATE:20180629
DTEND;VALUE=DATE:20180629
UID:ldzagWrwu_WMhd1Ha2wyaZQb@stanza.co
SUMMARY:Renegades @ ValleyCats
DESCRIPTION:Renegades @ ValleyCats\n\nFollow on MiLB First Pitch: https://stza.co/+xMof-3U\n\nShop: https://stza.co/+xMof-24\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144533Z
LAST-MODIFIED:20180213T144533Z
TRANSP:OPAQUE
END:VEVENT
* Renegades @ ValleyCats
<2018-06-30 Sat>--<2018-06-29 Fri>
:PROPERTIES:
:ID:       CKL3py6UxxGuBCaGRIa34XZd@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Renegades @ ValleyCats Renegades @ ValleyCats

Follow on MiLB First Pitch  https //stza.co/+xMog-23

Shop  https //stza.co/+xMog-N

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Renegades @ ValleyCats
END:VALARM
DTSTART;VALUE=DATE:20180630
DTEND;VALUE=DATE:20180630
UID:CKL3py6UxxGuBCaGRIa34XZd@stanza.co
SUMMARY:Renegades @ ValleyCats
DESCRIPTION:Renegades @ ValleyCats\n\nFollow on MiLB First Pitch: https://stza.co/+xMog-23\n\nShop: https://stza.co/+xMog-N\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144533Z
LAST-MODIFIED:20180213T144533Z
TRANSP:OPAQUE
END:VEVENT
* Renegades @ IronBirds
<2018-07-01 Sun 15:05-18:05>
:PROPERTIES:
:ID:       1UuB-gB0FhrFsIFfKdygopEL@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Renegades @ IronBirds Renegades @ IronBirds

Follow on MiLB First Pitch  https //stza.co/+xXU1-1s

Shop  https //stza.co/+xXU1-3x

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Renegades @ IronBirds
END:VALARM
DTSTART:20180701T200500Z
DTEND:20180701T230500Z
UID:1UuB-gB0FhrFsIFfKdygopEL@stanza.co
SUMMARY:Renegades @ IronBirds
DESCRIPTION:Renegades @ IronBirds\n\nFollow on MiLB First Pitch: https://stza.co/+xXU1-1s\n\nShop: https://stza.co/+xXU1-3x\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144533Z
LAST-MODIFIED:20180213T144533Z
TRANSP:OPAQUE
END:VEVENT
* Renegades @ IronBirds
<2018-07-02 Mon 18:05-21:05>
:PROPERTIES:
:ID:       jq0wuuYKig-ZMS3RUxoZoug2@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Renegades @ IronBirds Renegades @ IronBirds

Follow on MiLB First Pitch  https //stza.co/+xXU2-1d

Shop  https //stza.co/+xXU2-3Q

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Renegades @ IronBirds
END:VALARM
DTSTART:20180702T230500Z
DTEND:20180703T020500Z
UID:jq0wuuYKig-ZMS3RUxoZoug2@stanza.co
SUMMARY:Renegades @ IronBirds
DESCRIPTION:Renegades @ IronBirds\n\nFollow on MiLB First Pitch: https://stza.co/+xXU2-1d\n\nShop: https://stza.co/+xXU2-3Q\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144533Z
LAST-MODIFIED:20180213T144533Z
TRANSP:OPAQUE
END:VEVENT
* Renegades @ IronBirds
<2018-07-03 Tue 18:05-21:05>
:PROPERTIES:
:ID:       JQXMIH-KqsWbAOY4mBgHCkcP@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Renegades @ IronBirds Renegades @ IronBirds

Follow on MiLB First Pitch  https //stza.co/+xXU3-1S

Shop  https //stza.co/+xXU3-12

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Renegades @ IronBirds
END:VALARM
DTSTART:20180703T230500Z
DTEND:20180704T020500Z
UID:JQXMIH-KqsWbAOY4mBgHCkcP@stanza.co
SUMMARY:Renegades @ IronBirds
DESCRIPTION:Renegades @ IronBirds\n\nFollow on MiLB First Pitch: https://stza.co/+xXU3-1S\n\nShop: https://stza.co/+xXU3-12\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144533Z
LAST-MODIFIED:20180213T144533Z
TRANSP:OPAQUE
END:VEVENT
* Renegades @ Yankees
<2018-07-04 Wed>--<2018-07-03 Tue>
:PROPERTIES:
:ID:       UVrcRkFr1-2a5leamemdDiFC@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Renegades @ Yankees Renegades @ Yankees

Follow on MiLB First Pitch  https //stza.co/+xMoc-13

Shop  https //stza.co/+xMoc-k

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Renegades @ Yankees
END:VALARM
DTSTART;VALUE=DATE:20180704
DTEND;VALUE=DATE:20180704
UID:UVrcRkFr1-2a5leamemdDiFC@stanza.co
SUMMARY:Renegades @ Yankees
DESCRIPTION:Renegades @ Yankees\n\nFollow on MiLB First Pitch: https://stza.co/+xMoc-13\n\nShop: https://stza.co/+xMoc-k\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144533Z
LAST-MODIFIED:20180213T144533Z
TRANSP:OPAQUE
END:VEVENT
* Renegades vs. Yankees
<2018-07-05 Thu 18:05-21:05>
:PROPERTIES:
:ID:       ozZw67Al_JweVWivF33VYwlq@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Renegades vs. Yankees Renegades vs. Yankees

Follow on MiLB First Pitch  https //stza.co/+xV_T-G

Shop  https //stza.co/+xV_T-j

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Renegades vs. Yankees
END:VALARM
DTSTART:20180705T230500Z
DTEND:20180706T020500Z
UID:ozZw67Al_JweVWivF33VYwlq@stanza.co
SUMMARY:Renegades vs. Yankees
DESCRIPTION:Renegades vs. Yankees\n\nFollow on MiLB First Pitch: https://stza.co/+xV_T-G\n\nShop: https://stza.co/+xV_T-j\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144533Z
LAST-MODIFIED:20180213T144533Z
TRANSP:OPAQUE
END:VEVENT
* Renegades vs. Yankees
<2018-07-06 Fri 18:05-21:05>
:PROPERTIES:
:ID:       rwRhLGvhmNuBdfdKFZbgq3SX@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Renegades vs. Yankees Renegades vs. Yankees

Follow on MiLB First Pitch  https //stza.co/+xV_U-2W

Shop  https //stza.co/+xV_U-2X

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Renegades vs. Yankees
END:VALARM
DTSTART:20180706T230500Z
DTEND:20180707T020500Z
UID:rwRhLGvhmNuBdfdKFZbgq3SX@stanza.co
SUMMARY:Renegades vs. Yankees
DESCRIPTION:Renegades vs. Yankees\n\nFollow on MiLB First Pitch: https://stza.co/+xV_U-2W\n\nShop: https://stza.co/+xV_U-2X\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144533Z
LAST-MODIFIED:20180213T144533Z
TRANSP:OPAQUE
END:VEVENT
* Renegades @ Spinners
<2018-07-07 Sat>--<2018-07-06 Fri>
:PROPERTIES:
:ID:       Mc1PbVAVIL9l_Kym7Wn6lD5U@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Renegades @ Spinners Renegades @ Spinners

Follow on MiLB First Pitch  https //stza.co/+xMo3-3s

Shop  https //stza.co/+xMo3-1v

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Renegades @ Spinners
END:VALARM
DTSTART;VALUE=DATE:20180707
DTEND;VALUE=DATE:20180707
UID:Mc1PbVAVIL9l_Kym7Wn6lD5U@stanza.co
SUMMARY:Renegades @ Spinners
DESCRIPTION:Renegades @ Spinners\n\nFollow on MiLB First Pitch: https://stza.co/+xMo3-3s\n\nShop: https://stza.co/+xMo3-1v\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144533Z
LAST-MODIFIED:20180213T144533Z
TRANSP:OPAQUE
END:VEVENT
* Renegades @ Spinners
<2018-07-08 Sun>--<2018-07-07 Sat>
:PROPERTIES:
:ID:       --mRM3KGdCUKzs9vp7QBsXxp@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Renegades @ Spinners Renegades @ Spinners

Follow on MiLB First Pitch  https //stza.co/+xMo4-2F

Shop  https //stza.co/+xMo4-2h

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Renegades @ Spinners
END:VALARM
DTSTART;VALUE=DATE:20180708
DTEND;VALUE=DATE:20180708
UID:--mRM3KGdCUKzs9vp7QBsXxp@stanza.co
SUMMARY:Renegades @ Spinners
DESCRIPTION:Renegades @ Spinners\n\nFollow on MiLB First Pitch: https://stza.co/+xMo4-2F\n\nShop: https://stza.co/+xMo4-2h\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144533Z
LAST-MODIFIED:20180213T144533Z
TRANSP:OPAQUE
END:VEVENT
* Renegades @ Spinners
<2018-07-09 Mon>--<2018-07-08 Sun>
:PROPERTIES:
:ID:       bqW65ZQGfJzblx5gZN28DMhI@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Renegades @ Spinners Renegades @ Spinners

Follow on MiLB First Pitch  https //stza.co/+xMo5-3r

Shop  https //stza.co/+xMo5-l

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Renegades @ Spinners
END:VALARM
DTSTART;VALUE=DATE:20180709
DTEND;VALUE=DATE:20180709
UID:bqW65ZQGfJzblx5gZN28DMhI@stanza.co
SUMMARY:Renegades @ Spinners
DESCRIPTION:Renegades @ Spinners\n\nFollow on MiLB First Pitch: https://stza.co/+xMo5-3r\n\nShop: https://stza.co/+xMo5-l\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144533Z
LAST-MODIFIED:20180213T144533Z
TRANSP:OPAQUE
END:VEVENT
* Renegades vs. Black Bears
<2018-07-11 Wed 18:05-21:05>
:PROPERTIES:
:ID:       MF9vHjh_YFQHeHIBYKSmXYfU@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Renegades vs. Black Bears Renegades vs. Black Bears

Follow on MiLB First Pitch  https //stza.co/+xV_X-2O

Shop  https //stza.co/+xV_X-2g

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Renegades vs. Black Bears
END:VALARM
DTSTART:20180711T230500Z
DTEND:20180712T020500Z
UID:MF9vHjh_YFQHeHIBYKSmXYfU@stanza.co
SUMMARY:Renegades vs. Black Bears
DESCRIPTION:Renegades vs. Black Bears\n\nFollow on MiLB First Pitch: https://stza.co/+xV_X-2O\n\nShop: https://stza.co/+xV_X-2g\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144533Z
LAST-MODIFIED:20180213T144533Z
TRANSP:OPAQUE
END:VEVENT
* Renegades vs. Black Bears
<2018-07-12 Thu 18:05-21:05>
:PROPERTIES:
:ID:       AEE86AYXdktregtAXp5cUBgq@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Renegades vs. Black Bears Renegades vs. Black Bears

Follow on MiLB First Pitch  https //stza.co/+xV_Y-3L

Shop  https //stza.co/+xV_Y-1w

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Renegades vs. Black Bears
END:VALARM
DTSTART:20180712T230500Z
DTEND:20180713T020500Z
UID:AEE86AYXdktregtAXp5cUBgq@stanza.co
SUMMARY:Renegades vs. Black Bears
DESCRIPTION:Renegades vs. Black Bears\n\nFollow on MiLB First Pitch: https://stza.co/+xV_Y-3L\n\nShop: https://stza.co/+xV_Y-1w\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144533Z
LAST-MODIFIED:20180213T144533Z
TRANSP:OPAQUE
END:VEVENT
* Renegades vs. Black Bears
<2018-07-13 Fri 18:05-21:05>
:PROPERTIES:
:ID:       jLwYAsunX1FSxW6O5NJJDeqf@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Renegades vs. Black Bears Renegades vs. Black Bears

Follow on MiLB First Pitch  https //stza.co/+xV__-3j

Shop  https //stza.co/+xV__-20

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Renegades vs. Black Bears
END:VALARM
DTSTART:20180713T230500Z
DTEND:20180714T020500Z
UID:jLwYAsunX1FSxW6O5NJJDeqf@stanza.co
SUMMARY:Renegades vs. Black Bears
DESCRIPTION:Renegades vs. Black Bears\n\nFollow on MiLB First Pitch: https://stza.co/+xV__-3j\n\nShop: https://stza.co/+xV__-20\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144533Z
LAST-MODIFIED:20180213T144533Z
TRANSP:OPAQUE
END:VEVENT
* Renegades @ Scrappers
<2018-07-14 Sat>--<2018-07-13 Fri>
:PROPERTIES:
:ID:       2WtL-GotSnlrcPOYbi1QW2rx@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Renegades @ Scrappers Renegades @ Scrappers

Follow on MiLB First Pitch  https //stza.co/+xMo9-2T

Shop  https //stza.co/+xMo9-1f

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Renegades @ Scrappers
END:VALARM
DTSTART;VALUE=DATE:20180714
DTEND;VALUE=DATE:20180714
UID:2WtL-GotSnlrcPOYbi1QW2rx@stanza.co
SUMMARY:Renegades @ Scrappers
DESCRIPTION:Renegades @ Scrappers\n\nFollow on MiLB First Pitch: https://stza.co/+xMo9-2T\n\nShop: https://stza.co/+xMo9-1f\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144533Z
LAST-MODIFIED:20180213T144533Z
TRANSP:OPAQUE
END:VEVENT
* Renegades @ Scrappers
<2018-07-15 Sun>--<2018-07-14 Sat>
:PROPERTIES:
:ID:       coeTcmw9zgCm5d5V08tCWZu5@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Renegades @ Scrappers Renegades @ Scrappers

Follow on MiLB First Pitch  https //stza.co/+xMoa-2x

Shop  https //stza.co/+xMoa-3W

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Renegades @ Scrappers
END:VALARM
DTSTART;VALUE=DATE:20180715
DTEND;VALUE=DATE:20180715
UID:coeTcmw9zgCm5d5V08tCWZu5@stanza.co
SUMMARY:Renegades @ Scrappers
DESCRIPTION:Renegades @ Scrappers\n\nFollow on MiLB First Pitch: https://stza.co/+xMoa-2x\n\nShop: https://stza.co/+xMoa-3W\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144533Z
LAST-MODIFIED:20180213T144533Z
TRANSP:OPAQUE
END:VEVENT
* Renegades @ Scrappers
<2018-07-16 Mon>--<2018-07-15 Sun>
:PROPERTIES:
:ID:       7d0lhaCNEH-0-7UmaWIbM9yh@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Renegades @ Scrappers Renegades @ Scrappers

Follow on MiLB First Pitch  https //stza.co/+xMob-K

Shop  https //stza.co/+xMob-10

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Renegades @ Scrappers
END:VALARM
DTSTART;VALUE=DATE:20180716
DTEND;VALUE=DATE:20180716
UID:7d0lhaCNEH-0-7UmaWIbM9yh@stanza.co
SUMMARY:Renegades @ Scrappers
DESCRIPTION:Renegades @ Scrappers\n\nFollow on MiLB First Pitch: https://stza.co/+xMob-K\n\nShop: https://stza.co/+xMob-10\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144533Z
LAST-MODIFIED:20180213T144533Z
TRANSP:OPAQUE
END:VEVENT
* Renegades vs. Tigers
<2018-07-17 Tue 18:05-21:05>
:PROPERTIES:
:ID:       Q8Yi9KPqcCUsp1mKt9-oifyP@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Renegades vs. Tigers Renegades vs. Tigers

Follow on MiLB First Pitch  https //stza.co/+xV$0-I

Shop  https //stza.co/+xV$0-P

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Renegades vs. Tigers
END:VALARM
DTSTART:20180717T230500Z
DTEND:20180718T020500Z
UID:Q8Yi9KPqcCUsp1mKt9-oifyP@stanza.co
SUMMARY:Renegades vs. Tigers
DESCRIPTION:Renegades vs. Tigers\n\nFollow on MiLB First Pitch: https://stza.co/+xV$0-I\n\nShop: https://stza.co/+xV$0-P\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144533Z
LAST-MODIFIED:20180213T144533Z
TRANSP:OPAQUE
END:VEVENT
* Renegades vs. Tigers
<2018-07-18 Wed 18:05-21:05>
:PROPERTIES:
:ID:       5gLnOWXGW8RoGQl47tK8H6uk@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Renegades vs. Tigers Renegades vs. Tigers

Follow on MiLB First Pitch  https //stza.co/+xV$3-1K

Shop  https //stza.co/+xV$3-1n

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Renegades vs. Tigers
END:VALARM
DTSTART:20180718T230500Z
DTEND:20180719T020500Z
UID:5gLnOWXGW8RoGQl47tK8H6uk@stanza.co
SUMMARY:Renegades vs. Tigers
DESCRIPTION:Renegades vs. Tigers\n\nFollow on MiLB First Pitch: https://stza.co/+xV$3-1K\n\nShop: https://stza.co/+xV$3-1n\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144533Z
LAST-MODIFIED:20180213T144533Z
TRANSP:OPAQUE
END:VEVENT
* Renegades vs. Tigers
<2018-07-19 Thu 18:05-21:05>
:PROPERTIES:
:ID:       XooAbRiMEpHMyXHtJt_iSROX@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Renegades vs. Tigers Renegades vs. Tigers

Follow on MiLB First Pitch  https //stza.co/+xV$5-z

Shop  https //stza.co/+xV$5-3u

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Renegades vs. Tigers
END:VALARM
DTSTART:20180719T230500Z
DTEND:20180720T020500Z
UID:XooAbRiMEpHMyXHtJt_iSROX@stanza.co
SUMMARY:Renegades vs. Tigers
DESCRIPTION:Renegades vs. Tigers\n\nFollow on MiLB First Pitch: https://stza.co/+xV$5-z\n\nShop: https://stza.co/+xV$5-3u\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144533Z
LAST-MODIFIED:20180213T144533Z
TRANSP:OPAQUE
END:VEVENT
* Renegades vs. Lake Monsters
<2018-07-20 Fri 18:05-21:05>
:PROPERTIES:
:ID:       bDxrNoRnX_MKDOrduxC7lX_8@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Renegades vs. Lake Monsters Renegades vs. Lake Monsters

Follow on MiLB First Pitch  https //stza.co/+xV$7-1s

Shop  https //stza.co/+xV$7-2D

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Renegades vs. Lake Monsters
END:VALARM
DTSTART:20180720T230500Z
DTEND:20180721T020500Z
UID:bDxrNoRnX_MKDOrduxC7lX_8@stanza.co
SUMMARY:Renegades vs. Lake Monsters
DESCRIPTION:Renegades vs. Lake Monsters\n\nFollow on MiLB First Pitch: https://stza.co/+xV$7-1s\n\nShop: https://stza.co/+xV$7-2D\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144533Z
LAST-MODIFIED:20180213T144533Z
TRANSP:OPAQUE
END:VEVENT
* Renegades vs. Lake Monsters
<2018-07-21 Sat 17:05-20:05>
:PROPERTIES:
:ID:       -_qoRWmU9xiTmx4sruYvK5VY@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Renegades vs. Lake Monsters Renegades vs. Lake Monsters

Follow on MiLB First Pitch  https //stza.co/+xV$9-1M

Shop  https //stza.co/+xV$9-S

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Renegades vs. Lake Monsters
END:VALARM
DTSTART:20180721T220500Z
DTEND:20180722T010500Z
UID:-_qoRWmU9xiTmx4sruYvK5VY@stanza.co
SUMMARY:Renegades vs. Lake Monsters
DESCRIPTION:Renegades vs. Lake Monsters\n\nFollow on MiLB First Pitch: https://stza.co/+xV$9-1M\n\nShop: https://stza.co/+xV$9-S\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144533Z
LAST-MODIFIED:20180213T144533Z
TRANSP:OPAQUE
END:VEVENT
* Renegades vs. Lake Monsters
<2018-07-22 Sun 16:05-19:05>
:PROPERTIES:
:ID:       PeF7g7aAno1SVobrMgU4_z0i@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Renegades vs. Lake Monsters Renegades vs. Lake Monsters

Follow on MiLB First Pitch  https //stza.co/+xV$a-2b

Shop  https //stza.co/+xV$a-2o

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Renegades vs. Lake Monsters
END:VALARM
DTSTART:20180722T210500Z
DTEND:20180723T000500Z
UID:PeF7g7aAno1SVobrMgU4_z0i@stanza.co
SUMMARY:Renegades vs. Lake Monsters
DESCRIPTION:Renegades vs. Lake Monsters\n\nFollow on MiLB First Pitch: https://stza.co/+xV$a-2b\n\nShop: https://stza.co/+xV$a-2o\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144533Z
LAST-MODIFIED:20180213T144533Z
TRANSP:OPAQUE
END:VEVENT
* Renegades @ Spinners
<2018-07-24 Tue>--<2018-07-23 Mon>
:PROPERTIES:
:ID:       hEqIitIna_khbenSOe4-tGI6@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Renegades @ Spinners Renegades @ Spinners

Follow on MiLB First Pitch  https //stza.co/+xMo6-u

Shop  https //stza.co/+xMo6-3i

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Renegades @ Spinners
END:VALARM
DTSTART;VALUE=DATE:20180724
DTEND;VALUE=DATE:20180724
UID:hEqIitIna_khbenSOe4-tGI6@stanza.co
SUMMARY:Renegades @ Spinners
DESCRIPTION:Renegades @ Spinners\n\nFollow on MiLB First Pitch: https://stza.co/+xMo6-u\n\nShop: https://stza.co/+xMo6-3i\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144533Z
LAST-MODIFIED:20180213T144533Z
TRANSP:OPAQUE
END:VEVENT
* Renegades @ Spinners
<2018-07-25 Wed>--<2018-07-24 Tue>
:PROPERTIES:
:ID:       dMhHbXZAj_uDmFpjJR1SBJoZ@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Renegades @ Spinners Renegades @ Spinners

Follow on MiLB First Pitch  https //stza.co/+xMo7-i

Shop  https //stza.co/+xMo7-1l

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Renegades @ Spinners
END:VALARM
DTSTART;VALUE=DATE:20180725
DTEND;VALUE=DATE:20180725
UID:dMhHbXZAj_uDmFpjJR1SBJoZ@stanza.co
SUMMARY:Renegades @ Spinners
DESCRIPTION:Renegades @ Spinners\n\nFollow on MiLB First Pitch: https://stza.co/+xMo7-i\n\nShop: https://stza.co/+xMo7-1l\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144533Z
LAST-MODIFIED:20180213T144533Z
TRANSP:OPAQUE
END:VEVENT
* Renegades @ Spinners
<2018-07-26 Thu>--<2018-07-25 Wed>
:PROPERTIES:
:ID:       _GjndlihXFDF5puJSoLmaFX0@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Renegades @ Spinners Renegades @ Spinners

Follow on MiLB First Pitch  https //stza.co/+xMo8-1G

Shop  https //stza.co/+xMo8-2u

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Renegades @ Spinners
END:VALARM
DTSTART;VALUE=DATE:20180726
DTEND;VALUE=DATE:20180726
UID:_GjndlihXFDF5puJSoLmaFX0@stanza.co
SUMMARY:Renegades @ Spinners
DESCRIPTION:Renegades @ Spinners\n\nFollow on MiLB First Pitch: https://stza.co/+xMo8-1G\n\nShop: https://stza.co/+xMo8-2u\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144533Z
LAST-MODIFIED:20180213T144533Z
TRANSP:OPAQUE
END:VEVENT
* Renegades @ Crosscutters
<2018-07-27 Fri 18:05-21:05>
:PROPERTIES:
:ID:       wpspyPNkruz-lSbTEm7n2va9@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Renegades @ Crosscutters Renegades @ Crosscutters

Follow on MiLB First Pitch  https //stza.co/+x$68-1d

Shop  https //stza.co/+x$68-1v

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Renegades @ Crosscutters
END:VALARM
DTSTART:20180727T230500Z
DTEND:20180728T020500Z
UID:wpspyPNkruz-lSbTEm7n2va9@stanza.co
SUMMARY:Renegades @ Crosscutters
DESCRIPTION:Renegades @ Crosscutters\n\nFollow on MiLB First Pitch: https://stza.co/+x$68-1d\n\nShop: https://stza.co/+x$68-1v\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144533Z
LAST-MODIFIED:20180213T144533Z
TRANSP:OPAQUE
END:VEVENT
* Renegades @ Crosscutters
<2018-07-28 Sat 18:05-21:05>
:PROPERTIES:
:ID:       d0qvaVSUWFKpYJPFwwAMCDIk@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Renegades @ Crosscutters Renegades @ Crosscutters

Follow on MiLB First Pitch  https //stza.co/+x$69-1$

Shop  https //stza.co/+x$69-n

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Renegades @ Crosscutters
END:VALARM
DTSTART:20180728T230500Z
DTEND:20180729T020500Z
UID:d0qvaVSUWFKpYJPFwwAMCDIk@stanza.co
SUMMARY:Renegades @ Crosscutters
DESCRIPTION:Renegades @ Crosscutters\n\nFollow on MiLB First Pitch: https://stza.co/+x$69-1$\n\nShop: https://stza.co/+x$69-n\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144533Z
LAST-MODIFIED:20180213T144533Z
TRANSP:OPAQUE
END:VEVENT
* Renegades @ Crosscutters
<2018-07-29 Sun 16:05-19:05>
:PROPERTIES:
:ID:       LRiuCqbIJCLGwSXLV7SppRB0@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Renegades @ Crosscutters Renegades @ Crosscutters

Follow on MiLB First Pitch  https //stza.co/+x$6a-N

Shop  https //stza.co/+x$6a-25

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Renegades @ Crosscutters
END:VALARM
DTSTART:20180729T210500Z
DTEND:20180730T000500Z
UID:LRiuCqbIJCLGwSXLV7SppRB0@stanza.co
SUMMARY:Renegades @ Crosscutters
DESCRIPTION:Renegades @ Crosscutters\n\nFollow on MiLB First Pitch: https://stza.co/+x$6a-N\n\nShop: https://stza.co/+x$6a-25\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144533Z
LAST-MODIFIED:20180213T144533Z
TRANSP:OPAQUE
END:VEVENT
* Renegades vs. Spinners
<2018-07-30 Mon 18:05-21:05>
:PROPERTIES:
:ID:       6Az4eaRsIhik1l1NJcp4AZDA@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Renegades vs. Spinners Renegades vs. Spinners

Follow on MiLB First Pitch  https //stza.co/+xV$c-3z

Shop  https //stza.co/+xV$c-29

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Renegades vs. Spinners
END:VALARM
DTSTART:20180730T230500Z
DTEND:20180731T020500Z
UID:6Az4eaRsIhik1l1NJcp4AZDA@stanza.co
SUMMARY:Renegades vs. Spinners
DESCRIPTION:Renegades vs. Spinners\n\nFollow on MiLB First Pitch: https://stza.co/+xV$c-3z\n\nShop: https://stza.co/+xV$c-29\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144533Z
LAST-MODIFIED:20180213T144533Z
TRANSP:OPAQUE
END:VEVENT
* Renegades vs. Spinners
<2018-07-31 Tue 10:05-13:05>
:PROPERTIES:
:ID:       ubWyU5FdYbX9WSCm4upqAP0m@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Renegades vs. Spinners Renegades vs. Spinners

Follow on MiLB First Pitch  https //stza.co/+xV$e-1w

Shop  https //stza.co/+xV$e-1C

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Renegades vs. Spinners
END:VALARM
DTSTART:20180731T150500Z
DTEND:20180731T180500Z
UID:ubWyU5FdYbX9WSCm4upqAP0m@stanza.co
SUMMARY:Renegades vs. Spinners
DESCRIPTION:Renegades vs. Spinners\n\nFollow on MiLB First Pitch: https://stza.co/+xV$e-1w\n\nShop: https://stza.co/+xV$e-1C\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144533Z
LAST-MODIFIED:20180213T144533Z
TRANSP:OPAQUE
END:VEVENT
* Renegades vs. Spinners
<2018-08-01 Wed 18:05-21:05>
:PROPERTIES:
:ID:       JVPyvYW7iOBHIrK4zeSePe_A@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Renegades vs. Spinners Renegades vs. Spinners

Follow on MiLB First Pitch  https //stza.co/+xV$h-_

Shop  https //stza.co/+xV$h-20

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Renegades vs. Spinners
END:VALARM
DTSTART:20180801T230500Z
DTEND:20180802T020500Z
UID:JVPyvYW7iOBHIrK4zeSePe_A@stanza.co
SUMMARY:Renegades vs. Spinners
DESCRIPTION:Renegades vs. Spinners\n\nFollow on MiLB First Pitch: https://stza.co/+xV$h-_\n\nShop: https://stza.co/+xV$h-20\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144533Z
LAST-MODIFIED:20180213T144533Z
TRANSP:OPAQUE
END:VEVENT
* Renegades @ Lake Monsters
<2018-08-02 Thu>--<2018-08-01 Wed>
:PROPERTIES:
:ID:       G7JFdHvyg6FNxV7Dd33OONd5@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Renegades @ Lake Monsters Renegades @ Lake Monsters

Follow on MiLB First Pitch  https //stza.co/+xMok-1P

Shop  https //stza.co/+xMok-1O

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Renegades @ Lake Monsters
END:VALARM
DTSTART;VALUE=DATE:20180802
DTEND;VALUE=DATE:20180802
UID:G7JFdHvyg6FNxV7Dd33OONd5@stanza.co
SUMMARY:Renegades @ Lake Monsters
DESCRIPTION:Renegades @ Lake Monsters\n\nFollow on MiLB First Pitch: https://stza.co/+xMok-1P\n\nShop: https://stza.co/+xMok-1O\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144533Z
LAST-MODIFIED:20180213T144533Z
TRANSP:OPAQUE
END:VEVENT
* Renegades @ Lake Monsters
<2018-08-03 Fri>--<2018-08-02 Thu>
:PROPERTIES:
:ID:       mOC-lAupEnfy4DJ-pVlH5qCA@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Renegades @ Lake Monsters Renegades @ Lake Monsters

Follow on MiLB First Pitch  https //stza.co/+xMol-2L

Shop  https //stza.co/+xMol-3K

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Renegades @ Lake Monsters
END:VALARM
DTSTART;VALUE=DATE:20180803
DTEND;VALUE=DATE:20180803
UID:mOC-lAupEnfy4DJ-pVlH5qCA@stanza.co
SUMMARY:Renegades @ Lake Monsters
DESCRIPTION:Renegades @ Lake Monsters\n\nFollow on MiLB First Pitch: https://stza.co/+xMol-2L\n\nShop: https://stza.co/+xMol-3K\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144533Z
LAST-MODIFIED:20180213T144533Z
TRANSP:OPAQUE
END:VEVENT
* Renegades @ Lake Monsters
<2018-08-04 Sat>--<2018-08-03 Fri>
:PROPERTIES:
:ID:       ZPw5_ECtQhI3BVpy4eFTldPA@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Renegades @ Lake Monsters Renegades @ Lake Monsters

Follow on MiLB First Pitch  https //stza.co/+xMom-2r

Shop  https //stza.co/+xMom-1_

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Renegades @ Lake Monsters
END:VALARM
DTSTART;VALUE=DATE:20180804
DTEND;VALUE=DATE:20180804
UID:ZPw5_ECtQhI3BVpy4eFTldPA@stanza.co
SUMMARY:Renegades @ Lake Monsters
DESCRIPTION:Renegades @ Lake Monsters\n\nFollow on MiLB First Pitch: https://stza.co/+xMom-2r\n\nShop: https://stza.co/+xMom-1_\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144533Z
LAST-MODIFIED:20180213T144533Z
TRANSP:OPAQUE
END:VEVENT
* Renegades vs. Cyclones
<2018-08-05 Sun 16:05-19:05>
:PROPERTIES:
:ID:       UyidtnM-9rIw_T05Jval1oWB@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Renegades vs. Cyclones Renegades vs. Cyclones

Follow on MiLB First Pitch  https //stza.co/+xV$j-E

Shop  https //stza.co/+xV$j-I

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Renegades vs. Cyclones
END:VALARM
DTSTART:20180805T210500Z
DTEND:20180806T000500Z
UID:UyidtnM-9rIw_T05Jval1oWB@stanza.co
SUMMARY:Renegades vs. Cyclones
DESCRIPTION:Renegades vs. Cyclones\n\nFollow on MiLB First Pitch: https://stza.co/+xV$j-E\n\nShop: https://stza.co/+xV$j-I\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144533Z
LAST-MODIFIED:20180213T144533Z
TRANSP:OPAQUE
END:VEVENT
* Renegades vs. Cyclones
<2018-08-06 Mon 18:05-21:05>
:PROPERTIES:
:ID:       1ptk7G9BMLRZDkJfww5gqwKf@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Renegades vs. Cyclones Renegades vs. Cyclones

Follow on MiLB First Pitch  https //stza.co/+xV$k-A

Shop  https //stza.co/+xV$k-2o

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Renegades vs. Cyclones
END:VALARM
DTSTART:20180806T230500Z
DTEND:20180807T020500Z
UID:1ptk7G9BMLRZDkJfww5gqwKf@stanza.co
SUMMARY:Renegades vs. Cyclones
DESCRIPTION:Renegades vs. Cyclones\n\nFollow on MiLB First Pitch: https://stza.co/+xV$k-A\n\nShop: https://stza.co/+xV$k-2o\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144533Z
LAST-MODIFIED:20180213T144533Z
TRANSP:OPAQUE
END:VEVENT
* Renegades vs. Cyclones
<2018-08-07 Tue 18:05-21:05>
:PROPERTIES:
:ID:       Q1M4TnZLIIu8jdb7mZa6nmpS@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Renegades vs. Cyclones Renegades vs. Cyclones

Follow on MiLB First Pitch  https //stza.co/+xV$n-P

Shop  https //stza.co/+xV$n-3M

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Renegades vs. Cyclones
END:VALARM
DTSTART:20180807T230500Z
DTEND:20180808T020500Z
UID:Q1M4TnZLIIu8jdb7mZa6nmpS@stanza.co
SUMMARY:Renegades vs. Cyclones
DESCRIPTION:Renegades vs. Cyclones\n\nFollow on MiLB First Pitch: https://stza.co/+xV$n-P\n\nShop: https://stza.co/+xV$n-3M\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144533Z
LAST-MODIFIED:20180213T144533Z
TRANSP:OPAQUE
END:VEVENT
* Renegades @ ValleyCats
<2018-08-08 Wed>--<2018-08-07 Tue>
:PROPERTIES:
:ID:       DCnwKPYwCmHUlEgzbU3jGrDk@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Renegades @ ValleyCats Renegades @ ValleyCats

Follow on MiLB First Pitch  https //stza.co/+xMoh-E

Shop  https //stza.co/+xMoh-3Z

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Renegades @ ValleyCats
END:VALARM
DTSTART;VALUE=DATE:20180808
DTEND;VALUE=DATE:20180808
UID:DCnwKPYwCmHUlEgzbU3jGrDk@stanza.co
SUMMARY:Renegades @ ValleyCats
DESCRIPTION:Renegades @ ValleyCats\n\nFollow on MiLB First Pitch: https://stza.co/+xMoh-E\n\nShop: https://stza.co/+xMoh-3Z\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144533Z
LAST-MODIFIED:20180213T144533Z
TRANSP:OPAQUE
END:VEVENT
* Renegades @ ValleyCats
<2018-08-09 Thu>--<2018-08-08 Wed>
:PROPERTIES:
:ID:       uI0s5VXV3RgfKXkq-SZ8u0QE@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Renegades @ ValleyCats Renegades @ ValleyCats

Follow on MiLB First Pitch  https //stza.co/+xMoi-16

Shop  https //stza.co/+xMoi-1A

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Renegades @ ValleyCats
END:VALARM
DTSTART;VALUE=DATE:20180809
DTEND;VALUE=DATE:20180809
UID:uI0s5VXV3RgfKXkq-SZ8u0QE@stanza.co
SUMMARY:Renegades @ ValleyCats
DESCRIPTION:Renegades @ ValleyCats\n\nFollow on MiLB First Pitch: https://stza.co/+xMoi-16\n\nShop: https://stza.co/+xMoi-1A\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144533Z
LAST-MODIFIED:20180213T144533Z
TRANSP:OPAQUE
END:VEVENT
* Renegades @ ValleyCats
<2018-08-10 Fri>--<2018-08-09 Thu>
:PROPERTIES:
:ID:       TcDdpW62ngXoaVavNlUMJghh@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Renegades @ ValleyCats Renegades @ ValleyCats

Follow on MiLB First Pitch  https //stza.co/+xMoj-2x

Shop  https //stza.co/+xMoj-1X

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Renegades @ ValleyCats
END:VALARM
DTSTART;VALUE=DATE:20180810
DTEND;VALUE=DATE:20180810
UID:TcDdpW62ngXoaVavNlUMJghh@stanza.co
SUMMARY:Renegades @ ValleyCats
DESCRIPTION:Renegades @ ValleyCats\n\nFollow on MiLB First Pitch: https://stza.co/+xMoj-2x\n\nShop: https://stza.co/+xMoj-1X\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144533Z
LAST-MODIFIED:20180213T144533Z
TRANSP:OPAQUE
END:VEVENT
* Renegades vs. IronBirds
<2018-08-11 Sat 17:05-20:05>
:PROPERTIES:
:ID:       Wmy06fpi-YucVPux-NK3lsFF@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Renegades vs. IronBirds Renegades vs. IronBirds

Follow on MiLB First Pitch  https //stza.co/+xV$p-3M

Shop  https //stza.co/+xV$p-1C

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Renegades vs. IronBirds
END:VALARM
DTSTART:20180811T220500Z
DTEND:20180812T010500Z
UID:Wmy06fpi-YucVPux-NK3lsFF@stanza.co
SUMMARY:Renegades vs. IronBirds
DESCRIPTION:Renegades vs. IronBirds\n\nFollow on MiLB First Pitch: https://stza.co/+xV$p-3M\n\nShop: https://stza.co/+xV$p-1C\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144533Z
LAST-MODIFIED:20180213T144533Z
TRANSP:OPAQUE
END:VEVENT
* Renegades vs. IronBirds
<2018-08-12 Sun 16:05-19:05>
:PROPERTIES:
:ID:       1HfSS_p09OtHCnHYgL8hFBsS@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Renegades vs. IronBirds Renegades vs. IronBirds

Follow on MiLB First Pitch  https //stza.co/+xV$q-p

Shop  https //stza.co/+xV$q-2z

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Renegades vs. IronBirds
END:VALARM
DTSTART:20180812T210500Z
DTEND:20180813T000500Z
UID:1HfSS_p09OtHCnHYgL8hFBsS@stanza.co
SUMMARY:Renegades vs. IronBirds
DESCRIPTION:Renegades vs. IronBirds\n\nFollow on MiLB First Pitch: https://stza.co/+xV$q-p\n\nShop: https://stza.co/+xV$q-2z\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144533Z
LAST-MODIFIED:20180213T144533Z
TRANSP:OPAQUE
END:VEVENT
* Renegades @ Yankees
<2018-08-15 Wed>--<2018-08-14 Tue>
:PROPERTIES:
:ID:       nlLImgmRsbRCGU-bJHqTl-kJ@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Renegades @ Yankees Renegades @ Yankees

Follow on MiLB First Pitch  https //stza.co/+xMod-W

Shop  https //stza.co/+xMod-3H

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Renegades @ Yankees
END:VALARM
DTSTART;VALUE=DATE:20180815
DTEND;VALUE=DATE:20180815
UID:nlLImgmRsbRCGU-bJHqTl-kJ@stanza.co
SUMMARY:Renegades @ Yankees
DESCRIPTION:Renegades @ Yankees\n\nFollow on MiLB First Pitch: https://stza.co/+xMod-W\n\nShop: https://stza.co/+xMod-3H\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144533Z
LAST-MODIFIED:20180213T144533Z
TRANSP:OPAQUE
END:VEVENT
* Renegades vs. Yankees
<2018-08-16 Thu 18:05-21:05>
:PROPERTIES:
:ID:       vmg2WWP13Snwo34bZoIp8jam@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Renegades vs. Yankees Renegades vs. Yankees

Follow on MiLB First Pitch  https //stza.co/+xV$t-2d

Shop  https //stza.co/+xV$t-3j

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Renegades vs. Yankees
END:VALARM
DTSTART:20180816T230500Z
DTEND:20180817T020500Z
UID:vmg2WWP13Snwo34bZoIp8jam@stanza.co
SUMMARY:Renegades vs. Yankees
DESCRIPTION:Renegades vs. Yankees\n\nFollow on MiLB First Pitch: https://stza.co/+xV$t-2d\n\nShop: https://stza.co/+xV$t-3j\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144533Z
LAST-MODIFIED:20180213T144533Z
TRANSP:OPAQUE
END:VEVENT
* Renegades vs. Cyclones
<2018-08-17 Fri 18:05-21:05>
:PROPERTIES:
:ID:       LPR67O_Yb9II58uPNJjS7WnN@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Renegades vs. Cyclones Renegades vs. Cyclones

Follow on MiLB First Pitch  https //stza.co/+xV$v-1

Shop  https //stza.co/+xV$v-3l

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Renegades vs. Cyclones
END:VALARM
DTSTART:20180817T230500Z
DTEND:20180818T020500Z
UID:LPR67O_Yb9II58uPNJjS7WnN@stanza.co
SUMMARY:Renegades vs. Cyclones
DESCRIPTION:Renegades vs. Cyclones\n\nFollow on MiLB First Pitch: https://stza.co/+xV$v-1\n\nShop: https://stza.co/+xV$v-3l\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144533Z
LAST-MODIFIED:20180213T144533Z
TRANSP:OPAQUE
END:VEVENT
* Renegades vs. Cyclones
<2018-08-18 Sat 17:05-20:05>
:PROPERTIES:
:ID:       NvuqQwWmGphzdaZYl1oWSgXf@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Renegades vs. Cyclones Renegades vs. Cyclones

Follow on MiLB First Pitch  https //stza.co/+xV$w-_

Shop  https //stza.co/+xV$w-2E

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Renegades vs. Cyclones
END:VALARM
DTSTART:20180818T220500Z
DTEND:20180819T010500Z
UID:NvuqQwWmGphzdaZYl1oWSgXf@stanza.co
SUMMARY:Renegades vs. Cyclones
DESCRIPTION:Renegades vs. Cyclones\n\nFollow on MiLB First Pitch: https://stza.co/+xV$w-_\n\nShop: https://stza.co/+xV$w-2E\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144533Z
LAST-MODIFIED:20180213T144533Z
TRANSP:OPAQUE
END:VEVENT
* Renegades vs. Cyclones
<2018-08-19 Sun 16:05-19:05>
:PROPERTIES:
:ID:       u2tcyhHfWLbYPTALTSg4qogQ@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Renegades vs. Cyclones Renegades vs. Cyclones

Follow on MiLB First Pitch  https //stza.co/+xV$y-15

Shop  https //stza.co/+xV$y-3s

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Renegades vs. Cyclones
END:VALARM
DTSTART:20180819T210500Z
DTEND:20180820T000500Z
UID:u2tcyhHfWLbYPTALTSg4qogQ@stanza.co
SUMMARY:Renegades vs. Cyclones
DESCRIPTION:Renegades vs. Cyclones\n\nFollow on MiLB First Pitch: https://stza.co/+xV$y-15\n\nShop: https://stza.co/+xV$y-3s\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144533Z
LAST-MODIFIED:20180213T144533Z
TRANSP:OPAQUE
END:VEVENT
* Renegades @ Tigers
<2018-08-20 Mon>--<2018-08-19 Sun>
:PROPERTIES:
:ID:       x6COZJ0VY1lzwnXpfgjjP6I1@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Renegades @ Tigers Renegades @ Tigers

Follow on MiLB First Pitch  https //stza.co/+xMmQ-2L

Shop  https //stza.co/+xMmQ-1R

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Renegades @ Tigers
END:VALARM
DTSTART;VALUE=DATE:20180820
DTEND;VALUE=DATE:20180820
UID:x6COZJ0VY1lzwnXpfgjjP6I1@stanza.co
SUMMARY:Renegades @ Tigers
DESCRIPTION:Renegades @ Tigers\n\nFollow on MiLB First Pitch: https://stza.co/+xMmQ-2L\n\nShop: https://stza.co/+xMmQ-1R\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144533Z
LAST-MODIFIED:20180213T144533Z
TRANSP:OPAQUE
END:VEVENT
* Renegades @ Tigers
<2018-08-21 Tue>--<2018-08-20 Mon>
:PROPERTIES:
:ID:       03T09wnxJkD3yvzBya2-mLql@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Renegades @ Tigers Renegades @ Tigers

Follow on MiLB First Pitch  https //stza.co/+xMmR-3A

Shop  https //stza.co/+xMmR-2R

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Renegades @ Tigers
END:VALARM
DTSTART;VALUE=DATE:20180821
DTEND;VALUE=DATE:20180821
UID:03T09wnxJkD3yvzBya2-mLql@stanza.co
SUMMARY:Renegades @ Tigers
DESCRIPTION:Renegades @ Tigers\n\nFollow on MiLB First Pitch: https://stza.co/+xMmR-3A\n\nShop: https://stza.co/+xMmR-2R\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144533Z
LAST-MODIFIED:20180213T144533Z
TRANSP:OPAQUE
END:VEVENT
* Renegades @ Tigers
<2018-08-22 Wed>--<2018-08-21 Tue>
:PROPERTIES:
:ID:       Vws3OKgtXFdjY2q5QA7tuQlb@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Renegades @ Tigers Renegades @ Tigers

Follow on MiLB First Pitch  https //stza.co/+xMmS-16

Shop  https //stza.co/+xMmS-o

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Renegades @ Tigers
END:VALARM
DTSTART;VALUE=DATE:20180822
DTEND;VALUE=DATE:20180822
UID:Vws3OKgtXFdjY2q5QA7tuQlb@stanza.co
SUMMARY:Renegades @ Tigers
DESCRIPTION:Renegades @ Tigers\n\nFollow on MiLB First Pitch: https://stza.co/+xMmS-16\n\nShop: https://stza.co/+xMmS-o\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144533Z
LAST-MODIFIED:20180213T144533Z
TRANSP:OPAQUE
END:VEVENT
* Renegades vs. ValleyCats
<2018-08-23 Thu 18:05-21:05>
:PROPERTIES:
:ID:       PeN97MZB323vMnOj3hLK8Oy6@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Renegades vs. ValleyCats Renegades vs. ValleyCats

Follow on MiLB First Pitch  https //stza.co/+xV$B-2o

Shop  https //stza.co/+xV$B-3

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Renegades vs. ValleyCats
END:VALARM
DTSTART:20180823T230500Z
DTEND:20180824T020500Z
UID:PeN97MZB323vMnOj3hLK8Oy6@stanza.co
SUMMARY:Renegades vs. ValleyCats
DESCRIPTION:Renegades vs. ValleyCats\n\nFollow on MiLB First Pitch: https://stza.co/+xV$B-2o\n\nShop: https://stza.co/+xV$B-3\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144533Z
LAST-MODIFIED:20180213T144533Z
TRANSP:OPAQUE
END:VEVENT
* Renegades vs. ValleyCats
<2018-08-24 Fri 18:05-21:05>
:PROPERTIES:
:ID:       9_ZlYvMBW-eA7ImokIc0WO5P@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Renegades vs. ValleyCats Renegades vs. ValleyCats

Follow on MiLB First Pitch  https //stza.co/+xV$C-3z

Shop  https //stza.co/+xV$C-2W

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Renegades vs. ValleyCats
END:VALARM
DTSTART:20180824T230500Z
DTEND:20180825T020500Z
UID:9_ZlYvMBW-eA7ImokIc0WO5P@stanza.co
SUMMARY:Renegades vs. ValleyCats
DESCRIPTION:Renegades vs. ValleyCats\n\nFollow on MiLB First Pitch: https://stza.co/+xV$C-3z\n\nShop: https://stza.co/+xV$C-2W\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144533Z
LAST-MODIFIED:20180213T144533Z
TRANSP:OPAQUE
END:VEVENT
* Renegades vs. ValleyCats
<2018-08-25 Sat 17:05-20:05>
:PROPERTIES:
:ID:       DLuQqn2pi2fsKXWDPVdFrm1x@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Renegades vs. ValleyCats Renegades vs. ValleyCats

Follow on MiLB First Pitch  https //stza.co/+xV$E-v

Shop  https //stza.co/+xV$E-1D

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Renegades vs. ValleyCats
END:VALARM
DTSTART:20180825T220500Z
DTEND:20180826T010500Z
UID:DLuQqn2pi2fsKXWDPVdFrm1x@stanza.co
SUMMARY:Renegades vs. ValleyCats
DESCRIPTION:Renegades vs. ValleyCats\n\nFollow on MiLB First Pitch: https://stza.co/+xV$E-v\n\nShop: https://stza.co/+xV$E-1D\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144533Z
LAST-MODIFIED:20180213T144533Z
TRANSP:OPAQUE
END:VEVENT
* Renegades vs. Yankees
<2018-08-26 Sun 16:05-19:05>
:PROPERTIES:
:ID:       a6EFu4zDHcyN4MhCX0a6toQB@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Renegades vs. Yankees Renegades vs. Yankees

Follow on MiLB First Pitch  https //stza.co/+xV$G-3H

Shop  https //stza.co/+xV$G-1O

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Renegades vs. Yankees
END:VALARM
DTSTART:20180826T210500Z
DTEND:20180827T000500Z
UID:a6EFu4zDHcyN4MhCX0a6toQB@stanza.co
SUMMARY:Renegades vs. Yankees
DESCRIPTION:Renegades vs. Yankees\n\nFollow on MiLB First Pitch: https://stza.co/+xV$G-3H\n\nShop: https://stza.co/+xV$G-1O\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144533Z
LAST-MODIFIED:20180213T144533Z
TRANSP:OPAQUE
END:VEVENT
* Renegades vs. Yankees
<2018-08-27 Mon 18:05-21:05>
:PROPERTIES:
:ID:       pfhg4jJD20x6zll5cbxWeEqI@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Renegades vs. Yankees Renegades vs. Yankees

Follow on MiLB First Pitch  https //stza.co/+xV$I-E

Shop  https //stza.co/+xV$I-14

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Renegades vs. Yankees
END:VALARM
DTSTART:20180827T230500Z
DTEND:20180828T020500Z
UID:pfhg4jJD20x6zll5cbxWeEqI@stanza.co
SUMMARY:Renegades vs. Yankees
DESCRIPTION:Renegades vs. Yankees\n\nFollow on MiLB First Pitch: https://stza.co/+xV$I-E\n\nShop: https://stza.co/+xV$I-14\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144533Z
LAST-MODIFIED:20180213T144533Z
TRANSP:OPAQUE
END:VEVENT
* Renegades vs. Yankees
<2018-08-28 Tue 18:05-21:05>
:PROPERTIES:
:ID:       vzSy04LotJN-JC3NBC3RI_6S@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Renegades vs. Yankees Renegades vs. Yankees

Follow on MiLB First Pitch  https //stza.co/+xV$L-T

Shop  https //stza.co/+xV$L-1z

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Renegades vs. Yankees
END:VALARM
DTSTART:20180828T230500Z
DTEND:20180829T020500Z
UID:vzSy04LotJN-JC3NBC3RI_6S@stanza.co
SUMMARY:Renegades vs. Yankees
DESCRIPTION:Renegades vs. Yankees\n\nFollow on MiLB First Pitch: https://stza.co/+xV$L-T\n\nShop: https://stza.co/+xV$L-1z\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144533Z
LAST-MODIFIED:20180213T144533Z
TRANSP:OPAQUE
END:VEVENT
* Renegades @ Cyclones
<2018-08-29 Wed>--<2018-08-28 Tue>
:PROPERTIES:
:ID:       khxl9jJ-EyrDDk0AWDCbOcTt@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Renegades @ Cyclones Renegades @ Cyclones

Follow on MiLB First Pitch  https //stza.co/+xMmN-1d

Shop  https //stza.co/+xMmN-3E

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Renegades @ Cyclones
END:VALARM
DTSTART;VALUE=DATE:20180829
DTEND;VALUE=DATE:20180829
UID:khxl9jJ-EyrDDk0AWDCbOcTt@stanza.co
SUMMARY:Renegades @ Cyclones
DESCRIPTION:Renegades @ Cyclones\n\nFollow on MiLB First Pitch: https://stza.co/+xMmN-1d\n\nShop: https://stza.co/+xMmN-3E\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144533Z
LAST-MODIFIED:20180213T144533Z
TRANSP:OPAQUE
END:VEVENT
* Renegades @ Cyclones
<2018-08-30 Thu>--<2018-08-29 Wed>
:PROPERTIES:
:ID:       WZ2k8efnKmO25jEAAKCqsb0R@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Renegades @ Cyclones Renegades @ Cyclones

Follow on MiLB First Pitch  https //stza.co/+xMmO-2Q

Shop  https //stza.co/+xMmO-3L

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Renegades @ Cyclones
END:VALARM
DTSTART;VALUE=DATE:20180830
DTEND;VALUE=DATE:20180830
UID:WZ2k8efnKmO25jEAAKCqsb0R@stanza.co
SUMMARY:Renegades @ Cyclones
DESCRIPTION:Renegades @ Cyclones\n\nFollow on MiLB First Pitch: https://stza.co/+xMmO-2Q\n\nShop: https://stza.co/+xMmO-3L\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144533Z
LAST-MODIFIED:20180213T144533Z
TRANSP:OPAQUE
END:VEVENT
* Renegades @ Cyclones
<2018-08-31 Fri>--<2018-08-30 Thu>
:PROPERTIES:
:ID:       fz_di62XCF3FIBHG1KXmSgnb@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Renegades @ Cyclones Renegades @ Cyclones

Follow on MiLB First Pitch  https //stza.co/+xMmP-1X

Shop  https //stza.co/+xMmP-s

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Renegades @ Cyclones
END:VALARM
DTSTART;VALUE=DATE:20180831
DTEND;VALUE=DATE:20180831
UID:fz_di62XCF3FIBHG1KXmSgnb@stanza.co
SUMMARY:Renegades @ Cyclones
DESCRIPTION:Renegades @ Cyclones\n\nFollow on MiLB First Pitch: https://stza.co/+xMmP-1X\n\nShop: https://stza.co/+xMmP-s\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144533Z
LAST-MODIFIED:20180213T144533Z
TRANSP:OPAQUE
END:VEVENT
* Renegades vs. IronBirds
<2018-09-01 Sat 17:05-20:05>
:PROPERTIES:
:ID:       03nyAbmfwLSuwK20zfdjGLrR@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Renegades vs. IronBirds Renegades vs. IronBirds

Follow on MiLB First Pitch  https //stza.co/+xV$M-1Y

Shop  https //stza.co/+xV$M-1E

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Renegades vs. IronBirds
END:VALARM
DTSTART:20180901T220500Z
DTEND:20180902T010500Z
UID:03nyAbmfwLSuwK20zfdjGLrR@stanza.co
SUMMARY:Renegades vs. IronBirds
DESCRIPTION:Renegades vs. IronBirds\n\nFollow on MiLB First Pitch: https://stza.co/+xV$M-1Y\n\nShop: https://stza.co/+xV$M-1E\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144533Z
LAST-MODIFIED:20180213T144533Z
TRANSP:OPAQUE
END:VEVENT
* Renegades vs. IronBirds
<2018-09-02 Sun 16:05-19:05>
:PROPERTIES:
:ID:       6qNnwlhknz8h6FRMfR_BA1hb@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Renegades vs. IronBirds Renegades vs. IronBirds

Follow on MiLB First Pitch  https //stza.co/+xV$O-l

Shop  https //stza.co/+xV$O-a

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Renegades vs. IronBirds
END:VALARM
DTSTART:20180902T210500Z
DTEND:20180903T000500Z
UID:6qNnwlhknz8h6FRMfR_BA1hb@stanza.co
SUMMARY:Renegades vs. IronBirds
DESCRIPTION:Renegades vs. IronBirds\n\nFollow on MiLB First Pitch: https://stza.co/+xV$O-l\n\nShop: https://stza.co/+xV$O-a\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144533Z
LAST-MODIFIED:20180213T144533Z
TRANSP:OPAQUE
END:VEVENT
* Renegades vs. IronBirds
<2018-09-03 Mon 18:05-21:05>
:PROPERTIES:
:ID:       PbRfwsw_AeU9WOzWLUw5btnz@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Renegades vs. IronBirds Renegades vs. IronBirds

Follow on MiLB First Pitch  https //stza.co/+xV$R-k

Shop  https //stza.co/+xV$R-e

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Renegades vs. IronBirds
END:VALARM
DTSTART:20180903T230500Z
DTEND:20180904T020500Z
UID:PbRfwsw_AeU9WOzWLUw5btnz@stanza.co
SUMMARY:Renegades vs. IronBirds
DESCRIPTION:Renegades vs. IronBirds\n\nFollow on MiLB First Pitch: https://stza.co/+xV$R-k\n\nShop: https://stza.co/+xV$R-e\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144533Z
LAST-MODIFIED:20180213T144533Z
TRANSP:OPAQUE
END:VEVENT
