#+TITLE:       Main Google calendar entries
#+AUTHOR:      Eric S Fraga
#+EMAIL:       e.fraga@ucl.ac.uk
#+DESCRIPTION: converted using the ical2org awk script
#+CATEGORY:    google
#+STARTUP:     hidestars
#+STARTUP:     overview

* COMMENT original iCal preamble

* Missions @ Travelers
<2018-04-05 Thu 19:10-22:10>
:PROPERTIES:
:ID:       YWd7xL06iIVe7kuFi9N1buvM@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Missions @ Travelers Missions @ Travelers

Follow on MiLB First Pitch  https //stza.co/+w070-27

Shop  https //stza.co/+w070-

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Missions @ Travelers
END:VALARM
DTSTART:20180406T001000Z
DTEND:20180406T031000Z
UID:YWd7xL06iIVe7kuFi9N1buvM@stanza.co
SUMMARY:Missions @ Travelers
DESCRIPTION:Missions @ Travelers\n\nFollow on MiLB First Pitch: https://stza.co/+w070-27\n\nShop: https://stza.co/+w070-\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144556Z
LAST-MODIFIED:20180213T144556Z
TRANSP:OPAQUE
END:VEVENT
* Missions @ Travelers
<2018-04-06 Fri 19:10-22:10>
:PROPERTIES:
:ID:       2VtGjefgExsXV6G50VqQDfrq@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Missions @ Travelers Missions @ Travelers

Follow on MiLB First Pitch  https //stza.co/+w071-3W

Shop  https //stza.co/+w071-2Q

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Missions @ Travelers
END:VALARM
DTSTART:20180407T001000Z
DTEND:20180407T031000Z
UID:2VtGjefgExsXV6G50VqQDfrq@stanza.co
SUMMARY:Missions @ Travelers
DESCRIPTION:Missions @ Travelers\n\nFollow on MiLB First Pitch: https://stza.co/+w071-3W\n\nShop: https://stza.co/+w071-2Q\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144556Z
LAST-MODIFIED:20180213T144556Z
TRANSP:OPAQUE
END:VEVENT
* Missions @ Travelers
<2018-04-07 Sat 18:10-21:10>
:PROPERTIES:
:ID:       0czxziL3twQZtxQA85HRxqy-@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Missions @ Travelers Missions @ Travelers

Follow on MiLB First Pitch  https //stza.co/+w072-1D

Shop  https //stza.co/+w072-J

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Missions @ Travelers
END:VALARM
DTSTART:20180407T231000Z
DTEND:20180408T021000Z
UID:0czxziL3twQZtxQA85HRxqy-@stanza.co
SUMMARY:Missions @ Travelers
DESCRIPTION:Missions @ Travelers\n\nFollow on MiLB First Pitch: https://stza.co/+w072-1D\n\nShop: https://stza.co/+w072-J\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144556Z
LAST-MODIFIED:20180213T144556Z
TRANSP:OPAQUE
END:VEVENT
* Missions @ Naturals
<2018-04-08 Sun 16:05-19:05>
:PROPERTIES:
:ID:       rcQ7sdcmCvH8T3vg9Jk3L0sP@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Missions @ Naturals Missions @ Naturals

Follow on MiLB First Pitch  https //stza.co/+wi3s-2I

Shop  https //stza.co/+wi3s-1G

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Missions @ Naturals
END:VALARM
DTSTART:20180408T210500Z
DTEND:20180409T000500Z
UID:rcQ7sdcmCvH8T3vg9Jk3L0sP@stanza.co
SUMMARY:Missions @ Naturals
DESCRIPTION:Missions @ Naturals\n\nFollow on MiLB First Pitch: https://stza.co/+wi3s-2I\n\nShop: https://stza.co/+wi3s-1G\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144556Z
LAST-MODIFIED:20180213T144556Z
TRANSP:OPAQUE
END:VEVENT
* Missions @ Naturals
<2018-04-09 Mon 19:05-22:05>
:PROPERTIES:
:ID:       qz2QmVzgk57H7e5DDl33vcUO@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Missions @ Naturals Missions @ Naturals

Follow on MiLB First Pitch  https //stza.co/+wi3t-1r

Shop  https //stza.co/+wi3t-2S

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Missions @ Naturals
END:VALARM
DTSTART:20180410T000500Z
DTEND:20180410T030500Z
UID:qz2QmVzgk57H7e5DDl33vcUO@stanza.co
SUMMARY:Missions @ Naturals
DESCRIPTION:Missions @ Naturals\n\nFollow on MiLB First Pitch: https://stza.co/+wi3t-1r\n\nShop: https://stza.co/+wi3t-2S\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144556Z
LAST-MODIFIED:20180213T144556Z
TRANSP:OPAQUE
END:VEVENT
* Missions @ Naturals
<2018-04-10 Tue 11:05-14:05>
:PROPERTIES:
:ID:       Se9SHxDOzuboUzRnQw75nPDD@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Missions @ Naturals Missions @ Naturals

Follow on MiLB First Pitch  https //stza.co/+wi3u-o

Shop  https //stza.co/+wi3u-N

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Missions @ Naturals
END:VALARM
DTSTART:20180410T160500Z
DTEND:20180410T190500Z
UID:Se9SHxDOzuboUzRnQw75nPDD@stanza.co
SUMMARY:Missions @ Naturals
DESCRIPTION:Missions @ Naturals\n\nFollow on MiLB First Pitch: https://stza.co/+wi3u-o\n\nShop: https://stza.co/+wi3u-N\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144556Z
LAST-MODIFIED:20180213T144556Z
TRANSP:OPAQUE
END:VEVENT
* Missions vs. Travelers
<2018-04-12 Thu 19:05-22:05>
:PROPERTIES:
:ID:       HyMtgwz_eBLzlq8TLTYg5BO7@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Missions vs. Travelers Missions vs. Travelers

Follow on MiLB First Pitch  https //stza.co/+wMvM-p

Shop  https //stza.co/+wMvM-1K

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Missions vs. Travelers
END:VALARM
DTSTART:20180413T000500Z
DTEND:20180413T030500Z
UID:HyMtgwz_eBLzlq8TLTYg5BO7@stanza.co
SUMMARY:Missions vs. Travelers
DESCRIPTION:Missions vs. Travelers\n\nFollow on MiLB First Pitch: https://stza.co/+wMvM-p\n\nShop: https://stza.co/+wMvM-1K\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144556Z
LAST-MODIFIED:20180213T144556Z
TRANSP:OPAQUE
END:VEVENT
* Missions vs. Travelers
<2018-04-13 Fri 19:05-22:05>
:PROPERTIES:
:ID:       dmwCQCzBmglrlYuI1BDtM_hE@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Missions vs. Travelers Missions vs. Travelers

Follow on MiLB First Pitch  https //stza.co/+wMvR-2K

Shop  https //stza.co/+wMvR-1H

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Missions vs. Travelers
END:VALARM
DTSTART:20180414T000500Z
DTEND:20180414T030500Z
UID:dmwCQCzBmglrlYuI1BDtM_hE@stanza.co
SUMMARY:Missions vs. Travelers
DESCRIPTION:Missions vs. Travelers\n\nFollow on MiLB First Pitch: https://stza.co/+wMvR-2K\n\nShop: https://stza.co/+wMvR-1H\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144556Z
LAST-MODIFIED:20180213T144556Z
TRANSP:OPAQUE
END:VEVENT
* Missions vs. Travelers
<2018-04-14 Sat 19:05-22:05>
:PROPERTIES:
:ID:       Q5WGv_72cP-UMS2aRNWGvrOM@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Missions vs. Travelers Missions vs. Travelers

Follow on MiLB First Pitch  https //stza.co/+wMvV-3j

Shop  https //stza.co/+wMvV-3t

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Missions vs. Travelers
END:VALARM
DTSTART:20180415T000500Z
DTEND:20180415T030500Z
UID:Q5WGv_72cP-UMS2aRNWGvrOM@stanza.co
SUMMARY:Missions vs. Travelers
DESCRIPTION:Missions vs. Travelers\n\nFollow on MiLB First Pitch: https://stza.co/+wMvV-3j\n\nShop: https://stza.co/+wMvV-3t\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144556Z
LAST-MODIFIED:20180213T144556Z
TRANSP:OPAQUE
END:VEVENT
* Missions vs. Naturals
<2018-04-15 Sun 14:05-17:05>
:PROPERTIES:
:ID:       fnMDSntHehV4w0uWPKpkvDqU@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Missions vs. Naturals Missions vs. Naturals

Follow on MiLB First Pitch  https //stza.co/+wMvY-o

Shop  https //stza.co/+wMvY-P

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Missions vs. Naturals
END:VALARM
DTSTART:20180415T190500Z
DTEND:20180415T220500Z
UID:fnMDSntHehV4w0uWPKpkvDqU@stanza.co
SUMMARY:Missions vs. Naturals
DESCRIPTION:Missions vs. Naturals\n\nFollow on MiLB First Pitch: https://stza.co/+wMvY-o\n\nShop: https://stza.co/+wMvY-P\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144556Z
LAST-MODIFIED:20180213T144556Z
TRANSP:OPAQUE
END:VEVENT
* Missions vs. Naturals
<2018-04-16 Mon 11:05-14:05>
:PROPERTIES:
:ID:       7snSjYXfwBDpPU9bB-QkkBm9@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Missions vs. Naturals Missions vs. Naturals

Follow on MiLB First Pitch  https //stza.co/+wMv$-3E

Shop  https //stza.co/+wMv$-2y

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Missions vs. Naturals
END:VALARM
DTSTART:20180416T160500Z
DTEND:20180416T190500Z
UID:7snSjYXfwBDpPU9bB-QkkBm9@stanza.co
SUMMARY:Missions vs. Naturals
DESCRIPTION:Missions vs. Naturals\n\nFollow on MiLB First Pitch: https://stza.co/+wMv$-3E\n\nShop: https://stza.co/+wMv$-2y\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144556Z
LAST-MODIFIED:20180213T144556Z
TRANSP:OPAQUE
END:VEVENT
* Missions vs. Naturals
<2018-04-17 Tue 19:05-22:05>
:PROPERTIES:
:ID:       JPqDcHYWS1FbV4HtYquy_bwy@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Missions vs. Naturals Missions vs. Naturals

Follow on MiLB First Pitch  https //stza.co/+wMw1-Y

Shop  https //stza.co/+wMw1-b

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Missions vs. Naturals
END:VALARM
DTSTART:20180418T000500Z
DTEND:20180418T030500Z
UID:JPqDcHYWS1FbV4HtYquy_bwy@stanza.co
SUMMARY:Missions vs. Naturals
DESCRIPTION:Missions vs. Naturals\n\nFollow on MiLB First Pitch: https://stza.co/+wMw1-Y\n\nShop: https://stza.co/+wMw1-b\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144556Z
LAST-MODIFIED:20180213T144556Z
TRANSP:OPAQUE
END:VEVENT
* Missions @ RockHounds
<2018-04-19 Thu 19:00-22:00>
:PROPERTIES:
:ID:       _ei8ZPn05zfBCgaq7hq3id6p@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Missions @ RockHounds Missions @ RockHounds

Follow on MiLB First Pitch  https //stza.co/+wX5f-j

Shop  https //stza.co/+wX5f-27

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Missions @ RockHounds
END:VALARM
DTSTART:20180420T000000Z
DTEND:20180420T030000Z
UID:_ei8ZPn05zfBCgaq7hq3id6p@stanza.co
SUMMARY:Missions @ RockHounds
DESCRIPTION:Missions @ RockHounds\n\nFollow on MiLB First Pitch: https://stza.co/+wX5f-j\n\nShop: https://stza.co/+wX5f-27\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144556Z
LAST-MODIFIED:20180213T144556Z
TRANSP:OPAQUE
END:VEVENT
* Missions @ RockHounds
<2018-04-20 Fri 19:00-22:00>
:PROPERTIES:
:ID:       JCppK_6JrhX83HHb1UhS4ubY@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Missions @ RockHounds Missions @ RockHounds

Follow on MiLB First Pitch  https //stza.co/+wX5g-2I

Shop  https //stza.co/+wX5g-2T

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Missions @ RockHounds
END:VALARM
DTSTART:20180421T000000Z
DTEND:20180421T030000Z
UID:JCppK_6JrhX83HHb1UhS4ubY@stanza.co
SUMMARY:Missions @ RockHounds
DESCRIPTION:Missions @ RockHounds\n\nFollow on MiLB First Pitch: https://stza.co/+wX5g-2I\n\nShop: https://stza.co/+wX5g-2T\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144556Z
LAST-MODIFIED:20180213T144556Z
TRANSP:OPAQUE
END:VEVENT
* Missions @ RockHounds
<2018-04-21 Sat 19:00-22:00>
:PROPERTIES:
:ID:       wCDOrd_2Qlej2b990BYFfDnb@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Missions @ RockHounds Missions @ RockHounds

Follow on MiLB First Pitch  https //stza.co/+wX5h-U

Shop  https //stza.co/+wX5h-2D

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Missions @ RockHounds
END:VALARM
DTSTART:20180422T000000Z
DTEND:20180422T030000Z
UID:wCDOrd_2Qlej2b990BYFfDnb@stanza.co
SUMMARY:Missions @ RockHounds
DESCRIPTION:Missions @ RockHounds\n\nFollow on MiLB First Pitch: https://stza.co/+wX5h-U\n\nShop: https://stza.co/+wX5h-2D\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144556Z
LAST-MODIFIED:20180213T144556Z
TRANSP:OPAQUE
END:VEVENT
* Missions @ RockHounds
<2018-04-22 Sun 14:00-17:00>
:PROPERTIES:
:ID:       UzzLuYv9_4W06UzYinusFkOr@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Missions @ RockHounds Missions @ RockHounds

Follow on MiLB First Pitch  https //stza.co/+wX5i-1q

Shop  https //stza.co/+wX5i-3H

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Missions @ RockHounds
END:VALARM
DTSTART:20180422T190000Z
DTEND:20180422T220000Z
UID:UzzLuYv9_4W06UzYinusFkOr@stanza.co
SUMMARY:Missions @ RockHounds
DESCRIPTION:Missions @ RockHounds\n\nFollow on MiLB First Pitch: https://stza.co/+wX5i-1q\n\nShop: https://stza.co/+wX5i-3H\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144556Z
LAST-MODIFIED:20180213T144556Z
TRANSP:OPAQUE
END:VEVENT
* Missions vs. RoughRiders
<2018-04-23 Mon 19:05-22:05>
:PROPERTIES:
:ID:       ZOAAoR5s7N3MRaxugqDPe6z0@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Missions vs. RoughRiders Missions vs. RoughRiders

Follow on MiLB First Pitch  https //stza.co/+wMw3-l

Shop  https //stza.co/+wMw3-2b

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Missions vs. RoughRiders
END:VALARM
DTSTART:20180424T000500Z
DTEND:20180424T030500Z
UID:ZOAAoR5s7N3MRaxugqDPe6z0@stanza.co
SUMMARY:Missions vs. RoughRiders
DESCRIPTION:Missions vs. RoughRiders\n\nFollow on MiLB First Pitch: https://stza.co/+wMw3-l\n\nShop: https://stza.co/+wMw3-2b\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144556Z
LAST-MODIFIED:20180213T144556Z
TRANSP:OPAQUE
END:VEVENT
* Missions vs. RoughRiders
<2018-04-24 Tue 19:05-22:05>
:PROPERTIES:
:ID:       _vaDab7mQHLicKifOw9Qc7b6@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Missions vs. RoughRiders Missions vs. RoughRiders

Follow on MiLB First Pitch  https //stza.co/+wMw5-38

Shop  https //stza.co/+wMw5-f

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Missions vs. RoughRiders
END:VALARM
DTSTART:20180425T000500Z
DTEND:20180425T030500Z
UID:_vaDab7mQHLicKifOw9Qc7b6@stanza.co
SUMMARY:Missions vs. RoughRiders
DESCRIPTION:Missions vs. RoughRiders\n\nFollow on MiLB First Pitch: https://stza.co/+wMw5-38\n\nShop: https://stza.co/+wMw5-f\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144556Z
LAST-MODIFIED:20180213T144556Z
TRANSP:OPAQUE
END:VEVENT
* Missions vs. RoughRiders
<2018-04-25 Wed 19:05-22:05>
:PROPERTIES:
:ID:       6TYAxi4jEyN1yWpGLh8MUw0Z@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Missions vs. RoughRiders Missions vs. RoughRiders

Follow on MiLB First Pitch  https //stza.co/+wMw6-x

Shop  https //stza.co/+wMw6-2e

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Missions vs. RoughRiders
END:VALARM
DTSTART:20180426T000500Z
DTEND:20180426T030500Z
UID:6TYAxi4jEyN1yWpGLh8MUw0Z@stanza.co
SUMMARY:Missions vs. RoughRiders
DESCRIPTION:Missions vs. RoughRiders\n\nFollow on MiLB First Pitch: https://stza.co/+wMw6-x\n\nShop: https://stza.co/+wMw6-2e\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144556Z
LAST-MODIFIED:20180213T144556Z
TRANSP:OPAQUE
END:VEVENT
* Missions vs. RoughRiders
<2018-04-26 Thu 19:05-22:05>
:PROPERTIES:
:ID:       aA6BacKUpbM7w7dAHp_bE9s7@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Missions vs. RoughRiders Missions vs. RoughRiders

Follow on MiLB First Pitch  https //stza.co/+wMw8-v

Shop  https //stza.co/+wMw8-1M

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Missions vs. RoughRiders
END:VALARM
DTSTART:20180427T000500Z
DTEND:20180427T030500Z
UID:aA6BacKUpbM7w7dAHp_bE9s7@stanza.co
SUMMARY:Missions vs. RoughRiders
DESCRIPTION:Missions vs. RoughRiders\n\nFollow on MiLB First Pitch: https://stza.co/+wMw8-v\n\nShop: https://stza.co/+wMw8-1M\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144556Z
LAST-MODIFIED:20180213T144556Z
TRANSP:OPAQUE
END:VEVENT
* Missions vs. RockHounds
<2018-04-27 Fri 19:05-22:05>
:PROPERTIES:
:ID:       -SrkdT9MdrTHiI8uGg2dkP6p@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Missions vs. RockHounds Missions vs. RockHounds

Follow on MiLB First Pitch  https //stza.co/+wMwa-R

Shop  https //stza.co/+wMwa-1A

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Missions vs. RockHounds
END:VALARM
DTSTART:20180428T000500Z
DTEND:20180428T030500Z
UID:-SrkdT9MdrTHiI8uGg2dkP6p@stanza.co
SUMMARY:Missions vs. RockHounds
DESCRIPTION:Missions vs. RockHounds\n\nFollow on MiLB First Pitch: https://stza.co/+wMwa-R\n\nShop: https://stza.co/+wMwa-1A\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144556Z
LAST-MODIFIED:20180213T144556Z
TRANSP:OPAQUE
END:VEVENT
* Missions vs. RockHounds
<2018-04-28 Sat 19:05-22:05>
:PROPERTIES:
:ID:       Jk7X7wFJ4puzaNfpsMeb7EQO@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Missions vs. RockHounds Missions vs. RockHounds

Follow on MiLB First Pitch  https //stza.co/+wMwd-1x

Shop  https //stza.co/+wMwd-3U

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Missions vs. RockHounds
END:VALARM
DTSTART:20180429T000500Z
DTEND:20180429T030500Z
UID:Jk7X7wFJ4puzaNfpsMeb7EQO@stanza.co
SUMMARY:Missions vs. RockHounds
DESCRIPTION:Missions vs. RockHounds\n\nFollow on MiLB First Pitch: https://stza.co/+wMwd-1x\n\nShop: https://stza.co/+wMwd-3U\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144556Z
LAST-MODIFIED:20180213T144556Z
TRANSP:OPAQUE
END:VEVENT
* Missions vs. RockHounds
<2018-04-29 Sun 14:05-17:05>
:PROPERTIES:
:ID:       YaqaqvZbThUa606NdBLiAmq3@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Missions vs. RockHounds Missions vs. RockHounds

Follow on MiLB First Pitch  https //stza.co/+wMwf-2N

Shop  https //stza.co/+wMwf-2B

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Missions vs. RockHounds
END:VALARM
DTSTART:20180429T190500Z
DTEND:20180429T220500Z
UID:YaqaqvZbThUa606NdBLiAmq3@stanza.co
SUMMARY:Missions vs. RockHounds
DESCRIPTION:Missions vs. RockHounds\n\nFollow on MiLB First Pitch: https://stza.co/+wMwf-2N\n\nShop: https://stza.co/+wMwf-2B\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144556Z
LAST-MODIFIED:20180213T144556Z
TRANSP:OPAQUE
END:VEVENT
* Missions vs. RockHounds
<2018-04-30 Mon 11:05-14:05>
:PROPERTIES:
:ID:       FhEVNgQ6UfMNOEBrjGCADyEF@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Missions vs. RockHounds Missions vs. RockHounds

Follow on MiLB First Pitch  https //stza.co/+wMwi-p

Shop  https //stza.co/+wMwi-D

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Missions vs. RockHounds
END:VALARM
DTSTART:20180430T160500Z
DTEND:20180430T190500Z
UID:FhEVNgQ6UfMNOEBrjGCADyEF@stanza.co
SUMMARY:Missions vs. RockHounds
DESCRIPTION:Missions vs. RockHounds\n\nFollow on MiLB First Pitch: https://stza.co/+wMwi-p\n\nShop: https://stza.co/+wMwi-D\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144556Z
LAST-MODIFIED:20180213T144556Z
TRANSP:OPAQUE
END:VEVENT
* Missions @ RoughRiders
<2018-05-01 Tue 19:05-22:05>
:PROPERTIES:
:ID:       vUtuZhuse7i8ELX_YOaGpfqA@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Missions @ RoughRiders Missions @ RoughRiders

Follow on MiLB First Pitch  https //stza.co/+wYbO-2e

Shop  https //stza.co/+wYbO-d

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Missions @ RoughRiders
END:VALARM
DTSTART:20180502T000500Z
DTEND:20180502T030500Z
UID:vUtuZhuse7i8ELX_YOaGpfqA@stanza.co
SUMMARY:Missions @ RoughRiders
DESCRIPTION:Missions @ RoughRiders\n\nFollow on MiLB First Pitch: https://stza.co/+wYbO-2e\n\nShop: https://stza.co/+wYbO-d\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144556Z
LAST-MODIFIED:20180213T144556Z
TRANSP:OPAQUE
END:VEVENT
* Missions @ RoughRiders
<2018-05-02 Wed 11:05-14:05>
:PROPERTIES:
:ID:       Hq_aFD7Ns34_xim3Id57UJVx@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Missions @ RoughRiders Missions @ RoughRiders

Follow on MiLB First Pitch  https //stza.co/+wYbP-2i

Shop  https //stza.co/+wYbP-1f

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Missions @ RoughRiders
END:VALARM
DTSTART:20180502T160500Z
DTEND:20180502T190500Z
UID:Hq_aFD7Ns34_xim3Id57UJVx@stanza.co
SUMMARY:Missions @ RoughRiders
DESCRIPTION:Missions @ RoughRiders\n\nFollow on MiLB First Pitch: https://stza.co/+wYbP-2i\n\nShop: https://stza.co/+wYbP-1f\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144556Z
LAST-MODIFIED:20180213T144556Z
TRANSP:OPAQUE
END:VEVENT
* Missions @ RoughRiders
<2018-05-03 Thu 19:05-22:05>
:PROPERTIES:
:ID:       UkTk7fRy0RItepVYkF9utiz3@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Missions @ RoughRiders Missions @ RoughRiders

Follow on MiLB First Pitch  https //stza.co/+wYbQ-29

Shop  https //stza.co/+wYbQ-1f

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Missions @ RoughRiders
END:VALARM
DTSTART:20180504T000500Z
DTEND:20180504T030500Z
UID:UkTk7fRy0RItepVYkF9utiz3@stanza.co
SUMMARY:Missions @ RoughRiders
DESCRIPTION:Missions @ RoughRiders\n\nFollow on MiLB First Pitch: https://stza.co/+wYbQ-29\n\nShop: https://stza.co/+wYbQ-1f\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144556Z
LAST-MODIFIED:20180213T144556Z
TRANSP:OPAQUE
END:VEVENT
* Missions @ RoughRiders
<2018-05-04 Fri 19:05-22:05>
:PROPERTIES:
:ID:       skpFHzKd9fYuvlaeQL6OjP4m@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Missions @ RoughRiders Missions @ RoughRiders

Follow on MiLB First Pitch  https //stza.co/+wYbR-1Q

Shop  https //stza.co/+wYbR-1A

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Missions @ RoughRiders
END:VALARM
DTSTART:20180505T000500Z
DTEND:20180505T030500Z
UID:skpFHzKd9fYuvlaeQL6OjP4m@stanza.co
SUMMARY:Missions @ RoughRiders
DESCRIPTION:Missions @ RoughRiders\n\nFollow on MiLB First Pitch: https://stza.co/+wYbR-1Q\n\nShop: https://stza.co/+wYbR-1A\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144556Z
LAST-MODIFIED:20180213T144556Z
TRANSP:OPAQUE
END:VEVENT
* Missions vs. Hooks
<2018-05-05 Sat 19:05-22:05>
:PROPERTIES:
:ID:       E6GjnSo-2FoPiNNranh9ffep@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Missions vs. Hooks Missions vs. Hooks

Follow on MiLB First Pitch  https //stza.co/+wMwk-12

Shop  https //stza.co/+wMwk-2w

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Missions vs. Hooks
END:VALARM
DTSTART:20180506T000500Z
DTEND:20180506T030500Z
UID:E6GjnSo-2FoPiNNranh9ffep@stanza.co
SUMMARY:Missions vs. Hooks
DESCRIPTION:Missions vs. Hooks\n\nFollow on MiLB First Pitch: https://stza.co/+wMwk-12\n\nShop: https://stza.co/+wMwk-2w\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144556Z
LAST-MODIFIED:20180213T144556Z
TRANSP:OPAQUE
END:VEVENT
* Missions vs. Hooks
<2018-05-06 Sun 14:05-17:05>
:PROPERTIES:
:ID:       lqwKvSG3iLCJufrhNDwXqYW3@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Missions vs. Hooks Missions vs. Hooks

Follow on MiLB First Pitch  https //stza.co/+wMwm-2h

Shop  https //stza.co/+wMwm-1d

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Missions vs. Hooks
END:VALARM
DTSTART:20180506T190500Z
DTEND:20180506T220500Z
UID:lqwKvSG3iLCJufrhNDwXqYW3@stanza.co
SUMMARY:Missions vs. Hooks
DESCRIPTION:Missions vs. Hooks\n\nFollow on MiLB First Pitch: https://stza.co/+wMwm-2h\n\nShop: https://stza.co/+wMwm-1d\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144556Z
LAST-MODIFIED:20180213T144556Z
TRANSP:OPAQUE
END:VEVENT
* Missions vs. Hooks
<2018-05-07 Mon 19:05-22:05>
:PROPERTIES:
:ID:       HVC4g4ka98eyJys1vLhBzXGj@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Missions vs. Hooks Missions vs. Hooks

Follow on MiLB First Pitch  https //stza.co/+wMwn-27

Shop  https //stza.co/+wMwn-s

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Missions vs. Hooks
END:VALARM
DTSTART:20180508T000500Z
DTEND:20180508T030500Z
UID:HVC4g4ka98eyJys1vLhBzXGj@stanza.co
SUMMARY:Missions vs. Hooks
DESCRIPTION:Missions vs. Hooks\n\nFollow on MiLB First Pitch: https://stza.co/+wMwn-27\n\nShop: https://stza.co/+wMwn-s\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144556Z
LAST-MODIFIED:20180213T144556Z
TRANSP:OPAQUE
END:VEVENT
* Missions vs. Hooks
<2018-05-08 Tue 19:05-22:05>
:PROPERTIES:
:ID:       xgUNOJXjSE5-_5x_sDI5bEO7@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Missions vs. Hooks Missions vs. Hooks

Follow on MiLB First Pitch  https //stza.co/+wMwq-2i

Shop  https //stza.co/+wMwq-2s

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Missions vs. Hooks
END:VALARM
DTSTART:20180509T000500Z
DTEND:20180509T030500Z
UID:xgUNOJXjSE5-_5x_sDI5bEO7@stanza.co
SUMMARY:Missions vs. Hooks
DESCRIPTION:Missions vs. Hooks\n\nFollow on MiLB First Pitch: https://stza.co/+wMwq-2i\n\nShop: https://stza.co/+wMwq-2s\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144556Z
LAST-MODIFIED:20180213T144556Z
TRANSP:OPAQUE
END:VEVENT
* Missions vs. RoughRiders
<2018-05-10 Thu 19:05-22:05>
:PROPERTIES:
:ID:       SXevzqV0Nnjc-SJ40_pQNH0E@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Missions vs. RoughRiders Missions vs. RoughRiders

Follow on MiLB First Pitch  https //stza.co/+wMwu-2k

Shop  https //stza.co/+wMwu-2s

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Missions vs. RoughRiders
END:VALARM
DTSTART:20180511T000500Z
DTEND:20180511T030500Z
UID:SXevzqV0Nnjc-SJ40_pQNH0E@stanza.co
SUMMARY:Missions vs. RoughRiders
DESCRIPTION:Missions vs. RoughRiders\n\nFollow on MiLB First Pitch: https://stza.co/+wMwu-2k\n\nShop: https://stza.co/+wMwu-2s\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144556Z
LAST-MODIFIED:20180213T144556Z
TRANSP:OPAQUE
END:VEVENT
* Missions vs. RoughRiders
<2018-05-11 Fri 19:05-22:05>
:PROPERTIES:
:ID:       VX6xgBnKBY_mjRl09P868Iwd@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Missions vs. RoughRiders Missions vs. RoughRiders

Follow on MiLB First Pitch  https //stza.co/+wMwy-2M

Shop  https //stza.co/+wMwy-3m

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Missions vs. RoughRiders
END:VALARM
DTSTART:20180512T000500Z
DTEND:20180512T030500Z
UID:VX6xgBnKBY_mjRl09P868Iwd@stanza.co
SUMMARY:Missions vs. RoughRiders
DESCRIPTION:Missions vs. RoughRiders\n\nFollow on MiLB First Pitch: https://stza.co/+wMwy-2M\n\nShop: https://stza.co/+wMwy-3m\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144556Z
LAST-MODIFIED:20180213T144556Z
TRANSP:OPAQUE
END:VEVENT
* Missions vs. RoughRiders
<2018-05-12 Sat 19:05-22:05>
:PROPERTIES:
:ID:       zvoDsFMXWaoIgm5rUzFjEi7o@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Missions vs. RoughRiders Missions vs. RoughRiders

Follow on MiLB First Pitch  https //stza.co/+wMwA-3S

Shop  https //stza.co/+wMwA-I

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Missions vs. RoughRiders
END:VALARM
DTSTART:20180513T000500Z
DTEND:20180513T030500Z
UID:zvoDsFMXWaoIgm5rUzFjEi7o@stanza.co
SUMMARY:Missions vs. RoughRiders
DESCRIPTION:Missions vs. RoughRiders\n\nFollow on MiLB First Pitch: https://stza.co/+wMwA-3S\n\nShop: https://stza.co/+wMwA-I\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144556Z
LAST-MODIFIED:20180213T144556Z
TRANSP:OPAQUE
END:VEVENT
* Missions vs. RoughRiders
<2018-05-13 Sun 14:05-17:05>
:PROPERTIES:
:ID:       54XzmBn9SDoWK8nCKmpzq80b@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Missions vs. RoughRiders Missions vs. RoughRiders

Follow on MiLB First Pitch  https //stza.co/+wMwB-2i

Shop  https //stza.co/+wMwB-2w

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Missions vs. RoughRiders
END:VALARM
DTSTART:20180513T190500Z
DTEND:20180513T220500Z
UID:54XzmBn9SDoWK8nCKmpzq80b@stanza.co
SUMMARY:Missions vs. RoughRiders
DESCRIPTION:Missions vs. RoughRiders\n\nFollow on MiLB First Pitch: https://stza.co/+wMwB-2i\n\nShop: https://stza.co/+wMwB-2w\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144556Z
LAST-MODIFIED:20180213T144556Z
TRANSP:OPAQUE
END:VEVENT
* Missions @ Hooks
<2018-05-14 Mon 19:05-22:05>
:PROPERTIES:
:ID:       wP2VY9y8av6xqHhvw2dga2_b@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Missions @ Hooks Missions @ Hooks

Follow on MiLB First Pitch  https //stza.co/+xzI9-y

Shop  https //stza.co/+xzI9-2s

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Missions @ Hooks
END:VALARM
DTSTART:20180515T000500Z
DTEND:20180515T030500Z
UID:wP2VY9y8av6xqHhvw2dga2_b@stanza.co
SUMMARY:Missions @ Hooks
DESCRIPTION:Missions @ Hooks\n\nFollow on MiLB First Pitch: https://stza.co/+xzI9-y\n\nShop: https://stza.co/+xzI9-2s\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144556Z
LAST-MODIFIED:20180213T144556Z
TRANSP:OPAQUE
END:VEVENT
* Missions @ Hooks
<2018-05-15 Tue 19:05-22:05>
:PROPERTIES:
:ID:       GFgGcc_LeHrRKs7yErNJunT7@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Missions @ Hooks Missions @ Hooks

Follow on MiLB First Pitch  https //stza.co/+xzIa-B

Shop  https //stza.co/+xzIa-P

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Missions @ Hooks
END:VALARM
DTSTART:20180516T000500Z
DTEND:20180516T030500Z
UID:GFgGcc_LeHrRKs7yErNJunT7@stanza.co
SUMMARY:Missions @ Hooks
DESCRIPTION:Missions @ Hooks\n\nFollow on MiLB First Pitch: https://stza.co/+xzIa-B\n\nShop: https://stza.co/+xzIa-P\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144556Z
LAST-MODIFIED:20180213T144556Z
TRANSP:OPAQUE
END:VEVENT
* Missions @ Hooks
<2018-05-16 Wed 19:05-22:05>
:PROPERTIES:
:ID:       DXrgEv8jV1g8VF8ltjy5gn4e@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Missions @ Hooks Missions @ Hooks

Follow on MiLB First Pitch  https //stza.co/+xzIb-1_

Shop  https //stza.co/+xzIb-2f

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Missions @ Hooks
END:VALARM
DTSTART:20180517T000500Z
DTEND:20180517T030500Z
UID:DXrgEv8jV1g8VF8ltjy5gn4e@stanza.co
SUMMARY:Missions @ Hooks
DESCRIPTION:Missions @ Hooks\n\nFollow on MiLB First Pitch: https://stza.co/+xzIb-1_\n\nShop: https://stza.co/+xzIb-2f\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144556Z
LAST-MODIFIED:20180213T144556Z
TRANSP:OPAQUE
END:VEVENT
* Missions @ Hooks
<2018-05-17 Thu 19:05-22:05>
:PROPERTIES:
:ID:       Jlks-nqiI6P7BL4Db4nH3q9Y@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Missions @ Hooks Missions @ Hooks

Follow on MiLB First Pitch  https //stza.co/+xzIc-3n

Shop  https //stza.co/+xzIc-1d

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Missions @ Hooks
END:VALARM
DTSTART:20180518T000500Z
DTEND:20180518T030500Z
UID:Jlks-nqiI6P7BL4Db4nH3q9Y@stanza.co
SUMMARY:Missions @ Hooks
DESCRIPTION:Missions @ Hooks\n\nFollow on MiLB First Pitch: https://stza.co/+xzIc-3n\n\nShop: https://stza.co/+xzIc-1d\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144556Z
LAST-MODIFIED:20180213T144556Z
TRANSP:OPAQUE
END:VEVENT
* Missions @ RockHounds
<2018-05-18 Fri 19:00-22:00>
:PROPERTIES:
:ID:       K2zRVaLBjsT1nrnliQmKyiqo@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Missions @ RockHounds Missions @ RockHounds

Follow on MiLB First Pitch  https //stza.co/+wX5j-1C

Shop  https //stza.co/+wX5j-1P

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Missions @ RockHounds
END:VALARM
DTSTART:20180519T000000Z
DTEND:20180519T030000Z
UID:K2zRVaLBjsT1nrnliQmKyiqo@stanza.co
SUMMARY:Missions @ RockHounds
DESCRIPTION:Missions @ RockHounds\n\nFollow on MiLB First Pitch: https://stza.co/+wX5j-1C\n\nShop: https://stza.co/+wX5j-1P\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144556Z
LAST-MODIFIED:20180213T144556Z
TRANSP:OPAQUE
END:VEVENT
* Missions @ RockHounds
<2018-05-19 Sat 19:00-22:00>
:PROPERTIES:
:ID:       hOMMKilrZycxe8G2pvYKKuV7@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Missions @ RockHounds Missions @ RockHounds

Follow on MiLB First Pitch  https //stza.co/+wX5k-3T

Shop  https //stza.co/+wX5k-3J

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Missions @ RockHounds
END:VALARM
DTSTART:20180520T000000Z
DTEND:20180520T030000Z
UID:hOMMKilrZycxe8G2pvYKKuV7@stanza.co
SUMMARY:Missions @ RockHounds
DESCRIPTION:Missions @ RockHounds\n\nFollow on MiLB First Pitch: https://stza.co/+wX5k-3T\n\nShop: https://stza.co/+wX5k-3J\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144556Z
LAST-MODIFIED:20180213T144556Z
TRANSP:OPAQUE
END:VEVENT
* Missions @ RockHounds
<2018-05-20 Sun 14:00-17:00>
:PROPERTIES:
:ID:       ZGUJnxlC8mbHLcNcfNiSAfwk@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Missions @ RockHounds Missions @ RockHounds

Follow on MiLB First Pitch  https //stza.co/+wX5l-1V

Shop  https //stza.co/+wX5l-19

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Missions @ RockHounds
END:VALARM
DTSTART:20180520T190000Z
DTEND:20180520T220000Z
UID:ZGUJnxlC8mbHLcNcfNiSAfwk@stanza.co
SUMMARY:Missions @ RockHounds
DESCRIPTION:Missions @ RockHounds\n\nFollow on MiLB First Pitch: https://stza.co/+wX5l-1V\n\nShop: https://stza.co/+wX5l-19\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144556Z
LAST-MODIFIED:20180213T144556Z
TRANSP:OPAQUE
END:VEVENT
* Missions @ RockHounds
<2018-05-21 Mon 11:00-14:00>
:PROPERTIES:
:ID:       6Vjtjdn_keUoDBHlhKPsiN-O@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Missions @ RockHounds Missions @ RockHounds

Follow on MiLB First Pitch  https //stza.co/+wX5m-1a

Shop  https //stza.co/+wX5m-1X

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Missions @ RockHounds
END:VALARM
DTSTART:20180521T160000Z
DTEND:20180521T190000Z
UID:6Vjtjdn_keUoDBHlhKPsiN-O@stanza.co
SUMMARY:Missions @ RockHounds
DESCRIPTION:Missions @ RockHounds\n\nFollow on MiLB First Pitch: https://stza.co/+wX5m-1a\n\nShop: https://stza.co/+wX5m-1X\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144556Z
LAST-MODIFIED:20180213T144556Z
TRANSP:OPAQUE
END:VEVENT
* Missions vs. Drillers
<2018-05-22 Tue 19:05-22:05>
:PROPERTIES:
:ID:       P1dI_o3dxXZRIEptjwGWIxBc@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Missions vs. Drillers Missions vs. Drillers

Follow on MiLB First Pitch  https //stza.co/+wMwE-16

Shop  https //stza.co/+wMwE-2M

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Missions vs. Drillers
END:VALARM
DTSTART:20180523T000500Z
DTEND:20180523T030500Z
UID:P1dI_o3dxXZRIEptjwGWIxBc@stanza.co
SUMMARY:Missions vs. Drillers
DESCRIPTION:Missions vs. Drillers\n\nFollow on MiLB First Pitch: https://stza.co/+wMwE-16\n\nShop: https://stza.co/+wMwE-2M\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144556Z
LAST-MODIFIED:20180213T144556Z
TRANSP:OPAQUE
END:VEVENT
* Missions vs. Drillers
<2018-05-23 Wed 19:05-22:05>
:PROPERTIES:
:ID:       zfu5q8N0l9u1euRNxrUsfez1@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Missions vs. Drillers Missions vs. Drillers

Follow on MiLB First Pitch  https //stza.co/+wMwF-R

Shop  https //stza.co/+wMwF-t

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Missions vs. Drillers
END:VALARM
DTSTART:20180524T000500Z
DTEND:20180524T030500Z
UID:zfu5q8N0l9u1euRNxrUsfez1@stanza.co
SUMMARY:Missions vs. Drillers
DESCRIPTION:Missions vs. Drillers\n\nFollow on MiLB First Pitch: https://stza.co/+wMwF-R\n\nShop: https://stza.co/+wMwF-t\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144556Z
LAST-MODIFIED:20180213T144556Z
TRANSP:OPAQUE
END:VEVENT
* Missions vs. Drillers
<2018-05-24 Thu 19:05-22:05>
:PROPERTIES:
:ID:       H_cE42fHEMPbkFGTquq9PXVH@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Missions vs. Drillers Missions vs. Drillers

Follow on MiLB First Pitch  https //stza.co/+wMwI-3o

Shop  https //stza.co/+wMwI-3V

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Missions vs. Drillers
END:VALARM
DTSTART:20180525T000500Z
DTEND:20180525T030500Z
UID:H_cE42fHEMPbkFGTquq9PXVH@stanza.co
SUMMARY:Missions vs. Drillers
DESCRIPTION:Missions vs. Drillers\n\nFollow on MiLB First Pitch: https://stza.co/+wMwI-3o\n\nShop: https://stza.co/+wMwI-3V\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144556Z
LAST-MODIFIED:20180213T144556Z
TRANSP:OPAQUE
END:VEVENT
* Missions vs. Cardinals
<2018-05-25 Fri 19:05-22:05>
:PROPERTIES:
:ID:       MNzY_ZPCixpIJ9OEi_oEes31@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Missions vs. Cardinals Missions vs. Cardinals

Follow on MiLB First Pitch  https //stza.co/+wMwJ-34

Shop  https //stza.co/+wMwJ-1B

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Missions vs. Cardinals
END:VALARM
DTSTART:20180526T000500Z
DTEND:20180526T030500Z
UID:MNzY_ZPCixpIJ9OEi_oEes31@stanza.co
SUMMARY:Missions vs. Cardinals
DESCRIPTION:Missions vs. Cardinals\n\nFollow on MiLB First Pitch: https://stza.co/+wMwJ-34\n\nShop: https://stza.co/+wMwJ-1B\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144556Z
LAST-MODIFIED:20180213T144556Z
TRANSP:OPAQUE
END:VEVENT
* Missions vs. Cardinals
<2018-05-26 Sat 19:05-22:05>
:PROPERTIES:
:ID:       YvPsJKqQ2eXEcUVI9c3AwFcZ@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Missions vs. Cardinals Missions vs. Cardinals

Follow on MiLB First Pitch  https //stza.co/+wMwL-1s

Shop  https //stza.co/+wMwL-2u

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Missions vs. Cardinals
END:VALARM
DTSTART:20180527T000500Z
DTEND:20180527T030500Z
UID:YvPsJKqQ2eXEcUVI9c3AwFcZ@stanza.co
SUMMARY:Missions vs. Cardinals
DESCRIPTION:Missions vs. Cardinals\n\nFollow on MiLB First Pitch: https://stza.co/+wMwL-1s\n\nShop: https://stza.co/+wMwL-2u\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144556Z
LAST-MODIFIED:20180213T144556Z
TRANSP:OPAQUE
END:VEVENT
* Missions vs. Cardinals
<2018-05-27 Sun 17:05-20:05>
:PROPERTIES:
:ID:       Swg9wKK3EZiHhjGx3xCsgCEA@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Missions vs. Cardinals Missions vs. Cardinals

Follow on MiLB First Pitch  https //stza.co/+wMwO-3_

Shop  https //stza.co/+wMwO-20

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Missions vs. Cardinals
END:VALARM
DTSTART:20180527T220500Z
DTEND:20180528T010500Z
UID:Swg9wKK3EZiHhjGx3xCsgCEA@stanza.co
SUMMARY:Missions vs. Cardinals
DESCRIPTION:Missions vs. Cardinals\n\nFollow on MiLB First Pitch: https://stza.co/+wMwO-3_\n\nShop: https://stza.co/+wMwO-20\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144556Z
LAST-MODIFIED:20180213T144556Z
TRANSP:OPAQUE
END:VEVENT
* Missions @ Drillers
<2018-05-29 Tue 19:05-22:05>
:PROPERTIES:
:ID:       V1QwJ7diiihMqEzexVXY0PKp@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Missions @ Drillers Missions @ Drillers

Follow on MiLB First Pitch  https //stza.co/+w0ac-32

Shop  https //stza.co/+w0ac-30

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Missions @ Drillers
END:VALARM
DTSTART:20180530T000500Z
DTEND:20180530T030500Z
UID:V1QwJ7diiihMqEzexVXY0PKp@stanza.co
SUMMARY:Missions @ Drillers
DESCRIPTION:Missions @ Drillers\n\nFollow on MiLB First Pitch: https://stza.co/+w0ac-32\n\nShop: https://stza.co/+w0ac-30\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144556Z
LAST-MODIFIED:20180213T144556Z
TRANSP:OPAQUE
END:VEVENT
* Missions @ Drillers
<2018-05-30 Wed 19:05-22:05>
:PROPERTIES:
:ID:       VBNidgH9Net8pOYqGtIR_4KF@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Missions @ Drillers Missions @ Drillers

Follow on MiLB First Pitch  https //stza.co/+w0ad-3M

Shop  https //stza.co/+w0ad-1p

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Missions @ Drillers
END:VALARM
DTSTART:20180531T000500Z
DTEND:20180531T030500Z
UID:VBNidgH9Net8pOYqGtIR_4KF@stanza.co
SUMMARY:Missions @ Drillers
DESCRIPTION:Missions @ Drillers\n\nFollow on MiLB First Pitch: https://stza.co/+w0ad-3M\n\nShop: https://stza.co/+w0ad-1p\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144556Z
LAST-MODIFIED:20180213T144556Z
TRANSP:OPAQUE
END:VEVENT
* Missions @ Drillers
<2018-05-31 Thu 19:05-22:05>
:PROPERTIES:
:ID:       P3Yup_QdhZUqeiwcqaBwdkje@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Missions @ Drillers Missions @ Drillers

Follow on MiLB First Pitch  https //stza.co/+w0ae-1I

Shop  https //stza.co/+w0ae-1U

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Missions @ Drillers
END:VALARM
DTSTART:20180601T000500Z
DTEND:20180601T030500Z
UID:P3Yup_QdhZUqeiwcqaBwdkje@stanza.co
SUMMARY:Missions @ Drillers
DESCRIPTION:Missions @ Drillers\n\nFollow on MiLB First Pitch: https://stza.co/+w0ae-1I\n\nShop: https://stza.co/+w0ae-1U\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144556Z
LAST-MODIFIED:20180213T144556Z
TRANSP:OPAQUE
END:VEVENT
* Missions @ Cardinals
<2018-06-01 Fri 19:10-22:10>
:PROPERTIES:
:ID:       KXS88mKYtqgO0U1Cd1rDlqfU@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Missions @ Cardinals Missions @ Cardinals

Follow on MiLB First Pitch  https //stza.co/+wPNO-1l

Shop  https //stza.co/+wPNO-3U

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Missions @ Cardinals
END:VALARM
DTSTART:20180602T001000Z
DTEND:20180602T031000Z
UID:KXS88mKYtqgO0U1Cd1rDlqfU@stanza.co
SUMMARY:Missions @ Cardinals
DESCRIPTION:Missions @ Cardinals\n\nFollow on MiLB First Pitch: https://stza.co/+wPNO-1l\n\nShop: https://stza.co/+wPNO-3U\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144556Z
LAST-MODIFIED:20180213T144556Z
TRANSP:OPAQUE
END:VEVENT
* Missions @ Cardinals
<2018-06-02 Sat 18:10-21:10>
:PROPERTIES:
:ID:       0N7k2cpof16pY8mPV8tIdd5A@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Missions @ Cardinals Missions @ Cardinals

Follow on MiLB First Pitch  https //stza.co/+wPNP-1$

Shop  https //stza.co/+wPNP-1O

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Missions @ Cardinals
END:VALARM
DTSTART:20180602T231000Z
DTEND:20180603T021000Z
UID:0N7k2cpof16pY8mPV8tIdd5A@stanza.co
SUMMARY:Missions @ Cardinals
DESCRIPTION:Missions @ Cardinals\n\nFollow on MiLB First Pitch: https://stza.co/+wPNP-1$\n\nShop: https://stza.co/+wPNP-1O\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144556Z
LAST-MODIFIED:20180213T144556Z
TRANSP:OPAQUE
END:VEVENT
* Missions @ Cardinals
<2018-06-03 Sun 18:10-21:10>
:PROPERTIES:
:ID:       JzppnpybLP9Z6Yu0X4kyjCLJ@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Missions @ Cardinals Missions @ Cardinals

Follow on MiLB First Pitch  https //stza.co/+wPNQ-3L

Shop  https //stza.co/+wPNQ-9

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Missions @ Cardinals
END:VALARM
DTSTART:20180603T231000Z
DTEND:20180604T021000Z
UID:JzppnpybLP9Z6Yu0X4kyjCLJ@stanza.co
SUMMARY:Missions @ Cardinals
DESCRIPTION:Missions @ Cardinals\n\nFollow on MiLB First Pitch: https://stza.co/+wPNQ-3L\n\nShop: https://stza.co/+wPNQ-9\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144556Z
LAST-MODIFIED:20180213T144556Z
TRANSP:OPAQUE
END:VEVENT
* Missions vs. RockHounds
<2018-06-05 Tue 19:05-22:05>
:PROPERTIES:
:ID:       NRhYgXr9GUbYaQavlorlABBS@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Missions vs. RockHounds Missions vs. RockHounds

Follow on MiLB First Pitch  https //stza.co/+wMwQ-3M

Shop  https //stza.co/+wMwQ-1t

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Missions vs. RockHounds
END:VALARM
DTSTART:20180606T000500Z
DTEND:20180606T030500Z
UID:NRhYgXr9GUbYaQavlorlABBS@stanza.co
SUMMARY:Missions vs. RockHounds
DESCRIPTION:Missions vs. RockHounds\n\nFollow on MiLB First Pitch: https://stza.co/+wMwQ-3M\n\nShop: https://stza.co/+wMwQ-1t\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144556Z
LAST-MODIFIED:20180213T144556Z
TRANSP:OPAQUE
END:VEVENT
* Missions vs. RockHounds
<2018-06-06 Wed 19:05-22:05>
:PROPERTIES:
:ID:       IUravDdA-ce2pk-lf0X05lZg@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Missions vs. RockHounds Missions vs. RockHounds

Follow on MiLB First Pitch  https //stza.co/+wMwS-3v

Shop  https //stza.co/+wMwS-2i

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Missions vs. RockHounds
END:VALARM
DTSTART:20180607T000500Z
DTEND:20180607T030500Z
UID:IUravDdA-ce2pk-lf0X05lZg@stanza.co
SUMMARY:Missions vs. RockHounds
DESCRIPTION:Missions vs. RockHounds\n\nFollow on MiLB First Pitch: https://stza.co/+wMwS-3v\n\nShop: https://stza.co/+wMwS-2i\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144556Z
LAST-MODIFIED:20180213T144556Z
TRANSP:OPAQUE
END:VEVENT
* Missions vs. RockHounds
<2018-06-07 Thu 19:05-22:05>
:PROPERTIES:
:ID:       zml_YTEoSlTeiuQIFWSaTIAy@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Missions vs. RockHounds Missions vs. RockHounds

Follow on MiLB First Pitch  https //stza.co/+wMwT-v

Shop  https //stza.co/+wMwT-2w

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Missions vs. RockHounds
END:VALARM
DTSTART:20180608T000500Z
DTEND:20180608T030500Z
UID:zml_YTEoSlTeiuQIFWSaTIAy@stanza.co
SUMMARY:Missions vs. RockHounds
DESCRIPTION:Missions vs. RockHounds\n\nFollow on MiLB First Pitch: https://stza.co/+wMwT-v\n\nShop: https://stza.co/+wMwT-2w\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144556Z
LAST-MODIFIED:20180213T144556Z
TRANSP:OPAQUE
END:VEVENT
* Missions vs. RockHounds
<2018-06-08 Fri 19:05-22:05>
:PROPERTIES:
:ID:       jsJJmlSIqkbrYZQZBPQPQA2c@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Missions vs. RockHounds Missions vs. RockHounds

Follow on MiLB First Pitch  https //stza.co/+wMwV-2O

Shop  https //stza.co/+wMwV-N

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Missions vs. RockHounds
END:VALARM
DTSTART:20180609T000500Z
DTEND:20180609T030500Z
UID:jsJJmlSIqkbrYZQZBPQPQA2c@stanza.co
SUMMARY:Missions vs. RockHounds
DESCRIPTION:Missions vs. RockHounds\n\nFollow on MiLB First Pitch: https://stza.co/+wMwV-2O\n\nShop: https://stza.co/+wMwV-N\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144556Z
LAST-MODIFIED:20180213T144556Z
TRANSP:OPAQUE
END:VEVENT
* Missions @ Hooks
<2018-06-09 Sat 19:05-22:05>
:PROPERTIES:
:ID:       ic4jm2qAN4OkdE_DfTE9hnUJ@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Missions @ Hooks Missions @ Hooks

Follow on MiLB First Pitch  https //stza.co/+xzId-z

Shop  https //stza.co/+xzId-4

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Missions @ Hooks
END:VALARM
DTSTART:20180610T000500Z
DTEND:20180610T030500Z
UID:ic4jm2qAN4OkdE_DfTE9hnUJ@stanza.co
SUMMARY:Missions @ Hooks
DESCRIPTION:Missions @ Hooks\n\nFollow on MiLB First Pitch: https://stza.co/+xzId-z\n\nShop: https://stza.co/+xzId-4\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144556Z
LAST-MODIFIED:20180213T144556Z
TRANSP:OPAQUE
END:VEVENT
* Missions @ Hooks
<2018-06-10 Sun 18:05-21:05>
:PROPERTIES:
:ID:       uqXZAm2cKRWHzUPVaUyvayp_@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Missions @ Hooks Missions @ Hooks

Follow on MiLB First Pitch  https //stza.co/+xzIe-c

Shop  https //stza.co/+xzIe-3J

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Missions @ Hooks
END:VALARM
DTSTART:20180610T230500Z
DTEND:20180611T020500Z
UID:uqXZAm2cKRWHzUPVaUyvayp_@stanza.co
SUMMARY:Missions @ Hooks
DESCRIPTION:Missions @ Hooks\n\nFollow on MiLB First Pitch: https://stza.co/+xzIe-c\n\nShop: https://stza.co/+xzIe-3J\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144556Z
LAST-MODIFIED:20180213T144556Z
TRANSP:OPAQUE
END:VEVENT
* Missions @ Hooks
<2018-06-11 Mon 19:05-22:05>
:PROPERTIES:
:ID:       t-ov4LmvtTW5MiT6k9Z_5C_p@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Missions @ Hooks Missions @ Hooks

Follow on MiLB First Pitch  https //stza.co/+xzIf-1d

Shop  https //stza.co/+xzIf-C

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Missions @ Hooks
END:VALARM
DTSTART:20180612T000500Z
DTEND:20180612T030500Z
UID:t-ov4LmvtTW5MiT6k9Z_5C_p@stanza.co
SUMMARY:Missions @ Hooks
DESCRIPTION:Missions @ Hooks\n\nFollow on MiLB First Pitch: https://stza.co/+xzIf-1d\n\nShop: https://stza.co/+xzIf-C\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144556Z
LAST-MODIFIED:20180213T144556Z
TRANSP:OPAQUE
END:VEVENT
* Missions @ Hooks
<2018-06-12 Tue 19:05-22:05>
:PROPERTIES:
:ID:       fe-_SVhYo8S1Chrshtuh8kj4@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Missions @ Hooks Missions @ Hooks

Follow on MiLB First Pitch  https //stza.co/+xzIg-2n

Shop  https //stza.co/+xzIg-1

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Missions @ Hooks
END:VALARM
DTSTART:20180613T000500Z
DTEND:20180613T030500Z
UID:fe-_SVhYo8S1Chrshtuh8kj4@stanza.co
SUMMARY:Missions @ Hooks
DESCRIPTION:Missions @ Hooks\n\nFollow on MiLB First Pitch: https://stza.co/+xzIg-2n\n\nShop: https://stza.co/+xzIg-1\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144556Z
LAST-MODIFIED:20180213T144556Z
TRANSP:OPAQUE
END:VEVENT
* Missions @ RoughRiders
<2018-06-13 Wed 19:05-22:05>
:PROPERTIES:
:ID:       zTyEd6tNZ0CSqEW4FohYCEqu@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Missions @ RoughRiders Missions @ RoughRiders

Follow on MiLB First Pitch  https //stza.co/+wYbS-p

Shop  https //stza.co/+wYbS-1w

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Missions @ RoughRiders
END:VALARM
DTSTART:20180614T000500Z
DTEND:20180614T030500Z
UID:zTyEd6tNZ0CSqEW4FohYCEqu@stanza.co
SUMMARY:Missions @ RoughRiders
DESCRIPTION:Missions @ RoughRiders\n\nFollow on MiLB First Pitch: https://stza.co/+wYbS-p\n\nShop: https://stza.co/+wYbS-1w\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144556Z
LAST-MODIFIED:20180213T144556Z
TRANSP:OPAQUE
END:VEVENT
* Missions @ RoughRiders
<2018-06-14 Thu 19:05-22:05>
:PROPERTIES:
:ID:       Q0bm_mYWSg9L1XOirbfZWRWa@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Missions @ RoughRiders Missions @ RoughRiders

Follow on MiLB First Pitch  https //stza.co/+wYbU-I

Shop  https //stza.co/+wYbU-5

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Missions @ RoughRiders
END:VALARM
DTSTART:20180615T000500Z
DTEND:20180615T030500Z
UID:Q0bm_mYWSg9L1XOirbfZWRWa@stanza.co
SUMMARY:Missions @ RoughRiders
DESCRIPTION:Missions @ RoughRiders\n\nFollow on MiLB First Pitch: https://stza.co/+wYbU-I\n\nShop: https://stza.co/+wYbU-5\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144556Z
LAST-MODIFIED:20180213T144556Z
TRANSP:OPAQUE
END:VEVENT
* Missions @ RoughRiders
<2018-06-15 Fri 19:05-22:05>
:PROPERTIES:
:ID:       5obIULnbaDFIL8FtOTRNEQpF@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Missions @ RoughRiders Missions @ RoughRiders

Follow on MiLB First Pitch  https //stza.co/+wYbV-2q

Shop  https //stza.co/+wYbV-1v

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Missions @ RoughRiders
END:VALARM
DTSTART:20180616T000500Z
DTEND:20180616T030500Z
UID:5obIULnbaDFIL8FtOTRNEQpF@stanza.co
SUMMARY:Missions @ RoughRiders
DESCRIPTION:Missions @ RoughRiders\n\nFollow on MiLB First Pitch: https://stza.co/+wYbV-2q\n\nShop: https://stza.co/+wYbV-1v\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144556Z
LAST-MODIFIED:20180213T144556Z
TRANSP:OPAQUE
END:VEVENT
* Missions @ RoughRiders
<2018-06-16 Sat 19:05-22:05>
:PROPERTIES:
:ID:       vAu3isDjmnpbFnMqiUKGnCLy@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Missions @ RoughRiders Missions @ RoughRiders

Follow on MiLB First Pitch  https //stza.co/+wYbX-2N

Shop  https //stza.co/+wYbX-3i

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Missions @ RoughRiders
END:VALARM
DTSTART:20180617T000500Z
DTEND:20180617T030500Z
UID:vAu3isDjmnpbFnMqiUKGnCLy@stanza.co
SUMMARY:Missions @ RoughRiders
DESCRIPTION:Missions @ RoughRiders\n\nFollow on MiLB First Pitch: https://stza.co/+wYbX-2N\n\nShop: https://stza.co/+wYbX-3i\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144556Z
LAST-MODIFIED:20180213T144556Z
TRANSP:OPAQUE
END:VEVENT
* Missions vs. Hooks
<2018-06-17 Sun 16:05-19:05>
:PROPERTIES:
:ID:       qk5m-Ap2XQh61Udivxe2Y4kD@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Missions vs. Hooks Missions vs. Hooks

Follow on MiLB First Pitch  https //stza.co/+wMwZ-20

Shop  https //stza.co/+wMwZ-b

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Missions vs. Hooks
END:VALARM
DTSTART:20180617T210500Z
DTEND:20180618T000500Z
UID:qk5m-Ap2XQh61Udivxe2Y4kD@stanza.co
SUMMARY:Missions vs. Hooks
DESCRIPTION:Missions vs. Hooks\n\nFollow on MiLB First Pitch: https://stza.co/+wMwZ-20\n\nShop: https://stza.co/+wMwZ-b\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144556Z
LAST-MODIFIED:20180213T144556Z
TRANSP:OPAQUE
END:VEVENT
* Missions vs. Hooks
<2018-06-18 Mon 19:05-22:05>
:PROPERTIES:
:ID:       rrZFZX0IgsaDiiOPd8GYVkea@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Missions vs. Hooks Missions vs. Hooks

Follow on MiLB First Pitch  https //stza.co/+wMx0-1Y

Shop  https //stza.co/+wMx0-2T

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Missions vs. Hooks
END:VALARM
DTSTART:20180619T000500Z
DTEND:20180619T030500Z
UID:rrZFZX0IgsaDiiOPd8GYVkea@stanza.co
SUMMARY:Missions vs. Hooks
DESCRIPTION:Missions vs. Hooks\n\nFollow on MiLB First Pitch: https://stza.co/+wMx0-1Y\n\nShop: https://stza.co/+wMx0-2T\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144556Z
LAST-MODIFIED:20180213T144556Z
TRANSP:OPAQUE
END:VEVENT
* Missions vs. Hooks
<2018-06-19 Tue 19:05-22:05>
:PROPERTIES:
:ID:       MGF2eb-TgK578unTYmqc50I3@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Missions vs. Hooks Missions vs. Hooks

Follow on MiLB First Pitch  https //stza.co/+wMx1-6

Shop  https //stza.co/+wMx1-P

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Missions vs. Hooks
END:VALARM
DTSTART:20180620T000500Z
DTEND:20180620T030500Z
UID:MGF2eb-TgK578unTYmqc50I3@stanza.co
SUMMARY:Missions vs. Hooks
DESCRIPTION:Missions vs. Hooks\n\nFollow on MiLB First Pitch: https://stza.co/+wMx1-6\n\nShop: https://stza.co/+wMx1-P\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144556Z
LAST-MODIFIED:20180213T144556Z
TRANSP:OPAQUE
END:VEVENT
* Missions vs. Hooks
<2018-06-20 Wed 19:05-22:05>
:PROPERTIES:
:ID:       y80YOHUhEDxQkVVl4iOGjEon@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Missions vs. Hooks Missions vs. Hooks

Follow on MiLB First Pitch  https //stza.co/+wMx3-3j

Shop  https //stza.co/+wMx3-3f

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Missions vs. Hooks
END:VALARM
DTSTART:20180621T000500Z
DTEND:20180621T030500Z
UID:y80YOHUhEDxQkVVl4iOGjEon@stanza.co
SUMMARY:Missions vs. Hooks
DESCRIPTION:Missions vs. Hooks\n\nFollow on MiLB First Pitch: https://stza.co/+wMx3-3j\n\nShop: https://stza.co/+wMx3-3f\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144556Z
LAST-MODIFIED:20180213T144556Z
TRANSP:OPAQUE
END:VEVENT
* Missions vs. RockHounds
<2018-06-21 Thu 19:05-22:05>
:PROPERTIES:
:ID:       PXHNygPHdm78SOTJ6IUGPb-H@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Missions vs. RockHounds Missions vs. RockHounds

Follow on MiLB First Pitch  https //stza.co/+wMx5-1X

Shop  https //stza.co/+wMx5-3C

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Missions vs. RockHounds
END:VALARM
DTSTART:20180622T000500Z
DTEND:20180622T030500Z
UID:PXHNygPHdm78SOTJ6IUGPb-H@stanza.co
SUMMARY:Missions vs. RockHounds
DESCRIPTION:Missions vs. RockHounds\n\nFollow on MiLB First Pitch: https://stza.co/+wMx5-1X\n\nShop: https://stza.co/+wMx5-3C\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144556Z
LAST-MODIFIED:20180213T144556Z
TRANSP:OPAQUE
END:VEVENT
* Missions vs. RockHounds
<2018-06-22 Fri 19:05-22:05>
:PROPERTIES:
:ID:       MKYfbKT-4LjIHTC7St6CL81s@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Missions vs. RockHounds Missions vs. RockHounds

Follow on MiLB First Pitch  https //stza.co/+wMx8-2Z

Shop  https //stza.co/+wMx8-1m

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Missions vs. RockHounds
END:VALARM
DTSTART:20180623T000500Z
DTEND:20180623T030500Z
UID:MKYfbKT-4LjIHTC7St6CL81s@stanza.co
SUMMARY:Missions vs. RockHounds
DESCRIPTION:Missions vs. RockHounds\n\nFollow on MiLB First Pitch: https://stza.co/+wMx8-2Z\n\nShop: https://stza.co/+wMx8-1m\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144556Z
LAST-MODIFIED:20180213T144556Z
TRANSP:OPAQUE
END:VEVENT
* Missions vs. RockHounds
<2018-06-23 Sat 19:05-22:05>
:PROPERTIES:
:ID:       hgtKPYz5N2Dv4-T2E9600sDr@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Missions vs. RockHounds Missions vs. RockHounds

Follow on MiLB First Pitch  https //stza.co/+wMxa-3S

Shop  https //stza.co/+wMxa-2

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Missions vs. RockHounds
END:VALARM
DTSTART:20180624T000500Z
DTEND:20180624T030500Z
UID:hgtKPYz5N2Dv4-T2E9600sDr@stanza.co
SUMMARY:Missions vs. RockHounds
DESCRIPTION:Missions vs. RockHounds\n\nFollow on MiLB First Pitch: https://stza.co/+wMxa-3S\n\nShop: https://stza.co/+wMxa-2\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144556Z
LAST-MODIFIED:20180213T144556Z
TRANSP:OPAQUE
END:VEVENT
* Missions vs. RockHounds
<2018-06-24 Sun 19:05-22:05>
:PROPERTIES:
:ID:       U1vKIxMRb8VvN0wDk_31vglf@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Missions vs. RockHounds Missions vs. RockHounds

Follow on MiLB First Pitch  https //stza.co/+wMxc-1q

Shop  https //stza.co/+wMxc-1j

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Missions vs. RockHounds
END:VALARM
DTSTART:20180625T000500Z
DTEND:20180625T030500Z
UID:U1vKIxMRb8VvN0wDk_31vglf@stanza.co
SUMMARY:Missions vs. RockHounds
DESCRIPTION:Missions vs. RockHounds\n\nFollow on MiLB First Pitch: https://stza.co/+wMxc-1q\n\nShop: https://stza.co/+wMxc-1j\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144556Z
LAST-MODIFIED:20180213T144556Z
TRANSP:OPAQUE
END:VEVENT
* Missions @ Naturals
<2018-06-28 Thu 19:05-22:05>
:PROPERTIES:
:ID:       OkYrTMtTuQtloaMsr9kS8irP@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Missions @ Naturals Missions @ Naturals

Follow on MiLB First Pitch  https //stza.co/+wi3w-2h

Shop  https //stza.co/+wi3w-2x

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Missions @ Naturals
END:VALARM
DTSTART:20180629T000500Z
DTEND:20180629T030500Z
UID:OkYrTMtTuQtloaMsr9kS8irP@stanza.co
SUMMARY:Missions @ Naturals
DESCRIPTION:Missions @ Naturals\n\nFollow on MiLB First Pitch: https://stza.co/+wi3w-2h\n\nShop: https://stza.co/+wi3w-2x\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144556Z
LAST-MODIFIED:20180213T144556Z
TRANSP:OPAQUE
END:VEVENT
* Missions @ Naturals
<2018-06-29 Fri 19:05-22:05>
:PROPERTIES:
:ID:       RNmSUpAQsu3LS8Wh7W6ATalR@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Missions @ Naturals Missions @ Naturals

Follow on MiLB First Pitch  https //stza.co/+wi3y-1

Shop  https //stza.co/+wi3y-1s

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Missions @ Naturals
END:VALARM
DTSTART:20180630T000500Z
DTEND:20180630T030500Z
UID:RNmSUpAQsu3LS8Wh7W6ATalR@stanza.co
SUMMARY:Missions @ Naturals
DESCRIPTION:Missions @ Naturals\n\nFollow on MiLB First Pitch: https://stza.co/+wi3y-1\n\nShop: https://stza.co/+wi3y-1s\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144556Z
LAST-MODIFIED:20180213T144556Z
TRANSP:OPAQUE
END:VEVENT
* Missions @ Naturals
<2018-06-30 Sat 18:05-21:05>
:PROPERTIES:
:ID:       OumjSrti3wqiiCFSJwziv6dO@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Missions @ Naturals Missions @ Naturals

Follow on MiLB First Pitch  https //stza.co/+wi3z-2C

Shop  https //stza.co/+wi3z-23

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Missions @ Naturals
END:VALARM
DTSTART:20180630T230500Z
DTEND:20180701T020500Z
UID:OumjSrti3wqiiCFSJwziv6dO@stanza.co
SUMMARY:Missions @ Naturals
DESCRIPTION:Missions @ Naturals\n\nFollow on MiLB First Pitch: https://stza.co/+wi3z-2C\n\nShop: https://stza.co/+wi3z-23\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144556Z
LAST-MODIFIED:20180213T144556Z
TRANSP:OPAQUE
END:VEVENT
* Missions @ Travelers
<2018-07-01 Sun 14:10-17:10>
:PROPERTIES:
:ID:       xhSD1jLuN36EZQ5Kuzbfq0YT@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Missions @ Travelers Missions @ Travelers

Follow on MiLB First Pitch  https //stza.co/+xzI7-1G

Shop  https //stza.co/+xzI7-1X

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Missions @ Travelers
END:VALARM
DTSTART:20180701T191000Z
DTEND:20180701T221000Z
UID:xhSD1jLuN36EZQ5Kuzbfq0YT@stanza.co
SUMMARY:Missions @ Travelers
DESCRIPTION:Missions @ Travelers\n\nFollow on MiLB First Pitch: https://stza.co/+xzI7-1G\n\nShop: https://stza.co/+xzI7-1X\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144556Z
LAST-MODIFIED:20180213T144556Z
TRANSP:OPAQUE
END:VEVENT
* Missions @ Travelers
<2018-07-02 Mon 19:10-22:10>
:PROPERTIES:
:ID:       WPVeh_u79FtuwKiJ54tYY8vH@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Missions @ Travelers Missions @ Travelers

Follow on MiLB First Pitch  https //stza.co/+w074-3Z

Shop  https //stza.co/+w074-2c

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Missions @ Travelers
END:VALARM
DTSTART:20180703T001000Z
DTEND:20180703T031000Z
UID:WPVeh_u79FtuwKiJ54tYY8vH@stanza.co
SUMMARY:Missions @ Travelers
DESCRIPTION:Missions @ Travelers\n\nFollow on MiLB First Pitch: https://stza.co/+w074-3Z\n\nShop: https://stza.co/+w074-2c\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144556Z
LAST-MODIFIED:20180213T144556Z
TRANSP:OPAQUE
END:VEVENT
* Missions @ Travelers
<2018-07-03 Tue 18:10-21:10>
:PROPERTIES:
:ID:       V9HWmfNnUkiyaf4zXMma-u3A@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Missions @ Travelers Missions @ Travelers

Follow on MiLB First Pitch  https //stza.co/+xzI8-36

Shop  https //stza.co/+xzI8-2N

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Missions @ Travelers
END:VALARM
DTSTART:20180703T231000Z
DTEND:20180704T021000Z
UID:V9HWmfNnUkiyaf4zXMma-u3A@stanza.co
SUMMARY:Missions @ Travelers
DESCRIPTION:Missions @ Travelers\n\nFollow on MiLB First Pitch: https://stza.co/+xzI8-36\n\nShop: https://stza.co/+xzI8-2N\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144556Z
LAST-MODIFIED:20180213T144556Z
TRANSP:OPAQUE
END:VEVENT
* Missions vs. Naturals
<2018-07-04 Wed 17:05-20:05>
:PROPERTIES:
:ID:       dpsuAg3m4hGZ2MYCxeD4YYzY@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Missions vs. Naturals Missions vs. Naturals

Follow on MiLB First Pitch  https //stza.co/+wMxe-2A

Shop  https //stza.co/+wMxe-1R

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Missions vs. Naturals
END:VALARM
DTSTART:20180704T220500Z
DTEND:20180705T010500Z
UID:dpsuAg3m4hGZ2MYCxeD4YYzY@stanza.co
SUMMARY:Missions vs. Naturals
DESCRIPTION:Missions vs. Naturals\n\nFollow on MiLB First Pitch: https://stza.co/+wMxe-2A\n\nShop: https://stza.co/+wMxe-1R\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144556Z
LAST-MODIFIED:20180213T144556Z
TRANSP:OPAQUE
END:VEVENT
* Missions vs. Naturals
<2018-07-05 Thu 19:05-22:05>
:PROPERTIES:
:ID:       lFW0pA_XV10XV_oxLgYDciym@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Missions vs. Naturals Missions vs. Naturals

Follow on MiLB First Pitch  https //stza.co/+wMxf-3O

Shop  https //stza.co/+wMxf-2c

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Missions vs. Naturals
END:VALARM
DTSTART:20180706T000500Z
DTEND:20180706T030500Z
UID:lFW0pA_XV10XV_oxLgYDciym@stanza.co
SUMMARY:Missions vs. Naturals
DESCRIPTION:Missions vs. Naturals\n\nFollow on MiLB First Pitch: https://stza.co/+wMxf-3O\n\nShop: https://stza.co/+wMxf-2c\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144556Z
LAST-MODIFIED:20180213T144556Z
TRANSP:OPAQUE
END:VEVENT
* Missions vs. Naturals
<2018-07-06 Fri 19:05-22:05>
:PROPERTIES:
:ID:       q4SHVWAU443q5lYA5aTA7a_Z@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Missions vs. Naturals Missions vs. Naturals

Follow on MiLB First Pitch  https //stza.co/+wMxi-3k

Shop  https //stza.co/+wMxi-17

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Missions vs. Naturals
END:VALARM
DTSTART:20180707T000500Z
DTEND:20180707T030500Z
UID:q4SHVWAU443q5lYA5aTA7a_Z@stanza.co
SUMMARY:Missions vs. Naturals
DESCRIPTION:Missions vs. Naturals\n\nFollow on MiLB First Pitch: https://stza.co/+wMxi-3k\n\nShop: https://stza.co/+wMxi-17\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144556Z
LAST-MODIFIED:20180213T144556Z
TRANSP:OPAQUE
END:VEVENT
* Missions vs. Travelers
<2018-07-07 Sat 19:05-22:05>
:PROPERTIES:
:ID:       F-gWRjX4ej7_6iF36PajQduv@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Missions vs. Travelers Missions vs. Travelers

Follow on MiLB First Pitch  https //stza.co/+wMxm-2T

Shop  https //stza.co/+wMxm-24

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Missions vs. Travelers
END:VALARM
DTSTART:20180708T000500Z
DTEND:20180708T030500Z
UID:F-gWRjX4ej7_6iF36PajQduv@stanza.co
SUMMARY:Missions vs. Travelers
DESCRIPTION:Missions vs. Travelers\n\nFollow on MiLB First Pitch: https://stza.co/+wMxm-2T\n\nShop: https://stza.co/+wMxm-24\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144556Z
LAST-MODIFIED:20180213T144556Z
TRANSP:OPAQUE
END:VEVENT
* Missions vs. Travelers
<2018-07-08 Sun 18:05-21:05>
:PROPERTIES:
:ID:       7656nmyC65xm38BTbimzxtzx@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Missions vs. Travelers Missions vs. Travelers

Follow on MiLB First Pitch  https //stza.co/+wMxp-6

Shop  https //stza.co/+wMxp-22

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Missions vs. Travelers
END:VALARM
DTSTART:20180708T230500Z
DTEND:20180709T020500Z
UID:7656nmyC65xm38BTbimzxtzx@stanza.co
SUMMARY:Missions vs. Travelers
DESCRIPTION:Missions vs. Travelers\n\nFollow on MiLB First Pitch: https://stza.co/+wMxp-6\n\nShop: https://stza.co/+wMxp-22\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144556Z
LAST-MODIFIED:20180213T144556Z
TRANSP:OPAQUE
END:VEVENT
* Missions vs. Travelers
<2018-07-09 Mon 19:05-22:05>
:PROPERTIES:
:ID:       BWxpTAJQVvCVHXfHURnaGHqt@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Missions vs. Travelers Missions vs. Travelers

Follow on MiLB First Pitch  https //stza.co/+wMxr-3P

Shop  https //stza.co/+wMxr-I

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Missions vs. Travelers
END:VALARM
DTSTART:20180710T000500Z
DTEND:20180710T030500Z
UID:BWxpTAJQVvCVHXfHURnaGHqt@stanza.co
SUMMARY:Missions vs. Travelers
DESCRIPTION:Missions vs. Travelers\n\nFollow on MiLB First Pitch: https://stza.co/+wMxr-3P\n\nShop: https://stza.co/+wMxr-I\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144556Z
LAST-MODIFIED:20180213T144556Z
TRANSP:OPAQUE
END:VEVENT
* Missions @ RoughRiders
<2018-07-11 Wed 19:05-22:05>
:PROPERTIES:
:ID:       J6ufm6QsitvbRfvRrhxHsYgc@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Missions @ RoughRiders Missions @ RoughRiders

Follow on MiLB First Pitch  https //stza.co/+wYbY-2U

Shop  https //stza.co/+wYbY-19

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Missions @ RoughRiders
END:VALARM
DTSTART:20180712T000500Z
DTEND:20180712T030500Z
UID:J6ufm6QsitvbRfvRrhxHsYgc@stanza.co
SUMMARY:Missions @ RoughRiders
DESCRIPTION:Missions @ RoughRiders\n\nFollow on MiLB First Pitch: https://stza.co/+wYbY-2U\n\nShop: https://stza.co/+wYbY-19\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144556Z
LAST-MODIFIED:20180213T144556Z
TRANSP:OPAQUE
END:VEVENT
* Missions @ RoughRiders
<2018-07-12 Thu 19:05-22:05>
:PROPERTIES:
:ID:       NePBIKWhOBd8xIS8Tfk6AdKe@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Missions @ RoughRiders Missions @ RoughRiders

Follow on MiLB First Pitch  https //stza.co/+wYb_-A

Shop  https //stza.co/+wYb_-2y

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Missions @ RoughRiders
END:VALARM
DTSTART:20180713T000500Z
DTEND:20180713T030500Z
UID:NePBIKWhOBd8xIS8Tfk6AdKe@stanza.co
SUMMARY:Missions @ RoughRiders
DESCRIPTION:Missions @ RoughRiders\n\nFollow on MiLB First Pitch: https://stza.co/+wYb_-A\n\nShop: https://stza.co/+wYb_-2y\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144556Z
LAST-MODIFIED:20180213T144556Z
TRANSP:OPAQUE
END:VEVENT
* Missions @ RoughRiders
<2018-07-13 Fri 19:05-22:05>
:PROPERTIES:
:ID:       mo2xhYEETQGuYQxF2K2t_XWW@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Missions @ RoughRiders Missions @ RoughRiders

Follow on MiLB First Pitch  https //stza.co/+wYb$-5

Shop  https //stza.co/+wYb$-30

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Missions @ RoughRiders
END:VALARM
DTSTART:20180714T000500Z
DTEND:20180714T030500Z
UID:mo2xhYEETQGuYQxF2K2t_XWW@stanza.co
SUMMARY:Missions @ RoughRiders
DESCRIPTION:Missions @ RoughRiders\n\nFollow on MiLB First Pitch: https://stza.co/+wYb$-5\n\nShop: https://stza.co/+wYb$-30\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144556Z
LAST-MODIFIED:20180213T144556Z
TRANSP:OPAQUE
END:VEVENT
* Missions @ RoughRiders
<2018-07-14 Sat 19:05-22:05>
:PROPERTIES:
:ID:       S4svA5NaVoJdx2F6gOJ91zDW@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Missions @ RoughRiders Missions @ RoughRiders

Follow on MiLB First Pitch  https //stza.co/+wYc0-3

Shop  https //stza.co/+wYc0-2K

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Missions @ RoughRiders
END:VALARM
DTSTART:20180715T000500Z
DTEND:20180715T030500Z
UID:S4svA5NaVoJdx2F6gOJ91zDW@stanza.co
SUMMARY:Missions @ RoughRiders
DESCRIPTION:Missions @ RoughRiders\n\nFollow on MiLB First Pitch: https://stza.co/+wYc0-3\n\nShop: https://stza.co/+wYc0-2K\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144556Z
LAST-MODIFIED:20180213T144556Z
TRANSP:OPAQUE
END:VEVENT
* Missions vs. RockHounds
<2018-07-15 Sun 18:05-21:05>
:PROPERTIES:
:ID:       py-6HLuwM3gAiCdcoQhiniuG@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Missions vs. RockHounds Missions vs. RockHounds

Follow on MiLB First Pitch  https //stza.co/+wMxt-2P

Shop  https //stza.co/+wMxt-o

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Missions vs. RockHounds
END:VALARM
DTSTART:20180715T230500Z
DTEND:20180716T020500Z
UID:py-6HLuwM3gAiCdcoQhiniuG@stanza.co
SUMMARY:Missions vs. RockHounds
DESCRIPTION:Missions vs. RockHounds\n\nFollow on MiLB First Pitch: https://stza.co/+wMxt-2P\n\nShop: https://stza.co/+wMxt-o\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144556Z
LAST-MODIFIED:20180213T144556Z
TRANSP:OPAQUE
END:VEVENT
* Missions vs. RockHounds
<2018-07-16 Mon 11:05-14:05>
:PROPERTIES:
:ID:       OD9ov9frYovdpBoNLFAzzCfC@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Missions vs. RockHounds Missions vs. RockHounds

Follow on MiLB First Pitch  https //stza.co/+wMxv-p

Shop  https //stza.co/+wMxv-3z

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Missions vs. RockHounds
END:VALARM
DTSTART:20180716T160500Z
DTEND:20180716T190500Z
UID:OD9ov9frYovdpBoNLFAzzCfC@stanza.co
SUMMARY:Missions vs. RockHounds
DESCRIPTION:Missions vs. RockHounds\n\nFollow on MiLB First Pitch: https://stza.co/+wMxv-p\n\nShop: https://stza.co/+wMxv-3z\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144556Z
LAST-MODIFIED:20180213T144556Z
TRANSP:OPAQUE
END:VEVENT
* Missions vs. RockHounds
<2018-07-17 Tue 19:05-22:05>
:PROPERTIES:
:ID:       R0-ru4mrk2Mi_n7P-KemKArz@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Missions vs. RockHounds Missions vs. RockHounds

Follow on MiLB First Pitch  https //stza.co/+wMxw-3Z

Shop  https //stza.co/+wMxw-36

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Missions vs. RockHounds
END:VALARM
DTSTART:20180718T000500Z
DTEND:20180718T030500Z
UID:R0-ru4mrk2Mi_n7P-KemKArz@stanza.co
SUMMARY:Missions vs. RockHounds
DESCRIPTION:Missions vs. RockHounds\n\nFollow on MiLB First Pitch: https://stza.co/+wMxw-3Z\n\nShop: https://stza.co/+wMxw-36\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144556Z
LAST-MODIFIED:20180213T144556Z
TRANSP:OPAQUE
END:VEVENT
* Missions vs. RockHounds
<2018-07-18 Wed 19:05-22:05>
:PROPERTIES:
:ID:       jq2_8Zx6iOe21qmVd4EypX1T@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Missions vs. RockHounds Missions vs. RockHounds

Follow on MiLB First Pitch  https //stza.co/+wMxy-3k

Shop  https //stza.co/+wMxy-3Z

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Missions vs. RockHounds
END:VALARM
DTSTART:20180719T000500Z
DTEND:20180719T030500Z
UID:jq2_8Zx6iOe21qmVd4EypX1T@stanza.co
SUMMARY:Missions vs. RockHounds
DESCRIPTION:Missions vs. RockHounds\n\nFollow on MiLB First Pitch: https://stza.co/+wMxy-3k\n\nShop: https://stza.co/+wMxy-3Z\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144556Z
LAST-MODIFIED:20180213T144556Z
TRANSP:OPAQUE
END:VEVENT
* Missions @ RoughRiders
<2018-07-19 Thu 19:05-22:05>
:PROPERTIES:
:ID:       Ud1bS6VavAuo_QbITrvDa4UR@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Missions @ RoughRiders Missions @ RoughRiders

Follow on MiLB First Pitch  https //stza.co/+wYc2-b

Shop  https //stza.co/+wYc2-2I

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Missions @ RoughRiders
END:VALARM
DTSTART:20180720T000500Z
DTEND:20180720T030500Z
UID:Ud1bS6VavAuo_QbITrvDa4UR@stanza.co
SUMMARY:Missions @ RoughRiders
DESCRIPTION:Missions @ RoughRiders\n\nFollow on MiLB First Pitch: https://stza.co/+wYc2-b\n\nShop: https://stza.co/+wYc2-2I\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144556Z
LAST-MODIFIED:20180213T144556Z
TRANSP:OPAQUE
END:VEVENT
* Missions @ RoughRiders
<2018-07-20 Fri 19:05-22:05>
:PROPERTIES:
:ID:       CreL7RKm1R4JKyfj1JALbzIm@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Missions @ RoughRiders Missions @ RoughRiders

Follow on MiLB First Pitch  https //stza.co/+wYc3-3

Shop  https //stza.co/+wYc3-2K

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Missions @ RoughRiders
END:VALARM
DTSTART:20180721T000500Z
DTEND:20180721T030500Z
UID:CreL7RKm1R4JKyfj1JALbzIm@stanza.co
SUMMARY:Missions @ RoughRiders
DESCRIPTION:Missions @ RoughRiders\n\nFollow on MiLB First Pitch: https://stza.co/+wYc3-3\n\nShop: https://stza.co/+wYc3-2K\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144556Z
LAST-MODIFIED:20180213T144556Z
TRANSP:OPAQUE
END:VEVENT
* Missions @ RoughRiders
<2018-07-21 Sat 19:05-22:05>
:PROPERTIES:
:ID:       PPTRpblUVBjcBhtyvDFt_snJ@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Missions @ RoughRiders Missions @ RoughRiders

Follow on MiLB First Pitch  https //stza.co/+wYc6-2u

Shop  https //stza.co/+wYc6-2M

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Missions @ RoughRiders
END:VALARM
DTSTART:20180722T000500Z
DTEND:20180722T030500Z
UID:PPTRpblUVBjcBhtyvDFt_snJ@stanza.co
SUMMARY:Missions @ RoughRiders
DESCRIPTION:Missions @ RoughRiders\n\nFollow on MiLB First Pitch: https://stza.co/+wYc6-2u\n\nShop: https://stza.co/+wYc6-2M\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144556Z
LAST-MODIFIED:20180213T144556Z
TRANSP:OPAQUE
END:VEVENT
* Missions @ RoughRiders
<2018-07-22 Sun 19:05-22:05>
:PROPERTIES:
:ID:       mUEJQIDbf9mn9fOUXtFpbBFD@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Missions @ RoughRiders Missions @ RoughRiders

Follow on MiLB First Pitch  https //stza.co/+wYc7-23

Shop  https //stza.co/+wYc7-3b

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Missions @ RoughRiders
END:VALARM
DTSTART:20180723T000500Z
DTEND:20180723T030500Z
UID:mUEJQIDbf9mn9fOUXtFpbBFD@stanza.co
SUMMARY:Missions @ RoughRiders
DESCRIPTION:Missions @ RoughRiders\n\nFollow on MiLB First Pitch: https://stza.co/+wYc7-23\n\nShop: https://stza.co/+wYc7-3b\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144556Z
LAST-MODIFIED:20180213T144556Z
TRANSP:OPAQUE
END:VEVENT
* Missions vs. Hooks
<2018-07-23 Mon 19:05-22:05>
:PROPERTIES:
:ID:       TflTgou7PhgJ6oclh_Hhor40@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Missions vs. Hooks Missions vs. Hooks

Follow on MiLB First Pitch  https //stza.co/+wMxA-2a

Shop  https //stza.co/+wMxA-1r

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Missions vs. Hooks
END:VALARM
DTSTART:20180724T000500Z
DTEND:20180724T030500Z
UID:TflTgou7PhgJ6oclh_Hhor40@stanza.co
SUMMARY:Missions vs. Hooks
DESCRIPTION:Missions vs. Hooks\n\nFollow on MiLB First Pitch: https://stza.co/+wMxA-2a\n\nShop: https://stza.co/+wMxA-1r\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144556Z
LAST-MODIFIED:20180213T144556Z
TRANSP:OPAQUE
END:VEVENT
* Missions vs. Hooks
<2018-07-24 Tue 19:05-22:05>
:PROPERTIES:
:ID:       Yu-njhEhqvkmtQNegfwuCltx@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Missions vs. Hooks Missions vs. Hooks

Follow on MiLB First Pitch  https //stza.co/+wMxC-2L

Shop  https //stza.co/+wMxC-3R

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Missions vs. Hooks
END:VALARM
DTSTART:20180725T000500Z
DTEND:20180725T030500Z
UID:Yu-njhEhqvkmtQNegfwuCltx@stanza.co
SUMMARY:Missions vs. Hooks
DESCRIPTION:Missions vs. Hooks\n\nFollow on MiLB First Pitch: https://stza.co/+wMxC-2L\n\nShop: https://stza.co/+wMxC-3R\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144556Z
LAST-MODIFIED:20180213T144556Z
TRANSP:OPAQUE
END:VEVENT
* Missions vs. Hooks
<2018-07-25 Wed 19:05-22:05>
:PROPERTIES:
:ID:       WtNHCFg9UFVEOhEPXWxb-ewh@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Missions vs. Hooks Missions vs. Hooks

Follow on MiLB First Pitch  https //stza.co/+wMxF-Y

Shop  https //stza.co/+wMxF-3n

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Missions vs. Hooks
END:VALARM
DTSTART:20180726T000500Z
DTEND:20180726T030500Z
UID:WtNHCFg9UFVEOhEPXWxb-ewh@stanza.co
SUMMARY:Missions vs. Hooks
DESCRIPTION:Missions vs. Hooks\n\nFollow on MiLB First Pitch: https://stza.co/+wMxF-Y\n\nShop: https://stza.co/+wMxF-3n\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144556Z
LAST-MODIFIED:20180213T144556Z
TRANSP:OPAQUE
END:VEVENT
* Missions vs. RoughRiders
<2018-07-26 Thu 19:05-22:05>
:PROPERTIES:
:ID:       InlRHQ2wcKdorH-W7xeniSFc@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Missions vs. RoughRiders Missions vs. RoughRiders

Follow on MiLB First Pitch  https //stza.co/+wMxH-1M

Shop  https //stza.co/+wMxH-_

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Missions vs. RoughRiders
END:VALARM
DTSTART:20180727T000500Z
DTEND:20180727T030500Z
UID:InlRHQ2wcKdorH-W7xeniSFc@stanza.co
SUMMARY:Missions vs. RoughRiders
DESCRIPTION:Missions vs. RoughRiders\n\nFollow on MiLB First Pitch: https://stza.co/+wMxH-1M\n\nShop: https://stza.co/+wMxH-_\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144556Z
LAST-MODIFIED:20180213T144556Z
TRANSP:OPAQUE
END:VEVENT
* Missions vs. RoughRiders
<2018-07-27 Fri 19:05-22:05>
:PROPERTIES:
:ID:       UDjhUEXQmn5bUj5oebOVtWug@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Missions vs. RoughRiders Missions vs. RoughRiders

Follow on MiLB First Pitch  https //stza.co/+wMxJ-3o

Shop  https //stza.co/+wMxJ-2G

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Missions vs. RoughRiders
END:VALARM
DTSTART:20180728T000500Z
DTEND:20180728T030500Z
UID:UDjhUEXQmn5bUj5oebOVtWug@stanza.co
SUMMARY:Missions vs. RoughRiders
DESCRIPTION:Missions vs. RoughRiders\n\nFollow on MiLB First Pitch: https://stza.co/+wMxJ-3o\n\nShop: https://stza.co/+wMxJ-2G\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144556Z
LAST-MODIFIED:20180213T144556Z
TRANSP:OPAQUE
END:VEVENT
* Missions vs. RoughRiders
<2018-07-28 Sat 19:05-22:05>
:PROPERTIES:
:ID:       WCbiI-DNFQrL2B5di__J1SHk@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Missions vs. RoughRiders Missions vs. RoughRiders

Follow on MiLB First Pitch  https //stza.co/+wMxL-1M

Shop  https //stza.co/+wMxL-3v

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Missions vs. RoughRiders
END:VALARM
DTSTART:20180729T000500Z
DTEND:20180729T030500Z
UID:WCbiI-DNFQrL2B5di__J1SHk@stanza.co
SUMMARY:Missions vs. RoughRiders
DESCRIPTION:Missions vs. RoughRiders\n\nFollow on MiLB First Pitch: https://stza.co/+wMxL-1M\n\nShop: https://stza.co/+wMxL-3v\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144556Z
LAST-MODIFIED:20180213T144556Z
TRANSP:OPAQUE
END:VEVENT
* Missions vs. RoughRiders
<2018-07-29 Sun 18:05-21:05>
:PROPERTIES:
:ID:       eQaV_5BrLCXQpJb2zXD4Conj@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Missions vs. RoughRiders Missions vs. RoughRiders

Follow on MiLB First Pitch  https //stza.co/+wMxN-3p

Shop  https //stza.co/+wMxN-3K

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Missions vs. RoughRiders
END:VALARM
DTSTART:20180729T230500Z
DTEND:20180730T020500Z
UID:eQaV_5BrLCXQpJb2zXD4Conj@stanza.co
SUMMARY:Missions vs. RoughRiders
DESCRIPTION:Missions vs. RoughRiders\n\nFollow on MiLB First Pitch: https://stza.co/+wMxN-3p\n\nShop: https://stza.co/+wMxN-3K\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144556Z
LAST-MODIFIED:20180213T144556Z
TRANSP:OPAQUE
END:VEVENT
* Missions @ Hooks
<2018-07-30 Mon 19:05-22:05>
:PROPERTIES:
:ID:       d8rprS0XiGsGCxTmG1M7nfP1@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Missions @ Hooks Missions @ Hooks

Follow on MiLB First Pitch  https //stza.co/+xzIh-s

Shop  https //stza.co/+xzIh-1y

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Missions @ Hooks
END:VALARM
DTSTART:20180731T000500Z
DTEND:20180731T030500Z
UID:d8rprS0XiGsGCxTmG1M7nfP1@stanza.co
SUMMARY:Missions @ Hooks
DESCRIPTION:Missions @ Hooks\n\nFollow on MiLB First Pitch: https://stza.co/+xzIh-s\n\nShop: https://stza.co/+xzIh-1y\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144556Z
LAST-MODIFIED:20180213T144556Z
TRANSP:OPAQUE
END:VEVENT
* Missions @ Hooks
<2018-07-31 Tue 19:05-22:05>
:PROPERTIES:
:ID:       JQiJskEbIuArc5-6QBm5XdRR@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Missions @ Hooks Missions @ Hooks

Follow on MiLB First Pitch  https //stza.co/+xzIi-3s

Shop  https //stza.co/+xzIi-3f

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Missions @ Hooks
END:VALARM
DTSTART:20180801T000500Z
DTEND:20180801T030500Z
UID:JQiJskEbIuArc5-6QBm5XdRR@stanza.co
SUMMARY:Missions @ Hooks
DESCRIPTION:Missions @ Hooks\n\nFollow on MiLB First Pitch: https://stza.co/+xzIi-3s\n\nShop: https://stza.co/+xzIi-3f\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144556Z
LAST-MODIFIED:20180213T144556Z
TRANSP:OPAQUE
END:VEVENT
* Missions @ Hooks
<2018-08-01 Wed 19:05-22:05>
:PROPERTIES:
:ID:       LQwdsvqhNYRov_iHHN-bNPQ2@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Missions @ Hooks Missions @ Hooks

Follow on MiLB First Pitch  https //stza.co/+xzIj-1i

Shop  https //stza.co/+xzIj-2M

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Missions @ Hooks
END:VALARM
DTSTART:20180802T000500Z
DTEND:20180802T030500Z
UID:LQwdsvqhNYRov_iHHN-bNPQ2@stanza.co
SUMMARY:Missions @ Hooks
DESCRIPTION:Missions @ Hooks\n\nFollow on MiLB First Pitch: https://stza.co/+xzIj-1i\n\nShop: https://stza.co/+xzIj-2M\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144556Z
LAST-MODIFIED:20180213T144556Z
TRANSP:OPAQUE
END:VEVENT
* Missions @ RockHounds
<2018-08-02 Thu 19:00-22:00>
:PROPERTIES:
:ID:       vMmVvZEc5864bzxU_o0kYa9J@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Missions @ RockHounds Missions @ RockHounds

Follow on MiLB First Pitch  https //stza.co/+wX5n-1J

Shop  https //stza.co/+wX5n-21

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Missions @ RockHounds
END:VALARM
DTSTART:20180803T000000Z
DTEND:20180803T030000Z
UID:vMmVvZEc5864bzxU_o0kYa9J@stanza.co
SUMMARY:Missions @ RockHounds
DESCRIPTION:Missions @ RockHounds\n\nFollow on MiLB First Pitch: https://stza.co/+wX5n-1J\n\nShop: https://stza.co/+wX5n-21\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144556Z
LAST-MODIFIED:20180213T144556Z
TRANSP:OPAQUE
END:VEVENT
* Missions @ RockHounds
<2018-08-03 Fri 19:00-22:00>
:PROPERTIES:
:ID:       nGLU6YOIw9zEw0beuQGkcDgk@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Missions @ RockHounds Missions @ RockHounds

Follow on MiLB First Pitch  https //stza.co/+wX5p-I

Shop  https //stza.co/+wX5p-3c

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Missions @ RockHounds
END:VALARM
DTSTART:20180804T000000Z
DTEND:20180804T030000Z
UID:nGLU6YOIw9zEw0beuQGkcDgk@stanza.co
SUMMARY:Missions @ RockHounds
DESCRIPTION:Missions @ RockHounds\n\nFollow on MiLB First Pitch: https://stza.co/+wX5p-I\n\nShop: https://stza.co/+wX5p-3c\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144556Z
LAST-MODIFIED:20180213T144556Z
TRANSP:OPAQUE
END:VEVENT
* Missions @ RockHounds
<2018-08-04 Sat 19:00-22:00>
:PROPERTIES:
:ID:       nzaCuCO3GBAlUNgwBeI_jX0l@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Missions @ RockHounds Missions @ RockHounds

Follow on MiLB First Pitch  https //stza.co/+wX5q-1q

Shop  https //stza.co/+wX5q-q

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Missions @ RockHounds
END:VALARM
DTSTART:20180805T000000Z
DTEND:20180805T030000Z
UID:nzaCuCO3GBAlUNgwBeI_jX0l@stanza.co
SUMMARY:Missions @ RockHounds
DESCRIPTION:Missions @ RockHounds\n\nFollow on MiLB First Pitch: https://stza.co/+wX5q-1q\n\nShop: https://stza.co/+wX5q-q\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144556Z
LAST-MODIFIED:20180213T144556Z
TRANSP:OPAQUE
END:VEVENT
* Missions @ RockHounds
<2018-08-05 Sun 14:00-17:00>
:PROPERTIES:
:ID:       Ool7SXJ3UJJGD0w9bdnN7h8L@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Missions @ RockHounds Missions @ RockHounds

Follow on MiLB First Pitch  https //stza.co/+wX5r-3y

Shop  https //stza.co/+wX5r-z

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Missions @ RockHounds
END:VALARM
DTSTART:20180805T190000Z
DTEND:20180805T220000Z
UID:Ool7SXJ3UJJGD0w9bdnN7h8L@stanza.co
SUMMARY:Missions @ RockHounds
DESCRIPTION:Missions @ RockHounds\n\nFollow on MiLB First Pitch: https://stza.co/+wX5r-3y\n\nShop: https://stza.co/+wX5r-z\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144556Z
LAST-MODIFIED:20180213T144556Z
TRANSP:OPAQUE
END:VEVENT
* Missions vs. Cardinals
<2018-08-07 Tue 19:05-22:05>
:PROPERTIES:
:ID:       o8Sj_9RdfDWK6H1IYgi1Lw22@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Missions vs. Cardinals Missions vs. Cardinals

Follow on MiLB First Pitch  https //stza.co/+wMxO-1q

Shop  https //stza.co/+wMxO-29

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Missions vs. Cardinals
END:VALARM
DTSTART:20180808T000500Z
DTEND:20180808T030500Z
UID:o8Sj_9RdfDWK6H1IYgi1Lw22@stanza.co
SUMMARY:Missions vs. Cardinals
DESCRIPTION:Missions vs. Cardinals\n\nFollow on MiLB First Pitch: https://stza.co/+wMxO-1q\n\nShop: https://stza.co/+wMxO-29\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144556Z
LAST-MODIFIED:20180213T144556Z
TRANSP:OPAQUE
END:VEVENT
* Missions vs. Cardinals
<2018-08-08 Wed 19:05-22:05>
:PROPERTIES:
:ID:       NIxTCgsizC_IAx_2_AorH-pG@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Missions vs. Cardinals Missions vs. Cardinals

Follow on MiLB First Pitch  https //stza.co/+wMxR-3y

Shop  https //stza.co/+wMxR-3f

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Missions vs. Cardinals
END:VALARM
DTSTART:20180809T000500Z
DTEND:20180809T030500Z
UID:NIxTCgsizC_IAx_2_AorH-pG@stanza.co
SUMMARY:Missions vs. Cardinals
DESCRIPTION:Missions vs. Cardinals\n\nFollow on MiLB First Pitch: https://stza.co/+wMxR-3y\n\nShop: https://stza.co/+wMxR-3f\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144556Z
LAST-MODIFIED:20180213T144556Z
TRANSP:OPAQUE
END:VEVENT
* Missions vs. Cardinals
<2018-08-09 Thu 19:05-22:05>
:PROPERTIES:
:ID:       0qLBO4whHjIo1sW1EG1cB2x7@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Missions vs. Cardinals Missions vs. Cardinals

Follow on MiLB First Pitch  https //stza.co/+wMxT-3x

Shop  https //stza.co/+wMxT-2k

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Missions vs. Cardinals
END:VALARM
DTSTART:20180810T000500Z
DTEND:20180810T030500Z
UID:0qLBO4whHjIo1sW1EG1cB2x7@stanza.co
SUMMARY:Missions vs. Cardinals
DESCRIPTION:Missions vs. Cardinals\n\nFollow on MiLB First Pitch: https://stza.co/+wMxT-3x\n\nShop: https://stza.co/+wMxT-2k\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144556Z
LAST-MODIFIED:20180213T144556Z
TRANSP:OPAQUE
END:VEVENT
* Missions vs. Drillers
<2018-08-10 Fri 19:05-22:05>
:PROPERTIES:
:ID:       sPUypglZloQojTma93GMxXRj@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Missions vs. Drillers Missions vs. Drillers

Follow on MiLB First Pitch  https //stza.co/+wMxV-1W

Shop  https //stza.co/+wMxV-I

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Missions vs. Drillers
END:VALARM
DTSTART:20180811T000500Z
DTEND:20180811T030500Z
UID:sPUypglZloQojTma93GMxXRj@stanza.co
SUMMARY:Missions vs. Drillers
DESCRIPTION:Missions vs. Drillers\n\nFollow on MiLB First Pitch: https://stza.co/+wMxV-1W\n\nShop: https://stza.co/+wMxV-I\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144556Z
LAST-MODIFIED:20180213T144556Z
TRANSP:OPAQUE
END:VEVENT
* Missions vs. Drillers
<2018-08-11 Sat 19:05-22:05>
:PROPERTIES:
:ID:       jwkK5stwqncw3hkg3o2Ued_N@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Missions vs. Drillers Missions vs. Drillers

Follow on MiLB First Pitch  https //stza.co/+wMxY-6

Shop  https //stza.co/+wMxY-3I

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Missions vs. Drillers
END:VALARM
DTSTART:20180812T000500Z
DTEND:20180812T030500Z
UID:jwkK5stwqncw3hkg3o2Ued_N@stanza.co
SUMMARY:Missions vs. Drillers
DESCRIPTION:Missions vs. Drillers\n\nFollow on MiLB First Pitch: https://stza.co/+wMxY-6\n\nShop: https://stza.co/+wMxY-3I\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144556Z
LAST-MODIFIED:20180213T144556Z
TRANSP:OPAQUE
END:VEVENT
* Missions vs. Drillers
<2018-08-12 Sun 18:05-21:05>
:PROPERTIES:
:ID:       QLwcvXGZ5ejipZHEEMVLqMqW@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Missions vs. Drillers Missions vs. Drillers

Follow on MiLB First Pitch  https //stza.co/+wMx_-1C

Shop  https //stza.co/+wMx_-Q

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Missions vs. Drillers
END:VALARM
DTSTART:20180812T230500Z
DTEND:20180813T020500Z
UID:QLwcvXGZ5ejipZHEEMVLqMqW@stanza.co
SUMMARY:Missions vs. Drillers
DESCRIPTION:Missions vs. Drillers\n\nFollow on MiLB First Pitch: https://stza.co/+wMx_-1C\n\nShop: https://stza.co/+wMx_-Q\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144556Z
LAST-MODIFIED:20180213T144556Z
TRANSP:OPAQUE
END:VEVENT
* Missions @ Cardinals
<2018-08-14 Tue 18:30-21:30>
:PROPERTIES:
:ID:       Q5ZyWN1O4ef6j4dzJ09XjLAQ@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Missions @ Cardinals Missions @ Cardinals

Follow on MiLB First Pitch  https //stza.co/+wPNR-2u

Shop  https //stza.co/+wPNR-2N

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Missions @ Cardinals
END:VALARM
DTSTART:20180814T233000Z
DTEND:20180815T023000Z
UID:Q5ZyWN1O4ef6j4dzJ09XjLAQ@stanza.co
SUMMARY:Missions @ Cardinals
DESCRIPTION:Missions @ Cardinals\n\nFollow on MiLB First Pitch: https://stza.co/+wPNR-2u\n\nShop: https://stza.co/+wPNR-2N\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144556Z
LAST-MODIFIED:20180213T144556Z
TRANSP:OPAQUE
END:VEVENT
* Missions @ Cardinals
<2018-08-15 Wed 18:30-21:30>
:PROPERTIES:
:ID:       FDvQ_DlWGAaUuGLqd9X01Otc@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Missions @ Cardinals Missions @ Cardinals

Follow on MiLB First Pitch  https //stza.co/+wPNS-1H

Shop  https //stza.co/+wPNS-S

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Missions @ Cardinals
END:VALARM
DTSTART:20180815T233000Z
DTEND:20180816T023000Z
UID:FDvQ_DlWGAaUuGLqd9X01Otc@stanza.co
SUMMARY:Missions @ Cardinals
DESCRIPTION:Missions @ Cardinals\n\nFollow on MiLB First Pitch: https://stza.co/+wPNS-1H\n\nShop: https://stza.co/+wPNS-S\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144556Z
LAST-MODIFIED:20180213T144556Z
TRANSP:OPAQUE
END:VEVENT
* Missions @ Cardinals
<2018-08-16 Thu 19:10-22:10>
:PROPERTIES:
:ID:       itdc7rKdR5tm_eizUmXAeVvr@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Missions @ Cardinals Missions @ Cardinals

Follow on MiLB First Pitch  https //stza.co/+wPNT-3s

Shop  https //stza.co/+wPNT-3k

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Missions @ Cardinals
END:VALARM
DTSTART:20180817T001000Z
DTEND:20180817T031000Z
UID:itdc7rKdR5tm_eizUmXAeVvr@stanza.co
SUMMARY:Missions @ Cardinals
DESCRIPTION:Missions @ Cardinals\n\nFollow on MiLB First Pitch: https://stza.co/+wPNT-3s\n\nShop: https://stza.co/+wPNT-3k\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144556Z
LAST-MODIFIED:20180213T144556Z
TRANSP:OPAQUE
END:VEVENT
* Missions @ Drillers
<2018-08-17 Fri 19:05-22:05>
:PROPERTIES:
:ID:       A5cbDqQj1fxI2H9H2Rv-qgiP@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Missions @ Drillers Missions @ Drillers

Follow on MiLB First Pitch  https //stza.co/+w0af-17

Shop  https //stza.co/+w0af-2I

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Missions @ Drillers
END:VALARM
DTSTART:20180818T000500Z
DTEND:20180818T030500Z
UID:A5cbDqQj1fxI2H9H2Rv-qgiP@stanza.co
SUMMARY:Missions @ Drillers
DESCRIPTION:Missions @ Drillers\n\nFollow on MiLB First Pitch: https://stza.co/+w0af-17\n\nShop: https://stza.co/+w0af-2I\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144556Z
LAST-MODIFIED:20180213T144556Z
TRANSP:OPAQUE
END:VEVENT
* Missions @ Drillers
<2018-08-18 Sat 19:05-22:05>
:PROPERTIES:
:ID:       tS5EapHvsTWnUqHWS0R-M6IH@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Missions @ Drillers Missions @ Drillers

Follow on MiLB First Pitch  https //stza.co/+w0ag-m

Shop  https //stza.co/+w0ag-M

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Missions @ Drillers
END:VALARM
DTSTART:20180819T000500Z
DTEND:20180819T030500Z
UID:tS5EapHvsTWnUqHWS0R-M6IH@stanza.co
SUMMARY:Missions @ Drillers
DESCRIPTION:Missions @ Drillers\n\nFollow on MiLB First Pitch: https://stza.co/+w0ag-m\n\nShop: https://stza.co/+w0ag-M\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144556Z
LAST-MODIFIED:20180213T144556Z
TRANSP:OPAQUE
END:VEVENT
* Missions @ Drillers
<2018-08-19 Sun 19:05-22:05>
:PROPERTIES:
:ID:       3afo3MRwojUjEOfV56Qngr5I@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Missions @ Drillers Missions @ Drillers

Follow on MiLB First Pitch  https //stza.co/+w0ah-3d

Shop  https //stza.co/+w0ah-2H

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Missions @ Drillers
END:VALARM
DTSTART:20180820T000500Z
DTEND:20180820T030500Z
UID:3afo3MRwojUjEOfV56Qngr5I@stanza.co
SUMMARY:Missions @ Drillers
DESCRIPTION:Missions @ Drillers\n\nFollow on MiLB First Pitch: https://stza.co/+w0ah-3d\n\nShop: https://stza.co/+w0ah-2H\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144556Z
LAST-MODIFIED:20180213T144556Z
TRANSP:OPAQUE
END:VEVENT
* Missions vs. RoughRiders
<2018-08-21 Tue 19:05-22:05>
:PROPERTIES:
:ID:       AU8yD_7Rvwn6t2eQYUrsNavO@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Missions vs. RoughRiders Missions vs. RoughRiders

Follow on MiLB First Pitch  https //stza.co/+wMy1-2D

Shop  https //stza.co/+wMy1-3j

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Missions vs. RoughRiders
END:VALARM
DTSTART:20180822T000500Z
DTEND:20180822T030500Z
UID:AU8yD_7Rvwn6t2eQYUrsNavO@stanza.co
SUMMARY:Missions vs. RoughRiders
DESCRIPTION:Missions vs. RoughRiders\n\nFollow on MiLB First Pitch: https://stza.co/+wMy1-2D\n\nShop: https://stza.co/+wMy1-3j\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144556Z
LAST-MODIFIED:20180213T144556Z
TRANSP:OPAQUE
END:VEVENT
* Missions vs. RoughRiders
<2018-08-22 Wed 19:05-22:05>
:PROPERTIES:
:ID:       DEC4VHXeXIEEOKrS7TnemvkZ@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Missions vs. RoughRiders Missions vs. RoughRiders

Follow on MiLB First Pitch  https //stza.co/+wMy3-g

Shop  https //stza.co/+wMy3-2x

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Missions vs. RoughRiders
END:VALARM
DTSTART:20180823T000500Z
DTEND:20180823T030500Z
UID:DEC4VHXeXIEEOKrS7TnemvkZ@stanza.co
SUMMARY:Missions vs. RoughRiders
DESCRIPTION:Missions vs. RoughRiders\n\nFollow on MiLB First Pitch: https://stza.co/+wMy3-g\n\nShop: https://stza.co/+wMy3-2x\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144556Z
LAST-MODIFIED:20180213T144556Z
TRANSP:OPAQUE
END:VEVENT
* Missions vs. RoughRiders
<2018-08-23 Thu 19:05-22:05>
:PROPERTIES:
:ID:       jwybmio4J7nynHtRZxzxBSu-@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Missions vs. RoughRiders Missions vs. RoughRiders

Follow on MiLB First Pitch  https //stza.co/+wMy5-3O

Shop  https //stza.co/+wMy5-2m

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Missions vs. RoughRiders
END:VALARM
DTSTART:20180824T000500Z
DTEND:20180824T030500Z
UID:jwybmio4J7nynHtRZxzxBSu-@stanza.co
SUMMARY:Missions vs. RoughRiders
DESCRIPTION:Missions vs. RoughRiders\n\nFollow on MiLB First Pitch: https://stza.co/+wMy5-3O\n\nShop: https://stza.co/+wMy5-2m\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144556Z
LAST-MODIFIED:20180213T144556Z
TRANSP:OPAQUE
END:VEVENT
* Missions vs. RoughRiders
<2018-08-24 Fri 19:05-22:05>
:PROPERTIES:
:ID:       _Ai0FL30Z-3CGzlX9tdvt1b5@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Missions vs. RoughRiders Missions vs. RoughRiders

Follow on MiLB First Pitch  https //stza.co/+wMy7-2p

Shop  https //stza.co/+wMy7-6

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Missions vs. RoughRiders
END:VALARM
DTSTART:20180825T000500Z
DTEND:20180825T030500Z
UID:_Ai0FL30Z-3CGzlX9tdvt1b5@stanza.co
SUMMARY:Missions vs. RoughRiders
DESCRIPTION:Missions vs. RoughRiders\n\nFollow on MiLB First Pitch: https://stza.co/+wMy7-2p\n\nShop: https://stza.co/+wMy7-6\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144556Z
LAST-MODIFIED:20180213T144556Z
TRANSP:OPAQUE
END:VEVENT
* Missions @ Hooks
<2018-08-25 Sat 19:05-22:05>
:PROPERTIES:
:ID:       hlMolLgzJHKlr0zr_aubmPJt@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Missions @ Hooks Missions @ Hooks

Follow on MiLB First Pitch  https //stza.co/+xzIl-K

Shop  https //stza.co/+xzIl-3c

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Missions @ Hooks
END:VALARM
DTSTART:20180826T000500Z
DTEND:20180826T030500Z
UID:hlMolLgzJHKlr0zr_aubmPJt@stanza.co
SUMMARY:Missions @ Hooks
DESCRIPTION:Missions @ Hooks\n\nFollow on MiLB First Pitch: https://stza.co/+xzIl-K\n\nShop: https://stza.co/+xzIl-3c\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144556Z
LAST-MODIFIED:20180213T144556Z
TRANSP:OPAQUE
END:VEVENT
* Missions @ Hooks
<2018-08-26 Sun 18:05-21:05>
:PROPERTIES:
:ID:       g-2gVxWDKIsYDewpAHFL4Cos@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Missions @ Hooks Missions @ Hooks

Follow on MiLB First Pitch  https //stza.co/+xzIm-3f

Shop  https //stza.co/+xzIm-2I

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Missions @ Hooks
END:VALARM
DTSTART:20180826T230500Z
DTEND:20180827T020500Z
UID:g-2gVxWDKIsYDewpAHFL4Cos@stanza.co
SUMMARY:Missions @ Hooks
DESCRIPTION:Missions @ Hooks\n\nFollow on MiLB First Pitch: https://stza.co/+xzIm-3f\n\nShop: https://stza.co/+xzIm-2I\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144556Z
LAST-MODIFIED:20180213T144556Z
TRANSP:OPAQUE
END:VEVENT
* Missions @ Hooks
<2018-08-27 Mon 19:05-22:05>
:PROPERTIES:
:ID:       GUJIcUzRY8oy9zvW6YTcSjL3@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Missions @ Hooks Missions @ Hooks

Follow on MiLB First Pitch  https //stza.co/+xzIn-2M

Shop  https //stza.co/+xzIn-3N

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Missions @ Hooks
END:VALARM
DTSTART:20180828T000500Z
DTEND:20180828T030500Z
UID:GUJIcUzRY8oy9zvW6YTcSjL3@stanza.co
SUMMARY:Missions @ Hooks
DESCRIPTION:Missions @ Hooks\n\nFollow on MiLB First Pitch: https://stza.co/+xzIn-2M\n\nShop: https://stza.co/+xzIn-3N\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144556Z
LAST-MODIFIED:20180213T144556Z
TRANSP:OPAQUE
END:VEVENT
* Missions @ RockHounds
<2018-08-28 Tue 18:30-21:30>
:PROPERTIES:
:ID:       1bfZwSykoTi7wk3_jE92BC8Q@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Missions @ RockHounds Missions @ RockHounds

Follow on MiLB First Pitch  https //stza.co/+wX5s-2p

Shop  https //stza.co/+wX5s-3l

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Missions @ RockHounds
END:VALARM
DTSTART:20180828T233000Z
DTEND:20180829T023000Z
UID:1bfZwSykoTi7wk3_jE92BC8Q@stanza.co
SUMMARY:Missions @ RockHounds
DESCRIPTION:Missions @ RockHounds\n\nFollow on MiLB First Pitch: https://stza.co/+wX5s-2p\n\nShop: https://stza.co/+wX5s-3l\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144556Z
LAST-MODIFIED:20180213T144556Z
TRANSP:OPAQUE
END:VEVENT
* Missions @ RockHounds
<2018-08-29 Wed 18:30-21:30>
:PROPERTIES:
:ID:       MNYaXRBNjI7IE0sb8iv5uAib@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Missions @ RockHounds Missions @ RockHounds

Follow on MiLB First Pitch  https //stza.co/+wX5t-3K

Shop  https //stza.co/+wX5t-d

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Missions @ RockHounds
END:VALARM
DTSTART:20180829T233000Z
DTEND:20180830T023000Z
UID:MNYaXRBNjI7IE0sb8iv5uAib@stanza.co
SUMMARY:Missions @ RockHounds
DESCRIPTION:Missions @ RockHounds\n\nFollow on MiLB First Pitch: https://stza.co/+wX5t-3K\n\nShop: https://stza.co/+wX5t-d\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144556Z
LAST-MODIFIED:20180213T144556Z
TRANSP:OPAQUE
END:VEVENT
* Missions @ RockHounds
<2018-08-30 Thu 19:00-22:00>
:PROPERTIES:
:ID:       xBNS-yd-O7gdD-tpQPt0muHm@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Missions @ RockHounds Missions @ RockHounds

Follow on MiLB First Pitch  https //stza.co/+wX5u-20

Shop  https //stza.co/+wX5u-30

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Missions @ RockHounds
END:VALARM
DTSTART:20180831T000000Z
DTEND:20180831T030000Z
UID:xBNS-yd-O7gdD-tpQPt0muHm@stanza.co
SUMMARY:Missions @ RockHounds
DESCRIPTION:Missions @ RockHounds\n\nFollow on MiLB First Pitch: https://stza.co/+wX5u-20\n\nShop: https://stza.co/+wX5u-30\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144556Z
LAST-MODIFIED:20180213T144556Z
TRANSP:OPAQUE
END:VEVENT
* Missions @ RockHounds
<2018-08-31 Fri 19:00-22:00>
:PROPERTIES:
:ID:       iDXuQD4oPs1QnUmJ_ACsIwio@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Missions @ RockHounds Missions @ RockHounds

Follow on MiLB First Pitch  https //stza.co/+wX5v-3v

Shop  https //stza.co/+wX5v-I

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Missions @ RockHounds
END:VALARM
DTSTART:20180901T000000Z
DTEND:20180901T030000Z
UID:iDXuQD4oPs1QnUmJ_ACsIwio@stanza.co
SUMMARY:Missions @ RockHounds
DESCRIPTION:Missions @ RockHounds\n\nFollow on MiLB First Pitch: https://stza.co/+wX5v-3v\n\nShop: https://stza.co/+wX5v-I\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144556Z
LAST-MODIFIED:20180213T144556Z
TRANSP:OPAQUE
END:VEVENT
* Missions vs. Hooks
<2018-09-01 Sat 19:05-22:05>
:PROPERTIES:
:ID:       5yXx80AAZutfdkpgkLnlMikC@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Missions vs. Hooks Missions vs. Hooks

Follow on MiLB First Pitch  https //stza.co/+wMyb-1O

Shop  https //stza.co/+wMyb-14

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Missions vs. Hooks
END:VALARM
DTSTART:20180902T000500Z
DTEND:20180902T030500Z
UID:5yXx80AAZutfdkpgkLnlMikC@stanza.co
SUMMARY:Missions vs. Hooks
DESCRIPTION:Missions vs. Hooks\n\nFollow on MiLB First Pitch: https://stza.co/+wMyb-1O\n\nShop: https://stza.co/+wMyb-14\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144556Z
LAST-MODIFIED:20180213T144556Z
TRANSP:OPAQUE
END:VEVENT
* Missions vs. Hooks
<2018-09-02 Sun 18:05-21:05>
:PROPERTIES:
:ID:       G1ff3ZxpqXwvVlfa5KWoFisX@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Missions vs. Hooks Missions vs. Hooks

Follow on MiLB First Pitch  https //stza.co/+wMyc-2i

Shop  https //stza.co/+wMyc-Y

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Missions vs. Hooks
END:VALARM
DTSTART:20180902T230500Z
DTEND:20180903T020500Z
UID:G1ff3ZxpqXwvVlfa5KWoFisX@stanza.co
SUMMARY:Missions vs. Hooks
DESCRIPTION:Missions vs. Hooks\n\nFollow on MiLB First Pitch: https://stza.co/+wMyc-2i\n\nShop: https://stza.co/+wMyc-Y\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144556Z
LAST-MODIFIED:20180213T144556Z
TRANSP:OPAQUE
END:VEVENT
* Missions vs. Hooks
<2018-09-03 Mon 14:05-17:05>
:PROPERTIES:
:ID:       XweyTfMQ196GPo97plbie9Z0@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Missions vs. Hooks Missions vs. Hooks

Follow on MiLB First Pitch  https //stza.co/+wMyf-1c

Shop  https //stza.co/+wMyf-3a

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Missions vs. Hooks
END:VALARM
DTSTART:20180903T190500Z
DTEND:20180903T220500Z
UID:XweyTfMQ196GPo97plbie9Z0@stanza.co
SUMMARY:Missions vs. Hooks
DESCRIPTION:Missions vs. Hooks\n\nFollow on MiLB First Pitch: https://stza.co/+wMyf-1c\n\nShop: https://stza.co/+wMyf-3a\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144556Z
LAST-MODIFIED:20180213T144556Z
TRANSP:OPAQUE
END:VEVENT
