#+TITLE:       Main Google calendar entries
#+AUTHOR:      Eric S Fraga
#+EMAIL:       e.fraga@ucl.ac.uk
#+DESCRIPTION: converted using the ical2org awk script
#+CATEGORY:    google
#+STARTUP:     hidestars
#+STARTUP:     overview

* COMMENT original iCal preamble

* Fireflies vs. GreenJackets
<2018-04-05 Thu 18:05-21:05>
:PROPERTIES:
:ID:       -N6c7jecgTBfONaLXRu7fq7V@stanza.co
:LOCATION: Thirsty Thursday 
:STATUS:   CONFIRMED
:END:

Fireflies vs. GreenJackets Enjoy half priced beer and fountain drinks! 

Never miss a game- get your 2018 magnet schedule! 

Follow on MiLB First Pitch  https //stza.co/+xBMW-11

Shop  https //stza.co/+xBMW-2U

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Fireflies vs. GreenJackets
END:VALARM
DTSTART:20180405T230500Z
DTEND:20180406T020500Z
UID:-N6c7jecgTBfONaLXRu7fq7V@stanza.co
SUMMARY:Fireflies vs. GreenJackets
DESCRIPTION:Enjoy half priced beer and fountain drinks! \n\nNever miss a game- get your 2018 magnet schedule! \n\nFollow on MiLB First Pitch: https://stza.co/+xBMW-11\n\nShop: https://stza.co/+xBMW-2U\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Thirsty Thursday 
STATUS:CONFIRMED
CREATED:20180213T144515Z
LAST-MODIFIED:20180213T144515Z
TRANSP:OPAQUE
END:VEVENT
* Fireflies vs. GreenJackets
<2018-04-06 Fri 18:05-21:05>
:PROPERTIES:
:ID:       BwH1HeqB0muWjg3gi4gKv67y@stanza.co
:LOCATION: Firework Friday's!
:STATUS:   CONFIRMED
:END:

Fireflies vs. GreenJackets Enjoy fireworks after the game with your friends and family! It will be a blast! 

Never miss a game- get your 2018 magnet schedule! 

Follow on MiLB First Pitch  https //stza.co/+xBM_-3f

Shop  https //stza.co/+xBM_-2h

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Fireflies vs. GreenJackets
END:VALARM
DTSTART:20180406T230500Z
DTEND:20180407T020500Z
UID:BwH1HeqB0muWjg3gi4gKv67y@stanza.co
SUMMARY:Fireflies vs. GreenJackets
DESCRIPTION:Enjoy fireworks after the game with your friends and family! It will be a blast! \n\nNever miss a game- get your 2018 magnet schedule! \n\nFollow on MiLB First Pitch: https://stza.co/+xBM_-3f\n\nShop: https://stza.co/+xBM_-2h\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Firework Friday's!
STATUS:CONFIRMED
CREATED:20180213T144515Z
LAST-MODIFIED:20180213T144515Z
TRANSP:OPAQUE
END:VEVENT
* Fireflies vs. GreenJackets
<2018-04-07 Sat 17:05-20:05>
:PROPERTIES:
:ID:       2G-ktUxRL08ZCCAsH_lQCzKP@stanza.co
:LOCATION: Magnet Schedule Giveaway 
:STATUS:   CONFIRMED
:END:

Fireflies vs. GreenJackets Never miss a game- get your 2018 magnet schedule! 

Relive the summer of 1962 with Smalls and the Sandlot gang

Follow on MiLB First Pitch  https //stza.co/+xBN2-29

Shop  https //stza.co/+xBN2-1u

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Fireflies vs. GreenJackets
END:VALARM
DTSTART:20180407T220500Z
DTEND:20180408T010500Z
UID:2G-ktUxRL08ZCCAsH_lQCzKP@stanza.co
SUMMARY:Fireflies vs. GreenJackets
DESCRIPTION:Never miss a game- get your 2018 magnet schedule! \n\nRelive the summer of 1962 with Smalls and the Sandlot gang\n\nFollow on MiLB First Pitch: https://stza.co/+xBN2-29\n\nShop: https://stza.co/+xBN2-1u\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Magnet Schedule Giveaway 
STATUS:CONFIRMED
CREATED:20180213T144515Z
LAST-MODIFIED:20180213T144515Z
TRANSP:OPAQUE
END:VEVENT
* Fireflies vs. GreenJackets
<2018-04-08 Sun 13:05-16:05>
:PROPERTIES:
:ID:       YN2AzgSOOKADsvJm2S4jbSp0@stanza.co
:LOCATION: Sunday Splash Day's and Autographs
:STATUS:   CONFIRMED
:END:

Fireflies vs. GreenJackets Come get your favorite player's autograph and cool down in the Splash Zone during the game! 

Never miss a game- get your 2018 magnet schedule! 

Follow on MiLB First Pitch  https //stza.co/+xBN8-2e

Shop  https //stza.co/+xBN8-2F

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Fireflies vs. GreenJackets
END:VALARM
DTSTART:20180408T180500Z
DTEND:20180408T210500Z
UID:YN2AzgSOOKADsvJm2S4jbSp0@stanza.co
SUMMARY:Fireflies vs. GreenJackets
DESCRIPTION:Come get your favorite player's autograph and cool down in the Splash Zone during the game! \n\nNever miss a game- get your 2018 magnet schedule! \n\nFollow on MiLB First Pitch: https://stza.co/+xBN8-2e\n\nShop: https://stza.co/+xBN8-2F\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Sunday Splash Day's and Autographs
STATUS:CONFIRMED
CREATED:20180213T144515Z
LAST-MODIFIED:20180213T144515Z
TRANSP:OPAQUE
END:VEVENT
* Fireflies vs. Suns
<2018-04-09 Mon 18:05-21:05>
:PROPERTIES:
:ID:       N6h5tfIPQPqWJnDalr7g2N4J@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Fireflies vs. Suns Fireflies vs. Suns

Follow on MiLB First Pitch  https //stza.co/+xBNb-F

Shop  https //stza.co/+xBNb-2G

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Fireflies vs. Suns
END:VALARM
DTSTART:20180409T230500Z
DTEND:20180410T020500Z
UID:N6h5tfIPQPqWJnDalr7g2N4J@stanza.co
SUMMARY:Fireflies vs. Suns
DESCRIPTION:Fireflies vs. Suns\n\nFollow on MiLB First Pitch: https://stza.co/+xBNb-F\n\nShop: https://stza.co/+xBNb-2G\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144515Z
LAST-MODIFIED:20180213T144515Z
TRANSP:OPAQUE
END:VEVENT
* Fireflies vs. Suns
<2018-04-10 Tue 18:05-21:05>
:PROPERTIES:
:ID:       0s_ug17parwtvy6P8pvtY0m_@stanza.co
:LOCATION: $2 Tuesday!
:STATUS:   CONFIRMED
:END:

Fireflies vs. Suns Enjoy $2.00 hotdogs, fountain drinks and popcorn all game! 

Follow on MiLB First Pitch  https //stza.co/+xBNf-j

Shop  https //stza.co/+xBNf-3U

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Fireflies vs. Suns
END:VALARM
DTSTART:20180410T230500Z
DTEND:20180411T020500Z
UID:0s_ug17parwtvy6P8pvtY0m_@stanza.co
SUMMARY:Fireflies vs. Suns
DESCRIPTION:Enjoy $2.00 hotdogs, fountain drinks and popcorn all game! \n\nFollow on MiLB First Pitch: https://stza.co/+xBNf-j\n\nShop: https://stza.co/+xBNf-3U\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:$2 Tuesday!
STATUS:CONFIRMED
CREATED:20180213T144515Z
LAST-MODIFIED:20180213T144515Z
TRANSP:OPAQUE
END:VEVENT
* Fireflies vs. Suns
<2018-04-11 Wed 18:05-21:05>
:PROPERTIES:
:ID:       fXlQ1ueo0PbWWF1x5oYP4nxY@stanza.co
:LOCATION: Wag-Along Wednesday
:STATUS:   CONFIRMED
:END:

Fireflies vs. Suns Bring your dog to the game with you! 

Follow on MiLB First Pitch  https //stza.co/+xBNl-1$

Shop  https //stza.co/+xBNl-3q

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Fireflies vs. Suns
END:VALARM
DTSTART:20180411T230500Z
DTEND:20180412T020500Z
UID:fXlQ1ueo0PbWWF1x5oYP4nxY@stanza.co
SUMMARY:Fireflies vs. Suns
DESCRIPTION:Bring your dog to the game with you! \n\nFollow on MiLB First Pitch: https://stza.co/+xBNl-1$\n\nShop: https://stza.co/+xBNl-3q\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Wag-Along Wednesday
STATUS:CONFIRMED
CREATED:20180213T144515Z
LAST-MODIFIED:20180213T144515Z
TRANSP:OPAQUE
END:VEVENT
* Fireflies @ Tourists
<2018-04-12 Thu 18:05-21:05>
:PROPERTIES:
:ID:       GiOH4CWoEU4xLrtAw5QYvnli@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Fireflies @ Tourists Fireflies @ Tourists

Follow on MiLB First Pitch  https //stza.co/+vNCp-3k

Shop  https //stza.co/+vNCp-3G

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Fireflies @ Tourists
END:VALARM
DTSTART:20180412T230500Z
DTEND:20180413T020500Z
UID:GiOH4CWoEU4xLrtAw5QYvnli@stanza.co
SUMMARY:Fireflies @ Tourists
DESCRIPTION:Fireflies @ Tourists\n\nFollow on MiLB First Pitch: https://stza.co/+vNCp-3k\n\nShop: https://stza.co/+vNCp-3G\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144515Z
LAST-MODIFIED:20180213T144515Z
TRANSP:OPAQUE
END:VEVENT
* Fireflies @ Tourists
<2018-04-13 Fri 18:05-21:05>
:PROPERTIES:
:ID:       uUakdxMBo8YFfKhZkWu7Uhyx@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Fireflies @ Tourists Fireflies @ Tourists

Follow on MiLB First Pitch  https //stza.co/+vNCq-3M

Shop  https //stza.co/+vNCq-2s

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Fireflies @ Tourists
END:VALARM
DTSTART:20180413T230500Z
DTEND:20180414T020500Z
UID:uUakdxMBo8YFfKhZkWu7Uhyx@stanza.co
SUMMARY:Fireflies @ Tourists
DESCRIPTION:Fireflies @ Tourists\n\nFollow on MiLB First Pitch: https://stza.co/+vNCq-3M\n\nShop: https://stza.co/+vNCq-2s\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144515Z
LAST-MODIFIED:20180213T144515Z
TRANSP:OPAQUE
END:VEVENT
* Fireflies @ Tourists
<2018-04-14 Sat 17:05-20:05>
:PROPERTIES:
:ID:       qfUJQSa-uIrfT-jivCO56Ymo@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Fireflies @ Tourists Fireflies @ Tourists

Follow on MiLB First Pitch  https //stza.co/+vNCr-2q

Shop  https //stza.co/+vNCr-8

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Fireflies @ Tourists
END:VALARM
DTSTART:20180414T220500Z
DTEND:20180415T010500Z
UID:qfUJQSa-uIrfT-jivCO56Ymo@stanza.co
SUMMARY:Fireflies @ Tourists
DESCRIPTION:Fireflies @ Tourists\n\nFollow on MiLB First Pitch: https://stza.co/+vNCr-2q\n\nShop: https://stza.co/+vNCr-8\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144515Z
LAST-MODIFIED:20180213T144515Z
TRANSP:OPAQUE
END:VEVENT
* Fireflies @ Tourists
<2018-04-15 Sun 13:05-16:05>
:PROPERTIES:
:ID:       OEto1uGvFh_O7REexkGAu4dX@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Fireflies @ Tourists Fireflies @ Tourists

Follow on MiLB First Pitch  https //stza.co/+vNCs-C

Shop  https //stza.co/+vNCs-2O

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Fireflies @ Tourists
END:VALARM
DTSTART:20180415T180500Z
DTEND:20180415T210500Z
UID:OEto1uGvFh_O7REexkGAu4dX@stanza.co
SUMMARY:Fireflies @ Tourists
DESCRIPTION:Fireflies @ Tourists\n\nFollow on MiLB First Pitch: https://stza.co/+vNCs-C\n\nShop: https://stza.co/+vNCs-2O\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144515Z
LAST-MODIFIED:20180213T144515Z
TRANSP:OPAQUE
END:VEVENT
* Fireflies @ Drive
<2018-04-16 Mon 18:05-21:05>
:PROPERTIES:
:ID:       JjKlhVpSGzYAVacjswe13opk@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Fireflies @ Drive Fireflies @ Drive

Follow on MiLB First Pitch  https //stza.co/+xEZR-f

Shop  https //stza.co/+xEZR-2H

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Fireflies @ Drive
END:VALARM
DTSTART:20180416T230500Z
DTEND:20180417T020500Z
UID:JjKlhVpSGzYAVacjswe13opk@stanza.co
SUMMARY:Fireflies @ Drive
DESCRIPTION:Fireflies @ Drive\n\nFollow on MiLB First Pitch: https://stza.co/+xEZR-f\n\nShop: https://stza.co/+xEZR-2H\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144515Z
LAST-MODIFIED:20180213T144515Z
TRANSP:OPAQUE
END:VEVENT
* Fireflies @ Drive
<2018-04-17 Tue 18:05-21:05>
:PROPERTIES:
:ID:       M-IoZeL-dy0KDKLBMlI3z0Ze@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Fireflies @ Drive Fireflies @ Drive

Follow on MiLB First Pitch  https //stza.co/+xEZS-3G

Shop  https //stza.co/+xEZS-3c

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Fireflies @ Drive
END:VALARM
DTSTART:20180417T230500Z
DTEND:20180418T020500Z
UID:M-IoZeL-dy0KDKLBMlI3z0Ze@stanza.co
SUMMARY:Fireflies @ Drive
DESCRIPTION:Fireflies @ Drive\n\nFollow on MiLB First Pitch: https://stza.co/+xEZS-3G\n\nShop: https://stza.co/+xEZS-3c\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144515Z
LAST-MODIFIED:20180213T144515Z
TRANSP:OPAQUE
END:VEVENT
* Fireflies @ Drive
<2018-04-18 Wed 18:05-21:05>
:PROPERTIES:
:ID:       q4F3U23n7A--QdNJH64XDLCs@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Fireflies @ Drive Fireflies @ Drive

Follow on MiLB First Pitch  https //stza.co/+xEZT-2W

Shop  https //stza.co/+xEZT-1Y

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Fireflies @ Drive
END:VALARM
DTSTART:20180418T230500Z
DTEND:20180419T020500Z
UID:q4F3U23n7A--QdNJH64XDLCs@stanza.co
SUMMARY:Fireflies @ Drive
DESCRIPTION:Fireflies @ Drive\n\nFollow on MiLB First Pitch: https://stza.co/+xEZT-2W\n\nShop: https://stza.co/+xEZT-1Y\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144515Z
LAST-MODIFIED:20180213T144515Z
TRANSP:OPAQUE
END:VEVENT
* Fireflies vs. Crawdads
<2018-04-19 Thu 18:05-21:05>
:PROPERTIES:
:ID:       Nb5_uX1T5ZbRYvcl7g1h6bH6@stanza.co
:LOCATION: Thirsty Thursday 
:STATUS:   CONFIRMED
:END:

Fireflies vs. Crawdads Enjoy half priced beer and fountain drinks! 

Follow on MiLB First Pitch  https //stza.co/+xBNq-2Z

Shop  https //stza.co/+xBNq-1k

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Fireflies vs. Crawdads
END:VALARM
DTSTART:20180419T230500Z
DTEND:20180420T020500Z
UID:Nb5_uX1T5ZbRYvcl7g1h6bH6@stanza.co
SUMMARY:Fireflies vs. Crawdads
DESCRIPTION:Enjoy half priced beer and fountain drinks! \n\nFollow on MiLB First Pitch: https://stza.co/+xBNq-2Z\n\nShop: https://stza.co/+xBNq-1k\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Thirsty Thursday 
STATUS:CONFIRMED
CREATED:20180213T144515Z
LAST-MODIFIED:20180213T144515Z
TRANSP:OPAQUE
END:VEVENT
* Fireflies vs. Crawdads
<2018-04-20 Fri 18:05-21:05>
:PROPERTIES:
:ID:       uiLOkNulfma1TpkOFLY4Q9P-@stanza.co
:LOCATION: Firework Friday's!
:STATUS:   CONFIRMED
:END:

Fireflies vs. Crawdads Enjoy fireworks after the game with your friends and family! It will be a blast! 

Enjoy one of the most famous traveling entertainment acts in sports, and see baseball legends reimagined! 

Follow on MiLB First Pitch  https //stza.co/+xBNs-z

Shop  https //stza.co/+xBNs-3T

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Fireflies vs. Crawdads
END:VALARM
DTSTART:20180420T230500Z
DTEND:20180421T020500Z
UID:uiLOkNulfma1TpkOFLY4Q9P-@stanza.co
SUMMARY:Fireflies vs. Crawdads
DESCRIPTION:Enjoy fireworks after the game with your friends and family! It will be a blast! \n\nEnjoy one of the most famous traveling entertainment acts in sports, and see baseball legends reimagined! \n\nFollow on MiLB First Pitch: https://stza.co/+xBNs-z\n\nShop: https://stza.co/+xBNs-3T\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Firework Friday's!
STATUS:CONFIRMED
CREATED:20180213T144515Z
LAST-MODIFIED:20180213T144515Z
TRANSP:OPAQUE
END:VEVENT
* Fireflies vs. Crawdads
<2018-04-21 Sat 17:05-20:05>
:PROPERTIES:
:ID:       nEGuIFl3wYgLLFh2Ygai5S2K@stanza.co
:LOCATION: Halfway to Halloween
:STATUS:   CONFIRMED
:END:

Fireflies vs. Crawdads Break out your costume from this year or get a head start for next year as the Fireflies present a spooky evening at the ballpark 

Follow on MiLB First Pitch  https //stza.co/+xBNu-2K

Shop  https //stza.co/+xBNu-1U

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Fireflies vs. Crawdads
END:VALARM
DTSTART:20180421T220500Z
DTEND:20180422T010500Z
UID:nEGuIFl3wYgLLFh2Ygai5S2K@stanza.co
SUMMARY:Fireflies vs. Crawdads
DESCRIPTION:Break out your costume from this year or get a head start for next year as the Fireflies present a spooky evening at the ballpark \n\nFollow on MiLB First Pitch: https://stza.co/+xBNu-2K\n\nShop: https://stza.co/+xBNu-1U\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Halfway to Halloween
STATUS:CONFIRMED
CREATED:20180213T144515Z
LAST-MODIFIED:20180213T144515Z
TRANSP:OPAQUE
END:VEVENT
* Fireflies vs. Crawdads
<2018-04-22 Sun 13:05-16:05>
:PROPERTIES:
:ID:       D_krtGwzHjbNJzzSSYqmppB_@stanza.co
:LOCATION: Sunday Splash Day's and Autographs
:STATUS:   CONFIRMED
:END:

Fireflies vs. Crawdads Come get your favorite player's autograph and cool down in the Splash Zone during the game! 

Follow on MiLB First Pitch  https //stza.co/+xBNw-1Q

Shop  https //stza.co/+xBNw-f

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Fireflies vs. Crawdads
END:VALARM
DTSTART:20180422T180500Z
DTEND:20180422T210500Z
UID:D_krtGwzHjbNJzzSSYqmppB_@stanza.co
SUMMARY:Fireflies vs. Crawdads
DESCRIPTION:Come get your favorite player's autograph and cool down in the Splash Zone during the game! \n\nFollow on MiLB First Pitch: https://stza.co/+xBNw-1Q\n\nShop: https://stza.co/+xBNw-f\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Sunday Splash Day's and Autographs
STATUS:CONFIRMED
CREATED:20180213T144515Z
LAST-MODIFIED:20180213T144515Z
TRANSP:OPAQUE
END:VEVENT
* Fireflies @ RiverDogs
<2018-04-23 Mon 18:05-21:05>
:PROPERTIES:
:ID:       Ew40H1k4ZfxKsgUCD3y8wwNx@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Fireflies @ RiverDogs Fireflies @ RiverDogs

Follow on MiLB First Pitch  https //stza.co/+vNCL-33

Shop  https //stza.co/+vNCL-2k

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Fireflies @ RiverDogs
END:VALARM
DTSTART:20180423T230500Z
DTEND:20180424T020500Z
UID:Ew40H1k4ZfxKsgUCD3y8wwNx@stanza.co
SUMMARY:Fireflies @ RiverDogs
DESCRIPTION:Fireflies @ RiverDogs\n\nFollow on MiLB First Pitch: https://stza.co/+vNCL-33\n\nShop: https://stza.co/+vNCL-2k\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144515Z
LAST-MODIFIED:20180213T144515Z
TRANSP:OPAQUE
END:VEVENT
* Fireflies @ RiverDogs
<2018-04-24 Tue 18:05-21:05>
:PROPERTIES:
:ID:       JbmbSXBEpX5IkQ_tPMhWhKPt@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Fireflies @ RiverDogs Fireflies @ RiverDogs

Follow on MiLB First Pitch  https //stza.co/+vNCM-1w

Shop  https //stza.co/+vNCM-2f

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Fireflies @ RiverDogs
END:VALARM
DTSTART:20180424T230500Z
DTEND:20180425T020500Z
UID:JbmbSXBEpX5IkQ_tPMhWhKPt@stanza.co
SUMMARY:Fireflies @ RiverDogs
DESCRIPTION:Fireflies @ RiverDogs\n\nFollow on MiLB First Pitch: https://stza.co/+vNCM-1w\n\nShop: https://stza.co/+vNCM-2f\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144515Z
LAST-MODIFIED:20180213T144515Z
TRANSP:OPAQUE
END:VEVENT
* Fireflies @ RiverDogs
<2018-04-25 Wed 18:05-21:05>
:PROPERTIES:
:ID:       LiXgKBcWz1uf3-deEjvZGJZc@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Fireflies @ RiverDogs Fireflies @ RiverDogs

Follow on MiLB First Pitch  https //stza.co/+vNCN-3o

Shop  https //stza.co/+vNCN-1i

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Fireflies @ RiverDogs
END:VALARM
DTSTART:20180425T230500Z
DTEND:20180426T020500Z
UID:LiXgKBcWz1uf3-deEjvZGJZc@stanza.co
SUMMARY:Fireflies @ RiverDogs
DESCRIPTION:Fireflies @ RiverDogs\n\nFollow on MiLB First Pitch: https://stza.co/+vNCN-3o\n\nShop: https://stza.co/+vNCN-1i\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144515Z
LAST-MODIFIED:20180213T144515Z
TRANSP:OPAQUE
END:VEVENT
* Fireflies @ RiverDogs
<2018-04-26 Thu 18:05-21:05>
:PROPERTIES:
:ID:       emNhFZWqdyWCrHsVsFPJD5hX@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Fireflies @ RiverDogs Fireflies @ RiverDogs

Follow on MiLB First Pitch  https //stza.co/+vNCO-M

Shop  https //stza.co/+vNCO-S

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Fireflies @ RiverDogs
END:VALARM
DTSTART:20180426T230500Z
DTEND:20180427T020500Z
UID:emNhFZWqdyWCrHsVsFPJD5hX@stanza.co
SUMMARY:Fireflies @ RiverDogs
DESCRIPTION:Fireflies @ RiverDogs\n\nFollow on MiLB First Pitch: https://stza.co/+vNCO-M\n\nShop: https://stza.co/+vNCO-S\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144515Z
LAST-MODIFIED:20180213T144515Z
TRANSP:OPAQUE
END:VEVENT
* Fireflies @ GreenJackets
<2018-04-27 Fri 18:05-21:05>
:PROPERTIES:
:ID:       2gTTB7VZUdPBKy1f51Sr-r2z@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Fireflies @ GreenJackets Fireflies @ GreenJackets

Follow on MiLB First Pitch  https //stza.co/+xBMC-2I

Shop  https //stza.co/+xBMC-P

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Fireflies @ GreenJackets
END:VALARM
DTSTART:20180427T230500Z
DTEND:20180428T020500Z
UID:2gTTB7VZUdPBKy1f51Sr-r2z@stanza.co
SUMMARY:Fireflies @ GreenJackets
DESCRIPTION:Fireflies @ GreenJackets\n\nFollow on MiLB First Pitch: https://stza.co/+xBMC-2I\n\nShop: https://stza.co/+xBMC-P\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144515Z
LAST-MODIFIED:20180213T144515Z
TRANSP:OPAQUE
END:VEVENT
* Fireflies @ GreenJackets
<2018-04-28 Sat 17:05-20:05>
:PROPERTIES:
:ID:       QtPtvEUFkd4swFCfswRf3Tl_@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Fireflies @ GreenJackets Fireflies @ GreenJackets

Follow on MiLB First Pitch  https //stza.co/+xBMD-22

Shop  https //stza.co/+xBMD-1f

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Fireflies @ GreenJackets
END:VALARM
DTSTART:20180428T220500Z
DTEND:20180429T010500Z
UID:QtPtvEUFkd4swFCfswRf3Tl_@stanza.co
SUMMARY:Fireflies @ GreenJackets
DESCRIPTION:Fireflies @ GreenJackets\n\nFollow on MiLB First Pitch: https://stza.co/+xBMD-22\n\nShop: https://stza.co/+xBMD-1f\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144515Z
LAST-MODIFIED:20180213T144515Z
TRANSP:OPAQUE
END:VEVENT
* Fireflies @ GreenJackets
<2018-04-29 Sun 13:05-16:05>
:PROPERTIES:
:ID:       jRqRiyko8Rf9N0nTnNm1WjfL@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Fireflies @ GreenJackets Fireflies @ GreenJackets

Follow on MiLB First Pitch  https //stza.co/+xBME-w

Shop  https //stza.co/+xBME-2B

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Fireflies @ GreenJackets
END:VALARM
DTSTART:20180429T180500Z
DTEND:20180429T210500Z
UID:jRqRiyko8Rf9N0nTnNm1WjfL@stanza.co
SUMMARY:Fireflies @ GreenJackets
DESCRIPTION:Fireflies @ GreenJackets\n\nFollow on MiLB First Pitch: https://stza.co/+xBME-w\n\nShop: https://stza.co/+xBME-2B\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144515Z
LAST-MODIFIED:20180213T144515Z
TRANSP:OPAQUE
END:VEVENT
* Fireflies vs. Legends
<2018-05-01 Tue 18:05-21:05>
:PROPERTIES:
:ID:       aCksJpN8zDhTsV1BFCOVuOo4@stanza.co
:LOCATION: $2 Tuesday!
:STATUS:   CONFIRMED
:END:

Fireflies vs. Legends Enjoy $2.00 hotdogs, fountain drinks and popcorn all game! 

Follow on MiLB First Pitch  https //stza.co/+xBNy-Z

Shop  https //stza.co/+xBNy-1d

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Fireflies vs. Legends
END:VALARM
DTSTART:20180501T230500Z
DTEND:20180502T020500Z
UID:aCksJpN8zDhTsV1BFCOVuOo4@stanza.co
SUMMARY:Fireflies vs. Legends
DESCRIPTION:Enjoy $2.00 hotdogs, fountain drinks and popcorn all game! \n\nFollow on MiLB First Pitch: https://stza.co/+xBNy-Z\n\nShop: https://stza.co/+xBNy-1d\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:$2 Tuesday!
STATUS:CONFIRMED
CREATED:20180213T144515Z
LAST-MODIFIED:20180213T144515Z
TRANSP:OPAQUE
END:VEVENT
* Fireflies vs. Legends
<2018-05-02 Wed 10:05-13:05>
:PROPERTIES:
:ID:       pgV22SdhBStT7rl6zRNXW1Na@stanza.co
:LOCATION: Wag-Along Wednesday
:STATUS:   CONFIRMED
:END:

Fireflies vs. Legends Bring your dog to the game with you! 

Follow on MiLB First Pitch  https //stza.co/+xBNB-2S

Shop  https //stza.co/+xBNB-24

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Fireflies vs. Legends
END:VALARM
DTSTART:20180502T150500Z
DTEND:20180502T180500Z
UID:pgV22SdhBStT7rl6zRNXW1Na@stanza.co
SUMMARY:Fireflies vs. Legends
DESCRIPTION:Bring your dog to the game with you! \n\nFollow on MiLB First Pitch: https://stza.co/+xBNB-2S\n\nShop: https://stza.co/+xBNB-24\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Wag-Along Wednesday
STATUS:CONFIRMED
CREATED:20180213T144515Z
LAST-MODIFIED:20180213T144515Z
TRANSP:OPAQUE
END:VEVENT
* Fireflies vs. Legends
<2018-05-03 Thu 18:05-21:05>
:PROPERTIES:
:ID:       3Xb5dizVhUPwvV-qxGLoo6Vr@stanza.co
:LOCATION: Thirsty Thursday 
:STATUS:   CONFIRMED
:END:

Fireflies vs. Legends Enjoy half priced beer and fountain drinks! 

Come out and honor our service men and women for all that they have done for our country! 

Follow on MiLB First Pitch  https //stza.co/+xBNF-M

Shop  https //stza.co/+xBNF-3G

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Fireflies vs. Legends
END:VALARM
DTSTART:20180503T230500Z
DTEND:20180504T020500Z
UID:3Xb5dizVhUPwvV-qxGLoo6Vr@stanza.co
SUMMARY:Fireflies vs. Legends
DESCRIPTION:Enjoy half priced beer and fountain drinks! \n\nCome out and honor our service men and women for all that they have done for our country! \n\nFollow on MiLB First Pitch: https://stza.co/+xBNF-M\n\nShop: https://stza.co/+xBNF-3G\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Thirsty Thursday 
STATUS:CONFIRMED
CREATED:20180213T144515Z
LAST-MODIFIED:20180213T144515Z
TRANSP:OPAQUE
END:VEVENT
* Fireflies vs. BlueClaws
<2018-05-04 Fri 18:05-21:05>
:PROPERTIES:
:ID:       ejfvniVXHBf97YHAcs9CL7UQ@stanza.co
:LOCATION: Firework Friday's!
:STATUS:   CONFIRMED
:END:

Fireflies vs. BlueClaws Enjoy fireworks after the game with your friends and family! It will be a blast! 

The Force is strong with the Fireflies as they turn Spirit Communications Park into a galaxy far far away

Follow on MiLB First Pitch  https //stza.co/+xBNG-1h

Shop  https //stza.co/+xBNG-3P

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Fireflies vs. BlueClaws
END:VALARM
DTSTART:20180504T230500Z
DTEND:20180505T020500Z
UID:ejfvniVXHBf97YHAcs9CL7UQ@stanza.co
SUMMARY:Fireflies vs. BlueClaws
DESCRIPTION:Enjoy fireworks after the game with your friends and family! It will be a blast! \n\nThe Force is strong with the Fireflies as they turn Spirit Communications Park into a galaxy far far away\n\nFollow on MiLB First Pitch: https://stza.co/+xBNG-1h\n\nShop: https://stza.co/+xBNG-3P\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Firework Friday's!
STATUS:CONFIRMED
CREATED:20180213T144515Z
LAST-MODIFIED:20180213T144515Z
TRANSP:OPAQUE
END:VEVENT
* Fireflies vs. BlueClaws
<2018-05-05 Sat 17:05-20:05>
:PROPERTIES:
:ID:       Zz4OiBh5awhdLWCC7BCCo4Dm@stanza.co
:LOCATION: Cinco de Mayo 
:STATUS:   CONFIRMED
:END:

Fireflies vs. BlueClaws Enjoy a festive atmosphere to celebrate Mexican culture and heritage  

Follow on MiLB First Pitch  https //stza.co/+xBNK-2M

Shop  https //stza.co/+xBNK-15

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Fireflies vs. BlueClaws
END:VALARM
DTSTART:20180505T220500Z
DTEND:20180506T010500Z
UID:Zz4OiBh5awhdLWCC7BCCo4Dm@stanza.co
SUMMARY:Fireflies vs. BlueClaws
DESCRIPTION:Enjoy a festive atmosphere to celebrate Mexican culture and heritage  \n\nFollow on MiLB First Pitch: https://stza.co/+xBNK-2M\n\nShop: https://stza.co/+xBNK-15\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Cinco de Mayo 
STATUS:CONFIRMED
CREATED:20180213T144515Z
LAST-MODIFIED:20180213T144515Z
TRANSP:OPAQUE
END:VEVENT
* Fireflies vs. BlueClaws
<2018-05-06 Sun 13:05-16:05>
:PROPERTIES:
:ID:       GpdbdT-7is444zSC4dXT5_cm@stanza.co
:LOCATION: Sunday Splash Day's and Autographs
:STATUS:   CONFIRMED
:END:

Fireflies vs. BlueClaws Come get your favorite player's autograph and cool down in the Splash Zone during the game! 

Follow on MiLB First Pitch  https //stza.co/+xWNS-2J

Shop  https //stza.co/+xWNS-1R

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Fireflies vs. BlueClaws
END:VALARM
DTSTART:20180506T180500Z
DTEND:20180506T210500Z
UID:GpdbdT-7is444zSC4dXT5_cm@stanza.co
SUMMARY:Fireflies vs. BlueClaws
DESCRIPTION:Come get your favorite player's autograph and cool down in the Splash Zone during the game! \n\nFollow on MiLB First Pitch: https://stza.co/+xWNS-2J\n\nShop: https://stza.co/+xWNS-1R\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Sunday Splash Day's and Autographs
STATUS:CONFIRMED
CREATED:20180213T144515Z
LAST-MODIFIED:20180213T144515Z
TRANSP:OPAQUE
END:VEVENT
* Fireflies vs. BlueClaws
<2018-05-07 Mon 10:05-13:05>
:PROPERTIES:
:ID:       wtygZaOrcrRcW3quXQqLiR2i@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Fireflies vs. BlueClaws Fireflies vs. BlueClaws

Follow on MiLB First Pitch  https //stza.co/+xWNU-2z

Shop  https //stza.co/+xWNU-3L

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Fireflies vs. BlueClaws
END:VALARM
DTSTART:20180507T150500Z
DTEND:20180507T180500Z
UID:wtygZaOrcrRcW3quXQqLiR2i@stanza.co
SUMMARY:Fireflies vs. BlueClaws
DESCRIPTION:Fireflies vs. BlueClaws\n\nFollow on MiLB First Pitch: https://stza.co/+xWNU-2z\n\nShop: https://stza.co/+xWNU-3L\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144515Z
LAST-MODIFIED:20180213T144515Z
TRANSP:OPAQUE
END:VEVENT
* Fireflies @ Crawdads
<2018-05-09 Wed 17:00-20:00>
:PROPERTIES:
:ID:       8OjclwxVojM_3FzyDJsiITk-@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Fireflies @ Crawdads Fireflies @ Crawdads

Follow on MiLB First Pitch  https //stza.co/+w0Oe-2n

Shop  https //stza.co/+w0Oe-x

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Fireflies @ Crawdads
END:VALARM
DTSTART:20180509T220000Z
DTEND:20180510T010000Z
UID:8OjclwxVojM_3FzyDJsiITk-@stanza.co
SUMMARY:Fireflies @ Crawdads
DESCRIPTION:Fireflies @ Crawdads\n\nFollow on MiLB First Pitch: https://stza.co/+w0Oe-2n\n\nShop: https://stza.co/+w0Oe-x\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144515Z
LAST-MODIFIED:20180213T144515Z
TRANSP:OPAQUE
END:VEVENT
* Fireflies @ Crawdads
<2018-05-10 Thu 18:00-21:00>
:PROPERTIES:
:ID:       UUDMoOu0a-uGWyzpWbaKaSzN@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Fireflies @ Crawdads Fireflies @ Crawdads

Follow on MiLB First Pitch  https //stza.co/+w0Of-1Q

Shop  https //stza.co/+w0Of-3N

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Fireflies @ Crawdads
END:VALARM
DTSTART:20180510T230000Z
DTEND:20180511T020000Z
UID:UUDMoOu0a-uGWyzpWbaKaSzN@stanza.co
SUMMARY:Fireflies @ Crawdads
DESCRIPTION:Fireflies @ Crawdads\n\nFollow on MiLB First Pitch: https://stza.co/+w0Of-1Q\n\nShop: https://stza.co/+w0Of-3N\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144515Z
LAST-MODIFIED:20180213T144515Z
TRANSP:OPAQUE
END:VEVENT
* Fireflies @ Crawdads
<2018-05-11 Fri 18:00-21:00>
:PROPERTIES:
:ID:       zmO3JIbBKhgvvBAO4XHGEs7P@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Fireflies @ Crawdads Fireflies @ Crawdads

Follow on MiLB First Pitch  https //stza.co/+w0Og-3K

Shop  https //stza.co/+w0Og-3a

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Fireflies @ Crawdads
END:VALARM
DTSTART:20180511T230000Z
DTEND:20180512T020000Z
UID:zmO3JIbBKhgvvBAO4XHGEs7P@stanza.co
SUMMARY:Fireflies @ Crawdads
DESCRIPTION:Fireflies @ Crawdads\n\nFollow on MiLB First Pitch: https://stza.co/+w0Og-3K\n\nShop: https://stza.co/+w0Og-3a\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144515Z
LAST-MODIFIED:20180213T144515Z
TRANSP:OPAQUE
END:VEVENT
* Fireflies vs. Shorebirds
<2018-05-12 Sat 17:05-20:05>
:PROPERTIES:
:ID:       rdEZWqgiXzagzCK9sZEV5xf1@stanza.co
:LOCATION: Video Game Night
:STATUS:   CONFIRMED
:END:

Fireflies vs. Shorebirds Level up with the Fireflies and celebrate your favorite video games during a night at the ballpark

Follow on MiLB First Pitch  https //stza.co/+xBNS-2k

Shop  https //stza.co/+xBNS-31

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Fireflies vs. Shorebirds
END:VALARM
DTSTART:20180512T220500Z
DTEND:20180513T010500Z
UID:rdEZWqgiXzagzCK9sZEV5xf1@stanza.co
SUMMARY:Fireflies vs. Shorebirds
DESCRIPTION:Level up with the Fireflies and celebrate your favorite video games during a night at the ballpark\n\nFollow on MiLB First Pitch: https://stza.co/+xBNS-2k\n\nShop: https://stza.co/+xBNS-31\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Video Game Night
STATUS:CONFIRMED
CREATED:20180213T144515Z
LAST-MODIFIED:20180213T144515Z
TRANSP:OPAQUE
END:VEVENT
* Fireflies vs. Shorebirds
<2018-05-13 Sun 13:05-16:05>
:PROPERTIES:
:ID:       Ga5ou3adiz5GNj_vMfwAYtHb@stanza.co
:LOCATION: Sunday Splash Day's and Autographs
:STATUS:   CONFIRMED
:END:

Fireflies vs. Shorebirds Come get your favorite player's autograph and cool down in the Splash Zone during the game! 

Follow on MiLB First Pitch  https //stza.co/+xBNU-2K

Shop  https //stza.co/+xBNU-1K

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Fireflies vs. Shorebirds
END:VALARM
DTSTART:20180513T180500Z
DTEND:20180513T210500Z
UID:Ga5ou3adiz5GNj_vMfwAYtHb@stanza.co
SUMMARY:Fireflies vs. Shorebirds
DESCRIPTION:Come get your favorite player's autograph and cool down in the Splash Zone during the game! \n\nFollow on MiLB First Pitch: https://stza.co/+xBNU-2K\n\nShop: https://stza.co/+xBNU-1K\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Sunday Splash Day's and Autographs
STATUS:CONFIRMED
CREATED:20180213T144515Z
LAST-MODIFIED:20180213T144515Z
TRANSP:OPAQUE
END:VEVENT
* Fireflies vs. Shorebirds
<2018-05-14 Mon 18:05-21:05>
:PROPERTIES:
:ID:       TgRJjHwlai6ythmxqt0cq-Zl@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Fireflies vs. Shorebirds Fireflies vs. Shorebirds

Follow on MiLB First Pitch  https //stza.co/+xBNW-39

Shop  https //stza.co/+xBNW-J

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Fireflies vs. Shorebirds
END:VALARM
DTSTART:20180514T230500Z
DTEND:20180515T020500Z
UID:TgRJjHwlai6ythmxqt0cq-Zl@stanza.co
SUMMARY:Fireflies vs. Shorebirds
DESCRIPTION:Fireflies vs. Shorebirds\n\nFollow on MiLB First Pitch: https://stza.co/+xBNW-39\n\nShop: https://stza.co/+xBNW-J\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144515Z
LAST-MODIFIED:20180213T144515Z
TRANSP:OPAQUE
END:VEVENT
* Fireflies vs. Shorebirds
<2018-05-15 Tue 18:05-21:05>
:PROPERTIES:
:ID:       inMBNkvSlwu1CKZ_wWzIYUen@stanza.co
:LOCATION: $2 Tuesday!
:STATUS:   CONFIRMED
:END:

Fireflies vs. Shorebirds Enjoy $2.00 hotdogs, fountain drinks and popcorn all game! 

Follow on MiLB First Pitch  https //stza.co/+xBNY-3q

Shop  https //stza.co/+xBNY-t

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Fireflies vs. Shorebirds
END:VALARM
DTSTART:20180515T230500Z
DTEND:20180516T020500Z
UID:inMBNkvSlwu1CKZ_wWzIYUen@stanza.co
SUMMARY:Fireflies vs. Shorebirds
DESCRIPTION:Enjoy $2.00 hotdogs, fountain drinks and popcorn all game! \n\nFollow on MiLB First Pitch: https://stza.co/+xBNY-3q\n\nShop: https://stza.co/+xBNY-t\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:$2 Tuesday!
STATUS:CONFIRMED
CREATED:20180213T144515Z
LAST-MODIFIED:20180213T144515Z
TRANSP:OPAQUE
END:VEVENT
* Fireflies @ RiverDogs
<2018-05-17 Thu 18:05-21:05>
:PROPERTIES:
:ID:       lGAJ-5PDFh7M01QdbjdjLdEz@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Fireflies @ RiverDogs Fireflies @ RiverDogs

Follow on MiLB First Pitch  https //stza.co/+vNCP-q

Shop  https //stza.co/+vNCP-3M

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Fireflies @ RiverDogs
END:VALARM
DTSTART:20180517T230500Z
DTEND:20180518T020500Z
UID:lGAJ-5PDFh7M01QdbjdjLdEz@stanza.co
SUMMARY:Fireflies @ RiverDogs
DESCRIPTION:Fireflies @ RiverDogs\n\nFollow on MiLB First Pitch: https://stza.co/+vNCP-q\n\nShop: https://stza.co/+vNCP-3M\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144515Z
LAST-MODIFIED:20180213T144515Z
TRANSP:OPAQUE
END:VEVENT
* Fireflies @ RiverDogs
<2018-05-18 Fri 18:05-21:05>
:PROPERTIES:
:ID:       8NseFn04nSZg3TwdpItZsbrM@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Fireflies @ RiverDogs Fireflies @ RiverDogs

Follow on MiLB First Pitch  https //stza.co/+vNCQ-1F

Shop  https //stza.co/+vNCQ-1U

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Fireflies @ RiverDogs
END:VALARM
DTSTART:20180518T230500Z
DTEND:20180519T020500Z
UID:8NseFn04nSZg3TwdpItZsbrM@stanza.co
SUMMARY:Fireflies @ RiverDogs
DESCRIPTION:Fireflies @ RiverDogs\n\nFollow on MiLB First Pitch: https://stza.co/+vNCQ-1F\n\nShop: https://stza.co/+vNCQ-1U\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144515Z
LAST-MODIFIED:20180213T144515Z
TRANSP:OPAQUE
END:VEVENT
* Fireflies @ RiverDogs
<2018-05-19 Sat 17:05-20:05>
:PROPERTIES:
:ID:       jggs2sa8LlZpeD35RuZbAhIU@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Fireflies @ RiverDogs Fireflies @ RiverDogs

Follow on MiLB First Pitch  https //stza.co/+vNCR-1j

Shop  https //stza.co/+vNCR-1C

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Fireflies @ RiverDogs
END:VALARM
DTSTART:20180519T220500Z
DTEND:20180520T010500Z
UID:jggs2sa8LlZpeD35RuZbAhIU@stanza.co
SUMMARY:Fireflies @ RiverDogs
DESCRIPTION:Fireflies @ RiverDogs\n\nFollow on MiLB First Pitch: https://stza.co/+vNCR-1j\n\nShop: https://stza.co/+vNCR-1C\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144515Z
LAST-MODIFIED:20180213T144515Z
TRANSP:OPAQUE
END:VEVENT
* Fireflies @ RiverDogs
<2018-05-20 Sun 16:05-19:05>
:PROPERTIES:
:ID:       Pu0iRHeqZ6RmA_3zTmbyZTpQ@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Fireflies @ RiverDogs Fireflies @ RiverDogs

Follow on MiLB First Pitch  https //stza.co/+vNCS-32

Shop  https //stza.co/+vNCS-1B

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Fireflies @ RiverDogs
END:VALARM
DTSTART:20180520T210500Z
DTEND:20180521T000500Z
UID:Pu0iRHeqZ6RmA_3zTmbyZTpQ@stanza.co
SUMMARY:Fireflies @ RiverDogs
DESCRIPTION:Fireflies @ RiverDogs\n\nFollow on MiLB First Pitch: https://stza.co/+vNCS-32\n\nShop: https://stza.co/+vNCS-1B\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144515Z
LAST-MODIFIED:20180213T144515Z
TRANSP:OPAQUE
END:VEVENT
* Fireflies vs. Power
<2018-05-21 Mon 18:05-21:05>
:PROPERTIES:
:ID:       6FgKTg4amKI8XFB6_XvhyOHs@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Fireflies vs. Power Fireflies vs. Power

Follow on MiLB First Pitch  https //stza.co/+xBN$-4

Shop  https //stza.co/+xBN$-3j

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Fireflies vs. Power
END:VALARM
DTSTART:20180521T230500Z
DTEND:20180522T020500Z
UID:6FgKTg4amKI8XFB6_XvhyOHs@stanza.co
SUMMARY:Fireflies vs. Power
DESCRIPTION:Fireflies vs. Power\n\nFollow on MiLB First Pitch: https://stza.co/+xBN$-4\n\nShop: https://stza.co/+xBN$-3j\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144515Z
LAST-MODIFIED:20180213T144515Z
TRANSP:OPAQUE
END:VEVENT
* Fireflies vs. Power
<2018-05-22 Tue 18:05-21:05>
:PROPERTIES:
:ID:       MAkEGC47eVVDTcM9bSR1c4M5@stanza.co
:LOCATION: $2 Tuesday!
:STATUS:   CONFIRMED
:END:

Fireflies vs. Power Enjoy $2.00 hotdogs, fountain drinks and popcorn all game! 

Follow on MiLB First Pitch  https //stza.co/+xBO1-2h

Shop  https //stza.co/+xBO1-3f

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Fireflies vs. Power
END:VALARM
DTSTART:20180522T230500Z
DTEND:20180523T020500Z
UID:MAkEGC47eVVDTcM9bSR1c4M5@stanza.co
SUMMARY:Fireflies vs. Power
DESCRIPTION:Enjoy $2.00 hotdogs, fountain drinks and popcorn all game! \n\nFollow on MiLB First Pitch: https://stza.co/+xBO1-2h\n\nShop: https://stza.co/+xBO1-3f\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:$2 Tuesday!
STATUS:CONFIRMED
CREATED:20180213T144515Z
LAST-MODIFIED:20180213T144515Z
TRANSP:OPAQUE
END:VEVENT
* Fireflies vs. Power
<2018-05-23 Wed 10:05-13:05>
:PROPERTIES:
:ID:       3pLRCC2fmkTEt7XXuK8HSiLT@stanza.co
:LOCATION: Wag-Along Wednesday
:STATUS:   CONFIRMED
:END:

Fireflies vs. Power Bring your dog to the game with you! 

Follow on MiLB First Pitch  https //stza.co/+xBO4-1m

Shop  https //stza.co/+xBO4-3S

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Fireflies vs. Power
END:VALARM
DTSTART:20180523T150500Z
DTEND:20180523T180500Z
UID:3pLRCC2fmkTEt7XXuK8HSiLT@stanza.co
SUMMARY:Fireflies vs. Power
DESCRIPTION:Bring your dog to the game with you! \n\nFollow on MiLB First Pitch: https://stza.co/+xBO4-1m\n\nShop: https://stza.co/+xBO4-3S\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Wag-Along Wednesday
STATUS:CONFIRMED
CREATED:20180213T144515Z
LAST-MODIFIED:20180213T144515Z
TRANSP:OPAQUE
END:VEVENT
* Fireflies vs. Power
<2018-05-24 Thu 18:05-21:05>
:PROPERTIES:
:ID:       auXHyoIVtXp5gX91sgddvah5@stanza.co
:LOCATION: Thirsty Thursday 
:STATUS:   CONFIRMED
:END:

Fireflies vs. Power Enjoy half priced beer and fountain drinks! 

Follow on MiLB First Pitch  https //stza.co/+xBO6-2y

Shop  https //stza.co/+xBO6-24

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Fireflies vs. Power
END:VALARM
DTSTART:20180524T230500Z
DTEND:20180525T020500Z
UID:auXHyoIVtXp5gX91sgddvah5@stanza.co
SUMMARY:Fireflies vs. Power
DESCRIPTION:Enjoy half priced beer and fountain drinks! \n\nFollow on MiLB First Pitch: https://stza.co/+xBO6-2y\n\nShop: https://stza.co/+xBO6-24\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Thirsty Thursday 
STATUS:CONFIRMED
CREATED:20180213T144515Z
LAST-MODIFIED:20180213T144515Z
TRANSP:OPAQUE
END:VEVENT
* Fireflies vs. Drive
<2018-05-25 Fri 18:05-21:05>
:PROPERTIES:
:ID:       TLhsao75Uz8a0VcfAqOchA_F@stanza.co
:LOCATION: Firework Friday's!
:STATUS:   CONFIRMED
:END:

Fireflies vs. Drive Enjoy fireworks after the game with your friends and family! It will be a blast! 

Follow on MiLB First Pitch  https //stza.co/+xBO8-2V

Shop  https //stza.co/+xBO8-2z

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Fireflies vs. Drive
END:VALARM
DTSTART:20180525T230500Z
DTEND:20180526T020500Z
UID:TLhsao75Uz8a0VcfAqOchA_F@stanza.co
SUMMARY:Fireflies vs. Drive
DESCRIPTION:Enjoy fireworks after the game with your friends and family! It will be a blast! \n\nFollow on MiLB First Pitch: https://stza.co/+xBO8-2V\n\nShop: https://stza.co/+xBO8-2z\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Firework Friday's!
STATUS:CONFIRMED
CREATED:20180213T144515Z
LAST-MODIFIED:20180213T144515Z
TRANSP:OPAQUE
END:VEVENT
* Fireflies vs. Drive
<2018-05-26 Sat 17:05-20:05>
:PROPERTIES:
:ID:       0uRpBCIHw1QH39vioGNzlPKb@stanza.co
:LOCATION: Harry Potter Night 
:STATUS:   CONFIRMED
:END:

Fireflies vs. Drive Calling all wizards as Spirit Communications Park is transformed into Hogwarts School of Witchcraft and Wizardry

Follow on MiLB First Pitch  https //stza.co/+xBOb-2R

Shop  https //stza.co/+xBOb-2Z

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Fireflies vs. Drive
END:VALARM
DTSTART:20180526T220500Z
DTEND:20180527T010500Z
UID:0uRpBCIHw1QH39vioGNzlPKb@stanza.co
SUMMARY:Fireflies vs. Drive
DESCRIPTION:Calling all wizards as Spirit Communications Park is transformed into Hogwarts School of Witchcraft and Wizardry\n\nFollow on MiLB First Pitch: https://stza.co/+xBOb-2R\n\nShop: https://stza.co/+xBOb-2Z\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Harry Potter Night 
STATUS:CONFIRMED
CREATED:20180213T144515Z
LAST-MODIFIED:20180213T144515Z
TRANSP:OPAQUE
END:VEVENT
* Fireflies vs. Drive
<2018-05-27 Sun 17:05-20:05>
:PROPERTIES:
:ID:       u5tcELWxeM2XoOqa47zr9wL1@stanza.co
:LOCATION: Sunday Splash Day's and Autographs
:STATUS:   CONFIRMED
:END:

Fireflies vs. Drive Come get your favorite player's autograph and cool down in the Splash Zone during the game! 

Follow on MiLB First Pitch  https //stza.co/+xBOe-3b

Shop  https //stza.co/+xBOe-w

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Fireflies vs. Drive
END:VALARM
DTSTART:20180527T220500Z
DTEND:20180528T010500Z
UID:u5tcELWxeM2XoOqa47zr9wL1@stanza.co
SUMMARY:Fireflies vs. Drive
DESCRIPTION:Come get your favorite player's autograph and cool down in the Splash Zone during the game! \n\nFollow on MiLB First Pitch: https://stza.co/+xBOe-3b\n\nShop: https://stza.co/+xBOe-w\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Sunday Splash Day's and Autographs
STATUS:CONFIRMED
CREATED:20180213T144515Z
LAST-MODIFIED:20180213T144515Z
TRANSP:OPAQUE
END:VEVENT
* Fireflies vs. Drive
<2018-05-28 Mon 11:05-14:05>
:PROPERTIES:
:ID:       mwWnkyxDrFVxN14EM_4Y_r9W@stanza.co
:LOCATION: Military Card Set Giveaway
:STATUS:   CONFIRMED
:END:

Fireflies vs. Drive The Fireflies will honor hero's who have served by giving away military inspired card sets! 

Follow on MiLB First Pitch  https //stza.co/+xBOg-k

Shop  https //stza.co/+xBOg-1d

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Fireflies vs. Drive
END:VALARM
DTSTART:20180528T160500Z
DTEND:20180528T190500Z
UID:mwWnkyxDrFVxN14EM_4Y_r9W@stanza.co
SUMMARY:Fireflies vs. Drive
DESCRIPTION:The Fireflies will honor hero's who have served by giving away military inspired card sets! \n\nFollow on MiLB First Pitch: https://stza.co/+xBOg-k\n\nShop: https://stza.co/+xBOg-1d\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Military Card Set Giveaway
STATUS:CONFIRMED
CREATED:20180213T144515Z
LAST-MODIFIED:20180213T144515Z
TRANSP:OPAQUE
END:VEVENT
* Fireflies @ RiverDogs
<2018-05-29 Tue 18:05-21:05>
:PROPERTIES:
:ID:       GDgEFSHPYNse5X1fZ_NNzu9o@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Fireflies @ RiverDogs Fireflies @ RiverDogs

Follow on MiLB First Pitch  https //stza.co/+vNCT-14

Shop  https //stza.co/+vNCT-3M

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Fireflies @ RiverDogs
END:VALARM
DTSTART:20180529T230500Z
DTEND:20180530T020500Z
UID:GDgEFSHPYNse5X1fZ_NNzu9o@stanza.co
SUMMARY:Fireflies @ RiverDogs
DESCRIPTION:Fireflies @ RiverDogs\n\nFollow on MiLB First Pitch: https://stza.co/+vNCT-14\n\nShop: https://stza.co/+vNCT-3M\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144515Z
LAST-MODIFIED:20180213T144515Z
TRANSP:OPAQUE
END:VEVENT
* Fireflies @ RiverDogs
<2018-05-30 Wed 10:05-13:05>
:PROPERTIES:
:ID:       kPJeiJwsdHKm5YStviCDUkGT@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Fireflies @ RiverDogs Fireflies @ RiverDogs

Follow on MiLB First Pitch  https //stza.co/+vNCU-3y

Shop  https //stza.co/+vNCU-1o

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Fireflies @ RiverDogs
END:VALARM
DTSTART:20180530T150500Z
DTEND:20180530T180500Z
UID:kPJeiJwsdHKm5YStviCDUkGT@stanza.co
SUMMARY:Fireflies @ RiverDogs
DESCRIPTION:Fireflies @ RiverDogs\n\nFollow on MiLB First Pitch: https://stza.co/+vNCU-3y\n\nShop: https://stza.co/+vNCU-1o\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144515Z
LAST-MODIFIED:20180213T144515Z
TRANSP:OPAQUE
END:VEVENT
* Fireflies @ RiverDogs
<2018-05-31 Thu 18:05-21:05>
:PROPERTIES:
:ID:       r68YE6RUxkiC_NeLxQyX5EGs@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Fireflies @ RiverDogs Fireflies @ RiverDogs

Follow on MiLB First Pitch  https //stza.co/+vNCV-2s

Shop  https //stza.co/+vNCV-3T

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Fireflies @ RiverDogs
END:VALARM
DTSTART:20180531T230500Z
DTEND:20180601T020500Z
UID:r68YE6RUxkiC_NeLxQyX5EGs@stanza.co
SUMMARY:Fireflies @ RiverDogs
DESCRIPTION:Fireflies @ RiverDogs\n\nFollow on MiLB First Pitch: https://stza.co/+vNCV-2s\n\nShop: https://stza.co/+vNCV-3T\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144515Z
LAST-MODIFIED:20180213T144515Z
TRANSP:OPAQUE
END:VEVENT
* Fireflies @ Braves
<2018-06-01 Fri 18:00-21:00>
:PROPERTIES:
:ID:       EPs8AWTn9wV2FNbyJo6mKeG-@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Fireflies @ Braves Fireflies @ Braves

Follow on MiLB First Pitch  https //stza.co/+vNFx-f

Shop  https //stza.co/+vNFx-2m

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Fireflies @ Braves
END:VALARM
DTSTART:20180601T230000Z
DTEND:20180602T020000Z
UID:EPs8AWTn9wV2FNbyJo6mKeG-@stanza.co
SUMMARY:Fireflies @ Braves
DESCRIPTION:Fireflies @ Braves\n\nFollow on MiLB First Pitch: https://stza.co/+vNFx-f\n\nShop: https://stza.co/+vNFx-2m\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144515Z
LAST-MODIFIED:20180213T144515Z
TRANSP:OPAQUE
END:VEVENT
* Fireflies @ Braves
<2018-06-02 Sat 17:00-20:00>
:PROPERTIES:
:ID:       Gc_XOqzfDgW8oFG8GsKbzGCo@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Fireflies @ Braves Fireflies @ Braves

Follow on MiLB First Pitch  https //stza.co/+vNFy-G

Shop  https //stza.co/+vNFy-15

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Fireflies @ Braves
END:VALARM
DTSTART:20180602T220000Z
DTEND:20180603T010000Z
UID:Gc_XOqzfDgW8oFG8GsKbzGCo@stanza.co
SUMMARY:Fireflies @ Braves
DESCRIPTION:Fireflies @ Braves\n\nFollow on MiLB First Pitch: https://stza.co/+vNFy-G\n\nShop: https://stza.co/+vNFy-15\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144515Z
LAST-MODIFIED:20180213T144515Z
TRANSP:OPAQUE
END:VEVENT
* Fireflies @ Braves
<2018-06-03 Sun 13:00-16:00>
:PROPERTIES:
:ID:       dqf1gfxDX0woTw1IHhZmgVm4@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Fireflies @ Braves Fireflies @ Braves

Follow on MiLB First Pitch  https //stza.co/+vNFz-2c

Shop  https //stza.co/+vNFz-3v

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Fireflies @ Braves
END:VALARM
DTSTART:20180603T180000Z
DTEND:20180603T210000Z
UID:dqf1gfxDX0woTw1IHhZmgVm4@stanza.co
SUMMARY:Fireflies @ Braves
DESCRIPTION:Fireflies @ Braves\n\nFollow on MiLB First Pitch: https://stza.co/+vNFz-2c\n\nShop: https://stza.co/+vNFz-3v\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144515Z
LAST-MODIFIED:20180213T144515Z
TRANSP:OPAQUE
END:VEVENT
* Fireflies vs. RiverDogs
<2018-06-05 Tue 18:05-21:05>
:PROPERTIES:
:ID:       OPTLjobh0mnk-7tXixbrYcLE@stanza.co
:LOCATION: $2 Tuesday!
:STATUS:   CONFIRMED
:END:

Fireflies vs. RiverDogs Enjoy $2.00 hotdogs, fountain drinks and popcorn all game! 

Follow on MiLB First Pitch  https //stza.co/+xBOh-17

Shop  https //stza.co/+xBOh-34

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Fireflies vs. RiverDogs
END:VALARM
DTSTART:20180605T230500Z
DTEND:20180606T020500Z
UID:OPTLjobh0mnk-7tXixbrYcLE@stanza.co
SUMMARY:Fireflies vs. RiverDogs
DESCRIPTION:Enjoy $2.00 hotdogs, fountain drinks and popcorn all game! \n\nFollow on MiLB First Pitch: https://stza.co/+xBOh-17\n\nShop: https://stza.co/+xBOh-34\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:$2 Tuesday!
STATUS:CONFIRMED
CREATED:20180213T144515Z
LAST-MODIFIED:20180213T144515Z
TRANSP:OPAQUE
END:VEVENT
* Fireflies vs. RiverDogs
<2018-06-06 Wed 18:05-21:05>
:PROPERTIES:
:ID:       Qt4AAE5st9PrQ37to4nmVAif@stanza.co
:LOCATION: Wag-Along Wednesday
:STATUS:   CONFIRMED
:END:

Fireflies vs. RiverDogs Bring your dog to the game with you! 

Follow on MiLB First Pitch  https //stza.co/+xBOj-2$

Shop  https //stza.co/+xBOj-3j

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Fireflies vs. RiverDogs
END:VALARM
DTSTART:20180606T230500Z
DTEND:20180607T020500Z
UID:Qt4AAE5st9PrQ37to4nmVAif@stanza.co
SUMMARY:Fireflies vs. RiverDogs
DESCRIPTION:Bring your dog to the game with you! \n\nFollow on MiLB First Pitch: https://stza.co/+xBOj-2$\n\nShop: https://stza.co/+xBOj-3j\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Wag-Along Wednesday
STATUS:CONFIRMED
CREATED:20180213T144515Z
LAST-MODIFIED:20180213T144515Z
TRANSP:OPAQUE
END:VEVENT
* Fireflies vs. RiverDogs
<2018-06-07 Thu 18:05-21:05>
:PROPERTIES:
:ID:       qRDe3gBRHDW53M4R-T5sWwAS@stanza.co
:LOCATION: Thirsty Thursday 
:STATUS:   CONFIRMED
:END:

Fireflies vs. RiverDogs Enjoy half priced beer and fountain drinks! 

Baseball's most famous bat boy and golden retriever will spend the night fetching bats and delivering water to the umpires 

Follow on MiLB First Pitch  https //stza.co/+xBOl-3J

Shop  https //stza.co/+xBOl-V

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Fireflies vs. RiverDogs
END:VALARM
DTSTART:20180607T230500Z
DTEND:20180608T020500Z
UID:qRDe3gBRHDW53M4R-T5sWwAS@stanza.co
SUMMARY:Fireflies vs. RiverDogs
DESCRIPTION:Enjoy half priced beer and fountain drinks! \n\nBaseball's most famous bat boy and golden retriever will spend the night fetching bats and delivering water to the umpires \n\nFollow on MiLB First Pitch: https://stza.co/+xBOl-3J\n\nShop: https://stza.co/+xBOl-V\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Thirsty Thursday 
STATUS:CONFIRMED
CREATED:20180213T144515Z
LAST-MODIFIED:20180213T144515Z
TRANSP:OPAQUE
END:VEVENT
* Fireflies vs. GreenJackets
<2018-06-08 Fri 18:05-21:05>
:PROPERTIES:
:ID:       Rn-u0HMbnwqogSVtm06oqnbg@stanza.co
:LOCATION: Firework Friday's!
:STATUS:   CONFIRMED
:END:

Fireflies vs. GreenJackets Enjoy fireworks after the game with your friends and family! It will be a blast! 

Baseball's most famous bat boy and golden retriever will spend the night fetching bats and delivering water to the umpires 

Follow on MiLB First Pitch  https //stza.co/+xBOp-1y

Shop  https //stza.co/+xBOp-s

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Fireflies vs. GreenJackets
END:VALARM
DTSTART:20180608T230500Z
DTEND:20180609T020500Z
UID:Rn-u0HMbnwqogSVtm06oqnbg@stanza.co
SUMMARY:Fireflies vs. GreenJackets
DESCRIPTION:Enjoy fireworks after the game with your friends and family! It will be a blast! \n\nBaseball's most famous bat boy and golden retriever will spend the night fetching bats and delivering water to the umpires \n\nFollow on MiLB First Pitch: https://stza.co/+xBOp-1y\n\nShop: https://stza.co/+xBOp-s\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Firework Friday's!
STATUS:CONFIRMED
CREATED:20180213T144515Z
LAST-MODIFIED:20180213T144515Z
TRANSP:OPAQUE
END:VEVENT
* Fireflies vs. GreenJackets
<2018-06-09 Sat 17:05-20:05>
:PROPERTIES:
:ID:       Jn8kI8gmwCNjCsmKDaDVqfoY@stanza.co
:LOCATION: Country Night
:STATUS:   CONFIRMED
:END:

Fireflies vs. GreenJackets Dust off your boots and enjoy some of your favorite country classics as you take in the ball game 

Follow on MiLB First Pitch  https //stza.co/+xBOs-K

Shop  https //stza.co/+xBOs-h

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Fireflies vs. GreenJackets
END:VALARM
DTSTART:20180609T220500Z
DTEND:20180610T010500Z
UID:Jn8kI8gmwCNjCsmKDaDVqfoY@stanza.co
SUMMARY:Fireflies vs. GreenJackets
DESCRIPTION:Dust off your boots and enjoy some of your favorite country classics as you take in the ball game \n\nFollow on MiLB First Pitch: https://stza.co/+xBOs-K\n\nShop: https://stza.co/+xBOs-h\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Country Night
STATUS:CONFIRMED
CREATED:20180213T144515Z
LAST-MODIFIED:20180213T144515Z
TRANSP:OPAQUE
END:VEVENT
* Fireflies vs. GreenJackets
<2018-06-10 Sun 13:05-16:05>
:PROPERTIES:
:ID:       BdhDcQ0jRluRYWE9Hs8Q3OMA@stanza.co
:LOCATION: Sunday Splash Day's and Autographs
:STATUS:   CONFIRMED
:END:

Fireflies vs. GreenJackets Come get your favorite player's autograph and cool down in the Splash Zone during the game! 

Follow on MiLB First Pitch  https //stza.co/+xBOu-3u

Shop  https //stza.co/+xBOu-D

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Fireflies vs. GreenJackets
END:VALARM
DTSTART:20180610T180500Z
DTEND:20180610T210500Z
UID:BdhDcQ0jRluRYWE9Hs8Q3OMA@stanza.co
SUMMARY:Fireflies vs. GreenJackets
DESCRIPTION:Come get your favorite player's autograph and cool down in the Splash Zone during the game! \n\nFollow on MiLB First Pitch: https://stza.co/+xBOu-3u\n\nShop: https://stza.co/+xBOu-D\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Sunday Splash Day's and Autographs
STATUS:CONFIRMED
CREATED:20180213T144515Z
LAST-MODIFIED:20180213T144515Z
TRANSP:OPAQUE
END:VEVENT
* Fireflies @ Legends
<2018-06-11 Mon 18:05-21:05>
:PROPERTIES:
:ID:       JDTiD6ZxszTgDkx1ZiWt5BBY@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Fireflies @ Legends Fireflies @ Legends

Follow on MiLB First Pitch  https //stza.co/+xB0d-3I

Shop  https //stza.co/+xB0d-3S

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Fireflies @ Legends
END:VALARM
DTSTART:20180611T230500Z
DTEND:20180612T020500Z
UID:JDTiD6ZxszTgDkx1ZiWt5BBY@stanza.co
SUMMARY:Fireflies @ Legends
DESCRIPTION:Fireflies @ Legends\n\nFollow on MiLB First Pitch: https://stza.co/+xB0d-3I\n\nShop: https://stza.co/+xB0d-3S\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144515Z
LAST-MODIFIED:20180213T144515Z
TRANSP:OPAQUE
END:VEVENT
* Fireflies @ Legends
<2018-06-12 Tue 18:05-21:05>
:PROPERTIES:
:ID:       ey5dmqgFasRoAdrPPexlOvfP@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Fireflies @ Legends Fireflies @ Legends

Follow on MiLB First Pitch  https //stza.co/+xB0f-3c

Shop  https //stza.co/+xB0f-1q

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Fireflies @ Legends
END:VALARM
DTSTART:20180612T230500Z
DTEND:20180613T020500Z
UID:ey5dmqgFasRoAdrPPexlOvfP@stanza.co
SUMMARY:Fireflies @ Legends
DESCRIPTION:Fireflies @ Legends\n\nFollow on MiLB First Pitch: https://stza.co/+xB0f-3c\n\nShop: https://stza.co/+xB0f-1q\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144515Z
LAST-MODIFIED:20180213T144515Z
TRANSP:OPAQUE
END:VEVENT
* Fireflies @ Legends
<2018-06-13 Wed 09:35-12:35>
:PROPERTIES:
:ID:       csccWbjFev1uBAaSQVFBmW6j@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Fireflies @ Legends Fireflies @ Legends

Follow on MiLB First Pitch  https //stza.co/+xB0g-1h

Shop  https //stza.co/+xB0g-3E

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Fireflies @ Legends
END:VALARM
DTSTART:20180613T143500Z
DTEND:20180613T173500Z
UID:csccWbjFev1uBAaSQVFBmW6j@stanza.co
SUMMARY:Fireflies @ Legends
DESCRIPTION:Fireflies @ Legends\n\nFollow on MiLB First Pitch: https://stza.co/+xB0g-1h\n\nShop: https://stza.co/+xB0g-3E\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144515Z
LAST-MODIFIED:20180213T144515Z
TRANSP:OPAQUE
END:VEVENT
* Fireflies @ Legends
<2018-06-14 Thu 18:05-21:05>
:PROPERTIES:
:ID:       nn1SrPqDAVKrHb5CsJ4RFpGd@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Fireflies @ Legends Fireflies @ Legends

Follow on MiLB First Pitch  https //stza.co/+xB0h-d

Shop  https //stza.co/+xB0h-1s

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Fireflies @ Legends
END:VALARM
DTSTART:20180614T230500Z
DTEND:20180615T020500Z
UID:nn1SrPqDAVKrHb5CsJ4RFpGd@stanza.co
SUMMARY:Fireflies @ Legends
DESCRIPTION:Fireflies @ Legends\n\nFollow on MiLB First Pitch: https://stza.co/+xB0h-d\n\nShop: https://stza.co/+xB0h-1s\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144515Z
LAST-MODIFIED:20180213T144515Z
TRANSP:OPAQUE
END:VEVENT
* Fireflies @ Suns
<2018-06-15 Fri 18:05-21:05>
:PROPERTIES:
:ID:       lgVFFLJ-5uPEdeC49znfQ0iD@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Fireflies @ Suns Fireflies @ Suns

Follow on MiLB First Pitch  https //stza.co/+xEZU-3L

Shop  https //stza.co/+xEZU-h

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Fireflies @ Suns
END:VALARM
DTSTART:20180615T230500Z
DTEND:20180616T020500Z
UID:lgVFFLJ-5uPEdeC49znfQ0iD@stanza.co
SUMMARY:Fireflies @ Suns
DESCRIPTION:Fireflies @ Suns\n\nFollow on MiLB First Pitch: https://stza.co/+xEZU-3L\n\nShop: https://stza.co/+xEZU-h\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144515Z
LAST-MODIFIED:20180213T144515Z
TRANSP:OPAQUE
END:VEVENT
* Fireflies @ Suns
<2018-06-16 Sat 17:05-20:05>
:PROPERTIES:
:ID:       S2FNTojpnBIVLycsFQ8Yylb4@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Fireflies @ Suns Fireflies @ Suns

Follow on MiLB First Pitch  https //stza.co/+xEZV-1

Shop  https //stza.co/+xEZV-1i

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Fireflies @ Suns
END:VALARM
DTSTART:20180616T220500Z
DTEND:20180617T010500Z
UID:S2FNTojpnBIVLycsFQ8Yylb4@stanza.co
SUMMARY:Fireflies @ Suns
DESCRIPTION:Fireflies @ Suns\n\nFollow on MiLB First Pitch: https://stza.co/+xEZV-1\n\nShop: https://stza.co/+xEZV-1i\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144515Z
LAST-MODIFIED:20180213T144515Z
TRANSP:OPAQUE
END:VEVENT
* Fireflies @ Suns
<2018-06-17 Sun 13:05-16:05>
:PROPERTIES:
:ID:       w6qrzPUUc0w33P3AlTFsE9X7@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Fireflies @ Suns Fireflies @ Suns

Follow on MiLB First Pitch  https //stza.co/+xEZW-1z

Shop  https //stza.co/+xEZW-2n

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Fireflies @ Suns
END:VALARM
DTSTART:20180617T180500Z
DTEND:20180617T210500Z
UID:w6qrzPUUc0w33P3AlTFsE9X7@stanza.co
SUMMARY:Fireflies @ Suns
DESCRIPTION:Fireflies @ Suns\n\nFollow on MiLB First Pitch: https://stza.co/+xEZW-1z\n\nShop: https://stza.co/+xEZW-2n\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144515Z
LAST-MODIFIED:20180213T144515Z
TRANSP:OPAQUE
END:VEVENT
* Fireflies vs. BlueClaws
<2018-06-21 Thu 18:05-21:05>
:PROPERTIES:
:ID:       689uO4GiwvZuL6Yy3syxFd4o@stanza.co
:LOCATION: Thirsty Thursday 
:STATUS:   CONFIRMED
:END:

Fireflies vs. BlueClaws Enjoy half priced beer and fountain drinks! 

Follow on MiLB First Pitch  https //stza.co/+xBOv-20

Shop  https //stza.co/+xBOv-39

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Fireflies vs. BlueClaws
END:VALARM
DTSTART:20180621T230500Z
DTEND:20180622T020500Z
UID:689uO4GiwvZuL6Yy3syxFd4o@stanza.co
SUMMARY:Fireflies vs. BlueClaws
DESCRIPTION:Enjoy half priced beer and fountain drinks! \n\nFollow on MiLB First Pitch: https://stza.co/+xBOv-20\n\nShop: https://stza.co/+xBOv-39\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Thirsty Thursday 
STATUS:CONFIRMED
CREATED:20180213T144515Z
LAST-MODIFIED:20180213T144515Z
TRANSP:OPAQUE
END:VEVENT
* Fireflies vs. BlueClaws
<2018-06-22 Fri 18:05-21:05>
:PROPERTIES:
:ID:       8NvTVHwFnE8qFQxgadUmpVW4@stanza.co
:LOCATION: Firework Friday's!
:STATUS:   CONFIRMED
:END:

Fireflies vs. BlueClaws Enjoy fireworks after the game with your friends and family! It will be a blast! 

Follow on MiLB First Pitch  https //stza.co/+xBOx-3s

Shop  https //stza.co/+xBOx-1g

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Fireflies vs. BlueClaws
END:VALARM
DTSTART:20180622T230500Z
DTEND:20180623T020500Z
UID:8NvTVHwFnE8qFQxgadUmpVW4@stanza.co
SUMMARY:Fireflies vs. BlueClaws
DESCRIPTION:Enjoy fireworks after the game with your friends and family! It will be a blast! \n\nFollow on MiLB First Pitch: https://stza.co/+xBOx-3s\n\nShop: https://stza.co/+xBOx-1g\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Firework Friday's!
STATUS:CONFIRMED
CREATED:20180213T144515Z
LAST-MODIFIED:20180213T144515Z
TRANSP:OPAQUE
END:VEVENT
* Fireflies vs. BlueClaws
<2018-06-23 Sat 17:05-20:05>
:PROPERTIES:
:ID:       VzuZXqRUCs8SM70HawM7e7Ra@stanza.co
:LOCATION: Dino Night
:STATUS:   CONFIRMED
:END:

Fireflies vs. BlueClaws Be on the look out for pterodactyls and trisarahtops and other pre historic creatures around the ballpark

Follow on MiLB First Pitch  https //stza.co/+xBOB-31

Shop  https //stza.co/+xBOB-Q

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Fireflies vs. BlueClaws
END:VALARM
DTSTART:20180623T220500Z
DTEND:20180624T010500Z
UID:VzuZXqRUCs8SM70HawM7e7Ra@stanza.co
SUMMARY:Fireflies vs. BlueClaws
DESCRIPTION:Be on the look out for pterodactyls and trisarahtops and other pre historic creatures around the ballpark\n\nFollow on MiLB First Pitch: https://stza.co/+xBOB-31\n\nShop: https://stza.co/+xBOB-Q\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Dino Night
STATUS:CONFIRMED
CREATED:20180213T144515Z
LAST-MODIFIED:20180213T144515Z
TRANSP:OPAQUE
END:VEVENT
* Fireflies @ Legends
<2018-06-24 Sun 13:05-16:05>
:PROPERTIES:
:ID:       RTKcH0mfZ6gAz6YeixbTHPEN@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Fireflies @ Legends Fireflies @ Legends

Follow on MiLB First Pitch  https //stza.co/+xB0i-2Z

Shop  https //stza.co/+xB0i-2i

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Fireflies @ Legends
END:VALARM
DTSTART:20180624T180500Z
DTEND:20180624T210500Z
UID:RTKcH0mfZ6gAz6YeixbTHPEN@stanza.co
SUMMARY:Fireflies @ Legends
DESCRIPTION:Fireflies @ Legends\n\nFollow on MiLB First Pitch: https://stza.co/+xB0i-2Z\n\nShop: https://stza.co/+xB0i-2i\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144515Z
LAST-MODIFIED:20180213T144515Z
TRANSP:OPAQUE
END:VEVENT
* Fireflies @ Legends
<2018-06-25 Mon 18:05-21:05>
:PROPERTIES:
:ID:       602rdj2mNsmWihkq1V0SGV8h@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Fireflies @ Legends Fireflies @ Legends

Follow on MiLB First Pitch  https //stza.co/+xB0j-X

Shop  https //stza.co/+xB0j-4

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Fireflies @ Legends
END:VALARM
DTSTART:20180625T230500Z
DTEND:20180626T020500Z
UID:602rdj2mNsmWihkq1V0SGV8h@stanza.co
SUMMARY:Fireflies @ Legends
DESCRIPTION:Fireflies @ Legends\n\nFollow on MiLB First Pitch: https://stza.co/+xB0j-X\n\nShop: https://stza.co/+xB0j-4\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144515Z
LAST-MODIFIED:20180213T144515Z
TRANSP:OPAQUE
END:VEVENT
* Fireflies @ Legends
<2018-06-26 Tue 18:05-21:05>
:PROPERTIES:
:ID:       _czy8yXMtCIHTXn3qauwAz1A@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Fireflies @ Legends Fireflies @ Legends

Follow on MiLB First Pitch  https //stza.co/+xB0k-1G

Shop  https //stza.co/+xB0k-3L

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Fireflies @ Legends
END:VALARM
DTSTART:20180626T230500Z
DTEND:20180627T020500Z
UID:_czy8yXMtCIHTXn3qauwAz1A@stanza.co
SUMMARY:Fireflies @ Legends
DESCRIPTION:Fireflies @ Legends\n\nFollow on MiLB First Pitch: https://stza.co/+xB0k-1G\n\nShop: https://stza.co/+xB0k-3L\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144515Z
LAST-MODIFIED:20180213T144515Z
TRANSP:OPAQUE
END:VEVENT
* Fireflies vs. Tourists
<2018-06-27 Wed 18:05-21:05>
:PROPERTIES:
:ID:       nNnF1WMNo_cJayaYVrhmyb3V@stanza.co
:LOCATION: Wag-Along Wednesday
:STATUS:   CONFIRMED
:END:

Fireflies vs. Tourists Bring your dog to the game with you! 

Follow on MiLB First Pitch  https //stza.co/+xBOE-3C

Shop  https //stza.co/+xBOE-3M

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Fireflies vs. Tourists
END:VALARM
DTSTART:20180627T230500Z
DTEND:20180628T020500Z
UID:nNnF1WMNo_cJayaYVrhmyb3V@stanza.co
SUMMARY:Fireflies vs. Tourists
DESCRIPTION:Bring your dog to the game with you! \n\nFollow on MiLB First Pitch: https://stza.co/+xBOE-3C\n\nShop: https://stza.co/+xBOE-3M\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Wag-Along Wednesday
STATUS:CONFIRMED
CREATED:20180213T144515Z
LAST-MODIFIED:20180213T144515Z
TRANSP:OPAQUE
END:VEVENT
* Fireflies vs. Tourists
<2018-06-28 Thu 18:05-21:05>
:PROPERTIES:
:ID:       V66FDiWwdeNW2gHuyuefGD5Y@stanza.co
:LOCATION: Thirsty Thursday 
:STATUS:   CONFIRMED
:END:

Fireflies vs. Tourists Enjoy half priced beer and fountain drinks! 

Represent your favorite pro wrestler at the ballpark as the Fireflies pay homage to the sports most iconic athletes and personalities 

Follow on MiLB First Pitch  https //stza.co/+xBOG-29

Shop  https //stza.co/+xBOG-2K

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Fireflies vs. Tourists
END:VALARM
DTSTART:20180628T230500Z
DTEND:20180629T020500Z
UID:V66FDiWwdeNW2gHuyuefGD5Y@stanza.co
SUMMARY:Fireflies vs. Tourists
DESCRIPTION:Enjoy half priced beer and fountain drinks! \n\nRepresent your favorite pro wrestler at the ballpark as the Fireflies pay homage to the sports most iconic athletes and personalities \n\nFollow on MiLB First Pitch: https://stza.co/+xBOG-29\n\nShop: https://stza.co/+xBOG-2K\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Thirsty Thursday 
STATUS:CONFIRMED
CREATED:20180213T144515Z
LAST-MODIFIED:20180213T144515Z
TRANSP:OPAQUE
END:VEVENT
* Fireflies vs. Tourists
<2018-06-29 Fri 18:05-21:05>
:PROPERTIES:
:ID:       rSmWTI4rTosmklDOXJ_R4ii5@stanza.co
:LOCATION: Firework Friday's!
:STATUS:   CONFIRMED
:END:

Fireflies vs. Tourists Enjoy fireworks after the game with your friends and family! It will be a blast! 

Celebrate Mason's special day followed by a fireworks spectacular!

Follow on MiLB First Pitch  https //stza.co/+xBOH-$

Shop  https //stza.co/+xBOH-3o

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Fireflies vs. Tourists
END:VALARM
DTSTART:20180629T230500Z
DTEND:20180630T020500Z
UID:rSmWTI4rTosmklDOXJ_R4ii5@stanza.co
SUMMARY:Fireflies vs. Tourists
DESCRIPTION:Enjoy fireworks after the game with your friends and family! It will be a blast! \n\nCelebrate Mason's special day followed by a fireworks spectacular!\n\nFollow on MiLB First Pitch: https://stza.co/+xBOH-$\n\nShop: https://stza.co/+xBOH-3o\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Firework Friday's!
STATUS:CONFIRMED
CREATED:20180213T144515Z
LAST-MODIFIED:20180213T144515Z
TRANSP:OPAQUE
END:VEVENT
* Fireflies @ GreenJackets
<2018-06-30 Sat 17:05-20:05>
:PROPERTIES:
:ID:       Rr1xaRkCuIc-2zzf8PaMXe7N@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Fireflies @ GreenJackets Fireflies @ GreenJackets

Follow on MiLB First Pitch  https //stza.co/+xBMF-1z

Shop  https //stza.co/+xBMF-D

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Fireflies @ GreenJackets
END:VALARM
DTSTART:20180630T220500Z
DTEND:20180701T010500Z
UID:Rr1xaRkCuIc-2zzf8PaMXe7N@stanza.co
SUMMARY:Fireflies @ GreenJackets
DESCRIPTION:Fireflies @ GreenJackets\n\nFollow on MiLB First Pitch: https://stza.co/+xBMF-1z\n\nShop: https://stza.co/+xBMF-D\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144515Z
LAST-MODIFIED:20180213T144515Z
TRANSP:OPAQUE
END:VEVENT
* Fireflies @ GreenJackets
<2018-07-01 Sun 16:05-19:05>
:PROPERTIES:
:ID:       q8tgrSGEXux2cCpNE2S7FvL3@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Fireflies @ GreenJackets Fireflies @ GreenJackets

Follow on MiLB First Pitch  https //stza.co/+xBMG-3I

Shop  https //stza.co/+xBMG-2f

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Fireflies @ GreenJackets
END:VALARM
DTSTART:20180701T210500Z
DTEND:20180702T000500Z
UID:q8tgrSGEXux2cCpNE2S7FvL3@stanza.co
SUMMARY:Fireflies @ GreenJackets
DESCRIPTION:Fireflies @ GreenJackets\n\nFollow on MiLB First Pitch: https://stza.co/+xBMG-3I\n\nShop: https://stza.co/+xBMG-2f\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144515Z
LAST-MODIFIED:20180213T144515Z
TRANSP:OPAQUE
END:VEVENT
* Fireflies @ GreenJackets
<2018-07-02 Mon 18:05-21:05>
:PROPERTIES:
:ID:       91C8BsKY-D-R2BWrGIxM8s9j@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Fireflies @ GreenJackets Fireflies @ GreenJackets

Follow on MiLB First Pitch  https //stza.co/+xBMH-1g

Shop  https //stza.co/+xBMH-3F

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Fireflies @ GreenJackets
END:VALARM
DTSTART:20180702T230500Z
DTEND:20180703T020500Z
UID:91C8BsKY-D-R2BWrGIxM8s9j@stanza.co
SUMMARY:Fireflies @ GreenJackets
DESCRIPTION:Fireflies @ GreenJackets\n\nFollow on MiLB First Pitch: https://stza.co/+xBMH-1g\n\nShop: https://stza.co/+xBMH-3F\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144515Z
LAST-MODIFIED:20180213T144515Z
TRANSP:OPAQUE
END:VEVENT
* Fireflies @ GreenJackets
<2018-07-03 Tue 17:35-20:35>
:PROPERTIES:
:ID:       3xDgMdozx-4dJuRldMpTpceS@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Fireflies @ GreenJackets Fireflies @ GreenJackets

Follow on MiLB First Pitch  https //stza.co/+xBMI-3a

Shop  https //stza.co/+xBMI-11

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Fireflies @ GreenJackets
END:VALARM
DTSTART:20180703T223500Z
DTEND:20180704T013500Z
UID:3xDgMdozx-4dJuRldMpTpceS@stanza.co
SUMMARY:Fireflies @ GreenJackets
DESCRIPTION:Fireflies @ GreenJackets\n\nFollow on MiLB First Pitch: https://stza.co/+xBMI-3a\n\nShop: https://stza.co/+xBMI-11\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144515Z
LAST-MODIFIED:20180213T144515Z
TRANSP:OPAQUE
END:VEVENT
* Fireflies vs. Drive
<2018-07-04 Wed 17:05-20:05>
:PROPERTIES:
:ID:       LS5pDY0KGej6-OJolimbo8ib@stanza.co
:LOCATION: Independece Day Celebration
:STATUS:   CONFIRMED
:END:

Fireflies vs. Drive Enjoy a spectacular fireworks show and celebrate our nation's 242nd birthday with the Fireflies!

Follow on MiLB First Pitch  https //stza.co/+xBOJ-e

Shop  https //stza.co/+xBOJ-19

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Fireflies vs. Drive
END:VALARM
DTSTART:20180704T220500Z
DTEND:20180705T010500Z
UID:LS5pDY0KGej6-OJolimbo8ib@stanza.co
SUMMARY:Fireflies vs. Drive
DESCRIPTION:Enjoy a spectacular fireworks show and celebrate our nation's 242nd birthday with the Fireflies!\n\nFollow on MiLB First Pitch: https://stza.co/+xBOJ-e\n\nShop: https://stza.co/+xBOJ-19\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Independece Day Celebration
STATUS:CONFIRMED
CREATED:20180213T144515Z
LAST-MODIFIED:20180213T144515Z
TRANSP:OPAQUE
END:VEVENT
* Fireflies vs. Drive
<2018-07-05 Thu 18:05-21:05>
:PROPERTIES:
:ID:       c76xpOfBwtSD3mrIoJKyVIAZ@stanza.co
:LOCATION: Thirsty Thursday 
:STATUS:   CONFIRMED
:END:

Fireflies vs. Drive Enjoy half priced beer and fountain drinks! 

Follow on MiLB First Pitch  https //stza.co/+xBON-1I

Shop  https //stza.co/+xBON-H

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Fireflies vs. Drive
END:VALARM
DTSTART:20180705T230500Z
DTEND:20180706T020500Z
UID:c76xpOfBwtSD3mrIoJKyVIAZ@stanza.co
SUMMARY:Fireflies vs. Drive
DESCRIPTION:Enjoy half priced beer and fountain drinks! \n\nFollow on MiLB First Pitch: https://stza.co/+xBON-1I\n\nShop: https://stza.co/+xBON-H\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Thirsty Thursday 
STATUS:CONFIRMED
CREATED:20180213T144515Z
LAST-MODIFIED:20180213T144515Z
TRANSP:OPAQUE
END:VEVENT
* Fireflies vs. Drive
<2018-07-06 Fri 18:05-21:05>
:PROPERTIES:
:ID:       MyI_i-2xMCz0gPaivu5nGwxp@stanza.co
:LOCATION: Firework Friday's!
:STATUS:   CONFIRMED
:END:

Fireflies vs. Drive Enjoy fireworks after the game with your friends and family! It will be a blast! 

Enjoy America's Ballpark Prankster, as the spontaneous and unpredictable BirdZerk! pulls off hijinks with fans players, coaches, and umpires!

Follow on MiLB First Pitch  https //stza.co/+xBOQ-2G

Shop  https //stza.co/+xBOQ-3J

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Fireflies vs. Drive
END:VALARM
DTSTART:20180706T230500Z
DTEND:20180707T020500Z
UID:MyI_i-2xMCz0gPaivu5nGwxp@stanza.co
SUMMARY:Fireflies vs. Drive
DESCRIPTION:Enjoy fireworks after the game with your friends and family! It will be a blast! \n\nEnjoy America's Ballpark Prankster, as the spontaneous and unpredictable BirdZerk! pulls off hijinks with fans players, coaches, and umpires!\n\nFollow on MiLB First Pitch: https://stza.co/+xBOQ-2G\n\nShop: https://stza.co/+xBOQ-3J\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Firework Friday's!
STATUS:CONFIRMED
CREATED:20180213T144515Z
LAST-MODIFIED:20180213T144515Z
TRANSP:OPAQUE
END:VEVENT
* Fireflies vs. RiverDogs
<2018-07-07 Sat 17:05-20:05>
:PROPERTIES:
:ID:       WwCRlpc_m6oblteJ1DhaAjO0@stanza.co
:LOCATION: Superhero Night 
:STATUS:   CONFIRMED
:END:

Fireflies vs. RiverDogs Dress up as your favorite superhero and join other caped crusaders and masked crime fighters as they unite at Spirit Communications Park.  

Follow on MiLB First Pitch  https //stza.co/+xBOR-36

Shop  https //stza.co/+xBOR-2P

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Fireflies vs. RiverDogs
END:VALARM
DTSTART:20180707T220500Z
DTEND:20180708T010500Z
UID:WwCRlpc_m6oblteJ1DhaAjO0@stanza.co
SUMMARY:Fireflies vs. RiverDogs
DESCRIPTION:Dress up as your favorite superhero and join other caped crusaders and masked crime fighters as they unite at Spirit Communications Park.  \n\nFollow on MiLB First Pitch: https://stza.co/+xBOR-36\n\nShop: https://stza.co/+xBOR-2P\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Superhero Night 
STATUS:CONFIRMED
CREATED:20180213T144515Z
LAST-MODIFIED:20180213T144515Z
TRANSP:OPAQUE
END:VEVENT
* Fireflies vs. RiverDogs
<2018-07-08 Sun 13:05-16:05>
:PROPERTIES:
:ID:       pduU2V2sIvC3K4b1bDBsuCI3@stanza.co
:LOCATION: Sunday Splash Day's and Autographs
:STATUS:   CONFIRMED
:END:

Fireflies vs. RiverDogs Come get your favorite player's autograph and cool down in the Splash Zone during the game! 

Follow on MiLB First Pitch  https //stza.co/+xBOT-1_

Shop  https //stza.co/+xBOT-W

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Fireflies vs. RiverDogs
END:VALARM
DTSTART:20180708T180500Z
DTEND:20180708T210500Z
UID:pduU2V2sIvC3K4b1bDBsuCI3@stanza.co
SUMMARY:Fireflies vs. RiverDogs
DESCRIPTION:Come get your favorite player's autograph and cool down in the Splash Zone during the game! \n\nFollow on MiLB First Pitch: https://stza.co/+xBOT-1_\n\nShop: https://stza.co/+xBOT-W\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Sunday Splash Day's and Autographs
STATUS:CONFIRMED
CREATED:20180213T144515Z
LAST-MODIFIED:20180213T144515Z
TRANSP:OPAQUE
END:VEVENT
* Fireflies vs. RiverDogs
<2018-07-09 Mon 18:05-21:05>
:PROPERTIES:
:ID:       gTCY_nzOZVnET1m7KRFp4VSv@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Fireflies vs. RiverDogs Fireflies vs. RiverDogs

Follow on MiLB First Pitch  https //stza.co/+xBOW-3F

Shop  https //stza.co/+xBOW-3r

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Fireflies vs. RiverDogs
END:VALARM
DTSTART:20180709T230500Z
DTEND:20180710T020500Z
UID:gTCY_nzOZVnET1m7KRFp4VSv@stanza.co
SUMMARY:Fireflies vs. RiverDogs
DESCRIPTION:Fireflies vs. RiverDogs\n\nFollow on MiLB First Pitch: https://stza.co/+xBOW-3F\n\nShop: https://stza.co/+xBOW-3r\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144515Z
LAST-MODIFIED:20180213T144515Z
TRANSP:OPAQUE
END:VEVENT
* Fireflies @ Suns
<2018-07-11 Wed 18:05-21:05>
:PROPERTIES:
:ID:       _TDv7vW4StNUpPq8EnZdZBeG@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Fireflies @ Suns Fireflies @ Suns

Follow on MiLB First Pitch  https //stza.co/+xEZX-13

Shop  https //stza.co/+xEZX-1I

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Fireflies @ Suns
END:VALARM
DTSTART:20180711T230500Z
DTEND:20180712T020500Z
UID:_TDv7vW4StNUpPq8EnZdZBeG@stanza.co
SUMMARY:Fireflies @ Suns
DESCRIPTION:Fireflies @ Suns\n\nFollow on MiLB First Pitch: https://stza.co/+xEZX-13\n\nShop: https://stza.co/+xEZX-1I\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144515Z
LAST-MODIFIED:20180213T144515Z
TRANSP:OPAQUE
END:VEVENT
* Fireflies @ Suns
<2018-07-12 Thu 18:05-21:05>
:PROPERTIES:
:ID:       G63jZjKLvhSwbsQIaUnR84un@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Fireflies @ Suns Fireflies @ Suns

Follow on MiLB First Pitch  https //stza.co/+xEZY-1X

Shop  https //stza.co/+xEZY-2U

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Fireflies @ Suns
END:VALARM
DTSTART:20180712T230500Z
DTEND:20180713T020500Z
UID:G63jZjKLvhSwbsQIaUnR84un@stanza.co
SUMMARY:Fireflies @ Suns
DESCRIPTION:Fireflies @ Suns\n\nFollow on MiLB First Pitch: https://stza.co/+xEZY-1X\n\nShop: https://stza.co/+xEZY-2U\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144515Z
LAST-MODIFIED:20180213T144515Z
TRANSP:OPAQUE
END:VEVENT
* Fireflies @ Suns
<2018-07-13 Fri 18:05-21:05>
:PROPERTIES:
:ID:       jkMx-kaPZubOIAjEtR6GLplC@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Fireflies @ Suns Fireflies @ Suns

Follow on MiLB First Pitch  https //stza.co/+xEZZ-B

Shop  https //stza.co/+xEZZ-2x

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Fireflies @ Suns
END:VALARM
DTSTART:20180713T230500Z
DTEND:20180714T020500Z
UID:jkMx-kaPZubOIAjEtR6GLplC@stanza.co
SUMMARY:Fireflies @ Suns
DESCRIPTION:Fireflies @ Suns\n\nFollow on MiLB First Pitch: https://stza.co/+xEZZ-B\n\nShop: https://stza.co/+xEZZ-2x\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144515Z
LAST-MODIFIED:20180213T144515Z
TRANSP:OPAQUE
END:VEVENT
* Fireflies @ BlueClaws
<2018-07-14 Sat 18:05-21:05>
:PROPERTIES:
:ID:       RqDY_Lfd89iKJ4Amwq_SBNVF@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Fireflies @ BlueClaws Fireflies @ BlueClaws

Follow on MiLB First Pitch  https //stza.co/+vNFm-1z

Shop  https //stza.co/+vNFm-1$

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Fireflies @ BlueClaws
END:VALARM
DTSTART:20180714T230500Z
DTEND:20180715T020500Z
UID:RqDY_Lfd89iKJ4Amwq_SBNVF@stanza.co
SUMMARY:Fireflies @ BlueClaws
DESCRIPTION:Fireflies @ BlueClaws\n\nFollow on MiLB First Pitch: https://stza.co/+vNFm-1z\n\nShop: https://stza.co/+vNFm-1$\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144515Z
LAST-MODIFIED:20180213T144515Z
TRANSP:OPAQUE
END:VEVENT
* Fireflies @ BlueClaws
<2018-07-15 Sun 12:05-15:05>
:PROPERTIES:
:ID:       eggkX88-31RRvkuJFN0JLSwC@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Fireflies @ BlueClaws Fireflies @ BlueClaws

Follow on MiLB First Pitch  https //stza.co/+vNFn-2R

Shop  https //stza.co/+vNFn-15

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Fireflies @ BlueClaws
END:VALARM
DTSTART:20180715T170500Z
DTEND:20180715T200500Z
UID:eggkX88-31RRvkuJFN0JLSwC@stanza.co
SUMMARY:Fireflies @ BlueClaws
DESCRIPTION:Fireflies @ BlueClaws\n\nFollow on MiLB First Pitch: https://stza.co/+vNFn-2R\n\nShop: https://stza.co/+vNFn-15\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144515Z
LAST-MODIFIED:20180213T144515Z
TRANSP:OPAQUE
END:VEVENT
* Fireflies @ BlueClaws
<2018-07-16 Mon 18:05-21:05>
:PROPERTIES:
:ID:       -6TIBYhUyWcpNlSObjwa-sOR@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Fireflies @ BlueClaws Fireflies @ BlueClaws

Follow on MiLB First Pitch  https //stza.co/+vNFo-3T

Shop  https //stza.co/+vNFo-3W

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Fireflies @ BlueClaws
END:VALARM
DTSTART:20180716T230500Z
DTEND:20180717T020500Z
UID:-6TIBYhUyWcpNlSObjwa-sOR@stanza.co
SUMMARY:Fireflies @ BlueClaws
DESCRIPTION:Fireflies @ BlueClaws\n\nFollow on MiLB First Pitch: https://stza.co/+vNFo-3T\n\nShop: https://stza.co/+vNFo-3W\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144515Z
LAST-MODIFIED:20180213T144515Z
TRANSP:OPAQUE
END:VEVENT
* Fireflies @ BlueClaws
<2018-07-17 Tue 10:05-13:05>
:PROPERTIES:
:ID:       v9ocDtZ_WBXIdyfzDQW4oz64@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Fireflies @ BlueClaws Fireflies @ BlueClaws

Follow on MiLB First Pitch  https //stza.co/+vNFp-18

Shop  https //stza.co/+vNFp-z

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Fireflies @ BlueClaws
END:VALARM
DTSTART:20180717T150500Z
DTEND:20180717T180500Z
UID:v9ocDtZ_WBXIdyfzDQW4oz64@stanza.co
SUMMARY:Fireflies @ BlueClaws
DESCRIPTION:Fireflies @ BlueClaws\n\nFollow on MiLB First Pitch: https://stza.co/+vNFp-18\n\nShop: https://stza.co/+vNFp-z\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144515Z
LAST-MODIFIED:20180213T144515Z
TRANSP:OPAQUE
END:VEVENT
* Fireflies vs. GreenJackets
<2018-07-19 Thu 18:05-21:05>
:PROPERTIES:
:ID:       bTgA-bkPWv3PP1MLzIyiB-8m@stanza.co
:LOCATION: Thirsty Thursday 
:STATUS:   CONFIRMED
:END:

Fireflies vs. GreenJackets Enjoy half priced beer and fountain drinks! 

Follow on MiLB First Pitch  https //stza.co/+xBO_-2x

Shop  https //stza.co/+xBO_-2s

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Fireflies vs. GreenJackets
END:VALARM
DTSTART:20180719T230500Z
DTEND:20180720T020500Z
UID:bTgA-bkPWv3PP1MLzIyiB-8m@stanza.co
SUMMARY:Fireflies vs. GreenJackets
DESCRIPTION:Enjoy half priced beer and fountain drinks! \n\nFollow on MiLB First Pitch: https://stza.co/+xBO_-2x\n\nShop: https://stza.co/+xBO_-2s\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Thirsty Thursday 
STATUS:CONFIRMED
CREATED:20180213T144515Z
LAST-MODIFIED:20180213T144515Z
TRANSP:OPAQUE
END:VEVENT
* Fireflies vs. GreenJackets
<2018-07-20 Fri 18:05-21:05>
:PROPERTIES:
:ID:       3vsiV_ZciHYfY0ER4r9L9SKW@stanza.co
:LOCATION: Make your way to park for First Responders Night
:STATUS:   CONFIRMED
:END:

Fireflies vs. GreenJackets Enjoy fireworks after the game with your friends and family! It will be a blast! 

Enjoy a special night dedicated to the courageous men and women who keep us safe during emergencies! 

Follow on MiLB First Pitch  https //stza.co/+xBP2-2r

Shop  https //stza.co/+xBP2-3a

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Fireflies vs. GreenJackets
END:VALARM
DTSTART:20180720T230500Z
DTEND:20180721T020500Z
UID:3vsiV_ZciHYfY0ER4r9L9SKW@stanza.co
SUMMARY:Fireflies vs. GreenJackets
DESCRIPTION:Enjoy fireworks after the game with your friends and family! It will be a blast! \n\nEnjoy a special night dedicated to the courageous men and women who keep us safe during emergencies! \n\nFollow on MiLB First Pitch: https://stza.co/+xBP2-2r\n\nShop: https://stza.co/+xBP2-3a\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Make your way to park for First Responders Night
STATUS:CONFIRMED
CREATED:20180213T144515Z
LAST-MODIFIED:20180213T144515Z
TRANSP:OPAQUE
END:VEVENT
* Fireflies vs. GreenJackets
<2018-07-21 Sat 17:05-20:05>
:PROPERTIES:
:ID:       dSOpmt-OUpzyfh2WgHNwqmbN@stanza.co
:LOCATION: 80's Night 
:STATUS:   CONFIRMED
:END:

Fireflies vs. GreenJackets Enjoy iconic fads and music as the Fireflies help you relive your favorite memories from the 80s

Follow on MiLB First Pitch  https //stza.co/+xBP7-2N

Shop  https //stza.co/+xBP7-2O

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Fireflies vs. GreenJackets
END:VALARM
DTSTART:20180721T220500Z
DTEND:20180722T010500Z
UID:dSOpmt-OUpzyfh2WgHNwqmbN@stanza.co
SUMMARY:Fireflies vs. GreenJackets
DESCRIPTION:Enjoy iconic fads and music as the Fireflies help you relive your favorite memories from the 80s\n\nFollow on MiLB First Pitch: https://stza.co/+xBP7-2N\n\nShop: https://stza.co/+xBP7-2O\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:80's Night 
STATUS:CONFIRMED
CREATED:20180213T144515Z
LAST-MODIFIED:20180213T144515Z
TRANSP:OPAQUE
END:VEVENT
* Fireflies vs. GreenJackets
<2018-07-22 Sun 13:05-16:05>
:PROPERTIES:
:ID:       7lD4imDCItmt7bTcQv0wsdSt@stanza.co
:LOCATION: Sunday Splash Day's and Autographs
:STATUS:   CONFIRMED
:END:

Fireflies vs. GreenJackets Come get your favorite player's autograph and cool down in the Splash Zone during the game! 

Follow on MiLB First Pitch  https //stza.co/+xBPd-29

Shop  https //stza.co/+xBPd-3N

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Fireflies vs. GreenJackets
END:VALARM
DTSTART:20180722T180500Z
DTEND:20180722T210500Z
UID:7lD4imDCItmt7bTcQv0wsdSt@stanza.co
SUMMARY:Fireflies vs. GreenJackets
DESCRIPTION:Come get your favorite player's autograph and cool down in the Splash Zone during the game! \n\nFollow on MiLB First Pitch: https://stza.co/+xBPd-29\n\nShop: https://stza.co/+xBPd-3N\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Sunday Splash Day's and Autographs
STATUS:CONFIRMED
CREATED:20180213T144515Z
LAST-MODIFIED:20180213T144515Z
TRANSP:OPAQUE
END:VEVENT
* Fireflies @ Braves
<2018-07-23 Mon 18:00-21:00>
:PROPERTIES:
:ID:       0ZATOUjZ3oGG-OwG3s2rGIPz@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Fireflies @ Braves Fireflies @ Braves

Follow on MiLB First Pitch  https //stza.co/+vNFA-X

Shop  https //stza.co/+vNFA-3O

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Fireflies @ Braves
END:VALARM
DTSTART:20180723T230000Z
DTEND:20180724T020000Z
UID:0ZATOUjZ3oGG-OwG3s2rGIPz@stanza.co
SUMMARY:Fireflies @ Braves
DESCRIPTION:Fireflies @ Braves\n\nFollow on MiLB First Pitch: https://stza.co/+vNFA-X\n\nShop: https://stza.co/+vNFA-3O\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144515Z
LAST-MODIFIED:20180213T144515Z
TRANSP:OPAQUE
END:VEVENT
* Fireflies @ Braves
<2018-07-24 Tue 18:00-21:00>
:PROPERTIES:
:ID:       8-G9T_jNI9mhO7MQWJWkcQDK@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Fireflies @ Braves Fireflies @ Braves

Follow on MiLB First Pitch  https //stza.co/+vNFB-2P

Shop  https //stza.co/+vNFB-R

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Fireflies @ Braves
END:VALARM
DTSTART:20180724T230000Z
DTEND:20180725T020000Z
UID:8-G9T_jNI9mhO7MQWJWkcQDK@stanza.co
SUMMARY:Fireflies @ Braves
DESCRIPTION:Fireflies @ Braves\n\nFollow on MiLB First Pitch: https://stza.co/+vNFB-2P\n\nShop: https://stza.co/+vNFB-R\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144515Z
LAST-MODIFIED:20180213T144515Z
TRANSP:OPAQUE
END:VEVENT
* Fireflies @ Braves
<2018-07-25 Wed 12:00-15:00>
:PROPERTIES:
:ID:       EEM_FRWoAPCorgiGIN8vpqpG@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Fireflies @ Braves Fireflies @ Braves

Follow on MiLB First Pitch  https //stza.co/+vNFC-3F

Shop  https //stza.co/+vNFC-39

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Fireflies @ Braves
END:VALARM
DTSTART:20180725T170000Z
DTEND:20180725T200000Z
UID:EEM_FRWoAPCorgiGIN8vpqpG@stanza.co
SUMMARY:Fireflies @ Braves
DESCRIPTION:Fireflies @ Braves\n\nFollow on MiLB First Pitch: https://stza.co/+vNFC-3F\n\nShop: https://stza.co/+vNFC-39\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144515Z
LAST-MODIFIED:20180213T144515Z
TRANSP:OPAQUE
END:VEVENT
* Fireflies @ Braves
<2018-07-26 Thu 18:00-21:00>
:PROPERTIES:
:ID:       aHOcPJxD9gmj2TDsZqq9eX_6@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Fireflies @ Braves Fireflies @ Braves

Follow on MiLB First Pitch  https //stza.co/+vNFD-t

Shop  https //stza.co/+vNFD-12

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Fireflies @ Braves
END:VALARM
DTSTART:20180726T230000Z
DTEND:20180727T020000Z
UID:aHOcPJxD9gmj2TDsZqq9eX_6@stanza.co
SUMMARY:Fireflies @ Braves
DESCRIPTION:Fireflies @ Braves\n\nFollow on MiLB First Pitch: https://stza.co/+vNFD-t\n\nShop: https://stza.co/+vNFD-12\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144515Z
LAST-MODIFIED:20180213T144515Z
TRANSP:OPAQUE
END:VEVENT
* Fireflies @ GreenJackets
<2018-07-27 Fri 18:05-21:05>
:PROPERTIES:
:ID:       p_-fu-dHgwUJInzKxSSINt8w@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Fireflies @ GreenJackets Fireflies @ GreenJackets

Follow on MiLB First Pitch  https //stza.co/+xBMJ-1R

Shop  https //stza.co/+xBMJ-V

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Fireflies @ GreenJackets
END:VALARM
DTSTART:20180727T230500Z
DTEND:20180728T020500Z
UID:p_-fu-dHgwUJInzKxSSINt8w@stanza.co
SUMMARY:Fireflies @ GreenJackets
DESCRIPTION:Fireflies @ GreenJackets\n\nFollow on MiLB First Pitch: https://stza.co/+xBMJ-1R\n\nShop: https://stza.co/+xBMJ-V\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144515Z
LAST-MODIFIED:20180213T144515Z
TRANSP:OPAQUE
END:VEVENT
* Fireflies @ GreenJackets
<2018-07-28 Sat 17:05-20:05>
:PROPERTIES:
:ID:       PxVknnQDbQmVvUs8XlaRmc4W@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Fireflies @ GreenJackets Fireflies @ GreenJackets

Follow on MiLB First Pitch  https //stza.co/+xBMK-j

Shop  https //stza.co/+xBMK-1q

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Fireflies @ GreenJackets
END:VALARM
DTSTART:20180728T220500Z
DTEND:20180729T010500Z
UID:PxVknnQDbQmVvUs8XlaRmc4W@stanza.co
SUMMARY:Fireflies @ GreenJackets
DESCRIPTION:Fireflies @ GreenJackets\n\nFollow on MiLB First Pitch: https://stza.co/+xBMK-j\n\nShop: https://stza.co/+xBMK-1q\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144515Z
LAST-MODIFIED:20180213T144515Z
TRANSP:OPAQUE
END:VEVENT
* Fireflies @ GreenJackets
<2018-07-29 Sun 16:05-19:05>
:PROPERTIES:
:ID:       K7rigAfCwllTeZWol2g0qzSe@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Fireflies @ GreenJackets Fireflies @ GreenJackets

Follow on MiLB First Pitch  https //stza.co/+xBML-1V

Shop  https //stza.co/+xBML-l

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Fireflies @ GreenJackets
END:VALARM
DTSTART:20180729T210500Z
DTEND:20180730T000500Z
UID:K7rigAfCwllTeZWol2g0qzSe@stanza.co
SUMMARY:Fireflies @ GreenJackets
DESCRIPTION:Fireflies @ GreenJackets\n\nFollow on MiLB First Pitch: https://stza.co/+xBML-1V\n\nShop: https://stza.co/+xBML-l\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144515Z
LAST-MODIFIED:20180213T144515Z
TRANSP:OPAQUE
END:VEVENT
* Fireflies vs. Power
<2018-07-30 Mon 18:05-21:05>
:PROPERTIES:
:ID:       7P1HJzhjEUGf9cyiUTeF7pa4@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Fireflies vs. Power Fireflies vs. Power

Follow on MiLB First Pitch  https //stza.co/+xBPj-3c

Shop  https //stza.co/+xBPj-2O

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Fireflies vs. Power
END:VALARM
DTSTART:20180730T230500Z
DTEND:20180731T020500Z
UID:7P1HJzhjEUGf9cyiUTeF7pa4@stanza.co
SUMMARY:Fireflies vs. Power
DESCRIPTION:Fireflies vs. Power\n\nFollow on MiLB First Pitch: https://stza.co/+xBPj-3c\n\nShop: https://stza.co/+xBPj-2O\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144515Z
LAST-MODIFIED:20180213T144515Z
TRANSP:OPAQUE
END:VEVENT
* Fireflies vs. Power
<2018-07-31 Tue 18:05-21:05>
:PROPERTIES:
:ID:       Jvc9dsoIVhsEER_tvMSTHOod@stanza.co
:LOCATION: $2 Tuesday!
:STATUS:   CONFIRMED
:END:

Fireflies vs. Power Enjoy $2.00 hotdogs, fountain drinks and popcorn all game! 

Follow on MiLB First Pitch  https //stza.co/+xBPo-1J

Shop  https //stza.co/+xBPo-6

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Fireflies vs. Power
END:VALARM
DTSTART:20180731T230500Z
DTEND:20180801T020500Z
UID:Jvc9dsoIVhsEER_tvMSTHOod@stanza.co
SUMMARY:Fireflies vs. Power
DESCRIPTION:Enjoy $2.00 hotdogs, fountain drinks and popcorn all game! \n\nFollow on MiLB First Pitch: https://stza.co/+xBPo-1J\n\nShop: https://stza.co/+xBPo-6\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:$2 Tuesday!
STATUS:CONFIRMED
CREATED:20180213T144515Z
LAST-MODIFIED:20180213T144515Z
TRANSP:OPAQUE
END:VEVENT
* Fireflies vs. Power
<2018-08-01 Wed 18:05-21:05>
:PROPERTIES:
:ID:       Py3TrK3NyiH3ayAihHhQHoL1@stanza.co
:LOCATION: Wag-Along Wednesday
:STATUS:   CONFIRMED
:END:

Fireflies vs. Power Bring your dog to the game with you! 

Follow on MiLB First Pitch  https //stza.co/+xBPu-3x

Shop  https //stza.co/+xBPu-3Z

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Fireflies vs. Power
END:VALARM
DTSTART:20180801T230500Z
DTEND:20180802T020500Z
UID:Py3TrK3NyiH3ayAihHhQHoL1@stanza.co
SUMMARY:Fireflies vs. Power
DESCRIPTION:Bring your dog to the game with you! \n\nFollow on MiLB First Pitch: https://stza.co/+xBPu-3x\n\nShop: https://stza.co/+xBPu-3Z\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Wag-Along Wednesday
STATUS:CONFIRMED
CREATED:20180213T144515Z
LAST-MODIFIED:20180213T144515Z
TRANSP:OPAQUE
END:VEVENT
* Fireflies @ Tourists
<2018-08-02 Thu 18:05-21:05>
:PROPERTIES:
:ID:       mq6dDBI-YN6MP5JZWIz6FmJJ@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Fireflies @ Tourists Fireflies @ Tourists

Follow on MiLB First Pitch  https //stza.co/+vNCt-2C

Shop  https //stza.co/+vNCt-C

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Fireflies @ Tourists
END:VALARM
DTSTART:20180802T230500Z
DTEND:20180803T020500Z
UID:mq6dDBI-YN6MP5JZWIz6FmJJ@stanza.co
SUMMARY:Fireflies @ Tourists
DESCRIPTION:Fireflies @ Tourists\n\nFollow on MiLB First Pitch: https://stza.co/+vNCt-2C\n\nShop: https://stza.co/+vNCt-C\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144515Z
LAST-MODIFIED:20180213T144515Z
TRANSP:OPAQUE
END:VEVENT
* Fireflies @ Tourists
<2018-08-03 Fri 18:05-21:05>
:PROPERTIES:
:ID:       J6UpV3z3Lm9y4GtN-7QQMEiZ@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Fireflies @ Tourists Fireflies @ Tourists

Follow on MiLB First Pitch  https //stza.co/+vNCu-2j

Shop  https //stza.co/+vNCu-1a

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Fireflies @ Tourists
END:VALARM
DTSTART:20180803T230500Z
DTEND:20180804T020500Z
UID:J6UpV3z3Lm9y4GtN-7QQMEiZ@stanza.co
SUMMARY:Fireflies @ Tourists
DESCRIPTION:Fireflies @ Tourists\n\nFollow on MiLB First Pitch: https://stza.co/+vNCu-2j\n\nShop: https://stza.co/+vNCu-1a\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144515Z
LAST-MODIFIED:20180213T144515Z
TRANSP:OPAQUE
END:VEVENT
* Fireflies @ Tourists
<2018-08-04 Sat 17:05-20:05>
:PROPERTIES:
:ID:       W_ZShZVlUVHhVAHs_B21m700@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Fireflies @ Tourists Fireflies @ Tourists

Follow on MiLB First Pitch  https //stza.co/+vNCv-P

Shop  https //stza.co/+vNCv-39

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Fireflies @ Tourists
END:VALARM
DTSTART:20180804T220500Z
DTEND:20180805T010500Z
UID:W_ZShZVlUVHhVAHs_B21m700@stanza.co
SUMMARY:Fireflies @ Tourists
DESCRIPTION:Fireflies @ Tourists\n\nFollow on MiLB First Pitch: https://stza.co/+vNCv-P\n\nShop: https://stza.co/+vNCv-39\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144515Z
LAST-MODIFIED:20180213T144515Z
TRANSP:OPAQUE
END:VEVENT
* Fireflies @ Tourists
<2018-08-05 Sun 13:05-16:05>
:PROPERTIES:
:ID:       9X7Gf_NHA68cP-f21Hz81iti@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Fireflies @ Tourists Fireflies @ Tourists

Follow on MiLB First Pitch  https //stza.co/+vNCw-3G

Shop  https //stza.co/+vNCw-1G

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Fireflies @ Tourists
END:VALARM
DTSTART:20180805T180500Z
DTEND:20180805T210500Z
UID:9X7Gf_NHA68cP-f21Hz81iti@stanza.co
SUMMARY:Fireflies @ Tourists
DESCRIPTION:Fireflies @ Tourists\n\nFollow on MiLB First Pitch: https://stza.co/+vNCw-3G\n\nShop: https://stza.co/+vNCw-1G\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144515Z
LAST-MODIFIED:20180213T144515Z
TRANSP:OPAQUE
END:VEVENT
* Fireflies vs. Drive
<2018-08-07 Tue 18:05-21:05>
:PROPERTIES:
:ID:       bvhFrb67bZW80C9HKlQQRk_8@stanza.co
:LOCATION: $2 Tuesday!
:STATUS:   CONFIRMED
:END:

Fireflies vs. Drive Enjoy $2.00 hotdogs, fountain drinks and popcorn all game! 

Follow on MiLB First Pitch  https //stza.co/+xA$E-J

Shop  https //stza.co/+xA$E-6

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Fireflies vs. Drive
END:VALARM
DTSTART:20180807T230500Z
DTEND:20180808T020500Z
UID:bvhFrb67bZW80C9HKlQQRk_8@stanza.co
SUMMARY:Fireflies vs. Drive
DESCRIPTION:Enjoy $2.00 hotdogs, fountain drinks and popcorn all game! \n\nFollow on MiLB First Pitch: https://stza.co/+xA$E-J\n\nShop: https://stza.co/+xA$E-6\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:$2 Tuesday!
STATUS:CONFIRMED
CREATED:20180213T144515Z
LAST-MODIFIED:20180213T144515Z
TRANSP:OPAQUE
END:VEVENT
* Fireflies vs. Drive
<2018-08-08 Wed 18:05-21:05>
:PROPERTIES:
:ID:       X4NUkoYVs7rXslAzilk4p_VI@stanza.co
:LOCATION: Wag-Along Wednesday
:STATUS:   CONFIRMED
:END:

Fireflies vs. Drive Bring your dog to the game with you! 

If you can dodge a wrench, you can dodge a 100 mph fastball. 

Follow on MiLB First Pitch  https //stza.co/+xA$G-2$

Shop  https //stza.co/+xA$G-2A

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Fireflies vs. Drive
END:VALARM
DTSTART:20180808T230500Z
DTEND:20180809T020500Z
UID:X4NUkoYVs7rXslAzilk4p_VI@stanza.co
SUMMARY:Fireflies vs. Drive
DESCRIPTION:Bring your dog to the game with you! \n\nIf you can dodge a wrench, you can dodge a 100 mph fastball. \n\nFollow on MiLB First Pitch: https://stza.co/+xA$G-2$\n\nShop: https://stza.co/+xA$G-2A\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Wag-Along Wednesday
STATUS:CONFIRMED
CREATED:20180213T144515Z
LAST-MODIFIED:20180213T144515Z
TRANSP:OPAQUE
END:VEVENT
* Fireflies vs. Drive
<2018-08-09 Thu 18:05-21:05>
:PROPERTIES:
:ID:       -pInrmhnealH2maCe7CJcG0M@stanza.co
:LOCATION: Thirsty Thursday 
:STATUS:   CONFIRMED
:END:

Fireflies vs. Drive Enjoy half priced beer and fountain drinks! 

Follow on MiLB First Pitch  https //stza.co/+xA$I-1s

Shop  https //stza.co/+xA$I-2M

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Fireflies vs. Drive
END:VALARM
DTSTART:20180809T230500Z
DTEND:20180810T020500Z
UID:-pInrmhnealH2maCe7CJcG0M@stanza.co
SUMMARY:Fireflies vs. Drive
DESCRIPTION:Enjoy half priced beer and fountain drinks! \n\nFollow on MiLB First Pitch: https://stza.co/+xA$I-1s\n\nShop: https://stza.co/+xA$I-2M\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Thirsty Thursday 
STATUS:CONFIRMED
CREATED:20180213T144515Z
LAST-MODIFIED:20180213T144515Z
TRANSP:OPAQUE
END:VEVENT
* Fireflies vs. Shorebirds
<2018-08-10 Fri 18:05-21:05>
:PROPERTIES:
:ID:       sg2F2IPA_AfwImBp0XedT_K4@stanza.co
:LOCATION: Firework Friday's!
:STATUS:   CONFIRMED
:END:

Fireflies vs. Shorebirds Enjoy fireworks after the game with your friends and family! It will be a blast! 

Follow on MiLB First Pitch  https //stza.co/+xA$J-1k

Shop  https //stza.co/+xA$J-1J

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Fireflies vs. Shorebirds
END:VALARM
DTSTART:20180810T230500Z
DTEND:20180811T020500Z
UID:sg2F2IPA_AfwImBp0XedT_K4@stanza.co
SUMMARY:Fireflies vs. Shorebirds
DESCRIPTION:Enjoy fireworks after the game with your friends and family! It will be a blast! \n\nFollow on MiLB First Pitch: https://stza.co/+xA$J-1k\n\nShop: https://stza.co/+xA$J-1J\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Firework Friday's!
STATUS:CONFIRMED
CREATED:20180213T144515Z
LAST-MODIFIED:20180213T144515Z
TRANSP:OPAQUE
END:VEVENT
* Fireflies vs. Shorebirds
<2018-08-11 Sat 17:05-20:05>
:PROPERTIES:
:ID:       f3qgG-H9jTC4ycsoVIo2lEdF@stanza.co
:LOCATION: Celebrate the Soda City
:STATUS:   CONFIRMED
:END:

Fireflies vs. Shorebirds Celebrate our city at the game!

Follow on MiLB First Pitch  https //stza.co/+xA$L-3A

Shop  https //stza.co/+xA$L-3C

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Fireflies vs. Shorebirds
END:VALARM
DTSTART:20180811T220500Z
DTEND:20180812T010500Z
UID:f3qgG-H9jTC4ycsoVIo2lEdF@stanza.co
SUMMARY:Fireflies vs. Shorebirds
DESCRIPTION:Celebrate our city at the game!\n\nFollow on MiLB First Pitch: https://stza.co/+xA$L-3A\n\nShop: https://stza.co/+xA$L-3C\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Celebrate the Soda City
STATUS:CONFIRMED
CREATED:20180213T144515Z
LAST-MODIFIED:20180213T144515Z
TRANSP:OPAQUE
END:VEVENT
* Fireflies vs. Shorebirds
<2018-08-12 Sun 13:05-16:05>
:PROPERTIES:
:ID:       v1uYuP8gxVm_cCen_gbK3IJa@stanza.co
:LOCATION: Sunday Splash Day's and Autographs
:STATUS:   CONFIRMED
:END:

Fireflies vs. Shorebirds Come get your favorite player's autograph and cool down in the Splash Zone during the game! 

Follow on MiLB First Pitch  https //stza.co/+xA$N-29

Shop  https //stza.co/+xA$N-10

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Fireflies vs. Shorebirds
END:VALARM
DTSTART:20180812T180500Z
DTEND:20180812T210500Z
UID:v1uYuP8gxVm_cCen_gbK3IJa@stanza.co
SUMMARY:Fireflies vs. Shorebirds
DESCRIPTION:Come get your favorite player's autograph and cool down in the Splash Zone during the game! \n\nFollow on MiLB First Pitch: https://stza.co/+xA$N-29\n\nShop: https://stza.co/+xA$N-10\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Sunday Splash Day's and Autographs
STATUS:CONFIRMED
CREATED:20180213T144515Z
LAST-MODIFIED:20180213T144515Z
TRANSP:OPAQUE
END:VEVENT
* Fireflies vs. Shorebirds
<2018-08-13 Mon 18:05-21:05>
:PROPERTIES:
:ID:       sQ4O6daZ0d18Ed25iwLieJpG@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Fireflies vs. Shorebirds Fireflies vs. Shorebirds

Follow on MiLB First Pitch  https //stza.co/+xA$P-p

Shop  https //stza.co/+xA$P-3Q

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Fireflies vs. Shorebirds
END:VALARM
DTSTART:20180813T230500Z
DTEND:20180814T020500Z
UID:sQ4O6daZ0d18Ed25iwLieJpG@stanza.co
SUMMARY:Fireflies vs. Shorebirds
DESCRIPTION:Fireflies vs. Shorebirds\n\nFollow on MiLB First Pitch: https://stza.co/+xA$P-p\n\nShop: https://stza.co/+xA$P-3Q\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144515Z
LAST-MODIFIED:20180213T144515Z
TRANSP:OPAQUE
END:VEVENT
* Fireflies @ Power
<2018-08-15 Wed 18:05-21:05>
:PROPERTIES:
:ID:       YDSMiQbIS4Qs1XxZoiR5S9KI@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Fireflies @ Power Fireflies @ Power

Follow on MiLB First Pitch  https //stza.co/+xJ3C-1Y

Shop  https //stza.co/+xJ3C-3g

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Fireflies @ Power
END:VALARM
DTSTART:20180815T230500Z
DTEND:20180816T020500Z
UID:YDSMiQbIS4Qs1XxZoiR5S9KI@stanza.co
SUMMARY:Fireflies @ Power
DESCRIPTION:Fireflies @ Power\n\nFollow on MiLB First Pitch: https://stza.co/+xJ3C-1Y\n\nShop: https://stza.co/+xJ3C-3g\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144515Z
LAST-MODIFIED:20180213T144515Z
TRANSP:OPAQUE
END:VEVENT
* Fireflies @ Power
<2018-08-16 Thu 18:05-21:05>
:PROPERTIES:
:ID:       abILN6CLaKht0YiKGT8pziEk@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Fireflies @ Power Fireflies @ Power

Follow on MiLB First Pitch  https //stza.co/+xJ3D-35

Shop  https //stza.co/+xJ3D-17

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Fireflies @ Power
END:VALARM
DTSTART:20180816T230500Z
DTEND:20180817T020500Z
UID:abILN6CLaKht0YiKGT8pziEk@stanza.co
SUMMARY:Fireflies @ Power
DESCRIPTION:Fireflies @ Power\n\nFollow on MiLB First Pitch: https://stza.co/+xJ3D-35\n\nShop: https://stza.co/+xJ3D-17\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144515Z
LAST-MODIFIED:20180213T144515Z
TRANSP:OPAQUE
END:VEVENT
* Fireflies @ Power
<2018-08-17 Fri 18:05-21:05>
:PROPERTIES:
:ID:       B5ZsRmk0JP7eV8ept4E_wJmh@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Fireflies @ Power Fireflies @ Power

Follow on MiLB First Pitch  https //stza.co/+xJ3E-3x

Shop  https //stza.co/+xJ3E-1_

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Fireflies @ Power
END:VALARM
DTSTART:20180817T230500Z
DTEND:20180818T020500Z
UID:B5ZsRmk0JP7eV8ept4E_wJmh@stanza.co
SUMMARY:Fireflies @ Power
DESCRIPTION:Fireflies @ Power\n\nFollow on MiLB First Pitch: https://stza.co/+xJ3E-3x\n\nShop: https://stza.co/+xJ3E-1_\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144515Z
LAST-MODIFIED:20180213T144515Z
TRANSP:OPAQUE
END:VEVENT
* Fireflies @ Suns
<2018-08-18 Sat 17:05-20:05>
:PROPERTIES:
:ID:       fqTvtXO78vScbCZutRNJ0hRz@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Fireflies @ Suns Fireflies @ Suns

Follow on MiLB First Pitch  https //stza.co/+xEZ_-12

Shop  https //stza.co/+xEZ_-Y

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Fireflies @ Suns
END:VALARM
DTSTART:20180818T220500Z
DTEND:20180819T010500Z
UID:fqTvtXO78vScbCZutRNJ0hRz@stanza.co
SUMMARY:Fireflies @ Suns
DESCRIPTION:Fireflies @ Suns\n\nFollow on MiLB First Pitch: https://stza.co/+xEZ_-12\n\nShop: https://stza.co/+xEZ_-Y\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144515Z
LAST-MODIFIED:20180213T144515Z
TRANSP:OPAQUE
END:VEVENT
* Fireflies @ Suns
<2018-08-19 Sun 13:05-16:05>
:PROPERTIES:
:ID:       UldwnHuh6-zR1CsXASHSlqFh@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Fireflies @ Suns Fireflies @ Suns

Follow on MiLB First Pitch  https //stza.co/+xEZ$-1l

Shop  https //stza.co/+xEZ$-27

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Fireflies @ Suns
END:VALARM
DTSTART:20180819T180500Z
DTEND:20180819T210500Z
UID:UldwnHuh6-zR1CsXASHSlqFh@stanza.co
SUMMARY:Fireflies @ Suns
DESCRIPTION:Fireflies @ Suns\n\nFollow on MiLB First Pitch: https://stza.co/+xEZ$-1l\n\nShop: https://stza.co/+xEZ$-27\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144515Z
LAST-MODIFIED:20180213T144515Z
TRANSP:OPAQUE
END:VEVENT
* Fireflies @ Suns
<2018-08-20 Mon 18:05-21:05>
:PROPERTIES:
:ID:       dpLxiDSs4JtUdq-xQnc2ZXnh@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Fireflies @ Suns Fireflies @ Suns

Follow on MiLB First Pitch  https //stza.co/+xE_0-1$

Shop  https //stza.co/+xE_0-1T

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Fireflies @ Suns
END:VALARM
DTSTART:20180820T230500Z
DTEND:20180821T020500Z
UID:dpLxiDSs4JtUdq-xQnc2ZXnh@stanza.co
SUMMARY:Fireflies @ Suns
DESCRIPTION:Fireflies @ Suns\n\nFollow on MiLB First Pitch: https://stza.co/+xE_0-1$\n\nShop: https://stza.co/+xE_0-1T\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144515Z
LAST-MODIFIED:20180213T144515Z
TRANSP:OPAQUE
END:VEVENT
* Fireflies @ Suns
<2018-08-21 Tue 13:05-16:05>
:PROPERTIES:
:ID:       S996Sy5pd6M3QKSfgLENu4_T@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Fireflies @ Suns Fireflies @ Suns

Follow on MiLB First Pitch  https //stza.co/+xE_1-x

Shop  https //stza.co/+xE_1-W

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Fireflies @ Suns
END:VALARM
DTSTART:20180821T180500Z
DTEND:20180821T210500Z
UID:S996Sy5pd6M3QKSfgLENu4_T@stanza.co
SUMMARY:Fireflies @ Suns
DESCRIPTION:Fireflies @ Suns\n\nFollow on MiLB First Pitch: https://stza.co/+xE_1-x\n\nShop: https://stza.co/+xE_1-W\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144515Z
LAST-MODIFIED:20180213T144515Z
TRANSP:OPAQUE
END:VEVENT
* Fireflies vs. Tourists
<2018-08-23 Thu 18:05-21:05>
:PROPERTIES:
:ID:       7m0qpJsn9oo_5FMAtWU5Wa8g@stanza.co
:LOCATION: Thirsty Thursday 
:STATUS:   CONFIRMED
:END:

Fireflies vs. Tourists Enjoy half priced beer and fountain drinks! 

Follow on MiLB First Pitch  https //stza.co/+xA$T-v

Shop  https //stza.co/+xA$T-15

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Fireflies vs. Tourists
END:VALARM
DTSTART:20180823T230500Z
DTEND:20180824T020500Z
UID:7m0qpJsn9oo_5FMAtWU5Wa8g@stanza.co
SUMMARY:Fireflies vs. Tourists
DESCRIPTION:Enjoy half priced beer and fountain drinks! \n\nFollow on MiLB First Pitch: https://stza.co/+xA$T-v\n\nShop: https://stza.co/+xA$T-15\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Thirsty Thursday 
STATUS:CONFIRMED
CREATED:20180213T144515Z
LAST-MODIFIED:20180213T144515Z
TRANSP:OPAQUE
END:VEVENT
* Fireflies vs. Tourists
<2018-08-24 Fri 18:05-21:05>
:PROPERTIES:
:ID:       Qtuadkl5auz8ucNacJi5x5t4@stanza.co
:LOCATION: Firework Friday's!
:STATUS:   CONFIRMED
:END:

Fireflies vs. Tourists Enjoy fireworks after the game with your friends and family! It will be a blast! 

Enjoy one of the most famous traveling entertainment acts in sports, and see baseball legends reimagined! 

Follow on MiLB First Pitch  https //stza.co/+xA$W-3e

Shop  https //stza.co/+xA$W-2o

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Fireflies vs. Tourists
END:VALARM
DTSTART:20180824T230500Z
DTEND:20180825T020500Z
UID:Qtuadkl5auz8ucNacJi5x5t4@stanza.co
SUMMARY:Fireflies vs. Tourists
DESCRIPTION:Enjoy fireworks after the game with your friends and family! It will be a blast! \n\nEnjoy one of the most famous traveling entertainment acts in sports, and see baseball legends reimagined! \n\nFollow on MiLB First Pitch: https://stza.co/+xA$W-3e\n\nShop: https://stza.co/+xA$W-2o\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Firework Friday's!
STATUS:CONFIRMED
CREATED:20180213T144515Z
LAST-MODIFIED:20180213T144515Z
TRANSP:OPAQUE
END:VEVENT
* Fireflies vs. Tourists
<2018-08-25 Sat 17:05-20:05>
:PROPERTIES:
:ID:       O1R831F4fT3xB4LIpkNnEJil@stanza.co
:LOCATION: Zoo Night
:STATUS:   CONFIRMED
:END:

Fireflies vs. Tourists The Fireflies and Riverbanks Zoo celebrate our favorite animals during the game! 

Follow on MiLB First Pitch  https //stza.co/+xA$X-1x

Shop  https //stza.co/+xA$X-21

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Fireflies vs. Tourists
END:VALARM
DTSTART:20180825T220500Z
DTEND:20180826T010500Z
UID:O1R831F4fT3xB4LIpkNnEJil@stanza.co
SUMMARY:Fireflies vs. Tourists
DESCRIPTION:The Fireflies and Riverbanks Zoo celebrate our favorite animals during the game! \n\nFollow on MiLB First Pitch: https://stza.co/+xA$X-1x\n\nShop: https://stza.co/+xA$X-21\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Zoo Night
STATUS:CONFIRMED
CREATED:20180213T144515Z
LAST-MODIFIED:20180213T144515Z
TRANSP:OPAQUE
END:VEVENT
* Fireflies vs. Tourists
<2018-08-26 Sun 13:05-16:05>
:PROPERTIES:
:ID:       nCOJlhO_pdRE-Z9zhJhmPfG0@stanza.co
:LOCATION: Sunday Splash Day's and Autographs
:STATUS:   CONFIRMED
:END:

Fireflies vs. Tourists Come get your favorite player's autograph and cool down in the Splash Zone during the game! 

Follow on MiLB First Pitch  https //stza.co/+xA$Z-2X

Shop  https //stza.co/+xA$Z-s

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Fireflies vs. Tourists
END:VALARM
DTSTART:20180826T180500Z
DTEND:20180826T210500Z
UID:nCOJlhO_pdRE-Z9zhJhmPfG0@stanza.co
SUMMARY:Fireflies vs. Tourists
DESCRIPTION:Come get your favorite player's autograph and cool down in the Splash Zone during the game! \n\nFollow on MiLB First Pitch: https://stza.co/+xA$Z-2X\n\nShop: https://stza.co/+xA$Z-s\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Sunday Splash Day's and Autographs
STATUS:CONFIRMED
CREATED:20180213T144515Z
LAST-MODIFIED:20180213T144515Z
TRANSP:OPAQUE
END:VEVENT
* Fireflies vs. RiverDogs
<2018-08-27 Mon 18:05-21:05>
:PROPERTIES:
:ID:       SV_A8-l0hPGDMdWOz7UG3Df2@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Fireflies vs. RiverDogs Fireflies vs. RiverDogs

Follow on MiLB First Pitch  https //stza.co/+xB00-2p

Shop  https //stza.co/+xB00-3E

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Fireflies vs. RiverDogs
END:VALARM
DTSTART:20180827T230500Z
DTEND:20180828T020500Z
UID:SV_A8-l0hPGDMdWOz7UG3Df2@stanza.co
SUMMARY:Fireflies vs. RiverDogs
DESCRIPTION:Fireflies vs. RiverDogs\n\nFollow on MiLB First Pitch: https://stza.co/+xB00-2p\n\nShop: https://stza.co/+xB00-3E\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144515Z
LAST-MODIFIED:20180213T144515Z
TRANSP:OPAQUE
END:VEVENT
* Fireflies vs. RiverDogs
<2018-08-28 Tue 18:05-21:05>
:PROPERTIES:
:ID:       G79MMAKn84_c7Feada0RByJj@stanza.co
:LOCATION: $2 Tuesday!
:STATUS:   CONFIRMED
:END:

Fireflies vs. RiverDogs Enjoy $2.00 hotdogs, fountain drinks and popcorn all game! 

Follow on MiLB First Pitch  https //stza.co/+xB03-1V

Shop  https //stza.co/+xB03-Y

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Fireflies vs. RiverDogs
END:VALARM
DTSTART:20180828T230500Z
DTEND:20180829T020500Z
UID:G79MMAKn84_c7Feada0RByJj@stanza.co
SUMMARY:Fireflies vs. RiverDogs
DESCRIPTION:Enjoy $2.00 hotdogs, fountain drinks and popcorn all game! \n\nFollow on MiLB First Pitch: https://stza.co/+xB03-1V\n\nShop: https://stza.co/+xB03-Y\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:$2 Tuesday!
STATUS:CONFIRMED
CREATED:20180213T144515Z
LAST-MODIFIED:20180213T144515Z
TRANSP:OPAQUE
END:VEVENT
* Fireflies vs. RiverDogs
<2018-08-29 Wed 18:05-21:05>
:PROPERTIES:
:ID:       B5z4FOnInm2DcpetdfsONw9b@stanza.co
:LOCATION: Wag-Along Wednesday
:STATUS:   CONFIRMED
:END:

Fireflies vs. RiverDogs Bring your dog to the game with you! 

Follow on MiLB First Pitch  https //stza.co/+xB06-3O

Shop  https //stza.co/+xB06-1L

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Fireflies vs. RiverDogs
END:VALARM
DTSTART:20180829T230500Z
DTEND:20180830T020500Z
UID:B5z4FOnInm2DcpetdfsONw9b@stanza.co
SUMMARY:Fireflies vs. RiverDogs
DESCRIPTION:Bring your dog to the game with you! \n\nFollow on MiLB First Pitch: https://stza.co/+xB06-3O\n\nShop: https://stza.co/+xB06-1L\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Wag-Along Wednesday
STATUS:CONFIRMED
CREATED:20180213T144515Z
LAST-MODIFIED:20180213T144515Z
TRANSP:OPAQUE
END:VEVENT
* Fireflies vs. RiverDogs
<2018-08-30 Thu 18:05-21:05>
:PROPERTIES:
:ID:       hhNDu4ZA16hEvEfnOLkiP2rM@stanza.co
:LOCATION: Thirsty Thursday 
:STATUS:   CONFIRMED
:END:

Fireflies vs. RiverDogs Enjoy half priced beer and fountain drinks! 

Follow on MiLB First Pitch  https //stza.co/+xB08-1v

Shop  https //stza.co/+xB08-1e

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Fireflies vs. RiverDogs
END:VALARM
DTSTART:20180830T230500Z
DTEND:20180831T020500Z
UID:hhNDu4ZA16hEvEfnOLkiP2rM@stanza.co
SUMMARY:Fireflies vs. RiverDogs
DESCRIPTION:Enjoy half priced beer and fountain drinks! \n\nFollow on MiLB First Pitch: https://stza.co/+xB08-1v\n\nShop: https://stza.co/+xB08-1e\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Thirsty Thursday 
STATUS:CONFIRMED
CREATED:20180213T144515Z
LAST-MODIFIED:20180213T144515Z
TRANSP:OPAQUE
END:VEVENT
* Fireflies @ GreenJackets
<2018-08-31 Fri 18:05-21:05>
:PROPERTIES:
:ID:       oskDTYZ2sctJgyls-a2I8beY@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Fireflies @ GreenJackets Fireflies @ GreenJackets

Follow on MiLB First Pitch  https //stza.co/+xBMM-2y

Shop  https //stza.co/+xBMM-T

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Fireflies @ GreenJackets
END:VALARM
DTSTART:20180831T230500Z
DTEND:20180901T020500Z
UID:oskDTYZ2sctJgyls-a2I8beY@stanza.co
SUMMARY:Fireflies @ GreenJackets
DESCRIPTION:Fireflies @ GreenJackets\n\nFollow on MiLB First Pitch: https://stza.co/+xBMM-2y\n\nShop: https://stza.co/+xBMM-T\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144515Z
LAST-MODIFIED:20180213T144515Z
TRANSP:OPAQUE
END:VEVENT
* Fireflies @ GreenJackets
<2018-09-01 Sat 17:05-20:05>
:PROPERTIES:
:ID:       TGG3B5HCi-N1JLoYeXQY1Fsq@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Fireflies @ GreenJackets Fireflies @ GreenJackets

Follow on MiLB First Pitch  https //stza.co/+xBMN-F

Shop  https //stza.co/+xBMN-2R

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Fireflies @ GreenJackets
END:VALARM
DTSTART:20180901T220500Z
DTEND:20180902T010500Z
UID:TGG3B5HCi-N1JLoYeXQY1Fsq@stanza.co
SUMMARY:Fireflies @ GreenJackets
DESCRIPTION:Fireflies @ GreenJackets\n\nFollow on MiLB First Pitch: https://stza.co/+xBMN-F\n\nShop: https://stza.co/+xBMN-2R\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144515Z
LAST-MODIFIED:20180213T144515Z
TRANSP:OPAQUE
END:VEVENT
* Fireflies @ GreenJackets
<2018-09-02 Sun 17:35-20:35>
:PROPERTIES:
:ID:       vizUdpc9PPGGYZRzTWSEBgn2@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Fireflies @ GreenJackets Fireflies @ GreenJackets

Follow on MiLB First Pitch  https //stza.co/+xBMO-3Y

Shop  https //stza.co/+xBMO-7

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Fireflies @ GreenJackets
END:VALARM
DTSTART:20180902T223500Z
DTEND:20180903T013500Z
UID:vizUdpc9PPGGYZRzTWSEBgn2@stanza.co
SUMMARY:Fireflies @ GreenJackets
DESCRIPTION:Fireflies @ GreenJackets\n\nFollow on MiLB First Pitch: https://stza.co/+xBMO-3Y\n\nShop: https://stza.co/+xBMO-7\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144515Z
LAST-MODIFIED:20180213T144515Z
TRANSP:OPAQUE
END:VEVENT
* Fireflies @ GreenJackets
<2018-09-03 Mon 13:05-16:05>
:PROPERTIES:
:ID:       wLHbcF2SPMZb7X0WKWgwsMrk@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Fireflies @ GreenJackets Fireflies @ GreenJackets

Follow on MiLB First Pitch  https //stza.co/+xBMP-2h

Shop  https //stza.co/+xBMP-2Z

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Fireflies @ GreenJackets
END:VALARM
DTSTART:20180903T180500Z
DTEND:20180903T210500Z
UID:wLHbcF2SPMZb7X0WKWgwsMrk@stanza.co
SUMMARY:Fireflies @ GreenJackets
DESCRIPTION:Fireflies @ GreenJackets\n\nFollow on MiLB First Pitch: https://stza.co/+xBMP-2h\n\nShop: https://stza.co/+xBMP-2Z\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144515Z
LAST-MODIFIED:20180213T144515Z
TRANSP:OPAQUE
END:VEVENT
