#+TITLE:       Main Google calendar entries
#+AUTHOR:      Eric S Fraga
#+EMAIL:       e.fraga@ucl.ac.uk
#+DESCRIPTION: converted using the ical2org awk script
#+CATEGORY:    google
#+STARTUP:     hidestars
#+STARTUP:     overview

* COMMENT original iCal preamble

* Blue Jays @ Threshers
<2018-04-05 Thu 18:00-21:00>
:PROPERTIES:
:ID:       6DdPHWkxaNYx2Af6L-y_UEcf@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Blue Jays @ Threshers Blue Jays @ Threshers

Follow on MiLB First Pitch  https //stza.co/+xBdq-3a

Shop  https //stza.co/+xBdq-2a

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Blue Jays @ Threshers
END:VALARM
DTSTART:20180405T230000Z
DTEND:20180406T020000Z
UID:6DdPHWkxaNYx2Af6L-y_UEcf@stanza.co
SUMMARY:Blue Jays @ Threshers
DESCRIPTION:Blue Jays @ Threshers\n\nFollow on MiLB First Pitch: https://stza.co/+xBdq-3a\n\nShop: https://stza.co/+xBdq-2a\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144520Z
LAST-MODIFIED:20180213T144520Z
TRANSP:OPAQUE
END:VEVENT
* Blue Jays @ Threshers
<2018-04-06 Fri 17:15-20:15>
:PROPERTIES:
:ID:       jkapuFe0RmI0JpKaH2wr6A7L@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Blue Jays @ Threshers Blue Jays @ Threshers

Follow on MiLB First Pitch  https //stza.co/+xBdr-i

Shop  https //stza.co/+xBdr-2v

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Blue Jays @ Threshers
END:VALARM
DTSTART:20180406T221500Z
DTEND:20180407T011500Z
UID:jkapuFe0RmI0JpKaH2wr6A7L@stanza.co
SUMMARY:Blue Jays @ Threshers
DESCRIPTION:Blue Jays @ Threshers\n\nFollow on MiLB First Pitch: https://stza.co/+xBdr-i\n\nShop: https://stza.co/+xBdr-2v\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144520Z
LAST-MODIFIED:20180213T144520Z
TRANSP:OPAQUE
END:VEVENT
* Blue Jays vs. Threshers
<2018-04-07 Sat 17:30-20:30>
:PROPERTIES:
:ID:       -Y0urlVmV1hgj7Rr864EwP6J@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Blue Jays vs. Threshers Blue Jays vs. Threshers

Follow on MiLB First Pitch  https //stza.co/+y0GX-1U

Shop  https //stza.co/+y0GX-3n

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Blue Jays vs. Threshers
END:VALARM
DTSTART:20180407T223000Z
DTEND:20180408T013000Z
UID:-Y0urlVmV1hgj7Rr864EwP6J@stanza.co
SUMMARY:Blue Jays vs. Threshers
DESCRIPTION:Blue Jays vs. Threshers\n\nFollow on MiLB First Pitch: https://stza.co/+y0GX-1U\n\nShop: https://stza.co/+y0GX-3n\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144520Z
LAST-MODIFIED:20180213T144520Z
TRANSP:OPAQUE
END:VEVENT
* Blue Jays vs. Threshers
<2018-04-08 Sun 12:00-15:00>
:PROPERTIES:
:ID:       Sc52CqeQSTaARKyD1TuzMBoX@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Blue Jays vs. Threshers Blue Jays vs. Threshers

Follow on MiLB First Pitch  https //stza.co/+y0G_-2c

Shop  https //stza.co/+y0G_-3o

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Blue Jays vs. Threshers
END:VALARM
DTSTART:20180408T170000Z
DTEND:20180408T200000Z
UID:Sc52CqeQSTaARKyD1TuzMBoX@stanza.co
SUMMARY:Blue Jays vs. Threshers
DESCRIPTION:Blue Jays vs. Threshers\n\nFollow on MiLB First Pitch: https://stza.co/+y0G_-2c\n\nShop: https://stza.co/+y0G_-3o\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144520Z
LAST-MODIFIED:20180213T144520Z
TRANSP:OPAQUE
END:VEVENT
* Blue Jays @ Cardinals
<2018-04-09 Mon>--<2018-04-08 Sun>
:PROPERTIES:
:ID:       mn8-ngN250g3XURPASZrsn2u@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Blue Jays @ Cardinals Blue Jays @ Cardinals

Buy tickets here  https //stza.co/~vMnD

Follow on MiLB First Pitch  https //stza.co/+vMnD-P

Shop  https //stza.co/+vMnD-2Z

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Blue Jays @ Cardinals
END:VALARM
DTSTART;VALUE=DATE:20180409
DTEND;VALUE=DATE:20180409
UID:mn8-ngN250g3XURPASZrsn2u@stanza.co
SUMMARY:Blue Jays @ Cardinals
DESCRIPTION:Blue Jays @ Cardinals\n\nBuy tickets here: https://stza.co/~vMnD\n\nFollow on MiLB First Pitch: https://stza.co/+vMnD-P\n\nShop: https://stza.co/+vMnD-2Z\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144520Z
LAST-MODIFIED:20180213T144520Z
TRANSP:OPAQUE
END:VEVENT
* Blue Jays @ Cardinals
<2018-04-10 Tue>--<2018-04-09 Mon>
:PROPERTIES:
:ID:       oZmHKf0XzFQS-2NCTDrm9JIa@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Blue Jays @ Cardinals Blue Jays @ Cardinals

Buy tickets here  https //stza.co/~vMnE

Follow on MiLB First Pitch  https //stza.co/+vMnE-3B

Shop  https //stza.co/+vMnE-1Q

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Blue Jays @ Cardinals
END:VALARM
DTSTART;VALUE=DATE:20180410
DTEND;VALUE=DATE:20180410
UID:oZmHKf0XzFQS-2NCTDrm9JIa@stanza.co
SUMMARY:Blue Jays @ Cardinals
DESCRIPTION:Blue Jays @ Cardinals\n\nBuy tickets here: https://stza.co/~vMnE\n\nFollow on MiLB First Pitch: https://stza.co/+vMnE-3B\n\nShop: https://stza.co/+vMnE-1Q\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144520Z
LAST-MODIFIED:20180213T144520Z
TRANSP:OPAQUE
END:VEVENT
* Blue Jays @ Cardinals
<2018-04-11 Wed>--<2018-04-10 Tue>
:PROPERTIES:
:ID:       Sf-5HwwkjWlhRd2dCcwONT2E@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Blue Jays @ Cardinals Blue Jays @ Cardinals

Buy tickets here  https //stza.co/~vMnF

Follow on MiLB First Pitch  https //stza.co/+vMnF-d

Shop  https //stza.co/+vMnF-Q

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Blue Jays @ Cardinals
END:VALARM
DTSTART;VALUE=DATE:20180411
DTEND;VALUE=DATE:20180411
UID:Sf-5HwwkjWlhRd2dCcwONT2E@stanza.co
SUMMARY:Blue Jays @ Cardinals
DESCRIPTION:Blue Jays @ Cardinals\n\nBuy tickets here: https://stza.co/~vMnF\n\nFollow on MiLB First Pitch: https://stza.co/+vMnF-d\n\nShop: https://stza.co/+vMnF-Q\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144520Z
LAST-MODIFIED:20180213T144520Z
TRANSP:OPAQUE
END:VEVENT
* Blue Jays @ Cardinals
<2018-04-12 Thu>--<2018-04-11 Wed>
:PROPERTIES:
:ID:       SRUOcITiJMwuOSefDukPjNVo@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Blue Jays @ Cardinals Blue Jays @ Cardinals

Buy tickets here  https //stza.co/~vMnG

Follow on MiLB First Pitch  https //stza.co/+vMnG-1v

Shop  https //stza.co/+vMnG-2N

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Blue Jays @ Cardinals
END:VALARM
DTSTART;VALUE=DATE:20180412
DTEND;VALUE=DATE:20180412
UID:SRUOcITiJMwuOSefDukPjNVo@stanza.co
SUMMARY:Blue Jays @ Cardinals
DESCRIPTION:Blue Jays @ Cardinals\n\nBuy tickets here: https://stza.co/~vMnG\n\nFollow on MiLB First Pitch: https://stza.co/+vMnG-1v\n\nShop: https://stza.co/+vMnG-2N\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144520Z
LAST-MODIFIED:20180213T144520Z
TRANSP:OPAQUE
END:VEVENT
* Blue Jays @ Mets
<2018-04-13 Fri 17:30-20:30>
:PROPERTIES:
:ID:       K8I9VlSfpHRR0iwJ3hHL5HIm@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Blue Jays @ Mets Blue Jays @ Mets

Follow on MiLB First Pitch  https //stza.co/+vMnH-d

Shop  https //stza.co/+vMnH-18

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Blue Jays @ Mets
END:VALARM
DTSTART:20180413T223000Z
DTEND:20180414T013000Z
UID:K8I9VlSfpHRR0iwJ3hHL5HIm@stanza.co
SUMMARY:Blue Jays @ Mets
DESCRIPTION:Blue Jays @ Mets\n\nFollow on MiLB First Pitch: https://stza.co/+vMnH-d\n\nShop: https://stza.co/+vMnH-18\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144520Z
LAST-MODIFIED:20180213T144520Z
TRANSP:OPAQUE
END:VEVENT
* Blue Jays @ Mets
<2018-04-14 Sat 17:30-20:30>
:PROPERTIES:
:ID:       5s0i2YdxcYOa1klMcrTJ_Fy7@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Blue Jays @ Mets Blue Jays @ Mets

Follow on MiLB First Pitch  https //stza.co/+vMnI-2j

Shop  https //stza.co/+vMnI-22

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Blue Jays @ Mets
END:VALARM
DTSTART:20180414T223000Z
DTEND:20180415T013000Z
UID:5s0i2YdxcYOa1klMcrTJ_Fy7@stanza.co
SUMMARY:Blue Jays @ Mets
DESCRIPTION:Blue Jays @ Mets\n\nFollow on MiLB First Pitch: https://stza.co/+vMnI-2j\n\nShop: https://stza.co/+vMnI-22\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144520Z
LAST-MODIFIED:20180213T144520Z
TRANSP:OPAQUE
END:VEVENT
* Blue Jays @ Mets
<2018-04-15 Sun>--<2018-04-14 Sat>
:PROPERTIES:
:ID:       FNkZ1VmO2A_TSiaz1j7pRRRE@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Blue Jays @ Mets Blue Jays @ Mets

Follow on MiLB First Pitch  https //stza.co/+vMnJ-39

Shop  https //stza.co/+vMnJ-36

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Blue Jays @ Mets
END:VALARM
DTSTART;VALUE=DATE:20180415
DTEND;VALUE=DATE:20180415
UID:FNkZ1VmO2A_TSiaz1j7pRRRE@stanza.co
SUMMARY:Blue Jays @ Mets
DESCRIPTION:Blue Jays @ Mets\n\nFollow on MiLB First Pitch: https://stza.co/+vMnJ-39\n\nShop: https://stza.co/+vMnJ-36\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144520Z
LAST-MODIFIED:20180213T144520Z
TRANSP:OPAQUE
END:VEVENT
* Blue Jays vs. Miracle
<2018-04-17 Tue 17:30-20:30>
:PROPERTIES:
:ID:       -UQtkX-5obEdwU2va21O0BE4@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Blue Jays vs. Miracle Blue Jays vs. Miracle

Follow on MiLB First Pitch  https //stza.co/+y0G$-1L

Shop  https //stza.co/+y0G$-3T

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Blue Jays vs. Miracle
END:VALARM
DTSTART:20180417T223000Z
DTEND:20180418T013000Z
UID:-UQtkX-5obEdwU2va21O0BE4@stanza.co
SUMMARY:Blue Jays vs. Miracle
DESCRIPTION:Blue Jays vs. Miracle\n\nFollow on MiLB First Pitch: https://stza.co/+y0G$-1L\n\nShop: https://stza.co/+y0G$-3T\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144520Z
LAST-MODIFIED:20180213T144520Z
TRANSP:OPAQUE
END:VEVENT
* Blue Jays vs. Miracle
<2018-04-18 Wed 17:30-20:30>
:PROPERTIES:
:ID:       94l5G52OhAHtSWf3YLuUwZPI@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Blue Jays vs. Miracle Blue Jays vs. Miracle

Follow on MiLB First Pitch  https //stza.co/+y0H2-3a

Shop  https //stza.co/+y0H2-P

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Blue Jays vs. Miracle
END:VALARM
DTSTART:20180418T223000Z
DTEND:20180419T013000Z
UID:94l5G52OhAHtSWf3YLuUwZPI@stanza.co
SUMMARY:Blue Jays vs. Miracle
DESCRIPTION:Blue Jays vs. Miracle\n\nFollow on MiLB First Pitch: https://stza.co/+y0H2-3a\n\nShop: https://stza.co/+y0H2-P\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144520Z
LAST-MODIFIED:20180213T144520Z
TRANSP:OPAQUE
END:VEVENT
* Blue Jays vs. Miracle
<2018-04-19 Thu 17:30-20:30>
:PROPERTIES:
:ID:       _tnsKs-sGUw8J7lv5Yxtpu_p@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Blue Jays vs. Miracle Blue Jays vs. Miracle

Follow on MiLB First Pitch  https //stza.co/+y0H3-37

Shop  https //stza.co/+y0H3-35

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Blue Jays vs. Miracle
END:VALARM
DTSTART:20180419T223000Z
DTEND:20180420T013000Z
UID:_tnsKs-sGUw8J7lv5Yxtpu_p@stanza.co
SUMMARY:Blue Jays vs. Miracle
DESCRIPTION:Blue Jays vs. Miracle\n\nFollow on MiLB First Pitch: https://stza.co/+y0H3-37\n\nShop: https://stza.co/+y0H3-35\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144520Z
LAST-MODIFIED:20180213T144520Z
TRANSP:OPAQUE
END:VEVENT
* Blue Jays vs. Tortugas
<2018-04-20 Fri 17:30-20:30>
:PROPERTIES:
:ID:       nA8o9xziTgnVVjnKzCocLlOP@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Blue Jays vs. Tortugas Blue Jays vs. Tortugas

Follow on MiLB First Pitch  https //stza.co/+y0H5-1F

Shop  https //stza.co/+y0H5-3w

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Blue Jays vs. Tortugas
END:VALARM
DTSTART:20180420T223000Z
DTEND:20180421T013000Z
UID:nA8o9xziTgnVVjnKzCocLlOP@stanza.co
SUMMARY:Blue Jays vs. Tortugas
DESCRIPTION:Blue Jays vs. Tortugas\n\nFollow on MiLB First Pitch: https://stza.co/+y0H5-1F\n\nShop: https://stza.co/+y0H5-3w\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144520Z
LAST-MODIFIED:20180213T144520Z
TRANSP:OPAQUE
END:VEVENT
* Blue Jays vs. Tortugas
<2018-04-21 Sat 17:30-20:30>
:PROPERTIES:
:ID:       SKMi1V2YCnmd2lov9Pzti5PI@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Blue Jays vs. Tortugas Blue Jays vs. Tortugas

Follow on MiLB First Pitch  https //stza.co/+y0H8-m

Shop  https //stza.co/+y0H8-1m

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Blue Jays vs. Tortugas
END:VALARM
DTSTART:20180421T223000Z
DTEND:20180422T013000Z
UID:SKMi1V2YCnmd2lov9Pzti5PI@stanza.co
SUMMARY:Blue Jays vs. Tortugas
DESCRIPTION:Blue Jays vs. Tortugas\n\nFollow on MiLB First Pitch: https://stza.co/+y0H8-m\n\nShop: https://stza.co/+y0H8-1m\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144520Z
LAST-MODIFIED:20180213T144520Z
TRANSP:OPAQUE
END:VEVENT
* Blue Jays vs. Tortugas
<2018-04-22 Sun 12:00-15:00>
:PROPERTIES:
:ID:       ztPF1baF4SQNTmU_Wa9P2JeC@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Blue Jays vs. Tortugas Blue Jays vs. Tortugas

Follow on MiLB First Pitch  https //stza.co/+y0H9-1f

Shop  https //stza.co/+y0H9-3C

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Blue Jays vs. Tortugas
END:VALARM
DTSTART:20180422T170000Z
DTEND:20180422T200000Z
UID:ztPF1baF4SQNTmU_Wa9P2JeC@stanza.co
SUMMARY:Blue Jays vs. Tortugas
DESCRIPTION:Blue Jays vs. Tortugas\n\nFollow on MiLB First Pitch: https://stza.co/+y0H9-1f\n\nShop: https://stza.co/+y0H9-3C\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144520Z
LAST-MODIFIED:20180213T144520Z
TRANSP:OPAQUE
END:VEVENT
* Blue Jays @ Flying Tigers
<2018-04-23 Mon 17:30-20:30>
:PROPERTIES:
:ID:       2nf6-wyA2GHfyBGE7CakofVk@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Blue Jays @ Flying Tigers Blue Jays @ Flying Tigers

Follow on MiLB First Pitch  https //stza.co/+wKMG-2P

Shop  https //stza.co/+wKMG-k

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Blue Jays @ Flying Tigers
END:VALARM
DTSTART:20180423T223000Z
DTEND:20180424T013000Z
UID:2nf6-wyA2GHfyBGE7CakofVk@stanza.co
SUMMARY:Blue Jays @ Flying Tigers
DESCRIPTION:Blue Jays @ Flying Tigers\n\nFollow on MiLB First Pitch: https://stza.co/+wKMG-2P\n\nShop: https://stza.co/+wKMG-k\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144520Z
LAST-MODIFIED:20180213T144520Z
TRANSP:OPAQUE
END:VEVENT
* Blue Jays @ Flying Tigers
<2018-04-24 Tue 09:30-12:30>
:PROPERTIES:
:ID:       jYlki5F3eReR-2Qo1j7LxbP-@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Blue Jays @ Flying Tigers Blue Jays @ Flying Tigers

Follow on MiLB First Pitch  https //stza.co/+wKMH-1a

Shop  https //stza.co/+wKMH-1L

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Blue Jays @ Flying Tigers
END:VALARM
DTSTART:20180424T143000Z
DTEND:20180424T173000Z
UID:jYlki5F3eReR-2Qo1j7LxbP-@stanza.co
SUMMARY:Blue Jays @ Flying Tigers
DESCRIPTION:Blue Jays @ Flying Tigers\n\nFollow on MiLB First Pitch: https://stza.co/+wKMH-1a\n\nShop: https://stza.co/+wKMH-1L\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144520Z
LAST-MODIFIED:20180213T144520Z
TRANSP:OPAQUE
END:VEVENT
* Blue Jays @ Flying Tigers
<2018-04-25 Wed 17:30-20:30>
:PROPERTIES:
:ID:       6DtgIr3eobecH-vVs2SirEm6@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Blue Jays @ Flying Tigers Blue Jays @ Flying Tigers

Follow on MiLB First Pitch  https //stza.co/+wKMI-2q

Shop  https //stza.co/+wKMI-3b

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Blue Jays @ Flying Tigers
END:VALARM
DTSTART:20180425T223000Z
DTEND:20180426T013000Z
UID:6DtgIr3eobecH-vVs2SirEm6@stanza.co
SUMMARY:Blue Jays @ Flying Tigers
DESCRIPTION:Blue Jays @ Flying Tigers\n\nFollow on MiLB First Pitch: https://stza.co/+wKMI-2q\n\nShop: https://stza.co/+wKMI-3b\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144520Z
LAST-MODIFIED:20180213T144520Z
TRANSP:OPAQUE
END:VEVENT
* Blue Jays vs. Threshers
<2018-04-26 Thu 17:30-20:30>
:PROPERTIES:
:ID:       xDEh62C9L-_0hlAZIUKVLawl@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Blue Jays vs. Threshers Blue Jays vs. Threshers

Follow on MiLB First Pitch  https //stza.co/+y0Hb-$

Shop  https //stza.co/+y0Hb-28

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Blue Jays vs. Threshers
END:VALARM
DTSTART:20180426T223000Z
DTEND:20180427T013000Z
UID:xDEh62C9L-_0hlAZIUKVLawl@stanza.co
SUMMARY:Blue Jays vs. Threshers
DESCRIPTION:Blue Jays vs. Threshers\n\nFollow on MiLB First Pitch: https://stza.co/+y0Hb-$\n\nShop: https://stza.co/+y0Hb-28\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144520Z
LAST-MODIFIED:20180213T144520Z
TRANSP:OPAQUE
END:VEVENT
* Blue Jays vs. Threshers
<2018-04-27 Fri 17:30-20:30>
:PROPERTIES:
:ID:       5oVcYmESkCeg5BVanBxa5O0W@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Blue Jays vs. Threshers Blue Jays vs. Threshers

Follow on MiLB First Pitch  https //stza.co/+y0Hd-2S

Shop  https //stza.co/+y0Hd-27

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Blue Jays vs. Threshers
END:VALARM
DTSTART:20180427T223000Z
DTEND:20180428T013000Z
UID:5oVcYmESkCeg5BVanBxa5O0W@stanza.co
SUMMARY:Blue Jays vs. Threshers
DESCRIPTION:Blue Jays vs. Threshers\n\nFollow on MiLB First Pitch: https://stza.co/+y0Hd-2S\n\nShop: https://stza.co/+y0Hd-27\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144520Z
LAST-MODIFIED:20180213T144520Z
TRANSP:OPAQUE
END:VEVENT
* Blue Jays vs. Threshers
<2018-04-28 Sat 17:30-20:30>
:PROPERTIES:
:ID:       jdtFcxpa-AR_VO0FiZ0z3xpU@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Blue Jays vs. Threshers Blue Jays vs. Threshers

Follow on MiLB First Pitch  https //stza.co/+y0Hg-k

Shop  https //stza.co/+y0Hg-21

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Blue Jays vs. Threshers
END:VALARM
DTSTART:20180428T223000Z
DTEND:20180429T013000Z
UID:jdtFcxpa-AR_VO0FiZ0z3xpU@stanza.co
SUMMARY:Blue Jays vs. Threshers
DESCRIPTION:Blue Jays vs. Threshers\n\nFollow on MiLB First Pitch: https://stza.co/+y0Hg-k\n\nShop: https://stza.co/+y0Hg-21\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144520Z
LAST-MODIFIED:20180213T144520Z
TRANSP:OPAQUE
END:VEVENT
* Blue Jays vs. Threshers
<2018-04-29 Sun 12:00-15:00>
:PROPERTIES:
:ID:       WPaCr8AjYhSykFkcoKzRFRXq@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Blue Jays vs. Threshers Blue Jays vs. Threshers

Follow on MiLB First Pitch  https //stza.co/+y0Hh-3o

Shop  https //stza.co/+y0Hh-l

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Blue Jays vs. Threshers
END:VALARM
DTSTART:20180429T170000Z
DTEND:20180429T200000Z
UID:WPaCr8AjYhSykFkcoKzRFRXq@stanza.co
SUMMARY:Blue Jays vs. Threshers
DESCRIPTION:Blue Jays vs. Threshers\n\nFollow on MiLB First Pitch: https://stza.co/+y0Hh-3o\n\nShop: https://stza.co/+y0Hh-l\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144520Z
LAST-MODIFIED:20180213T144520Z
TRANSP:OPAQUE
END:VEVENT
* Blue Jays @ Marauders
<2018-05-01 Tue 17:30-20:30>
:PROPERTIES:
:ID:       WtvtZT9vtS1e7Qri3Wt8CADn@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Blue Jays @ Marauders Blue Jays @ Marauders

Follow on MiLB First Pitch  https //stza.co/+vMkC-38

Shop  https //stza.co/+vMkC-3J

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Blue Jays @ Marauders
END:VALARM
DTSTART:20180501T223000Z
DTEND:20180502T013000Z
UID:WtvtZT9vtS1e7Qri3Wt8CADn@stanza.co
SUMMARY:Blue Jays @ Marauders
DESCRIPTION:Blue Jays @ Marauders\n\nFollow on MiLB First Pitch: https://stza.co/+vMkC-38\n\nShop: https://stza.co/+vMkC-3J\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144520Z
LAST-MODIFIED:20180213T144520Z
TRANSP:OPAQUE
END:VEVENT
* Blue Jays @ Marauders
<2018-05-02 Wed 17:30-20:30>
:PROPERTIES:
:ID:       AV8CCOM3PwA6JzgIQnKTWRqR@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Blue Jays @ Marauders Blue Jays @ Marauders

Follow on MiLB First Pitch  https //stza.co/+vMkD-2N

Shop  https //stza.co/+vMkD-U

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Blue Jays @ Marauders
END:VALARM
DTSTART:20180502T223000Z
DTEND:20180503T013000Z
UID:AV8CCOM3PwA6JzgIQnKTWRqR@stanza.co
SUMMARY:Blue Jays @ Marauders
DESCRIPTION:Blue Jays @ Marauders\n\nFollow on MiLB First Pitch: https://stza.co/+vMkD-2N\n\nShop: https://stza.co/+vMkD-U\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144520Z
LAST-MODIFIED:20180213T144520Z
TRANSP:OPAQUE
END:VEVENT
* Blue Jays @ Marauders
<2018-05-03 Thu 17:30-20:30>
:PROPERTIES:
:ID:       7jGDOAn0DdGoedP0W0ZWrXV4@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Blue Jays @ Marauders Blue Jays @ Marauders

Follow on MiLB First Pitch  https //stza.co/+vMkE-2W

Shop  https //stza.co/+vMkE-2a

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Blue Jays @ Marauders
END:VALARM
DTSTART:20180503T223000Z
DTEND:20180504T013000Z
UID:7jGDOAn0DdGoedP0W0ZWrXV4@stanza.co
SUMMARY:Blue Jays @ Marauders
DESCRIPTION:Blue Jays @ Marauders\n\nFollow on MiLB First Pitch: https://stza.co/+vMkE-2W\n\nShop: https://stza.co/+vMkE-2a\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144520Z
LAST-MODIFIED:20180213T144520Z
TRANSP:OPAQUE
END:VEVENT
* Blue Jays @ Threshers
<2018-05-04 Fri 17:15-20:15>
:PROPERTIES:
:ID:       E_Y6R3tcCUBQrwVkUZmdswOb@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Blue Jays @ Threshers Blue Jays @ Threshers

Follow on MiLB First Pitch  https //stza.co/+xBds-1k

Shop  https //stza.co/+xBds-1

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Blue Jays @ Threshers
END:VALARM
DTSTART:20180504T221500Z
DTEND:20180505T011500Z
UID:E_Y6R3tcCUBQrwVkUZmdswOb@stanza.co
SUMMARY:Blue Jays @ Threshers
DESCRIPTION:Blue Jays @ Threshers\n\nFollow on MiLB First Pitch: https://stza.co/+xBds-1k\n\nShop: https://stza.co/+xBds-1\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144520Z
LAST-MODIFIED:20180213T144520Z
TRANSP:OPAQUE
END:VEVENT
* Blue Jays @ Threshers
<2018-05-05 Sat 17:15-20:15>
:PROPERTIES:
:ID:       J5xr82WxVXidU_vFkDsaxaeh@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Blue Jays @ Threshers Blue Jays @ Threshers

Follow on MiLB First Pitch  https //stza.co/+xBdt-1t

Shop  https //stza.co/+xBdt-1y

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Blue Jays @ Threshers
END:VALARM
DTSTART:20180505T221500Z
DTEND:20180506T011500Z
UID:J5xr82WxVXidU_vFkDsaxaeh@stanza.co
SUMMARY:Blue Jays @ Threshers
DESCRIPTION:Blue Jays @ Threshers\n\nFollow on MiLB First Pitch: https://stza.co/+xBdt-1t\n\nShop: https://stza.co/+xBdt-1y\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144520Z
LAST-MODIFIED:20180213T144520Z
TRANSP:OPAQUE
END:VEVENT
* Blue Jays @ Threshers
<2018-05-06 Sun 12:00-15:00>
:PROPERTIES:
:ID:       Q_fpmuc1Htxe7VpiHpO3190p@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Blue Jays @ Threshers Blue Jays @ Threshers

Follow on MiLB First Pitch  https //stza.co/+xBdu-3u

Shop  https //stza.co/+xBdu-l

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Blue Jays @ Threshers
END:VALARM
DTSTART:20180506T170000Z
DTEND:20180506T200000Z
UID:Q_fpmuc1Htxe7VpiHpO3190p@stanza.co
SUMMARY:Blue Jays @ Threshers
DESCRIPTION:Blue Jays @ Threshers\n\nFollow on MiLB First Pitch: https://stza.co/+xBdu-3u\n\nShop: https://stza.co/+xBdu-l\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144520Z
LAST-MODIFIED:20180213T144520Z
TRANSP:OPAQUE
END:VEVENT
* Blue Jays vs. Marauders
<2018-05-07 Mon 17:30-20:30>
:PROPERTIES:
:ID:       AVepUzaMx4Q4_eGeN0-iNyHT@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Blue Jays vs. Marauders Blue Jays vs. Marauders

Follow on MiLB First Pitch  https //stza.co/+y0Hk-1H

Shop  https //stza.co/+y0Hk-2d

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Blue Jays vs. Marauders
END:VALARM
DTSTART:20180507T223000Z
DTEND:20180508T013000Z
UID:AVepUzaMx4Q4_eGeN0-iNyHT@stanza.co
SUMMARY:Blue Jays vs. Marauders
DESCRIPTION:Blue Jays vs. Marauders\n\nFollow on MiLB First Pitch: https://stza.co/+y0Hk-1H\n\nShop: https://stza.co/+y0Hk-2d\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144520Z
LAST-MODIFIED:20180213T144520Z
TRANSP:OPAQUE
END:VEVENT
* Blue Jays vs. Marauders
<2018-05-08 Tue 17:30-20:30>
:PROPERTIES:
:ID:       rsE2eOvHB57aaeqEQ937O6EK@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Blue Jays vs. Marauders Blue Jays vs. Marauders

Follow on MiLB First Pitch  https //stza.co/+y0Hm-Y

Shop  https //stza.co/+y0Hm-1S

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Blue Jays vs. Marauders
END:VALARM
DTSTART:20180508T223000Z
DTEND:20180509T013000Z
UID:rsE2eOvHB57aaeqEQ937O6EK@stanza.co
SUMMARY:Blue Jays vs. Marauders
DESCRIPTION:Blue Jays vs. Marauders\n\nFollow on MiLB First Pitch: https://stza.co/+y0Hm-Y\n\nShop: https://stza.co/+y0Hm-1S\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144520Z
LAST-MODIFIED:20180213T144520Z
TRANSP:OPAQUE
END:VEVENT
* Blue Jays vs. Marauders
<2018-05-09 Wed 10:00-13:00>
:PROPERTIES:
:ID:       tj6JDnjb_fLOcffchrX1R2cj@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Blue Jays vs. Marauders Blue Jays vs. Marauders

Follow on MiLB First Pitch  https //stza.co/+y0Ho-2F

Shop  https //stza.co/+y0Ho-1Q

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Blue Jays vs. Marauders
END:VALARM
DTSTART:20180509T150000Z
DTEND:20180509T180000Z
UID:tj6JDnjb_fLOcffchrX1R2cj@stanza.co
SUMMARY:Blue Jays vs. Marauders
DESCRIPTION:Blue Jays vs. Marauders\n\nFollow on MiLB First Pitch: https://stza.co/+y0Ho-2F\n\nShop: https://stza.co/+y0Ho-1Q\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144520Z
LAST-MODIFIED:20180213T144520Z
TRANSP:OPAQUE
END:VEVENT
* Blue Jays vs. Miracle
<2018-05-10 Thu 17:30-20:30>
:PROPERTIES:
:ID:       M5zJ9VfM18EWziStjgdltf9L@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Blue Jays vs. Miracle Blue Jays vs. Miracle

Follow on MiLB First Pitch  https //stza.co/+y0Hq-3M

Shop  https //stza.co/+y0Hq-2i

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Blue Jays vs. Miracle
END:VALARM
DTSTART:20180510T223000Z
DTEND:20180511T013000Z
UID:M5zJ9VfM18EWziStjgdltf9L@stanza.co
SUMMARY:Blue Jays vs. Miracle
DESCRIPTION:Blue Jays vs. Miracle\n\nFollow on MiLB First Pitch: https://stza.co/+y0Hq-3M\n\nShop: https://stza.co/+y0Hq-2i\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144520Z
LAST-MODIFIED:20180213T144520Z
TRANSP:OPAQUE
END:VEVENT
* Blue Jays vs. Miracle
<2018-05-11 Fri 17:30-20:30>
:PROPERTIES:
:ID:       rW74YJaDf8i9LH63ET05nLz6@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Blue Jays vs. Miracle Blue Jays vs. Miracle

Follow on MiLB First Pitch  https //stza.co/+y0Hr-2s

Shop  https //stza.co/+y0Hr-1i

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Blue Jays vs. Miracle
END:VALARM
DTSTART:20180511T223000Z
DTEND:20180512T013000Z
UID:rW74YJaDf8i9LH63ET05nLz6@stanza.co
SUMMARY:Blue Jays vs. Miracle
DESCRIPTION:Blue Jays vs. Miracle\n\nFollow on MiLB First Pitch: https://stza.co/+y0Hr-2s\n\nShop: https://stza.co/+y0Hr-1i\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144520Z
LAST-MODIFIED:20180213T144520Z
TRANSP:OPAQUE
END:VEVENT
* Blue Jays vs. Miracle
<2018-05-12 Sat 17:30-20:30>
:PROPERTIES:
:ID:       2GQ5yBz5Bsf2DqL1hf3CeE9q@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Blue Jays vs. Miracle Blue Jays vs. Miracle

Follow on MiLB First Pitch  https //stza.co/+y0Ht-1Y

Shop  https //stza.co/+y0Ht-3I

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Blue Jays vs. Miracle
END:VALARM
DTSTART:20180512T223000Z
DTEND:20180513T013000Z
UID:2GQ5yBz5Bsf2DqL1hf3CeE9q@stanza.co
SUMMARY:Blue Jays vs. Miracle
DESCRIPTION:Blue Jays vs. Miracle\n\nFollow on MiLB First Pitch: https://stza.co/+y0Ht-1Y\n\nShop: https://stza.co/+y0Ht-3I\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144520Z
LAST-MODIFIED:20180213T144520Z
TRANSP:OPAQUE
END:VEVENT
* Blue Jays @ Tarpons
<2018-05-14 Mon>--<2018-05-13 Sun>
:PROPERTIES:
:ID:       FvaDOtPdKF98ludQw2hzUFVm@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Blue Jays @ Tarpons Blue Jays @ Tarpons

Follow on MiLB First Pitch  https //stza.co/+vMnN-D

Shop  https //stza.co/+vMnN-2C

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Blue Jays @ Tarpons
END:VALARM
DTSTART;VALUE=DATE:20180514
DTEND;VALUE=DATE:20180514
UID:FvaDOtPdKF98ludQw2hzUFVm@stanza.co
SUMMARY:Blue Jays @ Tarpons
DESCRIPTION:Blue Jays @ Tarpons\n\nFollow on MiLB First Pitch: https://stza.co/+vMnN-D\n\nShop: https://stza.co/+vMnN-2C\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144520Z
LAST-MODIFIED:20180213T144520Z
TRANSP:OPAQUE
END:VEVENT
* Blue Jays @ Tarpons
<2018-05-15 Tue>--<2018-05-14 Mon>
:PROPERTIES:
:ID:       eE6o1kFCGGxFG1XxgV7_SQBx@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Blue Jays @ Tarpons Blue Jays @ Tarpons

Follow on MiLB First Pitch  https //stza.co/+vjKg-2T

Shop  https //stza.co/+vjKg-R

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Blue Jays @ Tarpons
END:VALARM
DTSTART;VALUE=DATE:20180515
DTEND;VALUE=DATE:20180515
UID:eE6o1kFCGGxFG1XxgV7_SQBx@stanza.co
SUMMARY:Blue Jays @ Tarpons
DESCRIPTION:Blue Jays @ Tarpons\n\nFollow on MiLB First Pitch: https://stza.co/+vjKg-2T\n\nShop: https://stza.co/+vjKg-R\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144520Z
LAST-MODIFIED:20180213T144520Z
TRANSP:OPAQUE
END:VEVENT
* Blue Jays @ Tarpons
<2018-05-16 Wed>--<2018-05-15 Tue>
:PROPERTIES:
:ID:       gopDIjfFvlFmjjXi3xl1T1-J@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Blue Jays @ Tarpons Blue Jays @ Tarpons

Follow on MiLB First Pitch  https //stza.co/+vjKj-2N

Shop  https //stza.co/+vjKj-1n

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Blue Jays @ Tarpons
END:VALARM
DTSTART;VALUE=DATE:20180516
DTEND;VALUE=DATE:20180516
UID:gopDIjfFvlFmjjXi3xl1T1-J@stanza.co
SUMMARY:Blue Jays @ Tarpons
DESCRIPTION:Blue Jays @ Tarpons\n\nFollow on MiLB First Pitch: https://stza.co/+vjKj-2N\n\nShop: https://stza.co/+vjKj-1n\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144520Z
LAST-MODIFIED:20180213T144520Z
TRANSP:OPAQUE
END:VEVENT
* Blue Jays @ Tarpons
<2018-05-17 Thu>--<2018-05-16 Wed>
:PROPERTIES:
:ID:       YzQtkBib-yAKvzPXcqNxVqYV@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Blue Jays @ Tarpons Blue Jays @ Tarpons

Follow on MiLB First Pitch  https //stza.co/+vjKl-N

Shop  https //stza.co/+vjKl-2N

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Blue Jays @ Tarpons
END:VALARM
DTSTART;VALUE=DATE:20180517
DTEND;VALUE=DATE:20180517
UID:YzQtkBib-yAKvzPXcqNxVqYV@stanza.co
SUMMARY:Blue Jays @ Tarpons
DESCRIPTION:Blue Jays @ Tarpons\n\nFollow on MiLB First Pitch: https://stza.co/+vjKl-N\n\nShop: https://stza.co/+vjKl-2N\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144520Z
LAST-MODIFIED:20180213T144520Z
TRANSP:OPAQUE
END:VEVENT
* Blue Jays @ Tortugas
<2018-05-18 Fri 18:05-21:05>
:PROPERTIES:
:ID:       wchoPnol0ttbTaKJyhhb8R5x@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Blue Jays @ Tortugas Blue Jays @ Tortugas

Follow on MiLB First Pitch  https //stza.co/+vMl0-T

Shop  https //stza.co/+vMl0-2k

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Blue Jays @ Tortugas
END:VALARM
DTSTART:20180518T230500Z
DTEND:20180519T020500Z
UID:wchoPnol0ttbTaKJyhhb8R5x@stanza.co
SUMMARY:Blue Jays @ Tortugas
DESCRIPTION:Blue Jays @ Tortugas\n\nFollow on MiLB First Pitch: https://stza.co/+vMl0-T\n\nShop: https://stza.co/+vMl0-2k\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144520Z
LAST-MODIFIED:20180213T144520Z
TRANSP:OPAQUE
END:VEVENT
* Blue Jays @ Tortugas
<2018-05-19 Sat 18:05-21:05>
:PROPERTIES:
:ID:       rnVgnk0hNMHb4fq5PHQJXh2L@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Blue Jays @ Tortugas Blue Jays @ Tortugas

Follow on MiLB First Pitch  https //stza.co/+vMl1-2t

Shop  https //stza.co/+vMl1-3P

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Blue Jays @ Tortugas
END:VALARM
DTSTART:20180519T230500Z
DTEND:20180520T020500Z
UID:rnVgnk0hNMHb4fq5PHQJXh2L@stanza.co
SUMMARY:Blue Jays @ Tortugas
DESCRIPTION:Blue Jays @ Tortugas\n\nFollow on MiLB First Pitch: https://stza.co/+vMl1-2t\n\nShop: https://stza.co/+vMl1-3P\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144520Z
LAST-MODIFIED:20180213T144520Z
TRANSP:OPAQUE
END:VEVENT
* Blue Jays @ Tortugas
<2018-05-20 Sun 16:35-19:35>
:PROPERTIES:
:ID:       uL38sTQXxTsXI7GxrdWLJb2R@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Blue Jays @ Tortugas Blue Jays @ Tortugas

Follow on MiLB First Pitch  https //stza.co/+vMl2-2B

Shop  https //stza.co/+vMl2-2F

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Blue Jays @ Tortugas
END:VALARM
DTSTART:20180520T213500Z
DTEND:20180521T003500Z
UID:uL38sTQXxTsXI7GxrdWLJb2R@stanza.co
SUMMARY:Blue Jays @ Tortugas
DESCRIPTION:Blue Jays @ Tortugas\n\nFollow on MiLB First Pitch: https://stza.co/+vMl2-2B\n\nShop: https://stza.co/+vMl2-2F\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144520Z
LAST-MODIFIED:20180213T144520Z
TRANSP:OPAQUE
END:VEVENT
* Blue Jays vs. Fire Frogs
<2018-05-21 Mon 17:30-20:30>
:PROPERTIES:
:ID:       qHnlPnFFMDYIPkJ-28w-YdVE@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Blue Jays vs. Fire Frogs Blue Jays vs. Fire Frogs

Follow on MiLB First Pitch  https //stza.co/+y0Hw-3Y

Shop  https //stza.co/+y0Hw-5

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Blue Jays vs. Fire Frogs
END:VALARM
DTSTART:20180521T223000Z
DTEND:20180522T013000Z
UID:qHnlPnFFMDYIPkJ-28w-YdVE@stanza.co
SUMMARY:Blue Jays vs. Fire Frogs
DESCRIPTION:Blue Jays vs. Fire Frogs\n\nFollow on MiLB First Pitch: https://stza.co/+y0Hw-3Y\n\nShop: https://stza.co/+y0Hw-5\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144520Z
LAST-MODIFIED:20180213T144520Z
TRANSP:OPAQUE
END:VEVENT
* Blue Jays vs. Fire Frogs
<2018-05-22 Tue 17:30-20:30>
:PROPERTIES:
:ID:       SAL3N8nxZg8goIpXXQD_wyyC@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Blue Jays vs. Fire Frogs Blue Jays vs. Fire Frogs

Follow on MiLB First Pitch  https //stza.co/+y0Hy-1S

Shop  https //stza.co/+y0Hy-1s

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Blue Jays vs. Fire Frogs
END:VALARM
DTSTART:20180522T223000Z
DTEND:20180523T013000Z
UID:SAL3N8nxZg8goIpXXQD_wyyC@stanza.co
SUMMARY:Blue Jays vs. Fire Frogs
DESCRIPTION:Blue Jays vs. Fire Frogs\n\nFollow on MiLB First Pitch: https://stza.co/+y0Hy-1S\n\nShop: https://stza.co/+y0Hy-1s\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144520Z
LAST-MODIFIED:20180213T144520Z
TRANSP:OPAQUE
END:VEVENT
* Blue Jays vs. Fire Frogs
<2018-05-23 Wed 17:30-20:30>
:PROPERTIES:
:ID:       j-TbI1U0a4IHv5fnajraoapb@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Blue Jays vs. Fire Frogs Blue Jays vs. Fire Frogs

Follow on MiLB First Pitch  https //stza.co/+y0HA-q

Shop  https //stza.co/+y0HA-2P

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Blue Jays vs. Fire Frogs
END:VALARM
DTSTART:20180523T223000Z
DTEND:20180524T013000Z
UID:j-TbI1U0a4IHv5fnajraoapb@stanza.co
SUMMARY:Blue Jays vs. Fire Frogs
DESCRIPTION:Blue Jays vs. Fire Frogs\n\nFollow on MiLB First Pitch: https://stza.co/+y0HA-q\n\nShop: https://stza.co/+y0HA-2P\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144520Z
LAST-MODIFIED:20180213T144520Z
TRANSP:OPAQUE
END:VEVENT
* Blue Jays vs. Flying Tigers
<2018-05-24 Thu 17:30-20:30>
:PROPERTIES:
:ID:       OYuhmyGFz3qtsVQSUQ5dq1u-@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Blue Jays vs. Flying Tigers Blue Jays vs. Flying Tigers

Follow on MiLB First Pitch  https //stza.co/+y0HC-7

Shop  https //stza.co/+y0HC-K

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Blue Jays vs. Flying Tigers
END:VALARM
DTSTART:20180524T223000Z
DTEND:20180525T013000Z
UID:OYuhmyGFz3qtsVQSUQ5dq1u-@stanza.co
SUMMARY:Blue Jays vs. Flying Tigers
DESCRIPTION:Blue Jays vs. Flying Tigers\n\nFollow on MiLB First Pitch: https://stza.co/+y0HC-7\n\nShop: https://stza.co/+y0HC-K\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144520Z
LAST-MODIFIED:20180213T144520Z
TRANSP:OPAQUE
END:VEVENT
* Blue Jays vs. Flying Tigers
<2018-05-25 Fri 17:30-20:30>
:PROPERTIES:
:ID:       fpq7Pm7LTCBeTAoi7cebqAgL@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Blue Jays vs. Flying Tigers Blue Jays vs. Flying Tigers

Follow on MiLB First Pitch  https //stza.co/+y0HD-1S

Shop  https //stza.co/+y0HD-J

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Blue Jays vs. Flying Tigers
END:VALARM
DTSTART:20180525T223000Z
DTEND:20180526T013000Z
UID:fpq7Pm7LTCBeTAoi7cebqAgL@stanza.co
SUMMARY:Blue Jays vs. Flying Tigers
DESCRIPTION:Blue Jays vs. Flying Tigers\n\nFollow on MiLB First Pitch: https://stza.co/+y0HD-1S\n\nShop: https://stza.co/+y0HD-J\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144520Z
LAST-MODIFIED:20180213T144520Z
TRANSP:OPAQUE
END:VEVENT
* Blue Jays vs. Flying Tigers
<2018-05-26 Sat 17:30-20:30>
:PROPERTIES:
:ID:       pL1qibnHx-OhDKIzfpyO8ifa@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Blue Jays vs. Flying Tigers Blue Jays vs. Flying Tigers

Follow on MiLB First Pitch  https //stza.co/+y0HH-V

Shop  https //stza.co/+y0HH-2i

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Blue Jays vs. Flying Tigers
END:VALARM
DTSTART:20180526T223000Z
DTEND:20180527T013000Z
UID:pL1qibnHx-OhDKIzfpyO8ifa@stanza.co
SUMMARY:Blue Jays vs. Flying Tigers
DESCRIPTION:Blue Jays vs. Flying Tigers\n\nFollow on MiLB First Pitch: https://stza.co/+y0HH-V\n\nShop: https://stza.co/+y0HH-2i\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144520Z
LAST-MODIFIED:20180213T144520Z
TRANSP:OPAQUE
END:VEVENT
* Blue Jays vs. Flying Tigers
<2018-05-27 Sun 12:00-15:00>
:PROPERTIES:
:ID:       lnjB1RPQrQif7on2jUTo-JZx@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Blue Jays vs. Flying Tigers Blue Jays vs. Flying Tigers

Follow on MiLB First Pitch  https //stza.co/+y0HJ-2T

Shop  https //stza.co/+y0HJ-2D

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Blue Jays vs. Flying Tigers
END:VALARM
DTSTART:20180527T170000Z
DTEND:20180527T200000Z
UID:lnjB1RPQrQif7on2jUTo-JZx@stanza.co
SUMMARY:Blue Jays vs. Flying Tigers
DESCRIPTION:Blue Jays vs. Flying Tigers\n\nFollow on MiLB First Pitch: https://stza.co/+y0HJ-2T\n\nShop: https://stza.co/+y0HJ-2D\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144520Z
LAST-MODIFIED:20180213T144520Z
TRANSP:OPAQUE
END:VEVENT
* Blue Jays @ Fire Frogs
<2018-05-29 Tue 17:31-20:31>
:PROPERTIES:
:ID:       WF8i_JiljHwwovzl1AOlz4lO@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Blue Jays @ Fire Frogs Blue Jays @ Fire Frogs

Buy tickets here  https //stza.co/~xWKO

Follow on MiLB First Pitch  https //stza.co/+xWKO-2B

Shop  https //stza.co/+xWKO-2D

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Blue Jays @ Fire Frogs
END:VALARM
DTSTART:20180529T223100Z
DTEND:20180530T013100Z
UID:WF8i_JiljHwwovzl1AOlz4lO@stanza.co
SUMMARY:Blue Jays @ Fire Frogs
DESCRIPTION:Blue Jays @ Fire Frogs\n\nBuy tickets here: https://stza.co/~xWKO\n\nFollow on MiLB First Pitch: https://stza.co/+xWKO-2B\n\nShop: https://stza.co/+xWKO-2D\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144520Z
LAST-MODIFIED:20180213T144520Z
TRANSP:OPAQUE
END:VEVENT
* Blue Jays @ Fire Frogs
<2018-05-30 Wed 17:31-20:31>
:PROPERTIES:
:ID:       -VKWnWFkYElb6gVF8-6MMOlQ@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Blue Jays @ Fire Frogs Blue Jays @ Fire Frogs

Buy tickets here  https //stza.co/~xWKR

Follow on MiLB First Pitch  https //stza.co/+xWKR-B

Shop  https //stza.co/+xWKR-F

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Blue Jays @ Fire Frogs
END:VALARM
DTSTART:20180530T223100Z
DTEND:20180531T013100Z
UID:-VKWnWFkYElb6gVF8-6MMOlQ@stanza.co
SUMMARY:Blue Jays @ Fire Frogs
DESCRIPTION:Blue Jays @ Fire Frogs\n\nBuy tickets here: https://stza.co/~xWKR\n\nFollow on MiLB First Pitch: https://stza.co/+xWKR-B\n\nShop: https://stza.co/+xWKR-F\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144520Z
LAST-MODIFIED:20180213T144520Z
TRANSP:OPAQUE
END:VEVENT
* Blue Jays @ Fire Frogs
<2018-05-31 Thu 17:31-20:31>
:PROPERTIES:
:ID:       N1J96tg33r4SOVFaYVaoQjku@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Blue Jays @ Fire Frogs Blue Jays @ Fire Frogs

Buy tickets here  https //stza.co/~xWKS

Follow on MiLB First Pitch  https //stza.co/+xWKS-V

Shop  https //stza.co/+xWKS-3q

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Blue Jays @ Fire Frogs
END:VALARM
DTSTART:20180531T223100Z
DTEND:20180601T013100Z
UID:N1J96tg33r4SOVFaYVaoQjku@stanza.co
SUMMARY:Blue Jays @ Fire Frogs
DESCRIPTION:Blue Jays @ Fire Frogs\n\nBuy tickets here: https://stza.co/~xWKS\n\nFollow on MiLB First Pitch: https://stza.co/+xWKS-V\n\nShop: https://stza.co/+xWKS-3q\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144520Z
LAST-MODIFIED:20180213T144520Z
TRANSP:OPAQUE
END:VEVENT
* Blue Jays vs. Tarpons
<2018-06-01 Fri 17:30-20:30>
:PROPERTIES:
:ID:       nwa62R5my5EdYPrNMSaFD97b@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Blue Jays vs. Tarpons Blue Jays vs. Tarpons

Follow on MiLB First Pitch  https //stza.co/+y0HN-2u

Shop  https //stza.co/+y0HN-3H

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Blue Jays vs. Tarpons
END:VALARM
DTSTART:20180601T223000Z
DTEND:20180602T013000Z
UID:nwa62R5my5EdYPrNMSaFD97b@stanza.co
SUMMARY:Blue Jays vs. Tarpons
DESCRIPTION:Blue Jays vs. Tarpons\n\nFollow on MiLB First Pitch: https://stza.co/+y0HN-2u\n\nShop: https://stza.co/+y0HN-3H\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144520Z
LAST-MODIFIED:20180213T144520Z
TRANSP:OPAQUE
END:VEVENT
* Blue Jays vs. Tarpons
<2018-06-02 Sat 17:30-20:30>
:PROPERTIES:
:ID:       XNx5lCw7k-ntDa6XrktfNHep@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Blue Jays vs. Tarpons Blue Jays vs. Tarpons

Follow on MiLB First Pitch  https //stza.co/+y0HP-o

Shop  https //stza.co/+y0HP-34

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Blue Jays vs. Tarpons
END:VALARM
DTSTART:20180602T223000Z
DTEND:20180603T013000Z
UID:XNx5lCw7k-ntDa6XrktfNHep@stanza.co
SUMMARY:Blue Jays vs. Tarpons
DESCRIPTION:Blue Jays vs. Tarpons\n\nFollow on MiLB First Pitch: https://stza.co/+y0HP-o\n\nShop: https://stza.co/+y0HP-34\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144520Z
LAST-MODIFIED:20180213T144520Z
TRANSP:OPAQUE
END:VEVENT
* Blue Jays vs. Tarpons
<2018-06-03 Sun 12:00-15:00>
:PROPERTIES:
:ID:       jNQH9Akl36avEZ2E-sqptDMv@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Blue Jays vs. Tarpons Blue Jays vs. Tarpons

Follow on MiLB First Pitch  https //stza.co/+y0HQ-1o

Shop  https //stza.co/+y0HQ-3M

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Blue Jays vs. Tarpons
END:VALARM
DTSTART:20180603T170000Z
DTEND:20180603T200000Z
UID:jNQH9Akl36avEZ2E-sqptDMv@stanza.co
SUMMARY:Blue Jays vs. Tarpons
DESCRIPTION:Blue Jays vs. Tarpons\n\nFollow on MiLB First Pitch: https://stza.co/+y0HQ-1o\n\nShop: https://stza.co/+y0HQ-3M\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144520Z
LAST-MODIFIED:20180213T144520Z
TRANSP:OPAQUE
END:VEVENT
* Blue Jays @ Stone Crabs
<2018-06-04 Mon 17:35-20:35>
:PROPERTIES:
:ID:       qq7FZfGTU9aK6RlJsJQF2_1H@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Blue Jays @ Stone Crabs Blue Jays @ Stone Crabs

Follow on MiLB First Pitch  https //stza.co/+wYn6-3_

Shop  https //stza.co/+wYn6-2K

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Blue Jays @ Stone Crabs
END:VALARM
DTSTART:20180604T223500Z
DTEND:20180605T013500Z
UID:qq7FZfGTU9aK6RlJsJQF2_1H@stanza.co
SUMMARY:Blue Jays @ Stone Crabs
DESCRIPTION:Blue Jays @ Stone Crabs\n\nFollow on MiLB First Pitch: https://stza.co/+wYn6-3_\n\nShop: https://stza.co/+wYn6-2K\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144520Z
LAST-MODIFIED:20180213T144520Z
TRANSP:OPAQUE
END:VEVENT
* Blue Jays @ Stone Crabs
<2018-06-05 Tue 17:35-20:35>
:PROPERTIES:
:ID:       Epb9Ph07BiIQZ62LNwnUSxjS@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Blue Jays @ Stone Crabs Blue Jays @ Stone Crabs

Follow on MiLB First Pitch  https //stza.co/+wYn7-2X

Shop  https //stza.co/+wYn7-1F

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Blue Jays @ Stone Crabs
END:VALARM
DTSTART:20180605T223500Z
DTEND:20180606T013500Z
UID:Epb9Ph07BiIQZ62LNwnUSxjS@stanza.co
SUMMARY:Blue Jays @ Stone Crabs
DESCRIPTION:Blue Jays @ Stone Crabs\n\nFollow on MiLB First Pitch: https://stza.co/+wYn7-2X\n\nShop: https://stza.co/+wYn7-1F\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144520Z
LAST-MODIFIED:20180213T144520Z
TRANSP:OPAQUE
END:VEVENT
* Blue Jays @ Stone Crabs
<2018-06-06 Wed 17:35-20:35>
:PROPERTIES:
:ID:       NHNDe1KZfB5A4_-DwDu_45vn@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Blue Jays @ Stone Crabs Blue Jays @ Stone Crabs

Follow on MiLB First Pitch  https //stza.co/+wYn8-2T

Shop  https //stza.co/+wYn8-39

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Blue Jays @ Stone Crabs
END:VALARM
DTSTART:20180606T223500Z
DTEND:20180607T013500Z
UID:NHNDe1KZfB5A4_-DwDu_45vn@stanza.co
SUMMARY:Blue Jays @ Stone Crabs
DESCRIPTION:Blue Jays @ Stone Crabs\n\nFollow on MiLB First Pitch: https://stza.co/+wYn8-2T\n\nShop: https://stza.co/+wYn8-39\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144520Z
LAST-MODIFIED:20180213T144520Z
TRANSP:OPAQUE
END:VEVENT
* Blue Jays @ Stone Crabs
<2018-06-07 Thu 17:35-20:35>
:PROPERTIES:
:ID:       -s01OEJEaH_vcD-kVkZtJWRB@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Blue Jays @ Stone Crabs Blue Jays @ Stone Crabs

Follow on MiLB First Pitch  https //stza.co/+wYna-l

Shop  https //stza.co/+wYna-J

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Blue Jays @ Stone Crabs
END:VALARM
DTSTART:20180607T223500Z
DTEND:20180608T013500Z
UID:-s01OEJEaH_vcD-kVkZtJWRB@stanza.co
SUMMARY:Blue Jays @ Stone Crabs
DESCRIPTION:Blue Jays @ Stone Crabs\n\nFollow on MiLB First Pitch: https://stza.co/+wYna-l\n\nShop: https://stza.co/+wYna-J\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144520Z
LAST-MODIFIED:20180213T144520Z
TRANSP:OPAQUE
END:VEVENT
* Blue Jays @ Miracle
<2018-06-08 Fri 18:00-21:00>
:PROPERTIES:
:ID:       KthYJxH7r1BwrXrjdbLMkUnV@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Blue Jays @ Miracle Blue Jays @ Miracle

Follow on MiLB First Pitch  https //stza.co/+xMaz-2p

Shop  https //stza.co/+xMaz-n

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Blue Jays @ Miracle
END:VALARM
DTSTART:20180608T230000Z
DTEND:20180609T020000Z
UID:KthYJxH7r1BwrXrjdbLMkUnV@stanza.co
SUMMARY:Blue Jays @ Miracle
DESCRIPTION:Blue Jays @ Miracle\n\nFollow on MiLB First Pitch: https://stza.co/+xMaz-2p\n\nShop: https://stza.co/+xMaz-n\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144520Z
LAST-MODIFIED:20180213T144520Z
TRANSP:OPAQUE
END:VEVENT
* Blue Jays @ Miracle
<2018-06-09 Sat 17:00-20:00>
:PROPERTIES:
:ID:       gTE_MTAXNWMprzsEFqtmc7_Y@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Blue Jays @ Miracle Blue Jays @ Miracle

Follow on MiLB First Pitch  https //stza.co/+xMaA-2x

Shop  https //stza.co/+xMaA-1H

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Blue Jays @ Miracle
END:VALARM
DTSTART:20180609T220000Z
DTEND:20180610T010000Z
UID:gTE_MTAXNWMprzsEFqtmc7_Y@stanza.co
SUMMARY:Blue Jays @ Miracle
DESCRIPTION:Blue Jays @ Miracle\n\nFollow on MiLB First Pitch: https://stza.co/+xMaA-2x\n\nShop: https://stza.co/+xMaA-1H\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144520Z
LAST-MODIFIED:20180213T144520Z
TRANSP:OPAQUE
END:VEVENT
* Blue Jays @ Miracle
<2018-06-10 Sun 15:00-18:00>
:PROPERTIES:
:ID:       fGIsTs7CUGFh2HhBHD5f8WzQ@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Blue Jays @ Miracle Blue Jays @ Miracle

Follow on MiLB First Pitch  https //stza.co/+xMaB-1B

Shop  https //stza.co/+xMaB-2n

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Blue Jays @ Miracle
END:VALARM
DTSTART:20180610T200000Z
DTEND:20180610T230000Z
UID:fGIsTs7CUGFh2HhBHD5f8WzQ@stanza.co
SUMMARY:Blue Jays @ Miracle
DESCRIPTION:Blue Jays @ Miracle\n\nFollow on MiLB First Pitch: https://stza.co/+xMaB-1B\n\nShop: https://stza.co/+xMaB-2n\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144520Z
LAST-MODIFIED:20180213T144520Z
TRANSP:OPAQUE
END:VEVENT
* Blue Jays vs. Stone Crabs
<2018-06-11 Mon 17:30-20:30>
:PROPERTIES:
:ID:       Si87nnC8sk6jvo0Dux2cW9nb@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Blue Jays vs. Stone Crabs Blue Jays vs. Stone Crabs

Follow on MiLB First Pitch  https //stza.co/+y0HS-1P

Shop  https //stza.co/+y0HS-X

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Blue Jays vs. Stone Crabs
END:VALARM
DTSTART:20180611T223000Z
DTEND:20180612T013000Z
UID:Si87nnC8sk6jvo0Dux2cW9nb@stanza.co
SUMMARY:Blue Jays vs. Stone Crabs
DESCRIPTION:Blue Jays vs. Stone Crabs\n\nFollow on MiLB First Pitch: https://stza.co/+y0HS-1P\n\nShop: https://stza.co/+y0HS-X\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144520Z
LAST-MODIFIED:20180213T144520Z
TRANSP:OPAQUE
END:VEVENT
* Blue Jays vs. Stone Crabs
<2018-06-12 Tue 17:30-20:30>
:PROPERTIES:
:ID:       1AsLGAOJ-o2FEuwPqYx557E_@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Blue Jays vs. Stone Crabs Blue Jays vs. Stone Crabs

Follow on MiLB First Pitch  https //stza.co/+y0HU-3P

Shop  https //stza.co/+y0HU-1l

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Blue Jays vs. Stone Crabs
END:VALARM
DTSTART:20180612T223000Z
DTEND:20180613T013000Z
UID:1AsLGAOJ-o2FEuwPqYx557E_@stanza.co
SUMMARY:Blue Jays vs. Stone Crabs
DESCRIPTION:Blue Jays vs. Stone Crabs\n\nFollow on MiLB First Pitch: https://stza.co/+y0HU-3P\n\nShop: https://stza.co/+y0HU-1l\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144520Z
LAST-MODIFIED:20180213T144520Z
TRANSP:OPAQUE
END:VEVENT
* Blue Jays vs. Stone Crabs
<2018-06-13 Wed 17:30-20:30>
:PROPERTIES:
:ID:       83y_-RC5by4dgit-TWULEMEY@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Blue Jays vs. Stone Crabs Blue Jays vs. Stone Crabs

Follow on MiLB First Pitch  https //stza.co/+y0HW-3r

Shop  https //stza.co/+y0HW-2R

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Blue Jays vs. Stone Crabs
END:VALARM
DTSTART:20180613T223000Z
DTEND:20180614T013000Z
UID:83y_-RC5by4dgit-TWULEMEY@stanza.co
SUMMARY:Blue Jays vs. Stone Crabs
DESCRIPTION:Blue Jays vs. Stone Crabs\n\nFollow on MiLB First Pitch: https://stza.co/+y0HW-3r\n\nShop: https://stza.co/+y0HW-2R\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144520Z
LAST-MODIFIED:20180213T144520Z
TRANSP:OPAQUE
END:VEVENT
* Blue Jays vs. Stone Crabs
<2018-06-14 Thu 17:30-20:30>
:PROPERTIES:
:ID:       pDFvUE7J04BvkkF0Lnnu5vzh@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Blue Jays vs. Stone Crabs Blue Jays vs. Stone Crabs

Follow on MiLB First Pitch  https //stza.co/+y0HZ-i

Shop  https //stza.co/+y0HZ-3E

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Blue Jays vs. Stone Crabs
END:VALARM
DTSTART:20180614T223000Z
DTEND:20180615T013000Z
UID:pDFvUE7J04BvkkF0Lnnu5vzh@stanza.co
SUMMARY:Blue Jays vs. Stone Crabs
DESCRIPTION:Blue Jays vs. Stone Crabs\n\nFollow on MiLB First Pitch: https://stza.co/+y0HZ-i\n\nShop: https://stza.co/+y0HZ-3E\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144520Z
LAST-MODIFIED:20180213T144520Z
TRANSP:OPAQUE
END:VEVENT
* Blue Jays vs. Mets
<2018-06-18 Mon 17:30-20:30>
:PROPERTIES:
:ID:       pSAkLgzyxPBi-hZVeDk0TA1w@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Blue Jays vs. Mets Blue Jays vs. Mets

Follow on MiLB First Pitch  https //stza.co/+y0H_-1V

Shop  https //stza.co/+y0H_-v

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Blue Jays vs. Mets
END:VALARM
DTSTART:20180618T223000Z
DTEND:20180619T013000Z
UID:pSAkLgzyxPBi-hZVeDk0TA1w@stanza.co
SUMMARY:Blue Jays vs. Mets
DESCRIPTION:Blue Jays vs. Mets\n\nFollow on MiLB First Pitch: https://stza.co/+y0H_-1V\n\nShop: https://stza.co/+y0H_-v\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144520Z
LAST-MODIFIED:20180213T144520Z
TRANSP:OPAQUE
END:VEVENT
* Blue Jays vs. Mets
<2018-06-19 Tue 17:30-20:30>
:PROPERTIES:
:ID:       KfhWahATnF2Vv8f76oUCneHU@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Blue Jays vs. Mets Blue Jays vs. Mets

Follow on MiLB First Pitch  https //stza.co/+y0I0-3O

Shop  https //stza.co/+y0I0-22

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Blue Jays vs. Mets
END:VALARM
DTSTART:20180619T223000Z
DTEND:20180620T013000Z
UID:KfhWahATnF2Vv8f76oUCneHU@stanza.co
SUMMARY:Blue Jays vs. Mets
DESCRIPTION:Blue Jays vs. Mets\n\nFollow on MiLB First Pitch: https://stza.co/+y0I0-3O\n\nShop: https://stza.co/+y0I0-22\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144520Z
LAST-MODIFIED:20180213T144520Z
TRANSP:OPAQUE
END:VEVENT
* Blue Jays vs. Mets
<2018-06-20 Wed 10:00-13:00>
:PROPERTIES:
:ID:       dgo6tV-pa0b07mR2J4tx-v46@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Blue Jays vs. Mets Blue Jays vs. Mets

Follow on MiLB First Pitch  https //stza.co/+y0I2-2h

Shop  https //stza.co/+y0I2-3

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Blue Jays vs. Mets
END:VALARM
DTSTART:20180620T150000Z
DTEND:20180620T180000Z
UID:dgo6tV-pa0b07mR2J4tx-v46@stanza.co
SUMMARY:Blue Jays vs. Mets
DESCRIPTION:Blue Jays vs. Mets\n\nFollow on MiLB First Pitch: https://stza.co/+y0I2-2h\n\nShop: https://stza.co/+y0I2-3\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144520Z
LAST-MODIFIED:20180213T144520Z
TRANSP:OPAQUE
END:VEVENT
* Blue Jays @ Threshers
<2018-06-21 Thu 18:00-21:00>
:PROPERTIES:
:ID:       qfmBuRb-8NZQQ8ovJg8_BkL_@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Blue Jays @ Threshers Blue Jays @ Threshers

Follow on MiLB First Pitch  https //stza.co/+xBdv-e

Shop  https //stza.co/+xBdv-1G

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Blue Jays @ Threshers
END:VALARM
DTSTART:20180621T230000Z
DTEND:20180622T020000Z
UID:qfmBuRb-8NZQQ8ovJg8_BkL_@stanza.co
SUMMARY:Blue Jays @ Threshers
DESCRIPTION:Blue Jays @ Threshers\n\nFollow on MiLB First Pitch: https://stza.co/+xBdv-e\n\nShop: https://stza.co/+xBdv-1G\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144520Z
LAST-MODIFIED:20180213T144520Z
TRANSP:OPAQUE
END:VEVENT
* Blue Jays @ Threshers
<2018-06-22 Fri 17:15-20:15>
:PROPERTIES:
:ID:       dhgZENrqSDvj4wCcTjvltk4V@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Blue Jays @ Threshers Blue Jays @ Threshers

Follow on MiLB First Pitch  https //stza.co/+xBdw-3n

Shop  https //stza.co/+xBdw-2e

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Blue Jays @ Threshers
END:VALARM
DTSTART:20180622T221500Z
DTEND:20180623T011500Z
UID:dhgZENrqSDvj4wCcTjvltk4V@stanza.co
SUMMARY:Blue Jays @ Threshers
DESCRIPTION:Blue Jays @ Threshers\n\nFollow on MiLB First Pitch: https://stza.co/+xBdw-3n\n\nShop: https://stza.co/+xBdw-2e\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144520Z
LAST-MODIFIED:20180213T144520Z
TRANSP:OPAQUE
END:VEVENT
* Blue Jays @ Threshers
<2018-06-23 Sat 17:15-20:15>
:PROPERTIES:
:ID:       nx_Nd1OW4EF5BDWJyv6htnrr@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Blue Jays @ Threshers Blue Jays @ Threshers

Follow on MiLB First Pitch  https //stza.co/+xBdx-1W

Shop  https //stza.co/+xBdx-2N

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Blue Jays @ Threshers
END:VALARM
DTSTART:20180623T221500Z
DTEND:20180624T011500Z
UID:nx_Nd1OW4EF5BDWJyv6htnrr@stanza.co
SUMMARY:Blue Jays @ Threshers
DESCRIPTION:Blue Jays @ Threshers\n\nFollow on MiLB First Pitch: https://stza.co/+xBdx-1W\n\nShop: https://stza.co/+xBdx-2N\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144520Z
LAST-MODIFIED:20180213T144520Z
TRANSP:OPAQUE
END:VEVENT
* Blue Jays @ Threshers
<2018-06-24 Sun 12:00-15:00>
:PROPERTIES:
:ID:       sDLjUTRi2xmoi9GPvyPtLPTU@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Blue Jays @ Threshers Blue Jays @ Threshers

Follow on MiLB First Pitch  https //stza.co/+xBdy-2d

Shop  https //stza.co/+xBdy-2b

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Blue Jays @ Threshers
END:VALARM
DTSTART:20180624T170000Z
DTEND:20180624T200000Z
UID:sDLjUTRi2xmoi9GPvyPtLPTU@stanza.co
SUMMARY:Blue Jays @ Threshers
DESCRIPTION:Blue Jays @ Threshers\n\nFollow on MiLB First Pitch: https://stza.co/+xBdy-2d\n\nShop: https://stza.co/+xBdy-2b\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144520Z
LAST-MODIFIED:20180213T144520Z
TRANSP:OPAQUE
END:VEVENT
* Blue Jays @ Fire Frogs
<2018-06-26 Tue 17:31-20:31>
:PROPERTIES:
:ID:       36XNJiYuUTyh-oRD7WIo9bet@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Blue Jays @ Fire Frogs Blue Jays @ Fire Frogs

Buy tickets here  https //stza.co/~xWKT

Follow on MiLB First Pitch  https //stza.co/+xWKT-S

Shop  https //stza.co/+xWKT-3J

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Blue Jays @ Fire Frogs
END:VALARM
DTSTART:20180626T223100Z
DTEND:20180627T013100Z
UID:36XNJiYuUTyh-oRD7WIo9bet@stanza.co
SUMMARY:Blue Jays @ Fire Frogs
DESCRIPTION:Blue Jays @ Fire Frogs\n\nBuy tickets here: https://stza.co/~xWKT\n\nFollow on MiLB First Pitch: https://stza.co/+xWKT-S\n\nShop: https://stza.co/+xWKT-3J\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144520Z
LAST-MODIFIED:20180213T144520Z
TRANSP:OPAQUE
END:VEVENT
* Blue Jays @ Fire Frogs
<2018-06-27 Wed 10:00-13:00>
:PROPERTIES:
:ID:       JnpEFMG_ldNtu8fehPVrgVXr@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Blue Jays @ Fire Frogs Blue Jays @ Fire Frogs

Buy tickets here  https //stza.co/~xWKU

Follow on MiLB First Pitch  https //stza.co/+xWKU-v

Shop  https //stza.co/+xWKU-17

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Blue Jays @ Fire Frogs
END:VALARM
DTSTART:20180627T150000Z
DTEND:20180627T180000Z
UID:JnpEFMG_ldNtu8fehPVrgVXr@stanza.co
SUMMARY:Blue Jays @ Fire Frogs
DESCRIPTION:Blue Jays @ Fire Frogs\n\nBuy tickets here: https://stza.co/~xWKU\n\nFollow on MiLB First Pitch: https://stza.co/+xWKU-v\n\nShop: https://stza.co/+xWKU-17\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144520Z
LAST-MODIFIED:20180213T144520Z
TRANSP:OPAQUE
END:VEVENT
* Blue Jays @ Fire Frogs
<2018-06-28 Thu 17:31-20:31>
:PROPERTIES:
:ID:       YYhHXw-R1wzSwWaSagh1Elow@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Blue Jays @ Fire Frogs Blue Jays @ Fire Frogs

Buy tickets here  https //stza.co/~xWKV

Follow on MiLB First Pitch  https //stza.co/+xWKV-1$

Shop  https //stza.co/+xWKV-1W

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Blue Jays @ Fire Frogs
END:VALARM
DTSTART:20180628T223100Z
DTEND:20180629T013100Z
UID:YYhHXw-R1wzSwWaSagh1Elow@stanza.co
SUMMARY:Blue Jays @ Fire Frogs
DESCRIPTION:Blue Jays @ Fire Frogs\n\nBuy tickets here: https://stza.co/~xWKV\n\nFollow on MiLB First Pitch: https://stza.co/+xWKV-1$\n\nShop: https://stza.co/+xWKV-1W\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144520Z
LAST-MODIFIED:20180213T144520Z
TRANSP:OPAQUE
END:VEVENT
* Blue Jays vs. Marauders
<2018-06-29 Fri 17:30-20:30>
:PROPERTIES:
:ID:       fm-6NUH_tQJzilmi6AoCIgaL@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Blue Jays vs. Marauders Blue Jays vs. Marauders

Follow on MiLB First Pitch  https //stza.co/+y0I5-g

Shop  https //stza.co/+y0I5-t

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Blue Jays vs. Marauders
END:VALARM
DTSTART:20180629T223000Z
DTEND:20180630T013000Z
UID:fm-6NUH_tQJzilmi6AoCIgaL@stanza.co
SUMMARY:Blue Jays vs. Marauders
DESCRIPTION:Blue Jays vs. Marauders\n\nFollow on MiLB First Pitch: https://stza.co/+y0I5-g\n\nShop: https://stza.co/+y0I5-t\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144520Z
LAST-MODIFIED:20180213T144520Z
TRANSP:OPAQUE
END:VEVENT
* Blue Jays vs. Marauders
<2018-06-30 Sat 17:30-20:30>
:PROPERTIES:
:ID:       qsHDHeYyke_RLp8EiPtZ2A8W@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Blue Jays vs. Marauders Blue Jays vs. Marauders

Follow on MiLB First Pitch  https //stza.co/+y0I6-1b

Shop  https //stza.co/+y0I6-G

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Blue Jays vs. Marauders
END:VALARM
DTSTART:20180630T223000Z
DTEND:20180701T013000Z
UID:qsHDHeYyke_RLp8EiPtZ2A8W@stanza.co
SUMMARY:Blue Jays vs. Marauders
DESCRIPTION:Blue Jays vs. Marauders\n\nFollow on MiLB First Pitch: https://stza.co/+y0I6-1b\n\nShop: https://stza.co/+y0I6-G\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144520Z
LAST-MODIFIED:20180213T144520Z
TRANSP:OPAQUE
END:VEVENT
* Blue Jays vs. Marauders
<2018-07-01 Sun 12:00-15:00>
:PROPERTIES:
:ID:       rTPAxCuOhMXuhVlVqZ8YDtFf@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Blue Jays vs. Marauders Blue Jays vs. Marauders

Follow on MiLB First Pitch  https //stza.co/+y0I9-20

Shop  https //stza.co/+y0I9-3c

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Blue Jays vs. Marauders
END:VALARM
DTSTART:20180701T170000Z
DTEND:20180701T200000Z
UID:rTPAxCuOhMXuhVlVqZ8YDtFf@stanza.co
SUMMARY:Blue Jays vs. Marauders
DESCRIPTION:Blue Jays vs. Marauders\n\nFollow on MiLB First Pitch: https://stza.co/+y0I9-20\n\nShop: https://stza.co/+y0I9-3c\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144520Z
LAST-MODIFIED:20180213T144520Z
TRANSP:OPAQUE
END:VEVENT
* Blue Jays vs. Tarpons
<2018-07-02 Mon 17:30-20:30>
:PROPERTIES:
:ID:       pC5VABWa7F1mA3yIY4QNtVJu@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Blue Jays vs. Tarpons Blue Jays vs. Tarpons

Follow on MiLB First Pitch  https //stza.co/+y0Ia-I

Shop  https //stza.co/+y0Ia-2R

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Blue Jays vs. Tarpons
END:VALARM
DTSTART:20180702T223000Z
DTEND:20180703T013000Z
UID:pC5VABWa7F1mA3yIY4QNtVJu@stanza.co
SUMMARY:Blue Jays vs. Tarpons
DESCRIPTION:Blue Jays vs. Tarpons\n\nFollow on MiLB First Pitch: https://stza.co/+y0Ia-I\n\nShop: https://stza.co/+y0Ia-2R\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144520Z
LAST-MODIFIED:20180213T144520Z
TRANSP:OPAQUE
END:VEVENT
* Blue Jays vs. Tarpons
<2018-07-03 Tue 17:30-20:30>
:PROPERTIES:
:ID:       EMAKCdjHMbEKUHLowyElqvRB@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Blue Jays vs. Tarpons Blue Jays vs. Tarpons

Follow on MiLB First Pitch  https //stza.co/+y0Ic-j

Shop  https //stza.co/+y0Ic-2r

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Blue Jays vs. Tarpons
END:VALARM
DTSTART:20180703T223000Z
DTEND:20180704T013000Z
UID:EMAKCdjHMbEKUHLowyElqvRB@stanza.co
SUMMARY:Blue Jays vs. Tarpons
DESCRIPTION:Blue Jays vs. Tarpons\n\nFollow on MiLB First Pitch: https://stza.co/+y0Ic-j\n\nShop: https://stza.co/+y0Ic-2r\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144520Z
LAST-MODIFIED:20180213T144520Z
TRANSP:OPAQUE
END:VEVENT
* Blue Jays @ Miracle
<2018-07-04 Wed 18:00-21:00>
:PROPERTIES:
:ID:       tc-Wyq8_hER54cbkAWS1eqx0@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Blue Jays @ Miracle Blue Jays @ Miracle

Follow on MiLB First Pitch  https //stza.co/+xMaC-w

Shop  https //stza.co/+xMaC-a

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Blue Jays @ Miracle
END:VALARM
DTSTART:20180704T230000Z
DTEND:20180705T020000Z
UID:tc-Wyq8_hER54cbkAWS1eqx0@stanza.co
SUMMARY:Blue Jays @ Miracle
DESCRIPTION:Blue Jays @ Miracle\n\nFollow on MiLB First Pitch: https://stza.co/+xMaC-w\n\nShop: https://stza.co/+xMaC-a\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144520Z
LAST-MODIFIED:20180213T144520Z
TRANSP:OPAQUE
END:VEVENT
* Blue Jays @ Miracle
<2018-07-05 Thu 18:00-21:00>
:PROPERTIES:
:ID:       6QVC8Qg3iWtEsABXd-Vj-cxH@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Blue Jays @ Miracle Blue Jays @ Miracle

Follow on MiLB First Pitch  https //stza.co/+xMaD-2Z

Shop  https //stza.co/+xMaD-37

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Blue Jays @ Miracle
END:VALARM
DTSTART:20180705T230000Z
DTEND:20180706T020000Z
UID:6QVC8Qg3iWtEsABXd-Vj-cxH@stanza.co
SUMMARY:Blue Jays @ Miracle
DESCRIPTION:Blue Jays @ Miracle\n\nFollow on MiLB First Pitch: https://stza.co/+xMaD-2Z\n\nShop: https://stza.co/+xMaD-37\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144520Z
LAST-MODIFIED:20180213T144520Z
TRANSP:OPAQUE
END:VEVENT
* Blue Jays @ Mets
<2018-07-06 Fri 17:30-20:30>
:PROPERTIES:
:ID:       YsI74_5xRwCnnQCrNKwt4v1Q@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Blue Jays @ Mets Blue Jays @ Mets

Follow on MiLB First Pitch  https //stza.co/+vMnK-C

Shop  https //stza.co/+vMnK-M

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Blue Jays @ Mets
END:VALARM
DTSTART:20180706T223000Z
DTEND:20180707T013000Z
UID:YsI74_5xRwCnnQCrNKwt4v1Q@stanza.co
SUMMARY:Blue Jays @ Mets
DESCRIPTION:Blue Jays @ Mets\n\nFollow on MiLB First Pitch: https://stza.co/+vMnK-C\n\nShop: https://stza.co/+vMnK-M\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144520Z
LAST-MODIFIED:20180213T144520Z
TRANSP:OPAQUE
END:VEVENT
* Blue Jays @ Mets
<2018-07-07 Sat 17:30-20:30>
:PROPERTIES:
:ID:       dsYpCdC0bnryADKI9_BXC3A6@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Blue Jays @ Mets Blue Jays @ Mets

Follow on MiLB First Pitch  https //stza.co/+vMnL-3v

Shop  https //stza.co/+vMnL-2x

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Blue Jays @ Mets
END:VALARM
DTSTART:20180707T223000Z
DTEND:20180708T013000Z
UID:dsYpCdC0bnryADKI9_BXC3A6@stanza.co
SUMMARY:Blue Jays @ Mets
DESCRIPTION:Blue Jays @ Mets\n\nFollow on MiLB First Pitch: https://stza.co/+vMnL-3v\n\nShop: https://stza.co/+vMnL-2x\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144520Z
LAST-MODIFIED:20180213T144520Z
TRANSP:OPAQUE
END:VEVENT
* Blue Jays @ Mets
<2018-07-08 Sun 11:00-14:00>
:PROPERTIES:
:ID:       at8ZD_sQU9y5hHfABQ2hAtFY@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Blue Jays @ Mets Blue Jays @ Mets

Follow on MiLB First Pitch  https //stza.co/+vMnM-s

Shop  https //stza.co/+vMnM-3s

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Blue Jays @ Mets
END:VALARM
DTSTART:20180708T160000Z
DTEND:20180708T190000Z
UID:at8ZD_sQU9y5hHfABQ2hAtFY@stanza.co
SUMMARY:Blue Jays @ Mets
DESCRIPTION:Blue Jays @ Mets\n\nFollow on MiLB First Pitch: https://stza.co/+vMnM-s\n\nShop: https://stza.co/+vMnM-3s\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144520Z
LAST-MODIFIED:20180213T144520Z
TRANSP:OPAQUE
END:VEVENT
* Blue Jays vs. Threshers
<2018-07-09 Mon 17:30-20:30>
:PROPERTIES:
:ID:       XSzSNEi4JmKsMgqj66t8gVTV@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Blue Jays vs. Threshers Blue Jays vs. Threshers

Follow on MiLB First Pitch  https //stza.co/+y0If-2A

Shop  https //stza.co/+y0If-23

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Blue Jays vs. Threshers
END:VALARM
DTSTART:20180709T223000Z
DTEND:20180710T013000Z
UID:XSzSNEi4JmKsMgqj66t8gVTV@stanza.co
SUMMARY:Blue Jays vs. Threshers
DESCRIPTION:Blue Jays vs. Threshers\n\nFollow on MiLB First Pitch: https://stza.co/+y0If-2A\n\nShop: https://stza.co/+y0If-23\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144520Z
LAST-MODIFIED:20180213T144520Z
TRANSP:OPAQUE
END:VEVENT
* Blue Jays vs. Threshers
<2018-07-10 Tue 17:30-20:30>
:PROPERTIES:
:ID:       28ZVr8aVlTnOULXz4FBcBbGE@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Blue Jays vs. Threshers Blue Jays vs. Threshers

Follow on MiLB First Pitch  https //stza.co/+y0Ih-m

Shop  https //stza.co/+y0Ih-3k

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Blue Jays vs. Threshers
END:VALARM
DTSTART:20180710T223000Z
DTEND:20180711T013000Z
UID:28ZVr8aVlTnOULXz4FBcBbGE@stanza.co
SUMMARY:Blue Jays vs. Threshers
DESCRIPTION:Blue Jays vs. Threshers\n\nFollow on MiLB First Pitch: https://stza.co/+y0Ih-m\n\nShop: https://stza.co/+y0Ih-3k\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144520Z
LAST-MODIFIED:20180213T144520Z
TRANSP:OPAQUE
END:VEVENT
* Blue Jays vs. Threshers
<2018-07-11 Wed 17:30-20:30>
:PROPERTIES:
:ID:       0o_kwOv1RFjLLrpM3nw-QdSP@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Blue Jays vs. Threshers Blue Jays vs. Threshers

Follow on MiLB First Pitch  https //stza.co/+y0Ik-7

Shop  https //stza.co/+y0Ik-2b

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Blue Jays vs. Threshers
END:VALARM
DTSTART:20180711T223000Z
DTEND:20180712T013000Z
UID:0o_kwOv1RFjLLrpM3nw-QdSP@stanza.co
SUMMARY:Blue Jays vs. Threshers
DESCRIPTION:Blue Jays vs. Threshers\n\nFollow on MiLB First Pitch: https://stza.co/+y0Ik-7\n\nShop: https://stza.co/+y0Ik-2b\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144520Z
LAST-MODIFIED:20180213T144520Z
TRANSP:OPAQUE
END:VEVENT
* Blue Jays vs. Threshers
<2018-07-12 Thu 17:30-20:30>
:PROPERTIES:
:ID:       7SxSb1JnDBfvuEkHS8WryS0S@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Blue Jays vs. Threshers Blue Jays vs. Threshers

Follow on MiLB First Pitch  https //stza.co/+y0Il-Z

Shop  https //stza.co/+y0Il-3h

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Blue Jays vs. Threshers
END:VALARM
DTSTART:20180712T223000Z
DTEND:20180713T013000Z
UID:7SxSb1JnDBfvuEkHS8WryS0S@stanza.co
SUMMARY:Blue Jays vs. Threshers
DESCRIPTION:Blue Jays vs. Threshers\n\nFollow on MiLB First Pitch: https://stza.co/+y0Il-Z\n\nShop: https://stza.co/+y0Il-3h\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144520Z
LAST-MODIFIED:20180213T144520Z
TRANSP:OPAQUE
END:VEVENT
* Blue Jays @ Tarpons
<2018-07-13 Fri>--<2018-07-12 Thu>
:PROPERTIES:
:ID:       OcNNpDw2X6FhSC9xd0syRbwy@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Blue Jays @ Tarpons Blue Jays @ Tarpons

Follow on MiLB First Pitch  https //stza.co/+vjKm-L

Shop  https //stza.co/+vjKm-2b

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Blue Jays @ Tarpons
END:VALARM
DTSTART;VALUE=DATE:20180713
DTEND;VALUE=DATE:20180713
UID:OcNNpDw2X6FhSC9xd0syRbwy@stanza.co
SUMMARY:Blue Jays @ Tarpons
DESCRIPTION:Blue Jays @ Tarpons\n\nFollow on MiLB First Pitch: https://stza.co/+vjKm-L\n\nShop: https://stza.co/+vjKm-2b\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144520Z
LAST-MODIFIED:20180213T144520Z
TRANSP:OPAQUE
END:VEVENT
* Blue Jays @ Tarpons
<2018-07-14 Sat>--<2018-07-13 Fri>
:PROPERTIES:
:ID:       GvK3TQbW-SQQY4Hrx1mDHmHy@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Blue Jays @ Tarpons Blue Jays @ Tarpons

Follow on MiLB First Pitch  https //stza.co/+vjKn-1Y

Shop  https //stza.co/+vjKn-24

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Blue Jays @ Tarpons
END:VALARM
DTSTART;VALUE=DATE:20180714
DTEND;VALUE=DATE:20180714
UID:GvK3TQbW-SQQY4Hrx1mDHmHy@stanza.co
SUMMARY:Blue Jays @ Tarpons
DESCRIPTION:Blue Jays @ Tarpons\n\nFollow on MiLB First Pitch: https://stza.co/+vjKn-1Y\n\nShop: https://stza.co/+vjKn-24\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144520Z
LAST-MODIFIED:20180213T144520Z
TRANSP:OPAQUE
END:VEVENT
* Blue Jays @ Tarpons
<2018-07-15 Sun>--<2018-07-14 Sat>
:PROPERTIES:
:ID:       tQJX6YYyL1l0yQQcJ0lQPC1t@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Blue Jays @ Tarpons Blue Jays @ Tarpons

Follow on MiLB First Pitch  https //stza.co/+viIS-1Z

Shop  https //stza.co/+viIS-F

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Blue Jays @ Tarpons
END:VALARM
DTSTART;VALUE=DATE:20180715
DTEND;VALUE=DATE:20180715
UID:tQJX6YYyL1l0yQQcJ0lQPC1t@stanza.co
SUMMARY:Blue Jays @ Tarpons
DESCRIPTION:Blue Jays @ Tarpons\n\nFollow on MiLB First Pitch: https://stza.co/+viIS-1Z\n\nShop: https://stza.co/+viIS-F\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144520Z
LAST-MODIFIED:20180213T144520Z
TRANSP:OPAQUE
END:VEVENT
* Blue Jays vs. Fire Frogs
<2018-07-16 Mon 17:30-20:30>
:PROPERTIES:
:ID:       fMOWBx7dEjMWVwzO3uFEKbVZ@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Blue Jays vs. Fire Frogs Blue Jays vs. Fire Frogs

Follow on MiLB First Pitch  https //stza.co/+y0Io-32

Shop  https //stza.co/+y0Io-1q

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Blue Jays vs. Fire Frogs
END:VALARM
DTSTART:20180716T223000Z
DTEND:20180717T013000Z
UID:fMOWBx7dEjMWVwzO3uFEKbVZ@stanza.co
SUMMARY:Blue Jays vs. Fire Frogs
DESCRIPTION:Blue Jays vs. Fire Frogs\n\nFollow on MiLB First Pitch: https://stza.co/+y0Io-32\n\nShop: https://stza.co/+y0Io-1q\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144520Z
LAST-MODIFIED:20180213T144520Z
TRANSP:OPAQUE
END:VEVENT
* Blue Jays vs. Fire Frogs
<2018-07-17 Tue 10:00-13:00>
:PROPERTIES:
:ID:       WLN62jEWu-Yyp4owCMGAVrUG@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Blue Jays vs. Fire Frogs Blue Jays vs. Fire Frogs

Follow on MiLB First Pitch  https //stza.co/+y0Ip-3s

Shop  https //stza.co/+y0Ip-2h

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Blue Jays vs. Fire Frogs
END:VALARM
DTSTART:20180717T150000Z
DTEND:20180717T180000Z
UID:WLN62jEWu-Yyp4owCMGAVrUG@stanza.co
SUMMARY:Blue Jays vs. Fire Frogs
DESCRIPTION:Blue Jays vs. Fire Frogs\n\nFollow on MiLB First Pitch: https://stza.co/+y0Ip-3s\n\nShop: https://stza.co/+y0Ip-2h\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144520Z
LAST-MODIFIED:20180213T144520Z
TRANSP:OPAQUE
END:VEVENT
* Blue Jays vs. Fire Frogs
<2018-07-18 Wed 17:30-20:30>
:PROPERTIES:
:ID:       PXlj5fZOsYb0x_iGmra8y2oH@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Blue Jays vs. Fire Frogs Blue Jays vs. Fire Frogs

Follow on MiLB First Pitch  https //stza.co/+y0Ir-11

Shop  https //stza.co/+y0Ir-1Q

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Blue Jays vs. Fire Frogs
END:VALARM
DTSTART:20180718T223000Z
DTEND:20180719T013000Z
UID:PXlj5fZOsYb0x_iGmra8y2oH@stanza.co
SUMMARY:Blue Jays vs. Fire Frogs
DESCRIPTION:Blue Jays vs. Fire Frogs\n\nFollow on MiLB First Pitch: https://stza.co/+y0Ir-11\n\nShop: https://stza.co/+y0Ir-1Q\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144520Z
LAST-MODIFIED:20180213T144520Z
TRANSP:OPAQUE
END:VEVENT
* Blue Jays vs. Tarpons
<2018-07-19 Thu 17:30-20:30>
:PROPERTIES:
:ID:       lp4VRjPvPlcED5f3xQUNy7zI@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Blue Jays vs. Tarpons Blue Jays vs. Tarpons

Follow on MiLB First Pitch  https //stza.co/+y0It-2D

Shop  https //stza.co/+y0It-2R

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Blue Jays vs. Tarpons
END:VALARM
DTSTART:20180719T223000Z
DTEND:20180720T013000Z
UID:lp4VRjPvPlcED5f3xQUNy7zI@stanza.co
SUMMARY:Blue Jays vs. Tarpons
DESCRIPTION:Blue Jays vs. Tarpons\n\nFollow on MiLB First Pitch: https://stza.co/+y0It-2D\n\nShop: https://stza.co/+y0It-2R\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144520Z
LAST-MODIFIED:20180213T144520Z
TRANSP:OPAQUE
END:VEVENT
* Blue Jays vs. Tarpons
<2018-07-20 Fri 17:30-20:30>
:PROPERTIES:
:ID:       OizLlBFX__AEb_zK2G8_wXma@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Blue Jays vs. Tarpons Blue Jays vs. Tarpons

Follow on MiLB First Pitch  https //stza.co/+y0Iv-M

Shop  https //stza.co/+y0Iv-g

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Blue Jays vs. Tarpons
END:VALARM
DTSTART:20180720T223000Z
DTEND:20180721T013000Z
UID:OizLlBFX__AEb_zK2G8_wXma@stanza.co
SUMMARY:Blue Jays vs. Tarpons
DESCRIPTION:Blue Jays vs. Tarpons\n\nFollow on MiLB First Pitch: https://stza.co/+y0Iv-M\n\nShop: https://stza.co/+y0Iv-g\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144520Z
LAST-MODIFIED:20180213T144520Z
TRANSP:OPAQUE
END:VEVENT
* Blue Jays vs. Tarpons
<2018-07-21 Sat 17:30-20:30>
:PROPERTIES:
:ID:       djkivvasshin_x4rFxI3S1M7@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Blue Jays vs. Tarpons Blue Jays vs. Tarpons

Follow on MiLB First Pitch  https //stza.co/+y0Iy-1v

Shop  https //stza.co/+y0Iy-2t

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Blue Jays vs. Tarpons
END:VALARM
DTSTART:20180721T223000Z
DTEND:20180722T013000Z
UID:djkivvasshin_x4rFxI3S1M7@stanza.co
SUMMARY:Blue Jays vs. Tarpons
DESCRIPTION:Blue Jays vs. Tarpons\n\nFollow on MiLB First Pitch: https://stza.co/+y0Iy-1v\n\nShop: https://stza.co/+y0Iy-2t\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144520Z
LAST-MODIFIED:20180213T144520Z
TRANSP:OPAQUE
END:VEVENT
* Blue Jays @ Flying Tigers
<2018-07-23 Mon 17:30-20:30>
:PROPERTIES:
:ID:       nYqtwdM9L0tXmn3s_Rf5GV-r@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Blue Jays @ Flying Tigers Blue Jays @ Flying Tigers

Follow on MiLB First Pitch  https //stza.co/+wKMJ-3E

Shop  https //stza.co/+wKMJ-1U

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Blue Jays @ Flying Tigers
END:VALARM
DTSTART:20180723T223000Z
DTEND:20180724T013000Z
UID:nYqtwdM9L0tXmn3s_Rf5GV-r@stanza.co
SUMMARY:Blue Jays @ Flying Tigers
DESCRIPTION:Blue Jays @ Flying Tigers\n\nFollow on MiLB First Pitch: https://stza.co/+wKMJ-3E\n\nShop: https://stza.co/+wKMJ-1U\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144520Z
LAST-MODIFIED:20180213T144520Z
TRANSP:OPAQUE
END:VEVENT
* Blue Jays @ Flying Tigers
<2018-07-24 Tue 17:30-20:30>
:PROPERTIES:
:ID:       Cr-FnqL9ZU1V9thXn9vn6GiO@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Blue Jays @ Flying Tigers Blue Jays @ Flying Tigers

Follow on MiLB First Pitch  https //stza.co/+wKMK-33

Shop  https //stza.co/+wKMK-2

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Blue Jays @ Flying Tigers
END:VALARM
DTSTART:20180724T223000Z
DTEND:20180725T013000Z
UID:Cr-FnqL9ZU1V9thXn9vn6GiO@stanza.co
SUMMARY:Blue Jays @ Flying Tigers
DESCRIPTION:Blue Jays @ Flying Tigers\n\nFollow on MiLB First Pitch: https://stza.co/+wKMK-33\n\nShop: https://stza.co/+wKMK-2\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144520Z
LAST-MODIFIED:20180213T144520Z
TRANSP:OPAQUE
END:VEVENT
* Blue Jays @ Flying Tigers
<2018-07-25 Wed 17:30-20:30>
:PROPERTIES:
:ID:       o-W3wHEIoAv99eWsKWKC6FbP@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Blue Jays @ Flying Tigers Blue Jays @ Flying Tigers

Follow on MiLB First Pitch  https //stza.co/+wKML-_

Shop  https //stza.co/+wKML-2s

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Blue Jays @ Flying Tigers
END:VALARM
DTSTART:20180725T223000Z
DTEND:20180726T013000Z
UID:o-W3wHEIoAv99eWsKWKC6FbP@stanza.co
SUMMARY:Blue Jays @ Flying Tigers
DESCRIPTION:Blue Jays @ Flying Tigers\n\nFollow on MiLB First Pitch: https://stza.co/+wKML-_\n\nShop: https://stza.co/+wKML-2s\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144520Z
LAST-MODIFIED:20180213T144520Z
TRANSP:OPAQUE
END:VEVENT
* Blue Jays @ Hammerheads
<2018-07-26 Thu>--<2018-07-25 Wed>
:PROPERTIES:
:ID:       5gXxEZ52IUP1xAkkolHJIvfc@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Blue Jays @ Hammerheads Blue Jays @ Hammerheads

Buy tickets here  https //stza.co/~vMnt

Follow on MiLB First Pitch  https //stza.co/+vMnt-6

Shop  https //stza.co/+vMnt-2Q

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Blue Jays @ Hammerheads
END:VALARM
DTSTART;VALUE=DATE:20180726
DTEND;VALUE=DATE:20180726
UID:5gXxEZ52IUP1xAkkolHJIvfc@stanza.co
SUMMARY:Blue Jays @ Hammerheads
DESCRIPTION:Blue Jays @ Hammerheads\n\nBuy tickets here: https://stza.co/~vMnt\n\nFollow on MiLB First Pitch: https://stza.co/+vMnt-6\n\nShop: https://stza.co/+vMnt-2Q\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144520Z
LAST-MODIFIED:20180213T144520Z
TRANSP:OPAQUE
END:VEVENT
* Blue Jays @ Hammerheads
<2018-07-27 Fri>--<2018-07-26 Thu>
:PROPERTIES:
:ID:       XhYnlLQt-ZMrNF1lSGE5BiWW@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Blue Jays @ Hammerheads Blue Jays @ Hammerheads

Buy tickets here  https //stza.co/~vMnu

Follow on MiLB First Pitch  https //stza.co/+vMnu-V

Shop  https //stza.co/+vMnu-1_

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Blue Jays @ Hammerheads
END:VALARM
DTSTART;VALUE=DATE:20180727
DTEND;VALUE=DATE:20180727
UID:XhYnlLQt-ZMrNF1lSGE5BiWW@stanza.co
SUMMARY:Blue Jays @ Hammerheads
DESCRIPTION:Blue Jays @ Hammerheads\n\nBuy tickets here: https://stza.co/~vMnu\n\nFollow on MiLB First Pitch: https://stza.co/+vMnu-V\n\nShop: https://stza.co/+vMnu-1_\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144520Z
LAST-MODIFIED:20180213T144520Z
TRANSP:OPAQUE
END:VEVENT
* Blue Jays @ Hammerheads
<2018-07-28 Sat>--<2018-07-27 Fri>
:PROPERTIES:
:ID:       hNX7Ij8KnlIxcVW8AQpFzC9O@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Blue Jays @ Hammerheads Blue Jays @ Hammerheads

Buy tickets here  https //stza.co/~vMnv

Follow on MiLB First Pitch  https //stza.co/+vMnv-1l

Shop  https //stza.co/+vMnv-1g

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Blue Jays @ Hammerheads
END:VALARM
DTSTART;VALUE=DATE:20180728
DTEND;VALUE=DATE:20180728
UID:hNX7Ij8KnlIxcVW8AQpFzC9O@stanza.co
SUMMARY:Blue Jays @ Hammerheads
DESCRIPTION:Blue Jays @ Hammerheads\n\nBuy tickets here: https://stza.co/~vMnv\n\nFollow on MiLB First Pitch: https://stza.co/+vMnv-1l\n\nShop: https://stza.co/+vMnv-1g\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144520Z
LAST-MODIFIED:20180213T144520Z
TRANSP:OPAQUE
END:VEVENT
* Blue Jays @ Hammerheads
<2018-07-29 Sun>--<2018-07-28 Sat>
:PROPERTIES:
:ID:       IwMS7_Fw_QQCwN2kaROIpd5g@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Blue Jays @ Hammerheads Blue Jays @ Hammerheads

Buy tickets here  https //stza.co/~vMnw

Follow on MiLB First Pitch  https //stza.co/+vMnw-2f

Shop  https //stza.co/+vMnw-T

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Blue Jays @ Hammerheads
END:VALARM
DTSTART;VALUE=DATE:20180729
DTEND;VALUE=DATE:20180729
UID:IwMS7_Fw_QQCwN2kaROIpd5g@stanza.co
SUMMARY:Blue Jays @ Hammerheads
DESCRIPTION:Blue Jays @ Hammerheads\n\nBuy tickets here: https://stza.co/~vMnw\n\nFollow on MiLB First Pitch: https://stza.co/+vMnw-2f\n\nShop: https://stza.co/+vMnw-T\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144520Z
LAST-MODIFIED:20180213T144520Z
TRANSP:OPAQUE
END:VEVENT
* Blue Jays vs. Flying Tigers
<2018-07-31 Tue 17:30-20:30>
:PROPERTIES:
:ID:       jJzp7WH-RgSiUcF-jd6m6D1I@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Blue Jays vs. Flying Tigers Blue Jays vs. Flying Tigers

Follow on MiLB First Pitch  https //stza.co/+y0Iz-L

Shop  https //stza.co/+y0Iz-3u

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Blue Jays vs. Flying Tigers
END:VALARM
DTSTART:20180731T223000Z
DTEND:20180801T013000Z
UID:jJzp7WH-RgSiUcF-jd6m6D1I@stanza.co
SUMMARY:Blue Jays vs. Flying Tigers
DESCRIPTION:Blue Jays vs. Flying Tigers\n\nFollow on MiLB First Pitch: https://stza.co/+y0Iz-L\n\nShop: https://stza.co/+y0Iz-3u\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144520Z
LAST-MODIFIED:20180213T144520Z
TRANSP:OPAQUE
END:VEVENT
* Blue Jays vs. Flying Tigers
<2018-08-01 Wed 17:30-20:30>
:PROPERTIES:
:ID:       EvkP2Y7kBGVgFRCot_BkCLdY@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Blue Jays vs. Flying Tigers Blue Jays vs. Flying Tigers

Follow on MiLB First Pitch  https //stza.co/+y0IC-1u

Shop  https //stza.co/+y0IC-29

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Blue Jays vs. Flying Tigers
END:VALARM
DTSTART:20180801T223000Z
DTEND:20180802T013000Z
UID:EvkP2Y7kBGVgFRCot_BkCLdY@stanza.co
SUMMARY:Blue Jays vs. Flying Tigers
DESCRIPTION:Blue Jays vs. Flying Tigers\n\nFollow on MiLB First Pitch: https://stza.co/+y0IC-1u\n\nShop: https://stza.co/+y0IC-29\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144520Z
LAST-MODIFIED:20180213T144520Z
TRANSP:OPAQUE
END:VEVENT
* Blue Jays vs. Flying Tigers
<2018-08-02 Thu 17:30-20:30>
:PROPERTIES:
:ID:       bBRjCAhM-wtRskWs5_nB43z4@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Blue Jays vs. Flying Tigers Blue Jays vs. Flying Tigers

Follow on MiLB First Pitch  https //stza.co/+y0ID-3R

Shop  https //stza.co/+y0ID-E

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Blue Jays vs. Flying Tigers
END:VALARM
DTSTART:20180802T223000Z
DTEND:20180803T013000Z
UID:bBRjCAhM-wtRskWs5_nB43z4@stanza.co
SUMMARY:Blue Jays vs. Flying Tigers
DESCRIPTION:Blue Jays vs. Flying Tigers\n\nFollow on MiLB First Pitch: https://stza.co/+y0ID-3R\n\nShop: https://stza.co/+y0ID-E\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144520Z
LAST-MODIFIED:20180213T144520Z
TRANSP:OPAQUE
END:VEVENT
* Blue Jays vs. Stone Crabs
<2018-08-03 Fri 17:30-20:30>
:PROPERTIES:
:ID:       ZVWHkhY7YBb6ULmzCbkL_VH-@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Blue Jays vs. Stone Crabs Blue Jays vs. Stone Crabs

Follow on MiLB First Pitch  https //stza.co/+y0IF-13

Shop  https //stza.co/+y0IF-3s

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Blue Jays vs. Stone Crabs
END:VALARM
DTSTART:20180803T223000Z
DTEND:20180804T013000Z
UID:ZVWHkhY7YBb6ULmzCbkL_VH-@stanza.co
SUMMARY:Blue Jays vs. Stone Crabs
DESCRIPTION:Blue Jays vs. Stone Crabs\n\nFollow on MiLB First Pitch: https://stza.co/+y0IF-13\n\nShop: https://stza.co/+y0IF-3s\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144520Z
LAST-MODIFIED:20180213T144520Z
TRANSP:OPAQUE
END:VEVENT
* Blue Jays vs. Stone Crabs
<2018-08-04 Sat 17:30-20:30>
:PROPERTIES:
:ID:       OGrjnWqZQISOdEMtDoxd-O5m@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Blue Jays vs. Stone Crabs Blue Jays vs. Stone Crabs

Follow on MiLB First Pitch  https //stza.co/+y0IH-2N

Shop  https //stza.co/+y0IH-1y

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Blue Jays vs. Stone Crabs
END:VALARM
DTSTART:20180804T223000Z
DTEND:20180805T013000Z
UID:OGrjnWqZQISOdEMtDoxd-O5m@stanza.co
SUMMARY:Blue Jays vs. Stone Crabs
DESCRIPTION:Blue Jays vs. Stone Crabs\n\nFollow on MiLB First Pitch: https://stza.co/+y0IH-2N\n\nShop: https://stza.co/+y0IH-1y\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144520Z
LAST-MODIFIED:20180213T144520Z
TRANSP:OPAQUE
END:VEVENT
* Blue Jays vs. Stone Crabs
<2018-08-05 Sun 12:00-15:00>
:PROPERTIES:
:ID:       CF7JuUiRNp0ngh0TGGSRtwLG@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Blue Jays vs. Stone Crabs Blue Jays vs. Stone Crabs

Follow on MiLB First Pitch  https //stza.co/+y0IL-3E

Shop  https //stza.co/+y0IL-2q

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Blue Jays vs. Stone Crabs
END:VALARM
DTSTART:20180805T170000Z
DTEND:20180805T200000Z
UID:CF7JuUiRNp0ngh0TGGSRtwLG@stanza.co
SUMMARY:Blue Jays vs. Stone Crabs
DESCRIPTION:Blue Jays vs. Stone Crabs\n\nFollow on MiLB First Pitch: https://stza.co/+y0IL-3E\n\nShop: https://stza.co/+y0IL-2q\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144520Z
LAST-MODIFIED:20180213T144520Z
TRANSP:OPAQUE
END:VEVENT
* Blue Jays @ Tortugas
<2018-08-06 Mon 18:05-21:05>
:PROPERTIES:
:ID:       iDIZio9VGWxc1f7K3Io9V5bD@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Blue Jays @ Tortugas Blue Jays @ Tortugas

Follow on MiLB First Pitch  https //stza.co/+vMl3-5

Shop  https //stza.co/+vMl3-q

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Blue Jays @ Tortugas
END:VALARM
DTSTART:20180806T230500Z
DTEND:20180807T020500Z
UID:iDIZio9VGWxc1f7K3Io9V5bD@stanza.co
SUMMARY:Blue Jays @ Tortugas
DESCRIPTION:Blue Jays @ Tortugas\n\nFollow on MiLB First Pitch: https://stza.co/+vMl3-5\n\nShop: https://stza.co/+vMl3-q\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144520Z
LAST-MODIFIED:20180213T144520Z
TRANSP:OPAQUE
END:VEVENT
* Blue Jays @ Tortugas
<2018-08-07 Tue 18:05-21:05>
:PROPERTIES:
:ID:       IzJ9tZGClna438YZ71wFIDNU@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Blue Jays @ Tortugas Blue Jays @ Tortugas

Follow on MiLB First Pitch  https //stza.co/+vMl4-1z

Shop  https //stza.co/+vMl4-22

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Blue Jays @ Tortugas
END:VALARM
DTSTART:20180807T230500Z
DTEND:20180808T020500Z
UID:IzJ9tZGClna438YZ71wFIDNU@stanza.co
SUMMARY:Blue Jays @ Tortugas
DESCRIPTION:Blue Jays @ Tortugas\n\nFollow on MiLB First Pitch: https://stza.co/+vMl4-1z\n\nShop: https://stza.co/+vMl4-22\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144520Z
LAST-MODIFIED:20180213T144520Z
TRANSP:OPAQUE
END:VEVENT
* Blue Jays @ Tortugas
<2018-08-08 Wed 18:05-21:05>
:PROPERTIES:
:ID:       6HoXn09Q2zXr6ZbSgYb-mq4W@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Blue Jays @ Tortugas Blue Jays @ Tortugas

Follow on MiLB First Pitch  https //stza.co/+vMl5-11

Shop  https //stza.co/+vMl5-X

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Blue Jays @ Tortugas
END:VALARM
DTSTART:20180808T230500Z
DTEND:20180809T020500Z
UID:6HoXn09Q2zXr6ZbSgYb-mq4W@stanza.co
SUMMARY:Blue Jays @ Tortugas
DESCRIPTION:Blue Jays @ Tortugas\n\nFollow on MiLB First Pitch: https://stza.co/+vMl5-11\n\nShop: https://stza.co/+vMl5-X\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144520Z
LAST-MODIFIED:20180213T144520Z
TRANSP:OPAQUE
END:VEVENT
* Blue Jays @ Stone Crabs
<2018-08-09 Thu 17:35-20:35>
:PROPERTIES:
:ID:       c6WGgJcEBK-btZluWN_BpKuN@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Blue Jays @ Stone Crabs Blue Jays @ Stone Crabs

Follow on MiLB First Pitch  https //stza.co/+wYnc-b

Shop  https //stza.co/+wYnc-2T

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Blue Jays @ Stone Crabs
END:VALARM
DTSTART:20180809T223500Z
DTEND:20180810T013500Z
UID:c6WGgJcEBK-btZluWN_BpKuN@stanza.co
SUMMARY:Blue Jays @ Stone Crabs
DESCRIPTION:Blue Jays @ Stone Crabs\n\nFollow on MiLB First Pitch: https://stza.co/+wYnc-b\n\nShop: https://stza.co/+wYnc-2T\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144520Z
LAST-MODIFIED:20180213T144520Z
TRANSP:OPAQUE
END:VEVENT
* Blue Jays @ Stone Crabs
<2018-08-10 Fri 17:35-20:35>
:PROPERTIES:
:ID:       kYRmOOLCnFsrIlWxZEzOZj9d@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Blue Jays @ Stone Crabs Blue Jays @ Stone Crabs

Follow on MiLB First Pitch  https //stza.co/+wYnd-3P

Shop  https //stza.co/+wYnd-q

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Blue Jays @ Stone Crabs
END:VALARM
DTSTART:20180810T223500Z
DTEND:20180811T013500Z
UID:kYRmOOLCnFsrIlWxZEzOZj9d@stanza.co
SUMMARY:Blue Jays @ Stone Crabs
DESCRIPTION:Blue Jays @ Stone Crabs\n\nFollow on MiLB First Pitch: https://stza.co/+wYnd-3P\n\nShop: https://stza.co/+wYnd-q\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144520Z
LAST-MODIFIED:20180213T144520Z
TRANSP:OPAQUE
END:VEVENT
* Blue Jays @ Stone Crabs
<2018-08-11 Sat 17:05-20:05>
:PROPERTIES:
:ID:       I_PzUo-yRgeyugLTX38gx5A2@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Blue Jays @ Stone Crabs Blue Jays @ Stone Crabs

Follow on MiLB First Pitch  https //stza.co/+wYne-3W

Shop  https //stza.co/+wYne-11

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Blue Jays @ Stone Crabs
END:VALARM
DTSTART:20180811T220500Z
DTEND:20180812T010500Z
UID:I_PzUo-yRgeyugLTX38gx5A2@stanza.co
SUMMARY:Blue Jays @ Stone Crabs
DESCRIPTION:Blue Jays @ Stone Crabs\n\nFollow on MiLB First Pitch: https://stza.co/+wYne-3W\n\nShop: https://stza.co/+wYne-11\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144520Z
LAST-MODIFIED:20180213T144520Z
TRANSP:OPAQUE
END:VEVENT
* Blue Jays @ Stone Crabs
<2018-08-12 Sun 11:35-14:35>
:PROPERTIES:
:ID:       gHKmXheAmDB0Y9zkQEndDId2@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Blue Jays @ Stone Crabs Blue Jays @ Stone Crabs

Follow on MiLB First Pitch  https //stza.co/+wYnf-f

Shop  https //stza.co/+wYnf-Q

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Blue Jays @ Stone Crabs
END:VALARM
DTSTART:20180812T163500Z
DTEND:20180812T193500Z
UID:gHKmXheAmDB0Y9zkQEndDId2@stanza.co
SUMMARY:Blue Jays @ Stone Crabs
DESCRIPTION:Blue Jays @ Stone Crabs\n\nFollow on MiLB First Pitch: https://stza.co/+wYnf-f\n\nShop: https://stza.co/+wYnf-Q\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144520Z
LAST-MODIFIED:20180213T144520Z
TRANSP:OPAQUE
END:VEVENT
* Blue Jays vs. Hammerheads
<2018-08-13 Mon 17:30-20:30>
:PROPERTIES:
:ID:       3dHvdDBppLZeMjeuTtVasiyk@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Blue Jays vs. Hammerheads Blue Jays vs. Hammerheads

Follow on MiLB First Pitch  https //stza.co/+y0IN-2o

Shop  https //stza.co/+y0IN-u

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Blue Jays vs. Hammerheads
END:VALARM
DTSTART:20180813T223000Z
DTEND:20180814T013000Z
UID:3dHvdDBppLZeMjeuTtVasiyk@stanza.co
SUMMARY:Blue Jays vs. Hammerheads
DESCRIPTION:Blue Jays vs. Hammerheads\n\nFollow on MiLB First Pitch: https://stza.co/+y0IN-2o\n\nShop: https://stza.co/+y0IN-u\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144520Z
LAST-MODIFIED:20180213T144520Z
TRANSP:OPAQUE
END:VEVENT
* Blue Jays vs. Hammerheads
<2018-08-14 Tue 17:30-20:30>
:PROPERTIES:
:ID:       uxx0jsO_GcfZfAHUNDG6cYeR@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Blue Jays vs. Hammerheads Blue Jays vs. Hammerheads

Follow on MiLB First Pitch  https //stza.co/+y0IP-2p

Shop  https //stza.co/+y0IP-v

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Blue Jays vs. Hammerheads
END:VALARM
DTSTART:20180814T223000Z
DTEND:20180815T013000Z
UID:uxx0jsO_GcfZfAHUNDG6cYeR@stanza.co
SUMMARY:Blue Jays vs. Hammerheads
DESCRIPTION:Blue Jays vs. Hammerheads\n\nFollow on MiLB First Pitch: https://stza.co/+y0IP-2p\n\nShop: https://stza.co/+y0IP-v\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144520Z
LAST-MODIFIED:20180213T144520Z
TRANSP:OPAQUE
END:VEVENT
* Blue Jays vs. Hammerheads
<2018-08-15 Wed 17:30-20:30>
:PROPERTIES:
:ID:       _6ar21mrY-L918f7z3_KLKWa@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Blue Jays vs. Hammerheads Blue Jays vs. Hammerheads

Follow on MiLB First Pitch  https //stza.co/+y0IR-2s

Shop  https //stza.co/+y0IR-3g

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Blue Jays vs. Hammerheads
END:VALARM
DTSTART:20180815T223000Z
DTEND:20180816T013000Z
UID:_6ar21mrY-L918f7z3_KLKWa@stanza.co
SUMMARY:Blue Jays vs. Hammerheads
DESCRIPTION:Blue Jays vs. Hammerheads\n\nFollow on MiLB First Pitch: https://stza.co/+y0IR-2s\n\nShop: https://stza.co/+y0IR-3g\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144520Z
LAST-MODIFIED:20180213T144520Z
TRANSP:OPAQUE
END:VEVENT
* Blue Jays vs. Hammerheads
<2018-08-16 Thu 17:30-20:30>
:PROPERTIES:
:ID:       ZVxCy11tWziq8mWZhQ5Fyc1W@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Blue Jays vs. Hammerheads Blue Jays vs. Hammerheads

Follow on MiLB First Pitch  https //stza.co/+y0IT-3n

Shop  https //stza.co/+y0IT-1X

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Blue Jays vs. Hammerheads
END:VALARM
DTSTART:20180816T223000Z
DTEND:20180817T013000Z
UID:ZVxCy11tWziq8mWZhQ5Fyc1W@stanza.co
SUMMARY:Blue Jays vs. Hammerheads
DESCRIPTION:Blue Jays vs. Hammerheads\n\nFollow on MiLB First Pitch: https://stza.co/+y0IT-3n\n\nShop: https://stza.co/+y0IT-1X\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144520Z
LAST-MODIFIED:20180213T144520Z
TRANSP:OPAQUE
END:VEVENT
* Blue Jays vs. Mets
<2018-08-17 Fri 17:30-20:30>
:PROPERTIES:
:ID:       LGufbtM9ZUIBH9aqnIzuBuCd@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Blue Jays vs. Mets Blue Jays vs. Mets

Follow on MiLB First Pitch  https //stza.co/+y0IU-1G

Shop  https //stza.co/+y0IU-2p

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Blue Jays vs. Mets
END:VALARM
DTSTART:20180817T223000Z
DTEND:20180818T013000Z
UID:LGufbtM9ZUIBH9aqnIzuBuCd@stanza.co
SUMMARY:Blue Jays vs. Mets
DESCRIPTION:Blue Jays vs. Mets\n\nFollow on MiLB First Pitch: https://stza.co/+y0IU-1G\n\nShop: https://stza.co/+y0IU-2p\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144520Z
LAST-MODIFIED:20180213T144520Z
TRANSP:OPAQUE
END:VEVENT
* Blue Jays vs. Mets
<2018-08-18 Sat 17:30-20:30>
:PROPERTIES:
:ID:       IfSzx_zwle3R2XgAF3tV2G6l@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Blue Jays vs. Mets Blue Jays vs. Mets

Follow on MiLB First Pitch  https //stza.co/+y0IW-B

Shop  https //stza.co/+y0IW-3l

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Blue Jays vs. Mets
END:VALARM
DTSTART:20180818T223000Z
DTEND:20180819T013000Z
UID:IfSzx_zwle3R2XgAF3tV2G6l@stanza.co
SUMMARY:Blue Jays vs. Mets
DESCRIPTION:Blue Jays vs. Mets\n\nFollow on MiLB First Pitch: https://stza.co/+y0IW-B\n\nShop: https://stza.co/+y0IW-3l\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144520Z
LAST-MODIFIED:20180213T144520Z
TRANSP:OPAQUE
END:VEVENT
* Blue Jays vs. Mets
<2018-08-19 Sun 12:00-15:00>
:PROPERTIES:
:ID:       WbZBcVx1iFy2vLtdJ7TaGN6Q@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Blue Jays vs. Mets Blue Jays vs. Mets

Follow on MiLB First Pitch  https //stza.co/+y0IZ-28

Shop  https //stza.co/+y0IZ-11

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Blue Jays vs. Mets
END:VALARM
DTSTART:20180819T170000Z
DTEND:20180819T200000Z
UID:WbZBcVx1iFy2vLtdJ7TaGN6Q@stanza.co
SUMMARY:Blue Jays vs. Mets
DESCRIPTION:Blue Jays vs. Mets\n\nFollow on MiLB First Pitch: https://stza.co/+y0IZ-28\n\nShop: https://stza.co/+y0IZ-11\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144520Z
LAST-MODIFIED:20180213T144520Z
TRANSP:OPAQUE
END:VEVENT
* Blue Jays @ Threshers
<2018-08-21 Tue 18:00-21:00>
:PROPERTIES:
:ID:       S0ZPHKwatgYCnpSJp6VB4pjK@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Blue Jays @ Threshers Blue Jays @ Threshers

Follow on MiLB First Pitch  https //stza.co/+xBdz-3t

Shop  https //stza.co/+xBdz-3v

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Blue Jays @ Threshers
END:VALARM
DTSTART:20180821T230000Z
DTEND:20180822T020000Z
UID:S0ZPHKwatgYCnpSJp6VB4pjK@stanza.co
SUMMARY:Blue Jays @ Threshers
DESCRIPTION:Blue Jays @ Threshers\n\nFollow on MiLB First Pitch: https://stza.co/+xBdz-3t\n\nShop: https://stza.co/+xBdz-3v\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144520Z
LAST-MODIFIED:20180213T144520Z
TRANSP:OPAQUE
END:VEVENT
* Blue Jays @ Threshers
<2018-08-22 Wed 18:00-21:00>
:PROPERTIES:
:ID:       pthd7hoAHS2bHYLrbkJsm4l9@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Blue Jays @ Threshers Blue Jays @ Threshers

Follow on MiLB First Pitch  https //stza.co/+xBdA-36

Shop  https //stza.co/+xBdA-28

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Blue Jays @ Threshers
END:VALARM
DTSTART:20180822T230000Z
DTEND:20180823T020000Z
UID:pthd7hoAHS2bHYLrbkJsm4l9@stanza.co
SUMMARY:Blue Jays @ Threshers
DESCRIPTION:Blue Jays @ Threshers\n\nFollow on MiLB First Pitch: https://stza.co/+xBdA-36\n\nShop: https://stza.co/+xBdA-28\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144520Z
LAST-MODIFIED:20180213T144520Z
TRANSP:OPAQUE
END:VEVENT
* Blue Jays @ Threshers
<2018-08-23 Thu 18:00-21:00>
:PROPERTIES:
:ID:       N_2c4I9DWsGJHupWf25i_qiG@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Blue Jays @ Threshers Blue Jays @ Threshers

Follow on MiLB First Pitch  https //stza.co/+xBdB-2b

Shop  https //stza.co/+xBdB-2H

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Blue Jays @ Threshers
END:VALARM
DTSTART:20180823T230000Z
DTEND:20180824T020000Z
UID:N_2c4I9DWsGJHupWf25i_qiG@stanza.co
SUMMARY:Blue Jays @ Threshers
DESCRIPTION:Blue Jays @ Threshers\n\nFollow on MiLB First Pitch: https://stza.co/+xBdB-2b\n\nShop: https://stza.co/+xBdB-2H\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144520Z
LAST-MODIFIED:20180213T144520Z
TRANSP:OPAQUE
END:VEVENT
* Blue Jays @ Marauders
<2018-08-24 Fri 17:30-20:30>
:PROPERTIES:
:ID:       pBpKwN_QlHcl5OGZrvpf8HbL@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Blue Jays @ Marauders Blue Jays @ Marauders

Follow on MiLB First Pitch  https //stza.co/+vMkF-30

Shop  https //stza.co/+vMkF-2l

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Blue Jays @ Marauders
END:VALARM
DTSTART:20180824T223000Z
DTEND:20180825T013000Z
UID:pBpKwN_QlHcl5OGZrvpf8HbL@stanza.co
SUMMARY:Blue Jays @ Marauders
DESCRIPTION:Blue Jays @ Marauders\n\nFollow on MiLB First Pitch: https://stza.co/+vMkF-30\n\nShop: https://stza.co/+vMkF-2l\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144520Z
LAST-MODIFIED:20180213T144520Z
TRANSP:OPAQUE
END:VEVENT
* Blue Jays @ Marauders
<2018-08-25 Sat 17:30-20:30>
:PROPERTIES:
:ID:       JENZTDg95NMI9aGOd2oHJGO8@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Blue Jays @ Marauders Blue Jays @ Marauders

Follow on MiLB First Pitch  https //stza.co/+vMkG-3r

Shop  https //stza.co/+vMkG-2b

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Blue Jays @ Marauders
END:VALARM
DTSTART:20180825T223000Z
DTEND:20180826T013000Z
UID:JENZTDg95NMI9aGOd2oHJGO8@stanza.co
SUMMARY:Blue Jays @ Marauders
DESCRIPTION:Blue Jays @ Marauders\n\nFollow on MiLB First Pitch: https://stza.co/+vMkG-3r\n\nShop: https://stza.co/+vMkG-2b\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144520Z
LAST-MODIFIED:20180213T144520Z
TRANSP:OPAQUE
END:VEVENT
* Blue Jays @ Marauders
<2018-08-26 Sun 12:00-15:00>
:PROPERTIES:
:ID:       jaPiqBab4l80T6k7YmyMwKCT@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Blue Jays @ Marauders Blue Jays @ Marauders

Follow on MiLB First Pitch  https //stza.co/+vMkH-H

Shop  https //stza.co/+vMkH-2J

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Blue Jays @ Marauders
END:VALARM
DTSTART:20180826T170000Z
DTEND:20180826T200000Z
UID:jaPiqBab4l80T6k7YmyMwKCT@stanza.co
SUMMARY:Blue Jays @ Marauders
DESCRIPTION:Blue Jays @ Marauders\n\nFollow on MiLB First Pitch: https://stza.co/+vMkH-H\n\nShop: https://stza.co/+vMkH-2J\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144520Z
LAST-MODIFIED:20180213T144520Z
TRANSP:OPAQUE
END:VEVENT
* Blue Jays vs. Cardinals
<2018-08-27 Mon 17:30-20:30>
:PROPERTIES:
:ID:       ffQH1nJnuaHoTlkaX-mfZCxf@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Blue Jays vs. Cardinals Blue Jays vs. Cardinals

Follow on MiLB First Pitch  https //stza.co/+y0I_-t

Shop  https //stza.co/+y0I_-3r

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Blue Jays vs. Cardinals
END:VALARM
DTSTART:20180827T223000Z
DTEND:20180828T013000Z
UID:ffQH1nJnuaHoTlkaX-mfZCxf@stanza.co
SUMMARY:Blue Jays vs. Cardinals
DESCRIPTION:Blue Jays vs. Cardinals\n\nFollow on MiLB First Pitch: https://stza.co/+y0I_-t\n\nShop: https://stza.co/+y0I_-3r\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144520Z
LAST-MODIFIED:20180213T144520Z
TRANSP:OPAQUE
END:VEVENT
* Blue Jays vs. Cardinals
<2018-08-28 Tue 17:30-20:30>
:PROPERTIES:
:ID:       CpDsbxddX9WXE9H82UMCyvFB@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Blue Jays vs. Cardinals Blue Jays vs. Cardinals

Follow on MiLB First Pitch  https //stza.co/+y0J1-3Y

Shop  https //stza.co/+y0J1-3K

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Blue Jays vs. Cardinals
END:VALARM
DTSTART:20180828T223000Z
DTEND:20180829T013000Z
UID:CpDsbxddX9WXE9H82UMCyvFB@stanza.co
SUMMARY:Blue Jays vs. Cardinals
DESCRIPTION:Blue Jays vs. Cardinals\n\nFollow on MiLB First Pitch: https://stza.co/+y0J1-3Y\n\nShop: https://stza.co/+y0J1-3K\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144520Z
LAST-MODIFIED:20180213T144520Z
TRANSP:OPAQUE
END:VEVENT
* Blue Jays vs. Cardinals
<2018-08-29 Wed 17:30-20:30>
:PROPERTIES:
:ID:       3WX2Rzr8J2ZxOVZmz4aPteKQ@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Blue Jays vs. Cardinals Blue Jays vs. Cardinals

Follow on MiLB First Pitch  https //stza.co/+y0J2-3e

Shop  https //stza.co/+y0J2-g

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Blue Jays vs. Cardinals
END:VALARM
DTSTART:20180829T223000Z
DTEND:20180830T013000Z
UID:3WX2Rzr8J2ZxOVZmz4aPteKQ@stanza.co
SUMMARY:Blue Jays vs. Cardinals
DESCRIPTION:Blue Jays vs. Cardinals\n\nFollow on MiLB First Pitch: https://stza.co/+y0J2-3e\n\nShop: https://stza.co/+y0J2-g\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144520Z
LAST-MODIFIED:20180213T144520Z
TRANSP:OPAQUE
END:VEVENT
* Blue Jays vs. Cardinals
<2018-08-30 Thu 17:30-20:30>
:PROPERTIES:
:ID:       BKsSkkfxTrj3mT0aFb82Bktx@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Blue Jays vs. Cardinals Blue Jays vs. Cardinals

Follow on MiLB First Pitch  https //stza.co/+y0J5-3E

Shop  https //stza.co/+y0J5-2y

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Blue Jays vs. Cardinals
END:VALARM
DTSTART:20180830T223000Z
DTEND:20180831T013000Z
UID:BKsSkkfxTrj3mT0aFb82Bktx@stanza.co
SUMMARY:Blue Jays vs. Cardinals
DESCRIPTION:Blue Jays vs. Cardinals\n\nFollow on MiLB First Pitch: https://stza.co/+y0J5-3E\n\nShop: https://stza.co/+y0J5-2y\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144520Z
LAST-MODIFIED:20180213T144520Z
TRANSP:OPAQUE
END:VEVENT
* Blue Jays vs. Tortugas
<2018-08-31 Fri 17:30-20:30>
:PROPERTIES:
:ID:       qiuIxYGvt8fg9iFKR_VVy0Kd@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Blue Jays vs. Tortugas Blue Jays vs. Tortugas

Follow on MiLB First Pitch  https //stza.co/+y0J6-17

Shop  https //stza.co/+y0J6-2N

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Blue Jays vs. Tortugas
END:VALARM
DTSTART:20180831T223000Z
DTEND:20180901T013000Z
UID:qiuIxYGvt8fg9iFKR_VVy0Kd@stanza.co
SUMMARY:Blue Jays vs. Tortugas
DESCRIPTION:Blue Jays vs. Tortugas\n\nFollow on MiLB First Pitch: https://stza.co/+y0J6-17\n\nShop: https://stza.co/+y0J6-2N\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144520Z
LAST-MODIFIED:20180213T144520Z
TRANSP:OPAQUE
END:VEVENT
* Blue Jays vs. Tortugas
<2018-09-01 Sat 17:30-20:30>
:PROPERTIES:
:ID:       CnXMouMzRt59PLZvy776gbGb@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Blue Jays vs. Tortugas Blue Jays vs. Tortugas

Follow on MiLB First Pitch  https //stza.co/+y0Ja-2i

Shop  https //stza.co/+y0Ja-O

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Blue Jays vs. Tortugas
END:VALARM
DTSTART:20180901T223000Z
DTEND:20180902T013000Z
UID:CnXMouMzRt59PLZvy776gbGb@stanza.co
SUMMARY:Blue Jays vs. Tortugas
DESCRIPTION:Blue Jays vs. Tortugas\n\nFollow on MiLB First Pitch: https://stza.co/+y0Ja-2i\n\nShop: https://stza.co/+y0Ja-O\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144520Z
LAST-MODIFIED:20180213T144520Z
TRANSP:OPAQUE
END:VEVENT
* Blue Jays vs. Tortugas
<2018-09-02 Sun 11:00-14:00>
:PROPERTIES:
:ID:       sfVUQMd2yhfEohbhyU7vEQKF@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Blue Jays vs. Tortugas Blue Jays vs. Tortugas

Follow on MiLB First Pitch  https //stza.co/+y0Jb-9

Shop  https //stza.co/+y0Jb-1M

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Blue Jays vs. Tortugas
END:VALARM
DTSTART:20180902T160000Z
DTEND:20180902T190000Z
UID:sfVUQMd2yhfEohbhyU7vEQKF@stanza.co
SUMMARY:Blue Jays vs. Tortugas
DESCRIPTION:Blue Jays vs. Tortugas\n\nFollow on MiLB First Pitch: https://stza.co/+y0Jb-9\n\nShop: https://stza.co/+y0Jb-1M\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144520Z
LAST-MODIFIED:20180213T144520Z
TRANSP:OPAQUE
END:VEVENT
