#+TITLE:       Main Google calendar entries
#+AUTHOR:      Eric S Fraga
#+EMAIL:       e.fraga@ucl.ac.uk
#+DESCRIPTION: converted using the ical2org awk script
#+CATEGORY:    google
#+STARTUP:     hidestars
#+STARTUP:     overview

* COMMENT original iCal preamble

* Voyagers vs. Brewers
<2018-06-15 Fri>--<2018-06-14 Thu>
:PROPERTIES:
:ID:       1R-TKykgWSLmMtMWAMHAfVEl@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Voyagers vs. Brewers Voyagers vs. Brewers

Follow on MiLB First Pitch  https //stza.co/+xCsO-N

Shop  https //stza.co/+xCsO-3c

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Voyagers vs. Brewers
END:VALARM
DTSTART;VALUE=DATE:20180615
DTEND;VALUE=DATE:20180615
UID:1R-TKykgWSLmMtMWAMHAfVEl@stanza.co
SUMMARY:Voyagers vs. Brewers
DESCRIPTION:Voyagers vs. Brewers\n\nFollow on MiLB First Pitch: https://stza.co/+xCsO-N\n\nShop: https://stza.co/+xCsO-3c\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144528Z
LAST-MODIFIED:20180213T144528Z
TRANSP:OPAQUE
END:VEVENT
* Voyagers @ Brewers
<2018-06-16 Sat>--<2018-06-15 Fri>
:PROPERTIES:
:ID:       t7V7MqUVyoFMMG3AamyYn0e0@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Voyagers @ Brewers Voyagers @ Brewers

Follow on MiLB First Pitch  https //stza.co/+xCqy-31

Shop  https //stza.co/+xCqy-3_

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Voyagers @ Brewers
END:VALARM
DTSTART;VALUE=DATE:20180616
DTEND;VALUE=DATE:20180616
UID:t7V7MqUVyoFMMG3AamyYn0e0@stanza.co
SUMMARY:Voyagers @ Brewers
DESCRIPTION:Voyagers @ Brewers\n\nFollow on MiLB First Pitch: https://stza.co/+xCqy-31\n\nShop: https://stza.co/+xCqy-3_\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144528Z
LAST-MODIFIED:20180213T144528Z
TRANSP:OPAQUE
END:VEVENT
* Voyagers @ Brewers
<2018-06-17 Sun>--<2018-06-16 Sat>
:PROPERTIES:
:ID:       GNU0j0v_sWldXnvaK0sUM6WZ@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Voyagers @ Brewers Voyagers @ Brewers

Follow on MiLB First Pitch  https //stza.co/+xCqz-2$

Shop  https //stza.co/+xCqz-3D

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Voyagers @ Brewers
END:VALARM
DTSTART;VALUE=DATE:20180617
DTEND;VALUE=DATE:20180617
UID:GNU0j0v_sWldXnvaK0sUM6WZ@stanza.co
SUMMARY:Voyagers @ Brewers
DESCRIPTION:Voyagers @ Brewers\n\nFollow on MiLB First Pitch: https://stza.co/+xCqz-2$\n\nShop: https://stza.co/+xCqz-3D\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144528Z
LAST-MODIFIED:20180213T144528Z
TRANSP:OPAQUE
END:VEVENT
* Voyagers vs. Brewers
<2018-06-18 Mon>--<2018-06-17 Sun>
:PROPERTIES:
:ID:       -XyzlO5TCsvmyXjQ1ou7QpQu@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Voyagers vs. Brewers Voyagers vs. Brewers

Follow on MiLB First Pitch  https //stza.co/+xCsT-32

Shop  https //stza.co/+xCsT-28

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Voyagers vs. Brewers
END:VALARM
DTSTART;VALUE=DATE:20180618
DTEND;VALUE=DATE:20180618
UID:-XyzlO5TCsvmyXjQ1ou7QpQu@stanza.co
SUMMARY:Voyagers vs. Brewers
DESCRIPTION:Voyagers vs. Brewers\n\nFollow on MiLB First Pitch: https://stza.co/+xCsT-32\n\nShop: https://stza.co/+xCsT-28\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144528Z
LAST-MODIFIED:20180213T144528Z
TRANSP:OPAQUE
END:VEVENT
* Voyagers vs. Mustangs
<2018-06-19 Tue>--<2018-06-18 Mon>
:PROPERTIES:
:ID:       yGCJAXmr1BAAZFBgrpnshdlX@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Voyagers vs. Mustangs Voyagers vs. Mustangs

Follow on MiLB First Pitch  https //stza.co/+xCsX-q

Shop  https //stza.co/+xCsX-1n

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Voyagers vs. Mustangs
END:VALARM
DTSTART;VALUE=DATE:20180619
DTEND;VALUE=DATE:20180619
UID:yGCJAXmr1BAAZFBgrpnshdlX@stanza.co
SUMMARY:Voyagers vs. Mustangs
DESCRIPTION:Voyagers vs. Mustangs\n\nFollow on MiLB First Pitch: https://stza.co/+xCsX-q\n\nShop: https://stza.co/+xCsX-1n\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144528Z
LAST-MODIFIED:20180213T144528Z
TRANSP:OPAQUE
END:VEVENT
* Voyagers vs. Mustangs
<2018-06-20 Wed>--<2018-06-19 Tue>
:PROPERTIES:
:ID:       3bMYvzCID4hb_izPGWBxSmbF@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Voyagers vs. Mustangs Voyagers vs. Mustangs

Follow on MiLB First Pitch  https //stza.co/+xCt0-2i

Shop  https //stza.co/+xCt0-G

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Voyagers vs. Mustangs
END:VALARM
DTSTART;VALUE=DATE:20180620
DTEND;VALUE=DATE:20180620
UID:3bMYvzCID4hb_izPGWBxSmbF@stanza.co
SUMMARY:Voyagers vs. Mustangs
DESCRIPTION:Voyagers vs. Mustangs\n\nFollow on MiLB First Pitch: https://stza.co/+xCt0-2i\n\nShop: https://stza.co/+xCt0-G\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144528Z
LAST-MODIFIED:20180213T144528Z
TRANSP:OPAQUE
END:VEVENT
* Voyagers vs. Mustangs
<2018-06-21 Thu>--<2018-06-20 Wed>
:PROPERTIES:
:ID:       8V1yWRqOCEH7FlCaIB7TEXnp@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Voyagers vs. Mustangs Voyagers vs. Mustangs

Follow on MiLB First Pitch  https //stza.co/+xCt4-E

Shop  https //stza.co/+xCt4-F

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Voyagers vs. Mustangs
END:VALARM
DTSTART;VALUE=DATE:20180621
DTEND;VALUE=DATE:20180621
UID:8V1yWRqOCEH7FlCaIB7TEXnp@stanza.co
SUMMARY:Voyagers vs. Mustangs
DESCRIPTION:Voyagers vs. Mustangs\n\nFollow on MiLB First Pitch: https://stza.co/+xCt4-E\n\nShop: https://stza.co/+xCt4-F\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144528Z
LAST-MODIFIED:20180213T144528Z
TRANSP:OPAQUE
END:VEVENT
* Voyagers @ Osprey
<2018-06-22 Fri>--<2018-06-21 Thu>
:PROPERTIES:
:ID:       Hk_OuMyTlXXvNGmcvhNhEZsJ@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Voyagers @ Osprey Voyagers @ Osprey

Follow on MiLB First Pitch  https //stza.co/+xCs4-3G

Shop  https //stza.co/+xCs4-x

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Voyagers @ Osprey
END:VALARM
DTSTART;VALUE=DATE:20180622
DTEND;VALUE=DATE:20180622
UID:Hk_OuMyTlXXvNGmcvhNhEZsJ@stanza.co
SUMMARY:Voyagers @ Osprey
DESCRIPTION:Voyagers @ Osprey\n\nFollow on MiLB First Pitch: https://stza.co/+xCs4-3G\n\nShop: https://stza.co/+xCs4-x\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144528Z
LAST-MODIFIED:20180213T144528Z
TRANSP:OPAQUE
END:VEVENT
* Voyagers @ Osprey
<2018-06-23 Sat>--<2018-06-22 Fri>
:PROPERTIES:
:ID:       HFS8khmKHGsXOOUpInLuhZg3@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Voyagers @ Osprey Voyagers @ Osprey

Follow on MiLB First Pitch  https //stza.co/+xCsb-z

Shop  https //stza.co/+xCsb-2N

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Voyagers @ Osprey
END:VALARM
DTSTART;VALUE=DATE:20180623
DTEND;VALUE=DATE:20180623
UID:HFS8khmKHGsXOOUpInLuhZg3@stanza.co
SUMMARY:Voyagers @ Osprey
DESCRIPTION:Voyagers @ Osprey\n\nFollow on MiLB First Pitch: https://stza.co/+xCsb-z\n\nShop: https://stza.co/+xCsb-2N\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144528Z
LAST-MODIFIED:20180213T144528Z
TRANSP:OPAQUE
END:VEVENT
* Voyagers @ Osprey
<2018-06-24 Sun>--<2018-06-23 Sat>
:PROPERTIES:
:ID:       8UC-0gQOTbaZXXtTaEUuMlA3@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Voyagers @ Osprey Voyagers @ Osprey

Follow on MiLB First Pitch  https //stza.co/+xCsd-3

Shop  https //stza.co/+xCsd-1v

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Voyagers @ Osprey
END:VALARM
DTSTART;VALUE=DATE:20180624
DTEND;VALUE=DATE:20180624
UID:8UC-0gQOTbaZXXtTaEUuMlA3@stanza.co
SUMMARY:Voyagers @ Osprey
DESCRIPTION:Voyagers @ Osprey\n\nFollow on MiLB First Pitch: https://stza.co/+xCsd-3\n\nShop: https://stza.co/+xCsd-1v\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144528Z
LAST-MODIFIED:20180213T144528Z
TRANSP:OPAQUE
END:VEVENT
* Voyagers @ Mustangs
<2018-06-25 Mon 20:05-23:05>
:PROPERTIES:
:ID:       n4l5I6LHUzO8MhD-uZFr_e0h@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Voyagers @ Mustangs Voyagers @ Mustangs

Follow on MiLB First Pitch  https //stza.co/+xSOu-3z

Shop  https //stza.co/+xSOu-2x

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Voyagers @ Mustangs
END:VALARM
DTSTART:20180626T010500Z
DTEND:20180626T040500Z
UID:n4l5I6LHUzO8MhD-uZFr_e0h@stanza.co
SUMMARY:Voyagers @ Mustangs
DESCRIPTION:Voyagers @ Mustangs\n\nFollow on MiLB First Pitch: https://stza.co/+xSOu-3z\n\nShop: https://stza.co/+xSOu-2x\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144528Z
LAST-MODIFIED:20180213T144528Z
TRANSP:OPAQUE
END:VEVENT
* Voyagers @ Mustangs
<2018-06-26 Tue 20:05-23:05>
:PROPERTIES:
:ID:       ZsJqdREPv9fInAHI-dDipeEK@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Voyagers @ Mustangs Voyagers @ Mustangs

Follow on MiLB First Pitch  https //stza.co/+xSOv-y

Shop  https //stza.co/+xSOv-1W

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Voyagers @ Mustangs
END:VALARM
DTSTART:20180627T010500Z
DTEND:20180627T040500Z
UID:ZsJqdREPv9fInAHI-dDipeEK@stanza.co
SUMMARY:Voyagers @ Mustangs
DESCRIPTION:Voyagers @ Mustangs\n\nFollow on MiLB First Pitch: https://stza.co/+xSOv-y\n\nShop: https://stza.co/+xSOv-1W\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144528Z
LAST-MODIFIED:20180213T144528Z
TRANSP:OPAQUE
END:VEVENT
* Voyagers @ Mustangs
<2018-06-27 Wed 20:05-23:05>
:PROPERTIES:
:ID:       ThA669GtVWZJo2H13s-NX39v@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Voyagers @ Mustangs Voyagers @ Mustangs

Follow on MiLB First Pitch  https //stza.co/+xSOw-3l

Shop  https //stza.co/+xSOw-1c

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Voyagers @ Mustangs
END:VALARM
DTSTART:20180628T010500Z
DTEND:20180628T040500Z
UID:ThA669GtVWZJo2H13s-NX39v@stanza.co
SUMMARY:Voyagers @ Mustangs
DESCRIPTION:Voyagers @ Mustangs\n\nFollow on MiLB First Pitch: https://stza.co/+xSOw-3l\n\nShop: https://stza.co/+xSOw-1c\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144528Z
LAST-MODIFIED:20180213T144528Z
TRANSP:OPAQUE
END:VEVENT
* Voyagers vs. Osprey
<2018-06-28 Thu>--<2018-06-27 Wed>
:PROPERTIES:
:ID:       vLxyuZF9lkrHeFBi2OTn9fug@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Voyagers vs. Osprey Voyagers vs. Osprey

Follow on MiLB First Pitch  https //stza.co/+xCt9-1F

Shop  https //stza.co/+xCt9-2L

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Voyagers vs. Osprey
END:VALARM
DTSTART;VALUE=DATE:20180628
DTEND;VALUE=DATE:20180628
UID:vLxyuZF9lkrHeFBi2OTn9fug@stanza.co
SUMMARY:Voyagers vs. Osprey
DESCRIPTION:Voyagers vs. Osprey\n\nFollow on MiLB First Pitch: https://stza.co/+xCt9-1F\n\nShop: https://stza.co/+xCt9-2L\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144528Z
LAST-MODIFIED:20180213T144528Z
TRANSP:OPAQUE
END:VEVENT
* Voyagers vs. Osprey
<2018-06-29 Fri>--<2018-06-28 Thu>
:PROPERTIES:
:ID:       LE3PMb6iT6cye_hwZQJJL-_R@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Voyagers vs. Osprey Voyagers vs. Osprey

Follow on MiLB First Pitch  https //stza.co/+xCtc-3I

Shop  https //stza.co/+xCtc-3o

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Voyagers vs. Osprey
END:VALARM
DTSTART;VALUE=DATE:20180629
DTEND;VALUE=DATE:20180629
UID:LE3PMb6iT6cye_hwZQJJL-_R@stanza.co
SUMMARY:Voyagers vs. Osprey
DESCRIPTION:Voyagers vs. Osprey\n\nFollow on MiLB First Pitch: https://stza.co/+xCtc-3I\n\nShop: https://stza.co/+xCtc-3o\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144528Z
LAST-MODIFIED:20180213T144528Z
TRANSP:OPAQUE
END:VEVENT
* Voyagers vs. Brewers
<2018-06-30 Sat>--<2018-06-29 Fri>
:PROPERTIES:
:ID:       WQckM1F7zmnAxEqRPDCJ1H1t@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Voyagers vs. Brewers Voyagers vs. Brewers

Follow on MiLB First Pitch  https //stza.co/+xCtf-3p

Shop  https //stza.co/+xCtf-3a

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Voyagers vs. Brewers
END:VALARM
DTSTART;VALUE=DATE:20180630
DTEND;VALUE=DATE:20180630
UID:WQckM1F7zmnAxEqRPDCJ1H1t@stanza.co
SUMMARY:Voyagers vs. Brewers
DESCRIPTION:Voyagers vs. Brewers\n\nFollow on MiLB First Pitch: https://stza.co/+xCtf-3p\n\nShop: https://stza.co/+xCtf-3a\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144528Z
LAST-MODIFIED:20180213T144528Z
TRANSP:OPAQUE
END:VEVENT
* Voyagers vs. Brewers
<2018-07-01 Sun>--<2018-06-30 Sat>
:PROPERTIES:
:ID:       rGRJcaiZj_k-ZjvRcPDLX-ga@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Voyagers vs. Brewers Voyagers vs. Brewers

Follow on MiLB First Pitch  https //stza.co/+xCtj-Q

Shop  https //stza.co/+xCtj-16

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Voyagers vs. Brewers
END:VALARM
DTSTART;VALUE=DATE:20180701
DTEND;VALUE=DATE:20180701
UID:rGRJcaiZj_k-ZjvRcPDLX-ga@stanza.co
SUMMARY:Voyagers vs. Brewers
DESCRIPTION:Voyagers vs. Brewers\n\nFollow on MiLB First Pitch: https://stza.co/+xCtj-Q\n\nShop: https://stza.co/+xCtj-16\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144528Z
LAST-MODIFIED:20180213T144528Z
TRANSP:OPAQUE
END:VEVENT
* Voyagers @ Brewers
<2018-07-02 Mon>--<2018-07-01 Sun>
:PROPERTIES:
:ID:       uXtNa8pCMiLWkh3CMSARSkOh@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Voyagers @ Brewers Voyagers @ Brewers

Follow on MiLB First Pitch  https //stza.co/+xCqE-f

Shop  https //stza.co/+xCqE-2P

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Voyagers @ Brewers
END:VALARM
DTSTART;VALUE=DATE:20180702
DTEND;VALUE=DATE:20180702
UID:uXtNa8pCMiLWkh3CMSARSkOh@stanza.co
SUMMARY:Voyagers @ Brewers
DESCRIPTION:Voyagers @ Brewers\n\nFollow on MiLB First Pitch: https://stza.co/+xCqE-f\n\nShop: https://stza.co/+xCqE-2P\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144528Z
LAST-MODIFIED:20180213T144528Z
TRANSP:OPAQUE
END:VEVENT
* Voyagers @ Brewers
<2018-07-03 Tue>--<2018-07-02 Mon>
:PROPERTIES:
:ID:       tgl-DdbYxBWrdgrMqr4r0igq@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Voyagers @ Brewers Voyagers @ Brewers

Follow on MiLB First Pitch  https //stza.co/+xCqH-c

Shop  https //stza.co/+xCqH-3b

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Voyagers @ Brewers
END:VALARM
DTSTART;VALUE=DATE:20180703
DTEND;VALUE=DATE:20180703
UID:tgl-DdbYxBWrdgrMqr4r0igq@stanza.co
SUMMARY:Voyagers @ Brewers
DESCRIPTION:Voyagers @ Brewers\n\nFollow on MiLB First Pitch: https://stza.co/+xCqH-c\n\nShop: https://stza.co/+xCqH-3b\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144528Z
LAST-MODIFIED:20180213T144528Z
TRANSP:OPAQUE
END:VEVENT
* Voyagers vs. Osprey
<2018-07-04 Wed>--<2018-07-03 Tue>
:PROPERTIES:
:ID:       6vG0adHrwc54Pc1XqaapihKu@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Voyagers vs. Osprey Voyagers vs. Osprey

Follow on MiLB First Pitch  https //stza.co/+xCto-D

Shop  https //stza.co/+xCto-1I

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Voyagers vs. Osprey
END:VALARM
DTSTART;VALUE=DATE:20180704
DTEND;VALUE=DATE:20180704
UID:6vG0adHrwc54Pc1XqaapihKu@stanza.co
SUMMARY:Voyagers vs. Osprey
DESCRIPTION:Voyagers vs. Osprey\n\nFollow on MiLB First Pitch: https://stza.co/+xCto-D\n\nShop: https://stza.co/+xCto-1I\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144528Z
LAST-MODIFIED:20180213T144528Z
TRANSP:OPAQUE
END:VEVENT
* Voyagers vs. Osprey
<2018-07-05 Thu>--<2018-07-04 Wed>
:PROPERTIES:
:ID:       v9brNgjxKALLAfdWorxJP_S6@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Voyagers vs. Osprey Voyagers vs. Osprey

Follow on MiLB First Pitch  https //stza.co/+xCts-12

Shop  https //stza.co/+xCts-18

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Voyagers vs. Osprey
END:VALARM
DTSTART;VALUE=DATE:20180705
DTEND;VALUE=DATE:20180705
UID:v9brNgjxKALLAfdWorxJP_S6@stanza.co
SUMMARY:Voyagers vs. Osprey
DESCRIPTION:Voyagers vs. Osprey\n\nFollow on MiLB First Pitch: https://stza.co/+xCts-12\n\nShop: https://stza.co/+xCts-18\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144528Z
LAST-MODIFIED:20180213T144528Z
TRANSP:OPAQUE
END:VEVENT
* Voyagers vs. Osprey
<2018-07-06 Fri>--<2018-07-05 Thu>
:PROPERTIES:
:ID:       YtlT7HzzKvLXf8RA8BELGZ_5@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Voyagers vs. Osprey Voyagers vs. Osprey

Follow on MiLB First Pitch  https //stza.co/+xCtw-3S

Shop  https //stza.co/+xCtw-O

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Voyagers vs. Osprey
END:VALARM
DTSTART;VALUE=DATE:20180706
DTEND;VALUE=DATE:20180706
UID:YtlT7HzzKvLXf8RA8BELGZ_5@stanza.co
SUMMARY:Voyagers vs. Osprey
DESCRIPTION:Voyagers vs. Osprey\n\nFollow on MiLB First Pitch: https://stza.co/+xCtw-3S\n\nShop: https://stza.co/+xCtw-O\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144528Z
LAST-MODIFIED:20180213T144528Z
TRANSP:OPAQUE
END:VEVENT
* Voyagers @ Osprey
<2018-07-07 Sat>--<2018-07-06 Fri>
:PROPERTIES:
:ID:       2ZpZiTjKx_pH2pybPBExYZyR@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Voyagers @ Osprey Voyagers @ Osprey

Follow on MiLB First Pitch  https //stza.co/+xCsg-1h

Shop  https //stza.co/+xCsg-1Q

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Voyagers @ Osprey
END:VALARM
DTSTART;VALUE=DATE:20180707
DTEND;VALUE=DATE:20180707
UID:2ZpZiTjKx_pH2pybPBExYZyR@stanza.co
SUMMARY:Voyagers @ Osprey
DESCRIPTION:Voyagers @ Osprey\n\nFollow on MiLB First Pitch: https://stza.co/+xCsg-1h\n\nShop: https://stza.co/+xCsg-1Q\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144528Z
LAST-MODIFIED:20180213T144528Z
TRANSP:OPAQUE
END:VEVENT
* Voyagers @ Osprey
<2018-07-08 Sun>--<2018-07-07 Sat>
:PROPERTIES:
:ID:       s-fS6JDYf17cYzFAamhkMAQz@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Voyagers @ Osprey Voyagers @ Osprey

Follow on MiLB First Pitch  https //stza.co/+xCsi-3f

Shop  https //stza.co/+xCsi-2p

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Voyagers @ Osprey
END:VALARM
DTSTART;VALUE=DATE:20180708
DTEND;VALUE=DATE:20180708
UID:s-fS6JDYf17cYzFAamhkMAQz@stanza.co
SUMMARY:Voyagers @ Osprey
DESCRIPTION:Voyagers @ Osprey\n\nFollow on MiLB First Pitch: https://stza.co/+xCsi-3f\n\nShop: https://stza.co/+xCsi-2p\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144528Z
LAST-MODIFIED:20180213T144528Z
TRANSP:OPAQUE
END:VEVENT
* Voyagers vs. Owlz
<2018-07-10 Tue>--<2018-07-09 Mon>
:PROPERTIES:
:ID:       1iUAlpVBo1fy3r88qX_hFbwK@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Voyagers vs. Owlz Voyagers vs. Owlz

Follow on MiLB First Pitch  https //stza.co/+xCtA-1t

Shop  https //stza.co/+xCtA-1I

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Voyagers vs. Owlz
END:VALARM
DTSTART;VALUE=DATE:20180710
DTEND;VALUE=DATE:20180710
UID:1iUAlpVBo1fy3r88qX_hFbwK@stanza.co
SUMMARY:Voyagers vs. Owlz
DESCRIPTION:Voyagers vs. Owlz\n\nFollow on MiLB First Pitch: https://stza.co/+xCtA-1t\n\nShop: https://stza.co/+xCtA-1I\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144528Z
LAST-MODIFIED:20180213T144528Z
TRANSP:OPAQUE
END:VEVENT
* Voyagers vs. Owlz
<2018-07-11 Wed>--<2018-07-10 Tue>
:PROPERTIES:
:ID:       gXFHm2LnVqazqamzTi3eDy3g@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Voyagers vs. Owlz Voyagers vs. Owlz

Follow on MiLB First Pitch  https //stza.co/+xCtG-6

Shop  https //stza.co/+xCtG-1m

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Voyagers vs. Owlz
END:VALARM
DTSTART;VALUE=DATE:20180711
DTEND;VALUE=DATE:20180711
UID:gXFHm2LnVqazqamzTi3eDy3g@stanza.co
SUMMARY:Voyagers vs. Owlz
DESCRIPTION:Voyagers vs. Owlz\n\nFollow on MiLB First Pitch: https://stza.co/+xCtG-6\n\nShop: https://stza.co/+xCtG-1m\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144528Z
LAST-MODIFIED:20180213T144528Z
TRANSP:OPAQUE
END:VEVENT
* Voyagers vs. Owlz
<2018-07-12 Thu>--<2018-07-11 Wed>
:PROPERTIES:
:ID:       xxqKuDjix9pVsPXFTs4QRVyk@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Voyagers vs. Owlz Voyagers vs. Owlz

Follow on MiLB First Pitch  https //stza.co/+xCtJ-2p

Shop  https //stza.co/+xCtJ-1y

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Voyagers vs. Owlz
END:VALARM
DTSTART;VALUE=DATE:20180712
DTEND;VALUE=DATE:20180712
UID:xxqKuDjix9pVsPXFTs4QRVyk@stanza.co
SUMMARY:Voyagers vs. Owlz
DESCRIPTION:Voyagers vs. Owlz\n\nFollow on MiLB First Pitch: https://stza.co/+xCtJ-2p\n\nShop: https://stza.co/+xCtJ-1y\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144528Z
LAST-MODIFIED:20180213T144528Z
TRANSP:OPAQUE
END:VEVENT
* Voyagers vs. Owlz
<2018-07-13 Fri>--<2018-07-12 Thu>
:PROPERTIES:
:ID:       oYFE9kYiL6LbXrbzjygRmw2b@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Voyagers vs. Owlz Voyagers vs. Owlz

Follow on MiLB First Pitch  https //stza.co/+xCtO-1b

Shop  https //stza.co/+xCtO-2G

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Voyagers vs. Owlz
END:VALARM
DTSTART;VALUE=DATE:20180713
DTEND;VALUE=DATE:20180713
UID:oYFE9kYiL6LbXrbzjygRmw2b@stanza.co
SUMMARY:Voyagers vs. Owlz
DESCRIPTION:Voyagers vs. Owlz\n\nFollow on MiLB First Pitch: https://stza.co/+xCtO-1b\n\nShop: https://stza.co/+xCtO-2G\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144528Z
LAST-MODIFIED:20180213T144528Z
TRANSP:OPAQUE
END:VEVENT
* Voyagers vs. Rockies
<2018-07-14 Sat>--<2018-07-13 Fri>
:PROPERTIES:
:ID:       9BM7cpimlgxFahVQ6QiUQm3v@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Voyagers vs. Rockies Voyagers vs. Rockies

Follow on MiLB First Pitch  https //stza.co/+xCtR-36

Shop  https //stza.co/+xCtR-2e

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Voyagers vs. Rockies
END:VALARM
DTSTART;VALUE=DATE:20180714
DTEND;VALUE=DATE:20180714
UID:9BM7cpimlgxFahVQ6QiUQm3v@stanza.co
SUMMARY:Voyagers vs. Rockies
DESCRIPTION:Voyagers vs. Rockies\n\nFollow on MiLB First Pitch: https://stza.co/+xCtR-36\n\nShop: https://stza.co/+xCtR-2e\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144528Z
LAST-MODIFIED:20180213T144528Z
TRANSP:OPAQUE
END:VEVENT
* Voyagers vs. Rockies
<2018-07-15 Sun>--<2018-07-14 Sat>
:PROPERTIES:
:ID:       XNjmbtkfnyGA1NZsz8RIhg2M@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Voyagers vs. Rockies Voyagers vs. Rockies

Follow on MiLB First Pitch  https //stza.co/+xCtU-2T

Shop  https //stza.co/+xCtU-C

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Voyagers vs. Rockies
END:VALARM
DTSTART;VALUE=DATE:20180715
DTEND;VALUE=DATE:20180715
UID:XNjmbtkfnyGA1NZsz8RIhg2M@stanza.co
SUMMARY:Voyagers vs. Rockies
DESCRIPTION:Voyagers vs. Rockies\n\nFollow on MiLB First Pitch: https://stza.co/+xCtU-2T\n\nShop: https://stza.co/+xCtU-C\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144528Z
LAST-MODIFIED:20180213T144528Z
TRANSP:OPAQUE
END:VEVENT
* Voyagers vs. Rockies
<2018-07-16 Mon>--<2018-07-15 Sun>
:PROPERTIES:
:ID:       mUErP_YV4p_cUmIr8VqT_IKI@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Voyagers vs. Rockies Voyagers vs. Rockies

Follow on MiLB First Pitch  https //stza.co/+xCt_-16

Shop  https //stza.co/+xCt_-3o

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Voyagers vs. Rockies
END:VALARM
DTSTART;VALUE=DATE:20180716
DTEND;VALUE=DATE:20180716
UID:mUErP_YV4p_cUmIr8VqT_IKI@stanza.co
SUMMARY:Voyagers vs. Rockies
DESCRIPTION:Voyagers vs. Rockies\n\nFollow on MiLB First Pitch: https://stza.co/+xCt_-16\n\nShop: https://stza.co/+xCt_-3o\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144528Z
LAST-MODIFIED:20180213T144528Z
TRANSP:OPAQUE
END:VEVENT
* Voyagers @ Owlz
<2018-07-18 Wed 20:05-23:05>
:PROPERTIES:
:ID:       6J7djl2alFjGhsCXFqSwW6r8@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Voyagers @ Owlz Voyagers @ Owlz

Follow on MiLB First Pitch  https //stza.co/+xPBc-2g

Shop  https //stza.co/+xPBc-a

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Voyagers @ Owlz
END:VALARM
DTSTART:20180719T010500Z
DTEND:20180719T040500Z
UID:6J7djl2alFjGhsCXFqSwW6r8@stanza.co
SUMMARY:Voyagers @ Owlz
DESCRIPTION:Voyagers @ Owlz\n\nFollow on MiLB First Pitch: https://stza.co/+xPBc-2g\n\nShop: https://stza.co/+xPBc-a\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144528Z
LAST-MODIFIED:20180213T144528Z
TRANSP:OPAQUE
END:VEVENT
* Voyagers @ Owlz
<2018-07-19 Thu 20:05-23:05>
:PROPERTIES:
:ID:       HUOagqKR2YCUAq8JLl6AQbgk@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Voyagers @ Owlz Voyagers @ Owlz

Follow on MiLB First Pitch  https //stza.co/+xPBd-U

Shop  https //stza.co/+xPBd-R

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Voyagers @ Owlz
END:VALARM
DTSTART:20180720T010500Z
DTEND:20180720T040500Z
UID:HUOagqKR2YCUAq8JLl6AQbgk@stanza.co
SUMMARY:Voyagers @ Owlz
DESCRIPTION:Voyagers @ Owlz\n\nFollow on MiLB First Pitch: https://stza.co/+xPBd-U\n\nShop: https://stza.co/+xPBd-R\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144528Z
LAST-MODIFIED:20180213T144528Z
TRANSP:OPAQUE
END:VEVENT
* Voyagers @ Owlz
<2018-07-20 Fri 20:05-23:05>
:PROPERTIES:
:ID:       w-miisaeGm54ng3KN_6glO3k@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Voyagers @ Owlz Voyagers @ Owlz

Follow on MiLB First Pitch  https //stza.co/+xPBe-13

Shop  https //stza.co/+xPBe-3u

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Voyagers @ Owlz
END:VALARM
DTSTART:20180721T010500Z
DTEND:20180721T040500Z
UID:w-miisaeGm54ng3KN_6glO3k@stanza.co
SUMMARY:Voyagers @ Owlz
DESCRIPTION:Voyagers @ Owlz\n\nFollow on MiLB First Pitch: https://stza.co/+xPBe-13\n\nShop: https://stza.co/+xPBe-3u\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144528Z
LAST-MODIFIED:20180213T144528Z
TRANSP:OPAQUE
END:VEVENT
* Voyagers @ Rockies
<2018-07-21 Sat 19:40-22:40>
:PROPERTIES:
:ID:       fQFwSkgcz8I94w3Nr4dpXwE7@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Voyagers @ Rockies Voyagers @ Rockies

Follow on MiLB First Pitch  https //stza.co/+xJ84-3f

Shop  https //stza.co/+xJ84-3Z

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Voyagers @ Rockies
END:VALARM
DTSTART:20180722T004000Z
DTEND:20180722T034000Z
UID:fQFwSkgcz8I94w3Nr4dpXwE7@stanza.co
SUMMARY:Voyagers @ Rockies
DESCRIPTION:Voyagers @ Rockies\n\nFollow on MiLB First Pitch: https://stza.co/+xJ84-3f\n\nShop: https://stza.co/+xJ84-3Z\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144528Z
LAST-MODIFIED:20180213T144528Z
TRANSP:OPAQUE
END:VEVENT
* Voyagers @ Rockies
<2018-07-22 Sun 18:00-21:00>
:PROPERTIES:
:ID:       X3xeP3jQSmqFPfUMZMo_DBcf@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Voyagers @ Rockies Voyagers @ Rockies

Follow on MiLB First Pitch  https //stza.co/+xJ85-I

Shop  https //stza.co/+xJ85-g

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Voyagers @ Rockies
END:VALARM
DTSTART:20180722T230000Z
DTEND:20180723T020000Z
UID:X3xeP3jQSmqFPfUMZMo_DBcf@stanza.co
SUMMARY:Voyagers @ Rockies
DESCRIPTION:Voyagers @ Rockies\n\nFollow on MiLB First Pitch: https://stza.co/+xJ85-I\n\nShop: https://stza.co/+xJ85-g\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144528Z
LAST-MODIFIED:20180213T144528Z
TRANSP:OPAQUE
END:VEVENT
* Voyagers @ Rockies
<2018-07-23 Mon 19:40-22:40>
:PROPERTIES:
:ID:       h3Np1z-DF6gdnSWjFT_LezZ-@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Voyagers @ Rockies Voyagers @ Rockies

Follow on MiLB First Pitch  https //stza.co/+xJ86-2K

Shop  https //stza.co/+xJ86-2x

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Voyagers @ Rockies
END:VALARM
DTSTART:20180724T004000Z
DTEND:20180724T034000Z
UID:h3Np1z-DF6gdnSWjFT_LezZ-@stanza.co
SUMMARY:Voyagers @ Rockies
DESCRIPTION:Voyagers @ Rockies\n\nFollow on MiLB First Pitch: https://stza.co/+xJ86-2K\n\nShop: https://stza.co/+xJ86-2x\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144528Z
LAST-MODIFIED:20180213T144528Z
TRANSP:OPAQUE
END:VEVENT
* Voyagers @ Rockies
<2018-07-24 Tue 19:40-22:40>
:PROPERTIES:
:ID:       HegQlH4kkR_OPkpM_1CHsNya@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Voyagers @ Rockies Voyagers @ Rockies

Follow on MiLB First Pitch  https //stza.co/+xJ87-j

Shop  https //stza.co/+xJ87-3O

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Voyagers @ Rockies
END:VALARM
DTSTART:20180725T004000Z
DTEND:20180725T034000Z
UID:HegQlH4kkR_OPkpM_1CHsNya@stanza.co
SUMMARY:Voyagers @ Rockies
DESCRIPTION:Voyagers @ Rockies\n\nFollow on MiLB First Pitch: https://stza.co/+xJ87-j\n\nShop: https://stza.co/+xJ87-3O\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144528Z
LAST-MODIFIED:20180213T144528Z
TRANSP:OPAQUE
END:VEVENT
* Voyagers vs. Brewers
<2018-07-26 Thu>--<2018-07-25 Wed>
:PROPERTIES:
:ID:       tvqwXoOjKboLN0qhEoeh1RvX@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Voyagers vs. Brewers Voyagers vs. Brewers

Follow on MiLB First Pitch  https //stza.co/+xCu2-2t

Shop  https //stza.co/+xCu2-3A

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Voyagers vs. Brewers
END:VALARM
DTSTART;VALUE=DATE:20180726
DTEND;VALUE=DATE:20180726
UID:tvqwXoOjKboLN0qhEoeh1RvX@stanza.co
SUMMARY:Voyagers vs. Brewers
DESCRIPTION:Voyagers vs. Brewers\n\nFollow on MiLB First Pitch: https://stza.co/+xCu2-2t\n\nShop: https://stza.co/+xCu2-3A\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144528Z
LAST-MODIFIED:20180213T144528Z
TRANSP:OPAQUE
END:VEVENT
* Voyagers vs. Brewers
<2018-07-27 Fri>--<2018-07-26 Thu>
:PROPERTIES:
:ID:       HG6gSF7B0bxTSNWjlp9frU45@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Voyagers vs. Brewers Voyagers vs. Brewers

Follow on MiLB First Pitch  https //stza.co/+xCu6-2$

Shop  https //stza.co/+xCu6-3v

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Voyagers vs. Brewers
END:VALARM
DTSTART;VALUE=DATE:20180727
DTEND;VALUE=DATE:20180727
UID:HG6gSF7B0bxTSNWjlp9frU45@stanza.co
SUMMARY:Voyagers vs. Brewers
DESCRIPTION:Voyagers vs. Brewers\n\nFollow on MiLB First Pitch: https://stza.co/+xCu6-2$\n\nShop: https://stza.co/+xCu6-3v\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144528Z
LAST-MODIFIED:20180213T144528Z
TRANSP:OPAQUE
END:VEVENT
* Voyagers vs. Brewers
<2018-07-28 Sat>--<2018-07-27 Fri>
:PROPERTIES:
:ID:       Fi-8dDZpnJ8__WzeKdD-AMv4@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Voyagers vs. Brewers Voyagers vs. Brewers

Follow on MiLB First Pitch  https //stza.co/+xCua-1r

Shop  https //stza.co/+xCua-1A

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Voyagers vs. Brewers
END:VALARM
DTSTART;VALUE=DATE:20180728
DTEND;VALUE=DATE:20180728
UID:Fi-8dDZpnJ8__WzeKdD-AMv4@stanza.co
SUMMARY:Voyagers vs. Brewers
DESCRIPTION:Voyagers vs. Brewers\n\nFollow on MiLB First Pitch: https://stza.co/+xCua-1r\n\nShop: https://stza.co/+xCua-1A\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144528Z
LAST-MODIFIED:20180213T144528Z
TRANSP:OPAQUE
END:VEVENT
* Voyagers vs. Brewers
<2018-07-29 Sun>--<2018-07-28 Sat>
:PROPERTIES:
:ID:       9KQf35mHziF32lJ-6rm1v5P5@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Voyagers vs. Brewers Voyagers vs. Brewers

Follow on MiLB First Pitch  https //stza.co/+xCue-1p

Shop  https //stza.co/+xCue-X

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Voyagers vs. Brewers
END:VALARM
DTSTART;VALUE=DATE:20180729
DTEND;VALUE=DATE:20180729
UID:9KQf35mHziF32lJ-6rm1v5P5@stanza.co
SUMMARY:Voyagers vs. Brewers
DESCRIPTION:Voyagers vs. Brewers\n\nFollow on MiLB First Pitch: https://stza.co/+xCue-1p\n\nShop: https://stza.co/+xCue-X\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144528Z
LAST-MODIFIED:20180213T144528Z
TRANSP:OPAQUE
END:VEVENT
* Voyagers @ Mustangs
<2018-07-30 Mon 20:05-23:05>
:PROPERTIES:
:ID:       P1f5Bekqiny5djR1AKsy5HTk@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Voyagers @ Mustangs Voyagers @ Mustangs

Follow on MiLB First Pitch  https //stza.co/+xSOx-b

Shop  https //stza.co/+xSOx-2j

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Voyagers @ Mustangs
END:VALARM
DTSTART:20180731T010500Z
DTEND:20180731T040500Z
UID:P1f5Bekqiny5djR1AKsy5HTk@stanza.co
SUMMARY:Voyagers @ Mustangs
DESCRIPTION:Voyagers @ Mustangs\n\nFollow on MiLB First Pitch: https://stza.co/+xSOx-b\n\nShop: https://stza.co/+xSOx-2j\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144528Z
LAST-MODIFIED:20180213T144528Z
TRANSP:OPAQUE
END:VEVENT
* Voyagers @ Mustangs
<2018-07-31 Tue 20:05-23:05>
:PROPERTIES:
:ID:       0sxoQZIoy14k8r8fKfT97QW1@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Voyagers @ Mustangs Voyagers @ Mustangs

Follow on MiLB First Pitch  https //stza.co/+xSOy-G

Shop  https //stza.co/+xSOy-2L

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Voyagers @ Mustangs
END:VALARM
DTSTART:20180801T010500Z
DTEND:20180801T040500Z
UID:0sxoQZIoy14k8r8fKfT97QW1@stanza.co
SUMMARY:Voyagers @ Mustangs
DESCRIPTION:Voyagers @ Mustangs\n\nFollow on MiLB First Pitch: https://stza.co/+xSOy-G\n\nShop: https://stza.co/+xSOy-2L\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144528Z
LAST-MODIFIED:20180213T144528Z
TRANSP:OPAQUE
END:VEVENT
* Voyagers vs. Mustangs
<2018-08-01 Wed>--<2018-07-31 Tue>
:PROPERTIES:
:ID:       dDLEo5xA0l9Vu1uSMKC9wSKQ@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Voyagers vs. Mustangs Voyagers vs. Mustangs

Follow on MiLB First Pitch  https //stza.co/+xCui-1F

Shop  https //stza.co/+xCui-2W

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Voyagers vs. Mustangs
END:VALARM
DTSTART;VALUE=DATE:20180801
DTEND;VALUE=DATE:20180801
UID:dDLEo5xA0l9Vu1uSMKC9wSKQ@stanza.co
SUMMARY:Voyagers vs. Mustangs
DESCRIPTION:Voyagers vs. Mustangs\n\nFollow on MiLB First Pitch: https://stza.co/+xCui-1F\n\nShop: https://stza.co/+xCui-2W\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144528Z
LAST-MODIFIED:20180213T144528Z
TRANSP:OPAQUE
END:VEVENT
* Voyagers vs. Mustangs
<2018-08-02 Thu>--<2018-08-01 Wed>
:PROPERTIES:
:ID:       AbxhneGmcE-qh-2cqO_Tq7Z2@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Voyagers vs. Mustangs Voyagers vs. Mustangs

Follow on MiLB First Pitch  https //stza.co/+xCun-1M

Shop  https //stza.co/+xCun-1m

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Voyagers vs. Mustangs
END:VALARM
DTSTART;VALUE=DATE:20180802
DTEND;VALUE=DATE:20180802
UID:AbxhneGmcE-qh-2cqO_Tq7Z2@stanza.co
SUMMARY:Voyagers vs. Mustangs
DESCRIPTION:Voyagers vs. Mustangs\n\nFollow on MiLB First Pitch: https://stza.co/+xCun-1M\n\nShop: https://stza.co/+xCun-1m\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144528Z
LAST-MODIFIED:20180213T144528Z
TRANSP:OPAQUE
END:VEVENT
* Voyagers @ Osprey
<2018-08-03 Fri>--<2018-08-02 Thu>
:PROPERTIES:
:ID:       k6Jvt0buGaZbQh6OCF8G_Z-L@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Voyagers @ Osprey Voyagers @ Osprey

Follow on MiLB First Pitch  https //stza.co/+xCsk-3B

Shop  https //stza.co/+xCsk-3Y

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Voyagers @ Osprey
END:VALARM
DTSTART;VALUE=DATE:20180803
DTEND;VALUE=DATE:20180803
UID:k6Jvt0buGaZbQh6OCF8G_Z-L@stanza.co
SUMMARY:Voyagers @ Osprey
DESCRIPTION:Voyagers @ Osprey\n\nFollow on MiLB First Pitch: https://stza.co/+xCsk-3B\n\nShop: https://stza.co/+xCsk-3Y\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144528Z
LAST-MODIFIED:20180213T144528Z
TRANSP:OPAQUE
END:VEVENT
* Voyagers @ Osprey
<2018-08-04 Sat>--<2018-08-03 Fri>
:PROPERTIES:
:ID:       _haxtd_0IuFzch4lt4AqryFQ@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Voyagers @ Osprey Voyagers @ Osprey

Follow on MiLB First Pitch  https //stza.co/+xCso-9

Shop  https //stza.co/+xCso-P

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Voyagers @ Osprey
END:VALARM
DTSTART;VALUE=DATE:20180804
DTEND;VALUE=DATE:20180804
UID:_haxtd_0IuFzch4lt4AqryFQ@stanza.co
SUMMARY:Voyagers @ Osprey
DESCRIPTION:Voyagers @ Osprey\n\nFollow on MiLB First Pitch: https://stza.co/+xCso-9\n\nShop: https://stza.co/+xCso-P\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144528Z
LAST-MODIFIED:20180213T144528Z
TRANSP:OPAQUE
END:VEVENT
* Voyagers @ Osprey
<2018-08-05 Sun>--<2018-08-04 Sat>
:PROPERTIES:
:ID:       rwuAURYASjHHZQ_UPIFEXZQP@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Voyagers @ Osprey Voyagers @ Osprey

Follow on MiLB First Pitch  https //stza.co/+xCsp-u

Shop  https //stza.co/+xCsp-20

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Voyagers @ Osprey
END:VALARM
DTSTART;VALUE=DATE:20180805
DTEND;VALUE=DATE:20180805
UID:rwuAURYASjHHZQ_UPIFEXZQP@stanza.co
SUMMARY:Voyagers @ Osprey
DESCRIPTION:Voyagers @ Osprey\n\nFollow on MiLB First Pitch: https://stza.co/+xCsp-u\n\nShop: https://stza.co/+xCsp-20\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144528Z
LAST-MODIFIED:20180213T144528Z
TRANSP:OPAQUE
END:VEVENT
* Voyagers vs. Chukars
<2018-08-09 Thu>--<2018-08-08 Wed>
:PROPERTIES:
:ID:       AsbqDkujHXCPlOwKjOo16cfN@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Voyagers vs. Chukars Voyagers vs. Chukars

Follow on MiLB First Pitch  https //stza.co/+xCuo-1U

Shop  https //stza.co/+xCuo-2T

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Voyagers vs. Chukars
END:VALARM
DTSTART;VALUE=DATE:20180809
DTEND;VALUE=DATE:20180809
UID:AsbqDkujHXCPlOwKjOo16cfN@stanza.co
SUMMARY:Voyagers vs. Chukars
DESCRIPTION:Voyagers vs. Chukars\n\nFollow on MiLB First Pitch: https://stza.co/+xCuo-1U\n\nShop: https://stza.co/+xCuo-2T\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144528Z
LAST-MODIFIED:20180213T144528Z
TRANSP:OPAQUE
END:VEVENT
* Voyagers vs. Chukars
<2018-08-10 Fri>--<2018-08-09 Thu>
:PROPERTIES:
:ID:       ZWIKFvRUIzuUXXbNFIugl4Yp@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Voyagers vs. Chukars Voyagers vs. Chukars

Follow on MiLB First Pitch  https //stza.co/+xCus-2k

Shop  https //stza.co/+xCus-1$

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Voyagers vs. Chukars
END:VALARM
DTSTART;VALUE=DATE:20180810
DTEND;VALUE=DATE:20180810
UID:ZWIKFvRUIzuUXXbNFIugl4Yp@stanza.co
SUMMARY:Voyagers vs. Chukars
DESCRIPTION:Voyagers vs. Chukars\n\nFollow on MiLB First Pitch: https://stza.co/+xCus-2k\n\nShop: https://stza.co/+xCus-1$\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144528Z
LAST-MODIFIED:20180213T144528Z
TRANSP:OPAQUE
END:VEVENT
* Voyagers vs. Chukars
<2018-08-11 Sat>--<2018-08-10 Fri>
:PROPERTIES:
:ID:       O1GhHlrPTHWLMser5m0PHlUb@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Voyagers vs. Chukars Voyagers vs. Chukars

Follow on MiLB First Pitch  https //stza.co/+xCuu-1b

Shop  https //stza.co/+xCuu-d

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Voyagers vs. Chukars
END:VALARM
DTSTART;VALUE=DATE:20180811
DTEND;VALUE=DATE:20180811
UID:O1GhHlrPTHWLMser5m0PHlUb@stanza.co
SUMMARY:Voyagers vs. Chukars
DESCRIPTION:Voyagers vs. Chukars\n\nFollow on MiLB First Pitch: https://stza.co/+xCuu-1b\n\nShop: https://stza.co/+xCuu-d\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144528Z
LAST-MODIFIED:20180213T144528Z
TRANSP:OPAQUE
END:VEVENT
* Voyagers vs. Chukars
<2018-08-12 Sun>--<2018-08-11 Sat>
:PROPERTIES:
:ID:       A-g7p-yNQQysljR8yl6QXcu8@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Voyagers vs. Chukars Voyagers vs. Chukars

Follow on MiLB First Pitch  https //stza.co/+xCuv-20

Shop  https //stza.co/+xCuv-L

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Voyagers vs. Chukars
END:VALARM
DTSTART;VALUE=DATE:20180812
DTEND;VALUE=DATE:20180812
UID:A-g7p-yNQQysljR8yl6QXcu8@stanza.co
SUMMARY:Voyagers vs. Chukars
DESCRIPTION:Voyagers vs. Chukars\n\nFollow on MiLB First Pitch: https://stza.co/+xCuv-20\n\nShop: https://stza.co/+xCuv-L\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144528Z
LAST-MODIFIED:20180213T144528Z
TRANSP:OPAQUE
END:VEVENT
* Voyagers vs. Raptors
<2018-08-13 Mon>--<2018-08-12 Sun>
:PROPERTIES:
:ID:       OtpTsDS07RXNZI2zm_1o8r78@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Voyagers vs. Raptors Voyagers vs. Raptors

Follow on MiLB First Pitch  https //stza.co/+xCuy-3g

Shop  https //stza.co/+xCuy-3H

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Voyagers vs. Raptors
END:VALARM
DTSTART;VALUE=DATE:20180813
DTEND;VALUE=DATE:20180813
UID:OtpTsDS07RXNZI2zm_1o8r78@stanza.co
SUMMARY:Voyagers vs. Raptors
DESCRIPTION:Voyagers vs. Raptors\n\nFollow on MiLB First Pitch: https://stza.co/+xCuy-3g\n\nShop: https://stza.co/+xCuy-3H\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144528Z
LAST-MODIFIED:20180213T144528Z
TRANSP:OPAQUE
END:VEVENT
* Voyagers vs. Raptors
<2018-08-14 Tue>--<2018-08-13 Mon>
:PROPERTIES:
:ID:       9IsfYjvnF4PNIc8To0ohymaN@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Voyagers vs. Raptors Voyagers vs. Raptors

Follow on MiLB First Pitch  https //stza.co/+xCuA-2p

Shop  https //stza.co/+xCuA-r

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Voyagers vs. Raptors
END:VALARM
DTSTART;VALUE=DATE:20180814
DTEND;VALUE=DATE:20180814
UID:9IsfYjvnF4PNIc8To0ohymaN@stanza.co
SUMMARY:Voyagers vs. Raptors
DESCRIPTION:Voyagers vs. Raptors\n\nFollow on MiLB First Pitch: https://stza.co/+xCuA-2p\n\nShop: https://stza.co/+xCuA-r\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144528Z
LAST-MODIFIED:20180213T144528Z
TRANSP:OPAQUE
END:VEVENT
* Voyagers vs. Raptors
<2018-08-15 Wed>--<2018-08-14 Tue>
:PROPERTIES:
:ID:       flCfCwZjbvaRExeSPDY0a43T@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Voyagers vs. Raptors Voyagers vs. Raptors

Follow on MiLB First Pitch  https //stza.co/+xCuD-3z

Shop  https //stza.co/+xCuD-22

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Voyagers vs. Raptors
END:VALARM
DTSTART;VALUE=DATE:20180815
DTEND;VALUE=DATE:20180815
UID:flCfCwZjbvaRExeSPDY0a43T@stanza.co
SUMMARY:Voyagers vs. Raptors
DESCRIPTION:Voyagers vs. Raptors\n\nFollow on MiLB First Pitch: https://stza.co/+xCuD-3z\n\nShop: https://stza.co/+xCuD-22\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144528Z
LAST-MODIFIED:20180213T144528Z
TRANSP:OPAQUE
END:VEVENT
* Voyagers @ Chukars
<2018-08-17 Fri 20:15-23:15>
:PROPERTIES:
:ID:       hDVizqNf8ueSLjTbp1ev0ujb@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Voyagers @ Chukars Voyagers @ Chukars

Follow on MiLB First Pitch  https //stza.co/+xZUI-1h

Shop  https //stza.co/+xZUI-28

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Voyagers @ Chukars
END:VALARM
DTSTART:20180818T011500Z
DTEND:20180818T041500Z
UID:hDVizqNf8ueSLjTbp1ev0ujb@stanza.co
SUMMARY:Voyagers @ Chukars
DESCRIPTION:Voyagers @ Chukars\n\nFollow on MiLB First Pitch: https://stza.co/+xZUI-1h\n\nShop: https://stza.co/+xZUI-28\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144528Z
LAST-MODIFIED:20180213T144528Z
TRANSP:OPAQUE
END:VEVENT
* Voyagers @ Chukars
<2018-08-18 Sat 20:15-23:15>
:PROPERTIES:
:ID:       MJLmoHSZhc1-yjWcxIntxSz_@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Voyagers @ Chukars Voyagers @ Chukars

Follow on MiLB First Pitch  https //stza.co/+xZUJ-1I

Shop  https //stza.co/+xZUJ-G

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Voyagers @ Chukars
END:VALARM
DTSTART:20180819T011500Z
DTEND:20180819T041500Z
UID:MJLmoHSZhc1-yjWcxIntxSz_@stanza.co
SUMMARY:Voyagers @ Chukars
DESCRIPTION:Voyagers @ Chukars\n\nFollow on MiLB First Pitch: https://stza.co/+xZUJ-1I\n\nShop: https://stza.co/+xZUJ-G\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144528Z
LAST-MODIFIED:20180213T144528Z
TRANSP:OPAQUE
END:VEVENT
* Voyagers @ Chukars
<2018-08-19 Sun 17:00-20:00>
:PROPERTIES:
:ID:       Ah9e0OD00aINYSzB9lLXTulg@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Voyagers @ Chukars Voyagers @ Chukars

Follow on MiLB First Pitch  https //stza.co/+xZUK-2R

Shop  https //stza.co/+xZUK-3N

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Voyagers @ Chukars
END:VALARM
DTSTART:20180819T220000Z
DTEND:20180820T010000Z
UID:Ah9e0OD00aINYSzB9lLXTulg@stanza.co
SUMMARY:Voyagers @ Chukars
DESCRIPTION:Voyagers @ Chukars\n\nFollow on MiLB First Pitch: https://stza.co/+xZUK-2R\n\nShop: https://stza.co/+xZUK-3N\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144528Z
LAST-MODIFIED:20180213T144528Z
TRANSP:OPAQUE
END:VEVENT
* Voyagers @ Raptors
<2018-08-20 Mon 19:30-22:30>
:PROPERTIES:
:ID:       mlWxzKulU62-wHAbTfp2T3YD@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Voyagers @ Raptors Voyagers @ Raptors

Follow on MiLB First Pitch  https //stza.co/+x$7W-3d

Shop  https //stza.co/+x$7W-3J

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Voyagers @ Raptors
END:VALARM
DTSTART:20180821T003000Z
DTEND:20180821T033000Z
UID:mlWxzKulU62-wHAbTfp2T3YD@stanza.co
SUMMARY:Voyagers @ Raptors
DESCRIPTION:Voyagers @ Raptors\n\nFollow on MiLB First Pitch: https://stza.co/+x$7W-3d\n\nShop: https://stza.co/+x$7W-3J\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144528Z
LAST-MODIFIED:20180213T144528Z
TRANSP:OPAQUE
END:VEVENT
* Voyagers @ Raptors
<2018-08-21 Tue 19:30-22:30>
:PROPERTIES:
:ID:       73tbnOlZDEPw44X_JJneR4FW@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Voyagers @ Raptors Voyagers @ Raptors

Follow on MiLB First Pitch  https //stza.co/+x$7X-2O

Shop  https //stza.co/+x$7X-1m

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Voyagers @ Raptors
END:VALARM
DTSTART:20180822T003000Z
DTEND:20180822T033000Z
UID:73tbnOlZDEPw44X_JJneR4FW@stanza.co
SUMMARY:Voyagers @ Raptors
DESCRIPTION:Voyagers @ Raptors\n\nFollow on MiLB First Pitch: https://stza.co/+x$7X-2O\n\nShop: https://stza.co/+x$7X-1m\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144528Z
LAST-MODIFIED:20180213T144528Z
TRANSP:OPAQUE
END:VEVENT
* Voyagers @ Raptors
<2018-08-22 Wed 19:30-22:30>
:PROPERTIES:
:ID:       hXKqSt3Psb3vs0xGrJ5C-K5z@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Voyagers @ Raptors Voyagers @ Raptors

Follow on MiLB First Pitch  https //stza.co/+x$7Y-2k

Shop  https //stza.co/+x$7Y-Z

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Voyagers @ Raptors
END:VALARM
DTSTART:20180823T003000Z
DTEND:20180823T033000Z
UID:hXKqSt3Psb3vs0xGrJ5C-K5z@stanza.co
SUMMARY:Voyagers @ Raptors
DESCRIPTION:Voyagers @ Raptors\n\nFollow on MiLB First Pitch: https://stza.co/+x$7Y-2k\n\nShop: https://stza.co/+x$7Y-Z\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144528Z
LAST-MODIFIED:20180213T144528Z
TRANSP:OPAQUE
END:VEVENT
* Voyagers @ Raptors
<2018-08-23 Thu 19:30-22:30>
:PROPERTIES:
:ID:       SJdBxayppQ2oLQsyUu8VydgJ@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Voyagers @ Raptors Voyagers @ Raptors

Follow on MiLB First Pitch  https //stza.co/+x$7Z-1S

Shop  https //stza.co/+x$7Z-X

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Voyagers @ Raptors
END:VALARM
DTSTART:20180824T003000Z
DTEND:20180824T033000Z
UID:SJdBxayppQ2oLQsyUu8VydgJ@stanza.co
SUMMARY:Voyagers @ Raptors
DESCRIPTION:Voyagers @ Raptors\n\nFollow on MiLB First Pitch: https://stza.co/+x$7Z-1S\n\nShop: https://stza.co/+x$7Z-X\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144528Z
LAST-MODIFIED:20180213T144528Z
TRANSP:OPAQUE
END:VEVENT
* Voyagers vs. Osprey
<2018-08-25 Sat>--<2018-08-24 Fri>
:PROPERTIES:
:ID:       t8MQ64yl1inbOvtG6TzwlnyZ@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Voyagers vs. Osprey Voyagers vs. Osprey

Follow on MiLB First Pitch  https //stza.co/+xCuE-V

Shop  https //stza.co/+xCuE-f

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Voyagers vs. Osprey
END:VALARM
DTSTART;VALUE=DATE:20180825
DTEND;VALUE=DATE:20180825
UID:t8MQ64yl1inbOvtG6TzwlnyZ@stanza.co
SUMMARY:Voyagers vs. Osprey
DESCRIPTION:Voyagers vs. Osprey\n\nFollow on MiLB First Pitch: https://stza.co/+xCuE-V\n\nShop: https://stza.co/+xCuE-f\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144528Z
LAST-MODIFIED:20180213T144528Z
TRANSP:OPAQUE
END:VEVENT
* Voyagers vs. Osprey
<2018-08-26 Sun>--<2018-08-25 Sat>
:PROPERTIES:
:ID:       UtWCz5S4lCf6hWMV30eVcRmE@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Voyagers vs. Osprey Voyagers vs. Osprey

Follow on MiLB First Pitch  https //stza.co/+xCuH-1S

Shop  https //stza.co/+xCuH-39

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Voyagers vs. Osprey
END:VALARM
DTSTART;VALUE=DATE:20180826
DTEND;VALUE=DATE:20180826
UID:UtWCz5S4lCf6hWMV30eVcRmE@stanza.co
SUMMARY:Voyagers vs. Osprey
DESCRIPTION:Voyagers vs. Osprey\n\nFollow on MiLB First Pitch: https://stza.co/+xCuH-1S\n\nShop: https://stza.co/+xCuH-39\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144528Z
LAST-MODIFIED:20180213T144528Z
TRANSP:OPAQUE
END:VEVENT
* Voyagers vs. Osprey
<2018-08-27 Mon>--<2018-08-26 Sun>
:PROPERTIES:
:ID:       jdARrgNj41Seq2V2eRpTyL2F@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Voyagers vs. Osprey Voyagers vs. Osprey

Follow on MiLB First Pitch  https //stza.co/+xCuK-1_

Shop  https //stza.co/+xCuK-c

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Voyagers vs. Osprey
END:VALARM
DTSTART;VALUE=DATE:20180827
DTEND;VALUE=DATE:20180827
UID:jdARrgNj41Seq2V2eRpTyL2F@stanza.co
SUMMARY:Voyagers vs. Osprey
DESCRIPTION:Voyagers vs. Osprey\n\nFollow on MiLB First Pitch: https://stza.co/+xCuK-1_\n\nShop: https://stza.co/+xCuK-c\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144528Z
LAST-MODIFIED:20180213T144528Z
TRANSP:OPAQUE
END:VEVENT
* Voyagers @ Brewers
<2018-08-28 Tue>--<2018-08-27 Mon>
:PROPERTIES:
:ID:       nRAwViKIO9sXdvvoZvRLW1LP@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Voyagers @ Brewers Voyagers @ Brewers

Follow on MiLB First Pitch  https //stza.co/+xCqK-2o

Shop  https //stza.co/+xCqK-20

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Voyagers @ Brewers
END:VALARM
DTSTART;VALUE=DATE:20180828
DTEND;VALUE=DATE:20180828
UID:nRAwViKIO9sXdvvoZvRLW1LP@stanza.co
SUMMARY:Voyagers @ Brewers
DESCRIPTION:Voyagers @ Brewers\n\nFollow on MiLB First Pitch: https://stza.co/+xCqK-2o\n\nShop: https://stza.co/+xCqK-20\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144528Z
LAST-MODIFIED:20180213T144528Z
TRANSP:OPAQUE
END:VEVENT
* Voyagers @ Brewers
<2018-08-29 Wed>--<2018-08-28 Tue>
:PROPERTIES:
:ID:       uS9mverNGXnvAsfdCopX-t4M@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Voyagers @ Brewers Voyagers @ Brewers

Follow on MiLB First Pitch  https //stza.co/+xCqM-3V

Shop  https //stza.co/+xCqM-3G

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Voyagers @ Brewers
END:VALARM
DTSTART;VALUE=DATE:20180829
DTEND;VALUE=DATE:20180829
UID:uS9mverNGXnvAsfdCopX-t4M@stanza.co
SUMMARY:Voyagers @ Brewers
DESCRIPTION:Voyagers @ Brewers\n\nFollow on MiLB First Pitch: https://stza.co/+xCqM-3V\n\nShop: https://stza.co/+xCqM-3G\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144528Z
LAST-MODIFIED:20180213T144528Z
TRANSP:OPAQUE
END:VEVENT
* Voyagers @ Brewers
<2018-08-30 Thu>--<2018-08-29 Wed>
:PROPERTIES:
:ID:       GbzqfXYfmPvjrQjs6cAyb0Xm@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Voyagers @ Brewers Voyagers @ Brewers

Follow on MiLB First Pitch  https //stza.co/+xCqP-2I

Shop  https //stza.co/+xCqP-2m

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Voyagers @ Brewers
END:VALARM
DTSTART;VALUE=DATE:20180830
DTEND;VALUE=DATE:20180830
UID:GbzqfXYfmPvjrQjs6cAyb0Xm@stanza.co
SUMMARY:Voyagers @ Brewers
DESCRIPTION:Voyagers @ Brewers\n\nFollow on MiLB First Pitch: https://stza.co/+xCqP-2I\n\nShop: https://stza.co/+xCqP-2m\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144528Z
LAST-MODIFIED:20180213T144528Z
TRANSP:OPAQUE
END:VEVENT
* Voyagers @ Brewers
<2018-08-31 Fri>--<2018-08-30 Thu>
:PROPERTIES:
:ID:       wBBP5iwzsvOR9lyJsNDG9ksE@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Voyagers @ Brewers Voyagers @ Brewers

Follow on MiLB First Pitch  https //stza.co/+xCqT-3v

Shop  https //stza.co/+xCqT-2G

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Voyagers @ Brewers
END:VALARM
DTSTART;VALUE=DATE:20180831
DTEND;VALUE=DATE:20180831
UID:wBBP5iwzsvOR9lyJsNDG9ksE@stanza.co
SUMMARY:Voyagers @ Brewers
DESCRIPTION:Voyagers @ Brewers\n\nFollow on MiLB First Pitch: https://stza.co/+xCqT-3v\n\nShop: https://stza.co/+xCqT-2G\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144528Z
LAST-MODIFIED:20180213T144528Z
TRANSP:OPAQUE
END:VEVENT
* Voyagers vs. Mustangs
<2018-09-01 Sat>--<2018-08-31 Fri>
:PROPERTIES:
:ID:       jtdnHgNMKfa45yO41j5dNWb6@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Voyagers vs. Mustangs Voyagers vs. Mustangs

Follow on MiLB First Pitch  https //stza.co/+xCuM-A

Shop  https //stza.co/+xCuM-2y

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Voyagers vs. Mustangs
END:VALARM
DTSTART;VALUE=DATE:20180901
DTEND;VALUE=DATE:20180901
UID:jtdnHgNMKfa45yO41j5dNWb6@stanza.co
SUMMARY:Voyagers vs. Mustangs
DESCRIPTION:Voyagers vs. Mustangs\n\nFollow on MiLB First Pitch: https://stza.co/+xCuM-A\n\nShop: https://stza.co/+xCuM-2y\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144528Z
LAST-MODIFIED:20180213T144528Z
TRANSP:OPAQUE
END:VEVENT
* Voyagers vs. Mustangs
<2018-09-02 Sun>--<2018-09-01 Sat>
:PROPERTIES:
:ID:       O9uxWcaeG2r3gmc1JRBjnzrR@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Voyagers vs. Mustangs Voyagers vs. Mustangs

Follow on MiLB First Pitch  https //stza.co/+xCuN-2G

Shop  https //stza.co/+xCuN-K

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Voyagers vs. Mustangs
END:VALARM
DTSTART;VALUE=DATE:20180902
DTEND;VALUE=DATE:20180902
UID:O9uxWcaeG2r3gmc1JRBjnzrR@stanza.co
SUMMARY:Voyagers vs. Mustangs
DESCRIPTION:Voyagers vs. Mustangs\n\nFollow on MiLB First Pitch: https://stza.co/+xCuN-2G\n\nShop: https://stza.co/+xCuN-K\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144528Z
LAST-MODIFIED:20180213T144528Z
TRANSP:OPAQUE
END:VEVENT
* Voyagers vs. Mustangs
<2018-09-03 Mon>--<2018-09-02 Sun>
:PROPERTIES:
:ID:       FYoluplRBsY16axiMm6ng2mU@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Voyagers vs. Mustangs Voyagers vs. Mustangs

Follow on MiLB First Pitch  https //stza.co/+xCuR-33

Shop  https //stza.co/+xCuR-2V

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Voyagers vs. Mustangs
END:VALARM
DTSTART;VALUE=DATE:20180903
DTEND;VALUE=DATE:20180903
UID:FYoluplRBsY16axiMm6ng2mU@stanza.co
SUMMARY:Voyagers vs. Mustangs
DESCRIPTION:Voyagers vs. Mustangs\n\nFollow on MiLB First Pitch: https://stza.co/+xCuR-33\n\nShop: https://stza.co/+xCuR-2V\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144528Z
LAST-MODIFIED:20180213T144528Z
TRANSP:OPAQUE
END:VEVENT
* Voyagers @ Mustangs
<2018-09-04 Tue 20:05-23:05>
:PROPERTIES:
:ID:       kW9IuSvwcVYSMBJx55ctm6vT@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Voyagers @ Mustangs Voyagers @ Mustangs

Follow on MiLB First Pitch  https //stza.co/+xSOz-3q

Shop  https //stza.co/+xSOz-2k

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Voyagers @ Mustangs
END:VALARM
DTSTART:20180905T010500Z
DTEND:20180905T040500Z
UID:kW9IuSvwcVYSMBJx55ctm6vT@stanza.co
SUMMARY:Voyagers @ Mustangs
DESCRIPTION:Voyagers @ Mustangs\n\nFollow on MiLB First Pitch: https://stza.co/+xSOz-3q\n\nShop: https://stza.co/+xSOz-2k\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144528Z
LAST-MODIFIED:20180213T144528Z
TRANSP:OPAQUE
END:VEVENT
* Voyagers @ Mustangs
<2018-09-05 Wed 20:05-23:05>
:PROPERTIES:
:ID:       TFCaAdu3OD4N4Q2hkAnBxQPU@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Voyagers @ Mustangs Voyagers @ Mustangs

Follow on MiLB First Pitch  https //stza.co/+xSOA-W

Shop  https //stza.co/+xSOA-1_

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Voyagers @ Mustangs
END:VALARM
DTSTART:20180906T010500Z
DTEND:20180906T040500Z
UID:TFCaAdu3OD4N4Q2hkAnBxQPU@stanza.co
SUMMARY:Voyagers @ Mustangs
DESCRIPTION:Voyagers @ Mustangs\n\nFollow on MiLB First Pitch: https://stza.co/+xSOA-W\n\nShop: https://stza.co/+xSOA-1_\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144528Z
LAST-MODIFIED:20180213T144528Z
TRANSP:OPAQUE
END:VEVENT
* Voyagers @ Mustangs
<2018-09-06 Thu 20:05-23:05>
:PROPERTIES:
:ID:       6yQlVe8QigzTE6LOU0fS308Q@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Voyagers @ Mustangs Voyagers @ Mustangs

Follow on MiLB First Pitch  https //stza.co/+xSOB-1Q

Shop  https //stza.co/+xSOB-30

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Voyagers @ Mustangs
END:VALARM
DTSTART:20180907T010500Z
DTEND:20180907T040500Z
UID:6yQlVe8QigzTE6LOU0fS308Q@stanza.co
SUMMARY:Voyagers @ Mustangs
DESCRIPTION:Voyagers @ Mustangs\n\nFollow on MiLB First Pitch: https://stza.co/+xSOB-1Q\n\nShop: https://stza.co/+xSOB-30\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144528Z
LAST-MODIFIED:20180213T144528Z
TRANSP:OPAQUE
END:VEVENT
