#+TITLE:       Main Google calendar entries
#+AUTHOR:      Eric S Fraga
#+EMAIL:       e.fraga@ucl.ac.uk
#+DESCRIPTION: converted using the ical2org awk script
#+CATEGORY:    google
#+STARTUP:     hidestars
#+STARTUP:     overview

* COMMENT original iCal preamble

* Travelers vs. Missions
<2018-04-05 Thu 19:10-22:10>
:PROPERTIES:
:ID:       NmLUCnRh5qRl2J-Gel7MdjKN@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Travelers vs. Missions Travelers vs. Missions

Follow on MiLB First Pitch  https //stza.co/+v$SD-2B

Shop  https //stza.co/+v$SD-k

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Travelers vs. Missions
END:VALARM
DTSTART:20180406T001000Z
DTEND:20180406T031000Z
UID:NmLUCnRh5qRl2J-Gel7MdjKN@stanza.co
SUMMARY:Travelers vs. Missions
DESCRIPTION:Travelers vs. Missions\n\nFollow on MiLB First Pitch: https://stza.co/+v$SD-2B\n\nShop: https://stza.co/+v$SD-k\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144501Z
LAST-MODIFIED:20180213T144501Z
TRANSP:OPAQUE
END:VEVENT
* Travelers vs. Missions
<2018-04-06 Fri 19:10-22:10>
:PROPERTIES:
:ID:       QqNHd_bFW61Qqv_HUdzhD1QS@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Travelers vs. Missions Travelers vs. Missions

Follow on MiLB First Pitch  https //stza.co/+v$SF-2X

Shop  https //stza.co/+v$SF-3j

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Travelers vs. Missions
END:VALARM
DTSTART:20180407T001000Z
DTEND:20180407T031000Z
UID:QqNHd_bFW61Qqv_HUdzhD1QS@stanza.co
SUMMARY:Travelers vs. Missions
DESCRIPTION:Travelers vs. Missions\n\nFollow on MiLB First Pitch: https://stza.co/+v$SF-2X\n\nShop: https://stza.co/+v$SF-3j\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144501Z
LAST-MODIFIED:20180213T144501Z
TRANSP:OPAQUE
END:VEVENT
* Travelers vs. Missions
<2018-04-07 Sat 18:10-21:10>
:PROPERTIES:
:ID:       103luVQ85Khs3F98P_hE8_uO@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Travelers vs. Missions Travelers vs. Missions

Follow on MiLB First Pitch  https //stza.co/+v$SG-2z

Shop  https //stza.co/+v$SG-3m

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Travelers vs. Missions
END:VALARM
DTSTART:20180407T231000Z
DTEND:20180408T021000Z
UID:103luVQ85Khs3F98P_hE8_uO@stanza.co
SUMMARY:Travelers vs. Missions
DESCRIPTION:Travelers vs. Missions\n\nFollow on MiLB First Pitch: https://stza.co/+v$SG-2z\n\nShop: https://stza.co/+v$SG-3m\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144501Z
LAST-MODIFIED:20180213T144501Z
TRANSP:OPAQUE
END:VEVENT
* Travelers vs. Hooks
<2018-04-08 Sun 14:10-17:10>
:PROPERTIES:
:ID:       YPe25rJ-txmeatuRkQcL8uOo@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Travelers vs. Hooks Travelers vs. Hooks

Follow on MiLB First Pitch  https //stza.co/+v$SJ-3y

Shop  https //stza.co/+v$SJ-4

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Travelers vs. Hooks
END:VALARM
DTSTART:20180408T191000Z
DTEND:20180408T221000Z
UID:YPe25rJ-txmeatuRkQcL8uOo@stanza.co
SUMMARY:Travelers vs. Hooks
DESCRIPTION:Travelers vs. Hooks\n\nFollow on MiLB First Pitch: https://stza.co/+v$SJ-3y\n\nShop: https://stza.co/+v$SJ-4\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144501Z
LAST-MODIFIED:20180213T144501Z
TRANSP:OPAQUE
END:VEVENT
* Travelers vs. Hooks
<2018-04-09 Mon 19:10-22:10>
:PROPERTIES:
:ID:       2PbAyQ-vkEJIbs9t72KgBFo2@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Travelers vs. Hooks Travelers vs. Hooks

Follow on MiLB First Pitch  https //stza.co/+v$SL-S

Shop  https //stza.co/+v$SL-2s

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Travelers vs. Hooks
END:VALARM
DTSTART:20180410T001000Z
DTEND:20180410T031000Z
UID:2PbAyQ-vkEJIbs9t72KgBFo2@stanza.co
SUMMARY:Travelers vs. Hooks
DESCRIPTION:Travelers vs. Hooks\n\nFollow on MiLB First Pitch: https://stza.co/+v$SL-S\n\nShop: https://stza.co/+v$SL-2s\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144501Z
LAST-MODIFIED:20180213T144501Z
TRANSP:OPAQUE
END:VEVENT
* Travelers vs. Hooks
<2018-04-10 Tue 11:00-14:00>
:PROPERTIES:
:ID:       GFBC4Mda0rbDExeASvVpF0Os@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Travelers vs. Hooks Travelers vs. Hooks

Follow on MiLB First Pitch  https //stza.co/+v$SN-2j

Shop  https //stza.co/+v$SN-1e

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Travelers vs. Hooks
END:VALARM
DTSTART:20180410T160000Z
DTEND:20180410T190000Z
UID:GFBC4Mda0rbDExeASvVpF0Os@stanza.co
SUMMARY:Travelers vs. Hooks
DESCRIPTION:Travelers vs. Hooks\n\nFollow on MiLB First Pitch: https://stza.co/+v$SN-2j\n\nShop: https://stza.co/+v$SN-1e\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144501Z
LAST-MODIFIED:20180213T144501Z
TRANSP:OPAQUE
END:VEVENT
* Travelers @ Missions
<2018-04-12 Thu 19:05-22:05>
:PROPERTIES:
:ID:       nOxkqIn_bMB8VfRneVRmAyLt@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Travelers @ Missions Travelers @ Missions

Follow on MiLB First Pitch  https //stza.co/+wMth-1H

Shop  https //stza.co/+wMth-2j

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Travelers @ Missions
END:VALARM
DTSTART:20180413T000500Z
DTEND:20180413T030500Z
UID:nOxkqIn_bMB8VfRneVRmAyLt@stanza.co
SUMMARY:Travelers @ Missions
DESCRIPTION:Travelers @ Missions\n\nFollow on MiLB First Pitch: https://stza.co/+wMth-1H\n\nShop: https://stza.co/+wMth-2j\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144501Z
LAST-MODIFIED:20180213T144501Z
TRANSP:OPAQUE
END:VEVENT
* Travelers @ Missions
<2018-04-13 Fri 19:05-22:05>
:PROPERTIES:
:ID:       NasSp-UVH1sCJ8-qUiQRR6Xr@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Travelers @ Missions Travelers @ Missions

Follow on MiLB First Pitch  https //stza.co/+wMti-3n

Shop  https //stza.co/+wMti-2b

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Travelers @ Missions
END:VALARM
DTSTART:20180414T000500Z
DTEND:20180414T030500Z
UID:NasSp-UVH1sCJ8-qUiQRR6Xr@stanza.co
SUMMARY:Travelers @ Missions
DESCRIPTION:Travelers @ Missions\n\nFollow on MiLB First Pitch: https://stza.co/+wMti-3n\n\nShop: https://stza.co/+wMti-2b\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144501Z
LAST-MODIFIED:20180213T144501Z
TRANSP:OPAQUE
END:VEVENT
* Travelers @ Missions
<2018-04-14 Sat 19:05-22:05>
:PROPERTIES:
:ID:       GCzYwRVFqr4VpVgASh4E3gT5@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Travelers @ Missions Travelers @ Missions

Follow on MiLB First Pitch  https //stza.co/+wMtj-3v

Shop  https //stza.co/+wMtj-2M

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Travelers @ Missions
END:VALARM
DTSTART:20180415T000500Z
DTEND:20180415T030500Z
UID:GCzYwRVFqr4VpVgASh4E3gT5@stanza.co
SUMMARY:Travelers @ Missions
DESCRIPTION:Travelers @ Missions\n\nFollow on MiLB First Pitch: https://stza.co/+wMtj-3v\n\nShop: https://stza.co/+wMtj-2M\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144501Z
LAST-MODIFIED:20180213T144501Z
TRANSP:OPAQUE
END:VEVENT
* Travelers @ Hooks
<2018-04-15 Sun 14:05-17:05>
:PROPERTIES:
:ID:       82hKP3sWlXASoQCbp3hNVpk3@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Travelers @ Hooks Travelers @ Hooks

Follow on MiLB First Pitch  https //stza.co/+xzEF-2v

Shop  https //stza.co/+xzEF-1d

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Travelers @ Hooks
END:VALARM
DTSTART:20180415T190500Z
DTEND:20180415T220500Z
UID:82hKP3sWlXASoQCbp3hNVpk3@stanza.co
SUMMARY:Travelers @ Hooks
DESCRIPTION:Travelers @ Hooks\n\nFollow on MiLB First Pitch: https://stza.co/+xzEF-2v\n\nShop: https://stza.co/+xzEF-1d\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144501Z
LAST-MODIFIED:20180213T144501Z
TRANSP:OPAQUE
END:VEVENT
* Travelers @ Hooks
<2018-04-16 Mon 19:05-22:05>
:PROPERTIES:
:ID:       CeMZp5Kn3igE3dV7vRUkNwSd@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Travelers @ Hooks Travelers @ Hooks

Follow on MiLB First Pitch  https //stza.co/+xzEH-1u

Shop  https //stza.co/+xzEH-2W

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Travelers @ Hooks
END:VALARM
DTSTART:20180417T000500Z
DTEND:20180417T030500Z
UID:CeMZp5Kn3igE3dV7vRUkNwSd@stanza.co
SUMMARY:Travelers @ Hooks
DESCRIPTION:Travelers @ Hooks\n\nFollow on MiLB First Pitch: https://stza.co/+xzEH-1u\n\nShop: https://stza.co/+xzEH-2W\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144501Z
LAST-MODIFIED:20180213T144501Z
TRANSP:OPAQUE
END:VEVENT
* Travelers @ Hooks
<2018-04-17 Tue 19:05-22:05>
:PROPERTIES:
:ID:       EGCyF2gNPmoJBtD_FhOGKegl@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Travelers @ Hooks Travelers @ Hooks

Follow on MiLB First Pitch  https //stza.co/+xzEI-3y

Shop  https //stza.co/+xzEI-1X

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Travelers @ Hooks
END:VALARM
DTSTART:20180418T000500Z
DTEND:20180418T030500Z
UID:EGCyF2gNPmoJBtD_FhOGKegl@stanza.co
SUMMARY:Travelers @ Hooks
DESCRIPTION:Travelers @ Hooks\n\nFollow on MiLB First Pitch: https://stza.co/+xzEI-3y\n\nShop: https://stza.co/+xzEI-1X\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144501Z
LAST-MODIFIED:20180213T144501Z
TRANSP:OPAQUE
END:VEVENT
* Travelers vs. Cardinals
<2018-04-19 Thu 19:10-22:10>
:PROPERTIES:
:ID:       r68dj1UwT6cau1MV9iaMLId5@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Travelers vs. Cardinals Travelers vs. Cardinals

Follow on MiLB First Pitch  https //stza.co/+v$SP-1i

Shop  https //stza.co/+v$SP-1D

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Travelers vs. Cardinals
END:VALARM
DTSTART:20180420T001000Z
DTEND:20180420T031000Z
UID:r68dj1UwT6cau1MV9iaMLId5@stanza.co
SUMMARY:Travelers vs. Cardinals
DESCRIPTION:Travelers vs. Cardinals\n\nFollow on MiLB First Pitch: https://stza.co/+v$SP-1i\n\nShop: https://stza.co/+v$SP-1D\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144501Z
LAST-MODIFIED:20180213T144501Z
TRANSP:OPAQUE
END:VEVENT
* Travelers vs. Cardinals
<2018-04-20 Fri 19:10-22:10>
:PROPERTIES:
:ID:       iagrCW6rTmzXcpeaHPJkWBsb@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Travelers vs. Cardinals Travelers vs. Cardinals

Follow on MiLB First Pitch  https //stza.co/+v$SR-N

Shop  https //stza.co/+v$SR-l

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Travelers vs. Cardinals
END:VALARM
DTSTART:20180421T001000Z
DTEND:20180421T031000Z
UID:iagrCW6rTmzXcpeaHPJkWBsb@stanza.co
SUMMARY:Travelers vs. Cardinals
DESCRIPTION:Travelers vs. Cardinals\n\nFollow on MiLB First Pitch: https://stza.co/+v$SR-N\n\nShop: https://stza.co/+v$SR-l\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144501Z
LAST-MODIFIED:20180213T144501Z
TRANSP:OPAQUE
END:VEVENT
* Travelers vs. Cardinals
<2018-04-21 Sat 18:10-21:10>
:PROPERTIES:
:ID:       2lIzSnF7wZj_potctFKOw76e@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Travelers vs. Cardinals Travelers vs. Cardinals

Follow on MiLB First Pitch  https //stza.co/+v$SS-3E

Shop  https //stza.co/+v$SS-S

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Travelers vs. Cardinals
END:VALARM
DTSTART:20180421T231000Z
DTEND:20180422T021000Z
UID:2lIzSnF7wZj_potctFKOw76e@stanza.co
SUMMARY:Travelers vs. Cardinals
DESCRIPTION:Travelers vs. Cardinals\n\nFollow on MiLB First Pitch: https://stza.co/+v$SS-3E\n\nShop: https://stza.co/+v$SS-S\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144501Z
LAST-MODIFIED:20180213T144501Z
TRANSP:OPAQUE
END:VEVENT
* Travelers vs. Cardinals
<2018-04-22 Sun 14:10-17:10>
:PROPERTIES:
:ID:       b835wtM00w2Szz5zXIMF6kQ-@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Travelers vs. Cardinals Travelers vs. Cardinals

Follow on MiLB First Pitch  https //stza.co/+v$SV-3W

Shop  https //stza.co/+v$SV-3r

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Travelers vs. Cardinals
END:VALARM
DTSTART:20180422T191000Z
DTEND:20180422T221000Z
UID:b835wtM00w2Szz5zXIMF6kQ-@stanza.co
SUMMARY:Travelers vs. Cardinals
DESCRIPTION:Travelers vs. Cardinals\n\nFollow on MiLB First Pitch: https://stza.co/+v$SV-3W\n\nShop: https://stza.co/+v$SV-3r\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144501Z
LAST-MODIFIED:20180213T144501Z
TRANSP:OPAQUE
END:VEVENT
* Travelers vs. Drillers
<2018-04-23 Mon 19:10-22:10>
:PROPERTIES:
:ID:       HU1dt6-szOOLH0p76GBbpVpR@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Travelers vs. Drillers Travelers vs. Drillers

Follow on MiLB First Pitch  https //stza.co/+v$SW-3C

Shop  https //stza.co/+v$SW-1I

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Travelers vs. Drillers
END:VALARM
DTSTART:20180424T001000Z
DTEND:20180424T031000Z
UID:HU1dt6-szOOLH0p76GBbpVpR@stanza.co
SUMMARY:Travelers vs. Drillers
DESCRIPTION:Travelers vs. Drillers\n\nFollow on MiLB First Pitch: https://stza.co/+v$SW-3C\n\nShop: https://stza.co/+v$SW-1I\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144501Z
LAST-MODIFIED:20180213T144501Z
TRANSP:OPAQUE
END:VEVENT
* Travelers vs. Drillers
<2018-04-24 Tue 11:00-14:00>
:PROPERTIES:
:ID:       ChgjWcDCWm7dqhtxtxPK_uzC@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Travelers vs. Drillers Travelers vs. Drillers

Follow on MiLB First Pitch  https //stza.co/+v$SY-1

Shop  https //stza.co/+v$SY-h

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Travelers vs. Drillers
END:VALARM
DTSTART:20180424T160000Z
DTEND:20180424T190000Z
UID:ChgjWcDCWm7dqhtxtxPK_uzC@stanza.co
SUMMARY:Travelers vs. Drillers
DESCRIPTION:Travelers vs. Drillers\n\nFollow on MiLB First Pitch: https://stza.co/+v$SY-1\n\nShop: https://stza.co/+v$SY-h\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144501Z
LAST-MODIFIED:20180213T144501Z
TRANSP:OPAQUE
END:VEVENT
* Travelers vs. Drillers
<2018-04-25 Wed 19:10-22:10>
:PROPERTIES:
:ID:       fc7Uq7icAUL319WgyIK_L5pa@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Travelers vs. Drillers Travelers vs. Drillers

Follow on MiLB First Pitch  https //stza.co/+v$S$-7

Shop  https //stza.co/+v$S$-2_

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Travelers vs. Drillers
END:VALARM
DTSTART:20180426T001000Z
DTEND:20180426T031000Z
UID:fc7Uq7icAUL319WgyIK_L5pa@stanza.co
SUMMARY:Travelers vs. Drillers
DESCRIPTION:Travelers vs. Drillers\n\nFollow on MiLB First Pitch: https://stza.co/+v$S$-7\n\nShop: https://stza.co/+v$S$-2_\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144501Z
LAST-MODIFIED:20180213T144501Z
TRANSP:OPAQUE
END:VEVENT
* Travelers vs. Drillers
<2018-04-26 Thu 19:10-22:10>
:PROPERTIES:
:ID:       UYJV0NWCW3KISZTUNMikMlwR@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Travelers vs. Drillers Travelers vs. Drillers

Follow on MiLB First Pitch  https //stza.co/+v$T1-1c

Shop  https //stza.co/+v$T1-38

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Travelers vs. Drillers
END:VALARM
DTSTART:20180427T001000Z
DTEND:20180427T031000Z
UID:UYJV0NWCW3KISZTUNMikMlwR@stanza.co
SUMMARY:Travelers vs. Drillers
DESCRIPTION:Travelers vs. Drillers\n\nFollow on MiLB First Pitch: https://stza.co/+v$T1-1c\n\nShop: https://stza.co/+v$T1-38\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144501Z
LAST-MODIFIED:20180213T144501Z
TRANSP:OPAQUE
END:VEVENT
* Travelers @ Cardinals
<2018-04-27 Fri 19:10-22:10>
:PROPERTIES:
:ID:       uyRx5ZxSkwdj-HnI7Bh4FF5V@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Travelers @ Cardinals Travelers @ Cardinals

Follow on MiLB First Pitch  https //stza.co/+wPM0-36

Shop  https //stza.co/+wPM0-1u

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Travelers @ Cardinals
END:VALARM
DTSTART:20180428T001000Z
DTEND:20180428T031000Z
UID:uyRx5ZxSkwdj-HnI7Bh4FF5V@stanza.co
SUMMARY:Travelers @ Cardinals
DESCRIPTION:Travelers @ Cardinals\n\nFollow on MiLB First Pitch: https://stza.co/+wPM0-36\n\nShop: https://stza.co/+wPM0-1u\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144501Z
LAST-MODIFIED:20180213T144501Z
TRANSP:OPAQUE
END:VEVENT
* Travelers @ Cardinals
<2018-04-28 Sat 16:10-19:10>
:PROPERTIES:
:ID:       CaOA_U1LtzlJhWwRQoKSGo8e@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Travelers @ Cardinals Travelers @ Cardinals

Follow on MiLB First Pitch  https //stza.co/+wPM1-1O

Shop  https //stza.co/+wPM1-1W

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Travelers @ Cardinals
END:VALARM
DTSTART:20180428T211000Z
DTEND:20180429T001000Z
UID:CaOA_U1LtzlJhWwRQoKSGo8e@stanza.co
SUMMARY:Travelers @ Cardinals
DESCRIPTION:Travelers @ Cardinals\n\nFollow on MiLB First Pitch: https://stza.co/+wPM1-1O\n\nShop: https://stza.co/+wPM1-1W\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144501Z
LAST-MODIFIED:20180213T144501Z
TRANSP:OPAQUE
END:VEVENT
* Travelers @ Cardinals
<2018-04-29 Sun 14:10-17:10>
:PROPERTIES:
:ID:       bZF3zLykEhZ8WqMy5ZHrBpPL@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Travelers @ Cardinals Travelers @ Cardinals

Follow on MiLB First Pitch  https //stza.co/+wPM2-1B

Shop  https //stza.co/+wPM2-2d

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Travelers @ Cardinals
END:VALARM
DTSTART:20180429T191000Z
DTEND:20180429T221000Z
UID:bZF3zLykEhZ8WqMy5ZHrBpPL@stanza.co
SUMMARY:Travelers @ Cardinals
DESCRIPTION:Travelers @ Cardinals\n\nFollow on MiLB First Pitch: https://stza.co/+wPM2-1B\n\nShop: https://stza.co/+wPM2-2d\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144501Z
LAST-MODIFIED:20180213T144501Z
TRANSP:OPAQUE
END:VEVENT
* Travelers @ Cardinals
<2018-04-30 Mon 11:10-14:10>
:PROPERTIES:
:ID:       SXbmJhpkgurRg6N7AhTIGMZ1@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Travelers @ Cardinals Travelers @ Cardinals

Follow on MiLB First Pitch  https //stza.co/+wPM3-z

Shop  https //stza.co/+wPM3-U

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Travelers @ Cardinals
END:VALARM
DTSTART:20180430T161000Z
DTEND:20180430T191000Z
UID:SXbmJhpkgurRg6N7AhTIGMZ1@stanza.co
SUMMARY:Travelers @ Cardinals
DESCRIPTION:Travelers @ Cardinals\n\nFollow on MiLB First Pitch: https://stza.co/+wPM3-z\n\nShop: https://stza.co/+wPM3-U\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144501Z
LAST-MODIFIED:20180213T144501Z
TRANSP:OPAQUE
END:VEVENT
* Travelers @ Drillers
<2018-05-01 Tue 19:05-22:05>
:PROPERTIES:
:ID:       dg5FUz1IgJMwrP9OCKJ58IWB@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Travelers @ Drillers Travelers @ Drillers

Follow on MiLB First Pitch  https //stza.co/+v$VE-18

Shop  https //stza.co/+v$VE-c

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Travelers @ Drillers
END:VALARM
DTSTART:20180502T000500Z
DTEND:20180502T030500Z
UID:dg5FUz1IgJMwrP9OCKJ58IWB@stanza.co
SUMMARY:Travelers @ Drillers
DESCRIPTION:Travelers @ Drillers\n\nFollow on MiLB First Pitch: https://stza.co/+v$VE-18\n\nShop: https://stza.co/+v$VE-c\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144501Z
LAST-MODIFIED:20180213T144501Z
TRANSP:OPAQUE
END:VEVENT
* Travelers @ Drillers
<2018-05-02 Wed 12:05-15:05>
:PROPERTIES:
:ID:       m34W2x2vEmlA3Go0G1v8s3t_@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Travelers @ Drillers Travelers @ Drillers

Follow on MiLB First Pitch  https //stza.co/+v$VF-1X

Shop  https //stza.co/+v$VF-3v

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Travelers @ Drillers
END:VALARM
DTSTART:20180502T170500Z
DTEND:20180502T200500Z
UID:m34W2x2vEmlA3Go0G1v8s3t_@stanza.co
SUMMARY:Travelers @ Drillers
DESCRIPTION:Travelers @ Drillers\n\nFollow on MiLB First Pitch: https://stza.co/+v$VF-1X\n\nShop: https://stza.co/+v$VF-3v\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144501Z
LAST-MODIFIED:20180213T144501Z
TRANSP:OPAQUE
END:VEVENT
* Travelers @ Drillers
<2018-05-03 Thu 19:05-22:05>
:PROPERTIES:
:ID:       7KqIfsJByVIKTDiOzqH3ZOGA@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Travelers @ Drillers Travelers @ Drillers

Follow on MiLB First Pitch  https //stza.co/+v$VG-1v

Shop  https //stza.co/+v$VG-1Q

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Travelers @ Drillers
END:VALARM
DTSTART:20180504T000500Z
DTEND:20180504T030500Z
UID:7KqIfsJByVIKTDiOzqH3ZOGA@stanza.co
SUMMARY:Travelers @ Drillers
DESCRIPTION:Travelers @ Drillers\n\nFollow on MiLB First Pitch: https://stza.co/+v$VG-1v\n\nShop: https://stza.co/+v$VG-1Q\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144501Z
LAST-MODIFIED:20180213T144501Z
TRANSP:OPAQUE
END:VEVENT
* Travelers @ Drillers
<2018-05-04 Fri 19:05-22:05>
:PROPERTIES:
:ID:       26cs_ULYS-1x9drXIGyp3U73@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Travelers @ Drillers Travelers @ Drillers

Follow on MiLB First Pitch  https //stza.co/+v$VH-3Z

Shop  https //stza.co/+v$VH-2i

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Travelers @ Drillers
END:VALARM
DTSTART:20180505T000500Z
DTEND:20180505T030500Z
UID:26cs_ULYS-1x9drXIGyp3U73@stanza.co
SUMMARY:Travelers @ Drillers
DESCRIPTION:Travelers @ Drillers\n\nFollow on MiLB First Pitch: https://stza.co/+v$VH-3Z\n\nShop: https://stza.co/+v$VH-2i\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144501Z
LAST-MODIFIED:20180213T144501Z
TRANSP:OPAQUE
END:VEVENT
* Travelers vs. Naturals
<2018-05-05 Sat 17:30-20:30>
:PROPERTIES:
:ID:       hbdhC_M5rqpsLqVWAUBDuxKi@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Travelers vs. Naturals Travelers vs. Naturals

Follow on MiLB First Pitch  https //stza.co/+v$T2-2

Shop  https //stza.co/+v$T2-2c

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Travelers vs. Naturals
END:VALARM
DTSTART:20180505T223000Z
DTEND:20180506T013000Z
UID:hbdhC_M5rqpsLqVWAUBDuxKi@stanza.co
SUMMARY:Travelers vs. Naturals
DESCRIPTION:Travelers vs. Naturals\n\nFollow on MiLB First Pitch: https://stza.co/+v$T2-2\n\nShop: https://stza.co/+v$T2-2c\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144501Z
LAST-MODIFIED:20180213T144501Z
TRANSP:OPAQUE
END:VEVENT
* Travelers vs. Naturals
<2018-05-06 Sun 14:10-17:10>
:PROPERTIES:
:ID:       00QtuTwIGlpgW1EfAhj51Nn4@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Travelers vs. Naturals Travelers vs. Naturals

Follow on MiLB First Pitch  https //stza.co/+v$T4-1b

Shop  https //stza.co/+v$T4-1M

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Travelers vs. Naturals
END:VALARM
DTSTART:20180506T191000Z
DTEND:20180506T221000Z
UID:00QtuTwIGlpgW1EfAhj51Nn4@stanza.co
SUMMARY:Travelers vs. Naturals
DESCRIPTION:Travelers vs. Naturals\n\nFollow on MiLB First Pitch: https://stza.co/+v$T4-1b\n\nShop: https://stza.co/+v$T4-1M\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144501Z
LAST-MODIFIED:20180213T144501Z
TRANSP:OPAQUE
END:VEVENT
* Travelers vs. Naturals
<2018-05-07 Mon 19:10-22:10>
:PROPERTIES:
:ID:       pyx1Odp5qUGMorjRYpq_GoOb@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Travelers vs. Naturals Travelers vs. Naturals

Follow on MiLB First Pitch  https //stza.co/+v$T6-3d

Shop  https //stza.co/+v$T6-39

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Travelers vs. Naturals
END:VALARM
DTSTART:20180508T001000Z
DTEND:20180508T031000Z
UID:pyx1Odp5qUGMorjRYpq_GoOb@stanza.co
SUMMARY:Travelers vs. Naturals
DESCRIPTION:Travelers vs. Naturals\n\nFollow on MiLB First Pitch: https://stza.co/+v$T6-3d\n\nShop: https://stza.co/+v$T6-39\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144501Z
LAST-MODIFIED:20180213T144501Z
TRANSP:OPAQUE
END:VEVENT
* Travelers vs. Naturals
<2018-05-08 Tue 19:10-22:10>
:PROPERTIES:
:ID:       Ehbq2m3Un33twBfkK983ixuX@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Travelers vs. Naturals Travelers vs. Naturals

Follow on MiLB First Pitch  https //stza.co/+v$T9-2N

Shop  https //stza.co/+v$T9-3G

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Travelers vs. Naturals
END:VALARM
DTSTART:20180509T001000Z
DTEND:20180509T031000Z
UID:Ehbq2m3Un33twBfkK983ixuX@stanza.co
SUMMARY:Travelers vs. Naturals
DESCRIPTION:Travelers vs. Naturals\n\nFollow on MiLB First Pitch: https://stza.co/+v$T9-2N\n\nShop: https://stza.co/+v$T9-3G\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144501Z
LAST-MODIFIED:20180213T144501Z
TRANSP:OPAQUE
END:VEVENT
* Travelers vs. Cardinals
<2018-05-10 Thu 19:10-22:10>
:PROPERTIES:
:ID:       xqSEOOUTWfptXoSxRJqIxhRf@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Travelers vs. Cardinals Travelers vs. Cardinals

Follow on MiLB First Pitch  https //stza.co/+v$Ta-1m

Shop  https //stza.co/+v$Ta-L

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Travelers vs. Cardinals
END:VALARM
DTSTART:20180511T001000Z
DTEND:20180511T031000Z
UID:xqSEOOUTWfptXoSxRJqIxhRf@stanza.co
SUMMARY:Travelers vs. Cardinals
DESCRIPTION:Travelers vs. Cardinals\n\nFollow on MiLB First Pitch: https://stza.co/+v$Ta-1m\n\nShop: https://stza.co/+v$Ta-L\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144501Z
LAST-MODIFIED:20180213T144501Z
TRANSP:OPAQUE
END:VEVENT
* Travelers vs. Cardinals
<2018-05-11 Fri 19:10-22:10>
:PROPERTIES:
:ID:       u1qvbIJns_IJOilR7jQYxqLD@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Travelers vs. Cardinals Travelers vs. Cardinals

Follow on MiLB First Pitch  https //stza.co/+v$Td-O

Shop  https //stza.co/+v$Td-2p

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Travelers vs. Cardinals
END:VALARM
DTSTART:20180512T001000Z
DTEND:20180512T031000Z
UID:u1qvbIJns_IJOilR7jQYxqLD@stanza.co
SUMMARY:Travelers vs. Cardinals
DESCRIPTION:Travelers vs. Cardinals\n\nFollow on MiLB First Pitch: https://stza.co/+v$Td-O\n\nShop: https://stza.co/+v$Td-2p\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144501Z
LAST-MODIFIED:20180213T144501Z
TRANSP:OPAQUE
END:VEVENT
* Travelers vs. Cardinals
<2018-05-12 Sat 18:10-21:10>
:PROPERTIES:
:ID:       xtm2GqIERtY2nXKnQsXbthSD@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Travelers vs. Cardinals Travelers vs. Cardinals

Follow on MiLB First Pitch  https //stza.co/+v$Tf-2s

Shop  https //stza.co/+v$Tf-1m

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Travelers vs. Cardinals
END:VALARM
DTSTART:20180512T231000Z
DTEND:20180513T021000Z
UID:xtm2GqIERtY2nXKnQsXbthSD@stanza.co
SUMMARY:Travelers vs. Cardinals
DESCRIPTION:Travelers vs. Cardinals\n\nFollow on MiLB First Pitch: https://stza.co/+v$Tf-2s\n\nShop: https://stza.co/+v$Tf-1m\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144501Z
LAST-MODIFIED:20180213T144501Z
TRANSP:OPAQUE
END:VEVENT
* Travelers vs. Cardinals
<2018-05-13 Sun 14:10-17:10>
:PROPERTIES:
:ID:       hfchsG7xsqqgnGtsfCeLXZyJ@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Travelers vs. Cardinals Travelers vs. Cardinals

Follow on MiLB First Pitch  https //stza.co/+v$Th-z

Shop  https //stza.co/+v$Th-2Q

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Travelers vs. Cardinals
END:VALARM
DTSTART:20180513T191000Z
DTEND:20180513T221000Z
UID:hfchsG7xsqqgnGtsfCeLXZyJ@stanza.co
SUMMARY:Travelers vs. Cardinals
DESCRIPTION:Travelers vs. Cardinals\n\nFollow on MiLB First Pitch: https://stza.co/+v$Th-z\n\nShop: https://stza.co/+v$Th-2Q\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144501Z
LAST-MODIFIED:20180213T144501Z
TRANSP:OPAQUE
END:VEVENT
* Travelers @ Naturals
<2018-05-14 Mon 19:05-22:05>
:PROPERTIES:
:ID:       AYjugqg21OQPYmMxlDpBMoxE@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Travelers @ Naturals Travelers @ Naturals

Follow on MiLB First Pitch  https //stza.co/+wh$t-3t

Shop  https //stza.co/+wh$t-1t

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Travelers @ Naturals
END:VALARM
DTSTART:20180515T000500Z
DTEND:20180515T030500Z
UID:AYjugqg21OQPYmMxlDpBMoxE@stanza.co
SUMMARY:Travelers @ Naturals
DESCRIPTION:Travelers @ Naturals\n\nFollow on MiLB First Pitch: https://stza.co/+wh$t-3t\n\nShop: https://stza.co/+wh$t-1t\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144501Z
LAST-MODIFIED:20180213T144501Z
TRANSP:OPAQUE
END:VEVENT
* Travelers @ Naturals
<2018-05-15 Tue 19:05-22:05>
:PROPERTIES:
:ID:       zlk3uon4c5y2k08sW7wJ0Wau@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Travelers @ Naturals Travelers @ Naturals

Follow on MiLB First Pitch  https //stza.co/+wh$u-1a

Shop  https //stza.co/+wh$u-2I

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Travelers @ Naturals
END:VALARM
DTSTART:20180516T000500Z
DTEND:20180516T030500Z
UID:zlk3uon4c5y2k08sW7wJ0Wau@stanza.co
SUMMARY:Travelers @ Naturals
DESCRIPTION:Travelers @ Naturals\n\nFollow on MiLB First Pitch: https://stza.co/+wh$u-1a\n\nShop: https://stza.co/+wh$u-2I\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144501Z
LAST-MODIFIED:20180213T144501Z
TRANSP:OPAQUE
END:VEVENT
* Travelers @ Naturals
<2018-05-16 Wed 11:05-14:05>
:PROPERTIES:
:ID:       hyiA9aG4xQoFYClsp4k2dMLb@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Travelers @ Naturals Travelers @ Naturals

Follow on MiLB First Pitch  https //stza.co/+wh$v-1F

Shop  https //stza.co/+wh$v-1v

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Travelers @ Naturals
END:VALARM
DTSTART:20180516T160500Z
DTEND:20180516T190500Z
UID:hyiA9aG4xQoFYClsp4k2dMLb@stanza.co
SUMMARY:Travelers @ Naturals
DESCRIPTION:Travelers @ Naturals\n\nFollow on MiLB First Pitch: https://stza.co/+wh$v-1F\n\nShop: https://stza.co/+wh$v-1v\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144501Z
LAST-MODIFIED:20180213T144501Z
TRANSP:OPAQUE
END:VEVENT
* Travelers @ Naturals
<2018-05-17 Thu 19:05-22:05>
:PROPERTIES:
:ID:       8t7yWZipM8gPvKz5zWnWSSbr@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Travelers @ Naturals Travelers @ Naturals

Follow on MiLB First Pitch  https //stza.co/+wh$w-P

Shop  https //stza.co/+wh$w-3I

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Travelers @ Naturals
END:VALARM
DTSTART:20180518T000500Z
DTEND:20180518T030500Z
UID:8t7yWZipM8gPvKz5zWnWSSbr@stanza.co
SUMMARY:Travelers @ Naturals
DESCRIPTION:Travelers @ Naturals\n\nFollow on MiLB First Pitch: https://stza.co/+wh$w-P\n\nShop: https://stza.co/+wh$w-3I\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144501Z
LAST-MODIFIED:20180213T144501Z
TRANSP:OPAQUE
END:VEVENT
* Travelers @ Drillers
<2018-05-18 Fri 19:05-22:05>
:PROPERTIES:
:ID:       4diVXNUxTlAMogx4t3Cek8Zo@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Travelers @ Drillers Travelers @ Drillers

Follow on MiLB First Pitch  https //stza.co/+v$VI-1h

Shop  https //stza.co/+v$VI-3G

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Travelers @ Drillers
END:VALARM
DTSTART:20180519T000500Z
DTEND:20180519T030500Z
UID:4diVXNUxTlAMogx4t3Cek8Zo@stanza.co
SUMMARY:Travelers @ Drillers
DESCRIPTION:Travelers @ Drillers\n\nFollow on MiLB First Pitch: https://stza.co/+v$VI-1h\n\nShop: https://stza.co/+v$VI-3G\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144501Z
LAST-MODIFIED:20180213T144501Z
TRANSP:OPAQUE
END:VEVENT
* Travelers @ Drillers
<2018-05-19 Sat 19:05-22:05>
:PROPERTIES:
:ID:       b6Og09S4nTfbCQv3Af4zv0mE@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Travelers @ Drillers Travelers @ Drillers

Follow on MiLB First Pitch  https //stza.co/+v$VJ-2Z

Shop  https //stza.co/+v$VJ-3u

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Travelers @ Drillers
END:VALARM
DTSTART:20180520T000500Z
DTEND:20180520T030500Z
UID:b6Og09S4nTfbCQv3Af4zv0mE@stanza.co
SUMMARY:Travelers @ Drillers
DESCRIPTION:Travelers @ Drillers\n\nFollow on MiLB First Pitch: https://stza.co/+v$VJ-2Z\n\nShop: https://stza.co/+v$VJ-3u\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144501Z
LAST-MODIFIED:20180213T144501Z
TRANSP:OPAQUE
END:VEVENT
* Travelers @ Drillers
<2018-05-20 Sun 13:05-16:05>
:PROPERTIES:
:ID:       cPjXNnUsyjqWOqD7pwAgwki3@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Travelers @ Drillers Travelers @ Drillers

Follow on MiLB First Pitch  https //stza.co/+v$VK-I

Shop  https //stza.co/+v$VK-3M

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Travelers @ Drillers
END:VALARM
DTSTART:20180520T180500Z
DTEND:20180520T210500Z
UID:cPjXNnUsyjqWOqD7pwAgwki3@stanza.co
SUMMARY:Travelers @ Drillers
DESCRIPTION:Travelers @ Drillers\n\nFollow on MiLB First Pitch: https://stza.co/+v$VK-I\n\nShop: https://stza.co/+v$VK-3M\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144501Z
LAST-MODIFIED:20180213T144501Z
TRANSP:OPAQUE
END:VEVENT
* Travelers @ Drillers
<2018-05-21 Mon 12:05-15:05>
:PROPERTIES:
:ID:       QeuUpV61MGYdJFa_gHGeyoZx@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Travelers @ Drillers Travelers @ Drillers

Follow on MiLB First Pitch  https //stza.co/+v$VL-2m

Shop  https //stza.co/+v$VL-3u

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Travelers @ Drillers
END:VALARM
DTSTART:20180521T170500Z
DTEND:20180521T200500Z
UID:QeuUpV61MGYdJFa_gHGeyoZx@stanza.co
SUMMARY:Travelers @ Drillers
DESCRIPTION:Travelers @ Drillers\n\nFollow on MiLB First Pitch: https://stza.co/+v$VL-2m\n\nShop: https://stza.co/+v$VL-3u\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144501Z
LAST-MODIFIED:20180213T144501Z
TRANSP:OPAQUE
END:VEVENT
* Travelers vs. RockHounds
<2018-05-22 Tue 19:10-22:10>
:PROPERTIES:
:ID:       deDQvrCsO-PZqf1vvpt-fZog@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Travelers vs. RockHounds Travelers vs. RockHounds

Follow on MiLB First Pitch  https //stza.co/+v$Ti-

Shop  https //stza.co/+v$Ti-2K

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Travelers vs. RockHounds
END:VALARM
DTSTART:20180523T001000Z
DTEND:20180523T031000Z
UID:deDQvrCsO-PZqf1vvpt-fZog@stanza.co
SUMMARY:Travelers vs. RockHounds
DESCRIPTION:Travelers vs. RockHounds\n\nFollow on MiLB First Pitch: https://stza.co/+v$Ti-\n\nShop: https://stza.co/+v$Ti-2K\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144501Z
LAST-MODIFIED:20180213T144501Z
TRANSP:OPAQUE
END:VEVENT
* Travelers vs. RockHounds
<2018-05-23 Wed 19:10-22:10>
:PROPERTIES:
:ID:       94r6MiOd8kUc4-DuhGcaoMHY@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Travelers vs. RockHounds Travelers vs. RockHounds

Follow on MiLB First Pitch  https //stza.co/+v$Tl-2W

Shop  https //stza.co/+v$Tl-x

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Travelers vs. RockHounds
END:VALARM
DTSTART:20180524T001000Z
DTEND:20180524T031000Z
UID:94r6MiOd8kUc4-DuhGcaoMHY@stanza.co
SUMMARY:Travelers vs. RockHounds
DESCRIPTION:Travelers vs. RockHounds\n\nFollow on MiLB First Pitch: https://stza.co/+v$Tl-2W\n\nShop: https://stza.co/+v$Tl-x\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144501Z
LAST-MODIFIED:20180213T144501Z
TRANSP:OPAQUE
END:VEVENT
* Travelers vs. RockHounds
<2018-05-24 Thu 19:10-22:10>
:PROPERTIES:
:ID:       vPw0YvvCkoVomz43G9hr7V3l@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Travelers vs. RockHounds Travelers vs. RockHounds

Follow on MiLB First Pitch  https //stza.co/+v$Tm-29

Shop  https //stza.co/+v$Tm-3I

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Travelers vs. RockHounds
END:VALARM
DTSTART:20180525T001000Z
DTEND:20180525T031000Z
UID:vPw0YvvCkoVomz43G9hr7V3l@stanza.co
SUMMARY:Travelers vs. RockHounds
DESCRIPTION:Travelers vs. RockHounds\n\nFollow on MiLB First Pitch: https://stza.co/+v$Tm-29\n\nShop: https://stza.co/+v$Tm-3I\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144501Z
LAST-MODIFIED:20180213T144501Z
TRANSP:OPAQUE
END:VEVENT
* Travelers vs. RoughRiders
<2018-05-25 Fri 19:10-22:10>
:PROPERTIES:
:ID:       mvNhIY1hvbX6cUB6ApzByDQZ@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Travelers vs. RoughRiders Travelers vs. RoughRiders

Follow on MiLB First Pitch  https //stza.co/+v$Tp-1F

Shop  https //stza.co/+v$Tp-1Q

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Travelers vs. RoughRiders
END:VALARM
DTSTART:20180526T001000Z
DTEND:20180526T031000Z
UID:mvNhIY1hvbX6cUB6ApzByDQZ@stanza.co
SUMMARY:Travelers vs. RoughRiders
DESCRIPTION:Travelers vs. RoughRiders\n\nFollow on MiLB First Pitch: https://stza.co/+v$Tp-1F\n\nShop: https://stza.co/+v$Tp-1Q\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144501Z
LAST-MODIFIED:20180213T144501Z
TRANSP:OPAQUE
END:VEVENT
* Travelers vs. RoughRiders
<2018-05-26 Sat 18:10-21:10>
:PROPERTIES:
:ID:       WOfRqfQVBn3dIa3-QpC2cXw2@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Travelers vs. RoughRiders Travelers vs. RoughRiders

Follow on MiLB First Pitch  https //stza.co/+v$Tq-30

Shop  https //stza.co/+v$Tq-1l

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Travelers vs. RoughRiders
END:VALARM
DTSTART:20180526T231000Z
DTEND:20180527T021000Z
UID:WOfRqfQVBn3dIa3-QpC2cXw2@stanza.co
SUMMARY:Travelers vs. RoughRiders
DESCRIPTION:Travelers vs. RoughRiders\n\nFollow on MiLB First Pitch: https://stza.co/+v$Tq-30\n\nShop: https://stza.co/+v$Tq-1l\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144501Z
LAST-MODIFIED:20180213T144501Z
TRANSP:OPAQUE
END:VEVENT
* Travelers vs. RoughRiders
<2018-05-27 Sun 14:10-17:10>
:PROPERTIES:
:ID:       w-zfTz1Zx8BnutehUKS-xQDS@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Travelers vs. RoughRiders Travelers vs. RoughRiders

Follow on MiLB First Pitch  https //stza.co/+v$Ts-I

Shop  https //stza.co/+v$Ts-2b

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Travelers vs. RoughRiders
END:VALARM
DTSTART:20180527T191000Z
DTEND:20180527T221000Z
UID:w-zfTz1Zx8BnutehUKS-xQDS@stanza.co
SUMMARY:Travelers vs. RoughRiders
DESCRIPTION:Travelers vs. RoughRiders\n\nFollow on MiLB First Pitch: https://stza.co/+v$Ts-I\n\nShop: https://stza.co/+v$Ts-2b\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144501Z
LAST-MODIFIED:20180213T144501Z
TRANSP:OPAQUE
END:VEVENT
* Travelers @ RockHounds
<2018-05-29 Tue 18:30-21:30>
:PROPERTIES:
:ID:       xK_jM6qqP2xMbagDk0l7mUxR@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Travelers @ RockHounds Travelers @ RockHounds

Follow on MiLB First Pitch  https //stza.co/+wX0Y-J

Shop  https //stza.co/+wX0Y-c

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Travelers @ RockHounds
END:VALARM
DTSTART:20180529T233000Z
DTEND:20180530T023000Z
UID:xK_jM6qqP2xMbagDk0l7mUxR@stanza.co
SUMMARY:Travelers @ RockHounds
DESCRIPTION:Travelers @ RockHounds\n\nFollow on MiLB First Pitch: https://stza.co/+wX0Y-J\n\nShop: https://stza.co/+wX0Y-c\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144501Z
LAST-MODIFIED:20180213T144501Z
TRANSP:OPAQUE
END:VEVENT
* Travelers @ RockHounds
<2018-05-30 Wed 18:30-21:30>
:PROPERTIES:
:ID:       ZUzG5VdrrBSTB7BC01OSHFAN@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Travelers @ RockHounds Travelers @ RockHounds

Follow on MiLB First Pitch  https //stza.co/+wX0Z-1c

Shop  https //stza.co/+wX0Z-2W

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Travelers @ RockHounds
END:VALARM
DTSTART:20180530T233000Z
DTEND:20180531T023000Z
UID:ZUzG5VdrrBSTB7BC01OSHFAN@stanza.co
SUMMARY:Travelers @ RockHounds
DESCRIPTION:Travelers @ RockHounds\n\nFollow on MiLB First Pitch: https://stza.co/+wX0Z-1c\n\nShop: https://stza.co/+wX0Z-2W\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144501Z
LAST-MODIFIED:20180213T144501Z
TRANSP:OPAQUE
END:VEVENT
* Travelers @ RockHounds
<2018-05-31 Thu 19:00-22:00>
:PROPERTIES:
:ID:       EZIQHLNey-TaRjrOoPtwuH8E@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Travelers @ RockHounds Travelers @ RockHounds

Follow on MiLB First Pitch  https //stza.co/+wX0_-N

Shop  https //stza.co/+wX0_-2q

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Travelers @ RockHounds
END:VALARM
DTSTART:20180601T000000Z
DTEND:20180601T030000Z
UID:EZIQHLNey-TaRjrOoPtwuH8E@stanza.co
SUMMARY:Travelers @ RockHounds
DESCRIPTION:Travelers @ RockHounds\n\nFollow on MiLB First Pitch: https://stza.co/+wX0_-N\n\nShop: https://stza.co/+wX0_-2q\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144501Z
LAST-MODIFIED:20180213T144501Z
TRANSP:OPAQUE
END:VEVENT
* Travelers @ RoughRiders
<2018-06-01 Fri 19:05-22:05>
:PROPERTIES:
:ID:       vDIowjHrlACj7mlQ0hnE4qbM@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Travelers @ RoughRiders Travelers @ RoughRiders

Follow on MiLB First Pitch  https //stza.co/+wY6Q-21

Shop  https //stza.co/+wY6Q-C

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Travelers @ RoughRiders
END:VALARM
DTSTART:20180602T000500Z
DTEND:20180602T030500Z
UID:vDIowjHrlACj7mlQ0hnE4qbM@stanza.co
SUMMARY:Travelers @ RoughRiders
DESCRIPTION:Travelers @ RoughRiders\n\nFollow on MiLB First Pitch: https://stza.co/+wY6Q-21\n\nShop: https://stza.co/+wY6Q-C\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144501Z
LAST-MODIFIED:20180213T144501Z
TRANSP:OPAQUE
END:VEVENT
* Travelers @ RoughRiders
<2018-06-02 Sat 19:05-22:05>
:PROPERTIES:
:ID:       G94CrKEh9yHyu_R1CF1zAW33@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Travelers @ RoughRiders Travelers @ RoughRiders

Follow on MiLB First Pitch  https //stza.co/+wY6S-3K

Shop  https //stza.co/+wY6S-32

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Travelers @ RoughRiders
END:VALARM
DTSTART:20180603T000500Z
DTEND:20180603T030500Z
UID:G94CrKEh9yHyu_R1CF1zAW33@stanza.co
SUMMARY:Travelers @ RoughRiders
DESCRIPTION:Travelers @ RoughRiders\n\nFollow on MiLB First Pitch: https://stza.co/+wY6S-3K\n\nShop: https://stza.co/+wY6S-32\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144501Z
LAST-MODIFIED:20180213T144501Z
TRANSP:OPAQUE
END:VEVENT
* Travelers @ RoughRiders
<2018-06-03 Sun 19:05-22:05>
:PROPERTIES:
:ID:       IZNa6eHYTtFMPIwjGWUCuQil@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Travelers @ RoughRiders Travelers @ RoughRiders

Follow on MiLB First Pitch  https //stza.co/+wY6U-1j

Shop  https //stza.co/+wY6U-38

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Travelers @ RoughRiders
END:VALARM
DTSTART:20180604T000500Z
DTEND:20180604T030500Z
UID:IZNa6eHYTtFMPIwjGWUCuQil@stanza.co
SUMMARY:Travelers @ RoughRiders
DESCRIPTION:Travelers @ RoughRiders\n\nFollow on MiLB First Pitch: https://stza.co/+wY6U-1j\n\nShop: https://stza.co/+wY6U-38\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144501Z
LAST-MODIFIED:20180213T144501Z
TRANSP:OPAQUE
END:VEVENT
* Travelers vs. Drillers
<2018-06-05 Tue 19:10-22:10>
:PROPERTIES:
:ID:       pi1NdVZa844wKnTmxe0WMceL@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Travelers vs. Drillers Travelers vs. Drillers

Follow on MiLB First Pitch  https //stza.co/+v$Tv-2V

Shop  https //stza.co/+v$Tv-d

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Travelers vs. Drillers
END:VALARM
DTSTART:20180606T001000Z
DTEND:20180606T031000Z
UID:pi1NdVZa844wKnTmxe0WMceL@stanza.co
SUMMARY:Travelers vs. Drillers
DESCRIPTION:Travelers vs. Drillers\n\nFollow on MiLB First Pitch: https://stza.co/+v$Tv-2V\n\nShop: https://stza.co/+v$Tv-d\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144501Z
LAST-MODIFIED:20180213T144501Z
TRANSP:OPAQUE
END:VEVENT
* Travelers vs. Drillers
<2018-06-06 Wed 19:10-22:10>
:PROPERTIES:
:ID:       DmjoAKvMTPA-zEN3UElp9673@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Travelers vs. Drillers Travelers vs. Drillers

Follow on MiLB First Pitch  https //stza.co/+v$Tw-2Y

Shop  https //stza.co/+v$Tw-1X

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Travelers vs. Drillers
END:VALARM
DTSTART:20180607T001000Z
DTEND:20180607T031000Z
UID:DmjoAKvMTPA-zEN3UElp9673@stanza.co
SUMMARY:Travelers vs. Drillers
DESCRIPTION:Travelers vs. Drillers\n\nFollow on MiLB First Pitch: https://stza.co/+v$Tw-2Y\n\nShop: https://stza.co/+v$Tw-1X\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144501Z
LAST-MODIFIED:20180213T144501Z
TRANSP:OPAQUE
END:VEVENT
* Travelers vs. Drillers
<2018-06-07 Thu 19:10-22:10>
:PROPERTIES:
:ID:       SKb8_yFY-hEr5ycDITx1yKxt@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Travelers vs. Drillers Travelers vs. Drillers

Follow on MiLB First Pitch  https //stza.co/+v$Tz-3U

Shop  https //stza.co/+v$Tz-2

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Travelers vs. Drillers
END:VALARM
DTSTART:20180608T001000Z
DTEND:20180608T031000Z
UID:SKb8_yFY-hEr5ycDITx1yKxt@stanza.co
SUMMARY:Travelers vs. Drillers
DESCRIPTION:Travelers vs. Drillers\n\nFollow on MiLB First Pitch: https://stza.co/+v$Tz-3U\n\nShop: https://stza.co/+v$Tz-2\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144501Z
LAST-MODIFIED:20180213T144501Z
TRANSP:OPAQUE
END:VEVENT
* Travelers vs. Drillers
<2018-06-08 Fri 19:10-22:10>
:PROPERTIES:
:ID:       aotAzUIEzIVW4XKEn-BIVePs@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Travelers vs. Drillers Travelers vs. Drillers

Follow on MiLB First Pitch  https //stza.co/+v$TA-I

Shop  https //stza.co/+v$TA-3B

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Travelers vs. Drillers
END:VALARM
DTSTART:20180609T001000Z
DTEND:20180609T031000Z
UID:aotAzUIEzIVW4XKEn-BIVePs@stanza.co
SUMMARY:Travelers vs. Drillers
DESCRIPTION:Travelers vs. Drillers\n\nFollow on MiLB First Pitch: https://stza.co/+v$TA-I\n\nShop: https://stza.co/+v$TA-3B\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144501Z
LAST-MODIFIED:20180213T144501Z
TRANSP:OPAQUE
END:VEVENT
* Travelers vs. Naturals
<2018-06-09 Sat 18:10-21:10>
:PROPERTIES:
:ID:       GLAGX0cc4vcheel8bt574-Uv@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Travelers vs. Naturals Travelers vs. Naturals

Follow on MiLB First Pitch  https //stza.co/+v$TD-2A

Shop  https //stza.co/+v$TD-2d

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Travelers vs. Naturals
END:VALARM
DTSTART:20180609T231000Z
DTEND:20180610T021000Z
UID:GLAGX0cc4vcheel8bt574-Uv@stanza.co
SUMMARY:Travelers vs. Naturals
DESCRIPTION:Travelers vs. Naturals\n\nFollow on MiLB First Pitch: https://stza.co/+v$TD-2A\n\nShop: https://stza.co/+v$TD-2d\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144501Z
LAST-MODIFIED:20180213T144501Z
TRANSP:OPAQUE
END:VEVENT
* Travelers vs. Naturals
<2018-06-10 Sun 14:10-17:10>
:PROPERTIES:
:ID:       AwBRcQDOLbBloL_cqhe1Ts0i@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Travelers vs. Naturals Travelers vs. Naturals

Follow on MiLB First Pitch  https //stza.co/+v$TE-v

Shop  https //stza.co/+v$TE-24

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Travelers vs. Naturals
END:VALARM
DTSTART:20180610T191000Z
DTEND:20180610T221000Z
UID:AwBRcQDOLbBloL_cqhe1Ts0i@stanza.co
SUMMARY:Travelers vs. Naturals
DESCRIPTION:Travelers vs. Naturals\n\nFollow on MiLB First Pitch: https://stza.co/+v$TE-v\n\nShop: https://stza.co/+v$TE-24\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144501Z
LAST-MODIFIED:20180213T144501Z
TRANSP:OPAQUE
END:VEVENT
* Travelers vs. Naturals
<2018-06-11 Mon 19:10-22:10>
:PROPERTIES:
:ID:       _u5ioxBEaeBXss5wl-qUxlaX@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Travelers vs. Naturals Travelers vs. Naturals

Follow on MiLB First Pitch  https //stza.co/+v$TH-2c

Shop  https //stza.co/+v$TH-6

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Travelers vs. Naturals
END:VALARM
DTSTART:20180612T001000Z
DTEND:20180612T031000Z
UID:_u5ioxBEaeBXss5wl-qUxlaX@stanza.co
SUMMARY:Travelers vs. Naturals
DESCRIPTION:Travelers vs. Naturals\n\nFollow on MiLB First Pitch: https://stza.co/+v$TH-2c\n\nShop: https://stza.co/+v$TH-6\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144501Z
LAST-MODIFIED:20180213T144501Z
TRANSP:OPAQUE
END:VEVENT
* Travelers vs. Naturals
<2018-06-12 Tue 19:10-22:10>
:PROPERTIES:
:ID:       kF9NIYVGgBCP2PMCEsg2FOzJ@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Travelers vs. Naturals Travelers vs. Naturals

Follow on MiLB First Pitch  https //stza.co/+v$TI-8

Shop  https //stza.co/+v$TI-2x

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Travelers vs. Naturals
END:VALARM
DTSTART:20180613T001000Z
DTEND:20180613T031000Z
UID:kF9NIYVGgBCP2PMCEsg2FOzJ@stanza.co
SUMMARY:Travelers vs. Naturals
DESCRIPTION:Travelers vs. Naturals\n\nFollow on MiLB First Pitch: https://stza.co/+v$TI-8\n\nShop: https://stza.co/+v$TI-2x\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144501Z
LAST-MODIFIED:20180213T144501Z
TRANSP:OPAQUE
END:VEVENT
* Travelers @ Cardinals
<2018-06-13 Wed 18:30-21:30>
:PROPERTIES:
:ID:       -2M6Po0mdcwVQPk6r2JbZnIE@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Travelers @ Cardinals Travelers @ Cardinals

Follow on MiLB First Pitch  https //stza.co/+wPM4-3Z

Shop  https //stza.co/+wPM4-w

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Travelers @ Cardinals
END:VALARM
DTSTART:20180613T233000Z
DTEND:20180614T023000Z
UID:-2M6Po0mdcwVQPk6r2JbZnIE@stanza.co
SUMMARY:Travelers @ Cardinals
DESCRIPTION:Travelers @ Cardinals\n\nFollow on MiLB First Pitch: https://stza.co/+wPM4-3Z\n\nShop: https://stza.co/+wPM4-w\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144501Z
LAST-MODIFIED:20180213T144501Z
TRANSP:OPAQUE
END:VEVENT
* Travelers @ Cardinals
<2018-06-14 Thu 19:10-22:10>
:PROPERTIES:
:ID:       istvlp04BUrbJcdc4LOOjI_p@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Travelers @ Cardinals Travelers @ Cardinals

Follow on MiLB First Pitch  https //stza.co/+wPM5-7

Shop  https //stza.co/+wPM5-3n

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Travelers @ Cardinals
END:VALARM
DTSTART:20180615T001000Z
DTEND:20180615T031000Z
UID:istvlp04BUrbJcdc4LOOjI_p@stanza.co
SUMMARY:Travelers @ Cardinals
DESCRIPTION:Travelers @ Cardinals\n\nFollow on MiLB First Pitch: https://stza.co/+wPM5-7\n\nShop: https://stza.co/+wPM5-3n\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144501Z
LAST-MODIFIED:20180213T144501Z
TRANSP:OPAQUE
END:VEVENT
* Travelers @ Cardinals
<2018-06-15 Fri 19:10-22:10>
:PROPERTIES:
:ID:       BtBeSkYY2jZcnYvTBEp0GoX2@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Travelers @ Cardinals Travelers @ Cardinals

Follow on MiLB First Pitch  https //stza.co/+wPM7-1l

Shop  https //stza.co/+wPM7-2_

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Travelers @ Cardinals
END:VALARM
DTSTART:20180616T001000Z
DTEND:20180616T031000Z
UID:BtBeSkYY2jZcnYvTBEp0GoX2@stanza.co
SUMMARY:Travelers @ Cardinals
DESCRIPTION:Travelers @ Cardinals\n\nFollow on MiLB First Pitch: https://stza.co/+wPM7-1l\n\nShop: https://stza.co/+wPM7-2_\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144501Z
LAST-MODIFIED:20180213T144501Z
TRANSP:OPAQUE
END:VEVENT
* Travelers @ Cardinals
<2018-06-16 Sat 18:10-21:10>
:PROPERTIES:
:ID:       fFq5LYf-kqQ3KsQDObWJFunK@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Travelers @ Cardinals Travelers @ Cardinals

Follow on MiLB First Pitch  https //stza.co/+wPM8-2d

Shop  https //stza.co/+wPM8-3K

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Travelers @ Cardinals
END:VALARM
DTSTART:20180616T231000Z
DTEND:20180617T021000Z
UID:fFq5LYf-kqQ3KsQDObWJFunK@stanza.co
SUMMARY:Travelers @ Cardinals
DESCRIPTION:Travelers @ Cardinals\n\nFollow on MiLB First Pitch: https://stza.co/+wPM8-2d\n\nShop: https://stza.co/+wPM8-3K\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144501Z
LAST-MODIFIED:20180213T144501Z
TRANSP:OPAQUE
END:VEVENT
* Travelers @ Naturals
<2018-06-17 Sun 14:05-17:05>
:PROPERTIES:
:ID:       UGK7tTTkaX3mV09q--EXzMKe@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Travelers @ Naturals Travelers @ Naturals

Follow on MiLB First Pitch  https //stza.co/+wh$x-3s

Shop  https //stza.co/+wh$x-8

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Travelers @ Naturals
END:VALARM
DTSTART:20180617T190500Z
DTEND:20180617T220500Z
UID:UGK7tTTkaX3mV09q--EXzMKe@stanza.co
SUMMARY:Travelers @ Naturals
DESCRIPTION:Travelers @ Naturals\n\nFollow on MiLB First Pitch: https://stza.co/+wh$x-3s\n\nShop: https://stza.co/+wh$x-8\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144501Z
LAST-MODIFIED:20180213T144501Z
TRANSP:OPAQUE
END:VEVENT
* Travelers @ Naturals
<2018-06-18 Mon 19:05-22:05>
:PROPERTIES:
:ID:       qFOGEX6oNutv3-KSqab-uzNM@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Travelers @ Naturals Travelers @ Naturals

Follow on MiLB First Pitch  https //stza.co/+wh$y-L

Shop  https //stza.co/+wh$y-1a

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Travelers @ Naturals
END:VALARM
DTSTART:20180619T000500Z
DTEND:20180619T030500Z
UID:qFOGEX6oNutv3-KSqab-uzNM@stanza.co
SUMMARY:Travelers @ Naturals
DESCRIPTION:Travelers @ Naturals\n\nFollow on MiLB First Pitch: https://stza.co/+wh$y-L\n\nShop: https://stza.co/+wh$y-1a\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144501Z
LAST-MODIFIED:20180213T144501Z
TRANSP:OPAQUE
END:VEVENT
* Travelers @ Naturals
<2018-06-19 Tue 19:05-22:05>
:PROPERTIES:
:ID:       7hzkjLKxMx8G4NoreX5Eley-@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Travelers @ Naturals Travelers @ Naturals

Follow on MiLB First Pitch  https //stza.co/+wh$z-1O

Shop  https //stza.co/+wh$z-q

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Travelers @ Naturals
END:VALARM
DTSTART:20180620T000500Z
DTEND:20180620T030500Z
UID:7hzkjLKxMx8G4NoreX5Eley-@stanza.co
SUMMARY:Travelers @ Naturals
DESCRIPTION:Travelers @ Naturals\n\nFollow on MiLB First Pitch: https://stza.co/+wh$z-1O\n\nShop: https://stza.co/+wh$z-q\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144501Z
LAST-MODIFIED:20180213T144501Z
TRANSP:OPAQUE
END:VEVENT
* Travelers @ Naturals
<2018-06-20 Wed 12:05-15:05>
:PROPERTIES:
:ID:       Pb2VCzx9aKPR48sBYv8MJ1NC@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Travelers @ Naturals Travelers @ Naturals

Follow on MiLB First Pitch  https //stza.co/+wh$A-3W

Shop  https //stza.co/+wh$A-2Y

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Travelers @ Naturals
END:VALARM
DTSTART:20180620T170500Z
DTEND:20180620T200500Z
UID:Pb2VCzx9aKPR48sBYv8MJ1NC@stanza.co
SUMMARY:Travelers @ Naturals
DESCRIPTION:Travelers @ Naturals\n\nFollow on MiLB First Pitch: https://stza.co/+wh$A-3W\n\nShop: https://stza.co/+wh$A-2Y\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144501Z
LAST-MODIFIED:20180213T144501Z
TRANSP:OPAQUE
END:VEVENT
* Travelers @ Cardinals
<2018-06-21 Thu 19:10-22:10>
:PROPERTIES:
:ID:       AZkI6KTZrHqc2OOhVVE9Zn0o@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Travelers @ Cardinals Travelers @ Cardinals

Follow on MiLB First Pitch  https //stza.co/+wPM9-2F

Shop  https //stza.co/+wPM9-1v

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Travelers @ Cardinals
END:VALARM
DTSTART:20180622T001000Z
DTEND:20180622T031000Z
UID:AZkI6KTZrHqc2OOhVVE9Zn0o@stanza.co
SUMMARY:Travelers @ Cardinals
DESCRIPTION:Travelers @ Cardinals\n\nFollow on MiLB First Pitch: https://stza.co/+wPM9-2F\n\nShop: https://stza.co/+wPM9-1v\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144501Z
LAST-MODIFIED:20180213T144501Z
TRANSP:OPAQUE
END:VEVENT
* Travelers @ Cardinals
<2018-06-22 Fri 19:10-22:10>
:PROPERTIES:
:ID:       O--evozruL9POJiVuexHP3AK@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Travelers @ Cardinals Travelers @ Cardinals

Follow on MiLB First Pitch  https //stza.co/+wPMa-2G

Shop  https //stza.co/+wPMa-2H

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Travelers @ Cardinals
END:VALARM
DTSTART:20180623T001000Z
DTEND:20180623T031000Z
UID:O--evozruL9POJiVuexHP3AK@stanza.co
SUMMARY:Travelers @ Cardinals
DESCRIPTION:Travelers @ Cardinals\n\nFollow on MiLB First Pitch: https://stza.co/+wPMa-2G\n\nShop: https://stza.co/+wPMa-2H\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144501Z
LAST-MODIFIED:20180213T144501Z
TRANSP:OPAQUE
END:VEVENT
* Travelers @ Cardinals
<2018-06-23 Sat 18:10-21:10>
:PROPERTIES:
:ID:       HWiz85sdrQHUVts5vuIqgZom@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Travelers @ Cardinals Travelers @ Cardinals

Follow on MiLB First Pitch  https //stza.co/+wPMb-3D

Shop  https //stza.co/+wPMb-Z

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Travelers @ Cardinals
END:VALARM
DTSTART:20180623T231000Z
DTEND:20180624T021000Z
UID:HWiz85sdrQHUVts5vuIqgZom@stanza.co
SUMMARY:Travelers @ Cardinals
DESCRIPTION:Travelers @ Cardinals\n\nFollow on MiLB First Pitch: https://stza.co/+wPMb-3D\n\nShop: https://stza.co/+wPMb-Z\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144501Z
LAST-MODIFIED:20180213T144501Z
TRANSP:OPAQUE
END:VEVENT
* Travelers @ Cardinals
<2018-06-24 Sun 18:10-21:10>
:PROPERTIES:
:ID:       FSymSppZ87kk4mmj6zZpQOe4@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Travelers @ Cardinals Travelers @ Cardinals

Follow on MiLB First Pitch  https //stza.co/+wPMc-39

Shop  https //stza.co/+wPMc-2v

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Travelers @ Cardinals
END:VALARM
DTSTART:20180624T231000Z
DTEND:20180625T021000Z
UID:FSymSppZ87kk4mmj6zZpQOe4@stanza.co
SUMMARY:Travelers @ Cardinals
DESCRIPTION:Travelers @ Cardinals\n\nFollow on MiLB First Pitch: https://stza.co/+wPMc-39\n\nShop: https://stza.co/+wPMc-2v\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144501Z
LAST-MODIFIED:20180213T144501Z
TRANSP:OPAQUE
END:VEVENT
* Travelers vs. Hooks
<2018-06-28 Thu 19:10-22:10>
:PROPERTIES:
:ID:       GHYWw4JMVdXV80_IiuQLQyBB@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Travelers vs. Hooks Travelers vs. Hooks

Follow on MiLB First Pitch  https //stza.co/+v$TK-2p

Shop  https //stza.co/+v$TK-1o

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Travelers vs. Hooks
END:VALARM
DTSTART:20180629T001000Z
DTEND:20180629T031000Z
UID:GHYWw4JMVdXV80_IiuQLQyBB@stanza.co
SUMMARY:Travelers vs. Hooks
DESCRIPTION:Travelers vs. Hooks\n\nFollow on MiLB First Pitch: https://stza.co/+v$TK-2p\n\nShop: https://stza.co/+v$TK-1o\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144501Z
LAST-MODIFIED:20180213T144501Z
TRANSP:OPAQUE
END:VEVENT
* Travelers vs. Hooks
<2018-06-29 Fri 19:10-22:10>
:PROPERTIES:
:ID:       uaZ9zxwjEq1r14ndJW620uvV@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Travelers vs. Hooks Travelers vs. Hooks

Follow on MiLB First Pitch  https //stza.co/+v$TN-15

Shop  https //stza.co/+v$TN-f

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Travelers vs. Hooks
END:VALARM
DTSTART:20180630T001000Z
DTEND:20180630T031000Z
UID:uaZ9zxwjEq1r14ndJW620uvV@stanza.co
SUMMARY:Travelers vs. Hooks
DESCRIPTION:Travelers vs. Hooks\n\nFollow on MiLB First Pitch: https://stza.co/+v$TN-15\n\nShop: https://stza.co/+v$TN-f\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144501Z
LAST-MODIFIED:20180213T144501Z
TRANSP:OPAQUE
END:VEVENT
* Travelers vs. Hooks
<2018-06-30 Sat 18:10-21:10>
:PROPERTIES:
:ID:       XnaYwydBor5BuYaUgdWZ-xEj@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Travelers vs. Hooks Travelers vs. Hooks

Follow on MiLB First Pitch  https //stza.co/+v$TO-36

Shop  https //stza.co/+v$TO-17

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Travelers vs. Hooks
END:VALARM
DTSTART:20180630T231000Z
DTEND:20180701T021000Z
UID:XnaYwydBor5BuYaUgdWZ-xEj@stanza.co
SUMMARY:Travelers vs. Hooks
DESCRIPTION:Travelers vs. Hooks\n\nFollow on MiLB First Pitch: https://stza.co/+v$TO-36\n\nShop: https://stza.co/+v$TO-17\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144501Z
LAST-MODIFIED:20180213T144501Z
TRANSP:OPAQUE
END:VEVENT
* Travelers vs. Missions
<2018-07-01 Sun 14:10-17:10>
:PROPERTIES:
:ID:       qGBtbhjacncVcXlURkCjeqlI@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Travelers vs. Missions Travelers vs. Missions

Follow on MiLB First Pitch  https //stza.co/+xzEB-s

Shop  https //stza.co/+xzEB-A

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Travelers vs. Missions
END:VALARM
DTSTART:20180701T191000Z
DTEND:20180701T221000Z
UID:qGBtbhjacncVcXlURkCjeqlI@stanza.co
SUMMARY:Travelers vs. Missions
DESCRIPTION:Travelers vs. Missions\n\nFollow on MiLB First Pitch: https://stza.co/+xzEB-s\n\nShop: https://stza.co/+xzEB-A\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144501Z
LAST-MODIFIED:20180213T144501Z
TRANSP:OPAQUE
END:VEVENT
* Travelers vs. Missions
<2018-07-02 Mon 19:10-22:10>
:PROPERTIES:
:ID:       khk57ZAaI_uXra_uMSwvVNGG@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Travelers vs. Missions Travelers vs. Missions

Follow on MiLB First Pitch  https //stza.co/+v$TS-U

Shop  https //stza.co/+v$TS-2T

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Travelers vs. Missions
END:VALARM
DTSTART:20180703T001000Z
DTEND:20180703T031000Z
UID:khk57ZAaI_uXra_uMSwvVNGG@stanza.co
SUMMARY:Travelers vs. Missions
DESCRIPTION:Travelers vs. Missions\n\nFollow on MiLB First Pitch: https://stza.co/+v$TS-U\n\nShop: https://stza.co/+v$TS-2T\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144501Z
LAST-MODIFIED:20180213T144501Z
TRANSP:OPAQUE
END:VEVENT
* Travelers vs. Missions
<2018-07-03 Tue 18:10-21:10>
:PROPERTIES:
:ID:       ShFlxYlhIYOWQr8OQaFoQViA@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Travelers vs. Missions Travelers vs. Missions

Follow on MiLB First Pitch  https //stza.co/+xzED-1W

Shop  https //stza.co/+xzED-36

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Travelers vs. Missions
END:VALARM
DTSTART:20180703T231000Z
DTEND:20180704T021000Z
UID:ShFlxYlhIYOWQr8OQaFoQViA@stanza.co
SUMMARY:Travelers vs. Missions
DESCRIPTION:Travelers vs. Missions\n\nFollow on MiLB First Pitch: https://stza.co/+xzED-1W\n\nShop: https://stza.co/+xzED-36\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144501Z
LAST-MODIFIED:20180213T144501Z
TRANSP:OPAQUE
END:VEVENT
* Travelers @ Hooks
<2018-07-04 Wed 19:05-22:05>
:PROPERTIES:
:ID:       Ey5UUMGUCswYf_6YaTIYMo46@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Travelers @ Hooks Travelers @ Hooks

Follow on MiLB First Pitch  https //stza.co/+xzEJ-3T

Shop  https //stza.co/+xzEJ-3A

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Travelers @ Hooks
END:VALARM
DTSTART:20180705T000500Z
DTEND:20180705T030500Z
UID:Ey5UUMGUCswYf_6YaTIYMo46@stanza.co
SUMMARY:Travelers @ Hooks
DESCRIPTION:Travelers @ Hooks\n\nFollow on MiLB First Pitch: https://stza.co/+xzEJ-3T\n\nShop: https://stza.co/+xzEJ-3A\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144501Z
LAST-MODIFIED:20180213T144501Z
TRANSP:OPAQUE
END:VEVENT
* Travelers @ Hooks
<2018-07-05 Thu 19:05-22:05>
:PROPERTIES:
:ID:       XZDSNkpEZ_HyIVGSOiFIDt-7@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Travelers @ Hooks Travelers @ Hooks

Follow on MiLB First Pitch  https //stza.co/+xzEK-3V

Shop  https //stza.co/+xzEK-a

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Travelers @ Hooks
END:VALARM
DTSTART:20180706T000500Z
DTEND:20180706T030500Z
UID:XZDSNkpEZ_HyIVGSOiFIDt-7@stanza.co
SUMMARY:Travelers @ Hooks
DESCRIPTION:Travelers @ Hooks\n\nFollow on MiLB First Pitch: https://stza.co/+xzEK-3V\n\nShop: https://stza.co/+xzEK-a\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144501Z
LAST-MODIFIED:20180213T144501Z
TRANSP:OPAQUE
END:VEVENT
* Travelers @ Hooks
<2018-07-06 Fri 19:05-22:05>
:PROPERTIES:
:ID:       vzs1T4ahZ3ZYdF46Mr-wMH31@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Travelers @ Hooks Travelers @ Hooks

Follow on MiLB First Pitch  https //stza.co/+xzEL-1P

Shop  https //stza.co/+xzEL-

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Travelers @ Hooks
END:VALARM
DTSTART:20180707T000500Z
DTEND:20180707T030500Z
UID:vzs1T4ahZ3ZYdF46Mr-wMH31@stanza.co
SUMMARY:Travelers @ Hooks
DESCRIPTION:Travelers @ Hooks\n\nFollow on MiLB First Pitch: https://stza.co/+xzEL-1P\n\nShop: https://stza.co/+xzEL-\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144501Z
LAST-MODIFIED:20180213T144501Z
TRANSP:OPAQUE
END:VEVENT
* Travelers @ Missions
<2018-07-07 Sat 19:05-22:05>
:PROPERTIES:
:ID:       RJtD5Xkii23fVTxwCv-Tfi9R@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Travelers @ Missions Travelers @ Missions

Follow on MiLB First Pitch  https //stza.co/+wMtk-2T

Shop  https //stza.co/+wMtk-I

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Travelers @ Missions
END:VALARM
DTSTART:20180708T000500Z
DTEND:20180708T030500Z
UID:RJtD5Xkii23fVTxwCv-Tfi9R@stanza.co
SUMMARY:Travelers @ Missions
DESCRIPTION:Travelers @ Missions\n\nFollow on MiLB First Pitch: https://stza.co/+wMtk-2T\n\nShop: https://stza.co/+wMtk-I\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144501Z
LAST-MODIFIED:20180213T144501Z
TRANSP:OPAQUE
END:VEVENT
* Travelers @ Missions
<2018-07-08 Sun 18:05-21:05>
:PROPERTIES:
:ID:       PLt8uizvK9qlmeTP3yBWyUul@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Travelers @ Missions Travelers @ Missions

Follow on MiLB First Pitch  https //stza.co/+wMtl-g

Shop  https //stza.co/+wMtl-2V

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Travelers @ Missions
END:VALARM
DTSTART:20180708T230500Z
DTEND:20180709T020500Z
UID:PLt8uizvK9qlmeTP3yBWyUul@stanza.co
SUMMARY:Travelers @ Missions
DESCRIPTION:Travelers @ Missions\n\nFollow on MiLB First Pitch: https://stza.co/+wMtl-g\n\nShop: https://stza.co/+wMtl-2V\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144501Z
LAST-MODIFIED:20180213T144501Z
TRANSP:OPAQUE
END:VEVENT
* Travelers @ Missions
<2018-07-09 Mon 19:05-22:05>
:PROPERTIES:
:ID:       ZxJuNu4RoZYC5AusmfARaqFx@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Travelers @ Missions Travelers @ Missions

Follow on MiLB First Pitch  https //stza.co/+wMtm-1U

Shop  https //stza.co/+wMtm-3Q

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Travelers @ Missions
END:VALARM
DTSTART:20180710T000500Z
DTEND:20180710T030500Z
UID:ZxJuNu4RoZYC5AusmfARaqFx@stanza.co
SUMMARY:Travelers @ Missions
DESCRIPTION:Travelers @ Missions\n\nFollow on MiLB First Pitch: https://stza.co/+wMtm-1U\n\nShop: https://stza.co/+wMtm-3Q\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144501Z
LAST-MODIFIED:20180213T144501Z
TRANSP:OPAQUE
END:VEVENT
* Travelers vs. Cardinals
<2018-07-11 Wed 19:10-22:10>
:PROPERTIES:
:ID:       XBkIqcsyLHDu8CPBR_dvxfW8@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Travelers vs. Cardinals Travelers vs. Cardinals

Follow on MiLB First Pitch  https //stza.co/+v$TW-3l

Shop  https //stza.co/+v$TW-1L

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Travelers vs. Cardinals
END:VALARM
DTSTART:20180712T001000Z
DTEND:20180712T031000Z
UID:XBkIqcsyLHDu8CPBR_dvxfW8@stanza.co
SUMMARY:Travelers vs. Cardinals
DESCRIPTION:Travelers vs. Cardinals\n\nFollow on MiLB First Pitch: https://stza.co/+v$TW-3l\n\nShop: https://stza.co/+v$TW-1L\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144501Z
LAST-MODIFIED:20180213T144501Z
TRANSP:OPAQUE
END:VEVENT
* Travelers vs. Cardinals
<2018-07-12 Thu 19:10-22:10>
:PROPERTIES:
:ID:       M_5eM4LaY_1YOX5igExvYkhg@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Travelers vs. Cardinals Travelers vs. Cardinals

Follow on MiLB First Pitch  https //stza.co/+v$TY-2H

Shop  https //stza.co/+v$TY-k

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Travelers vs. Cardinals
END:VALARM
DTSTART:20180713T001000Z
DTEND:20180713T031000Z
UID:M_5eM4LaY_1YOX5igExvYkhg@stanza.co
SUMMARY:Travelers vs. Cardinals
DESCRIPTION:Travelers vs. Cardinals\n\nFollow on MiLB First Pitch: https://stza.co/+v$TY-2H\n\nShop: https://stza.co/+v$TY-k\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144501Z
LAST-MODIFIED:20180213T144501Z
TRANSP:OPAQUE
END:VEVENT
* Travelers vs. Cardinals
<2018-07-13 Fri 19:10-22:10>
:PROPERTIES:
:ID:       0iVWbqQUCqxiGv_wa9D6sotJ@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Travelers vs. Cardinals Travelers vs. Cardinals

Follow on MiLB First Pitch  https //stza.co/+v$T_-1w

Shop  https //stza.co/+v$T_-Y

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Travelers vs. Cardinals
END:VALARM
DTSTART:20180714T001000Z
DTEND:20180714T031000Z
UID:0iVWbqQUCqxiGv_wa9D6sotJ@stanza.co
SUMMARY:Travelers vs. Cardinals
DESCRIPTION:Travelers vs. Cardinals\n\nFollow on MiLB First Pitch: https://stza.co/+v$T_-1w\n\nShop: https://stza.co/+v$T_-Y\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144501Z
LAST-MODIFIED:20180213T144501Z
TRANSP:OPAQUE
END:VEVENT
* Travelers vs. Cardinals
<2018-07-14 Sat 18:10-21:10>
:PROPERTIES:
:ID:       DTKIoVmLBTMa5UydWqaAkv89@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Travelers vs. Cardinals Travelers vs. Cardinals

Follow on MiLB First Pitch  https //stza.co/+v$U1-1J

Shop  https //stza.co/+v$U1-3T

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Travelers vs. Cardinals
END:VALARM
DTSTART:20180714T231000Z
DTEND:20180715T021000Z
UID:DTKIoVmLBTMa5UydWqaAkv89@stanza.co
SUMMARY:Travelers vs. Cardinals
DESCRIPTION:Travelers vs. Cardinals\n\nFollow on MiLB First Pitch: https://stza.co/+v$U1-1J\n\nShop: https://stza.co/+v$U1-3T\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144501Z
LAST-MODIFIED:20180213T144501Z
TRANSP:OPAQUE
END:VEVENT
* Travelers @ Drillers
<2018-07-15 Sun 19:05-22:05>
:PROPERTIES:
:ID:       A5URhfgYhS9VNP9jWPxoxesf@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Travelers @ Drillers Travelers @ Drillers

Follow on MiLB First Pitch  https //stza.co/+v$VM-2s

Shop  https //stza.co/+v$VM-Y

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Travelers @ Drillers
END:VALARM
DTSTART:20180716T000500Z
DTEND:20180716T030500Z
UID:A5URhfgYhS9VNP9jWPxoxesf@stanza.co
SUMMARY:Travelers @ Drillers
DESCRIPTION:Travelers @ Drillers\n\nFollow on MiLB First Pitch: https://stza.co/+v$VM-2s\n\nShop: https://stza.co/+v$VM-Y\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144501Z
LAST-MODIFIED:20180213T144501Z
TRANSP:OPAQUE
END:VEVENT
* Travelers @ Drillers
<2018-07-16 Mon 19:05-22:05>
:PROPERTIES:
:ID:       XROdjv-IJCYbHXDRYdTGRx1Z@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Travelers @ Drillers Travelers @ Drillers

Follow on MiLB First Pitch  https //stza.co/+v$VN-2f

Shop  https //stza.co/+v$VN-3F

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Travelers @ Drillers
END:VALARM
DTSTART:20180717T000500Z
DTEND:20180717T030500Z
UID:XROdjv-IJCYbHXDRYdTGRx1Z@stanza.co
SUMMARY:Travelers @ Drillers
DESCRIPTION:Travelers @ Drillers\n\nFollow on MiLB First Pitch: https://stza.co/+v$VN-2f\n\nShop: https://stza.co/+v$VN-3F\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144501Z
LAST-MODIFIED:20180213T144501Z
TRANSP:OPAQUE
END:VEVENT
* Travelers @ Drillers
<2018-07-17 Tue 19:05-22:05>
:PROPERTIES:
:ID:       JxkIW_-9Db7x8uWcG2clvJmK@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Travelers @ Drillers Travelers @ Drillers

Follow on MiLB First Pitch  https //stza.co/+v$VO-3k

Shop  https //stza.co/+v$VO-M

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Travelers @ Drillers
END:VALARM
DTSTART:20180718T000500Z
DTEND:20180718T030500Z
UID:JxkIW_-9Db7x8uWcG2clvJmK@stanza.co
SUMMARY:Travelers @ Drillers
DESCRIPTION:Travelers @ Drillers\n\nFollow on MiLB First Pitch: https://stza.co/+v$VO-3k\n\nShop: https://stza.co/+v$VO-M\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144501Z
LAST-MODIFIED:20180213T144501Z
TRANSP:OPAQUE
END:VEVENT
* Travelers @ Drillers
<2018-07-18 Wed 19:05-22:05>
:PROPERTIES:
:ID:       XrFq0VwdMhU_RN9cR6gRzHwL@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Travelers @ Drillers Travelers @ Drillers

Follow on MiLB First Pitch  https //stza.co/+v$VP-U

Shop  https //stza.co/+v$VP-u

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Travelers @ Drillers
END:VALARM
DTSTART:20180719T000500Z
DTEND:20180719T030500Z
UID:XrFq0VwdMhU_RN9cR6gRzHwL@stanza.co
SUMMARY:Travelers @ Drillers
DESCRIPTION:Travelers @ Drillers\n\nFollow on MiLB First Pitch: https://stza.co/+v$VP-U\n\nShop: https://stza.co/+v$VP-u\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144501Z
LAST-MODIFIED:20180213T144501Z
TRANSP:OPAQUE
END:VEVENT
* Travelers vs. Cardinals
<2018-07-19 Thu 19:10-22:10>
:PROPERTIES:
:ID:       M2YXMv7Boo4xlsbE22CdCCcm@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Travelers vs. Cardinals Travelers vs. Cardinals

Follow on MiLB First Pitch  https //stza.co/+v$U2-2v

Shop  https //stza.co/+v$U2-1

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Travelers vs. Cardinals
END:VALARM
DTSTART:20180720T001000Z
DTEND:20180720T031000Z
UID:M2YXMv7Boo4xlsbE22CdCCcm@stanza.co
SUMMARY:Travelers vs. Cardinals
DESCRIPTION:Travelers vs. Cardinals\n\nFollow on MiLB First Pitch: https://stza.co/+v$U2-2v\n\nShop: https://stza.co/+v$U2-1\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144501Z
LAST-MODIFIED:20180213T144501Z
TRANSP:OPAQUE
END:VEVENT
* Travelers vs. Cardinals
<2018-07-20 Fri 19:10-22:10>
:PROPERTIES:
:ID:       tBfdr5Q6TtsWawrFbD9R15Ra@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Travelers vs. Cardinals Travelers vs. Cardinals

Follow on MiLB First Pitch  https //stza.co/+v$U4-1s

Shop  https //stza.co/+v$U4-2Q

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Travelers vs. Cardinals
END:VALARM
DTSTART:20180721T001000Z
DTEND:20180721T031000Z
UID:tBfdr5Q6TtsWawrFbD9R15Ra@stanza.co
SUMMARY:Travelers vs. Cardinals
DESCRIPTION:Travelers vs. Cardinals\n\nFollow on MiLB First Pitch: https://stza.co/+v$U4-1s\n\nShop: https://stza.co/+v$U4-2Q\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144501Z
LAST-MODIFIED:20180213T144501Z
TRANSP:OPAQUE
END:VEVENT
* Travelers vs. Cardinals
<2018-07-21 Sat 18:10-21:10>
:PROPERTIES:
:ID:       4ogwWbbZ7gdW5JF45X-_U8FF@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Travelers vs. Cardinals Travelers vs. Cardinals

Follow on MiLB First Pitch  https //stza.co/+v$U7-s

Shop  https //stza.co/+v$U7-V

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Travelers vs. Cardinals
END:VALARM
DTSTART:20180721T231000Z
DTEND:20180722T021000Z
UID:4ogwWbbZ7gdW5JF45X-_U8FF@stanza.co
SUMMARY:Travelers vs. Cardinals
DESCRIPTION:Travelers vs. Cardinals\n\nFollow on MiLB First Pitch: https://stza.co/+v$U7-s\n\nShop: https://stza.co/+v$U7-V\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144501Z
LAST-MODIFIED:20180213T144501Z
TRANSP:OPAQUE
END:VEVENT
* Travelers vs. Cardinals
<2018-07-22 Sun 18:10-21:10>
:PROPERTIES:
:ID:       zzOGFOJRMXc40TLKQpwW0h4G@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Travelers vs. Cardinals Travelers vs. Cardinals

Follow on MiLB First Pitch  https //stza.co/+v$U9-a

Shop  https //stza.co/+v$U9-1W

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Travelers vs. Cardinals
END:VALARM
DTSTART:20180722T231000Z
DTEND:20180723T021000Z
UID:zzOGFOJRMXc40TLKQpwW0h4G@stanza.co
SUMMARY:Travelers vs. Cardinals
DESCRIPTION:Travelers vs. Cardinals\n\nFollow on MiLB First Pitch: https://stza.co/+v$U9-a\n\nShop: https://stza.co/+v$U9-1W\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144501Z
LAST-MODIFIED:20180213T144501Z
TRANSP:OPAQUE
END:VEVENT
* Travelers @ Naturals
<2018-07-23 Mon 19:05-22:05>
:PROPERTIES:
:ID:       pCr8Wz__6UNxs62K-nreiQrq@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Travelers @ Naturals Travelers @ Naturals

Follow on MiLB First Pitch  https //stza.co/+wh$B-e

Shop  https //stza.co/+wh$B-1Y

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Travelers @ Naturals
END:VALARM
DTSTART:20180724T000500Z
DTEND:20180724T030500Z
UID:pCr8Wz__6UNxs62K-nreiQrq@stanza.co
SUMMARY:Travelers @ Naturals
DESCRIPTION:Travelers @ Naturals\n\nFollow on MiLB First Pitch: https://stza.co/+wh$B-e\n\nShop: https://stza.co/+wh$B-1Y\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144501Z
LAST-MODIFIED:20180213T144501Z
TRANSP:OPAQUE
END:VEVENT
* Travelers @ Naturals
<2018-07-24 Tue 19:05-22:05>
:PROPERTIES:
:ID:       IS5lyqKsiPPVAL-Mn-lPIpEN@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Travelers @ Naturals Travelers @ Naturals

Follow on MiLB First Pitch  https //stza.co/+wh$C-2w

Shop  https //stza.co/+wh$C-1P

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Travelers @ Naturals
END:VALARM
DTSTART:20180725T000500Z
DTEND:20180725T030500Z
UID:IS5lyqKsiPPVAL-Mn-lPIpEN@stanza.co
SUMMARY:Travelers @ Naturals
DESCRIPTION:Travelers @ Naturals\n\nFollow on MiLB First Pitch: https://stza.co/+wh$C-2w\n\nShop: https://stza.co/+wh$C-1P\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144501Z
LAST-MODIFIED:20180213T144501Z
TRANSP:OPAQUE
END:VEVENT
* Travelers @ Naturals
<2018-07-25 Wed 19:05-22:05>
:PROPERTIES:
:ID:       2ClkZ2yl-UjP-rwpzuBo3PgB@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Travelers @ Naturals Travelers @ Naturals

Follow on MiLB First Pitch  https //stza.co/+wh$D-1L

Shop  https //stza.co/+wh$D-2h

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Travelers @ Naturals
END:VALARM
DTSTART:20180726T000500Z
DTEND:20180726T030500Z
UID:2ClkZ2yl-UjP-rwpzuBo3PgB@stanza.co
SUMMARY:Travelers @ Naturals
DESCRIPTION:Travelers @ Naturals\n\nFollow on MiLB First Pitch: https://stza.co/+wh$D-1L\n\nShop: https://stza.co/+wh$D-2h\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144501Z
LAST-MODIFIED:20180213T144501Z
TRANSP:OPAQUE
END:VEVENT
* Travelers vs. Drillers
<2018-07-26 Thu 19:10-22:10>
:PROPERTIES:
:ID:       upWgE7FOlmRFpxwB4hLgJ8YD@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Travelers vs. Drillers Travelers vs. Drillers

Follow on MiLB First Pitch  https //stza.co/+v$Ua-D

Shop  https //stza.co/+v$Ua-C

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Travelers vs. Drillers
END:VALARM
DTSTART:20180727T001000Z
DTEND:20180727T031000Z
UID:upWgE7FOlmRFpxwB4hLgJ8YD@stanza.co
SUMMARY:Travelers vs. Drillers
DESCRIPTION:Travelers vs. Drillers\n\nFollow on MiLB First Pitch: https://stza.co/+v$Ua-D\n\nShop: https://stza.co/+v$Ua-C\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144501Z
LAST-MODIFIED:20180213T144501Z
TRANSP:OPAQUE
END:VEVENT
* Travelers vs. Drillers
<2018-07-27 Fri 19:10-22:10>
:PROPERTIES:
:ID:       5XytSvsGMtt8onwMGNcn4RIX@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Travelers vs. Drillers Travelers vs. Drillers

Follow on MiLB First Pitch  https //stza.co/+v$Uc-3u

Shop  https //stza.co/+v$Uc-3A

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Travelers vs. Drillers
END:VALARM
DTSTART:20180728T001000Z
DTEND:20180728T031000Z
UID:5XytSvsGMtt8onwMGNcn4RIX@stanza.co
SUMMARY:Travelers vs. Drillers
DESCRIPTION:Travelers vs. Drillers\n\nFollow on MiLB First Pitch: https://stza.co/+v$Uc-3u\n\nShop: https://stza.co/+v$Uc-3A\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144501Z
LAST-MODIFIED:20180213T144501Z
TRANSP:OPAQUE
END:VEVENT
* Travelers vs. Drillers
<2018-07-28 Sat 18:10-21:10>
:PROPERTIES:
:ID:       HJR-wP-MCha6rDM9w4eSZlNZ@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Travelers vs. Drillers Travelers vs. Drillers

Follow on MiLB First Pitch  https //stza.co/+v$Uf-24

Shop  https //stza.co/+v$Uf-3M

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Travelers vs. Drillers
END:VALARM
DTSTART:20180728T231000Z
DTEND:20180729T021000Z
UID:HJR-wP-MCha6rDM9w4eSZlNZ@stanza.co
SUMMARY:Travelers vs. Drillers
DESCRIPTION:Travelers vs. Drillers\n\nFollow on MiLB First Pitch: https://stza.co/+v$Uf-24\n\nShop: https://stza.co/+v$Uf-3M\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144501Z
LAST-MODIFIED:20180213T144501Z
TRANSP:OPAQUE
END:VEVENT
* Travelers vs. Drillers
<2018-07-29 Sun 18:10-21:10>
:PROPERTIES:
:ID:       Tw6TghnXm04qIdzXQSIMMtjA@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Travelers vs. Drillers Travelers vs. Drillers

Follow on MiLB First Pitch  https //stza.co/+v$Uh-2E

Shop  https //stza.co/+v$Uh-2r

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Travelers vs. Drillers
END:VALARM
DTSTART:20180729T231000Z
DTEND:20180730T021000Z
UID:Tw6TghnXm04qIdzXQSIMMtjA@stanza.co
SUMMARY:Travelers vs. Drillers
DESCRIPTION:Travelers vs. Drillers\n\nFollow on MiLB First Pitch: https://stza.co/+v$Uh-2E\n\nShop: https://stza.co/+v$Uh-2r\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144501Z
LAST-MODIFIED:20180213T144501Z
TRANSP:OPAQUE
END:VEVENT
* Travelers vs. Naturals
<2018-07-30 Mon 19:10-22:10>
:PROPERTIES:
:ID:       oOx0pWOcFqFkTqSksK6onmFK@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Travelers vs. Naturals Travelers vs. Naturals

Follow on MiLB First Pitch  https //stza.co/+v$Ui-3X

Shop  https //stza.co/+v$Ui-2F

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Travelers vs. Naturals
END:VALARM
DTSTART:20180731T001000Z
DTEND:20180731T031000Z
UID:oOx0pWOcFqFkTqSksK6onmFK@stanza.co
SUMMARY:Travelers vs. Naturals
DESCRIPTION:Travelers vs. Naturals\n\nFollow on MiLB First Pitch: https://stza.co/+v$Ui-3X\n\nShop: https://stza.co/+v$Ui-2F\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144501Z
LAST-MODIFIED:20180213T144501Z
TRANSP:OPAQUE
END:VEVENT
* Travelers vs. Naturals
<2018-07-31 Tue 19:10-22:10>
:PROPERTIES:
:ID:       7OvzRbU2bJxp1aP9fF-L98ht@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Travelers vs. Naturals Travelers vs. Naturals

Follow on MiLB First Pitch  https //stza.co/+v$Uk-1m

Shop  https //stza.co/+v$Uk-2p

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Travelers vs. Naturals
END:VALARM
DTSTART:20180801T001000Z
DTEND:20180801T031000Z
UID:7OvzRbU2bJxp1aP9fF-L98ht@stanza.co
SUMMARY:Travelers vs. Naturals
DESCRIPTION:Travelers vs. Naturals\n\nFollow on MiLB First Pitch: https://stza.co/+v$Uk-1m\n\nShop: https://stza.co/+v$Uk-2p\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144501Z
LAST-MODIFIED:20180213T144501Z
TRANSP:OPAQUE
END:VEVENT
* Travelers vs. Naturals
<2018-08-01 Wed 19:10-22:10>
:PROPERTIES:
:ID:       N-0V4ZT6WWDb32m6N9-cze3w@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Travelers vs. Naturals Travelers vs. Naturals

Follow on MiLB First Pitch  https //stza.co/+v$Um-3b

Shop  https //stza.co/+v$Um-21

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Travelers vs. Naturals
END:VALARM
DTSTART:20180802T001000Z
DTEND:20180802T031000Z
UID:N-0V4ZT6WWDb32m6N9-cze3w@stanza.co
SUMMARY:Travelers vs. Naturals
DESCRIPTION:Travelers vs. Naturals\n\nFollow on MiLB First Pitch: https://stza.co/+v$Um-3b\n\nShop: https://stza.co/+v$Um-21\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144501Z
LAST-MODIFIED:20180213T144501Z
TRANSP:OPAQUE
END:VEVENT
* Travelers @ Drillers
<2018-08-02 Thu 19:05-22:05>
:PROPERTIES:
:ID:       -bzvlV_4i5-VhlHuN_GXQU6N@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Travelers @ Drillers Travelers @ Drillers

Follow on MiLB First Pitch  https //stza.co/+v$VQ-36

Shop  https //stza.co/+v$VQ-1b

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Travelers @ Drillers
END:VALARM
DTSTART:20180803T000500Z
DTEND:20180803T030500Z
UID:-bzvlV_4i5-VhlHuN_GXQU6N@stanza.co
SUMMARY:Travelers @ Drillers
DESCRIPTION:Travelers @ Drillers\n\nFollow on MiLB First Pitch: https://stza.co/+v$VQ-36\n\nShop: https://stza.co/+v$VQ-1b\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144501Z
LAST-MODIFIED:20180213T144501Z
TRANSP:OPAQUE
END:VEVENT
* Travelers @ Drillers
<2018-08-03 Fri 19:05-22:05>
:PROPERTIES:
:ID:       m6tvgaRAV5r5ceXAb7I9NzNT@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Travelers @ Drillers Travelers @ Drillers

Follow on MiLB First Pitch  https //stza.co/+v$VR-1L

Shop  https //stza.co/+v$VR-1H

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Travelers @ Drillers
END:VALARM
DTSTART:20180804T000500Z
DTEND:20180804T030500Z
UID:m6tvgaRAV5r5ceXAb7I9NzNT@stanza.co
SUMMARY:Travelers @ Drillers
DESCRIPTION:Travelers @ Drillers\n\nFollow on MiLB First Pitch: https://stza.co/+v$VR-1L\n\nShop: https://stza.co/+v$VR-1H\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144501Z
LAST-MODIFIED:20180213T144501Z
TRANSP:OPAQUE
END:VEVENT
* Travelers @ Drillers
<2018-08-04 Sat 19:05-22:05>
:PROPERTIES:
:ID:       t4NlIffpYOuoz39G2ypcc83O@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Travelers @ Drillers Travelers @ Drillers

Follow on MiLB First Pitch  https //stza.co/+v$VS-1S

Shop  https //stza.co/+v$VS-a

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Travelers @ Drillers
END:VALARM
DTSTART:20180805T000500Z
DTEND:20180805T030500Z
UID:t4NlIffpYOuoz39G2ypcc83O@stanza.co
SUMMARY:Travelers @ Drillers
DESCRIPTION:Travelers @ Drillers\n\nFollow on MiLB First Pitch: https://stza.co/+v$VS-1S\n\nShop: https://stza.co/+v$VS-a\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144501Z
LAST-MODIFIED:20180213T144501Z
TRANSP:OPAQUE
END:VEVENT
* Travelers @ Drillers
<2018-08-05 Sun 19:05-22:05>
:PROPERTIES:
:ID:       rp0fc7BdReTFZ1SWuIoft4fc@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Travelers @ Drillers Travelers @ Drillers

Follow on MiLB First Pitch  https //stza.co/+v$VT-k

Shop  https //stza.co/+v$VT-3y

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Travelers @ Drillers
END:VALARM
DTSTART:20180806T000500Z
DTEND:20180806T030500Z
UID:rp0fc7BdReTFZ1SWuIoft4fc@stanza.co
SUMMARY:Travelers @ Drillers
DESCRIPTION:Travelers @ Drillers\n\nFollow on MiLB First Pitch: https://stza.co/+v$VT-k\n\nShop: https://stza.co/+v$VT-3y\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144501Z
LAST-MODIFIED:20180213T144501Z
TRANSP:OPAQUE
END:VEVENT
* Travelers vs. RoughRiders
<2018-08-07 Tue 19:10-22:10>
:PROPERTIES:
:ID:       5i3AiujBFURHXArTgGfjWpc9@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Travelers vs. RoughRiders Travelers vs. RoughRiders

Follow on MiLB First Pitch  https //stza.co/+v$Uo-2i

Shop  https //stza.co/+v$Uo-1U

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Travelers vs. RoughRiders
END:VALARM
DTSTART:20180808T001000Z
DTEND:20180808T031000Z
UID:5i3AiujBFURHXArTgGfjWpc9@stanza.co
SUMMARY:Travelers vs. RoughRiders
DESCRIPTION:Travelers vs. RoughRiders\n\nFollow on MiLB First Pitch: https://stza.co/+v$Uo-2i\n\nShop: https://stza.co/+v$Uo-1U\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144501Z
LAST-MODIFIED:20180213T144501Z
TRANSP:OPAQUE
END:VEVENT
* Travelers vs. RoughRiders
<2018-08-08 Wed 19:10-22:10>
:PROPERTIES:
:ID:       s_XCjmnnVXAFVDfIoMHPLFk5@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Travelers vs. RoughRiders Travelers vs. RoughRiders

Follow on MiLB First Pitch  https //stza.co/+v$Ur-3d

Shop  https //stza.co/+v$Ur-1x

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Travelers vs. RoughRiders
END:VALARM
DTSTART:20180809T001000Z
DTEND:20180809T031000Z
UID:s_XCjmnnVXAFVDfIoMHPLFk5@stanza.co
SUMMARY:Travelers vs. RoughRiders
DESCRIPTION:Travelers vs. RoughRiders\n\nFollow on MiLB First Pitch: https://stza.co/+v$Ur-3d\n\nShop: https://stza.co/+v$Ur-1x\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144501Z
LAST-MODIFIED:20180213T144501Z
TRANSP:OPAQUE
END:VEVENT
* Travelers vs. RoughRiders
<2018-08-09 Thu 19:10-22:10>
:PROPERTIES:
:ID:       iGZ4YK3rN9AaT-NIuA258d9L@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Travelers vs. RoughRiders Travelers vs. RoughRiders

Follow on MiLB First Pitch  https //stza.co/+v$Us-2A

Shop  https //stza.co/+v$Us-B

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Travelers vs. RoughRiders
END:VALARM
DTSTART:20180810T001000Z
DTEND:20180810T031000Z
UID:iGZ4YK3rN9AaT-NIuA258d9L@stanza.co
SUMMARY:Travelers vs. RoughRiders
DESCRIPTION:Travelers vs. RoughRiders\n\nFollow on MiLB First Pitch: https://stza.co/+v$Us-2A\n\nShop: https://stza.co/+v$Us-B\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144501Z
LAST-MODIFIED:20180213T144501Z
TRANSP:OPAQUE
END:VEVENT
* Travelers vs. RockHounds
<2018-08-10 Fri 19:10-22:10>
:PROPERTIES:
:ID:       mZrRhffsNT59ryyJSlbD78Js@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Travelers vs. RockHounds Travelers vs. RockHounds

Follow on MiLB First Pitch  https //stza.co/+v$Uv-23

Shop  https //stza.co/+v$Uv-18

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Travelers vs. RockHounds
END:VALARM
DTSTART:20180811T001000Z
DTEND:20180811T031000Z
UID:mZrRhffsNT59ryyJSlbD78Js@stanza.co
SUMMARY:Travelers vs. RockHounds
DESCRIPTION:Travelers vs. RockHounds\n\nFollow on MiLB First Pitch: https://stza.co/+v$Uv-23\n\nShop: https://stza.co/+v$Uv-18\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144501Z
LAST-MODIFIED:20180213T144501Z
TRANSP:OPAQUE
END:VEVENT
* Travelers vs. RockHounds
<2018-08-11 Sat 18:10-21:10>
:PROPERTIES:
:ID:       2BD38zUwGC-ooH0KwrzwXpe2@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Travelers vs. RockHounds Travelers vs. RockHounds

Follow on MiLB First Pitch  https //stza.co/+v$Ux-23

Shop  https //stza.co/+v$Ux-1e

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Travelers vs. RockHounds
END:VALARM
DTSTART:20180811T231000Z
DTEND:20180812T021000Z
UID:2BD38zUwGC-ooH0KwrzwXpe2@stanza.co
SUMMARY:Travelers vs. RockHounds
DESCRIPTION:Travelers vs. RockHounds\n\nFollow on MiLB First Pitch: https://stza.co/+v$Ux-23\n\nShop: https://stza.co/+v$Ux-1e\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144501Z
LAST-MODIFIED:20180213T144501Z
TRANSP:OPAQUE
END:VEVENT
* Travelers vs. RockHounds
<2018-08-12 Sun 14:10-17:10>
:PROPERTIES:
:ID:       FmUqMM1ZCA2dUjXIfEMLSGMB@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Travelers vs. RockHounds Travelers vs. RockHounds

Follow on MiLB First Pitch  https //stza.co/+v$Uy-p

Shop  https //stza.co/+v$Uy-1q

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Travelers vs. RockHounds
END:VALARM
DTSTART:20180812T191000Z
DTEND:20180812T221000Z
UID:FmUqMM1ZCA2dUjXIfEMLSGMB@stanza.co
SUMMARY:Travelers vs. RockHounds
DESCRIPTION:Travelers vs. RockHounds\n\nFollow on MiLB First Pitch: https://stza.co/+v$Uy-p\n\nShop: https://stza.co/+v$Uy-1q\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144501Z
LAST-MODIFIED:20180213T144501Z
TRANSP:OPAQUE
END:VEVENT
* Travelers @ RoughRiders
<2018-08-14 Tue 19:05-22:05>
:PROPERTIES:
:ID:       TSt6IY9o6HQY0GNqac7uzA_R@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Travelers @ RoughRiders Travelers @ RoughRiders

Follow on MiLB First Pitch  https //stza.co/+wY6V-Y

Shop  https //stza.co/+wY6V-2x

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Travelers @ RoughRiders
END:VALARM
DTSTART:20180815T000500Z
DTEND:20180815T030500Z
UID:TSt6IY9o6HQY0GNqac7uzA_R@stanza.co
SUMMARY:Travelers @ RoughRiders
DESCRIPTION:Travelers @ RoughRiders\n\nFollow on MiLB First Pitch: https://stza.co/+wY6V-Y\n\nShop: https://stza.co/+wY6V-2x\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144501Z
LAST-MODIFIED:20180213T144501Z
TRANSP:OPAQUE
END:VEVENT
* Travelers @ RoughRiders
<2018-08-15 Wed 19:05-22:05>
:PROPERTIES:
:ID:       10n4Bs9eHX1tREMXc75_aEsR@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Travelers @ RoughRiders Travelers @ RoughRiders

Follow on MiLB First Pitch  https //stza.co/+wY6W-37

Shop  https //stza.co/+wY6W-1k

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Travelers @ RoughRiders
END:VALARM
DTSTART:20180816T000500Z
DTEND:20180816T030500Z
UID:10n4Bs9eHX1tREMXc75_aEsR@stanza.co
SUMMARY:Travelers @ RoughRiders
DESCRIPTION:Travelers @ RoughRiders\n\nFollow on MiLB First Pitch: https://stza.co/+wY6W-37\n\nShop: https://stza.co/+wY6W-1k\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144501Z
LAST-MODIFIED:20180213T144501Z
TRANSP:OPAQUE
END:VEVENT
* Travelers @ RoughRiders
<2018-08-16 Thu 19:05-22:05>
:PROPERTIES:
:ID:       91U7b3OjRZSfoUqxkDXHiuBJ@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Travelers @ RoughRiders Travelers @ RoughRiders

Follow on MiLB First Pitch  https //stza.co/+wY6X-1J

Shop  https //stza.co/+wY6X-3

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Travelers @ RoughRiders
END:VALARM
DTSTART:20180817T000500Z
DTEND:20180817T030500Z
UID:91U7b3OjRZSfoUqxkDXHiuBJ@stanza.co
SUMMARY:Travelers @ RoughRiders
DESCRIPTION:Travelers @ RoughRiders\n\nFollow on MiLB First Pitch: https://stza.co/+wY6X-1J\n\nShop: https://stza.co/+wY6X-3\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144501Z
LAST-MODIFIED:20180213T144501Z
TRANSP:OPAQUE
END:VEVENT
* Travelers @ RockHounds
<2018-08-17 Fri 19:00-22:00>
:PROPERTIES:
:ID:       prGPnd3qbcMGcLqgFUwOGNCa@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Travelers @ RockHounds Travelers @ RockHounds

Follow on MiLB First Pitch  https //stza.co/+wX0$-1j

Shop  https //stza.co/+wX0$-39

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Travelers @ RockHounds
END:VALARM
DTSTART:20180818T000000Z
DTEND:20180818T030000Z
UID:prGPnd3qbcMGcLqgFUwOGNCa@stanza.co
SUMMARY:Travelers @ RockHounds
DESCRIPTION:Travelers @ RockHounds\n\nFollow on MiLB First Pitch: https://stza.co/+wX0$-1j\n\nShop: https://stza.co/+wX0$-39\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144501Z
LAST-MODIFIED:20180213T144501Z
TRANSP:OPAQUE
END:VEVENT
* Travelers @ RockHounds
<2018-08-18 Sat 19:00-22:00>
:PROPERTIES:
:ID:       dYPomTXLWTWotX2CYou5GOpm@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Travelers @ RockHounds Travelers @ RockHounds

Follow on MiLB First Pitch  https //stza.co/+wX10-6

Shop  https //stza.co/+wX10-1Q

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Travelers @ RockHounds
END:VALARM
DTSTART:20180819T000000Z
DTEND:20180819T030000Z
UID:dYPomTXLWTWotX2CYou5GOpm@stanza.co
SUMMARY:Travelers @ RockHounds
DESCRIPTION:Travelers @ RockHounds\n\nFollow on MiLB First Pitch: https://stza.co/+wX10-6\n\nShop: https://stza.co/+wX10-1Q\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144501Z
LAST-MODIFIED:20180213T144501Z
TRANSP:OPAQUE
END:VEVENT
* Travelers @ RockHounds
<2018-08-19 Sun 14:00-17:00>
:PROPERTIES:
:ID:       UwQ3L_SORdzl_5dn1VjpIyKE@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Travelers @ RockHounds Travelers @ RockHounds

Follow on MiLB First Pitch  https //stza.co/+wX11-y

Shop  https //stza.co/+wX11-Z

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Travelers @ RockHounds
END:VALARM
DTSTART:20180819T190000Z
DTEND:20180819T220000Z
UID:UwQ3L_SORdzl_5dn1VjpIyKE@stanza.co
SUMMARY:Travelers @ RockHounds
DESCRIPTION:Travelers @ RockHounds\n\nFollow on MiLB First Pitch: https://stza.co/+wX11-y\n\nShop: https://stza.co/+wX11-Z\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144501Z
LAST-MODIFIED:20180213T144501Z
TRANSP:OPAQUE
END:VEVENT
* Travelers vs. Drillers
<2018-08-21 Tue 19:10-22:10>
:PROPERTIES:
:ID:       2mjBBHFaMN6fQJKSki0-yTLo@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Travelers vs. Drillers Travelers vs. Drillers

Follow on MiLB First Pitch  https //stza.co/+v$UB-29

Shop  https //stza.co/+v$UB-J

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Travelers vs. Drillers
END:VALARM
DTSTART:20180822T001000Z
DTEND:20180822T031000Z
UID:2mjBBHFaMN6fQJKSki0-yTLo@stanza.co
SUMMARY:Travelers vs. Drillers
DESCRIPTION:Travelers vs. Drillers\n\nFollow on MiLB First Pitch: https://stza.co/+v$UB-29\n\nShop: https://stza.co/+v$UB-J\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144501Z
LAST-MODIFIED:20180213T144501Z
TRANSP:OPAQUE
END:VEVENT
* Travelers vs. Drillers
<2018-08-22 Wed 19:10-22:10>
:PROPERTIES:
:ID:       bA1AUIVAoO1ntwYhDOdUKCCi@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Travelers vs. Drillers Travelers vs. Drillers

Follow on MiLB First Pitch  https //stza.co/+v$UD-1q

Shop  https //stza.co/+v$UD-_

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Travelers vs. Drillers
END:VALARM
DTSTART:20180823T001000Z
DTEND:20180823T031000Z
UID:bA1AUIVAoO1ntwYhDOdUKCCi@stanza.co
SUMMARY:Travelers vs. Drillers
DESCRIPTION:Travelers vs. Drillers\n\nFollow on MiLB First Pitch: https://stza.co/+v$UD-1q\n\nShop: https://stza.co/+v$UD-_\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144501Z
LAST-MODIFIED:20180213T144501Z
TRANSP:OPAQUE
END:VEVENT
* Travelers vs. Drillers
<2018-08-23 Thu 19:10-22:10>
:PROPERTIES:
:ID:       cyjMEmfRDPq2G6BPkiBVAgLY@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Travelers vs. Drillers Travelers vs. Drillers

Follow on MiLB First Pitch  https //stza.co/+v$UE-F

Shop  https //stza.co/+v$UE-2t

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Travelers vs. Drillers
END:VALARM
DTSTART:20180824T001000Z
DTEND:20180824T031000Z
UID:cyjMEmfRDPq2G6BPkiBVAgLY@stanza.co
SUMMARY:Travelers vs. Drillers
DESCRIPTION:Travelers vs. Drillers\n\nFollow on MiLB First Pitch: https://stza.co/+v$UE-F\n\nShop: https://stza.co/+v$UE-2t\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144501Z
LAST-MODIFIED:20180213T144501Z
TRANSP:OPAQUE
END:VEVENT
* Travelers vs. Drillers
<2018-08-24 Fri 19:10-22:10>
:PROPERTIES:
:ID:       tfOaHmXilNUf9ap0mOwjpAsM@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Travelers vs. Drillers Travelers vs. Drillers

Follow on MiLB First Pitch  https //stza.co/+v$UH-2_

Shop  https //stza.co/+v$UH-2c

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Travelers vs. Drillers
END:VALARM
DTSTART:20180825T001000Z
DTEND:20180825T031000Z
UID:tfOaHmXilNUf9ap0mOwjpAsM@stanza.co
SUMMARY:Travelers vs. Drillers
DESCRIPTION:Travelers vs. Drillers\n\nFollow on MiLB First Pitch: https://stza.co/+v$UH-2_\n\nShop: https://stza.co/+v$UH-2c\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144501Z
LAST-MODIFIED:20180213T144501Z
TRANSP:OPAQUE
END:VEVENT
* Travelers vs. Naturals
<2018-08-25 Sat 18:10-21:10>
:PROPERTIES:
:ID:       YemBRshS35JpeSt7Trz7jvuZ@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Travelers vs. Naturals Travelers vs. Naturals

Follow on MiLB First Pitch  https //stza.co/+v$UI-1G

Shop  https //stza.co/+v$UI-I

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Travelers vs. Naturals
END:VALARM
DTSTART:20180825T231000Z
DTEND:20180826T021000Z
UID:YemBRshS35JpeSt7Trz7jvuZ@stanza.co
SUMMARY:Travelers vs. Naturals
DESCRIPTION:Travelers vs. Naturals\n\nFollow on MiLB First Pitch: https://stza.co/+v$UI-1G\n\nShop: https://stza.co/+v$UI-I\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144501Z
LAST-MODIFIED:20180213T144501Z
TRANSP:OPAQUE
END:VEVENT
* Travelers vs. Naturals
<2018-08-26 Sun 14:10-17:10>
:PROPERTIES:
:ID:       Uh2hBvwcddXgJgbkxCcykwFF@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Travelers vs. Naturals Travelers vs. Naturals

Follow on MiLB First Pitch  https //stza.co/+v$UK-l

Shop  https //stza.co/+v$UK-32

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Travelers vs. Naturals
END:VALARM
DTSTART:20180826T191000Z
DTEND:20180826T221000Z
UID:Uh2hBvwcddXgJgbkxCcykwFF@stanza.co
SUMMARY:Travelers vs. Naturals
DESCRIPTION:Travelers vs. Naturals\n\nFollow on MiLB First Pitch: https://stza.co/+v$UK-l\n\nShop: https://stza.co/+v$UK-32\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144501Z
LAST-MODIFIED:20180213T144501Z
TRANSP:OPAQUE
END:VEVENT
* Travelers vs. Naturals
<2018-08-27 Mon 19:10-22:10>
:PROPERTIES:
:ID:       nhttahba7Cg_6UPfWOVJ5j5l@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Travelers vs. Naturals Travelers vs. Naturals

Follow on MiLB First Pitch  https //stza.co/+v$UN-3z

Shop  https //stza.co/+v$UN-v

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Travelers vs. Naturals
END:VALARM
DTSTART:20180828T001000Z
DTEND:20180828T031000Z
UID:nhttahba7Cg_6UPfWOVJ5j5l@stanza.co
SUMMARY:Travelers vs. Naturals
DESCRIPTION:Travelers vs. Naturals\n\nFollow on MiLB First Pitch: https://stza.co/+v$UN-3z\n\nShop: https://stza.co/+v$UN-v\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144501Z
LAST-MODIFIED:20180213T144501Z
TRANSP:OPAQUE
END:VEVENT
* Travelers @ Cardinals
<2018-08-28 Tue 18:30-21:30>
:PROPERTIES:
:ID:       wLgi03sn9Rn4Q5IGxH5g8cpZ@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Travelers @ Cardinals Travelers @ Cardinals

Follow on MiLB First Pitch  https //stza.co/+wPMd-2u

Shop  https //stza.co/+wPMd-1K

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Travelers @ Cardinals
END:VALARM
DTSTART:20180828T233000Z
DTEND:20180829T023000Z
UID:wLgi03sn9Rn4Q5IGxH5g8cpZ@stanza.co
SUMMARY:Travelers @ Cardinals
DESCRIPTION:Travelers @ Cardinals\n\nFollow on MiLB First Pitch: https://stza.co/+wPMd-2u\n\nShop: https://stza.co/+wPMd-1K\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144501Z
LAST-MODIFIED:20180213T144501Z
TRANSP:OPAQUE
END:VEVENT
* Travelers @ Cardinals
<2018-08-29 Wed 18:30-21:30>
:PROPERTIES:
:ID:       Rc0XHXu7slnLhTJ9m-SshS-7@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Travelers @ Cardinals Travelers @ Cardinals

Follow on MiLB First Pitch  https //stza.co/+wPMe-3t

Shop  https //stza.co/+wPMe-3o

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Travelers @ Cardinals
END:VALARM
DTSTART:20180829T233000Z
DTEND:20180830T023000Z
UID:Rc0XHXu7slnLhTJ9m-SshS-7@stanza.co
SUMMARY:Travelers @ Cardinals
DESCRIPTION:Travelers @ Cardinals\n\nFollow on MiLB First Pitch: https://stza.co/+wPMe-3t\n\nShop: https://stza.co/+wPMe-3o\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144501Z
LAST-MODIFIED:20180213T144501Z
TRANSP:OPAQUE
END:VEVENT
* Travelers @ Cardinals
<2018-08-30 Thu 19:10-22:10>
:PROPERTIES:
:ID:       r0auHEB45zGoJjcVKShfGRJe@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Travelers @ Cardinals Travelers @ Cardinals

Follow on MiLB First Pitch  https //stza.co/+wPMg-3N

Shop  https //stza.co/+wPMg-e

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Travelers @ Cardinals
END:VALARM
DTSTART:20180831T001000Z
DTEND:20180831T031000Z
UID:r0auHEB45zGoJjcVKShfGRJe@stanza.co
SUMMARY:Travelers @ Cardinals
DESCRIPTION:Travelers @ Cardinals\n\nFollow on MiLB First Pitch: https://stza.co/+wPMg-3N\n\nShop: https://stza.co/+wPMg-e\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144501Z
LAST-MODIFIED:20180213T144501Z
TRANSP:OPAQUE
END:VEVENT
* Travelers @ Cardinals
<2018-08-31 Fri 19:10-22:10>
:PROPERTIES:
:ID:       iju1h0zQmD8COPdJKYBWrouo@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Travelers @ Cardinals Travelers @ Cardinals

Follow on MiLB First Pitch  https //stza.co/+wPMh-12

Shop  https //stza.co/+wPMh-3W

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Travelers @ Cardinals
END:VALARM
DTSTART:20180901T001000Z
DTEND:20180901T031000Z
UID:iju1h0zQmD8COPdJKYBWrouo@stanza.co
SUMMARY:Travelers @ Cardinals
DESCRIPTION:Travelers @ Cardinals\n\nFollow on MiLB First Pitch: https://stza.co/+wPMh-12\n\nShop: https://stza.co/+wPMh-3W\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144501Z
LAST-MODIFIED:20180213T144501Z
TRANSP:OPAQUE
END:VEVENT
* Travelers @ Naturals
<2018-09-01 Sat 18:05-21:05>
:PROPERTIES:
:ID:       c8hIXlTOF0gdnle6dhk91M86@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Travelers @ Naturals Travelers @ Naturals

Follow on MiLB First Pitch  https //stza.co/+wh$E-1u

Shop  https //stza.co/+wh$E-3K

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Travelers @ Naturals
END:VALARM
DTSTART:20180901T230500Z
DTEND:20180902T020500Z
UID:c8hIXlTOF0gdnle6dhk91M86@stanza.co
SUMMARY:Travelers @ Naturals
DESCRIPTION:Travelers @ Naturals\n\nFollow on MiLB First Pitch: https://stza.co/+wh$E-1u\n\nShop: https://stza.co/+wh$E-3K\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144501Z
LAST-MODIFIED:20180213T144501Z
TRANSP:OPAQUE
END:VEVENT
* Travelers @ Naturals
<2018-09-02 Sun 18:05-21:05>
:PROPERTIES:
:ID:       _dm2CFV9cr3uQP68OtOKsEVq@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Travelers @ Naturals Travelers @ Naturals

Follow on MiLB First Pitch  https //stza.co/+wh$G-3O

Shop  https //stza.co/+wh$G-2U

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Travelers @ Naturals
END:VALARM
DTSTART:20180902T230500Z
DTEND:20180903T020500Z
UID:_dm2CFV9cr3uQP68OtOKsEVq@stanza.co
SUMMARY:Travelers @ Naturals
DESCRIPTION:Travelers @ Naturals\n\nFollow on MiLB First Pitch: https://stza.co/+wh$G-3O\n\nShop: https://stza.co/+wh$G-2U\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144501Z
LAST-MODIFIED:20180213T144501Z
TRANSP:OPAQUE
END:VEVENT
* Travelers @ Naturals
<2018-09-03 Mon 13:05-16:05>
:PROPERTIES:
:ID:       k633acallJq0V5p8d_NCTBNT@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Travelers @ Naturals Travelers @ Naturals

Follow on MiLB First Pitch  https //stza.co/+wh$H-3U

Shop  https //stza.co/+wh$H-1M

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Travelers @ Naturals
END:VALARM
DTSTART:20180903T180500Z
DTEND:20180903T210500Z
UID:k633acallJq0V5p8d_NCTBNT@stanza.co
SUMMARY:Travelers @ Naturals
DESCRIPTION:Travelers @ Naturals\n\nFollow on MiLB First Pitch: https://stza.co/+wh$H-3U\n\nShop: https://stza.co/+wh$H-1M\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144501Z
LAST-MODIFIED:20180213T144501Z
TRANSP:OPAQUE
END:VEVENT
