#+TITLE:       Main Google calendar entries
#+AUTHOR:      Eric S Fraga
#+EMAIL:       e.fraga@ucl.ac.uk
#+DESCRIPTION: converted using the ical2org awk script
#+CATEGORY:    google
#+STARTUP:     hidestars
#+STARTUP:     overview

* COMMENT original iCal preamble

* Owlz @ Rockies
<2018-06-15 Fri 19:40-22:40>
:PROPERTIES:
:ID:       1kYVtjQVxZF3M4alDD71fw2e@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Owlz @ Rockies Owlz @ Rockies

Follow on MiLB First Pitch  https //stza.co/+xJ8y-M

Shop  https //stza.co/+xJ8y-1f

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Owlz @ Rockies
END:VALARM
DTSTART:20180616T004000Z
DTEND:20180616T034000Z
UID:1kYVtjQVxZF3M4alDD71fw2e@stanza.co
SUMMARY:Owlz @ Rockies
DESCRIPTION:Owlz @ Rockies\n\nFollow on MiLB First Pitch: https://stza.co/+xJ8y-M\n\nShop: https://stza.co/+xJ8y-1f\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144549Z
LAST-MODIFIED:20180213T144549Z
TRANSP:OPAQUE
END:VEVENT
* Owlz @ Rockies
<2018-06-16 Sat 19:40-22:40>
:PROPERTIES:
:ID:       q55Q5LZ9ihPcfUOerrVYqk4H@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Owlz @ Rockies Owlz @ Rockies

Follow on MiLB First Pitch  https //stza.co/+xJ8z-12

Shop  https //stza.co/+xJ8z-2j

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Owlz @ Rockies
END:VALARM
DTSTART:20180617T004000Z
DTEND:20180617T034000Z
UID:q55Q5LZ9ihPcfUOerrVYqk4H@stanza.co
SUMMARY:Owlz @ Rockies
DESCRIPTION:Owlz @ Rockies\n\nFollow on MiLB First Pitch: https://stza.co/+xJ8z-12\n\nShop: https://stza.co/+xJ8z-2j\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144549Z
LAST-MODIFIED:20180213T144549Z
TRANSP:OPAQUE
END:VEVENT
* Owlz @ Rockies
<2018-06-17 Sun 18:00-21:00>
:PROPERTIES:
:ID:       swNDoA0HLX7N-bm4atmShzQk@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Owlz @ Rockies Owlz @ Rockies

Follow on MiLB First Pitch  https //stza.co/+xJ8A-20

Shop  https //stza.co/+xJ8A-10

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Owlz @ Rockies
END:VALARM
DTSTART:20180617T230000Z
DTEND:20180618T020000Z
UID:swNDoA0HLX7N-bm4atmShzQk@stanza.co
SUMMARY:Owlz @ Rockies
DESCRIPTION:Owlz @ Rockies\n\nFollow on MiLB First Pitch: https://stza.co/+xJ8A-20\n\nShop: https://stza.co/+xJ8A-10\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144549Z
LAST-MODIFIED:20180213T144549Z
TRANSP:OPAQUE
END:VEVENT
* Owlz @ Rockies
<2018-06-18 Mon 19:40-22:40>
:PROPERTIES:
:ID:       VNKmcUj3pns74Blp0OOIPt20@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Owlz @ Rockies Owlz @ Rockies

Follow on MiLB First Pitch  https //stza.co/+xJ8B-2d

Shop  https //stza.co/+xJ8B-2a

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Owlz @ Rockies
END:VALARM
DTSTART:20180619T004000Z
DTEND:20180619T034000Z
UID:VNKmcUj3pns74Blp0OOIPt20@stanza.co
SUMMARY:Owlz @ Rockies
DESCRIPTION:Owlz @ Rockies\n\nFollow on MiLB First Pitch: https://stza.co/+xJ8B-2d\n\nShop: https://stza.co/+xJ8B-2a\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144549Z
LAST-MODIFIED:20180213T144549Z
TRANSP:OPAQUE
END:VEVENT
* Owlz @ Raptors
<2018-06-19 Tue 20:00-23:00>
:PROPERTIES:
:ID:       iJ75oC6YvKf8QWjoLgxJRBgU@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Owlz @ Raptors Owlz @ Raptors

Follow on MiLB First Pitch  https //stza.co/+x$9p-A

Shop  https //stza.co/+x$9p-1G

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Owlz @ Raptors
END:VALARM
DTSTART:20180620T010000Z
DTEND:20180620T040000Z
UID:iJ75oC6YvKf8QWjoLgxJRBgU@stanza.co
SUMMARY:Owlz @ Raptors
DESCRIPTION:Owlz @ Raptors\n\nFollow on MiLB First Pitch: https://stza.co/+x$9p-A\n\nShop: https://stza.co/+x$9p-1G\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144549Z
LAST-MODIFIED:20180213T144549Z
TRANSP:OPAQUE
END:VEVENT
* Owlz @ Raptors
<2018-06-20 Wed 20:00-23:00>
:PROPERTIES:
:ID:       XFe7ZJCjo_DbgJ_j3Jaire2H@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Owlz @ Raptors Owlz @ Raptors

Follow on MiLB First Pitch  https //stza.co/+x$9q-y

Shop  https //stza.co/+x$9q-1R

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Owlz @ Raptors
END:VALARM
DTSTART:20180621T010000Z
DTEND:20180621T040000Z
UID:XFe7ZJCjo_DbgJ_j3Jaire2H@stanza.co
SUMMARY:Owlz @ Raptors
DESCRIPTION:Owlz @ Raptors\n\nFollow on MiLB First Pitch: https://stza.co/+x$9q-y\n\nShop: https://stza.co/+x$9q-1R\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144549Z
LAST-MODIFIED:20180213T144549Z
TRANSP:OPAQUE
END:VEVENT
* Owlz vs. Raptors
<2018-06-21 Thu 20:05-23:05>
:PROPERTIES:
:ID:       on3ZDGHL9dL5miwqXvd4CwFz@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Owlz vs. Raptors Owlz vs. Raptors

Follow on MiLB First Pitch  https //stza.co/+xPBC-I

Shop  https //stza.co/+xPBC-2v

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Owlz vs. Raptors
END:VALARM
DTSTART:20180622T010500Z
DTEND:20180622T040500Z
UID:on3ZDGHL9dL5miwqXvd4CwFz@stanza.co
SUMMARY:Owlz vs. Raptors
DESCRIPTION:Owlz vs. Raptors\n\nFollow on MiLB First Pitch: https://stza.co/+xPBC-I\n\nShop: https://stza.co/+xPBC-2v\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144549Z
LAST-MODIFIED:20180213T144549Z
TRANSP:OPAQUE
END:VEVENT
* Owlz vs. Raptors
<2018-06-22 Fri 20:05-23:05>
:PROPERTIES:
:ID:       ZGomWOijfuQyKejUV2M5RPH_@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Owlz vs. Raptors Owlz vs. Raptors

Follow on MiLB First Pitch  https //stza.co/+xPBE-B

Shop  https //stza.co/+xPBE-F

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Owlz vs. Raptors
END:VALARM
DTSTART:20180623T010500Z
DTEND:20180623T040500Z
UID:ZGomWOijfuQyKejUV2M5RPH_@stanza.co
SUMMARY:Owlz vs. Raptors
DESCRIPTION:Owlz vs. Raptors\n\nFollow on MiLB First Pitch: https://stza.co/+xPBE-B\n\nShop: https://stza.co/+xPBE-F\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144549Z
LAST-MODIFIED:20180213T144549Z
TRANSP:OPAQUE
END:VEVENT
* Owlz vs. Chukars
<2018-06-23 Sat 20:05-23:05>
:PROPERTIES:
:ID:       rws-fJoOw0Xnebk7KlH4unGW@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Owlz vs. Chukars Owlz vs. Chukars

Follow on MiLB First Pitch  https //stza.co/+xPBH-3h

Shop  https //stza.co/+xPBH-1z

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Owlz vs. Chukars
END:VALARM
DTSTART:20180624T010500Z
DTEND:20180624T040500Z
UID:rws-fJoOw0Xnebk7KlH4unGW@stanza.co
SUMMARY:Owlz vs. Chukars
DESCRIPTION:Owlz vs. Chukars\n\nFollow on MiLB First Pitch: https://stza.co/+xPBH-3h\n\nShop: https://stza.co/+xPBH-1z\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144549Z
LAST-MODIFIED:20180213T144549Z
TRANSP:OPAQUE
END:VEVENT
* Owlz vs. Chukars
<2018-06-24 Sun 17:05-20:05>
:PROPERTIES:
:ID:       SB2DFr2rlFhMvLD9N1u3YvqR@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Owlz vs. Chukars Owlz vs. Chukars

Follow on MiLB First Pitch  https //stza.co/+xPBJ-2e

Shop  https //stza.co/+xPBJ-17

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Owlz vs. Chukars
END:VALARM
DTSTART:20180624T220500Z
DTEND:20180625T010500Z
UID:SB2DFr2rlFhMvLD9N1u3YvqR@stanza.co
SUMMARY:Owlz vs. Chukars
DESCRIPTION:Owlz vs. Chukars\n\nFollow on MiLB First Pitch: https://stza.co/+xPBJ-2e\n\nShop: https://stza.co/+xPBJ-17\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144549Z
LAST-MODIFIED:20180213T144549Z
TRANSP:OPAQUE
END:VEVENT
* Owlz vs. Chukars
<2018-06-25 Mon 20:05-23:05>
:PROPERTIES:
:ID:       1uMSTGOXAVX4NK26Pw-a1jWV@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Owlz vs. Chukars Owlz vs. Chukars

Follow on MiLB First Pitch  https //stza.co/+xPBK-2G

Shop  https //stza.co/+xPBK-1h

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Owlz vs. Chukars
END:VALARM
DTSTART:20180626T010500Z
DTEND:20180626T040500Z
UID:1uMSTGOXAVX4NK26Pw-a1jWV@stanza.co
SUMMARY:Owlz vs. Chukars
DESCRIPTION:Owlz vs. Chukars\n\nFollow on MiLB First Pitch: https://stza.co/+xPBK-2G\n\nShop: https://stza.co/+xPBK-1h\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144549Z
LAST-MODIFIED:20180213T144549Z
TRANSP:OPAQUE
END:VEVENT
* Owlz @ Raptors
<2018-06-26 Tue 20:00-23:00>
:PROPERTIES:
:ID:       A5VpyKuehUjxm95DxmbYqfDA@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Owlz @ Raptors Owlz @ Raptors

Follow on MiLB First Pitch  https //stza.co/+x$9r-3u

Shop  https //stza.co/+x$9r-b

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Owlz @ Raptors
END:VALARM
DTSTART:20180627T010000Z
DTEND:20180627T040000Z
UID:A5VpyKuehUjxm95DxmbYqfDA@stanza.co
SUMMARY:Owlz @ Raptors
DESCRIPTION:Owlz @ Raptors\n\nFollow on MiLB First Pitch: https://stza.co/+x$9r-3u\n\nShop: https://stza.co/+x$9r-b\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144549Z
LAST-MODIFIED:20180213T144549Z
TRANSP:OPAQUE
END:VEVENT
* Owlz @ Raptors
<2018-06-27 Wed 20:00-23:00>
:PROPERTIES:
:ID:       QzJHsmafTgq7sQGaM8HBYYfP@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Owlz @ Raptors Owlz @ Raptors

Follow on MiLB First Pitch  https //stza.co/+x$9s-2D

Shop  https //stza.co/+x$9s-17

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Owlz @ Raptors
END:VALARM
DTSTART:20180628T010000Z
DTEND:20180628T040000Z
UID:QzJHsmafTgq7sQGaM8HBYYfP@stanza.co
SUMMARY:Owlz @ Raptors
DESCRIPTION:Owlz @ Raptors\n\nFollow on MiLB First Pitch: https://stza.co/+x$9s-2D\n\nShop: https://stza.co/+x$9s-17\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144549Z
LAST-MODIFIED:20180213T144549Z
TRANSP:OPAQUE
END:VEVENT
* Owlz vs. Raptors
<2018-06-28 Thu 20:05-23:05>
:PROPERTIES:
:ID:       F3VGBsuUOiemztM1H8vo57f-@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Owlz vs. Raptors Owlz vs. Raptors

Follow on MiLB First Pitch  https //stza.co/+xPBM-2l

Shop  https //stza.co/+xPBM-7

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Owlz vs. Raptors
END:VALARM
DTSTART:20180629T010500Z
DTEND:20180629T040500Z
UID:F3VGBsuUOiemztM1H8vo57f-@stanza.co
SUMMARY:Owlz vs. Raptors
DESCRIPTION:Owlz vs. Raptors\n\nFollow on MiLB First Pitch: https://stza.co/+xPBM-2l\n\nShop: https://stza.co/+xPBM-7\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144549Z
LAST-MODIFIED:20180213T144549Z
TRANSP:OPAQUE
END:VEVENT
* Owlz vs. Raptors
<2018-06-29 Fri 20:05-23:05>
:PROPERTIES:
:ID:       zFCOD5Tc53BeWlCGXu-v0BZQ@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Owlz vs. Raptors Owlz vs. Raptors

Follow on MiLB First Pitch  https //stza.co/+xPBO-1X

Shop  https //stza.co/+xPBO-l

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Owlz vs. Raptors
END:VALARM
DTSTART:20180630T010500Z
DTEND:20180630T040500Z
UID:zFCOD5Tc53BeWlCGXu-v0BZQ@stanza.co
SUMMARY:Owlz vs. Raptors
DESCRIPTION:Owlz vs. Raptors\n\nFollow on MiLB First Pitch: https://stza.co/+xPBO-1X\n\nShop: https://stza.co/+xPBO-l\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144549Z
LAST-MODIFIED:20180213T144549Z
TRANSP:OPAQUE
END:VEVENT
* Owlz vs. Rockies
<2018-06-30 Sat 20:05-23:05>
:PROPERTIES:
:ID:       p0fchTcrGUUh7S-Kz0RtdcpC@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Owlz vs. Rockies Owlz vs. Rockies

Follow on MiLB First Pitch  https //stza.co/+xPBQ-1j

Shop  https //stza.co/+xPBQ-3b

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Owlz vs. Rockies
END:VALARM
DTSTART:20180701T010500Z
DTEND:20180701T040500Z
UID:p0fchTcrGUUh7S-Kz0RtdcpC@stanza.co
SUMMARY:Owlz vs. Rockies
DESCRIPTION:Owlz vs. Rockies\n\nFollow on MiLB First Pitch: https://stza.co/+xPBQ-1j\n\nShop: https://stza.co/+xPBQ-3b\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144549Z
LAST-MODIFIED:20180213T144549Z
TRANSP:OPAQUE
END:VEVENT
* Owlz vs. Rockies
<2018-07-01 Sun 17:05-20:05>
:PROPERTIES:
:ID:       2_Q34jeA07O48uwbIMt7c84l@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Owlz vs. Rockies Owlz vs. Rockies

Follow on MiLB First Pitch  https //stza.co/+xPBS-1B

Shop  https //stza.co/+xPBS-3L

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Owlz vs. Rockies
END:VALARM
DTSTART:20180701T220500Z
DTEND:20180702T010500Z
UID:2_Q34jeA07O48uwbIMt7c84l@stanza.co
SUMMARY:Owlz vs. Rockies
DESCRIPTION:Owlz vs. Rockies\n\nFollow on MiLB First Pitch: https://stza.co/+xPBS-1B\n\nShop: https://stza.co/+xPBS-3L\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144549Z
LAST-MODIFIED:20180213T144549Z
TRANSP:OPAQUE
END:VEVENT
* Owlz vs. Rockies
<2018-07-02 Mon 20:05-23:05>
:PROPERTIES:
:ID:       fKfLUdvPhBo3pkE4goNY141O@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Owlz vs. Rockies Owlz vs. Rockies

Follow on MiLB First Pitch  https //stza.co/+xPBU-3B

Shop  https //stza.co/+xPBU-Z

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Owlz vs. Rockies
END:VALARM
DTSTART:20180703T010500Z
DTEND:20180703T040500Z
UID:fKfLUdvPhBo3pkE4goNY141O@stanza.co
SUMMARY:Owlz vs. Rockies
DESCRIPTION:Owlz vs. Rockies\n\nFollow on MiLB First Pitch: https://stza.co/+xPBU-3B\n\nShop: https://stza.co/+xPBU-Z\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144549Z
LAST-MODIFIED:20180213T144549Z
TRANSP:OPAQUE
END:VEVENT
* Owlz vs. Rockies
<2018-07-03 Tue 20:05-23:05>
:PROPERTIES:
:ID:       CCZT6qxaT1EEwGADB0D1iwQy@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Owlz vs. Rockies Owlz vs. Rockies

Follow on MiLB First Pitch  https //stza.co/+xPBX-Y

Shop  https //stza.co/+xPBX-3l

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Owlz vs. Rockies
END:VALARM
DTSTART:20180704T010500Z
DTEND:20180704T040500Z
UID:CCZT6qxaT1EEwGADB0D1iwQy@stanza.co
SUMMARY:Owlz vs. Rockies
DESCRIPTION:Owlz vs. Rockies\n\nFollow on MiLB First Pitch: https://stza.co/+xPBX-Y\n\nShop: https://stza.co/+xPBX-3l\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144549Z
LAST-MODIFIED:20180213T144549Z
TRANSP:OPAQUE
END:VEVENT
* Owlz @ Chukars
<2018-07-04 Wed 17:30-20:30>
:PROPERTIES:
:ID:       hv8Z09ckzDYwe5lMSdvlfHMA@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Owlz @ Chukars Owlz @ Chukars

Follow on MiLB First Pitch  https //stza.co/+xZWa-Q

Shop  https //stza.co/+xZWa-1i

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Owlz @ Chukars
END:VALARM
DTSTART:20180704T223000Z
DTEND:20180705T013000Z
UID:hv8Z09ckzDYwe5lMSdvlfHMA@stanza.co
SUMMARY:Owlz @ Chukars
DESCRIPTION:Owlz @ Chukars\n\nFollow on MiLB First Pitch: https://stza.co/+xZWa-Q\n\nShop: https://stza.co/+xZWa-1i\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144549Z
LAST-MODIFIED:20180213T144549Z
TRANSP:OPAQUE
END:VEVENT
* Owlz @ Chukars
<2018-07-05 Thu 20:15-23:15>
:PROPERTIES:
:ID:       wCa6aoW9AI09ypIU6UR35QnP@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Owlz @ Chukars Owlz @ Chukars

Follow on MiLB First Pitch  https //stza.co/+xZWb-2T

Shop  https //stza.co/+xZWb-24

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Owlz @ Chukars
END:VALARM
DTSTART:20180706T011500Z
DTEND:20180706T041500Z
UID:wCa6aoW9AI09ypIU6UR35QnP@stanza.co
SUMMARY:Owlz @ Chukars
DESCRIPTION:Owlz @ Chukars\n\nFollow on MiLB First Pitch: https://stza.co/+xZWb-2T\n\nShop: https://stza.co/+xZWb-24\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144549Z
LAST-MODIFIED:20180213T144549Z
TRANSP:OPAQUE
END:VEVENT
* Owlz @ Chukars
<2018-07-06 Fri 20:15-23:15>
:PROPERTIES:
:ID:       smQAN7iDlXojL_t6Jk8nf0OH@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Owlz @ Chukars Owlz @ Chukars

Follow on MiLB First Pitch  https //stza.co/+xZWc-2q

Shop  https //stza.co/+xZWc-1W

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Owlz @ Chukars
END:VALARM
DTSTART:20180707T011500Z
DTEND:20180707T041500Z
UID:smQAN7iDlXojL_t6Jk8nf0OH@stanza.co
SUMMARY:Owlz @ Chukars
DESCRIPTION:Owlz @ Chukars\n\nFollow on MiLB First Pitch: https://stza.co/+xZWc-2q\n\nShop: https://stza.co/+xZWc-1W\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144549Z
LAST-MODIFIED:20180213T144549Z
TRANSP:OPAQUE
END:VEVENT
* Owlz vs. Chukars
<2018-07-07 Sat 20:05-23:05>
:PROPERTIES:
:ID:       3d6dfKpeBx-xME3RcXXiu9Rj@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Owlz vs. Chukars Owlz vs. Chukars

Follow on MiLB First Pitch  https //stza.co/+xPBZ-i

Shop  https //stza.co/+xPBZ-1R

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Owlz vs. Chukars
END:VALARM
DTSTART:20180708T010500Z
DTEND:20180708T040500Z
UID:3d6dfKpeBx-xME3RcXXiu9Rj@stanza.co
SUMMARY:Owlz vs. Chukars
DESCRIPTION:Owlz vs. Chukars\n\nFollow on MiLB First Pitch: https://stza.co/+xPBZ-i\n\nShop: https://stza.co/+xPBZ-1R\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144549Z
LAST-MODIFIED:20180213T144549Z
TRANSP:OPAQUE
END:VEVENT
* Owlz vs. Chukars
<2018-07-08 Sun 17:05-20:05>
:PROPERTIES:
:ID:       GuiWcCmZRBDilBou8hx3kaD6@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Owlz vs. Chukars Owlz vs. Chukars

Follow on MiLB First Pitch  https //stza.co/+xPB_-11

Shop  https //stza.co/+xPB_-12

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Owlz vs. Chukars
END:VALARM
DTSTART:20180708T220500Z
DTEND:20180709T010500Z
UID:GuiWcCmZRBDilBou8hx3kaD6@stanza.co
SUMMARY:Owlz vs. Chukars
DESCRIPTION:Owlz vs. Chukars\n\nFollow on MiLB First Pitch: https://stza.co/+xPB_-11\n\nShop: https://stza.co/+xPB_-12\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144549Z
LAST-MODIFIED:20180213T144549Z
TRANSP:OPAQUE
END:VEVENT
* Owlz @ Voyagers
<2018-07-10 Tue>--<2018-07-09 Mon>
:PROPERTIES:
:ID:       J2lR_XbBpxf_DeHcHuS421vG@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Owlz @ Voyagers Owlz @ Voyagers

Follow on MiLB First Pitch  https //stza.co/+xCEC-3H

Shop  https //stza.co/+xCEC-3g

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Owlz @ Voyagers
END:VALARM
DTSTART;VALUE=DATE:20180710
DTEND;VALUE=DATE:20180710
UID:J2lR_XbBpxf_DeHcHuS421vG@stanza.co
SUMMARY:Owlz @ Voyagers
DESCRIPTION:Owlz @ Voyagers\n\nFollow on MiLB First Pitch: https://stza.co/+xCEC-3H\n\nShop: https://stza.co/+xCEC-3g\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144549Z
LAST-MODIFIED:20180213T144549Z
TRANSP:OPAQUE
END:VEVENT
* Owlz @ Voyagers
<2018-07-11 Wed>--<2018-07-10 Tue>
:PROPERTIES:
:ID:       iehqWmYWIgibWNrtH-pPiGy7@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Owlz @ Voyagers Owlz @ Voyagers

Follow on MiLB First Pitch  https //stza.co/+xCED-3G

Shop  https //stza.co/+xCED-Z

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Owlz @ Voyagers
END:VALARM
DTSTART;VALUE=DATE:20180711
DTEND;VALUE=DATE:20180711
UID:iehqWmYWIgibWNrtH-pPiGy7@stanza.co
SUMMARY:Owlz @ Voyagers
DESCRIPTION:Owlz @ Voyagers\n\nFollow on MiLB First Pitch: https://stza.co/+xCED-3G\n\nShop: https://stza.co/+xCED-Z\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144549Z
LAST-MODIFIED:20180213T144549Z
TRANSP:OPAQUE
END:VEVENT
* Owlz @ Voyagers
<2018-07-12 Thu>--<2018-07-11 Wed>
:PROPERTIES:
:ID:       h1sWmY1N1wf9_Na16dxHbDuH@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Owlz @ Voyagers Owlz @ Voyagers

Follow on MiLB First Pitch  https //stza.co/+xCEE-1g

Shop  https //stza.co/+xCEE-1a

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Owlz @ Voyagers
END:VALARM
DTSTART;VALUE=DATE:20180712
DTEND;VALUE=DATE:20180712
UID:h1sWmY1N1wf9_Na16dxHbDuH@stanza.co
SUMMARY:Owlz @ Voyagers
DESCRIPTION:Owlz @ Voyagers\n\nFollow on MiLB First Pitch: https://stza.co/+xCEE-1g\n\nShop: https://stza.co/+xCEE-1a\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144549Z
LAST-MODIFIED:20180213T144549Z
TRANSP:OPAQUE
END:VEVENT
* Owlz @ Voyagers
<2018-07-13 Fri>--<2018-07-12 Thu>
:PROPERTIES:
:ID:       Qp_rWGj2xV74eAyRaCImwvw7@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Owlz @ Voyagers Owlz @ Voyagers

Follow on MiLB First Pitch  https //stza.co/+xCEF-3C

Shop  https //stza.co/+xCEF-2q

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Owlz @ Voyagers
END:VALARM
DTSTART;VALUE=DATE:20180713
DTEND;VALUE=DATE:20180713
UID:Qp_rWGj2xV74eAyRaCImwvw7@stanza.co
SUMMARY:Owlz @ Voyagers
DESCRIPTION:Owlz @ Voyagers\n\nFollow on MiLB First Pitch: https://stza.co/+xCEF-3C\n\nShop: https://stza.co/+xCEF-2q\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144549Z
LAST-MODIFIED:20180213T144549Z
TRANSP:OPAQUE
END:VEVENT
* Owlz @ Mustangs
<2018-07-14 Sat 19:05-22:05>
:PROPERTIES:
:ID:       3ekRKOfCWSfk-0hQsolmZ8X6@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Owlz @ Mustangs Owlz @ Mustangs

Follow on MiLB First Pitch  https //stza.co/+xSOZ-27

Shop  https //stza.co/+xSOZ-2O

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Owlz @ Mustangs
END:VALARM
DTSTART:20180715T000500Z
DTEND:20180715T030500Z
UID:3ekRKOfCWSfk-0hQsolmZ8X6@stanza.co
SUMMARY:Owlz @ Mustangs
DESCRIPTION:Owlz @ Mustangs\n\nFollow on MiLB First Pitch: https://stza.co/+xSOZ-27\n\nShop: https://stza.co/+xSOZ-2O\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144549Z
LAST-MODIFIED:20180213T144549Z
TRANSP:OPAQUE
END:VEVENT
* Owlz @ Mustangs
<2018-07-15 Sun 14:05-17:05>
:PROPERTIES:
:ID:       SAnt4sIQYnDmym66PcHCYxsK@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Owlz @ Mustangs Owlz @ Mustangs

Follow on MiLB First Pitch  https //stza.co/+xSO_-36

Shop  https //stza.co/+xSO_-g

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Owlz @ Mustangs
END:VALARM
DTSTART:20180715T190500Z
DTEND:20180715T220500Z
UID:SAnt4sIQYnDmym66PcHCYxsK@stanza.co
SUMMARY:Owlz @ Mustangs
DESCRIPTION:Owlz @ Mustangs\n\nFollow on MiLB First Pitch: https://stza.co/+xSO_-36\n\nShop: https://stza.co/+xSO_-g\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144549Z
LAST-MODIFIED:20180213T144549Z
TRANSP:OPAQUE
END:VEVENT
* Owlz @ Mustangs
<2018-07-16 Mon 20:05-23:05>
:PROPERTIES:
:ID:       o2qHYfRrfhao1qZ9UYBUHxr-@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Owlz @ Mustangs Owlz @ Mustangs

Follow on MiLB First Pitch  https //stza.co/+xSO$-2$

Shop  https //stza.co/+xSO$-1y

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Owlz @ Mustangs
END:VALARM
DTSTART:20180717T010500Z
DTEND:20180717T040500Z
UID:o2qHYfRrfhao1qZ9UYBUHxr-@stanza.co
SUMMARY:Owlz @ Mustangs
DESCRIPTION:Owlz @ Mustangs\n\nFollow on MiLB First Pitch: https://stza.co/+xSO$-2$\n\nShop: https://stza.co/+xSO$-1y\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144549Z
LAST-MODIFIED:20180213T144549Z
TRANSP:OPAQUE
END:VEVENT
* Owlz vs. Voyagers
<2018-07-18 Wed 20:05-23:05>
:PROPERTIES:
:ID:       W0WKdTAeOyxUfUvyioxIz4Xv@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Owlz vs. Voyagers Owlz vs. Voyagers

Follow on MiLB First Pitch  https //stza.co/+xPC1-16

Shop  https //stza.co/+xPC1-2k

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Owlz vs. Voyagers
END:VALARM
DTSTART:20180719T010500Z
DTEND:20180719T040500Z
UID:W0WKdTAeOyxUfUvyioxIz4Xv@stanza.co
SUMMARY:Owlz vs. Voyagers
DESCRIPTION:Owlz vs. Voyagers\n\nFollow on MiLB First Pitch: https://stza.co/+xPC1-16\n\nShop: https://stza.co/+xPC1-2k\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144549Z
LAST-MODIFIED:20180213T144549Z
TRANSP:OPAQUE
END:VEVENT
* Owlz vs. Voyagers
<2018-07-19 Thu 20:05-23:05>
:PROPERTIES:
:ID:       tsxiIwxS82Jj6eMP7qlK2qXZ@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Owlz vs. Voyagers Owlz vs. Voyagers

Follow on MiLB First Pitch  https //stza.co/+xPC3-15

Shop  https //stza.co/+xPC3-25

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Owlz vs. Voyagers
END:VALARM
DTSTART:20180720T010500Z
DTEND:20180720T040500Z
UID:tsxiIwxS82Jj6eMP7qlK2qXZ@stanza.co
SUMMARY:Owlz vs. Voyagers
DESCRIPTION:Owlz vs. Voyagers\n\nFollow on MiLB First Pitch: https://stza.co/+xPC3-15\n\nShop: https://stza.co/+xPC3-25\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144549Z
LAST-MODIFIED:20180213T144549Z
TRANSP:OPAQUE
END:VEVENT
* Owlz vs. Voyagers
<2018-07-20 Fri 20:05-23:05>
:PROPERTIES:
:ID:       lLTG_MGE--RT_ZrXS5xUnC8U@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Owlz vs. Voyagers Owlz vs. Voyagers

Follow on MiLB First Pitch  https //stza.co/+xPC5-2z

Shop  https //stza.co/+xPC5-2u

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Owlz vs. Voyagers
END:VALARM
DTSTART:20180721T010500Z
DTEND:20180721T040500Z
UID:lLTG_MGE--RT_ZrXS5xUnC8U@stanza.co
SUMMARY:Owlz vs. Voyagers
DESCRIPTION:Owlz vs. Voyagers\n\nFollow on MiLB First Pitch: https://stza.co/+xPC5-2z\n\nShop: https://stza.co/+xPC5-2u\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144549Z
LAST-MODIFIED:20180213T144549Z
TRANSP:OPAQUE
END:VEVENT
* Owlz vs. Mustangs
<2018-07-21 Sat 20:05-23:05>
:PROPERTIES:
:ID:       9gEskb-jC9aF-ygyaz_zPPTR@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Owlz vs. Mustangs Owlz vs. Mustangs

Follow on MiLB First Pitch  https //stza.co/+xPC7-1y

Shop  https //stza.co/+xPC7-u

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Owlz vs. Mustangs
END:VALARM
DTSTART:20180722T010500Z
DTEND:20180722T040500Z
UID:9gEskb-jC9aF-ygyaz_zPPTR@stanza.co
SUMMARY:Owlz vs. Mustangs
DESCRIPTION:Owlz vs. Mustangs\n\nFollow on MiLB First Pitch: https://stza.co/+xPC7-1y\n\nShop: https://stza.co/+xPC7-u\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144549Z
LAST-MODIFIED:20180213T144549Z
TRANSP:OPAQUE
END:VEVENT
* Owlz vs. Mustangs
<2018-07-22 Sun 17:05-20:05>
:PROPERTIES:
:ID:       BJplzCf2m_dhOS-Yr9NruqDn@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Owlz vs. Mustangs Owlz vs. Mustangs

Follow on MiLB First Pitch  https //stza.co/+xPC9-E

Shop  https //stza.co/+xPC9-X

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Owlz vs. Mustangs
END:VALARM
DTSTART:20180722T220500Z
DTEND:20180723T010500Z
UID:BJplzCf2m_dhOS-Yr9NruqDn@stanza.co
SUMMARY:Owlz vs. Mustangs
DESCRIPTION:Owlz vs. Mustangs\n\nFollow on MiLB First Pitch: https://stza.co/+xPC9-E\n\nShop: https://stza.co/+xPC9-X\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144549Z
LAST-MODIFIED:20180213T144549Z
TRANSP:OPAQUE
END:VEVENT
* Owlz vs. Mustangs
<2018-07-23 Mon 20:05-23:05>
:PROPERTIES:
:ID:       QdnI4qG0o4BLBW9c4A4fxA-a@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Owlz vs. Mustangs Owlz vs. Mustangs

Follow on MiLB First Pitch  https //stza.co/+xPCa-3O

Shop  https //stza.co/+xPCa-1Q

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Owlz vs. Mustangs
END:VALARM
DTSTART:20180724T010500Z
DTEND:20180724T040500Z
UID:QdnI4qG0o4BLBW9c4A4fxA-a@stanza.co
SUMMARY:Owlz vs. Mustangs
DESCRIPTION:Owlz vs. Mustangs\n\nFollow on MiLB First Pitch: https://stza.co/+xPCa-3O\n\nShop: https://stza.co/+xPCa-1Q\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144549Z
LAST-MODIFIED:20180213T144549Z
TRANSP:OPAQUE
END:VEVENT
* Owlz vs. Mustangs
<2018-07-24 Tue 20:05-23:05>
:PROPERTIES:
:ID:       mDpQJRliRMeiwK1SYw0zmgM2@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Owlz vs. Mustangs Owlz vs. Mustangs

Follow on MiLB First Pitch  https //stza.co/+xPCc-2A

Shop  https //stza.co/+xPCc-S

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Owlz vs. Mustangs
END:VALARM
DTSTART:20180725T010500Z
DTEND:20180725T040500Z
UID:mDpQJRliRMeiwK1SYw0zmgM2@stanza.co
SUMMARY:Owlz vs. Mustangs
DESCRIPTION:Owlz vs. Mustangs\n\nFollow on MiLB First Pitch: https://stza.co/+xPCc-2A\n\nShop: https://stza.co/+xPCc-S\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144549Z
LAST-MODIFIED:20180213T144549Z
TRANSP:OPAQUE
END:VEVENT
* Owlz @ Chukars
<2018-07-25 Wed 20:15-23:15>
:PROPERTIES:
:ID:       nofeT9cQ7jEjByFmsKNP8xpq@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Owlz @ Chukars Owlz @ Chukars

Follow on MiLB First Pitch  https //stza.co/+xZWd-1k

Shop  https //stza.co/+xZWd-9

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Owlz @ Chukars
END:VALARM
DTSTART:20180726T011500Z
DTEND:20180726T041500Z
UID:nofeT9cQ7jEjByFmsKNP8xpq@stanza.co
SUMMARY:Owlz @ Chukars
DESCRIPTION:Owlz @ Chukars\n\nFollow on MiLB First Pitch: https://stza.co/+xZWd-1k\n\nShop: https://stza.co/+xZWd-9\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144549Z
LAST-MODIFIED:20180213T144549Z
TRANSP:OPAQUE
END:VEVENT
* Owlz @ Chukars
<2018-07-26 Thu 20:15-23:15>
:PROPERTIES:
:ID:       rBQaNVWx_FgwdTOtdDxOo_5i@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Owlz @ Chukars Owlz @ Chukars

Follow on MiLB First Pitch  https //stza.co/+xZWe-1Y

Shop  https //stza.co/+xZWe-16

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Owlz @ Chukars
END:VALARM
DTSTART:20180727T011500Z
DTEND:20180727T041500Z
UID:rBQaNVWx_FgwdTOtdDxOo_5i@stanza.co
SUMMARY:Owlz @ Chukars
DESCRIPTION:Owlz @ Chukars\n\nFollow on MiLB First Pitch: https://stza.co/+xZWe-1Y\n\nShop: https://stza.co/+xZWe-16\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144549Z
LAST-MODIFIED:20180213T144549Z
TRANSP:OPAQUE
END:VEVENT
* Owlz @ Chukars
<2018-07-27 Fri 20:15-23:15>
:PROPERTIES:
:ID:       zb6ru0LjRA1i9IUTUJAsRctJ@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Owlz @ Chukars Owlz @ Chukars

Follow on MiLB First Pitch  https //stza.co/+xZWf-2P

Shop  https //stza.co/+xZWf-F

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Owlz @ Chukars
END:VALARM
DTSTART:20180728T011500Z
DTEND:20180728T041500Z
UID:zb6ru0LjRA1i9IUTUJAsRctJ@stanza.co
SUMMARY:Owlz @ Chukars
DESCRIPTION:Owlz @ Chukars\n\nFollow on MiLB First Pitch: https://stza.co/+xZWf-2P\n\nShop: https://stza.co/+xZWf-F\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144549Z
LAST-MODIFIED:20180213T144549Z
TRANSP:OPAQUE
END:VEVENT
* Owlz @ Rockies
<2018-07-28 Sat 19:40-22:40>
:PROPERTIES:
:ID:       tCwDxJmk3qDTMcP4r5O-RNjt@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Owlz @ Rockies Owlz @ Rockies

Follow on MiLB First Pitch  https //stza.co/+xJ8C-3z

Shop  https //stza.co/+xJ8C-3k

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Owlz @ Rockies
END:VALARM
DTSTART:20180729T004000Z
DTEND:20180729T034000Z
UID:tCwDxJmk3qDTMcP4r5O-RNjt@stanza.co
SUMMARY:Owlz @ Rockies
DESCRIPTION:Owlz @ Rockies\n\nFollow on MiLB First Pitch: https://stza.co/+xJ8C-3z\n\nShop: https://stza.co/+xJ8C-3k\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144549Z
LAST-MODIFIED:20180213T144549Z
TRANSP:OPAQUE
END:VEVENT
* Owlz @ Rockies
<2018-07-29 Sun 18:00-21:00>
:PROPERTIES:
:ID:       uzeUZgABH63AgytUbIOOOilS@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Owlz @ Rockies Owlz @ Rockies

Follow on MiLB First Pitch  https //stza.co/+xJ8D-3b

Shop  https //stza.co/+xJ8D-3q

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Owlz @ Rockies
END:VALARM
DTSTART:20180729T230000Z
DTEND:20180730T020000Z
UID:uzeUZgABH63AgytUbIOOOilS@stanza.co
SUMMARY:Owlz @ Rockies
DESCRIPTION:Owlz @ Rockies\n\nFollow on MiLB First Pitch: https://stza.co/+xJ8D-3b\n\nShop: https://stza.co/+xJ8D-3q\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144549Z
LAST-MODIFIED:20180213T144549Z
TRANSP:OPAQUE
END:VEVENT
* Owlz vs. Chukars
<2018-07-30 Mon 20:05-23:05>
:PROPERTIES:
:ID:       KCsAX35IlDKpSBy7LBSrV-S_@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Owlz vs. Chukars Owlz vs. Chukars

Follow on MiLB First Pitch  https //stza.co/+xPCf-2c

Shop  https //stza.co/+xPCf-U

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Owlz vs. Chukars
END:VALARM
DTSTART:20180731T010500Z
DTEND:20180731T040500Z
UID:KCsAX35IlDKpSBy7LBSrV-S_@stanza.co
SUMMARY:Owlz vs. Chukars
DESCRIPTION:Owlz vs. Chukars\n\nFollow on MiLB First Pitch: https://stza.co/+xPCf-2c\n\nShop: https://stza.co/+xPCf-U\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144549Z
LAST-MODIFIED:20180213T144549Z
TRANSP:OPAQUE
END:VEVENT
* Owlz vs. Chukars
<2018-07-31 Tue 20:05-23:05>
:PROPERTIES:
:ID:       e71R-u0IPkU2FW-tb94Ft-E3@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Owlz vs. Chukars Owlz vs. Chukars

Follow on MiLB First Pitch  https //stza.co/+xPCh-3h

Shop  https //stza.co/+xPCh-1Y

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Owlz vs. Chukars
END:VALARM
DTSTART:20180801T010500Z
DTEND:20180801T040500Z
UID:e71R-u0IPkU2FW-tb94Ft-E3@stanza.co
SUMMARY:Owlz vs. Chukars
DESCRIPTION:Owlz vs. Chukars\n\nFollow on MiLB First Pitch: https://stza.co/+xPCh-3h\n\nShop: https://stza.co/+xPCh-1Y\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144549Z
LAST-MODIFIED:20180213T144549Z
TRANSP:OPAQUE
END:VEVENT
* Owlz vs. Chukars
<2018-08-01 Wed 20:05-23:05>
:PROPERTIES:
:ID:       2-xVfkuLzf7ckuib-ta6YWlw@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Owlz vs. Chukars Owlz vs. Chukars

Follow on MiLB First Pitch  https //stza.co/+xPCj-3w

Shop  https //stza.co/+xPCj-3K

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Owlz vs. Chukars
END:VALARM
DTSTART:20180802T010500Z
DTEND:20180802T040500Z
UID:2-xVfkuLzf7ckuib-ta6YWlw@stanza.co
SUMMARY:Owlz vs. Chukars
DESCRIPTION:Owlz vs. Chukars\n\nFollow on MiLB First Pitch: https://stza.co/+xPCj-3w\n\nShop: https://stza.co/+xPCj-3K\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144549Z
LAST-MODIFIED:20180213T144549Z
TRANSP:OPAQUE
END:VEVENT
* Owlz @ Raptors
<2018-08-02 Thu 20:00-23:00>
:PROPERTIES:
:ID:       j53RGE8isF32bllKP2ny4s8P@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Owlz @ Raptors Owlz @ Raptors

Follow on MiLB First Pitch  https //stza.co/+x$9t-3L

Shop  https //stza.co/+x$9t-3R

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Owlz @ Raptors
END:VALARM
DTSTART:20180803T010000Z
DTEND:20180803T040000Z
UID:j53RGE8isF32bllKP2ny4s8P@stanza.co
SUMMARY:Owlz @ Raptors
DESCRIPTION:Owlz @ Raptors\n\nFollow on MiLB First Pitch: https://stza.co/+x$9t-3L\n\nShop: https://stza.co/+x$9t-3R\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144549Z
LAST-MODIFIED:20180213T144549Z
TRANSP:OPAQUE
END:VEVENT
* Owlz @ Raptors
<2018-08-03 Fri 20:00-23:00>
:PROPERTIES:
:ID:       NxRd1ummLBgKuZaLRNGiHjuR@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Owlz @ Raptors Owlz @ Raptors

Follow on MiLB First Pitch  https //stza.co/+x$9u-2$

Shop  https //stza.co/+x$9u-2N

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Owlz @ Raptors
END:VALARM
DTSTART:20180804T010000Z
DTEND:20180804T040000Z
UID:NxRd1ummLBgKuZaLRNGiHjuR@stanza.co
SUMMARY:Owlz @ Raptors
DESCRIPTION:Owlz @ Raptors\n\nFollow on MiLB First Pitch: https://stza.co/+x$9u-2$\n\nShop: https://stza.co/+x$9u-2N\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144549Z
LAST-MODIFIED:20180213T144549Z
TRANSP:OPAQUE
END:VEVENT
* Owlz @ Raptors
<2018-08-04 Sat 20:00-23:00>
:PROPERTIES:
:ID:       Uu4s6MSZTZwdsMXKI0-6CnzB@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Owlz @ Raptors Owlz @ Raptors

Follow on MiLB First Pitch  https //stza.co/+x$9v-3s

Shop  https //stza.co/+x$9v-O

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Owlz @ Raptors
END:VALARM
DTSTART:20180805T010000Z
DTEND:20180805T040000Z
UID:Uu4s6MSZTZwdsMXKI0-6CnzB@stanza.co
SUMMARY:Owlz @ Raptors
DESCRIPTION:Owlz @ Raptors\n\nFollow on MiLB First Pitch: https://stza.co/+x$9v-3s\n\nShop: https://stza.co/+x$9v-O\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144549Z
LAST-MODIFIED:20180213T144549Z
TRANSP:OPAQUE
END:VEVENT
* Owlz @ Raptors
<2018-08-05 Sun 17:00-20:00>
:PROPERTIES:
:ID:       VQxvKwCffDtPHAVFSARqzOC7@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Owlz @ Raptors Owlz @ Raptors

Follow on MiLB First Pitch  https //stza.co/+x$9w-S

Shop  https //stza.co/+x$9w-R

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Owlz @ Raptors
END:VALARM
DTSTART:20180805T220000Z
DTEND:20180806T010000Z
UID:VQxvKwCffDtPHAVFSARqzOC7@stanza.co
SUMMARY:Owlz @ Raptors
DESCRIPTION:Owlz @ Raptors\n\nFollow on MiLB First Pitch: https://stza.co/+x$9w-S\n\nShop: https://stza.co/+x$9w-R\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144549Z
LAST-MODIFIED:20180213T144549Z
TRANSP:OPAQUE
END:VEVENT
* Owlz vs. Osprey
<2018-08-09 Thu 20:05-23:05>
:PROPERTIES:
:ID:       OMJLIXGfQZuWtRqo-1LSJ4IT@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Owlz vs. Osprey Owlz vs. Osprey

Follow on MiLB First Pitch  https //stza.co/+xPCl-2w

Shop  https //stza.co/+xPCl-I

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Owlz vs. Osprey
END:VALARM
DTSTART:20180810T010500Z
DTEND:20180810T040500Z
UID:OMJLIXGfQZuWtRqo-1LSJ4IT@stanza.co
SUMMARY:Owlz vs. Osprey
DESCRIPTION:Owlz vs. Osprey\n\nFollow on MiLB First Pitch: https://stza.co/+xPCl-2w\n\nShop: https://stza.co/+xPCl-I\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144549Z
LAST-MODIFIED:20180213T144549Z
TRANSP:OPAQUE
END:VEVENT
* Owlz vs. Osprey
<2018-08-10 Fri 20:05-23:05>
:PROPERTIES:
:ID:       FiYW75MHrna_HXZfn0jwz7id@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Owlz vs. Osprey Owlz vs. Osprey

Follow on MiLB First Pitch  https //stza.co/+xPCn-a

Shop  https //stza.co/+xPCn-2j

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Owlz vs. Osprey
END:VALARM
DTSTART:20180811T010500Z
DTEND:20180811T040500Z
UID:FiYW75MHrna_HXZfn0jwz7id@stanza.co
SUMMARY:Owlz vs. Osprey
DESCRIPTION:Owlz vs. Osprey\n\nFollow on MiLB First Pitch: https://stza.co/+xPCn-a\n\nShop: https://stza.co/+xPCn-2j\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144549Z
LAST-MODIFIED:20180213T144549Z
TRANSP:OPAQUE
END:VEVENT
* Owlz vs. Osprey
<2018-08-11 Sat 20:05-23:05>
:PROPERTIES:
:ID:       D-oOJzftDyeSIA-nw2624rtq@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Owlz vs. Osprey Owlz vs. Osprey

Follow on MiLB First Pitch  https //stza.co/+xPCo-2C

Shop  https //stza.co/+xPCo-10

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Owlz vs. Osprey
END:VALARM
DTSTART:20180812T010500Z
DTEND:20180812T040500Z
UID:D-oOJzftDyeSIA-nw2624rtq@stanza.co
SUMMARY:Owlz vs. Osprey
DESCRIPTION:Owlz vs. Osprey\n\nFollow on MiLB First Pitch: https://stza.co/+xPCo-2C\n\nShop: https://stza.co/+xPCo-10\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144549Z
LAST-MODIFIED:20180213T144549Z
TRANSP:OPAQUE
END:VEVENT
* Owlz vs. Osprey
<2018-08-12 Sun 17:05-20:05>
:PROPERTIES:
:ID:       PWY7jtctlwizeoindYj6A0SH@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Owlz vs. Osprey Owlz vs. Osprey

Follow on MiLB First Pitch  https //stza.co/+xPCr-1V

Shop  https //stza.co/+xPCr-2J

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Owlz vs. Osprey
END:VALARM
DTSTART:20180812T220500Z
DTEND:20180813T010500Z
UID:PWY7jtctlwizeoindYj6A0SH@stanza.co
SUMMARY:Owlz vs. Osprey
DESCRIPTION:Owlz vs. Osprey\n\nFollow on MiLB First Pitch: https://stza.co/+xPCr-1V\n\nShop: https://stza.co/+xPCr-2J\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144549Z
LAST-MODIFIED:20180213T144549Z
TRANSP:OPAQUE
END:VEVENT
* Owlz vs. Brewers
<2018-08-13 Mon 20:05-23:05>
:PROPERTIES:
:ID:       ASWwjxD2LRp1bgmiIJBxRC0w@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Owlz vs. Brewers Owlz vs. Brewers

Follow on MiLB First Pitch  https //stza.co/+xPCt-18

Shop  https //stza.co/+xPCt-1Q

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Owlz vs. Brewers
END:VALARM
DTSTART:20180814T010500Z
DTEND:20180814T040500Z
UID:ASWwjxD2LRp1bgmiIJBxRC0w@stanza.co
SUMMARY:Owlz vs. Brewers
DESCRIPTION:Owlz vs. Brewers\n\nFollow on MiLB First Pitch: https://stza.co/+xPCt-18\n\nShop: https://stza.co/+xPCt-1Q\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144549Z
LAST-MODIFIED:20180213T144549Z
TRANSP:OPAQUE
END:VEVENT
* Owlz vs. Brewers
<2018-08-14 Tue 20:05-23:05>
:PROPERTIES:
:ID:       Shxo7bg51cLYuVMXaBNmrcCJ@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Owlz vs. Brewers Owlz vs. Brewers

Follow on MiLB First Pitch  https //stza.co/+xPCv-2e

Shop  https //stza.co/+xPCv-i

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Owlz vs. Brewers
END:VALARM
DTSTART:20180815T010500Z
DTEND:20180815T040500Z
UID:Shxo7bg51cLYuVMXaBNmrcCJ@stanza.co
SUMMARY:Owlz vs. Brewers
DESCRIPTION:Owlz vs. Brewers\n\nFollow on MiLB First Pitch: https://stza.co/+xPCv-2e\n\nShop: https://stza.co/+xPCv-i\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144549Z
LAST-MODIFIED:20180213T144549Z
TRANSP:OPAQUE
END:VEVENT
* Owlz vs. Brewers
<2018-08-15 Wed 20:05-23:05>
:PROPERTIES:
:ID:       KVBeuaaBPwJkiuNJ_UFNya3m@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Owlz vs. Brewers Owlz vs. Brewers

Follow on MiLB First Pitch  https //stza.co/+xPCw-H

Shop  https //stza.co/+xPCw-x

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Owlz vs. Brewers
END:VALARM
DTSTART:20180816T010500Z
DTEND:20180816T040500Z
UID:KVBeuaaBPwJkiuNJ_UFNya3m@stanza.co
SUMMARY:Owlz vs. Brewers
DESCRIPTION:Owlz vs. Brewers\n\nFollow on MiLB First Pitch: https://stza.co/+xPCw-H\n\nShop: https://stza.co/+xPCw-x\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144549Z
LAST-MODIFIED:20180213T144549Z
TRANSP:OPAQUE
END:VEVENT
* Owlz @ Osprey
<2018-08-17 Fri>--<2018-08-16 Thu>
:PROPERTIES:
:ID:       91ed4aDMwLa8Clp8GUNL-3uz@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Owlz @ Osprey Owlz @ Osprey

Follow on MiLB First Pitch  https //stza.co/+xCDe-d

Shop  https //stza.co/+xCDe-2I

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Owlz @ Osprey
END:VALARM
DTSTART;VALUE=DATE:20180817
DTEND;VALUE=DATE:20180817
UID:91ed4aDMwLa8Clp8GUNL-3uz@stanza.co
SUMMARY:Owlz @ Osprey
DESCRIPTION:Owlz @ Osprey\n\nFollow on MiLB First Pitch: https://stza.co/+xCDe-d\n\nShop: https://stza.co/+xCDe-2I\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144549Z
LAST-MODIFIED:20180213T144549Z
TRANSP:OPAQUE
END:VEVENT
* Owlz @ Osprey
<2018-08-18 Sat>--<2018-08-17 Fri>
:PROPERTIES:
:ID:       t3UGyvmD3al2X4q11JqTLbjp@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Owlz @ Osprey Owlz @ Osprey

Follow on MiLB First Pitch  https //stza.co/+xCDf-j

Shop  https //stza.co/+xCDf-z

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Owlz @ Osprey
END:VALARM
DTSTART;VALUE=DATE:20180818
DTEND;VALUE=DATE:20180818
UID:t3UGyvmD3al2X4q11JqTLbjp@stanza.co
SUMMARY:Owlz @ Osprey
DESCRIPTION:Owlz @ Osprey\n\nFollow on MiLB First Pitch: https://stza.co/+xCDf-j\n\nShop: https://stza.co/+xCDf-z\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144549Z
LAST-MODIFIED:20180213T144549Z
TRANSP:OPAQUE
END:VEVENT
* Owlz @ Osprey
<2018-08-19 Sun>--<2018-08-18 Sat>
:PROPERTIES:
:ID:       tnBuGQIOLapNaWHJ1mZ8r1ah@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Owlz @ Osprey Owlz @ Osprey

Follow on MiLB First Pitch  https //stza.co/+xCDg-1W

Shop  https //stza.co/+xCDg-38

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Owlz @ Osprey
END:VALARM
DTSTART;VALUE=DATE:20180819
DTEND;VALUE=DATE:20180819
UID:tnBuGQIOLapNaWHJ1mZ8r1ah@stanza.co
SUMMARY:Owlz @ Osprey
DESCRIPTION:Owlz @ Osprey\n\nFollow on MiLB First Pitch: https://stza.co/+xCDg-1W\n\nShop: https://stza.co/+xCDg-38\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144549Z
LAST-MODIFIED:20180213T144549Z
TRANSP:OPAQUE
END:VEVENT
* Owlz @ Brewers
<2018-08-20 Mon>--<2018-08-19 Sun>
:PROPERTIES:
:ID:       TvCoeoWxXrFMDeOSxdWV8Qxr@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Owlz @ Brewers Owlz @ Brewers

Follow on MiLB First Pitch  https //stza.co/+xCC$-z

Shop  https //stza.co/+xCC$-2e

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Owlz @ Brewers
END:VALARM
DTSTART;VALUE=DATE:20180820
DTEND;VALUE=DATE:20180820
UID:TvCoeoWxXrFMDeOSxdWV8Qxr@stanza.co
SUMMARY:Owlz @ Brewers
DESCRIPTION:Owlz @ Brewers\n\nFollow on MiLB First Pitch: https://stza.co/+xCC$-z\n\nShop: https://stza.co/+xCC$-2e\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144549Z
LAST-MODIFIED:20180213T144549Z
TRANSP:OPAQUE
END:VEVENT
* Owlz @ Brewers
<2018-08-21 Tue>--<2018-08-20 Mon>
:PROPERTIES:
:ID:       4p1-xdwes-cgtJtoK0a9x7HB@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Owlz @ Brewers Owlz @ Brewers

Follow on MiLB First Pitch  https //stza.co/+xCD0-l

Shop  https //stza.co/+xCD0-2t

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Owlz @ Brewers
END:VALARM
DTSTART;VALUE=DATE:20180821
DTEND;VALUE=DATE:20180821
UID:4p1-xdwes-cgtJtoK0a9x7HB@stanza.co
SUMMARY:Owlz @ Brewers
DESCRIPTION:Owlz @ Brewers\n\nFollow on MiLB First Pitch: https://stza.co/+xCD0-l\n\nShop: https://stza.co/+xCD0-2t\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144549Z
LAST-MODIFIED:20180213T144549Z
TRANSP:OPAQUE
END:VEVENT
* Owlz @ Brewers
<2018-08-22 Wed>--<2018-08-21 Tue>
:PROPERTIES:
:ID:       1wW-XJZ2CXh4sN4b0If0ZxU9@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Owlz @ Brewers Owlz @ Brewers

Follow on MiLB First Pitch  https //stza.co/+xCD1-2E

Shop  https //stza.co/+xCD1-3w

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Owlz @ Brewers
END:VALARM
DTSTART;VALUE=DATE:20180822
DTEND;VALUE=DATE:20180822
UID:1wW-XJZ2CXh4sN4b0If0ZxU9@stanza.co
SUMMARY:Owlz @ Brewers
DESCRIPTION:Owlz @ Brewers\n\nFollow on MiLB First Pitch: https://stza.co/+xCD1-2E\n\nShop: https://stza.co/+xCD1-3w\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144549Z
LAST-MODIFIED:20180213T144549Z
TRANSP:OPAQUE
END:VEVENT
* Owlz @ Brewers
<2018-08-23 Thu>--<2018-08-22 Wed>
:PROPERTIES:
:ID:       IN_3PCBKVzvhtN3814arR0GH@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Owlz @ Brewers Owlz @ Brewers

Follow on MiLB First Pitch  https //stza.co/+xCD2-1z

Shop  https //stza.co/+xCD2-2v

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Owlz @ Brewers
END:VALARM
DTSTART;VALUE=DATE:20180823
DTEND;VALUE=DATE:20180823
UID:IN_3PCBKVzvhtN3814arR0GH@stanza.co
SUMMARY:Owlz @ Brewers
DESCRIPTION:Owlz @ Brewers\n\nFollow on MiLB First Pitch: https://stza.co/+xCD2-1z\n\nShop: https://stza.co/+xCD2-2v\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144549Z
LAST-MODIFIED:20180213T144549Z
TRANSP:OPAQUE
END:VEVENT
* Owlz vs. Raptors
<2018-08-24 Fri 19:35-22:35>
:PROPERTIES:
:ID:       S55DIMJyvG_xK0j_mcVO8vWh@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Owlz vs. Raptors Owlz vs. Raptors

Follow on MiLB First Pitch  https //stza.co/+xPCz-3c

Shop  https //stza.co/+xPCz-2p

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Owlz vs. Raptors
END:VALARM
DTSTART:20180825T003500Z
DTEND:20180825T033500Z
UID:S55DIMJyvG_xK0j_mcVO8vWh@stanza.co
SUMMARY:Owlz vs. Raptors
DESCRIPTION:Owlz vs. Raptors\n\nFollow on MiLB First Pitch: https://stza.co/+xPCz-3c\n\nShop: https://stza.co/+xPCz-2p\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144549Z
LAST-MODIFIED:20180213T144549Z
TRANSP:OPAQUE
END:VEVENT
* Owlz vs. Raptors
<2018-08-25 Sat 19:35-22:35>
:PROPERTIES:
:ID:       VRJZbkGxbn0Ez2iYe2ytPwiz@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Owlz vs. Raptors Owlz vs. Raptors

Follow on MiLB First Pitch  https //stza.co/+xPCB-1c

Shop  https //stza.co/+xPCB-1K

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Owlz vs. Raptors
END:VALARM
DTSTART:20180826T003500Z
DTEND:20180826T033500Z
UID:VRJZbkGxbn0Ez2iYe2ytPwiz@stanza.co
SUMMARY:Owlz vs. Raptors
DESCRIPTION:Owlz vs. Raptors\n\nFollow on MiLB First Pitch: https://stza.co/+xPCB-1c\n\nShop: https://stza.co/+xPCB-1K\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144549Z
LAST-MODIFIED:20180213T144549Z
TRANSP:OPAQUE
END:VEVENT
* Owlz vs. Raptors
<2018-08-27 Mon 19:35-22:35>
:PROPERTIES:
:ID:       yyEPd-LBPZxHS-tKrxCFeMPl@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Owlz vs. Raptors Owlz vs. Raptors

Follow on MiLB First Pitch  https //stza.co/+xPCC-13

Shop  https //stza.co/+xPCC-c

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Owlz vs. Raptors
END:VALARM
DTSTART:20180828T003500Z
DTEND:20180828T033500Z
UID:yyEPd-LBPZxHS-tKrxCFeMPl@stanza.co
SUMMARY:Owlz vs. Raptors
DESCRIPTION:Owlz vs. Raptors\n\nFollow on MiLB First Pitch: https://stza.co/+xPCC-13\n\nShop: https://stza.co/+xPCC-c\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144549Z
LAST-MODIFIED:20180213T144549Z
TRANSP:OPAQUE
END:VEVENT
* Owlz vs. Raptors
<2018-08-28 Tue 19:35-22:35>
:PROPERTIES:
:ID:       pz6vAnffMW98n8rETmnu-Mn_@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Owlz vs. Raptors Owlz vs. Raptors

Follow on MiLB First Pitch  https //stza.co/+xPCF-3J

Shop  https //stza.co/+xPCF-2i

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Owlz vs. Raptors
END:VALARM
DTSTART:20180829T003500Z
DTEND:20180829T033500Z
UID:pz6vAnffMW98n8rETmnu-Mn_@stanza.co
SUMMARY:Owlz vs. Raptors
DESCRIPTION:Owlz vs. Raptors\n\nFollow on MiLB First Pitch: https://stza.co/+xPCF-3J\n\nShop: https://stza.co/+xPCF-2i\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144549Z
LAST-MODIFIED:20180213T144549Z
TRANSP:OPAQUE
END:VEVENT
* Owlz vs. Rockies
<2018-08-29 Wed 19:35-22:35>
:PROPERTIES:
:ID:       hTv2W7BmFIGozfxQvhhf2fJ9@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Owlz vs. Rockies Owlz vs. Rockies

Follow on MiLB First Pitch  https //stza.co/+xPCH-1_

Shop  https //stza.co/+xPCH-V

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Owlz vs. Rockies
END:VALARM
DTSTART:20180830T003500Z
DTEND:20180830T033500Z
UID:hTv2W7BmFIGozfxQvhhf2fJ9@stanza.co
SUMMARY:Owlz vs. Rockies
DESCRIPTION:Owlz vs. Rockies\n\nFollow on MiLB First Pitch: https://stza.co/+xPCH-1_\n\nShop: https://stza.co/+xPCH-V\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144549Z
LAST-MODIFIED:20180213T144549Z
TRANSP:OPAQUE
END:VEVENT
* Owlz vs. Rockies
<2018-08-30 Thu 19:35-22:35>
:PROPERTIES:
:ID:       GRAWuPQSDz--9p1QV2nSyLow@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Owlz vs. Rockies Owlz vs. Rockies

Follow on MiLB First Pitch  https //stza.co/+xPCJ-2T

Shop  https //stza.co/+xPCJ-36

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Owlz vs. Rockies
END:VALARM
DTSTART:20180831T003500Z
DTEND:20180831T033500Z
UID:GRAWuPQSDz--9p1QV2nSyLow@stanza.co
SUMMARY:Owlz vs. Rockies
DESCRIPTION:Owlz vs. Rockies\n\nFollow on MiLB First Pitch: https://stza.co/+xPCJ-2T\n\nShop: https://stza.co/+xPCJ-36\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144549Z
LAST-MODIFIED:20180213T144549Z
TRANSP:OPAQUE
END:VEVENT
* Owlz @ Chukars
<2018-08-31 Fri 20:15-23:15>
:PROPERTIES:
:ID:       VIPOr-3aDWzfnyBGbVBRqSI9@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Owlz @ Chukars Owlz @ Chukars

Follow on MiLB First Pitch  https //stza.co/+xZWg-27

Shop  https //stza.co/+xZWg-3F

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Owlz @ Chukars
END:VALARM
DTSTART:20180901T011500Z
DTEND:20180901T041500Z
UID:VIPOr-3aDWzfnyBGbVBRqSI9@stanza.co
SUMMARY:Owlz @ Chukars
DESCRIPTION:Owlz @ Chukars\n\nFollow on MiLB First Pitch: https://stza.co/+xZWg-27\n\nShop: https://stza.co/+xZWg-3F\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144549Z
LAST-MODIFIED:20180213T144549Z
TRANSP:OPAQUE
END:VEVENT
* Owlz @ Chukars
<2018-09-01 Sat 20:15-23:15>
:PROPERTIES:
:ID:       Q3r8plqpskLj4-HCLfNzEvDT@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Owlz @ Chukars Owlz @ Chukars

Follow on MiLB First Pitch  https //stza.co/+xZWh-2l

Shop  https //stza.co/+xZWh-2g

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Owlz @ Chukars
END:VALARM
DTSTART:20180902T011500Z
DTEND:20180902T041500Z
UID:Q3r8plqpskLj4-HCLfNzEvDT@stanza.co
SUMMARY:Owlz @ Chukars
DESCRIPTION:Owlz @ Chukars\n\nFollow on MiLB First Pitch: https://stza.co/+xZWh-2l\n\nShop: https://stza.co/+xZWh-2g\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144549Z
LAST-MODIFIED:20180213T144549Z
TRANSP:OPAQUE
END:VEVENT
* Owlz @ Rockies
<2018-09-03 Mon 19:40-22:40>
:PROPERTIES:
:ID:       LE5N4pCsamv2LU5TNhxSLR4N@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Owlz @ Rockies Owlz @ Rockies

Follow on MiLB First Pitch  https //stza.co/+xJ8E-3I

Shop  https //stza.co/+xJ8E-E

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Owlz @ Rockies
END:VALARM
DTSTART:20180904T004000Z
DTEND:20180904T034000Z
UID:LE5N4pCsamv2LU5TNhxSLR4N@stanza.co
SUMMARY:Owlz @ Rockies
DESCRIPTION:Owlz @ Rockies\n\nFollow on MiLB First Pitch: https://stza.co/+xJ8E-3I\n\nShop: https://stza.co/+xJ8E-E\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144549Z
LAST-MODIFIED:20180213T144549Z
TRANSP:OPAQUE
END:VEVENT
* Owlz @ Rockies
<2018-09-04 Tue 19:40-22:40>
:PROPERTIES:
:ID:       CLOiDA97sQuHXjR0vvFHHuPd@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Owlz @ Rockies Owlz @ Rockies

Follow on MiLB First Pitch  https //stza.co/+xJ8F-3v

Shop  https //stza.co/+xJ8F-1l

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Owlz @ Rockies
END:VALARM
DTSTART:20180905T004000Z
DTEND:20180905T034000Z
UID:CLOiDA97sQuHXjR0vvFHHuPd@stanza.co
SUMMARY:Owlz @ Rockies
DESCRIPTION:Owlz @ Rockies\n\nFollow on MiLB First Pitch: https://stza.co/+xJ8F-3v\n\nShop: https://stza.co/+xJ8F-1l\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144549Z
LAST-MODIFIED:20180213T144549Z
TRANSP:OPAQUE
END:VEVENT
* Owlz vs. Rockies
<2018-09-05 Wed 19:35-22:35>
:PROPERTIES:
:ID:       0muiOy6oCAyGL6ZR00ee9hoz@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Owlz vs. Rockies Owlz vs. Rockies

Follow on MiLB First Pitch  https //stza.co/+xPCK-21

Shop  https //stza.co/+xPCK-2J

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Owlz vs. Rockies
END:VALARM
DTSTART:20180906T003500Z
DTEND:20180906T033500Z
UID:0muiOy6oCAyGL6ZR00ee9hoz@stanza.co
SUMMARY:Owlz vs. Rockies
DESCRIPTION:Owlz vs. Rockies\n\nFollow on MiLB First Pitch: https://stza.co/+xPCK-21\n\nShop: https://stza.co/+xPCK-2J\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144549Z
LAST-MODIFIED:20180213T144549Z
TRANSP:OPAQUE
END:VEVENT
* Owlz vs. Rockies
<2018-09-06 Thu 19:35-22:35>
:PROPERTIES:
:ID:       kwhZbjD0v9jeEHIlXv8fEJ7E@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Owlz vs. Rockies Owlz vs. Rockies

Follow on MiLB First Pitch  https //stza.co/+xPCN-m

Shop  https //stza.co/+xPCN-2k

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Owlz vs. Rockies
END:VALARM
DTSTART:20180907T003500Z
DTEND:20180907T033500Z
UID:kwhZbjD0v9jeEHIlXv8fEJ7E@stanza.co
SUMMARY:Owlz vs. Rockies
DESCRIPTION:Owlz vs. Rockies\n\nFollow on MiLB First Pitch: https://stza.co/+xPCN-m\n\nShop: https://stza.co/+xPCN-2k\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144549Z
LAST-MODIFIED:20180213T144549Z
TRANSP:OPAQUE
END:VEVENT
