#+TITLE:       Main Google calendar entries
#+AUTHOR:      Eric S Fraga
#+EMAIL:       e.fraga@ucl.ac.uk
#+DESCRIPTION: converted using the ical2org awk script
#+CATEGORY:    google
#+STARTUP:     hidestars
#+STARTUP:     overview

* COMMENT original iCal preamble

* Shuckers @ Biscuits
<2018-04-05 Thu 18:35-21:35>
:PROPERTIES:
:ID:       Ud6hS8vJdWluaZbvvT_6o83Y@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Shuckers @ Biscuits Shuckers @ Biscuits

Follow on MiLB First Pitch  https //stza.co/+vcl8-1S

Shop  https //stza.co/+vcl8-3A

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Shuckers @ Biscuits
END:VALARM
DTSTART:20180405T233500Z
DTEND:20180406T023500Z
UID:Ud6hS8vJdWluaZbvvT_6o83Y@stanza.co
SUMMARY:Shuckers @ Biscuits
DESCRIPTION:Shuckers @ Biscuits\n\nFollow on MiLB First Pitch: https://stza.co/+vcl8-1S\n\nShop: https://stza.co/+vcl8-3A\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144505Z
LAST-MODIFIED:20180213T144505Z
TRANSP:OPAQUE
END:VEVENT
* Shuckers @ Biscuits
<2018-04-06 Fri 18:35-21:35>
:PROPERTIES:
:ID:       AAOQQLJA41k2ZJsF6i7m6NwO@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Shuckers @ Biscuits Shuckers @ Biscuits

Follow on MiLB First Pitch  https //stza.co/+vclj-2c

Shop  https //stza.co/+vclj-34

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Shuckers @ Biscuits
END:VALARM
DTSTART:20180406T233500Z
DTEND:20180407T023500Z
UID:AAOQQLJA41k2ZJsF6i7m6NwO@stanza.co
SUMMARY:Shuckers @ Biscuits
DESCRIPTION:Shuckers @ Biscuits\n\nFollow on MiLB First Pitch: https://stza.co/+vclj-2c\n\nShop: https://stza.co/+vclj-34\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144505Z
LAST-MODIFIED:20180213T144505Z
TRANSP:OPAQUE
END:VEVENT
* Shuckers @ Biscuits
<2018-04-07 Sat 18:05-21:05>
:PROPERTIES:
:ID:       5fBUpEgsR2gpmSe8tTqn8el9@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Shuckers @ Biscuits Shuckers @ Biscuits

Follow on MiLB First Pitch  https //stza.co/+vclw-3O

Shop  https //stza.co/+vclw-x

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Shuckers @ Biscuits
END:VALARM
DTSTART:20180407T230500Z
DTEND:20180408T020500Z
UID:5fBUpEgsR2gpmSe8tTqn8el9@stanza.co
SUMMARY:Shuckers @ Biscuits
DESCRIPTION:Shuckers @ Biscuits\n\nFollow on MiLB First Pitch: https://stza.co/+vclw-3O\n\nShop: https://stza.co/+vclw-x\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144505Z
LAST-MODIFIED:20180213T144505Z
TRANSP:OPAQUE
END:VEVENT
* Shuckers @ Biscuits
<2018-04-08 Sun 14:05-17:05>
:PROPERTIES:
:ID:       mDrkh_vFSGjyZS57DgeItnl-@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Shuckers @ Biscuits Shuckers @ Biscuits

Follow on MiLB First Pitch  https //stza.co/+vclF-1z

Shop  https //stza.co/+vclF-3J

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Shuckers @ Biscuits
END:VALARM
DTSTART:20180408T190500Z
DTEND:20180408T220500Z
UID:mDrkh_vFSGjyZS57DgeItnl-@stanza.co
SUMMARY:Shuckers @ Biscuits
DESCRIPTION:Shuckers @ Biscuits\n\nFollow on MiLB First Pitch: https://stza.co/+vclF-1z\n\nShop: https://stza.co/+vclF-3J\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144505Z
LAST-MODIFIED:20180213T144505Z
TRANSP:OPAQUE
END:VEVENT
* Shuckers @ Biscuits
<2018-04-09 Mon 18:35-21:35>
:PROPERTIES:
:ID:       XmfQK8YQK5cSEvoFyNq9fXGM@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Shuckers @ Biscuits Shuckers @ Biscuits

Follow on MiLB First Pitch  https //stza.co/+vclN-2m

Shop  https //stza.co/+vclN-e

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Shuckers @ Biscuits
END:VALARM
DTSTART:20180409T233500Z
DTEND:20180410T023500Z
UID:XmfQK8YQK5cSEvoFyNq9fXGM@stanza.co
SUMMARY:Shuckers @ Biscuits
DESCRIPTION:Shuckers @ Biscuits\n\nFollow on MiLB First Pitch: https://stza.co/+vclN-2m\n\nShop: https://stza.co/+vclN-e\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144505Z
LAST-MODIFIED:20180213T144505Z
TRANSP:OPAQUE
END:VEVENT
* Shuckers vs. Braves
<2018-04-11 Wed 18:35-21:35>
:PROPERTIES:
:ID:       _W_A7cUB-QTIl4Hyp5BGLRp-@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Shuckers vs. Braves Shuckers vs. Braves

Follow on MiLB First Pitch  https //stza.co/+vLwB-i

Shop  https //stza.co/+vLwB-3p

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Shuckers vs. Braves
END:VALARM
DTSTART:20180411T233500Z
DTEND:20180412T023500Z
UID:_W_A7cUB-QTIl4Hyp5BGLRp-@stanza.co
SUMMARY:Shuckers vs. Braves
DESCRIPTION:Shuckers vs. Braves\n\nFollow on MiLB First Pitch: https://stza.co/+vLwB-i\n\nShop: https://stza.co/+vLwB-3p\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144505Z
LAST-MODIFIED:20180213T144505Z
TRANSP:OPAQUE
END:VEVENT
* Shuckers vs. Braves
<2018-04-12 Thu 18:35-21:35>
:PROPERTIES:
:ID:       -JvOXZ4CzcX1Ch6KSWDmNWd4@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Shuckers vs. Braves Shuckers vs. Braves

Follow on MiLB First Pitch  https //stza.co/+vLwE-3H

Shop  https //stza.co/+vLwE-2K

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Shuckers vs. Braves
END:VALARM
DTSTART:20180412T233500Z
DTEND:20180413T023500Z
UID:-JvOXZ4CzcX1Ch6KSWDmNWd4@stanza.co
SUMMARY:Shuckers vs. Braves
DESCRIPTION:Shuckers vs. Braves\n\nFollow on MiLB First Pitch: https://stza.co/+vLwE-3H\n\nShop: https://stza.co/+vLwE-2K\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144505Z
LAST-MODIFIED:20180213T144505Z
TRANSP:OPAQUE
END:VEVENT
* Shuckers vs. Braves
<2018-04-13 Fri 18:35-21:35>
:PROPERTIES:
:ID:       3ws5UXmS0GhzCYGh2LX0LvM2@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Shuckers vs. Braves Shuckers vs. Braves

Follow on MiLB First Pitch  https //stza.co/+vLwG-1h

Shop  https //stza.co/+vLwG-1S

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Shuckers vs. Braves
END:VALARM
DTSTART:20180413T233500Z
DTEND:20180414T023500Z
UID:3ws5UXmS0GhzCYGh2LX0LvM2@stanza.co
SUMMARY:Shuckers vs. Braves
DESCRIPTION:Shuckers vs. Braves\n\nFollow on MiLB First Pitch: https://stza.co/+vLwG-1h\n\nShop: https://stza.co/+vLwG-1S\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144505Z
LAST-MODIFIED:20180213T144505Z
TRANSP:OPAQUE
END:VEVENT
* Shuckers vs. Braves
<2018-04-14 Sat 18:35-21:35>
:PROPERTIES:
:ID:       wOEGeau_GaS7G1ugRfyrp8bs@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Shuckers vs. Braves Shuckers vs. Braves

Follow on MiLB First Pitch  https //stza.co/+vLwH-2W

Shop  https //stza.co/+vLwH-1D

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Shuckers vs. Braves
END:VALARM
DTSTART:20180414T233500Z
DTEND:20180415T023500Z
UID:wOEGeau_GaS7G1ugRfyrp8bs@stanza.co
SUMMARY:Shuckers vs. Braves
DESCRIPTION:Shuckers vs. Braves\n\nFollow on MiLB First Pitch: https://stza.co/+vLwH-2W\n\nShop: https://stza.co/+vLwH-1D\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144505Z
LAST-MODIFIED:20180213T144505Z
TRANSP:OPAQUE
END:VEVENT
* Shuckers vs. Braves
<2018-04-15 Sun 14:05-17:05>
:PROPERTIES:
:ID:       ChvZkQUOiShYV847oiPCWUpf@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Shuckers vs. Braves Shuckers vs. Braves

Follow on MiLB First Pitch  https //stza.co/+vLwJ-23

Shop  https //stza.co/+vLwJ-M

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Shuckers vs. Braves
END:VALARM
DTSTART:20180415T190500Z
DTEND:20180415T220500Z
UID:ChvZkQUOiShYV847oiPCWUpf@stanza.co
SUMMARY:Shuckers vs. Braves
DESCRIPTION:Shuckers vs. Braves\n\nFollow on MiLB First Pitch: https://stza.co/+vLwJ-23\n\nShop: https://stza.co/+vLwJ-M\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144505Z
LAST-MODIFIED:20180213T144505Z
TRANSP:OPAQUE
END:VEVENT
* Shuckers @ BayBears
<2018-04-16 Mon 18:35-21:35>
:PROPERTIES:
:ID:       PPeoMYqgKb9GLjGrtdnolYHV@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Shuckers @ BayBears Shuckers @ BayBears

Follow on MiLB First Pitch  https //stza.co/+v$Pk-3n

Shop  https //stza.co/+v$Pk-32

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Shuckers @ BayBears
END:VALARM
DTSTART:20180416T233500Z
DTEND:20180417T023500Z
UID:PPeoMYqgKb9GLjGrtdnolYHV@stanza.co
SUMMARY:Shuckers @ BayBears
DESCRIPTION:Shuckers @ BayBears\n\nFollow on MiLB First Pitch: https://stza.co/+v$Pk-3n\n\nShop: https://stza.co/+v$Pk-32\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144505Z
LAST-MODIFIED:20180213T144505Z
TRANSP:OPAQUE
END:VEVENT
* Shuckers @ BayBears
<2018-04-17 Tue 18:35-21:35>
:PROPERTIES:
:ID:       B-038La_beEMaSwcmme6e2y9@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Shuckers @ BayBears Shuckers @ BayBears

Follow on MiLB First Pitch  https //stza.co/+v$Pl-30

Shop  https //stza.co/+v$Pl-3E

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Shuckers @ BayBears
END:VALARM
DTSTART:20180417T233500Z
DTEND:20180418T023500Z
UID:B-038La_beEMaSwcmme6e2y9@stanza.co
SUMMARY:Shuckers @ BayBears
DESCRIPTION:Shuckers @ BayBears\n\nFollow on MiLB First Pitch: https://stza.co/+v$Pl-30\n\nShop: https://stza.co/+v$Pl-3E\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144505Z
LAST-MODIFIED:20180213T144505Z
TRANSP:OPAQUE
END:VEVENT
* Shuckers @ BayBears
<2018-04-18 Wed 18:35-21:35>
:PROPERTIES:
:ID:       hHPmFwthe-rvXVPLXz7u4Shn@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Shuckers @ BayBears Shuckers @ BayBears

Follow on MiLB First Pitch  https //stza.co/+v$Pm-1H

Shop  https //stza.co/+v$Pm-8

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Shuckers @ BayBears
END:VALARM
DTSTART:20180418T233500Z
DTEND:20180419T023500Z
UID:hHPmFwthe-rvXVPLXz7u4Shn@stanza.co
SUMMARY:Shuckers @ BayBears
DESCRIPTION:Shuckers @ BayBears\n\nFollow on MiLB First Pitch: https://stza.co/+v$Pm-1H\n\nShop: https://stza.co/+v$Pm-8\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144505Z
LAST-MODIFIED:20180213T144505Z
TRANSP:OPAQUE
END:VEVENT
* Shuckers @ BayBears
<2018-04-19 Thu 18:35-21:35>
:PROPERTIES:
:ID:       _aHRDbsrj28-jLmMIbfdfVII@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Shuckers @ BayBears Shuckers @ BayBears

Follow on MiLB First Pitch  https //stza.co/+v$Pn-W

Shop  https //stza.co/+v$Pn-3H

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Shuckers @ BayBears
END:VALARM
DTSTART:20180419T233500Z
DTEND:20180420T023500Z
UID:_aHRDbsrj28-jLmMIbfdfVII@stanza.co
SUMMARY:Shuckers @ BayBears
DESCRIPTION:Shuckers @ BayBears\n\nFollow on MiLB First Pitch: https://stza.co/+v$Pn-W\n\nShop: https://stza.co/+v$Pn-3H\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144505Z
LAST-MODIFIED:20180213T144505Z
TRANSP:OPAQUE
END:VEVENT
* Shuckers @ BayBears
<2018-04-20 Fri 19:05-22:05>
:PROPERTIES:
:ID:       rfeIfKBhPekZeu3214UShAIt@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Shuckers @ BayBears Shuckers @ BayBears

Follow on MiLB First Pitch  https //stza.co/+v$Po-1e

Shop  https //stza.co/+v$Po-J

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Shuckers @ BayBears
END:VALARM
DTSTART:20180421T000500Z
DTEND:20180421T030500Z
UID:rfeIfKBhPekZeu3214UShAIt@stanza.co
SUMMARY:Shuckers @ BayBears
DESCRIPTION:Shuckers @ BayBears\n\nFollow on MiLB First Pitch: https://stza.co/+v$Po-1e\n\nShop: https://stza.co/+v$Po-J\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144505Z
LAST-MODIFIED:20180213T144505Z
TRANSP:OPAQUE
END:VEVENT
* Shuckers vs. Biscuits
<2018-04-21 Sat 18:35-21:35>
:PROPERTIES:
:ID:       rruEjceInK0FqZhfxDPF-dAR@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Shuckers vs. Biscuits Shuckers vs. Biscuits

Follow on MiLB First Pitch  https //stza.co/+vLwL-32

Shop  https //stza.co/+vLwL-l

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Shuckers vs. Biscuits
END:VALARM
DTSTART:20180421T233500Z
DTEND:20180422T023500Z
UID:rruEjceInK0FqZhfxDPF-dAR@stanza.co
SUMMARY:Shuckers vs. Biscuits
DESCRIPTION:Shuckers vs. Biscuits\n\nFollow on MiLB First Pitch: https://stza.co/+vLwL-32\n\nShop: https://stza.co/+vLwL-l\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144505Z
LAST-MODIFIED:20180213T144505Z
TRANSP:OPAQUE
END:VEVENT
* Shuckers vs. Biscuits
<2018-04-22 Sun 14:05-17:05>
:PROPERTIES:
:ID:       UomcvUrdJXS2wByRNlvm1iq-@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Shuckers vs. Biscuits Shuckers vs. Biscuits

Follow on MiLB First Pitch  https //stza.co/+vLwN-2x

Shop  https //stza.co/+vLwN-6

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Shuckers vs. Biscuits
END:VALARM
DTSTART:20180422T190500Z
DTEND:20180422T220500Z
UID:UomcvUrdJXS2wByRNlvm1iq-@stanza.co
SUMMARY:Shuckers vs. Biscuits
DESCRIPTION:Shuckers vs. Biscuits\n\nFollow on MiLB First Pitch: https://stza.co/+vLwN-2x\n\nShop: https://stza.co/+vLwN-6\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144505Z
LAST-MODIFIED:20180213T144505Z
TRANSP:OPAQUE
END:VEVENT
* Shuckers vs. Biscuits
<2018-04-23 Mon 18:35-21:35>
:PROPERTIES:
:ID:       cy024xGvmiczlZ606MvQj1wS@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Shuckers vs. Biscuits Shuckers vs. Biscuits

Follow on MiLB First Pitch  https //stza.co/+vLwQ-2C

Shop  https //stza.co/+vLwQ-3v

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Shuckers vs. Biscuits
END:VALARM
DTSTART:20180423T233500Z
DTEND:20180424T023500Z
UID:cy024xGvmiczlZ606MvQj1wS@stanza.co
SUMMARY:Shuckers vs. Biscuits
DESCRIPTION:Shuckers vs. Biscuits\n\nFollow on MiLB First Pitch: https://stza.co/+vLwQ-2C\n\nShop: https://stza.co/+vLwQ-3v\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144505Z
LAST-MODIFIED:20180213T144505Z
TRANSP:OPAQUE
END:VEVENT
* Shuckers vs. Biscuits
<2018-04-24 Tue 18:35-21:35>
:PROPERTIES:
:ID:       3txuyiqbEgdCw3srIhfuWWYZ@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Shuckers vs. Biscuits Shuckers vs. Biscuits

Follow on MiLB First Pitch  https //stza.co/+vLwR-3R

Shop  https //stza.co/+vLwR-2o

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Shuckers vs. Biscuits
END:VALARM
DTSTART:20180424T233500Z
DTEND:20180425T023500Z
UID:3txuyiqbEgdCw3srIhfuWWYZ@stanza.co
SUMMARY:Shuckers vs. Biscuits
DESCRIPTION:Shuckers vs. Biscuits\n\nFollow on MiLB First Pitch: https://stza.co/+vLwR-3R\n\nShop: https://stza.co/+vLwR-2o\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144505Z
LAST-MODIFIED:20180213T144505Z
TRANSP:OPAQUE
END:VEVENT
* Shuckers vs. Biscuits
<2018-04-25 Wed 10:35-13:35>
:PROPERTIES:
:ID:       z_duk4KGtf5qdRuj43Qimj0w@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Shuckers vs. Biscuits Shuckers vs. Biscuits

Follow on MiLB First Pitch  https //stza.co/+vLwU-a

Shop  https //stza.co/+vLwU-2b

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Shuckers vs. Biscuits
END:VALARM
DTSTART:20180425T153500Z
DTEND:20180425T183500Z
UID:z_duk4KGtf5qdRuj43Qimj0w@stanza.co
SUMMARY:Shuckers vs. Biscuits
DESCRIPTION:Shuckers vs. Biscuits\n\nFollow on MiLB First Pitch: https://stza.co/+vLwU-a\n\nShop: https://stza.co/+vLwU-2b\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144505Z
LAST-MODIFIED:20180213T144505Z
TRANSP:OPAQUE
END:VEVENT
* Shuckers @ Barons
<2018-04-26 Thu 19:05-22:05>
:PROPERTIES:
:ID:       1jlWAZ6-3XRkFrsDwddmnmV9@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Shuckers @ Barons Shuckers @ Barons

Follow on MiLB First Pitch  https //stza.co/+wFUU-3s

Shop  https //stza.co/+wFUU-3q

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Shuckers @ Barons
END:VALARM
DTSTART:20180427T000500Z
DTEND:20180427T030500Z
UID:1jlWAZ6-3XRkFrsDwddmnmV9@stanza.co
SUMMARY:Shuckers @ Barons
DESCRIPTION:Shuckers @ Barons\n\nFollow on MiLB First Pitch: https://stza.co/+wFUU-3s\n\nShop: https://stza.co/+wFUU-3q\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144505Z
LAST-MODIFIED:20180213T144505Z
TRANSP:OPAQUE
END:VEVENT
* Shuckers @ Barons
<2018-04-27 Fri 19:05-22:05>
:PROPERTIES:
:ID:       kVSYEfFTuQ8v2JjQwlolXFpi@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Shuckers @ Barons Shuckers @ Barons

Follow on MiLB First Pitch  https //stza.co/+wFUV-3p

Shop  https //stza.co/+wFUV-Y

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Shuckers @ Barons
END:VALARM
DTSTART:20180428T000500Z
DTEND:20180428T030500Z
UID:kVSYEfFTuQ8v2JjQwlolXFpi@stanza.co
SUMMARY:Shuckers @ Barons
DESCRIPTION:Shuckers @ Barons\n\nFollow on MiLB First Pitch: https://stza.co/+wFUV-3p\n\nShop: https://stza.co/+wFUV-Y\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144505Z
LAST-MODIFIED:20180213T144505Z
TRANSP:OPAQUE
END:VEVENT
* Shuckers @ Barons
<2018-04-28 Sat 18:30-21:30>
:PROPERTIES:
:ID:       vrMvfVrIQj7cz4bon5k7YVdj@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Shuckers @ Barons Shuckers @ Barons

Follow on MiLB First Pitch  https //stza.co/+wFUW-b

Shop  https //stza.co/+wFUW-5

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Shuckers @ Barons
END:VALARM
DTSTART:20180428T233000Z
DTEND:20180429T023000Z
UID:vrMvfVrIQj7cz4bon5k7YVdj@stanza.co
SUMMARY:Shuckers @ Barons
DESCRIPTION:Shuckers @ Barons\n\nFollow on MiLB First Pitch: https://stza.co/+wFUW-b\n\nShop: https://stza.co/+wFUW-5\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144505Z
LAST-MODIFIED:20180213T144505Z
TRANSP:OPAQUE
END:VEVENT
* Shuckers @ Barons
<2018-04-29 Sun 15:00-18:00>
:PROPERTIES:
:ID:       CddGaSsw1all6lek-aE3yoo3@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Shuckers @ Barons Shuckers @ Barons

Follow on MiLB First Pitch  https //stza.co/+wFUX-3N

Shop  https //stza.co/+wFUX-1B

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Shuckers @ Barons
END:VALARM
DTSTART:20180429T200000Z
DTEND:20180429T230000Z
UID:CddGaSsw1all6lek-aE3yoo3@stanza.co
SUMMARY:Shuckers @ Barons
DESCRIPTION:Shuckers @ Barons\n\nFollow on MiLB First Pitch: https://stza.co/+wFUX-3N\n\nShop: https://stza.co/+wFUX-1B\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144505Z
LAST-MODIFIED:20180213T144505Z
TRANSP:OPAQUE
END:VEVENT
* Shuckers @ Barons
<2018-04-30 Mon 11:00-14:00>
:PROPERTIES:
:ID:       rmhhqoLZYyqiKvjc9BDJ0i-r@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Shuckers @ Barons Shuckers @ Barons

Follow on MiLB First Pitch  https //stza.co/+wFUY-R

Shop  https //stza.co/+wFUY-1R

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Shuckers @ Barons
END:VALARM
DTSTART:20180430T160000Z
DTEND:20180430T190000Z
UID:rmhhqoLZYyqiKvjc9BDJ0i-r@stanza.co
SUMMARY:Shuckers @ Barons
DESCRIPTION:Shuckers @ Barons\n\nFollow on MiLB First Pitch: https://stza.co/+wFUY-R\n\nShop: https://stza.co/+wFUY-1R\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144505Z
LAST-MODIFIED:20180213T144505Z
TRANSP:OPAQUE
END:VEVENT
* Shuckers vs. Jumbo Shrimp
<2018-05-02 Wed 18:35-21:35>
:PROPERTIES:
:ID:       0OQUKOjNoXkltN7uBlxh0jc8@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Shuckers vs. Jumbo Shrimp Shuckers vs. Jumbo Shrimp

Follow on MiLB First Pitch  https //stza.co/+vLwV-1O

Shop  https //stza.co/+vLwV-o

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Shuckers vs. Jumbo Shrimp
END:VALARM
DTSTART:20180502T233500Z
DTEND:20180503T023500Z
UID:0OQUKOjNoXkltN7uBlxh0jc8@stanza.co
SUMMARY:Shuckers vs. Jumbo Shrimp
DESCRIPTION:Shuckers vs. Jumbo Shrimp\n\nFollow on MiLB First Pitch: https://stza.co/+vLwV-1O\n\nShop: https://stza.co/+vLwV-o\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144505Z
LAST-MODIFIED:20180213T144505Z
TRANSP:OPAQUE
END:VEVENT
* Shuckers vs. Jumbo Shrimp
<2018-05-03 Thu 18:35-21:35>
:PROPERTIES:
:ID:       cm-a8gYH-zqq8GmxsySMb_iH@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Shuckers vs. Jumbo Shrimp Shuckers vs. Jumbo Shrimp

Follow on MiLB First Pitch  https //stza.co/+vLwY-1w

Shop  https //stza.co/+vLwY-21

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Shuckers vs. Jumbo Shrimp
END:VALARM
DTSTART:20180503T233500Z
DTEND:20180504T023500Z
UID:cm-a8gYH-zqq8GmxsySMb_iH@stanza.co
SUMMARY:Shuckers vs. Jumbo Shrimp
DESCRIPTION:Shuckers vs. Jumbo Shrimp\n\nFollow on MiLB First Pitch: https://stza.co/+vLwY-1w\n\nShop: https://stza.co/+vLwY-21\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144505Z
LAST-MODIFIED:20180213T144505Z
TRANSP:OPAQUE
END:VEVENT
* Shuckers vs. Jumbo Shrimp
<2018-05-04 Fri 18:35-21:35>
:PROPERTIES:
:ID:       nLzQXjnvvXrP3WbHa5FaZ3_V@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Shuckers vs. Jumbo Shrimp Shuckers vs. Jumbo Shrimp

Follow on MiLB First Pitch  https //stza.co/+vLw_-3c

Shop  https //stza.co/+vLw_-2H

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Shuckers vs. Jumbo Shrimp
END:VALARM
DTSTART:20180504T233500Z
DTEND:20180505T023500Z
UID:nLzQXjnvvXrP3WbHa5FaZ3_V@stanza.co
SUMMARY:Shuckers vs. Jumbo Shrimp
DESCRIPTION:Shuckers vs. Jumbo Shrimp\n\nFollow on MiLB First Pitch: https://stza.co/+vLw_-3c\n\nShop: https://stza.co/+vLw_-2H\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144505Z
LAST-MODIFIED:20180213T144505Z
TRANSP:OPAQUE
END:VEVENT
* Shuckers vs. Jumbo Shrimp
<2018-05-05 Sat 18:35-21:35>
:PROPERTIES:
:ID:       kAh0ifCiQgHEyhxhytF_VzUV@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Shuckers vs. Jumbo Shrimp Shuckers vs. Jumbo Shrimp

Follow on MiLB First Pitch  https //stza.co/+vLx0-q

Shop  https //stza.co/+vLx0-23

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Shuckers vs. Jumbo Shrimp
END:VALARM
DTSTART:20180505T233500Z
DTEND:20180506T023500Z
UID:kAh0ifCiQgHEyhxhytF_VzUV@stanza.co
SUMMARY:Shuckers vs. Jumbo Shrimp
DESCRIPTION:Shuckers vs. Jumbo Shrimp\n\nFollow on MiLB First Pitch: https://stza.co/+vLx0-q\n\nShop: https://stza.co/+vLx0-23\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144505Z
LAST-MODIFIED:20180213T144505Z
TRANSP:OPAQUE
END:VEVENT
* Shuckers vs. Jumbo Shrimp
<2018-05-06 Sun 14:05-17:05>
:PROPERTIES:
:ID:       hVBfjGHD_2pP7r4YAxl6_Qzg@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Shuckers vs. Jumbo Shrimp Shuckers vs. Jumbo Shrimp

Follow on MiLB First Pitch  https //stza.co/+vLx2-w

Shop  https //stza.co/+vLx2-2T

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Shuckers vs. Jumbo Shrimp
END:VALARM
DTSTART:20180506T190500Z
DTEND:20180506T220500Z
UID:hVBfjGHD_2pP7r4YAxl6_Qzg@stanza.co
SUMMARY:Shuckers vs. Jumbo Shrimp
DESCRIPTION:Shuckers vs. Jumbo Shrimp\n\nFollow on MiLB First Pitch: https://stza.co/+vLx2-w\n\nShop: https://stza.co/+vLx2-2T\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144505Z
LAST-MODIFIED:20180213T144505Z
TRANSP:OPAQUE
END:VEVENT
* Shuckers @ Biscuits
<2018-05-07 Mon 18:35-21:35>
:PROPERTIES:
:ID:       3U1ZjcTjTGqHAomWDkRFQzkM@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Shuckers @ Biscuits Shuckers @ Biscuits

Follow on MiLB First Pitch  https //stza.co/+vcl$-1j

Shop  https //stza.co/+vcl$-12

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Shuckers @ Biscuits
END:VALARM
DTSTART:20180507T233500Z
DTEND:20180508T023500Z
UID:3U1ZjcTjTGqHAomWDkRFQzkM@stanza.co
SUMMARY:Shuckers @ Biscuits
DESCRIPTION:Shuckers @ Biscuits\n\nFollow on MiLB First Pitch: https://stza.co/+vcl$-1j\n\nShop: https://stza.co/+vcl$-12\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144505Z
LAST-MODIFIED:20180213T144505Z
TRANSP:OPAQUE
END:VEVENT
* Shuckers @ Biscuits
<2018-05-08 Tue 10:35-13:35>
:PROPERTIES:
:ID:       Pteof3us1LucDf5YVNa1SGsd@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Shuckers @ Biscuits Shuckers @ Biscuits

Follow on MiLB First Pitch  https //stza.co/+vcm8-6

Shop  https //stza.co/+vcm8-1r

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Shuckers @ Biscuits
END:VALARM
DTSTART:20180508T153500Z
DTEND:20180508T183500Z
UID:Pteof3us1LucDf5YVNa1SGsd@stanza.co
SUMMARY:Shuckers @ Biscuits
DESCRIPTION:Shuckers @ Biscuits\n\nFollow on MiLB First Pitch: https://stza.co/+vcm8-6\n\nShop: https://stza.co/+vcm8-1r\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144505Z
LAST-MODIFIED:20180213T144505Z
TRANSP:OPAQUE
END:VEVENT
* Shuckers @ Biscuits
<2018-05-09 Wed 18:35-21:35>
:PROPERTIES:
:ID:       dqzFVAjwekViSHLdMknFEFZR@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Shuckers @ Biscuits Shuckers @ Biscuits

Follow on MiLB First Pitch  https //stza.co/+vcmh-2S

Shop  https //stza.co/+vcmh-2$

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Shuckers @ Biscuits
END:VALARM
DTSTART:20180509T233500Z
DTEND:20180510T023500Z
UID:dqzFVAjwekViSHLdMknFEFZR@stanza.co
SUMMARY:Shuckers @ Biscuits
DESCRIPTION:Shuckers @ Biscuits\n\nFollow on MiLB First Pitch: https://stza.co/+vcmh-2S\n\nShop: https://stza.co/+vcmh-2$\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144505Z
LAST-MODIFIED:20180213T144505Z
TRANSP:OPAQUE
END:VEVENT
* Shuckers @ Biscuits
<2018-05-10 Thu 18:35-21:35>
:PROPERTIES:
:ID:       wXpuiGwE5kqMnySStpVBl02X@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Shuckers @ Biscuits Shuckers @ Biscuits

Follow on MiLB First Pitch  https //stza.co/+vcmp-3t

Shop  https //stza.co/+vcmp-Q

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Shuckers @ Biscuits
END:VALARM
DTSTART:20180510T233500Z
DTEND:20180511T023500Z
UID:wXpuiGwE5kqMnySStpVBl02X@stanza.co
SUMMARY:Shuckers @ Biscuits
DESCRIPTION:Shuckers @ Biscuits\n\nFollow on MiLB First Pitch: https://stza.co/+vcmp-3t\n\nShop: https://stza.co/+vcmp-Q\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144505Z
LAST-MODIFIED:20180213T144505Z
TRANSP:OPAQUE
END:VEVENT
* Shuckers @ Biscuits
<2018-05-11 Fri 18:35-21:35>
:PROPERTIES:
:ID:       8g7scc3E_AlB8TYnoKmrR4E7@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Shuckers @ Biscuits Shuckers @ Biscuits

Follow on MiLB First Pitch  https //stza.co/+vcmw-1K

Shop  https //stza.co/+vcmw-3e

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Shuckers @ Biscuits
END:VALARM
DTSTART:20180511T233500Z
DTEND:20180512T023500Z
UID:8g7scc3E_AlB8TYnoKmrR4E7@stanza.co
SUMMARY:Shuckers @ Biscuits
DESCRIPTION:Shuckers @ Biscuits\n\nFollow on MiLB First Pitch: https://stza.co/+vcmw-1K\n\nShop: https://stza.co/+vcmw-3e\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144505Z
LAST-MODIFIED:20180213T144505Z
TRANSP:OPAQUE
END:VEVENT
* Shuckers vs. Blue Wahoos
<2018-05-12 Sat 18:35-21:35>
:PROPERTIES:
:ID:       P27yj1vY75EBd1FuuvmYJth1@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Shuckers vs. Blue Wahoos Shuckers vs. Blue Wahoos

Follow on MiLB First Pitch  https //stza.co/+vLx4-3w

Shop  https //stza.co/+vLx4-2e

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Shuckers vs. Blue Wahoos
END:VALARM
DTSTART:20180512T233500Z
DTEND:20180513T023500Z
UID:P27yj1vY75EBd1FuuvmYJth1@stanza.co
SUMMARY:Shuckers vs. Blue Wahoos
DESCRIPTION:Shuckers vs. Blue Wahoos\n\nFollow on MiLB First Pitch: https://stza.co/+vLx4-3w\n\nShop: https://stza.co/+vLx4-2e\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144505Z
LAST-MODIFIED:20180213T144505Z
TRANSP:OPAQUE
END:VEVENT
* Shuckers vs. Blue Wahoos
<2018-05-13 Sun 14:05-17:05>
:PROPERTIES:
:ID:       ssrIqI2qezDBEWT3lMKYmhmp@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Shuckers vs. Blue Wahoos Shuckers vs. Blue Wahoos

Follow on MiLB First Pitch  https //stza.co/+vLx5-1R

Shop  https //stza.co/+vLx5-3e

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Shuckers vs. Blue Wahoos
END:VALARM
DTSTART:20180513T190500Z
DTEND:20180513T220500Z
UID:ssrIqI2qezDBEWT3lMKYmhmp@stanza.co
SUMMARY:Shuckers vs. Blue Wahoos
DESCRIPTION:Shuckers vs. Blue Wahoos\n\nFollow on MiLB First Pitch: https://stza.co/+vLx5-1R\n\nShop: https://stza.co/+vLx5-3e\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144505Z
LAST-MODIFIED:20180213T144505Z
TRANSP:OPAQUE
END:VEVENT
* Shuckers vs. Blue Wahoos
<2018-05-14 Mon 18:35-21:35>
:PROPERTIES:
:ID:       xwLFi-XZE_r8l4HZ6CjFHwMU@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Shuckers vs. Blue Wahoos Shuckers vs. Blue Wahoos

Follow on MiLB First Pitch  https //stza.co/+vLx8-1I

Shop  https //stza.co/+vLx8-2h

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Shuckers vs. Blue Wahoos
END:VALARM
DTSTART:20180514T233500Z
DTEND:20180515T023500Z
UID:xwLFi-XZE_r8l4HZ6CjFHwMU@stanza.co
SUMMARY:Shuckers vs. Blue Wahoos
DESCRIPTION:Shuckers vs. Blue Wahoos\n\nFollow on MiLB First Pitch: https://stza.co/+vLx8-1I\n\nShop: https://stza.co/+vLx8-2h\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144505Z
LAST-MODIFIED:20180213T144505Z
TRANSP:OPAQUE
END:VEVENT
* Shuckers vs. Blue Wahoos
<2018-05-15 Tue 18:35-21:35>
:PROPERTIES:
:ID:       gkrVH4C60VlzR8bV9uLK_DOI@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Shuckers vs. Blue Wahoos Shuckers vs. Blue Wahoos

Follow on MiLB First Pitch  https //stza.co/+vLx9-3s

Shop  https //stza.co/+vLx9-3B

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Shuckers vs. Blue Wahoos
END:VALARM
DTSTART:20180515T233500Z
DTEND:20180516T023500Z
UID:gkrVH4C60VlzR8bV9uLK_DOI@stanza.co
SUMMARY:Shuckers vs. Blue Wahoos
DESCRIPTION:Shuckers vs. Blue Wahoos\n\nFollow on MiLB First Pitch: https://stza.co/+vLx9-3s\n\nShop: https://stza.co/+vLx9-3B\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144505Z
LAST-MODIFIED:20180213T144505Z
TRANSP:OPAQUE
END:VEVENT
* Shuckers vs. Blue Wahoos
<2018-05-16 Wed 10:35-13:35>
:PROPERTIES:
:ID:       4oCol0CeZcbXZKpmVF9CqUxn@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Shuckers vs. Blue Wahoos Shuckers vs. Blue Wahoos

Follow on MiLB First Pitch  https //stza.co/+vLxb-2Q

Shop  https //stza.co/+vLxb-g

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Shuckers vs. Blue Wahoos
END:VALARM
DTSTART:20180516T153500Z
DTEND:20180516T183500Z
UID:4oCol0CeZcbXZKpmVF9CqUxn@stanza.co
SUMMARY:Shuckers vs. Blue Wahoos
DESCRIPTION:Shuckers vs. Blue Wahoos\n\nFollow on MiLB First Pitch: https://stza.co/+vLxb-2Q\n\nShop: https://stza.co/+vLxb-g\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144505Z
LAST-MODIFIED:20180213T144505Z
TRANSP:OPAQUE
END:VEVENT
* Shuckers vs. Lookouts
<2018-05-17 Thu 18:35-21:35>
:PROPERTIES:
:ID:       2RvlA-0wFJPARv9QNgRzb6kK@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Shuckers vs. Lookouts Shuckers vs. Lookouts

Follow on MiLB First Pitch  https //stza.co/+vLxd-3I

Shop  https //stza.co/+vLxd-5

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Shuckers vs. Lookouts
END:VALARM
DTSTART:20180517T233500Z
DTEND:20180518T023500Z
UID:2RvlA-0wFJPARv9QNgRzb6kK@stanza.co
SUMMARY:Shuckers vs. Lookouts
DESCRIPTION:Shuckers vs. Lookouts\n\nFollow on MiLB First Pitch: https://stza.co/+vLxd-3I\n\nShop: https://stza.co/+vLxd-5\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144505Z
LAST-MODIFIED:20180213T144505Z
TRANSP:OPAQUE
END:VEVENT
* Shuckers vs. Lookouts
<2018-05-18 Fri 18:35-21:35>
:PROPERTIES:
:ID:       sFviPU5JGHbEiiWmIw0DHRWs@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Shuckers vs. Lookouts Shuckers vs. Lookouts

Follow on MiLB First Pitch  https //stza.co/+vLxf-3e

Shop  https //stza.co/+vLxf-B

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Shuckers vs. Lookouts
END:VALARM
DTSTART:20180518T233500Z
DTEND:20180519T023500Z
UID:sFviPU5JGHbEiiWmIw0DHRWs@stanza.co
SUMMARY:Shuckers vs. Lookouts
DESCRIPTION:Shuckers vs. Lookouts\n\nFollow on MiLB First Pitch: https://stza.co/+vLxf-3e\n\nShop: https://stza.co/+vLxf-B\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144505Z
LAST-MODIFIED:20180213T144505Z
TRANSP:OPAQUE
END:VEVENT
* Shuckers vs. Lookouts
<2018-05-19 Sat 18:35-21:35>
:PROPERTIES:
:ID:       zbjNvTpKWoSDX5NTm6uYynhQ@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Shuckers vs. Lookouts Shuckers vs. Lookouts

Follow on MiLB First Pitch  https //stza.co/+vLxi-2

Shop  https //stza.co/+vLxi-6

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Shuckers vs. Lookouts
END:VALARM
DTSTART:20180519T233500Z
DTEND:20180520T023500Z
UID:zbjNvTpKWoSDX5NTm6uYynhQ@stanza.co
SUMMARY:Shuckers vs. Lookouts
DESCRIPTION:Shuckers vs. Lookouts\n\nFollow on MiLB First Pitch: https://stza.co/+vLxi-2\n\nShop: https://stza.co/+vLxi-6\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144505Z
LAST-MODIFIED:20180213T144505Z
TRANSP:OPAQUE
END:VEVENT
* Shuckers vs. Lookouts
<2018-05-20 Sun 14:05-17:05>
:PROPERTIES:
:ID:       18SU2H_tJLYs2SIk1N1Ho9HR@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Shuckers vs. Lookouts Shuckers vs. Lookouts

Follow on MiLB First Pitch  https //stza.co/+vLxk-1I

Shop  https //stza.co/+vLxk-12

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Shuckers vs. Lookouts
END:VALARM
DTSTART:20180520T190500Z
DTEND:20180520T220500Z
UID:18SU2H_tJLYs2SIk1N1Ho9HR@stanza.co
SUMMARY:Shuckers vs. Lookouts
DESCRIPTION:Shuckers vs. Lookouts\n\nFollow on MiLB First Pitch: https://stza.co/+vLxk-1I\n\nShop: https://stza.co/+vLxk-12\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144505Z
LAST-MODIFIED:20180213T144505Z
TRANSP:OPAQUE
END:VEVENT
* Shuckers vs. Lookouts
<2018-05-21 Mon 18:35-21:35>
:PROPERTIES:
:ID:       05JoQOjVogjyGBplkJfzsFg7@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Shuckers vs. Lookouts Shuckers vs. Lookouts

Follow on MiLB First Pitch  https //stza.co/+vLxl-1k

Shop  https //stza.co/+vLxl-x

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Shuckers vs. Lookouts
END:VALARM
DTSTART:20180521T233500Z
DTEND:20180522T023500Z
UID:05JoQOjVogjyGBplkJfzsFg7@stanza.co
SUMMARY:Shuckers vs. Lookouts
DESCRIPTION:Shuckers vs. Lookouts\n\nFollow on MiLB First Pitch: https://stza.co/+vLxl-1k\n\nShop: https://stza.co/+vLxl-x\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144505Z
LAST-MODIFIED:20180213T144505Z
TRANSP:OPAQUE
END:VEVENT
* Shuckers @ BayBears
<2018-05-23 Wed 18:35-21:35>
:PROPERTIES:
:ID:       mV2AEpp694bloFoUD56Zmrf4@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Shuckers @ BayBears Shuckers @ BayBears

Follow on MiLB First Pitch  https //stza.co/+v$Pp-18

Shop  https //stza.co/+v$Pp-3i

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Shuckers @ BayBears
END:VALARM
DTSTART:20180523T233500Z
DTEND:20180524T023500Z
UID:mV2AEpp694bloFoUD56Zmrf4@stanza.co
SUMMARY:Shuckers @ BayBears
DESCRIPTION:Shuckers @ BayBears\n\nFollow on MiLB First Pitch: https://stza.co/+v$Pp-18\n\nShop: https://stza.co/+v$Pp-3i\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144505Z
LAST-MODIFIED:20180213T144505Z
TRANSP:OPAQUE
END:VEVENT
* Shuckers @ BayBears
<2018-05-24 Thu 18:35-21:35>
:PROPERTIES:
:ID:       4p2sWddzQ5YSZXj48PG3SU0D@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Shuckers @ BayBears Shuckers @ BayBears

Follow on MiLB First Pitch  https //stza.co/+v$Pq-1X

Shop  https //stza.co/+v$Pq-2p

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Shuckers @ BayBears
END:VALARM
DTSTART:20180524T233500Z
DTEND:20180525T023500Z
UID:4p2sWddzQ5YSZXj48PG3SU0D@stanza.co
SUMMARY:Shuckers @ BayBears
DESCRIPTION:Shuckers @ BayBears\n\nFollow on MiLB First Pitch: https://stza.co/+v$Pq-1X\n\nShop: https://stza.co/+v$Pq-2p\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144505Z
LAST-MODIFIED:20180213T144505Z
TRANSP:OPAQUE
END:VEVENT
* Shuckers @ BayBears
<2018-05-25 Fri 19:05-22:05>
:PROPERTIES:
:ID:       vGZN92UDAuAifrH9w7ryVu-u@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Shuckers @ BayBears Shuckers @ BayBears

Follow on MiLB First Pitch  https //stza.co/+v$Pr-g

Shop  https //stza.co/+v$Pr-2o

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Shuckers @ BayBears
END:VALARM
DTSTART:20180526T000500Z
DTEND:20180526T030500Z
UID:vGZN92UDAuAifrH9w7ryVu-u@stanza.co
SUMMARY:Shuckers @ BayBears
DESCRIPTION:Shuckers @ BayBears\n\nFollow on MiLB First Pitch: https://stza.co/+v$Pr-g\n\nShop: https://stza.co/+v$Pr-2o\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144505Z
LAST-MODIFIED:20180213T144505Z
TRANSP:OPAQUE
END:VEVENT
* Shuckers @ BayBears
<2018-05-26 Sat 19:05-22:05>
:PROPERTIES:
:ID:       uAjkpyMm_PfXcJVLDviUG0mX@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Shuckers @ BayBears Shuckers @ BayBears

Follow on MiLB First Pitch  https //stza.co/+v$Ps-1s

Shop  https //stza.co/+v$Ps-1A

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Shuckers @ BayBears
END:VALARM
DTSTART:20180527T000500Z
DTEND:20180527T030500Z
UID:uAjkpyMm_PfXcJVLDviUG0mX@stanza.co
SUMMARY:Shuckers @ BayBears
DESCRIPTION:Shuckers @ BayBears\n\nFollow on MiLB First Pitch: https://stza.co/+v$Ps-1s\n\nShop: https://stza.co/+v$Ps-1A\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144505Z
LAST-MODIFIED:20180213T144505Z
TRANSP:OPAQUE
END:VEVENT
* Shuckers @ BayBears
<2018-05-27 Sun 14:05-17:05>
:PROPERTIES:
:ID:       K3cqTTooHC5voWUvodera8eC@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Shuckers @ BayBears Shuckers @ BayBears

Follow on MiLB First Pitch  https //stza.co/+v$Pt-d

Shop  https //stza.co/+v$Pt-c

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Shuckers @ BayBears
END:VALARM
DTSTART:20180527T190500Z
DTEND:20180527T220500Z
UID:K3cqTTooHC5voWUvodera8eC@stanza.co
SUMMARY:Shuckers @ BayBears
DESCRIPTION:Shuckers @ BayBears\n\nFollow on MiLB First Pitch: https://stza.co/+v$Pt-d\n\nShop: https://stza.co/+v$Pt-c\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144505Z
LAST-MODIFIED:20180213T144505Z
TRANSP:OPAQUE
END:VEVENT
* Shuckers vs. Braves
<2018-05-29 Tue 18:35-21:35>
:PROPERTIES:
:ID:       BtK2DQ2fR0K47rcvLE3SBiHn@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Shuckers vs. Braves Shuckers vs. Braves

Follow on MiLB First Pitch  https //stza.co/+vLxo-2y

Shop  https //stza.co/+vLxo-2k

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Shuckers vs. Braves
END:VALARM
DTSTART:20180529T233500Z
DTEND:20180530T023500Z
UID:BtK2DQ2fR0K47rcvLE3SBiHn@stanza.co
SUMMARY:Shuckers vs. Braves
DESCRIPTION:Shuckers vs. Braves\n\nFollow on MiLB First Pitch: https://stza.co/+vLxo-2y\n\nShop: https://stza.co/+vLxo-2k\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144505Z
LAST-MODIFIED:20180213T144505Z
TRANSP:OPAQUE
END:VEVENT
* Shuckers vs. Braves
<2018-05-30 Wed 18:35-21:35>
:PROPERTIES:
:ID:       7KD2fM_wVYdtfumxkB8_BAKR@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Shuckers vs. Braves Shuckers vs. Braves

Follow on MiLB First Pitch  https //stza.co/+vLxq-1r

Shop  https //stza.co/+vLxq-J

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Shuckers vs. Braves
END:VALARM
DTSTART:20180530T233500Z
DTEND:20180531T023500Z
UID:7KD2fM_wVYdtfumxkB8_BAKR@stanza.co
SUMMARY:Shuckers vs. Braves
DESCRIPTION:Shuckers vs. Braves\n\nFollow on MiLB First Pitch: https://stza.co/+vLxq-1r\n\nShop: https://stza.co/+vLxq-J\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144505Z
LAST-MODIFIED:20180213T144505Z
TRANSP:OPAQUE
END:VEVENT
* Shuckers vs. Braves
<2018-05-31 Thu 18:35-21:35>
:PROPERTIES:
:ID:       HVhkwjwLBwyxo9GCoG5vyt-H@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Shuckers vs. Braves Shuckers vs. Braves

Follow on MiLB First Pitch  https //stza.co/+vLxs-3n

Shop  https //stza.co/+vLxs-3g

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Shuckers vs. Braves
END:VALARM
DTSTART:20180531T233500Z
DTEND:20180601T023500Z
UID:HVhkwjwLBwyxo9GCoG5vyt-H@stanza.co
SUMMARY:Shuckers vs. Braves
DESCRIPTION:Shuckers vs. Braves\n\nFollow on MiLB First Pitch: https://stza.co/+vLxs-3n\n\nShop: https://stza.co/+vLxs-3g\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144505Z
LAST-MODIFIED:20180213T144505Z
TRANSP:OPAQUE
END:VEVENT
* Shuckers vs. Braves
<2018-06-01 Fri 18:35-21:35>
:PROPERTIES:
:ID:       Qp9JOu51sL02nYs_s2J3tlaD@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Shuckers vs. Braves Shuckers vs. Braves

Follow on MiLB First Pitch  https //stza.co/+vLxu-e

Shop  https //stza.co/+vLxu-2D

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Shuckers vs. Braves
END:VALARM
DTSTART:20180601T233500Z
DTEND:20180602T023500Z
UID:Qp9JOu51sL02nYs_s2J3tlaD@stanza.co
SUMMARY:Shuckers vs. Braves
DESCRIPTION:Shuckers vs. Braves\n\nFollow on MiLB First Pitch: https://stza.co/+vLxu-e\n\nShop: https://stza.co/+vLxu-2D\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144505Z
LAST-MODIFIED:20180213T144505Z
TRANSP:OPAQUE
END:VEVENT
* Shuckers vs. Braves
<2018-06-02 Sat 18:35-21:35>
:PROPERTIES:
:ID:       qJvaUz5jcYdl1W7sRCmc8Qze@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Shuckers vs. Braves Shuckers vs. Braves

Follow on MiLB First Pitch  https //stza.co/+vLxv-1v

Shop  https //stza.co/+vLxv-e

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Shuckers vs. Braves
END:VALARM
DTSTART:20180602T233500Z
DTEND:20180603T023500Z
UID:qJvaUz5jcYdl1W7sRCmc8Qze@stanza.co
SUMMARY:Shuckers vs. Braves
DESCRIPTION:Shuckers vs. Braves\n\nFollow on MiLB First Pitch: https://stza.co/+vLxv-1v\n\nShop: https://stza.co/+vLxv-e\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144505Z
LAST-MODIFIED:20180213T144505Z
TRANSP:OPAQUE
END:VEVENT
* Shuckers @ Blue Wahoos
<2018-06-03 Sun 17:05-20:05>
:PROPERTIES:
:ID:       80eIWj7Zb1MzHIPS458pnb_B@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Shuckers @ Blue Wahoos Shuckers @ Blue Wahoos

Follow on MiLB First Pitch  https //stza.co/+wx6j-3I

Shop  https //stza.co/+wx6j-p

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Shuckers @ Blue Wahoos
END:VALARM
DTSTART:20180603T220500Z
DTEND:20180604T010500Z
UID:80eIWj7Zb1MzHIPS458pnb_B@stanza.co
SUMMARY:Shuckers @ Blue Wahoos
DESCRIPTION:Shuckers @ Blue Wahoos\n\nFollow on MiLB First Pitch: https://stza.co/+wx6j-3I\n\nShop: https://stza.co/+wx6j-p\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144505Z
LAST-MODIFIED:20180213T144505Z
TRANSP:OPAQUE
END:VEVENT
* Shuckers @ Blue Wahoos
<2018-06-04 Mon 18:35-21:35>
:PROPERTIES:
:ID:       5hLszBQKXE__lCKf9FvzSVhC@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Shuckers @ Blue Wahoos Shuckers @ Blue Wahoos

Follow on MiLB First Pitch  https //stza.co/+wx6m-19

Shop  https //stza.co/+wx6m-n

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Shuckers @ Blue Wahoos
END:VALARM
DTSTART:20180604T233500Z
DTEND:20180605T023500Z
UID:5hLszBQKXE__lCKf9FvzSVhC@stanza.co
SUMMARY:Shuckers @ Blue Wahoos
DESCRIPTION:Shuckers @ Blue Wahoos\n\nFollow on MiLB First Pitch: https://stza.co/+wx6m-19\n\nShop: https://stza.co/+wx6m-n\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144505Z
LAST-MODIFIED:20180213T144505Z
TRANSP:OPAQUE
END:VEVENT
* Shuckers @ Blue Wahoos
<2018-06-05 Tue 18:35-21:35>
:PROPERTIES:
:ID:       KmttuOL0pEltwq6yxoRfaKf9@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Shuckers @ Blue Wahoos Shuckers @ Blue Wahoos

Follow on MiLB First Pitch  https //stza.co/+wx6p-2y

Shop  https //stza.co/+wx6p-1Y

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Shuckers @ Blue Wahoos
END:VALARM
DTSTART:20180605T233500Z
DTEND:20180606T023500Z
UID:KmttuOL0pEltwq6yxoRfaKf9@stanza.co
SUMMARY:Shuckers @ Blue Wahoos
DESCRIPTION:Shuckers @ Blue Wahoos\n\nFollow on MiLB First Pitch: https://stza.co/+wx6p-2y\n\nShop: https://stza.co/+wx6p-1Y\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144505Z
LAST-MODIFIED:20180213T144505Z
TRANSP:OPAQUE
END:VEVENT
* Shuckers @ Blue Wahoos
<2018-06-06 Wed 18:35-21:35>
:PROPERTIES:
:ID:       Cgpb9wS9MMDltaIpC2dCpCT3@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Shuckers @ Blue Wahoos Shuckers @ Blue Wahoos

Follow on MiLB First Pitch  https //stza.co/+wx6q-2J

Shop  https //stza.co/+wx6q-3o

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Shuckers @ Blue Wahoos
END:VALARM
DTSTART:20180606T233500Z
DTEND:20180607T023500Z
UID:Cgpb9wS9MMDltaIpC2dCpCT3@stanza.co
SUMMARY:Shuckers @ Blue Wahoos
DESCRIPTION:Shuckers @ Blue Wahoos\n\nFollow on MiLB First Pitch: https://stza.co/+wx6q-2J\n\nShop: https://stza.co/+wx6q-3o\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144505Z
LAST-MODIFIED:20180213T144505Z
TRANSP:OPAQUE
END:VEVENT
* Shuckers @ Blue Wahoos
<2018-06-07 Thu 18:35-21:35>
:PROPERTIES:
:ID:       dgzPROKBH75R2Oylapr_2ZO2@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Shuckers @ Blue Wahoos Shuckers @ Blue Wahoos

Follow on MiLB First Pitch  https //stza.co/+wx6r-3D

Shop  https //stza.co/+wx6r-33

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Shuckers @ Blue Wahoos
END:VALARM
DTSTART:20180607T233500Z
DTEND:20180608T023500Z
UID:dgzPROKBH75R2Oylapr_2ZO2@stanza.co
SUMMARY:Shuckers @ Blue Wahoos
DESCRIPTION:Shuckers @ Blue Wahoos\n\nFollow on MiLB First Pitch: https://stza.co/+wx6r-3D\n\nShop: https://stza.co/+wx6r-33\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144505Z
LAST-MODIFIED:20180213T144505Z
TRANSP:OPAQUE
END:VEVENT
* Shuckers @ Jumbo Shrimp
<2018-06-08 Fri 18:05-21:05>
:PROPERTIES:
:ID:       jvwpdcq7GGv6OcQb5NQJtyD5@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Shuckers @ Jumbo Shrimp Shuckers @ Jumbo Shrimp

Follow on MiLB First Pitch  https //stza.co/+vcgG-B

Shop  https //stza.co/+vcgG-11

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Shuckers @ Jumbo Shrimp
END:VALARM
DTSTART:20180608T230500Z
DTEND:20180609T020500Z
UID:jvwpdcq7GGv6OcQb5NQJtyD5@stanza.co
SUMMARY:Shuckers @ Jumbo Shrimp
DESCRIPTION:Shuckers @ Jumbo Shrimp\n\nFollow on MiLB First Pitch: https://stza.co/+vcgG-B\n\nShop: https://stza.co/+vcgG-11\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144505Z
LAST-MODIFIED:20180213T144505Z
TRANSP:OPAQUE
END:VEVENT
* Shuckers @ Jumbo Shrimp
<2018-06-09 Sat 17:35-20:35>
:PROPERTIES:
:ID:       BVRyX2OKnA-FF8qW6wFdqeos@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Shuckers @ Jumbo Shrimp Shuckers @ Jumbo Shrimp

Follow on MiLB First Pitch  https //stza.co/+vcgR-1G

Shop  https //stza.co/+vcgR-3i

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Shuckers @ Jumbo Shrimp
END:VALARM
DTSTART:20180609T223500Z
DTEND:20180610T013500Z
UID:BVRyX2OKnA-FF8qW6wFdqeos@stanza.co
SUMMARY:Shuckers @ Jumbo Shrimp
DESCRIPTION:Shuckers @ Jumbo Shrimp\n\nFollow on MiLB First Pitch: https://stza.co/+vcgR-1G\n\nShop: https://stza.co/+vcgR-3i\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144505Z
LAST-MODIFIED:20180213T144505Z
TRANSP:OPAQUE
END:VEVENT
* Shuckers @ Jumbo Shrimp
<2018-06-10 Sun 14:05-17:05>
:PROPERTIES:
:ID:       X5MHbf0el2lT8cOwFyuymYyi@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Shuckers @ Jumbo Shrimp Shuckers @ Jumbo Shrimp

Follow on MiLB First Pitch  https //stza.co/+vcgY-s

Shop  https //stza.co/+vcgY-14

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Shuckers @ Jumbo Shrimp
END:VALARM
DTSTART:20180610T190500Z
DTEND:20180610T220500Z
UID:X5MHbf0el2lT8cOwFyuymYyi@stanza.co
SUMMARY:Shuckers @ Jumbo Shrimp
DESCRIPTION:Shuckers @ Jumbo Shrimp\n\nFollow on MiLB First Pitch: https://stza.co/+vcgY-s\n\nShop: https://stza.co/+vcgY-14\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144505Z
LAST-MODIFIED:20180213T144505Z
TRANSP:OPAQUE
END:VEVENT
* Shuckers @ Jumbo Shrimp
<2018-06-11 Mon 18:05-21:05>
:PROPERTIES:
:ID:       LdEsgZPt2_T35brKGWx52D2-@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Shuckers @ Jumbo Shrimp Shuckers @ Jumbo Shrimp

Follow on MiLB First Pitch  https //stza.co/+vch9-2M

Shop  https //stza.co/+vch9-x

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Shuckers @ Jumbo Shrimp
END:VALARM
DTSTART:20180611T230500Z
DTEND:20180612T020500Z
UID:LdEsgZPt2_T35brKGWx52D2-@stanza.co
SUMMARY:Shuckers @ Jumbo Shrimp
DESCRIPTION:Shuckers @ Jumbo Shrimp\n\nFollow on MiLB First Pitch: https://stza.co/+vch9-2M\n\nShop: https://stza.co/+vch9-x\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144505Z
LAST-MODIFIED:20180213T144505Z
TRANSP:OPAQUE
END:VEVENT
* Shuckers @ Jumbo Shrimp
<2018-06-12 Tue 11:05-14:05>
:PROPERTIES:
:ID:       K2JPfKbAxfZvP7kl9rh5lM9e@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Shuckers @ Jumbo Shrimp Shuckers @ Jumbo Shrimp

Follow on MiLB First Pitch  https //stza.co/+vchm-3e

Shop  https //stza.co/+vchm-1k

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Shuckers @ Jumbo Shrimp
END:VALARM
DTSTART:20180612T160500Z
DTEND:20180612T190500Z
UID:K2JPfKbAxfZvP7kl9rh5lM9e@stanza.co
SUMMARY:Shuckers @ Jumbo Shrimp
DESCRIPTION:Shuckers @ Jumbo Shrimp\n\nFollow on MiLB First Pitch: https://stza.co/+vchm-3e\n\nShop: https://stza.co/+vchm-1k\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144505Z
LAST-MODIFIED:20180213T144505Z
TRANSP:OPAQUE
END:VEVENT
* Shuckers vs. Braves
<2018-06-13 Wed 18:35-21:35>
:PROPERTIES:
:ID:       ELKg_8HEfvHawYndviGkOXH9@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Shuckers vs. Braves Shuckers vs. Braves

Follow on MiLB First Pitch  https //stza.co/+vLxx-3i

Shop  https //stza.co/+vLxx-t

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Shuckers vs. Braves
END:VALARM
DTSTART:20180613T233500Z
DTEND:20180614T023500Z
UID:ELKg_8HEfvHawYndviGkOXH9@stanza.co
SUMMARY:Shuckers vs. Braves
DESCRIPTION:Shuckers vs. Braves\n\nFollow on MiLB First Pitch: https://stza.co/+vLxx-3i\n\nShop: https://stza.co/+vLxx-t\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144505Z
LAST-MODIFIED:20180213T144505Z
TRANSP:OPAQUE
END:VEVENT
* Shuckers vs. Braves
<2018-06-14 Thu 18:35-21:35>
:PROPERTIES:
:ID:       JLr196cFFZ2HcC2FRYRvQqs_@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Shuckers vs. Braves Shuckers vs. Braves

Follow on MiLB First Pitch  https //stza.co/+vLxA-1w

Shop  https //stza.co/+vLxA-1m

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Shuckers vs. Braves
END:VALARM
DTSTART:20180614T233500Z
DTEND:20180615T023500Z
UID:JLr196cFFZ2HcC2FRYRvQqs_@stanza.co
SUMMARY:Shuckers vs. Braves
DESCRIPTION:Shuckers vs. Braves\n\nFollow on MiLB First Pitch: https://stza.co/+vLxA-1w\n\nShop: https://stza.co/+vLxA-1m\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144505Z
LAST-MODIFIED:20180213T144505Z
TRANSP:OPAQUE
END:VEVENT
* Shuckers vs. Braves
<2018-06-15 Fri 18:35-21:35>
:PROPERTIES:
:ID:       ysgqYSqS12T5oGdrx90fk2wo@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Shuckers vs. Braves Shuckers vs. Braves

Follow on MiLB First Pitch  https //stza.co/+vLxC-t

Shop  https //stza.co/+vLxC-g

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Shuckers vs. Braves
END:VALARM
DTSTART:20180615T233500Z
DTEND:20180616T023500Z
UID:ysgqYSqS12T5oGdrx90fk2wo@stanza.co
SUMMARY:Shuckers vs. Braves
DESCRIPTION:Shuckers vs. Braves\n\nFollow on MiLB First Pitch: https://stza.co/+vLxC-t\n\nShop: https://stza.co/+vLxC-g\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144505Z
LAST-MODIFIED:20180213T144505Z
TRANSP:OPAQUE
END:VEVENT
* Shuckers vs. Braves
<2018-06-16 Sat 18:35-21:35>
:PROPERTIES:
:ID:       9Ks7UMN4_n_TLgONFaKf9HAI@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Shuckers vs. Braves Shuckers vs. Braves

Follow on MiLB First Pitch  https //stza.co/+vLxD-2T

Shop  https //stza.co/+vLxD-2C

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Shuckers vs. Braves
END:VALARM
DTSTART:20180616T233500Z
DTEND:20180617T023500Z
UID:9Ks7UMN4_n_TLgONFaKf9HAI@stanza.co
SUMMARY:Shuckers vs. Braves
DESCRIPTION:Shuckers vs. Braves\n\nFollow on MiLB First Pitch: https://stza.co/+vLxD-2T\n\nShop: https://stza.co/+vLxD-2C\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144505Z
LAST-MODIFIED:20180213T144505Z
TRANSP:OPAQUE
END:VEVENT
* Shuckers vs. Braves
<2018-06-17 Sun 16:05-19:05>
:PROPERTIES:
:ID:       n1o8D1ZfjjaVXP_FvV_htTCo@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Shuckers vs. Braves Shuckers vs. Braves

Follow on MiLB First Pitch  https //stza.co/+vLxF-1x

Shop  https //stza.co/+vLxF-17

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Shuckers vs. Braves
END:VALARM
DTSTART:20180617T210500Z
DTEND:20180618T000500Z
UID:n1o8D1ZfjjaVXP_FvV_htTCo@stanza.co
SUMMARY:Shuckers vs. Braves
DESCRIPTION:Shuckers vs. Braves\n\nFollow on MiLB First Pitch: https://stza.co/+vLxF-1x\n\nShop: https://stza.co/+vLxF-17\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144505Z
LAST-MODIFIED:20180213T144505Z
TRANSP:OPAQUE
END:VEVENT
* Shuckers @ Lookouts
<2018-06-21 Thu 18:15-21:15>
:PROPERTIES:
:ID:       pi87wPdM2PDdyrG5es0ki98F@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Shuckers @ Lookouts Shuckers @ Lookouts

Follow on MiLB First Pitch  https //stza.co/+wKB6-1M

Shop  https //stza.co/+wKB6-11

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Shuckers @ Lookouts
END:VALARM
DTSTART:20180621T231500Z
DTEND:20180622T021500Z
UID:pi87wPdM2PDdyrG5es0ki98F@stanza.co
SUMMARY:Shuckers @ Lookouts
DESCRIPTION:Shuckers @ Lookouts\n\nFollow on MiLB First Pitch: https://stza.co/+wKB6-1M\n\nShop: https://stza.co/+wKB6-11\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144505Z
LAST-MODIFIED:20180213T144505Z
TRANSP:OPAQUE
END:VEVENT
* Shuckers @ Lookouts
<2018-06-22 Fri 18:15-21:15>
:PROPERTIES:
:ID:       ao2vGZsm8sTKU2T0kTjoHjAY@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Shuckers @ Lookouts Shuckers @ Lookouts

Follow on MiLB First Pitch  https //stza.co/+wKBb-27

Shop  https //stza.co/+wKBb-3E

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Shuckers @ Lookouts
END:VALARM
DTSTART:20180622T231500Z
DTEND:20180623T021500Z
UID:ao2vGZsm8sTKU2T0kTjoHjAY@stanza.co
SUMMARY:Shuckers @ Lookouts
DESCRIPTION:Shuckers @ Lookouts\n\nFollow on MiLB First Pitch: https://stza.co/+wKBb-27\n\nShop: https://stza.co/+wKBb-3E\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144505Z
LAST-MODIFIED:20180213T144505Z
TRANSP:OPAQUE
END:VEVENT
* Shuckers @ Lookouts
<2018-06-23 Sat 18:15-21:15>
:PROPERTIES:
:ID:       oXMvjp9KfXjbymueQEuv9hvN@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Shuckers @ Lookouts Shuckers @ Lookouts

Follow on MiLB First Pitch  https //stza.co/+wKBf-8

Shop  https //stza.co/+wKBf-2g

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Shuckers @ Lookouts
END:VALARM
DTSTART:20180623T231500Z
DTEND:20180624T021500Z
UID:oXMvjp9KfXjbymueQEuv9hvN@stanza.co
SUMMARY:Shuckers @ Lookouts
DESCRIPTION:Shuckers @ Lookouts\n\nFollow on MiLB First Pitch: https://stza.co/+wKBf-8\n\nShop: https://stza.co/+wKBf-2g\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144505Z
LAST-MODIFIED:20180213T144505Z
TRANSP:OPAQUE
END:VEVENT
* Shuckers @ Lookouts
<2018-06-24 Sun 13:15-16:15>
:PROPERTIES:
:ID:       oQvX0gU4BbSSvkX0tbIdWjrZ@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Shuckers @ Lookouts Shuckers @ Lookouts

Follow on MiLB First Pitch  https //stza.co/+wKBh-1U

Shop  https //stza.co/+wKBh-3U

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Shuckers @ Lookouts
END:VALARM
DTSTART:20180624T181500Z
DTEND:20180624T211500Z
UID:oQvX0gU4BbSSvkX0tbIdWjrZ@stanza.co
SUMMARY:Shuckers @ Lookouts
DESCRIPTION:Shuckers @ Lookouts\n\nFollow on MiLB First Pitch: https://stza.co/+wKBh-1U\n\nShop: https://stza.co/+wKBh-3U\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144505Z
LAST-MODIFIED:20180213T144505Z
TRANSP:OPAQUE
END:VEVENT
* Shuckers @ Lookouts
<2018-06-25 Mon 18:15-21:15>
:PROPERTIES:
:ID:       xoo-i2gop0njDJAbkjsgASTo@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Shuckers @ Lookouts Shuckers @ Lookouts

Follow on MiLB First Pitch  https //stza.co/+wKBi-2L

Shop  https //stza.co/+wKBi-l

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Shuckers @ Lookouts
END:VALARM
DTSTART:20180625T231500Z
DTEND:20180626T021500Z
UID:xoo-i2gop0njDJAbkjsgASTo@stanza.co
SUMMARY:Shuckers @ Lookouts
DESCRIPTION:Shuckers @ Lookouts\n\nFollow on MiLB First Pitch: https://stza.co/+wKBi-2L\n\nShop: https://stza.co/+wKBi-l\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144505Z
LAST-MODIFIED:20180213T144505Z
TRANSP:OPAQUE
END:VEVENT
* Shuckers @ Lookouts
<2018-06-26 Tue 10:15-13:15>
:PROPERTIES:
:ID:       nArbHLPbUE6mdnODJAvfvviQ@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Shuckers @ Lookouts Shuckers @ Lookouts

Follow on MiLB First Pitch  https //stza.co/+wKBj-1$

Shop  https //stza.co/+wKBj-3N

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Shuckers @ Lookouts
END:VALARM
DTSTART:20180626T151500Z
DTEND:20180626T181500Z
UID:nArbHLPbUE6mdnODJAvfvviQ@stanza.co
SUMMARY:Shuckers @ Lookouts
DESCRIPTION:Shuckers @ Lookouts\n\nFollow on MiLB First Pitch: https://stza.co/+wKBj-1$\n\nShop: https://stza.co/+wKBj-3N\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144505Z
LAST-MODIFIED:20180213T144505Z
TRANSP:OPAQUE
END:VEVENT
* Shuckers vs. BayBears
<2018-06-28 Thu 18:35-21:35>
:PROPERTIES:
:ID:       3g_9XJVOL4bRf5L0hUNzo900@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Shuckers vs. BayBears Shuckers vs. BayBears

Follow on MiLB First Pitch  https //stza.co/+vLxH-U

Shop  https //stza.co/+vLxH-2l

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Shuckers vs. BayBears
END:VALARM
DTSTART:20180628T233500Z
DTEND:20180629T023500Z
UID:3g_9XJVOL4bRf5L0hUNzo900@stanza.co
SUMMARY:Shuckers vs. BayBears
DESCRIPTION:Shuckers vs. BayBears\n\nFollow on MiLB First Pitch: https://stza.co/+vLxH-U\n\nShop: https://stza.co/+vLxH-2l\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144505Z
LAST-MODIFIED:20180213T144505Z
TRANSP:OPAQUE
END:VEVENT
* Shuckers vs. BayBears
<2018-06-29 Fri 18:35-21:35>
:PROPERTIES:
:ID:       9BKAsxHQ5_1EjBsDomsTunaG@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Shuckers vs. BayBears Shuckers vs. BayBears

Follow on MiLB First Pitch  https //stza.co/+vLxJ-1p

Shop  https //stza.co/+vLxJ-2$

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Shuckers vs. BayBears
END:VALARM
DTSTART:20180629T233500Z
DTEND:20180630T023500Z
UID:9BKAsxHQ5_1EjBsDomsTunaG@stanza.co
SUMMARY:Shuckers vs. BayBears
DESCRIPTION:Shuckers vs. BayBears\n\nFollow on MiLB First Pitch: https://stza.co/+vLxJ-1p\n\nShop: https://stza.co/+vLxJ-2$\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144505Z
LAST-MODIFIED:20180213T144505Z
TRANSP:OPAQUE
END:VEVENT
* Shuckers vs. BayBears
<2018-06-30 Sat 18:35-21:35>
:PROPERTIES:
:ID:       DqlYEuqBNnGzM81TiQQBKfE9@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Shuckers vs. BayBears Shuckers vs. BayBears

Follow on MiLB First Pitch  https //stza.co/+vLxM-f

Shop  https //stza.co/+vLxM-2u

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Shuckers vs. BayBears
END:VALARM
DTSTART:20180630T233500Z
DTEND:20180701T023500Z
UID:DqlYEuqBNnGzM81TiQQBKfE9@stanza.co
SUMMARY:Shuckers vs. BayBears
DESCRIPTION:Shuckers vs. BayBears\n\nFollow on MiLB First Pitch: https://stza.co/+vLxM-f\n\nShop: https://stza.co/+vLxM-2u\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144505Z
LAST-MODIFIED:20180213T144505Z
TRANSP:OPAQUE
END:VEVENT
* Shuckers vs. BayBears
<2018-07-01 Sun 16:05-19:05>
:PROPERTIES:
:ID:       A9ZfYMdAHEMLMitZhQ67V3LH@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Shuckers vs. BayBears Shuckers vs. BayBears

Follow on MiLB First Pitch  https //stza.co/+vLxN-2T

Shop  https //stza.co/+vLxN-13

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Shuckers vs. BayBears
END:VALARM
DTSTART:20180701T210500Z
DTEND:20180702T000500Z
UID:A9ZfYMdAHEMLMitZhQ67V3LH@stanza.co
SUMMARY:Shuckers vs. BayBears
DESCRIPTION:Shuckers vs. BayBears\n\nFollow on MiLB First Pitch: https://stza.co/+vLxN-2T\n\nShop: https://stza.co/+vLxN-13\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144505Z
LAST-MODIFIED:20180213T144505Z
TRANSP:OPAQUE
END:VEVENT
* Shuckers vs. BayBears
<2018-07-02 Mon 18:35-21:35>
:PROPERTIES:
:ID:       P4EqJAjKjQ39i8r4akwf7IXP@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Shuckers vs. BayBears Shuckers vs. BayBears

Follow on MiLB First Pitch  https //stza.co/+vLxQ-3i

Shop  https //stza.co/+vLxQ-V

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Shuckers vs. BayBears
END:VALARM
DTSTART:20180702T233500Z
DTEND:20180703T023500Z
UID:P4EqJAjKjQ39i8r4akwf7IXP@stanza.co
SUMMARY:Shuckers vs. BayBears
DESCRIPTION:Shuckers vs. BayBears\n\nFollow on MiLB First Pitch: https://stza.co/+vLxQ-3i\n\nShop: https://stza.co/+vLxQ-V\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144505Z
LAST-MODIFIED:20180213T144505Z
TRANSP:OPAQUE
END:VEVENT
* Shuckers vs. BayBears
<2018-07-03 Tue 18:35-21:35>
:PROPERTIES:
:ID:       ylTlQ-QlFVGEl5PbZQ3rqyAi@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Shuckers vs. BayBears Shuckers vs. BayBears

Follow on MiLB First Pitch  https //stza.co/+vLxR-13

Shop  https //stza.co/+vLxR-1t

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Shuckers vs. BayBears
END:VALARM
DTSTART:20180703T233500Z
DTEND:20180704T023500Z
UID:ylTlQ-QlFVGEl5PbZQ3rqyAi@stanza.co
SUMMARY:Shuckers vs. BayBears
DESCRIPTION:Shuckers vs. BayBears\n\nFollow on MiLB First Pitch: https://stza.co/+vLxR-13\n\nShop: https://stza.co/+vLxR-1t\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144505Z
LAST-MODIFIED:20180213T144505Z
TRANSP:OPAQUE
END:VEVENT
* Shuckers @ Braves
<2018-07-04 Wed 19:00-22:00>
:PROPERTIES:
:ID:       DnOommbz-rbu3LPmFguICnOx@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Shuckers @ Braves Shuckers @ Braves

Follow on MiLB First Pitch  https //stza.co/+vciq-2n

Shop  https //stza.co/+vciq-3N

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Shuckers @ Braves
END:VALARM
DTSTART:20180705T000000Z
DTEND:20180705T030000Z
UID:DnOommbz-rbu3LPmFguICnOx@stanza.co
SUMMARY:Shuckers @ Braves
DESCRIPTION:Shuckers @ Braves\n\nFollow on MiLB First Pitch: https://stza.co/+vciq-2n\n\nShop: https://stza.co/+vciq-3N\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144505Z
LAST-MODIFIED:20180213T144505Z
TRANSP:OPAQUE
END:VEVENT
* Shuckers @ Braves
<2018-07-05 Thu 19:00-22:00>
:PROPERTIES:
:ID:       EtSzrYYLf4aR9pF8g43xw4VG@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Shuckers @ Braves Shuckers @ Braves

Follow on MiLB First Pitch  https //stza.co/+vciA-1X

Shop  https //stza.co/+vciA-1u

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Shuckers @ Braves
END:VALARM
DTSTART:20180706T000000Z
DTEND:20180706T030000Z
UID:EtSzrYYLf4aR9pF8g43xw4VG@stanza.co
SUMMARY:Shuckers @ Braves
DESCRIPTION:Shuckers @ Braves\n\nFollow on MiLB First Pitch: https://stza.co/+vciA-1X\n\nShop: https://stza.co/+vciA-1u\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144505Z
LAST-MODIFIED:20180213T144505Z
TRANSP:OPAQUE
END:VEVENT
* Shuckers @ Braves
<2018-07-06 Fri 19:00-22:00>
:PROPERTIES:
:ID:       WCIsW271Sp7zO_YAtoe6lDhN@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Shuckers @ Braves Shuckers @ Braves

Follow on MiLB First Pitch  https //stza.co/+vciK-3b

Shop  https //stza.co/+vciK-2a

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Shuckers @ Braves
END:VALARM
DTSTART:20180707T000000Z
DTEND:20180707T030000Z
UID:WCIsW271Sp7zO_YAtoe6lDhN@stanza.co
SUMMARY:Shuckers @ Braves
DESCRIPTION:Shuckers @ Braves\n\nFollow on MiLB First Pitch: https://stza.co/+vciK-3b\n\nShop: https://stza.co/+vciK-2a\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144505Z
LAST-MODIFIED:20180213T144505Z
TRANSP:OPAQUE
END:VEVENT
* Shuckers @ Braves
<2018-07-07 Sat 18:00-21:00>
:PROPERTIES:
:ID:       PWkaDdk0wMlUnwCuPfzevNlC@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Shuckers @ Braves Shuckers @ Braves

Follow on MiLB First Pitch  https //stza.co/+vciX-36

Shop  https //stza.co/+vciX-j

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Shuckers @ Braves
END:VALARM
DTSTART:20180707T230000Z
DTEND:20180708T020000Z
UID:PWkaDdk0wMlUnwCuPfzevNlC@stanza.co
SUMMARY:Shuckers @ Braves
DESCRIPTION:Shuckers @ Braves\n\nFollow on MiLB First Pitch: https://stza.co/+vciX-36\n\nShop: https://stza.co/+vciX-j\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144505Z
LAST-MODIFIED:20180213T144505Z
TRANSP:OPAQUE
END:VEVENT
* Shuckers vs. Generals
<2018-07-08 Sun 16:05-19:05>
:PROPERTIES:
:ID:       bVv_Z1zMyqdIz-eNQYcsQtNd@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Shuckers vs. Generals Shuckers vs. Generals

Follow on MiLB First Pitch  https //stza.co/+vLxU-F

Shop  https //stza.co/+vLxU-V

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Shuckers vs. Generals
END:VALARM
DTSTART:20180708T210500Z
DTEND:20180709T000500Z
UID:bVv_Z1zMyqdIz-eNQYcsQtNd@stanza.co
SUMMARY:Shuckers vs. Generals
DESCRIPTION:Shuckers vs. Generals\n\nFollow on MiLB First Pitch: https://stza.co/+vLxU-F\n\nShop: https://stza.co/+vLxU-V\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144505Z
LAST-MODIFIED:20180213T144505Z
TRANSP:OPAQUE
END:VEVENT
* Shuckers vs. Generals
<2018-07-09 Mon 18:35-21:35>
:PROPERTIES:
:ID:       lk4BGj5lxiqnPE_HDh-BMEDb@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Shuckers vs. Generals Shuckers vs. Generals

Follow on MiLB First Pitch  https //stza.co/+vLxW-30

Shop  https //stza.co/+vLxW-3Q

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Shuckers vs. Generals
END:VALARM
DTSTART:20180709T233500Z
DTEND:20180710T023500Z
UID:lk4BGj5lxiqnPE_HDh-BMEDb@stanza.co
SUMMARY:Shuckers vs. Generals
DESCRIPTION:Shuckers vs. Generals\n\nFollow on MiLB First Pitch: https://stza.co/+vLxW-30\n\nShop: https://stza.co/+vLxW-3Q\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144505Z
LAST-MODIFIED:20180213T144505Z
TRANSP:OPAQUE
END:VEVENT
* Shuckers vs. Generals
<2018-07-10 Tue 18:35-21:35>
:PROPERTIES:
:ID:       04an6e4eouDISy71wqJHo0-c@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Shuckers vs. Generals Shuckers vs. Generals

Follow on MiLB First Pitch  https //stza.co/+vLxY-p

Shop  https //stza.co/+vLxY-1u

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Shuckers vs. Generals
END:VALARM
DTSTART:20180710T233500Z
DTEND:20180711T023500Z
UID:04an6e4eouDISy71wqJHo0-c@stanza.co
SUMMARY:Shuckers vs. Generals
DESCRIPTION:Shuckers vs. Generals\n\nFollow on MiLB First Pitch: https://stza.co/+vLxY-p\n\nShop: https://stza.co/+vLxY-1u\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144505Z
LAST-MODIFIED:20180213T144505Z
TRANSP:OPAQUE
END:VEVENT
* Shuckers vs. Generals
<2018-07-11 Wed>--<2018-07-10 Tue>
:PROPERTIES:
:ID:       h5LWTLM0QY2YkLSd80Xu8rVM@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Shuckers vs. Generals Shuckers vs. Generals

Follow on MiLB First Pitch  https //stza.co/+vc54-2H

Shop  https //stza.co/+vc54-V

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Shuckers vs. Generals
END:VALARM
DTSTART;VALUE=DATE:20180711
DTEND;VALUE=DATE:20180711
UID:h5LWTLM0QY2YkLSd80Xu8rVM@stanza.co
SUMMARY:Shuckers vs. Generals
DESCRIPTION:Shuckers vs. Generals\n\nFollow on MiLB First Pitch: https://stza.co/+vc54-2H\n\nShop: https://stza.co/+vc54-V\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144505Z
LAST-MODIFIED:20180213T144505Z
TRANSP:OPAQUE
END:VEVENT
* Shuckers @ Jumbo Shrimp
<2018-07-12 Thu 18:05-21:05>
:PROPERTIES:
:ID:       wxSsQPKe2-OkeO-94jarmih6@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Shuckers @ Jumbo Shrimp Shuckers @ Jumbo Shrimp

Follow on MiLB First Pitch  https //stza.co/+vchx-3Z

Shop  https //stza.co/+vchx-3r

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Shuckers @ Jumbo Shrimp
END:VALARM
DTSTART:20180712T230500Z
DTEND:20180713T020500Z
UID:wxSsQPKe2-OkeO-94jarmih6@stanza.co
SUMMARY:Shuckers @ Jumbo Shrimp
DESCRIPTION:Shuckers @ Jumbo Shrimp\n\nFollow on MiLB First Pitch: https://stza.co/+vchx-3Z\n\nShop: https://stza.co/+vchx-3r\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144505Z
LAST-MODIFIED:20180213T144505Z
TRANSP:OPAQUE
END:VEVENT
* Shuckers @ Jumbo Shrimp
<2018-07-13 Fri 18:05-21:05>
:PROPERTIES:
:ID:       wzXCf56Vq7wfGx7eMpjBGjXG@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Shuckers @ Jumbo Shrimp Shuckers @ Jumbo Shrimp

Follow on MiLB First Pitch  https //stza.co/+vchI-1a

Shop  https //stza.co/+vchI-1Y

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Shuckers @ Jumbo Shrimp
END:VALARM
DTSTART:20180713T230500Z
DTEND:20180714T020500Z
UID:wzXCf56Vq7wfGx7eMpjBGjXG@stanza.co
SUMMARY:Shuckers @ Jumbo Shrimp
DESCRIPTION:Shuckers @ Jumbo Shrimp\n\nFollow on MiLB First Pitch: https://stza.co/+vchI-1a\n\nShop: https://stza.co/+vchI-1Y\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144505Z
LAST-MODIFIED:20180213T144505Z
TRANSP:OPAQUE
END:VEVENT
* Shuckers @ Jumbo Shrimp
<2018-07-14 Sat 17:35-20:35>
:PROPERTIES:
:ID:       fhWQct1BJDdgDlySVAh3r4R9@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Shuckers @ Jumbo Shrimp Shuckers @ Jumbo Shrimp

Follow on MiLB First Pitch  https //stza.co/+vchU-I

Shop  https //stza.co/+vchU-1D

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Shuckers @ Jumbo Shrimp
END:VALARM
DTSTART:20180714T223500Z
DTEND:20180715T013500Z
UID:fhWQct1BJDdgDlySVAh3r4R9@stanza.co
SUMMARY:Shuckers @ Jumbo Shrimp
DESCRIPTION:Shuckers @ Jumbo Shrimp\n\nFollow on MiLB First Pitch: https://stza.co/+vchU-I\n\nShop: https://stza.co/+vchU-1D\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144505Z
LAST-MODIFIED:20180213T144505Z
TRANSP:OPAQUE
END:VEVENT
* Shuckers @ Jumbo Shrimp
<2018-07-15 Sun 14:05-17:05>
:PROPERTIES:
:ID:       pJURSXd-9dbKloZXuHLXt3GH@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Shuckers @ Jumbo Shrimp Shuckers @ Jumbo Shrimp

Follow on MiLB First Pitch  https //stza.co/+vci8-2o

Shop  https //stza.co/+vci8-n

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Shuckers @ Jumbo Shrimp
END:VALARM
DTSTART:20180715T190500Z
DTEND:20180715T220500Z
UID:pJURSXd-9dbKloZXuHLXt3GH@stanza.co
SUMMARY:Shuckers @ Jumbo Shrimp
DESCRIPTION:Shuckers @ Jumbo Shrimp\n\nFollow on MiLB First Pitch: https://stza.co/+vci8-2o\n\nShop: https://stza.co/+vci8-n\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144505Z
LAST-MODIFIED:20180213T144505Z
TRANSP:OPAQUE
END:VEVENT
* Shuckers @ Jumbo Shrimp
<2018-07-16 Mon 18:05-21:05>
:PROPERTIES:
:ID:       -vQHTjQvPTaJH1ZaOfW0p38e@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Shuckers @ Jumbo Shrimp Shuckers @ Jumbo Shrimp

Follow on MiLB First Pitch  https //stza.co/+vcie-z

Shop  https //stza.co/+vcie-1x

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Shuckers @ Jumbo Shrimp
END:VALARM
DTSTART:20180716T230500Z
DTEND:20180717T020500Z
UID:-vQHTjQvPTaJH1ZaOfW0p38e@stanza.co
SUMMARY:Shuckers @ Jumbo Shrimp
DESCRIPTION:Shuckers @ Jumbo Shrimp\n\nFollow on MiLB First Pitch: https://stza.co/+vcie-z\n\nShop: https://stza.co/+vcie-1x\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144505Z
LAST-MODIFIED:20180213T144505Z
TRANSP:OPAQUE
END:VEVENT
* Shuckers vs. Smokies
<2018-07-18 Wed 18:35-21:35>
:PROPERTIES:
:ID:       H9ycH6ETwmijQt2GwmUCepc0@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Shuckers vs. Smokies Shuckers vs. Smokies

Follow on MiLB First Pitch  https //stza.co/+vLxZ-1X

Shop  https //stza.co/+vLxZ-2j

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Shuckers vs. Smokies
END:VALARM
DTSTART:20180718T233500Z
DTEND:20180719T023500Z
UID:H9ycH6ETwmijQt2GwmUCepc0@stanza.co
SUMMARY:Shuckers vs. Smokies
DESCRIPTION:Shuckers vs. Smokies\n\nFollow on MiLB First Pitch: https://stza.co/+vLxZ-1X\n\nShop: https://stza.co/+vLxZ-2j\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144505Z
LAST-MODIFIED:20180213T144505Z
TRANSP:OPAQUE
END:VEVENT
* Shuckers vs. Smokies
<2018-07-19 Thu 18:35-21:35>
:PROPERTIES:
:ID:       4RsDAov2HoUFpUPgqwW_Nr3m@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Shuckers vs. Smokies Shuckers vs. Smokies

Follow on MiLB First Pitch  https //stza.co/+vLy0-1D

Shop  https //stza.co/+vLy0-3j

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Shuckers vs. Smokies
END:VALARM
DTSTART:20180719T233500Z
DTEND:20180720T023500Z
UID:4RsDAov2HoUFpUPgqwW_Nr3m@stanza.co
SUMMARY:Shuckers vs. Smokies
DESCRIPTION:Shuckers vs. Smokies\n\nFollow on MiLB First Pitch: https://stza.co/+vLy0-1D\n\nShop: https://stza.co/+vLy0-3j\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144505Z
LAST-MODIFIED:20180213T144505Z
TRANSP:OPAQUE
END:VEVENT
* Shuckers vs. Smokies
<2018-07-20 Fri 18:35-21:35>
:PROPERTIES:
:ID:       fy1506r0JdjFyIPr39urTSPb@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Shuckers vs. Smokies Shuckers vs. Smokies

Follow on MiLB First Pitch  https //stza.co/+vLy2-1e

Shop  https //stza.co/+vLy2-1i

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Shuckers vs. Smokies
END:VALARM
DTSTART:20180720T233500Z
DTEND:20180721T023500Z
UID:fy1506r0JdjFyIPr39urTSPb@stanza.co
SUMMARY:Shuckers vs. Smokies
DESCRIPTION:Shuckers vs. Smokies\n\nFollow on MiLB First Pitch: https://stza.co/+vLy2-1e\n\nShop: https://stza.co/+vLy2-1i\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144505Z
LAST-MODIFIED:20180213T144505Z
TRANSP:OPAQUE
END:VEVENT
* Shuckers vs. Smokies
<2018-07-21 Sat 18:35-21:35>
:PROPERTIES:
:ID:       279_gttwSP7cWhK9Cf2swCqW@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Shuckers vs. Smokies Shuckers vs. Smokies

Follow on MiLB First Pitch  https //stza.co/+vLy3-2F

Shop  https //stza.co/+vLy3-A

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Shuckers vs. Smokies
END:VALARM
DTSTART:20180721T233500Z
DTEND:20180722T023500Z
UID:279_gttwSP7cWhK9Cf2swCqW@stanza.co
SUMMARY:Shuckers vs. Smokies
DESCRIPTION:Shuckers vs. Smokies\n\nFollow on MiLB First Pitch: https://stza.co/+vLy3-2F\n\nShop: https://stza.co/+vLy3-A\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144505Z
LAST-MODIFIED:20180213T144505Z
TRANSP:OPAQUE
END:VEVENT
* Shuckers vs. Smokies
<2018-07-22 Sun 16:05-19:05>
:PROPERTIES:
:ID:       P9sTT2BSrc-7kwAHrKc-yzV8@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Shuckers vs. Smokies Shuckers vs. Smokies

Follow on MiLB First Pitch  https //stza.co/+vLy5-E

Shop  https //stza.co/+vLy5-G

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Shuckers vs. Smokies
END:VALARM
DTSTART:20180722T210500Z
DTEND:20180723T000500Z
UID:P9sTT2BSrc-7kwAHrKc-yzV8@stanza.co
SUMMARY:Shuckers vs. Smokies
DESCRIPTION:Shuckers vs. Smokies\n\nFollow on MiLB First Pitch: https://stza.co/+vLy5-E\n\nShop: https://stza.co/+vLy5-G\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144505Z
LAST-MODIFIED:20180213T144505Z
TRANSP:OPAQUE
END:VEVENT
* Shuckers @ Generals
<2018-07-23 Mon 18:05-21:05>
:PROPERTIES:
:ID:       X1ddB7iFLQJ-QwxYqtqLELYB@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Shuckers @ Generals Shuckers @ Generals

Follow on MiLB First Pitch  https //stza.co/+wCM8-3b

Shop  https //stza.co/+wCM8-34

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Shuckers @ Generals
END:VALARM
DTSTART:20180723T230500Z
DTEND:20180724T020500Z
UID:X1ddB7iFLQJ-QwxYqtqLELYB@stanza.co
SUMMARY:Shuckers @ Generals
DESCRIPTION:Shuckers @ Generals\n\nFollow on MiLB First Pitch: https://stza.co/+wCM8-3b\n\nShop: https://stza.co/+wCM8-34\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144505Z
LAST-MODIFIED:20180213T144505Z
TRANSP:OPAQUE
END:VEVENT
* Shuckers @ Generals
<2018-07-24 Tue 18:05-21:05>
:PROPERTIES:
:ID:       zFrcJxywqaWqTu0fDgKVn3sj@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Shuckers @ Generals Shuckers @ Generals

Follow on MiLB First Pitch  https //stza.co/+wCM9-1i

Shop  https //stza.co/+wCM9-2u

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Shuckers @ Generals
END:VALARM
DTSTART:20180724T230500Z
DTEND:20180725T020500Z
UID:zFrcJxywqaWqTu0fDgKVn3sj@stanza.co
SUMMARY:Shuckers @ Generals
DESCRIPTION:Shuckers @ Generals\n\nFollow on MiLB First Pitch: https://stza.co/+wCM9-1i\n\nShop: https://stza.co/+wCM9-2u\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144505Z
LAST-MODIFIED:20180213T144505Z
TRANSP:OPAQUE
END:VEVENT
* Shuckers @ Generals
<2018-07-25 Wed 18:05-21:05>
:PROPERTIES:
:ID:       w4vayd9pWLfC66JlBvkqA3NR@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Shuckers @ Generals Shuckers @ Generals

Follow on MiLB First Pitch  https //stza.co/+wCMa-12

Shop  https //stza.co/+wCMa-1z

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Shuckers @ Generals
END:VALARM
DTSTART:20180725T230500Z
DTEND:20180726T020500Z
UID:w4vayd9pWLfC66JlBvkqA3NR@stanza.co
SUMMARY:Shuckers @ Generals
DESCRIPTION:Shuckers @ Generals\n\nFollow on MiLB First Pitch: https://stza.co/+wCMa-12\n\nShop: https://stza.co/+wCMa-1z\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144505Z
LAST-MODIFIED:20180213T144505Z
TRANSP:OPAQUE
END:VEVENT
* Shuckers @ Generals
<2018-07-26 Thu 18:05-21:05>
:PROPERTIES:
:ID:       UY7GMdFdaGYOE9OqIY7Zqqar@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Shuckers @ Generals Shuckers @ Generals

Follow on MiLB First Pitch  https //stza.co/+wCMb-2$

Shop  https //stza.co/+wCMb-4

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Shuckers @ Generals
END:VALARM
DTSTART:20180726T230500Z
DTEND:20180727T020500Z
UID:UY7GMdFdaGYOE9OqIY7Zqqar@stanza.co
SUMMARY:Shuckers @ Generals
DESCRIPTION:Shuckers @ Generals\n\nFollow on MiLB First Pitch: https://stza.co/+wCMb-2$\n\nShop: https://stza.co/+wCMb-4\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144505Z
LAST-MODIFIED:20180213T144505Z
TRANSP:OPAQUE
END:VEVENT
* Shuckers @ Generals
<2018-07-27 Fri 18:05-21:05>
:PROPERTIES:
:ID:       kf89m_SL8XBm0hgXABvBYAse@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Shuckers @ Generals Shuckers @ Generals

Follow on MiLB First Pitch  https //stza.co/+wCMc-3A

Shop  https //stza.co/+wCMc-1n

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Shuckers @ Generals
END:VALARM
DTSTART:20180727T230500Z
DTEND:20180728T020500Z
UID:kf89m_SL8XBm0hgXABvBYAse@stanza.co
SUMMARY:Shuckers @ Generals
DESCRIPTION:Shuckers @ Generals\n\nFollow on MiLB First Pitch: https://stza.co/+wCMc-3A\n\nShop: https://stza.co/+wCMc-1n\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144505Z
LAST-MODIFIED:20180213T144505Z
TRANSP:OPAQUE
END:VEVENT
* Shuckers @ Blue Wahoos
<2018-07-28 Sat 18:05-21:05>
:PROPERTIES:
:ID:       L1wK5ATPTKGe_TrmNch8vo7J@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Shuckers @ Blue Wahoos Shuckers @ Blue Wahoos

Follow on MiLB First Pitch  https //stza.co/+wx6s-2M

Shop  https //stza.co/+wx6s-8

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Shuckers @ Blue Wahoos
END:VALARM
DTSTART:20180728T230500Z
DTEND:20180729T020500Z
UID:L1wK5ATPTKGe_TrmNch8vo7J@stanza.co
SUMMARY:Shuckers @ Blue Wahoos
DESCRIPTION:Shuckers @ Blue Wahoos\n\nFollow on MiLB First Pitch: https://stza.co/+wx6s-2M\n\nShop: https://stza.co/+wx6s-8\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144505Z
LAST-MODIFIED:20180213T144505Z
TRANSP:OPAQUE
END:VEVENT
* Shuckers @ Blue Wahoos
<2018-07-29 Sun 17:05-20:05>
:PROPERTIES:
:ID:       R3YuYx7Q7llZG0P_YBKybuca@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Shuckers @ Blue Wahoos Shuckers @ Blue Wahoos

Follow on MiLB First Pitch  https //stza.co/+wx6t-M

Shop  https //stza.co/+wx6t-5

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Shuckers @ Blue Wahoos
END:VALARM
DTSTART:20180729T220500Z
DTEND:20180730T010500Z
UID:R3YuYx7Q7llZG0P_YBKybuca@stanza.co
SUMMARY:Shuckers @ Blue Wahoos
DESCRIPTION:Shuckers @ Blue Wahoos\n\nFollow on MiLB First Pitch: https://stza.co/+wx6t-M\n\nShop: https://stza.co/+wx6t-5\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144505Z
LAST-MODIFIED:20180213T144505Z
TRANSP:OPAQUE
END:VEVENT
* Shuckers @ Blue Wahoos
<2018-07-30 Mon 18:35-21:35>
:PROPERTIES:
:ID:       C6FxGI1AxMfDN6IiW15ajnpA@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Shuckers @ Blue Wahoos Shuckers @ Blue Wahoos

Follow on MiLB First Pitch  https //stza.co/+wx6u-2j

Shop  https //stza.co/+wx6u-r

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Shuckers @ Blue Wahoos
END:VALARM
DTSTART:20180730T233500Z
DTEND:20180731T023500Z
UID:C6FxGI1AxMfDN6IiW15ajnpA@stanza.co
SUMMARY:Shuckers @ Blue Wahoos
DESCRIPTION:Shuckers @ Blue Wahoos\n\nFollow on MiLB First Pitch: https://stza.co/+wx6u-2j\n\nShop: https://stza.co/+wx6u-r\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144505Z
LAST-MODIFIED:20180213T144505Z
TRANSP:OPAQUE
END:VEVENT
* Shuckers @ Blue Wahoos
<2018-07-31 Tue 18:35-21:35>
:PROPERTIES:
:ID:       FfdfAU3BarvWTuWRL2iIwfFA@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Shuckers @ Blue Wahoos Shuckers @ Blue Wahoos

Follow on MiLB First Pitch  https //stza.co/+wx6v-27

Shop  https //stza.co/+wx6v-3d

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Shuckers @ Blue Wahoos
END:VALARM
DTSTART:20180731T233500Z
DTEND:20180801T023500Z
UID:FfdfAU3BarvWTuWRL2iIwfFA@stanza.co
SUMMARY:Shuckers @ Blue Wahoos
DESCRIPTION:Shuckers @ Blue Wahoos\n\nFollow on MiLB First Pitch: https://stza.co/+wx6v-27\n\nShop: https://stza.co/+wx6v-3d\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144505Z
LAST-MODIFIED:20180213T144505Z
TRANSP:OPAQUE
END:VEVENT
* Shuckers @ Blue Wahoos
<2018-08-01 Wed 18:35-21:35>
:PROPERTIES:
:ID:       HfGn_7E4yb_4GZxg-3Iyka97@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Shuckers @ Blue Wahoos Shuckers @ Blue Wahoos

Follow on MiLB First Pitch  https //stza.co/+wx6w-30

Shop  https //stza.co/+wx6w-3F

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Shuckers @ Blue Wahoos
END:VALARM
DTSTART:20180801T233500Z
DTEND:20180802T023500Z
UID:HfGn_7E4yb_4GZxg-3Iyka97@stanza.co
SUMMARY:Shuckers @ Blue Wahoos
DESCRIPTION:Shuckers @ Blue Wahoos\n\nFollow on MiLB First Pitch: https://stza.co/+wx6w-30\n\nShop: https://stza.co/+wx6w-3F\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144505Z
LAST-MODIFIED:20180213T144505Z
TRANSP:OPAQUE
END:VEVENT
* Shuckers vs. Jumbo Shrimp
<2018-08-02 Thu 18:35-21:35>
:PROPERTIES:
:ID:       H69N9Nns-FvvY9HL4zV9pJem@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Shuckers vs. Jumbo Shrimp Shuckers vs. Jumbo Shrimp

Follow on MiLB First Pitch  https //stza.co/+vLy7-3C

Shop  https //stza.co/+vLy7-33

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Shuckers vs. Jumbo Shrimp
END:VALARM
DTSTART:20180802T233500Z
DTEND:20180803T023500Z
UID:H69N9Nns-FvvY9HL4zV9pJem@stanza.co
SUMMARY:Shuckers vs. Jumbo Shrimp
DESCRIPTION:Shuckers vs. Jumbo Shrimp\n\nFollow on MiLB First Pitch: https://stza.co/+vLy7-3C\n\nShop: https://stza.co/+vLy7-33\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144505Z
LAST-MODIFIED:20180213T144505Z
TRANSP:OPAQUE
END:VEVENT
* Shuckers vs. Jumbo Shrimp
<2018-08-03 Fri 18:35-21:35>
:PROPERTIES:
:ID:       eE5du6pNfQv7NhHxMs3zdsIS@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Shuckers vs. Jumbo Shrimp Shuckers vs. Jumbo Shrimp

Follow on MiLB First Pitch  https //stza.co/+vLy9-2Y

Shop  https //stza.co/+vLy9-1R

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Shuckers vs. Jumbo Shrimp
END:VALARM
DTSTART:20180803T233500Z
DTEND:20180804T023500Z
UID:eE5du6pNfQv7NhHxMs3zdsIS@stanza.co
SUMMARY:Shuckers vs. Jumbo Shrimp
DESCRIPTION:Shuckers vs. Jumbo Shrimp\n\nFollow on MiLB First Pitch: https://stza.co/+vLy9-2Y\n\nShop: https://stza.co/+vLy9-1R\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144505Z
LAST-MODIFIED:20180213T144505Z
TRANSP:OPAQUE
END:VEVENT
* Shuckers vs. Jumbo Shrimp
<2018-08-04 Sat 18:35-21:35>
:PROPERTIES:
:ID:       LvOHjgKfh8ZLCK7plBVWHik0@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Shuckers vs. Jumbo Shrimp Shuckers vs. Jumbo Shrimp

Follow on MiLB First Pitch  https //stza.co/+vLyc-17

Shop  https //stza.co/+vLyc-3F

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Shuckers vs. Jumbo Shrimp
END:VALARM
DTSTART:20180804T233500Z
DTEND:20180805T023500Z
UID:LvOHjgKfh8ZLCK7plBVWHik0@stanza.co
SUMMARY:Shuckers vs. Jumbo Shrimp
DESCRIPTION:Shuckers vs. Jumbo Shrimp\n\nFollow on MiLB First Pitch: https://stza.co/+vLyc-17\n\nShop: https://stza.co/+vLyc-3F\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144505Z
LAST-MODIFIED:20180213T144505Z
TRANSP:OPAQUE
END:VEVENT
* Shuckers vs. Jumbo Shrimp
<2018-08-05 Sun 16:05-19:05>
:PROPERTIES:
:ID:       84BJR0u-QjYKXshcKcBTOHt6@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Shuckers vs. Jumbo Shrimp Shuckers vs. Jumbo Shrimp

Follow on MiLB First Pitch  https //stza.co/+vLye-2i

Shop  https //stza.co/+vLye-3f

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Shuckers vs. Jumbo Shrimp
END:VALARM
DTSTART:20180805T210500Z
DTEND:20180806T000500Z
UID:84BJR0u-QjYKXshcKcBTOHt6@stanza.co
SUMMARY:Shuckers vs. Jumbo Shrimp
DESCRIPTION:Shuckers vs. Jumbo Shrimp\n\nFollow on MiLB First Pitch: https://stza.co/+vLye-2i\n\nShop: https://stza.co/+vLye-3f\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144505Z
LAST-MODIFIED:20180213T144505Z
TRANSP:OPAQUE
END:VEVENT
* Shuckers vs. Jumbo Shrimp
<2018-08-06 Mon 18:35-21:35>
:PROPERTIES:
:ID:       yo6VyB4ZSfpIVeqjChhFZz4F@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Shuckers vs. Jumbo Shrimp Shuckers vs. Jumbo Shrimp

Follow on MiLB First Pitch  https //stza.co/+vLyg-1K

Shop  https //stza.co/+vLyg-2U

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Shuckers vs. Jumbo Shrimp
END:VALARM
DTSTART:20180806T233500Z
DTEND:20180807T023500Z
UID:yo6VyB4ZSfpIVeqjChhFZz4F@stanza.co
SUMMARY:Shuckers vs. Jumbo Shrimp
DESCRIPTION:Shuckers vs. Jumbo Shrimp\n\nFollow on MiLB First Pitch: https://stza.co/+vLyg-1K\n\nShop: https://stza.co/+vLyg-2U\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144505Z
LAST-MODIFIED:20180213T144505Z
TRANSP:OPAQUE
END:VEVENT
* Shuckers @ Smokies
<2018-08-08 Wed 18:00-21:00>
:PROPERTIES:
:ID:       R4u94h1OcAWDHHbt82rqYXiZ@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Shuckers @ Smokies Shuckers @ Smokies

Follow on MiLB First Pitch  https //stza.co/+xVSI-2J

Shop  https //stza.co/+xVSI-3a

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Shuckers @ Smokies
END:VALARM
DTSTART:20180808T230000Z
DTEND:20180809T020000Z
UID:R4u94h1OcAWDHHbt82rqYXiZ@stanza.co
SUMMARY:Shuckers @ Smokies
DESCRIPTION:Shuckers @ Smokies\n\nFollow on MiLB First Pitch: https://stza.co/+xVSI-2J\n\nShop: https://stza.co/+xVSI-3a\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144505Z
LAST-MODIFIED:20180213T144505Z
TRANSP:OPAQUE
END:VEVENT
* Shuckers @ Smokies
<2018-08-09 Thu 18:00-21:00>
:PROPERTIES:
:ID:       Sc6Wzl7-lcUmPPMLDWN41yNy@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Shuckers @ Smokies Shuckers @ Smokies

Follow on MiLB First Pitch  https //stza.co/+xVSJ-39

Shop  https //stza.co/+xVSJ-3W

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Shuckers @ Smokies
END:VALARM
DTSTART:20180809T230000Z
DTEND:20180810T020000Z
UID:Sc6Wzl7-lcUmPPMLDWN41yNy@stanza.co
SUMMARY:Shuckers @ Smokies
DESCRIPTION:Shuckers @ Smokies\n\nFollow on MiLB First Pitch: https://stza.co/+xVSJ-39\n\nShop: https://stza.co/+xVSJ-3W\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144505Z
LAST-MODIFIED:20180213T144505Z
TRANSP:OPAQUE
END:VEVENT
* Shuckers @ Smokies
<2018-08-10 Fri 18:00-21:00>
:PROPERTIES:
:ID:       gcm7wJoZQWRVHR3GQP1gZCCk@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Shuckers @ Smokies Shuckers @ Smokies

Follow on MiLB First Pitch  https //stza.co/+xVSK-21

Shop  https //stza.co/+xVSK-j

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Shuckers @ Smokies
END:VALARM
DTSTART:20180810T230000Z
DTEND:20180811T020000Z
UID:gcm7wJoZQWRVHR3GQP1gZCCk@stanza.co
SUMMARY:Shuckers @ Smokies
DESCRIPTION:Shuckers @ Smokies\n\nFollow on MiLB First Pitch: https://stza.co/+xVSK-21\n\nShop: https://stza.co/+xVSK-j\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144505Z
LAST-MODIFIED:20180213T144505Z
TRANSP:OPAQUE
END:VEVENT
* Shuckers @ Smokies
<2018-08-11 Sat 18:00-21:00>
:PROPERTIES:
:ID:       U7siV27_3Dpv_ILoreUbfMTV@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Shuckers @ Smokies Shuckers @ Smokies

Follow on MiLB First Pitch  https //stza.co/+xVSL-2q

Shop  https //stza.co/+xVSL-13

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Shuckers @ Smokies
END:VALARM
DTSTART:20180811T230000Z
DTEND:20180812T020000Z
UID:U7siV27_3Dpv_ILoreUbfMTV@stanza.co
SUMMARY:Shuckers @ Smokies
DESCRIPTION:Shuckers @ Smokies\n\nFollow on MiLB First Pitch: https://stza.co/+xVSL-2q\n\nShop: https://stza.co/+xVSL-13\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144505Z
LAST-MODIFIED:20180213T144505Z
TRANSP:OPAQUE
END:VEVENT
* Shuckers @ Smokies
<2018-08-12 Sun 16:30-19:30>
:PROPERTIES:
:ID:       l4jXDoLLAKD9u4n-aZ3XXgHs@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Shuckers @ Smokies Shuckers @ Smokies

Follow on MiLB First Pitch  https //stza.co/+xVSM-c

Shop  https //stza.co/+xVSM-3r

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Shuckers @ Smokies
END:VALARM
DTSTART:20180812T213000Z
DTEND:20180813T003000Z
UID:l4jXDoLLAKD9u4n-aZ3XXgHs@stanza.co
SUMMARY:Shuckers @ Smokies
DESCRIPTION:Shuckers @ Smokies\n\nFollow on MiLB First Pitch: https://stza.co/+xVSM-c\n\nShop: https://stza.co/+xVSM-3r\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144505Z
LAST-MODIFIED:20180213T144505Z
TRANSP:OPAQUE
END:VEVENT
* Shuckers vs. BayBears
<2018-08-14 Tue 18:35-21:35>
:PROPERTIES:
:ID:       3YqUSMYOitCUyd0d9RC3VGh6@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Shuckers vs. BayBears Shuckers vs. BayBears

Follow on MiLB First Pitch  https //stza.co/+vLyh-37

Shop  https //stza.co/+vLyh-3c

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Shuckers vs. BayBears
END:VALARM
DTSTART:20180814T233500Z
DTEND:20180815T023500Z
UID:3YqUSMYOitCUyd0d9RC3VGh6@stanza.co
SUMMARY:Shuckers vs. BayBears
DESCRIPTION:Shuckers vs. BayBears\n\nFollow on MiLB First Pitch: https://stza.co/+vLyh-37\n\nShop: https://stza.co/+vLyh-3c\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144505Z
LAST-MODIFIED:20180213T144505Z
TRANSP:OPAQUE
END:VEVENT
* Shuckers vs. BayBears
<2018-08-15 Wed 18:35-21:35>
:PROPERTIES:
:ID:       C_xZw8TO60J8fwI_-Nx9DoCZ@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Shuckers vs. BayBears Shuckers vs. BayBears

Follow on MiLB First Pitch  https //stza.co/+vLyk-h

Shop  https //stza.co/+vLyk-r

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Shuckers vs. BayBears
END:VALARM
DTSTART:20180815T233500Z
DTEND:20180816T023500Z
UID:C_xZw8TO60J8fwI_-Nx9DoCZ@stanza.co
SUMMARY:Shuckers vs. BayBears
DESCRIPTION:Shuckers vs. BayBears\n\nFollow on MiLB First Pitch: https://stza.co/+vLyk-h\n\nShop: https://stza.co/+vLyk-r\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144505Z
LAST-MODIFIED:20180213T144505Z
TRANSP:OPAQUE
END:VEVENT
* Shuckers vs. BayBears
<2018-08-16 Thu 18:35-21:35>
:PROPERTIES:
:ID:       sgfymAgUUe24c8_neLFgmXDD@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Shuckers vs. BayBears Shuckers vs. BayBears

Follow on MiLB First Pitch  https //stza.co/+vLym-3b

Shop  https //stza.co/+vLym-18

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Shuckers vs. BayBears
END:VALARM
DTSTART:20180816T233500Z
DTEND:20180817T023500Z
UID:sgfymAgUUe24c8_neLFgmXDD@stanza.co
SUMMARY:Shuckers vs. BayBears
DESCRIPTION:Shuckers vs. BayBears\n\nFollow on MiLB First Pitch: https://stza.co/+vLym-3b\n\nShop: https://stza.co/+vLym-18\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144505Z
LAST-MODIFIED:20180213T144505Z
TRANSP:OPAQUE
END:VEVENT
* Shuckers vs. BayBears
<2018-08-17 Fri 18:35-21:35>
:PROPERTIES:
:ID:       0fs-9XvP_Xtet-Rt2-NNy90g@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Shuckers vs. BayBears Shuckers vs. BayBears

Follow on MiLB First Pitch  https //stza.co/+vLyo-3d

Shop  https //stza.co/+vLyo-a

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Shuckers vs. BayBears
END:VALARM
DTSTART:20180817T233500Z
DTEND:20180818T023500Z
UID:0fs-9XvP_Xtet-Rt2-NNy90g@stanza.co
SUMMARY:Shuckers vs. BayBears
DESCRIPTION:Shuckers vs. BayBears\n\nFollow on MiLB First Pitch: https://stza.co/+vLyo-3d\n\nShop: https://stza.co/+vLyo-a\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144505Z
LAST-MODIFIED:20180213T144505Z
TRANSP:OPAQUE
END:VEVENT
* Shuckers vs. BayBears
<2018-08-18 Sat 18:35-21:35>
:PROPERTIES:
:ID:       YyCn-l89Dh7XXfK9otP2Defl@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Shuckers vs. BayBears Shuckers vs. BayBears

Follow on MiLB First Pitch  https //stza.co/+vLyq-I

Shop  https //stza.co/+vLyq-2o

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Shuckers vs. BayBears
END:VALARM
DTSTART:20180818T233500Z
DTEND:20180819T023500Z
UID:YyCn-l89Dh7XXfK9otP2Defl@stanza.co
SUMMARY:Shuckers vs. BayBears
DESCRIPTION:Shuckers vs. BayBears\n\nFollow on MiLB First Pitch: https://stza.co/+vLyq-I\n\nShop: https://stza.co/+vLyq-2o\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144505Z
LAST-MODIFIED:20180213T144505Z
TRANSP:OPAQUE
END:VEVENT
* Shuckers vs. Blue Wahoos
<2018-08-19 Sun 16:05-19:05>
:PROPERTIES:
:ID:       hyydDziBWZ4pnMW8JzhLjc2d@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Shuckers vs. Blue Wahoos Shuckers vs. Blue Wahoos

Follow on MiLB First Pitch  https //stza.co/+vLys-33

Shop  https //stza.co/+vLys-H

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Shuckers vs. Blue Wahoos
END:VALARM
DTSTART:20180819T210500Z
DTEND:20180820T000500Z
UID:hyydDziBWZ4pnMW8JzhLjc2d@stanza.co
SUMMARY:Shuckers vs. Blue Wahoos
DESCRIPTION:Shuckers vs. Blue Wahoos\n\nFollow on MiLB First Pitch: https://stza.co/+vLys-33\n\nShop: https://stza.co/+vLys-H\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144505Z
LAST-MODIFIED:20180213T144505Z
TRANSP:OPAQUE
END:VEVENT
* Shuckers vs. Blue Wahoos
<2018-08-20 Mon 18:35-21:35>
:PROPERTIES:
:ID:       F3wOnxbbylxMEtw2ZwzMTtOk@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Shuckers vs. Blue Wahoos Shuckers vs. Blue Wahoos

Follow on MiLB First Pitch  https //stza.co/+vLyt-1C

Shop  https //stza.co/+vLyt-20

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Shuckers vs. Blue Wahoos
END:VALARM
DTSTART:20180820T233500Z
DTEND:20180821T023500Z
UID:F3wOnxbbylxMEtw2ZwzMTtOk@stanza.co
SUMMARY:Shuckers vs. Blue Wahoos
DESCRIPTION:Shuckers vs. Blue Wahoos\n\nFollow on MiLB First Pitch: https://stza.co/+vLyt-1C\n\nShop: https://stza.co/+vLyt-20\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144505Z
LAST-MODIFIED:20180213T144505Z
TRANSP:OPAQUE
END:VEVENT
* Shuckers vs. Blue Wahoos
<2018-08-21 Tue 10:35-13:35>
:PROPERTIES:
:ID:       VGoVqsy6Ep56sdi10xi16-sB@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Shuckers vs. Blue Wahoos Shuckers vs. Blue Wahoos

Follow on MiLB First Pitch  https //stza.co/+vLyw-1p

Shop  https //stza.co/+vLyw-3y

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Shuckers vs. Blue Wahoos
END:VALARM
DTSTART:20180821T153500Z
DTEND:20180821T183500Z
UID:VGoVqsy6Ep56sdi10xi16-sB@stanza.co
SUMMARY:Shuckers vs. Blue Wahoos
DESCRIPTION:Shuckers vs. Blue Wahoos\n\nFollow on MiLB First Pitch: https://stza.co/+vLyw-1p\n\nShop: https://stza.co/+vLyw-3y\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144505Z
LAST-MODIFIED:20180213T144505Z
TRANSP:OPAQUE
END:VEVENT
* Shuckers vs. Blue Wahoos
<2018-08-22 Wed 18:35-21:35>
:PROPERTIES:
:ID:       Vv6RIw2Ub9K8pRyUteI7xQBY@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Shuckers vs. Blue Wahoos Shuckers vs. Blue Wahoos

Follow on MiLB First Pitch  https //stza.co/+vLyy-18

Shop  https //stza.co/+vLyy-y

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Shuckers vs. Blue Wahoos
END:VALARM
DTSTART:20180822T233500Z
DTEND:20180823T023500Z
UID:Vv6RIw2Ub9K8pRyUteI7xQBY@stanza.co
SUMMARY:Shuckers vs. Blue Wahoos
DESCRIPTION:Shuckers vs. Blue Wahoos\n\nFollow on MiLB First Pitch: https://stza.co/+vLyy-18\n\nShop: https://stza.co/+vLyy-y\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144505Z
LAST-MODIFIED:20180213T144505Z
TRANSP:OPAQUE
END:VEVENT
* Shuckers vs. Blue Wahoos
<2018-08-23 Thu 18:35-21:35>
:PROPERTIES:
:ID:       plRCQ78H9uTWlA2Y-3vqV0_F@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Shuckers vs. Blue Wahoos Shuckers vs. Blue Wahoos

Follow on MiLB First Pitch  https //stza.co/+vLyz-2q

Shop  https //stza.co/+vLyz-D

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Shuckers vs. Blue Wahoos
END:VALARM
DTSTART:20180823T233500Z
DTEND:20180824T023500Z
UID:plRCQ78H9uTWlA2Y-3vqV0_F@stanza.co
SUMMARY:Shuckers vs. Blue Wahoos
DESCRIPTION:Shuckers vs. Blue Wahoos\n\nFollow on MiLB First Pitch: https://stza.co/+vLyz-2q\n\nShop: https://stza.co/+vLyz-D\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144505Z
LAST-MODIFIED:20180213T144505Z
TRANSP:OPAQUE
END:VEVENT
* Shuckers @ Braves
<2018-08-24 Fri 19:00-22:00>
:PROPERTIES:
:ID:       rUXlFRqQZsuoIGnhUexU8HL3@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Shuckers @ Braves Shuckers @ Braves

Follow on MiLB First Pitch  https //stza.co/+vcj6-2t

Shop  https //stza.co/+vcj6-3j

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Shuckers @ Braves
END:VALARM
DTSTART:20180825T000000Z
DTEND:20180825T030000Z
UID:rUXlFRqQZsuoIGnhUexU8HL3@stanza.co
SUMMARY:Shuckers @ Braves
DESCRIPTION:Shuckers @ Braves\n\nFollow on MiLB First Pitch: https://stza.co/+vcj6-2t\n\nShop: https://stza.co/+vcj6-3j\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144505Z
LAST-MODIFIED:20180213T144505Z
TRANSP:OPAQUE
END:VEVENT
* Shuckers @ Braves
<2018-08-25 Sat 18:00-21:00>
:PROPERTIES:
:ID:       D8Iu-awPxKzLsnXaY7BHpd0Y@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Shuckers @ Braves Shuckers @ Braves

Follow on MiLB First Pitch  https //stza.co/+vcjj-3w

Shop  https //stza.co/+vcjj-3N

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Shuckers @ Braves
END:VALARM
DTSTART:20180825T230000Z
DTEND:20180826T020000Z
UID:D8Iu-awPxKzLsnXaY7BHpd0Y@stanza.co
SUMMARY:Shuckers @ Braves
DESCRIPTION:Shuckers @ Braves\n\nFollow on MiLB First Pitch: https://stza.co/+vcjj-3w\n\nShop: https://stza.co/+vcjj-3N\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144505Z
LAST-MODIFIED:20180213T144505Z
TRANSP:OPAQUE
END:VEVENT
* Shuckers @ Braves
<2018-08-26 Sun 17:00-20:00>
:PROPERTIES:
:ID:       CEE0HJLcg1oZ1LiSNMvdLl-E@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Shuckers @ Braves Shuckers @ Braves

Follow on MiLB First Pitch  https //stza.co/+vcjr-$

Shop  https //stza.co/+vcjr-1N

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Shuckers @ Braves
END:VALARM
DTSTART:20180826T220000Z
DTEND:20180827T010000Z
UID:CEE0HJLcg1oZ1LiSNMvdLl-E@stanza.co
SUMMARY:Shuckers @ Braves
DESCRIPTION:Shuckers @ Braves\n\nFollow on MiLB First Pitch: https://stza.co/+vcjr-$\n\nShop: https://stza.co/+vcjr-1N\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144505Z
LAST-MODIFIED:20180213T144505Z
TRANSP:OPAQUE
END:VEVENT
* Shuckers @ Braves
<2018-08-27 Mon 19:00-22:00>
:PROPERTIES:
:ID:       qERtn9EXO8Cf9FBGAIMwyhOA@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Shuckers @ Braves Shuckers @ Braves

Follow on MiLB First Pitch  https //stza.co/+vcjE-c

Shop  https //stza.co/+vcjE-1P

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Shuckers @ Braves
END:VALARM
DTSTART:20180828T000000Z
DTEND:20180828T030000Z
UID:qERtn9EXO8Cf9FBGAIMwyhOA@stanza.co
SUMMARY:Shuckers @ Braves
DESCRIPTION:Shuckers @ Braves\n\nFollow on MiLB First Pitch: https://stza.co/+vcjE-c\n\nShop: https://stza.co/+vcjE-1P\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144505Z
LAST-MODIFIED:20180213T144505Z
TRANSP:OPAQUE
END:VEVENT
* Shuckers @ Braves
<2018-08-28 Tue 12:00-15:00>
:PROPERTIES:
:ID:       -crN5ONMcYleyg9TIdAs12CZ@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Shuckers @ Braves Shuckers @ Braves

Follow on MiLB First Pitch  https //stza.co/+xM5S-10

Shop  https //stza.co/+xM5S-29

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Shuckers @ Braves
END:VALARM
DTSTART:20180828T170000Z
DTEND:20180828T200000Z
UID:-crN5ONMcYleyg9TIdAs12CZ@stanza.co
SUMMARY:Shuckers @ Braves
DESCRIPTION:Shuckers @ Braves\n\nFollow on MiLB First Pitch: https://stza.co/+xM5S-10\n\nShop: https://stza.co/+xM5S-29\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144505Z
LAST-MODIFIED:20180213T144505Z
TRANSP:OPAQUE
END:VEVENT
* Shuckers vs. Barons
<2018-08-30 Thu 18:35-21:35>
:PROPERTIES:
:ID:       32FackI8fw3xlCLwrXmlLFL6@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Shuckers vs. Barons Shuckers vs. Barons

Follow on MiLB First Pitch  https //stza.co/+vLyC-1A

Shop  https //stza.co/+vLyC-2C

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Shuckers vs. Barons
END:VALARM
DTSTART:20180830T233500Z
DTEND:20180831T023500Z
UID:32FackI8fw3xlCLwrXmlLFL6@stanza.co
SUMMARY:Shuckers vs. Barons
DESCRIPTION:Shuckers vs. Barons\n\nFollow on MiLB First Pitch: https://stza.co/+vLyC-1A\n\nShop: https://stza.co/+vLyC-2C\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144505Z
LAST-MODIFIED:20180213T144505Z
TRANSP:OPAQUE
END:VEVENT
* Shuckers vs. Barons
<2018-08-31 Fri 18:35-21:35>
:PROPERTIES:
:ID:       tsfuxUQbOgbDiKdLroJVp-k_@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Shuckers vs. Barons Shuckers vs. Barons

Follow on MiLB First Pitch  https //stza.co/+vLyE-1p

Shop  https //stza.co/+vLyE-2o

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Shuckers vs. Barons
END:VALARM
DTSTART:20180831T233500Z
DTEND:20180901T023500Z
UID:tsfuxUQbOgbDiKdLroJVp-k_@stanza.co
SUMMARY:Shuckers vs. Barons
DESCRIPTION:Shuckers vs. Barons\n\nFollow on MiLB First Pitch: https://stza.co/+vLyE-1p\n\nShop: https://stza.co/+vLyE-2o\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144505Z
LAST-MODIFIED:20180213T144505Z
TRANSP:OPAQUE
END:VEVENT
* Shuckers vs. Barons
<2018-09-01 Sat 18:35-21:35>
:PROPERTIES:
:ID:       MVOGqtRUuObWNBGx5ECQ5I8p@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Shuckers vs. Barons Shuckers vs. Barons

Follow on MiLB First Pitch  https //stza.co/+vLyF-22

Shop  https //stza.co/+vLyF-3E

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Shuckers vs. Barons
END:VALARM
DTSTART:20180901T233500Z
DTEND:20180902T023500Z
UID:MVOGqtRUuObWNBGx5ECQ5I8p@stanza.co
SUMMARY:Shuckers vs. Barons
DESCRIPTION:Shuckers vs. Barons\n\nFollow on MiLB First Pitch: https://stza.co/+vLyF-22\n\nShop: https://stza.co/+vLyF-3E\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144505Z
LAST-MODIFIED:20180213T144505Z
TRANSP:OPAQUE
END:VEVENT
* Shuckers vs. Barons
<2018-09-02 Sun 16:05-19:05>
:PROPERTIES:
:ID:       9_67UdSLClQB4rk8zLfygzsL@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Shuckers vs. Barons Shuckers vs. Barons

Follow on MiLB First Pitch  https //stza.co/+vLyI-28

Shop  https //stza.co/+vLyI-3h

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Shuckers vs. Barons
END:VALARM
DTSTART:20180902T210500Z
DTEND:20180903T000500Z
UID:9_67UdSLClQB4rk8zLfygzsL@stanza.co
SUMMARY:Shuckers vs. Barons
DESCRIPTION:Shuckers vs. Barons\n\nFollow on MiLB First Pitch: https://stza.co/+vLyI-28\n\nShop: https://stza.co/+vLyI-3h\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144505Z
LAST-MODIFIED:20180213T144505Z
TRANSP:OPAQUE
END:VEVENT
* Shuckers vs. Barons
<2018-09-03 Mon>--<2018-09-02 Sun>
:PROPERTIES:
:ID:       r7hdDihibgEktM9_nJHl5VjG@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Shuckers vs. Barons Shuckers vs. Barons

Follow on MiLB First Pitch  https //stza.co/+vccL-3w

Shop  https //stza.co/+vccL-3_

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Shuckers vs. Barons
END:VALARM
DTSTART;VALUE=DATE:20180903
DTEND;VALUE=DATE:20180903
UID:r7hdDihibgEktM9_nJHl5VjG@stanza.co
SUMMARY:Shuckers vs. Barons
DESCRIPTION:Shuckers vs. Barons\n\nFollow on MiLB First Pitch: https://stza.co/+vccL-3w\n\nShop: https://stza.co/+vccL-3_\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144505Z
LAST-MODIFIED:20180213T144505Z
TRANSP:OPAQUE
END:VEVENT
