#+TITLE:       Main Google calendar entries
#+AUTHOR:      Eric S Fraga
#+EMAIL:       e.fraga@ucl.ac.uk
#+DESCRIPTION: converted using the ical2org awk script
#+CATEGORY:    google
#+STARTUP:     hidestars
#+STARTUP:     overview

* COMMENT original iCal preamble

* Muckdogs @ Doubledays
<2018-06-15 Fri 17:30-20:30>
:PROPERTIES:
:ID:       txXRq7l_LoT9XD8KUecWY34n@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Muckdogs @ Doubledays Muckdogs @ Doubledays

Follow on MiLB First Pitch  https //stza.co/+xV_9-U

Shop  https //stza.co/+xV_9-2T

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Muckdogs @ Doubledays
END:VALARM
DTSTART:20180615T223000Z
DTEND:20180616T013000Z
UID:txXRq7l_LoT9XD8KUecWY34n@stanza.co
SUMMARY:Muckdogs @ Doubledays
DESCRIPTION:Muckdogs @ Doubledays\n\nFollow on MiLB First Pitch: https://stza.co/+xV_9-U\n\nShop: https://stza.co/+xV_9-2T\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144503Z
LAST-MODIFIED:20180213T144503Z
TRANSP:OPAQUE
END:VEVENT
* Muckdogs @ Doubledays
<2018-06-16 Sat 17:30-20:30>
:PROPERTIES:
:ID:       gQtJ5Cg_bmFBrrVOaElTGPer@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Muckdogs @ Doubledays Muckdogs @ Doubledays

Follow on MiLB First Pitch  https //stza.co/+xV_a-1V

Shop  https //stza.co/+xV_a-2s

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Muckdogs @ Doubledays
END:VALARM
DTSTART:20180616T223000Z
DTEND:20180617T013000Z
UID:gQtJ5Cg_bmFBrrVOaElTGPer@stanza.co
SUMMARY:Muckdogs @ Doubledays
DESCRIPTION:Muckdogs @ Doubledays\n\nFollow on MiLB First Pitch: https://stza.co/+xV_a-1V\n\nShop: https://stza.co/+xV_a-2s\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144503Z
LAST-MODIFIED:20180213T144503Z
TRANSP:OPAQUE
END:VEVENT
* Muckdogs @ Doubledays
<2018-06-17 Sun 13:00-16:00>
:PROPERTIES:
:ID:       T_O6Mr52d9fvQUyR79Yk-D75@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Muckdogs @ Doubledays Muckdogs @ Doubledays

Follow on MiLB First Pitch  https //stza.co/+xV_b-k

Shop  https //stza.co/+xV_b-1H

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Muckdogs @ Doubledays
END:VALARM
DTSTART:20180617T180000Z
DTEND:20180617T210000Z
UID:T_O6Mr52d9fvQUyR79Yk-D75@stanza.co
SUMMARY:Muckdogs @ Doubledays
DESCRIPTION:Muckdogs @ Doubledays\n\nFollow on MiLB First Pitch: https://stza.co/+xV_b-k\n\nShop: https://stza.co/+xV_b-1H\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144503Z
LAST-MODIFIED:20180213T144503Z
TRANSP:OPAQUE
END:VEVENT
* Muckdogs vs. Black Bears
<2018-06-18 Mon>--<2018-06-17 Sun>
:PROPERTIES:
:ID:       P1y84gzI4q91tXqm9cO4evpF@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Muckdogs vs. Black Bears Muckdogs vs. Black Bears

Follow on MiLB First Pitch  https //stza.co/+xMhr-1F

Shop  https //stza.co/+xMhr-38

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Muckdogs vs. Black Bears
END:VALARM
DTSTART;VALUE=DATE:20180618
DTEND;VALUE=DATE:20180618
UID:P1y84gzI4q91tXqm9cO4evpF@stanza.co
SUMMARY:Muckdogs vs. Black Bears
DESCRIPTION:Muckdogs vs. Black Bears\n\nFollow on MiLB First Pitch: https://stza.co/+xMhr-1F\n\nShop: https://stza.co/+xMhr-38\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144503Z
LAST-MODIFIED:20180213T144503Z
TRANSP:OPAQUE
END:VEVENT
* Muckdogs vs. Black Bears
<2018-06-19 Tue>--<2018-06-18 Mon>
:PROPERTIES:
:ID:       ibGNGK36B9l27_XdYgegKZHA@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Muckdogs vs. Black Bears Muckdogs vs. Black Bears

Follow on MiLB First Pitch  https //stza.co/+xMht-1F

Shop  https //stza.co/+xMht-3f

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Muckdogs vs. Black Bears
END:VALARM
DTSTART;VALUE=DATE:20180619
DTEND;VALUE=DATE:20180619
UID:ibGNGK36B9l27_XdYgegKZHA@stanza.co
SUMMARY:Muckdogs vs. Black Bears
DESCRIPTION:Muckdogs vs. Black Bears\n\nFollow on MiLB First Pitch: https://stza.co/+xMht-1F\n\nShop: https://stza.co/+xMht-3f\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144503Z
LAST-MODIFIED:20180213T144503Z
TRANSP:OPAQUE
END:VEVENT
* Muckdogs vs. Black Bears
<2018-06-20 Wed>--<2018-06-19 Tue>
:PROPERTIES:
:ID:       sg4OpuFzbyFec_Ypo-gtSRns@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Muckdogs vs. Black Bears Muckdogs vs. Black Bears

Follow on MiLB First Pitch  https //stza.co/+xMhv-1E

Shop  https //stza.co/+xMhv-2$

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Muckdogs vs. Black Bears
END:VALARM
DTSTART;VALUE=DATE:20180620
DTEND;VALUE=DATE:20180620
UID:sg4OpuFzbyFec_Ypo-gtSRns@stanza.co
SUMMARY:Muckdogs vs. Black Bears
DESCRIPTION:Muckdogs vs. Black Bears\n\nFollow on MiLB First Pitch: https://stza.co/+xMhv-1E\n\nShop: https://stza.co/+xMhv-2$\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144503Z
LAST-MODIFIED:20180213T144503Z
TRANSP:OPAQUE
END:VEVENT
* Muckdogs vs. Crosscutters
<2018-06-21 Thu>--<2018-06-20 Wed>
:PROPERTIES:
:ID:       AAmPD-wMMhdG8pmcuuTy7cOn@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Muckdogs vs. Crosscutters Muckdogs vs. Crosscutters

Follow on MiLB First Pitch  https //stza.co/+xMhx-1d

Shop  https //stza.co/+xMhx-t

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Muckdogs vs. Crosscutters
END:VALARM
DTSTART;VALUE=DATE:20180621
DTEND;VALUE=DATE:20180621
UID:AAmPD-wMMhdG8pmcuuTy7cOn@stanza.co
SUMMARY:Muckdogs vs. Crosscutters
DESCRIPTION:Muckdogs vs. Crosscutters\n\nFollow on MiLB First Pitch: https://stza.co/+xMhx-1d\n\nShop: https://stza.co/+xMhx-t\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144503Z
LAST-MODIFIED:20180213T144503Z
TRANSP:OPAQUE
END:VEVENT
* Muckdogs vs. Crosscutters
<2018-06-22 Fri>--<2018-06-21 Thu>
:PROPERTIES:
:ID:       y2q2Mhiix8wWzoouyg94uicr@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Muckdogs vs. Crosscutters Muckdogs vs. Crosscutters

Follow on MiLB First Pitch  https //stza.co/+xMhz-28

Shop  https //stza.co/+xMhz-2B

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Muckdogs vs. Crosscutters
END:VALARM
DTSTART;VALUE=DATE:20180622
DTEND;VALUE=DATE:20180622
UID:y2q2Mhiix8wWzoouyg94uicr@stanza.co
SUMMARY:Muckdogs vs. Crosscutters
DESCRIPTION:Muckdogs vs. Crosscutters\n\nFollow on MiLB First Pitch: https://stza.co/+xMhz-28\n\nShop: https://stza.co/+xMhz-2B\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144503Z
LAST-MODIFIED:20180213T144503Z
TRANSP:OPAQUE
END:VEVENT
* Muckdogs vs. Crosscutters
<2018-06-23 Sat>--<2018-06-22 Fri>
:PROPERTIES:
:ID:       t6jzSqM5Ax0wLa3YF12ebHF2@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Muckdogs vs. Crosscutters Muckdogs vs. Crosscutters

Follow on MiLB First Pitch  https //stza.co/+xMhC-28

Shop  https //stza.co/+xMhC-3K

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Muckdogs vs. Crosscutters
END:VALARM
DTSTART;VALUE=DATE:20180623
DTEND;VALUE=DATE:20180623
UID:t6jzSqM5Ax0wLa3YF12ebHF2@stanza.co
SUMMARY:Muckdogs vs. Crosscutters
DESCRIPTION:Muckdogs vs. Crosscutters\n\nFollow on MiLB First Pitch: https://stza.co/+xMhC-28\n\nShop: https://stza.co/+xMhC-3K\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144503Z
LAST-MODIFIED:20180213T144503Z
TRANSP:OPAQUE
END:VEVENT
* Muckdogs @ Spikes
<2018-06-24 Sun>--<2018-06-23 Sat>
:PROPERTIES:
:ID:       oy0BD2-iy6IYteef_PzVSBh7@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Muckdogs @ Spikes Muckdogs @ Spikes

Follow on MiLB First Pitch  https //stza.co/+xMiM-3j

Shop  https //stza.co/+xMiM-x

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Muckdogs @ Spikes
END:VALARM
DTSTART;VALUE=DATE:20180624
DTEND;VALUE=DATE:20180624
UID:oy0BD2-iy6IYteef_PzVSBh7@stanza.co
SUMMARY:Muckdogs @ Spikes
DESCRIPTION:Muckdogs @ Spikes\n\nFollow on MiLB First Pitch: https://stza.co/+xMiM-3j\n\nShop: https://stza.co/+xMiM-x\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144503Z
LAST-MODIFIED:20180213T144503Z
TRANSP:OPAQUE
END:VEVENT
* Muckdogs @ Spikes
<2018-06-25 Mon>--<2018-06-24 Sun>
:PROPERTIES:
:ID:       MNCfpBFffmjVWDuC8vp5rxN1@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Muckdogs @ Spikes Muckdogs @ Spikes

Follow on MiLB First Pitch  https //stza.co/+xMiN-

Shop  https //stza.co/+xMiN-m

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Muckdogs @ Spikes
END:VALARM
DTSTART;VALUE=DATE:20180625
DTEND;VALUE=DATE:20180625
UID:MNCfpBFffmjVWDuC8vp5rxN1@stanza.co
SUMMARY:Muckdogs @ Spikes
DESCRIPTION:Muckdogs @ Spikes\n\nFollow on MiLB First Pitch: https://stza.co/+xMiN-\n\nShop: https://stza.co/+xMiN-m\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144503Z
LAST-MODIFIED:20180213T144503Z
TRANSP:OPAQUE
END:VEVENT
* Muckdogs @ Spikes
<2018-06-26 Tue>--<2018-06-25 Mon>
:PROPERTIES:
:ID:       CV3dafe4_B42a0pfmqnQz_OO@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Muckdogs @ Spikes Muckdogs @ Spikes

Follow on MiLB First Pitch  https //stza.co/+xMiO-F

Shop  https //stza.co/+xMiO-3V

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Muckdogs @ Spikes
END:VALARM
DTSTART;VALUE=DATE:20180626
DTEND;VALUE=DATE:20180626
UID:CV3dafe4_B42a0pfmqnQz_OO@stanza.co
SUMMARY:Muckdogs @ Spikes
DESCRIPTION:Muckdogs @ Spikes\n\nFollow on MiLB First Pitch: https://stza.co/+xMiO-F\n\nShop: https://stza.co/+xMiO-3V\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144503Z
LAST-MODIFIED:20180213T144503Z
TRANSP:OPAQUE
END:VEVENT
* Muckdogs vs. Doubledays
<2018-06-28 Thu>--<2018-06-27 Wed>
:PROPERTIES:
:ID:       7HXr3bKDY5eOQ8ZhU7JeVLM1@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Muckdogs vs. Doubledays Muckdogs vs. Doubledays

Follow on MiLB First Pitch  https //stza.co/+xMhE-4

Shop  https //stza.co/+xMhE-x

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Muckdogs vs. Doubledays
END:VALARM
DTSTART;VALUE=DATE:20180628
DTEND;VALUE=DATE:20180628
UID:7HXr3bKDY5eOQ8ZhU7JeVLM1@stanza.co
SUMMARY:Muckdogs vs. Doubledays
DESCRIPTION:Muckdogs vs. Doubledays\n\nFollow on MiLB First Pitch: https://stza.co/+xMhE-4\n\nShop: https://stza.co/+xMhE-x\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144503Z
LAST-MODIFIED:20180213T144503Z
TRANSP:OPAQUE
END:VEVENT
* Muckdogs @ Doubledays
<2018-06-29 Fri 17:30-20:30>
:PROPERTIES:
:ID:       UmmpqqFqmP_Dw1Xh8yPjBeHT@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Muckdogs @ Doubledays Muckdogs @ Doubledays

Follow on MiLB First Pitch  https //stza.co/+xV_c-2Z

Shop  https //stza.co/+xV_c-h

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Muckdogs @ Doubledays
END:VALARM
DTSTART:20180629T223000Z
DTEND:20180630T013000Z
UID:UmmpqqFqmP_Dw1Xh8yPjBeHT@stanza.co
SUMMARY:Muckdogs @ Doubledays
DESCRIPTION:Muckdogs @ Doubledays\n\nFollow on MiLB First Pitch: https://stza.co/+xV_c-2Z\n\nShop: https://stza.co/+xV_c-h\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144503Z
LAST-MODIFIED:20180213T144503Z
TRANSP:OPAQUE
END:VEVENT
* Muckdogs @ Doubledays
<2018-06-30 Sat 17:30-20:30>
:PROPERTIES:
:ID:       _LZgIVHG7SXiWY_lhvYN_TbL@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Muckdogs @ Doubledays Muckdogs @ Doubledays

Follow on MiLB First Pitch  https //stza.co/+xV_d-3k

Shop  https //stza.co/+xV_d-1L

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Muckdogs @ Doubledays
END:VALARM
DTSTART:20180630T223000Z
DTEND:20180701T013000Z
UID:_LZgIVHG7SXiWY_lhvYN_TbL@stanza.co
SUMMARY:Muckdogs @ Doubledays
DESCRIPTION:Muckdogs @ Doubledays\n\nFollow on MiLB First Pitch: https://stza.co/+xV_d-3k\n\nShop: https://stza.co/+xV_d-1L\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144503Z
LAST-MODIFIED:20180213T144503Z
TRANSP:OPAQUE
END:VEVENT
* Muckdogs vs. Black Bears
<2018-07-01 Sun>--<2018-06-30 Sat>
:PROPERTIES:
:ID:       vjwN4a4YFLFygJ545K1hdV7c@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Muckdogs vs. Black Bears Muckdogs vs. Black Bears

Follow on MiLB First Pitch  https //stza.co/+xMhG-L

Shop  https //stza.co/+xMhG-1V

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Muckdogs vs. Black Bears
END:VALARM
DTSTART;VALUE=DATE:20180701
DTEND;VALUE=DATE:20180701
UID:vjwN4a4YFLFygJ545K1hdV7c@stanza.co
SUMMARY:Muckdogs vs. Black Bears
DESCRIPTION:Muckdogs vs. Black Bears\n\nFollow on MiLB First Pitch: https://stza.co/+xMhG-L\n\nShop: https://stza.co/+xMhG-1V\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144503Z
LAST-MODIFIED:20180213T144503Z
TRANSP:OPAQUE
END:VEVENT
* Muckdogs vs. Black Bears
<2018-07-02 Mon>--<2018-07-01 Sun>
:PROPERTIES:
:ID:       H0cJYw_kFiL-9vsovRq7O4Xn@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Muckdogs vs. Black Bears Muckdogs vs. Black Bears

Follow on MiLB First Pitch  https //stza.co/+xMhH-1b

Shop  https //stza.co/+xMhH-3R

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Muckdogs vs. Black Bears
END:VALARM
DTSTART;VALUE=DATE:20180702
DTEND;VALUE=DATE:20180702
UID:H0cJYw_kFiL-9vsovRq7O4Xn@stanza.co
SUMMARY:Muckdogs vs. Black Bears
DESCRIPTION:Muckdogs vs. Black Bears\n\nFollow on MiLB First Pitch: https://stza.co/+xMhH-1b\n\nShop: https://stza.co/+xMhH-3R\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144503Z
LAST-MODIFIED:20180213T144503Z
TRANSP:OPAQUE
END:VEVENT
* Muckdogs vs. Black Bears
<2018-07-03 Tue>--<2018-07-02 Mon>
:PROPERTIES:
:ID:       tsZSe2JMVp2eciLKxzzRAtU8@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Muckdogs vs. Black Bears Muckdogs vs. Black Bears

Follow on MiLB First Pitch  https //stza.co/+xMhJ-m

Shop  https //stza.co/+xMhJ-1A

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Muckdogs vs. Black Bears
END:VALARM
DTSTART;VALUE=DATE:20180703
DTEND;VALUE=DATE:20180703
UID:tsZSe2JMVp2eciLKxzzRAtU8@stanza.co
SUMMARY:Muckdogs vs. Black Bears
DESCRIPTION:Muckdogs vs. Black Bears\n\nFollow on MiLB First Pitch: https://stza.co/+xMhJ-m\n\nShop: https://stza.co/+xMhJ-1A\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144503Z
LAST-MODIFIED:20180213T144503Z
TRANSP:OPAQUE
END:VEVENT
* Muckdogs @ Scrappers
<2018-07-04 Wed>--<2018-07-03 Tue>
:PROPERTIES:
:ID:       hzwaPhaV0hZs78R-sWRelbtz@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Muckdogs @ Scrappers Muckdogs @ Scrappers

Follow on MiLB First Pitch  https //stza.co/+xMiG-16

Shop  https //stza.co/+xMiG-2S

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Muckdogs @ Scrappers
END:VALARM
DTSTART;VALUE=DATE:20180704
DTEND;VALUE=DATE:20180704
UID:hzwaPhaV0hZs78R-sWRelbtz@stanza.co
SUMMARY:Muckdogs @ Scrappers
DESCRIPTION:Muckdogs @ Scrappers\n\nFollow on MiLB First Pitch: https://stza.co/+xMiG-16\n\nShop: https://stza.co/+xMiG-2S\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144503Z
LAST-MODIFIED:20180213T144503Z
TRANSP:OPAQUE
END:VEVENT
* Muckdogs @ Scrappers
<2018-07-05 Thu>--<2018-07-04 Wed>
:PROPERTIES:
:ID:       bjTohp4AETRnioDeX0x8DAoS@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Muckdogs @ Scrappers Muckdogs @ Scrappers

Follow on MiLB First Pitch  https //stza.co/+xMiH-3f

Shop  https //stza.co/+xMiH-2L

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Muckdogs @ Scrappers
END:VALARM
DTSTART;VALUE=DATE:20180705
DTEND;VALUE=DATE:20180705
UID:bjTohp4AETRnioDeX0x8DAoS@stanza.co
SUMMARY:Muckdogs @ Scrappers
DESCRIPTION:Muckdogs @ Scrappers\n\nFollow on MiLB First Pitch: https://stza.co/+xMiH-3f\n\nShop: https://stza.co/+xMiH-2L\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144503Z
LAST-MODIFIED:20180213T144503Z
TRANSP:OPAQUE
END:VEVENT
* Muckdogs @ Scrappers
<2018-07-06 Fri>--<2018-07-05 Thu>
:PROPERTIES:
:ID:       aTdqcmBNMSXpzwJV-a9mfO5d@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Muckdogs @ Scrappers Muckdogs @ Scrappers

Follow on MiLB First Pitch  https //stza.co/+xMiI-t

Shop  https //stza.co/+xMiI-2T

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Muckdogs @ Scrappers
END:VALARM
DTSTART;VALUE=DATE:20180706
DTEND;VALUE=DATE:20180706
UID:aTdqcmBNMSXpzwJV-a9mfO5d@stanza.co
SUMMARY:Muckdogs @ Scrappers
DESCRIPTION:Muckdogs @ Scrappers\n\nFollow on MiLB First Pitch: https://stza.co/+xMiI-t\n\nShop: https://stza.co/+xMiI-2T\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144503Z
LAST-MODIFIED:20180213T144503Z
TRANSP:OPAQUE
END:VEVENT
* Muckdogs vs. Spikes
<2018-07-07 Sat>--<2018-07-06 Fri>
:PROPERTIES:
:ID:       20Ng-RkHWEhhGxFApZ5YTJxW@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Muckdogs vs. Spikes Muckdogs vs. Spikes

Follow on MiLB First Pitch  https //stza.co/+xMhL-39

Shop  https //stza.co/+xMhL-2l

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Muckdogs vs. Spikes
END:VALARM
DTSTART;VALUE=DATE:20180707
DTEND;VALUE=DATE:20180707
UID:20Ng-RkHWEhhGxFApZ5YTJxW@stanza.co
SUMMARY:Muckdogs vs. Spikes
DESCRIPTION:Muckdogs vs. Spikes\n\nFollow on MiLB First Pitch: https://stza.co/+xMhL-39\n\nShop: https://stza.co/+xMhL-2l\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144503Z
LAST-MODIFIED:20180213T144503Z
TRANSP:OPAQUE
END:VEVENT
* Muckdogs vs. Spikes
<2018-07-08 Sun>--<2018-07-07 Sat>
:PROPERTIES:
:ID:       j0EWx54W-VUsVXM6f6FyyYn_@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Muckdogs vs. Spikes Muckdogs vs. Spikes

Follow on MiLB First Pitch  https //stza.co/+xMhO-3o

Shop  https //stza.co/+xMhO-a

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Muckdogs vs. Spikes
END:VALARM
DTSTART;VALUE=DATE:20180708
DTEND;VALUE=DATE:20180708
UID:j0EWx54W-VUsVXM6f6FyyYn_@stanza.co
SUMMARY:Muckdogs vs. Spikes
DESCRIPTION:Muckdogs vs. Spikes\n\nFollow on MiLB First Pitch: https://stza.co/+xMhO-3o\n\nShop: https://stza.co/+xMhO-a\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144503Z
LAST-MODIFIED:20180213T144503Z
TRANSP:OPAQUE
END:VEVENT
* Muckdogs vs. Spikes
<2018-07-09 Mon>--<2018-07-08 Sun>
:PROPERTIES:
:ID:       ZPLXss2h2ALxk-60NRRtZQVD@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Muckdogs vs. Spikes Muckdogs vs. Spikes

Follow on MiLB First Pitch  https //stza.co/+xMhP-1M

Shop  https //stza.co/+xMhP-U

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Muckdogs vs. Spikes
END:VALARM
DTSTART;VALUE=DATE:20180709
DTEND;VALUE=DATE:20180709
UID:ZPLXss2h2ALxk-60NRRtZQVD@stanza.co
SUMMARY:Muckdogs vs. Spikes
DESCRIPTION:Muckdogs vs. Spikes\n\nFollow on MiLB First Pitch: https://stza.co/+xMhP-1M\n\nShop: https://stza.co/+xMhP-U\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144503Z
LAST-MODIFIED:20180213T144503Z
TRANSP:OPAQUE
END:VEVENT
* Muckdogs @ Tigers
<2018-07-11 Wed>--<2018-07-10 Tue>
:PROPERTIES:
:ID:       2WYk3sQg7SNfT2m6goNAvTX4@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Muckdogs @ Tigers Muckdogs @ Tigers

Follow on MiLB First Pitch  https //stza.co/+xMiD-1q

Shop  https //stza.co/+xMiD-1D

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Muckdogs @ Tigers
END:VALARM
DTSTART;VALUE=DATE:20180711
DTEND;VALUE=DATE:20180711
UID:2WYk3sQg7SNfT2m6goNAvTX4@stanza.co
SUMMARY:Muckdogs @ Tigers
DESCRIPTION:Muckdogs @ Tigers\n\nFollow on MiLB First Pitch: https://stza.co/+xMiD-1q\n\nShop: https://stza.co/+xMiD-1D\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144503Z
LAST-MODIFIED:20180213T144503Z
TRANSP:OPAQUE
END:VEVENT
* Muckdogs @ Tigers
<2018-07-12 Thu>--<2018-07-11 Wed>
:PROPERTIES:
:ID:       ump1ywlSfFmJ4jd0qcP6cCs7@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Muckdogs @ Tigers Muckdogs @ Tigers

Follow on MiLB First Pitch  https //stza.co/+xMiE-1w

Shop  https //stza.co/+xMiE-1x

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Muckdogs @ Tigers
END:VALARM
DTSTART;VALUE=DATE:20180712
DTEND;VALUE=DATE:20180712
UID:ump1ywlSfFmJ4jd0qcP6cCs7@stanza.co
SUMMARY:Muckdogs @ Tigers
DESCRIPTION:Muckdogs @ Tigers\n\nFollow on MiLB First Pitch: https://stza.co/+xMiE-1w\n\nShop: https://stza.co/+xMiE-1x\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144503Z
LAST-MODIFIED:20180213T144503Z
TRANSP:OPAQUE
END:VEVENT
* Muckdogs @ Tigers
<2018-07-13 Fri>--<2018-07-12 Thu>
:PROPERTIES:
:ID:       002A1PXYeEu9KT90NyLcIXFE@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Muckdogs @ Tigers Muckdogs @ Tigers

Follow on MiLB First Pitch  https //stza.co/+xMiF-s

Shop  https //stza.co/+xMiF-r

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Muckdogs @ Tigers
END:VALARM
DTSTART;VALUE=DATE:20180713
DTEND;VALUE=DATE:20180713
UID:002A1PXYeEu9KT90NyLcIXFE@stanza.co
SUMMARY:Muckdogs @ Tigers
DESCRIPTION:Muckdogs @ Tigers\n\nFollow on MiLB First Pitch: https://stza.co/+xMiF-s\n\nShop: https://stza.co/+xMiF-r\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144503Z
LAST-MODIFIED:20180213T144503Z
TRANSP:OPAQUE
END:VEVENT
* Muckdogs vs. Spinners
<2018-07-14 Sat>--<2018-07-13 Fri>
:PROPERTIES:
:ID:       cb8SwxMrpUhuABgXpAAzEvKI@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Muckdogs vs. Spinners Muckdogs vs. Spinners

Follow on MiLB First Pitch  https //stza.co/+xMhS-3J

Shop  https //stza.co/+xMhS-p

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Muckdogs vs. Spinners
END:VALARM
DTSTART;VALUE=DATE:20180714
DTEND;VALUE=DATE:20180714
UID:cb8SwxMrpUhuABgXpAAzEvKI@stanza.co
SUMMARY:Muckdogs vs. Spinners
DESCRIPTION:Muckdogs vs. Spinners\n\nFollow on MiLB First Pitch: https://stza.co/+xMhS-3J\n\nShop: https://stza.co/+xMhS-p\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144503Z
LAST-MODIFIED:20180213T144503Z
TRANSP:OPAQUE
END:VEVENT
* Muckdogs vs. Spinners
<2018-07-15 Sun>--<2018-07-14 Sat>
:PROPERTIES:
:ID:       7UsnPz44MPNqUBmUI_Qh-oAm@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Muckdogs vs. Spinners Muckdogs vs. Spinners

Follow on MiLB First Pitch  https //stza.co/+xMhU-f

Shop  https //stza.co/+xMhU-3D

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Muckdogs vs. Spinners
END:VALARM
DTSTART;VALUE=DATE:20180715
DTEND;VALUE=DATE:20180715
UID:7UsnPz44MPNqUBmUI_Qh-oAm@stanza.co
SUMMARY:Muckdogs vs. Spinners
DESCRIPTION:Muckdogs vs. Spinners\n\nFollow on MiLB First Pitch: https://stza.co/+xMhU-f\n\nShop: https://stza.co/+xMhU-3D\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144503Z
LAST-MODIFIED:20180213T144503Z
TRANSP:OPAQUE
END:VEVENT
* Muckdogs vs. Spinners
<2018-07-16 Mon>--<2018-07-15 Sun>
:PROPERTIES:
:ID:       hDahB-ithtFPSuu3ljR9j7V8@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Muckdogs vs. Spinners Muckdogs vs. Spinners

Follow on MiLB First Pitch  https //stza.co/+xMhW-1v

Shop  https //stza.co/+xMhW-D

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Muckdogs vs. Spinners
END:VALARM
DTSTART;VALUE=DATE:20180716
DTEND;VALUE=DATE:20180716
UID:hDahB-ithtFPSuu3ljR9j7V8@stanza.co
SUMMARY:Muckdogs vs. Spinners
DESCRIPTION:Muckdogs vs. Spinners\n\nFollow on MiLB First Pitch: https://stza.co/+xMhW-1v\n\nShop: https://stza.co/+xMhW-D\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144503Z
LAST-MODIFIED:20180213T144503Z
TRANSP:OPAQUE
END:VEVENT
* Muckdogs @ Crosscutters
<2018-07-17 Tue 18:05-21:05>
:PROPERTIES:
:ID:       dQngkXWYPkFMwdzmTbj-D1Ik@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Muckdogs @ Crosscutters Muckdogs @ Crosscutters

Follow on MiLB First Pitch  https //stza.co/+x$63-1j

Shop  https //stza.co/+x$63-u

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Muckdogs @ Crosscutters
END:VALARM
DTSTART:20180717T230500Z
DTEND:20180718T020500Z
UID:dQngkXWYPkFMwdzmTbj-D1Ik@stanza.co
SUMMARY:Muckdogs @ Crosscutters
DESCRIPTION:Muckdogs @ Crosscutters\n\nFollow on MiLB First Pitch: https://stza.co/+x$63-1j\n\nShop: https://stza.co/+x$63-u\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144503Z
LAST-MODIFIED:20180213T144503Z
TRANSP:OPAQUE
END:VEVENT
* Muckdogs @ Crosscutters
<2018-07-18 Wed 18:05-21:05>
:PROPERTIES:
:ID:       msTc4d9ztgdFOwKmFGXh7XuP@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Muckdogs @ Crosscutters Muckdogs @ Crosscutters

Follow on MiLB First Pitch  https //stza.co/+x$64-J

Shop  https //stza.co/+x$64-4

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Muckdogs @ Crosscutters
END:VALARM
DTSTART:20180718T230500Z
DTEND:20180719T020500Z
UID:msTc4d9ztgdFOwKmFGXh7XuP@stanza.co
SUMMARY:Muckdogs @ Crosscutters
DESCRIPTION:Muckdogs @ Crosscutters\n\nFollow on MiLB First Pitch: https://stza.co/+x$64-J\n\nShop: https://stza.co/+x$64-4\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144503Z
LAST-MODIFIED:20180213T144503Z
TRANSP:OPAQUE
END:VEVENT
* Muckdogs @ Crosscutters
<2018-07-19 Thu 18:05-21:05>
:PROPERTIES:
:ID:       PmbaYq5FWiIPBJryKJwbAldY@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Muckdogs @ Crosscutters Muckdogs @ Crosscutters

Follow on MiLB First Pitch  https //stza.co/+x$65-2K

Shop  https //stza.co/+x$65-22

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Muckdogs @ Crosscutters
END:VALARM
DTSTART:20180719T230500Z
DTEND:20180720T020500Z
UID:PmbaYq5FWiIPBJryKJwbAldY@stanza.co
SUMMARY:Muckdogs @ Crosscutters
DESCRIPTION:Muckdogs @ Crosscutters\n\nFollow on MiLB First Pitch: https://stza.co/+x$65-2K\n\nShop: https://stza.co/+x$65-22\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144503Z
LAST-MODIFIED:20180213T144503Z
TRANSP:OPAQUE
END:VEVENT
* Muckdogs vs. Scrappers
<2018-07-20 Fri>--<2018-07-19 Thu>
:PROPERTIES:
:ID:       w-Q4Cjnzhn8Sigiaii_p6-L2@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Muckdogs vs. Scrappers Muckdogs vs. Scrappers

Follow on MiLB First Pitch  https //stza.co/+xMhY-15

Shop  https //stza.co/+xMhY-2s

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Muckdogs vs. Scrappers
END:VALARM
DTSTART;VALUE=DATE:20180720
DTEND;VALUE=DATE:20180720
UID:w-Q4Cjnzhn8Sigiaii_p6-L2@stanza.co
SUMMARY:Muckdogs vs. Scrappers
DESCRIPTION:Muckdogs vs. Scrappers\n\nFollow on MiLB First Pitch: https://stza.co/+xMhY-15\n\nShop: https://stza.co/+xMhY-2s\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144503Z
LAST-MODIFIED:20180213T144503Z
TRANSP:OPAQUE
END:VEVENT
* Muckdogs vs. Scrappers
<2018-07-21 Sat>--<2018-07-20 Fri>
:PROPERTIES:
:ID:       vesz5xHMnpBgJ629YBS_WXjh@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Muckdogs vs. Scrappers Muckdogs vs. Scrappers

Follow on MiLB First Pitch  https //stza.co/+xMhZ-2l

Shop  https //stza.co/+xMhZ-k

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Muckdogs vs. Scrappers
END:VALARM
DTSTART;VALUE=DATE:20180721
DTEND;VALUE=DATE:20180721
UID:vesz5xHMnpBgJ629YBS_WXjh@stanza.co
SUMMARY:Muckdogs vs. Scrappers
DESCRIPTION:Muckdogs vs. Scrappers\n\nFollow on MiLB First Pitch: https://stza.co/+xMhZ-2l\n\nShop: https://stza.co/+xMhZ-k\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144503Z
LAST-MODIFIED:20180213T144503Z
TRANSP:OPAQUE
END:VEVENT
* Muckdogs vs. Scrappers
<2018-07-22 Sun>--<2018-07-21 Sat>
:PROPERTIES:
:ID:       XibGofemzbCbWTVgx_vWrK3n@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Muckdogs vs. Scrappers Muckdogs vs. Scrappers

Follow on MiLB First Pitch  https //stza.co/+xMi0-8

Shop  https //stza.co/+xMi0-2Z

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Muckdogs vs. Scrappers
END:VALARM
DTSTART;VALUE=DATE:20180722
DTEND;VALUE=DATE:20180722
UID:XibGofemzbCbWTVgx_vWrK3n@stanza.co
SUMMARY:Muckdogs vs. Scrappers
DESCRIPTION:Muckdogs vs. Scrappers\n\nFollow on MiLB First Pitch: https://stza.co/+xMi0-8\n\nShop: https://stza.co/+xMi0-2Z\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144503Z
LAST-MODIFIED:20180213T144503Z
TRANSP:OPAQUE
END:VEVENT
* Muckdogs vs. Yankees
<2018-07-24 Tue>--<2018-07-23 Mon>
:PROPERTIES:
:ID:       DlIu5ING5Q-4UV9KcF0Co-Ly@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Muckdogs vs. Yankees Muckdogs vs. Yankees

Follow on MiLB First Pitch  https //stza.co/+xMi1-39

Shop  https //stza.co/+xMi1-1y

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Muckdogs vs. Yankees
END:VALARM
DTSTART;VALUE=DATE:20180724
DTEND;VALUE=DATE:20180724
UID:DlIu5ING5Q-4UV9KcF0Co-Ly@stanza.co
SUMMARY:Muckdogs vs. Yankees
DESCRIPTION:Muckdogs vs. Yankees\n\nFollow on MiLB First Pitch: https://stza.co/+xMi1-39\n\nShop: https://stza.co/+xMi1-1y\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144503Z
LAST-MODIFIED:20180213T144503Z
TRANSP:OPAQUE
END:VEVENT
* Muckdogs vs. Yankees
<2018-07-25 Wed>--<2018-07-24 Tue>
:PROPERTIES:
:ID:       Bm74_BRkap4RTjMLj6xFT0Ru@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Muckdogs vs. Yankees Muckdogs vs. Yankees

Follow on MiLB First Pitch  https //stza.co/+xMi3-32

Shop  https //stza.co/+xMi3-2p

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Muckdogs vs. Yankees
END:VALARM
DTSTART;VALUE=DATE:20180725
DTEND;VALUE=DATE:20180725
UID:Bm74_BRkap4RTjMLj6xFT0Ru@stanza.co
SUMMARY:Muckdogs vs. Yankees
DESCRIPTION:Muckdogs vs. Yankees\n\nFollow on MiLB First Pitch: https://stza.co/+xMi3-32\n\nShop: https://stza.co/+xMi3-2p\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144503Z
LAST-MODIFIED:20180213T144503Z
TRANSP:OPAQUE
END:VEVENT
* Muckdogs vs. Yankees
<2018-07-26 Thu>--<2018-07-25 Wed>
:PROPERTIES:
:ID:       j1f0jc5we94Yv8TEEzaSCrgF@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Muckdogs vs. Yankees Muckdogs vs. Yankees

Follow on MiLB First Pitch  https //stza.co/+xMi6-u

Shop  https //stza.co/+xMi6-6

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Muckdogs vs. Yankees
END:VALARM
DTSTART;VALUE=DATE:20180726
DTEND;VALUE=DATE:20180726
UID:j1f0jc5we94Yv8TEEzaSCrgF@stanza.co
SUMMARY:Muckdogs vs. Yankees
DESCRIPTION:Muckdogs vs. Yankees\n\nFollow on MiLB First Pitch: https://stza.co/+xMi6-u\n\nShop: https://stza.co/+xMi6-6\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144503Z
LAST-MODIFIED:20180213T144503Z
TRANSP:OPAQUE
END:VEVENT
* Muckdogs @ Lake Monsters
<2018-07-27 Fri>--<2018-07-26 Thu>
:PROPERTIES:
:ID:       CnLHByRQLXR1xkZcFSfEjX30@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Muckdogs @ Lake Monsters Muckdogs @ Lake Monsters

Follow on MiLB First Pitch  https //stza.co/+xMiS-v

Shop  https //stza.co/+xMiS-E

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Muckdogs @ Lake Monsters
END:VALARM
DTSTART;VALUE=DATE:20180727
DTEND;VALUE=DATE:20180727
UID:CnLHByRQLXR1xkZcFSfEjX30@stanza.co
SUMMARY:Muckdogs @ Lake Monsters
DESCRIPTION:Muckdogs @ Lake Monsters\n\nFollow on MiLB First Pitch: https://stza.co/+xMiS-v\n\nShop: https://stza.co/+xMiS-E\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144503Z
LAST-MODIFIED:20180213T144503Z
TRANSP:OPAQUE
END:VEVENT
* Muckdogs @ Lake Monsters
<2018-07-28 Sat>--<2018-07-27 Fri>
:PROPERTIES:
:ID:       vnPruWSyvGNk2y4vDciKJLz4@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Muckdogs @ Lake Monsters Muckdogs @ Lake Monsters

Follow on MiLB First Pitch  https //stza.co/+xMiT-3R

Shop  https //stza.co/+xMiT-2n

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Muckdogs @ Lake Monsters
END:VALARM
DTSTART;VALUE=DATE:20180728
DTEND;VALUE=DATE:20180728
UID:vnPruWSyvGNk2y4vDciKJLz4@stanza.co
SUMMARY:Muckdogs @ Lake Monsters
DESCRIPTION:Muckdogs @ Lake Monsters\n\nFollow on MiLB First Pitch: https://stza.co/+xMiT-3R\n\nShop: https://stza.co/+xMiT-2n\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144503Z
LAST-MODIFIED:20180213T144503Z
TRANSP:OPAQUE
END:VEVENT
* Muckdogs @ Lake Monsters
<2018-07-29 Sun>--<2018-07-28 Sat>
:PROPERTIES:
:ID:       tbys3ZvYz0DS0UUVXO9XMXZV@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Muckdogs @ Lake Monsters Muckdogs @ Lake Monsters

Follow on MiLB First Pitch  https //stza.co/+xMiU-1P

Shop  https //stza.co/+xMiU-h

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Muckdogs @ Lake Monsters
END:VALARM
DTSTART;VALUE=DATE:20180729
DTEND;VALUE=DATE:20180729
UID:tbys3ZvYz0DS0UUVXO9XMXZV@stanza.co
SUMMARY:Muckdogs @ Lake Monsters
DESCRIPTION:Muckdogs @ Lake Monsters\n\nFollow on MiLB First Pitch: https://stza.co/+xMiU-1P\n\nShop: https://stza.co/+xMiU-h\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144503Z
LAST-MODIFIED:20180213T144503Z
TRANSP:OPAQUE
END:VEVENT
* Muckdogs @ Spikes
<2018-07-30 Mon>--<2018-07-29 Sun>
:PROPERTIES:
:ID:       isIOPNCajafE7CjZ0khzFdq-@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Muckdogs @ Spikes Muckdogs @ Spikes

Follow on MiLB First Pitch  https //stza.co/+xMiP-1M

Shop  https //stza.co/+xMiP-3s

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Muckdogs @ Spikes
END:VALARM
DTSTART;VALUE=DATE:20180730
DTEND;VALUE=DATE:20180730
UID:isIOPNCajafE7CjZ0khzFdq-@stanza.co
SUMMARY:Muckdogs @ Spikes
DESCRIPTION:Muckdogs @ Spikes\n\nFollow on MiLB First Pitch: https://stza.co/+xMiP-1M\n\nShop: https://stza.co/+xMiP-3s\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144503Z
LAST-MODIFIED:20180213T144503Z
TRANSP:OPAQUE
END:VEVENT
* Muckdogs @ Spikes
<2018-07-31 Tue>--<2018-07-30 Mon>
:PROPERTIES:
:ID:       gVsIu5R9dp7FsaNf7KyXfUGm@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Muckdogs @ Spikes Muckdogs @ Spikes

Follow on MiLB First Pitch  https //stza.co/+xMiQ-M

Shop  https //stza.co/+xMiQ-2C

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Muckdogs @ Spikes
END:VALARM
DTSTART;VALUE=DATE:20180731
DTEND;VALUE=DATE:20180731
UID:gVsIu5R9dp7FsaNf7KyXfUGm@stanza.co
SUMMARY:Muckdogs @ Spikes
DESCRIPTION:Muckdogs @ Spikes\n\nFollow on MiLB First Pitch: https://stza.co/+xMiQ-M\n\nShop: https://stza.co/+xMiQ-2C\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144503Z
LAST-MODIFIED:20180213T144503Z
TRANSP:OPAQUE
END:VEVENT
* Muckdogs @ Spikes
<2018-08-01 Wed>--<2018-07-31 Tue>
:PROPERTIES:
:ID:       lsFp4v_CfF6p3EqLw5FwULEx@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Muckdogs @ Spikes Muckdogs @ Spikes

Follow on MiLB First Pitch  https //stza.co/+xMiR-1V

Shop  https //stza.co/+xMiR-1

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Muckdogs @ Spikes
END:VALARM
DTSTART;VALUE=DATE:20180801
DTEND;VALUE=DATE:20180801
UID:lsFp4v_CfF6p3EqLw5FwULEx@stanza.co
SUMMARY:Muckdogs @ Spikes
DESCRIPTION:Muckdogs @ Spikes\n\nFollow on MiLB First Pitch: https://stza.co/+xMiR-1V\n\nShop: https://stza.co/+xMiR-1\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144503Z
LAST-MODIFIED:20180213T144503Z
TRANSP:OPAQUE
END:VEVENT
* Muckdogs vs. Scrappers
<2018-08-02 Thu>--<2018-08-01 Wed>
:PROPERTIES:
:ID:       ORjRrvK-13PMCFAZR8x1RcTa@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Muckdogs vs. Scrappers Muckdogs vs. Scrappers

Follow on MiLB First Pitch  https //stza.co/+xMi7-6

Shop  https //stza.co/+xMi7-1p

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Muckdogs vs. Scrappers
END:VALARM
DTSTART;VALUE=DATE:20180802
DTEND;VALUE=DATE:20180802
UID:ORjRrvK-13PMCFAZR8x1RcTa@stanza.co
SUMMARY:Muckdogs vs. Scrappers
DESCRIPTION:Muckdogs vs. Scrappers\n\nFollow on MiLB First Pitch: https://stza.co/+xMi7-6\n\nShop: https://stza.co/+xMi7-1p\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144503Z
LAST-MODIFIED:20180213T144503Z
TRANSP:OPAQUE
END:VEVENT
* Muckdogs vs. Scrappers
<2018-08-03 Fri>--<2018-08-02 Thu>
:PROPERTIES:
:ID:       R8AoJfin14_rnGxac1YhJHl5@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Muckdogs vs. Scrappers Muckdogs vs. Scrappers

Follow on MiLB First Pitch  https //stza.co/+xMia-2R

Shop  https //stza.co/+xMia-s

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Muckdogs vs. Scrappers
END:VALARM
DTSTART;VALUE=DATE:20180803
DTEND;VALUE=DATE:20180803
UID:R8AoJfin14_rnGxac1YhJHl5@stanza.co
SUMMARY:Muckdogs vs. Scrappers
DESCRIPTION:Muckdogs vs. Scrappers\n\nFollow on MiLB First Pitch: https://stza.co/+xMia-2R\n\nShop: https://stza.co/+xMia-s\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144503Z
LAST-MODIFIED:20180213T144503Z
TRANSP:OPAQUE
END:VEVENT
* Muckdogs vs. Scrappers
<2018-08-04 Sat>--<2018-08-03 Fri>
:PROPERTIES:
:ID:       1h-FuRQ9e7RitvFlY9f-nCg2@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Muckdogs vs. Scrappers Muckdogs vs. Scrappers

Follow on MiLB First Pitch  https //stza.co/+xMic-10

Shop  https //stza.co/+xMic-2S

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Muckdogs vs. Scrappers
END:VALARM
DTSTART;VALUE=DATE:20180804
DTEND;VALUE=DATE:20180804
UID:1h-FuRQ9e7RitvFlY9f-nCg2@stanza.co
SUMMARY:Muckdogs vs. Scrappers
DESCRIPTION:Muckdogs vs. Scrappers\n\nFollow on MiLB First Pitch: https://stza.co/+xMic-10\n\nShop: https://stza.co/+xMic-2S\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144503Z
LAST-MODIFIED:20180213T144503Z
TRANSP:OPAQUE
END:VEVENT
* Muckdogs @ Black Bears
<2018-08-05 Sun 15:05-18:05>
:PROPERTIES:
:ID:       jCyD1_0ij0buul-_qxNWMDGX@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Muckdogs @ Black Bears Muckdogs @ Black Bears

Follow on MiLB First Pitch  https //stza.co/+xV_i-2O

Shop  https //stza.co/+xV_i-1Z

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Muckdogs @ Black Bears
END:VALARM
DTSTART:20180805T200500Z
DTEND:20180805T230500Z
UID:jCyD1_0ij0buul-_qxNWMDGX@stanza.co
SUMMARY:Muckdogs @ Black Bears
DESCRIPTION:Muckdogs @ Black Bears\n\nFollow on MiLB First Pitch: https://stza.co/+xV_i-2O\n\nShop: https://stza.co/+xV_i-1Z\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144503Z
LAST-MODIFIED:20180213T144503Z
TRANSP:OPAQUE
END:VEVENT
* Muckdogs @ Black Bears
<2018-08-06 Mon 18:05-21:05>
:PROPERTIES:
:ID:       wUYE-uoCcepunjYtGvvtK4rt@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Muckdogs @ Black Bears Muckdogs @ Black Bears

Follow on MiLB First Pitch  https //stza.co/+xV_j-3x

Shop  https //stza.co/+xV_j-3H

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Muckdogs @ Black Bears
END:VALARM
DTSTART:20180806T230500Z
DTEND:20180807T020500Z
UID:wUYE-uoCcepunjYtGvvtK4rt@stanza.co
SUMMARY:Muckdogs @ Black Bears
DESCRIPTION:Muckdogs @ Black Bears\n\nFollow on MiLB First Pitch: https://stza.co/+xV_j-3x\n\nShop: https://stza.co/+xV_j-3H\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144503Z
LAST-MODIFIED:20180213T144503Z
TRANSP:OPAQUE
END:VEVENT
* Muckdogs @ Black Bears
<2018-08-07 Tue 18:05-21:05>
:PROPERTIES:
:ID:       bfDyY9O9sDEuHKgHUEhAZtzG@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Muckdogs @ Black Bears Muckdogs @ Black Bears

Follow on MiLB First Pitch  https //stza.co/+xV_k-c

Shop  https //stza.co/+xV_k-1R

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Muckdogs @ Black Bears
END:VALARM
DTSTART:20180807T230500Z
DTEND:20180808T020500Z
UID:bfDyY9O9sDEuHKgHUEhAZtzG@stanza.co
SUMMARY:Muckdogs @ Black Bears
DESCRIPTION:Muckdogs @ Black Bears\n\nFollow on MiLB First Pitch: https://stza.co/+xV_k-c\n\nShop: https://stza.co/+xV_k-1R\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144503Z
LAST-MODIFIED:20180213T144503Z
TRANSP:OPAQUE
END:VEVENT
* Muckdogs @ Doubledays
<2018-08-08 Wed 17:30-20:30>
:PROPERTIES:
:ID:       nJ5f9Godh1Tgn4S2S4uai-mn@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Muckdogs @ Doubledays Muckdogs @ Doubledays

Follow on MiLB First Pitch  https //stza.co/+xV_e-3Z

Shop  https //stza.co/+xV_e-3x

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Muckdogs @ Doubledays
END:VALARM
DTSTART:20180808T223000Z
DTEND:20180809T013000Z
UID:nJ5f9Godh1Tgn4S2S4uai-mn@stanza.co
SUMMARY:Muckdogs @ Doubledays
DESCRIPTION:Muckdogs @ Doubledays\n\nFollow on MiLB First Pitch: https://stza.co/+xV_e-3Z\n\nShop: https://stza.co/+xV_e-3x\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144503Z
LAST-MODIFIED:20180213T144503Z
TRANSP:OPAQUE
END:VEVENT
* Muckdogs vs. Doubledays
<2018-08-09 Thu>--<2018-08-08 Wed>
:PROPERTIES:
:ID:       qGRKA8g4siwLVyaYRSC35fQ9@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Muckdogs vs. Doubledays Muckdogs vs. Doubledays

Follow on MiLB First Pitch  https //stza.co/+xMid-3X

Shop  https //stza.co/+xMid-32

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Muckdogs vs. Doubledays
END:VALARM
DTSTART;VALUE=DATE:20180809
DTEND;VALUE=DATE:20180809
UID:qGRKA8g4siwLVyaYRSC35fQ9@stanza.co
SUMMARY:Muckdogs vs. Doubledays
DESCRIPTION:Muckdogs vs. Doubledays\n\nFollow on MiLB First Pitch: https://stza.co/+xMid-3X\n\nShop: https://stza.co/+xMid-32\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144503Z
LAST-MODIFIED:20180213T144503Z
TRANSP:OPAQUE
END:VEVENT
* Muckdogs vs. Doubledays
<2018-08-10 Fri>--<2018-08-09 Thu>
:PROPERTIES:
:ID:       AiPfEg9Ghu1SMWBpxWLr1TrW@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Muckdogs vs. Doubledays Muckdogs vs. Doubledays

Follow on MiLB First Pitch  https //stza.co/+xMif-q

Shop  https //stza.co/+xMif-9

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Muckdogs vs. Doubledays
END:VALARM
DTSTART;VALUE=DATE:20180810
DTEND;VALUE=DATE:20180810
UID:AiPfEg9Ghu1SMWBpxWLr1TrW@stanza.co
SUMMARY:Muckdogs vs. Doubledays
DESCRIPTION:Muckdogs vs. Doubledays\n\nFollow on MiLB First Pitch: https://stza.co/+xMif-q\n\nShop: https://stza.co/+xMif-9\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144503Z
LAST-MODIFIED:20180213T144503Z
TRANSP:OPAQUE
END:VEVENT
* Muckdogs @ Crosscutters
<2018-08-11 Sat 18:05-21:05>
:PROPERTIES:
:ID:       mxAAjUkRaXCOPFw6FoYqrbqa@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Muckdogs @ Crosscutters Muckdogs @ Crosscutters

Follow on MiLB First Pitch  https //stza.co/+x$66-3Q

Shop  https //stza.co/+x$66-1Y

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Muckdogs @ Crosscutters
END:VALARM
DTSTART:20180811T230500Z
DTEND:20180812T020500Z
UID:mxAAjUkRaXCOPFw6FoYqrbqa@stanza.co
SUMMARY:Muckdogs @ Crosscutters
DESCRIPTION:Muckdogs @ Crosscutters\n\nFollow on MiLB First Pitch: https://stza.co/+x$66-3Q\n\nShop: https://stza.co/+x$66-1Y\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144503Z
LAST-MODIFIED:20180213T144503Z
TRANSP:OPAQUE
END:VEVENT
* Muckdogs @ Crosscutters
<2018-08-12 Sun 16:05-19:05>
:PROPERTIES:
:ID:       cD2MRPsywe8nBoSLPm8iw0X_@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Muckdogs @ Crosscutters Muckdogs @ Crosscutters

Follow on MiLB First Pitch  https //stza.co/+x$67-1D

Shop  https //stza.co/+x$67-1v

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Muckdogs @ Crosscutters
END:VALARM
DTSTART:20180812T210500Z
DTEND:20180813T000500Z
UID:cD2MRPsywe8nBoSLPm8iw0X_@stanza.co
SUMMARY:Muckdogs @ Crosscutters
DESCRIPTION:Muckdogs @ Crosscutters\n\nFollow on MiLB First Pitch: https://stza.co/+x$67-1D\n\nShop: https://stza.co/+x$67-1v\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144503Z
LAST-MODIFIED:20180213T144503Z
TRANSP:OPAQUE
END:VEVENT
* Muckdogs vs. Black Bears
<2018-08-15 Wed>--<2018-08-14 Tue>
:PROPERTIES:
:ID:       1njBgCcpAlIBlC7shvvK6UJS@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Muckdogs vs. Black Bears Muckdogs vs. Black Bears

Follow on MiLB First Pitch  https //stza.co/+xMih-W

Shop  https //stza.co/+xMih-3

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Muckdogs vs. Black Bears
END:VALARM
DTSTART;VALUE=DATE:20180815
DTEND;VALUE=DATE:20180815
UID:1njBgCcpAlIBlC7shvvK6UJS@stanza.co
SUMMARY:Muckdogs vs. Black Bears
DESCRIPTION:Muckdogs vs. Black Bears\n\nFollow on MiLB First Pitch: https://stza.co/+xMih-W\n\nShop: https://stza.co/+xMih-3\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144503Z
LAST-MODIFIED:20180213T144503Z
TRANSP:OPAQUE
END:VEVENT
* Muckdogs vs. Black Bears
<2018-08-16 Thu>--<2018-08-15 Wed>
:PROPERTIES:
:ID:       ma1uIVlSR85nqr4vJ6KU73jf@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Muckdogs vs. Black Bears Muckdogs vs. Black Bears

Follow on MiLB First Pitch  https //stza.co/+xMik-3E

Shop  https //stza.co/+xMik-3R

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Muckdogs vs. Black Bears
END:VALARM
DTSTART;VALUE=DATE:20180816
DTEND;VALUE=DATE:20180816
UID:ma1uIVlSR85nqr4vJ6KU73jf@stanza.co
SUMMARY:Muckdogs vs. Black Bears
DESCRIPTION:Muckdogs vs. Black Bears\n\nFollow on MiLB First Pitch: https://stza.co/+xMik-3E\n\nShop: https://stza.co/+xMik-3R\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144503Z
LAST-MODIFIED:20180213T144503Z
TRANSP:OPAQUE
END:VEVENT
* Muckdogs @ Doubledays
<2018-08-17 Fri 17:30-20:30>
:PROPERTIES:
:ID:       -oJgtMOVnOQpHcCVFsJdconJ@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Muckdogs @ Doubledays Muckdogs @ Doubledays

Follow on MiLB First Pitch  https //stza.co/+xV_f-e

Shop  https //stza.co/+xV_f-3v

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Muckdogs @ Doubledays
END:VALARM
DTSTART:20180817T223000Z
DTEND:20180818T013000Z
UID:-oJgtMOVnOQpHcCVFsJdconJ@stanza.co
SUMMARY:Muckdogs @ Doubledays
DESCRIPTION:Muckdogs @ Doubledays\n\nFollow on MiLB First Pitch: https://stza.co/+xV_f-e\n\nShop: https://stza.co/+xV_f-3v\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144503Z
LAST-MODIFIED:20180213T144503Z
TRANSP:OPAQUE
END:VEVENT
* Muckdogs @ Doubledays
<2018-08-18 Sat 17:30-20:30>
:PROPERTIES:
:ID:       FYrbmofcq3wnC-0JItTHp5aH@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Muckdogs @ Doubledays Muckdogs @ Doubledays

Follow on MiLB First Pitch  https //stza.co/+xV_g-2F

Shop  https //stza.co/+xV_g-s

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Muckdogs @ Doubledays
END:VALARM
DTSTART:20180818T223000Z
DTEND:20180819T013000Z
UID:FYrbmofcq3wnC-0JItTHp5aH@stanza.co
SUMMARY:Muckdogs @ Doubledays
DESCRIPTION:Muckdogs @ Doubledays\n\nFollow on MiLB First Pitch: https://stza.co/+xV_g-2F\n\nShop: https://stza.co/+xV_g-s\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144503Z
LAST-MODIFIED:20180213T144503Z
TRANSP:OPAQUE
END:VEVENT
* Muckdogs @ Doubledays
<2018-08-19 Sun 13:00-16:00>
:PROPERTIES:
:ID:       Kc9Okgp8qEbHlqAPYziRhYUA@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Muckdogs @ Doubledays Muckdogs @ Doubledays

Follow on MiLB First Pitch  https //stza.co/+xV_h-2D

Shop  https //stza.co/+xV_h-H

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Muckdogs @ Doubledays
END:VALARM
DTSTART:20180819T180000Z
DTEND:20180819T210000Z
UID:Kc9Okgp8qEbHlqAPYziRhYUA@stanza.co
SUMMARY:Muckdogs @ Doubledays
DESCRIPTION:Muckdogs @ Doubledays\n\nFollow on MiLB First Pitch: https://stza.co/+xV_h-2D\n\nShop: https://stza.co/+xV_h-H\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144503Z
LAST-MODIFIED:20180213T144503Z
TRANSP:OPAQUE
END:VEVENT
* Muckdogs @ Black Bears
<2018-08-20 Mon 18:05-21:05>
:PROPERTIES:
:ID:       cT-U9_GQ5rBEEX7G_CVdy7jE@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Muckdogs @ Black Bears Muckdogs @ Black Bears

Follow on MiLB First Pitch  https //stza.co/+xV_l-2n

Shop  https //stza.co/+xV_l-w

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Muckdogs @ Black Bears
END:VALARM
DTSTART:20180820T230500Z
DTEND:20180821T020500Z
UID:cT-U9_GQ5rBEEX7G_CVdy7jE@stanza.co
SUMMARY:Muckdogs @ Black Bears
DESCRIPTION:Muckdogs @ Black Bears\n\nFollow on MiLB First Pitch: https://stza.co/+xV_l-2n\n\nShop: https://stza.co/+xV_l-w\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144503Z
LAST-MODIFIED:20180213T144503Z
TRANSP:OPAQUE
END:VEVENT
* Muckdogs @ Black Bears
<2018-08-21 Tue 18:05-21:05>
:PROPERTIES:
:ID:       X63I-dTmcXnlLEF5CHDXEkdn@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Muckdogs @ Black Bears Muckdogs @ Black Bears

Follow on MiLB First Pitch  https //stza.co/+xV_m-2W

Shop  https //stza.co/+xV_m-1Q

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Muckdogs @ Black Bears
END:VALARM
DTSTART:20180821T230500Z
DTEND:20180822T020500Z
UID:X63I-dTmcXnlLEF5CHDXEkdn@stanza.co
SUMMARY:Muckdogs @ Black Bears
DESCRIPTION:Muckdogs @ Black Bears\n\nFollow on MiLB First Pitch: https://stza.co/+xV_m-2W\n\nShop: https://stza.co/+xV_m-1Q\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144503Z
LAST-MODIFIED:20180213T144503Z
TRANSP:OPAQUE
END:VEVENT
* Muckdogs @ Black Bears
<2018-08-22 Wed 18:05-21:05>
:PROPERTIES:
:ID:       lw_bpYpgvcgh3Lk43t4jFXft@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Muckdogs @ Black Bears Muckdogs @ Black Bears

Follow on MiLB First Pitch  https //stza.co/+xV_n-2x

Shop  https //stza.co/+xV_n-1r

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Muckdogs @ Black Bears
END:VALARM
DTSTART:20180822T230500Z
DTEND:20180823T020500Z
UID:lw_bpYpgvcgh3Lk43t4jFXft@stanza.co
SUMMARY:Muckdogs @ Black Bears
DESCRIPTION:Muckdogs @ Black Bears\n\nFollow on MiLB First Pitch: https://stza.co/+xV_n-2x\n\nShop: https://stza.co/+xV_n-1r\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144503Z
LAST-MODIFIED:20180213T144503Z
TRANSP:OPAQUE
END:VEVENT
* Muckdogs vs. Crosscutters
<2018-08-23 Thu>--<2018-08-22 Wed>
:PROPERTIES:
:ID:       3PdTDVCmrqEAQQd_73eHeciO@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Muckdogs vs. Crosscutters Muckdogs vs. Crosscutters

Follow on MiLB First Pitch  https //stza.co/+xMil-2x

Shop  https //stza.co/+xMil-v

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Muckdogs vs. Crosscutters
END:VALARM
DTSTART;VALUE=DATE:20180823
DTEND;VALUE=DATE:20180823
UID:3PdTDVCmrqEAQQd_73eHeciO@stanza.co
SUMMARY:Muckdogs vs. Crosscutters
DESCRIPTION:Muckdogs vs. Crosscutters\n\nFollow on MiLB First Pitch: https://stza.co/+xMil-2x\n\nShop: https://stza.co/+xMil-v\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144503Z
LAST-MODIFIED:20180213T144503Z
TRANSP:OPAQUE
END:VEVENT
* Muckdogs vs. Crosscutters
<2018-08-24 Fri>--<2018-08-23 Thu>
:PROPERTIES:
:ID:       iDeufYoPBu1CgxS3i663gI2I@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Muckdogs vs. Crosscutters Muckdogs vs. Crosscutters

Follow on MiLB First Pitch  https //stza.co/+xMin-Y

Shop  https //stza.co/+xMin-3W

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Muckdogs vs. Crosscutters
END:VALARM
DTSTART;VALUE=DATE:20180824
DTEND;VALUE=DATE:20180824
UID:iDeufYoPBu1CgxS3i663gI2I@stanza.co
SUMMARY:Muckdogs vs. Crosscutters
DESCRIPTION:Muckdogs vs. Crosscutters\n\nFollow on MiLB First Pitch: https://stza.co/+xMin-Y\n\nShop: https://stza.co/+xMin-3W\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144503Z
LAST-MODIFIED:20180213T144503Z
TRANSP:OPAQUE
END:VEVENT
* Muckdogs vs. Crosscutters
<2018-08-25 Sat>--<2018-08-24 Fri>
:PROPERTIES:
:ID:       HTi7XlGXZQgLUkCnpyQZbT8p@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Muckdogs vs. Crosscutters Muckdogs vs. Crosscutters

Follow on MiLB First Pitch  https //stza.co/+xMiq-e

Shop  https //stza.co/+xMiq-2O

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Muckdogs vs. Crosscutters
END:VALARM
DTSTART;VALUE=DATE:20180825
DTEND;VALUE=DATE:20180825
UID:HTi7XlGXZQgLUkCnpyQZbT8p@stanza.co
SUMMARY:Muckdogs vs. Crosscutters
DESCRIPTION:Muckdogs vs. Crosscutters\n\nFollow on MiLB First Pitch: https://stza.co/+xMiq-e\n\nShop: https://stza.co/+xMiq-2O\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144503Z
LAST-MODIFIED:20180213T144503Z
TRANSP:OPAQUE
END:VEVENT
* Muckdogs vs. Spikes
<2018-08-26 Sun>--<2018-08-25 Sat>
:PROPERTIES:
:ID:       Q5029SHyeAG4S64b5x3PsuHd@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Muckdogs vs. Spikes Muckdogs vs. Spikes

Follow on MiLB First Pitch  https //stza.co/+xMir-r

Shop  https //stza.co/+xMir-2y

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Muckdogs vs. Spikes
END:VALARM
DTSTART;VALUE=DATE:20180826
DTEND;VALUE=DATE:20180826
UID:Q5029SHyeAG4S64b5x3PsuHd@stanza.co
SUMMARY:Muckdogs vs. Spikes
DESCRIPTION:Muckdogs vs. Spikes\n\nFollow on MiLB First Pitch: https://stza.co/+xMir-r\n\nShop: https://stza.co/+xMir-2y\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144503Z
LAST-MODIFIED:20180213T144503Z
TRANSP:OPAQUE
END:VEVENT
* Muckdogs vs. Spikes
<2018-08-27 Mon>--<2018-08-26 Sun>
:PROPERTIES:
:ID:       HU1WeB5iLFbYUDjOK2HIRs-Q@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Muckdogs vs. Spikes Muckdogs vs. Spikes

Follow on MiLB First Pitch  https //stza.co/+xMiu-2y

Shop  https //stza.co/+xMiu-2_

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Muckdogs vs. Spikes
END:VALARM
DTSTART;VALUE=DATE:20180827
DTEND;VALUE=DATE:20180827
UID:HU1WeB5iLFbYUDjOK2HIRs-Q@stanza.co
SUMMARY:Muckdogs vs. Spikes
DESCRIPTION:Muckdogs vs. Spikes\n\nFollow on MiLB First Pitch: https://stza.co/+xMiu-2y\n\nShop: https://stza.co/+xMiu-2_\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144503Z
LAST-MODIFIED:20180213T144503Z
TRANSP:OPAQUE
END:VEVENT
* Muckdogs vs. Spikes
<2018-08-28 Tue>--<2018-08-27 Mon>
:PROPERTIES:
:ID:       zbezdm6n1Fbat5UPMpUyioy-@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Muckdogs vs. Spikes Muckdogs vs. Spikes

Follow on MiLB First Pitch  https //stza.co/+xMiw-1J

Shop  https //stza.co/+xMiw-1Z

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Muckdogs vs. Spikes
END:VALARM
DTSTART;VALUE=DATE:20180828
DTEND;VALUE=DATE:20180828
UID:zbezdm6n1Fbat5UPMpUyioy-@stanza.co
SUMMARY:Muckdogs vs. Spikes
DESCRIPTION:Muckdogs vs. Spikes\n\nFollow on MiLB First Pitch: https://stza.co/+xMiw-1J\n\nShop: https://stza.co/+xMiw-1Z\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144503Z
LAST-MODIFIED:20180213T144503Z
TRANSP:OPAQUE
END:VEVENT
* Muckdogs @ Scrappers
<2018-08-29 Wed>--<2018-08-28 Tue>
:PROPERTIES:
:ID:       A1PVRCv93F-E2FACNqTFNZ4W@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Muckdogs @ Scrappers Muckdogs @ Scrappers

Follow on MiLB First Pitch  https //stza.co/+xMiJ-2S

Shop  https //stza.co/+xMiJ-2T

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Muckdogs @ Scrappers
END:VALARM
DTSTART;VALUE=DATE:20180829
DTEND;VALUE=DATE:20180829
UID:A1PVRCv93F-E2FACNqTFNZ4W@stanza.co
SUMMARY:Muckdogs @ Scrappers
DESCRIPTION:Muckdogs @ Scrappers\n\nFollow on MiLB First Pitch: https://stza.co/+xMiJ-2S\n\nShop: https://stza.co/+xMiJ-2T\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144503Z
LAST-MODIFIED:20180213T144503Z
TRANSP:OPAQUE
END:VEVENT
* Muckdogs @ Scrappers
<2018-08-30 Thu>--<2018-08-29 Wed>
:PROPERTIES:
:ID:       IYL5S7_xpeWdUZyWPfT-SASp@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Muckdogs @ Scrappers Muckdogs @ Scrappers

Follow on MiLB First Pitch  https //stza.co/+xMiK-1v

Shop  https //stza.co/+xMiK-X

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Muckdogs @ Scrappers
END:VALARM
DTSTART;VALUE=DATE:20180830
DTEND;VALUE=DATE:20180830
UID:IYL5S7_xpeWdUZyWPfT-SASp@stanza.co
SUMMARY:Muckdogs @ Scrappers
DESCRIPTION:Muckdogs @ Scrappers\n\nFollow on MiLB First Pitch: https://stza.co/+xMiK-1v\n\nShop: https://stza.co/+xMiK-X\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144503Z
LAST-MODIFIED:20180213T144503Z
TRANSP:OPAQUE
END:VEVENT
* Muckdogs @ Scrappers
<2018-08-31 Fri>--<2018-08-30 Thu>
:PROPERTIES:
:ID:       _6PhxpV4QrppvF_1IgN9NLQT@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Muckdogs @ Scrappers Muckdogs @ Scrappers

Follow on MiLB First Pitch  https //stza.co/+xMiL-21

Shop  https //stza.co/+xMiL-2x

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Muckdogs @ Scrappers
END:VALARM
DTSTART;VALUE=DATE:20180831
DTEND;VALUE=DATE:20180831
UID:_6PhxpV4QrppvF_1IgN9NLQT@stanza.co
SUMMARY:Muckdogs @ Scrappers
DESCRIPTION:Muckdogs @ Scrappers\n\nFollow on MiLB First Pitch: https://stza.co/+xMiL-21\n\nShop: https://stza.co/+xMiL-2x\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144503Z
LAST-MODIFIED:20180213T144503Z
TRANSP:OPAQUE
END:VEVENT
* Muckdogs vs. Doubledays
<2018-09-01 Sat>--<2018-08-31 Fri>
:PROPERTIES:
:ID:       w4v1z7iHyWNNfMPesS7NmsLd@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Muckdogs vs. Doubledays Muckdogs vs. Doubledays

Follow on MiLB First Pitch  https //stza.co/+xMix-1$

Shop  https //stza.co/+xMix-1f

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Muckdogs vs. Doubledays
END:VALARM
DTSTART;VALUE=DATE:20180901
DTEND;VALUE=DATE:20180901
UID:w4v1z7iHyWNNfMPesS7NmsLd@stanza.co
SUMMARY:Muckdogs vs. Doubledays
DESCRIPTION:Muckdogs vs. Doubledays\n\nFollow on MiLB First Pitch: https://stza.co/+xMix-1$\n\nShop: https://stza.co/+xMix-1f\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144503Z
LAST-MODIFIED:20180213T144503Z
TRANSP:OPAQUE
END:VEVENT
* Muckdogs vs. Doubledays
<2018-09-02 Sun>--<2018-09-01 Sat>
:PROPERTIES:
:ID:       DzRXa4a-FpWK-kDq4A4Y80T2@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Muckdogs vs. Doubledays Muckdogs vs. Doubledays

Follow on MiLB First Pitch  https //stza.co/+xMiz-2f

Shop  https //stza.co/+xMiz-3_

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Muckdogs vs. Doubledays
END:VALARM
DTSTART;VALUE=DATE:20180902
DTEND;VALUE=DATE:20180902
UID:DzRXa4a-FpWK-kDq4A4Y80T2@stanza.co
SUMMARY:Muckdogs vs. Doubledays
DESCRIPTION:Muckdogs vs. Doubledays\n\nFollow on MiLB First Pitch: https://stza.co/+xMiz-2f\n\nShop: https://stza.co/+xMiz-3_\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144503Z
LAST-MODIFIED:20180213T144503Z
TRANSP:OPAQUE
END:VEVENT
* Muckdogs vs. Doubledays
<2018-09-03 Mon>--<2018-09-02 Sun>
:PROPERTIES:
:ID:       SmhAMJkshRRXv0h7JUCkM68W@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Muckdogs vs. Doubledays Muckdogs vs. Doubledays

Follow on MiLB First Pitch  https //stza.co/+xMiC-31

Shop  https //stza.co/+xMiC-13

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Muckdogs vs. Doubledays
END:VALARM
DTSTART;VALUE=DATE:20180903
DTEND;VALUE=DATE:20180903
UID:SmhAMJkshRRXv0h7JUCkM68W@stanza.co
SUMMARY:Muckdogs vs. Doubledays
DESCRIPTION:Muckdogs vs. Doubledays\n\nFollow on MiLB First Pitch: https://stza.co/+xMiC-31\n\nShop: https://stza.co/+xMiC-13\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144503Z
LAST-MODIFIED:20180213T144503Z
TRANSP:OPAQUE
END:VEVENT
