#+TITLE:       Main Google calendar entries
#+AUTHOR:      Eric S Fraga
#+EMAIL:       e.fraga@ucl.ac.uk
#+DESCRIPTION: converted using the ical2org awk script
#+CATEGORY:    google
#+STARTUP:     hidestars
#+STARTUP:     overview

* COMMENT original iCal preamble

* Red Wings vs. Bisons
<2018-04-06 Fri 17:05-20:05>
:PROPERTIES:
:ID:       aIcbZXWUPykTTCCgoENrwgZo@stanza.co
:LOCATION: Red Wings Magnet Schedule Giveaway
:STATUS:   CONFIRMED
:END:

Red Wings vs. Bisons Follow the Wings whereabouts all season long with a 2018 Red Wings magnet schedule.

Follow on MiLB First Pitch  https //stza.co/+vKlH-3W

Shop  https //stza.co/+vKlH-3F

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Red Wings vs. Bisons
END:VALARM
DTSTART:20180406T220500Z
DTEND:20180407T010500Z
UID:aIcbZXWUPykTTCCgoENrwgZo@stanza.co
SUMMARY:Red Wings vs. Bisons
DESCRIPTION:Follow the Wings whereabouts all season long with a 2018 Red Wings magnet schedule.\n\nFollow on MiLB First Pitch: https://stza.co/+vKlH-3W\n\nShop: https://stza.co/+vKlH-3F\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Red Wings Magnet Schedule Giveaway
STATUS:CONFIRMED
CREATED:20180213T144635Z
LAST-MODIFIED:20180213T144635Z
TRANSP:OPAQUE
END:VEVENT
* Red Wings vs. Bisons
<2018-04-07 Sat 12:05-15:05>
:PROPERTIES:
:ID:       UIGk7ezt2QJLdIz-YHqxnVkp@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Red Wings vs. Bisons Red Wings vs. Bisons

Follow on MiLB First Pitch  https //stza.co/+vKlK-J

Shop  https //stza.co/+vKlK-I

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Red Wings vs. Bisons
END:VALARM
DTSTART:20180407T170500Z
DTEND:20180407T200500Z
UID:UIGk7ezt2QJLdIz-YHqxnVkp@stanza.co
SUMMARY:Red Wings vs. Bisons
DESCRIPTION:Red Wings vs. Bisons\n\nFollow on MiLB First Pitch: https://stza.co/+vKlK-J\n\nShop: https://stza.co/+vKlK-I\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144635Z
LAST-MODIFIED:20180213T144635Z
TRANSP:OPAQUE
END:VEVENT
* Red Wings vs. Bisons
<2018-04-08 Sun 12:05-15:05>
:PROPERTIES:
:ID:       kygYodhISdN97O2b98BKsDpr@stanza.co
:LOCATION: Bark in the Park
:STATUS:   CONFIRMED
:END:

Red Wings vs. Bisons NEW in 2018  Fans with dogs will be able to participate in a pre-game dog parade on the field. Also, the third base grass berm will be open to all dogs and their owners.

Every Sunday kids 12 and under can run the bases with Red Wings mascots Spikes and Mittsy!

Follow on MiLB First Pitch  https //stza.co/+vKlM-1d

Shop  https //stza.co/+vKlM-1T

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Red Wings vs. Bisons
END:VALARM
DTSTART:20180408T170500Z
DTEND:20180408T200500Z
UID:kygYodhISdN97O2b98BKsDpr@stanza.co
SUMMARY:Red Wings vs. Bisons
DESCRIPTION:NEW in 2018: Fans with dogs will be able to participate in a pre-game dog parade on the field. Also, the third base grass berm will be open to all dogs and their owners.\n\nEvery Sunday kids 12 and under can run the bases with Red Wings mascots Spikes and Mittsy!\n\nFollow on MiLB First Pitch: https://stza.co/+vKlM-1d\n\nShop: https://stza.co/+vKlM-1T\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Bark in the Park
STATUS:CONFIRMED
CREATED:20180213T144635Z
LAST-MODIFIED:20180213T144635Z
TRANSP:OPAQUE
END:VEVENT
* Red Wings vs. Chiefs
<2018-04-09 Mon 17:35-20:35>
:PROPERTIES:
:ID:       LYmD_fI5SI6B5JQ5iNYL91pJ@stanza.co
:LOCATION: Kids Eat Free Mondays
:STATUS:   CONFIRMED
:END:

Red Wings vs. Chiefs Every Monday home game the first 500 kids get a FREE hot dog, snack item and soda!

Follow on MiLB First Pitch  https //stza.co/+vKlN-2$

Shop  https //stza.co/+vKlN-3w

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Red Wings vs. Chiefs
END:VALARM
DTSTART:20180409T223500Z
DTEND:20180410T013500Z
UID:LYmD_fI5SI6B5JQ5iNYL91pJ@stanza.co
SUMMARY:Red Wings vs. Chiefs
DESCRIPTION:Every Monday home game the first 500 kids get a FREE hot dog, snack item and soda!\n\nFollow on MiLB First Pitch: https://stza.co/+vKlN-2$\n\nShop: https://stza.co/+vKlN-3w\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Kids Eat Free Mondays
STATUS:CONFIRMED
CREATED:20180213T144635Z
LAST-MODIFIED:20180213T144635Z
TRANSP:OPAQUE
END:VEVENT
* Red Wings vs. Chiefs
<2018-04-10 Tue 17:35-20:35>
:PROPERTIES:
:ID:       eralbIGw2zozIs-wQ7MUgsLh@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Red Wings vs. Chiefs Red Wings vs. Chiefs

Follow on MiLB First Pitch  https //stza.co/+vKlP-17

Shop  https //stza.co/+vKlP-3T

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Red Wings vs. Chiefs
END:VALARM
DTSTART:20180410T223500Z
DTEND:20180411T013500Z
UID:eralbIGw2zozIs-wQ7MUgsLh@stanza.co
SUMMARY:Red Wings vs. Chiefs
DESCRIPTION:Red Wings vs. Chiefs\n\nFollow on MiLB First Pitch: https://stza.co/+vKlP-17\n\nShop: https://stza.co/+vKlP-3T\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144635Z
LAST-MODIFIED:20180213T144635Z
TRANSP:OPAQUE
END:VEVENT
* Red Wings vs. Chiefs
<2018-04-11 Wed 11:35-14:35>
:PROPERTIES:
:ID:       000sCOOnQUYUIatsLAuHU5nY@stanza.co
:LOCATION: $1 Wednesdays
:STATUS:   CONFIRMED
:END:

Red Wings vs. Chiefs Every Wednesday - excluding Wednesday, July 4th - enjoy ONE DOLLAR hot dogs, peanuts, cracker jacks and chips!

Follow on MiLB First Pitch  https //stza.co/+vKlR-D

Shop  https //stza.co/+vKlR-2X

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Red Wings vs. Chiefs
END:VALARM
DTSTART:20180411T163500Z
DTEND:20180411T193500Z
UID:000sCOOnQUYUIatsLAuHU5nY@stanza.co
SUMMARY:Red Wings vs. Chiefs
DESCRIPTION:Every Wednesday - excluding Wednesday, July 4th - enjoy ONE DOLLAR hot dogs, peanuts, cracker jacks and chips!\n\nFollow on MiLB First Pitch: https://stza.co/+vKlR-D\n\nShop: https://stza.co/+vKlR-2X\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:$1 Wednesdays
STATUS:CONFIRMED
CREATED:20180213T144635Z
LAST-MODIFIED:20180213T144635Z
TRANSP:OPAQUE
END:VEVENT
* Red Wings @ Stripers
<2018-04-12 Thu 18:05-21:05>
:PROPERTIES:
:ID:       cAokaFUmMDRHnNmd3p2bo0OZ@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Red Wings @ Stripers Red Wings @ Stripers

Follow on MiLB First Pitch  https //stza.co/+vKlf-2a

Shop  https //stza.co/+vKlf-T

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Red Wings @ Stripers
END:VALARM
DTSTART:20180412T230500Z
DTEND:20180413T020500Z
UID:cAokaFUmMDRHnNmd3p2bo0OZ@stanza.co
SUMMARY:Red Wings @ Stripers
DESCRIPTION:Red Wings @ Stripers\n\nFollow on MiLB First Pitch: https://stza.co/+vKlf-2a\n\nShop: https://stza.co/+vKlf-T\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144635Z
LAST-MODIFIED:20180213T144635Z
TRANSP:OPAQUE
END:VEVENT
* Red Wings @ Stripers
<2018-04-13 Fri 18:05-21:05>
:PROPERTIES:
:ID:       lnIC-GPf_lfbn95PQiryAU04@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Red Wings @ Stripers Red Wings @ Stripers

Follow on MiLB First Pitch  https //stza.co/+vKlg-1B

Shop  https //stza.co/+vKlg-3a

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Red Wings @ Stripers
END:VALARM
DTSTART:20180413T230500Z
DTEND:20180414T020500Z
UID:lnIC-GPf_lfbn95PQiryAU04@stanza.co
SUMMARY:Red Wings @ Stripers
DESCRIPTION:Red Wings @ Stripers\n\nFollow on MiLB First Pitch: https://stza.co/+vKlg-1B\n\nShop: https://stza.co/+vKlg-3a\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144635Z
LAST-MODIFIED:20180213T144635Z
TRANSP:OPAQUE
END:VEVENT
* Red Wings @ Stripers
<2018-04-14 Sat 17:05-20:05>
:PROPERTIES:
:ID:       FraGXfe0d8VdXNkmVd861uH9@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Red Wings @ Stripers Red Wings @ Stripers

Follow on MiLB First Pitch  https //stza.co/+vKlh-2l

Shop  https //stza.co/+vKlh-3U

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Red Wings @ Stripers
END:VALARM
DTSTART:20180414T220500Z
DTEND:20180415T010500Z
UID:FraGXfe0d8VdXNkmVd861uH9@stanza.co
SUMMARY:Red Wings @ Stripers
DESCRIPTION:Red Wings @ Stripers\n\nFollow on MiLB First Pitch: https://stza.co/+vKlh-2l\n\nShop: https://stza.co/+vKlh-3U\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144635Z
LAST-MODIFIED:20180213T144635Z
TRANSP:OPAQUE
END:VEVENT
* Red Wings @ Stripers
<2018-04-15 Sun 12:05-15:05>
:PROPERTIES:
:ID:       7b-MCgBcpJvawGe2zvldKjoc@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Red Wings @ Stripers Red Wings @ Stripers

Follow on MiLB First Pitch  https //stza.co/+vKli-1w

Shop  https //stza.co/+vKli-22

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Red Wings @ Stripers
END:VALARM
DTSTART:20180415T170500Z
DTEND:20180415T200500Z
UID:7b-MCgBcpJvawGe2zvldKjoc@stanza.co
SUMMARY:Red Wings @ Stripers
DESCRIPTION:Red Wings @ Stripers\n\nFollow on MiLB First Pitch: https://stza.co/+vKli-1w\n\nShop: https://stza.co/+vKli-22\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144635Z
LAST-MODIFIED:20180213T144635Z
TRANSP:OPAQUE
END:VEVENT
* Red Wings @ Knights
<2018-04-16 Mon 18:04-21:04>
:PROPERTIES:
:ID:       LmVd7G0gb-5TIaXowBk3WvJB@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Red Wings @ Knights Red Wings @ Knights

Follow on MiLB First Pitch  https //stza.co/+xONJ-3L

Shop  https //stza.co/+xONJ-E

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Red Wings @ Knights
END:VALARM
DTSTART:20180416T230400Z
DTEND:20180417T020400Z
UID:LmVd7G0gb-5TIaXowBk3WvJB@stanza.co
SUMMARY:Red Wings @ Knights
DESCRIPTION:Red Wings @ Knights\n\nFollow on MiLB First Pitch: https://stza.co/+xONJ-3L\n\nShop: https://stza.co/+xONJ-E\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144635Z
LAST-MODIFIED:20180213T144635Z
TRANSP:OPAQUE
END:VEVENT
* Red Wings @ Knights
<2018-04-17 Tue 18:04-21:04>
:PROPERTIES:
:ID:       letpb_9NVrusq4noYJoMaChu@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Red Wings @ Knights Red Wings @ Knights

Follow on MiLB First Pitch  https //stza.co/+xONK-1M

Shop  https //stza.co/+xONK-2U

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Red Wings @ Knights
END:VALARM
DTSTART:20180417T230400Z
DTEND:20180418T020400Z
UID:letpb_9NVrusq4noYJoMaChu@stanza.co
SUMMARY:Red Wings @ Knights
DESCRIPTION:Red Wings @ Knights\n\nFollow on MiLB First Pitch: https://stza.co/+xONK-1M\n\nShop: https://stza.co/+xONK-2U\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144635Z
LAST-MODIFIED:20180213T144635Z
TRANSP:OPAQUE
END:VEVENT
* Red Wings @ Knights
<2018-04-18 Wed 18:04-21:04>
:PROPERTIES:
:ID:       H8HQbKpU9WqkrPoL1dWpCSVb@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Red Wings @ Knights Red Wings @ Knights

Follow on MiLB First Pitch  https //stza.co/+xONL-2e

Shop  https //stza.co/+xONL-1u

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Red Wings @ Knights
END:VALARM
DTSTART:20180418T230400Z
DTEND:20180419T020400Z
UID:H8HQbKpU9WqkrPoL1dWpCSVb@stanza.co
SUMMARY:Red Wings @ Knights
DESCRIPTION:Red Wings @ Knights\n\nFollow on MiLB First Pitch: https://stza.co/+xONL-2e\n\nShop: https://stza.co/+xONL-1u\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144635Z
LAST-MODIFIED:20180213T144635Z
TRANSP:OPAQUE
END:VEVENT
* Red Wings vs. Clippers
<2018-04-20 Fri 17:35-20:35>
:PROPERTIES:
:ID:       7ZK7XA3moeEHIAa-aFXWVkSn@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Red Wings vs. Clippers Red Wings vs. Clippers

Follow on MiLB First Pitch  https //stza.co/+vKlU-2y

Shop  https //stza.co/+vKlU-23

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Red Wings vs. Clippers
END:VALARM
DTSTART:20180420T223500Z
DTEND:20180421T013500Z
UID:7ZK7XA3moeEHIAa-aFXWVkSn@stanza.co
SUMMARY:Red Wings vs. Clippers
DESCRIPTION:Red Wings vs. Clippers\n\nFollow on MiLB First Pitch: https://stza.co/+vKlU-2y\n\nShop: https://stza.co/+vKlU-23\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144635Z
LAST-MODIFIED:20180213T144635Z
TRANSP:OPAQUE
END:VEVENT
* Red Wings vs. Clippers
<2018-04-21 Sat 12:05-15:05>
:PROPERTIES:
:ID:       SyZFjdvZjTXwNwreWYb-bxDB@stanza.co
:LOCATION: Red Wings Team Autograph Day
:STATUS:   CONFIRMED
:END:

Red Wings vs. Clippers The entire Red Wings team will be signing autographs on the field immediately following the game.

Follow on MiLB First Pitch  https //stza.co/+vKlW-1o

Shop  https //stza.co/+vKlW-2S

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Red Wings vs. Clippers
END:VALARM
DTSTART:20180421T170500Z
DTEND:20180421T200500Z
UID:SyZFjdvZjTXwNwreWYb-bxDB@stanza.co
SUMMARY:Red Wings vs. Clippers
DESCRIPTION:The entire Red Wings team will be signing autographs on the field immediately following the game.\n\nFollow on MiLB First Pitch: https://stza.co/+vKlW-1o\n\nShop: https://stza.co/+vKlW-2S\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Red Wings Team Autograph Day
STATUS:CONFIRMED
CREATED:20180213T144635Z
LAST-MODIFIED:20180213T144635Z
TRANSP:OPAQUE
END:VEVENT
* Red Wings vs. Clippers
<2018-04-22 Sun 12:05-15:05>
:PROPERTIES:
:ID:       DFiIVt1PDlm0PSt4Gh4UrlJ7@stanza.co
:LOCATION: Bark in the Park
:STATUS:   CONFIRMED
:END:

Red Wings vs. Clippers NEW in 2018  Fans with dogs will be able to participate in a pre-game dog parade on the field. Also, the third base grass berm will be open to all dogs and their owners.

Every Sunday kids 12 and under can run the bases with Red Wings mascots Spikes and Mittsy!

Follow on MiLB First Pitch  https //stza.co/+vKlY-H

Shop  https //stza.co/+vKlY-1C

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Red Wings vs. Clippers
END:VALARM
DTSTART:20180422T170500Z
DTEND:20180422T200500Z
UID:DFiIVt1PDlm0PSt4Gh4UrlJ7@stanza.co
SUMMARY:Red Wings vs. Clippers
DESCRIPTION:NEW in 2018: Fans with dogs will be able to participate in a pre-game dog parade on the field. Also, the third base grass berm will be open to all dogs and their owners.\n\nEvery Sunday kids 12 and under can run the bases with Red Wings mascots Spikes and Mittsy!\n\nFollow on MiLB First Pitch: https://stza.co/+vKlY-H\n\nShop: https://stza.co/+vKlY-1C\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Bark in the Park
STATUS:CONFIRMED
CREATED:20180213T144635Z
LAST-MODIFIED:20180213T144635Z
TRANSP:OPAQUE
END:VEVENT
* Red Wings vs. Stripers
<2018-04-23 Mon 17:35-20:35>
:PROPERTIES:
:ID:       Is5yX-el6D4f27qiVg55-Vzj@stanza.co
:LOCATION: Kids Eat Free Mondays
:STATUS:   CONFIRMED
:END:

Red Wings vs. Stripers Every Monday home game the first 500 kids get a FREE hot dog, snack item and soda!

Follow on MiLB First Pitch  https //stza.co/+vKlZ-2g

Shop  https //stza.co/+vKlZ-11

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Red Wings vs. Stripers
END:VALARM
DTSTART:20180423T223500Z
DTEND:20180424T013500Z
UID:Is5yX-el6D4f27qiVg55-Vzj@stanza.co
SUMMARY:Red Wings vs. Stripers
DESCRIPTION:Every Monday home game the first 500 kids get a FREE hot dog, snack item and soda!\n\nFollow on MiLB First Pitch: https://stza.co/+vKlZ-2g\n\nShop: https://stza.co/+vKlZ-11\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Kids Eat Free Mondays
STATUS:CONFIRMED
CREATED:20180213T144635Z
LAST-MODIFIED:20180213T144635Z
TRANSP:OPAQUE
END:VEVENT
* Red Wings vs. Stripers
<2018-04-24 Tue 17:35-20:35>
:PROPERTIES:
:ID:       ZCuqMT5Epbjv4yHsqJKBX47V@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Red Wings vs. Stripers Red Wings vs. Stripers

Follow on MiLB First Pitch  https //stza.co/+vKl$-H

Shop  https //stza.co/+vKl$-I

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Red Wings vs. Stripers
END:VALARM
DTSTART:20180424T223500Z
DTEND:20180425T013500Z
UID:ZCuqMT5Epbjv4yHsqJKBX47V@stanza.co
SUMMARY:Red Wings vs. Stripers
DESCRIPTION:Red Wings vs. Stripers\n\nFollow on MiLB First Pitch: https://stza.co/+vKl$-H\n\nShop: https://stza.co/+vKl$-I\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144635Z
LAST-MODIFIED:20180213T144635Z
TRANSP:OPAQUE
END:VEVENT
* Red Wings vs. Stripers
<2018-04-25 Wed 10:05-13:05>
:PROPERTIES:
:ID:       ZVBhu6qaP-yjicmM7N7APYcg@stanza.co
:LOCATION: Careers in Sports Day
:STATUS:   CONFIRMED
:END:

Red Wings vs. Stripers Bring your school group out to learn about a variety of different careers in the sports industry from our distinguished panel of guests! Contact Eric Friedman 585-454-1001 ext. 3057 to book your group.

Every Wednesday - excluding Wednesday, July 4th - enjoy ONE DOLLAR hot dogs, peanuts, cracker jacks and chips!

Follow on MiLB First Pitch  https //stza.co/+vKm2-1n

Shop  https //stza.co/+vKm2-2m

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Red Wings vs. Stripers
END:VALARM
DTSTART:20180425T150500Z
DTEND:20180425T180500Z
UID:ZVBhu6qaP-yjicmM7N7APYcg@stanza.co
SUMMARY:Red Wings vs. Stripers
DESCRIPTION:Bring your school group out to learn about a variety of different careers in the sports industry from our distinguished panel of guests! Contact Eric Friedman 585-454-1001 ext. 3057 to book your group.\n\nEvery Wednesday - excluding Wednesday, July 4th - enjoy ONE DOLLAR hot dogs, peanuts, cracker jacks and chips!\n\nFollow on MiLB First Pitch: https://stza.co/+vKm2-1n\n\nShop: https://stza.co/+vKm2-2m\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Careers in Sports Day
STATUS:CONFIRMED
CREATED:20180213T144635Z
LAST-MODIFIED:20180213T144635Z
TRANSP:OPAQUE
END:VEVENT
* Red Wings @ Chiefs
<2018-04-27 Fri 17:35-20:35>
:PROPERTIES:
:ID:       hi7Jq_NoyTvgfk2JXiDwf35e@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Red Wings @ Chiefs Red Wings @ Chiefs

Follow on MiLB First Pitch  https //stza.co/+vKo2-2$

Shop  https //stza.co/+vKo2-1x

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Red Wings @ Chiefs
END:VALARM
DTSTART:20180427T223500Z
DTEND:20180428T013500Z
UID:hi7Jq_NoyTvgfk2JXiDwf35e@stanza.co
SUMMARY:Red Wings @ Chiefs
DESCRIPTION:Red Wings @ Chiefs\n\nFollow on MiLB First Pitch: https://stza.co/+vKo2-2$\n\nShop: https://stza.co/+vKo2-1x\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144635Z
LAST-MODIFIED:20180213T144635Z
TRANSP:OPAQUE
END:VEVENT
* Red Wings @ Chiefs
<2018-04-28 Sat 12:05-15:05>
:PROPERTIES:
:ID:       fk4hzX5eMzgXKxJuFMCWExey@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Red Wings @ Chiefs Red Wings @ Chiefs

Follow on MiLB First Pitch  https //stza.co/+vKo3-3n

Shop  https //stza.co/+vKo3-3D

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Red Wings @ Chiefs
END:VALARM
DTSTART:20180428T170500Z
DTEND:20180428T200500Z
UID:fk4hzX5eMzgXKxJuFMCWExey@stanza.co
SUMMARY:Red Wings @ Chiefs
DESCRIPTION:Red Wings @ Chiefs\n\nFollow on MiLB First Pitch: https://stza.co/+vKo3-3n\n\nShop: https://stza.co/+vKo3-3D\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144635Z
LAST-MODIFIED:20180213T144635Z
TRANSP:OPAQUE
END:VEVENT
* Red Wings @ Chiefs
<2018-04-29 Sun 12:05-15:05>
:PROPERTIES:
:ID:       LrFWZDKgpm75Kb6_yq-teOH8@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Red Wings @ Chiefs Red Wings @ Chiefs

Follow on MiLB First Pitch  https //stza.co/+vKo4-2_

Shop  https //stza.co/+vKo4-1B

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Red Wings @ Chiefs
END:VALARM
DTSTART:20180429T170500Z
DTEND:20180429T200500Z
UID:LrFWZDKgpm75Kb6_yq-teOH8@stanza.co
SUMMARY:Red Wings @ Chiefs
DESCRIPTION:Red Wings @ Chiefs\n\nFollow on MiLB First Pitch: https://stza.co/+vKo4-2_\n\nShop: https://stza.co/+vKo4-1B\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144635Z
LAST-MODIFIED:20180213T144635Z
TRANSP:OPAQUE
END:VEVENT
* Red Wings @ Red Sox
<2018-04-30 Mon 17:15-20:15>
:PROPERTIES:
:ID:       ihT3sF3aofRb3xG9O68xlhON@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Red Wings @ Red Sox Red Wings @ Red Sox

Buy tickets here  https //stza.co/~vKlz

Follow on MiLB First Pitch  https //stza.co/+vKlz-2o

Shop  https //stza.co/+vKlz-2L

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Red Wings @ Red Sox
END:VALARM
DTSTART:20180430T221500Z
DTEND:20180501T011500Z
UID:ihT3sF3aofRb3xG9O68xlhON@stanza.co
SUMMARY:Red Wings @ Red Sox
DESCRIPTION:Red Wings @ Red Sox\n\nBuy tickets here: https://stza.co/~vKlz\n\nFollow on MiLB First Pitch: https://stza.co/+vKlz-2o\n\nShop: https://stza.co/+vKlz-2L\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144635Z
LAST-MODIFIED:20180213T144635Z
TRANSP:OPAQUE
END:VEVENT
* Red Wings @ Red Sox
<2018-05-01 Tue 17:15-20:15>
:PROPERTIES:
:ID:       LrOQmR3KNQr1xO3aXygKEKHV@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Red Wings @ Red Sox Red Wings @ Red Sox

Buy tickets here  https //stza.co/~vKlA

Follow on MiLB First Pitch  https //stza.co/+vKlA-12

Shop  https //stza.co/+vKlA-W

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Red Wings @ Red Sox
END:VALARM
DTSTART:20180501T221500Z
DTEND:20180502T011500Z
UID:LrOQmR3KNQr1xO3aXygKEKHV@stanza.co
SUMMARY:Red Wings @ Red Sox
DESCRIPTION:Red Wings @ Red Sox\n\nBuy tickets here: https://stza.co/~vKlA\n\nFollow on MiLB First Pitch: https://stza.co/+vKlA-12\n\nShop: https://stza.co/+vKlA-W\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144635Z
LAST-MODIFIED:20180213T144635Z
TRANSP:OPAQUE
END:VEVENT
* Red Wings @ Red Sox
<2018-05-02 Wed 11:05-14:05>
:PROPERTIES:
:ID:       LbE51-OcgL7pWP4_A_FdCgtE@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Red Wings @ Red Sox Red Wings @ Red Sox

Buy tickets here  https //stza.co/~vKlB

Follow on MiLB First Pitch  https //stza.co/+vKlB-K

Shop  https //stza.co/+vKlB-27

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Red Wings @ Red Sox
END:VALARM
DTSTART:20180502T160500Z
DTEND:20180502T190500Z
UID:LbE51-OcgL7pWP4_A_FdCgtE@stanza.co
SUMMARY:Red Wings @ Red Sox
DESCRIPTION:Red Wings @ Red Sox\n\nBuy tickets here: https://stza.co/~vKlB\n\nFollow on MiLB First Pitch: https://stza.co/+vKlB-K\n\nShop: https://stza.co/+vKlB-27\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144635Z
LAST-MODIFIED:20180213T144635Z
TRANSP:OPAQUE
END:VEVENT
* Red Wings vs. IronPigs
<2018-05-03 Thu 18:05-21:05>
:PROPERTIES:
:ID:       gChiBPmNI0QVFM746QvAXB-b@stanza.co
:LOCATION: College Thursdays
:STATUS:   CONFIRMED
:END:

Red Wings vs. IronPigs Every Thursday - college students with a valid college ID can get a reserved ticket AND $5 Diamond Dollars for ONLY $10!

Follow on MiLB First Pitch  https //stza.co/+vKm3-3P

Shop  https //stza.co/+vKm3-2v

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Red Wings vs. IronPigs
END:VALARM
DTSTART:20180503T230500Z
DTEND:20180504T020500Z
UID:gChiBPmNI0QVFM746QvAXB-b@stanza.co
SUMMARY:Red Wings vs. IronPigs
DESCRIPTION:Every Thursday - college students with a valid college ID can get a reserved ticket AND $5 Diamond Dollars for ONLY $10!\n\nFollow on MiLB First Pitch: https://stza.co/+vKm3-3P\n\nShop: https://stza.co/+vKm3-2v\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:College Thursdays
STATUS:CONFIRMED
CREATED:20180213T144635Z
LAST-MODIFIED:20180213T144635Z
TRANSP:OPAQUE
END:VEVENT
* Red Wings vs. IronPigs
<2018-05-04 Fri 18:05-21:05>
:PROPERTIES:
:ID:       TGb7Po0LzBk7MYEEjC9hkacP@stanza.co
:LOCATION: May the force be with you! Come check out Stars Wars Night at the park
:STATUS:   CONFIRMED
:END:

Red Wings vs. IronPigs May The 4th Be With You! Come out and see all your favorite Star Wars characters from the Garrison Excelsior 501st Legion. As always the Wings will wear specialty jerseys with proceeds benefiting the Hillside Family of Agencies.

Follow on MiLB First Pitch  https //stza.co/+vKm6-S

Shop  https //stza.co/+vKm6-1q

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Red Wings vs. IronPigs
END:VALARM
DTSTART:20180504T230500Z
DTEND:20180505T020500Z
UID:TGb7Po0LzBk7MYEEjC9hkacP@stanza.co
SUMMARY:Red Wings vs. IronPigs
DESCRIPTION:May The 4th Be With You! Come out and see all your favorite Star Wars characters from the Garrison Excelsior 501st Legion. As always the Wings will wear specialty jerseys with proceeds benefiting the Hillside Family of Agencies.\n\nFollow on MiLB First Pitch: https://stza.co/+vKm6-S\n\nShop: https://stza.co/+vKm6-1q\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:May the force be with you! Come check out Stars Wars Night at the park
STATUS:CONFIRMED
CREATED:20180213T144635Z
LAST-MODIFIED:20180213T144635Z
TRANSP:OPAQUE
END:VEVENT
* Red Wings vs. IronPigs
<2018-05-05 Sat 12:05-15:05>
:PROPERTIES:
:ID:       7yxbJq-6RutSm8vNjdZbGfsF@stanza.co
:LOCATION: Clean Sweep
:STATUS:   CONFIRMED
:END:

Red Wings vs. IronPigs The Red Wings and the City of Rochester have teamed up once again for Clean Sweep 2018! Fans who volunteer to help clean up the city in the morning will receive a FREE game ticket for that afternoon, hot dog and t-shirt.

Follow on MiLB First Pitch  https //stza.co/+vKm8-2m

Shop  https //stza.co/+vKm8-9

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Red Wings vs. IronPigs
END:VALARM
DTSTART:20180505T170500Z
DTEND:20180505T200500Z
UID:7yxbJq-6RutSm8vNjdZbGfsF@stanza.co
SUMMARY:Red Wings vs. IronPigs
DESCRIPTION:The Red Wings and the City of Rochester have teamed up once again for Clean Sweep 2018! Fans who volunteer to help clean up the city in the morning will receive a FREE game ticket for that afternoon, hot dog and t-shirt.\n\nFollow on MiLB First Pitch: https://stza.co/+vKm8-2m\n\nShop: https://stza.co/+vKm8-9\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Clean Sweep
STATUS:CONFIRMED
CREATED:20180213T144635Z
LAST-MODIFIED:20180213T144635Z
TRANSP:OPAQUE
END:VEVENT
* Red Wings vs. IronPigs
<2018-05-06 Sun 12:05-15:05>
:PROPERTIES:
:ID:       CE-P3WVC-Got5zrIQJV0jx6r@stanza.co
:LOCATION: Bark in the Park
:STATUS:   CONFIRMED
:END:

Red Wings vs. IronPigs NEW in 2018  Fans with dogs will be able to participate in a pre-game dog parade on the field. Also, the third base grass berm will be open to all dogs and their owners.

Every Sunday kids 12 and under can run the bases with Red Wings mascots Spikes and Mittsy!

Follow on MiLB First Pitch  https //stza.co/+vKma-3o

Shop  https //stza.co/+vKma-1m

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Red Wings vs. IronPigs
END:VALARM
DTSTART:20180506T170500Z
DTEND:20180506T200500Z
UID:CE-P3WVC-Got5zrIQJV0jx6r@stanza.co
SUMMARY:Red Wings vs. IronPigs
DESCRIPTION:NEW in 2018: Fans with dogs will be able to participate in a pre-game dog parade on the field. Also, the third base grass berm will be open to all dogs and their owners.\n\nEvery Sunday kids 12 and under can run the bases with Red Wings mascots Spikes and Mittsy!\n\nFollow on MiLB First Pitch: https://stza.co/+vKma-3o\n\nShop: https://stza.co/+vKma-1m\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Bark in the Park
STATUS:CONFIRMED
CREATED:20180213T144635Z
LAST-MODIFIED:20180213T144635Z
TRANSP:OPAQUE
END:VEVENT
* Red Wings @ Bisons
<2018-05-07 Mon 17:05-20:05>
:PROPERTIES:
:ID:       x_2bjq1QlH6xqXIBjSdVv98P@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Red Wings @ Bisons Red Wings @ Bisons

Follow on MiLB First Pitch  https //stza.co/+vKk$-M

Shop  https //stza.co/+vKk$-2M

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Red Wings @ Bisons
END:VALARM
DTSTART:20180507T220500Z
DTEND:20180508T010500Z
UID:x_2bjq1QlH6xqXIBjSdVv98P@stanza.co
SUMMARY:Red Wings @ Bisons
DESCRIPTION:Red Wings @ Bisons\n\nFollow on MiLB First Pitch: https://stza.co/+vKk$-M\n\nShop: https://stza.co/+vKk$-2M\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144635Z
LAST-MODIFIED:20180213T144635Z
TRANSP:OPAQUE
END:VEVENT
* Red Wings @ Bisons
<2018-05-08 Tue 17:05-20:05>
:PROPERTIES:
:ID:       1lsYsn2qt_Ty975wUFOURRH0@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Red Wings @ Bisons Red Wings @ Bisons

Follow on MiLB First Pitch  https //stza.co/+vKl0-2j

Shop  https //stza.co/+vKl0-2F

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Red Wings @ Bisons
END:VALARM
DTSTART:20180508T220500Z
DTEND:20180509T010500Z
UID:1lsYsn2qt_Ty975wUFOURRH0@stanza.co
SUMMARY:Red Wings @ Bisons
DESCRIPTION:Red Wings @ Bisons\n\nFollow on MiLB First Pitch: https://stza.co/+vKl0-2j\n\nShop: https://stza.co/+vKl0-2F\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144635Z
LAST-MODIFIED:20180213T144635Z
TRANSP:OPAQUE
END:VEVENT
* Red Wings @ Bisons
<2018-05-09 Wed 12:05-15:05>
:PROPERTIES:
:ID:       Kpr5kJOra7VvS9ILXIsmmgqT@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Red Wings @ Bisons Red Wings @ Bisons

Follow on MiLB First Pitch  https //stza.co/+vKl1-W

Shop  https //stza.co/+vKl1-1G

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Red Wings @ Bisons
END:VALARM
DTSTART:20180509T170500Z
DTEND:20180509T200500Z
UID:Kpr5kJOra7VvS9ILXIsmmgqT@stanza.co
SUMMARY:Red Wings @ Bisons
DESCRIPTION:Red Wings @ Bisons\n\nFollow on MiLB First Pitch: https://stza.co/+vKl1-W\n\nShop: https://stza.co/+vKl1-1G\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144635Z
LAST-MODIFIED:20180213T144635Z
TRANSP:OPAQUE
END:VEVENT
* Red Wings @ RailRiders
<2018-05-10 Thu 17:35-20:35>
:PROPERTIES:
:ID:       qVbRbEe5oV79VADiwaNQH7po@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Red Wings @ RailRiders Red Wings @ RailRiders

Follow on MiLB First Pitch  https //stza.co/+vKnT-v

Shop  https //stza.co/+vKnT-3g

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Red Wings @ RailRiders
END:VALARM
DTSTART:20180510T223500Z
DTEND:20180511T013500Z
UID:qVbRbEe5oV79VADiwaNQH7po@stanza.co
SUMMARY:Red Wings @ RailRiders
DESCRIPTION:Red Wings @ RailRiders\n\nFollow on MiLB First Pitch: https://stza.co/+vKnT-v\n\nShop: https://stza.co/+vKnT-3g\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144635Z
LAST-MODIFIED:20180213T144635Z
TRANSP:OPAQUE
END:VEVENT
* Red Wings @ RailRiders
<2018-05-11 Fri 17:35-20:35>
:PROPERTIES:
:ID:       yhCY2STK35fcIBYqKWKqV_-Q@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Red Wings @ RailRiders Red Wings @ RailRiders

Follow on MiLB First Pitch  https //stza.co/+vKnU-X

Shop  https //stza.co/+vKnU-B

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Red Wings @ RailRiders
END:VALARM
DTSTART:20180511T223500Z
DTEND:20180512T013500Z
UID:yhCY2STK35fcIBYqKWKqV_-Q@stanza.co
SUMMARY:Red Wings @ RailRiders
DESCRIPTION:Red Wings @ RailRiders\n\nFollow on MiLB First Pitch: https://stza.co/+vKnU-X\n\nShop: https://stza.co/+vKnU-B\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144635Z
LAST-MODIFIED:20180213T144635Z
TRANSP:OPAQUE
END:VEVENT
* Red Wings @ RailRiders
<2018-05-12 Sat 15:05-18:05>
:PROPERTIES:
:ID:       sNyrt_P4E7jnZt4-kjI1NAD3@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Red Wings @ RailRiders Red Wings @ RailRiders

Follow on MiLB First Pitch  https //stza.co/+vKnV-r

Shop  https //stza.co/+vKnV-d

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Red Wings @ RailRiders
END:VALARM
DTSTART:20180512T200500Z
DTEND:20180512T230500Z
UID:sNyrt_P4E7jnZt4-kjI1NAD3@stanza.co
SUMMARY:Red Wings @ RailRiders
DESCRIPTION:Red Wings @ RailRiders\n\nFollow on MiLB First Pitch: https://stza.co/+vKnV-r\n\nShop: https://stza.co/+vKnV-d\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144635Z
LAST-MODIFIED:20180213T144635Z
TRANSP:OPAQUE
END:VEVENT
* Red Wings @ RailRiders
<2018-05-13 Sun 12:05-15:05>
:PROPERTIES:
:ID:       aVP2N9Dth17pFPAT4znLfBEz@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Red Wings @ RailRiders Red Wings @ RailRiders

Follow on MiLB First Pitch  https //stza.co/+vKnW-32

Shop  https //stza.co/+vKnW-3e

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Red Wings @ RailRiders
END:VALARM
DTSTART:20180513T170500Z
DTEND:20180513T200500Z
UID:aVP2N9Dth17pFPAT4znLfBEz@stanza.co
SUMMARY:Red Wings @ RailRiders
DESCRIPTION:Red Wings @ RailRiders\n\nFollow on MiLB First Pitch: https://stza.co/+vKnW-32\n\nShop: https://stza.co/+vKnW-3e\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144635Z
LAST-MODIFIED:20180213T144635Z
TRANSP:OPAQUE
END:VEVENT
* Red Wings vs. Chiefs
<2018-05-15 Tue 18:05-21:05>
:PROPERTIES:
:ID:       4GSkWypYIUd5Dg0LVLsQIiRe@stanza.co
:LOCATION: T-shirt Tuesday Giveaway
:STATUS:   CONFIRMED
:END:

Red Wings vs. Chiefs The first 500 fans in attendance will receive a FREE t-shirt.

Follow on MiLB First Pitch  https //stza.co/+vKmc-3S

Shop  https //stza.co/+vKmc-1U

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Red Wings vs. Chiefs
END:VALARM
DTSTART:20180515T230500Z
DTEND:20180516T020500Z
UID:4GSkWypYIUd5Dg0LVLsQIiRe@stanza.co
SUMMARY:Red Wings vs. Chiefs
DESCRIPTION:The first 500 fans in attendance will receive a FREE t-shirt.\n\nFollow on MiLB First Pitch: https://stza.co/+vKmc-3S\n\nShop: https://stza.co/+vKmc-1U\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:T-shirt Tuesday Giveaway
STATUS:CONFIRMED
CREATED:20180213T144635Z
LAST-MODIFIED:20180213T144635Z
TRANSP:OPAQUE
END:VEVENT
* Red Wings vs. Chiefs
<2018-05-16 Wed 18:05-21:05>
:PROPERTIES:
:ID:       aYQe_xIGVpojyWkBgXket3sC@stanza.co
:LOCATION: $1 Wednesdays
:STATUS:   CONFIRMED
:END:

Red Wings vs. Chiefs Every Wednesday - excluding Wednesday, July 4th - enjoy ONE DOLLAR hot dogs, peanuts, cracker jacks and chips!

Follow on MiLB First Pitch  https //stza.co/+vKme-2k

Shop  https //stza.co/+vKme-2f

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Red Wings vs. Chiefs
END:VALARM
DTSTART:20180516T230500Z
DTEND:20180517T020500Z
UID:aYQe_xIGVpojyWkBgXket3sC@stanza.co
SUMMARY:Red Wings vs. Chiefs
DESCRIPTION:Every Wednesday - excluding Wednesday, July 4th - enjoy ONE DOLLAR hot dogs, peanuts, cracker jacks and chips!\n\nFollow on MiLB First Pitch: https://stza.co/+vKme-2k\n\nShop: https://stza.co/+vKme-2f\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:$1 Wednesdays
STATUS:CONFIRMED
CREATED:20180213T144635Z
LAST-MODIFIED:20180213T144635Z
TRANSP:OPAQUE
END:VEVENT
* Red Wings vs. Chiefs
<2018-05-17 Thu 10:05-13:05>
:PROPERTIES:
:ID:       4kqBuQMmHlZBKq6EjoVXz5E6@stanza.co
:LOCATION: Education Day
:STATUS:   CONFIRMED
:END:

Red Wings vs. Chiefs Bring out your school group for this special 11 05 am start time. To bring your group out contact Eric Friedman at 585-454-1001 ext. 3057.

Every Thursday - college students with a valid college ID can get a reserved ticket AND $5 Diamond Dollars for ONLY $10!

Follow on MiLB First Pitch  https //stza.co/+vKmf-E

Shop  https //stza.co/+vKmf-r

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Red Wings vs. Chiefs
END:VALARM
DTSTART:20180517T150500Z
DTEND:20180517T180500Z
UID:4kqBuQMmHlZBKq6EjoVXz5E6@stanza.co
SUMMARY:Red Wings vs. Chiefs
DESCRIPTION:Bring out your school group for this special 11:05 am start time. To bring your group out contact Eric Friedman at 585-454-1001 ext. 3057.\n\nEvery Thursday - college students with a valid college ID can get a reserved ticket AND $5 Diamond Dollars for ONLY $10!\n\nFollow on MiLB First Pitch: https://stza.co/+vKmf-E\n\nShop: https://stza.co/+vKmf-r\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Education Day
STATUS:CONFIRMED
CREATED:20180213T144635Z
LAST-MODIFIED:20180213T144635Z
TRANSP:OPAQUE
END:VEVENT
* Red Wings vs. Red Sox
<2018-05-18 Fri 18:05-21:05>
:PROPERTIES:
:ID:       W8v2uA6h4tagCD6Q-3vHvvkg@stanza.co
:LOCATION: Renew Your Vows Night
:STATUS:   CONFIRMED
:END:

Red Wings vs. Red Sox Want to renew your vows at the ballpark? Now is your chance! More details coming soon.

Follow on MiLB First Pitch  https //stza.co/+vKmi-P

Shop  https //stza.co/+vKmi-2B

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Red Wings vs. Red Sox
END:VALARM
DTSTART:20180518T230500Z
DTEND:20180519T020500Z
UID:W8v2uA6h4tagCD6Q-3vHvvkg@stanza.co
SUMMARY:Red Wings vs. Red Sox
DESCRIPTION:Want to renew your vows at the ballpark? Now is your chance! More details coming soon.\n\nFollow on MiLB First Pitch: https://stza.co/+vKmi-P\n\nShop: https://stza.co/+vKmi-2B\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Renew Your Vows Night
STATUS:CONFIRMED
CREATED:20180213T144635Z
LAST-MODIFIED:20180213T144635Z
TRANSP:OPAQUE
END:VEVENT
* Red Wings vs. Red Sox
<2018-05-19 Sat 18:05-21:05>
:PROPERTIES:
:ID:       uIRt0XyyiC5i0S3YTKXeMhnE@stanza.co
:LOCATION: Stick around after the game for some spectacular fireworks!
:STATUS:   CONFIRMED
:END:

Red Wings vs. Red Sox Stick around after the game for the first fireworks show of the season!

Follow on MiLB First Pitch  https //stza.co/+vKmk-Z

Shop  https //stza.co/+vKmk-10

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Red Wings vs. Red Sox
END:VALARM
DTSTART:20180519T230500Z
DTEND:20180520T020500Z
UID:uIRt0XyyiC5i0S3YTKXeMhnE@stanza.co
SUMMARY:Red Wings vs. Red Sox
DESCRIPTION:Stick around after the game for the first fireworks show of the season!\n\nFollow on MiLB First Pitch: https://stza.co/+vKmk-Z\n\nShop: https://stza.co/+vKmk-10\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stick around after the game for some spectacular fireworks!
STATUS:CONFIRMED
CREATED:20180213T144635Z
LAST-MODIFIED:20180213T144635Z
TRANSP:OPAQUE
END:VEVENT
* Red Wings vs. Red Sox
<2018-05-20 Sun 12:05-15:05>
:PROPERTIES:
:ID:       _LkbA6eYn_HrUwMl8XTuaHvC@stanza.co
:LOCATION: Kids Run the Bases with Spikes and Mittsy
:STATUS:   CONFIRMED
:END:

Red Wings vs. Red Sox Every Sunday kids 12 and under can run the bases with Red Wings mascots Spikes and Mittsy!

Follow on MiLB First Pitch  https //stza.co/+vKml-3Q

Shop  https //stza.co/+vKml-$

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Red Wings vs. Red Sox
END:VALARM
DTSTART:20180520T170500Z
DTEND:20180520T200500Z
UID:_LkbA6eYn_HrUwMl8XTuaHvC@stanza.co
SUMMARY:Red Wings vs. Red Sox
DESCRIPTION:Every Sunday kids 12 and under can run the bases with Red Wings mascots Spikes and Mittsy!\n\nFollow on MiLB First Pitch: https://stza.co/+vKml-3Q\n\nShop: https://stza.co/+vKml-$\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Kids Run the Bases with Spikes and Mittsy
STATUS:CONFIRMED
CREATED:20180213T144635Z
LAST-MODIFIED:20180213T144635Z
TRANSP:OPAQUE
END:VEVENT
* Red Wings @ IronPigs
<2018-05-21 Mon 18:05-21:05>
:PROPERTIES:
:ID:       rGqrja62N53zeiTT0CkKv5ZU@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Red Wings @ IronPigs Red Wings @ IronPigs

Follow on MiLB First Pitch  https //stza.co/+vKlm-3o

Shop  https //stza.co/+vKlm-1a

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Red Wings @ IronPigs
END:VALARM
DTSTART:20180521T230500Z
DTEND:20180522T020500Z
UID:rGqrja62N53zeiTT0CkKv5ZU@stanza.co
SUMMARY:Red Wings @ IronPigs
DESCRIPTION:Red Wings @ IronPigs\n\nFollow on MiLB First Pitch: https://stza.co/+vKlm-3o\n\nShop: https://stza.co/+vKlm-1a\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144635Z
LAST-MODIFIED:20180213T144635Z
TRANSP:OPAQUE
END:VEVENT
* Red Wings @ IronPigs
<2018-05-22 Tue 18:05-21:05>
:PROPERTIES:
:ID:       pJM-19Gbm_KjoWj-Yj75TNc0@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Red Wings @ IronPigs Red Wings @ IronPigs

Follow on MiLB First Pitch  https //stza.co/+vKln-1q

Shop  https //stza.co/+vKln-3l

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Red Wings @ IronPigs
END:VALARM
DTSTART:20180522T230500Z
DTEND:20180523T020500Z
UID:pJM-19Gbm_KjoWj-Yj75TNc0@stanza.co
SUMMARY:Red Wings @ IronPigs
DESCRIPTION:Red Wings @ IronPigs\n\nFollow on MiLB First Pitch: https://stza.co/+vKln-1q\n\nShop: https://stza.co/+vKln-3l\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144635Z
LAST-MODIFIED:20180213T144635Z
TRANSP:OPAQUE
END:VEVENT
* Red Wings @ IronPigs
<2018-05-23 Wed 18:05-21:05>
:PROPERTIES:
:ID:       x4pea_RF-kWBAWwrezVZdoSo@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Red Wings @ IronPigs Red Wings @ IronPigs

Follow on MiLB First Pitch  https //stza.co/+vKlo-3F

Shop  https //stza.co/+vKlo-m

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Red Wings @ IronPigs
END:VALARM
DTSTART:20180523T230500Z
DTEND:20180524T020500Z
UID:x4pea_RF-kWBAWwrezVZdoSo@stanza.co
SUMMARY:Red Wings @ IronPigs
DESCRIPTION:Red Wings @ IronPigs\n\nFollow on MiLB First Pitch: https://stza.co/+vKlo-3F\n\nShop: https://stza.co/+vKlo-m\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144635Z
LAST-MODIFIED:20180213T144635Z
TRANSP:OPAQUE
END:VEVENT
* Red Wings @ IronPigs
<2018-05-24 Thu 18:05-21:05>
:PROPERTIES:
:ID:       LKQGrsAZC2Rv0nIRTkI9J2Lb@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Red Wings @ IronPigs Red Wings @ IronPigs

Follow on MiLB First Pitch  https //stza.co/+vKlp-3I

Shop  https //stza.co/+vKlp-12

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Red Wings @ IronPigs
END:VALARM
DTSTART:20180524T230500Z
DTEND:20180525T020500Z
UID:LKQGrsAZC2Rv0nIRTkI9J2Lb@stanza.co
SUMMARY:Red Wings @ IronPigs
DESCRIPTION:Red Wings @ IronPigs\n\nFollow on MiLB First Pitch: https://stza.co/+vKlp-3I\n\nShop: https://stza.co/+vKlp-12\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144635Z
LAST-MODIFIED:20180213T144635Z
TRANSP:OPAQUE
END:VEVENT
* Red Wings vs. Bisons
<2018-05-25 Fri 18:05-21:05>
:PROPERTIES:
:ID:       LwND3CAHHRMeu1H3NPbaLhUJ@stanza.co
:LOCATION: Stick around after the game for some spectacular fireworks!
:STATUS:   CONFIRMED
:END:

Red Wings vs. Bisons Want to laugh? Be sure to come out for our 1st annual Comedy Night! More details to be announced at a later date.



Follow on MiLB First Pitch  https //stza.co/+vKmn-1e

Shop  https //stza.co/+vKmn-2_

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Red Wings vs. Bisons
END:VALARM
DTSTART:20180525T230500Z
DTEND:20180526T020500Z
UID:LwND3CAHHRMeu1H3NPbaLhUJ@stanza.co
SUMMARY:Red Wings vs. Bisons
DESCRIPTION:Want to laugh? Be sure to come out for our 1st annual Comedy Night! More details to be announced at a later date.\n\n\n\nFollow on MiLB First Pitch: https://stza.co/+vKmn-1e\n\nShop: https://stza.co/+vKmn-2_\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stick around after the game for some spectacular fireworks!
STATUS:CONFIRMED
CREATED:20180213T144635Z
LAST-MODIFIED:20180213T144635Z
TRANSP:OPAQUE
END:VEVENT
* Red Wings vs. Bisons
<2018-05-26 Sat 18:05-21:05>
:PROPERTIES:
:ID:       y_gxRfIQVLRnJmhSlOd7gVqA@stanza.co
:LOCATION: Stick around after the game for some spectacular fireworks!
:STATUS:   CONFIRMED
:END:

Red Wings vs. Bisons Details coming soon...



Follow on MiLB First Pitch  https //stza.co/+vKmq-3v

Shop  https //stza.co/+vKmq-29

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Red Wings vs. Bisons
END:VALARM
DTSTART:20180526T230500Z
DTEND:20180527T020500Z
UID:y_gxRfIQVLRnJmhSlOd7gVqA@stanza.co
SUMMARY:Red Wings vs. Bisons
DESCRIPTION:Details coming soon...\n\n\n\nFollow on MiLB First Pitch: https://stza.co/+vKmq-3v\n\nShop: https://stza.co/+vKmq-29\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stick around after the game for some spectacular fireworks!
STATUS:CONFIRMED
CREATED:20180213T144635Z
LAST-MODIFIED:20180213T144635Z
TRANSP:OPAQUE
END:VEVENT
* Red Wings vs. Bisons
<2018-05-27 Sun 12:05-15:05>
:PROPERTIES:
:ID:       s6teixAfHiXxt14g6iELJP82@stanza.co
:LOCATION: Bark in the Park
:STATUS:   CONFIRMED
:END:

Red Wings vs. Bisons NEW in 2018  Fans with dogs will be able to participate in a pre-game dog parade on the field. Also, the third base grass berm will be open to all dogs and their owners.

Every Sunday kids 12 and under can run the bases with Red Wings mascots Spikes and Mittsy!

Follow on MiLB First Pitch  https //stza.co/+vKms-3q

Shop  https //stza.co/+vKms-2l

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Red Wings vs. Bisons
END:VALARM
DTSTART:20180527T170500Z
DTEND:20180527T200500Z
UID:s6teixAfHiXxt14g6iELJP82@stanza.co
SUMMARY:Red Wings vs. Bisons
DESCRIPTION:NEW in 2018: Fans with dogs will be able to participate in a pre-game dog parade on the field. Also, the third base grass berm will be open to all dogs and their owners.\n\nEvery Sunday kids 12 and under can run the bases with Red Wings mascots Spikes and Mittsy!\n\nFollow on MiLB First Pitch: https://stza.co/+vKms-3q\n\nShop: https://stza.co/+vKms-2l\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Bark in the Park
STATUS:CONFIRMED
CREATED:20180213T144635Z
LAST-MODIFIED:20180213T144635Z
TRANSP:OPAQUE
END:VEVENT
* Red Wings vs. Bisons
<2018-05-28 Mon 12:05-15:05>
:PROPERTIES:
:ID:       vupfVhs4VsTF0bOSISU-3TtC@stanza.co
:LOCATION: Memorial Day Celebration ft. $5 tickets & 50-cent hot dogs
:STATUS:   CONFIRMED
:END:

Red Wings vs. Bisons Spend your Memorial Day with us at Frontier Field. All tickets are just $5 and  hot dogs are only 50-cents!



Every Monday home game the first 500 kids get a FREE hot dog, snack item and soda!

Follow on MiLB First Pitch  https //stza.co/+vKmt-1

Shop  https //stza.co/+vKmt-2w

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Red Wings vs. Bisons
END:VALARM
DTSTART:20180528T170500Z
DTEND:20180528T200500Z
UID:vupfVhs4VsTF0bOSISU-3TtC@stanza.co
SUMMARY:Red Wings vs. Bisons
DESCRIPTION:Spend your Memorial Day with us at Frontier Field. All tickets are just $5 and  hot dogs are only 50-cents!\n\n\n\nEvery Monday home game the first 500 kids get a FREE hot dog, snack item and soda!\n\nFollow on MiLB First Pitch: https://stza.co/+vKmt-1\n\nShop: https://stza.co/+vKmt-2w\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Memorial Day Celebration ft. $5 tickets & 50-cent hot dogs
STATUS:CONFIRMED
CREATED:20180213T144635Z
LAST-MODIFIED:20180213T144635Z
TRANSP:OPAQUE
END:VEVENT
* Red Wings @ Bulls
<2018-05-29 Tue 18:05-21:05>
:PROPERTIES:
:ID:       tXkYWPcUx1mWlzhu4Hyg7y7a@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Red Wings @ Bulls Red Wings @ Bulls

Follow on MiLB First Pitch  https //stza.co/+vKlc-36

Shop  https //stza.co/+vKlc-2V

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Red Wings @ Bulls
END:VALARM
DTSTART:20180529T230500Z
DTEND:20180530T020500Z
UID:tXkYWPcUx1mWlzhu4Hyg7y7a@stanza.co
SUMMARY:Red Wings @ Bulls
DESCRIPTION:Red Wings @ Bulls\n\nFollow on MiLB First Pitch: https://stza.co/+vKlc-36\n\nShop: https://stza.co/+vKlc-2V\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144635Z
LAST-MODIFIED:20180213T144635Z
TRANSP:OPAQUE
END:VEVENT
* Red Wings @ Bulls
<2018-05-30 Wed 12:05-15:05>
:PROPERTIES:
:ID:       b37878khKkmbZtgbnrxPxdR0@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Red Wings @ Bulls Red Wings @ Bulls

Follow on MiLB First Pitch  https //stza.co/+vKld-O

Shop  https //stza.co/+vKld-1r

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Red Wings @ Bulls
END:VALARM
DTSTART:20180530T170500Z
DTEND:20180530T200500Z
UID:b37878khKkmbZtgbnrxPxdR0@stanza.co
SUMMARY:Red Wings @ Bulls
DESCRIPTION:Red Wings @ Bulls\n\nFollow on MiLB First Pitch: https://stza.co/+vKld-O\n\nShop: https://stza.co/+vKld-1r\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144635Z
LAST-MODIFIED:20180213T144635Z
TRANSP:OPAQUE
END:VEVENT
* Red Wings @ Bulls
<2018-05-31 Thu 18:05-21:05>
:PROPERTIES:
:ID:       Xkj34ZI6A-ncWLwSwfPc5Nwb@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Red Wings @ Bulls Red Wings @ Bulls

Follow on MiLB First Pitch  https //stza.co/+vKle-30

Shop  https //stza.co/+vKle-H

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Red Wings @ Bulls
END:VALARM
DTSTART:20180531T230500Z
DTEND:20180601T020500Z
UID:Xkj34ZI6A-ncWLwSwfPc5Nwb@stanza.co
SUMMARY:Red Wings @ Bulls
DESCRIPTION:Red Wings @ Bulls\n\nFollow on MiLB First Pitch: https://stza.co/+vKle-30\n\nShop: https://stza.co/+vKle-H\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144635Z
LAST-MODIFIED:20180213T144635Z
TRANSP:OPAQUE
END:VEVENT
* Red Wings @ Tides
<2018-06-01 Fri 18:05-21:05>
:PROPERTIES:
:ID:       9Ky_ii3HpaMo4-vJJYTctz0d@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Red Wings @ Tides Red Wings @ Tides

Follow on MiLB First Pitch  https //stza.co/+vKlw-1H

Shop  https //stza.co/+vKlw-2w

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Red Wings @ Tides
END:VALARM
DTSTART:20180601T230500Z
DTEND:20180602T020500Z
UID:9Ky_ii3HpaMo4-vJJYTctz0d@stanza.co
SUMMARY:Red Wings @ Tides
DESCRIPTION:Red Wings @ Tides\n\nFollow on MiLB First Pitch: https://stza.co/+vKlw-1H\n\nShop: https://stza.co/+vKlw-2w\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144635Z
LAST-MODIFIED:20180213T144635Z
TRANSP:OPAQUE
END:VEVENT
* Red Wings @ Tides
<2018-06-02 Sat 18:05-21:05>
:PROPERTIES:
:ID:       CuQQwMQNmyzQTTuWCgX8m61s@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Red Wings @ Tides Red Wings @ Tides

Follow on MiLB First Pitch  https //stza.co/+vKlx-1a

Shop  https //stza.co/+vKlx-2z

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Red Wings @ Tides
END:VALARM
DTSTART:20180602T230500Z
DTEND:20180603T020500Z
UID:CuQQwMQNmyzQTTuWCgX8m61s@stanza.co
SUMMARY:Red Wings @ Tides
DESCRIPTION:Red Wings @ Tides\n\nFollow on MiLB First Pitch: https://stza.co/+vKlx-1a\n\nShop: https://stza.co/+vKlx-2z\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144635Z
LAST-MODIFIED:20180213T144635Z
TRANSP:OPAQUE
END:VEVENT
* Red Wings @ Tides
<2018-06-03 Sun 12:05-15:05>
:PROPERTIES:
:ID:       eUqYgeHHP0pr71Ej2IADsCMW@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Red Wings @ Tides Red Wings @ Tides

Follow on MiLB First Pitch  https //stza.co/+vKly-F

Shop  https //stza.co/+vKly-2M

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Red Wings @ Tides
END:VALARM
DTSTART:20180603T170500Z
DTEND:20180603T200500Z
UID:eUqYgeHHP0pr71Ej2IADsCMW@stanza.co
SUMMARY:Red Wings @ Tides
DESCRIPTION:Red Wings @ Tides\n\nFollow on MiLB First Pitch: https://stza.co/+vKly-F\n\nShop: https://stza.co/+vKly-2M\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144635Z
LAST-MODIFIED:20180213T144635Z
TRANSP:OPAQUE
END:VEVENT
* Red Wings vs. Indians
<2018-06-05 Tue 18:05-21:05>
:PROPERTIES:
:ID:       XJ94-Go0FuK7M92BYggP71Of@stanza.co
:LOCATION: T-shirt Tuesday Giveaway
:STATUS:   CONFIRMED
:END:

Red Wings vs. Indians Free t-shirt giveaway for the first 1000 fans in attendance courtesy of the local Rochester area YMCA!

Follow on MiLB First Pitch  https //stza.co/+vKmv-1H

Shop  https //stza.co/+vKmv-D

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Red Wings vs. Indians
END:VALARM
DTSTART:20180605T230500Z
DTEND:20180606T020500Z
UID:XJ94-Go0FuK7M92BYggP71Of@stanza.co
SUMMARY:Red Wings vs. Indians
DESCRIPTION:Free t-shirt giveaway for the first 1000 fans in attendance courtesy of the local Rochester area YMCA!\n\nFollow on MiLB First Pitch: https://stza.co/+vKmv-1H\n\nShop: https://stza.co/+vKmv-D\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:T-shirt Tuesday Giveaway
STATUS:CONFIRMED
CREATED:20180213T144635Z
LAST-MODIFIED:20180213T144635Z
TRANSP:OPAQUE
END:VEVENT
* Red Wings vs. Indians
<2018-06-06 Wed 18:05-21:05>
:PROPERTIES:
:ID:       h8tmqmuOjrSkKYeShBlgWMjg@stanza.co
:LOCATION: $1 Wednesdays
:STATUS:   CONFIRMED
:END:

Red Wings vs. Indians Every Wednesday - excluding Wednesday, July 4th - enjoy ONE DOLLAR hot dogs, peanuts, cracker jacks and chips!

Follow on MiLB First Pitch  https //stza.co/+vKmy-2t

Shop  https //stza.co/+vKmy-2k

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Red Wings vs. Indians
END:VALARM
DTSTART:20180606T230500Z
DTEND:20180607T020500Z
UID:h8tmqmuOjrSkKYeShBlgWMjg@stanza.co
SUMMARY:Red Wings vs. Indians
DESCRIPTION:Every Wednesday - excluding Wednesday, July 4th - enjoy ONE DOLLAR hot dogs, peanuts, cracker jacks and chips!\n\nFollow on MiLB First Pitch: https://stza.co/+vKmy-2t\n\nShop: https://stza.co/+vKmy-2k\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:$1 Wednesdays
STATUS:CONFIRMED
CREATED:20180213T144635Z
LAST-MODIFIED:20180213T144635Z
TRANSP:OPAQUE
END:VEVENT
* Red Wings vs. Indians
<2018-06-07 Thu 11:35-14:35>
:PROPERTIES:
:ID:       ydnSgjuTt1YMZt0emrpdjlZO@stanza.co
:LOCATION: College Thursdays
:STATUS:   CONFIRMED
:END:

Red Wings vs. Indians Every Thursday - college students with a valid college ID can get a reserved ticket AND $5 Diamond Dollars for ONLY $10!

Follow on MiLB First Pitch  https //stza.co/+vKmz-3B

Shop  https //stza.co/+vKmz-2j

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Red Wings vs. Indians
END:VALARM
DTSTART:20180607T163500Z
DTEND:20180607T193500Z
UID:ydnSgjuTt1YMZt0emrpdjlZO@stanza.co
SUMMARY:Red Wings vs. Indians
DESCRIPTION:Every Thursday - college students with a valid college ID can get a reserved ticket AND $5 Diamond Dollars for ONLY $10!\n\nFollow on MiLB First Pitch: https://stza.co/+vKmz-3B\n\nShop: https://stza.co/+vKmz-2j\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:College Thursdays
STATUS:CONFIRMED
CREATED:20180213T144635Z
LAST-MODIFIED:20180213T144635Z
TRANSP:OPAQUE
END:VEVENT
* Red Wings vs. Bulls
<2018-06-08 Fri 18:05-21:05>
:PROPERTIES:
:ID:       u4E6kZu8FIW2bts4oGX8OMef@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Red Wings vs. Bulls Red Wings vs. Bulls

Follow on MiLB First Pitch  https //stza.co/+vKmC-1n

Shop  https //stza.co/+vKmC-2j

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Red Wings vs. Bulls
END:VALARM
DTSTART:20180608T230500Z
DTEND:20180609T020500Z
UID:u4E6kZu8FIW2bts4oGX8OMef@stanza.co
SUMMARY:Red Wings vs. Bulls
DESCRIPTION:Red Wings vs. Bulls\n\nFollow on MiLB First Pitch: https://stza.co/+vKmC-1n\n\nShop: https://stza.co/+vKmC-2j\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144635Z
LAST-MODIFIED:20180213T144635Z
TRANSP:OPAQUE
END:VEVENT
* Red Wings vs. Bulls
<2018-06-09 Sat 18:05-21:05>
:PROPERTIES:
:ID:       AS9o-L-Tem8CBcz-JGvmJ9b_@stanza.co
:LOCATION: Stick around after the game for some spectacular fireworks!
:STATUS:   CONFIRMED
:END:

Red Wings vs. Bulls 

The always hilarious ZOOperstars storm back to Frontier Field for the first of two shows in 2018!

Hold on to your phone in style with a Red Wings Pop Socket.

Follow on MiLB First Pitch  https //stza.co/+vKmE-3t

Shop  https //stza.co/+vKmE-c

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Red Wings vs. Bulls
END:VALARM
DTSTART:20180609T230500Z
DTEND:20180610T020500Z
UID:AS9o-L-Tem8CBcz-JGvmJ9b_@stanza.co
SUMMARY:Red Wings vs. Bulls
DESCRIPTION:\n\nThe always hilarious ZOOperstars storm back to Frontier Field for the first of two shows in 2018!\n\nHold on to your phone in style with a Red Wings Pop Socket.\n\nFollow on MiLB First Pitch: https://stza.co/+vKmE-3t\n\nShop: https://stza.co/+vKmE-c\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stick around after the game for some spectacular fireworks!
STATUS:CONFIRMED
CREATED:20180213T144635Z
LAST-MODIFIED:20180213T144635Z
TRANSP:OPAQUE
END:VEVENT
* Red Wings vs. Bulls
<2018-06-10 Sun 12:05-15:05>
:PROPERTIES:
:ID:       kFtVTkebV5I7vc8q4U3kKh4h@stanza.co
:LOCATION: Father's Day Celebration with Baseball Giveaway
:STATUS:   CONFIRMED
:END:

Red Wings vs. Bulls A special Red Wings baseball giveaway and post-game catch on the field with Dad!

Specialty jerseys modeled after the Wings baby blue uniforms of the early 80's will be worn and auctioned off to benefit the Catholic Diocese of Rochester!

Every Sunday kids 12 and under can run the bases with Red Wings mascots Spikes and Mittsy!

Follow on MiLB First Pitch  https //stza.co/+vKmG-$

Shop  https //stza.co/+vKmG-z

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Red Wings vs. Bulls
END:VALARM
DTSTART:20180610T170500Z
DTEND:20180610T200500Z
UID:kFtVTkebV5I7vc8q4U3kKh4h@stanza.co
SUMMARY:Red Wings vs. Bulls
DESCRIPTION:A special Red Wings baseball giveaway and post-game catch on the field with Dad!\n\nSpecialty jerseys modeled after the Wings baby blue uniforms of the early 80's will be worn and auctioned off to benefit the Catholic Diocese of Rochester!\n\nEvery Sunday kids 12 and under can run the bases with Red Wings mascots Spikes and Mittsy!\n\nFollow on MiLB First Pitch: https://stza.co/+vKmG-$\n\nShop: https://stza.co/+vKmG-z\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Father's Day Celebration with Baseball Giveaway
STATUS:CONFIRMED
CREATED:20180213T144635Z
LAST-MODIFIED:20180213T144635Z
TRANSP:OPAQUE
END:VEVENT
* Red Wings @ RailRiders
<2018-06-11 Mon 17:35-20:35>
:PROPERTIES:
:ID:       qtq52qIk8f1pyzqk8rAuIALi@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Red Wings @ RailRiders Red Wings @ RailRiders

Follow on MiLB First Pitch  https //stza.co/+vKnX-3r

Shop  https //stza.co/+vKnX-1U

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Red Wings @ RailRiders
END:VALARM
DTSTART:20180611T223500Z
DTEND:20180612T013500Z
UID:qtq52qIk8f1pyzqk8rAuIALi@stanza.co
SUMMARY:Red Wings @ RailRiders
DESCRIPTION:Red Wings @ RailRiders\n\nFollow on MiLB First Pitch: https://stza.co/+vKnX-3r\n\nShop: https://stza.co/+vKnX-1U\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144635Z
LAST-MODIFIED:20180213T144635Z
TRANSP:OPAQUE
END:VEVENT
* Red Wings @ RailRiders
<2018-06-12 Tue 17:35-20:35>
:PROPERTIES:
:ID:       aCcEHY7NR_rqNuIqd8EHlmAG@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Red Wings @ RailRiders Red Wings @ RailRiders

Follow on MiLB First Pitch  https //stza.co/+vKnY-39

Shop  https //stza.co/+vKnY-2v

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Red Wings @ RailRiders
END:VALARM
DTSTART:20180612T223500Z
DTEND:20180613T013500Z
UID:aCcEHY7NR_rqNuIqd8EHlmAG@stanza.co
SUMMARY:Red Wings @ RailRiders
DESCRIPTION:Red Wings @ RailRiders\n\nFollow on MiLB First Pitch: https://stza.co/+vKnY-39\n\nShop: https://stza.co/+vKnY-2v\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144635Z
LAST-MODIFIED:20180213T144635Z
TRANSP:OPAQUE
END:VEVENT
* Red Wings @ RailRiders
<2018-06-13 Wed 17:35-20:35>
:PROPERTIES:
:ID:       gkH4gGHMj7-E09lo-NejPj57@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Red Wings @ RailRiders Red Wings @ RailRiders

Follow on MiLB First Pitch  https //stza.co/+vKnZ-15

Shop  https //stza.co/+vKnZ-2Q

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Red Wings @ RailRiders
END:VALARM
DTSTART:20180613T223500Z
DTEND:20180614T013500Z
UID:gkH4gGHMj7-E09lo-NejPj57@stanza.co
SUMMARY:Red Wings @ RailRiders
DESCRIPTION:Red Wings @ RailRiders\n\nFollow on MiLB First Pitch: https://stza.co/+vKnZ-15\n\nShop: https://stza.co/+vKnZ-2Q\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144635Z
LAST-MODIFIED:20180213T144635Z
TRANSP:OPAQUE
END:VEVENT
* Red Wings @ Bisons
<2018-06-14 Thu 18:05-21:05>
:PROPERTIES:
:ID:       nDBCxhTOvC2dvuoaClVuns3P@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Red Wings @ Bisons Red Wings @ Bisons

Follow on MiLB First Pitch  https //stza.co/+vKl2-J

Shop  https //stza.co/+vKl2-2F

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Red Wings @ Bisons
END:VALARM
DTSTART:20180614T230500Z
DTEND:20180615T020500Z
UID:nDBCxhTOvC2dvuoaClVuns3P@stanza.co
SUMMARY:Red Wings @ Bisons
DESCRIPTION:Red Wings @ Bisons\n\nFollow on MiLB First Pitch: https://stza.co/+vKl2-J\n\nShop: https://stza.co/+vKl2-2F\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144635Z
LAST-MODIFIED:20180213T144635Z
TRANSP:OPAQUE
END:VEVENT
* Red Wings @ Bisons
<2018-06-15 Fri 18:05-21:05>
:PROPERTIES:
:ID:       cRt5MM8ScKnAGEELbEl3STv3@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Red Wings @ Bisons Red Wings @ Bisons

Follow on MiLB First Pitch  https //stza.co/+vKl3-1_

Shop  https //stza.co/+vKl3-3M

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Red Wings @ Bisons
END:VALARM
DTSTART:20180615T230500Z
DTEND:20180616T020500Z
UID:cRt5MM8ScKnAGEELbEl3STv3@stanza.co
SUMMARY:Red Wings @ Bisons
DESCRIPTION:Red Wings @ Bisons\n\nFollow on MiLB First Pitch: https://stza.co/+vKl3-1_\n\nShop: https://stza.co/+vKl3-3M\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144635Z
LAST-MODIFIED:20180213T144635Z
TRANSP:OPAQUE
END:VEVENT
* Red Wings @ Bisons
<2018-06-16 Sat 17:05-20:05>
:PROPERTIES:
:ID:       atGh7IAF8bq7w6rPTVjs9UtN@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Red Wings @ Bisons Red Wings @ Bisons

Follow on MiLB First Pitch  https //stza.co/+vKl4-u

Shop  https //stza.co/+vKl4-2m

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Red Wings @ Bisons
END:VALARM
DTSTART:20180616T220500Z
DTEND:20180617T010500Z
UID:atGh7IAF8bq7w6rPTVjs9UtN@stanza.co
SUMMARY:Red Wings @ Bisons
DESCRIPTION:Red Wings @ Bisons\n\nFollow on MiLB First Pitch: https://stza.co/+vKl4-u\n\nShop: https://stza.co/+vKl4-2m\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144635Z
LAST-MODIFIED:20180213T144635Z
TRANSP:OPAQUE
END:VEVENT
* Red Wings @ Bisons
<2018-06-17 Sun 12:05-15:05>
:PROPERTIES:
:ID:       YLEZlesECtt6qeViwqA22_Ut@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Red Wings @ Bisons Red Wings @ Bisons

Follow on MiLB First Pitch  https //stza.co/+vKl5-C

Shop  https //stza.co/+vKl5-2f

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Red Wings @ Bisons
END:VALARM
DTSTART:20180617T170500Z
DTEND:20180617T200500Z
UID:YLEZlesECtt6qeViwqA22_Ut@stanza.co
SUMMARY:Red Wings @ Bisons
DESCRIPTION:Red Wings @ Bisons\n\nFollow on MiLB First Pitch: https://stza.co/+vKl5-C\n\nShop: https://stza.co/+vKl5-2f\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144635Z
LAST-MODIFIED:20180213T144635Z
TRANSP:OPAQUE
END:VEVENT
* Red Wings vs. Chiefs
<2018-06-19 Tue 18:05-21:05>
:PROPERTIES:
:ID:       dcZGnU53LAkb_MVyzh-S1wbf@stanza.co
:LOCATION: T-shirt Tuesday Giveaway
:STATUS:   CONFIRMED
:END:

Red Wings vs. Chiefs Free t-shirt giveaway for the first 500 fans in attendance courtesy of Zweigle's!

Follow on MiLB First Pitch  https //stza.co/+vKmH-T

Shop  https //stza.co/+vKmH-11

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Red Wings vs. Chiefs
END:VALARM
DTSTART:20180619T230500Z
DTEND:20180620T020500Z
UID:dcZGnU53LAkb_MVyzh-S1wbf@stanza.co
SUMMARY:Red Wings vs. Chiefs
DESCRIPTION:Free t-shirt giveaway for the first 500 fans in attendance courtesy of Zweigle's!\n\nFollow on MiLB First Pitch: https://stza.co/+vKmH-T\n\nShop: https://stza.co/+vKmH-11\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:T-shirt Tuesday Giveaway
STATUS:CONFIRMED
CREATED:20180213T144635Z
LAST-MODIFIED:20180213T144635Z
TRANSP:OPAQUE
END:VEVENT
* Red Wings vs. Chiefs
<2018-06-20 Wed 11:35-14:35>
:PROPERTIES:
:ID:       iccH4bhYm2TZaszCXzVrAoyL@stanza.co
:LOCATION: $1 Wednesdays
:STATUS:   CONFIRMED
:END:

Red Wings vs. Chiefs Every Wednesday - excluding Wednesday, July 4th - enjoy ONE DOLLAR hot dogs, peanuts, cracker jacks and chips!

Follow on MiLB First Pitch  https //stza.co/+vKmK-2k

Shop  https //stza.co/+vKmK-1n

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Red Wings vs. Chiefs
END:VALARM
DTSTART:20180620T163500Z
DTEND:20180620T193500Z
UID:iccH4bhYm2TZaszCXzVrAoyL@stanza.co
SUMMARY:Red Wings vs. Chiefs
DESCRIPTION:Every Wednesday - excluding Wednesday, July 4th - enjoy ONE DOLLAR hot dogs, peanuts, cracker jacks and chips!\n\nFollow on MiLB First Pitch: https://stza.co/+vKmK-2k\n\nShop: https://stza.co/+vKmK-1n\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:$1 Wednesdays
STATUS:CONFIRMED
CREATED:20180213T144635Z
LAST-MODIFIED:20180213T144635Z
TRANSP:OPAQUE
END:VEVENT
* Red Wings vs. Chiefs
<2018-06-21 Thu 18:05-21:05>
:PROPERTIES:
:ID:       bW6Qxetv5RWmtnRgMoujcSGz@stanza.co
:LOCATION: Thirsty Thursday Pre-Game Happy Hour
:STATUS:   CONFIRMED
:END:

Red Wings vs. Chiefs Enjoy $2 beers from 6-7 pm and live music from Rob Gioia at the 10th Inning Bar!

Every Thursday - college students with a valid college ID can get a reserved ticket AND $5 Diamond Dollars for ONLY $10!

Follow on MiLB First Pitch  https //stza.co/+vKmL-q

Shop  https //stza.co/+vKmL-2w

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Red Wings vs. Chiefs
END:VALARM
DTSTART:20180621T230500Z
DTEND:20180622T020500Z
UID:bW6Qxetv5RWmtnRgMoujcSGz@stanza.co
SUMMARY:Red Wings vs. Chiefs
DESCRIPTION:Enjoy $2 beers from 6-7 pm and live music from Rob Gioia at the 10th Inning Bar!\n\nEvery Thursday - college students with a valid college ID can get a reserved ticket AND $5 Diamond Dollars for ONLY $10!\n\nFollow on MiLB First Pitch: https://stza.co/+vKmL-q\n\nShop: https://stza.co/+vKmL-2w\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Thirsty Thursday Pre-Game Happy Hour
STATUS:CONFIRMED
CREATED:20180213T144635Z
LAST-MODIFIED:20180213T144635Z
TRANSP:OPAQUE
END:VEVENT
* Red Wings vs. RailRiders
<2018-06-22 Fri 18:05-21:05>
:PROPERTIES:
:ID:       caQ-90_e_vMpyzyTkkeyLXvF@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Red Wings vs. RailRiders Red Wings vs. RailRiders

Follow on MiLB First Pitch  https //stza.co/+vKmO-2y

Shop  https //stza.co/+vKmO-1P

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Red Wings vs. RailRiders
END:VALARM
DTSTART:20180622T230500Z
DTEND:20180623T020500Z
UID:caQ-90_e_vMpyzyTkkeyLXvF@stanza.co
SUMMARY:Red Wings vs. RailRiders
DESCRIPTION:Red Wings vs. RailRiders\n\nFollow on MiLB First Pitch: https://stza.co/+vKmO-2y\n\nShop: https://stza.co/+vKmO-1P\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144635Z
LAST-MODIFIED:20180213T144635Z
TRANSP:OPAQUE
END:VEVENT
* Red Wings vs. RailRiders
<2018-06-23 Sat 18:05-21:05>
:PROPERTIES:
:ID:       aGOx_VEIpQLw70Jszs1fJSkH@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Red Wings vs. RailRiders Red Wings vs. RailRiders

Follow on MiLB First Pitch  https //stza.co/+vKmP-2D

Shop  https //stza.co/+vKmP-h

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Red Wings vs. RailRiders
END:VALARM
DTSTART:20180623T230500Z
DTEND:20180624T020500Z
UID:aGOx_VEIpQLw70Jszs1fJSkH@stanza.co
SUMMARY:Red Wings vs. RailRiders
DESCRIPTION:Red Wings vs. RailRiders\n\nFollow on MiLB First Pitch: https://stza.co/+vKmP-2D\n\nShop: https://stza.co/+vKmP-h\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144635Z
LAST-MODIFIED:20180213T144635Z
TRANSP:OPAQUE
END:VEVENT
* Red Wings vs. RailRiders
<2018-06-24 Sun 12:05-15:05>
:PROPERTIES:
:ID:       DwAYHQKWgIo9Hk9shSNVFJ4v@stanza.co
:LOCATION: Toy Hall of Fame Day
:STATUS:   CONFIRMED
:END:

Red Wings vs. RailRiders A tribute to toys - including the 2017 inductees of the Wiffle Ball, Clue and the Paper Airplane! More details to be announced.

Every Sunday kids 12 and under can run the bases with Red Wings mascots Spikes and Mittsy!

Follow on MiLB First Pitch  https //stza.co/+vKmS-1E

Shop  https //stza.co/+vKmS-2M

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Red Wings vs. RailRiders
END:VALARM
DTSTART:20180624T170500Z
DTEND:20180624T200500Z
UID:DwAYHQKWgIo9Hk9shSNVFJ4v@stanza.co
SUMMARY:Red Wings vs. RailRiders
DESCRIPTION:A tribute to toys - including the 2017 inductees of the Wiffle Ball, Clue and the Paper Airplane! More details to be announced.\n\nEvery Sunday kids 12 and under can run the bases with Red Wings mascots Spikes and Mittsy!\n\nFollow on MiLB First Pitch: https://stza.co/+vKmS-1E\n\nShop: https://stza.co/+vKmS-2M\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Toy Hall of Fame Day
STATUS:CONFIRMED
CREATED:20180213T144635Z
LAST-MODIFIED:20180213T144635Z
TRANSP:OPAQUE
END:VEVENT
* Red Wings @ Chiefs
<2018-06-25 Mon 17:35-20:35>
:PROPERTIES:
:ID:       uswFXPw6eUcKAlQYYFw3tP2f@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Red Wings @ Chiefs Red Wings @ Chiefs

Follow on MiLB First Pitch  https //stza.co/+vKo5-22

Shop  https //stza.co/+vKo5-2z

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Red Wings @ Chiefs
END:VALARM
DTSTART:20180625T223500Z
DTEND:20180626T013500Z
UID:uswFXPw6eUcKAlQYYFw3tP2f@stanza.co
SUMMARY:Red Wings @ Chiefs
DESCRIPTION:Red Wings @ Chiefs\n\nFollow on MiLB First Pitch: https://stza.co/+vKo5-22\n\nShop: https://stza.co/+vKo5-2z\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144635Z
LAST-MODIFIED:20180213T144635Z
TRANSP:OPAQUE
END:VEVENT
* Red Wings @ Chiefs
<2018-06-26 Tue 17:35-20:35>
:PROPERTIES:
:ID:       FoQeyu7m7qGDP0J-_wIAgXHv@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Red Wings @ Chiefs Red Wings @ Chiefs

Follow on MiLB First Pitch  https //stza.co/+vKo6-2$

Shop  https //stza.co/+vKo6-1v

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Red Wings @ Chiefs
END:VALARM
DTSTART:20180626T223500Z
DTEND:20180627T013500Z
UID:FoQeyu7m7qGDP0J-_wIAgXHv@stanza.co
SUMMARY:Red Wings @ Chiefs
DESCRIPTION:Red Wings @ Chiefs\n\nFollow on MiLB First Pitch: https://stza.co/+vKo6-2$\n\nShop: https://stza.co/+vKo6-1v\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144635Z
LAST-MODIFIED:20180213T144635Z
TRANSP:OPAQUE
END:VEVENT
* Red Wings @ Chiefs
<2018-06-27 Wed 17:35-20:35>
:PROPERTIES:
:ID:       5pToYsUQfLG_byY9JSYJHNjh@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Red Wings @ Chiefs Red Wings @ Chiefs

Follow on MiLB First Pitch  https //stza.co/+vKo7-2N

Shop  https //stza.co/+vKo7-3O

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Red Wings @ Chiefs
END:VALARM
DTSTART:20180627T223500Z
DTEND:20180628T013500Z
UID:5pToYsUQfLG_byY9JSYJHNjh@stanza.co
SUMMARY:Red Wings @ Chiefs
DESCRIPTION:Red Wings @ Chiefs\n\nFollow on MiLB First Pitch: https://stza.co/+vKo7-2N\n\nShop: https://stza.co/+vKo7-3O\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144635Z
LAST-MODIFIED:20180213T144635Z
TRANSP:OPAQUE
END:VEVENT
* Red Wings @ Chiefs
<2018-06-28 Thu 17:35-20:35>
:PROPERTIES:
:ID:       6fIghyYikav1xcPA27kkvEJg@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Red Wings @ Chiefs Red Wings @ Chiefs

Follow on MiLB First Pitch  https //stza.co/+vKo8-4

Shop  https //stza.co/+vKo8-F

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Red Wings @ Chiefs
END:VALARM
DTSTART:20180628T223500Z
DTEND:20180629T013500Z
UID:6fIghyYikav1xcPA27kkvEJg@stanza.co
SUMMARY:Red Wings @ Chiefs
DESCRIPTION:Red Wings @ Chiefs\n\nFollow on MiLB First Pitch: https://stza.co/+vKo8-4\n\nShop: https://stza.co/+vKo8-F\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144635Z
LAST-MODIFIED:20180213T144635Z
TRANSP:OPAQUE
END:VEVENT
* Red Wings vs. IronPigs
<2018-06-29 Fri 18:05-21:05>
:PROPERTIES:
:ID:       5srDhzGdh3bNRZLqgsUapGBn@stanza.co
:LOCATION: Stick around after the game for some spectacular fireworks!
:STATUS:   CONFIRMED
:END:

Red Wings vs. IronPigs The Red Wings will be welcoming  Punxsutawney Phil to Frontier Field for Salute to 'Groundhog Day' Night in celebration of the 25th anniversary of the timeless Bill Murray movie. There will also be a t-shirt giveaway and the team will wear specialty jerseys.

We have 1,000 t-shirts to giveaway away but they won't be given away at the gates. Just be in your seat at game time for your chance to grab one.



Follow on MiLB First Pitch  https //stza.co/+vKmU-1j

Shop  https //stza.co/+vKmU-2u

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Red Wings vs. IronPigs
END:VALARM
DTSTART:20180629T230500Z
DTEND:20180630T020500Z
UID:5srDhzGdh3bNRZLqgsUapGBn@stanza.co
SUMMARY:Red Wings vs. IronPigs
DESCRIPTION:The Red Wings will be welcoming  Punxsutawney Phil to Frontier Field for Salute to 'Groundhog Day' Night in celebration of the 25th anniversary of the timeless Bill Murray movie. There will also be a t-shirt giveaway and the team will wear specialty jerseys.\n\nWe have 1,000 t-shirts to giveaway away but they won't be given away at the gates. Just be in your seat at game time for your chance to grab one.\n\n\n\nFollow on MiLB First Pitch: https://stza.co/+vKmU-1j\n\nShop: https://stza.co/+vKmU-2u\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stick around after the game for some spectacular fireworks!
STATUS:CONFIRMED
CREATED:20180213T144635Z
LAST-MODIFIED:20180213T144635Z
TRANSP:OPAQUE
END:VEVENT
* Red Wings vs. IronPigs
<2018-06-30 Sat 18:05-21:05>
:PROPERTIES:
:ID:       TtZdU9LwVI28e-b3Bo2f-LXC@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Red Wings vs. IronPigs Red Wings vs. IronPigs

Follow on MiLB First Pitch  https //stza.co/+vKmW-9

Shop  https //stza.co/+vKmW-1n

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Red Wings vs. IronPigs
END:VALARM
DTSTART:20180630T230500Z
DTEND:20180701T020500Z
UID:TtZdU9LwVI28e-b3Bo2f-LXC@stanza.co
SUMMARY:Red Wings vs. IronPigs
DESCRIPTION:Red Wings vs. IronPigs\n\nFollow on MiLB First Pitch: https://stza.co/+vKmW-9\n\nShop: https://stza.co/+vKmW-1n\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144635Z
LAST-MODIFIED:20180213T144635Z
TRANSP:OPAQUE
END:VEVENT
* Red Wings vs. IronPigs
<2018-07-01 Sun 12:05-15:05>
:PROPERTIES:
:ID:       dIwK5UHx-teExrtH3vt-4eZM@stanza.co
:LOCATION: Halloween Day
:STATUS:   CONFIRMED
:END:

Red Wings vs. IronPigs Featuring a helicopter candy drop! More details to come.

Every Sunday kids 12 and under can run the bases with Red Wings mascots Spikes and Mittsy!

Follow on MiLB First Pitch  https //stza.co/+vKmY-29

Shop  https //stza.co/+vKmY-2D

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Red Wings vs. IronPigs
END:VALARM
DTSTART:20180701T170500Z
DTEND:20180701T200500Z
UID:dIwK5UHx-teExrtH3vt-4eZM@stanza.co
SUMMARY:Red Wings vs. IronPigs
DESCRIPTION:Featuring a helicopter candy drop! More details to come.\n\nEvery Sunday kids 12 and under can run the bases with Red Wings mascots Spikes and Mittsy!\n\nFollow on MiLB First Pitch: https://stza.co/+vKmY-29\n\nShop: https://stza.co/+vKmY-2D\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Halloween Day
STATUS:CONFIRMED
CREATED:20180213T144635Z
LAST-MODIFIED:20180213T144635Z
TRANSP:OPAQUE
END:VEVENT
* Red Wings @ Red Sox
<2018-07-02 Mon 17:15-20:15>
:PROPERTIES:
:ID:       Rdi1m7gZwtyN2Yqu4M6sCuS4@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Red Wings @ Red Sox Red Wings @ Red Sox

Buy tickets here  https //stza.co/~vKlC

Follow on MiLB First Pitch  https //stza.co/+vKlC-2h

Shop  https //stza.co/+vKlC-1x

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Red Wings @ Red Sox
END:VALARM
DTSTART:20180702T221500Z
DTEND:20180703T011500Z
UID:Rdi1m7gZwtyN2Yqu4M6sCuS4@stanza.co
SUMMARY:Red Wings @ Red Sox
DESCRIPTION:Red Wings @ Red Sox\n\nBuy tickets here: https://stza.co/~vKlC\n\nFollow on MiLB First Pitch: https://stza.co/+vKlC-2h\n\nShop: https://stza.co/+vKlC-1x\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144635Z
LAST-MODIFIED:20180213T144635Z
TRANSP:OPAQUE
END:VEVENT
* Red Wings @ Red Sox
<2018-07-03 Tue 17:15-20:15>
:PROPERTIES:
:ID:       5U_WzvLauNZIXLkO7bEVg6b-@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Red Wings @ Red Sox Red Wings @ Red Sox

Buy tickets here  https //stza.co/~vKlD

Follow on MiLB First Pitch  https //stza.co/+vKlD-1

Shop  https //stza.co/+vKlD-2l

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Red Wings @ Red Sox
END:VALARM
DTSTART:20180703T221500Z
DTEND:20180704T011500Z
UID:5U_WzvLauNZIXLkO7bEVg6b-@stanza.co
SUMMARY:Red Wings @ Red Sox
DESCRIPTION:Red Wings @ Red Sox\n\nBuy tickets here: https://stza.co/~vKlD\n\nFollow on MiLB First Pitch: https://stza.co/+vKlD-1\n\nShop: https://stza.co/+vKlD-2l\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144635Z
LAST-MODIFIED:20180213T144635Z
TRANSP:OPAQUE
END:VEVENT
* Red Wings vs. Red Sox
<2018-07-04 Wed 18:05-21:05>
:PROPERTIES:
:ID:       RxksVp_BqApzm9RdUaDnhPtk@stanza.co
:LOCATION: Stick around after the game for some spectacular fireworks!
:STATUS:   CONFIRMED
:END:

Red Wings vs. Red Sox Come out for the biggest post-game fireworks display of the season! Also, a patriotic-themed jersey auction.



Follow on MiLB First Pitch  https //stza.co/+vKm_-M

Shop  https //stza.co/+vKm_-3y

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Red Wings vs. Red Sox
END:VALARM
DTSTART:20180704T230500Z
DTEND:20180705T020500Z
UID:RxksVp_BqApzm9RdUaDnhPtk@stanza.co
SUMMARY:Red Wings vs. Red Sox
DESCRIPTION:Come out for the biggest post-game fireworks display of the season! Also, a patriotic-themed jersey auction.\n\n\n\nFollow on MiLB First Pitch: https://stza.co/+vKm_-M\n\nShop: https://stza.co/+vKm_-3y\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stick around after the game for some spectacular fireworks!
STATUS:CONFIRMED
CREATED:20180213T144635Z
LAST-MODIFIED:20180213T144635Z
TRANSP:OPAQUE
END:VEVENT
* Red Wings vs. Red Sox
<2018-07-05 Thu 16:05-19:05>
:PROPERTIES:
:ID:       S9OAv99qPv4HMHlLaUed5mJB@stanza.co
:LOCATION: Bark in the Park
:STATUS:   CONFIRMED
:END:

Red Wings vs. Red Sox NEW in 2018  Fans with dogs will be able to participate in a pre-game dog parade on the field. Also, the third base grass berm will be open to all dogs and their owners.

Enjoy $2 beers at the 10th Inning Bar from 4-5 pm

Every Thursday - college students with a valid college ID can get a reserved ticket AND $5 Diamond Dollars for ONLY $10!

Follow on MiLB First Pitch  https //stza.co/+vKn0-2m

Shop  https //stza.co/+vKn0-1X

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Red Wings vs. Red Sox
END:VALARM
DTSTART:20180705T210500Z
DTEND:20180706T000500Z
UID:S9OAv99qPv4HMHlLaUed5mJB@stanza.co
SUMMARY:Red Wings vs. Red Sox
DESCRIPTION:NEW in 2018: Fans with dogs will be able to participate in a pre-game dog parade on the field. Also, the third base grass berm will be open to all dogs and their owners.\n\nEnjoy $2 beers at the 10th Inning Bar from 4-5 pm\n\nEvery Thursday - college students with a valid college ID can get a reserved ticket AND $5 Diamond Dollars for ONLY $10!\n\nFollow on MiLB First Pitch: https://stza.co/+vKn0-2m\n\nShop: https://stza.co/+vKn0-1X\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Bark in the Park
STATUS:CONFIRMED
CREATED:20180213T144635Z
LAST-MODIFIED:20180213T144635Z
TRANSP:OPAQUE
END:VEVENT
* Red Wings @ IronPigs
<2018-07-06 Fri 18:05-21:05>
:PROPERTIES:
:ID:       MTWVfnfOklUvaR4wjTzHO92c@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Red Wings @ IronPigs Red Wings @ IronPigs

Follow on MiLB First Pitch  https //stza.co/+vKlq-31

Shop  https //stza.co/+vKlq-1F

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Red Wings @ IronPigs
END:VALARM
DTSTART:20180706T230500Z
DTEND:20180707T020500Z
UID:MTWVfnfOklUvaR4wjTzHO92c@stanza.co
SUMMARY:Red Wings @ IronPigs
DESCRIPTION:Red Wings @ IronPigs\n\nFollow on MiLB First Pitch: https://stza.co/+vKlq-31\n\nShop: https://stza.co/+vKlq-1F\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144635Z
LAST-MODIFIED:20180213T144635Z
TRANSP:OPAQUE
END:VEVENT
* Red Wings @ IronPigs
<2018-07-07 Sat 17:35-20:35>
:PROPERTIES:
:ID:       HipJYyA5r9Hh-356wTMbgKHX@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Red Wings @ IronPigs Red Wings @ IronPigs

Follow on MiLB First Pitch  https //stza.co/+vKlr-n

Shop  https //stza.co/+vKlr-1F

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Red Wings @ IronPigs
END:VALARM
DTSTART:20180707T223500Z
DTEND:20180708T013500Z
UID:HipJYyA5r9Hh-356wTMbgKHX@stanza.co
SUMMARY:Red Wings @ IronPigs
DESCRIPTION:Red Wings @ IronPigs\n\nFollow on MiLB First Pitch: https://stza.co/+vKlr-n\n\nShop: https://stza.co/+vKlr-1F\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144635Z
LAST-MODIFIED:20180213T144635Z
TRANSP:OPAQUE
END:VEVENT
* Red Wings @ IronPigs
<2018-07-08 Sun 12:35-15:35>
:PROPERTIES:
:ID:       t9nCG_G8_uipoZpovu9wMWSo@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Red Wings @ IronPigs Red Wings @ IronPigs

Follow on MiLB First Pitch  https //stza.co/+vKls-1D

Shop  https //stza.co/+vKls-1u

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Red Wings @ IronPigs
END:VALARM
DTSTART:20180708T173500Z
DTEND:20180708T203500Z
UID:t9nCG_G8_uipoZpovu9wMWSo@stanza.co
SUMMARY:Red Wings @ IronPigs
DESCRIPTION:Red Wings @ IronPigs\n\nFollow on MiLB First Pitch: https://stza.co/+vKls-1D\n\nShop: https://stza.co/+vKls-1u\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144635Z
LAST-MODIFIED:20180213T144635Z
TRANSP:OPAQUE
END:VEVENT
* Red Wings @ RailRiders
<2018-07-12 Thu 18:05-21:05>
:PROPERTIES:
:ID:       Tje_wdqzsXqKQqBOx-D0ideF@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Red Wings @ RailRiders Red Wings @ RailRiders

Follow on MiLB First Pitch  https //stza.co/+vKn_-3V

Shop  https //stza.co/+vKn_-1k

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Red Wings @ RailRiders
END:VALARM
DTSTART:20180712T230500Z
DTEND:20180713T020500Z
UID:Tje_wdqzsXqKQqBOx-D0ideF@stanza.co
SUMMARY:Red Wings @ RailRiders
DESCRIPTION:Red Wings @ RailRiders\n\nFollow on MiLB First Pitch: https://stza.co/+vKn_-3V\n\nShop: https://stza.co/+vKn_-1k\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144635Z
LAST-MODIFIED:20180213T144635Z
TRANSP:OPAQUE
END:VEVENT
* Red Wings @ RailRiders
<2018-07-13 Fri 18:05-21:05>
:PROPERTIES:
:ID:       e6bGSYQ6uzc5E5eYukbvSyDO@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Red Wings @ RailRiders Red Wings @ RailRiders

Follow on MiLB First Pitch  https //stza.co/+vKn$-3y

Shop  https //stza.co/+vKn$-3b

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Red Wings @ RailRiders
END:VALARM
DTSTART:20180713T230500Z
DTEND:20180714T020500Z
UID:e6bGSYQ6uzc5E5eYukbvSyDO@stanza.co
SUMMARY:Red Wings @ RailRiders
DESCRIPTION:Red Wings @ RailRiders\n\nFollow on MiLB First Pitch: https://stza.co/+vKn$-3y\n\nShop: https://stza.co/+vKn$-3b\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144635Z
LAST-MODIFIED:20180213T144635Z
TRANSP:OPAQUE
END:VEVENT
* Red Wings @ RailRiders
<2018-07-14 Sat 17:35-20:35>
:PROPERTIES:
:ID:       3BybmQ-K6f2HQfOkT4-HmJlC@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Red Wings @ RailRiders Red Wings @ RailRiders

Follow on MiLB First Pitch  https //stza.co/+vKo0-S

Shop  https //stza.co/+vKo0-3i

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Red Wings @ RailRiders
END:VALARM
DTSTART:20180714T223500Z
DTEND:20180715T013500Z
UID:3BybmQ-K6f2HQfOkT4-HmJlC@stanza.co
SUMMARY:Red Wings @ RailRiders
DESCRIPTION:Red Wings @ RailRiders\n\nFollow on MiLB First Pitch: https://stza.co/+vKo0-S\n\nShop: https://stza.co/+vKo0-3i\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144635Z
LAST-MODIFIED:20180213T144635Z
TRANSP:OPAQUE
END:VEVENT
* Red Wings @ RailRiders
<2018-07-15 Sun 12:05-15:05>
:PROPERTIES:
:ID:       FNBldBmjSEB466bqOuoVeUR5@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Red Wings @ RailRiders Red Wings @ RailRiders

Follow on MiLB First Pitch  https //stza.co/+vKo1-2t

Shop  https //stza.co/+vKo1-3y

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Red Wings @ RailRiders
END:VALARM
DTSTART:20180715T170500Z
DTEND:20180715T200500Z
UID:FNBldBmjSEB466bqOuoVeUR5@stanza.co
SUMMARY:Red Wings @ RailRiders
DESCRIPTION:Red Wings @ RailRiders\n\nFollow on MiLB First Pitch: https://stza.co/+vKo1-2t\n\nShop: https://stza.co/+vKo1-3y\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144635Z
LAST-MODIFIED:20180213T144635Z
TRANSP:OPAQUE
END:VEVENT
* Red Wings vs. Bats
<2018-07-16 Mon 18:05-21:05>
:PROPERTIES:
:ID:       4tJOcwxfaQWnBWA0HJQNbHhs@stanza.co
:LOCATION: Kids Eat Free Mondays
:STATUS:   CONFIRMED
:END:

Red Wings vs. Bats Every Monday home game the first 500 kids get a FREE hot dog, snack item and soda!

Follow on MiLB First Pitch  https //stza.co/+vKn2-2c

Shop  https //stza.co/+vKn2-25

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Red Wings vs. Bats
END:VALARM
DTSTART:20180716T230500Z
DTEND:20180717T020500Z
UID:4tJOcwxfaQWnBWA0HJQNbHhs@stanza.co
SUMMARY:Red Wings vs. Bats
DESCRIPTION:Every Monday home game the first 500 kids get a FREE hot dog, snack item and soda!\n\nFollow on MiLB First Pitch: https://stza.co/+vKn2-2c\n\nShop: https://stza.co/+vKn2-25\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Kids Eat Free Mondays
STATUS:CONFIRMED
CREATED:20180213T144635Z
LAST-MODIFIED:20180213T144635Z
TRANSP:OPAQUE
END:VEVENT
* Red Wings vs. Bats
<2018-07-17 Tue 10:05-13:05>
:PROPERTIES:
:ID:       EUEGTK-pBFAEkUNTn5ZeJLjj@stanza.co
:LOCATION: Camp Day
:STATUS:   CONFIRMED
:END:

Red Wings vs. Bats 

Free t-shirt giveaway for the first 500 fans in attendance courtesy of Zweigle's!

Follow on MiLB First Pitch  https //stza.co/+vKn4-2

Shop  https //stza.co/+vKn4-31

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Red Wings vs. Bats
END:VALARM
DTSTART:20180717T150500Z
DTEND:20180717T180500Z
UID:EUEGTK-pBFAEkUNTn5ZeJLjj@stanza.co
SUMMARY:Red Wings vs. Bats
DESCRIPTION:\n\nFree t-shirt giveaway for the first 500 fans in attendance courtesy of Zweigle's!\n\nFollow on MiLB First Pitch: https://stza.co/+vKn4-2\n\nShop: https://stza.co/+vKn4-31\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Camp Day
STATUS:CONFIRMED
CREATED:20180213T144635Z
LAST-MODIFIED:20180213T144635Z
TRANSP:OPAQUE
END:VEVENT
* Red Wings vs. Bats
<2018-07-18 Wed 18:05-21:05>
:PROPERTIES:
:ID:       RpZBNfizY2ZRjjeZe6dxjiRo@stanza.co
:LOCATION: A Christmas Story in July w/ Ornament Giveaway
:STATUS:   CONFIRMED
:END:

Red Wings vs. Bats We'll be celebrating the 35th anniversary of the timeless Christmas classic!

Every Wednesday - excluding Wednesday, July 4th - enjoy ONE DOLLAR hot dogs, peanuts, cracker jacks and chips!

Follow on MiLB First Pitch  https //stza.co/+vKn6-O

Shop  https //stza.co/+vKn6-I

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Red Wings vs. Bats
END:VALARM
DTSTART:20180718T230500Z
DTEND:20180719T020500Z
UID:RpZBNfizY2ZRjjeZe6dxjiRo@stanza.co
SUMMARY:Red Wings vs. Bats
DESCRIPTION:We'll be celebrating the 35th anniversary of the timeless Christmas classic!\n\nEvery Wednesday - excluding Wednesday, July 4th - enjoy ONE DOLLAR hot dogs, peanuts, cracker jacks and chips!\n\nFollow on MiLB First Pitch: https://stza.co/+vKn6-O\n\nShop: https://stza.co/+vKn6-I\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:A Christmas Story in July w/ Ornament Giveaway
STATUS:CONFIRMED
CREATED:20180213T144635Z
LAST-MODIFIED:20180213T144635Z
TRANSP:OPAQUE
END:VEVENT
* Red Wings vs. Tides
<2018-07-19 Thu 18:05-21:05>
:PROPERTIES:
:ID:       lFGU3LcprBggWerhfBvYzDar@stanza.co
:LOCATION: College Thursdays
:STATUS:   CONFIRMED
:END:

Red Wings vs. Tides Every Thursday - college students with a valid college ID can get a reserved ticket AND $5 Diamond Dollars for ONLY $10!

Enjoy $2 beers from 6-7 pm and live music from Genesee Saw at the 10th Inning Bar!

Follow on MiLB First Pitch  https //stza.co/+vKn7-2W

Shop  https //stza.co/+vKn7-2M

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Red Wings vs. Tides
END:VALARM
DTSTART:20180719T230500Z
DTEND:20180720T020500Z
UID:lFGU3LcprBggWerhfBvYzDar@stanza.co
SUMMARY:Red Wings vs. Tides
DESCRIPTION:Every Thursday - college students with a valid college ID can get a reserved ticket AND $5 Diamond Dollars for ONLY $10!\n\nEnjoy $2 beers from 6-7 pm and live music from Genesee Saw at the 10th Inning Bar!\n\nFollow on MiLB First Pitch: https://stza.co/+vKn7-2W\n\nShop: https://stza.co/+vKn7-2M\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:College Thursdays
STATUS:CONFIRMED
CREATED:20180213T144635Z
LAST-MODIFIED:20180213T144635Z
TRANSP:OPAQUE
END:VEVENT
* Red Wings vs. Tides
<2018-07-20 Fri 17:05-20:05>
:PROPERTIES:
:ID:       Ile0CNGlGIkPF1OOh3JmZald@stanza.co
:LOCATION: Stick around after the game for some spectacular fireworks!
:STATUS:   CONFIRMED
:END:

Red Wings vs. Tides A great tradition at Frontier Field! Come check out a Wings game followed by an RPO concert and fireworks show for ONLY the price of a game ticket!



Follow on MiLB First Pitch  https //stza.co/+vKna-J

Shop  https //stza.co/+vKna-3T

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Red Wings vs. Tides
END:VALARM
DTSTART:20180720T220500Z
DTEND:20180721T010500Z
UID:Ile0CNGlGIkPF1OOh3JmZald@stanza.co
SUMMARY:Red Wings vs. Tides
DESCRIPTION:A great tradition at Frontier Field! Come check out a Wings game followed by an RPO concert and fireworks show for ONLY the price of a game ticket!\n\n\n\nFollow on MiLB First Pitch: https://stza.co/+vKna-J\n\nShop: https://stza.co/+vKna-3T\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stick around after the game for some spectacular fireworks!
STATUS:CONFIRMED
CREATED:20180213T144635Z
LAST-MODIFIED:20180213T144635Z
TRANSP:OPAQUE
END:VEVENT
* Red Wings vs. Tides
<2018-07-21 Sat 17:05-20:05>
:PROPERTIES:
:ID:       wyoNWjpVC77RRkBl3pR2Q6bm@stanza.co
:LOCATION: Stick around after the game for some spectacular fireworks!
:STATUS:   CONFIRMED
:END:

Red Wings vs. Tides Stick around after the game for a country concert and fireworks for just the price of a game ticket! Act TBD.

The first 2,000 fans will take home a FREE Wings cap!



Follow on MiLB First Pitch  https //stza.co/+vKnc-J

Shop  https //stza.co/+vKnc-1h

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Red Wings vs. Tides
END:VALARM
DTSTART:20180721T220500Z
DTEND:20180722T010500Z
UID:wyoNWjpVC77RRkBl3pR2Q6bm@stanza.co
SUMMARY:Red Wings vs. Tides
DESCRIPTION:Stick around after the game for a country concert and fireworks for just the price of a game ticket! Act TBD.\n\nThe first 2,000 fans will take home a FREE Wings cap!\n\n\n\nFollow on MiLB First Pitch: https://stza.co/+vKnc-J\n\nShop: https://stza.co/+vKnc-1h\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stick around after the game for some spectacular fireworks!
STATUS:CONFIRMED
CREATED:20180213T144635Z
LAST-MODIFIED:20180213T144635Z
TRANSP:OPAQUE
END:VEVENT
* Red Wings vs. Tides
<2018-07-22 Sun 12:05-15:05>
:PROPERTIES:
:ID:       MDOvhjM3nV10lZYYcijp-8Yo@stanza.co
:LOCATION: First Responder's Day
:STATUS:   CONFIRMED
:END:

Red Wings vs. Tides We'll pay tribute to the police officers, firefighters and EMT's who help keep us safe every day!

Every Sunday kids 12 and under can run the bases with Red Wings mascots Spikes and Mittsy!

Follow on MiLB First Pitch  https //stza.co/+vKnd-14

Shop  https //stza.co/+vKnd-3f

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Red Wings vs. Tides
END:VALARM
DTSTART:20180722T170500Z
DTEND:20180722T200500Z
UID:MDOvhjM3nV10lZYYcijp-8Yo@stanza.co
SUMMARY:Red Wings vs. Tides
DESCRIPTION:We'll pay tribute to the police officers, firefighters and EMT's who help keep us safe every day!\n\nEvery Sunday kids 12 and under can run the bases with Red Wings mascots Spikes and Mittsy!\n\nFollow on MiLB First Pitch: https://stza.co/+vKnd-14\n\nShop: https://stza.co/+vKnd-3f\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:First Responder's Day
STATUS:CONFIRMED
CREATED:20180213T144635Z
LAST-MODIFIED:20180213T144635Z
TRANSP:OPAQUE
END:VEVENT
* Red Wings @ Indians
<2018-07-24 Tue 18:05-21:05>
:PROPERTIES:
:ID:       aK5Tiwb2tCVf9JfRWEVfW-IU@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Red Wings @ Indians Red Wings @ Indians

Follow on MiLB First Pitch  https //stza.co/+vKlj-3w

Shop  https //stza.co/+vKlj-3d

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Red Wings @ Indians
END:VALARM
DTSTART:20180724T230500Z
DTEND:20180725T020500Z
UID:aK5Tiwb2tCVf9JfRWEVfW-IU@stanza.co
SUMMARY:Red Wings @ Indians
DESCRIPTION:Red Wings @ Indians\n\nFollow on MiLB First Pitch: https://stza.co/+vKlj-3w\n\nShop: https://stza.co/+vKlj-3d\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144635Z
LAST-MODIFIED:20180213T144635Z
TRANSP:OPAQUE
END:VEVENT
* Red Wings @ Indians
<2018-07-25 Wed 18:05-21:05>
:PROPERTIES:
:ID:       J917X-S4YBHseRmJHijjAdqc@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Red Wings @ Indians Red Wings @ Indians

Follow on MiLB First Pitch  https //stza.co/+vKlk-2L

Shop  https //stza.co/+vKlk-K

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Red Wings @ Indians
END:VALARM
DTSTART:20180725T230500Z
DTEND:20180726T020500Z
UID:J917X-S4YBHseRmJHijjAdqc@stanza.co
SUMMARY:Red Wings @ Indians
DESCRIPTION:Red Wings @ Indians\n\nFollow on MiLB First Pitch: https://stza.co/+vKlk-2L\n\nShop: https://stza.co/+vKlk-K\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144635Z
LAST-MODIFIED:20180213T144635Z
TRANSP:OPAQUE
END:VEVENT
* Red Wings @ Indians
<2018-07-26 Thu 18:05-21:05>
:PROPERTIES:
:ID:       QxJNx7xhV0MkCTKAwXonHqwb@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Red Wings @ Indians Red Wings @ Indians

Follow on MiLB First Pitch  https //stza.co/+vKll-25

Shop  https //stza.co/+vKll-1w

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Red Wings @ Indians
END:VALARM
DTSTART:20180726T230500Z
DTEND:20180727T020500Z
UID:QxJNx7xhV0MkCTKAwXonHqwb@stanza.co
SUMMARY:Red Wings @ Indians
DESCRIPTION:Red Wings @ Indians\n\nFollow on MiLB First Pitch: https://stza.co/+vKll-25\n\nShop: https://stza.co/+vKll-1w\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144635Z
LAST-MODIFIED:20180213T144635Z
TRANSP:OPAQUE
END:VEVENT
* Red Wings @ Bats
<2018-07-27 Fri 18:00-21:00>
:PROPERTIES:
:ID:       O1QVvKMP6KwyC_Zkuco4Woq1@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Red Wings @ Bats Red Wings @ Bats

Buy tickets here  https //stza.co/~vKlt

Follow on MiLB First Pitch  https //stza.co/+vKlt-3A

Shop  https //stza.co/+vKlt-2S

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Red Wings @ Bats
END:VALARM
DTSTART:20180727T230000Z
DTEND:20180728T020000Z
UID:O1QVvKMP6KwyC_Zkuco4Woq1@stanza.co
SUMMARY:Red Wings @ Bats
DESCRIPTION:Red Wings @ Bats\n\nBuy tickets here: https://stza.co/~vKlt\n\nFollow on MiLB First Pitch: https://stza.co/+vKlt-3A\n\nShop: https://stza.co/+vKlt-2S\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144635Z
LAST-MODIFIED:20180213T144635Z
TRANSP:OPAQUE
END:VEVENT
* Red Wings @ Bats
<2018-07-28 Sat 17:30-20:30>
:PROPERTIES:
:ID:       WQ9axL83khoQK_fAaJmtkXyh@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Red Wings @ Bats Red Wings @ Bats

Buy tickets here  https //stza.co/~vKlu

Follow on MiLB First Pitch  https //stza.co/+vKlu-2Q

Shop  https //stza.co/+vKlu-c

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Red Wings @ Bats
END:VALARM
DTSTART:20180728T223000Z
DTEND:20180729T013000Z
UID:WQ9axL83khoQK_fAaJmtkXyh@stanza.co
SUMMARY:Red Wings @ Bats
DESCRIPTION:Red Wings @ Bats\n\nBuy tickets here: https://stza.co/~vKlu\n\nFollow on MiLB First Pitch: https://stza.co/+vKlu-2Q\n\nShop: https://stza.co/+vKlu-c\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144635Z
LAST-MODIFIED:20180213T144635Z
TRANSP:OPAQUE
END:VEVENT
* Red Wings @ Bats
<2018-07-29 Sun 17:00-20:00>
:PROPERTIES:
:ID:       s-2esfthxeaV6MOCt-8xb1X9@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Red Wings @ Bats Red Wings @ Bats

Buy tickets here  https //stza.co/~vKlv

Follow on MiLB First Pitch  https //stza.co/+vKlv-2b

Shop  https //stza.co/+vKlv-w

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Red Wings @ Bats
END:VALARM
DTSTART:20180729T220000Z
DTEND:20180730T010000Z
UID:s-2esfthxeaV6MOCt-8xb1X9@stanza.co
SUMMARY:Red Wings @ Bats
DESCRIPTION:Red Wings @ Bats\n\nBuy tickets here: https://stza.co/~vKlv\n\nFollow on MiLB First Pitch: https://stza.co/+vKlv-2b\n\nShop: https://stza.co/+vKlv-w\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144635Z
LAST-MODIFIED:20180213T144635Z
TRANSP:OPAQUE
END:VEVENT
* Red Wings vs. RailRiders
<2018-07-30 Mon 18:05-21:05>
:PROPERTIES:
:ID:       aVmpTuB1Q4U-HMWDNZGGmkDV@stanza.co
:LOCATION: Kids Eat Free Mondays
:STATUS:   CONFIRMED
:END:

Red Wings vs. RailRiders Every Monday home game the first 500 kids get a FREE hot dog, snack item and soda!

Follow on MiLB First Pitch  https //stza.co/+vKnf-2k

Shop  https //stza.co/+vKnf-1u

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Red Wings vs. RailRiders
END:VALARM
DTSTART:20180730T230500Z
DTEND:20180731T020500Z
UID:aVmpTuB1Q4U-HMWDNZGGmkDV@stanza.co
SUMMARY:Red Wings vs. RailRiders
DESCRIPTION:Every Monday home game the first 500 kids get a FREE hot dog, snack item and soda!\n\nFollow on MiLB First Pitch: https://stza.co/+vKnf-2k\n\nShop: https://stza.co/+vKnf-1u\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Kids Eat Free Mondays
STATUS:CONFIRMED
CREATED:20180213T144635Z
LAST-MODIFIED:20180213T144635Z
TRANSP:OPAQUE
END:VEVENT
* Red Wings vs. RailRiders
<2018-07-31 Tue 18:05-21:05>
:PROPERTIES:
:ID:       UzpoYg0v68e7XpRs_uJTdkmD@stanza.co
:LOCATION: T-Shirt Tuesday Giveaway
:STATUS:   CONFIRMED
:END:

Red Wings vs. RailRiders The first 500 fans will get a FREE t-shirt!

Follow on MiLB First Pitch  https //stza.co/+vKnh-3J

Shop  https //stza.co/+vKnh-20

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Red Wings vs. RailRiders
END:VALARM
DTSTART:20180731T230500Z
DTEND:20180801T020500Z
UID:UzpoYg0v68e7XpRs_uJTdkmD@stanza.co
SUMMARY:Red Wings vs. RailRiders
DESCRIPTION:The first 500 fans will get a FREE t-shirt!\n\nFollow on MiLB First Pitch: https://stza.co/+vKnh-3J\n\nShop: https://stza.co/+vKnh-20\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:T-Shirt Tuesday Giveaway
STATUS:CONFIRMED
CREATED:20180213T144635Z
LAST-MODIFIED:20180213T144635Z
TRANSP:OPAQUE
END:VEVENT
* Red Wings vs. RailRiders
<2018-08-01 Wed 18:05-21:05>
:PROPERTIES:
:ID:       vOcOhQOlBq04Tx7uxQvql_tm@stanza.co
:LOCATION: $1 Wednesdays
:STATUS:   CONFIRMED
:END:

Red Wings vs. RailRiders Every Wednesday - excluding Wednesday, July 4th - enjoy ONE DOLLAR hot dogs, peanuts, cracker jacks and chips!

Follow on MiLB First Pitch  https //stza.co/+vKnk-g

Shop  https //stza.co/+vKnk-1V

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Red Wings vs. RailRiders
END:VALARM
DTSTART:20180801T230500Z
DTEND:20180802T020500Z
UID:vOcOhQOlBq04Tx7uxQvql_tm@stanza.co
SUMMARY:Red Wings vs. RailRiders
DESCRIPTION:Every Wednesday - excluding Wednesday, July 4th - enjoy ONE DOLLAR hot dogs, peanuts, cracker jacks and chips!\n\nFollow on MiLB First Pitch: https://stza.co/+vKnk-g\n\nShop: https://stza.co/+vKnk-1V\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:$1 Wednesdays
STATUS:CONFIRMED
CREATED:20180213T144635Z
LAST-MODIFIED:20180213T144635Z
TRANSP:OPAQUE
END:VEVENT
* Red Wings vs. RailRiders
<2018-08-02 Thu 11:35-14:35>
:PROPERTIES:
:ID:       4GqIs0yHYUdZjLiSEgybV77m@stanza.co
:LOCATION: Thirsty Thursday Pre-Game Happy Hour
:STATUS:   CONFIRMED
:END:

Red Wings vs. RailRiders Enjoy $2 beers at the 10th Inning Bar from 11 30-12 30.

Every Thursday - college students with a valid college ID can get a reserved ticket AND $5 Diamond Dollars for ONLY $10!

Follow on MiLB First Pitch  https //stza.co/+vKnl-B

Shop  https //stza.co/+vKnl-2k

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Red Wings vs. RailRiders
END:VALARM
DTSTART:20180802T163500Z
DTEND:20180802T193500Z
UID:4GqIs0yHYUdZjLiSEgybV77m@stanza.co
SUMMARY:Red Wings vs. RailRiders
DESCRIPTION:Enjoy $2 beers at the 10th Inning Bar from 11:30-12:30.\n\nEvery Thursday - college students with a valid college ID can get a reserved ticket AND $5 Diamond Dollars for ONLY $10!\n\nFollow on MiLB First Pitch: https://stza.co/+vKnl-B\n\nShop: https://stza.co/+vKnl-2k\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Thirsty Thursday Pre-Game Happy Hour
STATUS:CONFIRMED
CREATED:20180213T144635Z
LAST-MODIFIED:20180213T144635Z
TRANSP:OPAQUE
END:VEVENT
* Red Wings @ Red Sox
<2018-08-03 Fri 18:05-21:05>
:PROPERTIES:
:ID:       WtEhjdWxd_0ttwTHXof6xUc1@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Red Wings @ Red Sox Red Wings @ Red Sox

Buy tickets here  https //stza.co/~vKlE

Follow on MiLB First Pitch  https //stza.co/+vKlE-$

Shop  https //stza.co/+vKlE-3B

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Red Wings @ Red Sox
END:VALARM
DTSTART:20180803T230500Z
DTEND:20180804T020500Z
UID:WtEhjdWxd_0ttwTHXof6xUc1@stanza.co
SUMMARY:Red Wings @ Red Sox
DESCRIPTION:Red Wings @ Red Sox\n\nBuy tickets here: https://stza.co/~vKlE\n\nFollow on MiLB First Pitch: https://stza.co/+vKlE-$\n\nShop: https://stza.co/+vKlE-3B\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144635Z
LAST-MODIFIED:20180213T144635Z
TRANSP:OPAQUE
END:VEVENT
* Red Wings @ Red Sox
<2018-08-04 Sat 17:15-20:15>
:PROPERTIES:
:ID:       z65eLfRnFdwyvhGmsV59RIoD@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Red Wings @ Red Sox Red Wings @ Red Sox

Buy tickets here  https //stza.co/~vKlF

Follow on MiLB First Pitch  https //stza.co/+vKlF-3U

Shop  https //stza.co/+vKlF-3d

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Red Wings @ Red Sox
END:VALARM
DTSTART:20180804T221500Z
DTEND:20180805T011500Z
UID:z65eLfRnFdwyvhGmsV59RIoD@stanza.co
SUMMARY:Red Wings @ Red Sox
DESCRIPTION:Red Wings @ Red Sox\n\nBuy tickets here: https://stza.co/~vKlF\n\nFollow on MiLB First Pitch: https://stza.co/+vKlF-3U\n\nShop: https://stza.co/+vKlF-3d\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144635Z
LAST-MODIFIED:20180213T144635Z
TRANSP:OPAQUE
END:VEVENT
* Red Wings @ Red Sox
<2018-08-05 Sun 12:35-15:35>
:PROPERTIES:
:ID:       7U3SKqRa52xINpvXuFAKTnJs@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Red Wings @ Red Sox Red Wings @ Red Sox

Buy tickets here  https //stza.co/~vKlG

Follow on MiLB First Pitch  https //stza.co/+vKlG-2e

Shop  https //stza.co/+vKlG-12

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Red Wings @ Red Sox
END:VALARM
DTSTART:20180805T173500Z
DTEND:20180805T203500Z
UID:7U3SKqRa52xINpvXuFAKTnJs@stanza.co
SUMMARY:Red Wings @ Red Sox
DESCRIPTION:Red Wings @ Red Sox\n\nBuy tickets here: https://stza.co/~vKlG\n\nFollow on MiLB First Pitch: https://stza.co/+vKlG-2e\n\nShop: https://stza.co/+vKlG-12\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144635Z
LAST-MODIFIED:20180213T144635Z
TRANSP:OPAQUE
END:VEVENT
* Red Wings vs. Mud Hens
<2018-08-07 Tue 18:05-21:05>
:PROPERTIES:
:ID:       r8Tvi_pdGxe8Ua3QFAIXy9hm@stanza.co
:LOCATION: T-shirt Tuesday Giveaway
:STATUS:   CONFIRMED
:END:

Red Wings vs. Mud Hens Free t-shirt giveaway for the first 500 fans in attendance courtesy of Zweigle's!

Follow on MiLB First Pitch  https //stza.co/+vKnn-3A

Shop  https //stza.co/+vKnn-2y

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Red Wings vs. Mud Hens
END:VALARM
DTSTART:20180807T230500Z
DTEND:20180808T020500Z
UID:r8Tvi_pdGxe8Ua3QFAIXy9hm@stanza.co
SUMMARY:Red Wings vs. Mud Hens
DESCRIPTION:Free t-shirt giveaway for the first 500 fans in attendance courtesy of Zweigle's!\n\nFollow on MiLB First Pitch: https://stza.co/+vKnn-3A\n\nShop: https://stza.co/+vKnn-2y\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:T-shirt Tuesday Giveaway
STATUS:CONFIRMED
CREATED:20180213T144635Z
LAST-MODIFIED:20180213T144635Z
TRANSP:OPAQUE
END:VEVENT
* Red Wings vs. Mud Hens
<2018-08-08 Wed 18:05-21:05>
:PROPERTIES:
:ID:       NkgfnM3tpisliJmJWhT1ydDW@stanza.co
:LOCATION: ROC the ROC Night
:STATUS:   CONFIRMED
:END:

Red Wings vs. Mud Hens A celebration of EVERYTHING Rochester! More details to be announced soon.

Every Wednesday - excluding Wednesday, July 4th - enjoy ONE DOLLAR hot dogs, peanuts, cracker jacks and chips!

Follow on MiLB First Pitch  https //stza.co/+vKnq-2J

Shop  https //stza.co/+vKnq-2A

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Red Wings vs. Mud Hens
END:VALARM
DTSTART:20180808T230500Z
DTEND:20180809T020500Z
UID:NkgfnM3tpisliJmJWhT1ydDW@stanza.co
SUMMARY:Red Wings vs. Mud Hens
DESCRIPTION:A celebration of EVERYTHING Rochester! More details to be announced soon.\n\nEvery Wednesday - excluding Wednesday, July 4th - enjoy ONE DOLLAR hot dogs, peanuts, cracker jacks and chips!\n\nFollow on MiLB First Pitch: https://stza.co/+vKnq-2J\n\nShop: https://stza.co/+vKnq-2A\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:ROC the ROC Night
STATUS:CONFIRMED
CREATED:20180213T144635Z
LAST-MODIFIED:20180213T144635Z
TRANSP:OPAQUE
END:VEVENT
* Red Wings vs. Mud Hens
<2018-08-09 Thu 18:05-21:05>
:PROPERTIES:
:ID:       hyxcHj_WZK0Ns5wyyUEeiQq8@stanza.co
:LOCATION: College Thursdays
:STATUS:   CONFIRMED
:END:

Red Wings vs. Mud Hens Every Thursday - college students with a valid college ID can get a reserved ticket AND $5 Diamond Dollars for ONLY $10!

Enjoy $2 beers from 6-7 pm and live music from the Neil Van Dorn Trio at the 10th Inning Bar!

Follow on MiLB First Pitch  https //stza.co/+vKnr-1a

Shop  https //stza.co/+vKnr-3a

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Red Wings vs. Mud Hens
END:VALARM
DTSTART:20180809T230500Z
DTEND:20180810T020500Z
UID:hyxcHj_WZK0Ns5wyyUEeiQq8@stanza.co
SUMMARY:Red Wings vs. Mud Hens
DESCRIPTION:Every Thursday - college students with a valid college ID can get a reserved ticket AND $5 Diamond Dollars for ONLY $10!\n\nEnjoy $2 beers from 6-7 pm and live music from the Neil Van Dorn Trio at the 10th Inning Bar!\n\nFollow on MiLB First Pitch: https://stza.co/+vKnr-1a\n\nShop: https://stza.co/+vKnr-3a\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:College Thursdays
STATUS:CONFIRMED
CREATED:20180213T144635Z
LAST-MODIFIED:20180213T144635Z
TRANSP:OPAQUE
END:VEVENT
* Red Wings vs. Knights
<2018-08-10 Fri 18:05-21:05>
:PROPERTIES:
:ID:       QAeY14yN_qT0yYfJhkA6lon6@stanza.co
:LOCATION: Stick around after the game for some spectacular fireworks!
:STATUS:   CONFIRMED
:END:

Red Wings vs. Knights 

Free update card set giveaway for the first 1,000 fans in attendance courtesy of CollectorFest Monthly!

Follow on MiLB First Pitch  https //stza.co/+vKnt-1q

Shop  https //stza.co/+vKnt-3I

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Red Wings vs. Knights
END:VALARM
DTSTART:20180810T230500Z
DTEND:20180811T020500Z
UID:QAeY14yN_qT0yYfJhkA6lon6@stanza.co
SUMMARY:Red Wings vs. Knights
DESCRIPTION:\n\nFree update card set giveaway for the first 1,000 fans in attendance courtesy of CollectorFest Monthly!\n\nFollow on MiLB First Pitch: https://stza.co/+vKnt-1q\n\nShop: https://stza.co/+vKnt-3I\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stick around after the game for some spectacular fireworks!
STATUS:CONFIRMED
CREATED:20180213T144635Z
LAST-MODIFIED:20180213T144635Z
TRANSP:OPAQUE
END:VEVENT
* Red Wings vs. Knights
<2018-08-11 Sat 18:05-21:05>
:PROPERTIES:
:ID:       2pDAh3y5WYdkuQ9W5vfVnOtm@stanza.co
:LOCATION: Stick around after the game for some spectacular fireworks!
:STATUS:   CONFIRMED
:END:

Red Wings vs. Knights The zany ZOOperstars make their second and final trip of the season to Rochester for what's sure to be one hilarious show!



Follow on MiLB First Pitch  https //stza.co/+vKnv-1B

Shop  https //stza.co/+vKnv-1k

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Red Wings vs. Knights
END:VALARM
DTSTART:20180811T230500Z
DTEND:20180812T020500Z
UID:2pDAh3y5WYdkuQ9W5vfVnOtm@stanza.co
SUMMARY:Red Wings vs. Knights
DESCRIPTION:The zany ZOOperstars make their second and final trip of the season to Rochester for what's sure to be one hilarious show!\n\n\n\nFollow on MiLB First Pitch: https://stza.co/+vKnv-1B\n\nShop: https://stza.co/+vKnv-1k\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stick around after the game for some spectacular fireworks!
STATUS:CONFIRMED
CREATED:20180213T144635Z
LAST-MODIFIED:20180213T144635Z
TRANSP:OPAQUE
END:VEVENT
* Red Wings vs. Knights
<2018-08-12 Sun 12:05-15:05>
:PROPERTIES:
:ID:       dQBqss67NLe2nZ7LmIhoc1wH@stanza.co
:LOCATION: Kids Run the Bases with Spikes and Mittsy
:STATUS:   CONFIRMED
:END:

Red Wings vs. Knights Every Sunday kids 12 and under can run the bases with Red Wings mascots Spikes and Mittsy!

Follow on MiLB First Pitch  https //stza.co/+vKny-G

Shop  https //stza.co/+vKny-w

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Red Wings vs. Knights
END:VALARM
DTSTART:20180812T170500Z
DTEND:20180812T200500Z
UID:dQBqss67NLe2nZ7LmIhoc1wH@stanza.co
SUMMARY:Red Wings vs. Knights
DESCRIPTION:Every Sunday kids 12 and under can run the bases with Red Wings mascots Spikes and Mittsy!\n\nFollow on MiLB First Pitch: https://stza.co/+vKny-G\n\nShop: https://stza.co/+vKny-w\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Kids Run the Bases with Spikes and Mittsy
STATUS:CONFIRMED
CREATED:20180213T144635Z
LAST-MODIFIED:20180213T144635Z
TRANSP:OPAQUE
END:VEVENT
* Red Wings @ Clippers
<2018-08-13 Mon 18:05-21:05>
:PROPERTIES:
:ID:       fOVGW3r5xSFQGtd9pQE8B9ej@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Red Wings @ Clippers Red Wings @ Clippers

Buy tickets here  https //stza.co/~vKl9

Follow on MiLB First Pitch  https //stza.co/+vKl9-i

Shop  https //stza.co/+vKl9-G

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Red Wings @ Clippers
END:VALARM
DTSTART:20180813T230500Z
DTEND:20180814T020500Z
UID:fOVGW3r5xSFQGtd9pQE8B9ej@stanza.co
SUMMARY:Red Wings @ Clippers
DESCRIPTION:Red Wings @ Clippers\n\nBuy tickets here: https://stza.co/~vKl9\n\nFollow on MiLB First Pitch: https://stza.co/+vKl9-i\n\nShop: https://stza.co/+vKl9-G\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144635Z
LAST-MODIFIED:20180213T144635Z
TRANSP:OPAQUE
END:VEVENT
* Red Wings @ Clippers
<2018-08-14 Tue 18:05-21:05>
:PROPERTIES:
:ID:       x5RNee2cRiZa2OjzpugstcIR@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Red Wings @ Clippers Red Wings @ Clippers

Buy tickets here  https //stza.co/~vKla

Follow on MiLB First Pitch  https //stza.co/+vKla-2h

Shop  https //stza.co/+vKla-2M

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Red Wings @ Clippers
END:VALARM
DTSTART:20180814T230500Z
DTEND:20180815T020500Z
UID:x5RNee2cRiZa2OjzpugstcIR@stanza.co
SUMMARY:Red Wings @ Clippers
DESCRIPTION:Red Wings @ Clippers\n\nBuy tickets here: https://stza.co/~vKla\n\nFollow on MiLB First Pitch: https://stza.co/+vKla-2h\n\nShop: https://stza.co/+vKla-2M\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144635Z
LAST-MODIFIED:20180213T144635Z
TRANSP:OPAQUE
END:VEVENT
* Red Wings @ Clippers
<2018-08-15 Wed 11:05-14:05>
:PROPERTIES:
:ID:       qhTX7kgJuoqkXjyFsEUms_oM@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Red Wings @ Clippers Red Wings @ Clippers

Buy tickets here  https //stza.co/~vKlb

Follow on MiLB First Pitch  https //stza.co/+vKlb-2$

Shop  https //stza.co/+vKlb-3H

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Red Wings @ Clippers
END:VALARM
DTSTART:20180815T160500Z
DTEND:20180815T190500Z
UID:qhTX7kgJuoqkXjyFsEUms_oM@stanza.co
SUMMARY:Red Wings @ Clippers
DESCRIPTION:Red Wings @ Clippers\n\nBuy tickets here: https://stza.co/~vKlb\n\nFollow on MiLB First Pitch: https://stza.co/+vKlb-2$\n\nShop: https://stza.co/+vKlb-3H\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144635Z
LAST-MODIFIED:20180213T144635Z
TRANSP:OPAQUE
END:VEVENT
* Red Wings @ Mud Hens
<2018-08-16 Thu 18:05-21:05>
:PROPERTIES:
:ID:       6Fe-dL7KjmM3CCvejpcCYneg@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Red Wings @ Mud Hens Red Wings @ Mud Hens

Follow on MiLB First Pitch  https //stza.co/+vKod-2T

Shop  https //stza.co/+vKod-2x

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Red Wings @ Mud Hens
END:VALARM
DTSTART:20180816T230500Z
DTEND:20180817T020500Z
UID:6Fe-dL7KjmM3CCvejpcCYneg@stanza.co
SUMMARY:Red Wings @ Mud Hens
DESCRIPTION:Red Wings @ Mud Hens\n\nFollow on MiLB First Pitch: https://stza.co/+vKod-2T\n\nShop: https://stza.co/+vKod-2x\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144635Z
LAST-MODIFIED:20180213T144635Z
TRANSP:OPAQUE
END:VEVENT
* Red Wings @ Mud Hens
<2018-08-17 Fri 18:05-21:05>
:PROPERTIES:
:ID:       KxpKN9f1rCImFLRmvH6G6Y8N@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Red Wings @ Mud Hens Red Wings @ Mud Hens

Follow on MiLB First Pitch  https //stza.co/+vKoe-1l

Shop  https //stza.co/+vKoe-1K

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Red Wings @ Mud Hens
END:VALARM
DTSTART:20180817T230500Z
DTEND:20180818T020500Z
UID:KxpKN9f1rCImFLRmvH6G6Y8N@stanza.co
SUMMARY:Red Wings @ Mud Hens
DESCRIPTION:Red Wings @ Mud Hens\n\nFollow on MiLB First Pitch: https://stza.co/+vKoe-1l\n\nShop: https://stza.co/+vKoe-1K\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144635Z
LAST-MODIFIED:20180213T144635Z
TRANSP:OPAQUE
END:VEVENT
* Red Wings @ Mud Hens
<2018-08-18 Sat 18:05-21:05>
:PROPERTIES:
:ID:       xgRVx_xIaXBAUuoCSZSLN_G6@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Red Wings @ Mud Hens Red Wings @ Mud Hens

Follow on MiLB First Pitch  https //stza.co/+vKof-17

Shop  https //stza.co/+vKof-2D

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Red Wings @ Mud Hens
END:VALARM
DTSTART:20180818T230500Z
DTEND:20180819T020500Z
UID:xgRVx_xIaXBAUuoCSZSLN_G6@stanza.co
SUMMARY:Red Wings @ Mud Hens
DESCRIPTION:Red Wings @ Mud Hens\n\nFollow on MiLB First Pitch: https://stza.co/+vKof-17\n\nShop: https://stza.co/+vKof-2D\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144635Z
LAST-MODIFIED:20180213T144635Z
TRANSP:OPAQUE
END:VEVENT
* Red Wings @ Mud Hens
<2018-08-19 Sun 17:05-20:05>
:PROPERTIES:
:ID:       fF_xzDET6Zwo8AWkNQdeYapc@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Red Wings @ Mud Hens Red Wings @ Mud Hens

Follow on MiLB First Pitch  https //stza.co/+vKog-2H

Shop  https //stza.co/+vKog-3O

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Red Wings @ Mud Hens
END:VALARM
DTSTART:20180819T220500Z
DTEND:20180820T010500Z
UID:fF_xzDET6Zwo8AWkNQdeYapc@stanza.co
SUMMARY:Red Wings @ Mud Hens
DESCRIPTION:Red Wings @ Mud Hens\n\nFollow on MiLB First Pitch: https://stza.co/+vKog-2H\n\nShop: https://stza.co/+vKog-3O\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144635Z
LAST-MODIFIED:20180213T144635Z
TRANSP:OPAQUE
END:VEVENT
* Red Wings vs. Red Sox
<2018-08-21 Tue 18:05-21:05>
:PROPERTIES:
:ID:       zs457XZpIrmIDx_6kKK0uBXY@stanza.co
:LOCATION: T-shirt Tuesday Giveaway
:STATUS:   CONFIRMED
:END:

Red Wings vs. Red Sox Free t-shirt giveaway for the first 1500 fans in attendance courtesy of NY 529 College Savings Direct Plan!

Follow on MiLB First Pitch  https //stza.co/+vKnA-27

Shop  https //stza.co/+vKnA-W

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Red Wings vs. Red Sox
END:VALARM
DTSTART:20180821T230500Z
DTEND:20180822T020500Z
UID:zs457XZpIrmIDx_6kKK0uBXY@stanza.co
SUMMARY:Red Wings vs. Red Sox
DESCRIPTION:Free t-shirt giveaway for the first 1500 fans in attendance courtesy of NY 529 College Savings Direct Plan!\n\nFollow on MiLB First Pitch: https://stza.co/+vKnA-27\n\nShop: https://stza.co/+vKnA-W\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:T-shirt Tuesday Giveaway
STATUS:CONFIRMED
CREATED:20180213T144635Z
LAST-MODIFIED:20180213T144635Z
TRANSP:OPAQUE
END:VEVENT
* Red Wings vs. Red Sox
<2018-08-22 Wed 18:05-21:05>
:PROPERTIES:
:ID:       UVSkdDwTMASRFFfA1h42hP0-@stanza.co
:LOCATION: $1 Wednesdays
:STATUS:   CONFIRMED
:END:

Red Wings vs. Red Sox Every Wednesday - excluding Wednesday, July 4th - enjoy ONE DOLLAR hot dogs, peanuts, cracker jacks and chips!

Follow on MiLB First Pitch  https //stza.co/+vKnC-10

Shop  https //stza.co/+vKnC-2b

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Red Wings vs. Red Sox
END:VALARM
DTSTART:20180822T230500Z
DTEND:20180823T020500Z
UID:UVSkdDwTMASRFFfA1h42hP0-@stanza.co
SUMMARY:Red Wings vs. Red Sox
DESCRIPTION:Every Wednesday - excluding Wednesday, July 4th - enjoy ONE DOLLAR hot dogs, peanuts, cracker jacks and chips!\n\nFollow on MiLB First Pitch: https://stza.co/+vKnC-10\n\nShop: https://stza.co/+vKnC-2b\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:$1 Wednesdays
STATUS:CONFIRMED
CREATED:20180213T144635Z
LAST-MODIFIED:20180213T144635Z
TRANSP:OPAQUE
END:VEVENT
* Red Wings vs. Red Sox
<2018-08-23 Thu 18:05-21:05>
:PROPERTIES:
:ID:       fhF6r1rKcZXvhT8nwKMdR7V0@stanza.co
:LOCATION: College Thursdays
:STATUS:   CONFIRMED
:END:

Red Wings vs. Red Sox Every Thursday - college students with a valid college ID can get a reserved ticket AND $5 Diamond Dollars for ONLY $10!

Enjoy $2 beers from 6-7 pm and live music from Genesee Saw at the 10th Inning Bar!

Follow on MiLB First Pitch  https //stza.co/+vKnE-3S

Shop  https //stza.co/+vKnE-2q

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Red Wings vs. Red Sox
END:VALARM
DTSTART:20180823T230500Z
DTEND:20180824T020500Z
UID:fhF6r1rKcZXvhT8nwKMdR7V0@stanza.co
SUMMARY:Red Wings vs. Red Sox
DESCRIPTION:Every Thursday - college students with a valid college ID can get a reserved ticket AND $5 Diamond Dollars for ONLY $10!\n\nEnjoy $2 beers from 6-7 pm and live music from Genesee Saw at the 10th Inning Bar!\n\nFollow on MiLB First Pitch: https://stza.co/+vKnE-3S\n\nShop: https://stza.co/+vKnE-2q\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:College Thursdays
STATUS:CONFIRMED
CREATED:20180213T144635Z
LAST-MODIFIED:20180213T144635Z
TRANSP:OPAQUE
END:VEVENT
* Red Wings @ Chiefs
<2018-08-24 Fri 18:05-21:05>
:PROPERTIES:
:ID:       okzHgAuibIjEFibE_305iR1j@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Red Wings @ Chiefs Red Wings @ Chiefs

Follow on MiLB First Pitch  https //stza.co/+vKo9-3_

Shop  https //stza.co/+vKo9-2_

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Red Wings @ Chiefs
END:VALARM
DTSTART:20180824T230500Z
DTEND:20180825T020500Z
UID:okzHgAuibIjEFibE_305iR1j@stanza.co
SUMMARY:Red Wings @ Chiefs
DESCRIPTION:Red Wings @ Chiefs\n\nFollow on MiLB First Pitch: https://stza.co/+vKo9-3_\n\nShop: https://stza.co/+vKo9-2_\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144635Z
LAST-MODIFIED:20180213T144635Z
TRANSP:OPAQUE
END:VEVENT
* Red Wings @ Chiefs
<2018-08-25 Sat 18:05-21:05>
:PROPERTIES:
:ID:       u4yP24JEx1tg93brPfOT_CpQ@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Red Wings @ Chiefs Red Wings @ Chiefs

Follow on MiLB First Pitch  https //stza.co/+vKoa-E

Shop  https //stza.co/+vKoa-2p

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Red Wings @ Chiefs
END:VALARM
DTSTART:20180825T230500Z
DTEND:20180826T020500Z
UID:u4yP24JEx1tg93brPfOT_CpQ@stanza.co
SUMMARY:Red Wings @ Chiefs
DESCRIPTION:Red Wings @ Chiefs\n\nFollow on MiLB First Pitch: https://stza.co/+vKoa-E\n\nShop: https://stza.co/+vKoa-2p\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144635Z
LAST-MODIFIED:20180213T144635Z
TRANSP:OPAQUE
END:VEVENT
* Red Wings @ Chiefs
<2018-08-26 Sun 12:05-15:05>
:PROPERTIES:
:ID:       s38aE38lGsDZYX54GYcNGZ1h@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Red Wings @ Chiefs Red Wings @ Chiefs

Follow on MiLB First Pitch  https //stza.co/+vKob-2p

Shop  https //stza.co/+vKob-3F

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Red Wings @ Chiefs
END:VALARM
DTSTART:20180826T170500Z
DTEND:20180826T200500Z
UID:s38aE38lGsDZYX54GYcNGZ1h@stanza.co
SUMMARY:Red Wings @ Chiefs
DESCRIPTION:Red Wings @ Chiefs\n\nFollow on MiLB First Pitch: https://stza.co/+vKob-2p\n\nShop: https://stza.co/+vKob-3F\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144635Z
LAST-MODIFIED:20180213T144635Z
TRANSP:OPAQUE
END:VEVENT
* Red Wings @ Chiefs
<2018-08-27 Mon 17:35-20:35>
:PROPERTIES:
:ID:       svTvz9AWhw-e_HN0Y6yytqes@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Red Wings @ Chiefs Red Wings @ Chiefs

Follow on MiLB First Pitch  https //stza.co/+vKoc-29

Shop  https //stza.co/+vKoc-3c

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Red Wings @ Chiefs
END:VALARM
DTSTART:20180827T223500Z
DTEND:20180828T013500Z
UID:svTvz9AWhw-e_HN0Y6yytqes@stanza.co
SUMMARY:Red Wings @ Chiefs
DESCRIPTION:Red Wings @ Chiefs\n\nFollow on MiLB First Pitch: https://stza.co/+vKoc-29\n\nShop: https://stza.co/+vKoc-3c\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144635Z
LAST-MODIFIED:20180213T144635Z
TRANSP:OPAQUE
END:VEVENT
* Red Wings vs. Bisons
<2018-08-28 Tue 18:05-21:05>
:PROPERTIES:
:ID:       RAFl3zAoqy0A3m2x4dANlOeU@stanza.co
:LOCATION: T-shirt Tuesday Giveaway
:STATUS:   CONFIRMED
:END:

Red Wings vs. Bisons First 500 fans get a FREE t-shirt!

Follow on MiLB First Pitch  https //stza.co/+vKnF-3o

Shop  https //stza.co/+vKnF-F

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Red Wings vs. Bisons
END:VALARM
DTSTART:20180828T230500Z
DTEND:20180829T020500Z
UID:RAFl3zAoqy0A3m2x4dANlOeU@stanza.co
SUMMARY:Red Wings vs. Bisons
DESCRIPTION:First 500 fans get a FREE t-shirt!\n\nFollow on MiLB First Pitch: https://stza.co/+vKnF-3o\n\nShop: https://stza.co/+vKnF-F\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:T-shirt Tuesday Giveaway
STATUS:CONFIRMED
CREATED:20180213T144635Z
LAST-MODIFIED:20180213T144635Z
TRANSP:OPAQUE
END:VEVENT
* Red Wings vs. Bisons
<2018-08-29 Wed 18:05-21:05>
:PROPERTIES:
:ID:       A1k_6OsXdV9aPFXQgAgMsqwZ@stanza.co
:LOCATION: $1 Wednesdays
:STATUS:   CONFIRMED
:END:

Red Wings vs. Bisons Every Wednesday - excluding Wednesday, July 4th - enjoy ONE DOLLAR hot dogs, peanuts, cracker jacks and chips!

Follow on MiLB First Pitch  https //stza.co/+vKnH-G

Shop  https //stza.co/+vKnH-2y

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Red Wings vs. Bisons
END:VALARM
DTSTART:20180829T230500Z
DTEND:20180830T020500Z
UID:A1k_6OsXdV9aPFXQgAgMsqwZ@stanza.co
SUMMARY:Red Wings vs. Bisons
DESCRIPTION:Every Wednesday - excluding Wednesday, July 4th - enjoy ONE DOLLAR hot dogs, peanuts, cracker jacks and chips!\n\nFollow on MiLB First Pitch: https://stza.co/+vKnH-G\n\nShop: https://stza.co/+vKnH-2y\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:$1 Wednesdays
STATUS:CONFIRMED
CREATED:20180213T144635Z
LAST-MODIFIED:20180213T144635Z
TRANSP:OPAQUE
END:VEVENT
* Red Wings vs. Bisons
<2018-08-30 Thu 18:05-21:05>
:PROPERTIES:
:ID:       IpIrAso7XMgds9eLqbPFsaoj@stanza.co
:LOCATION: College Thursdays
:STATUS:   CONFIRMED
:END:

Red Wings vs. Bisons Every Thursday - college students with a valid college ID can get a reserved ticket AND $5 Diamond Dollars for ONLY $10!

Enjoy $2 beers from 6-7 pm and live music out at the 10th Inning Bar!

Follow on MiLB First Pitch  https //stza.co/+vKnK-3l

Shop  https //stza.co/+vKnK-2J

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Red Wings vs. Bisons
END:VALARM
DTSTART:20180830T230500Z
DTEND:20180831T020500Z
UID:IpIrAso7XMgds9eLqbPFsaoj@stanza.co
SUMMARY:Red Wings vs. Bisons
DESCRIPTION:Every Thursday - college students with a valid college ID can get a reserved ticket AND $5 Diamond Dollars for ONLY $10!\n\nEnjoy $2 beers from 6-7 pm and live music out at the 10th Inning Bar!\n\nFollow on MiLB First Pitch: https://stza.co/+vKnK-3l\n\nShop: https://stza.co/+vKnK-2J\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:College Thursdays
STATUS:CONFIRMED
CREATED:20180213T144635Z
LAST-MODIFIED:20180213T144635Z
TRANSP:OPAQUE
END:VEVENT
* Red Wings vs. IronPigs
<2018-08-31 Fri 18:05-21:05>
:PROPERTIES:
:ID:       -sHuQSD0hfJEsiGxMy0ZYIwN@stanza.co
:LOCATION: Stick around after the game for some spectacular fireworks!
:STATUS:   CONFIRMED
:END:

Red Wings vs. IronPigs 

Spend a night under the stars at Frontier Field on Friday, August 31! After the game we'll be showing the movie 'The Sandlot'. No extra ticket - other than your game ticket - is needed to stay over.

Follow on MiLB First Pitch  https //stza.co/+vKnM-1s

Shop  https //stza.co/+vKnM-4

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Red Wings vs. IronPigs
END:VALARM
DTSTART:20180831T230500Z
DTEND:20180901T020500Z
UID:-sHuQSD0hfJEsiGxMy0ZYIwN@stanza.co
SUMMARY:Red Wings vs. IronPigs
DESCRIPTION:\n\nSpend a night under the stars at Frontier Field on Friday, August 31! After the game we'll be showing the movie 'The Sandlot'. No extra ticket - other than your game ticket - is needed to stay over.\n\nFollow on MiLB First Pitch: https://stza.co/+vKnM-1s\n\nShop: https://stza.co/+vKnM-4\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stick around after the game for some spectacular fireworks!
STATUS:CONFIRMED
CREATED:20180213T144635Z
LAST-MODIFIED:20180213T144635Z
TRANSP:OPAQUE
END:VEVENT
* Red Wings vs. IronPigs
<2018-09-01 Sat 17:05-20:05>
:PROPERTIES:
:ID:       DRbwDHzGPARc7gZ8MrWLhUO3@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Red Wings vs. IronPigs Red Wings vs. IronPigs

Follow on MiLB First Pitch  https //stza.co/+vKnO-2p

Shop  https //stza.co/+vKnO-26

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Red Wings vs. IronPigs
END:VALARM
DTSTART:20180901T220500Z
DTEND:20180902T010500Z
UID:DRbwDHzGPARc7gZ8MrWLhUO3@stanza.co
SUMMARY:Red Wings vs. IronPigs
DESCRIPTION:Red Wings vs. IronPigs\n\nFollow on MiLB First Pitch: https://stza.co/+vKnO-2p\n\nShop: https://stza.co/+vKnO-26\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144635Z
LAST-MODIFIED:20180213T144635Z
TRANSP:OPAQUE
END:VEVENT
* Red Wings vs. IronPigs
<2018-09-02 Sun 17:05-20:05>
:PROPERTIES:
:ID:       ZEmiFgsUUHbsZcaRHQZf8ovJ@stanza.co
:LOCATION: Stick around after the game for some spectacular fireworks!
:STATUS:   CONFIRMED
:END:

Red Wings vs. IronPigs Every Sunday kids 12 and under can run the bases with Red Wings mascots Spikes and Mittsy!



Follow on MiLB First Pitch  https //stza.co/+wjvY-4

Shop  https //stza.co/+wjvY-1o

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Red Wings vs. IronPigs
END:VALARM
DTSTART:20180902T220500Z
DTEND:20180903T010500Z
UID:ZEmiFgsUUHbsZcaRHQZf8ovJ@stanza.co
SUMMARY:Red Wings vs. IronPigs
DESCRIPTION:Every Sunday kids 12 and under can run the bases with Red Wings mascots Spikes and Mittsy!\n\n\n\nFollow on MiLB First Pitch: https://stza.co/+wjvY-4\n\nShop: https://stza.co/+wjvY-1o\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stick around after the game for some spectacular fireworks!
STATUS:CONFIRMED
CREATED:20180213T144635Z
LAST-MODIFIED:20180213T144635Z
TRANSP:OPAQUE
END:VEVENT
* Red Wings vs. IronPigs
<2018-09-03 Mon 12:05-15:05>
:PROPERTIES:
:ID:       LXUg3ZVWB7adhPir_5FFtJ0h@stanza.co
:LOCATION: Kids Eat Free Mondays
:STATUS:   CONFIRMED
:END:

Red Wings vs. IronPigs Every Monday home game the first 500 kids get a FREE hot dog, snack item and soda!

Follow on MiLB First Pitch  https //stza.co/+vKnS-11

Shop  https //stza.co/+vKnS-P

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Red Wings vs. IronPigs
END:VALARM
DTSTART:20180903T170500Z
DTEND:20180903T200500Z
UID:LXUg3ZVWB7adhPir_5FFtJ0h@stanza.co
SUMMARY:Red Wings vs. IronPigs
DESCRIPTION:Every Monday home game the first 500 kids get a FREE hot dog, snack item and soda!\n\nFollow on MiLB First Pitch: https://stza.co/+vKnS-11\n\nShop: https://stza.co/+vKnS-P\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Kids Eat Free Mondays
STATUS:CONFIRMED
CREATED:20180213T144635Z
LAST-MODIFIED:20180213T144635Z
TRANSP:OPAQUE
END:VEVENT
