#+TITLE:       Main Google calendar entries
#+AUTHOR:      Eric S Fraga
#+EMAIL:       e.fraga@ucl.ac.uk
#+DESCRIPTION: converted using the ical2org awk script
#+CATEGORY:    google
#+STARTUP:     hidestars
#+STARTUP:     overview

* COMMENT original iCal preamble

* Drillers @ RoughRiders
<2018-04-05 Thu 19:05-22:05>
:PROPERTIES:
:ID:       WZrQ80hPS64fnktEsGR77FT1@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Drillers @ RoughRiders Drillers @ RoughRiders

Follow on MiLB First Pitch  https //stza.co/+wYd2-3H

Shop  https //stza.co/+wYd2-P

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Drillers @ RoughRiders
END:VALARM
DTSTART:20180406T000500Z
DTEND:20180406T030500Z
UID:WZrQ80hPS64fnktEsGR77FT1@stanza.co
SUMMARY:Drillers @ RoughRiders
DESCRIPTION:Drillers @ RoughRiders\n\nFollow on MiLB First Pitch: https://stza.co/+wYd2-3H\n\nShop: https://stza.co/+wYd2-P\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Drillers @ RoughRiders
<2018-04-06 Fri 19:05-22:05>
:PROPERTIES:
:ID:       FGPbO4yUJItyE5wcZZONBQX_@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Drillers @ RoughRiders Drillers @ RoughRiders

Follow on MiLB First Pitch  https //stza.co/+wYd3-2i

Shop  https //stza.co/+wYd3-1x

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Drillers @ RoughRiders
END:VALARM
DTSTART:20180407T000500Z
DTEND:20180407T030500Z
UID:FGPbO4yUJItyE5wcZZONBQX_@stanza.co
SUMMARY:Drillers @ RoughRiders
DESCRIPTION:Drillers @ RoughRiders\n\nFollow on MiLB First Pitch: https://stza.co/+wYd3-2i\n\nShop: https://stza.co/+wYd3-1x\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Drillers @ RoughRiders
<2018-04-07 Sat 19:05-22:05>
:PROPERTIES:
:ID:       Oqn00jPzC9INUh71RzYaWip2@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Drillers @ RoughRiders Drillers @ RoughRiders

Follow on MiLB First Pitch  https //stza.co/+wYd4-3S

Shop  https //stza.co/+wYd4-3W

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Drillers @ RoughRiders
END:VALARM
DTSTART:20180408T000500Z
DTEND:20180408T030500Z
UID:Oqn00jPzC9INUh71RzYaWip2@stanza.co
SUMMARY:Drillers @ RoughRiders
DESCRIPTION:Drillers @ RoughRiders\n\nFollow on MiLB First Pitch: https://stza.co/+wYd4-3S\n\nShop: https://stza.co/+wYd4-3W\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Drillers @ RockHounds
<2018-04-08 Sun 16:00-19:00>
:PROPERTIES:
:ID:       cQXfp4rm5j4palGQS6L0jGLQ@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Drillers @ RockHounds Drillers @ RockHounds

Follow on MiLB First Pitch  https //stza.co/+wX5Z-1c

Shop  https //stza.co/+wX5Z-12

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Drillers @ RockHounds
END:VALARM
DTSTART:20180408T210000Z
DTEND:20180409T000000Z
UID:cQXfp4rm5j4palGQS6L0jGLQ@stanza.co
SUMMARY:Drillers @ RockHounds
DESCRIPTION:Drillers @ RockHounds\n\nFollow on MiLB First Pitch: https://stza.co/+wX5Z-1c\n\nShop: https://stza.co/+wX5Z-12\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Drillers @ RockHounds
<2018-04-09 Mon 18:30-21:30>
:PROPERTIES:
:ID:       Vp7TtY-bntVKJo6JfF5COyO_@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Drillers @ RockHounds Drillers @ RockHounds

Follow on MiLB First Pitch  https //stza.co/+wX5_-1M

Shop  https //stza.co/+wX5_-2z

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Drillers @ RockHounds
END:VALARM
DTSTART:20180409T233000Z
DTEND:20180410T023000Z
UID:Vp7TtY-bntVKJo6JfF5COyO_@stanza.co
SUMMARY:Drillers @ RockHounds
DESCRIPTION:Drillers @ RockHounds\n\nFollow on MiLB First Pitch: https://stza.co/+wX5_-1M\n\nShop: https://stza.co/+wX5_-2z\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Drillers @ RockHounds
<2018-04-10 Tue 18:30-21:30>
:PROPERTIES:
:ID:       mQUpAPpn6NzAy5E5TFLNX3A8@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Drillers @ RockHounds Drillers @ RockHounds

Follow on MiLB First Pitch  https //stza.co/+wX5$-2_

Shop  https //stza.co/+wX5$-2l

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Drillers @ RockHounds
END:VALARM
DTSTART:20180410T233000Z
DTEND:20180411T023000Z
UID:mQUpAPpn6NzAy5E5TFLNX3A8@stanza.co
SUMMARY:Drillers @ RockHounds
DESCRIPTION:Drillers @ RockHounds\n\nFollow on MiLB First Pitch: https://stza.co/+wX5$-2_\n\nShop: https://stza.co/+wX5$-2l\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Drillers vs. RoughRiders
<2018-04-12 Thu 19:05-22:05>
:PROPERTIES:
:ID:       rZhQtrICdSElV4ZTCyjq4BxJ@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Drillers vs. RoughRiders Drillers vs. RoughRiders

Follow on MiLB First Pitch  https //stza.co/+w0eH-3h

Shop  https //stza.co/+w0eH-1Z

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Drillers vs. RoughRiders
END:VALARM
DTSTART:20180413T000500Z
DTEND:20180413T030500Z
UID:rZhQtrICdSElV4ZTCyjq4BxJ@stanza.co
SUMMARY:Drillers vs. RoughRiders
DESCRIPTION:Drillers vs. RoughRiders\n\nFollow on MiLB First Pitch: https://stza.co/+w0eH-3h\n\nShop: https://stza.co/+w0eH-1Z\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Drillers vs. RoughRiders
<2018-04-13 Fri 19:05-22:05>
:PROPERTIES:
:ID:       IsAkq01LWDxqYYBlpNzSk2xc@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Drillers vs. RoughRiders Drillers vs. RoughRiders

Follow on MiLB First Pitch  https //stza.co/+w0eJ-P

Shop  https //stza.co/+w0eJ-2M

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Drillers vs. RoughRiders
END:VALARM
DTSTART:20180414T000500Z
DTEND:20180414T030500Z
UID:IsAkq01LWDxqYYBlpNzSk2xc@stanza.co
SUMMARY:Drillers vs. RoughRiders
DESCRIPTION:Drillers vs. RoughRiders\n\nFollow on MiLB First Pitch: https://stza.co/+w0eJ-P\n\nShop: https://stza.co/+w0eJ-2M\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Drillers vs. RoughRiders
<2018-04-14 Sat 19:05-22:05>
:PROPERTIES:
:ID:       go6jQEicAvNXRWLfPfASd3zo@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Drillers vs. RoughRiders Drillers vs. RoughRiders

Follow on MiLB First Pitch  https //stza.co/+w0eK-D

Shop  https //stza.co/+w0eK-3Q

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Drillers vs. RoughRiders
END:VALARM
DTSTART:20180415T000500Z
DTEND:20180415T030500Z
UID:go6jQEicAvNXRWLfPfASd3zo@stanza.co
SUMMARY:Drillers vs. RoughRiders
DESCRIPTION:Drillers vs. RoughRiders\n\nFollow on MiLB First Pitch: https://stza.co/+w0eK-D\n\nShop: https://stza.co/+w0eK-3Q\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Drillers vs. RockHounds
<2018-04-15 Sun 16:05-19:05>
:PROPERTIES:
:ID:       cV834Sk4ZwDjnapRDI3QFtPn@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Drillers vs. RockHounds Drillers vs. RockHounds

Follow on MiLB First Pitch  https //stza.co/+w0eM-c

Shop  https //stza.co/+w0eM-x

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Drillers vs. RockHounds
END:VALARM
DTSTART:20180415T210500Z
DTEND:20180416T000500Z
UID:cV834Sk4ZwDjnapRDI3QFtPn@stanza.co
SUMMARY:Drillers vs. RockHounds
DESCRIPTION:Drillers vs. RockHounds\n\nFollow on MiLB First Pitch: https://stza.co/+w0eM-c\n\nShop: https://stza.co/+w0eM-x\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Drillers vs. RockHounds
<2018-04-16 Mon 16:05-19:05>
:PROPERTIES:
:ID:       s0X_-c-8oYRipjvtYkyyuar6@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Drillers vs. RockHounds Drillers vs. RockHounds

Follow on MiLB First Pitch  https //stza.co/+w0eO-Z

Shop  https //stza.co/+w0eO-3F

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Drillers vs. RockHounds
END:VALARM
DTSTART:20180416T210500Z
DTEND:20180417T000500Z
UID:s0X_-c-8oYRipjvtYkyyuar6@stanza.co
SUMMARY:Drillers vs. RockHounds
DESCRIPTION:Drillers vs. RockHounds\n\nFollow on MiLB First Pitch: https://stza.co/+w0eO-Z\n\nShop: https://stza.co/+w0eO-3F\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Drillers vs. RockHounds
<2018-04-17 Tue 19:05-22:05>
:PROPERTIES:
:ID:       C2ZJ9cUfqEYV-nFCj3mf18CL@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Drillers vs. RockHounds Drillers vs. RockHounds

Follow on MiLB First Pitch  https //stza.co/+w0eQ-o

Shop  https //stza.co/+w0eQ-2p

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Drillers vs. RockHounds
END:VALARM
DTSTART:20180418T000500Z
DTEND:20180418T030500Z
UID:C2ZJ9cUfqEYV-nFCj3mf18CL@stanza.co
SUMMARY:Drillers vs. RockHounds
DESCRIPTION:Drillers vs. RockHounds\n\nFollow on MiLB First Pitch: https://stza.co/+w0eQ-o\n\nShop: https://stza.co/+w0eQ-2p\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Drillers @ Naturals
<2018-04-19 Thu 19:05-22:05>
:PROPERTIES:
:ID:       UAA3XWAa5v95i36r76sUrCgk@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Drillers @ Naturals Drillers @ Naturals

Follow on MiLB First Pitch  https //stza.co/+wi4i-2T

Shop  https //stza.co/+wi4i-1E

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Drillers @ Naturals
END:VALARM
DTSTART:20180420T000500Z
DTEND:20180420T030500Z
UID:UAA3XWAa5v95i36r76sUrCgk@stanza.co
SUMMARY:Drillers @ Naturals
DESCRIPTION:Drillers @ Naturals\n\nFollow on MiLB First Pitch: https://stza.co/+wi4i-2T\n\nShop: https://stza.co/+wi4i-1E\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Drillers @ Naturals
<2018-04-20 Fri 19:05-22:05>
:PROPERTIES:
:ID:       R73-Wa4inkRJyRvGuoI20cdf@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Drillers @ Naturals Drillers @ Naturals

Follow on MiLB First Pitch  https //stza.co/+wi4j-2U

Shop  https //stza.co/+wi4j-P

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Drillers @ Naturals
END:VALARM
DTSTART:20180421T000500Z
DTEND:20180421T030500Z
UID:R73-Wa4inkRJyRvGuoI20cdf@stanza.co
SUMMARY:Drillers @ Naturals
DESCRIPTION:Drillers @ Naturals\n\nFollow on MiLB First Pitch: https://stza.co/+wi4j-2U\n\nShop: https://stza.co/+wi4j-P\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Drillers vs. Naturals
<2018-04-21 Sat 19:05-22:05>
:PROPERTIES:
:ID:       FerWDTC8u9fuhSWf6OvPI6d4@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Drillers vs. Naturals Drillers vs. Naturals

Follow on MiLB First Pitch  https //stza.co/+w0eT-34

Shop  https //stza.co/+w0eT-1K

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Drillers vs. Naturals
END:VALARM
DTSTART:20180422T000500Z
DTEND:20180422T030500Z
UID:FerWDTC8u9fuhSWf6OvPI6d4@stanza.co
SUMMARY:Drillers vs. Naturals
DESCRIPTION:Drillers vs. Naturals\n\nFollow on MiLB First Pitch: https://stza.co/+w0eT-34\n\nShop: https://stza.co/+w0eT-1K\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Drillers vs. Naturals
<2018-04-22 Sun 13:05-16:05>
:PROPERTIES:
:ID:       zDO_ealX7rZJSTgi_oFcaroC@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Drillers vs. Naturals Drillers vs. Naturals

Follow on MiLB First Pitch  https //stza.co/+w0eV-2W

Shop  https //stza.co/+w0eV-1q

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Drillers vs. Naturals
END:VALARM
DTSTART:20180422T180500Z
DTEND:20180422T210500Z
UID:zDO_ealX7rZJSTgi_oFcaroC@stanza.co
SUMMARY:Drillers vs. Naturals
DESCRIPTION:Drillers vs. Naturals\n\nFollow on MiLB First Pitch: https://stza.co/+w0eV-2W\n\nShop: https://stza.co/+w0eV-1q\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Drillers @ Travelers
<2018-04-23 Mon 19:10-22:10>
:PROPERTIES:
:ID:       9-Dr0Y_PLkKtZL5KkJaHwBm5@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Drillers @ Travelers Drillers @ Travelers

Follow on MiLB First Pitch  https //stza.co/+w0dA-1Y

Shop  https //stza.co/+w0dA-1j

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Drillers @ Travelers
END:VALARM
DTSTART:20180424T001000Z
DTEND:20180424T031000Z
UID:9-Dr0Y_PLkKtZL5KkJaHwBm5@stanza.co
SUMMARY:Drillers @ Travelers
DESCRIPTION:Drillers @ Travelers\n\nFollow on MiLB First Pitch: https://stza.co/+w0dA-1Y\n\nShop: https://stza.co/+w0dA-1j\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Drillers @ Travelers
<2018-04-24 Tue 11:00-14:00>
:PROPERTIES:
:ID:       GvF8muMaQ1BFPp5gPDNkdDRa@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Drillers @ Travelers Drillers @ Travelers

Follow on MiLB First Pitch  https //stza.co/+w0dB-3r

Shop  https //stza.co/+w0dB-3b

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Drillers @ Travelers
END:VALARM
DTSTART:20180424T160000Z
DTEND:20180424T190000Z
UID:GvF8muMaQ1BFPp5gPDNkdDRa@stanza.co
SUMMARY:Drillers @ Travelers
DESCRIPTION:Drillers @ Travelers\n\nFollow on MiLB First Pitch: https://stza.co/+w0dB-3r\n\nShop: https://stza.co/+w0dB-3b\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Drillers @ Travelers
<2018-04-25 Wed 19:10-22:10>
:PROPERTIES:
:ID:       TAc2zsAzgYkkgcm49FrjdrPw@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Drillers @ Travelers Drillers @ Travelers

Follow on MiLB First Pitch  https //stza.co/+w0dC-2B

Shop  https //stza.co/+w0dC-3q

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Drillers @ Travelers
END:VALARM
DTSTART:20180426T001000Z
DTEND:20180426T031000Z
UID:TAc2zsAzgYkkgcm49FrjdrPw@stanza.co
SUMMARY:Drillers @ Travelers
DESCRIPTION:Drillers @ Travelers\n\nFollow on MiLB First Pitch: https://stza.co/+w0dC-2B\n\nShop: https://stza.co/+w0dC-3q\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Drillers @ Travelers
<2018-04-26 Thu 19:10-22:10>
:PROPERTIES:
:ID:       WBioAWFSE8TcfudFhbjpjS16@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Drillers @ Travelers Drillers @ Travelers

Follow on MiLB First Pitch  https //stza.co/+w0dD-3r

Shop  https //stza.co/+w0dD-Y

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Drillers @ Travelers
END:VALARM
DTSTART:20180427T001000Z
DTEND:20180427T031000Z
UID:WBioAWFSE8TcfudFhbjpjS16@stanza.co
SUMMARY:Drillers @ Travelers
DESCRIPTION:Drillers @ Travelers\n\nFollow on MiLB First Pitch: https://stza.co/+w0dD-3r\n\nShop: https://stza.co/+w0dD-Y\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Drillers vs. Naturals
<2018-04-27 Fri 19:05-22:05>
:PROPERTIES:
:ID:       AWQBwy0om0LYI591y8C-9mRf@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Drillers vs. Naturals Drillers vs. Naturals

Follow on MiLB First Pitch  https //stza.co/+w0eX-K

Shop  https //stza.co/+w0eX-2A

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Drillers vs. Naturals
END:VALARM
DTSTART:20180428T000500Z
DTEND:20180428T030500Z
UID:AWQBwy0om0LYI591y8C-9mRf@stanza.co
SUMMARY:Drillers vs. Naturals
DESCRIPTION:Drillers vs. Naturals\n\nFollow on MiLB First Pitch: https://stza.co/+w0eX-K\n\nShop: https://stza.co/+w0eX-2A\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Drillers @ Naturals
<2018-04-28 Sat 18:05-21:05>
:PROPERTIES:
:ID:       cLrku_0qEZfW0_c7K-CWpzQM@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Drillers @ Naturals Drillers @ Naturals

Follow on MiLB First Pitch  https //stza.co/+wi4m-3F

Shop  https //stza.co/+wi4m-3M

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Drillers @ Naturals
END:VALARM
DTSTART:20180428T230500Z
DTEND:20180429T020500Z
UID:cLrku_0qEZfW0_c7K-CWpzQM@stanza.co
SUMMARY:Drillers @ Naturals
DESCRIPTION:Drillers @ Naturals\n\nFollow on MiLB First Pitch: https://stza.co/+wi4m-3F\n\nShop: https://stza.co/+wi4m-3M\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Drillers @ Naturals
<2018-04-29 Sun 14:05-17:05>
:PROPERTIES:
:ID:       L7yUHQQgpFByIpHtp-p1kkiq@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Drillers @ Naturals Drillers @ Naturals

Follow on MiLB First Pitch  https //stza.co/+wi4n-2e

Shop  https //stza.co/+wi4n-D

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Drillers @ Naturals
END:VALARM
DTSTART:20180429T190500Z
DTEND:20180429T220500Z
UID:L7yUHQQgpFByIpHtp-p1kkiq@stanza.co
SUMMARY:Drillers @ Naturals
DESCRIPTION:Drillers @ Naturals\n\nFollow on MiLB First Pitch: https://stza.co/+wi4n-2e\n\nShop: https://stza.co/+wi4n-D\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Drillers vs. Naturals
<2018-04-30 Mon 11:05-14:05>
:PROPERTIES:
:ID:       V1ewYWbfizkFwrmncHaKyIrl@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Drillers vs. Naturals Drillers vs. Naturals

Follow on MiLB First Pitch  https //stza.co/+w0eY-3

Shop  https //stza.co/+w0eY-10

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Drillers vs. Naturals
END:VALARM
DTSTART:20180430T160500Z
DTEND:20180430T190500Z
UID:V1ewYWbfizkFwrmncHaKyIrl@stanza.co
SUMMARY:Drillers vs. Naturals
DESCRIPTION:Drillers vs. Naturals\n\nFollow on MiLB First Pitch: https://stza.co/+w0eY-3\n\nShop: https://stza.co/+w0eY-10\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Drillers vs. Travelers
<2018-05-01 Tue 19:05-22:05>
:PROPERTIES:
:ID:       yRnhazweVuZNTUDLP2_-ipZB@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Drillers vs. Travelers Drillers vs. Travelers

Follow on MiLB First Pitch  https //stza.co/+w0e_-1K

Shop  https //stza.co/+w0e_-3S

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Drillers vs. Travelers
END:VALARM
DTSTART:20180502T000500Z
DTEND:20180502T030500Z
UID:yRnhazweVuZNTUDLP2_-ipZB@stanza.co
SUMMARY:Drillers vs. Travelers
DESCRIPTION:Drillers vs. Travelers\n\nFollow on MiLB First Pitch: https://stza.co/+w0e_-1K\n\nShop: https://stza.co/+w0e_-3S\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Drillers vs. Travelers
<2018-05-02 Wed 12:05-15:05>
:PROPERTIES:
:ID:       3Ddwm528Ug0F9EGjGUviVP0M@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Drillers vs. Travelers Drillers vs. Travelers

Follow on MiLB First Pitch  https //stza.co/+w0f1-1z

Shop  https //stza.co/+w0f1-2R

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Drillers vs. Travelers
END:VALARM
DTSTART:20180502T170500Z
DTEND:20180502T200500Z
UID:3Ddwm528Ug0F9EGjGUviVP0M@stanza.co
SUMMARY:Drillers vs. Travelers
DESCRIPTION:Drillers vs. Travelers\n\nFollow on MiLB First Pitch: https://stza.co/+w0f1-1z\n\nShop: https://stza.co/+w0f1-2R\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Drillers vs. Travelers
<2018-05-03 Thu 19:05-22:05>
:PROPERTIES:
:ID:       vhLp61BJ3ZuPSrSp6knsZQvh@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Drillers vs. Travelers Drillers vs. Travelers

Follow on MiLB First Pitch  https //stza.co/+w0f2-2S

Shop  https //stza.co/+w0f2-2R

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Drillers vs. Travelers
END:VALARM
DTSTART:20180504T000500Z
DTEND:20180504T030500Z
UID:vhLp61BJ3ZuPSrSp6knsZQvh@stanza.co
SUMMARY:Drillers vs. Travelers
DESCRIPTION:Drillers vs. Travelers\n\nFollow on MiLB First Pitch: https://stza.co/+w0f2-2S\n\nShop: https://stza.co/+w0f2-2R\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Drillers vs. Travelers
<2018-05-04 Fri 19:05-22:05>
:PROPERTIES:
:ID:       36THgkFQajGeNQNdMaGBYOgt@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Drillers vs. Travelers Drillers vs. Travelers

Follow on MiLB First Pitch  https //stza.co/+w0f5-X

Shop  https //stza.co/+w0f5-21

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Drillers vs. Travelers
END:VALARM
DTSTART:20180505T000500Z
DTEND:20180505T030500Z
UID:36THgkFQajGeNQNdMaGBYOgt@stanza.co
SUMMARY:Drillers vs. Travelers
DESCRIPTION:Drillers vs. Travelers\n\nFollow on MiLB First Pitch: https://stza.co/+w0f5-X\n\nShop: https://stza.co/+w0f5-21\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Drillers @ Cardinals
<2018-05-05 Sat 18:10-21:10>
:PROPERTIES:
:ID:       gdenBibJ1UNRQa6UFaH3lb9O@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Drillers @ Cardinals Drillers @ Cardinals

Follow on MiLB First Pitch  https //stza.co/+wPQO-3F

Shop  https //stza.co/+wPQO-1_

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Drillers @ Cardinals
END:VALARM
DTSTART:20180505T231000Z
DTEND:20180506T021000Z
UID:gdenBibJ1UNRQa6UFaH3lb9O@stanza.co
SUMMARY:Drillers @ Cardinals
DESCRIPTION:Drillers @ Cardinals\n\nFollow on MiLB First Pitch: https://stza.co/+wPQO-3F\n\nShop: https://stza.co/+wPQO-1_\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Drillers @ Cardinals
<2018-05-06 Sun 14:10-17:10>
:PROPERTIES:
:ID:       AKshay--YjZof0lzs1esN1KQ@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Drillers @ Cardinals Drillers @ Cardinals

Follow on MiLB First Pitch  https //stza.co/+wPQP-24

Shop  https //stza.co/+wPQP-3B

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Drillers @ Cardinals
END:VALARM
DTSTART:20180506T191000Z
DTEND:20180506T221000Z
UID:AKshay--YjZof0lzs1esN1KQ@stanza.co
SUMMARY:Drillers @ Cardinals
DESCRIPTION:Drillers @ Cardinals\n\nFollow on MiLB First Pitch: https://stza.co/+wPQP-24\n\nShop: https://stza.co/+wPQP-3B\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Drillers @ Cardinals
<2018-05-07 Mon 11:10-14:10>
:PROPERTIES:
:ID:       TSQ6qHCpqhIAmwpSsto5TzMg@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Drillers @ Cardinals Drillers @ Cardinals

Follow on MiLB First Pitch  https //stza.co/+wPQQ-3K

Shop  https //stza.co/+wPQQ-3I

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Drillers @ Cardinals
END:VALARM
DTSTART:20180507T161000Z
DTEND:20180507T191000Z
UID:TSQ6qHCpqhIAmwpSsto5TzMg@stanza.co
SUMMARY:Drillers @ Cardinals
DESCRIPTION:Drillers @ Cardinals\n\nFollow on MiLB First Pitch: https://stza.co/+wPQQ-3K\n\nShop: https://stza.co/+wPQQ-3I\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Drillers @ Cardinals
<2018-05-08 Tue 18:30-21:30>
:PROPERTIES:
:ID:       oCJUmACwe50y7gXPuI7WUzlt@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Drillers @ Cardinals Drillers @ Cardinals

Follow on MiLB First Pitch  https //stza.co/+wPQR-2S

Shop  https //stza.co/+wPQR-2o

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Drillers @ Cardinals
END:VALARM
DTSTART:20180508T233000Z
DTEND:20180509T023000Z
UID:oCJUmACwe50y7gXPuI7WUzlt@stanza.co
SUMMARY:Drillers @ Cardinals
DESCRIPTION:Drillers @ Cardinals\n\nFollow on MiLB First Pitch: https://stza.co/+wPQR-2S\n\nShop: https://stza.co/+wPQR-2o\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Drillers @ Naturals
<2018-05-10 Thu 19:05-22:05>
:PROPERTIES:
:ID:       0AzVkBx-Rcklsv2xEvsnSc5L@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Drillers @ Naturals Drillers @ Naturals

Follow on MiLB First Pitch  https //stza.co/+wi4o-1T

Shop  https //stza.co/+wi4o-2n

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Drillers @ Naturals
END:VALARM
DTSTART:20180511T000500Z
DTEND:20180511T030500Z
UID:0AzVkBx-Rcklsv2xEvsnSc5L@stanza.co
SUMMARY:Drillers @ Naturals
DESCRIPTION:Drillers @ Naturals\n\nFollow on MiLB First Pitch: https://stza.co/+wi4o-1T\n\nShop: https://stza.co/+wi4o-2n\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Drillers @ Naturals
<2018-05-11 Fri 19:15-22:15>
:PROPERTIES:
:ID:       eyH5vNhEfXZ6dtfFLyRov7o_@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Drillers @ Naturals Drillers @ Naturals

Follow on MiLB First Pitch  https //stza.co/+wi4p-P

Shop  https //stza.co/+wi4p-1n

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Drillers @ Naturals
END:VALARM
DTSTART:20180512T001500Z
DTEND:20180512T031500Z
UID:eyH5vNhEfXZ6dtfFLyRov7o_@stanza.co
SUMMARY:Drillers @ Naturals
DESCRIPTION:Drillers @ Naturals\n\nFollow on MiLB First Pitch: https://stza.co/+wi4p-P\n\nShop: https://stza.co/+wi4p-1n\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Drillers @ Naturals
<2018-05-12 Sat 18:05-21:05>
:PROPERTIES:
:ID:       KuiSoQmYCgzjRgiU6tW-ta55@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Drillers @ Naturals Drillers @ Naturals

Follow on MiLB First Pitch  https //stza.co/+wi4q-3u

Shop  https //stza.co/+wi4q-1K

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Drillers @ Naturals
END:VALARM
DTSTART:20180512T230500Z
DTEND:20180513T020500Z
UID:KuiSoQmYCgzjRgiU6tW-ta55@stanza.co
SUMMARY:Drillers @ Naturals
DESCRIPTION:Drillers @ Naturals\n\nFollow on MiLB First Pitch: https://stza.co/+wi4q-3u\n\nShop: https://stza.co/+wi4q-1K\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Drillers @ Naturals
<2018-05-13 Sun 14:05-17:05>
:PROPERTIES:
:ID:       xqqHcfcojHyLYvTusFQ4or4u@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Drillers @ Naturals Drillers @ Naturals

Follow on MiLB First Pitch  https //stza.co/+wi4r-1c

Shop  https //stza.co/+wi4r-3c

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Drillers @ Naturals
END:VALARM
DTSTART:20180513T190500Z
DTEND:20180513T220500Z
UID:xqqHcfcojHyLYvTusFQ4or4u@stanza.co
SUMMARY:Drillers @ Naturals
DESCRIPTION:Drillers @ Naturals\n\nFollow on MiLB First Pitch: https://stza.co/+wi4r-1c\n\nShop: https://stza.co/+wi4r-3c\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Drillers vs. Cardinals
<2018-05-14 Mon 19:05-22:05>
:PROPERTIES:
:ID:       2wevAiK6f1C5gGJuxz-fXQ0y@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Drillers vs. Cardinals Drillers vs. Cardinals

Follow on MiLB First Pitch  https //stza.co/+w0f6-p

Shop  https //stza.co/+w0f6-3H

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Drillers vs. Cardinals
END:VALARM
DTSTART:20180515T000500Z
DTEND:20180515T030500Z
UID:2wevAiK6f1C5gGJuxz-fXQ0y@stanza.co
SUMMARY:Drillers vs. Cardinals
DESCRIPTION:Drillers vs. Cardinals\n\nFollow on MiLB First Pitch: https://stza.co/+w0f6-p\n\nShop: https://stza.co/+w0f6-3H\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Drillers vs. Cardinals
<2018-05-15 Tue 19:05-22:05>
:PROPERTIES:
:ID:       _3dGnVjRoe8qdFCQ6-dWv4k8@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Drillers vs. Cardinals Drillers vs. Cardinals

Follow on MiLB First Pitch  https //stza.co/+w0f8-w

Shop  https //stza.co/+w0f8-3B

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Drillers vs. Cardinals
END:VALARM
DTSTART:20180516T000500Z
DTEND:20180516T030500Z
UID:_3dGnVjRoe8qdFCQ6-dWv4k8@stanza.co
SUMMARY:Drillers vs. Cardinals
DESCRIPTION:Drillers vs. Cardinals\n\nFollow on MiLB First Pitch: https://stza.co/+w0f8-w\n\nShop: https://stza.co/+w0f8-3B\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Drillers vs. Cardinals
<2018-05-16 Wed 11:05-14:05>
:PROPERTIES:
:ID:       8N77qRTtht261YnQ1jg6VhcK@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Drillers vs. Cardinals Drillers vs. Cardinals

Follow on MiLB First Pitch  https //stza.co/+w0fb-2t

Shop  https //stza.co/+w0fb-3L

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Drillers vs. Cardinals
END:VALARM
DTSTART:20180516T160500Z
DTEND:20180516T190500Z
UID:8N77qRTtht261YnQ1jg6VhcK@stanza.co
SUMMARY:Drillers vs. Cardinals
DESCRIPTION:Drillers vs. Cardinals\n\nFollow on MiLB First Pitch: https://stza.co/+w0fb-2t\n\nShop: https://stza.co/+w0fb-3L\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Drillers vs. Cardinals
<2018-05-17 Thu 19:05-22:05>
:PROPERTIES:
:ID:       XDo4PzjXowhgsoqAChcS2O8Q@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Drillers vs. Cardinals Drillers vs. Cardinals

Follow on MiLB First Pitch  https //stza.co/+w0fc-1b

Shop  https //stza.co/+w0fc-39

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Drillers vs. Cardinals
END:VALARM
DTSTART:20180518T000500Z
DTEND:20180518T030500Z
UID:XDo4PzjXowhgsoqAChcS2O8Q@stanza.co
SUMMARY:Drillers vs. Cardinals
DESCRIPTION:Drillers vs. Cardinals\n\nFollow on MiLB First Pitch: https://stza.co/+w0fc-1b\n\nShop: https://stza.co/+w0fc-39\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Drillers vs. Travelers
<2018-05-18 Fri 19:05-22:05>
:PROPERTIES:
:ID:       xg79SBWD_eM_crSLej-pKF4K@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Drillers vs. Travelers Drillers vs. Travelers

Follow on MiLB First Pitch  https //stza.co/+w0fe-3m

Shop  https //stza.co/+w0fe-1K

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Drillers vs. Travelers
END:VALARM
DTSTART:20180519T000500Z
DTEND:20180519T030500Z
UID:xg79SBWD_eM_crSLej-pKF4K@stanza.co
SUMMARY:Drillers vs. Travelers
DESCRIPTION:Drillers vs. Travelers\n\nFollow on MiLB First Pitch: https://stza.co/+w0fe-3m\n\nShop: https://stza.co/+w0fe-1K\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Drillers vs. Travelers
<2018-05-19 Sat 19:05-22:05>
:PROPERTIES:
:ID:       _twZ3AFhgmsVLiONKjuSYZA1@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Drillers vs. Travelers Drillers vs. Travelers

Follow on MiLB First Pitch  https //stza.co/+w0fh-2_

Shop  https //stza.co/+w0fh-2u

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Drillers vs. Travelers
END:VALARM
DTSTART:20180520T000500Z
DTEND:20180520T030500Z
UID:_twZ3AFhgmsVLiONKjuSYZA1@stanza.co
SUMMARY:Drillers vs. Travelers
DESCRIPTION:Drillers vs. Travelers\n\nFollow on MiLB First Pitch: https://stza.co/+w0fh-2_\n\nShop: https://stza.co/+w0fh-2u\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Drillers vs. Travelers
<2018-05-20 Sun 13:05-16:05>
:PROPERTIES:
:ID:       UjxjRbNZyWLz_Mga-FPkUD9A@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Drillers vs. Travelers Drillers vs. Travelers

Follow on MiLB First Pitch  https //stza.co/+w0fj-1z

Shop  https //stza.co/+w0fj-1E

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Drillers vs. Travelers
END:VALARM
DTSTART:20180520T180500Z
DTEND:20180520T210500Z
UID:UjxjRbNZyWLz_Mga-FPkUD9A@stanza.co
SUMMARY:Drillers vs. Travelers
DESCRIPTION:Drillers vs. Travelers\n\nFollow on MiLB First Pitch: https://stza.co/+w0fj-1z\n\nShop: https://stza.co/+w0fj-1E\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Drillers vs. Travelers
<2018-05-21 Mon 12:05-15:05>
:PROPERTIES:
:ID:       8qogmX0e4qrb4L9L3TfTNLzV@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Drillers vs. Travelers Drillers vs. Travelers

Follow on MiLB First Pitch  https //stza.co/+w0fk-1s

Shop  https //stza.co/+w0fk-1J

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Drillers vs. Travelers
END:VALARM
DTSTART:20180521T170500Z
DTEND:20180521T200500Z
UID:8qogmX0e4qrb4L9L3TfTNLzV@stanza.co
SUMMARY:Drillers vs. Travelers
DESCRIPTION:Drillers vs. Travelers\n\nFollow on MiLB First Pitch: https://stza.co/+w0fk-1s\n\nShop: https://stza.co/+w0fk-1J\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Drillers @ Missions
<2018-05-22 Tue 19:05-22:05>
:PROPERTIES:
:ID:       9dXJgKRI3nxjNjek1eftVvy9@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Drillers @ Missions Drillers @ Missions

Follow on MiLB First Pitch  https //stza.co/+wMA8-1n

Shop  https //stza.co/+wMA8-v

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Drillers @ Missions
END:VALARM
DTSTART:20180523T000500Z
DTEND:20180523T030500Z
UID:9dXJgKRI3nxjNjek1eftVvy9@stanza.co
SUMMARY:Drillers @ Missions
DESCRIPTION:Drillers @ Missions\n\nFollow on MiLB First Pitch: https://stza.co/+wMA8-1n\n\nShop: https://stza.co/+wMA8-v\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Drillers @ Missions
<2018-05-23 Wed 19:05-22:05>
:PROPERTIES:
:ID:       PH5hG2-nSpFFz441jtZB1e0r@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Drillers @ Missions Drillers @ Missions

Follow on MiLB First Pitch  https //stza.co/+wMA9-1J

Shop  https //stza.co/+wMA9-35

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Drillers @ Missions
END:VALARM
DTSTART:20180524T000500Z
DTEND:20180524T030500Z
UID:PH5hG2-nSpFFz441jtZB1e0r@stanza.co
SUMMARY:Drillers @ Missions
DESCRIPTION:Drillers @ Missions\n\nFollow on MiLB First Pitch: https://stza.co/+wMA9-1J\n\nShop: https://stza.co/+wMA9-35\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Drillers @ Missions
<2018-05-24 Thu 19:05-22:05>
:PROPERTIES:
:ID:       cQiCjfo6wnjW310DXB15M9nK@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Drillers @ Missions Drillers @ Missions

Follow on MiLB First Pitch  https //stza.co/+wMAb-n

Shop  https //stza.co/+wMAb-1G

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Drillers @ Missions
END:VALARM
DTSTART:20180525T000500Z
DTEND:20180525T030500Z
UID:cQiCjfo6wnjW310DXB15M9nK@stanza.co
SUMMARY:Drillers @ Missions
DESCRIPTION:Drillers @ Missions\n\nFollow on MiLB First Pitch: https://stza.co/+wMAb-n\n\nShop: https://stza.co/+wMAb-1G\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Drillers @ Hooks
<2018-05-25 Fri 19:05-22:05>
:PROPERTIES:
:ID:       tacBrqJ9MniWzRpefdVs4Gcu@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Drillers @ Hooks Drillers @ Hooks

Follow on MiLB First Pitch  https //stza.co/+xAIS-1M

Shop  https //stza.co/+xAIS-3r

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Drillers @ Hooks
END:VALARM
DTSTART:20180526T000500Z
DTEND:20180526T030500Z
UID:tacBrqJ9MniWzRpefdVs4Gcu@stanza.co
SUMMARY:Drillers @ Hooks
DESCRIPTION:Drillers @ Hooks\n\nFollow on MiLB First Pitch: https://stza.co/+xAIS-1M\n\nShop: https://stza.co/+xAIS-3r\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Drillers @ Hooks
<2018-05-26 Sat 19:05-22:05>
:PROPERTIES:
:ID:       SWhrEwG01Pv5adokGsWErWQc@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Drillers @ Hooks Drillers @ Hooks

Follow on MiLB First Pitch  https //stza.co/+xAIT-20

Shop  https //stza.co/+xAIT-1D

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Drillers @ Hooks
END:VALARM
DTSTART:20180527T000500Z
DTEND:20180527T030500Z
UID:SWhrEwG01Pv5adokGsWErWQc@stanza.co
SUMMARY:Drillers @ Hooks
DESCRIPTION:Drillers @ Hooks\n\nFollow on MiLB First Pitch: https://stza.co/+xAIT-20\n\nShop: https://stza.co/+xAIT-1D\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Drillers @ Hooks
<2018-05-27 Sun 18:05-21:05>
:PROPERTIES:
:ID:       BNBdbS6n3ZYET3j1EFb2bR11@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Drillers @ Hooks Drillers @ Hooks

Follow on MiLB First Pitch  https //stza.co/+xAIW-1T

Shop  https //stza.co/+xAIW-3P

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Drillers @ Hooks
END:VALARM
DTSTART:20180527T230500Z
DTEND:20180528T020500Z
UID:BNBdbS6n3ZYET3j1EFb2bR11@stanza.co
SUMMARY:Drillers @ Hooks
DESCRIPTION:Drillers @ Hooks\n\nFollow on MiLB First Pitch: https://stza.co/+xAIW-1T\n\nShop: https://stza.co/+xAIW-3P\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Drillers vs. Missions
<2018-05-29 Tue 19:05-22:05>
:PROPERTIES:
:ID:       qqlBhJy3KvC_fBKs-ZqzZ_CA@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Drillers vs. Missions Drillers vs. Missions

Follow on MiLB First Pitch  https //stza.co/+w0fn-1z

Shop  https //stza.co/+w0fn-34

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Drillers vs. Missions
END:VALARM
DTSTART:20180530T000500Z
DTEND:20180530T030500Z
UID:qqlBhJy3KvC_fBKs-ZqzZ_CA@stanza.co
SUMMARY:Drillers vs. Missions
DESCRIPTION:Drillers vs. Missions\n\nFollow on MiLB First Pitch: https://stza.co/+w0fn-1z\n\nShop: https://stza.co/+w0fn-34\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Drillers vs. Missions
<2018-05-30 Wed 19:05-22:05>
:PROPERTIES:
:ID:       iPi7bAG9ULeQ3BIMttalRRLH@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Drillers vs. Missions Drillers vs. Missions

Follow on MiLB First Pitch  https //stza.co/+w0fp-T

Shop  https //stza.co/+w0fp-2J

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Drillers vs. Missions
END:VALARM
DTSTART:20180531T000500Z
DTEND:20180531T030500Z
UID:iPi7bAG9ULeQ3BIMttalRRLH@stanza.co
SUMMARY:Drillers vs. Missions
DESCRIPTION:Drillers vs. Missions\n\nFollow on MiLB First Pitch: https://stza.co/+w0fp-T\n\nShop: https://stza.co/+w0fp-2J\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Drillers vs. Missions
<2018-05-31 Thu 19:05-22:05>
:PROPERTIES:
:ID:       7r8lp6v3zfnZF3oaK5mCMvXS@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Drillers vs. Missions Drillers vs. Missions

Follow on MiLB First Pitch  https //stza.co/+w0fq-1S

Shop  https //stza.co/+w0fq-f

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Drillers vs. Missions
END:VALARM
DTSTART:20180601T000500Z
DTEND:20180601T030500Z
UID:7r8lp6v3zfnZF3oaK5mCMvXS@stanza.co
SUMMARY:Drillers vs. Missions
DESCRIPTION:Drillers vs. Missions\n\nFollow on MiLB First Pitch: https://stza.co/+w0fq-1S\n\nShop: https://stza.co/+w0fq-f\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Drillers vs. Hooks
<2018-06-01 Fri 19:05-22:05>
:PROPERTIES:
:ID:       WW8o9wEx7Nk6ZgJ8ZtRXUmqp@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Drillers vs. Hooks Drillers vs. Hooks

Follow on MiLB First Pitch  https //stza.co/+w0fs-T

Shop  https //stza.co/+w0fs-q

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Drillers vs. Hooks
END:VALARM
DTSTART:20180602T000500Z
DTEND:20180602T030500Z
UID:WW8o9wEx7Nk6ZgJ8ZtRXUmqp@stanza.co
SUMMARY:Drillers vs. Hooks
DESCRIPTION:Drillers vs. Hooks\n\nFollow on MiLB First Pitch: https://stza.co/+w0fs-T\n\nShop: https://stza.co/+w0fs-q\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Drillers vs. Hooks
<2018-06-02 Sat 19:05-22:05>
:PROPERTIES:
:ID:       dD8OQlL71SkALfeVCl77IqGs@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Drillers vs. Hooks Drillers vs. Hooks

Follow on MiLB First Pitch  https //stza.co/+w0fv-20

Shop  https //stza.co/+w0fv-2m

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Drillers vs. Hooks
END:VALARM
DTSTART:20180603T000500Z
DTEND:20180603T030500Z
UID:dD8OQlL71SkALfeVCl77IqGs@stanza.co
SUMMARY:Drillers vs. Hooks
DESCRIPTION:Drillers vs. Hooks\n\nFollow on MiLB First Pitch: https://stza.co/+w0fv-20\n\nShop: https://stza.co/+w0fv-2m\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Drillers vs. Hooks
<2018-06-03 Sun 13:05-16:05>
:PROPERTIES:
:ID:       uZzHnxeD-K33iw7l5vGamND-@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Drillers vs. Hooks Drillers vs. Hooks

Follow on MiLB First Pitch  https //stza.co/+w0fx-24

Shop  https //stza.co/+w0fx-3

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Drillers vs. Hooks
END:VALARM
DTSTART:20180603T180500Z
DTEND:20180603T210500Z
UID:uZzHnxeD-K33iw7l5vGamND-@stanza.co
SUMMARY:Drillers vs. Hooks
DESCRIPTION:Drillers vs. Hooks\n\nFollow on MiLB First Pitch: https://stza.co/+w0fx-24\n\nShop: https://stza.co/+w0fx-3\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Drillers @ Travelers
<2018-06-05 Tue 19:10-22:10>
:PROPERTIES:
:ID:       8hzSMv7BLa4DPCXHK0p8uCB0@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Drillers @ Travelers Drillers @ Travelers

Follow on MiLB First Pitch  https //stza.co/+w0dE-2Z

Shop  https //stza.co/+w0dE-c

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Drillers @ Travelers
END:VALARM
DTSTART:20180606T001000Z
DTEND:20180606T031000Z
UID:8hzSMv7BLa4DPCXHK0p8uCB0@stanza.co
SUMMARY:Drillers @ Travelers
DESCRIPTION:Drillers @ Travelers\n\nFollow on MiLB First Pitch: https://stza.co/+w0dE-2Z\n\nShop: https://stza.co/+w0dE-c\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Drillers @ Travelers
<2018-06-06 Wed 19:10-22:10>
:PROPERTIES:
:ID:       vip_B9s5Mf9wH0AFCeMpoZJK@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Drillers @ Travelers Drillers @ Travelers

Follow on MiLB First Pitch  https //stza.co/+w0dF-2E

Shop  https //stza.co/+w0dF-l

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Drillers @ Travelers
END:VALARM
DTSTART:20180607T001000Z
DTEND:20180607T031000Z
UID:vip_B9s5Mf9wH0AFCeMpoZJK@stanza.co
SUMMARY:Drillers @ Travelers
DESCRIPTION:Drillers @ Travelers\n\nFollow on MiLB First Pitch: https://stza.co/+w0dF-2E\n\nShop: https://stza.co/+w0dF-l\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Drillers @ Travelers
<2018-06-07 Thu 19:10-22:10>
:PROPERTIES:
:ID:       FF2Ud3tXbZysaFAt1_7jAAvs@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Drillers @ Travelers Drillers @ Travelers

Follow on MiLB First Pitch  https //stza.co/+w0dG-s

Shop  https //stza.co/+w0dG-2v

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Drillers @ Travelers
END:VALARM
DTSTART:20180608T001000Z
DTEND:20180608T031000Z
UID:FF2Ud3tXbZysaFAt1_7jAAvs@stanza.co
SUMMARY:Drillers @ Travelers
DESCRIPTION:Drillers @ Travelers\n\nFollow on MiLB First Pitch: https://stza.co/+w0dG-s\n\nShop: https://stza.co/+w0dG-2v\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Drillers @ Travelers
<2018-06-08 Fri 19:10-22:10>
:PROPERTIES:
:ID:       Vbo66_xiCakyMUNaVuiuuUop@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Drillers @ Travelers Drillers @ Travelers

Follow on MiLB First Pitch  https //stza.co/+w0dH-3T

Shop  https //stza.co/+w0dH-30

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Drillers @ Travelers
END:VALARM
DTSTART:20180609T001000Z
DTEND:20180609T031000Z
UID:Vbo66_xiCakyMUNaVuiuuUop@stanza.co
SUMMARY:Drillers @ Travelers
DESCRIPTION:Drillers @ Travelers\n\nFollow on MiLB First Pitch: https://stza.co/+w0dH-3T\n\nShop: https://stza.co/+w0dH-30\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Drillers @ Cardinals
<2018-06-09 Sat 18:10-21:10>
:PROPERTIES:
:ID:       8IJhkYN6oZZc9qvA6wfpjzAA@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Drillers @ Cardinals Drillers @ Cardinals

Follow on MiLB First Pitch  https //stza.co/+wPQS-27

Shop  https //stza.co/+wPQS-3V

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Drillers @ Cardinals
END:VALARM
DTSTART:20180609T231000Z
DTEND:20180610T021000Z
UID:8IJhkYN6oZZc9qvA6wfpjzAA@stanza.co
SUMMARY:Drillers @ Cardinals
DESCRIPTION:Drillers @ Cardinals\n\nFollow on MiLB First Pitch: https://stza.co/+wPQS-27\n\nShop: https://stza.co/+wPQS-3V\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Drillers @ Cardinals
<2018-06-10 Sun 18:10-21:10>
:PROPERTIES:
:ID:       HJcZbh74UJBBLTMGR-oEaOq-@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Drillers @ Cardinals Drillers @ Cardinals

Follow on MiLB First Pitch  https //stza.co/+wPQT-2u

Shop  https //stza.co/+wPQT-E

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Drillers @ Cardinals
END:VALARM
DTSTART:20180610T231000Z
DTEND:20180611T021000Z
UID:HJcZbh74UJBBLTMGR-oEaOq-@stanza.co
SUMMARY:Drillers @ Cardinals
DESCRIPTION:Drillers @ Cardinals\n\nFollow on MiLB First Pitch: https://stza.co/+wPQT-2u\n\nShop: https://stza.co/+wPQT-E\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Drillers @ Cardinals
<2018-06-11 Mon 11:10-14:10>
:PROPERTIES:
:ID:       mGAlHIfuNzn2oJwcEFJ88F42@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Drillers @ Cardinals Drillers @ Cardinals

Follow on MiLB First Pitch  https //stza.co/+wPQU-3K

Shop  https //stza.co/+wPQU-2A

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Drillers @ Cardinals
END:VALARM
DTSTART:20180611T161000Z
DTEND:20180611T191000Z
UID:mGAlHIfuNzn2oJwcEFJ88F42@stanza.co
SUMMARY:Drillers @ Cardinals
DESCRIPTION:Drillers @ Cardinals\n\nFollow on MiLB First Pitch: https://stza.co/+wPQU-3K\n\nShop: https://stza.co/+wPQU-2A\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Drillers @ Cardinals
<2018-06-12 Tue 18:30-21:30>
:PROPERTIES:
:ID:       3WDobpZVpzTWcuoo1DYnOKJp@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Drillers @ Cardinals Drillers @ Cardinals

Follow on MiLB First Pitch  https //stza.co/+wPQV-1J

Shop  https //stza.co/+wPQV-t

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Drillers @ Cardinals
END:VALARM
DTSTART:20180612T233000Z
DTEND:20180613T023000Z
UID:3WDobpZVpzTWcuoo1DYnOKJp@stanza.co
SUMMARY:Drillers @ Cardinals
DESCRIPTION:Drillers @ Cardinals\n\nFollow on MiLB First Pitch: https://stza.co/+wPQV-1J\n\nShop: https://stza.co/+wPQV-t\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Drillers vs. Naturals
<2018-06-13 Wed 19:05-22:05>
:PROPERTIES:
:ID:       7SpgixvZiPdg4iaSytCg2y6y@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Drillers vs. Naturals Drillers vs. Naturals

Follow on MiLB First Pitch  https //stza.co/+w0fz-k

Shop  https //stza.co/+w0fz-2Z

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Drillers vs. Naturals
END:VALARM
DTSTART:20180614T000500Z
DTEND:20180614T030500Z
UID:7SpgixvZiPdg4iaSytCg2y6y@stanza.co
SUMMARY:Drillers vs. Naturals
DESCRIPTION:Drillers vs. Naturals\n\nFollow on MiLB First Pitch: https://stza.co/+w0fz-k\n\nShop: https://stza.co/+w0fz-2Z\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Drillers vs. Naturals
<2018-06-14 Thu 19:05-22:05>
:PROPERTIES:
:ID:       aRXLKbK1agKJG58Hwnc-jBC7@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Drillers vs. Naturals Drillers vs. Naturals

Follow on MiLB First Pitch  https //stza.co/+w0fB-1w

Shop  https //stza.co/+w0fB-a

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Drillers vs. Naturals
END:VALARM
DTSTART:20180615T000500Z
DTEND:20180615T030500Z
UID:aRXLKbK1agKJG58Hwnc-jBC7@stanza.co
SUMMARY:Drillers vs. Naturals
DESCRIPTION:Drillers vs. Naturals\n\nFollow on MiLB First Pitch: https://stza.co/+w0fB-1w\n\nShop: https://stza.co/+w0fB-a\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Drillers vs. Naturals
<2018-06-15 Fri 19:05-22:05>
:PROPERTIES:
:ID:       9jSx1bTepZ-ZA9RzP5Z82-wA@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Drillers vs. Naturals Drillers vs. Naturals

Follow on MiLB First Pitch  https //stza.co/+w0fC-12

Shop  https //stza.co/+w0fC-D

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Drillers vs. Naturals
END:VALARM
DTSTART:20180616T000500Z
DTEND:20180616T030500Z
UID:9jSx1bTepZ-ZA9RzP5Z82-wA@stanza.co
SUMMARY:Drillers vs. Naturals
DESCRIPTION:Drillers vs. Naturals\n\nFollow on MiLB First Pitch: https://stza.co/+w0fC-12\n\nShop: https://stza.co/+w0fC-D\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Drillers vs. Naturals
<2018-06-16 Sat 19:05-22:05>
:PROPERTIES:
:ID:       1_UFNckspV4tzj9qIQKyxhVS@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Drillers vs. Naturals Drillers vs. Naturals

Follow on MiLB First Pitch  https //stza.co/+w0fF-1p

Shop  https //stza.co/+w0fF-3h

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Drillers vs. Naturals
END:VALARM
DTSTART:20180617T000500Z
DTEND:20180617T030500Z
UID:1_UFNckspV4tzj9qIQKyxhVS@stanza.co
SUMMARY:Drillers vs. Naturals
DESCRIPTION:Drillers vs. Naturals\n\nFollow on MiLB First Pitch: https://stza.co/+w0fF-1p\n\nShop: https://stza.co/+w0fF-3h\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Drillers vs. Cardinals
<2018-06-17 Sun 13:05-16:05>
:PROPERTIES:
:ID:       OIb6IKDUPTUlMQa8xPDl3POi@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Drillers vs. Cardinals Drillers vs. Cardinals

Follow on MiLB First Pitch  https //stza.co/+w0fH-16

Shop  https //stza.co/+w0fH-z

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Drillers vs. Cardinals
END:VALARM
DTSTART:20180617T180500Z
DTEND:20180617T210500Z
UID:OIb6IKDUPTUlMQa8xPDl3POi@stanza.co
SUMMARY:Drillers vs. Cardinals
DESCRIPTION:Drillers vs. Cardinals\n\nFollow on MiLB First Pitch: https://stza.co/+w0fH-16\n\nShop: https://stza.co/+w0fH-z\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Drillers vs. Cardinals
<2018-06-18 Mon 19:05-22:05>
:PROPERTIES:
:ID:       0rkLjYknTlsjg5_V1vvdN21z@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Drillers vs. Cardinals Drillers vs. Cardinals

Follow on MiLB First Pitch  https //stza.co/+w0fJ-2r

Shop  https //stza.co/+w0fJ-2s

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Drillers vs. Cardinals
END:VALARM
DTSTART:20180619T000500Z
DTEND:20180619T030500Z
UID:0rkLjYknTlsjg5_V1vvdN21z@stanza.co
SUMMARY:Drillers vs. Cardinals
DESCRIPTION:Drillers vs. Cardinals\n\nFollow on MiLB First Pitch: https://stza.co/+w0fJ-2r\n\nShop: https://stza.co/+w0fJ-2s\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Drillers vs. Cardinals
<2018-06-19 Tue 19:05-22:05>
:PROPERTIES:
:ID:       8yrnRsIcl7wT0oa_G6BhIUWt@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Drillers vs. Cardinals Drillers vs. Cardinals

Follow on MiLB First Pitch  https //stza.co/+w0fL-3W

Shop  https //stza.co/+w0fL-1p

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Drillers vs. Cardinals
END:VALARM
DTSTART:20180620T000500Z
DTEND:20180620T030500Z
UID:8yrnRsIcl7wT0oa_G6BhIUWt@stanza.co
SUMMARY:Drillers vs. Cardinals
DESCRIPTION:Drillers vs. Cardinals\n\nFollow on MiLB First Pitch: https://stza.co/+w0fL-3W\n\nShop: https://stza.co/+w0fL-1p\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Drillers vs. Cardinals
<2018-06-20 Wed 11:05-14:05>
:PROPERTIES:
:ID:       mJyw9SjDP1lqXhWEm95ukWqs@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Drillers vs. Cardinals Drillers vs. Cardinals

Follow on MiLB First Pitch  https //stza.co/+w0fM-t

Shop  https //stza.co/+w0fM-3P

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Drillers vs. Cardinals
END:VALARM
DTSTART:20180620T160500Z
DTEND:20180620T190500Z
UID:mJyw9SjDP1lqXhWEm95ukWqs@stanza.co
SUMMARY:Drillers vs. Cardinals
DESCRIPTION:Drillers vs. Cardinals\n\nFollow on MiLB First Pitch: https://stza.co/+w0fM-t\n\nShop: https://stza.co/+w0fM-3P\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Drillers vs. Naturals
<2018-06-21 Thu 19:05-22:05>
:PROPERTIES:
:ID:       bM81I7dzzc06tFMKQf8AHSFU@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Drillers vs. Naturals Drillers vs. Naturals

Follow on MiLB First Pitch  https //stza.co/+w0fP-25

Shop  https //stza.co/+w0fP-2X

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Drillers vs. Naturals
END:VALARM
DTSTART:20180622T000500Z
DTEND:20180622T030500Z
UID:bM81I7dzzc06tFMKQf8AHSFU@stanza.co
SUMMARY:Drillers vs. Naturals
DESCRIPTION:Drillers vs. Naturals\n\nFollow on MiLB First Pitch: https://stza.co/+w0fP-25\n\nShop: https://stza.co/+w0fP-2X\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Drillers vs. Naturals
<2018-06-22 Fri 19:05-22:05>
:PROPERTIES:
:ID:       ubVcGyVwAl-XS0wkNTvRcnqc@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Drillers vs. Naturals Drillers vs. Naturals

Follow on MiLB First Pitch  https //stza.co/+w0fR-1$

Shop  https //stza.co/+w0fR-2K

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Drillers vs. Naturals
END:VALARM
DTSTART:20180623T000500Z
DTEND:20180623T030500Z
UID:ubVcGyVwAl-XS0wkNTvRcnqc@stanza.co
SUMMARY:Drillers vs. Naturals
DESCRIPTION:Drillers vs. Naturals\n\nFollow on MiLB First Pitch: https://stza.co/+w0fR-1$\n\nShop: https://stza.co/+w0fR-2K\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Drillers vs. Naturals
<2018-06-23 Sat 19:05-22:05>
:PROPERTIES:
:ID:       DK8yjNpbyvJ4IidFZNX9SQFf@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Drillers vs. Naturals Drillers vs. Naturals

Follow on MiLB First Pitch  https //stza.co/+w0fT-e

Shop  https //stza.co/+w0fT-1V

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Drillers vs. Naturals
END:VALARM
DTSTART:20180624T000500Z
DTEND:20180624T030500Z
UID:DK8yjNpbyvJ4IidFZNX9SQFf@stanza.co
SUMMARY:Drillers vs. Naturals
DESCRIPTION:Drillers vs. Naturals\n\nFollow on MiLB First Pitch: https://stza.co/+w0fT-e\n\nShop: https://stza.co/+w0fT-1V\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Drillers vs. Naturals
<2018-06-24 Sun 13:05-16:05>
:PROPERTIES:
:ID:       npaEYtxCoEh8XI8IMmBrrtVO@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Drillers vs. Naturals Drillers vs. Naturals

Follow on MiLB First Pitch  https //stza.co/+w0fU-V

Shop  https //stza.co/+w0fU-3T

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Drillers vs. Naturals
END:VALARM
DTSTART:20180624T180500Z
DTEND:20180624T210500Z
UID:npaEYtxCoEh8XI8IMmBrrtVO@stanza.co
SUMMARY:Drillers vs. Naturals
DESCRIPTION:Drillers vs. Naturals\n\nFollow on MiLB First Pitch: https://stza.co/+w0fU-V\n\nShop: https://stza.co/+w0fU-3T\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Drillers @ RockHounds
<2018-06-28 Thu 19:00-22:00>
:PROPERTIES:
:ID:       PVeqhc2lKlinhvk3xKSyh3Hs@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Drillers @ RockHounds Drillers @ RockHounds

Follow on MiLB First Pitch  https //stza.co/+wX60-d

Shop  https //stza.co/+wX60-E

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Drillers @ RockHounds
END:VALARM
DTSTART:20180629T000000Z
DTEND:20180629T030000Z
UID:PVeqhc2lKlinhvk3xKSyh3Hs@stanza.co
SUMMARY:Drillers @ RockHounds
DESCRIPTION:Drillers @ RockHounds\n\nFollow on MiLB First Pitch: https://stza.co/+wX60-d\n\nShop: https://stza.co/+wX60-E\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Drillers @ RockHounds
<2018-06-29 Fri 19:00-22:00>
:PROPERTIES:
:ID:       A1J2h8NS0PubS_WK-G8NFB8M@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Drillers @ RockHounds Drillers @ RockHounds

Follow on MiLB First Pitch  https //stza.co/+wX61-3r

Shop  https //stza.co/+wX61-3u

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Drillers @ RockHounds
END:VALARM
DTSTART:20180630T000000Z
DTEND:20180630T030000Z
UID:A1J2h8NS0PubS_WK-G8NFB8M@stanza.co
SUMMARY:Drillers @ RockHounds
DESCRIPTION:Drillers @ RockHounds\n\nFollow on MiLB First Pitch: https://stza.co/+wX61-3r\n\nShop: https://stza.co/+wX61-3u\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Drillers @ RockHounds
<2018-06-30 Sat 19:00-22:00>
:PROPERTIES:
:ID:       71KVV-VeaWA1BHSMYu9ktHKI@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Drillers @ RockHounds Drillers @ RockHounds

Follow on MiLB First Pitch  https //stza.co/+wX63-3m

Shop  https //stza.co/+wX63-1N

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Drillers @ RockHounds
END:VALARM
DTSTART:20180701T000000Z
DTEND:20180701T030000Z
UID:71KVV-VeaWA1BHSMYu9ktHKI@stanza.co
SUMMARY:Drillers @ RockHounds
DESCRIPTION:Drillers @ RockHounds\n\nFollow on MiLB First Pitch: https://stza.co/+wX63-3m\n\nShop: https://stza.co/+wX63-1N\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Drillers @ RoughRiders
<2018-07-01 Sun 19:05-22:05>
:PROPERTIES:
:ID:       TnLm_mq8--WcMYgcee8PvqNG@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Drillers @ RoughRiders Drillers @ RoughRiders

Follow on MiLB First Pitch  https //stza.co/+wYd5-1M

Shop  https //stza.co/+wYd5-20

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Drillers @ RoughRiders
END:VALARM
DTSTART:20180702T000500Z
DTEND:20180702T030500Z
UID:TnLm_mq8--WcMYgcee8PvqNG@stanza.co
SUMMARY:Drillers @ RoughRiders
DESCRIPTION:Drillers @ RoughRiders\n\nFollow on MiLB First Pitch: https://stza.co/+wYd5-1M\n\nShop: https://stza.co/+wYd5-20\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Drillers @ RoughRiders
<2018-07-02 Mon 19:05-22:05>
:PROPERTIES:
:ID:       _ct7QKGsAnLHXBRcFIVgWLIh@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Drillers @ RoughRiders Drillers @ RoughRiders

Follow on MiLB First Pitch  https //stza.co/+wYd6-2i

Shop  https //stza.co/+wYd6-$

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Drillers @ RoughRiders
END:VALARM
DTSTART:20180703T000500Z
DTEND:20180703T030500Z
UID:_ct7QKGsAnLHXBRcFIVgWLIh@stanza.co
SUMMARY:Drillers @ RoughRiders
DESCRIPTION:Drillers @ RoughRiders\n\nFollow on MiLB First Pitch: https://stza.co/+wYd6-2i\n\nShop: https://stza.co/+wYd6-$\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Drillers @ RoughRiders
<2018-07-03 Tue 19:05-22:05>
:PROPERTIES:
:ID:       nuYOt8_lgaQNZxnTsA16LPQS@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Drillers @ RoughRiders Drillers @ RoughRiders

Follow on MiLB First Pitch  https //stza.co/+wYd7-i

Shop  https //stza.co/+wYd7-1J

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Drillers @ RoughRiders
END:VALARM
DTSTART:20180704T000500Z
DTEND:20180704T030500Z
UID:nuYOt8_lgaQNZxnTsA16LPQS@stanza.co
SUMMARY:Drillers @ RoughRiders
DESCRIPTION:Drillers @ RoughRiders\n\nFollow on MiLB First Pitch: https://stza.co/+wYd7-i\n\nShop: https://stza.co/+wYd7-1J\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Drillers vs. RockHounds
<2018-07-04 Wed 19:05-22:05>
:PROPERTIES:
:ID:       xTQBaKrzvx4DR8bUFdkyn-01@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Drillers vs. RockHounds Drillers vs. RockHounds

Follow on MiLB First Pitch  https //stza.co/+w0fW-3t

Shop  https //stza.co/+w0fW-12

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Drillers vs. RockHounds
END:VALARM
DTSTART:20180705T000500Z
DTEND:20180705T030500Z
UID:xTQBaKrzvx4DR8bUFdkyn-01@stanza.co
SUMMARY:Drillers vs. RockHounds
DESCRIPTION:Drillers vs. RockHounds\n\nFollow on MiLB First Pitch: https://stza.co/+w0fW-3t\n\nShop: https://stza.co/+w0fW-12\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Drillers vs. RockHounds
<2018-07-05 Thu 19:05-22:05>
:PROPERTIES:
:ID:       pxOXf_M1bXZtgkOY6v5fB-_9@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Drillers vs. RockHounds Drillers vs. RockHounds

Follow on MiLB First Pitch  https //stza.co/+w0fZ-3a

Shop  https //stza.co/+w0fZ-3T

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Drillers vs. RockHounds
END:VALARM
DTSTART:20180706T000500Z
DTEND:20180706T030500Z
UID:pxOXf_M1bXZtgkOY6v5fB-_9@stanza.co
SUMMARY:Drillers vs. RockHounds
DESCRIPTION:Drillers vs. RockHounds\n\nFollow on MiLB First Pitch: https://stza.co/+w0fZ-3a\n\nShop: https://stza.co/+w0fZ-3T\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Drillers vs. RockHounds
<2018-07-06 Fri 19:05-22:05>
:PROPERTIES:
:ID:       Wf1EnqmCGrvrB8FFt2V1-dyw@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Drillers vs. RockHounds Drillers vs. RockHounds

Follow on MiLB First Pitch  https //stza.co/+w0f_-n

Shop  https //stza.co/+w0f_-13

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Drillers vs. RockHounds
END:VALARM
DTSTART:20180707T000500Z
DTEND:20180707T030500Z
UID:Wf1EnqmCGrvrB8FFt2V1-dyw@stanza.co
SUMMARY:Drillers vs. RockHounds
DESCRIPTION:Drillers vs. RockHounds\n\nFollow on MiLB First Pitch: https://stza.co/+w0f_-n\n\nShop: https://stza.co/+w0f_-13\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Drillers vs. RoughRiders
<2018-07-07 Sat 19:05-22:05>
:PROPERTIES:
:ID:       MRWL-hXHzqFBE92Lqi6DVN2j@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Drillers vs. RoughRiders Drillers vs. RoughRiders

Follow on MiLB First Pitch  https //stza.co/+w0g0-3V

Shop  https //stza.co/+w0g0-3w

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Drillers vs. RoughRiders
END:VALARM
DTSTART:20180708T000500Z
DTEND:20180708T030500Z
UID:MRWL-hXHzqFBE92Lqi6DVN2j@stanza.co
SUMMARY:Drillers vs. RoughRiders
DESCRIPTION:Drillers vs. RoughRiders\n\nFollow on MiLB First Pitch: https://stza.co/+w0g0-3V\n\nShop: https://stza.co/+w0g0-3w\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Drillers vs. RoughRiders
<2018-07-08 Sun 19:05-22:05>
:PROPERTIES:
:ID:       aZ0SuqM-1Kw7Kd-vdXIUtJZV@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Drillers vs. RoughRiders Drillers vs. RoughRiders

Follow on MiLB First Pitch  https //stza.co/+w0g2-2O

Shop  https //stza.co/+w0g2-3Q

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Drillers vs. RoughRiders
END:VALARM
DTSTART:20180709T000500Z
DTEND:20180709T030500Z
UID:aZ0SuqM-1Kw7Kd-vdXIUtJZV@stanza.co
SUMMARY:Drillers vs. RoughRiders
DESCRIPTION:Drillers vs. RoughRiders\n\nFollow on MiLB First Pitch: https://stza.co/+w0g2-2O\n\nShop: https://stza.co/+w0g2-3Q\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Drillers vs. RoughRiders
<2018-07-09 Mon 19:05-22:05>
:PROPERTIES:
:ID:       bZM0PA-UDe9k_3Rxop5iRatU@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Drillers vs. RoughRiders Drillers vs. RoughRiders

Follow on MiLB First Pitch  https //stza.co/+w0g5-3N

Shop  https //stza.co/+w0g5-W

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Drillers vs. RoughRiders
END:VALARM
DTSTART:20180710T000500Z
DTEND:20180710T030500Z
UID:bZM0PA-UDe9k_3Rxop5iRatU@stanza.co
SUMMARY:Drillers vs. RoughRiders
DESCRIPTION:Drillers vs. RoughRiders\n\nFollow on MiLB First Pitch: https://stza.co/+w0g5-3N\n\nShop: https://stza.co/+w0g5-W\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Drillers @ Naturals
<2018-07-11 Wed 19:05-22:05>
:PROPERTIES:
:ID:       PuA4-rS-gxvRyy9kM3z-OnWC@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Drillers @ Naturals Drillers @ Naturals

Follow on MiLB First Pitch  https //stza.co/+wi4s-28

Shop  https //stza.co/+wi4s-3r

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Drillers @ Naturals
END:VALARM
DTSTART:20180712T000500Z
DTEND:20180712T030500Z
UID:PuA4-rS-gxvRyy9kM3z-OnWC@stanza.co
SUMMARY:Drillers @ Naturals
DESCRIPTION:Drillers @ Naturals\n\nFollow on MiLB First Pitch: https://stza.co/+wi4s-28\n\nShop: https://stza.co/+wi4s-3r\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Drillers @ Naturals
<2018-07-12 Thu 19:05-22:05>
:PROPERTIES:
:ID:       R8SoPyFq8VVmOfZqU6h4z21z@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Drillers @ Naturals Drillers @ Naturals

Follow on MiLB First Pitch  https //stza.co/+wi4t-3w

Shop  https //stza.co/+wi4t-36

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Drillers @ Naturals
END:VALARM
DTSTART:20180713T000500Z
DTEND:20180713T030500Z
UID:R8SoPyFq8VVmOfZqU6h4z21z@stanza.co
SUMMARY:Drillers @ Naturals
DESCRIPTION:Drillers @ Naturals\n\nFollow on MiLB First Pitch: https://stza.co/+wi4t-3w\n\nShop: https://stza.co/+wi4t-36\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Drillers @ Naturals
<2018-07-13 Fri 19:05-22:05>
:PROPERTIES:
:ID:       3YFoyWahpZU8FNkbSGUgQ7Ya@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Drillers @ Naturals Drillers @ Naturals

Follow on MiLB First Pitch  https //stza.co/+wi4u-U

Shop  https //stza.co/+wi4u-3l

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Drillers @ Naturals
END:VALARM
DTSTART:20180714T000500Z
DTEND:20180714T030500Z
UID:3YFoyWahpZU8FNkbSGUgQ7Ya@stanza.co
SUMMARY:Drillers @ Naturals
DESCRIPTION:Drillers @ Naturals\n\nFollow on MiLB First Pitch: https://stza.co/+wi4u-U\n\nShop: https://stza.co/+wi4u-3l\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Drillers @ Naturals
<2018-07-14 Sat 18:05-21:05>
:PROPERTIES:
:ID:       mXRHFMMEXl8QST5I9dYVlWGR@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Drillers @ Naturals Drillers @ Naturals

Follow on MiLB First Pitch  https //stza.co/+wi4v-o

Shop  https //stza.co/+wi4v-2D

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Drillers @ Naturals
END:VALARM
DTSTART:20180714T230500Z
DTEND:20180715T020500Z
UID:mXRHFMMEXl8QST5I9dYVlWGR@stanza.co
SUMMARY:Drillers @ Naturals
DESCRIPTION:Drillers @ Naturals\n\nFollow on MiLB First Pitch: https://stza.co/+wi4v-o\n\nShop: https://stza.co/+wi4v-2D\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Drillers vs. Travelers
<2018-07-15 Sun 19:05-22:05>
:PROPERTIES:
:ID:       Yal0DblX8gE-Y5EZtWboa-Qc@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Drillers vs. Travelers Drillers vs. Travelers

Follow on MiLB First Pitch  https //stza.co/+w0g7-1l

Shop  https //stza.co/+w0g7-2s

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Drillers vs. Travelers
END:VALARM
DTSTART:20180716T000500Z
DTEND:20180716T030500Z
UID:Yal0DblX8gE-Y5EZtWboa-Qc@stanza.co
SUMMARY:Drillers vs. Travelers
DESCRIPTION:Drillers vs. Travelers\n\nFollow on MiLB First Pitch: https://stza.co/+w0g7-1l\n\nShop: https://stza.co/+w0g7-2s\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Drillers vs. Travelers
<2018-07-16 Mon 19:05-22:05>
:PROPERTIES:
:ID:       O6Fn2G4GuXIB3GDLWbxVLYVE@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Drillers vs. Travelers Drillers vs. Travelers

Follow on MiLB First Pitch  https //stza.co/+w0g9-1U

Shop  https //stza.co/+w0g9-r

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Drillers vs. Travelers
END:VALARM
DTSTART:20180717T000500Z
DTEND:20180717T030500Z
UID:O6Fn2G4GuXIB3GDLWbxVLYVE@stanza.co
SUMMARY:Drillers vs. Travelers
DESCRIPTION:Drillers vs. Travelers\n\nFollow on MiLB First Pitch: https://stza.co/+w0g9-1U\n\nShop: https://stza.co/+w0g9-r\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Drillers vs. Travelers
<2018-07-17 Tue 19:05-22:05>
:PROPERTIES:
:ID:       -ZqFkFuAmMx_wkYTGnvZo2qc@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Drillers vs. Travelers Drillers vs. Travelers

Follow on MiLB First Pitch  https //stza.co/+w0ga-2E

Shop  https //stza.co/+w0ga-3g

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Drillers vs. Travelers
END:VALARM
DTSTART:20180718T000500Z
DTEND:20180718T030500Z
UID:-ZqFkFuAmMx_wkYTGnvZo2qc@stanza.co
SUMMARY:Drillers vs. Travelers
DESCRIPTION:Drillers vs. Travelers\n\nFollow on MiLB First Pitch: https://stza.co/+w0ga-2E\n\nShop: https://stza.co/+w0ga-3g\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Drillers vs. Travelers
<2018-07-18 Wed 19:05-22:05>
:PROPERTIES:
:ID:       T_rOO553Gi4rkZYb_z5EgfY5@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Drillers vs. Travelers Drillers vs. Travelers

Follow on MiLB First Pitch  https //stza.co/+w0gc-2g

Shop  https //stza.co/+w0gc-2M

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Drillers vs. Travelers
END:VALARM
DTSTART:20180719T000500Z
DTEND:20180719T030500Z
UID:T_rOO553Gi4rkZYb_z5EgfY5@stanza.co
SUMMARY:Drillers vs. Travelers
DESCRIPTION:Drillers vs. Travelers\n\nFollow on MiLB First Pitch: https://stza.co/+w0gc-2g\n\nShop: https://stza.co/+w0gc-2M\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Drillers @ Naturals
<2018-07-19 Thu 19:05-22:05>
:PROPERTIES:
:ID:       XWEsj6bjeQDpH-iivu6eCT_j@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Drillers @ Naturals Drillers @ Naturals

Follow on MiLB First Pitch  https //stza.co/+wi4w-2C

Shop  https //stza.co/+wi4w-c

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Drillers @ Naturals
END:VALARM
DTSTART:20180720T000500Z
DTEND:20180720T030500Z
UID:XWEsj6bjeQDpH-iivu6eCT_j@stanza.co
SUMMARY:Drillers @ Naturals
DESCRIPTION:Drillers @ Naturals\n\nFollow on MiLB First Pitch: https://stza.co/+wi4w-2C\n\nShop: https://stza.co/+wi4w-c\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Drillers @ Naturals
<2018-07-20 Fri 19:05-22:05>
:PROPERTIES:
:ID:       QMfQysWy4ilcMWvBPXaCbdC_@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Drillers @ Naturals Drillers @ Naturals

Follow on MiLB First Pitch  https //stza.co/+wi4x-1V

Shop  https //stza.co/+wi4x-2e

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Drillers @ Naturals
END:VALARM
DTSTART:20180721T000500Z
DTEND:20180721T030500Z
UID:QMfQysWy4ilcMWvBPXaCbdC_@stanza.co
SUMMARY:Drillers @ Naturals
DESCRIPTION:Drillers @ Naturals\n\nFollow on MiLB First Pitch: https://stza.co/+wi4x-1V\n\nShop: https://stza.co/+wi4x-2e\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Drillers @ Naturals
<2018-07-21 Sat 18:05-21:05>
:PROPERTIES:
:ID:       9Z_Nq47_jLyUfervZxI68gPD@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Drillers @ Naturals Drillers @ Naturals

Follow on MiLB First Pitch  https //stza.co/+wi4y-2q

Shop  https //stza.co/+wi4y-1S

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Drillers @ Naturals
END:VALARM
DTSTART:20180721T230500Z
DTEND:20180722T020500Z
UID:9Z_Nq47_jLyUfervZxI68gPD@stanza.co
SUMMARY:Drillers @ Naturals
DESCRIPTION:Drillers @ Naturals\n\nFollow on MiLB First Pitch: https://stza.co/+wi4y-2q\n\nShop: https://stza.co/+wi4y-1S\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Drillers @ Naturals
<2018-07-22 Sun 14:05-17:05>
:PROPERTIES:
:ID:       AJI77aouEf8gD293Ohy3Le19@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Drillers @ Naturals Drillers @ Naturals

Follow on MiLB First Pitch  https //stza.co/+wi4z-2g

Shop  https //stza.co/+wi4z-3u

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Drillers @ Naturals
END:VALARM
DTSTART:20180722T190500Z
DTEND:20180722T220500Z
UID:AJI77aouEf8gD293Ohy3Le19@stanza.co
SUMMARY:Drillers @ Naturals
DESCRIPTION:Drillers @ Naturals\n\nFollow on MiLB First Pitch: https://stza.co/+wi4z-2g\n\nShop: https://stza.co/+wi4z-3u\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Drillers vs. Cardinals
<2018-07-23 Mon 19:05-22:05>
:PROPERTIES:
:ID:       rGkQtqcnH-ReLBj4r5RTfqpo@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Drillers vs. Cardinals Drillers vs. Cardinals

Follow on MiLB First Pitch  https //stza.co/+w0ge-3l

Shop  https //stza.co/+w0ge-2L

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Drillers vs. Cardinals
END:VALARM
DTSTART:20180724T000500Z
DTEND:20180724T030500Z
UID:rGkQtqcnH-ReLBj4r5RTfqpo@stanza.co
SUMMARY:Drillers vs. Cardinals
DESCRIPTION:Drillers vs. Cardinals\n\nFollow on MiLB First Pitch: https://stza.co/+w0ge-3l\n\nShop: https://stza.co/+w0ge-2L\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Drillers vs. Cardinals
<2018-07-24 Tue 19:05-22:05>
:PROPERTIES:
:ID:       rfmOpGJujfV3nj3I9fPw-v0x@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Drillers vs. Cardinals Drillers vs. Cardinals

Follow on MiLB First Pitch  https //stza.co/+w0gg-3i

Shop  https //stza.co/+w0gg-1q

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Drillers vs. Cardinals
END:VALARM
DTSTART:20180725T000500Z
DTEND:20180725T030500Z
UID:rfmOpGJujfV3nj3I9fPw-v0x@stanza.co
SUMMARY:Drillers vs. Cardinals
DESCRIPTION:Drillers vs. Cardinals\n\nFollow on MiLB First Pitch: https://stza.co/+w0gg-3i\n\nShop: https://stza.co/+w0gg-1q\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Drillers vs. Cardinals
<2018-07-25 Wed 19:05-22:05>
:PROPERTIES:
:ID:       Uooho4VT2qj3JGuNCI5n2MkL@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Drillers vs. Cardinals Drillers vs. Cardinals

Follow on MiLB First Pitch  https //stza.co/+w0gi-2I

Shop  https //stza.co/+w0gi-1

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Drillers vs. Cardinals
END:VALARM
DTSTART:20180726T000500Z
DTEND:20180726T030500Z
UID:Uooho4VT2qj3JGuNCI5n2MkL@stanza.co
SUMMARY:Drillers vs. Cardinals
DESCRIPTION:Drillers vs. Cardinals\n\nFollow on MiLB First Pitch: https://stza.co/+w0gi-2I\n\nShop: https://stza.co/+w0gi-1\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Drillers @ Travelers
<2018-07-26 Thu 19:10-22:10>
:PROPERTIES:
:ID:       -B_HQyoHWw_WQRrinWa8-3l6@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Drillers @ Travelers Drillers @ Travelers

Follow on MiLB First Pitch  https //stza.co/+w0dI-3i

Shop  https //stza.co/+w0dI-J

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Drillers @ Travelers
END:VALARM
DTSTART:20180727T001000Z
DTEND:20180727T031000Z
UID:-B_HQyoHWw_WQRrinWa8-3l6@stanza.co
SUMMARY:Drillers @ Travelers
DESCRIPTION:Drillers @ Travelers\n\nFollow on MiLB First Pitch: https://stza.co/+w0dI-3i\n\nShop: https://stza.co/+w0dI-J\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Drillers @ Travelers
<2018-07-27 Fri 19:10-22:10>
:PROPERTIES:
:ID:       znJXOOp4zL9kt05F6-n1sqRu@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Drillers @ Travelers Drillers @ Travelers

Follow on MiLB First Pitch  https //stza.co/+w0dJ-3r

Shop  https //stza.co/+w0dJ-3P

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Drillers @ Travelers
END:VALARM
DTSTART:20180728T001000Z
DTEND:20180728T031000Z
UID:znJXOOp4zL9kt05F6-n1sqRu@stanza.co
SUMMARY:Drillers @ Travelers
DESCRIPTION:Drillers @ Travelers\n\nFollow on MiLB First Pitch: https://stza.co/+w0dJ-3r\n\nShop: https://stza.co/+w0dJ-3P\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Drillers @ Travelers
<2018-07-28 Sat 18:10-21:10>
:PROPERTIES:
:ID:       RjlVW66v6kGOQUAz2QI4g_U5@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Drillers @ Travelers Drillers @ Travelers

Follow on MiLB First Pitch  https //stza.co/+w0dK-3P

Shop  https //stza.co/+w0dK-2v

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Drillers @ Travelers
END:VALARM
DTSTART:20180728T231000Z
DTEND:20180729T021000Z
UID:RjlVW66v6kGOQUAz2QI4g_U5@stanza.co
SUMMARY:Drillers @ Travelers
DESCRIPTION:Drillers @ Travelers\n\nFollow on MiLB First Pitch: https://stza.co/+w0dK-3P\n\nShop: https://stza.co/+w0dK-2v\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Drillers @ Travelers
<2018-07-29 Sun 18:10-21:10>
:PROPERTIES:
:ID:       qidzC6TpjY-lcHpUZlg6JBxy@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Drillers @ Travelers Drillers @ Travelers

Follow on MiLB First Pitch  https //stza.co/+w0dL-3y

Shop  https //stza.co/+w0dL-3a

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Drillers @ Travelers
END:VALARM
DTSTART:20180729T231000Z
DTEND:20180730T021000Z
UID:qidzC6TpjY-lcHpUZlg6JBxy@stanza.co
SUMMARY:Drillers @ Travelers
DESCRIPTION:Drillers @ Travelers\n\nFollow on MiLB First Pitch: https://stza.co/+w0dL-3y\n\nShop: https://stza.co/+w0dL-3a\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Drillers @ Cardinals
<2018-07-30 Mon 18:30-21:30>
:PROPERTIES:
:ID:       t4wC4uJZ9fYG6RuLp-7l7XXm@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Drillers @ Cardinals Drillers @ Cardinals

Follow on MiLB First Pitch  https //stza.co/+wPQW-1L

Shop  https //stza.co/+wPQW-3D

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Drillers @ Cardinals
END:VALARM
DTSTART:20180730T233000Z
DTEND:20180731T023000Z
UID:t4wC4uJZ9fYG6RuLp-7l7XXm@stanza.co
SUMMARY:Drillers @ Cardinals
DESCRIPTION:Drillers @ Cardinals\n\nFollow on MiLB First Pitch: https://stza.co/+wPQW-1L\n\nShop: https://stza.co/+wPQW-3D\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Drillers @ Cardinals
<2018-07-31 Tue 18:30-21:30>
:PROPERTIES:
:ID:       H9UJw7QgkT2-YX4YupMdNFgU@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Drillers @ Cardinals Drillers @ Cardinals

Follow on MiLB First Pitch  https //stza.co/+wPQX-1z

Shop  https //stza.co/+wPQX-1m

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Drillers @ Cardinals
END:VALARM
DTSTART:20180731T233000Z
DTEND:20180801T023000Z
UID:H9UJw7QgkT2-YX4YupMdNFgU@stanza.co
SUMMARY:Drillers @ Cardinals
DESCRIPTION:Drillers @ Cardinals\n\nFollow on MiLB First Pitch: https://stza.co/+wPQX-1z\n\nShop: https://stza.co/+wPQX-1m\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Drillers @ Cardinals
<2018-08-01 Wed 18:30-21:30>
:PROPERTIES:
:ID:       WL1kcde7o-gEVqSZFVP6I1aS@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Drillers @ Cardinals Drillers @ Cardinals

Follow on MiLB First Pitch  https //stza.co/+wPQY-2z

Shop  https //stza.co/+wPQY-2e

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Drillers @ Cardinals
END:VALARM
DTSTART:20180801T233000Z
DTEND:20180802T023000Z
UID:WL1kcde7o-gEVqSZFVP6I1aS@stanza.co
SUMMARY:Drillers @ Cardinals
DESCRIPTION:Drillers @ Cardinals\n\nFollow on MiLB First Pitch: https://stza.co/+wPQY-2z\n\nShop: https://stza.co/+wPQY-2e\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Drillers vs. Travelers
<2018-08-02 Thu 19:05-22:05>
:PROPERTIES:
:ID:       35vKW_kusrkq3E2t5seFziYE@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Drillers vs. Travelers Drillers vs. Travelers

Follow on MiLB First Pitch  https //stza.co/+w0gk-R

Shop  https //stza.co/+w0gk-

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Drillers vs. Travelers
END:VALARM
DTSTART:20180803T000500Z
DTEND:20180803T030500Z
UID:35vKW_kusrkq3E2t5seFziYE@stanza.co
SUMMARY:Drillers vs. Travelers
DESCRIPTION:Drillers vs. Travelers\n\nFollow on MiLB First Pitch: https://stza.co/+w0gk-R\n\nShop: https://stza.co/+w0gk-\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Drillers vs. Travelers
<2018-08-03 Fri 19:05-22:05>
:PROPERTIES:
:ID:       eoHe-DM0jcyyRyjRkM7W0j4_@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Drillers vs. Travelers Drillers vs. Travelers

Follow on MiLB First Pitch  https //stza.co/+w0gm-3e

Shop  https //stza.co/+w0gm-

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Drillers vs. Travelers
END:VALARM
DTSTART:20180804T000500Z
DTEND:20180804T030500Z
UID:eoHe-DM0jcyyRyjRkM7W0j4_@stanza.co
SUMMARY:Drillers vs. Travelers
DESCRIPTION:Drillers vs. Travelers\n\nFollow on MiLB First Pitch: https://stza.co/+w0gm-3e\n\nShop: https://stza.co/+w0gm-\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Drillers vs. Travelers
<2018-08-04 Sat 19:05-22:05>
:PROPERTIES:
:ID:       ohrPoZY0wwEn5OrnhRsJFP4l@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Drillers vs. Travelers Drillers vs. Travelers

Follow on MiLB First Pitch  https //stza.co/+w0go-3R

Shop  https //stza.co/+w0go-1c

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Drillers vs. Travelers
END:VALARM
DTSTART:20180805T000500Z
DTEND:20180805T030500Z
UID:ohrPoZY0wwEn5OrnhRsJFP4l@stanza.co
SUMMARY:Drillers vs. Travelers
DESCRIPTION:Drillers vs. Travelers\n\nFollow on MiLB First Pitch: https://stza.co/+w0go-3R\n\nShop: https://stza.co/+w0go-1c\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Drillers vs. Travelers
<2018-08-05 Sun 19:05-22:05>
:PROPERTIES:
:ID:       5ZczgyGwlvqy9mpmhfzC6YB0@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Drillers vs. Travelers Drillers vs. Travelers

Follow on MiLB First Pitch  https //stza.co/+w0gr-3E

Shop  https //stza.co/+w0gr-1$

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Drillers vs. Travelers
END:VALARM
DTSTART:20180806T000500Z
DTEND:20180806T030500Z
UID:5ZczgyGwlvqy9mpmhfzC6YB0@stanza.co
SUMMARY:Drillers vs. Travelers
DESCRIPTION:Drillers vs. Travelers\n\nFollow on MiLB First Pitch: https://stza.co/+w0gr-3E\n\nShop: https://stza.co/+w0gr-1$\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Drillers @ Hooks
<2018-08-07 Tue 19:05-22:05>
:PROPERTIES:
:ID:       G7QF49KwVKMqWcFwjkkYdT4e@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Drillers @ Hooks Drillers @ Hooks

Follow on MiLB First Pitch  https //stza.co/+xAIX-2f

Shop  https //stza.co/+xAIX-3o

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Drillers @ Hooks
END:VALARM
DTSTART:20180808T000500Z
DTEND:20180808T030500Z
UID:G7QF49KwVKMqWcFwjkkYdT4e@stanza.co
SUMMARY:Drillers @ Hooks
DESCRIPTION:Drillers @ Hooks\n\nFollow on MiLB First Pitch: https://stza.co/+xAIX-2f\n\nShop: https://stza.co/+xAIX-3o\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Drillers @ Hooks
<2018-08-08 Wed 19:05-22:05>
:PROPERTIES:
:ID:       WLDHf3dTuNwH2hohx8euZXbu@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Drillers @ Hooks Drillers @ Hooks

Follow on MiLB First Pitch  https //stza.co/+xAIY-1n

Shop  https //stza.co/+xAIY-3d

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Drillers @ Hooks
END:VALARM
DTSTART:20180809T000500Z
DTEND:20180809T030500Z
UID:WLDHf3dTuNwH2hohx8euZXbu@stanza.co
SUMMARY:Drillers @ Hooks
DESCRIPTION:Drillers @ Hooks\n\nFollow on MiLB First Pitch: https://stza.co/+xAIY-1n\n\nShop: https://stza.co/+xAIY-3d\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Drillers @ Hooks
<2018-08-09 Thu 19:05-22:05>
:PROPERTIES:
:ID:       Bysyj4VBYaxKrbh66KV_9p38@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Drillers @ Hooks Drillers @ Hooks

Follow on MiLB First Pitch  https //stza.co/+xAIZ-2g

Shop  https //stza.co/+xAIZ-2a

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Drillers @ Hooks
END:VALARM
DTSTART:20180810T000500Z
DTEND:20180810T030500Z
UID:Bysyj4VBYaxKrbh66KV_9p38@stanza.co
SUMMARY:Drillers @ Hooks
DESCRIPTION:Drillers @ Hooks\n\nFollow on MiLB First Pitch: https://stza.co/+xAIZ-2g\n\nShop: https://stza.co/+xAIZ-2a\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Drillers @ Missions
<2018-08-10 Fri 19:05-22:05>
:PROPERTIES:
:ID:       wdncOHOc2Sp0B_6pJb-0PHR0@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Drillers @ Missions Drillers @ Missions

Follow on MiLB First Pitch  https //stza.co/+wMAd-1r

Shop  https //stza.co/+wMAd-3y

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Drillers @ Missions
END:VALARM
DTSTART:20180811T000500Z
DTEND:20180811T030500Z
UID:wdncOHOc2Sp0B_6pJb-0PHR0@stanza.co
SUMMARY:Drillers @ Missions
DESCRIPTION:Drillers @ Missions\n\nFollow on MiLB First Pitch: https://stza.co/+wMAd-1r\n\nShop: https://stza.co/+wMAd-3y\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Drillers @ Missions
<2018-08-11 Sat 19:05-22:05>
:PROPERTIES:
:ID:       KU9zGuK-RM2_Q2FTjpEY7Edh@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Drillers @ Missions Drillers @ Missions

Follow on MiLB First Pitch  https //stza.co/+wMAe-3o

Shop  https //stza.co/+wMAe-1h

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Drillers @ Missions
END:VALARM
DTSTART:20180812T000500Z
DTEND:20180812T030500Z
UID:KU9zGuK-RM2_Q2FTjpEY7Edh@stanza.co
SUMMARY:Drillers @ Missions
DESCRIPTION:Drillers @ Missions\n\nFollow on MiLB First Pitch: https://stza.co/+wMAe-3o\n\nShop: https://stza.co/+wMAe-1h\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Drillers @ Missions
<2018-08-12 Sun 18:05-21:05>
:PROPERTIES:
:ID:       U0qEETazMps4cj-xo9bfZkhr@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Drillers @ Missions Drillers @ Missions

Follow on MiLB First Pitch  https //stza.co/+wMAf-1i

Shop  https //stza.co/+wMAf-30

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Drillers @ Missions
END:VALARM
DTSTART:20180812T230500Z
DTEND:20180813T020500Z
UID:U0qEETazMps4cj-xo9bfZkhr@stanza.co
SUMMARY:Drillers @ Missions
DESCRIPTION:Drillers @ Missions\n\nFollow on MiLB First Pitch: https://stza.co/+wMAf-1i\n\nShop: https://stza.co/+wMAf-30\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Drillers vs. Hooks
<2018-08-14 Tue 19:05-22:05>
:PROPERTIES:
:ID:       5AoRJsNKI51YlV2nKgPF3lgs@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Drillers vs. Hooks Drillers vs. Hooks

Follow on MiLB First Pitch  https //stza.co/+w0gs-2s

Shop  https //stza.co/+w0gs-2I

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Drillers vs. Hooks
END:VALARM
DTSTART:20180815T000500Z
DTEND:20180815T030500Z
UID:5AoRJsNKI51YlV2nKgPF3lgs@stanza.co
SUMMARY:Drillers vs. Hooks
DESCRIPTION:Drillers vs. Hooks\n\nFollow on MiLB First Pitch: https://stza.co/+w0gs-2s\n\nShop: https://stza.co/+w0gs-2I\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Drillers vs. Hooks
<2018-08-15 Wed 19:05-22:05>
:PROPERTIES:
:ID:       qniIr_00xOScFWeb46CC2Dp-@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Drillers vs. Hooks Drillers vs. Hooks

Follow on MiLB First Pitch  https //stza.co/+w0gv-2y

Shop  https //stza.co/+w0gv-w

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Drillers vs. Hooks
END:VALARM
DTSTART:20180816T000500Z
DTEND:20180816T030500Z
UID:qniIr_00xOScFWeb46CC2Dp-@stanza.co
SUMMARY:Drillers vs. Hooks
DESCRIPTION:Drillers vs. Hooks\n\nFollow on MiLB First Pitch: https://stza.co/+w0gv-2y\n\nShop: https://stza.co/+w0gv-w\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Drillers vs. Hooks
<2018-08-16 Thu 19:05-22:05>
:PROPERTIES:
:ID:       -vqeyq3sVMKTkOhqqp24jGo3@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Drillers vs. Hooks Drillers vs. Hooks

Follow on MiLB First Pitch  https //stza.co/+w0gx-1I

Shop  https //stza.co/+w0gx-3K

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Drillers vs. Hooks
END:VALARM
DTSTART:20180817T000500Z
DTEND:20180817T030500Z
UID:-vqeyq3sVMKTkOhqqp24jGo3@stanza.co
SUMMARY:Drillers vs. Hooks
DESCRIPTION:Drillers vs. Hooks\n\nFollow on MiLB First Pitch: https://stza.co/+w0gx-1I\n\nShop: https://stza.co/+w0gx-3K\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Drillers vs. Missions
<2018-08-17 Fri 19:05-22:05>
:PROPERTIES:
:ID:       4yKJpD3rZeD0BZvs2Hg2MlcL@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Drillers vs. Missions Drillers vs. Missions

Follow on MiLB First Pitch  https //stza.co/+w0gy-3h

Shop  https //stza.co/+w0gy-z

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Drillers vs. Missions
END:VALARM
DTSTART:20180818T000500Z
DTEND:20180818T030500Z
UID:4yKJpD3rZeD0BZvs2Hg2MlcL@stanza.co
SUMMARY:Drillers vs. Missions
DESCRIPTION:Drillers vs. Missions\n\nFollow on MiLB First Pitch: https://stza.co/+w0gy-3h\n\nShop: https://stza.co/+w0gy-z\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Drillers vs. Missions
<2018-08-18 Sat 19:05-22:05>
:PROPERTIES:
:ID:       ZglvlyXhKVil6_asgGG9u5NC@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Drillers vs. Missions Drillers vs. Missions

Follow on MiLB First Pitch  https //stza.co/+w0gB-3g

Shop  https //stza.co/+w0gB-y

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Drillers vs. Missions
END:VALARM
DTSTART:20180819T000500Z
DTEND:20180819T030500Z
UID:ZglvlyXhKVil6_asgGG9u5NC@stanza.co
SUMMARY:Drillers vs. Missions
DESCRIPTION:Drillers vs. Missions\n\nFollow on MiLB First Pitch: https://stza.co/+w0gB-3g\n\nShop: https://stza.co/+w0gB-y\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Drillers vs. Missions
<2018-08-19 Sun 19:05-22:05>
:PROPERTIES:
:ID:       s8owLX9Vlm94nLNLVcLtK7m_@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Drillers vs. Missions Drillers vs. Missions

Follow on MiLB First Pitch  https //stza.co/+w0gC-2p

Shop  https //stza.co/+w0gC-2F

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Drillers vs. Missions
END:VALARM
DTSTART:20180820T000500Z
DTEND:20180820T030500Z
UID:s8owLX9Vlm94nLNLVcLtK7m_@stanza.co
SUMMARY:Drillers vs. Missions
DESCRIPTION:Drillers vs. Missions\n\nFollow on MiLB First Pitch: https://stza.co/+w0gC-2p\n\nShop: https://stza.co/+w0gC-2F\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Drillers @ Travelers
<2018-08-21 Tue 19:10-22:10>
:PROPERTIES:
:ID:       gCbtaGgAJ-pxWubs_4J-mxIN@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Drillers @ Travelers Drillers @ Travelers

Follow on MiLB First Pitch  https //stza.co/+w0dM-l

Shop  https //stza.co/+w0dM-1T

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Drillers @ Travelers
END:VALARM
DTSTART:20180822T001000Z
DTEND:20180822T031000Z
UID:gCbtaGgAJ-pxWubs_4J-mxIN@stanza.co
SUMMARY:Drillers @ Travelers
DESCRIPTION:Drillers @ Travelers\n\nFollow on MiLB First Pitch: https://stza.co/+w0dM-l\n\nShop: https://stza.co/+w0dM-1T\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Drillers @ Travelers
<2018-08-22 Wed 19:10-22:10>
:PROPERTIES:
:ID:       s3jXUjZ6sNscVvTpkXGJJfDK@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Drillers @ Travelers Drillers @ Travelers

Follow on MiLB First Pitch  https //stza.co/+w0dN-2Q

Shop  https //stza.co/+w0dN-18

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Drillers @ Travelers
END:VALARM
DTSTART:20180823T001000Z
DTEND:20180823T031000Z
UID:s3jXUjZ6sNscVvTpkXGJJfDK@stanza.co
SUMMARY:Drillers @ Travelers
DESCRIPTION:Drillers @ Travelers\n\nFollow on MiLB First Pitch: https://stza.co/+w0dN-2Q\n\nShop: https://stza.co/+w0dN-18\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Drillers @ Travelers
<2018-08-23 Thu 19:10-22:10>
:PROPERTIES:
:ID:       Bi2dpSkyqmNtkzHTQQ6wZeci@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Drillers @ Travelers Drillers @ Travelers

Follow on MiLB First Pitch  https //stza.co/+w0dO-2k

Shop  https //stza.co/+w0dO-1M

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Drillers @ Travelers
END:VALARM
DTSTART:20180824T001000Z
DTEND:20180824T031000Z
UID:Bi2dpSkyqmNtkzHTQQ6wZeci@stanza.co
SUMMARY:Drillers @ Travelers
DESCRIPTION:Drillers @ Travelers\n\nFollow on MiLB First Pitch: https://stza.co/+w0dO-2k\n\nShop: https://stza.co/+w0dO-1M\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Drillers @ Travelers
<2018-08-24 Fri 19:10-22:10>
:PROPERTIES:
:ID:       EACctoeJ0gQBkPr5-C0QYwvO@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Drillers @ Travelers Drillers @ Travelers

Follow on MiLB First Pitch  https //stza.co/+w0dP-$

Shop  https //stza.co/+w0dP-1r

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Drillers @ Travelers
END:VALARM
DTSTART:20180825T001000Z
DTEND:20180825T031000Z
UID:EACctoeJ0gQBkPr5-C0QYwvO@stanza.co
SUMMARY:Drillers @ Travelers
DESCRIPTION:Drillers @ Travelers\n\nFollow on MiLB First Pitch: https://stza.co/+w0dP-$\n\nShop: https://stza.co/+w0dP-1r\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Drillers vs. Cardinals
<2018-08-25 Sat 19:05-22:05>
:PROPERTIES:
:ID:       z88nVibNVnZ6LxJsxCroCHHS@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Drillers vs. Cardinals Drillers vs. Cardinals

Follow on MiLB First Pitch  https //stza.co/+w0gE-3c

Shop  https //stza.co/+w0gE-j

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Drillers vs. Cardinals
END:VALARM
DTSTART:20180826T000500Z
DTEND:20180826T030500Z
UID:z88nVibNVnZ6LxJsxCroCHHS@stanza.co
SUMMARY:Drillers vs. Cardinals
DESCRIPTION:Drillers vs. Cardinals\n\nFollow on MiLB First Pitch: https://stza.co/+w0gE-3c\n\nShop: https://stza.co/+w0gE-j\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Drillers vs. Cardinals
<2018-08-26 Sun 19:05-22:05>
:PROPERTIES:
:ID:       GIv45sGSsDJGu2oFr9vnviQw@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Drillers vs. Cardinals Drillers vs. Cardinals

Follow on MiLB First Pitch  https //stza.co/+w0gH-d

Shop  https //stza.co/+w0gH-I

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Drillers vs. Cardinals
END:VALARM
DTSTART:20180827T000500Z
DTEND:20180827T030500Z
UID:GIv45sGSsDJGu2oFr9vnviQw@stanza.co
SUMMARY:Drillers vs. Cardinals
DESCRIPTION:Drillers vs. Cardinals\n\nFollow on MiLB First Pitch: https://stza.co/+w0gH-d\n\nShop: https://stza.co/+w0gH-I\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Drillers vs. Cardinals
<2018-08-27 Mon 19:05-22:05>
:PROPERTIES:
:ID:       SczQVhWrR41hV88F-iw2qRe4@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Drillers vs. Cardinals Drillers vs. Cardinals

Follow on MiLB First Pitch  https //stza.co/+w0gI-1l

Shop  https //stza.co/+w0gI-1q

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Drillers vs. Cardinals
END:VALARM
DTSTART:20180828T000500Z
DTEND:20180828T030500Z
UID:SczQVhWrR41hV88F-iw2qRe4@stanza.co
SUMMARY:Drillers vs. Cardinals
DESCRIPTION:Drillers vs. Cardinals\n\nFollow on MiLB First Pitch: https://stza.co/+w0gI-1l\n\nShop: https://stza.co/+w0gI-1q\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Drillers vs. Naturals
<2018-08-28 Tue 19:05-22:05>
:PROPERTIES:
:ID:       ZpFv4WgdgCfqFFq98hC4F6dv@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Drillers vs. Naturals Drillers vs. Naturals

Follow on MiLB First Pitch  https //stza.co/+w0gL-3J

Shop  https //stza.co/+w0gL-2z

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Drillers vs. Naturals
END:VALARM
DTSTART:20180829T000500Z
DTEND:20180829T030500Z
UID:ZpFv4WgdgCfqFFq98hC4F6dv@stanza.co
SUMMARY:Drillers vs. Naturals
DESCRIPTION:Drillers vs. Naturals\n\nFollow on MiLB First Pitch: https://stza.co/+w0gL-3J\n\nShop: https://stza.co/+w0gL-2z\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Drillers vs. Naturals
<2018-08-29 Wed 19:05-22:05>
:PROPERTIES:
:ID:       yY6RUco3YmtCSBoij7Gm2A7r@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Drillers vs. Naturals Drillers vs. Naturals

Follow on MiLB First Pitch  https //stza.co/+w0gN-2l

Shop  https //stza.co/+w0gN-1$

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Drillers vs. Naturals
END:VALARM
DTSTART:20180830T000500Z
DTEND:20180830T030500Z
UID:yY6RUco3YmtCSBoij7Gm2A7r@stanza.co
SUMMARY:Drillers vs. Naturals
DESCRIPTION:Drillers vs. Naturals\n\nFollow on MiLB First Pitch: https://stza.co/+w0gN-2l\n\nShop: https://stza.co/+w0gN-1$\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Drillers vs. Naturals
<2018-08-30 Thu 19:05-22:05>
:PROPERTIES:
:ID:       7-sFFm-mkhn12j-JZGBIde-8@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Drillers vs. Naturals Drillers vs. Naturals

Follow on MiLB First Pitch  https //stza.co/+w0gO-2y

Shop  https //stza.co/+w0gO-T

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Drillers vs. Naturals
END:VALARM
DTSTART:20180831T000500Z
DTEND:20180831T030500Z
UID:7-sFFm-mkhn12j-JZGBIde-8@stanza.co
SUMMARY:Drillers vs. Naturals
DESCRIPTION:Drillers vs. Naturals\n\nFollow on MiLB First Pitch: https://stza.co/+w0gO-2y\n\nShop: https://stza.co/+w0gO-T\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Drillers vs. Naturals
<2018-08-31 Fri 19:05-22:05>
:PROPERTIES:
:ID:       -njTJ-ML5-XE0St7Hb9xCx8M@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Drillers vs. Naturals Drillers vs. Naturals

Follow on MiLB First Pitch  https //stza.co/+w0gR-2j

Shop  https //stza.co/+w0gR-3M

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Drillers vs. Naturals
END:VALARM
DTSTART:20180901T000500Z
DTEND:20180901T030500Z
UID:-njTJ-ML5-XE0St7Hb9xCx8M@stanza.co
SUMMARY:Drillers vs. Naturals
DESCRIPTION:Drillers vs. Naturals\n\nFollow on MiLB First Pitch: https://stza.co/+w0gR-2j\n\nShop: https://stza.co/+w0gR-3M\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Drillers @ Cardinals
<2018-09-01 Sat 18:10-21:10>
:PROPERTIES:
:ID:       hWc4XnYK15bktZI2AwzrbX_S@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Drillers @ Cardinals Drillers @ Cardinals

Follow on MiLB First Pitch  https //stza.co/+wPQZ-39

Shop  https //stza.co/+wPQZ-6

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Drillers @ Cardinals
END:VALARM
DTSTART:20180901T231000Z
DTEND:20180902T021000Z
UID:hWc4XnYK15bktZI2AwzrbX_S@stanza.co
SUMMARY:Drillers @ Cardinals
DESCRIPTION:Drillers @ Cardinals\n\nFollow on MiLB First Pitch: https://stza.co/+wPQZ-39\n\nShop: https://stza.co/+wPQZ-6\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Drillers @ Cardinals
<2018-09-02 Sun 18:10-21:10>
:PROPERTIES:
:ID:       xaAJoXXoYBU3sWGje4gSzWmQ@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Drillers @ Cardinals Drillers @ Cardinals

Follow on MiLB First Pitch  https //stza.co/+wPQ_-1s

Shop  https //stza.co/+wPQ_-2I

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Drillers @ Cardinals
END:VALARM
DTSTART:20180902T231000Z
DTEND:20180903T021000Z
UID:xaAJoXXoYBU3sWGje4gSzWmQ@stanza.co
SUMMARY:Drillers @ Cardinals
DESCRIPTION:Drillers @ Cardinals\n\nFollow on MiLB First Pitch: https://stza.co/+wPQ_-1s\n\nShop: https://stza.co/+wPQ_-2I\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Drillers @ Cardinals
<2018-09-03 Mon 12:15-15:15>
:PROPERTIES:
:ID:       TZxUSLoUJnkpus5IgYzMJpYI@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Drillers @ Cardinals Drillers @ Cardinals

Follow on MiLB First Pitch  https //stza.co/+wPQ$-20

Shop  https //stza.co/+wPQ$-1n

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Drillers @ Cardinals
END:VALARM
DTSTART:20180903T171500Z
DTEND:20180903T201500Z
UID:TZxUSLoUJnkpus5IgYzMJpYI@stanza.co
SUMMARY:Drillers @ Cardinals
DESCRIPTION:Drillers @ Cardinals\n\nFollow on MiLB First Pitch: https://stza.co/+wPQ$-20\n\nShop: https://stza.co/+wPQ$-1n\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
