#+TITLE:       Main Google calendar entries
#+AUTHOR:      Eric S Fraga
#+EMAIL:       e.fraga@ucl.ac.uk
#+DESCRIPTION: converted using the ical2org awk script
#+CATEGORY:    google
#+STARTUP:     hidestars
#+STARTUP:     overview

* COMMENT original iCal preamble

* Giants @ 66ers
<2018-04-05 Thu 21:05>--<2018-04-06 Fri 00:05>
:PROPERTIES:
:ID:       saub5PsQmUZH_pa6GlguJvIa@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Giants @ 66ers Giants @ 66ers

Follow on MiLB First Pitch  https //stza.co/+y0CU-2d

Shop  https //stza.co/+y0CU-2V

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Giants @ 66ers
END:VALARM
DTSTART:20180406T020500Z
DTEND:20180406T050500Z
UID:saub5PsQmUZH_pa6GlguJvIa@stanza.co
SUMMARY:Giants @ 66ers
DESCRIPTION:Giants @ 66ers\n\nFollow on MiLB First Pitch: https://stza.co/+y0CU-2d\n\nShop: https://stza.co/+y0CU-2V\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144557Z
LAST-MODIFIED:20180213T144557Z
TRANSP:OPAQUE
END:VEVENT
* Giants @ 66ers
<2018-04-06 Fri 21:05>--<2018-04-07 Sat 00:05>
:PROPERTIES:
:ID:       1u06hEAeLHfpYYgxisqkL7b2@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Giants @ 66ers Giants @ 66ers

Follow on MiLB First Pitch  https //stza.co/+y0CV-2q

Shop  https //stza.co/+y0CV-3i

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Giants @ 66ers
END:VALARM
DTSTART:20180407T020500Z
DTEND:20180407T050500Z
UID:1u06hEAeLHfpYYgxisqkL7b2@stanza.co
SUMMARY:Giants @ 66ers
DESCRIPTION:Giants @ 66ers\n\nFollow on MiLB First Pitch: https://stza.co/+y0CV-2q\n\nShop: https://stza.co/+y0CV-3i\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144557Z
LAST-MODIFIED:20180213T144557Z
TRANSP:OPAQUE
END:VEVENT
* Giants @ 66ers
<2018-04-07 Sat 20:05-23:05>
:PROPERTIES:
:ID:       NOXErOt9v0t0A5sZUtsUOi7w@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Giants @ 66ers Giants @ 66ers

Follow on MiLB First Pitch  https //stza.co/+y0CW-b

Shop  https //stza.co/+y0CW-15

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Giants @ 66ers
END:VALARM
DTSTART:20180408T010500Z
DTEND:20180408T040500Z
UID:NOXErOt9v0t0A5sZUtsUOi7w@stanza.co
SUMMARY:Giants @ 66ers
DESCRIPTION:Giants @ 66ers\n\nFollow on MiLB First Pitch: https://stza.co/+y0CW-b\n\nShop: https://stza.co/+y0CW-15\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144557Z
LAST-MODIFIED:20180213T144557Z
TRANSP:OPAQUE
END:VEVENT
* Giants @ 66ers
<2018-04-08 Sun 16:05-19:05>
:PROPERTIES:
:ID:       3ZYbsoRzOUx5pB6yfXC-SdNp@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Giants @ 66ers Giants @ 66ers

Follow on MiLB First Pitch  https //stza.co/+y0CX-Y

Shop  https //stza.co/+y0CX-3D

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Giants @ 66ers
END:VALARM
DTSTART:20180408T210500Z
DTEND:20180409T000500Z
UID:3ZYbsoRzOUx5pB6yfXC-SdNp@stanza.co
SUMMARY:Giants @ 66ers
DESCRIPTION:Giants @ 66ers\n\nFollow on MiLB First Pitch: https://stza.co/+y0CX-Y\n\nShop: https://stza.co/+y0CX-3D\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144557Z
LAST-MODIFIED:20180213T144557Z
TRANSP:OPAQUE
END:VEVENT
* Giants @ JetHawks
<2018-04-09 Mon 20:35-23:35>
:PROPERTIES:
:ID:       VNmh-km51gZ9tzZxgcJEjUcc@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Giants @ JetHawks Giants @ JetHawks

Follow on MiLB First Pitch  https //stza.co/+vfbR-3P

Shop  https //stza.co/+vfbR-

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Giants @ JetHawks
END:VALARM
DTSTART:20180410T013500Z
DTEND:20180410T043500Z
UID:VNmh-km51gZ9tzZxgcJEjUcc@stanza.co
SUMMARY:Giants @ JetHawks
DESCRIPTION:Giants @ JetHawks\n\nFollow on MiLB First Pitch: https://stza.co/+vfbR-3P\n\nShop: https://stza.co/+vfbR-\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144557Z
LAST-MODIFIED:20180213T144557Z
TRANSP:OPAQUE
END:VEVENT
* Giants @ JetHawks
<2018-04-10 Tue 20:35-23:35>
:PROPERTIES:
:ID:       YaSNt_sFK10dfp1nJHOemPOZ@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Giants @ JetHawks Giants @ JetHawks

Follow on MiLB First Pitch  https //stza.co/+vfb_-m

Shop  https //stza.co/+vfb_-3U

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Giants @ JetHawks
END:VALARM
DTSTART:20180411T013500Z
DTEND:20180411T043500Z
UID:YaSNt_sFK10dfp1nJHOemPOZ@stanza.co
SUMMARY:Giants @ JetHawks
DESCRIPTION:Giants @ JetHawks\n\nFollow on MiLB First Pitch: https://stza.co/+vfb_-m\n\nShop: https://stza.co/+vfb_-3U\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144557Z
LAST-MODIFIED:20180213T144557Z
TRANSP:OPAQUE
END:VEVENT
* Giants @ JetHawks
<2018-04-11 Wed 20:35-23:35>
:PROPERTIES:
:ID:       jgdN10RPkWUhf3Yhu3Q_Q_lo@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Giants @ JetHawks Giants @ JetHawks

Follow on MiLB First Pitch  https //stza.co/+vfc6-1j

Shop  https //stza.co/+vfc6-z

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Giants @ JetHawks
END:VALARM
DTSTART:20180412T013500Z
DTEND:20180412T043500Z
UID:jgdN10RPkWUhf3Yhu3Q_Q_lo@stanza.co
SUMMARY:Giants @ JetHawks
DESCRIPTION:Giants @ JetHawks\n\nFollow on MiLB First Pitch: https://stza.co/+vfc6-1j\n\nShop: https://stza.co/+vfc6-z\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144557Z
LAST-MODIFIED:20180213T144557Z
TRANSP:OPAQUE
END:VEVENT
* Giants vs. Ports
<2018-04-12 Thu 21:00>--<2018-04-13 Fri 00:00>
:PROPERTIES:
:ID:       oRYmZXVBgr7tPCLfiHZ-EH-q@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Giants vs. Ports Giants vs. Ports

Follow on MiLB First Pitch  https //stza.co/+xEWv-15

Shop  https //stza.co/+xEWv-3U

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Giants vs. Ports
END:VALARM
DTSTART:20180413T020000Z
DTEND:20180413T050000Z
UID:oRYmZXVBgr7tPCLfiHZ-EH-q@stanza.co
SUMMARY:Giants vs. Ports
DESCRIPTION:Giants vs. Ports\n\nFollow on MiLB First Pitch: https://stza.co/+xEWv-15\n\nShop: https://stza.co/+xEWv-3U\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144557Z
LAST-MODIFIED:20180213T144557Z
TRANSP:OPAQUE
END:VEVENT
* Giants vs. Ports
<2018-04-13 Fri 21:00>--<2018-04-14 Sat 00:00>
:PROPERTIES:
:ID:       fBj8TDqKvH8et8FO-Dewqrji@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Giants vs. Ports Giants vs. Ports

Follow on MiLB First Pitch  https //stza.co/+xEWx-3x

Shop  https //stza.co/+xEWx-3y

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Giants vs. Ports
END:VALARM
DTSTART:20180414T020000Z
DTEND:20180414T050000Z
UID:fBj8TDqKvH8et8FO-Dewqrji@stanza.co
SUMMARY:Giants vs. Ports
DESCRIPTION:Giants vs. Ports\n\nFollow on MiLB First Pitch: https://stza.co/+xEWx-3x\n\nShop: https://stza.co/+xEWx-3y\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144557Z
LAST-MODIFIED:20180213T144557Z
TRANSP:OPAQUE
END:VEVENT
* Giants vs. Ports
<2018-04-14 Sat 20:00-23:00>
:PROPERTIES:
:ID:       0HSdVkZwaSVDAnaQ5sw-aOpw@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Giants vs. Ports Giants vs. Ports

Follow on MiLB First Pitch  https //stza.co/+xKKI-7

Shop  https //stza.co/+xKKI-1H

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Giants vs. Ports
END:VALARM
DTSTART:20180415T010000Z
DTEND:20180415T040000Z
UID:0HSdVkZwaSVDAnaQ5sw-aOpw@stanza.co
SUMMARY:Giants vs. Ports
DESCRIPTION:Giants vs. Ports\n\nFollow on MiLB First Pitch: https://stza.co/+xKKI-7\n\nShop: https://stza.co/+xKKI-1H\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144557Z
LAST-MODIFIED:20180213T144557Z
TRANSP:OPAQUE
END:VEVENT
* Giants vs. Ports
<2018-04-15 Sun 15:00-18:00>
:PROPERTIES:
:ID:       r1zHf0PfzYCcDrEbciRTXs36@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Giants vs. Ports Giants vs. Ports

Follow on MiLB First Pitch  https //stza.co/+xEWB-2M

Shop  https //stza.co/+xEWB-10

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Giants vs. Ports
END:VALARM
DTSTART:20180415T200000Z
DTEND:20180415T230000Z
UID:r1zHf0PfzYCcDrEbciRTXs36@stanza.co
SUMMARY:Giants vs. Ports
DESCRIPTION:Giants vs. Ports\n\nFollow on MiLB First Pitch: https://stza.co/+xEWB-2M\n\nShop: https://stza.co/+xEWB-10\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144557Z
LAST-MODIFIED:20180213T144557Z
TRANSP:OPAQUE
END:VEVENT
* Giants @ Rawhide
<2018-04-16 Mon>--<2018-04-15 Sun>
:PROPERTIES:
:ID:       LwVEXH_3A0ZlZ0mbbuSlHtkO@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Giants @ Rawhide Giants @ Rawhide

Follow on MiLB First Pitch  https //stza.co/+vM1O-1k

Shop  https //stza.co/+vM1O-1

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Giants @ Rawhide
END:VALARM
DTSTART;VALUE=DATE:20180416
DTEND;VALUE=DATE:20180416
UID:LwVEXH_3A0ZlZ0mbbuSlHtkO@stanza.co
SUMMARY:Giants @ Rawhide
DESCRIPTION:Giants @ Rawhide\n\nFollow on MiLB First Pitch: https://stza.co/+vM1O-1k\n\nShop: https://stza.co/+vM1O-1\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144557Z
LAST-MODIFIED:20180213T144557Z
TRANSP:OPAQUE
END:VEVENT
* Giants @ Rawhide
<2018-04-17 Tue>--<2018-04-16 Mon>
:PROPERTIES:
:ID:       ENpS2ipbv0KhxTSTsSGHaOeK@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Giants @ Rawhide Giants @ Rawhide

Follow on MiLB First Pitch  https //stza.co/+vM1P-1G

Shop  https //stza.co/+vM1P-3Y

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Giants @ Rawhide
END:VALARM
DTSTART;VALUE=DATE:20180417
DTEND;VALUE=DATE:20180417
UID:ENpS2ipbv0KhxTSTsSGHaOeK@stanza.co
SUMMARY:Giants @ Rawhide
DESCRIPTION:Giants @ Rawhide\n\nFollow on MiLB First Pitch: https://stza.co/+vM1P-1G\n\nShop: https://stza.co/+vM1P-3Y\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144557Z
LAST-MODIFIED:20180213T144557Z
TRANSP:OPAQUE
END:VEVENT
* Giants @ Rawhide
<2018-04-18 Wed>--<2018-04-17 Tue>
:PROPERTIES:
:ID:       z6duqImt4SWNrwpeHE9a4lc-@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Giants @ Rawhide Giants @ Rawhide

Follow on MiLB First Pitch  https //stza.co/+vM1Q-r

Shop  https //stza.co/+vM1Q-29

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Giants @ Rawhide
END:VALARM
DTSTART;VALUE=DATE:20180418
DTEND;VALUE=DATE:20180418
UID:z6duqImt4SWNrwpeHE9a4lc-@stanza.co
SUMMARY:Giants @ Rawhide
DESCRIPTION:Giants @ Rawhide\n\nFollow on MiLB First Pitch: https://stza.co/+vM1Q-r\n\nShop: https://stza.co/+vM1Q-29\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144557Z
LAST-MODIFIED:20180213T144557Z
TRANSP:OPAQUE
END:VEVENT
* Giants vs. Nuts
<2018-04-19 Thu 21:00>--<2018-04-20 Fri 00:00>
:PROPERTIES:
:ID:       QWuf4fmhwfh_OG4QhCHE15RR@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Giants vs. Nuts Giants vs. Nuts

Follow on MiLB First Pitch  https //stza.co/+xEWE-2X

Shop  https //stza.co/+xEWE-h

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Giants vs. Nuts
END:VALARM
DTSTART:20180420T020000Z
DTEND:20180420T050000Z
UID:QWuf4fmhwfh_OG4QhCHE15RR@stanza.co
SUMMARY:Giants vs. Nuts
DESCRIPTION:Giants vs. Nuts\n\nFollow on MiLB First Pitch: https://stza.co/+xEWE-2X\n\nShop: https://stza.co/+xEWE-h\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144557Z
LAST-MODIFIED:20180213T144557Z
TRANSP:OPAQUE
END:VEVENT
* Giants vs. Nuts
<2018-04-20 Fri 21:00>--<2018-04-21 Sat 00:00>
:PROPERTIES:
:ID:       aGifdg2fZ9xcR8-9uz5iLxjL@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Giants vs. Nuts Giants vs. Nuts

Follow on MiLB First Pitch  https //stza.co/+xEWG-1X

Shop  https //stza.co/+xEWG-3D

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Giants vs. Nuts
END:VALARM
DTSTART:20180421T020000Z
DTEND:20180421T050000Z
UID:aGifdg2fZ9xcR8-9uz5iLxjL@stanza.co
SUMMARY:Giants vs. Nuts
DESCRIPTION:Giants vs. Nuts\n\nFollow on MiLB First Pitch: https://stza.co/+xEWG-1X\n\nShop: https://stza.co/+xEWG-3D\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144557Z
LAST-MODIFIED:20180213T144557Z
TRANSP:OPAQUE
END:VEVENT
* Giants vs. Nuts
<2018-04-21 Sat 19:00-22:00>
:PROPERTIES:
:ID:       3GvfkmJwSu62SdvrZPYdFGWQ@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Giants vs. Nuts Giants vs. Nuts

Follow on MiLB First Pitch  https //stza.co/+xEWH-3a

Shop  https //stza.co/+xEWH-2S

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Giants vs. Nuts
END:VALARM
DTSTART:20180422T000000Z
DTEND:20180422T030000Z
UID:3GvfkmJwSu62SdvrZPYdFGWQ@stanza.co
SUMMARY:Giants vs. Nuts
DESCRIPTION:Giants vs. Nuts\n\nFollow on MiLB First Pitch: https://stza.co/+xEWH-3a\n\nShop: https://stza.co/+xEWH-2S\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144557Z
LAST-MODIFIED:20180213T144557Z
TRANSP:OPAQUE
END:VEVENT
* Giants vs. Nuts
<2018-04-22 Sun 15:00-18:00>
:PROPERTIES:
:ID:       yoN1u0qk-i2Go7OIdfsahq2v@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Giants vs. Nuts Giants vs. Nuts

Follow on MiLB First Pitch  https //stza.co/+xEWK-2t

Shop  https //stza.co/+xEWK-3y

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Giants vs. Nuts
END:VALARM
DTSTART:20180422T200000Z
DTEND:20180422T230000Z
UID:yoN1u0qk-i2Go7OIdfsahq2v@stanza.co
SUMMARY:Giants vs. Nuts
DESCRIPTION:Giants vs. Nuts\n\nFollow on MiLB First Pitch: https://stza.co/+xEWK-2t\n\nShop: https://stza.co/+xEWK-3y\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144557Z
LAST-MODIFIED:20180213T144557Z
TRANSP:OPAQUE
END:VEVENT
* Giants vs. Storm
<2018-04-23 Mon 20:30-23:30>
:PROPERTIES:
:ID:       -pyz7-xFroov5sXt7ggm_Kn9@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Giants vs. Storm Giants vs. Storm

Follow on MiLB First Pitch  https //stza.co/+xEWL-3z

Shop  https //stza.co/+xEWL-3s

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Giants vs. Storm
END:VALARM
DTSTART:20180424T013000Z
DTEND:20180424T043000Z
UID:-pyz7-xFroov5sXt7ggm_Kn9@stanza.co
SUMMARY:Giants vs. Storm
DESCRIPTION:Giants vs. Storm\n\nFollow on MiLB First Pitch: https://stza.co/+xEWL-3z\n\nShop: https://stza.co/+xEWL-3s\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144557Z
LAST-MODIFIED:20180213T144557Z
TRANSP:OPAQUE
END:VEVENT
* Giants vs. Storm
<2018-04-24 Tue 20:30-23:30>
:PROPERTIES:
:ID:       yJIUiclPz8U1IfURDvjtsVgB@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Giants vs. Storm Giants vs. Storm

Follow on MiLB First Pitch  https //stza.co/+xEWN-1G

Shop  https //stza.co/+xEWN-n

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Giants vs. Storm
END:VALARM
DTSTART:20180425T013000Z
DTEND:20180425T043000Z
UID:yJIUiclPz8U1IfURDvjtsVgB@stanza.co
SUMMARY:Giants vs. Storm
DESCRIPTION:Giants vs. Storm\n\nFollow on MiLB First Pitch: https://stza.co/+xEWN-1G\n\nShop: https://stza.co/+xEWN-n\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144557Z
LAST-MODIFIED:20180213T144557Z
TRANSP:OPAQUE
END:VEVENT
* Giants vs. Storm
<2018-04-25 Wed 13:30-16:30>
:PROPERTIES:
:ID:       zeDKzO9WuUuXzYd3zzD5meN8@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Giants vs. Storm Giants vs. Storm

Follow on MiLB First Pitch  https //stza.co/+xEWP-3H

Shop  https //stza.co/+xEWP-2f

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Giants vs. Storm
END:VALARM
DTSTART:20180425T183000Z
DTEND:20180425T213000Z
UID:zeDKzO9WuUuXzYd3zzD5meN8@stanza.co
SUMMARY:Giants vs. Storm
DESCRIPTION:Giants vs. Storm\n\nFollow on MiLB First Pitch: https://stza.co/+xEWP-3H\n\nShop: https://stza.co/+xEWP-2f\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144557Z
LAST-MODIFIED:20180213T144557Z
TRANSP:OPAQUE
END:VEVENT
* Giants @ Nuts
<2018-04-27 Fri 21:05>--<2018-04-28 Sat 00:05>
:PROPERTIES:
:ID:       5a0wfsINnGVb-5vM2JQ6ChQg@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Giants @ Nuts Giants @ Nuts

Follow on MiLB First Pitch  https //stza.co/+xz$3-3J

Shop  https //stza.co/+xz$3-P

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Giants @ Nuts
END:VALARM
DTSTART:20180428T020500Z
DTEND:20180428T050500Z
UID:5a0wfsINnGVb-5vM2JQ6ChQg@stanza.co
SUMMARY:Giants @ Nuts
DESCRIPTION:Giants @ Nuts\n\nFollow on MiLB First Pitch: https://stza.co/+xz$3-3J\n\nShop: https://stza.co/+xz$3-P\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144557Z
LAST-MODIFIED:20180213T144557Z
TRANSP:OPAQUE
END:VEVENT
* Giants @ Nuts
<2018-04-28 Sat 21:05>--<2018-04-29 Sun 00:05>
:PROPERTIES:
:ID:       xHDSeG9klCUoea3trfGAMpKo@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Giants @ Nuts Giants @ Nuts

Follow on MiLB First Pitch  https //stza.co/+xz$6-3y

Shop  https //stza.co/+xz$6-W

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Giants @ Nuts
END:VALARM
DTSTART:20180429T020500Z
DTEND:20180429T050500Z
UID:xHDSeG9klCUoea3trfGAMpKo@stanza.co
SUMMARY:Giants @ Nuts
DESCRIPTION:Giants @ Nuts\n\nFollow on MiLB First Pitch: https://stza.co/+xz$6-3y\n\nShop: https://stza.co/+xz$6-W\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144557Z
LAST-MODIFIED:20180213T144557Z
TRANSP:OPAQUE
END:VEVENT
* Giants @ Nuts
<2018-04-29 Sun 16:05-19:05>
:PROPERTIES:
:ID:       7enm6rcGIzpcLD7sAR_PspML@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Giants @ Nuts Giants @ Nuts

Follow on MiLB First Pitch  https //stza.co/+xz$9-A

Shop  https //stza.co/+xz$9-1u

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Giants @ Nuts
END:VALARM
DTSTART:20180429T210500Z
DTEND:20180430T000500Z
UID:7enm6rcGIzpcLD7sAR_PspML@stanza.co
SUMMARY:Giants @ Nuts
DESCRIPTION:Giants @ Nuts\n\nFollow on MiLB First Pitch: https://stza.co/+xz$9-A\n\nShop: https://stza.co/+xz$9-1u\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144557Z
LAST-MODIFIED:20180213T144557Z
TRANSP:OPAQUE
END:VEVENT
* Giants vs. Rawhide
<2018-04-30 Mon 20:30-23:30>
:PROPERTIES:
:ID:       ABgyDfCM3L7I228WHqonvhGN@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Giants vs. Rawhide Giants vs. Rawhide

Follow on MiLB First Pitch  https //stza.co/+xEWS-1B

Shop  https //stza.co/+xEWS-27

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Giants vs. Rawhide
END:VALARM
DTSTART:20180501T013000Z
DTEND:20180501T043000Z
UID:ABgyDfCM3L7I228WHqonvhGN@stanza.co
SUMMARY:Giants vs. Rawhide
DESCRIPTION:Giants vs. Rawhide\n\nFollow on MiLB First Pitch: https://stza.co/+xEWS-1B\n\nShop: https://stza.co/+xEWS-27\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144557Z
LAST-MODIFIED:20180213T144557Z
TRANSP:OPAQUE
END:VEVENT
* Giants vs. Rawhide
<2018-05-01 Tue 20:30-23:30>
:PROPERTIES:
:ID:       8tZQD9-2nYyrluAqLn-HcWIm@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Giants vs. Rawhide Giants vs. Rawhide

Follow on MiLB First Pitch  https //stza.co/+xEWT-Z

Shop  https //stza.co/+xEWT-2K

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Giants vs. Rawhide
END:VALARM
DTSTART:20180502T013000Z
DTEND:20180502T043000Z
UID:8tZQD9-2nYyrluAqLn-HcWIm@stanza.co
SUMMARY:Giants vs. Rawhide
DESCRIPTION:Giants vs. Rawhide\n\nFollow on MiLB First Pitch: https://stza.co/+xEWT-Z\n\nShop: https://stza.co/+xEWT-2K\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144557Z
LAST-MODIFIED:20180213T144557Z
TRANSP:OPAQUE
END:VEVENT
* Giants vs. Rawhide
<2018-05-02 Wed 20:30-23:30>
:PROPERTIES:
:ID:       AbBlqcL_dBagB8a3DzDOKqlR@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Giants vs. Rawhide Giants vs. Rawhide

Follow on MiLB First Pitch  https //stza.co/+xEWV-Y

Shop  https //stza.co/+xEWV-3O

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Giants vs. Rawhide
END:VALARM
DTSTART:20180503T013000Z
DTEND:20180503T043000Z
UID:AbBlqcL_dBagB8a3DzDOKqlR@stanza.co
SUMMARY:Giants vs. Rawhide
DESCRIPTION:Giants vs. Rawhide\n\nFollow on MiLB First Pitch: https://stza.co/+xEWV-Y\n\nShop: https://stza.co/+xEWV-3O\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144557Z
LAST-MODIFIED:20180213T144557Z
TRANSP:OPAQUE
END:VEVENT
* Giants vs. Rawhide
<2018-05-03 Thu 14:30-17:30>
:PROPERTIES:
:ID:       wwioYk5xURGsUFfIKM_li5VB@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Giants vs. Rawhide Giants vs. Rawhide

Follow on MiLB First Pitch  https //stza.co/+xEWY-4

Shop  https //stza.co/+xEWY-3h

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Giants vs. Rawhide
END:VALARM
DTSTART:20180503T193000Z
DTEND:20180503T223000Z
UID:wwioYk5xURGsUFfIKM_li5VB@stanza.co
SUMMARY:Giants vs. Rawhide
DESCRIPTION:Giants vs. Rawhide\n\nFollow on MiLB First Pitch: https://stza.co/+xEWY-4\n\nShop: https://stza.co/+xEWY-3h\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144557Z
LAST-MODIFIED:20180213T144557Z
TRANSP:OPAQUE
END:VEVENT
* Giants @ JetHawks
<2018-05-04 Fri 20:35-23:35>
:PROPERTIES:
:ID:       X1sMZvjHuMzXLyntBgBc5AlZ@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Giants @ JetHawks Giants @ JetHawks

Follow on MiLB First Pitch  https //stza.co/+vfce-

Shop  https //stza.co/+vfce-3S

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Giants @ JetHawks
END:VALARM
DTSTART:20180505T013500Z
DTEND:20180505T043500Z
UID:X1sMZvjHuMzXLyntBgBc5AlZ@stanza.co
SUMMARY:Giants @ JetHawks
DESCRIPTION:Giants @ JetHawks\n\nFollow on MiLB First Pitch: https://stza.co/+vfce-\n\nShop: https://stza.co/+vfce-3S\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144557Z
LAST-MODIFIED:20180213T144557Z
TRANSP:OPAQUE
END:VEVENT
* Giants @ JetHawks
<2018-05-05 Sat 20:05-23:05>
:PROPERTIES:
:ID:       L8v8Z5dYuuyJi1oON_KGiD-2@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Giants @ JetHawks Giants @ JetHawks

Follow on MiLB First Pitch  https //stza.co/+vfcp-y

Shop  https //stza.co/+vfcp-C

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Giants @ JetHawks
END:VALARM
DTSTART:20180506T010500Z
DTEND:20180506T040500Z
UID:L8v8Z5dYuuyJi1oON_KGiD-2@stanza.co
SUMMARY:Giants @ JetHawks
DESCRIPTION:Giants @ JetHawks\n\nFollow on MiLB First Pitch: https://stza.co/+vfcp-y\n\nShop: https://stza.co/+vfcp-C\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144557Z
LAST-MODIFIED:20180213T144557Z
TRANSP:OPAQUE
END:VEVENT
* Giants @ JetHawks
<2018-05-06 Sun>--<2018-05-05 Sat>
:PROPERTIES:
:ID:       3u-HY5VxJwdyOo68AwylrYue@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Giants @ JetHawks Giants @ JetHawks

Follow on MiLB First Pitch  https //stza.co/+vfcs-1M

Shop  https //stza.co/+vfcs-3p

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Giants @ JetHawks
END:VALARM
DTSTART;VALUE=DATE:20180506
DTEND;VALUE=DATE:20180506
UID:3u-HY5VxJwdyOo68AwylrYue@stanza.co
SUMMARY:Giants @ JetHawks
DESCRIPTION:Giants @ JetHawks\n\nFollow on MiLB First Pitch: https://stza.co/+vfcs-1M\n\nShop: https://stza.co/+vfcs-3p\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144557Z
LAST-MODIFIED:20180213T144557Z
TRANSP:OPAQUE
END:VEVENT
* Giants @ Nuts
<2018-05-08 Tue 21:05>--<2018-05-09 Wed 00:05>
:PROPERTIES:
:ID:       MweIGKzUbfiApq3gHgk7Q8yi@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Giants @ Nuts Giants @ Nuts

Follow on MiLB First Pitch  https //stza.co/+xz$U-1c

Shop  https //stza.co/+xz$U-2f

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Giants @ Nuts
END:VALARM
DTSTART:20180509T020500Z
DTEND:20180509T050500Z
UID:MweIGKzUbfiApq3gHgk7Q8yi@stanza.co
SUMMARY:Giants @ Nuts
DESCRIPTION:Giants @ Nuts\n\nFollow on MiLB First Pitch: https://stza.co/+xz$U-1c\n\nShop: https://stza.co/+xz$U-2f\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144557Z
LAST-MODIFIED:20180213T144557Z
TRANSP:OPAQUE
END:VEVENT
* Giants @ Nuts
<2018-05-09 Wed 18:05-21:05>
:PROPERTIES:
:ID:       o-LAjqWQi6gmKVdbYqVWnCsl@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Giants @ Nuts Giants @ Nuts

Follow on MiLB First Pitch  https //stza.co/+xz$X-3a

Shop  https //stza.co/+xz$X-r

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Giants @ Nuts
END:VALARM
DTSTART:20180509T230500Z
DTEND:20180510T020500Z
UID:o-LAjqWQi6gmKVdbYqVWnCsl@stanza.co
SUMMARY:Giants @ Nuts
DESCRIPTION:Giants @ Nuts\n\nFollow on MiLB First Pitch: https://stza.co/+xz$X-3a\n\nShop: https://stza.co/+xz$X-r\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144557Z
LAST-MODIFIED:20180213T144557Z
TRANSP:OPAQUE
END:VEVENT
* Giants @ Nuts
<2018-05-10 Thu 21:05>--<2018-05-11 Fri 00:05>
:PROPERTIES:
:ID:       Izq3zl_ht_Y8wmE6kZh78wRq@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Giants @ Nuts Giants @ Nuts

Follow on MiLB First Pitch  https //stza.co/+xz$_-2f

Shop  https //stza.co/+xz$_-2Y

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Giants @ Nuts
END:VALARM
DTSTART:20180511T020500Z
DTEND:20180511T050500Z
UID:Izq3zl_ht_Y8wmE6kZh78wRq@stanza.co
SUMMARY:Giants @ Nuts
DESCRIPTION:Giants @ Nuts\n\nFollow on MiLB First Pitch: https://stza.co/+xz$_-2f\n\nShop: https://stza.co/+xz$_-2Y\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144557Z
LAST-MODIFIED:20180213T144557Z
TRANSP:OPAQUE
END:VEVENT
* Giants vs. JetHawks
<2018-05-11 Fri 21:00>--<2018-05-12 Sat 00:00>
:PROPERTIES:
:ID:       y-meUrwCM6ads0v81biiQZhe@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Giants vs. JetHawks Giants vs. JetHawks

Follow on MiLB First Pitch  https //stza.co/+xEW_-36

Shop  https //stza.co/+xEW_-28

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Giants vs. JetHawks
END:VALARM
DTSTART:20180512T020000Z
DTEND:20180512T050000Z
UID:y-meUrwCM6ads0v81biiQZhe@stanza.co
SUMMARY:Giants vs. JetHawks
DESCRIPTION:Giants vs. JetHawks\n\nFollow on MiLB First Pitch: https://stza.co/+xEW_-36\n\nShop: https://stza.co/+xEW_-28\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144557Z
LAST-MODIFIED:20180213T144557Z
TRANSP:OPAQUE
END:VEVENT
* Giants vs. JetHawks
<2018-05-12 Sat 19:00-22:00>
:PROPERTIES:
:ID:       InaBD0_CD3bkFwm0FaOSFxts@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Giants vs. JetHawks Giants vs. JetHawks

Follow on MiLB First Pitch  https //stza.co/+xEW$-3p

Shop  https //stza.co/+xEW$-T

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Giants vs. JetHawks
END:VALARM
DTSTART:20180513T000000Z
DTEND:20180513T030000Z
UID:InaBD0_CD3bkFwm0FaOSFxts@stanza.co
SUMMARY:Giants vs. JetHawks
DESCRIPTION:Giants vs. JetHawks\n\nFollow on MiLB First Pitch: https://stza.co/+xEW$-3p\n\nShop: https://stza.co/+xEW$-T\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144557Z
LAST-MODIFIED:20180213T144557Z
TRANSP:OPAQUE
END:VEVENT
* Giants vs. JetHawks
<2018-05-13 Sun 15:00-18:00>
:PROPERTIES:
:ID:       3UGJhjIi5lWaYkQAZKf-zPEy@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Giants vs. JetHawks Giants vs. JetHawks

Follow on MiLB First Pitch  https //stza.co/+xEX2-9

Shop  https //stza.co/+xEX2-3Q

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Giants vs. JetHawks
END:VALARM
DTSTART:20180513T200000Z
DTEND:20180513T230000Z
UID:3UGJhjIi5lWaYkQAZKf-zPEy@stanza.co
SUMMARY:Giants vs. JetHawks
DESCRIPTION:Giants vs. JetHawks\n\nFollow on MiLB First Pitch: https://stza.co/+xEX2-9\n\nShop: https://stza.co/+xEX2-3Q\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144557Z
LAST-MODIFIED:20180213T144557Z
TRANSP:OPAQUE
END:VEVENT
* Giants vs. JetHawks
<2018-05-14 Mon 20:30-23:30>
:PROPERTIES:
:ID:       g0Ihj5Yv9e3UrMF6OVtmBzBF@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Giants vs. JetHawks Giants vs. JetHawks

Follow on MiLB First Pitch  https //stza.co/+xEX3-1S

Shop  https //stza.co/+xEX3-3w

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Giants vs. JetHawks
END:VALARM
DTSTART:20180515T013000Z
DTEND:20180515T043000Z
UID:g0Ihj5Yv9e3UrMF6OVtmBzBF@stanza.co
SUMMARY:Giants vs. JetHawks
DESCRIPTION:Giants vs. JetHawks\n\nFollow on MiLB First Pitch: https://stza.co/+xEX3-1S\n\nShop: https://stza.co/+xEX3-3w\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144557Z
LAST-MODIFIED:20180213T144557Z
TRANSP:OPAQUE
END:VEVENT
* Giants vs. Nuts
<2018-05-15 Tue 20:30-23:30>
:PROPERTIES:
:ID:       yQiN7mS5Fod3aPbFG9v6p8HT@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Giants vs. Nuts Giants vs. Nuts

Follow on MiLB First Pitch  https //stza.co/+xEWp-x

Shop  https //stza.co/+xEWp-30

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Giants vs. Nuts
END:VALARM
DTSTART:20180516T013000Z
DTEND:20180516T043000Z
UID:yQiN7mS5Fod3aPbFG9v6p8HT@stanza.co
SUMMARY:Giants vs. Nuts
DESCRIPTION:Giants vs. Nuts\n\nFollow on MiLB First Pitch: https://stza.co/+xEWp-x\n\nShop: https://stza.co/+xEWp-30\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144557Z
LAST-MODIFIED:20180213T144557Z
TRANSP:OPAQUE
END:VEVENT
* Giants vs. Nuts
<2018-05-16 Wed 20:30-23:30>
:PROPERTIES:
:ID:       1ZW6EwJSuAaFWp0WndO1tYzd@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Giants vs. Nuts Giants vs. Nuts

Follow on MiLB First Pitch  https //stza.co/+xEWs-$

Shop  https //stza.co/+xEWs-t

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Giants vs. Nuts
END:VALARM
DTSTART:20180517T013000Z
DTEND:20180517T043000Z
UID:1ZW6EwJSuAaFWp0WndO1tYzd@stanza.co
SUMMARY:Giants vs. Nuts
DESCRIPTION:Giants vs. Nuts\n\nFollow on MiLB First Pitch: https://stza.co/+xEWs-$\n\nShop: https://stza.co/+xEWs-t\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144557Z
LAST-MODIFIED:20180213T144557Z
TRANSP:OPAQUE
END:VEVENT
* Giants vs. Nuts
<2018-05-17 Thu 13:30-16:30>
:PROPERTIES:
:ID:       wX1JnqcFbyM8owxf3uiCanft@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Giants vs. Nuts Giants vs. Nuts

Follow on MiLB First Pitch  https //stza.co/+xEWt-d

Shop  https //stza.co/+xEWt-1u

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Giants vs. Nuts
END:VALARM
DTSTART:20180517T183000Z
DTEND:20180517T213000Z
UID:wX1JnqcFbyM8owxf3uiCanft@stanza.co
SUMMARY:Giants vs. Nuts
DESCRIPTION:Giants vs. Nuts\n\nFollow on MiLB First Pitch: https://stza.co/+xEWt-d\n\nShop: https://stza.co/+xEWt-1u\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144557Z
LAST-MODIFIED:20180213T144557Z
TRANSP:OPAQUE
END:VEVENT
* Giants @ Ports
<2018-05-18 Fri 21:10>--<2018-05-19 Sat 00:10>
:PROPERTIES:
:ID:       PEmWuVlsfs4hSottwG_7Qii5@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Giants @ Ports Giants @ Ports

Follow on MiLB First Pitch  https //stza.co/+vM1A-3k

Shop  https //stza.co/+vM1A-n

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Giants @ Ports
END:VALARM
DTSTART:20180519T021000Z
DTEND:20180519T051000Z
UID:PEmWuVlsfs4hSottwG_7Qii5@stanza.co
SUMMARY:Giants @ Ports
DESCRIPTION:Giants @ Ports\n\nFollow on MiLB First Pitch: https://stza.co/+vM1A-3k\n\nShop: https://stza.co/+vM1A-n\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144557Z
LAST-MODIFIED:20180213T144557Z
TRANSP:OPAQUE
END:VEVENT
* Giants @ Ports
<2018-05-19 Sat 21:10>--<2018-05-20 Sun 00:10>
:PROPERTIES:
:ID:       0QaYXFJTZVFoqKsLn6NNKFUL@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Giants @ Ports Giants @ Ports

Follow on MiLB First Pitch  https //stza.co/+vM1B-K

Shop  https //stza.co/+vM1B-1d

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Giants @ Ports
END:VALARM
DTSTART:20180520T021000Z
DTEND:20180520T051000Z
UID:0QaYXFJTZVFoqKsLn6NNKFUL@stanza.co
SUMMARY:Giants @ Ports
DESCRIPTION:Giants @ Ports\n\nFollow on MiLB First Pitch: https://stza.co/+vM1B-K\n\nShop: https://stza.co/+vM1B-1d\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144557Z
LAST-MODIFIED:20180213T144557Z
TRANSP:OPAQUE
END:VEVENT
* Giants @ Ports
<2018-05-20 Sun 16:09-19:09>
:PROPERTIES:
:ID:       gjmsOv5O_dkxvZBjunO5vM9E@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Giants @ Ports Giants @ Ports

Follow on MiLB First Pitch  https //stza.co/+vM1C-38

Shop  https //stza.co/+vM1C-3_

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Giants @ Ports
END:VALARM
DTSTART:20180520T210900Z
DTEND:20180521T000900Z
UID:gjmsOv5O_dkxvZBjunO5vM9E@stanza.co
SUMMARY:Giants @ Ports
DESCRIPTION:Giants @ Ports\n\nFollow on MiLB First Pitch: https://stza.co/+vM1C-38\n\nShop: https://stza.co/+vM1C-3_\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144557Z
LAST-MODIFIED:20180213T144557Z
TRANSP:OPAQUE
END:VEVENT
* Giants @ Nuts
<2018-05-22 Tue 21:05>--<2018-05-23 Wed 00:05>
:PROPERTIES:
:ID:       -TLPHu87ZqVa-xoKfucFdcai@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Giants @ Nuts Giants @ Nuts

Follow on MiLB First Pitch  https //stza.co/+xz$d-b

Shop  https //stza.co/+xz$d-1b

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Giants @ Nuts
END:VALARM
DTSTART:20180523T020500Z
DTEND:20180523T050500Z
UID:-TLPHu87ZqVa-xoKfucFdcai@stanza.co
SUMMARY:Giants @ Nuts
DESCRIPTION:Giants @ Nuts\n\nFollow on MiLB First Pitch: https://stza.co/+xz$d-b\n\nShop: https://stza.co/+xz$d-1b\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144557Z
LAST-MODIFIED:20180213T144557Z
TRANSP:OPAQUE
END:VEVENT
* Giants @ Nuts
<2018-05-23 Wed 21:05>--<2018-05-24 Thu 00:05>
:PROPERTIES:
:ID:       vK_28tRULtCvI1KKUQTteK5r@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Giants @ Nuts Giants @ Nuts

Follow on MiLB First Pitch  https //stza.co/+xz$g-B

Shop  https //stza.co/+xz$g-g

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Giants @ Nuts
END:VALARM
DTSTART:20180524T020500Z
DTEND:20180524T050500Z
UID:vK_28tRULtCvI1KKUQTteK5r@stanza.co
SUMMARY:Giants @ Nuts
DESCRIPTION:Giants @ Nuts\n\nFollow on MiLB First Pitch: https://stza.co/+xz$g-B\n\nShop: https://stza.co/+xz$g-g\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144557Z
LAST-MODIFIED:20180213T144557Z
TRANSP:OPAQUE
END:VEVENT
* Giants @ Nuts
<2018-05-24 Thu 21:05>--<2018-05-25 Fri 00:05>
:PROPERTIES:
:ID:       nYq10ye0GoOzQMgX2VLzL1h7@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Giants @ Nuts Giants @ Nuts

Follow on MiLB First Pitch  https //stza.co/+xz$j-2k

Shop  https //stza.co/+xz$j-11

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Giants @ Nuts
END:VALARM
DTSTART:20180525T020500Z
DTEND:20180525T050500Z
UID:nYq10ye0GoOzQMgX2VLzL1h7@stanza.co
SUMMARY:Giants @ Nuts
DESCRIPTION:Giants @ Nuts\n\nFollow on MiLB First Pitch: https://stza.co/+xz$j-2k\n\nShop: https://stza.co/+xz$j-11\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144557Z
LAST-MODIFIED:20180213T144557Z
TRANSP:OPAQUE
END:VEVENT
* Giants @ Storm
<2018-05-25 Fri 21:00>--<2018-05-26 Sat 00:00>
:PROPERTIES:
:ID:       QL8JdIoNYqb37M8S5lCQVf35@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Giants @ Storm Giants @ Storm

Follow on MiLB First Pitch  https //stza.co/+xz_Y-u

Shop  https //stza.co/+xz_Y-3p

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Giants @ Storm
END:VALARM
DTSTART:20180526T020000Z
DTEND:20180526T050000Z
UID:QL8JdIoNYqb37M8S5lCQVf35@stanza.co
SUMMARY:Giants @ Storm
DESCRIPTION:Giants @ Storm\n\nFollow on MiLB First Pitch: https://stza.co/+xz_Y-u\n\nShop: https://stza.co/+xz_Y-3p\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144557Z
LAST-MODIFIED:20180213T144557Z
TRANSP:OPAQUE
END:VEVENT
* Giants @ Storm
<2018-05-26 Sat 20:00-23:00>
:PROPERTIES:
:ID:       qqTyN9JVt5pKitJcGiVbNYFG@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Giants @ Storm Giants @ Storm

Follow on MiLB First Pitch  https //stza.co/+xz_Z-2Y

Shop  https //stza.co/+xz_Z-1h

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Giants @ Storm
END:VALARM
DTSTART:20180527T010000Z
DTEND:20180527T040000Z
UID:qqTyN9JVt5pKitJcGiVbNYFG@stanza.co
SUMMARY:Giants @ Storm
DESCRIPTION:Giants @ Storm\n\nFollow on MiLB First Pitch: https://stza.co/+xz_Z-2Y\n\nShop: https://stza.co/+xz_Z-1h\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144557Z
LAST-MODIFIED:20180213T144557Z
TRANSP:OPAQUE
END:VEVENT
* Giants @ Storm
<2018-05-27 Sun>--<2018-05-26 Sat>
:PROPERTIES:
:ID:       HZkZZ5P5ox_SGCB-Ziqf_Pd4@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Giants @ Storm Giants @ Storm

Follow on MiLB First Pitch  https //stza.co/+vfbj-m

Shop  https //stza.co/+vfbj-1J

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Giants @ Storm
END:VALARM
DTSTART;VALUE=DATE:20180527
DTEND;VALUE=DATE:20180527
UID:HZkZZ5P5ox_SGCB-Ziqf_Pd4@stanza.co
SUMMARY:Giants @ Storm
DESCRIPTION:Giants @ Storm\n\nFollow on MiLB First Pitch: https://stza.co/+vfbj-m\n\nShop: https://stza.co/+vfbj-1J\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144557Z
LAST-MODIFIED:20180213T144557Z
TRANSP:OPAQUE
END:VEVENT
* Giants vs. Rawhide
<2018-05-28 Mon 19:00-22:00>
:PROPERTIES:
:ID:       rlk-EPobsELuReypCNNJnwQa@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Giants vs. Rawhide Giants vs. Rawhide

Follow on MiLB First Pitch  https //stza.co/+xEX6-O

Shop  https //stza.co/+xEX6-W

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Giants vs. Rawhide
END:VALARM
DTSTART:20180529T000000Z
DTEND:20180529T030000Z
UID:rlk-EPobsELuReypCNNJnwQa@stanza.co
SUMMARY:Giants vs. Rawhide
DESCRIPTION:Giants vs. Rawhide\n\nFollow on MiLB First Pitch: https://stza.co/+xEX6-O\n\nShop: https://stza.co/+xEX6-W\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144557Z
LAST-MODIFIED:20180213T144557Z
TRANSP:OPAQUE
END:VEVENT
* Giants vs. Rawhide
<2018-05-29 Tue 20:30-23:30>
:PROPERTIES:
:ID:       AWnnu5HdUjfS5x9ToSf8YntO@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Giants vs. Rawhide Giants vs. Rawhide

Follow on MiLB First Pitch  https //stza.co/+xEX8-3O

Shop  https //stza.co/+xEX8-i

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Giants vs. Rawhide
END:VALARM
DTSTART:20180530T013000Z
DTEND:20180530T043000Z
UID:AWnnu5HdUjfS5x9ToSf8YntO@stanza.co
SUMMARY:Giants vs. Rawhide
DESCRIPTION:Giants vs. Rawhide\n\nFollow on MiLB First Pitch: https://stza.co/+xEX8-3O\n\nShop: https://stza.co/+xEX8-i\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144557Z
LAST-MODIFIED:20180213T144557Z
TRANSP:OPAQUE
END:VEVENT
* Giants vs. Rawhide
<2018-05-30 Wed 20:30-23:30>
:PROPERTIES:
:ID:       nKJN7NlXwiF0zOwYOvBk-xC2@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Giants vs. Rawhide Giants vs. Rawhide

Follow on MiLB First Pitch  https //stza.co/+xEXa-1r

Shop  https //stza.co/+xEXa-1O

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Giants vs. Rawhide
END:VALARM
DTSTART:20180531T013000Z
DTEND:20180531T043000Z
UID:nKJN7NlXwiF0zOwYOvBk-xC2@stanza.co
SUMMARY:Giants vs. Rawhide
DESCRIPTION:Giants vs. Rawhide\n\nFollow on MiLB First Pitch: https://stza.co/+xEXa-1r\n\nShop: https://stza.co/+xEXa-1O\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144557Z
LAST-MODIFIED:20180213T144557Z
TRANSP:OPAQUE
END:VEVENT
* Giants vs. Rawhide
<2018-05-31 Thu 21:00>--<2018-06-01 Fri 00:00>
:PROPERTIES:
:ID:       g0MxXaF5aFBk3xBAA7kjjcya@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Giants vs. Rawhide Giants vs. Rawhide

Follow on MiLB First Pitch  https //stza.co/+xEXc-2r

Shop  https //stza.co/+xEXc-2B

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Giants vs. Rawhide
END:VALARM
DTSTART:20180601T020000Z
DTEND:20180601T050000Z
UID:g0MxXaF5aFBk3xBAA7kjjcya@stanza.co
SUMMARY:Giants vs. Rawhide
DESCRIPTION:Giants vs. Rawhide\n\nFollow on MiLB First Pitch: https://stza.co/+xEXc-2r\n\nShop: https://stza.co/+xEXc-2B\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144557Z
LAST-MODIFIED:20180213T144557Z
TRANSP:OPAQUE
END:VEVENT
* Giants vs. Nuts
<2018-06-01 Fri 21:00>--<2018-06-02 Sat 00:00>
:PROPERTIES:
:ID:       t0iOQFrcIfh_DA4k_Nhryp2n@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Giants vs. Nuts Giants vs. Nuts

Follow on MiLB First Pitch  https //stza.co/+xEXe-1B

Shop  https //stza.co/+xEXe-2Z

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Giants vs. Nuts
END:VALARM
DTSTART:20180602T020000Z
DTEND:20180602T050000Z
UID:t0iOQFrcIfh_DA4k_Nhryp2n@stanza.co
SUMMARY:Giants vs. Nuts
DESCRIPTION:Giants vs. Nuts\n\nFollow on MiLB First Pitch: https://stza.co/+xEXe-1B\n\nShop: https://stza.co/+xEXe-2Z\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144557Z
LAST-MODIFIED:20180213T144557Z
TRANSP:OPAQUE
END:VEVENT
* Giants vs. Nuts
<2018-06-02 Sat 20:00-23:00>
:PROPERTIES:
:ID:       kg09giAnKOD2HabTLQ0a8sPq@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Giants vs. Nuts Giants vs. Nuts

Follow on MiLB First Pitch  https //stza.co/+xKKJ-y

Shop  https //stza.co/+xKKJ-1m

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Giants vs. Nuts
END:VALARM
DTSTART:20180603T010000Z
DTEND:20180603T040000Z
UID:kg09giAnKOD2HabTLQ0a8sPq@stanza.co
SUMMARY:Giants vs. Nuts
DESCRIPTION:Giants vs. Nuts\n\nFollow on MiLB First Pitch: https://stza.co/+xKKJ-y\n\nShop: https://stza.co/+xKKJ-1m\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144557Z
LAST-MODIFIED:20180213T144557Z
TRANSP:OPAQUE
END:VEVENT
* Giants vs. Nuts
<2018-06-03 Sun 15:00-18:00>
:PROPERTIES:
:ID:       IM9-bzxwJlGodU8_F-kjMzdA@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Giants vs. Nuts Giants vs. Nuts

Follow on MiLB First Pitch  https //stza.co/+xEXi-2E

Shop  https //stza.co/+xEXi-1Q

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Giants vs. Nuts
END:VALARM
DTSTART:20180603T200000Z
DTEND:20180603T230000Z
UID:IM9-bzxwJlGodU8_F-kjMzdA@stanza.co
SUMMARY:Giants vs. Nuts
DESCRIPTION:Giants vs. Nuts\n\nFollow on MiLB First Pitch: https://stza.co/+xEXi-2E\n\nShop: https://stza.co/+xEXi-1Q\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144557Z
LAST-MODIFIED:20180213T144557Z
TRANSP:OPAQUE
END:VEVENT
* Giants vs. Ports
<2018-06-05 Tue 20:30-23:30>
:PROPERTIES:
:ID:       U5LHZ6dEWdHzhywe6TEkPO34@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Giants vs. Ports Giants vs. Ports

Follow on MiLB First Pitch  https //stza.co/+xEXk-2l

Shop  https //stza.co/+xEXk-26

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Giants vs. Ports
END:VALARM
DTSTART:20180606T013000Z
DTEND:20180606T043000Z
UID:U5LHZ6dEWdHzhywe6TEkPO34@stanza.co
SUMMARY:Giants vs. Ports
DESCRIPTION:Giants vs. Ports\n\nFollow on MiLB First Pitch: https://stza.co/+xEXk-2l\n\nShop: https://stza.co/+xEXk-26\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144557Z
LAST-MODIFIED:20180213T144557Z
TRANSP:OPAQUE
END:VEVENT
* Giants vs. Ports
<2018-06-06 Wed 20:30-23:30>
:PROPERTIES:
:ID:       b9TfhXYn7aLTWLdMTDpZ1OQf@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Giants vs. Ports Giants vs. Ports

Follow on MiLB First Pitch  https //stza.co/+xEXl-3H

Shop  https //stza.co/+xEXl-3s

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Giants vs. Ports
END:VALARM
DTSTART:20180607T013000Z
DTEND:20180607T043000Z
UID:b9TfhXYn7aLTWLdMTDpZ1OQf@stanza.co
SUMMARY:Giants vs. Ports
DESCRIPTION:Giants vs. Ports\n\nFollow on MiLB First Pitch: https://stza.co/+xEXl-3H\n\nShop: https://stza.co/+xEXl-3s\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144557Z
LAST-MODIFIED:20180213T144557Z
TRANSP:OPAQUE
END:VEVENT
* Giants vs. Ports
<2018-06-07 Thu 14:30-17:30>
:PROPERTIES:
:ID:       mPOrEAwZpAcPywUwmg9ARDZN@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Giants vs. Ports Giants vs. Ports

Follow on MiLB First Pitch  https //stza.co/+xEXn-6

Shop  https //stza.co/+xEXn-2B

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Giants vs. Ports
END:VALARM
DTSTART:20180607T193000Z
DTEND:20180607T223000Z
UID:mPOrEAwZpAcPywUwmg9ARDZN@stanza.co
SUMMARY:Giants vs. Ports
DESCRIPTION:Giants vs. Ports\n\nFollow on MiLB First Pitch: https://stza.co/+xEXn-6\n\nShop: https://stza.co/+xEXn-2B\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144557Z
LAST-MODIFIED:20180213T144557Z
TRANSP:OPAQUE
END:VEVENT
* Giants @ Nuts
<2018-06-08 Fri 21:05>--<2018-06-09 Sat 00:05>
:PROPERTIES:
:ID:       _pRHjh7RJj6UlmqQldn-k-BT@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Giants @ Nuts Giants @ Nuts

Follow on MiLB First Pitch  https //stza.co/+xz$o-7

Shop  https //stza.co/+xz$o-

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Giants @ Nuts
END:VALARM
DTSTART:20180609T020500Z
DTEND:20180609T050500Z
UID:_pRHjh7RJj6UlmqQldn-k-BT@stanza.co
SUMMARY:Giants @ Nuts
DESCRIPTION:Giants @ Nuts\n\nFollow on MiLB First Pitch: https://stza.co/+xz$o-7\n\nShop: https://stza.co/+xz$o-\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144557Z
LAST-MODIFIED:20180213T144557Z
TRANSP:OPAQUE
END:VEVENT
* Giants @ Nuts
<2018-06-09 Sat 21:05>--<2018-06-10 Sun 00:05>
:PROPERTIES:
:ID:       6_37VpPNvcdhDSxvLYrfKMDH@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Giants @ Nuts Giants @ Nuts

Follow on MiLB First Pitch  https //stza.co/+xz$r-3z

Shop  https //stza.co/+xz$r-h

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Giants @ Nuts
END:VALARM
DTSTART:20180610T020500Z
DTEND:20180610T050500Z
UID:6_37VpPNvcdhDSxvLYrfKMDH@stanza.co
SUMMARY:Giants @ Nuts
DESCRIPTION:Giants @ Nuts\n\nFollow on MiLB First Pitch: https://stza.co/+xz$r-3z\n\nShop: https://stza.co/+xz$r-h\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144557Z
LAST-MODIFIED:20180213T144557Z
TRANSP:OPAQUE
END:VEVENT
* Giants @ Nuts
<2018-06-10 Sun 16:05-19:05>
:PROPERTIES:
:ID:       Pv1mi1loOfinyhX6ih5GiLpZ@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Giants @ Nuts Giants @ Nuts

Follow on MiLB First Pitch  https //stza.co/+xz$u-1h

Shop  https //stza.co/+xz$u-x

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Giants @ Nuts
END:VALARM
DTSTART:20180610T210500Z
DTEND:20180611T000500Z
UID:Pv1mi1loOfinyhX6ih5GiLpZ@stanza.co
SUMMARY:Giants @ Nuts
DESCRIPTION:Giants @ Nuts\n\nFollow on MiLB First Pitch: https://stza.co/+xz$u-1h\n\nShop: https://stza.co/+xz$u-x\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144557Z
LAST-MODIFIED:20180213T144557Z
TRANSP:OPAQUE
END:VEVENT
* Giants @ Ports
<2018-06-11 Mon 21:10>--<2018-06-12 Tue 00:10>
:PROPERTIES:
:ID:       -_Uc1u_aNM6hdUVZvzHjP6Uv@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Giants @ Ports Giants @ Ports

Follow on MiLB First Pitch  https //stza.co/+vM1D-2L

Shop  https //stza.co/+vM1D-3S

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Giants @ Ports
END:VALARM
DTSTART:20180612T021000Z
DTEND:20180612T051000Z
UID:-_Uc1u_aNM6hdUVZvzHjP6Uv@stanza.co
SUMMARY:Giants @ Ports
DESCRIPTION:Giants @ Ports\n\nFollow on MiLB First Pitch: https://stza.co/+vM1D-2L\n\nShop: https://stza.co/+vM1D-3S\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144557Z
LAST-MODIFIED:20180213T144557Z
TRANSP:OPAQUE
END:VEVENT
* Giants @ Ports
<2018-06-12 Tue 21:10>--<2018-06-13 Wed 00:10>
:PROPERTIES:
:ID:       VdFPe835F__RHgBK-1d4nu6s@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Giants @ Ports Giants @ Ports

Follow on MiLB First Pitch  https //stza.co/+vM1E-1b

Shop  https //stza.co/+vM1E-3a

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Giants @ Ports
END:VALARM
DTSTART:20180613T021000Z
DTEND:20180613T051000Z
UID:VdFPe835F__RHgBK-1d4nu6s@stanza.co
SUMMARY:Giants @ Ports
DESCRIPTION:Giants @ Ports\n\nFollow on MiLB First Pitch: https://stza.co/+vM1E-1b\n\nShop: https://stza.co/+vM1E-3a\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144557Z
LAST-MODIFIED:20180213T144557Z
TRANSP:OPAQUE
END:VEVENT
* Giants @ Ports
<2018-06-13 Wed 21:10>--<2018-06-14 Thu 00:10>
:PROPERTIES:
:ID:       Uqrn4K9nw3R-aGaorY1fJGx2@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Giants @ Ports Giants @ Ports

Follow on MiLB First Pitch  https //stza.co/+vM1F-3v

Shop  https //stza.co/+vM1F-T

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Giants @ Ports
END:VALARM
DTSTART:20180614T021000Z
DTEND:20180614T051000Z
UID:Uqrn4K9nw3R-aGaorY1fJGx2@stanza.co
SUMMARY:Giants @ Ports
DESCRIPTION:Giants @ Ports\n\nFollow on MiLB First Pitch: https://stza.co/+vM1F-3v\n\nShop: https://stza.co/+vM1F-T\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144557Z
LAST-MODIFIED:20180213T144557Z
TRANSP:OPAQUE
END:VEVENT
* Giants @ Ports
<2018-06-14 Thu 21:10>--<2018-06-15 Fri 00:10>
:PROPERTIES:
:ID:       5mJo3kgE3gOSIIQ3fdiFzP9M@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Giants @ Ports Giants @ Ports

Follow on MiLB First Pitch  https //stza.co/+vM1G-3

Shop  https //stza.co/+vM1G-2_

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Giants @ Ports
END:VALARM
DTSTART:20180615T021000Z
DTEND:20180615T051000Z
UID:5mJo3kgE3gOSIIQ3fdiFzP9M@stanza.co
SUMMARY:Giants @ Ports
DESCRIPTION:Giants @ Ports\n\nFollow on MiLB First Pitch: https://stza.co/+vM1G-3\n\nShop: https://stza.co/+vM1G-2_\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144557Z
LAST-MODIFIED:20180213T144557Z
TRANSP:OPAQUE
END:VEVENT
* Giants vs. Rawhide
<2018-06-15 Fri 21:00>--<2018-06-16 Sat 00:00>
:PROPERTIES:
:ID:       02F_N8ZRfPWyByoRpn3bNQNj@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Giants vs. Rawhide Giants vs. Rawhide

Follow on MiLB First Pitch  https //stza.co/+xEXq-7

Shop  https //stza.co/+xEXq-3t

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Giants vs. Rawhide
END:VALARM
DTSTART:20180616T020000Z
DTEND:20180616T050000Z
UID:02F_N8ZRfPWyByoRpn3bNQNj@stanza.co
SUMMARY:Giants vs. Rawhide
DESCRIPTION:Giants vs. Rawhide\n\nFollow on MiLB First Pitch: https://stza.co/+xEXq-7\n\nShop: https://stza.co/+xEXq-3t\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144557Z
LAST-MODIFIED:20180213T144557Z
TRANSP:OPAQUE
END:VEVENT
* Giants vs. Rawhide
<2018-06-16 Sat 19:00-22:00>
:PROPERTIES:
:ID:       OryjCNzr_GCByV9rdycZR7_L@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Giants vs. Rawhide Giants vs. Rawhide

Follow on MiLB First Pitch  https //stza.co/+xEXs-S

Shop  https //stza.co/+xEXs-29

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Giants vs. Rawhide
END:VALARM
DTSTART:20180617T000000Z
DTEND:20180617T030000Z
UID:OryjCNzr_GCByV9rdycZR7_L@stanza.co
SUMMARY:Giants vs. Rawhide
DESCRIPTION:Giants vs. Rawhide\n\nFollow on MiLB First Pitch: https://stza.co/+xEXs-S\n\nShop: https://stza.co/+xEXs-29\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144557Z
LAST-MODIFIED:20180213T144557Z
TRANSP:OPAQUE
END:VEVENT
* Giants vs. Rawhide
<2018-06-17 Sun 15:00-18:00>
:PROPERTIES:
:ID:       138QBFuYz-D9lfK5k6K22dTq@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Giants vs. Rawhide Giants vs. Rawhide

Follow on MiLB First Pitch  https //stza.co/+xEXt-X

Shop  https //stza.co/+xEXt-B

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Giants vs. Rawhide
END:VALARM
DTSTART:20180617T200000Z
DTEND:20180617T230000Z
UID:138QBFuYz-D9lfK5k6K22dTq@stanza.co
SUMMARY:Giants vs. Rawhide
DESCRIPTION:Giants vs. Rawhide\n\nFollow on MiLB First Pitch: https://stza.co/+xEXt-X\n\nShop: https://stza.co/+xEXt-B\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144557Z
LAST-MODIFIED:20180213T144557Z
TRANSP:OPAQUE
END:VEVENT
* Giants @ Quakes
<2018-06-21 Thu 21:05>--<2018-06-22 Fri 00:05>
:PROPERTIES:
:ID:       swQkbguxwDrNCri3mJnTCHYs@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Giants @ Quakes Giants @ Quakes

Follow on MiLB First Pitch  https //stza.co/+xz$J-2h

Shop  https //stza.co/+xz$J-2M

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Giants @ Quakes
END:VALARM
DTSTART:20180622T020500Z
DTEND:20180622T050500Z
UID:swQkbguxwDrNCri3mJnTCHYs@stanza.co
SUMMARY:Giants @ Quakes
DESCRIPTION:Giants @ Quakes\n\nFollow on MiLB First Pitch: https://stza.co/+xz$J-2h\n\nShop: https://stza.co/+xz$J-2M\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144557Z
LAST-MODIFIED:20180213T144557Z
TRANSP:OPAQUE
END:VEVENT
* Giants @ Quakes
<2018-06-22 Fri 21:05>--<2018-06-23 Sat 00:05>
:PROPERTIES:
:ID:       r9mpIjyuX9zy7c8q2s8Hbffs@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Giants @ Quakes Giants @ Quakes

Follow on MiLB First Pitch  https //stza.co/+xz$K-n

Shop  https //stza.co/+xz$K-13

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Giants @ Quakes
END:VALARM
DTSTART:20180623T020500Z
DTEND:20180623T050500Z
UID:r9mpIjyuX9zy7c8q2s8Hbffs@stanza.co
SUMMARY:Giants @ Quakes
DESCRIPTION:Giants @ Quakes\n\nFollow on MiLB First Pitch: https://stza.co/+xz$K-n\n\nShop: https://stza.co/+xz$K-13\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144557Z
LAST-MODIFIED:20180213T144557Z
TRANSP:OPAQUE
END:VEVENT
* Giants @ Quakes
<2018-06-23 Sat 21:05>--<2018-06-24 Sun 00:05>
:PROPERTIES:
:ID:       Gk4ERe3Zqwc3vGOR1t53PlDK@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Giants @ Quakes Giants @ Quakes

Follow on MiLB First Pitch  https //stza.co/+xz$N-3K

Shop  https //stza.co/+xz$N-18

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Giants @ Quakes
END:VALARM
DTSTART:20180624T020500Z
DTEND:20180624T050500Z
UID:Gk4ERe3Zqwc3vGOR1t53PlDK@stanza.co
SUMMARY:Giants @ Quakes
DESCRIPTION:Giants @ Quakes\n\nFollow on MiLB First Pitch: https://stza.co/+xz$N-3K\n\nShop: https://stza.co/+xz$N-18\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144557Z
LAST-MODIFIED:20180213T144557Z
TRANSP:OPAQUE
END:VEVENT
* Giants @ Quakes
<2018-06-24 Sun 16:05-19:05>
:PROPERTIES:
:ID:       YWUntmj9e2dLFllfuDwZcgYj@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Giants @ Quakes Giants @ Quakes

Follow on MiLB First Pitch  https //stza.co/+xz$O-1q

Shop  https //stza.co/+xz$O-2o

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Giants @ Quakes
END:VALARM
DTSTART:20180624T210500Z
DTEND:20180625T000500Z
UID:YWUntmj9e2dLFllfuDwZcgYj@stanza.co
SUMMARY:Giants @ Quakes
DESCRIPTION:Giants @ Quakes\n\nFollow on MiLB First Pitch: https://stza.co/+xz$O-1q\n\nShop: https://stza.co/+xz$O-2o\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144557Z
LAST-MODIFIED:20180213T144557Z
TRANSP:OPAQUE
END:VEVENT
* Giants vs. Ports
<2018-06-25 Mon 21:00>--<2018-06-26 Tue 00:00>
:PROPERTIES:
:ID:       XXBpEgSPU-nixHCeL1mtEpfw@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Giants vs. Ports Giants vs. Ports

Follow on MiLB First Pitch  https //stza.co/+xEXv-_

Shop  https //stza.co/+xEXv-2r

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Giants vs. Ports
END:VALARM
DTSTART:20180626T020000Z
DTEND:20180626T050000Z
UID:XXBpEgSPU-nixHCeL1mtEpfw@stanza.co
SUMMARY:Giants vs. Ports
DESCRIPTION:Giants vs. Ports\n\nFollow on MiLB First Pitch: https://stza.co/+xEXv-_\n\nShop: https://stza.co/+xEXv-2r\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144557Z
LAST-MODIFIED:20180213T144557Z
TRANSP:OPAQUE
END:VEVENT
* Giants vs. Ports
<2018-06-26 Tue 21:00>--<2018-06-27 Wed 00:00>
:PROPERTIES:
:ID:       u_UcEKRyyJLl_DtMSyBzPswq@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Giants vs. Ports Giants vs. Ports

Follow on MiLB First Pitch  https //stza.co/+xEXy-b

Shop  https //stza.co/+xEXy-d

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Giants vs. Ports
END:VALARM
DTSTART:20180627T020000Z
DTEND:20180627T050000Z
UID:u_UcEKRyyJLl_DtMSyBzPswq@stanza.co
SUMMARY:Giants vs. Ports
DESCRIPTION:Giants vs. Ports\n\nFollow on MiLB First Pitch: https://stza.co/+xEXy-b\n\nShop: https://stza.co/+xEXy-d\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144557Z
LAST-MODIFIED:20180213T144557Z
TRANSP:OPAQUE
END:VEVENT
* Giants vs. Ports
<2018-06-27 Wed 21:00>--<2018-06-28 Thu 00:00>
:PROPERTIES:
:ID:       mxX8KdSUw8Rx7iDZ_6QgVans@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Giants vs. Ports Giants vs. Ports

Follow on MiLB First Pitch  https //stza.co/+xEXA-z

Shop  https //stza.co/+xEXA-1i

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Giants vs. Ports
END:VALARM
DTSTART:20180628T020000Z
DTEND:20180628T050000Z
UID:mxX8KdSUw8Rx7iDZ_6QgVans@stanza.co
SUMMARY:Giants vs. Ports
DESCRIPTION:Giants vs. Ports\n\nFollow on MiLB First Pitch: https://stza.co/+xEXA-z\n\nShop: https://stza.co/+xEXA-1i\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144557Z
LAST-MODIFIED:20180213T144557Z
TRANSP:OPAQUE
END:VEVENT
* Giants vs. Ports
<2018-06-28 Thu 14:30-17:30>
:PROPERTIES:
:ID:       H6LBZUovh2uWtZJNGxRePA7N@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Giants vs. Ports Giants vs. Ports

Follow on MiLB First Pitch  https //stza.co/+xEXC-1d

Shop  https //stza.co/+xEXC-N

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Giants vs. Ports
END:VALARM
DTSTART:20180628T193000Z
DTEND:20180628T223000Z
UID:H6LBZUovh2uWtZJNGxRePA7N@stanza.co
SUMMARY:Giants vs. Ports
DESCRIPTION:Giants vs. Ports\n\nFollow on MiLB First Pitch: https://stza.co/+xEXC-1d\n\nShop: https://stza.co/+xEXC-N\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144557Z
LAST-MODIFIED:20180213T144557Z
TRANSP:OPAQUE
END:VEVENT
* Giants @ Rawhide
<2018-06-29 Fri>--<2018-06-28 Thu>
:PROPERTIES:
:ID:       SDPZl6oXeGceNdFJIUfoCHum@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Giants @ Rawhide Giants @ Rawhide

Follow on MiLB First Pitch  https //stza.co/+vM1R-2s

Shop  https //stza.co/+vM1R-2W

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Giants @ Rawhide
END:VALARM
DTSTART;VALUE=DATE:20180629
DTEND;VALUE=DATE:20180629
UID:SDPZl6oXeGceNdFJIUfoCHum@stanza.co
SUMMARY:Giants @ Rawhide
DESCRIPTION:Giants @ Rawhide\n\nFollow on MiLB First Pitch: https://stza.co/+vM1R-2s\n\nShop: https://stza.co/+vM1R-2W\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144557Z
LAST-MODIFIED:20180213T144557Z
TRANSP:OPAQUE
END:VEVENT
* Giants @ Rawhide
<2018-06-30 Sat>--<2018-06-29 Fri>
:PROPERTIES:
:ID:       BLp4qrpOYxn2FI0cZ0MGGViq@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Giants @ Rawhide Giants @ Rawhide

Follow on MiLB First Pitch  https //stza.co/+vM1S-1g

Shop  https //stza.co/+vM1S-V

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Giants @ Rawhide
END:VALARM
DTSTART;VALUE=DATE:20180630
DTEND;VALUE=DATE:20180630
UID:BLp4qrpOYxn2FI0cZ0MGGViq@stanza.co
SUMMARY:Giants @ Rawhide
DESCRIPTION:Giants @ Rawhide\n\nFollow on MiLB First Pitch: https://stza.co/+vM1S-1g\n\nShop: https://stza.co/+vM1S-V\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144557Z
LAST-MODIFIED:20180213T144557Z
TRANSP:OPAQUE
END:VEVENT
* Giants @ Rawhide
<2018-07-01 Sun>--<2018-06-30 Sat>
:PROPERTIES:
:ID:       YcEHk5KY8FQXA4AfP__-_X-Q@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Giants @ Rawhide Giants @ Rawhide

Follow on MiLB First Pitch  https //stza.co/+vM1T-1N

Shop  https //stza.co/+vM1T-2J

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Giants @ Rawhide
END:VALARM
DTSTART;VALUE=DATE:20180701
DTEND;VALUE=DATE:20180701
UID:YcEHk5KY8FQXA4AfP__-_X-Q@stanza.co
SUMMARY:Giants @ Rawhide
DESCRIPTION:Giants @ Rawhide\n\nFollow on MiLB First Pitch: https://stza.co/+vM1T-1N\n\nShop: https://stza.co/+vM1T-2J\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144557Z
LAST-MODIFIED:20180213T144557Z
TRANSP:OPAQUE
END:VEVENT
* Giants @ Rawhide
<2018-07-02 Mon>--<2018-07-01 Sun>
:PROPERTIES:
:ID:       8g6Xve0Wvrd-Z2h-uykPW43x@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Giants @ Rawhide Giants @ Rawhide

Follow on MiLB First Pitch  https //stza.co/+vM1U-22

Shop  https //stza.co/+vM1U-o

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Giants @ Rawhide
END:VALARM
DTSTART;VALUE=DATE:20180702
DTEND;VALUE=DATE:20180702
UID:8g6Xve0Wvrd-Z2h-uykPW43x@stanza.co
SUMMARY:Giants @ Rawhide
DESCRIPTION:Giants @ Rawhide\n\nFollow on MiLB First Pitch: https://stza.co/+vM1U-22\n\nShop: https://stza.co/+vM1U-o\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144557Z
LAST-MODIFIED:20180213T144557Z
TRANSP:OPAQUE
END:VEVENT
* Giants @ Rawhide
<2018-07-03 Tue>--<2018-07-02 Mon>
:PROPERTIES:
:ID:       k6O7kYAfvGCz9cIohJNuQgop@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Giants @ Rawhide Giants @ Rawhide

Follow on MiLB First Pitch  https //stza.co/+vM1V-21

Shop  https //stza.co/+vM1V-b

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Giants @ Rawhide
END:VALARM
DTSTART;VALUE=DATE:20180703
DTEND;VALUE=DATE:20180703
UID:k6O7kYAfvGCz9cIohJNuQgop@stanza.co
SUMMARY:Giants @ Rawhide
DESCRIPTION:Giants @ Rawhide\n\nFollow on MiLB First Pitch: https://stza.co/+vM1V-21\n\nShop: https://stza.co/+vM1V-b\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144557Z
LAST-MODIFIED:20180213T144557Z
TRANSP:OPAQUE
END:VEVENT
* Giants vs. Quakes
<2018-07-04 Wed 20:30-23:30>
:PROPERTIES:
:ID:       6Kz6HE2TBTkqMF39ZYOO8TZU@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Giants vs. Quakes Giants vs. Quakes

Follow on MiLB First Pitch  https //stza.co/+xEXD-3y

Shop  https //stza.co/+xEXD-3w

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Giants vs. Quakes
END:VALARM
DTSTART:20180705T013000Z
DTEND:20180705T043000Z
UID:6Kz6HE2TBTkqMF39ZYOO8TZU@stanza.co
SUMMARY:Giants vs. Quakes
DESCRIPTION:Giants vs. Quakes\n\nFollow on MiLB First Pitch: https://stza.co/+xEXD-3y\n\nShop: https://stza.co/+xEXD-3w\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144557Z
LAST-MODIFIED:20180213T144557Z
TRANSP:OPAQUE
END:VEVENT
* Giants vs. Quakes
<2018-07-05 Thu 21:00>--<2018-07-06 Fri 00:00>
:PROPERTIES:
:ID:       9MMesWdJORd0Bo-v9haBwV7r@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Giants vs. Quakes Giants vs. Quakes

Follow on MiLB First Pitch  https //stza.co/+xEXG-2E

Shop  https //stza.co/+xEXG-M

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Giants vs. Quakes
END:VALARM
DTSTART:20180706T020000Z
DTEND:20180706T050000Z
UID:9MMesWdJORd0Bo-v9haBwV7r@stanza.co
SUMMARY:Giants vs. Quakes
DESCRIPTION:Giants vs. Quakes\n\nFollow on MiLB First Pitch: https://stza.co/+xEXG-2E\n\nShop: https://stza.co/+xEXG-M\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144557Z
LAST-MODIFIED:20180213T144557Z
TRANSP:OPAQUE
END:VEVENT
* Giants vs. Quakes
<2018-07-06 Fri 21:00>--<2018-07-07 Sat 00:00>
:PROPERTIES:
:ID:       m-AbJoAQKm_A_jMgfxjhN3up@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Giants vs. Quakes Giants vs. Quakes

Follow on MiLB First Pitch  https //stza.co/+xEXI-2u

Shop  https //stza.co/+xEXI-T

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Giants vs. Quakes
END:VALARM
DTSTART:20180707T020000Z
DTEND:20180707T050000Z
UID:m-AbJoAQKm_A_jMgfxjhN3up@stanza.co
SUMMARY:Giants vs. Quakes
DESCRIPTION:Giants vs. Quakes\n\nFollow on MiLB First Pitch: https://stza.co/+xEXI-2u\n\nShop: https://stza.co/+xEXI-T\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144557Z
LAST-MODIFIED:20180213T144557Z
TRANSP:OPAQUE
END:VEVENT
* Giants vs. Quakes
<2018-07-07 Sat 19:00-22:00>
:PROPERTIES:
:ID:       myPDiFiunrJtuLNm52GuC8pr@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Giants vs. Quakes Giants vs. Quakes

Follow on MiLB First Pitch  https //stza.co/+xEXK-3V

Shop  https //stza.co/+xEXK-2d

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Giants vs. Quakes
END:VALARM
DTSTART:20180708T000000Z
DTEND:20180708T030000Z
UID:myPDiFiunrJtuLNm52GuC8pr@stanza.co
SUMMARY:Giants vs. Quakes
DESCRIPTION:Giants vs. Quakes\n\nFollow on MiLB First Pitch: https://stza.co/+xEXK-3V\n\nShop: https://stza.co/+xEXK-2d\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144557Z
LAST-MODIFIED:20180213T144557Z
TRANSP:OPAQUE
END:VEVENT
* Giants vs. Quakes
<2018-07-08 Sun 19:00-22:00>
:PROPERTIES:
:ID:       lVEDMiERkep7JDE4TEM1AQWk@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Giants vs. Quakes Giants vs. Quakes

Follow on MiLB First Pitch  https //stza.co/+xEXM-10

Shop  https //stza.co/+xEXM-39

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Giants vs. Quakes
END:VALARM
DTSTART:20180709T000000Z
DTEND:20180709T030000Z
UID:lVEDMiERkep7JDE4TEM1AQWk@stanza.co
SUMMARY:Giants vs. Quakes
DESCRIPTION:Giants vs. Quakes\n\nFollow on MiLB First Pitch: https://stza.co/+xEXM-10\n\nShop: https://stza.co/+xEXM-39\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144557Z
LAST-MODIFIED:20180213T144557Z
TRANSP:OPAQUE
END:VEVENT
* Giants @ Ports
<2018-07-09 Mon 21:10>--<2018-07-10 Tue 00:10>
:PROPERTIES:
:ID:       fs07oV2_BM4HNuoW-qSY4Qo1@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Giants @ Ports Giants @ Ports

Follow on MiLB First Pitch  https //stza.co/+vM1H-J

Shop  https //stza.co/+vM1H-3Y

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Giants @ Ports
END:VALARM
DTSTART:20180710T021000Z
DTEND:20180710T051000Z
UID:fs07oV2_BM4HNuoW-qSY4Qo1@stanza.co
SUMMARY:Giants @ Ports
DESCRIPTION:Giants @ Ports\n\nFollow on MiLB First Pitch: https://stza.co/+vM1H-J\n\nShop: https://stza.co/+vM1H-3Y\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144557Z
LAST-MODIFIED:20180213T144557Z
TRANSP:OPAQUE
END:VEVENT
* Giants @ Ports
<2018-07-10 Tue 21:10>--<2018-07-11 Wed 00:10>
:PROPERTIES:
:ID:       279O3qf924ykQawis5l4cN07@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Giants @ Ports Giants @ Ports

Follow on MiLB First Pitch  https //stza.co/+vM1I-X

Shop  https //stza.co/+vM1I-1r

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Giants @ Ports
END:VALARM
DTSTART:20180711T021000Z
DTEND:20180711T051000Z
UID:279O3qf924ykQawis5l4cN07@stanza.co
SUMMARY:Giants @ Ports
DESCRIPTION:Giants @ Ports\n\nFollow on MiLB First Pitch: https://stza.co/+vM1I-X\n\nShop: https://stza.co/+vM1I-1r\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144557Z
LAST-MODIFIED:20180213T144557Z
TRANSP:OPAQUE
END:VEVENT
* Giants @ Ports
<2018-07-11 Wed 21:10>--<2018-07-12 Thu 00:10>
:PROPERTIES:
:ID:       Lu-A-KbD05Q7ApAwS0AbKMyp@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Giants @ Ports Giants @ Ports

Follow on MiLB First Pitch  https //stza.co/+vM1J-2S

Shop  https //stza.co/+vM1J-2v

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Giants @ Ports
END:VALARM
DTSTART:20180712T021000Z
DTEND:20180712T051000Z
UID:Lu-A-KbD05Q7ApAwS0AbKMyp@stanza.co
SUMMARY:Giants @ Ports
DESCRIPTION:Giants @ Ports\n\nFollow on MiLB First Pitch: https://stza.co/+vM1J-2S\n\nShop: https://stza.co/+vM1J-2v\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144557Z
LAST-MODIFIED:20180213T144557Z
TRANSP:OPAQUE
END:VEVENT
* Giants @ Ports
<2018-07-12 Thu 21:10>--<2018-07-13 Fri 00:10>
:PROPERTIES:
:ID:       f1orgK00pk9f-4t8_RfKfCxw@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Giants @ Ports Giants @ Ports

Follow on MiLB First Pitch  https //stza.co/+vM1K-g

Shop  https //stza.co/+vM1K-x

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Giants @ Ports
END:VALARM
DTSTART:20180713T021000Z
DTEND:20180713T051000Z
UID:f1orgK00pk9f-4t8_RfKfCxw@stanza.co
SUMMARY:Giants @ Ports
DESCRIPTION:Giants @ Ports\n\nFollow on MiLB First Pitch: https://stza.co/+vM1K-g\n\nShop: https://stza.co/+vM1K-x\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144557Z
LAST-MODIFIED:20180213T144557Z
TRANSP:OPAQUE
END:VEVENT
* Giants vs. Rawhide
<2018-07-13 Fri 21:00>--<2018-07-14 Sat 00:00>
:PROPERTIES:
:ID:       m5wX-VMoJKlZFMpdAxc7EuOM@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Giants vs. Rawhide Giants vs. Rawhide

Follow on MiLB First Pitch  https //stza.co/+xEXO-2B

Shop  https //stza.co/+xEXO-3V

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Giants vs. Rawhide
END:VALARM
DTSTART:20180714T020000Z
DTEND:20180714T050000Z
UID:m5wX-VMoJKlZFMpdAxc7EuOM@stanza.co
SUMMARY:Giants vs. Rawhide
DESCRIPTION:Giants vs. Rawhide\n\nFollow on MiLB First Pitch: https://stza.co/+xEXO-2B\n\nShop: https://stza.co/+xEXO-3V\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144557Z
LAST-MODIFIED:20180213T144557Z
TRANSP:OPAQUE
END:VEVENT
* Giants vs. Rawhide
<2018-07-14 Sat 19:00-22:00>
:PROPERTIES:
:ID:       1uSk2bG6XOTGQvKGa98Nf2om@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Giants vs. Rawhide Giants vs. Rawhide

Follow on MiLB First Pitch  https //stza.co/+xEXQ-3Y

Shop  https //stza.co/+xEXQ-3g

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Giants vs. Rawhide
END:VALARM
DTSTART:20180715T000000Z
DTEND:20180715T030000Z
UID:1uSk2bG6XOTGQvKGa98Nf2om@stanza.co
SUMMARY:Giants vs. Rawhide
DESCRIPTION:Giants vs. Rawhide\n\nFollow on MiLB First Pitch: https://stza.co/+xEXQ-3Y\n\nShop: https://stza.co/+xEXQ-3g\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144557Z
LAST-MODIFIED:20180213T144557Z
TRANSP:OPAQUE
END:VEVENT
* Giants vs. Rawhide
<2018-07-15 Sun 19:00-22:00>
:PROPERTIES:
:ID:       cRe6ezicezAlfnRsKfRxuiDb@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Giants vs. Rawhide Giants vs. Rawhide

Follow on MiLB First Pitch  https //stza.co/+xEXR-1_

Shop  https //stza.co/+xEXR-K

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Giants vs. Rawhide
END:VALARM
DTSTART:20180716T000000Z
DTEND:20180716T030000Z
UID:cRe6ezicezAlfnRsKfRxuiDb@stanza.co
SUMMARY:Giants vs. Rawhide
DESCRIPTION:Giants vs. Rawhide\n\nFollow on MiLB First Pitch: https://stza.co/+xEXR-1_\n\nShop: https://stza.co/+xEXR-K\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144557Z
LAST-MODIFIED:20180213T144557Z
TRANSP:OPAQUE
END:VEVENT
* Giants vs. Rawhide
<2018-07-16 Mon 14:30-17:30>
:PROPERTIES:
:ID:       THEaXONZewbdIfnqfOzThbYD@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Giants vs. Rawhide Giants vs. Rawhide

Follow on MiLB First Pitch  https //stza.co/+xEXU-3U

Shop  https //stza.co/+xEXU-d

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Giants vs. Rawhide
END:VALARM
DTSTART:20180716T193000Z
DTEND:20180716T223000Z
UID:THEaXONZewbdIfnqfOzThbYD@stanza.co
SUMMARY:Giants vs. Rawhide
DESCRIPTION:Giants vs. Rawhide\n\nFollow on MiLB First Pitch: https://stza.co/+xEXU-3U\n\nShop: https://stza.co/+xEXU-d\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144557Z
LAST-MODIFIED:20180213T144557Z
TRANSP:OPAQUE
END:VEVENT
* Giants @ Quakes
<2018-07-18 Wed 21:05>--<2018-07-19 Thu 00:05>
:PROPERTIES:
:ID:       X4RBYS1l0kHoTpOXrsFIhpDC@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Giants @ Quakes Giants @ Quakes

Follow on MiLB First Pitch  https //stza.co/+xz$P-3h

Shop  https //stza.co/+xz$P-12

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Giants @ Quakes
END:VALARM
DTSTART:20180719T020500Z
DTEND:20180719T050500Z
UID:X4RBYS1l0kHoTpOXrsFIhpDC@stanza.co
SUMMARY:Giants @ Quakes
DESCRIPTION:Giants @ Quakes\n\nFollow on MiLB First Pitch: https://stza.co/+xz$P-3h\n\nShop: https://stza.co/+xz$P-12\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144557Z
LAST-MODIFIED:20180213T144557Z
TRANSP:OPAQUE
END:VEVENT
* Giants @ Quakes
<2018-07-19 Thu 21:05>--<2018-07-20 Fri 00:05>
:PROPERTIES:
:ID:       ZX0E_3oZTtvQvOXq1c5Cfky0@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Giants @ Quakes Giants @ Quakes

Follow on MiLB First Pitch  https //stza.co/+xz$Q-2u

Shop  https //stza.co/+xz$Q-3W

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Giants @ Quakes
END:VALARM
DTSTART:20180720T020500Z
DTEND:20180720T050500Z
UID:ZX0E_3oZTtvQvOXq1c5Cfky0@stanza.co
SUMMARY:Giants @ Quakes
DESCRIPTION:Giants @ Quakes\n\nFollow on MiLB First Pitch: https://stza.co/+xz$Q-2u\n\nShop: https://stza.co/+xz$Q-3W\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144557Z
LAST-MODIFIED:20180213T144557Z
TRANSP:OPAQUE
END:VEVENT
* Giants @ Quakes
<2018-07-20 Fri 21:05>--<2018-07-21 Sat 00:05>
:PROPERTIES:
:ID:       Hg3ozaAas1Pa2sCz5cFu9ydV@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Giants @ Quakes Giants @ Quakes

Follow on MiLB First Pitch  https //stza.co/+xz$R-37

Shop  https //stza.co/+xz$R-2l

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Giants @ Quakes
END:VALARM
DTSTART:20180721T020500Z
DTEND:20180721T050500Z
UID:Hg3ozaAas1Pa2sCz5cFu9ydV@stanza.co
SUMMARY:Giants @ Quakes
DESCRIPTION:Giants @ Quakes\n\nFollow on MiLB First Pitch: https://stza.co/+xz$R-37\n\nShop: https://stza.co/+xz$R-2l\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144557Z
LAST-MODIFIED:20180213T144557Z
TRANSP:OPAQUE
END:VEVENT
* Giants @ Storm
<2018-07-21 Sat 20:00-23:00>
:PROPERTIES:
:ID:       1DInzBSUoisJEo1TfKh2XDzb@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Giants @ Storm Giants @ Storm

Follow on MiLB First Pitch  https //stza.co/+xz_$-I

Shop  https //stza.co/+xz_$-2Q

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Giants @ Storm
END:VALARM
DTSTART:20180722T010000Z
DTEND:20180722T040000Z
UID:1DInzBSUoisJEo1TfKh2XDzb@stanza.co
SUMMARY:Giants @ Storm
DESCRIPTION:Giants @ Storm\n\nFollow on MiLB First Pitch: https://stza.co/+xz_$-I\n\nShop: https://stza.co/+xz_$-2Q\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144557Z
LAST-MODIFIED:20180213T144557Z
TRANSP:OPAQUE
END:VEVENT
* Giants @ Storm
<2018-07-22 Sun>--<2018-07-21 Sat>
:PROPERTIES:
:ID:       0GPLnk27tMtKuUdLKL-Pn4qW@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Giants @ Storm Giants @ Storm

Follow on MiLB First Pitch  https //stza.co/+vfbB-2C

Shop  https //stza.co/+vfbB-2m

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Giants @ Storm
END:VALARM
DTSTART;VALUE=DATE:20180722
DTEND;VALUE=DATE:20180722
UID:0GPLnk27tMtKuUdLKL-Pn4qW@stanza.co
SUMMARY:Giants @ Storm
DESCRIPTION:Giants @ Storm\n\nFollow on MiLB First Pitch: https://stza.co/+vfbB-2C\n\nShop: https://stza.co/+vfbB-2m\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144557Z
LAST-MODIFIED:20180213T144557Z
TRANSP:OPAQUE
END:VEVENT
* Giants @ Storm
<2018-07-23 Mon 20:00-23:00>
:PROPERTIES:
:ID:       Oa0J7nb6rXdRflUUxa4akvez@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Giants @ Storm Giants @ Storm

Follow on MiLB First Pitch  https //stza.co/+xz$1-2R

Shop  https //stza.co/+xz$1-v

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Giants @ Storm
END:VALARM
DTSTART:20180724T010000Z
DTEND:20180724T040000Z
UID:Oa0J7nb6rXdRflUUxa4akvez@stanza.co
SUMMARY:Giants @ Storm
DESCRIPTION:Giants @ Storm\n\nFollow on MiLB First Pitch: https://stza.co/+xz$1-2R\n\nShop: https://stza.co/+xz$1-v\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144557Z
LAST-MODIFIED:20180213T144557Z
TRANSP:OPAQUE
END:VEVENT
* Giants vs. Quakes
<2018-07-24 Tue 21:00>--<2018-07-25 Wed 00:00>
:PROPERTIES:
:ID:       9HvRIs-R18N1Ve4g7fWqQGZe@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Giants vs. Quakes Giants vs. Quakes

Follow on MiLB First Pitch  https //stza.co/+xEXW-1t

Shop  https //stza.co/+xEXW-e

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Giants vs. Quakes
END:VALARM
DTSTART:20180725T020000Z
DTEND:20180725T050000Z
UID:9HvRIs-R18N1Ve4g7fWqQGZe@stanza.co
SUMMARY:Giants vs. Quakes
DESCRIPTION:Giants vs. Quakes\n\nFollow on MiLB First Pitch: https://stza.co/+xEXW-1t\n\nShop: https://stza.co/+xEXW-e\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144557Z
LAST-MODIFIED:20180213T144557Z
TRANSP:OPAQUE
END:VEVENT
* Giants vs. Quakes
<2018-07-25 Wed 21:00>--<2018-07-26 Thu 00:00>
:PROPERTIES:
:ID:       0oQ3bDXT60P87gLjX-AdzPEI@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Giants vs. Quakes Giants vs. Quakes

Follow on MiLB First Pitch  https //stza.co/+xEXX-f

Shop  https //stza.co/+xEXX-1H

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Giants vs. Quakes
END:VALARM
DTSTART:20180726T020000Z
DTEND:20180726T050000Z
UID:0oQ3bDXT60P87gLjX-AdzPEI@stanza.co
SUMMARY:Giants vs. Quakes
DESCRIPTION:Giants vs. Quakes\n\nFollow on MiLB First Pitch: https://stza.co/+xEXX-f\n\nShop: https://stza.co/+xEXX-1H\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144557Z
LAST-MODIFIED:20180213T144557Z
TRANSP:OPAQUE
END:VEVENT
* Giants vs. Quakes
<2018-07-26 Thu 14:30-17:30>
:PROPERTIES:
:ID:       SesBAfTAVWKEJE3pAxfOYVhF@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Giants vs. Quakes Giants vs. Quakes

Follow on MiLB First Pitch  https //stza.co/+xEX_-2l

Shop  https //stza.co/+xEX_-x

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Giants vs. Quakes
END:VALARM
DTSTART:20180726T193000Z
DTEND:20180726T223000Z
UID:SesBAfTAVWKEJE3pAxfOYVhF@stanza.co
SUMMARY:Giants vs. Quakes
DESCRIPTION:Giants vs. Quakes\n\nFollow on MiLB First Pitch: https://stza.co/+xEX_-2l\n\nShop: https://stza.co/+xEX_-x\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144557Z
LAST-MODIFIED:20180213T144557Z
TRANSP:OPAQUE
END:VEVENT
* Giants vs. 66ers
<2018-07-27 Fri 21:00>--<2018-07-28 Sat 00:00>
:PROPERTIES:
:ID:       lw2hESPCDUffapAC3w3IxkRC@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Giants vs. 66ers Giants vs. 66ers

Follow on MiLB First Pitch  https //stza.co/+xEY0-o

Shop  https //stza.co/+xEY0-l

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Giants vs. 66ers
END:VALARM
DTSTART:20180728T020000Z
DTEND:20180728T050000Z
UID:lw2hESPCDUffapAC3w3IxkRC@stanza.co
SUMMARY:Giants vs. 66ers
DESCRIPTION:Giants vs. 66ers\n\nFollow on MiLB First Pitch: https://stza.co/+xEY0-o\n\nShop: https://stza.co/+xEY0-l\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144557Z
LAST-MODIFIED:20180213T144557Z
TRANSP:OPAQUE
END:VEVENT
* Giants vs. 66ers
<2018-07-28 Sat 20:00-23:00>
:PROPERTIES:
:ID:       e1KsyY6fNuWxhG_2o0xajhQk@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Giants vs. 66ers Giants vs. 66ers

Follow on MiLB First Pitch  https //stza.co/+xEY1-3u

Shop  https //stza.co/+xEY1-1k

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Giants vs. 66ers
END:VALARM
DTSTART:20180729T010000Z
DTEND:20180729T040000Z
UID:e1KsyY6fNuWxhG_2o0xajhQk@stanza.co
SUMMARY:Giants vs. 66ers
DESCRIPTION:Giants vs. 66ers\n\nFollow on MiLB First Pitch: https://stza.co/+xEY1-3u\n\nShop: https://stza.co/+xEY1-1k\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144557Z
LAST-MODIFIED:20180213T144557Z
TRANSP:OPAQUE
END:VEVENT
* Giants vs. 66ers
<2018-07-29 Sun 19:00-22:00>
:PROPERTIES:
:ID:       A4oDLckhY1TTjy1TtaF9cbn_@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Giants vs. 66ers Giants vs. 66ers

Follow on MiLB First Pitch  https //stza.co/+xEY4-l

Shop  https //stza.co/+xEY4-W

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Giants vs. 66ers
END:VALARM
DTSTART:20180730T000000Z
DTEND:20180730T030000Z
UID:A4oDLckhY1TTjy1TtaF9cbn_@stanza.co
SUMMARY:Giants vs. 66ers
DESCRIPTION:Giants vs. 66ers\n\nFollow on MiLB First Pitch: https://stza.co/+xEY4-l\n\nShop: https://stza.co/+xEY4-W\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144557Z
LAST-MODIFIED:20180213T144557Z
TRANSP:OPAQUE
END:VEVENT
* Giants @ Rawhide
<2018-07-31 Tue>--<2018-07-30 Mon>
:PROPERTIES:
:ID:       VcHhSQbZXCAdwHTFsvg2cmfR@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Giants @ Rawhide Giants @ Rawhide

Follow on MiLB First Pitch  https //stza.co/+vM1W-3Y

Shop  https //stza.co/+vM1W-L

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Giants @ Rawhide
END:VALARM
DTSTART;VALUE=DATE:20180731
DTEND;VALUE=DATE:20180731
UID:VcHhSQbZXCAdwHTFsvg2cmfR@stanza.co
SUMMARY:Giants @ Rawhide
DESCRIPTION:Giants @ Rawhide\n\nFollow on MiLB First Pitch: https://stza.co/+vM1W-3Y\n\nShop: https://stza.co/+vM1W-L\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144557Z
LAST-MODIFIED:20180213T144557Z
TRANSP:OPAQUE
END:VEVENT
* Giants @ Rawhide
<2018-08-01 Wed>--<2018-07-31 Tue>
:PROPERTIES:
:ID:       nsGvvXYoDfVbe7CusZggdyUL@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Giants @ Rawhide Giants @ Rawhide

Follow on MiLB First Pitch  https //stza.co/+vM1X-2k

Shop  https //stza.co/+vM1X-2L

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Giants @ Rawhide
END:VALARM
DTSTART;VALUE=DATE:20180801
DTEND;VALUE=DATE:20180801
UID:nsGvvXYoDfVbe7CusZggdyUL@stanza.co
SUMMARY:Giants @ Rawhide
DESCRIPTION:Giants @ Rawhide\n\nFollow on MiLB First Pitch: https://stza.co/+vM1X-2k\n\nShop: https://stza.co/+vM1X-2L\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144557Z
LAST-MODIFIED:20180213T144557Z
TRANSP:OPAQUE
END:VEVENT
* Giants @ Rawhide
<2018-08-02 Thu>--<2018-08-01 Wed>
:PROPERTIES:
:ID:       b8xInYMlN0nldLVuTlsY3tcb@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Giants @ Rawhide Giants @ Rawhide

Follow on MiLB First Pitch  https //stza.co/+vM1Y-7

Shop  https //stza.co/+vM1Y-3H

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Giants @ Rawhide
END:VALARM
DTSTART;VALUE=DATE:20180802
DTEND;VALUE=DATE:20180802
UID:b8xInYMlN0nldLVuTlsY3tcb@stanza.co
SUMMARY:Giants @ Rawhide
DESCRIPTION:Giants @ Rawhide\n\nFollow on MiLB First Pitch: https://stza.co/+vM1Y-7\n\nShop: https://stza.co/+vM1Y-3H\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144557Z
LAST-MODIFIED:20180213T144557Z
TRANSP:OPAQUE
END:VEVENT
* Giants vs. Storm
<2018-08-03 Fri 21:00>--<2018-08-04 Sat 00:00>
:PROPERTIES:
:ID:       uGfrj1L5BRM4W2VyYW6zl67o@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Giants vs. Storm Giants vs. Storm

Follow on MiLB First Pitch  https //stza.co/+xEY6-3p

Shop  https //stza.co/+xEY6-3Q

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Giants vs. Storm
END:VALARM
DTSTART:20180804T020000Z
DTEND:20180804T050000Z
UID:uGfrj1L5BRM4W2VyYW6zl67o@stanza.co
SUMMARY:Giants vs. Storm
DESCRIPTION:Giants vs. Storm\n\nFollow on MiLB First Pitch: https://stza.co/+xEY6-3p\n\nShop: https://stza.co/+xEY6-3Q\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144557Z
LAST-MODIFIED:20180213T144557Z
TRANSP:OPAQUE
END:VEVENT
* Giants vs. Storm
<2018-08-04 Sat 19:00-22:00>
:PROPERTIES:
:ID:       54dBrWWO1d8Katb5MQ8yl0_k@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Giants vs. Storm Giants vs. Storm

Follow on MiLB First Pitch  https //stza.co/+xEY8-l

Shop  https //stza.co/+xEY8-f

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Giants vs. Storm
END:VALARM
DTSTART:20180805T000000Z
DTEND:20180805T030000Z
UID:54dBrWWO1d8Katb5MQ8yl0_k@stanza.co
SUMMARY:Giants vs. Storm
DESCRIPTION:Giants vs. Storm\n\nFollow on MiLB First Pitch: https://stza.co/+xEY8-l\n\nShop: https://stza.co/+xEY8-f\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144557Z
LAST-MODIFIED:20180213T144557Z
TRANSP:OPAQUE
END:VEVENT
* Giants vs. Storm
<2018-08-05 Sun 19:00-22:00>
:PROPERTIES:
:ID:       NyLqGAnyHvrA29-ZQc1YXDhL@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Giants vs. Storm Giants vs. Storm

Follow on MiLB First Pitch  https //stza.co/+xEY9-2f

Shop  https //stza.co/+xEY9-X

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Giants vs. Storm
END:VALARM
DTSTART:20180806T000000Z
DTEND:20180806T030000Z
UID:NyLqGAnyHvrA29-ZQc1YXDhL@stanza.co
SUMMARY:Giants vs. Storm
DESCRIPTION:Giants vs. Storm\n\nFollow on MiLB First Pitch: https://stza.co/+xEY9-2f\n\nShop: https://stza.co/+xEY9-X\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144557Z
LAST-MODIFIED:20180213T144557Z
TRANSP:OPAQUE
END:VEVENT
* Giants vs. Quakes
<2018-08-06 Mon 21:00>--<2018-08-07 Tue 00:00>
:PROPERTIES:
:ID:       50txac3-x9A5ndOZJNrbERdO@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Giants vs. Quakes Giants vs. Quakes

Follow on MiLB First Pitch  https //stza.co/+xEYc-3p

Shop  https //stza.co/+xEYc-2M

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Giants vs. Quakes
END:VALARM
DTSTART:20180807T020000Z
DTEND:20180807T050000Z
UID:50txac3-x9A5ndOZJNrbERdO@stanza.co
SUMMARY:Giants vs. Quakes
DESCRIPTION:Giants vs. Quakes\n\nFollow on MiLB First Pitch: https://stza.co/+xEYc-3p\n\nShop: https://stza.co/+xEYc-2M\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144557Z
LAST-MODIFIED:20180213T144557Z
TRANSP:OPAQUE
END:VEVENT
* Giants vs. Quakes
<2018-08-07 Tue 21:00>--<2018-08-08 Wed 00:00>
:PROPERTIES:
:ID:       STNVzhZzSkzPA8hDJG-v60VL@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Giants vs. Quakes Giants vs. Quakes

Follow on MiLB First Pitch  https //stza.co/+xEYe-2i

Shop  https //stza.co/+xEYe-2X

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Giants vs. Quakes
END:VALARM
DTSTART:20180808T020000Z
DTEND:20180808T050000Z
UID:STNVzhZzSkzPA8hDJG-v60VL@stanza.co
SUMMARY:Giants vs. Quakes
DESCRIPTION:Giants vs. Quakes\n\nFollow on MiLB First Pitch: https://stza.co/+xEYe-2i\n\nShop: https://stza.co/+xEYe-2X\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144557Z
LAST-MODIFIED:20180213T144557Z
TRANSP:OPAQUE
END:VEVENT
* Giants vs. Quakes
<2018-08-08 Wed 14:30-17:30>
:PROPERTIES:
:ID:       B56m5WeaRk3IanGvuYZBPISj@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Giants vs. Quakes Giants vs. Quakes

Follow on MiLB First Pitch  https //stza.co/+xEYg-2c

Shop  https //stza.co/+xEYg-21

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Giants vs. Quakes
END:VALARM
DTSTART:20180808T193000Z
DTEND:20180808T223000Z
UID:B56m5WeaRk3IanGvuYZBPISj@stanza.co
SUMMARY:Giants vs. Quakes
DESCRIPTION:Giants vs. Quakes\n\nFollow on MiLB First Pitch: https://stza.co/+xEYg-2c\n\nShop: https://stza.co/+xEYg-21\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144557Z
LAST-MODIFIED:20180213T144557Z
TRANSP:OPAQUE
END:VEVENT
* Giants @ Ports
<2018-08-10 Fri 21:10>--<2018-08-11 Sat 00:10>
:PROPERTIES:
:ID:       V1KV7QHe8po4XT96gqN2D7Xt@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Giants @ Ports Giants @ Ports

Follow on MiLB First Pitch  https //stza.co/+vM1L-D

Shop  https //stza.co/+vM1L-n

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Giants @ Ports
END:VALARM
DTSTART:20180811T021000Z
DTEND:20180811T051000Z
UID:V1KV7QHe8po4XT96gqN2D7Xt@stanza.co
SUMMARY:Giants @ Ports
DESCRIPTION:Giants @ Ports\n\nFollow on MiLB First Pitch: https://stza.co/+vM1L-D\n\nShop: https://stza.co/+vM1L-n\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144557Z
LAST-MODIFIED:20180213T144557Z
TRANSP:OPAQUE
END:VEVENT
* Giants @ Ports
<2018-08-11 Sat 21:10>--<2018-08-12 Sun 00:10>
:PROPERTIES:
:ID:       mr13dSfRncawIqDY2TgIHTgh@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Giants @ Ports Giants @ Ports

Follow on MiLB First Pitch  https //stza.co/+vM1M-g

Shop  https //stza.co/+vM1M-2

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Giants @ Ports
END:VALARM
DTSTART:20180812T021000Z
DTEND:20180812T051000Z
UID:mr13dSfRncawIqDY2TgIHTgh@stanza.co
SUMMARY:Giants @ Ports
DESCRIPTION:Giants @ Ports\n\nFollow on MiLB First Pitch: https://stza.co/+vM1M-g\n\nShop: https://stza.co/+vM1M-2\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144557Z
LAST-MODIFIED:20180213T144557Z
TRANSP:OPAQUE
END:VEVENT
* Giants @ Ports
<2018-08-12 Sun 20:10-23:10>
:PROPERTIES:
:ID:       F4DseJ7bbtApqlhZ2tdANrax@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Giants @ Ports Giants @ Ports

Follow on MiLB First Pitch  https //stza.co/+vM1N-30

Shop  https //stza.co/+vM1N-1o

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Giants @ Ports
END:VALARM
DTSTART:20180813T011000Z
DTEND:20180813T041000Z
UID:F4DseJ7bbtApqlhZ2tdANrax@stanza.co
SUMMARY:Giants @ Ports
DESCRIPTION:Giants @ Ports\n\nFollow on MiLB First Pitch: https://stza.co/+vM1N-30\n\nShop: https://stza.co/+vM1N-1o\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144557Z
LAST-MODIFIED:20180213T144557Z
TRANSP:OPAQUE
END:VEVENT
* Giants @ 66ers
<2018-08-13 Mon 21:05>--<2018-08-14 Tue 00:05>
:PROPERTIES:
:ID:       u5jTRqqvZBVnzlu869kMzp3b@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Giants @ 66ers Giants @ 66ers

Follow on MiLB First Pitch  https //stza.co/+y0CY-u

Shop  https //stza.co/+y0CY-3B

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Giants @ 66ers
END:VALARM
DTSTART:20180814T020500Z
DTEND:20180814T050500Z
UID:u5jTRqqvZBVnzlu869kMzp3b@stanza.co
SUMMARY:Giants @ 66ers
DESCRIPTION:Giants @ 66ers\n\nFollow on MiLB First Pitch: https://stza.co/+y0CY-u\n\nShop: https://stza.co/+y0CY-3B\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144557Z
LAST-MODIFIED:20180213T144557Z
TRANSP:OPAQUE
END:VEVENT
* Giants @ 66ers
<2018-08-14 Tue 21:05>--<2018-08-15 Wed 00:05>
:PROPERTIES:
:ID:       FKO0PPQqwScxttvF6KBzwtuv@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Giants @ 66ers Giants @ 66ers

Follow on MiLB First Pitch  https //stza.co/+y0CZ-L

Shop  https //stza.co/+y0CZ-1$

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Giants @ 66ers
END:VALARM
DTSTART:20180815T020500Z
DTEND:20180815T050500Z
UID:FKO0PPQqwScxttvF6KBzwtuv@stanza.co
SUMMARY:Giants @ 66ers
DESCRIPTION:Giants @ 66ers\n\nFollow on MiLB First Pitch: https://stza.co/+y0CZ-L\n\nShop: https://stza.co/+y0CZ-1$\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144557Z
LAST-MODIFIED:20180213T144557Z
TRANSP:OPAQUE
END:VEVENT
* Giants @ 66ers
<2018-08-15 Wed 21:05>--<2018-08-16 Thu 00:05>
:PROPERTIES:
:ID:       v2FEUjhfPDt7-amJGCYWIKiN@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Giants @ 66ers Giants @ 66ers

Follow on MiLB First Pitch  https //stza.co/+y0C_-32

Shop  https //stza.co/+y0C_-H

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Giants @ 66ers
END:VALARM
DTSTART:20180816T020500Z
DTEND:20180816T050500Z
UID:v2FEUjhfPDt7-amJGCYWIKiN@stanza.co
SUMMARY:Giants @ 66ers
DESCRIPTION:Giants @ 66ers\n\nFollow on MiLB First Pitch: https://stza.co/+y0C_-32\n\nShop: https://stza.co/+y0C_-H\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144557Z
LAST-MODIFIED:20180213T144557Z
TRANSP:OPAQUE
END:VEVENT
* Giants vs. JetHawks
<2018-08-17 Fri 21:00>--<2018-08-18 Sat 00:00>
:PROPERTIES:
:ID:       dOihLrEfS_fB_hLWryhBy2BD@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Giants vs. JetHawks Giants vs. JetHawks

Follow on MiLB First Pitch  https //stza.co/+xEYi-2K

Shop  https //stza.co/+xEYi-E

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Giants vs. JetHawks
END:VALARM
DTSTART:20180818T020000Z
DTEND:20180818T050000Z
UID:dOihLrEfS_fB_hLWryhBy2BD@stanza.co
SUMMARY:Giants vs. JetHawks
DESCRIPTION:Giants vs. JetHawks\n\nFollow on MiLB First Pitch: https://stza.co/+xEYi-2K\n\nShop: https://stza.co/+xEYi-E\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144557Z
LAST-MODIFIED:20180213T144557Z
TRANSP:OPAQUE
END:VEVENT
* Giants vs. JetHawks
<2018-08-18 Sat 19:00-22:00>
:PROPERTIES:
:ID:       S6Ce3A_xFguv9_EWrkU_SmVK@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Giants vs. JetHawks Giants vs. JetHawks

Follow on MiLB First Pitch  https //stza.co/+xEYj-3S

Shop  https //stza.co/+xEYj-2W

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Giants vs. JetHawks
END:VALARM
DTSTART:20180819T000000Z
DTEND:20180819T030000Z
UID:S6Ce3A_xFguv9_EWrkU_SmVK@stanza.co
SUMMARY:Giants vs. JetHawks
DESCRIPTION:Giants vs. JetHawks\n\nFollow on MiLB First Pitch: https://stza.co/+xEYj-3S\n\nShop: https://stza.co/+xEYj-2W\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144557Z
LAST-MODIFIED:20180213T144557Z
TRANSP:OPAQUE
END:VEVENT
* Giants vs. JetHawks
<2018-08-19 Sun 19:00-22:00>
:PROPERTIES:
:ID:       KMYipkF3uc90DmopOdInUZf6@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Giants vs. JetHawks Giants vs. JetHawks

Follow on MiLB First Pitch  https //stza.co/+xEYl-21

Shop  https //stza.co/+xEYl-V

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Giants vs. JetHawks
END:VALARM
DTSTART:20180820T000000Z
DTEND:20180820T030000Z
UID:KMYipkF3uc90DmopOdInUZf6@stanza.co
SUMMARY:Giants vs. JetHawks
DESCRIPTION:Giants vs. JetHawks\n\nFollow on MiLB First Pitch: https://stza.co/+xEYl-21\n\nShop: https://stza.co/+xEYl-V\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144557Z
LAST-MODIFIED:20180213T144557Z
TRANSP:OPAQUE
END:VEVENT
* Giants @ Rawhide
<2018-08-21 Tue>--<2018-08-20 Mon>
:PROPERTIES:
:ID:       N46NC-oAMsJ9OmFCl0N_zp0n@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Giants @ Rawhide Giants @ Rawhide

Follow on MiLB First Pitch  https //stza.co/+vM1Z-K

Shop  https //stza.co/+vM1Z-2_

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Giants @ Rawhide
END:VALARM
DTSTART;VALUE=DATE:20180821
DTEND;VALUE=DATE:20180821
UID:N46NC-oAMsJ9OmFCl0N_zp0n@stanza.co
SUMMARY:Giants @ Rawhide
DESCRIPTION:Giants @ Rawhide\n\nFollow on MiLB First Pitch: https://stza.co/+vM1Z-K\n\nShop: https://stza.co/+vM1Z-2_\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144557Z
LAST-MODIFIED:20180213T144557Z
TRANSP:OPAQUE
END:VEVENT
* Giants @ Rawhide
<2018-08-22 Wed>--<2018-08-21 Tue>
:PROPERTIES:
:ID:       Duj28RH-IP2ewP9SEM3zRAwz@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Giants @ Rawhide Giants @ Rawhide

Follow on MiLB First Pitch  https //stza.co/+vM1_-2I

Shop  https //stza.co/+vM1_-D

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Giants @ Rawhide
END:VALARM
DTSTART;VALUE=DATE:20180822
DTEND;VALUE=DATE:20180822
UID:Duj28RH-IP2ewP9SEM3zRAwz@stanza.co
SUMMARY:Giants @ Rawhide
DESCRIPTION:Giants @ Rawhide\n\nFollow on MiLB First Pitch: https://stza.co/+vM1_-2I\n\nShop: https://stza.co/+vM1_-D\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144557Z
LAST-MODIFIED:20180213T144557Z
TRANSP:OPAQUE
END:VEVENT
* Giants @ Rawhide
<2018-08-23 Thu>--<2018-08-22 Wed>
:PROPERTIES:
:ID:       xoF1ePy6H_J8_dmO9zxX6av0@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Giants @ Rawhide Giants @ Rawhide

Follow on MiLB First Pitch  https //stza.co/+vg71-3d

Shop  https //stza.co/+vg71-Z

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Giants @ Rawhide
END:VALARM
DTSTART;VALUE=DATE:20180823
DTEND;VALUE=DATE:20180823
UID:xoF1ePy6H_J8_dmO9zxX6av0@stanza.co
SUMMARY:Giants @ Rawhide
DESCRIPTION:Giants @ Rawhide\n\nFollow on MiLB First Pitch: https://stza.co/+vg71-3d\n\nShop: https://stza.co/+vg71-Z\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144557Z
LAST-MODIFIED:20180213T144557Z
TRANSP:OPAQUE
END:VEVENT
* Giants @ Nuts
<2018-08-24 Fri 21:05>--<2018-08-25 Sat 00:05>
:PROPERTIES:
:ID:       bo1ZC8gY-qV7zKRH2oiTnoxe@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Giants @ Nuts Giants @ Nuts

Follow on MiLB First Pitch  https //stza.co/+xz$x-2w

Shop  https //stza.co/+xz$x-13

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Giants @ Nuts
END:VALARM
DTSTART:20180825T020500Z
DTEND:20180825T050500Z
UID:bo1ZC8gY-qV7zKRH2oiTnoxe@stanza.co
SUMMARY:Giants @ Nuts
DESCRIPTION:Giants @ Nuts\n\nFollow on MiLB First Pitch: https://stza.co/+xz$x-2w\n\nShop: https://stza.co/+xz$x-13\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144557Z
LAST-MODIFIED:20180213T144557Z
TRANSP:OPAQUE
END:VEVENT
* Giants @ Nuts
<2018-08-25 Sat 21:05>--<2018-08-26 Sun 00:05>
:PROPERTIES:
:ID:       s_Rvj7FvOfNF2vYFic0ViTdS@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Giants @ Nuts Giants @ Nuts

Follow on MiLB First Pitch  https //stza.co/+xz$A-M

Shop  https //stza.co/+xz$A-1f

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Giants @ Nuts
END:VALARM
DTSTART:20180826T020500Z
DTEND:20180826T050500Z
UID:s_Rvj7FvOfNF2vYFic0ViTdS@stanza.co
SUMMARY:Giants @ Nuts
DESCRIPTION:Giants @ Nuts\n\nFollow on MiLB First Pitch: https://stza.co/+xz$A-M\n\nShop: https://stza.co/+xz$A-1f\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144557Z
LAST-MODIFIED:20180213T144557Z
TRANSP:OPAQUE
END:VEVENT
* Giants @ Nuts
<2018-08-26 Sun 20:05-23:05>
:PROPERTIES:
:ID:       PIWEvbQmpqOVGXSRBnvRc6EQ@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Giants @ Nuts Giants @ Nuts

Follow on MiLB First Pitch  https //stza.co/+xz$D-G

Shop  https //stza.co/+xz$D-z

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Giants @ Nuts
END:VALARM
DTSTART:20180827T010500Z
DTEND:20180827T040500Z
UID:PIWEvbQmpqOVGXSRBnvRc6EQ@stanza.co
SUMMARY:Giants @ Nuts
DESCRIPTION:Giants @ Nuts\n\nFollow on MiLB First Pitch: https://stza.co/+xz$D-G\n\nShop: https://stza.co/+xz$D-z\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144557Z
LAST-MODIFIED:20180213T144557Z
TRANSP:OPAQUE
END:VEVENT
* Giants @ Nuts
<2018-08-27 Mon 21:05>--<2018-08-28 Tue 00:05>
:PROPERTIES:
:ID:       hvNnw1OKm_ov-l_JDAUv7XH4@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Giants @ Nuts Giants @ Nuts

Follow on MiLB First Pitch  https //stza.co/+xz$G-2Y

Shop  https //stza.co/+xz$G-3_

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Giants @ Nuts
END:VALARM
DTSTART:20180828T020500Z
DTEND:20180828T050500Z
UID:hvNnw1OKm_ov-l_JDAUv7XH4@stanza.co
SUMMARY:Giants @ Nuts
DESCRIPTION:Giants @ Nuts\n\nFollow on MiLB First Pitch: https://stza.co/+xz$G-2Y\n\nShop: https://stza.co/+xz$G-3_\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144557Z
LAST-MODIFIED:20180213T144557Z
TRANSP:OPAQUE
END:VEVENT
* Giants vs. Ports
<2018-08-28 Tue 21:00>--<2018-08-29 Wed 00:00>
:PROPERTIES:
:ID:       HceyUzkZL3wCoLlltmCYl1Zt@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Giants vs. Ports Giants vs. Ports

Follow on MiLB First Pitch  https //stza.co/+xEYn-3M

Shop  https //stza.co/+xEYn-38

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Giants vs. Ports
END:VALARM
DTSTART:20180829T020000Z
DTEND:20180829T050000Z
UID:HceyUzkZL3wCoLlltmCYl1Zt@stanza.co
SUMMARY:Giants vs. Ports
DESCRIPTION:Giants vs. Ports\n\nFollow on MiLB First Pitch: https://stza.co/+xEYn-3M\n\nShop: https://stza.co/+xEYn-38\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144557Z
LAST-MODIFIED:20180213T144557Z
TRANSP:OPAQUE
END:VEVENT
* Giants vs. Ports
<2018-08-29 Wed 21:00>--<2018-08-30 Thu 00:00>
:PROPERTIES:
:ID:       F988Y_Qgeh8iMPewyew-kZqR@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Giants vs. Ports Giants vs. Ports

Follow on MiLB First Pitch  https //stza.co/+xEYp-1Y

Shop  https //stza.co/+xEYp-3r

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Giants vs. Ports
END:VALARM
DTSTART:20180830T020000Z
DTEND:20180830T050000Z
UID:F988Y_Qgeh8iMPewyew-kZqR@stanza.co
SUMMARY:Giants vs. Ports
DESCRIPTION:Giants vs. Ports\n\nFollow on MiLB First Pitch: https://stza.co/+xEYp-1Y\n\nShop: https://stza.co/+xEYp-3r\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144557Z
LAST-MODIFIED:20180213T144557Z
TRANSP:OPAQUE
END:VEVENT
* Giants vs. Ports
<2018-08-30 Thu 14:30-17:30>
:PROPERTIES:
:ID:       Qaq1Fa39bogYa1v6JUYGD23A@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Giants vs. Ports Giants vs. Ports

Follow on MiLB First Pitch  https //stza.co/+xEYs-3

Shop  https //stza.co/+xEYs-3P

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Giants vs. Ports
END:VALARM
DTSTART:20180830T193000Z
DTEND:20180830T223000Z
UID:Qaq1Fa39bogYa1v6JUYGD23A@stanza.co
SUMMARY:Giants vs. Ports
DESCRIPTION:Giants vs. Ports\n\nFollow on MiLB First Pitch: https://stza.co/+xEYs-3\n\nShop: https://stza.co/+xEYs-3P\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144557Z
LAST-MODIFIED:20180213T144557Z
TRANSP:OPAQUE
END:VEVENT
* Giants vs. Nuts
<2018-08-31 Fri 21:00>--<2018-09-01 Sat 00:00>
:PROPERTIES:
:ID:       K2nXRKkGaPW2lS0ypKy_JJ4Z@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Giants vs. Nuts Giants vs. Nuts

Follow on MiLB First Pitch  https //stza.co/+xEYu-1z

Shop  https //stza.co/+xEYu-2Z

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Giants vs. Nuts
END:VALARM
DTSTART:20180901T020000Z
DTEND:20180901T050000Z
UID:K2nXRKkGaPW2lS0ypKy_JJ4Z@stanza.co
SUMMARY:Giants vs. Nuts
DESCRIPTION:Giants vs. Nuts\n\nFollow on MiLB First Pitch: https://stza.co/+xEYu-1z\n\nShop: https://stza.co/+xEYu-2Z\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144557Z
LAST-MODIFIED:20180213T144557Z
TRANSP:OPAQUE
END:VEVENT
* Giants vs. Nuts
<2018-09-01 Sat 19:00-22:00>
:PROPERTIES:
:ID:       e1cJ5eDwjH9GxvITbnBOUNXV@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Giants vs. Nuts Giants vs. Nuts

Follow on MiLB First Pitch  https //stza.co/+xEYv-8

Shop  https //stza.co/+xEYv-X

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Giants vs. Nuts
END:VALARM
DTSTART:20180902T000000Z
DTEND:20180902T030000Z
UID:e1cJ5eDwjH9GxvITbnBOUNXV@stanza.co
SUMMARY:Giants vs. Nuts
DESCRIPTION:Giants vs. Nuts\n\nFollow on MiLB First Pitch: https://stza.co/+xEYv-8\n\nShop: https://stza.co/+xEYv-X\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144557Z
LAST-MODIFIED:20180213T144557Z
TRANSP:OPAQUE
END:VEVENT
* Giants vs. Nuts
<2018-09-02 Sun 15:00-18:00>
:PROPERTIES:
:ID:       CDv3wFFGt7f-m6iAhtDgfKyN@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Giants vs. Nuts Giants vs. Nuts

Follow on MiLB First Pitch  https //stza.co/+xEYy-2w

Shop  https //stza.co/+xEYy-3X

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Giants vs. Nuts
END:VALARM
DTSTART:20180902T200000Z
DTEND:20180902T230000Z
UID:CDv3wFFGt7f-m6iAhtDgfKyN@stanza.co
SUMMARY:Giants vs. Nuts
DESCRIPTION:Giants vs. Nuts\n\nFollow on MiLB First Pitch: https://stza.co/+xEYy-2w\n\nShop: https://stza.co/+xEYy-3X\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144557Z
LAST-MODIFIED:20180213T144557Z
TRANSP:OPAQUE
END:VEVENT
* Giants vs. Nuts
<2018-09-03 Mon 16:00-19:00>
:PROPERTIES:
:ID:       bCiekQGLT1RTCZ4gKLOlrInr@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Giants vs. Nuts Giants vs. Nuts

Follow on MiLB First Pitch  https //stza.co/+xEYA-a

Shop  https //stza.co/+xEYA-q

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Giants vs. Nuts
END:VALARM
DTSTART:20180903T210000Z
DTEND:20180904T000000Z
UID:bCiekQGLT1RTCZ4gKLOlrInr@stanza.co
SUMMARY:Giants vs. Nuts
DESCRIPTION:Giants vs. Nuts\n\nFollow on MiLB First Pitch: https://stza.co/+xEYA-a\n\nShop: https://stza.co/+xEYA-q\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144557Z
LAST-MODIFIED:20180213T144557Z
TRANSP:OPAQUE
END:VEVENT
