#+TITLE:       Main Google calendar entries
#+AUTHOR:      Eric S Fraga
#+EMAIL:       e.fraga@ucl.ac.uk
#+DESCRIPTION: converted using the ical2org awk script
#+CATEGORY:    google
#+STARTUP:     hidestars
#+STARTUP:     overview

* COMMENT original iCal preamble

* Hot Rods vs. Dragons
<2018-04-05 Thu 18:35-21:35>
:PROPERTIES:
:ID:       l2aDsieTKYt-90FkbUbYiE5L@stanza.co
:LOCATION: Throwback Thursday 
:STATUS:   CONFIRMED
:END:

Hot Rods vs. Dragons $2 Pepsi Products and $2 Domestic Beer

Exclusive 10th Season Shirt

Follow on MiLB First Pitch  https //stza.co/+vMNF-3c

Shop  https //stza.co/+vMNF-P

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Hot Rods vs. Dragons
END:VALARM
DTSTART:20180405T233500Z
DTEND:20180406T023500Z
UID:l2aDsieTKYt-90FkbUbYiE5L@stanza.co
SUMMARY:Hot Rods vs. Dragons
DESCRIPTION:$2 Pepsi Products and $2 Domestic Beer\n\nExclusive 10th Season Shirt\n\nFollow on MiLB First Pitch: https://stza.co/+vMNF-3c\n\nShop: https://stza.co/+vMNF-P\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Throwback Thursday 
STATUS:CONFIRMED
CREATED:20180213T144508Z
LAST-MODIFIED:20180213T144508Z
TRANSP:OPAQUE
END:VEVENT
* Hot Rods vs. Dragons
<2018-04-06 Fri 18:35-21:35>
:PROPERTIES:
:ID:       s-DSFbu_vWek2JgbZx2OCxcC@stanza.co
:LOCATION: Fireworks Friday
:STATUS:   CONFIRMED
:END:

Hot Rods vs. Dragons Enjoy post-game fireworks every Friday home game!

Dress like your favorite super hero!

Follow on MiLB First Pitch  https //stza.co/+vMNH-N

Shop  https //stza.co/+vMNH-1E

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Hot Rods vs. Dragons
END:VALARM
DTSTART:20180406T233500Z
DTEND:20180407T023500Z
UID:s-DSFbu_vWek2JgbZx2OCxcC@stanza.co
SUMMARY:Hot Rods vs. Dragons
DESCRIPTION:Enjoy post-game fireworks every Friday home game!\n\nDress like your favorite super hero!\n\nFollow on MiLB First Pitch: https://stza.co/+vMNH-N\n\nShop: https://stza.co/+vMNH-1E\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Fireworks Friday
STATUS:CONFIRMED
CREATED:20180213T144508Z
LAST-MODIFIED:20180213T144508Z
TRANSP:OPAQUE
END:VEVENT
* Hot Rods @ Dragons
<2018-04-07 Sat 18:00-21:00>
:PROPERTIES:
:ID:       PY1v4uJe0TEthg0bKivMKp3H@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Hot Rods @ Dragons Hot Rods @ Dragons

Follow on MiLB First Pitch  https //stza.co/+vMPW-e

Shop  https //stza.co/+vMPW-U

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Hot Rods @ Dragons
END:VALARM
DTSTART:20180407T230000Z
DTEND:20180408T020000Z
UID:PY1v4uJe0TEthg0bKivMKp3H@stanza.co
SUMMARY:Hot Rods @ Dragons
DESCRIPTION:Hot Rods @ Dragons\n\nFollow on MiLB First Pitch: https://stza.co/+vMPW-e\n\nShop: https://stza.co/+vMPW-U\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144508Z
LAST-MODIFIED:20180213T144508Z
TRANSP:OPAQUE
END:VEVENT
* Hot Rods @ Dragons
<2018-04-08 Sun 13:00-16:00>
:PROPERTIES:
:ID:       _ZjEURcDc2wTg2OzRXJNiNbK@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Hot Rods @ Dragons Hot Rods @ Dragons

Follow on MiLB First Pitch  https //stza.co/+vMPX-P

Shop  https //stza.co/+vMPX-3j

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Hot Rods @ Dragons
END:VALARM
DTSTART:20180408T180000Z
DTEND:20180408T210000Z
UID:_ZjEURcDc2wTg2OzRXJNiNbK@stanza.co
SUMMARY:Hot Rods @ Dragons
DESCRIPTION:Hot Rods @ Dragons\n\nFollow on MiLB First Pitch: https://stza.co/+vMPX-P\n\nShop: https://stza.co/+vMPX-3j\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144508Z
LAST-MODIFIED:20180213T144508Z
TRANSP:OPAQUE
END:VEVENT
* Hot Rods @ Cubs
<2018-04-09 Mon 18:05-21:05>
:PROPERTIES:
:ID:       4V4UT_arkVvEi2v3HX3HDXiy@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Hot Rods @ Cubs Hot Rods @ Cubs

Follow on MiLB First Pitch  https //stza.co/+vMQA-30

Shop  https //stza.co/+vMQA-1p

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Hot Rods @ Cubs
END:VALARM
DTSTART:20180409T230500Z
DTEND:20180410T020500Z
UID:4V4UT_arkVvEi2v3HX3HDXiy@stanza.co
SUMMARY:Hot Rods @ Cubs
DESCRIPTION:Hot Rods @ Cubs\n\nFollow on MiLB First Pitch: https://stza.co/+vMQA-30\n\nShop: https://stza.co/+vMQA-1p\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144508Z
LAST-MODIFIED:20180213T144508Z
TRANSP:OPAQUE
END:VEVENT
* Hot Rods @ Cubs
<2018-04-10 Tue 18:05-21:05>
:PROPERTIES:
:ID:       c9Lbqi8-fNUcTAi9qgrQzZpY@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Hot Rods @ Cubs Hot Rods @ Cubs

Follow on MiLB First Pitch  https //stza.co/+vMQB-u

Shop  https //stza.co/+vMQB-f

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Hot Rods @ Cubs
END:VALARM
DTSTART:20180410T230500Z
DTEND:20180411T020500Z
UID:c9Lbqi8-fNUcTAi9qgrQzZpY@stanza.co
SUMMARY:Hot Rods @ Cubs
DESCRIPTION:Hot Rods @ Cubs\n\nFollow on MiLB First Pitch: https://stza.co/+vMQB-u\n\nShop: https://stza.co/+vMQB-f\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144508Z
LAST-MODIFIED:20180213T144508Z
TRANSP:OPAQUE
END:VEVENT
* Hot Rods @ Cubs
<2018-04-11 Wed 18:05-21:05>
:PROPERTIES:
:ID:       d3kx6VR2oKrCBBToAUwmFTG0@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Hot Rods @ Cubs Hot Rods @ Cubs

Follow on MiLB First Pitch  https //stza.co/+vMQC-1T

Shop  https //stza.co/+vMQC-2A

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Hot Rods @ Cubs
END:VALARM
DTSTART:20180411T230500Z
DTEND:20180412T020500Z
UID:d3kx6VR2oKrCBBToAUwmFTG0@stanza.co
SUMMARY:Hot Rods @ Cubs
DESCRIPTION:Hot Rods @ Cubs\n\nFollow on MiLB First Pitch: https://stza.co/+vMQC-1T\n\nShop: https://stza.co/+vMQC-2A\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144508Z
LAST-MODIFIED:20180213T144508Z
TRANSP:OPAQUE
END:VEVENT
* Hot Rods @ Cubs
<2018-04-12 Thu 18:05-21:05>
:PROPERTIES:
:ID:       LeMeYbT-DJdpD4VayphFyE-X@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Hot Rods @ Cubs Hot Rods @ Cubs

Follow on MiLB First Pitch  https //stza.co/+vMQD-3d

Shop  https //stza.co/+vMQD-3L

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Hot Rods @ Cubs
END:VALARM
DTSTART:20180412T230500Z
DTEND:20180413T020500Z
UID:LeMeYbT-DJdpD4VayphFyE-X@stanza.co
SUMMARY:Hot Rods @ Cubs
DESCRIPTION:Hot Rods @ Cubs\n\nFollow on MiLB First Pitch: https://stza.co/+vMQD-3d\n\nShop: https://stza.co/+vMQD-3L\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144508Z
LAST-MODIFIED:20180213T144508Z
TRANSP:OPAQUE
END:VEVENT
* Hot Rods vs. TinCaps
<2018-04-13 Fri 18:35-21:35>
:PROPERTIES:
:ID:       w-KMPCal3csP-qpBtyFW7Q9w@stanza.co
:LOCATION: Fireworks Friday
:STATUS:   CONFIRMED
:END:

Hot Rods vs. TinCaps Enjoy post-game fireworks every Friday home game!

We're halfway to Halloween so dress up and be ready for some SpOoKy fun!

Follow on MiLB First Pitch  https //stza.co/+vMNJ-23

Shop  https //stza.co/+vMNJ-E

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Hot Rods vs. TinCaps
END:VALARM
DTSTART:20180413T233500Z
DTEND:20180414T023500Z
UID:w-KMPCal3csP-qpBtyFW7Q9w@stanza.co
SUMMARY:Hot Rods vs. TinCaps
DESCRIPTION:Enjoy post-game fireworks every Friday home game!\n\nWe're halfway to Halloween so dress up and be ready for some SpOoKy fun!\n\nFollow on MiLB First Pitch: https://stza.co/+vMNJ-23\n\nShop: https://stza.co/+vMNJ-E\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Fireworks Friday
STATUS:CONFIRMED
CREATED:20180213T144508Z
LAST-MODIFIED:20180213T144508Z
TRANSP:OPAQUE
END:VEVENT
* Hot Rods vs. TinCaps
<2018-04-14 Sat 18:35-21:35>
:PROPERTIES:
:ID:       5qXb3BY_FRhe36_veK2nZX4c@stanza.co
:LOCATION: Super Saturday
:STATUS:   CONFIRMED
:END:

Hot Rods vs. TinCaps Saturdays include specialty giveaways and entertainment! 



Follow on MiLB First Pitch  https //stza.co/+vMNK-3D

Shop  https //stza.co/+vMNK-3p

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Hot Rods vs. TinCaps
END:VALARM
DTSTART:20180414T233500Z
DTEND:20180415T023500Z
UID:5qXb3BY_FRhe36_veK2nZX4c@stanza.co
SUMMARY:Hot Rods vs. TinCaps
DESCRIPTION:Saturdays include specialty giveaways and entertainment! \n\n\n\nFollow on MiLB First Pitch: https://stza.co/+vMNK-3D\n\nShop: https://stza.co/+vMNK-3p\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Super Saturday
STATUS:CONFIRMED
CREATED:20180213T144508Z
LAST-MODIFIED:20180213T144508Z
TRANSP:OPAQUE
END:VEVENT
* Hot Rods vs. TinCaps
<2018-04-15 Sun 14:05-17:05>
:PROPERTIES:
:ID:       QL4tsxI3CXpILw9XLNKAZB7P@stanza.co
:LOCATION: Sunday Funday
:STATUS:   CONFIRMED
:END:

Hot Rods vs. TinCaps Join us for Sunday Funday! First 500 kids eat free with paid ticket! Postgame autographs and postgame kids run the bases! 

Follow on MiLB First Pitch  https //stza.co/+vMNM-3Z

Shop  https //stza.co/+vMNM-1D

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Hot Rods vs. TinCaps
END:VALARM
DTSTART:20180415T190500Z
DTEND:20180415T220500Z
UID:QL4tsxI3CXpILw9XLNKAZB7P@stanza.co
SUMMARY:Hot Rods vs. TinCaps
DESCRIPTION:Join us for Sunday Funday! First 500 kids eat free with paid ticket! Postgame autographs and postgame kids run the bases! \n\nFollow on MiLB First Pitch: https://stza.co/+vMNM-3Z\n\nShop: https://stza.co/+vMNM-1D\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Sunday Funday
STATUS:CONFIRMED
CREATED:20180213T144508Z
LAST-MODIFIED:20180213T144508Z
TRANSP:OPAQUE
END:VEVENT
* Hot Rods @ Whitecaps
<2018-04-17 Tue 17:35-20:35>
:PROPERTIES:
:ID:       g8O2YLqr2d6kzof1FdktE6u3@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Hot Rods @ Whitecaps Hot Rods @ Whitecaps

Follow on MiLB First Pitch  https //stza.co/+vMQJ-1D

Shop  https //stza.co/+vMQJ-z

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Hot Rods @ Whitecaps
END:VALARM
DTSTART:20180417T223500Z
DTEND:20180418T013500Z
UID:g8O2YLqr2d6kzof1FdktE6u3@stanza.co
SUMMARY:Hot Rods @ Whitecaps
DESCRIPTION:Hot Rods @ Whitecaps\n\nFollow on MiLB First Pitch: https://stza.co/+vMQJ-1D\n\nShop: https://stza.co/+vMQJ-z\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144508Z
LAST-MODIFIED:20180213T144508Z
TRANSP:OPAQUE
END:VEVENT
* Hot Rods @ Whitecaps
<2018-04-18 Wed 11:00-14:00>
:PROPERTIES:
:ID:       VXPVp9UMVEjkUX3qVVtK7y5Z@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Hot Rods @ Whitecaps Hot Rods @ Whitecaps

Follow on MiLB First Pitch  https //stza.co/+vMQK-2i

Shop  https //stza.co/+vMQK-x

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Hot Rods @ Whitecaps
END:VALARM
DTSTART:20180418T160000Z
DTEND:20180418T190000Z
UID:VXPVp9UMVEjkUX3qVVtK7y5Z@stanza.co
SUMMARY:Hot Rods @ Whitecaps
DESCRIPTION:Hot Rods @ Whitecaps\n\nFollow on MiLB First Pitch: https://stza.co/+vMQK-2i\n\nShop: https://stza.co/+vMQK-x\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144508Z
LAST-MODIFIED:20180213T144508Z
TRANSP:OPAQUE
END:VEVENT
* Hot Rods @ Whitecaps
<2018-04-19 Thu 17:35-20:35>
:PROPERTIES:
:ID:       b9L9laPD3xZL-o3qT418LMrG@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Hot Rods @ Whitecaps Hot Rods @ Whitecaps

Follow on MiLB First Pitch  https //stza.co/+vMQL-32

Shop  https //stza.co/+vMQL-R

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Hot Rods @ Whitecaps
END:VALARM
DTSTART:20180419T223500Z
DTEND:20180420T013500Z
UID:b9L9laPD3xZL-o3qT418LMrG@stanza.co
SUMMARY:Hot Rods @ Whitecaps
DESCRIPTION:Hot Rods @ Whitecaps\n\nFollow on MiLB First Pitch: https://stza.co/+vMQL-32\n\nShop: https://stza.co/+vMQL-R\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144508Z
LAST-MODIFIED:20180213T144508Z
TRANSP:OPAQUE
END:VEVENT
* Hot Rods @ Captains
<2018-04-20 Fri 17:30-20:30>
:PROPERTIES:
:ID:       MeIDpWxFnxiZqYF37Zrz7VIu@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Hot Rods @ Captains Hot Rods @ Captains

Follow on MiLB First Pitch  https //stza.co/+xBj3-16

Shop  https //stza.co/+xBj3-2p

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Hot Rods @ Captains
END:VALARM
DTSTART:20180420T223000Z
DTEND:20180421T013000Z
UID:MeIDpWxFnxiZqYF37Zrz7VIu@stanza.co
SUMMARY:Hot Rods @ Captains
DESCRIPTION:Hot Rods @ Captains\n\nFollow on MiLB First Pitch: https://stza.co/+xBj3-16\n\nShop: https://stza.co/+xBj3-2p\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144508Z
LAST-MODIFIED:20180213T144508Z
TRANSP:OPAQUE
END:VEVENT
* Hot Rods @ Captains
<2018-04-21 Sat 17:30-20:30>
:PROPERTIES:
:ID:       RqPkgu6mJUdtqEvoa26oFjRD@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Hot Rods @ Captains Hot Rods @ Captains

Follow on MiLB First Pitch  https //stza.co/+xBj6-1P

Shop  https //stza.co/+xBj6-1k

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Hot Rods @ Captains
END:VALARM
DTSTART:20180421T223000Z
DTEND:20180422T013000Z
UID:RqPkgu6mJUdtqEvoa26oFjRD@stanza.co
SUMMARY:Hot Rods @ Captains
DESCRIPTION:Hot Rods @ Captains\n\nFollow on MiLB First Pitch: https://stza.co/+xBj6-1P\n\nShop: https://stza.co/+xBj6-1k\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144508Z
LAST-MODIFIED:20180213T144508Z
TRANSP:OPAQUE
END:VEVENT
* Hot Rods @ Captains
<2018-04-22 Sun 12:30-15:30>
:PROPERTIES:
:ID:       -SbuZn0DBEbn0_1sADuuQuGa@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Hot Rods @ Captains Hot Rods @ Captains

Follow on MiLB First Pitch  https //stza.co/+xBj9-3N

Shop  https //stza.co/+xBj9-3_

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Hot Rods @ Captains
END:VALARM
DTSTART:20180422T173000Z
DTEND:20180422T203000Z
UID:-SbuZn0DBEbn0_1sADuuQuGa@stanza.co
SUMMARY:Hot Rods @ Captains
DESCRIPTION:Hot Rods @ Captains\n\nFollow on MiLB First Pitch: https://stza.co/+xBj9-3N\n\nShop: https://stza.co/+xBj9-3_\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144508Z
LAST-MODIFIED:20180213T144508Z
TRANSP:OPAQUE
END:VEVENT
* Hot Rods vs. Cubs
<2018-04-23 Mon 18:35-21:35>
:PROPERTIES:
:ID:       2Zru5uP6W1FL7KiKVwzpKXRy@stanza.co
:LOCATION: Buck Monday
:STATUS:   CONFIRMED
:END:

Hot Rods vs. Cubs $1 Popcorn and $1 Pepsi Products 

Follow on MiLB First Pitch  https //stza.co/+vMNP-3C

Shop  https //stza.co/+vMNP-2b

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Hot Rods vs. Cubs
END:VALARM
DTSTART:20180423T233500Z
DTEND:20180424T023500Z
UID:2Zru5uP6W1FL7KiKVwzpKXRy@stanza.co
SUMMARY:Hot Rods vs. Cubs
DESCRIPTION:$1 Popcorn and $1 Pepsi Products \n\nFollow on MiLB First Pitch: https://stza.co/+vMNP-3C\n\nShop: https://stza.co/+vMNP-2b\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Buck Monday
STATUS:CONFIRMED
CREATED:20180213T144508Z
LAST-MODIFIED:20180213T144508Z
TRANSP:OPAQUE
END:VEVENT
* Hot Rods vs. Cubs
<2018-04-24 Tue 18:35-21:35>
:PROPERTIES:
:ID:       edk3fBwL3y630rvRNQFk3h6k@stanza.co
:LOCATION: Tail Waggin' Tuesday
:STATUS:   CONFIRMED
:END:

Hot Rods vs. Cubs $1 Hot Dogs. Dogs are welcome EVERY Tuesday home game and get in FREE with their owner.



Follow on MiLB First Pitch  https //stza.co/+vMNQ-3m

Shop  https //stza.co/+vMNQ-2O

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Hot Rods vs. Cubs
END:VALARM
DTSTART:20180424T233500Z
DTEND:20180425T023500Z
UID:edk3fBwL3y630rvRNQFk3h6k@stanza.co
SUMMARY:Hot Rods vs. Cubs
DESCRIPTION:$1 Hot Dogs. Dogs are welcome EVERY Tuesday home game and get in FREE with their owner.\n\n\n\nFollow on MiLB First Pitch: https://stza.co/+vMNQ-3m\n\nShop: https://stza.co/+vMNQ-2O\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Tail Waggin' Tuesday
STATUS:CONFIRMED
CREATED:20180213T144508Z
LAST-MODIFIED:20180213T144508Z
TRANSP:OPAQUE
END:VEVENT
* Hot Rods vs. Cubs
<2018-04-25 Wed 18:35-21:35>
:PROPERTIES:
:ID:       w6-ebgcNiIgNFZtJMGG8VRu2@stanza.co
:LOCATION: Winning Wednesday
:STATUS:   CONFIRMED
:END:

Hot Rods vs. Cubs Play baseball bingo and have the chance to win great prizes! 

Follow on MiLB First Pitch  https //stza.co/+vMNS-x

Shop  https //stza.co/+vMNS-X

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Hot Rods vs. Cubs
END:VALARM
DTSTART:20180425T233500Z
DTEND:20180426T023500Z
UID:w6-ebgcNiIgNFZtJMGG8VRu2@stanza.co
SUMMARY:Hot Rods vs. Cubs
DESCRIPTION:Play baseball bingo and have the chance to win great prizes! \n\nFollow on MiLB First Pitch: https://stza.co/+vMNS-x\n\nShop: https://stza.co/+vMNS-X\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Winning Wednesday
STATUS:CONFIRMED
CREATED:20180213T144508Z
LAST-MODIFIED:20180213T144508Z
TRANSP:OPAQUE
END:VEVENT
* Hot Rods vs. Cubs
<2018-04-26 Thu 10:35-13:35>
:PROPERTIES:
:ID:       6-9bVGSTjkazT_obVcgwXxd0@stanza.co
:LOCATION: Throwback Thursday 
:STATUS:   CONFIRMED
:END:

Hot Rods vs. Cubs $2 Pepsi Products and $2 Domestic Beer



Follow on MiLB First Pitch  https //stza.co/+vMNU-p

Shop  https //stza.co/+vMNU-2q

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Hot Rods vs. Cubs
END:VALARM
DTSTART:20180426T153500Z
DTEND:20180426T183500Z
UID:6-9bVGSTjkazT_obVcgwXxd0@stanza.co
SUMMARY:Hot Rods vs. Cubs
DESCRIPTION:$2 Pepsi Products and $2 Domestic Beer\n\n\n\nFollow on MiLB First Pitch: https://stza.co/+vMNU-p\n\nShop: https://stza.co/+vMNU-2q\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Throwback Thursday 
STATUS:CONFIRMED
CREATED:20180213T144508Z
LAST-MODIFIED:20180213T144508Z
TRANSP:OPAQUE
END:VEVENT
* Hot Rods vs. Captains
<2018-04-27 Fri 18:35-21:35>
:PROPERTIES:
:ID:       vZpLJ2TqrCA-e4-kGPRLvxFM@stanza.co
:LOCATION: Fireworks Friday
:STATUS:   CONFIRMED
:END:

Hot Rods vs. Captains Enjoy post-game fireworks every Friday home game!

Dress up as your favorite princess or pirate and enjoy the game! Be sure to stay for post-game fireworks! Free TV Friday sponsored by McGown TV Sales and Service. 

Follow on MiLB First Pitch  https //stza.co/+vMNW-1W

Shop  https //stza.co/+vMNW-3f

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Hot Rods vs. Captains
END:VALARM
DTSTART:20180427T233500Z
DTEND:20180428T023500Z
UID:vZpLJ2TqrCA-e4-kGPRLvxFM@stanza.co
SUMMARY:Hot Rods vs. Captains
DESCRIPTION:Enjoy post-game fireworks every Friday home game!\n\nDress up as your favorite princess or pirate and enjoy the game! Be sure to stay for post-game fireworks! Free TV Friday sponsored by McGown TV Sales and Service. \n\nFollow on MiLB First Pitch: https://stza.co/+vMNW-1W\n\nShop: https://stza.co/+vMNW-3f\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Fireworks Friday
STATUS:CONFIRMED
CREATED:20180213T144508Z
LAST-MODIFIED:20180213T144508Z
TRANSP:OPAQUE
END:VEVENT
* Hot Rods vs. Captains
<2018-04-28 Sat 18:35-21:35>
:PROPERTIES:
:ID:       Gc1o98VDzdqkWl4AfpM_6Dkd@stanza.co
:LOCATION: Super Saturday
:STATUS:   CONFIRMED
:END:

Hot Rods vs. Captains Saturdays include specialty giveaways and entertainment! 

The Bowling Green Bootleggers are back! Join us for an exclusive Bootleggers hat giveaway and a jersey auction benefiting Stuff the Bus! 

Follow on MiLB First Pitch  https //stza.co/+vMNY-e

Shop  https //stza.co/+vMNY-8

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Hot Rods vs. Captains
END:VALARM
DTSTART:20180428T233500Z
DTEND:20180429T023500Z
UID:Gc1o98VDzdqkWl4AfpM_6Dkd@stanza.co
SUMMARY:Hot Rods vs. Captains
DESCRIPTION:Saturdays include specialty giveaways and entertainment! \n\nThe Bowling Green Bootleggers are back! Join us for an exclusive Bootleggers hat giveaway and a jersey auction benefiting Stuff the Bus! \n\nFollow on MiLB First Pitch: https://stza.co/+vMNY-e\n\nShop: https://stza.co/+vMNY-8\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Super Saturday
STATUS:CONFIRMED
CREATED:20180213T144508Z
LAST-MODIFIED:20180213T144508Z
TRANSP:OPAQUE
END:VEVENT
* Hot Rods vs. Captains
<2018-04-29 Sun 14:05-17:05>
:PROPERTIES:
:ID:       JJt-GO_32jCJNDkq1Nrj3U47@stanza.co
:LOCATION: Sunday Funday
:STATUS:   CONFIRMED
:END:

Hot Rods vs. Captains Join us for Sunday Funday! First 500 kids eat free with paid ticket! Postgame autographs and postgame kids run the bases! 

Follow on MiLB First Pitch  https //stza.co/+vMN$-2z

Shop  https //stza.co/+vMN$-4

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Hot Rods vs. Captains
END:VALARM
DTSTART:20180429T190500Z
DTEND:20180429T220500Z
UID:JJt-GO_32jCJNDkq1Nrj3U47@stanza.co
SUMMARY:Hot Rods vs. Captains
DESCRIPTION:Join us for Sunday Funday! First 500 kids eat free with paid ticket! Postgame autographs and postgame kids run the bases! \n\nFollow on MiLB First Pitch: https://stza.co/+vMN$-2z\n\nShop: https://stza.co/+vMN$-4\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Sunday Funday
STATUS:CONFIRMED
CREATED:20180213T144508Z
LAST-MODIFIED:20180213T144508Z
TRANSP:OPAQUE
END:VEVENT
* Hot Rods @ LumberKings
<2018-05-01 Tue 18:30-21:30>
:PROPERTIES:
:ID:       mkX9P_eTH9e1em2TOas692Tg@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Hot Rods @ LumberKings Hot Rods @ LumberKings

Follow on MiLB First Pitch  https //stza.co/+vMPT-1u

Shop  https //stza.co/+vMPT-3T

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Hot Rods @ LumberKings
END:VALARM
DTSTART:20180501T233000Z
DTEND:20180502T023000Z
UID:mkX9P_eTH9e1em2TOas692Tg@stanza.co
SUMMARY:Hot Rods @ LumberKings
DESCRIPTION:Hot Rods @ LumberKings\n\nFollow on MiLB First Pitch: https://stza.co/+vMPT-1u\n\nShop: https://stza.co/+vMPT-3T\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144508Z
LAST-MODIFIED:20180213T144508Z
TRANSP:OPAQUE
END:VEVENT
* Hot Rods @ LumberKings
<2018-05-02 Wed>--<2018-05-01 Tue>
:PROPERTIES:
:ID:       _E-hhNbus_O26a1kv24nUi8Q@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Hot Rods @ LumberKings Hot Rods @ LumberKings

Follow on MiLB First Pitch  https //stza.co/+vMPU-33

Shop  https //stza.co/+vMPU-3Y

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Hot Rods @ LumberKings
END:VALARM
DTSTART;VALUE=DATE:20180502
DTEND;VALUE=DATE:20180502
UID:_E-hhNbus_O26a1kv24nUi8Q@stanza.co
SUMMARY:Hot Rods @ LumberKings
DESCRIPTION:Hot Rods @ LumberKings\n\nFollow on MiLB First Pitch: https://stza.co/+vMPU-33\n\nShop: https://stza.co/+vMPU-3Y\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144508Z
LAST-MODIFIED:20180213T144508Z
TRANSP:OPAQUE
END:VEVENT
* Hot Rods @ LumberKings
<2018-05-03 Thu 18:30-21:30>
:PROPERTIES:
:ID:       BtF9nlGpneuYTVKSM27A37wW@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Hot Rods @ LumberKings Hot Rods @ LumberKings

Follow on MiLB First Pitch  https //stza.co/+xVYf-37

Shop  https //stza.co/+xVYf-8

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Hot Rods @ LumberKings
END:VALARM
DTSTART:20180503T233000Z
DTEND:20180504T023000Z
UID:BtF9nlGpneuYTVKSM27A37wW@stanza.co
SUMMARY:Hot Rods @ LumberKings
DESCRIPTION:Hot Rods @ LumberKings\n\nFollow on MiLB First Pitch: https://stza.co/+xVYf-37\n\nShop: https://stza.co/+xVYf-8\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144508Z
LAST-MODIFIED:20180213T144508Z
TRANSP:OPAQUE
END:VEVENT
* Hot Rods @ Bees
<2018-05-04 Fri 18:30-21:30>
:PROPERTIES:
:ID:       HFyeSz6jTs48E5_Qv54-sMeg@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Hot Rods @ Bees Hot Rods @ Bees

Follow on MiLB First Pitch  https //stza.co/+xBj0-26

Shop  https //stza.co/+xBj0-2J

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Hot Rods @ Bees
END:VALARM
DTSTART:20180504T233000Z
DTEND:20180505T023000Z
UID:HFyeSz6jTs48E5_Qv54-sMeg@stanza.co
SUMMARY:Hot Rods @ Bees
DESCRIPTION:Hot Rods @ Bees\n\nFollow on MiLB First Pitch: https://stza.co/+xBj0-26\n\nShop: https://stza.co/+xBj0-2J\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144508Z
LAST-MODIFIED:20180213T144508Z
TRANSP:OPAQUE
END:VEVENT
* Hot Rods @ Bees
<2018-05-05 Sat 17:00-20:00>
:PROPERTIES:
:ID:       hfD4KTVpOEYUw_mLJu13deNJ@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Hot Rods @ Bees Hot Rods @ Bees

Follow on MiLB First Pitch  https //stza.co/+xBj1-1V

Shop  https //stza.co/+xBj1-3A

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Hot Rods @ Bees
END:VALARM
DTSTART:20180505T220000Z
DTEND:20180506T010000Z
UID:hfD4KTVpOEYUw_mLJu13deNJ@stanza.co
SUMMARY:Hot Rods @ Bees
DESCRIPTION:Hot Rods @ Bees\n\nFollow on MiLB First Pitch: https://stza.co/+xBj1-1V\n\nShop: https://stza.co/+xBj1-3A\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144508Z
LAST-MODIFIED:20180213T144508Z
TRANSP:OPAQUE
END:VEVENT
* Hot Rods @ Bees
<2018-05-06 Sun 14:00-17:00>
:PROPERTIES:
:ID:       dGaho4O706TxEyEL6K48mu6A@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Hot Rods @ Bees Hot Rods @ Bees

Follow on MiLB First Pitch  https //stza.co/+xBj2-3E

Shop  https //stza.co/+xBj2-21

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Hot Rods @ Bees
END:VALARM
DTSTART:20180506T190000Z
DTEND:20180506T220000Z
UID:dGaho4O706TxEyEL6K48mu6A@stanza.co
SUMMARY:Hot Rods @ Bees
DESCRIPTION:Hot Rods @ Bees\n\nFollow on MiLB First Pitch: https://stza.co/+xBj2-3E\n\nShop: https://stza.co/+xBj2-21\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144508Z
LAST-MODIFIED:20180213T144508Z
TRANSP:OPAQUE
END:VEVENT
* Hot Rods vs. Chiefs
<2018-05-07 Mon 18:35-21:35>
:PROPERTIES:
:ID:       M_qNEC3DnYqgyLixggTldvVI@stanza.co
:LOCATION: Buck Monday
:STATUS:   CONFIRMED
:END:

Hot Rods vs. Chiefs $1 Popcorn and $1 Pepsi Products 

Follow on MiLB First Pitch  https //stza.co/+vMO1-b

Shop  https //stza.co/+vMO1-1D

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Hot Rods vs. Chiefs
END:VALARM
DTSTART:20180507T233500Z
DTEND:20180508T023500Z
UID:M_qNEC3DnYqgyLixggTldvVI@stanza.co
SUMMARY:Hot Rods vs. Chiefs
DESCRIPTION:$1 Popcorn and $1 Pepsi Products \n\nFollow on MiLB First Pitch: https://stza.co/+vMO1-b\n\nShop: https://stza.co/+vMO1-1D\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Buck Monday
STATUS:CONFIRMED
CREATED:20180213T144508Z
LAST-MODIFIED:20180213T144508Z
TRANSP:OPAQUE
END:VEVENT
* Hot Rods vs. Chiefs
<2018-05-08 Tue 18:35-21:35>
:PROPERTIES:
:ID:       d408vxkXG6wC07N85sDBeLib@stanza.co
:LOCATION: Tail Waggin' Tuesday
:STATUS:   CONFIRMED
:END:

Hot Rods vs. Chiefs $1 Hot Dogs. Dogs are welcome EVERY Tuesday home game and get in FREE with their owner.

Join us as the Bowling Green Bootleggers 'Battle for the Barrel' against the Peoria Distillers! 

Follow on MiLB First Pitch  https //stza.co/+vMO3-17

Shop  https //stza.co/+vMO3-7

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Hot Rods vs. Chiefs
END:VALARM
DTSTART:20180508T233500Z
DTEND:20180509T023500Z
UID:d408vxkXG6wC07N85sDBeLib@stanza.co
SUMMARY:Hot Rods vs. Chiefs
DESCRIPTION:$1 Hot Dogs. Dogs are welcome EVERY Tuesday home game and get in FREE with their owner.\n\nJoin us as the Bowling Green Bootleggers 'Battle for the Barrel' against the Peoria Distillers! \n\nFollow on MiLB First Pitch: https://stza.co/+vMO3-17\n\nShop: https://stza.co/+vMO3-7\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Tail Waggin' Tuesday
STATUS:CONFIRMED
CREATED:20180213T144508Z
LAST-MODIFIED:20180213T144508Z
TRANSP:OPAQUE
END:VEVENT
* Hot Rods vs. Chiefs
<2018-05-09 Wed 10:35-13:35>
:PROPERTIES:
:ID:       5yvbX3eNcIJKUSyLhONCTmDg@stanza.co
:LOCATION: Winning Wednesday
:STATUS:   CONFIRMED
:END:

Hot Rods vs. Chiefs Play baseball bingo and have the chance to win great prizes! 



Follow on MiLB First Pitch  https //stza.co/+vMO4-1L

Shop  https //stza.co/+vMO4-1C

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Hot Rods vs. Chiefs
END:VALARM
DTSTART:20180509T153500Z
DTEND:20180509T183500Z
UID:5yvbX3eNcIJKUSyLhONCTmDg@stanza.co
SUMMARY:Hot Rods vs. Chiefs
DESCRIPTION:Play baseball bingo and have the chance to win great prizes! \n\n\n\nFollow on MiLB First Pitch: https://stza.co/+vMO4-1L\n\nShop: https://stza.co/+vMO4-1C\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Winning Wednesday
STATUS:CONFIRMED
CREATED:20180213T144508Z
LAST-MODIFIED:20180213T144508Z
TRANSP:OPAQUE
END:VEVENT
* Hot Rods vs. Kernels
<2018-05-10 Thu 18:35-21:35>
:PROPERTIES:
:ID:       rUkac8CCXQmKm2QeDjsZ-PO9@stanza.co
:LOCATION: Throwback Thursday 
:STATUS:   CONFIRMED
:END:

Hot Rods vs. Kernels $2 Pepsi Products and $2 Domestic Beer

Follow on MiLB First Pitch  https //stza.co/+vMO7-3V

Shop  https //stza.co/+vMO7-2u

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Hot Rods vs. Kernels
END:VALARM
DTSTART:20180510T233500Z
DTEND:20180511T023500Z
UID:rUkac8CCXQmKm2QeDjsZ-PO9@stanza.co
SUMMARY:Hot Rods vs. Kernels
DESCRIPTION:$2 Pepsi Products and $2 Domestic Beer\n\nFollow on MiLB First Pitch: https://stza.co/+vMO7-3V\n\nShop: https://stza.co/+vMO7-2u\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Throwback Thursday 
STATUS:CONFIRMED
CREATED:20180213T144508Z
LAST-MODIFIED:20180213T144508Z
TRANSP:OPAQUE
END:VEVENT
* Hot Rods vs. Kernels
<2018-05-11 Fri 18:35-21:35>
:PROPERTIES:
:ID:       s9QUgV21GgzwqgGcmGfXwGQg@stanza.co
:LOCATION: Fireworks Friday
:STATUS:   CONFIRMED
:END:

Hot Rods vs. Kernels Enjoy post-game fireworks every Friday home game!

Join us for Faith and Family Night! Stay for the post-game fireworks presented by Norton Children's Hospital and post-game concert by Austin French sponsored by Christian Family Radio! 

Follow on MiLB First Pitch  https //stza.co/+vMO8-3l

Shop  https //stza.co/+vMO8-23

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Hot Rods vs. Kernels
END:VALARM
DTSTART:20180511T233500Z
DTEND:20180512T023500Z
UID:s9QUgV21GgzwqgGcmGfXwGQg@stanza.co
SUMMARY:Hot Rods vs. Kernels
DESCRIPTION:Enjoy post-game fireworks every Friday home game!\n\nJoin us for Faith and Family Night! Stay for the post-game fireworks presented by Norton Children's Hospital and post-game concert by Austin French sponsored by Christian Family Radio! \n\nFollow on MiLB First Pitch: https://stza.co/+vMO8-3l\n\nShop: https://stza.co/+vMO8-23\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Fireworks Friday
STATUS:CONFIRMED
CREATED:20180213T144508Z
LAST-MODIFIED:20180213T144508Z
TRANSP:OPAQUE
END:VEVENT
* Hot Rods vs. Kernels
<2018-05-12 Sat 18:35-21:35>
:PROPERTIES:
:ID:       SIGyJvrexFD04KCH3MeZlZ8i@stanza.co
:LOCATION: Super Saturday
:STATUS:   CONFIRMED
:END:

Hot Rods vs. Kernels Saturdays include specialty giveaways and entertainment! 

Join us in the fight against cancer! Pregame yoga, tote bag giveaway, jersey auction, and more! Wear pink to show your support!

Follow on MiLB First Pitch  https //stza.co/+vMOb-1U

Shop  https //stza.co/+vMOb-3J

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Hot Rods vs. Kernels
END:VALARM
DTSTART:20180512T233500Z
DTEND:20180513T023500Z
UID:SIGyJvrexFD04KCH3MeZlZ8i@stanza.co
SUMMARY:Hot Rods vs. Kernels
DESCRIPTION:Saturdays include specialty giveaways and entertainment! \n\nJoin us in the fight against cancer! Pregame yoga, tote bag giveaway, jersey auction, and more! Wear pink to show your support!\n\nFollow on MiLB First Pitch: https://stza.co/+vMOb-1U\n\nShop: https://stza.co/+vMOb-3J\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Super Saturday
STATUS:CONFIRMED
CREATED:20180213T144508Z
LAST-MODIFIED:20180213T144508Z
TRANSP:OPAQUE
END:VEVENT
* Hot Rods @ Loons
<2018-05-14 Mon 18:05-21:05>
:PROPERTIES:
:ID:       AL8ykil0QfawY5LWmjQuW0s5@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Hot Rods @ Loons Hot Rods @ Loons

Follow on MiLB First Pitch  https //stza.co/+vMQd-2t

Shop  https //stza.co/+vMQd-2c

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Hot Rods @ Loons
END:VALARM
DTSTART:20180514T230500Z
DTEND:20180515T020500Z
UID:AL8ykil0QfawY5LWmjQuW0s5@stanza.co
SUMMARY:Hot Rods @ Loons
DESCRIPTION:Hot Rods @ Loons\n\nFollow on MiLB First Pitch: https://stza.co/+vMQd-2t\n\nShop: https://stza.co/+vMQd-2c\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144508Z
LAST-MODIFIED:20180213T144508Z
TRANSP:OPAQUE
END:VEVENT
* Hot Rods @ Loons
<2018-05-15 Tue 09:35-12:35>
:PROPERTIES:
:ID:       pCLFrjemKgSp3OrhycTgI9jP@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Hot Rods @ Loons Hot Rods @ Loons

Follow on MiLB First Pitch  https //stza.co/+vMQe-1a

Shop  https //stza.co/+vMQe-K

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Hot Rods @ Loons
END:VALARM
DTSTART:20180515T143500Z
DTEND:20180515T173500Z
UID:pCLFrjemKgSp3OrhycTgI9jP@stanza.co
SUMMARY:Hot Rods @ Loons
DESCRIPTION:Hot Rods @ Loons\n\nFollow on MiLB First Pitch: https://stza.co/+vMQe-1a\n\nShop: https://stza.co/+vMQe-K\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144508Z
LAST-MODIFIED:20180213T144508Z
TRANSP:OPAQUE
END:VEVENT
* Hot Rods @ Loons
<2018-05-16 Wed 18:05-21:05>
:PROPERTIES:
:ID:       ds9EhlEfejuvOGYn1ZlbI1YL@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Hot Rods @ Loons Hot Rods @ Loons

Follow on MiLB First Pitch  https //stza.co/+vMQf-33

Shop  https //stza.co/+vMQf-2h

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Hot Rods @ Loons
END:VALARM
DTSTART:20180516T230500Z
DTEND:20180517T020500Z
UID:ds9EhlEfejuvOGYn1ZlbI1YL@stanza.co
SUMMARY:Hot Rods @ Loons
DESCRIPTION:Hot Rods @ Loons\n\nFollow on MiLB First Pitch: https://stza.co/+vMQf-33\n\nShop: https://stza.co/+vMQf-2h\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144508Z
LAST-MODIFIED:20180213T144508Z
TRANSP:OPAQUE
END:VEVENT
* Hot Rods @ Loons
<2018-05-17 Thu 18:05-21:05>
:PROPERTIES:
:ID:       hC48iW1yKKkUd2V4eNhVpAnL@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Hot Rods @ Loons Hot Rods @ Loons

Follow on MiLB First Pitch  https //stza.co/+vMQg-G

Shop  https //stza.co/+vMQg-3q

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Hot Rods @ Loons
END:VALARM
DTSTART:20180517T230500Z
DTEND:20180518T020500Z
UID:hC48iW1yKKkUd2V4eNhVpAnL@stanza.co
SUMMARY:Hot Rods @ Loons
DESCRIPTION:Hot Rods @ Loons\n\nFollow on MiLB First Pitch: https://stza.co/+vMQg-G\n\nShop: https://stza.co/+vMQg-3q\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144508Z
LAST-MODIFIED:20180213T144508Z
TRANSP:OPAQUE
END:VEVENT
* Hot Rods @ Lugnuts
<2018-05-18 Fri 18:05-21:05>
:PROPERTIES:
:ID:       fVWvVzK8_-rPkxQk8PddeMTk@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Hot Rods @ Lugnuts Hot Rods @ Lugnuts

Follow on MiLB First Pitch  https //stza.co/+vMQt-2W

Shop  https //stza.co/+vMQt-2f

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Hot Rods @ Lugnuts
END:VALARM
DTSTART:20180518T230500Z
DTEND:20180519T020500Z
UID:fVWvVzK8_-rPkxQk8PddeMTk@stanza.co
SUMMARY:Hot Rods @ Lugnuts
DESCRIPTION:Hot Rods @ Lugnuts\n\nFollow on MiLB First Pitch: https://stza.co/+vMQt-2W\n\nShop: https://stza.co/+vMQt-2f\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144508Z
LAST-MODIFIED:20180213T144508Z
TRANSP:OPAQUE
END:VEVENT
* Hot Rods @ Lugnuts
<2018-05-19 Sat 18:05-21:05>
:PROPERTIES:
:ID:       LyPrda6FUEtYEVzSVLgHPj0k@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Hot Rods @ Lugnuts Hot Rods @ Lugnuts

Follow on MiLB First Pitch  https //stza.co/+vMQu-n

Shop  https //stza.co/+vMQu-3R

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Hot Rods @ Lugnuts
END:VALARM
DTSTART:20180519T230500Z
DTEND:20180520T020500Z
UID:LyPrda6FUEtYEVzSVLgHPj0k@stanza.co
SUMMARY:Hot Rods @ Lugnuts
DESCRIPTION:Hot Rods @ Lugnuts\n\nFollow on MiLB First Pitch: https://stza.co/+vMQu-n\n\nShop: https://stza.co/+vMQu-3R\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144508Z
LAST-MODIFIED:20180213T144508Z
TRANSP:OPAQUE
END:VEVENT
* Hot Rods @ Lugnuts
<2018-05-20 Sun 12:05-15:05>
:PROPERTIES:
:ID:       KFTy2axDJRA828ZL9fffp8iv@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Hot Rods @ Lugnuts Hot Rods @ Lugnuts

Follow on MiLB First Pitch  https //stza.co/+vMQv-2y

Shop  https //stza.co/+vMQv-1Z

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Hot Rods @ Lugnuts
END:VALARM
DTSTART:20180520T170500Z
DTEND:20180520T200500Z
UID:KFTy2axDJRA828ZL9fffp8iv@stanza.co
SUMMARY:Hot Rods @ Lugnuts
DESCRIPTION:Hot Rods @ Lugnuts\n\nFollow on MiLB First Pitch: https://stza.co/+vMQv-2y\n\nShop: https://stza.co/+vMQv-1Z\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144508Z
LAST-MODIFIED:20180213T144508Z
TRANSP:OPAQUE
END:VEVENT
* Hot Rods vs. Loons
<2018-05-21 Mon 18:35-21:35>
:PROPERTIES:
:ID:       JxZLsxHbXhKEffLfR4qGUYLY@stanza.co
:LOCATION: Buck Monday
:STATUS:   CONFIRMED
:END:

Hot Rods vs. Loons $1 Popcorn and $1 Pepsi Products 

Follow on MiLB First Pitch  https //stza.co/+vMOc-3B

Shop  https //stza.co/+vMOc-21

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Hot Rods vs. Loons
END:VALARM
DTSTART:20180521T233500Z
DTEND:20180522T023500Z
UID:JxZLsxHbXhKEffLfR4qGUYLY@stanza.co
SUMMARY:Hot Rods vs. Loons
DESCRIPTION:$1 Popcorn and $1 Pepsi Products \n\nFollow on MiLB First Pitch: https://stza.co/+vMOc-3B\n\nShop: https://stza.co/+vMOc-21\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Buck Monday
STATUS:CONFIRMED
CREATED:20180213T144508Z
LAST-MODIFIED:20180213T144508Z
TRANSP:OPAQUE
END:VEVENT
* Hot Rods vs. Loons
<2018-05-22 Tue 18:35-21:35>
:PROPERTIES:
:ID:       h8ax_YzNJ_xGWn4DFxHQzp0O@stanza.co
:LOCATION: Tail Waggin' Tuesday
:STATUS:   CONFIRMED
:END:

Hot Rods vs. Loons $1 Hot Dogs. Dogs are welcome EVERY Tuesday home game and get in FREE with their owner.

Follow on MiLB First Pitch  https //stza.co/+vMOe-1m

Shop  https //stza.co/+vMOe-1b

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Hot Rods vs. Loons
END:VALARM
DTSTART:20180522T233500Z
DTEND:20180523T023500Z
UID:h8ax_YzNJ_xGWn4DFxHQzp0O@stanza.co
SUMMARY:Hot Rods vs. Loons
DESCRIPTION:$1 Hot Dogs. Dogs are welcome EVERY Tuesday home game and get in FREE with their owner.\n\nFollow on MiLB First Pitch: https://stza.co/+vMOe-1m\n\nShop: https://stza.co/+vMOe-1b\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Tail Waggin' Tuesday
STATUS:CONFIRMED
CREATED:20180213T144508Z
LAST-MODIFIED:20180213T144508Z
TRANSP:OPAQUE
END:VEVENT
* Hot Rods vs. Loons
<2018-05-23 Wed 18:35-21:35>
:PROPERTIES:
:ID:       onKA1iCHRQvKTticq6-sBwa0@stanza.co
:LOCATION: Winning Wednesday
:STATUS:   CONFIRMED
:END:

Hot Rods vs. Loons Play baseball bingo and have the chance to win great prizes! 

Follow on MiLB First Pitch  https //stza.co/+vMOg-3I

Shop  https //stza.co/+vMOg-6

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Hot Rods vs. Loons
END:VALARM
DTSTART:20180523T233500Z
DTEND:20180524T023500Z
UID:onKA1iCHRQvKTticq6-sBwa0@stanza.co
SUMMARY:Hot Rods vs. Loons
DESCRIPTION:Play baseball bingo and have the chance to win great prizes! \n\nFollow on MiLB First Pitch: https://stza.co/+vMOg-3I\n\nShop: https://stza.co/+vMOg-6\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Winning Wednesday
STATUS:CONFIRMED
CREATED:20180213T144508Z
LAST-MODIFIED:20180213T144508Z
TRANSP:OPAQUE
END:VEVENT
* Hot Rods vs. Loons
<2018-05-24 Thu 18:35-21:35>
:PROPERTIES:
:ID:       QMkIowgxUvIqaK5O3N6jgNrU@stanza.co
:LOCATION: Throwback Thursday 
:STATUS:   CONFIRMED
:END:

Hot Rods vs. Loons $2 Pepsi Products and $2 Domestic Beer

Follow on MiLB First Pitch  https //stza.co/+vMOj-3t

Shop  https //stza.co/+vMOj-3L

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Hot Rods vs. Loons
END:VALARM
DTSTART:20180524T233500Z
DTEND:20180525T023500Z
UID:QMkIowgxUvIqaK5O3N6jgNrU@stanza.co
SUMMARY:Hot Rods vs. Loons
DESCRIPTION:$2 Pepsi Products and $2 Domestic Beer\n\nFollow on MiLB First Pitch: https://stza.co/+vMOj-3t\n\nShop: https://stza.co/+vMOj-3L\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Throwback Thursday 
STATUS:CONFIRMED
CREATED:20180213T144508Z
LAST-MODIFIED:20180213T144508Z
TRANSP:OPAQUE
END:VEVENT
* Hot Rods vs. Dragons
<2018-05-25 Fri 18:35-21:35>
:PROPERTIES:
:ID:       PM-8zU3pCtqATe10fUyc8k3H@stanza.co
:LOCATION: Fireworks Friday
:STATUS:   CONFIRMED
:END:

Hot Rods vs. Dragons Enjoy post-game fireworks every Friday home game!

Join us in honoring our EMTs! Stay for postgame fireworks! 

Follow on MiLB First Pitch  https //stza.co/+vMOk-3I

Shop  https //stza.co/+vMOk-y

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Hot Rods vs. Dragons
END:VALARM
DTSTART:20180525T233500Z
DTEND:20180526T023500Z
UID:PM-8zU3pCtqATe10fUyc8k3H@stanza.co
SUMMARY:Hot Rods vs. Dragons
DESCRIPTION:Enjoy post-game fireworks every Friday home game!\n\nJoin us in honoring our EMTs! Stay for postgame fireworks! \n\nFollow on MiLB First Pitch: https://stza.co/+vMOk-3I\n\nShop: https://stza.co/+vMOk-y\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Fireworks Friday
STATUS:CONFIRMED
CREATED:20180213T144508Z
LAST-MODIFIED:20180213T144508Z
TRANSP:OPAQUE
END:VEVENT
* Hot Rods vs. Dragons
<2018-05-26 Sat 18:35-21:35>
:PROPERTIES:
:ID:       dvYIF61WfwhMgzPdCP0yUukZ@stanza.co
:LOCATION: Super Saturday
:STATUS:   CONFIRMED
:END:

Hot Rods vs. Dragons Saturdays include specialty giveaways and entertainment! 

Follow on MiLB First Pitch  https //stza.co/+vMOm-3A

Shop  https //stza.co/+vMOm-3t

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Hot Rods vs. Dragons
END:VALARM
DTSTART:20180526T233500Z
DTEND:20180527T023500Z
UID:dvYIF61WfwhMgzPdCP0yUukZ@stanza.co
SUMMARY:Hot Rods vs. Dragons
DESCRIPTION:Saturdays include specialty giveaways and entertainment! \n\nFollow on MiLB First Pitch: https://stza.co/+vMOm-3A\n\nShop: https://stza.co/+vMOm-3t\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Super Saturday
STATUS:CONFIRMED
CREATED:20180213T144508Z
LAST-MODIFIED:20180213T144508Z
TRANSP:OPAQUE
END:VEVENT
* Hot Rods vs. Dragons
<2018-05-27 Sun 18:35-21:35>
:PROPERTIES:
:ID:       Kqtd1NzLozf6C5UZWTMLB1_A@stanza.co
:LOCATION: 2000s Night
:STATUS:   CONFIRMED
:END:

Hot Rods vs. Dragons No post-game autographs this Sunday as we will be having a special fireworks show! 

Join us for Sunday Funday! First 500 kids eat free with paid ticket! Postgame autographs and postgame kids run the bases! 

Follow on MiLB First Pitch  https //stza.co/+vMOp-B

Shop  https //stza.co/+vMOp-1u

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Hot Rods vs. Dragons
END:VALARM
DTSTART:20180527T233500Z
DTEND:20180528T023500Z
UID:Kqtd1NzLozf6C5UZWTMLB1_A@stanza.co
SUMMARY:Hot Rods vs. Dragons
DESCRIPTION:No post-game autographs this Sunday as we will be having a special fireworks show! \n\nJoin us for Sunday Funday! First 500 kids eat free with paid ticket! Postgame autographs and postgame kids run the bases! \n\nFollow on MiLB First Pitch: https://stza.co/+vMOp-B\n\nShop: https://stza.co/+vMOp-1u\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:2000s Night
STATUS:CONFIRMED
CREATED:20180213T144508Z
LAST-MODIFIED:20180213T144508Z
TRANSP:OPAQUE
END:VEVENT
* Hot Rods vs. Dragons
<2018-05-28 Mon 12:05-15:05>
:PROPERTIES:
:ID:       RuoCcS8mi1CQERgK7UaesYDJ@stanza.co
:LOCATION: Buck Monday
:STATUS:   CONFIRMED
:END:

Hot Rods vs. Dragons $1 Popcorn and $1 Pepsi Products 

Join us as we honor our military! 

Follow on MiLB First Pitch  https //stza.co/+vMOq-2J

Shop  https //stza.co/+vMOq-O

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Hot Rods vs. Dragons
END:VALARM
DTSTART:20180528T170500Z
DTEND:20180528T200500Z
UID:RuoCcS8mi1CQERgK7UaesYDJ@stanza.co
SUMMARY:Hot Rods vs. Dragons
DESCRIPTION:$1 Popcorn and $1 Pepsi Products \n\nJoin us as we honor our military! \n\nFollow on MiLB First Pitch: https://stza.co/+vMOq-2J\n\nShop: https://stza.co/+vMOq-O\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Buck Monday
STATUS:CONFIRMED
CREATED:20180213T144508Z
LAST-MODIFIED:20180213T144508Z
TRANSP:OPAQUE
END:VEVENT
* Hot Rods @ TinCaps
<2018-05-29 Tue 18:05-21:05>
:PROPERTIES:
:ID:       3qXSfJxET1GFxV1j8Yzdb5A6@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Hot Rods @ TinCaps Hot Rods @ TinCaps

Follow on MiLB First Pitch  https //stza.co/+vMQ3-3s

Shop  https //stza.co/+vMQ3-1_

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Hot Rods @ TinCaps
END:VALARM
DTSTART:20180529T230500Z
DTEND:20180530T020500Z
UID:3qXSfJxET1GFxV1j8Yzdb5A6@stanza.co
SUMMARY:Hot Rods @ TinCaps
DESCRIPTION:Hot Rods @ TinCaps\n\nFollow on MiLB First Pitch: https://stza.co/+vMQ3-3s\n\nShop: https://stza.co/+vMQ3-1_\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144508Z
LAST-MODIFIED:20180213T144508Z
TRANSP:OPAQUE
END:VEVENT
* Hot Rods @ TinCaps
<2018-05-30 Wed 18:05-21:05>
:PROPERTIES:
:ID:       ElyqPXBp9mOpJ6NzgO6mj8Yh@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Hot Rods @ TinCaps Hot Rods @ TinCaps

Follow on MiLB First Pitch  https //stza.co/+vMQ4-11

Shop  https //stza.co/+vMQ4-B

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Hot Rods @ TinCaps
END:VALARM
DTSTART:20180530T230500Z
DTEND:20180531T020500Z
UID:ElyqPXBp9mOpJ6NzgO6mj8Yh@stanza.co
SUMMARY:Hot Rods @ TinCaps
DESCRIPTION:Hot Rods @ TinCaps\n\nFollow on MiLB First Pitch: https://stza.co/+vMQ4-11\n\nShop: https://stza.co/+vMQ4-B\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144508Z
LAST-MODIFIED:20180213T144508Z
TRANSP:OPAQUE
END:VEVENT
* Hot Rods @ TinCaps
<2018-05-31 Thu 18:05-21:05>
:PROPERTIES:
:ID:       iCXqI8q0n9kH-jGiqtC1LZzy@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Hot Rods @ TinCaps Hot Rods @ TinCaps

Follow on MiLB First Pitch  https //stza.co/+vMQ5-2o

Shop  https //stza.co/+vMQ5-Y

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Hot Rods @ TinCaps
END:VALARM
DTSTART:20180531T230500Z
DTEND:20180601T020500Z
UID:iCXqI8q0n9kH-jGiqtC1LZzy@stanza.co
SUMMARY:Hot Rods @ TinCaps
DESCRIPTION:Hot Rods @ TinCaps\n\nFollow on MiLB First Pitch: https://stza.co/+vMQ5-2o\n\nShop: https://stza.co/+vMQ5-Y\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144508Z
LAST-MODIFIED:20180213T144508Z
TRANSP:OPAQUE
END:VEVENT
* Hot Rods vs. Whitecaps
<2018-06-01 Fri 18:35-21:35>
:PROPERTIES:
:ID:       IKIV294SO6AiPsy38pbGGOaL@stanza.co
:LOCATION: Fireworks Friday
:STATUS:   CONFIRMED
:END:

Hot Rods vs. Whitecaps Enjoy post-game fireworks every Friday home game!



Follow on MiLB First Pitch  https //stza.co/+vMOs-1W

Shop  https //stza.co/+vMOs-3x

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Hot Rods vs. Whitecaps
END:VALARM
DTSTART:20180601T233500Z
DTEND:20180602T023500Z
UID:IKIV294SO6AiPsy38pbGGOaL@stanza.co
SUMMARY:Hot Rods vs. Whitecaps
DESCRIPTION:Enjoy post-game fireworks every Friday home game!\n\n\n\nFollow on MiLB First Pitch: https://stza.co/+vMOs-1W\n\nShop: https://stza.co/+vMOs-3x\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Fireworks Friday
STATUS:CONFIRMED
CREATED:20180213T144508Z
LAST-MODIFIED:20180213T144508Z
TRANSP:OPAQUE
END:VEVENT
* Hot Rods vs. Whitecaps
<2018-06-02 Sat 18:35-21:35>
:PROPERTIES:
:ID:       sda3PdQof-CeCx42VkzM3_YK@stanza.co
:LOCATION: Super Saturday
:STATUS:   CONFIRMED
:END:

Hot Rods vs. Whitecaps Saturdays include specialty giveaways and entertainment! 

Jersey Auction, Soccer Scarf Giveaway, and More! 

Follow on MiLB First Pitch  https //stza.co/+vMOv-1b

Shop  https //stza.co/+vMOv-3F

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Hot Rods vs. Whitecaps
END:VALARM
DTSTART:20180602T233500Z
DTEND:20180603T023500Z
UID:sda3PdQof-CeCx42VkzM3_YK@stanza.co
SUMMARY:Hot Rods vs. Whitecaps
DESCRIPTION:Saturdays include specialty giveaways and entertainment! \n\nJersey Auction, Soccer Scarf Giveaway, and More! \n\nFollow on MiLB First Pitch: https://stza.co/+vMOv-1b\n\nShop: https://stza.co/+vMOv-3F\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Super Saturday
STATUS:CONFIRMED
CREATED:20180213T144508Z
LAST-MODIFIED:20180213T144508Z
TRANSP:OPAQUE
END:VEVENT
* Hot Rods vs. Whitecaps
<2018-06-03 Sun 14:05-17:05>
:PROPERTIES:
:ID:       NJKHn4ZEiNinT7IpZR049JJG@stanza.co
:LOCATION: Roscoe's Birthday
:STATUS:   CONFIRMED
:END:

Hot Rods vs. Whitecaps Join as we celebrate Roscoe's Birthday! Special PBS character appearance by Clifford! 

Join us for Sunday Funday! First 500 kids eat free with paid ticket! Postgame autographs and postgame kids run the bases! 

Follow on MiLB First Pitch  https //stza.co/+vMOw-1W

Shop  https //stza.co/+vMOw-3

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Hot Rods vs. Whitecaps
END:VALARM
DTSTART:20180603T190500Z
DTEND:20180603T220500Z
UID:NJKHn4ZEiNinT7IpZR049JJG@stanza.co
SUMMARY:Hot Rods vs. Whitecaps
DESCRIPTION:Join as we celebrate Roscoe's Birthday! Special PBS character appearance by Clifford! \n\nJoin us for Sunday Funday! First 500 kids eat free with paid ticket! Postgame autographs and postgame kids run the bases! \n\nFollow on MiLB First Pitch: https://stza.co/+vMOw-1W\n\nShop: https://stza.co/+vMOw-3\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Roscoe's Birthday
STATUS:CONFIRMED
CREATED:20180213T144508Z
LAST-MODIFIED:20180213T144508Z
TRANSP:OPAQUE
END:VEVENT
* Hot Rods vs. Lugnuts
<2018-06-05 Tue 18:35-21:35>
:PROPERTIES:
:ID:       wrJdw4bH_oyLGQ9jn97dq3IK@stanza.co
:LOCATION: Tail Waggin' Tuesday
:STATUS:   CONFIRMED
:END:

Hot Rods vs. Lugnuts $1 Hot Dogs. Dogs are welcome EVERY Tuesday home game and get in FREE with their owner.



Follow on MiLB First Pitch  https //stza.co/+vMOz-24

Shop  https //stza.co/+vMOz-2s

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Hot Rods vs. Lugnuts
END:VALARM
DTSTART:20180605T233500Z
DTEND:20180606T023500Z
UID:wrJdw4bH_oyLGQ9jn97dq3IK@stanza.co
SUMMARY:Hot Rods vs. Lugnuts
DESCRIPTION:$1 Hot Dogs. Dogs are welcome EVERY Tuesday home game and get in FREE with their owner.\n\n\n\nFollow on MiLB First Pitch: https://stza.co/+vMOz-24\n\nShop: https://stza.co/+vMOz-2s\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Tail Waggin' Tuesday
STATUS:CONFIRMED
CREATED:20180213T144508Z
LAST-MODIFIED:20180213T144508Z
TRANSP:OPAQUE
END:VEVENT
* Hot Rods vs. Lugnuts
<2018-06-06 Wed 18:35-21:35>
:PROPERTIES:
:ID:       6pgMd2g9QNAy6lP6XL7WHX_y@stanza.co
:LOCATION: Winning Wednesday
:STATUS:   CONFIRMED
:END:

Hot Rods vs. Lugnuts Play baseball bingo and have the chance to win great prizes! 

Follow on MiLB First Pitch  https //stza.co/+vMOB-1p

Shop  https //stza.co/+vMOB-20

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Hot Rods vs. Lugnuts
END:VALARM
DTSTART:20180606T233500Z
DTEND:20180607T023500Z
UID:6pgMd2g9QNAy6lP6XL7WHX_y@stanza.co
SUMMARY:Hot Rods vs. Lugnuts
DESCRIPTION:Play baseball bingo and have the chance to win great prizes! \n\nFollow on MiLB First Pitch: https://stza.co/+vMOB-1p\n\nShop: https://stza.co/+vMOB-20\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Winning Wednesday
STATUS:CONFIRMED
CREATED:20180213T144508Z
LAST-MODIFIED:20180213T144508Z
TRANSP:OPAQUE
END:VEVENT
* Hot Rods vs. Lugnuts
<2018-06-07 Thu 18:35-21:35>
:PROPERTIES:
:ID:       sM3Yb_pG1zUQxKa1jguy1Sd-@stanza.co
:LOCATION: Throwback Thursday 
:STATUS:   CONFIRMED
:END:

Hot Rods vs. Lugnuts $2 Pepsi Products and $2 Domestic Beer

Follow on MiLB First Pitch  https //stza.co/+vMOD-F

Shop  https //stza.co/+vMOD-3

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Hot Rods vs. Lugnuts
END:VALARM
DTSTART:20180607T233500Z
DTEND:20180608T023500Z
UID:sM3Yb_pG1zUQxKa1jguy1Sd-@stanza.co
SUMMARY:Hot Rods vs. Lugnuts
DESCRIPTION:$2 Pepsi Products and $2 Domestic Beer\n\nFollow on MiLB First Pitch: https://stza.co/+vMOD-F\n\nShop: https://stza.co/+vMOD-3\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Throwback Thursday 
STATUS:CONFIRMED
CREATED:20180213T144508Z
LAST-MODIFIED:20180213T144508Z
TRANSP:OPAQUE
END:VEVENT
* Hot Rods @ Dragons
<2018-06-08 Fri 18:00-21:00>
:PROPERTIES:
:ID:       oql0cNVqLu17bwrBaW08YdSr@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Hot Rods @ Dragons Hot Rods @ Dragons

Follow on MiLB First Pitch  https //stza.co/+vMPY-24

Shop  https //stza.co/+vMPY-12

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Hot Rods @ Dragons
END:VALARM
DTSTART:20180608T230000Z
DTEND:20180609T020000Z
UID:oql0cNVqLu17bwrBaW08YdSr@stanza.co
SUMMARY:Hot Rods @ Dragons
DESCRIPTION:Hot Rods @ Dragons\n\nFollow on MiLB First Pitch: https://stza.co/+vMPY-24\n\nShop: https://stza.co/+vMPY-12\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144508Z
LAST-MODIFIED:20180213T144508Z
TRANSP:OPAQUE
END:VEVENT
* Hot Rods @ Dragons
<2018-06-09 Sat 18:00-21:00>
:PROPERTIES:
:ID:       ilYubMqTpZkz4yVblgdqiJxE@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Hot Rods @ Dragons Hot Rods @ Dragons

Follow on MiLB First Pitch  https //stza.co/+vMPZ-_

Shop  https //stza.co/+vMPZ-B

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Hot Rods @ Dragons
END:VALARM
DTSTART:20180609T230000Z
DTEND:20180610T020000Z
UID:ilYubMqTpZkz4yVblgdqiJxE@stanza.co
SUMMARY:Hot Rods @ Dragons
DESCRIPTION:Hot Rods @ Dragons\n\nFollow on MiLB First Pitch: https://stza.co/+vMPZ-_\n\nShop: https://stza.co/+vMPZ-B\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144508Z
LAST-MODIFIED:20180213T144508Z
TRANSP:OPAQUE
END:VEVENT
* Hot Rods @ Dragons
<2018-06-10 Sun 13:00-16:00>
:PROPERTIES:
:ID:       9t9P81RUMsypXD2DBESuy6rH@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Hot Rods @ Dragons Hot Rods @ Dragons

Follow on MiLB First Pitch  https //stza.co/+vMP_-3l

Shop  https //stza.co/+vMP_-1U

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Hot Rods @ Dragons
END:VALARM
DTSTART:20180610T180000Z
DTEND:20180610T210000Z
UID:9t9P81RUMsypXD2DBESuy6rH@stanza.co
SUMMARY:Hot Rods @ Dragons
DESCRIPTION:Hot Rods @ Dragons\n\nFollow on MiLB First Pitch: https://stza.co/+vMP_-3l\n\nShop: https://stza.co/+vMP_-1U\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144508Z
LAST-MODIFIED:20180213T144508Z
TRANSP:OPAQUE
END:VEVENT
* Hot Rods @ Dragons
<2018-06-11 Mon 18:00-21:00>
:PROPERTIES:
:ID:       9XTMfjhfQq0dEuMQUpS8Uic3@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Hot Rods @ Dragons Hot Rods @ Dragons

Follow on MiLB First Pitch  https //stza.co/+vMP$-3t

Shop  https //stza.co/+vMP$-2j

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Hot Rods @ Dragons
END:VALARM
DTSTART:20180611T230000Z
DTEND:20180612T020000Z
UID:9XTMfjhfQq0dEuMQUpS8Uic3@stanza.co
SUMMARY:Hot Rods @ Dragons
DESCRIPTION:Hot Rods @ Dragons\n\nFollow on MiLB First Pitch: https://stza.co/+vMP$-3t\n\nShop: https://stza.co/+vMP$-2j\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144508Z
LAST-MODIFIED:20180213T144508Z
TRANSP:OPAQUE
END:VEVENT
* Hot Rods vs. TinCaps
<2018-06-12 Tue 18:35-21:35>
:PROPERTIES:
:ID:       o3DXz4jC4SE06TlmrVfl0F3j@stanza.co
:LOCATION: Tail Waggin' Tuesday
:STATUS:   CONFIRMED
:END:

Hot Rods vs. TinCaps $1 Hot Dogs. Dogs are welcome EVERY Tuesday home game and get in FREE with their owner.

Follow on MiLB First Pitch  https //stza.co/+vMOE-1f

Shop  https //stza.co/+vMOE-2Z

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Hot Rods vs. TinCaps
END:VALARM
DTSTART:20180612T233500Z
DTEND:20180613T023500Z
UID:o3DXz4jC4SE06TlmrVfl0F3j@stanza.co
SUMMARY:Hot Rods vs. TinCaps
DESCRIPTION:$1 Hot Dogs. Dogs are welcome EVERY Tuesday home game and get in FREE with their owner.\n\nFollow on MiLB First Pitch: https://stza.co/+vMOE-1f\n\nShop: https://stza.co/+vMOE-2Z\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Tail Waggin' Tuesday
STATUS:CONFIRMED
CREATED:20180213T144508Z
LAST-MODIFIED:20180213T144508Z
TRANSP:OPAQUE
END:VEVENT
* Hot Rods vs. TinCaps
<2018-06-13 Wed 18:35-21:35>
:PROPERTIES:
:ID:       ljZhe78hni6frppzqsdYYqFZ@stanza.co
:LOCATION: Winning Wednesday
:STATUS:   CONFIRMED
:END:

Hot Rods vs. TinCaps Play baseball bingo and have the chance to win great prizes! 

Follow on MiLB First Pitch  https //stza.co/+vMOH-V

Shop  https //stza.co/+vMOH-1_

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Hot Rods vs. TinCaps
END:VALARM
DTSTART:20180613T233500Z
DTEND:20180614T023500Z
UID:ljZhe78hni6frppzqsdYYqFZ@stanza.co
SUMMARY:Hot Rods vs. TinCaps
DESCRIPTION:Play baseball bingo and have the chance to win great prizes! \n\nFollow on MiLB First Pitch: https://stza.co/+vMOH-V\n\nShop: https://stza.co/+vMOH-1_\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Winning Wednesday
STATUS:CONFIRMED
CREATED:20180213T144508Z
LAST-MODIFIED:20180213T144508Z
TRANSP:OPAQUE
END:VEVENT
* Hot Rods vs. TinCaps
<2018-06-14 Thu 18:35-21:35>
:PROPERTIES:
:ID:       KwQnYyRIlugPPUw_DuK3arug@stanza.co
:LOCATION: Throwback Thursday 
:STATUS:   CONFIRMED
:END:

Hot Rods vs. TinCaps $2 Pepsi Products and $2 Domestic Beer



Follow on MiLB First Pitch  https //stza.co/+vMOJ-1c

Shop  https //stza.co/+vMOJ-3S

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Hot Rods vs. TinCaps
END:VALARM
DTSTART:20180614T233500Z
DTEND:20180615T023500Z
UID:KwQnYyRIlugPPUw_DuK3arug@stanza.co
SUMMARY:Hot Rods vs. TinCaps
DESCRIPTION:$2 Pepsi Products and $2 Domestic Beer\n\n\n\nFollow on MiLB First Pitch: https://stza.co/+vMOJ-1c\n\nShop: https://stza.co/+vMOJ-3S\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Throwback Thursday 
STATUS:CONFIRMED
CREATED:20180213T144508Z
LAST-MODIFIED:20180213T144508Z
TRANSP:OPAQUE
END:VEVENT
* Hot Rods @ Captains
<2018-06-15 Fri 18:00-21:00>
:PROPERTIES:
:ID:       VwbS4L7TrUWIiUAUuE_AS9Dk@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Hot Rods @ Captains Hot Rods @ Captains

Follow on MiLB First Pitch  https //stza.co/+xBjc-1n

Shop  https //stza.co/+xBjc-6

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Hot Rods @ Captains
END:VALARM
DTSTART:20180615T230000Z
DTEND:20180616T020000Z
UID:VwbS4L7TrUWIiUAUuE_AS9Dk@stanza.co
SUMMARY:Hot Rods @ Captains
DESCRIPTION:Hot Rods @ Captains\n\nFollow on MiLB First Pitch: https://stza.co/+xBjc-1n\n\nShop: https://stza.co/+xBjc-6\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144508Z
LAST-MODIFIED:20180213T144508Z
TRANSP:OPAQUE
END:VEVENT
* Hot Rods @ Captains
<2018-06-16 Sat 18:00-21:00>
:PROPERTIES:
:ID:       f5i6OqV0WIBSZrzvEw-sPFdX@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Hot Rods @ Captains Hot Rods @ Captains

Follow on MiLB First Pitch  https //stza.co/+xBjf-3t

Shop  https //stza.co/+xBjf-$

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Hot Rods @ Captains
END:VALARM
DTSTART:20180616T230000Z
DTEND:20180617T020000Z
UID:f5i6OqV0WIBSZrzvEw-sPFdX@stanza.co
SUMMARY:Hot Rods @ Captains
DESCRIPTION:Hot Rods @ Captains\n\nFollow on MiLB First Pitch: https://stza.co/+xBjf-3t\n\nShop: https://stza.co/+xBjf-$\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144508Z
LAST-MODIFIED:20180213T144508Z
TRANSP:OPAQUE
END:VEVENT
* Hot Rods @ Captains
<2018-06-17 Sun 15:00-18:00>
:PROPERTIES:
:ID:       O8uz-yFgN6JaauHVk84vMvtw@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Hot Rods @ Captains Hot Rods @ Captains

Follow on MiLB First Pitch  https //stza.co/+xBji-C

Shop  https //stza.co/+xBji-2s

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Hot Rods @ Captains
END:VALARM
DTSTART:20180617T200000Z
DTEND:20180617T230000Z
UID:O8uz-yFgN6JaauHVk84vMvtw@stanza.co
SUMMARY:Hot Rods @ Captains
DESCRIPTION:Hot Rods @ Captains\n\nFollow on MiLB First Pitch: https://stza.co/+xBji-C\n\nShop: https://stza.co/+xBji-2s\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144508Z
LAST-MODIFIED:20180213T144508Z
TRANSP:OPAQUE
END:VEVENT
* Hot Rods vs. Captains
<2018-06-21 Thu 18:35-21:35>
:PROPERTIES:
:ID:       tVS-ZAeiFUyP1ZDlLRx-UZbo@stanza.co
:LOCATION: Throwback Thursday 
:STATUS:   CONFIRMED
:END:

Hot Rods vs. Captains $2 Pepsi Products and $2 Domestic Beer

Follow on MiLB First Pitch  https //stza.co/+vMOL-3A

Shop  https //stza.co/+vMOL-3Y

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Hot Rods vs. Captains
END:VALARM
DTSTART:20180621T233500Z
DTEND:20180622T023500Z
UID:tVS-ZAeiFUyP1ZDlLRx-UZbo@stanza.co
SUMMARY:Hot Rods vs. Captains
DESCRIPTION:$2 Pepsi Products and $2 Domestic Beer\n\nFollow on MiLB First Pitch: https://stza.co/+vMOL-3A\n\nShop: https://stza.co/+vMOL-3Y\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Throwback Thursday 
STATUS:CONFIRMED
CREATED:20180213T144508Z
LAST-MODIFIED:20180213T144508Z
TRANSP:OPAQUE
END:VEVENT
* Hot Rods vs. Captains
<2018-06-22 Fri 18:35-21:35>
:PROPERTIES:
:ID:       1AhmJxUme-MR4VJGasjNnXkT@stanza.co
:LOCATION: Fireworks Friday
:STATUS:   CONFIRMED
:END:

Hot Rods vs. Captains Enjoy post-game fireworks every Friday home game!

Dress up as your favorite princess or pirate and enjoy the game! Get here early for our Roscoe Soap Dispenser giveaway and be sure to stay for post-game fireworks!

Follow on MiLB First Pitch  https //stza.co/+vMON-1t

Shop  https //stza.co/+vMON-2U

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Hot Rods vs. Captains
END:VALARM
DTSTART:20180622T233500Z
DTEND:20180623T023500Z
UID:1AhmJxUme-MR4VJGasjNnXkT@stanza.co
SUMMARY:Hot Rods vs. Captains
DESCRIPTION:Enjoy post-game fireworks every Friday home game!\n\nDress up as your favorite princess or pirate and enjoy the game! Get here early for our Roscoe Soap Dispenser giveaway and be sure to stay for post-game fireworks!\n\nFollow on MiLB First Pitch: https://stza.co/+vMON-1t\n\nShop: https://stza.co/+vMON-2U\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Fireworks Friday
STATUS:CONFIRMED
CREATED:20180213T144508Z
LAST-MODIFIED:20180213T144508Z
TRANSP:OPAQUE
END:VEVENT
* Hot Rods vs. Captains
<2018-06-23 Sat 18:35-21:35>
:PROPERTIES:
:ID:       ahXz4YsMrkT_doXFIUV4HZ24@stanza.co
:LOCATION: Super Saturday
:STATUS:   CONFIRMED
:END:

Hot Rods vs. Captains Saturdays include specialty giveaways and entertainment! 

Join us as we celebrate having our 2 millionth fan in Bowling Green Ballpark! Each fan will receive a 2018 team card set giving him/her the potential to win an ultimate Hot Rods prize! The Zooperstars are back again for fun in-game entertainment! 

Follow on MiLB First Pitch  https //stza.co/+vMOP-3l

Shop  https //stza.co/+vMOP-y

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Hot Rods vs. Captains
END:VALARM
DTSTART:20180623T233500Z
DTEND:20180624T023500Z
UID:ahXz4YsMrkT_doXFIUV4HZ24@stanza.co
SUMMARY:Hot Rods vs. Captains
DESCRIPTION:Saturdays include specialty giveaways and entertainment! \n\nJoin us as we celebrate having our 2 millionth fan in Bowling Green Ballpark! Each fan will receive a 2018 team card set giving him/her the potential to win an ultimate Hot Rods prize! The Zooperstars are back again for fun in-game entertainment! \n\nFollow on MiLB First Pitch: https://stza.co/+vMOP-3l\n\nShop: https://stza.co/+vMOP-y\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Super Saturday
STATUS:CONFIRMED
CREATED:20180213T144508Z
LAST-MODIFIED:20180213T144508Z
TRANSP:OPAQUE
END:VEVENT
* Hot Rods vs. Captains
<2018-06-24 Sun 14:05-17:05>
:PROPERTIES:
:ID:       r4FWFl6ggJ6i3bGbFFuoXNen@stanza.co
:LOCATION: Sunday Funday
:STATUS:   CONFIRMED
:END:

Hot Rods vs. Captains Join us for Sunday Funday! First 500 kids eat free with paid ticket! Postgame autographs and postgame kids run the bases! 

Follow on MiLB First Pitch  https //stza.co/+vMOR-q

Shop  https //stza.co/+vMOR-2h

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Hot Rods vs. Captains
END:VALARM
DTSTART:20180624T190500Z
DTEND:20180624T220500Z
UID:r4FWFl6ggJ6i3bGbFFuoXNen@stanza.co
SUMMARY:Hot Rods vs. Captains
DESCRIPTION:Join us for Sunday Funday! First 500 kids eat free with paid ticket! Postgame autographs and postgame kids run the bases! \n\nFollow on MiLB First Pitch: https://stza.co/+vMOR-q\n\nShop: https://stza.co/+vMOR-2h\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Sunday Funday
STATUS:CONFIRMED
CREATED:20180213T144508Z
LAST-MODIFIED:20180213T144508Z
TRANSP:OPAQUE
END:VEVENT
* Hot Rods @ TinCaps
<2018-06-25 Mon 18:05-21:05>
:PROPERTIES:
:ID:       -7rn-h9Y0j-E7Q6k-hqlRY-T@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Hot Rods @ TinCaps Hot Rods @ TinCaps

Follow on MiLB First Pitch  https //stza.co/+vMQ6-2x

Shop  https //stza.co/+vMQ6-1T

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Hot Rods @ TinCaps
END:VALARM
DTSTART:20180625T230500Z
DTEND:20180626T020500Z
UID:-7rn-h9Y0j-E7Q6k-hqlRY-T@stanza.co
SUMMARY:Hot Rods @ TinCaps
DESCRIPTION:Hot Rods @ TinCaps\n\nFollow on MiLB First Pitch: https://stza.co/+vMQ6-2x\n\nShop: https://stza.co/+vMQ6-1T\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144508Z
LAST-MODIFIED:20180213T144508Z
TRANSP:OPAQUE
END:VEVENT
* Hot Rods @ TinCaps
<2018-06-26 Tue 18:05-21:05>
:PROPERTIES:
:ID:       eizBXjJZFwnFjIn0Zob51g9l@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Hot Rods @ TinCaps Hot Rods @ TinCaps

Follow on MiLB First Pitch  https //stza.co/+vMQ7-6

Shop  https //stza.co/+vMQ7-3r

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Hot Rods @ TinCaps
END:VALARM
DTSTART:20180626T230500Z
DTEND:20180627T020500Z
UID:eizBXjJZFwnFjIn0Zob51g9l@stanza.co
SUMMARY:Hot Rods @ TinCaps
DESCRIPTION:Hot Rods @ TinCaps\n\nFollow on MiLB First Pitch: https://stza.co/+vMQ7-6\n\nShop: https://stza.co/+vMQ7-3r\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144508Z
LAST-MODIFIED:20180213T144508Z
TRANSP:OPAQUE
END:VEVENT
* Hot Rods @ TinCaps
<2018-06-27 Wed 11:05-14:05>
:PROPERTIES:
:ID:       21UlhGeS8rkfrjijeM8tmBTH@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Hot Rods @ TinCaps Hot Rods @ TinCaps

Follow on MiLB First Pitch  https //stza.co/+vMQ8-r

Shop  https //stza.co/+vMQ8-2o

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Hot Rods @ TinCaps
END:VALARM
DTSTART:20180627T160500Z
DTEND:20180627T190500Z
UID:21UlhGeS8rkfrjijeM8tmBTH@stanza.co
SUMMARY:Hot Rods @ TinCaps
DESCRIPTION:Hot Rods @ TinCaps\n\nFollow on MiLB First Pitch: https://stza.co/+vMQ8-r\n\nShop: https://stza.co/+vMQ8-2o\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144508Z
LAST-MODIFIED:20180213T144508Z
TRANSP:OPAQUE
END:VEVENT
* Hot Rods @ Whitecaps
<2018-06-28 Thu 18:05-21:05>
:PROPERTIES:
:ID:       wRanY4CDzgvboiWDtU4BSXVC@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Hot Rods @ Whitecaps Hot Rods @ Whitecaps

Follow on MiLB First Pitch  https //stza.co/+vMQM-1

Shop  https //stza.co/+vMQM-3k

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Hot Rods @ Whitecaps
END:VALARM
DTSTART:20180628T230500Z
DTEND:20180629T020500Z
UID:wRanY4CDzgvboiWDtU4BSXVC@stanza.co
SUMMARY:Hot Rods @ Whitecaps
DESCRIPTION:Hot Rods @ Whitecaps\n\nFollow on MiLB First Pitch: https://stza.co/+vMQM-1\n\nShop: https://stza.co/+vMQM-3k\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144508Z
LAST-MODIFIED:20180213T144508Z
TRANSP:OPAQUE
END:VEVENT
* Hot Rods @ Whitecaps
<2018-06-29 Fri 18:05-21:05>
:PROPERTIES:
:ID:       opHYyC5ifVXNq2wYomwBQfR9@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Hot Rods @ Whitecaps Hot Rods @ Whitecaps

Follow on MiLB First Pitch  https //stza.co/+vMQN-2_

Shop  https //stza.co/+vMQN-1x

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Hot Rods @ Whitecaps
END:VALARM
DTSTART:20180629T230500Z
DTEND:20180630T020500Z
UID:opHYyC5ifVXNq2wYomwBQfR9@stanza.co
SUMMARY:Hot Rods @ Whitecaps
DESCRIPTION:Hot Rods @ Whitecaps\n\nFollow on MiLB First Pitch: https://stza.co/+vMQN-2_\n\nShop: https://stza.co/+vMQN-1x\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144508Z
LAST-MODIFIED:20180213T144508Z
TRANSP:OPAQUE
END:VEVENT
* Hot Rods @ Whitecaps
<2018-06-30 Sat 18:05-21:05>
:PROPERTIES:
:ID:       1r9Hl_hfOEnTHdYhMCaLVsV-@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Hot Rods @ Whitecaps Hot Rods @ Whitecaps

Follow on MiLB First Pitch  https //stza.co/+vMQO-8

Shop  https //stza.co/+vMQO-1w

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Hot Rods @ Whitecaps
END:VALARM
DTSTART:20180630T230500Z
DTEND:20180701T020500Z
UID:1r9Hl_hfOEnTHdYhMCaLVsV-@stanza.co
SUMMARY:Hot Rods @ Whitecaps
DESCRIPTION:Hot Rods @ Whitecaps\n\nFollow on MiLB First Pitch: https://stza.co/+vMQO-8\n\nShop: https://stza.co/+vMQO-1w\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144508Z
LAST-MODIFIED:20180213T144508Z
TRANSP:OPAQUE
END:VEVENT
* Hot Rods @ Whitecaps
<2018-07-01 Sun 13:00-16:00>
:PROPERTIES:
:ID:       pYolqxsZ4fmXwi3SXv8bqXAb@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Hot Rods @ Whitecaps Hot Rods @ Whitecaps

Follow on MiLB First Pitch  https //stza.co/+vMQP-1e

Shop  https //stza.co/+vMQP-g

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Hot Rods @ Whitecaps
END:VALARM
DTSTART:20180701T180000Z
DTEND:20180701T210000Z
UID:pYolqxsZ4fmXwi3SXv8bqXAb@stanza.co
SUMMARY:Hot Rods @ Whitecaps
DESCRIPTION:Hot Rods @ Whitecaps\n\nFollow on MiLB First Pitch: https://stza.co/+vMQP-1e\n\nShop: https://stza.co/+vMQP-g\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144508Z
LAST-MODIFIED:20180213T144508Z
TRANSP:OPAQUE
END:VEVENT
* Hot Rods @ Cubs
<2018-07-02 Mon 18:35-21:35>
:PROPERTIES:
:ID:       wY2HQDbEj93hivIMbdn5i0kH@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Hot Rods @ Cubs Hot Rods @ Cubs

Follow on MiLB First Pitch  https //stza.co/+vMQE-23

Shop  https //stza.co/+vMQE-37

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Hot Rods @ Cubs
END:VALARM
DTSTART:20180702T233500Z
DTEND:20180703T023500Z
UID:wY2HQDbEj93hivIMbdn5i0kH@stanza.co
SUMMARY:Hot Rods @ Cubs
DESCRIPTION:Hot Rods @ Cubs\n\nFollow on MiLB First Pitch: https://stza.co/+vMQE-23\n\nShop: https://stza.co/+vMQE-37\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144508Z
LAST-MODIFIED:20180213T144508Z
TRANSP:OPAQUE
END:VEVENT
* Hot Rods @ Cubs
<2018-07-03 Tue 18:35-21:35>
:PROPERTIES:
:ID:       knvI4zwFgYEDDEqhfkfuOHb3@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Hot Rods @ Cubs Hot Rods @ Cubs

Follow on MiLB First Pitch  https //stza.co/+vMQF-c

Shop  https //stza.co/+vMQF-2p

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Hot Rods @ Cubs
END:VALARM
DTSTART:20180703T233500Z
DTEND:20180704T023500Z
UID:knvI4zwFgYEDDEqhfkfuOHb3@stanza.co
SUMMARY:Hot Rods @ Cubs
DESCRIPTION:Hot Rods @ Cubs\n\nFollow on MiLB First Pitch: https://stza.co/+vMQF-c\n\nShop: https://stza.co/+vMQF-2p\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144508Z
LAST-MODIFIED:20180213T144508Z
TRANSP:OPAQUE
END:VEVENT
* Hot Rods vs. Cubs
<2018-07-04 Wed 18:35-21:35>
:PROPERTIES:
:ID:       1udwanZTUxHoCuCv34f91Ulo@stanza.co
:LOCATION: Winning Wednesday
:STATUS:   CONFIRMED
:END:

Hot Rods vs. Cubs Play baseball bingo and have the chance to win great prizes! 

Join as we celebrate the Fourth of July with one of the largest fireworks shows in south central Kentucky! 

Follow on MiLB First Pitch  https //stza.co/+vMOT-s

Shop  https //stza.co/+vMOT-29

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Hot Rods vs. Cubs
END:VALARM
DTSTART:20180704T233500Z
DTEND:20180705T023500Z
UID:1udwanZTUxHoCuCv34f91Ulo@stanza.co
SUMMARY:Hot Rods vs. Cubs
DESCRIPTION:Play baseball bingo and have the chance to win great prizes! \n\nJoin as we celebrate the Fourth of July with one of the largest fireworks shows in south central Kentucky! \n\nFollow on MiLB First Pitch: https://stza.co/+vMOT-s\n\nShop: https://stza.co/+vMOT-29\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Winning Wednesday
STATUS:CONFIRMED
CREATED:20180213T144508Z
LAST-MODIFIED:20180213T144508Z
TRANSP:OPAQUE
END:VEVENT
* Hot Rods vs. Cubs
<2018-07-05 Thu 18:35-21:35>
:PROPERTIES:
:ID:       4Oj8OB5NOmtrC2NeNKXfjIq0@stanza.co
:LOCATION: Throwback Thursday 
:STATUS:   CONFIRMED
:END:

Hot Rods vs. Cubs $2 Pepsi Products and $2 Domestic Beer

Follow on MiLB First Pitch  https //stza.co/+vMOV-2_

Shop  https //stza.co/+vMOV-1m

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Hot Rods vs. Cubs
END:VALARM
DTSTART:20180705T233500Z
DTEND:20180706T023500Z
UID:4Oj8OB5NOmtrC2NeNKXfjIq0@stanza.co
SUMMARY:Hot Rods vs. Cubs
DESCRIPTION:$2 Pepsi Products and $2 Domestic Beer\n\nFollow on MiLB First Pitch: https://stza.co/+vMOV-2_\n\nShop: https://stza.co/+vMOV-1m\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Throwback Thursday 
STATUS:CONFIRMED
CREATED:20180213T144508Z
LAST-MODIFIED:20180213T144508Z
TRANSP:OPAQUE
END:VEVENT
* Hot Rods @ TinCaps
<2018-07-06 Fri 18:05-21:05>
:PROPERTIES:
:ID:       LX73lfs4iW1Sax7DhIyoowQe@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Hot Rods @ TinCaps Hot Rods @ TinCaps

Follow on MiLB First Pitch  https //stza.co/+vMQ9-2f

Shop  https //stza.co/+vMQ9-24

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Hot Rods @ TinCaps
END:VALARM
DTSTART:20180706T230500Z
DTEND:20180707T020500Z
UID:LX73lfs4iW1Sax7DhIyoowQe@stanza.co
SUMMARY:Hot Rods @ TinCaps
DESCRIPTION:Hot Rods @ TinCaps\n\nFollow on MiLB First Pitch: https://stza.co/+vMQ9-2f\n\nShop: https://stza.co/+vMQ9-24\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144508Z
LAST-MODIFIED:20180213T144508Z
TRANSP:OPAQUE
END:VEVENT
* Hot Rods @ TinCaps
<2018-07-07 Sat 18:05-21:05>
:PROPERTIES:
:ID:       P0Px1BIvQiDZr_VScCeEgWwf@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Hot Rods @ TinCaps Hot Rods @ TinCaps

Follow on MiLB First Pitch  https //stza.co/+vMQa-1V

Shop  https //stza.co/+vMQa-10

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Hot Rods @ TinCaps
END:VALARM
DTSTART:20180707T230500Z
DTEND:20180708T020500Z
UID:P0Px1BIvQiDZr_VScCeEgWwf@stanza.co
SUMMARY:Hot Rods @ TinCaps
DESCRIPTION:Hot Rods @ TinCaps\n\nFollow on MiLB First Pitch: https://stza.co/+vMQa-1V\n\nShop: https://stza.co/+vMQa-10\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144508Z
LAST-MODIFIED:20180213T144508Z
TRANSP:OPAQUE
END:VEVENT
* Hot Rods @ TinCaps
<2018-07-08 Sun 14:05-17:05>
:PROPERTIES:
:ID:       xnVl3n9E1WsfTnr81R0PcXiz@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Hot Rods @ TinCaps Hot Rods @ TinCaps

Follow on MiLB First Pitch  https //stza.co/+vMQb-1R

Shop  https //stza.co/+vMQb-1M

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Hot Rods @ TinCaps
END:VALARM
DTSTART:20180708T190500Z
DTEND:20180708T220500Z
UID:xnVl3n9E1WsfTnr81R0PcXiz@stanza.co
SUMMARY:Hot Rods @ TinCaps
DESCRIPTION:Hot Rods @ TinCaps\n\nFollow on MiLB First Pitch: https://stza.co/+vMQb-1R\n\nShop: https://stza.co/+vMQb-1M\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144508Z
LAST-MODIFIED:20180213T144508Z
TRANSP:OPAQUE
END:VEVENT
* Hot Rods @ TinCaps
<2018-07-09 Mon 18:05-21:05>
:PROPERTIES:
:ID:       spqcqkm6D_5H-YUn6C0GrrcS@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Hot Rods @ TinCaps Hot Rods @ TinCaps

Follow on MiLB First Pitch  https //stza.co/+vMQc-20

Shop  https //stza.co/+vMQc-3n

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Hot Rods @ TinCaps
END:VALARM
DTSTART:20180709T230500Z
DTEND:20180710T020500Z
UID:spqcqkm6D_5H-YUn6C0GrrcS@stanza.co
SUMMARY:Hot Rods @ TinCaps
DESCRIPTION:Hot Rods @ TinCaps\n\nFollow on MiLB First Pitch: https://stza.co/+vMQc-20\n\nShop: https://stza.co/+vMQc-3n\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144508Z
LAST-MODIFIED:20180213T144508Z
TRANSP:OPAQUE
END:VEVENT
* Hot Rods vs. Cougars
<2018-07-11 Wed 18:35-21:35>
:PROPERTIES:
:ID:       5Mz7JjtKH5CEuk1KxYKjc3aP@stanza.co
:LOCATION: Winning Wednesday
:STATUS:   CONFIRMED
:END:

Hot Rods vs. Cougars Play baseball bingo and have the chance to win great prizes! 

Follow on MiLB First Pitch  https //stza.co/+vMOX-2N

Shop  https //stza.co/+vMOX-1b

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Hot Rods vs. Cougars
END:VALARM
DTSTART:20180711T233500Z
DTEND:20180712T023500Z
UID:5Mz7JjtKH5CEuk1KxYKjc3aP@stanza.co
SUMMARY:Hot Rods vs. Cougars
DESCRIPTION:Play baseball bingo and have the chance to win great prizes! \n\nFollow on MiLB First Pitch: https://stza.co/+vMOX-2N\n\nShop: https://stza.co/+vMOX-1b\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Winning Wednesday
STATUS:CONFIRMED
CREATED:20180213T144508Z
LAST-MODIFIED:20180213T144508Z
TRANSP:OPAQUE
END:VEVENT
* Hot Rods vs. Cougars
<2018-07-12 Thu 18:35-21:35>
:PROPERTIES:
:ID:       KeoNSlBs9uJ3KyDha4UvFspo@stanza.co
:LOCATION: Throwback Thursday 
:STATUS:   CONFIRMED
:END:

Hot Rods vs. Cougars $2 Pepsi Products and $2 Domestic Beer

Follow on MiLB First Pitch  https //stza.co/+vMOZ-3P

Shop  https //stza.co/+vMOZ-3I

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Hot Rods vs. Cougars
END:VALARM
DTSTART:20180712T233500Z
DTEND:20180713T023500Z
UID:KeoNSlBs9uJ3KyDha4UvFspo@stanza.co
SUMMARY:Hot Rods vs. Cougars
DESCRIPTION:$2 Pepsi Products and $2 Domestic Beer\n\nFollow on MiLB First Pitch: https://stza.co/+vMOZ-3P\n\nShop: https://stza.co/+vMOZ-3I\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Throwback Thursday 
STATUS:CONFIRMED
CREATED:20180213T144508Z
LAST-MODIFIED:20180213T144508Z
TRANSP:OPAQUE
END:VEVENT
* Hot Rods vs. Cougars
<2018-07-13 Fri 18:35-21:35>
:PROPERTIES:
:ID:       _lTrao_2XeUpS2nhHGnqkAD3@stanza.co
:LOCATION: Fireworks Friday
:STATUS:   CONFIRMED
:END:

Hot Rods vs. Cougars Enjoy post-game fireworks every Friday home game!

Follow on MiLB First Pitch  https //stza.co/+vMO_-3s

Shop  https //stza.co/+vMO_-u

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Hot Rods vs. Cougars
END:VALARM
DTSTART:20180713T233500Z
DTEND:20180714T023500Z
UID:_lTrao_2XeUpS2nhHGnqkAD3@stanza.co
SUMMARY:Hot Rods vs. Cougars
DESCRIPTION:Enjoy post-game fireworks every Friday home game!\n\nFollow on MiLB First Pitch: https://stza.co/+vMO_-3s\n\nShop: https://stza.co/+vMO_-u\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Fireworks Friday
STATUS:CONFIRMED
CREATED:20180213T144508Z
LAST-MODIFIED:20180213T144508Z
TRANSP:OPAQUE
END:VEVENT
* Hot Rods vs. River Bandits
<2018-07-14 Sat 18:35-21:35>
:PROPERTIES:
:ID:       sB39SYJZKryR1eaqb93MQubK@stanza.co
:LOCATION: Super Saturday
:STATUS:   CONFIRMED
:END:

Hot Rods vs. River Bandits Saturdays include specialty giveaways and entertainment! 

Mini Bat Giveaway

Follow on MiLB First Pitch  https //stza.co/+vMP1-3S

Shop  https //stza.co/+vMP1-2G

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Hot Rods vs. River Bandits
END:VALARM
DTSTART:20180714T233500Z
DTEND:20180715T023500Z
UID:sB39SYJZKryR1eaqb93MQubK@stanza.co
SUMMARY:Hot Rods vs. River Bandits
DESCRIPTION:Saturdays include specialty giveaways and entertainment! \n\nMini Bat Giveaway\n\nFollow on MiLB First Pitch: https://stza.co/+vMP1-3S\n\nShop: https://stza.co/+vMP1-2G\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Super Saturday
STATUS:CONFIRMED
CREATED:20180213T144508Z
LAST-MODIFIED:20180213T144508Z
TRANSP:OPAQUE
END:VEVENT
* Hot Rods vs. River Bandits
<2018-07-15 Sun 14:05-17:05>
:PROPERTIES:
:ID:       EdSW24EnPhk91LUTstl3Msqu@stanza.co
:LOCATION: Sunday Funday
:STATUS:   CONFIRMED
:END:

Hot Rods vs. River Bandits Join us for Sunday Funday! First 500 kids eat free with paid ticket! Postgame autographs and postgame kids run the bases! 

Follow on MiLB First Pitch  https //stza.co/+vMP3-2d

Shop  https //stza.co/+vMP3-s

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Hot Rods vs. River Bandits
END:VALARM
DTSTART:20180715T190500Z
DTEND:20180715T220500Z
UID:EdSW24EnPhk91LUTstl3Msqu@stanza.co
SUMMARY:Hot Rods vs. River Bandits
DESCRIPTION:Join us for Sunday Funday! First 500 kids eat free with paid ticket! Postgame autographs and postgame kids run the bases! \n\nFollow on MiLB First Pitch: https://stza.co/+vMP3-2d\n\nShop: https://stza.co/+vMP3-s\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Sunday Funday
STATUS:CONFIRMED
CREATED:20180213T144508Z
LAST-MODIFIED:20180213T144508Z
TRANSP:OPAQUE
END:VEVENT
* Hot Rods vs. River Bandits
<2018-07-16 Mon 12:05-15:05>
:PROPERTIES:
:ID:       uRoBFrALjdlez5LQxbsa9qQi@stanza.co
:LOCATION: Buck Monday
:STATUS:   CONFIRMED
:END:

Hot Rods vs. River Bandits $1 Popcorn and $1 Pepsi Products 



Follow on MiLB First Pitch  https //stza.co/+vMP5-2u

Shop  https //stza.co/+vMP5-K

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Hot Rods vs. River Bandits
END:VALARM
DTSTART:20180716T170500Z
DTEND:20180716T200500Z
UID:uRoBFrALjdlez5LQxbsa9qQi@stanza.co
SUMMARY:Hot Rods vs. River Bandits
DESCRIPTION:$1 Popcorn and $1 Pepsi Products \n\n\n\nFollow on MiLB First Pitch: https://stza.co/+vMP5-2u\n\nShop: https://stza.co/+vMP5-K\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Buck Monday
STATUS:CONFIRMED
CREATED:20180213T144508Z
LAST-MODIFIED:20180213T144508Z
TRANSP:OPAQUE
END:VEVENT
* Hot Rods @ Snappers
<2018-07-18 Wed 19:00-22:00>
:PROPERTIES:
:ID:       dggDL-XAr7owxXpWAgPOSC7m@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Hot Rods @ Snappers Hot Rods @ Snappers

Follow on MiLB First Pitch  https //stza.co/+wSKk-s

Shop  https //stza.co/+wSKk-3w

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Hot Rods @ Snappers
END:VALARM
DTSTART:20180719T000000Z
DTEND:20180719T030000Z
UID:dggDL-XAr7owxXpWAgPOSC7m@stanza.co
SUMMARY:Hot Rods @ Snappers
DESCRIPTION:Hot Rods @ Snappers\n\nFollow on MiLB First Pitch: https://stza.co/+wSKk-s\n\nShop: https://stza.co/+wSKk-3w\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144508Z
LAST-MODIFIED:20180213T144508Z
TRANSP:OPAQUE
END:VEVENT
* Hot Rods @ Snappers
<2018-07-19 Thu 19:00-22:00>
:PROPERTIES:
:ID:       _CfUszuZYTk3x4kRxczejRpY@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Hot Rods @ Snappers Hot Rods @ Snappers

Follow on MiLB First Pitch  https //stza.co/+wSKl-3L

Shop  https //stza.co/+wSKl-2U

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Hot Rods @ Snappers
END:VALARM
DTSTART:20180720T000000Z
DTEND:20180720T030000Z
UID:_CfUszuZYTk3x4kRxczejRpY@stanza.co
SUMMARY:Hot Rods @ Snappers
DESCRIPTION:Hot Rods @ Snappers\n\nFollow on MiLB First Pitch: https://stza.co/+wSKl-3L\n\nShop: https://stza.co/+wSKl-2U\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144508Z
LAST-MODIFIED:20180213T144508Z
TRANSP:OPAQUE
END:VEVENT
* Hot Rods @ Snappers
<2018-07-20 Fri 19:00-22:00>
:PROPERTIES:
:ID:       Xs4GaCl-rrE21jzCYoqANFEL@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Hot Rods @ Snappers Hot Rods @ Snappers

Follow on MiLB First Pitch  https //stza.co/+wSKm-1e

Shop  https //stza.co/+wSKm-39

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Hot Rods @ Snappers
END:VALARM
DTSTART:20180721T000000Z
DTEND:20180721T030000Z
UID:Xs4GaCl-rrE21jzCYoqANFEL@stanza.co
SUMMARY:Hot Rods @ Snappers
DESCRIPTION:Hot Rods @ Snappers\n\nFollow on MiLB First Pitch: https://stza.co/+wSKm-1e\n\nShop: https://stza.co/+wSKm-39\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144508Z
LAST-MODIFIED:20180213T144508Z
TRANSP:OPAQUE
END:VEVENT
* Hot Rods @ Timber Rattlers
<2018-07-21 Sat 18:35-21:35>
:PROPERTIES:
:ID:       VItogqt-Ymhhty4G5Zyan9Xs@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Hot Rods @ Timber Rattlers Hot Rods @ Timber Rattlers

Follow on MiLB First Pitch  https //stza.co/+vMQQ-11

Shop  https //stza.co/+vMQQ-1Z

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Hot Rods @ Timber Rattlers
END:VALARM
DTSTART:20180721T233500Z
DTEND:20180722T023500Z
UID:VItogqt-Ymhhty4G5Zyan9Xs@stanza.co
SUMMARY:Hot Rods @ Timber Rattlers
DESCRIPTION:Hot Rods @ Timber Rattlers\n\nFollow on MiLB First Pitch: https://stza.co/+vMQQ-11\n\nShop: https://stza.co/+vMQQ-1Z\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144508Z
LAST-MODIFIED:20180213T144508Z
TRANSP:OPAQUE
END:VEVENT
* Hot Rods @ Timber Rattlers
<2018-07-22 Sun 13:05-16:05>
:PROPERTIES:
:ID:       KN2DItm72ijM0EH-8_FhFHwa@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Hot Rods @ Timber Rattlers Hot Rods @ Timber Rattlers

Follow on MiLB First Pitch  https //stza.co/+vMQR-3B

Shop  https //stza.co/+vMQR-2

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Hot Rods @ Timber Rattlers
END:VALARM
DTSTART:20180722T180500Z
DTEND:20180722T210500Z
UID:KN2DItm72ijM0EH-8_FhFHwa@stanza.co
SUMMARY:Hot Rods @ Timber Rattlers
DESCRIPTION:Hot Rods @ Timber Rattlers\n\nFollow on MiLB First Pitch: https://stza.co/+vMQR-3B\n\nShop: https://stza.co/+vMQR-2\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144508Z
LAST-MODIFIED:20180213T144508Z
TRANSP:OPAQUE
END:VEVENT
* Hot Rods @ Timber Rattlers
<2018-07-23 Mon 12:05-15:05>
:PROPERTIES:
:ID:       ot1flZy5qxmOUUCBgdQXOG8Y@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Hot Rods @ Timber Rattlers Hot Rods @ Timber Rattlers

Follow on MiLB First Pitch  https //stza.co/+vo7$-2a

Shop  https //stza.co/+vo7$-2R

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Hot Rods @ Timber Rattlers
END:VALARM
DTSTART:20180723T170500Z
DTEND:20180723T200500Z
UID:ot1flZy5qxmOUUCBgdQXOG8Y@stanza.co
SUMMARY:Hot Rods @ Timber Rattlers
DESCRIPTION:Hot Rods @ Timber Rattlers\n\nFollow on MiLB First Pitch: https://stza.co/+vo7$-2a\n\nShop: https://stza.co/+vo7$-2R\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144508Z
LAST-MODIFIED:20180213T144508Z
TRANSP:OPAQUE
END:VEVENT
* Hot Rods vs. Loons
<2018-07-25 Wed 18:35-21:35>
:PROPERTIES:
:ID:       2BSXVtYerEhaIINFiS_8GJut@stanza.co
:LOCATION: Winning Wednesday
:STATUS:   CONFIRMED
:END:

Hot Rods vs. Loons Play baseball bingo and have the chance to win great prizes! 

Follow on MiLB First Pitch  https //stza.co/+vMP7-1s

Shop  https //stza.co/+vMP7-3r

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Hot Rods vs. Loons
END:VALARM
DTSTART:20180725T233500Z
DTEND:20180726T023500Z
UID:2BSXVtYerEhaIINFiS_8GJut@stanza.co
SUMMARY:Hot Rods vs. Loons
DESCRIPTION:Play baseball bingo and have the chance to win great prizes! \n\nFollow on MiLB First Pitch: https://stza.co/+vMP7-1s\n\nShop: https://stza.co/+vMP7-3r\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Winning Wednesday
STATUS:CONFIRMED
CREATED:20180213T144508Z
LAST-MODIFIED:20180213T144508Z
TRANSP:OPAQUE
END:VEVENT
* Hot Rods vs. Loons
<2018-07-26 Thu 18:35-21:35>
:PROPERTIES:
:ID:       IwuFZ8KkAhWdKCYQlk8fen2r@stanza.co
:LOCATION: Throwback Thursday 
:STATUS:   CONFIRMED
:END:

Hot Rods vs. Loons $2 Pepsi Products and $2 Domestic Beer

Follow on MiLB First Pitch  https //stza.co/+vMP8-24

Shop  https //stza.co/+vMP8-3T

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Hot Rods vs. Loons
END:VALARM
DTSTART:20180726T233500Z
DTEND:20180727T023500Z
UID:IwuFZ8KkAhWdKCYQlk8fen2r@stanza.co
SUMMARY:Hot Rods vs. Loons
DESCRIPTION:$2 Pepsi Products and $2 Domestic Beer\n\nFollow on MiLB First Pitch: https://stza.co/+vMP8-24\n\nShop: https://stza.co/+vMP8-3T\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Throwback Thursday 
STATUS:CONFIRMED
CREATED:20180213T144508Z
LAST-MODIFIED:20180213T144508Z
TRANSP:OPAQUE
END:VEVENT
* Hot Rods vs. Loons
<2018-07-27 Fri 18:35-21:35>
:PROPERTIES:
:ID:       yiGOPHcCE_CsqIPziLpV9ac5@stanza.co
:LOCATION: Fireworks Friday
:STATUS:   CONFIRMED
:END:

Hot Rods vs. Loons Enjoy post-game fireworks every Friday home game!



Follow on MiLB First Pitch  https //stza.co/+vMPb-2x

Shop  https //stza.co/+vMPb-13

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Hot Rods vs. Loons
END:VALARM
DTSTART:20180727T233500Z
DTEND:20180728T023500Z
UID:yiGOPHcCE_CsqIPziLpV9ac5@stanza.co
SUMMARY:Hot Rods vs. Loons
DESCRIPTION:Enjoy post-game fireworks every Friday home game!\n\n\n\nFollow on MiLB First Pitch: https://stza.co/+vMPb-2x\n\nShop: https://stza.co/+vMPb-13\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Fireworks Friday
STATUS:CONFIRMED
CREATED:20180213T144508Z
LAST-MODIFIED:20180213T144508Z
TRANSP:OPAQUE
END:VEVENT
* Hot Rods vs. TinCaps
<2018-07-28 Sat 18:35-21:35>
:PROPERTIES:
:ID:       xpSiKna5_KweOllTvIZY8WfE@stanza.co
:LOCATION: Super Saturday
:STATUS:   CONFIRMED
:END:

Hot Rods vs. TinCaps Saturdays include specialty giveaways and entertainment! 

Margaritaville night is back again! Bucket Hat giveaway by Ashley Homestore and jersey auction. 

Follow on MiLB First Pitch  https //stza.co/+vMPc-3K

Shop  https //stza.co/+vMPc-2j

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Hot Rods vs. TinCaps
END:VALARM
DTSTART:20180728T233500Z
DTEND:20180729T023500Z
UID:xpSiKna5_KweOllTvIZY8WfE@stanza.co
SUMMARY:Hot Rods vs. TinCaps
DESCRIPTION:Saturdays include specialty giveaways and entertainment! \n\nMargaritaville night is back again! Bucket Hat giveaway by Ashley Homestore and jersey auction. \n\nFollow on MiLB First Pitch: https://stza.co/+vMPc-3K\n\nShop: https://stza.co/+vMPc-2j\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Super Saturday
STATUS:CONFIRMED
CREATED:20180213T144508Z
LAST-MODIFIED:20180213T144508Z
TRANSP:OPAQUE
END:VEVENT
* Hot Rods vs. TinCaps
<2018-07-29 Sun 14:05-17:05>
:PROPERTIES:
:ID:       _bawGriCTQB9gs4IV8ecFj2F@stanza.co
:LOCATION: Sunday Funday
:STATUS:   CONFIRMED
:END:

Hot Rods vs. TinCaps Join us for Sunday Funday! First 500 kids eat free with paid ticket! Postgame autographs and postgame kids run the bases! 

Follow on MiLB First Pitch  https //stza.co/+vMPf-29

Shop  https //stza.co/+vMPf-3x

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Hot Rods vs. TinCaps
END:VALARM
DTSTART:20180729T190500Z
DTEND:20180729T220500Z
UID:_bawGriCTQB9gs4IV8ecFj2F@stanza.co
SUMMARY:Hot Rods vs. TinCaps
DESCRIPTION:Join us for Sunday Funday! First 500 kids eat free with paid ticket! Postgame autographs and postgame kids run the bases! \n\nFollow on MiLB First Pitch: https://stza.co/+vMPf-29\n\nShop: https://stza.co/+vMPf-3x\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Sunday Funday
STATUS:CONFIRMED
CREATED:20180213T144508Z
LAST-MODIFIED:20180213T144508Z
TRANSP:OPAQUE
END:VEVENT
* Hot Rods vs. TinCaps
<2018-07-30 Mon 18:35-21:35>
:PROPERTIES:
:ID:       vMnzDdlNpQlag59CQwqAtujV@stanza.co
:LOCATION: Buck Monday
:STATUS:   CONFIRMED
:END:

Hot Rods vs. TinCaps $1 Popcorn and $1 Pepsi Products 

Follow on MiLB First Pitch  https //stza.co/+vMPg-3J

Shop  https //stza.co/+vMPg-2c

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Hot Rods vs. TinCaps
END:VALARM
DTSTART:20180730T233500Z
DTEND:20180731T023500Z
UID:vMnzDdlNpQlag59CQwqAtujV@stanza.co
SUMMARY:Hot Rods vs. TinCaps
DESCRIPTION:$1 Popcorn and $1 Pepsi Products \n\nFollow on MiLB First Pitch: https://stza.co/+vMPg-3J\n\nShop: https://stza.co/+vMPg-2c\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Buck Monday
STATUS:CONFIRMED
CREATED:20180213T144508Z
LAST-MODIFIED:20180213T144508Z
TRANSP:OPAQUE
END:VEVENT
* Hot Rods vs. TinCaps
<2018-07-31 Tue 12:05-15:05>
:PROPERTIES:
:ID:       M1n_kUTkSk9lmrqzITpHIQcX@stanza.co
:LOCATION: Tail Waggin' Tuesday
:STATUS:   CONFIRMED
:END:

Hot Rods vs. TinCaps $1 Hot Dogs. Dogs are welcome EVERY Tuesday home game and get in FREE with their owner.

Follow on MiLB First Pitch  https //stza.co/+vMPi-3U

Shop  https //stza.co/+vMPi-1r

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Hot Rods vs. TinCaps
END:VALARM
DTSTART:20180731T170500Z
DTEND:20180731T200500Z
UID:M1n_kUTkSk9lmrqzITpHIQcX@stanza.co
SUMMARY:Hot Rods vs. TinCaps
DESCRIPTION:$1 Hot Dogs. Dogs are welcome EVERY Tuesday home game and get in FREE with their owner.\n\nFollow on MiLB First Pitch: https://stza.co/+vMPi-3U\n\nShop: https://stza.co/+vMPi-1r\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Tail Waggin' Tuesday
STATUS:CONFIRMED
CREATED:20180213T144508Z
LAST-MODIFIED:20180213T144508Z
TRANSP:OPAQUE
END:VEVENT
* Hot Rods @ Captains
<2018-08-01 Wed 18:00-21:00>
:PROPERTIES:
:ID:       8A2sC834Z_H39g3BdN8o-U4M@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Hot Rods @ Captains Hot Rods @ Captains

Follow on MiLB First Pitch  https //stza.co/+xBjj-j

Shop  https //stza.co/+xBjj-3

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Hot Rods @ Captains
END:VALARM
DTSTART:20180801T230000Z
DTEND:20180802T020000Z
UID:8A2sC834Z_H39g3BdN8o-U4M@stanza.co
SUMMARY:Hot Rods @ Captains
DESCRIPTION:Hot Rods @ Captains\n\nFollow on MiLB First Pitch: https://stza.co/+xBjj-j\n\nShop: https://stza.co/+xBjj-3\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144508Z
LAST-MODIFIED:20180213T144508Z
TRANSP:OPAQUE
END:VEVENT
* Hot Rods @ Captains
<2018-08-02 Thu 18:00-21:00>
:PROPERTIES:
:ID:       oWDnULrEIkARyJ91X7eLzVyx@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Hot Rods @ Captains Hot Rods @ Captains

Follow on MiLB First Pitch  https //stza.co/+xBjk-E

Shop  https //stza.co/+xBjk-1w

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Hot Rods @ Captains
END:VALARM
DTSTART:20180802T230000Z
DTEND:20180803T020000Z
UID:oWDnULrEIkARyJ91X7eLzVyx@stanza.co
SUMMARY:Hot Rods @ Captains
DESCRIPTION:Hot Rods @ Captains\n\nFollow on MiLB First Pitch: https://stza.co/+xBjk-E\n\nShop: https://stza.co/+xBjk-1w\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144508Z
LAST-MODIFIED:20180213T144508Z
TRANSP:OPAQUE
END:VEVENT
* Hot Rods @ Captains
<2018-08-03 Fri 18:00-21:00>
:PROPERTIES:
:ID:       -Qv_wuLYH4-rpLA3koDqlS-3@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Hot Rods @ Captains Hot Rods @ Captains

Follow on MiLB First Pitch  https //stza.co/+xBjn-F

Shop  https //stza.co/+xBjn-31

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Hot Rods @ Captains
END:VALARM
DTSTART:20180803T230000Z
DTEND:20180804T020000Z
UID:-Qv_wuLYH4-rpLA3koDqlS-3@stanza.co
SUMMARY:Hot Rods @ Captains
DESCRIPTION:Hot Rods @ Captains\n\nFollow on MiLB First Pitch: https://stza.co/+xBjn-F\n\nShop: https://stza.co/+xBjn-31\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144508Z
LAST-MODIFIED:20180213T144508Z
TRANSP:OPAQUE
END:VEVENT
* Hot Rods vs. Cubs
<2018-08-04 Sat 18:35-21:35>
:PROPERTIES:
:ID:       J3jrtYL3YY28zG9V-E9VwzzR@stanza.co
:LOCATION: Super Saturday
:STATUS:   CONFIRMED
:END:

Hot Rods vs. Cubs Saturdays include specialty giveaways and entertainment! 

Celebrate our wonderful city of Bowling Green, KY on Local Matters night featuring a shirt giveaway designed by one of our fans! 

Follow on MiLB First Pitch  https //stza.co/+vMPk-2b

Shop  https //stza.co/+vMPk-1u

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Hot Rods vs. Cubs
END:VALARM
DTSTART:20180804T233500Z
DTEND:20180805T023500Z
UID:J3jrtYL3YY28zG9V-E9VwzzR@stanza.co
SUMMARY:Hot Rods vs. Cubs
DESCRIPTION:Saturdays include specialty giveaways and entertainment! \n\nCelebrate our wonderful city of Bowling Green, KY on Local Matters night featuring a shirt giveaway designed by one of our fans! \n\nFollow on MiLB First Pitch: https://stza.co/+vMPk-2b\n\nShop: https://stza.co/+vMPk-1u\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Super Saturday
STATUS:CONFIRMED
CREATED:20180213T144508Z
LAST-MODIFIED:20180213T144508Z
TRANSP:OPAQUE
END:VEVENT
* Hot Rods vs. Cubs
<2018-08-05 Sun 14:05-17:05>
:PROPERTIES:
:ID:       bEjtldbAi0pBf95y-CUn-g0L@stanza.co
:LOCATION: Sunday Funday
:STATUS:   CONFIRMED
:END:

Hot Rods vs. Cubs Join us for Sunday Funday! First 500 kids eat free with paid ticket! Postgame autographs and postgame kids run the bases! 

Follow on MiLB First Pitch  https //stza.co/+vMPn-2U

Shop  https //stza.co/+vMPn-3C

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Hot Rods vs. Cubs
END:VALARM
DTSTART:20180805T190500Z
DTEND:20180805T220500Z
UID:bEjtldbAi0pBf95y-CUn-g0L@stanza.co
SUMMARY:Hot Rods vs. Cubs
DESCRIPTION:Join us for Sunday Funday! First 500 kids eat free with paid ticket! Postgame autographs and postgame kids run the bases! \n\nFollow on MiLB First Pitch: https://stza.co/+vMPn-2U\n\nShop: https://stza.co/+vMPn-3C\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Sunday Funday
STATUS:CONFIRMED
CREATED:20180213T144508Z
LAST-MODIFIED:20180213T144508Z
TRANSP:OPAQUE
END:VEVENT
* Hot Rods vs. Cubs
<2018-08-06 Mon 12:05-15:05>
:PROPERTIES:
:ID:       BWMDSxsgQKZojZnhTQqY1c8Z@stanza.co
:LOCATION: Buck Monday
:STATUS:   CONFIRMED
:END:

Hot Rods vs. Cubs $1 Popcorn and $1 Pepsi Products 

Follow on MiLB First Pitch  https //stza.co/+vMPp-1C

Shop  https //stza.co/+vMPp-1G

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Hot Rods vs. Cubs
END:VALARM
DTSTART:20180806T170500Z
DTEND:20180806T200500Z
UID:BWMDSxsgQKZojZnhTQqY1c8Z@stanza.co
SUMMARY:Hot Rods vs. Cubs
DESCRIPTION:$1 Popcorn and $1 Pepsi Products \n\nFollow on MiLB First Pitch: https://stza.co/+vMPp-1C\n\nShop: https://stza.co/+vMPp-1G\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Buck Monday
STATUS:CONFIRMED
CREATED:20180213T144508Z
LAST-MODIFIED:20180213T144508Z
TRANSP:OPAQUE
END:VEVENT
* Hot Rods vs. Whitecaps
<2018-08-08 Wed 18:35-21:35>
:PROPERTIES:
:ID:       6PqxkpKLXg4AAgbGo8V37Axw@stanza.co
:LOCATION: Winning Wednesday
:STATUS:   CONFIRMED
:END:

Hot Rods vs. Whitecaps Play baseball bingo and have the chance to win great prizes! 

Follow on MiLB First Pitch  https //stza.co/+vMPr-j

Shop  https //stza.co/+vMPr-P

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Hot Rods vs. Whitecaps
END:VALARM
DTSTART:20180808T233500Z
DTEND:20180809T023500Z
UID:6PqxkpKLXg4AAgbGo8V37Axw@stanza.co
SUMMARY:Hot Rods vs. Whitecaps
DESCRIPTION:Play baseball bingo and have the chance to win great prizes! \n\nFollow on MiLB First Pitch: https://stza.co/+vMPr-j\n\nShop: https://stza.co/+vMPr-P\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Winning Wednesday
STATUS:CONFIRMED
CREATED:20180213T144508Z
LAST-MODIFIED:20180213T144508Z
TRANSP:OPAQUE
END:VEVENT
* Hot Rods vs. Whitecaps
<2018-08-09 Thu 18:35-21:35>
:PROPERTIES:
:ID:       _r1ExbaD-k_SxKuaItU19qUq@stanza.co
:LOCATION: Throwback Thursday 
:STATUS:   CONFIRMED
:END:

Hot Rods vs. Whitecaps $2 Pepsi Products and $2 Domestic Beer

Follow on MiLB First Pitch  https //stza.co/+vMPs-2S

Shop  https //stza.co/+vMPs-X

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Hot Rods vs. Whitecaps
END:VALARM
DTSTART:20180809T233500Z
DTEND:20180810T023500Z
UID:_r1ExbaD-k_SxKuaItU19qUq@stanza.co
SUMMARY:Hot Rods vs. Whitecaps
DESCRIPTION:$2 Pepsi Products and $2 Domestic Beer\n\nFollow on MiLB First Pitch: https://stza.co/+vMPs-2S\n\nShop: https://stza.co/+vMPs-X\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Throwback Thursday 
STATUS:CONFIRMED
CREATED:20180213T144508Z
LAST-MODIFIED:20180213T144508Z
TRANSP:OPAQUE
END:VEVENT
* Hot Rods vs. Whitecaps
<2018-08-10 Fri 18:35-21:35>
:PROPERTIES:
:ID:       Xx7vnpJWki3aq64sTcOYx-BB@stanza.co
:LOCATION: Fireworks Friday
:STATUS:   CONFIRMED
:END:

Hot Rods vs. Whitecaps Enjoy post-game fireworks every Friday home game!

Dress up as your favorite princess or pirate and enjoy the game! Be sure to stay for post-game fireworks!

Follow on MiLB First Pitch  https //stza.co/+vMPu-1U

Shop  https //stza.co/+vMPu-2z

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Hot Rods vs. Whitecaps
END:VALARM
DTSTART:20180810T233500Z
DTEND:20180811T023500Z
UID:Xx7vnpJWki3aq64sTcOYx-BB@stanza.co
SUMMARY:Hot Rods vs. Whitecaps
DESCRIPTION:Enjoy post-game fireworks every Friday home game!\n\nDress up as your favorite princess or pirate and enjoy the game! Be sure to stay for post-game fireworks!\n\nFollow on MiLB First Pitch: https://stza.co/+vMPu-1U\n\nShop: https://stza.co/+vMPu-2z\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Fireworks Friday
STATUS:CONFIRMED
CREATED:20180213T144508Z
LAST-MODIFIED:20180213T144508Z
TRANSP:OPAQUE
END:VEVENT
* Hot Rods @ Lugnuts
<2018-08-11 Sat 18:05-21:05>
:PROPERTIES:
:ID:       2wrAeuwrGhLRXoaawIzwzNZA@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Hot Rods @ Lugnuts Hot Rods @ Lugnuts

Follow on MiLB First Pitch  https //stza.co/+vMQw-2

Shop  https //stza.co/+vMQw-3V

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Hot Rods @ Lugnuts
END:VALARM
DTSTART:20180811T230500Z
DTEND:20180812T020500Z
UID:2wrAeuwrGhLRXoaawIzwzNZA@stanza.co
SUMMARY:Hot Rods @ Lugnuts
DESCRIPTION:Hot Rods @ Lugnuts\n\nFollow on MiLB First Pitch: https://stza.co/+vMQw-2\n\nShop: https://stza.co/+vMQw-3V\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144508Z
LAST-MODIFIED:20180213T144508Z
TRANSP:OPAQUE
END:VEVENT
* Hot Rods @ Lugnuts
<2018-08-12 Sun 12:05-15:05>
:PROPERTIES:
:ID:       m74YC4fDzF6lxarsOAo79x5D@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Hot Rods @ Lugnuts Hot Rods @ Lugnuts

Follow on MiLB First Pitch  https //stza.co/+xZUg-17

Shop  https //stza.co/+xZUg-2f

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Hot Rods @ Lugnuts
END:VALARM
DTSTART:20180812T170500Z
DTEND:20180812T200500Z
UID:m74YC4fDzF6lxarsOAo79x5D@stanza.co
SUMMARY:Hot Rods @ Lugnuts
DESCRIPTION:Hot Rods @ Lugnuts\n\nFollow on MiLB First Pitch: https://stza.co/+xZUg-17\n\nShop: https://stza.co/+xZUg-2f\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144508Z
LAST-MODIFIED:20180213T144508Z
TRANSP:OPAQUE
END:VEVENT
* Hot Rods @ Lugnuts
<2018-08-13 Mon 18:05-21:05>
:PROPERTIES:
:ID:       ncUTclmVurAIK683YMj4QvKn@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Hot Rods @ Lugnuts Hot Rods @ Lugnuts

Follow on MiLB First Pitch  https //stza.co/+vMQy-a

Shop  https //stza.co/+vMQy-2B

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Hot Rods @ Lugnuts
END:VALARM
DTSTART:20180813T230500Z
DTEND:20180814T020500Z
UID:ncUTclmVurAIK683YMj4QvKn@stanza.co
SUMMARY:Hot Rods @ Lugnuts
DESCRIPTION:Hot Rods @ Lugnuts\n\nFollow on MiLB First Pitch: https://stza.co/+vMQy-a\n\nShop: https://stza.co/+vMQy-2B\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144508Z
LAST-MODIFIED:20180213T144508Z
TRANSP:OPAQUE
END:VEVENT
* Hot Rods @ Lugnuts
<2018-08-14 Tue 18:05-21:05>
:PROPERTIES:
:ID:       QyVqruKoxt07kYGfhEaaN6aI@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Hot Rods @ Lugnuts Hot Rods @ Lugnuts

Follow on MiLB First Pitch  https //stza.co/+vMQz-2H

Shop  https //stza.co/+vMQz-3i

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Hot Rods @ Lugnuts
END:VALARM
DTSTART:20180814T230500Z
DTEND:20180815T020500Z
UID:QyVqruKoxt07kYGfhEaaN6aI@stanza.co
SUMMARY:Hot Rods @ Lugnuts
DESCRIPTION:Hot Rods @ Lugnuts\n\nFollow on MiLB First Pitch: https://stza.co/+vMQz-2H\n\nShop: https://stza.co/+vMQz-3i\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144508Z
LAST-MODIFIED:20180213T144508Z
TRANSP:OPAQUE
END:VEVENT
* Hot Rods @ Loons
<2018-08-15 Wed 18:05-21:05>
:PROPERTIES:
:ID:       K1MtmWtlogVC-Gjk0w0sMX2V@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Hot Rods @ Loons Hot Rods @ Loons

Follow on MiLB First Pitch  https //stza.co/+vMQh-2U

Shop  https //stza.co/+vMQh-x

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Hot Rods @ Loons
END:VALARM
DTSTART:20180815T230500Z
DTEND:20180816T020500Z
UID:K1MtmWtlogVC-Gjk0w0sMX2V@stanza.co
SUMMARY:Hot Rods @ Loons
DESCRIPTION:Hot Rods @ Loons\n\nFollow on MiLB First Pitch: https://stza.co/+vMQh-2U\n\nShop: https://stza.co/+vMQh-x\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144508Z
LAST-MODIFIED:20180213T144508Z
TRANSP:OPAQUE
END:VEVENT
* Hot Rods @ Loons
<2018-08-16 Thu 18:05-21:05>
:PROPERTIES:
:ID:       77JwsrGzAtXKRaSNk2_S-a45@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Hot Rods @ Loons Hot Rods @ Loons

Follow on MiLB First Pitch  https //stza.co/+vMQi-1l

Shop  https //stza.co/+vMQi-26

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Hot Rods @ Loons
END:VALARM
DTSTART:20180816T230500Z
DTEND:20180817T020500Z
UID:77JwsrGzAtXKRaSNk2_S-a45@stanza.co
SUMMARY:Hot Rods @ Loons
DESCRIPTION:Hot Rods @ Loons\n\nFollow on MiLB First Pitch: https://stza.co/+vMQi-1l\n\nShop: https://stza.co/+vMQi-26\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144508Z
LAST-MODIFIED:20180213T144508Z
TRANSP:OPAQUE
END:VEVENT
* Hot Rods @ Loons
<2018-08-17 Fri 18:05-21:05>
:PROPERTIES:
:ID:       9vpfbYSjdMaHaCA3FcTAx82A@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Hot Rods @ Loons Hot Rods @ Loons

Follow on MiLB First Pitch  https //stza.co/+vMQj-$

Shop  https //stza.co/+vMQj-1a

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Hot Rods @ Loons
END:VALARM
DTSTART:20180817T230500Z
DTEND:20180818T020500Z
UID:9vpfbYSjdMaHaCA3FcTAx82A@stanza.co
SUMMARY:Hot Rods @ Loons
DESCRIPTION:Hot Rods @ Loons\n\nFollow on MiLB First Pitch: https://stza.co/+vMQj-$\n\nShop: https://stza.co/+vMQj-1a\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144508Z
LAST-MODIFIED:20180213T144508Z
TRANSP:OPAQUE
END:VEVENT
* Hot Rods @ Dragons
<2018-08-18 Sat 18:00-21:00>
:PROPERTIES:
:ID:       P1iuoqxLWxiediAh5PCU59aE@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Hot Rods @ Dragons Hot Rods @ Dragons

Follow on MiLB First Pitch  https //stza.co/+vMQ0-2$

Shop  https //stza.co/+vMQ0-30

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Hot Rods @ Dragons
END:VALARM
DTSTART:20180818T230000Z
DTEND:20180819T020000Z
UID:P1iuoqxLWxiediAh5PCU59aE@stanza.co
SUMMARY:Hot Rods @ Dragons
DESCRIPTION:Hot Rods @ Dragons\n\nFollow on MiLB First Pitch: https://stza.co/+vMQ0-2$\n\nShop: https://stza.co/+vMQ0-30\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144508Z
LAST-MODIFIED:20180213T144508Z
TRANSP:OPAQUE
END:VEVENT
* Hot Rods @ Dragons
<2018-08-19 Sun 13:00-16:00>
:PROPERTIES:
:ID:       9qY-keN0X5EgdRnRpx8iS3N5@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Hot Rods @ Dragons Hot Rods @ Dragons

Follow on MiLB First Pitch  https //stza.co/+vMQ1-1E

Shop  https //stza.co/+vMQ1-1a

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Hot Rods @ Dragons
END:VALARM
DTSTART:20180819T180000Z
DTEND:20180819T210000Z
UID:9qY-keN0X5EgdRnRpx8iS3N5@stanza.co
SUMMARY:Hot Rods @ Dragons
DESCRIPTION:Hot Rods @ Dragons\n\nFollow on MiLB First Pitch: https://stza.co/+vMQ1-1E\n\nShop: https://stza.co/+vMQ1-1a\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144508Z
LAST-MODIFIED:20180213T144508Z
TRANSP:OPAQUE
END:VEVENT
* Hot Rods @ Dragons
<2018-08-20 Mon 18:00-21:00>
:PROPERTIES:
:ID:       N25EakLLRx63dEh0lfOhTWpR@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Hot Rods @ Dragons Hot Rods @ Dragons

Follow on MiLB First Pitch  https //stza.co/+vMQ2-J

Shop  https //stza.co/+vMQ2-m

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Hot Rods @ Dragons
END:VALARM
DTSTART:20180820T230000Z
DTEND:20180821T020000Z
UID:N25EakLLRx63dEh0lfOhTWpR@stanza.co
SUMMARY:Hot Rods @ Dragons
DESCRIPTION:Hot Rods @ Dragons\n\nFollow on MiLB First Pitch: https://stza.co/+vMQ2-J\n\nShop: https://stza.co/+vMQ2-m\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144508Z
LAST-MODIFIED:20180213T144508Z
TRANSP:OPAQUE
END:VEVENT
* Hot Rods vs. Lugnuts
<2018-08-21 Tue 18:35-21:35>
:PROPERTIES:
:ID:       6Cinwb9rDgmbCwu88GgoNtRH@stanza.co
:LOCATION: Tail Waggin' Tuesday
:STATUS:   CONFIRMED
:END:

Hot Rods vs. Lugnuts $1 Hot Dogs. Dogs are welcome EVERY Tuesday home game and get in FREE with their owner.

Follow on MiLB First Pitch  https //stza.co/+vMPw-A

Shop  https //stza.co/+vMPw-3L

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Hot Rods vs. Lugnuts
END:VALARM
DTSTART:20180821T233500Z
DTEND:20180822T023500Z
UID:6Cinwb9rDgmbCwu88GgoNtRH@stanza.co
SUMMARY:Hot Rods vs. Lugnuts
DESCRIPTION:$1 Hot Dogs. Dogs are welcome EVERY Tuesday home game and get in FREE with their owner.\n\nFollow on MiLB First Pitch: https://stza.co/+vMPw-A\n\nShop: https://stza.co/+vMPw-3L\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Tail Waggin' Tuesday
STATUS:CONFIRMED
CREATED:20180213T144508Z
LAST-MODIFIED:20180213T144508Z
TRANSP:OPAQUE
END:VEVENT
* Hot Rods vs. Lugnuts
<2018-08-22 Wed 18:35-21:35>
:PROPERTIES:
:ID:       H1HMXXPYwAw0Di1cLCT5QhFG@stanza.co
:LOCATION: Winning Wednesday
:STATUS:   CONFIRMED
:END:

Hot Rods vs. Lugnuts Play baseball bingo and have the chance to win great prizes! 

Follow on MiLB First Pitch  https //stza.co/+vMPz-U

Shop  https //stza.co/+vMPz-F

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Hot Rods vs. Lugnuts
END:VALARM
DTSTART:20180822T233500Z
DTEND:20180823T023500Z
UID:H1HMXXPYwAw0Di1cLCT5QhFG@stanza.co
SUMMARY:Hot Rods vs. Lugnuts
DESCRIPTION:Play baseball bingo and have the chance to win great prizes! \n\nFollow on MiLB First Pitch: https://stza.co/+vMPz-U\n\nShop: https://stza.co/+vMPz-F\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Winning Wednesday
STATUS:CONFIRMED
CREATED:20180213T144508Z
LAST-MODIFIED:20180213T144508Z
TRANSP:OPAQUE
END:VEVENT
* Hot Rods vs. Lugnuts
<2018-08-23 Thu 18:35-21:35>
:PROPERTIES:
:ID:       QAxJjPBWdtRtOBgPk3PzVw42@stanza.co
:LOCATION: Throwback Thursday 
:STATUS:   CONFIRMED
:END:

Hot Rods vs. Lugnuts $2 Pepsi Products and $2 Domestic Beer



Follow on MiLB First Pitch  https //stza.co/+vMPB-29

Shop  https //stza.co/+vMPB-2v

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Hot Rods vs. Lugnuts
END:VALARM
DTSTART:20180823T233500Z
DTEND:20180824T023500Z
UID:QAxJjPBWdtRtOBgPk3PzVw42@stanza.co
SUMMARY:Hot Rods vs. Lugnuts
DESCRIPTION:$2 Pepsi Products and $2 Domestic Beer\n\n\n\nFollow on MiLB First Pitch: https://stza.co/+vMPB-29\n\nShop: https://stza.co/+vMPB-2v\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Throwback Thursday 
STATUS:CONFIRMED
CREATED:20180213T144508Z
LAST-MODIFIED:20180213T144508Z
TRANSP:OPAQUE
END:VEVENT
* Hot Rods vs. Captains
<2018-08-24 Fri 18:35-21:35>
:PROPERTIES:
:ID:       2eCvmc-n2VSue7pJXtMBabYI@stanza.co
:LOCATION: Fireworks Friday
:STATUS:   CONFIRMED
:END:

Hot Rods vs. Captains Enjoy post-game fireworks every Friday home game!



Follow on MiLB First Pitch  https //stza.co/+vMPD-1y

Shop  https //stza.co/+vMPD-1G

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Hot Rods vs. Captains
END:VALARM
DTSTART:20180824T233500Z
DTEND:20180825T023500Z
UID:2eCvmc-n2VSue7pJXtMBabYI@stanza.co
SUMMARY:Hot Rods vs. Captains
DESCRIPTION:Enjoy post-game fireworks every Friday home game!\n\n\n\nFollow on MiLB First Pitch: https://stza.co/+vMPD-1y\n\nShop: https://stza.co/+vMPD-1G\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Fireworks Friday
STATUS:CONFIRMED
CREATED:20180213T144508Z
LAST-MODIFIED:20180213T144508Z
TRANSP:OPAQUE
END:VEVENT
* Hot Rods vs. Captains
<2018-08-25 Sat 18:35-21:35>
:PROPERTIES:
:ID:       l3IHlWYsXBrv_0FRuXhr5Sew@stanza.co
:LOCATION: Super Saturday
:STATUS:   CONFIRMED
:END:

Hot Rods vs. Captains Saturdays include specialty giveaways and entertainment! 

Camo Hat giveaway and jersey auction

Follow on MiLB First Pitch  https //stza.co/+vMPE-25

Shop  https //stza.co/+vMPE-1n

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Hot Rods vs. Captains
END:VALARM
DTSTART:20180825T233500Z
DTEND:20180826T023500Z
UID:l3IHlWYsXBrv_0FRuXhr5Sew@stanza.co
SUMMARY:Hot Rods vs. Captains
DESCRIPTION:Saturdays include specialty giveaways and entertainment! \n\nCamo Hat giveaway and jersey auction\n\nFollow on MiLB First Pitch: https://stza.co/+vMPE-25\n\nShop: https://stza.co/+vMPE-1n\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Super Saturday
STATUS:CONFIRMED
CREATED:20180213T144508Z
LAST-MODIFIED:20180213T144508Z
TRANSP:OPAQUE
END:VEVENT
* Hot Rods vs. Captains
<2018-08-26 Sun 14:05-17:05>
:PROPERTIES:
:ID:       qwsfUKc4JcNc3SaVhvPIgDhI@stanza.co
:LOCATION: Video Game Night
:STATUS:   CONFIRMED
:END:

Hot Rods vs. Captains 

Join us for Sunday Funday! First 500 kids eat free with paid ticket! Postgame autographs and postgame kids run the bases! 

Follow on MiLB First Pitch  https //stza.co/+vMPH-3I

Shop  https //stza.co/+vMPH-3y

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Hot Rods vs. Captains
END:VALARM
DTSTART:20180826T190500Z
DTEND:20180826T220500Z
UID:qwsfUKc4JcNc3SaVhvPIgDhI@stanza.co
SUMMARY:Hot Rods vs. Captains
DESCRIPTION:\n\nJoin us for Sunday Funday! First 500 kids eat free with paid ticket! Postgame autographs and postgame kids run the bases! \n\nFollow on MiLB First Pitch: https://stza.co/+vMPH-3I\n\nShop: https://stza.co/+vMPH-3y\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Video Game Night
STATUS:CONFIRMED
CREATED:20180213T144508Z
LAST-MODIFIED:20180213T144508Z
TRANSP:OPAQUE
END:VEVENT
* Hot Rods vs. Captains
<2018-08-27 Mon 12:05-15:05>
:PROPERTIES:
:ID:       VKZa1TVL5HYbjhDPRoJLNisi@stanza.co
:LOCATION: Buck Monday
:STATUS:   CONFIRMED
:END:

Hot Rods vs. Captains $1 Popcorn and $1 Pepsi Products 

Follow on MiLB First Pitch  https //stza.co/+vMPJ-3y

Shop  https //stza.co/+vMPJ-38

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Hot Rods vs. Captains
END:VALARM
DTSTART:20180827T170500Z
DTEND:20180827T200500Z
UID:VKZa1TVL5HYbjhDPRoJLNisi@stanza.co
SUMMARY:Hot Rods vs. Captains
DESCRIPTION:$1 Popcorn and $1 Pepsi Products \n\nFollow on MiLB First Pitch: https://stza.co/+vMPJ-3y\n\nShop: https://stza.co/+vMPJ-38\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Buck Monday
STATUS:CONFIRMED
CREATED:20180213T144508Z
LAST-MODIFIED:20180213T144508Z
TRANSP:OPAQUE
END:VEVENT
* Hot Rods @ Cubs
<2018-08-29 Wed 18:05-21:05>
:PROPERTIES:
:ID:       4tkw4JlYTViSMjfqHJWiY8xL@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Hot Rods @ Cubs Hot Rods @ Cubs

Follow on MiLB First Pitch  https //stza.co/+vMQG-2Z

Shop  https //stza.co/+vMQG-2w

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Hot Rods @ Cubs
END:VALARM
DTSTART:20180829T230500Z
DTEND:20180830T020500Z
UID:4tkw4JlYTViSMjfqHJWiY8xL@stanza.co
SUMMARY:Hot Rods @ Cubs
DESCRIPTION:Hot Rods @ Cubs\n\nFollow on MiLB First Pitch: https://stza.co/+vMQG-2Z\n\nShop: https://stza.co/+vMQG-2w\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144508Z
LAST-MODIFIED:20180213T144508Z
TRANSP:OPAQUE
END:VEVENT
* Hot Rods @ Cubs
<2018-08-30 Thu 18:05-21:05>
:PROPERTIES:
:ID:       XloKAc6UJvmay16wwXzTdTgO@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Hot Rods @ Cubs Hot Rods @ Cubs

Follow on MiLB First Pitch  https //stza.co/+vMQH-3z

Shop  https //stza.co/+vMQH-g

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Hot Rods @ Cubs
END:VALARM
DTSTART:20180830T230500Z
DTEND:20180831T020500Z
UID:XloKAc6UJvmay16wwXzTdTgO@stanza.co
SUMMARY:Hot Rods @ Cubs
DESCRIPTION:Hot Rods @ Cubs\n\nFollow on MiLB First Pitch: https://stza.co/+vMQH-3z\n\nShop: https://stza.co/+vMQH-g\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144508Z
LAST-MODIFIED:20180213T144508Z
TRANSP:OPAQUE
END:VEVENT
* Hot Rods @ Cubs
<2018-08-31 Fri 18:35-21:35>
:PROPERTIES:
:ID:       vcqL4UnNIjZiDrdum3O0Hgvw@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Hot Rods @ Cubs Hot Rods @ Cubs

Follow on MiLB First Pitch  https //stza.co/+vMQI-3R

Shop  https //stza.co/+vMQI-2t

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Hot Rods @ Cubs
END:VALARM
DTSTART:20180831T233500Z
DTEND:20180901T023500Z
UID:vcqL4UnNIjZiDrdum3O0Hgvw@stanza.co
SUMMARY:Hot Rods @ Cubs
DESCRIPTION:Hot Rods @ Cubs\n\nFollow on MiLB First Pitch: https://stza.co/+vMQI-3R\n\nShop: https://stza.co/+vMQI-2t\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144508Z
LAST-MODIFIED:20180213T144508Z
TRANSP:OPAQUE
END:VEVENT
* Hot Rods vs. Dragons
<2018-09-01 Sat 18:35-21:35>
:PROPERTIES:
:ID:       0jG2F7Jm5qS_o4TKnepASlsz@stanza.co
:LOCATION: Super Saturday
:STATUS:   CONFIRMED
:END:

Hot Rods vs. Dragons Saturdays include specialty giveaways and entertainment! 

Septembeer is back with a glass giveaway!

Follow on MiLB First Pitch  https //stza.co/+vMPK-2f

Shop  https //stza.co/+vMPK-y

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Hot Rods vs. Dragons
END:VALARM
DTSTART:20180901T233500Z
DTEND:20180902T023500Z
UID:0jG2F7Jm5qS_o4TKnepASlsz@stanza.co
SUMMARY:Hot Rods vs. Dragons
DESCRIPTION:Saturdays include specialty giveaways and entertainment! \n\nSeptembeer is back with a glass giveaway!\n\nFollow on MiLB First Pitch: https://stza.co/+vMPK-2f\n\nShop: https://stza.co/+vMPK-y\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Super Saturday
STATUS:CONFIRMED
CREATED:20180213T144508Z
LAST-MODIFIED:20180213T144508Z
TRANSP:OPAQUE
END:VEVENT
* Hot Rods vs. Dragons
<2018-09-02 Sun 18:35-21:35>
:PROPERTIES:
:ID:       S3Fh76ZdY_BH_iOWS13t2DT6@stanza.co
:LOCATION: Sunday Funday
:STATUS:   CONFIRMED
:END:

Hot Rods vs. Dragons Join us for Sunday Funday! First 500 kids eat free with paid ticket! Postgame autographs and postgame kids run the bases! 

Follow on MiLB First Pitch  https //stza.co/+vMPN-1V

Shop  https //stza.co/+vMPN-2b

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Hot Rods vs. Dragons
END:VALARM
DTSTART:20180902T233500Z
DTEND:20180903T023500Z
UID:S3Fh76ZdY_BH_iOWS13t2DT6@stanza.co
SUMMARY:Hot Rods vs. Dragons
DESCRIPTION:Join us for Sunday Funday! First 500 kids eat free with paid ticket! Postgame autographs and postgame kids run the bases! \n\nFollow on MiLB First Pitch: https://stza.co/+vMPN-1V\n\nShop: https://stza.co/+vMPN-2b\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Sunday Funday
STATUS:CONFIRMED
CREATED:20180213T144508Z
LAST-MODIFIED:20180213T144508Z
TRANSP:OPAQUE
END:VEVENT
* Hot Rods vs. Dragons
<2018-09-03 Mon 12:05-15:05>
:PROPERTIES:
:ID:       GBFk4RGzTmIzHKDe8ihT7kMh@stanza.co
:LOCATION: Buck Monday
:STATUS:   CONFIRMED
:END:

Hot Rods vs. Dragons $1 Popcorn and $1 Pepsi Products 

Follow on MiLB First Pitch  https //stza.co/+vMPO-2h

Shop  https //stza.co/+vMPO-1y

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Hot Rods vs. Dragons
END:VALARM
DTSTART:20180903T170500Z
DTEND:20180903T200500Z
UID:GBFk4RGzTmIzHKDe8ihT7kMh@stanza.co
SUMMARY:Hot Rods vs. Dragons
DESCRIPTION:$1 Popcorn and $1 Pepsi Products \n\nFollow on MiLB First Pitch: https://stza.co/+vMPO-2h\n\nShop: https://stza.co/+vMPO-1y\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Buck Monday
STATUS:CONFIRMED
CREATED:20180213T144508Z
LAST-MODIFIED:20180213T144508Z
TRANSP:OPAQUE
END:VEVENT
