#+TITLE:       Main Google calendar entries
#+AUTHOR:      Eric S Fraga
#+EMAIL:       e.fraga@ucl.ac.uk
#+DESCRIPTION: converted using the ical2org awk script
#+CATEGORY:    google
#+STARTUP:     hidestars
#+STARTUP:     overview

* COMMENT original iCal preamble

* Black Bears @ Scrappers
<2018-06-15 Fri>--<2018-06-14 Thu>
:PROPERTIES:
:ID:       wMoBICZoyBfqccxmyPaFwt3N@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Black Bears @ Scrappers Black Bears @ Scrappers

Follow on MiLB First Pitch  https //stza.co/+xMzo-w

Shop  https //stza.co/+xMzo-2i

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Black Bears @ Scrappers
END:VALARM
DTSTART;VALUE=DATE:20180615
DTEND;VALUE=DATE:20180615
UID:wMoBICZoyBfqccxmyPaFwt3N@stanza.co
SUMMARY:Black Bears @ Scrappers
DESCRIPTION:Black Bears @ Scrappers\n\nFollow on MiLB First Pitch: https://stza.co/+xMzo-w\n\nShop: https://stza.co/+xMzo-2i\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144605Z
LAST-MODIFIED:20180213T144605Z
TRANSP:OPAQUE
END:VEVENT
* Black Bears @ Scrappers
<2018-06-16 Sat>--<2018-06-15 Fri>
:PROPERTIES:
:ID:       7PnUZXGGP3hLrp_7C0EGkJ8N@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Black Bears @ Scrappers Black Bears @ Scrappers

Follow on MiLB First Pitch  https //stza.co/+xMzp-H

Shop  https //stza.co/+xMzp-3B

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Black Bears @ Scrappers
END:VALARM
DTSTART;VALUE=DATE:20180616
DTEND;VALUE=DATE:20180616
UID:7PnUZXGGP3hLrp_7C0EGkJ8N@stanza.co
SUMMARY:Black Bears @ Scrappers
DESCRIPTION:Black Bears @ Scrappers\n\nFollow on MiLB First Pitch: https://stza.co/+xMzp-H\n\nShop: https://stza.co/+xMzp-3B\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144605Z
LAST-MODIFIED:20180213T144605Z
TRANSP:OPAQUE
END:VEVENT
* Black Bears @ Scrappers
<2018-06-17 Sun>--<2018-06-16 Sat>
:PROPERTIES:
:ID:       rTtiq-zlW5AADl3xPXACrxyI@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Black Bears @ Scrappers Black Bears @ Scrappers

Follow on MiLB First Pitch  https //stza.co/+xMzq-3k

Shop  https //stza.co/+xMzq-6

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Black Bears @ Scrappers
END:VALARM
DTSTART;VALUE=DATE:20180617
DTEND;VALUE=DATE:20180617
UID:rTtiq-zlW5AADl3xPXACrxyI@stanza.co
SUMMARY:Black Bears @ Scrappers
DESCRIPTION:Black Bears @ Scrappers\n\nFollow on MiLB First Pitch: https://stza.co/+xMzq-3k\n\nShop: https://stza.co/+xMzq-6\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144605Z
LAST-MODIFIED:20180213T144605Z
TRANSP:OPAQUE
END:VEVENT
* Black Bears @ Muckdogs
<2018-06-18 Mon>--<2018-06-17 Sun>
:PROPERTIES:
:ID:       4PR7fBGfwrdOWkdIjEajgP67@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Black Bears @ Muckdogs Black Bears @ Muckdogs

Follow on MiLB First Pitch  https //stza.co/+xMzd-1L

Shop  https //stza.co/+xMzd-3V

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Black Bears @ Muckdogs
END:VALARM
DTSTART;VALUE=DATE:20180618
DTEND;VALUE=DATE:20180618
UID:4PR7fBGfwrdOWkdIjEajgP67@stanza.co
SUMMARY:Black Bears @ Muckdogs
DESCRIPTION:Black Bears @ Muckdogs\n\nFollow on MiLB First Pitch: https://stza.co/+xMzd-1L\n\nShop: https://stza.co/+xMzd-3V\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144605Z
LAST-MODIFIED:20180213T144605Z
TRANSP:OPAQUE
END:VEVENT
* Black Bears @ Muckdogs
<2018-06-19 Tue>--<2018-06-18 Mon>
:PROPERTIES:
:ID:       I6Zz4Z-4M7wMvJQ5amwWEUl4@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Black Bears @ Muckdogs Black Bears @ Muckdogs

Follow on MiLB First Pitch  https //stza.co/+xMze-3K

Shop  https //stza.co/+xMze-1W

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Black Bears @ Muckdogs
END:VALARM
DTSTART;VALUE=DATE:20180619
DTEND;VALUE=DATE:20180619
UID:I6Zz4Z-4M7wMvJQ5amwWEUl4@stanza.co
SUMMARY:Black Bears @ Muckdogs
DESCRIPTION:Black Bears @ Muckdogs\n\nFollow on MiLB First Pitch: https://stza.co/+xMze-3K\n\nShop: https://stza.co/+xMze-1W\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144605Z
LAST-MODIFIED:20180213T144605Z
TRANSP:OPAQUE
END:VEVENT
* Black Bears @ Muckdogs
<2018-06-20 Wed>--<2018-06-19 Tue>
:PROPERTIES:
:ID:       u-oqZ1kwPZkPMARDlaJNg8Ph@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Black Bears @ Muckdogs Black Bears @ Muckdogs

Follow on MiLB First Pitch  https //stza.co/+xMzf-R

Shop  https //stza.co/+xMzf-2F

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Black Bears @ Muckdogs
END:VALARM
DTSTART;VALUE=DATE:20180620
DTEND;VALUE=DATE:20180620
UID:u-oqZ1kwPZkPMARDlaJNg8Ph@stanza.co
SUMMARY:Black Bears @ Muckdogs
DESCRIPTION:Black Bears @ Muckdogs\n\nFollow on MiLB First Pitch: https://stza.co/+xMzf-R\n\nShop: https://stza.co/+xMzf-2F\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144605Z
LAST-MODIFIED:20180213T144605Z
TRANSP:OPAQUE
END:VEVENT
* Black Bears vs. Spikes
<2018-06-21 Thu 18:05-21:05>
:PROPERTIES:
:ID:       lC_RXxyA8-VQu2XLoexrR3ft@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Black Bears vs. Spikes Black Bears vs. Spikes

Follow on MiLB First Pitch  https //stza.co/+xW0J-A

Shop  https //stza.co/+xW0J-c

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Black Bears vs. Spikes
END:VALARM
DTSTART:20180621T230500Z
DTEND:20180622T020500Z
UID:lC_RXxyA8-VQu2XLoexrR3ft@stanza.co
SUMMARY:Black Bears vs. Spikes
DESCRIPTION:Black Bears vs. Spikes\n\nFollow on MiLB First Pitch: https://stza.co/+xW0J-A\n\nShop: https://stza.co/+xW0J-c\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144605Z
LAST-MODIFIED:20180213T144605Z
TRANSP:OPAQUE
END:VEVENT
* Black Bears vs. Spikes
<2018-06-22 Fri 18:05-21:05>
:PROPERTIES:
:ID:       tKzZvKCfRQWvIeu3jV7AEob0@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Black Bears vs. Spikes Black Bears vs. Spikes

Follow on MiLB First Pitch  https //stza.co/+xW0L-1z

Shop  https //stza.co/+xW0L-Y

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Black Bears vs. Spikes
END:VALARM
DTSTART:20180622T230500Z
DTEND:20180623T020500Z
UID:tKzZvKCfRQWvIeu3jV7AEob0@stanza.co
SUMMARY:Black Bears vs. Spikes
DESCRIPTION:Black Bears vs. Spikes\n\nFollow on MiLB First Pitch: https://stza.co/+xW0L-1z\n\nShop: https://stza.co/+xW0L-Y\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144605Z
LAST-MODIFIED:20180213T144605Z
TRANSP:OPAQUE
END:VEVENT
* Black Bears vs. Spikes
<2018-06-23 Sat 18:05-21:05>
:PROPERTIES:
:ID:       Luu3TrBfSKAiazaPhb5BVFu3@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Black Bears vs. Spikes Black Bears vs. Spikes

Follow on MiLB First Pitch  https //stza.co/+xW0N-21

Shop  https //stza.co/+xW0N-2D

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Black Bears vs. Spikes
END:VALARM
DTSTART:20180623T230500Z
DTEND:20180624T020500Z
UID:Luu3TrBfSKAiazaPhb5BVFu3@stanza.co
SUMMARY:Black Bears vs. Spikes
DESCRIPTION:Black Bears vs. Spikes\n\nFollow on MiLB First Pitch: https://stza.co/+xW0N-21\n\nShop: https://stza.co/+xW0N-2D\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144605Z
LAST-MODIFIED:20180213T144605Z
TRANSP:OPAQUE
END:VEVENT
* Black Bears @ Doubledays
<2018-06-24 Sun 13:00-16:00>
:PROPERTIES:
:ID:       2Bk_beQknVNGfOv2UbFnjIU6@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Black Bears @ Doubledays Black Bears @ Doubledays

Follow on MiLB First Pitch  https //stza.co/+xW0A-3z

Shop  https //stza.co/+xW0A-m

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Black Bears @ Doubledays
END:VALARM
DTSTART:20180624T180000Z
DTEND:20180624T210000Z
UID:2Bk_beQknVNGfOv2UbFnjIU6@stanza.co
SUMMARY:Black Bears @ Doubledays
DESCRIPTION:Black Bears @ Doubledays\n\nFollow on MiLB First Pitch: https://stza.co/+xW0A-3z\n\nShop: https://stza.co/+xW0A-m\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144605Z
LAST-MODIFIED:20180213T144605Z
TRANSP:OPAQUE
END:VEVENT
* Black Bears @ Doubledays
<2018-06-25 Mon 17:30-20:30>
:PROPERTIES:
:ID:       o2ImepvckNelWy1TminsfwVX@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Black Bears @ Doubledays Black Bears @ Doubledays

Follow on MiLB First Pitch  https //stza.co/+xW0B-1A

Shop  https //stza.co/+xW0B-18

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Black Bears @ Doubledays
END:VALARM
DTSTART:20180625T223000Z
DTEND:20180626T013000Z
UID:o2ImepvckNelWy1TminsfwVX@stanza.co
SUMMARY:Black Bears @ Doubledays
DESCRIPTION:Black Bears @ Doubledays\n\nFollow on MiLB First Pitch: https://stza.co/+xW0B-1A\n\nShop: https://stza.co/+xW0B-18\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144605Z
LAST-MODIFIED:20180213T144605Z
TRANSP:OPAQUE
END:VEVENT
* Black Bears @ Doubledays
<2018-06-26 Tue 17:30-20:30>
:PROPERTIES:
:ID:       Cjy8vKZTe0I_cG59ybs_Ql5N@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Black Bears @ Doubledays Black Bears @ Doubledays

Follow on MiLB First Pitch  https //stza.co/+xW0C-19

Shop  https //stza.co/+xW0C-3Y

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Black Bears @ Doubledays
END:VALARM
DTSTART:20180626T223000Z
DTEND:20180627T013000Z
UID:Cjy8vKZTe0I_cG59ybs_Ql5N@stanza.co
SUMMARY:Black Bears @ Doubledays
DESCRIPTION:Black Bears @ Doubledays\n\nFollow on MiLB First Pitch: https://stza.co/+xW0C-19\n\nShop: https://stza.co/+xW0C-3Y\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144605Z
LAST-MODIFIED:20180213T144605Z
TRANSP:OPAQUE
END:VEVENT
* Black Bears vs. Scrappers
<2018-06-28 Thu 18:05-21:05>
:PROPERTIES:
:ID:       EhdjMJkjRqNozthfYTks6X7N@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Black Bears vs. Scrappers Black Bears vs. Scrappers

Follow on MiLB First Pitch  https //stza.co/+xW0P-1P

Shop  https //stza.co/+xW0P-3v

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Black Bears vs. Scrappers
END:VALARM
DTSTART:20180628T230500Z
DTEND:20180629T020500Z
UID:EhdjMJkjRqNozthfYTks6X7N@stanza.co
SUMMARY:Black Bears vs. Scrappers
DESCRIPTION:Black Bears vs. Scrappers\n\nFollow on MiLB First Pitch: https://stza.co/+xW0P-1P\n\nShop: https://stza.co/+xW0P-3v\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144605Z
LAST-MODIFIED:20180213T144605Z
TRANSP:OPAQUE
END:VEVENT
* Black Bears vs. Scrappers
<2018-06-29 Fri 18:05-21:05>
:PROPERTIES:
:ID:       nI7U0wlLSWEGEFAlPrKMqPa5@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Black Bears vs. Scrappers Black Bears vs. Scrappers

Follow on MiLB First Pitch  https //stza.co/+xW0R-8

Shop  https //stza.co/+xW0R-2K

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Black Bears vs. Scrappers
END:VALARM
DTSTART:20180629T230500Z
DTEND:20180630T020500Z
UID:nI7U0wlLSWEGEFAlPrKMqPa5@stanza.co
SUMMARY:Black Bears vs. Scrappers
DESCRIPTION:Black Bears vs. Scrappers\n\nFollow on MiLB First Pitch: https://stza.co/+xW0R-8\n\nShop: https://stza.co/+xW0R-2K\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144605Z
LAST-MODIFIED:20180213T144605Z
TRANSP:OPAQUE
END:VEVENT
* Black Bears vs. Scrappers
<2018-06-30 Sat 18:05-21:05>
:PROPERTIES:
:ID:       PojDxR4XKUZrCHua3ksBWzdo@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Black Bears vs. Scrappers Black Bears vs. Scrappers

Follow on MiLB First Pitch  https //stza.co/+xW0U-1P

Shop  https //stza.co/+xW0U-h

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Black Bears vs. Scrappers
END:VALARM
DTSTART:20180630T230500Z
DTEND:20180701T020500Z
UID:PojDxR4XKUZrCHua3ksBWzdo@stanza.co
SUMMARY:Black Bears vs. Scrappers
DESCRIPTION:Black Bears vs. Scrappers\n\nFollow on MiLB First Pitch: https://stza.co/+xW0U-1P\n\nShop: https://stza.co/+xW0U-h\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144605Z
LAST-MODIFIED:20180213T144605Z
TRANSP:OPAQUE
END:VEVENT
* Black Bears @ Muckdogs
<2018-07-01 Sun>--<2018-06-30 Sat>
:PROPERTIES:
:ID:       SGtR4rAWGDFmGfVvALdrJFYf@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Black Bears @ Muckdogs Black Bears @ Muckdogs

Follow on MiLB First Pitch  https //stza.co/+xMzg-2m

Shop  https //stza.co/+xMzg-3B

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Black Bears @ Muckdogs
END:VALARM
DTSTART;VALUE=DATE:20180701
DTEND;VALUE=DATE:20180701
UID:SGtR4rAWGDFmGfVvALdrJFYf@stanza.co
SUMMARY:Black Bears @ Muckdogs
DESCRIPTION:Black Bears @ Muckdogs\n\nFollow on MiLB First Pitch: https://stza.co/+xMzg-2m\n\nShop: https://stza.co/+xMzg-3B\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144605Z
LAST-MODIFIED:20180213T144605Z
TRANSP:OPAQUE
END:VEVENT
* Black Bears @ Muckdogs
<2018-07-02 Mon>--<2018-07-01 Sun>
:PROPERTIES:
:ID:       CQyufcjeK5nHvgV_fDptYVu7@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Black Bears @ Muckdogs Black Bears @ Muckdogs

Follow on MiLB First Pitch  https //stza.co/+xMzh-32

Shop  https //stza.co/+xMzh-i

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Black Bears @ Muckdogs
END:VALARM
DTSTART;VALUE=DATE:20180702
DTEND;VALUE=DATE:20180702
UID:CQyufcjeK5nHvgV_fDptYVu7@stanza.co
SUMMARY:Black Bears @ Muckdogs
DESCRIPTION:Black Bears @ Muckdogs\n\nFollow on MiLB First Pitch: https://stza.co/+xMzh-32\n\nShop: https://stza.co/+xMzh-i\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144605Z
LAST-MODIFIED:20180213T144605Z
TRANSP:OPAQUE
END:VEVENT
* Black Bears @ Muckdogs
<2018-07-03 Tue>--<2018-07-02 Mon>
:PROPERTIES:
:ID:       KcW04qDQSC0qs8DgZhXoHuee@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Black Bears @ Muckdogs Black Bears @ Muckdogs

Follow on MiLB First Pitch  https //stza.co/+xMzi-r

Shop  https //stza.co/+xMzi-1x

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Black Bears @ Muckdogs
END:VALARM
DTSTART;VALUE=DATE:20180703
DTEND;VALUE=DATE:20180703
UID:KcW04qDQSC0qs8DgZhXoHuee@stanza.co
SUMMARY:Black Bears @ Muckdogs
DESCRIPTION:Black Bears @ Muckdogs\n\nFollow on MiLB First Pitch: https://stza.co/+xMzi-r\n\nShop: https://stza.co/+xMzi-1x\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144605Z
LAST-MODIFIED:20180213T144605Z
TRANSP:OPAQUE
END:VEVENT
* Black Bears vs. Crosscutters
<2018-07-04 Wed 18:05-21:05>
:PROPERTIES:
:ID:       7-dTZCBAxVmHHnibyRw_B-dW@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Black Bears vs. Crosscutters Black Bears vs. Crosscutters

Follow on MiLB First Pitch  https //stza.co/+xW0W-3d

Shop  https //stza.co/+xW0W-3i

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Black Bears vs. Crosscutters
END:VALARM
DTSTART:20180704T230500Z
DTEND:20180705T020500Z
UID:7-dTZCBAxVmHHnibyRw_B-dW@stanza.co
SUMMARY:Black Bears vs. Crosscutters
DESCRIPTION:Black Bears vs. Crosscutters\n\nFollow on MiLB First Pitch: https://stza.co/+xW0W-3d\n\nShop: https://stza.co/+xW0W-3i\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144605Z
LAST-MODIFIED:20180213T144605Z
TRANSP:OPAQUE
END:VEVENT
* Black Bears vs. Crosscutters
<2018-07-05 Thu 18:05-21:05>
:PROPERTIES:
:ID:       BKeZHFezVocqyvYG9c6DWrHQ@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Black Bears vs. Crosscutters Black Bears vs. Crosscutters

Follow on MiLB First Pitch  https //stza.co/+xW0X-11

Shop  https //stza.co/+xW0X-23

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Black Bears vs. Crosscutters
END:VALARM
DTSTART:20180705T230500Z
DTEND:20180706T020500Z
UID:BKeZHFezVocqyvYG9c6DWrHQ@stanza.co
SUMMARY:Black Bears vs. Crosscutters
DESCRIPTION:Black Bears vs. Crosscutters\n\nFollow on MiLB First Pitch: https://stza.co/+xW0X-11\n\nShop: https://stza.co/+xW0X-23\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144605Z
LAST-MODIFIED:20180213T144605Z
TRANSP:OPAQUE
END:VEVENT
* Black Bears vs. Crosscutters
<2018-07-06 Fri 18:05-21:05>
:PROPERTIES:
:ID:       TdKcl5IrZOdpMxPkKmaRKK9e@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Black Bears vs. Crosscutters Black Bears vs. Crosscutters

Follow on MiLB First Pitch  https //stza.co/+xW0_-1r

Shop  https //stza.co/+xW0_-3i

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Black Bears vs. Crosscutters
END:VALARM
DTSTART:20180706T230500Z
DTEND:20180707T020500Z
UID:TdKcl5IrZOdpMxPkKmaRKK9e@stanza.co
SUMMARY:Black Bears vs. Crosscutters
DESCRIPTION:Black Bears vs. Crosscutters\n\nFollow on MiLB First Pitch: https://stza.co/+xW0_-1r\n\nShop: https://stza.co/+xW0_-3i\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144605Z
LAST-MODIFIED:20180213T144605Z
TRANSP:OPAQUE
END:VEVENT
* Black Bears vs. Doubledays
<2018-07-07 Sat 18:05-21:05>
:PROPERTIES:
:ID:       2HEZDoNZvfPhEuFKOsJzmcFn@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Black Bears vs. Doubledays Black Bears vs. Doubledays

Follow on MiLB First Pitch  https //stza.co/+xW0$-1b

Shop  https //stza.co/+xW0$-8

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Black Bears vs. Doubledays
END:VALARM
DTSTART:20180707T230500Z
DTEND:20180708T020500Z
UID:2HEZDoNZvfPhEuFKOsJzmcFn@stanza.co
SUMMARY:Black Bears vs. Doubledays
DESCRIPTION:Black Bears vs. Doubledays\n\nFollow on MiLB First Pitch: https://stza.co/+xW0$-1b\n\nShop: https://stza.co/+xW0$-8\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144605Z
LAST-MODIFIED:20180213T144605Z
TRANSP:OPAQUE
END:VEVENT
* Black Bears vs. Doubledays
<2018-07-08 Sun 15:05-18:05>
:PROPERTIES:
:ID:       i-xbuqJgqeAlsQqHLvATg65V@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Black Bears vs. Doubledays Black Bears vs. Doubledays

Follow on MiLB First Pitch  https //stza.co/+xW11-U

Shop  https //stza.co/+xW11-1Z

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Black Bears vs. Doubledays
END:VALARM
DTSTART:20180708T200500Z
DTEND:20180708T230500Z
UID:i-xbuqJgqeAlsQqHLvATg65V@stanza.co
SUMMARY:Black Bears vs. Doubledays
DESCRIPTION:Black Bears vs. Doubledays\n\nFollow on MiLB First Pitch: https://stza.co/+xW11-U\n\nShop: https://stza.co/+xW11-1Z\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144605Z
LAST-MODIFIED:20180213T144605Z
TRANSP:OPAQUE
END:VEVENT
* Black Bears vs. Doubledays
<2018-07-09 Mon 18:05-21:05>
:PROPERTIES:
:ID:       ZCJPAsQXgXsWzJmQod337yAZ@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Black Bears vs. Doubledays Black Bears vs. Doubledays

Follow on MiLB First Pitch  https //stza.co/+xW14-19

Shop  https //stza.co/+xW14-2Q

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Black Bears vs. Doubledays
END:VALARM
DTSTART:20180709T230500Z
DTEND:20180710T020500Z
UID:ZCJPAsQXgXsWzJmQod337yAZ@stanza.co
SUMMARY:Black Bears vs. Doubledays
DESCRIPTION:Black Bears vs. Doubledays\n\nFollow on MiLB First Pitch: https://stza.co/+xW14-19\n\nShop: https://stza.co/+xW14-2Q\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144605Z
LAST-MODIFIED:20180213T144605Z
TRANSP:OPAQUE
END:VEVENT
* Black Bears @ Renegades
<2018-07-11 Wed 18:05-21:05>
:PROPERTIES:
:ID:       tb79Luwm_Ai41zdTMGkF6Chf@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Black Bears @ Renegades Black Bears @ Renegades

Follow on MiLB First Pitch  https //stza.co/+xW0G-11

Shop  https //stza.co/+xW0G-2c

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Black Bears @ Renegades
END:VALARM
DTSTART:20180711T230500Z
DTEND:20180712T020500Z
UID:tb79Luwm_Ai41zdTMGkF6Chf@stanza.co
SUMMARY:Black Bears @ Renegades
DESCRIPTION:Black Bears @ Renegades\n\nFollow on MiLB First Pitch: https://stza.co/+xW0G-11\n\nShop: https://stza.co/+xW0G-2c\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144605Z
LAST-MODIFIED:20180213T144605Z
TRANSP:OPAQUE
END:VEVENT
* Black Bears @ Renegades
<2018-07-12 Thu 18:05-21:05>
:PROPERTIES:
:ID:       YelF0upT5dRviF3_nxvW2AFX@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Black Bears @ Renegades Black Bears @ Renegades

Follow on MiLB First Pitch  https //stza.co/+xW0H-s

Shop  https //stza.co/+xW0H-3a

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Black Bears @ Renegades
END:VALARM
DTSTART:20180712T230500Z
DTEND:20180713T020500Z
UID:YelF0upT5dRviF3_nxvW2AFX@stanza.co
SUMMARY:Black Bears @ Renegades
DESCRIPTION:Black Bears @ Renegades\n\nFollow on MiLB First Pitch: https://stza.co/+xW0H-s\n\nShop: https://stza.co/+xW0H-3a\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144605Z
LAST-MODIFIED:20180213T144605Z
TRANSP:OPAQUE
END:VEVENT
* Black Bears @ Renegades
<2018-07-13 Fri 18:05-21:05>
:PROPERTIES:
:ID:       S1BDmAeZUiwg_iTfKw-E7Oz4@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Black Bears @ Renegades Black Bears @ Renegades

Follow on MiLB First Pitch  https //stza.co/+xW0I-11

Shop  https //stza.co/+xW0I-3G

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Black Bears @ Renegades
END:VALARM
DTSTART:20180713T230500Z
DTEND:20180714T020500Z
UID:S1BDmAeZUiwg_iTfKw-E7Oz4@stanza.co
SUMMARY:Black Bears @ Renegades
DESCRIPTION:Black Bears @ Renegades\n\nFollow on MiLB First Pitch: https://stza.co/+xW0I-11\n\nShop: https://stza.co/+xW0I-3G\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144605Z
LAST-MODIFIED:20180213T144605Z
TRANSP:OPAQUE
END:VEVENT
* Black Bears @ Yankees
<2018-07-14 Sat>--<2018-07-13 Fri>
:PROPERTIES:
:ID:       nl1YpwVq-zoLI3hmyzjlwILm@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Black Bears @ Yankees Black Bears @ Yankees

Follow on MiLB First Pitch  https //stza.co/+xMzA-4

Shop  https //stza.co/+xMzA-2B

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Black Bears @ Yankees
END:VALARM
DTSTART;VALUE=DATE:20180714
DTEND;VALUE=DATE:20180714
UID:nl1YpwVq-zoLI3hmyzjlwILm@stanza.co
SUMMARY:Black Bears @ Yankees
DESCRIPTION:Black Bears @ Yankees\n\nFollow on MiLB First Pitch: https://stza.co/+xMzA-4\n\nShop: https://stza.co/+xMzA-2B\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144605Z
LAST-MODIFIED:20180213T144605Z
TRANSP:OPAQUE
END:VEVENT
* Black Bears @ Yankees
<2018-07-15 Sun>--<2018-07-14 Sat>
:PROPERTIES:
:ID:       rACNgz3NRn8uNzYF2GYJIBHo@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Black Bears @ Yankees Black Bears @ Yankees

Follow on MiLB First Pitch  https //stza.co/+xMzB-2B

Shop  https //stza.co/+xMzB-f

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Black Bears @ Yankees
END:VALARM
DTSTART;VALUE=DATE:20180715
DTEND;VALUE=DATE:20180715
UID:rACNgz3NRn8uNzYF2GYJIBHo@stanza.co
SUMMARY:Black Bears @ Yankees
DESCRIPTION:Black Bears @ Yankees\n\nFollow on MiLB First Pitch: https://stza.co/+xMzB-2B\n\nShop: https://stza.co/+xMzB-f\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144605Z
LAST-MODIFIED:20180213T144605Z
TRANSP:OPAQUE
END:VEVENT
* Black Bears @ Yankees
<2018-07-16 Mon>--<2018-07-15 Sun>
:PROPERTIES:
:ID:       BR_DLIHJUtB3lYN5ArfD_Rvi@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Black Bears @ Yankees Black Bears @ Yankees

Follow on MiLB First Pitch  https //stza.co/+xMzC-1z

Shop  https //stza.co/+xMzC-3p

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Black Bears @ Yankees
END:VALARM
DTSTART;VALUE=DATE:20180716
DTEND;VALUE=DATE:20180716
UID:BR_DLIHJUtB3lYN5ArfD_Rvi@stanza.co
SUMMARY:Black Bears @ Yankees
DESCRIPTION:Black Bears @ Yankees\n\nFollow on MiLB First Pitch: https://stza.co/+xMzC-1z\n\nShop: https://stza.co/+xMzC-3p\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144605Z
LAST-MODIFIED:20180213T144605Z
TRANSP:OPAQUE
END:VEVENT
* Black Bears vs. Spikes
<2018-07-17 Tue 18:05-21:05>
:PROPERTIES:
:ID:       ytxCMFLMu2j6XHLeJvECyXcQ@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Black Bears vs. Spikes Black Bears vs. Spikes

Follow on MiLB First Pitch  https //stza.co/+xW16-18

Shop  https //stza.co/+xW16-3I

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Black Bears vs. Spikes
END:VALARM
DTSTART:20180717T230500Z
DTEND:20180718T020500Z
UID:ytxCMFLMu2j6XHLeJvECyXcQ@stanza.co
SUMMARY:Black Bears vs. Spikes
DESCRIPTION:Black Bears vs. Spikes\n\nFollow on MiLB First Pitch: https://stza.co/+xW16-18\n\nShop: https://stza.co/+xW16-3I\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144605Z
LAST-MODIFIED:20180213T144605Z
TRANSP:OPAQUE
END:VEVENT
* Black Bears vs. Spikes
<2018-07-18 Wed 18:05-21:05>
:PROPERTIES:
:ID:       mLnpoX8EsgARb52iJ3L_u-vZ@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Black Bears vs. Spikes Black Bears vs. Spikes

Follow on MiLB First Pitch  https //stza.co/+xW18-G

Shop  https //stza.co/+xW18-2R

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Black Bears vs. Spikes
END:VALARM
DTSTART:20180718T230500Z
DTEND:20180719T020500Z
UID:mLnpoX8EsgARb52iJ3L_u-vZ@stanza.co
SUMMARY:Black Bears vs. Spikes
DESCRIPTION:Black Bears vs. Spikes\n\nFollow on MiLB First Pitch: https://stza.co/+xW18-G\n\nShop: https://stza.co/+xW18-2R\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144605Z
LAST-MODIFIED:20180213T144605Z
TRANSP:OPAQUE
END:VEVENT
* Black Bears vs. Spikes
<2018-07-19 Thu 18:05-21:05>
:PROPERTIES:
:ID:       HyTc0iTv5Ao_BthfqG1QwCth@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Black Bears vs. Spikes Black Bears vs. Spikes

Follow on MiLB First Pitch  https //stza.co/+xW1a-3c

Shop  https //stza.co/+xW1a-2v

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Black Bears vs. Spikes
END:VALARM
DTSTART:20180719T230500Z
DTEND:20180720T020500Z
UID:HyTc0iTv5Ao_BthfqG1QwCth@stanza.co
SUMMARY:Black Bears vs. Spikes
DESCRIPTION:Black Bears vs. Spikes\n\nFollow on MiLB First Pitch: https://stza.co/+xW1a-3c\n\nShop: https://stza.co/+xW1a-2v\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144605Z
LAST-MODIFIED:20180213T144605Z
TRANSP:OPAQUE
END:VEVENT
* Black Bears @ Crosscutters
<2018-07-20 Fri 18:05-21:05>
:PROPERTIES:
:ID:       Wpr7YE4GObUrmtgyh-KVB9Hg@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Black Bears @ Crosscutters Black Bears @ Crosscutters

Follow on MiLB First Pitch  https //stza.co/+x$6t-1L

Shop  https //stza.co/+x$6t-14

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Black Bears @ Crosscutters
END:VALARM
DTSTART:20180720T230500Z
DTEND:20180721T020500Z
UID:Wpr7YE4GObUrmtgyh-KVB9Hg@stanza.co
SUMMARY:Black Bears @ Crosscutters
DESCRIPTION:Black Bears @ Crosscutters\n\nFollow on MiLB First Pitch: https://stza.co/+x$6t-1L\n\nShop: https://stza.co/+x$6t-14\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144605Z
LAST-MODIFIED:20180213T144605Z
TRANSP:OPAQUE
END:VEVENT
* Black Bears @ Crosscutters
<2018-07-21 Sat 18:05-21:05>
:PROPERTIES:
:ID:       e77LZj1eCn6l1Hy-QOjbt4kG@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Black Bears @ Crosscutters Black Bears @ Crosscutters

Follow on MiLB First Pitch  https //stza.co/+x$6u-2X

Shop  https //stza.co/+x$6u-2D

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Black Bears @ Crosscutters
END:VALARM
DTSTART:20180721T230500Z
DTEND:20180722T020500Z
UID:e77LZj1eCn6l1Hy-QOjbt4kG@stanza.co
SUMMARY:Black Bears @ Crosscutters
DESCRIPTION:Black Bears @ Crosscutters\n\nFollow on MiLB First Pitch: https://stza.co/+x$6u-2X\n\nShop: https://stza.co/+x$6u-2D\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144605Z
LAST-MODIFIED:20180213T144605Z
TRANSP:OPAQUE
END:VEVENT
* Black Bears @ Crosscutters
<2018-07-22 Sun 16:05-19:05>
:PROPERTIES:
:ID:       3OE_LCJtmYrXGD9ibivKaNfW@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Black Bears @ Crosscutters Black Bears @ Crosscutters

Follow on MiLB First Pitch  https //stza.co/+x$6v-1m

Shop  https //stza.co/+x$6v-u

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Black Bears @ Crosscutters
END:VALARM
DTSTART:20180722T210500Z
DTEND:20180723T000500Z
UID:3OE_LCJtmYrXGD9ibivKaNfW@stanza.co
SUMMARY:Black Bears @ Crosscutters
DESCRIPTION:Black Bears @ Crosscutters\n\nFollow on MiLB First Pitch: https://stza.co/+x$6v-1m\n\nShop: https://stza.co/+x$6v-u\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144605Z
LAST-MODIFIED:20180213T144605Z
TRANSP:OPAQUE
END:VEVENT
* Black Bears vs. IronBirds
<2018-07-24 Tue 18:05-21:05>
:PROPERTIES:
:ID:       sTIsheyY_wAiKiiVCouhfaFP@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Black Bears vs. IronBirds Black Bears vs. IronBirds

Follow on MiLB First Pitch  https //stza.co/+xW1c-18

Shop  https //stza.co/+xW1c-3n

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Black Bears vs. IronBirds
END:VALARM
DTSTART:20180724T230500Z
DTEND:20180725T020500Z
UID:sTIsheyY_wAiKiiVCouhfaFP@stanza.co
SUMMARY:Black Bears vs. IronBirds
DESCRIPTION:Black Bears vs. IronBirds\n\nFollow on MiLB First Pitch: https://stza.co/+xW1c-18\n\nShop: https://stza.co/+xW1c-3n\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144605Z
LAST-MODIFIED:20180213T144605Z
TRANSP:OPAQUE
END:VEVENT
* Black Bears vs. IronBirds
<2018-07-25 Wed 18:05-21:05>
:PROPERTIES:
:ID:       rVKtsWt04GL6xrXlyIhA2dwb@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Black Bears vs. IronBirds Black Bears vs. IronBirds

Follow on MiLB First Pitch  https //stza.co/+xW1d-2F

Shop  https //stza.co/+xW1d-2P

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Black Bears vs. IronBirds
END:VALARM
DTSTART:20180725T230500Z
DTEND:20180726T020500Z
UID:rVKtsWt04GL6xrXlyIhA2dwb@stanza.co
SUMMARY:Black Bears vs. IronBirds
DESCRIPTION:Black Bears vs. IronBirds\n\nFollow on MiLB First Pitch: https://stza.co/+xW1d-2F\n\nShop: https://stza.co/+xW1d-2P\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144605Z
LAST-MODIFIED:20180213T144605Z
TRANSP:OPAQUE
END:VEVENT
* Black Bears vs. IronBirds
<2018-07-26 Thu 18:05-21:05>
:PROPERTIES:
:ID:       Y5ASlE2Txut--k1TWRon2rYh@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Black Bears vs. IronBirds Black Bears vs. IronBirds

Follow on MiLB First Pitch  https //stza.co/+xW1g-2P

Shop  https //stza.co/+xW1g-3Q

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Black Bears vs. IronBirds
END:VALARM
DTSTART:20180726T230500Z
DTEND:20180727T020500Z
UID:Y5ASlE2Txut--k1TWRon2rYh@stanza.co
SUMMARY:Black Bears vs. IronBirds
DESCRIPTION:Black Bears vs. IronBirds\n\nFollow on MiLB First Pitch: https://stza.co/+xW1g-2P\n\nShop: https://stza.co/+xW1g-3Q\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144605Z
LAST-MODIFIED:20180213T144605Z
TRANSP:OPAQUE
END:VEVENT
* Black Bears vs. Cyclones
<2018-07-27 Fri 18:05-21:05>
:PROPERTIES:
:ID:       cRlsXXvdPUcdpMn_cRMM2n8F@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Black Bears vs. Cyclones Black Bears vs. Cyclones

Follow on MiLB First Pitch  https //stza.co/+xW1h-1L

Shop  https //stza.co/+xW1h-2O

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Black Bears vs. Cyclones
END:VALARM
DTSTART:20180727T230500Z
DTEND:20180728T020500Z
UID:cRlsXXvdPUcdpMn_cRMM2n8F@stanza.co
SUMMARY:Black Bears vs. Cyclones
DESCRIPTION:Black Bears vs. Cyclones\n\nFollow on MiLB First Pitch: https://stza.co/+xW1h-1L\n\nShop: https://stza.co/+xW1h-2O\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144605Z
LAST-MODIFIED:20180213T144605Z
TRANSP:OPAQUE
END:VEVENT
* Black Bears vs. Cyclones
<2018-07-28 Sat 18:05-21:05>
:PROPERTIES:
:ID:       JalmbrianXzlGvWv1vsASbX_@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Black Bears vs. Cyclones Black Bears vs. Cyclones

Follow on MiLB First Pitch  https //stza.co/+xW1j-S

Shop  https //stza.co/+xW1j-2V

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Black Bears vs. Cyclones
END:VALARM
DTSTART:20180728T230500Z
DTEND:20180729T020500Z
UID:JalmbrianXzlGvWv1vsASbX_@stanza.co
SUMMARY:Black Bears vs. Cyclones
DESCRIPTION:Black Bears vs. Cyclones\n\nFollow on MiLB First Pitch: https://stza.co/+xW1j-S\n\nShop: https://stza.co/+xW1j-2V\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144605Z
LAST-MODIFIED:20180213T144605Z
TRANSP:OPAQUE
END:VEVENT
* Black Bears vs. Cyclones
<2018-07-29 Sun 15:05-18:05>
:PROPERTIES:
:ID:       L8U9HOOUu_jH4tKs6WsjetaG@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Black Bears vs. Cyclones Black Bears vs. Cyclones

Follow on MiLB First Pitch  https //stza.co/+xW1m-1Y

Shop  https //stza.co/+xW1m-2Q

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Black Bears vs. Cyclones
END:VALARM
DTSTART:20180729T200500Z
DTEND:20180729T230500Z
UID:L8U9HOOUu_jH4tKs6WsjetaG@stanza.co
SUMMARY:Black Bears vs. Cyclones
DESCRIPTION:Black Bears vs. Cyclones\n\nFollow on MiLB First Pitch: https://stza.co/+xW1m-1Y\n\nShop: https://stza.co/+xW1m-2Q\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144605Z
LAST-MODIFIED:20180213T144605Z
TRANSP:OPAQUE
END:VEVENT
* Black Bears @ Doubledays
<2018-07-30 Mon 17:30-20:30>
:PROPERTIES:
:ID:       K5n-D-waOWzyryviKvasS6Rc@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Black Bears @ Doubledays Black Bears @ Doubledays

Follow on MiLB First Pitch  https //stza.co/+xW0D-1A

Shop  https //stza.co/+xW0D-2s

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Black Bears @ Doubledays
END:VALARM
DTSTART:20180730T223000Z
DTEND:20180731T013000Z
UID:K5n-D-waOWzyryviKvasS6Rc@stanza.co
SUMMARY:Black Bears @ Doubledays
DESCRIPTION:Black Bears @ Doubledays\n\nFollow on MiLB First Pitch: https://stza.co/+xW0D-1A\n\nShop: https://stza.co/+xW0D-2s\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144605Z
LAST-MODIFIED:20180213T144605Z
TRANSP:OPAQUE
END:VEVENT
* Black Bears @ Doubledays
<2018-07-31 Tue 17:30-20:30>
:PROPERTIES:
:ID:       Uv8v2Y_ZFB8X51DGPVw7GNMg@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Black Bears @ Doubledays Black Bears @ Doubledays

Follow on MiLB First Pitch  https //stza.co/+xW0E-27

Shop  https //stza.co/+xW0E-H

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Black Bears @ Doubledays
END:VALARM
DTSTART:20180731T223000Z
DTEND:20180801T013000Z
UID:Uv8v2Y_ZFB8X51DGPVw7GNMg@stanza.co
SUMMARY:Black Bears @ Doubledays
DESCRIPTION:Black Bears @ Doubledays\n\nFollow on MiLB First Pitch: https://stza.co/+xW0E-27\n\nShop: https://stza.co/+xW0E-H\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144605Z
LAST-MODIFIED:20180213T144605Z
TRANSP:OPAQUE
END:VEVENT
* Black Bears @ Doubledays
<2018-08-01 Wed 17:30-20:30>
:PROPERTIES:
:ID:       JFdF8AFCp07gYvnhar9SxKol@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Black Bears @ Doubledays Black Bears @ Doubledays

Follow on MiLB First Pitch  https //stza.co/+xW0F-1M

Shop  https //stza.co/+xW0F-2O

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Black Bears @ Doubledays
END:VALARM
DTSTART:20180801T223000Z
DTEND:20180802T013000Z
UID:JFdF8AFCp07gYvnhar9SxKol@stanza.co
SUMMARY:Black Bears @ Doubledays
DESCRIPTION:Black Bears @ Doubledays\n\nFollow on MiLB First Pitch: https://stza.co/+xW0F-1M\n\nShop: https://stza.co/+xW0F-2O\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144605Z
LAST-MODIFIED:20180213T144605Z
TRANSP:OPAQUE
END:VEVENT
* Black Bears @ Crosscutters
<2018-08-02 Thu 18:05-21:05>
:PROPERTIES:
:ID:       irbX-Pw-BwRom2iCC5H3Re38@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Black Bears @ Crosscutters Black Bears @ Crosscutters

Follow on MiLB First Pitch  https //stza.co/+x$6w-30

Shop  https //stza.co/+x$6w-3H

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Black Bears @ Crosscutters
END:VALARM
DTSTART:20180802T230500Z
DTEND:20180803T020500Z
UID:irbX-Pw-BwRom2iCC5H3Re38@stanza.co
SUMMARY:Black Bears @ Crosscutters
DESCRIPTION:Black Bears @ Crosscutters\n\nFollow on MiLB First Pitch: https://stza.co/+x$6w-30\n\nShop: https://stza.co/+x$6w-3H\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144605Z
LAST-MODIFIED:20180213T144605Z
TRANSP:OPAQUE
END:VEVENT
* Black Bears @ Crosscutters
<2018-08-03 Fri 18:05-21:05>
:PROPERTIES:
:ID:       ZM4e4FbGsbp480mCFqsLq6po@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Black Bears @ Crosscutters Black Bears @ Crosscutters

Follow on MiLB First Pitch  https //stza.co/+x$6x-S

Shop  https //stza.co/+x$6x-3k

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Black Bears @ Crosscutters
END:VALARM
DTSTART:20180803T230500Z
DTEND:20180804T020500Z
UID:ZM4e4FbGsbp480mCFqsLq6po@stanza.co
SUMMARY:Black Bears @ Crosscutters
DESCRIPTION:Black Bears @ Crosscutters\n\nFollow on MiLB First Pitch: https://stza.co/+x$6x-S\n\nShop: https://stza.co/+x$6x-3k\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144605Z
LAST-MODIFIED:20180213T144605Z
TRANSP:OPAQUE
END:VEVENT
* Black Bears @ Crosscutters
<2018-08-04 Sat 18:05-21:05>
:PROPERTIES:
:ID:       mYR_86heEQM-6PtfZzVcalfR@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Black Bears @ Crosscutters Black Bears @ Crosscutters

Follow on MiLB First Pitch  https //stza.co/+x$6y-2e

Shop  https //stza.co/+x$6y-24

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Black Bears @ Crosscutters
END:VALARM
DTSTART:20180804T230500Z
DTEND:20180805T020500Z
UID:mYR_86heEQM-6PtfZzVcalfR@stanza.co
SUMMARY:Black Bears @ Crosscutters
DESCRIPTION:Black Bears @ Crosscutters\n\nFollow on MiLB First Pitch: https://stza.co/+x$6y-2e\n\nShop: https://stza.co/+x$6y-24\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144605Z
LAST-MODIFIED:20180213T144605Z
TRANSP:OPAQUE
END:VEVENT
* Black Bears vs. Muckdogs
<2018-08-05 Sun 15:05-18:05>
:PROPERTIES:
:ID:       PYoBJ5Uv-RAIW3ysyqgBgNmJ@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Black Bears vs. Muckdogs Black Bears vs. Muckdogs

Follow on MiLB First Pitch  https //stza.co/+xW1o-r

Shop  https //stza.co/+xW1o-1Q

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Black Bears vs. Muckdogs
END:VALARM
DTSTART:20180805T200500Z
DTEND:20180805T230500Z
UID:PYoBJ5Uv-RAIW3ysyqgBgNmJ@stanza.co
SUMMARY:Black Bears vs. Muckdogs
DESCRIPTION:Black Bears vs. Muckdogs\n\nFollow on MiLB First Pitch: https://stza.co/+xW1o-r\n\nShop: https://stza.co/+xW1o-1Q\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144605Z
LAST-MODIFIED:20180213T144605Z
TRANSP:OPAQUE
END:VEVENT
* Black Bears vs. Muckdogs
<2018-08-06 Mon 18:05-21:05>
:PROPERTIES:
:ID:       qgqNqQqfP7trGZ1M2m4Ur29J@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Black Bears vs. Muckdogs Black Bears vs. Muckdogs

Follow on MiLB First Pitch  https //stza.co/+xW1p-1N

Shop  https //stza.co/+xW1p-1U

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Black Bears vs. Muckdogs
END:VALARM
DTSTART:20180806T230500Z
DTEND:20180807T020500Z
UID:qgqNqQqfP7trGZ1M2m4Ur29J@stanza.co
SUMMARY:Black Bears vs. Muckdogs
DESCRIPTION:Black Bears vs. Muckdogs\n\nFollow on MiLB First Pitch: https://stza.co/+xW1p-1N\n\nShop: https://stza.co/+xW1p-1U\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144605Z
LAST-MODIFIED:20180213T144605Z
TRANSP:OPAQUE
END:VEVENT
* Black Bears vs. Muckdogs
<2018-08-07 Tue 18:05-21:05>
:PROPERTIES:
:ID:       CjL0Kl61V_EqoHHFPxRyGPOI@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Black Bears vs. Muckdogs Black Bears vs. Muckdogs

Follow on MiLB First Pitch  https //stza.co/+xW1s-3l

Shop  https //stza.co/+xW1s-21

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Black Bears vs. Muckdogs
END:VALARM
DTSTART:20180807T230500Z
DTEND:20180808T020500Z
UID:CjL0Kl61V_EqoHHFPxRyGPOI@stanza.co
SUMMARY:Black Bears vs. Muckdogs
DESCRIPTION:Black Bears vs. Muckdogs\n\nFollow on MiLB First Pitch: https://stza.co/+xW1s-3l\n\nShop: https://stza.co/+xW1s-21\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144605Z
LAST-MODIFIED:20180213T144605Z
TRANSP:OPAQUE
END:VEVENT
* Black Bears @ Spikes
<2018-08-08 Wed>--<2018-08-07 Tue>
:PROPERTIES:
:ID:       p3Melxho89T0HNQ31BrJm1la@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Black Bears @ Spikes Black Bears @ Spikes

Follow on MiLB First Pitch  https //stza.co/+xMzu-W

Shop  https //stza.co/+xMzu-3M

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Black Bears @ Spikes
END:VALARM
DTSTART;VALUE=DATE:20180808
DTEND;VALUE=DATE:20180808
UID:p3Melxho89T0HNQ31BrJm1la@stanza.co
SUMMARY:Black Bears @ Spikes
DESCRIPTION:Black Bears @ Spikes\n\nFollow on MiLB First Pitch: https://stza.co/+xMzu-W\n\nShop: https://stza.co/+xMzu-3M\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144605Z
LAST-MODIFIED:20180213T144605Z
TRANSP:OPAQUE
END:VEVENT
* Black Bears @ Spikes
<2018-08-09 Thu>--<2018-08-08 Wed>
:PROPERTIES:
:ID:       SZK0fig9q5__-DgIaXHbCqKm@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Black Bears @ Spikes Black Bears @ Spikes

Follow on MiLB First Pitch  https //stza.co/+xMzv-1a

Shop  https //stza.co/+xMzv-E

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Black Bears @ Spikes
END:VALARM
DTSTART;VALUE=DATE:20180809
DTEND;VALUE=DATE:20180809
UID:SZK0fig9q5__-DgIaXHbCqKm@stanza.co
SUMMARY:Black Bears @ Spikes
DESCRIPTION:Black Bears @ Spikes\n\nFollow on MiLB First Pitch: https://stza.co/+xMzv-1a\n\nShop: https://stza.co/+xMzv-E\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144605Z
LAST-MODIFIED:20180213T144605Z
TRANSP:OPAQUE
END:VEVENT
* Black Bears @ Spikes
<2018-08-10 Fri>--<2018-08-09 Thu>
:PROPERTIES:
:ID:       MQQqDj6FHl1VBdWfUhc6z6bY@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Black Bears @ Spikes Black Bears @ Spikes

Follow on MiLB First Pitch  https //stza.co/+xMzw-1p

Shop  https //stza.co/+xMzw-2c

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Black Bears @ Spikes
END:VALARM
DTSTART;VALUE=DATE:20180810
DTEND;VALUE=DATE:20180810
UID:MQQqDj6FHl1VBdWfUhc6z6bY@stanza.co
SUMMARY:Black Bears @ Spikes
DESCRIPTION:Black Bears @ Spikes\n\nFollow on MiLB First Pitch: https://stza.co/+xMzw-1p\n\nShop: https://stza.co/+xMzw-2c\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144605Z
LAST-MODIFIED:20180213T144605Z
TRANSP:OPAQUE
END:VEVENT
* Black Bears vs. Scrappers
<2018-08-11 Sat 18:05-21:05>
:PROPERTIES:
:ID:       qvfdBeeLUj13RQRoodYT57mx@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Black Bears vs. Scrappers Black Bears vs. Scrappers

Follow on MiLB First Pitch  https //stza.co/+xW1t-5

Shop  https //stza.co/+xW1t-1O

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Black Bears vs. Scrappers
END:VALARM
DTSTART:20180811T230500Z
DTEND:20180812T020500Z
UID:qvfdBeeLUj13RQRoodYT57mx@stanza.co
SUMMARY:Black Bears vs. Scrappers
DESCRIPTION:Black Bears vs. Scrappers\n\nFollow on MiLB First Pitch: https://stza.co/+xW1t-5\n\nShop: https://stza.co/+xW1t-1O\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144605Z
LAST-MODIFIED:20180213T144605Z
TRANSP:OPAQUE
END:VEVENT
* Black Bears vs. Scrappers
<2018-08-12 Sun 15:05-18:05>
:PROPERTIES:
:ID:       DldKAkRRJmBo0i2bHwdlBfso@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Black Bears vs. Scrappers Black Bears vs. Scrappers

Follow on MiLB First Pitch  https //stza.co/+xW1v-3v

Shop  https //stza.co/+xW1v-l

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Black Bears vs. Scrappers
END:VALARM
DTSTART:20180812T200500Z
DTEND:20180812T230500Z
UID:DldKAkRRJmBo0i2bHwdlBfso@stanza.co
SUMMARY:Black Bears vs. Scrappers
DESCRIPTION:Black Bears vs. Scrappers\n\nFollow on MiLB First Pitch: https://stza.co/+xW1v-3v\n\nShop: https://stza.co/+xW1v-l\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144605Z
LAST-MODIFIED:20180213T144605Z
TRANSP:OPAQUE
END:VEVENT
* Black Bears @ Muckdogs
<2018-08-15 Wed>--<2018-08-14 Tue>
:PROPERTIES:
:ID:       2jsrHPpFLdM-Y5KpzyHg16d8@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Black Bears @ Muckdogs Black Bears @ Muckdogs

Follow on MiLB First Pitch  https //stza.co/+xMzj-1t

Shop  https //stza.co/+xMzj-19

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Black Bears @ Muckdogs
END:VALARM
DTSTART;VALUE=DATE:20180815
DTEND;VALUE=DATE:20180815
UID:2jsrHPpFLdM-Y5KpzyHg16d8@stanza.co
SUMMARY:Black Bears @ Muckdogs
DESCRIPTION:Black Bears @ Muckdogs\n\nFollow on MiLB First Pitch: https://stza.co/+xMzj-1t\n\nShop: https://stza.co/+xMzj-19\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144605Z
LAST-MODIFIED:20180213T144605Z
TRANSP:OPAQUE
END:VEVENT
* Black Bears @ Muckdogs
<2018-08-16 Thu>--<2018-08-15 Wed>
:PROPERTIES:
:ID:       OWBzyijqKUgkYcE9pcG_-lSH@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Black Bears @ Muckdogs Black Bears @ Muckdogs

Follow on MiLB First Pitch  https //stza.co/+xMzk-1o

Shop  https //stza.co/+xMzk-6

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Black Bears @ Muckdogs
END:VALARM
DTSTART;VALUE=DATE:20180816
DTEND;VALUE=DATE:20180816
UID:OWBzyijqKUgkYcE9pcG_-lSH@stanza.co
SUMMARY:Black Bears @ Muckdogs
DESCRIPTION:Black Bears @ Muckdogs\n\nFollow on MiLB First Pitch: https://stza.co/+xMzk-1o\n\nShop: https://stza.co/+xMzk-6\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144605Z
LAST-MODIFIED:20180213T144605Z
TRANSP:OPAQUE
END:VEVENT
* Black Bears vs. Crosscutters
<2018-08-17 Fri 18:05-21:05>
:PROPERTIES:
:ID:       NT4PU-pwMq5SYpQxqsTRXDHD@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Black Bears vs. Crosscutters Black Bears vs. Crosscutters

Follow on MiLB First Pitch  https //stza.co/+xW1x-1z

Shop  https //stza.co/+xW1x-2N

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Black Bears vs. Crosscutters
END:VALARM
DTSTART:20180817T230500Z
DTEND:20180818T020500Z
UID:NT4PU-pwMq5SYpQxqsTRXDHD@stanza.co
SUMMARY:Black Bears vs. Crosscutters
DESCRIPTION:Black Bears vs. Crosscutters\n\nFollow on MiLB First Pitch: https://stza.co/+xW1x-1z\n\nShop: https://stza.co/+xW1x-2N\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144605Z
LAST-MODIFIED:20180213T144605Z
TRANSP:OPAQUE
END:VEVENT
* Black Bears vs. Crosscutters
<2018-08-18 Sat 18:05-21:05>
:PROPERTIES:
:ID:       X4tJjPMIgKcMApUz5_0zJ3_F@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Black Bears vs. Crosscutters Black Bears vs. Crosscutters

Follow on MiLB First Pitch  https //stza.co/+xW1A-3n

Shop  https //stza.co/+xW1A-n

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Black Bears vs. Crosscutters
END:VALARM
DTSTART:20180818T230500Z
DTEND:20180819T020500Z
UID:X4tJjPMIgKcMApUz5_0zJ3_F@stanza.co
SUMMARY:Black Bears vs. Crosscutters
DESCRIPTION:Black Bears vs. Crosscutters\n\nFollow on MiLB First Pitch: https://stza.co/+xW1A-3n\n\nShop: https://stza.co/+xW1A-n\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144605Z
LAST-MODIFIED:20180213T144605Z
TRANSP:OPAQUE
END:VEVENT
* Black Bears vs. Crosscutters
<2018-08-19 Sun 15:05-18:05>
:PROPERTIES:
:ID:       vGf-I-QVwGHWHVDuxVmJnA_2@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Black Bears vs. Crosscutters Black Bears vs. Crosscutters

Follow on MiLB First Pitch  https //stza.co/+xW1C-2u

Shop  https //stza.co/+xW1C-31

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Black Bears vs. Crosscutters
END:VALARM
DTSTART:20180819T200500Z
DTEND:20180819T230500Z
UID:vGf-I-QVwGHWHVDuxVmJnA_2@stanza.co
SUMMARY:Black Bears vs. Crosscutters
DESCRIPTION:Black Bears vs. Crosscutters\n\nFollow on MiLB First Pitch: https://stza.co/+xW1C-2u\n\nShop: https://stza.co/+xW1C-31\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144605Z
LAST-MODIFIED:20180213T144605Z
TRANSP:OPAQUE
END:VEVENT
* Black Bears vs. Muckdogs
<2018-08-20 Mon 18:05-21:05>
:PROPERTIES:
:ID:       AYUCLFT4_O2YnG2cMbue6CPE@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Black Bears vs. Muckdogs Black Bears vs. Muckdogs

Follow on MiLB First Pitch  https //stza.co/+xW1D-P

Shop  https //stza.co/+xW1D-30

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Black Bears vs. Muckdogs
END:VALARM
DTSTART:20180820T230500Z
DTEND:20180821T020500Z
UID:AYUCLFT4_O2YnG2cMbue6CPE@stanza.co
SUMMARY:Black Bears vs. Muckdogs
DESCRIPTION:Black Bears vs. Muckdogs\n\nFollow on MiLB First Pitch: https://stza.co/+xW1D-P\n\nShop: https://stza.co/+xW1D-30\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144605Z
LAST-MODIFIED:20180213T144605Z
TRANSP:OPAQUE
END:VEVENT
* Black Bears vs. Muckdogs
<2018-08-21 Tue 18:05-21:05>
:PROPERTIES:
:ID:       g2PkZY4hum9Or89pjy3Izvb3@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Black Bears vs. Muckdogs Black Bears vs. Muckdogs

Follow on MiLB First Pitch  https //stza.co/+xW1F-2D

Shop  https //stza.co/+xW1F-1N

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Black Bears vs. Muckdogs
END:VALARM
DTSTART:20180821T230500Z
DTEND:20180822T020500Z
UID:g2PkZY4hum9Or89pjy3Izvb3@stanza.co
SUMMARY:Black Bears vs. Muckdogs
DESCRIPTION:Black Bears vs. Muckdogs\n\nFollow on MiLB First Pitch: https://stza.co/+xW1F-2D\n\nShop: https://stza.co/+xW1F-1N\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144605Z
LAST-MODIFIED:20180213T144605Z
TRANSP:OPAQUE
END:VEVENT
* Black Bears vs. Muckdogs
<2018-08-22 Wed 18:05-21:05>
:PROPERTIES:
:ID:       PRAcKCvDPvoAHOSXbizYfuop@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Black Bears vs. Muckdogs Black Bears vs. Muckdogs

Follow on MiLB First Pitch  https //stza.co/+xW1H-A

Shop  https //stza.co/+xW1H-2k

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Black Bears vs. Muckdogs
END:VALARM
DTSTART:20180822T230500Z
DTEND:20180823T020500Z
UID:PRAcKCvDPvoAHOSXbizYfuop@stanza.co
SUMMARY:Black Bears vs. Muckdogs
DESCRIPTION:Black Bears vs. Muckdogs\n\nFollow on MiLB First Pitch: https://stza.co/+xW1H-A\n\nShop: https://stza.co/+xW1H-2k\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144605Z
LAST-MODIFIED:20180213T144605Z
TRANSP:OPAQUE
END:VEVENT
* Black Bears @ Scrappers
<2018-08-23 Thu>--<2018-08-22 Wed>
:PROPERTIES:
:ID:       nW2d6lnIe76lpnuFC81rSK3W@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Black Bears @ Scrappers Black Bears @ Scrappers

Follow on MiLB First Pitch  https //stza.co/+xMzr-t

Shop  https //stza.co/+xMzr-1_

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Black Bears @ Scrappers
END:VALARM
DTSTART;VALUE=DATE:20180823
DTEND;VALUE=DATE:20180823
UID:nW2d6lnIe76lpnuFC81rSK3W@stanza.co
SUMMARY:Black Bears @ Scrappers
DESCRIPTION:Black Bears @ Scrappers\n\nFollow on MiLB First Pitch: https://stza.co/+xMzr-t\n\nShop: https://stza.co/+xMzr-1_\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144605Z
LAST-MODIFIED:20180213T144605Z
TRANSP:OPAQUE
END:VEVENT
* Black Bears @ Scrappers
<2018-08-24 Fri>--<2018-08-23 Thu>
:PROPERTIES:
:ID:       DvI7khL4HLLBs6MjtTyFvFDQ@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Black Bears @ Scrappers Black Bears @ Scrappers

Follow on MiLB First Pitch  https //stza.co/+xMzs-r

Shop  https //stza.co/+xMzs-3e

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Black Bears @ Scrappers
END:VALARM
DTSTART;VALUE=DATE:20180824
DTEND;VALUE=DATE:20180824
UID:DvI7khL4HLLBs6MjtTyFvFDQ@stanza.co
SUMMARY:Black Bears @ Scrappers
DESCRIPTION:Black Bears @ Scrappers\n\nFollow on MiLB First Pitch: https://stza.co/+xMzs-r\n\nShop: https://stza.co/+xMzs-3e\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144605Z
LAST-MODIFIED:20180213T144605Z
TRANSP:OPAQUE
END:VEVENT
* Black Bears @ Scrappers
<2018-08-25 Sat>--<2018-08-24 Fri>
:PROPERTIES:
:ID:       9NH8gtJ1Iz8-x94Y28NWlDx_@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Black Bears @ Scrappers Black Bears @ Scrappers

Follow on MiLB First Pitch  https //stza.co/+xMzt-2$

Shop  https //stza.co/+xMzt-C

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Black Bears @ Scrappers
END:VALARM
DTSTART;VALUE=DATE:20180825
DTEND;VALUE=DATE:20180825
UID:9NH8gtJ1Iz8-x94Y28NWlDx_@stanza.co
SUMMARY:Black Bears @ Scrappers
DESCRIPTION:Black Bears @ Scrappers\n\nFollow on MiLB First Pitch: https://stza.co/+xMzt-2$\n\nShop: https://stza.co/+xMzt-C\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144605Z
LAST-MODIFIED:20180213T144605Z
TRANSP:OPAQUE
END:VEVENT
* Black Bears vs. Doubledays
<2018-08-26 Sun 15:05-18:05>
:PROPERTIES:
:ID:       tzFcDtvrGhkYGop4nF6gGEYV@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Black Bears vs. Doubledays Black Bears vs. Doubledays

Follow on MiLB First Pitch  https //stza.co/+xW1K-3D

Shop  https //stza.co/+xW1K-f

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Black Bears vs. Doubledays
END:VALARM
DTSTART:20180826T200500Z
DTEND:20180826T230500Z
UID:tzFcDtvrGhkYGop4nF6gGEYV@stanza.co
SUMMARY:Black Bears vs. Doubledays
DESCRIPTION:Black Bears vs. Doubledays\n\nFollow on MiLB First Pitch: https://stza.co/+xW1K-3D\n\nShop: https://stza.co/+xW1K-f\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144605Z
LAST-MODIFIED:20180213T144605Z
TRANSP:OPAQUE
END:VEVENT
* Black Bears vs. Doubledays
<2018-08-27 Mon 18:05-21:05>
:PROPERTIES:
:ID:       6jjy2RvOdK_ga_T5QZSgh-ax@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Black Bears vs. Doubledays Black Bears vs. Doubledays

Follow on MiLB First Pitch  https //stza.co/+xW1L-D

Shop  https //stza.co/+xW1L-1k

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Black Bears vs. Doubledays
END:VALARM
DTSTART:20180827T230500Z
DTEND:20180828T020500Z
UID:6jjy2RvOdK_ga_T5QZSgh-ax@stanza.co
SUMMARY:Black Bears vs. Doubledays
DESCRIPTION:Black Bears vs. Doubledays\n\nFollow on MiLB First Pitch: https://stza.co/+xW1L-D\n\nShop: https://stza.co/+xW1L-1k\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144605Z
LAST-MODIFIED:20180213T144605Z
TRANSP:OPAQUE
END:VEVENT
* Black Bears vs. Doubledays
<2018-08-28 Tue 18:05-21:05>
:PROPERTIES:
:ID:       UhtyoNK10ccHpnOyDGVtCeel@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Black Bears vs. Doubledays Black Bears vs. Doubledays

Follow on MiLB First Pitch  https //stza.co/+xW1N-3k

Shop  https //stza.co/+xW1N-o

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Black Bears vs. Doubledays
END:VALARM
DTSTART:20180828T230500Z
DTEND:20180829T020500Z
UID:UhtyoNK10ccHpnOyDGVtCeel@stanza.co
SUMMARY:Black Bears vs. Doubledays
DESCRIPTION:Black Bears vs. Doubledays\n\nFollow on MiLB First Pitch: https://stza.co/+xW1N-3k\n\nShop: https://stza.co/+xW1N-o\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144605Z
LAST-MODIFIED:20180213T144605Z
TRANSP:OPAQUE
END:VEVENT
* Black Bears @ Spikes
<2018-08-29 Wed>--<2018-08-28 Tue>
:PROPERTIES:
:ID:       x9atOR6nop-csd0LdBFeCFL0@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Black Bears @ Spikes Black Bears @ Spikes

Follow on MiLB First Pitch  https //stza.co/+xMzx-3R

Shop  https //stza.co/+xMzx-D

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Black Bears @ Spikes
END:VALARM
DTSTART;VALUE=DATE:20180829
DTEND;VALUE=DATE:20180829
UID:x9atOR6nop-csd0LdBFeCFL0@stanza.co
SUMMARY:Black Bears @ Spikes
DESCRIPTION:Black Bears @ Spikes\n\nFollow on MiLB First Pitch: https://stza.co/+xMzx-3R\n\nShop: https://stza.co/+xMzx-D\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144605Z
LAST-MODIFIED:20180213T144605Z
TRANSP:OPAQUE
END:VEVENT
* Black Bears @ Spikes
<2018-08-30 Thu>--<2018-08-29 Wed>
:PROPERTIES:
:ID:       ezndo_nP9joYsNX--65TsdEa@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Black Bears @ Spikes Black Bears @ Spikes

Follow on MiLB First Pitch  https //stza.co/+xMzy-2i

Shop  https //stza.co/+xMzy-1F

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Black Bears @ Spikes
END:VALARM
DTSTART;VALUE=DATE:20180830
DTEND;VALUE=DATE:20180830
UID:ezndo_nP9joYsNX--65TsdEa@stanza.co
SUMMARY:Black Bears @ Spikes
DESCRIPTION:Black Bears @ Spikes\n\nFollow on MiLB First Pitch: https://stza.co/+xMzy-2i\n\nShop: https://stza.co/+xMzy-1F\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144605Z
LAST-MODIFIED:20180213T144605Z
TRANSP:OPAQUE
END:VEVENT
* Black Bears @ Spikes
<2018-08-31 Fri>--<2018-08-30 Thu>
:PROPERTIES:
:ID:       IBU37fxvseDcrsfSmH43fNAy@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Black Bears @ Spikes Black Bears @ Spikes

Follow on MiLB First Pitch  https //stza.co/+xMzz-1C

Shop  https //stza.co/+xMzz-28

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Black Bears @ Spikes
END:VALARM
DTSTART;VALUE=DATE:20180831
DTEND;VALUE=DATE:20180831
UID:IBU37fxvseDcrsfSmH43fNAy@stanza.co
SUMMARY:Black Bears @ Spikes
DESCRIPTION:Black Bears @ Spikes\n\nFollow on MiLB First Pitch: https://stza.co/+xMzz-1C\n\nShop: https://stza.co/+xMzz-28\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144605Z
LAST-MODIFIED:20180213T144605Z
TRANSP:OPAQUE
END:VEVENT
* Black Bears vs. Scrappers
<2018-09-01 Sat 18:05-21:05>
:PROPERTIES:
:ID:       es0bWBeCV2sz9umXGPnJ0632@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Black Bears vs. Scrappers Black Bears vs. Scrappers

Follow on MiLB First Pitch  https //stza.co/+xW1Q-3V

Shop  https //stza.co/+xW1Q-3A

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Black Bears vs. Scrappers
END:VALARM
DTSTART:20180901T230500Z
DTEND:20180902T020500Z
UID:es0bWBeCV2sz9umXGPnJ0632@stanza.co
SUMMARY:Black Bears vs. Scrappers
DESCRIPTION:Black Bears vs. Scrappers\n\nFollow on MiLB First Pitch: https://stza.co/+xW1Q-3V\n\nShop: https://stza.co/+xW1Q-3A\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144605Z
LAST-MODIFIED:20180213T144605Z
TRANSP:OPAQUE
END:VEVENT
* Black Bears vs. Scrappers
<2018-09-02 Sun 15:05-18:05>
:PROPERTIES:
:ID:       QBrfCkCpu42rG-yy9lVZNg4u@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Black Bears vs. Scrappers Black Bears vs. Scrappers

Follow on MiLB First Pitch  https //stza.co/+xW1S-X

Shop  https //stza.co/+xW1S-W

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Black Bears vs. Scrappers
END:VALARM
DTSTART:20180902T200500Z
DTEND:20180902T230500Z
UID:QBrfCkCpu42rG-yy9lVZNg4u@stanza.co
SUMMARY:Black Bears vs. Scrappers
DESCRIPTION:Black Bears vs. Scrappers\n\nFollow on MiLB First Pitch: https://stza.co/+xW1S-X\n\nShop: https://stza.co/+xW1S-W\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144605Z
LAST-MODIFIED:20180213T144605Z
TRANSP:OPAQUE
END:VEVENT
* Black Bears vs. Scrappers
<2018-09-03 Mon 12:05-15:05>
:PROPERTIES:
:ID:       QoPgTJXT1h95ztefGQ6J7Zmi@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Black Bears vs. Scrappers Black Bears vs. Scrappers

Follow on MiLB First Pitch  https //stza.co/+xW1T-2F

Shop  https //stza.co/+xW1T-2i

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Black Bears vs. Scrappers
END:VALARM
DTSTART:20180903T170500Z
DTEND:20180903T200500Z
UID:QoPgTJXT1h95ztefGQ6J7Zmi@stanza.co
SUMMARY:Black Bears vs. Scrappers
DESCRIPTION:Black Bears vs. Scrappers\n\nFollow on MiLB First Pitch: https://stza.co/+xW1T-2F\n\nShop: https://stza.co/+xW1T-2i\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144605Z
LAST-MODIFIED:20180213T144605Z
TRANSP:OPAQUE
END:VEVENT
