#+TITLE:       Main Google calendar entries
#+AUTHOR:      Eric S Fraga
#+EMAIL:       e.fraga@ucl.ac.uk
#+DESCRIPTION: converted using the ical2org awk script
#+CATEGORY:    google
#+STARTUP:     hidestars
#+STARTUP:     overview

* COMMENT original iCal preamble

* Aces vs. Grizzlies
<2018-04-05 Thu 20:35-23:35>
:PROPERTIES:
:ID:       QRsuuHiC6tMydyMAs7Q3hvag@stanza.co
:LOCATION: Opening Day
:STATUS:   CONFIRMED
:END:

Aces vs. Grizzlies Kick off 2018 with the Aces as we enter our 10th season celebration!

Come quench your thirst and enjoy a game with us on Thirsty Thursdays! Enjoy $2 pints of Coors Light until the middle of the 5th inning.

Be one of the first 2,500 fans through the gates and receive an Aces Magnetic Schedule! 

Follow on MiLB First Pitch  https //stza.co/+wjF3-1r

Shop  https //stza.co/+wjF3-t

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Aces vs. Grizzlies
END:VALARM
DTSTART:20180406T013500Z
DTEND:20180406T043500Z
UID:QRsuuHiC6tMydyMAs7Q3hvag@stanza.co
SUMMARY:Aces vs. Grizzlies
DESCRIPTION:Kick off 2018 with the Aces as we enter our 10th season celebration!\n\nCome quench your thirst and enjoy a game with us on Thirsty Thursdays! Enjoy $2 pints of Coors Light until the middle of the 5th inning.\n\nBe one of the first 2,500 fans through the gates and receive an Aces Magnetic Schedule! \n\nFollow on MiLB First Pitch: https://stza.co/+wjF3-1r\n\nShop: https://stza.co/+wjF3-t\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Opening Day
STATUS:CONFIRMED
CREATED:20180213T144553Z
LAST-MODIFIED:20180213T144553Z
TRANSP:OPAQUE
END:VEVENT
* Aces vs. Grizzlies
<2018-04-06 Fri 20:35-23:35>
:PROPERTIES:
:ID:       JmMcijpzfDi1wOolM5ZpXDD3@stanza.co
:LOCATION: Saint Mary's Fireworks Friday
:STATUS:   CONFIRMED
:END:

Aces vs. Grizzlies Come see our spectacular fireworks display! It's sure to light up the sky and your heart.

Follow on MiLB First Pitch  https //stza.co/+wjF5-1F

Shop  https //stza.co/+wjF5-6

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Aces vs. Grizzlies
END:VALARM
DTSTART:20180407T013500Z
DTEND:20180407T043500Z
UID:JmMcijpzfDi1wOolM5ZpXDD3@stanza.co
SUMMARY:Aces vs. Grizzlies
DESCRIPTION:Come see our spectacular fireworks display! It's sure to light up the sky and your heart.\n\nFollow on MiLB First Pitch: https://stza.co/+wjF5-1F\n\nShop: https://stza.co/+wjF5-6\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Saint Mary's Fireworks Friday
STATUS:CONFIRMED
CREATED:20180213T144553Z
LAST-MODIFIED:20180213T144553Z
TRANSP:OPAQUE
END:VEVENT
* Aces vs. Grizzlies
<2018-04-07 Sat 18:05-21:05>
:PROPERTIES:
:ID:       j5PjHEG6cpKLF0Kpj7FFnURA@stanza.co
:LOCATION: Fleece Blanket Giveaway
:STATUS:   CONFIRMED
:END:

Aces vs. Grizzlies Be one of the first 1,000 lucky fans to receive an Aces 10th season fleece blanket!

Follow on MiLB First Pitch  https //stza.co/+wjF8-32

Shop  https //stza.co/+wjF8-2O

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Aces vs. Grizzlies
END:VALARM
DTSTART:20180407T230500Z
DTEND:20180408T020500Z
UID:j5PjHEG6cpKLF0Kpj7FFnURA@stanza.co
SUMMARY:Aces vs. Grizzlies
DESCRIPTION:Be one of the first 1,000 lucky fans to receive an Aces 10th season fleece blanket!\n\nFollow on MiLB First Pitch: https://stza.co/+wjF8-32\n\nShop: https://stza.co/+wjF8-2O\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Fleece Blanket Giveaway
STATUS:CONFIRMED
CREATED:20180213T144553Z
LAST-MODIFIED:20180213T144553Z
TRANSP:OPAQUE
END:VEVENT
* Aces vs. Grizzlies
<2018-04-08 Sun 15:05-18:05>
:PROPERTIES:
:ID:       OratEMlsJFpZzIu9nyBgQ5T6@stanza.co
:LOCATION: Dollar Menu Sunday
:STATUS:   CONFIRMED
:END:

Aces vs. Grizzlies Come for the games, stay for the Dollar Menu Sundays!

Follow along with the ballgame by playing Baseball Bingo!

Follow on MiLB First Pitch  https //stza.co/+wjF9-3T

Shop  https //stza.co/+wjF9-1W

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Aces vs. Grizzlies
END:VALARM
DTSTART:20180408T200500Z
DTEND:20180408T230500Z
UID:OratEMlsJFpZzIu9nyBgQ5T6@stanza.co
SUMMARY:Aces vs. Grizzlies
DESCRIPTION:Come for the games, stay for the Dollar Menu Sundays!\n\nFollow along with the ballgame by playing Baseball Bingo!\n\nFollow on MiLB First Pitch: https://stza.co/+wjF9-3T\n\nShop: https://stza.co/+wjF9-1W\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Dollar Menu Sunday
STATUS:CONFIRMED
CREATED:20180213T144553Z
LAST-MODIFIED:20180213T144553Z
TRANSP:OPAQUE
END:VEVENT
* Aces vs. Grizzlies
<2018-04-09 Mon 15:05-18:05>
:PROPERTIES:
:ID:       sYmGGYmyMcElgb0g5AvLiEzL@stanza.co
:LOCATION: Military Monday
:STATUS:   CONFIRMED
:END:

Aces vs. Grizzlies Receive BOGO tickets on Infield Reserve, Right Field Reserve and Standing Room Only for all active and retired military personnel & first responders courtesy of Jones-West Ford.

Follow on MiLB First Pitch  https //stza.co/+wjFc-18

Shop  https //stza.co/+wjFc-2E

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Aces vs. Grizzlies
END:VALARM
DTSTART:20180409T200500Z
DTEND:20180409T230500Z
UID:sYmGGYmyMcElgb0g5AvLiEzL@stanza.co
SUMMARY:Aces vs. Grizzlies
DESCRIPTION:Receive BOGO tickets on Infield Reserve, Right Field Reserve and Standing Room Only for all active and retired military personnel & first responders courtesy of Jones-West Ford.\n\nFollow on MiLB First Pitch: https://stza.co/+wjFc-18\n\nShop: https://stza.co/+wjFc-2E\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Military Monday
STATUS:CONFIRMED
CREATED:20180213T144553Z
LAST-MODIFIED:20180213T144553Z
TRANSP:OPAQUE
END:VEVENT
* Aces @ River Cats
<2018-04-10 Tue 21:05>--<2018-04-11 Wed 00:05>
:PROPERTIES:
:ID:       t0xPnED5rIG079Te_MDo7cjE@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Aces @ River Cats Aces @ River Cats

Follow on MiLB First Pitch  https //stza.co/+wjHs-r

Shop  https //stza.co/+wjHs-2g

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Aces @ River Cats
END:VALARM
DTSTART:20180411T020500Z
DTEND:20180411T050500Z
UID:t0xPnED5rIG079Te_MDo7cjE@stanza.co
SUMMARY:Aces @ River Cats
DESCRIPTION:Aces @ River Cats\n\nFollow on MiLB First Pitch: https://stza.co/+wjHs-r\n\nShop: https://stza.co/+wjHs-2g\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144553Z
LAST-MODIFIED:20180213T144553Z
TRANSP:OPAQUE
END:VEVENT
* Aces @ River Cats
<2018-04-11 Wed 14:05-17:05>
:PROPERTIES:
:ID:       LjSeF6_rlbA8pHRSQdcba_QA@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Aces @ River Cats Aces @ River Cats

Follow on MiLB First Pitch  https //stza.co/+wjHt-2I

Shop  https //stza.co/+wjHt-1

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Aces @ River Cats
END:VALARM
DTSTART:20180411T190500Z
DTEND:20180411T220500Z
UID:LjSeF6_rlbA8pHRSQdcba_QA@stanza.co
SUMMARY:Aces @ River Cats
DESCRIPTION:Aces @ River Cats\n\nFollow on MiLB First Pitch: https://stza.co/+wjHt-2I\n\nShop: https://stza.co/+wjHt-1\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144553Z
LAST-MODIFIED:20180213T144553Z
TRANSP:OPAQUE
END:VEVENT
* Aces @ River Cats
<2018-04-12 Thu 21:05>--<2018-04-13 Fri 00:05>
:PROPERTIES:
:ID:       h_6JtA4Jdfw-GBgEOkO-BgDk@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Aces @ River Cats Aces @ River Cats

Follow on MiLB First Pitch  https //stza.co/+wjHu-1L

Shop  https //stza.co/+wjHu-1q

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Aces @ River Cats
END:VALARM
DTSTART:20180413T020500Z
DTEND:20180413T050500Z
UID:h_6JtA4Jdfw-GBgEOkO-BgDk@stanza.co
SUMMARY:Aces @ River Cats
DESCRIPTION:Aces @ River Cats\n\nFollow on MiLB First Pitch: https://stza.co/+wjHu-1L\n\nShop: https://stza.co/+wjHu-1q\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144553Z
LAST-MODIFIED:20180213T144553Z
TRANSP:OPAQUE
END:VEVENT
* Aces @ Grizzlies
<2018-04-13 Fri 21:05>--<2018-04-14 Sat 00:05>
:PROPERTIES:
:ID:       GgB_fQiIj6LZ4xsyXeymCAvk@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Aces @ Grizzlies Aces @ Grizzlies

Follow on MiLB First Pitch  https //stza.co/+wjEW-p

Shop  https //stza.co/+wjEW-2H

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Aces @ Grizzlies
END:VALARM
DTSTART:20180414T020500Z
DTEND:20180414T050500Z
UID:GgB_fQiIj6LZ4xsyXeymCAvk@stanza.co
SUMMARY:Aces @ Grizzlies
DESCRIPTION:Aces @ Grizzlies\n\nFollow on MiLB First Pitch: https://stza.co/+wjEW-p\n\nShop: https://stza.co/+wjEW-2H\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144553Z
LAST-MODIFIED:20180213T144553Z
TRANSP:OPAQUE
END:VEVENT
* Aces @ Grizzlies
<2018-04-14 Sat 21:05>--<2018-04-15 Sun 00:05>
:PROPERTIES:
:ID:       pPdkL3ayoGQ-ld6y-VH7gHqS@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Aces @ Grizzlies Aces @ Grizzlies

Follow on MiLB First Pitch  https //stza.co/+wjEX-M

Shop  https //stza.co/+wjEX-1E

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Aces @ Grizzlies
END:VALARM
DTSTART:20180415T020500Z
DTEND:20180415T050500Z
UID:pPdkL3ayoGQ-ld6y-VH7gHqS@stanza.co
SUMMARY:Aces @ Grizzlies
DESCRIPTION:Aces @ Grizzlies\n\nFollow on MiLB First Pitch: https://stza.co/+wjEX-M\n\nShop: https://stza.co/+wjEX-1E\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144553Z
LAST-MODIFIED:20180213T144553Z
TRANSP:OPAQUE
END:VEVENT
* Aces @ Grizzlies
<2018-04-15 Sun 15:05-18:05>
:PROPERTIES:
:ID:       lHkZ3LAP2XqEkMQ_n1yCoSU1@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Aces @ Grizzlies Aces @ Grizzlies

Follow on MiLB First Pitch  https //stza.co/+wjEZ-1f

Shop  https //stza.co/+wjEZ-9

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Aces @ Grizzlies
END:VALARM
DTSTART:20180415T200500Z
DTEND:20180415T230500Z
UID:lHkZ3LAP2XqEkMQ_n1yCoSU1@stanza.co
SUMMARY:Aces @ Grizzlies
DESCRIPTION:Aces @ Grizzlies\n\nFollow on MiLB First Pitch: https://stza.co/+wjEZ-1f\n\nShop: https://stza.co/+wjEZ-9\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144553Z
LAST-MODIFIED:20180213T144553Z
TRANSP:OPAQUE
END:VEVENT
* Aces @ Grizzlies
<2018-04-16 Mon 13:05-16:05>
:PROPERTIES:
:ID:       e6w55lqwlW_LDkglWiLtnjqu@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Aces @ Grizzlies Aces @ Grizzlies

Follow on MiLB First Pitch  https //stza.co/+wjE_-1Z

Shop  https //stza.co/+wjE_-3C

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Aces @ Grizzlies
END:VALARM
DTSTART:20180416T180500Z
DTEND:20180416T210500Z
UID:e6w55lqwlW_LDkglWiLtnjqu@stanza.co
SUMMARY:Aces @ Grizzlies
DESCRIPTION:Aces @ Grizzlies\n\nFollow on MiLB First Pitch: https://stza.co/+wjE_-1Z\n\nShop: https://stza.co/+wjE_-3C\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144553Z
LAST-MODIFIED:20180213T144553Z
TRANSP:OPAQUE
END:VEVENT
* Aces vs. Chihuahuas
<2018-04-17 Tue 20:35-23:35>
:PROPERTIES:
:ID:       XDbGKtWDx81PAGmtvQ_Ko5Sf@stanza.co
:LOCATION: 2-for-$22 Tuesdays
:STATUS:   CONFIRMED
:END:

Aces vs. Chihuahuas Bring a friend for 2-for-$22 Tuesdays its 2 good to miss. For just $22 receive 2 hot dogs, 2 sodas and 2 Standing Room Only tickets.

It's the 10th season anniversary of the first Aces home game! Pay whatever you want to attend that night's game, it's on the Aces! Offer only available at the Ticket Office. Offer not available online.

Follow on MiLB First Pitch  https //stza.co/+wjFe-2I

Shop  https //stza.co/+wjFe-2k

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Aces vs. Chihuahuas
END:VALARM
DTSTART:20180418T013500Z
DTEND:20180418T043500Z
UID:XDbGKtWDx81PAGmtvQ_Ko5Sf@stanza.co
SUMMARY:Aces vs. Chihuahuas
DESCRIPTION:Bring a friend for 2-for-$22 Tuesdays its 2 good to miss. For just $22 receive 2 hot dogs, 2 sodas and 2 Standing Room Only tickets.\n\nIt's the 10th season anniversary of the first Aces home game! Pay whatever you want to attend that night's game, it's on the Aces! Offer only available at the Ticket Office. Offer not available online.\n\nFollow on MiLB First Pitch: https://stza.co/+wjFe-2I\n\nShop: https://stza.co/+wjFe-2k\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:2-for-$22 Tuesdays
STATUS:CONFIRMED
CREATED:20180213T144553Z
LAST-MODIFIED:20180213T144553Z
TRANSP:OPAQUE
END:VEVENT
* Aces vs. Chihuahuas
<2018-04-18 Wed 20:35-23:35>
:PROPERTIES:
:ID:       FV525bvvwUKn_QBmTs6CMA12@stanza.co
:LOCATION: Dog Days of Summer
:STATUS:   CONFIRMED
:END:

Aces vs. Chihuahuas Bring mans best friend to the ballyard every Wednesday home game! Enter via the Media Entrance along Kuenzli Street and bring proof of your pup's rabies vaccination. Human tickets are required for entrance.

Over 50 years old?! Receive BOGO tickets on any physical seating section with proof of ID at the Ticket Office.

Follow on MiLB First Pitch  https //stza.co/+wjFg-T

Shop  https //stza.co/+wjFg-32

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Aces vs. Chihuahuas
END:VALARM
DTSTART:20180419T013500Z
DTEND:20180419T043500Z
UID:FV525bvvwUKn_QBmTs6CMA12@stanza.co
SUMMARY:Aces vs. Chihuahuas
DESCRIPTION:Bring mans best friend to the ballyard every Wednesday home game! Enter via the Media Entrance along Kuenzli Street and bring proof of your pup's rabies vaccination. Human tickets are required for entrance.\n\nOver 50 years old?! Receive BOGO tickets on any physical seating section with proof of ID at the Ticket Office.\n\nFollow on MiLB First Pitch: https://stza.co/+wjFg-T\n\nShop: https://stza.co/+wjFg-32\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Dog Days of Summer
STATUS:CONFIRMED
CREATED:20180213T144553Z
LAST-MODIFIED:20180213T144553Z
TRANSP:OPAQUE
END:VEVENT
* Aces vs. Chihuahuas
<2018-04-19 Thu 20:35-23:35>
:PROPERTIES:
:ID:       SavvG24ccjpXNbc2VLbKPyVN@stanza.co
:LOCATION: Coors Light Thirsty Thursdays
:STATUS:   CONFIRMED
:END:

Aces vs. Chihuahuas Come quench your thirst and enjoy a game with us on Thirsty Thursdays! Enjoy $2 pints of Coors Light until the middle of the 5th inning.

Follow on MiLB First Pitch  https //stza.co/+wjFi-25

Shop  https //stza.co/+wjFi-15

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Aces vs. Chihuahuas
END:VALARM
DTSTART:20180420T013500Z
DTEND:20180420T043500Z
UID:SavvG24ccjpXNbc2VLbKPyVN@stanza.co
SUMMARY:Aces vs. Chihuahuas
DESCRIPTION:Come quench your thirst and enjoy a game with us on Thirsty Thursdays! Enjoy $2 pints of Coors Light until the middle of the 5th inning.\n\nFollow on MiLB First Pitch: https://stza.co/+wjFi-25\n\nShop: https://stza.co/+wjFi-15\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Coors Light Thirsty Thursdays
STATUS:CONFIRMED
CREATED:20180213T144553Z
LAST-MODIFIED:20180213T144553Z
TRANSP:OPAQUE
END:VEVENT
* Aces vs. Chihuahuas
<2018-04-20 Fri 20:35-23:35>
:PROPERTIES:
:ID:       D50BzCTIqJIHa1nAaYgmrX7J@stanza.co
:LOCATION: Saint Mary's Fireworks Friday
:STATUS:   CONFIRMED
:END:

Aces vs. Chihuahuas Come see our spectacular fireworks display! It's sure to light up the sky and your heart.

Follow on MiLB First Pitch  https //stza.co/+wjFk-2k

Shop  https //stza.co/+wjFk-2r

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Aces vs. Chihuahuas
END:VALARM
DTSTART:20180421T013500Z
DTEND:20180421T043500Z
UID:D50BzCTIqJIHa1nAaYgmrX7J@stanza.co
SUMMARY:Aces vs. Chihuahuas
DESCRIPTION:Come see our spectacular fireworks display! It's sure to light up the sky and your heart.\n\nFollow on MiLB First Pitch: https://stza.co/+wjFk-2k\n\nShop: https://stza.co/+wjFk-2r\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Saint Mary's Fireworks Friday
STATUS:CONFIRMED
CREATED:20180213T144553Z
LAST-MODIFIED:20180213T144553Z
TRANSP:OPAQUE
END:VEVENT
* Aces vs. Grizzlies
<2018-04-21 Sat 18:05-21:05>
:PROPERTIES:
:ID:       CHu9p8PgoUHc6D4a7vnIgObZ@stanza.co
:LOCATION: 10th Season Baseball Giveaway
:STATUS:   CONFIRMED
:END:

Aces vs. Grizzlies Be one of the first 1,000 lucky fans to receive an Aces 10th season baseball!

Follow on MiLB First Pitch  https //stza.co/+wjFo-P

Shop  https //stza.co/+wjFo-2n

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Aces vs. Grizzlies
END:VALARM
DTSTART:20180421T230500Z
DTEND:20180422T020500Z
UID:CHu9p8PgoUHc6D4a7vnIgObZ@stanza.co
SUMMARY:Aces vs. Grizzlies
DESCRIPTION:Be one of the first 1,000 lucky fans to receive an Aces 10th season baseball!\n\nFollow on MiLB First Pitch: https://stza.co/+wjFo-P\n\nShop: https://stza.co/+wjFo-2n\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:10th Season Baseball Giveaway
STATUS:CONFIRMED
CREATED:20180213T144553Z
LAST-MODIFIED:20180213T144553Z
TRANSP:OPAQUE
END:VEVENT
* Aces vs. Grizzlies
<2018-04-22 Sun 15:05-18:05>
:PROPERTIES:
:ID:       V-h7o4YTLCByGC1Ah8iUEw12@stanza.co
:LOCATION: Dollar Menu Sunday
:STATUS:   CONFIRMED
:END:

Aces vs. Grizzlies Come for the games, stay for the Dollar Menu Sundays!

Follow along with the ballgame by playing Baseball Bingo!

Follow on MiLB First Pitch  https //stza.co/+wjFr-a

Shop  https //stza.co/+wjFr-34

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Aces vs. Grizzlies
END:VALARM
DTSTART:20180422T200500Z
DTEND:20180422T230500Z
UID:V-h7o4YTLCByGC1Ah8iUEw12@stanza.co
SUMMARY:Aces vs. Grizzlies
DESCRIPTION:Come for the games, stay for the Dollar Menu Sundays!\n\nFollow along with the ballgame by playing Baseball Bingo!\n\nFollow on MiLB First Pitch: https://stza.co/+wjFr-a\n\nShop: https://stza.co/+wjFr-34\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Dollar Menu Sunday
STATUS:CONFIRMED
CREATED:20180213T144553Z
LAST-MODIFIED:20180213T144553Z
TRANSP:OPAQUE
END:VEVENT
* Aces vs. Grizzlies
<2018-04-23 Mon 13:35-16:35>
:PROPERTIES:
:ID:       zjWuErtv7htDvDvvmyf4f0BG@stanza.co
:LOCATION: Military Monday
:STATUS:   CONFIRMED
:END:

Aces vs. Grizzlies Receive BOGO tickets on Infield Reserve, Right Field Reserve and Standing Room Only for all active and retired military personnel & first responders courtesy of Jones-West Ford.

Follow on MiLB First Pitch  https //stza.co/+wjFu-2F

Shop  https //stza.co/+wjFu-1W

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Aces vs. Grizzlies
END:VALARM
DTSTART:20180423T183500Z
DTEND:20180423T213500Z
UID:zjWuErtv7htDvDvvmyf4f0BG@stanza.co
SUMMARY:Aces vs. Grizzlies
DESCRIPTION:Receive BOGO tickets on Infield Reserve, Right Field Reserve and Standing Room Only for all active and retired military personnel & first responders courtesy of Jones-West Ford.\n\nFollow on MiLB First Pitch: https://stza.co/+wjFu-2F\n\nShop: https://stza.co/+wjFu-1W\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Military Monday
STATUS:CONFIRMED
CREATED:20180213T144553Z
LAST-MODIFIED:20180213T144553Z
TRANSP:OPAQUE
END:VEVENT
* Aces @ River Cats
<2018-04-25 Wed 21:05>--<2018-04-26 Thu 00:05>
:PROPERTIES:
:ID:       rJqktyuQJWnLeVoIDHmG1BJD@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Aces @ River Cats Aces @ River Cats

Follow on MiLB First Pitch  https //stza.co/+wjHw-N

Shop  https //stza.co/+wjHw-2B

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Aces @ River Cats
END:VALARM
DTSTART:20180426T020500Z
DTEND:20180426T050500Z
UID:rJqktyuQJWnLeVoIDHmG1BJD@stanza.co
SUMMARY:Aces @ River Cats
DESCRIPTION:Aces @ River Cats\n\nFollow on MiLB First Pitch: https://stza.co/+wjHw-N\n\nShop: https://stza.co/+wjHw-2B\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144553Z
LAST-MODIFIED:20180213T144553Z
TRANSP:OPAQUE
END:VEVENT
* Aces @ River Cats
<2018-04-26 Thu 21:05>--<2018-04-27 Fri 00:05>
:PROPERTIES:
:ID:       d94iIAOY49D3MWocTheDbau2@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Aces @ River Cats Aces @ River Cats

Follow on MiLB First Pitch  https //stza.co/+wjHy-3b

Shop  https //stza.co/+wjHy-2Q

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Aces @ River Cats
END:VALARM
DTSTART:20180427T020500Z
DTEND:20180427T050500Z
UID:d94iIAOY49D3MWocTheDbau2@stanza.co
SUMMARY:Aces @ River Cats
DESCRIPTION:Aces @ River Cats\n\nFollow on MiLB First Pitch: https://stza.co/+wjHy-3b\n\nShop: https://stza.co/+wjHy-2Q\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144553Z
LAST-MODIFIED:20180213T144553Z
TRANSP:OPAQUE
END:VEVENT
* Aces @ River Cats
<2018-04-27 Fri 21:05>--<2018-04-28 Sat 00:05>
:PROPERTIES:
:ID:       jcCfyuIdotvYx1xofYrHTUDW@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Aces @ River Cats Aces @ River Cats

Follow on MiLB First Pitch  https //stza.co/+wjHz-1j

Shop  https //stza.co/+wjHz-2A

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Aces @ River Cats
END:VALARM
DTSTART:20180428T020500Z
DTEND:20180428T050500Z
UID:jcCfyuIdotvYx1xofYrHTUDW@stanza.co
SUMMARY:Aces @ River Cats
DESCRIPTION:Aces @ River Cats\n\nFollow on MiLB First Pitch: https://stza.co/+wjHz-1j\n\nShop: https://stza.co/+wjHz-2A\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144553Z
LAST-MODIFIED:20180213T144553Z
TRANSP:OPAQUE
END:VEVENT
* Aces @ River Cats
<2018-04-28 Sat 21:05>--<2018-04-29 Sun 00:05>
:PROPERTIES:
:ID:       WSW49V949NzCztlRTe1zr2J6@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Aces @ River Cats Aces @ River Cats

Follow on MiLB First Pitch  https //stza.co/+wjHB-1J

Shop  https //stza.co/+wjHB-2M

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Aces @ River Cats
END:VALARM
DTSTART:20180429T020500Z
DTEND:20180429T050500Z
UID:WSW49V949NzCztlRTe1zr2J6@stanza.co
SUMMARY:Aces @ River Cats
DESCRIPTION:Aces @ River Cats\n\nFollow on MiLB First Pitch: https://stza.co/+wjHB-1J\n\nShop: https://stza.co/+wjHB-2M\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144553Z
LAST-MODIFIED:20180213T144553Z
TRANSP:OPAQUE
END:VEVENT
* Aces @ River Cats
<2018-04-29 Sun 15:05-18:05>
:PROPERTIES:
:ID:       pYhjJZN5Q3CPaD2ChotSHH2J@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Aces @ River Cats Aces @ River Cats

Follow on MiLB First Pitch  https //stza.co/+wjHC-2g

Shop  https //stza.co/+wjHC-3H

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Aces @ River Cats
END:VALARM
DTSTART:20180429T200500Z
DTEND:20180429T230500Z
UID:pYhjJZN5Q3CPaD2ChotSHH2J@stanza.co
SUMMARY:Aces @ River Cats
DESCRIPTION:Aces @ River Cats\n\nFollow on MiLB First Pitch: https://stza.co/+wjHC-2g\n\nShop: https://stza.co/+wjHC-3H\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144553Z
LAST-MODIFIED:20180213T144553Z
TRANSP:OPAQUE
END:VEVENT
* Aces @ Chihuahuas
<2018-04-30 Mon 19:35-22:35>
:PROPERTIES:
:ID:       CWqXPjyJhKWDZ9v4RMaLh3cg@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Aces @ Chihuahuas Aces @ Chihuahuas

Follow on MiLB First Pitch  https //stza.co/+wmL2-2H

Shop  https //stza.co/+wmL2-2m

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Aces @ Chihuahuas
END:VALARM
DTSTART:20180501T003500Z
DTEND:20180501T033500Z
UID:CWqXPjyJhKWDZ9v4RMaLh3cg@stanza.co
SUMMARY:Aces @ Chihuahuas
DESCRIPTION:Aces @ Chihuahuas\n\nFollow on MiLB First Pitch: https://stza.co/+wmL2-2H\n\nShop: https://stza.co/+wmL2-2m\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144553Z
LAST-MODIFIED:20180213T144553Z
TRANSP:OPAQUE
END:VEVENT
* Aces @ Chihuahuas
<2018-05-01 Tue 19:35-22:35>
:PROPERTIES:
:ID:       RvB1N0LJ974IktZDuzYDkdVj@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Aces @ Chihuahuas Aces @ Chihuahuas

Follow on MiLB First Pitch  https //stza.co/+wmL5-K

Shop  https //stza.co/+wmL5-1W

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Aces @ Chihuahuas
END:VALARM
DTSTART:20180502T003500Z
DTEND:20180502T033500Z
UID:RvB1N0LJ974IktZDuzYDkdVj@stanza.co
SUMMARY:Aces @ Chihuahuas
DESCRIPTION:Aces @ Chihuahuas\n\nFollow on MiLB First Pitch: https://stza.co/+wmL5-K\n\nShop: https://stza.co/+wmL5-1W\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144553Z
LAST-MODIFIED:20180213T144553Z
TRANSP:OPAQUE
END:VEVENT
* Aces @ Chihuahuas
<2018-05-02 Wed 12:05-15:05>
:PROPERTIES:
:ID:       _sdE94ptc0aaYfYYMBWAr-sc@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Aces @ Chihuahuas Aces @ Chihuahuas

Follow on MiLB First Pitch  https //stza.co/+wmL6-1a

Shop  https //stza.co/+wmL6-3K

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Aces @ Chihuahuas
END:VALARM
DTSTART:20180502T170500Z
DTEND:20180502T200500Z
UID:_sdE94ptc0aaYfYYMBWAr-sc@stanza.co
SUMMARY:Aces @ Chihuahuas
DESCRIPTION:Aces @ Chihuahuas\n\nFollow on MiLB First Pitch: https://stza.co/+wmL6-1a\n\nShop: https://stza.co/+wmL6-3K\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144553Z
LAST-MODIFIED:20180213T144553Z
TRANSP:OPAQUE
END:VEVENT
* Aces @ Chihuahuas
<2018-05-03 Thu 19:35-22:35>
:PROPERTIES:
:ID:       qlzqRUm1oKmTbnqdIfoFL3OH@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Aces @ Chihuahuas Aces @ Chihuahuas

Follow on MiLB First Pitch  https //stza.co/+wmL7-3n

Shop  https //stza.co/+wmL7-1S

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Aces @ Chihuahuas
END:VALARM
DTSTART:20180504T003500Z
DTEND:20180504T033500Z
UID:qlzqRUm1oKmTbnqdIfoFL3OH@stanza.co
SUMMARY:Aces @ Chihuahuas
DESCRIPTION:Aces @ Chihuahuas\n\nFollow on MiLB First Pitch: https://stza.co/+wmL7-3n\n\nShop: https://stza.co/+wmL7-1S\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144553Z
LAST-MODIFIED:20180213T144553Z
TRANSP:OPAQUE
END:VEVENT
* Aces vs. Rainiers
<2018-05-04 Fri 20:35-23:35>
:PROPERTIES:
:ID:       KiuKScVVxsQ0HhDo4GzP-N2x@stanza.co
:LOCATION: Saint Mary's Fireworks Friday
:STATUS:   CONFIRMED
:END:

Aces vs. Rainiers Come see our spectacular fireworks display! It's sure to light up the sky and your heart.

Follow on MiLB First Pitch  https //stza.co/+wjFy-x

Shop  https //stza.co/+wjFy-2i

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Aces vs. Rainiers
END:VALARM
DTSTART:20180505T013500Z
DTEND:20180505T043500Z
UID:KiuKScVVxsQ0HhDo4GzP-N2x@stanza.co
SUMMARY:Aces vs. Rainiers
DESCRIPTION:Come see our spectacular fireworks display! It's sure to light up the sky and your heart.\n\nFollow on MiLB First Pitch: https://stza.co/+wjFy-x\n\nShop: https://stza.co/+wjFy-2i\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Saint Mary's Fireworks Friday
STATUS:CONFIRMED
CREATED:20180213T144553Z
LAST-MODIFIED:20180213T144553Z
TRANSP:OPAQUE
END:VEVENT
* Aces vs. Rainiers
<2018-05-05 Sat 20:35-23:35>
:PROPERTIES:
:ID:       K8Ip2EPWoWaS-JAuICd05fOE@stanza.co
:LOCATION: 10th Season Mini Bat Giveaway
:STATUS:   CONFIRMED
:END:

Aces vs. Rainiers Be one of the first 1,000 lucky fans to receive an Aces 10th season mini bat courtesy of Greater Nevada Credit Union!

Pick-up your 10th Season Mini Bat presented by Greater Nevada Credit Union while enjoying Cinco de Mayo at Greater Nevada Field! 

Follow on MiLB First Pitch  https //stza.co/+wjFA-o

Shop  https //stza.co/+wjFA-4

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Aces vs. Rainiers
END:VALARM
DTSTART:20180506T013500Z
DTEND:20180506T043500Z
UID:K8Ip2EPWoWaS-JAuICd05fOE@stanza.co
SUMMARY:Aces vs. Rainiers
DESCRIPTION:Be one of the first 1,000 lucky fans to receive an Aces 10th season mini bat courtesy of Greater Nevada Credit Union!\n\nPick-up your 10th Season Mini Bat presented by Greater Nevada Credit Union while enjoying Cinco de Mayo at Greater Nevada Field! \n\nFollow on MiLB First Pitch: https://stza.co/+wjFA-o\n\nShop: https://stza.co/+wjFA-4\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:10th Season Mini Bat Giveaway
STATUS:CONFIRMED
CREATED:20180213T144553Z
LAST-MODIFIED:20180213T144553Z
TRANSP:OPAQUE
END:VEVENT
* Aces vs. Rainiers
<2018-05-06 Sun 15:05-18:05>
:PROPERTIES:
:ID:       GpxYeNaUh4FRlktRJtNYvtyw@stanza.co
:LOCATION: Dollar Menu Sunday
:STATUS:   CONFIRMED
:END:

Aces vs. Rainiers Come for the games, stay for the Dollar Menu Sundays!

Follow along with the ballgame by playing Baseball Bingo!

Follow on MiLB First Pitch  https //stza.co/+wjFD-3z

Shop  https //stza.co/+wjFD-23

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Aces vs. Rainiers
END:VALARM
DTSTART:20180506T200500Z
DTEND:20180506T230500Z
UID:GpxYeNaUh4FRlktRJtNYvtyw@stanza.co
SUMMARY:Aces vs. Rainiers
DESCRIPTION:Come for the games, stay for the Dollar Menu Sundays!\n\nFollow along with the ballgame by playing Baseball Bingo!\n\nFollow on MiLB First Pitch: https://stza.co/+wjFD-3z\n\nShop: https://stza.co/+wjFD-23\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Dollar Menu Sunday
STATUS:CONFIRMED
CREATED:20180213T144553Z
LAST-MODIFIED:20180213T144553Z
TRANSP:OPAQUE
END:VEVENT
* Aces vs. Rainiers
<2018-05-07 Mon 13:35-16:35>
:PROPERTIES:
:ID:       ckKTqTae6R9-NAoi8ge1P31s@stanza.co
:LOCATION: Military Monday
:STATUS:   CONFIRMED
:END:

Aces vs. Rainiers Receive BOGO tickets on Infield Reserve, Right Field Reserve and Standing Room Only for all active and retired military personnel & first responders courtesy of Jones-West Ford.

Follow on MiLB First Pitch  https //stza.co/+wjFF-2D

Shop  https //stza.co/+wjFF-11

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Aces vs. Rainiers
END:VALARM
DTSTART:20180507T183500Z
DTEND:20180507T213500Z
UID:ckKTqTae6R9-NAoi8ge1P31s@stanza.co
SUMMARY:Aces vs. Rainiers
DESCRIPTION:Receive BOGO tickets on Infield Reserve, Right Field Reserve and Standing Room Only for all active and retired military personnel & first responders courtesy of Jones-West Ford.\n\nFollow on MiLB First Pitch: https://stza.co/+wjFF-2D\n\nShop: https://stza.co/+wjFF-11\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Military Monday
STATUS:CONFIRMED
CREATED:20180213T144553Z
LAST-MODIFIED:20180213T144553Z
TRANSP:OPAQUE
END:VEVENT
* Aces vs. Isotopes
<2018-05-08 Tue 20:35-23:35>
:PROPERTIES:
:ID:       6wClIs9IPz9h56P2_78I_oCs@stanza.co
:LOCATION: 2-for-$22 Tuesdays
:STATUS:   CONFIRMED
:END:

Aces vs. Isotopes Bring a friend for 2-for-$22 Tuesdays its 2 good to miss. For just $22 receive 2 hot dogs, 2 sodas and 2 Standing Room Only tickets.

Follow on MiLB First Pitch  https //stza.co/+wjFH-y

Shop  https //stza.co/+wjFH-8

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Aces vs. Isotopes
END:VALARM
DTSTART:20180509T013500Z
DTEND:20180509T043500Z
UID:6wClIs9IPz9h56P2_78I_oCs@stanza.co
SUMMARY:Aces vs. Isotopes
DESCRIPTION:Bring a friend for 2-for-$22 Tuesdays its 2 good to miss. For just $22 receive 2 hot dogs, 2 sodas and 2 Standing Room Only tickets.\n\nFollow on MiLB First Pitch: https://stza.co/+wjFH-y\n\nShop: https://stza.co/+wjFH-8\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:2-for-$22 Tuesdays
STATUS:CONFIRMED
CREATED:20180213T144553Z
LAST-MODIFIED:20180213T144553Z
TRANSP:OPAQUE
END:VEVENT
* Aces vs. Isotopes
<2018-05-09 Wed 20:35-23:35>
:PROPERTIES:
:ID:       IpN9T9B_3jDtze44cIkzag_s@stanza.co
:LOCATION: Reno's 150th Birthday in Partnership with the City of Reno
:STATUS:   CONFIRMED
:END:

Aces vs. Isotopes May 9 marks Reno's 150th Birthday! To put the icing on the cake, that night's game is FREE! 

Don't miss the best fireworks shows in town! 

Follow on MiLB First Pitch  https //stza.co/+wjFJ-3z

Shop  https //stza.co/+wjFJ-1m

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Aces vs. Isotopes
END:VALARM
DTSTART:20180510T013500Z
DTEND:20180510T043500Z
UID:IpN9T9B_3jDtze44cIkzag_s@stanza.co
SUMMARY:Aces vs. Isotopes
DESCRIPTION:May 9 marks Reno's 150th Birthday! To put the icing on the cake, that night's game is FREE! \n\nDon't miss the best fireworks shows in town! \n\nFollow on MiLB First Pitch: https://stza.co/+wjFJ-3z\n\nShop: https://stza.co/+wjFJ-1m\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Reno's 150th Birthday in Partnership with the City of Reno
STATUS:CONFIRMED
CREATED:20180213T144553Z
LAST-MODIFIED:20180213T144553Z
TRANSP:OPAQUE
END:VEVENT
* Aces vs. Isotopes
<2018-05-10 Thu 20:35-23:35>
:PROPERTIES:
:ID:       _BuMo_XwiiV223xCmzX7rEuF@stanza.co
:LOCATION: Coors Light Thirsty Thursdays
:STATUS:   CONFIRMED
:END:

Aces vs. Isotopes Come quench your thirst and enjoy a game with us on Thirsty Thursdays! Enjoy $2 pints of Coors Light until the middle of the 5th inning.

Follow on MiLB First Pitch  https //stza.co/+wjFL-3y

Shop  https //stza.co/+wjFL-3g

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Aces vs. Isotopes
END:VALARM
DTSTART:20180511T013500Z
DTEND:20180511T043500Z
UID:_BuMo_XwiiV223xCmzX7rEuF@stanza.co
SUMMARY:Aces vs. Isotopes
DESCRIPTION:Come quench your thirst and enjoy a game with us on Thirsty Thursdays! Enjoy $2 pints of Coors Light until the middle of the 5th inning.\n\nFollow on MiLB First Pitch: https://stza.co/+wjFL-3y\n\nShop: https://stza.co/+wjFL-3g\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Coors Light Thirsty Thursdays
STATUS:CONFIRMED
CREATED:20180213T144553Z
LAST-MODIFIED:20180213T144553Z
TRANSP:OPAQUE
END:VEVENT
* Aces vs. Isotopes
<2018-05-11 Fri 20:35-23:35>
:PROPERTIES:
:ID:       _axtKxJpQyuHntXyfNcUjatV@stanza.co
:LOCATION: Saint Mary's Fireworks Friday
:STATUS:   CONFIRMED
:END:

Aces vs. Isotopes Come see our spectacular fireworks display! It's sure to light up the sky and your heart.

Follow on MiLB First Pitch  https //stza.co/+wjFM-1k

Shop  https //stza.co/+wjFM-2p

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Aces vs. Isotopes
END:VALARM
DTSTART:20180512T013500Z
DTEND:20180512T043500Z
UID:_axtKxJpQyuHntXyfNcUjatV@stanza.co
SUMMARY:Aces vs. Isotopes
DESCRIPTION:Come see our spectacular fireworks display! It's sure to light up the sky and your heart.\n\nFollow on MiLB First Pitch: https://stza.co/+wjFM-1k\n\nShop: https://stza.co/+wjFM-2p\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Saint Mary's Fireworks Friday
STATUS:CONFIRMED
CREATED:20180213T144553Z
LAST-MODIFIED:20180213T144553Z
TRANSP:OPAQUE
END:VEVENT
* Aces vs. Chihuahuas
<2018-05-12 Sat 20:35-23:35>
:PROPERTIES:
:ID:       A0QT_s-zSgE4S53K0lmsILjQ@stanza.co
:LOCATION: May the force be with you! Come check out Stars Wars Night at the park
:STATUS:   CONFIRMED
:END:

Aces vs. Chihuahuas Let the force be with you May 12 during Star Wars Night! Mingle with the 501st Legion, watch fireworks and bid on Star Wars themed jerseys with proceeds benefiting the Northern Nevada Children's Cancer Foundation.

Don't miss the best fireworks shows in town! 

Follow on MiLB First Pitch  https //stza.co/+wjFO-21

Shop  https //stza.co/+wjFO-2I

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Aces vs. Chihuahuas
END:VALARM
DTSTART:20180513T013500Z
DTEND:20180513T043500Z
UID:A0QT_s-zSgE4S53K0lmsILjQ@stanza.co
SUMMARY:Aces vs. Chihuahuas
DESCRIPTION:Let the force be with you May 12 during Star Wars Night! Mingle with the 501st Legion, watch fireworks and bid on Star Wars themed jerseys with proceeds benefiting the Northern Nevada Children's Cancer Foundation.\n\nDon't miss the best fireworks shows in town! \n\nFollow on MiLB First Pitch: https://stza.co/+wjFO-21\n\nShop: https://stza.co/+wjFO-2I\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:May the force be with you! Come check out Stars Wars Night at the park
STATUS:CONFIRMED
CREATED:20180213T144553Z
LAST-MODIFIED:20180213T144553Z
TRANSP:OPAQUE
END:VEVENT
* Aces vs. Chihuahuas
<2018-05-13 Sun 15:05-18:05>
:PROPERTIES:
:ID:       XL5sTsiDj4WcdF45jhPa0ywN@stanza.co
:LOCATION: Mother's Day
:STATUS:   CONFIRMED
:END:

Aces vs. Chihuahuas Bring Mom out to the field for a day of fun and baseball! Enjoy the Dollar Menu Sunday and follow along with the game by playing Baseball Bingo! 

Come for the games, stay for the Dollar Menu Sundays!

Follow along with the ballgame by playing Baseball Bingo!

Follow on MiLB First Pitch  https //stza.co/+wjFQ-3f

Shop  https //stza.co/+wjFQ-1u

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Aces vs. Chihuahuas
END:VALARM
DTSTART:20180513T200500Z
DTEND:20180513T230500Z
UID:XL5sTsiDj4WcdF45jhPa0ywN@stanza.co
SUMMARY:Aces vs. Chihuahuas
DESCRIPTION:Bring Mom out to the field for a day of fun and baseball! Enjoy the Dollar Menu Sunday and follow along with the game by playing Baseball Bingo! \n\nCome for the games, stay for the Dollar Menu Sundays!\n\nFollow along with the ballgame by playing Baseball Bingo!\n\nFollow on MiLB First Pitch: https://stza.co/+wjFQ-3f\n\nShop: https://stza.co/+wjFQ-1u\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Mother's Day
STATUS:CONFIRMED
CREATED:20180213T144553Z
LAST-MODIFIED:20180213T144553Z
TRANSP:OPAQUE
END:VEVENT
* Aces vs. Chihuahuas
<2018-05-14 Mon 20:35-23:35>
:PROPERTIES:
:ID:       d0XW8_xwdc5tGZPKVSWy0GFI@stanza.co
:LOCATION: Military Monday
:STATUS:   CONFIRMED
:END:

Aces vs. Chihuahuas Receive BOGO tickets on Infield Reserve, Right Field Reserve and Standing Room Only for all active and retired military personnel & first responders courtesy of Jones-West Ford.

Follow on MiLB First Pitch  https //stza.co/+wjFS-R

Shop  https //stza.co/+wjFS-1N

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Aces vs. Chihuahuas
END:VALARM
DTSTART:20180515T013500Z
DTEND:20180515T043500Z
UID:d0XW8_xwdc5tGZPKVSWy0GFI@stanza.co
SUMMARY:Aces vs. Chihuahuas
DESCRIPTION:Receive BOGO tickets on Infield Reserve, Right Field Reserve and Standing Room Only for all active and retired military personnel & first responders courtesy of Jones-West Ford.\n\nFollow on MiLB First Pitch: https://stza.co/+wjFS-R\n\nShop: https://stza.co/+wjFS-1N\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Military Monday
STATUS:CONFIRMED
CREATED:20180213T144553Z
LAST-MODIFIED:20180213T144553Z
TRANSP:OPAQUE
END:VEVENT
* Aces vs. Chihuahuas
<2018-05-15 Tue 13:35-16:35>
:PROPERTIES:
:ID:       G9JzeES2cLxMK4mi3YuAsbpc@stanza.co
:LOCATION: 2-for-$22 Tuesdays
:STATUS:   CONFIRMED
:END:

Aces vs. Chihuahuas Bring a friend for 2-for-$22 Tuesdays its 2 good to miss. For just $22 receive 2 hot dogs, 2 sodas and 2 Standing Room Only tickets.

Follow on MiLB First Pitch  https //stza.co/+wjFV-5

Shop  https //stza.co/+wjFV-3z

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Aces vs. Chihuahuas
END:VALARM
DTSTART:20180515T183500Z
DTEND:20180515T213500Z
UID:G9JzeES2cLxMK4mi3YuAsbpc@stanza.co
SUMMARY:Aces vs. Chihuahuas
DESCRIPTION:Bring a friend for 2-for-$22 Tuesdays its 2 good to miss. For just $22 receive 2 hot dogs, 2 sodas and 2 Standing Room Only tickets.\n\nFollow on MiLB First Pitch: https://stza.co/+wjFV-5\n\nShop: https://stza.co/+wjFV-3z\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:2-for-$22 Tuesdays
STATUS:CONFIRMED
CREATED:20180213T144553Z
LAST-MODIFIED:20180213T144553Z
TRANSP:OPAQUE
END:VEVENT
* Aces @ Isotopes
<2018-05-17 Thu 19:35-22:35>
:PROPERTIES:
:ID:       zv9rS87T48eTZp1cqdg1IizQ@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Aces @ Isotopes Aces @ Isotopes

Follow on MiLB First Pitch  https //stza.co/+whPz-3i

Shop  https //stza.co/+whPz-

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Aces @ Isotopes
END:VALARM
DTSTART:20180518T003500Z
DTEND:20180518T033500Z
UID:zv9rS87T48eTZp1cqdg1IizQ@stanza.co
SUMMARY:Aces @ Isotopes
DESCRIPTION:Aces @ Isotopes\n\nFollow on MiLB First Pitch: https://stza.co/+whPz-3i\n\nShop: https://stza.co/+whPz-\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144553Z
LAST-MODIFIED:20180213T144553Z
TRANSP:OPAQUE
END:VEVENT
* Aces @ Isotopes
<2018-05-18 Fri 19:35-22:35>
:PROPERTIES:
:ID:       JlQX88lteGvr8iVavXJZ4s4G@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Aces @ Isotopes Aces @ Isotopes

Follow on MiLB First Pitch  https //stza.co/+whPA-1C

Shop  https //stza.co/+whPA-3I

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Aces @ Isotopes
END:VALARM
DTSTART:20180519T003500Z
DTEND:20180519T033500Z
UID:JlQX88lteGvr8iVavXJZ4s4G@stanza.co
SUMMARY:Aces @ Isotopes
DESCRIPTION:Aces @ Isotopes\n\nFollow on MiLB First Pitch: https://stza.co/+whPA-1C\n\nShop: https://stza.co/+whPA-3I\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144553Z
LAST-MODIFIED:20180213T144553Z
TRANSP:OPAQUE
END:VEVENT
* Aces @ Isotopes
<2018-05-19 Sat 19:35-22:35>
:PROPERTIES:
:ID:       79zrhrBDK8VbOMV80wgxR3wk@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Aces @ Isotopes Aces @ Isotopes

Follow on MiLB First Pitch  https //stza.co/+whPB-w

Shop  https //stza.co/+whPB-1x

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Aces @ Isotopes
END:VALARM
DTSTART:20180520T003500Z
DTEND:20180520T033500Z
UID:79zrhrBDK8VbOMV80wgxR3wk@stanza.co
SUMMARY:Aces @ Isotopes
DESCRIPTION:Aces @ Isotopes\n\nFollow on MiLB First Pitch: https://stza.co/+whPB-w\n\nShop: https://stza.co/+whPB-1x\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144553Z
LAST-MODIFIED:20180213T144553Z
TRANSP:OPAQUE
END:VEVENT
* Aces @ Isotopes
<2018-05-20 Sun 14:35-17:35>
:PROPERTIES:
:ID:       GvnAIU-1HMlgW7EZCyAZlqYb@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Aces @ Isotopes Aces @ Isotopes

Follow on MiLB First Pitch  https //stza.co/+whPC-2a

Shop  https //stza.co/+whPC-1h

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Aces @ Isotopes
END:VALARM
DTSTART:20180520T193500Z
DTEND:20180520T223500Z
UID:GvnAIU-1HMlgW7EZCyAZlqYb@stanza.co
SUMMARY:Aces @ Isotopes
DESCRIPTION:Aces @ Isotopes\n\nFollow on MiLB First Pitch: https://stza.co/+whPC-2a\n\nShop: https://stza.co/+whPC-1h\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144553Z
LAST-MODIFIED:20180213T144553Z
TRANSP:OPAQUE
END:VEVENT
* Aces @ Grizzlies
<2018-05-21 Mon 20:35-23:35>
:PROPERTIES:
:ID:       XM2CKiWN2m5LcZiMxmfdlvfU@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Aces @ Grizzlies Aces @ Grizzlies

Follow on MiLB First Pitch  https //stza.co/+wjE$-1B

Shop  https //stza.co/+wjE$-20

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Aces @ Grizzlies
END:VALARM
DTSTART:20180522T013500Z
DTEND:20180522T043500Z
UID:XM2CKiWN2m5LcZiMxmfdlvfU@stanza.co
SUMMARY:Aces @ Grizzlies
DESCRIPTION:Aces @ Grizzlies\n\nFollow on MiLB First Pitch: https://stza.co/+wjE$-1B\n\nShop: https://stza.co/+wjE$-20\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144553Z
LAST-MODIFIED:20180213T144553Z
TRANSP:OPAQUE
END:VEVENT
* Aces @ Grizzlies
<2018-05-22 Tue 20:35-23:35>
:PROPERTIES:
:ID:       RoR4eguPAdvsier9W2-5qUZY@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Aces @ Grizzlies Aces @ Grizzlies

Follow on MiLB First Pitch  https //stza.co/+wjF0-2e

Shop  https //stza.co/+wjF0-3U

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Aces @ Grizzlies
END:VALARM
DTSTART:20180523T013500Z
DTEND:20180523T043500Z
UID:RoR4eguPAdvsier9W2-5qUZY@stanza.co
SUMMARY:Aces @ Grizzlies
DESCRIPTION:Aces @ Grizzlies\n\nFollow on MiLB First Pitch: https://stza.co/+wjF0-2e\n\nShop: https://stza.co/+wjF0-3U\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144553Z
LAST-MODIFIED:20180213T144553Z
TRANSP:OPAQUE
END:VEVENT
* Aces @ Grizzlies
<2018-05-23 Wed 13:05-16:05>
:PROPERTIES:
:ID:       CL_qgsWFVHX02752tk-7vpCb@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Aces @ Grizzlies Aces @ Grizzlies

Follow on MiLB First Pitch  https //stza.co/+wjF1-3S

Shop  https //stza.co/+wjF1-2G

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Aces @ Grizzlies
END:VALARM
DTSTART:20180523T180500Z
DTEND:20180523T210500Z
UID:CL_qgsWFVHX02752tk-7vpCb@stanza.co
SUMMARY:Aces @ Grizzlies
DESCRIPTION:Aces @ Grizzlies\n\nFollow on MiLB First Pitch: https://stza.co/+wjF1-3S\n\nShop: https://stza.co/+wjF1-2G\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144553Z
LAST-MODIFIED:20180213T144553Z
TRANSP:OPAQUE
END:VEVENT
* Aces @ Grizzlies
<2018-05-24 Thu 21:05>--<2018-05-25 Fri 00:05>
:PROPERTIES:
:ID:       M0vE6Rj63OshNXzIK-RfQFCU@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Aces @ Grizzlies Aces @ Grizzlies

Follow on MiLB First Pitch  https //stza.co/+wjF2-q

Shop  https //stza.co/+wjF2-j

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Aces @ Grizzlies
END:VALARM
DTSTART:20180525T020500Z
DTEND:20180525T050500Z
UID:M0vE6Rj63OshNXzIK-RfQFCU@stanza.co
SUMMARY:Aces @ Grizzlies
DESCRIPTION:Aces @ Grizzlies\n\nFollow on MiLB First Pitch: https://stza.co/+wjF2-q\n\nShop: https://stza.co/+wjF2-j\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144553Z
LAST-MODIFIED:20180213T144553Z
TRANSP:OPAQUE
END:VEVENT
* Aces @ Bees
<2018-05-25 Fri 19:35-22:35>
:PROPERTIES:
:ID:       0eFscDzbR5gTu1eoHSnwi4g7@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Aces @ Bees Aces @ Bees

Follow on MiLB First Pitch  https //stza.co/+wmLg-37

Shop  https //stza.co/+wmLg-3q

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Aces @ Bees
END:VALARM
DTSTART:20180526T003500Z
DTEND:20180526T033500Z
UID:0eFscDzbR5gTu1eoHSnwi4g7@stanza.co
SUMMARY:Aces @ Bees
DESCRIPTION:Aces @ Bees\n\nFollow on MiLB First Pitch: https://stza.co/+wmLg-37\n\nShop: https://stza.co/+wmLg-3q\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144553Z
LAST-MODIFIED:20180213T144553Z
TRANSP:OPAQUE
END:VEVENT
* Aces @ Bees
<2018-05-26 Sat 19:35-22:35>
:PROPERTIES:
:ID:       A9KZ1HA0oWumTB9hzh8zo5sB@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Aces @ Bees Aces @ Bees

Follow on MiLB First Pitch  https //stza.co/+wmLh-1

Shop  https //stza.co/+wmLh-N

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Aces @ Bees
END:VALARM
DTSTART:20180527T003500Z
DTEND:20180527T033500Z
UID:A9KZ1HA0oWumTB9hzh8zo5sB@stanza.co
SUMMARY:Aces @ Bees
DESCRIPTION:Aces @ Bees\n\nFollow on MiLB First Pitch: https://stza.co/+wmLh-1\n\nShop: https://stza.co/+wmLh-N\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144553Z
LAST-MODIFIED:20180213T144553Z
TRANSP:OPAQUE
END:VEVENT
* Aces @ Bees
<2018-05-27 Sun 19:35-22:35>
:PROPERTIES:
:ID:       sx0skcP15EmN4AJJTeNvN2lR@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Aces @ Bees Aces @ Bees

Follow on MiLB First Pitch  https //stza.co/+wmLi-2D

Shop  https //stza.co/+wmLi-1Z

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Aces @ Bees
END:VALARM
DTSTART:20180528T003500Z
DTEND:20180528T033500Z
UID:sx0skcP15EmN4AJJTeNvN2lR@stanza.co
SUMMARY:Aces @ Bees
DESCRIPTION:Aces @ Bees\n\nFollow on MiLB First Pitch: https://stza.co/+wmLi-2D\n\nShop: https://stza.co/+wmLi-1Z\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144553Z
LAST-MODIFIED:20180213T144553Z
TRANSP:OPAQUE
END:VEVENT
* Aces @ Bees
<2018-05-28 Mon 19:35-22:35>
:PROPERTIES:
:ID:       kDpJB2tGZxpjqF1Mw6iU4Msm@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Aces @ Bees Aces @ Bees

Follow on MiLB First Pitch  https //stza.co/+wmLj-32

Shop  https //stza.co/+wmLj-2

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Aces @ Bees
END:VALARM
DTSTART:20180529T003500Z
DTEND:20180529T033500Z
UID:kDpJB2tGZxpjqF1Mw6iU4Msm@stanza.co
SUMMARY:Aces @ Bees
DESCRIPTION:Aces @ Bees\n\nFollow on MiLB First Pitch: https://stza.co/+wmLj-32\n\nShop: https://stza.co/+wmLj-2\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144553Z
LAST-MODIFIED:20180213T144553Z
TRANSP:OPAQUE
END:VEVENT
* Aces @ Bees
<2018-05-29 Tue 13:05-16:05>
:PROPERTIES:
:ID:       5N5PlhL-Bbv2Nj6DBMiBO5_k@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Aces @ Bees Aces @ Bees

Follow on MiLB First Pitch  https //stza.co/+wmLl-3B

Shop  https //stza.co/+wmLl-17

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Aces @ Bees
END:VALARM
DTSTART:20180529T180500Z
DTEND:20180529T210500Z
UID:5N5PlhL-Bbv2Nj6DBMiBO5_k@stanza.co
SUMMARY:Aces @ Bees
DESCRIPTION:Aces @ Bees\n\nFollow on MiLB First Pitch: https://stza.co/+wmLl-3B\n\nShop: https://stza.co/+wmLl-17\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144553Z
LAST-MODIFIED:20180213T144553Z
TRANSP:OPAQUE
END:VEVENT
* Aces vs. 51s
<2018-05-30 Wed 21:05>--<2018-05-31 Thu 00:05>
:PROPERTIES:
:ID:       zgwWervarIQuM5_Y_sIMgQSJ@stanza.co
:LOCATION: Dog Days of Summer
:STATUS:   CONFIRMED
:END:

Aces vs. 51s Bring mans best friend to the ballyard every Wednesday home game! Enter via the Media Entrance along Kuenzli Street and bring proof of your pup's rabies vaccination. Human tickets are required for entrance.

Over 50 years old?! Receive BOGO tickets on any physical seating section with proof of ID at the Ticket Office.

Follow on MiLB First Pitch  https //stza.co/+wjFW-U

Shop  https //stza.co/+wjFW-k

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Aces vs. 51s
END:VALARM
DTSTART:20180531T020500Z
DTEND:20180531T050500Z
UID:zgwWervarIQuM5_Y_sIMgQSJ@stanza.co
SUMMARY:Aces vs. 51s
DESCRIPTION:Bring mans best friend to the ballyard every Wednesday home game! Enter via the Media Entrance along Kuenzli Street and bring proof of your pup's rabies vaccination. Human tickets are required for entrance.\n\nOver 50 years old?! Receive BOGO tickets on any physical seating section with proof of ID at the Ticket Office.\n\nFollow on MiLB First Pitch: https://stza.co/+wjFW-U\n\nShop: https://stza.co/+wjFW-k\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Dog Days of Summer
STATUS:CONFIRMED
CREATED:20180213T144553Z
LAST-MODIFIED:20180213T144553Z
TRANSP:OPAQUE
END:VEVENT
* Aces vs. 51s
<2018-05-31 Thu 21:05>--<2018-06-01 Fri 00:05>
:PROPERTIES:
:ID:       QyPeFT-TACdszRNYcMWSh1bG@stanza.co
:LOCATION: Coors Light Thirsty Thursdays
:STATUS:   CONFIRMED
:END:

Aces vs. 51s Come quench your thirst and enjoy a game with us on Thirsty Thursdays! Enjoy $2 pints of Coors Light until the middle of the 5th inning.

Follow on MiLB First Pitch  https //stza.co/+wjFZ-5

Shop  https //stza.co/+wjFZ-15

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Aces vs. 51s
END:VALARM
DTSTART:20180601T020500Z
DTEND:20180601T050500Z
UID:QyPeFT-TACdszRNYcMWSh1bG@stanza.co
SUMMARY:Aces vs. 51s
DESCRIPTION:Come quench your thirst and enjoy a game with us on Thirsty Thursdays! Enjoy $2 pints of Coors Light until the middle of the 5th inning.\n\nFollow on MiLB First Pitch: https://stza.co/+wjFZ-5\n\nShop: https://stza.co/+wjFZ-15\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Coors Light Thirsty Thursdays
STATUS:CONFIRMED
CREATED:20180213T144553Z
LAST-MODIFIED:20180213T144553Z
TRANSP:OPAQUE
END:VEVENT
* Aces vs. 51s
<2018-06-01 Fri 21:05>--<2018-06-02 Sat 00:05>
:PROPERTIES:
:ID:       2A-sv0XmWJeR-td1JGFJNIBG@stanza.co
:LOCATION: Saint Mary's Fireworks Friday
:STATUS:   CONFIRMED
:END:

Aces vs. 51s Come see our spectacular fireworks display! It's sure to light up the sky and your heart.

If you can't get enough Halloween in your life, you're going to want to be at Greater Nevada Field for this spooky baseball experience! After, stay for Saint Mary's Fireworks Friday presented by KRNV News 4 set to your favorite Halloween music.

Follow on MiLB First Pitch  https //stza.co/+wjF_-17

Shop  https //stza.co/+wjF_-Z

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Aces vs. 51s
END:VALARM
DTSTART:20180602T020500Z
DTEND:20180602T050500Z
UID:2A-sv0XmWJeR-td1JGFJNIBG@stanza.co
SUMMARY:Aces vs. 51s
DESCRIPTION:Come see our spectacular fireworks display! It's sure to light up the sky and your heart.\n\nIf you can't get enough Halloween in your life, you're going to want to be at Greater Nevada Field for this spooky baseball experience! After, stay for Saint Mary's Fireworks Friday presented by KRNV News 4 set to your favorite Halloween music.\n\nFollow on MiLB First Pitch: https://stza.co/+wjF_-17\n\nShop: https://stza.co/+wjF_-Z\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Saint Mary's Fireworks Friday
STATUS:CONFIRMED
CREATED:20180213T144553Z
LAST-MODIFIED:20180213T144553Z
TRANSP:OPAQUE
END:VEVENT
* Aces vs. 51s
<2018-06-02 Sat 21:05>--<2018-06-03 Sun 00:05>
:PROPERTIES:
:ID:       NUmofh_q_SzV7gapYzQGqJYR@stanza.co
:LOCATION: Military Appreciation Night
:STATUS:   CONFIRMED
:END:

Aces vs. 51s Join us as we salute our Military members with a postgame Fireworks spectacular!

Don't miss the best fireworks shows in town! 

Follow on MiLB First Pitch  https //stza.co/+wjG0-2P

Shop  https //stza.co/+wjG0-3Y

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Aces vs. 51s
END:VALARM
DTSTART:20180603T020500Z
DTEND:20180603T050500Z
UID:NUmofh_q_SzV7gapYzQGqJYR@stanza.co
SUMMARY:Aces vs. 51s
DESCRIPTION:Join us as we salute our Military members with a postgame Fireworks spectacular!\n\nDon't miss the best fireworks shows in town! \n\nFollow on MiLB First Pitch: https://stza.co/+wjG0-2P\n\nShop: https://stza.co/+wjG0-3Y\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Military Appreciation Night
STATUS:CONFIRMED
CREATED:20180213T144553Z
LAST-MODIFIED:20180213T144553Z
TRANSP:OPAQUE
END:VEVENT
* Aces vs. 51s
<2018-06-03 Sun 15:05-18:05>
:PROPERTIES:
:ID:       DsMvOSQAz93cjqFOw9x3-nkI@stanza.co
:LOCATION: Dollar Menu Sunday
:STATUS:   CONFIRMED
:END:

Aces vs. 51s Come for the games, stay for the Dollar Menu Sundays!

Follow along with the ballgame by playing Baseball Bingo!

Follow on MiLB First Pitch  https //stza.co/+wjG3-d

Shop  https //stza.co/+wjG3-2U

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Aces vs. 51s
END:VALARM
DTSTART:20180603T200500Z
DTEND:20180603T230500Z
UID:DsMvOSQAz93cjqFOw9x3-nkI@stanza.co
SUMMARY:Aces vs. 51s
DESCRIPTION:Come for the games, stay for the Dollar Menu Sundays!\n\nFollow along with the ballgame by playing Baseball Bingo!\n\nFollow on MiLB First Pitch: https://stza.co/+wjG3-d\n\nShop: https://stza.co/+wjG3-2U\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Dollar Menu Sunday
STATUS:CONFIRMED
CREATED:20180213T144553Z
LAST-MODIFIED:20180213T144553Z
TRANSP:OPAQUE
END:VEVENT
* Aces @ Sounds
<2018-06-05 Tue 19:05-22:05>
:PROPERTIES:
:ID:       3iOgKAKTE_J0HHFg9kl8jBRS@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Aces @ Sounds Aces @ Sounds

Follow on MiLB First Pitch  https //stza.co/+whPK-1x

Shop  https //stza.co/+whPK-9

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Aces @ Sounds
END:VALARM
DTSTART:20180606T000500Z
DTEND:20180606T030500Z
UID:3iOgKAKTE_J0HHFg9kl8jBRS@stanza.co
SUMMARY:Aces @ Sounds
DESCRIPTION:Aces @ Sounds\n\nFollow on MiLB First Pitch: https://stza.co/+whPK-1x\n\nShop: https://stza.co/+whPK-9\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144553Z
LAST-MODIFIED:20180213T144553Z
TRANSP:OPAQUE
END:VEVENT
* Aces @ Sounds
<2018-06-06 Wed 19:05-22:05>
:PROPERTIES:
:ID:       VaMsB6ytc6_3iCx0FJ55okhc@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Aces @ Sounds Aces @ Sounds

Follow on MiLB First Pitch  https //stza.co/+whPL-1e

Shop  https //stza.co/+whPL-2H

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Aces @ Sounds
END:VALARM
DTSTART:20180607T000500Z
DTEND:20180607T030500Z
UID:VaMsB6ytc6_3iCx0FJ55okhc@stanza.co
SUMMARY:Aces @ Sounds
DESCRIPTION:Aces @ Sounds\n\nFollow on MiLB First Pitch: https://stza.co/+whPL-1e\n\nShop: https://stza.co/+whPL-2H\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144553Z
LAST-MODIFIED:20180213T144553Z
TRANSP:OPAQUE
END:VEVENT
* Aces @ Sounds
<2018-06-07 Thu 19:05-22:05>
:PROPERTIES:
:ID:       rh8Po0DwswKZY4FkSai58NbK@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Aces @ Sounds Aces @ Sounds

Follow on MiLB First Pitch  https //stza.co/+whPM-2i

Shop  https //stza.co/+whPM-2I

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Aces @ Sounds
END:VALARM
DTSTART:20180608T000500Z
DTEND:20180608T030500Z
UID:rh8Po0DwswKZY4FkSai58NbK@stanza.co
SUMMARY:Aces @ Sounds
DESCRIPTION:Aces @ Sounds\n\nFollow on MiLB First Pitch: https://stza.co/+whPM-2i\n\nShop: https://stza.co/+whPM-2I\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144553Z
LAST-MODIFIED:20180213T144553Z
TRANSP:OPAQUE
END:VEVENT
* Aces @ Redbirds
<2018-06-08 Fri 19:05-22:05>
:PROPERTIES:
:ID:       wxgEDUGgi5vVyrIedQYepY0r@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Aces @ Redbirds Aces @ Redbirds

Follow on MiLB First Pitch  https //stza.co/+wmLc-L

Shop  https //stza.co/+wmLc-21

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Aces @ Redbirds
END:VALARM
DTSTART:20180609T000500Z
DTEND:20180609T030500Z
UID:wxgEDUGgi5vVyrIedQYepY0r@stanza.co
SUMMARY:Aces @ Redbirds
DESCRIPTION:Aces @ Redbirds\n\nFollow on MiLB First Pitch: https://stza.co/+wmLc-L\n\nShop: https://stza.co/+wmLc-21\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144553Z
LAST-MODIFIED:20180213T144553Z
TRANSP:OPAQUE
END:VEVENT
* Aces @ Redbirds
<2018-06-09 Sat 18:35-21:35>
:PROPERTIES:
:ID:       ri8y0--36ePDlEUnDgnYSLh4@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Aces @ Redbirds Aces @ Redbirds

Follow on MiLB First Pitch  https //stza.co/+wmLd-10

Shop  https //stza.co/+wmLd-2

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Aces @ Redbirds
END:VALARM
DTSTART:20180609T233500Z
DTEND:20180610T023500Z
UID:ri8y0--36ePDlEUnDgnYSLh4@stanza.co
SUMMARY:Aces @ Redbirds
DESCRIPTION:Aces @ Redbirds\n\nFollow on MiLB First Pitch: https://stza.co/+wmLd-10\n\nShop: https://stza.co/+wmLd-2\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144553Z
LAST-MODIFIED:20180213T144553Z
TRANSP:OPAQUE
END:VEVENT
* Aces @ Redbirds
<2018-06-10 Sun 14:05-17:05>
:PROPERTIES:
:ID:       jIfqzWswI8Grl6YNEQpvdMSP@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Aces @ Redbirds Aces @ Redbirds

Follow on MiLB First Pitch  https //stza.co/+wmLe-1L

Shop  https //stza.co/+wmLe-m

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Aces @ Redbirds
END:VALARM
DTSTART:20180610T190500Z
DTEND:20180610T220500Z
UID:jIfqzWswI8Grl6YNEQpvdMSP@stanza.co
SUMMARY:Aces @ Redbirds
DESCRIPTION:Aces @ Redbirds\n\nFollow on MiLB First Pitch: https://stza.co/+wmLe-1L\n\nShop: https://stza.co/+wmLe-m\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144553Z
LAST-MODIFIED:20180213T144553Z
TRANSP:OPAQUE
END:VEVENT
* Aces @ Redbirds
<2018-06-11 Mon 12:05-15:05>
:PROPERTIES:
:ID:       UNuKUM4_s8cMz4oMgSX3Q1ij@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Aces @ Redbirds Aces @ Redbirds

Follow on MiLB First Pitch  https //stza.co/+wmLf-j

Shop  https //stza.co/+wmLf-19

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Aces @ Redbirds
END:VALARM
DTSTART:20180611T170500Z
DTEND:20180611T200500Z
UID:UNuKUM4_s8cMz4oMgSX3Q1ij@stanza.co
SUMMARY:Aces @ Redbirds
DESCRIPTION:Aces @ Redbirds\n\nFollow on MiLB First Pitch: https://stza.co/+wmLf-j\n\nShop: https://stza.co/+wmLf-19\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144553Z
LAST-MODIFIED:20180213T144553Z
TRANSP:OPAQUE
END:VEVENT
* Aces vs. Cubs
<2018-06-13 Wed 21:05>--<2018-06-14 Thu 00:05>
:PROPERTIES:
:ID:       -Qn198Xn9e8Ar4FtwSU9zC3e@stanza.co
:LOCATION: Dog Days of Summer
:STATUS:   CONFIRMED
:END:

Aces vs. Cubs Bring mans best friend to the ballyard every Wednesday home game! Enter via the Media Entrance along Kuenzli Street and bring proof of your pup's rabies vaccination. Human tickets are required for entrance.

Over 50 years old?! Receive BOGO tickets on any physical seating section with proof of ID at the Ticket Office.



Follow on MiLB First Pitch  https //stza.co/+wjG6-1j

Shop  https //stza.co/+wjG6-e

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Aces vs. Cubs
END:VALARM
DTSTART:20180614T020500Z
DTEND:20180614T050500Z
UID:-Qn198Xn9e8Ar4FtwSU9zC3e@stanza.co
SUMMARY:Aces vs. Cubs
DESCRIPTION:Bring mans best friend to the ballyard every Wednesday home game! Enter via the Media Entrance along Kuenzli Street and bring proof of your pup's rabies vaccination. Human tickets are required for entrance.\n\nOver 50 years old?! Receive BOGO tickets on any physical seating section with proof of ID at the Ticket Office.\n\n\n\nFollow on MiLB First Pitch: https://stza.co/+wjG6-1j\n\nShop: https://stza.co/+wjG6-e\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Dog Days of Summer
STATUS:CONFIRMED
CREATED:20180213T144553Z
LAST-MODIFIED:20180213T144553Z
TRANSP:OPAQUE
END:VEVENT
* Aces vs. Cubs
<2018-06-14 Thu 21:05>--<2018-06-15 Fri 00:05>
:PROPERTIES:
:ID:       -H--jp8T5vahMpAmL8LJg4TX@stanza.co
:LOCATION: Coors Light Thirsty Thursdays
:STATUS:   CONFIRMED
:END:

Aces vs. Cubs Come quench your thirst and enjoy a game with us on Thirsty Thursdays! Enjoy $2 pints of Coors Light until the middle of the 5th inning.

Follow on MiLB First Pitch  https //stza.co/+wjG8-3O

Shop  https //stza.co/+wjG8-n

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Aces vs. Cubs
END:VALARM
DTSTART:20180615T020500Z
DTEND:20180615T050500Z
UID:-H--jp8T5vahMpAmL8LJg4TX@stanza.co
SUMMARY:Aces vs. Cubs
DESCRIPTION:Come quench your thirst and enjoy a game with us on Thirsty Thursdays! Enjoy $2 pints of Coors Light until the middle of the 5th inning.\n\nFollow on MiLB First Pitch: https://stza.co/+wjG8-3O\n\nShop: https://stza.co/+wjG8-n\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Coors Light Thirsty Thursdays
STATUS:CONFIRMED
CREATED:20180213T144553Z
LAST-MODIFIED:20180213T144553Z
TRANSP:OPAQUE
END:VEVENT
* Aces vs. Cubs
<2018-06-15 Fri 21:05>--<2018-06-16 Sat 00:05>
:PROPERTIES:
:ID:       ytc3aDIZhU3V1Wj0wqqEcx8g@stanza.co
:LOCATION: Saint Mary's Fireworks Friday
:STATUS:   CONFIRMED
:END:

Aces vs. Cubs Come see our spectacular fireworks display! It's sure to light up the sky and your heart.

Follow on MiLB First Pitch  https //stza.co/+wjGa-3_

Shop  https //stza.co/+wjGa-1Y

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Aces vs. Cubs
END:VALARM
DTSTART:20180616T020500Z
DTEND:20180616T050500Z
UID:ytc3aDIZhU3V1Wj0wqqEcx8g@stanza.co
SUMMARY:Aces vs. Cubs
DESCRIPTION:Come see our spectacular fireworks display! It's sure to light up the sky and your heart.\n\nFollow on MiLB First Pitch: https://stza.co/+wjGa-3_\n\nShop: https://stza.co/+wjGa-1Y\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Saint Mary's Fireworks Friday
STATUS:CONFIRMED
CREATED:20180213T144553Z
LAST-MODIFIED:20180213T144553Z
TRANSP:OPAQUE
END:VEVENT
* Aces vs. Storm Chasers
<2018-06-16 Sat 21:05>--<2018-06-17 Sun 00:05>
:PROPERTIES:
:ID:       lPe7u6JS-SBYdtxek4TAep7x@stanza.co
:LOCATION: Super Hero Night
:STATUS:   CONFIRMED
:END:

Aces vs. Storm Chasers Featuring a special Captain America Appearance! 

Be one of the first 1,000 lucky fans to receive an Aces 10th season cape giveaway courtesy of Renown Health & Hometown Health!

Follow on MiLB First Pitch  https //stza.co/+wjGc-3G

Shop  https //stza.co/+wjGc-2O

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Aces vs. Storm Chasers
END:VALARM
DTSTART:20180617T020500Z
DTEND:20180617T050500Z
UID:lPe7u6JS-SBYdtxek4TAep7x@stanza.co
SUMMARY:Aces vs. Storm Chasers
DESCRIPTION:Featuring a special Captain America Appearance! \n\nBe one of the first 1,000 lucky fans to receive an Aces 10th season cape giveaway courtesy of Renown Health & Hometown Health!\n\nFollow on MiLB First Pitch: https://stza.co/+wjGc-3G\n\nShop: https://stza.co/+wjGc-2O\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Super Hero Night
STATUS:CONFIRMED
CREATED:20180213T144553Z
LAST-MODIFIED:20180213T144553Z
TRANSP:OPAQUE
END:VEVENT
* Aces vs. Storm Chasers
<2018-06-17 Sun 15:05-18:05>
:PROPERTIES:
:ID:       cXHOf5p3yvT1ysk-358w1YRX@stanza.co
:LOCATION: Father's Day with Pre-Game Catch on the Field
:STATUS:   CONFIRMED
:END:

Aces vs. Storm Chasers Pregame catch on the field

Come for the games, stay for the Dollar Menu Sundays!

Follow along with the ballgame by playing Baseball Bingo!

Follow on MiLB First Pitch  https //stza.co/+wjGe-3j

Shop  https //stza.co/+wjGe-13

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Aces vs. Storm Chasers
END:VALARM
DTSTART:20180617T200500Z
DTEND:20180617T230500Z
UID:cXHOf5p3yvT1ysk-358w1YRX@stanza.co
SUMMARY:Aces vs. Storm Chasers
DESCRIPTION:Pregame catch on the field\n\nCome for the games, stay for the Dollar Menu Sundays!\n\nFollow along with the ballgame by playing Baseball Bingo!\n\nFollow on MiLB First Pitch: https://stza.co/+wjGe-3j\n\nShop: https://stza.co/+wjGe-13\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Father's Day with Pre-Game Catch on the Field
STATUS:CONFIRMED
CREATED:20180213T144553Z
LAST-MODIFIED:20180213T144553Z
TRANSP:OPAQUE
END:VEVENT
* Aces vs. Storm Chasers
<2018-06-18 Mon 21:05>--<2018-06-19 Tue 00:05>
:PROPERTIES:
:ID:       ek6pkdWBoTYipFuFhFUvuzL-@stanza.co
:LOCATION: Military Monday
:STATUS:   CONFIRMED
:END:

Aces vs. Storm Chasers Receive BOGO tickets on Infield Reserve, Right Field Reserve and Standing Room Only for all active and retired military personnel & first responders courtesy of Jones-West Ford.

Follow on MiLB First Pitch  https //stza.co/+wjGf-1S

Shop  https //stza.co/+wjGf-j

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Aces vs. Storm Chasers
END:VALARM
DTSTART:20180619T020500Z
DTEND:20180619T050500Z
UID:ek6pkdWBoTYipFuFhFUvuzL-@stanza.co
SUMMARY:Aces vs. Storm Chasers
DESCRIPTION:Receive BOGO tickets on Infield Reserve, Right Field Reserve and Standing Room Only for all active and retired military personnel & first responders courtesy of Jones-West Ford.\n\nFollow on MiLB First Pitch: https://stza.co/+wjGf-1S\n\nShop: https://stza.co/+wjGf-j\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Military Monday
STATUS:CONFIRMED
CREATED:20180213T144553Z
LAST-MODIFIED:20180213T144553Z
TRANSP:OPAQUE
END:VEVENT
* Aces vs. Storm Chasers
<2018-06-19 Tue 15:05-18:05>
:PROPERTIES:
:ID:       5MxgJnIzmv2zm4OZDPj-7aF2@stanza.co
:LOCATION: 2-for-$22 Tuesdays
:STATUS:   CONFIRMED
:END:

Aces vs. Storm Chasers Bring a friend for 2-for-$22 Tuesdays its 2 good to miss. For just $22 receive 2 hot dogs, 2 sodas and 2 Standing Room Only tickets.

Follow on MiLB First Pitch  https //stza.co/+wjGi-3i

Shop  https //stza.co/+wjGi-2R

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Aces vs. Storm Chasers
END:VALARM
DTSTART:20180619T200500Z
DTEND:20180619T230500Z
UID:5MxgJnIzmv2zm4OZDPj-7aF2@stanza.co
SUMMARY:Aces vs. Storm Chasers
DESCRIPTION:Bring a friend for 2-for-$22 Tuesdays its 2 good to miss. For just $22 receive 2 hot dogs, 2 sodas and 2 Standing Room Only tickets.\n\nFollow on MiLB First Pitch: https://stza.co/+wjGi-3i\n\nShop: https://stza.co/+wjGi-2R\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:2-for-$22 Tuesdays
STATUS:CONFIRMED
CREATED:20180213T144553Z
LAST-MODIFIED:20180213T144553Z
TRANSP:OPAQUE
END:VEVENT
* Aces @ 51s
<2018-06-21 Thu 21:05>--<2018-06-22 Fri 00:05>
:PROPERTIES:
:ID:       WANUI-2LW17Si97i9VMJDI_n@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Aces @ 51s Aces @ 51s

Follow on MiLB First Pitch  https //stza.co/+vKTC-s

Shop  https //stza.co/+vKTC-1q

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Aces @ 51s
END:VALARM
DTSTART:20180622T020500Z
DTEND:20180622T050500Z
UID:WANUI-2LW17Si97i9VMJDI_n@stanza.co
SUMMARY:Aces @ 51s
DESCRIPTION:Aces @ 51s\n\nFollow on MiLB First Pitch: https://stza.co/+vKTC-s\n\nShop: https://stza.co/+vKTC-1q\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144553Z
LAST-MODIFIED:20180213T144553Z
TRANSP:OPAQUE
END:VEVENT
* Aces @ 51s
<2018-06-22 Fri 21:05>--<2018-06-23 Sat 00:05>
:PROPERTIES:
:ID:       FZzdj7eUB_cVLhyTuhRJv3Dd@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Aces @ 51s Aces @ 51s

Follow on MiLB First Pitch  https //stza.co/+vKTD-2E

Shop  https //stza.co/+vKTD-2f

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Aces @ 51s
END:VALARM
DTSTART:20180623T020500Z
DTEND:20180623T050500Z
UID:FZzdj7eUB_cVLhyTuhRJv3Dd@stanza.co
SUMMARY:Aces @ 51s
DESCRIPTION:Aces @ 51s\n\nFollow on MiLB First Pitch: https://stza.co/+vKTD-2E\n\nShop: https://stza.co/+vKTD-2f\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144553Z
LAST-MODIFIED:20180213T144553Z
TRANSP:OPAQUE
END:VEVENT
* Aces @ 51s
<2018-06-23 Sat 21:05>--<2018-06-24 Sun 00:05>
:PROPERTIES:
:ID:       FIlnnA2kmUFkbiFSehqvERgd@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Aces @ 51s Aces @ 51s

Follow on MiLB First Pitch  https //stza.co/+vKTE-28

Shop  https //stza.co/+vKTE-1R

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Aces @ 51s
END:VALARM
DTSTART:20180624T020500Z
DTEND:20180624T050500Z
UID:FIlnnA2kmUFkbiFSehqvERgd@stanza.co
SUMMARY:Aces @ 51s
DESCRIPTION:Aces @ 51s\n\nFollow on MiLB First Pitch: https://stza.co/+vKTE-28\n\nShop: https://stza.co/+vKTE-1R\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144553Z
LAST-MODIFIED:20180213T144553Z
TRANSP:OPAQUE
END:VEVENT
* Aces @ 51s
<2018-06-24 Sun 14:05-17:05>
:PROPERTIES:
:ID:       zNcWB1qjfVCqsRPf9nrzKSBT@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Aces @ 51s Aces @ 51s

Follow on MiLB First Pitch  https //stza.co/+vKTF-1x

Shop  https //stza.co/+vKTF-14

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Aces @ 51s
END:VALARM
DTSTART:20180624T190500Z
DTEND:20180624T220500Z
UID:zNcWB1qjfVCqsRPf9nrzKSBT@stanza.co
SUMMARY:Aces @ 51s
DESCRIPTION:Aces @ 51s\n\nFollow on MiLB First Pitch: https://stza.co/+vKTF-1x\n\nShop: https://stza.co/+vKTF-14\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144553Z
LAST-MODIFIED:20180213T144553Z
TRANSP:OPAQUE
END:VEVENT
* Aces vs. Bees
<2018-06-25 Mon 21:05>--<2018-06-26 Tue 00:05>
:PROPERTIES:
:ID:       9oQumbJ28cLglYoTZt3tR8SV@stanza.co
:LOCATION: Military Monday
:STATUS:   CONFIRMED
:END:

Aces vs. Bees Receive BOGO tickets on Infield Reserve, Right Field Reserve and Standing Room Only for all active and retired military personnel & first responders courtesy of Jones-West Ford.

Follow on MiLB First Pitch  https //stza.co/+wjGj-3V

Shop  https //stza.co/+wjGj-2i

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Aces vs. Bees
END:VALARM
DTSTART:20180626T020500Z
DTEND:20180626T050500Z
UID:9oQumbJ28cLglYoTZt3tR8SV@stanza.co
SUMMARY:Aces vs. Bees
DESCRIPTION:Receive BOGO tickets on Infield Reserve, Right Field Reserve and Standing Room Only for all active and retired military personnel & first responders courtesy of Jones-West Ford.\n\nFollow on MiLB First Pitch: https://stza.co/+wjGj-3V\n\nShop: https://stza.co/+wjGj-2i\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Military Monday
STATUS:CONFIRMED
CREATED:20180213T144553Z
LAST-MODIFIED:20180213T144553Z
TRANSP:OPAQUE
END:VEVENT
* Aces vs. Bees
<2018-06-26 Tue 21:05>--<2018-06-27 Wed 00:05>
:PROPERTIES:
:ID:       kCT-iYLvkt_1vfVkY8cKQrPh@stanza.co
:LOCATION: 2-for-$22 Tuesdays
:STATUS:   CONFIRMED
:END:

Aces vs. Bees Bring a friend for 2-for-$22 Tuesdays its 2 good to miss. For just $22 receive 2 hot dogs, 2 sodas and 2 Standing Room Only tickets.

Follow on MiLB First Pitch  https //stza.co/+wjGm-3q

Shop  https //stza.co/+wjGm-3e

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Aces vs. Bees
END:VALARM
DTSTART:20180627T020500Z
DTEND:20180627T050500Z
UID:kCT-iYLvkt_1vfVkY8cKQrPh@stanza.co
SUMMARY:Aces vs. Bees
DESCRIPTION:Bring a friend for 2-for-$22 Tuesdays its 2 good to miss. For just $22 receive 2 hot dogs, 2 sodas and 2 Standing Room Only tickets.\n\nFollow on MiLB First Pitch: https://stza.co/+wjGm-3q\n\nShop: https://stza.co/+wjGm-3e\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:2-for-$22 Tuesdays
STATUS:CONFIRMED
CREATED:20180213T144553Z
LAST-MODIFIED:20180213T144553Z
TRANSP:OPAQUE
END:VEVENT
* Aces vs. Bees
<2018-06-27 Wed 21:05>--<2018-06-28 Thu 00:05>
:PROPERTIES:
:ID:       6iXLO0m48V2gBkflu2zrQt73@stanza.co
:LOCATION: Dog Days of Summer
:STATUS:   CONFIRMED
:END:

Aces vs. Bees Bring mans best friend to the ballyard every Wednesday home game! Enter via the Media Entrance along Kuenzli Street and bring proof of your pup's rabies vaccination. Human tickets are required for entrance.

Over 50 years old?! Receive BOGO tickets on any physical seating section with proof of ID at the Ticket Office.

Follow on MiLB First Pitch  https //stza.co/+wjGp-q

Shop  https //stza.co/+wjGp-2C

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Aces vs. Bees
END:VALARM
DTSTART:20180628T020500Z
DTEND:20180628T050500Z
UID:6iXLO0m48V2gBkflu2zrQt73@stanza.co
SUMMARY:Aces vs. Bees
DESCRIPTION:Bring mans best friend to the ballyard every Wednesday home game! Enter via the Media Entrance along Kuenzli Street and bring proof of your pup's rabies vaccination. Human tickets are required for entrance.\n\nOver 50 years old?! Receive BOGO tickets on any physical seating section with proof of ID at the Ticket Office.\n\nFollow on MiLB First Pitch: https://stza.co/+wjGp-q\n\nShop: https://stza.co/+wjGp-2C\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Dog Days of Summer
STATUS:CONFIRMED
CREATED:20180213T144553Z
LAST-MODIFIED:20180213T144553Z
TRANSP:OPAQUE
END:VEVENT
* Aces vs. Bees
<2018-06-28 Thu 21:05>--<2018-06-29 Fri 00:05>
:PROPERTIES:
:ID:       FglixXxJ4dWaq4mJNMhMskxU@stanza.co
:LOCATION: Coors Light Thirsty Thursdays
:STATUS:   CONFIRMED
:END:

Aces vs. Bees Come quench your thirst and enjoy a game with us on Thirsty Thursdays! Enjoy $2 pints of Coors Light until the middle of the 5th inning.

Follow on MiLB First Pitch  https //stza.co/+wjGs-I

Shop  https //stza.co/+wjGs-2

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Aces vs. Bees
END:VALARM
DTSTART:20180629T020500Z
DTEND:20180629T050500Z
UID:FglixXxJ4dWaq4mJNMhMskxU@stanza.co
SUMMARY:Aces vs. Bees
DESCRIPTION:Come quench your thirst and enjoy a game with us on Thirsty Thursdays! Enjoy $2 pints of Coors Light until the middle of the 5th inning.\n\nFollow on MiLB First Pitch: https://stza.co/+wjGs-I\n\nShop: https://stza.co/+wjGs-2\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Coors Light Thirsty Thursdays
STATUS:CONFIRMED
CREATED:20180213T144553Z
LAST-MODIFIED:20180213T144553Z
TRANSP:OPAQUE
END:VEVENT
* Aces @ Rainiers
<2018-06-29 Fri 21:05>--<2018-06-30 Sat 00:05>
:PROPERTIES:
:ID:       cT8cFSCNiyghac8_4pTnjVPi@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Aces @ Rainiers Aces @ Rainiers

Follow on MiLB First Pitch  https //stza.co/+wjHD-1u

Shop  https //stza.co/+wjHD-3e

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Aces @ Rainiers
END:VALARM
DTSTART:20180630T020500Z
DTEND:20180630T050500Z
UID:cT8cFSCNiyghac8_4pTnjVPi@stanza.co
SUMMARY:Aces @ Rainiers
DESCRIPTION:Aces @ Rainiers\n\nFollow on MiLB First Pitch: https://stza.co/+wjHD-1u\n\nShop: https://stza.co/+wjHD-3e\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144553Z
LAST-MODIFIED:20180213T144553Z
TRANSP:OPAQUE
END:VEVENT
* Aces @ Rainiers
<2018-06-30 Sat 19:05-22:05>
:PROPERTIES:
:ID:       _uT5lL9IG03RLDQDrZwwAaC1@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Aces @ Rainiers Aces @ Rainiers

Follow on MiLB First Pitch  https //stza.co/+wjHE-y

Shop  https //stza.co/+wjHE-3J

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Aces @ Rainiers
END:VALARM
DTSTART:20180701T000500Z
DTEND:20180701T030500Z
UID:_uT5lL9IG03RLDQDrZwwAaC1@stanza.co
SUMMARY:Aces @ Rainiers
DESCRIPTION:Aces @ Rainiers\n\nFollow on MiLB First Pitch: https://stza.co/+wjHE-y\n\nShop: https://stza.co/+wjHE-3J\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144553Z
LAST-MODIFIED:20180213T144553Z
TRANSP:OPAQUE
END:VEVENT
* Aces @ Rainiers
<2018-07-01 Sun 15:35-18:35>
:PROPERTIES:
:ID:       skFg7K0PFPHdL_kUqbAJV-6k@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Aces @ Rainiers Aces @ Rainiers

Follow on MiLB First Pitch  https //stza.co/+wjHF-2X

Shop  https //stza.co/+wjHF-2v

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Aces @ Rainiers
END:VALARM
DTSTART:20180701T203500Z
DTEND:20180701T233500Z
UID:skFg7K0PFPHdL_kUqbAJV-6k@stanza.co
SUMMARY:Aces @ Rainiers
DESCRIPTION:Aces @ Rainiers\n\nFollow on MiLB First Pitch: https://stza.co/+wjHF-2X\n\nShop: https://stza.co/+wjHF-2v\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144553Z
LAST-MODIFIED:20180213T144553Z
TRANSP:OPAQUE
END:VEVENT
* Aces @ Rainiers
<2018-07-02 Mon 21:05>--<2018-07-03 Tue 00:05>
:PROPERTIES:
:ID:       kXcFQs12-mJMHgcSj_eW9bxN@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Aces @ Rainiers Aces @ Rainiers

Follow on MiLB First Pitch  https //stza.co/+wjHG-1b

Shop  https //stza.co/+wjHG-3Q

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Aces @ Rainiers
END:VALARM
DTSTART:20180703T020500Z
DTEND:20180703T050500Z
UID:kXcFQs12-mJMHgcSj_eW9bxN@stanza.co
SUMMARY:Aces @ Rainiers
DESCRIPTION:Aces @ Rainiers\n\nFollow on MiLB First Pitch: https://stza.co/+wjHG-1b\n\nShop: https://stza.co/+wjHG-3Q\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144553Z
LAST-MODIFIED:20180213T144553Z
TRANSP:OPAQUE
END:VEVENT
* Aces @ Rainiers
<2018-07-03 Tue 21:05>--<2018-07-04 Wed 00:05>
:PROPERTIES:
:ID:       VPXP2Z8xh-ldF0HOE6jGXB99@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Aces @ Rainiers Aces @ Rainiers

Follow on MiLB First Pitch  https //stza.co/+wjHH-2t

Shop  https //stza.co/+wjHH-3G

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Aces @ Rainiers
END:VALARM
DTSTART:20180704T020500Z
DTEND:20180704T050500Z
UID:VPXP2Z8xh-ldF0HOE6jGXB99@stanza.co
SUMMARY:Aces @ Rainiers
DESCRIPTION:Aces @ Rainiers\n\nFollow on MiLB First Pitch: https://stza.co/+wjHH-2t\n\nShop: https://stza.co/+wjHH-3G\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144553Z
LAST-MODIFIED:20180213T144553Z
TRANSP:OPAQUE
END:VEVENT
* Aces vs. River Cats
<2018-07-04 Wed 20:35-23:35>
:PROPERTIES:
:ID:       T42YooHQZZwbZ4xQIXw9RUUL@stanza.co
:LOCATION: Atlantis Casino Resort Spa Independence Day Celebration
:STATUS:   CONFIRMED
:END:

Aces vs. River Cats Celebrate Independence Day in the most American way - baseball, followed by postgame fireworks! 

Don't miss the best fireworks shows in town! 

Follow on MiLB First Pitch  https //stza.co/+wjGt-1d

Shop  https //stza.co/+wjGt-2k

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Aces vs. River Cats
END:VALARM
DTSTART:20180705T013500Z
DTEND:20180705T043500Z
UID:T42YooHQZZwbZ4xQIXw9RUUL@stanza.co
SUMMARY:Aces vs. River Cats
DESCRIPTION:Celebrate Independence Day in the most American way - baseball, followed by postgame fireworks! \n\nDon't miss the best fireworks shows in town! \n\nFollow on MiLB First Pitch: https://stza.co/+wjGt-1d\n\nShop: https://stza.co/+wjGt-2k\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Atlantis Casino Resort Spa Independence Day Celebration
STATUS:CONFIRMED
CREATED:20180213T144553Z
LAST-MODIFIED:20180213T144553Z
TRANSP:OPAQUE
END:VEVENT
* Aces vs. River Cats
<2018-07-05 Thu 21:05>--<2018-07-06 Fri 00:05>
:PROPERTIES:
:ID:       nJ8PvcO7opwqKB9_k7pLnLUE@stanza.co
:LOCATION: Coors Light Thirsty Thursdays
:STATUS:   CONFIRMED
:END:

Aces vs. River Cats Come quench your thirst and enjoy a game with us on Thirsty Thursdays! Enjoy $2 pints of Coors Light until the middle of the 5th inning.

Follow on MiLB First Pitch  https //stza.co/+wjGv-1$

Shop  https //stza.co/+wjGv-2F

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Aces vs. River Cats
END:VALARM
DTSTART:20180706T020500Z
DTEND:20180706T050500Z
UID:nJ8PvcO7opwqKB9_k7pLnLUE@stanza.co
SUMMARY:Aces vs. River Cats
DESCRIPTION:Come quench your thirst and enjoy a game with us on Thirsty Thursdays! Enjoy $2 pints of Coors Light until the middle of the 5th inning.\n\nFollow on MiLB First Pitch: https://stza.co/+wjGv-1$\n\nShop: https://stza.co/+wjGv-2F\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Coors Light Thirsty Thursdays
STATUS:CONFIRMED
CREATED:20180213T144553Z
LAST-MODIFIED:20180213T144553Z
TRANSP:OPAQUE
END:VEVENT
* Aces vs. River Cats
<2018-07-06 Fri 21:05>--<2018-07-07 Sat 00:05>
:PROPERTIES:
:ID:       fScFMGdMrNn0rpwe6an47aw_@stanza.co
:LOCATION: Saint Mary's Fireworks Friday
:STATUS:   CONFIRMED
:END:

Aces vs. River Cats Come see our spectacular fireworks display! It's sure to light up the sky and your heart.

Follow on MiLB First Pitch  https //stza.co/+wjGy-3c

Shop  https //stza.co/+wjGy-1o

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Aces vs. River Cats
END:VALARM
DTSTART:20180707T020500Z
DTEND:20180707T050500Z
UID:fScFMGdMrNn0rpwe6an47aw_@stanza.co
SUMMARY:Aces vs. River Cats
DESCRIPTION:Come see our spectacular fireworks display! It's sure to light up the sky and your heart.\n\nFollow on MiLB First Pitch: https://stza.co/+wjGy-3c\n\nShop: https://stza.co/+wjGy-1o\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Saint Mary's Fireworks Friday
STATUS:CONFIRMED
CREATED:20180213T144553Z
LAST-MODIFIED:20180213T144553Z
TRANSP:OPAQUE
END:VEVENT
* Aces vs. River Cats
<2018-07-07 Sat 21:05>--<2018-07-08 Sun 00:05>
:PROPERTIES:
:ID:       w9yOBFy5rZthuEksW3LH6lIF@stanza.co
:LOCATION: Margaritaville Night
:STATUS:   CONFIRMED
:END:

Aces vs. River Cats 'If life gives you limes, make Margaritas.' We'll do just that. Purchase an enhanced ticket package and receive a Hawaiian shirt to mark the occasion. The Aces will be wearing special jerseys that will be auctioned to benefit a local charity. 

Follow on MiLB First Pitch  https //stza.co/+wjGz-2T

Shop  https //stza.co/+wjGz-3s

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Aces vs. River Cats
END:VALARM
DTSTART:20180708T020500Z
DTEND:20180708T050500Z
UID:w9yOBFy5rZthuEksW3LH6lIF@stanza.co
SUMMARY:Aces vs. River Cats
DESCRIPTION:'If life gives you limes, make Margaritas.' We'll do just that. Purchase an enhanced ticket package and receive a Hawaiian shirt to mark the occasion. The Aces will be wearing special jerseys that will be auctioned to benefit a local charity. \n\nFollow on MiLB First Pitch: https://stza.co/+wjGz-2T\n\nShop: https://stza.co/+wjGz-3s\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Margaritaville Night
STATUS:CONFIRMED
CREATED:20180213T144553Z
LAST-MODIFIED:20180213T144553Z
TRANSP:OPAQUE
END:VEVENT
* Aces vs. River Cats
<2018-07-08 Sun 15:05-18:05>
:PROPERTIES:
:ID:       bI6IMzk19DA3M-RPlh1-Mf_s@stanza.co
:LOCATION: Dollar Menu Sunday
:STATUS:   CONFIRMED
:END:

Aces vs. River Cats Come for the games, stay for the Dollar Menu Sundays!

Follow along with the ballgame by playing Baseball Bingo!

Follow on MiLB First Pitch  https //stza.co/+wjGC-3o

Shop  https //stza.co/+wjGC-3A

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Aces vs. River Cats
END:VALARM
DTSTART:20180708T200500Z
DTEND:20180708T230500Z
UID:bI6IMzk19DA3M-RPlh1-Mf_s@stanza.co
SUMMARY:Aces vs. River Cats
DESCRIPTION:Come for the games, stay for the Dollar Menu Sundays!\n\nFollow along with the ballgame by playing Baseball Bingo!\n\nFollow on MiLB First Pitch: https://stza.co/+wjGC-3o\n\nShop: https://stza.co/+wjGC-3A\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Dollar Menu Sunday
STATUS:CONFIRMED
CREATED:20180213T144553Z
LAST-MODIFIED:20180213T144553Z
TRANSP:OPAQUE
END:VEVENT
* Aces @ Chihuahuas
<2018-07-12 Thu 20:05-23:05>
:PROPERTIES:
:ID:       maCiHJL3QP7u8E_UfxjvfRWX@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Aces @ Chihuahuas Aces @ Chihuahuas

Follow on MiLB First Pitch  https //stza.co/+wmL8-3B

Shop  https //stza.co/+wmL8-3T

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Aces @ Chihuahuas
END:VALARM
DTSTART:20180713T010500Z
DTEND:20180713T040500Z
UID:maCiHJL3QP7u8E_UfxjvfRWX@stanza.co
SUMMARY:Aces @ Chihuahuas
DESCRIPTION:Aces @ Chihuahuas\n\nFollow on MiLB First Pitch: https://stza.co/+wmL8-3B\n\nShop: https://stza.co/+wmL8-3T\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144553Z
LAST-MODIFIED:20180213T144553Z
TRANSP:OPAQUE
END:VEVENT
* Aces @ Chihuahuas
<2018-07-13 Fri 20:05-23:05>
:PROPERTIES:
:ID:       tQ-chbFGni7hNQ0-GiBRmUv_@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Aces @ Chihuahuas Aces @ Chihuahuas

Follow on MiLB First Pitch  https //stza.co/+wmL9-1r

Shop  https //stza.co/+wmL9-2h

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Aces @ Chihuahuas
END:VALARM
DTSTART:20180714T010500Z
DTEND:20180714T040500Z
UID:tQ-chbFGni7hNQ0-GiBRmUv_@stanza.co
SUMMARY:Aces @ Chihuahuas
DESCRIPTION:Aces @ Chihuahuas\n\nFollow on MiLB First Pitch: https://stza.co/+wmL9-1r\n\nShop: https://stza.co/+wmL9-2h\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144553Z
LAST-MODIFIED:20180213T144553Z
TRANSP:OPAQUE
END:VEVENT
* Aces @ Chihuahuas
<2018-07-14 Sat 20:05-23:05>
:PROPERTIES:
:ID:       Lo5JNihFQm4EHqAaMCdWH97K@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Aces @ Chihuahuas Aces @ Chihuahuas

Follow on MiLB First Pitch  https //stza.co/+wmLa-2w

Shop  https //stza.co/+wmLa-2i

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Aces @ Chihuahuas
END:VALARM
DTSTART:20180715T010500Z
DTEND:20180715T040500Z
UID:Lo5JNihFQm4EHqAaMCdWH97K@stanza.co
SUMMARY:Aces @ Chihuahuas
DESCRIPTION:Aces @ Chihuahuas\n\nFollow on MiLB First Pitch: https://stza.co/+wmLa-2w\n\nShop: https://stza.co/+wmLa-2i\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144553Z
LAST-MODIFIED:20180213T144553Z
TRANSP:OPAQUE
END:VEVENT
* Aces @ Chihuahuas
<2018-07-15 Sun 19:05-22:05>
:PROPERTIES:
:ID:       -3yT3bptZx3bcAjNYOa7xEIj@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Aces @ Chihuahuas Aces @ Chihuahuas

Follow on MiLB First Pitch  https //stza.co/+wmLb-3q

Shop  https //stza.co/+wmLb-2g

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Aces @ Chihuahuas
END:VALARM
DTSTART:20180716T000500Z
DTEND:20180716T030500Z
UID:-3yT3bptZx3bcAjNYOa7xEIj@stanza.co
SUMMARY:Aces @ Chihuahuas
DESCRIPTION:Aces @ Chihuahuas\n\nFollow on MiLB First Pitch: https://stza.co/+wmLb-3q\n\nShop: https://stza.co/+wmLb-2g\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144553Z
LAST-MODIFIED:20180213T144553Z
TRANSP:OPAQUE
END:VEVENT
* Aces vs. Rainiers
<2018-07-16 Mon 21:05>--<2018-07-17 Tue 00:05>
:PROPERTIES:
:ID:       luJz9cS4f7tnOLPfPa-UQqYI@stanza.co
:LOCATION: Military Monday
:STATUS:   CONFIRMED
:END:

Aces vs. Rainiers Receive BOGO tickets on Infield Reserve, Right Field Reserve and Standing Room Only for all active and retired military personnel & first responders courtesy of Jones-West Ford.

Follow on MiLB First Pitch  https //stza.co/+wjGF-24

Shop  https //stza.co/+wjGF-3B

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Aces vs. Rainiers
END:VALARM
DTSTART:20180717T020500Z
DTEND:20180717T050500Z
UID:luJz9cS4f7tnOLPfPa-UQqYI@stanza.co
SUMMARY:Aces vs. Rainiers
DESCRIPTION:Receive BOGO tickets on Infield Reserve, Right Field Reserve and Standing Room Only for all active and retired military personnel & first responders courtesy of Jones-West Ford.\n\nFollow on MiLB First Pitch: https://stza.co/+wjGF-24\n\nShop: https://stza.co/+wjGF-3B\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Military Monday
STATUS:CONFIRMED
CREATED:20180213T144553Z
LAST-MODIFIED:20180213T144553Z
TRANSP:OPAQUE
END:VEVENT
* Aces vs. Rainiers
<2018-07-17 Tue 21:05>--<2018-07-18 Wed 00:05>
:PROPERTIES:
:ID:       UX11AiHyHWbR-NCBK-156Xmc@stanza.co
:LOCATION: 2-for-$22 Tuesdays
:STATUS:   CONFIRMED
:END:

Aces vs. Rainiers Bring a friend for 2-for-$22 Tuesdays its 2 good to miss. For just $22 receive 2 hot dogs, 2 sodas and 2 Standing Room Only tickets.

Follow on MiLB First Pitch  https //stza.co/+wjGG-2Z

Shop  https //stza.co/+wjGG-3s

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Aces vs. Rainiers
END:VALARM
DTSTART:20180718T020500Z
DTEND:20180718T050500Z
UID:UX11AiHyHWbR-NCBK-156Xmc@stanza.co
SUMMARY:Aces vs. Rainiers
DESCRIPTION:Bring a friend for 2-for-$22 Tuesdays its 2 good to miss. For just $22 receive 2 hot dogs, 2 sodas and 2 Standing Room Only tickets.\n\nFollow on MiLB First Pitch: https://stza.co/+wjGG-2Z\n\nShop: https://stza.co/+wjGG-3s\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:2-for-$22 Tuesdays
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Aces vs. Rainiers
<2018-07-18 Wed 21:05>--<2018-07-19 Thu 00:05>
:PROPERTIES:
:ID:       S56dR00uK0KWL_gd61Akq7BI@stanza.co
:LOCATION: Dog Days of Summer
:STATUS:   CONFIRMED
:END:

Aces vs. Rainiers Bring mans best friend to the ballyard every Wednesday home game! Enter via the Media Entrance along Kuenzli Street and bring proof of your pup's rabies vaccination. Human tickets are required for entrance.

Over 50 years old?! Receive BOGO tickets on any physical seating section with proof of ID at the Ticket Office.

Follow on MiLB First Pitch  https //stza.co/+wjGJ-3n

Shop  https //stza.co/+wjGJ-3m

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Aces vs. Rainiers
END:VALARM
DTSTART:20180719T020500Z
DTEND:20180719T050500Z
UID:S56dR00uK0KWL_gd61Akq7BI@stanza.co
SUMMARY:Aces vs. Rainiers
DESCRIPTION:Bring mans best friend to the ballyard every Wednesday home game! Enter via the Media Entrance along Kuenzli Street and bring proof of your pup's rabies vaccination. Human tickets are required for entrance.\n\nOver 50 years old?! Receive BOGO tickets on any physical seating section with proof of ID at the Ticket Office.\n\nFollow on MiLB First Pitch: https://stza.co/+wjGJ-3n\n\nShop: https://stza.co/+wjGJ-3m\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Dog Days of Summer
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Aces vs. Rainiers
<2018-07-19 Thu 21:05>--<2018-07-20 Fri 00:05>
:PROPERTIES:
:ID:       eGyddMg_8KwHGYeZn8MxTwFI@stanza.co
:LOCATION: Coors Light Thirsty Thursdays
:STATUS:   CONFIRMED
:END:

Aces vs. Rainiers Come quench your thirst and enjoy a game with us on Thirsty Thursdays! Enjoy $2 pints of Coors Light until the middle of the 5th inning.

Follow on MiLB First Pitch  https //stza.co/+wjGL-v

Shop  https //stza.co/+wjGL-2

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Aces vs. Rainiers
END:VALARM
DTSTART:20180720T020500Z
DTEND:20180720T050500Z
UID:eGyddMg_8KwHGYeZn8MxTwFI@stanza.co
SUMMARY:Aces vs. Rainiers
DESCRIPTION:Come quench your thirst and enjoy a game with us on Thirsty Thursdays! Enjoy $2 pints of Coors Light until the middle of the 5th inning.\n\nFollow on MiLB First Pitch: https://stza.co/+wjGL-v\n\nShop: https://stza.co/+wjGL-2\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Coors Light Thirsty Thursdays
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Aces vs. 51s
<2018-07-20 Fri 21:05>--<2018-07-21 Sat 00:05>
:PROPERTIES:
:ID:       bDouPeTMcyg-8Yby_q39avLS@stanza.co
:LOCATION: Artown Night
:STATUS:   CONFIRMED
:END:

Aces vs. 51s Artown Night captures the spirit of Reno - featuring art from local artists around Greater Nevada Field. After the game, we will mark the occasion with a firework spectacular presented by Saint Mary's 

Come see our spectacular fireworks display! It's sure to light up the sky and your heart.

Follow on MiLB First Pitch  https //stza.co/+wjGM-2X

Shop  https //stza.co/+wjGM-5

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Aces vs. 51s
END:VALARM
DTSTART:20180721T020500Z
DTEND:20180721T050500Z
UID:bDouPeTMcyg-8Yby_q39avLS@stanza.co
SUMMARY:Aces vs. 51s
DESCRIPTION:Artown Night captures the spirit of Reno - featuring art from local artists around Greater Nevada Field. After the game, we will mark the occasion with a firework spectacular presented by Saint Mary's \n\nCome see our spectacular fireworks display! It's sure to light up the sky and your heart.\n\nFollow on MiLB First Pitch: https://stza.co/+wjGM-2X\n\nShop: https://stza.co/+wjGM-5\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Artown Night
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Aces vs. 51s
<2018-07-21 Sat 21:05>--<2018-07-22 Sun 00:05>
:PROPERTIES:
:ID:       Bg_jyVexa7oWh0aW1begggMX@stanza.co
:LOCATION: Christmas in July
:STATUS:   CONFIRMED
:END:

Aces vs. 51s Santa is bringing his summer vacation to Reno! There will also be an Aces replica jersey giveaway presented by Dillard's and a toy donation drive benefiting local charity. 

Look like the Aces with this jersey giveaway presented by Dillard's! Available for the first 1,000 fans in attendance.

Follow on MiLB First Pitch  https //stza.co/+wjGO-1n

Shop  https //stza.co/+wjGO-1G

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Aces vs. 51s
END:VALARM
DTSTART:20180722T020500Z
DTEND:20180722T050500Z
UID:Bg_jyVexa7oWh0aW1begggMX@stanza.co
SUMMARY:Aces vs. 51s
DESCRIPTION:Santa is bringing his summer vacation to Reno! There will also be an Aces replica jersey giveaway presented by Dillard's and a toy donation drive benefiting local charity. \n\nLook like the Aces with this jersey giveaway presented by Dillard's! Available for the first 1,000 fans in attendance.\n\nFollow on MiLB First Pitch: https://stza.co/+wjGO-1n\n\nShop: https://stza.co/+wjGO-1G\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Christmas in July
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Aces vs. 51s
<2018-07-22 Sun 15:05-18:05>
:PROPERTIES:
:ID:       HxS5zFdKAbd5RLNXwvXZmSZp@stanza.co
:LOCATION: Dollar Menu Sunday
:STATUS:   CONFIRMED
:END:

Aces vs. 51s Come for the games, stay for the Dollar Menu Sundays!

Follow along with the ballgame by playing Baseball Bingo!

Follow on MiLB First Pitch  https //stza.co/+wjGQ-3a

Shop  https //stza.co/+wjGQ-29

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Aces vs. 51s
END:VALARM
DTSTART:20180722T200500Z
DTEND:20180722T230500Z
UID:HxS5zFdKAbd5RLNXwvXZmSZp@stanza.co
SUMMARY:Aces vs. 51s
DESCRIPTION:Come for the games, stay for the Dollar Menu Sundays!\n\nFollow along with the ballgame by playing Baseball Bingo!\n\nFollow on MiLB First Pitch: https://stza.co/+wjGQ-3a\n\nShop: https://stza.co/+wjGQ-29\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Dollar Menu Sunday
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Aces @ Baby Cakes
<2018-07-24 Tue 19:00-22:00>
:PROPERTIES:
:ID:       J6O_mDxHCHZ1qq9uFyzIGKUM@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Aces @ Baby Cakes Aces @ Baby Cakes

Follow on MiLB First Pitch  https //stza.co/+whPN-

Shop  https //stza.co/+whPN-L

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Aces @ Baby Cakes
END:VALARM
DTSTART:20180725T000000Z
DTEND:20180725T030000Z
UID:J6O_mDxHCHZ1qq9uFyzIGKUM@stanza.co
SUMMARY:Aces @ Baby Cakes
DESCRIPTION:Aces @ Baby Cakes\n\nFollow on MiLB First Pitch: https://stza.co/+whPN-\n\nShop: https://stza.co/+whPN-L\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Aces @ Baby Cakes
<2018-07-25 Wed 19:00-22:00>
:PROPERTIES:
:ID:       HefqP4BJmCoHjxkUB9L8Az8a@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Aces @ Baby Cakes Aces @ Baby Cakes

Follow on MiLB First Pitch  https //stza.co/+whPO-f

Shop  https //stza.co/+whPO-3_

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Aces @ Baby Cakes
END:VALARM
DTSTART:20180726T000000Z
DTEND:20180726T030000Z
UID:HefqP4BJmCoHjxkUB9L8Az8a@stanza.co
SUMMARY:Aces @ Baby Cakes
DESCRIPTION:Aces @ Baby Cakes\n\nFollow on MiLB First Pitch: https://stza.co/+whPO-f\n\nShop: https://stza.co/+whPO-3_\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Aces @ Baby Cakes
<2018-07-26 Thu 19:00-22:00>
:PROPERTIES:
:ID:       mj19PaElJzJ3c3PA2g8xzYW2@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Aces @ Baby Cakes Aces @ Baby Cakes

Follow on MiLB First Pitch  https //stza.co/+whPP-1M

Shop  https //stza.co/+whPP-17

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Aces @ Baby Cakes
END:VALARM
DTSTART:20180727T000000Z
DTEND:20180727T030000Z
UID:mj19PaElJzJ3c3PA2g8xzYW2@stanza.co
SUMMARY:Aces @ Baby Cakes
DESCRIPTION:Aces @ Baby Cakes\n\nFollow on MiLB First Pitch: https://stza.co/+whPP-1M\n\nShop: https://stza.co/+whPP-17\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Aces @ Express
<2018-07-27 Fri 19:05-22:05>
:PROPERTIES:
:ID:       fnxHMXIBpGuO5rVtTY4XjdwP@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Aces @ Express Aces @ Express

Follow on MiLB First Pitch  https //stza.co/+v4f0-3

Shop  https //stza.co/+v4f0-2F

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Aces @ Express
END:VALARM
DTSTART:20180728T000500Z
DTEND:20180728T030500Z
UID:fnxHMXIBpGuO5rVtTY4XjdwP@stanza.co
SUMMARY:Aces @ Express
DESCRIPTION:Aces @ Express\n\nFollow on MiLB First Pitch: https://stza.co/+v4f0-3\n\nShop: https://stza.co/+v4f0-2F\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Aces @ Express
<2018-07-28 Sat 19:05-22:05>
:PROPERTIES:
:ID:       1rPtvuaL18dFJCocKaLQIwqo@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Aces @ Express Aces @ Express

Follow on MiLB First Pitch  https //stza.co/+v4f1-1N

Shop  https //stza.co/+v4f1-23

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Aces @ Express
END:VALARM
DTSTART:20180729T000500Z
DTEND:20180729T030500Z
UID:1rPtvuaL18dFJCocKaLQIwqo@stanza.co
SUMMARY:Aces @ Express
DESCRIPTION:Aces @ Express\n\nFollow on MiLB First Pitch: https://stza.co/+v4f1-1N\n\nShop: https://stza.co/+v4f1-23\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Aces @ Express
<2018-07-29 Sun 18:05-21:05>
:PROPERTIES:
:ID:       L6C4u1s-QIY_sOOJhdaj4qBk@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Aces @ Express Aces @ Express

Follow on MiLB First Pitch  https //stza.co/+v4f2-38

Shop  https //stza.co/+v4f2-1m

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Aces @ Express
END:VALARM
DTSTART:20180729T230500Z
DTEND:20180730T020500Z
UID:L6C4u1s-QIY_sOOJhdaj4qBk@stanza.co
SUMMARY:Aces @ Express
DESCRIPTION:Aces @ Express\n\nFollow on MiLB First Pitch: https://stza.co/+v4f2-38\n\nShop: https://stza.co/+v4f2-1m\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Aces @ Express
<2018-07-30 Mon 19:05-22:05>
:PROPERTIES:
:ID:       qWCr7icb00BCzc2Nxb7nRzas@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Aces @ Express Aces @ Express

Follow on MiLB First Pitch  https //stza.co/+v4f3-2v

Shop  https //stza.co/+v4f3-2p

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Aces @ Express
END:VALARM
DTSTART:20180731T000500Z
DTEND:20180731T030500Z
UID:qWCr7icb00BCzc2Nxb7nRzas@stanza.co
SUMMARY:Aces @ Express
DESCRIPTION:Aces @ Express\n\nFollow on MiLB First Pitch: https://stza.co/+v4f3-2v\n\nShop: https://stza.co/+v4f3-2p\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Aces vs. Sky Sox
<2018-08-01 Wed 21:05>--<2018-08-02 Thu 00:05>
:PROPERTIES:
:ID:       92e52Oi_Loomg7w8ug2h_GBf@stanza.co
:LOCATION: Dog Days of Summer
:STATUS:   CONFIRMED
:END:

Aces vs. Sky Sox Bring mans best friend to the ballyard every Wednesday home game! Enter via the Media Entrance along Kuenzli Street and bring proof of your pup's rabies vaccination. Human tickets are required for entrance.

Over 50 years old?! Receive BOGO tickets on any physical seating section with proof of ID at the Ticket Office.

Follow on MiLB First Pitch  https //stza.co/+wjGU-2x

Shop  https //stza.co/+wjGU-1o

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Aces vs. Sky Sox
END:VALARM
DTSTART:20180802T020500Z
DTEND:20180802T050500Z
UID:92e52Oi_Loomg7w8ug2h_GBf@stanza.co
SUMMARY:Aces vs. Sky Sox
DESCRIPTION:Bring mans best friend to the ballyard every Wednesday home game! Enter via the Media Entrance along Kuenzli Street and bring proof of your pup's rabies vaccination. Human tickets are required for entrance.\n\nOver 50 years old?! Receive BOGO tickets on any physical seating section with proof of ID at the Ticket Office.\n\nFollow on MiLB First Pitch: https://stza.co/+wjGU-2x\n\nShop: https://stza.co/+wjGU-1o\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Dog Days of Summer
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Aces vs. Sky Sox
<2018-08-02 Thu 21:05>--<2018-08-03 Fri 00:05>
:PROPERTIES:
:ID:       H6aIQ2e_OfEWk8HcpOWGMHrY@stanza.co
:LOCATION: Coors Light Thirsty Thursdays
:STATUS:   CONFIRMED
:END:

Aces vs. Sky Sox Come quench your thirst and enjoy a game with us on Thirsty Thursdays! Enjoy $2 pints of Coors Light until the middle of the 5th inning.

Follow on MiLB First Pitch  https //stza.co/+wjGW-y

Shop  https //stza.co/+wjGW-w

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Aces vs. Sky Sox
END:VALARM
DTSTART:20180803T020500Z
DTEND:20180803T050500Z
UID:H6aIQ2e_OfEWk8HcpOWGMHrY@stanza.co
SUMMARY:Aces vs. Sky Sox
DESCRIPTION:Come quench your thirst and enjoy a game with us on Thirsty Thursdays! Enjoy $2 pints of Coors Light until the middle of the 5th inning.\n\nFollow on MiLB First Pitch: https://stza.co/+wjGW-y\n\nShop: https://stza.co/+wjGW-w\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Coors Light Thirsty Thursdays
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Aces vs. Sky Sox
<2018-08-03 Fri 21:05>--<2018-08-04 Sat 00:05>
:PROPERTIES:
:ID:       AEaG6uKI6qx_-HbamA33uJmI@stanza.co
:LOCATION: Wizarding World of the Reno Aces
:STATUS:   CONFIRMED
:END:

Aces vs. Sky Sox We solemnly sweat to be up to no good. Stay after the game on Friday for Saint Mary's Fireworks Friday presented by KRNV News 4. The Aces will be wearing custom jerseys that will be auctioned off to benefit charity! 

Come see our spectacular fireworks display! It's sure to light up the sky and your heart.

Follow on MiLB First Pitch  https //stza.co/+wjGX-2L

Shop  https //stza.co/+wjGX-1u

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Aces vs. Sky Sox
END:VALARM
DTSTART:20180804T020500Z
DTEND:20180804T050500Z
UID:AEaG6uKI6qx_-HbamA33uJmI@stanza.co
SUMMARY:Aces vs. Sky Sox
DESCRIPTION:We solemnly sweat to be up to no good. Stay after the game on Friday for Saint Mary's Fireworks Friday presented by KRNV News 4. The Aces will be wearing custom jerseys that will be auctioned off to benefit charity! \n\nCome see our spectacular fireworks display! It's sure to light up the sky and your heart.\n\nFollow on MiLB First Pitch: https://stza.co/+wjGX-2L\n\nShop: https://stza.co/+wjGX-1u\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Wizarding World of the Reno Aces
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Aces vs. Dodgers
<2018-08-04 Sat 21:05>--<2018-08-05 Sun 00:05>
:PROPERTIES:
:ID:       8K-dbl7ziR_3eWDlZa6MJ62b@stanza.co
:LOCATION: Wizarding World of the Reno Aces
:STATUS:   CONFIRMED
:END:

Aces vs. Dodgers We solemnly sweat to be up to no good. Stay after the game on Friday for Saint Mary's Fireworks Friday presented by KRNV News 4. The Aces will be wearing custom jerseys that will be auctioned off to benefit charity! 

Be one of the first 1,000 lucky fans to receive an Aces 10th season/Wizarding World lunchbox!

Follow on MiLB First Pitch  https //stza.co/+wjGZ-2l

Shop  https //stza.co/+wjGZ-31

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Aces vs. Dodgers
END:VALARM
DTSTART:20180805T020500Z
DTEND:20180805T050500Z
UID:8K-dbl7ziR_3eWDlZa6MJ62b@stanza.co
SUMMARY:Aces vs. Dodgers
DESCRIPTION:We solemnly sweat to be up to no good. Stay after the game on Friday for Saint Mary's Fireworks Friday presented by KRNV News 4. The Aces will be wearing custom jerseys that will be auctioned off to benefit charity! \n\nBe one of the first 1,000 lucky fans to receive an Aces 10th season/Wizarding World lunchbox!\n\nFollow on MiLB First Pitch: https://stza.co/+wjGZ-2l\n\nShop: https://stza.co/+wjGZ-31\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Wizarding World of the Reno Aces
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Aces vs. Dodgers
<2018-08-05 Sun 15:05-18:05>
:PROPERTIES:
:ID:       YP-MdSJcovSkEr4hcdGnB2nU@stanza.co
:LOCATION: Dollar Menu Sunday
:STATUS:   CONFIRMED
:END:

Aces vs. Dodgers Come for the games, stay for the Dollar Menu Sundays!

Follow along with the ballgame by playing Baseball Bingo!

Follow on MiLB First Pitch  https //stza.co/+wjH1-34

Shop  https //stza.co/+wjH1-1H

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Aces vs. Dodgers
END:VALARM
DTSTART:20180805T200500Z
DTEND:20180805T230500Z
UID:YP-MdSJcovSkEr4hcdGnB2nU@stanza.co
SUMMARY:Aces vs. Dodgers
DESCRIPTION:Come for the games, stay for the Dollar Menu Sundays!\n\nFollow along with the ballgame by playing Baseball Bingo!\n\nFollow on MiLB First Pitch: https://stza.co/+wjH1-34\n\nShop: https://stza.co/+wjH1-1H\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Dollar Menu Sunday
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Aces vs. Dodgers
<2018-08-06 Mon 21:05>--<2018-08-07 Tue 00:05>
:PROPERTIES:
:ID:       uqYAFEeOzRRayCXGW79O6lTu@stanza.co
:LOCATION: Military Monday
:STATUS:   CONFIRMED
:END:

Aces vs. Dodgers Receive BOGO tickets on Infield Reserve, Right Field Reserve and Standing Room Only for all active and retired military personnel & first responders courtesy of Jones-West Ford.

Follow on MiLB First Pitch  https //stza.co/+wjH3-3P

Shop  https //stza.co/+wjH3-o

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Aces vs. Dodgers
END:VALARM
DTSTART:20180807T020500Z
DTEND:20180807T050500Z
UID:uqYAFEeOzRRayCXGW79O6lTu@stanza.co
SUMMARY:Aces vs. Dodgers
DESCRIPTION:Receive BOGO tickets on Infield Reserve, Right Field Reserve and Standing Room Only for all active and retired military personnel & first responders courtesy of Jones-West Ford.\n\nFollow on MiLB First Pitch: https://stza.co/+wjH3-3P\n\nShop: https://stza.co/+wjH3-o\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Military Monday
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Aces vs. Dodgers
<2018-08-07 Tue 21:05>--<2018-08-08 Wed 00:05>
:PROPERTIES:
:ID:       sKOC3WLw-XmTuT-voQr5R9yz@stanza.co
:LOCATION: 2-for-$22 Tuesdays
:STATUS:   CONFIRMED
:END:

Aces vs. Dodgers Bring a friend for 2-for-$22 Tuesdays its 2 good to miss. For just $22 receive 2 hot dogs, 2 sodas and 2 Standing Room Only tickets.

Follow on MiLB First Pitch  https //stza.co/+wjH5-6

Shop  https //stza.co/+wjH5-1O

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Aces vs. Dodgers
END:VALARM
DTSTART:20180808T020500Z
DTEND:20180808T050500Z
UID:sKOC3WLw-XmTuT-voQr5R9yz@stanza.co
SUMMARY:Aces vs. Dodgers
DESCRIPTION:Bring a friend for 2-for-$22 Tuesdays its 2 good to miss. For just $22 receive 2 hot dogs, 2 sodas and 2 Standing Room Only tickets.\n\nFollow on MiLB First Pitch: https://stza.co/+wjH5-6\n\nShop: https://stza.co/+wjH5-1O\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:2-for-$22 Tuesdays
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Aces @ 51s
<2018-08-09 Thu 21:05>--<2018-08-10 Fri 00:05>
:PROPERTIES:
:ID:       KlsbmmV-2nNxw75ZUqe8NMR2@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Aces @ 51s Aces @ 51s

Follow on MiLB First Pitch  https //stza.co/+vKTG-U

Shop  https //stza.co/+vKTG-17

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Aces @ 51s
END:VALARM
DTSTART:20180810T020500Z
DTEND:20180810T050500Z
UID:KlsbmmV-2nNxw75ZUqe8NMR2@stanza.co
SUMMARY:Aces @ 51s
DESCRIPTION:Aces @ 51s\n\nFollow on MiLB First Pitch: https://stza.co/+vKTG-U\n\nShop: https://stza.co/+vKTG-17\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Aces @ 51s
<2018-08-10 Fri 21:05>--<2018-08-11 Sat 00:05>
:PROPERTIES:
:ID:       IxDyQkh6_IP0Hj89HVBxfde_@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Aces @ 51s Aces @ 51s

Follow on MiLB First Pitch  https //stza.co/+vKTH-A

Shop  https //stza.co/+vKTH-3W

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Aces @ 51s
END:VALARM
DTSTART:20180811T020500Z
DTEND:20180811T050500Z
UID:IxDyQkh6_IP0Hj89HVBxfde_@stanza.co
SUMMARY:Aces @ 51s
DESCRIPTION:Aces @ 51s\n\nFollow on MiLB First Pitch: https://stza.co/+vKTH-A\n\nShop: https://stza.co/+vKTH-3W\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Aces @ 51s
<2018-08-11 Sat 21:05>--<2018-08-12 Sun 00:05>
:PROPERTIES:
:ID:       gBVl1JNzJ-2lUnBOX8xqhYh7@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Aces @ 51s Aces @ 51s

Follow on MiLB First Pitch  https //stza.co/+vKTI-J

Shop  https //stza.co/+vKTI-32

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Aces @ 51s
END:VALARM
DTSTART:20180812T020500Z
DTEND:20180812T050500Z
UID:gBVl1JNzJ-2lUnBOX8xqhYh7@stanza.co
SUMMARY:Aces @ 51s
DESCRIPTION:Aces @ 51s\n\nFollow on MiLB First Pitch: https://stza.co/+vKTI-J\n\nShop: https://stza.co/+vKTI-32\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Aces @ 51s
<2018-08-12 Sun 21:05>--<2018-08-13 Mon 00:05>
:PROPERTIES:
:ID:       2gVPODYEzClWi_k0BsBCtZuL@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Aces @ 51s Aces @ 51s

Follow on MiLB First Pitch  https //stza.co/+vKTJ-1J

Shop  https //stza.co/+vKTJ-2e

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Aces @ 51s
END:VALARM
DTSTART:20180813T020500Z
DTEND:20180813T050500Z
UID:2gVPODYEzClWi_k0BsBCtZuL@stanza.co
SUMMARY:Aces @ 51s
DESCRIPTION:Aces @ 51s\n\nFollow on MiLB First Pitch: https://stza.co/+vKTJ-1J\n\nShop: https://stza.co/+vKTJ-2e\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Aces vs. River Cats
<2018-08-13 Mon 21:05>--<2018-08-14 Tue 00:05>
:PROPERTIES:
:ID:       1izQZElQs5leEJ2YK7LAsFr0@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Aces vs. River Cats Aces vs. River Cats

Follow on MiLB First Pitch  https //stza.co/+wjH7-35

Shop  https //stza.co/+wjH7-L

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Aces vs. River Cats
END:VALARM
DTSTART:20180814T020500Z
DTEND:20180814T050500Z
UID:1izQZElQs5leEJ2YK7LAsFr0@stanza.co
SUMMARY:Aces vs. River Cats
DESCRIPTION:Aces vs. River Cats\n\nFollow on MiLB First Pitch: https://stza.co/+wjH7-35\n\nShop: https://stza.co/+wjH7-L\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Aces vs. River Cats
<2018-08-14 Tue 21:05>--<2018-08-15 Wed 00:05>
:PROPERTIES:
:ID:       66OO1rVELXjdVgacQYu82wl8@stanza.co
:LOCATION: 2-for-$22 Tuesdays
:STATUS:   CONFIRMED
:END:

Aces vs. River Cats Bring a friend for 2-for-$22 Tuesdays its 2 good to miss. For just $22 receive 2 hot dogs, 2 sodas and 2 Standing Room Only tickets.

Follow on MiLB First Pitch  https //stza.co/+wjH9-1S

Shop  https //stza.co/+wjH9-3_

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Aces vs. River Cats
END:VALARM
DTSTART:20180815T020500Z
DTEND:20180815T050500Z
UID:66OO1rVELXjdVgacQYu82wl8@stanza.co
SUMMARY:Aces vs. River Cats
DESCRIPTION:Bring a friend for 2-for-$22 Tuesdays its 2 good to miss. For just $22 receive 2 hot dogs, 2 sodas and 2 Standing Room Only tickets.\n\nFollow on MiLB First Pitch: https://stza.co/+wjH9-1S\n\nShop: https://stza.co/+wjH9-3_\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:2-for-$22 Tuesdays
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Aces vs. River Cats
<2018-08-15 Wed 21:05>--<2018-08-16 Thu 00:05>
:PROPERTIES:
:ID:       2Y68WJoU607Ik2bVXDzGiGvi@stanza.co
:LOCATION: Dog Days of Summer
:STATUS:   CONFIRMED
:END:

Aces vs. River Cats Bring mans best friend to the ballyard every Wednesday home game! Enter via the Media Entrance along Kuenzli Street and bring proof of your pup's rabies vaccination. Human tickets are required for entrance.

Over 50 years old?! Receive BOGO tickets on any physical seating section with proof of ID at the Ticket Office.

Follow on MiLB First Pitch  https //stza.co/+wjHb-17

Shop  https //stza.co/+wjHb-31

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Aces vs. River Cats
END:VALARM
DTSTART:20180816T020500Z
DTEND:20180816T050500Z
UID:2Y68WJoU607Ik2bVXDzGiGvi@stanza.co
SUMMARY:Aces vs. River Cats
DESCRIPTION:Bring mans best friend to the ballyard every Wednesday home game! Enter via the Media Entrance along Kuenzli Street and bring proof of your pup's rabies vaccination. Human tickets are required for entrance.\n\nOver 50 years old?! Receive BOGO tickets on any physical seating section with proof of ID at the Ticket Office.\n\nFollow on MiLB First Pitch: https://stza.co/+wjHb-17\n\nShop: https://stza.co/+wjHb-31\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Dog Days of Summer
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Aces vs. Bees
<2018-08-16 Thu 21:05>--<2018-08-17 Fri 00:05>
:PROPERTIES:
:ID:       2Fy3R9GvZhgSrxsn_0vc_OjC@stanza.co
:LOCATION: Coors Light Thirsty Thursdays
:STATUS:   CONFIRMED
:END:

Aces vs. Bees Come quench your thirst and enjoy a game with us on Thirsty Thursdays! Enjoy $2 pints of Coors Light until the middle of the 5th inning.

Follow on MiLB First Pitch  https //stza.co/+wjHc-1R

Shop  https //stza.co/+wjHc-d

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Aces vs. Bees
END:VALARM
DTSTART:20180817T020500Z
DTEND:20180817T050500Z
UID:2Fy3R9GvZhgSrxsn_0vc_OjC@stanza.co
SUMMARY:Aces vs. Bees
DESCRIPTION:Come quench your thirst and enjoy a game with us on Thirsty Thursdays! Enjoy $2 pints of Coors Light until the middle of the 5th inning.\n\nFollow on MiLB First Pitch: https://stza.co/+wjHc-1R\n\nShop: https://stza.co/+wjHc-d\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Coors Light Thirsty Thursdays
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Aces vs. Bees
<2018-08-17 Fri 21:05>--<2018-08-18 Sat 00:05>
:PROPERTIES:
:ID:       uYBdAGBel2mgjWCUXikr1PAI@stanza.co
:LOCATION: Saint Mary's Fireworks Friday
:STATUS:   CONFIRMED
:END:

Aces vs. Bees Come see our spectacular fireworks display! It's sure to light up the sky and your heart.



Follow on MiLB First Pitch  https //stza.co/+wjHf-1i

Shop  https //stza.co/+wjHf-19

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Aces vs. Bees
END:VALARM
DTSTART:20180818T020500Z
DTEND:20180818T050500Z
UID:uYBdAGBel2mgjWCUXikr1PAI@stanza.co
SUMMARY:Aces vs. Bees
DESCRIPTION:Come see our spectacular fireworks display! It's sure to light up the sky and your heart.\n\n\n\nFollow on MiLB First Pitch: https://stza.co/+wjHf-1i\n\nShop: https://stza.co/+wjHf-19\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Saint Mary's Fireworks Friday
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Aces vs. Bees
<2018-08-18 Sat 21:05>--<2018-08-19 Sun 00:05>
:PROPERTIES:
:ID:       Ui8-PYM_C6lA1Q1qIkAY73sH@stanza.co
:LOCATION: Tribute to Johnny Cash Night
:STATUS:   CONFIRMED
:END:

Aces vs. Bees 'As sure as night is dark and day is light', you're going to want to be here for this night. We will be wearing specially designed jerseys that will be auction for charity! 

Follow on MiLB First Pitch  https //stza.co/+wjHg-2d

Shop  https //stza.co/+wjHg-1M

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Aces vs. Bees
END:VALARM
DTSTART:20180819T020500Z
DTEND:20180819T050500Z
UID:Ui8-PYM_C6lA1Q1qIkAY73sH@stanza.co
SUMMARY:Aces vs. Bees
DESCRIPTION:'As sure as night is dark and day is light', you're going to want to be here for this night. We will be wearing specially designed jerseys that will be auction for charity! \n\nFollow on MiLB First Pitch: https://stza.co/+wjHg-2d\n\nShop: https://stza.co/+wjHg-1M\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Tribute to Johnny Cash Night
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Aces vs. Bees
<2018-08-19 Sun 15:05-18:05>
:PROPERTIES:
:ID:       vS6KELvHIv16m8mMISCF8AyN@stanza.co
:LOCATION: Dollar Menu Sunday
:STATUS:   CONFIRMED
:END:

Aces vs. Bees Come for the games, stay for the Dollar Menu Sundays!

Follow along with the ballgame by playing Baseball Bingo!

Follow on MiLB First Pitch  https //stza.co/+wjHi-2d

Shop  https //stza.co/+wjHi-3P

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Aces vs. Bees
END:VALARM
DTSTART:20180819T200500Z
DTEND:20180819T230500Z
UID:vS6KELvHIv16m8mMISCF8AyN@stanza.co
SUMMARY:Aces vs. Bees
DESCRIPTION:Come for the games, stay for the Dollar Menu Sundays!\n\nFollow along with the ballgame by playing Baseball Bingo!\n\nFollow on MiLB First Pitch: https://stza.co/+wjHi-2d\n\nShop: https://stza.co/+wjHi-3P\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Dollar Menu Sunday
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Aces @ Rainiers
<2018-08-21 Tue 21:05>--<2018-08-22 Wed 00:05>
:PROPERTIES:
:ID:       E_pzkhjd6DYW3OsXmB1Y8Zs2@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Aces @ Rainiers Aces @ Rainiers

Follow on MiLB First Pitch  https //stza.co/+wjHI-3s

Shop  https //stza.co/+wjHI-3T

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Aces @ Rainiers
END:VALARM
DTSTART:20180822T020500Z
DTEND:20180822T050500Z
UID:E_pzkhjd6DYW3OsXmB1Y8Zs2@stanza.co
SUMMARY:Aces @ Rainiers
DESCRIPTION:Aces @ Rainiers\n\nFollow on MiLB First Pitch: https://stza.co/+wjHI-3s\n\nShop: https://stza.co/+wjHI-3T\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Aces @ Rainiers
<2018-08-22 Wed 21:05>--<2018-08-23 Thu 00:05>
:PROPERTIES:
:ID:       seRUTDBsmIQ_f9phAJOrDWfk@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Aces @ Rainiers Aces @ Rainiers

Follow on MiLB First Pitch  https //stza.co/+wjHJ-3X

Shop  https //stza.co/+wjHJ-l

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Aces @ Rainiers
END:VALARM
DTSTART:20180823T020500Z
DTEND:20180823T050500Z
UID:seRUTDBsmIQ_f9phAJOrDWfk@stanza.co
SUMMARY:Aces @ Rainiers
DESCRIPTION:Aces @ Rainiers\n\nFollow on MiLB First Pitch: https://stza.co/+wjHJ-3X\n\nShop: https://stza.co/+wjHJ-l\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Aces @ Rainiers
<2018-08-23 Thu 21:05>--<2018-08-24 Fri 00:05>
:PROPERTIES:
:ID:       761wK9F1m396Ynm7anCVICk6@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Aces @ Rainiers Aces @ Rainiers

Follow on MiLB First Pitch  https //stza.co/+wjHK-Y

Shop  https //stza.co/+wjHK-2w

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Aces @ Rainiers
END:VALARM
DTSTART:20180824T020500Z
DTEND:20180824T050500Z
UID:761wK9F1m396Ynm7anCVICk6@stanza.co
SUMMARY:Aces @ Rainiers
DESCRIPTION:Aces @ Rainiers\n\nFollow on MiLB First Pitch: https://stza.co/+wjHK-Y\n\nShop: https://stza.co/+wjHK-2w\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Aces @ Isotopes
<2018-08-24 Fri 19:35-22:35>
:PROPERTIES:
:ID:       mlJ0eJZDHq9sFpwVouYguFFn@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Aces @ Isotopes Aces @ Isotopes

Follow on MiLB First Pitch  https //stza.co/+whPD-1o

Shop  https //stza.co/+whPD-3J

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Aces @ Isotopes
END:VALARM
DTSTART:20180825T003500Z
DTEND:20180825T033500Z
UID:mlJ0eJZDHq9sFpwVouYguFFn@stanza.co
SUMMARY:Aces @ Isotopes
DESCRIPTION:Aces @ Isotopes\n\nFollow on MiLB First Pitch: https://stza.co/+whPD-1o\n\nShop: https://stza.co/+whPD-3J\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Aces @ Isotopes
<2018-08-25 Sat 19:35-22:35>
:PROPERTIES:
:ID:       Y4vFy0xhULGEWFCU2F5X6Qug@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Aces @ Isotopes Aces @ Isotopes

Follow on MiLB First Pitch  https //stza.co/+whPF-3c

Shop  https //stza.co/+whPF-G

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Aces @ Isotopes
END:VALARM
DTSTART:20180826T003500Z
DTEND:20180826T033500Z
UID:Y4vFy0xhULGEWFCU2F5X6Qug@stanza.co
SUMMARY:Aces @ Isotopes
DESCRIPTION:Aces @ Isotopes\n\nFollow on MiLB First Pitch: https://stza.co/+whPF-3c\n\nShop: https://stza.co/+whPF-G\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Aces @ Isotopes
<2018-08-26 Sun 19:05-22:05>
:PROPERTIES:
:ID:       VheYD7d7RBXflx3Dc0cu1BV9@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Aces @ Isotopes Aces @ Isotopes

Follow on MiLB First Pitch  https //stza.co/+whPH-I

Shop  https //stza.co/+whPH-2I

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Aces @ Isotopes
END:VALARM
DTSTART:20180827T000500Z
DTEND:20180827T030500Z
UID:VheYD7d7RBXflx3Dc0cu1BV9@stanza.co
SUMMARY:Aces @ Isotopes
DESCRIPTION:Aces @ Isotopes\n\nFollow on MiLB First Pitch: https://stza.co/+whPH-I\n\nShop: https://stza.co/+whPH-2I\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Aces @ Isotopes
<2018-08-27 Mon 19:35-22:35>
:PROPERTIES:
:ID:       UUzN8h-sMTeIZqNn09zgNKv6@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Aces @ Isotopes Aces @ Isotopes

Follow on MiLB First Pitch  https //stza.co/+whPI-a

Shop  https //stza.co/+whPI-1L

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Aces @ Isotopes
END:VALARM
DTSTART:20180828T003500Z
DTEND:20180828T033500Z
UID:UUzN8h-sMTeIZqNn09zgNKv6@stanza.co
SUMMARY:Aces @ Isotopes
DESCRIPTION:Aces @ Isotopes\n\nFollow on MiLB First Pitch: https://stza.co/+whPI-a\n\nShop: https://stza.co/+whPI-1L\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Aces @ Bees
<2018-08-28 Tue 20:05-23:05>
:PROPERTIES:
:ID:       7yCOr-hrhJdmtCr8Qk7G8716@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Aces @ Bees Aces @ Bees

Follow on MiLB First Pitch  https //stza.co/+wmLm-9

Shop  https //stza.co/+wmLm-2Z

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Aces @ Bees
END:VALARM
DTSTART:20180829T010500Z
DTEND:20180829T040500Z
UID:7yCOr-hrhJdmtCr8Qk7G8716@stanza.co
SUMMARY:Aces @ Bees
DESCRIPTION:Aces @ Bees\n\nFollow on MiLB First Pitch: https://stza.co/+wmLm-9\n\nShop: https://stza.co/+wmLm-2Z\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Aces @ Bees
<2018-08-29 Wed 20:05-23:05>
:PROPERTIES:
:ID:       NPCLoD3j88tHlj5zAxbasEHq@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Aces @ Bees Aces @ Bees

Follow on MiLB First Pitch  https //stza.co/+wmLn-3T

Shop  https //stza.co/+wmLn-1Y

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Aces @ Bees
END:VALARM
DTSTART:20180830T010500Z
DTEND:20180830T040500Z
UID:NPCLoD3j88tHlj5zAxbasEHq@stanza.co
SUMMARY:Aces @ Bees
DESCRIPTION:Aces @ Bees\n\nFollow on MiLB First Pitch: https://stza.co/+wmLn-3T\n\nShop: https://stza.co/+wmLn-1Y\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Aces @ Bees
<2018-08-30 Thu 20:05-23:05>
:PROPERTIES:
:ID:       J98Mj1nc1Vnv-lSRN0GtEafX@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Aces @ Bees Aces @ Bees

Follow on MiLB First Pitch  https //stza.co/+wmLo-3a

Shop  https //stza.co/+wmLo-2E

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Aces @ Bees
END:VALARM
DTSTART:20180831T010500Z
DTEND:20180831T040500Z
UID:J98Mj1nc1Vnv-lSRN0GtEafX@stanza.co
SUMMARY:Aces @ Bees
DESCRIPTION:Aces @ Bees\n\nFollow on MiLB First Pitch: https://stza.co/+wmLo-3a\n\nShop: https://stza.co/+wmLo-2E\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Aces vs. Isotopes
<2018-08-31 Fri 21:05>--<2018-09-01 Sat 00:05>
:PROPERTIES:
:ID:       wIzg0otuY4XaFLlF7vWeUcDp@stanza.co
:LOCATION: Fan Appreciation Weekend
:STATUS:   CONFIRMED
:END:

Aces vs. Isotopes Come on down to Greater Nevada Field for our last homestand as we dedicate it to our fans! Friday will have postgame Saint Mary's Fireworks, presented by KRNV News 4. Saturday's game will feature a 10th Celebration Bobblehead giveaway, followed by Sunday's Dollar Menu options and Baseball Bingo! On Monday, we close out the season with a Military Monday, courtesy of Jones-West Ford.

Come see our spectacular fireworks display! It's sure to light up the sky and your heart.

Follow on MiLB First Pitch  https //stza.co/+wjHk-2T

Shop  https //stza.co/+wjHk-2b

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Aces vs. Isotopes
END:VALARM
DTSTART:20180901T020500Z
DTEND:20180901T050500Z
UID:wIzg0otuY4XaFLlF7vWeUcDp@stanza.co
SUMMARY:Aces vs. Isotopes
DESCRIPTION:Come on down to Greater Nevada Field for our last homestand as we dedicate it to our fans! Friday will have postgame Saint Mary's Fireworks, presented by KRNV News 4. Saturday's game will feature a 10th Celebration Bobblehead giveaway, followed by Sunday's Dollar Menu options and Baseball Bingo! On Monday, we close out the season with a Military Monday, courtesy of Jones-West Ford.\n\nCome see our spectacular fireworks display! It's sure to light up the sky and your heart.\n\nFollow on MiLB First Pitch: https://stza.co/+wjHk-2T\n\nShop: https://stza.co/+wjHk-2b\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Fan Appreciation Weekend
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Aces vs. Isotopes
<2018-09-01 Sat 21:05>--<2018-09-02 Sun 00:05>
:PROPERTIES:
:ID:       y0IPCtYmVM1sSgcrn0gHTdGe@stanza.co
:LOCATION: Fan Appreciation Weekend
:STATUS:   CONFIRMED
:END:

Aces vs. Isotopes Come on down to Greater Nevada Field for our last homestand as we dedicate it to our fans! Friday will have postgame Saint Mary's Fireworks, presented by KRNV News 4. Saturday's game will feature a 10th Celebration Bobblehead giveaway, followed by Sunday's Dollar Menu options and Baseball Bingo! On Monday, we close out the season with a Military Monday, courtesy of Jones-West Ford.

Be one of the first 1,000 lucky fans to receive an Aces 10th season bobblehead!

Don't miss the best fireworks shows in town! 

Follow on MiLB First Pitch  https //stza.co/+wjHn-g

Shop  https //stza.co/+wjHn-$

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Aces vs. Isotopes
END:VALARM
DTSTART:20180902T020500Z
DTEND:20180902T050500Z
UID:y0IPCtYmVM1sSgcrn0gHTdGe@stanza.co
SUMMARY:Aces vs. Isotopes
DESCRIPTION:Come on down to Greater Nevada Field for our last homestand as we dedicate it to our fans! Friday will have postgame Saint Mary's Fireworks, presented by KRNV News 4. Saturday's game will feature a 10th Celebration Bobblehead giveaway, followed by Sunday's Dollar Menu options and Baseball Bingo! On Monday, we close out the season with a Military Monday, courtesy of Jones-West Ford.\n\nBe one of the first 1,000 lucky fans to receive an Aces 10th season bobblehead!\n\nDon't miss the best fireworks shows in town! \n\nFollow on MiLB First Pitch: https://stza.co/+wjHn-g\n\nShop: https://stza.co/+wjHn-$\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Fan Appreciation Weekend
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Aces vs. Isotopes
<2018-09-02 Sun 20:05-23:05>
:PROPERTIES:
:ID:       8nhPDQ-rchuKRpp6Fhjmfszi@stanza.co
:LOCATION: Fan Appreciation Weekend
:STATUS:   CONFIRMED
:END:

Aces vs. Isotopes Come on down to Greater Nevada Field for our last homestand as we dedicate it to our fans! Friday will have postgame Saint Mary's Fireworks, presented by KRNV News 4. Saturday's game will feature a 10th Celebration Bobblehead giveaway, followed by Sunday's Dollar Menu options and Baseball Bingo! On Monday, we close out the season with a Military Monday, courtesy of Jones-West Ford.

Come for the games, stay for the Dollar Menu Sundays!

Don't miss the best fireworks shows in town! 

Follow along with the ballgame by playing Baseball Bingo!

Follow on MiLB First Pitch  https //stza.co/+wjHp-3w

Shop  https //stza.co/+wjHp-K

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Aces vs. Isotopes
END:VALARM
DTSTART:20180903T010500Z
DTEND:20180903T040500Z
UID:8nhPDQ-rchuKRpp6Fhjmfszi@stanza.co
SUMMARY:Aces vs. Isotopes
DESCRIPTION:Come on down to Greater Nevada Field for our last homestand as we dedicate it to our fans! Friday will have postgame Saint Mary's Fireworks, presented by KRNV News 4. Saturday's game will feature a 10th Celebration Bobblehead giveaway, followed by Sunday's Dollar Menu options and Baseball Bingo! On Monday, we close out the season with a Military Monday, courtesy of Jones-West Ford.\n\nCome for the games, stay for the Dollar Menu Sundays!\n\nDon't miss the best fireworks shows in town! \n\nFollow along with the ballgame by playing Baseball Bingo!\n\nFollow on MiLB First Pitch: https://stza.co/+wjHp-3w\n\nShop: https://stza.co/+wjHp-K\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Fan Appreciation Weekend
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Aces vs. Isotopes
<2018-09-03 Mon 15:05-18:05>
:PROPERTIES:
:ID:       lNYx2YHsbQ0hWZ0zxewbsUFl@stanza.co
:LOCATION: Fan Appreciation Weekend
:STATUS:   CONFIRMED
:END:

Aces vs. Isotopes Come on down to Greater Nevada Field for our last homestand as we dedicate it to our fans! Friday will have postgame Saint Mary's Fireworks, presented by KRNV News 4. Saturday's game will feature a 10th Celebration Bobblehead giveaway, followed by Sunday's Dollar Menu options and Baseball Bingo! On Monday, we close out the season with a Military Monday, courtesy of Jones-West Ford.

Receive BOGO tickets on Infield Reserve, Right Field Reserve and Standing Room Only for all active and retired military personnel & first responders courtesy of Jones-West Ford.

Follow on MiLB First Pitch  https //stza.co/+wjHq-2b

Shop  https //stza.co/+wjHq-1Q

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Aces vs. Isotopes
END:VALARM
DTSTART:20180903T200500Z
DTEND:20180903T230500Z
UID:lNYx2YHsbQ0hWZ0zxewbsUFl@stanza.co
SUMMARY:Aces vs. Isotopes
DESCRIPTION:Come on down to Greater Nevada Field for our last homestand as we dedicate it to our fans! Friday will have postgame Saint Mary's Fireworks, presented by KRNV News 4. Saturday's game will feature a 10th Celebration Bobblehead giveaway, followed by Sunday's Dollar Menu options and Baseball Bingo! On Monday, we close out the season with a Military Monday, courtesy of Jones-West Ford.\n\nReceive BOGO tickets on Infield Reserve, Right Field Reserve and Standing Room Only for all active and retired military personnel & first responders courtesy of Jones-West Ford.\n\nFollow on MiLB First Pitch: https://stza.co/+wjHq-2b\n\nShop: https://stza.co/+wjHq-1Q\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Fan Appreciation Weekend
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
