#+TITLE:       Main Google calendar entries
#+AUTHOR:      Eric S Fraga
#+EMAIL:       e.fraga@ucl.ac.uk
#+DESCRIPTION: converted using the ical2org awk script
#+CATEGORY:    google
#+STARTUP:     hidestars
#+STARTUP:     overview

* COMMENT original iCal preamble

* Thunder vs. Flying Squirrels
<2018-04-05 Thu 18:00-21:00>
:PROPERTIES:
:ID:       KE59sEU2giwGtcaic6mmkqWD@stanza.co
:LOCATION: 25th Season Baseball Card Set
:STATUS:   CONFIRMED
:END:

Thunder vs. Flying Squirrels Take home a special 25th anniversary baseball card set with some of the best players in franchise history included. 

Follow on MiLB First Pitch  https //stza.co/+vbJn-1w

Shop  https //stza.co/+vbJn-t

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Thunder vs. Flying Squirrels
END:VALARM
DTSTART:20180405T230000Z
DTEND:20180406T020000Z
UID:KE59sEU2giwGtcaic6mmkqWD@stanza.co
SUMMARY:Thunder vs. Flying Squirrels
DESCRIPTION:Take home a special 25th anniversary baseball card set with some of the best players in franchise history included. \n\nFollow on MiLB First Pitch: https://stza.co/+vbJn-1w\n\nShop: https://stza.co/+vbJn-t\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:25th Season Baseball Card Set
STATUS:CONFIRMED
CREATED:20180213T144602Z
LAST-MODIFIED:20180213T144602Z
TRANSP:OPAQUE
END:VEVENT
* Thunder vs. Flying Squirrels
<2018-04-06 Fri 18:00-21:00>
:PROPERTIES:
:ID:       PtbsoC2RCQI-8olZUyEpKWvD@stanza.co
:LOCATION: Magnetic Schedule Giveaway
:STATUS:   CONFIRMED
:END:

Thunder vs. Flying Squirrels Don't miss a game all season with our Magnetic Schedule Giveaway!

Follow on MiLB First Pitch  https //stza.co/+vbJw-3x

Shop  https //stza.co/+vbJw-3q

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Thunder vs. Flying Squirrels
END:VALARM
DTSTART:20180406T230000Z
DTEND:20180407T020000Z
UID:PtbsoC2RCQI-8olZUyEpKWvD@stanza.co
SUMMARY:Thunder vs. Flying Squirrels
DESCRIPTION:Don't miss a game all season with our Magnetic Schedule Giveaway!\n\nFollow on MiLB First Pitch: https://stza.co/+vbJw-3x\n\nShop: https://stza.co/+vbJw-3q\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Magnetic Schedule Giveaway
STATUS:CONFIRMED
CREATED:20180213T144602Z
LAST-MODIFIED:20180213T144602Z
TRANSP:OPAQUE
END:VEVENT
* Thunder vs. Flying Squirrels
<2018-04-07 Sat 12:00-15:00>
:PROPERTIES:
:ID:       yvZpT_pxhaZBoln0mybxuNEh@stanza.co
:LOCATION: Aaron Judge Youth T-Shirt
:STATUS:   CONFIRMED
:END:

Thunder vs. Flying Squirrels Celebrate the 2017 AL Rookie of the Year with an Aaron Judge Youth T-shirt for the first 1,025 fans ages 5-13!

Follow on MiLB First Pitch  https //stza.co/+vbJG-3b

Shop  https //stza.co/+vbJG-Z

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Thunder vs. Flying Squirrels
END:VALARM
DTSTART:20180407T170000Z
DTEND:20180407T200000Z
UID:yvZpT_pxhaZBoln0mybxuNEh@stanza.co
SUMMARY:Thunder vs. Flying Squirrels
DESCRIPTION:Celebrate the 2017 AL Rookie of the Year with an Aaron Judge Youth T-shirt for the first 1,025 fans ages 5-13!\n\nFollow on MiLB First Pitch: https://stza.co/+vbJG-3b\n\nShop: https://stza.co/+vbJG-Z\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Aaron Judge Youth T-Shirt
STATUS:CONFIRMED
CREATED:20180213T144602Z
LAST-MODIFIED:20180213T144602Z
TRANSP:OPAQUE
END:VEVENT
* Thunder vs. Flying Squirrels
<2018-04-08 Sun 12:00-15:00>
:PROPERTIES:
:ID:       us7Zbv5Bv8OemB7uMxN2pMDj@stanza.co
:LOCATION: Kids Pennant
:STATUS:   CONFIRMED
:END:

Thunder vs. Flying Squirrels Show your Thunder pride with a Kids Pennant for the first 1,025 ages 5-13! 

Follow on MiLB First Pitch  https //stza.co/+vbJW-9

Shop  https //stza.co/+vbJW-19

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Thunder vs. Flying Squirrels
END:VALARM
DTSTART:20180408T170000Z
DTEND:20180408T200000Z
UID:us7Zbv5Bv8OemB7uMxN2pMDj@stanza.co
SUMMARY:Thunder vs. Flying Squirrels
DESCRIPTION:Show your Thunder pride with a Kids Pennant for the first 1,025 ages 5-13! \n\nFollow on MiLB First Pitch: https://stza.co/+vbJW-9\n\nShop: https://stza.co/+vbJW-19\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Kids Pennant
STATUS:CONFIRMED
CREATED:20180213T144602Z
LAST-MODIFIED:20180213T144602Z
TRANSP:OPAQUE
END:VEVENT
* Thunder vs. Fisher Cats
<2018-04-09 Mon 18:00-21:00>
:PROPERTIES:
:ID:       yrxk4pWggpTMIQCOll_Q01RX@stanza.co
:LOCATION: Magnetic Schedule Giveaway
:STATUS:   CONFIRMED
:END:

Thunder vs. Fisher Cats Don't miss a game all season with our Magnetic Schedule Giveaway!

Follow on MiLB First Pitch  https //stza.co/+vbK2-Q

Shop  https //stza.co/+vbK2-2M

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Thunder vs. Fisher Cats
END:VALARM
DTSTART:20180409T230000Z
DTEND:20180410T020000Z
UID:yrxk4pWggpTMIQCOll_Q01RX@stanza.co
SUMMARY:Thunder vs. Fisher Cats
DESCRIPTION:Don't miss a game all season with our Magnetic Schedule Giveaway!\n\nFollow on MiLB First Pitch: https://stza.co/+vbK2-Q\n\nShop: https://stza.co/+vbK2-2M\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Magnetic Schedule Giveaway
STATUS:CONFIRMED
CREATED:20180213T144602Z
LAST-MODIFIED:20180213T144602Z
TRANSP:OPAQUE
END:VEVENT
* Thunder vs. Fisher Cats
<2018-04-10 Tue 18:00-21:00>
:PROPERTIES:
:ID:       kufmeyk1-frgb5q54-18Gv6d@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Thunder vs. Fisher Cats Thunder vs. Fisher Cats

Follow on MiLB First Pitch  https //stza.co/+vbKg-1O

Shop  https //stza.co/+vbKg-Z

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Thunder vs. Fisher Cats
END:VALARM
DTSTART:20180410T230000Z
DTEND:20180411T020000Z
UID:kufmeyk1-frgb5q54-18Gv6d@stanza.co
SUMMARY:Thunder vs. Fisher Cats
DESCRIPTION:Thunder vs. Fisher Cats\n\nFollow on MiLB First Pitch: https://stza.co/+vbKg-1O\n\nShop: https://stza.co/+vbKg-Z\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144602Z
LAST-MODIFIED:20180213T144602Z
TRANSP:OPAQUE
END:VEVENT
* Thunder vs. Fisher Cats
<2018-04-11 Wed 18:00-21:00>
:PROPERTIES:
:ID:       uF57B4daBb_IsgEoac_sE6lM@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Thunder vs. Fisher Cats Thunder vs. Fisher Cats

Follow on MiLB First Pitch  https //stza.co/+vbKu-1e

Shop  https //stza.co/+vbKu-2S

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Thunder vs. Fisher Cats
END:VALARM
DTSTART:20180411T230000Z
DTEND:20180412T020000Z
UID:uF57B4daBb_IsgEoac_sE6lM@stanza.co
SUMMARY:Thunder vs. Fisher Cats
DESCRIPTION:Thunder vs. Fisher Cats\n\nFollow on MiLB First Pitch: https://stza.co/+vbKu-1e\n\nShop: https://stza.co/+vbKu-2S\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144602Z
LAST-MODIFIED:20180213T144602Z
TRANSP:OPAQUE
END:VEVENT
* Thunder @ RubberDucks
<2018-04-13 Fri 17:35-20:35>
:PROPERTIES:
:ID:       VMbr88AUA0gmHoGm5YJOM8NF@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Thunder @ RubberDucks Thunder @ RubberDucks

Follow on MiLB First Pitch  https //stza.co/+vLwt-r

Shop  https //stza.co/+vLwt-1u

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Thunder @ RubberDucks
END:VALARM
DTSTART:20180413T223500Z
DTEND:20180414T013500Z
UID:VMbr88AUA0gmHoGm5YJOM8NF@stanza.co
SUMMARY:Thunder @ RubberDucks
DESCRIPTION:Thunder @ RubberDucks\n\nFollow on MiLB First Pitch: https://stza.co/+vLwt-r\n\nShop: https://stza.co/+vLwt-1u\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144602Z
LAST-MODIFIED:20180213T144602Z
TRANSP:OPAQUE
END:VEVENT
* Thunder @ RubberDucks
<2018-04-14 Sat 13:05-16:05>
:PROPERTIES:
:ID:       xa33wQJVgIPhcr5QipLi9EXw@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Thunder @ RubberDucks Thunder @ RubberDucks

Follow on MiLB First Pitch  https //stza.co/+vLwu-3P

Shop  https //stza.co/+vLwu-3j

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Thunder @ RubberDucks
END:VALARM
DTSTART:20180414T180500Z
DTEND:20180414T210500Z
UID:xa33wQJVgIPhcr5QipLi9EXw@stanza.co
SUMMARY:Thunder @ RubberDucks
DESCRIPTION:Thunder @ RubberDucks\n\nFollow on MiLB First Pitch: https://stza.co/+vLwu-3P\n\nShop: https://stza.co/+vLwu-3j\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144602Z
LAST-MODIFIED:20180213T144602Z
TRANSP:OPAQUE
END:VEVENT
* Thunder @ RubberDucks
<2018-04-15 Sun 13:05-16:05>
:PROPERTIES:
:ID:       Z5jfObUYQtt5clrqdVtE1KEs@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Thunder @ RubberDucks Thunder @ RubberDucks

Follow on MiLB First Pitch  https //stza.co/+vLwv-3l

Shop  https //stza.co/+vLwv-b

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Thunder @ RubberDucks
END:VALARM
DTSTART:20180415T180500Z
DTEND:20180415T210500Z
UID:Z5jfObUYQtt5clrqdVtE1KEs@stanza.co
SUMMARY:Thunder @ RubberDucks
DESCRIPTION:Thunder @ RubberDucks\n\nFollow on MiLB First Pitch: https://stza.co/+vLwv-3l\n\nShop: https://stza.co/+vLwv-b\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144602Z
LAST-MODIFIED:20180213T144602Z
TRANSP:OPAQUE
END:VEVENT
* Thunder @ SeaWolves
<2018-04-16 Mon 17:05-20:05>
:PROPERTIES:
:ID:       _qCL28t8qxALKtpnKzjhy-2f@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Thunder @ SeaWolves Thunder @ SeaWolves

Follow on MiLB First Pitch  https //stza.co/+vby6-11

Shop  https //stza.co/+vby6-3N

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Thunder @ SeaWolves
END:VALARM
DTSTART:20180416T220500Z
DTEND:20180417T010500Z
UID:_qCL28t8qxALKtpnKzjhy-2f@stanza.co
SUMMARY:Thunder @ SeaWolves
DESCRIPTION:Thunder @ SeaWolves\n\nFollow on MiLB First Pitch: https://stza.co/+vby6-11\n\nShop: https://stza.co/+vby6-3N\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144602Z
LAST-MODIFIED:20180213T144602Z
TRANSP:OPAQUE
END:VEVENT
* Thunder @ SeaWolves
<2018-04-17 Tue 17:05-20:05>
:PROPERTIES:
:ID:       abZjhcfmngXb7BI8Hop0S8jF@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Thunder @ SeaWolves Thunder @ SeaWolves

Follow on MiLB First Pitch  https //stza.co/+vbys-3w

Shop  https //stza.co/+vbys-1$

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Thunder @ SeaWolves
END:VALARM
DTSTART:20180417T220500Z
DTEND:20180418T010500Z
UID:abZjhcfmngXb7BI8Hop0S8jF@stanza.co
SUMMARY:Thunder @ SeaWolves
DESCRIPTION:Thunder @ SeaWolves\n\nFollow on MiLB First Pitch: https://stza.co/+vbys-3w\n\nShop: https://stza.co/+vbys-1$\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144602Z
LAST-MODIFIED:20180213T144602Z
TRANSP:OPAQUE
END:VEVENT
* Thunder @ SeaWolves
<2018-04-18 Wed 17:05-20:05>
:PROPERTIES:
:ID:       OJbRsdyjMku_1Glh_TbFF9VN@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Thunder @ SeaWolves Thunder @ SeaWolves

Follow on MiLB First Pitch  https //stza.co/+vbyF-g

Shop  https //stza.co/+vbyF-3q

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Thunder @ SeaWolves
END:VALARM
DTSTART:20180418T220500Z
DTEND:20180419T010500Z
UID:OJbRsdyjMku_1Glh_TbFF9VN@stanza.co
SUMMARY:Thunder @ SeaWolves
DESCRIPTION:Thunder @ SeaWolves\n\nFollow on MiLB First Pitch: https://stza.co/+vbyF-g\n\nShop: https://stza.co/+vbyF-3q\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144602Z
LAST-MODIFIED:20180213T144602Z
TRANSP:OPAQUE
END:VEVENT
* Thunder @ SeaWolves
<2018-04-19 Thu 11:05-14:05>
:PROPERTIES:
:ID:       Zat2XQ5qg1ESzjDjEWNplspn@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Thunder @ SeaWolves Thunder @ SeaWolves

Follow on MiLB First Pitch  https //stza.co/+vby_-3E

Shop  https //stza.co/+vby_-3M

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Thunder @ SeaWolves
END:VALARM
DTSTART:20180419T160500Z
DTEND:20180419T190500Z
UID:Zat2XQ5qg1ESzjDjEWNplspn@stanza.co
SUMMARY:Thunder @ SeaWolves
DESCRIPTION:Thunder @ SeaWolves\n\nFollow on MiLB First Pitch: https://stza.co/+vby_-3E\n\nShop: https://stza.co/+vby_-3M\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144602Z
LAST-MODIFIED:20180213T144602Z
TRANSP:OPAQUE
END:VEVENT
* Thunder vs. Sea Dogs
<2018-04-20 Fri 18:00-21:00>
:PROPERTIES:
:ID:       IyL5BB4YahbUe1Ihjr7OHPUQ@stanza.co
:LOCATION: Tony Clark Bobblehead Giveaway
:STATUS:   CONFIRMED
:END:

Thunder vs. Sea Dogs The first in a special 25th anniversary set of bobbleheads. Take home a bobblehead of one of the best 1B in franchise history!

Follow on MiLB First Pitch  https //stza.co/+vbKH-2y

Shop  https //stza.co/+vbKH-1i

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Thunder vs. Sea Dogs
END:VALARM
DTSTART:20180420T230000Z
DTEND:20180421T020000Z
UID:IyL5BB4YahbUe1Ihjr7OHPUQ@stanza.co
SUMMARY:Thunder vs. Sea Dogs
DESCRIPTION:The first in a special 25th anniversary set of bobbleheads. Take home a bobblehead of one of the best 1B in franchise history!\n\nFollow on MiLB First Pitch: https://stza.co/+vbKH-2y\n\nShop: https://stza.co/+vbKH-1i\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Tony Clark Bobblehead Giveaway
STATUS:CONFIRMED
CREATED:20180213T144602Z
LAST-MODIFIED:20180213T144602Z
TRANSP:OPAQUE
END:VEVENT
* Thunder vs. Sea Dogs
<2018-04-21 Sat 12:00-15:00>
:PROPERTIES:
:ID:       ZDPj7U8Rt6QDrlsjWbdqPF5r@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Thunder vs. Sea Dogs Thunder vs. Sea Dogs

Follow on MiLB First Pitch  https //stza.co/+vbKT-2e

Shop  https //stza.co/+vbKT-I

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Thunder vs. Sea Dogs
END:VALARM
DTSTART:20180421T170000Z
DTEND:20180421T200000Z
UID:ZDPj7U8Rt6QDrlsjWbdqPF5r@stanza.co
SUMMARY:Thunder vs. Sea Dogs
DESCRIPTION:Thunder vs. Sea Dogs\n\nFollow on MiLB First Pitch: https://stza.co/+vbKT-2e\n\nShop: https://stza.co/+vbKT-I\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144602Z
LAST-MODIFIED:20180213T144602Z
TRANSP:OPAQUE
END:VEVENT
* Thunder vs. Sea Dogs
<2018-04-22 Sun 12:00-15:00>
:PROPERTIES:
:ID:       WQEa9OhriV4WTjrH4N0vfqMk@stanza.co
:LOCATION: Autograph Book
:STATUS:   CONFIRMED
:END:

Thunder vs. Sea Dogs 



Follow on MiLB First Pitch  https //stza.co/+vbL4-1A

Shop  https //stza.co/+vbL4-3j

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Thunder vs. Sea Dogs
END:VALARM
DTSTART:20180422T170000Z
DTEND:20180422T200000Z
UID:WQEa9OhriV4WTjrH4N0vfqMk@stanza.co
SUMMARY:Thunder vs. Sea Dogs
DESCRIPTION:\n\n\n\nFollow on MiLB First Pitch: https://stza.co/+vbL4-1A\n\nShop: https://stza.co/+vbL4-3j\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Autograph Book
STATUS:CONFIRMED
CREATED:20180213T144602Z
LAST-MODIFIED:20180213T144602Z
TRANSP:OPAQUE
END:VEVENT
* Thunder vs. Senators
<2018-04-23 Mon 18:00-21:00>
:PROPERTIES:
:ID:       T4OVaOFzXrQjZpZoFwJ7tTr8@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Thunder vs. Senators Thunder vs. Senators

Follow on MiLB First Pitch  https //stza.co/+vbLi-3r

Shop  https //stza.co/+vbLi-2x

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Thunder vs. Senators
END:VALARM
DTSTART:20180423T230000Z
DTEND:20180424T020000Z
UID:T4OVaOFzXrQjZpZoFwJ7tTr8@stanza.co
SUMMARY:Thunder vs. Senators
DESCRIPTION:Thunder vs. Senators\n\nFollow on MiLB First Pitch: https://stza.co/+vbLi-3r\n\nShop: https://stza.co/+vbLi-2x\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144602Z
LAST-MODIFIED:20180213T144602Z
TRANSP:OPAQUE
END:VEVENT
* Thunder vs. Senators
<2018-04-24 Tue 18:00-21:00>
:PROPERTIES:
:ID:       1VPBDDduUHIgjoI2elXO0g1l@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Thunder vs. Senators Thunder vs. Senators

Follow on MiLB First Pitch  https //stza.co/+vbLu-2R

Shop  https //stza.co/+vbLu-1B

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Thunder vs. Senators
END:VALARM
DTSTART:20180424T230000Z
DTEND:20180425T020000Z
UID:1VPBDDduUHIgjoI2elXO0g1l@stanza.co
SUMMARY:Thunder vs. Senators
DESCRIPTION:Thunder vs. Senators\n\nFollow on MiLB First Pitch: https://stza.co/+vbLu-2R\n\nShop: https://stza.co/+vbLu-1B\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144602Z
LAST-MODIFIED:20180213T144602Z
TRANSP:OPAQUE
END:VEVENT
* Thunder vs. Senators
<2018-04-25 Wed 09:30-12:30>
:PROPERTIES:
:ID:       3o7_N3njZTU-0DjAy3ZloXHe@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Thunder vs. Senators Thunder vs. Senators

Follow on MiLB First Pitch  https //stza.co/+vbLz-N

Shop  https //stza.co/+vbLz-1Z

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Thunder vs. Senators
END:VALARM
DTSTART:20180425T143000Z
DTEND:20180425T173000Z
UID:3o7_N3njZTU-0DjAy3ZloXHe@stanza.co
SUMMARY:Thunder vs. Senators
DESCRIPTION:Thunder vs. Senators\n\nFollow on MiLB First Pitch: https://stza.co/+vbLz-N\n\nShop: https://stza.co/+vbLz-1Z\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144602Z
LAST-MODIFIED:20180213T144602Z
TRANSP:OPAQUE
END:VEVENT
* Thunder @ Fisher Cats
<2018-04-27 Fri 17:35-20:35>
:PROPERTIES:
:ID:       rBub0vURtF6N-r43eLXnTOj0@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Thunder @ Fisher Cats Thunder @ Fisher Cats

Follow on MiLB First Pitch  https //stza.co/+vbCL-2g

Shop  https //stza.co/+vbCL-I

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Thunder @ Fisher Cats
END:VALARM
DTSTART:20180427T223500Z
DTEND:20180428T013500Z
UID:rBub0vURtF6N-r43eLXnTOj0@stanza.co
SUMMARY:Thunder @ Fisher Cats
DESCRIPTION:Thunder @ Fisher Cats\n\nFollow on MiLB First Pitch: https://stza.co/+vbCL-2g\n\nShop: https://stza.co/+vbCL-I\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144602Z
LAST-MODIFIED:20180213T144602Z
TRANSP:OPAQUE
END:VEVENT
* Thunder @ Fisher Cats
<2018-04-28 Sat 17:35-20:35>
:PROPERTIES:
:ID:       p2e2xr6BbD5lNTXZ7QY9cdNj@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Thunder @ Fisher Cats Thunder @ Fisher Cats

Follow on MiLB First Pitch  https //stza.co/+vbD8-d

Shop  https //stza.co/+vbD8-1G

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Thunder @ Fisher Cats
END:VALARM
DTSTART:20180428T223500Z
DTEND:20180429T013500Z
UID:p2e2xr6BbD5lNTXZ7QY9cdNj@stanza.co
SUMMARY:Thunder @ Fisher Cats
DESCRIPTION:Thunder @ Fisher Cats\n\nFollow on MiLB First Pitch: https://stza.co/+vbD8-d\n\nShop: https://stza.co/+vbD8-1G\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144602Z
LAST-MODIFIED:20180213T144602Z
TRANSP:OPAQUE
END:VEVENT
* Thunder @ Fisher Cats
<2018-04-29 Sun 12:35-15:35>
:PROPERTIES:
:ID:       mAENa0xycBQ4gGpsMMcbyVVu@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Thunder @ Fisher Cats Thunder @ Fisher Cats

Follow on MiLB First Pitch  https //stza.co/+vbDr-U

Shop  https //stza.co/+vbDr-1M

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Thunder @ Fisher Cats
END:VALARM
DTSTART:20180429T173500Z
DTEND:20180429T203500Z
UID:mAENa0xycBQ4gGpsMMcbyVVu@stanza.co
SUMMARY:Thunder @ Fisher Cats
DESCRIPTION:Thunder @ Fisher Cats\n\nFollow on MiLB First Pitch: https://stza.co/+vbDr-U\n\nShop: https://stza.co/+vbDr-1M\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144602Z
LAST-MODIFIED:20180213T144602Z
TRANSP:OPAQUE
END:VEVENT
* Thunder @ Sea Dogs
<2018-04-30 Mon 17:00-20:00>
:PROPERTIES:
:ID:       Uev21QdwjVC-oY23Q1W3QNwH@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Thunder @ Sea Dogs Thunder @ Sea Dogs

Buy tickets here  https //stza.co/~vbEy

Follow on MiLB First Pitch  https //stza.co/+vbEy-X

Shop  https //stza.co/+vbEy-3J

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Thunder @ Sea Dogs
END:VALARM
DTSTART:20180430T220000Z
DTEND:20180501T010000Z
UID:Uev21QdwjVC-oY23Q1W3QNwH@stanza.co
SUMMARY:Thunder @ Sea Dogs
DESCRIPTION:Thunder @ Sea Dogs\n\nBuy tickets here: https://stza.co/~vbEy\n\nFollow on MiLB First Pitch: https://stza.co/+vbEy-X\n\nShop: https://stza.co/+vbEy-3J\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144602Z
LAST-MODIFIED:20180213T144602Z
TRANSP:OPAQUE
END:VEVENT
* Thunder @ Sea Dogs
<2018-05-01 Tue 17:00-20:00>
:PROPERTIES:
:ID:       9xzRTDyJtgDMHZ4WGOkDnv9u@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Thunder @ Sea Dogs Thunder @ Sea Dogs

Buy tickets here  https //stza.co/~vbET

Follow on MiLB First Pitch  https //stza.co/+vbET-2F

Shop  https //stza.co/+vbET-s

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Thunder @ Sea Dogs
END:VALARM
DTSTART:20180501T220000Z
DTEND:20180502T010000Z
UID:9xzRTDyJtgDMHZ4WGOkDnv9u@stanza.co
SUMMARY:Thunder @ Sea Dogs
DESCRIPTION:Thunder @ Sea Dogs\n\nBuy tickets here: https://stza.co/~vbET\n\nFollow on MiLB First Pitch: https://stza.co/+vbET-2F\n\nShop: https://stza.co/+vbET-s\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144602Z
LAST-MODIFIED:20180213T144602Z
TRANSP:OPAQUE
END:VEVENT
* Thunder @ Sea Dogs
<2018-05-02 Wed 17:00-20:00>
:PROPERTIES:
:ID:       J9ayOCnWw39hoGkFhZ8Mo8LI@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Thunder @ Sea Dogs Thunder @ Sea Dogs

Buy tickets here  https //stza.co/~vbF9

Follow on MiLB First Pitch  https //stza.co/+vbF9-3z

Shop  https //stza.co/+vbF9-b

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Thunder @ Sea Dogs
END:VALARM
DTSTART:20180502T220000Z
DTEND:20180503T010000Z
UID:J9ayOCnWw39hoGkFhZ8Mo8LI@stanza.co
SUMMARY:Thunder @ Sea Dogs
DESCRIPTION:Thunder @ Sea Dogs\n\nBuy tickets here: https://stza.co/~vbF9\n\nFollow on MiLB First Pitch: https://stza.co/+vbF9-3z\n\nShop: https://stza.co/+vbF9-b\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144602Z
LAST-MODIFIED:20180213T144602Z
TRANSP:OPAQUE
END:VEVENT
* Thunder vs. Senators
<2018-05-03 Thu 18:00-21:00>
:PROPERTIES:
:ID:       SlGHmxql_uPbp1suR9Dglrd6@stanza.co
:LOCATION: Fireworks Spectacular
:STATUS:   CONFIRMED
:END:

Thunder vs. Senators Take in the awe-inspiring majesty of our post-game fireworks spectacular after the game right from your seat!

Follow on MiLB First Pitch  https //stza.co/+vbLL-2F

Shop  https //stza.co/+vbLL-3v

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Thunder vs. Senators
END:VALARM
DTSTART:20180503T230000Z
DTEND:20180504T020000Z
UID:SlGHmxql_uPbp1suR9Dglrd6@stanza.co
SUMMARY:Thunder vs. Senators
DESCRIPTION:Take in the awe-inspiring majesty of our post-game fireworks spectacular after the game right from your seat!\n\nFollow on MiLB First Pitch: https://stza.co/+vbLL-2F\n\nShop: https://stza.co/+vbLL-3v\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Fireworks Spectacular
STATUS:CONFIRMED
CREATED:20180213T144602Z
LAST-MODIFIED:20180213T144602Z
TRANSP:OPAQUE
END:VEVENT
* Thunder vs. Senators
<2018-05-04 Fri 18:00-21:00>
:PROPERTIES:
:ID:       Ma6oEGLHvzWNjGuVvGIbw7Zz@stanza.co
:LOCATION: Robinson Cano Bobblehead Giveaway
:STATUS:   CONFIRMED
:END:

Thunder vs. Senators The second in a special 25th anniversary set of bobbleheads. Take home a bobblehead of one of the best 2B in franchise history!

Follow on MiLB First Pitch  https //stza.co/+vbL_-3i

Shop  https //stza.co/+vbL_-27

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Thunder vs. Senators
END:VALARM
DTSTART:20180504T230000Z
DTEND:20180505T020000Z
UID:Ma6oEGLHvzWNjGuVvGIbw7Zz@stanza.co
SUMMARY:Thunder vs. Senators
DESCRIPTION:The second in a special 25th anniversary set of bobbleheads. Take home a bobblehead of one of the best 2B in franchise history!\n\nFollow on MiLB First Pitch: https://stza.co/+vbL_-3i\n\nShop: https://stza.co/+vbL_-27\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Robinson Cano Bobblehead Giveaway
STATUS:CONFIRMED
CREATED:20180213T144602Z
LAST-MODIFIED:20180213T144602Z
TRANSP:OPAQUE
END:VEVENT
* Thunder vs. Senators
<2018-05-05 Sat 18:00-21:00>
:PROPERTIES:
:ID:       PJ0BIRILptAAT7QzF_iWIkIA@stanza.co
:LOCATION: Fireworks Spectacular
:STATUS:   CONFIRMED
:END:

Thunder vs. Senators Take in the awe-inspiring majesty of our post-game fireworks spectacular after the game right from your seat!

Follow on MiLB First Pitch  https //stza.co/+vbM6-3f

Shop  https //stza.co/+vbM6-2E

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Thunder vs. Senators
END:VALARM
DTSTART:20180505T230000Z
DTEND:20180506T020000Z
UID:PJ0BIRILptAAT7QzF_iWIkIA@stanza.co
SUMMARY:Thunder vs. Senators
DESCRIPTION:Take in the awe-inspiring majesty of our post-game fireworks spectacular after the game right from your seat!\n\nFollow on MiLB First Pitch: https://stza.co/+vbM6-3f\n\nShop: https://stza.co/+vbM6-2E\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Fireworks Spectacular
STATUS:CONFIRMED
CREATED:20180213T144602Z
LAST-MODIFIED:20180213T144602Z
TRANSP:OPAQUE
END:VEVENT
* Thunder vs. Senators
<2018-05-06 Sun 12:00-15:00>
:PROPERTIES:
:ID:       4T0Mt1maV9gwPHKpkqhg20VJ@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Thunder vs. Senators Thunder vs. Senators

Follow on MiLB First Pitch  https //stza.co/+vbMj-1d

Shop  https //stza.co/+vbMj-3d

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Thunder vs. Senators
END:VALARM
DTSTART:20180506T170000Z
DTEND:20180506T200000Z
UID:4T0Mt1maV9gwPHKpkqhg20VJ@stanza.co
SUMMARY:Thunder vs. Senators
DESCRIPTION:Thunder vs. Senators\n\nFollow on MiLB First Pitch: https://stza.co/+vbMj-1d\n\nShop: https://stza.co/+vbMj-3d\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144602Z
LAST-MODIFIED:20180213T144602Z
TRANSP:OPAQUE
END:VEVENT
* Thunder vs. Fightin Phils
<2018-05-07 Mon 18:00-21:00>
:PROPERTIES:
:ID:       zGRu1Ldm9RtKHdv7oEx_JHyD@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Thunder vs. Fightin Phils Thunder vs. Fightin Phils

Follow on MiLB First Pitch  https //stza.co/+vbMy-3h

Shop  https //stza.co/+vbMy-1k

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Thunder vs. Fightin Phils
END:VALARM
DTSTART:20180507T230000Z
DTEND:20180508T020000Z
UID:zGRu1Ldm9RtKHdv7oEx_JHyD@stanza.co
SUMMARY:Thunder vs. Fightin Phils
DESCRIPTION:Thunder vs. Fightin Phils\n\nFollow on MiLB First Pitch: https://stza.co/+vbMy-3h\n\nShop: https://stza.co/+vbMy-1k\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144602Z
LAST-MODIFIED:20180213T144602Z
TRANSP:OPAQUE
END:VEVENT
* Thunder vs. Fightin Phils
<2018-05-08 Tue 18:00-21:00>
:PROPERTIES:
:ID:       CAuywvl87Z_NpdXuX4DMBprY@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Thunder vs. Fightin Phils Thunder vs. Fightin Phils

Follow on MiLB First Pitch  https //stza.co/+vbMO-1U

Shop  https //stza.co/+vbMO-1R

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Thunder vs. Fightin Phils
END:VALARM
DTSTART:20180508T230000Z
DTEND:20180509T020000Z
UID:CAuywvl87Z_NpdXuX4DMBprY@stanza.co
SUMMARY:Thunder vs. Fightin Phils
DESCRIPTION:Thunder vs. Fightin Phils\n\nFollow on MiLB First Pitch: https://stza.co/+vbMO-1U\n\nShop: https://stza.co/+vbMO-1R\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144602Z
LAST-MODIFIED:20180213T144602Z
TRANSP:OPAQUE
END:VEVENT
* Thunder vs. Fightin Phils
<2018-05-09 Wed 09:30-12:30>
:PROPERTIES:
:ID:       omzgNAgqare0yKRP065UepYn@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Thunder vs. Fightin Phils Thunder vs. Fightin Phils

Follow on MiLB First Pitch  https //stza.co/+vbMZ-V

Shop  https //stza.co/+vbMZ-3k

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Thunder vs. Fightin Phils
END:VALARM
DTSTART:20180509T143000Z
DTEND:20180509T173000Z
UID:omzgNAgqare0yKRP065UepYn@stanza.co
SUMMARY:Thunder vs. Fightin Phils
DESCRIPTION:Thunder vs. Fightin Phils\n\nFollow on MiLB First Pitch: https://stza.co/+vbMZ-V\n\nShop: https://stza.co/+vbMZ-3k\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144602Z
LAST-MODIFIED:20180213T144602Z
TRANSP:OPAQUE
END:VEVENT
* Thunder @ Flying Squirrels
<2018-05-10 Thu 17:35-20:35>
:PROPERTIES:
:ID:       tXBOyeNz6NIbUxIDeweIw1tD@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Thunder @ Flying Squirrels Thunder @ Flying Squirrels

Follow on MiLB First Pitch  https //stza.co/+vbIG-1K

Shop  https //stza.co/+vbIG-j

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Thunder @ Flying Squirrels
END:VALARM
DTSTART:20180510T223500Z
DTEND:20180511T013500Z
UID:tXBOyeNz6NIbUxIDeweIw1tD@stanza.co
SUMMARY:Thunder @ Flying Squirrels
DESCRIPTION:Thunder @ Flying Squirrels\n\nFollow on MiLB First Pitch: https://stza.co/+vbIG-1K\n\nShop: https://stza.co/+vbIG-j\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144602Z
LAST-MODIFIED:20180213T144602Z
TRANSP:OPAQUE
END:VEVENT
* Thunder @ Flying Squirrels
<2018-05-11 Fri 18:05-21:05>
:PROPERTIES:
:ID:       dEVuypzRxHch3woC3Tp7SsIE@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Thunder @ Flying Squirrels Thunder @ Flying Squirrels

Follow on MiLB First Pitch  https //stza.co/+vbIS-16

Shop  https //stza.co/+vbIS-1B

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Thunder @ Flying Squirrels
END:VALARM
DTSTART:20180511T230500Z
DTEND:20180512T020500Z
UID:dEVuypzRxHch3woC3Tp7SsIE@stanza.co
SUMMARY:Thunder @ Flying Squirrels
DESCRIPTION:Thunder @ Flying Squirrels\n\nFollow on MiLB First Pitch: https://stza.co/+vbIS-16\n\nShop: https://stza.co/+vbIS-1B\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144602Z
LAST-MODIFIED:20180213T144602Z
TRANSP:OPAQUE
END:VEVENT
* Thunder @ Flying Squirrels
<2018-05-12 Sat 17:05-20:05>
:PROPERTIES:
:ID:       lck9kKw2AZN57dNzCY1jKiYo@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Thunder @ Flying Squirrels Thunder @ Flying Squirrels

Follow on MiLB First Pitch  https //stza.co/+vbJ1-1Z

Shop  https //stza.co/+vbJ1-10

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Thunder @ Flying Squirrels
END:VALARM
DTSTART:20180512T220500Z
DTEND:20180513T010500Z
UID:lck9kKw2AZN57dNzCY1jKiYo@stanza.co
SUMMARY:Thunder @ Flying Squirrels
DESCRIPTION:Thunder @ Flying Squirrels\n\nFollow on MiLB First Pitch: https://stza.co/+vbJ1-1Z\n\nShop: https://stza.co/+vbJ1-10\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144602Z
LAST-MODIFIED:20180213T144602Z
TRANSP:OPAQUE
END:VEVENT
* Thunder @ Flying Squirrels
<2018-05-13 Sun 12:05-15:05>
:PROPERTIES:
:ID:       IlvsugXvIPO-0AAqR-Hje7zc@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Thunder @ Flying Squirrels Thunder @ Flying Squirrels

Follow on MiLB First Pitch  https //stza.co/+vbJd-3O

Shop  https //stza.co/+vbJd-3G

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Thunder @ Flying Squirrels
END:VALARM
DTSTART:20180513T170500Z
DTEND:20180513T200500Z
UID:IlvsugXvIPO-0AAqR-Hje7zc@stanza.co
SUMMARY:Thunder @ Flying Squirrels
DESCRIPTION:Thunder @ Flying Squirrels\n\nFollow on MiLB First Pitch: https://stza.co/+vbJd-3O\n\nShop: https://stza.co/+vbJd-3G\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144602Z
LAST-MODIFIED:20180213T144602Z
TRANSP:OPAQUE
END:VEVENT
* Thunder vs. RubberDucks
<2018-05-14 Mon 18:00-21:00>
:PROPERTIES:
:ID:       wW8NVLGPidr3c6L5hd1yMGVk@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Thunder vs. RubberDucks Thunder vs. RubberDucks

Follow on MiLB First Pitch  https //stza.co/+vbN9-3y

Shop  https //stza.co/+vbN9-3w

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Thunder vs. RubberDucks
END:VALARM
DTSTART:20180514T230000Z
DTEND:20180515T020000Z
UID:wW8NVLGPidr3c6L5hd1yMGVk@stanza.co
SUMMARY:Thunder vs. RubberDucks
DESCRIPTION:Thunder vs. RubberDucks\n\nFollow on MiLB First Pitch: https://stza.co/+vbN9-3y\n\nShop: https://stza.co/+vbN9-3w\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144602Z
LAST-MODIFIED:20180213T144602Z
TRANSP:OPAQUE
END:VEVENT
* Thunder vs. RubberDucks
<2018-05-15 Tue 18:00-21:00>
:PROPERTIES:
:ID:       eaZZH4L_MZuy2UXsjTDSE-2_@stanza.co
:LOCATION: Nomar Garciaparra Bobblehead Giveaway
:STATUS:   CONFIRMED
:END:

Thunder vs. RubberDucks The third in a special 25th anniversary set of bobbleheads. Take home a bobblehead of one of the best SS in franchise history!

Follow on MiLB First Pitch  https //stza.co/+vbNo-O

Shop  https //stza.co/+vbNo-2N

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Thunder vs. RubberDucks
END:VALARM
DTSTART:20180515T230000Z
DTEND:20180516T020000Z
UID:eaZZH4L_MZuy2UXsjTDSE-2_@stanza.co
SUMMARY:Thunder vs. RubberDucks
DESCRIPTION:The third in a special 25th anniversary set of bobbleheads. Take home a bobblehead of one of the best SS in franchise history!\n\nFollow on MiLB First Pitch: https://stza.co/+vbNo-O\n\nShop: https://stza.co/+vbNo-2N\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Nomar Garciaparra Bobblehead Giveaway
STATUS:CONFIRMED
CREATED:20180213T144602Z
LAST-MODIFIED:20180213T144602Z
TRANSP:OPAQUE
END:VEVENT
* Thunder vs. RubberDucks
<2018-05-16 Wed 09:30-12:30>
:PROPERTIES:
:ID:       VWm4tGuhAGkIgJ3lRKvGy5Gw@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Thunder vs. RubberDucks Thunder vs. RubberDucks

Follow on MiLB First Pitch  https //stza.co/+vbNA-k

Shop  https //stza.co/+vbNA-m

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Thunder vs. RubberDucks
END:VALARM
DTSTART:20180516T143000Z
DTEND:20180516T173000Z
UID:VWm4tGuhAGkIgJ3lRKvGy5Gw@stanza.co
SUMMARY:Thunder vs. RubberDucks
DESCRIPTION:Thunder vs. RubberDucks\n\nFollow on MiLB First Pitch: https://stza.co/+vbNA-k\n\nShop: https://stza.co/+vbNA-m\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144602Z
LAST-MODIFIED:20180213T144602Z
TRANSP:OPAQUE
END:VEVENT
* Thunder vs. Baysox
<2018-05-17 Thu 18:00-21:00>
:PROPERTIES:
:ID:       TQx5Lb1hZpdu3lrMacUEe1C_@stanza.co
:LOCATION: Firework Spectacular
:STATUS:   CONFIRMED
:END:

Thunder vs. Baysox Take in the awe-inspiring majesty of our post-game fireworks spectacular after the game right from your seat. 

Follow on MiLB First Pitch  https //stza.co/+vbNL-3d

Shop  https //stza.co/+vbNL-L

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Thunder vs. Baysox
END:VALARM
DTSTART:20180517T230000Z
DTEND:20180518T020000Z
UID:TQx5Lb1hZpdu3lrMacUEe1C_@stanza.co
SUMMARY:Thunder vs. Baysox
DESCRIPTION:Take in the awe-inspiring majesty of our post-game fireworks spectacular after the game right from your seat. \n\nFollow on MiLB First Pitch: https://stza.co/+vbNL-3d\n\nShop: https://stza.co/+vbNL-L\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Firework Spectacular
STATUS:CONFIRMED
CREATED:20180213T144602Z
LAST-MODIFIED:20180213T144602Z
TRANSP:OPAQUE
END:VEVENT
* Thunder vs. Baysox
<2018-05-18 Fri 18:00-21:00>
:PROPERTIES:
:ID:       4lKg9DBgCEhtkKkRmWTAhXM5@stanza.co
:LOCATION: Apron Giveaway
:STATUS:   CONFIRMED
:END:

Thunder vs. Baysox Celebrate Pork Roll with us and the first 1,025 fans ages 21 and older will receive a Case's Pork Roll Apron Giveaway!

Celebrate a New Jersey favorite! All fans can enjoy $1 pork roll sandwiches all night and see the anticipated debut of the Thunder Pork Roll uniforms!

Follow on MiLB First Pitch  https //stza.co/+vbNZ-20

Shop  https //stza.co/+vbNZ-3t

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Thunder vs. Baysox
END:VALARM
DTSTART:20180518T230000Z
DTEND:20180519T020000Z
UID:4lKg9DBgCEhtkKkRmWTAhXM5@stanza.co
SUMMARY:Thunder vs. Baysox
DESCRIPTION:Celebrate Pork Roll with us and the first 1,025 fans ages 21 and older will receive a Case's Pork Roll Apron Giveaway!\n\nCelebrate a New Jersey favorite! All fans can enjoy $1 pork roll sandwiches all night and see the anticipated debut of the Thunder Pork Roll uniforms!\n\nFollow on MiLB First Pitch: https://stza.co/+vbNZ-20\n\nShop: https://stza.co/+vbNZ-3t\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Apron Giveaway
STATUS:CONFIRMED
CREATED:20180213T144602Z
LAST-MODIFIED:20180213T144602Z
TRANSP:OPAQUE
END:VEVENT
* Thunder vs. Baysox
<2018-05-19 Sat 18:00-21:00>
:PROPERTIES:
:ID:       OYA1p7vcfH46EYXrxJ9Ib0b8@stanza.co
:LOCATION: Fireworks Spectacular
:STATUS:   CONFIRMED
:END:

Thunder vs. Baysox Take in the awe-inspiring majesty of our post-game fireworks spectacular after the game right from your seat!

Follow on MiLB First Pitch  https //stza.co/+vbO9-2G

Shop  https //stza.co/+vbO9-2f

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Thunder vs. Baysox
END:VALARM
DTSTART:20180519T230000Z
DTEND:20180520T020000Z
UID:OYA1p7vcfH46EYXrxJ9Ib0b8@stanza.co
SUMMARY:Thunder vs. Baysox
DESCRIPTION:Take in the awe-inspiring majesty of our post-game fireworks spectacular after the game right from your seat!\n\nFollow on MiLB First Pitch: https://stza.co/+vbO9-2G\n\nShop: https://stza.co/+vbO9-2f\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Fireworks Spectacular
STATUS:CONFIRMED
CREATED:20180213T144602Z
LAST-MODIFIED:20180213T144602Z
TRANSP:OPAQUE
END:VEVENT
* Thunder vs. Baysox
<2018-05-20 Sun 12:00-15:00>
:PROPERTIES:
:ID:       RSWDTXKrbL-T8sUAxzNogDVX@stanza.co
:LOCATION: Boomer's Birthday T-Shirt Giveaway
:STATUS:   CONFIRMED
:END:

Thunder vs. Baysox Celebrate Boomer's Birthday with many of his mascot friends and arrive early for our special Boomer's Birthday T-Shirt Giveaway!

Follow on MiLB First Pitch  https //stza.co/+vbOj-D

Shop  https //stza.co/+vbOj-18

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Thunder vs. Baysox
END:VALARM
DTSTART:20180520T170000Z
DTEND:20180520T200000Z
UID:RSWDTXKrbL-T8sUAxzNogDVX@stanza.co
SUMMARY:Thunder vs. Baysox
DESCRIPTION:Celebrate Boomer's Birthday with many of his mascot friends and arrive early for our special Boomer's Birthday T-Shirt Giveaway!\n\nFollow on MiLB First Pitch: https://stza.co/+vbOj-D\n\nShop: https://stza.co/+vbOj-18\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Boomer's Birthday T-Shirt Giveaway
STATUS:CONFIRMED
CREATED:20180213T144602Z
LAST-MODIFIED:20180213T144602Z
TRANSP:OPAQUE
END:VEVENT
* Thunder @ RubberDucks
<2018-05-22 Tue 17:35-20:35>
:PROPERTIES:
:ID:       Mz45Ff3GtD9Za9iX-iAjYyni@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Thunder @ RubberDucks Thunder @ RubberDucks

Follow on MiLB First Pitch  https //stza.co/+vLww-o

Shop  https //stza.co/+vLww-2R

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Thunder @ RubberDucks
END:VALARM
DTSTART:20180522T223500Z
DTEND:20180523T013500Z
UID:Mz45Ff3GtD9Za9iX-iAjYyni@stanza.co
SUMMARY:Thunder @ RubberDucks
DESCRIPTION:Thunder @ RubberDucks\n\nFollow on MiLB First Pitch: https://stza.co/+vLww-o\n\nShop: https://stza.co/+vLww-2R\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144602Z
LAST-MODIFIED:20180213T144602Z
TRANSP:OPAQUE
END:VEVENT
* Thunder @ RubberDucks
<2018-05-23 Wed 09:35-12:35>
:PROPERTIES:
:ID:       Ngf85BiM8Xjo0UfSgFwgkZCz@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Thunder @ RubberDucks Thunder @ RubberDucks

Follow on MiLB First Pitch  https //stza.co/+vbrE-p

Shop  https //stza.co/+vbrE-3k

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Thunder @ RubberDucks
END:VALARM
DTSTART:20180523T143500Z
DTEND:20180523T173500Z
UID:Ngf85BiM8Xjo0UfSgFwgkZCz@stanza.co
SUMMARY:Thunder @ RubberDucks
DESCRIPTION:Thunder @ RubberDucks\n\nFollow on MiLB First Pitch: https://stza.co/+vbrE-p\n\nShop: https://stza.co/+vbrE-3k\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144602Z
LAST-MODIFIED:20180213T144602Z
TRANSP:OPAQUE
END:VEVENT
* Thunder @ RubberDucks
<2018-05-24 Thu 09:35-12:35>
:PROPERTIES:
:ID:       Jz8zE6X8y9ToMS4sjQHCSeKE@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Thunder @ RubberDucks Thunder @ RubberDucks

Follow on MiLB First Pitch  https //stza.co/+vbrV-1C

Shop  https //stza.co/+vbrV-1

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Thunder @ RubberDucks
END:VALARM
DTSTART:20180524T143500Z
DTEND:20180524T173500Z
UID:Jz8zE6X8y9ToMS4sjQHCSeKE@stanza.co
SUMMARY:Thunder @ RubberDucks
DESCRIPTION:Thunder @ RubberDucks\n\nFollow on MiLB First Pitch: https://stza.co/+vbrV-1C\n\nShop: https://stza.co/+vbrV-1\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144602Z
LAST-MODIFIED:20180213T144602Z
TRANSP:OPAQUE
END:VEVENT
* Thunder @ SeaWolves
<2018-05-25 Fri 17:05-20:05>
:PROPERTIES:
:ID:       pEARPFd9lF8LM1P-FM7Tet2R@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Thunder @ SeaWolves Thunder @ SeaWolves

Follow on MiLB First Pitch  https //stza.co/+vbze-b

Shop  https //stza.co/+vbze-Z

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Thunder @ SeaWolves
END:VALARM
DTSTART:20180525T220500Z
DTEND:20180526T010500Z
UID:pEARPFd9lF8LM1P-FM7Tet2R@stanza.co
SUMMARY:Thunder @ SeaWolves
DESCRIPTION:Thunder @ SeaWolves\n\nFollow on MiLB First Pitch: https://stza.co/+vbze-b\n\nShop: https://stza.co/+vbze-Z\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144602Z
LAST-MODIFIED:20180213T144602Z
TRANSP:OPAQUE
END:VEVENT
* Thunder @ SeaWolves
<2018-05-26 Sat 17:05-20:05>
:PROPERTIES:
:ID:       CIUixBawRFF4oWrdxbC7FjI3@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Thunder @ SeaWolves Thunder @ SeaWolves

Follow on MiLB First Pitch  https //stza.co/+vbzu-N

Shop  https //stza.co/+vbzu-S

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Thunder @ SeaWolves
END:VALARM
DTSTART:20180526T220500Z
DTEND:20180527T010500Z
UID:CIUixBawRFF4oWrdxbC7FjI3@stanza.co
SUMMARY:Thunder @ SeaWolves
DESCRIPTION:Thunder @ SeaWolves\n\nFollow on MiLB First Pitch: https://stza.co/+vbzu-N\n\nShop: https://stza.co/+vbzu-S\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144602Z
LAST-MODIFIED:20180213T144602Z
TRANSP:OPAQUE
END:VEVENT
* Thunder @ SeaWolves
<2018-05-27 Sun 12:35-15:35>
:PROPERTIES:
:ID:       wIf4cT-ZySY_Pt62CR3bFgsy@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Thunder @ SeaWolves Thunder @ SeaWolves

Follow on MiLB First Pitch  https //stza.co/+vbzL-1E

Shop  https //stza.co/+vbzL-2n

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Thunder @ SeaWolves
END:VALARM
DTSTART:20180527T173500Z
DTEND:20180527T203500Z
UID:wIf4cT-ZySY_Pt62CR3bFgsy@stanza.co
SUMMARY:Thunder @ SeaWolves
DESCRIPTION:Thunder @ SeaWolves\n\nFollow on MiLB First Pitch: https://stza.co/+vbzL-1E\n\nShop: https://stza.co/+vbzL-2n\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144602Z
LAST-MODIFIED:20180213T144602Z
TRANSP:OPAQUE
END:VEVENT
* Thunder @ SeaWolves
<2018-05-28 Mon 12:35-15:35>
:PROPERTIES:
:ID:       nB3PJTm5k-D0uNpw54HkHlt3@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Thunder @ SeaWolves Thunder @ SeaWolves

Follow on MiLB First Pitch  https //stza.co/+vbz$-1y

Shop  https //stza.co/+vbz$-b

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Thunder @ SeaWolves
END:VALARM
DTSTART:20180528T173500Z
DTEND:20180528T203500Z
UID:nB3PJTm5k-D0uNpw54HkHlt3@stanza.co
SUMMARY:Thunder @ SeaWolves
DESCRIPTION:Thunder @ SeaWolves\n\nFollow on MiLB First Pitch: https://stza.co/+vbz$-1y\n\nShop: https://stza.co/+vbz$-b\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144602Z
LAST-MODIFIED:20180213T144602Z
TRANSP:OPAQUE
END:VEVENT
* Thunder vs. Fightin Phils
<2018-05-29 Tue 18:00-21:00>
:PROPERTIES:
:ID:       KrgPfH9TcI8zjGTMl2HpjEAE@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Thunder vs. Fightin Phils Thunder vs. Fightin Phils

Follow on MiLB First Pitch  https //stza.co/+vbOw-y

Shop  https //stza.co/+vbOw-13

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Thunder vs. Fightin Phils
END:VALARM
DTSTART:20180529T230000Z
DTEND:20180530T020000Z
UID:KrgPfH9TcI8zjGTMl2HpjEAE@stanza.co
SUMMARY:Thunder vs. Fightin Phils
DESCRIPTION:Thunder vs. Fightin Phils\n\nFollow on MiLB First Pitch: https://stza.co/+vbOw-y\n\nShop: https://stza.co/+vbOw-13\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144602Z
LAST-MODIFIED:20180213T144602Z
TRANSP:OPAQUE
END:VEVENT
* Thunder vs. Fightin Phils
<2018-05-30 Wed 18:00-21:00>
:PROPERTIES:
:ID:       RjNpsS725JGGABl4exqAguJP@stanza.co
:LOCATION: Fireworks Spectacular
:STATUS:   CONFIRMED
:END:

Thunder vs. Fightin Phils Take in the awe-inspiring majesty of our post-game fireworks spectacular after the game right from your seat!

Follow on MiLB First Pitch  https //stza.co/+vbOG-1x

Shop  https //stza.co/+vbOG-2W

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Thunder vs. Fightin Phils
END:VALARM
DTSTART:20180530T230000Z
DTEND:20180531T020000Z
UID:RjNpsS725JGGABl4exqAguJP@stanza.co
SUMMARY:Thunder vs. Fightin Phils
DESCRIPTION:Take in the awe-inspiring majesty of our post-game fireworks spectacular after the game right from your seat!\n\nFollow on MiLB First Pitch: https://stza.co/+vbOG-1x\n\nShop: https://stza.co/+vbOG-2W\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Fireworks Spectacular
STATUS:CONFIRMED
CREATED:20180213T144602Z
LAST-MODIFIED:20180213T144602Z
TRANSP:OPAQUE
END:VEVENT
* Thunder vs. Fightin Phils
<2018-05-31 Thu 18:00-21:00>
:PROPERTIES:
:ID:       klGd1wtGfOTTY_CJD2DM8ERP@stanza.co
:LOCATION: Fireworks Spectacular
:STATUS:   CONFIRMED
:END:

Thunder vs. Fightin Phils Take in the awe-inspiring majesty of our post-game fireworks spectacular after the game right from your seat!

Follow on MiLB First Pitch  https //stza.co/+vbn$-3h

Shop  https //stza.co/+vbn$-31

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Thunder vs. Fightin Phils
END:VALARM
DTSTART:20180531T230000Z
DTEND:20180601T020000Z
UID:klGd1wtGfOTTY_CJD2DM8ERP@stanza.co
SUMMARY:Thunder vs. Fightin Phils
DESCRIPTION:Take in the awe-inspiring majesty of our post-game fireworks spectacular after the game right from your seat!\n\nFollow on MiLB First Pitch: https://stza.co/+vbn$-3h\n\nShop: https://stza.co/+vbn$-31\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Fireworks Spectacular
STATUS:CONFIRMED
CREATED:20180213T144602Z
LAST-MODIFIED:20180213T144602Z
TRANSP:OPAQUE
END:VEVENT
* Thunder @ Baysox
<2018-06-01 Fri 18:05-21:05>
:PROPERTIES:
:ID:       vRj5owr6OoZQZkuiOZKlfBO0@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Thunder @ Baysox Thunder @ Baysox

Follow on MiLB First Pitch  https //stza.co/+vbwB-1O

Shop  https //stza.co/+vbwB-3t

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Thunder @ Baysox
END:VALARM
DTSTART:20180601T230500Z
DTEND:20180602T020500Z
UID:vRj5owr6OoZQZkuiOZKlfBO0@stanza.co
SUMMARY:Thunder @ Baysox
DESCRIPTION:Thunder @ Baysox\n\nFollow on MiLB First Pitch: https://stza.co/+vbwB-1O\n\nShop: https://stza.co/+vbwB-3t\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144602Z
LAST-MODIFIED:20180213T144602Z
TRANSP:OPAQUE
END:VEVENT
* Thunder @ Baysox
<2018-06-02 Sat 17:35-20:35>
:PROPERTIES:
:ID:       13qoEn5WP3cmah4DF7xaboFU@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Thunder @ Baysox Thunder @ Baysox

Follow on MiLB First Pitch  https //stza.co/+vbwQ-2t

Shop  https //stza.co/+vbwQ-1a

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Thunder @ Baysox
END:VALARM
DTSTART:20180602T223500Z
DTEND:20180603T013500Z
UID:13qoEn5WP3cmah4DF7xaboFU@stanza.co
SUMMARY:Thunder @ Baysox
DESCRIPTION:Thunder @ Baysox\n\nFollow on MiLB First Pitch: https://stza.co/+vbwQ-2t\n\nShop: https://stza.co/+vbwQ-1a\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144602Z
LAST-MODIFIED:20180213T144602Z
TRANSP:OPAQUE
END:VEVENT
* Thunder @ Baysox
<2018-06-03 Sun 12:35-15:35>
:PROPERTIES:
:ID:       VSvD2pPFfn-Ws6jeGC6txSXU@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Thunder @ Baysox Thunder @ Baysox

Follow on MiLB First Pitch  https //stza.co/+vbx5-e

Shop  https //stza.co/+vbx5-3Z

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Thunder @ Baysox
END:VALARM
DTSTART:20180603T173500Z
DTEND:20180603T203500Z
UID:VSvD2pPFfn-Ws6jeGC6txSXU@stanza.co
SUMMARY:Thunder @ Baysox
DESCRIPTION:Thunder @ Baysox\n\nFollow on MiLB First Pitch: https://stza.co/+vbx5-e\n\nShop: https://stza.co/+vbx5-3Z\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144602Z
LAST-MODIFIED:20180213T144602Z
TRANSP:OPAQUE
END:VEVENT
* Thunder vs. Flying Squirrels
<2018-06-05 Tue 18:00-21:00>
:PROPERTIES:
:ID:       D2oIoljyBPYXZGhfKncyfdga@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Thunder vs. Flying Squirrels Thunder vs. Flying Squirrels

Follow on MiLB First Pitch  https //stza.co/+vbo0-3k

Shop  https //stza.co/+vbo0-3I

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Thunder vs. Flying Squirrels
END:VALARM
DTSTART:20180605T230000Z
DTEND:20180606T020000Z
UID:D2oIoljyBPYXZGhfKncyfdga@stanza.co
SUMMARY:Thunder vs. Flying Squirrels
DESCRIPTION:Thunder vs. Flying Squirrels\n\nFollow on MiLB First Pitch: https://stza.co/+vbo0-3k\n\nShop: https://stza.co/+vbo0-3I\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144602Z
LAST-MODIFIED:20180213T144602Z
TRANSP:OPAQUE
END:VEVENT
* Thunder vs. Flying Squirrels
<2018-06-06 Wed 18:00-21:00>
:PROPERTIES:
:ID:       vJth0o7HXgHwMCJSF5CjcRYG@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Thunder vs. Flying Squirrels Thunder vs. Flying Squirrels

Follow on MiLB First Pitch  https //stza.co/+vbO$-2x

Shop  https //stza.co/+vbO$-1L

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Thunder vs. Flying Squirrels
END:VALARM
DTSTART:20180606T230000Z
DTEND:20180607T020000Z
UID:vJth0o7HXgHwMCJSF5CjcRYG@stanza.co
SUMMARY:Thunder vs. Flying Squirrels
DESCRIPTION:Thunder vs. Flying Squirrels\n\nFollow on MiLB First Pitch: https://stza.co/+vbO$-2x\n\nShop: https://stza.co/+vbO$-1L\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144602Z
LAST-MODIFIED:20180213T144602Z
TRANSP:OPAQUE
END:VEVENT
* Thunder vs. Flying Squirrels
<2018-06-07 Thu 18:00-21:00>
:PROPERTIES:
:ID:       wTd3PX9R5nqkuxXUoOlcxMgB@stanza.co
:LOCATION: Fireworks Spectacular
:STATUS:   CONFIRMED
:END:

Thunder vs. Flying Squirrels Take in the awe-inspiring majesty of our post-game fireworks spectacular after the game right from your seat!

Follow on MiLB First Pitch  https //stza.co/+vbP7-K

Shop  https //stza.co/+vbP7-2y

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Thunder vs. Flying Squirrels
END:VALARM
DTSTART:20180607T230000Z
DTEND:20180608T020000Z
UID:wTd3PX9R5nqkuxXUoOlcxMgB@stanza.co
SUMMARY:Thunder vs. Flying Squirrels
DESCRIPTION:Take in the awe-inspiring majesty of our post-game fireworks spectacular after the game right from your seat!\n\nFollow on MiLB First Pitch: https://stza.co/+vbP7-K\n\nShop: https://stza.co/+vbP7-2y\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Fireworks Spectacular
STATUS:CONFIRMED
CREATED:20180213T144602Z
LAST-MODIFIED:20180213T144602Z
TRANSP:OPAQUE
END:VEVENT
* Thunder vs. Rumble Ponies
<2018-06-08 Fri 18:00-21:00>
:PROPERTIES:
:ID:       yQctggS6-ueZW299tbNflmKz@stanza.co
:LOCATION: Kevin Youkilis Bobblehead Giveaway
:STATUS:   CONFIRMED
:END:

Thunder vs. Rumble Ponies The fourth in a special 25th anniversary set of bobbleheads. Take home a bobblehead of one of the best 3B in franchise history!

Follow on MiLB First Pitch  https //stza.co/+vbPm-2A

Shop  https //stza.co/+vbPm-K

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Thunder vs. Rumble Ponies
END:VALARM
DTSTART:20180608T230000Z
DTEND:20180609T020000Z
UID:yQctggS6-ueZW299tbNflmKz@stanza.co
SUMMARY:Thunder vs. Rumble Ponies
DESCRIPTION:The fourth in a special 25th anniversary set of bobbleheads. Take home a bobblehead of one of the best 3B in franchise history!\n\nFollow on MiLB First Pitch: https://stza.co/+vbPm-2A\n\nShop: https://stza.co/+vbPm-K\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Kevin Youkilis Bobblehead Giveaway
STATUS:CONFIRMED
CREATED:20180213T144602Z
LAST-MODIFIED:20180213T144602Z
TRANSP:OPAQUE
END:VEVENT
* Thunder vs. Rumble Ponies
<2018-06-09 Sat 18:00-21:00>
:PROPERTIES:
:ID:       EJcwJnE1dWcjguWISYhxzjke@stanza.co
:LOCATION: Fireworks Spectacular
:STATUS:   CONFIRMED
:END:

Thunder vs. Rumble Ponies Take in the awe-inspiring majesty of our post-game fireworks spectacular after the game right from your seat!

Follow on MiLB First Pitch  https //stza.co/+vbPw-3C

Shop  https //stza.co/+vbPw-1o

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Thunder vs. Rumble Ponies
END:VALARM
DTSTART:20180609T230000Z
DTEND:20180610T020000Z
UID:EJcwJnE1dWcjguWISYhxzjke@stanza.co
SUMMARY:Thunder vs. Rumble Ponies
DESCRIPTION:Take in the awe-inspiring majesty of our post-game fireworks spectacular after the game right from your seat!\n\nFollow on MiLB First Pitch: https://stza.co/+vbPw-3C\n\nShop: https://stza.co/+vbPw-1o\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Fireworks Spectacular
STATUS:CONFIRMED
CREATED:20180213T144602Z
LAST-MODIFIED:20180213T144602Z
TRANSP:OPAQUE
END:VEVENT
* Thunder vs. Rumble Ponies
<2018-06-10 Sun 12:00-15:00>
:PROPERTIES:
:ID:       Z9vL38E866DSoAZYLVoQx0Ob@stanza.co
:LOCATION: Greg Bird Replica Jersey Giveaway
:STATUS:   CONFIRMED
:END:

Thunder vs. Rumble Ponies Celebrate some summer fun with our Greg Bird Replica Jersey Giveaway to the first 1,025 fans, ages 5-13!

Follow on MiLB First Pitch  https //stza.co/+vbPL-F

Shop  https //stza.co/+vbPL-1E

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Thunder vs. Rumble Ponies
END:VALARM
DTSTART:20180610T170000Z
DTEND:20180610T200000Z
UID:Z9vL38E866DSoAZYLVoQx0Ob@stanza.co
SUMMARY:Thunder vs. Rumble Ponies
DESCRIPTION:Celebrate some summer fun with our Greg Bird Replica Jersey Giveaway to the first 1,025 fans, ages 5-13!\n\nFollow on MiLB First Pitch: https://stza.co/+vbPL-F\n\nShop: https://stza.co/+vbPL-1E\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Greg Bird Replica Jersey Giveaway
STATUS:CONFIRMED
CREATED:20180213T144602Z
LAST-MODIFIED:20180213T144602Z
TRANSP:OPAQUE
END:VEVENT
* Thunder @ Baysox
<2018-06-12 Tue 17:35-20:35>
:PROPERTIES:
:ID:       ktgXZ1CH7-AS_jEhY7MjkCpU@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Thunder @ Baysox Thunder @ Baysox

Follow on MiLB First Pitch  https //stza.co/+vbxi-1f

Shop  https //stza.co/+vbxi-35

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Thunder @ Baysox
END:VALARM
DTSTART:20180612T223500Z
DTEND:20180613T013500Z
UID:ktgXZ1CH7-AS_jEhY7MjkCpU@stanza.co
SUMMARY:Thunder @ Baysox
DESCRIPTION:Thunder @ Baysox\n\nFollow on MiLB First Pitch: https://stza.co/+vbxi-1f\n\nShop: https://stza.co/+vbxi-35\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144602Z
LAST-MODIFIED:20180213T144602Z
TRANSP:OPAQUE
END:VEVENT
* Thunder @ Baysox
<2018-06-13 Wed 17:35-20:35>
:PROPERTIES:
:ID:       TNjZJwvN_AKffNP9gixEmwH9@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Thunder @ Baysox Thunder @ Baysox

Follow on MiLB First Pitch  https //stza.co/+vbxH-2k

Shop  https //stza.co/+vbxH-2p

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Thunder @ Baysox
END:VALARM
DTSTART:20180613T223500Z
DTEND:20180614T013500Z
UID:TNjZJwvN_AKffNP9gixEmwH9@stanza.co
SUMMARY:Thunder @ Baysox
DESCRIPTION:Thunder @ Baysox\n\nFollow on MiLB First Pitch: https://stza.co/+vbxH-2k\n\nShop: https://stza.co/+vbxH-2p\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144602Z
LAST-MODIFIED:20180213T144602Z
TRANSP:OPAQUE
END:VEVENT
* Thunder @ Baysox
<2018-06-14 Thu 17:35-20:35>
:PROPERTIES:
:ID:       9jWKiZO7gK0y9vSh_Hh-8mND@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Thunder @ Baysox Thunder @ Baysox

Follow on MiLB First Pitch  https //stza.co/+vbxW-1D

Shop  https //stza.co/+vbxW-3x

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Thunder @ Baysox
END:VALARM
DTSTART:20180614T223500Z
DTEND:20180615T013500Z
UID:9jWKiZO7gK0y9vSh_Hh-8mND@stanza.co
SUMMARY:Thunder @ Baysox
DESCRIPTION:Thunder @ Baysox\n\nFollow on MiLB First Pitch: https://stza.co/+vbxW-1D\n\nShop: https://stza.co/+vbxW-3x\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144602Z
LAST-MODIFIED:20180213T144602Z
TRANSP:OPAQUE
END:VEVENT
* Thunder vs. SeaWolves
<2018-06-15 Fri 18:00-21:00>
:PROPERTIES:
:ID:       Smjpm4GS_3gN9D_0hWtiSgDI@stanza.co
:LOCATION: Gary Sanchez Bobblehead Doll Giveaway
:STATUS:   CONFIRMED
:END:

Thunder vs. SeaWolves The fifth in a special 25th anniversary set of bobbleheads. Take home a bobblehead of one of the best 1B in franchise history!

Follow on MiLB First Pitch  https //stza.co/+vbPX-e

Shop  https //stza.co/+vbPX-3e

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Thunder vs. SeaWolves
END:VALARM
DTSTART:20180615T230000Z
DTEND:20180616T020000Z
UID:Smjpm4GS_3gN9D_0hWtiSgDI@stanza.co
SUMMARY:Thunder vs. SeaWolves
DESCRIPTION:The fifth in a special 25th anniversary set of bobbleheads. Take home a bobblehead of one of the best 1B in franchise history!\n\nFollow on MiLB First Pitch: https://stza.co/+vbPX-e\n\nShop: https://stza.co/+vbPX-3e\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Gary Sanchez Bobblehead Doll Giveaway
STATUS:CONFIRMED
CREATED:20180213T144602Z
LAST-MODIFIED:20180213T144602Z
TRANSP:OPAQUE
END:VEVENT
* Thunder vs. SeaWolves
<2018-06-16 Sat 18:00-21:00>
:PROPERTIES:
:ID:       kd8pAxBwZfknEmZsawqxJgc6@stanza.co
:LOCATION: Fireworks Spectacular
:STATUS:   CONFIRMED
:END:

Thunder vs. SeaWolves Take in the awe-inspiring majesty of our post-game fireworks spectacular after the game right from your seat!

Follow on MiLB First Pitch  https //stza.co/+vbQ6-3O

Shop  https //stza.co/+vbQ6-1y

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Thunder vs. SeaWolves
END:VALARM
DTSTART:20180616T230000Z
DTEND:20180617T020000Z
UID:kd8pAxBwZfknEmZsawqxJgc6@stanza.co
SUMMARY:Thunder vs. SeaWolves
DESCRIPTION:Take in the awe-inspiring majesty of our post-game fireworks spectacular after the game right from your seat!\n\nFollow on MiLB First Pitch: https://stza.co/+vbQ6-3O\n\nShop: https://stza.co/+vbQ6-1y\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Fireworks Spectacular
STATUS:CONFIRMED
CREATED:20180213T144602Z
LAST-MODIFIED:20180213T144602Z
TRANSP:OPAQUE
END:VEVENT
* Thunder vs. SeaWolves
<2018-06-17 Sun 12:00-15:00>
:PROPERTIES:
:ID:       JNvze6FWqsKC3lZmSbpZOsM9@stanza.co
:LOCATION: Father's Day 25th Anniversary Koozie
:STATUS:   CONFIRMED
:END:

Thunder vs. SeaWolves Celebrate Father's Day with a special 25th Anniversary koozie giveaway for the first 1,025 fans ages 18 and older!

Follow on MiLB First Pitch  https //stza.co/+vbQg-1e

Shop  https //stza.co/+vbQg-1H

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Thunder vs. SeaWolves
END:VALARM
DTSTART:20180617T170000Z
DTEND:20180617T200000Z
UID:JNvze6FWqsKC3lZmSbpZOsM9@stanza.co
SUMMARY:Thunder vs. SeaWolves
DESCRIPTION:Celebrate Father's Day with a special 25th Anniversary koozie giveaway for the first 1,025 fans ages 18 and older!\n\nFollow on MiLB First Pitch: https://stza.co/+vbQg-1e\n\nShop: https://stza.co/+vbQg-1H\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Father's Day 25th Anniversary Koozie
STATUS:CONFIRMED
CREATED:20180213T144602Z
LAST-MODIFIED:20180213T144602Z
TRANSP:OPAQUE
END:VEVENT
* Thunder vs. Rumble Ponies
<2018-06-19 Tue 18:00-21:00>
:PROPERTIES:
:ID:       gCharpRkxBqMzY94QwhlJRwn@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Thunder vs. Rumble Ponies Thunder vs. Rumble Ponies

Follow on MiLB First Pitch  https //stza.co/+vbQs-r

Shop  https //stza.co/+vbQs-y

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Thunder vs. Rumble Ponies
END:VALARM
DTSTART:20180619T230000Z
DTEND:20180620T020000Z
UID:gCharpRkxBqMzY94QwhlJRwn@stanza.co
SUMMARY:Thunder vs. Rumble Ponies
DESCRIPTION:Thunder vs. Rumble Ponies\n\nFollow on MiLB First Pitch: https://stza.co/+vbQs-r\n\nShop: https://stza.co/+vbQs-y\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144602Z
LAST-MODIFIED:20180213T144602Z
TRANSP:OPAQUE
END:VEVENT
* Thunder vs. Rumble Ponies
<2018-06-20 Wed 18:00-21:00>
:PROPERTIES:
:ID:       LEbI3Ef9cIqaVxwnpIXkWpKT@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Thunder vs. Rumble Ponies Thunder vs. Rumble Ponies

Follow on MiLB First Pitch  https //stza.co/+vbQD-2U

Shop  https //stza.co/+vbQD-D

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Thunder vs. Rumble Ponies
END:VALARM
DTSTART:20180620T230000Z
DTEND:20180621T020000Z
UID:LEbI3Ef9cIqaVxwnpIXkWpKT@stanza.co
SUMMARY:Thunder vs. Rumble Ponies
DESCRIPTION:Thunder vs. Rumble Ponies\n\nFollow on MiLB First Pitch: https://stza.co/+vbQD-2U\n\nShop: https://stza.co/+vbQD-D\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144602Z
LAST-MODIFIED:20180213T144602Z
TRANSP:OPAQUE
END:VEVENT
* Thunder vs. Rumble Ponies
<2018-06-21 Thu 18:00-21:00>
:PROPERTIES:
:ID:       dsV-EmtJCfH6kNhx4BV3HaG1@stanza.co
:LOCATION: Fireworks Spectacular
:STATUS:   CONFIRMED
:END:

Thunder vs. Rumble Ponies Take in the awe-inspiring majesty of our post-game fireworks spectacular after the game right from your seat!

Nominate a local hometown hero and take home a special card set commemorating those who do great in our community!

Follow on MiLB First Pitch  https //stza.co/+vbQO-1s

Shop  https //stza.co/+vbQO-1f

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Thunder vs. Rumble Ponies
END:VALARM
DTSTART:20180621T230000Z
DTEND:20180622T020000Z
UID:dsV-EmtJCfH6kNhx4BV3HaG1@stanza.co
SUMMARY:Thunder vs. Rumble Ponies
DESCRIPTION:Take in the awe-inspiring majesty of our post-game fireworks spectacular after the game right from your seat!\n\nNominate a local hometown hero and take home a special card set commemorating those who do great in our community!\n\nFollow on MiLB First Pitch: https://stza.co/+vbQO-1s\n\nShop: https://stza.co/+vbQO-1f\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Fireworks Spectacular
STATUS:CONFIRMED
CREATED:20180213T144602Z
LAST-MODIFIED:20180213T144602Z
TRANSP:OPAQUE
END:VEVENT
* Thunder @ Sea Dogs
<2018-06-22 Fri 18:00-21:00>
:PROPERTIES:
:ID:       lS7o2HbK8G3VNabtGZzP75SM@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Thunder @ Sea Dogs Thunder @ Sea Dogs

Buy tickets here  https //stza.co/~vbFl

Follow on MiLB First Pitch  https //stza.co/+vbFl-32

Shop  https //stza.co/+vbFl-1Y

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Thunder @ Sea Dogs
END:VALARM
DTSTART:20180622T230000Z
DTEND:20180623T020000Z
UID:lS7o2HbK8G3VNabtGZzP75SM@stanza.co
SUMMARY:Thunder @ Sea Dogs
DESCRIPTION:Thunder @ Sea Dogs\n\nBuy tickets here: https://stza.co/~vbFl\n\nFollow on MiLB First Pitch: https://stza.co/+vbFl-32\n\nShop: https://stza.co/+vbFl-1Y\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144602Z
LAST-MODIFIED:20180213T144602Z
TRANSP:OPAQUE
END:VEVENT
* Thunder @ Sea Dogs
<2018-06-23 Sat 17:00-20:00>
:PROPERTIES:
:ID:       pw6WkG4nhFv8e2yv1rCT-F1R@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Thunder @ Sea Dogs Thunder @ Sea Dogs

Buy tickets here  https //stza.co/~vbFM

Follow on MiLB First Pitch  https //stza.co/+vbFM-2f

Shop  https //stza.co/+vbFM-m

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Thunder @ Sea Dogs
END:VALARM
DTSTART:20180623T220000Z
DTEND:20180624T010000Z
UID:pw6WkG4nhFv8e2yv1rCT-F1R@stanza.co
SUMMARY:Thunder @ Sea Dogs
DESCRIPTION:Thunder @ Sea Dogs\n\nBuy tickets here: https://stza.co/~vbFM\n\nFollow on MiLB First Pitch: https://stza.co/+vbFM-2f\n\nShop: https://stza.co/+vbFM-m\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144602Z
LAST-MODIFIED:20180213T144602Z
TRANSP:OPAQUE
END:VEVENT
* Thunder @ Sea Dogs
<2018-06-24 Sun 12:00-15:00>
:PROPERTIES:
:ID:       DEDhJ9LYfZbOtNeL8_nYAuJn@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Thunder @ Sea Dogs Thunder @ Sea Dogs

Buy tickets here  https //stza.co/~vbG2

Follow on MiLB First Pitch  https //stza.co/+vbG2-12

Shop  https //stza.co/+vbG2-3m

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Thunder @ Sea Dogs
END:VALARM
DTSTART:20180624T170000Z
DTEND:20180624T200000Z
UID:DEDhJ9LYfZbOtNeL8_nYAuJn@stanza.co
SUMMARY:Thunder @ Sea Dogs
DESCRIPTION:Thunder @ Sea Dogs\n\nBuy tickets here: https://stza.co/~vbG2\n\nFollow on MiLB First Pitch: https://stza.co/+vbG2-12\n\nShop: https://stza.co/+vbG2-3m\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144602Z
LAST-MODIFIED:20180213T144602Z
TRANSP:OPAQUE
END:VEVENT
* Thunder @ Rumble Ponies
<2018-06-25 Mon 17:35-20:35>
:PROPERTIES:
:ID:       dBC8oG2Qi-GSeKVWAGs-0oqu@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Thunder @ Rumble Ponies Thunder @ Rumble Ponies

Follow on MiLB First Pitch  https //stza.co/+vbut-b

Shop  https //stza.co/+vbut-2q

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Thunder @ Rumble Ponies
END:VALARM
DTSTART:20180625T223500Z
DTEND:20180626T013500Z
UID:dBC8oG2Qi-GSeKVWAGs-0oqu@stanza.co
SUMMARY:Thunder @ Rumble Ponies
DESCRIPTION:Thunder @ Rumble Ponies\n\nFollow on MiLB First Pitch: https://stza.co/+vbut-b\n\nShop: https://stza.co/+vbut-2q\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144602Z
LAST-MODIFIED:20180213T144602Z
TRANSP:OPAQUE
END:VEVENT
* Thunder @ Rumble Ponies
<2018-06-26 Tue 17:35-20:35>
:PROPERTIES:
:ID:       NX8Nw6QkyWdwplBbMcyKJKoG@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Thunder @ Rumble Ponies Thunder @ Rumble Ponies

Follow on MiLB First Pitch  https //stza.co/+vbuK-2j

Shop  https //stza.co/+vbuK-3P

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Thunder @ Rumble Ponies
END:VALARM
DTSTART:20180626T223500Z
DTEND:20180627T013500Z
UID:NX8Nw6QkyWdwplBbMcyKJKoG@stanza.co
SUMMARY:Thunder @ Rumble Ponies
DESCRIPTION:Thunder @ Rumble Ponies\n\nFollow on MiLB First Pitch: https://stza.co/+vbuK-2j\n\nShop: https://stza.co/+vbuK-3P\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144602Z
LAST-MODIFIED:20180213T144602Z
TRANSP:OPAQUE
END:VEVENT
* Thunder @ Rumble Ponies
<2018-06-27 Wed 17:35-20:35>
:PROPERTIES:
:ID:       ydbncVyzR4QluWT0iqov2_Yu@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Thunder @ Rumble Ponies Thunder @ Rumble Ponies

Follow on MiLB First Pitch  https //stza.co/+vbv1-2I

Shop  https //stza.co/+vbv1-29

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Thunder @ Rumble Ponies
END:VALARM
DTSTART:20180627T223500Z
DTEND:20180628T013500Z
UID:ydbncVyzR4QluWT0iqov2_Yu@stanza.co
SUMMARY:Thunder @ Rumble Ponies
DESCRIPTION:Thunder @ Rumble Ponies\n\nFollow on MiLB First Pitch: https://stza.co/+vbv1-2I\n\nShop: https://stza.co/+vbv1-29\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144602Z
LAST-MODIFIED:20180213T144602Z
TRANSP:OPAQUE
END:VEVENT
* Thunder @ Rumble Ponies
<2018-06-28 Thu 17:35-20:35>
:PROPERTIES:
:ID:       x5egdwju0G_O9A0qTNApYVGZ@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Thunder @ Rumble Ponies Thunder @ Rumble Ponies

Follow on MiLB First Pitch  https //stza.co/+vbvg-1A

Shop  https //stza.co/+vbvg-C

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Thunder @ Rumble Ponies
END:VALARM
DTSTART:20180628T223500Z
DTEND:20180629T013500Z
UID:x5egdwju0G_O9A0qTNApYVGZ@stanza.co
SUMMARY:Thunder @ Rumble Ponies
DESCRIPTION:Thunder @ Rumble Ponies\n\nFollow on MiLB First Pitch: https://stza.co/+vbvg-1A\n\nShop: https://stza.co/+vbvg-C\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144602Z
LAST-MODIFIED:20180213T144602Z
TRANSP:OPAQUE
END:VEVENT
* Thunder vs. Fisher Cats
<2018-06-29 Fri 18:00-21:00>
:PROPERTIES:
:ID:       0P-0ronD-QpV9TawF4Vov4a5@stanza.co
:LOCATION: David Robertson Bobblehead Giveaway
:STATUS:   CONFIRMED
:END:

Thunder vs. Fisher Cats The sixth in a special 25th anniversary set of bobbleheads. Take home a bobblehead of one of the best P in franchise history!

Follow on MiLB First Pitch  https //stza.co/+vbQY-T

Shop  https //stza.co/+vbQY-2i

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Thunder vs. Fisher Cats
END:VALARM
DTSTART:20180629T230000Z
DTEND:20180630T020000Z
UID:0P-0ronD-QpV9TawF4Vov4a5@stanza.co
SUMMARY:Thunder vs. Fisher Cats
DESCRIPTION:The sixth in a special 25th anniversary set of bobbleheads. Take home a bobblehead of one of the best P in franchise history!\n\nFollow on MiLB First Pitch: https://stza.co/+vbQY-T\n\nShop: https://stza.co/+vbQY-2i\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:David Robertson Bobblehead Giveaway
STATUS:CONFIRMED
CREATED:20180213T144602Z
LAST-MODIFIED:20180213T144602Z
TRANSP:OPAQUE
END:VEVENT
* Thunder vs. Fisher Cats
<2018-06-30 Sat 18:00-21:00>
:PROPERTIES:
:ID:       xv6Y_QMRgFIcPzoED2Vy3tO0@stanza.co
:LOCATION: Fireworks Spectacular
:STATUS:   CONFIRMED
:END:

Thunder vs. Fisher Cats Take in the awe-inspiring majesty of our post-game fireworks spectacular after the game right from your seat!

Follow on MiLB First Pitch  https //stza.co/+vbR9-3t

Shop  https //stza.co/+vbR9-R

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Thunder vs. Fisher Cats
END:VALARM
DTSTART:20180630T230000Z
DTEND:20180701T020000Z
UID:xv6Y_QMRgFIcPzoED2Vy3tO0@stanza.co
SUMMARY:Thunder vs. Fisher Cats
DESCRIPTION:Take in the awe-inspiring majesty of our post-game fireworks spectacular after the game right from your seat!\n\nFollow on MiLB First Pitch: https://stza.co/+vbR9-3t\n\nShop: https://stza.co/+vbR9-R\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Fireworks Spectacular
STATUS:CONFIRMED
CREATED:20180213T144602Z
LAST-MODIFIED:20180213T144602Z
TRANSP:OPAQUE
END:VEVENT
* Thunder vs. Fisher Cats
<2018-07-01 Sun 12:00-15:00>
:PROPERTIES:
:ID:       a24o6URJrLOdO7-d6YXRDXQb@stanza.co
:LOCATION: Foam Gavel
:STATUS:   CONFIRMED
:END:

Thunder vs. Fisher Cats All Rise! The first 1,025 fans ages 5-13 will receive a foam gavel as we honor Aaron Judge!

Follow on MiLB First Pitch  https //stza.co/+vbRm-36

Shop  https //stza.co/+vbRm-3R

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Thunder vs. Fisher Cats
END:VALARM
DTSTART:20180701T170000Z
DTEND:20180701T200000Z
UID:a24o6URJrLOdO7-d6YXRDXQb@stanza.co
SUMMARY:Thunder vs. Fisher Cats
DESCRIPTION:All Rise! The first 1,025 fans ages 5-13 will receive a foam gavel as we honor Aaron Judge!\n\nFollow on MiLB First Pitch: https://stza.co/+vbRm-36\n\nShop: https://stza.co/+vbRm-3R\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Foam Gavel
STATUS:CONFIRMED
CREATED:20180213T144602Z
LAST-MODIFIED:20180213T144602Z
TRANSP:OPAQUE
END:VEVENT
* Thunder vs. Fisher Cats
<2018-07-02 Mon 18:00-21:00>
:PROPERTIES:
:ID:       S3oRzwFIqCM1V6t4aU-xWudu@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Thunder vs. Fisher Cats Thunder vs. Fisher Cats

Follow on MiLB First Pitch  https //stza.co/+vbRy-2P

Shop  https //stza.co/+vbRy-1v

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Thunder vs. Fisher Cats
END:VALARM
DTSTART:20180702T230000Z
DTEND:20180703T020000Z
UID:S3oRzwFIqCM1V6t4aU-xWudu@stanza.co
SUMMARY:Thunder vs. Fisher Cats
DESCRIPTION:Thunder vs. Fisher Cats\n\nFollow on MiLB First Pitch: https://stza.co/+vbRy-2P\n\nShop: https://stza.co/+vbRy-1v\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144602Z
LAST-MODIFIED:20180213T144602Z
TRANSP:OPAQUE
END:VEVENT
* Thunder vs. Fisher Cats
<2018-07-03 Tue 18:00-21:00>
:PROPERTIES:
:ID:       6LwJ9QfTjnn9ZHg4yKi1XuSV@stanza.co
:LOCATION: Fireworks Spectacular
:STATUS:   CONFIRMED
:END:

Thunder vs. Fisher Cats Take in the awe-inspiring majesty of our post-game fireworks spectacular after the game right from your seat!

Follow on MiLB First Pitch  https //stza.co/+vbRG-3a

Shop  https //stza.co/+vbRG-6

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Thunder vs. Fisher Cats
END:VALARM
DTSTART:20180703T230000Z
DTEND:20180704T020000Z
UID:6LwJ9QfTjnn9ZHg4yKi1XuSV@stanza.co
SUMMARY:Thunder vs. Fisher Cats
DESCRIPTION:Take in the awe-inspiring majesty of our post-game fireworks spectacular after the game right from your seat!\n\nFollow on MiLB First Pitch: https://stza.co/+vbRG-3a\n\nShop: https://stza.co/+vbRG-6\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Fireworks Spectacular
STATUS:CONFIRMED
CREATED:20180213T144602Z
LAST-MODIFIED:20180213T144602Z
TRANSP:OPAQUE
END:VEVENT
* Thunder @ Curve
<2018-07-04 Wed 18:00-21:00>
:PROPERTIES:
:ID:       1FRDFcoywMUAMljVbgoj1akL@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Thunder @ Curve Thunder @ Curve

Follow on MiLB First Pitch  https //stza.co/+vbsa-13

Shop  https //stza.co/+vbsa-2W

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Thunder @ Curve
END:VALARM
DTSTART:20180704T230000Z
DTEND:20180705T020000Z
UID:1FRDFcoywMUAMljVbgoj1akL@stanza.co
SUMMARY:Thunder @ Curve
DESCRIPTION:Thunder @ Curve\n\nFollow on MiLB First Pitch: https://stza.co/+vbsa-13\n\nShop: https://stza.co/+vbsa-2W\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144602Z
LAST-MODIFIED:20180213T144602Z
TRANSP:OPAQUE
END:VEVENT
* Thunder @ Curve
<2018-07-05 Thu 18:00-21:00>
:PROPERTIES:
:ID:       4kNDC13TFspifCjRWrTA0p_y@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Thunder @ Curve Thunder @ Curve

Follow on MiLB First Pitch  https //stza.co/+vbsl-3B

Shop  https //stza.co/+vbsl-35

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Thunder @ Curve
END:VALARM
DTSTART:20180705T230000Z
DTEND:20180706T020000Z
UID:4kNDC13TFspifCjRWrTA0p_y@stanza.co
SUMMARY:Thunder @ Curve
DESCRIPTION:Thunder @ Curve\n\nFollow on MiLB First Pitch: https://stza.co/+vbsl-3B\n\nShop: https://stza.co/+vbsl-35\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144602Z
LAST-MODIFIED:20180213T144602Z
TRANSP:OPAQUE
END:VEVENT
* Thunder @ Curve
<2018-07-06 Fri 18:00-21:00>
:PROPERTIES:
:ID:       T27K57KYOvP7vjYj-3QCraXm@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Thunder @ Curve Thunder @ Curve

Follow on MiLB First Pitch  https //stza.co/+vbsE-W

Shop  https //stza.co/+vbsE-b

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Thunder @ Curve
END:VALARM
DTSTART:20180706T230000Z
DTEND:20180707T020000Z
UID:T27K57KYOvP7vjYj-3QCraXm@stanza.co
SUMMARY:Thunder @ Curve
DESCRIPTION:Thunder @ Curve\n\nFollow on MiLB First Pitch: https://stza.co/+vbsE-W\n\nShop: https://stza.co/+vbsE-b\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144602Z
LAST-MODIFIED:20180213T144602Z
TRANSP:OPAQUE
END:VEVENT
* Thunder @ Curve
<2018-07-07 Sat 17:00-20:00>
:PROPERTIES:
:ID:       0uhrukiFPQ5mCHOo9dVUr1wv@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Thunder @ Curve Thunder @ Curve

Follow on MiLB First Pitch  https //stza.co/+vbsW-2_

Shop  https //stza.co/+vbsW-2V

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Thunder @ Curve
END:VALARM
DTSTART:20180707T220000Z
DTEND:20180708T010000Z
UID:0uhrukiFPQ5mCHOo9dVUr1wv@stanza.co
SUMMARY:Thunder @ Curve
DESCRIPTION:Thunder @ Curve\n\nFollow on MiLB First Pitch: https://stza.co/+vbsW-2_\n\nShop: https://stza.co/+vbsW-2V\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144602Z
LAST-MODIFIED:20180213T144602Z
TRANSP:OPAQUE
END:VEVENT
* Thunder @ Curve
<2018-07-08 Sun 13:00-16:00>
:PROPERTIES:
:ID:       qtUsO6S5fo2n2lEX7kti2dw1@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Thunder @ Curve Thunder @ Curve

Follow on MiLB First Pitch  https //stza.co/+vbt8-11

Shop  https //stza.co/+vbt8-3M

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Thunder @ Curve
END:VALARM
DTSTART:20180708T180000Z
DTEND:20180708T210000Z
UID:qtUsO6S5fo2n2lEX7kti2dw1@stanza.co
SUMMARY:Thunder @ Curve
DESCRIPTION:Thunder @ Curve\n\nFollow on MiLB First Pitch: https://stza.co/+vbt8-11\n\nShop: https://stza.co/+vbt8-3M\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144602Z
LAST-MODIFIED:20180213T144602Z
TRANSP:OPAQUE
END:VEVENT
* Thunder vs. Flying Squirrels
<2018-07-12 Thu 18:00-21:00>
:PROPERTIES:
:ID:       LdHRyU_Pu9qMVQ81dFg67hpH@stanza.co
:LOCATION: Fireworks Spectacular
:STATUS:   CONFIRMED
:END:

Thunder vs. Flying Squirrels Take in the awe-inspiring majesty of our post-game fireworks spectacular after the game right from your seat!

Follow on MiLB First Pitch  https //stza.co/+vbRS-2$

Shop  https //stza.co/+vbRS-3C

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Thunder vs. Flying Squirrels
END:VALARM
DTSTART:20180712T230000Z
DTEND:20180713T020000Z
UID:LdHRyU_Pu9qMVQ81dFg67hpH@stanza.co
SUMMARY:Thunder vs. Flying Squirrels
DESCRIPTION:Take in the awe-inspiring majesty of our post-game fireworks spectacular after the game right from your seat!\n\nFollow on MiLB First Pitch: https://stza.co/+vbRS-2$\n\nShop: https://stza.co/+vbRS-3C\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Fireworks Spectacular
STATUS:CONFIRMED
CREATED:20180213T144602Z
LAST-MODIFIED:20180213T144602Z
TRANSP:OPAQUE
END:VEVENT
* Thunder vs. Flying Squirrels
<2018-07-13 Fri 18:00-21:00>
:PROPERTIES:
:ID:       iE3GeLbRJu94V_2I-R1IlGZo@stanza.co
:LOCATION: Brett Gardner Bobblehead Giveaway
:STATUS:   CONFIRMED
:END:

Thunder vs. Flying Squirrels The seventh in a special 25th anniversary set of bobbleheads. Take home a bobblehead of one of the best OF in franchise history!

Follow on MiLB First Pitch  https //stza.co/+vbS1-23

Shop  https //stza.co/+vbS1-3D

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Thunder vs. Flying Squirrels
END:VALARM
DTSTART:20180713T230000Z
DTEND:20180714T020000Z
UID:iE3GeLbRJu94V_2I-R1IlGZo@stanza.co
SUMMARY:Thunder vs. Flying Squirrels
DESCRIPTION:The seventh in a special 25th anniversary set of bobbleheads. Take home a bobblehead of one of the best OF in franchise history!\n\nFollow on MiLB First Pitch: https://stza.co/+vbS1-23\n\nShop: https://stza.co/+vbS1-3D\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Brett Gardner Bobblehead Giveaway
STATUS:CONFIRMED
CREATED:20180213T144602Z
LAST-MODIFIED:20180213T144602Z
TRANSP:OPAQUE
END:VEVENT
* Thunder vs. Flying Squirrels
<2018-07-14 Sat 18:00-21:00>
:PROPERTIES:
:ID:       jAYpPdYLmS66l3F1hUxZRQA5@stanza.co
:LOCATION: Fireworks Spectacular
:STATUS:   CONFIRMED
:END:

Thunder vs. Flying Squirrels Take in the awe-inspiring majesty of our post-game fireworks spectacular after the game right from your seat!

Follow on MiLB First Pitch  https //stza.co/+vbSc-3Z

Shop  https //stza.co/+vbSc-Y

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Thunder vs. Flying Squirrels
END:VALARM
DTSTART:20180714T230000Z
DTEND:20180715T020000Z
UID:jAYpPdYLmS66l3F1hUxZRQA5@stanza.co
SUMMARY:Thunder vs. Flying Squirrels
DESCRIPTION:Take in the awe-inspiring majesty of our post-game fireworks spectacular after the game right from your seat!\n\nFollow on MiLB First Pitch: https://stza.co/+vbSc-3Z\n\nShop: https://stza.co/+vbSc-Y\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Fireworks Spectacular
STATUS:CONFIRMED
CREATED:20180213T144602Z
LAST-MODIFIED:20180213T144602Z
TRANSP:OPAQUE
END:VEVENT
* Thunder vs. Flying Squirrels
<2018-07-15 Sun 12:00-15:00>
:PROPERTIES:
:ID:       b39WLzX28LUKzzQ9f375SHxj@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Thunder vs. Flying Squirrels Thunder vs. Flying Squirrels

Follow on MiLB First Pitch  https //stza.co/+vbSv-2a

Shop  https //stza.co/+vbSv-3t

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Thunder vs. Flying Squirrels
END:VALARM
DTSTART:20180715T170000Z
DTEND:20180715T200000Z
UID:b39WLzX28LUKzzQ9f375SHxj@stanza.co
SUMMARY:Thunder vs. Flying Squirrels
DESCRIPTION:Thunder vs. Flying Squirrels\n\nFollow on MiLB First Pitch: https://stza.co/+vbSv-2a\n\nShop: https://stza.co/+vbSv-3t\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144602Z
LAST-MODIFIED:20180213T144602Z
TRANSP:OPAQUE
END:VEVENT
* Thunder @ Fisher Cats
<2018-07-16 Mon 18:05-21:05>
:PROPERTIES:
:ID:       z6YvQBKKA7xW0j7UjsRmhzYB@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Thunder @ Fisher Cats Thunder @ Fisher Cats

Follow on MiLB First Pitch  https //stza.co/+vbDL-T

Shop  https //stza.co/+vbDL-E

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Thunder @ Fisher Cats
END:VALARM
DTSTART:20180716T230500Z
DTEND:20180717T020500Z
UID:z6YvQBKKA7xW0j7UjsRmhzYB@stanza.co
SUMMARY:Thunder @ Fisher Cats
DESCRIPTION:Thunder @ Fisher Cats\n\nFollow on MiLB First Pitch: https://stza.co/+vbDL-T\n\nShop: https://stza.co/+vbDL-E\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144602Z
LAST-MODIFIED:20180213T144602Z
TRANSP:OPAQUE
END:VEVENT
* Thunder @ Fisher Cats
<2018-07-17 Tue 18:05-21:05>
:PROPERTIES:
:ID:       gjHyDwwUvdsOK8fZ3oFZiKsj@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Thunder @ Fisher Cats Thunder @ Fisher Cats

Follow on MiLB First Pitch  https //stza.co/+vbD$-2H

Shop  https //stza.co/+vbD$-28

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Thunder @ Fisher Cats
END:VALARM
DTSTART:20180717T230500Z
DTEND:20180718T020500Z
UID:gjHyDwwUvdsOK8fZ3oFZiKsj@stanza.co
SUMMARY:Thunder @ Fisher Cats
DESCRIPTION:Thunder @ Fisher Cats\n\nFollow on MiLB First Pitch: https://stza.co/+vbD$-2H\n\nShop: https://stza.co/+vbD$-28\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144602Z
LAST-MODIFIED:20180213T144602Z
TRANSP:OPAQUE
END:VEVENT
* Thunder @ Fisher Cats
<2018-07-18 Wed 11:05-14:05>
:PROPERTIES:
:ID:       EG64OwcrpXevRTB2JR38M-pZ@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Thunder @ Fisher Cats Thunder @ Fisher Cats

Follow on MiLB First Pitch  https //stza.co/+vbEf-1d

Shop  https //stza.co/+vbEf-13

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Thunder @ Fisher Cats
END:VALARM
DTSTART:20180718T160500Z
DTEND:20180718T190500Z
UID:EG64OwcrpXevRTB2JR38M-pZ@stanza.co
SUMMARY:Thunder @ Fisher Cats
DESCRIPTION:Thunder @ Fisher Cats\n\nFollow on MiLB First Pitch: https://stza.co/+vbEf-1d\n\nShop: https://stza.co/+vbEf-13\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144602Z
LAST-MODIFIED:20180213T144602Z
TRANSP:OPAQUE
END:VEVENT
* Thunder @ Rumble Ponies
<2018-07-19 Thu 17:35-20:35>
:PROPERTIES:
:ID:       NluTuKKYzzoc8cDi60hZl5eW@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Thunder @ Rumble Ponies Thunder @ Rumble Ponies

Follow on MiLB First Pitch  https //stza.co/+vbvz-P

Shop  https //stza.co/+vbvz-2d

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Thunder @ Rumble Ponies
END:VALARM
DTSTART:20180719T223500Z
DTEND:20180720T013500Z
UID:NluTuKKYzzoc8cDi60hZl5eW@stanza.co
SUMMARY:Thunder @ Rumble Ponies
DESCRIPTION:Thunder @ Rumble Ponies\n\nFollow on MiLB First Pitch: https://stza.co/+vbvz-P\n\nShop: https://stza.co/+vbvz-2d\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144602Z
LAST-MODIFIED:20180213T144602Z
TRANSP:OPAQUE
END:VEVENT
* Thunder @ Rumble Ponies
<2018-07-20 Fri 18:05-21:05>
:PROPERTIES:
:ID:       bemJffA59fW9vCo5M3eVbl3O@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Thunder @ Rumble Ponies Thunder @ Rumble Ponies

Follow on MiLB First Pitch  https //stza.co/+vbvP-3y

Shop  https //stza.co/+vbvP-10

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Thunder @ Rumble Ponies
END:VALARM
DTSTART:20180720T230500Z
DTEND:20180721T020500Z
UID:bemJffA59fW9vCo5M3eVbl3O@stanza.co
SUMMARY:Thunder @ Rumble Ponies
DESCRIPTION:Thunder @ Rumble Ponies\n\nFollow on MiLB First Pitch: https://stza.co/+vbvP-3y\n\nShop: https://stza.co/+vbvP-10\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144602Z
LAST-MODIFIED:20180213T144602Z
TRANSP:OPAQUE
END:VEVENT
* Thunder @ Rumble Ponies
<2018-07-21 Sat 17:05-20:05>
:PROPERTIES:
:ID:       ngIv2Lm0OjGXsMhuNEOSAmoT@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Thunder @ Rumble Ponies Thunder @ Rumble Ponies

Follow on MiLB First Pitch  https //stza.co/+vbw4-D

Shop  https //stza.co/+vbw4-1Y

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Thunder @ Rumble Ponies
END:VALARM
DTSTART:20180721T220500Z
DTEND:20180722T010500Z
UID:ngIv2Lm0OjGXsMhuNEOSAmoT@stanza.co
SUMMARY:Thunder @ Rumble Ponies
DESCRIPTION:Thunder @ Rumble Ponies\n\nFollow on MiLB First Pitch: https://stza.co/+vbw4-D\n\nShop: https://stza.co/+vbw4-1Y\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144602Z
LAST-MODIFIED:20180213T144602Z
TRANSP:OPAQUE
END:VEVENT
* Thunder @ Rumble Ponies
<2018-07-22 Sun 13:05-16:05>
:PROPERTIES:
:ID:       od-GzKX_gsv5gdu49K2ur1UZ@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Thunder @ Rumble Ponies Thunder @ Rumble Ponies

Follow on MiLB First Pitch  https //stza.co/+vbwk-1S

Shop  https //stza.co/+vbwk-1w

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Thunder @ Rumble Ponies
END:VALARM
DTSTART:20180722T180500Z
DTEND:20180722T210500Z
UID:od-GzKX_gsv5gdu49K2ur1UZ@stanza.co
SUMMARY:Thunder @ Rumble Ponies
DESCRIPTION:Thunder @ Rumble Ponies\n\nFollow on MiLB First Pitch: https://stza.co/+vbwk-1S\n\nShop: https://stza.co/+vbwk-1w\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144602Z
LAST-MODIFIED:20180213T144602Z
TRANSP:OPAQUE
END:VEVENT
* Thunder vs. Yard Goats
<2018-07-23 Mon 18:00-21:00>
:PROPERTIES:
:ID:       zQOFwgoaL5zY7fY2w6HXhgOp@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Thunder vs. Yard Goats Thunder vs. Yard Goats

Follow on MiLB First Pitch  https //stza.co/+vbSG-3b

Shop  https //stza.co/+vbSG-P

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Thunder vs. Yard Goats
END:VALARM
DTSTART:20180723T230000Z
DTEND:20180724T020000Z
UID:zQOFwgoaL5zY7fY2w6HXhgOp@stanza.co
SUMMARY:Thunder vs. Yard Goats
DESCRIPTION:Thunder vs. Yard Goats\n\nFollow on MiLB First Pitch: https://stza.co/+vbSG-3b\n\nShop: https://stza.co/+vbSG-P\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144602Z
LAST-MODIFIED:20180213T144602Z
TRANSP:OPAQUE
END:VEVENT
* Thunder vs. Yard Goats
<2018-07-24 Tue 18:00-21:00>
:PROPERTIES:
:ID:       RbIpZzysHtFj6goIi6n4TKG0@stanza.co
:LOCATION: Austin Jackson Bobblehead Giveaway
:STATUS:   CONFIRMED
:END:

Thunder vs. Yard Goats The eighth in a special 25th anniversary set of bobbleheads. Take home a bobblehead of one of the best OF in franchise history!

Follow on MiLB First Pitch  https //stza.co/+vbSQ-6

Shop  https //stza.co/+vbSQ-2M

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Thunder vs. Yard Goats
END:VALARM
DTSTART:20180724T230000Z
DTEND:20180725T020000Z
UID:RbIpZzysHtFj6goIi6n4TKG0@stanza.co
SUMMARY:Thunder vs. Yard Goats
DESCRIPTION:The eighth in a special 25th anniversary set of bobbleheads. Take home a bobblehead of one of the best OF in franchise history!\n\nFollow on MiLB First Pitch: https://stza.co/+vbSQ-6\n\nShop: https://stza.co/+vbSQ-2M\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Austin Jackson Bobblehead Giveaway
STATUS:CONFIRMED
CREATED:20180213T144602Z
LAST-MODIFIED:20180213T144602Z
TRANSP:OPAQUE
END:VEVENT
* Thunder vs. Yard Goats
<2018-07-25 Wed 10:00-13:00>
:PROPERTIES:
:ID:       MUp40Pm8gzmZscAFPCmX5o2g@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Thunder vs. Yard Goats Thunder vs. Yard Goats

Follow on MiLB First Pitch  https //stza.co/+vbSZ-3U

Shop  https //stza.co/+vbSZ-25

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Thunder vs. Yard Goats
END:VALARM
DTSTART:20180725T150000Z
DTEND:20180725T180000Z
UID:MUp40Pm8gzmZscAFPCmX5o2g@stanza.co
SUMMARY:Thunder vs. Yard Goats
DESCRIPTION:Thunder vs. Yard Goats\n\nFollow on MiLB First Pitch: https://stza.co/+vbSZ-3U\n\nShop: https://stza.co/+vbSZ-25\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144602Z
LAST-MODIFIED:20180213T144602Z
TRANSP:OPAQUE
END:VEVENT
* Thunder vs. Sea Dogs
<2018-07-26 Thu 18:00-21:00>
:PROPERTIES:
:ID:       m-kQxzEqnd5G0vlkzvgnccde@stanza.co
:LOCATION: Fireworks Spectacular
:STATUS:   CONFIRMED
:END:

Thunder vs. Sea Dogs Take in the awe-inspiring majesty of our post-game fireworks spectacular after the game right from your seat!

Follow on MiLB First Pitch  https //stza.co/+vbT8-X

Shop  https //stza.co/+vbT8-3v

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Thunder vs. Sea Dogs
END:VALARM
DTSTART:20180726T230000Z
DTEND:20180727T020000Z
UID:m-kQxzEqnd5G0vlkzvgnccde@stanza.co
SUMMARY:Thunder vs. Sea Dogs
DESCRIPTION:Take in the awe-inspiring majesty of our post-game fireworks spectacular after the game right from your seat!\n\nFollow on MiLB First Pitch: https://stza.co/+vbT8-X\n\nShop: https://stza.co/+vbT8-3v\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Fireworks Spectacular
STATUS:CONFIRMED
CREATED:20180213T144602Z
LAST-MODIFIED:20180213T144602Z
TRANSP:OPAQUE
END:VEVENT
* Thunder vs. Sea Dogs
<2018-07-27 Fri 18:00-21:00>
:PROPERTIES:
:ID:       O5oJhBrWQO_-yjVDXN_Tm5ai@stanza.co
:LOCATION: Christmas Ornament Giveaway
:STATUS:   CONFIRMED
:END:

Thunder vs. Sea Dogs Christmas comes early with our special 25th Anniversary Christmas Ornament giveaway on Friday, July 27!

Follow on MiLB First Pitch  https //stza.co/+vbTi-3N

Shop  https //stza.co/+vbTi-3X

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Thunder vs. Sea Dogs
END:VALARM
DTSTART:20180727T230000Z
DTEND:20180728T020000Z
UID:O5oJhBrWQO_-yjVDXN_Tm5ai@stanza.co
SUMMARY:Thunder vs. Sea Dogs
DESCRIPTION:Christmas comes early with our special 25th Anniversary Christmas Ornament giveaway on Friday, July 27!\n\nFollow on MiLB First Pitch: https://stza.co/+vbTi-3N\n\nShop: https://stza.co/+vbTi-3X\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Christmas Ornament Giveaway
STATUS:CONFIRMED
CREATED:20180213T144602Z
LAST-MODIFIED:20180213T144602Z
TRANSP:OPAQUE
END:VEVENT
* Thunder vs. Sea Dogs
<2018-07-28 Sat 18:00-21:00>
:PROPERTIES:
:ID:       LvMJUrYHzdwHkYOHPuUR_KRF@stanza.co
:LOCATION: Fireworks Spectacular
:STATUS:   CONFIRMED
:END:

Thunder vs. Sea Dogs Take in the awe-inspiring majesty of our post-game fireworks spectacular after the game right from your seat!

Follow on MiLB First Pitch  https //stza.co/+vbTu-v

Shop  https //stza.co/+vbTu-2i

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Thunder vs. Sea Dogs
END:VALARM
DTSTART:20180728T230000Z
DTEND:20180729T020000Z
UID:LvMJUrYHzdwHkYOHPuUR_KRF@stanza.co
SUMMARY:Thunder vs. Sea Dogs
DESCRIPTION:Take in the awe-inspiring majesty of our post-game fireworks spectacular after the game right from your seat!\n\nFollow on MiLB First Pitch: https://stza.co/+vbTu-v\n\nShop: https://stza.co/+vbTu-2i\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Fireworks Spectacular
STATUS:CONFIRMED
CREATED:20180213T144602Z
LAST-MODIFIED:20180213T144602Z
TRANSP:OPAQUE
END:VEVENT
* Thunder vs. Sea Dogs
<2018-07-29 Sun 16:00-19:00>
:PROPERTIES:
:ID:       bBzJBVh9xMHpXiA6zXwPvBu1@stanza.co
:LOCATION: Aaron Judge Mini Bat Giveaway
:STATUS:   CONFIRMED
:END:

Thunder vs. Sea Dogs Take swings like the Baby Bomber with our Aaron Judge Mini Bat Giveaway to the first 1,025 fans, ages 5-13, on Sunday, July 29th!

Follow on MiLB First Pitch  https //stza.co/+vbTI-3_

Shop  https //stza.co/+vbTI-3M

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Thunder vs. Sea Dogs
END:VALARM
DTSTART:20180729T210000Z
DTEND:20180730T000000Z
UID:bBzJBVh9xMHpXiA6zXwPvBu1@stanza.co
SUMMARY:Thunder vs. Sea Dogs
DESCRIPTION:Take swings like the Baby Bomber with our Aaron Judge Mini Bat Giveaway to the first 1,025 fans, ages 5-13, on Sunday, July 29th!\n\nFollow on MiLB First Pitch: https://stza.co/+vbTI-3_\n\nShop: https://stza.co/+vbTI-3M\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Aaron Judge Mini Bat Giveaway
STATUS:CONFIRMED
CREATED:20180213T144602Z
LAST-MODIFIED:20180213T144602Z
TRANSP:OPAQUE
END:VEVENT
* Thunder @ Fightin Phils
<2018-07-31 Tue 18:05-21:05>
:PROPERTIES:
:ID:       TlS8IZI7SqWkGdw1vQu3u3ZK@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Thunder @ Fightin Phils Thunder @ Fightin Phils

Buy tickets here  https //stza.co/~vbHk

Follow on MiLB First Pitch  https //stza.co/+vbHk-1J

Shop  https //stza.co/+vbHk-1q

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Thunder @ Fightin Phils
END:VALARM
DTSTART:20180731T230500Z
DTEND:20180801T020500Z
UID:TlS8IZI7SqWkGdw1vQu3u3ZK@stanza.co
SUMMARY:Thunder @ Fightin Phils
DESCRIPTION:Thunder @ Fightin Phils\n\nBuy tickets here: https://stza.co/~vbHk\n\nFollow on MiLB First Pitch: https://stza.co/+vbHk-1J\n\nShop: https://stza.co/+vbHk-1q\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144602Z
LAST-MODIFIED:20180213T144602Z
TRANSP:OPAQUE
END:VEVENT
* Thunder @ Fightin Phils
<2018-08-01 Wed 18:05-21:05>
:PROPERTIES:
:ID:       EF8tJ2M5gT-DLYWWe9rQPuz0@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Thunder @ Fightin Phils Thunder @ Fightin Phils

Buy tickets here  https //stza.co/~vbHE

Follow on MiLB First Pitch  https //stza.co/+vbHE-1T

Shop  https //stza.co/+vbHE-1Z

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Thunder @ Fightin Phils
END:VALARM
DTSTART:20180801T230500Z
DTEND:20180802T020500Z
UID:EF8tJ2M5gT-DLYWWe9rQPuz0@stanza.co
SUMMARY:Thunder @ Fightin Phils
DESCRIPTION:Thunder @ Fightin Phils\n\nBuy tickets here: https://stza.co/~vbHE\n\nFollow on MiLB First Pitch: https://stza.co/+vbHE-1T\n\nShop: https://stza.co/+vbHE-1Z\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144602Z
LAST-MODIFIED:20180213T144602Z
TRANSP:OPAQUE
END:VEVENT
* Thunder @ Fightin Phils
<2018-08-02 Thu 18:05-21:05>
:PROPERTIES:
:ID:       7sHvvFVKrkelGPOH5mG_XtPE@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Thunder @ Fightin Phils Thunder @ Fightin Phils

Buy tickets here  https //stza.co/~vbHY

Follow on MiLB First Pitch  https //stza.co/+vbHY-13

Shop  https //stza.co/+vbHY-15

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Thunder @ Fightin Phils
END:VALARM
DTSTART:20180802T230500Z
DTEND:20180803T020500Z
UID:7sHvvFVKrkelGPOH5mG_XtPE@stanza.co
SUMMARY:Thunder @ Fightin Phils
DESCRIPTION:Thunder @ Fightin Phils\n\nBuy tickets here: https://stza.co/~vbHY\n\nFollow on MiLB First Pitch: https://stza.co/+vbHY-13\n\nShop: https://stza.co/+vbHY-15\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144602Z
LAST-MODIFIED:20180213T144602Z
TRANSP:OPAQUE
END:VEVENT
* Thunder @ Yard Goats
<2018-08-03 Fri 18:05-21:05>
:PROPERTIES:
:ID:       NXsFIKkKwW9JtzfDxDY0mw_c@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Thunder @ Yard Goats Thunder @ Yard Goats

Buy tickets here  https //stza.co/~vbB2

Follow on MiLB First Pitch  https //stza.co/+vbB2-1u

Shop  https //stza.co/+vbB2-x

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Thunder @ Yard Goats
END:VALARM
DTSTART:20180803T230500Z
DTEND:20180804T020500Z
UID:NXsFIKkKwW9JtzfDxDY0mw_c@stanza.co
SUMMARY:Thunder @ Yard Goats
DESCRIPTION:Thunder @ Yard Goats\n\nBuy tickets here: https://stza.co/~vbB2\n\nFollow on MiLB First Pitch: https://stza.co/+vbB2-1u\n\nShop: https://stza.co/+vbB2-x\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144602Z
LAST-MODIFIED:20180213T144602Z
TRANSP:OPAQUE
END:VEVENT
* Thunder @ Yard Goats
<2018-08-04 Sat 17:05-20:05>
:PROPERTIES:
:ID:       Bq_wFDQsHvoQHfJMN2sttYGt@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Thunder @ Yard Goats Thunder @ Yard Goats

Buy tickets here  https //stza.co/~vbBl

Follow on MiLB First Pitch  https //stza.co/+vbBl-3z

Shop  https //stza.co/+vbBl-2e

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Thunder @ Yard Goats
END:VALARM
DTSTART:20180804T220500Z
DTEND:20180805T010500Z
UID:Bq_wFDQsHvoQHfJMN2sttYGt@stanza.co
SUMMARY:Thunder @ Yard Goats
DESCRIPTION:Thunder @ Yard Goats\n\nBuy tickets here: https://stza.co/~vbBl\n\nFollow on MiLB First Pitch: https://stza.co/+vbBl-3z\n\nShop: https://stza.co/+vbBl-2e\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144602Z
LAST-MODIFIED:20180213T144602Z
TRANSP:OPAQUE
END:VEVENT
* Thunder @ Yard Goats
<2018-08-05 Sun 16:05-19:05>
:PROPERTIES:
:ID:       Vu7H5glGOgg_aPhxPIMFmka4@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Thunder @ Yard Goats Thunder @ Yard Goats

Buy tickets here  https //stza.co/~vbBA

Follow on MiLB First Pitch  https //stza.co/+vbBA-2H

Shop  https //stza.co/+vbBA-B

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Thunder @ Yard Goats
END:VALARM
DTSTART:20180805T210500Z
DTEND:20180806T000500Z
UID:Vu7H5glGOgg_aPhxPIMFmka4@stanza.co
SUMMARY:Thunder @ Yard Goats
DESCRIPTION:Thunder @ Yard Goats\n\nBuy tickets here: https://stza.co/~vbBA\n\nFollow on MiLB First Pitch: https://stza.co/+vbBA-2H\n\nShop: https://stza.co/+vbBA-B\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144602Z
LAST-MODIFIED:20180213T144602Z
TRANSP:OPAQUE
END:VEVENT
* Thunder vs. Curve
<2018-08-07 Tue 18:00-21:00>
:PROPERTIES:
:ID:       LxQiVd71oUqc4R7WxMGwpvBn@stanza.co
:LOCATION: Aaron Judge Bobblehead Giveaway
:STATUS:   CONFIRMED
:END:

Thunder vs. Curve The ninth in a special 25th anniversary set of bobbleheads. Take home a bobblehead of one of the best OF in franchise history!

Follow on MiLB First Pitch  https //stza.co/+vbTW-33

Shop  https //stza.co/+vbTW-5

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Thunder vs. Curve
END:VALARM
DTSTART:20180807T230000Z
DTEND:20180808T020000Z
UID:LxQiVd71oUqc4R7WxMGwpvBn@stanza.co
SUMMARY:Thunder vs. Curve
DESCRIPTION:The ninth in a special 25th anniversary set of bobbleheads. Take home a bobblehead of one of the best OF in franchise history!\n\nFollow on MiLB First Pitch: https://stza.co/+vbTW-33\n\nShop: https://stza.co/+vbTW-5\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Aaron Judge Bobblehead Giveaway
STATUS:CONFIRMED
CREATED:20180213T144602Z
LAST-MODIFIED:20180213T144602Z
TRANSP:OPAQUE
END:VEVENT
* Thunder vs. Curve
<2018-08-08 Wed 11:00-14:00>
:PROPERTIES:
:ID:       wvTVtRVtDJkPGu4ecl3oCCQt@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Thunder vs. Curve Thunder vs. Curve

Follow on MiLB First Pitch  https //stza.co/+vbU5-3d

Shop  https //stza.co/+vbU5-P

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Thunder vs. Curve
END:VALARM
DTSTART:20180808T160000Z
DTEND:20180808T190000Z
UID:wvTVtRVtDJkPGu4ecl3oCCQt@stanza.co
SUMMARY:Thunder vs. Curve
DESCRIPTION:Thunder vs. Curve\n\nFollow on MiLB First Pitch: https://stza.co/+vbU5-3d\n\nShop: https://stza.co/+vbU5-P\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144602Z
LAST-MODIFIED:20180213T144602Z
TRANSP:OPAQUE
END:VEVENT
* Thunder vs. Curve
<2018-08-09 Thu 18:00-21:00>
:PROPERTIES:
:ID:       lUdlkzDs3wj-LHB12SOD6wIK@stanza.co
:LOCATION: Fireworks Spectacular
:STATUS:   CONFIRMED
:END:

Thunder vs. Curve Take in the awe-inspiring majesty of our post-game fireworks spectacular after the game right from your seat!

Follow on MiLB First Pitch  https //stza.co/+vbUh-Q

Shop  https //stza.co/+vbUh-V

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Thunder vs. Curve
END:VALARM
DTSTART:20180809T230000Z
DTEND:20180810T020000Z
UID:lUdlkzDs3wj-LHB12SOD6wIK@stanza.co
SUMMARY:Thunder vs. Curve
DESCRIPTION:Take in the awe-inspiring majesty of our post-game fireworks spectacular after the game right from your seat!\n\nFollow on MiLB First Pitch: https://stza.co/+vbUh-Q\n\nShop: https://stza.co/+vbUh-V\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Fireworks Spectacular
STATUS:CONFIRMED
CREATED:20180213T144602Z
LAST-MODIFIED:20180213T144602Z
TRANSP:OPAQUE
END:VEVENT
* Thunder @ Senators
<2018-08-10 Fri 18:00-21:00>
:PROPERTIES:
:ID:       Zvfzkf1nLCA8JZNI_yJMPL1I@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Thunder @ Senators Thunder @ Senators

Follow on MiLB First Pitch  https //stza.co/+vbAg-27

Shop  https //stza.co/+vbAg-D

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Thunder @ Senators
END:VALARM
DTSTART:20180810T230000Z
DTEND:20180811T020000Z
UID:Zvfzkf1nLCA8JZNI_yJMPL1I@stanza.co
SUMMARY:Thunder @ Senators
DESCRIPTION:Thunder @ Senators\n\nFollow on MiLB First Pitch: https://stza.co/+vbAg-27\n\nShop: https://stza.co/+vbAg-D\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144602Z
LAST-MODIFIED:20180213T144602Z
TRANSP:OPAQUE
END:VEVENT
* Thunder @ Senators
<2018-08-11 Sat 17:00-20:00>
:PROPERTIES:
:ID:       2PgSohZM-6zjtsOGfw3exquv@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Thunder @ Senators Thunder @ Senators

Follow on MiLB First Pitch  https //stza.co/+vbAz-3p

Shop  https //stza.co/+vbAz-1

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Thunder @ Senators
END:VALARM
DTSTART:20180811T220000Z
DTEND:20180812T010000Z
UID:2PgSohZM-6zjtsOGfw3exquv@stanza.co
SUMMARY:Thunder @ Senators
DESCRIPTION:Thunder @ Senators\n\nFollow on MiLB First Pitch: https://stza.co/+vbAz-3p\n\nShop: https://stza.co/+vbAz-1\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144602Z
LAST-MODIFIED:20180213T144602Z
TRANSP:OPAQUE
END:VEVENT
* Thunder @ Senators
<2018-08-12 Sun 12:30-15:30>
:PROPERTIES:
:ID:       wnWSBKpDz8A7b2zaM20sUDW5@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Thunder @ Senators Thunder @ Senators

Follow on MiLB First Pitch  https //stza.co/+vbAP-1A

Shop  https //stza.co/+vbAP-2D

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Thunder @ Senators
END:VALARM
DTSTART:20180812T173000Z
DTEND:20180812T203000Z
UID:wnWSBKpDz8A7b2zaM20sUDW5@stanza.co
SUMMARY:Thunder @ Senators
DESCRIPTION:Thunder @ Senators\n\nFollow on MiLB First Pitch: https://stza.co/+vbAP-1A\n\nShop: https://stza.co/+vbAP-2D\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144602Z
LAST-MODIFIED:20180213T144602Z
TRANSP:OPAQUE
END:VEVENT
* Thunder @ Sea Dogs
<2018-08-14 Tue 18:00-21:00>
:PROPERTIES:
:ID:       tq0Wk5lfw1et9kpSCJzDaphm@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Thunder @ Sea Dogs Thunder @ Sea Dogs

Buy tickets here  https //stza.co/~vbGg

Follow on MiLB First Pitch  https //stza.co/+vbGg-2R

Shop  https //stza.co/+vbGg-2H

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Thunder @ Sea Dogs
END:VALARM
DTSTART:20180814T230000Z
DTEND:20180815T020000Z
UID:tq0Wk5lfw1et9kpSCJzDaphm@stanza.co
SUMMARY:Thunder @ Sea Dogs
DESCRIPTION:Thunder @ Sea Dogs\n\nBuy tickets here: https://stza.co/~vbGg\n\nFollow on MiLB First Pitch: https://stza.co/+vbGg-2R\n\nShop: https://stza.co/+vbGg-2H\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144602Z
LAST-MODIFIED:20180213T144602Z
TRANSP:OPAQUE
END:VEVENT
* Thunder @ Sea Dogs
<2018-08-15 Wed 18:00-21:00>
:PROPERTIES:
:ID:       V-eWL5rcZe0tCZ23BAbkI0vO@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Thunder @ Sea Dogs Thunder @ Sea Dogs

Buy tickets here  https //stza.co/~vbGB

Follow on MiLB First Pitch  https //stza.co/+vbGB-E

Shop  https //stza.co/+vbGB-2r

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Thunder @ Sea Dogs
END:VALARM
DTSTART:20180815T230000Z
DTEND:20180816T020000Z
UID:V-eWL5rcZe0tCZ23BAbkI0vO@stanza.co
SUMMARY:Thunder @ Sea Dogs
DESCRIPTION:Thunder @ Sea Dogs\n\nBuy tickets here: https://stza.co/~vbGB\n\nFollow on MiLB First Pitch: https://stza.co/+vbGB-E\n\nShop: https://stza.co/+vbGB-2r\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144602Z
LAST-MODIFIED:20180213T144602Z
TRANSP:OPAQUE
END:VEVENT
* Thunder @ Sea Dogs
<2018-08-16 Thu 11:00-14:00>
:PROPERTIES:
:ID:       --3DX_rSjSPDARyDgaawr63N@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Thunder @ Sea Dogs Thunder @ Sea Dogs

Buy tickets here  https //stza.co/~vbGV

Follow on MiLB First Pitch  https //stza.co/+vbGV-n

Shop  https //stza.co/+vbGV-2r

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Thunder @ Sea Dogs
END:VALARM
DTSTART:20180816T160000Z
DTEND:20180816T190000Z
UID:--3DX_rSjSPDARyDgaawr63N@stanza.co
SUMMARY:Thunder @ Sea Dogs
DESCRIPTION:Thunder @ Sea Dogs\n\nBuy tickets here: https://stza.co/~vbGV\n\nFollow on MiLB First Pitch: https://stza.co/+vbGV-n\n\nShop: https://stza.co/+vbGV-2r\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144602Z
LAST-MODIFIED:20180213T144602Z
TRANSP:OPAQUE
END:VEVENT
* Thunder vs. Fisher Cats
<2018-08-17 Fri 18:00-21:00>
:PROPERTIES:
:ID:       aS7M9m5E86i5pwI9Q9nQPoGT@stanza.co
:LOCATION: Fireworks Spectacular
:STATUS:   CONFIRMED
:END:

Thunder vs. Fisher Cats Take in the awe-inspiring majesty of our post-game fireworks spectacular after the game right from your seat!

Follow on MiLB First Pitch  https //stza.co/+vbUo-U

Shop  https //stza.co/+vbUo-2i

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Thunder vs. Fisher Cats
END:VALARM
DTSTART:20180817T230000Z
DTEND:20180818T020000Z
UID:aS7M9m5E86i5pwI9Q9nQPoGT@stanza.co
SUMMARY:Thunder vs. Fisher Cats
DESCRIPTION:Take in the awe-inspiring majesty of our post-game fireworks spectacular after the game right from your seat!\n\nFollow on MiLB First Pitch: https://stza.co/+vbUo-U\n\nShop: https://stza.co/+vbUo-2i\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Fireworks Spectacular
STATUS:CONFIRMED
CREATED:20180213T144602Z
LAST-MODIFIED:20180213T144602Z
TRANSP:OPAQUE
END:VEVENT
* Thunder vs. Fisher Cats
<2018-08-18 Sat 18:00-21:00>
:PROPERTIES:
:ID:       e2Xo76AI0N7stz2J8ygLrS1l@stanza.co
:LOCATION: Fireworks Spectacular
:STATUS:   CONFIRMED
:END:

Thunder vs. Fisher Cats Take in the awe-inspiring majesty of our post-game fireworks spectacular after the game right from your seat!

Follow on MiLB First Pitch  https //stza.co/+vbUA-3Z

Shop  https //stza.co/+vbUA-3E

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Thunder vs. Fisher Cats
END:VALARM
DTSTART:20180818T230000Z
DTEND:20180819T020000Z
UID:e2Xo76AI0N7stz2J8ygLrS1l@stanza.co
SUMMARY:Thunder vs. Fisher Cats
DESCRIPTION:Take in the awe-inspiring majesty of our post-game fireworks spectacular after the game right from your seat!\n\nFollow on MiLB First Pitch: https://stza.co/+vbUA-3Z\n\nShop: https://stza.co/+vbUA-3E\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Fireworks Spectacular
STATUS:CONFIRMED
CREATED:20180213T144602Z
LAST-MODIFIED:20180213T144602Z
TRANSP:OPAQUE
END:VEVENT
* Thunder vs. Fisher Cats
<2018-08-19 Sun 16:00-19:00>
:PROPERTIES:
:ID:       wOB3y71oP9IaClmyu_DOYxTV@stanza.co
:LOCATION: Bark in the Park
:STATUS:   CONFIRMED
:END:

Thunder vs. Fisher Cats A fan favorite returns! Bring in your dog free of charge and visit with dozens of local pet vendors on the concourse

Follow on MiLB First Pitch  https //stza.co/+vbUL-3B

Shop  https //stza.co/+vbUL-D

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Thunder vs. Fisher Cats
END:VALARM
DTSTART:20180819T210000Z
DTEND:20180820T000000Z
UID:wOB3y71oP9IaClmyu_DOYxTV@stanza.co
SUMMARY:Thunder vs. Fisher Cats
DESCRIPTION:A fan favorite returns! Bring in your dog free of charge and visit with dozens of local pet vendors on the concourse\n\nFollow on MiLB First Pitch: https://stza.co/+vbUL-3B\n\nShop: https://stza.co/+vbUL-D\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Bark in the Park
STATUS:CONFIRMED
CREATED:20180213T144602Z
LAST-MODIFIED:20180213T144602Z
TRANSP:OPAQUE
END:VEVENT
* Thunder vs. Yard Goats
<2018-08-20 Mon 18:00-21:00>
:PROPERTIES:
:ID:       HFj1Wm8pieHuAOS-HUMMkvYh@stanza.co
:LOCATION: Yankees Magazine Night
:STATUS:   CONFIRMED
:END:

Thunder vs. Yard Goats The first 1,025 fans ages 14 and older will receive the latest issue of Yankees Magazine!

Follow on MiLB First Pitch  https //stza.co/+vbUQ-3y

Shop  https //stza.co/+vbUQ-13

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Thunder vs. Yard Goats
END:VALARM
DTSTART:20180820T230000Z
DTEND:20180821T020000Z
UID:HFj1Wm8pieHuAOS-HUMMkvYh@stanza.co
SUMMARY:Thunder vs. Yard Goats
DESCRIPTION:The first 1,025 fans ages 14 and older will receive the latest issue of Yankees Magazine!\n\nFollow on MiLB First Pitch: https://stza.co/+vbUQ-3y\n\nShop: https://stza.co/+vbUQ-13\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Yankees Magazine Night
STATUS:CONFIRMED
CREATED:20180213T144602Z
LAST-MODIFIED:20180213T144602Z
TRANSP:OPAQUE
END:VEVENT
* Thunder vs. Yard Goats
<2018-08-21 Tue 18:00-21:00>
:PROPERTIES:
:ID:       5MLoUctu2uaejhZ2s885RpNP@stanza.co
:LOCATION: Football Night
:STATUS:   CONFIRMED
:END:

Thunder vs. Yard Goats Wear your favorite football jersey to the ballpark and celebrate the return of the gridiron!

Follow on MiLB First Pitch  https //stza.co/+vbUW-1C

Shop  https //stza.co/+vbUW-3U

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Thunder vs. Yard Goats
END:VALARM
DTSTART:20180821T230000Z
DTEND:20180822T020000Z
UID:5MLoUctu2uaejhZ2s885RpNP@stanza.co
SUMMARY:Thunder vs. Yard Goats
DESCRIPTION:Wear your favorite football jersey to the ballpark and celebrate the return of the gridiron!\n\nFollow on MiLB First Pitch: https://stza.co/+vbUW-1C\n\nShop: https://stza.co/+vbUW-3U\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Football Night
STATUS:CONFIRMED
CREATED:20180213T144602Z
LAST-MODIFIED:20180213T144602Z
TRANSP:OPAQUE
END:VEVENT
* Thunder @ Fightin Phils
<2018-08-22 Wed 18:05-21:05>
:PROPERTIES:
:ID:       AFXpoHW-6SGuLQvhI8kMuSR-@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Thunder @ Fightin Phils Thunder @ Fightin Phils

Buy tickets here  https //stza.co/~vbI4

Follow on MiLB First Pitch  https //stza.co/+vbI4-1b

Shop  https //stza.co/+vbI4-1k

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Thunder @ Fightin Phils
END:VALARM
DTSTART:20180822T230500Z
DTEND:20180823T020500Z
UID:AFXpoHW-6SGuLQvhI8kMuSR-@stanza.co
SUMMARY:Thunder @ Fightin Phils
DESCRIPTION:Thunder @ Fightin Phils\n\nBuy tickets here: https://stza.co/~vbI4\n\nFollow on MiLB First Pitch: https://stza.co/+vbI4-1b\n\nShop: https://stza.co/+vbI4-1k\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144602Z
LAST-MODIFIED:20180213T144602Z
TRANSP:OPAQUE
END:VEVENT
* Thunder @ Fightin Phils
<2018-08-23 Thu 18:05-21:05>
:PROPERTIES:
:ID:       gffZuI4q81xOfZ3oAwkxo6AM@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Thunder @ Fightin Phils Thunder @ Fightin Phils

Buy tickets here  https //stza.co/~vbIs

Follow on MiLB First Pitch  https //stza.co/+vbIs-3r

Shop  https //stza.co/+vbIs-r

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Thunder @ Fightin Phils
END:VALARM
DTSTART:20180823T230500Z
DTEND:20180824T020500Z
UID:gffZuI4q81xOfZ3oAwkxo6AM@stanza.co
SUMMARY:Thunder @ Fightin Phils
DESCRIPTION:Thunder @ Fightin Phils\n\nBuy tickets here: https://stza.co/~vbIs\n\nFollow on MiLB First Pitch: https://stza.co/+vbIs-3r\n\nShop: https://stza.co/+vbIs-r\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144602Z
LAST-MODIFIED:20180213T144602Z
TRANSP:OPAQUE
END:VEVENT
* Thunder @ Yard Goats
<2018-08-24 Fri 18:05-21:05>
:PROPERTIES:
:ID:       AIw4weJ-GsP3q6krgbim1L7e@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Thunder @ Yard Goats Thunder @ Yard Goats

Buy tickets here  https //stza.co/~vbBW

Follow on MiLB First Pitch  https //stza.co/+vbBW-B

Shop  https //stza.co/+vbBW-3G

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Thunder @ Yard Goats
END:VALARM
DTSTART:20180824T230500Z
DTEND:20180825T020500Z
UID:AIw4weJ-GsP3q6krgbim1L7e@stanza.co
SUMMARY:Thunder @ Yard Goats
DESCRIPTION:Thunder @ Yard Goats\n\nBuy tickets here: https://stza.co/~vbBW\n\nFollow on MiLB First Pitch: https://stza.co/+vbBW-B\n\nShop: https://stza.co/+vbBW-3G\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144602Z
LAST-MODIFIED:20180213T144602Z
TRANSP:OPAQUE
END:VEVENT
* Thunder @ Yard Goats
<2018-08-25 Sat 17:05-20:05>
:PROPERTIES:
:ID:       uaNANIAw4D0gKuvORT4yXecM@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Thunder @ Yard Goats Thunder @ Yard Goats

Buy tickets here  https //stza.co/~vbC8

Follow on MiLB First Pitch  https //stza.co/+vbC8-a

Shop  https //stza.co/+vbC8-3W

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Thunder @ Yard Goats
END:VALARM
DTSTART:20180825T220500Z
DTEND:20180826T010500Z
UID:uaNANIAw4D0gKuvORT4yXecM@stanza.co
SUMMARY:Thunder @ Yard Goats
DESCRIPTION:Thunder @ Yard Goats\n\nBuy tickets here: https://stza.co/~vbC8\n\nFollow on MiLB First Pitch: https://stza.co/+vbC8-a\n\nShop: https://stza.co/+vbC8-3W\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144602Z
LAST-MODIFIED:20180213T144602Z
TRANSP:OPAQUE
END:VEVENT
* Thunder @ Yard Goats
<2018-08-26 Sun 12:05-15:05>
:PROPERTIES:
:ID:       N7HuWwore_z6BA5a3NP57iEe@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Thunder @ Yard Goats Thunder @ Yard Goats

Buy tickets here  https //stza.co/~vbCy

Follow on MiLB First Pitch  https //stza.co/+vbCy-2s

Shop  https //stza.co/+vbCy-1Y

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Thunder @ Yard Goats
END:VALARM
DTSTART:20180826T170500Z
DTEND:20180826T200500Z
UID:N7HuWwore_z6BA5a3NP57iEe@stanza.co
SUMMARY:Thunder @ Yard Goats
DESCRIPTION:Thunder @ Yard Goats\n\nBuy tickets here: https://stza.co/~vbCy\n\nFollow on MiLB First Pitch: https://stza.co/+vbCy-2s\n\nShop: https://stza.co/+vbCy-1Y\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144602Z
LAST-MODIFIED:20180213T144602Z
TRANSP:OPAQUE
END:VEVENT
* Thunder @ Curve
<2018-08-27 Mon 17:00-20:00>
:PROPERTIES:
:ID:       C2Q4WB4tHvQKGg8xKx7D6g0I@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Thunder @ Curve Thunder @ Curve

Follow on MiLB First Pitch  https //stza.co/+vbtp-2Y

Shop  https //stza.co/+vbtp-10

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Thunder @ Curve
END:VALARM
DTSTART:20180827T220000Z
DTEND:20180828T010000Z
UID:C2Q4WB4tHvQKGg8xKx7D6g0I@stanza.co
SUMMARY:Thunder @ Curve
DESCRIPTION:Thunder @ Curve\n\nFollow on MiLB First Pitch: https://stza.co/+vbtp-2Y\n\nShop: https://stza.co/+vbtp-10\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144602Z
LAST-MODIFIED:20180213T144602Z
TRANSP:OPAQUE
END:VEVENT
* Thunder @ Curve
<2018-08-28 Tue 17:00-20:00>
:PROPERTIES:
:ID:       3Oxj5Yn4nZNujSD3bWkQQe5O@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Thunder @ Curve Thunder @ Curve

Follow on MiLB First Pitch  https //stza.co/+vbtG-10

Shop  https //stza.co/+vbtG-28

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Thunder @ Curve
END:VALARM
DTSTART:20180828T220000Z
DTEND:20180829T010000Z
UID:3Oxj5Yn4nZNujSD3bWkQQe5O@stanza.co
SUMMARY:Thunder @ Curve
DESCRIPTION:Thunder @ Curve\n\nFollow on MiLB First Pitch: https://stza.co/+vbtG-10\n\nShop: https://stza.co/+vbtG-28\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144602Z
LAST-MODIFIED:20180213T144602Z
TRANSP:OPAQUE
END:VEVENT
* Thunder @ Curve
<2018-08-29 Wed 17:00-20:00>
:PROPERTIES:
:ID:       KE2W4ilSqLp9UdR2e4RGcUUm@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Thunder @ Curve Thunder @ Curve

Follow on MiLB First Pitch  https //stza.co/+vbtX-1G

Shop  https //stza.co/+vbtX-13

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Thunder @ Curve
END:VALARM
DTSTART:20180829T220000Z
DTEND:20180830T010000Z
UID:KE2W4ilSqLp9UdR2e4RGcUUm@stanza.co
SUMMARY:Thunder @ Curve
DESCRIPTION:Thunder @ Curve\n\nFollow on MiLB First Pitch: https://stza.co/+vbtX-1G\n\nShop: https://stza.co/+vbtX-13\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144602Z
LAST-MODIFIED:20180213T144602Z
TRANSP:OPAQUE
END:VEVENT
* Thunder @ Curve
<2018-08-30 Thu 17:00-20:00>
:PROPERTIES:
:ID:       iNq1iVImJ69tzHHuH0V5eCDT@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Thunder @ Curve Thunder @ Curve

Follow on MiLB First Pitch  https //stza.co/+vbuc-3b

Shop  https //stza.co/+vbuc-6

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Thunder @ Curve
END:VALARM
DTSTART:20180830T220000Z
DTEND:20180831T010000Z
UID:iNq1iVImJ69tzHHuH0V5eCDT@stanza.co
SUMMARY:Thunder @ Curve
DESCRIPTION:Thunder @ Curve\n\nFollow on MiLB First Pitch: https://stza.co/+vbuc-3b\n\nShop: https://stza.co/+vbuc-6\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144602Z
LAST-MODIFIED:20180213T144602Z
TRANSP:OPAQUE
END:VEVENT
* Thunder vs. Fightin Phils
<2018-08-31 Fri 18:00-21:00>
:PROPERTIES:
:ID:       wYor8xFe9QQ9l4gDHauD4xwJ@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Thunder vs. Fightin Phils Thunder vs. Fightin Phils

Follow on MiLB First Pitch  https //stza.co/+vbU_-2H

Shop  https //stza.co/+vbU_-1Z

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Thunder vs. Fightin Phils
END:VALARM
DTSTART:20180831T230000Z
DTEND:20180901T020000Z
UID:wYor8xFe9QQ9l4gDHauD4xwJ@stanza.co
SUMMARY:Thunder vs. Fightin Phils
DESCRIPTION:Thunder vs. Fightin Phils\n\nFollow on MiLB First Pitch: https://stza.co/+vbU_-2H\n\nShop: https://stza.co/+vbU_-1Z\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144602Z
LAST-MODIFIED:20180213T144602Z
TRANSP:OPAQUE
END:VEVENT
* Thunder vs. Fightin Phils
<2018-09-01 Sat 18:00-21:00>
:PROPERTIES:
:ID:       n7lSKBdQdcKwUFMlrEugmFwa@stanza.co
:LOCATION: Fireworks Spectacular
:STATUS:   CONFIRMED
:END:

Thunder vs. Fightin Phils Take in the awe-inspiring majesty of our post-game fireworks spectacular after the game right from your seat!

Follow on MiLB First Pitch  https //stza.co/+vbV0-9

Shop  https //stza.co/+vbV0-1c

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Thunder vs. Fightin Phils
END:VALARM
DTSTART:20180901T230000Z
DTEND:20180902T020000Z
UID:n7lSKBdQdcKwUFMlrEugmFwa@stanza.co
SUMMARY:Thunder vs. Fightin Phils
DESCRIPTION:Take in the awe-inspiring majesty of our post-game fireworks spectacular after the game right from your seat!\n\nFollow on MiLB First Pitch: https://stza.co/+vbV0-9\n\nShop: https://stza.co/+vbV0-1c\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Fireworks Spectacular
STATUS:CONFIRMED
CREATED:20180213T144602Z
LAST-MODIFIED:20180213T144602Z
TRANSP:OPAQUE
END:VEVENT
* Thunder vs. Fightin Phils
<2018-09-02 Sun 18:00-21:00>
:PROPERTIES:
:ID:       8S4iqGsFlSGQ5HQst49nkVG9@stanza.co
:LOCATION: Fireworks Spectacular
:STATUS:   CONFIRMED
:END:

Thunder vs. Fightin Phils Take in the awe-inspiring majesty of our post-game fireworks spectacular after the game right from your seat!

Follow on MiLB First Pitch  https //stza.co/+vLwx-3f

Shop  https //stza.co/+vLwx-3c

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Thunder vs. Fightin Phils
END:VALARM
DTSTART:20180902T230000Z
DTEND:20180903T020000Z
UID:8S4iqGsFlSGQ5HQst49nkVG9@stanza.co
SUMMARY:Thunder vs. Fightin Phils
DESCRIPTION:Take in the awe-inspiring majesty of our post-game fireworks spectacular after the game right from your seat!\n\nFollow on MiLB First Pitch: https://stza.co/+vLwx-3f\n\nShop: https://stza.co/+vLwx-3c\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Fireworks Spectacular
STATUS:CONFIRMED
CREATED:20180213T144602Z
LAST-MODIFIED:20180213T144602Z
TRANSP:OPAQUE
END:VEVENT
* Thunder vs. Fightin Phils
<2018-09-03 Mon 12:00-15:00>
:PROPERTIES:
:ID:       zxJqXFKrYyAlQxlZsbMNYaUu@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Thunder vs. Fightin Phils Thunder vs. Fightin Phils

Follow on MiLB First Pitch  https //stza.co/+vLwA-19

Shop  https //stza.co/+vLwA-t

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Thunder vs. Fightin Phils
END:VALARM
DTSTART:20180903T170000Z
DTEND:20180903T200000Z
UID:zxJqXFKrYyAlQxlZsbMNYaUu@stanza.co
SUMMARY:Thunder vs. Fightin Phils
DESCRIPTION:Thunder vs. Fightin Phils\n\nFollow on MiLB First Pitch: https://stza.co/+vLwA-19\n\nShop: https://stza.co/+vLwA-t\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144602Z
LAST-MODIFIED:20180213T144602Z
TRANSP:OPAQUE
END:VEVENT
