#+TITLE:       Main Google calendar entries
#+AUTHOR:      Eric S Fraga
#+EMAIL:       e.fraga@ucl.ac.uk
#+DESCRIPTION: converted using the ical2org awk script
#+CATEGORY:    google
#+STARTUP:     hidestars
#+STARTUP:     overview

* COMMENT original iCal preamble

* Crosscutters vs. Spikes
<2018-06-15 Fri 18:05-21:05>
:PROPERTIES:
:ID:       nfOrXA7KPothWFT0Oufix4zp@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Crosscutters vs. Spikes Crosscutters vs. Spikes

Follow on MiLB First Pitch  https //stza.co/+x$6z-2S

Shop  https //stza.co/+x$6z-1i

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Crosscutters vs. Spikes
END:VALARM
DTSTART:20180615T230500Z
DTEND:20180616T020500Z
UID:nfOrXA7KPothWFT0Oufix4zp@stanza.co
SUMMARY:Crosscutters vs. Spikes
DESCRIPTION:Crosscutters vs. Spikes\n\nFollow on MiLB First Pitch: https://stza.co/+x$6z-2S\n\nShop: https://stza.co/+x$6z-1i\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144606Z
LAST-MODIFIED:20180213T144606Z
TRANSP:OPAQUE
END:VEVENT
* Crosscutters @ Spikes
<2018-06-16 Sat>--<2018-06-15 Fri>
:PROPERTIES:
:ID:       0yWLP6t2Krq2m-haADELzvgm@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Crosscutters @ Spikes Crosscutters @ Spikes

Follow on MiLB First Pitch  https //stza.co/+xMBh-J

Shop  https //stza.co/+xMBh-V

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Crosscutters @ Spikes
END:VALARM
DTSTART;VALUE=DATE:20180616
DTEND;VALUE=DATE:20180616
UID:0yWLP6t2Krq2m-haADELzvgm@stanza.co
SUMMARY:Crosscutters @ Spikes
DESCRIPTION:Crosscutters @ Spikes\n\nFollow on MiLB First Pitch: https://stza.co/+xMBh-J\n\nShop: https://stza.co/+xMBh-V\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144606Z
LAST-MODIFIED:20180213T144606Z
TRANSP:OPAQUE
END:VEVENT
* Crosscutters vs. Spikes
<2018-06-17 Sun 16:05-19:05>
:PROPERTIES:
:ID:       p0T-yIiDM-TU-JVnLXNyLZ-5@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Crosscutters vs. Spikes Crosscutters vs. Spikes

Follow on MiLB First Pitch  https //stza.co/+x$6B-V

Shop  https //stza.co/+x$6B-m

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Crosscutters vs. Spikes
END:VALARM
DTSTART:20180617T210500Z
DTEND:20180618T000500Z
UID:p0T-yIiDM-TU-JVnLXNyLZ-5@stanza.co
SUMMARY:Crosscutters vs. Spikes
DESCRIPTION:Crosscutters vs. Spikes\n\nFollow on MiLB First Pitch: https://stza.co/+x$6B-V\n\nShop: https://stza.co/+x$6B-m\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144606Z
LAST-MODIFIED:20180213T144606Z
TRANSP:OPAQUE
END:VEVENT
* Crosscutters vs. Doubledays
<2018-06-18 Mon 18:05-21:05>
:PROPERTIES:
:ID:       VWHeFo45DFGdEuH41ak3b-sa@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Crosscutters vs. Doubledays Crosscutters vs. Doubledays

Follow on MiLB First Pitch  https //stza.co/+x$6D-2G

Shop  https //stza.co/+x$6D-34

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Crosscutters vs. Doubledays
END:VALARM
DTSTART:20180618T230500Z
DTEND:20180619T020500Z
UID:VWHeFo45DFGdEuH41ak3b-sa@stanza.co
SUMMARY:Crosscutters vs. Doubledays
DESCRIPTION:Crosscutters vs. Doubledays\n\nFollow on MiLB First Pitch: https://stza.co/+x$6D-2G\n\nShop: https://stza.co/+x$6D-34\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144606Z
LAST-MODIFIED:20180213T144606Z
TRANSP:OPAQUE
END:VEVENT
* Crosscutters vs. Doubledays
<2018-06-19 Tue 18:05-21:05>
:PROPERTIES:
:ID:       Ob3_vcbnN5auCGjSf-wMMBCl@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Crosscutters vs. Doubledays Crosscutters vs. Doubledays

Follow on MiLB First Pitch  https //stza.co/+x$6F-27

Shop  https //stza.co/+x$6F-18

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Crosscutters vs. Doubledays
END:VALARM
DTSTART:20180619T230500Z
DTEND:20180620T020500Z
UID:Ob3_vcbnN5auCGjSf-wMMBCl@stanza.co
SUMMARY:Crosscutters vs. Doubledays
DESCRIPTION:Crosscutters vs. Doubledays\n\nFollow on MiLB First Pitch: https://stza.co/+x$6F-27\n\nShop: https://stza.co/+x$6F-18\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144606Z
LAST-MODIFIED:20180213T144606Z
TRANSP:OPAQUE
END:VEVENT
* Crosscutters vs. Doubledays
<2018-06-20 Wed 18:05-21:05>
:PROPERTIES:
:ID:       vRkolCNm2pZJM6oPFjwBc_F_@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Crosscutters vs. Doubledays Crosscutters vs. Doubledays

Follow on MiLB First Pitch  https //stza.co/+x$6I-14

Shop  https //stza.co/+x$6I-1C

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Crosscutters vs. Doubledays
END:VALARM
DTSTART:20180620T230500Z
DTEND:20180621T020500Z
UID:vRkolCNm2pZJM6oPFjwBc_F_@stanza.co
SUMMARY:Crosscutters vs. Doubledays
DESCRIPTION:Crosscutters vs. Doubledays\n\nFollow on MiLB First Pitch: https://stza.co/+x$6I-14\n\nShop: https://stza.co/+x$6I-1C\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144606Z
LAST-MODIFIED:20180213T144606Z
TRANSP:OPAQUE
END:VEVENT
* Crosscutters @ Muckdogs
<2018-06-21 Thu>--<2018-06-20 Wed>
:PROPERTIES:
:ID:       Z-1MzJD36-u_cz-q5KNwJB38@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Crosscutters @ Muckdogs Crosscutters @ Muckdogs

Follow on MiLB First Pitch  https //stza.co/+xMA$-1i

Shop  https //stza.co/+xMA$-O

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Crosscutters @ Muckdogs
END:VALARM
DTSTART;VALUE=DATE:20180621
DTEND;VALUE=DATE:20180621
UID:Z-1MzJD36-u_cz-q5KNwJB38@stanza.co
SUMMARY:Crosscutters @ Muckdogs
DESCRIPTION:Crosscutters @ Muckdogs\n\nFollow on MiLB First Pitch: https://stza.co/+xMA$-1i\n\nShop: https://stza.co/+xMA$-O\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144606Z
LAST-MODIFIED:20180213T144606Z
TRANSP:OPAQUE
END:VEVENT
* Crosscutters @ Muckdogs
<2018-06-22 Fri>--<2018-06-21 Thu>
:PROPERTIES:
:ID:       GAIEFdSYCRookL0QUZs-2r1m@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Crosscutters @ Muckdogs Crosscutters @ Muckdogs

Follow on MiLB First Pitch  https //stza.co/+xMB0-3j

Shop  https //stza.co/+xMB0-j

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Crosscutters @ Muckdogs
END:VALARM
DTSTART;VALUE=DATE:20180622
DTEND;VALUE=DATE:20180622
UID:GAIEFdSYCRookL0QUZs-2r1m@stanza.co
SUMMARY:Crosscutters @ Muckdogs
DESCRIPTION:Crosscutters @ Muckdogs\n\nFollow on MiLB First Pitch: https://stza.co/+xMB0-3j\n\nShop: https://stza.co/+xMB0-j\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144606Z
LAST-MODIFIED:20180213T144606Z
TRANSP:OPAQUE
END:VEVENT
* Crosscutters @ Muckdogs
<2018-06-23 Sat>--<2018-06-22 Fri>
:PROPERTIES:
:ID:       d-et0BwK_ZIUp3Y3w54XRenW@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Crosscutters @ Muckdogs Crosscutters @ Muckdogs

Follow on MiLB First Pitch  https //stza.co/+xMB1-1Z

Shop  https //stza.co/+xMB1-3U

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Crosscutters @ Muckdogs
END:VALARM
DTSTART;VALUE=DATE:20180623
DTEND;VALUE=DATE:20180623
UID:d-et0BwK_ZIUp3Y3w54XRenW@stanza.co
SUMMARY:Crosscutters @ Muckdogs
DESCRIPTION:Crosscutters @ Muckdogs\n\nFollow on MiLB First Pitch: https://stza.co/+xMB1-1Z\n\nShop: https://stza.co/+xMB1-3U\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144606Z
LAST-MODIFIED:20180213T144606Z
TRANSP:OPAQUE
END:VEVENT
* Crosscutters @ Scrappers
<2018-06-24 Sun>--<2018-06-23 Sat>
:PROPERTIES:
:ID:       jhLXnXljlvk3q6ulc8-WBJUc@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Crosscutters @ Scrappers Crosscutters @ Scrappers

Follow on MiLB First Pitch  https //stza.co/+xMB8-3m

Shop  https //stza.co/+xMB8-21

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Crosscutters @ Scrappers
END:VALARM
DTSTART;VALUE=DATE:20180624
DTEND;VALUE=DATE:20180624
UID:jhLXnXljlvk3q6ulc8-WBJUc@stanza.co
SUMMARY:Crosscutters @ Scrappers
DESCRIPTION:Crosscutters @ Scrappers\n\nFollow on MiLB First Pitch: https://stza.co/+xMB8-3m\n\nShop: https://stza.co/+xMB8-21\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144606Z
LAST-MODIFIED:20180213T144606Z
TRANSP:OPAQUE
END:VEVENT
* Crosscutters @ Scrappers
<2018-06-25 Mon>--<2018-06-24 Sun>
:PROPERTIES:
:ID:       iH-juvpM6VQO0317jErC3KQb@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Crosscutters @ Scrappers Crosscutters @ Scrappers

Follow on MiLB First Pitch  https //stza.co/+xMB9-2Q

Shop  https //stza.co/+xMB9-w

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Crosscutters @ Scrappers
END:VALARM
DTSTART;VALUE=DATE:20180625
DTEND;VALUE=DATE:20180625
UID:iH-juvpM6VQO0317jErC3KQb@stanza.co
SUMMARY:Crosscutters @ Scrappers
DESCRIPTION:Crosscutters @ Scrappers\n\nFollow on MiLB First Pitch: https://stza.co/+xMB9-2Q\n\nShop: https://stza.co/+xMB9-w\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144606Z
LAST-MODIFIED:20180213T144606Z
TRANSP:OPAQUE
END:VEVENT
* Crosscutters @ Scrappers
<2018-06-26 Tue>--<2018-06-25 Mon>
:PROPERTIES:
:ID:       Vf0UJdCRv021Sev22TSdk66z@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Crosscutters @ Scrappers Crosscutters @ Scrappers

Follow on MiLB First Pitch  https //stza.co/+xMBa-8

Shop  https //stza.co/+xMBa-2t

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Crosscutters @ Scrappers
END:VALARM
DTSTART;VALUE=DATE:20180626
DTEND;VALUE=DATE:20180626
UID:Vf0UJdCRv021Sev22TSdk66z@stanza.co
SUMMARY:Crosscutters @ Scrappers
DESCRIPTION:Crosscutters @ Scrappers\n\nFollow on MiLB First Pitch: https://stza.co/+xMBa-8\n\nShop: https://stza.co/+xMBa-2t\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144606Z
LAST-MODIFIED:20180213T144606Z
TRANSP:OPAQUE
END:VEVENT
* Crosscutters vs. Spikes
<2018-06-28 Thu 18:05-21:05>
:PROPERTIES:
:ID:       3YIJcAYCyidxk7sonZxmpfWZ@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Crosscutters vs. Spikes Crosscutters vs. Spikes

Follow on MiLB First Pitch  https //stza.co/+x$6J-t

Shop  https //stza.co/+x$6J-2t

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Crosscutters vs. Spikes
END:VALARM
DTSTART:20180628T230500Z
DTEND:20180629T020500Z
UID:3YIJcAYCyidxk7sonZxmpfWZ@stanza.co
SUMMARY:Crosscutters vs. Spikes
DESCRIPTION:Crosscutters vs. Spikes\n\nFollow on MiLB First Pitch: https://stza.co/+x$6J-t\n\nShop: https://stza.co/+x$6J-2t\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144606Z
LAST-MODIFIED:20180213T144606Z
TRANSP:OPAQUE
END:VEVENT
* Crosscutters @ Spikes
<2018-06-29 Fri>--<2018-06-28 Thu>
:PROPERTIES:
:ID:       lnDWRdegmYcgIbYhE0pNRDPx@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Crosscutters @ Spikes Crosscutters @ Spikes

Follow on MiLB First Pitch  https //stza.co/+xMBi-9

Shop  https //stza.co/+xMBi-J

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Crosscutters @ Spikes
END:VALARM
DTSTART;VALUE=DATE:20180629
DTEND;VALUE=DATE:20180629
UID:lnDWRdegmYcgIbYhE0pNRDPx@stanza.co
SUMMARY:Crosscutters @ Spikes
DESCRIPTION:Crosscutters @ Spikes\n\nFollow on MiLB First Pitch: https://stza.co/+xMBi-9\n\nShop: https://stza.co/+xMBi-J\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144606Z
LAST-MODIFIED:20180213T144606Z
TRANSP:OPAQUE
END:VEVENT
* Crosscutters vs. Spikes
<2018-06-30 Sat 18:05-21:05>
:PROPERTIES:
:ID:       YsRcymEGOFmZcjHTYxK9D8S2@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Crosscutters vs. Spikes Crosscutters vs. Spikes

Follow on MiLB First Pitch  https //stza.co/+x$6L-2w

Shop  https //stza.co/+x$6L-1r

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Crosscutters vs. Spikes
END:VALARM
DTSTART:20180630T230500Z
DTEND:20180701T020500Z
UID:YsRcymEGOFmZcjHTYxK9D8S2@stanza.co
SUMMARY:Crosscutters vs. Spikes
DESCRIPTION:Crosscutters vs. Spikes\n\nFollow on MiLB First Pitch: https://stza.co/+x$6L-2w\n\nShop: https://stza.co/+x$6L-1r\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144606Z
LAST-MODIFIED:20180213T144606Z
TRANSP:OPAQUE
END:VEVENT
* Crosscutters vs. Doubledays
<2018-07-01 Sun 16:05-19:05>
:PROPERTIES:
:ID:       jBfbirV5wkJDosLczpbkXiMS@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Crosscutters vs. Doubledays Crosscutters vs. Doubledays

Follow on MiLB First Pitch  https //stza.co/+x$6O-13

Shop  https //stza.co/+x$6O-2w

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Crosscutters vs. Doubledays
END:VALARM
DTSTART:20180701T210500Z
DTEND:20180702T000500Z
UID:jBfbirV5wkJDosLczpbkXiMS@stanza.co
SUMMARY:Crosscutters vs. Doubledays
DESCRIPTION:Crosscutters vs. Doubledays\n\nFollow on MiLB First Pitch: https://stza.co/+x$6O-13\n\nShop: https://stza.co/+x$6O-2w\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144606Z
LAST-MODIFIED:20180213T144606Z
TRANSP:OPAQUE
END:VEVENT
* Crosscutters vs. Doubledays
<2018-07-02 Mon 18:05-21:05>
:PROPERTIES:
:ID:       i1nK3tEMUbH7z_O0dpn9rpCX@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Crosscutters vs. Doubledays Crosscutters vs. Doubledays

Follow on MiLB First Pitch  https //stza.co/+x$6Q-4

Shop  https //stza.co/+x$6Q-$

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Crosscutters vs. Doubledays
END:VALARM
DTSTART:20180702T230500Z
DTEND:20180703T020500Z
UID:i1nK3tEMUbH7z_O0dpn9rpCX@stanza.co
SUMMARY:Crosscutters vs. Doubledays
DESCRIPTION:Crosscutters vs. Doubledays\n\nFollow on MiLB First Pitch: https://stza.co/+x$6Q-4\n\nShop: https://stza.co/+x$6Q-$\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144606Z
LAST-MODIFIED:20180213T144606Z
TRANSP:OPAQUE
END:VEVENT
* Crosscutters vs. Doubledays
<2018-07-03 Tue 18:05-21:05>
:PROPERTIES:
:ID:       txxB1l51YtDMJkmthGNvbNOO@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Crosscutters vs. Doubledays Crosscutters vs. Doubledays

Follow on MiLB First Pitch  https //stza.co/+x$6S-R

Shop  https //stza.co/+x$6S-2X

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Crosscutters vs. Doubledays
END:VALARM
DTSTART:20180703T230500Z
DTEND:20180704T020500Z
UID:txxB1l51YtDMJkmthGNvbNOO@stanza.co
SUMMARY:Crosscutters vs. Doubledays
DESCRIPTION:Crosscutters vs. Doubledays\n\nFollow on MiLB First Pitch: https://stza.co/+x$6S-R\n\nShop: https://stza.co/+x$6S-2X\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144606Z
LAST-MODIFIED:20180213T144606Z
TRANSP:OPAQUE
END:VEVENT
* Crosscutters @ Black Bears
<2018-07-04 Wed 18:05-21:05>
:PROPERTIES:
:ID:       AmQTCJqf6KrD8nC2m5nk6e04@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Crosscutters @ Black Bears Crosscutters @ Black Bears

Follow on MiLB First Pitch  https //stza.co/+xW1$-2n

Shop  https //stza.co/+xW1$-b

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Crosscutters @ Black Bears
END:VALARM
DTSTART:20180704T230500Z
DTEND:20180705T020500Z
UID:AmQTCJqf6KrD8nC2m5nk6e04@stanza.co
SUMMARY:Crosscutters @ Black Bears
DESCRIPTION:Crosscutters @ Black Bears\n\nFollow on MiLB First Pitch: https://stza.co/+xW1$-2n\n\nShop: https://stza.co/+xW1$-b\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144606Z
LAST-MODIFIED:20180213T144606Z
TRANSP:OPAQUE
END:VEVENT
* Crosscutters @ Black Bears
<2018-07-05 Thu 18:05-21:05>
:PROPERTIES:
:ID:       0FpWr9ZWlukhT7zlL7kMDwe-@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Crosscutters @ Black Bears Crosscutters @ Black Bears

Follow on MiLB First Pitch  https //stza.co/+xW20-2e

Shop  https //stza.co/+xW20-j

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Crosscutters @ Black Bears
END:VALARM
DTSTART:20180705T230500Z
DTEND:20180706T020500Z
UID:0FpWr9ZWlukhT7zlL7kMDwe-@stanza.co
SUMMARY:Crosscutters @ Black Bears
DESCRIPTION:Crosscutters @ Black Bears\n\nFollow on MiLB First Pitch: https://stza.co/+xW20-2e\n\nShop: https://stza.co/+xW20-j\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144606Z
LAST-MODIFIED:20180213T144606Z
TRANSP:OPAQUE
END:VEVENT
* Crosscutters @ Black Bears
<2018-07-06 Fri 18:05-21:05>
:PROPERTIES:
:ID:       X9tEvwYpL4JIps0UkUCWmXKO@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Crosscutters @ Black Bears Crosscutters @ Black Bears

Follow on MiLB First Pitch  https //stza.co/+xW21-3W

Shop  https //stza.co/+xW21-3I

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Crosscutters @ Black Bears
END:VALARM
DTSTART:20180706T230500Z
DTEND:20180707T020500Z
UID:X9tEvwYpL4JIps0UkUCWmXKO@stanza.co
SUMMARY:Crosscutters @ Black Bears
DESCRIPTION:Crosscutters @ Black Bears\n\nFollow on MiLB First Pitch: https://stza.co/+xW21-3W\n\nShop: https://stza.co/+xW21-3I\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144606Z
LAST-MODIFIED:20180213T144606Z
TRANSP:OPAQUE
END:VEVENT
* Crosscutters @ Scrappers
<2018-07-07 Sat>--<2018-07-06 Fri>
:PROPERTIES:
:ID:       rJJDGbYASRZv6osnfOELLGUt@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Crosscutters @ Scrappers Crosscutters @ Scrappers

Follow on MiLB First Pitch  https //stza.co/+xMBb-1I

Shop  https //stza.co/+xMBb-3G

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Crosscutters @ Scrappers
END:VALARM
DTSTART;VALUE=DATE:20180707
DTEND;VALUE=DATE:20180707
UID:rJJDGbYASRZv6osnfOELLGUt@stanza.co
SUMMARY:Crosscutters @ Scrappers
DESCRIPTION:Crosscutters @ Scrappers\n\nFollow on MiLB First Pitch: https://stza.co/+xMBb-1I\n\nShop: https://stza.co/+xMBb-3G\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144606Z
LAST-MODIFIED:20180213T144606Z
TRANSP:OPAQUE
END:VEVENT
* Crosscutters @ Scrappers
<2018-07-08 Sun>--<2018-07-07 Sat>
:PROPERTIES:
:ID:       0gZ-FFc6yHayMw9o-ML7uf5I@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Crosscutters @ Scrappers Crosscutters @ Scrappers

Follow on MiLB First Pitch  https //stza.co/+xMBc-1d

Shop  https //stza.co/+xMBc-3p

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Crosscutters @ Scrappers
END:VALARM
DTSTART;VALUE=DATE:20180708
DTEND;VALUE=DATE:20180708
UID:0gZ-FFc6yHayMw9o-ML7uf5I@stanza.co
SUMMARY:Crosscutters @ Scrappers
DESCRIPTION:Crosscutters @ Scrappers\n\nFollow on MiLB First Pitch: https://stza.co/+xMBc-1d\n\nShop: https://stza.co/+xMBc-3p\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144606Z
LAST-MODIFIED:20180213T144606Z
TRANSP:OPAQUE
END:VEVENT
* Crosscutters @ Scrappers
<2018-07-09 Mon>--<2018-07-08 Sun>
:PROPERTIES:
:ID:       McVhABgtQB-5Ac4pzjAgceR3@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Crosscutters @ Scrappers Crosscutters @ Scrappers

Follow on MiLB First Pitch  https //stza.co/+xMBd-c

Shop  https //stza.co/+xMBd-C

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Crosscutters @ Scrappers
END:VALARM
DTSTART;VALUE=DATE:20180709
DTEND;VALUE=DATE:20180709
UID:McVhABgtQB-5Ac4pzjAgceR3@stanza.co
SUMMARY:Crosscutters @ Scrappers
DESCRIPTION:Crosscutters @ Scrappers\n\nFollow on MiLB First Pitch: https://stza.co/+xMBd-c\n\nShop: https://stza.co/+xMBd-C\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144606Z
LAST-MODIFIED:20180213T144606Z
TRANSP:OPAQUE
END:VEVENT
* Crosscutters vs. ValleyCats
<2018-07-11 Wed 18:05-21:05>
:PROPERTIES:
:ID:       kZt5d8xqKwETT5Zq8C0D2oWR@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Crosscutters vs. ValleyCats Crosscutters vs. ValleyCats

Follow on MiLB First Pitch  https //stza.co/+x$6T-2L

Shop  https //stza.co/+x$6T-3

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Crosscutters vs. ValleyCats
END:VALARM
DTSTART:20180711T230500Z
DTEND:20180712T020500Z
UID:kZt5d8xqKwETT5Zq8C0D2oWR@stanza.co
SUMMARY:Crosscutters vs. ValleyCats
DESCRIPTION:Crosscutters vs. ValleyCats\n\nFollow on MiLB First Pitch: https://stza.co/+x$6T-2L\n\nShop: https://stza.co/+x$6T-3\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144606Z
LAST-MODIFIED:20180213T144606Z
TRANSP:OPAQUE
END:VEVENT
* Crosscutters vs. ValleyCats
<2018-07-12 Thu 18:05-21:05>
:PROPERTIES:
:ID:       RyJS4S7JT_BTcovm6jbZZ1ac@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Crosscutters vs. ValleyCats Crosscutters vs. ValleyCats

Follow on MiLB First Pitch  https //stza.co/+x$6W-2c

Shop  https //stza.co/+x$6W-1J

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Crosscutters vs. ValleyCats
END:VALARM
DTSTART:20180712T230500Z
DTEND:20180713T020500Z
UID:RyJS4S7JT_BTcovm6jbZZ1ac@stanza.co
SUMMARY:Crosscutters vs. ValleyCats
DESCRIPTION:Crosscutters vs. ValleyCats\n\nFollow on MiLB First Pitch: https://stza.co/+x$6W-2c\n\nShop: https://stza.co/+x$6W-1J\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144606Z
LAST-MODIFIED:20180213T144606Z
TRANSP:OPAQUE
END:VEVENT
* Crosscutters vs. ValleyCats
<2018-07-13 Fri 18:05-21:05>
:PROPERTIES:
:ID:       1GhbkHGRBanypJ1Ij38LV4MT@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Crosscutters vs. ValleyCats Crosscutters vs. ValleyCats

Follow on MiLB First Pitch  https //stza.co/+x$6X-1x

Shop  https //stza.co/+x$6X-h

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Crosscutters vs. ValleyCats
END:VALARM
DTSTART:20180713T230500Z
DTEND:20180714T020500Z
UID:1GhbkHGRBanypJ1Ij38LV4MT@stanza.co
SUMMARY:Crosscutters vs. ValleyCats
DESCRIPTION:Crosscutters vs. ValleyCats\n\nFollow on MiLB First Pitch: https://stza.co/+x$6X-1x\n\nShop: https://stza.co/+x$6X-h\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144606Z
LAST-MODIFIED:20180213T144606Z
TRANSP:OPAQUE
END:VEVENT
* Crosscutters @ Cyclones
<2018-07-14 Sat>--<2018-07-13 Fri>
:PROPERTIES:
:ID:       1O7wuAtsYDZ-hMRm2c8gedBJ@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Crosscutters @ Cyclones Crosscutters @ Cyclones

Follow on MiLB First Pitch  https //stza.co/+xMB5-14

Shop  https //stza.co/+xMB5-2v

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Crosscutters @ Cyclones
END:VALARM
DTSTART;VALUE=DATE:20180714
DTEND;VALUE=DATE:20180714
UID:1O7wuAtsYDZ-hMRm2c8gedBJ@stanza.co
SUMMARY:Crosscutters @ Cyclones
DESCRIPTION:Crosscutters @ Cyclones\n\nFollow on MiLB First Pitch: https://stza.co/+xMB5-14\n\nShop: https://stza.co/+xMB5-2v\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144606Z
LAST-MODIFIED:20180213T144606Z
TRANSP:OPAQUE
END:VEVENT
* Crosscutters @ Cyclones
<2018-07-15 Sun>--<2018-07-14 Sat>
:PROPERTIES:
:ID:       R144UmLt-90KK_wiEAidyfZA@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Crosscutters @ Cyclones Crosscutters @ Cyclones

Follow on MiLB First Pitch  https //stza.co/+xMB6-3Q

Shop  https //stza.co/+xMB6-15

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Crosscutters @ Cyclones
END:VALARM
DTSTART;VALUE=DATE:20180715
DTEND;VALUE=DATE:20180715
UID:R144UmLt-90KK_wiEAidyfZA@stanza.co
SUMMARY:Crosscutters @ Cyclones
DESCRIPTION:Crosscutters @ Cyclones\n\nFollow on MiLB First Pitch: https://stza.co/+xMB6-3Q\n\nShop: https://stza.co/+xMB6-15\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144606Z
LAST-MODIFIED:20180213T144606Z
TRANSP:OPAQUE
END:VEVENT
* Crosscutters @ Cyclones
<2018-07-16 Mon>--<2018-07-15 Sun>
:PROPERTIES:
:ID:       Zx9P5FBywzn6Sb3iFFg_ayDP@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Crosscutters @ Cyclones Crosscutters @ Cyclones

Follow on MiLB First Pitch  https //stza.co/+xMB7-Y

Shop  https //stza.co/+xMB7-3Z

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Crosscutters @ Cyclones
END:VALARM
DTSTART;VALUE=DATE:20180716
DTEND;VALUE=DATE:20180716
UID:Zx9P5FBywzn6Sb3iFFg_ayDP@stanza.co
SUMMARY:Crosscutters @ Cyclones
DESCRIPTION:Crosscutters @ Cyclones\n\nFollow on MiLB First Pitch: https://stza.co/+xMB7-Y\n\nShop: https://stza.co/+xMB7-3Z\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144606Z
LAST-MODIFIED:20180213T144606Z
TRANSP:OPAQUE
END:VEVENT
* Crosscutters vs. Muckdogs
<2018-07-17 Tue 18:05-21:05>
:PROPERTIES:
:ID:       U3YRpGM7tMEHGIDr_btytVHg@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Crosscutters vs. Muckdogs Crosscutters vs. Muckdogs

Follow on MiLB First Pitch  https //stza.co/+x$6Z-3p

Shop  https //stza.co/+x$6Z-36

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Crosscutters vs. Muckdogs
END:VALARM
DTSTART:20180717T230500Z
DTEND:20180718T020500Z
UID:U3YRpGM7tMEHGIDr_btytVHg@stanza.co
SUMMARY:Crosscutters vs. Muckdogs
DESCRIPTION:Crosscutters vs. Muckdogs\n\nFollow on MiLB First Pitch: https://stza.co/+x$6Z-3p\n\nShop: https://stza.co/+x$6Z-36\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144606Z
LAST-MODIFIED:20180213T144606Z
TRANSP:OPAQUE
END:VEVENT
* Crosscutters vs. Muckdogs
<2018-07-18 Wed 18:05-21:05>
:PROPERTIES:
:ID:       nqqQRxvFaQCy2MemkIdVkqJL@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Crosscutters vs. Muckdogs Crosscutters vs. Muckdogs

Follow on MiLB First Pitch  https //stza.co/+x$6$-1j

Shop  https //stza.co/+x$6$-2P

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Crosscutters vs. Muckdogs
END:VALARM
DTSTART:20180718T230500Z
DTEND:20180719T020500Z
UID:nqqQRxvFaQCy2MemkIdVkqJL@stanza.co
SUMMARY:Crosscutters vs. Muckdogs
DESCRIPTION:Crosscutters vs. Muckdogs\n\nFollow on MiLB First Pitch: https://stza.co/+x$6$-1j\n\nShop: https://stza.co/+x$6$-2P\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144606Z
LAST-MODIFIED:20180213T144606Z
TRANSP:OPAQUE
END:VEVENT
* Crosscutters vs. Muckdogs
<2018-07-19 Thu 18:05-21:05>
:PROPERTIES:
:ID:       0ZnZjYt7uJ6rYxnAKVDQmvtM@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Crosscutters vs. Muckdogs Crosscutters vs. Muckdogs

Follow on MiLB First Pitch  https //stza.co/+x$71-v

Shop  https //stza.co/+x$71-3j

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Crosscutters vs. Muckdogs
END:VALARM
DTSTART:20180719T230500Z
DTEND:20180720T020500Z
UID:0ZnZjYt7uJ6rYxnAKVDQmvtM@stanza.co
SUMMARY:Crosscutters vs. Muckdogs
DESCRIPTION:Crosscutters vs. Muckdogs\n\nFollow on MiLB First Pitch: https://stza.co/+x$71-v\n\nShop: https://stza.co/+x$71-3j\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144606Z
LAST-MODIFIED:20180213T144606Z
TRANSP:OPAQUE
END:VEVENT
* Crosscutters vs. Black Bears
<2018-07-20 Fri 18:05-21:05>
:PROPERTIES:
:ID:       UnpatLP6W763OJW9Zc0-_ucm@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Crosscutters vs. Black Bears Crosscutters vs. Black Bears

Follow on MiLB First Pitch  https //stza.co/+x$74-1x

Shop  https //stza.co/+x$74-2D

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Crosscutters vs. Black Bears
END:VALARM
DTSTART:20180720T230500Z
DTEND:20180721T020500Z
UID:UnpatLP6W763OJW9Zc0-_ucm@stanza.co
SUMMARY:Crosscutters vs. Black Bears
DESCRIPTION:Crosscutters vs. Black Bears\n\nFollow on MiLB First Pitch: https://stza.co/+x$74-1x\n\nShop: https://stza.co/+x$74-2D\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144606Z
LAST-MODIFIED:20180213T144606Z
TRANSP:OPAQUE
END:VEVENT
* Crosscutters vs. Black Bears
<2018-07-21 Sat 18:05-21:05>
:PROPERTIES:
:ID:       aXi1DZFty8AM29oBqjVdrXVW@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Crosscutters vs. Black Bears Crosscutters vs. Black Bears

Follow on MiLB First Pitch  https //stza.co/+x$75-1L

Shop  https //stza.co/+x$75-1H

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Crosscutters vs. Black Bears
END:VALARM
DTSTART:20180721T230500Z
DTEND:20180722T020500Z
UID:aXi1DZFty8AM29oBqjVdrXVW@stanza.co
SUMMARY:Crosscutters vs. Black Bears
DESCRIPTION:Crosscutters vs. Black Bears\n\nFollow on MiLB First Pitch: https://stza.co/+x$75-1L\n\nShop: https://stza.co/+x$75-1H\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144606Z
LAST-MODIFIED:20180213T144606Z
TRANSP:OPAQUE
END:VEVENT
* Crosscutters vs. Black Bears
<2018-07-22 Sun 16:05-19:05>
:PROPERTIES:
:ID:       DsxY7yCRajBErn8aENA490Zk@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Crosscutters vs. Black Bears Crosscutters vs. Black Bears

Follow on MiLB First Pitch  https //stza.co/+x$78-j

Shop  https //stza.co/+x$78-1S

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Crosscutters vs. Black Bears
END:VALARM
DTSTART:20180722T210500Z
DTEND:20180723T000500Z
UID:DsxY7yCRajBErn8aENA490Zk@stanza.co
SUMMARY:Crosscutters vs. Black Bears
DESCRIPTION:Crosscutters vs. Black Bears\n\nFollow on MiLB First Pitch: https://stza.co/+x$78-j\n\nShop: https://stza.co/+x$78-1S\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144606Z
LAST-MODIFIED:20180213T144606Z
TRANSP:OPAQUE
END:VEVENT
* Crosscutters @ Lake Monsters
<2018-07-24 Tue>--<2018-07-23 Mon>
:PROPERTIES:
:ID:       ts68WupvWioBREQumRYN08j6@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Crosscutters @ Lake Monsters Crosscutters @ Lake Monsters

Follow on MiLB First Pitch  https //stza.co/+xMBm-2B

Shop  https //stza.co/+xMBm-2_

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Crosscutters @ Lake Monsters
END:VALARM
DTSTART;VALUE=DATE:20180724
DTEND;VALUE=DATE:20180724
UID:ts68WupvWioBREQumRYN08j6@stanza.co
SUMMARY:Crosscutters @ Lake Monsters
DESCRIPTION:Crosscutters @ Lake Monsters\n\nFollow on MiLB First Pitch: https://stza.co/+xMBm-2B\n\nShop: https://stza.co/+xMBm-2_\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144606Z
LAST-MODIFIED:20180213T144606Z
TRANSP:OPAQUE
END:VEVENT
* Crosscutters @ Lake Monsters
<2018-07-25 Wed>--<2018-07-24 Tue>
:PROPERTIES:
:ID:       2KiYkG7IkAsZmCrRXEyCg5n0@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Crosscutters @ Lake Monsters Crosscutters @ Lake Monsters

Follow on MiLB First Pitch  https //stza.co/+xMBn-2B

Shop  https //stza.co/+xMBn-17

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Crosscutters @ Lake Monsters
END:VALARM
DTSTART;VALUE=DATE:20180725
DTEND;VALUE=DATE:20180725
UID:2KiYkG7IkAsZmCrRXEyCg5n0@stanza.co
SUMMARY:Crosscutters @ Lake Monsters
DESCRIPTION:Crosscutters @ Lake Monsters\n\nFollow on MiLB First Pitch: https://stza.co/+xMBn-2B\n\nShop: https://stza.co/+xMBn-17\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144606Z
LAST-MODIFIED:20180213T144606Z
TRANSP:OPAQUE
END:VEVENT
* Crosscutters @ Lake Monsters
<2018-07-26 Thu>--<2018-07-25 Wed>
:PROPERTIES:
:ID:       SgSeing2CMy4ispVvLo90PTu@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Crosscutters @ Lake Monsters Crosscutters @ Lake Monsters

Follow on MiLB First Pitch  https //stza.co/+xMBo-N

Shop  https //stza.co/+xMBo-t

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Crosscutters @ Lake Monsters
END:VALARM
DTSTART;VALUE=DATE:20180726
DTEND;VALUE=DATE:20180726
UID:SgSeing2CMy4ispVvLo90PTu@stanza.co
SUMMARY:Crosscutters @ Lake Monsters
DESCRIPTION:Crosscutters @ Lake Monsters\n\nFollow on MiLB First Pitch: https://stza.co/+xMBo-N\n\nShop: https://stza.co/+xMBo-t\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144606Z
LAST-MODIFIED:20180213T144606Z
TRANSP:OPAQUE
END:VEVENT
* Crosscutters vs. Renegades
<2018-07-27 Fri 18:05-21:05>
:PROPERTIES:
:ID:       v5wcg5vB43CND_X_ExjqtJ7k@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Crosscutters vs. Renegades Crosscutters vs. Renegades

Follow on MiLB First Pitch  https //stza.co/+x$7a-3y

Shop  https //stza.co/+x$7a-3f

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Crosscutters vs. Renegades
END:VALARM
DTSTART:20180727T230500Z
DTEND:20180728T020500Z
UID:v5wcg5vB43CND_X_ExjqtJ7k@stanza.co
SUMMARY:Crosscutters vs. Renegades
DESCRIPTION:Crosscutters vs. Renegades\n\nFollow on MiLB First Pitch: https://stza.co/+x$7a-3y\n\nShop: https://stza.co/+x$7a-3f\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144606Z
LAST-MODIFIED:20180213T144606Z
TRANSP:OPAQUE
END:VEVENT
* Crosscutters vs. Renegades
<2018-07-28 Sat 18:05-21:05>
:PROPERTIES:
:ID:       ZA3EsBUzAHBnnhS3cWrpEodz@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Crosscutters vs. Renegades Crosscutters vs. Renegades

Follow on MiLB First Pitch  https //stza.co/+x$7c-38

Shop  https //stza.co/+x$7c-2q

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Crosscutters vs. Renegades
END:VALARM
DTSTART:20180728T230500Z
DTEND:20180729T020500Z
UID:ZA3EsBUzAHBnnhS3cWrpEodz@stanza.co
SUMMARY:Crosscutters vs. Renegades
DESCRIPTION:Crosscutters vs. Renegades\n\nFollow on MiLB First Pitch: https://stza.co/+x$7c-38\n\nShop: https://stza.co/+x$7c-2q\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144606Z
LAST-MODIFIED:20180213T144606Z
TRANSP:OPAQUE
END:VEVENT
* Crosscutters vs. Renegades
<2018-07-29 Sun 16:05-19:05>
:PROPERTIES:
:ID:       bdxztniaS8CN-FdB5XKziBU_@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Crosscutters vs. Renegades Crosscutters vs. Renegades

Follow on MiLB First Pitch  https //stza.co/+x$7e-l

Shop  https //stza.co/+x$7e-z

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Crosscutters vs. Renegades
END:VALARM
DTSTART:20180729T210500Z
DTEND:20180730T000500Z
UID:bdxztniaS8CN-FdB5XKziBU_@stanza.co
SUMMARY:Crosscutters vs. Renegades
DESCRIPTION:Crosscutters vs. Renegades\n\nFollow on MiLB First Pitch: https://stza.co/+x$7e-l\n\nShop: https://stza.co/+x$7e-z\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144606Z
LAST-MODIFIED:20180213T144606Z
TRANSP:OPAQUE
END:VEVENT
* Crosscutters @ Scrappers
<2018-07-30 Mon>--<2018-07-29 Sun>
:PROPERTIES:
:ID:       BPqi-LpAFk3-BB5HtflDBCq9@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Crosscutters @ Scrappers Crosscutters @ Scrappers

Follow on MiLB First Pitch  https //stza.co/+xMBe-1j

Shop  https //stza.co/+xMBe-31

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Crosscutters @ Scrappers
END:VALARM
DTSTART;VALUE=DATE:20180730
DTEND;VALUE=DATE:20180730
UID:BPqi-LpAFk3-BB5HtflDBCq9@stanza.co
SUMMARY:Crosscutters @ Scrappers
DESCRIPTION:Crosscutters @ Scrappers\n\nFollow on MiLB First Pitch: https://stza.co/+xMBe-1j\n\nShop: https://stza.co/+xMBe-31\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144606Z
LAST-MODIFIED:20180213T144606Z
TRANSP:OPAQUE
END:VEVENT
* Crosscutters @ Scrappers
<2018-07-31 Tue>--<2018-07-30 Mon>
:PROPERTIES:
:ID:       0894EnDBgUCs_53wW-6KO_lA@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Crosscutters @ Scrappers Crosscutters @ Scrappers

Follow on MiLB First Pitch  https //stza.co/+xMBf-3C

Shop  https //stza.co/+xMBf-3V

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Crosscutters @ Scrappers
END:VALARM
DTSTART;VALUE=DATE:20180731
DTEND;VALUE=DATE:20180731
UID:0894EnDBgUCs_53wW-6KO_lA@stanza.co
SUMMARY:Crosscutters @ Scrappers
DESCRIPTION:Crosscutters @ Scrappers\n\nFollow on MiLB First Pitch: https://stza.co/+xMBf-3C\n\nShop: https://stza.co/+xMBf-3V\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144606Z
LAST-MODIFIED:20180213T144606Z
TRANSP:OPAQUE
END:VEVENT
* Crosscutters @ Scrappers
<2018-08-01 Wed>--<2018-07-31 Tue>
:PROPERTIES:
:ID:       XXcpVjKJRDY85Jsx0tXljW5i@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Crosscutters @ Scrappers Crosscutters @ Scrappers

Follow on MiLB First Pitch  https //stza.co/+xMBg-10

Shop  https //stza.co/+xMBg-n

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Crosscutters @ Scrappers
END:VALARM
DTSTART;VALUE=DATE:20180801
DTEND;VALUE=DATE:20180801
UID:XXcpVjKJRDY85Jsx0tXljW5i@stanza.co
SUMMARY:Crosscutters @ Scrappers
DESCRIPTION:Crosscutters @ Scrappers\n\nFollow on MiLB First Pitch: https://stza.co/+xMBg-10\n\nShop: https://stza.co/+xMBg-n\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144606Z
LAST-MODIFIED:20180213T144606Z
TRANSP:OPAQUE
END:VEVENT
* Crosscutters vs. Black Bears
<2018-08-02 Thu 18:05-21:05>
:PROPERTIES:
:ID:       r5hjzDRp4o-EOcv8pLTLcLyr@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Crosscutters vs. Black Bears Crosscutters vs. Black Bears

Follow on MiLB First Pitch  https //stza.co/+x$7f-1p

Shop  https //stza.co/+x$7f-3L

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Crosscutters vs. Black Bears
END:VALARM
DTSTART:20180802T230500Z
DTEND:20180803T020500Z
UID:r5hjzDRp4o-EOcv8pLTLcLyr@stanza.co
SUMMARY:Crosscutters vs. Black Bears
DESCRIPTION:Crosscutters vs. Black Bears\n\nFollow on MiLB First Pitch: https://stza.co/+x$7f-1p\n\nShop: https://stza.co/+x$7f-3L\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144606Z
LAST-MODIFIED:20180213T144606Z
TRANSP:OPAQUE
END:VEVENT
* Crosscutters vs. Black Bears
<2018-08-03 Fri 18:05-21:05>
:PROPERTIES:
:ID:       Z20z8DmjkI3WjcLGjyUhrPJy@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Crosscutters vs. Black Bears Crosscutters vs. Black Bears

Follow on MiLB First Pitch  https //stza.co/+x$7i-2B

Shop  https //stza.co/+x$7i-3k

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Crosscutters vs. Black Bears
END:VALARM
DTSTART:20180803T230500Z
DTEND:20180804T020500Z
UID:Z20z8DmjkI3WjcLGjyUhrPJy@stanza.co
SUMMARY:Crosscutters vs. Black Bears
DESCRIPTION:Crosscutters vs. Black Bears\n\nFollow on MiLB First Pitch: https://stza.co/+x$7i-2B\n\nShop: https://stza.co/+x$7i-3k\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144606Z
LAST-MODIFIED:20180213T144606Z
TRANSP:OPAQUE
END:VEVENT
* Crosscutters vs. Black Bears
<2018-08-04 Sat 18:05-21:05>
:PROPERTIES:
:ID:       NWKYesez8vT2ssKBUiN45cRI@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Crosscutters vs. Black Bears Crosscutters vs. Black Bears

Follow on MiLB First Pitch  https //stza.co/+x$7j-3u

Shop  https //stza.co/+x$7j-1O

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Crosscutters vs. Black Bears
END:VALARM
DTSTART:20180804T230500Z
DTEND:20180805T020500Z
UID:NWKYesez8vT2ssKBUiN45cRI@stanza.co
SUMMARY:Crosscutters vs. Black Bears
DESCRIPTION:Crosscutters vs. Black Bears\n\nFollow on MiLB First Pitch: https://stza.co/+x$7j-3u\n\nShop: https://stza.co/+x$7j-1O\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144606Z
LAST-MODIFIED:20180213T144606Z
TRANSP:OPAQUE
END:VEVENT
* Crosscutters @ Doubledays
<2018-08-05 Sun 13:00-16:00>
:PROPERTIES:
:ID:       gwOK8p8ndP7HD_8xEbmtDO7Y@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Crosscutters @ Doubledays Crosscutters @ Doubledays

Follow on MiLB First Pitch  https //stza.co/+xW1V-34

Shop  https //stza.co/+xW1V-1G

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Crosscutters @ Doubledays
END:VALARM
DTSTART:20180805T180000Z
DTEND:20180805T210000Z
UID:gwOK8p8ndP7HD_8xEbmtDO7Y@stanza.co
SUMMARY:Crosscutters @ Doubledays
DESCRIPTION:Crosscutters @ Doubledays\n\nFollow on MiLB First Pitch: https://stza.co/+xW1V-34\n\nShop: https://stza.co/+xW1V-1G\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144606Z
LAST-MODIFIED:20180213T144606Z
TRANSP:OPAQUE
END:VEVENT
* Crosscutters @ Doubledays
<2018-08-06 Mon 17:30-20:30>
:PROPERTIES:
:ID:       Alot9ukwMYv4QR1Keh9iein2@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Crosscutters @ Doubledays Crosscutters @ Doubledays

Follow on MiLB First Pitch  https //stza.co/+xW1W-k

Shop  https //stza.co/+xW1W-R

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Crosscutters @ Doubledays
END:VALARM
DTSTART:20180806T223000Z
DTEND:20180807T013000Z
UID:Alot9ukwMYv4QR1Keh9iein2@stanza.co
SUMMARY:Crosscutters @ Doubledays
DESCRIPTION:Crosscutters @ Doubledays\n\nFollow on MiLB First Pitch: https://stza.co/+xW1W-k\n\nShop: https://stza.co/+xW1W-R\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144606Z
LAST-MODIFIED:20180213T144606Z
TRANSP:OPAQUE
END:VEVENT
* Crosscutters @ Doubledays
<2018-08-07 Tue 17:30-20:30>
:PROPERTIES:
:ID:       VUv5Dlhf_QhajcbzojNszEga@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Crosscutters @ Doubledays Crosscutters @ Doubledays

Follow on MiLB First Pitch  https //stza.co/+xW1X-i

Shop  https //stza.co/+xW1X-21

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Crosscutters @ Doubledays
END:VALARM
DTSTART:20180807T223000Z
DTEND:20180808T013000Z
UID:VUv5Dlhf_QhajcbzojNszEga@stanza.co
SUMMARY:Crosscutters @ Doubledays
DESCRIPTION:Crosscutters @ Doubledays\n\nFollow on MiLB First Pitch: https://stza.co/+xW1X-i\n\nShop: https://stza.co/+xW1X-21\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144606Z
LAST-MODIFIED:20180213T144606Z
TRANSP:OPAQUE
END:VEVENT
* Crosscutters vs. Scrappers
<2018-08-08 Wed 18:05-21:05>
:PROPERTIES:
:ID:       83rYoWOfkStjNetlBJ8QuTSL@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Crosscutters vs. Scrappers Crosscutters vs. Scrappers

Follow on MiLB First Pitch  https //stza.co/+x$7m-S

Shop  https //stza.co/+x$7m-3c

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Crosscutters vs. Scrappers
END:VALARM
DTSTART:20180808T230500Z
DTEND:20180809T020500Z
UID:83rYoWOfkStjNetlBJ8QuTSL@stanza.co
SUMMARY:Crosscutters vs. Scrappers
DESCRIPTION:Crosscutters vs. Scrappers\n\nFollow on MiLB First Pitch: https://stza.co/+x$7m-S\n\nShop: https://stza.co/+x$7m-3c\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144606Z
LAST-MODIFIED:20180213T144606Z
TRANSP:OPAQUE
END:VEVENT
* Crosscutters vs. Scrappers
<2018-08-09 Thu 18:05-21:05>
:PROPERTIES:
:ID:       tjK28Ck9zE2YZix7lB3016-V@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Crosscutters vs. Scrappers Crosscutters vs. Scrappers

Follow on MiLB First Pitch  https //stza.co/+x$7o-3y

Shop  https //stza.co/+x$7o-3a

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Crosscutters vs. Scrappers
END:VALARM
DTSTART:20180809T230500Z
DTEND:20180810T020500Z
UID:tjK28Ck9zE2YZix7lB3016-V@stanza.co
SUMMARY:Crosscutters vs. Scrappers
DESCRIPTION:Crosscutters vs. Scrappers\n\nFollow on MiLB First Pitch: https://stza.co/+x$7o-3y\n\nShop: https://stza.co/+x$7o-3a\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144606Z
LAST-MODIFIED:20180213T144606Z
TRANSP:OPAQUE
END:VEVENT
* Crosscutters vs. Scrappers
<2018-08-10 Fri 18:05-21:05>
:PROPERTIES:
:ID:       cNNGSCtj1_r5cI98bjLMwF5n@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Crosscutters vs. Scrappers Crosscutters vs. Scrappers

Follow on MiLB First Pitch  https //stza.co/+x$7p-4

Shop  https //stza.co/+x$7p-3S

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Crosscutters vs. Scrappers
END:VALARM
DTSTART:20180810T230500Z
DTEND:20180811T020500Z
UID:cNNGSCtj1_r5cI98bjLMwF5n@stanza.co
SUMMARY:Crosscutters vs. Scrappers
DESCRIPTION:Crosscutters vs. Scrappers\n\nFollow on MiLB First Pitch: https://stza.co/+x$7p-4\n\nShop: https://stza.co/+x$7p-3S\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144606Z
LAST-MODIFIED:20180213T144606Z
TRANSP:OPAQUE
END:VEVENT
* Crosscutters vs. Muckdogs
<2018-08-11 Sat 18:05-21:05>
:PROPERTIES:
:ID:       Y83R9ybxv_tu6c87J1jzehgL@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Crosscutters vs. Muckdogs Crosscutters vs. Muckdogs

Follow on MiLB First Pitch  https //stza.co/+x$7s-X

Shop  https //stza.co/+x$7s-1Z

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Crosscutters vs. Muckdogs
END:VALARM
DTSTART:20180811T230500Z
DTEND:20180812T020500Z
UID:Y83R9ybxv_tu6c87J1jzehgL@stanza.co
SUMMARY:Crosscutters vs. Muckdogs
DESCRIPTION:Crosscutters vs. Muckdogs\n\nFollow on MiLB First Pitch: https://stza.co/+x$7s-X\n\nShop: https://stza.co/+x$7s-1Z\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144606Z
LAST-MODIFIED:20180213T144606Z
TRANSP:OPAQUE
END:VEVENT
* Crosscutters vs. Muckdogs
<2018-08-12 Sun 16:05-19:05>
:PROPERTIES:
:ID:       OT6h1ULIqJADmpg1ONecsYBG@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Crosscutters vs. Muckdogs Crosscutters vs. Muckdogs

Follow on MiLB First Pitch  https //stza.co/+x$7t-1J

Shop  https //stza.co/+x$7t-6

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Crosscutters vs. Muckdogs
END:VALARM
DTSTART:20180812T210500Z
DTEND:20180813T000500Z
UID:OT6h1ULIqJADmpg1ONecsYBG@stanza.co
SUMMARY:Crosscutters vs. Muckdogs
DESCRIPTION:Crosscutters vs. Muckdogs\n\nFollow on MiLB First Pitch: https://stza.co/+x$7t-1J\n\nShop: https://stza.co/+x$7t-6\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144606Z
LAST-MODIFIED:20180213T144606Z
TRANSP:OPAQUE
END:VEVENT
* Crosscutters @ Spikes
<2018-08-15 Wed>--<2018-08-14 Tue>
:PROPERTIES:
:ID:       oqobRP4pzXqZLU3H9DUC0jso@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Crosscutters @ Spikes Crosscutters @ Spikes

Follow on MiLB First Pitch  https //stza.co/+xMBj-1x

Shop  https //stza.co/+xMBj-1o

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Crosscutters @ Spikes
END:VALARM
DTSTART;VALUE=DATE:20180815
DTEND;VALUE=DATE:20180815
UID:oqobRP4pzXqZLU3H9DUC0jso@stanza.co
SUMMARY:Crosscutters @ Spikes
DESCRIPTION:Crosscutters @ Spikes\n\nFollow on MiLB First Pitch: https://stza.co/+xMBj-1x\n\nShop: https://stza.co/+xMBj-1o\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144606Z
LAST-MODIFIED:20180213T144606Z
TRANSP:OPAQUE
END:VEVENT
* Crosscutters @ Spikes
<2018-08-16 Thu>--<2018-08-15 Wed>
:PROPERTIES:
:ID:       jURTbS8Shz5BcofouAtbo74Q@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Crosscutters @ Spikes Crosscutters @ Spikes

Follow on MiLB First Pitch  https //stza.co/+xMBk-39

Shop  https //stza.co/+xMBk-o

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Crosscutters @ Spikes
END:VALARM
DTSTART;VALUE=DATE:20180816
DTEND;VALUE=DATE:20180816
UID:jURTbS8Shz5BcofouAtbo74Q@stanza.co
SUMMARY:Crosscutters @ Spikes
DESCRIPTION:Crosscutters @ Spikes\n\nFollow on MiLB First Pitch: https://stza.co/+xMBk-39\n\nShop: https://stza.co/+xMBk-o\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144606Z
LAST-MODIFIED:20180213T144606Z
TRANSP:OPAQUE
END:VEVENT
* Crosscutters @ Black Bears
<2018-08-17 Fri 18:05-21:05>
:PROPERTIES:
:ID:       t54azNoaxVUDpVI2j0XV4NnK@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Crosscutters @ Black Bears Crosscutters @ Black Bears

Follow on MiLB First Pitch  https //stza.co/+xW22-2y

Shop  https //stza.co/+xW22-3u

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Crosscutters @ Black Bears
END:VALARM
DTSTART:20180817T230500Z
DTEND:20180818T020500Z
UID:t54azNoaxVUDpVI2j0XV4NnK@stanza.co
SUMMARY:Crosscutters @ Black Bears
DESCRIPTION:Crosscutters @ Black Bears\n\nFollow on MiLB First Pitch: https://stza.co/+xW22-2y\n\nShop: https://stza.co/+xW22-3u\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144606Z
LAST-MODIFIED:20180213T144606Z
TRANSP:OPAQUE
END:VEVENT
* Crosscutters @ Black Bears
<2018-08-18 Sat 18:05-21:05>
:PROPERTIES:
:ID:       wcLuy6dmprI0CsRNCUgc_mMQ@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Crosscutters @ Black Bears Crosscutters @ Black Bears

Follow on MiLB First Pitch  https //stza.co/+xW23-R

Shop  https //stza.co/+xW23-2i

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Crosscutters @ Black Bears
END:VALARM
DTSTART:20180818T230500Z
DTEND:20180819T020500Z
UID:wcLuy6dmprI0CsRNCUgc_mMQ@stanza.co
SUMMARY:Crosscutters @ Black Bears
DESCRIPTION:Crosscutters @ Black Bears\n\nFollow on MiLB First Pitch: https://stza.co/+xW23-R\n\nShop: https://stza.co/+xW23-2i\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144606Z
LAST-MODIFIED:20180213T144606Z
TRANSP:OPAQUE
END:VEVENT
* Crosscutters @ Black Bears
<2018-08-19 Sun 15:05-18:05>
:PROPERTIES:
:ID:       2t0LdHoUdVyIJfjPqdONTxk-@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Crosscutters @ Black Bears Crosscutters @ Black Bears

Follow on MiLB First Pitch  https //stza.co/+xW24-1P

Shop  https //stza.co/+xW24-e

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Crosscutters @ Black Bears
END:VALARM
DTSTART:20180819T200500Z
DTEND:20180819T230500Z
UID:2t0LdHoUdVyIJfjPqdONTxk-@stanza.co
SUMMARY:Crosscutters @ Black Bears
DESCRIPTION:Crosscutters @ Black Bears\n\nFollow on MiLB First Pitch: https://stza.co/+xW24-1P\n\nShop: https://stza.co/+xW24-e\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144606Z
LAST-MODIFIED:20180213T144606Z
TRANSP:OPAQUE
END:VEVENT
* Crosscutters @ Spikes
<2018-08-20 Mon>--<2018-08-19 Sun>
:PROPERTIES:
:ID:       iR3SjAX67m6Sj_VzApmK6Kss@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Crosscutters @ Spikes Crosscutters @ Spikes

Follow on MiLB First Pitch  https //stza.co/+xMBl-7

Shop  https //stza.co/+xMBl-2r

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Crosscutters @ Spikes
END:VALARM
DTSTART;VALUE=DATE:20180820
DTEND;VALUE=DATE:20180820
UID:iR3SjAX67m6Sj_VzApmK6Kss@stanza.co
SUMMARY:Crosscutters @ Spikes
DESCRIPTION:Crosscutters @ Spikes\n\nFollow on MiLB First Pitch: https://stza.co/+xMBl-7\n\nShop: https://stza.co/+xMBl-2r\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144606Z
LAST-MODIFIED:20180213T144606Z
TRANSP:OPAQUE
END:VEVENT
* Crosscutters vs. Spikes
<2018-08-21 Tue 18:05-21:05>
:PROPERTIES:
:ID:       -BLPu4Nlx89eLmq5KPqEogOW@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Crosscutters vs. Spikes Crosscutters vs. Spikes

Follow on MiLB First Pitch  https //stza.co/+x$7v-10

Shop  https //stza.co/+x$7v-E

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Crosscutters vs. Spikes
END:VALARM
DTSTART:20180821T230500Z
DTEND:20180822T020500Z
UID:-BLPu4Nlx89eLmq5KPqEogOW@stanza.co
SUMMARY:Crosscutters vs. Spikes
DESCRIPTION:Crosscutters vs. Spikes\n\nFollow on MiLB First Pitch: https://stza.co/+x$7v-10\n\nShop: https://stza.co/+x$7v-E\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144606Z
LAST-MODIFIED:20180213T144606Z
TRANSP:OPAQUE
END:VEVENT
* Crosscutters vs. Spikes
<2018-08-22 Wed 18:05-21:05>
:PROPERTIES:
:ID:       U0uqOGKKfslVOL6ohEjTLLZB@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Crosscutters vs. Spikes Crosscutters vs. Spikes

Follow on MiLB First Pitch  https //stza.co/+x$7y-2$

Shop  https //stza.co/+x$7y-19

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Crosscutters vs. Spikes
END:VALARM
DTSTART:20180822T230500Z
DTEND:20180823T020500Z
UID:U0uqOGKKfslVOL6ohEjTLLZB@stanza.co
SUMMARY:Crosscutters vs. Spikes
DESCRIPTION:Crosscutters vs. Spikes\n\nFollow on MiLB First Pitch: https://stza.co/+x$7y-2$\n\nShop: https://stza.co/+x$7y-19\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144606Z
LAST-MODIFIED:20180213T144606Z
TRANSP:OPAQUE
END:VEVENT
* Crosscutters @ Muckdogs
<2018-08-23 Thu>--<2018-08-22 Wed>
:PROPERTIES:
:ID:       t3PDCnmJgVz-vRiIwFXCQARC@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Crosscutters @ Muckdogs Crosscutters @ Muckdogs

Follow on MiLB First Pitch  https //stza.co/+xMB2-2l

Shop  https //stza.co/+xMB2-e

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Crosscutters @ Muckdogs
END:VALARM
DTSTART;VALUE=DATE:20180823
DTEND;VALUE=DATE:20180823
UID:t3PDCnmJgVz-vRiIwFXCQARC@stanza.co
SUMMARY:Crosscutters @ Muckdogs
DESCRIPTION:Crosscutters @ Muckdogs\n\nFollow on MiLB First Pitch: https://stza.co/+xMB2-2l\n\nShop: https://stza.co/+xMB2-e\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144606Z
LAST-MODIFIED:20180213T144606Z
TRANSP:OPAQUE
END:VEVENT
* Crosscutters @ Muckdogs
<2018-08-24 Fri>--<2018-08-23 Thu>
:PROPERTIES:
:ID:       5Wc5jkKhGLsZwb8uXpEvq9hm@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Crosscutters @ Muckdogs Crosscutters @ Muckdogs

Follow on MiLB First Pitch  https //stza.co/+xMB3-_

Shop  https //stza.co/+xMB3-3R

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Crosscutters @ Muckdogs
END:VALARM
DTSTART;VALUE=DATE:20180824
DTEND;VALUE=DATE:20180824
UID:5Wc5jkKhGLsZwb8uXpEvq9hm@stanza.co
SUMMARY:Crosscutters @ Muckdogs
DESCRIPTION:Crosscutters @ Muckdogs\n\nFollow on MiLB First Pitch: https://stza.co/+xMB3-_\n\nShop: https://stza.co/+xMB3-3R\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144606Z
LAST-MODIFIED:20180213T144606Z
TRANSP:OPAQUE
END:VEVENT
* Crosscutters @ Muckdogs
<2018-08-25 Sat>--<2018-08-24 Fri>
:PROPERTIES:
:ID:       6sgx-2PswjfhJiiMdtdBGKXY@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Crosscutters @ Muckdogs Crosscutters @ Muckdogs

Follow on MiLB First Pitch  https //stza.co/+xMB4-d

Shop  https //stza.co/+xMB4-3N

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Crosscutters @ Muckdogs
END:VALARM
DTSTART;VALUE=DATE:20180825
DTEND;VALUE=DATE:20180825
UID:6sgx-2PswjfhJiiMdtdBGKXY@stanza.co
SUMMARY:Crosscutters @ Muckdogs
DESCRIPTION:Crosscutters @ Muckdogs\n\nFollow on MiLB First Pitch: https://stza.co/+xMB4-d\n\nShop: https://stza.co/+xMB4-3N\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144606Z
LAST-MODIFIED:20180213T144606Z
TRANSP:OPAQUE
END:VEVENT
* Crosscutters vs. Scrappers
<2018-08-26 Sun 18:05-21:05>
:PROPERTIES:
:ID:       s6JQ-DMNSNrbHHYiWnsx6oXw@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Crosscutters vs. Scrappers Crosscutters vs. Scrappers

Follow on MiLB First Pitch  https //stza.co/+x$7z-I

Shop  https //stza.co/+x$7z-P

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Crosscutters vs. Scrappers
END:VALARM
DTSTART:20180826T230500Z
DTEND:20180827T020500Z
UID:s6JQ-DMNSNrbHHYiWnsx6oXw@stanza.co
SUMMARY:Crosscutters vs. Scrappers
DESCRIPTION:Crosscutters vs. Scrappers\n\nFollow on MiLB First Pitch: https://stza.co/+x$7z-I\n\nShop: https://stza.co/+x$7z-P\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144606Z
LAST-MODIFIED:20180213T144606Z
TRANSP:OPAQUE
END:VEVENT
* Crosscutters vs. Scrappers
<2018-08-27 Mon 18:05-21:05>
:PROPERTIES:
:ID:       OefnFpVc_uHTxkK_Qwc6XMoJ@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Crosscutters vs. Scrappers Crosscutters vs. Scrappers

Follow on MiLB First Pitch  https //stza.co/+x$7C-10

Shop  https //stza.co/+x$7C-1p

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Crosscutters vs. Scrappers
END:VALARM
DTSTART:20180827T230500Z
DTEND:20180828T020500Z
UID:OefnFpVc_uHTxkK_Qwc6XMoJ@stanza.co
SUMMARY:Crosscutters vs. Scrappers
DESCRIPTION:Crosscutters vs. Scrappers\n\nFollow on MiLB First Pitch: https://stza.co/+x$7C-10\n\nShop: https://stza.co/+x$7C-1p\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144606Z
LAST-MODIFIED:20180213T144606Z
TRANSP:OPAQUE
END:VEVENT
* Crosscutters vs. Scrappers
<2018-08-28 Tue 18:05-21:05>
:PROPERTIES:
:ID:       -PycAvV7YJeEitp5_Y0OOhmC@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Crosscutters vs. Scrappers Crosscutters vs. Scrappers

Follow on MiLB First Pitch  https //stza.co/+x$7D-2B

Shop  https //stza.co/+x$7D-j

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Crosscutters vs. Scrappers
END:VALARM
DTSTART:20180828T230500Z
DTEND:20180829T020500Z
UID:-PycAvV7YJeEitp5_Y0OOhmC@stanza.co
SUMMARY:Crosscutters vs. Scrappers
DESCRIPTION:Crosscutters vs. Scrappers\n\nFollow on MiLB First Pitch: https://stza.co/+x$7D-2B\n\nShop: https://stza.co/+x$7D-j\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144606Z
LAST-MODIFIED:20180213T144606Z
TRANSP:OPAQUE
END:VEVENT
* Crosscutters @ Doubledays
<2018-08-29 Wed 17:30-20:30>
:PROPERTIES:
:ID:       W3tMlSHPhP2x80LjQVgp4nhb@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Crosscutters @ Doubledays Crosscutters @ Doubledays

Follow on MiLB First Pitch  https //stza.co/+xW1Y-1G

Shop  https //stza.co/+xW1Y-1X

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Crosscutters @ Doubledays
END:VALARM
DTSTART:20180829T223000Z
DTEND:20180830T013000Z
UID:W3tMlSHPhP2x80LjQVgp4nhb@stanza.co
SUMMARY:Crosscutters @ Doubledays
DESCRIPTION:Crosscutters @ Doubledays\n\nFollow on MiLB First Pitch: https://stza.co/+xW1Y-1G\n\nShop: https://stza.co/+xW1Y-1X\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144606Z
LAST-MODIFIED:20180213T144606Z
TRANSP:OPAQUE
END:VEVENT
* Crosscutters @ Doubledays
<2018-08-30 Thu 17:30-20:30>
:PROPERTIES:
:ID:       BG3IEPx5r-DVcAfbUbik83RM@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Crosscutters @ Doubledays Crosscutters @ Doubledays

Follow on MiLB First Pitch  https //stza.co/+xW1Z-19

Shop  https //stza.co/+xW1Z-1n

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Crosscutters @ Doubledays
END:VALARM
DTSTART:20180830T223000Z
DTEND:20180831T013000Z
UID:BG3IEPx5r-DVcAfbUbik83RM@stanza.co
SUMMARY:Crosscutters @ Doubledays
DESCRIPTION:Crosscutters @ Doubledays\n\nFollow on MiLB First Pitch: https://stza.co/+xW1Z-19\n\nShop: https://stza.co/+xW1Z-1n\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144606Z
LAST-MODIFIED:20180213T144606Z
TRANSP:OPAQUE
END:VEVENT
* Crosscutters @ Doubledays
<2018-08-31 Fri 17:30-20:30>
:PROPERTIES:
:ID:       3JrhRj99ZrBCaHCdX9NDew14@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Crosscutters @ Doubledays Crosscutters @ Doubledays

Follow on MiLB First Pitch  https //stza.co/+xW1_-2t

Shop  https //stza.co/+xW1_-O

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Crosscutters @ Doubledays
END:VALARM
DTSTART:20180831T223000Z
DTEND:20180901T013000Z
UID:3JrhRj99ZrBCaHCdX9NDew14@stanza.co
SUMMARY:Crosscutters @ Doubledays
DESCRIPTION:Crosscutters @ Doubledays\n\nFollow on MiLB First Pitch: https://stza.co/+xW1_-2t\n\nShop: https://stza.co/+xW1_-O\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144606Z
LAST-MODIFIED:20180213T144606Z
TRANSP:OPAQUE
END:VEVENT
* Crosscutters vs. Spikes
<2018-09-01 Sat 18:05-21:05>
:PROPERTIES:
:ID:       W7Y7J24Y9oj10U6lKXcIHUst@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Crosscutters vs. Spikes Crosscutters vs. Spikes

Follow on MiLB First Pitch  https //stza.co/+x$7F-1G

Shop  https //stza.co/+x$7F-14

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Crosscutters vs. Spikes
END:VALARM
DTSTART:20180901T230500Z
DTEND:20180902T020500Z
UID:W7Y7J24Y9oj10U6lKXcIHUst@stanza.co
SUMMARY:Crosscutters vs. Spikes
DESCRIPTION:Crosscutters vs. Spikes\n\nFollow on MiLB First Pitch: https://stza.co/+x$7F-1G\n\nShop: https://stza.co/+x$7F-14\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144606Z
LAST-MODIFIED:20180213T144606Z
TRANSP:OPAQUE
END:VEVENT
* Crosscutters vs. Spikes
<2018-09-02 Sun 16:05-19:05>
:PROPERTIES:
:ID:       EhJ-QLqgCxe-rWkdhrlfpUeI@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Crosscutters vs. Spikes Crosscutters vs. Spikes

Follow on MiLB First Pitch  https //stza.co/+x$7I-2I

Shop  https //stza.co/+x$7I-m

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Crosscutters vs. Spikes
END:VALARM
DTSTART:20180902T210500Z
DTEND:20180903T000500Z
UID:EhJ-QLqgCxe-rWkdhrlfpUeI@stanza.co
SUMMARY:Crosscutters vs. Spikes
DESCRIPTION:Crosscutters vs. Spikes\n\nFollow on MiLB First Pitch: https://stza.co/+x$7I-2I\n\nShop: https://stza.co/+x$7I-m\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144606Z
LAST-MODIFIED:20180213T144606Z
TRANSP:OPAQUE
END:VEVENT
* Crosscutters vs. Spikes
<2018-09-03 Mon 12:05-15:05>
:PROPERTIES:
:ID:       Fi_q8f6yyPD5Cru4A71WmoWR@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Crosscutters vs. Spikes Crosscutters vs. Spikes

Follow on MiLB First Pitch  https //stza.co/+x$7K-1w

Shop  https //stza.co/+x$7K-2a

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Crosscutters vs. Spikes
END:VALARM
DTSTART:20180903T170500Z
DTEND:20180903T200500Z
UID:Fi_q8f6yyPD5Cru4A71WmoWR@stanza.co
SUMMARY:Crosscutters vs. Spikes
DESCRIPTION:Crosscutters vs. Spikes\n\nFollow on MiLB First Pitch: https://stza.co/+x$7K-1w\n\nShop: https://stza.co/+x$7K-2a\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144606Z
LAST-MODIFIED:20180213T144606Z
TRANSP:OPAQUE
END:VEVENT
