#+TITLE:       Main Google calendar entries
#+AUTHOR:      Eric S Fraga
#+EMAIL:       e.fraga@ucl.ac.uk
#+DESCRIPTION: converted using the ical2org awk script
#+CATEGORY:    google
#+STARTUP:     hidestars
#+STARTUP:     overview

* COMMENT original iCal preamble

* Braves vs. Suns
<2018-04-05 Thu 18:00-21:00>
:PROPERTIES:
:ID:       4K7ggEgGbflAb5Jhr-hmXy0F@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Braves vs. Suns Braves vs. Suns

Follow on MiLB First Pitch  https //stza.co/+vN_j-O

Shop  https //stza.co/+vN_j-2r

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Braves vs. Suns
END:VALARM
DTSTART:20180405T230000Z
DTEND:20180406T020000Z
UID:4K7ggEgGbflAb5Jhr-hmXy0F@stanza.co
SUMMARY:Braves vs. Suns
DESCRIPTION:Braves vs. Suns\n\nFollow on MiLB First Pitch: https://stza.co/+vN_j-O\n\nShop: https://stza.co/+vN_j-2r\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Braves vs. Suns
<2018-04-06 Fri 18:00-21:00>
:PROPERTIES:
:ID:       x16K-2BQNARirHJZEnqPnubz@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Braves vs. Suns Braves vs. Suns

Follow on MiLB First Pitch  https //stza.co/+vN_l-2d

Shop  https //stza.co/+vN_l-9

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Braves vs. Suns
END:VALARM
DTSTART:20180406T230000Z
DTEND:20180407T020000Z
UID:x16K-2BQNARirHJZEnqPnubz@stanza.co
SUMMARY:Braves vs. Suns
DESCRIPTION:Braves vs. Suns\n\nFollow on MiLB First Pitch: https://stza.co/+vN_l-2d\n\nShop: https://stza.co/+vN_l-9\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Braves vs. Suns
<2018-04-07 Sat 17:00-20:00>
:PROPERTIES:
:ID:       5sp9vuVAMHdC9Zi06UpzGdNm@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Braves vs. Suns Braves vs. Suns

Follow on MiLB First Pitch  https //stza.co/+vN_n-3q

Shop  https //stza.co/+vN_n-1$

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Braves vs. Suns
END:VALARM
DTSTART:20180407T220000Z
DTEND:20180408T010000Z
UID:5sp9vuVAMHdC9Zi06UpzGdNm@stanza.co
SUMMARY:Braves vs. Suns
DESCRIPTION:Braves vs. Suns\n\nFollow on MiLB First Pitch: https://stza.co/+vN_n-3q\n\nShop: https://stza.co/+vN_n-1$\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Braves vs. Suns
<2018-04-08 Sun 13:00-16:00>
:PROPERTIES:
:ID:       r4pZi2x_--OnCvahTwQTWEJR@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Braves vs. Suns Braves vs. Suns

Follow on MiLB First Pitch  https //stza.co/+vN_o-1N

Shop  https //stza.co/+vN_o-1n

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Braves vs. Suns
END:VALARM
DTSTART:20180408T180000Z
DTEND:20180408T210000Z
UID:r4pZi2x_--OnCvahTwQTWEJR@stanza.co
SUMMARY:Braves vs. Suns
DESCRIPTION:Braves vs. Suns\n\nFollow on MiLB First Pitch: https://stza.co/+vN_o-1N\n\nShop: https://stza.co/+vN_o-1n\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Braves vs. RiverDogs
<2018-04-09 Mon 18:00-21:00>
:PROPERTIES:
:ID:       6qRRBt0Fwf-2YJ2IeOIGGz5p@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Braves vs. RiverDogs Braves vs. RiverDogs

Follow on MiLB First Pitch  https //stza.co/+vN_r-2T

Shop  https //stza.co/+vN_r-3r

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Braves vs. RiverDogs
END:VALARM
DTSTART:20180409T230000Z
DTEND:20180410T020000Z
UID:6qRRBt0Fwf-2YJ2IeOIGGz5p@stanza.co
SUMMARY:Braves vs. RiverDogs
DESCRIPTION:Braves vs. RiverDogs\n\nFollow on MiLB First Pitch: https://stza.co/+vN_r-2T\n\nShop: https://stza.co/+vN_r-3r\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Braves vs. RiverDogs
<2018-04-10 Tue 09:30-12:30>
:PROPERTIES:
:ID:       JL_NdjvS3nT1QIGyfRKq2Ct8@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Braves vs. RiverDogs Braves vs. RiverDogs

Follow on MiLB First Pitch  https //stza.co/+vN_t-1I

Shop  https //stza.co/+vN_t-B

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Braves vs. RiverDogs
END:VALARM
DTSTART:20180410T143000Z
DTEND:20180410T173000Z
UID:JL_NdjvS3nT1QIGyfRKq2Ct8@stanza.co
SUMMARY:Braves vs. RiverDogs
DESCRIPTION:Braves vs. RiverDogs\n\nFollow on MiLB First Pitch: https://stza.co/+vN_t-1I\n\nShop: https://stza.co/+vN_t-B\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Braves vs. RiverDogs
<2018-04-11 Wed 12:00-15:00>
:PROPERTIES:
:ID:       L0oimr-x6w3RPKxkEp-iUQQv@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Braves vs. RiverDogs Braves vs. RiverDogs

Follow on MiLB First Pitch  https //stza.co/+vN_v-14

Shop  https //stza.co/+vN_v-2t

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Braves vs. RiverDogs
END:VALARM
DTSTART:20180411T170000Z
DTEND:20180411T200000Z
UID:L0oimr-x6w3RPKxkEp-iUQQv@stanza.co
SUMMARY:Braves vs. RiverDogs
DESCRIPTION:Braves vs. RiverDogs\n\nFollow on MiLB First Pitch: https://stza.co/+vN_v-14\n\nShop: https://stza.co/+vN_v-2t\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Braves @ Drive
<2018-04-12 Thu 18:05-21:05>
:PROPERTIES:
:ID:       pIv7-qDe2iZm_pmG3PetMgUn@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Braves @ Drive Braves @ Drive

Follow on MiLB First Pitch  https //stza.co/+xF8M-1U

Shop  https //stza.co/+xF8M-a

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Braves @ Drive
END:VALARM
DTSTART:20180412T230500Z
DTEND:20180413T020500Z
UID:pIv7-qDe2iZm_pmG3PetMgUn@stanza.co
SUMMARY:Braves @ Drive
DESCRIPTION:Braves @ Drive\n\nFollow on MiLB First Pitch: https://stza.co/+xF8M-1U\n\nShop: https://stza.co/+xF8M-a\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Braves @ Drive
<2018-04-13 Fri 18:05-21:05>
:PROPERTIES:
:ID:       EiTIX_dpml3PACu4xlpyW54t@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Braves @ Drive Braves @ Drive

Follow on MiLB First Pitch  https //stza.co/+xF8O-1D

Shop  https //stza.co/+xF8O-$

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Braves @ Drive
END:VALARM
DTSTART:20180413T230500Z
DTEND:20180414T020500Z
UID:EiTIX_dpml3PACu4xlpyW54t@stanza.co
SUMMARY:Braves @ Drive
DESCRIPTION:Braves @ Drive\n\nFollow on MiLB First Pitch: https://stza.co/+xF8O-1D\n\nShop: https://stza.co/+xF8O-$\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Braves @ Drive
<2018-04-14 Sat 18:05-21:05>
:PROPERTIES:
:ID:       QSBEVbm1lmS_PKQTNN59GJ9Q@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Braves @ Drive Braves @ Drive

Follow on MiLB First Pitch  https //stza.co/+xF8P-3I

Shop  https //stza.co/+xF8P-2f

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Braves @ Drive
END:VALARM
DTSTART:20180414T230500Z
DTEND:20180415T020500Z
UID:QSBEVbm1lmS_PKQTNN59GJ9Q@stanza.co
SUMMARY:Braves @ Drive
DESCRIPTION:Braves @ Drive\n\nFollow on MiLB First Pitch: https://stza.co/+xF8P-3I\n\nShop: https://stza.co/+xF8P-2f\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Braves @ Drive
<2018-04-15 Sun 15:05-18:05>
:PROPERTIES:
:ID:       cF6Bkvu63kBBDQ2-qKIBvlJ8@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Braves @ Drive Braves @ Drive

Follow on MiLB First Pitch  https //stza.co/+xF8Q-3q

Shop  https //stza.co/+xF8Q-P

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Braves @ Drive
END:VALARM
DTSTART:20180415T200500Z
DTEND:20180415T230500Z
UID:cF6Bkvu63kBBDQ2-qKIBvlJ8@stanza.co
SUMMARY:Braves @ Drive
DESCRIPTION:Braves @ Drive\n\nFollow on MiLB First Pitch: https://stza.co/+xF8Q-3q\n\nShop: https://stza.co/+xF8Q-P\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Braves @ Tourists
<2018-04-16 Mon 18:05-21:05>
:PROPERTIES:
:ID:       TaUMRbpns-cwFeUnz1lOmrI9@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Braves @ Tourists Braves @ Tourists

Follow on MiLB First Pitch  https //stza.co/+vNZg-2M

Shop  https //stza.co/+vNZg-2D

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Braves @ Tourists
END:VALARM
DTSTART:20180416T230500Z
DTEND:20180417T020500Z
UID:TaUMRbpns-cwFeUnz1lOmrI9@stanza.co
SUMMARY:Braves @ Tourists
DESCRIPTION:Braves @ Tourists\n\nFollow on MiLB First Pitch: https://stza.co/+vNZg-2M\n\nShop: https://stza.co/+vNZg-2D\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Braves @ Tourists
<2018-04-17 Tue 18:05-21:05>
:PROPERTIES:
:ID:       lAF5sxCnOrFA5SKNwzjhB-zD@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Braves @ Tourists Braves @ Tourists

Follow on MiLB First Pitch  https //stza.co/+vNZh-a

Shop  https //stza.co/+vNZh-3H

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Braves @ Tourists
END:VALARM
DTSTART:20180417T230500Z
DTEND:20180418T020500Z
UID:lAF5sxCnOrFA5SKNwzjhB-zD@stanza.co
SUMMARY:Braves @ Tourists
DESCRIPTION:Braves @ Tourists\n\nFollow on MiLB First Pitch: https://stza.co/+vNZh-a\n\nShop: https://stza.co/+vNZh-3H\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Braves @ Tourists
<2018-04-18 Wed 18:05-21:05>
:PROPERTIES:
:ID:       egOOl7oQFX0-Ifnwyz4XhIP2@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Braves @ Tourists Braves @ Tourists

Follow on MiLB First Pitch  https //stza.co/+vNZi-2W

Shop  https //stza.co/+vNZi-X

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Braves @ Tourists
END:VALARM
DTSTART:20180418T230500Z
DTEND:20180419T020500Z
UID:egOOl7oQFX0-Ifnwyz4XhIP2@stanza.co
SUMMARY:Braves @ Tourists
DESCRIPTION:Braves @ Tourists\n\nFollow on MiLB First Pitch: https://stza.co/+vNZi-2W\n\nShop: https://stza.co/+vNZi-X\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Braves vs. GreenJackets
<2018-04-19 Thu 18:00-21:00>
:PROPERTIES:
:ID:       VLSf75kfM8RKXHiCWiXGoPal@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Braves vs. GreenJackets Braves vs. GreenJackets

Follow on MiLB First Pitch  https //stza.co/+vN_x-1s

Shop  https //stza.co/+vN_x-1V

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Braves vs. GreenJackets
END:VALARM
DTSTART:20180419T230000Z
DTEND:20180420T020000Z
UID:VLSf75kfM8RKXHiCWiXGoPal@stanza.co
SUMMARY:Braves vs. GreenJackets
DESCRIPTION:Braves vs. GreenJackets\n\nFollow on MiLB First Pitch: https://stza.co/+vN_x-1s\n\nShop: https://stza.co/+vN_x-1V\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Braves vs. GreenJackets
<2018-04-20 Fri 18:00-21:00>
:PROPERTIES:
:ID:       CG7QDvd8bU9PjSxkxNgp_Lj6@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Braves vs. GreenJackets Braves vs. GreenJackets

Follow on MiLB First Pitch  https //stza.co/+vN_z-O

Shop  https //stza.co/+vN_z-J

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Braves vs. GreenJackets
END:VALARM
DTSTART:20180420T230000Z
DTEND:20180421T020000Z
UID:CG7QDvd8bU9PjSxkxNgp_Lj6@stanza.co
SUMMARY:Braves vs. GreenJackets
DESCRIPTION:Braves vs. GreenJackets\n\nFollow on MiLB First Pitch: https://stza.co/+vN_z-O\n\nShop: https://stza.co/+vN_z-J\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Braves vs. GreenJackets
<2018-04-21 Sat 17:00-20:00>
:PROPERTIES:
:ID:       86VeJ9IR488bjapiefzfgSqu@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Braves vs. GreenJackets Braves vs. GreenJackets

Follow on MiLB First Pitch  https //stza.co/+vN_B-n

Shop  https //stza.co/+vN_B-1x

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Braves vs. GreenJackets
END:VALARM
DTSTART:20180421T220000Z
DTEND:20180422T010000Z
UID:86VeJ9IR488bjapiefzfgSqu@stanza.co
SUMMARY:Braves vs. GreenJackets
DESCRIPTION:Braves vs. GreenJackets\n\nFollow on MiLB First Pitch: https://stza.co/+vN_B-n\n\nShop: https://stza.co/+vN_B-1x\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Braves vs. GreenJackets
<2018-04-22 Sun 13:00-16:00>
:PROPERTIES:
:ID:       1u7RAWyFoGTzJfX7kaDgLIh0@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Braves vs. GreenJackets Braves vs. GreenJackets

Follow on MiLB First Pitch  https //stza.co/+vN_D-3K

Shop  https //stza.co/+vN_D-m

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Braves vs. GreenJackets
END:VALARM
DTSTART:20180422T180000Z
DTEND:20180422T210000Z
UID:1u7RAWyFoGTzJfX7kaDgLIh0@stanza.co
SUMMARY:Braves vs. GreenJackets
DESCRIPTION:Braves vs. GreenJackets\n\nFollow on MiLB First Pitch: https://stza.co/+vN_D-3K\n\nShop: https://stza.co/+vN_D-m\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Braves @ Power
<2018-04-23 Mon 18:05-21:05>
:PROPERTIES:
:ID:       OQOSZ5Q6pE77J_B6lc_D4xoY@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Braves @ Power Braves @ Power

Follow on MiLB First Pitch  https //stza.co/+xJ4s-j

Shop  https //stza.co/+xJ4s-1q

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Braves @ Power
END:VALARM
DTSTART:20180423T230500Z
DTEND:20180424T020500Z
UID:OQOSZ5Q6pE77J_B6lc_D4xoY@stanza.co
SUMMARY:Braves @ Power
DESCRIPTION:Braves @ Power\n\nFollow on MiLB First Pitch: https://stza.co/+xJ4s-j\n\nShop: https://stza.co/+xJ4s-1q\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Braves @ Power
<2018-04-24 Tue 09:35-12:35>
:PROPERTIES:
:ID:       MbpOcwcXAGie3SpOMr2g8XQK@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Braves @ Power Braves @ Power

Follow on MiLB First Pitch  https //stza.co/+xJ4t-2b

Shop  https //stza.co/+xJ4t-1I

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Braves @ Power
END:VALARM
DTSTART:20180424T143500Z
DTEND:20180424T173500Z
UID:MbpOcwcXAGie3SpOMr2g8XQK@stanza.co
SUMMARY:Braves @ Power
DESCRIPTION:Braves @ Power\n\nFollow on MiLB First Pitch: https://stza.co/+xJ4t-2b\n\nShop: https://stza.co/+xJ4t-1I\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Braves @ Power
<2018-04-25 Wed 18:05-21:05>
:PROPERTIES:
:ID:       2tKE7I9kr9rT7FdmncwI0HBQ@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Braves @ Power Braves @ Power

Follow on MiLB First Pitch  https //stza.co/+xJ4u-L

Shop  https //stza.co/+xJ4u-a

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Braves @ Power
END:VALARM
DTSTART:20180425T230500Z
DTEND:20180426T020500Z
UID:2tKE7I9kr9rT7FdmncwI0HBQ@stanza.co
SUMMARY:Braves @ Power
DESCRIPTION:Braves @ Power\n\nFollow on MiLB First Pitch: https://stza.co/+xJ4u-L\n\nShop: https://stza.co/+xJ4u-a\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Braves @ Power
<2018-04-26 Thu 18:05-21:05>
:PROPERTIES:
:ID:       oPT0pqseSzVYtvbXU9Ko9gXx@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Braves @ Power Braves @ Power

Follow on MiLB First Pitch  https //stza.co/+xJ4v-1Y

Shop  https //stza.co/+xJ4v-3f

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Braves @ Power
END:VALARM
DTSTART:20180426T230500Z
DTEND:20180427T020500Z
UID:oPT0pqseSzVYtvbXU9Ko9gXx@stanza.co
SUMMARY:Braves @ Power
DESCRIPTION:Braves @ Power\n\nFollow on MiLB First Pitch: https://stza.co/+xJ4v-1Y\n\nShop: https://stza.co/+xJ4v-3f\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Braves @ Suns
<2018-04-27 Fri 17:05-20:05>
:PROPERTIES:
:ID:       q5n20n5ssS81HYZQZla_Q1WO@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Braves @ Suns Braves @ Suns

Follow on MiLB First Pitch  https //stza.co/+xF90-1D

Shop  https //stza.co/+xF90-2b

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Braves @ Suns
END:VALARM
DTSTART:20180427T220500Z
DTEND:20180428T010500Z
UID:q5n20n5ssS81HYZQZla_Q1WO@stanza.co
SUMMARY:Braves @ Suns
DESCRIPTION:Braves @ Suns\n\nFollow on MiLB First Pitch: https://stza.co/+xF90-1D\n\nShop: https://stza.co/+xF90-2b\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Braves @ Suns
<2018-04-28 Sat 17:05-20:05>
:PROPERTIES:
:ID:       AQIOJdtDH1cVjCQ9Weoaq6FF@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Braves @ Suns Braves @ Suns

Follow on MiLB First Pitch  https //stza.co/+xF91-1i

Shop  https //stza.co/+xF91-1Z

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Braves @ Suns
END:VALARM
DTSTART:20180428T220500Z
DTEND:20180429T010500Z
UID:AQIOJdtDH1cVjCQ9Weoaq6FF@stanza.co
SUMMARY:Braves @ Suns
DESCRIPTION:Braves @ Suns\n\nFollow on MiLB First Pitch: https://stza.co/+xF91-1i\n\nShop: https://stza.co/+xF91-1Z\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Braves @ Suns
<2018-04-29 Sun 13:05-16:05>
:PROPERTIES:
:ID:       FfVGpmy20rm6yueyTqSwZ-DJ@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Braves @ Suns Braves @ Suns

Follow on MiLB First Pitch  https //stza.co/+xF92-N

Shop  https //stza.co/+xF92-U

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Braves @ Suns
END:VALARM
DTSTART:20180429T180500Z
DTEND:20180429T210500Z
UID:FfVGpmy20rm6yueyTqSwZ-DJ@stanza.co
SUMMARY:Braves @ Suns
DESCRIPTION:Braves @ Suns\n\nFollow on MiLB First Pitch: https://stza.co/+xF92-N\n\nShop: https://stza.co/+xF92-U\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Braves vs. BlueClaws
<2018-05-01 Tue 18:00-21:00>
:PROPERTIES:
:ID:       2B3gcSWzag-wgyowdcswN-bB@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Braves vs. BlueClaws Braves vs. BlueClaws

Follow on MiLB First Pitch  https //stza.co/+vN_E-1P

Shop  https //stza.co/+vN_E-2K

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Braves vs. BlueClaws
END:VALARM
DTSTART:20180501T230000Z
DTEND:20180502T020000Z
UID:2B3gcSWzag-wgyowdcswN-bB@stanza.co
SUMMARY:Braves vs. BlueClaws
DESCRIPTION:Braves vs. BlueClaws\n\nFollow on MiLB First Pitch: https://stza.co/+vN_E-1P\n\nShop: https://stza.co/+vN_E-2K\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Braves vs. BlueClaws
<2018-05-02 Wed 18:00-21:00>
:PROPERTIES:
:ID:       EJBUlNjgcNrhDQawBqHPOFpC@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Braves vs. BlueClaws Braves vs. BlueClaws

Follow on MiLB First Pitch  https //stza.co/+vN_G-2U

Shop  https //stza.co/+vN_G-3s

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Braves vs. BlueClaws
END:VALARM
DTSTART:20180502T230000Z
DTEND:20180503T020000Z
UID:EJBUlNjgcNrhDQawBqHPOFpC@stanza.co
SUMMARY:Braves vs. BlueClaws
DESCRIPTION:Braves vs. BlueClaws\n\nFollow on MiLB First Pitch: https://stza.co/+vN_G-2U\n\nShop: https://stza.co/+vN_G-3s\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Braves vs. BlueClaws
<2018-05-03 Thu 09:30-12:30>
:PROPERTIES:
:ID:       ikfeoa0x0H493rd9lx99MWBk@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Braves vs. BlueClaws Braves vs. BlueClaws

Follow on MiLB First Pitch  https //stza.co/+vN_J-3S

Shop  https //stza.co/+vN_J-19

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Braves vs. BlueClaws
END:VALARM
DTSTART:20180503T143000Z
DTEND:20180503T173000Z
UID:ikfeoa0x0H493rd9lx99MWBk@stanza.co
SUMMARY:Braves vs. BlueClaws
DESCRIPTION:Braves vs. BlueClaws\n\nFollow on MiLB First Pitch: https://stza.co/+vN_J-3S\n\nShop: https://stza.co/+vN_J-19\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Braves vs. Tourists
<2018-05-04 Fri 18:00-21:00>
:PROPERTIES:
:ID:       RK3Yqpzdd-19cAf1ze2G6kxq@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Braves vs. Tourists Braves vs. Tourists

Follow on MiLB First Pitch  https //stza.co/+vN_K-9

Shop  https //stza.co/+vN_K-10

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Braves vs. Tourists
END:VALARM
DTSTART:20180504T230000Z
DTEND:20180505T020000Z
UID:RK3Yqpzdd-19cAf1ze2G6kxq@stanza.co
SUMMARY:Braves vs. Tourists
DESCRIPTION:Braves vs. Tourists\n\nFollow on MiLB First Pitch: https://stza.co/+vN_K-9\n\nShop: https://stza.co/+vN_K-10\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Braves vs. Tourists
<2018-05-05 Sat 17:00-20:00>
:PROPERTIES:
:ID:       aNlEInqLjDijka_ASDo2Arcm@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Braves vs. Tourists Braves vs. Tourists

Follow on MiLB First Pitch  https //stza.co/+vN_N-Q

Shop  https //stza.co/+vN_N-1R

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Braves vs. Tourists
END:VALARM
DTSTART:20180505T220000Z
DTEND:20180506T010000Z
UID:aNlEInqLjDijka_ASDo2Arcm@stanza.co
SUMMARY:Braves vs. Tourists
DESCRIPTION:Braves vs. Tourists\n\nFollow on MiLB First Pitch: https://stza.co/+vN_N-Q\n\nShop: https://stza.co/+vN_N-1R\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Braves vs. Tourists
<2018-05-06 Sun 13:00-16:00>
:PROPERTIES:
:ID:       XoootCGNvB4Sgfv8wUVSpX7k@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Braves vs. Tourists Braves vs. Tourists

Follow on MiLB First Pitch  https //stza.co/+vN_P-3O

Shop  https //stza.co/+vN_P-1o

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Braves vs. Tourists
END:VALARM
DTSTART:20180506T180000Z
DTEND:20180506T210000Z
UID:XoootCGNvB4Sgfv8wUVSpX7k@stanza.co
SUMMARY:Braves vs. Tourists
DESCRIPTION:Braves vs. Tourists\n\nFollow on MiLB First Pitch: https://stza.co/+vN_P-3O\n\nShop: https://stza.co/+vN_P-1o\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Braves vs. Tourists
<2018-05-07 Mon 09:30-12:30>
:PROPERTIES:
:ID:       k0K5K7B23gUjyv_bHTBxNQTF@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Braves vs. Tourists Braves vs. Tourists

Follow on MiLB First Pitch  https //stza.co/+vN_R-1T

Shop  https //stza.co/+vN_R-3

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Braves vs. Tourists
END:VALARM
DTSTART:20180507T143000Z
DTEND:20180507T173000Z
UID:k0K5K7B23gUjyv_bHTBxNQTF@stanza.co
SUMMARY:Braves vs. Tourists
DESCRIPTION:Braves vs. Tourists\n\nFollow on MiLB First Pitch: https://stza.co/+vN_R-1T\n\nShop: https://stza.co/+vN_R-3\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Braves @ GreenJackets
<2018-05-09 Wed 18:05-21:05>
:PROPERTIES:
:ID:       gy93XSzZyGIi1JQsND-7xNtp@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Braves @ GreenJackets Braves @ GreenJackets

Follow on MiLB First Pitch  https //stza.co/+xB_5-1s

Shop  https //stza.co/+xB_5-3z

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Braves @ GreenJackets
END:VALARM
DTSTART:20180509T230500Z
DTEND:20180510T020500Z
UID:gy93XSzZyGIi1JQsND-7xNtp@stanza.co
SUMMARY:Braves @ GreenJackets
DESCRIPTION:Braves @ GreenJackets\n\nFollow on MiLB First Pitch: https://stza.co/+xB_5-1s\n\nShop: https://stza.co/+xB_5-3z\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Braves @ GreenJackets
<2018-05-10 Thu 18:05-21:05>
:PROPERTIES:
:ID:       YWsE8cPTnfU5o7FyutbpK5h7@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Braves @ GreenJackets Braves @ GreenJackets

Follow on MiLB First Pitch  https //stza.co/+xB_9-z

Shop  https //stza.co/+xB_9-C

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Braves @ GreenJackets
END:VALARM
DTSTART:20180510T230500Z
DTEND:20180511T020500Z
UID:YWsE8cPTnfU5o7FyutbpK5h7@stanza.co
SUMMARY:Braves @ GreenJackets
DESCRIPTION:Braves @ GreenJackets\n\nFollow on MiLB First Pitch: https://stza.co/+xB_9-z\n\nShop: https://stza.co/+xB_9-C\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Braves @ GreenJackets
<2018-05-11 Fri 18:05-21:05>
:PROPERTIES:
:ID:       VcHDJsKNKargmyyCGrm1DFd7@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Braves @ GreenJackets Braves @ GreenJackets

Follow on MiLB First Pitch  https //stza.co/+xB_d-25

Shop  https //stza.co/+xB_d-39

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Braves @ GreenJackets
END:VALARM
DTSTART:20180511T230500Z
DTEND:20180512T020500Z
UID:VcHDJsKNKargmyyCGrm1DFd7@stanza.co
SUMMARY:Braves @ GreenJackets
DESCRIPTION:Braves @ GreenJackets\n\nFollow on MiLB First Pitch: https://stza.co/+xB_d-25\n\nShop: https://stza.co/+xB_d-39\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Braves @ Crawdads
<2018-05-12 Sat 17:00-20:00>
:PROPERTIES:
:ID:       EFy1L5JIr_tJnSeAEqW0Gy2N@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Braves @ Crawdads Braves @ Crawdads

Follow on MiLB First Pitch  https //stza.co/+w0R5-S

Shop  https //stza.co/+w0R5-2k

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Braves @ Crawdads
END:VALARM
DTSTART:20180512T220000Z
DTEND:20180513T010000Z
UID:EFy1L5JIr_tJnSeAEqW0Gy2N@stanza.co
SUMMARY:Braves @ Crawdads
DESCRIPTION:Braves @ Crawdads\n\nFollow on MiLB First Pitch: https://stza.co/+w0R5-S\n\nShop: https://stza.co/+w0R5-2k\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Braves @ Crawdads
<2018-05-13 Sun 14:00-17:00>
:PROPERTIES:
:ID:       SApogQH6O_slck634nj2HeQz@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Braves @ Crawdads Braves @ Crawdads

Follow on MiLB First Pitch  https //stza.co/+w0R6-2n

Shop  https //stza.co/+w0R6-x

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Braves @ Crawdads
END:VALARM
DTSTART:20180513T190000Z
DTEND:20180513T220000Z
UID:SApogQH6O_slck634nj2HeQz@stanza.co
SUMMARY:Braves @ Crawdads
DESCRIPTION:Braves @ Crawdads\n\nFollow on MiLB First Pitch: https://stza.co/+w0R6-2n\n\nShop: https://stza.co/+w0R6-x\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Braves @ Crawdads
<2018-05-14 Mon 17:00-20:00>
:PROPERTIES:
:ID:       RUT-PE7lI6QHWLDLSQ_q_D0A@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Braves @ Crawdads Braves @ Crawdads

Follow on MiLB First Pitch  https //stza.co/+w0R7-1y

Shop  https //stza.co/+w0R7-Q

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Braves @ Crawdads
END:VALARM
DTSTART:20180514T220000Z
DTEND:20180515T010000Z
UID:RUT-PE7lI6QHWLDLSQ_q_D0A@stanza.co
SUMMARY:Braves @ Crawdads
DESCRIPTION:Braves @ Crawdads\n\nFollow on MiLB First Pitch: https://stza.co/+w0R7-1y\n\nShop: https://stza.co/+w0R7-Q\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Braves @ Crawdads
<2018-05-15 Tue 09:30-12:30>
:PROPERTIES:
:ID:       6Y8UUot7Ziw8umYvCmPjJ8g4@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Braves @ Crawdads Braves @ Crawdads

Follow on MiLB First Pitch  https //stza.co/+w0R8-3c

Shop  https //stza.co/+w0R8-1l

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Braves @ Crawdads
END:VALARM
DTSTART:20180515T143000Z
DTEND:20180515T173000Z
UID:6Y8UUot7Ziw8umYvCmPjJ8g4@stanza.co
SUMMARY:Braves @ Crawdads
DESCRIPTION:Braves @ Crawdads\n\nFollow on MiLB First Pitch: https://stza.co/+w0R8-3c\n\nShop: https://stza.co/+w0R8-1l\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Braves vs. Tourists
<2018-05-17 Thu 18:00-21:00>
:PROPERTIES:
:ID:       TKF_mdarB74ptMG3JIxqu1dk@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Braves vs. Tourists Braves vs. Tourists

Follow on MiLB First Pitch  https //stza.co/+vN_T-2U

Shop  https //stza.co/+vN_T-3c

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Braves vs. Tourists
END:VALARM
DTSTART:20180517T230000Z
DTEND:20180518T020000Z
UID:TKF_mdarB74ptMG3JIxqu1dk@stanza.co
SUMMARY:Braves vs. Tourists
DESCRIPTION:Braves vs. Tourists\n\nFollow on MiLB First Pitch: https://stza.co/+vN_T-2U\n\nShop: https://stza.co/+vN_T-3c\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Braves vs. Tourists
<2018-05-18 Fri 18:00-21:00>
:PROPERTIES:
:ID:       Rd6D0EcO5BgheUZgrc8bA914@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Braves vs. Tourists Braves vs. Tourists

Follow on MiLB First Pitch  https //stza.co/+vN_V-2k

Shop  https //stza.co/+vN_V-2N

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Braves vs. Tourists
END:VALARM
DTSTART:20180518T230000Z
DTEND:20180519T020000Z
UID:Rd6D0EcO5BgheUZgrc8bA914@stanza.co
SUMMARY:Braves vs. Tourists
DESCRIPTION:Braves vs. Tourists\n\nFollow on MiLB First Pitch: https://stza.co/+vN_V-2k\n\nShop: https://stza.co/+vN_V-2N\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Braves vs. Tourists
<2018-05-19 Sat 17:00-20:00>
:PROPERTIES:
:ID:       8LnZaH38AQiI0Vf3PJ6KXP7g@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Braves vs. Tourists Braves vs. Tourists

Follow on MiLB First Pitch  https //stza.co/+vN_W-2L

Shop  https //stza.co/+vN_W-1$

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Braves vs. Tourists
END:VALARM
DTSTART:20180519T220000Z
DTEND:20180520T010000Z
UID:8LnZaH38AQiI0Vf3PJ6KXP7g@stanza.co
SUMMARY:Braves vs. Tourists
DESCRIPTION:Braves vs. Tourists\n\nFollow on MiLB First Pitch: https://stza.co/+vN_W-2L\n\nShop: https://stza.co/+vN_W-1$\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Braves vs. Tourists
<2018-05-20 Sun 13:00-16:00>
:PROPERTIES:
:ID:       5lbdfHS3Ge9qdOWlrDvwdckj@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Braves vs. Tourists Braves vs. Tourists

Follow on MiLB First Pitch  https //stza.co/+vN_Y-9

Shop  https //stza.co/+vN_Y-e

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Braves vs. Tourists
END:VALARM
DTSTART:20180520T180000Z
DTEND:20180520T210000Z
UID:5lbdfHS3Ge9qdOWlrDvwdckj@stanza.co
SUMMARY:Braves vs. Tourists
DESCRIPTION:Braves vs. Tourists\n\nFollow on MiLB First Pitch: https://stza.co/+vN_Y-9\n\nShop: https://stza.co/+vN_Y-e\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Braves @ Legends
<2018-05-21 Mon 18:05-21:05>
:PROPERTIES:
:ID:       _7_s5Qvp4XAgLOZr3muaNS3M@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Braves @ Legends Braves @ Legends

Follow on MiLB First Pitch  https //stza.co/+xB$6-m

Shop  https //stza.co/+xB$6-10

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Braves @ Legends
END:VALARM
DTSTART:20180521T230500Z
DTEND:20180522T020500Z
UID:_7_s5Qvp4XAgLOZr3muaNS3M@stanza.co
SUMMARY:Braves @ Legends
DESCRIPTION:Braves @ Legends\n\nFollow on MiLB First Pitch: https://stza.co/+xB$6-m\n\nShop: https://stza.co/+xB$6-10\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Braves @ Legends
<2018-05-22 Tue 18:05-21:05>
:PROPERTIES:
:ID:       T9wYW-rPmPUz6snTvdph0ka0@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Braves @ Legends Braves @ Legends

Follow on MiLB First Pitch  https //stza.co/+xB$8-3K

Shop  https //stza.co/+xB$8-3j

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Braves @ Legends
END:VALARM
DTSTART:20180522T230500Z
DTEND:20180523T020500Z
UID:T9wYW-rPmPUz6snTvdph0ka0@stanza.co
SUMMARY:Braves @ Legends
DESCRIPTION:Braves @ Legends\n\nFollow on MiLB First Pitch: https://stza.co/+xB$8-3K\n\nShop: https://stza.co/+xB$8-3j\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Braves @ Legends
<2018-05-23 Wed 12:05-15:05>
:PROPERTIES:
:ID:       m0DgYTI5ArcRoubeMV4ismuj@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Braves @ Legends Braves @ Legends

Follow on MiLB First Pitch  https //stza.co/+xB$c-$

Shop  https //stza.co/+xB$c-m

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Braves @ Legends
END:VALARM
DTSTART:20180523T170500Z
DTEND:20180523T200500Z
UID:m0DgYTI5ArcRoubeMV4ismuj@stanza.co
SUMMARY:Braves @ Legends
DESCRIPTION:Braves @ Legends\n\nFollow on MiLB First Pitch: https://stza.co/+xB$c-$\n\nShop: https://stza.co/+xB$c-m\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Braves @ Legends
<2018-05-24 Thu 18:05-21:05>
:PROPERTIES:
:ID:       2xYsQtQOjUnXaOcV1kCRK-tu@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Braves @ Legends Braves @ Legends

Follow on MiLB First Pitch  https //stza.co/+xB$g-2z

Shop  https //stza.co/+xB$g-2N

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Braves @ Legends
END:VALARM
DTSTART:20180524T230500Z
DTEND:20180525T020500Z
UID:2xYsQtQOjUnXaOcV1kCRK-tu@stanza.co
SUMMARY:Braves @ Legends
DESCRIPTION:Braves @ Legends\n\nFollow on MiLB First Pitch: https://stza.co/+xB$g-2z\n\nShop: https://stza.co/+xB$g-2N\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Braves @ GreenJackets
<2018-05-25 Fri 18:05-21:05>
:PROPERTIES:
:ID:       vYnLo7Q7IhYvlBxNUQKW6WZO@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Braves @ GreenJackets Braves @ GreenJackets

Follow on MiLB First Pitch  https //stza.co/+xB_g-3l

Shop  https //stza.co/+xB_g-3e

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Braves @ GreenJackets
END:VALARM
DTSTART:20180525T230500Z
DTEND:20180526T020500Z
UID:vYnLo7Q7IhYvlBxNUQKW6WZO@stanza.co
SUMMARY:Braves @ GreenJackets
DESCRIPTION:Braves @ GreenJackets\n\nFollow on MiLB First Pitch: https://stza.co/+xB_g-3l\n\nShop: https://stza.co/+xB_g-3e\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Braves @ GreenJackets
<2018-05-26 Sat 17:05-20:05>
:PROPERTIES:
:ID:       mf488v4dSEYo83UXAB-FEM53@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Braves @ GreenJackets Braves @ GreenJackets

Follow on MiLB First Pitch  https //stza.co/+xB_k-3C

Shop  https //stza.co/+xB_k-24

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Braves @ GreenJackets
END:VALARM
DTSTART:20180526T220500Z
DTEND:20180527T010500Z
UID:mf488v4dSEYo83UXAB-FEM53@stanza.co
SUMMARY:Braves @ GreenJackets
DESCRIPTION:Braves @ GreenJackets\n\nFollow on MiLB First Pitch: https://stza.co/+xB_k-3C\n\nShop: https://stza.co/+xB_k-24\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Braves @ GreenJackets
<2018-05-27 Sun 17:35-20:35>
:PROPERTIES:
:ID:       s6OsrZVgaqDeBX3ofSYoHemL@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Braves @ GreenJackets Braves @ GreenJackets

Follow on MiLB First Pitch  https //stza.co/+xB_o-3x

Shop  https //stza.co/+xB_o-2U

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Braves @ GreenJackets
END:VALARM
DTSTART:20180527T223500Z
DTEND:20180528T013500Z
UID:s6OsrZVgaqDeBX3ofSYoHemL@stanza.co
SUMMARY:Braves @ GreenJackets
DESCRIPTION:Braves @ GreenJackets\n\nFollow on MiLB First Pitch: https://stza.co/+xB_o-3x\n\nShop: https://stza.co/+xB_o-2U\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Braves @ GreenJackets
<2018-05-28 Mon 13:05-16:05>
:PROPERTIES:
:ID:       xtULhtyZnDOA7D2IjTH4cDEt@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Braves @ GreenJackets Braves @ GreenJackets

Follow on MiLB First Pitch  https //stza.co/+xB_q-e

Shop  https //stza.co/+xB_q-1v

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Braves @ GreenJackets
END:VALARM
DTSTART:20180528T180500Z
DTEND:20180528T210500Z
UID:xtULhtyZnDOA7D2IjTH4cDEt@stanza.co
SUMMARY:Braves @ GreenJackets
DESCRIPTION:Braves @ GreenJackets\n\nFollow on MiLB First Pitch: https://stza.co/+xB_q-e\n\nShop: https://stza.co/+xB_q-1v\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Braves vs. Tourists
<2018-05-29 Tue 18:00-21:00>
:PROPERTIES:
:ID:       dIWnwbw4_hfP6PTo8FuKaMjM@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Braves vs. Tourists Braves vs. Tourists

Follow on MiLB First Pitch  https //stza.co/+vN_$-3B

Shop  https //stza.co/+vN_$-2V

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Braves vs. Tourists
END:VALARM
DTSTART:20180529T230000Z
DTEND:20180530T020000Z
UID:dIWnwbw4_hfP6PTo8FuKaMjM@stanza.co
SUMMARY:Braves vs. Tourists
DESCRIPTION:Braves vs. Tourists\n\nFollow on MiLB First Pitch: https://stza.co/+vN_$-3B\n\nShop: https://stza.co/+vN_$-2V\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Braves vs. Tourists
<2018-05-30 Wed 12:00-15:00>
:PROPERTIES:
:ID:       xAQwsGKzhBIKP9_aGkIa51P7@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Braves vs. Tourists Braves vs. Tourists

Follow on MiLB First Pitch  https //stza.co/+vN$1-2o

Shop  https //stza.co/+vN$1-R

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Braves vs. Tourists
END:VALARM
DTSTART:20180530T170000Z
DTEND:20180530T200000Z
UID:xAQwsGKzhBIKP9_aGkIa51P7@stanza.co
SUMMARY:Braves vs. Tourists
DESCRIPTION:Braves vs. Tourists\n\nFollow on MiLB First Pitch: https://stza.co/+vN$1-2o\n\nShop: https://stza.co/+vN$1-R\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Braves vs. Tourists
<2018-05-31 Thu 18:00-21:00>
:PROPERTIES:
:ID:       rbgaRc2KwdMwQr7TnMsf-1Gn@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Braves vs. Tourists Braves vs. Tourists

Follow on MiLB First Pitch  https //stza.co/+vN$3-3E

Shop  https //stza.co/+vN$3-3N

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Braves vs. Tourists
END:VALARM
DTSTART:20180531T230000Z
DTEND:20180601T020000Z
UID:rbgaRc2KwdMwQr7TnMsf-1Gn@stanza.co
SUMMARY:Braves vs. Tourists
DESCRIPTION:Braves vs. Tourists\n\nFollow on MiLB First Pitch: https://stza.co/+vN$3-3E\n\nShop: https://stza.co/+vN$3-3N\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Braves vs. Fireflies
<2018-06-01 Fri 18:00-21:00>
:PROPERTIES:
:ID:       Id9BbdJKiEh94D_B5nrIX846@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Braves vs. Fireflies Braves vs. Fireflies

Follow on MiLB First Pitch  https //stza.co/+vN$4-1i

Shop  https //stza.co/+vN$4-3K

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Braves vs. Fireflies
END:VALARM
DTSTART:20180601T230000Z
DTEND:20180602T020000Z
UID:Id9BbdJKiEh94D_B5nrIX846@stanza.co
SUMMARY:Braves vs. Fireflies
DESCRIPTION:Braves vs. Fireflies\n\nFollow on MiLB First Pitch: https://stza.co/+vN$4-1i\n\nShop: https://stza.co/+vN$4-3K\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Braves vs. Fireflies
<2018-06-02 Sat 17:00-20:00>
:PROPERTIES:
:ID:       KCRacFupdK-prrNm6zdZQ0m1@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Braves vs. Fireflies Braves vs. Fireflies

Follow on MiLB First Pitch  https //stza.co/+vN$7-27

Shop  https //stza.co/+vN$7-2U

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Braves vs. Fireflies
END:VALARM
DTSTART:20180602T220000Z
DTEND:20180603T010000Z
UID:KCRacFupdK-prrNm6zdZQ0m1@stanza.co
SUMMARY:Braves vs. Fireflies
DESCRIPTION:Braves vs. Fireflies\n\nFollow on MiLB First Pitch: https://stza.co/+vN$7-27\n\nShop: https://stza.co/+vN$7-2U\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Braves vs. Fireflies
<2018-06-03 Sun 13:00-16:00>
:PROPERTIES:
:ID:       p6ep-ySSiGfq5dZR71-H20ET@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Braves vs. Fireflies Braves vs. Fireflies

Follow on MiLB First Pitch  https //stza.co/+vN$8-3N

Shop  https //stza.co/+vN$8-1T

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Braves vs. Fireflies
END:VALARM
DTSTART:20180603T180000Z
DTEND:20180603T210000Z
UID:p6ep-ySSiGfq5dZR71-H20ET@stanza.co
SUMMARY:Braves vs. Fireflies
DESCRIPTION:Braves vs. Fireflies\n\nFollow on MiLB First Pitch: https://stza.co/+vN$8-3N\n\nShop: https://stza.co/+vN$8-1T\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Braves @ Tourists
<2018-06-05 Tue 18:05-21:05>
:PROPERTIES:
:ID:       GXLCBz5zpllN6IDtel3TL_eI@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Braves @ Tourists Braves @ Tourists

Follow on MiLB First Pitch  https //stza.co/+vNZj-4

Shop  https //stza.co/+vNZj-3a

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Braves @ Tourists
END:VALARM
DTSTART:20180605T230500Z
DTEND:20180606T020500Z
UID:GXLCBz5zpllN6IDtel3TL_eI@stanza.co
SUMMARY:Braves @ Tourists
DESCRIPTION:Braves @ Tourists\n\nFollow on MiLB First Pitch: https://stza.co/+vNZj-4\n\nShop: https://stza.co/+vNZj-3a\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Braves @ Tourists
<2018-06-06 Wed 18:05-21:05>
:PROPERTIES:
:ID:       k9K-52Acns3MKRhTpoJfi546@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Braves @ Tourists Braves @ Tourists

Follow on MiLB First Pitch  https //stza.co/+vNZk-2$

Shop  https //stza.co/+vNZk-3b

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Braves @ Tourists
END:VALARM
DTSTART:20180606T230500Z
DTEND:20180607T020500Z
UID:k9K-52Acns3MKRhTpoJfi546@stanza.co
SUMMARY:Braves @ Tourists
DESCRIPTION:Braves @ Tourists\n\nFollow on MiLB First Pitch: https://stza.co/+vNZk-2$\n\nShop: https://stza.co/+vNZk-3b\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Braves @ Tourists
<2018-06-07 Thu 18:05-21:05>
:PROPERTIES:
:ID:       A85808dg0CYVExuu8OcKzYN9@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Braves @ Tourists Braves @ Tourists

Follow on MiLB First Pitch  https //stza.co/+vNZl-2C

Shop  https //stza.co/+vNZl-1S

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Braves @ Tourists
END:VALARM
DTSTART:20180607T230500Z
DTEND:20180608T020500Z
UID:A85808dg0CYVExuu8OcKzYN9@stanza.co
SUMMARY:Braves @ Tourists
DESCRIPTION:Braves @ Tourists\n\nFollow on MiLB First Pitch: https://stza.co/+vNZl-2C\n\nShop: https://stza.co/+vNZl-1S\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Braves vs. Intimidators
<2018-06-08 Fri 18:00-21:00>
:PROPERTIES:
:ID:       ZIGrVuEexfWPqIyT4QqevWxD@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Braves vs. Intimidators Braves vs. Intimidators

Follow on MiLB First Pitch  https //stza.co/+vN$a-2w

Shop  https //stza.co/+vN$a-2M

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Braves vs. Intimidators
END:VALARM
DTSTART:20180608T230000Z
DTEND:20180609T020000Z
UID:ZIGrVuEexfWPqIyT4QqevWxD@stanza.co
SUMMARY:Braves vs. Intimidators
DESCRIPTION:Braves vs. Intimidators\n\nFollow on MiLB First Pitch: https://stza.co/+vN$a-2w\n\nShop: https://stza.co/+vN$a-2M\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Braves vs. Intimidators
<2018-06-09 Sat 17:00-20:00>
:PROPERTIES:
:ID:       u_T-NKKo4FL89CveGYyYv_OM@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Braves vs. Intimidators Braves vs. Intimidators

Follow on MiLB First Pitch  https //stza.co/+vN$c-22

Shop  https //stza.co/+vN$c-

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Braves vs. Intimidators
END:VALARM
DTSTART:20180609T220000Z
DTEND:20180610T010000Z
UID:u_T-NKKo4FL89CveGYyYv_OM@stanza.co
SUMMARY:Braves vs. Intimidators
DESCRIPTION:Braves vs. Intimidators\n\nFollow on MiLB First Pitch: https://stza.co/+vN$c-22\n\nShop: https://stza.co/+vN$c-\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Braves vs. Intimidators
<2018-06-10 Sun 13:00-16:00>
:PROPERTIES:
:ID:       sypGvmkhRa2HehG5ec1ew4qX@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Braves vs. Intimidators Braves vs. Intimidators

Follow on MiLB First Pitch  https //stza.co/+vN$f-_

Shop  https //stza.co/+vN$f-3T

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Braves vs. Intimidators
END:VALARM
DTSTART:20180610T180000Z
DTEND:20180610T210000Z
UID:sypGvmkhRa2HehG5ec1ew4qX@stanza.co
SUMMARY:Braves vs. Intimidators
DESCRIPTION:Braves vs. Intimidators\n\nFollow on MiLB First Pitch: https://stza.co/+vN$f-_\n\nShop: https://stza.co/+vN$f-3T\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Braves @ Drive
<2018-06-11 Mon 18:05-21:05>
:PROPERTIES:
:ID:       gZRI7wdOyzE1MlaFQ4E9cmyZ@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Braves @ Drive Braves @ Drive

Follow on MiLB First Pitch  https //stza.co/+xF8R-1I

Shop  https //stza.co/+xF8R-1v

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Braves @ Drive
END:VALARM
DTSTART:20180611T230500Z
DTEND:20180612T020500Z
UID:gZRI7wdOyzE1MlaFQ4E9cmyZ@stanza.co
SUMMARY:Braves @ Drive
DESCRIPTION:Braves @ Drive\n\nFollow on MiLB First Pitch: https://stza.co/+xF8R-1I\n\nShop: https://stza.co/+xF8R-1v\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Braves @ Drive
<2018-06-12 Tue 18:05-21:05>
:PROPERTIES:
:ID:       jtk5562_t70ZfZMVOKbMvqTa@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Braves @ Drive Braves @ Drive

Follow on MiLB First Pitch  https //stza.co/+xF8S-10

Shop  https //stza.co/+xF8S-R

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Braves @ Drive
END:VALARM
DTSTART:20180612T230500Z
DTEND:20180613T020500Z
UID:jtk5562_t70ZfZMVOKbMvqTa@stanza.co
SUMMARY:Braves @ Drive
DESCRIPTION:Braves @ Drive\n\nFollow on MiLB First Pitch: https://stza.co/+xF8S-10\n\nShop: https://stza.co/+xF8S-R\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Braves @ Drive
<2018-06-13 Wed 18:05-21:05>
:PROPERTIES:
:ID:       KWUCSw3o2HSCFxW27onUmskk@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Braves @ Drive Braves @ Drive

Follow on MiLB First Pitch  https //stza.co/+xF8T-2B

Shop  https //stza.co/+xF8T-2N

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Braves @ Drive
END:VALARM
DTSTART:20180613T230500Z
DTEND:20180614T020500Z
UID:KWUCSw3o2HSCFxW27onUmskk@stanza.co
SUMMARY:Braves @ Drive
DESCRIPTION:Braves @ Drive\n\nFollow on MiLB First Pitch: https://stza.co/+xF8T-2B\n\nShop: https://stza.co/+xF8T-2N\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Braves @ Drive
<2018-06-14 Thu 18:05-21:05>
:PROPERTIES:
:ID:       jLp_LZgMh70G_G6LzecpsB6y@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Braves @ Drive Braves @ Drive

Follow on MiLB First Pitch  https //stza.co/+xF8U-S

Shop  https //stza.co/+xF8U-3Q

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Braves @ Drive
END:VALARM
DTSTART:20180614T230500Z
DTEND:20180615T020500Z
UID:jLp_LZgMh70G_G6LzecpsB6y@stanza.co
SUMMARY:Braves @ Drive
DESCRIPTION:Braves @ Drive\n\nFollow on MiLB First Pitch: https://stza.co/+xF8U-S\n\nShop: https://stza.co/+xF8U-3Q\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Braves vs. Legends
<2018-06-15 Fri 18:00-21:00>
:PROPERTIES:
:ID:       RLmAjhTgdNBvY0nugbimxcXW@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Braves vs. Legends Braves vs. Legends

Follow on MiLB First Pitch  https //stza.co/+vN$g-3l

Shop  https //stza.co/+vN$g-1R

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Braves vs. Legends
END:VALARM
DTSTART:20180615T230000Z
DTEND:20180616T020000Z
UID:RLmAjhTgdNBvY0nugbimxcXW@stanza.co
SUMMARY:Braves vs. Legends
DESCRIPTION:Braves vs. Legends\n\nFollow on MiLB First Pitch: https://stza.co/+vN$g-3l\n\nShop: https://stza.co/+vN$g-1R\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Braves vs. Legends
<2018-06-16 Sat 17:00-20:00>
:PROPERTIES:
:ID:       A_0h0lhPuW6eFGzToSodU3BT@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Braves vs. Legends Braves vs. Legends

Follow on MiLB First Pitch  https //stza.co/+vN$i-2o

Shop  https //stza.co/+vN$i-1_

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Braves vs. Legends
END:VALARM
DTSTART:20180616T220000Z
DTEND:20180617T010000Z
UID:A_0h0lhPuW6eFGzToSodU3BT@stanza.co
SUMMARY:Braves vs. Legends
DESCRIPTION:Braves vs. Legends\n\nFollow on MiLB First Pitch: https://stza.co/+vN$i-2o\n\nShop: https://stza.co/+vN$i-1_\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Braves vs. Legends
<2018-06-17 Sun 13:00-16:00>
:PROPERTIES:
:ID:       P5VyD_bOotmVUkkPf1Oo2aBQ@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Braves vs. Legends Braves vs. Legends

Follow on MiLB First Pitch  https //stza.co/+vN$k-1e

Shop  https //stza.co/+vN$k-U

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Braves vs. Legends
END:VALARM
DTSTART:20180617T180000Z
DTEND:20180617T210000Z
UID:P5VyD_bOotmVUkkPf1Oo2aBQ@stanza.co
SUMMARY:Braves vs. Legends
DESCRIPTION:Braves vs. Legends\n\nFollow on MiLB First Pitch: https://stza.co/+vN$k-1e\n\nShop: https://stza.co/+vN$k-U\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Braves @ GreenJackets
<2018-06-21 Thu 18:05-21:05>
:PROPERTIES:
:ID:       42S77Em_o5HiATxczbxjrTxi@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Braves @ GreenJackets Braves @ GreenJackets

Follow on MiLB First Pitch  https //stza.co/+xB_s-3F

Shop  https //stza.co/+xB_s-G

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Braves @ GreenJackets
END:VALARM
DTSTART:20180621T230500Z
DTEND:20180622T020500Z
UID:42S77Em_o5HiATxczbxjrTxi@stanza.co
SUMMARY:Braves @ GreenJackets
DESCRIPTION:Braves @ GreenJackets\n\nFollow on MiLB First Pitch: https://stza.co/+xB_s-3F\n\nShop: https://stza.co/+xB_s-G\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Braves @ GreenJackets
<2018-06-22 Fri 18:05-21:05>
:PROPERTIES:
:ID:       TfszPwHAbNLcTLtdDkep01uB@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Braves @ GreenJackets Braves @ GreenJackets

Follow on MiLB First Pitch  https //stza.co/+xB_w-h

Shop  https //stza.co/+xB_w-1L

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Braves @ GreenJackets
END:VALARM
DTSTART:20180622T230500Z
DTEND:20180623T020500Z
UID:TfszPwHAbNLcTLtdDkep01uB@stanza.co
SUMMARY:Braves @ GreenJackets
DESCRIPTION:Braves @ GreenJackets\n\nFollow on MiLB First Pitch: https://stza.co/+xB_w-h\n\nShop: https://stza.co/+xB_w-1L\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Braves @ GreenJackets
<2018-06-23 Sat 17:05-20:05>
:PROPERTIES:
:ID:       cxN2mVzRbTgl9ERLB4vozBsS@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Braves @ GreenJackets Braves @ GreenJackets

Follow on MiLB First Pitch  https //stza.co/+xB_B-2j

Shop  https //stza.co/+xB_B-38

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Braves @ GreenJackets
END:VALARM
DTSTART:20180623T220500Z
DTEND:20180624T010500Z
UID:cxN2mVzRbTgl9ERLB4vozBsS@stanza.co
SUMMARY:Braves @ GreenJackets
DESCRIPTION:Braves @ GreenJackets\n\nFollow on MiLB First Pitch: https://stza.co/+xB_B-2j\n\nShop: https://stza.co/+xB_B-38\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Braves vs. Drive
<2018-06-24 Sun 13:00-16:00>
:PROPERTIES:
:ID:       NGmBkFwzv7Zd1B1pOt3i-yHu@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Braves vs. Drive Braves vs. Drive

Follow on MiLB First Pitch  https //stza.co/+vN$n-3N

Shop  https //stza.co/+vN$n-X

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Braves vs. Drive
END:VALARM
DTSTART:20180624T180000Z
DTEND:20180624T210000Z
UID:NGmBkFwzv7Zd1B1pOt3i-yHu@stanza.co
SUMMARY:Braves vs. Drive
DESCRIPTION:Braves vs. Drive\n\nFollow on MiLB First Pitch: https://stza.co/+vN$n-3N\n\nShop: https://stza.co/+vN$n-X\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Braves vs. Drive
<2018-06-25 Mon 18:00-21:00>
:PROPERTIES:
:ID:       I4IdOggSp589aRj69qd8r4Vt@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Braves vs. Drive Braves vs. Drive

Follow on MiLB First Pitch  https //stza.co/+vN$o-1E

Shop  https //stza.co/+vN$o-2b

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Braves vs. Drive
END:VALARM
DTSTART:20180625T230000Z
DTEND:20180626T020000Z
UID:I4IdOggSp589aRj69qd8r4Vt@stanza.co
SUMMARY:Braves vs. Drive
DESCRIPTION:Braves vs. Drive\n\nFollow on MiLB First Pitch: https://stza.co/+vN$o-1E\n\nShop: https://stza.co/+vN$o-2b\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Braves vs. Drive
<2018-06-26 Tue 12:00-15:00>
:PROPERTIES:
:ID:       3ROINW97_ZZNtXcwogcADc4o@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Braves vs. Drive Braves vs. Drive

Follow on MiLB First Pitch  https //stza.co/+vN$q-n

Shop  https //stza.co/+vN$q-r

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Braves vs. Drive
END:VALARM
DTSTART:20180626T170000Z
DTEND:20180626T200000Z
UID:3ROINW97_ZZNtXcwogcADc4o@stanza.co
SUMMARY:Braves vs. Drive
DESCRIPTION:Braves vs. Drive\n\nFollow on MiLB First Pitch: https://stza.co/+vN$q-n\n\nShop: https://stza.co/+vN$q-r\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Braves @ RiverDogs
<2018-06-27 Wed 18:05-21:05>
:PROPERTIES:
:ID:       vvQFAL5Ba9QY2RmA9380Tmuc@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Braves @ RiverDogs Braves @ RiverDogs

Follow on MiLB First Pitch  https //stza.co/+vNZH-r

Shop  https //stza.co/+vNZH-3Z

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Braves @ RiverDogs
END:VALARM
DTSTART:20180627T230500Z
DTEND:20180628T020500Z
UID:vvQFAL5Ba9QY2RmA9380Tmuc@stanza.co
SUMMARY:Braves @ RiverDogs
DESCRIPTION:Braves @ RiverDogs\n\nFollow on MiLB First Pitch: https://stza.co/+vNZH-r\n\nShop: https://stza.co/+vNZH-3Z\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Braves @ RiverDogs
<2018-06-28 Thu 18:05-21:05>
:PROPERTIES:
:ID:       GEfxnq3AS4vBtKMnMFThyQaf@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Braves @ RiverDogs Braves @ RiverDogs

Follow on MiLB First Pitch  https //stza.co/+vNZI-F

Shop  https //stza.co/+vNZI-3g

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Braves @ RiverDogs
END:VALARM
DTSTART:20180628T230500Z
DTEND:20180629T020500Z
UID:GEfxnq3AS4vBtKMnMFThyQaf@stanza.co
SUMMARY:Braves @ RiverDogs
DESCRIPTION:Braves @ RiverDogs\n\nFollow on MiLB First Pitch: https://stza.co/+vNZI-F\n\nShop: https://stza.co/+vNZI-3g\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Braves @ RiverDogs
<2018-06-29 Fri 18:05-21:05>
:PROPERTIES:
:ID:       t8NR7WDhnY_D_NSYwbns88Yi@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Braves @ RiverDogs Braves @ RiverDogs

Follow on MiLB First Pitch  https //stza.co/+vNZJ-13

Shop  https //stza.co/+vNZJ-1D

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Braves @ RiverDogs
END:VALARM
DTSTART:20180629T230500Z
DTEND:20180630T020500Z
UID:t8NR7WDhnY_D_NSYwbns88Yi@stanza.co
SUMMARY:Braves @ RiverDogs
DESCRIPTION:Braves @ RiverDogs\n\nFollow on MiLB First Pitch: https://stza.co/+vNZJ-13\n\nShop: https://stza.co/+vNZJ-1D\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Braves vs. Intimidators
<2018-06-30 Sat 17:00-20:00>
:PROPERTIES:
:ID:       UWh6lQ566hxCFqd_eF1PP2Jg@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Braves vs. Intimidators Braves vs. Intimidators

Follow on MiLB First Pitch  https //stza.co/+vN$s-33

Shop  https //stza.co/+vN$s-1a

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Braves vs. Intimidators
END:VALARM
DTSTART:20180630T220000Z
DTEND:20180701T010000Z
UID:UWh6lQ566hxCFqd_eF1PP2Jg@stanza.co
SUMMARY:Braves vs. Intimidators
DESCRIPTION:Braves vs. Intimidators\n\nFollow on MiLB First Pitch: https://stza.co/+vN$s-33\n\nShop: https://stza.co/+vN$s-1a\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Braves vs. Intimidators
<2018-07-01 Sun 13:00-16:00>
:PROPERTIES:
:ID:       HKbDsvTHGA9k45SAOvs3Trfp@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Braves vs. Intimidators Braves vs. Intimidators

Follow on MiLB First Pitch  https //stza.co/+vN$v-3c

Shop  https //stza.co/+vN$v-3L

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Braves vs. Intimidators
END:VALARM
DTSTART:20180701T180000Z
DTEND:20180701T210000Z
UID:HKbDsvTHGA9k45SAOvs3Trfp@stanza.co
SUMMARY:Braves vs. Intimidators
DESCRIPTION:Braves vs. Intimidators\n\nFollow on MiLB First Pitch: https://stza.co/+vN$v-3c\n\nShop: https://stza.co/+vN$v-3L\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Braves vs. Intimidators
<2018-07-02 Mon 18:00-21:00>
:PROPERTIES:
:ID:       L4nBvl5uarF0Idv6qmLv9QOg@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Braves vs. Intimidators Braves vs. Intimidators

Follow on MiLB First Pitch  https //stza.co/+vN$w-2p

Shop  https //stza.co/+vN$w-d

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Braves vs. Intimidators
END:VALARM
DTSTART:20180702T230000Z
DTEND:20180703T020000Z
UID:L4nBvl5uarF0Idv6qmLv9QOg@stanza.co
SUMMARY:Braves vs. Intimidators
DESCRIPTION:Braves vs. Intimidators\n\nFollow on MiLB First Pitch: https://stza.co/+vN$w-2p\n\nShop: https://stza.co/+vN$w-d\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Braves vs. Intimidators
<2018-07-03 Tue 18:00-21:00>
:PROPERTIES:
:ID:       9TmR62EEeu4gjUTD0bQiHhqG@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Braves vs. Intimidators Braves vs. Intimidators

Follow on MiLB First Pitch  https //stza.co/+vN$z-a

Shop  https //stza.co/+vN$z-2d

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Braves vs. Intimidators
END:VALARM
DTSTART:20180703T230000Z
DTEND:20180704T020000Z
UID:9TmR62EEeu4gjUTD0bQiHhqG@stanza.co
SUMMARY:Braves vs. Intimidators
DESCRIPTION:Braves vs. Intimidators\n\nFollow on MiLB First Pitch: https://stza.co/+vN$z-a\n\nShop: https://stza.co/+vN$z-2d\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Braves @ Tourists
<2018-07-04 Wed 18:05-21:05>
:PROPERTIES:
:ID:       Z7m43lLsERyve3OBx-x9uaIS@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Braves @ Tourists Braves @ Tourists

Follow on MiLB First Pitch  https //stza.co/+vNZm-1R

Shop  https //stza.co/+vNZm-t

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Braves @ Tourists
END:VALARM
DTSTART:20180704T230500Z
DTEND:20180705T020500Z
UID:Z7m43lLsERyve3OBx-x9uaIS@stanza.co
SUMMARY:Braves @ Tourists
DESCRIPTION:Braves @ Tourists\n\nFollow on MiLB First Pitch: https://stza.co/+vNZm-1R\n\nShop: https://stza.co/+vNZm-t\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Braves @ Tourists
<2018-07-05 Thu 18:05-21:05>
:PROPERTIES:
:ID:       xBFwnFMiMLuD5JL3-U2NN5p3@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Braves @ Tourists Braves @ Tourists

Follow on MiLB First Pitch  https //stza.co/+vNZn-2K

Shop  https //stza.co/+vNZn-2Y

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Braves @ Tourists
END:VALARM
DTSTART:20180705T230500Z
DTEND:20180706T020500Z
UID:xBFwnFMiMLuD5JL3-U2NN5p3@stanza.co
SUMMARY:Braves @ Tourists
DESCRIPTION:Braves @ Tourists\n\nFollow on MiLB First Pitch: https://stza.co/+vNZn-2K\n\nShop: https://stza.co/+vNZn-2Y\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Braves @ Tourists
<2018-07-06 Fri 18:05-21:05>
:PROPERTIES:
:ID:       W67IOmGfLLVDanYFQe25XaD7@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Braves @ Tourists Braves @ Tourists

Follow on MiLB First Pitch  https //stza.co/+vNZo-K

Shop  https //stza.co/+vNZo-12

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Braves @ Tourists
END:VALARM
DTSTART:20180706T230500Z
DTEND:20180707T020500Z
UID:W67IOmGfLLVDanYFQe25XaD7@stanza.co
SUMMARY:Braves @ Tourists
DESCRIPTION:Braves @ Tourists\n\nFollow on MiLB First Pitch: https://stza.co/+vNZo-K\n\nShop: https://stza.co/+vNZo-12\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Braves vs. GreenJackets
<2018-07-07 Sat 17:00-20:00>
:PROPERTIES:
:ID:       d5if87-2QUcbvdQTQPczaTNr@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Braves vs. GreenJackets Braves vs. GreenJackets

Follow on MiLB First Pitch  https //stza.co/+vN$B-3q

Shop  https //stza.co/+vN$B-2w

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Braves vs. GreenJackets
END:VALARM
DTSTART:20180707T220000Z
DTEND:20180708T010000Z
UID:d5if87-2QUcbvdQTQPczaTNr@stanza.co
SUMMARY:Braves vs. GreenJackets
DESCRIPTION:Braves vs. GreenJackets\n\nFollow on MiLB First Pitch: https://stza.co/+vN$B-3q\n\nShop: https://stza.co/+vN$B-2w\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Braves vs. GreenJackets
<2018-07-08 Sun 13:00-16:00>
:PROPERTIES:
:ID:       8hOIl-FiOLiZdPtCP2i0tTKP@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Braves vs. GreenJackets Braves vs. GreenJackets

Follow on MiLB First Pitch  https //stza.co/+vN$D-2R

Shop  https //stza.co/+vN$D-2y

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Braves vs. GreenJackets
END:VALARM
DTSTART:20180708T180000Z
DTEND:20180708T210000Z
UID:8hOIl-FiOLiZdPtCP2i0tTKP@stanza.co
SUMMARY:Braves vs. GreenJackets
DESCRIPTION:Braves vs. GreenJackets\n\nFollow on MiLB First Pitch: https://stza.co/+vN$D-2R\n\nShop: https://stza.co/+vN$D-2y\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Braves vs. GreenJackets
<2018-07-09 Mon 18:00-21:00>
:PROPERTIES:
:ID:       AGKkiHAV52JGKJGK6qkTzlB9@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Braves vs. GreenJackets Braves vs. GreenJackets

Follow on MiLB First Pitch  https //stza.co/+vN$F-2E

Shop  https //stza.co/+vN$F-3l

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Braves vs. GreenJackets
END:VALARM
DTSTART:20180709T230000Z
DTEND:20180710T020000Z
UID:AGKkiHAV52JGKJGK6qkTzlB9@stanza.co
SUMMARY:Braves vs. GreenJackets
DESCRIPTION:Braves vs. GreenJackets\n\nFollow on MiLB First Pitch: https://stza.co/+vN$F-2E\n\nShop: https://stza.co/+vN$F-3l\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Braves @ Drive
<2018-07-11 Wed 18:05-21:05>
:PROPERTIES:
:ID:       qs_aaivlqdVrh3tcc-AJmWCZ@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Braves @ Drive Braves @ Drive

Follow on MiLB First Pitch  https //stza.co/+xF8V-23

Shop  https //stza.co/+xF8V-w

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Braves @ Drive
END:VALARM
DTSTART:20180711T230500Z
DTEND:20180712T020500Z
UID:qs_aaivlqdVrh3tcc-AJmWCZ@stanza.co
SUMMARY:Braves @ Drive
DESCRIPTION:Braves @ Drive\n\nFollow on MiLB First Pitch: https://stza.co/+xF8V-23\n\nShop: https://stza.co/+xF8V-w\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Braves @ Drive
<2018-07-12 Thu 18:05-21:05>
:PROPERTIES:
:ID:       0ktWFt7CmMx-o-_pR1-bV9T3@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Braves @ Drive Braves @ Drive

Follow on MiLB First Pitch  https //stza.co/+xF8W-S

Shop  https //stza.co/+xF8W-1X

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Braves @ Drive
END:VALARM
DTSTART:20180712T230500Z
DTEND:20180713T020500Z
UID:0ktWFt7CmMx-o-_pR1-bV9T3@stanza.co
SUMMARY:Braves @ Drive
DESCRIPTION:Braves @ Drive\n\nFollow on MiLB First Pitch: https://stza.co/+xF8W-S\n\nShop: https://stza.co/+xF8W-1X\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Braves @ Drive
<2018-07-13 Fri 18:05-21:05>
:PROPERTIES:
:ID:       obAYn6XVnRmrJEclVFBLWbCM@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Braves @ Drive Braves @ Drive

Follow on MiLB First Pitch  https //stza.co/+xF8X-I

Shop  https //stza.co/+xF8X-3G

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Braves @ Drive
END:VALARM
DTSTART:20180713T230500Z
DTEND:20180714T020500Z
UID:obAYn6XVnRmrJEclVFBLWbCM@stanza.co
SUMMARY:Braves @ Drive
DESCRIPTION:Braves @ Drive\n\nFollow on MiLB First Pitch: https://stza.co/+xF8X-I\n\nShop: https://stza.co/+xF8X-3G\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Braves @ GreenJackets
<2018-07-14 Sat 17:05-20:05>
:PROPERTIES:
:ID:       Vm7CSo_BRmmWcps6srvnsRYZ@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Braves @ GreenJackets Braves @ GreenJackets

Follow on MiLB First Pitch  https //stza.co/+xB_F-1C

Shop  https //stza.co/+xB_F-7

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Braves @ GreenJackets
END:VALARM
DTSTART:20180714T220500Z
DTEND:20180715T010500Z
UID:Vm7CSo_BRmmWcps6srvnsRYZ@stanza.co
SUMMARY:Braves @ GreenJackets
DESCRIPTION:Braves @ GreenJackets\n\nFollow on MiLB First Pitch: https://stza.co/+xB_F-1C\n\nShop: https://stza.co/+xB_F-7\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Braves @ GreenJackets
<2018-07-15 Sun 16:05-19:05>
:PROPERTIES:
:ID:       ura1xUUYKlSbsekhvqfGcfOQ@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Braves @ GreenJackets Braves @ GreenJackets

Follow on MiLB First Pitch  https //stza.co/+xB_K-1j

Shop  https //stza.co/+xB_K-35

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Braves @ GreenJackets
END:VALARM
DTSTART:20180715T210500Z
DTEND:20180716T000500Z
UID:ura1xUUYKlSbsekhvqfGcfOQ@stanza.co
SUMMARY:Braves @ GreenJackets
DESCRIPTION:Braves @ GreenJackets\n\nFollow on MiLB First Pitch: https://stza.co/+xB_K-1j\n\nShop: https://stza.co/+xB_K-35\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Braves @ GreenJackets
<2018-07-16 Mon 18:05-21:05>
:PROPERTIES:
:ID:       QNV_7Y8TxJ_7JgDrn6YGDtBf@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Braves @ GreenJackets Braves @ GreenJackets

Follow on MiLB First Pitch  https //stza.co/+xB_N-3S

Shop  https //stza.co/+xB_N-1G

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Braves @ GreenJackets
END:VALARM
DTSTART:20180716T230500Z
DTEND:20180717T020500Z
UID:QNV_7Y8TxJ_7JgDrn6YGDtBf@stanza.co
SUMMARY:Braves @ GreenJackets
DESCRIPTION:Braves @ GreenJackets\n\nFollow on MiLB First Pitch: https://stza.co/+xB_N-3S\n\nShop: https://stza.co/+xB_N-1G\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Braves @ GreenJackets
<2018-07-17 Tue 11:05-14:05>
:PROPERTIES:
:ID:       liXAIm0Tt8x2Q70MMqh41D0L@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Braves @ GreenJackets Braves @ GreenJackets

Follow on MiLB First Pitch  https //stza.co/+xB_R-X

Shop  https //stza.co/+xB_R-3r

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Braves @ GreenJackets
END:VALARM
DTSTART:20180717T160500Z
DTEND:20180717T190500Z
UID:liXAIm0Tt8x2Q70MMqh41D0L@stanza.co
SUMMARY:Braves @ GreenJackets
DESCRIPTION:Braves @ GreenJackets\n\nFollow on MiLB First Pitch: https://stza.co/+xB_R-X\n\nShop: https://stza.co/+xB_R-3r\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Braves vs. RiverDogs
<2018-07-19 Thu 18:00-21:00>
:PROPERTIES:
:ID:       z5bpA4lxpugEwOyf7XMs2VQM@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Braves vs. RiverDogs Braves vs. RiverDogs

Follow on MiLB First Pitch  https //stza.co/+vN$G-36

Shop  https //stza.co/+vN$G-1r

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Braves vs. RiverDogs
END:VALARM
DTSTART:20180719T230000Z
DTEND:20180720T020000Z
UID:z5bpA4lxpugEwOyf7XMs2VQM@stanza.co
SUMMARY:Braves vs. RiverDogs
DESCRIPTION:Braves vs. RiverDogs\n\nFollow on MiLB First Pitch: https://stza.co/+vN$G-36\n\nShop: https://stza.co/+vN$G-1r\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Braves vs. RiverDogs
<2018-07-20 Fri 18:00-21:00>
:PROPERTIES:
:ID:       SiEUCCOMUUzcTYm2PvMGB2wm@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Braves vs. RiverDogs Braves vs. RiverDogs

Follow on MiLB First Pitch  https //stza.co/+vN$I-3O

Shop  https //stza.co/+vN$I-5

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Braves vs. RiverDogs
END:VALARM
DTSTART:20180720T230000Z
DTEND:20180721T020000Z
UID:SiEUCCOMUUzcTYm2PvMGB2wm@stanza.co
SUMMARY:Braves vs. RiverDogs
DESCRIPTION:Braves vs. RiverDogs\n\nFollow on MiLB First Pitch: https://stza.co/+vN$I-3O\n\nShop: https://stza.co/+vN$I-5\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Braves vs. RiverDogs
<2018-07-21 Sat 17:00-20:00>
:PROPERTIES:
:ID:       7Cl1KjkB7UPtXZWOfUuiqyO4@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Braves vs. RiverDogs Braves vs. RiverDogs

Follow on MiLB First Pitch  https //stza.co/+vN$K-i

Shop  https //stza.co/+vN$K-3N

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Braves vs. RiverDogs
END:VALARM
DTSTART:20180721T220000Z
DTEND:20180722T010000Z
UID:7Cl1KjkB7UPtXZWOfUuiqyO4@stanza.co
SUMMARY:Braves vs. RiverDogs
DESCRIPTION:Braves vs. RiverDogs\n\nFollow on MiLB First Pitch: https://stza.co/+vN$K-i\n\nShop: https://stza.co/+vN$K-3N\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Braves vs. RiverDogs
<2018-07-22 Sun 13:00-16:00>
:PROPERTIES:
:ID:       o-RFnw38G0p4yDDgue0Q4itm@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Braves vs. RiverDogs Braves vs. RiverDogs

Follow on MiLB First Pitch  https //stza.co/+vN$N-1

Shop  https //stza.co/+vN$N-2w

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Braves vs. RiverDogs
END:VALARM
DTSTART:20180722T180000Z
DTEND:20180722T210000Z
UID:o-RFnw38G0p4yDDgue0Q4itm@stanza.co
SUMMARY:Braves vs. RiverDogs
DESCRIPTION:Braves vs. RiverDogs\n\nFollow on MiLB First Pitch: https://stza.co/+vN$N-1\n\nShop: https://stza.co/+vN$N-2w\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Braves vs. Fireflies
<2018-07-23 Mon 18:00-21:00>
:PROPERTIES:
:ID:       Cx-adlePN_8jDqIhgjls8Gpc@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Braves vs. Fireflies Braves vs. Fireflies

Follow on MiLB First Pitch  https //stza.co/+vN$P-3X

Shop  https //stza.co/+vN$P-1a

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Braves vs. Fireflies
END:VALARM
DTSTART:20180723T230000Z
DTEND:20180724T020000Z
UID:Cx-adlePN_8jDqIhgjls8Gpc@stanza.co
SUMMARY:Braves vs. Fireflies
DESCRIPTION:Braves vs. Fireflies\n\nFollow on MiLB First Pitch: https://stza.co/+vN$P-3X\n\nShop: https://stza.co/+vN$P-1a\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Braves vs. Fireflies
<2018-07-24 Tue 18:00-21:00>
:PROPERTIES:
:ID:       Fa1GtdcO-Wfb1dZ75gjYlq6I@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Braves vs. Fireflies Braves vs. Fireflies

Follow on MiLB First Pitch  https //stza.co/+vN$R-1e

Shop  https //stza.co/+vN$R-2x

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Braves vs. Fireflies
END:VALARM
DTSTART:20180724T230000Z
DTEND:20180725T020000Z
UID:Fa1GtdcO-Wfb1dZ75gjYlq6I@stanza.co
SUMMARY:Braves vs. Fireflies
DESCRIPTION:Braves vs. Fireflies\n\nFollow on MiLB First Pitch: https://stza.co/+vN$R-1e\n\nShop: https://stza.co/+vN$R-2x\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Braves vs. Fireflies
<2018-07-25 Wed 12:00-15:00>
:PROPERTIES:
:ID:       GE_cPqPGSKod6bqj4ukg_PZk@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Braves vs. Fireflies Braves vs. Fireflies

Follow on MiLB First Pitch  https //stza.co/+vN$S-1X

Shop  https //stza.co/+vN$S-2P

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Braves vs. Fireflies
END:VALARM
DTSTART:20180725T170000Z
DTEND:20180725T200000Z
UID:GE_cPqPGSKod6bqj4ukg_PZk@stanza.co
SUMMARY:Braves vs. Fireflies
DESCRIPTION:Braves vs. Fireflies\n\nFollow on MiLB First Pitch: https://stza.co/+vN$S-1X\n\nShop: https://stza.co/+vN$S-2P\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Braves vs. Fireflies
<2018-07-26 Thu 18:00-21:00>
:PROPERTIES:
:ID:       iqef9Ka24c0C_DnZMxkp4aMT@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Braves vs. Fireflies Braves vs. Fireflies

Follow on MiLB First Pitch  https //stza.co/+vN$U-2x

Shop  https //stza.co/+vN$U-3n

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Braves vs. Fireflies
END:VALARM
DTSTART:20180726T230000Z
DTEND:20180727T020000Z
UID:iqef9Ka24c0C_DnZMxkp4aMT@stanza.co
SUMMARY:Braves vs. Fireflies
DESCRIPTION:Braves vs. Fireflies\n\nFollow on MiLB First Pitch: https://stza.co/+vN$U-2x\n\nShop: https://stza.co/+vN$U-3n\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Braves @ Legends
<2018-07-27 Fri 18:05-21:05>
:PROPERTIES:
:ID:       YWtJmzGKhWA4hoyDhToBatQj@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Braves @ Legends Braves @ Legends

Follow on MiLB First Pitch  https //stza.co/+xB$l-W

Shop  https //stza.co/+xB$l-G

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Braves @ Legends
END:VALARM
DTSTART:20180727T230500Z
DTEND:20180728T020500Z
UID:YWtJmzGKhWA4hoyDhToBatQj@stanza.co
SUMMARY:Braves @ Legends
DESCRIPTION:Braves @ Legends\n\nFollow on MiLB First Pitch: https://stza.co/+xB$l-W\n\nShop: https://stza.co/+xB$l-G\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Braves @ Legends
<2018-07-28 Sat 17:35-20:35>
:PROPERTIES:
:ID:       ucdRpsbccmB6qUisroOwhKLQ@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Braves @ Legends Braves @ Legends

Follow on MiLB First Pitch  https //stza.co/+xB$p-3c

Shop  https //stza.co/+xB$p-7

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Braves @ Legends
END:VALARM
DTSTART:20180728T223500Z
DTEND:20180729T013500Z
UID:ucdRpsbccmB6qUisroOwhKLQ@stanza.co
SUMMARY:Braves @ Legends
DESCRIPTION:Braves @ Legends\n\nFollow on MiLB First Pitch: https://stza.co/+xB$p-3c\n\nShop: https://stza.co/+xB$p-7\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Braves @ Legends
<2018-07-29 Sun 13:05-16:05>
:PROPERTIES:
:ID:       iaz44orLp8xXrXdEuAMQot5P@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Braves @ Legends Braves @ Legends

Follow on MiLB First Pitch  https //stza.co/+xB$s-1r

Shop  https //stza.co/+xB$s-2P

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Braves @ Legends
END:VALARM
DTSTART:20180729T180500Z
DTEND:20180729T210500Z
UID:iaz44orLp8xXrXdEuAMQot5P@stanza.co
SUMMARY:Braves @ Legends
DESCRIPTION:Braves @ Legends\n\nFollow on MiLB First Pitch: https://stza.co/+xB$s-1r\n\nShop: https://stza.co/+xB$s-2P\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Braves vs. Grasshoppers
<2018-07-30 Mon 18:00-21:00>
:PROPERTIES:
:ID:       nCxXtNx6FTu4uFfEzwGHX2KQ@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Braves vs. Grasshoppers Braves vs. Grasshoppers

Follow on MiLB First Pitch  https //stza.co/+vN$X-3L

Shop  https //stza.co/+vN$X-e

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Braves vs. Grasshoppers
END:VALARM
DTSTART:20180730T230000Z
DTEND:20180731T020000Z
UID:nCxXtNx6FTu4uFfEzwGHX2KQ@stanza.co
SUMMARY:Braves vs. Grasshoppers
DESCRIPTION:Braves vs. Grasshoppers\n\nFollow on MiLB First Pitch: https://stza.co/+vN$X-3L\n\nShop: https://stza.co/+vN$X-e\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Braves vs. Grasshoppers
<2018-07-31 Tue 18:00-21:00>
:PROPERTIES:
:ID:       AR2RihGnxVZGmof1RlHXxKrj@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Braves vs. Grasshoppers Braves vs. Grasshoppers

Follow on MiLB First Pitch  https //stza.co/+vN$Y-3c

Shop  https //stza.co/+vN$Y-2B

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Braves vs. Grasshoppers
END:VALARM
DTSTART:20180731T230000Z
DTEND:20180801T020000Z
UID:AR2RihGnxVZGmof1RlHXxKrj@stanza.co
SUMMARY:Braves vs. Grasshoppers
DESCRIPTION:Braves vs. Grasshoppers\n\nFollow on MiLB First Pitch: https://stza.co/+vN$Y-3c\n\nShop: https://stza.co/+vN$Y-2B\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Braves vs. Grasshoppers
<2018-08-01 Wed 12:00-15:00>
:PROPERTIES:
:ID:       f6dn_PvB7IlxQxReoS5zfBzW@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Braves vs. Grasshoppers Braves vs. Grasshoppers

Follow on MiLB First Pitch  https //stza.co/+vN$$-2b

Shop  https //stza.co/+vN$$-20

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Braves vs. Grasshoppers
END:VALARM
DTSTART:20180801T170000Z
DTEND:20180801T200000Z
UID:f6dn_PvB7IlxQxReoS5zfBzW@stanza.co
SUMMARY:Braves vs. Grasshoppers
DESCRIPTION:Braves vs. Grasshoppers\n\nFollow on MiLB First Pitch: https://stza.co/+vN$$-2b\n\nShop: https://stza.co/+vN$$-20\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Braves @ Drive
<2018-08-02 Thu 18:05-21:05>
:PROPERTIES:
:ID:       im08SXAKveTrVSW17Nzlal3Z@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Braves @ Drive Braves @ Drive

Follow on MiLB First Pitch  https //stza.co/+xF8Y-2

Shop  https //stza.co/+xF8Y-1M

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Braves @ Drive
END:VALARM
DTSTART:20180802T230500Z
DTEND:20180803T020500Z
UID:im08SXAKveTrVSW17Nzlal3Z@stanza.co
SUMMARY:Braves @ Drive
DESCRIPTION:Braves @ Drive\n\nFollow on MiLB First Pitch: https://stza.co/+xF8Y-2\n\nShop: https://stza.co/+xF8Y-1M\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Braves @ Drive
<2018-08-03 Fri 18:05-21:05>
:PROPERTIES:
:ID:       PbmgB66qF6A6DB6cSZUSzGk6@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Braves @ Drive Braves @ Drive

Follow on MiLB First Pitch  https //stza.co/+xF8Z-3S

Shop  https //stza.co/+xF8Z-b

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Braves @ Drive
END:VALARM
DTSTART:20180803T230500Z
DTEND:20180804T020500Z
UID:PbmgB66qF6A6DB6cSZUSzGk6@stanza.co
SUMMARY:Braves @ Drive
DESCRIPTION:Braves @ Drive\n\nFollow on MiLB First Pitch: https://stza.co/+xF8Z-3S\n\nShop: https://stza.co/+xF8Z-b\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Braves @ Drive
<2018-08-04 Sat 18:05-21:05>
:PROPERTIES:
:ID:       6LB7fA7jZVCcJN7QhkYJDG17@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Braves @ Drive Braves @ Drive

Follow on MiLB First Pitch  https //stza.co/+xF8_-1Y

Shop  https //stza.co/+xF8_-1b

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Braves @ Drive
END:VALARM
DTSTART:20180804T230500Z
DTEND:20180805T020500Z
UID:6LB7fA7jZVCcJN7QhkYJDG17@stanza.co
SUMMARY:Braves @ Drive
DESCRIPTION:Braves @ Drive\n\nFollow on MiLB First Pitch: https://stza.co/+xF8_-1Y\n\nShop: https://stza.co/+xF8_-1b\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Braves @ Drive
<2018-08-05 Sun 15:05-18:05>
:PROPERTIES:
:ID:       g88sg9Y3hqB91HrRQn_UB3qy@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Braves @ Drive Braves @ Drive

Follow on MiLB First Pitch  https //stza.co/+xF8$-8

Shop  https //stza.co/+xF8$-3o

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Braves @ Drive
END:VALARM
DTSTART:20180805T200500Z
DTEND:20180805T230500Z
UID:g88sg9Y3hqB91HrRQn_UB3qy@stanza.co
SUMMARY:Braves @ Drive
DESCRIPTION:Braves @ Drive\n\nFollow on MiLB First Pitch: https://stza.co/+xF8$-8\n\nShop: https://stza.co/+xF8$-3o\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Braves vs. Shorebirds
<2018-08-07 Tue 18:00-21:00>
:PROPERTIES:
:ID:       eM3S9X-yoVFoT31kvoYzbHP5@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Braves vs. Shorebirds Braves vs. Shorebirds

Follow on MiLB First Pitch  https //stza.co/+vO01-2x

Shop  https //stza.co/+vO01-G

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Braves vs. Shorebirds
END:VALARM
DTSTART:20180807T230000Z
DTEND:20180808T020000Z
UID:eM3S9X-yoVFoT31kvoYzbHP5@stanza.co
SUMMARY:Braves vs. Shorebirds
DESCRIPTION:Braves vs. Shorebirds\n\nFollow on MiLB First Pitch: https://stza.co/+vO01-2x\n\nShop: https://stza.co/+vO01-G\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Braves vs. Shorebirds
<2018-08-08 Wed 18:00-21:00>
:PROPERTIES:
:ID:       aFnQr6LclqOF2RH-UuUl3xUq@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Braves vs. Shorebirds Braves vs. Shorebirds

Follow on MiLB First Pitch  https //stza.co/+vO02-3d

Shop  https //stza.co/+vO02-p

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Braves vs. Shorebirds
END:VALARM
DTSTART:20180808T230000Z
DTEND:20180809T020000Z
UID:aFnQr6LclqOF2RH-UuUl3xUq@stanza.co
SUMMARY:Braves vs. Shorebirds
DESCRIPTION:Braves vs. Shorebirds\n\nFollow on MiLB First Pitch: https://stza.co/+vO02-3d\n\nShop: https://stza.co/+vO02-p\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Braves vs. Shorebirds
<2018-08-09 Thu 18:00-21:00>
:PROPERTIES:
:ID:       3WiHDL6hcMKIOlvBxXgluvaj@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Braves vs. Shorebirds Braves vs. Shorebirds

Follow on MiLB First Pitch  https //stza.co/+vO05-3R

Shop  https //stza.co/+vO05-1h

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Braves vs. Shorebirds
END:VALARM
DTSTART:20180809T230000Z
DTEND:20180810T020000Z
UID:3WiHDL6hcMKIOlvBxXgluvaj@stanza.co
SUMMARY:Braves vs. Shorebirds
DESCRIPTION:Braves vs. Shorebirds\n\nFollow on MiLB First Pitch: https://stza.co/+vO05-3R\n\nShop: https://stza.co/+vO05-1h\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Braves vs. Power
<2018-08-10 Fri 18:00-21:00>
:PROPERTIES:
:ID:       SRqauqARTcmI2NJzNIAPSSbC@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Braves vs. Power Braves vs. Power

Follow on MiLB First Pitch  https //stza.co/+vO07-2p

Shop  https //stza.co/+vO07-1i

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Braves vs. Power
END:VALARM
DTSTART:20180810T230000Z
DTEND:20180811T020000Z
UID:SRqauqARTcmI2NJzNIAPSSbC@stanza.co
SUMMARY:Braves vs. Power
DESCRIPTION:Braves vs. Power\n\nFollow on MiLB First Pitch: https://stza.co/+vO07-2p\n\nShop: https://stza.co/+vO07-1i\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Braves vs. Power
<2018-08-11 Sat 17:00-20:00>
:PROPERTIES:
:ID:       vp0rdmvmSsjorkDbZpEavw9N@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Braves vs. Power Braves vs. Power

Follow on MiLB First Pitch  https //stza.co/+vO09-2a

Shop  https //stza.co/+vO09-36

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Braves vs. Power
END:VALARM
DTSTART:20180811T220000Z
DTEND:20180812T010000Z
UID:vp0rdmvmSsjorkDbZpEavw9N@stanza.co
SUMMARY:Braves vs. Power
DESCRIPTION:Braves vs. Power\n\nFollow on MiLB First Pitch: https://stza.co/+vO09-2a\n\nShop: https://stza.co/+vO09-36\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Braves vs. Power
<2018-08-12 Sun 13:00-16:00>
:PROPERTIES:
:ID:       hnSGwJ8gwnB4Y1ef9akCdRbo@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Braves vs. Power Braves vs. Power

Follow on MiLB First Pitch  https //stza.co/+vO0b-2w

Shop  https //stza.co/+vO0b-3p

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Braves vs. Power
END:VALARM
DTSTART:20180812T180000Z
DTEND:20180812T210000Z
UID:hnSGwJ8gwnB4Y1ef9akCdRbo@stanza.co
SUMMARY:Braves vs. Power
DESCRIPTION:Braves vs. Power\n\nFollow on MiLB First Pitch: https://stza.co/+vO0b-2w\n\nShop: https://stza.co/+vO0b-3p\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Braves vs. Power
<2018-08-13 Mon 18:00-21:00>
:PROPERTIES:
:ID:       mGVSVtF9BYBNCsEwLnQ8dSpY@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Braves vs. Power Braves vs. Power

Follow on MiLB First Pitch  https //stza.co/+vO0d-14

Shop  https //stza.co/+vO0d-v

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Braves vs. Power
END:VALARM
DTSTART:20180813T230000Z
DTEND:20180814T020000Z
UID:mGVSVtF9BYBNCsEwLnQ8dSpY@stanza.co
SUMMARY:Braves vs. Power
DESCRIPTION:Braves vs. Power\n\nFollow on MiLB First Pitch: https://stza.co/+vO0d-14\n\nShop: https://stza.co/+vO0d-v\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Braves @ BlueClaws
<2018-08-15 Wed 18:05-21:05>
:PROPERTIES:
:ID:       PEUv4BDXuhZfTtR4Zi-pbSfI@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Braves @ BlueClaws Braves @ BlueClaws

Follow on MiLB First Pitch  https //stza.co/+vN_8-3R

Shop  https //stza.co/+vN_8-3q

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Braves @ BlueClaws
END:VALARM
DTSTART:20180815T230500Z
DTEND:20180816T020500Z
UID:PEUv4BDXuhZfTtR4Zi-pbSfI@stanza.co
SUMMARY:Braves @ BlueClaws
DESCRIPTION:Braves @ BlueClaws\n\nFollow on MiLB First Pitch: https://stza.co/+vN_8-3R\n\nShop: https://stza.co/+vN_8-3q\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Braves @ BlueClaws
<2018-08-16 Thu 18:05-21:05>
:PROPERTIES:
:ID:       QBgzj1l0ye3ZuNeth-dbDgxD@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Braves @ BlueClaws Braves @ BlueClaws

Follow on MiLB First Pitch  https //stza.co/+vN_9-23

Shop  https //stza.co/+vN_9-1$

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Braves @ BlueClaws
END:VALARM
DTSTART:20180816T230500Z
DTEND:20180817T020500Z
UID:QBgzj1l0ye3ZuNeth-dbDgxD@stanza.co
SUMMARY:Braves @ BlueClaws
DESCRIPTION:Braves @ BlueClaws\n\nFollow on MiLB First Pitch: https://stza.co/+vN_9-23\n\nShop: https://stza.co/+vN_9-1$\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Braves @ BlueClaws
<2018-08-17 Fri 18:05-21:05>
:PROPERTIES:
:ID:       FLkHDJA5czmizd-eH80tm_1f@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Braves @ BlueClaws Braves @ BlueClaws

Follow on MiLB First Pitch  https //stza.co/+vN_a-2m

Shop  https //stza.co/+vN_a-3l

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Braves @ BlueClaws
END:VALARM
DTSTART:20180817T230500Z
DTEND:20180818T020500Z
UID:FLkHDJA5czmizd-eH80tm_1f@stanza.co
SUMMARY:Braves @ BlueClaws
DESCRIPTION:Braves @ BlueClaws\n\nFollow on MiLB First Pitch: https://stza.co/+vN_a-2m\n\nShop: https://stza.co/+vN_a-3l\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Braves @ Shorebirds
<2018-08-18 Sat 18:05-21:05>
:PROPERTIES:
:ID:       yVbYSlz2hOCEoKGoyS6gIWKc@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Braves @ Shorebirds Braves @ Shorebirds

Follow on MiLB First Pitch  https //stza.co/+wHSC-3O

Shop  https //stza.co/+wHSC-14

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Braves @ Shorebirds
END:VALARM
DTSTART:20180818T230500Z
DTEND:20180819T020500Z
UID:yVbYSlz2hOCEoKGoyS6gIWKc@stanza.co
SUMMARY:Braves @ Shorebirds
DESCRIPTION:Braves @ Shorebirds\n\nFollow on MiLB First Pitch: https://stza.co/+wHSC-3O\n\nShop: https://stza.co/+wHSC-14\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Braves @ Shorebirds
<2018-08-19 Sun 16:05-19:05>
:PROPERTIES:
:ID:       wNW4j7etLUqh281CWTrDoAu-@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Braves @ Shorebirds Braves @ Shorebirds

Follow on MiLB First Pitch  https //stza.co/+wHSD-4

Shop  https //stza.co/+wHSD-1a

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Braves @ Shorebirds
END:VALARM
DTSTART:20180819T210500Z
DTEND:20180820T000500Z
UID:wNW4j7etLUqh281CWTrDoAu-@stanza.co
SUMMARY:Braves @ Shorebirds
DESCRIPTION:Braves @ Shorebirds\n\nFollow on MiLB First Pitch: https://stza.co/+wHSD-4\n\nShop: https://stza.co/+wHSD-1a\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Braves @ Shorebirds
<2018-08-20 Mon 18:05-21:05>
:PROPERTIES:
:ID:       8rVC_NEKuS4FO3HS1x4Ywc88@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Braves @ Shorebirds Braves @ Shorebirds

Follow on MiLB First Pitch  https //stza.co/+wHSE-2q

Shop  https //stza.co/+wHSE-d

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Braves @ Shorebirds
END:VALARM
DTSTART:20180820T230500Z
DTEND:20180821T020500Z
UID:8rVC_NEKuS4FO3HS1x4Ywc88@stanza.co
SUMMARY:Braves @ Shorebirds
DESCRIPTION:Braves @ Shorebirds\n\nFollow on MiLB First Pitch: https://stza.co/+wHSE-2q\n\nShop: https://stza.co/+wHSE-d\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Braves @ Shorebirds
<2018-08-21 Tue 18:05-21:05>
:PROPERTIES:
:ID:       GF93pHZ8LNLjdNyzIUnEtZ1w@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Braves @ Shorebirds Braves @ Shorebirds

Follow on MiLB First Pitch  https //stza.co/+wHRX-1j

Shop  https //stza.co/+wHRX-Y

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Braves @ Shorebirds
END:VALARM
DTSTART:20180821T230500Z
DTEND:20180822T020500Z
UID:GF93pHZ8LNLjdNyzIUnEtZ1w@stanza.co
SUMMARY:Braves @ Shorebirds
DESCRIPTION:Braves @ Shorebirds\n\nFollow on MiLB First Pitch: https://stza.co/+wHRX-1j\n\nShop: https://stza.co/+wHRX-Y\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Braves vs. Power
<2018-08-23 Thu 18:00-21:00>
:PROPERTIES:
:ID:       BBt0k2LfO6XGdEn5LVcfbmWH@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Braves vs. Power Braves vs. Power

Follow on MiLB First Pitch  https //stza.co/+vO0e-2F

Shop  https //stza.co/+vO0e-h

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Braves vs. Power
END:VALARM
DTSTART:20180823T230000Z
DTEND:20180824T020000Z
UID:BBt0k2LfO6XGdEn5LVcfbmWH@stanza.co
SUMMARY:Braves vs. Power
DESCRIPTION:Braves vs. Power\n\nFollow on MiLB First Pitch: https://stza.co/+vO0e-2F\n\nShop: https://stza.co/+vO0e-h\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Braves vs. Power
<2018-08-24 Fri 18:00-21:00>
:PROPERTIES:
:ID:       WOToDJQbPHockRXtVQc2V5C-@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Braves vs. Power Braves vs. Power

Follow on MiLB First Pitch  https //stza.co/+vO0h-2U

Shop  https //stza.co/+vO0h-r

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Braves vs. Power
END:VALARM
DTSTART:20180824T230000Z
DTEND:20180825T020000Z
UID:WOToDJQbPHockRXtVQc2V5C-@stanza.co
SUMMARY:Braves vs. Power
DESCRIPTION:Braves vs. Power\n\nFollow on MiLB First Pitch: https://stza.co/+vO0h-2U\n\nShop: https://stza.co/+vO0h-r\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Braves vs. Power
<2018-08-25 Sat 17:00-20:00>
:PROPERTIES:
:ID:       c1Cho2JPvT5RxYYAuK1Tt8Gy@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Braves vs. Power Braves vs. Power

Follow on MiLB First Pitch  https //stza.co/+vO0j-1Y

Shop  https //stza.co/+vO0j-24

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Braves vs. Power
END:VALARM
DTSTART:20180825T220000Z
DTEND:20180826T010000Z
UID:c1Cho2JPvT5RxYYAuK1Tt8Gy@stanza.co
SUMMARY:Braves vs. Power
DESCRIPTION:Braves vs. Power\n\nFollow on MiLB First Pitch: https://stza.co/+vO0j-1Y\n\nShop: https://stza.co/+vO0j-24\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Braves vs. Power
<2018-08-26 Sun 13:00-16:00>
:PROPERTIES:
:ID:       iuity0dy99GmMX_kKOORM5zn@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Braves vs. Power Braves vs. Power

Follow on MiLB First Pitch  https //stza.co/+vO0l-32

Shop  https //stza.co/+vO0l-3B

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Braves vs. Power
END:VALARM
DTSTART:20180826T180000Z
DTEND:20180826T210000Z
UID:iuity0dy99GmMX_kKOORM5zn@stanza.co
SUMMARY:Braves vs. Power
DESCRIPTION:Braves vs. Power\n\nFollow on MiLB First Pitch: https://stza.co/+vO0l-32\n\nShop: https://stza.co/+vO0l-3B\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Braves vs. Drive
<2018-08-27 Mon 18:00-21:00>
:PROPERTIES:
:ID:       LyG-xOYUpzLpY7i2Vr_HdLIJ@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Braves vs. Drive Braves vs. Drive

Follow on MiLB First Pitch  https //stza.co/+vO0m-12

Shop  https //stza.co/+vO0m-38

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Braves vs. Drive
END:VALARM
DTSTART:20180827T230000Z
DTEND:20180828T020000Z
UID:LyG-xOYUpzLpY7i2Vr_HdLIJ@stanza.co
SUMMARY:Braves vs. Drive
DESCRIPTION:Braves vs. Drive\n\nFollow on MiLB First Pitch: https://stza.co/+vO0m-12\n\nShop: https://stza.co/+vO0m-38\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Braves vs. Drive
<2018-08-28 Tue 18:00-21:00>
:PROPERTIES:
:ID:       s4O7Jk8ApwYta3ELExc9H_iZ@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Braves vs. Drive Braves vs. Drive

Follow on MiLB First Pitch  https //stza.co/+vO0o-3A

Shop  https //stza.co/+vO0o-1o

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Braves vs. Drive
END:VALARM
DTSTART:20180828T230000Z
DTEND:20180829T020000Z
UID:s4O7Jk8ApwYta3ELExc9H_iZ@stanza.co
SUMMARY:Braves vs. Drive
DESCRIPTION:Braves vs. Drive\n\nFollow on MiLB First Pitch: https://stza.co/+vO0o-3A\n\nShop: https://stza.co/+vO0o-1o\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Braves vs. Drive
<2018-08-29 Wed 18:00-21:00>
:PROPERTIES:
:ID:       4sAk0uo3di95uUxP5PzBxhZ5@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Braves vs. Drive Braves vs. Drive

Follow on MiLB First Pitch  https //stza.co/+vO0q-1X

Shop  https //stza.co/+vO0q-3T

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Braves vs. Drive
END:VALARM
DTSTART:20180829T230000Z
DTEND:20180830T020000Z
UID:4sAk0uo3di95uUxP5PzBxhZ5@stanza.co
SUMMARY:Braves vs. Drive
DESCRIPTION:Braves vs. Drive\n\nFollow on MiLB First Pitch: https://stza.co/+vO0q-1X\n\nShop: https://stza.co/+vO0q-3T\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Braves vs. Drive
<2018-08-30 Thu 18:00-21:00>
:PROPERTIES:
:ID:       DDRX_mc2DghHDT-SXbY-JiA5@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Braves vs. Drive Braves vs. Drive

Follow on MiLB First Pitch  https //stza.co/+vO0t-T

Shop  https //stza.co/+vO0t-2q

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Braves vs. Drive
END:VALARM
DTSTART:20180830T230000Z
DTEND:20180831T020000Z
UID:DDRX_mc2DghHDT-SXbY-JiA5@stanza.co
SUMMARY:Braves vs. Drive
DESCRIPTION:Braves vs. Drive\n\nFollow on MiLB First Pitch: https://stza.co/+vO0t-T\n\nShop: https://stza.co/+vO0t-2q\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Braves @ Tourists
<2018-08-31 Fri 18:05-21:05>
:PROPERTIES:
:ID:       gTSwsbWfMN_rHMfmdhTOOPRU@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Braves @ Tourists Braves @ Tourists

Follow on MiLB First Pitch  https //stza.co/+vNZp-34

Shop  https //stza.co/+vNZp-2f

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Braves @ Tourists
END:VALARM
DTSTART:20180831T230500Z
DTEND:20180901T020500Z
UID:gTSwsbWfMN_rHMfmdhTOOPRU@stanza.co
SUMMARY:Braves @ Tourists
DESCRIPTION:Braves @ Tourists\n\nFollow on MiLB First Pitch: https://stza.co/+vNZp-34\n\nShop: https://stza.co/+vNZp-2f\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Braves @ Tourists
<2018-09-01 Sat 17:05-20:05>
:PROPERTIES:
:ID:       cRXW4zGWfuYQIp3ejlsQfoq_@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Braves @ Tourists Braves @ Tourists

Follow on MiLB First Pitch  https //stza.co/+vNZq-2H

Shop  https //stza.co/+vNZq-1d

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Braves @ Tourists
END:VALARM
DTSTART:20180901T220500Z
DTEND:20180902T010500Z
UID:cRXW4zGWfuYQIp3ejlsQfoq_@stanza.co
SUMMARY:Braves @ Tourists
DESCRIPTION:Braves @ Tourists\n\nFollow on MiLB First Pitch: https://stza.co/+vNZq-2H\n\nShop: https://stza.co/+vNZq-1d\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Braves @ Tourists
<2018-09-02 Sun 18:05-21:05>
:PROPERTIES:
:ID:       ZCTj-zEkS-e8bNPGYrrml7XO@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Braves @ Tourists Braves @ Tourists

Follow on MiLB First Pitch  https //stza.co/+xBZZ-1f

Shop  https //stza.co/+xBZZ-E

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Braves @ Tourists
END:VALARM
DTSTART:20180902T230500Z
DTEND:20180903T020500Z
UID:ZCTj-zEkS-e8bNPGYrrml7XO@stanza.co
SUMMARY:Braves @ Tourists
DESCRIPTION:Braves @ Tourists\n\nFollow on MiLB First Pitch: https://stza.co/+xBZZ-1f\n\nShop: https://stza.co/+xBZZ-E\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
* Braves @ Tourists
<2018-09-03 Mon 12:05-15:05>
:PROPERTIES:
:ID:       lA3Xb71qlLeZp8jlYZXvt3qr@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Braves @ Tourists Braves @ Tourists

Follow on MiLB First Pitch  https //stza.co/+xB_2-1D

Shop  https //stza.co/+xB_2-2H

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Braves @ Tourists
END:VALARM
DTSTART:20180903T170500Z
DTEND:20180903T200500Z
UID:lA3Xb71qlLeZp8jlYZXvt3qr@stanza.co
SUMMARY:Braves @ Tourists
DESCRIPTION:Braves @ Tourists\n\nFollow on MiLB First Pitch: https://stza.co/+xB_2-1D\n\nShop: https://stza.co/+xB_2-2H\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144554Z
LAST-MODIFIED:20180213T144554Z
TRANSP:OPAQUE
END:VEVENT
