#+TITLE:       Main Google calendar entries
#+AUTHOR:      Eric S Fraga
#+EMAIL:       e.fraga@ucl.ac.uk
#+DESCRIPTION: converted using the ical2org awk script
#+CATEGORY:    google
#+STARTUP:     hidestars
#+STARTUP:     overview

* COMMENT original iCal preamble

* Sky Sox @ Storm Chasers
<2018-04-05 Thu 18:35-21:35>
:PROPERTIES:
:ID:       nYMS_Sod_zduXVnggOWWdQcU@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Sky Sox @ Storm Chasers Sky Sox @ Storm Chasers

Follow on MiLB First Pitch  https //stza.co/+whCw-X

Shop  https //stza.co/+whCw-1W

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Sky Sox @ Storm Chasers
END:VALARM
DTSTART:20180405T233500Z
DTEND:20180406T023500Z
UID:nYMS_Sod_zduXVnggOWWdQcU@stanza.co
SUMMARY:Sky Sox @ Storm Chasers
DESCRIPTION:Sky Sox @ Storm Chasers\n\nFollow on MiLB First Pitch: https://stza.co/+whCw-X\n\nShop: https://stza.co/+whCw-1W\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144515Z
LAST-MODIFIED:20180213T144515Z
TRANSP:OPAQUE
END:VEVENT
* Sky Sox @ Storm Chasers
<2018-04-06 Fri 19:05-22:05>
:PROPERTIES:
:ID:       7ETX8UZ24k4dQn5LCERjfDex@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Sky Sox @ Storm Chasers Sky Sox @ Storm Chasers

Follow on MiLB First Pitch  https //stza.co/+whCx-8

Shop  https //stza.co/+whCx-1K

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Sky Sox @ Storm Chasers
END:VALARM
DTSTART:20180407T000500Z
DTEND:20180407T030500Z
UID:7ETX8UZ24k4dQn5LCERjfDex@stanza.co
SUMMARY:Sky Sox @ Storm Chasers
DESCRIPTION:Sky Sox @ Storm Chasers\n\nFollow on MiLB First Pitch: https://stza.co/+whCx-8\n\nShop: https://stza.co/+whCx-1K\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144515Z
LAST-MODIFIED:20180213T144515Z
TRANSP:OPAQUE
END:VEVENT
* Sky Sox @ Storm Chasers
<2018-04-07 Sat 14:05-17:05>
:PROPERTIES:
:ID:       ZuDrWM1w01_AynHiEzumFo3r@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Sky Sox @ Storm Chasers Sky Sox @ Storm Chasers

Follow on MiLB First Pitch  https //stza.co/+whCy-A

Shop  https //stza.co/+whCy-3t

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Sky Sox @ Storm Chasers
END:VALARM
DTSTART:20180407T190500Z
DTEND:20180407T220500Z
UID:ZuDrWM1w01_AynHiEzumFo3r@stanza.co
SUMMARY:Sky Sox @ Storm Chasers
DESCRIPTION:Sky Sox @ Storm Chasers\n\nFollow on MiLB First Pitch: https://stza.co/+whCy-A\n\nShop: https://stza.co/+whCy-3t\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144515Z
LAST-MODIFIED:20180213T144515Z
TRANSP:OPAQUE
END:VEVENT
* Sky Sox @ Storm Chasers
<2018-04-08 Sun 14:05-17:05>
:PROPERTIES:
:ID:       etFl5xKwDe5HmxB19vUpX_mT@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Sky Sox @ Storm Chasers Sky Sox @ Storm Chasers

Follow on MiLB First Pitch  https //stza.co/+whCz-3B

Shop  https //stza.co/+whCz-l

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Sky Sox @ Storm Chasers
END:VALARM
DTSTART:20180408T190500Z
DTEND:20180408T220500Z
UID:etFl5xKwDe5HmxB19vUpX_mT@stanza.co
SUMMARY:Sky Sox @ Storm Chasers
DESCRIPTION:Sky Sox @ Storm Chasers\n\nFollow on MiLB First Pitch: https://stza.co/+whCz-3B\n\nShop: https://stza.co/+whCz-l\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144515Z
LAST-MODIFIED:20180213T144515Z
TRANSP:OPAQUE
END:VEVENT
* Sky Sox @ Storm Chasers
<2018-04-09 Mon 11:05-14:05>
:PROPERTIES:
:ID:       HTHwejPk_EPBdMzX_kopcIMx@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Sky Sox @ Storm Chasers Sky Sox @ Storm Chasers

Follow on MiLB First Pitch  https //stza.co/+whCA-14

Shop  https //stza.co/+whCA-2n

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Sky Sox @ Storm Chasers
END:VALARM
DTSTART:20180409T160500Z
DTEND:20180409T190500Z
UID:HTHwejPk_EPBdMzX_kopcIMx@stanza.co
SUMMARY:Sky Sox @ Storm Chasers
DESCRIPTION:Sky Sox @ Storm Chasers\n\nFollow on MiLB First Pitch: https://stza.co/+whCA-14\n\nShop: https://stza.co/+whCA-2n\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144515Z
LAST-MODIFIED:20180213T144515Z
TRANSP:OPAQUE
END:VEVENT
* Sky Sox vs. Baby Cakes
<2018-04-10 Tue 19:40-22:40>
:PROPERTIES:
:ID:       D5ikBsaC_1Gn2Bq42kEAPCld@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Sky Sox vs. Baby Cakes Sky Sox vs. Baby Cakes

Follow on MiLB First Pitch  https //stza.co/+wmw4-b

Shop  https //stza.co/+wmw4-y

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Sky Sox vs. Baby Cakes
END:VALARM
DTSTART:20180411T004000Z
DTEND:20180411T034000Z
UID:D5ikBsaC_1Gn2Bq42kEAPCld@stanza.co
SUMMARY:Sky Sox vs. Baby Cakes
DESCRIPTION:Sky Sox vs. Baby Cakes\n\nFollow on MiLB First Pitch: https://stza.co/+wmw4-b\n\nShop: https://stza.co/+wmw4-y\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144515Z
LAST-MODIFIED:20180213T144515Z
TRANSP:OPAQUE
END:VEVENT
* Sky Sox vs. Baby Cakes
<2018-04-11 Wed 19:40-22:40>
:PROPERTIES:
:ID:       IO15rt5JjBcB0IgMG1oxt8Aa@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Sky Sox vs. Baby Cakes Sky Sox vs. Baby Cakes

Follow on MiLB First Pitch  https //stza.co/+wmw6-2w

Shop  https //stza.co/+wmw6-12

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Sky Sox vs. Baby Cakes
END:VALARM
DTSTART:20180412T004000Z
DTEND:20180412T034000Z
UID:IO15rt5JjBcB0IgMG1oxt8Aa@stanza.co
SUMMARY:Sky Sox vs. Baby Cakes
DESCRIPTION:Sky Sox vs. Baby Cakes\n\nFollow on MiLB First Pitch: https://stza.co/+wmw6-2w\n\nShop: https://stza.co/+wmw6-12\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144515Z
LAST-MODIFIED:20180213T144515Z
TRANSP:OPAQUE
END:VEVENT
* Sky Sox vs. Baby Cakes
<2018-04-12 Thu 19:40-22:40>
:PROPERTIES:
:ID:       4wuIx_ZSMIG_bJ5EsrxZwyFm@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Sky Sox vs. Baby Cakes Sky Sox vs. Baby Cakes

Follow on MiLB First Pitch  https //stza.co/+wmw8-1u

Shop  https //stza.co/+wmw8-3N

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Sky Sox vs. Baby Cakes
END:VALARM
DTSTART:20180413T004000Z
DTEND:20180413T034000Z
UID:4wuIx_ZSMIG_bJ5EsrxZwyFm@stanza.co
SUMMARY:Sky Sox vs. Baby Cakes
DESCRIPTION:Sky Sox vs. Baby Cakes\n\nFollow on MiLB First Pitch: https://stza.co/+wmw8-1u\n\nShop: https://stza.co/+wmw8-3N\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144515Z
LAST-MODIFIED:20180213T144515Z
TRANSP:OPAQUE
END:VEVENT
* Sky Sox vs. Express
<2018-04-13 Fri 19:40-22:40>
:PROPERTIES:
:ID:       RYi8NsMPQT-wqB2QNHnnfKet@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Sky Sox vs. Express Sky Sox vs. Express

Follow on MiLB First Pitch  https //stza.co/+wmwb-1s

Shop  https //stza.co/+wmwb-1F

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Sky Sox vs. Express
END:VALARM
DTSTART:20180414T004000Z
DTEND:20180414T034000Z
UID:RYi8NsMPQT-wqB2QNHnnfKet@stanza.co
SUMMARY:Sky Sox vs. Express
DESCRIPTION:Sky Sox vs. Express\n\nFollow on MiLB First Pitch: https://stza.co/+wmwb-1s\n\nShop: https://stza.co/+wmwb-1F\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144515Z
LAST-MODIFIED:20180213T144515Z
TRANSP:OPAQUE
END:VEVENT
* Sky Sox vs. Express
<2018-04-14 Sat 17:00-20:00>
:PROPERTIES:
:ID:       xpLHlF2dZ7wMBGhgdGu88Y11@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Sky Sox vs. Express Sky Sox vs. Express

Follow on MiLB First Pitch  https //stza.co/+wmwd-2

Shop  https //stza.co/+wmwd-3t

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Sky Sox vs. Express
END:VALARM
DTSTART:20180414T220000Z
DTEND:20180415T010000Z
UID:xpLHlF2dZ7wMBGhgdGu88Y11@stanza.co
SUMMARY:Sky Sox vs. Express
DESCRIPTION:Sky Sox vs. Express\n\nFollow on MiLB First Pitch: https://stza.co/+wmwd-2\n\nShop: https://stza.co/+wmwd-3t\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144515Z
LAST-MODIFIED:20180213T144515Z
TRANSP:OPAQUE
END:VEVENT
* Sky Sox vs. Express
<2018-04-15 Sun 14:30-17:30>
:PROPERTIES:
:ID:       GBOmh4pjRm_B1NMKp4euyYaz@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Sky Sox vs. Express Sky Sox vs. Express

Follow on MiLB First Pitch  https //stza.co/+wmwf-2B

Shop  https //stza.co/+wmwf-1V

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Sky Sox vs. Express
END:VALARM
DTSTART:20180415T193000Z
DTEND:20180415T223000Z
UID:GBOmh4pjRm_B1NMKp4euyYaz@stanza.co
SUMMARY:Sky Sox vs. Express
DESCRIPTION:Sky Sox vs. Express\n\nFollow on MiLB First Pitch: https://stza.co/+wmwf-2B\n\nShop: https://stza.co/+wmwf-1V\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144515Z
LAST-MODIFIED:20180213T144515Z
TRANSP:OPAQUE
END:VEVENT
* Sky Sox vs. Express
<2018-04-16 Mon 12:05-15:05>
:PROPERTIES:
:ID:       uWShkMOcbVzRDxRfgq_m6ur8@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Sky Sox vs. Express Sky Sox vs. Express

Follow on MiLB First Pitch  https //stza.co/+wmwh-1k

Shop  https //stza.co/+wmwh-R

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Sky Sox vs. Express
END:VALARM
DTSTART:20180416T170500Z
DTEND:20180416T200500Z
UID:uWShkMOcbVzRDxRfgq_m6ur8@stanza.co
SUMMARY:Sky Sox vs. Express
DESCRIPTION:Sky Sox vs. Express\n\nFollow on MiLB First Pitch: https://stza.co/+wmwh-1k\n\nShop: https://stza.co/+wmwh-R\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144515Z
LAST-MODIFIED:20180213T144515Z
TRANSP:OPAQUE
END:VEVENT
* Sky Sox @ Baby Cakes
<2018-04-17 Tue 19:00-22:00>
:PROPERTIES:
:ID:       w5U7p47FklnqKtU8kf2dYAj8@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Sky Sox @ Baby Cakes Sky Sox @ Baby Cakes

Follow on MiLB First Pitch  https //stza.co/+whCo-2V

Shop  https //stza.co/+whCo-1x

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Sky Sox @ Baby Cakes
END:VALARM
DTSTART:20180418T000000Z
DTEND:20180418T030000Z
UID:w5U7p47FklnqKtU8kf2dYAj8@stanza.co
SUMMARY:Sky Sox @ Baby Cakes
DESCRIPTION:Sky Sox @ Baby Cakes\n\nFollow on MiLB First Pitch: https://stza.co/+whCo-2V\n\nShop: https://stza.co/+whCo-1x\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144515Z
LAST-MODIFIED:20180213T144515Z
TRANSP:OPAQUE
END:VEVENT
* Sky Sox @ Baby Cakes
<2018-04-18 Wed 19:00-22:00>
:PROPERTIES:
:ID:       v5haXOTBnrAe3I8XfnLuYHwL@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Sky Sox @ Baby Cakes Sky Sox @ Baby Cakes

Follow on MiLB First Pitch  https //stza.co/+whCp-2G

Shop  https //stza.co/+whCp-1_

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Sky Sox @ Baby Cakes
END:VALARM
DTSTART:20180419T000000Z
DTEND:20180419T030000Z
UID:v5haXOTBnrAe3I8XfnLuYHwL@stanza.co
SUMMARY:Sky Sox @ Baby Cakes
DESCRIPTION:Sky Sox @ Baby Cakes\n\nFollow on MiLB First Pitch: https://stza.co/+whCp-2G\n\nShop: https://stza.co/+whCp-1_\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144515Z
LAST-MODIFIED:20180213T144515Z
TRANSP:OPAQUE
END:VEVENT
* Sky Sox @ Baby Cakes
<2018-04-19 Thu 19:00-22:00>
:PROPERTIES:
:ID:       uxn54Wb-fpGL-tYVwtxVr7LL@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Sky Sox @ Baby Cakes Sky Sox @ Baby Cakes

Follow on MiLB First Pitch  https //stza.co/+whCq-c

Shop  https //stza.co/+whCq-d

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Sky Sox @ Baby Cakes
END:VALARM
DTSTART:20180420T000000Z
DTEND:20180420T030000Z
UID:uxn54Wb-fpGL-tYVwtxVr7LL@stanza.co
SUMMARY:Sky Sox @ Baby Cakes
DESCRIPTION:Sky Sox @ Baby Cakes\n\nFollow on MiLB First Pitch: https://stza.co/+whCq-c\n\nShop: https://stza.co/+whCq-d\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144515Z
LAST-MODIFIED:20180213T144515Z
TRANSP:OPAQUE
END:VEVENT
* Sky Sox @ Baby Cakes
<2018-04-20 Fri 19:00-22:00>
:PROPERTIES:
:ID:       HMm97p2yQYsiJDkm9dDJkJWW@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Sky Sox @ Baby Cakes Sky Sox @ Baby Cakes

Follow on MiLB First Pitch  https //stza.co/+whCr-2t

Shop  https //stza.co/+whCr-2Q

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Sky Sox @ Baby Cakes
END:VALARM
DTSTART:20180421T000000Z
DTEND:20180421T030000Z
UID:HMm97p2yQYsiJDkm9dDJkJWW@stanza.co
SUMMARY:Sky Sox @ Baby Cakes
DESCRIPTION:Sky Sox @ Baby Cakes\n\nFollow on MiLB First Pitch: https://stza.co/+whCr-2t\n\nShop: https://stza.co/+whCr-2Q\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144515Z
LAST-MODIFIED:20180213T144515Z
TRANSP:OPAQUE
END:VEVENT
* Sky Sox @ Express
<2018-04-21 Sat 19:05-22:05>
:PROPERTIES:
:ID:       E2w32y8vUlwq9pMdg1UcJbhx@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Sky Sox @ Express Sky Sox @ Express

Follow on MiLB First Pitch  https //stza.co/+vKvC-A

Shop  https //stza.co/+vKvC-t

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Sky Sox @ Express
END:VALARM
DTSTART:20180422T000500Z
DTEND:20180422T030500Z
UID:E2w32y8vUlwq9pMdg1UcJbhx@stanza.co
SUMMARY:Sky Sox @ Express
DESCRIPTION:Sky Sox @ Express\n\nFollow on MiLB First Pitch: https://stza.co/+vKvC-A\n\nShop: https://stza.co/+vKvC-t\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144515Z
LAST-MODIFIED:20180213T144515Z
TRANSP:OPAQUE
END:VEVENT
* Sky Sox @ Express
<2018-04-22 Sun 13:05-16:05>
:PROPERTIES:
:ID:       FF22bQAYeT3EMIPhD5FVQpMJ@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Sky Sox @ Express Sky Sox @ Express

Follow on MiLB First Pitch  https //stza.co/+vKvD-1a

Shop  https //stza.co/+vKvD-b

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Sky Sox @ Express
END:VALARM
DTSTART:20180422T180500Z
DTEND:20180422T210500Z
UID:FF22bQAYeT3EMIPhD5FVQpMJ@stanza.co
SUMMARY:Sky Sox @ Express
DESCRIPTION:Sky Sox @ Express\n\nFollow on MiLB First Pitch: https://stza.co/+vKvD-1a\n\nShop: https://stza.co/+vKvD-b\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144515Z
LAST-MODIFIED:20180213T144515Z
TRANSP:OPAQUE
END:VEVENT
* Sky Sox @ Express
<2018-04-23 Mon 19:05-22:05>
:PROPERTIES:
:ID:       84VZ_7TAGtOnNbKBK9hrzVbH@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Sky Sox @ Express Sky Sox @ Express

Follow on MiLB First Pitch  https //stza.co/+vKvE-2f

Shop  https //stza.co/+vKvE-1a

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Sky Sox @ Express
END:VALARM
DTSTART:20180424T000500Z
DTEND:20180424T030500Z
UID:84VZ_7TAGtOnNbKBK9hrzVbH@stanza.co
SUMMARY:Sky Sox @ Express
DESCRIPTION:Sky Sox @ Express\n\nFollow on MiLB First Pitch: https://stza.co/+vKvE-2f\n\nShop: https://stza.co/+vKvE-1a\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144515Z
LAST-MODIFIED:20180213T144515Z
TRANSP:OPAQUE
END:VEVENT
* Sky Sox vs. Storm Chasers
<2018-04-25 Wed 19:40-22:40>
:PROPERTIES:
:ID:       wtAEIzAAdNCWJdovvCrA6wfm@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Sky Sox vs. Storm Chasers Sky Sox vs. Storm Chasers

Follow on MiLB First Pitch  https //stza.co/+wmwi-2d

Shop  https //stza.co/+wmwi-16

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Sky Sox vs. Storm Chasers
END:VALARM
DTSTART:20180426T004000Z
DTEND:20180426T034000Z
UID:wtAEIzAAdNCWJdovvCrA6wfm@stanza.co
SUMMARY:Sky Sox vs. Storm Chasers
DESCRIPTION:Sky Sox vs. Storm Chasers\n\nFollow on MiLB First Pitch: https://stza.co/+wmwi-2d\n\nShop: https://stza.co/+wmwi-16\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144515Z
LAST-MODIFIED:20180213T144515Z
TRANSP:OPAQUE
END:VEVENT
* Sky Sox vs. Storm Chasers
<2018-04-26 Thu 19:40-22:40>
:PROPERTIES:
:ID:       8OIWO1bXEjiu1pad82GX9Nn6@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Sky Sox vs. Storm Chasers Sky Sox vs. Storm Chasers

Follow on MiLB First Pitch  https //stza.co/+wmwl-K

Shop  https //stza.co/+wmwl-3G

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Sky Sox vs. Storm Chasers
END:VALARM
DTSTART:20180427T004000Z
DTEND:20180427T034000Z
UID:8OIWO1bXEjiu1pad82GX9Nn6@stanza.co
SUMMARY:Sky Sox vs. Storm Chasers
DESCRIPTION:Sky Sox vs. Storm Chasers\n\nFollow on MiLB First Pitch: https://stza.co/+wmwl-K\n\nShop: https://stza.co/+wmwl-3G\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144515Z
LAST-MODIFIED:20180213T144515Z
TRANSP:OPAQUE
END:VEVENT
* Sky Sox vs. Storm Chasers
<2018-04-27 Fri 19:40-22:40>
:PROPERTIES:
:ID:       I2uEJLDr5R4IB3skx8pNhGdi@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Sky Sox vs. Storm Chasers Sky Sox vs. Storm Chasers

Follow on MiLB First Pitch  https //stza.co/+wmwm-3S

Shop  https //stza.co/+wmwm-1s

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Sky Sox vs. Storm Chasers
END:VALARM
DTSTART:20180428T004000Z
DTEND:20180428T034000Z
UID:I2uEJLDr5R4IB3skx8pNhGdi@stanza.co
SUMMARY:Sky Sox vs. Storm Chasers
DESCRIPTION:Sky Sox vs. Storm Chasers\n\nFollow on MiLB First Pitch: https://stza.co/+wmwm-3S\n\nShop: https://stza.co/+wmwm-1s\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144515Z
LAST-MODIFIED:20180213T144515Z
TRANSP:OPAQUE
END:VEVENT
* Sky Sox vs. Storm Chasers
<2018-04-28 Sat 17:00-20:00>
:PROPERTIES:
:ID:       eHU4moH7FGvy0U5RJy37PNYC@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Sky Sox vs. Storm Chasers Sky Sox vs. Storm Chasers

Follow on MiLB First Pitch  https //stza.co/+wmwp-V

Shop  https //stza.co/+wmwp-1N

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Sky Sox vs. Storm Chasers
END:VALARM
DTSTART:20180428T220000Z
DTEND:20180429T010000Z
UID:eHU4moH7FGvy0U5RJy37PNYC@stanza.co
SUMMARY:Sky Sox vs. Storm Chasers
DESCRIPTION:Sky Sox vs. Storm Chasers\n\nFollow on MiLB First Pitch: https://stza.co/+wmwp-V\n\nShop: https://stza.co/+wmwp-1N\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144515Z
LAST-MODIFIED:20180213T144515Z
TRANSP:OPAQUE
END:VEVENT
* Sky Sox vs. Storm Chasers
<2018-04-29 Sun 14:00-17:00>
:PROPERTIES:
:ID:       bMyKBC4qeDMMKt6j2rqwpmKm@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Sky Sox vs. Storm Chasers Sky Sox vs. Storm Chasers

Follow on MiLB First Pitch  https //stza.co/+xKKx-3I

Shop  https //stza.co/+xKKx-3

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Sky Sox vs. Storm Chasers
END:VALARM
DTSTART:20180429T190000Z
DTEND:20180429T220000Z
UID:bMyKBC4qeDMMKt6j2rqwpmKm@stanza.co
SUMMARY:Sky Sox vs. Storm Chasers
DESCRIPTION:Sky Sox vs. Storm Chasers\n\nFollow on MiLB First Pitch: https://stza.co/+xKKx-3I\n\nShop: https://stza.co/+xKKx-3\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144515Z
LAST-MODIFIED:20180213T144515Z
TRANSP:OPAQUE
END:VEVENT
* Sky Sox vs. Sounds
<2018-04-30 Mon 19:40-22:40>
:PROPERTIES:
:ID:       8zhI4VcanJUIKx86jlpCvMlI@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Sky Sox vs. Sounds Sky Sox vs. Sounds

Follow on MiLB First Pitch  https //stza.co/+wmws-1

Shop  https //stza.co/+wmws-3M

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Sky Sox vs. Sounds
END:VALARM
DTSTART:20180501T004000Z
DTEND:20180501T034000Z
UID:8zhI4VcanJUIKx86jlpCvMlI@stanza.co
SUMMARY:Sky Sox vs. Sounds
DESCRIPTION:Sky Sox vs. Sounds\n\nFollow on MiLB First Pitch: https://stza.co/+wmws-1\n\nShop: https://stza.co/+wmws-3M\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144515Z
LAST-MODIFIED:20180213T144515Z
TRANSP:OPAQUE
END:VEVENT
* Sky Sox vs. Sounds
<2018-05-01 Tue 19:40-22:40>
:PROPERTIES:
:ID:       FAtGAbkwCKqmTKjG8P2_OY41@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Sky Sox vs. Sounds Sky Sox vs. Sounds

Follow on MiLB First Pitch  https //stza.co/+wmwu-24

Shop  https //stza.co/+wmwu-34

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Sky Sox vs. Sounds
END:VALARM
DTSTART:20180502T004000Z
DTEND:20180502T034000Z
UID:FAtGAbkwCKqmTKjG8P2_OY41@stanza.co
SUMMARY:Sky Sox vs. Sounds
DESCRIPTION:Sky Sox vs. Sounds\n\nFollow on MiLB First Pitch: https://stza.co/+wmwu-24\n\nShop: https://stza.co/+wmwu-34\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144515Z
LAST-MODIFIED:20180213T144515Z
TRANSP:OPAQUE
END:VEVENT
* Sky Sox vs. Sounds
<2018-05-02 Wed 12:05-15:05>
:PROPERTIES:
:ID:       TjgKGcq86XjRXK2VpDuMToj8@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Sky Sox vs. Sounds Sky Sox vs. Sounds

Follow on MiLB First Pitch  https //stza.co/+wmww-3h

Shop  https //stza.co/+wmww-1L

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Sky Sox vs. Sounds
END:VALARM
DTSTART:20180502T170500Z
DTEND:20180502T200500Z
UID:TjgKGcq86XjRXK2VpDuMToj8@stanza.co
SUMMARY:Sky Sox vs. Sounds
DESCRIPTION:Sky Sox vs. Sounds\n\nFollow on MiLB First Pitch: https://stza.co/+wmww-3h\n\nShop: https://stza.co/+wmww-1L\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144515Z
LAST-MODIFIED:20180213T144515Z
TRANSP:OPAQUE
END:VEVENT
* Sky Sox vs. Sounds
<2018-05-03 Thu 12:05-15:05>
:PROPERTIES:
:ID:       KlZTAJjLYznPopuHQzEY3Tp2@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Sky Sox vs. Sounds Sky Sox vs. Sounds

Follow on MiLB First Pitch  https //stza.co/+wmwz-35

Shop  https //stza.co/+wmwz-2d

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Sky Sox vs. Sounds
END:VALARM
DTSTART:20180503T170500Z
DTEND:20180503T200500Z
UID:KlZTAJjLYznPopuHQzEY3Tp2@stanza.co
SUMMARY:Sky Sox vs. Sounds
DESCRIPTION:Sky Sox vs. Sounds\n\nFollow on MiLB First Pitch: https://stza.co/+wmwz-35\n\nShop: https://stza.co/+wmwz-2d\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144515Z
LAST-MODIFIED:20180213T144515Z
TRANSP:OPAQUE
END:VEVENT
* Sky Sox @ Dodgers
<2018-05-04 Fri 19:05-22:05>
:PROPERTIES:
:ID:       Vc2aJB-Wtvgiidd_EMGRhkNQ@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Sky Sox @ Dodgers Sky Sox @ Dodgers

Follow on MiLB First Pitch  https //stza.co/+v$M5-1M

Shop  https //stza.co/+v$M5-G

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Sky Sox @ Dodgers
END:VALARM
DTSTART:20180505T000500Z
DTEND:20180505T030500Z
UID:Vc2aJB-Wtvgiidd_EMGRhkNQ@stanza.co
SUMMARY:Sky Sox @ Dodgers
DESCRIPTION:Sky Sox @ Dodgers\n\nFollow on MiLB First Pitch: https://stza.co/+v$M5-1M\n\nShop: https://stza.co/+v$M5-G\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144515Z
LAST-MODIFIED:20180213T144515Z
TRANSP:OPAQUE
END:VEVENT
* Sky Sox @ Dodgers
<2018-05-05 Sat 19:05-22:05>
:PROPERTIES:
:ID:       GP-Tyqr1WWOxSeRKdjcAJyOl@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Sky Sox @ Dodgers Sky Sox @ Dodgers

Follow on MiLB First Pitch  https //stza.co/+v$M6-V

Shop  https //stza.co/+v$M6-1L

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Sky Sox @ Dodgers
END:VALARM
DTSTART:20180506T000500Z
DTEND:20180506T030500Z
UID:GP-Tyqr1WWOxSeRKdjcAJyOl@stanza.co
SUMMARY:Sky Sox @ Dodgers
DESCRIPTION:Sky Sox @ Dodgers\n\nFollow on MiLB First Pitch: https://stza.co/+v$M6-V\n\nShop: https://stza.co/+v$M6-1L\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144515Z
LAST-MODIFIED:20180213T144515Z
TRANSP:OPAQUE
END:VEVENT
* Sky Sox @ Dodgers
<2018-05-06 Sun 14:05-17:05>
:PROPERTIES:
:ID:       LfAVZxjfvGhGb4xbHLoSHiYJ@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Sky Sox @ Dodgers Sky Sox @ Dodgers

Follow on MiLB First Pitch  https //stza.co/+v$M7-2Z

Shop  https //stza.co/+v$M7-M

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Sky Sox @ Dodgers
END:VALARM
DTSTART:20180506T190500Z
DTEND:20180506T220500Z
UID:LfAVZxjfvGhGb4xbHLoSHiYJ@stanza.co
SUMMARY:Sky Sox @ Dodgers
DESCRIPTION:Sky Sox @ Dodgers\n\nFollow on MiLB First Pitch: https://stza.co/+v$M7-2Z\n\nShop: https://stza.co/+v$M7-M\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144515Z
LAST-MODIFIED:20180213T144515Z
TRANSP:OPAQUE
END:VEVENT
* Sky Sox @ Dodgers
<2018-05-07 Mon 11:05-14:05>
:PROPERTIES:
:ID:       zE-mqJQvIKopJQX2CmDBDl5H@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Sky Sox @ Dodgers Sky Sox @ Dodgers

Follow on MiLB First Pitch  https //stza.co/+v$M8-1G

Shop  https //stza.co/+v$M8-2l

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Sky Sox @ Dodgers
END:VALARM
DTSTART:20180507T160500Z
DTEND:20180507T190500Z
UID:zE-mqJQvIKopJQX2CmDBDl5H@stanza.co
SUMMARY:Sky Sox @ Dodgers
DESCRIPTION:Sky Sox @ Dodgers\n\nFollow on MiLB First Pitch: https://stza.co/+v$M8-1G\n\nShop: https://stza.co/+v$M8-2l\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144515Z
LAST-MODIFIED:20180213T144515Z
TRANSP:OPAQUE
END:VEVENT
* Sky Sox @ Sounds
<2018-05-08 Tue 18:35-21:35>
:PROPERTIES:
:ID:       eN7ixf-9MXN1AFeT5oGMpPZx@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Sky Sox @ Sounds Sky Sox @ Sounds

Follow on MiLB First Pitch  https //stza.co/+whCf-1

Shop  https //stza.co/+whCf-36

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Sky Sox @ Sounds
END:VALARM
DTSTART:20180508T233500Z
DTEND:20180509T023500Z
UID:eN7ixf-9MXN1AFeT5oGMpPZx@stanza.co
SUMMARY:Sky Sox @ Sounds
DESCRIPTION:Sky Sox @ Sounds\n\nFollow on MiLB First Pitch: https://stza.co/+whCf-1\n\nShop: https://stza.co/+whCf-36\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144515Z
LAST-MODIFIED:20180213T144515Z
TRANSP:OPAQUE
END:VEVENT
* Sky Sox @ Sounds
<2018-05-09 Wed 18:35-21:35>
:PROPERTIES:
:ID:       wsyEenSbA41Xr5YLzYK3gWw8@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Sky Sox @ Sounds Sky Sox @ Sounds

Follow on MiLB First Pitch  https //stza.co/+whCg-2c

Shop  https //stza.co/+whCg-1G

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Sky Sox @ Sounds
END:VALARM
DTSTART:20180509T233500Z
DTEND:20180510T023500Z
UID:wsyEenSbA41Xr5YLzYK3gWw8@stanza.co
SUMMARY:Sky Sox @ Sounds
DESCRIPTION:Sky Sox @ Sounds\n\nFollow on MiLB First Pitch: https://stza.co/+whCg-2c\n\nShop: https://stza.co/+whCg-1G\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144515Z
LAST-MODIFIED:20180213T144515Z
TRANSP:OPAQUE
END:VEVENT
* Sky Sox @ Sounds
<2018-05-10 Thu 18:35-21:35>
:PROPERTIES:
:ID:       PHZAqhwwNAN20AwR7Wmq3s9n@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Sky Sox @ Sounds Sky Sox @ Sounds

Follow on MiLB First Pitch  https //stza.co/+whCh-2n

Shop  https //stza.co/+whCh-3t

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Sky Sox @ Sounds
END:VALARM
DTSTART:20180510T233500Z
DTEND:20180511T023500Z
UID:PHZAqhwwNAN20AwR7Wmq3s9n@stanza.co
SUMMARY:Sky Sox @ Sounds
DESCRIPTION:Sky Sox @ Sounds\n\nFollow on MiLB First Pitch: https://stza.co/+whCh-2n\n\nShop: https://stza.co/+whCh-3t\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144515Z
LAST-MODIFIED:20180213T144515Z
TRANSP:OPAQUE
END:VEVENT
* Sky Sox @ Sounds
<2018-05-11 Fri 18:35-21:35>
:PROPERTIES:
:ID:       q-aaFApld854WzDR-YCrt-VA@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Sky Sox @ Sounds Sky Sox @ Sounds

Follow on MiLB First Pitch  https //stza.co/+whCj-u

Shop  https //stza.co/+whCj-c

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Sky Sox @ Sounds
END:VALARM
DTSTART:20180511T233500Z
DTEND:20180512T023500Z
UID:q-aaFApld854WzDR-YCrt-VA@stanza.co
SUMMARY:Sky Sox @ Sounds
DESCRIPTION:Sky Sox @ Sounds\n\nFollow on MiLB First Pitch: https://stza.co/+whCj-u\n\nShop: https://stza.co/+whCj-c\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144515Z
LAST-MODIFIED:20180213T144515Z
TRANSP:OPAQUE
END:VEVENT
* Sky Sox vs. Dodgers
<2018-05-12 Sat 19:00-22:00>
:PROPERTIES:
:ID:       i5Gg77Ke3JFyLtP7KL6ic2j6@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Sky Sox vs. Dodgers Sky Sox vs. Dodgers

Follow on MiLB First Pitch  https //stza.co/+wmwB-2C

Shop  https //stza.co/+wmwB-1Z

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Sky Sox vs. Dodgers
END:VALARM
DTSTART:20180513T000000Z
DTEND:20180513T030000Z
UID:i5Gg77Ke3JFyLtP7KL6ic2j6@stanza.co
SUMMARY:Sky Sox vs. Dodgers
DESCRIPTION:Sky Sox vs. Dodgers\n\nFollow on MiLB First Pitch: https://stza.co/+wmwB-2C\n\nShop: https://stza.co/+wmwB-1Z\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144515Z
LAST-MODIFIED:20180213T144515Z
TRANSP:OPAQUE
END:VEVENT
* Sky Sox vs. Dodgers
<2018-05-13 Sun 14:30-17:30>
:PROPERTIES:
:ID:       ZWK-2cBihqw2DcoBneSr6llz@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Sky Sox vs. Dodgers Sky Sox vs. Dodgers

Follow on MiLB First Pitch  https //stza.co/+wmwC-3N

Shop  https //stza.co/+wmwC-3o

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Sky Sox vs. Dodgers
END:VALARM
DTSTART:20180513T193000Z
DTEND:20180513T223000Z
UID:ZWK-2cBihqw2DcoBneSr6llz@stanza.co
SUMMARY:Sky Sox vs. Dodgers
DESCRIPTION:Sky Sox vs. Dodgers\n\nFollow on MiLB First Pitch: https://stza.co/+wmwC-3N\n\nShop: https://stza.co/+wmwC-3o\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144515Z
LAST-MODIFIED:20180213T144515Z
TRANSP:OPAQUE
END:VEVENT
* Sky Sox vs. Dodgers
<2018-05-14 Mon 19:40-22:40>
:PROPERTIES:
:ID:       X4Jxdyjsr-Plku-GqVqrRUhK@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Sky Sox vs. Dodgers Sky Sox vs. Dodgers

Follow on MiLB First Pitch  https //stza.co/+wmwF-2u

Shop  https //stza.co/+wmwF-1

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Sky Sox vs. Dodgers
END:VALARM
DTSTART:20180515T004000Z
DTEND:20180515T034000Z
UID:X4Jxdyjsr-Plku-GqVqrRUhK@stanza.co
SUMMARY:Sky Sox vs. Dodgers
DESCRIPTION:Sky Sox vs. Dodgers\n\nFollow on MiLB First Pitch: https://stza.co/+wmwF-2u\n\nShop: https://stza.co/+wmwF-1\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144515Z
LAST-MODIFIED:20180213T144515Z
TRANSP:OPAQUE
END:VEVENT
* Sky Sox vs. Dodgers
<2018-05-15 Tue 19:40-22:40>
:PROPERTIES:
:ID:       _gPTG7lVOx4nmyO6S8P6-Urf@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Sky Sox vs. Dodgers Sky Sox vs. Dodgers

Follow on MiLB First Pitch  https //stza.co/+wmwI-_

Shop  https //stza.co/+wmwI-2p

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Sky Sox vs. Dodgers
END:VALARM
DTSTART:20180516T004000Z
DTEND:20180516T034000Z
UID:_gPTG7lVOx4nmyO6S8P6-Urf@stanza.co
SUMMARY:Sky Sox vs. Dodgers
DESCRIPTION:Sky Sox vs. Dodgers\n\nFollow on MiLB First Pitch: https://stza.co/+wmwI-_\n\nShop: https://stza.co/+wmwI-2p\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144515Z
LAST-MODIFIED:20180213T144515Z
TRANSP:OPAQUE
END:VEVENT
* Sky Sox vs. Redbirds
<2018-05-17 Thu 19:40-22:40>
:PROPERTIES:
:ID:       a2jKvUkgTXxYXymI2jfYnP8-@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Sky Sox vs. Redbirds Sky Sox vs. Redbirds

Follow on MiLB First Pitch  https //stza.co/+wmwK-g

Shop  https //stza.co/+wmwK-1L

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Sky Sox vs. Redbirds
END:VALARM
DTSTART:20180518T004000Z
DTEND:20180518T034000Z
UID:a2jKvUkgTXxYXymI2jfYnP8-@stanza.co
SUMMARY:Sky Sox vs. Redbirds
DESCRIPTION:Sky Sox vs. Redbirds\n\nFollow on MiLB First Pitch: https://stza.co/+wmwK-g\n\nShop: https://stza.co/+wmwK-1L\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144515Z
LAST-MODIFIED:20180213T144515Z
TRANSP:OPAQUE
END:VEVENT
* Sky Sox vs. Redbirds
<2018-05-18 Fri 19:40-22:40>
:PROPERTIES:
:ID:       JyuJv2Aep6twWnie4ESA6-yL@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Sky Sox vs. Redbirds Sky Sox vs. Redbirds

Follow on MiLB First Pitch  https //stza.co/+wmwL-1C

Shop  https //stza.co/+wmwL-31

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Sky Sox vs. Redbirds
END:VALARM
DTSTART:20180519T004000Z
DTEND:20180519T034000Z
UID:JyuJv2Aep6twWnie4ESA6-yL@stanza.co
SUMMARY:Sky Sox vs. Redbirds
DESCRIPTION:Sky Sox vs. Redbirds\n\nFollow on MiLB First Pitch: https://stza.co/+wmwL-1C\n\nShop: https://stza.co/+wmwL-31\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144515Z
LAST-MODIFIED:20180213T144515Z
TRANSP:OPAQUE
END:VEVENT
* Sky Sox vs. Redbirds
<2018-05-19 Sat 19:00-22:00>
:PROPERTIES:
:ID:       JzJH69CKKRTto4ycOROXo3bR@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Sky Sox vs. Redbirds Sky Sox vs. Redbirds

Follow on MiLB First Pitch  https //stza.co/+wmwO-1L

Shop  https //stza.co/+wmwO-2O

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Sky Sox vs. Redbirds
END:VALARM
DTSTART:20180520T000000Z
DTEND:20180520T030000Z
UID:JzJH69CKKRTto4ycOROXo3bR@stanza.co
SUMMARY:Sky Sox vs. Redbirds
DESCRIPTION:Sky Sox vs. Redbirds\n\nFollow on MiLB First Pitch: https://stza.co/+wmwO-1L\n\nShop: https://stza.co/+wmwO-2O\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144515Z
LAST-MODIFIED:20180213T144515Z
TRANSP:OPAQUE
END:VEVENT
* Sky Sox vs. Redbirds
<2018-05-20 Sun 14:00-17:00>
:PROPERTIES:
:ID:       YqioIjXuHGViL5bwmW0fcs7F@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Sky Sox vs. Redbirds Sky Sox vs. Redbirds

Follow on MiLB First Pitch  https //stza.co/+xKKy-6

Shop  https //stza.co/+xKKy-29

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Sky Sox vs. Redbirds
END:VALARM
DTSTART:20180520T190000Z
DTEND:20180520T220000Z
UID:YqioIjXuHGViL5bwmW0fcs7F@stanza.co
SUMMARY:Sky Sox vs. Redbirds
DESCRIPTION:Sky Sox vs. Redbirds\n\nFollow on MiLB First Pitch: https://stza.co/+xKKy-6\n\nShop: https://stza.co/+xKKy-29\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144515Z
LAST-MODIFIED:20180213T144515Z
TRANSP:OPAQUE
END:VEVENT
* Sky Sox @ Sounds
<2018-05-21 Mon 18:35-21:35>
:PROPERTIES:
:ID:       UDB1RklndFd8lqsI6NS8kTRw@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Sky Sox @ Sounds Sky Sox @ Sounds

Follow on MiLB First Pitch  https //stza.co/+whCk-1R

Shop  https //stza.co/+whCk-17

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Sky Sox @ Sounds
END:VALARM
DTSTART:20180521T233500Z
DTEND:20180522T023500Z
UID:UDB1RklndFd8lqsI6NS8kTRw@stanza.co
SUMMARY:Sky Sox @ Sounds
DESCRIPTION:Sky Sox @ Sounds\n\nFollow on MiLB First Pitch: https://stza.co/+whCk-1R\n\nShop: https://stza.co/+whCk-17\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144515Z
LAST-MODIFIED:20180213T144515Z
TRANSP:OPAQUE
END:VEVENT
* Sky Sox @ Sounds
<2018-05-22 Tue 18:35-21:35>
:PROPERTIES:
:ID:       XtQX3A0tXzb0_PvnOYsmzv6S@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Sky Sox @ Sounds Sky Sox @ Sounds

Follow on MiLB First Pitch  https //stza.co/+whCl-18

Shop  https //stza.co/+whCl-3z

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Sky Sox @ Sounds
END:VALARM
DTSTART:20180522T233500Z
DTEND:20180523T023500Z
UID:XtQX3A0tXzb0_PvnOYsmzv6S@stanza.co
SUMMARY:Sky Sox @ Sounds
DESCRIPTION:Sky Sox @ Sounds\n\nFollow on MiLB First Pitch: https://stza.co/+whCl-18\n\nShop: https://stza.co/+whCl-3z\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144515Z
LAST-MODIFIED:20180213T144515Z
TRANSP:OPAQUE
END:VEVENT
* Sky Sox @ Sounds
<2018-05-23 Wed 18:35-21:35>
:PROPERTIES:
:ID:       2ozuka9VplNZNyjJZBSHPXFw@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Sky Sox @ Sounds Sky Sox @ Sounds

Follow on MiLB First Pitch  https //stza.co/+whCm-1L

Shop  https //stza.co/+whCm-3C

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Sky Sox @ Sounds
END:VALARM
DTSTART:20180523T233500Z
DTEND:20180524T023500Z
UID:2ozuka9VplNZNyjJZBSHPXFw@stanza.co
SUMMARY:Sky Sox @ Sounds
DESCRIPTION:Sky Sox @ Sounds\n\nFollow on MiLB First Pitch: https://stza.co/+whCm-1L\n\nShop: https://stza.co/+whCm-3C\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144515Z
LAST-MODIFIED:20180213T144515Z
TRANSP:OPAQUE
END:VEVENT
* Sky Sox @ Sounds
<2018-05-24 Thu 18:35-21:35>
:PROPERTIES:
:ID:       uCwKAR1QFh11ndw4XED85P-9@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Sky Sox @ Sounds Sky Sox @ Sounds

Follow on MiLB First Pitch  https //stza.co/+whCn-3p

Shop  https //stza.co/+whCn-35

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Sky Sox @ Sounds
END:VALARM
DTSTART:20180524T233500Z
DTEND:20180525T023500Z
UID:uCwKAR1QFh11ndw4XED85P-9@stanza.co
SUMMARY:Sky Sox @ Sounds
DESCRIPTION:Sky Sox @ Sounds\n\nFollow on MiLB First Pitch: https://stza.co/+whCn-3p\n\nShop: https://stza.co/+whCn-35\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144515Z
LAST-MODIFIED:20180213T144515Z
TRANSP:OPAQUE
END:VEVENT
* Sky Sox @ Redbirds
<2018-05-25 Fri 19:05-22:05>
:PROPERTIES:
:ID:       4p8bFGGbMNQKDYOaDRDfhsj1@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Sky Sox @ Redbirds Sky Sox @ Redbirds

Follow on MiLB First Pitch  https //stza.co/+wmyh-1W

Shop  https //stza.co/+wmyh-3S

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Sky Sox @ Redbirds
END:VALARM
DTSTART:20180526T000500Z
DTEND:20180526T030500Z
UID:4p8bFGGbMNQKDYOaDRDfhsj1@stanza.co
SUMMARY:Sky Sox @ Redbirds
DESCRIPTION:Sky Sox @ Redbirds\n\nFollow on MiLB First Pitch: https://stza.co/+wmyh-1W\n\nShop: https://stza.co/+wmyh-3S\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144515Z
LAST-MODIFIED:20180213T144515Z
TRANSP:OPAQUE
END:VEVENT
* Sky Sox @ Redbirds
<2018-05-26 Sat 18:35-21:35>
:PROPERTIES:
:ID:       cBtXA0efn6HSG6TM_GkUkgne@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Sky Sox @ Redbirds Sky Sox @ Redbirds

Follow on MiLB First Pitch  https //stza.co/+wmyi-1b

Shop  https //stza.co/+wmyi-2V

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Sky Sox @ Redbirds
END:VALARM
DTSTART:20180526T233500Z
DTEND:20180527T023500Z
UID:cBtXA0efn6HSG6TM_GkUkgne@stanza.co
SUMMARY:Sky Sox @ Redbirds
DESCRIPTION:Sky Sox @ Redbirds\n\nFollow on MiLB First Pitch: https://stza.co/+wmyi-1b\n\nShop: https://stza.co/+wmyi-2V\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144515Z
LAST-MODIFIED:20180213T144515Z
TRANSP:OPAQUE
END:VEVENT
* Sky Sox @ Redbirds
<2018-05-27 Sun 18:35-21:35>
:PROPERTIES:
:ID:       0_uvs9DDhYmvQd_4wlU0HnuC@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Sky Sox @ Redbirds Sky Sox @ Redbirds

Follow on MiLB First Pitch  https //stza.co/+wmyj-29

Shop  https //stza.co/+wmyj-5

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Sky Sox @ Redbirds
END:VALARM
DTSTART:20180527T233500Z
DTEND:20180528T023500Z
UID:0_uvs9DDhYmvQd_4wlU0HnuC@stanza.co
SUMMARY:Sky Sox @ Redbirds
DESCRIPTION:Sky Sox @ Redbirds\n\nFollow on MiLB First Pitch: https://stza.co/+wmyj-29\n\nShop: https://stza.co/+wmyj-5\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144515Z
LAST-MODIFIED:20180213T144515Z
TRANSP:OPAQUE
END:VEVENT
* Sky Sox @ Redbirds
<2018-05-28 Mon 13:05-16:05>
:PROPERTIES:
:ID:       3Mngp2UYp3ABI-47btu2ASGq@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Sky Sox @ Redbirds Sky Sox @ Redbirds

Follow on MiLB First Pitch  https //stza.co/+wmyk-3Z

Shop  https //stza.co/+wmyk-K

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Sky Sox @ Redbirds
END:VALARM
DTSTART:20180528T180500Z
DTEND:20180528T210500Z
UID:3Mngp2UYp3ABI-47btu2ASGq@stanza.co
SUMMARY:Sky Sox @ Redbirds
DESCRIPTION:Sky Sox @ Redbirds\n\nFollow on MiLB First Pitch: https://stza.co/+wmyk-3Z\n\nShop: https://stza.co/+wmyk-K\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144515Z
LAST-MODIFIED:20180213T144515Z
TRANSP:OPAQUE
END:VEVENT
* Sky Sox @ Redbirds
<2018-05-29 Tue 12:05-15:05>
:PROPERTIES:
:ID:       L3sI-i6DDtqPabtuQy4Myh_w@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Sky Sox @ Redbirds Sky Sox @ Redbirds

Follow on MiLB First Pitch  https //stza.co/+wmyl-38

Shop  https //stza.co/+wmyl-14

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Sky Sox @ Redbirds
END:VALARM
DTSTART:20180529T170500Z
DTEND:20180529T200500Z
UID:L3sI-i6DDtqPabtuQy4Myh_w@stanza.co
SUMMARY:Sky Sox @ Redbirds
DESCRIPTION:Sky Sox @ Redbirds\n\nFollow on MiLB First Pitch: https://stza.co/+wmyl-38\n\nShop: https://stza.co/+wmyl-14\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144515Z
LAST-MODIFIED:20180213T144515Z
TRANSP:OPAQUE
END:VEVENT
* Sky Sox vs. Cubs
<2018-05-30 Wed 19:40-22:40>
:PROPERTIES:
:ID:       bHuLLmNZp3sqmXmAAjUxPh0h@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Sky Sox vs. Cubs Sky Sox vs. Cubs

Follow on MiLB First Pitch  https //stza.co/+wmwS-g

Shop  https //stza.co/+wmwS-b

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Sky Sox vs. Cubs
END:VALARM
DTSTART:20180531T004000Z
DTEND:20180531T034000Z
UID:bHuLLmNZp3sqmXmAAjUxPh0h@stanza.co
SUMMARY:Sky Sox vs. Cubs
DESCRIPTION:Sky Sox vs. Cubs\n\nFollow on MiLB First Pitch: https://stza.co/+wmwS-g\n\nShop: https://stza.co/+wmwS-b\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144515Z
LAST-MODIFIED:20180213T144515Z
TRANSP:OPAQUE
END:VEVENT
* Sky Sox vs. Cubs
<2018-05-31 Thu 19:40-22:40>
:PROPERTIES:
:ID:       4THJP_JJIRc3b5q5rX3P31BB@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Sky Sox vs. Cubs Sky Sox vs. Cubs

Follow on MiLB First Pitch  https //stza.co/+wmwU-1T

Shop  https //stza.co/+wmwU-J

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Sky Sox vs. Cubs
END:VALARM
DTSTART:20180601T004000Z
DTEND:20180601T034000Z
UID:4THJP_JJIRc3b5q5rX3P31BB@stanza.co
SUMMARY:Sky Sox vs. Cubs
DESCRIPTION:Sky Sox vs. Cubs\n\nFollow on MiLB First Pitch: https://stza.co/+wmwU-1T\n\nShop: https://stza.co/+wmwU-J\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144515Z
LAST-MODIFIED:20180213T144515Z
TRANSP:OPAQUE
END:VEVENT
* Sky Sox vs. Cubs
<2018-06-01 Fri 19:40-22:40>
:PROPERTIES:
:ID:       zQxOuYQM5BTjWuNl7uLGHarH@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Sky Sox vs. Cubs Sky Sox vs. Cubs

Follow on MiLB First Pitch  https //stza.co/+wmwW-2K

Shop  https //stza.co/+wmwW-2Q

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Sky Sox vs. Cubs
END:VALARM
DTSTART:20180602T004000Z
DTEND:20180602T034000Z
UID:zQxOuYQM5BTjWuNl7uLGHarH@stanza.co
SUMMARY:Sky Sox vs. Cubs
DESCRIPTION:Sky Sox vs. Cubs\n\nFollow on MiLB First Pitch: https://stza.co/+wmwW-2K\n\nShop: https://stza.co/+wmwW-2Q\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144515Z
LAST-MODIFIED:20180213T144515Z
TRANSP:OPAQUE
END:VEVENT
* Sky Sox vs. Cubs
<2018-06-02 Sat 19:00-22:00>
:PROPERTIES:
:ID:       cNuGyCWWoLDzBVrdJJHohWFP@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Sky Sox vs. Cubs Sky Sox vs. Cubs

Follow on MiLB First Pitch  https //stza.co/+wmwX-W

Shop  https //stza.co/+wmwX-1_

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Sky Sox vs. Cubs
END:VALARM
DTSTART:20180603T000000Z
DTEND:20180603T030000Z
UID:cNuGyCWWoLDzBVrdJJHohWFP@stanza.co
SUMMARY:Sky Sox vs. Cubs
DESCRIPTION:Sky Sox vs. Cubs\n\nFollow on MiLB First Pitch: https://stza.co/+wmwX-W\n\nShop: https://stza.co/+wmwX-1_\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144515Z
LAST-MODIFIED:20180213T144515Z
TRANSP:OPAQUE
END:VEVENT
* Sky Sox vs. Cubs
<2018-06-03 Sun 14:00-17:00>
:PROPERTIES:
:ID:       ySi87ixMKVgZvD7Gzy146ssf@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Sky Sox vs. Cubs Sky Sox vs. Cubs

Follow on MiLB First Pitch  https //stza.co/+xZT_-N

Shop  https //stza.co/+xZT_-3L

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Sky Sox vs. Cubs
END:VALARM
DTSTART:20180603T190000Z
DTEND:20180603T220000Z
UID:ySi87ixMKVgZvD7Gzy146ssf@stanza.co
SUMMARY:Sky Sox vs. Cubs
DESCRIPTION:Sky Sox vs. Cubs\n\nFollow on MiLB First Pitch: https://stza.co/+xZT_-N\n\nShop: https://stza.co/+xZT_-3L\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144515Z
LAST-MODIFIED:20180213T144515Z
TRANSP:OPAQUE
END:VEVENT
* Sky Sox @ Grizzlies
<2018-06-05 Tue 21:05>--<2018-06-06 Wed 00:05>
:PROPERTIES:
:ID:       PE_jqtaQMwBKiZIZCUXP4UFr@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Sky Sox @ Grizzlies Sky Sox @ Grizzlies

Follow on MiLB First Pitch  https //stza.co/+wjwL-29

Shop  https //stza.co/+wjwL-2z

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Sky Sox @ Grizzlies
END:VALARM
DTSTART:20180606T020500Z
DTEND:20180606T050500Z
UID:PE_jqtaQMwBKiZIZCUXP4UFr@stanza.co
SUMMARY:Sky Sox @ Grizzlies
DESCRIPTION:Sky Sox @ Grizzlies\n\nFollow on MiLB First Pitch: https://stza.co/+wjwL-29\n\nShop: https://stza.co/+wjwL-2z\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144515Z
LAST-MODIFIED:20180213T144515Z
TRANSP:OPAQUE
END:VEVENT
* Sky Sox @ Grizzlies
<2018-06-06 Wed 21:05>--<2018-06-07 Thu 00:05>
:PROPERTIES:
:ID:       mo5czWBlDIyF_mlRnmRe1Pzz@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Sky Sox @ Grizzlies Sky Sox @ Grizzlies

Follow on MiLB First Pitch  https //stza.co/+wjwM-2H

Shop  https //stza.co/+wjwM-V

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Sky Sox @ Grizzlies
END:VALARM
DTSTART:20180607T020500Z
DTEND:20180607T050500Z
UID:mo5czWBlDIyF_mlRnmRe1Pzz@stanza.co
SUMMARY:Sky Sox @ Grizzlies
DESCRIPTION:Sky Sox @ Grizzlies\n\nFollow on MiLB First Pitch: https://stza.co/+wjwM-2H\n\nShop: https://stza.co/+wjwM-V\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144515Z
LAST-MODIFIED:20180213T144515Z
TRANSP:OPAQUE
END:VEVENT
* Sky Sox @ Grizzlies
<2018-06-07 Thu 21:05>--<2018-06-08 Fri 00:05>
:PROPERTIES:
:ID:       PVPtZq_x-AK1NRUUNTll90B4@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Sky Sox @ Grizzlies Sky Sox @ Grizzlies

Follow on MiLB First Pitch  https //stza.co/+wjwN-3m

Shop  https //stza.co/+wjwN-38

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Sky Sox @ Grizzlies
END:VALARM
DTSTART:20180608T020500Z
DTEND:20180608T050500Z
UID:PVPtZq_x-AK1NRUUNTll90B4@stanza.co
SUMMARY:Sky Sox @ Grizzlies
DESCRIPTION:Sky Sox @ Grizzlies\n\nFollow on MiLB First Pitch: https://stza.co/+wjwN-3m\n\nShop: https://stza.co/+wjwN-38\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144515Z
LAST-MODIFIED:20180213T144515Z
TRANSP:OPAQUE
END:VEVENT
* Sky Sox @ River Cats
<2018-06-08 Fri 21:05>--<2018-06-09 Sat 00:05>
:PROPERTIES:
:ID:       HDoJYQ6MWMHtkLArheVzvn3M@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Sky Sox @ River Cats Sky Sox @ River Cats

Follow on MiLB First Pitch  https //stza.co/+wjwR-23

Shop  https //stza.co/+wjwR-3o

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Sky Sox @ River Cats
END:VALARM
DTSTART:20180609T020500Z
DTEND:20180609T050500Z
UID:HDoJYQ6MWMHtkLArheVzvn3M@stanza.co
SUMMARY:Sky Sox @ River Cats
DESCRIPTION:Sky Sox @ River Cats\n\nFollow on MiLB First Pitch: https://stza.co/+wjwR-23\n\nShop: https://stza.co/+wjwR-3o\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144515Z
LAST-MODIFIED:20180213T144515Z
TRANSP:OPAQUE
END:VEVENT
* Sky Sox @ River Cats
<2018-06-09 Sat 21:05>--<2018-06-10 Sun 00:05>
:PROPERTIES:
:ID:       5Ifkf9Rlo_hPuntBWFo46bLQ@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Sky Sox @ River Cats Sky Sox @ River Cats

Follow on MiLB First Pitch  https //stza.co/+wjwS-1w

Shop  https //stza.co/+wjwS-2y

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Sky Sox @ River Cats
END:VALARM
DTSTART:20180610T020500Z
DTEND:20180610T050500Z
UID:5Ifkf9Rlo_hPuntBWFo46bLQ@stanza.co
SUMMARY:Sky Sox @ River Cats
DESCRIPTION:Sky Sox @ River Cats\n\nFollow on MiLB First Pitch: https://stza.co/+wjwS-1w\n\nShop: https://stza.co/+wjwS-2y\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144515Z
LAST-MODIFIED:20180213T144515Z
TRANSP:OPAQUE
END:VEVENT
* Sky Sox @ River Cats
<2018-06-10 Sun 15:05-18:05>
:PROPERTIES:
:ID:       K-8l6HL6J7LYPXxK2ZtCMz-e@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Sky Sox @ River Cats Sky Sox @ River Cats

Follow on MiLB First Pitch  https //stza.co/+wjwT-2x

Shop  https //stza.co/+wjwT-36

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Sky Sox @ River Cats
END:VALARM
DTSTART:20180610T200500Z
DTEND:20180610T230500Z
UID:K-8l6HL6J7LYPXxK2ZtCMz-e@stanza.co
SUMMARY:Sky Sox @ River Cats
DESCRIPTION:Sky Sox @ River Cats\n\nFollow on MiLB First Pitch: https://stza.co/+wjwT-2x\n\nShop: https://stza.co/+wjwT-36\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144515Z
LAST-MODIFIED:20180213T144515Z
TRANSP:OPAQUE
END:VEVENT
* Sky Sox @ River Cats
<2018-06-11 Mon 21:05>--<2018-06-12 Tue 00:05>
:PROPERTIES:
:ID:       NImMl6A0O108sfv8X6_Adc7N@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Sky Sox @ River Cats Sky Sox @ River Cats

Follow on MiLB First Pitch  https //stza.co/+wjwU-3v

Shop  https //stza.co/+wjwU-1Q

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Sky Sox @ River Cats
END:VALARM
DTSTART:20180612T020500Z
DTEND:20180612T050500Z
UID:NImMl6A0O108sfv8X6_Adc7N@stanza.co
SUMMARY:Sky Sox @ River Cats
DESCRIPTION:Sky Sox @ River Cats\n\nFollow on MiLB First Pitch: https://stza.co/+wjwU-3v\n\nShop: https://stza.co/+wjwU-1Q\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144515Z
LAST-MODIFIED:20180213T144515Z
TRANSP:OPAQUE
END:VEVENT
* Sky Sox vs. 51s
<2018-06-13 Wed 19:40-22:40>
:PROPERTIES:
:ID:       uoT7jI25-PtjehSvvBrwwvHv@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Sky Sox vs. 51s Sky Sox vs. 51s

Follow on MiLB First Pitch  https //stza.co/+wmw$-2K

Shop  https //stza.co/+wmw$-1T

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Sky Sox vs. 51s
END:VALARM
DTSTART:20180614T004000Z
DTEND:20180614T034000Z
UID:uoT7jI25-PtjehSvvBrwwvHv@stanza.co
SUMMARY:Sky Sox vs. 51s
DESCRIPTION:Sky Sox vs. 51s\n\nFollow on MiLB First Pitch: https://stza.co/+wmw$-2K\n\nShop: https://stza.co/+wmw$-1T\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144515Z
LAST-MODIFIED:20180213T144515Z
TRANSP:OPAQUE
END:VEVENT
* Sky Sox vs. 51s
<2018-06-14 Thu 19:40-22:40>
:PROPERTIES:
:ID:       OqmUrl0f94RyJMqPSddUaHBG@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Sky Sox vs. 51s Sky Sox vs. 51s

Follow on MiLB First Pitch  https //stza.co/+wmx1-o

Shop  https //stza.co/+wmx1-2k

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Sky Sox vs. 51s
END:VALARM
DTSTART:20180615T004000Z
DTEND:20180615T034000Z
UID:OqmUrl0f94RyJMqPSddUaHBG@stanza.co
SUMMARY:Sky Sox vs. 51s
DESCRIPTION:Sky Sox vs. 51s\n\nFollow on MiLB First Pitch: https://stza.co/+wmx1-o\n\nShop: https://stza.co/+wmx1-2k\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144515Z
LAST-MODIFIED:20180213T144515Z
TRANSP:OPAQUE
END:VEVENT
* Sky Sox vs. 51s
<2018-06-15 Fri 19:40-22:40>
:PROPERTIES:
:ID:       9xzJ8AWL0psa51CAFsMybcoC@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Sky Sox vs. 51s Sky Sox vs. 51s

Follow on MiLB First Pitch  https //stza.co/+wmx3-14

Shop  https //stza.co/+wmx3-J

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Sky Sox vs. 51s
END:VALARM
DTSTART:20180616T004000Z
DTEND:20180616T034000Z
UID:9xzJ8AWL0psa51CAFsMybcoC@stanza.co
SUMMARY:Sky Sox vs. 51s
DESCRIPTION:Sky Sox vs. 51s\n\nFollow on MiLB First Pitch: https://stza.co/+wmx3-14\n\nShop: https://stza.co/+wmx3-J\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144515Z
LAST-MODIFIED:20180213T144515Z
TRANSP:OPAQUE
END:VEVENT
* Sky Sox vs. Bees
<2018-06-16 Sat 19:00-22:00>
:PROPERTIES:
:ID:       b7xulRMwMl_0rfuFT1XnwqGJ@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Sky Sox vs. Bees Sky Sox vs. Bees

Follow on MiLB First Pitch  https //stza.co/+wmx5-2R

Shop  https //stza.co/+wmx5-3Z

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Sky Sox vs. Bees
END:VALARM
DTSTART:20180617T000000Z
DTEND:20180617T030000Z
UID:b7xulRMwMl_0rfuFT1XnwqGJ@stanza.co
SUMMARY:Sky Sox vs. Bees
DESCRIPTION:Sky Sox vs. Bees\n\nFollow on MiLB First Pitch: https://stza.co/+wmx5-2R\n\nShop: https://stza.co/+wmx5-3Z\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144515Z
LAST-MODIFIED:20180213T144515Z
TRANSP:OPAQUE
END:VEVENT
* Sky Sox vs. Bees
<2018-06-17 Sun 14:30-17:30>
:PROPERTIES:
:ID:       kSfTq9UyANaPby3396aUu_ki@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Sky Sox vs. Bees Sky Sox vs. Bees

Follow on MiLB First Pitch  https //stza.co/+wmx8-35

Shop  https //stza.co/+wmx8-3s

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Sky Sox vs. Bees
END:VALARM
DTSTART:20180617T193000Z
DTEND:20180617T223000Z
UID:kSfTq9UyANaPby3396aUu_ki@stanza.co
SUMMARY:Sky Sox vs. Bees
DESCRIPTION:Sky Sox vs. Bees\n\nFollow on MiLB First Pitch: https://stza.co/+wmx8-35\n\nShop: https://stza.co/+wmx8-3s\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144515Z
LAST-MODIFIED:20180213T144515Z
TRANSP:OPAQUE
END:VEVENT
* Sky Sox vs. Bees
<2018-06-18 Mon 19:40-22:40>
:PROPERTIES:
:ID:       GNubA9QO48Gb0YI4NbZgFfUI@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Sky Sox vs. Bees Sky Sox vs. Bees

Follow on MiLB First Pitch  https //stza.co/+wmx9-1l

Shop  https //stza.co/+wmx9-1F

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Sky Sox vs. Bees
END:VALARM
DTSTART:20180619T004000Z
DTEND:20180619T034000Z
UID:GNubA9QO48Gb0YI4NbZgFfUI@stanza.co
SUMMARY:Sky Sox vs. Bees
DESCRIPTION:Sky Sox vs. Bees\n\nFollow on MiLB First Pitch: https://stza.co/+wmx9-1l\n\nShop: https://stza.co/+wmx9-1F\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144515Z
LAST-MODIFIED:20180213T144515Z
TRANSP:OPAQUE
END:VEVENT
* Sky Sox vs. Bees
<2018-06-19 Tue 19:40-22:40>
:PROPERTIES:
:ID:       Op3kjMZXcx2bMeKMmvfe5nJf@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Sky Sox vs. Bees Sky Sox vs. Bees

Follow on MiLB First Pitch  https //stza.co/+wmxc-3n

Shop  https //stza.co/+wmxc-2R

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Sky Sox vs. Bees
END:VALARM
DTSTART:20180620T004000Z
DTEND:20180620T034000Z
UID:Op3kjMZXcx2bMeKMmvfe5nJf@stanza.co
SUMMARY:Sky Sox vs. Bees
DESCRIPTION:Sky Sox vs. Bees\n\nFollow on MiLB First Pitch: https://stza.co/+wmxc-3n\n\nShop: https://stza.co/+wmxc-2R\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144515Z
LAST-MODIFIED:20180213T144515Z
TRANSP:OPAQUE
END:VEVENT
* Sky Sox @ Cubs
<2018-06-21 Thu 19:08-22:08>
:PROPERTIES:
:ID:       Xj-HLYRbW4zwdHKhFLlTBT5P@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Sky Sox @ Cubs Sky Sox @ Cubs

Follow on MiLB First Pitch  https //stza.co/+vKuP-2z

Shop  https //stza.co/+vKuP-3f

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Sky Sox @ Cubs
END:VALARM
DTSTART:20180622T000800Z
DTEND:20180622T030800Z
UID:Xj-HLYRbW4zwdHKhFLlTBT5P@stanza.co
SUMMARY:Sky Sox @ Cubs
DESCRIPTION:Sky Sox @ Cubs\n\nFollow on MiLB First Pitch: https://stza.co/+vKuP-2z\n\nShop: https://stza.co/+vKuP-3f\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144515Z
LAST-MODIFIED:20180213T144515Z
TRANSP:OPAQUE
END:VEVENT
* Sky Sox @ Cubs
<2018-06-22 Fri 19:08-22:08>
:PROPERTIES:
:ID:       DqOFRAUnTtJOVoibXFEG-K79@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Sky Sox @ Cubs Sky Sox @ Cubs

Follow on MiLB First Pitch  https //stza.co/+vKuQ-1y

Shop  https //stza.co/+vKuQ-3d

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Sky Sox @ Cubs
END:VALARM
DTSTART:20180623T000800Z
DTEND:20180623T030800Z
UID:DqOFRAUnTtJOVoibXFEG-K79@stanza.co
SUMMARY:Sky Sox @ Cubs
DESCRIPTION:Sky Sox @ Cubs\n\nFollow on MiLB First Pitch: https://stza.co/+vKuQ-1y\n\nShop: https://stza.co/+vKuQ-3d\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144515Z
LAST-MODIFIED:20180213T144515Z
TRANSP:OPAQUE
END:VEVENT
* Sky Sox @ Cubs
<2018-06-23 Sat 12:08-15:08>
:PROPERTIES:
:ID:       PZ9_OgFdLhmvMfaZjNKBIP3W@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Sky Sox @ Cubs Sky Sox @ Cubs

Follow on MiLB First Pitch  https //stza.co/+xzzm-M

Shop  https //stza.co/+xzzm-1P

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Sky Sox @ Cubs
END:VALARM
DTSTART:20180623T170800Z
DTEND:20180623T200800Z
UID:PZ9_OgFdLhmvMfaZjNKBIP3W@stanza.co
SUMMARY:Sky Sox @ Cubs
DESCRIPTION:Sky Sox @ Cubs\n\nFollow on MiLB First Pitch: https://stza.co/+xzzm-M\n\nShop: https://stza.co/+xzzm-1P\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144515Z
LAST-MODIFIED:20180213T144515Z
TRANSP:OPAQUE
END:VEVENT
* Sky Sox @ Cubs
<2018-06-23 Sat 19:08-22:08>
:PROPERTIES:
:ID:       klKsdSygA4SSmcY1h8JGwLQ-@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Sky Sox @ Cubs Sky Sox @ Cubs

Follow on MiLB First Pitch  https //stza.co/+xzzo-21

Shop  https //stza.co/+xzzo-3v

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Sky Sox @ Cubs
END:VALARM
DTSTART:20180624T000800Z
DTEND:20180624T030800Z
UID:klKsdSygA4SSmcY1h8JGwLQ-@stanza.co
SUMMARY:Sky Sox @ Cubs
DESCRIPTION:Sky Sox @ Cubs\n\nFollow on MiLB First Pitch: https://stza.co/+xzzo-21\n\nShop: https://stza.co/+xzzo-3v\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144515Z
LAST-MODIFIED:20180213T144515Z
TRANSP:OPAQUE
END:VEVENT
* Sky Sox @ Cubs
<2018-06-24 Sun 13:08-16:08>
:PROPERTIES:
:ID:       KX40Yi8n38Li3tNv-sm3xzko@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Sky Sox @ Cubs Sky Sox @ Cubs

Follow on MiLB First Pitch  https //stza.co/+vKuT-3V

Shop  https //stza.co/+vKuT-39

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Sky Sox @ Cubs
END:VALARM
DTSTART:20180624T180800Z
DTEND:20180624T210800Z
UID:KX40Yi8n38Li3tNv-sm3xzko@stanza.co
SUMMARY:Sky Sox @ Cubs
DESCRIPTION:Sky Sox @ Cubs\n\nFollow on MiLB First Pitch: https://stza.co/+vKuT-3V\n\nShop: https://stza.co/+vKuT-39\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144515Z
LAST-MODIFIED:20180213T144515Z
TRANSP:OPAQUE
END:VEVENT
* Sky Sox vs. Redbirds
<2018-06-25 Mon 19:40-22:40>
:PROPERTIES:
:ID:       7G4VMgkUJR7xPFvuiWb2uYtE@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Sky Sox vs. Redbirds Sky Sox vs. Redbirds

Follow on MiLB First Pitch  https //stza.co/+wmxd-r

Shop  https //stza.co/+wmxd-1_

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Sky Sox vs. Redbirds
END:VALARM
DTSTART:20180626T004000Z
DTEND:20180626T034000Z
UID:7G4VMgkUJR7xPFvuiWb2uYtE@stanza.co
SUMMARY:Sky Sox vs. Redbirds
DESCRIPTION:Sky Sox vs. Redbirds\n\nFollow on MiLB First Pitch: https://stza.co/+wmxd-r\n\nShop: https://stza.co/+wmxd-1_\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144515Z
LAST-MODIFIED:20180213T144515Z
TRANSP:OPAQUE
END:VEVENT
* Sky Sox vs. Redbirds
<2018-06-26 Tue 19:40-22:40>
:PROPERTIES:
:ID:       ySHYaONz9kOvLFmzeAcURNoL@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Sky Sox vs. Redbirds Sky Sox vs. Redbirds

Follow on MiLB First Pitch  https //stza.co/+wmxf-x

Shop  https //stza.co/+wmxf-1k

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Sky Sox vs. Redbirds
END:VALARM
DTSTART:20180627T004000Z
DTEND:20180627T034000Z
UID:ySHYaONz9kOvLFmzeAcURNoL@stanza.co
SUMMARY:Sky Sox vs. Redbirds
DESCRIPTION:Sky Sox vs. Redbirds\n\nFollow on MiLB First Pitch: https://stza.co/+wmxf-x\n\nShop: https://stza.co/+wmxf-1k\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144515Z
LAST-MODIFIED:20180213T144515Z
TRANSP:OPAQUE
END:VEVENT
* Sky Sox vs. Redbirds
<2018-06-27 Wed 13:30-16:30>
:PROPERTIES:
:ID:       VM-vV0wwGcbXaHBS6ZzAMtFe@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Sky Sox vs. Redbirds Sky Sox vs. Redbirds

Follow on MiLB First Pitch  https //stza.co/+wmxh-2d

Shop  https //stza.co/+wmxh-1X

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Sky Sox vs. Redbirds
END:VALARM
DTSTART:20180627T183000Z
DTEND:20180627T213000Z
UID:VM-vV0wwGcbXaHBS6ZzAMtFe@stanza.co
SUMMARY:Sky Sox vs. Redbirds
DESCRIPTION:Sky Sox vs. Redbirds\n\nFollow on MiLB First Pitch: https://stza.co/+wmxh-2d\n\nShop: https://stza.co/+wmxh-1X\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144515Z
LAST-MODIFIED:20180213T144515Z
TRANSP:OPAQUE
END:VEVENT
* Sky Sox vs. Redbirds
<2018-06-28 Thu 19:40-22:40>
:PROPERTIES:
:ID:       MlLA4nCt3xlgN2PKDwMUR8Qu@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Sky Sox vs. Redbirds Sky Sox vs. Redbirds

Follow on MiLB First Pitch  https //stza.co/+wmxj-A

Shop  https //stza.co/+wmxj-o

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Sky Sox vs. Redbirds
END:VALARM
DTSTART:20180629T004000Z
DTEND:20180629T034000Z
UID:MlLA4nCt3xlgN2PKDwMUR8Qu@stanza.co
SUMMARY:Sky Sox vs. Redbirds
DESCRIPTION:Sky Sox vs. Redbirds\n\nFollow on MiLB First Pitch: https://stza.co/+wmxj-A\n\nShop: https://stza.co/+wmxj-o\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144515Z
LAST-MODIFIED:20180213T144515Z
TRANSP:OPAQUE
END:VEVENT
* Sky Sox @ Express
<2018-06-29 Fri 19:05-22:05>
:PROPERTIES:
:ID:       mnaQy67YgCqVXr-LcfDFNp3C@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Sky Sox @ Express Sky Sox @ Express

Follow on MiLB First Pitch  https //stza.co/+vKvF-F

Shop  https //stza.co/+vKvF-2r

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Sky Sox @ Express
END:VALARM
DTSTART:20180630T000500Z
DTEND:20180630T030500Z
UID:mnaQy67YgCqVXr-LcfDFNp3C@stanza.co
SUMMARY:Sky Sox @ Express
DESCRIPTION:Sky Sox @ Express\n\nFollow on MiLB First Pitch: https://stza.co/+vKvF-F\n\nShop: https://stza.co/+vKvF-2r\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144515Z
LAST-MODIFIED:20180213T144515Z
TRANSP:OPAQUE
END:VEVENT
* Sky Sox @ Express
<2018-06-30 Sat 19:05-22:05>
:PROPERTIES:
:ID:       xYpr4Oo53FJ2GqMYTnjzN5Ag@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Sky Sox @ Express Sky Sox @ Express

Follow on MiLB First Pitch  https //stza.co/+vKvG-10

Shop  https //stza.co/+vKvG-1T

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Sky Sox @ Express
END:VALARM
DTSTART:20180701T000500Z
DTEND:20180701T030500Z
UID:xYpr4Oo53FJ2GqMYTnjzN5Ag@stanza.co
SUMMARY:Sky Sox @ Express
DESCRIPTION:Sky Sox @ Express\n\nFollow on MiLB First Pitch: https://stza.co/+vKvG-10\n\nShop: https://stza.co/+vKvG-1T\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144515Z
LAST-MODIFIED:20180213T144515Z
TRANSP:OPAQUE
END:VEVENT
* Sky Sox @ Express
<2018-07-01 Sun 18:05-21:05>
:PROPERTIES:
:ID:       Kyynm2YoY3iTQsDQhiCgvoY-@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Sky Sox @ Express Sky Sox @ Express

Follow on MiLB First Pitch  https //stza.co/+vKvH-I

Shop  https //stza.co/+vKvH-1K

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Sky Sox @ Express
END:VALARM
DTSTART:20180701T230500Z
DTEND:20180702T020500Z
UID:Kyynm2YoY3iTQsDQhiCgvoY-@stanza.co
SUMMARY:Sky Sox @ Express
DESCRIPTION:Sky Sox @ Express\n\nFollow on MiLB First Pitch: https://stza.co/+vKvH-I\n\nShop: https://stza.co/+vKvH-1K\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144515Z
LAST-MODIFIED:20180213T144515Z
TRANSP:OPAQUE
END:VEVENT
* Sky Sox @ Express
<2018-07-02 Mon 19:05-22:05>
:PROPERTIES:
:ID:       87msxCOj5zAAs7oPaqyhOt-Z@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Sky Sox @ Express Sky Sox @ Express

Follow on MiLB First Pitch  https //stza.co/+vKvI-3K

Shop  https //stza.co/+vKvI-C

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Sky Sox @ Express
END:VALARM
DTSTART:20180703T000500Z
DTEND:20180703T030500Z
UID:87msxCOj5zAAs7oPaqyhOt-Z@stanza.co
SUMMARY:Sky Sox @ Express
DESCRIPTION:Sky Sox @ Express\n\nFollow on MiLB First Pitch: https://stza.co/+vKvI-3K\n\nShop: https://stza.co/+vKvI-C\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144515Z
LAST-MODIFIED:20180213T144515Z
TRANSP:OPAQUE
END:VEVENT
* Sky Sox @ Express
<2018-07-03 Tue 19:05-22:05>
:PROPERTIES:
:ID:       bTuf5gVx6hIRdBLrOb6Qa7IZ@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Sky Sox @ Express Sky Sox @ Express

Follow on MiLB First Pitch  https //stza.co/+vKvJ-D

Shop  https //stza.co/+vKvJ-3Z

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Sky Sox @ Express
END:VALARM
DTSTART:20180704T000500Z
DTEND:20180704T030500Z
UID:bTuf5gVx6hIRdBLrOb6Qa7IZ@stanza.co
SUMMARY:Sky Sox @ Express
DESCRIPTION:Sky Sox @ Express\n\nFollow on MiLB First Pitch: https://stza.co/+vKvJ-D\n\nShop: https://stza.co/+vKvJ-3Z\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144515Z
LAST-MODIFIED:20180213T144515Z
TRANSP:OPAQUE
END:VEVENT
* Sky Sox vs. Baby Cakes
<2018-07-04 Wed 20:00-23:00>
:PROPERTIES:
:ID:       eQ_pj0RvQEOJ6gqniZ-oFVmD@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Sky Sox vs. Baby Cakes Sky Sox vs. Baby Cakes

Follow on MiLB First Pitch  https //stza.co/+wmxl-1S

Shop  https //stza.co/+wmxl-3x

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Sky Sox vs. Baby Cakes
END:VALARM
DTSTART:20180705T010000Z
DTEND:20180705T040000Z
UID:eQ_pj0RvQEOJ6gqniZ-oFVmD@stanza.co
SUMMARY:Sky Sox vs. Baby Cakes
DESCRIPTION:Sky Sox vs. Baby Cakes\n\nFollow on MiLB First Pitch: https://stza.co/+wmxl-1S\n\nShop: https://stza.co/+wmxl-3x\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144515Z
LAST-MODIFIED:20180213T144515Z
TRANSP:OPAQUE
END:VEVENT
* Sky Sox vs. Baby Cakes
<2018-07-05 Thu 19:40-22:40>
:PROPERTIES:
:ID:       vGvkIa6vBygylZpz0bwCmhs4@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Sky Sox vs. Baby Cakes Sky Sox vs. Baby Cakes

Follow on MiLB First Pitch  https //stza.co/+wmxn-26

Shop  https //stza.co/+wmxn-22

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Sky Sox vs. Baby Cakes
END:VALARM
DTSTART:20180706T004000Z
DTEND:20180706T034000Z
UID:vGvkIa6vBygylZpz0bwCmhs4@stanza.co
SUMMARY:Sky Sox vs. Baby Cakes
DESCRIPTION:Sky Sox vs. Baby Cakes\n\nFollow on MiLB First Pitch: https://stza.co/+wmxn-26\n\nShop: https://stza.co/+wmxn-22\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144515Z
LAST-MODIFIED:20180213T144515Z
TRANSP:OPAQUE
END:VEVENT
* Sky Sox vs. Baby Cakes
<2018-07-06 Fri 19:40-22:40>
:PROPERTIES:
:ID:       V53VztDHeva1z4k8kMxD2D2T@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Sky Sox vs. Baby Cakes Sky Sox vs. Baby Cakes

Follow on MiLB First Pitch  https //stza.co/+wmxq-2$

Shop  https //stza.co/+wmxq-3S

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Sky Sox vs. Baby Cakes
END:VALARM
DTSTART:20180707T004000Z
DTEND:20180707T034000Z
UID:V53VztDHeva1z4k8kMxD2D2T@stanza.co
SUMMARY:Sky Sox vs. Baby Cakes
DESCRIPTION:Sky Sox vs. Baby Cakes\n\nFollow on MiLB First Pitch: https://stza.co/+wmxq-2$\n\nShop: https://stza.co/+wmxq-3S\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144515Z
LAST-MODIFIED:20180213T144515Z
TRANSP:OPAQUE
END:VEVENT
* Sky Sox vs. Baby Cakes
<2018-07-07 Sat 19:00-22:00>
:PROPERTIES:
:ID:       W2XcjHbPKnIurOtautT0acZi@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Sky Sox vs. Baby Cakes Sky Sox vs. Baby Cakes

Follow on MiLB First Pitch  https //stza.co/+wmxs-2r

Shop  https //stza.co/+wmxs-l

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Sky Sox vs. Baby Cakes
END:VALARM
DTSTART:20180708T000000Z
DTEND:20180708T030000Z
UID:W2XcjHbPKnIurOtautT0acZi@stanza.co
SUMMARY:Sky Sox vs. Baby Cakes
DESCRIPTION:Sky Sox vs. Baby Cakes\n\nFollow on MiLB First Pitch: https://stza.co/+wmxs-2r\n\nShop: https://stza.co/+wmxs-l\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144515Z
LAST-MODIFIED:20180213T144515Z
TRANSP:OPAQUE
END:VEVENT
* Sky Sox vs. Baby Cakes
<2018-07-08 Sun 14:00-17:00>
:PROPERTIES:
:ID:       loiXOtIZE--ceLJs3rvfdxSJ@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Sky Sox vs. Baby Cakes Sky Sox vs. Baby Cakes

Follow on MiLB First Pitch  https //stza.co/+wmxu-38

Shop  https //stza.co/+wmxu-3r

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Sky Sox vs. Baby Cakes
END:VALARM
DTSTART:20180708T190000Z
DTEND:20180708T220000Z
UID:loiXOtIZE--ceLJs3rvfdxSJ@stanza.co
SUMMARY:Sky Sox vs. Baby Cakes
DESCRIPTION:Sky Sox vs. Baby Cakes\n\nFollow on MiLB First Pitch: https://stza.co/+wmxu-38\n\nShop: https://stza.co/+wmxu-3r\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144515Z
LAST-MODIFIED:20180213T144515Z
TRANSP:OPAQUE
END:VEVENT
* Sky Sox @ Baby Cakes
<2018-07-12 Thu 19:00-22:00>
:PROPERTIES:
:ID:       TAjaPAHZ2aDDdleRCzWO3KB6@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Sky Sox @ Baby Cakes Sky Sox @ Baby Cakes

Follow on MiLB First Pitch  https //stza.co/+whCs-1D

Shop  https //stza.co/+whCs-K

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Sky Sox @ Baby Cakes
END:VALARM
DTSTART:20180713T000000Z
DTEND:20180713T030000Z
UID:TAjaPAHZ2aDDdleRCzWO3KB6@stanza.co
SUMMARY:Sky Sox @ Baby Cakes
DESCRIPTION:Sky Sox @ Baby Cakes\n\nFollow on MiLB First Pitch: https://stza.co/+whCs-1D\n\nShop: https://stza.co/+whCs-K\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144515Z
LAST-MODIFIED:20180213T144515Z
TRANSP:OPAQUE
END:VEVENT
* Sky Sox @ Baby Cakes
<2018-07-13 Fri 19:00-22:00>
:PROPERTIES:
:ID:       mOVsxMlC05AlvXJbYZ-Ltvko@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Sky Sox @ Baby Cakes Sky Sox @ Baby Cakes

Follow on MiLB First Pitch  https //stza.co/+whCt-3f

Shop  https //stza.co/+whCt-3v

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Sky Sox @ Baby Cakes
END:VALARM
DTSTART:20180714T000000Z
DTEND:20180714T030000Z
UID:mOVsxMlC05AlvXJbYZ-Ltvko@stanza.co
SUMMARY:Sky Sox @ Baby Cakes
DESCRIPTION:Sky Sox @ Baby Cakes\n\nFollow on MiLB First Pitch: https://stza.co/+whCt-3f\n\nShop: https://stza.co/+whCt-3v\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144515Z
LAST-MODIFIED:20180213T144515Z
TRANSP:OPAQUE
END:VEVENT
* Sky Sox @ Baby Cakes
<2018-07-14 Sat 18:00-21:00>
:PROPERTIES:
:ID:       ijF7YkIys2wHto8EMU7LuBc3@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Sky Sox @ Baby Cakes Sky Sox @ Baby Cakes

Follow on MiLB First Pitch  https //stza.co/+whCu-1r

Shop  https //stza.co/+whCu-a

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Sky Sox @ Baby Cakes
END:VALARM
DTSTART:20180714T230000Z
DTEND:20180715T020000Z
UID:ijF7YkIys2wHto8EMU7LuBc3@stanza.co
SUMMARY:Sky Sox @ Baby Cakes
DESCRIPTION:Sky Sox @ Baby Cakes\n\nFollow on MiLB First Pitch: https://stza.co/+whCu-1r\n\nShop: https://stza.co/+whCu-a\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144515Z
LAST-MODIFIED:20180213T144515Z
TRANSP:OPAQUE
END:VEVENT
* Sky Sox @ Baby Cakes
<2018-07-15 Sun 13:00-16:00>
:PROPERTIES:
:ID:       6AUOl7w8X5YgIbBPLIKICRiG@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Sky Sox @ Baby Cakes Sky Sox @ Baby Cakes

Follow on MiLB First Pitch  https //stza.co/+whCv-3q

Shop  https //stza.co/+whCv-a

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Sky Sox @ Baby Cakes
END:VALARM
DTSTART:20180715T180000Z
DTEND:20180715T210000Z
UID:6AUOl7w8X5YgIbBPLIKICRiG@stanza.co
SUMMARY:Sky Sox @ Baby Cakes
DESCRIPTION:Sky Sox @ Baby Cakes\n\nFollow on MiLB First Pitch: https://stza.co/+whCv-3q\n\nShop: https://stza.co/+whCv-a\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144515Z
LAST-MODIFIED:20180213T144515Z
TRANSP:OPAQUE
END:VEVENT
* Sky Sox vs. Express
<2018-07-16 Mon 19:40-22:40>
:PROPERTIES:
:ID:       f84ev7RE00D6OawozjL1sr81@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Sky Sox vs. Express Sky Sox vs. Express

Follow on MiLB First Pitch  https //stza.co/+wmxw-G

Shop  https //stza.co/+wmxw-2l

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Sky Sox vs. Express
END:VALARM
DTSTART:20180717T004000Z
DTEND:20180717T034000Z
UID:f84ev7RE00D6OawozjL1sr81@stanza.co
SUMMARY:Sky Sox vs. Express
DESCRIPTION:Sky Sox vs. Express\n\nFollow on MiLB First Pitch: https://stza.co/+wmxw-G\n\nShop: https://stza.co/+wmxw-2l\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144515Z
LAST-MODIFIED:20180213T144515Z
TRANSP:OPAQUE
END:VEVENT
* Sky Sox vs. Express
<2018-07-17 Tue 19:40-22:40>
:PROPERTIES:
:ID:       dKrGalOVTAjifLY1nxKoiPbC@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Sky Sox vs. Express Sky Sox vs. Express

Follow on MiLB First Pitch  https //stza.co/+wmxy-1n

Shop  https //stza.co/+wmxy-W

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Sky Sox vs. Express
END:VALARM
DTSTART:20180718T004000Z
DTEND:20180718T034000Z
UID:dKrGalOVTAjifLY1nxKoiPbC@stanza.co
SUMMARY:Sky Sox vs. Express
DESCRIPTION:Sky Sox vs. Express\n\nFollow on MiLB First Pitch: https://stza.co/+wmxy-1n\n\nShop: https://stza.co/+wmxy-W\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144515Z
LAST-MODIFIED:20180213T144515Z
TRANSP:OPAQUE
END:VEVENT
* Sky Sox vs. Express
<2018-07-18 Wed 19:40-22:40>
:PROPERTIES:
:ID:       Xb-BjYmPgZZTj5K1HSWqfe8p@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Sky Sox vs. Express Sky Sox vs. Express

Follow on MiLB First Pitch  https //stza.co/+wmxA-v

Shop  https //stza.co/+wmxA-3o

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Sky Sox vs. Express
END:VALARM
DTSTART:20180719T004000Z
DTEND:20180719T034000Z
UID:Xb-BjYmPgZZTj5K1HSWqfe8p@stanza.co
SUMMARY:Sky Sox vs. Express
DESCRIPTION:Sky Sox vs. Express\n\nFollow on MiLB First Pitch: https://stza.co/+wmxA-v\n\nShop: https://stza.co/+wmxA-3o\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144515Z
LAST-MODIFIED:20180213T144515Z
TRANSP:OPAQUE
END:VEVENT
* Sky Sox vs. Express
<2018-07-19 Thu 19:40-22:40>
:PROPERTIES:
:ID:       2QVGuHcXkPSKSZfOjDMv5gxG@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Sky Sox vs. Express Sky Sox vs. Express

Follow on MiLB First Pitch  https //stza.co/+wmxC-1D

Shop  https //stza.co/+wmxC-14

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Sky Sox vs. Express
END:VALARM
DTSTART:20180720T004000Z
DTEND:20180720T034000Z
UID:2QVGuHcXkPSKSZfOjDMv5gxG@stanza.co
SUMMARY:Sky Sox vs. Express
DESCRIPTION:Sky Sox vs. Express\n\nFollow on MiLB First Pitch: https://stza.co/+wmxC-1D\n\nShop: https://stza.co/+wmxC-14\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144515Z
LAST-MODIFIED:20180213T144515Z
TRANSP:OPAQUE
END:VEVENT
* Sky Sox @ Redbirds
<2018-07-20 Fri 19:05-22:05>
:PROPERTIES:
:ID:       FKdbWrK4xxc2xXHxE6OQ261v@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Sky Sox @ Redbirds Sky Sox @ Redbirds

Follow on MiLB First Pitch  https //stza.co/+wmym-1L

Shop  https //stza.co/+wmym-W

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Sky Sox @ Redbirds
END:VALARM
DTSTART:20180721T000500Z
DTEND:20180721T030500Z
UID:FKdbWrK4xxc2xXHxE6OQ261v@stanza.co
SUMMARY:Sky Sox @ Redbirds
DESCRIPTION:Sky Sox @ Redbirds\n\nFollow on MiLB First Pitch: https://stza.co/+wmym-1L\n\nShop: https://stza.co/+wmym-W\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144515Z
LAST-MODIFIED:20180213T144515Z
TRANSP:OPAQUE
END:VEVENT
* Sky Sox @ Redbirds
<2018-07-21 Sat 18:35-21:35>
:PROPERTIES:
:ID:       WeD40ZS-TKRDracSTSzi-SIs@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Sky Sox @ Redbirds Sky Sox @ Redbirds

Follow on MiLB First Pitch  https //stza.co/+wmyn-1s

Shop  https //stza.co/+wmyn-2p

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Sky Sox @ Redbirds
END:VALARM
DTSTART:20180721T233500Z
DTEND:20180722T023500Z
UID:WeD40ZS-TKRDracSTSzi-SIs@stanza.co
SUMMARY:Sky Sox @ Redbirds
DESCRIPTION:Sky Sox @ Redbirds\n\nFollow on MiLB First Pitch: https://stza.co/+wmyn-1s\n\nShop: https://stza.co/+wmyn-2p\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144515Z
LAST-MODIFIED:20180213T144515Z
TRANSP:OPAQUE
END:VEVENT
* Sky Sox @ Redbirds
<2018-07-22 Sun 14:05-17:05>
:PROPERTIES:
:ID:       vpehA_Bf0fNkxZwTnbWqVV8A@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Sky Sox @ Redbirds Sky Sox @ Redbirds

Follow on MiLB First Pitch  https //stza.co/+wmyo-U

Shop  https //stza.co/+wmyo-1X

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Sky Sox @ Redbirds
END:VALARM
DTSTART:20180722T190500Z
DTEND:20180722T220500Z
UID:vpehA_Bf0fNkxZwTnbWqVV8A@stanza.co
SUMMARY:Sky Sox @ Redbirds
DESCRIPTION:Sky Sox @ Redbirds\n\nFollow on MiLB First Pitch: https://stza.co/+wmyo-U\n\nShop: https://stza.co/+wmyo-1X\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144515Z
LAST-MODIFIED:20180213T144515Z
TRANSP:OPAQUE
END:VEVENT
* Sky Sox vs. Chihuahuas
<2018-07-24 Tue 19:40-22:40>
:PROPERTIES:
:ID:       iU6Rv7tQN4OR6bfMGxuv8RM6@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Sky Sox vs. Chihuahuas Sky Sox vs. Chihuahuas

Follow on MiLB First Pitch  https //stza.co/+wmxD-1h

Shop  https //stza.co/+wmxD-3a

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Sky Sox vs. Chihuahuas
END:VALARM
DTSTART:20180725T004000Z
DTEND:20180725T034000Z
UID:iU6Rv7tQN4OR6bfMGxuv8RM6@stanza.co
SUMMARY:Sky Sox vs. Chihuahuas
DESCRIPTION:Sky Sox vs. Chihuahuas\n\nFollow on MiLB First Pitch: https://stza.co/+wmxD-1h\n\nShop: https://stza.co/+wmxD-3a\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144515Z
LAST-MODIFIED:20180213T144515Z
TRANSP:OPAQUE
END:VEVENT
* Sky Sox vs. Chihuahuas
<2018-07-25 Wed 13:30-16:30>
:PROPERTIES:
:ID:       7xMmwETrVaz7oiMfsgv8VVTi@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Sky Sox vs. Chihuahuas Sky Sox vs. Chihuahuas

Follow on MiLB First Pitch  https //stza.co/+wmxG-3s

Shop  https //stza.co/+wmxG-3e

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Sky Sox vs. Chihuahuas
END:VALARM
DTSTART:20180725T183000Z
DTEND:20180725T213000Z
UID:7xMmwETrVaz7oiMfsgv8VVTi@stanza.co
SUMMARY:Sky Sox vs. Chihuahuas
DESCRIPTION:Sky Sox vs. Chihuahuas\n\nFollow on MiLB First Pitch: https://stza.co/+wmxG-3s\n\nShop: https://stza.co/+wmxG-3e\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144515Z
LAST-MODIFIED:20180213T144515Z
TRANSP:OPAQUE
END:VEVENT
* Sky Sox vs. Chihuahuas
<2018-07-26 Thu 19:40-22:40>
:PROPERTIES:
:ID:       IevW7wL0WGG311R0fOGiQ2p0@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Sky Sox vs. Chihuahuas Sky Sox vs. Chihuahuas

Follow on MiLB First Pitch  https //stza.co/+wmxI-2R

Shop  https //stza.co/+wmxI-2v

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Sky Sox vs. Chihuahuas
END:VALARM
DTSTART:20180727T004000Z
DTEND:20180727T034000Z
UID:IevW7wL0WGG311R0fOGiQ2p0@stanza.co
SUMMARY:Sky Sox vs. Chihuahuas
DESCRIPTION:Sky Sox vs. Chihuahuas\n\nFollow on MiLB First Pitch: https://stza.co/+wmxI-2R\n\nShop: https://stza.co/+wmxI-2v\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144515Z
LAST-MODIFIED:20180213T144515Z
TRANSP:OPAQUE
END:VEVENT
* Sky Sox vs. Isotopes
<2018-07-27 Fri 19:40-22:40>
:PROPERTIES:
:ID:       Brvncoq2bXxLgWrBBi8jZhSE@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Sky Sox vs. Isotopes Sky Sox vs. Isotopes

Follow on MiLB First Pitch  https //stza.co/+wmxK-1o

Shop  https //stza.co/+wmxK-2o

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Sky Sox vs. Isotopes
END:VALARM
DTSTART:20180728T004000Z
DTEND:20180728T034000Z
UID:Brvncoq2bXxLgWrBBi8jZhSE@stanza.co
SUMMARY:Sky Sox vs. Isotopes
DESCRIPTION:Sky Sox vs. Isotopes\n\nFollow on MiLB First Pitch: https://stza.co/+wmxK-1o\n\nShop: https://stza.co/+wmxK-2o\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144515Z
LAST-MODIFIED:20180213T144515Z
TRANSP:OPAQUE
END:VEVENT
* Sky Sox vs. Isotopes
<2018-07-28 Sat 19:00-22:00>
:PROPERTIES:
:ID:       uzffIpXlSEqqpUn7EQkbw_l1@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Sky Sox vs. Isotopes Sky Sox vs. Isotopes

Follow on MiLB First Pitch  https //stza.co/+wmxL-I

Shop  https //stza.co/+wmxL-32

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Sky Sox vs. Isotopes
END:VALARM
DTSTART:20180729T000000Z
DTEND:20180729T030000Z
UID:uzffIpXlSEqqpUn7EQkbw_l1@stanza.co
SUMMARY:Sky Sox vs. Isotopes
DESCRIPTION:Sky Sox vs. Isotopes\n\nFollow on MiLB First Pitch: https://stza.co/+wmxL-I\n\nShop: https://stza.co/+wmxL-32\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144515Z
LAST-MODIFIED:20180213T144515Z
TRANSP:OPAQUE
END:VEVENT
* Sky Sox vs. Isotopes
<2018-07-29 Sun 14:30-17:30>
:PROPERTIES:
:ID:       Wnk5CWWmgFo0ZO3Klo9yT2M6@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Sky Sox vs. Isotopes Sky Sox vs. Isotopes

Follow on MiLB First Pitch  https //stza.co/+wmxO-9

Shop  https //stza.co/+wmxO-38

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Sky Sox vs. Isotopes
END:VALARM
DTSTART:20180729T193000Z
DTEND:20180729T223000Z
UID:Wnk5CWWmgFo0ZO3Klo9yT2M6@stanza.co
SUMMARY:Sky Sox vs. Isotopes
DESCRIPTION:Sky Sox vs. Isotopes\n\nFollow on MiLB First Pitch: https://stza.co/+wmxO-9\n\nShop: https://stza.co/+wmxO-38\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144515Z
LAST-MODIFIED:20180213T144515Z
TRANSP:OPAQUE
END:VEVENT
* Sky Sox vs. Isotopes
<2018-07-30 Mon 19:40-22:40>
:PROPERTIES:
:ID:       TgfVcjxcI9Cku4ox5xXKq5cw@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Sky Sox vs. Isotopes Sky Sox vs. Isotopes

Follow on MiLB First Pitch  https //stza.co/+wmxP-1Q

Shop  https //stza.co/+wmxP-1J

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Sky Sox vs. Isotopes
END:VALARM
DTSTART:20180731T004000Z
DTEND:20180731T034000Z
UID:TgfVcjxcI9Cku4ox5xXKq5cw@stanza.co
SUMMARY:Sky Sox vs. Isotopes
DESCRIPTION:Sky Sox vs. Isotopes\n\nFollow on MiLB First Pitch: https://stza.co/+wmxP-1Q\n\nShop: https://stza.co/+wmxP-1J\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144515Z
LAST-MODIFIED:20180213T144515Z
TRANSP:OPAQUE
END:VEVENT
* Sky Sox @ Aces
<2018-08-01 Wed 21:05>--<2018-08-02 Thu 00:05>
:PROPERTIES:
:ID:       UGf3jmXmaJhnA7bECOZjOheK@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Sky Sox @ Aces Sky Sox @ Aces

Follow on MiLB First Pitch  https //stza.co/+wjwO-2a

Shop  https //stza.co/+wjwO-27

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Sky Sox @ Aces
END:VALARM
DTSTART:20180802T020500Z
DTEND:20180802T050500Z
UID:UGf3jmXmaJhnA7bECOZjOheK@stanza.co
SUMMARY:Sky Sox @ Aces
DESCRIPTION:Sky Sox @ Aces\n\nFollow on MiLB First Pitch: https://stza.co/+wjwO-2a\n\nShop: https://stza.co/+wjwO-27\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144515Z
LAST-MODIFIED:20180213T144515Z
TRANSP:OPAQUE
END:VEVENT
* Sky Sox @ Aces
<2018-08-02 Thu 21:05>--<2018-08-03 Fri 00:05>
:PROPERTIES:
:ID:       csy1u_1eNt4HY2_3tscuKBe8@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Sky Sox @ Aces Sky Sox @ Aces

Follow on MiLB First Pitch  https //stza.co/+wjwP-2$

Shop  https //stza.co/+wjwP-1G

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Sky Sox @ Aces
END:VALARM
DTSTART:20180803T020500Z
DTEND:20180803T050500Z
UID:csy1u_1eNt4HY2_3tscuKBe8@stanza.co
SUMMARY:Sky Sox @ Aces
DESCRIPTION:Sky Sox @ Aces\n\nFollow on MiLB First Pitch: https://stza.co/+wjwP-2$\n\nShop: https://stza.co/+wjwP-1G\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144515Z
LAST-MODIFIED:20180213T144515Z
TRANSP:OPAQUE
END:VEVENT
* Sky Sox @ Aces
<2018-08-03 Fri 21:05>--<2018-08-04 Sat 00:05>
:PROPERTIES:
:ID:       lMVXFNLf5dTn_tm60sk3I16X@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Sky Sox @ Aces Sky Sox @ Aces

Follow on MiLB First Pitch  https //stza.co/+wjwQ-2z

Shop  https //stza.co/+wjwQ-z

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Sky Sox @ Aces
END:VALARM
DTSTART:20180804T020500Z
DTEND:20180804T050500Z
UID:lMVXFNLf5dTn_tm60sk3I16X@stanza.co
SUMMARY:Sky Sox @ Aces
DESCRIPTION:Sky Sox @ Aces\n\nFollow on MiLB First Pitch: https://stza.co/+wjwQ-2z\n\nShop: https://stza.co/+wjwQ-z\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144515Z
LAST-MODIFIED:20180213T144515Z
TRANSP:OPAQUE
END:VEVENT
* Sky Sox @ Rainiers
<2018-08-04 Sat 21:05>--<2018-08-05 Sun 00:05>
:PROPERTIES:
:ID:       WcQczpMJoeqUH4EoGOeZyarQ@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Sky Sox @ Rainiers Sky Sox @ Rainiers

Follow on MiLB First Pitch  https //stza.co/+wjwW-2d

Shop  https //stza.co/+wjwW-3v

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Sky Sox @ Rainiers
END:VALARM
DTSTART:20180805T020500Z
DTEND:20180805T050500Z
UID:WcQczpMJoeqUH4EoGOeZyarQ@stanza.co
SUMMARY:Sky Sox @ Rainiers
DESCRIPTION:Sky Sox @ Rainiers\n\nFollow on MiLB First Pitch: https://stza.co/+wjwW-2d\n\nShop: https://stza.co/+wjwW-3v\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144515Z
LAST-MODIFIED:20180213T144515Z
TRANSP:OPAQUE
END:VEVENT
* Sky Sox @ Rainiers
<2018-08-05 Sun 15:35-18:35>
:PROPERTIES:
:ID:       KZGhcm9Uw2tdcxIEow7RYgh-@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Sky Sox @ Rainiers Sky Sox @ Rainiers

Follow on MiLB First Pitch  https //stza.co/+wjwX-2T

Shop  https //stza.co/+wjwX-2b

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Sky Sox @ Rainiers
END:VALARM
DTSTART:20180805T203500Z
DTEND:20180805T233500Z
UID:KZGhcm9Uw2tdcxIEow7RYgh-@stanza.co
SUMMARY:Sky Sox @ Rainiers
DESCRIPTION:Sky Sox @ Rainiers\n\nFollow on MiLB First Pitch: https://stza.co/+wjwX-2T\n\nShop: https://stza.co/+wjwX-2b\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144515Z
LAST-MODIFIED:20180213T144515Z
TRANSP:OPAQUE
END:VEVENT
* Sky Sox @ Rainiers
<2018-08-06 Mon 21:05>--<2018-08-07 Tue 00:05>
:PROPERTIES:
:ID:       2JNqxLT5ZFYk4YLKaWqHgU-e@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Sky Sox @ Rainiers Sky Sox @ Rainiers

Follow on MiLB First Pitch  https //stza.co/+wjwY-3J

Shop  https //stza.co/+wjwY-1o

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Sky Sox @ Rainiers
END:VALARM
DTSTART:20180807T020500Z
DTEND:20180807T050500Z
UID:2JNqxLT5ZFYk4YLKaWqHgU-e@stanza.co
SUMMARY:Sky Sox @ Rainiers
DESCRIPTION:Sky Sox @ Rainiers\n\nFollow on MiLB First Pitch: https://stza.co/+wjwY-3J\n\nShop: https://stza.co/+wjwY-1o\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144515Z
LAST-MODIFIED:20180213T144515Z
TRANSP:OPAQUE
END:VEVENT
* Sky Sox @ Rainiers
<2018-08-07 Tue 13:35-16:35>
:PROPERTIES:
:ID:       enoDhe1vZssHs_JFq3S4fdGP@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Sky Sox @ Rainiers Sky Sox @ Rainiers

Follow on MiLB First Pitch  https //stza.co/+wjwZ-1I

Shop  https //stza.co/+wjwZ-1S

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Sky Sox @ Rainiers
END:VALARM
DTSTART:20180807T183500Z
DTEND:20180807T213500Z
UID:enoDhe1vZssHs_JFq3S4fdGP@stanza.co
SUMMARY:Sky Sox @ Rainiers
DESCRIPTION:Sky Sox @ Rainiers\n\nFollow on MiLB First Pitch: https://stza.co/+wjwZ-1I\n\nShop: https://stza.co/+wjwZ-1S\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144515Z
LAST-MODIFIED:20180213T144515Z
TRANSP:OPAQUE
END:VEVENT
* Sky Sox vs. Sounds
<2018-08-09 Thu 19:40-22:40>
:PROPERTIES:
:ID:       r44YwRaU-464WPlulKZeF1iU@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Sky Sox vs. Sounds Sky Sox vs. Sounds

Follow on MiLB First Pitch  https //stza.co/+wmxS-2a

Shop  https //stza.co/+wmxS-2Q

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Sky Sox vs. Sounds
END:VALARM
DTSTART:20180810T004000Z
DTEND:20180810T034000Z
UID:r44YwRaU-464WPlulKZeF1iU@stanza.co
SUMMARY:Sky Sox vs. Sounds
DESCRIPTION:Sky Sox vs. Sounds\n\nFollow on MiLB First Pitch: https://stza.co/+wmxS-2a\n\nShop: https://stza.co/+wmxS-2Q\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144515Z
LAST-MODIFIED:20180213T144515Z
TRANSP:OPAQUE
END:VEVENT
* Sky Sox vs. Sounds
<2018-08-10 Fri 19:40-22:40>
:PROPERTIES:
:ID:       KLM8mPTRbGk5YkOMbY5wmQEb@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Sky Sox vs. Sounds Sky Sox vs. Sounds

Follow on MiLB First Pitch  https //stza.co/+wmxT-N

Shop  https //stza.co/+wmxT-1i

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Sky Sox vs. Sounds
END:VALARM
DTSTART:20180811T004000Z
DTEND:20180811T034000Z
UID:KLM8mPTRbGk5YkOMbY5wmQEb@stanza.co
SUMMARY:Sky Sox vs. Sounds
DESCRIPTION:Sky Sox vs. Sounds\n\nFollow on MiLB First Pitch: https://stza.co/+wmxT-N\n\nShop: https://stza.co/+wmxT-1i\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144515Z
LAST-MODIFIED:20180213T144515Z
TRANSP:OPAQUE
END:VEVENT
* Sky Sox vs. Sounds
<2018-08-11 Sat 19:00-22:00>
:PROPERTIES:
:ID:       mt8dLqcGVlu7WX-hrRYsqPYy@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Sky Sox vs. Sounds Sky Sox vs. Sounds

Follow on MiLB First Pitch  https //stza.co/+wmxV-3h

Shop  https //stza.co/+wmxV-2f

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Sky Sox vs. Sounds
END:VALARM
DTSTART:20180812T000000Z
DTEND:20180812T030000Z
UID:mt8dLqcGVlu7WX-hrRYsqPYy@stanza.co
SUMMARY:Sky Sox vs. Sounds
DESCRIPTION:Sky Sox vs. Sounds\n\nFollow on MiLB First Pitch: https://stza.co/+wmxV-3h\n\nShop: https://stza.co/+wmxV-2f\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144515Z
LAST-MODIFIED:20180213T144515Z
TRANSP:OPAQUE
END:VEVENT
* Sky Sox vs. Sounds
<2018-08-12 Sun 14:30-17:30>
:PROPERTIES:
:ID:       FSOAJufnnPn2pCMGJ3c5p88K@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Sky Sox vs. Sounds Sky Sox vs. Sounds

Follow on MiLB First Pitch  https //stza.co/+wmxY-3I

Shop  https //stza.co/+wmxY-30

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Sky Sox vs. Sounds
END:VALARM
DTSTART:20180812T193000Z
DTEND:20180812T223000Z
UID:FSOAJufnnPn2pCMGJ3c5p88K@stanza.co
SUMMARY:Sky Sox vs. Sounds
DESCRIPTION:Sky Sox vs. Sounds\n\nFollow on MiLB First Pitch: https://stza.co/+wmxY-3I\n\nShop: https://stza.co/+wmxY-30\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144515Z
LAST-MODIFIED:20180213T144515Z
TRANSP:OPAQUE
END:VEVENT
* Sky Sox @ Cubs
<2018-08-14 Tue 19:08-22:08>
:PROPERTIES:
:ID:       acic670RwYMLWCuRfolzBBOc@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Sky Sox @ Cubs Sky Sox @ Cubs

Follow on MiLB First Pitch  https //stza.co/+vKuU-3C

Shop  https //stza.co/+vKuU-2j

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Sky Sox @ Cubs
END:VALARM
DTSTART:20180815T000800Z
DTEND:20180815T030800Z
UID:acic670RwYMLWCuRfolzBBOc@stanza.co
SUMMARY:Sky Sox @ Cubs
DESCRIPTION:Sky Sox @ Cubs\n\nFollow on MiLB First Pitch: https://stza.co/+vKuU-3C\n\nShop: https://stza.co/+vKuU-2j\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144515Z
LAST-MODIFIED:20180213T144515Z
TRANSP:OPAQUE
END:VEVENT
* Sky Sox @ Cubs
<2018-08-15 Wed 19:08-22:08>
:PROPERTIES:
:ID:       LA1mmhRsbduW-zTa-j1pqHCo@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Sky Sox @ Cubs Sky Sox @ Cubs

Follow on MiLB First Pitch  https //stza.co/+vKuV-1Q

Shop  https //stza.co/+vKuV-l

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Sky Sox @ Cubs
END:VALARM
DTSTART:20180816T000800Z
DTEND:20180816T030800Z
UID:LA1mmhRsbduW-zTa-j1pqHCo@stanza.co
SUMMARY:Sky Sox @ Cubs
DESCRIPTION:Sky Sox @ Cubs\n\nFollow on MiLB First Pitch: https://stza.co/+vKuV-1Q\n\nShop: https://stza.co/+vKuV-l\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144515Z
LAST-MODIFIED:20180213T144515Z
TRANSP:OPAQUE
END:VEVENT
* Sky Sox @ Cubs
<2018-08-16 Thu 12:08-15:08>
:PROPERTIES:
:ID:       X8Afp7GC3RHurWv2tNiE89Uq@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Sky Sox @ Cubs Sky Sox @ Cubs

Follow on MiLB First Pitch  https //stza.co/+vKuW-2b

Shop  https //stza.co/+vKuW-3D

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Sky Sox @ Cubs
END:VALARM
DTSTART:20180816T170800Z
DTEND:20180816T200800Z
UID:X8Afp7GC3RHurWv2tNiE89Uq@stanza.co
SUMMARY:Sky Sox @ Cubs
DESCRIPTION:Sky Sox @ Cubs\n\nFollow on MiLB First Pitch: https://stza.co/+vKuW-2b\n\nShop: https://stza.co/+vKuW-3D\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144515Z
LAST-MODIFIED:20180213T144515Z
TRANSP:OPAQUE
END:VEVENT
* Sky Sox vs. Storm Chasers
<2018-08-17 Fri 19:40-22:40>
:PROPERTIES:
:ID:       NP2TEunL1hB6fD8rqU8T66vE@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Sky Sox vs. Storm Chasers Sky Sox vs. Storm Chasers

Follow on MiLB First Pitch  https //stza.co/+wmx_-3c

Shop  https //stza.co/+wmx_-3K

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Sky Sox vs. Storm Chasers
END:VALARM
DTSTART:20180818T004000Z
DTEND:20180818T034000Z
UID:NP2TEunL1hB6fD8rqU8T66vE@stanza.co
SUMMARY:Sky Sox vs. Storm Chasers
DESCRIPTION:Sky Sox vs. Storm Chasers\n\nFollow on MiLB First Pitch: https://stza.co/+wmx_-3c\n\nShop: https://stza.co/+wmx_-3K\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144515Z
LAST-MODIFIED:20180213T144515Z
TRANSP:OPAQUE
END:VEVENT
* Sky Sox vs. Storm Chasers
<2018-08-18 Sat 19:00-22:00>
:PROPERTIES:
:ID:       fxUPlxtkM7eNn9h55xF0it0e@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Sky Sox vs. Storm Chasers Sky Sox vs. Storm Chasers

Follow on MiLB First Pitch  https //stza.co/+wmy0-2p

Shop  https //stza.co/+wmy0-31

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Sky Sox vs. Storm Chasers
END:VALARM
DTSTART:20180819T000000Z
DTEND:20180819T030000Z
UID:fxUPlxtkM7eNn9h55xF0it0e@stanza.co
SUMMARY:Sky Sox vs. Storm Chasers
DESCRIPTION:Sky Sox vs. Storm Chasers\n\nFollow on MiLB First Pitch: https://stza.co/+wmy0-2p\n\nShop: https://stza.co/+wmy0-31\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144515Z
LAST-MODIFIED:20180213T144515Z
TRANSP:OPAQUE
END:VEVENT
* Sky Sox vs. Storm Chasers
<2018-08-19 Sun 14:30-17:30>
:PROPERTIES:
:ID:       PPIbTXtSaCXMet0WFUKldfAu@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Sky Sox vs. Storm Chasers Sky Sox vs. Storm Chasers

Follow on MiLB First Pitch  https //stza.co/+wmy2-2L

Shop  https //stza.co/+wmy2-33

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Sky Sox vs. Storm Chasers
END:VALARM
DTSTART:20180819T193000Z
DTEND:20180819T223000Z
UID:PPIbTXtSaCXMet0WFUKldfAu@stanza.co
SUMMARY:Sky Sox vs. Storm Chasers
DESCRIPTION:Sky Sox vs. Storm Chasers\n\nFollow on MiLB First Pitch: https://stza.co/+wmy2-2L\n\nShop: https://stza.co/+wmy2-33\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144515Z
LAST-MODIFIED:20180213T144515Z
TRANSP:OPAQUE
END:VEVENT
* Sky Sox vs. Cubs
<2018-08-21 Tue 19:40-22:40>
:PROPERTIES:
:ID:       vu36kTF3cgs-x_lJ67GuJWMD@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Sky Sox vs. Cubs Sky Sox vs. Cubs

Follow on MiLB First Pitch  https //stza.co/+wmy4-2W

Shop  https //stza.co/+wmy4-3f

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Sky Sox vs. Cubs
END:VALARM
DTSTART:20180822T004000Z
DTEND:20180822T034000Z
UID:vu36kTF3cgs-x_lJ67GuJWMD@stanza.co
SUMMARY:Sky Sox vs. Cubs
DESCRIPTION:Sky Sox vs. Cubs\n\nFollow on MiLB First Pitch: https://stza.co/+wmy4-2W\n\nShop: https://stza.co/+wmy4-3f\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144515Z
LAST-MODIFIED:20180213T144515Z
TRANSP:OPAQUE
END:VEVENT
* Sky Sox vs. Cubs
<2018-08-22 Wed 19:40-22:40>
:PROPERTIES:
:ID:       -Mp_SpIFaplfoao2ktBk4ZA0@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Sky Sox vs. Cubs Sky Sox vs. Cubs

Follow on MiLB First Pitch  https //stza.co/+wmy6-E

Shop  https //stza.co/+wmy6-3x

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Sky Sox vs. Cubs
END:VALARM
DTSTART:20180823T004000Z
DTEND:20180823T034000Z
UID:-Mp_SpIFaplfoao2ktBk4ZA0@stanza.co
SUMMARY:Sky Sox vs. Cubs
DESCRIPTION:Sky Sox vs. Cubs\n\nFollow on MiLB First Pitch: https://stza.co/+wmy6-E\n\nShop: https://stza.co/+wmy6-3x\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144515Z
LAST-MODIFIED:20180213T144515Z
TRANSP:OPAQUE
END:VEVENT
* Sky Sox vs. Cubs
<2018-08-23 Thu 19:40-22:40>
:PROPERTIES:
:ID:       f734mhdaHBpxfaLBwsIpgDXZ@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Sky Sox vs. Cubs Sky Sox vs. Cubs

Follow on MiLB First Pitch  https //stza.co/+wmy8-3i

Shop  https //stza.co/+wmy8-S

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Sky Sox vs. Cubs
END:VALARM
DTSTART:20180824T004000Z
DTEND:20180824T034000Z
UID:f734mhdaHBpxfaLBwsIpgDXZ@stanza.co
SUMMARY:Sky Sox vs. Cubs
DESCRIPTION:Sky Sox vs. Cubs\n\nFollow on MiLB First Pitch: https://stza.co/+wmy8-3i\n\nShop: https://stza.co/+wmy8-S\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144515Z
LAST-MODIFIED:20180213T144515Z
TRANSP:OPAQUE
END:VEVENT
* Sky Sox @ Dodgers
<2018-08-24 Fri 19:05-22:05>
:PROPERTIES:
:ID:       BcWpRKF3TpjYsoJgVj7VWDqS@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Sky Sox @ Dodgers Sky Sox @ Dodgers

Follow on MiLB First Pitch  https //stza.co/+v$M9-3p

Shop  https //stza.co/+v$M9-G

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Sky Sox @ Dodgers
END:VALARM
DTSTART:20180825T000500Z
DTEND:20180825T030500Z
UID:BcWpRKF3TpjYsoJgVj7VWDqS@stanza.co
SUMMARY:Sky Sox @ Dodgers
DESCRIPTION:Sky Sox @ Dodgers\n\nFollow on MiLB First Pitch: https://stza.co/+v$M9-3p\n\nShop: https://stza.co/+v$M9-G\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144515Z
LAST-MODIFIED:20180213T144515Z
TRANSP:OPAQUE
END:VEVENT
* Sky Sox @ Dodgers
<2018-08-25 Sat 19:05-22:05>
:PROPERTIES:
:ID:       n-o7iW8NoRozk7m0CmihwiXk@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Sky Sox @ Dodgers Sky Sox @ Dodgers

Follow on MiLB First Pitch  https //stza.co/+v$Ma-3a

Shop  https //stza.co/+v$Ma-X

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Sky Sox @ Dodgers
END:VALARM
DTSTART:20180826T000500Z
DTEND:20180826T030500Z
UID:n-o7iW8NoRozk7m0CmihwiXk@stanza.co
SUMMARY:Sky Sox @ Dodgers
DESCRIPTION:Sky Sox @ Dodgers\n\nFollow on MiLB First Pitch: https://stza.co/+v$Ma-3a\n\nShop: https://stza.co/+v$Ma-X\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144515Z
LAST-MODIFIED:20180213T144515Z
TRANSP:OPAQUE
END:VEVENT
* Sky Sox @ Dodgers
<2018-08-26 Sun 18:05-21:05>
:PROPERTIES:
:ID:       0pKF8cQg2SfOSlyS6wXzExq4@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Sky Sox @ Dodgers Sky Sox @ Dodgers

Follow on MiLB First Pitch  https //stza.co/+v$Mb-2O

Shop  https //stza.co/+v$Mb-3X

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Sky Sox @ Dodgers
END:VALARM
DTSTART:20180826T230500Z
DTEND:20180827T020500Z
UID:0pKF8cQg2SfOSlyS6wXzExq4@stanza.co
SUMMARY:Sky Sox @ Dodgers
DESCRIPTION:Sky Sox @ Dodgers\n\nFollow on MiLB First Pitch: https://stza.co/+v$Mb-2O\n\nShop: https://stza.co/+v$Mb-3X\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144515Z
LAST-MODIFIED:20180213T144515Z
TRANSP:OPAQUE
END:VEVENT
* Sky Sox @ Dodgers
<2018-08-27 Mon 19:05-22:05>
:PROPERTIES:
:ID:       VSISZe7HTF8JsxaFMHKjhAgU@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Sky Sox @ Dodgers Sky Sox @ Dodgers

Follow on MiLB First Pitch  https //stza.co/+v$Mc-L

Shop  https //stza.co/+v$Mc-2M

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Sky Sox @ Dodgers
END:VALARM
DTSTART:20180828T000500Z
DTEND:20180828T030500Z
UID:VSISZe7HTF8JsxaFMHKjhAgU@stanza.co
SUMMARY:Sky Sox @ Dodgers
DESCRIPTION:Sky Sox @ Dodgers\n\nFollow on MiLB First Pitch: https://stza.co/+v$Mc-L\n\nShop: https://stza.co/+v$Mc-2M\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144515Z
LAST-MODIFIED:20180213T144515Z
TRANSP:OPAQUE
END:VEVENT
* Sky Sox @ Storm Chasers
<2018-08-28 Tue 19:05-22:05>
:PROPERTIES:
:ID:       DaewXBXWP84UcUM3dYsFmPqu@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Sky Sox @ Storm Chasers Sky Sox @ Storm Chasers

Follow on MiLB First Pitch  https //stza.co/+whCB-3y

Shop  https //stza.co/+whCB-39

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Sky Sox @ Storm Chasers
END:VALARM
DTSTART:20180829T000500Z
DTEND:20180829T030500Z
UID:DaewXBXWP84UcUM3dYsFmPqu@stanza.co
SUMMARY:Sky Sox @ Storm Chasers
DESCRIPTION:Sky Sox @ Storm Chasers\n\nFollow on MiLB First Pitch: https://stza.co/+whCB-3y\n\nShop: https://stza.co/+whCB-39\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144515Z
LAST-MODIFIED:20180213T144515Z
TRANSP:OPAQUE
END:VEVENT
* Sky Sox @ Storm Chasers
<2018-08-29 Wed 19:05-22:05>
:PROPERTIES:
:ID:       YxWsdjanOpo_dfIlylGzZaWN@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Sky Sox @ Storm Chasers Sky Sox @ Storm Chasers

Follow on MiLB First Pitch  https //stza.co/+whCC-o

Shop  https //stza.co/+whCC-1b

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Sky Sox @ Storm Chasers
END:VALARM
DTSTART:20180830T000500Z
DTEND:20180830T030500Z
UID:YxWsdjanOpo_dfIlylGzZaWN@stanza.co
SUMMARY:Sky Sox @ Storm Chasers
DESCRIPTION:Sky Sox @ Storm Chasers\n\nFollow on MiLB First Pitch: https://stza.co/+whCC-o\n\nShop: https://stza.co/+whCC-1b\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144515Z
LAST-MODIFIED:20180213T144515Z
TRANSP:OPAQUE
END:VEVENT
* Sky Sox @ Storm Chasers
<2018-08-30 Thu 19:05-22:05>
:PROPERTIES:
:ID:       b74Un43ldFr9EbXkFnxSTDKy@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Sky Sox @ Storm Chasers Sky Sox @ Storm Chasers

Follow on MiLB First Pitch  https //stza.co/+whCD-1W

Shop  https //stza.co/+whCD-39

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Sky Sox @ Storm Chasers
END:VALARM
DTSTART:20180831T000500Z
DTEND:20180831T030500Z
UID:b74Un43ldFr9EbXkFnxSTDKy@stanza.co
SUMMARY:Sky Sox @ Storm Chasers
DESCRIPTION:Sky Sox @ Storm Chasers\n\nFollow on MiLB First Pitch: https://stza.co/+whCD-1W\n\nShop: https://stza.co/+whCD-39\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144515Z
LAST-MODIFIED:20180213T144515Z
TRANSP:OPAQUE
END:VEVENT
* Sky Sox vs. Dodgers
<2018-08-31 Fri 19:40-22:40>
:PROPERTIES:
:ID:       jairWvBZh8HML6LZirFWjEqd@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Sky Sox vs. Dodgers Sky Sox vs. Dodgers

Follow on MiLB First Pitch  https //stza.co/+wmy9-a

Shop  https //stza.co/+wmy9-1j

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Sky Sox vs. Dodgers
END:VALARM
DTSTART:20180901T004000Z
DTEND:20180901T034000Z
UID:jairWvBZh8HML6LZirFWjEqd@stanza.co
SUMMARY:Sky Sox vs. Dodgers
DESCRIPTION:Sky Sox vs. Dodgers\n\nFollow on MiLB First Pitch: https://stza.co/+wmy9-a\n\nShop: https://stza.co/+wmy9-1j\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144515Z
LAST-MODIFIED:20180213T144515Z
TRANSP:OPAQUE
END:VEVENT
* Sky Sox vs. Dodgers
<2018-09-01 Sat 19:00-22:00>
:PROPERTIES:
:ID:       Ad8Mpl8mH_nlOziXocDBQhyr@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Sky Sox vs. Dodgers Sky Sox vs. Dodgers

Follow on MiLB First Pitch  https //stza.co/+wmyc-20

Shop  https //stza.co/+wmyc-3N

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Sky Sox vs. Dodgers
END:VALARM
DTSTART:20180902T000000Z
DTEND:20180902T030000Z
UID:Ad8Mpl8mH_nlOziXocDBQhyr@stanza.co
SUMMARY:Sky Sox vs. Dodgers
DESCRIPTION:Sky Sox vs. Dodgers\n\nFollow on MiLB First Pitch: https://stza.co/+wmyc-20\n\nShop: https://stza.co/+wmyc-3N\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144515Z
LAST-MODIFIED:20180213T144515Z
TRANSP:OPAQUE
END:VEVENT
* Sky Sox vs. Dodgers
<2018-09-02 Sun 18:00-21:00>
:PROPERTIES:
:ID:       qtHJtEuIFS-ns8EypoiF6Gps@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Sky Sox vs. Dodgers Sky Sox vs. Dodgers

Follow on MiLB First Pitch  https //stza.co/+wmye-19

Shop  https //stza.co/+wmye-2S

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Sky Sox vs. Dodgers
END:VALARM
DTSTART:20180902T230000Z
DTEND:20180903T020000Z
UID:qtHJtEuIFS-ns8EypoiF6Gps@stanza.co
SUMMARY:Sky Sox vs. Dodgers
DESCRIPTION:Sky Sox vs. Dodgers\n\nFollow on MiLB First Pitch: https://stza.co/+wmye-19\n\nShop: https://stza.co/+wmye-2S\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144515Z
LAST-MODIFIED:20180213T144515Z
TRANSP:OPAQUE
END:VEVENT
* Sky Sox vs. Dodgers
<2018-09-03 Mon 14:00-17:00>
:PROPERTIES:
:ID:       LKiS3mVnUHZtyt3uzEv2h97_@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Sky Sox vs. Dodgers Sky Sox vs. Dodgers

Follow on MiLB First Pitch  https //stza.co/+wmyg-3

Shop  https //stza.co/+wmyg-1q

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Sky Sox vs. Dodgers
END:VALARM
DTSTART:20180903T190000Z
DTEND:20180903T220000Z
UID:LKiS3mVnUHZtyt3uzEv2h97_@stanza.co
SUMMARY:Sky Sox vs. Dodgers
DESCRIPTION:Sky Sox vs. Dodgers\n\nFollow on MiLB First Pitch: https://stza.co/+wmyg-3\n\nShop: https://stza.co/+wmyg-1q\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144515Z
LAST-MODIFIED:20180213T144515Z
TRANSP:OPAQUE
END:VEVENT
