#+TITLE:       Main Google calendar entries
#+AUTHOR:      Eric S Fraga
#+EMAIL:       e.fraga@ucl.ac.uk
#+DESCRIPTION: converted using the ical2org awk script
#+CATEGORY:    google
#+STARTUP:     hidestars
#+STARTUP:     overview

* COMMENT original iCal preamble

* Barons @ Lookouts
<2018-04-05 Thu 17:15-20:15>
:PROPERTIES:
:ID:       WMAXbDU1M1tSBliAZ77H-T5l@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Barons @ Lookouts Barons @ Lookouts

Follow on MiLB First Pitch  https //stza.co/+wKBq-q

Shop  https //stza.co/+wKBq-k

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Barons @ Lookouts
END:VALARM
DTSTART:20180405T221500Z
DTEND:20180406T011500Z
UID:WMAXbDU1M1tSBliAZ77H-T5l@stanza.co
SUMMARY:Barons @ Lookouts
DESCRIPTION:Barons @ Lookouts\n\nFollow on MiLB First Pitch: https://stza.co/+wKBq-q\n\nShop: https://stza.co/+wKBq-k\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144506Z
LAST-MODIFIED:20180213T144506Z
TRANSP:OPAQUE
END:VEVENT
* Barons @ Lookouts
<2018-04-06 Fri 18:15-21:15>
:PROPERTIES:
:ID:       c9mLd2e4czjFyTlKxCZ3_X-K@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Barons @ Lookouts Barons @ Lookouts

Follow on MiLB First Pitch  https //stza.co/+wKBr-14

Shop  https //stza.co/+wKBr-3Q

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Barons @ Lookouts
END:VALARM
DTSTART:20180406T231500Z
DTEND:20180407T021500Z
UID:c9mLd2e4czjFyTlKxCZ3_X-K@stanza.co
SUMMARY:Barons @ Lookouts
DESCRIPTION:Barons @ Lookouts\n\nFollow on MiLB First Pitch: https://stza.co/+wKBr-14\n\nShop: https://stza.co/+wKBr-3Q\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144506Z
LAST-MODIFIED:20180213T144506Z
TRANSP:OPAQUE
END:VEVENT
* Barons @ Lookouts
<2018-04-07 Sat 18:15-21:15>
:PROPERTIES:
:ID:       W8fosHPwGdQDG9Gta43__uBB@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Barons @ Lookouts Barons @ Lookouts

Follow on MiLB First Pitch  https //stza.co/+wKBs-2u

Shop  https //stza.co/+wKBs-2a

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Barons @ Lookouts
END:VALARM
DTSTART:20180407T231500Z
DTEND:20180408T021500Z
UID:W8fosHPwGdQDG9Gta43__uBB@stanza.co
SUMMARY:Barons @ Lookouts
DESCRIPTION:Barons @ Lookouts\n\nFollow on MiLB First Pitch: https://stza.co/+wKBs-2u\n\nShop: https://stza.co/+wKBs-2a\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144506Z
LAST-MODIFIED:20180213T144506Z
TRANSP:OPAQUE
END:VEVENT
* Barons @ Lookouts
<2018-04-08 Sun 13:15-16:15>
:PROPERTIES:
:ID:       8-UD-KhUOD0HANSunQnngu30@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Barons @ Lookouts Barons @ Lookouts

Follow on MiLB First Pitch  https //stza.co/+wKBt-S

Shop  https //stza.co/+wKBt-J

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Barons @ Lookouts
END:VALARM
DTSTART:20180408T181500Z
DTEND:20180408T211500Z
UID:8-UD-KhUOD0HANSunQnngu30@stanza.co
SUMMARY:Barons @ Lookouts
DESCRIPTION:Barons @ Lookouts\n\nFollow on MiLB First Pitch: https://stza.co/+wKBt-S\n\nShop: https://stza.co/+wKBt-J\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144506Z
LAST-MODIFIED:20180213T144506Z
TRANSP:OPAQUE
END:VEVENT
* Barons @ Lookouts
<2018-04-09 Mon 18:15-21:15>
:PROPERTIES:
:ID:       3kwnnzXMoy7TBqN_daOyYU2k@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Barons @ Lookouts Barons @ Lookouts

Follow on MiLB First Pitch  https //stza.co/+wKBu-V

Shop  https //stza.co/+wKBu-2b

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Barons @ Lookouts
END:VALARM
DTSTART:20180409T231500Z
DTEND:20180410T021500Z
UID:3kwnnzXMoy7TBqN_daOyYU2k@stanza.co
SUMMARY:Barons @ Lookouts
DESCRIPTION:Barons @ Lookouts\n\nFollow on MiLB First Pitch: https://stza.co/+wKBu-V\n\nShop: https://stza.co/+wKBu-2b\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144506Z
LAST-MODIFIED:20180213T144506Z
TRANSP:OPAQUE
END:VEVENT
* Barons vs. Biscuits
<2018-04-11 Wed 19:05-22:05>
:PROPERTIES:
:ID:       NQJxZktAgWKBPV8Ka4fobJPZ@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Barons vs. Biscuits Barons vs. Biscuits

Follow on MiLB First Pitch  https //stza.co/+wFU_-3Z

Shop  https //stza.co/+wFU_-30

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Barons vs. Biscuits
END:VALARM
DTSTART:20180412T000500Z
DTEND:20180412T030500Z
UID:NQJxZktAgWKBPV8Ka4fobJPZ@stanza.co
SUMMARY:Barons vs. Biscuits
DESCRIPTION:Barons vs. Biscuits\n\nFollow on MiLB First Pitch: https://stza.co/+wFU_-3Z\n\nShop: https://stza.co/+wFU_-30\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144506Z
LAST-MODIFIED:20180213T144506Z
TRANSP:OPAQUE
END:VEVENT
* Barons vs. Biscuits
<2018-04-12 Thu 19:05-22:05>
:PROPERTIES:
:ID:       qx4BUThTqykYMyi84fGp1xB5@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Barons vs. Biscuits Barons vs. Biscuits

Follow on MiLB First Pitch  https //stza.co/+wFV0-25

Shop  https //stza.co/+wFV0-39

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Barons vs. Biscuits
END:VALARM
DTSTART:20180413T000500Z
DTEND:20180413T030500Z
UID:qx4BUThTqykYMyi84fGp1xB5@stanza.co
SUMMARY:Barons vs. Biscuits
DESCRIPTION:Barons vs. Biscuits\n\nFollow on MiLB First Pitch: https://stza.co/+wFV0-25\n\nShop: https://stza.co/+wFV0-39\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144506Z
LAST-MODIFIED:20180213T144506Z
TRANSP:OPAQUE
END:VEVENT
* Barons vs. Biscuits
<2018-04-13 Fri 19:05-22:05>
:PROPERTIES:
:ID:       ErJIJSpxN-omajdcOg6NTD6J@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Barons vs. Biscuits Barons vs. Biscuits

Follow on MiLB First Pitch  https //stza.co/+wFV1-3o

Shop  https //stza.co/+wFV1-1l

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Barons vs. Biscuits
END:VALARM
DTSTART:20180414T000500Z
DTEND:20180414T030500Z
UID:ErJIJSpxN-omajdcOg6NTD6J@stanza.co
SUMMARY:Barons vs. Biscuits
DESCRIPTION:Barons vs. Biscuits\n\nFollow on MiLB First Pitch: https://stza.co/+wFV1-3o\n\nShop: https://stza.co/+wFV1-1l\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144506Z
LAST-MODIFIED:20180213T144506Z
TRANSP:OPAQUE
END:VEVENT
* Barons vs. Biscuits
<2018-04-14 Sat 18:30-21:30>
:PROPERTIES:
:ID:       xIhw7dnBYjxsSUtw6_uRnS2G@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Barons vs. Biscuits Barons vs. Biscuits

Follow on MiLB First Pitch  https //stza.co/+wFV3-3k

Shop  https //stza.co/+wFV3-3V

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Barons vs. Biscuits
END:VALARM
DTSTART:20180414T233000Z
DTEND:20180415T023000Z
UID:xIhw7dnBYjxsSUtw6_uRnS2G@stanza.co
SUMMARY:Barons vs. Biscuits
DESCRIPTION:Barons vs. Biscuits\n\nFollow on MiLB First Pitch: https://stza.co/+wFV3-3k\n\nShop: https://stza.co/+wFV3-3V\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144506Z
LAST-MODIFIED:20180213T144506Z
TRANSP:OPAQUE
END:VEVENT
* Barons vs. Biscuits
<2018-04-15 Sun 15:00-18:00>
:PROPERTIES:
:ID:       BFHXa0kVFkzYFUUBywZ57ymD@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Barons vs. Biscuits Barons vs. Biscuits

Follow on MiLB First Pitch  https //stza.co/+wFV6-3k

Shop  https //stza.co/+wFV6-1T

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Barons vs. Biscuits
END:VALARM
DTSTART:20180415T200000Z
DTEND:20180415T230000Z
UID:BFHXa0kVFkzYFUUBywZ57ymD@stanza.co
SUMMARY:Barons vs. Biscuits
DESCRIPTION:Barons vs. Biscuits\n\nFollow on MiLB First Pitch: https://stza.co/+wFV6-3k\n\nShop: https://stza.co/+wFV6-1T\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144506Z
LAST-MODIFIED:20180213T144506Z
TRANSP:OPAQUE
END:VEVENT
* Barons @ Generals
<2018-04-16 Mon 18:05-21:05>
:PROPERTIES:
:ID:       F0itySE1ivHsDiZY3i54khFM@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Barons @ Generals Barons @ Generals

Follow on MiLB First Pitch  https //stza.co/+wCMN-B

Shop  https //stza.co/+wCMN-1V

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Barons @ Generals
END:VALARM
DTSTART:20180416T230500Z
DTEND:20180417T020500Z
UID:F0itySE1ivHsDiZY3i54khFM@stanza.co
SUMMARY:Barons @ Generals
DESCRIPTION:Barons @ Generals\n\nFollow on MiLB First Pitch: https://stza.co/+wCMN-B\n\nShop: https://stza.co/+wCMN-1V\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144506Z
LAST-MODIFIED:20180213T144506Z
TRANSP:OPAQUE
END:VEVENT
* Barons @ Generals
<2018-04-17 Tue 18:05-21:05>
:PROPERTIES:
:ID:       hePo3KOe3pF8RGAL8dFXTzZx@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Barons @ Generals Barons @ Generals

Follow on MiLB First Pitch  https //stza.co/+wCMO-3f

Shop  https //stza.co/+wCMO-1Q

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Barons @ Generals
END:VALARM
DTSTART:20180417T230500Z
DTEND:20180418T020500Z
UID:hePo3KOe3pF8RGAL8dFXTzZx@stanza.co
SUMMARY:Barons @ Generals
DESCRIPTION:Barons @ Generals\n\nFollow on MiLB First Pitch: https://stza.co/+wCMO-3f\n\nShop: https://stza.co/+wCMO-1Q\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144506Z
LAST-MODIFIED:20180213T144506Z
TRANSP:OPAQUE
END:VEVENT
* Barons @ Generals
<2018-04-18 Wed 11:05-14:05>
:PROPERTIES:
:ID:       GudRSZ_NVqZHIXzelkMFNUQr@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Barons @ Generals Barons @ Generals

Follow on MiLB First Pitch  https //stza.co/+wCMP-2Z

Shop  https //stza.co/+wCMP-35

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Barons @ Generals
END:VALARM
DTSTART:20180418T160500Z
DTEND:20180418T190500Z
UID:GudRSZ_NVqZHIXzelkMFNUQr@stanza.co
SUMMARY:Barons @ Generals
DESCRIPTION:Barons @ Generals\n\nFollow on MiLB First Pitch: https://stza.co/+wCMP-2Z\n\nShop: https://stza.co/+wCMP-35\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144506Z
LAST-MODIFIED:20180213T144506Z
TRANSP:OPAQUE
END:VEVENT
* Barons @ Generals
<2018-04-19 Thu 18:05-21:05>
:PROPERTIES:
:ID:       VzVqtA2uapIfan6NW7toGgTj@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Barons @ Generals Barons @ Generals

Follow on MiLB First Pitch  https //stza.co/+wCMQ-Q

Shop  https //stza.co/+wCMQ-I

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Barons @ Generals
END:VALARM
DTSTART:20180419T230500Z
DTEND:20180420T020500Z
UID:VzVqtA2uapIfan6NW7toGgTj@stanza.co
SUMMARY:Barons @ Generals
DESCRIPTION:Barons @ Generals\n\nFollow on MiLB First Pitch: https://stza.co/+wCMQ-Q\n\nShop: https://stza.co/+wCMQ-I\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144506Z
LAST-MODIFIED:20180213T144506Z
TRANSP:OPAQUE
END:VEVENT
* Barons @ Generals
<2018-04-20 Fri 18:05-21:05>
:PROPERTIES:
:ID:       K36kTYBvoWXy23ZJI511OTxX@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Barons @ Generals Barons @ Generals

Follow on MiLB First Pitch  https //stza.co/+wCMS-b

Shop  https //stza.co/+wCMS-a

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Barons @ Generals
END:VALARM
DTSTART:20180420T230500Z
DTEND:20180421T020500Z
UID:K36kTYBvoWXy23ZJI511OTxX@stanza.co
SUMMARY:Barons @ Generals
DESCRIPTION:Barons @ Generals\n\nFollow on MiLB First Pitch: https://stza.co/+wCMS-b\n\nShop: https://stza.co/+wCMS-a\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144506Z
LAST-MODIFIED:20180213T144506Z
TRANSP:OPAQUE
END:VEVENT
* Barons @ Blue Wahoos
<2018-04-21 Sat 18:05-21:05>
:PROPERTIES:
:ID:       4icKVQzUrI33gNL8LqEeuzXV@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Barons @ Blue Wahoos Barons @ Blue Wahoos

Follow on MiLB First Pitch  https //stza.co/+wx6Q-1D

Shop  https //stza.co/+wx6Q-F

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Barons @ Blue Wahoos
END:VALARM
DTSTART:20180421T230500Z
DTEND:20180422T020500Z
UID:4icKVQzUrI33gNL8LqEeuzXV@stanza.co
SUMMARY:Barons @ Blue Wahoos
DESCRIPTION:Barons @ Blue Wahoos\n\nFollow on MiLB First Pitch: https://stza.co/+wx6Q-1D\n\nShop: https://stza.co/+wx6Q-F\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144506Z
LAST-MODIFIED:20180213T144506Z
TRANSP:OPAQUE
END:VEVENT
* Barons @ Blue Wahoos
<2018-04-22 Sun 13:05-16:05>
:PROPERTIES:
:ID:       FZf1j2ZaZlkk5HPoyzOiyjqd@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Barons @ Blue Wahoos Barons @ Blue Wahoos

Follow on MiLB First Pitch  https //stza.co/+wx6R-2L

Shop  https //stza.co/+wx6R-3w

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Barons @ Blue Wahoos
END:VALARM
DTSTART:20180422T180500Z
DTEND:20180422T210500Z
UID:FZf1j2ZaZlkk5HPoyzOiyjqd@stanza.co
SUMMARY:Barons @ Blue Wahoos
DESCRIPTION:Barons @ Blue Wahoos\n\nFollow on MiLB First Pitch: https://stza.co/+wx6R-2L\n\nShop: https://stza.co/+wx6R-3w\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144506Z
LAST-MODIFIED:20180213T144506Z
TRANSP:OPAQUE
END:VEVENT
* Barons @ Blue Wahoos
<2018-04-23 Mon 18:35-21:35>
:PROPERTIES:
:ID:       zhQSAiBjRdhevQzeglZTC0nW@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Barons @ Blue Wahoos Barons @ Blue Wahoos

Follow on MiLB First Pitch  https //stza.co/+wx6S-2a

Shop  https //stza.co/+wx6S-b

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Barons @ Blue Wahoos
END:VALARM
DTSTART:20180423T233500Z
DTEND:20180424T023500Z
UID:zhQSAiBjRdhevQzeglZTC0nW@stanza.co
SUMMARY:Barons @ Blue Wahoos
DESCRIPTION:Barons @ Blue Wahoos\n\nFollow on MiLB First Pitch: https://stza.co/+wx6S-2a\n\nShop: https://stza.co/+wx6S-b\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144506Z
LAST-MODIFIED:20180213T144506Z
TRANSP:OPAQUE
END:VEVENT
* Barons @ Blue Wahoos
<2018-04-24 Tue 18:35-21:35>
:PROPERTIES:
:ID:       JpbnbPnqPnZ5wg1mZ4DSA53R@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Barons @ Blue Wahoos Barons @ Blue Wahoos

Follow on MiLB First Pitch  https //stza.co/+wx6U-2E

Shop  https //stza.co/+wx6U-27

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Barons @ Blue Wahoos
END:VALARM
DTSTART:20180424T233500Z
DTEND:20180425T023500Z
UID:JpbnbPnqPnZ5wg1mZ4DSA53R@stanza.co
SUMMARY:Barons @ Blue Wahoos
DESCRIPTION:Barons @ Blue Wahoos\n\nFollow on MiLB First Pitch: https://stza.co/+wx6U-2E\n\nShop: https://stza.co/+wx6U-27\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144506Z
LAST-MODIFIED:20180213T144506Z
TRANSP:OPAQUE
END:VEVENT
* Barons @ Blue Wahoos
<2018-04-25 Wed 18:35-21:35>
:PROPERTIES:
:ID:       AH0aqa2OkeLisHzx8pjSbtfz@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Barons @ Blue Wahoos Barons @ Blue Wahoos

Follow on MiLB First Pitch  https //stza.co/+wx6V-1_

Shop  https //stza.co/+wx6V-3z

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Barons @ Blue Wahoos
END:VALARM
DTSTART:20180425T233500Z
DTEND:20180426T023500Z
UID:AH0aqa2OkeLisHzx8pjSbtfz@stanza.co
SUMMARY:Barons @ Blue Wahoos
DESCRIPTION:Barons @ Blue Wahoos\n\nFollow on MiLB First Pitch: https://stza.co/+wx6V-1_\n\nShop: https://stza.co/+wx6V-3z\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144506Z
LAST-MODIFIED:20180213T144506Z
TRANSP:OPAQUE
END:VEVENT
* Barons vs. Shuckers
<2018-04-26 Thu 19:05-22:05>
:PROPERTIES:
:ID:       UojRztQwcJ8vPSxCtEjKY4DJ@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Barons vs. Shuckers Barons vs. Shuckers

Follow on MiLB First Pitch  https //stza.co/+wFV8-2G

Shop  https //stza.co/+wFV8-2K

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Barons vs. Shuckers
END:VALARM
DTSTART:20180427T000500Z
DTEND:20180427T030500Z
UID:UojRztQwcJ8vPSxCtEjKY4DJ@stanza.co
SUMMARY:Barons vs. Shuckers
DESCRIPTION:Barons vs. Shuckers\n\nFollow on MiLB First Pitch: https://stza.co/+wFV8-2G\n\nShop: https://stza.co/+wFV8-2K\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144506Z
LAST-MODIFIED:20180213T144506Z
TRANSP:OPAQUE
END:VEVENT
* Barons vs. Shuckers
<2018-04-27 Fri 19:05-22:05>
:PROPERTIES:
:ID:       UNcwIDkztfH983hpTJQYYbtS@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Barons vs. Shuckers Barons vs. Shuckers

Follow on MiLB First Pitch  https //stza.co/+wFV9-3X

Shop  https //stza.co/+wFV9-C

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Barons vs. Shuckers
END:VALARM
DTSTART:20180428T000500Z
DTEND:20180428T030500Z
UID:UNcwIDkztfH983hpTJQYYbtS@stanza.co
SUMMARY:Barons vs. Shuckers
DESCRIPTION:Barons vs. Shuckers\n\nFollow on MiLB First Pitch: https://stza.co/+wFV9-3X\n\nShop: https://stza.co/+wFV9-C\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144506Z
LAST-MODIFIED:20180213T144506Z
TRANSP:OPAQUE
END:VEVENT
* Barons vs. Shuckers
<2018-04-28 Sat 18:30-21:30>
:PROPERTIES:
:ID:       akIrg_FGVDxoXvmBySnTgbXL@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Barons vs. Shuckers Barons vs. Shuckers

Follow on MiLB First Pitch  https //stza.co/+wFVb-2E

Shop  https //stza.co/+wFVb-20

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Barons vs. Shuckers
END:VALARM
DTSTART:20180428T233000Z
DTEND:20180429T023000Z
UID:akIrg_FGVDxoXvmBySnTgbXL@stanza.co
SUMMARY:Barons vs. Shuckers
DESCRIPTION:Barons vs. Shuckers\n\nFollow on MiLB First Pitch: https://stza.co/+wFVb-2E\n\nShop: https://stza.co/+wFVb-20\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144506Z
LAST-MODIFIED:20180213T144506Z
TRANSP:OPAQUE
END:VEVENT
* Barons vs. Shuckers
<2018-04-29 Sun 15:00-18:00>
:PROPERTIES:
:ID:       F9pT1DJNj6GvyICCTQUIa5t0@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Barons vs. Shuckers Barons vs. Shuckers

Follow on MiLB First Pitch  https //stza.co/+wFVe-1b

Shop  https //stza.co/+wFVe-w

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Barons vs. Shuckers
END:VALARM
DTSTART:20180429T200000Z
DTEND:20180429T230000Z
UID:F9pT1DJNj6GvyICCTQUIa5t0@stanza.co
SUMMARY:Barons vs. Shuckers
DESCRIPTION:Barons vs. Shuckers\n\nFollow on MiLB First Pitch: https://stza.co/+wFVe-1b\n\nShop: https://stza.co/+wFVe-w\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144506Z
LAST-MODIFIED:20180213T144506Z
TRANSP:OPAQUE
END:VEVENT
* Barons vs. Shuckers
<2018-04-30 Mon 11:00-14:00>
:PROPERTIES:
:ID:       kI9yzp7ihc_-RxRlVGj319VW@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Barons vs. Shuckers Barons vs. Shuckers

Follow on MiLB First Pitch  https //stza.co/+wFVf-2D

Shop  https //stza.co/+wFVf-3y

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Barons vs. Shuckers
END:VALARM
DTSTART:20180430T160000Z
DTEND:20180430T190000Z
UID:kI9yzp7ihc_-RxRlVGj319VW@stanza.co
SUMMARY:Barons vs. Shuckers
DESCRIPTION:Barons vs. Shuckers\n\nFollow on MiLB First Pitch: https://stza.co/+wFVf-2D\n\nShop: https://stza.co/+wFVf-3y\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144506Z
LAST-MODIFIED:20180213T144506Z
TRANSP:OPAQUE
END:VEVENT
* Barons @ Smokies
<2018-05-02 Wed 18:00-21:00>
:PROPERTIES:
:ID:       YripCTZwQPRMrM9uYac_7pvz@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Barons @ Smokies Barons @ Smokies

Follow on MiLB First Pitch  https //stza.co/+xVSP-2b

Shop  https //stza.co/+xVSP-3e

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Barons @ Smokies
END:VALARM
DTSTART:20180502T230000Z
DTEND:20180503T020000Z
UID:YripCTZwQPRMrM9uYac_7pvz@stanza.co
SUMMARY:Barons @ Smokies
DESCRIPTION:Barons @ Smokies\n\nFollow on MiLB First Pitch: https://stza.co/+xVSP-2b\n\nShop: https://stza.co/+xVSP-3e\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144506Z
LAST-MODIFIED:20180213T144506Z
TRANSP:OPAQUE
END:VEVENT
* Barons @ Smokies
<2018-05-03 Thu 18:00-21:00>
:PROPERTIES:
:ID:       QoHXDVqx5x99IBCJDvFg0Ix2@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Barons @ Smokies Barons @ Smokies

Follow on MiLB First Pitch  https //stza.co/+xVSQ-D

Shop  https //stza.co/+xVSQ-1s

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Barons @ Smokies
END:VALARM
DTSTART:20180503T230000Z
DTEND:20180504T020000Z
UID:QoHXDVqx5x99IBCJDvFg0Ix2@stanza.co
SUMMARY:Barons @ Smokies
DESCRIPTION:Barons @ Smokies\n\nFollow on MiLB First Pitch: https://stza.co/+xVSQ-D\n\nShop: https://stza.co/+xVSQ-1s\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144506Z
LAST-MODIFIED:20180213T144506Z
TRANSP:OPAQUE
END:VEVENT
* Barons @ Smokies
<2018-05-04 Fri 18:00-21:00>
:PROPERTIES:
:ID:       CbrwUT9FDm0IU_ffvPQq7Hk7@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Barons @ Smokies Barons @ Smokies

Follow on MiLB First Pitch  https //stza.co/+xVSR-1r

Shop  https //stza.co/+xVSR-3C

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Barons @ Smokies
END:VALARM
DTSTART:20180504T230000Z
DTEND:20180505T020000Z
UID:CbrwUT9FDm0IU_ffvPQq7Hk7@stanza.co
SUMMARY:Barons @ Smokies
DESCRIPTION:Barons @ Smokies\n\nFollow on MiLB First Pitch: https://stza.co/+xVSR-1r\n\nShop: https://stza.co/+xVSR-3C\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144506Z
LAST-MODIFIED:20180213T144506Z
TRANSP:OPAQUE
END:VEVENT
* Barons @ Smokies
<2018-05-05 Sat 18:00-21:00>
:PROPERTIES:
:ID:       DTKbL3b5d1AOqv0w0Mt-L-ej@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Barons @ Smokies Barons @ Smokies

Follow on MiLB First Pitch  https //stza.co/+xVSS-2h

Shop  https //stza.co/+xVSS-1C

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Barons @ Smokies
END:VALARM
DTSTART:20180505T230000Z
DTEND:20180506T020000Z
UID:DTKbL3b5d1AOqv0w0Mt-L-ej@stanza.co
SUMMARY:Barons @ Smokies
DESCRIPTION:Barons @ Smokies\n\nFollow on MiLB First Pitch: https://stza.co/+xVSS-2h\n\nShop: https://stza.co/+xVSS-1C\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144506Z
LAST-MODIFIED:20180213T144506Z
TRANSP:OPAQUE
END:VEVENT
* Barons @ Smokies
<2018-05-06 Sun 13:00-16:00>
:PROPERTIES:
:ID:       21naZhmOG_RE_wGqqI7z2UKH@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Barons @ Smokies Barons @ Smokies

Follow on MiLB First Pitch  https //stza.co/+xVST-3Q

Shop  https //stza.co/+xVST-3N

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Barons @ Smokies
END:VALARM
DTSTART:20180506T180000Z
DTEND:20180506T210000Z
UID:21naZhmOG_RE_wGqqI7z2UKH@stanza.co
SUMMARY:Barons @ Smokies
DESCRIPTION:Barons @ Smokies\n\nFollow on MiLB First Pitch: https://stza.co/+xVST-3Q\n\nShop: https://stza.co/+xVST-3N\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144506Z
LAST-MODIFIED:20180213T144506Z
TRANSP:OPAQUE
END:VEVENT
* Barons vs. Blue Wahoos
<2018-05-07 Mon 19:05-22:05>
:PROPERTIES:
:ID:       XNAYqgX0-hhMt3viYABFyzZp@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Barons vs. Blue Wahoos Barons vs. Blue Wahoos

Follow on MiLB First Pitch  https //stza.co/+wFVi-1n

Shop  https //stza.co/+wFVi-1Q

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Barons vs. Blue Wahoos
END:VALARM
DTSTART:20180508T000500Z
DTEND:20180508T030500Z
UID:XNAYqgX0-hhMt3viYABFyzZp@stanza.co
SUMMARY:Barons vs. Blue Wahoos
DESCRIPTION:Barons vs. Blue Wahoos\n\nFollow on MiLB First Pitch: https://stza.co/+wFVi-1n\n\nShop: https://stza.co/+wFVi-1Q\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144506Z
LAST-MODIFIED:20180213T144506Z
TRANSP:OPAQUE
END:VEVENT
* Barons vs. Blue Wahoos
<2018-05-08 Tue 19:05-22:05>
:PROPERTIES:
:ID:       6OMpT2igffD2botE0rIsdETJ@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Barons vs. Blue Wahoos Barons vs. Blue Wahoos

Follow on MiLB First Pitch  https //stza.co/+wFVj-3D

Shop  https //stza.co/+wFVj-1N

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Barons vs. Blue Wahoos
END:VALARM
DTSTART:20180509T000500Z
DTEND:20180509T030500Z
UID:6OMpT2igffD2botE0rIsdETJ@stanza.co
SUMMARY:Barons vs. Blue Wahoos
DESCRIPTION:Barons vs. Blue Wahoos\n\nFollow on MiLB First Pitch: https://stza.co/+wFVj-3D\n\nShop: https://stza.co/+wFVj-1N\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144506Z
LAST-MODIFIED:20180213T144506Z
TRANSP:OPAQUE
END:VEVENT
* Barons vs. Blue Wahoos
<2018-05-09 Wed 11:30-14:30>
:PROPERTIES:
:ID:       C_PMl30hFnWdxk5LFzWy9xX1@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Barons vs. Blue Wahoos Barons vs. Blue Wahoos

Follow on MiLB First Pitch  https //stza.co/+wFVm-1R

Shop  https //stza.co/+wFVm-I

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Barons vs. Blue Wahoos
END:VALARM
DTSTART:20180509T163000Z
DTEND:20180509T193000Z
UID:C_PMl30hFnWdxk5LFzWy9xX1@stanza.co
SUMMARY:Barons vs. Blue Wahoos
DESCRIPTION:Barons vs. Blue Wahoos\n\nFollow on MiLB First Pitch: https://stza.co/+wFVm-1R\n\nShop: https://stza.co/+wFVm-I\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144506Z
LAST-MODIFIED:20180213T144506Z
TRANSP:OPAQUE
END:VEVENT
* Barons vs. Blue Wahoos
<2018-05-10 Thu 19:05-22:05>
:PROPERTIES:
:ID:       Z66Uxk-EHani3v84lIDbYxUp@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Barons vs. Blue Wahoos Barons vs. Blue Wahoos

Follow on MiLB First Pitch  https //stza.co/+wFVn-1y

Shop  https //stza.co/+wFVn-3s

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Barons vs. Blue Wahoos
END:VALARM
DTSTART:20180511T000500Z
DTEND:20180511T030500Z
UID:Z66Uxk-EHani3v84lIDbYxUp@stanza.co
SUMMARY:Barons vs. Blue Wahoos
DESCRIPTION:Barons vs. Blue Wahoos\n\nFollow on MiLB First Pitch: https://stza.co/+wFVn-1y\n\nShop: https://stza.co/+wFVn-3s\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144506Z
LAST-MODIFIED:20180213T144506Z
TRANSP:OPAQUE
END:VEVENT
* Barons vs. Blue Wahoos
<2018-05-11 Fri 19:05-22:05>
:PROPERTIES:
:ID:       MeFbuEMTrl4cN5wbwM7tgZ08@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Barons vs. Blue Wahoos Barons vs. Blue Wahoos

Follow on MiLB First Pitch  https //stza.co/+wFVq-2j

Shop  https //stza.co/+wFVq-2z

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Barons vs. Blue Wahoos
END:VALARM
DTSTART:20180512T000500Z
DTEND:20180512T030500Z
UID:MeFbuEMTrl4cN5wbwM7tgZ08@stanza.co
SUMMARY:Barons vs. Blue Wahoos
DESCRIPTION:Barons vs. Blue Wahoos\n\nFollow on MiLB First Pitch: https://stza.co/+wFVq-2j\n\nShop: https://stza.co/+wFVq-2z\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144506Z
LAST-MODIFIED:20180213T144506Z
TRANSP:OPAQUE
END:VEVENT
* Barons @ BayBears
<2018-05-12 Sat 19:05-22:05>
:PROPERTIES:
:ID:       YbGjkaq1PjUCxEXxKH7VV81D@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Barons @ BayBears Barons @ BayBears

Follow on MiLB First Pitch  https //stza.co/+v$Pu-2M

Shop  https //stza.co/+v$Pu-3Q

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Barons @ BayBears
END:VALARM
DTSTART:20180513T000500Z
DTEND:20180513T030500Z
UID:YbGjkaq1PjUCxEXxKH7VV81D@stanza.co
SUMMARY:Barons @ BayBears
DESCRIPTION:Barons @ BayBears\n\nFollow on MiLB First Pitch: https://stza.co/+v$Pu-2M\n\nShop: https://stza.co/+v$Pu-3Q\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144506Z
LAST-MODIFIED:20180213T144506Z
TRANSP:OPAQUE
END:VEVENT
* Barons @ BayBears
<2018-05-13 Sun 14:05-17:05>
:PROPERTIES:
:ID:       t-XqHFwQJP-EYNVlyPqvgvwS@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Barons @ BayBears Barons @ BayBears

Follow on MiLB First Pitch  https //stza.co/+v$Pv-1j

Shop  https //stza.co/+v$Pv-1G

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Barons @ BayBears
END:VALARM
DTSTART:20180513T190500Z
DTEND:20180513T220500Z
UID:t-XqHFwQJP-EYNVlyPqvgvwS@stanza.co
SUMMARY:Barons @ BayBears
DESCRIPTION:Barons @ BayBears\n\nFollow on MiLB First Pitch: https://stza.co/+v$Pv-1j\n\nShop: https://stza.co/+v$Pv-1G\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144506Z
LAST-MODIFIED:20180213T144506Z
TRANSP:OPAQUE
END:VEVENT
* Barons @ BayBears
<2018-05-14 Mon 18:35-21:35>
:PROPERTIES:
:ID:       sW_8SDMb9UudrOfSaMWu5DZY@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Barons @ BayBears Barons @ BayBears

Follow on MiLB First Pitch  https //stza.co/+v$Pw-3h

Shop  https //stza.co/+v$Pw-3n

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Barons @ BayBears
END:VALARM
DTSTART:20180514T233500Z
DTEND:20180515T023500Z
UID:sW_8SDMb9UudrOfSaMWu5DZY@stanza.co
SUMMARY:Barons @ BayBears
DESCRIPTION:Barons @ BayBears\n\nFollow on MiLB First Pitch: https://stza.co/+v$Pw-3h\n\nShop: https://stza.co/+v$Pw-3n\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144506Z
LAST-MODIFIED:20180213T144506Z
TRANSP:OPAQUE
END:VEVENT
* Barons @ BayBears
<2018-05-15 Tue 18:35-21:35>
:PROPERTIES:
:ID:       BR6Inc_5zP0Rthogo1uQS0iG@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Barons @ BayBears Barons @ BayBears

Follow on MiLB First Pitch  https //stza.co/+v$Px-3Y

Shop  https //stza.co/+v$Px-1r

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Barons @ BayBears
END:VALARM
DTSTART:20180515T233500Z
DTEND:20180516T023500Z
UID:BR6Inc_5zP0Rthogo1uQS0iG@stanza.co
SUMMARY:Barons @ BayBears
DESCRIPTION:Barons @ BayBears\n\nFollow on MiLB First Pitch: https://stza.co/+v$Px-3Y\n\nShop: https://stza.co/+v$Px-1r\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144506Z
LAST-MODIFIED:20180213T144506Z
TRANSP:OPAQUE
END:VEVENT
* Barons @ BayBears
<2018-05-16 Wed 11:05-14:05>
:PROPERTIES:
:ID:       Z8spyclyyXBbRe85SYOBWwqU@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Barons @ BayBears Barons @ BayBears

Follow on MiLB First Pitch  https //stza.co/+v$Py-p

Shop  https //stza.co/+v$Py-3j

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Barons @ BayBears
END:VALARM
DTSTART:20180516T160500Z
DTEND:20180516T190500Z
UID:Z8spyclyyXBbRe85SYOBWwqU@stanza.co
SUMMARY:Barons @ BayBears
DESCRIPTION:Barons @ BayBears\n\nFollow on MiLB First Pitch: https://stza.co/+v$Py-p\n\nShop: https://stza.co/+v$Py-3j\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144506Z
LAST-MODIFIED:20180213T144506Z
TRANSP:OPAQUE
END:VEVENT
* Barons vs. Biscuits
<2018-05-17 Thu 19:05-22:05>
:PROPERTIES:
:ID:       iKg8GpKH9w8owvcrx1H3Pe8j@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Barons vs. Biscuits Barons vs. Biscuits

Follow on MiLB First Pitch  https //stza.co/+wFVr-C

Shop  https //stza.co/+wFVr-2m

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Barons vs. Biscuits
END:VALARM
DTSTART:20180518T000500Z
DTEND:20180518T030500Z
UID:iKg8GpKH9w8owvcrx1H3Pe8j@stanza.co
SUMMARY:Barons vs. Biscuits
DESCRIPTION:Barons vs. Biscuits\n\nFollow on MiLB First Pitch: https://stza.co/+wFVr-C\n\nShop: https://stza.co/+wFVr-2m\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144506Z
LAST-MODIFIED:20180213T144506Z
TRANSP:OPAQUE
END:VEVENT
* Barons vs. Biscuits
<2018-05-18 Fri 19:05-22:05>
:PROPERTIES:
:ID:       fJZXPGMeoVjuehpc89E3JLSJ@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Barons vs. Biscuits Barons vs. Biscuits

Follow on MiLB First Pitch  https //stza.co/+wFVu-e

Shop  https //stza.co/+wFVu-20

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Barons vs. Biscuits
END:VALARM
DTSTART:20180519T000500Z
DTEND:20180519T030500Z
UID:fJZXPGMeoVjuehpc89E3JLSJ@stanza.co
SUMMARY:Barons vs. Biscuits
DESCRIPTION:Barons vs. Biscuits\n\nFollow on MiLB First Pitch: https://stza.co/+wFVu-e\n\nShop: https://stza.co/+wFVu-20\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144506Z
LAST-MODIFIED:20180213T144506Z
TRANSP:OPAQUE
END:VEVENT
* Barons vs. Biscuits
<2018-05-19 Sat 18:30-21:30>
:PROPERTIES:
:ID:       _xbooY_bJpoWCerQBJcsxLDB@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Barons vs. Biscuits Barons vs. Biscuits

Follow on MiLB First Pitch  https //stza.co/+wFVv-1z

Shop  https //stza.co/+wFVv-2T

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Barons vs. Biscuits
END:VALARM
DTSTART:20180519T233000Z
DTEND:20180520T023000Z
UID:_xbooY_bJpoWCerQBJcsxLDB@stanza.co
SUMMARY:Barons vs. Biscuits
DESCRIPTION:Barons vs. Biscuits\n\nFollow on MiLB First Pitch: https://stza.co/+wFVv-1z\n\nShop: https://stza.co/+wFVv-2T\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144506Z
LAST-MODIFIED:20180213T144506Z
TRANSP:OPAQUE
END:VEVENT
* Barons vs. Biscuits
<2018-05-20 Sun 15:00-18:00>
:PROPERTIES:
:ID:       vljTky1AiNLmIeWqV6WksDK2@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Barons vs. Biscuits Barons vs. Biscuits

Follow on MiLB First Pitch  https //stza.co/+wFVx-25

Shop  https //stza.co/+wFVx-3D

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Barons vs. Biscuits
END:VALARM
DTSTART:20180520T200000Z
DTEND:20180520T230000Z
UID:vljTky1AiNLmIeWqV6WksDK2@stanza.co
SUMMARY:Barons vs. Biscuits
DESCRIPTION:Barons vs. Biscuits\n\nFollow on MiLB First Pitch: https://stza.co/+wFVx-25\n\nShop: https://stza.co/+wFVx-3D\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144506Z
LAST-MODIFIED:20180213T144506Z
TRANSP:OPAQUE
END:VEVENT
* Barons vs. Biscuits
<2018-05-21 Mon 19:05-22:05>
:PROPERTIES:
:ID:       MvriGwl70L_BPSaGfbiLKpaZ@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Barons vs. Biscuits Barons vs. Biscuits

Follow on MiLB First Pitch  https //stza.co/+wFVA-2J

Shop  https //stza.co/+wFVA-3T

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Barons vs. Biscuits
END:VALARM
DTSTART:20180522T000500Z
DTEND:20180522T030500Z
UID:MvriGwl70L_BPSaGfbiLKpaZ@stanza.co
SUMMARY:Barons vs. Biscuits
DESCRIPTION:Barons vs. Biscuits\n\nFollow on MiLB First Pitch: https://stza.co/+wFVA-2J\n\nShop: https://stza.co/+wFVA-3T\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144506Z
LAST-MODIFIED:20180213T144506Z
TRANSP:OPAQUE
END:VEVENT
* Barons @ Generals
<2018-05-23 Wed 18:05-21:05>
:PROPERTIES:
:ID:       4U5wi7laPEW6aKyuWFCxecQc@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Barons @ Generals Barons @ Generals

Follow on MiLB First Pitch  https //stza.co/+wCMT-2X

Shop  https //stza.co/+wCMT-1k

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Barons @ Generals
END:VALARM
DTSTART:20180523T230500Z
DTEND:20180524T020500Z
UID:4U5wi7laPEW6aKyuWFCxecQc@stanza.co
SUMMARY:Barons @ Generals
DESCRIPTION:Barons @ Generals\n\nFollow on MiLB First Pitch: https://stza.co/+wCMT-2X\n\nShop: https://stza.co/+wCMT-1k\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144506Z
LAST-MODIFIED:20180213T144506Z
TRANSP:OPAQUE
END:VEVENT
* Barons @ Generals
<2018-05-24 Thu 18:05-21:05>
:PROPERTIES:
:ID:       S1uExBK_2X7Mvlr2FWEuIZXS@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Barons @ Generals Barons @ Generals

Follow on MiLB First Pitch  https //stza.co/+wCMU-W

Shop  https //stza.co/+wCMU-2Q

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Barons @ Generals
END:VALARM
DTSTART:20180524T230500Z
DTEND:20180525T020500Z
UID:S1uExBK_2X7Mvlr2FWEuIZXS@stanza.co
SUMMARY:Barons @ Generals
DESCRIPTION:Barons @ Generals\n\nFollow on MiLB First Pitch: https://stza.co/+wCMU-W\n\nShop: https://stza.co/+wCMU-2Q\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144506Z
LAST-MODIFIED:20180213T144506Z
TRANSP:OPAQUE
END:VEVENT
* Barons @ Generals
<2018-05-25 Fri 18:05-21:05>
:PROPERTIES:
:ID:       5735J_i5UZIs3frQTdgA0WII@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Barons @ Generals Barons @ Generals

Follow on MiLB First Pitch  https //stza.co/+wCMV-R

Shop  https //stza.co/+wCMV-9

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Barons @ Generals
END:VALARM
DTSTART:20180525T230500Z
DTEND:20180526T020500Z
UID:5735J_i5UZIs3frQTdgA0WII@stanza.co
SUMMARY:Barons @ Generals
DESCRIPTION:Barons @ Generals\n\nFollow on MiLB First Pitch: https://stza.co/+wCMV-R\n\nShop: https://stza.co/+wCMV-9\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144506Z
LAST-MODIFIED:20180213T144506Z
TRANSP:OPAQUE
END:VEVENT
* Barons @ Generals
<2018-05-26 Sat 18:05-21:05>
:PROPERTIES:
:ID:       gJN3Nmqs33M1pmUZ8NzQACKJ@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Barons @ Generals Barons @ Generals

Follow on MiLB First Pitch  https //stza.co/+wCMW-21

Shop  https //stza.co/+wCMW-2K

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Barons @ Generals
END:VALARM
DTSTART:20180526T230500Z
DTEND:20180527T020500Z
UID:gJN3Nmqs33M1pmUZ8NzQACKJ@stanza.co
SUMMARY:Barons @ Generals
DESCRIPTION:Barons @ Generals\n\nFollow on MiLB First Pitch: https://stza.co/+wCMW-21\n\nShop: https://stza.co/+wCMW-2K\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144506Z
LAST-MODIFIED:20180213T144506Z
TRANSP:OPAQUE
END:VEVENT
* Barons @ Generals
<2018-05-27 Sun 14:05-17:05>
:PROPERTIES:
:ID:       5YeFgK6kJG0LAjfGtSjwoWag@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Barons @ Generals Barons @ Generals

Follow on MiLB First Pitch  https //stza.co/+wCMX-2D

Shop  https //stza.co/+wCMX-O

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Barons @ Generals
END:VALARM
DTSTART:20180527T190500Z
DTEND:20180527T220500Z
UID:5YeFgK6kJG0LAjfGtSjwoWag@stanza.co
SUMMARY:Barons @ Generals
DESCRIPTION:Barons @ Generals\n\nFollow on MiLB First Pitch: https://stza.co/+wCMX-2D\n\nShop: https://stza.co/+wCMX-O\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144506Z
LAST-MODIFIED:20180213T144506Z
TRANSP:OPAQUE
END:VEVENT
* Barons vs. Lookouts
<2018-05-29 Tue 19:05-22:05>
:PROPERTIES:
:ID:       Ie0S0VzpFW2wUkQ0iat_dA1f@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Barons vs. Lookouts Barons vs. Lookouts

Follow on MiLB First Pitch  https //stza.co/+wFVC-L

Shop  https //stza.co/+wFVC-33

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Barons vs. Lookouts
END:VALARM
DTSTART:20180530T000500Z
DTEND:20180530T030500Z
UID:Ie0S0VzpFW2wUkQ0iat_dA1f@stanza.co
SUMMARY:Barons vs. Lookouts
DESCRIPTION:Barons vs. Lookouts\n\nFollow on MiLB First Pitch: https://stza.co/+wFVC-L\n\nShop: https://stza.co/+wFVC-33\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144506Z
LAST-MODIFIED:20180213T144506Z
TRANSP:OPAQUE
END:VEVENT
* Barons vs. Lookouts
<2018-05-30 Wed 12:30-15:30>
:PROPERTIES:
:ID:       FxSlUDXFweiCd8zm9y0RnOQx@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Barons vs. Lookouts Barons vs. Lookouts

Follow on MiLB First Pitch  https //stza.co/+wFVE-3j

Shop  https //stza.co/+wFVE-3w

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Barons vs. Lookouts
END:VALARM
DTSTART:20180530T173000Z
DTEND:20180530T203000Z
UID:FxSlUDXFweiCd8zm9y0RnOQx@stanza.co
SUMMARY:Barons vs. Lookouts
DESCRIPTION:Barons vs. Lookouts\n\nFollow on MiLB First Pitch: https://stza.co/+wFVE-3j\n\nShop: https://stza.co/+wFVE-3w\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144506Z
LAST-MODIFIED:20180213T144506Z
TRANSP:OPAQUE
END:VEVENT
* Barons vs. Lookouts
<2018-05-31 Thu 19:05-22:05>
:PROPERTIES:
:ID:       A8FtVzDo-fiaqzPEhaM3YrCD@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Barons vs. Lookouts Barons vs. Lookouts

Follow on MiLB First Pitch  https //stza.co/+wFVG-1A

Shop  https //stza.co/+wFVG-26

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Barons vs. Lookouts
END:VALARM
DTSTART:20180601T000500Z
DTEND:20180601T030500Z
UID:A8FtVzDo-fiaqzPEhaM3YrCD@stanza.co
SUMMARY:Barons vs. Lookouts
DESCRIPTION:Barons vs. Lookouts\n\nFollow on MiLB First Pitch: https://stza.co/+wFVG-1A\n\nShop: https://stza.co/+wFVG-26\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144506Z
LAST-MODIFIED:20180213T144506Z
TRANSP:OPAQUE
END:VEVENT
* Barons vs. Lookouts
<2018-06-01 Fri 19:05-22:05>
:PROPERTIES:
:ID:       IOXA-w15z0Nhyl_grl8qP6i-@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Barons vs. Lookouts Barons vs. Lookouts

Follow on MiLB First Pitch  https //stza.co/+wFVI-B

Shop  https //stza.co/+wFVI-M

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Barons vs. Lookouts
END:VALARM
DTSTART:20180602T000500Z
DTEND:20180602T030500Z
UID:IOXA-w15z0Nhyl_grl8qP6i-@stanza.co
SUMMARY:Barons vs. Lookouts
DESCRIPTION:Barons vs. Lookouts\n\nFollow on MiLB First Pitch: https://stza.co/+wFVI-B\n\nShop: https://stza.co/+wFVI-M\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144506Z
LAST-MODIFIED:20180213T144506Z
TRANSP:OPAQUE
END:VEVENT
* Barons vs. Lookouts
<2018-06-02 Sat 18:30-21:30>
:PROPERTIES:
:ID:       nJ0R20weGaLE-Oz0y6vXmB3L@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Barons vs. Lookouts Barons vs. Lookouts

Follow on MiLB First Pitch  https //stza.co/+wFVK-2G

Shop  https //stza.co/+wFVK-1M

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Barons vs. Lookouts
END:VALARM
DTSTART:20180602T233000Z
DTEND:20180603T023000Z
UID:nJ0R20weGaLE-Oz0y6vXmB3L@stanza.co
SUMMARY:Barons vs. Lookouts
DESCRIPTION:Barons vs. Lookouts\n\nFollow on MiLB First Pitch: https://stza.co/+wFVK-2G\n\nShop: https://stza.co/+wFVK-1M\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144506Z
LAST-MODIFIED:20180213T144506Z
TRANSP:OPAQUE
END:VEVENT
* Barons vs. Jumbo Shrimp
<2018-06-03 Sun 18:00-21:00>
:PROPERTIES:
:ID:       M0NjSlhj2nyMsdXt1yIFARR0@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Barons vs. Jumbo Shrimp Barons vs. Jumbo Shrimp

Follow on MiLB First Pitch  https //stza.co/+wFVL-3i

Shop  https //stza.co/+wFVL-J

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Barons vs. Jumbo Shrimp
END:VALARM
DTSTART:20180603T230000Z
DTEND:20180604T020000Z
UID:M0NjSlhj2nyMsdXt1yIFARR0@stanza.co
SUMMARY:Barons vs. Jumbo Shrimp
DESCRIPTION:Barons vs. Jumbo Shrimp\n\nFollow on MiLB First Pitch: https://stza.co/+wFVL-3i\n\nShop: https://stza.co/+wFVL-J\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144506Z
LAST-MODIFIED:20180213T144506Z
TRANSP:OPAQUE
END:VEVENT
* Barons vs. Jumbo Shrimp
<2018-06-04 Mon 19:05-22:05>
:PROPERTIES:
:ID:       I6hkxjnq8zltOD6TXdhJWVBf@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Barons vs. Jumbo Shrimp Barons vs. Jumbo Shrimp

Follow on MiLB First Pitch  https //stza.co/+wFVO-

Shop  https //stza.co/+wFVO-1B

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Barons vs. Jumbo Shrimp
END:VALARM
DTSTART:20180605T000500Z
DTEND:20180605T030500Z
UID:I6hkxjnq8zltOD6TXdhJWVBf@stanza.co
SUMMARY:Barons vs. Jumbo Shrimp
DESCRIPTION:Barons vs. Jumbo Shrimp\n\nFollow on MiLB First Pitch: https://stza.co/+wFVO-\n\nShop: https://stza.co/+wFVO-1B\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144506Z
LAST-MODIFIED:20180213T144506Z
TRANSP:OPAQUE
END:VEVENT
* Barons vs. Jumbo Shrimp
<2018-06-05 Tue 19:05-22:05>
:PROPERTIES:
:ID:       AWsakrRFRssGRPrOUME772Qz@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Barons vs. Jumbo Shrimp Barons vs. Jumbo Shrimp

Follow on MiLB First Pitch  https //stza.co/+wFVP-y

Shop  https //stza.co/+wFVP-1H

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Barons vs. Jumbo Shrimp
END:VALARM
DTSTART:20180606T000500Z
DTEND:20180606T030500Z
UID:AWsakrRFRssGRPrOUME772Qz@stanza.co
SUMMARY:Barons vs. Jumbo Shrimp
DESCRIPTION:Barons vs. Jumbo Shrimp\n\nFollow on MiLB First Pitch: https://stza.co/+wFVP-y\n\nShop: https://stza.co/+wFVP-1H\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144506Z
LAST-MODIFIED:20180213T144506Z
TRANSP:OPAQUE
END:VEVENT
* Barons vs. Jumbo Shrimp
<2018-06-06 Wed 11:30-14:30>
:PROPERTIES:
:ID:       4u9KgSfbZ_DKNhbtVAmXoo7q@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Barons vs. Jumbo Shrimp Barons vs. Jumbo Shrimp

Follow on MiLB First Pitch  https //stza.co/+wFVS-2$

Shop  https //stza.co/+wFVS-2z

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Barons vs. Jumbo Shrimp
END:VALARM
DTSTART:20180606T163000Z
DTEND:20180606T193000Z
UID:4u9KgSfbZ_DKNhbtVAmXoo7q@stanza.co
SUMMARY:Barons vs. Jumbo Shrimp
DESCRIPTION:Barons vs. Jumbo Shrimp\n\nFollow on MiLB First Pitch: https://stza.co/+wFVS-2$\n\nShop: https://stza.co/+wFVS-2z\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144506Z
LAST-MODIFIED:20180213T144506Z
TRANSP:OPAQUE
END:VEVENT
* Barons vs. Jumbo Shrimp
<2018-06-07 Thu 19:05-22:05>
:PROPERTIES:
:ID:       Mf1o1sjiNKsqlcumINlZU0GX@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Barons vs. Jumbo Shrimp Barons vs. Jumbo Shrimp

Follow on MiLB First Pitch  https //stza.co/+wFVT-2k

Shop  https //stza.co/+wFVT-2G

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Barons vs. Jumbo Shrimp
END:VALARM
DTSTART:20180608T000500Z
DTEND:20180608T030500Z
UID:Mf1o1sjiNKsqlcumINlZU0GX@stanza.co
SUMMARY:Barons vs. Jumbo Shrimp
DESCRIPTION:Barons vs. Jumbo Shrimp\n\nFollow on MiLB First Pitch: https://stza.co/+wFVT-2k\n\nShop: https://stza.co/+wFVT-2G\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144506Z
LAST-MODIFIED:20180213T144506Z
TRANSP:OPAQUE
END:VEVENT
* Barons @ Smokies
<2018-06-08 Fri 18:00-21:00>
:PROPERTIES:
:ID:       sskBevkFgrI9lzqVeO4QTFvi@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Barons @ Smokies Barons @ Smokies

Follow on MiLB First Pitch  https //stza.co/+xVSU-31

Shop  https //stza.co/+xVSU-3X

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Barons @ Smokies
END:VALARM
DTSTART:20180608T230000Z
DTEND:20180609T020000Z
UID:sskBevkFgrI9lzqVeO4QTFvi@stanza.co
SUMMARY:Barons @ Smokies
DESCRIPTION:Barons @ Smokies\n\nFollow on MiLB First Pitch: https://stza.co/+xVSU-31\n\nShop: https://stza.co/+xVSU-3X\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144506Z
LAST-MODIFIED:20180213T144506Z
TRANSP:OPAQUE
END:VEVENT
* Barons @ Smokies
<2018-06-09 Sat 18:00-21:00>
:PROPERTIES:
:ID:       uTu2Ov-SboNimTHo4mzDteS3@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Barons @ Smokies Barons @ Smokies

Follow on MiLB First Pitch  https //stza.co/+xVSV-1Z

Shop  https //stza.co/+xVSV-J

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Barons @ Smokies
END:VALARM
DTSTART:20180609T230000Z
DTEND:20180610T020000Z
UID:uTu2Ov-SboNimTHo4mzDteS3@stanza.co
SUMMARY:Barons @ Smokies
DESCRIPTION:Barons @ Smokies\n\nFollow on MiLB First Pitch: https://stza.co/+xVSV-1Z\n\nShop: https://stza.co/+xVSV-J\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144506Z
LAST-MODIFIED:20180213T144506Z
TRANSP:OPAQUE
END:VEVENT
* Barons @ Smokies
<2018-06-10 Sun 13:00-16:00>
:PROPERTIES:
:ID:       A1YOPRCGGeuWqXnuwrQIqMCV@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Barons @ Smokies Barons @ Smokies

Follow on MiLB First Pitch  https //stza.co/+xVSW-$

Shop  https //stza.co/+xVSW-1O

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Barons @ Smokies
END:VALARM
DTSTART:20180610T180000Z
DTEND:20180610T210000Z
UID:A1YOPRCGGeuWqXnuwrQIqMCV@stanza.co
SUMMARY:Barons @ Smokies
DESCRIPTION:Barons @ Smokies\n\nFollow on MiLB First Pitch: https://stza.co/+xVSW-$\n\nShop: https://stza.co/+xVSW-1O\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144506Z
LAST-MODIFIED:20180213T144506Z
TRANSP:OPAQUE
END:VEVENT
* Barons @ Smokies
<2018-06-11 Mon 18:00-21:00>
:PROPERTIES:
:ID:       4DazdFKQvnZzwi4ZJCZMxERt@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Barons @ Smokies Barons @ Smokies

Follow on MiLB First Pitch  https //stza.co/+xVSX-1W

Shop  https //stza.co/+xVSX-3Q

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Barons @ Smokies
END:VALARM
DTSTART:20180611T230000Z
DTEND:20180612T020000Z
UID:4DazdFKQvnZzwi4ZJCZMxERt@stanza.co
SUMMARY:Barons @ Smokies
DESCRIPTION:Barons @ Smokies\n\nFollow on MiLB First Pitch: https://stza.co/+xVSX-1W\n\nShop: https://stza.co/+xVSX-3Q\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144506Z
LAST-MODIFIED:20180213T144506Z
TRANSP:OPAQUE
END:VEVENT
* Barons @ Smokies
<2018-06-12 Tue 18:00-21:00>
:PROPERTIES:
:ID:       fa6rH03GTrbV151-1uWz8sZd@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Barons @ Smokies Barons @ Smokies

Follow on MiLB First Pitch  https //stza.co/+xVSY-t

Shop  https //stza.co/+xVSY-3P

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Barons @ Smokies
END:VALARM
DTSTART:20180612T230000Z
DTEND:20180613T020000Z
UID:fa6rH03GTrbV151-1uWz8sZd@stanza.co
SUMMARY:Barons @ Smokies
DESCRIPTION:Barons @ Smokies\n\nFollow on MiLB First Pitch: https://stza.co/+xVSY-t\n\nShop: https://stza.co/+xVSY-3P\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144506Z
LAST-MODIFIED:20180213T144506Z
TRANSP:OPAQUE
END:VEVENT
* Barons vs. Lookouts
<2018-06-13 Wed 19:05-22:05>
:PROPERTIES:
:ID:       RJ162H8o9zsb-PHmwL7CQmvO@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Barons vs. Lookouts Barons vs. Lookouts

Follow on MiLB First Pitch  https //stza.co/+wFVV-1Q

Shop  https //stza.co/+wFVV-3k

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Barons vs. Lookouts
END:VALARM
DTSTART:20180614T000500Z
DTEND:20180614T030500Z
UID:RJ162H8o9zsb-PHmwL7CQmvO@stanza.co
SUMMARY:Barons vs. Lookouts
DESCRIPTION:Barons vs. Lookouts\n\nFollow on MiLB First Pitch: https://stza.co/+wFVV-1Q\n\nShop: https://stza.co/+wFVV-3k\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144506Z
LAST-MODIFIED:20180213T144506Z
TRANSP:OPAQUE
END:VEVENT
* Barons vs. Lookouts
<2018-06-14 Thu 19:05-22:05>
:PROPERTIES:
:ID:       SpWkHVfxh4cY4fTKNfJBbjLQ@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Barons vs. Lookouts Barons vs. Lookouts

Follow on MiLB First Pitch  https //stza.co/+wFVY-$

Shop  https //stza.co/+wFVY-11

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Barons vs. Lookouts
END:VALARM
DTSTART:20180615T000500Z
DTEND:20180615T030500Z
UID:SpWkHVfxh4cY4fTKNfJBbjLQ@stanza.co
SUMMARY:Barons vs. Lookouts
DESCRIPTION:Barons vs. Lookouts\n\nFollow on MiLB First Pitch: https://stza.co/+wFVY-$\n\nShop: https://stza.co/+wFVY-11\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144506Z
LAST-MODIFIED:20180213T144506Z
TRANSP:OPAQUE
END:VEVENT
* Barons vs. Lookouts
<2018-06-15 Fri 19:05-22:05>
:PROPERTIES:
:ID:       547y5lTD7h4N_0SJ3Mk3-6oM@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Barons vs. Lookouts Barons vs. Lookouts

Follow on MiLB First Pitch  https //stza.co/+wFV_-2c

Shop  https //stza.co/+wFV_-A

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Barons vs. Lookouts
END:VALARM
DTSTART:20180616T000500Z
DTEND:20180616T030500Z
UID:547y5lTD7h4N_0SJ3Mk3-6oM@stanza.co
SUMMARY:Barons vs. Lookouts
DESCRIPTION:Barons vs. Lookouts\n\nFollow on MiLB First Pitch: https://stza.co/+wFV_-2c\n\nShop: https://stza.co/+wFV_-A\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144506Z
LAST-MODIFIED:20180213T144506Z
TRANSP:OPAQUE
END:VEVENT
* Barons vs. Lookouts
<2018-06-16 Sat 18:30-21:30>
:PROPERTIES:
:ID:       v2iAuxgBYPI-HuYdx0jp-lFD@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Barons vs. Lookouts Barons vs. Lookouts

Follow on MiLB First Pitch  https //stza.co/+wFV$-q

Shop  https //stza.co/+wFV$-t

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Barons vs. Lookouts
END:VALARM
DTSTART:20180616T233000Z
DTEND:20180617T023000Z
UID:v2iAuxgBYPI-HuYdx0jp-lFD@stanza.co
SUMMARY:Barons vs. Lookouts
DESCRIPTION:Barons vs. Lookouts\n\nFollow on MiLB First Pitch: https://stza.co/+wFV$-q\n\nShop: https://stza.co/+wFV$-t\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144506Z
LAST-MODIFIED:20180213T144506Z
TRANSP:OPAQUE
END:VEVENT
* Barons vs. Lookouts
<2018-06-17 Sun 15:00-18:00>
:PROPERTIES:
:ID:       BtzHaRC6lErGyzLfQw6DuTZB@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Barons vs. Lookouts Barons vs. Lookouts

Follow on MiLB First Pitch  https //stza.co/+xM5V-3h

Shop  https //stza.co/+xM5V-1i

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Barons vs. Lookouts
END:VALARM
DTSTART:20180617T200000Z
DTEND:20180617T230000Z
UID:BtzHaRC6lErGyzLfQw6DuTZB@stanza.co
SUMMARY:Barons vs. Lookouts
DESCRIPTION:Barons vs. Lookouts\n\nFollow on MiLB First Pitch: https://stza.co/+xM5V-3h\n\nShop: https://stza.co/+xM5V-1i\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144506Z
LAST-MODIFIED:20180213T144506Z
TRANSP:OPAQUE
END:VEVENT
* Barons @ Biscuits
<2018-06-21 Thu 18:35-21:35>
:PROPERTIES:
:ID:       EigM_OwXKsns4r6IVJp-Ng79@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Barons @ Biscuits Barons @ Biscuits

Follow on MiLB First Pitch  https //stza.co/+vLBy-2I

Shop  https //stza.co/+vLBy-2m

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Barons @ Biscuits
END:VALARM
DTSTART:20180621T233500Z
DTEND:20180622T023500Z
UID:EigM_OwXKsns4r6IVJp-Ng79@stanza.co
SUMMARY:Barons @ Biscuits
DESCRIPTION:Barons @ Biscuits\n\nFollow on MiLB First Pitch: https://stza.co/+vLBy-2I\n\nShop: https://stza.co/+vLBy-2m\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144506Z
LAST-MODIFIED:20180213T144506Z
TRANSP:OPAQUE
END:VEVENT
* Barons @ Biscuits
<2018-06-22 Fri 18:35-21:35>
:PROPERTIES:
:ID:       aY7sWswANcw76yzMk7Qzq5MZ@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Barons @ Biscuits Barons @ Biscuits

Follow on MiLB First Pitch  https //stza.co/+vLBz-X

Shop  https //stza.co/+vLBz-3d

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Barons @ Biscuits
END:VALARM
DTSTART:20180622T233500Z
DTEND:20180623T023500Z
UID:aY7sWswANcw76yzMk7Qzq5MZ@stanza.co
SUMMARY:Barons @ Biscuits
DESCRIPTION:Barons @ Biscuits\n\nFollow on MiLB First Pitch: https://stza.co/+vLBz-X\n\nShop: https://stza.co/+vLBz-3d\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144506Z
LAST-MODIFIED:20180213T144506Z
TRANSP:OPAQUE
END:VEVENT
* Barons @ Biscuits
<2018-06-23 Sat 18:05-21:05>
:PROPERTIES:
:ID:       FAPwRfHRY1jzkHVR-yOCGbx2@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Barons @ Biscuits Barons @ Biscuits

Follow on MiLB First Pitch  https //stza.co/+vLBA-30

Shop  https //stza.co/+vLBA-1R

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Barons @ Biscuits
END:VALARM
DTSTART:20180623T230500Z
DTEND:20180624T020500Z
UID:FAPwRfHRY1jzkHVR-yOCGbx2@stanza.co
SUMMARY:Barons @ Biscuits
DESCRIPTION:Barons @ Biscuits\n\nFollow on MiLB First Pitch: https://stza.co/+vLBA-30\n\nShop: https://stza.co/+vLBA-1R\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144506Z
LAST-MODIFIED:20180213T144506Z
TRANSP:OPAQUE
END:VEVENT
* Barons @ Biscuits
<2018-06-24 Sun 17:05-20:05>
:PROPERTIES:
:ID:       UdZ3zeMki-PC-7iW3BobHy9S@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Barons @ Biscuits Barons @ Biscuits

Follow on MiLB First Pitch  https //stza.co/+vLBB-w

Shop  https //stza.co/+vLBB-3Z

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Barons @ Biscuits
END:VALARM
DTSTART:20180624T220500Z
DTEND:20180625T010500Z
UID:UdZ3zeMki-PC-7iW3BobHy9S@stanza.co
SUMMARY:Barons @ Biscuits
DESCRIPTION:Barons @ Biscuits\n\nFollow on MiLB First Pitch: https://stza.co/+vLBB-w\n\nShop: https://stza.co/+vLBB-3Z\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144506Z
LAST-MODIFIED:20180213T144506Z
TRANSP:OPAQUE
END:VEVENT
* Barons @ Biscuits
<2018-06-25 Mon 18:35-21:35>
:PROPERTIES:
:ID:       wGPnEmuS7konSitybQ25YiVt@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Barons @ Biscuits Barons @ Biscuits

Follow on MiLB First Pitch  https //stza.co/+vLBC-2l

Shop  https //stza.co/+vLBC-3A

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Barons @ Biscuits
END:VALARM
DTSTART:20180625T233500Z
DTEND:20180626T023500Z
UID:wGPnEmuS7konSitybQ25YiVt@stanza.co
SUMMARY:Barons @ Biscuits
DESCRIPTION:Barons @ Biscuits\n\nFollow on MiLB First Pitch: https://stza.co/+vLBC-2l\n\nShop: https://stza.co/+vLBC-3A\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144506Z
LAST-MODIFIED:20180213T144506Z
TRANSP:OPAQUE
END:VEVENT
* Barons @ Biscuits
<2018-06-26 Tue 18:35-21:35>
:PROPERTIES:
:ID:       r8cqWN1ttP-bC_Lagm5Gfi3Q@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Barons @ Biscuits Barons @ Biscuits

Follow on MiLB First Pitch  https //stza.co/+vLBD-1z

Shop  https //stza.co/+vLBD-3f

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Barons @ Biscuits
END:VALARM
DTSTART:20180626T233500Z
DTEND:20180627T023500Z
UID:r8cqWN1ttP-bC_Lagm5Gfi3Q@stanza.co
SUMMARY:Barons @ Biscuits
DESCRIPTION:Barons @ Biscuits\n\nFollow on MiLB First Pitch: https://stza.co/+vLBD-1z\n\nShop: https://stza.co/+vLBD-3f\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144506Z
LAST-MODIFIED:20180213T144506Z
TRANSP:OPAQUE
END:VEVENT
* Barons vs. Generals
<2018-06-28 Thu 19:05-22:05>
:PROPERTIES:
:ID:       HIi2A74Prs_WXqAvFTeQlZYL@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Barons vs. Generals Barons vs. Generals

Follow on MiLB First Pitch  https //stza.co/+wFW3-1g

Shop  https //stza.co/+wFW3-31

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Barons vs. Generals
END:VALARM
DTSTART:20180629T000500Z
DTEND:20180629T030500Z
UID:HIi2A74Prs_WXqAvFTeQlZYL@stanza.co
SUMMARY:Barons vs. Generals
DESCRIPTION:Barons vs. Generals\n\nFollow on MiLB First Pitch: https://stza.co/+wFW3-1g\n\nShop: https://stza.co/+wFW3-31\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144506Z
LAST-MODIFIED:20180213T144506Z
TRANSP:OPAQUE
END:VEVENT
* Barons vs. Generals
<2018-06-29 Fri 19:05-22:05>
:PROPERTIES:
:ID:       tt9LUlKE2uzefDLuGrjIvqJh@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Barons vs. Generals Barons vs. Generals

Follow on MiLB First Pitch  https //stza.co/+wFW6-2L

Shop  https //stza.co/+wFW6-1$

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Barons vs. Generals
END:VALARM
DTSTART:20180630T000500Z
DTEND:20180630T030500Z
UID:tt9LUlKE2uzefDLuGrjIvqJh@stanza.co
SUMMARY:Barons vs. Generals
DESCRIPTION:Barons vs. Generals\n\nFollow on MiLB First Pitch: https://stza.co/+wFW6-2L\n\nShop: https://stza.co/+wFW6-1$\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144506Z
LAST-MODIFIED:20180213T144506Z
TRANSP:OPAQUE
END:VEVENT
* Barons vs. Generals
<2018-06-30 Sat 18:30-21:30>
:PROPERTIES:
:ID:       U9u--3a7wJFfsCYXsPhRnv3g@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Barons vs. Generals Barons vs. Generals

Follow on MiLB First Pitch  https //stza.co/+wFW7-1$

Shop  https //stza.co/+wFW7-Y

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Barons vs. Generals
END:VALARM
DTSTART:20180630T233000Z
DTEND:20180701T023000Z
UID:U9u--3a7wJFfsCYXsPhRnv3g@stanza.co
SUMMARY:Barons vs. Generals
DESCRIPTION:Barons vs. Generals\n\nFollow on MiLB First Pitch: https://stza.co/+wFW7-1$\n\nShop: https://stza.co/+wFW7-Y\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144506Z
LAST-MODIFIED:20180213T144506Z
TRANSP:OPAQUE
END:VEVENT
* Barons vs. Generals
<2018-07-01 Sun 15:00-18:00>
:PROPERTIES:
:ID:       TnXeZyNfLOellZpw2LaCYp2f@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Barons vs. Generals Barons vs. Generals

Follow on MiLB First Pitch  https //stza.co/+wFWa-1

Shop  https //stza.co/+wFWa-1S

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Barons vs. Generals
END:VALARM
DTSTART:20180701T200000Z
DTEND:20180701T230000Z
UID:TnXeZyNfLOellZpw2LaCYp2f@stanza.co
SUMMARY:Barons vs. Generals
DESCRIPTION:Barons vs. Generals\n\nFollow on MiLB First Pitch: https://stza.co/+wFWa-1\n\nShop: https://stza.co/+wFWa-1S\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144506Z
LAST-MODIFIED:20180213T144506Z
TRANSP:OPAQUE
END:VEVENT
* Barons vs. Generals
<2018-07-02 Mon 19:05-22:05>
:PROPERTIES:
:ID:       NSPNRq3HzPENbRqpegcEkB_G@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Barons vs. Generals Barons vs. Generals

Follow on MiLB First Pitch  https //stza.co/+wFWb-17

Shop  https //stza.co/+wFWb-2I

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Barons vs. Generals
END:VALARM
DTSTART:20180703T000500Z
DTEND:20180703T030500Z
UID:NSPNRq3HzPENbRqpegcEkB_G@stanza.co
SUMMARY:Barons vs. Generals
DESCRIPTION:Barons vs. Generals\n\nFollow on MiLB First Pitch: https://stza.co/+wFWb-17\n\nShop: https://stza.co/+wFWb-2I\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144506Z
LAST-MODIFIED:20180213T144506Z
TRANSP:OPAQUE
END:VEVENT
* Barons vs. Generals
<2018-07-03 Tue 18:30-21:30>
:PROPERTIES:
:ID:       9BL5Q6rLpzDObVS9VF2KbKPj@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Barons vs. Generals Barons vs. Generals

Follow on MiLB First Pitch  https //stza.co/+xM5X-y

Shop  https //stza.co/+xM5X-2n

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Barons vs. Generals
END:VALARM
DTSTART:20180703T233000Z
DTEND:20180704T023000Z
UID:9BL5Q6rLpzDObVS9VF2KbKPj@stanza.co
SUMMARY:Barons vs. Generals
DESCRIPTION:Barons vs. Generals\n\nFollow on MiLB First Pitch: https://stza.co/+xM5X-y\n\nShop: https://stza.co/+xM5X-2n\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144506Z
LAST-MODIFIED:20180213T144506Z
TRANSP:OPAQUE
END:VEVENT
* Barons @ Lookouts
<2018-07-04 Wed 17:15-20:15>
:PROPERTIES:
:ID:       xRX-gf16PXGe-bZBvtarU2sH@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Barons @ Lookouts Barons @ Lookouts

Follow on MiLB First Pitch  https //stza.co/+wKBv-1$

Shop  https //stza.co/+wKBv-2m

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Barons @ Lookouts
END:VALARM
DTSTART:20180704T221500Z
DTEND:20180705T011500Z
UID:xRX-gf16PXGe-bZBvtarU2sH@stanza.co
SUMMARY:Barons @ Lookouts
DESCRIPTION:Barons @ Lookouts\n\nFollow on MiLB First Pitch: https://stza.co/+wKBv-1$\n\nShop: https://stza.co/+wKBv-2m\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144506Z
LAST-MODIFIED:20180213T144506Z
TRANSP:OPAQUE
END:VEVENT
* Barons @ Lookouts
<2018-07-05 Thu 18:15-21:15>
:PROPERTIES:
:ID:       DYxXP_WvGmixG87t7zdJojot@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Barons @ Lookouts Barons @ Lookouts

Follow on MiLB First Pitch  https //stza.co/+wKBw-x

Shop  https //stza.co/+wKBw-9

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Barons @ Lookouts
END:VALARM
DTSTART:20180705T231500Z
DTEND:20180706T021500Z
UID:DYxXP_WvGmixG87t7zdJojot@stanza.co
SUMMARY:Barons @ Lookouts
DESCRIPTION:Barons @ Lookouts\n\nFollow on MiLB First Pitch: https://stza.co/+wKBw-x\n\nShop: https://stza.co/+wKBw-9\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144506Z
LAST-MODIFIED:20180213T144506Z
TRANSP:OPAQUE
END:VEVENT
* Barons @ Lookouts
<2018-07-06 Fri 18:15-21:15>
:PROPERTIES:
:ID:       CONeSj05dYSnCXou8AwHkZQJ@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Barons @ Lookouts Barons @ Lookouts

Follow on MiLB First Pitch  https //stza.co/+wKBx-9

Shop  https //stza.co/+wKBx-34

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Barons @ Lookouts
END:VALARM
DTSTART:20180706T231500Z
DTEND:20180707T021500Z
UID:CONeSj05dYSnCXou8AwHkZQJ@stanza.co
SUMMARY:Barons @ Lookouts
DESCRIPTION:Barons @ Lookouts\n\nFollow on MiLB First Pitch: https://stza.co/+wKBx-9\n\nShop: https://stza.co/+wKBx-34\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144506Z
LAST-MODIFIED:20180213T144506Z
TRANSP:OPAQUE
END:VEVENT
* Barons @ Lookouts
<2018-07-07 Sat 18:15-21:15>
:PROPERTIES:
:ID:       AptJkWEs58J7ZhcFpmmtPFWY@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Barons @ Lookouts Barons @ Lookouts

Follow on MiLB First Pitch  https //stza.co/+wKBy-21

Shop  https //stza.co/+wKBy-16

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Barons @ Lookouts
END:VALARM
DTSTART:20180707T231500Z
DTEND:20180708T021500Z
UID:AptJkWEs58J7ZhcFpmmtPFWY@stanza.co
SUMMARY:Barons @ Lookouts
DESCRIPTION:Barons @ Lookouts\n\nFollow on MiLB First Pitch: https://stza.co/+wKBy-21\n\nShop: https://stza.co/+wKBy-16\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144506Z
LAST-MODIFIED:20180213T144506Z
TRANSP:OPAQUE
END:VEVENT
* Barons vs. Braves
<2018-07-08 Sun 18:00-21:00>
:PROPERTIES:
:ID:       I4oy5_V1VN-7YZmx1I4Qijtx@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Barons vs. Braves Barons vs. Braves

Follow on MiLB First Pitch  https //stza.co/+wFWg-_

Shop  https //stza.co/+wFWg-2w

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Barons vs. Braves
END:VALARM
DTSTART:20180708T230000Z
DTEND:20180709T020000Z
UID:I4oy5_V1VN-7YZmx1I4Qijtx@stanza.co
SUMMARY:Barons vs. Braves
DESCRIPTION:Barons vs. Braves\n\nFollow on MiLB First Pitch: https://stza.co/+wFWg-_\n\nShop: https://stza.co/+wFWg-2w\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144506Z
LAST-MODIFIED:20180213T144506Z
TRANSP:OPAQUE
END:VEVENT
* Barons vs. Braves
<2018-07-09 Mon 19:05-22:05>
:PROPERTIES:
:ID:       -LMQS7cqIbsZZCw1o1iw-vo3@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Barons vs. Braves Barons vs. Braves

Follow on MiLB First Pitch  https //stza.co/+wFWi-2p

Shop  https //stza.co/+wFWi-3_

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Barons vs. Braves
END:VALARM
DTSTART:20180710T000500Z
DTEND:20180710T030500Z
UID:-LMQS7cqIbsZZCw1o1iw-vo3@stanza.co
SUMMARY:Barons vs. Braves
DESCRIPTION:Barons vs. Braves\n\nFollow on MiLB First Pitch: https://stza.co/+wFWi-2p\n\nShop: https://stza.co/+wFWi-3_\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144506Z
LAST-MODIFIED:20180213T144506Z
TRANSP:OPAQUE
END:VEVENT
* Barons vs. Braves
<2018-07-10 Tue 19:05-22:05>
:PROPERTIES:
:ID:       YD5G8k4TWeq-EAM-rI0XA5Ht@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Barons vs. Braves Barons vs. Braves

Follow on MiLB First Pitch  https //stza.co/+wFWj-7

Shop  https //stza.co/+wFWj-2v

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Barons vs. Braves
END:VALARM
DTSTART:20180711T000500Z
DTEND:20180711T030500Z
UID:YD5G8k4TWeq-EAM-rI0XA5Ht@stanza.co
SUMMARY:Barons vs. Braves
DESCRIPTION:Barons vs. Braves\n\nFollow on MiLB First Pitch: https://stza.co/+wFWj-7\n\nShop: https://stza.co/+wFWj-2v\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144506Z
LAST-MODIFIED:20180213T144506Z
TRANSP:OPAQUE
END:VEVENT
* Barons vs. Braves
<2018-07-11 Wed 19:05-22:05>
:PROPERTIES:
:ID:       w6RPuXOXNfWjyTR3gRppMOyY@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Barons vs. Braves Barons vs. Braves

Follow on MiLB First Pitch  https //stza.co/+wFWl-27

Shop  https //stza.co/+wFWl-p

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Barons vs. Braves
END:VALARM
DTSTART:20180712T000500Z
DTEND:20180712T030500Z
UID:w6RPuXOXNfWjyTR3gRppMOyY@stanza.co
SUMMARY:Barons vs. Braves
DESCRIPTION:Barons vs. Braves\n\nFollow on MiLB First Pitch: https://stza.co/+wFWl-27\n\nShop: https://stza.co/+wFWl-p\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144506Z
LAST-MODIFIED:20180213T144506Z
TRANSP:OPAQUE
END:VEVENT
* Barons @ Smokies
<2018-07-12 Thu 18:00-21:00>
:PROPERTIES:
:ID:       rx0Qifd0fFxTfjPdb92nnvB8@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Barons @ Smokies Barons @ Smokies

Follow on MiLB First Pitch  https //stza.co/+xVSZ-2B

Shop  https //stza.co/+xVSZ-2H

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Barons @ Smokies
END:VALARM
DTSTART:20180712T230000Z
DTEND:20180713T020000Z
UID:rx0Qifd0fFxTfjPdb92nnvB8@stanza.co
SUMMARY:Barons @ Smokies
DESCRIPTION:Barons @ Smokies\n\nFollow on MiLB First Pitch: https://stza.co/+xVSZ-2B\n\nShop: https://stza.co/+xVSZ-2H\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144506Z
LAST-MODIFIED:20180213T144506Z
TRANSP:OPAQUE
END:VEVENT
* Barons @ Smokies
<2018-07-13 Fri 18:00-21:00>
:PROPERTIES:
:ID:       R3O3YD4rpjmAyv7NGHQyePW8@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Barons @ Smokies Barons @ Smokies

Follow on MiLB First Pitch  https //stza.co/+xVS_-1s

Shop  https //stza.co/+xVS_-2n

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Barons @ Smokies
END:VALARM
DTSTART:20180713T230000Z
DTEND:20180714T020000Z
UID:R3O3YD4rpjmAyv7NGHQyePW8@stanza.co
SUMMARY:Barons @ Smokies
DESCRIPTION:Barons @ Smokies\n\nFollow on MiLB First Pitch: https://stza.co/+xVS_-1s\n\nShop: https://stza.co/+xVS_-2n\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144506Z
LAST-MODIFIED:20180213T144506Z
TRANSP:OPAQUE
END:VEVENT
* Barons @ Smokies
<2018-07-14 Sat 18:00-21:00>
:PROPERTIES:
:ID:       omiqs8v5RLY0B2sXWrRLCeca@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Barons @ Smokies Barons @ Smokies

Follow on MiLB First Pitch  https //stza.co/+xVS$-H

Shop  https //stza.co/+xVS$-j

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Barons @ Smokies
END:VALARM
DTSTART:20180714T230000Z
DTEND:20180715T020000Z
UID:omiqs8v5RLY0B2sXWrRLCeca@stanza.co
SUMMARY:Barons @ Smokies
DESCRIPTION:Barons @ Smokies\n\nFollow on MiLB First Pitch: https://stza.co/+xVS$-H\n\nShop: https://stza.co/+xVS$-j\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144506Z
LAST-MODIFIED:20180213T144506Z
TRANSP:OPAQUE
END:VEVENT
* Barons @ Smokies
<2018-07-15 Sun 16:30-19:30>
:PROPERTIES:
:ID:       bSI89V2A7svGmjA5HrEbYxxl@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Barons @ Smokies Barons @ Smokies

Follow on MiLB First Pitch  https //stza.co/+xVT0-2r

Shop  https //stza.co/+xVT0-1W

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Barons @ Smokies
END:VALARM
DTSTART:20180715T213000Z
DTEND:20180716T003000Z
UID:bSI89V2A7svGmjA5HrEbYxxl@stanza.co
SUMMARY:Barons @ Smokies
DESCRIPTION:Barons @ Smokies\n\nFollow on MiLB First Pitch: https://stza.co/+xVT0-2r\n\nShop: https://stza.co/+xVT0-1W\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144506Z
LAST-MODIFIED:20180213T144506Z
TRANSP:OPAQUE
END:VEVENT
* Barons @ Smokies
<2018-07-16 Mon 18:00-21:00>
:PROPERTIES:
:ID:       D-jLnBoWd-_kbQwF5eoi2E0u@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Barons @ Smokies Barons @ Smokies

Follow on MiLB First Pitch  https //stza.co/+xVT2-2N

Shop  https //stza.co/+xVT2-1g

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Barons @ Smokies
END:VALARM
DTSTART:20180716T230000Z
DTEND:20180717T020000Z
UID:D-jLnBoWd-_kbQwF5eoi2E0u@stanza.co
SUMMARY:Barons @ Smokies
DESCRIPTION:Barons @ Smokies\n\nFollow on MiLB First Pitch: https://stza.co/+xVT2-2N\n\nShop: https://stza.co/+xVT2-1g\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144506Z
LAST-MODIFIED:20180213T144506Z
TRANSP:OPAQUE
END:VEVENT
* Barons vs. Generals
<2018-07-18 Wed 19:05-22:05>
:PROPERTIES:
:ID:       Fzq9leZSAeCKhkvxM2lrN44C@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Barons vs. Generals Barons vs. Generals

Follow on MiLB First Pitch  https //stza.co/+wFWn-X

Shop  https //stza.co/+wFWn-3d

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Barons vs. Generals
END:VALARM
DTSTART:20180719T000500Z
DTEND:20180719T030500Z
UID:Fzq9leZSAeCKhkvxM2lrN44C@stanza.co
SUMMARY:Barons vs. Generals
DESCRIPTION:Barons vs. Generals\n\nFollow on MiLB First Pitch: https://stza.co/+wFWn-X\n\nShop: https://stza.co/+wFWn-3d\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144506Z
LAST-MODIFIED:20180213T144506Z
TRANSP:OPAQUE
END:VEVENT
* Barons vs. Generals
<2018-07-19 Thu 19:05-22:05>
:PROPERTIES:
:ID:       ZNyVzkQTRpf1aQgAHWA5BEF3@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Barons vs. Generals Barons vs. Generals

Follow on MiLB First Pitch  https //stza.co/+wFWq-h

Shop  https //stza.co/+wFWq-J

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Barons vs. Generals
END:VALARM
DTSTART:20180720T000500Z
DTEND:20180720T030500Z
UID:ZNyVzkQTRpf1aQgAHWA5BEF3@stanza.co
SUMMARY:Barons vs. Generals
DESCRIPTION:Barons vs. Generals\n\nFollow on MiLB First Pitch: https://stza.co/+wFWq-h\n\nShop: https://stza.co/+wFWq-J\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144506Z
LAST-MODIFIED:20180213T144506Z
TRANSP:OPAQUE
END:VEVENT
* Barons vs. Generals
<2018-07-20 Fri 19:05-22:05>
:PROPERTIES:
:ID:       LTYskF2-pO1srrnfJwLKhXOQ@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Barons vs. Generals Barons vs. Generals

Follow on MiLB First Pitch  https //stza.co/+wFWs-2n

Shop  https //stza.co/+wFWs-u

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Barons vs. Generals
END:VALARM
DTSTART:20180721T000500Z
DTEND:20180721T030500Z
UID:LTYskF2-pO1srrnfJwLKhXOQ@stanza.co
SUMMARY:Barons vs. Generals
DESCRIPTION:Barons vs. Generals\n\nFollow on MiLB First Pitch: https://stza.co/+wFWs-2n\n\nShop: https://stza.co/+wFWs-u\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144506Z
LAST-MODIFIED:20180213T144506Z
TRANSP:OPAQUE
END:VEVENT
* Barons vs. Generals
<2018-07-21 Sat 18:30-21:30>
:PROPERTIES:
:ID:       XdfICRjZt5IE42LJQx0av_Q3@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Barons vs. Generals Barons vs. Generals

Follow on MiLB First Pitch  https //stza.co/+wFWu-e

Shop  https //stza.co/+wFWu-3D

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Barons vs. Generals
END:VALARM
DTSTART:20180721T233000Z
DTEND:20180722T023000Z
UID:XdfICRjZt5IE42LJQx0av_Q3@stanza.co
SUMMARY:Barons vs. Generals
DESCRIPTION:Barons vs. Generals\n\nFollow on MiLB First Pitch: https://stza.co/+wFWu-e\n\nShop: https://stza.co/+wFWu-3D\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144506Z
LAST-MODIFIED:20180213T144506Z
TRANSP:OPAQUE
END:VEVENT
* Barons vs. Generals
<2018-07-22 Sun 15:00-18:00>
:PROPERTIES:
:ID:       T7Fk_Mr6Vtn1moUl_jy3rU5D@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Barons vs. Generals Barons vs. Generals

Follow on MiLB First Pitch  https //stza.co/+wFWw-D

Shop  https //stza.co/+wFWw-2d

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Barons vs. Generals
END:VALARM
DTSTART:20180722T200000Z
DTEND:20180722T230000Z
UID:T7Fk_Mr6Vtn1moUl_jy3rU5D@stanza.co
SUMMARY:Barons vs. Generals
DESCRIPTION:Barons vs. Generals\n\nFollow on MiLB First Pitch: https://stza.co/+wFWw-D\n\nShop: https://stza.co/+wFWw-2d\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144506Z
LAST-MODIFIED:20180213T144506Z
TRANSP:OPAQUE
END:VEVENT
* Barons vs. Smokies
<2018-07-23 Mon 19:05-22:05>
:PROPERTIES:
:ID:       f7uW25lAV_zh2b5aKHsYXLuy@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Barons vs. Smokies Barons vs. Smokies

Follow on MiLB First Pitch  https //stza.co/+wFWy-20

Shop  https //stza.co/+wFWy-2m

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Barons vs. Smokies
END:VALARM
DTSTART:20180724T000500Z
DTEND:20180724T030500Z
UID:f7uW25lAV_zh2b5aKHsYXLuy@stanza.co
SUMMARY:Barons vs. Smokies
DESCRIPTION:Barons vs. Smokies\n\nFollow on MiLB First Pitch: https://stza.co/+wFWy-20\n\nShop: https://stza.co/+wFWy-2m\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144506Z
LAST-MODIFIED:20180213T144506Z
TRANSP:OPAQUE
END:VEVENT
* Barons vs. Smokies
<2018-07-24 Tue 19:05-22:05>
:PROPERTIES:
:ID:       ZfTv3novL2xlFqcgrIEfhMS2@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Barons vs. Smokies Barons vs. Smokies

Follow on MiLB First Pitch  https //stza.co/+wFWz-h

Shop  https //stza.co/+wFWz-1$

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Barons vs. Smokies
END:VALARM
DTSTART:20180725T000500Z
DTEND:20180725T030500Z
UID:ZfTv3novL2xlFqcgrIEfhMS2@stanza.co
SUMMARY:Barons vs. Smokies
DESCRIPTION:Barons vs. Smokies\n\nFollow on MiLB First Pitch: https://stza.co/+wFWz-h\n\nShop: https://stza.co/+wFWz-1$\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144506Z
LAST-MODIFIED:20180213T144506Z
TRANSP:OPAQUE
END:VEVENT
* Barons vs. Smokies
<2018-07-25 Wed 19:05-22:05>
:PROPERTIES:
:ID:       lSoR_IdnAwU3y3LGaEX9rATO@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Barons vs. Smokies Barons vs. Smokies

Follow on MiLB First Pitch  https //stza.co/+wFWB-2U

Shop  https //stza.co/+wFWB-2b

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Barons vs. Smokies
END:VALARM
DTSTART:20180726T000500Z
DTEND:20180726T030500Z
UID:lSoR_IdnAwU3y3LGaEX9rATO@stanza.co
SUMMARY:Barons vs. Smokies
DESCRIPTION:Barons vs. Smokies\n\nFollow on MiLB First Pitch: https://stza.co/+wFWB-2U\n\nShop: https://stza.co/+wFWB-2b\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144506Z
LAST-MODIFIED:20180213T144506Z
TRANSP:OPAQUE
END:VEVENT
* Barons vs. Smokies
<2018-07-26 Thu 19:05-22:05>
:PROPERTIES:
:ID:       tnmjRzbGntXeKoSH5j0Q0IrG@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Barons vs. Smokies Barons vs. Smokies

Follow on MiLB First Pitch  https //stza.co/+wFWE-22

Shop  https //stza.co/+wFWE-2J

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Barons vs. Smokies
END:VALARM
DTSTART:20180727T000500Z
DTEND:20180727T030500Z
UID:tnmjRzbGntXeKoSH5j0Q0IrG@stanza.co
SUMMARY:Barons vs. Smokies
DESCRIPTION:Barons vs. Smokies\n\nFollow on MiLB First Pitch: https://stza.co/+wFWE-22\n\nShop: https://stza.co/+wFWE-2J\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144506Z
LAST-MODIFIED:20180213T144506Z
TRANSP:OPAQUE
END:VEVENT
* Barons vs. Smokies
<2018-07-27 Fri 19:05-22:05>
:PROPERTIES:
:ID:       29LMn8C-3sCBQbMucnK4qNqf@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Barons vs. Smokies Barons vs. Smokies

Follow on MiLB First Pitch  https //stza.co/+wFWF-g

Shop  https //stza.co/+wFWF-2F

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Barons vs. Smokies
END:VALARM
DTSTART:20180728T000500Z
DTEND:20180728T030500Z
UID:29LMn8C-3sCBQbMucnK4qNqf@stanza.co
SUMMARY:Barons vs. Smokies
DESCRIPTION:Barons vs. Smokies\n\nFollow on MiLB First Pitch: https://stza.co/+wFWF-g\n\nShop: https://stza.co/+wFWF-2F\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144506Z
LAST-MODIFIED:20180213T144506Z
TRANSP:OPAQUE
END:VEVENT
* Barons @ Braves
<2018-07-28 Sat 18:00-21:00>
:PROPERTIES:
:ID:       vgPEq88jHAF6B-cZInrHxA4I@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Barons @ Braves Barons @ Braves

Follow on MiLB First Pitch  https //stza.co/+vLBo-d

Shop  https //stza.co/+vLBo-1j

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Barons @ Braves
END:VALARM
DTSTART:20180728T230000Z
DTEND:20180729T020000Z
UID:vgPEq88jHAF6B-cZInrHxA4I@stanza.co
SUMMARY:Barons @ Braves
DESCRIPTION:Barons @ Braves\n\nFollow on MiLB First Pitch: https://stza.co/+vLBo-d\n\nShop: https://stza.co/+vLBo-1j\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144506Z
LAST-MODIFIED:20180213T144506Z
TRANSP:OPAQUE
END:VEVENT
* Barons @ Braves
<2018-07-29 Sun 17:00-20:00>
:PROPERTIES:
:ID:       92dQU7dKbQjb5o2hiIBMdqN8@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Barons @ Braves Barons @ Braves

Follow on MiLB First Pitch  https //stza.co/+vLBp-a

Shop  https //stza.co/+vLBp-V

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Barons @ Braves
END:VALARM
DTSTART:20180729T220000Z
DTEND:20180730T010000Z
UID:92dQU7dKbQjb5o2hiIBMdqN8@stanza.co
SUMMARY:Barons @ Braves
DESCRIPTION:Barons @ Braves\n\nFollow on MiLB First Pitch: https://stza.co/+vLBp-a\n\nShop: https://stza.co/+vLBp-V\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144506Z
LAST-MODIFIED:20180213T144506Z
TRANSP:OPAQUE
END:VEVENT
* Barons @ Braves
<2018-07-30 Mon 19:00-22:00>
:PROPERTIES:
:ID:       wba2C5tJ2Oe9Hiq4gFvxf0k_@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Barons @ Braves Barons @ Braves

Follow on MiLB First Pitch  https //stza.co/+vLBq-1u

Shop  https //stza.co/+vLBq-2p

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Barons @ Braves
END:VALARM
DTSTART:20180731T000000Z
DTEND:20180731T030000Z
UID:wba2C5tJ2Oe9Hiq4gFvxf0k_@stanza.co
SUMMARY:Barons @ Braves
DESCRIPTION:Barons @ Braves\n\nFollow on MiLB First Pitch: https://stza.co/+vLBq-1u\n\nShop: https://stza.co/+vLBq-2p\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144506Z
LAST-MODIFIED:20180213T144506Z
TRANSP:OPAQUE
END:VEVENT
* Barons @ Braves
<2018-07-31 Tue 19:00-22:00>
:PROPERTIES:
:ID:       _9gVKU4tuM7neiq8yrG8lclB@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Barons @ Braves Barons @ Braves

Follow on MiLB First Pitch  https //stza.co/+vLBr-32

Shop  https //stza.co/+vLBr-1N

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Barons @ Braves
END:VALARM
DTSTART:20180801T000000Z
DTEND:20180801T030000Z
UID:_9gVKU4tuM7neiq8yrG8lclB@stanza.co
SUMMARY:Barons @ Braves
DESCRIPTION:Barons @ Braves\n\nFollow on MiLB First Pitch: https://stza.co/+vLBr-32\n\nShop: https://stza.co/+vLBr-1N\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144506Z
LAST-MODIFIED:20180213T144506Z
TRANSP:OPAQUE
END:VEVENT
* Barons @ Braves
<2018-08-01 Wed 19:00-22:00>
:PROPERTIES:
:ID:       4QK-mw3QAZCvX0j8mGQCsgk3@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Barons @ Braves Barons @ Braves

Follow on MiLB First Pitch  https //stza.co/+vLBs-3v

Shop  https //stza.co/+vLBs-1H

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Barons @ Braves
END:VALARM
DTSTART:20180802T000000Z
DTEND:20180802T030000Z
UID:4QK-mw3QAZCvX0j8mGQCsgk3@stanza.co
SUMMARY:Barons @ Braves
DESCRIPTION:Barons @ Braves\n\nFollow on MiLB First Pitch: https://stza.co/+vLBs-3v\n\nShop: https://stza.co/+vLBs-1H\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144506Z
LAST-MODIFIED:20180213T144506Z
TRANSP:OPAQUE
END:VEVENT
* Barons vs. BayBears
<2018-08-02 Thu 19:05-22:05>
:PROPERTIES:
:ID:       Gw8BNa6bb1c52QETl54UrqI8@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Barons vs. BayBears Barons vs. BayBears

Follow on MiLB First Pitch  https //stza.co/+wFWH-28

Shop  https //stza.co/+wFWH-1i

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Barons vs. BayBears
END:VALARM
DTSTART:20180803T000500Z
DTEND:20180803T030500Z
UID:Gw8BNa6bb1c52QETl54UrqI8@stanza.co
SUMMARY:Barons vs. BayBears
DESCRIPTION:Barons vs. BayBears\n\nFollow on MiLB First Pitch: https://stza.co/+wFWH-28\n\nShop: https://stza.co/+wFWH-1i\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144506Z
LAST-MODIFIED:20180213T144506Z
TRANSP:OPAQUE
END:VEVENT
* Barons vs. BayBears
<2018-08-03 Fri 19:05-22:05>
:PROPERTIES:
:ID:       TJwG-jVb4wvja0vKqaf7s42w@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Barons vs. BayBears Barons vs. BayBears

Follow on MiLB First Pitch  https //stza.co/+wFWJ-2g

Shop  https //stza.co/+wFWJ-7

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Barons vs. BayBears
END:VALARM
DTSTART:20180804T000500Z
DTEND:20180804T030500Z
UID:TJwG-jVb4wvja0vKqaf7s42w@stanza.co
SUMMARY:Barons vs. BayBears
DESCRIPTION:Barons vs. BayBears\n\nFollow on MiLB First Pitch: https://stza.co/+wFWJ-2g\n\nShop: https://stza.co/+wFWJ-7\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144506Z
LAST-MODIFIED:20180213T144506Z
TRANSP:OPAQUE
END:VEVENT
* Barons vs. BayBears
<2018-08-04 Sat 18:30-21:30>
:PROPERTIES:
:ID:       -6ZJ_XQmNiJ0vK7LFO2sO4d4@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Barons vs. BayBears Barons vs. BayBears

Follow on MiLB First Pitch  https //stza.co/+wFWM-1r

Shop  https //stza.co/+wFWM-2Q

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Barons vs. BayBears
END:VALARM
DTSTART:20180804T233000Z
DTEND:20180805T023000Z
UID:-6ZJ_XQmNiJ0vK7LFO2sO4d4@stanza.co
SUMMARY:Barons vs. BayBears
DESCRIPTION:Barons vs. BayBears\n\nFollow on MiLB First Pitch: https://stza.co/+wFWM-1r\n\nShop: https://stza.co/+wFWM-2Q\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144506Z
LAST-MODIFIED:20180213T144506Z
TRANSP:OPAQUE
END:VEVENT
* Barons vs. BayBears
<2018-08-05 Sun 15:00-18:00>
:PROPERTIES:
:ID:       mMQSaXi22V6f_oKhNoeuEslA@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Barons vs. BayBears Barons vs. BayBears

Follow on MiLB First Pitch  https //stza.co/+wFWO-$

Shop  https //stza.co/+wFWO-1p

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Barons vs. BayBears
END:VALARM
DTSTART:20180805T200000Z
DTEND:20180805T230000Z
UID:mMQSaXi22V6f_oKhNoeuEslA@stanza.co
SUMMARY:Barons vs. BayBears
DESCRIPTION:Barons vs. BayBears\n\nFollow on MiLB First Pitch: https://stza.co/+wFWO-$\n\nShop: https://stza.co/+wFWO-1p\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144506Z
LAST-MODIFIED:20180213T144506Z
TRANSP:OPAQUE
END:VEVENT
* Barons vs. BayBears
<2018-08-06 Mon 19:05-22:05>
:PROPERTIES:
:ID:       _or5OMBTgtNHctAu2IqvaMNB@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Barons vs. BayBears Barons vs. BayBears

Follow on MiLB First Pitch  https //stza.co/+wFWQ-1K

Shop  https //stza.co/+wFWQ-2C

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Barons vs. BayBears
END:VALARM
DTSTART:20180807T000500Z
DTEND:20180807T030500Z
UID:_or5OMBTgtNHctAu2IqvaMNB@stanza.co
SUMMARY:Barons vs. BayBears
DESCRIPTION:Barons vs. BayBears\n\nFollow on MiLB First Pitch: https://stza.co/+wFWQ-1K\n\nShop: https://stza.co/+wFWQ-2C\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144506Z
LAST-MODIFIED:20180213T144506Z
TRANSP:OPAQUE
END:VEVENT
* Barons @ Biscuits
<2018-08-08 Wed 18:35-21:35>
:PROPERTIES:
:ID:       FdhBfu2gxuUWPvxdVyfCpne9@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Barons @ Biscuits Barons @ Biscuits

Follow on MiLB First Pitch  https //stza.co/+vLBE-1k

Shop  https //stza.co/+vLBE-I

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Barons @ Biscuits
END:VALARM
DTSTART:20180808T233500Z
DTEND:20180809T023500Z
UID:FdhBfu2gxuUWPvxdVyfCpne9@stanza.co
SUMMARY:Barons @ Biscuits
DESCRIPTION:Barons @ Biscuits\n\nFollow on MiLB First Pitch: https://stza.co/+vLBE-1k\n\nShop: https://stza.co/+vLBE-I\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144506Z
LAST-MODIFIED:20180213T144506Z
TRANSP:OPAQUE
END:VEVENT
* Barons @ Biscuits
<2018-08-09 Thu 18:35-21:35>
:PROPERTIES:
:ID:       u9juw8MhJTV3B-0_Gqa6SQdh@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Barons @ Biscuits Barons @ Biscuits

Follow on MiLB First Pitch  https //stza.co/+vLBF-2C

Shop  https //stza.co/+vLBF-2m

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Barons @ Biscuits
END:VALARM
DTSTART:20180809T233500Z
DTEND:20180810T023500Z
UID:u9juw8MhJTV3B-0_Gqa6SQdh@stanza.co
SUMMARY:Barons @ Biscuits
DESCRIPTION:Barons @ Biscuits\n\nFollow on MiLB First Pitch: https://stza.co/+vLBF-2C\n\nShop: https://stza.co/+vLBF-2m\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144506Z
LAST-MODIFIED:20180213T144506Z
TRANSP:OPAQUE
END:VEVENT
* Barons @ Biscuits
<2018-08-10 Fri 18:35-21:35>
:PROPERTIES:
:ID:       aPAFTYNJI-MMP_oKxLwXMqGv@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Barons @ Biscuits Barons @ Biscuits

Follow on MiLB First Pitch  https //stza.co/+vLBG-20

Shop  https //stza.co/+vLBG-3k

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Barons @ Biscuits
END:VALARM
DTSTART:20180810T233500Z
DTEND:20180811T023500Z
UID:aPAFTYNJI-MMP_oKxLwXMqGv@stanza.co
SUMMARY:Barons @ Biscuits
DESCRIPTION:Barons @ Biscuits\n\nFollow on MiLB First Pitch: https://stza.co/+vLBG-20\n\nShop: https://stza.co/+vLBG-3k\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144506Z
LAST-MODIFIED:20180213T144506Z
TRANSP:OPAQUE
END:VEVENT
* Barons @ Biscuits
<2018-08-11 Sat 18:05-21:05>
:PROPERTIES:
:ID:       53HRaonpTb2xVc8kTGH7EKh1@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Barons @ Biscuits Barons @ Biscuits

Follow on MiLB First Pitch  https //stza.co/+vLBH-2c

Shop  https //stza.co/+vLBH-2e

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Barons @ Biscuits
END:VALARM
DTSTART:20180811T230500Z
DTEND:20180812T020500Z
UID:53HRaonpTb2xVc8kTGH7EKh1@stanza.co
SUMMARY:Barons @ Biscuits
DESCRIPTION:Barons @ Biscuits\n\nFollow on MiLB First Pitch: https://stza.co/+vLBH-2c\n\nShop: https://stza.co/+vLBH-2e\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144506Z
LAST-MODIFIED:20180213T144506Z
TRANSP:OPAQUE
END:VEVENT
* Barons @ Biscuits
<2018-08-12 Sun 17:05-20:05>
:PROPERTIES:
:ID:       mvlpbsgy9JHovo-QaNLEkxPJ@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Barons @ Biscuits Barons @ Biscuits

Follow on MiLB First Pitch  https //stza.co/+vLBI-2F

Shop  https //stza.co/+vLBI-2j

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Barons @ Biscuits
END:VALARM
DTSTART:20180812T220500Z
DTEND:20180813T010500Z
UID:mvlpbsgy9JHovo-QaNLEkxPJ@stanza.co
SUMMARY:Barons @ Biscuits
DESCRIPTION:Barons @ Biscuits\n\nFollow on MiLB First Pitch: https://stza.co/+vLBI-2F\n\nShop: https://stza.co/+vLBI-2j\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144506Z
LAST-MODIFIED:20180213T144506Z
TRANSP:OPAQUE
END:VEVENT
* Barons vs. Smokies
<2018-08-14 Tue 19:05-22:05>
:PROPERTIES:
:ID:       TqSIzJ7JYFrtvtGkXgOWiMzw@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Barons vs. Smokies Barons vs. Smokies

Follow on MiLB First Pitch  https //stza.co/+wFWR-3f

Shop  https //stza.co/+wFWR-w

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Barons vs. Smokies
END:VALARM
DTSTART:20180815T000500Z
DTEND:20180815T030500Z
UID:TqSIzJ7JYFrtvtGkXgOWiMzw@stanza.co
SUMMARY:Barons vs. Smokies
DESCRIPTION:Barons vs. Smokies\n\nFollow on MiLB First Pitch: https://stza.co/+wFWR-3f\n\nShop: https://stza.co/+wFWR-w\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144506Z
LAST-MODIFIED:20180213T144506Z
TRANSP:OPAQUE
END:VEVENT
* Barons vs. Smokies
<2018-08-15 Wed 19:05-22:05>
:PROPERTIES:
:ID:       U1zcjEfZJGvHfggqjb72w6yQ@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Barons vs. Smokies Barons vs. Smokies

Follow on MiLB First Pitch  https //stza.co/+wFWU-1U

Shop  https //stza.co/+wFWU-1n

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Barons vs. Smokies
END:VALARM
DTSTART:20180816T000500Z
DTEND:20180816T030500Z
UID:U1zcjEfZJGvHfggqjb72w6yQ@stanza.co
SUMMARY:Barons vs. Smokies
DESCRIPTION:Barons vs. Smokies\n\nFollow on MiLB First Pitch: https://stza.co/+wFWU-1U\n\nShop: https://stza.co/+wFWU-1n\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144506Z
LAST-MODIFIED:20180213T144506Z
TRANSP:OPAQUE
END:VEVENT
* Barons vs. Smokies
<2018-08-16 Thu 19:05-22:05>
:PROPERTIES:
:ID:       m5BlGpddIDVTuZ14DUFyhaQB@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Barons vs. Smokies Barons vs. Smokies

Follow on MiLB First Pitch  https //stza.co/+wFWW-3n

Shop  https //stza.co/+wFWW-2V

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Barons vs. Smokies
END:VALARM
DTSTART:20180817T000500Z
DTEND:20180817T030500Z
UID:m5BlGpddIDVTuZ14DUFyhaQB@stanza.co
SUMMARY:Barons vs. Smokies
DESCRIPTION:Barons vs. Smokies\n\nFollow on MiLB First Pitch: https://stza.co/+wFWW-3n\n\nShop: https://stza.co/+wFWW-2V\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144506Z
LAST-MODIFIED:20180213T144506Z
TRANSP:OPAQUE
END:VEVENT
* Barons vs. Smokies
<2018-08-17 Fri 19:05-22:05>
:PROPERTIES:
:ID:       f232TpfkBZ9HBf5eiBGRNEhX@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Barons vs. Smokies Barons vs. Smokies

Follow on MiLB First Pitch  https //stza.co/+wFWX-Y

Shop  https //stza.co/+wFWX-I

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Barons vs. Smokies
END:VALARM
DTSTART:20180818T000500Z
DTEND:20180818T030500Z
UID:f232TpfkBZ9HBf5eiBGRNEhX@stanza.co
SUMMARY:Barons vs. Smokies
DESCRIPTION:Barons vs. Smokies\n\nFollow on MiLB First Pitch: https://stza.co/+wFWX-Y\n\nShop: https://stza.co/+wFWX-I\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144506Z
LAST-MODIFIED:20180213T144506Z
TRANSP:OPAQUE
END:VEVENT
* Barons vs. Smokies
<2018-08-18 Sat 18:30-21:30>
:PROPERTIES:
:ID:       jZEj8X98BbofuMUql9LXDusn@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Barons vs. Smokies Barons vs. Smokies

Follow on MiLB First Pitch  https //stza.co/+wFW_-1Y

Shop  https //stza.co/+wFW_-39

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Barons vs. Smokies
END:VALARM
DTSTART:20180818T233000Z
DTEND:20180819T023000Z
UID:jZEj8X98BbofuMUql9LXDusn@stanza.co
SUMMARY:Barons vs. Smokies
DESCRIPTION:Barons vs. Smokies\n\nFollow on MiLB First Pitch: https://stza.co/+wFW_-1Y\n\nShop: https://stza.co/+wFW_-39\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144506Z
LAST-MODIFIED:20180213T144506Z
TRANSP:OPAQUE
END:VEVENT
* Barons @ Jumbo Shrimp
<2018-08-19 Sun 17:05-20:05>
:PROPERTIES:
:ID:       Rr0TdcOydShmg6nzbg0aje53@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Barons @ Jumbo Shrimp Barons @ Jumbo Shrimp

Follow on MiLB First Pitch  https //stza.co/+vLBj-3Y

Shop  https //stza.co/+vLBj-3g

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Barons @ Jumbo Shrimp
END:VALARM
DTSTART:20180819T220500Z
DTEND:20180820T010500Z
UID:Rr0TdcOydShmg6nzbg0aje53@stanza.co
SUMMARY:Barons @ Jumbo Shrimp
DESCRIPTION:Barons @ Jumbo Shrimp\n\nFollow on MiLB First Pitch: https://stza.co/+vLBj-3Y\n\nShop: https://stza.co/+vLBj-3g\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144506Z
LAST-MODIFIED:20180213T144506Z
TRANSP:OPAQUE
END:VEVENT
* Barons @ Jumbo Shrimp
<2018-08-20 Mon 18:05-21:05>
:PROPERTIES:
:ID:       sZP7yDcQtH0rGOY1wljTu0_E@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Barons @ Jumbo Shrimp Barons @ Jumbo Shrimp

Follow on MiLB First Pitch  https //stza.co/+vLBk-1M

Shop  https //stza.co/+vLBk-3M

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Barons @ Jumbo Shrimp
END:VALARM
DTSTART:20180820T230500Z
DTEND:20180821T020500Z
UID:sZP7yDcQtH0rGOY1wljTu0_E@stanza.co
SUMMARY:Barons @ Jumbo Shrimp
DESCRIPTION:Barons @ Jumbo Shrimp\n\nFollow on MiLB First Pitch: https://stza.co/+vLBk-1M\n\nShop: https://stza.co/+vLBk-3M\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144506Z
LAST-MODIFIED:20180213T144506Z
TRANSP:OPAQUE
END:VEVENT
* Barons @ Jumbo Shrimp
<2018-08-21 Tue 18:05-21:05>
:PROPERTIES:
:ID:       0SNloJnC0HLxXwlveL-yeDFN@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Barons @ Jumbo Shrimp Barons @ Jumbo Shrimp

Follow on MiLB First Pitch  https //stza.co/+vLBl-2X

Shop  https //stza.co/+vLBl-13

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Barons @ Jumbo Shrimp
END:VALARM
DTSTART:20180821T230500Z
DTEND:20180822T020500Z
UID:0SNloJnC0HLxXwlveL-yeDFN@stanza.co
SUMMARY:Barons @ Jumbo Shrimp
DESCRIPTION:Barons @ Jumbo Shrimp\n\nFollow on MiLB First Pitch: https://stza.co/+vLBl-2X\n\nShop: https://stza.co/+vLBl-13\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144506Z
LAST-MODIFIED:20180213T144506Z
TRANSP:OPAQUE
END:VEVENT
* Barons @ Jumbo Shrimp
<2018-08-22 Wed 18:05-21:05>
:PROPERTIES:
:ID:       4vakSiVs1y6NA2aUbcvOOlPU@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Barons @ Jumbo Shrimp Barons @ Jumbo Shrimp

Follow on MiLB First Pitch  https //stza.co/+vLBm-38

Shop  https //stza.co/+vLBm-11

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Barons @ Jumbo Shrimp
END:VALARM
DTSTART:20180822T230500Z
DTEND:20180823T020500Z
UID:4vakSiVs1y6NA2aUbcvOOlPU@stanza.co
SUMMARY:Barons @ Jumbo Shrimp
DESCRIPTION:Barons @ Jumbo Shrimp\n\nFollow on MiLB First Pitch: https://stza.co/+vLBm-38\n\nShop: https://stza.co/+vLBm-11\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144506Z
LAST-MODIFIED:20180213T144506Z
TRANSP:OPAQUE
END:VEVENT
* Barons @ Jumbo Shrimp
<2018-08-23 Thu 18:05-21:05>
:PROPERTIES:
:ID:       3rNDmwY7_rTHjyGbBMEpT0Os@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Barons @ Jumbo Shrimp Barons @ Jumbo Shrimp

Follow on MiLB First Pitch  https //stza.co/+vLBn-5

Shop  https //stza.co/+vLBn-2M

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Barons @ Jumbo Shrimp
END:VALARM
DTSTART:20180823T230500Z
DTEND:20180824T020500Z
UID:3rNDmwY7_rTHjyGbBMEpT0Os@stanza.co
SUMMARY:Barons @ Jumbo Shrimp
DESCRIPTION:Barons @ Jumbo Shrimp\n\nFollow on MiLB First Pitch: https://stza.co/+vLBn-5\n\nShop: https://stza.co/+vLBn-2M\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144506Z
LAST-MODIFIED:20180213T144506Z
TRANSP:OPAQUE
END:VEVENT
* Barons vs. Generals
<2018-08-24 Fri 19:05-22:05>
:PROPERTIES:
:ID:       SoeDWOw15SsFLP13q1KI038r@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Barons vs. Generals Barons vs. Generals

Follow on MiLB First Pitch  https //stza.co/+wFW$-1p

Shop  https //stza.co/+wFW$-3G

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Barons vs. Generals
END:VALARM
DTSTART:20180825T000500Z
DTEND:20180825T030500Z
UID:SoeDWOw15SsFLP13q1KI038r@stanza.co
SUMMARY:Barons vs. Generals
DESCRIPTION:Barons vs. Generals\n\nFollow on MiLB First Pitch: https://stza.co/+wFW$-1p\n\nShop: https://stza.co/+wFW$-3G\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144506Z
LAST-MODIFIED:20180213T144506Z
TRANSP:OPAQUE
END:VEVENT
* Barons vs. Generals
<2018-08-25 Sat 18:30-21:30>
:PROPERTIES:
:ID:       GweGmiXA9ti_u6JuAdIHSNmU@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Barons vs. Generals Barons vs. Generals

Follow on MiLB First Pitch  https //stza.co/+wFX1-U

Shop  https //stza.co/+wFX1-H

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Barons vs. Generals
END:VALARM
DTSTART:20180825T233000Z
DTEND:20180826T023000Z
UID:GweGmiXA9ti_u6JuAdIHSNmU@stanza.co
SUMMARY:Barons vs. Generals
DESCRIPTION:Barons vs. Generals\n\nFollow on MiLB First Pitch: https://stza.co/+wFX1-U\n\nShop: https://stza.co/+wFX1-H\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144506Z
LAST-MODIFIED:20180213T144506Z
TRANSP:OPAQUE
END:VEVENT
* Barons vs. Generals
<2018-08-26 Sun 15:00-18:00>
:PROPERTIES:
:ID:       g6qrijc27bRLM-I4RwBuGssj@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Barons vs. Generals Barons vs. Generals

Follow on MiLB First Pitch  https //stza.co/+wFX3-22

Shop  https //stza.co/+wFX3-3W

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Barons vs. Generals
END:VALARM
DTSTART:20180826T200000Z
DTEND:20180826T230000Z
UID:g6qrijc27bRLM-I4RwBuGssj@stanza.co
SUMMARY:Barons vs. Generals
DESCRIPTION:Barons vs. Generals\n\nFollow on MiLB First Pitch: https://stza.co/+wFX3-22\n\nShop: https://stza.co/+wFX3-3W\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144506Z
LAST-MODIFIED:20180213T144506Z
TRANSP:OPAQUE
END:VEVENT
* Barons vs. Generals
<2018-08-27 Mon 19:05-22:05>
:PROPERTIES:
:ID:       lRXVoWSTdy5XlkO3D76OaOVp@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Barons vs. Generals Barons vs. Generals

Follow on MiLB First Pitch  https //stza.co/+wFX6-1k

Shop  https //stza.co/+wFX6-1u

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Barons vs. Generals
END:VALARM
DTSTART:20180828T000500Z
DTEND:20180828T030500Z
UID:lRXVoWSTdy5XlkO3D76OaOVp@stanza.co
SUMMARY:Barons vs. Generals
DESCRIPTION:Barons vs. Generals\n\nFollow on MiLB First Pitch: https://stza.co/+wFX6-1k\n\nShop: https://stza.co/+wFX6-1u\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144506Z
LAST-MODIFIED:20180213T144506Z
TRANSP:OPAQUE
END:VEVENT
* Barons vs. Generals
<2018-08-28 Tue 19:05-22:05>
:PROPERTIES:
:ID:       94ElJS7doASmJ0oNb0L_Yvc3@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Barons vs. Generals Barons vs. Generals

Follow on MiLB First Pitch  https //stza.co/+wFX7-2H

Shop  https //stza.co/+wFX7-t

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Barons vs. Generals
END:VALARM
DTSTART:20180829T000500Z
DTEND:20180829T030500Z
UID:94ElJS7doASmJ0oNb0L_Yvc3@stanza.co
SUMMARY:Barons vs. Generals
DESCRIPTION:Barons vs. Generals\n\nFollow on MiLB First Pitch: https://stza.co/+wFX7-2H\n\nShop: https://stza.co/+wFX7-t\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144506Z
LAST-MODIFIED:20180213T144506Z
TRANSP:OPAQUE
END:VEVENT
* Barons @ Shuckers
<2018-08-30 Thu 18:35-21:35>
:PROPERTIES:
:ID:       O_1ctUVH47dvaRigdcjyMazH@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Barons @ Shuckers Barons @ Shuckers

Follow on MiLB First Pitch  https //stza.co/+vLyL-2n

Shop  https //stza.co/+vLyL-33

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Barons @ Shuckers
END:VALARM
DTSTART:20180830T233500Z
DTEND:20180831T023500Z
UID:O_1ctUVH47dvaRigdcjyMazH@stanza.co
SUMMARY:Barons @ Shuckers
DESCRIPTION:Barons @ Shuckers\n\nFollow on MiLB First Pitch: https://stza.co/+vLyL-2n\n\nShop: https://stza.co/+vLyL-33\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144506Z
LAST-MODIFIED:20180213T144506Z
TRANSP:OPAQUE
END:VEVENT
* Barons @ Shuckers
<2018-08-31 Fri 18:35-21:35>
:PROPERTIES:
:ID:       6ilX2R861dy8aAasoP4fupgR@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Barons @ Shuckers Barons @ Shuckers

Follow on MiLB First Pitch  https //stza.co/+vLyM-3D

Shop  https //stza.co/+vLyM-3G

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Barons @ Shuckers
END:VALARM
DTSTART:20180831T233500Z
DTEND:20180901T023500Z
UID:6ilX2R861dy8aAasoP4fupgR@stanza.co
SUMMARY:Barons @ Shuckers
DESCRIPTION:Barons @ Shuckers\n\nFollow on MiLB First Pitch: https://stza.co/+vLyM-3D\n\nShop: https://stza.co/+vLyM-3G\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144506Z
LAST-MODIFIED:20180213T144506Z
TRANSP:OPAQUE
END:VEVENT
* Barons @ Shuckers
<2018-09-01 Sat 18:35-21:35>
:PROPERTIES:
:ID:       5i1c0NuuBkWAuQAuMbO9vAtU@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Barons @ Shuckers Barons @ Shuckers

Follow on MiLB First Pitch  https //stza.co/+vLyN-2N

Shop  https //stza.co/+vLyN-2O

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Barons @ Shuckers
END:VALARM
DTSTART:20180901T233500Z
DTEND:20180902T023500Z
UID:5i1c0NuuBkWAuQAuMbO9vAtU@stanza.co
SUMMARY:Barons @ Shuckers
DESCRIPTION:Barons @ Shuckers\n\nFollow on MiLB First Pitch: https://stza.co/+vLyN-2N\n\nShop: https://stza.co/+vLyN-2O\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144506Z
LAST-MODIFIED:20180213T144506Z
TRANSP:OPAQUE
END:VEVENT
* Barons @ Shuckers
<2018-09-02 Sun 16:05-19:05>
:PROPERTIES:
:ID:       a5of8oceCEPP_y2TXyj6eht4@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Barons @ Shuckers Barons @ Shuckers

Follow on MiLB First Pitch  https //stza.co/+vLyO-Z

Shop  https //stza.co/+vLyO-1c

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Barons @ Shuckers
END:VALARM
DTSTART:20180902T210500Z
DTEND:20180903T000500Z
UID:a5of8oceCEPP_y2TXyj6eht4@stanza.co
SUMMARY:Barons @ Shuckers
DESCRIPTION:Barons @ Shuckers\n\nFollow on MiLB First Pitch: https://stza.co/+vLyO-Z\n\nShop: https://stza.co/+vLyO-1c\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144506Z
LAST-MODIFIED:20180213T144506Z
TRANSP:OPAQUE
END:VEVENT
* Barons @ Shuckers
<2018-09-03 Mon>--<2018-09-02 Sun>
:PROPERTIES:
:ID:       tZI2pwbsa2JBVTLbuYJriEMm@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Barons @ Shuckers Barons @ Shuckers

Follow on MiLB First Pitch  https //stza.co/+vLyP-2c

Shop  https //stza.co/+vLyP-1q

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Barons @ Shuckers
END:VALARM
DTSTART;VALUE=DATE:20180903
DTEND;VALUE=DATE:20180903
UID:tZI2pwbsa2JBVTLbuYJriEMm@stanza.co
SUMMARY:Barons @ Shuckers
DESCRIPTION:Barons @ Shuckers\n\nFollow on MiLB First Pitch: https://stza.co/+vLyP-2c\n\nShop: https://stza.co/+vLyP-1q\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144506Z
LAST-MODIFIED:20180213T144506Z
TRANSP:OPAQUE
END:VEVENT
