#+TITLE:       Main Google calendar entries
#+AUTHOR:      Eric S Fraga
#+EMAIL:       e.fraga@ucl.ac.uk
#+DESCRIPTION: converted using the ical2org awk script
#+CATEGORY:    google
#+STARTUP:     hidestars
#+STARTUP:     overview

* COMMENT original iCal preamble

* AquaSox vs. Hops
<2018-06-15 Fri 21:05>--<2018-06-16 Sat 00:05>
:PROPERTIES:
:ID:       GbaekGR4GAvvslcmepqXlqiT@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

AquaSox vs. Hops AquaSox vs. Hops

Follow on MiLB First Pitch  https //stza.co/+vO7z-y

Shop  https //stza.co/+vO7z-1m

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:AquaSox vs. Hops
END:VALARM
DTSTART:20180616T020500Z
DTEND:20180616T050500Z
UID:GbaekGR4GAvvslcmepqXlqiT@stanza.co
SUMMARY:AquaSox vs. Hops
DESCRIPTION:AquaSox vs. Hops\n\nFollow on MiLB First Pitch: https://stza.co/+vO7z-y\n\nShop: https://stza.co/+vO7z-1m\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144524Z
LAST-MODIFIED:20180213T144524Z
TRANSP:OPAQUE
END:VEVENT
* AquaSox vs. Hops
<2018-06-16 Sat 21:05>--<2018-06-17 Sun 00:05>
:PROPERTIES:
:ID:       Tc-phpDK2lWYn-rDRHHin8Qc@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

AquaSox vs. Hops AquaSox vs. Hops

Follow on MiLB First Pitch  https //stza.co/+vO7A-2p

Shop  https //stza.co/+vO7A-2I

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:AquaSox vs. Hops
END:VALARM
DTSTART:20180617T020500Z
DTEND:20180617T050500Z
UID:Tc-phpDK2lWYn-rDRHHin8Qc@stanza.co
SUMMARY:AquaSox vs. Hops
DESCRIPTION:AquaSox vs. Hops\n\nFollow on MiLB First Pitch: https://stza.co/+vO7A-2p\n\nShop: https://stza.co/+vO7A-2I\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144524Z
LAST-MODIFIED:20180213T144524Z
TRANSP:OPAQUE
END:VEVENT
* AquaSox vs. Hops
<2018-06-17 Sun 18:05-21:05>
:PROPERTIES:
:ID:       y2okKU7B1WXB_f39IMSLNZZT@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

AquaSox vs. Hops AquaSox vs. Hops

Follow on MiLB First Pitch  https //stza.co/+vO7C-1m

Shop  https //stza.co/+vO7C-3M

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:AquaSox vs. Hops
END:VALARM
DTSTART:20180617T230500Z
DTEND:20180618T020500Z
UID:y2okKU7B1WXB_f39IMSLNZZT@stanza.co
SUMMARY:AquaSox vs. Hops
DESCRIPTION:AquaSox vs. Hops\n\nFollow on MiLB First Pitch: https://stza.co/+vO7C-1m\n\nShop: https://stza.co/+vO7C-3M\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144524Z
LAST-MODIFIED:20180213T144524Z
TRANSP:OPAQUE
END:VEVENT
* AquaSox vs. Hops
<2018-06-18 Mon 21:05>--<2018-06-19 Tue 00:05>
:PROPERTIES:
:ID:       c-IJ4PBivW9AM6hJRfmtkJ45@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

AquaSox vs. Hops AquaSox vs. Hops

Follow on MiLB First Pitch  https //stza.co/+vO7E-D

Shop  https //stza.co/+vO7E-3t

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:AquaSox vs. Hops
END:VALARM
DTSTART:20180619T020500Z
DTEND:20180619T050500Z
UID:c-IJ4PBivW9AM6hJRfmtkJ45@stanza.co
SUMMARY:AquaSox vs. Hops
DESCRIPTION:AquaSox vs. Hops\n\nFollow on MiLB First Pitch: https://stza.co/+vO7E-D\n\nShop: https://stza.co/+vO7E-3t\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144524Z
LAST-MODIFIED:20180213T144524Z
TRANSP:OPAQUE
END:VEVENT
* AquaSox vs. Hops
<2018-06-19 Tue 21:05>--<2018-06-20 Wed 00:05>
:PROPERTIES:
:ID:       C3LTDC_9BueRXLWKNJlm7tPu@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

AquaSox vs. Hops AquaSox vs. Hops

Follow on MiLB First Pitch  https //stza.co/+vO7H-2B

Shop  https //stza.co/+vO7H-2V

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:AquaSox vs. Hops
END:VALARM
DTSTART:20180620T020500Z
DTEND:20180620T050500Z
UID:C3LTDC_9BueRXLWKNJlm7tPu@stanza.co
SUMMARY:AquaSox vs. Hops
DESCRIPTION:AquaSox vs. Hops\n\nFollow on MiLB First Pitch: https://stza.co/+vO7H-2B\n\nShop: https://stza.co/+vO7H-2V\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144524Z
LAST-MODIFIED:20180213T144524Z
TRANSP:OPAQUE
END:VEVENT
* AquaSox @ Canadians
<2018-06-20 Wed 21:05>--<2018-06-21 Thu 00:05>
:PROPERTIES:
:ID:       ww8jpZ4fdRKKE-3XPGk1bCqC@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

AquaSox @ Canadians AquaSox @ Canadians

Follow on MiLB First Pitch  https //stza.co/+xXUP-3M

Shop  https //stza.co/+xXUP-3Y

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:AquaSox @ Canadians
END:VALARM
DTSTART:20180621T020500Z
DTEND:20180621T050500Z
UID:ww8jpZ4fdRKKE-3XPGk1bCqC@stanza.co
SUMMARY:AquaSox @ Canadians
DESCRIPTION:AquaSox @ Canadians\n\nFollow on MiLB First Pitch: https://stza.co/+xXUP-3M\n\nShop: https://stza.co/+xXUP-3Y\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144524Z
LAST-MODIFIED:20180213T144524Z
TRANSP:OPAQUE
END:VEVENT
* AquaSox @ Canadians
<2018-06-21 Thu 21:05>--<2018-06-22 Fri 00:05>
:PROPERTIES:
:ID:       wHE2A1jNzYfJ_7LQuWVej5EK@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

AquaSox @ Canadians AquaSox @ Canadians

Follow on MiLB First Pitch  https //stza.co/+xXUQ-3i

Shop  https //stza.co/+xXUQ-3I

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:AquaSox @ Canadians
END:VALARM
DTSTART:20180622T020500Z
DTEND:20180622T050500Z
UID:wHE2A1jNzYfJ_7LQuWVej5EK@stanza.co
SUMMARY:AquaSox @ Canadians
DESCRIPTION:AquaSox @ Canadians\n\nFollow on MiLB First Pitch: https://stza.co/+xXUQ-3i\n\nShop: https://stza.co/+xXUQ-3I\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144524Z
LAST-MODIFIED:20180213T144524Z
TRANSP:OPAQUE
END:VEVENT
* AquaSox @ Canadians
<2018-06-22 Fri 15:05-18:05>
:PROPERTIES:
:ID:       eAcSmaG0-EpGZPIXOYQzXiPW@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

AquaSox @ Canadians AquaSox @ Canadians

Follow on MiLB First Pitch  https //stza.co/+xXUR-3S

Shop  https //stza.co/+xXUR-2n

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:AquaSox @ Canadians
END:VALARM
DTSTART:20180622T200500Z
DTEND:20180622T230500Z
UID:eAcSmaG0-EpGZPIXOYQzXiPW@stanza.co
SUMMARY:AquaSox @ Canadians
DESCRIPTION:AquaSox @ Canadians\n\nFollow on MiLB First Pitch: https://stza.co/+xXUR-3S\n\nShop: https://stza.co/+xXUR-2n\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144524Z
LAST-MODIFIED:20180213T144524Z
TRANSP:OPAQUE
END:VEVENT
* AquaSox vs. Dust Devils
<2018-06-23 Sat 21:05>--<2018-06-24 Sun 00:05>
:PROPERTIES:
:ID:       2ErXYf-KXD-83o41I95RU-ny@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

AquaSox vs. Dust Devils AquaSox vs. Dust Devils

Follow on MiLB First Pitch  https //stza.co/+vO7I-19

Shop  https //stza.co/+vO7I-M

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:AquaSox vs. Dust Devils
END:VALARM
DTSTART:20180624T020500Z
DTEND:20180624T050500Z
UID:2ErXYf-KXD-83o41I95RU-ny@stanza.co
SUMMARY:AquaSox vs. Dust Devils
DESCRIPTION:AquaSox vs. Dust Devils\n\nFollow on MiLB First Pitch: https://stza.co/+vO7I-19\n\nShop: https://stza.co/+vO7I-M\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144524Z
LAST-MODIFIED:20180213T144524Z
TRANSP:OPAQUE
END:VEVENT
* AquaSox vs. Dust Devils
<2018-06-24 Sun 18:05-21:05>
:PROPERTIES:
:ID:       OiDOA45OXKDEpi1VAQqeaF6i@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

AquaSox vs. Dust Devils AquaSox vs. Dust Devils

Follow on MiLB First Pitch  https //stza.co/+vO7K-3L

Shop  https //stza.co/+vO7K-1B

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:AquaSox vs. Dust Devils
END:VALARM
DTSTART:20180624T230500Z
DTEND:20180625T020500Z
UID:OiDOA45OXKDEpi1VAQqeaF6i@stanza.co
SUMMARY:AquaSox vs. Dust Devils
DESCRIPTION:AquaSox vs. Dust Devils\n\nFollow on MiLB First Pitch: https://stza.co/+vO7K-3L\n\nShop: https://stza.co/+vO7K-1B\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144524Z
LAST-MODIFIED:20180213T144524Z
TRANSP:OPAQUE
END:VEVENT
* AquaSox vs. Dust Devils
<2018-06-25 Mon 21:05>--<2018-06-26 Tue 00:05>
:PROPERTIES:
:ID:       -0yqViKGa5fU_3kW8YOsmclN@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

AquaSox vs. Dust Devils AquaSox vs. Dust Devils

Follow on MiLB First Pitch  https //stza.co/+vO7N-F

Shop  https //stza.co/+vO7N-3R

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:AquaSox vs. Dust Devils
END:VALARM
DTSTART:20180626T020500Z
DTEND:20180626T050500Z
UID:-0yqViKGa5fU_3kW8YOsmclN@stanza.co
SUMMARY:AquaSox vs. Dust Devils
DESCRIPTION:AquaSox vs. Dust Devils\n\nFollow on MiLB First Pitch: https://stza.co/+vO7N-F\n\nShop: https://stza.co/+vO7N-3R\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144524Z
LAST-MODIFIED:20180213T144524Z
TRANSP:OPAQUE
END:VEVENT
* AquaSox @ Indians
<2018-06-26 Tue 20:30-23:30>
:PROPERTIES:
:ID:       eecmaYDtvNjiBMorhD5omL6s@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

AquaSox @ Indians AquaSox @ Indians

Follow on MiLB First Pitch  https //stza.co/+xC7B-2_

Shop  https //stza.co/+xC7B-2p

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:AquaSox @ Indians
END:VALARM
DTSTART:20180627T013000Z
DTEND:20180627T043000Z
UID:eecmaYDtvNjiBMorhD5omL6s@stanza.co
SUMMARY:AquaSox @ Indians
DESCRIPTION:AquaSox @ Indians\n\nFollow on MiLB First Pitch: https://stza.co/+xC7B-2_\n\nShop: https://stza.co/+xC7B-2p\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144524Z
LAST-MODIFIED:20180213T144524Z
TRANSP:OPAQUE
END:VEVENT
* AquaSox @ Indians
<2018-06-27 Wed 20:30-23:30>
:PROPERTIES:
:ID:       17xTLyjfvCvuwo4DeIpHRndS@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

AquaSox @ Indians AquaSox @ Indians

Follow on MiLB First Pitch  https //stza.co/+xC7D-35

Shop  https //stza.co/+xC7D-1H

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:AquaSox @ Indians
END:VALARM
DTSTART:20180628T013000Z
DTEND:20180628T043000Z
UID:17xTLyjfvCvuwo4DeIpHRndS@stanza.co
SUMMARY:AquaSox @ Indians
DESCRIPTION:AquaSox @ Indians\n\nFollow on MiLB First Pitch: https://stza.co/+xC7D-35\n\nShop: https://stza.co/+xC7D-1H\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144524Z
LAST-MODIFIED:20180213T144524Z
TRANSP:OPAQUE
END:VEVENT
* AquaSox @ Indians
<2018-06-28 Thu 20:30-23:30>
:PROPERTIES:
:ID:       nLFt2-o3XaykUa2Zj0cSzTUt@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

AquaSox @ Indians AquaSox @ Indians

Follow on MiLB First Pitch  https //stza.co/+xC7H-Q

Shop  https //stza.co/+xC7H-1g

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:AquaSox @ Indians
END:VALARM
DTSTART:20180629T013000Z
DTEND:20180629T043000Z
UID:nLFt2-o3XaykUa2Zj0cSzTUt@stanza.co
SUMMARY:AquaSox @ Indians
DESCRIPTION:AquaSox @ Indians\n\nFollow on MiLB First Pitch: https://stza.co/+xC7H-Q\n\nShop: https://stza.co/+xC7H-1g\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144524Z
LAST-MODIFIED:20180213T144524Z
TRANSP:OPAQUE
END:VEVENT
* AquaSox @ Emeralds
<2018-06-29 Fri 21:05>--<2018-06-30 Sat 00:05>
:PROPERTIES:
:ID:       uVE4MZUCS3vpM9HoW5gUXtZ5@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

AquaSox @ Emeralds AquaSox @ Emeralds

Follow on MiLB First Pitch  https //stza.co/+xWPd-1N

Shop  https //stza.co/+xWPd-1Q

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:AquaSox @ Emeralds
END:VALARM
DTSTART:20180630T020500Z
DTEND:20180630T050500Z
UID:uVE4MZUCS3vpM9HoW5gUXtZ5@stanza.co
SUMMARY:AquaSox @ Emeralds
DESCRIPTION:AquaSox @ Emeralds\n\nFollow on MiLB First Pitch: https://stza.co/+xWPd-1N\n\nShop: https://stza.co/+xWPd-1Q\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144524Z
LAST-MODIFIED:20180213T144524Z
TRANSP:OPAQUE
END:VEVENT
* AquaSox @ Emeralds
<2018-07-01 Sun>--<2018-06-30 Sat>
:PROPERTIES:
:ID:       n9SUdvCLoO63IaaMKW7WhsXP@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

AquaSox @ Emeralds AquaSox @ Emeralds

Follow on MiLB First Pitch  https //stza.co/+vO7v-2

Shop  https //stza.co/+vO7v-3T

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:AquaSox @ Emeralds
END:VALARM
DTSTART;VALUE=DATE:20180701
DTEND;VALUE=DATE:20180701
UID:n9SUdvCLoO63IaaMKW7WhsXP@stanza.co
SUMMARY:AquaSox @ Emeralds
DESCRIPTION:AquaSox @ Emeralds\n\nFollow on MiLB First Pitch: https://stza.co/+vO7v-2\n\nShop: https://stza.co/+vO7v-3T\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144524Z
LAST-MODIFIED:20180213T144524Z
TRANSP:OPAQUE
END:VEVENT
* AquaSox @ Emeralds
<2018-07-01 Sun 18:05-21:05>
:PROPERTIES:
:ID:       08ErRKD_YZupdQNKyo0g4r0-@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

AquaSox @ Emeralds AquaSox @ Emeralds

Follow on MiLB First Pitch  https //stza.co/+xWPe-2j

Shop  https //stza.co/+xWPe-19

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:AquaSox @ Emeralds
END:VALARM
DTSTART:20180701T230500Z
DTEND:20180702T020500Z
UID:08ErRKD_YZupdQNKyo0g4r0-@stanza.co
SUMMARY:AquaSox @ Emeralds
DESCRIPTION:AquaSox @ Emeralds\n\nFollow on MiLB First Pitch: https://stza.co/+xWPe-2j\n\nShop: https://stza.co/+xWPe-19\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144524Z
LAST-MODIFIED:20180213T144524Z
TRANSP:OPAQUE
END:VEVENT
* AquaSox @ Emeralds
<2018-07-02 Mon 21:05>--<2018-07-03 Tue 00:05>
:PROPERTIES:
:ID:       LxEgAySP20iD2YavRx7CJt56@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

AquaSox @ Emeralds AquaSox @ Emeralds

Follow on MiLB First Pitch  https //stza.co/+xWPf-1P

Shop  https //stza.co/+xWPf-3x

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:AquaSox @ Emeralds
END:VALARM
DTSTART:20180703T020500Z
DTEND:20180703T050500Z
UID:LxEgAySP20iD2YavRx7CJt56@stanza.co
SUMMARY:AquaSox @ Emeralds
DESCRIPTION:AquaSox @ Emeralds\n\nFollow on MiLB First Pitch: https://stza.co/+xWPf-1P\n\nShop: https://stza.co/+xWPf-3x\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144524Z
LAST-MODIFIED:20180213T144524Z
TRANSP:OPAQUE
END:VEVENT
* AquaSox @ Emeralds
<2018-07-03 Tue 21:05>--<2018-07-04 Wed 00:05>
:PROPERTIES:
:ID:       fSD3hymI67JSwbZ9rBU_aw4J@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

AquaSox @ Emeralds AquaSox @ Emeralds

Follow on MiLB First Pitch  https //stza.co/+xWPg-3h

Shop  https //stza.co/+xWPg-d

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:AquaSox @ Emeralds
END:VALARM
DTSTART:20180704T020500Z
DTEND:20180704T050500Z
UID:fSD3hymI67JSwbZ9rBU_aw4J@stanza.co
SUMMARY:AquaSox @ Emeralds
DESCRIPTION:AquaSox @ Emeralds\n\nFollow on MiLB First Pitch: https://stza.co/+xWPg-3h\n\nShop: https://stza.co/+xWPg-d\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144524Z
LAST-MODIFIED:20180213T144524Z
TRANSP:OPAQUE
END:VEVENT
* AquaSox vs. Canadians
<2018-07-04 Wed 21:05>--<2018-07-05 Thu 00:05>
:PROPERTIES:
:ID:       v3I47IqW-SuVBJG07xvDeP-e@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

AquaSox vs. Canadians AquaSox vs. Canadians

Follow on MiLB First Pitch  https //stza.co/+vO7P-2V

Shop  https //stza.co/+vO7P-9

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:AquaSox vs. Canadians
END:VALARM
DTSTART:20180705T020500Z
DTEND:20180705T050500Z
UID:v3I47IqW-SuVBJG07xvDeP-e@stanza.co
SUMMARY:AquaSox vs. Canadians
DESCRIPTION:AquaSox vs. Canadians\n\nFollow on MiLB First Pitch: https://stza.co/+vO7P-2V\n\nShop: https://stza.co/+vO7P-9\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144524Z
LAST-MODIFIED:20180213T144524Z
TRANSP:OPAQUE
END:VEVENT
* AquaSox vs. Canadians
<2018-07-05 Thu 21:05>--<2018-07-06 Fri 00:05>
:PROPERTIES:
:ID:       c5SX6rgCHOoIxrD5k3xi0ENQ@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

AquaSox vs. Canadians AquaSox vs. Canadians

Follow on MiLB First Pitch  https //stza.co/+vO7R-Q

Shop  https //stza.co/+vO7R-2H

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:AquaSox vs. Canadians
END:VALARM
DTSTART:20180706T020500Z
DTEND:20180706T050500Z
UID:c5SX6rgCHOoIxrD5k3xi0ENQ@stanza.co
SUMMARY:AquaSox vs. Canadians
DESCRIPTION:AquaSox vs. Canadians\n\nFollow on MiLB First Pitch: https://stza.co/+vO7R-Q\n\nShop: https://stza.co/+vO7R-2H\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144524Z
LAST-MODIFIED:20180213T144524Z
TRANSP:OPAQUE
END:VEVENT
* AquaSox vs. Canadians
<2018-07-06 Fri 21:05>--<2018-07-07 Sat 00:05>
:PROPERTIES:
:ID:       P5KLrs5Xvs0qpUC88tXqvBg2@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

AquaSox vs. Canadians AquaSox vs. Canadians

Follow on MiLB First Pitch  https //stza.co/+vO7T-1N

Shop  https //stza.co/+vO7T-1p

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:AquaSox vs. Canadians
END:VALARM
DTSTART:20180707T020500Z
DTEND:20180707T050500Z
UID:P5KLrs5Xvs0qpUC88tXqvBg2@stanza.co
SUMMARY:AquaSox vs. Canadians
DESCRIPTION:AquaSox vs. Canadians\n\nFollow on MiLB First Pitch: https://stza.co/+vO7T-1N\n\nShop: https://stza.co/+vO7T-1p\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144524Z
LAST-MODIFIED:20180213T144524Z
TRANSP:OPAQUE
END:VEVENT
* AquaSox @ Dust Devils
<2018-07-07 Sat 21:15>--<2018-07-08 Sun 00:15>
:PROPERTIES:
:ID:       G_ZrFNguTANDCbaFqNzjmqeG@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

AquaSox @ Dust Devils AquaSox @ Dust Devils

Follow on MiLB First Pitch  https //stza.co/+vO8_-3w

Shop  https //stza.co/+vO8_-3K

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:AquaSox @ Dust Devils
END:VALARM
DTSTART:20180708T021500Z
DTEND:20180708T051500Z
UID:G_ZrFNguTANDCbaFqNzjmqeG@stanza.co
SUMMARY:AquaSox @ Dust Devils
DESCRIPTION:AquaSox @ Dust Devils\n\nFollow on MiLB First Pitch: https://stza.co/+vO8_-3w\n\nShop: https://stza.co/+vO8_-3K\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144524Z
LAST-MODIFIED:20180213T144524Z
TRANSP:OPAQUE
END:VEVENT
* AquaSox @ Dust Devils
<2018-07-08 Sun 21:15>--<2018-07-09 Mon 00:15>
:PROPERTIES:
:ID:       7HgMExwb3rTqF8qDG_hFkCzv@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

AquaSox @ Dust Devils AquaSox @ Dust Devils

Follow on MiLB First Pitch  https //stza.co/+vO8$-O

Shop  https //stza.co/+vO8$-3k

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:AquaSox @ Dust Devils
END:VALARM
DTSTART:20180709T021500Z
DTEND:20180709T051500Z
UID:7HgMExwb3rTqF8qDG_hFkCzv@stanza.co
SUMMARY:AquaSox @ Dust Devils
DESCRIPTION:AquaSox @ Dust Devils\n\nFollow on MiLB First Pitch: https://stza.co/+vO8$-O\n\nShop: https://stza.co/+vO8$-3k\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144524Z
LAST-MODIFIED:20180213T144524Z
TRANSP:OPAQUE
END:VEVENT
* AquaSox @ Dust Devils
<2018-07-09 Mon 21:15>--<2018-07-10 Tue 00:15>
:PROPERTIES:
:ID:       YCWLJywtu3rKiZXsQ8JPD7dp@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

AquaSox @ Dust Devils AquaSox @ Dust Devils

Follow on MiLB First Pitch  https //stza.co/+vO90-b

Shop  https //stza.co/+vO90-G

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:AquaSox @ Dust Devils
END:VALARM
DTSTART:20180710T021500Z
DTEND:20180710T051500Z
UID:YCWLJywtu3rKiZXsQ8JPD7dp@stanza.co
SUMMARY:AquaSox @ Dust Devils
DESCRIPTION:AquaSox @ Dust Devils\n\nFollow on MiLB First Pitch: https://stza.co/+vO90-b\n\nShop: https://stza.co/+vO90-G\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144524Z
LAST-MODIFIED:20180213T144524Z
TRANSP:OPAQUE
END:VEVENT
* AquaSox vs. Volcanoes
<2018-07-11 Wed 21:05>--<2018-07-12 Thu 00:05>
:PROPERTIES:
:ID:       3afU_HyzzDDOuxL1RAw9QcrX@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

AquaSox vs. Volcanoes AquaSox vs. Volcanoes

Follow on MiLB First Pitch  https //stza.co/+vO7U-2k

Shop  https //stza.co/+vO7U-2L

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:AquaSox vs. Volcanoes
END:VALARM
DTSTART:20180712T020500Z
DTEND:20180712T050500Z
UID:3afU_HyzzDDOuxL1RAw9QcrX@stanza.co
SUMMARY:AquaSox vs. Volcanoes
DESCRIPTION:AquaSox vs. Volcanoes\n\nFollow on MiLB First Pitch: https://stza.co/+vO7U-2k\n\nShop: https://stza.co/+vO7U-2L\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144524Z
LAST-MODIFIED:20180213T144524Z
TRANSP:OPAQUE
END:VEVENT
* AquaSox vs. Volcanoes
<2018-07-12 Thu 21:05>--<2018-07-13 Fri 00:05>
:PROPERTIES:
:ID:       h_urTl7G80O3TDalfVl9ABi6@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

AquaSox vs. Volcanoes AquaSox vs. Volcanoes

Follow on MiLB First Pitch  https //stza.co/+vO7W-3F

Shop  https //stza.co/+vO7W-1y

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:AquaSox vs. Volcanoes
END:VALARM
DTSTART:20180713T020500Z
DTEND:20180713T050500Z
UID:h_urTl7G80O3TDalfVl9ABi6@stanza.co
SUMMARY:AquaSox vs. Volcanoes
DESCRIPTION:AquaSox vs. Volcanoes\n\nFollow on MiLB First Pitch: https://stza.co/+vO7W-3F\n\nShop: https://stza.co/+vO7W-1y\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144524Z
LAST-MODIFIED:20180213T144524Z
TRANSP:OPAQUE
END:VEVENT
* AquaSox vs. Volcanoes
<2018-07-13 Fri 21:05>--<2018-07-14 Sat 00:05>
:PROPERTIES:
:ID:       FHEmNzaB_-w6dojJsmom-O4p@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

AquaSox vs. Volcanoes AquaSox vs. Volcanoes

Follow on MiLB First Pitch  https //stza.co/+vO7Z-u

Shop  https //stza.co/+vO7Z-1m

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:AquaSox vs. Volcanoes
END:VALARM
DTSTART:20180714T020500Z
DTEND:20180714T050500Z
UID:FHEmNzaB_-w6dojJsmom-O4p@stanza.co
SUMMARY:AquaSox vs. Volcanoes
DESCRIPTION:AquaSox vs. Volcanoes\n\nFollow on MiLB First Pitch: https://stza.co/+vO7Z-u\n\nShop: https://stza.co/+vO7Z-1m\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144524Z
LAST-MODIFIED:20180213T144524Z
TRANSP:OPAQUE
END:VEVENT
* AquaSox vs. Volcanoes
<2018-07-14 Sat 21:05>--<2018-07-15 Sun 00:05>
:PROPERTIES:
:ID:       OMH4qEl9sRncEZvZtIumfwz8@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

AquaSox vs. Volcanoes AquaSox vs. Volcanoes

Follow on MiLB First Pitch  https //stza.co/+vO7_-1V

Shop  https //stza.co/+vO7_-v

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:AquaSox vs. Volcanoes
END:VALARM
DTSTART:20180715T020500Z
DTEND:20180715T050500Z
UID:OMH4qEl9sRncEZvZtIumfwz8@stanza.co
SUMMARY:AquaSox vs. Volcanoes
DESCRIPTION:AquaSox vs. Volcanoes\n\nFollow on MiLB First Pitch: https://stza.co/+vO7_-1V\n\nShop: https://stza.co/+vO7_-v\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144524Z
LAST-MODIFIED:20180213T144524Z
TRANSP:OPAQUE
END:VEVENT
* AquaSox vs. Volcanoes
<2018-07-15 Sun 18:05-21:05>
:PROPERTIES:
:ID:       EVGxz_dMK6zstbS9LsdmrMEJ@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

AquaSox vs. Volcanoes AquaSox vs. Volcanoes

Follow on MiLB First Pitch  https //stza.co/+vO80-2H

Shop  https //stza.co/+vO80-3S

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:AquaSox vs. Volcanoes
END:VALARM
DTSTART:20180715T230500Z
DTEND:20180716T020500Z
UID:EVGxz_dMK6zstbS9LsdmrMEJ@stanza.co
SUMMARY:AquaSox vs. Volcanoes
DESCRIPTION:AquaSox vs. Volcanoes\n\nFollow on MiLB First Pitch: https://stza.co/+vO80-2H\n\nShop: https://stza.co/+vO80-3S\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144524Z
LAST-MODIFIED:20180213T144524Z
TRANSP:OPAQUE
END:VEVENT
* AquaSox vs. Indians
<2018-07-16 Mon 21:05>--<2018-07-17 Tue 00:05>
:PROPERTIES:
:ID:       A19nT0u02DH3UW8--_irr3Uo@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

AquaSox vs. Indians AquaSox vs. Indians

Follow on MiLB First Pitch  https //stza.co/+vO82-3T

Shop  https //stza.co/+vO82-o

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:AquaSox vs. Indians
END:VALARM
DTSTART:20180717T020500Z
DTEND:20180717T050500Z
UID:A19nT0u02DH3UW8--_irr3Uo@stanza.co
SUMMARY:AquaSox vs. Indians
DESCRIPTION:AquaSox vs. Indians\n\nFollow on MiLB First Pitch: https://stza.co/+vO82-3T\n\nShop: https://stza.co/+vO82-o\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144524Z
LAST-MODIFIED:20180213T144524Z
TRANSP:OPAQUE
END:VEVENT
* AquaSox vs. Indians
<2018-07-17 Tue 21:05>--<2018-07-18 Wed 00:05>
:PROPERTIES:
:ID:       us8tmebr2MGc3z7DvCKusXVg@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

AquaSox vs. Indians AquaSox vs. Indians

Follow on MiLB First Pitch  https //stza.co/+vO84-1B

Shop  https //stza.co/+vO84-3P

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:AquaSox vs. Indians
END:VALARM
DTSTART:20180718T020500Z
DTEND:20180718T050500Z
UID:us8tmebr2MGc3z7DvCKusXVg@stanza.co
SUMMARY:AquaSox vs. Indians
DESCRIPTION:AquaSox vs. Indians\n\nFollow on MiLB First Pitch: https://stza.co/+vO84-1B\n\nShop: https://stza.co/+vO84-3P\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144524Z
LAST-MODIFIED:20180213T144524Z
TRANSP:OPAQUE
END:VEVENT
* AquaSox vs. Indians
<2018-07-18 Wed 13:05-16:05>
:PROPERTIES:
:ID:       meQz8MTvGR3TMJ9WMUyH8rvQ@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

AquaSox vs. Indians AquaSox vs. Indians

Follow on MiLB First Pitch  https //stza.co/+vO87-3O

Shop  https //stza.co/+vO87-3m

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:AquaSox vs. Indians
END:VALARM
DTSTART:20180718T180500Z
DTEND:20180718T210500Z
UID:meQz8MTvGR3TMJ9WMUyH8rvQ@stanza.co
SUMMARY:AquaSox vs. Indians
DESCRIPTION:AquaSox vs. Indians\n\nFollow on MiLB First Pitch: https://stza.co/+vO87-3O\n\nShop: https://stza.co/+vO87-3m\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144524Z
LAST-MODIFIED:20180213T144524Z
TRANSP:OPAQUE
END:VEVENT
* AquaSox @ Hawks
<2018-07-19 Thu 20:15-23:15>
:PROPERTIES:
:ID:       VhFHwl00bLaXNf-6x888WEnk@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

AquaSox @ Hawks AquaSox @ Hawks

Follow on MiLB First Pitch  https //stza.co/+xC6N-2R

Shop  https //stza.co/+xC6N-1C

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:AquaSox @ Hawks
END:VALARM
DTSTART:20180720T011500Z
DTEND:20180720T041500Z
UID:VhFHwl00bLaXNf-6x888WEnk@stanza.co
SUMMARY:AquaSox @ Hawks
DESCRIPTION:AquaSox @ Hawks\n\nFollow on MiLB First Pitch: https://stza.co/+xC6N-2R\n\nShop: https://stza.co/+xC6N-1C\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144524Z
LAST-MODIFIED:20180213T144524Z
TRANSP:OPAQUE
END:VEVENT
* AquaSox @ Hawks
<2018-07-20 Fri 20:15-23:15>
:PROPERTIES:
:ID:       6glTMt1XYzAuUoxIxffxpf4T@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

AquaSox @ Hawks AquaSox @ Hawks

Follow on MiLB First Pitch  https //stza.co/+xC6P-7

Shop  https //stza.co/+xC6P-1o

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:AquaSox @ Hawks
END:VALARM
DTSTART:20180721T011500Z
DTEND:20180721T041500Z
UID:6glTMt1XYzAuUoxIxffxpf4T@stanza.co
SUMMARY:AquaSox @ Hawks
DESCRIPTION:AquaSox @ Hawks\n\nFollow on MiLB First Pitch: https://stza.co/+xC6P-7\n\nShop: https://stza.co/+xC6P-1o\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144524Z
LAST-MODIFIED:20180213T144524Z
TRANSP:OPAQUE
END:VEVENT
* AquaSox @ Hawks
<2018-07-21 Sat 20:15-23:15>
:PROPERTIES:
:ID:       Nm4pQwQTSRRqpBV0ce7TL7i6@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

AquaSox @ Hawks AquaSox @ Hawks

Follow on MiLB First Pitch  https //stza.co/+xC6V-2S

Shop  https //stza.co/+xC6V-3f

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:AquaSox @ Hawks
END:VALARM
DTSTART:20180722T011500Z
DTEND:20180722T041500Z
UID:Nm4pQwQTSRRqpBV0ce7TL7i6@stanza.co
SUMMARY:AquaSox @ Hawks
DESCRIPTION:AquaSox @ Hawks\n\nFollow on MiLB First Pitch: https://stza.co/+xC6V-2S\n\nShop: https://stza.co/+xC6V-3f\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144524Z
LAST-MODIFIED:20180213T144524Z
TRANSP:OPAQUE
END:VEVENT
* AquaSox @ Hawks
<2018-07-22 Sun 18:15-21:15>
:PROPERTIES:
:ID:       d8_JgZfebiqay73bLsoSDG3e@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

AquaSox @ Hawks AquaSox @ Hawks

Follow on MiLB First Pitch  https //stza.co/+xC6Z-3W

Shop  https //stza.co/+xC6Z-2Y

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:AquaSox @ Hawks
END:VALARM
DTSTART:20180722T231500Z
DTEND:20180723T021500Z
UID:d8_JgZfebiqay73bLsoSDG3e@stanza.co
SUMMARY:AquaSox @ Hawks
DESCRIPTION:AquaSox @ Hawks\n\nFollow on MiLB First Pitch: https://stza.co/+xC6Z-3W\n\nShop: https://stza.co/+xC6Z-2Y\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144524Z
LAST-MODIFIED:20180213T144524Z
TRANSP:OPAQUE
END:VEVENT
* AquaSox @ Hawks
<2018-07-23 Mon 20:15-23:15>
:PROPERTIES:
:ID:       VcU0g0E-AiJ_wrbcPk6KXU-y@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

AquaSox @ Hawks AquaSox @ Hawks

Follow on MiLB First Pitch  https //stza.co/+xC70-1$

Shop  https //stza.co/+xC70-33

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:AquaSox @ Hawks
END:VALARM
DTSTART:20180724T011500Z
DTEND:20180724T041500Z
UID:VcU0g0E-AiJ_wrbcPk6KXU-y@stanza.co
SUMMARY:AquaSox @ Hawks
DESCRIPTION:AquaSox @ Hawks\n\nFollow on MiLB First Pitch: https://stza.co/+xC70-1$\n\nShop: https://stza.co/+xC70-33\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144524Z
LAST-MODIFIED:20180213T144524Z
TRANSP:OPAQUE
END:VEVENT
* AquaSox vs. Canadians
<2018-07-24 Tue 21:05>--<2018-07-25 Wed 00:05>
:PROPERTIES:
:ID:       4F3xTk6gz2zLWm9UyHcP7jdC@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

AquaSox vs. Canadians AquaSox vs. Canadians

Follow on MiLB First Pitch  https //stza.co/+vO88-Z

Shop  https //stza.co/+vO88-34

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:AquaSox vs. Canadians
END:VALARM
DTSTART:20180725T020500Z
DTEND:20180725T050500Z
UID:4F3xTk6gz2zLWm9UyHcP7jdC@stanza.co
SUMMARY:AquaSox vs. Canadians
DESCRIPTION:AquaSox vs. Canadians\n\nFollow on MiLB First Pitch: https://stza.co/+vO88-Z\n\nShop: https://stza.co/+vO88-34\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144524Z
LAST-MODIFIED:20180213T144524Z
TRANSP:OPAQUE
END:VEVENT
* AquaSox vs. Canadians
<2018-07-25 Wed 21:05>--<2018-07-26 Thu 00:05>
:PROPERTIES:
:ID:       -oD6KuZJjs5uVZG7Ks3VDlIw@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

AquaSox vs. Canadians AquaSox vs. Canadians

Follow on MiLB First Pitch  https //stza.co/+vO8b-28

Shop  https //stza.co/+vO8b-3U

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:AquaSox vs. Canadians
END:VALARM
DTSTART:20180726T020500Z
DTEND:20180726T050500Z
UID:-oD6KuZJjs5uVZG7Ks3VDlIw@stanza.co
SUMMARY:AquaSox vs. Canadians
DESCRIPTION:AquaSox vs. Canadians\n\nFollow on MiLB First Pitch: https://stza.co/+vO8b-28\n\nShop: https://stza.co/+vO8b-3U\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144524Z
LAST-MODIFIED:20180213T144524Z
TRANSP:OPAQUE
END:VEVENT
* AquaSox vs. Canadians
<2018-07-26 Thu 13:05-16:05>
:PROPERTIES:
:ID:       9wbLUTrGrgHLct3mCsrPsxaA@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

AquaSox vs. Canadians AquaSox vs. Canadians

Follow on MiLB First Pitch  https //stza.co/+vO8c-2$

Shop  https //stza.co/+vO8c-1L

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:AquaSox vs. Canadians
END:VALARM
DTSTART:20180726T180500Z
DTEND:20180726T210500Z
UID:9wbLUTrGrgHLct3mCsrPsxaA@stanza.co
SUMMARY:AquaSox vs. Canadians
DESCRIPTION:AquaSox vs. Canadians\n\nFollow on MiLB First Pitch: https://stza.co/+vO8c-2$\n\nShop: https://stza.co/+vO8c-1L\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144524Z
LAST-MODIFIED:20180213T144524Z
TRANSP:OPAQUE
END:VEVENT
* AquaSox @ Volcanoes
<2018-07-27 Fri>--<2018-07-26 Thu>
:PROPERTIES:
:ID:       wHR08pjwLZSKhTq2EN-JZBpW@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

AquaSox @ Volcanoes AquaSox @ Volcanoes

Follow on MiLB First Pitch  https //stza.co/+vO8P-3F

Shop  https //stza.co/+vO8P-2k

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:AquaSox @ Volcanoes
END:VALARM
DTSTART;VALUE=DATE:20180727
DTEND;VALUE=DATE:20180727
UID:wHR08pjwLZSKhTq2EN-JZBpW@stanza.co
SUMMARY:AquaSox @ Volcanoes
DESCRIPTION:AquaSox @ Volcanoes\n\nFollow on MiLB First Pitch: https://stza.co/+vO8P-3F\n\nShop: https://stza.co/+vO8P-2k\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144524Z
LAST-MODIFIED:20180213T144524Z
TRANSP:OPAQUE
END:VEVENT
* AquaSox @ Volcanoes
<2018-07-28 Sat>--<2018-07-27 Fri>
:PROPERTIES:
:ID:       ZPAo_GRZKo_Bvd6fE3szXtmC@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

AquaSox @ Volcanoes AquaSox @ Volcanoes

Follow on MiLB First Pitch  https //stza.co/+vO8Q-1S

Shop  https //stza.co/+vO8Q-3Z

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:AquaSox @ Volcanoes
END:VALARM
DTSTART;VALUE=DATE:20180728
DTEND;VALUE=DATE:20180728
UID:ZPAo_GRZKo_Bvd6fE3szXtmC@stanza.co
SUMMARY:AquaSox @ Volcanoes
DESCRIPTION:AquaSox @ Volcanoes\n\nFollow on MiLB First Pitch: https://stza.co/+vO8Q-1S\n\nShop: https://stza.co/+vO8Q-3Z\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144524Z
LAST-MODIFIED:20180213T144524Z
TRANSP:OPAQUE
END:VEVENT
* AquaSox @ Volcanoes
<2018-07-29 Sun>--<2018-07-28 Sat>
:PROPERTIES:
:ID:       w4ZbOVQx4KqZYrsM67l3eWSG@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

AquaSox @ Volcanoes AquaSox @ Volcanoes

Follow on MiLB First Pitch  https //stza.co/+vO8R-R

Shop  https //stza.co/+vO8R-34

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:AquaSox @ Volcanoes
END:VALARM
DTSTART;VALUE=DATE:20180729
DTEND;VALUE=DATE:20180729
UID:w4ZbOVQx4KqZYrsM67l3eWSG@stanza.co
SUMMARY:AquaSox @ Volcanoes
DESCRIPTION:AquaSox @ Volcanoes\n\nFollow on MiLB First Pitch: https://stza.co/+vO8R-R\n\nShop: https://stza.co/+vO8R-34\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144524Z
LAST-MODIFIED:20180213T144524Z
TRANSP:OPAQUE
END:VEVENT
* AquaSox @ Volcanoes
<2018-07-30 Mon>--<2018-07-29 Sun>
:PROPERTIES:
:ID:       arq1beJgFbc7eLMfXhosPUZA@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

AquaSox @ Volcanoes AquaSox @ Volcanoes

Follow on MiLB First Pitch  https //stza.co/+vO8S-2l

Shop  https //stza.co/+vO8S-3X

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:AquaSox @ Volcanoes
END:VALARM
DTSTART;VALUE=DATE:20180730
DTEND;VALUE=DATE:20180730
UID:arq1beJgFbc7eLMfXhosPUZA@stanza.co
SUMMARY:AquaSox @ Volcanoes
DESCRIPTION:AquaSox @ Volcanoes\n\nFollow on MiLB First Pitch: https://stza.co/+vO8S-2l\n\nShop: https://stza.co/+vO8S-3X\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144524Z
LAST-MODIFIED:20180213T144524Z
TRANSP:OPAQUE
END:VEVENT
* AquaSox @ Volcanoes
<2018-07-31 Tue>--<2018-07-30 Mon>
:PROPERTIES:
:ID:       42gqu3juAJD4BdQcnCbTyARk@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

AquaSox @ Volcanoes AquaSox @ Volcanoes

Follow on MiLB First Pitch  https //stza.co/+vO8T-3i

Shop  https //stza.co/+vO8T-3w

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:AquaSox @ Volcanoes
END:VALARM
DTSTART;VALUE=DATE:20180731
DTEND;VALUE=DATE:20180731
UID:42gqu3juAJD4BdQcnCbTyARk@stanza.co
SUMMARY:AquaSox @ Volcanoes
DESCRIPTION:AquaSox @ Volcanoes\n\nFollow on MiLB First Pitch: https://stza.co/+vO8T-3i\n\nShop: https://stza.co/+vO8T-3w\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144524Z
LAST-MODIFIED:20180213T144524Z
TRANSP:OPAQUE
END:VEVENT
* AquaSox vs. Hawks
<2018-08-01 Wed 21:05>--<2018-08-02 Thu 00:05>
:PROPERTIES:
:ID:       cIQzF_ZCTWwrqNGrMFLnVPdB@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

AquaSox vs. Hawks AquaSox vs. Hawks

Follow on MiLB First Pitch  https //stza.co/+vO8f-1l

Shop  https //stza.co/+vO8f-17

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:AquaSox vs. Hawks
END:VALARM
DTSTART:20180802T020500Z
DTEND:20180802T050500Z
UID:cIQzF_ZCTWwrqNGrMFLnVPdB@stanza.co
SUMMARY:AquaSox vs. Hawks
DESCRIPTION:AquaSox vs. Hawks\n\nFollow on MiLB First Pitch: https://stza.co/+vO8f-1l\n\nShop: https://stza.co/+vO8f-17\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144524Z
LAST-MODIFIED:20180213T144524Z
TRANSP:OPAQUE
END:VEVENT
* AquaSox vs. Hawks
<2018-08-02 Thu 21:05>--<2018-08-03 Fri 00:05>
:PROPERTIES:
:ID:       ZaLJ-624Om2Ploucbg4vzY0p@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

AquaSox vs. Hawks AquaSox vs. Hawks

Follow on MiLB First Pitch  https //stza.co/+vO8h-34

Shop  https //stza.co/+vO8h-23

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:AquaSox vs. Hawks
END:VALARM
DTSTART:20180803T020500Z
DTEND:20180803T050500Z
UID:ZaLJ-624Om2Ploucbg4vzY0p@stanza.co
SUMMARY:AquaSox vs. Hawks
DESCRIPTION:AquaSox vs. Hawks\n\nFollow on MiLB First Pitch: https://stza.co/+vO8h-34\n\nShop: https://stza.co/+vO8h-23\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144524Z
LAST-MODIFIED:20180213T144524Z
TRANSP:OPAQUE
END:VEVENT
* AquaSox vs. Hawks
<2018-08-03 Fri 21:05>--<2018-08-04 Sat 00:05>
:PROPERTIES:
:ID:       9aWPWwU0HakRg1ILvl8h8eua@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

AquaSox vs. Hawks AquaSox vs. Hawks

Follow on MiLB First Pitch  https //stza.co/+vO8j-1K

Shop  https //stza.co/+vO8j-34

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:AquaSox vs. Hawks
END:VALARM
DTSTART:20180804T020500Z
DTEND:20180804T050500Z
UID:9aWPWwU0HakRg1ILvl8h8eua@stanza.co
SUMMARY:AquaSox vs. Hawks
DESCRIPTION:AquaSox vs. Hawks\n\nFollow on MiLB First Pitch: https://stza.co/+vO8j-1K\n\nShop: https://stza.co/+vO8j-34\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144524Z
LAST-MODIFIED:20180213T144524Z
TRANSP:OPAQUE
END:VEVENT
* AquaSox vs. Hawks
<2018-08-04 Sat 21:05>--<2018-08-05 Sun 00:05>
:PROPERTIES:
:ID:       wRmlzvxwrmHqaYkRKoISuig_@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

AquaSox vs. Hawks AquaSox vs. Hawks

Follow on MiLB First Pitch  https //stza.co/+vO8k-2H

Shop  https //stza.co/+vO8k-1p

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:AquaSox vs. Hawks
END:VALARM
DTSTART:20180805T020500Z
DTEND:20180805T050500Z
UID:wRmlzvxwrmHqaYkRKoISuig_@stanza.co
SUMMARY:AquaSox vs. Hawks
DESCRIPTION:AquaSox vs. Hawks\n\nFollow on MiLB First Pitch: https://stza.co/+vO8k-2H\n\nShop: https://stza.co/+vO8k-1p\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144524Z
LAST-MODIFIED:20180213T144524Z
TRANSP:OPAQUE
END:VEVENT
* AquaSox vs. Hawks
<2018-08-05 Sun 18:05-21:05>
:PROPERTIES:
:ID:       8qpjI65HdIFPGaVEBZamcTOz@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

AquaSox vs. Hawks AquaSox vs. Hawks

Follow on MiLB First Pitch  https //stza.co/+vO8m-2W

Shop  https //stza.co/+vO8m-2Q

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:AquaSox vs. Hawks
END:VALARM
DTSTART:20180805T230500Z
DTEND:20180806T020500Z
UID:8qpjI65HdIFPGaVEBZamcTOz@stanza.co
SUMMARY:AquaSox vs. Hawks
DESCRIPTION:AquaSox vs. Hawks\n\nFollow on MiLB First Pitch: https://stza.co/+vO8m-2W\n\nShop: https://stza.co/+vO8m-2Q\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144524Z
LAST-MODIFIED:20180213T144524Z
TRANSP:OPAQUE
END:VEVENT
* AquaSox vs. Emeralds
<2018-08-09 Thu 21:05>--<2018-08-10 Fri 00:05>
:PROPERTIES:
:ID:       F7nJ451EeHbQ0ZmkdA0AievJ@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

AquaSox vs. Emeralds AquaSox vs. Emeralds

Follow on MiLB First Pitch  https //stza.co/+vO8o-22

Shop  https //stza.co/+vO8o-3k

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:AquaSox vs. Emeralds
END:VALARM
DTSTART:20180810T020500Z
DTEND:20180810T050500Z
UID:F7nJ451EeHbQ0ZmkdA0AievJ@stanza.co
SUMMARY:AquaSox vs. Emeralds
DESCRIPTION:AquaSox vs. Emeralds\n\nFollow on MiLB First Pitch: https://stza.co/+vO8o-22\n\nShop: https://stza.co/+vO8o-3k\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144524Z
LAST-MODIFIED:20180213T144524Z
TRANSP:OPAQUE
END:VEVENT
* AquaSox vs. Emeralds
<2018-08-10 Fri 21:05>--<2018-08-11 Sat 00:05>
:PROPERTIES:
:ID:       40C3dgTs_LyFk_Cq9PHSLuDs@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

AquaSox vs. Emeralds AquaSox vs. Emeralds

Follow on MiLB First Pitch  https //stza.co/+vO8r-1Q

Shop  https //stza.co/+vO8r-U

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:AquaSox vs. Emeralds
END:VALARM
DTSTART:20180811T020500Z
DTEND:20180811T050500Z
UID:40C3dgTs_LyFk_Cq9PHSLuDs@stanza.co
SUMMARY:AquaSox vs. Emeralds
DESCRIPTION:AquaSox vs. Emeralds\n\nFollow on MiLB First Pitch: https://stza.co/+vO8r-1Q\n\nShop: https://stza.co/+vO8r-U\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144524Z
LAST-MODIFIED:20180213T144524Z
TRANSP:OPAQUE
END:VEVENT
* AquaSox vs. Emeralds
<2018-08-11 Sat 21:05>--<2018-08-12 Sun 00:05>
:PROPERTIES:
:ID:       JxD9C6SzmgLdk_YV1cUJE9B4@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

AquaSox vs. Emeralds AquaSox vs. Emeralds

Follow on MiLB First Pitch  https //stza.co/+vO8t-v

Shop  https //stza.co/+vO8t-1W

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:AquaSox vs. Emeralds
END:VALARM
DTSTART:20180812T020500Z
DTEND:20180812T050500Z
UID:JxD9C6SzmgLdk_YV1cUJE9B4@stanza.co
SUMMARY:AquaSox vs. Emeralds
DESCRIPTION:AquaSox vs. Emeralds\n\nFollow on MiLB First Pitch: https://stza.co/+vO8t-v\n\nShop: https://stza.co/+vO8t-1W\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144524Z
LAST-MODIFIED:20180213T144524Z
TRANSP:OPAQUE
END:VEVENT
* AquaSox vs. Emeralds
<2018-08-12 Sun 18:05-21:05>
:PROPERTIES:
:ID:       -poQdo4WRJvQ1sblU0nGhO7J@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

AquaSox vs. Emeralds AquaSox vs. Emeralds

Follow on MiLB First Pitch  https //stza.co/+vO8u-1U

Shop  https //stza.co/+vO8u-J

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:AquaSox vs. Emeralds
END:VALARM
DTSTART:20180812T230500Z
DTEND:20180813T020500Z
UID:-poQdo4WRJvQ1sblU0nGhO7J@stanza.co
SUMMARY:AquaSox vs. Emeralds
DESCRIPTION:AquaSox vs. Emeralds\n\nFollow on MiLB First Pitch: https://stza.co/+vO8u-1U\n\nShop: https://stza.co/+vO8u-J\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144524Z
LAST-MODIFIED:20180213T144524Z
TRANSP:OPAQUE
END:VEVENT
* AquaSox vs. Emeralds
<2018-08-13 Mon 21:05>--<2018-08-14 Tue 00:05>
:PROPERTIES:
:ID:       tT70XD2TFGZnmETNYN0AMnvQ@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

AquaSox vs. Emeralds AquaSox vs. Emeralds

Follow on MiLB First Pitch  https //stza.co/+vO8x-O

Shop  https //stza.co/+vO8x-16

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:AquaSox vs. Emeralds
END:VALARM
DTSTART:20180814T020500Z
DTEND:20180814T050500Z
UID:tT70XD2TFGZnmETNYN0AMnvQ@stanza.co
SUMMARY:AquaSox vs. Emeralds
DESCRIPTION:AquaSox vs. Emeralds\n\nFollow on MiLB First Pitch: https://stza.co/+vO8x-O\n\nShop: https://stza.co/+vO8x-16\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144524Z
LAST-MODIFIED:20180213T144524Z
TRANSP:OPAQUE
END:VEVENT
* AquaSox @ Indians
<2018-08-14 Tue 20:30-23:30>
:PROPERTIES:
:ID:       Iheoz-JqkKAf9QoBqTcCUWH3@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

AquaSox @ Indians AquaSox @ Indians

Follow on MiLB First Pitch  https //stza.co/+xC7L-4

Shop  https //stza.co/+xC7L-3Z

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:AquaSox @ Indians
END:VALARM
DTSTART:20180815T013000Z
DTEND:20180815T043000Z
UID:Iheoz-JqkKAf9QoBqTcCUWH3@stanza.co
SUMMARY:AquaSox @ Indians
DESCRIPTION:AquaSox @ Indians\n\nFollow on MiLB First Pitch: https://stza.co/+xC7L-4\n\nShop: https://stza.co/+xC7L-3Z\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144524Z
LAST-MODIFIED:20180213T144524Z
TRANSP:OPAQUE
END:VEVENT
* AquaSox @ Indians
<2018-08-15 Wed 20:30-23:30>
:PROPERTIES:
:ID:       iPW_zNNk0A6WTWWT52jaNB_J@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

AquaSox @ Indians AquaSox @ Indians

Follow on MiLB First Pitch  https //stza.co/+xC7Q-2n

Shop  https //stza.co/+xC7Q-2q

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:AquaSox @ Indians
END:VALARM
DTSTART:20180816T013000Z
DTEND:20180816T043000Z
UID:iPW_zNNk0A6WTWWT52jaNB_J@stanza.co
SUMMARY:AquaSox @ Indians
DESCRIPTION:AquaSox @ Indians\n\nFollow on MiLB First Pitch: https://stza.co/+xC7Q-2n\n\nShop: https://stza.co/+xC7Q-2q\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144524Z
LAST-MODIFIED:20180213T144524Z
TRANSP:OPAQUE
END:VEVENT
* AquaSox @ Indians
<2018-08-16 Thu 20:30-23:30>
:PROPERTIES:
:ID:       p6igzZpqkKggWeTwWD2W38cC@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

AquaSox @ Indians AquaSox @ Indians

Follow on MiLB First Pitch  https //stza.co/+xBhY-25

Shop  https //stza.co/+xBhY-3o

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:AquaSox @ Indians
END:VALARM
DTSTART:20180817T013000Z
DTEND:20180817T043000Z
UID:p6igzZpqkKggWeTwWD2W38cC@stanza.co
SUMMARY:AquaSox @ Indians
DESCRIPTION:AquaSox @ Indians\n\nFollow on MiLB First Pitch: https://stza.co/+xBhY-25\n\nShop: https://stza.co/+xBhY-3o\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144524Z
LAST-MODIFIED:20180213T144524Z
TRANSP:OPAQUE
END:VEVENT
* AquaSox @ Dust Devils
<2018-08-17 Fri 21:15>--<2018-08-18 Sat 00:15>
:PROPERTIES:
:ID:       QpKnxZeypXprorWOdlmHHTJ5@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

AquaSox @ Dust Devils AquaSox @ Dust Devils

Follow on MiLB First Pitch  https //stza.co/+vO91-3v

Shop  https //stza.co/+vO91-1h

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:AquaSox @ Dust Devils
END:VALARM
DTSTART:20180818T021500Z
DTEND:20180818T051500Z
UID:QpKnxZeypXprorWOdlmHHTJ5@stanza.co
SUMMARY:AquaSox @ Dust Devils
DESCRIPTION:AquaSox @ Dust Devils\n\nFollow on MiLB First Pitch: https://stza.co/+vO91-3v\n\nShop: https://stza.co/+vO91-1h\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144524Z
LAST-MODIFIED:20180213T144524Z
TRANSP:OPAQUE
END:VEVENT
* AquaSox @ Dust Devils
<2018-08-18 Sat 21:15>--<2018-08-19 Sun 00:15>
:PROPERTIES:
:ID:       P5BYx4aFHCH8xvwV24tK5UiW@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

AquaSox @ Dust Devils AquaSox @ Dust Devils

Follow on MiLB First Pitch  https //stza.co/+vO92-2$

Shop  https //stza.co/+vO92-1w

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:AquaSox @ Dust Devils
END:VALARM
DTSTART:20180819T021500Z
DTEND:20180819T051500Z
UID:P5BYx4aFHCH8xvwV24tK5UiW@stanza.co
SUMMARY:AquaSox @ Dust Devils
DESCRIPTION:AquaSox @ Dust Devils\n\nFollow on MiLB First Pitch: https://stza.co/+vO92-2$\n\nShop: https://stza.co/+vO92-1w\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144524Z
LAST-MODIFIED:20180213T144524Z
TRANSP:OPAQUE
END:VEVENT
* AquaSox @ Dust Devils
<2018-08-19 Sun 21:15>--<2018-08-20 Mon 00:15>
:PROPERTIES:
:ID:       dldOlISzMO9Itzt7w7BHw-wb@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

AquaSox @ Dust Devils AquaSox @ Dust Devils

Follow on MiLB First Pitch  https //stza.co/+vO93-1s

Shop  https //stza.co/+vO93-1J

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:AquaSox @ Dust Devils
END:VALARM
DTSTART:20180820T021500Z
DTEND:20180820T051500Z
UID:dldOlISzMO9Itzt7w7BHw-wb@stanza.co
SUMMARY:AquaSox @ Dust Devils
DESCRIPTION:AquaSox @ Dust Devils\n\nFollow on MiLB First Pitch: https://stza.co/+vO93-1s\n\nShop: https://stza.co/+vO93-1J\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144524Z
LAST-MODIFIED:20180213T144524Z
TRANSP:OPAQUE
END:VEVENT
* AquaSox vs. Indians
<2018-08-20 Mon 21:05>--<2018-08-21 Tue 00:05>
:PROPERTIES:
:ID:       mJskahPWJIZ-IxveZMJr7QNm@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

AquaSox vs. Indians AquaSox vs. Indians

Follow on MiLB First Pitch  https //stza.co/+vO8z-2s

Shop  https //stza.co/+vO8z-6

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:AquaSox vs. Indians
END:VALARM
DTSTART:20180821T020500Z
DTEND:20180821T050500Z
UID:mJskahPWJIZ-IxveZMJr7QNm@stanza.co
SUMMARY:AquaSox vs. Indians
DESCRIPTION:AquaSox vs. Indians\n\nFollow on MiLB First Pitch: https://stza.co/+vO8z-2s\n\nShop: https://stza.co/+vO8z-6\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144524Z
LAST-MODIFIED:20180213T144524Z
TRANSP:OPAQUE
END:VEVENT
* AquaSox vs. Indians
<2018-08-21 Tue 21:05>--<2018-08-22 Wed 00:05>
:PROPERTIES:
:ID:       ZmILveaib5rXm-FC4EY1nsfQ@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

AquaSox vs. Indians AquaSox vs. Indians

Follow on MiLB First Pitch  https //stza.co/+vO8B-2p

Shop  https //stza.co/+vO8B-3e

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:AquaSox vs. Indians
END:VALARM
DTSTART:20180822T020500Z
DTEND:20180822T050500Z
UID:ZmILveaib5rXm-FC4EY1nsfQ@stanza.co
SUMMARY:AquaSox vs. Indians
DESCRIPTION:AquaSox vs. Indians\n\nFollow on MiLB First Pitch: https://stza.co/+vO8B-2p\n\nShop: https://stza.co/+vO8B-3e\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144524Z
LAST-MODIFIED:20180213T144524Z
TRANSP:OPAQUE
END:VEVENT
* AquaSox vs. Indians
<2018-08-22 Wed 21:05>--<2018-08-23 Thu 00:05>
:PROPERTIES:
:ID:       dzidfHC0Kx6_i6JqvA4mqFRH@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

AquaSox vs. Indians AquaSox vs. Indians

Follow on MiLB First Pitch  https //stza.co/+vO8C-3s

Shop  https //stza.co/+vO8C-1_

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:AquaSox vs. Indians
END:VALARM
DTSTART:20180823T020500Z
DTEND:20180823T050500Z
UID:dzidfHC0Kx6_i6JqvA4mqFRH@stanza.co
SUMMARY:AquaSox vs. Indians
DESCRIPTION:AquaSox vs. Indians\n\nFollow on MiLB First Pitch: https://stza.co/+vO8C-3s\n\nShop: https://stza.co/+vO8C-1_\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144524Z
LAST-MODIFIED:20180213T144524Z
TRANSP:OPAQUE
END:VEVENT
* AquaSox @ Hops
<2018-08-23 Thu 21:05>--<2018-08-24 Fri 00:05>
:PROPERTIES:
:ID:       k5EsG52hhIVrGgcGrP3O50kv@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

AquaSox @ Hops AquaSox @ Hops

Follow on MiLB First Pitch  https //stza.co/+vO8K-1L

Shop  https //stza.co/+vO8K-b

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:AquaSox @ Hops
END:VALARM
DTSTART:20180824T020500Z
DTEND:20180824T050500Z
UID:k5EsG52hhIVrGgcGrP3O50kv@stanza.co
SUMMARY:AquaSox @ Hops
DESCRIPTION:AquaSox @ Hops\n\nFollow on MiLB First Pitch: https://stza.co/+vO8K-1L\n\nShop: https://stza.co/+vO8K-b\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144524Z
LAST-MODIFIED:20180213T144524Z
TRANSP:OPAQUE
END:VEVENT
* AquaSox @ Hops
<2018-08-24 Fri 21:05>--<2018-08-25 Sat 00:05>
:PROPERTIES:
:ID:       7gMRxFkfhe5cIEnT92yN8PPk@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

AquaSox @ Hops AquaSox @ Hops

Follow on MiLB First Pitch  https //stza.co/+vO8L-c

Shop  https //stza.co/+vO8L-2J

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:AquaSox @ Hops
END:VALARM
DTSTART:20180825T020500Z
DTEND:20180825T050500Z
UID:7gMRxFkfhe5cIEnT92yN8PPk@stanza.co
SUMMARY:AquaSox @ Hops
DESCRIPTION:AquaSox @ Hops\n\nFollow on MiLB First Pitch: https://stza.co/+vO8L-c\n\nShop: https://stza.co/+vO8L-2J\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144524Z
LAST-MODIFIED:20180213T144524Z
TRANSP:OPAQUE
END:VEVENT
* AquaSox @ Hops
<2018-08-25 Sat 21:05>--<2018-08-26 Sun 00:05>
:PROPERTIES:
:ID:       aJhZXhIH8Mm6GKtIfsRbM-sw@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

AquaSox @ Hops AquaSox @ Hops

Follow on MiLB First Pitch  https //stza.co/+vO8M-B

Shop  https //stza.co/+vO8M-c

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:AquaSox @ Hops
END:VALARM
DTSTART:20180826T020500Z
DTEND:20180826T050500Z
UID:aJhZXhIH8Mm6GKtIfsRbM-sw@stanza.co
SUMMARY:AquaSox @ Hops
DESCRIPTION:AquaSox @ Hops\n\nFollow on MiLB First Pitch: https://stza.co/+vO8M-B\n\nShop: https://stza.co/+vO8M-c\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144524Z
LAST-MODIFIED:20180213T144524Z
TRANSP:OPAQUE
END:VEVENT
* AquaSox @ Hops
<2018-08-26 Sun 18:05-21:05>
:PROPERTIES:
:ID:       l380t_uUy5MAGUEUZgQaq6jB@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

AquaSox @ Hops AquaSox @ Hops

Follow on MiLB First Pitch  https //stza.co/+vO8N-1d

Shop  https //stza.co/+vO8N-3U

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:AquaSox @ Hops
END:VALARM
DTSTART:20180826T230500Z
DTEND:20180827T020500Z
UID:l380t_uUy5MAGUEUZgQaq6jB@stanza.co
SUMMARY:AquaSox @ Hops
DESCRIPTION:AquaSox @ Hops\n\nFollow on MiLB First Pitch: https://stza.co/+vO8N-1d\n\nShop: https://stza.co/+vO8N-3U\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144524Z
LAST-MODIFIED:20180213T144524Z
TRANSP:OPAQUE
END:VEVENT
* AquaSox @ Hops
<2018-08-27 Mon 15:05-18:05>
:PROPERTIES:
:ID:       BtV3DPEbwciO6QB9QcH43B9v@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

AquaSox @ Hops AquaSox @ Hops

Follow on MiLB First Pitch  https //stza.co/+vO8O-1e

Shop  https //stza.co/+vO8O-1Y

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:AquaSox @ Hops
END:VALARM
DTSTART:20180827T200500Z
DTEND:20180827T230500Z
UID:BtV3DPEbwciO6QB9QcH43B9v@stanza.co
SUMMARY:AquaSox @ Hops
DESCRIPTION:AquaSox @ Hops\n\nFollow on MiLB First Pitch: https://stza.co/+vO8O-1e\n\nShop: https://stza.co/+vO8O-1Y\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144524Z
LAST-MODIFIED:20180213T144524Z
TRANSP:OPAQUE
END:VEVENT
* AquaSox @ Canadians
<2018-08-29 Wed 21:05>--<2018-08-30 Thu 00:05>
:PROPERTIES:
:ID:       gUkvrRJ_WqFyEEH4mXaJlR1O@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

AquaSox @ Canadians AquaSox @ Canadians

Follow on MiLB First Pitch  https //stza.co/+xXUS-2K

Shop  https //stza.co/+xXUS-J

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:AquaSox @ Canadians
END:VALARM
DTSTART:20180830T020500Z
DTEND:20180830T050500Z
UID:gUkvrRJ_WqFyEEH4mXaJlR1O@stanza.co
SUMMARY:AquaSox @ Canadians
DESCRIPTION:AquaSox @ Canadians\n\nFollow on MiLB First Pitch: https://stza.co/+xXUS-2K\n\nShop: https://stza.co/+xXUS-J\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144524Z
LAST-MODIFIED:20180213T144524Z
TRANSP:OPAQUE
END:VEVENT
* AquaSox @ Canadians
<2018-08-30 Thu 21:05>--<2018-08-31 Fri 00:05>
:PROPERTIES:
:ID:       j45sttvSpLMA2xXXXeL8c9aE@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

AquaSox @ Canadians AquaSox @ Canadians

Follow on MiLB First Pitch  https //stza.co/+xXUT-2c

Shop  https //stza.co/+xXUT-3g

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:AquaSox @ Canadians
END:VALARM
DTSTART:20180831T020500Z
DTEND:20180831T050500Z
UID:j45sttvSpLMA2xXXXeL8c9aE@stanza.co
SUMMARY:AquaSox @ Canadians
DESCRIPTION:AquaSox @ Canadians\n\nFollow on MiLB First Pitch: https://stza.co/+xXUT-2c\n\nShop: https://stza.co/+xXUT-3g\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144524Z
LAST-MODIFIED:20180213T144524Z
TRANSP:OPAQUE
END:VEVENT
* AquaSox @ Canadians
<2018-08-31 Fri 15:05-18:05>
:PROPERTIES:
:ID:       qMa7PaDgv0m3m15h6qf1FONY@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

AquaSox @ Canadians AquaSox @ Canadians

Follow on MiLB First Pitch  https //stza.co/+xXUU-2J

Shop  https //stza.co/+xXUU-3T

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:AquaSox @ Canadians
END:VALARM
DTSTART:20180831T200500Z
DTEND:20180831T230500Z
UID:qMa7PaDgv0m3m15h6qf1FONY@stanza.co
SUMMARY:AquaSox @ Canadians
DESCRIPTION:AquaSox @ Canadians\n\nFollow on MiLB First Pitch: https://stza.co/+xXUU-2J\n\nShop: https://stza.co/+xXUU-3T\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144524Z
LAST-MODIFIED:20180213T144524Z
TRANSP:OPAQUE
END:VEVENT
* AquaSox vs. Dust Devils
<2018-09-01 Sat 21:05>--<2018-09-02 Sun 00:05>
:PROPERTIES:
:ID:       2LZTgvkXEMAxzSJUTOu_M0Wo@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

AquaSox vs. Dust Devils AquaSox vs. Dust Devils

Follow on MiLB First Pitch  https //stza.co/+vO8F-2z

Shop  https //stza.co/+vO8F-1E

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:AquaSox vs. Dust Devils
END:VALARM
DTSTART:20180902T020500Z
DTEND:20180902T050500Z
UID:2LZTgvkXEMAxzSJUTOu_M0Wo@stanza.co
SUMMARY:AquaSox vs. Dust Devils
DESCRIPTION:AquaSox vs. Dust Devils\n\nFollow on MiLB First Pitch: https://stza.co/+vO8F-2z\n\nShop: https://stza.co/+vO8F-1E\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144524Z
LAST-MODIFIED:20180213T144524Z
TRANSP:OPAQUE
END:VEVENT
* AquaSox vs. Dust Devils
<2018-09-02 Sun 18:05-21:05>
:PROPERTIES:
:ID:       VHDycLqZVmgrCp7rxb4yz4Cg@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

AquaSox vs. Dust Devils AquaSox vs. Dust Devils

Follow on MiLB First Pitch  https //stza.co/+vO8H-3V

Shop  https //stza.co/+vO8H-3L

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:AquaSox vs. Dust Devils
END:VALARM
DTSTART:20180902T230500Z
DTEND:20180903T020500Z
UID:VHDycLqZVmgrCp7rxb4yz4Cg@stanza.co
SUMMARY:AquaSox vs. Dust Devils
DESCRIPTION:AquaSox vs. Dust Devils\n\nFollow on MiLB First Pitch: https://stza.co/+vO8H-3V\n\nShop: https://stza.co/+vO8H-3L\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144524Z
LAST-MODIFIED:20180213T144524Z
TRANSP:OPAQUE
END:VEVENT
* AquaSox vs. Dust Devils
<2018-09-03 Mon 18:05-21:05>
:PROPERTIES:
:ID:       Oem1M0KTmHW6-lovwcM27ZIF@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

AquaSox vs. Dust Devils AquaSox vs. Dust Devils

Follow on MiLB First Pitch  https //stza.co/+vO8J-9

Shop  https //stza.co/+vO8J-V

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:AquaSox vs. Dust Devils
END:VALARM
DTSTART:20180903T230500Z
DTEND:20180904T020500Z
UID:Oem1M0KTmHW6-lovwcM27ZIF@stanza.co
SUMMARY:AquaSox vs. Dust Devils
DESCRIPTION:AquaSox vs. Dust Devils\n\nFollow on MiLB First Pitch: https://stza.co/+vO8J-9\n\nShop: https://stza.co/+vO8J-V\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144524Z
LAST-MODIFIED:20180213T144524Z
TRANSP:OPAQUE
END:VEVENT
