#+TITLE:       Main Google calendar entries
#+AUTHOR:      Eric S Fraga
#+EMAIL:       e.fraga@ucl.ac.uk
#+DESCRIPTION: converted using the ical2org awk script
#+CATEGORY:    google
#+STARTUP:     hidestars
#+STARTUP:     overview

* COMMENT original iCal preamble

* Shorebirds vs. Tourists
<2018-04-05 Thu 18:05-21:05>
:PROPERTIES:
:ID:       AYd0OixYoU3HIWQyeDazzG4F@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Shorebirds vs. Tourists Shorebirds vs. Tourists

Follow on MiLB First Pitch  https //stza.co/+wHM1-J

Shop  https //stza.co/+wHM1-35

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Shorebirds vs. Tourists
END:VALARM
DTSTART:20180405T230500Z
DTEND:20180406T020500Z
UID:AYd0OixYoU3HIWQyeDazzG4F@stanza.co
SUMMARY:Shorebirds vs. Tourists
DESCRIPTION:Shorebirds vs. Tourists\n\nFollow on MiLB First Pitch: https://stza.co/+wHM1-J\n\nShop: https://stza.co/+wHM1-35\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144519Z
LAST-MODIFIED:20180213T144519Z
TRANSP:OPAQUE
END:VEVENT
* Shorebirds vs. Tourists
<2018-04-06 Fri 18:05-21:05>
:PROPERTIES:
:ID:       7ZageERygJMeBK-v261NxBGU@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Shorebirds vs. Tourists Shorebirds vs. Tourists

Follow on MiLB First Pitch  https //stza.co/+wHMf-3t

Shop  https //stza.co/+wHMf-2c

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Shorebirds vs. Tourists
END:VALARM
DTSTART:20180406T230500Z
DTEND:20180407T020500Z
UID:7ZageERygJMeBK-v261NxBGU@stanza.co
SUMMARY:Shorebirds vs. Tourists
DESCRIPTION:Shorebirds vs. Tourists\n\nFollow on MiLB First Pitch: https://stza.co/+wHMf-3t\n\nShop: https://stza.co/+wHMf-2c\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144519Z
LAST-MODIFIED:20180213T144519Z
TRANSP:OPAQUE
END:VEVENT
* Shorebirds vs. Tourists
<2018-04-07 Sat 18:05-21:05>
:PROPERTIES:
:ID:       A-hQYpYoJA_yAh1YfqT1NxZn@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Shorebirds vs. Tourists Shorebirds vs. Tourists

Follow on MiLB First Pitch  https //stza.co/+wHMp-26

Shop  https //stza.co/+wHMp-C

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Shorebirds vs. Tourists
END:VALARM
DTSTART:20180407T230500Z
DTEND:20180408T020500Z
UID:A-hQYpYoJA_yAh1YfqT1NxZn@stanza.co
SUMMARY:Shorebirds vs. Tourists
DESCRIPTION:Shorebirds vs. Tourists\n\nFollow on MiLB First Pitch: https://stza.co/+wHMp-26\n\nShop: https://stza.co/+wHMp-C\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144519Z
LAST-MODIFIED:20180213T144519Z
TRANSP:OPAQUE
END:VEVENT
* Shorebirds vs. Tourists
<2018-04-08 Sun 13:05-16:05>
:PROPERTIES:
:ID:       p7EuFKNqUtyI7m0SQUFVWUGG@stanza.co
:LOCATION: Kids run the bases for today's game. Bring out the family!
:STATUS:   CONFIRMED
:END:

Shorebirds vs. Tourists Bring 2 canned food items to the Shorebirds box office and receive an upper reserved ticket for $3. All collected items will be donated to the local area food banks.

Kids 13 & under get to run the bases after the game, presented by Chili's Grill & Bar.

Follow on MiLB First Pitch  https //stza.co/+wHMt-3m

Shop  https //stza.co/+wHMt-2N

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Shorebirds vs. Tourists
END:VALARM
DTSTART:20180408T180500Z
DTEND:20180408T210500Z
UID:p7EuFKNqUtyI7m0SQUFVWUGG@stanza.co
SUMMARY:Shorebirds vs. Tourists
DESCRIPTION:Bring 2 canned food items to the Shorebirds box office and receive an upper reserved ticket for $3. All collected items will be donated to the local area food banks.\n\nKids 13 & under get to run the bases after the game, presented by Chili's Grill & Bar.\n\nFollow on MiLB First Pitch: https://stza.co/+wHMt-3m\n\nShop: https://stza.co/+wHMt-2N\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Kids run the bases for today's game. Bring out the family!
STATUS:CONFIRMED
CREATED:20180213T144519Z
LAST-MODIFIED:20180213T144519Z
TRANSP:OPAQUE
END:VEVENT
* Shorebirds vs. Crawdads
<2018-04-09 Mon 18:05-21:05>
:PROPERTIES:
:ID:       yvJILpY-J8zp4jsufMWZ_AHw@stanza.co
:LOCATION: 47 ABC 2 Buck Monday
:STATUS:   CONFIRMED
:END:

Shorebirds vs. Crawdads Enjoy $2 Upper Reserved tickets, $2 hotdogs, and $2 fountain Pepsi products.

Follow on MiLB First Pitch  https //stza.co/+wHMF-3Z

Shop  https //stza.co/+wHMF-3S

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Shorebirds vs. Crawdads
END:VALARM
DTSTART:20180409T230500Z
DTEND:20180410T020500Z
UID:yvJILpY-J8zp4jsufMWZ_AHw@stanza.co
SUMMARY:Shorebirds vs. Crawdads
DESCRIPTION:Enjoy $2 Upper Reserved tickets, $2 hotdogs, and $2 fountain Pepsi products.\n\nFollow on MiLB First Pitch: https://stza.co/+wHMF-3Z\n\nShop: https://stza.co/+wHMF-3S\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:47 ABC 2 Buck Monday
STATUS:CONFIRMED
CREATED:20180213T144519Z
LAST-MODIFIED:20180213T144519Z
TRANSP:OPAQUE
END:VEVENT
* Shorebirds vs. Crawdads
<2018-04-10 Tue 18:05-21:05>
:PROPERTIES:
:ID:       aSPoqpCd_Gqx21EAAVBB9nVo@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Shorebirds vs. Crawdads Shorebirds vs. Crawdads

Follow on MiLB First Pitch  https //stza.co/+wHMP-i

Shop  https //stza.co/+wHMP-1l

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Shorebirds vs. Crawdads
END:VALARM
DTSTART:20180410T230500Z
DTEND:20180411T020500Z
UID:aSPoqpCd_Gqx21EAAVBB9nVo@stanza.co
SUMMARY:Shorebirds vs. Crawdads
DESCRIPTION:Shorebirds vs. Crawdads\n\nFollow on MiLB First Pitch: https://stza.co/+wHMP-i\n\nShop: https://stza.co/+wHMP-1l\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144519Z
LAST-MODIFIED:20180213T144519Z
TRANSP:OPAQUE
END:VEVENT
* Shorebirds vs. Crawdads
<2018-04-11 Wed 09:35-12:35>
:PROPERTIES:
:ID:       uUuc2fXLvd82SBqT4-FCLZdM@stanza.co
:LOCATION: Silver Slugger Game
:STATUS:   CONFIRMED
:END:

Shorebirds vs. Crawdads This game is included in the Silver Sluggers membership for fans 55 and up.

Follow on MiLB First Pitch  https //stza.co/+wHM$-3N

Shop  https //stza.co/+wHM$-2R

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Shorebirds vs. Crawdads
END:VALARM
DTSTART:20180411T143500Z
DTEND:20180411T173500Z
UID:uUuc2fXLvd82SBqT4-FCLZdM@stanza.co
SUMMARY:Shorebirds vs. Crawdads
DESCRIPTION:This game is included in the Silver Sluggers membership for fans 55 and up.\n\nFollow on MiLB First Pitch: https://stza.co/+wHM$-3N\n\nShop: https://stza.co/+wHM$-2R\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Silver Slugger Game
STATUS:CONFIRMED
CREATED:20180213T144519Z
LAST-MODIFIED:20180213T144519Z
TRANSP:OPAQUE
END:VEVENT
* Shorebirds @ BlueClaws
<2018-04-12 Thu 17:35-20:35>
:PROPERTIES:
:ID:       0atC7fNXMGuVuxDnxb9ZPS_z@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Shorebirds @ BlueClaws Shorebirds @ BlueClaws

Follow on MiLB First Pitch  https //stza.co/+vNIA-13

Shop  https //stza.co/+vNIA-1u

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Shorebirds @ BlueClaws
END:VALARM
DTSTART:20180412T223500Z
DTEND:20180413T013500Z
UID:0atC7fNXMGuVuxDnxb9ZPS_z@stanza.co
SUMMARY:Shorebirds @ BlueClaws
DESCRIPTION:Shorebirds @ BlueClaws\n\nFollow on MiLB First Pitch: https://stza.co/+vNIA-13\n\nShop: https://stza.co/+vNIA-1u\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144519Z
LAST-MODIFIED:20180213T144519Z
TRANSP:OPAQUE
END:VEVENT
* Shorebirds @ BlueClaws
<2018-04-13 Fri 18:05-21:05>
:PROPERTIES:
:ID:       0rDaHdq_Priel22gsZn75yHT@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Shorebirds @ BlueClaws Shorebirds @ BlueClaws

Follow on MiLB First Pitch  https //stza.co/+vNIB-3i

Shop  https //stza.co/+vNIB-1k

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Shorebirds @ BlueClaws
END:VALARM
DTSTART:20180413T230500Z
DTEND:20180414T020500Z
UID:0rDaHdq_Priel22gsZn75yHT@stanza.co
SUMMARY:Shorebirds @ BlueClaws
DESCRIPTION:Shorebirds @ BlueClaws\n\nFollow on MiLB First Pitch: https://stza.co/+vNIB-3i\n\nShop: https://stza.co/+vNIB-1k\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144519Z
LAST-MODIFIED:20180213T144519Z
TRANSP:OPAQUE
END:VEVENT
* Shorebirds @ BlueClaws
<2018-04-14 Sat 15:05-18:05>
:PROPERTIES:
:ID:       oeGuqrB4E_M5GvpjWYxFIGv0@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Shorebirds @ BlueClaws Shorebirds @ BlueClaws

Follow on MiLB First Pitch  https //stza.co/+vNIC-2h

Shop  https //stza.co/+vNIC-2Q

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Shorebirds @ BlueClaws
END:VALARM
DTSTART:20180414T200500Z
DTEND:20180414T230500Z
UID:oeGuqrB4E_M5GvpjWYxFIGv0@stanza.co
SUMMARY:Shorebirds @ BlueClaws
DESCRIPTION:Shorebirds @ BlueClaws\n\nFollow on MiLB First Pitch: https://stza.co/+vNIC-2h\n\nShop: https://stza.co/+vNIC-2Q\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144519Z
LAST-MODIFIED:20180213T144519Z
TRANSP:OPAQUE
END:VEVENT
* Shorebirds @ BlueClaws
<2018-04-15 Sun 12:05-15:05>
:PROPERTIES:
:ID:       w-UoF3SSFM3iIIvJIYIyaONg@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Shorebirds @ BlueClaws Shorebirds @ BlueClaws

Follow on MiLB First Pitch  https //stza.co/+vNID-1M

Shop  https //stza.co/+vNID-2G

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Shorebirds @ BlueClaws
END:VALARM
DTSTART:20180415T170500Z
DTEND:20180415T200500Z
UID:w-UoF3SSFM3iIIvJIYIyaONg@stanza.co
SUMMARY:Shorebirds @ BlueClaws
DESCRIPTION:Shorebirds @ BlueClaws\n\nFollow on MiLB First Pitch: https://stza.co/+vNID-1M\n\nShop: https://stza.co/+vNID-2G\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144519Z
LAST-MODIFIED:20180213T144519Z
TRANSP:OPAQUE
END:VEVENT
* Shorebirds @ Suns
<2018-04-16 Mon 17:05-20:05>
:PROPERTIES:
:ID:       GXPpmEx5XLfJqUHRerjlclEj@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Shorebirds @ Suns Shorebirds @ Suns

Follow on MiLB First Pitch  https //stza.co/+xE_2-3C

Shop  https //stza.co/+xE_2-24

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Shorebirds @ Suns
END:VALARM
DTSTART:20180416T220500Z
DTEND:20180417T010500Z
UID:GXPpmEx5XLfJqUHRerjlclEj@stanza.co
SUMMARY:Shorebirds @ Suns
DESCRIPTION:Shorebirds @ Suns\n\nFollow on MiLB First Pitch: https://stza.co/+xE_2-3C\n\nShop: https://stza.co/+xE_2-24\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144519Z
LAST-MODIFIED:20180213T144519Z
TRANSP:OPAQUE
END:VEVENT
* Shorebirds @ Suns
<2018-04-17 Tue 17:05-20:05>
:PROPERTIES:
:ID:       Y-2h0AX8naQNv7UwvQKv-Vs-@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Shorebirds @ Suns Shorebirds @ Suns

Follow on MiLB First Pitch  https //stza.co/+xE_3-3a

Shop  https //stza.co/+xE_3-C

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Shorebirds @ Suns
END:VALARM
DTSTART:20180417T220500Z
DTEND:20180418T010500Z
UID:Y-2h0AX8naQNv7UwvQKv-Vs-@stanza.co
SUMMARY:Shorebirds @ Suns
DESCRIPTION:Shorebirds @ Suns\n\nFollow on MiLB First Pitch: https://stza.co/+xE_3-3a\n\nShop: https://stza.co/+xE_3-C\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144519Z
LAST-MODIFIED:20180213T144519Z
TRANSP:OPAQUE
END:VEVENT
* Shorebirds @ Suns
<2018-04-18 Wed 09:35-12:35>
:PROPERTIES:
:ID:       rl6zHuAjY42gV4gTXJa3MdOk@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Shorebirds @ Suns Shorebirds @ Suns

Follow on MiLB First Pitch  https //stza.co/+xE_4-1

Shop  https //stza.co/+xE_4-3d

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Shorebirds @ Suns
END:VALARM
DTSTART:20180418T143500Z
DTEND:20180418T173500Z
UID:rl6zHuAjY42gV4gTXJa3MdOk@stanza.co
SUMMARY:Shorebirds @ Suns
DESCRIPTION:Shorebirds @ Suns\n\nFollow on MiLB First Pitch: https://stza.co/+xE_4-1\n\nShop: https://stza.co/+xE_4-3d\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144519Z
LAST-MODIFIED:20180213T144519Z
TRANSP:OPAQUE
END:VEVENT
* Shorebirds vs. BlueClaws
<2018-04-19 Thu 18:05-21:05>
:PROPERTIES:
:ID:       fcqy_064I1LoK7YgopZs8067@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Shorebirds vs. BlueClaws Shorebirds vs. BlueClaws

Follow on MiLB First Pitch  https //stza.co/+wHNb-1l

Shop  https //stza.co/+wHNb-1S

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Shorebirds vs. BlueClaws
END:VALARM
DTSTART:20180419T230500Z
DTEND:20180420T020500Z
UID:fcqy_064I1LoK7YgopZs8067@stanza.co
SUMMARY:Shorebirds vs. BlueClaws
DESCRIPTION:Shorebirds vs. BlueClaws\n\nFollow on MiLB First Pitch: https://stza.co/+wHNb-1l\n\nShop: https://stza.co/+wHNb-1S\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144519Z
LAST-MODIFIED:20180213T144519Z
TRANSP:OPAQUE
END:VEVENT
* Shorebirds vs. BlueClaws
<2018-04-20 Fri 18:05-21:05>
:PROPERTIES:
:ID:       RX5TogqJcRg4MEGY_jbWAdLl@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Shorebirds vs. BlueClaws Shorebirds vs. BlueClaws

Follow on MiLB First Pitch  https //stza.co/+wHNo-2

Shop  https //stza.co/+wHNo-L

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Shorebirds vs. BlueClaws
END:VALARM
DTSTART:20180420T230500Z
DTEND:20180421T020500Z
UID:RX5TogqJcRg4MEGY_jbWAdLl@stanza.co
SUMMARY:Shorebirds vs. BlueClaws
DESCRIPTION:Shorebirds vs. BlueClaws\n\nFollow on MiLB First Pitch: https://stza.co/+wHNo-2\n\nShop: https://stza.co/+wHNo-L\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144519Z
LAST-MODIFIED:20180213T144519Z
TRANSP:OPAQUE
END:VEVENT
* Shorebirds vs. BlueClaws
<2018-04-21 Sat 18:05-21:05>
:PROPERTIES:
:ID:       jMf021PF2Cw_j2bsD2_zytcz@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Shorebirds vs. BlueClaws Shorebirds vs. BlueClaws

Follow on MiLB First Pitch  https //stza.co/+wHNB-1k

Shop  https //stza.co/+wHNB-32

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Shorebirds vs. BlueClaws
END:VALARM
DTSTART:20180421T230500Z
DTEND:20180422T020500Z
UID:jMf021PF2Cw_j2bsD2_zytcz@stanza.co
SUMMARY:Shorebirds vs. BlueClaws
DESCRIPTION:Shorebirds vs. BlueClaws\n\nFollow on MiLB First Pitch: https://stza.co/+wHNB-1k\n\nShop: https://stza.co/+wHNB-32\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144519Z
LAST-MODIFIED:20180213T144519Z
TRANSP:OPAQUE
END:VEVENT
* Shorebirds vs. BlueClaws
<2018-04-22 Sun 13:05-16:05>
:PROPERTIES:
:ID:       Makxx41_TR8oPz6eNAZd1ldC@stanza.co
:LOCATION: Kids run the bases for today's game. Bring out the family!
:STATUS:   CONFIRMED
:END:

Shorebirds vs. BlueClaws Bring 2 canned food items to the Shorebirds box office and receive an upper reserved ticket for $3. All collected items will be donated to the local area food banks.

Kids 13 & under get to run the bases after the game, presented by Chili's Grill & Bar.

Follow on MiLB First Pitch  https //stza.co/+wHNH-1d

Shop  https //stza.co/+wHNH-2j

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Shorebirds vs. BlueClaws
END:VALARM
DTSTART:20180422T180500Z
DTEND:20180422T210500Z
UID:Makxx41_TR8oPz6eNAZd1ldC@stanza.co
SUMMARY:Shorebirds vs. BlueClaws
DESCRIPTION:Bring 2 canned food items to the Shorebirds box office and receive an upper reserved ticket for $3. All collected items will be donated to the local area food banks.\n\nKids 13 & under get to run the bases after the game, presented by Chili's Grill & Bar.\n\nFollow on MiLB First Pitch: https://stza.co/+wHNH-1d\n\nShop: https://stza.co/+wHNH-2j\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Kids run the bases for today's game. Bring out the family!
STATUS:CONFIRMED
CREATED:20180213T144519Z
LAST-MODIFIED:20180213T144519Z
TRANSP:OPAQUE
END:VEVENT
* Shorebirds vs. Intimidators
<2018-04-23 Mon 18:05-21:05>
:PROPERTIES:
:ID:       Lan0U9HAFYCaKu4cTW_AQZJt@stanza.co
:LOCATION: 47 ABC 2 Buck Monday
:STATUS:   CONFIRMED
:END:

Shorebirds vs. Intimidators Enjoy $2 Upper Reserved tickets, $2 hotdogs, and $2 fountain Pepsi products.

Follow on MiLB First Pitch  https //stza.co/+wHNU-1a

Shop  https //stza.co/+wHNU-2q

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Shorebirds vs. Intimidators
END:VALARM
DTSTART:20180423T230500Z
DTEND:20180424T020500Z
UID:Lan0U9HAFYCaKu4cTW_AQZJt@stanza.co
SUMMARY:Shorebirds vs. Intimidators
DESCRIPTION:Enjoy $2 Upper Reserved tickets, $2 hotdogs, and $2 fountain Pepsi products.\n\nFollow on MiLB First Pitch: https://stza.co/+wHNU-1a\n\nShop: https://stza.co/+wHNU-2q\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:47 ABC 2 Buck Monday
STATUS:CONFIRMED
CREATED:20180213T144519Z
LAST-MODIFIED:20180213T144519Z
TRANSP:OPAQUE
END:VEVENT
* Shorebirds vs. Intimidators
<2018-04-24 Tue 18:05-21:05>
:PROPERTIES:
:ID:       D7EfalxqxRs0YWsH5cF_Adoj@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Shorebirds vs. Intimidators Shorebirds vs. Intimidators

Follow on MiLB First Pitch  https //stza.co/+wHO0-1C

Shop  https //stza.co/+wHO0-2A

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Shorebirds vs. Intimidators
END:VALARM
DTSTART:20180424T230500Z
DTEND:20180425T020500Z
UID:D7EfalxqxRs0YWsH5cF_Adoj@stanza.co
SUMMARY:Shorebirds vs. Intimidators
DESCRIPTION:Shorebirds vs. Intimidators\n\nFollow on MiLB First Pitch: https://stza.co/+wHO0-1C\n\nShop: https://stza.co/+wHO0-2A\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144519Z
LAST-MODIFIED:20180213T144519Z
TRANSP:OPAQUE
END:VEVENT
* Shorebirds vs. Intimidators
<2018-04-25 Wed 18:05-21:05>
:PROPERTIES:
:ID:       iIw7f9IUYOdciicneo7KZR-r@stanza.co
:LOCATION: Silver Slugger Game
:STATUS:   CONFIRMED
:END:

Shorebirds vs. Intimidators This game is included in the Silver Sluggers membership for fans 55 and up.

Follow on MiLB First Pitch  https //stza.co/+wHO4-1g

Shop  https //stza.co/+wHO4-1P

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Shorebirds vs. Intimidators
END:VALARM
DTSTART:20180425T230500Z
DTEND:20180426T020500Z
UID:iIw7f9IUYOdciicneo7KZR-r@stanza.co
SUMMARY:Shorebirds vs. Intimidators
DESCRIPTION:This game is included in the Silver Sluggers membership for fans 55 and up.\n\nFollow on MiLB First Pitch: https://stza.co/+wHO4-1g\n\nShop: https://stza.co/+wHO4-1P\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Silver Slugger Game
STATUS:CONFIRMED
CREATED:20180213T144519Z
LAST-MODIFIED:20180213T144519Z
TRANSP:OPAQUE
END:VEVENT
* Shorebirds vs. Intimidators
<2018-04-26 Thu 09:35-12:35>
:PROPERTIES:
:ID:       3BG88RGH-GlVJ6zHhsx4tERi@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Shorebirds vs. Intimidators Shorebirds vs. Intimidators

Follow on MiLB First Pitch  https //stza.co/+wHO9-1M

Shop  https //stza.co/+wHO9-3p

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Shorebirds vs. Intimidators
END:VALARM
DTSTART:20180426T143500Z
DTEND:20180426T173500Z
UID:3BG88RGH-GlVJ6zHhsx4tERi@stanza.co
SUMMARY:Shorebirds vs. Intimidators
DESCRIPTION:Shorebirds vs. Intimidators\n\nFollow on MiLB First Pitch: https://stza.co/+wHO9-1M\n\nShop: https://stza.co/+wHO9-3p\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144519Z
LAST-MODIFIED:20180213T144519Z
TRANSP:OPAQUE
END:VEVENT
* Shorebirds @ Crawdads
<2018-04-27 Fri 18:00-21:00>
:PROPERTIES:
:ID:       gptmVwQbs-g9yjjjHksGZfrp@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Shorebirds @ Crawdads Shorebirds @ Crawdads

Follow on MiLB First Pitch  https //stza.co/+w0Oh-36

Shop  https //stza.co/+w0Oh-2t

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Shorebirds @ Crawdads
END:VALARM
DTSTART:20180427T230000Z
DTEND:20180428T020000Z
UID:gptmVwQbs-g9yjjjHksGZfrp@stanza.co
SUMMARY:Shorebirds @ Crawdads
DESCRIPTION:Shorebirds @ Crawdads\n\nFollow on MiLB First Pitch: https://stza.co/+w0Oh-36\n\nShop: https://stza.co/+w0Oh-2t\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144519Z
LAST-MODIFIED:20180213T144519Z
TRANSP:OPAQUE
END:VEVENT
* Shorebirds @ Crawdads
<2018-04-28 Sat 16:00-19:00>
:PROPERTIES:
:ID:       11MLow-mp5JRVIchsPONHqcL@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Shorebirds @ Crawdads Shorebirds @ Crawdads

Follow on MiLB First Pitch  https //stza.co/+xB1j-1v

Shop  https //stza.co/+xB1j-3V

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Shorebirds @ Crawdads
END:VALARM
DTSTART:20180428T210000Z
DTEND:20180429T000000Z
UID:11MLow-mp5JRVIchsPONHqcL@stanza.co
SUMMARY:Shorebirds @ Crawdads
DESCRIPTION:Shorebirds @ Crawdads\n\nFollow on MiLB First Pitch: https://stza.co/+xB1j-1v\n\nShop: https://stza.co/+xB1j-3V\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144519Z
LAST-MODIFIED:20180213T144519Z
TRANSP:OPAQUE
END:VEVENT
* Shorebirds @ Crawdads
<2018-04-29 Sun 14:00-17:00>
:PROPERTIES:
:ID:       fvF8KhggtQmHmQOM5LNm825h@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Shorebirds @ Crawdads Shorebirds @ Crawdads

Follow on MiLB First Pitch  https //stza.co/+w0Oj-1w

Shop  https //stza.co/+w0Oj-j

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Shorebirds @ Crawdads
END:VALARM
DTSTART:20180429T190000Z
DTEND:20180429T220000Z
UID:fvF8KhggtQmHmQOM5LNm825h@stanza.co
SUMMARY:Shorebirds @ Crawdads
DESCRIPTION:Shorebirds @ Crawdads\n\nFollow on MiLB First Pitch: https://stza.co/+w0Oj-1w\n\nShop: https://stza.co/+w0Oj-j\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144519Z
LAST-MODIFIED:20180213T144519Z
TRANSP:OPAQUE
END:VEVENT
* Shorebirds vs. Drive
<2018-05-01 Tue 18:05-21:05>
:PROPERTIES:
:ID:       gKnxBcpqo6X2cEWKOPAF7t3a@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Shorebirds vs. Drive Shorebirds vs. Drive

Follow on MiLB First Pitch  https //stza.co/+wHOd-3e

Shop  https //stza.co/+wHOd-1d

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Shorebirds vs. Drive
END:VALARM
DTSTART:20180501T230500Z
DTEND:20180502T020500Z
UID:gKnxBcpqo6X2cEWKOPAF7t3a@stanza.co
SUMMARY:Shorebirds vs. Drive
DESCRIPTION:Shorebirds vs. Drive\n\nFollow on MiLB First Pitch: https://stza.co/+wHOd-3e\n\nShop: https://stza.co/+wHOd-1d\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144519Z
LAST-MODIFIED:20180213T144519Z
TRANSP:OPAQUE
END:VEVENT
* Shorebirds vs. Drive
<2018-05-02 Wed 18:05-21:05>
:PROPERTIES:
:ID:       8qzwt-5BgV2LEZ1h4KQ8Xne4@stanza.co
:LOCATION: Silver Slugger Game
:STATUS:   CONFIRMED
:END:

Shorebirds vs. Drive This game is included in the Silver Sluggers membership for fans 55 and up.

Follow on MiLB First Pitch  https //stza.co/+wHOi-2R

Shop  https //stza.co/+wHOi-1m

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Shorebirds vs. Drive
END:VALARM
DTSTART:20180502T230500Z
DTEND:20180503T020500Z
UID:8qzwt-5BgV2LEZ1h4KQ8Xne4@stanza.co
SUMMARY:Shorebirds vs. Drive
DESCRIPTION:This game is included in the Silver Sluggers membership for fans 55 and up.\n\nFollow on MiLB First Pitch: https://stza.co/+wHOi-2R\n\nShop: https://stza.co/+wHOi-1m\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Silver Slugger Game
STATUS:CONFIRMED
CREATED:20180213T144519Z
LAST-MODIFIED:20180213T144519Z
TRANSP:OPAQUE
END:VEVENT
* Shorebirds vs. Drive
<2018-05-03 Thu 09:35-12:35>
:PROPERTIES:
:ID:       Pz_zgUkmdCrSTjWvY2r4DMo_@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Shorebirds vs. Drive Shorebirds vs. Drive

Follow on MiLB First Pitch  https //stza.co/+wHOm-2L

Shop  https //stza.co/+wHOm-29

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Shorebirds vs. Drive
END:VALARM
DTSTART:20180503T143500Z
DTEND:20180503T173500Z
UID:Pz_zgUkmdCrSTjWvY2r4DMo_@stanza.co
SUMMARY:Shorebirds vs. Drive
DESCRIPTION:Shorebirds vs. Drive\n\nFollow on MiLB First Pitch: https://stza.co/+wHOm-2L\n\nShop: https://stza.co/+wHOm-29\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144519Z
LAST-MODIFIED:20180213T144519Z
TRANSP:OPAQUE
END:VEVENT
* Shorebirds vs. GreenJackets
<2018-05-04 Fri 18:05-21:05>
:PROPERTIES:
:ID:       qqk8TfxTiXSORgaXzWvvEHzd@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Shorebirds vs. GreenJackets Shorebirds vs. GreenJackets

Follow on MiLB First Pitch  https //stza.co/+wHOq-14

Shop  https //stza.co/+wHOq-13

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Shorebirds vs. GreenJackets
END:VALARM
DTSTART:20180504T230500Z
DTEND:20180505T020500Z
UID:qqk8TfxTiXSORgaXzWvvEHzd@stanza.co
SUMMARY:Shorebirds vs. GreenJackets
DESCRIPTION:Shorebirds vs. GreenJackets\n\nFollow on MiLB First Pitch: https://stza.co/+wHOq-14\n\nShop: https://stza.co/+wHOq-13\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144519Z
LAST-MODIFIED:20180213T144519Z
TRANSP:OPAQUE
END:VEVENT
* Shorebirds vs. GreenJackets
<2018-05-05 Sat 18:05-21:05>
:PROPERTIES:
:ID:       eQDbmHC3I5MsafGos7u_R2Un@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Shorebirds vs. GreenJackets Shorebirds vs. GreenJackets

Follow on MiLB First Pitch  https //stza.co/+wHOs-1n

Shop  https //stza.co/+wHOs-3M

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Shorebirds vs. GreenJackets
END:VALARM
DTSTART:20180505T230500Z
DTEND:20180506T020500Z
UID:eQDbmHC3I5MsafGos7u_R2Un@stanza.co
SUMMARY:Shorebirds vs. GreenJackets
DESCRIPTION:Shorebirds vs. GreenJackets\n\nFollow on MiLB First Pitch: https://stza.co/+wHOs-1n\n\nShop: https://stza.co/+wHOs-3M\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144519Z
LAST-MODIFIED:20180213T144519Z
TRANSP:OPAQUE
END:VEVENT
* Shorebirds vs. GreenJackets
<2018-05-06 Sun 13:05-16:05>
:PROPERTIES:
:ID:       -OolnIgrCUQS7GKD6u8cKxa9@stanza.co
:LOCATION: Kids run the bases for today's game. Bring out the family!
:STATUS:   CONFIRMED
:END:

Shorebirds vs. GreenJackets Bring 2 canned food items to the Shorebirds box office and receive an upper reserved ticket for $3. All collected items will be donated to the local area food banks.

Kids 13 & under get to run the bases after the game, presented by Chili's Grill & Bar.

Follow on MiLB First Pitch  https //stza.co/+wHOu-3Y

Shop  https //stza.co/+wHOu-2V

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Shorebirds vs. GreenJackets
END:VALARM
DTSTART:20180506T180500Z
DTEND:20180506T210500Z
UID:-OolnIgrCUQS7GKD6u8cKxa9@stanza.co
SUMMARY:Shorebirds vs. GreenJackets
DESCRIPTION:Bring 2 canned food items to the Shorebirds box office and receive an upper reserved ticket for $3. All collected items will be donated to the local area food banks.\n\nKids 13 & under get to run the bases after the game, presented by Chili's Grill & Bar.\n\nFollow on MiLB First Pitch: https://stza.co/+wHOu-3Y\n\nShop: https://stza.co/+wHOu-2V\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Kids run the bases for today's game. Bring out the family!
STATUS:CONFIRMED
CREATED:20180213T144519Z
LAST-MODIFIED:20180213T144519Z
TRANSP:OPAQUE
END:VEVENT
* Shorebirds vs. GreenJackets
<2018-05-07 Mon 18:05-21:05>
:PROPERTIES:
:ID:       nr_EwUJ5goTiuOGefA-vgoIc@stanza.co
:LOCATION: 47 ABC 2 Buck Monday
:STATUS:   CONFIRMED
:END:

Shorebirds vs. GreenJackets Enjoy $2 Upper Reserved tickets, $2 hotdogs, and $2 fountain Pepsi products.

Follow on MiLB First Pitch  https //stza.co/+wHOw-3b

Shop  https //stza.co/+wHOw-2d

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Shorebirds vs. GreenJackets
END:VALARM
DTSTART:20180507T230500Z
DTEND:20180508T020500Z
UID:nr_EwUJ5goTiuOGefA-vgoIc@stanza.co
SUMMARY:Shorebirds vs. GreenJackets
DESCRIPTION:Enjoy $2 Upper Reserved tickets, $2 hotdogs, and $2 fountain Pepsi products.\n\nFollow on MiLB First Pitch: https://stza.co/+wHOw-3b\n\nShop: https://stza.co/+wHOw-2d\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:47 ABC 2 Buck Monday
STATUS:CONFIRMED
CREATED:20180213T144519Z
LAST-MODIFIED:20180213T144519Z
TRANSP:OPAQUE
END:VEVENT
* Shorebirds @ Legends
<2018-05-09 Wed 09:35-12:35>
:PROPERTIES:
:ID:       Iomi3pgh7dLhXt6jn-4y-EeP@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Shorebirds @ Legends Shorebirds @ Legends

Follow on MiLB First Pitch  https //stza.co/+xB1q-8

Shop  https //stza.co/+xB1q-2$

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Shorebirds @ Legends
END:VALARM
DTSTART:20180509T143500Z
DTEND:20180509T173500Z
UID:Iomi3pgh7dLhXt6jn-4y-EeP@stanza.co
SUMMARY:Shorebirds @ Legends
DESCRIPTION:Shorebirds @ Legends\n\nFollow on MiLB First Pitch: https://stza.co/+xB1q-8\n\nShop: https://stza.co/+xB1q-2$\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144519Z
LAST-MODIFIED:20180213T144519Z
TRANSP:OPAQUE
END:VEVENT
* Shorebirds @ Legends
<2018-05-10 Thu 18:05-21:05>
:PROPERTIES:
:ID:       WY5PYq3mFX3qZeEMstWFgKbN@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Shorebirds @ Legends Shorebirds @ Legends

Follow on MiLB First Pitch  https //stza.co/+xB1x-2Q

Shop  https //stza.co/+xB1x-1Q

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Shorebirds @ Legends
END:VALARM
DTSTART:20180510T230500Z
DTEND:20180511T020500Z
UID:WY5PYq3mFX3qZeEMstWFgKbN@stanza.co
SUMMARY:Shorebirds @ Legends
DESCRIPTION:Shorebirds @ Legends\n\nFollow on MiLB First Pitch: https://stza.co/+xB1x-2Q\n\nShop: https://stza.co/+xB1x-1Q\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144519Z
LAST-MODIFIED:20180213T144519Z
TRANSP:OPAQUE
END:VEVENT
* Shorebirds @ Legends
<2018-05-11 Fri 18:05-21:05>
:PROPERTIES:
:ID:       9lfDMlrQSiPkBgkt8ukVMaC5@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Shorebirds @ Legends Shorebirds @ Legends

Follow on MiLB First Pitch  https //stza.co/+xB1G-r

Shop  https //stza.co/+xB1G-O

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Shorebirds @ Legends
END:VALARM
DTSTART:20180511T230500Z
DTEND:20180512T020500Z
UID:9lfDMlrQSiPkBgkt8ukVMaC5@stanza.co
SUMMARY:Shorebirds @ Legends
DESCRIPTION:Shorebirds @ Legends\n\nFollow on MiLB First Pitch: https://stza.co/+xB1G-r\n\nShop: https://stza.co/+xB1G-O\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144519Z
LAST-MODIFIED:20180213T144519Z
TRANSP:OPAQUE
END:VEVENT
* Shorebirds @ Fireflies
<2018-05-12 Sat 17:05-20:05>
:PROPERTIES:
:ID:       EVOe5mNfOQYiJNQv3L2EX7yG@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Shorebirds @ Fireflies Shorebirds @ Fireflies

Follow on MiLB First Pitch  https //stza.co/+xBQr-1k

Shop  https //stza.co/+xBQr-30

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Shorebirds @ Fireflies
END:VALARM
DTSTART:20180512T220500Z
DTEND:20180513T010500Z
UID:EVOe5mNfOQYiJNQv3L2EX7yG@stanza.co
SUMMARY:Shorebirds @ Fireflies
DESCRIPTION:Shorebirds @ Fireflies\n\nFollow on MiLB First Pitch: https://stza.co/+xBQr-1k\n\nShop: https://stza.co/+xBQr-30\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144519Z
LAST-MODIFIED:20180213T144519Z
TRANSP:OPAQUE
END:VEVENT
* Shorebirds @ Fireflies
<2018-05-13 Sun 13:05-16:05>
:PROPERTIES:
:ID:       NvDlmRZY6nfVj3qQPK6RZuUc@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Shorebirds @ Fireflies Shorebirds @ Fireflies

Follow on MiLB First Pitch  https //stza.co/+xBQw-2k

Shop  https //stza.co/+xBQw-p

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Shorebirds @ Fireflies
END:VALARM
DTSTART:20180513T180500Z
DTEND:20180513T210500Z
UID:NvDlmRZY6nfVj3qQPK6RZuUc@stanza.co
SUMMARY:Shorebirds @ Fireflies
DESCRIPTION:Shorebirds @ Fireflies\n\nFollow on MiLB First Pitch: https://stza.co/+xBQw-2k\n\nShop: https://stza.co/+xBQw-p\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144519Z
LAST-MODIFIED:20180213T144519Z
TRANSP:OPAQUE
END:VEVENT
* Shorebirds @ Fireflies
<2018-05-14 Mon 18:05-21:05>
:PROPERTIES:
:ID:       YRTcDHk7RWDzTxR0URLKEq23@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Shorebirds @ Fireflies Shorebirds @ Fireflies

Follow on MiLB First Pitch  https //stza.co/+xBQB-25

Shop  https //stza.co/+xBQB-3p

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Shorebirds @ Fireflies
END:VALARM
DTSTART:20180514T230500Z
DTEND:20180515T020500Z
UID:YRTcDHk7RWDzTxR0URLKEq23@stanza.co
SUMMARY:Shorebirds @ Fireflies
DESCRIPTION:Shorebirds @ Fireflies\n\nFollow on MiLB First Pitch: https://stza.co/+xBQB-25\n\nShop: https://stza.co/+xBQB-3p\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144519Z
LAST-MODIFIED:20180213T144519Z
TRANSP:OPAQUE
END:VEVENT
* Shorebirds @ Fireflies
<2018-05-15 Tue 18:05-21:05>
:PROPERTIES:
:ID:       R4W8VVYNvgVW_EgbMLQhoLnl@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Shorebirds @ Fireflies Shorebirds @ Fireflies

Follow on MiLB First Pitch  https //stza.co/+xBQI-3m

Shop  https //stza.co/+xBQI-L

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Shorebirds @ Fireflies
END:VALARM
DTSTART:20180515T230500Z
DTEND:20180516T020500Z
UID:R4W8VVYNvgVW_EgbMLQhoLnl@stanza.co
SUMMARY:Shorebirds @ Fireflies
DESCRIPTION:Shorebirds @ Fireflies\n\nFollow on MiLB First Pitch: https://stza.co/+xBQI-3m\n\nShop: https://stza.co/+xBQI-L\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144519Z
LAST-MODIFIED:20180213T144519Z
TRANSP:OPAQUE
END:VEVENT
* Shorebirds vs. Suns
<2018-05-17 Thu 18:05-21:05>
:PROPERTIES:
:ID:       WhdiSEbuF_43APa0P9SqnUmt@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Shorebirds vs. Suns Shorebirds vs. Suns

Follow on MiLB First Pitch  https //stza.co/+wHOx-3m

Shop  https //stza.co/+wHOx-B

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Shorebirds vs. Suns
END:VALARM
DTSTART:20180517T230500Z
DTEND:20180518T020500Z
UID:WhdiSEbuF_43APa0P9SqnUmt@stanza.co
SUMMARY:Shorebirds vs. Suns
DESCRIPTION:Shorebirds vs. Suns\n\nFollow on MiLB First Pitch: https://stza.co/+wHOx-3m\n\nShop: https://stza.co/+wHOx-B\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144519Z
LAST-MODIFIED:20180213T144519Z
TRANSP:OPAQUE
END:VEVENT
* Shorebirds vs. Suns
<2018-05-18 Fri 18:05-21:05>
:PROPERTIES:
:ID:       8g8s08GCT96J91IViMTMHzjQ@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Shorebirds vs. Suns Shorebirds vs. Suns

Follow on MiLB First Pitch  https //stza.co/+wHOD-2K

Shop  https //stza.co/+wHOD-1x

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Shorebirds vs. Suns
END:VALARM
DTSTART:20180518T230500Z
DTEND:20180519T020500Z
UID:8g8s08GCT96J91IViMTMHzjQ@stanza.co
SUMMARY:Shorebirds vs. Suns
DESCRIPTION:Shorebirds vs. Suns\n\nFollow on MiLB First Pitch: https://stza.co/+wHOD-2K\n\nShop: https://stza.co/+wHOD-1x\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144519Z
LAST-MODIFIED:20180213T144519Z
TRANSP:OPAQUE
END:VEVENT
* Shorebirds vs. Suns
<2018-05-19 Sat 18:05-21:05>
:PROPERTIES:
:ID:       qIJEmpy_44DN1FFQNEg_8dmz@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Shorebirds vs. Suns Shorebirds vs. Suns

Follow on MiLB First Pitch  https //stza.co/+wHOV-2i

Shop  https //stza.co/+wHOV-1a

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Shorebirds vs. Suns
END:VALARM
DTSTART:20180519T230500Z
DTEND:20180520T020500Z
UID:qIJEmpy_44DN1FFQNEg_8dmz@stanza.co
SUMMARY:Shorebirds vs. Suns
DESCRIPTION:Shorebirds vs. Suns\n\nFollow on MiLB First Pitch: https://stza.co/+wHOV-2i\n\nShop: https://stza.co/+wHOV-1a\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144519Z
LAST-MODIFIED:20180213T144519Z
TRANSP:OPAQUE
END:VEVENT
* Shorebirds vs. Suns
<2018-05-20 Sun 13:05-16:05>
:PROPERTIES:
:ID:       WOQ05fs6Z09S4QycmnLW9ldD@stanza.co
:LOCATION: Kids run the bases for today's game. Bring out the family!
:STATUS:   CONFIRMED
:END:

Shorebirds vs. Suns Bring 2 canned food items to the Shorebirds box office and receive an upper reserved ticket for $3. All collected items will be donated to the local area food banks.

Kids 13 & under get to run the bases after the game, presented by Chili's Grill & Bar.

Follow on MiLB First Pitch  https //stza.co/+wHPw-1F

Shop  https //stza.co/+wHPw-21

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Shorebirds vs. Suns
END:VALARM
DTSTART:20180520T180500Z
DTEND:20180520T210500Z
UID:WOQ05fs6Z09S4QycmnLW9ldD@stanza.co
SUMMARY:Shorebirds vs. Suns
DESCRIPTION:Bring 2 canned food items to the Shorebirds box office and receive an upper reserved ticket for $3. All collected items will be donated to the local area food banks.\n\nKids 13 & under get to run the bases after the game, presented by Chili's Grill & Bar.\n\nFollow on MiLB First Pitch: https://stza.co/+wHPw-1F\n\nShop: https://stza.co/+wHPw-21\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Kids run the bases for today's game. Bring out the family!
STATUS:CONFIRMED
CREATED:20180213T144519Z
LAST-MODIFIED:20180213T144519Z
TRANSP:OPAQUE
END:VEVENT
* Shorebirds @ Crawdads
<2018-05-21 Mon 17:00-20:00>
:PROPERTIES:
:ID:       QoRLMv1HlBmlYuQAPTvKTH2P@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Shorebirds @ Crawdads Shorebirds @ Crawdads

Follow on MiLB First Pitch  https //stza.co/+w0Ok-1k

Shop  https //stza.co/+w0Ok-2r

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Shorebirds @ Crawdads
END:VALARM
DTSTART:20180521T220000Z
DTEND:20180522T010000Z
UID:QoRLMv1HlBmlYuQAPTvKTH2P@stanza.co
SUMMARY:Shorebirds @ Crawdads
DESCRIPTION:Shorebirds @ Crawdads\n\nFollow on MiLB First Pitch: https://stza.co/+w0Ok-1k\n\nShop: https://stza.co/+w0Ok-2r\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144519Z
LAST-MODIFIED:20180213T144519Z
TRANSP:OPAQUE
END:VEVENT
* Shorebirds @ Crawdads
<2018-05-22 Tue 17:00-20:00>
:PROPERTIES:
:ID:       1j2765TvIZDk-nbR3eZ8CQct@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Shorebirds @ Crawdads Shorebirds @ Crawdads

Follow on MiLB First Pitch  https //stza.co/+w0Ol-32

Shop  https //stza.co/+w0Ol-X

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Shorebirds @ Crawdads
END:VALARM
DTSTART:20180522T220000Z
DTEND:20180523T010000Z
UID:1j2765TvIZDk-nbR3eZ8CQct@stanza.co
SUMMARY:Shorebirds @ Crawdads
DESCRIPTION:Shorebirds @ Crawdads\n\nFollow on MiLB First Pitch: https://stza.co/+w0Ol-32\n\nShop: https://stza.co/+w0Ol-X\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144519Z
LAST-MODIFIED:20180213T144519Z
TRANSP:OPAQUE
END:VEVENT
* Shorebirds @ Crawdads
<2018-05-23 Wed 17:00-20:00>
:PROPERTIES:
:ID:       NDKlgqdpOvcCdCmZQ2g-WKQo@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Shorebirds @ Crawdads Shorebirds @ Crawdads

Follow on MiLB First Pitch  https //stza.co/+w0Om-2c

Shop  https //stza.co/+w0Om-L

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Shorebirds @ Crawdads
END:VALARM
DTSTART:20180523T220000Z
DTEND:20180524T010000Z
UID:NDKlgqdpOvcCdCmZQ2g-WKQo@stanza.co
SUMMARY:Shorebirds @ Crawdads
DESCRIPTION:Shorebirds @ Crawdads\n\nFollow on MiLB First Pitch: https://stza.co/+w0Om-2c\n\nShop: https://stza.co/+w0Om-L\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144519Z
LAST-MODIFIED:20180213T144519Z
TRANSP:OPAQUE
END:VEVENT
* Shorebirds @ Crawdads
<2018-05-24 Thu 18:00-21:00>
:PROPERTIES:
:ID:       nVrEXJcOdSXAFyFu3SgwLJsN@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Shorebirds @ Crawdads Shorebirds @ Crawdads

Follow on MiLB First Pitch  https //stza.co/+w0On-2c

Shop  https //stza.co/+w0On-n

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Shorebirds @ Crawdads
END:VALARM
DTSTART:20180524T230000Z
DTEND:20180525T020000Z
UID:nVrEXJcOdSXAFyFu3SgwLJsN@stanza.co
SUMMARY:Shorebirds @ Crawdads
DESCRIPTION:Shorebirds @ Crawdads\n\nFollow on MiLB First Pitch: https://stza.co/+w0On-2c\n\nShop: https://stza.co/+w0On-n\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144519Z
LAST-MODIFIED:20180213T144519Z
TRANSP:OPAQUE
END:VEVENT
* Shorebirds vs. BlueClaws
<2018-05-25 Fri 18:05-21:05>
:PROPERTIES:
:ID:       tX2qJK1nYumBkJRZH-ywrCBo@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Shorebirds vs. BlueClaws Shorebirds vs. BlueClaws

Follow on MiLB First Pitch  https //stza.co/+wHPN-3A

Shop  https //stza.co/+wHPN-1I

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Shorebirds vs. BlueClaws
END:VALARM
DTSTART:20180525T230500Z
DTEND:20180526T020500Z
UID:tX2qJK1nYumBkJRZH-ywrCBo@stanza.co
SUMMARY:Shorebirds vs. BlueClaws
DESCRIPTION:Shorebirds vs. BlueClaws\n\nFollow on MiLB First Pitch: https://stza.co/+wHPN-3A\n\nShop: https://stza.co/+wHPN-1I\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144519Z
LAST-MODIFIED:20180213T144519Z
TRANSP:OPAQUE
END:VEVENT
* Shorebirds vs. BlueClaws
<2018-05-26 Sat 18:05-21:05>
:PROPERTIES:
:ID:       1vGe7PNrzUsHJ88gu2mVsyLY@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Shorebirds vs. BlueClaws Shorebirds vs. BlueClaws

Follow on MiLB First Pitch  https //stza.co/+wHPQ-2W

Shop  https //stza.co/+wHPQ-1H

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Shorebirds vs. BlueClaws
END:VALARM
DTSTART:20180526T230500Z
DTEND:20180527T020500Z
UID:1vGe7PNrzUsHJ88gu2mVsyLY@stanza.co
SUMMARY:Shorebirds vs. BlueClaws
DESCRIPTION:Shorebirds vs. BlueClaws\n\nFollow on MiLB First Pitch: https://stza.co/+wHPQ-2W\n\nShop: https://stza.co/+wHPQ-1H\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144519Z
LAST-MODIFIED:20180213T144519Z
TRANSP:OPAQUE
END:VEVENT
* Shorebirds vs. BlueClaws
<2018-05-27 Sun 13:05-16:05>
:PROPERTIES:
:ID:       7S8aJ8Gf7q1wnqHZsylqZJ5G@stanza.co
:LOCATION: Kids run the bases for today's game. Bring out the family!
:STATUS:   CONFIRMED
:END:

Shorebirds vs. BlueClaws Bring 2 canned food items to the Shorebirds box office and receive an upper reserved ticket for $3. All collected items will be donated to the local area food banks.

Kids 13 & under get to run the bases after the game, presented by Chili's Grill & Bar.

Follow on MiLB First Pitch  https //stza.co/+wHPT-1b

Shop  https //stza.co/+wHPT-2

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Shorebirds vs. BlueClaws
END:VALARM
DTSTART:20180527T180500Z
DTEND:20180527T210500Z
UID:7S8aJ8Gf7q1wnqHZsylqZJ5G@stanza.co
SUMMARY:Shorebirds vs. BlueClaws
DESCRIPTION:Bring 2 canned food items to the Shorebirds box office and receive an upper reserved ticket for $3. All collected items will be donated to the local area food banks.\n\nKids 13 & under get to run the bases after the game, presented by Chili's Grill & Bar.\n\nFollow on MiLB First Pitch: https://stza.co/+wHPT-1b\n\nShop: https://stza.co/+wHPT-2\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Kids run the bases for today's game. Bring out the family!
STATUS:CONFIRMED
CREATED:20180213T144519Z
LAST-MODIFIED:20180213T144519Z
TRANSP:OPAQUE
END:VEVENT
* Shorebirds vs. BlueClaws
<2018-05-28 Mon 13:05-16:05>
:PROPERTIES:
:ID:       pVDeya8UM67WdibbnV0ZViVu@stanza.co
:LOCATION: 47 ABC 2 Buck Monday
:STATUS:   CONFIRMED
:END:

Shorebirds vs. BlueClaws Enjoy $2 Upper Reserved tickets, $2 hotdogs, and $2 fountain Pepsi products.

This game is included in the Silver Sluggers membership for fans 55 and up.

Follow on MiLB First Pitch  https //stza.co/+wHPY-2N

Shop  https //stza.co/+wHPY-2H

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Shorebirds vs. BlueClaws
END:VALARM
DTSTART:20180528T180500Z
DTEND:20180528T210500Z
UID:pVDeya8UM67WdibbnV0ZViVu@stanza.co
SUMMARY:Shorebirds vs. BlueClaws
DESCRIPTION:Enjoy $2 Upper Reserved tickets, $2 hotdogs, and $2 fountain Pepsi products.\n\nThis game is included in the Silver Sluggers membership for fans 55 and up.\n\nFollow on MiLB First Pitch: https://stza.co/+wHPY-2N\n\nShop: https://stza.co/+wHPY-2H\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:47 ABC 2 Buck Monday
STATUS:CONFIRMED
CREATED:20180213T144519Z
LAST-MODIFIED:20180213T144519Z
TRANSP:OPAQUE
END:VEVENT
* Shorebirds @ Intimidators
<2018-05-29 Tue 17:35-20:35>
:PROPERTIES:
:ID:       _G0gM2upTPAwABmtsFKek6qq@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Shorebirds @ Intimidators Shorebirds @ Intimidators

Follow on MiLB First Pitch  https //stza.co/+wIBH-3M

Shop  https //stza.co/+wIBH-1u

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Shorebirds @ Intimidators
END:VALARM
DTSTART:20180529T223500Z
DTEND:20180530T013500Z
UID:_G0gM2upTPAwABmtsFKek6qq@stanza.co
SUMMARY:Shorebirds @ Intimidators
DESCRIPTION:Shorebirds @ Intimidators\n\nFollow on MiLB First Pitch: https://stza.co/+wIBH-3M\n\nShop: https://stza.co/+wIBH-1u\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144519Z
LAST-MODIFIED:20180213T144519Z
TRANSP:OPAQUE
END:VEVENT
* Shorebirds @ Intimidators
<2018-05-30 Wed 17:35-20:35>
:PROPERTIES:
:ID:       Rl92ENI0K8Lk4vmGYOMo0o5-@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Shorebirds @ Intimidators Shorebirds @ Intimidators

Follow on MiLB First Pitch  https //stza.co/+wIBI-2M

Shop  https //stza.co/+wIBI-3K

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Shorebirds @ Intimidators
END:VALARM
DTSTART:20180530T223500Z
DTEND:20180531T013500Z
UID:Rl92ENI0K8Lk4vmGYOMo0o5-@stanza.co
SUMMARY:Shorebirds @ Intimidators
DESCRIPTION:Shorebirds @ Intimidators\n\nFollow on MiLB First Pitch: https://stza.co/+wIBI-2M\n\nShop: https://stza.co/+wIBI-3K\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144519Z
LAST-MODIFIED:20180213T144519Z
TRANSP:OPAQUE
END:VEVENT
* Shorebirds @ Intimidators
<2018-05-31 Thu 17:35-20:35>
:PROPERTIES:
:ID:       ZWND6ihNoH2KqMlm01WdLP5i@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Shorebirds @ Intimidators Shorebirds @ Intimidators

Follow on MiLB First Pitch  https //stza.co/+wIBJ-2p

Shop  https //stza.co/+wIBJ-1m

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Shorebirds @ Intimidators
END:VALARM
DTSTART:20180531T223500Z
DTEND:20180601T013500Z
UID:ZWND6ihNoH2KqMlm01WdLP5i@stanza.co
SUMMARY:Shorebirds @ Intimidators
DESCRIPTION:Shorebirds @ Intimidators\n\nFollow on MiLB First Pitch: https://stza.co/+wIBJ-2p\n\nShop: https://stza.co/+wIBJ-1m\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144519Z
LAST-MODIFIED:20180213T144519Z
TRANSP:OPAQUE
END:VEVENT
* Shorebirds @ RiverDogs
<2018-06-01 Fri 18:05-21:05>
:PROPERTIES:
:ID:       hCkMq6h9ZszNy2dxUUWPUp3O@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Shorebirds @ RiverDogs Shorebirds @ RiverDogs

Follow on MiLB First Pitch  https //stza.co/+vNFH-1E

Shop  https //stza.co/+vNFH-3I

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Shorebirds @ RiverDogs
END:VALARM
DTSTART:20180601T230500Z
DTEND:20180602T020500Z
UID:hCkMq6h9ZszNy2dxUUWPUp3O@stanza.co
SUMMARY:Shorebirds @ RiverDogs
DESCRIPTION:Shorebirds @ RiverDogs\n\nFollow on MiLB First Pitch: https://stza.co/+vNFH-1E\n\nShop: https://stza.co/+vNFH-3I\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144519Z
LAST-MODIFIED:20180213T144519Z
TRANSP:OPAQUE
END:VEVENT
* Shorebirds @ RiverDogs
<2018-06-02 Sat 17:05-20:05>
:PROPERTIES:
:ID:       rfj4hdSal_KWPOk86fz6yG3g@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Shorebirds @ RiverDogs Shorebirds @ RiverDogs

Follow on MiLB First Pitch  https //stza.co/+vNFI-2d

Shop  https //stza.co/+vNFI-2R

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Shorebirds @ RiverDogs
END:VALARM
DTSTART:20180602T220500Z
DTEND:20180603T010500Z
UID:rfj4hdSal_KWPOk86fz6yG3g@stanza.co
SUMMARY:Shorebirds @ RiverDogs
DESCRIPTION:Shorebirds @ RiverDogs\n\nFollow on MiLB First Pitch: https://stza.co/+vNFI-2d\n\nShop: https://stza.co/+vNFI-2R\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144519Z
LAST-MODIFIED:20180213T144519Z
TRANSP:OPAQUE
END:VEVENT
* Shorebirds @ RiverDogs
<2018-06-03 Sun 16:05-19:05>
:PROPERTIES:
:ID:       NloF066Q_Nnqs4RRLTNo3HIe@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Shorebirds @ RiverDogs Shorebirds @ RiverDogs

Follow on MiLB First Pitch  https //stza.co/+vNFJ-3g

Shop  https //stza.co/+vNFJ-3S

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Shorebirds @ RiverDogs
END:VALARM
DTSTART:20180603T210500Z
DTEND:20180604T000500Z
UID:NloF066Q_Nnqs4RRLTNo3HIe@stanza.co
SUMMARY:Shorebirds @ RiverDogs
DESCRIPTION:Shorebirds @ RiverDogs\n\nFollow on MiLB First Pitch: https://stza.co/+vNFJ-3g\n\nShop: https://stza.co/+vNFJ-3S\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144519Z
LAST-MODIFIED:20180213T144519Z
TRANSP:OPAQUE
END:VEVENT
* Shorebirds vs. Grasshoppers
<2018-06-05 Tue 18:05-21:05>
:PROPERTIES:
:ID:       I0Ie_CRD49ROPx6tEbxDJNZe@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Shorebirds vs. Grasshoppers Shorebirds vs. Grasshoppers

Follow on MiLB First Pitch  https //stza.co/+wHP$-11

Shop  https //stza.co/+wHP$-10

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Shorebirds vs. Grasshoppers
END:VALARM
DTSTART:20180605T230500Z
DTEND:20180606T020500Z
UID:I0Ie_CRD49ROPx6tEbxDJNZe@stanza.co
SUMMARY:Shorebirds vs. Grasshoppers
DESCRIPTION:Shorebirds vs. Grasshoppers\n\nFollow on MiLB First Pitch: https://stza.co/+wHP$-11\n\nShop: https://stza.co/+wHP$-10\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144519Z
LAST-MODIFIED:20180213T144519Z
TRANSP:OPAQUE
END:VEVENT
* Shorebirds vs. Grasshoppers
<2018-06-06 Wed 18:05-21:05>
:PROPERTIES:
:ID:       d-AQ5F3Es_btmixRUUDfWcYN@stanza.co
:LOCATION: Silver Slugger Game
:STATUS:   CONFIRMED
:END:

Shorebirds vs. Grasshoppers This game is included in the Silver Sluggers membership for fans 55 and up.

Follow on MiLB First Pitch  https //stza.co/+wHQ4-2d

Shop  https //stza.co/+wHQ4-w

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Shorebirds vs. Grasshoppers
END:VALARM
DTSTART:20180606T230500Z
DTEND:20180607T020500Z
UID:d-AQ5F3Es_btmixRUUDfWcYN@stanza.co
SUMMARY:Shorebirds vs. Grasshoppers
DESCRIPTION:This game is included in the Silver Sluggers membership for fans 55 and up.\n\nFollow on MiLB First Pitch: https://stza.co/+wHQ4-2d\n\nShop: https://stza.co/+wHQ4-w\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Silver Slugger Game
STATUS:CONFIRMED
CREATED:20180213T144519Z
LAST-MODIFIED:20180213T144519Z
TRANSP:OPAQUE
END:VEVENT
* Shorebirds vs. Grasshoppers
<2018-06-07 Thu 18:05-21:05>
:PROPERTIES:
:ID:       ElvnV1GV6-oXP51XUdXeN-9K@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Shorebirds vs. Grasshoppers Shorebirds vs. Grasshoppers

Follow on MiLB First Pitch  https //stza.co/+wHQ7-2D

Shop  https //stza.co/+wHQ7-2H

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Shorebirds vs. Grasshoppers
END:VALARM
DTSTART:20180607T230500Z
DTEND:20180608T020500Z
UID:ElvnV1GV6-oXP51XUdXeN-9K@stanza.co
SUMMARY:Shorebirds vs. Grasshoppers
DESCRIPTION:Shorebirds vs. Grasshoppers\n\nFollow on MiLB First Pitch: https://stza.co/+wHQ7-2D\n\nShop: https://stza.co/+wHQ7-2H\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144519Z
LAST-MODIFIED:20180213T144519Z
TRANSP:OPAQUE
END:VEVENT
* Shorebirds vs. Suns
<2018-06-08 Fri 18:05-21:05>
:PROPERTIES:
:ID:       0CF-9Ti7Rr8Fxy7cSdWhj650@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Shorebirds vs. Suns Shorebirds vs. Suns

Follow on MiLB First Pitch  https //stza.co/+wHQb-16

Shop  https //stza.co/+wHQb-1r

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Shorebirds vs. Suns
END:VALARM
DTSTART:20180608T230500Z
DTEND:20180609T020500Z
UID:0CF-9Ti7Rr8Fxy7cSdWhj650@stanza.co
SUMMARY:Shorebirds vs. Suns
DESCRIPTION:Shorebirds vs. Suns\n\nFollow on MiLB First Pitch: https://stza.co/+wHQb-16\n\nShop: https://stza.co/+wHQb-1r\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144519Z
LAST-MODIFIED:20180213T144519Z
TRANSP:OPAQUE
END:VEVENT
* Shorebirds vs. Suns
<2018-06-09 Sat 17:35-20:35>
:PROPERTIES:
:ID:       bMhpNOMrCWNQjO6Zy1OBLNd_@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Shorebirds vs. Suns Shorebirds vs. Suns

Follow on MiLB First Pitch  https //stza.co/+wHQe-3n

Shop  https //stza.co/+wHQe-l

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Shorebirds vs. Suns
END:VALARM
DTSTART:20180609T223500Z
DTEND:20180610T013500Z
UID:bMhpNOMrCWNQjO6Zy1OBLNd_@stanza.co
SUMMARY:Shorebirds vs. Suns
DESCRIPTION:Shorebirds vs. Suns\n\nFollow on MiLB First Pitch: https://stza.co/+wHQe-3n\n\nShop: https://stza.co/+wHQe-l\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144519Z
LAST-MODIFIED:20180213T144519Z
TRANSP:OPAQUE
END:VEVENT
* Shorebirds vs. Suns
<2018-06-10 Sun 13:05-16:05>
:PROPERTIES:
:ID:       ogi2T59FDr8_Rqn7vxbxzVef@stanza.co
:LOCATION: Kids run the bases for today's game. Bring out the family!
:STATUS:   CONFIRMED
:END:

Shorebirds vs. Suns Bring 2 canned food items to the Shorebirds box office and receive an upper reserved ticket for $3. All collected items will be donated to the local area food banks.

Kids 13 & under get to run the bases after the game, presented by Chili's Grill & Bar.

Follow on MiLB First Pitch  https //stza.co/+wHQg-3a

Shop  https //stza.co/+wHQg-u

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Shorebirds vs. Suns
END:VALARM
DTSTART:20180610T180500Z
DTEND:20180610T210500Z
UID:ogi2T59FDr8_Rqn7vxbxzVef@stanza.co
SUMMARY:Shorebirds vs. Suns
DESCRIPTION:Bring 2 canned food items to the Shorebirds box office and receive an upper reserved ticket for $3. All collected items will be donated to the local area food banks.\n\nKids 13 & under get to run the bases after the game, presented by Chili's Grill & Bar.\n\nFollow on MiLB First Pitch: https://stza.co/+wHQg-3a\n\nShop: https://stza.co/+wHQg-u\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Kids run the bases for today's game. Bring out the family!
STATUS:CONFIRMED
CREATED:20180213T144519Z
LAST-MODIFIED:20180213T144519Z
TRANSP:OPAQUE
END:VEVENT
* Shorebirds @ Intimidators
<2018-06-11 Mon 18:05-21:05>
:PROPERTIES:
:ID:       ituxTyw1ffGQ4I0LQCxx7TIZ@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Shorebirds @ Intimidators Shorebirds @ Intimidators

Follow on MiLB First Pitch  https //stza.co/+wIBK-2$

Shop  https //stza.co/+wIBK-3i

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Shorebirds @ Intimidators
END:VALARM
DTSTART:20180611T230500Z
DTEND:20180612T020500Z
UID:ituxTyw1ffGQ4I0LQCxx7TIZ@stanza.co
SUMMARY:Shorebirds @ Intimidators
DESCRIPTION:Shorebirds @ Intimidators\n\nFollow on MiLB First Pitch: https://stza.co/+wIBK-2$\n\nShop: https://stza.co/+wIBK-3i\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144519Z
LAST-MODIFIED:20180213T144519Z
TRANSP:OPAQUE
END:VEVENT
* Shorebirds @ Intimidators
<2018-06-12 Tue 18:05-21:05>
:PROPERTIES:
:ID:       Pgou9ivhYromqLIFtLtIdnxa@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Shorebirds @ Intimidators Shorebirds @ Intimidators

Follow on MiLB First Pitch  https //stza.co/+wIBL-1q

Shop  https //stza.co/+wIBL-x

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Shorebirds @ Intimidators
END:VALARM
DTSTART:20180612T230500Z
DTEND:20180613T020500Z
UID:Pgou9ivhYromqLIFtLtIdnxa@stanza.co
SUMMARY:Shorebirds @ Intimidators
DESCRIPTION:Shorebirds @ Intimidators\n\nFollow on MiLB First Pitch: https://stza.co/+wIBL-1q\n\nShop: https://stza.co/+wIBL-x\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144519Z
LAST-MODIFIED:20180213T144519Z
TRANSP:OPAQUE
END:VEVENT
* Shorebirds @ Intimidators
<2018-06-13 Wed 18:05-21:05>
:PROPERTIES:
:ID:       fg-OlWsg4AC5A2ZZkWN9W3F6@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Shorebirds @ Intimidators Shorebirds @ Intimidators

Follow on MiLB First Pitch  https //stza.co/+wIBM-E

Shop  https //stza.co/+wIBM-1X

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Shorebirds @ Intimidators
END:VALARM
DTSTART:20180613T230500Z
DTEND:20180614T020500Z
UID:fg-OlWsg4AC5A2ZZkWN9W3F6@stanza.co
SUMMARY:Shorebirds @ Intimidators
DESCRIPTION:Shorebirds @ Intimidators\n\nFollow on MiLB First Pitch: https://stza.co/+wIBM-E\n\nShop: https://stza.co/+wIBM-1X\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144519Z
LAST-MODIFIED:20180213T144519Z
TRANSP:OPAQUE
END:VEVENT
* Shorebirds @ Intimidators
<2018-06-14 Thu 18:05-21:05>
:PROPERTIES:
:ID:       wIwLDYjnmmosu02NQoy3uAAz@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Shorebirds @ Intimidators Shorebirds @ Intimidators

Follow on MiLB First Pitch  https //stza.co/+wIBN-8

Shop  https //stza.co/+wIBN-2M

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Shorebirds @ Intimidators
END:VALARM
DTSTART:20180614T230500Z
DTEND:20180615T020500Z
UID:wIwLDYjnmmosu02NQoy3uAAz@stanza.co
SUMMARY:Shorebirds @ Intimidators
DESCRIPTION:Shorebirds @ Intimidators\n\nFollow on MiLB First Pitch: https://stza.co/+wIBN-8\n\nShop: https://stza.co/+wIBN-2M\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144519Z
LAST-MODIFIED:20180213T144519Z
TRANSP:OPAQUE
END:VEVENT
* Shorebirds @ Power
<2018-06-15 Fri 18:05-21:05>
:PROPERTIES:
:ID:       pW6wiX02wDFBXRAJEc4KA5_e@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Shorebirds @ Power Shorebirds @ Power

Follow on MiLB First Pitch  https //stza.co/+xJ3F-3M

Shop  https //stza.co/+xJ3F-1y

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Shorebirds @ Power
END:VALARM
DTSTART:20180615T230500Z
DTEND:20180616T020500Z
UID:pW6wiX02wDFBXRAJEc4KA5_e@stanza.co
SUMMARY:Shorebirds @ Power
DESCRIPTION:Shorebirds @ Power\n\nFollow on MiLB First Pitch: https://stza.co/+xJ3F-3M\n\nShop: https://stza.co/+xJ3F-1y\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144519Z
LAST-MODIFIED:20180213T144519Z
TRANSP:OPAQUE
END:VEVENT
* Shorebirds @ Power
<2018-06-16 Sat 17:05-20:05>
:PROPERTIES:
:ID:       jw0kizeuH2D4gwix6P7pUyOk@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Shorebirds @ Power Shorebirds @ Power

Follow on MiLB First Pitch  https //stza.co/+xJ3G-23

Shop  https //stza.co/+xJ3G-2w

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Shorebirds @ Power
END:VALARM
DTSTART:20180616T220500Z
DTEND:20180617T010500Z
UID:jw0kizeuH2D4gwix6P7pUyOk@stanza.co
SUMMARY:Shorebirds @ Power
DESCRIPTION:Shorebirds @ Power\n\nFollow on MiLB First Pitch: https://stza.co/+xJ3G-23\n\nShop: https://stza.co/+xJ3G-2w\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144519Z
LAST-MODIFIED:20180213T144519Z
TRANSP:OPAQUE
END:VEVENT
* Shorebirds @ Power
<2018-06-17 Sun 13:05-16:05>
:PROPERTIES:
:ID:       Xzs1N1qj55Ja7P5Rvr7YPXRS@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Shorebirds @ Power Shorebirds @ Power

Follow on MiLB First Pitch  https //stza.co/+xJ3H-2U

Shop  https //stza.co/+xJ3H-1j

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Shorebirds @ Power
END:VALARM
DTSTART:20180617T180500Z
DTEND:20180617T210500Z
UID:Xzs1N1qj55Ja7P5Rvr7YPXRS@stanza.co
SUMMARY:Shorebirds @ Power
DESCRIPTION:Shorebirds @ Power\n\nFollow on MiLB First Pitch: https://stza.co/+xJ3H-2U\n\nShop: https://stza.co/+xJ3H-1j\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144519Z
LAST-MODIFIED:20180213T144519Z
TRANSP:OPAQUE
END:VEVENT
* Shorebirds vs. Intimidators
<2018-06-21 Thu 18:05-21:05>
:PROPERTIES:
:ID:       wkWMWbHOmGHVGpRTOAWD-DiF@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Shorebirds vs. Intimidators Shorebirds vs. Intimidators

Follow on MiLB First Pitch  https //stza.co/+wHQi-2w

Shop  https //stza.co/+wHQi-3c

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Shorebirds vs. Intimidators
END:VALARM
DTSTART:20180621T230500Z
DTEND:20180622T020500Z
UID:wkWMWbHOmGHVGpRTOAWD-DiF@stanza.co
SUMMARY:Shorebirds vs. Intimidators
DESCRIPTION:Shorebirds vs. Intimidators\n\nFollow on MiLB First Pitch: https://stza.co/+wHQi-2w\n\nShop: https://stza.co/+wHQi-3c\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144519Z
LAST-MODIFIED:20180213T144519Z
TRANSP:OPAQUE
END:VEVENT
* Shorebirds vs. Intimidators
<2018-06-22 Fri 18:05-21:05>
:PROPERTIES:
:ID:       h1sriS6DLiwpW8PWoRJpJF4s@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Shorebirds vs. Intimidators Shorebirds vs. Intimidators

Follow on MiLB First Pitch  https //stza.co/+wHQj-Y

Shop  https //stza.co/+wHQj-A

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Shorebirds vs. Intimidators
END:VALARM
DTSTART:20180622T230500Z
DTEND:20180623T020500Z
UID:h1sriS6DLiwpW8PWoRJpJF4s@stanza.co
SUMMARY:Shorebirds vs. Intimidators
DESCRIPTION:Shorebirds vs. Intimidators\n\nFollow on MiLB First Pitch: https://stza.co/+wHQj-Y\n\nShop: https://stza.co/+wHQj-A\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144519Z
LAST-MODIFIED:20180213T144519Z
TRANSP:OPAQUE
END:VEVENT
* Shorebirds vs. Intimidators
<2018-06-23 Sat 18:05-21:05>
:PROPERTIES:
:ID:       E3viQWYQ2Hp0TxJT5OPqL65U@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Shorebirds vs. Intimidators Shorebirds vs. Intimidators

Follow on MiLB First Pitch  https //stza.co/+wHQl-13

Shop  https //stza.co/+wHQl-1E

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Shorebirds vs. Intimidators
END:VALARM
DTSTART:20180623T230500Z
DTEND:20180624T020500Z
UID:E3viQWYQ2Hp0TxJT5OPqL65U@stanza.co
SUMMARY:Shorebirds vs. Intimidators
DESCRIPTION:Shorebirds vs. Intimidators\n\nFollow on MiLB First Pitch: https://stza.co/+wHQl-13\n\nShop: https://stza.co/+wHQl-1E\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144519Z
LAST-MODIFIED:20180213T144519Z
TRANSP:OPAQUE
END:VEVENT
* Shorebirds vs. Suns
<2018-06-24 Sun 13:05-16:05>
:PROPERTIES:
:ID:       -yoMQoEixGem-jrV7KX-Hv-I@stanza.co
:LOCATION: Kids run the bases for today's game. Bring out the family!
:STATUS:   CONFIRMED
:END:

Shorebirds vs. Suns Bring 2 canned food items to the Shorebirds box office and receive an upper reserved ticket for $3. All collected items will be donated to the local area food banks.

Kids 13 & under get to run the bases after the game, presented by Chili's Grill & Bar.

Follow on MiLB First Pitch  https //stza.co/+wHQp-1n

Shop  https //stza.co/+wHQp-1

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Shorebirds vs. Suns
END:VALARM
DTSTART:20180624T180500Z
DTEND:20180624T210500Z
UID:-yoMQoEixGem-jrV7KX-Hv-I@stanza.co
SUMMARY:Shorebirds vs. Suns
DESCRIPTION:Bring 2 canned food items to the Shorebirds box office and receive an upper reserved ticket for $3. All collected items will be donated to the local area food banks.\n\nKids 13 & under get to run the bases after the game, presented by Chili's Grill & Bar.\n\nFollow on MiLB First Pitch: https://stza.co/+wHQp-1n\n\nShop: https://stza.co/+wHQp-1\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Kids run the bases for today's game. Bring out the family!
STATUS:CONFIRMED
CREATED:20180213T144519Z
LAST-MODIFIED:20180213T144519Z
TRANSP:OPAQUE
END:VEVENT
* Shorebirds vs. Suns
<2018-06-25 Mon 18:05-21:05>
:PROPERTIES:
:ID:       O2wGwLrVBUAYF1F3JPzybH8q@stanza.co
:LOCATION: 47 ABC 2 Buck Monday
:STATUS:   CONFIRMED
:END:

Shorebirds vs. Suns Enjoy $2 Upper Reserved tickets, $2 hotdogs, and $2 fountain Pepsi products.

Follow on MiLB First Pitch  https //stza.co/+wHQs-3y

Shop  https //stza.co/+wHQs-H

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Shorebirds vs. Suns
END:VALARM
DTSTART:20180625T230500Z
DTEND:20180626T020500Z
UID:O2wGwLrVBUAYF1F3JPzybH8q@stanza.co
SUMMARY:Shorebirds vs. Suns
DESCRIPTION:Enjoy $2 Upper Reserved tickets, $2 hotdogs, and $2 fountain Pepsi products.\n\nFollow on MiLB First Pitch: https://stza.co/+wHQs-3y\n\nShop: https://stza.co/+wHQs-H\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:47 ABC 2 Buck Monday
STATUS:CONFIRMED
CREATED:20180213T144519Z
LAST-MODIFIED:20180213T144519Z
TRANSP:OPAQUE
END:VEVENT
* Shorebirds vs. Suns
<2018-06-26 Tue 18:05-21:05>
:PROPERTIES:
:ID:       -m-uKWzcu06ki7bi67xFIXlR@stanza.co
:LOCATION: Silver Slugger Game
:STATUS:   CONFIRMED
:END:

Shorebirds vs. Suns This game is included in the Silver Sluggers membership for fans 55 and up.

Follow on MiLB First Pitch  https //stza.co/+wHQw-25

Shop  https //stza.co/+wHQw-2j

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Shorebirds vs. Suns
END:VALARM
DTSTART:20180626T230500Z
DTEND:20180627T020500Z
UID:-m-uKWzcu06ki7bi67xFIXlR@stanza.co
SUMMARY:Shorebirds vs. Suns
DESCRIPTION:This game is included in the Silver Sluggers membership for fans 55 and up.\n\nFollow on MiLB First Pitch: https://stza.co/+wHQw-25\n\nShop: https://stza.co/+wHQw-2j\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Silver Slugger Game
STATUS:CONFIRMED
CREATED:20180213T144519Z
LAST-MODIFIED:20180213T144519Z
TRANSP:OPAQUE
END:VEVENT
* Shorebirds @ Grasshoppers
<2018-06-27 Wed 18:00-21:00>
:PROPERTIES:
:ID:       eUdT_QldRme7vENek4GA-Bgh@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Shorebirds @ Grasshoppers Shorebirds @ Grasshoppers

Follow on MiLB First Pitch  https //stza.co/+wiwN-13

Shop  https //stza.co/+wiwN-1c

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Shorebirds @ Grasshoppers
END:VALARM
DTSTART:20180627T230000Z
DTEND:20180628T020000Z
UID:eUdT_QldRme7vENek4GA-Bgh@stanza.co
SUMMARY:Shorebirds @ Grasshoppers
DESCRIPTION:Shorebirds @ Grasshoppers\n\nFollow on MiLB First Pitch: https://stza.co/+wiwN-13\n\nShop: https://stza.co/+wiwN-1c\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144519Z
LAST-MODIFIED:20180213T144519Z
TRANSP:OPAQUE
END:VEVENT
* Shorebirds @ Grasshoppers
<2018-06-28 Thu 18:00-21:00>
:PROPERTIES:
:ID:       YGRnV5C7JwQpn8OUQz7CAlRQ@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Shorebirds @ Grasshoppers Shorebirds @ Grasshoppers

Follow on MiLB First Pitch  https //stza.co/+wiwO-2t

Shop  https //stza.co/+wiwO-3G

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Shorebirds @ Grasshoppers
END:VALARM
DTSTART:20180628T230000Z
DTEND:20180629T020000Z
UID:YGRnV5C7JwQpn8OUQz7CAlRQ@stanza.co
SUMMARY:Shorebirds @ Grasshoppers
DESCRIPTION:Shorebirds @ Grasshoppers\n\nFollow on MiLB First Pitch: https://stza.co/+wiwO-2t\n\nShop: https://stza.co/+wiwO-3G\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144519Z
LAST-MODIFIED:20180213T144519Z
TRANSP:OPAQUE
END:VEVENT
* Shorebirds @ Grasshoppers
<2018-06-29 Fri 18:00-21:00>
:PROPERTIES:
:ID:       7t0fn9QT6Pc8bdBQHF5dYb-V@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Shorebirds @ Grasshoppers Shorebirds @ Grasshoppers

Follow on MiLB First Pitch  https //stza.co/+wiwP-1n

Shop  https //stza.co/+wiwP-2u

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Shorebirds @ Grasshoppers
END:VALARM
DTSTART:20180629T230000Z
DTEND:20180630T020000Z
UID:7t0fn9QT6Pc8bdBQHF5dYb-V@stanza.co
SUMMARY:Shorebirds @ Grasshoppers
DESCRIPTION:Shorebirds @ Grasshoppers\n\nFollow on MiLB First Pitch: https://stza.co/+wiwP-1n\n\nShop: https://stza.co/+wiwP-2u\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144519Z
LAST-MODIFIED:20180213T144519Z
TRANSP:OPAQUE
END:VEVENT
* Shorebirds @ BlueClaws
<2018-06-30 Sat 18:05-21:05>
:PROPERTIES:
:ID:       PgjCTpzKijtvXRSkNIRlDlIA@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Shorebirds @ BlueClaws Shorebirds @ BlueClaws

Follow on MiLB First Pitch  https //stza.co/+vNIE-1q

Shop  https //stza.co/+vNIE-r

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Shorebirds @ BlueClaws
END:VALARM
DTSTART:20180630T230500Z
DTEND:20180701T020500Z
UID:PgjCTpzKijtvXRSkNIRlDlIA@stanza.co
SUMMARY:Shorebirds @ BlueClaws
DESCRIPTION:Shorebirds @ BlueClaws\n\nFollow on MiLB First Pitch: https://stza.co/+vNIE-1q\n\nShop: https://stza.co/+vNIE-r\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144519Z
LAST-MODIFIED:20180213T144519Z
TRANSP:OPAQUE
END:VEVENT
* Shorebirds @ BlueClaws
<2018-07-01 Sun 12:05-15:05>
:PROPERTIES:
:ID:       INQbHJ_qT7mPrhP-2FLckz-F@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Shorebirds @ BlueClaws Shorebirds @ BlueClaws

Follow on MiLB First Pitch  https //stza.co/+vNIF-T

Shop  https //stza.co/+vNIF-3S

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Shorebirds @ BlueClaws
END:VALARM
DTSTART:20180701T170500Z
DTEND:20180701T200500Z
UID:INQbHJ_qT7mPrhP-2FLckz-F@stanza.co
SUMMARY:Shorebirds @ BlueClaws
DESCRIPTION:Shorebirds @ BlueClaws\n\nFollow on MiLB First Pitch: https://stza.co/+vNIF-T\n\nShop: https://stza.co/+vNIF-3S\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144519Z
LAST-MODIFIED:20180213T144519Z
TRANSP:OPAQUE
END:VEVENT
* Shorebirds @ BlueClaws
<2018-07-02 Mon 18:05-21:05>
:PROPERTIES:
:ID:       0tNHyJ0EokQPffVT7gm4lfQE@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Shorebirds @ BlueClaws Shorebirds @ BlueClaws

Follow on MiLB First Pitch  https //stza.co/+vNIG-2T

Shop  https //stza.co/+vNIG-2d

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Shorebirds @ BlueClaws
END:VALARM
DTSTART:20180702T230500Z
DTEND:20180703T020500Z
UID:0tNHyJ0EokQPffVT7gm4lfQE@stanza.co
SUMMARY:Shorebirds @ BlueClaws
DESCRIPTION:Shorebirds @ BlueClaws\n\nFollow on MiLB First Pitch: https://stza.co/+vNIG-2T\n\nShop: https://stza.co/+vNIG-2d\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144519Z
LAST-MODIFIED:20180213T144519Z
TRANSP:OPAQUE
END:VEVENT
* Shorebirds @ BlueClaws
<2018-07-03 Tue 18:05-21:05>
:PROPERTIES:
:ID:       f6qmHzCD0kxepz0LiB9WIa0y@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Shorebirds @ BlueClaws Shorebirds @ BlueClaws

Follow on MiLB First Pitch  https //stza.co/+vNIH-h

Shop  https //stza.co/+vNIH-2s

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Shorebirds @ BlueClaws
END:VALARM
DTSTART:20180703T230500Z
DTEND:20180704T020500Z
UID:f6qmHzCD0kxepz0LiB9WIa0y@stanza.co
SUMMARY:Shorebirds @ BlueClaws
DESCRIPTION:Shorebirds @ BlueClaws\n\nFollow on MiLB First Pitch: https://stza.co/+vNIH-h\n\nShop: https://stza.co/+vNIH-2s\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144519Z
LAST-MODIFIED:20180213T144519Z
TRANSP:OPAQUE
END:VEVENT
* Shorebirds vs. Suns
<2018-07-04 Wed 17:05-20:05>
:PROPERTIES:
:ID:       QaqNS4FjWU5TWv2P_vsBJIpa@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Shorebirds vs. Suns Shorebirds vs. Suns

Follow on MiLB First Pitch  https //stza.co/+wHQA-1G

Shop  https //stza.co/+wHQA-O

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Shorebirds vs. Suns
END:VALARM
DTSTART:20180704T220500Z
DTEND:20180705T010500Z
UID:QaqNS4FjWU5TWv2P_vsBJIpa@stanza.co
SUMMARY:Shorebirds vs. Suns
DESCRIPTION:Shorebirds vs. Suns\n\nFollow on MiLB First Pitch: https://stza.co/+wHQA-1G\n\nShop: https://stza.co/+wHQA-O\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144519Z
LAST-MODIFIED:20180213T144519Z
TRANSP:OPAQUE
END:VEVENT
* Shorebirds vs. Suns
<2018-07-05 Thu 18:05-21:05>
:PROPERTIES:
:ID:       De9wFEIGbzZDAXhRO3cmHwO5@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Shorebirds vs. Suns Shorebirds vs. Suns

Follow on MiLB First Pitch  https //stza.co/+wHQF-

Shop  https //stza.co/+wHQF-1b

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Shorebirds vs. Suns
END:VALARM
DTSTART:20180705T230500Z
DTEND:20180706T020500Z
UID:De9wFEIGbzZDAXhRO3cmHwO5@stanza.co
SUMMARY:Shorebirds vs. Suns
DESCRIPTION:Shorebirds vs. Suns\n\nFollow on MiLB First Pitch: https://stza.co/+wHQF-\n\nShop: https://stza.co/+wHQF-1b\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144519Z
LAST-MODIFIED:20180213T144519Z
TRANSP:OPAQUE
END:VEVENT
* Shorebirds vs. Suns
<2018-07-06 Fri 18:05-21:05>
:PROPERTIES:
:ID:       Vgl9uJSh4J27eIlKWhLkefuy@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Shorebirds vs. Suns Shorebirds vs. Suns

Follow on MiLB First Pitch  https //stza.co/+wHQI-1N

Shop  https //stza.co/+wHQI-1j

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Shorebirds vs. Suns
END:VALARM
DTSTART:20180706T230500Z
DTEND:20180707T020500Z
UID:Vgl9uJSh4J27eIlKWhLkefuy@stanza.co
SUMMARY:Shorebirds vs. Suns
DESCRIPTION:Shorebirds vs. Suns\n\nFollow on MiLB First Pitch: https://stza.co/+wHQI-1N\n\nShop: https://stza.co/+wHQI-1j\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144519Z
LAST-MODIFIED:20180213T144519Z
TRANSP:OPAQUE
END:VEVENT
* Shorebirds vs. Crawdads
<2018-07-07 Sat 18:05-21:05>
:PROPERTIES:
:ID:       azTz0d27R9ncZDyEvoOY_nEr@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Shorebirds vs. Crawdads Shorebirds vs. Crawdads

Follow on MiLB First Pitch  https //stza.co/+wHQM-a

Shop  https //stza.co/+wHQM-b

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Shorebirds vs. Crawdads
END:VALARM
DTSTART:20180707T230500Z
DTEND:20180708T020500Z
UID:azTz0d27R9ncZDyEvoOY_nEr@stanza.co
SUMMARY:Shorebirds vs. Crawdads
DESCRIPTION:Shorebirds vs. Crawdads\n\nFollow on MiLB First Pitch: https://stza.co/+wHQM-a\n\nShop: https://stza.co/+wHQM-b\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144519Z
LAST-MODIFIED:20180213T144519Z
TRANSP:OPAQUE
END:VEVENT
* Shorebirds vs. Crawdads
<2018-07-08 Sun 16:05-19:05>
:PROPERTIES:
:ID:       6CEcaTqdUkW9FtG4Flhtm3-p@stanza.co
:LOCATION: Kids run the bases for today's game. Bring out the family!
:STATUS:   CONFIRMED
:END:

Shorebirds vs. Crawdads Bring 2 canned food items to the Shorebirds box office and receive an upper reserved ticket for $3. All collected items will be donated to the local area food banks.

Kids 13 & under get to run the bases after the game, presented by Chili's Grill & Bar.

Follow on MiLB First Pitch  https //stza.co/+wHQQ-1S

Shop  https //stza.co/+wHQQ-3r

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Shorebirds vs. Crawdads
END:VALARM
DTSTART:20180708T210500Z
DTEND:20180709T000500Z
UID:6CEcaTqdUkW9FtG4Flhtm3-p@stanza.co
SUMMARY:Shorebirds vs. Crawdads
DESCRIPTION:Bring 2 canned food items to the Shorebirds box office and receive an upper reserved ticket for $3. All collected items will be donated to the local area food banks.\n\nKids 13 & under get to run the bases after the game, presented by Chili's Grill & Bar.\n\nFollow on MiLB First Pitch: https://stza.co/+wHQQ-1S\n\nShop: https://stza.co/+wHQQ-3r\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Kids run the bases for today's game. Bring out the family!
STATUS:CONFIRMED
CREATED:20180213T144519Z
LAST-MODIFIED:20180213T144519Z
TRANSP:OPAQUE
END:VEVENT
* Shorebirds vs. Crawdads
<2018-07-09 Mon 18:05-21:05>
:PROPERTIES:
:ID:       tEoIY-vpzt_x29-vsDSL6r5v@stanza.co
:LOCATION: 47 ABC 2 Buck Monday
:STATUS:   CONFIRMED
:END:

Shorebirds vs. Crawdads Enjoy $2 Upper Reserved tickets, $2 hotdogs, and $2 fountain Pepsi products.

Follow on MiLB First Pitch  https //stza.co/+wHQS-2M

Shop  https //stza.co/+wHQS-3k

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Shorebirds vs. Crawdads
END:VALARM
DTSTART:20180709T230500Z
DTEND:20180710T020500Z
UID:tEoIY-vpzt_x29-vsDSL6r5v@stanza.co
SUMMARY:Shorebirds vs. Crawdads
DESCRIPTION:Enjoy $2 Upper Reserved tickets, $2 hotdogs, and $2 fountain Pepsi products.\n\nFollow on MiLB First Pitch: https://stza.co/+wHQS-2M\n\nShop: https://stza.co/+wHQS-3k\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:47 ABC 2 Buck Monday
STATUS:CONFIRMED
CREATED:20180213T144519Z
LAST-MODIFIED:20180213T144519Z
TRANSP:OPAQUE
END:VEVENT
* Shorebirds @ RiverDogs
<2018-07-11 Wed 18:05-21:05>
:PROPERTIES:
:ID:       uRe_DJ-Rvi2jce45nXX8vLXt@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Shorebirds @ RiverDogs Shorebirds @ RiverDogs

Follow on MiLB First Pitch  https //stza.co/+vNFK-Y

Shop  https //stza.co/+vNFK-2i

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Shorebirds @ RiverDogs
END:VALARM
DTSTART:20180711T230500Z
DTEND:20180712T020500Z
UID:uRe_DJ-Rvi2jce45nXX8vLXt@stanza.co
SUMMARY:Shorebirds @ RiverDogs
DESCRIPTION:Shorebirds @ RiverDogs\n\nFollow on MiLB First Pitch: https://stza.co/+vNFK-Y\n\nShop: https://stza.co/+vNFK-2i\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144519Z
LAST-MODIFIED:20180213T144519Z
TRANSP:OPAQUE
END:VEVENT
* Shorebirds @ RiverDogs
<2018-07-12 Thu 18:05-21:05>
:PROPERTIES:
:ID:       FhZ-JDA4WRMkR19dEvxsfROA@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Shorebirds @ RiverDogs Shorebirds @ RiverDogs

Follow on MiLB First Pitch  https //stza.co/+vNFL-1u

Shop  https //stza.co/+vNFL-1U

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Shorebirds @ RiverDogs
END:VALARM
DTSTART:20180712T230500Z
DTEND:20180713T020500Z
UID:FhZ-JDA4WRMkR19dEvxsfROA@stanza.co
SUMMARY:Shorebirds @ RiverDogs
DESCRIPTION:Shorebirds @ RiverDogs\n\nFollow on MiLB First Pitch: https://stza.co/+vNFL-1u\n\nShop: https://stza.co/+vNFL-1U\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144519Z
LAST-MODIFIED:20180213T144519Z
TRANSP:OPAQUE
END:VEVENT
* Shorebirds @ RiverDogs
<2018-07-13 Fri 18:05-21:05>
:PROPERTIES:
:ID:       v7WZafPSuHrHQtaJ4oE3d5-2@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Shorebirds @ RiverDogs Shorebirds @ RiverDogs

Follow on MiLB First Pitch  https //stza.co/+vNFM-2$

Shop  https //stza.co/+vNFM-3X

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Shorebirds @ RiverDogs
END:VALARM
DTSTART:20180713T230500Z
DTEND:20180714T020500Z
UID:v7WZafPSuHrHQtaJ4oE3d5-2@stanza.co
SUMMARY:Shorebirds @ RiverDogs
DESCRIPTION:Shorebirds @ RiverDogs\n\nFollow on MiLB First Pitch: https://stza.co/+vNFM-2$\n\nShop: https://stza.co/+vNFM-3X\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144519Z
LAST-MODIFIED:20180213T144519Z
TRANSP:OPAQUE
END:VEVENT
* Shorebirds @ Power
<2018-07-14 Sat 17:05-20:05>
:PROPERTIES:
:ID:       bp9nRLorg3adXyVv-7CPFt-4@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Shorebirds @ Power Shorebirds @ Power

Follow on MiLB First Pitch  https //stza.co/+xJ3I-w

Shop  https //stza.co/+xJ3I-28

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Shorebirds @ Power
END:VALARM
DTSTART:20180714T220500Z
DTEND:20180715T010500Z
UID:bp9nRLorg3adXyVv-7CPFt-4@stanza.co
SUMMARY:Shorebirds @ Power
DESCRIPTION:Shorebirds @ Power\n\nFollow on MiLB First Pitch: https://stza.co/+xJ3I-w\n\nShop: https://stza.co/+xJ3I-28\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144519Z
LAST-MODIFIED:20180213T144519Z
TRANSP:OPAQUE
END:VEVENT
* Shorebirds @ Power
<2018-07-15 Sun 13:05-16:05>
:PROPERTIES:
:ID:       KcCAUAOJLR4X4Wj5BVEf67_c@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Shorebirds @ Power Shorebirds @ Power

Follow on MiLB First Pitch  https //stza.co/+xJ3J-L

Shop  https //stza.co/+xJ3J-H

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Shorebirds @ Power
END:VALARM
DTSTART:20180715T180500Z
DTEND:20180715T210500Z
UID:KcCAUAOJLR4X4Wj5BVEf67_c@stanza.co
SUMMARY:Shorebirds @ Power
DESCRIPTION:Shorebirds @ Power\n\nFollow on MiLB First Pitch: https://stza.co/+xJ3J-L\n\nShop: https://stza.co/+xJ3J-H\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144519Z
LAST-MODIFIED:20180213T144519Z
TRANSP:OPAQUE
END:VEVENT
* Shorebirds @ Power
<2018-07-16 Mon 18:05-21:05>
:PROPERTIES:
:ID:       sSGWC7sPMZJcYoiTArcZt_O5@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Shorebirds @ Power Shorebirds @ Power

Follow on MiLB First Pitch  https //stza.co/+xJ3K-y

Shop  https //stza.co/+xJ3K-z

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Shorebirds @ Power
END:VALARM
DTSTART:20180716T230500Z
DTEND:20180717T020500Z
UID:sSGWC7sPMZJcYoiTArcZt_O5@stanza.co
SUMMARY:Shorebirds @ Power
DESCRIPTION:Shorebirds @ Power\n\nFollow on MiLB First Pitch: https://stza.co/+xJ3K-y\n\nShop: https://stza.co/+xJ3K-z\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144519Z
LAST-MODIFIED:20180213T144519Z
TRANSP:OPAQUE
END:VEVENT
* Shorebirds @ Power
<2018-07-17 Tue 11:05-14:05>
:PROPERTIES:
:ID:       2UT7o8omHOeqw44sBBFQVnLz@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Shorebirds @ Power Shorebirds @ Power

Follow on MiLB First Pitch  https //stza.co/+xJ3L-18

Shop  https //stza.co/+xJ3L-2f

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Shorebirds @ Power
END:VALARM
DTSTART:20180717T160500Z
DTEND:20180717T190500Z
UID:2UT7o8omHOeqw44sBBFQVnLz@stanza.co
SUMMARY:Shorebirds @ Power
DESCRIPTION:Shorebirds @ Power\n\nFollow on MiLB First Pitch: https://stza.co/+xJ3L-18\n\nShop: https://stza.co/+xJ3L-2f\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144519Z
LAST-MODIFIED:20180213T144519Z
TRANSP:OPAQUE
END:VEVENT
* Shorebirds vs. Grasshoppers
<2018-07-19 Thu 18:05-21:05>
:PROPERTIES:
:ID:       Oc58K3nO-rx27wRMpjJK5vy2@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Shorebirds vs. Grasshoppers Shorebirds vs. Grasshoppers

Follow on MiLB First Pitch  https //stza.co/+wHQU-2p

Shop  https //stza.co/+wHQU-3c

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Shorebirds vs. Grasshoppers
END:VALARM
DTSTART:20180719T230500Z
DTEND:20180720T020500Z
UID:Oc58K3nO-rx27wRMpjJK5vy2@stanza.co
SUMMARY:Shorebirds vs. Grasshoppers
DESCRIPTION:Shorebirds vs. Grasshoppers\n\nFollow on MiLB First Pitch: https://stza.co/+wHQU-2p\n\nShop: https://stza.co/+wHQU-3c\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144519Z
LAST-MODIFIED:20180213T144519Z
TRANSP:OPAQUE
END:VEVENT
* Shorebirds vs. Grasshoppers
<2018-07-20 Fri 18:05-21:05>
:PROPERTIES:
:ID:       I0yOFbszqEN3YzQ0KYfWuU3i@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Shorebirds vs. Grasshoppers Shorebirds vs. Grasshoppers

Follow on MiLB First Pitch  https //stza.co/+wHR3-H

Shop  https //stza.co/+wHR3-Z

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Shorebirds vs. Grasshoppers
END:VALARM
DTSTART:20180720T230500Z
DTEND:20180721T020500Z
UID:I0yOFbszqEN3YzQ0KYfWuU3i@stanza.co
SUMMARY:Shorebirds vs. Grasshoppers
DESCRIPTION:Shorebirds vs. Grasshoppers\n\nFollow on MiLB First Pitch: https://stza.co/+wHR3-H\n\nShop: https://stza.co/+wHR3-Z\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144519Z
LAST-MODIFIED:20180213T144519Z
TRANSP:OPAQUE
END:VEVENT
* Shorebirds vs. Grasshoppers
<2018-07-21 Sat 18:05-21:05>
:PROPERTIES:
:ID:       l2adJ-62IFBN3ZYQIZI6Tb_b@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Shorebirds vs. Grasshoppers Shorebirds vs. Grasshoppers

Follow on MiLB First Pitch  https //stza.co/+wHR6-3H

Shop  https //stza.co/+wHR6-1X

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Shorebirds vs. Grasshoppers
END:VALARM
DTSTART:20180721T230500Z
DTEND:20180722T020500Z
UID:l2adJ-62IFBN3ZYQIZI6Tb_b@stanza.co
SUMMARY:Shorebirds vs. Grasshoppers
DESCRIPTION:Shorebirds vs. Grasshoppers\n\nFollow on MiLB First Pitch: https://stza.co/+wHR6-3H\n\nShop: https://stza.co/+wHR6-1X\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144519Z
LAST-MODIFIED:20180213T144519Z
TRANSP:OPAQUE
END:VEVENT
* Shorebirds vs. Grasshoppers
<2018-07-22 Sun 16:05-19:05>
:PROPERTIES:
:ID:       B0zFax_QAofPuZv6Hp6P9Mar@stanza.co
:LOCATION: Kids run the bases for today's game. Bring out the family!
:STATUS:   CONFIRMED
:END:

Shorebirds vs. Grasshoppers Bring 2 canned food items to the Shorebirds box office and receive an upper reserved ticket for $3. All collected items will be donated to the local area food banks.

Kids 13 & under get to run the bases after the game, presented by Chili's Grill & Bar.

Follow on MiLB First Pitch  https //stza.co/+wHRa-3s

Shop  https //stza.co/+wHRa-1i

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Shorebirds vs. Grasshoppers
END:VALARM
DTSTART:20180722T210500Z
DTEND:20180723T000500Z
UID:B0zFax_QAofPuZv6Hp6P9Mar@stanza.co
SUMMARY:Shorebirds vs. Grasshoppers
DESCRIPTION:Bring 2 canned food items to the Shorebirds box office and receive an upper reserved ticket for $3. All collected items will be donated to the local area food banks.\n\nKids 13 & under get to run the bases after the game, presented by Chili's Grill & Bar.\n\nFollow on MiLB First Pitch: https://stza.co/+wHRa-3s\n\nShop: https://stza.co/+wHRa-1i\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Kids run the bases for today's game. Bring out the family!
STATUS:CONFIRMED
CREATED:20180213T144519Z
LAST-MODIFIED:20180213T144519Z
TRANSP:OPAQUE
END:VEVENT
* Shorebirds @ Suns
<2018-07-23 Mon 18:05-21:05>
:PROPERTIES:
:ID:       XhgAWeSjAPNIIbu1W1u7v5b9@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Shorebirds @ Suns Shorebirds @ Suns

Follow on MiLB First Pitch  https //stza.co/+xE_5-1b

Shop  https //stza.co/+xE_5-3C

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Shorebirds @ Suns
END:VALARM
DTSTART:20180723T230500Z
DTEND:20180724T020500Z
UID:XhgAWeSjAPNIIbu1W1u7v5b9@stanza.co
SUMMARY:Shorebirds @ Suns
DESCRIPTION:Shorebirds @ Suns\n\nFollow on MiLB First Pitch: https://stza.co/+xE_5-1b\n\nShop: https://stza.co/+xE_5-3C\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144519Z
LAST-MODIFIED:20180213T144519Z
TRANSP:OPAQUE
END:VEVENT
* Shorebirds @ Suns
<2018-07-24 Tue 18:05-21:05>
:PROPERTIES:
:ID:       92BBmhdyqpf2nuHBcpvw6UQl@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Shorebirds @ Suns Shorebirds @ Suns

Follow on MiLB First Pitch  https //stza.co/+xE_6-3P

Shop  https //stza.co/+xE_6-1A

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Shorebirds @ Suns
END:VALARM
DTSTART:20180724T230500Z
DTEND:20180725T020500Z
UID:92BBmhdyqpf2nuHBcpvw6UQl@stanza.co
SUMMARY:Shorebirds @ Suns
DESCRIPTION:Shorebirds @ Suns\n\nFollow on MiLB First Pitch: https://stza.co/+xE_6-3P\n\nShop: https://stza.co/+xE_6-1A\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144519Z
LAST-MODIFIED:20180213T144519Z
TRANSP:OPAQUE
END:VEVENT
* Shorebirds @ Suns
<2018-07-25 Wed 18:05-21:05>
:PROPERTIES:
:ID:       lxMXArdO8c7rfhGtmtSTqaf2@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Shorebirds @ Suns Shorebirds @ Suns

Follow on MiLB First Pitch  https //stza.co/+xE_7-3i

Shop  https //stza.co/+xE_7-32

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Shorebirds @ Suns
END:VALARM
DTSTART:20180725T230500Z
DTEND:20180726T020500Z
UID:lxMXArdO8c7rfhGtmtSTqaf2@stanza.co
SUMMARY:Shorebirds @ Suns
DESCRIPTION:Shorebirds @ Suns\n\nFollow on MiLB First Pitch: https://stza.co/+xE_7-3i\n\nShop: https://stza.co/+xE_7-32\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144519Z
LAST-MODIFIED:20180213T144519Z
TRANSP:OPAQUE
END:VEVENT
* Shorebirds @ Suns
<2018-07-26 Thu 18:05-21:05>
:PROPERTIES:
:ID:       QdENG9BP8ldyrRQRlGriPVZF@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Shorebirds @ Suns Shorebirds @ Suns

Follow on MiLB First Pitch  https //stza.co/+xE_9-26

Shop  https //stza.co/+xE_9-1u

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Shorebirds @ Suns
END:VALARM
DTSTART:20180726T230500Z
DTEND:20180727T020500Z
UID:QdENG9BP8ldyrRQRlGriPVZF@stanza.co
SUMMARY:Shorebirds @ Suns
DESCRIPTION:Shorebirds @ Suns\n\nFollow on MiLB First Pitch: https://stza.co/+xE_9-26\n\nShop: https://stza.co/+xE_9-1u\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144519Z
LAST-MODIFIED:20180213T144519Z
TRANSP:OPAQUE
END:VEVENT
* Shorebirds @ Intimidators
<2018-07-27 Fri 18:05-21:05>
:PROPERTIES:
:ID:       uJKtXKMVym-TavR08ksNOgWB@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Shorebirds @ Intimidators Shorebirds @ Intimidators

Follow on MiLB First Pitch  https //stza.co/+wIBO-D

Shop  https //stza.co/+wIBO-3X

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Shorebirds @ Intimidators
END:VALARM
DTSTART:20180727T230500Z
DTEND:20180728T020500Z
UID:uJKtXKMVym-TavR08ksNOgWB@stanza.co
SUMMARY:Shorebirds @ Intimidators
DESCRIPTION:Shorebirds @ Intimidators\n\nFollow on MiLB First Pitch: https://stza.co/+wIBO-D\n\nShop: https://stza.co/+wIBO-3X\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144519Z
LAST-MODIFIED:20180213T144519Z
TRANSP:OPAQUE
END:VEVENT
* Shorebirds @ Intimidators
<2018-07-28 Sat 18:05-21:05>
:PROPERTIES:
:ID:       baMvl-pjON20Y5Fnool0L-kL@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Shorebirds @ Intimidators Shorebirds @ Intimidators

Follow on MiLB First Pitch  https //stza.co/+wIBP-3m

Shop  https //stza.co/+wIBP-27

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Shorebirds @ Intimidators
END:VALARM
DTSTART:20180728T230500Z
DTEND:20180729T020500Z
UID:baMvl-pjON20Y5Fnool0L-kL@stanza.co
SUMMARY:Shorebirds @ Intimidators
DESCRIPTION:Shorebirds @ Intimidators\n\nFollow on MiLB First Pitch: https://stza.co/+wIBP-3m\n\nShop: https://stza.co/+wIBP-27\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144519Z
LAST-MODIFIED:20180213T144519Z
TRANSP:OPAQUE
END:VEVENT
* Shorebirds @ Intimidators
<2018-07-29 Sun 16:05-19:05>
:PROPERTIES:
:ID:       04Q1gVpMQg3b_XHzdlVW7Omg@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Shorebirds @ Intimidators Shorebirds @ Intimidators

Follow on MiLB First Pitch  https //stza.co/+wIBR-1E

Shop  https //stza.co/+wIBR-3P

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Shorebirds @ Intimidators
END:VALARM
DTSTART:20180729T210500Z
DTEND:20180730T000500Z
UID:04Q1gVpMQg3b_XHzdlVW7Omg@stanza.co
SUMMARY:Shorebirds @ Intimidators
DESCRIPTION:Shorebirds @ Intimidators\n\nFollow on MiLB First Pitch: https://stza.co/+wIBR-1E\n\nShop: https://stza.co/+wIBR-3P\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144519Z
LAST-MODIFIED:20180213T144519Z
TRANSP:OPAQUE
END:VEVENT
* Shorebirds vs. BlueClaws
<2018-07-30 Mon 18:05-21:05>
:PROPERTIES:
:ID:       9g7zg5RaONmTI_Rt4W-Pm50k@stanza.co
:LOCATION: 47 ABC 2 Buck Monday
:STATUS:   CONFIRMED
:END:

Shorebirds vs. BlueClaws Enjoy $2 Upper Reserved tickets, $2 hotdogs, and $2 fountain Pepsi products.

Follow on MiLB First Pitch  https //stza.co/+wHRe-2H

Shop  https //stza.co/+wHRe-2t

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Shorebirds vs. BlueClaws
END:VALARM
DTSTART:20180730T230500Z
DTEND:20180731T020500Z
UID:9g7zg5RaONmTI_Rt4W-Pm50k@stanza.co
SUMMARY:Shorebirds vs. BlueClaws
DESCRIPTION:Enjoy $2 Upper Reserved tickets, $2 hotdogs, and $2 fountain Pepsi products.\n\nFollow on MiLB First Pitch: https://stza.co/+wHRe-2H\n\nShop: https://stza.co/+wHRe-2t\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:47 ABC 2 Buck Monday
STATUS:CONFIRMED
CREATED:20180213T144519Z
LAST-MODIFIED:20180213T144519Z
TRANSP:OPAQUE
END:VEVENT
* Shorebirds vs. BlueClaws
<2018-07-31 Tue 18:05-21:05>
:PROPERTIES:
:ID:       1ygzcAgBXSRQT6XQi3QUtPlX@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Shorebirds vs. BlueClaws Shorebirds vs. BlueClaws

Follow on MiLB First Pitch  https //stza.co/+wHRj-v

Shop  https //stza.co/+wHRj-3k

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Shorebirds vs. BlueClaws
END:VALARM
DTSTART:20180731T230500Z
DTEND:20180801T020500Z
UID:1ygzcAgBXSRQT6XQi3QUtPlX@stanza.co
SUMMARY:Shorebirds vs. BlueClaws
DESCRIPTION:Shorebirds vs. BlueClaws\n\nFollow on MiLB First Pitch: https://stza.co/+wHRj-v\n\nShop: https://stza.co/+wHRj-3k\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144519Z
LAST-MODIFIED:20180213T144519Z
TRANSP:OPAQUE
END:VEVENT
* Shorebirds vs. BlueClaws
<2018-08-01 Wed 18:05-21:05>
:PROPERTIES:
:ID:       -23r_i2L4OiZ_ZH30uyNjYLL@stanza.co
:LOCATION: Silver Slugger Game
:STATUS:   CONFIRMED
:END:

Shorebirds vs. BlueClaws This game is included in the Silver Sluggers membership for fans 55 and up.

Follow on MiLB First Pitch  https //stza.co/+wHRm-3P

Shop  https //stza.co/+wHRm-1G

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Shorebirds vs. BlueClaws
END:VALARM
DTSTART:20180801T230500Z
DTEND:20180802T020500Z
UID:-23r_i2L4OiZ_ZH30uyNjYLL@stanza.co
SUMMARY:Shorebirds vs. BlueClaws
DESCRIPTION:This game is included in the Silver Sluggers membership for fans 55 and up.\n\nFollow on MiLB First Pitch: https://stza.co/+wHRm-3P\n\nShop: https://stza.co/+wHRm-1G\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Silver Slugger Game
STATUS:CONFIRMED
CREATED:20180213T144519Z
LAST-MODIFIED:20180213T144519Z
TRANSP:OPAQUE
END:VEVENT
* Shorebirds vs. RiverDogs
<2018-08-02 Thu 18:05-21:05>
:PROPERTIES:
:ID:       p3qnxl-QJqFYUa83_SCkeivu@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Shorebirds vs. RiverDogs Shorebirds vs. RiverDogs

Follow on MiLB First Pitch  https //stza.co/+wHRq-9

Shop  https //stza.co/+wHRq-1m

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Shorebirds vs. RiverDogs
END:VALARM
DTSTART:20180802T230500Z
DTEND:20180803T020500Z
UID:p3qnxl-QJqFYUa83_SCkeivu@stanza.co
SUMMARY:Shorebirds vs. RiverDogs
DESCRIPTION:Shorebirds vs. RiverDogs\n\nFollow on MiLB First Pitch: https://stza.co/+wHRq-9\n\nShop: https://stza.co/+wHRq-1m\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144519Z
LAST-MODIFIED:20180213T144519Z
TRANSP:OPAQUE
END:VEVENT
* Shorebirds vs. RiverDogs
<2018-08-03 Fri 18:05-21:05>
:PROPERTIES:
:ID:       ImLwAw-UHpWT3YqSQZaWqzDL@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Shorebirds vs. RiverDogs Shorebirds vs. RiverDogs

Follow on MiLB First Pitch  https //stza.co/+wHRt-16

Shop  https //stza.co/+wHRt-9

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Shorebirds vs. RiverDogs
END:VALARM
DTSTART:20180803T230500Z
DTEND:20180804T020500Z
UID:ImLwAw-UHpWT3YqSQZaWqzDL@stanza.co
SUMMARY:Shorebirds vs. RiverDogs
DESCRIPTION:Shorebirds vs. RiverDogs\n\nFollow on MiLB First Pitch: https://stza.co/+wHRt-16\n\nShop: https://stza.co/+wHRt-9\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144519Z
LAST-MODIFIED:20180213T144519Z
TRANSP:OPAQUE
END:VEVENT
* Shorebirds vs. RiverDogs
<2018-08-04 Sat 18:05-21:05>
:PROPERTIES:
:ID:       4tWxqzhIE1bqvPc4j_9UiU0L@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Shorebirds vs. RiverDogs Shorebirds vs. RiverDogs

Follow on MiLB First Pitch  https //stza.co/+wHRv-3V

Shop  https //stza.co/+wHRv-2D

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Shorebirds vs. RiverDogs
END:VALARM
DTSTART:20180804T230500Z
DTEND:20180805T020500Z
UID:4tWxqzhIE1bqvPc4j_9UiU0L@stanza.co
SUMMARY:Shorebirds vs. RiverDogs
DESCRIPTION:Shorebirds vs. RiverDogs\n\nFollow on MiLB First Pitch: https://stza.co/+wHRv-3V\n\nShop: https://stza.co/+wHRv-2D\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144519Z
LAST-MODIFIED:20180213T144519Z
TRANSP:OPAQUE
END:VEVENT
* Shorebirds vs. RiverDogs
<2018-08-05 Sun 16:05-19:05>
:PROPERTIES:
:ID:       gEgBjkIObScx6LKqmIpuZljM@stanza.co
:LOCATION: Kids run the bases for today's game. Bring out the family!
:STATUS:   CONFIRMED
:END:

Shorebirds vs. RiverDogs Bring 2 canned food items to the Shorebirds box office and receive an upper reserved ticket for $3. All collected items will be donated to the local area food banks.

Kids 13 & under get to run the bases after the game, presented by Chili's Grill & Bar.

Follow on MiLB First Pitch  https //stza.co/+wHRx-18

Shop  https //stza.co/+wHRx-3l

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Shorebirds vs. RiverDogs
END:VALARM
DTSTART:20180805T210500Z
DTEND:20180806T000500Z
UID:gEgBjkIObScx6LKqmIpuZljM@stanza.co
SUMMARY:Shorebirds vs. RiverDogs
DESCRIPTION:Bring 2 canned food items to the Shorebirds box office and receive an upper reserved ticket for $3. All collected items will be donated to the local area food banks.\n\nKids 13 & under get to run the bases after the game, presented by Chili's Grill & Bar.\n\nFollow on MiLB First Pitch: https://stza.co/+wHRx-18\n\nShop: https://stza.co/+wHRx-3l\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Kids run the bases for today's game. Bring out the family!
STATUS:CONFIRMED
CREATED:20180213T144519Z
LAST-MODIFIED:20180213T144519Z
TRANSP:OPAQUE
END:VEVENT
* Shorebirds @ Braves
<2018-08-07 Tue 18:00-21:00>
:PROPERTIES:
:ID:       Mu0kaeh4ErpBpHCGh5Ct18uO@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Shorebirds @ Braves Shorebirds @ Braves

Follow on MiLB First Pitch  https //stza.co/+vNIP-1X

Shop  https //stza.co/+vNIP-2g

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Shorebirds @ Braves
END:VALARM
DTSTART:20180807T230000Z
DTEND:20180808T020000Z
UID:Mu0kaeh4ErpBpHCGh5Ct18uO@stanza.co
SUMMARY:Shorebirds @ Braves
DESCRIPTION:Shorebirds @ Braves\n\nFollow on MiLB First Pitch: https://stza.co/+vNIP-1X\n\nShop: https://stza.co/+vNIP-2g\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144519Z
LAST-MODIFIED:20180213T144519Z
TRANSP:OPAQUE
END:VEVENT
* Shorebirds @ Braves
<2018-08-08 Wed 18:00-21:00>
:PROPERTIES:
:ID:       iGY2CPtvvPO5YVYL2ihsCdGr@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Shorebirds @ Braves Shorebirds @ Braves

Follow on MiLB First Pitch  https //stza.co/+vNIQ-x

Shop  https //stza.co/+vNIQ-1C

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Shorebirds @ Braves
END:VALARM
DTSTART:20180808T230000Z
DTEND:20180809T020000Z
UID:iGY2CPtvvPO5YVYL2ihsCdGr@stanza.co
SUMMARY:Shorebirds @ Braves
DESCRIPTION:Shorebirds @ Braves\n\nFollow on MiLB First Pitch: https://stza.co/+vNIQ-x\n\nShop: https://stza.co/+vNIQ-1C\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144519Z
LAST-MODIFIED:20180213T144519Z
TRANSP:OPAQUE
END:VEVENT
* Shorebirds @ Braves
<2018-08-09 Thu 18:00-21:00>
:PROPERTIES:
:ID:       v-LTEzeF5MWNFJ5bfWFJB2aH@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Shorebirds @ Braves Shorebirds @ Braves

Follow on MiLB First Pitch  https //stza.co/+vNIR-e

Shop  https //stza.co/+vNIR-1J

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Shorebirds @ Braves
END:VALARM
DTSTART:20180809T230000Z
DTEND:20180810T020000Z
UID:v-LTEzeF5MWNFJ5bfWFJB2aH@stanza.co
SUMMARY:Shorebirds @ Braves
DESCRIPTION:Shorebirds @ Braves\n\nFollow on MiLB First Pitch: https://stza.co/+vNIR-e\n\nShop: https://stza.co/+vNIR-1J\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144519Z
LAST-MODIFIED:20180213T144519Z
TRANSP:OPAQUE
END:VEVENT
* Shorebirds @ Fireflies
<2018-08-10 Fri 18:05-21:05>
:PROPERTIES:
:ID:       dI29-VFiNg-Ta-NjphSM15V8@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Shorebirds @ Fireflies Shorebirds @ Fireflies

Follow on MiLB First Pitch  https //stza.co/+xBQN-1w

Shop  https //stza.co/+xBQN-2J

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Shorebirds @ Fireflies
END:VALARM
DTSTART:20180810T230500Z
DTEND:20180811T020500Z
UID:dI29-VFiNg-Ta-NjphSM15V8@stanza.co
SUMMARY:Shorebirds @ Fireflies
DESCRIPTION:Shorebirds @ Fireflies\n\nFollow on MiLB First Pitch: https://stza.co/+xBQN-1w\n\nShop: https://stza.co/+xBQN-2J\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144519Z
LAST-MODIFIED:20180213T144519Z
TRANSP:OPAQUE
END:VEVENT
* Shorebirds @ Fireflies
<2018-08-11 Sat 17:05-20:05>
:PROPERTIES:
:ID:       CKrmCLTwNAmEeldPl-8O5sNa@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Shorebirds @ Fireflies Shorebirds @ Fireflies

Follow on MiLB First Pitch  https //stza.co/+xBQS-2D

Shop  https //stza.co/+xBQS-2U

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Shorebirds @ Fireflies
END:VALARM
DTSTART:20180811T220500Z
DTEND:20180812T010500Z
UID:CKrmCLTwNAmEeldPl-8O5sNa@stanza.co
SUMMARY:Shorebirds @ Fireflies
DESCRIPTION:Shorebirds @ Fireflies\n\nFollow on MiLB First Pitch: https://stza.co/+xBQS-2D\n\nShop: https://stza.co/+xBQS-2U\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144519Z
LAST-MODIFIED:20180213T144519Z
TRANSP:OPAQUE
END:VEVENT
* Shorebirds @ Fireflies
<2018-08-12 Sun 13:05-16:05>
:PROPERTIES:
:ID:       wfYazgoa7G6GHBt405fxBJKV@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Shorebirds @ Fireflies Shorebirds @ Fireflies

Follow on MiLB First Pitch  https //stza.co/+xB17-z

Shop  https //stza.co/+xB17-3Z

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Shorebirds @ Fireflies
END:VALARM
DTSTART:20180812T180500Z
DTEND:20180812T210500Z
UID:wfYazgoa7G6GHBt405fxBJKV@stanza.co
SUMMARY:Shorebirds @ Fireflies
DESCRIPTION:Shorebirds @ Fireflies\n\nFollow on MiLB First Pitch: https://stza.co/+xB17-z\n\nShop: https://stza.co/+xB17-3Z\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144519Z
LAST-MODIFIED:20180213T144519Z
TRANSP:OPAQUE
END:VEVENT
* Shorebirds @ Fireflies
<2018-08-13 Mon 18:05-21:05>
:PROPERTIES:
:ID:       EhG-MFdAOgPN7vasx6i3F30H@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Shorebirds @ Fireflies Shorebirds @ Fireflies

Follow on MiLB First Pitch  https //stza.co/+xB1d-1p

Shop  https //stza.co/+xB1d-1v

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Shorebirds @ Fireflies
END:VALARM
DTSTART:20180813T230500Z
DTEND:20180814T020500Z
UID:EhG-MFdAOgPN7vasx6i3F30H@stanza.co
SUMMARY:Shorebirds @ Fireflies
DESCRIPTION:Shorebirds @ Fireflies\n\nFollow on MiLB First Pitch: https://stza.co/+xB1d-1p\n\nShop: https://stza.co/+xB1d-1v\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144519Z
LAST-MODIFIED:20180213T144519Z
TRANSP:OPAQUE
END:VEVENT
* Shorebirds vs. RiverDogs
<2018-08-15 Wed 18:05-21:05>
:PROPERTIES:
:ID:       2xPdiz21HvamtH7dC85hWeJh@stanza.co
:LOCATION: Silver Slugger Game
:STATUS:   CONFIRMED
:END:

Shorebirds vs. RiverDogs This game is included in the Silver Sluggers membership for fans 55 and up.

Follow on MiLB First Pitch  https //stza.co/+wHRz-1

Shop  https //stza.co/+wHRz-1Y

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Shorebirds vs. RiverDogs
END:VALARM
DTSTART:20180815T230500Z
DTEND:20180816T020500Z
UID:2xPdiz21HvamtH7dC85hWeJh@stanza.co
SUMMARY:Shorebirds vs. RiverDogs
DESCRIPTION:This game is included in the Silver Sluggers membership for fans 55 and up.\n\nFollow on MiLB First Pitch: https://stza.co/+wHRz-1\n\nShop: https://stza.co/+wHRz-1Y\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Silver Slugger Game
STATUS:CONFIRMED
CREATED:20180213T144519Z
LAST-MODIFIED:20180213T144519Z
TRANSP:OPAQUE
END:VEVENT
* Shorebirds vs. RiverDogs
<2018-08-16 Thu 18:05-21:05>
:PROPERTIES:
:ID:       Mh5K-C6r_40JtYVqUElqzI-G@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Shorebirds vs. RiverDogs Shorebirds vs. RiverDogs

Follow on MiLB First Pitch  https //stza.co/+wHRB-V

Shop  https //stza.co/+wHRB-5

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Shorebirds vs. RiverDogs
END:VALARM
DTSTART:20180816T230500Z
DTEND:20180817T020500Z
UID:Mh5K-C6r_40JtYVqUElqzI-G@stanza.co
SUMMARY:Shorebirds vs. RiverDogs
DESCRIPTION:Shorebirds vs. RiverDogs\n\nFollow on MiLB First Pitch: https://stza.co/+wHRB-V\n\nShop: https://stza.co/+wHRB-5\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144519Z
LAST-MODIFIED:20180213T144519Z
TRANSP:OPAQUE
END:VEVENT
* Shorebirds vs. RiverDogs
<2018-08-17 Fri 18:05-21:05>
:PROPERTIES:
:ID:       ylL-QIgM4DEzkHF4akhsG6dm@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Shorebirds vs. RiverDogs Shorebirds vs. RiverDogs

Follow on MiLB First Pitch  https //stza.co/+wHRE-35

Shop  https //stza.co/+wHRE-3X

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Shorebirds vs. RiverDogs
END:VALARM
DTSTART:20180817T230500Z
DTEND:20180818T020500Z
UID:ylL-QIgM4DEzkHF4akhsG6dm@stanza.co
SUMMARY:Shorebirds vs. RiverDogs
DESCRIPTION:Shorebirds vs. RiverDogs\n\nFollow on MiLB First Pitch: https://stza.co/+wHRE-35\n\nShop: https://stza.co/+wHRE-3X\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144519Z
LAST-MODIFIED:20180213T144519Z
TRANSP:OPAQUE
END:VEVENT
* Shorebirds vs. Braves
<2018-08-18 Sat 18:05-21:05>
:PROPERTIES:
:ID:       fGjWPdF9a7jpxEfM9u6J5sQ3@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Shorebirds vs. Braves Shorebirds vs. Braves

Follow on MiLB First Pitch  https //stza.co/+wHRF-3T

Shop  https //stza.co/+wHRF-21

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Shorebirds vs. Braves
END:VALARM
DTSTART:20180818T230500Z
DTEND:20180819T020500Z
UID:fGjWPdF9a7jpxEfM9u6J5sQ3@stanza.co
SUMMARY:Shorebirds vs. Braves
DESCRIPTION:Shorebirds vs. Braves\n\nFollow on MiLB First Pitch: https://stza.co/+wHRF-3T\n\nShop: https://stza.co/+wHRF-21\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144519Z
LAST-MODIFIED:20180213T144519Z
TRANSP:OPAQUE
END:VEVENT
* Shorebirds vs. Braves
<2018-08-19 Sun 16:05-19:05>
:PROPERTIES:
:ID:       sZdU0B_ujKJv_koK8olMdKZk@stanza.co
:LOCATION: Kids run the bases for today's game. Bring out the family!
:STATUS:   CONFIRMED
:END:

Shorebirds vs. Braves Bring 2 canned food items to the Shorebirds box office and receive an upper reserved ticket for $3. All collected items will be donated to the local area food banks.

Kids 13 & under get to run the bases after the game, presented by Chili's Grill & Bar.

Follow on MiLB First Pitch  https //stza.co/+wHRI-35

Shop  https //stza.co/+wHRI-1H

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Shorebirds vs. Braves
END:VALARM
DTSTART:20180819T210500Z
DTEND:20180820T000500Z
UID:sZdU0B_ujKJv_koK8olMdKZk@stanza.co
SUMMARY:Shorebirds vs. Braves
DESCRIPTION:Bring 2 canned food items to the Shorebirds box office and receive an upper reserved ticket for $3. All collected items will be donated to the local area food banks.\n\nKids 13 & under get to run the bases after the game, presented by Chili's Grill & Bar.\n\nFollow on MiLB First Pitch: https://stza.co/+wHRI-35\n\nShop: https://stza.co/+wHRI-1H\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Kids run the bases for today's game. Bring out the family!
STATUS:CONFIRMED
CREATED:20180213T144519Z
LAST-MODIFIED:20180213T144519Z
TRANSP:OPAQUE
END:VEVENT
* Shorebirds vs. Braves
<2018-08-20 Mon 18:05-21:05>
:PROPERTIES:
:ID:       BMnxrxLpEIMyEQD1FEVnyxzy@stanza.co
:LOCATION: 47 ABC 2 Buck Monday
:STATUS:   CONFIRMED
:END:

Shorebirds vs. Braves Enjoy $2 Upper Reserved tickets, $2 hotdogs, and $2 fountain Pepsi products.

Follow on MiLB First Pitch  https //stza.co/+wHRK-j

Shop  https //stza.co/+wHRK-F

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Shorebirds vs. Braves
END:VALARM
DTSTART:20180820T230500Z
DTEND:20180821T020500Z
UID:BMnxrxLpEIMyEQD1FEVnyxzy@stanza.co
SUMMARY:Shorebirds vs. Braves
DESCRIPTION:Enjoy $2 Upper Reserved tickets, $2 hotdogs, and $2 fountain Pepsi products.\n\nFollow on MiLB First Pitch: https://stza.co/+wHRK-j\n\nShop: https://stza.co/+wHRK-F\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:47 ABC 2 Buck Monday
STATUS:CONFIRMED
CREATED:20180213T144519Z
LAST-MODIFIED:20180213T144519Z
TRANSP:OPAQUE
END:VEVENT
* Shorebirds vs. Braves
<2018-08-21 Tue 18:05-21:05>
:PROPERTIES:
:ID:       AH_PxwcS4oFYE2COu7x1fRUI@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Shorebirds vs. Braves Shorebirds vs. Braves

Follow on MiLB First Pitch  https //stza.co/+wHRN-1Z

Shop  https //stza.co/+wHRN-2s

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Shorebirds vs. Braves
END:VALARM
DTSTART:20180821T230500Z
DTEND:20180822T020500Z
UID:AH_PxwcS4oFYE2COu7x1fRUI@stanza.co
SUMMARY:Shorebirds vs. Braves
DESCRIPTION:Shorebirds vs. Braves\n\nFollow on MiLB First Pitch: https://stza.co/+wHRN-1Z\n\nShop: https://stza.co/+wHRN-2s\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144519Z
LAST-MODIFIED:20180213T144519Z
TRANSP:OPAQUE
END:VEVENT
* Shorebirds @ Grasshoppers
<2018-08-23 Thu 18:00-21:00>
:PROPERTIES:
:ID:       Xtl2AAGpXPoNHAMmLo-2Ai6C@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Shorebirds @ Grasshoppers Shorebirds @ Grasshoppers

Follow on MiLB First Pitch  https //stza.co/+wiwQ-2u

Shop  https //stza.co/+wiwQ-33

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Shorebirds @ Grasshoppers
END:VALARM
DTSTART:20180823T230000Z
DTEND:20180824T020000Z
UID:Xtl2AAGpXPoNHAMmLo-2Ai6C@stanza.co
SUMMARY:Shorebirds @ Grasshoppers
DESCRIPTION:Shorebirds @ Grasshoppers\n\nFollow on MiLB First Pitch: https://stza.co/+wiwQ-2u\n\nShop: https://stza.co/+wiwQ-33\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144519Z
LAST-MODIFIED:20180213T144519Z
TRANSP:OPAQUE
END:VEVENT
* Shorebirds @ Grasshoppers
<2018-08-24 Fri 18:00-21:00>
:PROPERTIES:
:ID:       9FR7N0e5Fp_ZaXY2JIbyJYLT@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Shorebirds @ Grasshoppers Shorebirds @ Grasshoppers

Follow on MiLB First Pitch  https //stza.co/+wiwR-$

Shop  https //stza.co/+wiwR-1F

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Shorebirds @ Grasshoppers
END:VALARM
DTSTART:20180824T230000Z
DTEND:20180825T020000Z
UID:9FR7N0e5Fp_ZaXY2JIbyJYLT@stanza.co
SUMMARY:Shorebirds @ Grasshoppers
DESCRIPTION:Shorebirds @ Grasshoppers\n\nFollow on MiLB First Pitch: https://stza.co/+wiwR-$\n\nShop: https://stza.co/+wiwR-1F\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144519Z
LAST-MODIFIED:20180213T144519Z
TRANSP:OPAQUE
END:VEVENT
* Shorebirds @ Grasshoppers
<2018-08-25 Sat 18:00-21:00>
:PROPERTIES:
:ID:       3viLNZeOY7MnfJfKIW7OPSH5@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Shorebirds @ Grasshoppers Shorebirds @ Grasshoppers

Follow on MiLB First Pitch  https //stza.co/+wiwS-8

Shop  https //stza.co/+wiwS-2S

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Shorebirds @ Grasshoppers
END:VALARM
DTSTART:20180825T230000Z
DTEND:20180826T020000Z
UID:3viLNZeOY7MnfJfKIW7OPSH5@stanza.co
SUMMARY:Shorebirds @ Grasshoppers
DESCRIPTION:Shorebirds @ Grasshoppers\n\nFollow on MiLB First Pitch: https://stza.co/+wiwS-8\n\nShop: https://stza.co/+wiwS-2S\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144519Z
LAST-MODIFIED:20180213T144519Z
TRANSP:OPAQUE
END:VEVENT
* Shorebirds @ Grasshoppers
<2018-08-26 Sun 15:00-18:00>
:PROPERTIES:
:ID:       nMky4_ts0rYgtf9yGfNzcJB4@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Shorebirds @ Grasshoppers Shorebirds @ Grasshoppers

Follow on MiLB First Pitch  https //stza.co/+wiwT-3V

Shop  https //stza.co/+wiwT-2g

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Shorebirds @ Grasshoppers
END:VALARM
DTSTART:20180826T200000Z
DTEND:20180826T230000Z
UID:nMky4_ts0rYgtf9yGfNzcJB4@stanza.co
SUMMARY:Shorebirds @ Grasshoppers
DESCRIPTION:Shorebirds @ Grasshoppers\n\nFollow on MiLB First Pitch: https://stza.co/+wiwT-3V\n\nShop: https://stza.co/+wiwT-2g\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144519Z
LAST-MODIFIED:20180213T144519Z
TRANSP:OPAQUE
END:VEVENT
* Shorebirds vs. Crawdads
<2018-08-27 Mon 18:05-21:05>
:PROPERTIES:
:ID:       5YHFhjhnz26jZMqJNiUab1gj@stanza.co
:LOCATION: 47 ABC 2 Buck Monday
:STATUS:   CONFIRMED
:END:

Shorebirds vs. Crawdads Enjoy $2 Upper Reserved tickets, $2 hotdogs, and $2 fountain Pepsi products.

Follow on MiLB First Pitch  https //stza.co/+wHRQ-2G

Shop  https //stza.co/+wHRQ-W

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Shorebirds vs. Crawdads
END:VALARM
DTSTART:20180827T230500Z
DTEND:20180828T020500Z
UID:5YHFhjhnz26jZMqJNiUab1gj@stanza.co
SUMMARY:Shorebirds vs. Crawdads
DESCRIPTION:Enjoy $2 Upper Reserved tickets, $2 hotdogs, and $2 fountain Pepsi products.\n\nFollow on MiLB First Pitch: https://stza.co/+wHRQ-2G\n\nShop: https://stza.co/+wHRQ-W\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:47 ABC 2 Buck Monday
STATUS:CONFIRMED
CREATED:20180213T144519Z
LAST-MODIFIED:20180213T144519Z
TRANSP:OPAQUE
END:VEVENT
* Shorebirds vs. Crawdads
<2018-08-28 Tue 18:05-21:05>
:PROPERTIES:
:ID:       zNq0pWZbd8c41CMtwMvznouG@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Shorebirds vs. Crawdads Shorebirds vs. Crawdads

Follow on MiLB First Pitch  https //stza.co/+wHL1-1a

Shop  https //stza.co/+wHL1-1k

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Shorebirds vs. Crawdads
END:VALARM
DTSTART:20180828T230500Z
DTEND:20180829T020500Z
UID:zNq0pWZbd8c41CMtwMvznouG@stanza.co
SUMMARY:Shorebirds vs. Crawdads
DESCRIPTION:Shorebirds vs. Crawdads\n\nFollow on MiLB First Pitch: https://stza.co/+wHL1-1a\n\nShop: https://stza.co/+wHL1-1k\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144519Z
LAST-MODIFIED:20180213T144519Z
TRANSP:OPAQUE
END:VEVENT
* Shorebirds vs. Crawdads
<2018-08-29 Wed 18:05-21:05>
:PROPERTIES:
:ID:       ORYNIgdGA0Z_hRgh1VzjaP7S@stanza.co
:LOCATION: Silver Slugger Game
:STATUS:   CONFIRMED
:END:

Shorebirds vs. Crawdads This game is included in the Silver Sluggers membership for fans 55 and up.

Follow on MiLB First Pitch  https //stza.co/+wHL4-1R

Shop  https //stza.co/+wHL4-3h

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Shorebirds vs. Crawdads
END:VALARM
DTSTART:20180829T230500Z
DTEND:20180830T020500Z
UID:ORYNIgdGA0Z_hRgh1VzjaP7S@stanza.co
SUMMARY:Shorebirds vs. Crawdads
DESCRIPTION:This game is included in the Silver Sluggers membership for fans 55 and up.\n\nFollow on MiLB First Pitch: https://stza.co/+wHL4-1R\n\nShop: https://stza.co/+wHL4-3h\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Silver Slugger Game
STATUS:CONFIRMED
CREATED:20180213T144519Z
LAST-MODIFIED:20180213T144519Z
TRANSP:OPAQUE
END:VEVENT
* Shorebirds vs. Crawdads
<2018-08-30 Thu 18:05-21:05>
:PROPERTIES:
:ID:       CvIX_wPhyh9coRjkRNlATsz_@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Shorebirds vs. Crawdads Shorebirds vs. Crawdads

Follow on MiLB First Pitch  https //stza.co/+wHLa-2_

Shop  https //stza.co/+wHLa-1d

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Shorebirds vs. Crawdads
END:VALARM
DTSTART:20180830T230500Z
DTEND:20180831T020500Z
UID:CvIX_wPhyh9coRjkRNlATsz_@stanza.co
SUMMARY:Shorebirds vs. Crawdads
DESCRIPTION:Shorebirds vs. Crawdads\n\nFollow on MiLB First Pitch: https://stza.co/+wHLa-2_\n\nShop: https://stza.co/+wHLa-1d\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144519Z
LAST-MODIFIED:20180213T144519Z
TRANSP:OPAQUE
END:VEVENT
* Shorebirds @ BlueClaws
<2018-08-31 Fri 18:05-21:05>
:PROPERTIES:
:ID:       koC1rVnCl53QIMZGMdyRz9SR@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Shorebirds @ BlueClaws Shorebirds @ BlueClaws

Follow on MiLB First Pitch  https //stza.co/+vNII-1Q

Shop  https //stza.co/+vNII-F

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Shorebirds @ BlueClaws
END:VALARM
DTSTART:20180831T230500Z
DTEND:20180901T020500Z
UID:koC1rVnCl53QIMZGMdyRz9SR@stanza.co
SUMMARY:Shorebirds @ BlueClaws
DESCRIPTION:Shorebirds @ BlueClaws\n\nFollow on MiLB First Pitch: https://stza.co/+vNII-1Q\n\nShop: https://stza.co/+vNII-F\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144519Z
LAST-MODIFIED:20180213T144519Z
TRANSP:OPAQUE
END:VEVENT
* Shorebirds @ BlueClaws
<2018-09-01 Sat 18:05-21:05>
:PROPERTIES:
:ID:       JzAPr5TEC9dbIxGmFg68H8dV@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Shorebirds @ BlueClaws Shorebirds @ BlueClaws

Follow on MiLB First Pitch  https //stza.co/+vNIJ-3v

Shop  https //stza.co/+vNIJ-2F

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Shorebirds @ BlueClaws
END:VALARM
DTSTART:20180901T230500Z
DTEND:20180902T020500Z
UID:JzAPr5TEC9dbIxGmFg68H8dV@stanza.co
SUMMARY:Shorebirds @ BlueClaws
DESCRIPTION:Shorebirds @ BlueClaws\n\nFollow on MiLB First Pitch: https://stza.co/+vNIJ-3v\n\nShop: https://stza.co/+vNIJ-2F\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144519Z
LAST-MODIFIED:20180213T144519Z
TRANSP:OPAQUE
END:VEVENT
* Shorebirds @ BlueClaws
<2018-09-02 Sun 18:05-21:05>
:PROPERTIES:
:ID:       UYSUd2YraQ0VYOjSSMt63l-n@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Shorebirds @ BlueClaws Shorebirds @ BlueClaws

Follow on MiLB First Pitch  https //stza.co/+vNIK-2G

Shop  https //stza.co/+vNIK-2U

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Shorebirds @ BlueClaws
END:VALARM
DTSTART:20180902T230500Z
DTEND:20180903T020500Z
UID:UYSUd2YraQ0VYOjSSMt63l-n@stanza.co
SUMMARY:Shorebirds @ BlueClaws
DESCRIPTION:Shorebirds @ BlueClaws\n\nFollow on MiLB First Pitch: https://stza.co/+vNIK-2G\n\nShop: https://stza.co/+vNIK-2U\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144519Z
LAST-MODIFIED:20180213T144519Z
TRANSP:OPAQUE
END:VEVENT
* Shorebirds @ BlueClaws
<2018-09-03 Mon 12:05-15:05>
:PROPERTIES:
:ID:       uECRm5ADdegXtuySV762jzSt@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Shorebirds @ BlueClaws Shorebirds @ BlueClaws

Follow on MiLB First Pitch  https //stza.co/+vNIL-3h

Shop  https //stza.co/+vNIL-3s

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Shorebirds @ BlueClaws
END:VALARM
DTSTART:20180903T170500Z
DTEND:20180903T200500Z
UID:uECRm5ADdegXtuySV762jzSt@stanza.co
SUMMARY:Shorebirds @ BlueClaws
DESCRIPTION:Shorebirds @ BlueClaws\n\nFollow on MiLB First Pitch: https://stza.co/+vNIL-3h\n\nShop: https://stza.co/+vNIL-3s\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144519Z
LAST-MODIFIED:20180213T144519Z
TRANSP:OPAQUE
END:VEVENT
