#+TITLE:       Main Google calendar entries
#+AUTHOR:      Eric S Fraga
#+EMAIL:       e.fraga@ucl.ac.uk
#+DESCRIPTION: converted using the ical2org awk script
#+CATEGORY:    google
#+STARTUP:     hidestars
#+STARTUP:     overview

* COMMENT original iCal preamble

* Lookouts vs. Barons
<2018-04-05 Thu 17:15-20:15>
:PROPERTIES:
:ID:       IGRk_Bmj720b1iLU_i5eZD47@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Lookouts vs. Barons Lookouts vs. Barons

Follow on MiLB First Pitch  https //stza.co/+wKCk-1L

Shop  https //stza.co/+wKCk-3j

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Lookouts vs. Barons
END:VALARM
DTSTART:20180405T221500Z
DTEND:20180406T011500Z
UID:IGRk_Bmj720b1iLU_i5eZD47@stanza.co
SUMMARY:Lookouts vs. Barons
DESCRIPTION:Lookouts vs. Barons\n\nFollow on MiLB First Pitch: https://stza.co/+wKCk-1L\n\nShop: https://stza.co/+wKCk-3j\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144513Z
LAST-MODIFIED:20180213T144513Z
TRANSP:OPAQUE
END:VEVENT
* Lookouts vs. Barons
<2018-04-06 Fri 18:15-21:15>
:PROPERTIES:
:ID:       m8167DgKKHQhAOlRROGXUxTd@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Lookouts vs. Barons Lookouts vs. Barons

Follow on MiLB First Pitch  https //stza.co/+wKCn-

Shop  https //stza.co/+wKCn-2l

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Lookouts vs. Barons
END:VALARM
DTSTART:20180406T231500Z
DTEND:20180407T021500Z
UID:m8167DgKKHQhAOlRROGXUxTd@stanza.co
SUMMARY:Lookouts vs. Barons
DESCRIPTION:Lookouts vs. Barons\n\nFollow on MiLB First Pitch: https://stza.co/+wKCn-\n\nShop: https://stza.co/+wKCn-2l\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144513Z
LAST-MODIFIED:20180213T144513Z
TRANSP:OPAQUE
END:VEVENT
* Lookouts vs. Barons
<2018-04-07 Sat 18:15-21:15>
:PROPERTIES:
:ID:       Vfmcj-9T-c2g-i2uWVyZkUbV@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Lookouts vs. Barons Lookouts vs. Barons

Follow on MiLB First Pitch  https //stza.co/+wKCq-P

Shop  https //stza.co/+wKCq-33

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Lookouts vs. Barons
END:VALARM
DTSTART:20180407T231500Z
DTEND:20180408T021500Z
UID:Vfmcj-9T-c2g-i2uWVyZkUbV@stanza.co
SUMMARY:Lookouts vs. Barons
DESCRIPTION:Lookouts vs. Barons\n\nFollow on MiLB First Pitch: https://stza.co/+wKCq-P\n\nShop: https://stza.co/+wKCq-33\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144513Z
LAST-MODIFIED:20180213T144513Z
TRANSP:OPAQUE
END:VEVENT
* Lookouts vs. Barons
<2018-04-08 Sun 13:15-16:15>
:PROPERTIES:
:ID:       D9QGLXNuWCdYRV43UOmcLGjB@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Lookouts vs. Barons Lookouts vs. Barons

Follow on MiLB First Pitch  https //stza.co/+wKCs-1X

Shop  https //stza.co/+wKCs-1S

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Lookouts vs. Barons
END:VALARM
DTSTART:20180408T181500Z
DTEND:20180408T211500Z
UID:D9QGLXNuWCdYRV43UOmcLGjB@stanza.co
SUMMARY:Lookouts vs. Barons
DESCRIPTION:Lookouts vs. Barons\n\nFollow on MiLB First Pitch: https://stza.co/+wKCs-1X\n\nShop: https://stza.co/+wKCs-1S\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144513Z
LAST-MODIFIED:20180213T144513Z
TRANSP:OPAQUE
END:VEVENT
* Lookouts vs. Barons
<2018-04-09 Mon 18:15-21:15>
:PROPERTIES:
:ID:       T1pu-mmwEsWjiliG7JZEXOyW@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Lookouts vs. Barons Lookouts vs. Barons

Follow on MiLB First Pitch  https //stza.co/+wKCu-j

Shop  https //stza.co/+wKCu-4

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Lookouts vs. Barons
END:VALARM
DTSTART:20180409T231500Z
DTEND:20180410T021500Z
UID:T1pu-mmwEsWjiliG7JZEXOyW@stanza.co
SUMMARY:Lookouts vs. Barons
DESCRIPTION:Lookouts vs. Barons\n\nFollow on MiLB First Pitch: https://stza.co/+wKCu-j\n\nShop: https://stza.co/+wKCu-4\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144513Z
LAST-MODIFIED:20180213T144513Z
TRANSP:OPAQUE
END:VEVENT
* Lookouts @ Blue Wahoos
<2018-04-11 Wed 18:35-21:35>
:PROPERTIES:
:ID:       CymRFola7dlMnwhK4Wr29yEF@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Lookouts @ Blue Wahoos Lookouts @ Blue Wahoos

Follow on MiLB First Pitch  https //stza.co/+wx7m-2d

Shop  https //stza.co/+wx7m-2_

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Lookouts @ Blue Wahoos
END:VALARM
DTSTART:20180411T233500Z
DTEND:20180412T023500Z
UID:CymRFola7dlMnwhK4Wr29yEF@stanza.co
SUMMARY:Lookouts @ Blue Wahoos
DESCRIPTION:Lookouts @ Blue Wahoos\n\nFollow on MiLB First Pitch: https://stza.co/+wx7m-2d\n\nShop: https://stza.co/+wx7m-2_\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144513Z
LAST-MODIFIED:20180213T144513Z
TRANSP:OPAQUE
END:VEVENT
* Lookouts @ Blue Wahoos
<2018-04-12 Thu 18:35-21:35>
:PROPERTIES:
:ID:       1yR4ISP-CwExi6_btXG3xGRh@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Lookouts @ Blue Wahoos Lookouts @ Blue Wahoos

Follow on MiLB First Pitch  https //stza.co/+wx7n-2g

Shop  https //stza.co/+wx7n-2j

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Lookouts @ Blue Wahoos
END:VALARM
DTSTART:20180412T233500Z
DTEND:20180413T023500Z
UID:1yR4ISP-CwExi6_btXG3xGRh@stanza.co
SUMMARY:Lookouts @ Blue Wahoos
DESCRIPTION:Lookouts @ Blue Wahoos\n\nFollow on MiLB First Pitch: https://stza.co/+wx7n-2g\n\nShop: https://stza.co/+wx7n-2j\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144513Z
LAST-MODIFIED:20180213T144513Z
TRANSP:OPAQUE
END:VEVENT
* Lookouts @ Blue Wahoos
<2018-04-13 Fri 18:35-21:35>
:PROPERTIES:
:ID:       xfRDcimA8QlIqEALRl2kDu0S@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Lookouts @ Blue Wahoos Lookouts @ Blue Wahoos

Follow on MiLB First Pitch  https //stza.co/+wx7o-$

Shop  https //stza.co/+wx7o-A

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Lookouts @ Blue Wahoos
END:VALARM
DTSTART:20180413T233500Z
DTEND:20180414T023500Z
UID:xfRDcimA8QlIqEALRl2kDu0S@stanza.co
SUMMARY:Lookouts @ Blue Wahoos
DESCRIPTION:Lookouts @ Blue Wahoos\n\nFollow on MiLB First Pitch: https://stza.co/+wx7o-$\n\nShop: https://stza.co/+wx7o-A\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144513Z
LAST-MODIFIED:20180213T144513Z
TRANSP:OPAQUE
END:VEVENT
* Lookouts @ Blue Wahoos
<2018-04-14 Sat 18:05-21:05>
:PROPERTIES:
:ID:       _vqyjk1I22jxwAKG_4qVSjmH@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Lookouts @ Blue Wahoos Lookouts @ Blue Wahoos

Follow on MiLB First Pitch  https //stza.co/+wx7p-1F

Shop  https //stza.co/+wx7p-h

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Lookouts @ Blue Wahoos
END:VALARM
DTSTART:20180414T230500Z
DTEND:20180415T020500Z
UID:_vqyjk1I22jxwAKG_4qVSjmH@stanza.co
SUMMARY:Lookouts @ Blue Wahoos
DESCRIPTION:Lookouts @ Blue Wahoos\n\nFollow on MiLB First Pitch: https://stza.co/+wx7p-1F\n\nShop: https://stza.co/+wx7p-h\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144513Z
LAST-MODIFIED:20180213T144513Z
TRANSP:OPAQUE
END:VEVENT
* Lookouts @ Blue Wahoos
<2018-04-15 Sun 13:05-16:05>
:PROPERTIES:
:ID:       BM1rjNoGv1JXJScb22WPLuaK@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Lookouts @ Blue Wahoos Lookouts @ Blue Wahoos

Follow on MiLB First Pitch  https //stza.co/+wx7q-U

Shop  https //stza.co/+wx7q-17

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Lookouts @ Blue Wahoos
END:VALARM
DTSTART:20180415T180500Z
DTEND:20180415T210500Z
UID:BM1rjNoGv1JXJScb22WPLuaK@stanza.co
SUMMARY:Lookouts @ Blue Wahoos
DESCRIPTION:Lookouts @ Blue Wahoos\n\nFollow on MiLB First Pitch: https://stza.co/+wx7q-U\n\nShop: https://stza.co/+wx7q-17\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144513Z
LAST-MODIFIED:20180213T144513Z
TRANSP:OPAQUE
END:VEVENT
* Lookouts vs. Jumbo Shrimp
<2018-04-16 Mon 18:15-21:15>
:PROPERTIES:
:ID:       V55b1YCDND_nB7XB_QZh0jOo@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Lookouts vs. Jumbo Shrimp Lookouts vs. Jumbo Shrimp

Follow on MiLB First Pitch  https //stza.co/+wKCv-N

Shop  https //stza.co/+wKCv-1v

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Lookouts vs. Jumbo Shrimp
END:VALARM
DTSTART:20180416T231500Z
DTEND:20180417T021500Z
UID:V55b1YCDND_nB7XB_QZh0jOo@stanza.co
SUMMARY:Lookouts vs. Jumbo Shrimp
DESCRIPTION:Lookouts vs. Jumbo Shrimp\n\nFollow on MiLB First Pitch: https://stza.co/+wKCv-N\n\nShop: https://stza.co/+wKCv-1v\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144513Z
LAST-MODIFIED:20180213T144513Z
TRANSP:OPAQUE
END:VEVENT
* Lookouts vs. Jumbo Shrimp
<2018-04-17 Tue 18:15-21:15>
:PROPERTIES:
:ID:       T78xEzAKETPM-K9rpBF-_Mrx@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Lookouts vs. Jumbo Shrimp Lookouts vs. Jumbo Shrimp

Follow on MiLB First Pitch  https //stza.co/+wKCx-1L

Shop  https //stza.co/+wKCx-$

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Lookouts vs. Jumbo Shrimp
END:VALARM
DTSTART:20180417T231500Z
DTEND:20180418T021500Z
UID:T78xEzAKETPM-K9rpBF-_Mrx@stanza.co
SUMMARY:Lookouts vs. Jumbo Shrimp
DESCRIPTION:Lookouts vs. Jumbo Shrimp\n\nFollow on MiLB First Pitch: https://stza.co/+wKCx-1L\n\nShop: https://stza.co/+wKCx-$\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144513Z
LAST-MODIFIED:20180213T144513Z
TRANSP:OPAQUE
END:VEVENT
* Lookouts vs. Jumbo Shrimp
<2018-04-18 Wed 18:15-21:15>
:PROPERTIES:
:ID:       si_e1I6-ZINax_HplCOpHB5B@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Lookouts vs. Jumbo Shrimp Lookouts vs. Jumbo Shrimp

Follow on MiLB First Pitch  https //stza.co/+wKCA-7

Shop  https //stza.co/+wKCA-2I

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Lookouts vs. Jumbo Shrimp
END:VALARM
DTSTART:20180418T231500Z
DTEND:20180419T021500Z
UID:si_e1I6-ZINax_HplCOpHB5B@stanza.co
SUMMARY:Lookouts vs. Jumbo Shrimp
DESCRIPTION:Lookouts vs. Jumbo Shrimp\n\nFollow on MiLB First Pitch: https://stza.co/+wKCA-7\n\nShop: https://stza.co/+wKCA-2I\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144513Z
LAST-MODIFIED:20180213T144513Z
TRANSP:OPAQUE
END:VEVENT
* Lookouts vs. Jumbo Shrimp
<2018-04-19 Thu 18:15-21:15>
:PROPERTIES:
:ID:       b91IoheIRYnONn51urguRc6r@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Lookouts vs. Jumbo Shrimp Lookouts vs. Jumbo Shrimp

Follow on MiLB First Pitch  https //stza.co/+wKCC-2L

Shop  https //stza.co/+wKCC-2r

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Lookouts vs. Jumbo Shrimp
END:VALARM
DTSTART:20180419T231500Z
DTEND:20180420T021500Z
UID:b91IoheIRYnONn51urguRc6r@stanza.co
SUMMARY:Lookouts vs. Jumbo Shrimp
DESCRIPTION:Lookouts vs. Jumbo Shrimp\n\nFollow on MiLB First Pitch: https://stza.co/+wKCC-2L\n\nShop: https://stza.co/+wKCC-2r\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144513Z
LAST-MODIFIED:20180213T144513Z
TRANSP:OPAQUE
END:VEVENT
* Lookouts vs. Jumbo Shrimp
<2018-04-20 Fri 18:15-21:15>
:PROPERTIES:
:ID:       TI2RI_F7xGjCX_3Pa2K1oWv-@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Lookouts vs. Jumbo Shrimp Lookouts vs. Jumbo Shrimp

Follow on MiLB First Pitch  https //stza.co/+wKCE-3i

Shop  https //stza.co/+wKCE-2e

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Lookouts vs. Jumbo Shrimp
END:VALARM
DTSTART:20180420T231500Z
DTEND:20180421T021500Z
UID:TI2RI_F7xGjCX_3Pa2K1oWv-@stanza.co
SUMMARY:Lookouts vs. Jumbo Shrimp
DESCRIPTION:Lookouts vs. Jumbo Shrimp\n\nFollow on MiLB First Pitch: https://stza.co/+wKCE-3i\n\nShop: https://stza.co/+wKCE-2e\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144513Z
LAST-MODIFIED:20180213T144513Z
TRANSP:OPAQUE
END:VEVENT
* Lookouts @ Generals
<2018-04-21 Sat 18:05-21:05>
:PROPERTIES:
:ID:       uP5OLd1AVLB_hqvYH6zesECM@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Lookouts @ Generals Lookouts @ Generals

Follow on MiLB First Pitch  https //stza.co/+wCNu-1x

Shop  https //stza.co/+wCNu-2E

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Lookouts @ Generals
END:VALARM
DTSTART:20180421T230500Z
DTEND:20180422T020500Z
UID:uP5OLd1AVLB_hqvYH6zesECM@stanza.co
SUMMARY:Lookouts @ Generals
DESCRIPTION:Lookouts @ Generals\n\nFollow on MiLB First Pitch: https://stza.co/+wCNu-1x\n\nShop: https://stza.co/+wCNu-2E\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144513Z
LAST-MODIFIED:20180213T144513Z
TRANSP:OPAQUE
END:VEVENT
* Lookouts @ Generals
<2018-04-22 Sun 14:05-17:05>
:PROPERTIES:
:ID:       pBgRq7Pe6Y1xVX4AQ5iCmh0U@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Lookouts @ Generals Lookouts @ Generals

Follow on MiLB First Pitch  https //stza.co/+wCNv-2T

Shop  https //stza.co/+wCNv-2

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Lookouts @ Generals
END:VALARM
DTSTART:20180422T190500Z
DTEND:20180422T220500Z
UID:pBgRq7Pe6Y1xVX4AQ5iCmh0U@stanza.co
SUMMARY:Lookouts @ Generals
DESCRIPTION:Lookouts @ Generals\n\nFollow on MiLB First Pitch: https://stza.co/+wCNv-2T\n\nShop: https://stza.co/+wCNv-2\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144513Z
LAST-MODIFIED:20180213T144513Z
TRANSP:OPAQUE
END:VEVENT
* Lookouts @ Generals
<2018-04-23 Mon 18:05-21:05>
:PROPERTIES:
:ID:       NcW-aVV5POPG1zjpt7QiKG4X@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Lookouts @ Generals Lookouts @ Generals

Follow on MiLB First Pitch  https //stza.co/+wCNw-1r

Shop  https //stza.co/+wCNw-2

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Lookouts @ Generals
END:VALARM
DTSTART:20180423T230500Z
DTEND:20180424T020500Z
UID:NcW-aVV5POPG1zjpt7QiKG4X@stanza.co
SUMMARY:Lookouts @ Generals
DESCRIPTION:Lookouts @ Generals\n\nFollow on MiLB First Pitch: https://stza.co/+wCNw-1r\n\nShop: https://stza.co/+wCNw-2\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144513Z
LAST-MODIFIED:20180213T144513Z
TRANSP:OPAQUE
END:VEVENT
* Lookouts @ Generals
<2018-04-24 Tue 18:05-21:05>
:PROPERTIES:
:ID:       LknyYGKs_IydRVDpm7Qv2Ak2@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Lookouts @ Generals Lookouts @ Generals

Follow on MiLB First Pitch  https //stza.co/+wCNx-A

Shop  https //stza.co/+wCNx-2F

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Lookouts @ Generals
END:VALARM
DTSTART:20180424T230500Z
DTEND:20180425T020500Z
UID:LknyYGKs_IydRVDpm7Qv2Ak2@stanza.co
SUMMARY:Lookouts @ Generals
DESCRIPTION:Lookouts @ Generals\n\nFollow on MiLB First Pitch: https://stza.co/+wCNx-A\n\nShop: https://stza.co/+wCNx-2F\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144513Z
LAST-MODIFIED:20180213T144513Z
TRANSP:OPAQUE
END:VEVENT
* Lookouts @ Generals
<2018-04-25 Wed 11:05-14:05>
:PROPERTIES:
:ID:       FEjZ2NvCNGQVZgdmBYgikEkT@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Lookouts @ Generals Lookouts @ Generals

Follow on MiLB First Pitch  https //stza.co/+wCNz-3H

Shop  https //stza.co/+wCNz-2P

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Lookouts @ Generals
END:VALARM
DTSTART:20180425T160500Z
DTEND:20180425T190500Z
UID:FEjZ2NvCNGQVZgdmBYgikEkT@stanza.co
SUMMARY:Lookouts @ Generals
DESCRIPTION:Lookouts @ Generals\n\nFollow on MiLB First Pitch: https://stza.co/+wCNz-3H\n\nShop: https://stza.co/+wCNz-2P\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144513Z
LAST-MODIFIED:20180213T144513Z
TRANSP:OPAQUE
END:VEVENT
* Lookouts vs. Smokies
<2018-04-26 Thu 18:15-21:15>
:PROPERTIES:
:ID:       IX_z5IEz69RkRb-KKwuskByp@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Lookouts vs. Smokies Lookouts vs. Smokies

Follow on MiLB First Pitch  https //stza.co/+wKCG-9

Shop  https //stza.co/+wKCG-L

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Lookouts vs. Smokies
END:VALARM
DTSTART:20180426T231500Z
DTEND:20180427T021500Z
UID:IX_z5IEz69RkRb-KKwuskByp@stanza.co
SUMMARY:Lookouts vs. Smokies
DESCRIPTION:Lookouts vs. Smokies\n\nFollow on MiLB First Pitch: https://stza.co/+wKCG-9\n\nShop: https://stza.co/+wKCG-L\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144513Z
LAST-MODIFIED:20180213T144513Z
TRANSP:OPAQUE
END:VEVENT
* Lookouts vs. Smokies
<2018-04-27 Fri 18:15-21:15>
:PROPERTIES:
:ID:       IlHJrVffyF6rEh9s4pFP7ufR@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Lookouts vs. Smokies Lookouts vs. Smokies

Follow on MiLB First Pitch  https //stza.co/+wKCI-11

Shop  https //stza.co/+wKCI-31

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Lookouts vs. Smokies
END:VALARM
DTSTART:20180427T231500Z
DTEND:20180428T021500Z
UID:IlHJrVffyF6rEh9s4pFP7ufR@stanza.co
SUMMARY:Lookouts vs. Smokies
DESCRIPTION:Lookouts vs. Smokies\n\nFollow on MiLB First Pitch: https://stza.co/+wKCI-11\n\nShop: https://stza.co/+wKCI-31\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144513Z
LAST-MODIFIED:20180213T144513Z
TRANSP:OPAQUE
END:VEVENT
* Lookouts vs. Smokies
<2018-04-28 Sat 18:15-21:15>
:PROPERTIES:
:ID:       7cFkU0MYjUQjds8CbyRoITxX@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Lookouts vs. Smokies Lookouts vs. Smokies

Follow on MiLB First Pitch  https //stza.co/+wKCK-C

Shop  https //stza.co/+wKCK-E

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Lookouts vs. Smokies
END:VALARM
DTSTART:20180428T231500Z
DTEND:20180429T021500Z
UID:7cFkU0MYjUQjds8CbyRoITxX@stanza.co
SUMMARY:Lookouts vs. Smokies
DESCRIPTION:Lookouts vs. Smokies\n\nFollow on MiLB First Pitch: https://stza.co/+wKCK-C\n\nShop: https://stza.co/+wKCK-E\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144513Z
LAST-MODIFIED:20180213T144513Z
TRANSP:OPAQUE
END:VEVENT
* Lookouts vs. Smokies
<2018-04-29 Sun 13:15-16:15>
:PROPERTIES:
:ID:       FcqCxe--HMn7roQ--dWeduGL@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Lookouts vs. Smokies Lookouts vs. Smokies

Follow on MiLB First Pitch  https //stza.co/+wKCL-2M

Shop  https //stza.co/+wKCL-26

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Lookouts vs. Smokies
END:VALARM
DTSTART:20180429T181500Z
DTEND:20180429T211500Z
UID:FcqCxe--HMn7roQ--dWeduGL@stanza.co
SUMMARY:Lookouts vs. Smokies
DESCRIPTION:Lookouts vs. Smokies\n\nFollow on MiLB First Pitch: https://stza.co/+wKCL-2M\n\nShop: https://stza.co/+wKCL-26\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144513Z
LAST-MODIFIED:20180213T144513Z
TRANSP:OPAQUE
END:VEVENT
* Lookouts vs. Smokies
<2018-04-30 Mon 10:15-13:15>
:PROPERTIES:
:ID:       Ab7scbuIAL4OPmrtvSaTE92g@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Lookouts vs. Smokies Lookouts vs. Smokies

Follow on MiLB First Pitch  https //stza.co/+wKCO-D

Shop  https //stza.co/+wKCO-1P

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Lookouts vs. Smokies
END:VALARM
DTSTART:20180430T151500Z
DTEND:20180430T181500Z
UID:Ab7scbuIAL4OPmrtvSaTE92g@stanza.co
SUMMARY:Lookouts vs. Smokies
DESCRIPTION:Lookouts vs. Smokies\n\nFollow on MiLB First Pitch: https://stza.co/+wKCO-D\n\nShop: https://stza.co/+wKCO-1P\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144513Z
LAST-MODIFIED:20180213T144513Z
TRANSP:OPAQUE
END:VEVENT
* Lookouts @ BayBears
<2018-05-02 Wed 18:35-21:35>
:PROPERTIES:
:ID:       4xzeRofRvtoIouDY1sQFj-S_@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Lookouts @ BayBears Lookouts @ BayBears

Follow on MiLB First Pitch  https //stza.co/+v$Pz-29

Shop  https //stza.co/+v$Pz-2d

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Lookouts @ BayBears
END:VALARM
DTSTART:20180502T233500Z
DTEND:20180503T023500Z
UID:4xzeRofRvtoIouDY1sQFj-S_@stanza.co
SUMMARY:Lookouts @ BayBears
DESCRIPTION:Lookouts @ BayBears\n\nFollow on MiLB First Pitch: https://stza.co/+v$Pz-29\n\nShop: https://stza.co/+v$Pz-2d\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144513Z
LAST-MODIFIED:20180213T144513Z
TRANSP:OPAQUE
END:VEVENT
* Lookouts @ BayBears
<2018-05-03 Thu 18:35-21:35>
:PROPERTIES:
:ID:       vbeQPEU2Srfgx1fl1S21MuA1@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Lookouts @ BayBears Lookouts @ BayBears

Follow on MiLB First Pitch  https //stza.co/+v$PA-13

Shop  https //stza.co/+v$PA-1h

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Lookouts @ BayBears
END:VALARM
DTSTART:20180503T233500Z
DTEND:20180504T023500Z
UID:vbeQPEU2Srfgx1fl1S21MuA1@stanza.co
SUMMARY:Lookouts @ BayBears
DESCRIPTION:Lookouts @ BayBears\n\nFollow on MiLB First Pitch: https://stza.co/+v$PA-13\n\nShop: https://stza.co/+v$PA-1h\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144513Z
LAST-MODIFIED:20180213T144513Z
TRANSP:OPAQUE
END:VEVENT
* Lookouts @ BayBears
<2018-05-04 Fri 19:05-22:05>
:PROPERTIES:
:ID:       3EQc2Wq793W_FPRcqLPF3XD3@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Lookouts @ BayBears Lookouts @ BayBears

Follow on MiLB First Pitch  https //stza.co/+v$PB-3K

Shop  https //stza.co/+v$PB-2z

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Lookouts @ BayBears
END:VALARM
DTSTART:20180505T000500Z
DTEND:20180505T030500Z
UID:3EQc2Wq793W_FPRcqLPF3XD3@stanza.co
SUMMARY:Lookouts @ BayBears
DESCRIPTION:Lookouts @ BayBears\n\nFollow on MiLB First Pitch: https://stza.co/+v$PB-3K\n\nShop: https://stza.co/+v$PB-2z\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144513Z
LAST-MODIFIED:20180213T144513Z
TRANSP:OPAQUE
END:VEVENT
* Lookouts @ BayBears
<2018-05-05 Sat 19:05-22:05>
:PROPERTIES:
:ID:       2-EuOpk53q5HLEmVoRoO0pCt@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Lookouts @ BayBears Lookouts @ BayBears

Follow on MiLB First Pitch  https //stza.co/+v$PC-p

Shop  https //stza.co/+v$PC-2$

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Lookouts @ BayBears
END:VALARM
DTSTART:20180506T000500Z
DTEND:20180506T030500Z
UID:2-EuOpk53q5HLEmVoRoO0pCt@stanza.co
SUMMARY:Lookouts @ BayBears
DESCRIPTION:Lookouts @ BayBears\n\nFollow on MiLB First Pitch: https://stza.co/+v$PC-p\n\nShop: https://stza.co/+v$PC-2$\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144513Z
LAST-MODIFIED:20180213T144513Z
TRANSP:OPAQUE
END:VEVENT
* Lookouts @ BayBears
<2018-05-06 Sun 14:05-17:05>
:PROPERTIES:
:ID:       kthihX_iNa9g9mdSz1b8_pzk@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Lookouts @ BayBears Lookouts @ BayBears

Follow on MiLB First Pitch  https //stza.co/+v$PD-1H

Shop  https //stza.co/+v$PD-2L

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Lookouts @ BayBears
END:VALARM
DTSTART:20180506T190500Z
DTEND:20180506T220500Z
UID:kthihX_iNa9g9mdSz1b8_pzk@stanza.co
SUMMARY:Lookouts @ BayBears
DESCRIPTION:Lookouts @ BayBears\n\nFollow on MiLB First Pitch: https://stza.co/+v$PD-1H\n\nShop: https://stza.co/+v$PD-2L\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144513Z
LAST-MODIFIED:20180213T144513Z
TRANSP:OPAQUE
END:VEVENT
* Lookouts vs. Generals
<2018-05-07 Mon 18:15-21:15>
:PROPERTIES:
:ID:       ZdGOn7CzmioKXDiy7UJryjNA@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Lookouts vs. Generals Lookouts vs. Generals

Follow on MiLB First Pitch  https //stza.co/+wKCQ-3_

Shop  https //stza.co/+wKCQ-H

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Lookouts vs. Generals
END:VALARM
DTSTART:20180507T231500Z
DTEND:20180508T021500Z
UID:ZdGOn7CzmioKXDiy7UJryjNA@stanza.co
SUMMARY:Lookouts vs. Generals
DESCRIPTION:Lookouts vs. Generals\n\nFollow on MiLB First Pitch: https://stza.co/+wKCQ-3_\n\nShop: https://stza.co/+wKCQ-H\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144513Z
LAST-MODIFIED:20180213T144513Z
TRANSP:OPAQUE
END:VEVENT
* Lookouts vs. Generals
<2018-05-08 Tue 18:15-21:15>
:PROPERTIES:
:ID:       rTWrrdp5TWEzrrzp03bxVhXO@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Lookouts vs. Generals Lookouts vs. Generals

Follow on MiLB First Pitch  https //stza.co/+wKCS-U

Shop  https //stza.co/+wKCS-A

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Lookouts vs. Generals
END:VALARM
DTSTART:20180508T231500Z
DTEND:20180509T021500Z
UID:rTWrrdp5TWEzrrzp03bxVhXO@stanza.co
SUMMARY:Lookouts vs. Generals
DESCRIPTION:Lookouts vs. Generals\n\nFollow on MiLB First Pitch: https://stza.co/+wKCS-U\n\nShop: https://stza.co/+wKCS-A\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144513Z
LAST-MODIFIED:20180213T144513Z
TRANSP:OPAQUE
END:VEVENT
* Lookouts vs. Generals
<2018-05-09 Wed 18:15-21:15>
:PROPERTIES:
:ID:       mngDnf9kcNP_OmACPFCE-KLO@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Lookouts vs. Generals Lookouts vs. Generals

Follow on MiLB First Pitch  https //stza.co/+wKCV-y

Shop  https //stza.co/+wKCV-1d

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Lookouts vs. Generals
END:VALARM
DTSTART:20180509T231500Z
DTEND:20180510T021500Z
UID:mngDnf9kcNP_OmACPFCE-KLO@stanza.co
SUMMARY:Lookouts vs. Generals
DESCRIPTION:Lookouts vs. Generals\n\nFollow on MiLB First Pitch: https://stza.co/+wKCV-y\n\nShop: https://stza.co/+wKCV-1d\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144513Z
LAST-MODIFIED:20180213T144513Z
TRANSP:OPAQUE
END:VEVENT
* Lookouts vs. Generals
<2018-05-10 Thu 18:15-21:15>
:PROPERTIES:
:ID:       XGkw4rDwN0x1kQaF8v07hQiJ@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Lookouts vs. Generals Lookouts vs. Generals

Follow on MiLB First Pitch  https //stza.co/+wKCW-3M

Shop  https //stza.co/+wKCW-2g

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Lookouts vs. Generals
END:VALARM
DTSTART:20180510T231500Z
DTEND:20180511T021500Z
UID:XGkw4rDwN0x1kQaF8v07hQiJ@stanza.co
SUMMARY:Lookouts vs. Generals
DESCRIPTION:Lookouts vs. Generals\n\nFollow on MiLB First Pitch: https://stza.co/+wKCW-3M\n\nShop: https://stza.co/+wKCW-2g\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144513Z
LAST-MODIFIED:20180213T144513Z
TRANSP:OPAQUE
END:VEVENT
* Lookouts vs. Generals
<2018-05-11 Fri 18:15-21:15>
:PROPERTIES:
:ID:       Wolz2gs0rQr8G1uHHRev51HG@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Lookouts vs. Generals Lookouts vs. Generals

Follow on MiLB First Pitch  https //stza.co/+wKCZ-2b

Shop  https //stza.co/+wKCZ-2h

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Lookouts vs. Generals
END:VALARM
DTSTART:20180511T231500Z
DTEND:20180512T021500Z
UID:Wolz2gs0rQr8G1uHHRev51HG@stanza.co
SUMMARY:Lookouts vs. Generals
DESCRIPTION:Lookouts vs. Generals\n\nFollow on MiLB First Pitch: https://stza.co/+wKCZ-2b\n\nShop: https://stza.co/+wKCZ-2h\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144513Z
LAST-MODIFIED:20180213T144513Z
TRANSP:OPAQUE
END:VEVENT
* Lookouts vs. Smokies
<2018-05-12 Sat 18:15-21:15>
:PROPERTIES:
:ID:       DbV1B32_aXAVFlUjnkCXRJw_@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Lookouts vs. Smokies Lookouts vs. Smokies

Follow on MiLB First Pitch  https //stza.co/+wKC$-3H

Shop  https //stza.co/+wKC$-29

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Lookouts vs. Smokies
END:VALARM
DTSTART:20180512T231500Z
DTEND:20180513T021500Z
UID:DbV1B32_aXAVFlUjnkCXRJw_@stanza.co
SUMMARY:Lookouts vs. Smokies
DESCRIPTION:Lookouts vs. Smokies\n\nFollow on MiLB First Pitch: https://stza.co/+wKC$-3H\n\nShop: https://stza.co/+wKC$-29\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144513Z
LAST-MODIFIED:20180213T144513Z
TRANSP:OPAQUE
END:VEVENT
* Lookouts vs. Smokies
<2018-05-13 Sun 13:15-16:15>
:PROPERTIES:
:ID:       ybKcpGeQcChrzaYQaZcMzpE6@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Lookouts vs. Smokies Lookouts vs. Smokies

Follow on MiLB First Pitch  https //stza.co/+wKD1-Y

Shop  https //stza.co/+wKD1-3V

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Lookouts vs. Smokies
END:VALARM
DTSTART:20180513T181500Z
DTEND:20180513T211500Z
UID:ybKcpGeQcChrzaYQaZcMzpE6@stanza.co
SUMMARY:Lookouts vs. Smokies
DESCRIPTION:Lookouts vs. Smokies\n\nFollow on MiLB First Pitch: https://stza.co/+wKD1-Y\n\nShop: https://stza.co/+wKD1-3V\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144513Z
LAST-MODIFIED:20180213T144513Z
TRANSP:OPAQUE
END:VEVENT
* Lookouts vs. Smokies
<2018-05-14 Mon 18:15-21:15>
:PROPERTIES:
:ID:       Eo1TNlP5RvJwLZCPb7uv8mQt@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Lookouts vs. Smokies Lookouts vs. Smokies

Follow on MiLB First Pitch  https //stza.co/+wKD2-2l

Shop  https //stza.co/+wKD2-39

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Lookouts vs. Smokies
END:VALARM
DTSTART:20180514T231500Z
DTEND:20180515T021500Z
UID:Eo1TNlP5RvJwLZCPb7uv8mQt@stanza.co
SUMMARY:Lookouts vs. Smokies
DESCRIPTION:Lookouts vs. Smokies\n\nFollow on MiLB First Pitch: https://stza.co/+wKD2-2l\n\nShop: https://stza.co/+wKD2-39\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144513Z
LAST-MODIFIED:20180213T144513Z
TRANSP:OPAQUE
END:VEVENT
* Lookouts vs. Smokies
<2018-05-15 Tue 18:15-21:15>
:PROPERTIES:
:ID:       7bkO30EJpg6szReHRKC0BUth@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Lookouts vs. Smokies Lookouts vs. Smokies

Follow on MiLB First Pitch  https //stza.co/+wKD5-q

Shop  https //stza.co/+wKD5-2Q

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Lookouts vs. Smokies
END:VALARM
DTSTART:20180515T231500Z
DTEND:20180516T021500Z
UID:7bkO30EJpg6szReHRKC0BUth@stanza.co
SUMMARY:Lookouts vs. Smokies
DESCRIPTION:Lookouts vs. Smokies\n\nFollow on MiLB First Pitch: https://stza.co/+wKD5-q\n\nShop: https://stza.co/+wKD5-2Q\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144513Z
LAST-MODIFIED:20180213T144513Z
TRANSP:OPAQUE
END:VEVENT
* Lookouts vs. Smokies
<2018-05-16 Wed 10:15-13:15>
:PROPERTIES:
:ID:       wAnkB9kMEtVy8CUiBow_pbKL@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Lookouts vs. Smokies Lookouts vs. Smokies

Follow on MiLB First Pitch  https //stza.co/+wKD6-2m

Shop  https //stza.co/+wKD6-2s

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Lookouts vs. Smokies
END:VALARM
DTSTART:20180516T151500Z
DTEND:20180516T181500Z
UID:wAnkB9kMEtVy8CUiBow_pbKL@stanza.co
SUMMARY:Lookouts vs. Smokies
DESCRIPTION:Lookouts vs. Smokies\n\nFollow on MiLB First Pitch: https://stza.co/+wKD6-2m\n\nShop: https://stza.co/+wKD6-2s\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144513Z
LAST-MODIFIED:20180213T144513Z
TRANSP:OPAQUE
END:VEVENT
* Lookouts @ Shuckers
<2018-05-17 Thu 18:35-21:35>
:PROPERTIES:
:ID:       Q-4XDgCYtuvCfR_8K6eJM-89@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Lookouts @ Shuckers Lookouts @ Shuckers

Follow on MiLB First Pitch  https //stza.co/+vLB$-1U

Shop  https //stza.co/+vLB$-n

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Lookouts @ Shuckers
END:VALARM
DTSTART:20180517T233500Z
DTEND:20180518T023500Z
UID:Q-4XDgCYtuvCfR_8K6eJM-89@stanza.co
SUMMARY:Lookouts @ Shuckers
DESCRIPTION:Lookouts @ Shuckers\n\nFollow on MiLB First Pitch: https://stza.co/+vLB$-1U\n\nShop: https://stza.co/+vLB$-n\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144513Z
LAST-MODIFIED:20180213T144513Z
TRANSP:OPAQUE
END:VEVENT
* Lookouts @ Shuckers
<2018-05-18 Fri 18:35-21:35>
:PROPERTIES:
:ID:       4dCK_UEjCh0iaq8PS8DUTA2W@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Lookouts @ Shuckers Lookouts @ Shuckers

Follow on MiLB First Pitch  https //stza.co/+vLC0-3s

Shop  https //stza.co/+vLC0-3X

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Lookouts @ Shuckers
END:VALARM
DTSTART:20180518T233500Z
DTEND:20180519T023500Z
UID:4dCK_UEjCh0iaq8PS8DUTA2W@stanza.co
SUMMARY:Lookouts @ Shuckers
DESCRIPTION:Lookouts @ Shuckers\n\nFollow on MiLB First Pitch: https://stza.co/+vLC0-3s\n\nShop: https://stza.co/+vLC0-3X\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144513Z
LAST-MODIFIED:20180213T144513Z
TRANSP:OPAQUE
END:VEVENT
* Lookouts @ Shuckers
<2018-05-19 Sat 18:35-21:35>
:PROPERTIES:
:ID:       ht-KPWAJ6tiF4_ErgIpwtU1o@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Lookouts @ Shuckers Lookouts @ Shuckers

Follow on MiLB First Pitch  https //stza.co/+vLC1-d

Shop  https //stza.co/+vLC1-3L

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Lookouts @ Shuckers
END:VALARM
DTSTART:20180519T233500Z
DTEND:20180520T023500Z
UID:ht-KPWAJ6tiF4_ErgIpwtU1o@stanza.co
SUMMARY:Lookouts @ Shuckers
DESCRIPTION:Lookouts @ Shuckers\n\nFollow on MiLB First Pitch: https://stza.co/+vLC1-d\n\nShop: https://stza.co/+vLC1-3L\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144513Z
LAST-MODIFIED:20180213T144513Z
TRANSP:OPAQUE
END:VEVENT
* Lookouts @ Shuckers
<2018-05-20 Sun 14:05-17:05>
:PROPERTIES:
:ID:       mePevtZ23FpDmX8ZABk5jZxw@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Lookouts @ Shuckers Lookouts @ Shuckers

Follow on MiLB First Pitch  https //stza.co/+vLC2-E

Shop  https //stza.co/+vLC2-1Z

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Lookouts @ Shuckers
END:VALARM
DTSTART:20180520T190500Z
DTEND:20180520T220500Z
UID:mePevtZ23FpDmX8ZABk5jZxw@stanza.co
SUMMARY:Lookouts @ Shuckers
DESCRIPTION:Lookouts @ Shuckers\n\nFollow on MiLB First Pitch: https://stza.co/+vLC2-E\n\nShop: https://stza.co/+vLC2-1Z\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144513Z
LAST-MODIFIED:20180213T144513Z
TRANSP:OPAQUE
END:VEVENT
* Lookouts @ Shuckers
<2018-05-21 Mon 18:35-21:35>
:PROPERTIES:
:ID:       3KvQ-kdtTs8OZLey_e92IQcx@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Lookouts @ Shuckers Lookouts @ Shuckers

Follow on MiLB First Pitch  https //stza.co/+vLC3-2b

Shop  https //stza.co/+vLC3-3D

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Lookouts @ Shuckers
END:VALARM
DTSTART:20180521T233500Z
DTEND:20180522T023500Z
UID:3KvQ-kdtTs8OZLey_e92IQcx@stanza.co
SUMMARY:Lookouts @ Shuckers
DESCRIPTION:Lookouts @ Shuckers\n\nFollow on MiLB First Pitch: https://stza.co/+vLC3-2b\n\nShop: https://stza.co/+vLC3-3D\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144513Z
LAST-MODIFIED:20180213T144513Z
TRANSP:OPAQUE
END:VEVENT
* Lookouts vs. Biscuits
<2018-05-23 Wed 18:15-21:15>
:PROPERTIES:
:ID:       6a71kLCU2LikT8TzWPHHL0TG@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Lookouts vs. Biscuits Lookouts vs. Biscuits

Follow on MiLB First Pitch  https //stza.co/+wKD8-2_

Shop  https //stza.co/+wKD8-I

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Lookouts vs. Biscuits
END:VALARM
DTSTART:20180523T231500Z
DTEND:20180524T021500Z
UID:6a71kLCU2LikT8TzWPHHL0TG@stanza.co
SUMMARY:Lookouts vs. Biscuits
DESCRIPTION:Lookouts vs. Biscuits\n\nFollow on MiLB First Pitch: https://stza.co/+wKD8-2_\n\nShop: https://stza.co/+wKD8-I\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144513Z
LAST-MODIFIED:20180213T144513Z
TRANSP:OPAQUE
END:VEVENT
* Lookouts vs. Biscuits
<2018-05-24 Thu 18:15-21:15>
:PROPERTIES:
:ID:       cjKXG0PB3tF7NInz9lyxdU_k@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Lookouts vs. Biscuits Lookouts vs. Biscuits

Follow on MiLB First Pitch  https //stza.co/+wKDb-e

Shop  https //stza.co/+wKDb-k

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Lookouts vs. Biscuits
END:VALARM
DTSTART:20180524T231500Z
DTEND:20180525T021500Z
UID:cjKXG0PB3tF7NInz9lyxdU_k@stanza.co
SUMMARY:Lookouts vs. Biscuits
DESCRIPTION:Lookouts vs. Biscuits\n\nFollow on MiLB First Pitch: https://stza.co/+wKDb-e\n\nShop: https://stza.co/+wKDb-k\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144513Z
LAST-MODIFIED:20180213T144513Z
TRANSP:OPAQUE
END:VEVENT
* Lookouts vs. Biscuits
<2018-05-25 Fri 18:15-21:15>
:PROPERTIES:
:ID:       H8sA-FcwZp9-KK0e3eskKBDZ@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Lookouts vs. Biscuits Lookouts vs. Biscuits

Follow on MiLB First Pitch  https //stza.co/+wKDd-2W

Shop  https //stza.co/+wKDd-3t

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Lookouts vs. Biscuits
END:VALARM
DTSTART:20180525T231500Z
DTEND:20180526T021500Z
UID:H8sA-FcwZp9-KK0e3eskKBDZ@stanza.co
SUMMARY:Lookouts vs. Biscuits
DESCRIPTION:Lookouts vs. Biscuits\n\nFollow on MiLB First Pitch: https://stza.co/+wKDd-2W\n\nShop: https://stza.co/+wKDd-3t\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144513Z
LAST-MODIFIED:20180213T144513Z
TRANSP:OPAQUE
END:VEVENT
* Lookouts vs. Biscuits
<2018-05-26 Sat 18:15-21:15>
:PROPERTIES:
:ID:       wLpci0e3FDyVvWOmpuzPBRu-@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Lookouts vs. Biscuits Lookouts vs. Biscuits

Follow on MiLB First Pitch  https //stza.co/+wKDg-3F

Shop  https //stza.co/+wKDg-1p

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Lookouts vs. Biscuits
END:VALARM
DTSTART:20180526T231500Z
DTEND:20180527T021500Z
UID:wLpci0e3FDyVvWOmpuzPBRu-@stanza.co
SUMMARY:Lookouts vs. Biscuits
DESCRIPTION:Lookouts vs. Biscuits\n\nFollow on MiLB First Pitch: https://stza.co/+wKDg-3F\n\nShop: https://stza.co/+wKDg-1p\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144513Z
LAST-MODIFIED:20180213T144513Z
TRANSP:OPAQUE
END:VEVENT
* Lookouts vs. Biscuits
<2018-05-27 Sun 17:15-20:15>
:PROPERTIES:
:ID:       vi1KnUNa_K1lirOm63kn2H8m@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Lookouts vs. Biscuits Lookouts vs. Biscuits

Follow on MiLB First Pitch  https //stza.co/+wKDi-34

Shop  https //stza.co/+wKDi-1q

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Lookouts vs. Biscuits
END:VALARM
DTSTART:20180527T221500Z
DTEND:20180528T011500Z
UID:vi1KnUNa_K1lirOm63kn2H8m@stanza.co
SUMMARY:Lookouts vs. Biscuits
DESCRIPTION:Lookouts vs. Biscuits\n\nFollow on MiLB First Pitch: https://stza.co/+wKDi-34\n\nShop: https://stza.co/+wKDi-1q\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144513Z
LAST-MODIFIED:20180213T144513Z
TRANSP:OPAQUE
END:VEVENT
* Lookouts @ Barons
<2018-05-29 Tue 19:05-22:05>
:PROPERTIES:
:ID:       H1xVjAY5ztXOMlQZufHGNQ2H@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Lookouts @ Barons Lookouts @ Barons

Follow on MiLB First Pitch  https //stza.co/+wFX9-3I

Shop  https //stza.co/+wFX9-3j

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Lookouts @ Barons
END:VALARM
DTSTART:20180530T000500Z
DTEND:20180530T030500Z
UID:H1xVjAY5ztXOMlQZufHGNQ2H@stanza.co
SUMMARY:Lookouts @ Barons
DESCRIPTION:Lookouts @ Barons\n\nFollow on MiLB First Pitch: https://stza.co/+wFX9-3I\n\nShop: https://stza.co/+wFX9-3j\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144513Z
LAST-MODIFIED:20180213T144513Z
TRANSP:OPAQUE
END:VEVENT
* Lookouts @ Barons
<2018-05-30 Wed 12:30-15:30>
:PROPERTIES:
:ID:       yrYkxRMr0AydxB9aPAjAhvy0@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Lookouts @ Barons Lookouts @ Barons

Follow on MiLB First Pitch  https //stza.co/+wFXa-P

Shop  https //stza.co/+wFXa-

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Lookouts @ Barons
END:VALARM
DTSTART:20180530T173000Z
DTEND:20180530T203000Z
UID:yrYkxRMr0AydxB9aPAjAhvy0@stanza.co
SUMMARY:Lookouts @ Barons
DESCRIPTION:Lookouts @ Barons\n\nFollow on MiLB First Pitch: https://stza.co/+wFXa-P\n\nShop: https://stza.co/+wFXa-\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144513Z
LAST-MODIFIED:20180213T144513Z
TRANSP:OPAQUE
END:VEVENT
* Lookouts @ Barons
<2018-05-31 Thu 19:05-22:05>
:PROPERTIES:
:ID:       _YBBdpWhnxf5pwuV3wRDXCoC@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Lookouts @ Barons Lookouts @ Barons

Follow on MiLB First Pitch  https //stza.co/+wFXb-23

Shop  https //stza.co/+wFXb-1U

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Lookouts @ Barons
END:VALARM
DTSTART:20180601T000500Z
DTEND:20180601T030500Z
UID:_YBBdpWhnxf5pwuV3wRDXCoC@stanza.co
SUMMARY:Lookouts @ Barons
DESCRIPTION:Lookouts @ Barons\n\nFollow on MiLB First Pitch: https://stza.co/+wFXb-23\n\nShop: https://stza.co/+wFXb-1U\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144513Z
LAST-MODIFIED:20180213T144513Z
TRANSP:OPAQUE
END:VEVENT
* Lookouts @ Barons
<2018-06-01 Fri 19:05-22:05>
:PROPERTIES:
:ID:       gY8rQU5S_8T0GWBFSornkAtm@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Lookouts @ Barons Lookouts @ Barons

Follow on MiLB First Pitch  https //stza.co/+wFXc-t

Shop  https //stza.co/+wFXc-2j

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Lookouts @ Barons
END:VALARM
DTSTART:20180602T000500Z
DTEND:20180602T030500Z
UID:gY8rQU5S_8T0GWBFSornkAtm@stanza.co
SUMMARY:Lookouts @ Barons
DESCRIPTION:Lookouts @ Barons\n\nFollow on MiLB First Pitch: https://stza.co/+wFXc-t\n\nShop: https://stza.co/+wFXc-2j\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144513Z
LAST-MODIFIED:20180213T144513Z
TRANSP:OPAQUE
END:VEVENT
* Lookouts @ Barons
<2018-06-02 Sat 18:30-21:30>
:PROPERTIES:
:ID:       Q6_NiQJaDgXJpGAqk3_Ol4rF@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Lookouts @ Barons Lookouts @ Barons

Follow on MiLB First Pitch  https //stza.co/+wFXd-P

Shop  https //stza.co/+wFXd-2J

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Lookouts @ Barons
END:VALARM
DTSTART:20180602T233000Z
DTEND:20180603T023000Z
UID:Q6_NiQJaDgXJpGAqk3_Ol4rF@stanza.co
SUMMARY:Lookouts @ Barons
DESCRIPTION:Lookouts @ Barons\n\nFollow on MiLB First Pitch: https://stza.co/+wFXd-P\n\nShop: https://stza.co/+wFXd-2J\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144513Z
LAST-MODIFIED:20180213T144513Z
TRANSP:OPAQUE
END:VEVENT
* Lookouts vs. BayBears
<2018-06-03 Sun 16:15-19:15>
:PROPERTIES:
:ID:       HcjuS8nwG3JUNFVx_DqEJ4Zq@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Lookouts vs. BayBears Lookouts vs. BayBears

Follow on MiLB First Pitch  https //stza.co/+wKDj-2Y

Shop  https //stza.co/+wKDj-1N

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Lookouts vs. BayBears
END:VALARM
DTSTART:20180603T211500Z
DTEND:20180604T001500Z
UID:HcjuS8nwG3JUNFVx_DqEJ4Zq@stanza.co
SUMMARY:Lookouts vs. BayBears
DESCRIPTION:Lookouts vs. BayBears\n\nFollow on MiLB First Pitch: https://stza.co/+wKDj-2Y\n\nShop: https://stza.co/+wKDj-1N\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144513Z
LAST-MODIFIED:20180213T144513Z
TRANSP:OPAQUE
END:VEVENT
* Lookouts vs. BayBears
<2018-06-04 Mon 18:15-21:15>
:PROPERTIES:
:ID:       LocbV9TIb8GVTOfZcOlSJzvp@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Lookouts vs. BayBears Lookouts vs. BayBears

Follow on MiLB First Pitch  https //stza.co/+wKDm-q

Shop  https //stza.co/+wKDm-3q

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Lookouts vs. BayBears
END:VALARM
DTSTART:20180604T231500Z
DTEND:20180605T021500Z
UID:LocbV9TIb8GVTOfZcOlSJzvp@stanza.co
SUMMARY:Lookouts vs. BayBears
DESCRIPTION:Lookouts vs. BayBears\n\nFollow on MiLB First Pitch: https://stza.co/+wKDm-q\n\nShop: https://stza.co/+wKDm-3q\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144513Z
LAST-MODIFIED:20180213T144513Z
TRANSP:OPAQUE
END:VEVENT
* Lookouts vs. BayBears
<2018-06-05 Tue 18:15-21:15>
:PROPERTIES:
:ID:       5K2XV8qgscdrOrhW-OKpex_5@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Lookouts vs. BayBears Lookouts vs. BayBears

Follow on MiLB First Pitch  https //stza.co/+wKDn-3

Shop  https //stza.co/+wKDn-1z

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Lookouts vs. BayBears
END:VALARM
DTSTART:20180605T231500Z
DTEND:20180606T021500Z
UID:5K2XV8qgscdrOrhW-OKpex_5@stanza.co
SUMMARY:Lookouts vs. BayBears
DESCRIPTION:Lookouts vs. BayBears\n\nFollow on MiLB First Pitch: https://stza.co/+wKDn-3\n\nShop: https://stza.co/+wKDn-1z\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144513Z
LAST-MODIFIED:20180213T144513Z
TRANSP:OPAQUE
END:VEVENT
* Lookouts vs. BayBears
<2018-06-06 Wed 10:15-13:15>
:PROPERTIES:
:ID:       MeuJnG35DMN0FixZYbC6axQ_@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Lookouts vs. BayBears Lookouts vs. BayBears

Follow on MiLB First Pitch  https //stza.co/+wKDq-a

Shop  https //stza.co/+wKDq-2I

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Lookouts vs. BayBears
END:VALARM
DTSTART:20180606T151500Z
DTEND:20180606T181500Z
UID:MeuJnG35DMN0FixZYbC6axQ_@stanza.co
SUMMARY:Lookouts vs. BayBears
DESCRIPTION:Lookouts vs. BayBears\n\nFollow on MiLB First Pitch: https://stza.co/+wKDq-a\n\nShop: https://stza.co/+wKDq-2I\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144513Z
LAST-MODIFIED:20180213T144513Z
TRANSP:OPAQUE
END:VEVENT
* Lookouts vs. BayBears
<2018-06-07 Thu 18:15-21:15>
:PROPERTIES:
:ID:       8fFIhLqqESNAsNlRQn7M6AVi@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Lookouts vs. BayBears Lookouts vs. BayBears

Follow on MiLB First Pitch  https //stza.co/+wKDt-1o

Shop  https //stza.co/+wKDt-R

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Lookouts vs. BayBears
END:VALARM
DTSTART:20180607T231500Z
DTEND:20180608T021500Z
UID:8fFIhLqqESNAsNlRQn7M6AVi@stanza.co
SUMMARY:Lookouts vs. BayBears
DESCRIPTION:Lookouts vs. BayBears\n\nFollow on MiLB First Pitch: https://stza.co/+wKDt-1o\n\nShop: https://stza.co/+wKDt-R\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144513Z
LAST-MODIFIED:20180213T144513Z
TRANSP:OPAQUE
END:VEVENT
* Lookouts @ Biscuits
<2018-06-08 Fri 18:35-21:35>
:PROPERTIES:
:ID:       lZ66huKQJasIql-Xhh0WmyoT@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Lookouts @ Biscuits Lookouts @ Biscuits

Follow on MiLB First Pitch  https //stza.co/+vLET-a

Shop  https //stza.co/+vLET-3x

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Lookouts @ Biscuits
END:VALARM
DTSTART:20180608T233500Z
DTEND:20180609T023500Z
UID:lZ66huKQJasIql-Xhh0WmyoT@stanza.co
SUMMARY:Lookouts @ Biscuits
DESCRIPTION:Lookouts @ Biscuits\n\nFollow on MiLB First Pitch: https://stza.co/+vLET-a\n\nShop: https://stza.co/+vLET-3x\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144513Z
LAST-MODIFIED:20180213T144513Z
TRANSP:OPAQUE
END:VEVENT
* Lookouts @ Biscuits
<2018-06-09 Sat 18:05-21:05>
:PROPERTIES:
:ID:       dHLGos1h_rmuh7pfhRuPbLLd@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Lookouts @ Biscuits Lookouts @ Biscuits

Follow on MiLB First Pitch  https //stza.co/+vLEU-2e

Shop  https //stza.co/+vLEU-3j

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Lookouts @ Biscuits
END:VALARM
DTSTART:20180609T230500Z
DTEND:20180610T020500Z
UID:dHLGos1h_rmuh7pfhRuPbLLd@stanza.co
SUMMARY:Lookouts @ Biscuits
DESCRIPTION:Lookouts @ Biscuits\n\nFollow on MiLB First Pitch: https://stza.co/+vLEU-2e\n\nShop: https://stza.co/+vLEU-3j\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144513Z
LAST-MODIFIED:20180213T144513Z
TRANSP:OPAQUE
END:VEVENT
* Lookouts @ Biscuits
<2018-06-10 Sun 17:05-20:05>
:PROPERTIES:
:ID:       7er_kmFlh8Xh7dirzYr0v4OQ@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Lookouts @ Biscuits Lookouts @ Biscuits

Follow on MiLB First Pitch  https //stza.co/+vLEV-B

Shop  https //stza.co/+vLEV-27

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Lookouts @ Biscuits
END:VALARM
DTSTART:20180610T220500Z
DTEND:20180611T010500Z
UID:7er_kmFlh8Xh7dirzYr0v4OQ@stanza.co
SUMMARY:Lookouts @ Biscuits
DESCRIPTION:Lookouts @ Biscuits\n\nFollow on MiLB First Pitch: https://stza.co/+vLEV-B\n\nShop: https://stza.co/+vLEV-27\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144513Z
LAST-MODIFIED:20180213T144513Z
TRANSP:OPAQUE
END:VEVENT
* Lookouts @ Biscuits
<2018-06-11 Mon 18:35-21:35>
:PROPERTIES:
:ID:       O2gTA5-mIzCiE-HkD2wOr_14@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Lookouts @ Biscuits Lookouts @ Biscuits

Follow on MiLB First Pitch  https //stza.co/+vLEW-3k

Shop  https //stza.co/+vLEW-3w

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Lookouts @ Biscuits
END:VALARM
DTSTART:20180611T233500Z
DTEND:20180612T023500Z
UID:O2gTA5-mIzCiE-HkD2wOr_14@stanza.co
SUMMARY:Lookouts @ Biscuits
DESCRIPTION:Lookouts @ Biscuits\n\nFollow on MiLB First Pitch: https://stza.co/+vLEW-3k\n\nShop: https://stza.co/+vLEW-3w\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144513Z
LAST-MODIFIED:20180213T144513Z
TRANSP:OPAQUE
END:VEVENT
* Lookouts @ Biscuits
<2018-06-12 Tue 12:05-15:05>
:PROPERTIES:
:ID:       QHaff7O9JVfd7fDyWkCUXHtd@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Lookouts @ Biscuits Lookouts @ Biscuits

Follow on MiLB First Pitch  https //stza.co/+vLEX-34

Shop  https //stza.co/+vLEX-1K

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Lookouts @ Biscuits
END:VALARM
DTSTART:20180612T170500Z
DTEND:20180612T200500Z
UID:QHaff7O9JVfd7fDyWkCUXHtd@stanza.co
SUMMARY:Lookouts @ Biscuits
DESCRIPTION:Lookouts @ Biscuits\n\nFollow on MiLB First Pitch: https://stza.co/+vLEX-34\n\nShop: https://stza.co/+vLEX-1K\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144513Z
LAST-MODIFIED:20180213T144513Z
TRANSP:OPAQUE
END:VEVENT
* Lookouts @ Barons
<2018-06-13 Wed 19:05-22:05>
:PROPERTIES:
:ID:       jwZy9gkgYPZdAcrtDxZCKj2B@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Lookouts @ Barons Lookouts @ Barons

Follow on MiLB First Pitch  https //stza.co/+wFXe-T

Shop  https //stza.co/+wFXe-2i

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Lookouts @ Barons
END:VALARM
DTSTART:20180614T000500Z
DTEND:20180614T030500Z
UID:jwZy9gkgYPZdAcrtDxZCKj2B@stanza.co
SUMMARY:Lookouts @ Barons
DESCRIPTION:Lookouts @ Barons\n\nFollow on MiLB First Pitch: https://stza.co/+wFXe-T\n\nShop: https://stza.co/+wFXe-2i\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144513Z
LAST-MODIFIED:20180213T144513Z
TRANSP:OPAQUE
END:VEVENT
* Lookouts @ Barons
<2018-06-14 Thu 19:05-22:05>
:PROPERTIES:
:ID:       c0AZ29GugsLT4K90JcQNdek-@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Lookouts @ Barons Lookouts @ Barons

Follow on MiLB First Pitch  https //stza.co/+wFXf-i

Shop  https //stza.co/+wFXf-2s

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Lookouts @ Barons
END:VALARM
DTSTART:20180615T000500Z
DTEND:20180615T030500Z
UID:c0AZ29GugsLT4K90JcQNdek-@stanza.co
SUMMARY:Lookouts @ Barons
DESCRIPTION:Lookouts @ Barons\n\nFollow on MiLB First Pitch: https://stza.co/+wFXf-i\n\nShop: https://stza.co/+wFXf-2s\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144513Z
LAST-MODIFIED:20180213T144513Z
TRANSP:OPAQUE
END:VEVENT
* Lookouts @ Barons
<2018-06-15 Fri 19:05-22:05>
:PROPERTIES:
:ID:       w3RkGyxOd9JKcpjgt3OttDM-@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Lookouts @ Barons Lookouts @ Barons

Follow on MiLB First Pitch  https //stza.co/+wFXg-3V

Shop  https //stza.co/+wFXg-23

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Lookouts @ Barons
END:VALARM
DTSTART:20180616T000500Z
DTEND:20180616T030500Z
UID:w3RkGyxOd9JKcpjgt3OttDM-@stanza.co
SUMMARY:Lookouts @ Barons
DESCRIPTION:Lookouts @ Barons\n\nFollow on MiLB First Pitch: https://stza.co/+wFXg-3V\n\nShop: https://stza.co/+wFXg-23\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144513Z
LAST-MODIFIED:20180213T144513Z
TRANSP:OPAQUE
END:VEVENT
* Lookouts @ Barons
<2018-06-16 Sat 18:30-21:30>
:PROPERTIES:
:ID:       IU8HpBfRuTZwdHAHu3i3TNpZ@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Lookouts @ Barons Lookouts @ Barons

Follow on MiLB First Pitch  https //stza.co/+wFXh-11

Shop  https //stza.co/+wFXh-1u

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Lookouts @ Barons
END:VALARM
DTSTART:20180616T233000Z
DTEND:20180617T023000Z
UID:IU8HpBfRuTZwdHAHu3i3TNpZ@stanza.co
SUMMARY:Lookouts @ Barons
DESCRIPTION:Lookouts @ Barons\n\nFollow on MiLB First Pitch: https://stza.co/+wFXh-11\n\nShop: https://stza.co/+wFXh-1u\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144513Z
LAST-MODIFIED:20180213T144513Z
TRANSP:OPAQUE
END:VEVENT
* Lookouts @ Barons
<2018-06-17 Sun 15:00-18:00>
:PROPERTIES:
:ID:       8jgglASqUMOvWdumh2YEMItj@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Lookouts @ Barons Lookouts @ Barons

Follow on MiLB First Pitch  https //stza.co/+xM60-3s

Shop  https //stza.co/+xM60-P

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Lookouts @ Barons
END:VALARM
DTSTART:20180617T200000Z
DTEND:20180617T230000Z
UID:8jgglASqUMOvWdumh2YEMItj@stanza.co
SUMMARY:Lookouts @ Barons
DESCRIPTION:Lookouts @ Barons\n\nFollow on MiLB First Pitch: https://stza.co/+xM60-3s\n\nShop: https://stza.co/+xM60-P\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144513Z
LAST-MODIFIED:20180213T144513Z
TRANSP:OPAQUE
END:VEVENT
* Lookouts vs. Shuckers
<2018-06-21 Thu 18:15-21:15>
:PROPERTIES:
:ID:       c1MQKeJpGwuyR6iFRdXhRKlK@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Lookouts vs. Shuckers Lookouts vs. Shuckers

Follow on MiLB First Pitch  https //stza.co/+wKDu-1j

Shop  https //stza.co/+wKDu-1q

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Lookouts vs. Shuckers
END:VALARM
DTSTART:20180621T231500Z
DTEND:20180622T021500Z
UID:c1MQKeJpGwuyR6iFRdXhRKlK@stanza.co
SUMMARY:Lookouts vs. Shuckers
DESCRIPTION:Lookouts vs. Shuckers\n\nFollow on MiLB First Pitch: https://stza.co/+wKDu-1j\n\nShop: https://stza.co/+wKDu-1q\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144513Z
LAST-MODIFIED:20180213T144513Z
TRANSP:OPAQUE
END:VEVENT
* Lookouts vs. Shuckers
<2018-06-22 Fri 18:15-21:15>
:PROPERTIES:
:ID:       11Vh0kNNdGl4orQ5fDSoRebW@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Lookouts vs. Shuckers Lookouts vs. Shuckers

Follow on MiLB First Pitch  https //stza.co/+wKDx-2w

Shop  https //stza.co/+wKDx-1F

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Lookouts vs. Shuckers
END:VALARM
DTSTART:20180622T231500Z
DTEND:20180623T021500Z
UID:11Vh0kNNdGl4orQ5fDSoRebW@stanza.co
SUMMARY:Lookouts vs. Shuckers
DESCRIPTION:Lookouts vs. Shuckers\n\nFollow on MiLB First Pitch: https://stza.co/+wKDx-2w\n\nShop: https://stza.co/+wKDx-1F\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144513Z
LAST-MODIFIED:20180213T144513Z
TRANSP:OPAQUE
END:VEVENT
* Lookouts vs. Shuckers
<2018-06-23 Sat 18:15-21:15>
:PROPERTIES:
:ID:       AbZKUpsCvtvZFJUNfaR2bkU4@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Lookouts vs. Shuckers Lookouts vs. Shuckers

Follow on MiLB First Pitch  https //stza.co/+wKDz-2D

Shop  https //stza.co/+wKDz-y

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Lookouts vs. Shuckers
END:VALARM
DTSTART:20180623T231500Z
DTEND:20180624T021500Z
UID:AbZKUpsCvtvZFJUNfaR2bkU4@stanza.co
SUMMARY:Lookouts vs. Shuckers
DESCRIPTION:Lookouts vs. Shuckers\n\nFollow on MiLB First Pitch: https://stza.co/+wKDz-2D\n\nShop: https://stza.co/+wKDz-y\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144513Z
LAST-MODIFIED:20180213T144513Z
TRANSP:OPAQUE
END:VEVENT
* Lookouts vs. Shuckers
<2018-06-24 Sun 13:15-16:15>
:PROPERTIES:
:ID:       WlDHYMd30y6Zs7QU8R36oLcw@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Lookouts vs. Shuckers Lookouts vs. Shuckers

Follow on MiLB First Pitch  https //stza.co/+wKDA-3y

Shop  https //stza.co/+wKDA-3Y

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Lookouts vs. Shuckers
END:VALARM
DTSTART:20180624T181500Z
DTEND:20180624T211500Z
UID:WlDHYMd30y6Zs7QU8R36oLcw@stanza.co
SUMMARY:Lookouts vs. Shuckers
DESCRIPTION:Lookouts vs. Shuckers\n\nFollow on MiLB First Pitch: https://stza.co/+wKDA-3y\n\nShop: https://stza.co/+wKDA-3Y\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144513Z
LAST-MODIFIED:20180213T144513Z
TRANSP:OPAQUE
END:VEVENT
* Lookouts vs. Shuckers
<2018-06-25 Mon 18:15-21:15>
:PROPERTIES:
:ID:       MKF8lkvSPvKVu4xxkiXOr18V@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Lookouts vs. Shuckers Lookouts vs. Shuckers

Follow on MiLB First Pitch  https //stza.co/+wKDC-T

Shop  https //stza.co/+wKDC-1n

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Lookouts vs. Shuckers
END:VALARM
DTSTART:20180625T231500Z
DTEND:20180626T021500Z
UID:MKF8lkvSPvKVu4xxkiXOr18V@stanza.co
SUMMARY:Lookouts vs. Shuckers
DESCRIPTION:Lookouts vs. Shuckers\n\nFollow on MiLB First Pitch: https://stza.co/+wKDC-T\n\nShop: https://stza.co/+wKDC-1n\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144513Z
LAST-MODIFIED:20180213T144513Z
TRANSP:OPAQUE
END:VEVENT
* Lookouts vs. Shuckers
<2018-06-26 Tue 10:15-13:15>
:PROPERTIES:
:ID:       _0pIAYhuB0A8PfHswo967mAm@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Lookouts vs. Shuckers Lookouts vs. Shuckers

Follow on MiLB First Pitch  https //stza.co/+wKDF-3r

Shop  https //stza.co/+wKDF-2M

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Lookouts vs. Shuckers
END:VALARM
DTSTART:20180626T151500Z
DTEND:20180626T181500Z
UID:_0pIAYhuB0A8PfHswo967mAm@stanza.co
SUMMARY:Lookouts vs. Shuckers
DESCRIPTION:Lookouts vs. Shuckers\n\nFollow on MiLB First Pitch: https://stza.co/+wKDF-3r\n\nShop: https://stza.co/+wKDF-2M\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144513Z
LAST-MODIFIED:20180213T144513Z
TRANSP:OPAQUE
END:VEVENT
* Lookouts @ Smokies
<2018-06-28 Thu 18:00-21:00>
:PROPERTIES:
:ID:       7bQC1Gre2-9J0Ez9pRjKCTp5@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Lookouts @ Smokies Lookouts @ Smokies

Follow on MiLB First Pitch  https //stza.co/+xVT3-n

Shop  https //stza.co/+xVT3-3x

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Lookouts @ Smokies
END:VALARM
DTSTART:20180628T230000Z
DTEND:20180629T020000Z
UID:7bQC1Gre2-9J0Ez9pRjKCTp5@stanza.co
SUMMARY:Lookouts @ Smokies
DESCRIPTION:Lookouts @ Smokies\n\nFollow on MiLB First Pitch: https://stza.co/+xVT3-n\n\nShop: https://stza.co/+xVT3-3x\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144513Z
LAST-MODIFIED:20180213T144513Z
TRANSP:OPAQUE
END:VEVENT
* Lookouts @ Smokies
<2018-06-29 Fri 18:00-21:00>
:PROPERTIES:
:ID:       c9uXoo8bilakP4kJCVMpDMiC@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Lookouts @ Smokies Lookouts @ Smokies

Follow on MiLB First Pitch  https //stza.co/+xVT5-13

Shop  https //stza.co/+xVT5-10

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Lookouts @ Smokies
END:VALARM
DTSTART:20180629T230000Z
DTEND:20180630T020000Z
UID:c9uXoo8bilakP4kJCVMpDMiC@stanza.co
SUMMARY:Lookouts @ Smokies
DESCRIPTION:Lookouts @ Smokies\n\nFollow on MiLB First Pitch: https://stza.co/+xVT5-13\n\nShop: https://stza.co/+xVT5-10\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144513Z
LAST-MODIFIED:20180213T144513Z
TRANSP:OPAQUE
END:VEVENT
* Lookouts @ Smokies
<2018-06-30 Sat 18:00-21:00>
:PROPERTIES:
:ID:       pFnzqVPDwHkDu9GiKV46a0eT@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Lookouts @ Smokies Lookouts @ Smokies

Follow on MiLB First Pitch  https //stza.co/+xVT6-28

Shop  https //stza.co/+xVT6-3W

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Lookouts @ Smokies
END:VALARM
DTSTART:20180630T230000Z
DTEND:20180701T020000Z
UID:pFnzqVPDwHkDu9GiKV46a0eT@stanza.co
SUMMARY:Lookouts @ Smokies
DESCRIPTION:Lookouts @ Smokies\n\nFollow on MiLB First Pitch: https://stza.co/+xVT6-28\n\nShop: https://stza.co/+xVT6-3W\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144513Z
LAST-MODIFIED:20180213T144513Z
TRANSP:OPAQUE
END:VEVENT
* Lookouts @ Smokies
<2018-07-01 Sun 17:30-20:30>
:PROPERTIES:
:ID:       bfJV22TSfkaQsWnDPukqdFfR@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Lookouts @ Smokies Lookouts @ Smokies

Follow on MiLB First Pitch  https //stza.co/+xVT7-16

Shop  https //stza.co/+xVT7-22

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Lookouts @ Smokies
END:VALARM
DTSTART:20180701T223000Z
DTEND:20180702T013000Z
UID:bfJV22TSfkaQsWnDPukqdFfR@stanza.co
SUMMARY:Lookouts @ Smokies
DESCRIPTION:Lookouts @ Smokies\n\nFollow on MiLB First Pitch: https://stza.co/+xVT7-16\n\nShop: https://stza.co/+xVT7-22\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144513Z
LAST-MODIFIED:20180213T144513Z
TRANSP:OPAQUE
END:VEVENT
* Lookouts @ Smokies
<2018-07-02 Mon 18:00-21:00>
:PROPERTIES:
:ID:       EHKuPYpohi52DBhvRkDNKwTt@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Lookouts @ Smokies Lookouts @ Smokies

Follow on MiLB First Pitch  https //stza.co/+xVT8-z

Shop  https //stza.co/+xVT8-3d

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Lookouts @ Smokies
END:VALARM
DTSTART:20180702T230000Z
DTEND:20180703T020000Z
UID:EHKuPYpohi52DBhvRkDNKwTt@stanza.co
SUMMARY:Lookouts @ Smokies
DESCRIPTION:Lookouts @ Smokies\n\nFollow on MiLB First Pitch: https://stza.co/+xVT8-z\n\nShop: https://stza.co/+xVT8-3d\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144513Z
LAST-MODIFIED:20180213T144513Z
TRANSP:OPAQUE
END:VEVENT
* Lookouts @ Smokies
<2018-07-03 Tue 18:00-21:00>
:PROPERTIES:
:ID:       sFP31pfvdtjoZ69q9r8pGQI4@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Lookouts @ Smokies Lookouts @ Smokies

Follow on MiLB First Pitch  https //stza.co/+xVT9-1s

Shop  https //stza.co/+xVT9-2D

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Lookouts @ Smokies
END:VALARM
DTSTART:20180703T230000Z
DTEND:20180704T020000Z
UID:sFP31pfvdtjoZ69q9r8pGQI4@stanza.co
SUMMARY:Lookouts @ Smokies
DESCRIPTION:Lookouts @ Smokies\n\nFollow on MiLB First Pitch: https://stza.co/+xVT9-1s\n\nShop: https://stza.co/+xVT9-2D\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144513Z
LAST-MODIFIED:20180213T144513Z
TRANSP:OPAQUE
END:VEVENT
* Lookouts vs. Barons
<2018-07-04 Wed 17:15-20:15>
:PROPERTIES:
:ID:       0cxtV_z2jvs3F1thleG7_NMv@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Lookouts vs. Barons Lookouts vs. Barons

Follow on MiLB First Pitch  https //stza.co/+wKDG-38

Shop  https //stza.co/+wKDG-2N

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Lookouts vs. Barons
END:VALARM
DTSTART:20180704T221500Z
DTEND:20180705T011500Z
UID:0cxtV_z2jvs3F1thleG7_NMv@stanza.co
SUMMARY:Lookouts vs. Barons
DESCRIPTION:Lookouts vs. Barons\n\nFollow on MiLB First Pitch: https://stza.co/+wKDG-38\n\nShop: https://stza.co/+wKDG-2N\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144513Z
LAST-MODIFIED:20180213T144513Z
TRANSP:OPAQUE
END:VEVENT
* Lookouts vs. Barons
<2018-07-05 Thu 18:15-21:15>
:PROPERTIES:
:ID:       75G2tiDNePfSi22vzNtJmBuZ@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Lookouts vs. Barons Lookouts vs. Barons

Follow on MiLB First Pitch  https //stza.co/+wKDJ-F

Shop  https //stza.co/+wKDJ-2Y

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Lookouts vs. Barons
END:VALARM
DTSTART:20180705T231500Z
DTEND:20180706T021500Z
UID:75G2tiDNePfSi22vzNtJmBuZ@stanza.co
SUMMARY:Lookouts vs. Barons
DESCRIPTION:Lookouts vs. Barons\n\nFollow on MiLB First Pitch: https://stza.co/+wKDJ-F\n\nShop: https://stza.co/+wKDJ-2Y\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144513Z
LAST-MODIFIED:20180213T144513Z
TRANSP:OPAQUE
END:VEVENT
* Lookouts vs. Barons
<2018-07-06 Fri 18:15-21:15>
:PROPERTIES:
:ID:       lN0TjYI8aFfj-7FhjiW1qLqs@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Lookouts vs. Barons Lookouts vs. Barons

Follow on MiLB First Pitch  https //stza.co/+wKDL-3T

Shop  https //stza.co/+wKDL-1I

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Lookouts vs. Barons
END:VALARM
DTSTART:20180706T231500Z
DTEND:20180707T021500Z
UID:lN0TjYI8aFfj-7FhjiW1qLqs@stanza.co
SUMMARY:Lookouts vs. Barons
DESCRIPTION:Lookouts vs. Barons\n\nFollow on MiLB First Pitch: https://stza.co/+wKDL-3T\n\nShop: https://stza.co/+wKDL-1I\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144513Z
LAST-MODIFIED:20180213T144513Z
TRANSP:OPAQUE
END:VEVENT
* Lookouts vs. Barons
<2018-07-07 Sat 18:15-21:15>
:PROPERTIES:
:ID:       xbGZDnZSVYiBG32ZnZeIyOO9@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Lookouts vs. Barons Lookouts vs. Barons

Follow on MiLB First Pitch  https //stza.co/+wKDN-F

Shop  https //stza.co/+wKDN-30

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Lookouts vs. Barons
END:VALARM
DTSTART:20180707T231500Z
DTEND:20180708T021500Z
UID:xbGZDnZSVYiBG32ZnZeIyOO9@stanza.co
SUMMARY:Lookouts vs. Barons
DESCRIPTION:Lookouts vs. Barons\n\nFollow on MiLB First Pitch: https://stza.co/+wKDN-F\n\nShop: https://stza.co/+wKDN-30\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144513Z
LAST-MODIFIED:20180213T144513Z
TRANSP:OPAQUE
END:VEVENT
* Lookouts @ Jumbo Shrimp
<2018-07-08 Sun 17:05-20:05>
:PROPERTIES:
:ID:       Pb1fGg7uqcHtGJhC_weURSuL@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Lookouts @ Jumbo Shrimp Lookouts @ Jumbo Shrimp

Follow on MiLB First Pitch  https //stza.co/+vLEA-21

Shop  https //stza.co/+vLEA-2_

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Lookouts @ Jumbo Shrimp
END:VALARM
DTSTART:20180708T220500Z
DTEND:20180709T010500Z
UID:Pb1fGg7uqcHtGJhC_weURSuL@stanza.co
SUMMARY:Lookouts @ Jumbo Shrimp
DESCRIPTION:Lookouts @ Jumbo Shrimp\n\nFollow on MiLB First Pitch: https://stza.co/+vLEA-21\n\nShop: https://stza.co/+vLEA-2_\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144513Z
LAST-MODIFIED:20180213T144513Z
TRANSP:OPAQUE
END:VEVENT
* Lookouts @ Jumbo Shrimp
<2018-07-09 Mon 18:05-21:05>
:PROPERTIES:
:ID:       woaCaPwLnMyKkw9cvNkJ2diV@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Lookouts @ Jumbo Shrimp Lookouts @ Jumbo Shrimp

Follow on MiLB First Pitch  https //stza.co/+vLEB-2Y

Shop  https //stza.co/+vLEB-3S

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Lookouts @ Jumbo Shrimp
END:VALARM
DTSTART:20180709T230500Z
DTEND:20180710T020500Z
UID:woaCaPwLnMyKkw9cvNkJ2diV@stanza.co
SUMMARY:Lookouts @ Jumbo Shrimp
DESCRIPTION:Lookouts @ Jumbo Shrimp\n\nFollow on MiLB First Pitch: https://stza.co/+vLEB-2Y\n\nShop: https://stza.co/+vLEB-3S\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144513Z
LAST-MODIFIED:20180213T144513Z
TRANSP:OPAQUE
END:VEVENT
* Lookouts @ Jumbo Shrimp
<2018-07-10 Tue 18:05-21:05>
:PROPERTIES:
:ID:       VoTN6MLUxgHAnZDM6m51B_Lp@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Lookouts @ Jumbo Shrimp Lookouts @ Jumbo Shrimp

Follow on MiLB First Pitch  https //stza.co/+vLEC-z

Shop  https //stza.co/+vLEC-3l

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Lookouts @ Jumbo Shrimp
END:VALARM
DTSTART:20180710T230500Z
DTEND:20180711T020500Z
UID:VoTN6MLUxgHAnZDM6m51B_Lp@stanza.co
SUMMARY:Lookouts @ Jumbo Shrimp
DESCRIPTION:Lookouts @ Jumbo Shrimp\n\nFollow on MiLB First Pitch: https://stza.co/+vLEC-z\n\nShop: https://stza.co/+vLEC-3l\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144513Z
LAST-MODIFIED:20180213T144513Z
TRANSP:OPAQUE
END:VEVENT
* Lookouts @ Jumbo Shrimp
<2018-07-11 Wed 11:05-14:05>
:PROPERTIES:
:ID:       crcPrOlIEs77BjG2IGy1jZcK@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Lookouts @ Jumbo Shrimp Lookouts @ Jumbo Shrimp

Follow on MiLB First Pitch  https //stza.co/+vLED-22

Shop  https //stza.co/+vLED-2$

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Lookouts @ Jumbo Shrimp
END:VALARM
DTSTART:20180711T160500Z
DTEND:20180711T190500Z
UID:crcPrOlIEs77BjG2IGy1jZcK@stanza.co
SUMMARY:Lookouts @ Jumbo Shrimp
DESCRIPTION:Lookouts @ Jumbo Shrimp\n\nFollow on MiLB First Pitch: https://stza.co/+vLED-22\n\nShop: https://stza.co/+vLED-2$\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144513Z
LAST-MODIFIED:20180213T144513Z
TRANSP:OPAQUE
END:VEVENT
* Lookouts vs. Biscuits
<2018-07-12 Thu 18:15-21:15>
:PROPERTIES:
:ID:       KZOA2FyPPTVickpnDc60DTmj@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Lookouts vs. Biscuits Lookouts vs. Biscuits

Follow on MiLB First Pitch  https //stza.co/+wKDO-2P

Shop  https //stza.co/+wKDO-W

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Lookouts vs. Biscuits
END:VALARM
DTSTART:20180712T231500Z
DTEND:20180713T021500Z
UID:KZOA2FyPPTVickpnDc60DTmj@stanza.co
SUMMARY:Lookouts vs. Biscuits
DESCRIPTION:Lookouts vs. Biscuits\n\nFollow on MiLB First Pitch: https://stza.co/+wKDO-2P\n\nShop: https://stza.co/+wKDO-W\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144513Z
LAST-MODIFIED:20180213T144513Z
TRANSP:OPAQUE
END:VEVENT
* Lookouts vs. Biscuits
<2018-07-13 Fri 18:15-21:15>
:PROPERTIES:
:ID:       gkdpd51z3l_RGlvQe6p1tah9@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Lookouts vs. Biscuits Lookouts vs. Biscuits

Follow on MiLB First Pitch  https //stza.co/+wKDR-m

Shop  https //stza.co/+wKDR-2C

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Lookouts vs. Biscuits
END:VALARM
DTSTART:20180713T231500Z
DTEND:20180714T021500Z
UID:gkdpd51z3l_RGlvQe6p1tah9@stanza.co
SUMMARY:Lookouts vs. Biscuits
DESCRIPTION:Lookouts vs. Biscuits\n\nFollow on MiLB First Pitch: https://stza.co/+wKDR-m\n\nShop: https://stza.co/+wKDR-2C\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144513Z
LAST-MODIFIED:20180213T144513Z
TRANSP:OPAQUE
END:VEVENT
* Lookouts vs. Biscuits
<2018-07-14 Sat 18:15-21:15>
:PROPERTIES:
:ID:       H_ImOG7CXo0UQOG1oGTJ1rHs@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Lookouts vs. Biscuits Lookouts vs. Biscuits

Follow on MiLB First Pitch  https //stza.co/+wKDS-2T

Shop  https //stza.co/+wKDS-1n

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Lookouts vs. Biscuits
END:VALARM
DTSTART:20180714T231500Z
DTEND:20180715T021500Z
UID:H_ImOG7CXo0UQOG1oGTJ1rHs@stanza.co
SUMMARY:Lookouts vs. Biscuits
DESCRIPTION:Lookouts vs. Biscuits\n\nFollow on MiLB First Pitch: https://stza.co/+wKDS-2T\n\nShop: https://stza.co/+wKDS-1n\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144513Z
LAST-MODIFIED:20180213T144513Z
TRANSP:OPAQUE
END:VEVENT
* Lookouts vs. Biscuits
<2018-07-15 Sun 13:15-16:15>
:PROPERTIES:
:ID:       fE5wuBveRGa4rtXbjo2XHbJt@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Lookouts vs. Biscuits Lookouts vs. Biscuits

Follow on MiLB First Pitch  https //stza.co/+wKDV-1T

Shop  https //stza.co/+wKDV-W

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Lookouts vs. Biscuits
END:VALARM
DTSTART:20180715T181500Z
DTEND:20180715T211500Z
UID:fE5wuBveRGa4rtXbjo2XHbJt@stanza.co
SUMMARY:Lookouts vs. Biscuits
DESCRIPTION:Lookouts vs. Biscuits\n\nFollow on MiLB First Pitch: https://stza.co/+wKDV-1T\n\nShop: https://stza.co/+wKDV-W\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144513Z
LAST-MODIFIED:20180213T144513Z
TRANSP:OPAQUE
END:VEVENT
* Lookouts vs. Biscuits
<2018-07-16 Mon 18:15-21:15>
:PROPERTIES:
:ID:       02wbjt1tX2TWv2gpLcaTyhfK@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Lookouts vs. Biscuits Lookouts vs. Biscuits

Follow on MiLB First Pitch  https //stza.co/+wKDY-3k

Shop  https //stza.co/+wKDY-q

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Lookouts vs. Biscuits
END:VALARM
DTSTART:20180716T231500Z
DTEND:20180717T021500Z
UID:02wbjt1tX2TWv2gpLcaTyhfK@stanza.co
SUMMARY:Lookouts vs. Biscuits
DESCRIPTION:Lookouts vs. Biscuits\n\nFollow on MiLB First Pitch: https://stza.co/+wKDY-3k\n\nShop: https://stza.co/+wKDY-q\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144513Z
LAST-MODIFIED:20180213T144513Z
TRANSP:OPAQUE
END:VEVENT
* Lookouts @ BayBears
<2018-07-18 Wed 18:35-21:35>
:PROPERTIES:
:ID:       BqFdDCytKtt1eZ0Kdh_JLctT@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Lookouts @ BayBears Lookouts @ BayBears

Follow on MiLB First Pitch  https //stza.co/+v$PE-32

Shop  https //stza.co/+v$PE-2e

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Lookouts @ BayBears
END:VALARM
DTSTART:20180718T233500Z
DTEND:20180719T023500Z
UID:BqFdDCytKtt1eZ0Kdh_JLctT@stanza.co
SUMMARY:Lookouts @ BayBears
DESCRIPTION:Lookouts @ BayBears\n\nFollow on MiLB First Pitch: https://stza.co/+v$PE-32\n\nShop: https://stza.co/+v$PE-2e\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144513Z
LAST-MODIFIED:20180213T144513Z
TRANSP:OPAQUE
END:VEVENT
* Lookouts @ BayBears
<2018-07-19 Thu 18:35-21:35>
:PROPERTIES:
:ID:       HSWwrAdE6No-bRTr7qDG14Yq@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Lookouts @ BayBears Lookouts @ BayBears

Follow on MiLB First Pitch  https //stza.co/+v$PF-P

Shop  https //stza.co/+v$PF-34

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Lookouts @ BayBears
END:VALARM
DTSTART:20180719T233500Z
DTEND:20180720T023500Z
UID:HSWwrAdE6No-bRTr7qDG14Yq@stanza.co
SUMMARY:Lookouts @ BayBears
DESCRIPTION:Lookouts @ BayBears\n\nFollow on MiLB First Pitch: https://stza.co/+v$PF-P\n\nShop: https://stza.co/+v$PF-34\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144513Z
LAST-MODIFIED:20180213T144513Z
TRANSP:OPAQUE
END:VEVENT
* Lookouts @ BayBears
<2018-07-20 Fri 19:05-22:05>
:PROPERTIES:
:ID:       NV3DnWioFwz6LoZpeAtt11e6@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Lookouts @ BayBears Lookouts @ BayBears

Follow on MiLB First Pitch  https //stza.co/+v$PG-39

Shop  https //stza.co/+v$PG-20

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Lookouts @ BayBears
END:VALARM
DTSTART:20180721T000500Z
DTEND:20180721T030500Z
UID:NV3DnWioFwz6LoZpeAtt11e6@stanza.co
SUMMARY:Lookouts @ BayBears
DESCRIPTION:Lookouts @ BayBears\n\nFollow on MiLB First Pitch: https://stza.co/+v$PG-39\n\nShop: https://stza.co/+v$PG-20\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144513Z
LAST-MODIFIED:20180213T144513Z
TRANSP:OPAQUE
END:VEVENT
* Lookouts @ BayBears
<2018-07-21 Sat 19:05-22:05>
:PROPERTIES:
:ID:       tYKKZye85tGtj-ogtwq5C0a7@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Lookouts @ BayBears Lookouts @ BayBears

Follow on MiLB First Pitch  https //stza.co/+v$PH-3X

Shop  https //stza.co/+v$PH-3V

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Lookouts @ BayBears
END:VALARM
DTSTART:20180722T000500Z
DTEND:20180722T030500Z
UID:tYKKZye85tGtj-ogtwq5C0a7@stanza.co
SUMMARY:Lookouts @ BayBears
DESCRIPTION:Lookouts @ BayBears\n\nFollow on MiLB First Pitch: https://stza.co/+v$PH-3X\n\nShop: https://stza.co/+v$PH-3V\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144513Z
LAST-MODIFIED:20180213T144513Z
TRANSP:OPAQUE
END:VEVENT
* Lookouts @ BayBears
<2018-07-22 Sun 17:05-20:05>
:PROPERTIES:
:ID:       xoR2NtxiIj2rXzZ-wscIDUBS@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Lookouts @ BayBears Lookouts @ BayBears

Follow on MiLB First Pitch  https //stza.co/+v$PI-3p

Shop  https //stza.co/+v$PI-3U

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Lookouts @ BayBears
END:VALARM
DTSTART:20180722T220500Z
DTEND:20180723T010500Z
UID:xoR2NtxiIj2rXzZ-wscIDUBS@stanza.co
SUMMARY:Lookouts @ BayBears
DESCRIPTION:Lookouts @ BayBears\n\nFollow on MiLB First Pitch: https://stza.co/+v$PI-3p\n\nShop: https://stza.co/+v$PI-3U\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144513Z
LAST-MODIFIED:20180213T144513Z
TRANSP:OPAQUE
END:VEVENT
* Lookouts vs. Blue Wahoos
<2018-07-23 Mon 18:15-21:15>
:PROPERTIES:
:ID:       28MC4IRrRZHrfVnO_RqrBLKC@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Lookouts vs. Blue Wahoos Lookouts vs. Blue Wahoos

Follow on MiLB First Pitch  https //stza.co/+wKD_-C

Shop  https //stza.co/+wKD_-1a

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Lookouts vs. Blue Wahoos
END:VALARM
DTSTART:20180723T231500Z
DTEND:20180724T021500Z
UID:28MC4IRrRZHrfVnO_RqrBLKC@stanza.co
SUMMARY:Lookouts vs. Blue Wahoos
DESCRIPTION:Lookouts vs. Blue Wahoos\n\nFollow on MiLB First Pitch: https://stza.co/+wKD_-C\n\nShop: https://stza.co/+wKD_-1a\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144513Z
LAST-MODIFIED:20180213T144513Z
TRANSP:OPAQUE
END:VEVENT
* Lookouts vs. Blue Wahoos
<2018-07-24 Tue 18:15-21:15>
:PROPERTIES:
:ID:       lJWwQFwdAbpLQZWuZOkzxDMT@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Lookouts vs. Blue Wahoos Lookouts vs. Blue Wahoos

Follow on MiLB First Pitch  https //stza.co/+wKE0-M

Shop  https //stza.co/+wKE0-31

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Lookouts vs. Blue Wahoos
END:VALARM
DTSTART:20180724T231500Z
DTEND:20180725T021500Z
UID:lJWwQFwdAbpLQZWuZOkzxDMT@stanza.co
SUMMARY:Lookouts vs. Blue Wahoos
DESCRIPTION:Lookouts vs. Blue Wahoos\n\nFollow on MiLB First Pitch: https://stza.co/+wKE0-M\n\nShop: https://stza.co/+wKE0-31\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144513Z
LAST-MODIFIED:20180213T144513Z
TRANSP:OPAQUE
END:VEVENT
* Lookouts vs. Blue Wahoos
<2018-07-25 Wed 10:15-13:15>
:PROPERTIES:
:ID:       RwCkWl5iNzVxKhlJtZ1_L7BG@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Lookouts vs. Blue Wahoos Lookouts vs. Blue Wahoos

Follow on MiLB First Pitch  https //stza.co/+wKE1-G

Shop  https //stza.co/+wKE1-3b

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Lookouts vs. Blue Wahoos
END:VALARM
DTSTART:20180725T151500Z
DTEND:20180725T181500Z
UID:RwCkWl5iNzVxKhlJtZ1_L7BG@stanza.co
SUMMARY:Lookouts vs. Blue Wahoos
DESCRIPTION:Lookouts vs. Blue Wahoos\n\nFollow on MiLB First Pitch: https://stza.co/+wKE1-G\n\nShop: https://stza.co/+wKE1-3b\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144513Z
LAST-MODIFIED:20180213T144513Z
TRANSP:OPAQUE
END:VEVENT
* Lookouts vs. Blue Wahoos
<2018-07-26 Thu 18:15-21:15>
:PROPERTIES:
:ID:       leuEywGS6bp-cG18KG8FjddP@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Lookouts vs. Blue Wahoos Lookouts vs. Blue Wahoos

Follow on MiLB First Pitch  https //stza.co/+wKE4-1i

Shop  https //stza.co/+wKE4-2m

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Lookouts vs. Blue Wahoos
END:VALARM
DTSTART:20180726T231500Z
DTEND:20180727T021500Z
UID:leuEywGS6bp-cG18KG8FjddP@stanza.co
SUMMARY:Lookouts vs. Blue Wahoos
DESCRIPTION:Lookouts vs. Blue Wahoos\n\nFollow on MiLB First Pitch: https://stza.co/+wKE4-1i\n\nShop: https://stza.co/+wKE4-2m\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144513Z
LAST-MODIFIED:20180213T144513Z
TRANSP:OPAQUE
END:VEVENT
* Lookouts vs. Blue Wahoos
<2018-07-27 Fri 18:15-21:15>
:PROPERTIES:
:ID:       6VYScj9wks6GXKSYon-QLopU@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Lookouts vs. Blue Wahoos Lookouts vs. Blue Wahoos

Follow on MiLB First Pitch  https //stza.co/+wKE6-2z

Shop  https //stza.co/+wKE6-k

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Lookouts vs. Blue Wahoos
END:VALARM
DTSTART:20180727T231500Z
DTEND:20180728T021500Z
UID:6VYScj9wks6GXKSYon-QLopU@stanza.co
SUMMARY:Lookouts vs. Blue Wahoos
DESCRIPTION:Lookouts vs. Blue Wahoos\n\nFollow on MiLB First Pitch: https://stza.co/+wKE6-2z\n\nShop: https://stza.co/+wKE6-k\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144513Z
LAST-MODIFIED:20180213T144513Z
TRANSP:OPAQUE
END:VEVENT
* Lookouts @ Smokies
<2018-07-28 Sat 18:00-21:00>
:PROPERTIES:
:ID:       NucBzkKmEyTwMpLwNdeScDc3@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Lookouts @ Smokies Lookouts @ Smokies

Follow on MiLB First Pitch  https //stza.co/+xVTa-J

Shop  https //stza.co/+xVTa-3i

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Lookouts @ Smokies
END:VALARM
DTSTART:20180728T230000Z
DTEND:20180729T020000Z
UID:NucBzkKmEyTwMpLwNdeScDc3@stanza.co
SUMMARY:Lookouts @ Smokies
DESCRIPTION:Lookouts @ Smokies\n\nFollow on MiLB First Pitch: https://stza.co/+xVTa-J\n\nShop: https://stza.co/+xVTa-3i\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144513Z
LAST-MODIFIED:20180213T144513Z
TRANSP:OPAQUE
END:VEVENT
* Lookouts @ Smokies
<2018-07-29 Sun 16:30-19:30>
:PROPERTIES:
:ID:       6Fo2pDVDkWmcue01l-fGFzHs@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Lookouts @ Smokies Lookouts @ Smokies

Follow on MiLB First Pitch  https //stza.co/+xVTb-1f

Shop  https //stza.co/+xVTb-1W

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Lookouts @ Smokies
END:VALARM
DTSTART:20180729T213000Z
DTEND:20180730T003000Z
UID:6Fo2pDVDkWmcue01l-fGFzHs@stanza.co
SUMMARY:Lookouts @ Smokies
DESCRIPTION:Lookouts @ Smokies\n\nFollow on MiLB First Pitch: https://stza.co/+xVTb-1f\n\nShop: https://stza.co/+xVTb-1W\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144513Z
LAST-MODIFIED:20180213T144513Z
TRANSP:OPAQUE
END:VEVENT
* Lookouts @ Smokies
<2018-07-30 Mon 18:00-21:00>
:PROPERTIES:
:ID:       V2gsOuGhEaMxfsLyqvS1EDEN@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Lookouts @ Smokies Lookouts @ Smokies

Follow on MiLB First Pitch  https //stza.co/+xVTc-y

Shop  https //stza.co/+xVTc-3z

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Lookouts @ Smokies
END:VALARM
DTSTART:20180730T230000Z
DTEND:20180731T020000Z
UID:V2gsOuGhEaMxfsLyqvS1EDEN@stanza.co
SUMMARY:Lookouts @ Smokies
DESCRIPTION:Lookouts @ Smokies\n\nFollow on MiLB First Pitch: https://stza.co/+xVTc-y\n\nShop: https://stza.co/+xVTc-3z\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144513Z
LAST-MODIFIED:20180213T144513Z
TRANSP:OPAQUE
END:VEVENT
* Lookouts @ Smokies
<2018-07-31 Tue 18:00-21:00>
:PROPERTIES:
:ID:       ebusvvlRm7WbqjXKYN0qgEwM@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Lookouts @ Smokies Lookouts @ Smokies

Follow on MiLB First Pitch  https //stza.co/+xVTd-38

Shop  https //stza.co/+xVTd-1Z

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Lookouts @ Smokies
END:VALARM
DTSTART:20180731T230000Z
DTEND:20180801T020000Z
UID:ebusvvlRm7WbqjXKYN0qgEwM@stanza.co
SUMMARY:Lookouts @ Smokies
DESCRIPTION:Lookouts @ Smokies\n\nFollow on MiLB First Pitch: https://stza.co/+xVTd-38\n\nShop: https://stza.co/+xVTd-1Z\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144513Z
LAST-MODIFIED:20180213T144513Z
TRANSP:OPAQUE
END:VEVENT
* Lookouts @ Smokies
<2018-08-01 Wed 18:00-21:00>
:PROPERTIES:
:ID:       u9p_R-FnfVNau05GSQDBtBZI@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Lookouts @ Smokies Lookouts @ Smokies

Follow on MiLB First Pitch  https //stza.co/+xVTe-l

Shop  https //stza.co/+xVTe-2$

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Lookouts @ Smokies
END:VALARM
DTSTART:20180801T230000Z
DTEND:20180802T020000Z
UID:u9p_R-FnfVNau05GSQDBtBZI@stanza.co
SUMMARY:Lookouts @ Smokies
DESCRIPTION:Lookouts @ Smokies\n\nFollow on MiLB First Pitch: https://stza.co/+xVTe-l\n\nShop: https://stza.co/+xVTe-2$\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144513Z
LAST-MODIFIED:20180213T144513Z
TRANSP:OPAQUE
END:VEVENT
* Lookouts vs. Braves
<2018-08-02 Thu 18:15-21:15>
:PROPERTIES:
:ID:       2OXuTSd2fIKQRPQe9db4l_8-@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Lookouts vs. Braves Lookouts vs. Braves

Follow on MiLB First Pitch  https //stza.co/+wKE8-1a

Shop  https //stza.co/+wKE8-1f

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Lookouts vs. Braves
END:VALARM
DTSTART:20180802T231500Z
DTEND:20180803T021500Z
UID:2OXuTSd2fIKQRPQe9db4l_8-@stanza.co
SUMMARY:Lookouts vs. Braves
DESCRIPTION:Lookouts vs. Braves\n\nFollow on MiLB First Pitch: https://stza.co/+wKE8-1a\n\nShop: https://stza.co/+wKE8-1f\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144513Z
LAST-MODIFIED:20180213T144513Z
TRANSP:OPAQUE
END:VEVENT
* Lookouts vs. Braves
<2018-08-03 Fri 18:15-21:15>
:PROPERTIES:
:ID:       7LV760iQOCs_tps1gFgEMCb-@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Lookouts vs. Braves Lookouts vs. Braves

Follow on MiLB First Pitch  https //stza.co/+wKE9-O

Shop  https //stza.co/+wKE9-1F

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Lookouts vs. Braves
END:VALARM
DTSTART:20180803T231500Z
DTEND:20180804T021500Z
UID:7LV760iQOCs_tps1gFgEMCb-@stanza.co
SUMMARY:Lookouts vs. Braves
DESCRIPTION:Lookouts vs. Braves\n\nFollow on MiLB First Pitch: https://stza.co/+wKE9-O\n\nShop: https://stza.co/+wKE9-1F\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144513Z
LAST-MODIFIED:20180213T144513Z
TRANSP:OPAQUE
END:VEVENT
* Lookouts vs. Braves
<2018-08-04 Sat 18:15-21:15>
:PROPERTIES:
:ID:       VdPpSpBZ1fCrJgvOJKQLuKXO@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Lookouts vs. Braves Lookouts vs. Braves

Follow on MiLB First Pitch  https //stza.co/+wKEc-33

Shop  https //stza.co/+wKEc-j

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Lookouts vs. Braves
END:VALARM
DTSTART:20180804T231500Z
DTEND:20180805T021500Z
UID:VdPpSpBZ1fCrJgvOJKQLuKXO@stanza.co
SUMMARY:Lookouts vs. Braves
DESCRIPTION:Lookouts vs. Braves\n\nFollow on MiLB First Pitch: https://stza.co/+wKEc-33\n\nShop: https://stza.co/+wKEc-j\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144513Z
LAST-MODIFIED:20180213T144513Z
TRANSP:OPAQUE
END:VEVENT
* Lookouts vs. Braves
<2018-08-05 Sun 13:15-16:15>
:PROPERTIES:
:ID:       r_5MeZgIHfHDPizjJNCdV-hQ@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Lookouts vs. Braves Lookouts vs. Braves

Follow on MiLB First Pitch  https //stza.co/+wKEe-2r

Shop  https //stza.co/+wKEe-1_

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Lookouts vs. Braves
END:VALARM
DTSTART:20180805T181500Z
DTEND:20180805T211500Z
UID:r_5MeZgIHfHDPizjJNCdV-hQ@stanza.co
SUMMARY:Lookouts vs. Braves
DESCRIPTION:Lookouts vs. Braves\n\nFollow on MiLB First Pitch: https://stza.co/+wKEe-2r\n\nShop: https://stza.co/+wKEe-1_\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144513Z
LAST-MODIFIED:20180213T144513Z
TRANSP:OPAQUE
END:VEVENT
* Lookouts vs. Braves
<2018-08-06 Mon 18:15-21:15>
:PROPERTIES:
:ID:       ipI3UahVghb3dRw5VZ-3utUD@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Lookouts vs. Braves Lookouts vs. Braves

Follow on MiLB First Pitch  https //stza.co/+wKEf-2H

Shop  https //stza.co/+wKEf-1K

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Lookouts vs. Braves
END:VALARM
DTSTART:20180806T231500Z
DTEND:20180807T021500Z
UID:ipI3UahVghb3dRw5VZ-3utUD@stanza.co
SUMMARY:Lookouts vs. Braves
DESCRIPTION:Lookouts vs. Braves\n\nFollow on MiLB First Pitch: https://stza.co/+wKEf-2H\n\nShop: https://stza.co/+wKEf-1K\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144513Z
LAST-MODIFIED:20180213T144513Z
TRANSP:OPAQUE
END:VEVENT
* Lookouts vs. Generals
<2018-08-08 Wed 18:15-21:15>
:PROPERTIES:
:ID:       Y3bp0qFrxav1FcZPM0iM1Ad8@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Lookouts vs. Generals Lookouts vs. Generals

Follow on MiLB First Pitch  https //stza.co/+wKEh-1d

Shop  https //stza.co/+wKEh-3d

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Lookouts vs. Generals
END:VALARM
DTSTART:20180808T231500Z
DTEND:20180809T021500Z
UID:Y3bp0qFrxav1FcZPM0iM1Ad8@stanza.co
SUMMARY:Lookouts vs. Generals
DESCRIPTION:Lookouts vs. Generals\n\nFollow on MiLB First Pitch: https://stza.co/+wKEh-1d\n\nShop: https://stza.co/+wKEh-3d\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144513Z
LAST-MODIFIED:20180213T144513Z
TRANSP:OPAQUE
END:VEVENT
* Lookouts vs. Generals
<2018-08-09 Thu 18:15-21:15>
:PROPERTIES:
:ID:       AZTJJS5ntuzM6lvwPwKFxg3T@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Lookouts vs. Generals Lookouts vs. Generals

Follow on MiLB First Pitch  https //stza.co/+wKEj-29

Shop  https //stza.co/+wKEj-1j

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Lookouts vs. Generals
END:VALARM
DTSTART:20180809T231500Z
DTEND:20180810T021500Z
UID:AZTJJS5ntuzM6lvwPwKFxg3T@stanza.co
SUMMARY:Lookouts vs. Generals
DESCRIPTION:Lookouts vs. Generals\n\nFollow on MiLB First Pitch: https://stza.co/+wKEj-29\n\nShop: https://stza.co/+wKEj-1j\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144513Z
LAST-MODIFIED:20180213T144513Z
TRANSP:OPAQUE
END:VEVENT
* Lookouts vs. Generals
<2018-08-10 Fri 18:15-21:15>
:PROPERTIES:
:ID:       UKFDbYoGtiVzEnrAY_yFBpSg@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Lookouts vs. Generals Lookouts vs. Generals

Follow on MiLB First Pitch  https //stza.co/+wKEm-37

Shop  https //stza.co/+wKEm-2f

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Lookouts vs. Generals
END:VALARM
DTSTART:20180810T231500Z
DTEND:20180811T021500Z
UID:UKFDbYoGtiVzEnrAY_yFBpSg@stanza.co
SUMMARY:Lookouts vs. Generals
DESCRIPTION:Lookouts vs. Generals\n\nFollow on MiLB First Pitch: https://stza.co/+wKEm-37\n\nShop: https://stza.co/+wKEm-2f\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144513Z
LAST-MODIFIED:20180213T144513Z
TRANSP:OPAQUE
END:VEVENT
* Lookouts vs. Generals
<2018-08-11 Sat 18:15-21:15>
:PROPERTIES:
:ID:       LPL-YJWoKEnHJpnRf6yRms1-@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Lookouts vs. Generals Lookouts vs. Generals

Follow on MiLB First Pitch  https //stza.co/+wKEo-2z

Shop  https //stza.co/+wKEo-C

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Lookouts vs. Generals
END:VALARM
DTSTART:20180811T231500Z
DTEND:20180812T021500Z
UID:LPL-YJWoKEnHJpnRf6yRms1-@stanza.co
SUMMARY:Lookouts vs. Generals
DESCRIPTION:Lookouts vs. Generals\n\nFollow on MiLB First Pitch: https://stza.co/+wKEo-2z\n\nShop: https://stza.co/+wKEo-C\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144513Z
LAST-MODIFIED:20180213T144513Z
TRANSP:OPAQUE
END:VEVENT
* Lookouts vs. Generals
<2018-08-12 Sun 13:15-16:15>
:PROPERTIES:
:ID:       BPp7oFOSTlb_WMAGpB51I4dj@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Lookouts vs. Generals Lookouts vs. Generals

Follow on MiLB First Pitch  https //stza.co/+wKEr-2Z

Shop  https //stza.co/+wKEr-1V

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Lookouts vs. Generals
END:VALARM
DTSTART:20180812T181500Z
DTEND:20180812T211500Z
UID:BPp7oFOSTlb_WMAGpB51I4dj@stanza.co
SUMMARY:Lookouts vs. Generals
DESCRIPTION:Lookouts vs. Generals\n\nFollow on MiLB First Pitch: https://stza.co/+wKEr-2Z\n\nShop: https://stza.co/+wKEr-1V\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144513Z
LAST-MODIFIED:20180213T144513Z
TRANSP:OPAQUE
END:VEVENT
* Lookouts @ Braves
<2018-08-14 Tue 19:00-22:00>
:PROPERTIES:
:ID:       D9LKCadZiL5OaZtOgkDBGH3R@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Lookouts @ Braves Lookouts @ Braves

Follow on MiLB First Pitch  https //stza.co/+vLEE-3F

Shop  https //stza.co/+vLEE-3Q

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Lookouts @ Braves
END:VALARM
DTSTART:20180815T000000Z
DTEND:20180815T030000Z
UID:D9LKCadZiL5OaZtOgkDBGH3R@stanza.co
SUMMARY:Lookouts @ Braves
DESCRIPTION:Lookouts @ Braves\n\nFollow on MiLB First Pitch: https://stza.co/+vLEE-3F\n\nShop: https://stza.co/+vLEE-3Q\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144513Z
LAST-MODIFIED:20180213T144513Z
TRANSP:OPAQUE
END:VEVENT
* Lookouts @ Braves
<2018-08-15 Wed 19:00-22:00>
:PROPERTIES:
:ID:       Unr83Els-80KOwVEU4cm9dGx@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Lookouts @ Braves Lookouts @ Braves

Follow on MiLB First Pitch  https //stza.co/+vLEF-2X

Shop  https //stza.co/+vLEF-3V

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Lookouts @ Braves
END:VALARM
DTSTART:20180816T000000Z
DTEND:20180816T030000Z
UID:Unr83Els-80KOwVEU4cm9dGx@stanza.co
SUMMARY:Lookouts @ Braves
DESCRIPTION:Lookouts @ Braves\n\nFollow on MiLB First Pitch: https://stza.co/+vLEF-2X\n\nShop: https://stza.co/+vLEF-3V\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144513Z
LAST-MODIFIED:20180213T144513Z
TRANSP:OPAQUE
END:VEVENT
* Lookouts @ Braves
<2018-08-16 Thu 19:00-22:00>
:PROPERTIES:
:ID:       jQrfhSxaUXY-u4r6JB_9mp-r@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Lookouts @ Braves Lookouts @ Braves

Follow on MiLB First Pitch  https //stza.co/+vLEG-3r

Shop  https //stza.co/+vLEG-2N

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Lookouts @ Braves
END:VALARM
DTSTART:20180817T000000Z
DTEND:20180817T030000Z
UID:jQrfhSxaUXY-u4r6JB_9mp-r@stanza.co
SUMMARY:Lookouts @ Braves
DESCRIPTION:Lookouts @ Braves\n\nFollow on MiLB First Pitch: https://stza.co/+vLEG-3r\n\nShop: https://stza.co/+vLEG-2N\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144513Z
LAST-MODIFIED:20180213T144513Z
TRANSP:OPAQUE
END:VEVENT
* Lookouts @ Braves
<2018-08-17 Fri 19:00-22:00>
:PROPERTIES:
:ID:       toLeYWffBRkLO0aXMKX2TH0U@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Lookouts @ Braves Lookouts @ Braves

Follow on MiLB First Pitch  https //stza.co/+vLEH-2u

Shop  https //stza.co/+vLEH-17

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Lookouts @ Braves
END:VALARM
DTSTART:20180818T000000Z
DTEND:20180818T030000Z
UID:toLeYWffBRkLO0aXMKX2TH0U@stanza.co
SUMMARY:Lookouts @ Braves
DESCRIPTION:Lookouts @ Braves\n\nFollow on MiLB First Pitch: https://stza.co/+vLEH-2u\n\nShop: https://stza.co/+vLEH-17\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144513Z
LAST-MODIFIED:20180213T144513Z
TRANSP:OPAQUE
END:VEVENT
* Lookouts @ Braves
<2018-08-18 Sat 18:00-21:00>
:PROPERTIES:
:ID:       d5tns887qxgJRWAwzDPEVlRx@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Lookouts @ Braves Lookouts @ Braves

Follow on MiLB First Pitch  https //stza.co/+vLEI-1H

Shop  https //stza.co/+vLEI-3b

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Lookouts @ Braves
END:VALARM
DTSTART:20180818T230000Z
DTEND:20180819T020000Z
UID:d5tns887qxgJRWAwzDPEVlRx@stanza.co
SUMMARY:Lookouts @ Braves
DESCRIPTION:Lookouts @ Braves\n\nFollow on MiLB First Pitch: https://stza.co/+vLEI-1H\n\nShop: https://stza.co/+vLEI-3b\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144513Z
LAST-MODIFIED:20180213T144513Z
TRANSP:OPAQUE
END:VEVENT
* Lookouts @ Biscuits
<2018-08-19 Sun 17:05-20:05>
:PROPERTIES:
:ID:       7XvvGhxDNboKVjO02V3LADUL@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Lookouts @ Biscuits Lookouts @ Biscuits

Follow on MiLB First Pitch  https //stza.co/+vLEY-$

Shop  https //stza.co/+vLEY-1H

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Lookouts @ Biscuits
END:VALARM
DTSTART:20180819T220500Z
DTEND:20180820T010500Z
UID:7XvvGhxDNboKVjO02V3LADUL@stanza.co
SUMMARY:Lookouts @ Biscuits
DESCRIPTION:Lookouts @ Biscuits\n\nFollow on MiLB First Pitch: https://stza.co/+vLEY-$\n\nShop: https://stza.co/+vLEY-1H\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144513Z
LAST-MODIFIED:20180213T144513Z
TRANSP:OPAQUE
END:VEVENT
* Lookouts @ Biscuits
<2018-08-20 Mon 18:35-21:35>
:PROPERTIES:
:ID:       7N9RaM71FGiMfRe7uEWdOp0V@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Lookouts @ Biscuits Lookouts @ Biscuits

Follow on MiLB First Pitch  https //stza.co/+vLEZ-3b

Shop  https //stza.co/+vLEZ-z

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Lookouts @ Biscuits
END:VALARM
DTSTART:20180820T233500Z
DTEND:20180821T023500Z
UID:7N9RaM71FGiMfRe7uEWdOp0V@stanza.co
SUMMARY:Lookouts @ Biscuits
DESCRIPTION:Lookouts @ Biscuits\n\nFollow on MiLB First Pitch: https://stza.co/+vLEZ-3b\n\nShop: https://stza.co/+vLEZ-z\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144513Z
LAST-MODIFIED:20180213T144513Z
TRANSP:OPAQUE
END:VEVENT
* Lookouts @ Biscuits
<2018-08-21 Tue 18:35-21:35>
:PROPERTIES:
:ID:       b6pZYAsxBPFHueH_fWW4dzeR@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Lookouts @ Biscuits Lookouts @ Biscuits

Follow on MiLB First Pitch  https //stza.co/+vLE_-3o

Shop  https //stza.co/+vLE_-1c

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Lookouts @ Biscuits
END:VALARM
DTSTART:20180821T233500Z
DTEND:20180822T023500Z
UID:b6pZYAsxBPFHueH_fWW4dzeR@stanza.co
SUMMARY:Lookouts @ Biscuits
DESCRIPTION:Lookouts @ Biscuits\n\nFollow on MiLB First Pitch: https://stza.co/+vLE_-3o\n\nShop: https://stza.co/+vLE_-1c\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144513Z
LAST-MODIFIED:20180213T144513Z
TRANSP:OPAQUE
END:VEVENT
* Lookouts @ Biscuits
<2018-08-22 Wed 18:35-21:35>
:PROPERTIES:
:ID:       06ynGg9Btlsh1JVCm1jwGjNz@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Lookouts @ Biscuits Lookouts @ Biscuits

Follow on MiLB First Pitch  https //stza.co/+vLE$-1w

Shop  https //stza.co/+vLE$-2t

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Lookouts @ Biscuits
END:VALARM
DTSTART:20180822T233500Z
DTEND:20180823T023500Z
UID:06ynGg9Btlsh1JVCm1jwGjNz@stanza.co
SUMMARY:Lookouts @ Biscuits
DESCRIPTION:Lookouts @ Biscuits\n\nFollow on MiLB First Pitch: https://stza.co/+vLE$-1w\n\nShop: https://stza.co/+vLE$-2t\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144513Z
LAST-MODIFIED:20180213T144513Z
TRANSP:OPAQUE
END:VEVENT
* Lookouts @ Biscuits
<2018-08-23 Thu 18:35-21:35>
:PROPERTIES:
:ID:       4GnuqIFNTvBin2m1y8ZkLqvJ@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Lookouts @ Biscuits Lookouts @ Biscuits

Follow on MiLB First Pitch  https //stza.co/+vLF0-3P

Shop  https //stza.co/+vLF0-3h

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Lookouts @ Biscuits
END:VALARM
DTSTART:20180823T233500Z
DTEND:20180824T023500Z
UID:4GnuqIFNTvBin2m1y8ZkLqvJ@stanza.co
SUMMARY:Lookouts @ Biscuits
DESCRIPTION:Lookouts @ Biscuits\n\nFollow on MiLB First Pitch: https://stza.co/+vLF0-3P\n\nShop: https://stza.co/+vLF0-3h\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144513Z
LAST-MODIFIED:20180213T144513Z
TRANSP:OPAQUE
END:VEVENT
* Lookouts vs. Jumbo Shrimp
<2018-08-24 Fri 18:15-21:15>
:PROPERTIES:
:ID:       8V6clu54nWO7nAYD7A3xleDG@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Lookouts vs. Jumbo Shrimp Lookouts vs. Jumbo Shrimp

Follow on MiLB First Pitch  https //stza.co/+wKEt-N

Shop  https //stza.co/+wKEt-P

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Lookouts vs. Jumbo Shrimp
END:VALARM
DTSTART:20180824T231500Z
DTEND:20180825T021500Z
UID:8V6clu54nWO7nAYD7A3xleDG@stanza.co
SUMMARY:Lookouts vs. Jumbo Shrimp
DESCRIPTION:Lookouts vs. Jumbo Shrimp\n\nFollow on MiLB First Pitch: https://stza.co/+wKEt-N\n\nShop: https://stza.co/+wKEt-P\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144513Z
LAST-MODIFIED:20180213T144513Z
TRANSP:OPAQUE
END:VEVENT
* Lookouts vs. Jumbo Shrimp
<2018-08-25 Sat 18:15-21:15>
:PROPERTIES:
:ID:       6HWoCkEH8nox1lWMktQra1V1@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Lookouts vs. Jumbo Shrimp Lookouts vs. Jumbo Shrimp

Follow on MiLB First Pitch  https //stza.co/+wKEv-q

Shop  https //stza.co/+wKEv-1i

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Lookouts vs. Jumbo Shrimp
END:VALARM
DTSTART:20180825T231500Z
DTEND:20180826T021500Z
UID:6HWoCkEH8nox1lWMktQra1V1@stanza.co
SUMMARY:Lookouts vs. Jumbo Shrimp
DESCRIPTION:Lookouts vs. Jumbo Shrimp\n\nFollow on MiLB First Pitch: https://stza.co/+wKEv-q\n\nShop: https://stza.co/+wKEv-1i\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144513Z
LAST-MODIFIED:20180213T144513Z
TRANSP:OPAQUE
END:VEVENT
* Lookouts vs. Jumbo Shrimp
<2018-08-26 Sun 13:15-16:15>
:PROPERTIES:
:ID:       GbiTEk7JhhBXYcdFGQ_nNDkq@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Lookouts vs. Jumbo Shrimp Lookouts vs. Jumbo Shrimp

Follow on MiLB First Pitch  https //stza.co/+wKEw-3p

Shop  https //stza.co/+wKEw-2P

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Lookouts vs. Jumbo Shrimp
END:VALARM
DTSTART:20180826T181500Z
DTEND:20180826T211500Z
UID:GbiTEk7JhhBXYcdFGQ_nNDkq@stanza.co
SUMMARY:Lookouts vs. Jumbo Shrimp
DESCRIPTION:Lookouts vs. Jumbo Shrimp\n\nFollow on MiLB First Pitch: https://stza.co/+wKEw-3p\n\nShop: https://stza.co/+wKEw-2P\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144513Z
LAST-MODIFIED:20180213T144513Z
TRANSP:OPAQUE
END:VEVENT
* Lookouts vs. Jumbo Shrimp
<2018-08-27 Mon 18:15-21:15>
:PROPERTIES:
:ID:       2zYzu08L0Z647STxIC9-gUgu@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Lookouts vs. Jumbo Shrimp Lookouts vs. Jumbo Shrimp

Follow on MiLB First Pitch  https //stza.co/+wKEy-1g

Shop  https //stza.co/+wKEy-2U

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Lookouts vs. Jumbo Shrimp
END:VALARM
DTSTART:20180827T231500Z
DTEND:20180828T021500Z
UID:2zYzu08L0Z647STxIC9-gUgu@stanza.co
SUMMARY:Lookouts vs. Jumbo Shrimp
DESCRIPTION:Lookouts vs. Jumbo Shrimp\n\nFollow on MiLB First Pitch: https://stza.co/+wKEy-1g\n\nShop: https://stza.co/+wKEy-2U\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144513Z
LAST-MODIFIED:20180213T144513Z
TRANSP:OPAQUE
END:VEVENT
* Lookouts vs. Jumbo Shrimp
<2018-08-28 Tue 18:15-21:15>
:PROPERTIES:
:ID:       IfTYdWRqs4Z_4VL2A7-QBlW7@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Lookouts vs. Jumbo Shrimp Lookouts vs. Jumbo Shrimp

Follow on MiLB First Pitch  https //stza.co/+wKEA-s

Shop  https //stza.co/+wKEA-2E

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Lookouts vs. Jumbo Shrimp
END:VALARM
DTSTART:20180828T231500Z
DTEND:20180829T021500Z
UID:IfTYdWRqs4Z_4VL2A7-QBlW7@stanza.co
SUMMARY:Lookouts vs. Jumbo Shrimp
DESCRIPTION:Lookouts vs. Jumbo Shrimp\n\nFollow on MiLB First Pitch: https://stza.co/+wKEA-s\n\nShop: https://stza.co/+wKEA-2E\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144513Z
LAST-MODIFIED:20180213T144513Z
TRANSP:OPAQUE
END:VEVENT
* Lookouts @ Generals
<2018-08-30 Thu 18:05-21:05>
:PROPERTIES:
:ID:       wOQCdsqHFDzV5nlGdq44VOqH@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Lookouts @ Generals Lookouts @ Generals

Follow on MiLB First Pitch  https //stza.co/+wCNA-Y

Shop  https //stza.co/+wCNA-1X

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Lookouts @ Generals
END:VALARM
DTSTART:20180830T230500Z
DTEND:20180831T020500Z
UID:wOQCdsqHFDzV5nlGdq44VOqH@stanza.co
SUMMARY:Lookouts @ Generals
DESCRIPTION:Lookouts @ Generals\n\nFollow on MiLB First Pitch: https://stza.co/+wCNA-Y\n\nShop: https://stza.co/+wCNA-1X\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144513Z
LAST-MODIFIED:20180213T144513Z
TRANSP:OPAQUE
END:VEVENT
* Lookouts @ Generals
<2018-08-31 Fri 18:05-21:05>
:PROPERTIES:
:ID:       EqC7iDIHbEKrr2-Va1K6Lbsj@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Lookouts @ Generals Lookouts @ Generals

Follow on MiLB First Pitch  https //stza.co/+wCNB-2i

Shop  https //stza.co/+wCNB-22

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Lookouts @ Generals
END:VALARM
DTSTART:20180831T230500Z
DTEND:20180901T020500Z
UID:EqC7iDIHbEKrr2-Va1K6Lbsj@stanza.co
SUMMARY:Lookouts @ Generals
DESCRIPTION:Lookouts @ Generals\n\nFollow on MiLB First Pitch: https://stza.co/+wCNB-2i\n\nShop: https://stza.co/+wCNB-22\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144513Z
LAST-MODIFIED:20180213T144513Z
TRANSP:OPAQUE
END:VEVENT
* Lookouts @ Generals
<2018-09-01 Sat 18:05-21:05>
:PROPERTIES:
:ID:       PfbmrVod82ycEMS78kRjd0J6@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Lookouts @ Generals Lookouts @ Generals

Follow on MiLB First Pitch  https //stza.co/+wCNC-2F

Shop  https //stza.co/+wCNC-1Y

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Lookouts @ Generals
END:VALARM
DTSTART:20180901T230500Z
DTEND:20180902T020500Z
UID:PfbmrVod82ycEMS78kRjd0J6@stanza.co
SUMMARY:Lookouts @ Generals
DESCRIPTION:Lookouts @ Generals\n\nFollow on MiLB First Pitch: https://stza.co/+wCNC-2F\n\nShop: https://stza.co/+wCNC-1Y\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144513Z
LAST-MODIFIED:20180213T144513Z
TRANSP:OPAQUE
END:VEVENT
* Lookouts @ Generals
<2018-09-02 Sun 14:05-17:05>
:PROPERTIES:
:ID:       u6o7ihE4aYRGuPeKZABVcZht@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Lookouts @ Generals Lookouts @ Generals

Follow on MiLB First Pitch  https //stza.co/+wCND-3k

Shop  https //stza.co/+wCND-3f

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Lookouts @ Generals
END:VALARM
DTSTART:20180902T190500Z
DTEND:20180902T220500Z
UID:u6o7ihE4aYRGuPeKZABVcZht@stanza.co
SUMMARY:Lookouts @ Generals
DESCRIPTION:Lookouts @ Generals\n\nFollow on MiLB First Pitch: https://stza.co/+wCND-3k\n\nShop: https://stza.co/+wCND-3f\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144513Z
LAST-MODIFIED:20180213T144513Z
TRANSP:OPAQUE
END:VEVENT
* Lookouts @ Generals
<2018-09-03 Mon 14:05-17:05>
:PROPERTIES:
:ID:       IuyTKJwJ0h3WbYuBcyH-YZje@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Lookouts @ Generals Lookouts @ Generals

Follow on MiLB First Pitch  https //stza.co/+wCNE-2$

Shop  https //stza.co/+wCNE-1P

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Lookouts @ Generals
END:VALARM
DTSTART:20180903T190500Z
DTEND:20180903T220500Z
UID:IuyTKJwJ0h3WbYuBcyH-YZje@stanza.co
SUMMARY:Lookouts @ Generals
DESCRIPTION:Lookouts @ Generals\n\nFollow on MiLB First Pitch: https://stza.co/+wCNE-2$\n\nShop: https://stza.co/+wCNE-1P\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144513Z
LAST-MODIFIED:20180213T144513Z
TRANSP:OPAQUE
END:VEVENT
