#+TITLE:       Main Google calendar entries
#+AUTHOR:      Eric S Fraga
#+EMAIL:       e.fraga@ucl.ac.uk
#+DESCRIPTION: converted using the ical2org awk script
#+CATEGORY:    google
#+STARTUP:     hidestars
#+STARTUP:     overview

* COMMENT original iCal preamble

* BayBears vs. Blue Wahoos
<2018-04-05 Thu 18:35-21:35>
:PROPERTIES:
:ID:       OO0O6f-_R5vd-D9VjaQmZJR2@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

BayBears vs. Blue Wahoos BayBears vs. Blue Wahoos

Follow on MiLB First Pitch  https //stza.co/+v$Q5-3Y

Shop  https //stza.co/+v$Q5-J

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:BayBears vs. Blue Wahoos
END:VALARM
DTSTART:20180405T233500Z
DTEND:20180406T023500Z
UID:OO0O6f-_R5vd-D9VjaQmZJR2@stanza.co
SUMMARY:BayBears vs. Blue Wahoos
DESCRIPTION:BayBears vs. Blue Wahoos\n\nFollow on MiLB First Pitch: https://stza.co/+v$Q5-3Y\n\nShop: https://stza.co/+v$Q5-J\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144544Z
LAST-MODIFIED:20180213T144544Z
TRANSP:OPAQUE
END:VEVENT
* BayBears vs. Blue Wahoos
<2018-04-06 Fri 19:05-22:05>
:PROPERTIES:
:ID:       NQDvHaedcxEqMUtph39L2Gw0@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

BayBears vs. Blue Wahoos BayBears vs. Blue Wahoos

Follow on MiLB First Pitch  https //stza.co/+v$Q8-2g

Shop  https //stza.co/+v$Q8-3X

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:BayBears vs. Blue Wahoos
END:VALARM
DTSTART:20180407T000500Z
DTEND:20180407T030500Z
UID:NQDvHaedcxEqMUtph39L2Gw0@stanza.co
SUMMARY:BayBears vs. Blue Wahoos
DESCRIPTION:BayBears vs. Blue Wahoos\n\nFollow on MiLB First Pitch: https://stza.co/+v$Q8-2g\n\nShop: https://stza.co/+v$Q8-3X\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144544Z
LAST-MODIFIED:20180213T144544Z
TRANSP:OPAQUE
END:VEVENT
* BayBears vs. Blue Wahoos
<2018-04-07 Sat 19:05-22:05>
:PROPERTIES:
:ID:       WGV3yUE4btid0VxToLuZq0Fc@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

BayBears vs. Blue Wahoos BayBears vs. Blue Wahoos

Follow on MiLB First Pitch  https //stza.co/+v$Qa-2X

Shop  https //stza.co/+v$Qa-q

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:BayBears vs. Blue Wahoos
END:VALARM
DTSTART:20180408T000500Z
DTEND:20180408T030500Z
UID:WGV3yUE4btid0VxToLuZq0Fc@stanza.co
SUMMARY:BayBears vs. Blue Wahoos
DESCRIPTION:BayBears vs. Blue Wahoos\n\nFollow on MiLB First Pitch: https://stza.co/+v$Qa-2X\n\nShop: https://stza.co/+v$Qa-q\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144544Z
LAST-MODIFIED:20180213T144544Z
TRANSP:OPAQUE
END:VEVENT
* BayBears vs. Blue Wahoos
<2018-04-08 Sun 14:05-17:05>
:PROPERTIES:
:ID:       V0zi5rDqOzyrXY_hiXtk5enC@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

BayBears vs. Blue Wahoos BayBears vs. Blue Wahoos

Follow on MiLB First Pitch  https //stza.co/+v$Qb-2C

Shop  https //stza.co/+v$Qb-29

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:BayBears vs. Blue Wahoos
END:VALARM
DTSTART:20180408T190500Z
DTEND:20180408T220500Z
UID:V0zi5rDqOzyrXY_hiXtk5enC@stanza.co
SUMMARY:BayBears vs. Blue Wahoos
DESCRIPTION:BayBears vs. Blue Wahoos\n\nFollow on MiLB First Pitch: https://stza.co/+v$Qb-2C\n\nShop: https://stza.co/+v$Qb-29\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144544Z
LAST-MODIFIED:20180213T144544Z
TRANSP:OPAQUE
END:VEVENT
* BayBears vs. Blue Wahoos
<2018-04-09 Mon 18:35-21:35>
:PROPERTIES:
:ID:       8ZJumC0D6_R3t15pm0PqsoR1@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

BayBears vs. Blue Wahoos BayBears vs. Blue Wahoos

Follow on MiLB First Pitch  https //stza.co/+v$Qd-2s

Shop  https //stza.co/+v$Qd-7

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:BayBears vs. Blue Wahoos
END:VALARM
DTSTART:20180409T233500Z
DTEND:20180410T023500Z
UID:8ZJumC0D6_R3t15pm0PqsoR1@stanza.co
SUMMARY:BayBears vs. Blue Wahoos
DESCRIPTION:BayBears vs. Blue Wahoos\n\nFollow on MiLB First Pitch: https://stza.co/+v$Qd-2s\n\nShop: https://stza.co/+v$Qd-7\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144544Z
LAST-MODIFIED:20180213T144544Z
TRANSP:OPAQUE
END:VEVENT
* BayBears @ Jumbo Shrimp
<2018-04-11 Wed 18:05-21:05>
:PROPERTIES:
:ID:       CWR1g_kOSjO1Utmhvh81oWv5@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

BayBears @ Jumbo Shrimp BayBears @ Jumbo Shrimp

Follow on MiLB First Pitch  https //stza.co/+vLM2-2H

Shop  https //stza.co/+vLM2-3Y

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:BayBears @ Jumbo Shrimp
END:VALARM
DTSTART:20180411T230500Z
DTEND:20180412T020500Z
UID:CWR1g_kOSjO1Utmhvh81oWv5@stanza.co
SUMMARY:BayBears @ Jumbo Shrimp
DESCRIPTION:BayBears @ Jumbo Shrimp\n\nFollow on MiLB First Pitch: https://stza.co/+vLM2-2H\n\nShop: https://stza.co/+vLM2-3Y\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144544Z
LAST-MODIFIED:20180213T144544Z
TRANSP:OPAQUE
END:VEVENT
* BayBears @ Jumbo Shrimp
<2018-04-12 Thu 18:05-21:05>
:PROPERTIES:
:ID:       tKLAgELMIURW6p6WUpGg8VnD@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

BayBears @ Jumbo Shrimp BayBears @ Jumbo Shrimp

Follow on MiLB First Pitch  https //stza.co/+vLM3-3a

Shop  https //stza.co/+vLM3-22

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:BayBears @ Jumbo Shrimp
END:VALARM
DTSTART:20180412T230500Z
DTEND:20180413T020500Z
UID:tKLAgELMIURW6p6WUpGg8VnD@stanza.co
SUMMARY:BayBears @ Jumbo Shrimp
DESCRIPTION:BayBears @ Jumbo Shrimp\n\nFollow on MiLB First Pitch: https://stza.co/+vLM3-3a\n\nShop: https://stza.co/+vLM3-22\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144544Z
LAST-MODIFIED:20180213T144544Z
TRANSP:OPAQUE
END:VEVENT
* BayBears @ Jumbo Shrimp
<2018-04-13 Fri 18:05-21:05>
:PROPERTIES:
:ID:       uxhsVKDrCeumLlnn1SRyD29L@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

BayBears @ Jumbo Shrimp BayBears @ Jumbo Shrimp

Follow on MiLB First Pitch  https //stza.co/+vLM4-3

Shop  https //stza.co/+vLM4-3W

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:BayBears @ Jumbo Shrimp
END:VALARM
DTSTART:20180413T230500Z
DTEND:20180414T020500Z
UID:uxhsVKDrCeumLlnn1SRyD29L@stanza.co
SUMMARY:BayBears @ Jumbo Shrimp
DESCRIPTION:BayBears @ Jumbo Shrimp\n\nFollow on MiLB First Pitch: https://stza.co/+vLM4-3\n\nShop: https://stza.co/+vLM4-3W\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144544Z
LAST-MODIFIED:20180213T144544Z
TRANSP:OPAQUE
END:VEVENT
* BayBears @ Jumbo Shrimp
<2018-04-14 Sat 17:35-20:35>
:PROPERTIES:
:ID:       iogy11z74BJoXl8qogo8v4-Q@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

BayBears @ Jumbo Shrimp BayBears @ Jumbo Shrimp

Follow on MiLB First Pitch  https //stza.co/+vLM5-1P

Shop  https //stza.co/+vLM5-3d

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:BayBears @ Jumbo Shrimp
END:VALARM
DTSTART:20180414T223500Z
DTEND:20180415T013500Z
UID:iogy11z74BJoXl8qogo8v4-Q@stanza.co
SUMMARY:BayBears @ Jumbo Shrimp
DESCRIPTION:BayBears @ Jumbo Shrimp\n\nFollow on MiLB First Pitch: https://stza.co/+vLM5-1P\n\nShop: https://stza.co/+vLM5-3d\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144544Z
LAST-MODIFIED:20180213T144544Z
TRANSP:OPAQUE
END:VEVENT
* BayBears @ Jumbo Shrimp
<2018-04-15 Sun 14:05-17:05>
:PROPERTIES:
:ID:       6-e0P1L0CMBFzAGfH7gB7iPE@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

BayBears @ Jumbo Shrimp BayBears @ Jumbo Shrimp

Follow on MiLB First Pitch  https //stza.co/+vLM6-z

Shop  https //stza.co/+vLM6-1g

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:BayBears @ Jumbo Shrimp
END:VALARM
DTSTART:20180415T190500Z
DTEND:20180415T220500Z
UID:6-e0P1L0CMBFzAGfH7gB7iPE@stanza.co
SUMMARY:BayBears @ Jumbo Shrimp
DESCRIPTION:BayBears @ Jumbo Shrimp\n\nFollow on MiLB First Pitch: https://stza.co/+vLM6-z\n\nShop: https://stza.co/+vLM6-1g\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144544Z
LAST-MODIFIED:20180213T144544Z
TRANSP:OPAQUE
END:VEVENT
* BayBears vs. Shuckers
<2018-04-16 Mon 18:35-21:35>
:PROPERTIES:
:ID:       pGJ8gCXUac3iK5LvtS3cP0GB@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

BayBears vs. Shuckers BayBears vs. Shuckers

Follow on MiLB First Pitch  https //stza.co/+v$Qg-2p

Shop  https //stza.co/+v$Qg-1Q

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:BayBears vs. Shuckers
END:VALARM
DTSTART:20180416T233500Z
DTEND:20180417T023500Z
UID:pGJ8gCXUac3iK5LvtS3cP0GB@stanza.co
SUMMARY:BayBears vs. Shuckers
DESCRIPTION:BayBears vs. Shuckers\n\nFollow on MiLB First Pitch: https://stza.co/+v$Qg-2p\n\nShop: https://stza.co/+v$Qg-1Q\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144544Z
LAST-MODIFIED:20180213T144544Z
TRANSP:OPAQUE
END:VEVENT
* BayBears vs. Shuckers
<2018-04-17 Tue 18:35-21:35>
:PROPERTIES:
:ID:       _zhJGd3yYGHsZHt-JLIZqDo3@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

BayBears vs. Shuckers BayBears vs. Shuckers

Follow on MiLB First Pitch  https //stza.co/+v$Qi-d

Shop  https //stza.co/+v$Qi-11

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:BayBears vs. Shuckers
END:VALARM
DTSTART:20180417T233500Z
DTEND:20180418T023500Z
UID:_zhJGd3yYGHsZHt-JLIZqDo3@stanza.co
SUMMARY:BayBears vs. Shuckers
DESCRIPTION:BayBears vs. Shuckers\n\nFollow on MiLB First Pitch: https://stza.co/+v$Qi-d\n\nShop: https://stza.co/+v$Qi-11\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144544Z
LAST-MODIFIED:20180213T144544Z
TRANSP:OPAQUE
END:VEVENT
* BayBears vs. Shuckers
<2018-04-18 Wed 18:35-21:35>
:PROPERTIES:
:ID:       JiiJyUn008viXAnfj9Zc5mz8@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

BayBears vs. Shuckers BayBears vs. Shuckers

Follow on MiLB First Pitch  https //stza.co/+v$Qj-s

Shop  https //stza.co/+v$Qj-1W

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:BayBears vs. Shuckers
END:VALARM
DTSTART:20180418T233500Z
DTEND:20180419T023500Z
UID:JiiJyUn008viXAnfj9Zc5mz8@stanza.co
SUMMARY:BayBears vs. Shuckers
DESCRIPTION:BayBears vs. Shuckers\n\nFollow on MiLB First Pitch: https://stza.co/+v$Qj-s\n\nShop: https://stza.co/+v$Qj-1W\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144544Z
LAST-MODIFIED:20180213T144544Z
TRANSP:OPAQUE
END:VEVENT
* BayBears vs. Shuckers
<2018-04-19 Thu 18:35-21:35>
:PROPERTIES:
:ID:       4GpIeeuPrfTHYatoh0hjPgCz@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

BayBears vs. Shuckers BayBears vs. Shuckers

Follow on MiLB First Pitch  https //stza.co/+v$Ql-3d

Shop  https //stza.co/+v$Ql-1I

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:BayBears vs. Shuckers
END:VALARM
DTSTART:20180419T233500Z
DTEND:20180420T023500Z
UID:4GpIeeuPrfTHYatoh0hjPgCz@stanza.co
SUMMARY:BayBears vs. Shuckers
DESCRIPTION:BayBears vs. Shuckers\n\nFollow on MiLB First Pitch: https://stza.co/+v$Ql-3d\n\nShop: https://stza.co/+v$Ql-1I\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144544Z
LAST-MODIFIED:20180213T144544Z
TRANSP:OPAQUE
END:VEVENT
* BayBears vs. Shuckers
<2018-04-20 Fri 19:05-22:05>
:PROPERTIES:
:ID:       AfrhhVOBySd_sH4u0MEG1L1h@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

BayBears vs. Shuckers BayBears vs. Shuckers

Follow on MiLB First Pitch  https //stza.co/+v$Qo-3Y

Shop  https //stza.co/+v$Qo-2i

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:BayBears vs. Shuckers
END:VALARM
DTSTART:20180421T000500Z
DTEND:20180421T030500Z
UID:AfrhhVOBySd_sH4u0MEG1L1h@stanza.co
SUMMARY:BayBears vs. Shuckers
DESCRIPTION:BayBears vs. Shuckers\n\nFollow on MiLB First Pitch: https://stza.co/+v$Qo-3Y\n\nShop: https://stza.co/+v$Qo-2i\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144544Z
LAST-MODIFIED:20180213T144544Z
TRANSP:OPAQUE
END:VEVENT
* BayBears vs. Braves
<2018-04-21 Sat 19:05-22:05>
:PROPERTIES:
:ID:       Rl1K_3n6sgN9PtiCVB8RgXYe@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

BayBears vs. Braves BayBears vs. Braves

Follow on MiLB First Pitch  https //stza.co/+v$Qq-1a

Shop  https //stza.co/+v$Qq-12

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:BayBears vs. Braves
END:VALARM
DTSTART:20180422T000500Z
DTEND:20180422T030500Z
UID:Rl1K_3n6sgN9PtiCVB8RgXYe@stanza.co
SUMMARY:BayBears vs. Braves
DESCRIPTION:BayBears vs. Braves\n\nFollow on MiLB First Pitch: https://stza.co/+v$Qq-1a\n\nShop: https://stza.co/+v$Qq-12\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144544Z
LAST-MODIFIED:20180213T144544Z
TRANSP:OPAQUE
END:VEVENT
* BayBears vs. Braves
<2018-04-22 Sun 14:05-17:05>
:PROPERTIES:
:ID:       KYeRQEVgK3ARz4FQlvs6TWkb@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

BayBears vs. Braves BayBears vs. Braves

Follow on MiLB First Pitch  https //stza.co/+v$Qs-3a

Shop  https //stza.co/+v$Qs-3F

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:BayBears vs. Braves
END:VALARM
DTSTART:20180422T190500Z
DTEND:20180422T220500Z
UID:KYeRQEVgK3ARz4FQlvs6TWkb@stanza.co
SUMMARY:BayBears vs. Braves
DESCRIPTION:BayBears vs. Braves\n\nFollow on MiLB First Pitch: https://stza.co/+v$Qs-3a\n\nShop: https://stza.co/+v$Qs-3F\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144544Z
LAST-MODIFIED:20180213T144544Z
TRANSP:OPAQUE
END:VEVENT
* BayBears vs. Braves
<2018-04-23 Mon 18:35-21:35>
:PROPERTIES:
:ID:       WrjYwgXwBFg-SBPrgtgrT6Iu@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

BayBears vs. Braves BayBears vs. Braves

Follow on MiLB First Pitch  https //stza.co/+v$Qu-1V

Shop  https //stza.co/+v$Qu-3c

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:BayBears vs. Braves
END:VALARM
DTSTART:20180423T233500Z
DTEND:20180424T023500Z
UID:WrjYwgXwBFg-SBPrgtgrT6Iu@stanza.co
SUMMARY:BayBears vs. Braves
DESCRIPTION:BayBears vs. Braves\n\nFollow on MiLB First Pitch: https://stza.co/+v$Qu-1V\n\nShop: https://stza.co/+v$Qu-3c\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144544Z
LAST-MODIFIED:20180213T144544Z
TRANSP:OPAQUE
END:VEVENT
* BayBears vs. Braves
<2018-04-24 Tue 18:35-21:35>
:PROPERTIES:
:ID:       rl_7yQxC_pTuoYo8qBD1JxXz@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

BayBears vs. Braves BayBears vs. Braves

Follow on MiLB First Pitch  https //stza.co/+v$Qv-1V

Shop  https //stza.co/+v$Qv-3m

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:BayBears vs. Braves
END:VALARM
DTSTART:20180424T233500Z
DTEND:20180425T023500Z
UID:rl_7yQxC_pTuoYo8qBD1JxXz@stanza.co
SUMMARY:BayBears vs. Braves
DESCRIPTION:BayBears vs. Braves\n\nFollow on MiLB First Pitch: https://stza.co/+v$Qv-1V\n\nShop: https://stza.co/+v$Qv-3m\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144544Z
LAST-MODIFIED:20180213T144544Z
TRANSP:OPAQUE
END:VEVENT
* BayBears vs. Braves
<2018-04-25 Wed 11:05-14:05>
:PROPERTIES:
:ID:       9cGgOWAPDD9Er-J__wiUf-4n@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

BayBears vs. Braves BayBears vs. Braves

Follow on MiLB First Pitch  https //stza.co/+v$Qy-1c

Shop  https //stza.co/+v$Qy-$

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:BayBears vs. Braves
END:VALARM
DTSTART:20180425T160500Z
DTEND:20180425T190500Z
UID:9cGgOWAPDD9Er-J__wiUf-4n@stanza.co
SUMMARY:BayBears vs. Braves
DESCRIPTION:BayBears vs. Braves\n\nFollow on MiLB First Pitch: https://stza.co/+v$Qy-1c\n\nShop: https://stza.co/+v$Qy-$\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144544Z
LAST-MODIFIED:20180213T144544Z
TRANSP:OPAQUE
END:VEVENT
* BayBears @ Biscuits
<2018-04-26 Thu 18:35-21:35>
:PROPERTIES:
:ID:       eMcRIUY2_kwphqE5R0jmhD_0@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

BayBears @ Biscuits BayBears @ Biscuits

Follow on MiLB First Pitch  https //stza.co/+vLOy-3L

Shop  https //stza.co/+vLOy-2S

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:BayBears @ Biscuits
END:VALARM
DTSTART:20180426T233500Z
DTEND:20180427T023500Z
UID:eMcRIUY2_kwphqE5R0jmhD_0@stanza.co
SUMMARY:BayBears @ Biscuits
DESCRIPTION:BayBears @ Biscuits\n\nFollow on MiLB First Pitch: https://stza.co/+vLOy-3L\n\nShop: https://stza.co/+vLOy-2S\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144544Z
LAST-MODIFIED:20180213T144544Z
TRANSP:OPAQUE
END:VEVENT
* BayBears @ Biscuits
<2018-04-27 Fri 18:35-21:35>
:PROPERTIES:
:ID:       O9Vt3zUVx8WlJIkZRHRdbrcB@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

BayBears @ Biscuits BayBears @ Biscuits

Follow on MiLB First Pitch  https //stza.co/+vLOz-3x

Shop  https //stza.co/+vLOz-U

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:BayBears @ Biscuits
END:VALARM
DTSTART:20180427T233500Z
DTEND:20180428T023500Z
UID:O9Vt3zUVx8WlJIkZRHRdbrcB@stanza.co
SUMMARY:BayBears @ Biscuits
DESCRIPTION:BayBears @ Biscuits\n\nFollow on MiLB First Pitch: https://stza.co/+vLOz-3x\n\nShop: https://stza.co/+vLOz-U\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144544Z
LAST-MODIFIED:20180213T144544Z
TRANSP:OPAQUE
END:VEVENT
* BayBears @ Biscuits
<2018-04-28 Sat 18:05-21:05>
:PROPERTIES:
:ID:       Sv_gFcHGEhOUL4KxUbzdWVf7@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

BayBears @ Biscuits BayBears @ Biscuits

Follow on MiLB First Pitch  https //stza.co/+vLOA-3F

Shop  https //stza.co/+vLOA-3l

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:BayBears @ Biscuits
END:VALARM
DTSTART:20180428T230500Z
DTEND:20180429T020500Z
UID:Sv_gFcHGEhOUL4KxUbzdWVf7@stanza.co
SUMMARY:BayBears @ Biscuits
DESCRIPTION:BayBears @ Biscuits\n\nFollow on MiLB First Pitch: https://stza.co/+vLOA-3F\n\nShop: https://stza.co/+vLOA-3l\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144544Z
LAST-MODIFIED:20180213T144544Z
TRANSP:OPAQUE
END:VEVENT
* BayBears @ Biscuits
<2018-04-29 Sun 14:05-17:05>
:PROPERTIES:
:ID:       3WYOVPVjVRr9Asginw2sRd8f@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

BayBears @ Biscuits BayBears @ Biscuits

Follow on MiLB First Pitch  https //stza.co/+vLOB-Q

Shop  https //stza.co/+vLOB-r

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:BayBears @ Biscuits
END:VALARM
DTSTART:20180429T190500Z
DTEND:20180429T220500Z
UID:3WYOVPVjVRr9Asginw2sRd8f@stanza.co
SUMMARY:BayBears @ Biscuits
DESCRIPTION:BayBears @ Biscuits\n\nFollow on MiLB First Pitch: https://stza.co/+vLOB-Q\n\nShop: https://stza.co/+vLOB-r\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144544Z
LAST-MODIFIED:20180213T144544Z
TRANSP:OPAQUE
END:VEVENT
* BayBears @ Biscuits
<2018-04-30 Mon 10:35-13:35>
:PROPERTIES:
:ID:       _AiiXa6xopnt15p-8wrWNsdX@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

BayBears @ Biscuits BayBears @ Biscuits

Follow on MiLB First Pitch  https //stza.co/+vLOC-2d

Shop  https //stza.co/+vLOC-F

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:BayBears @ Biscuits
END:VALARM
DTSTART:20180430T153500Z
DTEND:20180430T183500Z
UID:_AiiXa6xopnt15p-8wrWNsdX@stanza.co
SUMMARY:BayBears @ Biscuits
DESCRIPTION:BayBears @ Biscuits\n\nFollow on MiLB First Pitch: https://stza.co/+vLOC-2d\n\nShop: https://stza.co/+vLOC-F\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144544Z
LAST-MODIFIED:20180213T144544Z
TRANSP:OPAQUE
END:VEVENT
* BayBears vs. Lookouts
<2018-05-02 Wed 18:35-21:35>
:PROPERTIES:
:ID:       wnyF7uz4AsftoJVOEk0EtAjW@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

BayBears vs. Lookouts BayBears vs. Lookouts

Follow on MiLB First Pitch  https //stza.co/+v$Qz-1q

Shop  https //stza.co/+v$Qz-B

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:BayBears vs. Lookouts
END:VALARM
DTSTART:20180502T233500Z
DTEND:20180503T023500Z
UID:wnyF7uz4AsftoJVOEk0EtAjW@stanza.co
SUMMARY:BayBears vs. Lookouts
DESCRIPTION:BayBears vs. Lookouts\n\nFollow on MiLB First Pitch: https://stza.co/+v$Qz-1q\n\nShop: https://stza.co/+v$Qz-B\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144544Z
LAST-MODIFIED:20180213T144544Z
TRANSP:OPAQUE
END:VEVENT
* BayBears vs. Lookouts
<2018-05-03 Thu 18:35-21:35>
:PROPERTIES:
:ID:       xvFid0wL74gQ8xjT5iXNIG7x@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

BayBears vs. Lookouts BayBears vs. Lookouts

Follow on MiLB First Pitch  https //stza.co/+v$QB-3Y

Shop  https //stza.co/+v$QB-d

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:BayBears vs. Lookouts
END:VALARM
DTSTART:20180503T233500Z
DTEND:20180504T023500Z
UID:xvFid0wL74gQ8xjT5iXNIG7x@stanza.co
SUMMARY:BayBears vs. Lookouts
DESCRIPTION:BayBears vs. Lookouts\n\nFollow on MiLB First Pitch: https://stza.co/+v$QB-3Y\n\nShop: https://stza.co/+v$QB-d\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144544Z
LAST-MODIFIED:20180213T144544Z
TRANSP:OPAQUE
END:VEVENT
* BayBears vs. Lookouts
<2018-05-04 Fri 19:05-22:05>
:PROPERTIES:
:ID:       Q2kluUFWE91AmcHXE6IRqbQB@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

BayBears vs. Lookouts BayBears vs. Lookouts

Follow on MiLB First Pitch  https //stza.co/+v$QE-23

Shop  https //stza.co/+v$QE-2A

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:BayBears vs. Lookouts
END:VALARM
DTSTART:20180505T000500Z
DTEND:20180505T030500Z
UID:Q2kluUFWE91AmcHXE6IRqbQB@stanza.co
SUMMARY:BayBears vs. Lookouts
DESCRIPTION:BayBears vs. Lookouts\n\nFollow on MiLB First Pitch: https://stza.co/+v$QE-23\n\nShop: https://stza.co/+v$QE-2A\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144544Z
LAST-MODIFIED:20180213T144544Z
TRANSP:OPAQUE
END:VEVENT
* BayBears vs. Lookouts
<2018-05-05 Sat 19:05-22:05>
:PROPERTIES:
:ID:       7QwCqqWiMRNl5kMWSovexprf@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

BayBears vs. Lookouts BayBears vs. Lookouts

Follow on MiLB First Pitch  https //stza.co/+v$QF-9

Shop  https //stza.co/+v$QF-2N

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:BayBears vs. Lookouts
END:VALARM
DTSTART:20180506T000500Z
DTEND:20180506T030500Z
UID:7QwCqqWiMRNl5kMWSovexprf@stanza.co
SUMMARY:BayBears vs. Lookouts
DESCRIPTION:BayBears vs. Lookouts\n\nFollow on MiLB First Pitch: https://stza.co/+v$QF-9\n\nShop: https://stza.co/+v$QF-2N\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144544Z
LAST-MODIFIED:20180213T144544Z
TRANSP:OPAQUE
END:VEVENT
* BayBears vs. Lookouts
<2018-05-06 Sun 14:05-17:05>
:PROPERTIES:
:ID:       mmtmVUbQvttkeyU4a58c-OEB@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

BayBears vs. Lookouts BayBears vs. Lookouts

Follow on MiLB First Pitch  https //stza.co/+v$QI-3L

Shop  https //stza.co/+v$QI-36

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:BayBears vs. Lookouts
END:VALARM
DTSTART:20180506T190500Z
DTEND:20180506T220500Z
UID:mmtmVUbQvttkeyU4a58c-OEB@stanza.co
SUMMARY:BayBears vs. Lookouts
DESCRIPTION:BayBears vs. Lookouts\n\nFollow on MiLB First Pitch: https://stza.co/+v$QI-3L\n\nShop: https://stza.co/+v$QI-36\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144544Z
LAST-MODIFIED:20180213T144544Z
TRANSP:OPAQUE
END:VEVENT
* BayBears @ Braves
<2018-05-07 Mon 19:00-22:00>
:PROPERTIES:
:ID:       s-TrpjxPqtycKifSBkbwwFoc@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

BayBears @ Braves BayBears @ Braves

Follow on MiLB First Pitch  https //stza.co/+vLMc-37

Shop  https //stza.co/+vLMc-l

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:BayBears @ Braves
END:VALARM
DTSTART:20180508T000000Z
DTEND:20180508T030000Z
UID:s-TrpjxPqtycKifSBkbwwFoc@stanza.co
SUMMARY:BayBears @ Braves
DESCRIPTION:BayBears @ Braves\n\nFollow on MiLB First Pitch: https://stza.co/+vLMc-37\n\nShop: https://stza.co/+vLMc-l\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144544Z
LAST-MODIFIED:20180213T144544Z
TRANSP:OPAQUE
END:VEVENT
* BayBears @ Braves
<2018-05-08 Tue 19:00-22:00>
:PROPERTIES:
:ID:       EmpPhEhDFCCUgANEOEdyXEBk@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

BayBears @ Braves BayBears @ Braves

Follow on MiLB First Pitch  https //stza.co/+vLMd-1B

Shop  https //stza.co/+vLMd-28

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:BayBears @ Braves
END:VALARM
DTSTART:20180509T000000Z
DTEND:20180509T030000Z
UID:EmpPhEhDFCCUgANEOEdyXEBk@stanza.co
SUMMARY:BayBears @ Braves
DESCRIPTION:BayBears @ Braves\n\nFollow on MiLB First Pitch: https://stza.co/+vLMd-1B\n\nShop: https://stza.co/+vLMd-28\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144544Z
LAST-MODIFIED:20180213T144544Z
TRANSP:OPAQUE
END:VEVENT
* BayBears @ Braves
<2018-05-09 Wed 10:35-13:35>
:PROPERTIES:
:ID:       UqOLYAXVc_keBwDBZaUKnAV8@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

BayBears @ Braves BayBears @ Braves

Follow on MiLB First Pitch  https //stza.co/+vLMe-2r

Shop  https //stza.co/+vLMe-m

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:BayBears @ Braves
END:VALARM
DTSTART:20180509T153500Z
DTEND:20180509T183500Z
UID:UqOLYAXVc_keBwDBZaUKnAV8@stanza.co
SUMMARY:BayBears @ Braves
DESCRIPTION:BayBears @ Braves\n\nFollow on MiLB First Pitch: https://stza.co/+vLMe-2r\n\nShop: https://stza.co/+vLMe-m\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144544Z
LAST-MODIFIED:20180213T144544Z
TRANSP:OPAQUE
END:VEVENT
* BayBears @ Braves
<2018-05-10 Thu 19:00-22:00>
:PROPERTIES:
:ID:       tHBSENUBdINC98Ti51bod1Ba@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

BayBears @ Braves BayBears @ Braves

Follow on MiLB First Pitch  https //stza.co/+vLMf-3V

Shop  https //stza.co/+vLMf-32

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:BayBears @ Braves
END:VALARM
DTSTART:20180511T000000Z
DTEND:20180511T030000Z
UID:tHBSENUBdINC98Ti51bod1Ba@stanza.co
SUMMARY:BayBears @ Braves
DESCRIPTION:BayBears @ Braves\n\nFollow on MiLB First Pitch: https://stza.co/+vLMf-3V\n\nShop: https://stza.co/+vLMf-32\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144544Z
LAST-MODIFIED:20180213T144544Z
TRANSP:OPAQUE
END:VEVENT
* BayBears @ Braves
<2018-05-11 Fri 19:00-22:00>
:PROPERTIES:
:ID:       YIM5kf2fi7HMlRE5837PGaJv@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

BayBears @ Braves BayBears @ Braves

Follow on MiLB First Pitch  https //stza.co/+vLMg-_

Shop  https //stza.co/+vLMg-e

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:BayBears @ Braves
END:VALARM
DTSTART:20180512T000000Z
DTEND:20180512T030000Z
UID:YIM5kf2fi7HMlRE5837PGaJv@stanza.co
SUMMARY:BayBears @ Braves
DESCRIPTION:BayBears @ Braves\n\nFollow on MiLB First Pitch: https://stza.co/+vLMg-_\n\nShop: https://stza.co/+vLMg-e\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144544Z
LAST-MODIFIED:20180213T144544Z
TRANSP:OPAQUE
END:VEVENT
* BayBears vs. Barons
<2018-05-12 Sat 19:05-22:05>
:PROPERTIES:
:ID:       6ZRTXG1P4PrTuIoykZpj8h5k@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

BayBears vs. Barons BayBears vs. Barons

Follow on MiLB First Pitch  https //stza.co/+v$QK-1t

Shop  https //stza.co/+v$QK-3M

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:BayBears vs. Barons
END:VALARM
DTSTART:20180513T000500Z
DTEND:20180513T030500Z
UID:6ZRTXG1P4PrTuIoykZpj8h5k@stanza.co
SUMMARY:BayBears vs. Barons
DESCRIPTION:BayBears vs. Barons\n\nFollow on MiLB First Pitch: https://stza.co/+v$QK-1t\n\nShop: https://stza.co/+v$QK-3M\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144544Z
LAST-MODIFIED:20180213T144544Z
TRANSP:OPAQUE
END:VEVENT
* BayBears vs. Barons
<2018-05-13 Sun 14:05-17:05>
:PROPERTIES:
:ID:       o-pPGJu84-4lAqoR21A5FHCf@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

BayBears vs. Barons BayBears vs. Barons

Follow on MiLB First Pitch  https //stza.co/+v$QM-39

Shop  https //stza.co/+v$QM-r

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:BayBears vs. Barons
END:VALARM
DTSTART:20180513T190500Z
DTEND:20180513T220500Z
UID:o-pPGJu84-4lAqoR21A5FHCf@stanza.co
SUMMARY:BayBears vs. Barons
DESCRIPTION:BayBears vs. Barons\n\nFollow on MiLB First Pitch: https://stza.co/+v$QM-39\n\nShop: https://stza.co/+v$QM-r\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144544Z
LAST-MODIFIED:20180213T144544Z
TRANSP:OPAQUE
END:VEVENT
* BayBears vs. Barons
<2018-05-14 Mon 18:35-21:35>
:PROPERTIES:
:ID:       1kjUaZCGvwWeqDs0hOH2X60r@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

BayBears vs. Barons BayBears vs. Barons

Follow on MiLB First Pitch  https //stza.co/+v$QO-c

Shop  https //stza.co/+v$QO-2Y

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:BayBears vs. Barons
END:VALARM
DTSTART:20180514T233500Z
DTEND:20180515T023500Z
UID:1kjUaZCGvwWeqDs0hOH2X60r@stanza.co
SUMMARY:BayBears vs. Barons
DESCRIPTION:BayBears vs. Barons\n\nFollow on MiLB First Pitch: https://stza.co/+v$QO-c\n\nShop: https://stza.co/+v$QO-2Y\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144544Z
LAST-MODIFIED:20180213T144544Z
TRANSP:OPAQUE
END:VEVENT
* BayBears vs. Barons
<2018-05-15 Tue 18:35-21:35>
:PROPERTIES:
:ID:       m_nsyg9vfPt6KMwKXtR4Q0Nu@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

BayBears vs. Barons BayBears vs. Barons

Follow on MiLB First Pitch  https //stza.co/+v$QP-2r

Shop  https //stza.co/+v$QP-3B

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:BayBears vs. Barons
END:VALARM
DTSTART:20180515T233500Z
DTEND:20180516T023500Z
UID:m_nsyg9vfPt6KMwKXtR4Q0Nu@stanza.co
SUMMARY:BayBears vs. Barons
DESCRIPTION:BayBears vs. Barons\n\nFollow on MiLB First Pitch: https://stza.co/+v$QP-2r\n\nShop: https://stza.co/+v$QP-3B\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144544Z
LAST-MODIFIED:20180213T144544Z
TRANSP:OPAQUE
END:VEVENT
* BayBears vs. Barons
<2018-05-16 Wed 11:05-14:05>
:PROPERTIES:
:ID:       OUOGj2MXJZrKdAA4UD37ALng@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

BayBears vs. Barons BayBears vs. Barons

Follow on MiLB First Pitch  https //stza.co/+v$QR-3w

Shop  https //stza.co/+v$QR-3C

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:BayBears vs. Barons
END:VALARM
DTSTART:20180516T160500Z
DTEND:20180516T190500Z
UID:OUOGj2MXJZrKdAA4UD37ALng@stanza.co
SUMMARY:BayBears vs. Barons
DESCRIPTION:BayBears vs. Barons\n\nFollow on MiLB First Pitch: https://stza.co/+v$QR-3w\n\nShop: https://stza.co/+v$QR-3C\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144544Z
LAST-MODIFIED:20180213T144544Z
TRANSP:OPAQUE
END:VEVENT
* BayBears @ Jumbo Shrimp
<2018-05-17 Thu 18:05-21:05>
:PROPERTIES:
:ID:       in3yCPU6NgQRtJjNKNVARUju@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

BayBears @ Jumbo Shrimp BayBears @ Jumbo Shrimp

Follow on MiLB First Pitch  https //stza.co/+vLM7-J

Shop  https //stza.co/+vLM7-2v

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:BayBears @ Jumbo Shrimp
END:VALARM
DTSTART:20180517T230500Z
DTEND:20180518T020500Z
UID:in3yCPU6NgQRtJjNKNVARUju@stanza.co
SUMMARY:BayBears @ Jumbo Shrimp
DESCRIPTION:BayBears @ Jumbo Shrimp\n\nFollow on MiLB First Pitch: https://stza.co/+vLM7-J\n\nShop: https://stza.co/+vLM7-2v\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144544Z
LAST-MODIFIED:20180213T144544Z
TRANSP:OPAQUE
END:VEVENT
* BayBears @ Jumbo Shrimp
<2018-05-18 Fri 18:05-21:05>
:PROPERTIES:
:ID:       l-DK5o5MCU8-uuiOCJUcqsQR@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

BayBears @ Jumbo Shrimp BayBears @ Jumbo Shrimp

Follow on MiLB First Pitch  https //stza.co/+vLM8-3D

Shop  https //stza.co/+vLM8-2E

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:BayBears @ Jumbo Shrimp
END:VALARM
DTSTART:20180518T230500Z
DTEND:20180519T020500Z
UID:l-DK5o5MCU8-uuiOCJUcqsQR@stanza.co
SUMMARY:BayBears @ Jumbo Shrimp
DESCRIPTION:BayBears @ Jumbo Shrimp\n\nFollow on MiLB First Pitch: https://stza.co/+vLM8-3D\n\nShop: https://stza.co/+vLM8-2E\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144544Z
LAST-MODIFIED:20180213T144544Z
TRANSP:OPAQUE
END:VEVENT
* BayBears @ Jumbo Shrimp
<2018-05-19 Sat 17:35-20:35>
:PROPERTIES:
:ID:       0iGObPMod12m9tbs0_QTNBRV@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

BayBears @ Jumbo Shrimp BayBears @ Jumbo Shrimp

Follow on MiLB First Pitch  https //stza.co/+vLM9-6

Shop  https //stza.co/+vLM9-2H

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:BayBears @ Jumbo Shrimp
END:VALARM
DTSTART:20180519T223500Z
DTEND:20180520T013500Z
UID:0iGObPMod12m9tbs0_QTNBRV@stanza.co
SUMMARY:BayBears @ Jumbo Shrimp
DESCRIPTION:BayBears @ Jumbo Shrimp\n\nFollow on MiLB First Pitch: https://stza.co/+vLM9-6\n\nShop: https://stza.co/+vLM9-2H\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144544Z
LAST-MODIFIED:20180213T144544Z
TRANSP:OPAQUE
END:VEVENT
* BayBears @ Jumbo Shrimp
<2018-05-20 Sun 14:05-17:05>
:PROPERTIES:
:ID:       3kqje_hZaa9NI4LZ-HtgvSHE@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

BayBears @ Jumbo Shrimp BayBears @ Jumbo Shrimp

Follow on MiLB First Pitch  https //stza.co/+vLMa-3e

Shop  https //stza.co/+vLMa-O

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:BayBears @ Jumbo Shrimp
END:VALARM
DTSTART:20180520T190500Z
DTEND:20180520T220500Z
UID:3kqje_hZaa9NI4LZ-HtgvSHE@stanza.co
SUMMARY:BayBears @ Jumbo Shrimp
DESCRIPTION:BayBears @ Jumbo Shrimp\n\nFollow on MiLB First Pitch: https://stza.co/+vLMa-3e\n\nShop: https://stza.co/+vLMa-O\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144544Z
LAST-MODIFIED:20180213T144544Z
TRANSP:OPAQUE
END:VEVENT
* BayBears @ Jumbo Shrimp
<2018-05-21 Mon 10:05-13:05>
:PROPERTIES:
:ID:       _ZoBnRfRUCVbBt-a4FZi6qDi@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

BayBears @ Jumbo Shrimp BayBears @ Jumbo Shrimp

Follow on MiLB First Pitch  https //stza.co/+vLMb-2x

Shop  https //stza.co/+vLMb-3n

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:BayBears @ Jumbo Shrimp
END:VALARM
DTSTART:20180521T150500Z
DTEND:20180521T180500Z
UID:_ZoBnRfRUCVbBt-a4FZi6qDi@stanza.co
SUMMARY:BayBears @ Jumbo Shrimp
DESCRIPTION:BayBears @ Jumbo Shrimp\n\nFollow on MiLB First Pitch: https://stza.co/+vLMb-2x\n\nShop: https://stza.co/+vLMb-3n\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144544Z
LAST-MODIFIED:20180213T144544Z
TRANSP:OPAQUE
END:VEVENT
* BayBears vs. Shuckers
<2018-05-23 Wed 18:35-21:35>
:PROPERTIES:
:ID:       0G2Bt15Q8SyZDU4hFxWg8lCq@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

BayBears vs. Shuckers BayBears vs. Shuckers

Follow on MiLB First Pitch  https //stza.co/+v$QT-23

Shop  https //stza.co/+v$QT-3M

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:BayBears vs. Shuckers
END:VALARM
DTSTART:20180523T233500Z
DTEND:20180524T023500Z
UID:0G2Bt15Q8SyZDU4hFxWg8lCq@stanza.co
SUMMARY:BayBears vs. Shuckers
DESCRIPTION:BayBears vs. Shuckers\n\nFollow on MiLB First Pitch: https://stza.co/+v$QT-23\n\nShop: https://stza.co/+v$QT-3M\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144544Z
LAST-MODIFIED:20180213T144544Z
TRANSP:OPAQUE
END:VEVENT
* BayBears vs. Shuckers
<2018-05-24 Thu 18:35-21:35>
:PROPERTIES:
:ID:       XdAS7JI46VblQi_NQw4RQl0p@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

BayBears vs. Shuckers BayBears vs. Shuckers

Follow on MiLB First Pitch  https //stza.co/+v$QV-3w

Shop  https //stza.co/+v$QV-2m

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:BayBears vs. Shuckers
END:VALARM
DTSTART:20180524T233500Z
DTEND:20180525T023500Z
UID:XdAS7JI46VblQi_NQw4RQl0p@stanza.co
SUMMARY:BayBears vs. Shuckers
DESCRIPTION:BayBears vs. Shuckers\n\nFollow on MiLB First Pitch: https://stza.co/+v$QV-3w\n\nShop: https://stza.co/+v$QV-2m\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144544Z
LAST-MODIFIED:20180213T144544Z
TRANSP:OPAQUE
END:VEVENT
* BayBears vs. Shuckers
<2018-05-25 Fri 19:05-22:05>
:PROPERTIES:
:ID:       li2_lO8G9PfpvWAlWygpxRra@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

BayBears vs. Shuckers BayBears vs. Shuckers

Follow on MiLB First Pitch  https //stza.co/+v$QX-2g

Shop  https //stza.co/+v$QX-E

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:BayBears vs. Shuckers
END:VALARM
DTSTART:20180526T000500Z
DTEND:20180526T030500Z
UID:li2_lO8G9PfpvWAlWygpxRra@stanza.co
SUMMARY:BayBears vs. Shuckers
DESCRIPTION:BayBears vs. Shuckers\n\nFollow on MiLB First Pitch: https://stza.co/+v$QX-2g\n\nShop: https://stza.co/+v$QX-E\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144544Z
LAST-MODIFIED:20180213T144544Z
TRANSP:OPAQUE
END:VEVENT
* BayBears vs. Shuckers
<2018-05-26 Sat 19:05-22:05>
:PROPERTIES:
:ID:       1cVxADNBrxxbbUpnslDCDQnb@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

BayBears vs. Shuckers BayBears vs. Shuckers

Follow on MiLB First Pitch  https //stza.co/+v$Q_-F

Shop  https //stza.co/+v$Q_-1o

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:BayBears vs. Shuckers
END:VALARM
DTSTART:20180527T000500Z
DTEND:20180527T030500Z
UID:1cVxADNBrxxbbUpnslDCDQnb@stanza.co
SUMMARY:BayBears vs. Shuckers
DESCRIPTION:BayBears vs. Shuckers\n\nFollow on MiLB First Pitch: https://stza.co/+v$Q_-F\n\nShop: https://stza.co/+v$Q_-1o\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144544Z
LAST-MODIFIED:20180213T144544Z
TRANSP:OPAQUE
END:VEVENT
* BayBears vs. Shuckers
<2018-05-27 Sun 14:05-17:05>
:PROPERTIES:
:ID:       F0tn65Iukj-6te49k9uheC83@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

BayBears vs. Shuckers BayBears vs. Shuckers

Follow on MiLB First Pitch  https //stza.co/+v$R0-3s

Shop  https //stza.co/+v$R0-2_

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:BayBears vs. Shuckers
END:VALARM
DTSTART:20180527T190500Z
DTEND:20180527T220500Z
UID:F0tn65Iukj-6te49k9uheC83@stanza.co
SUMMARY:BayBears vs. Shuckers
DESCRIPTION:BayBears vs. Shuckers\n\nFollow on MiLB First Pitch: https://stza.co/+v$R0-3s\n\nShop: https://stza.co/+v$R0-2_\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144544Z
LAST-MODIFIED:20180213T144544Z
TRANSP:OPAQUE
END:VEVENT
* BayBears @ Smokies
<2018-05-29 Tue 18:00-21:00>
:PROPERTIES:
:ID:       UK1VvYWGFcavbBshH5ZXHXcs@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

BayBears @ Smokies BayBears @ Smokies

Follow on MiLB First Pitch  https //stza.co/+xVTJ-I

Shop  https //stza.co/+xVTJ-J

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:BayBears @ Smokies
END:VALARM
DTSTART:20180529T230000Z
DTEND:20180530T020000Z
UID:UK1VvYWGFcavbBshH5ZXHXcs@stanza.co
SUMMARY:BayBears @ Smokies
DESCRIPTION:BayBears @ Smokies\n\nFollow on MiLB First Pitch: https://stza.co/+xVTJ-I\n\nShop: https://stza.co/+xVTJ-J\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144544Z
LAST-MODIFIED:20180213T144544Z
TRANSP:OPAQUE
END:VEVENT
* BayBears @ Smokies
<2018-05-30 Wed 18:00-21:00>
:PROPERTIES:
:ID:       Jo9x7DeiAKo1nSZ8KcTyFOra@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

BayBears @ Smokies BayBears @ Smokies

Follow on MiLB First Pitch  https //stza.co/+xVTK-19

Shop  https //stza.co/+xVTK-I

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:BayBears @ Smokies
END:VALARM
DTSTART:20180530T230000Z
DTEND:20180531T020000Z
UID:Jo9x7DeiAKo1nSZ8KcTyFOra@stanza.co
SUMMARY:BayBears @ Smokies
DESCRIPTION:BayBears @ Smokies\n\nFollow on MiLB First Pitch: https://stza.co/+xVTK-19\n\nShop: https://stza.co/+xVTK-I\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144544Z
LAST-MODIFIED:20180213T144544Z
TRANSP:OPAQUE
END:VEVENT
* BayBears @ Smokies
<2018-05-31 Thu 18:00-21:00>
:PROPERTIES:
:ID:       vKTA_4OQHe7BFU2XFtNy0KW3@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

BayBears @ Smokies BayBears @ Smokies

Follow on MiLB First Pitch  https //stza.co/+xVTL-k

Shop  https //stza.co/+xVTL-3F

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:BayBears @ Smokies
END:VALARM
DTSTART:20180531T230000Z
DTEND:20180601T020000Z
UID:vKTA_4OQHe7BFU2XFtNy0KW3@stanza.co
SUMMARY:BayBears @ Smokies
DESCRIPTION:BayBears @ Smokies\n\nFollow on MiLB First Pitch: https://stza.co/+xVTL-k\n\nShop: https://stza.co/+xVTL-3F\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144544Z
LAST-MODIFIED:20180213T144544Z
TRANSP:OPAQUE
END:VEVENT
* BayBears @ Smokies
<2018-06-01 Fri 18:00-21:00>
:PROPERTIES:
:ID:       oRovsmUE6uSY8eymTar3wy8F@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

BayBears @ Smokies BayBears @ Smokies

Follow on MiLB First Pitch  https //stza.co/+xVTM-39

Shop  https //stza.co/+xVTM-l

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:BayBears @ Smokies
END:VALARM
DTSTART:20180601T230000Z
DTEND:20180602T020000Z
UID:oRovsmUE6uSY8eymTar3wy8F@stanza.co
SUMMARY:BayBears @ Smokies
DESCRIPTION:BayBears @ Smokies\n\nFollow on MiLB First Pitch: https://stza.co/+xVTM-39\n\nShop: https://stza.co/+xVTM-l\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144544Z
LAST-MODIFIED:20180213T144544Z
TRANSP:OPAQUE
END:VEVENT
* BayBears @ Smokies
<2018-06-02 Sat 18:00-21:00>
:PROPERTIES:
:ID:       GXRjj7VKyrqFZ65CSKGozKhh@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

BayBears @ Smokies BayBears @ Smokies

Follow on MiLB First Pitch  https //stza.co/+xVTN-15

Shop  https //stza.co/+xVTN-19

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:BayBears @ Smokies
END:VALARM
DTSTART:20180602T230000Z
DTEND:20180603T020000Z
UID:GXRjj7VKyrqFZ65CSKGozKhh@stanza.co
SUMMARY:BayBears @ Smokies
DESCRIPTION:BayBears @ Smokies\n\nFollow on MiLB First Pitch: https://stza.co/+xVTN-15\n\nShop: https://stza.co/+xVTN-19\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144544Z
LAST-MODIFIED:20180213T144544Z
TRANSP:OPAQUE
END:VEVENT
* BayBears @ Lookouts
<2018-06-03 Sun 16:15-19:15>
:PROPERTIES:
:ID:       Pan3qaaYZtR8s_Bqu4dToiYV@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

BayBears @ Lookouts BayBears @ Lookouts

Follow on MiLB First Pitch  https //stza.co/+wKFt-2H

Shop  https //stza.co/+wKFt-2U

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:BayBears @ Lookouts
END:VALARM
DTSTART:20180603T211500Z
DTEND:20180604T001500Z
UID:Pan3qaaYZtR8s_Bqu4dToiYV@stanza.co
SUMMARY:BayBears @ Lookouts
DESCRIPTION:BayBears @ Lookouts\n\nFollow on MiLB First Pitch: https://stza.co/+wKFt-2H\n\nShop: https://stza.co/+wKFt-2U\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144544Z
LAST-MODIFIED:20180213T144544Z
TRANSP:OPAQUE
END:VEVENT
* BayBears @ Lookouts
<2018-06-04 Mon 18:15-21:15>
:PROPERTIES:
:ID:       l_AgvuMgH1uoNxDWB44rAZ5e@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

BayBears @ Lookouts BayBears @ Lookouts

Follow on MiLB First Pitch  https //stza.co/+wKFu-r

Shop  https //stza.co/+wKFu-j

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:BayBears @ Lookouts
END:VALARM
DTSTART:20180604T231500Z
DTEND:20180605T021500Z
UID:l_AgvuMgH1uoNxDWB44rAZ5e@stanza.co
SUMMARY:BayBears @ Lookouts
DESCRIPTION:BayBears @ Lookouts\n\nFollow on MiLB First Pitch: https://stza.co/+wKFu-r\n\nShop: https://stza.co/+wKFu-j\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144544Z
LAST-MODIFIED:20180213T144544Z
TRANSP:OPAQUE
END:VEVENT
* BayBears @ Lookouts
<2018-06-05 Tue 18:15-21:15>
:PROPERTIES:
:ID:       I8-w01syJLMq3f3qb60cpz7j@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

BayBears @ Lookouts BayBears @ Lookouts

Follow on MiLB First Pitch  https //stza.co/+wKFv-2Q

Shop  https //stza.co/+wKFv-3a

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:BayBears @ Lookouts
END:VALARM
DTSTART:20180605T231500Z
DTEND:20180606T021500Z
UID:I8-w01syJLMq3f3qb60cpz7j@stanza.co
SUMMARY:BayBears @ Lookouts
DESCRIPTION:BayBears @ Lookouts\n\nFollow on MiLB First Pitch: https://stza.co/+wKFv-2Q\n\nShop: https://stza.co/+wKFv-3a\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144544Z
LAST-MODIFIED:20180213T144544Z
TRANSP:OPAQUE
END:VEVENT
* BayBears @ Lookouts
<2018-06-06 Wed 10:15-13:15>
:PROPERTIES:
:ID:       AXK3T8OupxYNrhmpM2r96blK@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

BayBears @ Lookouts BayBears @ Lookouts

Follow on MiLB First Pitch  https //stza.co/+wKFw-V

Shop  https //stza.co/+wKFw-2C

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:BayBears @ Lookouts
END:VALARM
DTSTART:20180606T151500Z
DTEND:20180606T181500Z
UID:AXK3T8OupxYNrhmpM2r96blK@stanza.co
SUMMARY:BayBears @ Lookouts
DESCRIPTION:BayBears @ Lookouts\n\nFollow on MiLB First Pitch: https://stza.co/+wKFw-V\n\nShop: https://stza.co/+wKFw-2C\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144544Z
LAST-MODIFIED:20180213T144544Z
TRANSP:OPAQUE
END:VEVENT
* BayBears @ Lookouts
<2018-06-07 Thu 18:15-21:15>
:PROPERTIES:
:ID:       cogTRbi5h644P1t2qbiQXlOX@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

BayBears @ Lookouts BayBears @ Lookouts

Follow on MiLB First Pitch  https //stza.co/+wKFx-3q

Shop  https //stza.co/+wKFx-38

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:BayBears @ Lookouts
END:VALARM
DTSTART:20180607T231500Z
DTEND:20180608T021500Z
UID:cogTRbi5h644P1t2qbiQXlOX@stanza.co
SUMMARY:BayBears @ Lookouts
DESCRIPTION:BayBears @ Lookouts\n\nFollow on MiLB First Pitch: https://stza.co/+wKFx-3q\n\nShop: https://stza.co/+wKFx-38\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144544Z
LAST-MODIFIED:20180213T144544Z
TRANSP:OPAQUE
END:VEVENT
* BayBears vs. Generals
<2018-06-08 Fri 19:05-22:05>
:PROPERTIES:
:ID:       Yb747R6tqNQk9IHiyv60bviJ@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

BayBears vs. Generals BayBears vs. Generals

Follow on MiLB First Pitch  https //stza.co/+v$R1-1B

Shop  https //stza.co/+v$R1-1r

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:BayBears vs. Generals
END:VALARM
DTSTART:20180609T000500Z
DTEND:20180609T030500Z
UID:Yb747R6tqNQk9IHiyv60bviJ@stanza.co
SUMMARY:BayBears vs. Generals
DESCRIPTION:BayBears vs. Generals\n\nFollow on MiLB First Pitch: https://stza.co/+v$R1-1B\n\nShop: https://stza.co/+v$R1-1r\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144544Z
LAST-MODIFIED:20180213T144544Z
TRANSP:OPAQUE
END:VEVENT
* BayBears vs. Generals
<2018-06-09 Sat 19:05-22:05>
:PROPERTIES:
:ID:       5pEPAT2C_bpPxqrGFsujo6Ge@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

BayBears vs. Generals BayBears vs. Generals

Follow on MiLB First Pitch  https //stza.co/+v$R4-1G

Shop  https //stza.co/+v$R4-K

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:BayBears vs. Generals
END:VALARM
DTSTART:20180610T000500Z
DTEND:20180610T030500Z
UID:5pEPAT2C_bpPxqrGFsujo6Ge@stanza.co
SUMMARY:BayBears vs. Generals
DESCRIPTION:BayBears vs. Generals\n\nFollow on MiLB First Pitch: https://stza.co/+v$R4-1G\n\nShop: https://stza.co/+v$R4-K\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144544Z
LAST-MODIFIED:20180213T144544Z
TRANSP:OPAQUE
END:VEVENT
* BayBears vs. Generals
<2018-06-10 Sun 17:05-20:05>
:PROPERTIES:
:ID:       NER9d203Z6SlqWvMzyKay2We@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

BayBears vs. Generals BayBears vs. Generals

Follow on MiLB First Pitch  https //stza.co/+v$R5-19

Shop  https //stza.co/+v$R5-3u

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:BayBears vs. Generals
END:VALARM
DTSTART:20180610T220500Z
DTEND:20180611T010500Z
UID:NER9d203Z6SlqWvMzyKay2We@stanza.co
SUMMARY:BayBears vs. Generals
DESCRIPTION:BayBears vs. Generals\n\nFollow on MiLB First Pitch: https://stza.co/+v$R5-19\n\nShop: https://stza.co/+v$R5-3u\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144544Z
LAST-MODIFIED:20180213T144544Z
TRANSP:OPAQUE
END:VEVENT
* BayBears vs. Generals
<2018-06-11 Mon 18:35-21:35>
:PROPERTIES:
:ID:       sVdASIo3FYDG9OOdHEEH7_XZ@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

BayBears vs. Generals BayBears vs. Generals

Follow on MiLB First Pitch  https //stza.co/+v$R8-Q

Shop  https //stza.co/+v$R8-W

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:BayBears vs. Generals
END:VALARM
DTSTART:20180611T233500Z
DTEND:20180612T023500Z
UID:sVdASIo3FYDG9OOdHEEH7_XZ@stanza.co
SUMMARY:BayBears vs. Generals
DESCRIPTION:BayBears vs. Generals\n\nFollow on MiLB First Pitch: https://stza.co/+v$R8-Q\n\nShop: https://stza.co/+v$R8-W\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144544Z
LAST-MODIFIED:20180213T144544Z
TRANSP:OPAQUE
END:VEVENT
* BayBears vs. Generals
<2018-06-12 Tue 12:05-15:05>
:PROPERTIES:
:ID:       fRJTQ0DY_x6FOFEwbj-PGsVh@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

BayBears vs. Generals BayBears vs. Generals

Follow on MiLB First Pitch  https //stza.co/+v$R9-3i

Shop  https //stza.co/+v$R9-c

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:BayBears vs. Generals
END:VALARM
DTSTART:20180612T170500Z
DTEND:20180612T200500Z
UID:fRJTQ0DY_x6FOFEwbj-PGsVh@stanza.co
SUMMARY:BayBears vs. Generals
DESCRIPTION:BayBears vs. Generals\n\nFollow on MiLB First Pitch: https://stza.co/+v$R9-3i\n\nShop: https://stza.co/+v$R9-c\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144544Z
LAST-MODIFIED:20180213T144544Z
TRANSP:OPAQUE
END:VEVENT
* BayBears @ Blue Wahoos
<2018-06-13 Wed 18:35-21:35>
:PROPERTIES:
:ID:       EubawxpBnI_7ktzbzUK6icYg@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

BayBears @ Blue Wahoos BayBears @ Blue Wahoos

Follow on MiLB First Pitch  https //stza.co/+wx92-2K

Shop  https //stza.co/+wx92-2_

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:BayBears @ Blue Wahoos
END:VALARM
DTSTART:20180613T233500Z
DTEND:20180614T023500Z
UID:EubawxpBnI_7ktzbzUK6icYg@stanza.co
SUMMARY:BayBears @ Blue Wahoos
DESCRIPTION:BayBears @ Blue Wahoos\n\nFollow on MiLB First Pitch: https://stza.co/+wx92-2K\n\nShop: https://stza.co/+wx92-2_\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144544Z
LAST-MODIFIED:20180213T144544Z
TRANSP:OPAQUE
END:VEVENT
* BayBears @ Blue Wahoos
<2018-06-14 Thu 18:35-21:35>
:PROPERTIES:
:ID:       eX_nPgsKG-AJ-XvEkoQDyyse@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

BayBears @ Blue Wahoos BayBears @ Blue Wahoos

Follow on MiLB First Pitch  https //stza.co/+wx93-1z

Shop  https //stza.co/+wx93-2g

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:BayBears @ Blue Wahoos
END:VALARM
DTSTART:20180614T233500Z
DTEND:20180615T023500Z
UID:eX_nPgsKG-AJ-XvEkoQDyyse@stanza.co
SUMMARY:BayBears @ Blue Wahoos
DESCRIPTION:BayBears @ Blue Wahoos\n\nFollow on MiLB First Pitch: https://stza.co/+wx93-1z\n\nShop: https://stza.co/+wx93-2g\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144544Z
LAST-MODIFIED:20180213T144544Z
TRANSP:OPAQUE
END:VEVENT
* BayBears @ Blue Wahoos
<2018-06-15 Fri 18:35-21:35>
:PROPERTIES:
:ID:       gjOmf9_D492jgwefX-9IEGA8@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

BayBears @ Blue Wahoos BayBears @ Blue Wahoos

Follow on MiLB First Pitch  https //stza.co/+wx94-2v

Shop  https //stza.co/+wx94-2N

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:BayBears @ Blue Wahoos
END:VALARM
DTSTART:20180615T233500Z
DTEND:20180616T023500Z
UID:gjOmf9_D492jgwefX-9IEGA8@stanza.co
SUMMARY:BayBears @ Blue Wahoos
DESCRIPTION:BayBears @ Blue Wahoos\n\nFollow on MiLB First Pitch: https://stza.co/+wx94-2v\n\nShop: https://stza.co/+wx94-2N\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144544Z
LAST-MODIFIED:20180213T144544Z
TRANSP:OPAQUE
END:VEVENT
* BayBears @ Blue Wahoos
<2018-06-16 Sat 18:05-21:05>
:PROPERTIES:
:ID:       8Z-tmv21Qkw4040G7wZyf183@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

BayBears @ Blue Wahoos BayBears @ Blue Wahoos

Follow on MiLB First Pitch  https //stza.co/+wx95-1i

Shop  https //stza.co/+wx95-I

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:BayBears @ Blue Wahoos
END:VALARM
DTSTART:20180616T230500Z
DTEND:20180617T020500Z
UID:8Z-tmv21Qkw4040G7wZyf183@stanza.co
SUMMARY:BayBears @ Blue Wahoos
DESCRIPTION:BayBears @ Blue Wahoos\n\nFollow on MiLB First Pitch: https://stza.co/+wx95-1i\n\nShop: https://stza.co/+wx95-I\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144544Z
LAST-MODIFIED:20180213T144544Z
TRANSP:OPAQUE
END:VEVENT
* BayBears @ Blue Wahoos
<2018-06-17 Sun 17:05-20:05>
:PROPERTIES:
:ID:       I5avF2zhZ5kk6dYPDWp-IG6D@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

BayBears @ Blue Wahoos BayBears @ Blue Wahoos

Follow on MiLB First Pitch  https //stza.co/+wx96-3H

Shop  https //stza.co/+wx96-1y

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:BayBears @ Blue Wahoos
END:VALARM
DTSTART:20180617T220500Z
DTEND:20180618T010500Z
UID:I5avF2zhZ5kk6dYPDWp-IG6D@stanza.co
SUMMARY:BayBears @ Blue Wahoos
DESCRIPTION:BayBears @ Blue Wahoos\n\nFollow on MiLB First Pitch: https://stza.co/+wx96-3H\n\nShop: https://stza.co/+wx96-1y\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144544Z
LAST-MODIFIED:20180213T144544Z
TRANSP:OPAQUE
END:VEVENT
* BayBears vs. Smokies
<2018-06-21 Thu 18:35-21:35>
:PROPERTIES:
:ID:       M2yMIoUnptKjQTOmV5CJoeb8@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

BayBears vs. Smokies BayBears vs. Smokies

Follow on MiLB First Pitch  https //stza.co/+v$Rc-2V

Shop  https //stza.co/+v$Rc-39

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:BayBears vs. Smokies
END:VALARM
DTSTART:20180621T233500Z
DTEND:20180622T023500Z
UID:M2yMIoUnptKjQTOmV5CJoeb8@stanza.co
SUMMARY:BayBears vs. Smokies
DESCRIPTION:BayBears vs. Smokies\n\nFollow on MiLB First Pitch: https://stza.co/+v$Rc-2V\n\nShop: https://stza.co/+v$Rc-39\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144544Z
LAST-MODIFIED:20180213T144544Z
TRANSP:OPAQUE
END:VEVENT
* BayBears vs. Smokies
<2018-06-22 Fri 19:05-22:05>
:PROPERTIES:
:ID:       071MFPaICX2-rdkwzjzLcFVo@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

BayBears vs. Smokies BayBears vs. Smokies

Follow on MiLB First Pitch  https //stza.co/+v$Re-3G

Shop  https //stza.co/+v$Re-1W

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:BayBears vs. Smokies
END:VALARM
DTSTART:20180623T000500Z
DTEND:20180623T030500Z
UID:071MFPaICX2-rdkwzjzLcFVo@stanza.co
SUMMARY:BayBears vs. Smokies
DESCRIPTION:BayBears vs. Smokies\n\nFollow on MiLB First Pitch: https://stza.co/+v$Re-3G\n\nShop: https://stza.co/+v$Re-1W\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144544Z
LAST-MODIFIED:20180213T144544Z
TRANSP:OPAQUE
END:VEVENT
* BayBears vs. Smokies
<2018-06-23 Sat 19:05-22:05>
:PROPERTIES:
:ID:       VsIMI-mVDQNPYajVLTMgLJSO@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

BayBears vs. Smokies BayBears vs. Smokies

Follow on MiLB First Pitch  https //stza.co/+v$Rg-F

Shop  https //stza.co/+v$Rg-1R

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:BayBears vs. Smokies
END:VALARM
DTSTART:20180624T000500Z
DTEND:20180624T030500Z
UID:VsIMI-mVDQNPYajVLTMgLJSO@stanza.co
SUMMARY:BayBears vs. Smokies
DESCRIPTION:BayBears vs. Smokies\n\nFollow on MiLB First Pitch: https://stza.co/+v$Rg-F\n\nShop: https://stza.co/+v$Rg-1R\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144544Z
LAST-MODIFIED:20180213T144544Z
TRANSP:OPAQUE
END:VEVENT
* BayBears vs. Smokies
<2018-06-24 Sun 17:05-20:05>
:PROPERTIES:
:ID:       y9N8Qqsn7ARV2jHCDBsFIHOV@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

BayBears vs. Smokies BayBears vs. Smokies

Follow on MiLB First Pitch  https //stza.co/+v$Ri-3O

Shop  https //stza.co/+v$Ri-2h

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:BayBears vs. Smokies
END:VALARM
DTSTART:20180624T220500Z
DTEND:20180625T010500Z
UID:y9N8Qqsn7ARV2jHCDBsFIHOV@stanza.co
SUMMARY:BayBears vs. Smokies
DESCRIPTION:BayBears vs. Smokies\n\nFollow on MiLB First Pitch: https://stza.co/+v$Ri-3O\n\nShop: https://stza.co/+v$Ri-2h\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144544Z
LAST-MODIFIED:20180213T144544Z
TRANSP:OPAQUE
END:VEVENT
* BayBears vs. Smokies
<2018-06-25 Mon 18:35-21:35>
:PROPERTIES:
:ID:       adAWWnUjNds8cqiX_YAIJrow@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

BayBears vs. Smokies BayBears vs. Smokies

Follow on MiLB First Pitch  https //stza.co/+v$Rk-2Q

Shop  https //stza.co/+v$Rk-2v

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:BayBears vs. Smokies
END:VALARM
DTSTART:20180625T233500Z
DTEND:20180626T023500Z
UID:adAWWnUjNds8cqiX_YAIJrow@stanza.co
SUMMARY:BayBears vs. Smokies
DESCRIPTION:BayBears vs. Smokies\n\nFollow on MiLB First Pitch: https://stza.co/+v$Rk-2Q\n\nShop: https://stza.co/+v$Rk-2v\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144544Z
LAST-MODIFIED:20180213T144544Z
TRANSP:OPAQUE
END:VEVENT
* BayBears vs. Smokies
<2018-06-26 Tue 18:35-21:35>
:PROPERTIES:
:ID:       h3VBIqRTY7LuStpKvV1YmTRu@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

BayBears vs. Smokies BayBears vs. Smokies

Follow on MiLB First Pitch  https //stza.co/+v$Rl-34

Shop  https //stza.co/+v$Rl-2q

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:BayBears vs. Smokies
END:VALARM
DTSTART:20180626T233500Z
DTEND:20180627T023500Z
UID:h3VBIqRTY7LuStpKvV1YmTRu@stanza.co
SUMMARY:BayBears vs. Smokies
DESCRIPTION:BayBears vs. Smokies\n\nFollow on MiLB First Pitch: https://stza.co/+v$Rl-34\n\nShop: https://stza.co/+v$Rl-2q\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144544Z
LAST-MODIFIED:20180213T144544Z
TRANSP:OPAQUE
END:VEVENT
* BayBears @ Shuckers
<2018-06-28 Thu 18:35-21:35>
:PROPERTIES:
:ID:       YTh3LqZ0h6-ail_2vcz-cyYP@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

BayBears @ Shuckers BayBears @ Shuckers

Follow on MiLB First Pitch  https //stza.co/+vLLE-3s

Shop  https //stza.co/+vLLE-D

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:BayBears @ Shuckers
END:VALARM
DTSTART:20180628T233500Z
DTEND:20180629T023500Z
UID:YTh3LqZ0h6-ail_2vcz-cyYP@stanza.co
SUMMARY:BayBears @ Shuckers
DESCRIPTION:BayBears @ Shuckers\n\nFollow on MiLB First Pitch: https://stza.co/+vLLE-3s\n\nShop: https://stza.co/+vLLE-D\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144544Z
LAST-MODIFIED:20180213T144544Z
TRANSP:OPAQUE
END:VEVENT
* BayBears @ Shuckers
<2018-06-29 Fri 18:35-21:35>
:PROPERTIES:
:ID:       LJs40bMxUTYUwZchlw47vP0G@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

BayBears @ Shuckers BayBears @ Shuckers

Follow on MiLB First Pitch  https //stza.co/+vLLF-2V

Shop  https //stza.co/+vLLF-2o

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:BayBears @ Shuckers
END:VALARM
DTSTART:20180629T233500Z
DTEND:20180630T023500Z
UID:LJs40bMxUTYUwZchlw47vP0G@stanza.co
SUMMARY:BayBears @ Shuckers
DESCRIPTION:BayBears @ Shuckers\n\nFollow on MiLB First Pitch: https://stza.co/+vLLF-2V\n\nShop: https://stza.co/+vLLF-2o\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144544Z
LAST-MODIFIED:20180213T144544Z
TRANSP:OPAQUE
END:VEVENT
* BayBears @ Shuckers
<2018-06-30 Sat 18:35-21:35>
:PROPERTIES:
:ID:       BtCmeyBJxJTShBV4vzC7GPrb@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

BayBears @ Shuckers BayBears @ Shuckers

Follow on MiLB First Pitch  https //stza.co/+vLLG-e

Shop  https //stza.co/+vLLG-2B

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:BayBears @ Shuckers
END:VALARM
DTSTART:20180630T233500Z
DTEND:20180701T023500Z
UID:BtCmeyBJxJTShBV4vzC7GPrb@stanza.co
SUMMARY:BayBears @ Shuckers
DESCRIPTION:BayBears @ Shuckers\n\nFollow on MiLB First Pitch: https://stza.co/+vLLG-e\n\nShop: https://stza.co/+vLLG-2B\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144544Z
LAST-MODIFIED:20180213T144544Z
TRANSP:OPAQUE
END:VEVENT
* BayBears @ Shuckers
<2018-07-01 Sun 16:05-19:05>
:PROPERTIES:
:ID:       KTLUERf7UHx5eJAzwO9kZot7@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

BayBears @ Shuckers BayBears @ Shuckers

Follow on MiLB First Pitch  https //stza.co/+vLLH-2u

Shop  https //stza.co/+vLLH-O

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:BayBears @ Shuckers
END:VALARM
DTSTART:20180701T210500Z
DTEND:20180702T000500Z
UID:KTLUERf7UHx5eJAzwO9kZot7@stanza.co
SUMMARY:BayBears @ Shuckers
DESCRIPTION:BayBears @ Shuckers\n\nFollow on MiLB First Pitch: https://stza.co/+vLLH-2u\n\nShop: https://stza.co/+vLLH-O\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144544Z
LAST-MODIFIED:20180213T144544Z
TRANSP:OPAQUE
END:VEVENT
* BayBears @ Shuckers
<2018-07-02 Mon 18:35-21:35>
:PROPERTIES:
:ID:       P5k_-zAyUwUTyOu2okSlky-h@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

BayBears @ Shuckers BayBears @ Shuckers

Follow on MiLB First Pitch  https //stza.co/+vLLI-2p

Shop  https //stza.co/+vLLI-3o

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:BayBears @ Shuckers
END:VALARM
DTSTART:20180702T233500Z
DTEND:20180703T023500Z
UID:P5k_-zAyUwUTyOu2okSlky-h@stanza.co
SUMMARY:BayBears @ Shuckers
DESCRIPTION:BayBears @ Shuckers\n\nFollow on MiLB First Pitch: https://stza.co/+vLLI-2p\n\nShop: https://stza.co/+vLLI-3o\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144544Z
LAST-MODIFIED:20180213T144544Z
TRANSP:OPAQUE
END:VEVENT
* BayBears @ Shuckers
<2018-07-03 Tue 18:35-21:35>
:PROPERTIES:
:ID:       cvQvgPiOwEEeccbzKTMoO6H1@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

BayBears @ Shuckers BayBears @ Shuckers

Follow on MiLB First Pitch  https //stza.co/+vLLJ-2z

Shop  https //stza.co/+vLLJ-21

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:BayBears @ Shuckers
END:VALARM
DTSTART:20180703T233500Z
DTEND:20180704T023500Z
UID:cvQvgPiOwEEeccbzKTMoO6H1@stanza.co
SUMMARY:BayBears @ Shuckers
DESCRIPTION:BayBears @ Shuckers\n\nFollow on MiLB First Pitch: https://stza.co/+vLLJ-2z\n\nShop: https://stza.co/+vLLJ-21\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144544Z
LAST-MODIFIED:20180213T144544Z
TRANSP:OPAQUE
END:VEVENT
* BayBears vs. Jumbo Shrimp
<2018-07-04 Wed 18:35-21:35>
:PROPERTIES:
:ID:       AmmyxU7_rSH1GvbLdsepAAaO@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

BayBears vs. Jumbo Shrimp BayBears vs. Jumbo Shrimp

Follow on MiLB First Pitch  https //stza.co/+v$Rn-C

Shop  https //stza.co/+v$Rn-1U

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:BayBears vs. Jumbo Shrimp
END:VALARM
DTSTART:20180704T233500Z
DTEND:20180705T023500Z
UID:AmmyxU7_rSH1GvbLdsepAAaO@stanza.co
SUMMARY:BayBears vs. Jumbo Shrimp
DESCRIPTION:BayBears vs. Jumbo Shrimp\n\nFollow on MiLB First Pitch: https://stza.co/+v$Rn-C\n\nShop: https://stza.co/+v$Rn-1U\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144544Z
LAST-MODIFIED:20180213T144544Z
TRANSP:OPAQUE
END:VEVENT
* BayBears vs. Jumbo Shrimp
<2018-07-05 Thu 18:35-21:35>
:PROPERTIES:
:ID:       -G1XyYXIXltaZ4HUTkoAeLew@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

BayBears vs. Jumbo Shrimp BayBears vs. Jumbo Shrimp

Follow on MiLB First Pitch  https //stza.co/+v$Rp-U

Shop  https //stza.co/+v$Rp-3k

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:BayBears vs. Jumbo Shrimp
END:VALARM
DTSTART:20180705T233500Z
DTEND:20180706T023500Z
UID:-G1XyYXIXltaZ4HUTkoAeLew@stanza.co
SUMMARY:BayBears vs. Jumbo Shrimp
DESCRIPTION:BayBears vs. Jumbo Shrimp\n\nFollow on MiLB First Pitch: https://stza.co/+v$Rp-U\n\nShop: https://stza.co/+v$Rp-3k\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144544Z
LAST-MODIFIED:20180213T144544Z
TRANSP:OPAQUE
END:VEVENT
* BayBears vs. Jumbo Shrimp
<2018-07-06 Fri 19:05-22:05>
:PROPERTIES:
:ID:       2yhv_MTWpP9d8JPDbSY8EV-A@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

BayBears vs. Jumbo Shrimp BayBears vs. Jumbo Shrimp

Follow on MiLB First Pitch  https //stza.co/+v$Rr-2b

Shop  https //stza.co/+v$Rr-2q

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:BayBears vs. Jumbo Shrimp
END:VALARM
DTSTART:20180707T000500Z
DTEND:20180707T030500Z
UID:2yhv_MTWpP9d8JPDbSY8EV-A@stanza.co
SUMMARY:BayBears vs. Jumbo Shrimp
DESCRIPTION:BayBears vs. Jumbo Shrimp\n\nFollow on MiLB First Pitch: https://stza.co/+v$Rr-2b\n\nShop: https://stza.co/+v$Rr-2q\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144544Z
LAST-MODIFIED:20180213T144544Z
TRANSP:OPAQUE
END:VEVENT
* BayBears vs. Jumbo Shrimp
<2018-07-07 Sat 19:05-22:05>
:PROPERTIES:
:ID:       1HklWaeuF1ohcQLLKwHzl3zb@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

BayBears vs. Jumbo Shrimp BayBears vs. Jumbo Shrimp

Follow on MiLB First Pitch  https //stza.co/+v$Rt-g

Shop  https //stza.co/+v$Rt-

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:BayBears vs. Jumbo Shrimp
END:VALARM
DTSTART:20180708T000500Z
DTEND:20180708T030500Z
UID:1HklWaeuF1ohcQLLKwHzl3zb@stanza.co
SUMMARY:BayBears vs. Jumbo Shrimp
DESCRIPTION:BayBears vs. Jumbo Shrimp\n\nFollow on MiLB First Pitch: https://stza.co/+v$Rt-g\n\nShop: https://stza.co/+v$Rt-\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144544Z
LAST-MODIFIED:20180213T144544Z
TRANSP:OPAQUE
END:VEVENT
* BayBears @ Blue Wahoos
<2018-07-08 Sun 17:05-20:05>
:PROPERTIES:
:ID:       -PFiUO73Wxah4oqtpHUKBC33@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

BayBears @ Blue Wahoos BayBears @ Blue Wahoos

Follow on MiLB First Pitch  https //stza.co/+wx97-2T

Shop  https //stza.co/+wx97-2U

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:BayBears @ Blue Wahoos
END:VALARM
DTSTART:20180708T220500Z
DTEND:20180709T010500Z
UID:-PFiUO73Wxah4oqtpHUKBC33@stanza.co
SUMMARY:BayBears @ Blue Wahoos
DESCRIPTION:BayBears @ Blue Wahoos\n\nFollow on MiLB First Pitch: https://stza.co/+wx97-2T\n\nShop: https://stza.co/+wx97-2U\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144544Z
LAST-MODIFIED:20180213T144544Z
TRANSP:OPAQUE
END:VEVENT
* BayBears @ Blue Wahoos
<2018-07-09 Mon 18:35-21:35>
:PROPERTIES:
:ID:       HnUPq2iwSKbu88nKFrqg8cxH@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

BayBears @ Blue Wahoos BayBears @ Blue Wahoos

Follow on MiLB First Pitch  https //stza.co/+wx99-3t

Shop  https //stza.co/+wx99-$

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:BayBears @ Blue Wahoos
END:VALARM
DTSTART:20180709T233500Z
DTEND:20180710T023500Z
UID:HnUPq2iwSKbu88nKFrqg8cxH@stanza.co
SUMMARY:BayBears @ Blue Wahoos
DESCRIPTION:BayBears @ Blue Wahoos\n\nFollow on MiLB First Pitch: https://stza.co/+wx99-3t\n\nShop: https://stza.co/+wx99-$\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144544Z
LAST-MODIFIED:20180213T144544Z
TRANSP:OPAQUE
END:VEVENT
* BayBears @ Blue Wahoos
<2018-07-10 Tue 18:35-21:35>
:PROPERTIES:
:ID:       lGJBImpd-_bo6V9TuiRqsxmL@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

BayBears @ Blue Wahoos BayBears @ Blue Wahoos

Follow on MiLB First Pitch  https //stza.co/+wx9a-18

Shop  https //stza.co/+wx9a-2v

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:BayBears @ Blue Wahoos
END:VALARM
DTSTART:20180710T233500Z
DTEND:20180711T023500Z
UID:lGJBImpd-_bo6V9TuiRqsxmL@stanza.co
SUMMARY:BayBears @ Blue Wahoos
DESCRIPTION:BayBears @ Blue Wahoos\n\nFollow on MiLB First Pitch: https://stza.co/+wx9a-18\n\nShop: https://stza.co/+wx9a-2v\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144544Z
LAST-MODIFIED:20180213T144544Z
TRANSP:OPAQUE
END:VEVENT
* BayBears @ Blue Wahoos
<2018-07-11 Wed 18:35-21:35>
:PROPERTIES:
:ID:       39vg7axENmxqEm23-2tVlHW2@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

BayBears @ Blue Wahoos BayBears @ Blue Wahoos

Follow on MiLB First Pitch  https //stza.co/+wx9b-P

Shop  https //stza.co/+wx9b-1Y

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:BayBears @ Blue Wahoos
END:VALARM
DTSTART:20180711T233500Z
DTEND:20180712T023500Z
UID:39vg7axENmxqEm23-2tVlHW2@stanza.co
SUMMARY:BayBears @ Blue Wahoos
DESCRIPTION:BayBears @ Blue Wahoos\n\nFollow on MiLB First Pitch: https://stza.co/+wx9b-P\n\nShop: https://stza.co/+wx9b-1Y\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144544Z
LAST-MODIFIED:20180213T144544Z
TRANSP:OPAQUE
END:VEVENT
* BayBears @ Generals
<2018-07-12 Thu 18:05-21:05>
:PROPERTIES:
:ID:       Kjo8yPKuYkoRdtJpVTyON1JI@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

BayBears @ Generals BayBears @ Generals

Follow on MiLB First Pitch  https //stza.co/+wCRB-11

Shop  https //stza.co/+wCRB-2K

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:BayBears @ Generals
END:VALARM
DTSTART:20180712T230500Z
DTEND:20180713T020500Z
UID:Kjo8yPKuYkoRdtJpVTyON1JI@stanza.co
SUMMARY:BayBears @ Generals
DESCRIPTION:BayBears @ Generals\n\nFollow on MiLB First Pitch: https://stza.co/+wCRB-11\n\nShop: https://stza.co/+wCRB-2K\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144544Z
LAST-MODIFIED:20180213T144544Z
TRANSP:OPAQUE
END:VEVENT
* BayBears @ Generals
<2018-07-13 Fri 18:05-21:05>
:PROPERTIES:
:ID:       qPgbXqbZScWUnaAVV5cKWGqB@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

BayBears @ Generals BayBears @ Generals

Follow on MiLB First Pitch  https //stza.co/+wCRC-3c

Shop  https //stza.co/+wCRC-1g

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:BayBears @ Generals
END:VALARM
DTSTART:20180713T230500Z
DTEND:20180714T020500Z
UID:qPgbXqbZScWUnaAVV5cKWGqB@stanza.co
SUMMARY:BayBears @ Generals
DESCRIPTION:BayBears @ Generals\n\nFollow on MiLB First Pitch: https://stza.co/+wCRC-3c\n\nShop: https://stza.co/+wCRC-1g\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144544Z
LAST-MODIFIED:20180213T144544Z
TRANSP:OPAQUE
END:VEVENT
* BayBears @ Generals
<2018-07-14 Sat 18:05-21:05>
:PROPERTIES:
:ID:       rC2kFZ8NY2wKGZyaP7APimi8@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

BayBears @ Generals BayBears @ Generals

Follow on MiLB First Pitch  https //stza.co/+wCRD-2S

Shop  https //stza.co/+wCRD-3j

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:BayBears @ Generals
END:VALARM
DTSTART:20180714T230500Z
DTEND:20180715T020500Z
UID:rC2kFZ8NY2wKGZyaP7APimi8@stanza.co
SUMMARY:BayBears @ Generals
DESCRIPTION:BayBears @ Generals\n\nFollow on MiLB First Pitch: https://stza.co/+wCRD-2S\n\nShop: https://stza.co/+wCRD-3j\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144544Z
LAST-MODIFIED:20180213T144544Z
TRANSP:OPAQUE
END:VEVENT
* BayBears @ Generals
<2018-07-15 Sun 18:05-21:05>
:PROPERTIES:
:ID:       IDOOsoGviPczFvUH5PGpbQZI@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

BayBears @ Generals BayBears @ Generals

Follow on MiLB First Pitch  https //stza.co/+wCRE-3V

Shop  https //stza.co/+wCRE-2Z

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:BayBears @ Generals
END:VALARM
DTSTART:20180715T230500Z
DTEND:20180716T020500Z
UID:IDOOsoGviPczFvUH5PGpbQZI@stanza.co
SUMMARY:BayBears @ Generals
DESCRIPTION:BayBears @ Generals\n\nFollow on MiLB First Pitch: https://stza.co/+wCRE-3V\n\nShop: https://stza.co/+wCRE-2Z\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144544Z
LAST-MODIFIED:20180213T144544Z
TRANSP:OPAQUE
END:VEVENT
* BayBears @ Generals
<2018-07-16 Mon 18:05-21:05>
:PROPERTIES:
:ID:       EzA1T_j-k1Q9gHUj2fHa8Gig@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

BayBears @ Generals BayBears @ Generals

Follow on MiLB First Pitch  https //stza.co/+wCRF-1r

Shop  https //stza.co/+wCRF-2v

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:BayBears @ Generals
END:VALARM
DTSTART:20180716T230500Z
DTEND:20180717T020500Z
UID:EzA1T_j-k1Q9gHUj2fHa8Gig@stanza.co
SUMMARY:BayBears @ Generals
DESCRIPTION:BayBears @ Generals\n\nFollow on MiLB First Pitch: https://stza.co/+wCRF-1r\n\nShop: https://stza.co/+wCRF-2v\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144544Z
LAST-MODIFIED:20180213T144544Z
TRANSP:OPAQUE
END:VEVENT
* BayBears vs. Lookouts
<2018-07-18 Wed 18:35-21:35>
:PROPERTIES:
:ID:       -gom7nH8sxiMyjHS1PcWo-3d@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

BayBears vs. Lookouts BayBears vs. Lookouts

Follow on MiLB First Pitch  https //stza.co/+v$Rv-1G

Shop  https //stza.co/+v$Rv-2c

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:BayBears vs. Lookouts
END:VALARM
DTSTART:20180718T233500Z
DTEND:20180719T023500Z
UID:-gom7nH8sxiMyjHS1PcWo-3d@stanza.co
SUMMARY:BayBears vs. Lookouts
DESCRIPTION:BayBears vs. Lookouts\n\nFollow on MiLB First Pitch: https://stza.co/+v$Rv-1G\n\nShop: https://stza.co/+v$Rv-2c\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144544Z
LAST-MODIFIED:20180213T144544Z
TRANSP:OPAQUE
END:VEVENT
* BayBears vs. Lookouts
<2018-07-19 Thu 18:35-21:35>
:PROPERTIES:
:ID:       P7TnLuEbaGSLJDc1z4_TMxIK@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

BayBears vs. Lookouts BayBears vs. Lookouts

Follow on MiLB First Pitch  https //stza.co/+v$Ry-3x

Shop  https //stza.co/+v$Ry-14

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:BayBears vs. Lookouts
END:VALARM
DTSTART:20180719T233500Z
DTEND:20180720T023500Z
UID:P7TnLuEbaGSLJDc1z4_TMxIK@stanza.co
SUMMARY:BayBears vs. Lookouts
DESCRIPTION:BayBears vs. Lookouts\n\nFollow on MiLB First Pitch: https://stza.co/+v$Ry-3x\n\nShop: https://stza.co/+v$Ry-14\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144544Z
LAST-MODIFIED:20180213T144544Z
TRANSP:OPAQUE
END:VEVENT
* BayBears vs. Lookouts
<2018-07-20 Fri 19:05-22:05>
:PROPERTIES:
:ID:       yLKVRtiG-O6Rg8dYhBqFajib@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

BayBears vs. Lookouts BayBears vs. Lookouts

Follow on MiLB First Pitch  https //stza.co/+v$RA-r

Shop  https //stza.co/+v$RA-3u

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:BayBears vs. Lookouts
END:VALARM
DTSTART:20180721T000500Z
DTEND:20180721T030500Z
UID:yLKVRtiG-O6Rg8dYhBqFajib@stanza.co
SUMMARY:BayBears vs. Lookouts
DESCRIPTION:BayBears vs. Lookouts\n\nFollow on MiLB First Pitch: https://stza.co/+v$RA-r\n\nShop: https://stza.co/+v$RA-3u\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144544Z
LAST-MODIFIED:20180213T144544Z
TRANSP:OPAQUE
END:VEVENT
* BayBears vs. Lookouts
<2018-07-21 Sat 19:05-22:05>
:PROPERTIES:
:ID:       tUJ3cLskDTY2itP91kbZE9ej@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

BayBears vs. Lookouts BayBears vs. Lookouts

Follow on MiLB First Pitch  https //stza.co/+v$RC-3t

Shop  https //stza.co/+v$RC-K

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:BayBears vs. Lookouts
END:VALARM
DTSTART:20180722T000500Z
DTEND:20180722T030500Z
UID:tUJ3cLskDTY2itP91kbZE9ej@stanza.co
SUMMARY:BayBears vs. Lookouts
DESCRIPTION:BayBears vs. Lookouts\n\nFollow on MiLB First Pitch: https://stza.co/+v$RC-3t\n\nShop: https://stza.co/+v$RC-K\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144544Z
LAST-MODIFIED:20180213T144544Z
TRANSP:OPAQUE
END:VEVENT
* BayBears vs. Lookouts
<2018-07-22 Sun 17:05-20:05>
:PROPERTIES:
:ID:       tMhRogCVFMSedFqV7nq4iVKb@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

BayBears vs. Lookouts BayBears vs. Lookouts

Follow on MiLB First Pitch  https //stza.co/+v$RD-2U

Shop  https //stza.co/+v$RD-v

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:BayBears vs. Lookouts
END:VALARM
DTSTART:20180722T220500Z
DTEND:20180723T010500Z
UID:tMhRogCVFMSedFqV7nq4iVKb@stanza.co
SUMMARY:BayBears vs. Lookouts
DESCRIPTION:BayBears vs. Lookouts\n\nFollow on MiLB First Pitch: https://stza.co/+v$RD-2U\n\nShop: https://stza.co/+v$RD-v\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144544Z
LAST-MODIFIED:20180213T144544Z
TRANSP:OPAQUE
END:VEVENT
* BayBears @ Braves
<2018-07-23 Mon 19:00-22:00>
:PROPERTIES:
:ID:       etVfomhY0E1iljWtwXuMS9dX@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

BayBears @ Braves BayBears @ Braves

Follow on MiLB First Pitch  https //stza.co/+vLMh-1I

Shop  https //stza.co/+vLMh-26

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:BayBears @ Braves
END:VALARM
DTSTART:20180724T000000Z
DTEND:20180724T030000Z
UID:etVfomhY0E1iljWtwXuMS9dX@stanza.co
SUMMARY:BayBears @ Braves
DESCRIPTION:BayBears @ Braves\n\nFollow on MiLB First Pitch: https://stza.co/+vLMh-1I\n\nShop: https://stza.co/+vLMh-26\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144544Z
LAST-MODIFIED:20180213T144544Z
TRANSP:OPAQUE
END:VEVENT
* BayBears @ Braves
<2018-07-24 Tue 19:00-22:00>
:PROPERTIES:
:ID:       AtG3aYMINQDkT9x6cVY_RmJC@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

BayBears @ Braves BayBears @ Braves

Follow on MiLB First Pitch  https //stza.co/+vLMi-Z

Shop  https //stza.co/+vLMi-24

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:BayBears @ Braves
END:VALARM
DTSTART:20180725T000000Z
DTEND:20180725T030000Z
UID:AtG3aYMINQDkT9x6cVY_RmJC@stanza.co
SUMMARY:BayBears @ Braves
DESCRIPTION:BayBears @ Braves\n\nFollow on MiLB First Pitch: https://stza.co/+vLMi-Z\n\nShop: https://stza.co/+vLMi-24\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144544Z
LAST-MODIFIED:20180213T144544Z
TRANSP:OPAQUE
END:VEVENT
* BayBears @ Braves
<2018-07-25 Wed 19:00-22:00>
:PROPERTIES:
:ID:       eX1hkC31OSUsGGa0_uzI5a8d@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

BayBears @ Braves BayBears @ Braves

Follow on MiLB First Pitch  https //stza.co/+vLMj-2q

Shop  https //stza.co/+vLMj-2Y

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:BayBears @ Braves
END:VALARM
DTSTART:20180726T000000Z
DTEND:20180726T030000Z
UID:eX1hkC31OSUsGGa0_uzI5a8d@stanza.co
SUMMARY:BayBears @ Braves
DESCRIPTION:BayBears @ Braves\n\nFollow on MiLB First Pitch: https://stza.co/+vLMj-2q\n\nShop: https://stza.co/+vLMj-2Y\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144544Z
LAST-MODIFIED:20180213T144544Z
TRANSP:OPAQUE
END:VEVENT
* BayBears @ Braves
<2018-07-26 Thu 19:00-22:00>
:PROPERTIES:
:ID:       HP5uravTcHEQPUmaczNkBePa@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

BayBears @ Braves BayBears @ Braves

Follow on MiLB First Pitch  https //stza.co/+vLMk-2G

Shop  https //stza.co/+vLMk-2a

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:BayBears @ Braves
END:VALARM
DTSTART:20180727T000000Z
DTEND:20180727T030000Z
UID:HP5uravTcHEQPUmaczNkBePa@stanza.co
SUMMARY:BayBears @ Braves
DESCRIPTION:BayBears @ Braves\n\nFollow on MiLB First Pitch: https://stza.co/+vLMk-2G\n\nShop: https://stza.co/+vLMk-2a\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144544Z
LAST-MODIFIED:20180213T144544Z
TRANSP:OPAQUE
END:VEVENT
* BayBears @ Braves
<2018-07-27 Fri 19:00-22:00>
:PROPERTIES:
:ID:       AHciEYN23rI-zvfVyAzplild@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

BayBears @ Braves BayBears @ Braves

Follow on MiLB First Pitch  https //stza.co/+vLMl-1w

Shop  https //stza.co/+vLMl-1M

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:BayBears @ Braves
END:VALARM
DTSTART:20180728T000000Z
DTEND:20180728T030000Z
UID:AHciEYN23rI-zvfVyAzplild@stanza.co
SUMMARY:BayBears @ Braves
DESCRIPTION:BayBears @ Braves\n\nFollow on MiLB First Pitch: https://stza.co/+vLMl-1w\n\nShop: https://stza.co/+vLMl-1M\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144544Z
LAST-MODIFIED:20180213T144544Z
TRANSP:OPAQUE
END:VEVENT
* BayBears vs. Jumbo Shrimp
<2018-07-28 Sat 19:05-22:05>
:PROPERTIES:
:ID:       MYiKXjLmDVrYCrhYdSHzBCs5@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

BayBears vs. Jumbo Shrimp BayBears vs. Jumbo Shrimp

Follow on MiLB First Pitch  https //stza.co/+v$RG-3z

Shop  https //stza.co/+v$RG-35

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:BayBears vs. Jumbo Shrimp
END:VALARM
DTSTART:20180729T000500Z
DTEND:20180729T030500Z
UID:MYiKXjLmDVrYCrhYdSHzBCs5@stanza.co
SUMMARY:BayBears vs. Jumbo Shrimp
DESCRIPTION:BayBears vs. Jumbo Shrimp\n\nFollow on MiLB First Pitch: https://stza.co/+v$RG-3z\n\nShop: https://stza.co/+v$RG-35\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144544Z
LAST-MODIFIED:20180213T144544Z
TRANSP:OPAQUE
END:VEVENT
* BayBears vs. Jumbo Shrimp
<2018-07-29 Sun 17:05-20:05>
:PROPERTIES:
:ID:       d_EueOJvn2rLkWEwWLfgq4HE@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

BayBears vs. Jumbo Shrimp BayBears vs. Jumbo Shrimp

Follow on MiLB First Pitch  https //stza.co/+v$RH-1t

Shop  https //stza.co/+v$RH-11

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:BayBears vs. Jumbo Shrimp
END:VALARM
DTSTART:20180729T220500Z
DTEND:20180730T010500Z
UID:d_EueOJvn2rLkWEwWLfgq4HE@stanza.co
SUMMARY:BayBears vs. Jumbo Shrimp
DESCRIPTION:BayBears vs. Jumbo Shrimp\n\nFollow on MiLB First Pitch: https://stza.co/+v$RH-1t\n\nShop: https://stza.co/+v$RH-11\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144544Z
LAST-MODIFIED:20180213T144544Z
TRANSP:OPAQUE
END:VEVENT
* BayBears vs. Jumbo Shrimp
<2018-07-30 Mon 18:35-21:35>
:PROPERTIES:
:ID:       gU_Atzktki9ysgsN-iCA_XUn@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

BayBears vs. Jumbo Shrimp BayBears vs. Jumbo Shrimp

Follow on MiLB First Pitch  https //stza.co/+v$RJ-J

Shop  https //stza.co/+v$RJ-1c

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:BayBears vs. Jumbo Shrimp
END:VALARM
DTSTART:20180730T233500Z
DTEND:20180731T023500Z
UID:gU_Atzktki9ysgsN-iCA_XUn@stanza.co
SUMMARY:BayBears vs. Jumbo Shrimp
DESCRIPTION:BayBears vs. Jumbo Shrimp\n\nFollow on MiLB First Pitch: https://stza.co/+v$RJ-J\n\nShop: https://stza.co/+v$RJ-1c\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144544Z
LAST-MODIFIED:20180213T144544Z
TRANSP:OPAQUE
END:VEVENT
* BayBears vs. Jumbo Shrimp
<2018-07-31 Tue 18:35-21:35>
:PROPERTIES:
:ID:       ibmewCVLEm9yqMYqIQbGhGkx@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

BayBears vs. Jumbo Shrimp BayBears vs. Jumbo Shrimp

Follow on MiLB First Pitch  https //stza.co/+v$RM-k

Shop  https //stza.co/+v$RM-1a

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:BayBears vs. Jumbo Shrimp
END:VALARM
DTSTART:20180731T233500Z
DTEND:20180801T023500Z
UID:ibmewCVLEm9yqMYqIQbGhGkx@stanza.co
SUMMARY:BayBears vs. Jumbo Shrimp
DESCRIPTION:BayBears vs. Jumbo Shrimp\n\nFollow on MiLB First Pitch: https://stza.co/+v$RM-k\n\nShop: https://stza.co/+v$RM-1a\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144544Z
LAST-MODIFIED:20180213T144544Z
TRANSP:OPAQUE
END:VEVENT
* BayBears vs. Jumbo Shrimp
<2018-08-01 Wed 18:35-21:35>
:PROPERTIES:
:ID:       Na1Ml6j38MejpSgsez-j-Pch@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

BayBears vs. Jumbo Shrimp BayBears vs. Jumbo Shrimp

Follow on MiLB First Pitch  https //stza.co/+v$RO-3V

Shop  https //stza.co/+v$RO-3G

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:BayBears vs. Jumbo Shrimp
END:VALARM
DTSTART:20180801T233500Z
DTEND:20180802T023500Z
UID:Na1Ml6j38MejpSgsez-j-Pch@stanza.co
SUMMARY:BayBears vs. Jumbo Shrimp
DESCRIPTION:BayBears vs. Jumbo Shrimp\n\nFollow on MiLB First Pitch: https://stza.co/+v$RO-3V\n\nShop: https://stza.co/+v$RO-3G\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144544Z
LAST-MODIFIED:20180213T144544Z
TRANSP:OPAQUE
END:VEVENT
* BayBears @ Barons
<2018-08-02 Thu 19:05-22:05>
:PROPERTIES:
:ID:       qF9uJ24pQeiEg4ZJBGnctt0V@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

BayBears @ Barons BayBears @ Barons

Follow on MiLB First Pitch  https //stza.co/+wFXJ-5

Shop  https //stza.co/+wFXJ-1e

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:BayBears @ Barons
END:VALARM
DTSTART:20180803T000500Z
DTEND:20180803T030500Z
UID:qF9uJ24pQeiEg4ZJBGnctt0V@stanza.co
SUMMARY:BayBears @ Barons
DESCRIPTION:BayBears @ Barons\n\nFollow on MiLB First Pitch: https://stza.co/+wFXJ-5\n\nShop: https://stza.co/+wFXJ-1e\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144544Z
LAST-MODIFIED:20180213T144544Z
TRANSP:OPAQUE
END:VEVENT
* BayBears @ Barons
<2018-08-03 Fri 19:05-22:05>
:PROPERTIES:
:ID:       jqsKAf6TYNFu7RJO74ragZf4@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

BayBears @ Barons BayBears @ Barons

Follow on MiLB First Pitch  https //stza.co/+wFXK-3d

Shop  https //stza.co/+wFXK-P

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:BayBears @ Barons
END:VALARM
DTSTART:20180804T000500Z
DTEND:20180804T030500Z
UID:jqsKAf6TYNFu7RJO74ragZf4@stanza.co
SUMMARY:BayBears @ Barons
DESCRIPTION:BayBears @ Barons\n\nFollow on MiLB First Pitch: https://stza.co/+wFXK-3d\n\nShop: https://stza.co/+wFXK-P\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144544Z
LAST-MODIFIED:20180213T144544Z
TRANSP:OPAQUE
END:VEVENT
* BayBears @ Barons
<2018-08-04 Sat 18:30-21:30>
:PROPERTIES:
:ID:       b_dg6s2n5YzeFiN6ml2XVXW1@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

BayBears @ Barons BayBears @ Barons

Follow on MiLB First Pitch  https //stza.co/+wFXL-3I

Shop  https //stza.co/+wFXL-23

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:BayBears @ Barons
END:VALARM
DTSTART:20180804T233000Z
DTEND:20180805T023000Z
UID:b_dg6s2n5YzeFiN6ml2XVXW1@stanza.co
SUMMARY:BayBears @ Barons
DESCRIPTION:BayBears @ Barons\n\nFollow on MiLB First Pitch: https://stza.co/+wFXL-3I\n\nShop: https://stza.co/+wFXL-23\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144544Z
LAST-MODIFIED:20180213T144544Z
TRANSP:OPAQUE
END:VEVENT
* BayBears @ Barons
<2018-08-05 Sun 15:00-18:00>
:PROPERTIES:
:ID:       OVIpQLCbufWWz25apEWGTcPG@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

BayBears @ Barons BayBears @ Barons

Follow on MiLB First Pitch  https //stza.co/+wFXM-3H

Shop  https //stza.co/+wFXM-E

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:BayBears @ Barons
END:VALARM
DTSTART:20180805T200000Z
DTEND:20180805T230000Z
UID:OVIpQLCbufWWz25apEWGTcPG@stanza.co
SUMMARY:BayBears @ Barons
DESCRIPTION:BayBears @ Barons\n\nFollow on MiLB First Pitch: https://stza.co/+wFXM-3H\n\nShop: https://stza.co/+wFXM-E\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144544Z
LAST-MODIFIED:20180213T144544Z
TRANSP:OPAQUE
END:VEVENT
* BayBears @ Barons
<2018-08-06 Mon 19:05-22:05>
:PROPERTIES:
:ID:       5hAgbwDbTmwnqWHwiUiuD6HK@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

BayBears @ Barons BayBears @ Barons

Follow on MiLB First Pitch  https //stza.co/+wFXN-2N

Shop  https //stza.co/+wFXN-1D

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:BayBears @ Barons
END:VALARM
DTSTART:20180807T000500Z
DTEND:20180807T030500Z
UID:5hAgbwDbTmwnqWHwiUiuD6HK@stanza.co
SUMMARY:BayBears @ Barons
DESCRIPTION:BayBears @ Barons\n\nFollow on MiLB First Pitch: https://stza.co/+wFXN-2N\n\nShop: https://stza.co/+wFXN-1D\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144544Z
LAST-MODIFIED:20180213T144544Z
TRANSP:OPAQUE
END:VEVENT
* BayBears vs. Blue Wahoos
<2018-08-08 Wed 18:35-21:35>
:PROPERTIES:
:ID:       GblvBzHWh0mhCE80C27Y-v9t@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

BayBears vs. Blue Wahoos BayBears vs. Blue Wahoos

Follow on MiLB First Pitch  https //stza.co/+v$RP-3G

Shop  https //stza.co/+v$RP-3q

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:BayBears vs. Blue Wahoos
END:VALARM
DTSTART:20180808T233500Z
DTEND:20180809T023500Z
UID:GblvBzHWh0mhCE80C27Y-v9t@stanza.co
SUMMARY:BayBears vs. Blue Wahoos
DESCRIPTION:BayBears vs. Blue Wahoos\n\nFollow on MiLB First Pitch: https://stza.co/+v$RP-3G\n\nShop: https://stza.co/+v$RP-3q\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144544Z
LAST-MODIFIED:20180213T144544Z
TRANSP:OPAQUE
END:VEVENT
* BayBears vs. Blue Wahoos
<2018-08-09 Thu 18:35-21:35>
:PROPERTIES:
:ID:       g3_nz0vFm-PCi93ELgPi3ZiZ@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

BayBears vs. Blue Wahoos BayBears vs. Blue Wahoos

Follow on MiLB First Pitch  https //stza.co/+v$RR-1

Shop  https //stza.co/+v$RR-2F

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:BayBears vs. Blue Wahoos
END:VALARM
DTSTART:20180809T233500Z
DTEND:20180810T023500Z
UID:g3_nz0vFm-PCi93ELgPi3ZiZ@stanza.co
SUMMARY:BayBears vs. Blue Wahoos
DESCRIPTION:BayBears vs. Blue Wahoos\n\nFollow on MiLB First Pitch: https://stza.co/+v$RR-1\n\nShop: https://stza.co/+v$RR-2F\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144544Z
LAST-MODIFIED:20180213T144544Z
TRANSP:OPAQUE
END:VEVENT
* BayBears vs. Blue Wahoos
<2018-08-10 Fri 19:05-22:05>
:PROPERTIES:
:ID:       Rvc9foxKicjNazPkv7r03PSz@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

BayBears vs. Blue Wahoos BayBears vs. Blue Wahoos

Follow on MiLB First Pitch  https //stza.co/+v$RU-H

Shop  https //stza.co/+v$RU-1M

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:BayBears vs. Blue Wahoos
END:VALARM
DTSTART:20180811T000500Z
DTEND:20180811T030500Z
UID:Rvc9foxKicjNazPkv7r03PSz@stanza.co
SUMMARY:BayBears vs. Blue Wahoos
DESCRIPTION:BayBears vs. Blue Wahoos\n\nFollow on MiLB First Pitch: https://stza.co/+v$RU-H\n\nShop: https://stza.co/+v$RU-1M\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144544Z
LAST-MODIFIED:20180213T144544Z
TRANSP:OPAQUE
END:VEVENT
* BayBears vs. Blue Wahoos
<2018-08-11 Sat 19:05-22:05>
:PROPERTIES:
:ID:       vqJRN503B-kybnniYvKY7COj@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

BayBears vs. Blue Wahoos BayBears vs. Blue Wahoos

Follow on MiLB First Pitch  https //stza.co/+v$RW-20

Shop  https //stza.co/+v$RW-33

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:BayBears vs. Blue Wahoos
END:VALARM
DTSTART:20180812T000500Z
DTEND:20180812T030500Z
UID:vqJRN503B-kybnniYvKY7COj@stanza.co
SUMMARY:BayBears vs. Blue Wahoos
DESCRIPTION:BayBears vs. Blue Wahoos\n\nFollow on MiLB First Pitch: https://stza.co/+v$RW-20\n\nShop: https://stza.co/+v$RW-33\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144544Z
LAST-MODIFIED:20180213T144544Z
TRANSP:OPAQUE
END:VEVENT
* BayBears vs. Blue Wahoos
<2018-08-12 Sun 17:05-20:05>
:PROPERTIES:
:ID:       xtKxIGdRFZNqJmSWqVMoHjQI@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

BayBears vs. Blue Wahoos BayBears vs. Blue Wahoos

Follow on MiLB First Pitch  https //stza.co/+v$RY-F

Shop  https //stza.co/+v$RY-3z

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:BayBears vs. Blue Wahoos
END:VALARM
DTSTART:20180812T220500Z
DTEND:20180813T010500Z
UID:xtKxIGdRFZNqJmSWqVMoHjQI@stanza.co
SUMMARY:BayBears vs. Blue Wahoos
DESCRIPTION:BayBears vs. Blue Wahoos\n\nFollow on MiLB First Pitch: https://stza.co/+v$RY-F\n\nShop: https://stza.co/+v$RY-3z\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144544Z
LAST-MODIFIED:20180213T144544Z
TRANSP:OPAQUE
END:VEVENT
* BayBears @ Shuckers
<2018-08-14 Tue 18:35-21:35>
:PROPERTIES:
:ID:       tx72Da-iwmtp-TxMjaTwGmF2@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

BayBears @ Shuckers BayBears @ Shuckers

Follow on MiLB First Pitch  https //stza.co/+vLLK-2X

Shop  https //stza.co/+vLLK-1X

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:BayBears @ Shuckers
END:VALARM
DTSTART:20180814T233500Z
DTEND:20180815T023500Z
UID:tx72Da-iwmtp-TxMjaTwGmF2@stanza.co
SUMMARY:BayBears @ Shuckers
DESCRIPTION:BayBears @ Shuckers\n\nFollow on MiLB First Pitch: https://stza.co/+vLLK-2X\n\nShop: https://stza.co/+vLLK-1X\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144544Z
LAST-MODIFIED:20180213T144544Z
TRANSP:OPAQUE
END:VEVENT
* BayBears @ Shuckers
<2018-08-15 Wed 18:35-21:35>
:PROPERTIES:
:ID:       Z_el8sd9okfiaYcrEYv8nndd@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

BayBears @ Shuckers BayBears @ Shuckers

Follow on MiLB First Pitch  https //stza.co/+vLLL-$

Shop  https //stza.co/+vLLL-W

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:BayBears @ Shuckers
END:VALARM
DTSTART:20180815T233500Z
DTEND:20180816T023500Z
UID:Z_el8sd9okfiaYcrEYv8nndd@stanza.co
SUMMARY:BayBears @ Shuckers
DESCRIPTION:BayBears @ Shuckers\n\nFollow on MiLB First Pitch: https://stza.co/+vLLL-$\n\nShop: https://stza.co/+vLLL-W\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144544Z
LAST-MODIFIED:20180213T144544Z
TRANSP:OPAQUE
END:VEVENT
* BayBears @ Shuckers
<2018-08-16 Thu 18:35-21:35>
:PROPERTIES:
:ID:       ceiuNFgI0iUJhIHuKzNe_pEY@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

BayBears @ Shuckers BayBears @ Shuckers

Follow on MiLB First Pitch  https //stza.co/+vLLM-2d

Shop  https //stza.co/+vLLM-3B

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:BayBears @ Shuckers
END:VALARM
DTSTART:20180816T233500Z
DTEND:20180817T023500Z
UID:ceiuNFgI0iUJhIHuKzNe_pEY@stanza.co
SUMMARY:BayBears @ Shuckers
DESCRIPTION:BayBears @ Shuckers\n\nFollow on MiLB First Pitch: https://stza.co/+vLLM-2d\n\nShop: https://stza.co/+vLLM-3B\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144544Z
LAST-MODIFIED:20180213T144544Z
TRANSP:OPAQUE
END:VEVENT
* BayBears @ Shuckers
<2018-08-17 Fri 18:35-21:35>
:PROPERTIES:
:ID:       3KNHHXSVwulse7bp3t8cvP35@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

BayBears @ Shuckers BayBears @ Shuckers

Follow on MiLB First Pitch  https //stza.co/+vLLN-18

Shop  https //stza.co/+vLLN-3c

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:BayBears @ Shuckers
END:VALARM
DTSTART:20180817T233500Z
DTEND:20180818T023500Z
UID:3KNHHXSVwulse7bp3t8cvP35@stanza.co
SUMMARY:BayBears @ Shuckers
DESCRIPTION:BayBears @ Shuckers\n\nFollow on MiLB First Pitch: https://stza.co/+vLLN-18\n\nShop: https://stza.co/+vLLN-3c\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144544Z
LAST-MODIFIED:20180213T144544Z
TRANSP:OPAQUE
END:VEVENT
* BayBears @ Shuckers
<2018-08-18 Sat 18:35-21:35>
:PROPERTIES:
:ID:       5nq5MKDcoP3HR2lVlxpGBT9r@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

BayBears @ Shuckers BayBears @ Shuckers

Follow on MiLB First Pitch  https //stza.co/+vLLO-E

Shop  https //stza.co/+vLLO-3y

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:BayBears @ Shuckers
END:VALARM
DTSTART:20180818T233500Z
DTEND:20180819T023500Z
UID:5nq5MKDcoP3HR2lVlxpGBT9r@stanza.co
SUMMARY:BayBears @ Shuckers
DESCRIPTION:BayBears @ Shuckers\n\nFollow on MiLB First Pitch: https://stza.co/+vLLO-E\n\nShop: https://stza.co/+vLLO-3y\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144544Z
LAST-MODIFIED:20180213T144544Z
TRANSP:OPAQUE
END:VEVENT
* BayBears vs. Braves
<2018-08-19 Sun 17:05-20:05>
:PROPERTIES:
:ID:       yOu0I1x6t_UxgrmUryOam7l_@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

BayBears vs. Braves BayBears vs. Braves

Follow on MiLB First Pitch  https //stza.co/+v$RZ-c

Shop  https //stza.co/+v$RZ-23

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:BayBears vs. Braves
END:VALARM
DTSTART:20180819T220500Z
DTEND:20180820T010500Z
UID:yOu0I1x6t_UxgrmUryOam7l_@stanza.co
SUMMARY:BayBears vs. Braves
DESCRIPTION:BayBears vs. Braves\n\nFollow on MiLB First Pitch: https://stza.co/+v$RZ-c\n\nShop: https://stza.co/+v$RZ-23\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144544Z
LAST-MODIFIED:20180213T144544Z
TRANSP:OPAQUE
END:VEVENT
* BayBears vs. Braves
<2018-08-20 Mon 18:35-21:35>
:PROPERTIES:
:ID:       oidiabKiaP5GvT4wUVBtqlsR@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

BayBears vs. Braves BayBears vs. Braves

Follow on MiLB First Pitch  https //stza.co/+v$S0-10

Shop  https //stza.co/+v$S0-1f

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:BayBears vs. Braves
END:VALARM
DTSTART:20180820T233500Z
DTEND:20180821T023500Z
UID:oidiabKiaP5GvT4wUVBtqlsR@stanza.co
SUMMARY:BayBears vs. Braves
DESCRIPTION:BayBears vs. Braves\n\nFollow on MiLB First Pitch: https://stza.co/+v$S0-10\n\nShop: https://stza.co/+v$S0-1f\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144544Z
LAST-MODIFIED:20180213T144544Z
TRANSP:OPAQUE
END:VEVENT
* BayBears vs. Braves
<2018-08-21 Tue 18:35-21:35>
:PROPERTIES:
:ID:       f1Eklw8wPjvzC0csB9Fm9zWN@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

BayBears vs. Braves BayBears vs. Braves

Follow on MiLB First Pitch  https //stza.co/+v$S2-25

Shop  https //stza.co/+v$S2-_

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:BayBears vs. Braves
END:VALARM
DTSTART:20180821T233500Z
DTEND:20180822T023500Z
UID:f1Eklw8wPjvzC0csB9Fm9zWN@stanza.co
SUMMARY:BayBears vs. Braves
DESCRIPTION:BayBears vs. Braves\n\nFollow on MiLB First Pitch: https://stza.co/+v$S2-25\n\nShop: https://stza.co/+v$S2-_\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144544Z
LAST-MODIFIED:20180213T144544Z
TRANSP:OPAQUE
END:VEVENT
* BayBears vs. Braves
<2018-08-22 Wed 18:35-21:35>
:PROPERTIES:
:ID:       YQsysf0HRyvRg5BedfXBP4pS@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

BayBears vs. Braves BayBears vs. Braves

Follow on MiLB First Pitch  https //stza.co/+v$S4-2A

Shop  https //stza.co/+v$S4-1s

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:BayBears vs. Braves
END:VALARM
DTSTART:20180822T233500Z
DTEND:20180823T023500Z
UID:YQsysf0HRyvRg5BedfXBP4pS@stanza.co
SUMMARY:BayBears vs. Braves
DESCRIPTION:BayBears vs. Braves\n\nFollow on MiLB First Pitch: https://stza.co/+v$S4-2A\n\nShop: https://stza.co/+v$S4-1s\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144544Z
LAST-MODIFIED:20180213T144544Z
TRANSP:OPAQUE
END:VEVENT
* BayBears vs. Braves
<2018-08-23 Thu 18:35-21:35>
:PROPERTIES:
:ID:       1D72ixHKmu9-JjO29SfoSyuE@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

BayBears vs. Braves BayBears vs. Braves

Follow on MiLB First Pitch  https //stza.co/+v$S6-j

Shop  https //stza.co/+v$S6-1t

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:BayBears vs. Braves
END:VALARM
DTSTART:20180823T233500Z
DTEND:20180824T023500Z
UID:1D72ixHKmu9-JjO29SfoSyuE@stanza.co
SUMMARY:BayBears vs. Braves
DESCRIPTION:BayBears vs. Braves\n\nFollow on MiLB First Pitch: https://stza.co/+v$S6-j\n\nShop: https://stza.co/+v$S6-1t\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144544Z
LAST-MODIFIED:20180213T144544Z
TRANSP:OPAQUE
END:VEVENT
* BayBears @ Blue Wahoos
<2018-08-24 Fri 18:35-21:35>
:PROPERTIES:
:ID:       XuGPd2TtNxcXryY0w_TjDmcU@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

BayBears @ Blue Wahoos BayBears @ Blue Wahoos

Follow on MiLB First Pitch  https //stza.co/+wx9c-3C

Shop  https //stza.co/+wx9c-1n

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:BayBears @ Blue Wahoos
END:VALARM
DTSTART:20180824T233500Z
DTEND:20180825T023500Z
UID:XuGPd2TtNxcXryY0w_TjDmcU@stanza.co
SUMMARY:BayBears @ Blue Wahoos
DESCRIPTION:BayBears @ Blue Wahoos\n\nFollow on MiLB First Pitch: https://stza.co/+wx9c-3C\n\nShop: https://stza.co/+wx9c-1n\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144544Z
LAST-MODIFIED:20180213T144544Z
TRANSP:OPAQUE
END:VEVENT
* BayBears @ Blue Wahoos
<2018-08-25 Sat 18:05-21:05>
:PROPERTIES:
:ID:       mON2jXGVJgdHhAkE1T3MoT8C@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

BayBears @ Blue Wahoos BayBears @ Blue Wahoos

Follow on MiLB First Pitch  https //stza.co/+wx9d-2s

Shop  https //stza.co/+wx9d-1o

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:BayBears @ Blue Wahoos
END:VALARM
DTSTART:20180825T230500Z
DTEND:20180826T020500Z
UID:mON2jXGVJgdHhAkE1T3MoT8C@stanza.co
SUMMARY:BayBears @ Blue Wahoos
DESCRIPTION:BayBears @ Blue Wahoos\n\nFollow on MiLB First Pitch: https://stza.co/+wx9d-2s\n\nShop: https://stza.co/+wx9d-1o\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144544Z
LAST-MODIFIED:20180213T144544Z
TRANSP:OPAQUE
END:VEVENT
* BayBears @ Blue Wahoos
<2018-08-26 Sun 17:05-20:05>
:PROPERTIES:
:ID:       r0EOgLrAmnD0OTI7HKTOWJFh@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

BayBears @ Blue Wahoos BayBears @ Blue Wahoos

Follow on MiLB First Pitch  https //stza.co/+wx9e-2

Shop  https //stza.co/+wx9e-1A

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:BayBears @ Blue Wahoos
END:VALARM
DTSTART:20180826T220500Z
DTEND:20180827T010500Z
UID:r0EOgLrAmnD0OTI7HKTOWJFh@stanza.co
SUMMARY:BayBears @ Blue Wahoos
DESCRIPTION:BayBears @ Blue Wahoos\n\nFollow on MiLB First Pitch: https://stza.co/+wx9e-2\n\nShop: https://stza.co/+wx9e-1A\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144544Z
LAST-MODIFIED:20180213T144544Z
TRANSP:OPAQUE
END:VEVENT
* BayBears @ Blue Wahoos
<2018-08-27 Mon 18:35-21:35>
:PROPERTIES:
:ID:       iJk1krx_sHRXDW1tWktnGPo1@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

BayBears @ Blue Wahoos BayBears @ Blue Wahoos

Follow on MiLB First Pitch  https //stza.co/+wx9f-1d

Shop  https //stza.co/+wx9f-2$

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:BayBears @ Blue Wahoos
END:VALARM
DTSTART:20180827T233500Z
DTEND:20180828T023500Z
UID:iJk1krx_sHRXDW1tWktnGPo1@stanza.co
SUMMARY:BayBears @ Blue Wahoos
DESCRIPTION:BayBears @ Blue Wahoos\n\nFollow on MiLB First Pitch: https://stza.co/+wx9f-1d\n\nShop: https://stza.co/+wx9f-2$\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144544Z
LAST-MODIFIED:20180213T144544Z
TRANSP:OPAQUE
END:VEVENT
* BayBears @ Blue Wahoos
<2018-08-28 Tue 18:35-21:35>
:PROPERTIES:
:ID:       oLnTl3B2rrHSxtYbKbvUnufL@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

BayBears @ Blue Wahoos BayBears @ Blue Wahoos

Follow on MiLB First Pitch  https //stza.co/+wx9g-3W

Shop  https //stza.co/+wx9g-1R

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:BayBears @ Blue Wahoos
END:VALARM
DTSTART:20180828T233500Z
DTEND:20180829T023500Z
UID:oLnTl3B2rrHSxtYbKbvUnufL@stanza.co
SUMMARY:BayBears @ Blue Wahoos
DESCRIPTION:BayBears @ Blue Wahoos\n\nFollow on MiLB First Pitch: https://stza.co/+wx9g-3W\n\nShop: https://stza.co/+wx9g-1R\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144544Z
LAST-MODIFIED:20180213T144544Z
TRANSP:OPAQUE
END:VEVENT
* BayBears vs. Biscuits
<2018-08-30 Thu 18:35-21:35>
:PROPERTIES:
:ID:       J_HmNhaSlvcYLUa4MBlG2PYq@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

BayBears vs. Biscuits BayBears vs. Biscuits

Follow on MiLB First Pitch  https //stza.co/+v$S8-2s

Shop  https //stza.co/+v$S8-3J

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:BayBears vs. Biscuits
END:VALARM
DTSTART:20180830T233500Z
DTEND:20180831T023500Z
UID:J_HmNhaSlvcYLUa4MBlG2PYq@stanza.co
SUMMARY:BayBears vs. Biscuits
DESCRIPTION:BayBears vs. Biscuits\n\nFollow on MiLB First Pitch: https://stza.co/+v$S8-2s\n\nShop: https://stza.co/+v$S8-3J\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144544Z
LAST-MODIFIED:20180213T144544Z
TRANSP:OPAQUE
END:VEVENT
* BayBears vs. Biscuits
<2018-08-31 Fri 19:05-22:05>
:PROPERTIES:
:ID:       nUtYHta6fYTy760SZz5J0seL@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

BayBears vs. Biscuits BayBears vs. Biscuits

Follow on MiLB First Pitch  https //stza.co/+v$Sa-r

Shop  https //stza.co/+v$Sa-t

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:BayBears vs. Biscuits
END:VALARM
DTSTART:20180901T000500Z
DTEND:20180901T030500Z
UID:nUtYHta6fYTy760SZz5J0seL@stanza.co
SUMMARY:BayBears vs. Biscuits
DESCRIPTION:BayBears vs. Biscuits\n\nFollow on MiLB First Pitch: https://stza.co/+v$Sa-r\n\nShop: https://stza.co/+v$Sa-t\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144544Z
LAST-MODIFIED:20180213T144544Z
TRANSP:OPAQUE
END:VEVENT
* BayBears vs. Biscuits
<2018-09-01 Sat 19:05-22:05>
:PROPERTIES:
:ID:       3dYjp7ttLLyaVU0u8tf4gBbT@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

BayBears vs. Biscuits BayBears vs. Biscuits

Follow on MiLB First Pitch  https //stza.co/+v$Sc-2J

Shop  https //stza.co/+v$Sc-1P

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:BayBears vs. Biscuits
END:VALARM
DTSTART:20180902T000500Z
DTEND:20180902T030500Z
UID:3dYjp7ttLLyaVU0u8tf4gBbT@stanza.co
SUMMARY:BayBears vs. Biscuits
DESCRIPTION:BayBears vs. Biscuits\n\nFollow on MiLB First Pitch: https://stza.co/+v$Sc-2J\n\nShop: https://stza.co/+v$Sc-1P\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144544Z
LAST-MODIFIED:20180213T144544Z
TRANSP:OPAQUE
END:VEVENT
* BayBears vs. Biscuits
<2018-09-02 Sun 17:05-20:05>
:PROPERTIES:
:ID:       blqTtH3BsIyuf53qWBuPyiuw@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

BayBears vs. Biscuits BayBears vs. Biscuits

Follow on MiLB First Pitch  https //stza.co/+v$Se-1o

Shop  https //stza.co/+v$Se-37

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:BayBears vs. Biscuits
END:VALARM
DTSTART:20180902T220500Z
DTEND:20180903T010500Z
UID:blqTtH3BsIyuf53qWBuPyiuw@stanza.co
SUMMARY:BayBears vs. Biscuits
DESCRIPTION:BayBears vs. Biscuits\n\nFollow on MiLB First Pitch: https://stza.co/+v$Se-1o\n\nShop: https://stza.co/+v$Se-37\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144544Z
LAST-MODIFIED:20180213T144544Z
TRANSP:OPAQUE
END:VEVENT
* BayBears vs. Biscuits
<2018-09-03 Mon 12:05-15:05>
:PROPERTIES:
:ID:       NQbFbQPhq9BKHnbXWGbsZz_J@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

BayBears vs. Biscuits BayBears vs. Biscuits

Follow on MiLB First Pitch  https //stza.co/+v$Sg-3E

Shop  https //stza.co/+v$Sg-1N

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:BayBears vs. Biscuits
END:VALARM
DTSTART:20180903T170500Z
DTEND:20180903T200500Z
UID:NQbFbQPhq9BKHnbXWGbsZz_J@stanza.co
SUMMARY:BayBears vs. Biscuits
DESCRIPTION:BayBears vs. Biscuits\n\nFollow on MiLB First Pitch: https://stza.co/+v$Sg-3E\n\nShop: https://stza.co/+v$Sg-1N\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144544Z
LAST-MODIFIED:20180213T144544Z
TRANSP:OPAQUE
END:VEVENT
