#+TITLE:       Main Google calendar entries
#+AUTHOR:      Eric S Fraga
#+EMAIL:       e.fraga@ucl.ac.uk
#+DESCRIPTION: converted using the ical2org awk script
#+CATEGORY:    google
#+STARTUP:     hidestars
#+STARTUP:     overview

* COMMENT original iCal preamble

* Chihuahuas vs. Padres
<2018-03-26 Mon 19:05-22:05>
:PROPERTIES:
:ID:       GAy0GiauLOSUOFM8hdwceu8G@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Chihuahuas vs. Padres Chihuahuas vs. Padres

Follow on MiLB First Pitch  https //stza.co/+xDLi-2w

Shop  https //stza.co/+xDLi-1Z

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Chihuahuas vs. Padres
END:VALARM
DTSTART:20180327T000500Z
DTEND:20180327T030500Z
UID:GAy0GiauLOSUOFM8hdwceu8G@stanza.co
SUMMARY:Chihuahuas vs. Padres
DESCRIPTION:Chihuahuas vs. Padres\n\nFollow on MiLB First Pitch: https://stza.co/+xDLi-2w\n\nShop: https://stza.co/+xDLi-1Z\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144522Z
LAST-MODIFIED:20180213T144522Z
TRANSP:OPAQUE
END:VEVENT
* Chihuahuas @ 51s
<2018-04-05 Thu 21:05>--<2018-04-06 Fri 00:05>
:PROPERTIES:
:ID:       RTQZPWF_J-s5inNKHNitxREb@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Chihuahuas @ 51s Chihuahuas @ 51s

Follow on MiLB First Pitch  https //stza.co/+vKyp-3t

Shop  https //stza.co/+vKyp-d

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Chihuahuas @ 51s
END:VALARM
DTSTART:20180406T020500Z
DTEND:20180406T050500Z
UID:RTQZPWF_J-s5inNKHNitxREb@stanza.co
SUMMARY:Chihuahuas @ 51s
DESCRIPTION:Chihuahuas @ 51s\n\nFollow on MiLB First Pitch: https://stza.co/+vKyp-3t\n\nShop: https://stza.co/+vKyp-d\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144522Z
LAST-MODIFIED:20180213T144522Z
TRANSP:OPAQUE
END:VEVENT
* Chihuahuas @ 51s
<2018-04-06 Fri 21:05>--<2018-04-07 Sat 00:05>
:PROPERTIES:
:ID:       YQ51BvVtO5y45aQNNMUSHBXu@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Chihuahuas @ 51s Chihuahuas @ 51s

Follow on MiLB First Pitch  https //stza.co/+vKyq-W

Shop  https //stza.co/+vKyq-_

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Chihuahuas @ 51s
END:VALARM
DTSTART:20180407T020500Z
DTEND:20180407T050500Z
UID:YQ51BvVtO5y45aQNNMUSHBXu@stanza.co
SUMMARY:Chihuahuas @ 51s
DESCRIPTION:Chihuahuas @ 51s\n\nFollow on MiLB First Pitch: https://stza.co/+vKyq-W\n\nShop: https://stza.co/+vKyq-_\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144522Z
LAST-MODIFIED:20180213T144522Z
TRANSP:OPAQUE
END:VEVENT
* Chihuahuas @ 51s
<2018-04-07 Sat 21:05>--<2018-04-08 Sun 00:05>
:PROPERTIES:
:ID:       yF6uUZ1iX_8l-9KKmZ67N7hr@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Chihuahuas @ 51s Chihuahuas @ 51s

Follow on MiLB First Pitch  https //stza.co/+vKyr-14

Shop  https //stza.co/+vKyr-2T

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Chihuahuas @ 51s
END:VALARM
DTSTART:20180408T020500Z
DTEND:20180408T050500Z
UID:yF6uUZ1iX_8l-9KKmZ67N7hr@stanza.co
SUMMARY:Chihuahuas @ 51s
DESCRIPTION:Chihuahuas @ 51s\n\nFollow on MiLB First Pitch: https://stza.co/+vKyr-14\n\nShop: https://stza.co/+vKyr-2T\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144522Z
LAST-MODIFIED:20180213T144522Z
TRANSP:OPAQUE
END:VEVENT
* Chihuahuas @ 51s
<2018-04-08 Sun 14:05-17:05>
:PROPERTIES:
:ID:       Y3zIS2azFKG5OXj2GvbwTWk2@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Chihuahuas @ 51s Chihuahuas @ 51s

Follow on MiLB First Pitch  https //stza.co/+vKys-3W

Shop  https //stza.co/+vKys-J

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Chihuahuas @ 51s
END:VALARM
DTSTART:20180408T190500Z
DTEND:20180408T220500Z
UID:Y3zIS2azFKG5OXj2GvbwTWk2@stanza.co
SUMMARY:Chihuahuas @ 51s
DESCRIPTION:Chihuahuas @ 51s\n\nFollow on MiLB First Pitch: https://stza.co/+vKys-3W\n\nShop: https://stza.co/+vKys-J\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144522Z
LAST-MODIFIED:20180213T144522Z
TRANSP:OPAQUE
END:VEVENT
* Chihuahuas @ 51s
<2018-04-09 Mon 21:05>--<2018-04-10 Tue 00:05>
:PROPERTIES:
:ID:       RYTFmVJIbInyjNdb7Xo89nXZ@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Chihuahuas @ 51s Chihuahuas @ 51s

Follow on MiLB First Pitch  https //stza.co/+vKyt-T

Shop  https //stza.co/+vKyt-3i

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Chihuahuas @ 51s
END:VALARM
DTSTART:20180410T020500Z
DTEND:20180410T050500Z
UID:RYTFmVJIbInyjNdb7Xo89nXZ@stanza.co
SUMMARY:Chihuahuas @ 51s
DESCRIPTION:Chihuahuas @ 51s\n\nFollow on MiLB First Pitch: https://stza.co/+vKyt-T\n\nShop: https://stza.co/+vKyt-3i\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144522Z
LAST-MODIFIED:20180213T144522Z
TRANSP:OPAQUE
END:VEVENT
* Chihuahuas vs. Bees
<2018-04-10 Tue 20:05-23:05>
:PROPERTIES:
:ID:       WsfE9tFPGzSsjLdbV5sARfa7@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Chihuahuas vs. Bees Chihuahuas vs. Bees

Follow on MiLB First Pitch  https //stza.co/+wmz7-2v

Shop  https //stza.co/+wmz7-O

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Chihuahuas vs. Bees
END:VALARM
DTSTART:20180411T010500Z
DTEND:20180411T040500Z
UID:WsfE9tFPGzSsjLdbV5sARfa7@stanza.co
SUMMARY:Chihuahuas vs. Bees
DESCRIPTION:Chihuahuas vs. Bees\n\nFollow on MiLB First Pitch: https://stza.co/+wmz7-2v\n\nShop: https://stza.co/+wmz7-O\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144522Z
LAST-MODIFIED:20180213T144522Z
TRANSP:OPAQUE
END:VEVENT
* Chihuahuas vs. Bees
<2018-04-11 Wed 12:05-15:05>
:PROPERTIES:
:ID:       GIgyocHWiGtKI86gMb_ivPg1@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Chihuahuas vs. Bees Chihuahuas vs. Bees

Follow on MiLB First Pitch  https //stza.co/+wmz9-3E

Shop  https //stza.co/+wmz9-2Q

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Chihuahuas vs. Bees
END:VALARM
DTSTART:20180411T170500Z
DTEND:20180411T200500Z
UID:GIgyocHWiGtKI86gMb_ivPg1@stanza.co
SUMMARY:Chihuahuas vs. Bees
DESCRIPTION:Chihuahuas vs. Bees\n\nFollow on MiLB First Pitch: https://stza.co/+wmz9-3E\n\nShop: https://stza.co/+wmz9-2Q\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144522Z
LAST-MODIFIED:20180213T144522Z
TRANSP:OPAQUE
END:VEVENT
* Chihuahuas vs. Bees
<2018-04-12 Thu 19:35-22:35>
:PROPERTIES:
:ID:       oLbZgIi5ioq-sxjxY4uPa45k@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Chihuahuas vs. Bees Chihuahuas vs. Bees

Follow on MiLB First Pitch  https //stza.co/+wmza-5

Shop  https //stza.co/+wmza-N

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Chihuahuas vs. Bees
END:VALARM
DTSTART:20180413T003500Z
DTEND:20180413T033500Z
UID:oLbZgIi5ioq-sxjxY4uPa45k@stanza.co
SUMMARY:Chihuahuas vs. Bees
DESCRIPTION:Chihuahuas vs. Bees\n\nFollow on MiLB First Pitch: https://stza.co/+wmza-5\n\nShop: https://stza.co/+wmza-N\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144522Z
LAST-MODIFIED:20180213T144522Z
TRANSP:OPAQUE
END:VEVENT
* Chihuahuas vs. 51s
<2018-04-13 Fri 20:05-23:05>
:PROPERTIES:
:ID:       m9ymja3SWwrLubLZrA0fNYZF@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Chihuahuas vs. 51s Chihuahuas vs. 51s

Follow on MiLB First Pitch  https //stza.co/+wmzc-2g

Shop  https //stza.co/+wmzc-25

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Chihuahuas vs. 51s
END:VALARM
DTSTART:20180414T010500Z
DTEND:20180414T040500Z
UID:m9ymja3SWwrLubLZrA0fNYZF@stanza.co
SUMMARY:Chihuahuas vs. 51s
DESCRIPTION:Chihuahuas vs. 51s\n\nFollow on MiLB First Pitch: https://stza.co/+wmzc-2g\n\nShop: https://stza.co/+wmzc-25\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144522Z
LAST-MODIFIED:20180213T144522Z
TRANSP:OPAQUE
END:VEVENT
* Chihuahuas vs. 51s
<2018-04-14 Sat 20:05-23:05>
:PROPERTIES:
:ID:       1C3xRjzGQgWxh4TlWXd5hAL6@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Chihuahuas vs. 51s Chihuahuas vs. 51s

Follow on MiLB First Pitch  https //stza.co/+wmzf-2g

Shop  https //stza.co/+wmzf-5

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Chihuahuas vs. 51s
END:VALARM
DTSTART:20180415T010500Z
DTEND:20180415T040500Z
UID:1C3xRjzGQgWxh4TlWXd5hAL6@stanza.co
SUMMARY:Chihuahuas vs. 51s
DESCRIPTION:Chihuahuas vs. 51s\n\nFollow on MiLB First Pitch: https://stza.co/+wmzf-2g\n\nShop: https://stza.co/+wmzf-5\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144522Z
LAST-MODIFIED:20180213T144522Z
TRANSP:OPAQUE
END:VEVENT
* Chihuahuas vs. 51s
<2018-04-15 Sun 14:05-17:05>
:PROPERTIES:
:ID:       uoGVyztbS_O57gTUSZdrd52c@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Chihuahuas vs. 51s Chihuahuas vs. 51s

Follow on MiLB First Pitch  https //stza.co/+wmzi-d

Shop  https //stza.co/+wmzi-2r

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Chihuahuas vs. 51s
END:VALARM
DTSTART:20180415T190500Z
DTEND:20180415T220500Z
UID:uoGVyztbS_O57gTUSZdrd52c@stanza.co
SUMMARY:Chihuahuas vs. 51s
DESCRIPTION:Chihuahuas vs. 51s\n\nFollow on MiLB First Pitch: https://stza.co/+wmzi-d\n\nShop: https://stza.co/+wmzi-2r\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144522Z
LAST-MODIFIED:20180213T144522Z
TRANSP:OPAQUE
END:VEVENT
* Chihuahuas vs. 51s
<2018-04-16 Mon 12:05-15:05>
:PROPERTIES:
:ID:       xpWNNp_w2WZ14g6KcscFAtfZ@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Chihuahuas vs. 51s Chihuahuas vs. 51s

Follow on MiLB First Pitch  https //stza.co/+wmzj-3D

Shop  https //stza.co/+wmzj-3j

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Chihuahuas vs. 51s
END:VALARM
DTSTART:20180416T170500Z
DTEND:20180416T200500Z
UID:xpWNNp_w2WZ14g6KcscFAtfZ@stanza.co
SUMMARY:Chihuahuas vs. 51s
DESCRIPTION:Chihuahuas vs. 51s\n\nFollow on MiLB First Pitch: https://stza.co/+wmzj-3D\n\nShop: https://stza.co/+wmzj-3j\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144522Z
LAST-MODIFIED:20180213T144522Z
TRANSP:OPAQUE
END:VEVENT
* Chihuahuas @ Aces
<2018-04-17 Tue 20:35-23:35>
:PROPERTIES:
:ID:       S4sA8eg3Rtjx6zp4u03kvgDm@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Chihuahuas @ Aces Chihuahuas @ Aces

Follow on MiLB First Pitch  https //stza.co/+wjxc-34

Shop  https //stza.co/+wjxc-2T

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Chihuahuas @ Aces
END:VALARM
DTSTART:20180418T013500Z
DTEND:20180418T043500Z
UID:S4sA8eg3Rtjx6zp4u03kvgDm@stanza.co
SUMMARY:Chihuahuas @ Aces
DESCRIPTION:Chihuahuas @ Aces\n\nFollow on MiLB First Pitch: https://stza.co/+wjxc-34\n\nShop: https://stza.co/+wjxc-2T\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144522Z
LAST-MODIFIED:20180213T144522Z
TRANSP:OPAQUE
END:VEVENT
* Chihuahuas @ Aces
<2018-04-18 Wed 20:35-23:35>
:PROPERTIES:
:ID:       HT1zouikq2D5vYtj_KYx3Nzg@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Chihuahuas @ Aces Chihuahuas @ Aces

Follow on MiLB First Pitch  https //stza.co/+wjxd-1G

Shop  https //stza.co/+wjxd-2v

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Chihuahuas @ Aces
END:VALARM
DTSTART:20180419T013500Z
DTEND:20180419T043500Z
UID:HT1zouikq2D5vYtj_KYx3Nzg@stanza.co
SUMMARY:Chihuahuas @ Aces
DESCRIPTION:Chihuahuas @ Aces\n\nFollow on MiLB First Pitch: https://stza.co/+wjxd-1G\n\nShop: https://stza.co/+wjxd-2v\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144522Z
LAST-MODIFIED:20180213T144522Z
TRANSP:OPAQUE
END:VEVENT
* Chihuahuas @ Aces
<2018-04-19 Thu 20:35-23:35>
:PROPERTIES:
:ID:       Zpa4FlQYCkmyZCJC1z90AfPR@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Chihuahuas @ Aces Chihuahuas @ Aces

Follow on MiLB First Pitch  https //stza.co/+wjxe-3R

Shop  https //stza.co/+wjxe-y

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Chihuahuas @ Aces
END:VALARM
DTSTART:20180420T013500Z
DTEND:20180420T043500Z
UID:Zpa4FlQYCkmyZCJC1z90AfPR@stanza.co
SUMMARY:Chihuahuas @ Aces
DESCRIPTION:Chihuahuas @ Aces\n\nFollow on MiLB First Pitch: https://stza.co/+wjxe-3R\n\nShop: https://stza.co/+wjxe-y\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144522Z
LAST-MODIFIED:20180213T144522Z
TRANSP:OPAQUE
END:VEVENT
* Chihuahuas @ Aces
<2018-04-20 Fri 20:35-23:35>
:PROPERTIES:
:ID:       FcONHsxgy27dI20SVyjtOYZq@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Chihuahuas @ Aces Chihuahuas @ Aces

Follow on MiLB First Pitch  https //stza.co/+wjxf-3u

Shop  https //stza.co/+wjxf-3R

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Chihuahuas @ Aces
END:VALARM
DTSTART:20180421T013500Z
DTEND:20180421T043500Z
UID:FcONHsxgy27dI20SVyjtOYZq@stanza.co
SUMMARY:Chihuahuas @ Aces
DESCRIPTION:Chihuahuas @ Aces\n\nFollow on MiLB First Pitch: https://stza.co/+wjxf-3u\n\nShop: https://stza.co/+wjxf-3R\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144522Z
LAST-MODIFIED:20180213T144522Z
TRANSP:OPAQUE
END:VEVENT
* Chihuahuas @ 51s
<2018-04-21 Sat 21:05>--<2018-04-22 Sun 00:05>
:PROPERTIES:
:ID:       dPBEUVydXwiekWA7yDWCIUMP@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Chihuahuas @ 51s Chihuahuas @ 51s

Follow on MiLB First Pitch  https //stza.co/+vKyu-1M

Shop  https //stza.co/+vKyu-a

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Chihuahuas @ 51s
END:VALARM
DTSTART:20180422T020500Z
DTEND:20180422T050500Z
UID:dPBEUVydXwiekWA7yDWCIUMP@stanza.co
SUMMARY:Chihuahuas @ 51s
DESCRIPTION:Chihuahuas @ 51s\n\nFollow on MiLB First Pitch: https://stza.co/+vKyu-1M\n\nShop: https://stza.co/+vKyu-a\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144522Z
LAST-MODIFIED:20180213T144522Z
TRANSP:OPAQUE
END:VEVENT
* Chihuahuas @ 51s
<2018-04-22 Sun 14:05-17:05>
:PROPERTIES:
:ID:       uJo4VCQhrOaInseXMjh0wAlQ@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Chihuahuas @ 51s Chihuahuas @ 51s

Follow on MiLB First Pitch  https //stza.co/+vKyv-2m

Shop  https //stza.co/+vKyv-X

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Chihuahuas @ 51s
END:VALARM
DTSTART:20180422T190500Z
DTEND:20180422T220500Z
UID:uJo4VCQhrOaInseXMjh0wAlQ@stanza.co
SUMMARY:Chihuahuas @ 51s
DESCRIPTION:Chihuahuas @ 51s\n\nFollow on MiLB First Pitch: https://stza.co/+vKyv-2m\n\nShop: https://stza.co/+vKyv-X\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144522Z
LAST-MODIFIED:20180213T144522Z
TRANSP:OPAQUE
END:VEVENT
* Chihuahuas @ 51s
<2018-04-23 Mon 21:05>--<2018-04-24 Tue 00:05>
:PROPERTIES:
:ID:       -aHxd3HchcdngxJ8AJFqEq3C@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Chihuahuas @ 51s Chihuahuas @ 51s

Follow on MiLB First Pitch  https //stza.co/+vKyw-2F

Shop  https //stza.co/+vKyw-3n

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Chihuahuas @ 51s
END:VALARM
DTSTART:20180424T020500Z
DTEND:20180424T050500Z
UID:-aHxd3HchcdngxJ8AJFqEq3C@stanza.co
SUMMARY:Chihuahuas @ 51s
DESCRIPTION:Chihuahuas @ 51s\n\nFollow on MiLB First Pitch: https://stza.co/+vKyw-2F\n\nShop: https://stza.co/+vKyw-3n\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144522Z
LAST-MODIFIED:20180213T144522Z
TRANSP:OPAQUE
END:VEVENT
* Chihuahuas vs. Bees
<2018-04-25 Wed 19:35-22:35>
:PROPERTIES:
:ID:       XH3LPEK1Ns57ewPjnBq1qzmQ@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Chihuahuas vs. Bees Chihuahuas vs. Bees

Follow on MiLB First Pitch  https //stza.co/+wmzm-Y

Shop  https //stza.co/+wmzm-q

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Chihuahuas vs. Bees
END:VALARM
DTSTART:20180426T003500Z
DTEND:20180426T033500Z
UID:XH3LPEK1Ns57ewPjnBq1qzmQ@stanza.co
SUMMARY:Chihuahuas vs. Bees
DESCRIPTION:Chihuahuas vs. Bees\n\nFollow on MiLB First Pitch: https://stza.co/+wmzm-Y\n\nShop: https://stza.co/+wmzm-q\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144522Z
LAST-MODIFIED:20180213T144522Z
TRANSP:OPAQUE
END:VEVENT
* Chihuahuas vs. Bees
<2018-04-26 Thu 19:35-22:35>
:PROPERTIES:
:ID:       iAkFwEJaUryzYJDdycsyBLA6@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Chihuahuas vs. Bees Chihuahuas vs. Bees

Follow on MiLB First Pitch  https //stza.co/+wmzo-3J

Shop  https //stza.co/+wmzo-2$

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Chihuahuas vs. Bees
END:VALARM
DTSTART:20180427T003500Z
DTEND:20180427T033500Z
UID:iAkFwEJaUryzYJDdycsyBLA6@stanza.co
SUMMARY:Chihuahuas vs. Bees
DESCRIPTION:Chihuahuas vs. Bees\n\nFollow on MiLB First Pitch: https://stza.co/+wmzo-3J\n\nShop: https://stza.co/+wmzo-2$\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144522Z
LAST-MODIFIED:20180213T144522Z
TRANSP:OPAQUE
END:VEVENT
* Chihuahuas vs. Bees
<2018-04-27 Fri 20:05-23:05>
:PROPERTIES:
:ID:       jOOcFUh9tQlbIcRkw-6OYDH3@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Chihuahuas vs. Bees Chihuahuas vs. Bees

Follow on MiLB First Pitch  https //stza.co/+wmzq-3x

Shop  https //stza.co/+wmzq-u

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Chihuahuas vs. Bees
END:VALARM
DTSTART:20180428T010500Z
DTEND:20180428T040500Z
UID:jOOcFUh9tQlbIcRkw-6OYDH3@stanza.co
SUMMARY:Chihuahuas vs. Bees
DESCRIPTION:Chihuahuas vs. Bees\n\nFollow on MiLB First Pitch: https://stza.co/+wmzq-3x\n\nShop: https://stza.co/+wmzq-u\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144522Z
LAST-MODIFIED:20180213T144522Z
TRANSP:OPAQUE
END:VEVENT
* Chihuahuas vs. Bees
<2018-04-28 Sat 20:05-23:05>
:PROPERTIES:
:ID:       SG6bv2IobdXyKV9bw4uzg0XA@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Chihuahuas vs. Bees Chihuahuas vs. Bees

Follow on MiLB First Pitch  https //stza.co/+wmzr-3x

Shop  https //stza.co/+wmzr-I

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Chihuahuas vs. Bees
END:VALARM
DTSTART:20180429T010500Z
DTEND:20180429T040500Z
UID:SG6bv2IobdXyKV9bw4uzg0XA@stanza.co
SUMMARY:Chihuahuas vs. Bees
DESCRIPTION:Chihuahuas vs. Bees\n\nFollow on MiLB First Pitch: https://stza.co/+wmzr-3x\n\nShop: https://stza.co/+wmzr-I\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144522Z
LAST-MODIFIED:20180213T144522Z
TRANSP:OPAQUE
END:VEVENT
* Chihuahuas vs. Bees
<2018-04-29 Sun 14:05-17:05>
:PROPERTIES:
:ID:       sOK3PxpcMxdGMNSbxmQ3BJw6@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Chihuahuas vs. Bees Chihuahuas vs. Bees

Follow on MiLB First Pitch  https //stza.co/+wmzu-2v

Shop  https //stza.co/+wmzu-s

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Chihuahuas vs. Bees
END:VALARM
DTSTART:20180429T190500Z
DTEND:20180429T220500Z
UID:sOK3PxpcMxdGMNSbxmQ3BJw6@stanza.co
SUMMARY:Chihuahuas vs. Bees
DESCRIPTION:Chihuahuas vs. Bees\n\nFollow on MiLB First Pitch: https://stza.co/+wmzu-2v\n\nShop: https://stza.co/+wmzu-s\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144522Z
LAST-MODIFIED:20180213T144522Z
TRANSP:OPAQUE
END:VEVENT
* Chihuahuas vs. Aces
<2018-04-30 Mon 19:35-22:35>
:PROPERTIES:
:ID:       kq6MJqjkRo4JoMsu4Sexm55q@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Chihuahuas vs. Aces Chihuahuas vs. Aces

Follow on MiLB First Pitch  https //stza.co/+wmzw-2G

Shop  https //stza.co/+wmzw-3Y

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Chihuahuas vs. Aces
END:VALARM
DTSTART:20180501T003500Z
DTEND:20180501T033500Z
UID:kq6MJqjkRo4JoMsu4Sexm55q@stanza.co
SUMMARY:Chihuahuas vs. Aces
DESCRIPTION:Chihuahuas vs. Aces\n\nFollow on MiLB First Pitch: https://stza.co/+wmzw-2G\n\nShop: https://stza.co/+wmzw-3Y\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144522Z
LAST-MODIFIED:20180213T144522Z
TRANSP:OPAQUE
END:VEVENT
* Chihuahuas vs. Aces
<2018-05-01 Tue 19:35-22:35>
:PROPERTIES:
:ID:       jrGf1D0-S45TWUx7OX0tqT2f@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Chihuahuas vs. Aces Chihuahuas vs. Aces

Follow on MiLB First Pitch  https //stza.co/+wmzx-t

Shop  https //stza.co/+wmzx-v

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Chihuahuas vs. Aces
END:VALARM
DTSTART:20180502T003500Z
DTEND:20180502T033500Z
UID:jrGf1D0-S45TWUx7OX0tqT2f@stanza.co
SUMMARY:Chihuahuas vs. Aces
DESCRIPTION:Chihuahuas vs. Aces\n\nFollow on MiLB First Pitch: https://stza.co/+wmzx-t\n\nShop: https://stza.co/+wmzx-v\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144522Z
LAST-MODIFIED:20180213T144522Z
TRANSP:OPAQUE
END:VEVENT
* Chihuahuas vs. Aces
<2018-05-02 Wed 12:05-15:05>
:PROPERTIES:
:ID:       tk0rOPV64Rpyutn0uMckaSnM@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Chihuahuas vs. Aces Chihuahuas vs. Aces

Follow on MiLB First Pitch  https //stza.co/+wmzz-F

Shop  https //stza.co/+wmzz-1k

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Chihuahuas vs. Aces
END:VALARM
DTSTART:20180502T170500Z
DTEND:20180502T200500Z
UID:tk0rOPV64Rpyutn0uMckaSnM@stanza.co
SUMMARY:Chihuahuas vs. Aces
DESCRIPTION:Chihuahuas vs. Aces\n\nFollow on MiLB First Pitch: https://stza.co/+wmzz-F\n\nShop: https://stza.co/+wmzz-1k\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144522Z
LAST-MODIFIED:20180213T144522Z
TRANSP:OPAQUE
END:VEVENT
* Chihuahuas vs. Aces
<2018-05-03 Thu 19:35-22:35>
:PROPERTIES:
:ID:       pV5c3vEz1M_MCFPjee3SepIu@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Chihuahuas vs. Aces Chihuahuas vs. Aces

Follow on MiLB First Pitch  https //stza.co/+wmzC-o

Shop  https //stza.co/+wmzC-1o

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Chihuahuas vs. Aces
END:VALARM
DTSTART:20180504T003500Z
DTEND:20180504T033500Z
UID:pV5c3vEz1M_MCFPjee3SepIu@stanza.co
SUMMARY:Chihuahuas vs. Aces
DESCRIPTION:Chihuahuas vs. Aces\n\nFollow on MiLB First Pitch: https://stza.co/+wmzC-o\n\nShop: https://stza.co/+wmzC-1o\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144522Z
LAST-MODIFIED:20180213T144522Z
TRANSP:OPAQUE
END:VEVENT
* Chihuahuas @ Isotopes
<2018-05-04 Fri 19:35-22:35>
:PROPERTIES:
:ID:       6G4gcHLmGtzbjqsKVjQxN0xn@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Chihuahuas @ Isotopes Chihuahuas @ Isotopes

Follow on MiLB First Pitch  https //stza.co/+whCU-3B

Shop  https //stza.co/+whCU-u

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Chihuahuas @ Isotopes
END:VALARM
DTSTART:20180505T003500Z
DTEND:20180505T033500Z
UID:6G4gcHLmGtzbjqsKVjQxN0xn@stanza.co
SUMMARY:Chihuahuas @ Isotopes
DESCRIPTION:Chihuahuas @ Isotopes\n\nFollow on MiLB First Pitch: https://stza.co/+whCU-3B\n\nShop: https://stza.co/+whCU-u\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144522Z
LAST-MODIFIED:20180213T144522Z
TRANSP:OPAQUE
END:VEVENT
* Chihuahuas @ Isotopes
<2018-05-05 Sat 19:35-22:35>
:PROPERTIES:
:ID:       tIVKykdiEQRKJV55R_77BLaa@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Chihuahuas @ Isotopes Chihuahuas @ Isotopes

Follow on MiLB First Pitch  https //stza.co/+whCV-27

Shop  https //stza.co/+whCV-1x

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Chihuahuas @ Isotopes
END:VALARM
DTSTART:20180506T003500Z
DTEND:20180506T033500Z
UID:tIVKykdiEQRKJV55R_77BLaa@stanza.co
SUMMARY:Chihuahuas @ Isotopes
DESCRIPTION:Chihuahuas @ Isotopes\n\nFollow on MiLB First Pitch: https://stza.co/+whCV-27\n\nShop: https://stza.co/+whCV-1x\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144522Z
LAST-MODIFIED:20180213T144522Z
TRANSP:OPAQUE
END:VEVENT
* Chihuahuas @ Isotopes
<2018-05-06 Sun 14:35-17:35>
:PROPERTIES:
:ID:       FrbX4DC8pk7G6UTt1_uao-fN@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Chihuahuas @ Isotopes Chihuahuas @ Isotopes

Follow on MiLB First Pitch  https //stza.co/+whCW-15

Shop  https //stza.co/+whCW-25

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Chihuahuas @ Isotopes
END:VALARM
DTSTART:20180506T193500Z
DTEND:20180506T223500Z
UID:FrbX4DC8pk7G6UTt1_uao-fN@stanza.co
SUMMARY:Chihuahuas @ Isotopes
DESCRIPTION:Chihuahuas @ Isotopes\n\nFollow on MiLB First Pitch: https://stza.co/+whCW-15\n\nShop: https://stza.co/+whCW-25\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144522Z
LAST-MODIFIED:20180213T144522Z
TRANSP:OPAQUE
END:VEVENT
* Chihuahuas @ Isotopes
<2018-05-07 Mon 12:05-15:05>
:PROPERTIES:
:ID:       d57H5atiiTBGKIvDbZyTtBVV@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Chihuahuas @ Isotopes Chihuahuas @ Isotopes

Follow on MiLB First Pitch  https //stza.co/+whCX-1e

Shop  https //stza.co/+whCX-1a

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Chihuahuas @ Isotopes
END:VALARM
DTSTART:20180507T170500Z
DTEND:20180507T200500Z
UID:d57H5atiiTBGKIvDbZyTtBVV@stanza.co
SUMMARY:Chihuahuas @ Isotopes
DESCRIPTION:Chihuahuas @ Isotopes\n\nFollow on MiLB First Pitch: https://stza.co/+whCX-1e\n\nShop: https://stza.co/+whCX-1a\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144522Z
LAST-MODIFIED:20180213T144522Z
TRANSP:OPAQUE
END:VEVENT
* Chihuahuas vs. Rainiers
<2018-05-08 Tue 19:35-22:35>
:PROPERTIES:
:ID:       PssnDpyKj3cSSfbvyLAtn-Z0@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Chihuahuas vs. Rainiers Chihuahuas vs. Rainiers

Follow on MiLB First Pitch  https //stza.co/+wmzE-2P

Shop  https //stza.co/+wmzE-f

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Chihuahuas vs. Rainiers
END:VALARM
DTSTART:20180509T003500Z
DTEND:20180509T033500Z
UID:PssnDpyKj3cSSfbvyLAtn-Z0@stanza.co
SUMMARY:Chihuahuas vs. Rainiers
DESCRIPTION:Chihuahuas vs. Rainiers\n\nFollow on MiLB First Pitch: https://stza.co/+wmzE-2P\n\nShop: https://stza.co/+wmzE-f\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144522Z
LAST-MODIFIED:20180213T144522Z
TRANSP:OPAQUE
END:VEVENT
* Chihuahuas vs. Rainiers
<2018-05-09 Wed 19:35-22:35>
:PROPERTIES:
:ID:       BV75VeQaIAt9URnNzPhDvTlA@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Chihuahuas vs. Rainiers Chihuahuas vs. Rainiers

Follow on MiLB First Pitch  https //stza.co/+wmzG-3b

Shop  https //stza.co/+wmzG-k

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Chihuahuas vs. Rainiers
END:VALARM
DTSTART:20180510T003500Z
DTEND:20180510T033500Z
UID:BV75VeQaIAt9URnNzPhDvTlA@stanza.co
SUMMARY:Chihuahuas vs. Rainiers
DESCRIPTION:Chihuahuas vs. Rainiers\n\nFollow on MiLB First Pitch: https://stza.co/+wmzG-3b\n\nShop: https://stza.co/+wmzG-k\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144522Z
LAST-MODIFIED:20180213T144522Z
TRANSP:OPAQUE
END:VEVENT
* Chihuahuas vs. Rainiers
<2018-05-10 Thu 19:35-22:35>
:PROPERTIES:
:ID:       WqqTSMOMz-I4paPtIIsmseFa@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Chihuahuas vs. Rainiers Chihuahuas vs. Rainiers

Follow on MiLB First Pitch  https //stza.co/+wmzI-3c

Shop  https //stza.co/+wmzI-3D

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Chihuahuas vs. Rainiers
END:VALARM
DTSTART:20180511T003500Z
DTEND:20180511T033500Z
UID:WqqTSMOMz-I4paPtIIsmseFa@stanza.co
SUMMARY:Chihuahuas vs. Rainiers
DESCRIPTION:Chihuahuas vs. Rainiers\n\nFollow on MiLB First Pitch: https://stza.co/+wmzI-3c\n\nShop: https://stza.co/+wmzI-3D\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144522Z
LAST-MODIFIED:20180213T144522Z
TRANSP:OPAQUE
END:VEVENT
* Chihuahuas vs. Rainiers
<2018-05-11 Fri 20:05-23:05>
:PROPERTIES:
:ID:       GTJhHiIAYZuFjQ-N2r0YHCn5@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Chihuahuas vs. Rainiers Chihuahuas vs. Rainiers

Follow on MiLB First Pitch  https //stza.co/+wmzK-1l

Shop  https //stza.co/+wmzK-n

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Chihuahuas vs. Rainiers
END:VALARM
DTSTART:20180512T010500Z
DTEND:20180512T040500Z
UID:GTJhHiIAYZuFjQ-N2r0YHCn5@stanza.co
SUMMARY:Chihuahuas vs. Rainiers
DESCRIPTION:Chihuahuas vs. Rainiers\n\nFollow on MiLB First Pitch: https://stza.co/+wmzK-1l\n\nShop: https://stza.co/+wmzK-n\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144522Z
LAST-MODIFIED:20180213T144522Z
TRANSP:OPAQUE
END:VEVENT
* Chihuahuas @ Aces
<2018-05-12 Sat 20:35-23:35>
:PROPERTIES:
:ID:       L8Eo4YysjUAg3a9vHSNg1reW@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Chihuahuas @ Aces Chihuahuas @ Aces

Follow on MiLB First Pitch  https //stza.co/+wjxg-3Q

Shop  https //stza.co/+wjxg-3E

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Chihuahuas @ Aces
END:VALARM
DTSTART:20180513T013500Z
DTEND:20180513T043500Z
UID:L8Eo4YysjUAg3a9vHSNg1reW@stanza.co
SUMMARY:Chihuahuas @ Aces
DESCRIPTION:Chihuahuas @ Aces\n\nFollow on MiLB First Pitch: https://stza.co/+wjxg-3Q\n\nShop: https://stza.co/+wjxg-3E\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144522Z
LAST-MODIFIED:20180213T144522Z
TRANSP:OPAQUE
END:VEVENT
* Chihuahuas @ Aces
<2018-05-13 Sun 15:05-18:05>
:PROPERTIES:
:ID:       8aalOiQKs0abE0Wuu5m81tEj@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Chihuahuas @ Aces Chihuahuas @ Aces

Follow on MiLB First Pitch  https //stza.co/+wjxh-3_

Shop  https //stza.co/+wjxh-1m

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Chihuahuas @ Aces
END:VALARM
DTSTART:20180513T200500Z
DTEND:20180513T230500Z
UID:8aalOiQKs0abE0Wuu5m81tEj@stanza.co
SUMMARY:Chihuahuas @ Aces
DESCRIPTION:Chihuahuas @ Aces\n\nFollow on MiLB First Pitch: https://stza.co/+wjxh-3_\n\nShop: https://stza.co/+wjxh-1m\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144522Z
LAST-MODIFIED:20180213T144522Z
TRANSP:OPAQUE
END:VEVENT
* Chihuahuas @ Aces
<2018-05-14 Mon 20:35-23:35>
:PROPERTIES:
:ID:       zcS6yX9TohvelQOE8UOi_Eb1@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Chihuahuas @ Aces Chihuahuas @ Aces

Follow on MiLB First Pitch  https //stza.co/+wjxi-1R

Shop  https //stza.co/+wjxi-3I

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Chihuahuas @ Aces
END:VALARM
DTSTART:20180515T013500Z
DTEND:20180515T043500Z
UID:zcS6yX9TohvelQOE8UOi_Eb1@stanza.co
SUMMARY:Chihuahuas @ Aces
DESCRIPTION:Chihuahuas @ Aces\n\nFollow on MiLB First Pitch: https://stza.co/+wjxi-1R\n\nShop: https://stza.co/+wjxi-3I\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144522Z
LAST-MODIFIED:20180213T144522Z
TRANSP:OPAQUE
END:VEVENT
* Chihuahuas @ Aces
<2018-05-15 Tue 13:35-16:35>
:PROPERTIES:
:ID:       F3ujk-5VZrLV5vnLb4QYefRb@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Chihuahuas @ Aces Chihuahuas @ Aces

Follow on MiLB First Pitch  https //stza.co/+wjxj-q

Shop  https //stza.co/+wjxj-3W

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Chihuahuas @ Aces
END:VALARM
DTSTART:20180515T183500Z
DTEND:20180515T213500Z
UID:F3ujk-5VZrLV5vnLb4QYefRb@stanza.co
SUMMARY:Chihuahuas @ Aces
DESCRIPTION:Chihuahuas @ Aces\n\nFollow on MiLB First Pitch: https://stza.co/+wjxj-q\n\nShop: https://stza.co/+wjxj-3W\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144522Z
LAST-MODIFIED:20180213T144522Z
TRANSP:OPAQUE
END:VEVENT
* Chihuahuas vs. Grizzlies
<2018-05-17 Thu 19:35-22:35>
:PROPERTIES:
:ID:       WBMKYIC5ugvzqU0OYXeLGf9v@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Chihuahuas vs. Grizzlies Chihuahuas vs. Grizzlies

Follow on MiLB First Pitch  https //stza.co/+wmzM-1

Shop  https //stza.co/+wmzM-3D

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Chihuahuas vs. Grizzlies
END:VALARM
DTSTART:20180518T003500Z
DTEND:20180518T033500Z
UID:WBMKYIC5ugvzqU0OYXeLGf9v@stanza.co
SUMMARY:Chihuahuas vs. Grizzlies
DESCRIPTION:Chihuahuas vs. Grizzlies\n\nFollow on MiLB First Pitch: https://stza.co/+wmzM-1\n\nShop: https://stza.co/+wmzM-3D\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144522Z
LAST-MODIFIED:20180213T144522Z
TRANSP:OPAQUE
END:VEVENT
* Chihuahuas vs. Grizzlies
<2018-05-18 Fri 20:05-23:05>
:PROPERTIES:
:ID:       YPs-BN8vGnGVGdlBPg1zMuu-@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Chihuahuas vs. Grizzlies Chihuahuas vs. Grizzlies

Follow on MiLB First Pitch  https //stza.co/+wmzN-r

Shop  https //stza.co/+wmzN-3F

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Chihuahuas vs. Grizzlies
END:VALARM
DTSTART:20180519T010500Z
DTEND:20180519T040500Z
UID:YPs-BN8vGnGVGdlBPg1zMuu-@stanza.co
SUMMARY:Chihuahuas vs. Grizzlies
DESCRIPTION:Chihuahuas vs. Grizzlies\n\nFollow on MiLB First Pitch: https://stza.co/+wmzN-r\n\nShop: https://stza.co/+wmzN-3F\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144522Z
LAST-MODIFIED:20180213T144522Z
TRANSP:OPAQUE
END:VEVENT
* Chihuahuas vs. Grizzlies
<2018-05-19 Sat 20:05-23:05>
:PROPERTIES:
:ID:       Sa0VsrGHyeFwWPQ7YqmCalaU@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Chihuahuas vs. Grizzlies Chihuahuas vs. Grizzlies

Follow on MiLB First Pitch  https //stza.co/+wmzQ-1r

Shop  https //stza.co/+wmzQ-3S

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Chihuahuas vs. Grizzlies
END:VALARM
DTSTART:20180520T010500Z
DTEND:20180520T040500Z
UID:Sa0VsrGHyeFwWPQ7YqmCalaU@stanza.co
SUMMARY:Chihuahuas vs. Grizzlies
DESCRIPTION:Chihuahuas vs. Grizzlies\n\nFollow on MiLB First Pitch: https://stza.co/+wmzQ-1r\n\nShop: https://stza.co/+wmzQ-3S\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144522Z
LAST-MODIFIED:20180213T144522Z
TRANSP:OPAQUE
END:VEVENT
* Chihuahuas vs. Grizzlies
<2018-05-20 Sun 19:05-22:05>
:PROPERTIES:
:ID:       TH-4VtwuzdnuYGzoUQAJ7nf-@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Chihuahuas vs. Grizzlies Chihuahuas vs. Grizzlies

Follow on MiLB First Pitch  https //stza.co/+wmzR-2M

Shop  https //stza.co/+wmzR-2f

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Chihuahuas vs. Grizzlies
END:VALARM
DTSTART:20180521T000500Z
DTEND:20180521T030500Z
UID:TH-4VtwuzdnuYGzoUQAJ7nf-@stanza.co
SUMMARY:Chihuahuas vs. Grizzlies
DESCRIPTION:Chihuahuas vs. Grizzlies\n\nFollow on MiLB First Pitch: https://stza.co/+wmzR-2M\n\nShop: https://stza.co/+wmzR-2f\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144522Z
LAST-MODIFIED:20180213T144522Z
TRANSP:OPAQUE
END:VEVENT
* Chihuahuas @ Rainiers
<2018-05-21 Mon 20:05-23:05>
:PROPERTIES:
:ID:       IfJ6xQVMZeQgUzR6-68Be1uD@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Chihuahuas @ Rainiers Chihuahuas @ Rainiers

Follow on MiLB First Pitch  https //stza.co/+wjxs-1l

Shop  https //stza.co/+wjxs-e

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Chihuahuas @ Rainiers
END:VALARM
DTSTART:20180522T010500Z
DTEND:20180522T040500Z
UID:IfJ6xQVMZeQgUzR6-68Be1uD@stanza.co
SUMMARY:Chihuahuas @ Rainiers
DESCRIPTION:Chihuahuas @ Rainiers\n\nFollow on MiLB First Pitch: https://stza.co/+wjxs-1l\n\nShop: https://stza.co/+wjxs-e\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144522Z
LAST-MODIFIED:20180213T144522Z
TRANSP:OPAQUE
END:VEVENT
* Chihuahuas @ Rainiers
<2018-05-22 Tue 20:05-23:05>
:PROPERTIES:
:ID:       863mRFtUL5AVojrkgwtHlXeS@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Chihuahuas @ Rainiers Chihuahuas @ Rainiers

Follow on MiLB First Pitch  https //stza.co/+wjxt-2F

Shop  https //stza.co/+wjxt-3i

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Chihuahuas @ Rainiers
END:VALARM
DTSTART:20180523T010500Z
DTEND:20180523T040500Z
UID:863mRFtUL5AVojrkgwtHlXeS@stanza.co
SUMMARY:Chihuahuas @ Rainiers
DESCRIPTION:Chihuahuas @ Rainiers\n\nFollow on MiLB First Pitch: https://stza.co/+wjxt-2F\n\nShop: https://stza.co/+wjxt-3i\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144522Z
LAST-MODIFIED:20180213T144522Z
TRANSP:OPAQUE
END:VEVENT
* Chihuahuas @ Rainiers
<2018-05-23 Wed 13:35-16:35>
:PROPERTIES:
:ID:       lU5t8GPOSdwfjPIPCbp8ooFV@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Chihuahuas @ Rainiers Chihuahuas @ Rainiers

Follow on MiLB First Pitch  https //stza.co/+wjxu-3P

Shop  https //stza.co/+wjxu-3D

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Chihuahuas @ Rainiers
END:VALARM
DTSTART:20180523T183500Z
DTEND:20180523T213500Z
UID:lU5t8GPOSdwfjPIPCbp8ooFV@stanza.co
SUMMARY:Chihuahuas @ Rainiers
DESCRIPTION:Chihuahuas @ Rainiers\n\nFollow on MiLB First Pitch: https://stza.co/+wjxu-3P\n\nShop: https://stza.co/+wjxu-3D\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144522Z
LAST-MODIFIED:20180213T144522Z
TRANSP:OPAQUE
END:VEVENT
* Chihuahuas @ Rainiers
<2018-05-24 Thu 21:05>--<2018-05-25 Fri 00:05>
:PROPERTIES:
:ID:       S-QDhtYVC2aaM1c11nEDNheP@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Chihuahuas @ Rainiers Chihuahuas @ Rainiers

Follow on MiLB First Pitch  https //stza.co/+wjxv-1m

Shop  https //stza.co/+wjxv-1g

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Chihuahuas @ Rainiers
END:VALARM
DTSTART:20180525T020500Z
DTEND:20180525T050500Z
UID:S-QDhtYVC2aaM1c11nEDNheP@stanza.co
SUMMARY:Chihuahuas @ Rainiers
DESCRIPTION:Chihuahuas @ Rainiers\n\nFollow on MiLB First Pitch: https://stza.co/+wjxv-1m\n\nShop: https://stza.co/+wjxv-1g\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144522Z
LAST-MODIFIED:20180213T144522Z
TRANSP:OPAQUE
END:VEVENT
* Chihuahuas @ Grizzlies
<2018-05-25 Fri 21:05>--<2018-05-26 Sat 00:05>
:PROPERTIES:
:ID:       2_-alIeCmtYjPFPAx7of357W@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Chihuahuas @ Grizzlies Chihuahuas @ Grizzlies

Follow on MiLB First Pitch  https //stza.co/+wjx3-1s

Shop  https //stza.co/+wjx3-3s

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Chihuahuas @ Grizzlies
END:VALARM
DTSTART:20180526T020500Z
DTEND:20180526T050500Z
UID:2_-alIeCmtYjPFPAx7of357W@stanza.co
SUMMARY:Chihuahuas @ Grizzlies
DESCRIPTION:Chihuahuas @ Grizzlies\n\nFollow on MiLB First Pitch: https://stza.co/+wjx3-1s\n\nShop: https://stza.co/+wjx3-3s\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144522Z
LAST-MODIFIED:20180213T144522Z
TRANSP:OPAQUE
END:VEVENT
* Chihuahuas @ Grizzlies
<2018-05-26 Sat 21:05>--<2018-05-27 Sun 00:05>
:PROPERTIES:
:ID:       AUTNXpCE-UYMgFJHSTM0ARjx@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Chihuahuas @ Grizzlies Chihuahuas @ Grizzlies

Follow on MiLB First Pitch  https //stza.co/+wjx4-3I

Shop  https //stza.co/+wjx4-2y

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Chihuahuas @ Grizzlies
END:VALARM
DTSTART:20180527T020500Z
DTEND:20180527T050500Z
UID:AUTNXpCE-UYMgFJHSTM0ARjx@stanza.co
SUMMARY:Chihuahuas @ Grizzlies
DESCRIPTION:Chihuahuas @ Grizzlies\n\nFollow on MiLB First Pitch: https://stza.co/+wjx4-3I\n\nShop: https://stza.co/+wjx4-2y\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144522Z
LAST-MODIFIED:20180213T144522Z
TRANSP:OPAQUE
END:VEVENT
* Chihuahuas @ Grizzlies
<2018-05-27 Sun 15:05-18:05>
:PROPERTIES:
:ID:       gi4yqT9ipbc55tf4Pg9-ujMo@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Chihuahuas @ Grizzlies Chihuahuas @ Grizzlies

Follow on MiLB First Pitch  https //stza.co/+wjx5-35

Shop  https //stza.co/+wjx5-3G

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Chihuahuas @ Grizzlies
END:VALARM
DTSTART:20180527T200500Z
DTEND:20180527T230500Z
UID:gi4yqT9ipbc55tf4Pg9-ujMo@stanza.co
SUMMARY:Chihuahuas @ Grizzlies
DESCRIPTION:Chihuahuas @ Grizzlies\n\nFollow on MiLB First Pitch: https://stza.co/+wjx5-35\n\nShop: https://stza.co/+wjx5-3G\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144522Z
LAST-MODIFIED:20180213T144522Z
TRANSP:OPAQUE
END:VEVENT
* Chihuahuas @ Grizzlies
<2018-05-28 Mon 18:05-21:05>
:PROPERTIES:
:ID:       9dRY6EvByiMASgQ7k4DP5VUj@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Chihuahuas @ Grizzlies Chihuahuas @ Grizzlies

Follow on MiLB First Pitch  https //stza.co/+wjx6-2a

Shop  https //stza.co/+wjx6-2N

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Chihuahuas @ Grizzlies
END:VALARM
DTSTART:20180528T230500Z
DTEND:20180529T020500Z
UID:9dRY6EvByiMASgQ7k4DP5VUj@stanza.co
SUMMARY:Chihuahuas @ Grizzlies
DESCRIPTION:Chihuahuas @ Grizzlies\n\nFollow on MiLB First Pitch: https://stza.co/+wjx6-2a\n\nShop: https://stza.co/+wjx6-2N\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144522Z
LAST-MODIFIED:20180213T144522Z
TRANSP:OPAQUE
END:VEVENT
* Chihuahuas @ Grizzlies
<2018-05-29 Tue 13:05-16:05>
:PROPERTIES:
:ID:       xUlhqdQu2mCgzVJ2cT44X6w8@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Chihuahuas @ Grizzlies Chihuahuas @ Grizzlies

Follow on MiLB First Pitch  https //stza.co/+wjx7-33

Shop  https //stza.co/+wjx7-R

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Chihuahuas @ Grizzlies
END:VALARM
DTSTART:20180529T180500Z
DTEND:20180529T210500Z
UID:xUlhqdQu2mCgzVJ2cT44X6w8@stanza.co
SUMMARY:Chihuahuas @ Grizzlies
DESCRIPTION:Chihuahuas @ Grizzlies\n\nFollow on MiLB First Pitch: https://stza.co/+wjx7-33\n\nShop: https://stza.co/+wjx7-R\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144522Z
LAST-MODIFIED:20180213T144522Z
TRANSP:OPAQUE
END:VEVENT
* Chihuahuas vs. River Cats
<2018-05-30 Wed 19:35-22:35>
:PROPERTIES:
:ID:       DfzZlADquixfViYHKwyOqkQJ@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Chihuahuas vs. River Cats Chihuahuas vs. River Cats

Follow on MiLB First Pitch  https //stza.co/+wmzU-3i

Shop  https //stza.co/+wmzU-1p

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Chihuahuas vs. River Cats
END:VALARM
DTSTART:20180531T003500Z
DTEND:20180531T033500Z
UID:DfzZlADquixfViYHKwyOqkQJ@stanza.co
SUMMARY:Chihuahuas vs. River Cats
DESCRIPTION:Chihuahuas vs. River Cats\n\nFollow on MiLB First Pitch: https://stza.co/+wmzU-3i\n\nShop: https://stza.co/+wmzU-1p\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144522Z
LAST-MODIFIED:20180213T144522Z
TRANSP:OPAQUE
END:VEVENT
* Chihuahuas vs. River Cats
<2018-05-31 Thu 19:35-22:35>
:PROPERTIES:
:ID:       5GWJoXiD1RzfHUY7Snidv7iq@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Chihuahuas vs. River Cats Chihuahuas vs. River Cats

Follow on MiLB First Pitch  https //stza.co/+wmzV-16

Shop  https //stza.co/+wmzV-1m

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Chihuahuas vs. River Cats
END:VALARM
DTSTART:20180601T003500Z
DTEND:20180601T033500Z
UID:5GWJoXiD1RzfHUY7Snidv7iq@stanza.co
SUMMARY:Chihuahuas vs. River Cats
DESCRIPTION:Chihuahuas vs. River Cats\n\nFollow on MiLB First Pitch: https://stza.co/+wmzV-16\n\nShop: https://stza.co/+wmzV-1m\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144522Z
LAST-MODIFIED:20180213T144522Z
TRANSP:OPAQUE
END:VEVENT
* Chihuahuas vs. River Cats
<2018-06-01 Fri 20:05-23:05>
:PROPERTIES:
:ID:       dSVirCUOqf_bb0H18QSOKxUx@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Chihuahuas vs. River Cats Chihuahuas vs. River Cats

Follow on MiLB First Pitch  https //stza.co/+wmzX-3X

Shop  https //stza.co/+wmzX-Z

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Chihuahuas vs. River Cats
END:VALARM
DTSTART:20180602T010500Z
DTEND:20180602T040500Z
UID:dSVirCUOqf_bb0H18QSOKxUx@stanza.co
SUMMARY:Chihuahuas vs. River Cats
DESCRIPTION:Chihuahuas vs. River Cats\n\nFollow on MiLB First Pitch: https://stza.co/+wmzX-3X\n\nShop: https://stza.co/+wmzX-Z\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144522Z
LAST-MODIFIED:20180213T144522Z
TRANSP:OPAQUE
END:VEVENT
* Chihuahuas vs. River Cats
<2018-06-02 Sat 20:05-23:05>
:PROPERTIES:
:ID:       bcZ3PhHmZWyDrSuB3x_Xh51E@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Chihuahuas vs. River Cats Chihuahuas vs. River Cats

Follow on MiLB First Pitch  https //stza.co/+wmzZ-2M

Shop  https //stza.co/+wmzZ-2N

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Chihuahuas vs. River Cats
END:VALARM
DTSTART:20180603T010500Z
DTEND:20180603T040500Z
UID:bcZ3PhHmZWyDrSuB3x_Xh51E@stanza.co
SUMMARY:Chihuahuas vs. River Cats
DESCRIPTION:Chihuahuas vs. River Cats\n\nFollow on MiLB First Pitch: https://stza.co/+wmzZ-2M\n\nShop: https://stza.co/+wmzZ-2N\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144522Z
LAST-MODIFIED:20180213T144522Z
TRANSP:OPAQUE
END:VEVENT
* Chihuahuas vs. River Cats
<2018-06-03 Sun 19:05-22:05>
:PROPERTIES:
:ID:       bbY1zTDv_WyDkIwvUm2nhPXi@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Chihuahuas vs. River Cats Chihuahuas vs. River Cats

Follow on MiLB First Pitch  https //stza.co/+wmA0-r

Shop  https //stza.co/+wmA0-2D

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Chihuahuas vs. River Cats
END:VALARM
DTSTART:20180604T000500Z
DTEND:20180604T030500Z
UID:bbY1zTDv_WyDkIwvUm2nhPXi@stanza.co
SUMMARY:Chihuahuas vs. River Cats
DESCRIPTION:Chihuahuas vs. River Cats\n\nFollow on MiLB First Pitch: https://stza.co/+wmA0-r\n\nShop: https://stza.co/+wmA0-2D\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144522Z
LAST-MODIFIED:20180213T144522Z
TRANSP:OPAQUE
END:VEVENT
* Chihuahuas @ Storm Chasers
<2018-06-05 Tue 19:05-22:05>
:PROPERTIES:
:ID:       zykzqGp86SBcq7-so1nYW2Or@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Chihuahuas @ Storm Chasers Chihuahuas @ Storm Chasers

Follow on MiLB First Pitch  https //stza.co/+whD6-3k

Shop  https //stza.co/+whD6-2

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Chihuahuas @ Storm Chasers
END:VALARM
DTSTART:20180606T000500Z
DTEND:20180606T030500Z
UID:zykzqGp86SBcq7-so1nYW2Or@stanza.co
SUMMARY:Chihuahuas @ Storm Chasers
DESCRIPTION:Chihuahuas @ Storm Chasers\n\nFollow on MiLB First Pitch: https://stza.co/+whD6-3k\n\nShop: https://stza.co/+whD6-2\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144522Z
LAST-MODIFIED:20180213T144522Z
TRANSP:OPAQUE
END:VEVENT
* Chihuahuas @ Storm Chasers
<2018-06-06 Wed 19:05-22:05>
:PROPERTIES:
:ID:       RyGGKxYECh37KmnSe8G1SjxP@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Chihuahuas @ Storm Chasers Chihuahuas @ Storm Chasers

Follow on MiLB First Pitch  https //stza.co/+whD7-w

Shop  https //stza.co/+whD7-38

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Chihuahuas @ Storm Chasers
END:VALARM
DTSTART:20180607T000500Z
DTEND:20180607T030500Z
UID:RyGGKxYECh37KmnSe8G1SjxP@stanza.co
SUMMARY:Chihuahuas @ Storm Chasers
DESCRIPTION:Chihuahuas @ Storm Chasers\n\nFollow on MiLB First Pitch: https://stza.co/+whD7-w\n\nShop: https://stza.co/+whD7-38\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144522Z
LAST-MODIFIED:20180213T144522Z
TRANSP:OPAQUE
END:VEVENT
* Chihuahuas @ Storm Chasers
<2018-06-07 Thu 19:05-22:05>
:PROPERTIES:
:ID:       6Vnc8wgJ0vhiAcaTJmgGmWCD@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Chihuahuas @ Storm Chasers Chihuahuas @ Storm Chasers

Follow on MiLB First Pitch  https //stza.co/+whD8-1D

Shop  https //stza.co/+whD8-_

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Chihuahuas @ Storm Chasers
END:VALARM
DTSTART:20180608T000500Z
DTEND:20180608T030500Z
UID:6Vnc8wgJ0vhiAcaTJmgGmWCD@stanza.co
SUMMARY:Chihuahuas @ Storm Chasers
DESCRIPTION:Chihuahuas @ Storm Chasers\n\nFollow on MiLB First Pitch: https://stza.co/+whD8-1D\n\nShop: https://stza.co/+whD8-_\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144522Z
LAST-MODIFIED:20180213T144522Z
TRANSP:OPAQUE
END:VEVENT
* Chihuahuas @ Cubs
<2018-06-08 Fri 19:08-22:08>
:PROPERTIES:
:ID:       aTYvCbSf-n032Q3KKsOUh9S_@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Chihuahuas @ Cubs Chihuahuas @ Cubs

Follow on MiLB First Pitch  https //stza.co/+vKyl-3M

Shop  https //stza.co/+vKyl-3W

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Chihuahuas @ Cubs
END:VALARM
DTSTART:20180609T000800Z
DTEND:20180609T030800Z
UID:aTYvCbSf-n032Q3KKsOUh9S_@stanza.co
SUMMARY:Chihuahuas @ Cubs
DESCRIPTION:Chihuahuas @ Cubs\n\nFollow on MiLB First Pitch: https://stza.co/+vKyl-3M\n\nShop: https://stza.co/+vKyl-3W\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144522Z
LAST-MODIFIED:20180213T144522Z
TRANSP:OPAQUE
END:VEVENT
* Chihuahuas @ Cubs
<2018-06-09 Sat 19:08-22:08>
:PROPERTIES:
:ID:       NHgBqfAEiILNlNShXei7iH68@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Chihuahuas @ Cubs Chihuahuas @ Cubs

Follow on MiLB First Pitch  https //stza.co/+vKym-3p

Shop  https //stza.co/+vKym-3E

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Chihuahuas @ Cubs
END:VALARM
DTSTART:20180610T000800Z
DTEND:20180610T030800Z
UID:NHgBqfAEiILNlNShXei7iH68@stanza.co
SUMMARY:Chihuahuas @ Cubs
DESCRIPTION:Chihuahuas @ Cubs\n\nFollow on MiLB First Pitch: https://stza.co/+vKym-3p\n\nShop: https://stza.co/+vKym-3E\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144522Z
LAST-MODIFIED:20180213T144522Z
TRANSP:OPAQUE
END:VEVENT
* Chihuahuas @ Cubs
<2018-06-10 Sun 13:08-16:08>
:PROPERTIES:
:ID:       dIaQ0HMcgyVgwUvNx2hP3oGN@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Chihuahuas @ Cubs Chihuahuas @ Cubs

Follow on MiLB First Pitch  https //stza.co/+xDLh-2B

Shop  https //stza.co/+xDLh-2C

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Chihuahuas @ Cubs
END:VALARM
DTSTART:20180610T180800Z
DTEND:20180610T210800Z
UID:dIaQ0HMcgyVgwUvNx2hP3oGN@stanza.co
SUMMARY:Chihuahuas @ Cubs
DESCRIPTION:Chihuahuas @ Cubs\n\nFollow on MiLB First Pitch: https://stza.co/+xDLh-2B\n\nShop: https://stza.co/+xDLh-2C\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144522Z
LAST-MODIFIED:20180213T144522Z
TRANSP:OPAQUE
END:VEVENT
* Chihuahuas @ Cubs
<2018-06-11 Mon 12:08-15:08>
:PROPERTIES:
:ID:       u_A45bjTuFzZxiGuX5aXKSNH@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Chihuahuas @ Cubs Chihuahuas @ Cubs

Follow on MiLB First Pitch  https //stza.co/+vKyo-1r

Shop  https //stza.co/+vKyo-f

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Chihuahuas @ Cubs
END:VALARM
DTSTART:20180611T170800Z
DTEND:20180611T200800Z
UID:u_A45bjTuFzZxiGuX5aXKSNH@stanza.co
SUMMARY:Chihuahuas @ Cubs
DESCRIPTION:Chihuahuas @ Cubs\n\nFollow on MiLB First Pitch: https://stza.co/+vKyo-1r\n\nShop: https://stza.co/+vKyo-f\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144522Z
LAST-MODIFIED:20180213T144522Z
TRANSP:OPAQUE
END:VEVENT
* Chihuahuas vs. Sounds
<2018-06-13 Wed 20:05-23:05>
:PROPERTIES:
:ID:       CZYwG4Nx4AaEbr0ym4s6mMAU@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Chihuahuas vs. Sounds Chihuahuas vs. Sounds

Follow on MiLB First Pitch  https //stza.co/+wmA1-1E

Shop  https //stza.co/+wmA1-y

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Chihuahuas vs. Sounds
END:VALARM
DTSTART:20180614T010500Z
DTEND:20180614T040500Z
UID:CZYwG4Nx4AaEbr0ym4s6mMAU@stanza.co
SUMMARY:Chihuahuas vs. Sounds
DESCRIPTION:Chihuahuas vs. Sounds\n\nFollow on MiLB First Pitch: https://stza.co/+wmA1-1E\n\nShop: https://stza.co/+wmA1-y\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144522Z
LAST-MODIFIED:20180213T144522Z
TRANSP:OPAQUE
END:VEVENT
* Chihuahuas vs. Sounds
<2018-06-14 Thu 20:05-23:05>
:PROPERTIES:
:ID:       gasgxzr5tIPSd2kua0LGZHHY@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Chihuahuas vs. Sounds Chihuahuas vs. Sounds

Follow on MiLB First Pitch  https //stza.co/+wmA3-2x

Shop  https //stza.co/+wmA3-1y

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Chihuahuas vs. Sounds
END:VALARM
DTSTART:20180615T010500Z
DTEND:20180615T040500Z
UID:gasgxzr5tIPSd2kua0LGZHHY@stanza.co
SUMMARY:Chihuahuas vs. Sounds
DESCRIPTION:Chihuahuas vs. Sounds\n\nFollow on MiLB First Pitch: https://stza.co/+wmA3-2x\n\nShop: https://stza.co/+wmA3-1y\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144522Z
LAST-MODIFIED:20180213T144522Z
TRANSP:OPAQUE
END:VEVENT
* Chihuahuas vs. Sounds
<2018-06-15 Fri 20:05-23:05>
:PROPERTIES:
:ID:       hM7IcX74AQi-3fzyTqaVgLm7@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Chihuahuas vs. Sounds Chihuahuas vs. Sounds

Follow on MiLB First Pitch  https //stza.co/+wmA6-3I

Shop  https //stza.co/+wmA6-M

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Chihuahuas vs. Sounds
END:VALARM
DTSTART:20180616T010500Z
DTEND:20180616T040500Z
UID:hM7IcX74AQi-3fzyTqaVgLm7@stanza.co
SUMMARY:Chihuahuas vs. Sounds
DESCRIPTION:Chihuahuas vs. Sounds\n\nFollow on MiLB First Pitch: https://stza.co/+wmA6-3I\n\nShop: https://stza.co/+wmA6-M\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144522Z
LAST-MODIFIED:20180213T144522Z
TRANSP:OPAQUE
END:VEVENT
* Chihuahuas vs. Redbirds
<2018-06-16 Sat 20:05-23:05>
:PROPERTIES:
:ID:       R3Pz5nlEMx2tsQDvgwHToeBi@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Chihuahuas vs. Redbirds Chihuahuas vs. Redbirds

Follow on MiLB First Pitch  https //stza.co/+wmA8-3c

Shop  https //stza.co/+wmA8-X

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Chihuahuas vs. Redbirds
END:VALARM
DTSTART:20180617T010500Z
DTEND:20180617T040500Z
UID:R3Pz5nlEMx2tsQDvgwHToeBi@stanza.co
SUMMARY:Chihuahuas vs. Redbirds
DESCRIPTION:Chihuahuas vs. Redbirds\n\nFollow on MiLB First Pitch: https://stza.co/+wmA8-3c\n\nShop: https://stza.co/+wmA8-X\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144522Z
LAST-MODIFIED:20180213T144522Z
TRANSP:OPAQUE
END:VEVENT
* Chihuahuas vs. Redbirds
<2018-06-17 Sun 19:05-22:05>
:PROPERTIES:
:ID:       SpwyxQmV-hMP-b0DMb1OKads@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Chihuahuas vs. Redbirds Chihuahuas vs. Redbirds

Follow on MiLB First Pitch  https //stza.co/+wmA9-I

Shop  https //stza.co/+wmA9-2S

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Chihuahuas vs. Redbirds
END:VALARM
DTSTART:20180618T000500Z
DTEND:20180618T030500Z
UID:SpwyxQmV-hMP-b0DMb1OKads@stanza.co
SUMMARY:Chihuahuas vs. Redbirds
DESCRIPTION:Chihuahuas vs. Redbirds\n\nFollow on MiLB First Pitch: https://stza.co/+wmA9-I\n\nShop: https://stza.co/+wmA9-2S\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144522Z
LAST-MODIFIED:20180213T144522Z
TRANSP:OPAQUE
END:VEVENT
* Chihuahuas vs. Redbirds
<2018-06-18 Mon 20:05-23:05>
:PROPERTIES:
:ID:       X8sT2sNKHzwcgFRik2Rka-wH@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Chihuahuas vs. Redbirds Chihuahuas vs. Redbirds

Follow on MiLB First Pitch  https //stza.co/+wmAc-d

Shop  https //stza.co/+wmAc-1O

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Chihuahuas vs. Redbirds
END:VALARM
DTSTART:20180619T010500Z
DTEND:20180619T040500Z
UID:X8sT2sNKHzwcgFRik2Rka-wH@stanza.co
SUMMARY:Chihuahuas vs. Redbirds
DESCRIPTION:Chihuahuas vs. Redbirds\n\nFollow on MiLB First Pitch: https://stza.co/+wmAc-d\n\nShop: https://stza.co/+wmAc-1O\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144522Z
LAST-MODIFIED:20180213T144522Z
TRANSP:OPAQUE
END:VEVENT
* Chihuahuas vs. Redbirds
<2018-06-19 Tue 20:05-23:05>
:PROPERTIES:
:ID:       RFTKtDBDkq7WAXzFtdCaSv5e@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Chihuahuas vs. Redbirds Chihuahuas vs. Redbirds

Follow on MiLB First Pitch  https //stza.co/+wmAe-2K

Shop  https //stza.co/+wmAe-A

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Chihuahuas vs. Redbirds
END:VALARM
DTSTART:20180620T010500Z
DTEND:20180620T040500Z
UID:RFTKtDBDkq7WAXzFtdCaSv5e@stanza.co
SUMMARY:Chihuahuas vs. Redbirds
DESCRIPTION:Chihuahuas vs. Redbirds\n\nFollow on MiLB First Pitch: https://stza.co/+wmAe-2K\n\nShop: https://stza.co/+wmAe-A\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144522Z
LAST-MODIFIED:20180213T144522Z
TRANSP:OPAQUE
END:VEVENT
* Chihuahuas @ River Cats
<2018-06-21 Thu 21:05>--<2018-06-22 Fri 00:05>
:PROPERTIES:
:ID:       CjoVjbtE4LwMU2eddYMsTcle@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Chihuahuas @ River Cats Chihuahuas @ River Cats

Follow on MiLB First Pitch  https //stza.co/+wjxk-1X

Shop  https //stza.co/+wjxk-J

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Chihuahuas @ River Cats
END:VALARM
DTSTART:20180622T020500Z
DTEND:20180622T050500Z
UID:CjoVjbtE4LwMU2eddYMsTcle@stanza.co
SUMMARY:Chihuahuas @ River Cats
DESCRIPTION:Chihuahuas @ River Cats\n\nFollow on MiLB First Pitch: https://stza.co/+wjxk-1X\n\nShop: https://stza.co/+wjxk-J\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144522Z
LAST-MODIFIED:20180213T144522Z
TRANSP:OPAQUE
END:VEVENT
* Chihuahuas @ River Cats
<2018-06-22 Fri 21:05>--<2018-06-23 Sat 00:05>
:PROPERTIES:
:ID:       _ln00EoLb21wBbpGCwN9n0VE@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Chihuahuas @ River Cats Chihuahuas @ River Cats

Follow on MiLB First Pitch  https //stza.co/+wjxl-C

Shop  https //stza.co/+wjxl-3u

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Chihuahuas @ River Cats
END:VALARM
DTSTART:20180623T020500Z
DTEND:20180623T050500Z
UID:_ln00EoLb21wBbpGCwN9n0VE@stanza.co
SUMMARY:Chihuahuas @ River Cats
DESCRIPTION:Chihuahuas @ River Cats\n\nFollow on MiLB First Pitch: https://stza.co/+wjxl-C\n\nShop: https://stza.co/+wjxl-3u\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144522Z
LAST-MODIFIED:20180213T144522Z
TRANSP:OPAQUE
END:VEVENT
* Chihuahuas @ River Cats
<2018-06-23 Sat 21:05>--<2018-06-24 Sun 00:05>
:PROPERTIES:
:ID:       g1DHn4xQxX86kIFUZcbQKxYn@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Chihuahuas @ River Cats Chihuahuas @ River Cats

Follow on MiLB First Pitch  https //stza.co/+wjxm-3n

Shop  https //stza.co/+wjxm-3N

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Chihuahuas @ River Cats
END:VALARM
DTSTART:20180624T020500Z
DTEND:20180624T050500Z
UID:g1DHn4xQxX86kIFUZcbQKxYn@stanza.co
SUMMARY:Chihuahuas @ River Cats
DESCRIPTION:Chihuahuas @ River Cats\n\nFollow on MiLB First Pitch: https://stza.co/+wjxm-3n\n\nShop: https://stza.co/+wjxm-3N\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144522Z
LAST-MODIFIED:20180213T144522Z
TRANSP:OPAQUE
END:VEVENT
* Chihuahuas @ River Cats
<2018-06-24 Sun 15:05-18:05>
:PROPERTIES:
:ID:       jkgD7VYd7_pg0mg3j9k_tZgF@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Chihuahuas @ River Cats Chihuahuas @ River Cats

Follow on MiLB First Pitch  https //stza.co/+wjxn-_

Shop  https //stza.co/+wjxn-3X

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Chihuahuas @ River Cats
END:VALARM
DTSTART:20180624T200500Z
DTEND:20180624T230500Z
UID:jkgD7VYd7_pg0mg3j9k_tZgF@stanza.co
SUMMARY:Chihuahuas @ River Cats
DESCRIPTION:Chihuahuas @ River Cats\n\nFollow on MiLB First Pitch: https://stza.co/+wjxn-_\n\nShop: https://stza.co/+wjxn-3X\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144522Z
LAST-MODIFIED:20180213T144522Z
TRANSP:OPAQUE
END:VEVENT
* Chihuahuas vs. Grizzlies
<2018-06-25 Mon 20:05-23:05>
:PROPERTIES:
:ID:       cCyOvqzgl0PPkEvNQ3VU0C3b@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Chihuahuas vs. Grizzlies Chihuahuas vs. Grizzlies

Follow on MiLB First Pitch  https //stza.co/+wmAf-S

Shop  https //stza.co/+wmAf-2X

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Chihuahuas vs. Grizzlies
END:VALARM
DTSTART:20180626T010500Z
DTEND:20180626T040500Z
UID:cCyOvqzgl0PPkEvNQ3VU0C3b@stanza.co
SUMMARY:Chihuahuas vs. Grizzlies
DESCRIPTION:Chihuahuas vs. Grizzlies\n\nFollow on MiLB First Pitch: https://stza.co/+wmAf-S\n\nShop: https://stza.co/+wmAf-2X\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144522Z
LAST-MODIFIED:20180213T144522Z
TRANSP:OPAQUE
END:VEVENT
* Chihuahuas vs. Grizzlies
<2018-06-26 Tue 20:05-23:05>
:PROPERTIES:
:ID:       krFj7NSbXAv9ZmFmUKMFIFMl@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Chihuahuas vs. Grizzlies Chihuahuas vs. Grizzlies

Follow on MiLB First Pitch  https //stza.co/+wmAi-11

Shop  https //stza.co/+wmAi-10

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Chihuahuas vs. Grizzlies
END:VALARM
DTSTART:20180627T010500Z
DTEND:20180627T040500Z
UID:krFj7NSbXAv9ZmFmUKMFIFMl@stanza.co
SUMMARY:Chihuahuas vs. Grizzlies
DESCRIPTION:Chihuahuas vs. Grizzlies\n\nFollow on MiLB First Pitch: https://stza.co/+wmAi-11\n\nShop: https://stza.co/+wmAi-10\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144522Z
LAST-MODIFIED:20180213T144522Z
TRANSP:OPAQUE
END:VEVENT
* Chihuahuas vs. Grizzlies
<2018-06-27 Wed 20:05-23:05>
:PROPERTIES:
:ID:       3PrSfqJXA9SSvJJexoqnJQF-@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Chihuahuas vs. Grizzlies Chihuahuas vs. Grizzlies

Follow on MiLB First Pitch  https //stza.co/+wmAj-3

Shop  https //stza.co/+wmAj-1Z

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Chihuahuas vs. Grizzlies
END:VALARM
DTSTART:20180628T010500Z
DTEND:20180628T040500Z
UID:3PrSfqJXA9SSvJJexoqnJQF-@stanza.co
SUMMARY:Chihuahuas vs. Grizzlies
DESCRIPTION:Chihuahuas vs. Grizzlies\n\nFollow on MiLB First Pitch: https://stza.co/+wmAj-3\n\nShop: https://stza.co/+wmAj-1Z\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144522Z
LAST-MODIFIED:20180213T144522Z
TRANSP:OPAQUE
END:VEVENT
* Chihuahuas vs. Grizzlies
<2018-06-28 Thu 20:05-23:05>
:PROPERTIES:
:ID:       MOaVniSxY7IeOElOALwJk7Ct@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Chihuahuas vs. Grizzlies Chihuahuas vs. Grizzlies

Follow on MiLB First Pitch  https //stza.co/+wmAl-1v

Shop  https //stza.co/+wmAl-3C

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Chihuahuas vs. Grizzlies
END:VALARM
DTSTART:20180629T010500Z
DTEND:20180629T040500Z
UID:MOaVniSxY7IeOElOALwJk7Ct@stanza.co
SUMMARY:Chihuahuas vs. Grizzlies
DESCRIPTION:Chihuahuas vs. Grizzlies\n\nFollow on MiLB First Pitch: https://stza.co/+wmAl-1v\n\nShop: https://stza.co/+wmAl-3C\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144522Z
LAST-MODIFIED:20180213T144522Z
TRANSP:OPAQUE
END:VEVENT
* Chihuahuas vs. Isotopes
<2018-06-29 Fri 20:05-23:05>
:PROPERTIES:
:ID:       b-a_yLh6PB6xqpXrvwjnLSLk@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Chihuahuas vs. Isotopes Chihuahuas vs. Isotopes

Follow on MiLB First Pitch  https //stza.co/+wmAn-3J

Shop  https //stza.co/+wmAn-36

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Chihuahuas vs. Isotopes
END:VALARM
DTSTART:20180630T010500Z
DTEND:20180630T040500Z
UID:b-a_yLh6PB6xqpXrvwjnLSLk@stanza.co
SUMMARY:Chihuahuas vs. Isotopes
DESCRIPTION:Chihuahuas vs. Isotopes\n\nFollow on MiLB First Pitch: https://stza.co/+wmAn-3J\n\nShop: https://stza.co/+wmAn-36\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144522Z
LAST-MODIFIED:20180213T144522Z
TRANSP:OPAQUE
END:VEVENT
* Chihuahuas vs. Isotopes
<2018-06-30 Sat 20:05-23:05>
:PROPERTIES:
:ID:       LqPhy-KE0EJ2rJhO_HFDV0e4@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Chihuahuas vs. Isotopes Chihuahuas vs. Isotopes

Follow on MiLB First Pitch  https //stza.co/+wmAp-2$

Shop  https //stza.co/+wmAp-1P

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Chihuahuas vs. Isotopes
END:VALARM
DTSTART:20180701T010500Z
DTEND:20180701T040500Z
UID:LqPhy-KE0EJ2rJhO_HFDV0e4@stanza.co
SUMMARY:Chihuahuas vs. Isotopes
DESCRIPTION:Chihuahuas vs. Isotopes\n\nFollow on MiLB First Pitch: https://stza.co/+wmAp-2$\n\nShop: https://stza.co/+wmAp-1P\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144522Z
LAST-MODIFIED:20180213T144522Z
TRANSP:OPAQUE
END:VEVENT
* Chihuahuas vs. Isotopes
<2018-07-01 Sun 19:05-22:05>
:PROPERTIES:
:ID:       RCa7iwqkpO6D81k6UzBC6uDT@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Chihuahuas vs. Isotopes Chihuahuas vs. Isotopes

Follow on MiLB First Pitch  https //stza.co/+wmAs-2R

Shop  https //stza.co/+wmAs-19

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Chihuahuas vs. Isotopes
END:VALARM
DTSTART:20180702T000500Z
DTEND:20180702T030500Z
UID:RCa7iwqkpO6D81k6UzBC6uDT@stanza.co
SUMMARY:Chihuahuas vs. Isotopes
DESCRIPTION:Chihuahuas vs. Isotopes\n\nFollow on MiLB First Pitch: https://stza.co/+wmAs-2R\n\nShop: https://stza.co/+wmAs-19\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144522Z
LAST-MODIFIED:20180213T144522Z
TRANSP:OPAQUE
END:VEVENT
* Chihuahuas vs. Isotopes
<2018-07-02 Mon 20:05-23:05>
:PROPERTIES:
:ID:       Z_xG_vUbkDaxS3cAKKoKWYEB@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Chihuahuas vs. Isotopes Chihuahuas vs. Isotopes

Follow on MiLB First Pitch  https //stza.co/+wmAt-27

Shop  https //stza.co/+wmAt-3T

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Chihuahuas vs. Isotopes
END:VALARM
DTSTART:20180703T010500Z
DTEND:20180703T040500Z
UID:Z_xG_vUbkDaxS3cAKKoKWYEB@stanza.co
SUMMARY:Chihuahuas vs. Isotopes
DESCRIPTION:Chihuahuas vs. Isotopes\n\nFollow on MiLB First Pitch: https://stza.co/+wmAt-27\n\nShop: https://stza.co/+wmAt-3T\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144522Z
LAST-MODIFIED:20180213T144522Z
TRANSP:OPAQUE
END:VEVENT
* Chihuahuas vs. Isotopes
<2018-07-03 Tue 20:05-23:05>
:PROPERTIES:
:ID:       W7tvBs0tNPL5V2E0pUX-UaPN@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Chihuahuas vs. Isotopes Chihuahuas vs. Isotopes

Follow on MiLB First Pitch  https //stza.co/+wmAw-2T

Shop  https //stza.co/+wmAw-1Z

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Chihuahuas vs. Isotopes
END:VALARM
DTSTART:20180704T010500Z
DTEND:20180704T040500Z
UID:W7tvBs0tNPL5V2E0pUX-UaPN@stanza.co
SUMMARY:Chihuahuas vs. Isotopes
DESCRIPTION:Chihuahuas vs. Isotopes\n\nFollow on MiLB First Pitch: https://stza.co/+wmAw-2T\n\nShop: https://stza.co/+wmAw-1Z\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144522Z
LAST-MODIFIED:20180213T144522Z
TRANSP:OPAQUE
END:VEVENT
* Chihuahuas @ Bees
<2018-07-04 Wed 19:35-22:35>
:PROPERTIES:
:ID:       ey-HjJ7T8JboagesgZQzVBuk@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Chihuahuas @ Bees Chihuahuas @ Bees

Follow on MiLB First Pitch  https //stza.co/+wmBs-15

Shop  https //stza.co/+wmBs-1a

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Chihuahuas @ Bees
END:VALARM
DTSTART:20180705T003500Z
DTEND:20180705T033500Z
UID:ey-HjJ7T8JboagesgZQzVBuk@stanza.co
SUMMARY:Chihuahuas @ Bees
DESCRIPTION:Chihuahuas @ Bees\n\nFollow on MiLB First Pitch: https://stza.co/+wmBs-15\n\nShop: https://stza.co/+wmBs-1a\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144522Z
LAST-MODIFIED:20180213T144522Z
TRANSP:OPAQUE
END:VEVENT
* Chihuahuas @ Bees
<2018-07-05 Thu 20:05-23:05>
:PROPERTIES:
:ID:       Hi2NmwEoYK8k1xTLFW25r-9v@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Chihuahuas @ Bees Chihuahuas @ Bees

Follow on MiLB First Pitch  https //stza.co/+wmBt-y

Shop  https //stza.co/+wmBt-20

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Chihuahuas @ Bees
END:VALARM
DTSTART:20180706T010500Z
DTEND:20180706T040500Z
UID:Hi2NmwEoYK8k1xTLFW25r-9v@stanza.co
SUMMARY:Chihuahuas @ Bees
DESCRIPTION:Chihuahuas @ Bees\n\nFollow on MiLB First Pitch: https://stza.co/+wmBt-y\n\nShop: https://stza.co/+wmBt-20\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144522Z
LAST-MODIFIED:20180213T144522Z
TRANSP:OPAQUE
END:VEVENT
* Chihuahuas @ Bees
<2018-07-06 Fri 19:35-22:35>
:PROPERTIES:
:ID:       vgh9MyuURQJIGa5KHR-mlwbz@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Chihuahuas @ Bees Chihuahuas @ Bees

Follow on MiLB First Pitch  https //stza.co/+wmBu-2m

Shop  https //stza.co/+wmBu-24

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Chihuahuas @ Bees
END:VALARM
DTSTART:20180707T003500Z
DTEND:20180707T033500Z
UID:vgh9MyuURQJIGa5KHR-mlwbz@stanza.co
SUMMARY:Chihuahuas @ Bees
DESCRIPTION:Chihuahuas @ Bees\n\nFollow on MiLB First Pitch: https://stza.co/+wmBu-2m\n\nShop: https://stza.co/+wmBu-24\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144522Z
LAST-MODIFIED:20180213T144522Z
TRANSP:OPAQUE
END:VEVENT
* Chihuahuas @ Bees
<2018-07-07 Sat 19:35-22:35>
:PROPERTIES:
:ID:       NeeVE8SJqWMXZ4pi1esWPjDH@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Chihuahuas @ Bees Chihuahuas @ Bees

Follow on MiLB First Pitch  https //stza.co/+wmBv-2v

Shop  https //stza.co/+wmBv-36

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Chihuahuas @ Bees
END:VALARM
DTSTART:20180708T003500Z
DTEND:20180708T033500Z
UID:NeeVE8SJqWMXZ4pi1esWPjDH@stanza.co
SUMMARY:Chihuahuas @ Bees
DESCRIPTION:Chihuahuas @ Bees\n\nFollow on MiLB First Pitch: https://stza.co/+wmBv-2v\n\nShop: https://stza.co/+wmBv-36\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144522Z
LAST-MODIFIED:20180213T144522Z
TRANSP:OPAQUE
END:VEVENT
* Chihuahuas @ Bees
<2018-07-08 Sun 14:05-17:05>
:PROPERTIES:
:ID:       J9Wg1_K_TBpGQTtDRxZeCYyr@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Chihuahuas @ Bees Chihuahuas @ Bees

Follow on MiLB First Pitch  https //stza.co/+wmBw-1T

Shop  https //stza.co/+wmBw-2D

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Chihuahuas @ Bees
END:VALARM
DTSTART:20180708T190500Z
DTEND:20180708T220500Z
UID:J9Wg1_K_TBpGQTtDRxZeCYyr@stanza.co
SUMMARY:Chihuahuas @ Bees
DESCRIPTION:Chihuahuas @ Bees\n\nFollow on MiLB First Pitch: https://stza.co/+wmBw-1T\n\nShop: https://stza.co/+wmBw-2D\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144522Z
LAST-MODIFIED:20180213T144522Z
TRANSP:OPAQUE
END:VEVENT
* Chihuahuas vs. Aces
<2018-07-12 Thu 20:05-23:05>
:PROPERTIES:
:ID:       4nyI2XezB9U55JfV0ee9qbwJ@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Chihuahuas vs. Aces Chihuahuas vs. Aces

Follow on MiLB First Pitch  https //stza.co/+wmAy-i

Shop  https //stza.co/+wmAy-39

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Chihuahuas vs. Aces
END:VALARM
DTSTART:20180713T010500Z
DTEND:20180713T040500Z
UID:4nyI2XezB9U55JfV0ee9qbwJ@stanza.co
SUMMARY:Chihuahuas vs. Aces
DESCRIPTION:Chihuahuas vs. Aces\n\nFollow on MiLB First Pitch: https://stza.co/+wmAy-i\n\nShop: https://stza.co/+wmAy-39\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144522Z
LAST-MODIFIED:20180213T144522Z
TRANSP:OPAQUE
END:VEVENT
* Chihuahuas vs. Aces
<2018-07-13 Fri 20:05-23:05>
:PROPERTIES:
:ID:       YvIZk3wFw8lJP-yNDzzQwpzO@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Chihuahuas vs. Aces Chihuahuas vs. Aces

Follow on MiLB First Pitch  https //stza.co/+wmAB-_

Shop  https //stza.co/+wmAB-1c

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Chihuahuas vs. Aces
END:VALARM
DTSTART:20180714T010500Z
DTEND:20180714T040500Z
UID:YvIZk3wFw8lJP-yNDzzQwpzO@stanza.co
SUMMARY:Chihuahuas vs. Aces
DESCRIPTION:Chihuahuas vs. Aces\n\nFollow on MiLB First Pitch: https://stza.co/+wmAB-_\n\nShop: https://stza.co/+wmAB-1c\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144522Z
LAST-MODIFIED:20180213T144522Z
TRANSP:OPAQUE
END:VEVENT
* Chihuahuas vs. Aces
<2018-07-14 Sat 20:05-23:05>
:PROPERTIES:
:ID:       G7t4xumpXLXeEt2NRCTfvDJ8@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Chihuahuas vs. Aces Chihuahuas vs. Aces

Follow on MiLB First Pitch  https //stza.co/+wmAD-2Z

Shop  https //stza.co/+wmAD-11

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Chihuahuas vs. Aces
END:VALARM
DTSTART:20180715T010500Z
DTEND:20180715T040500Z
UID:G7t4xumpXLXeEt2NRCTfvDJ8@stanza.co
SUMMARY:Chihuahuas vs. Aces
DESCRIPTION:Chihuahuas vs. Aces\n\nFollow on MiLB First Pitch: https://stza.co/+wmAD-2Z\n\nShop: https://stza.co/+wmAD-11\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144522Z
LAST-MODIFIED:20180213T144522Z
TRANSP:OPAQUE
END:VEVENT
* Chihuahuas vs. Aces
<2018-07-15 Sun 19:05-22:05>
:PROPERTIES:
:ID:       bLTDNS0oNVrpRwd_e0-gVs-P@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Chihuahuas vs. Aces Chihuahuas vs. Aces

Follow on MiLB First Pitch  https //stza.co/+wmAG-2r

Shop  https //stza.co/+wmAG-3N

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Chihuahuas vs. Aces
END:VALARM
DTSTART:20180716T000500Z
DTEND:20180716T030500Z
UID:bLTDNS0oNVrpRwd_e0-gVs-P@stanza.co
SUMMARY:Chihuahuas vs. Aces
DESCRIPTION:Chihuahuas vs. Aces\n\nFollow on MiLB First Pitch: https://stza.co/+wmAG-2r\n\nShop: https://stza.co/+wmAG-3N\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144522Z
LAST-MODIFIED:20180213T144522Z
TRANSP:OPAQUE
END:VEVENT
* Chihuahuas @ Isotopes
<2018-07-16 Mon 19:35-22:35>
:PROPERTIES:
:ID:       BhsQ8k0En5GT4Shb9xJBv5B9@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Chihuahuas @ Isotopes Chihuahuas @ Isotopes

Follow on MiLB First Pitch  https //stza.co/+whCY-2e

Shop  https //stza.co/+whCY-$

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Chihuahuas @ Isotopes
END:VALARM
DTSTART:20180717T003500Z
DTEND:20180717T033500Z
UID:BhsQ8k0En5GT4Shb9xJBv5B9@stanza.co
SUMMARY:Chihuahuas @ Isotopes
DESCRIPTION:Chihuahuas @ Isotopes\n\nFollow on MiLB First Pitch: https://stza.co/+whCY-2e\n\nShop: https://stza.co/+whCY-$\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144522Z
LAST-MODIFIED:20180213T144522Z
TRANSP:OPAQUE
END:VEVENT
* Chihuahuas @ Isotopes
<2018-07-17 Tue 19:35-22:35>
:PROPERTIES:
:ID:       hR8Zsr8D1JFt46sSVotumbKa@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Chihuahuas @ Isotopes Chihuahuas @ Isotopes

Follow on MiLB First Pitch  https //stza.co/+whCZ-2V

Shop  https //stza.co/+whCZ-3e

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Chihuahuas @ Isotopes
END:VALARM
DTSTART:20180718T003500Z
DTEND:20180718T033500Z
UID:hR8Zsr8D1JFt46sSVotumbKa@stanza.co
SUMMARY:Chihuahuas @ Isotopes
DESCRIPTION:Chihuahuas @ Isotopes\n\nFollow on MiLB First Pitch: https://stza.co/+whCZ-2V\n\nShop: https://stza.co/+whCZ-3e\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144522Z
LAST-MODIFIED:20180213T144522Z
TRANSP:OPAQUE
END:VEVENT
* Chihuahuas @ Isotopes
<2018-07-18 Wed 19:35-22:35>
:PROPERTIES:
:ID:       gRZvxKOsd8JotCqaqOW0r62B@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Chihuahuas @ Isotopes Chihuahuas @ Isotopes

Follow on MiLB First Pitch  https //stza.co/+whC_-3E

Shop  https //stza.co/+whC_-2A

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Chihuahuas @ Isotopes
END:VALARM
DTSTART:20180719T003500Z
DTEND:20180719T033500Z
UID:gRZvxKOsd8JotCqaqOW0r62B@stanza.co
SUMMARY:Chihuahuas @ Isotopes
DESCRIPTION:Chihuahuas @ Isotopes\n\nFollow on MiLB First Pitch: https://stza.co/+whC_-3E\n\nShop: https://stza.co/+whC_-2A\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144522Z
LAST-MODIFIED:20180213T144522Z
TRANSP:OPAQUE
END:VEVENT
* Chihuahuas @ Isotopes
<2018-07-19 Thu 13:05-16:05>
:PROPERTIES:
:ID:       zjXVX9uKVLBw1yjWRllswd2M@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Chihuahuas @ Isotopes Chihuahuas @ Isotopes

Follow on MiLB First Pitch  https //stza.co/+whD0-2H

Shop  https //stza.co/+whD0-2q

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Chihuahuas @ Isotopes
END:VALARM
DTSTART:20180719T180500Z
DTEND:20180719T210500Z
UID:zjXVX9uKVLBw1yjWRllswd2M@stanza.co
SUMMARY:Chihuahuas @ Isotopes
DESCRIPTION:Chihuahuas @ Isotopes\n\nFollow on MiLB First Pitch: https://stza.co/+whD0-2H\n\nShop: https://stza.co/+whD0-2q\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144522Z
LAST-MODIFIED:20180213T144522Z
TRANSP:OPAQUE
END:VEVENT
* Chihuahuas vs. River Cats
<2018-07-20 Fri 20:05-23:05>
:PROPERTIES:
:ID:       66teouhP6J4FOfxzQzvumnYV@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Chihuahuas vs. River Cats Chihuahuas vs. River Cats

Follow on MiLB First Pitch  https //stza.co/+wmAI-1M

Shop  https //stza.co/+wmAI-

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Chihuahuas vs. River Cats
END:VALARM
DTSTART:20180721T010500Z
DTEND:20180721T040500Z
UID:66teouhP6J4FOfxzQzvumnYV@stanza.co
SUMMARY:Chihuahuas vs. River Cats
DESCRIPTION:Chihuahuas vs. River Cats\n\nFollow on MiLB First Pitch: https://stza.co/+wmAI-1M\n\nShop: https://stza.co/+wmAI-\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144522Z
LAST-MODIFIED:20180213T144522Z
TRANSP:OPAQUE
END:VEVENT
* Chihuahuas vs. River Cats
<2018-07-21 Sat 20:05-23:05>
:PROPERTIES:
:ID:       xoqSKLNmiCus-WncGbSHYQiQ@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Chihuahuas vs. River Cats Chihuahuas vs. River Cats

Follow on MiLB First Pitch  https //stza.co/+wmAL-2B

Shop  https //stza.co/+wmAL-2r

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Chihuahuas vs. River Cats
END:VALARM
DTSTART:20180722T010500Z
DTEND:20180722T040500Z
UID:xoqSKLNmiCus-WncGbSHYQiQ@stanza.co
SUMMARY:Chihuahuas vs. River Cats
DESCRIPTION:Chihuahuas vs. River Cats\n\nFollow on MiLB First Pitch: https://stza.co/+wmAL-2B\n\nShop: https://stza.co/+wmAL-2r\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144522Z
LAST-MODIFIED:20180213T144522Z
TRANSP:OPAQUE
END:VEVENT
* Chihuahuas vs. River Cats
<2018-07-22 Sun 19:05-22:05>
:PROPERTIES:
:ID:       gwQDyihBJxkvzIrpfaqLHejc@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Chihuahuas vs. River Cats Chihuahuas vs. River Cats

Follow on MiLB First Pitch  https //stza.co/+xzzB-22

Shop  https //stza.co/+xzzB-3G

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Chihuahuas vs. River Cats
END:VALARM
DTSTART:20180723T000500Z
DTEND:20180723T030500Z
UID:gwQDyihBJxkvzIrpfaqLHejc@stanza.co
SUMMARY:Chihuahuas vs. River Cats
DESCRIPTION:Chihuahuas vs. River Cats\n\nFollow on MiLB First Pitch: https://stza.co/+xzzB-22\n\nShop: https://stza.co/+xzzB-3G\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144522Z
LAST-MODIFIED:20180213T144522Z
TRANSP:OPAQUE
END:VEVENT
* Chihuahuas @ Sky Sox
<2018-07-24 Tue 19:40-22:40>
:PROPERTIES:
:ID:       CuZO8494wrL39yl47MMuEibb@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Chihuahuas @ Sky Sox Chihuahuas @ Sky Sox

Follow on MiLB First Pitch  https //stza.co/+wmz3-19

Shop  https //stza.co/+wmz3-1T

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Chihuahuas @ Sky Sox
END:VALARM
DTSTART:20180725T004000Z
DTEND:20180725T034000Z
UID:CuZO8494wrL39yl47MMuEibb@stanza.co
SUMMARY:Chihuahuas @ Sky Sox
DESCRIPTION:Chihuahuas @ Sky Sox\n\nFollow on MiLB First Pitch: https://stza.co/+wmz3-19\n\nShop: https://stza.co/+wmz3-1T\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144522Z
LAST-MODIFIED:20180213T144522Z
TRANSP:OPAQUE
END:VEVENT
* Chihuahuas @ Sky Sox
<2018-07-25 Wed 13:30-16:30>
:PROPERTIES:
:ID:       z9EoBBsg3rvirbRZJMJl8SJd@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Chihuahuas @ Sky Sox Chihuahuas @ Sky Sox

Follow on MiLB First Pitch  https //stza.co/+wmz4-e

Shop  https //stza.co/+wmz4-o

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Chihuahuas @ Sky Sox
END:VALARM
DTSTART:20180725T183000Z
DTEND:20180725T213000Z
UID:z9EoBBsg3rvirbRZJMJl8SJd@stanza.co
SUMMARY:Chihuahuas @ Sky Sox
DESCRIPTION:Chihuahuas @ Sky Sox\n\nFollow on MiLB First Pitch: https://stza.co/+wmz4-e\n\nShop: https://stza.co/+wmz4-o\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144522Z
LAST-MODIFIED:20180213T144522Z
TRANSP:OPAQUE
END:VEVENT
* Chihuahuas @ Sky Sox
<2018-07-26 Thu 19:40-22:40>
:PROPERTIES:
:ID:       tyF_YmzJLvKOoFxke-oMXSNp@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Chihuahuas @ Sky Sox Chihuahuas @ Sky Sox

Follow on MiLB First Pitch  https //stza.co/+wmz5-2H

Shop  https //stza.co/+wmz5-1e

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Chihuahuas @ Sky Sox
END:VALARM
DTSTART:20180727T004000Z
DTEND:20180727T034000Z
UID:tyF_YmzJLvKOoFxke-oMXSNp@stanza.co
SUMMARY:Chihuahuas @ Sky Sox
DESCRIPTION:Chihuahuas @ Sky Sox\n\nFollow on MiLB First Pitch: https://stza.co/+wmz5-2H\n\nShop: https://stza.co/+wmz5-1e\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144522Z
LAST-MODIFIED:20180213T144522Z
TRANSP:OPAQUE
END:VEVENT
* Chihuahuas @ Dodgers
<2018-07-27 Fri 19:05-22:05>
:PROPERTIES:
:ID:       i_WxfpV0Ma9D11HTA-P5EIh7@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Chihuahuas @ Dodgers Chihuahuas @ Dodgers

Follow on MiLB First Pitch  https //stza.co/+v$Md-h

Shop  https //stza.co/+v$Md-2$

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Chihuahuas @ Dodgers
END:VALARM
DTSTART:20180728T000500Z
DTEND:20180728T030500Z
UID:i_WxfpV0Ma9D11HTA-P5EIh7@stanza.co
SUMMARY:Chihuahuas @ Dodgers
DESCRIPTION:Chihuahuas @ Dodgers\n\nFollow on MiLB First Pitch: https://stza.co/+v$Md-h\n\nShop: https://stza.co/+v$Md-2$\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144522Z
LAST-MODIFIED:20180213T144522Z
TRANSP:OPAQUE
END:VEVENT
* Chihuahuas @ Dodgers
<2018-07-28 Sat 19:05-22:05>
:PROPERTIES:
:ID:       sfOGdtNhAxrBzY9nAryytx0N@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Chihuahuas @ Dodgers Chihuahuas @ Dodgers

Follow on MiLB First Pitch  https //stza.co/+v$Me-1z

Shop  https //stza.co/+v$Me-1T

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Chihuahuas @ Dodgers
END:VALARM
DTSTART:20180729T000500Z
DTEND:20180729T030500Z
UID:sfOGdtNhAxrBzY9nAryytx0N@stanza.co
SUMMARY:Chihuahuas @ Dodgers
DESCRIPTION:Chihuahuas @ Dodgers\n\nFollow on MiLB First Pitch: https://stza.co/+v$Me-1z\n\nShop: https://stza.co/+v$Me-1T\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144522Z
LAST-MODIFIED:20180213T144522Z
TRANSP:OPAQUE
END:VEVENT
* Chihuahuas @ Dodgers
<2018-07-29 Sun 18:05-21:05>
:PROPERTIES:
:ID:       jykYiNPyCfqd3IivGFNkt2QH@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Chihuahuas @ Dodgers Chihuahuas @ Dodgers

Follow on MiLB First Pitch  https //stza.co/+v$Mf-3C

Shop  https //stza.co/+v$Mf-36

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Chihuahuas @ Dodgers
END:VALARM
DTSTART:20180729T230500Z
DTEND:20180730T020500Z
UID:jykYiNPyCfqd3IivGFNkt2QH@stanza.co
SUMMARY:Chihuahuas @ Dodgers
DESCRIPTION:Chihuahuas @ Dodgers\n\nFollow on MiLB First Pitch: https://stza.co/+v$Mf-3C\n\nShop: https://stza.co/+v$Mf-36\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144522Z
LAST-MODIFIED:20180213T144522Z
TRANSP:OPAQUE
END:VEVENT
* Chihuahuas @ Dodgers
<2018-07-30 Mon 19:05-22:05>
:PROPERTIES:
:ID:       UhNhVrpEuhhTVggbzAB37xC5@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Chihuahuas @ Dodgers Chihuahuas @ Dodgers

Follow on MiLB First Pitch  https //stza.co/+v$Mg-37

Shop  https //stza.co/+v$Mg-1d

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Chihuahuas @ Dodgers
END:VALARM
DTSTART:20180731T000500Z
DTEND:20180731T030500Z
UID:UhNhVrpEuhhTVggbzAB37xC5@stanza.co
SUMMARY:Chihuahuas @ Dodgers
DESCRIPTION:Chihuahuas @ Dodgers\n\nFollow on MiLB First Pitch: https://stza.co/+v$Mg-37\n\nShop: https://stza.co/+v$Mg-1d\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144522Z
LAST-MODIFIED:20180213T144522Z
TRANSP:OPAQUE
END:VEVENT
* Chihuahuas vs. Baby Cakes
<2018-08-01 Wed 20:05-23:05>
:PROPERTIES:
:ID:       tXjgDDpWPbtzZkfpNinzC-zq@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Chihuahuas vs. Baby Cakes Chihuahuas vs. Baby Cakes

Follow on MiLB First Pitch  https //stza.co/+wmAQ-1o

Shop  https //stza.co/+wmAQ-1U

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Chihuahuas vs. Baby Cakes
END:VALARM
DTSTART:20180802T010500Z
DTEND:20180802T040500Z
UID:tXjgDDpWPbtzZkfpNinzC-zq@stanza.co
SUMMARY:Chihuahuas vs. Baby Cakes
DESCRIPTION:Chihuahuas vs. Baby Cakes\n\nFollow on MiLB First Pitch: https://stza.co/+wmAQ-1o\n\nShop: https://stza.co/+wmAQ-1U\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144522Z
LAST-MODIFIED:20180213T144522Z
TRANSP:OPAQUE
END:VEVENT
* Chihuahuas vs. Baby Cakes
<2018-08-02 Thu 20:05-23:05>
:PROPERTIES:
:ID:       pWTPKDPIjlBKfi5iK3mIPaOe@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Chihuahuas vs. Baby Cakes Chihuahuas vs. Baby Cakes

Follow on MiLB First Pitch  https //stza.co/+wmAS-2A

Shop  https //stza.co/+wmAS-1

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Chihuahuas vs. Baby Cakes
END:VALARM
DTSTART:20180803T010500Z
DTEND:20180803T040500Z
UID:pWTPKDPIjlBKfi5iK3mIPaOe@stanza.co
SUMMARY:Chihuahuas vs. Baby Cakes
DESCRIPTION:Chihuahuas vs. Baby Cakes\n\nFollow on MiLB First Pitch: https://stza.co/+wmAS-2A\n\nShop: https://stza.co/+wmAS-1\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144522Z
LAST-MODIFIED:20180213T144522Z
TRANSP:OPAQUE
END:VEVENT
* Chihuahuas vs. Baby Cakes
<2018-08-03 Fri 20:05-23:05>
:PROPERTIES:
:ID:       bgKMnYCXfeXA_Zxp2c_3E3Uo@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Chihuahuas vs. Baby Cakes Chihuahuas vs. Baby Cakes

Follow on MiLB First Pitch  https //stza.co/+wmAV-3X

Shop  https //stza.co/+wmAV-1Y

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Chihuahuas vs. Baby Cakes
END:VALARM
DTSTART:20180804T010500Z
DTEND:20180804T040500Z
UID:bgKMnYCXfeXA_Zxp2c_3E3Uo@stanza.co
SUMMARY:Chihuahuas vs. Baby Cakes
DESCRIPTION:Chihuahuas vs. Baby Cakes\n\nFollow on MiLB First Pitch: https://stza.co/+wmAV-3X\n\nShop: https://stza.co/+wmAV-1Y\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144522Z
LAST-MODIFIED:20180213T144522Z
TRANSP:OPAQUE
END:VEVENT
* Chihuahuas vs. Express
<2018-08-04 Sat 20:05-23:05>
:PROPERTIES:
:ID:       AHFaKDW9vRuVB664dyJpn1xG@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Chihuahuas vs. Express Chihuahuas vs. Express

Follow on MiLB First Pitch  https //stza.co/+wmAZ-2K

Shop  https //stza.co/+wmAZ-2g

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Chihuahuas vs. Express
END:VALARM
DTSTART:20180805T010500Z
DTEND:20180805T040500Z
UID:AHFaKDW9vRuVB664dyJpn1xG@stanza.co
SUMMARY:Chihuahuas vs. Express
DESCRIPTION:Chihuahuas vs. Express\n\nFollow on MiLB First Pitch: https://stza.co/+wmAZ-2K\n\nShop: https://stza.co/+wmAZ-2g\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144522Z
LAST-MODIFIED:20180213T144522Z
TRANSP:OPAQUE
END:VEVENT
* Chihuahuas vs. Express
<2018-08-05 Sun 19:05-22:05>
:PROPERTIES:
:ID:       NouTXKpD51kd9VHDxo7kkOTI@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Chihuahuas vs. Express Chihuahuas vs. Express

Follow on MiLB First Pitch  https //stza.co/+wmA$-1T

Shop  https //stza.co/+wmA$-3o

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Chihuahuas vs. Express
END:VALARM
DTSTART:20180806T000500Z
DTEND:20180806T030500Z
UID:NouTXKpD51kd9VHDxo7kkOTI@stanza.co
SUMMARY:Chihuahuas vs. Express
DESCRIPTION:Chihuahuas vs. Express\n\nFollow on MiLB First Pitch: https://stza.co/+wmA$-1T\n\nShop: https://stza.co/+wmA$-3o\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144522Z
LAST-MODIFIED:20180213T144522Z
TRANSP:OPAQUE
END:VEVENT
* Chihuahuas vs. Express
<2018-08-06 Mon 20:05-23:05>
:PROPERTIES:
:ID:       w7p2PYpBbpxVnC3u3H2Zvv0Q@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Chihuahuas vs. Express Chihuahuas vs. Express

Follow on MiLB First Pitch  https //stza.co/+wmB1-2w

Shop  https //stza.co/+wmB1-1v

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Chihuahuas vs. Express
END:VALARM
DTSTART:20180807T010500Z
DTEND:20180807T040500Z
UID:w7p2PYpBbpxVnC3u3H2Zvv0Q@stanza.co
SUMMARY:Chihuahuas vs. Express
DESCRIPTION:Chihuahuas vs. Express\n\nFollow on MiLB First Pitch: https://stza.co/+wmB1-2w\n\nShop: https://stza.co/+wmB1-1v\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144522Z
LAST-MODIFIED:20180213T144522Z
TRANSP:OPAQUE
END:VEVENT
* Chihuahuas vs. Express
<2018-08-07 Tue 20:05-23:05>
:PROPERTIES:
:ID:       wP56ThVJbrsh1odAAXeR2n5C@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Chihuahuas vs. Express Chihuahuas vs. Express

Follow on MiLB First Pitch  https //stza.co/+wmB3-2f

Shop  https //stza.co/+wmB3-2U

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Chihuahuas vs. Express
END:VALARM
DTSTART:20180808T010500Z
DTEND:20180808T040500Z
UID:wP56ThVJbrsh1odAAXeR2n5C@stanza.co
SUMMARY:Chihuahuas vs. Express
DESCRIPTION:Chihuahuas vs. Express\n\nFollow on MiLB First Pitch: https://stza.co/+wmB3-2f\n\nShop: https://stza.co/+wmB3-2U\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144522Z
LAST-MODIFIED:20180213T144522Z
TRANSP:OPAQUE
END:VEVENT
* Chihuahuas @ River Cats
<2018-08-09 Thu 21:05>--<2018-08-10 Fri 00:05>
:PROPERTIES:
:ID:       OgngIDxo_uLeMgfaQrJ8EBMT@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Chihuahuas @ River Cats Chihuahuas @ River Cats

Follow on MiLB First Pitch  https //stza.co/+wjxo-2C

Shop  https //stza.co/+wjxo-2x

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Chihuahuas @ River Cats
END:VALARM
DTSTART:20180810T020500Z
DTEND:20180810T050500Z
UID:OgngIDxo_uLeMgfaQrJ8EBMT@stanza.co
SUMMARY:Chihuahuas @ River Cats
DESCRIPTION:Chihuahuas @ River Cats\n\nFollow on MiLB First Pitch: https://stza.co/+wjxo-2C\n\nShop: https://stza.co/+wjxo-2x\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144522Z
LAST-MODIFIED:20180213T144522Z
TRANSP:OPAQUE
END:VEVENT
* Chihuahuas @ River Cats
<2018-08-10 Fri 21:05>--<2018-08-11 Sat 00:05>
:PROPERTIES:
:ID:       qpZauQcXGRn9NLfxY1DClEGZ@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Chihuahuas @ River Cats Chihuahuas @ River Cats

Follow on MiLB First Pitch  https //stza.co/+wjxp-35

Shop  https //stza.co/+wjxp-_

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Chihuahuas @ River Cats
END:VALARM
DTSTART:20180811T020500Z
DTEND:20180811T050500Z
UID:qpZauQcXGRn9NLfxY1DClEGZ@stanza.co
SUMMARY:Chihuahuas @ River Cats
DESCRIPTION:Chihuahuas @ River Cats\n\nFollow on MiLB First Pitch: https://stza.co/+wjxp-35\n\nShop: https://stza.co/+wjxp-_\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144522Z
LAST-MODIFIED:20180213T144522Z
TRANSP:OPAQUE
END:VEVENT
* Chihuahuas @ River Cats
<2018-08-11 Sat 21:05>--<2018-08-12 Sun 00:05>
:PROPERTIES:
:ID:       0zLep-Z_gAbLFzjmCbM9Dgwd@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Chihuahuas @ River Cats Chihuahuas @ River Cats

Follow on MiLB First Pitch  https //stza.co/+wjxq-3l

Shop  https //stza.co/+wjxq-3W

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Chihuahuas @ River Cats
END:VALARM
DTSTART:20180812T020500Z
DTEND:20180812T050500Z
UID:0zLep-Z_gAbLFzjmCbM9Dgwd@stanza.co
SUMMARY:Chihuahuas @ River Cats
DESCRIPTION:Chihuahuas @ River Cats\n\nFollow on MiLB First Pitch: https://stza.co/+wjxq-3l\n\nShop: https://stza.co/+wjxq-3W\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144522Z
LAST-MODIFIED:20180213T144522Z
TRANSP:OPAQUE
END:VEVENT
* Chihuahuas @ River Cats
<2018-08-12 Sun 15:05-18:05>
:PROPERTIES:
:ID:       of6ejHtS521G0JLLAH6Hd-Jy@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Chihuahuas @ River Cats Chihuahuas @ River Cats

Follow on MiLB First Pitch  https //stza.co/+wjxr-2r

Shop  https //stza.co/+wjxr-2G

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Chihuahuas @ River Cats
END:VALARM
DTSTART:20180812T200500Z
DTEND:20180812T230500Z
UID:of6ejHtS521G0JLLAH6Hd-Jy@stanza.co
SUMMARY:Chihuahuas @ River Cats
DESCRIPTION:Chihuahuas @ River Cats\n\nFollow on MiLB First Pitch: https://stza.co/+wjxr-2r\n\nShop: https://stza.co/+wjxr-2G\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144522Z
LAST-MODIFIED:20180213T144522Z
TRANSP:OPAQUE
END:VEVENT
* Chihuahuas @ Bees
<2018-08-13 Mon 20:05-23:05>
:PROPERTIES:
:ID:       MAWLyOS6SstWvddxn2y3b5rE@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Chihuahuas @ Bees Chihuahuas @ Bees

Follow on MiLB First Pitch  https //stza.co/+wmBx-2u

Shop  https //stza.co/+wmBx-3N

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Chihuahuas @ Bees
END:VALARM
DTSTART:20180814T010500Z
DTEND:20180814T040500Z
UID:MAWLyOS6SstWvddxn2y3b5rE@stanza.co
SUMMARY:Chihuahuas @ Bees
DESCRIPTION:Chihuahuas @ Bees\n\nFollow on MiLB First Pitch: https://stza.co/+wmBx-2u\n\nShop: https://stza.co/+wmBx-3N\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144522Z
LAST-MODIFIED:20180213T144522Z
TRANSP:OPAQUE
END:VEVENT
* Chihuahuas @ Bees
<2018-08-14 Tue 20:05-23:05>
:PROPERTIES:
:ID:       qnWzWMUz2-eIOgjO6mJa1MpT@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Chihuahuas @ Bees Chihuahuas @ Bees

Follow on MiLB First Pitch  https //stza.co/+wmBy-2M

Shop  https //stza.co/+wmBy-2N

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Chihuahuas @ Bees
END:VALARM
DTSTART:20180815T010500Z
DTEND:20180815T040500Z
UID:qnWzWMUz2-eIOgjO6mJa1MpT@stanza.co
SUMMARY:Chihuahuas @ Bees
DESCRIPTION:Chihuahuas @ Bees\n\nFollow on MiLB First Pitch: https://stza.co/+wmBy-2M\n\nShop: https://stza.co/+wmBy-2N\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144522Z
LAST-MODIFIED:20180213T144522Z
TRANSP:OPAQUE
END:VEVENT
* Chihuahuas @ Bees
<2018-08-15 Wed 20:05-23:05>
:PROPERTIES:
:ID:       vaCGHyO1v9GgUZnAMXTzQdxc@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Chihuahuas @ Bees Chihuahuas @ Bees

Follow on MiLB First Pitch  https //stza.co/+wmBz-3r

Shop  https //stza.co/+wmBz-3p

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Chihuahuas @ Bees
END:VALARM
DTSTART:20180816T010500Z
DTEND:20180816T040500Z
UID:vaCGHyO1v9GgUZnAMXTzQdxc@stanza.co
SUMMARY:Chihuahuas @ Bees
DESCRIPTION:Chihuahuas @ Bees\n\nFollow on MiLB First Pitch: https://stza.co/+wmBz-3r\n\nShop: https://stza.co/+wmBz-3p\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144522Z
LAST-MODIFIED:20180213T144522Z
TRANSP:OPAQUE
END:VEVENT
* Chihuahuas vs. 51s
<2018-08-16 Thu 20:05-23:05>
:PROPERTIES:
:ID:       q8r1_m1hRY9PWh2k97ucapUY@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Chihuahuas vs. 51s Chihuahuas vs. 51s

Follow on MiLB First Pitch  https //stza.co/+wmB5-23

Shop  https //stza.co/+wmB5-L

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Chihuahuas vs. 51s
END:VALARM
DTSTART:20180817T010500Z
DTEND:20180817T040500Z
UID:q8r1_m1hRY9PWh2k97ucapUY@stanza.co
SUMMARY:Chihuahuas vs. 51s
DESCRIPTION:Chihuahuas vs. 51s\n\nFollow on MiLB First Pitch: https://stza.co/+wmB5-23\n\nShop: https://stza.co/+wmB5-L\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144522Z
LAST-MODIFIED:20180213T144522Z
TRANSP:OPAQUE
END:VEVENT
* Chihuahuas vs. 51s
<2018-08-17 Fri 20:05-23:05>
:PROPERTIES:
:ID:       P2MMOMbihmjVF3E3voyXj2S7@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Chihuahuas vs. 51s Chihuahuas vs. 51s

Follow on MiLB First Pitch  https //stza.co/+wmB7-2x

Shop  https //stza.co/+wmB7-1N

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Chihuahuas vs. 51s
END:VALARM
DTSTART:20180818T010500Z
DTEND:20180818T040500Z
UID:P2MMOMbihmjVF3E3voyXj2S7@stanza.co
SUMMARY:Chihuahuas vs. 51s
DESCRIPTION:Chihuahuas vs. 51s\n\nFollow on MiLB First Pitch: https://stza.co/+wmB7-2x\n\nShop: https://stza.co/+wmB7-1N\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144522Z
LAST-MODIFIED:20180213T144522Z
TRANSP:OPAQUE
END:VEVENT
* Chihuahuas vs. 51s
<2018-08-18 Sat 20:05-23:05>
:PROPERTIES:
:ID:       n2aKxh5qzbVnluaGYUrVezdr@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Chihuahuas vs. 51s Chihuahuas vs. 51s

Follow on MiLB First Pitch  https //stza.co/+wmB9-2z

Shop  https //stza.co/+wmB9-2i

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Chihuahuas vs. 51s
END:VALARM
DTSTART:20180819T010500Z
DTEND:20180819T040500Z
UID:n2aKxh5qzbVnluaGYUrVezdr@stanza.co
SUMMARY:Chihuahuas vs. 51s
DESCRIPTION:Chihuahuas vs. 51s\n\nFollow on MiLB First Pitch: https://stza.co/+wmB9-2z\n\nShop: https://stza.co/+wmB9-2i\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144522Z
LAST-MODIFIED:20180213T144522Z
TRANSP:OPAQUE
END:VEVENT
* Chihuahuas vs. 51s
<2018-08-19 Sun 19:05-22:05>
:PROPERTIES:
:ID:       fFRaKykeHOtlRSmkHkLNDTyG@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Chihuahuas vs. 51s Chihuahuas vs. 51s

Follow on MiLB First Pitch  https //stza.co/+wmBb-1U

Shop  https //stza.co/+wmBb-3S

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Chihuahuas vs. 51s
END:VALARM
DTSTART:20180820T000500Z
DTEND:20180820T030500Z
UID:fFRaKykeHOtlRSmkHkLNDTyG@stanza.co
SUMMARY:Chihuahuas vs. 51s
DESCRIPTION:Chihuahuas vs. 51s\n\nFollow on MiLB First Pitch: https://stza.co/+wmBb-1U\n\nShop: https://stza.co/+wmBb-3S\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144522Z
LAST-MODIFIED:20180213T144522Z
TRANSP:OPAQUE
END:VEVENT
* Chihuahuas vs. Isotopes
<2018-08-21 Tue 19:35-22:35>
:PROPERTIES:
:ID:       H9LpdR0g46E3tKxyBrc-CcoO@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Chihuahuas vs. Isotopes Chihuahuas vs. Isotopes

Follow on MiLB First Pitch  https //stza.co/+wmBd-3f

Shop  https //stza.co/+wmBd-3X

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Chihuahuas vs. Isotopes
END:VALARM
DTSTART:20180822T003500Z
DTEND:20180822T033500Z
UID:H9LpdR0g46E3tKxyBrc-CcoO@stanza.co
SUMMARY:Chihuahuas vs. Isotopes
DESCRIPTION:Chihuahuas vs. Isotopes\n\nFollow on MiLB First Pitch: https://stza.co/+wmBd-3f\n\nShop: https://stza.co/+wmBd-3X\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144522Z
LAST-MODIFIED:20180213T144522Z
TRANSP:OPAQUE
END:VEVENT
* Chihuahuas vs. Isotopes
<2018-08-22 Wed 19:35-22:35>
:PROPERTIES:
:ID:       f_BiHZIa5uj_LS8W0fZvNus3@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Chihuahuas vs. Isotopes Chihuahuas vs. Isotopes

Follow on MiLB First Pitch  https //stza.co/+wmBg-d

Shop  https //stza.co/+wmBg-2a

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Chihuahuas vs. Isotopes
END:VALARM
DTSTART:20180823T003500Z
DTEND:20180823T033500Z
UID:f_BiHZIa5uj_LS8W0fZvNus3@stanza.co
SUMMARY:Chihuahuas vs. Isotopes
DESCRIPTION:Chihuahuas vs. Isotopes\n\nFollow on MiLB First Pitch: https://stza.co/+wmBg-d\n\nShop: https://stza.co/+wmBg-2a\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144522Z
LAST-MODIFIED:20180213T144522Z
TRANSP:OPAQUE
END:VEVENT
* Chihuahuas vs. Isotopes
<2018-08-23 Thu 19:35-22:35>
:PROPERTIES:
:ID:       B6taejTG1sR5YMtI3Fan-WAI@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Chihuahuas vs. Isotopes Chihuahuas vs. Isotopes

Follow on MiLB First Pitch  https //stza.co/+wmBh-1C

Shop  https //stza.co/+wmBh-33

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Chihuahuas vs. Isotopes
END:VALARM
DTSTART:20180824T003500Z
DTEND:20180824T033500Z
UID:B6taejTG1sR5YMtI3Fan-WAI@stanza.co
SUMMARY:Chihuahuas vs. Isotopes
DESCRIPTION:Chihuahuas vs. Isotopes\n\nFollow on MiLB First Pitch: https://stza.co/+wmBh-1C\n\nShop: https://stza.co/+wmBh-33\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144522Z
LAST-MODIFIED:20180213T144522Z
TRANSP:OPAQUE
END:VEVENT
* Chihuahuas @ Rainiers
<2018-08-24 Fri 21:05>--<2018-08-25 Sat 00:05>
:PROPERTIES:
:ID:       XCVW8EobgNm8kPp0xlbEDJDl@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Chihuahuas @ Rainiers Chihuahuas @ Rainiers

Follow on MiLB First Pitch  https //stza.co/+wjxw-U

Shop  https //stza.co/+wjxw-a

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Chihuahuas @ Rainiers
END:VALARM
DTSTART:20180825T020500Z
DTEND:20180825T050500Z
UID:XCVW8EobgNm8kPp0xlbEDJDl@stanza.co
SUMMARY:Chihuahuas @ Rainiers
DESCRIPTION:Chihuahuas @ Rainiers\n\nFollow on MiLB First Pitch: https://stza.co/+wjxw-U\n\nShop: https://stza.co/+wjxw-a\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144522Z
LAST-MODIFIED:20180213T144522Z
TRANSP:OPAQUE
END:VEVENT
* Chihuahuas @ Rainiers
<2018-08-25 Sat 21:05>--<2018-08-26 Sun 00:05>
:PROPERTIES:
:ID:       2k6mKJUGy-K-LOGlnkK8OMkT@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Chihuahuas @ Rainiers Chihuahuas @ Rainiers

Follow on MiLB First Pitch  https //stza.co/+wjxx-1i

Shop  https //stza.co/+wjxx-i

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Chihuahuas @ Rainiers
END:VALARM
DTSTART:20180826T020500Z
DTEND:20180826T050500Z
UID:2k6mKJUGy-K-LOGlnkK8OMkT@stanza.co
SUMMARY:Chihuahuas @ Rainiers
DESCRIPTION:Chihuahuas @ Rainiers\n\nFollow on MiLB First Pitch: https://stza.co/+wjxx-1i\n\nShop: https://stza.co/+wjxx-i\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144522Z
LAST-MODIFIED:20180213T144522Z
TRANSP:OPAQUE
END:VEVENT
* Chihuahuas @ Rainiers
<2018-08-26 Sun 15:35-18:35>
:PROPERTIES:
:ID:       4cB3prHhA7Sn2iUMhAlfPsny@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Chihuahuas @ Rainiers Chihuahuas @ Rainiers

Follow on MiLB First Pitch  https //stza.co/+wjxy-1A

Shop  https //stza.co/+wjxy-2t

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Chihuahuas @ Rainiers
END:VALARM
DTSTART:20180826T203500Z
DTEND:20180826T233500Z
UID:4cB3prHhA7Sn2iUMhAlfPsny@stanza.co
SUMMARY:Chihuahuas @ Rainiers
DESCRIPTION:Chihuahuas @ Rainiers\n\nFollow on MiLB First Pitch: https://stza.co/+wjxy-1A\n\nShop: https://stza.co/+wjxy-2t\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144522Z
LAST-MODIFIED:20180213T144522Z
TRANSP:OPAQUE
END:VEVENT
* Chihuahuas @ Rainiers
<2018-08-27 Mon 21:05>--<2018-08-28 Tue 00:05>
:PROPERTIES:
:ID:       ZGHdHtFrWjaG_Lg1hA76xEh0@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Chihuahuas @ Rainiers Chihuahuas @ Rainiers

Follow on MiLB First Pitch  https //stza.co/+wjxz-D

Shop  https //stza.co/+wjxz-1R

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Chihuahuas @ Rainiers
END:VALARM
DTSTART:20180828T020500Z
DTEND:20180828T050500Z
UID:ZGHdHtFrWjaG_Lg1hA76xEh0@stanza.co
SUMMARY:Chihuahuas @ Rainiers
DESCRIPTION:Chihuahuas @ Rainiers\n\nFollow on MiLB First Pitch: https://stza.co/+wjxz-D\n\nShop: https://stza.co/+wjxz-1R\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144522Z
LAST-MODIFIED:20180213T144522Z
TRANSP:OPAQUE
END:VEVENT
* Chihuahuas @ Grizzlies
<2018-08-28 Tue 21:05>--<2018-08-29 Wed 00:05>
:PROPERTIES:
:ID:       RqF3qVRPeeCMW6SpPNcKYn_I@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Chihuahuas @ Grizzlies Chihuahuas @ Grizzlies

Follow on MiLB First Pitch  https //stza.co/+wjx8-2S

Shop  https //stza.co/+wjx8-1_

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Chihuahuas @ Grizzlies
END:VALARM
DTSTART:20180829T020500Z
DTEND:20180829T050500Z
UID:RqF3qVRPeeCMW6SpPNcKYn_I@stanza.co
SUMMARY:Chihuahuas @ Grizzlies
DESCRIPTION:Chihuahuas @ Grizzlies\n\nFollow on MiLB First Pitch: https://stza.co/+wjx8-2S\n\nShop: https://stza.co/+wjx8-1_\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144522Z
LAST-MODIFIED:20180213T144522Z
TRANSP:OPAQUE
END:VEVENT
* Chihuahuas @ Grizzlies
<2018-08-29 Wed 21:05>--<2018-08-30 Thu 00:05>
:PROPERTIES:
:ID:       oT-Ep_Le3AjGClm8Q6xzDI0D@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Chihuahuas @ Grizzlies Chihuahuas @ Grizzlies

Follow on MiLB First Pitch  https //stza.co/+wjxa-v

Shop  https //stza.co/+wjxa-1l

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Chihuahuas @ Grizzlies
END:VALARM
DTSTART:20180830T020500Z
DTEND:20180830T050500Z
UID:oT-Ep_Le3AjGClm8Q6xzDI0D@stanza.co
SUMMARY:Chihuahuas @ Grizzlies
DESCRIPTION:Chihuahuas @ Grizzlies\n\nFollow on MiLB First Pitch: https://stza.co/+wjxa-v\n\nShop: https://stza.co/+wjxa-1l\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144522Z
LAST-MODIFIED:20180213T144522Z
TRANSP:OPAQUE
END:VEVENT
* Chihuahuas @ Grizzlies
<2018-08-30 Thu 21:05>--<2018-08-31 Fri 00:05>
:PROPERTIES:
:ID:       Hbp-I9Xvv09dMcd-i9XVzsPC@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Chihuahuas @ Grizzlies Chihuahuas @ Grizzlies

Follow on MiLB First Pitch  https //stza.co/+wjxb-3G

Shop  https //stza.co/+wjxb-1e

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Chihuahuas @ Grizzlies
END:VALARM
DTSTART:20180831T020500Z
DTEND:20180831T050500Z
UID:Hbp-I9Xvv09dMcd-i9XVzsPC@stanza.co
SUMMARY:Chihuahuas @ Grizzlies
DESCRIPTION:Chihuahuas @ Grizzlies\n\nFollow on MiLB First Pitch: https://stza.co/+wjxb-3G\n\nShop: https://stza.co/+wjxb-1e\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144522Z
LAST-MODIFIED:20180213T144522Z
TRANSP:OPAQUE
END:VEVENT
* Chihuahuas vs. Rainiers
<2018-08-31 Fri 20:05-23:05>
:PROPERTIES:
:ID:       pJr3b2b9xA1DSqdrBM_yvQhq@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Chihuahuas vs. Rainiers Chihuahuas vs. Rainiers

Follow on MiLB First Pitch  https //stza.co/+wmBk-1E

Shop  https //stza.co/+wmBk-1M

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Chihuahuas vs. Rainiers
END:VALARM
DTSTART:20180901T010500Z
DTEND:20180901T040500Z
UID:pJr3b2b9xA1DSqdrBM_yvQhq@stanza.co
SUMMARY:Chihuahuas vs. Rainiers
DESCRIPTION:Chihuahuas vs. Rainiers\n\nFollow on MiLB First Pitch: https://stza.co/+wmBk-1E\n\nShop: https://stza.co/+wmBk-1M\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144522Z
LAST-MODIFIED:20180213T144522Z
TRANSP:OPAQUE
END:VEVENT
* Chihuahuas vs. Rainiers
<2018-09-01 Sat 20:05-23:05>
:PROPERTIES:
:ID:       gDEQAarnbR3SRrlZ-p9yyQUg@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Chihuahuas vs. Rainiers Chihuahuas vs. Rainiers

Follow on MiLB First Pitch  https //stza.co/+wmBn-1d

Shop  https //stza.co/+wmBn-r

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Chihuahuas vs. Rainiers
END:VALARM
DTSTART:20180902T010500Z
DTEND:20180902T040500Z
UID:gDEQAarnbR3SRrlZ-p9yyQUg@stanza.co
SUMMARY:Chihuahuas vs. Rainiers
DESCRIPTION:Chihuahuas vs. Rainiers\n\nFollow on MiLB First Pitch: https://stza.co/+wmBn-1d\n\nShop: https://stza.co/+wmBn-r\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144522Z
LAST-MODIFIED:20180213T144522Z
TRANSP:OPAQUE
END:VEVENT
* Chihuahuas vs. Rainiers
<2018-09-02 Sun 19:05-22:05>
:PROPERTIES:
:ID:       E1PkNTTISvBvPxTnIEbvyyQb@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Chihuahuas vs. Rainiers Chihuahuas vs. Rainiers

Follow on MiLB First Pitch  https //stza.co/+wmBp-2G

Shop  https //stza.co/+wmBp-3L

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Chihuahuas vs. Rainiers
END:VALARM
DTSTART:20180903T000500Z
DTEND:20180903T030500Z
UID:E1PkNTTISvBvPxTnIEbvyyQb@stanza.co
SUMMARY:Chihuahuas vs. Rainiers
DESCRIPTION:Chihuahuas vs. Rainiers\n\nFollow on MiLB First Pitch: https://stza.co/+wmBp-2G\n\nShop: https://stza.co/+wmBp-3L\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144522Z
LAST-MODIFIED:20180213T144522Z
TRANSP:OPAQUE
END:VEVENT
* Chihuahuas vs. Rainiers
<2018-09-03 Mon 14:05-17:05>
:PROPERTIES:
:ID:       CfltZ8EDt6euLX_tfda0Koo8@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Chihuahuas vs. Rainiers Chihuahuas vs. Rainiers

Follow on MiLB First Pitch  https //stza.co/+wmBr-22

Shop  https //stza.co/+wmBr-1M

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Chihuahuas vs. Rainiers
END:VALARM
DTSTART:20180903T190500Z
DTEND:20180903T220500Z
UID:CfltZ8EDt6euLX_tfda0Koo8@stanza.co
SUMMARY:Chihuahuas vs. Rainiers
DESCRIPTION:Chihuahuas vs. Rainiers\n\nFollow on MiLB First Pitch: https://stza.co/+wmBr-22\n\nShop: https://stza.co/+wmBr-1M\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144522Z
LAST-MODIFIED:20180213T144522Z
TRANSP:OPAQUE
END:VEVENT
