#+TITLE:       Main Google calendar entries
#+AUTHOR:      Eric S Fraga
#+EMAIL:       e.fraga@ucl.ac.uk
#+DESCRIPTION: converted using the ical2org awk script
#+CATEGORY:    google
#+STARTUP:     hidestars
#+STARTUP:     overview

* COMMENT original iCal preamble

* Crawdads @ Grasshoppers
<2018-04-05 Thu 18:00-21:00>
:PROPERTIES:
:ID:       oQvx_4dz0pbkCfIyGWDCC6rs@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Crawdads @ Grasshoppers Crawdads @ Grasshoppers

Follow on MiLB First Pitch  https //stza.co/+wizk-21

Shop  https //stza.co/+wizk-1Y

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Crawdads @ Grasshoppers
END:VALARM
DTSTART:20180405T230000Z
DTEND:20180406T020000Z
UID:oQvx_4dz0pbkCfIyGWDCC6rs@stanza.co
SUMMARY:Crawdads @ Grasshoppers
DESCRIPTION:Crawdads @ Grasshoppers\n\nFollow on MiLB First Pitch: https://stza.co/+wizk-21\n\nShop: https://stza.co/+wizk-1Y\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144532Z
LAST-MODIFIED:20180213T144532Z
TRANSP:OPAQUE
END:VEVENT
* Crawdads @ Grasshoppers
<2018-04-06 Fri 18:00-21:00>
:PROPERTIES:
:ID:       x-H-ypDPc2qNJIKzreWrBuG_@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Crawdads @ Grasshoppers Crawdads @ Grasshoppers

Follow on MiLB First Pitch  https //stza.co/+wizl-3D

Shop  https //stza.co/+wizl-21

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Crawdads @ Grasshoppers
END:VALARM
DTSTART:20180406T230000Z
DTEND:20180407T020000Z
UID:x-H-ypDPc2qNJIKzreWrBuG_@stanza.co
SUMMARY:Crawdads @ Grasshoppers
DESCRIPTION:Crawdads @ Grasshoppers\n\nFollow on MiLB First Pitch: https://stza.co/+wizl-3D\n\nShop: https://stza.co/+wizl-21\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144532Z
LAST-MODIFIED:20180213T144532Z
TRANSP:OPAQUE
END:VEVENT
* Crawdads @ Grasshoppers
<2018-04-07 Sat 18:00-21:00>
:PROPERTIES:
:ID:       5vu-8_9n726nFVlRRcSW0ooy@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Crawdads @ Grasshoppers Crawdads @ Grasshoppers

Follow on MiLB First Pitch  https //stza.co/+wizm-2w

Shop  https //stza.co/+wizm-1R

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Crawdads @ Grasshoppers
END:VALARM
DTSTART:20180407T230000Z
DTEND:20180408T020000Z
UID:5vu-8_9n726nFVlRRcSW0ooy@stanza.co
SUMMARY:Crawdads @ Grasshoppers
DESCRIPTION:Crawdads @ Grasshoppers\n\nFollow on MiLB First Pitch: https://stza.co/+wizm-2w\n\nShop: https://stza.co/+wizm-1R\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144532Z
LAST-MODIFIED:20180213T144532Z
TRANSP:OPAQUE
END:VEVENT
* Crawdads @ Grasshoppers
<2018-04-08 Sun 13:00-16:00>
:PROPERTIES:
:ID:       KN5c3MNwR9jwS0-lfbfvWUM7@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Crawdads @ Grasshoppers Crawdads @ Grasshoppers

Follow on MiLB First Pitch  https //stza.co/+wizn-2y

Shop  https //stza.co/+wizn-T

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Crawdads @ Grasshoppers
END:VALARM
DTSTART:20180408T180000Z
DTEND:20180408T210000Z
UID:KN5c3MNwR9jwS0-lfbfvWUM7@stanza.co
SUMMARY:Crawdads @ Grasshoppers
DESCRIPTION:Crawdads @ Grasshoppers\n\nFollow on MiLB First Pitch: https://stza.co/+wizn-2y\n\nShop: https://stza.co/+wizn-T\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144532Z
LAST-MODIFIED:20180213T144532Z
TRANSP:OPAQUE
END:VEVENT
* Crawdads @ Shorebirds
<2018-04-09 Mon 18:05-21:05>
:PROPERTIES:
:ID:       Batu0F6i4CtM51E0BgBumdtI@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Crawdads @ Shorebirds Crawdads @ Shorebirds

Follow on MiLB First Pitch  https //stza.co/+wHSd-11

Shop  https //stza.co/+wHSd-2O

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Crawdads @ Shorebirds
END:VALARM
DTSTART:20180409T230500Z
DTEND:20180410T020500Z
UID:Batu0F6i4CtM51E0BgBumdtI@stanza.co
SUMMARY:Crawdads @ Shorebirds
DESCRIPTION:Crawdads @ Shorebirds\n\nFollow on MiLB First Pitch: https://stza.co/+wHSd-11\n\nShop: https://stza.co/+wHSd-2O\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144532Z
LAST-MODIFIED:20180213T144532Z
TRANSP:OPAQUE
END:VEVENT
* Crawdads @ Shorebirds
<2018-04-10 Tue 18:05-21:05>
:PROPERTIES:
:ID:       d7znis1epp2ccNLpCj3V28Pd@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Crawdads @ Shorebirds Crawdads @ Shorebirds

Follow on MiLB First Pitch  https //stza.co/+wHSe-3y

Shop  https //stza.co/+wHSe-3z

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Crawdads @ Shorebirds
END:VALARM
DTSTART:20180410T230500Z
DTEND:20180411T020500Z
UID:d7znis1epp2ccNLpCj3V28Pd@stanza.co
SUMMARY:Crawdads @ Shorebirds
DESCRIPTION:Crawdads @ Shorebirds\n\nFollow on MiLB First Pitch: https://stza.co/+wHSe-3y\n\nShop: https://stza.co/+wHSe-3z\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144532Z
LAST-MODIFIED:20180213T144532Z
TRANSP:OPAQUE
END:VEVENT
* Crawdads @ Shorebirds
<2018-04-11 Wed 09:35-12:35>
:PROPERTIES:
:ID:       6OiH7McSTIZT2tnF7ZliYVHY@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Crawdads @ Shorebirds Crawdads @ Shorebirds

Follow on MiLB First Pitch  https //stza.co/+wHSf-3F

Shop  https //stza.co/+wHSf-O

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Crawdads @ Shorebirds
END:VALARM
DTSTART:20180411T143500Z
DTEND:20180411T173500Z
UID:6OiH7McSTIZT2tnF7ZliYVHY@stanza.co
SUMMARY:Crawdads @ Shorebirds
DESCRIPTION:Crawdads @ Shorebirds\n\nFollow on MiLB First Pitch: https://stza.co/+wHSf-3F\n\nShop: https://stza.co/+wHSf-O\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144532Z
LAST-MODIFIED:20180213T144532Z
TRANSP:OPAQUE
END:VEVENT
* Crawdads vs. Power
<2018-04-12 Thu 18:00-21:00>
:PROPERTIES:
:ID:       IFeTgQLkoMhY75HdIt_gYaiB@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Crawdads vs. Power Crawdads vs. Power

Follow on MiLB First Pitch  https //stza.co/+w0OB-o

Shop  https //stza.co/+w0OB-U

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Crawdads vs. Power
END:VALARM
DTSTART:20180412T230000Z
DTEND:20180413T020000Z
UID:IFeTgQLkoMhY75HdIt_gYaiB@stanza.co
SUMMARY:Crawdads vs. Power
DESCRIPTION:Crawdads vs. Power\n\nFollow on MiLB First Pitch: https://stza.co/+w0OB-o\n\nShop: https://stza.co/+w0OB-U\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144532Z
LAST-MODIFIED:20180213T144532Z
TRANSP:OPAQUE
END:VEVENT
* Crawdads vs. Power
<2018-04-13 Fri 18:00-21:00>
:PROPERTIES:
:ID:       2LOoczvfxN_QgOzsIpf9CzQD@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Crawdads vs. Power Crawdads vs. Power

Follow on MiLB First Pitch  https //stza.co/+w0OD-_

Shop  https //stza.co/+w0OD-2H

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Crawdads vs. Power
END:VALARM
DTSTART:20180413T230000Z
DTEND:20180414T020000Z
UID:2LOoczvfxN_QgOzsIpf9CzQD@stanza.co
SUMMARY:Crawdads vs. Power
DESCRIPTION:Crawdads vs. Power\n\nFollow on MiLB First Pitch: https://stza.co/+w0OD-_\n\nShop: https://stza.co/+w0OD-2H\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144532Z
LAST-MODIFIED:20180213T144532Z
TRANSP:OPAQUE
END:VEVENT
* Crawdads vs. Power
<2018-04-14 Sat 17:00-20:00>
:PROPERTIES:
:ID:       W6SrxMiJI4xEUjiXtasZckd7@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Crawdads vs. Power Crawdads vs. Power

Follow on MiLB First Pitch  https //stza.co/+w0OF-1g

Shop  https //stza.co/+w0OF-1r

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Crawdads vs. Power
END:VALARM
DTSTART:20180414T220000Z
DTEND:20180415T010000Z
UID:W6SrxMiJI4xEUjiXtasZckd7@stanza.co
SUMMARY:Crawdads vs. Power
DESCRIPTION:Crawdads vs. Power\n\nFollow on MiLB First Pitch: https://stza.co/+w0OF-1g\n\nShop: https://stza.co/+w0OF-1r\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144532Z
LAST-MODIFIED:20180213T144532Z
TRANSP:OPAQUE
END:VEVENT
* Crawdads vs. Power
<2018-04-15 Sun 14:00-17:00>
:PROPERTIES:
:ID:       sWC6s4mp8L3MB62mEfsB3m_Z@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Crawdads vs. Power Crawdads vs. Power

Follow on MiLB First Pitch  https //stza.co/+w0OH-c

Shop  https //stza.co/+w0OH-G

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Crawdads vs. Power
END:VALARM
DTSTART:20180415T190000Z
DTEND:20180415T220000Z
UID:sWC6s4mp8L3MB62mEfsB3m_Z@stanza.co
SUMMARY:Crawdads vs. Power
DESCRIPTION:Crawdads vs. Power\n\nFollow on MiLB First Pitch: https://stza.co/+w0OH-c\n\nShop: https://stza.co/+w0OH-G\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144532Z
LAST-MODIFIED:20180213T144532Z
TRANSP:OPAQUE
END:VEVENT
* Crawdads vs. Legends
<2018-04-16 Mon 17:00-20:00>
:PROPERTIES:
:ID:       yHypc-WVnvoYORflvDxJQiQj@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Crawdads vs. Legends Crawdads vs. Legends

Follow on MiLB First Pitch  https //stza.co/+y7AD-1m

Shop  https //stza.co/+y7AD-8

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Crawdads vs. Legends
END:VALARM
DTSTART:20180416T220000Z
DTEND:20180417T010000Z
UID:yHypc-WVnvoYORflvDxJQiQj@stanza.co
SUMMARY:Crawdads vs. Legends
DESCRIPTION:Crawdads vs. Legends\n\nFollow on MiLB First Pitch: https://stza.co/+y7AD-1m\n\nShop: https://stza.co/+y7AD-8\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144532Z
LAST-MODIFIED:20180213T144532Z
TRANSP:OPAQUE
END:VEVENT
* Crawdads vs. Legends
<2018-04-17 Tue 17:00-20:00>
:PROPERTIES:
:ID:       MXUok8KeHHgsZCdRtqyqXgor@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Crawdads vs. Legends Crawdads vs. Legends

Follow on MiLB First Pitch  https //stza.co/+w0OK-1R

Shop  https //stza.co/+w0OK-35

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Crawdads vs. Legends
END:VALARM
DTSTART:20180417T220000Z
DTEND:20180418T010000Z
UID:MXUok8KeHHgsZCdRtqyqXgor@stanza.co
SUMMARY:Crawdads vs. Legends
DESCRIPTION:Crawdads vs. Legends\n\nFollow on MiLB First Pitch: https://stza.co/+w0OK-1R\n\nShop: https://stza.co/+w0OK-35\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144532Z
LAST-MODIFIED:20180213T144532Z
TRANSP:OPAQUE
END:VEVENT
* Crawdads vs. Legends
<2018-04-18 Wed 09:30-12:30>
:PROPERTIES:
:ID:       l9-PKXqH7yBaoWvgtW8P6jCa@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Crawdads vs. Legends Crawdads vs. Legends

Follow on MiLB First Pitch  https //stza.co/+w0ON-2T

Shop  https //stza.co/+w0ON-1q

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Crawdads vs. Legends
END:VALARM
DTSTART:20180418T143000Z
DTEND:20180418T173000Z
UID:l9-PKXqH7yBaoWvgtW8P6jCa@stanza.co
SUMMARY:Crawdads vs. Legends
DESCRIPTION:Crawdads vs. Legends\n\nFollow on MiLB First Pitch: https://stza.co/+w0ON-2T\n\nShop: https://stza.co/+w0ON-1q\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144532Z
LAST-MODIFIED:20180213T144532Z
TRANSP:OPAQUE
END:VEVENT
* Crawdads @ Fireflies
<2018-04-19 Thu 18:05-21:05>
:PROPERTIES:
:ID:       6R9eTG_kqOGpyEhYr7nkfcFq@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Crawdads @ Fireflies Crawdads @ Fireflies

Follow on MiLB First Pitch  https //stza.co/+xBVE-3x

Shop  https //stza.co/+xBVE-3V

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Crawdads @ Fireflies
END:VALARM
DTSTART:20180419T230500Z
DTEND:20180420T020500Z
UID:6R9eTG_kqOGpyEhYr7nkfcFq@stanza.co
SUMMARY:Crawdads @ Fireflies
DESCRIPTION:Crawdads @ Fireflies\n\nFollow on MiLB First Pitch: https://stza.co/+xBVE-3x\n\nShop: https://stza.co/+xBVE-3V\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144532Z
LAST-MODIFIED:20180213T144532Z
TRANSP:OPAQUE
END:VEVENT
* Crawdads @ Fireflies
<2018-04-20 Fri 18:05-21:05>
:PROPERTIES:
:ID:       W6pfh0KKyXDTNBOxTsV09vfL@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Crawdads @ Fireflies Crawdads @ Fireflies

Follow on MiLB First Pitch  https //stza.co/+xBVI-15

Shop  https //stza.co/+xBVI-10

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Crawdads @ Fireflies
END:VALARM
DTSTART:20180420T230500Z
DTEND:20180421T020500Z
UID:W6pfh0KKyXDTNBOxTsV09vfL@stanza.co
SUMMARY:Crawdads @ Fireflies
DESCRIPTION:Crawdads @ Fireflies\n\nFollow on MiLB First Pitch: https://stza.co/+xBVI-15\n\nShop: https://stza.co/+xBVI-10\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144532Z
LAST-MODIFIED:20180213T144532Z
TRANSP:OPAQUE
END:VEVENT
* Crawdads @ Fireflies
<2018-04-21 Sat 17:05-20:05>
:PROPERTIES:
:ID:       eSX7izxKyECA80Tjup5keal8@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Crawdads @ Fireflies Crawdads @ Fireflies

Follow on MiLB First Pitch  https //stza.co/+xBVM-4

Shop  https //stza.co/+xBVM-3h

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Crawdads @ Fireflies
END:VALARM
DTSTART:20180421T220500Z
DTEND:20180422T010500Z
UID:eSX7izxKyECA80Tjup5keal8@stanza.co
SUMMARY:Crawdads @ Fireflies
DESCRIPTION:Crawdads @ Fireflies\n\nFollow on MiLB First Pitch: https://stza.co/+xBVM-4\n\nShop: https://stza.co/+xBVM-3h\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144532Z
LAST-MODIFIED:20180213T144532Z
TRANSP:OPAQUE
END:VEVENT
* Crawdads @ Fireflies
<2018-04-22 Sun 13:05-16:05>
:PROPERTIES:
:ID:       EVi8r6guRDI2cAKv-OrYChDB@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Crawdads @ Fireflies Crawdads @ Fireflies

Follow on MiLB First Pitch  https //stza.co/+xBVP-3E

Shop  https //stza.co/+xBVP-1U

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Crawdads @ Fireflies
END:VALARM
DTSTART:20180422T180500Z
DTEND:20180422T210500Z
UID:EVi8r6guRDI2cAKv-OrYChDB@stanza.co
SUMMARY:Crawdads @ Fireflies
DESCRIPTION:Crawdads @ Fireflies\n\nFollow on MiLB First Pitch: https://stza.co/+xBVP-3E\n\nShop: https://stza.co/+xBVP-1U\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144532Z
LAST-MODIFIED:20180213T144532Z
TRANSP:OPAQUE
END:VEVENT
* Crawdads vs. Grasshoppers
<2018-04-23 Mon 17:00-20:00>
:PROPERTIES:
:ID:       ZWISDCgB5j_QEX1cx4oSiHmP@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Crawdads vs. Grasshoppers Crawdads vs. Grasshoppers

Follow on MiLB First Pitch  https //stza.co/+w0OP-1G

Shop  https //stza.co/+w0OP-34

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Crawdads vs. Grasshoppers
END:VALARM
DTSTART:20180423T220000Z
DTEND:20180424T010000Z
UID:ZWISDCgB5j_QEX1cx4oSiHmP@stanza.co
SUMMARY:Crawdads vs. Grasshoppers
DESCRIPTION:Crawdads vs. Grasshoppers\n\nFollow on MiLB First Pitch: https://stza.co/+w0OP-1G\n\nShop: https://stza.co/+w0OP-34\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144532Z
LAST-MODIFIED:20180213T144532Z
TRANSP:OPAQUE
END:VEVENT
* Crawdads vs. Grasshoppers
<2018-04-24 Tue 17:00-20:00>
:PROPERTIES:
:ID:       XhGI2wU8t5VWzzFmZOCa6aJO@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Crawdads vs. Grasshoppers Crawdads vs. Grasshoppers

Follow on MiLB First Pitch  https //stza.co/+w0OR-2b

Shop  https //stza.co/+w0OR-A

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Crawdads vs. Grasshoppers
END:VALARM
DTSTART:20180424T220000Z
DTEND:20180425T010000Z
UID:XhGI2wU8t5VWzzFmZOCa6aJO@stanza.co
SUMMARY:Crawdads vs. Grasshoppers
DESCRIPTION:Crawdads vs. Grasshoppers\n\nFollow on MiLB First Pitch: https://stza.co/+w0OR-2b\n\nShop: https://stza.co/+w0OR-A\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144532Z
LAST-MODIFIED:20180213T144532Z
TRANSP:OPAQUE
END:VEVENT
* Crawdads vs. Grasshoppers
<2018-04-25 Wed 09:30-12:30>
:PROPERTIES:
:ID:       M2GUlMhiWsp53ysH8AkowFcZ@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Crawdads vs. Grasshoppers Crawdads vs. Grasshoppers

Follow on MiLB First Pitch  https //stza.co/+w0OS-11

Shop  https //stza.co/+w0OS-3v

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Crawdads vs. Grasshoppers
END:VALARM
DTSTART:20180425T143000Z
DTEND:20180425T173000Z
UID:M2GUlMhiWsp53ysH8AkowFcZ@stanza.co
SUMMARY:Crawdads vs. Grasshoppers
DESCRIPTION:Crawdads vs. Grasshoppers\n\nFollow on MiLB First Pitch: https://stza.co/+w0OS-11\n\nShop: https://stza.co/+w0OS-3v\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144532Z
LAST-MODIFIED:20180213T144532Z
TRANSP:OPAQUE
END:VEVENT
* Crawdads vs. Grasshoppers
<2018-04-26 Thu 18:00-21:00>
:PROPERTIES:
:ID:       -J_lANjWKtxasUnKAe--k9re@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Crawdads vs. Grasshoppers Crawdads vs. Grasshoppers

Follow on MiLB First Pitch  https //stza.co/+w0OU-

Shop  https //stza.co/+w0OU-3u

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Crawdads vs. Grasshoppers
END:VALARM
DTSTART:20180426T230000Z
DTEND:20180427T020000Z
UID:-J_lANjWKtxasUnKAe--k9re@stanza.co
SUMMARY:Crawdads vs. Grasshoppers
DESCRIPTION:Crawdads vs. Grasshoppers\n\nFollow on MiLB First Pitch: https://stza.co/+w0OU-\n\nShop: https://stza.co/+w0OU-3u\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144532Z
LAST-MODIFIED:20180213T144532Z
TRANSP:OPAQUE
END:VEVENT
* Crawdads vs. Shorebirds
<2018-04-27 Fri 18:00-21:00>
:PROPERTIES:
:ID:       c46bO0kPmD3BAiD40inaV-t4@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Crawdads vs. Shorebirds Crawdads vs. Shorebirds

Follow on MiLB First Pitch  https //stza.co/+w0OX-1S

Shop  https //stza.co/+w0OX-31

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Crawdads vs. Shorebirds
END:VALARM
DTSTART:20180427T230000Z
DTEND:20180428T020000Z
UID:c46bO0kPmD3BAiD40inaV-t4@stanza.co
SUMMARY:Crawdads vs. Shorebirds
DESCRIPTION:Crawdads vs. Shorebirds\n\nFollow on MiLB First Pitch: https://stza.co/+w0OX-1S\n\nShop: https://stza.co/+w0OX-31\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144532Z
LAST-MODIFIED:20180213T144532Z
TRANSP:OPAQUE
END:VEVENT
* Crawdads vs. Shorebirds
<2018-04-28 Sat 16:00-19:00>
:PROPERTIES:
:ID:       9xMJUjcZNuX6-xxTaJh3BlrW@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Crawdads vs. Shorebirds Crawdads vs. Shorebirds

Follow on MiLB First Pitch  https //stza.co/+xB4B-3j

Shop  https //stza.co/+xB4B-3q

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Crawdads vs. Shorebirds
END:VALARM
DTSTART:20180428T210000Z
DTEND:20180429T000000Z
UID:9xMJUjcZNuX6-xxTaJh3BlrW@stanza.co
SUMMARY:Crawdads vs. Shorebirds
DESCRIPTION:Crawdads vs. Shorebirds\n\nFollow on MiLB First Pitch: https://stza.co/+xB4B-3j\n\nShop: https://stza.co/+xB4B-3q\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144532Z
LAST-MODIFIED:20180213T144532Z
TRANSP:OPAQUE
END:VEVENT
* Crawdads vs. Shorebirds
<2018-04-29 Sun 14:00-17:00>
:PROPERTIES:
:ID:       ERvZVz0ydZcinMn6d8PjWcRc@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Crawdads vs. Shorebirds Crawdads vs. Shorebirds

Follow on MiLB First Pitch  https //stza.co/+w0O_-3y

Shop  https //stza.co/+w0O_-I

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Crawdads vs. Shorebirds
END:VALARM
DTSTART:20180429T190000Z
DTEND:20180429T220000Z
UID:ERvZVz0ydZcinMn6d8PjWcRc@stanza.co
SUMMARY:Crawdads vs. Shorebirds
DESCRIPTION:Crawdads vs. Shorebirds\n\nFollow on MiLB First Pitch: https://stza.co/+w0O_-3y\n\nShop: https://stza.co/+w0O_-I\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144532Z
LAST-MODIFIED:20180213T144532Z
TRANSP:OPAQUE
END:VEVENT
* Crawdads @ Intimidators
<2018-05-01 Tue 17:35-20:35>
:PROPERTIES:
:ID:       UuxXwTZf-GlZPwRktrAqvJEf@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Crawdads @ Intimidators Crawdads @ Intimidators

Follow on MiLB First Pitch  https //stza.co/+wICQ-2r

Shop  https //stza.co/+wICQ-2M

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Crawdads @ Intimidators
END:VALARM
DTSTART:20180501T223500Z
DTEND:20180502T013500Z
UID:UuxXwTZf-GlZPwRktrAqvJEf@stanza.co
SUMMARY:Crawdads @ Intimidators
DESCRIPTION:Crawdads @ Intimidators\n\nFollow on MiLB First Pitch: https://stza.co/+wICQ-2r\n\nShop: https://stza.co/+wICQ-2M\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144532Z
LAST-MODIFIED:20180213T144532Z
TRANSP:OPAQUE
END:VEVENT
* Crawdads @ Intimidators
<2018-05-02 Wed 17:35-20:35>
:PROPERTIES:
:ID:       zqA8RPCQErIGxXHYLvVXYwZB@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Crawdads @ Intimidators Crawdads @ Intimidators

Follow on MiLB First Pitch  https //stza.co/+wICS-2Q

Shop  https //stza.co/+wICS-v

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Crawdads @ Intimidators
END:VALARM
DTSTART:20180502T223500Z
DTEND:20180503T013500Z
UID:zqA8RPCQErIGxXHYLvVXYwZB@stanza.co
SUMMARY:Crawdads @ Intimidators
DESCRIPTION:Crawdads @ Intimidators\n\nFollow on MiLB First Pitch: https://stza.co/+wICS-2Q\n\nShop: https://stza.co/+wICS-v\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144532Z
LAST-MODIFIED:20180213T144532Z
TRANSP:OPAQUE
END:VEVENT
* Crawdads @ Intimidators
<2018-05-03 Thu 17:35-20:35>
:PROPERTIES:
:ID:       nDkiuPzOaK0BtNxZOC7i7Hbj@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Crawdads @ Intimidators Crawdads @ Intimidators

Follow on MiLB First Pitch  https //stza.co/+wICT-1q

Shop  https //stza.co/+wICT-2n

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Crawdads @ Intimidators
END:VALARM
DTSTART:20180503T223500Z
DTEND:20180504T013500Z
UID:nDkiuPzOaK0BtNxZOC7i7Hbj@stanza.co
SUMMARY:Crawdads @ Intimidators
DESCRIPTION:Crawdads @ Intimidators\n\nFollow on MiLB First Pitch: https://stza.co/+wICT-1q\n\nShop: https://stza.co/+wICT-2n\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144532Z
LAST-MODIFIED:20180213T144532Z
TRANSP:OPAQUE
END:VEVENT
* Crawdads @ Power
<2018-05-04 Fri 18:05-21:05>
:PROPERTIES:
:ID:       DQbUHKzxAUXtBPXzkEV1PZ4L@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Crawdads @ Power Crawdads @ Power

Follow on MiLB First Pitch  https //stza.co/+xJ3_-1D

Shop  https //stza.co/+xJ3_-3q

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Crawdads @ Power
END:VALARM
DTSTART:20180504T230500Z
DTEND:20180505T020500Z
UID:DQbUHKzxAUXtBPXzkEV1PZ4L@stanza.co
SUMMARY:Crawdads @ Power
DESCRIPTION:Crawdads @ Power\n\nFollow on MiLB First Pitch: https://stza.co/+xJ3_-1D\n\nShop: https://stza.co/+xJ3_-3q\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144532Z
LAST-MODIFIED:20180213T144532Z
TRANSP:OPAQUE
END:VEVENT
* Crawdads @ Power
<2018-05-05 Sat 17:05-20:05>
:PROPERTIES:
:ID:       w0javnDf3uQG1V7npIDqvaBI@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Crawdads @ Power Crawdads @ Power

Follow on MiLB First Pitch  https //stza.co/+xJ3$-2k

Shop  https //stza.co/+xJ3$-3L

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Crawdads @ Power
END:VALARM
DTSTART:20180505T220500Z
DTEND:20180506T010500Z
UID:w0javnDf3uQG1V7npIDqvaBI@stanza.co
SUMMARY:Crawdads @ Power
DESCRIPTION:Crawdads @ Power\n\nFollow on MiLB First Pitch: https://stza.co/+xJ3$-2k\n\nShop: https://stza.co/+xJ3$-3L\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144532Z
LAST-MODIFIED:20180213T144532Z
TRANSP:OPAQUE
END:VEVENT
* Crawdads @ Power
<2018-05-06 Sun 13:05-16:05>
:PROPERTIES:
:ID:       kJMd5lgaG_86oXgGst7erH5y@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Crawdads @ Power Crawdads @ Power

Follow on MiLB First Pitch  https //stza.co/+xJ40-P

Shop  https //stza.co/+xJ40-2W

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Crawdads @ Power
END:VALARM
DTSTART:20180506T180500Z
DTEND:20180506T210500Z
UID:kJMd5lgaG_86oXgGst7erH5y@stanza.co
SUMMARY:Crawdads @ Power
DESCRIPTION:Crawdads @ Power\n\nFollow on MiLB First Pitch: https://stza.co/+xJ40-P\n\nShop: https://stza.co/+xJ40-2W\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144532Z
LAST-MODIFIED:20180213T144532Z
TRANSP:OPAQUE
END:VEVENT
* Crawdads @ Power
<2018-05-07 Mon 18:05-21:05>
:PROPERTIES:
:ID:       i2JOBJN8QzKFbLZ3XhH0MWay@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Crawdads @ Power Crawdads @ Power

Follow on MiLB First Pitch  https //stza.co/+xJ41-28

Shop  https //stza.co/+xJ41-t

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Crawdads @ Power
END:VALARM
DTSTART:20180507T230500Z
DTEND:20180508T020500Z
UID:i2JOBJN8QzKFbLZ3XhH0MWay@stanza.co
SUMMARY:Crawdads @ Power
DESCRIPTION:Crawdads @ Power\n\nFollow on MiLB First Pitch: https://stza.co/+xJ41-28\n\nShop: https://stza.co/+xJ41-t\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144532Z
LAST-MODIFIED:20180213T144532Z
TRANSP:OPAQUE
END:VEVENT
* Crawdads vs. Fireflies
<2018-05-09 Wed 17:00-20:00>
:PROPERTIES:
:ID:       ze10nLszfuLIjGp52YSLaz1w@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Crawdads vs. Fireflies Crawdads vs. Fireflies

Follow on MiLB First Pitch  https //stza.co/+w0P1-2C

Shop  https //stza.co/+w0P1-1H

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Crawdads vs. Fireflies
END:VALARM
DTSTART:20180509T220000Z
DTEND:20180510T010000Z
UID:ze10nLszfuLIjGp52YSLaz1w@stanza.co
SUMMARY:Crawdads vs. Fireflies
DESCRIPTION:Crawdads vs. Fireflies\n\nFollow on MiLB First Pitch: https://stza.co/+w0P1-2C\n\nShop: https://stza.co/+w0P1-1H\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144532Z
LAST-MODIFIED:20180213T144532Z
TRANSP:OPAQUE
END:VEVENT
* Crawdads vs. Fireflies
<2018-05-10 Thu 18:00-21:00>
:PROPERTIES:
:ID:       l22zzkfvoLrbaEgfWgV_eBjz@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Crawdads vs. Fireflies Crawdads vs. Fireflies

Follow on MiLB First Pitch  https //stza.co/+w0P3-3L

Shop  https //stza.co/+w0P3-2l

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Crawdads vs. Fireflies
END:VALARM
DTSTART:20180510T230000Z
DTEND:20180511T020000Z
UID:l22zzkfvoLrbaEgfWgV_eBjz@stanza.co
SUMMARY:Crawdads vs. Fireflies
DESCRIPTION:Crawdads vs. Fireflies\n\nFollow on MiLB First Pitch: https://stza.co/+w0P3-3L\n\nShop: https://stza.co/+w0P3-2l\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144532Z
LAST-MODIFIED:20180213T144532Z
TRANSP:OPAQUE
END:VEVENT
* Crawdads vs. Fireflies
<2018-05-11 Fri 18:00-21:00>
:PROPERTIES:
:ID:       2-icnPll05aIMflcKSnNWYWR@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Crawdads vs. Fireflies Crawdads vs. Fireflies

Follow on MiLB First Pitch  https //stza.co/+w0P5-6

Shop  https //stza.co/+w0P5-1y

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Crawdads vs. Fireflies
END:VALARM
DTSTART:20180511T230000Z
DTEND:20180512T020000Z
UID:2-icnPll05aIMflcKSnNWYWR@stanza.co
SUMMARY:Crawdads vs. Fireflies
DESCRIPTION:Crawdads vs. Fireflies\n\nFollow on MiLB First Pitch: https://stza.co/+w0P5-6\n\nShop: https://stza.co/+w0P5-1y\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144532Z
LAST-MODIFIED:20180213T144532Z
TRANSP:OPAQUE
END:VEVENT
* Crawdads vs. Braves
<2018-05-12 Sat 17:00-20:00>
:PROPERTIES:
:ID:       JwO5oMg-Ca_Id7Kg8Pbmn-N1@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Crawdads vs. Braves Crawdads vs. Braves

Follow on MiLB First Pitch  https //stza.co/+w0P7-T

Shop  https //stza.co/+w0P7-25

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Crawdads vs. Braves
END:VALARM
DTSTART:20180512T220000Z
DTEND:20180513T010000Z
UID:JwO5oMg-Ca_Id7Kg8Pbmn-N1@stanza.co
SUMMARY:Crawdads vs. Braves
DESCRIPTION:Crawdads vs. Braves\n\nFollow on MiLB First Pitch: https://stza.co/+w0P7-T\n\nShop: https://stza.co/+w0P7-25\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144532Z
LAST-MODIFIED:20180213T144532Z
TRANSP:OPAQUE
END:VEVENT
* Crawdads vs. Braves
<2018-05-13 Sun 14:00-17:00>
:PROPERTIES:
:ID:       tUxNU7ysa6WyPKfZKo2hl-Td@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Crawdads vs. Braves Crawdads vs. Braves

Follow on MiLB First Pitch  https //stza.co/+w0P8-D

Shop  https //stza.co/+w0P8-2S

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Crawdads vs. Braves
END:VALARM
DTSTART:20180513T190000Z
DTEND:20180513T220000Z
UID:tUxNU7ysa6WyPKfZKo2hl-Td@stanza.co
SUMMARY:Crawdads vs. Braves
DESCRIPTION:Crawdads vs. Braves\n\nFollow on MiLB First Pitch: https://stza.co/+w0P8-D\n\nShop: https://stza.co/+w0P8-2S\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144532Z
LAST-MODIFIED:20180213T144532Z
TRANSP:OPAQUE
END:VEVENT
* Crawdads vs. Braves
<2018-05-14 Mon 17:00-20:00>
:PROPERTIES:
:ID:       s26e-Bsy-wxShFezApchL_GF@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Crawdads vs. Braves Crawdads vs. Braves

Follow on MiLB First Pitch  https //stza.co/+w0Pa-2T

Shop  https //stza.co/+w0Pa-1n

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Crawdads vs. Braves
END:VALARM
DTSTART:20180514T220000Z
DTEND:20180515T010000Z
UID:s26e-Bsy-wxShFezApchL_GF@stanza.co
SUMMARY:Crawdads vs. Braves
DESCRIPTION:Crawdads vs. Braves\n\nFollow on MiLB First Pitch: https://stza.co/+w0Pa-2T\n\nShop: https://stza.co/+w0Pa-1n\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144532Z
LAST-MODIFIED:20180213T144532Z
TRANSP:OPAQUE
END:VEVENT
* Crawdads vs. Braves
<2018-05-15 Tue 09:30-12:30>
:PROPERTIES:
:ID:       XvLZNaUnbQ51PV3LOn2cekWq@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Crawdads vs. Braves Crawdads vs. Braves

Follow on MiLB First Pitch  https //stza.co/+w0Pc-2S

Shop  https //stza.co/+w0Pc-1G

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Crawdads vs. Braves
END:VALARM
DTSTART:20180515T143000Z
DTEND:20180515T173000Z
UID:XvLZNaUnbQ51PV3LOn2cekWq@stanza.co
SUMMARY:Crawdads vs. Braves
DESCRIPTION:Crawdads vs. Braves\n\nFollow on MiLB First Pitch: https://stza.co/+w0Pc-2S\n\nShop: https://stza.co/+w0Pc-1G\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144532Z
LAST-MODIFIED:20180213T144532Z
TRANSP:OPAQUE
END:VEVENT
* Crawdads @ Intimidators
<2018-05-17 Thu 17:35-20:35>
:PROPERTIES:
:ID:       IW3Lh4EBTzUu09e91nnQKhOp@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Crawdads @ Intimidators Crawdads @ Intimidators

Follow on MiLB First Pitch  https //stza.co/+wICU-j

Shop  https //stza.co/+wICU-1

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Crawdads @ Intimidators
END:VALARM
DTSTART:20180517T223500Z
DTEND:20180518T013500Z
UID:IW3Lh4EBTzUu09e91nnQKhOp@stanza.co
SUMMARY:Crawdads @ Intimidators
DESCRIPTION:Crawdads @ Intimidators\n\nFollow on MiLB First Pitch: https://stza.co/+wICU-j\n\nShop: https://stza.co/+wICU-1\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144532Z
LAST-MODIFIED:20180213T144532Z
TRANSP:OPAQUE
END:VEVENT
* Crawdads @ Intimidators
<2018-05-18 Fri 18:05-21:05>
:PROPERTIES:
:ID:       Oo36XELNM7FuOmisvbmplXLM@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Crawdads @ Intimidators Crawdads @ Intimidators

Follow on MiLB First Pitch  https //stza.co/+wICW-1Q

Shop  https //stza.co/+wICW-1S

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Crawdads @ Intimidators
END:VALARM
DTSTART:20180518T230500Z
DTEND:20180519T020500Z
UID:Oo36XELNM7FuOmisvbmplXLM@stanza.co
SUMMARY:Crawdads @ Intimidators
DESCRIPTION:Crawdads @ Intimidators\n\nFollow on MiLB First Pitch: https://stza.co/+wICW-1Q\n\nShop: https://stza.co/+wICW-1S\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144532Z
LAST-MODIFIED:20180213T144532Z
TRANSP:OPAQUE
END:VEVENT
* Crawdads @ Intimidators
<2018-05-19 Sat 18:05-21:05>
:PROPERTIES:
:ID:       3ZbT1ldipxAaFXW3mnFM9VoJ@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Crawdads @ Intimidators Crawdads @ Intimidators

Follow on MiLB First Pitch  https //stza.co/+wICX-h

Shop  https //stza.co/+wICX-2O

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Crawdads @ Intimidators
END:VALARM
DTSTART:20180519T230500Z
DTEND:20180520T020500Z
UID:3ZbT1ldipxAaFXW3mnFM9VoJ@stanza.co
SUMMARY:Crawdads @ Intimidators
DESCRIPTION:Crawdads @ Intimidators\n\nFollow on MiLB First Pitch: https://stza.co/+wICX-h\n\nShop: https://stza.co/+wICX-2O\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144532Z
LAST-MODIFIED:20180213T144532Z
TRANSP:OPAQUE
END:VEVENT
* Crawdads @ Intimidators
<2018-05-20 Sun 14:35-17:35>
:PROPERTIES:
:ID:       gnqamLEoDxDYcDWEFTlHNC1X@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Crawdads @ Intimidators Crawdads @ Intimidators

Follow on MiLB First Pitch  https //stza.co/+wICY-Q

Shop  https //stza.co/+wICY-z

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Crawdads @ Intimidators
END:VALARM
DTSTART:20180520T193500Z
DTEND:20180520T223500Z
UID:gnqamLEoDxDYcDWEFTlHNC1X@stanza.co
SUMMARY:Crawdads @ Intimidators
DESCRIPTION:Crawdads @ Intimidators\n\nFollow on MiLB First Pitch: https://stza.co/+wICY-Q\n\nShop: https://stza.co/+wICY-z\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144532Z
LAST-MODIFIED:20180213T144532Z
TRANSP:OPAQUE
END:VEVENT
* Crawdads vs. Shorebirds
<2018-05-21 Mon 17:00-20:00>
:PROPERTIES:
:ID:       OY0aDgDL3Et6HtXS7-GioETu@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Crawdads vs. Shorebirds Crawdads vs. Shorebirds

Follow on MiLB First Pitch  https //stza.co/+w0Pe-32

Shop  https //stza.co/+w0Pe-b

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Crawdads vs. Shorebirds
END:VALARM
DTSTART:20180521T220000Z
DTEND:20180522T010000Z
UID:OY0aDgDL3Et6HtXS7-GioETu@stanza.co
SUMMARY:Crawdads vs. Shorebirds
DESCRIPTION:Crawdads vs. Shorebirds\n\nFollow on MiLB First Pitch: https://stza.co/+w0Pe-32\n\nShop: https://stza.co/+w0Pe-b\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144532Z
LAST-MODIFIED:20180213T144532Z
TRANSP:OPAQUE
END:VEVENT
* Crawdads vs. Shorebirds
<2018-05-22 Tue 17:00-20:00>
:PROPERTIES:
:ID:       grHIheyX7PCil7sL1xNw74cZ@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Crawdads vs. Shorebirds Crawdads vs. Shorebirds

Follow on MiLB First Pitch  https //stza.co/+w0Pg-2C

Shop  https //stza.co/+w0Pg-24

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Crawdads vs. Shorebirds
END:VALARM
DTSTART:20180522T220000Z
DTEND:20180523T010000Z
UID:grHIheyX7PCil7sL1xNw74cZ@stanza.co
SUMMARY:Crawdads vs. Shorebirds
DESCRIPTION:Crawdads vs. Shorebirds\n\nFollow on MiLB First Pitch: https://stza.co/+w0Pg-2C\n\nShop: https://stza.co/+w0Pg-24\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144532Z
LAST-MODIFIED:20180213T144532Z
TRANSP:OPAQUE
END:VEVENT
* Crawdads vs. Shorebirds
<2018-05-23 Wed 17:00-20:00>
:PROPERTIES:
:ID:       vVp2f6Pk8DVNcWT2HfE9Zbs0@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Crawdads vs. Shorebirds Crawdads vs. Shorebirds

Follow on MiLB First Pitch  https //stza.co/+w0Pi-3c

Shop  https //stza.co/+w0Pi-1p

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Crawdads vs. Shorebirds
END:VALARM
DTSTART:20180523T220000Z
DTEND:20180524T010000Z
UID:vVp2f6Pk8DVNcWT2HfE9Zbs0@stanza.co
SUMMARY:Crawdads vs. Shorebirds
DESCRIPTION:Crawdads vs. Shorebirds\n\nFollow on MiLB First Pitch: https://stza.co/+w0Pi-3c\n\nShop: https://stza.co/+w0Pi-1p\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144532Z
LAST-MODIFIED:20180213T144532Z
TRANSP:OPAQUE
END:VEVENT
* Crawdads vs. Shorebirds
<2018-05-24 Thu 18:00-21:00>
:PROPERTIES:
:ID:       E7xxweNTBuVu4sjRP3z9qH7o@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Crawdads vs. Shorebirds Crawdads vs. Shorebirds

Follow on MiLB First Pitch  https //stza.co/+w0Pk-2S

Shop  https //stza.co/+w0Pk-1l

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Crawdads vs. Shorebirds
END:VALARM
DTSTART:20180524T230000Z
DTEND:20180525T020000Z
UID:E7xxweNTBuVu4sjRP3z9qH7o@stanza.co
SUMMARY:Crawdads vs. Shorebirds
DESCRIPTION:Crawdads vs. Shorebirds\n\nFollow on MiLB First Pitch: https://stza.co/+w0Pk-2S\n\nShop: https://stza.co/+w0Pk-1l\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144532Z
LAST-MODIFIED:20180213T144532Z
TRANSP:OPAQUE
END:VEVENT
* Crawdads vs. RiverDogs
<2018-05-25 Fri 18:00-21:00>
:PROPERTIES:
:ID:       ZtYWTGL522d29qlXfBJQYETF@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Crawdads vs. RiverDogs Crawdads vs. RiverDogs

Follow on MiLB First Pitch  https //stza.co/+w0Pn-30

Shop  https //stza.co/+w0Pn-3o

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Crawdads vs. RiverDogs
END:VALARM
DTSTART:20180525T230000Z
DTEND:20180526T020000Z
UID:ZtYWTGL522d29qlXfBJQYETF@stanza.co
SUMMARY:Crawdads vs. RiverDogs
DESCRIPTION:Crawdads vs. RiverDogs\n\nFollow on MiLB First Pitch: https://stza.co/+w0Pn-30\n\nShop: https://stza.co/+w0Pn-3o\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144532Z
LAST-MODIFIED:20180213T144532Z
TRANSP:OPAQUE
END:VEVENT
* Crawdads vs. RiverDogs
<2018-05-26 Sat 17:00-20:00>
:PROPERTIES:
:ID:       AoqBLYMhmkfq1P4e4FeNgjrb@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Crawdads vs. RiverDogs Crawdads vs. RiverDogs

Follow on MiLB First Pitch  https //stza.co/+w0Po-1h

Shop  https //stza.co/+w0Po-1O

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Crawdads vs. RiverDogs
END:VALARM
DTSTART:20180526T220000Z
DTEND:20180527T010000Z
UID:AoqBLYMhmkfq1P4e4FeNgjrb@stanza.co
SUMMARY:Crawdads vs. RiverDogs
DESCRIPTION:Crawdads vs. RiverDogs\n\nFollow on MiLB First Pitch: https://stza.co/+w0Po-1h\n\nShop: https://stza.co/+w0Po-1O\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144532Z
LAST-MODIFIED:20180213T144532Z
TRANSP:OPAQUE
END:VEVENT
* Crawdads vs. RiverDogs
<2018-05-27 Sun 14:00-17:00>
:PROPERTIES:
:ID:       EohjBA70HM5CAnxwuvc3BuXf@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Crawdads vs. RiverDogs Crawdads vs. RiverDogs

Follow on MiLB First Pitch  https //stza.co/+w0Pr-2d

Shop  https //stza.co/+w0Pr-3z

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Crawdads vs. RiverDogs
END:VALARM
DTSTART:20180527T190000Z
DTEND:20180527T220000Z
UID:EohjBA70HM5CAnxwuvc3BuXf@stanza.co
SUMMARY:Crawdads vs. RiverDogs
DESCRIPTION:Crawdads vs. RiverDogs\n\nFollow on MiLB First Pitch: https://stza.co/+w0Pr-2d\n\nShop: https://stza.co/+w0Pr-3z\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144532Z
LAST-MODIFIED:20180213T144532Z
TRANSP:OPAQUE
END:VEVENT
* Crawdads vs. RiverDogs
<2018-05-28 Mon 12:00-15:00>
:PROPERTIES:
:ID:       57G5lQ2ga4g-PU4LeaSq-JcV@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Crawdads vs. RiverDogs Crawdads vs. RiverDogs

Follow on MiLB First Pitch  https //stza.co/+w0Pt-1A

Shop  https //stza.co/+w0Pt-2I

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Crawdads vs. RiverDogs
END:VALARM
DTSTART:20180528T170000Z
DTEND:20180528T200000Z
UID:57G5lQ2ga4g-PU4LeaSq-JcV@stanza.co
SUMMARY:Crawdads vs. RiverDogs
DESCRIPTION:Crawdads vs. RiverDogs\n\nFollow on MiLB First Pitch: https://stza.co/+w0Pt-1A\n\nShop: https://stza.co/+w0Pt-2I\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144532Z
LAST-MODIFIED:20180213T144532Z
TRANSP:OPAQUE
END:VEVENT
* Crawdads @ Suns
<2018-05-29 Tue 18:05-21:05>
:PROPERTIES:
:ID:       OImz_tQGx66ILaibMd-VFpyV@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Crawdads @ Suns Crawdads @ Suns

Follow on MiLB First Pitch  https //stza.co/+xF7C-k

Shop  https //stza.co/+xF7C-1R

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Crawdads @ Suns
END:VALARM
DTSTART:20180529T230500Z
DTEND:20180530T020500Z
UID:OImz_tQGx66ILaibMd-VFpyV@stanza.co
SUMMARY:Crawdads @ Suns
DESCRIPTION:Crawdads @ Suns\n\nFollow on MiLB First Pitch: https://stza.co/+xF7C-k\n\nShop: https://stza.co/+xF7C-1R\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144532Z
LAST-MODIFIED:20180213T144532Z
TRANSP:OPAQUE
END:VEVENT
* Crawdads @ Suns
<2018-05-30 Wed 18:05-21:05>
:PROPERTIES:
:ID:       2F8ZtKoFzNphK3RXeuD0yjDA@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Crawdads @ Suns Crawdads @ Suns

Follow on MiLB First Pitch  https //stza.co/+xF7D-2I

Shop  https //stza.co/+xF7D-1i

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Crawdads @ Suns
END:VALARM
DTSTART:20180530T230500Z
DTEND:20180531T020500Z
UID:2F8ZtKoFzNphK3RXeuD0yjDA@stanza.co
SUMMARY:Crawdads @ Suns
DESCRIPTION:Crawdads @ Suns\n\nFollow on MiLB First Pitch: https://stza.co/+xF7D-2I\n\nShop: https://stza.co/+xF7D-1i\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144532Z
LAST-MODIFIED:20180213T144532Z
TRANSP:OPAQUE
END:VEVENT
* Crawdads @ Suns
<2018-05-31 Thu 18:05-21:05>
:PROPERTIES:
:ID:       y47DTPbzo1EJLvACamMiIEt_@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Crawdads @ Suns Crawdads @ Suns

Follow on MiLB First Pitch  https //stza.co/+xF7E-2v

Shop  https //stza.co/+xF7E-2z

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Crawdads @ Suns
END:VALARM
DTSTART:20180531T230500Z
DTEND:20180601T020500Z
UID:y47DTPbzo1EJLvACamMiIEt_@stanza.co
SUMMARY:Crawdads @ Suns
DESCRIPTION:Crawdads @ Suns\n\nFollow on MiLB First Pitch: https://stza.co/+xF7E-2v\n\nShop: https://stza.co/+xF7E-2z\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144532Z
LAST-MODIFIED:20180213T144532Z
TRANSP:OPAQUE
END:VEVENT
* Crawdads @ BlueClaws
<2018-06-01 Fri 18:05-21:05>
:PROPERTIES:
:ID:       aESRJzleCWJMyoJ2WbUdQR4g@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Crawdads @ BlueClaws Crawdads @ BlueClaws

Follow on MiLB First Pitch  https //stza.co/+vNPe-S

Shop  https //stza.co/+vNPe-3o

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Crawdads @ BlueClaws
END:VALARM
DTSTART:20180601T230500Z
DTEND:20180602T020500Z
UID:aESRJzleCWJMyoJ2WbUdQR4g@stanza.co
SUMMARY:Crawdads @ BlueClaws
DESCRIPTION:Crawdads @ BlueClaws\n\nFollow on MiLB First Pitch: https://stza.co/+vNPe-S\n\nShop: https://stza.co/+vNPe-3o\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144532Z
LAST-MODIFIED:20180213T144532Z
TRANSP:OPAQUE
END:VEVENT
* Crawdads @ BlueClaws
<2018-06-02 Sat 18:05-21:05>
:PROPERTIES:
:ID:       2xAi_ezf4QmvNmEdG91__-yN@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Crawdads @ BlueClaws Crawdads @ BlueClaws

Follow on MiLB First Pitch  https //stza.co/+vNPf-2d

Shop  https //stza.co/+vNPf-1i

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Crawdads @ BlueClaws
END:VALARM
DTSTART:20180602T230500Z
DTEND:20180603T020500Z
UID:2xAi_ezf4QmvNmEdG91__-yN@stanza.co
SUMMARY:Crawdads @ BlueClaws
DESCRIPTION:Crawdads @ BlueClaws\n\nFollow on MiLB First Pitch: https://stza.co/+vNPf-2d\n\nShop: https://stza.co/+vNPf-1i\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144532Z
LAST-MODIFIED:20180213T144532Z
TRANSP:OPAQUE
END:VEVENT
* Crawdads @ BlueClaws
<2018-06-03 Sun 12:05-15:05>
:PROPERTIES:
:ID:       CsQejPPEnDbeYh6q2qZNkQWy@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Crawdads @ BlueClaws Crawdads @ BlueClaws

Follow on MiLB First Pitch  https //stza.co/+vNPg-1I

Shop  https //stza.co/+vNPg-3o

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Crawdads @ BlueClaws
END:VALARM
DTSTART:20180603T170500Z
DTEND:20180603T200500Z
UID:CsQejPPEnDbeYh6q2qZNkQWy@stanza.co
SUMMARY:Crawdads @ BlueClaws
DESCRIPTION:Crawdads @ BlueClaws\n\nFollow on MiLB First Pitch: https://stza.co/+vNPg-1I\n\nShop: https://stza.co/+vNPg-3o\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144532Z
LAST-MODIFIED:20180213T144532Z
TRANSP:OPAQUE
END:VEVENT
* Crawdads vs. Intimidators
<2018-06-05 Tue 17:00-20:00>
:PROPERTIES:
:ID:       g5r2t5_B5O2BHB5Us5IvmFUw@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Crawdads vs. Intimidators Crawdads vs. Intimidators

Follow on MiLB First Pitch  https //stza.co/+w0Pv-1D

Shop  https //stza.co/+w0Pv-H

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Crawdads vs. Intimidators
END:VALARM
DTSTART:20180605T220000Z
DTEND:20180606T010000Z
UID:g5r2t5_B5O2BHB5Us5IvmFUw@stanza.co
SUMMARY:Crawdads vs. Intimidators
DESCRIPTION:Crawdads vs. Intimidators\n\nFollow on MiLB First Pitch: https://stza.co/+w0Pv-1D\n\nShop: https://stza.co/+w0Pv-H\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144532Z
LAST-MODIFIED:20180213T144532Z
TRANSP:OPAQUE
END:VEVENT
* Crawdads vs. Intimidators
<2018-06-06 Wed 09:30-12:30>
:PROPERTIES:
:ID:       fAWwN9hi5E_5yucmeS-emcaY@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Crawdads vs. Intimidators Crawdads vs. Intimidators

Follow on MiLB First Pitch  https //stza.co/+w0Pw-2B

Shop  https //stza.co/+w0Pw-R

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Crawdads vs. Intimidators
END:VALARM
DTSTART:20180606T143000Z
DTEND:20180606T173000Z
UID:fAWwN9hi5E_5yucmeS-emcaY@stanza.co
SUMMARY:Crawdads vs. Intimidators
DESCRIPTION:Crawdads vs. Intimidators\n\nFollow on MiLB First Pitch: https://stza.co/+w0Pw-2B\n\nShop: https://stza.co/+w0Pw-R\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144532Z
LAST-MODIFIED:20180213T144532Z
TRANSP:OPAQUE
END:VEVENT
* Crawdads vs. Intimidators
<2018-06-07 Thu 18:00-21:00>
:PROPERTIES:
:ID:       AsMeVBiJhrWPQu8RIiRd1Ot4@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Crawdads vs. Intimidators Crawdads vs. Intimidators

Follow on MiLB First Pitch  https //stza.co/+w0Pz-m

Shop  https //stza.co/+w0Pz-o

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Crawdads vs. Intimidators
END:VALARM
DTSTART:20180607T230000Z
DTEND:20180608T020000Z
UID:AsMeVBiJhrWPQu8RIiRd1Ot4@stanza.co
SUMMARY:Crawdads vs. Intimidators
DESCRIPTION:Crawdads vs. Intimidators\n\nFollow on MiLB First Pitch: https://stza.co/+w0Pz-m\n\nShop: https://stza.co/+w0Pz-o\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144532Z
LAST-MODIFIED:20180213T144532Z
TRANSP:OPAQUE
END:VEVENT
* Crawdads vs. Power
<2018-06-08 Fri 18:00-21:00>
:PROPERTIES:
:ID:       qeK3Z7cU7DihIvkaiy-lyl-7@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Crawdads vs. Power Crawdads vs. Power

Follow on MiLB First Pitch  https //stza.co/+w0PA-3E

Shop  https //stza.co/+w0PA-n

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Crawdads vs. Power
END:VALARM
DTSTART:20180608T230000Z
DTEND:20180609T020000Z
UID:qeK3Z7cU7DihIvkaiy-lyl-7@stanza.co
SUMMARY:Crawdads vs. Power
DESCRIPTION:Crawdads vs. Power\n\nFollow on MiLB First Pitch: https://stza.co/+w0PA-3E\n\nShop: https://stza.co/+w0PA-n\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144532Z
LAST-MODIFIED:20180213T144532Z
TRANSP:OPAQUE
END:VEVENT
* Crawdads vs. Power
<2018-06-09 Sat 17:00-20:00>
:PROPERTIES:
:ID:       MVHaEqCgfIlWwVvE3m_rQiNK@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Crawdads vs. Power Crawdads vs. Power

Follow on MiLB First Pitch  https //stza.co/+w0PC-3N

Shop  https //stza.co/+w0PC-3h

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Crawdads vs. Power
END:VALARM
DTSTART:20180609T220000Z
DTEND:20180610T010000Z
UID:MVHaEqCgfIlWwVvE3m_rQiNK@stanza.co
SUMMARY:Crawdads vs. Power
DESCRIPTION:Crawdads vs. Power\n\nFollow on MiLB First Pitch: https://stza.co/+w0PC-3N\n\nShop: https://stza.co/+w0PC-3h\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144532Z
LAST-MODIFIED:20180213T144532Z
TRANSP:OPAQUE
END:VEVENT
* Crawdads vs. Power
<2018-06-10 Sun 14:00-17:00>
:PROPERTIES:
:ID:       rHNNnWLFstKSr3KPAtGt0zGe@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Crawdads vs. Power Crawdads vs. Power

Follow on MiLB First Pitch  https //stza.co/+w0PF-E

Shop  https //stza.co/+w0PF-B

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Crawdads vs. Power
END:VALARM
DTSTART:20180610T190000Z
DTEND:20180610T220000Z
UID:rHNNnWLFstKSr3KPAtGt0zGe@stanza.co
SUMMARY:Crawdads vs. Power
DESCRIPTION:Crawdads vs. Power\n\nFollow on MiLB First Pitch: https://stza.co/+w0PF-E\n\nShop: https://stza.co/+w0PF-B\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144532Z
LAST-MODIFIED:20180213T144532Z
TRANSP:OPAQUE
END:VEVENT
* Crawdads @ Grasshoppers
<2018-06-11 Mon 18:00-21:00>
:PROPERTIES:
:ID:       sby2sXociaDH9nAvXsePOp7v@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Crawdads @ Grasshoppers Crawdads @ Grasshoppers

Follow on MiLB First Pitch  https //stza.co/+wizo-1b

Shop  https //stza.co/+wizo-M

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Crawdads @ Grasshoppers
END:VALARM
DTSTART:20180611T230000Z
DTEND:20180612T020000Z
UID:sby2sXociaDH9nAvXsePOp7v@stanza.co
SUMMARY:Crawdads @ Grasshoppers
DESCRIPTION:Crawdads @ Grasshoppers\n\nFollow on MiLB First Pitch: https://stza.co/+wizo-1b\n\nShop: https://stza.co/+wizo-M\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144532Z
LAST-MODIFIED:20180213T144532Z
TRANSP:OPAQUE
END:VEVENT
* Crawdads @ Grasshoppers
<2018-06-12 Tue 18:00-21:00>
:PROPERTIES:
:ID:       GYFygwCM3Ib0yuRlaFkDGIEO@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Crawdads @ Grasshoppers Crawdads @ Grasshoppers

Follow on MiLB First Pitch  https //stza.co/+wizp-f

Shop  https //stza.co/+wizp-A

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Crawdads @ Grasshoppers
END:VALARM
DTSTART:20180612T230000Z
DTEND:20180613T020000Z
UID:GYFygwCM3Ib0yuRlaFkDGIEO@stanza.co
SUMMARY:Crawdads @ Grasshoppers
DESCRIPTION:Crawdads @ Grasshoppers\n\nFollow on MiLB First Pitch: https://stza.co/+wizp-f\n\nShop: https://stza.co/+wizp-A\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144532Z
LAST-MODIFIED:20180213T144532Z
TRANSP:OPAQUE
END:VEVENT
* Crawdads @ Grasshoppers
<2018-06-13 Wed 11:00-14:00>
:PROPERTIES:
:ID:       wDYg2OplluCDBFb5OlIpe-Ff@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Crawdads @ Grasshoppers Crawdads @ Grasshoppers

Follow on MiLB First Pitch  https //stza.co/+wizq-16

Shop  https //stza.co/+wizq-2R

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Crawdads @ Grasshoppers
END:VALARM
DTSTART:20180613T160000Z
DTEND:20180613T190000Z
UID:wDYg2OplluCDBFb5OlIpe-Ff@stanza.co
SUMMARY:Crawdads @ Grasshoppers
DESCRIPTION:Crawdads @ Grasshoppers\n\nFollow on MiLB First Pitch: https://stza.co/+wizq-16\n\nShop: https://stza.co/+wizq-2R\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144532Z
LAST-MODIFIED:20180213T144532Z
TRANSP:OPAQUE
END:VEVENT
* Crawdads @ Grasshoppers
<2018-06-14 Thu 18:00-21:00>
:PROPERTIES:
:ID:       GLXDaEgn5gzoQJtMnj_te9p6@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Crawdads @ Grasshoppers Crawdads @ Grasshoppers

Follow on MiLB First Pitch  https //stza.co/+wizr-3Q

Shop  https //stza.co/+wizr-$

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Crawdads @ Grasshoppers
END:VALARM
DTSTART:20180614T230000Z
DTEND:20180615T020000Z
UID:GLXDaEgn5gzoQJtMnj_te9p6@stanza.co
SUMMARY:Crawdads @ Grasshoppers
DESCRIPTION:Crawdads @ Grasshoppers\n\nFollow on MiLB First Pitch: https://stza.co/+wizr-3Q\n\nShop: https://stza.co/+wizr-$\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144532Z
LAST-MODIFIED:20180213T144532Z
TRANSP:OPAQUE
END:VEVENT
* Crawdads @ BlueClaws
<2018-06-15 Fri 18:05-21:05>
:PROPERTIES:
:ID:       zcewJJmAXpfsReOPF4Wt-zKW@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Crawdads @ BlueClaws Crawdads @ BlueClaws

Follow on MiLB First Pitch  https //stza.co/+vNPh-36

Shop  https //stza.co/+vNPh-13

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Crawdads @ BlueClaws
END:VALARM
DTSTART:20180615T230500Z
DTEND:20180616T020500Z
UID:zcewJJmAXpfsReOPF4Wt-zKW@stanza.co
SUMMARY:Crawdads @ BlueClaws
DESCRIPTION:Crawdads @ BlueClaws\n\nFollow on MiLB First Pitch: https://stza.co/+vNPh-36\n\nShop: https://stza.co/+vNPh-13\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144532Z
LAST-MODIFIED:20180213T144532Z
TRANSP:OPAQUE
END:VEVENT
* Crawdads @ BlueClaws
<2018-06-16 Sat 18:05-21:05>
:PROPERTIES:
:ID:       Hr6ZVabTx-4JY4qSRqnzUe4a@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Crawdads @ BlueClaws Crawdads @ BlueClaws

Follow on MiLB First Pitch  https //stza.co/+vNPi-2L

Shop  https //stza.co/+vNPi-28

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Crawdads @ BlueClaws
END:VALARM
DTSTART:20180616T230500Z
DTEND:20180617T020500Z
UID:Hr6ZVabTx-4JY4qSRqnzUe4a@stanza.co
SUMMARY:Crawdads @ BlueClaws
DESCRIPTION:Crawdads @ BlueClaws\n\nFollow on MiLB First Pitch: https://stza.co/+vNPi-2L\n\nShop: https://stza.co/+vNPi-28\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144532Z
LAST-MODIFIED:20180213T144532Z
TRANSP:OPAQUE
END:VEVENT
* Crawdads @ BlueClaws
<2018-06-17 Sun 12:05-15:05>
:PROPERTIES:
:ID:       RkE-2g8i63LcO03JEp9ZrHTW@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Crawdads @ BlueClaws Crawdads @ BlueClaws

Follow on MiLB First Pitch  https //stza.co/+vNPj-Y

Shop  https //stza.co/+vNPj-1Y

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Crawdads @ BlueClaws
END:VALARM
DTSTART:20180617T170500Z
DTEND:20180617T200500Z
UID:RkE-2g8i63LcO03JEp9ZrHTW@stanza.co
SUMMARY:Crawdads @ BlueClaws
DESCRIPTION:Crawdads @ BlueClaws\n\nFollow on MiLB First Pitch: https://stza.co/+vNPj-Y\n\nShop: https://stza.co/+vNPj-1Y\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144532Z
LAST-MODIFIED:20180213T144532Z
TRANSP:OPAQUE
END:VEVENT
* Crawdads vs. Power
<2018-06-21 Thu 18:00-21:00>
:PROPERTIES:
:ID:       lY2yXJgYu1ro4G2d8NbmXxzJ@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Crawdads vs. Power Crawdads vs. Power

Follow on MiLB First Pitch  https //stza.co/+w0PG-Q

Shop  https //stza.co/+w0PG-O

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Crawdads vs. Power
END:VALARM
DTSTART:20180621T230000Z
DTEND:20180622T020000Z
UID:lY2yXJgYu1ro4G2d8NbmXxzJ@stanza.co
SUMMARY:Crawdads vs. Power
DESCRIPTION:Crawdads vs. Power\n\nFollow on MiLB First Pitch: https://stza.co/+w0PG-Q\n\nShop: https://stza.co/+w0PG-O\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144532Z
LAST-MODIFIED:20180213T144532Z
TRANSP:OPAQUE
END:VEVENT
* Crawdads vs. Power
<2018-06-22 Fri 18:00-21:00>
:PROPERTIES:
:ID:       7v3w8XLaruDbmZ5VQ2EuDdRK@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Crawdads vs. Power Crawdads vs. Power

Follow on MiLB First Pitch  https //stza.co/+w0PI-3o

Shop  https //stza.co/+w0PI-S

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Crawdads vs. Power
END:VALARM
DTSTART:20180622T230000Z
DTEND:20180623T020000Z
UID:7v3w8XLaruDbmZ5VQ2EuDdRK@stanza.co
SUMMARY:Crawdads vs. Power
DESCRIPTION:Crawdads vs. Power\n\nFollow on MiLB First Pitch: https://stza.co/+w0PI-3o\n\nShop: https://stza.co/+w0PI-S\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144532Z
LAST-MODIFIED:20180213T144532Z
TRANSP:OPAQUE
END:VEVENT
* Crawdads vs. Power
<2018-06-23 Sat 18:00-21:00>
:PROPERTIES:
:ID:       xLOddGQBSYicObFGGBXrqEJc@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Crawdads vs. Power Crawdads vs. Power

Follow on MiLB First Pitch  https //stza.co/+w0PL-19

Shop  https //stza.co/+w0PL-3L

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Crawdads vs. Power
END:VALARM
DTSTART:20180623T230000Z
DTEND:20180624T020000Z
UID:xLOddGQBSYicObFGGBXrqEJc@stanza.co
SUMMARY:Crawdads vs. Power
DESCRIPTION:Crawdads vs. Power\n\nFollow on MiLB First Pitch: https://stza.co/+w0PL-19\n\nShop: https://stza.co/+w0PL-3L\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144532Z
LAST-MODIFIED:20180213T144532Z
TRANSP:OPAQUE
END:VEVENT
* Crawdads vs. GreenJackets
<2018-06-24 Sun 16:00-19:00>
:PROPERTIES:
:ID:       VAhQK7UNAqs6M9qiCH60bH09@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Crawdads vs. GreenJackets Crawdads vs. GreenJackets

Follow on MiLB First Pitch  https //stza.co/+w0PM-1q

Shop  https //stza.co/+w0PM-2k

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Crawdads vs. GreenJackets
END:VALARM
DTSTART:20180624T210000Z
DTEND:20180625T000000Z
UID:VAhQK7UNAqs6M9qiCH60bH09@stanza.co
SUMMARY:Crawdads vs. GreenJackets
DESCRIPTION:Crawdads vs. GreenJackets\n\nFollow on MiLB First Pitch: https://stza.co/+w0PM-1q\n\nShop: https://stza.co/+w0PM-2k\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144532Z
LAST-MODIFIED:20180213T144532Z
TRANSP:OPAQUE
END:VEVENT
* Crawdads vs. GreenJackets
<2018-06-25 Mon 18:00-21:00>
:PROPERTIES:
:ID:       jf2ThHTeZ5_ja9F4g6zmgCQc@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Crawdads vs. GreenJackets Crawdads vs. GreenJackets

Follow on MiLB First Pitch  https //stza.co/+w0PP-3C

Shop  https //stza.co/+w0PP-2N

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Crawdads vs. GreenJackets
END:VALARM
DTSTART:20180625T230000Z
DTEND:20180626T020000Z
UID:jf2ThHTeZ5_ja9F4g6zmgCQc@stanza.co
SUMMARY:Crawdads vs. GreenJackets
DESCRIPTION:Crawdads vs. GreenJackets\n\nFollow on MiLB First Pitch: https://stza.co/+w0PP-3C\n\nShop: https://stza.co/+w0PP-2N\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144532Z
LAST-MODIFIED:20180213T144532Z
TRANSP:OPAQUE
END:VEVENT
* Crawdads vs. GreenJackets
<2018-06-26 Tue 11:00-14:00>
:PROPERTIES:
:ID:       Bf2Cj3ps9gtRsIfYpL35iG5o@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Crawdads vs. GreenJackets Crawdads vs. GreenJackets

Follow on MiLB First Pitch  https //stza.co/+w0PR-X

Shop  https //stza.co/+w0PR-W

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Crawdads vs. GreenJackets
END:VALARM
DTSTART:20180626T160000Z
DTEND:20180626T190000Z
UID:Bf2Cj3ps9gtRsIfYpL35iG5o@stanza.co
SUMMARY:Crawdads vs. GreenJackets
DESCRIPTION:Crawdads vs. GreenJackets\n\nFollow on MiLB First Pitch: https://stza.co/+w0PR-X\n\nShop: https://stza.co/+w0PR-W\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144532Z
LAST-MODIFIED:20180213T144532Z
TRANSP:OPAQUE
END:VEVENT
* Crawdads @ Power
<2018-06-27 Wed 18:05-21:05>
:PROPERTIES:
:ID:       77-jofqFTQAr_357LqORNyka@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Crawdads @ Power Crawdads @ Power

Follow on MiLB First Pitch  https //stza.co/+xJ42-d

Shop  https //stza.co/+xJ42-26

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Crawdads @ Power
END:VALARM
DTSTART:20180627T230500Z
DTEND:20180628T020500Z
UID:77-jofqFTQAr_357LqORNyka@stanza.co
SUMMARY:Crawdads @ Power
DESCRIPTION:Crawdads @ Power\n\nFollow on MiLB First Pitch: https://stza.co/+xJ42-d\n\nShop: https://stza.co/+xJ42-26\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144532Z
LAST-MODIFIED:20180213T144532Z
TRANSP:OPAQUE
END:VEVENT
* Crawdads @ Power
<2018-06-28 Thu 18:05-21:05>
:PROPERTIES:
:ID:       Lg4nvpz5woPzD3edYjY0gyt-@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Crawdads @ Power Crawdads @ Power

Follow on MiLB First Pitch  https //stza.co/+xJ43-3l

Shop  https //stza.co/+xJ43-2s

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Crawdads @ Power
END:VALARM
DTSTART:20180628T230500Z
DTEND:20180629T020500Z
UID:Lg4nvpz5woPzD3edYjY0gyt-@stanza.co
SUMMARY:Crawdads @ Power
DESCRIPTION:Crawdads @ Power\n\nFollow on MiLB First Pitch: https://stza.co/+xJ43-3l\n\nShop: https://stza.co/+xJ43-2s\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144532Z
LAST-MODIFIED:20180213T144532Z
TRANSP:OPAQUE
END:VEVENT
* Crawdads @ Power
<2018-06-29 Fri 18:05-21:05>
:PROPERTIES:
:ID:       jK9SYb-tAa5oUfumwX-nwN0Y@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Crawdads @ Power Crawdads @ Power

Follow on MiLB First Pitch  https //stza.co/+xJ44-37

Shop  https //stza.co/+xJ44-2w

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Crawdads @ Power
END:VALARM
DTSTART:20180629T230500Z
DTEND:20180630T020500Z
UID:jK9SYb-tAa5oUfumwX-nwN0Y@stanza.co
SUMMARY:Crawdads @ Power
DESCRIPTION:Crawdads @ Power\n\nFollow on MiLB First Pitch: https://stza.co/+xJ44-37\n\nShop: https://stza.co/+xJ44-2w\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144532Z
LAST-MODIFIED:20180213T144532Z
TRANSP:OPAQUE
END:VEVENT
* Crawdads vs. Grasshoppers
<2018-06-30 Sat 18:00-21:00>
:PROPERTIES:
:ID:       KTFMar3hwDb0ITdtNRypFFuR@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Crawdads vs. Grasshoppers Crawdads vs. Grasshoppers

Follow on MiLB First Pitch  https //stza.co/+w0PT-1w

Shop  https //stza.co/+w0PT-3Y

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Crawdads vs. Grasshoppers
END:VALARM
DTSTART:20180630T230000Z
DTEND:20180701T020000Z
UID:KTFMar3hwDb0ITdtNRypFFuR@stanza.co
SUMMARY:Crawdads vs. Grasshoppers
DESCRIPTION:Crawdads vs. Grasshoppers\n\nFollow on MiLB First Pitch: https://stza.co/+w0PT-1w\n\nShop: https://stza.co/+w0PT-3Y\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144532Z
LAST-MODIFIED:20180213T144532Z
TRANSP:OPAQUE
END:VEVENT
* Crawdads vs. Grasshoppers
<2018-07-01 Sun 16:00-19:00>
:PROPERTIES:
:ID:       fln_M6U5aFpVW8Vr1AG-HGGI@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Crawdads vs. Grasshoppers Crawdads vs. Grasshoppers

Follow on MiLB First Pitch  https //stza.co/+w0PU-3x

Shop  https //stza.co/+w0PU-34

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Crawdads vs. Grasshoppers
END:VALARM
DTSTART:20180701T210000Z
DTEND:20180702T000000Z
UID:fln_M6U5aFpVW8Vr1AG-HGGI@stanza.co
SUMMARY:Crawdads vs. Grasshoppers
DESCRIPTION:Crawdads vs. Grasshoppers\n\nFollow on MiLB First Pitch: https://stza.co/+w0PU-3x\n\nShop: https://stza.co/+w0PU-34\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144532Z
LAST-MODIFIED:20180213T144532Z
TRANSP:OPAQUE
END:VEVENT
* Crawdads vs. Grasshoppers
<2018-07-02 Mon 18:00-21:00>
:PROPERTIES:
:ID:       7HvvoVZzgaj1-yNE1HDkL2hs@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Crawdads vs. Grasshoppers Crawdads vs. Grasshoppers

Follow on MiLB First Pitch  https //stza.co/+w0PW-1i

Shop  https //stza.co/+w0PW-3

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Crawdads vs. Grasshoppers
END:VALARM
DTSTART:20180702T230000Z
DTEND:20180703T020000Z
UID:7HvvoVZzgaj1-yNE1HDkL2hs@stanza.co
SUMMARY:Crawdads vs. Grasshoppers
DESCRIPTION:Crawdads vs. Grasshoppers\n\nFollow on MiLB First Pitch: https://stza.co/+w0PW-1i\n\nShop: https://stza.co/+w0PW-3\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144532Z
LAST-MODIFIED:20180213T144532Z
TRANSP:OPAQUE
END:VEVENT
* Crawdads vs. Grasshoppers
<2018-07-03 Tue 18:00-21:00>
:PROPERTIES:
:ID:       j91l8VVD8ia9_rgH_JTMVtuX@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Crawdads vs. Grasshoppers Crawdads vs. Grasshoppers

Follow on MiLB First Pitch  https //stza.co/+w0PZ-3_

Shop  https //stza.co/+w0PZ-3N

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Crawdads vs. Grasshoppers
END:VALARM
DTSTART:20180703T230000Z
DTEND:20180704T020000Z
UID:j91l8VVD8ia9_rgH_JTMVtuX@stanza.co
SUMMARY:Crawdads vs. Grasshoppers
DESCRIPTION:Crawdads vs. Grasshoppers\n\nFollow on MiLB First Pitch: https://stza.co/+w0PZ-3_\n\nShop: https://stza.co/+w0PZ-3N\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144532Z
LAST-MODIFIED:20180213T144532Z
TRANSP:OPAQUE
END:VEVENT
* Crawdads @ Intimidators
<2018-07-04 Wed 18:05-21:05>
:PROPERTIES:
:ID:       oluYtn0vGTE4QAKtZFF6NOsF@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Crawdads @ Intimidators Crawdads @ Intimidators

Follow on MiLB First Pitch  https //stza.co/+wICZ-3Y

Shop  https //stza.co/+wICZ-1j

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Crawdads @ Intimidators
END:VALARM
DTSTART:20180704T230500Z
DTEND:20180705T020500Z
UID:oluYtn0vGTE4QAKtZFF6NOsF@stanza.co
SUMMARY:Crawdads @ Intimidators
DESCRIPTION:Crawdads @ Intimidators\n\nFollow on MiLB First Pitch: https://stza.co/+wICZ-3Y\n\nShop: https://stza.co/+wICZ-1j\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144532Z
LAST-MODIFIED:20180213T144532Z
TRANSP:OPAQUE
END:VEVENT
* Crawdads @ Intimidators
<2018-07-05 Thu 18:05-21:05>
:PROPERTIES:
:ID:       5ihjiFIQtjK-_WACtnHtJCey@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Crawdads @ Intimidators Crawdads @ Intimidators

Follow on MiLB First Pitch  https //stza.co/+wIC_-$

Shop  https //stza.co/+wIC_-22

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Crawdads @ Intimidators
END:VALARM
DTSTART:20180705T230500Z
DTEND:20180706T020500Z
UID:5ihjiFIQtjK-_WACtnHtJCey@stanza.co
SUMMARY:Crawdads @ Intimidators
DESCRIPTION:Crawdads @ Intimidators\n\nFollow on MiLB First Pitch: https://stza.co/+wIC_-$\n\nShop: https://stza.co/+wIC_-22\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144532Z
LAST-MODIFIED:20180213T144532Z
TRANSP:OPAQUE
END:VEVENT
* Crawdads @ Intimidators
<2018-07-06 Fri 18:05-21:05>
:PROPERTIES:
:ID:       wjAIdrlkaOdZ8mrfI37hv9Q0@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Crawdads @ Intimidators Crawdads @ Intimidators

Follow on MiLB First Pitch  https //stza.co/+wIC$-3C

Shop  https //stza.co/+wIC$-1E

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Crawdads @ Intimidators
END:VALARM
DTSTART:20180706T230500Z
DTEND:20180707T020500Z
UID:wjAIdrlkaOdZ8mrfI37hv9Q0@stanza.co
SUMMARY:Crawdads @ Intimidators
DESCRIPTION:Crawdads @ Intimidators\n\nFollow on MiLB First Pitch: https://stza.co/+wIC$-3C\n\nShop: https://stza.co/+wIC$-1E\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144532Z
LAST-MODIFIED:20180213T144532Z
TRANSP:OPAQUE
END:VEVENT
* Crawdads @ Shorebirds
<2018-07-07 Sat 18:05-21:05>
:PROPERTIES:
:ID:       SKuNRHNRN-2YCRFmBh6KX5Uy@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Crawdads @ Shorebirds Crawdads @ Shorebirds

Follow on MiLB First Pitch  https //stza.co/+wHSg-3

Shop  https //stza.co/+wHSg-2H

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Crawdads @ Shorebirds
END:VALARM
DTSTART:20180707T230500Z
DTEND:20180708T020500Z
UID:SKuNRHNRN-2YCRFmBh6KX5Uy@stanza.co
SUMMARY:Crawdads @ Shorebirds
DESCRIPTION:Crawdads @ Shorebirds\n\nFollow on MiLB First Pitch: https://stza.co/+wHSg-3\n\nShop: https://stza.co/+wHSg-2H\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144532Z
LAST-MODIFIED:20180213T144532Z
TRANSP:OPAQUE
END:VEVENT
* Crawdads @ Shorebirds
<2018-07-08 Sun 16:05-19:05>
:PROPERTIES:
:ID:       2eCKDwfJuAIab0wslarMwAZX@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Crawdads @ Shorebirds Crawdads @ Shorebirds

Follow on MiLB First Pitch  https //stza.co/+wHSh-2w

Shop  https //stza.co/+wHSh-32

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Crawdads @ Shorebirds
END:VALARM
DTSTART:20180708T210500Z
DTEND:20180709T000500Z
UID:2eCKDwfJuAIab0wslarMwAZX@stanza.co
SUMMARY:Crawdads @ Shorebirds
DESCRIPTION:Crawdads @ Shorebirds\n\nFollow on MiLB First Pitch: https://stza.co/+wHSh-2w\n\nShop: https://stza.co/+wHSh-32\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144532Z
LAST-MODIFIED:20180213T144532Z
TRANSP:OPAQUE
END:VEVENT
* Crawdads @ Shorebirds
<2018-07-09 Mon 18:05-21:05>
:PROPERTIES:
:ID:       3Az6d8wmpSD8YcEzcy8nJd-8@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Crawdads @ Shorebirds Crawdads @ Shorebirds

Follow on MiLB First Pitch  https //stza.co/+wHSi-5

Shop  https //stza.co/+wHSi-3V

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Crawdads @ Shorebirds
END:VALARM
DTSTART:20180709T230500Z
DTEND:20180710T020500Z
UID:3Az6d8wmpSD8YcEzcy8nJd-8@stanza.co
SUMMARY:Crawdads @ Shorebirds
DESCRIPTION:Crawdads @ Shorebirds\n\nFollow on MiLB First Pitch: https://stza.co/+wHSi-5\n\nShop: https://stza.co/+wHSi-3V\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144532Z
LAST-MODIFIED:20180213T144532Z
TRANSP:OPAQUE
END:VEVENT
* Crawdads vs. Power
<2018-07-11 Wed 18:00-21:00>
:PROPERTIES:
:ID:       uEqaI78wniFkGj6DVWSidbFS@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Crawdads vs. Power Crawdads vs. Power

Follow on MiLB First Pitch  https //stza.co/+w0P_-2F

Shop  https //stza.co/+w0P_-3a

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Crawdads vs. Power
END:VALARM
DTSTART:20180711T230000Z
DTEND:20180712T020000Z
UID:uEqaI78wniFkGj6DVWSidbFS@stanza.co
SUMMARY:Crawdads vs. Power
DESCRIPTION:Crawdads vs. Power\n\nFollow on MiLB First Pitch: https://stza.co/+w0P_-2F\n\nShop: https://stza.co/+w0P_-3a\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144532Z
LAST-MODIFIED:20180213T144532Z
TRANSP:OPAQUE
END:VEVENT
* Crawdads vs. Power
<2018-07-12 Thu 18:00-21:00>
:PROPERTIES:
:ID:       Ru-B0hAvE5ps_5mQbn5r3vND@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Crawdads vs. Power Crawdads vs. Power

Follow on MiLB First Pitch  https //stza.co/+w0Q1-1H

Shop  https //stza.co/+w0Q1-1c

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Crawdads vs. Power
END:VALARM
DTSTART:20180712T230000Z
DTEND:20180713T020000Z
UID:Ru-B0hAvE5ps_5mQbn5r3vND@stanza.co
SUMMARY:Crawdads vs. Power
DESCRIPTION:Crawdads vs. Power\n\nFollow on MiLB First Pitch: https://stza.co/+w0Q1-1H\n\nShop: https://stza.co/+w0Q1-1c\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144532Z
LAST-MODIFIED:20180213T144532Z
TRANSP:OPAQUE
END:VEVENT
* Crawdads vs. Power
<2018-07-13 Fri 18:00-21:00>
:PROPERTIES:
:ID:       fh0gVEUy6OgBYvRV27Fisn2g@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Crawdads vs. Power Crawdads vs. Power

Follow on MiLB First Pitch  https //stza.co/+w0Q2-B

Shop  https //stza.co/+w0Q2-K

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Crawdads vs. Power
END:VALARM
DTSTART:20180713T230000Z
DTEND:20180714T020000Z
UID:fh0gVEUy6OgBYvRV27Fisn2g@stanza.co
SUMMARY:Crawdads vs. Power
DESCRIPTION:Crawdads vs. Power\n\nFollow on MiLB First Pitch: https://stza.co/+w0Q2-B\n\nShop: https://stza.co/+w0Q2-K\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144532Z
LAST-MODIFIED:20180213T144532Z
TRANSP:OPAQUE
END:VEVENT
* Crawdads @ RiverDogs
<2018-07-14 Sat 17:05-20:05>
:PROPERTIES:
:ID:       mOQ82U_7d0nDsjZ0YgF0z0Je@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Crawdads @ RiverDogs Crawdads @ RiverDogs

Follow on MiLB First Pitch  https //stza.co/+vNMc-1f

Shop  https //stza.co/+vNMc-1Y

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Crawdads @ RiverDogs
END:VALARM
DTSTART:20180714T220500Z
DTEND:20180715T010500Z
UID:mOQ82U_7d0nDsjZ0YgF0z0Je@stanza.co
SUMMARY:Crawdads @ RiverDogs
DESCRIPTION:Crawdads @ RiverDogs\n\nFollow on MiLB First Pitch: https://stza.co/+vNMc-1f\n\nShop: https://stza.co/+vNMc-1Y\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144532Z
LAST-MODIFIED:20180213T144532Z
TRANSP:OPAQUE
END:VEVENT
* Crawdads @ RiverDogs
<2018-07-15 Sun 16:05-19:05>
:PROPERTIES:
:ID:       F6QOE8Wi4B3oAIChjBkJOss_@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Crawdads @ RiverDogs Crawdads @ RiverDogs

Follow on MiLB First Pitch  https //stza.co/+vNMd-2a

Shop  https //stza.co/+vNMd-1t

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Crawdads @ RiverDogs
END:VALARM
DTSTART:20180715T210500Z
DTEND:20180716T000500Z
UID:F6QOE8Wi4B3oAIChjBkJOss_@stanza.co
SUMMARY:Crawdads @ RiverDogs
DESCRIPTION:Crawdads @ RiverDogs\n\nFollow on MiLB First Pitch: https://stza.co/+vNMd-2a\n\nShop: https://stza.co/+vNMd-1t\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144532Z
LAST-MODIFIED:20180213T144532Z
TRANSP:OPAQUE
END:VEVENT
* Crawdads @ RiverDogs
<2018-07-16 Mon 18:05-21:05>
:PROPERTIES:
:ID:       DHSiONrku_BfPDJRkWwpnKY9@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Crawdads @ RiverDogs Crawdads @ RiverDogs

Follow on MiLB First Pitch  https //stza.co/+vNMe-3u

Shop  https //stza.co/+vNMe-1c

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Crawdads @ RiverDogs
END:VALARM
DTSTART:20180716T230500Z
DTEND:20180717T020500Z
UID:DHSiONrku_BfPDJRkWwpnKY9@stanza.co
SUMMARY:Crawdads @ RiverDogs
DESCRIPTION:Crawdads @ RiverDogs\n\nFollow on MiLB First Pitch: https://stza.co/+vNMe-3u\n\nShop: https://stza.co/+vNMe-1c\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144532Z
LAST-MODIFIED:20180213T144532Z
TRANSP:OPAQUE
END:VEVENT
* Crawdads @ RiverDogs
<2018-07-17 Tue 11:05-14:05>
:PROPERTIES:
:ID:       oRqJKqXRXQRIXbzUVMM_Cqeu@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Crawdads @ RiverDogs Crawdads @ RiverDogs

Follow on MiLB First Pitch  https //stza.co/+vNMf-2S

Shop  https //stza.co/+vNMf-15

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Crawdads @ RiverDogs
END:VALARM
DTSTART:20180717T160500Z
DTEND:20180717T190500Z
UID:oRqJKqXRXQRIXbzUVMM_Cqeu@stanza.co
SUMMARY:Crawdads @ RiverDogs
DESCRIPTION:Crawdads @ RiverDogs\n\nFollow on MiLB First Pitch: https://stza.co/+vNMf-2S\n\nShop: https://stza.co/+vNMf-15\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144532Z
LAST-MODIFIED:20180213T144532Z
TRANSP:OPAQUE
END:VEVENT
* Crawdads vs. Intimidators
<2018-07-19 Thu 18:00-21:00>
:PROPERTIES:
:ID:       3Q0LKE4FFekWPQwem1YzebYS@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Crawdads vs. Intimidators Crawdads vs. Intimidators

Follow on MiLB First Pitch  https //stza.co/+w0Q5-10

Shop  https //stza.co/+w0Q5-2N

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Crawdads vs. Intimidators
END:VALARM
DTSTART:20180719T230000Z
DTEND:20180720T020000Z
UID:3Q0LKE4FFekWPQwem1YzebYS@stanza.co
SUMMARY:Crawdads vs. Intimidators
DESCRIPTION:Crawdads vs. Intimidators\n\nFollow on MiLB First Pitch: https://stza.co/+w0Q5-10\n\nShop: https://stza.co/+w0Q5-2N\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144532Z
LAST-MODIFIED:20180213T144532Z
TRANSP:OPAQUE
END:VEVENT
* Crawdads vs. Intimidators
<2018-07-20 Fri 18:00-21:00>
:PROPERTIES:
:ID:       MEZ_ar5jjQBXC4pE-V7EgW1Z@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Crawdads vs. Intimidators Crawdads vs. Intimidators

Follow on MiLB First Pitch  https //stza.co/+w0Q6-27

Shop  https //stza.co/+w0Q6-Y

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Crawdads vs. Intimidators
END:VALARM
DTSTART:20180720T230000Z
DTEND:20180721T020000Z
UID:MEZ_ar5jjQBXC4pE-V7EgW1Z@stanza.co
SUMMARY:Crawdads vs. Intimidators
DESCRIPTION:Crawdads vs. Intimidators\n\nFollow on MiLB First Pitch: https://stza.co/+w0Q6-27\n\nShop: https://stza.co/+w0Q6-Y\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144532Z
LAST-MODIFIED:20180213T144532Z
TRANSP:OPAQUE
END:VEVENT
* Crawdads vs. Intimidators
<2018-07-21 Sat 16:00-19:00>
:PROPERTIES:
:ID:       5OJ6MT11Ly6Vu5tjVOSy96mZ@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Crawdads vs. Intimidators Crawdads vs. Intimidators

Follow on MiLB First Pitch  https //stza.co/+xB4C-2g

Shop  https //stza.co/+xB4C-9

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Crawdads vs. Intimidators
END:VALARM
DTSTART:20180721T210000Z
DTEND:20180722T000000Z
UID:5OJ6MT11Ly6Vu5tjVOSy96mZ@stanza.co
SUMMARY:Crawdads vs. Intimidators
DESCRIPTION:Crawdads vs. Intimidators\n\nFollow on MiLB First Pitch: https://stza.co/+xB4C-2g\n\nShop: https://stza.co/+xB4C-9\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144532Z
LAST-MODIFIED:20180213T144532Z
TRANSP:OPAQUE
END:VEVENT
* Crawdads vs. Intimidators
<2018-07-22 Sun 16:00-19:00>
:PROPERTIES:
:ID:       HC9WncolntczisIlPOLxYVPL@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Crawdads vs. Intimidators Crawdads vs. Intimidators

Follow on MiLB First Pitch  https //stza.co/+w0Qb-l

Shop  https //stza.co/+w0Qb-L

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Crawdads vs. Intimidators
END:VALARM
DTSTART:20180722T210000Z
DTEND:20180723T000000Z
UID:HC9WncolntczisIlPOLxYVPL@stanza.co
SUMMARY:Crawdads vs. Intimidators
DESCRIPTION:Crawdads vs. Intimidators\n\nFollow on MiLB First Pitch: https://stza.co/+w0Qb-l\n\nShop: https://stza.co/+w0Qb-L\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144532Z
LAST-MODIFIED:20180213T144532Z
TRANSP:OPAQUE
END:VEVENT
* Crawdads @ Drive
<2018-07-23 Mon 18:05-21:05>
:PROPERTIES:
:ID:       x9cMMHSLpOQrWL91kDE76sh1@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Crawdads @ Drive Crawdads @ Drive

Follow on MiLB First Pitch  https //stza.co/+xGFQ-18

Shop  https //stza.co/+xGFQ-15

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Crawdads @ Drive
END:VALARM
DTSTART:20180723T230500Z
DTEND:20180724T020500Z
UID:x9cMMHSLpOQrWL91kDE76sh1@stanza.co
SUMMARY:Crawdads @ Drive
DESCRIPTION:Crawdads @ Drive\n\nFollow on MiLB First Pitch: https://stza.co/+xGFQ-18\n\nShop: https://stza.co/+xGFQ-15\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144532Z
LAST-MODIFIED:20180213T144532Z
TRANSP:OPAQUE
END:VEVENT
* Crawdads @ Drive
<2018-07-24 Tue 18:05-21:05>
:PROPERTIES:
:ID:       Gc6xwGGkcBqIBEhGN28HQpPV@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Crawdads @ Drive Crawdads @ Drive

Follow on MiLB First Pitch  https //stza.co/+xGFR-L

Shop  https //stza.co/+xGFR-1z

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Crawdads @ Drive
END:VALARM
DTSTART:20180724T230500Z
DTEND:20180725T020500Z
UID:Gc6xwGGkcBqIBEhGN28HQpPV@stanza.co
SUMMARY:Crawdads @ Drive
DESCRIPTION:Crawdads @ Drive\n\nFollow on MiLB First Pitch: https://stza.co/+xGFR-L\n\nShop: https://stza.co/+xGFR-1z\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144532Z
LAST-MODIFIED:20180213T144532Z
TRANSP:OPAQUE
END:VEVENT
* Crawdads @ Drive
<2018-07-25 Wed 18:05-21:05>
:PROPERTIES:
:ID:       7umPeHz9m8T6uTRfGFH2-JlE@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Crawdads @ Drive Crawdads @ Drive

Follow on MiLB First Pitch  https //stza.co/+xGFS-3E

Shop  https //stza.co/+xGFS-1H

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Crawdads @ Drive
END:VALARM
DTSTART:20180725T230500Z
DTEND:20180726T020500Z
UID:7umPeHz9m8T6uTRfGFH2-JlE@stanza.co
SUMMARY:Crawdads @ Drive
DESCRIPTION:Crawdads @ Drive\n\nFollow on MiLB First Pitch: https://stza.co/+xGFS-3E\n\nShop: https://stza.co/+xGFS-1H\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144532Z
LAST-MODIFIED:20180213T144532Z
TRANSP:OPAQUE
END:VEVENT
* Crawdads @ Drive
<2018-07-26 Thu 18:05-21:05>
:PROPERTIES:
:ID:       9pozQ0Ng7W_iE0EVkcKDwrbv@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Crawdads @ Drive Crawdads @ Drive

Follow on MiLB First Pitch  https //stza.co/+xF7w-34

Shop  https //stza.co/+xF7w-2i

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Crawdads @ Drive
END:VALARM
DTSTART:20180726T230500Z
DTEND:20180727T020500Z
UID:9pozQ0Ng7W_iE0EVkcKDwrbv@stanza.co
SUMMARY:Crawdads @ Drive
DESCRIPTION:Crawdads @ Drive\n\nFollow on MiLB First Pitch: https://stza.co/+xF7w-34\n\nShop: https://stza.co/+xF7w-2i\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144532Z
LAST-MODIFIED:20180213T144532Z
TRANSP:OPAQUE
END:VEVENT
* Crawdads @ Grasshoppers
<2018-07-27 Fri 18:00-21:00>
:PROPERTIES:
:ID:       gmk-NrawP_IEce43ilNvFomd@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Crawdads @ Grasshoppers Crawdads @ Grasshoppers

Follow on MiLB First Pitch  https //stza.co/+wizs-31

Shop  https //stza.co/+wizs-36

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Crawdads @ Grasshoppers
END:VALARM
DTSTART:20180727T230000Z
DTEND:20180728T020000Z
UID:gmk-NrawP_IEce43ilNvFomd@stanza.co
SUMMARY:Crawdads @ Grasshoppers
DESCRIPTION:Crawdads @ Grasshoppers\n\nFollow on MiLB First Pitch: https://stza.co/+wizs-31\n\nShop: https://stza.co/+wizs-36\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144532Z
LAST-MODIFIED:20180213T144532Z
TRANSP:OPAQUE
END:VEVENT
* Crawdads @ Grasshoppers
<2018-07-28 Sat 18:00-21:00>
:PROPERTIES:
:ID:       Aj86VeU_R1pJ7Nf6FQ0qIPzI@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Crawdads @ Grasshoppers Crawdads @ Grasshoppers

Follow on MiLB First Pitch  https //stza.co/+wizu-3I

Shop  https //stza.co/+wizu-J

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Crawdads @ Grasshoppers
END:VALARM
DTSTART:20180728T230000Z
DTEND:20180729T020000Z
UID:Aj86VeU_R1pJ7Nf6FQ0qIPzI@stanza.co
SUMMARY:Crawdads @ Grasshoppers
DESCRIPTION:Crawdads @ Grasshoppers\n\nFollow on MiLB First Pitch: https://stza.co/+wizu-3I\n\nShop: https://stza.co/+wizu-J\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144532Z
LAST-MODIFIED:20180213T144532Z
TRANSP:OPAQUE
END:VEVENT
* Crawdads @ Grasshoppers
<2018-07-29 Sun 15:00-18:00>
:PROPERTIES:
:ID:       RVjkNvFmIVwEjeVCMhARBn3Q@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Crawdads @ Grasshoppers Crawdads @ Grasshoppers

Follow on MiLB First Pitch  https //stza.co/+wizv-3Y

Shop  https //stza.co/+wizv-14

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Crawdads @ Grasshoppers
END:VALARM
DTSTART:20180729T200000Z
DTEND:20180729T230000Z
UID:RVjkNvFmIVwEjeVCMhARBn3Q@stanza.co
SUMMARY:Crawdads @ Grasshoppers
DESCRIPTION:Crawdads @ Grasshoppers\n\nFollow on MiLB First Pitch: https://stza.co/+wizv-3Y\n\nShop: https://stza.co/+wizv-14\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144532Z
LAST-MODIFIED:20180213T144532Z
TRANSP:OPAQUE
END:VEVENT
* Crawdads vs. RiverDogs
<2018-07-30 Mon 18:00-21:00>
:PROPERTIES:
:ID:       b5DDFCEqDN5iYOyIAYjeUjx6@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Crawdads vs. RiverDogs Crawdads vs. RiverDogs

Follow on MiLB First Pitch  https //stza.co/+w0Qd-S

Shop  https //stza.co/+w0Qd-2U

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Crawdads vs. RiverDogs
END:VALARM
DTSTART:20180730T230000Z
DTEND:20180731T020000Z
UID:b5DDFCEqDN5iYOyIAYjeUjx6@stanza.co
SUMMARY:Crawdads vs. RiverDogs
DESCRIPTION:Crawdads vs. RiverDogs\n\nFollow on MiLB First Pitch: https://stza.co/+w0Qd-S\n\nShop: https://stza.co/+w0Qd-2U\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144532Z
LAST-MODIFIED:20180213T144532Z
TRANSP:OPAQUE
END:VEVENT
* Crawdads vs. RiverDogs
<2018-07-31 Tue 18:00-21:00>
:PROPERTIES:
:ID:       UM9Vw6kLDar_hUL19ZxZ-kti@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Crawdads vs. RiverDogs Crawdads vs. RiverDogs

Follow on MiLB First Pitch  https //stza.co/+w0Qe-3O

Shop  https //stza.co/+w0Qe-3L

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Crawdads vs. RiverDogs
END:VALARM
DTSTART:20180731T230000Z
DTEND:20180801T020000Z
UID:UM9Vw6kLDar_hUL19ZxZ-kti@stanza.co
SUMMARY:Crawdads vs. RiverDogs
DESCRIPTION:Crawdads vs. RiverDogs\n\nFollow on MiLB First Pitch: https://stza.co/+w0Qe-3O\n\nShop: https://stza.co/+w0Qe-3L\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144532Z
LAST-MODIFIED:20180213T144532Z
TRANSP:OPAQUE
END:VEVENT
* Crawdads vs. RiverDogs
<2018-08-01 Wed 11:00-14:00>
:PROPERTIES:
:ID:       6a6IY5TkdwU6DmAIlieXhazU@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Crawdads vs. RiverDogs Crawdads vs. RiverDogs

Follow on MiLB First Pitch  https //stza.co/+w0Qg-2w

Shop  https //stza.co/+w0Qg-1c

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Crawdads vs. RiverDogs
END:VALARM
DTSTART:20180801T160000Z
DTEND:20180801T190000Z
UID:6a6IY5TkdwU6DmAIlieXhazU@stanza.co
SUMMARY:Crawdads vs. RiverDogs
DESCRIPTION:Crawdads vs. RiverDogs\n\nFollow on MiLB First Pitch: https://stza.co/+w0Qg-2w\n\nShop: https://stza.co/+w0Qg-1c\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144532Z
LAST-MODIFIED:20180213T144532Z
TRANSP:OPAQUE
END:VEVENT
* Crawdads @ Suns
<2018-08-02 Thu 18:05-21:05>
:PROPERTIES:
:ID:       of5IvzBcC7_-ncqFTETNpCcA@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Crawdads @ Suns Crawdads @ Suns

Follow on MiLB First Pitch  https //stza.co/+xF7F-3o

Shop  https //stza.co/+xF7F-A

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Crawdads @ Suns
END:VALARM
DTSTART:20180802T230500Z
DTEND:20180803T020500Z
UID:of5IvzBcC7_-ncqFTETNpCcA@stanza.co
SUMMARY:Crawdads @ Suns
DESCRIPTION:Crawdads @ Suns\n\nFollow on MiLB First Pitch: https://stza.co/+xF7F-3o\n\nShop: https://stza.co/+xF7F-A\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144532Z
LAST-MODIFIED:20180213T144532Z
TRANSP:OPAQUE
END:VEVENT
* Crawdads @ Suns
<2018-08-03 Fri 18:05-21:05>
:PROPERTIES:
:ID:       e_Y8a8_9zXWWSmMW2x52cUQD@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Crawdads @ Suns Crawdads @ Suns

Follow on MiLB First Pitch  https //stza.co/+xF7H-x

Shop  https //stza.co/+xF7H-24

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Crawdads @ Suns
END:VALARM
DTSTART:20180803T230500Z
DTEND:20180804T020500Z
UID:e_Y8a8_9zXWWSmMW2x52cUQD@stanza.co
SUMMARY:Crawdads @ Suns
DESCRIPTION:Crawdads @ Suns\n\nFollow on MiLB First Pitch: https://stza.co/+xF7H-x\n\nShop: https://stza.co/+xF7H-24\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144532Z
LAST-MODIFIED:20180213T144532Z
TRANSP:OPAQUE
END:VEVENT
* Crawdads @ Suns
<2018-08-04 Sat 17:05-20:05>
:PROPERTIES:
:ID:       cz2JmohSkw7gZGW1cihA2sLM@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Crawdads @ Suns Crawdads @ Suns

Follow on MiLB First Pitch  https //stza.co/+xF7I-15

Shop  https //stza.co/+xF7I-37

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Crawdads @ Suns
END:VALARM
DTSTART:20180804T220500Z
DTEND:20180805T010500Z
UID:cz2JmohSkw7gZGW1cihA2sLM@stanza.co
SUMMARY:Crawdads @ Suns
DESCRIPTION:Crawdads @ Suns\n\nFollow on MiLB First Pitch: https://stza.co/+xF7I-15\n\nShop: https://stza.co/+xF7I-37\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144532Z
LAST-MODIFIED:20180213T144532Z
TRANSP:OPAQUE
END:VEVENT
* Crawdads @ Suns
<2018-08-05 Sun 13:05-16:05>
:PROPERTIES:
:ID:       1b_68eaV-_Q4OzSXt8Z3dbl6@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Crawdads @ Suns Crawdads @ Suns

Follow on MiLB First Pitch  https //stza.co/+xF7M-k

Shop  https //stza.co/+xF7M-3C

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Crawdads @ Suns
END:VALARM
DTSTART:20180805T180500Z
DTEND:20180805T210500Z
UID:1b_68eaV-_Q4OzSXt8Z3dbl6@stanza.co
SUMMARY:Crawdads @ Suns
DESCRIPTION:Crawdads @ Suns\n\nFollow on MiLB First Pitch: https://stza.co/+xF7M-k\n\nShop: https://stza.co/+xF7M-3C\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144532Z
LAST-MODIFIED:20180213T144532Z
TRANSP:OPAQUE
END:VEVENT
* Crawdads vs. Intimidators
<2018-08-07 Tue 18:00-21:00>
:PROPERTIES:
:ID:       11ec0QEuxAK4cIeyyx4aHatt@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Crawdads vs. Intimidators Crawdads vs. Intimidators

Follow on MiLB First Pitch  https //stza.co/+w0Qi-3Z

Shop  https //stza.co/+w0Qi-1I

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Crawdads vs. Intimidators
END:VALARM
DTSTART:20180807T230000Z
DTEND:20180808T020000Z
UID:11ec0QEuxAK4cIeyyx4aHatt@stanza.co
SUMMARY:Crawdads vs. Intimidators
DESCRIPTION:Crawdads vs. Intimidators\n\nFollow on MiLB First Pitch: https://stza.co/+w0Qi-3Z\n\nShop: https://stza.co/+w0Qi-1I\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144532Z
LAST-MODIFIED:20180213T144532Z
TRANSP:OPAQUE
END:VEVENT
* Crawdads vs. Intimidators
<2018-08-08 Wed 18:00-21:00>
:PROPERTIES:
:ID:       I4IeT_MJ2T5_mPo2tVbAmSlG@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Crawdads vs. Intimidators Crawdads vs. Intimidators

Follow on MiLB First Pitch  https //stza.co/+w0Ql-1E

Shop  https //stza.co/+w0Ql-g

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Crawdads vs. Intimidators
END:VALARM
DTSTART:20180808T230000Z
DTEND:20180809T020000Z
UID:I4IeT_MJ2T5_mPo2tVbAmSlG@stanza.co
SUMMARY:Crawdads vs. Intimidators
DESCRIPTION:Crawdads vs. Intimidators\n\nFollow on MiLB First Pitch: https://stza.co/+w0Ql-1E\n\nShop: https://stza.co/+w0Ql-g\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144532Z
LAST-MODIFIED:20180213T144532Z
TRANSP:OPAQUE
END:VEVENT
* Crawdads vs. Intimidators
<2018-08-09 Thu 18:00-21:00>
:PROPERTIES:
:ID:       On2Mcqqcw9kKXhq2dpngHzsy@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Crawdads vs. Intimidators Crawdads vs. Intimidators

Follow on MiLB First Pitch  https //stza.co/+w0Qm-1c

Shop  https //stza.co/+w0Qm-3L

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Crawdads vs. Intimidators
END:VALARM
DTSTART:20180809T230000Z
DTEND:20180810T020000Z
UID:On2Mcqqcw9kKXhq2dpngHzsy@stanza.co
SUMMARY:Crawdads vs. Intimidators
DESCRIPTION:Crawdads vs. Intimidators\n\nFollow on MiLB First Pitch: https://stza.co/+w0Qm-1c\n\nShop: https://stza.co/+w0Qm-3L\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144532Z
LAST-MODIFIED:20180213T144532Z
TRANSP:OPAQUE
END:VEVENT
* Crawdads vs. BlueClaws
<2018-08-10 Fri 18:00-21:00>
:PROPERTIES:
:ID:       J4MQpm2iSnuyKaJgXO2CurPG@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Crawdads vs. BlueClaws Crawdads vs. BlueClaws

Follow on MiLB First Pitch  https //stza.co/+w0Qp-3F

Shop  https //stza.co/+w0Qp-13

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Crawdads vs. BlueClaws
END:VALARM
DTSTART:20180810T230000Z
DTEND:20180811T020000Z
UID:J4MQpm2iSnuyKaJgXO2CurPG@stanza.co
SUMMARY:Crawdads vs. BlueClaws
DESCRIPTION:Crawdads vs. BlueClaws\n\nFollow on MiLB First Pitch: https://stza.co/+w0Qp-3F\n\nShop: https://stza.co/+w0Qp-13\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144532Z
LAST-MODIFIED:20180213T144532Z
TRANSP:OPAQUE
END:VEVENT
* Crawdads vs. BlueClaws
<2018-08-11 Sat 18:00-21:00>
:PROPERTIES:
:ID:       O8uT6tGPfKh0EVufEIUpb-1V@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Crawdads vs. BlueClaws Crawdads vs. BlueClaws

Follow on MiLB First Pitch  https //stza.co/+xB4F-17

Shop  https //stza.co/+xB4F-3Q

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Crawdads vs. BlueClaws
END:VALARM
DTSTART:20180811T230000Z
DTEND:20180812T020000Z
UID:O8uT6tGPfKh0EVufEIUpb-1V@stanza.co
SUMMARY:Crawdads vs. BlueClaws
DESCRIPTION:Crawdads vs. BlueClaws\n\nFollow on MiLB First Pitch: https://stza.co/+xB4F-17\n\nShop: https://stza.co/+xB4F-3Q\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144532Z
LAST-MODIFIED:20180213T144532Z
TRANSP:OPAQUE
END:VEVENT
* Crawdads vs. BlueClaws
<2018-08-12 Sun 16:00-19:00>
:PROPERTIES:
:ID:       o5l8w3pdrsJx_i_FykskGUeO@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Crawdads vs. BlueClaws Crawdads vs. BlueClaws

Follow on MiLB First Pitch  https //stza.co/+w0Qt-2I

Shop  https //stza.co/+w0Qt-32

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Crawdads vs. BlueClaws
END:VALARM
DTSTART:20180812T210000Z
DTEND:20180813T000000Z
UID:o5l8w3pdrsJx_i_FykskGUeO@stanza.co
SUMMARY:Crawdads vs. BlueClaws
DESCRIPTION:Crawdads vs. BlueClaws\n\nFollow on MiLB First Pitch: https://stza.co/+w0Qt-2I\n\nShop: https://stza.co/+w0Qt-32\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144532Z
LAST-MODIFIED:20180213T144532Z
TRANSP:OPAQUE
END:VEVENT
* Crawdads vs. BlueClaws
<2018-08-13 Mon 11:00-14:00>
:PROPERTIES:
:ID:       tt4K-pIWglxXDOIqSMQOxvPC@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Crawdads vs. BlueClaws Crawdads vs. BlueClaws

Follow on MiLB First Pitch  https //stza.co/+w0Qv-1s

Shop  https //stza.co/+w0Qv-27

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Crawdads vs. BlueClaws
END:VALARM
DTSTART:20180813T160000Z
DTEND:20180813T190000Z
UID:tt4K-pIWglxXDOIqSMQOxvPC@stanza.co
SUMMARY:Crawdads vs. BlueClaws
DESCRIPTION:Crawdads vs. BlueClaws\n\nFollow on MiLB First Pitch: https://stza.co/+w0Qv-1s\n\nShop: https://stza.co/+w0Qv-27\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144532Z
LAST-MODIFIED:20180213T144532Z
TRANSP:OPAQUE
END:VEVENT
* Crawdads @ Tourists
<2018-08-15 Wed 18:05-21:05>
:PROPERTIES:
:ID:       q4Bm4ogjH8Qn6on7GOF8f5CW@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Crawdads @ Tourists Crawdads @ Tourists

Follow on MiLB First Pitch  https //stza.co/+vNM9-17

Shop  https //stza.co/+vNM9-21

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Crawdads @ Tourists
END:VALARM
DTSTART:20180815T230500Z
DTEND:20180816T020500Z
UID:q4Bm4ogjH8Qn6on7GOF8f5CW@stanza.co
SUMMARY:Crawdads @ Tourists
DESCRIPTION:Crawdads @ Tourists\n\nFollow on MiLB First Pitch: https://stza.co/+vNM9-17\n\nShop: https://stza.co/+vNM9-21\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144532Z
LAST-MODIFIED:20180213T144532Z
TRANSP:OPAQUE
END:VEVENT
* Crawdads @ Tourists
<2018-08-16 Thu 18:05-21:05>
:PROPERTIES:
:ID:       1-kjR5vD9zanKAkGASi9GbKg@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Crawdads @ Tourists Crawdads @ Tourists

Follow on MiLB First Pitch  https //stza.co/+vNMa-3G

Shop  https //stza.co/+vNMa-2t

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Crawdads @ Tourists
END:VALARM
DTSTART:20180816T230500Z
DTEND:20180817T020500Z
UID:1-kjR5vD9zanKAkGASi9GbKg@stanza.co
SUMMARY:Crawdads @ Tourists
DESCRIPTION:Crawdads @ Tourists\n\nFollow on MiLB First Pitch: https://stza.co/+vNMa-3G\n\nShop: https://stza.co/+vNMa-2t\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144532Z
LAST-MODIFIED:20180213T144532Z
TRANSP:OPAQUE
END:VEVENT
* Crawdads @ Tourists
<2018-08-17 Fri 18:05-21:05>
:PROPERTIES:
:ID:       oMWai79hSfMrm_JbjqKEP-_q@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Crawdads @ Tourists Crawdads @ Tourists

Follow on MiLB First Pitch  https //stza.co/+vNMb-1K

Shop  https //stza.co/+vNMb-2F

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Crawdads @ Tourists
END:VALARM
DTSTART:20180817T230500Z
DTEND:20180818T020500Z
UID:oMWai79hSfMrm_JbjqKEP-_q@stanza.co
SUMMARY:Crawdads @ Tourists
DESCRIPTION:Crawdads @ Tourists\n\nFollow on MiLB First Pitch: https://stza.co/+vNMb-1K\n\nShop: https://stza.co/+vNMb-2F\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144532Z
LAST-MODIFIED:20180213T144532Z
TRANSP:OPAQUE
END:VEVENT
* Crawdads @ Drive
<2018-08-18 Sat 18:05-21:05>
:PROPERTIES:
:ID:       W_Y3sy2E1kERm82k8L6RqmQJ@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Crawdads @ Drive Crawdads @ Drive

Follow on MiLB First Pitch  https //stza.co/+xF7x-3S

Shop  https //stza.co/+xF7x-3O

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Crawdads @ Drive
END:VALARM
DTSTART:20180818T230500Z
DTEND:20180819T020500Z
UID:W_Y3sy2E1kERm82k8L6RqmQJ@stanza.co
SUMMARY:Crawdads @ Drive
DESCRIPTION:Crawdads @ Drive\n\nFollow on MiLB First Pitch: https://stza.co/+xF7x-3S\n\nShop: https://stza.co/+xF7x-3O\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144532Z
LAST-MODIFIED:20180213T144532Z
TRANSP:OPAQUE
END:VEVENT
* Crawdads @ Drive
<2018-08-19 Sun 15:05-18:05>
:PROPERTIES:
:ID:       Oiq4ANMtCyOyOcCWPgfOVSAz@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Crawdads @ Drive Crawdads @ Drive

Follow on MiLB First Pitch  https //stza.co/+xF7y-2w

Shop  https //stza.co/+xF7y-2u

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Crawdads @ Drive
END:VALARM
DTSTART:20180819T200500Z
DTEND:20180819T230500Z
UID:Oiq4ANMtCyOyOcCWPgfOVSAz@stanza.co
SUMMARY:Crawdads @ Drive
DESCRIPTION:Crawdads @ Drive\n\nFollow on MiLB First Pitch: https://stza.co/+xF7y-2w\n\nShop: https://stza.co/+xF7y-2u\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144532Z
LAST-MODIFIED:20180213T144532Z
TRANSP:OPAQUE
END:VEVENT
* Crawdads @ Drive
<2018-08-20 Mon 18:05-21:05>
:PROPERTIES:
:ID:       b3Aj0d6TB4THg2gRUKUgh8tL@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Crawdads @ Drive Crawdads @ Drive

Follow on MiLB First Pitch  https //stza.co/+xF7z-1q

Shop  https //stza.co/+xF7z-1u

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Crawdads @ Drive
END:VALARM
DTSTART:20180820T230500Z
DTEND:20180821T020500Z
UID:b3Aj0d6TB4THg2gRUKUgh8tL@stanza.co
SUMMARY:Crawdads @ Drive
DESCRIPTION:Crawdads @ Drive\n\nFollow on MiLB First Pitch: https://stza.co/+xF7z-1q\n\nShop: https://stza.co/+xF7z-1u\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144532Z
LAST-MODIFIED:20180213T144532Z
TRANSP:OPAQUE
END:VEVENT
* Crawdads @ Drive
<2018-08-21 Tue 18:05-21:05>
:PROPERTIES:
:ID:       aDYZyo-8C3vsd5YXp8RkRm-K@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Crawdads @ Drive Crawdads @ Drive

Follow on MiLB First Pitch  https //stza.co/+xF7A-1M

Shop  https //stza.co/+xF7A-v

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Crawdads @ Drive
END:VALARM
DTSTART:20180821T230500Z
DTEND:20180822T020500Z
UID:aDYZyo-8C3vsd5YXp8RkRm-K@stanza.co
SUMMARY:Crawdads @ Drive
DESCRIPTION:Crawdads @ Drive\n\nFollow on MiLB First Pitch: https://stza.co/+xF7A-1M\n\nShop: https://stza.co/+xF7A-v\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144532Z
LAST-MODIFIED:20180213T144532Z
TRANSP:OPAQUE
END:VEVENT
* Crawdads vs. BlueClaws
<2018-08-23 Thu 18:00-21:00>
:PROPERTIES:
:ID:       VITb4glSkM5qL_C2_m0zU55X@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Crawdads vs. BlueClaws Crawdads vs. BlueClaws

Follow on MiLB First Pitch  https //stza.co/+w0Qx-1m

Shop  https //stza.co/+w0Qx-3J

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Crawdads vs. BlueClaws
END:VALARM
DTSTART:20180823T230000Z
DTEND:20180824T020000Z
UID:VITb4glSkM5qL_C2_m0zU55X@stanza.co
SUMMARY:Crawdads vs. BlueClaws
DESCRIPTION:Crawdads vs. BlueClaws\n\nFollow on MiLB First Pitch: https://stza.co/+w0Qx-1m\n\nShop: https://stza.co/+w0Qx-3J\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144532Z
LAST-MODIFIED:20180213T144532Z
TRANSP:OPAQUE
END:VEVENT
* Crawdads vs. BlueClaws
<2018-08-24 Fri 18:00-21:00>
:PROPERTIES:
:ID:       Aek1FE28Szz4oAMIpZUOwteE@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Crawdads vs. BlueClaws Crawdads vs. BlueClaws

Follow on MiLB First Pitch  https //stza.co/+w0Qy-12

Shop  https //stza.co/+w0Qy-1Z

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Crawdads vs. BlueClaws
END:VALARM
DTSTART:20180824T230000Z
DTEND:20180825T020000Z
UID:Aek1FE28Szz4oAMIpZUOwteE@stanza.co
SUMMARY:Crawdads vs. BlueClaws
DESCRIPTION:Crawdads vs. BlueClaws\n\nFollow on MiLB First Pitch: https://stza.co/+w0Qy-12\n\nShop: https://stza.co/+w0Qy-1Z\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144532Z
LAST-MODIFIED:20180213T144532Z
TRANSP:OPAQUE
END:VEVENT
* Crawdads vs. BlueClaws
<2018-08-25 Sat 18:00-21:00>
:PROPERTIES:
:ID:       GeqgCvjajdJ3iqMGt3i1j9zV@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Crawdads vs. BlueClaws Crawdads vs. BlueClaws

Follow on MiLB First Pitch  https //stza.co/+w0QB-2a

Shop  https //stza.co/+w0QB-1w

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Crawdads vs. BlueClaws
END:VALARM
DTSTART:20180825T230000Z
DTEND:20180826T020000Z
UID:GeqgCvjajdJ3iqMGt3i1j9zV@stanza.co
SUMMARY:Crawdads vs. BlueClaws
DESCRIPTION:Crawdads vs. BlueClaws\n\nFollow on MiLB First Pitch: https://stza.co/+w0QB-2a\n\nShop: https://stza.co/+w0QB-1w\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144532Z
LAST-MODIFIED:20180213T144532Z
TRANSP:OPAQUE
END:VEVENT
* Crawdads vs. BlueClaws
<2018-08-26 Sun 16:00-19:00>
:PROPERTIES:
:ID:       rsGxj9d1KRrVMaQdNjeOkm11@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Crawdads vs. BlueClaws Crawdads vs. BlueClaws

Follow on MiLB First Pitch  https //stza.co/+w0QD-1j

Shop  https //stza.co/+w0QD-1m

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Crawdads vs. BlueClaws
END:VALARM
DTSTART:20180826T210000Z
DTEND:20180827T000000Z
UID:rsGxj9d1KRrVMaQdNjeOkm11@stanza.co
SUMMARY:Crawdads vs. BlueClaws
DESCRIPTION:Crawdads vs. BlueClaws\n\nFollow on MiLB First Pitch: https://stza.co/+w0QD-1j\n\nShop: https://stza.co/+w0QD-1m\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144532Z
LAST-MODIFIED:20180213T144532Z
TRANSP:OPAQUE
END:VEVENT
* Crawdads @ Shorebirds
<2018-08-27 Mon 18:05-21:05>
:PROPERTIES:
:ID:       72L3VFbVizCTqmkX4JI_l1XM@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Crawdads @ Shorebirds Crawdads @ Shorebirds

Follow on MiLB First Pitch  https //stza.co/+wHSj-23

Shop  https //stza.co/+wHSj-2h

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Crawdads @ Shorebirds
END:VALARM
DTSTART:20180827T230500Z
DTEND:20180828T020500Z
UID:72L3VFbVizCTqmkX4JI_l1XM@stanza.co
SUMMARY:Crawdads @ Shorebirds
DESCRIPTION:Crawdads @ Shorebirds\n\nFollow on MiLB First Pitch: https://stza.co/+wHSj-23\n\nShop: https://stza.co/+wHSj-2h\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144532Z
LAST-MODIFIED:20180213T144532Z
TRANSP:OPAQUE
END:VEVENT
* Crawdads @ Shorebirds
<2018-08-28 Tue 18:05-21:05>
:PROPERTIES:
:ID:       v0Ed16n6E_K9fL6sbei-0z6a@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Crawdads @ Shorebirds Crawdads @ Shorebirds

Follow on MiLB First Pitch  https //stza.co/+wHSk-1Z

Shop  https //stza.co/+wHSk-3t

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Crawdads @ Shorebirds
END:VALARM
DTSTART:20180828T230500Z
DTEND:20180829T020500Z
UID:v0Ed16n6E_K9fL6sbei-0z6a@stanza.co
SUMMARY:Crawdads @ Shorebirds
DESCRIPTION:Crawdads @ Shorebirds\n\nFollow on MiLB First Pitch: https://stza.co/+wHSk-1Z\n\nShop: https://stza.co/+wHSk-3t\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144532Z
LAST-MODIFIED:20180213T144532Z
TRANSP:OPAQUE
END:VEVENT
* Crawdads @ Shorebirds
<2018-08-29 Wed 18:05-21:05>
:PROPERTIES:
:ID:       xxdMAALlMuNYcrEzuQL0im3u@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Crawdads @ Shorebirds Crawdads @ Shorebirds

Follow on MiLB First Pitch  https //stza.co/+wHSl-z

Shop  https //stza.co/+wHSl-3E

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Crawdads @ Shorebirds
END:VALARM
DTSTART:20180829T230500Z
DTEND:20180830T020500Z
UID:xxdMAALlMuNYcrEzuQL0im3u@stanza.co
SUMMARY:Crawdads @ Shorebirds
DESCRIPTION:Crawdads @ Shorebirds\n\nFollow on MiLB First Pitch: https://stza.co/+wHSl-z\n\nShop: https://stza.co/+wHSl-3E\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144532Z
LAST-MODIFIED:20180213T144532Z
TRANSP:OPAQUE
END:VEVENT
* Crawdads @ Shorebirds
<2018-08-30 Thu 18:05-21:05>
:PROPERTIES:
:ID:       GGEIMl_5r0LyYz9h1frpAbQR@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Crawdads @ Shorebirds Crawdads @ Shorebirds

Follow on MiLB First Pitch  https //stza.co/+wHQa-19

Shop  https //stza.co/+wHQa-1H

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Crawdads @ Shorebirds
END:VALARM
DTSTART:20180830T230500Z
DTEND:20180831T020500Z
UID:GGEIMl_5r0LyYz9h1frpAbQR@stanza.co
SUMMARY:Crawdads @ Shorebirds
DESCRIPTION:Crawdads @ Shorebirds\n\nFollow on MiLB First Pitch: https://stza.co/+wHQa-19\n\nShop: https://stza.co/+wHQa-1H\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144532Z
LAST-MODIFIED:20180213T144532Z
TRANSP:OPAQUE
END:VEVENT
* Crawdads vs. Grasshoppers
<2018-08-31 Fri 18:00-21:00>
:PROPERTIES:
:ID:       ZfvcrPBE4lU_vMJuAGGhMsph@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Crawdads vs. Grasshoppers Crawdads vs. Grasshoppers

Follow on MiLB First Pitch  https //stza.co/+w0QE-26

Shop  https //stza.co/+w0QE-2p

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Crawdads vs. Grasshoppers
END:VALARM
DTSTART:20180831T230000Z
DTEND:20180901T020000Z
UID:ZfvcrPBE4lU_vMJuAGGhMsph@stanza.co
SUMMARY:Crawdads vs. Grasshoppers
DESCRIPTION:Crawdads vs. Grasshoppers\n\nFollow on MiLB First Pitch: https://stza.co/+w0QE-26\n\nShop: https://stza.co/+w0QE-2p\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144532Z
LAST-MODIFIED:20180213T144532Z
TRANSP:OPAQUE
END:VEVENT
* Crawdads vs. Grasshoppers
<2018-09-01 Sat 18:00-21:00>
:PROPERTIES:
:ID:       Zttbwxxr4BZtjNnjiqSeozmz@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Crawdads vs. Grasshoppers Crawdads vs. Grasshoppers

Follow on MiLB First Pitch  https //stza.co/+w0QH-2w

Shop  https //stza.co/+w0QH-2C

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Crawdads vs. Grasshoppers
END:VALARM
DTSTART:20180901T230000Z
DTEND:20180902T020000Z
UID:Zttbwxxr4BZtjNnjiqSeozmz@stanza.co
SUMMARY:Crawdads vs. Grasshoppers
DESCRIPTION:Crawdads vs. Grasshoppers\n\nFollow on MiLB First Pitch: https://stza.co/+w0QH-2w\n\nShop: https://stza.co/+w0QH-2C\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144532Z
LAST-MODIFIED:20180213T144532Z
TRANSP:OPAQUE
END:VEVENT
* Crawdads vs. Grasshoppers
<2018-09-02 Sun 16:00-19:00>
:PROPERTIES:
:ID:       Fa6CCJRp0pIapi2ievIYSgUW@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Crawdads vs. Grasshoppers Crawdads vs. Grasshoppers

Follow on MiLB First Pitch  https //stza.co/+w0QI-15

Shop  https //stza.co/+w0QI-E

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Crawdads vs. Grasshoppers
END:VALARM
DTSTART:20180902T210000Z
DTEND:20180903T000000Z
UID:Fa6CCJRp0pIapi2ievIYSgUW@stanza.co
SUMMARY:Crawdads vs. Grasshoppers
DESCRIPTION:Crawdads vs. Grasshoppers\n\nFollow on MiLB First Pitch: https://stza.co/+w0QI-15\n\nShop: https://stza.co/+w0QI-E\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144532Z
LAST-MODIFIED:20180213T144532Z
TRANSP:OPAQUE
END:VEVENT
* Crawdads vs. Grasshoppers
<2018-09-03 Mon 12:00-15:00>
:PROPERTIES:
:ID:       ou6xSdv-jFKMLhk6Y0JXxM6G@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Crawdads vs. Grasshoppers Crawdads vs. Grasshoppers

Follow on MiLB First Pitch  https //stza.co/+w0QL-3T

Shop  https //stza.co/+w0QL-1V

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Crawdads vs. Grasshoppers
END:VALARM
DTSTART:20180903T170000Z
DTEND:20180903T200000Z
UID:ou6xSdv-jFKMLhk6Y0JXxM6G@stanza.co
SUMMARY:Crawdads vs. Grasshoppers
DESCRIPTION:Crawdads vs. Grasshoppers\n\nFollow on MiLB First Pitch: https://stza.co/+w0QL-3T\n\nShop: https://stza.co/+w0QL-1V\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144532Z
LAST-MODIFIED:20180213T144532Z
TRANSP:OPAQUE
END:VEVENT
