#+TITLE:       Main Google calendar entries
#+AUTHOR:      Eric S Fraga
#+EMAIL:       e.fraga@ucl.ac.uk
#+DESCRIPTION: converted using the ical2org awk script
#+CATEGORY:    google
#+STARTUP:     hidestars
#+STARTUP:     overview

* COMMENT original iCal preamble

* Sounds @ Baby Cakes
<2018-04-05 Thu 19:00-22:00>
:PROPERTIES:
:ID:       JgTUpkGu8Nyl5nyw9TChhtNd@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Sounds @ Baby Cakes Sounds @ Baby Cakes

Follow on MiLB First Pitch  https //stza.co/+whIs-1w

Shop  https //stza.co/+whIs-2y

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Sounds @ Baby Cakes
END:VALARM
DTSTART:20180406T000000Z
DTEND:20180406T030000Z
UID:JgTUpkGu8Nyl5nyw9TChhtNd@stanza.co
SUMMARY:Sounds @ Baby Cakes
DESCRIPTION:Sounds @ Baby Cakes\n\nFollow on MiLB First Pitch: https://stza.co/+whIs-1w\n\nShop: https://stza.co/+whIs-2y\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Sounds @ Baby Cakes
<2018-04-06 Fri 19:00-22:00>
:PROPERTIES:
:ID:       tdVBBe_XBAHNkTV53NeIDZMg@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Sounds @ Baby Cakes Sounds @ Baby Cakes

Follow on MiLB First Pitch  https //stza.co/+whIt-1r

Shop  https //stza.co/+whIt-3Y

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Sounds @ Baby Cakes
END:VALARM
DTSTART:20180407T000000Z
DTEND:20180407T030000Z
UID:tdVBBe_XBAHNkTV53NeIDZMg@stanza.co
SUMMARY:Sounds @ Baby Cakes
DESCRIPTION:Sounds @ Baby Cakes\n\nFollow on MiLB First Pitch: https://stza.co/+whIt-1r\n\nShop: https://stza.co/+whIt-3Y\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Sounds @ Baby Cakes
<2018-04-07 Sat 18:00-21:00>
:PROPERTIES:
:ID:       OvtvfDAbMb7yXwtS0-GM50Tb@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Sounds @ Baby Cakes Sounds @ Baby Cakes

Follow on MiLB First Pitch  https //stza.co/+whIv-A

Shop  https //stza.co/+whIv-1L

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Sounds @ Baby Cakes
END:VALARM
DTSTART:20180407T230000Z
DTEND:20180408T020000Z
UID:OvtvfDAbMb7yXwtS0-GM50Tb@stanza.co
SUMMARY:Sounds @ Baby Cakes
DESCRIPTION:Sounds @ Baby Cakes\n\nFollow on MiLB First Pitch: https://stza.co/+whIv-A\n\nShop: https://stza.co/+whIv-1L\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Sounds @ Baby Cakes
<2018-04-08 Sun 13:00-16:00>
:PROPERTIES:
:ID:       vlqsKo2vVWM72tLM4OhS2qEk@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Sounds @ Baby Cakes Sounds @ Baby Cakes

Follow on MiLB First Pitch  https //stza.co/+whIw-2Y

Shop  https //stza.co/+whIw-3X

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Sounds @ Baby Cakes
END:VALARM
DTSTART:20180408T180000Z
DTEND:20180408T210000Z
UID:vlqsKo2vVWM72tLM4OhS2qEk@stanza.co
SUMMARY:Sounds @ Baby Cakes
DESCRIPTION:Sounds @ Baby Cakes\n\nFollow on MiLB First Pitch: https://stza.co/+whIw-2Y\n\nShop: https://stza.co/+whIw-3X\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Sounds @ Baby Cakes
<2018-04-09 Mon 12:00-15:00>
:PROPERTIES:
:ID:       OjuvX7uEHdr0-4Yz7zrpDubu@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Sounds @ Baby Cakes Sounds @ Baby Cakes

Follow on MiLB First Pitch  https //stza.co/+whIx-r

Shop  https //stza.co/+whIx-1_

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Sounds @ Baby Cakes
END:VALARM
DTSTART:20180409T170000Z
DTEND:20180409T200000Z
UID:OjuvX7uEHdr0-4Yz7zrpDubu@stanza.co
SUMMARY:Sounds @ Baby Cakes
DESCRIPTION:Sounds @ Baby Cakes\n\nFollow on MiLB First Pitch: https://stza.co/+whIx-r\n\nShop: https://stza.co/+whIx-1_\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Sounds vs. Cubs
<2018-04-10 Tue 18:35-21:35>
:PROPERTIES:
:ID:       I3LnYxuu_uSpN1RGNmklUM4M@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Sounds vs. Cubs Sounds vs. Cubs

Follow on MiLB First Pitch  https //stza.co/+whGa-2h

Shop  https //stza.co/+whGa-3F

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Sounds vs. Cubs
END:VALARM
DTSTART:20180410T233500Z
DTEND:20180411T023500Z
UID:I3LnYxuu_uSpN1RGNmklUM4M@stanza.co
SUMMARY:Sounds vs. Cubs
DESCRIPTION:Sounds vs. Cubs\n\nFollow on MiLB First Pitch: https://stza.co/+whGa-2h\n\nShop: https://stza.co/+whGa-3F\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Sounds vs. Cubs
<2018-04-11 Wed 18:35-21:35>
:PROPERTIES:
:ID:       9UIi2RFoZzbJLu17TVN7LxYu@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Sounds vs. Cubs Sounds vs. Cubs

Follow on MiLB First Pitch  https //stza.co/+whGb-J

Shop  https //stza.co/+whGb-q

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Sounds vs. Cubs
END:VALARM
DTSTART:20180411T233500Z
DTEND:20180412T023500Z
UID:9UIi2RFoZzbJLu17TVN7LxYu@stanza.co
SUMMARY:Sounds vs. Cubs
DESCRIPTION:Sounds vs. Cubs\n\nFollow on MiLB First Pitch: https://stza.co/+whGb-J\n\nShop: https://stza.co/+whGb-q\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Sounds vs. Cubs
<2018-04-12 Thu 18:35-21:35>
:PROPERTIES:
:ID:       slRzd9I0QZ8MgMxZSt_x3MnY@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Sounds vs. Cubs Sounds vs. Cubs

Follow on MiLB First Pitch  https //stza.co/+whGd-2j

Shop  https //stza.co/+whGd-3G

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Sounds vs. Cubs
END:VALARM
DTSTART:20180412T233500Z
DTEND:20180413T023500Z
UID:slRzd9I0QZ8MgMxZSt_x3MnY@stanza.co
SUMMARY:Sounds vs. Cubs
DESCRIPTION:Sounds vs. Cubs\n\nFollow on MiLB First Pitch: https://stza.co/+whGd-2j\n\nShop: https://stza.co/+whGd-3G\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Sounds vs. Storm Chasers
<2018-04-13 Fri 18:35-21:35>
:PROPERTIES:
:ID:       B1VAh3nBvpxHvQtnyY0j5fDL@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Sounds vs. Storm Chasers Sounds vs. Storm Chasers

Follow on MiLB First Pitch  https //stza.co/+whGg-3N

Shop  https //stza.co/+whGg-2g

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Sounds vs. Storm Chasers
END:VALARM
DTSTART:20180413T233500Z
DTEND:20180414T023500Z
UID:B1VAh3nBvpxHvQtnyY0j5fDL@stanza.co
SUMMARY:Sounds vs. Storm Chasers
DESCRIPTION:Sounds vs. Storm Chasers\n\nFollow on MiLB First Pitch: https://stza.co/+whGg-3N\n\nShop: https://stza.co/+whGg-2g\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Sounds vs. Storm Chasers
<2018-04-14 Sat 18:35-21:35>
:PROPERTIES:
:ID:       ElfYlo3uyCASnUaHpQ6ajVtG@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Sounds vs. Storm Chasers Sounds vs. Storm Chasers

Follow on MiLB First Pitch  https //stza.co/+whGi-1p

Shop  https //stza.co/+whGi-1N

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Sounds vs. Storm Chasers
END:VALARM
DTSTART:20180414T233500Z
DTEND:20180415T023500Z
UID:ElfYlo3uyCASnUaHpQ6ajVtG@stanza.co
SUMMARY:Sounds vs. Storm Chasers
DESCRIPTION:Sounds vs. Storm Chasers\n\nFollow on MiLB First Pitch: https://stza.co/+whGi-1p\n\nShop: https://stza.co/+whGi-1N\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Sounds vs. Storm Chasers
<2018-04-15 Sun 14:05-17:05>
:PROPERTIES:
:ID:       eG_cSaDUad1yk3tdlegpFu3p@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Sounds vs. Storm Chasers Sounds vs. Storm Chasers

Follow on MiLB First Pitch  https //stza.co/+whGk-2Q

Shop  https //stza.co/+whGk-3m

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Sounds vs. Storm Chasers
END:VALARM
DTSTART:20180415T190500Z
DTEND:20180415T220500Z
UID:eG_cSaDUad1yk3tdlegpFu3p@stanza.co
SUMMARY:Sounds vs. Storm Chasers
DESCRIPTION:Sounds vs. Storm Chasers\n\nFollow on MiLB First Pitch: https://stza.co/+whGk-2Q\n\nShop: https://stza.co/+whGk-3m\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Sounds vs. Storm Chasers
<2018-04-16 Mon 12:05-15:05>
:PROPERTIES:
:ID:       KOq-MoSm2zFuZfod1m0xGADg@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Sounds vs. Storm Chasers Sounds vs. Storm Chasers

Follow on MiLB First Pitch  https //stza.co/+whGn-3q

Shop  https //stza.co/+whGn-3k

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Sounds vs. Storm Chasers
END:VALARM
DTSTART:20180416T170500Z
DTEND:20180416T200500Z
UID:KOq-MoSm2zFuZfod1m0xGADg@stanza.co
SUMMARY:Sounds vs. Storm Chasers
DESCRIPTION:Sounds vs. Storm Chasers\n\nFollow on MiLB First Pitch: https://stza.co/+whGn-3q\n\nShop: https://stza.co/+whGn-3k\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Sounds @ Cubs
<2018-04-17 Tue 18:38-21:38>
:PROPERTIES:
:ID:       LqNEEHGvUvoUE8nPcBLY0Fn6@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Sounds @ Cubs Sounds @ Cubs

Follow on MiLB First Pitch  https //stza.co/+vKJ5-3D

Shop  https //stza.co/+vKJ5-2q

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Sounds @ Cubs
END:VALARM
DTSTART:20180417T233800Z
DTEND:20180418T023800Z
UID:LqNEEHGvUvoUE8nPcBLY0Fn6@stanza.co
SUMMARY:Sounds @ Cubs
DESCRIPTION:Sounds @ Cubs\n\nFollow on MiLB First Pitch: https://stza.co/+vKJ5-3D\n\nShop: https://stza.co/+vKJ5-2q\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Sounds @ Cubs
<2018-04-18 Wed 12:08-15:08>
:PROPERTIES:
:ID:       pOCQaZ9iAq0S6quqUQccWvn1@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Sounds @ Cubs Sounds @ Cubs

Follow on MiLB First Pitch  https //stza.co/+vKJ6-1p

Shop  https //stza.co/+vKJ6-20

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Sounds @ Cubs
END:VALARM
DTSTART:20180418T170800Z
DTEND:20180418T200800Z
UID:pOCQaZ9iAq0S6quqUQccWvn1@stanza.co
SUMMARY:Sounds @ Cubs
DESCRIPTION:Sounds @ Cubs\n\nFollow on MiLB First Pitch: https://stza.co/+vKJ6-1p\n\nShop: https://stza.co/+vKJ6-20\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Sounds @ Cubs
<2018-04-19 Thu 18:38-21:38>
:PROPERTIES:
:ID:       GXXKiv6ETzx7bCNm71-h1Sa_@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Sounds @ Cubs Sounds @ Cubs

Follow on MiLB First Pitch  https //stza.co/+vKJ7-2n

Shop  https //stza.co/+vKJ7-1h

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Sounds @ Cubs
END:VALARM
DTSTART:20180419T233800Z
DTEND:20180420T023800Z
UID:GXXKiv6ETzx7bCNm71-h1Sa_@stanza.co
SUMMARY:Sounds @ Cubs
DESCRIPTION:Sounds @ Cubs\n\nFollow on MiLB First Pitch: https://stza.co/+vKJ7-2n\n\nShop: https://stza.co/+vKJ7-1h\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Sounds @ Cubs
<2018-04-20 Fri 19:08-22:08>
:PROPERTIES:
:ID:       ssCOIAnDg1Z-gfQ_x-PbN8WK@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Sounds @ Cubs Sounds @ Cubs

Follow on MiLB First Pitch  https //stza.co/+vKJ8-1n

Shop  https //stza.co/+vKJ8-2h

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Sounds @ Cubs
END:VALARM
DTSTART:20180421T000800Z
DTEND:20180421T030800Z
UID:ssCOIAnDg1Z-gfQ_x-PbN8WK@stanza.co
SUMMARY:Sounds @ Cubs
DESCRIPTION:Sounds @ Cubs\n\nFollow on MiLB First Pitch: https://stza.co/+vKJ8-1n\n\nShop: https://stza.co/+vKJ8-2h\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Sounds @ Storm Chasers
<2018-04-21 Sat 19:05-22:05>
:PROPERTIES:
:ID:       aLSWig2gBo2yd3J_kYTOyUBo@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Sounds @ Storm Chasers Sounds @ Storm Chasers

Follow on MiLB First Pitch  https //stza.co/+whIC-2L

Shop  https //stza.co/+whIC-K

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Sounds @ Storm Chasers
END:VALARM
DTSTART:20180422T000500Z
DTEND:20180422T030500Z
UID:aLSWig2gBo2yd3J_kYTOyUBo@stanza.co
SUMMARY:Sounds @ Storm Chasers
DESCRIPTION:Sounds @ Storm Chasers\n\nFollow on MiLB First Pitch: https://stza.co/+whIC-2L\n\nShop: https://stza.co/+whIC-K\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Sounds @ Storm Chasers
<2018-04-22 Sun 14:05-17:05>
:PROPERTIES:
:ID:       _XcwohIhwjDyo5DNdlc96Uvy@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Sounds @ Storm Chasers Sounds @ Storm Chasers

Follow on MiLB First Pitch  https //stza.co/+whID-27

Shop  https //stza.co/+whID-2U

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Sounds @ Storm Chasers
END:VALARM
DTSTART:20180422T190500Z
DTEND:20180422T220500Z
UID:_XcwohIhwjDyo5DNdlc96Uvy@stanza.co
SUMMARY:Sounds @ Storm Chasers
DESCRIPTION:Sounds @ Storm Chasers\n\nFollow on MiLB First Pitch: https://stza.co/+whID-27\n\nShop: https://stza.co/+whID-2U\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Sounds @ Storm Chasers
<2018-04-23 Mon 11:05-14:05>
:PROPERTIES:
:ID:       si1_UV64QlOF3GiCAimQhmzf@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Sounds @ Storm Chasers Sounds @ Storm Chasers

Follow on MiLB First Pitch  https //stza.co/+whIE-2y

Shop  https //stza.co/+whIE-2X

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Sounds @ Storm Chasers
END:VALARM
DTSTART:20180423T160500Z
DTEND:20180423T190500Z
UID:si1_UV64QlOF3GiCAimQhmzf@stanza.co
SUMMARY:Sounds @ Storm Chasers
DESCRIPTION:Sounds @ Storm Chasers\n\nFollow on MiLB First Pitch: https://stza.co/+whIE-2y\n\nShop: https://stza.co/+whIE-2X\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Sounds vs. Baby Cakes
<2018-04-25 Wed 18:35-21:35>
:PROPERTIES:
:ID:       -1vBEcR8-xklLc3tEGISUa06@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Sounds vs. Baby Cakes Sounds vs. Baby Cakes

Follow on MiLB First Pitch  https //stza.co/+whGp-2X

Shop  https //stza.co/+whGp-1z

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Sounds vs. Baby Cakes
END:VALARM
DTSTART:20180425T233500Z
DTEND:20180426T023500Z
UID:-1vBEcR8-xklLc3tEGISUa06@stanza.co
SUMMARY:Sounds vs. Baby Cakes
DESCRIPTION:Sounds vs. Baby Cakes\n\nFollow on MiLB First Pitch: https://stza.co/+whGp-2X\n\nShop: https://stza.co/+whGp-1z\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Sounds vs. Baby Cakes
<2018-04-26 Thu 18:35-21:35>
:PROPERTIES:
:ID:       PmenMwE6xGLFMxSlFz2o7rZZ@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Sounds vs. Baby Cakes Sounds vs. Baby Cakes

Follow on MiLB First Pitch  https //stza.co/+whGs-2u

Shop  https //stza.co/+whGs-2j

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Sounds vs. Baby Cakes
END:VALARM
DTSTART:20180426T233500Z
DTEND:20180427T023500Z
UID:PmenMwE6xGLFMxSlFz2o7rZZ@stanza.co
SUMMARY:Sounds vs. Baby Cakes
DESCRIPTION:Sounds vs. Baby Cakes\n\nFollow on MiLB First Pitch: https://stza.co/+whGs-2u\n\nShop: https://stza.co/+whGs-2j\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Sounds vs. Baby Cakes
<2018-04-27 Fri 18:35-21:35>
:PROPERTIES:
:ID:       Ho4HQ-LYVCoJYrxpF9BKceud@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Sounds vs. Baby Cakes Sounds vs. Baby Cakes

Follow on MiLB First Pitch  https //stza.co/+whGu-I

Shop  https //stza.co/+whGu-E

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Sounds vs. Baby Cakes
END:VALARM
DTSTART:20180427T233500Z
DTEND:20180428T023500Z
UID:Ho4HQ-LYVCoJYrxpF9BKceud@stanza.co
SUMMARY:Sounds vs. Baby Cakes
DESCRIPTION:Sounds vs. Baby Cakes\n\nFollow on MiLB First Pitch: https://stza.co/+whGu-I\n\nShop: https://stza.co/+whGu-E\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Sounds vs. Baby Cakes
<2018-04-28 Sat 18:35-21:35>
:PROPERTIES:
:ID:       iNqKJvYq7oPDUpW7ng7OxOLT@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Sounds vs. Baby Cakes Sounds vs. Baby Cakes

Follow on MiLB First Pitch  https //stza.co/+whGx-29

Shop  https //stza.co/+whGx-2M

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Sounds vs. Baby Cakes
END:VALARM
DTSTART:20180428T233500Z
DTEND:20180429T023500Z
UID:iNqKJvYq7oPDUpW7ng7OxOLT@stanza.co
SUMMARY:Sounds vs. Baby Cakes
DESCRIPTION:Sounds vs. Baby Cakes\n\nFollow on MiLB First Pitch: https://stza.co/+whGx-29\n\nShop: https://stza.co/+whGx-2M\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Sounds vs. Baby Cakes
<2018-04-29 Sun 13:05-16:05>
:PROPERTIES:
:ID:       RATcgIt3DALkCu-L86tuKi-J@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Sounds vs. Baby Cakes Sounds vs. Baby Cakes

Follow on MiLB First Pitch  https //stza.co/+wCF9-3M

Shop  https //stza.co/+wCF9-e

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Sounds vs. Baby Cakes
END:VALARM
DTSTART:20180429T180500Z
DTEND:20180429T210500Z
UID:RATcgIt3DALkCu-L86tuKi-J@stanza.co
SUMMARY:Sounds vs. Baby Cakes
DESCRIPTION:Sounds vs. Baby Cakes\n\nFollow on MiLB First Pitch: https://stza.co/+wCF9-3M\n\nShop: https://stza.co/+wCF9-e\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Sounds @ Sky Sox
<2018-04-30 Mon 19:40-22:40>
:PROPERTIES:
:ID:       nRT5cILyDX5cY_aZmFIcyHMD@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Sounds @ Sky Sox Sounds @ Sky Sox

Follow on MiLB First Pitch  https //stza.co/+wmGT-2g

Shop  https //stza.co/+wmGT-Y

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Sounds @ Sky Sox
END:VALARM
DTSTART:20180501T004000Z
DTEND:20180501T034000Z
UID:nRT5cILyDX5cY_aZmFIcyHMD@stanza.co
SUMMARY:Sounds @ Sky Sox
DESCRIPTION:Sounds @ Sky Sox\n\nFollow on MiLB First Pitch: https://stza.co/+wmGT-2g\n\nShop: https://stza.co/+wmGT-Y\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Sounds @ Sky Sox
<2018-05-01 Tue 19:40-22:40>
:PROPERTIES:
:ID:       gryyxoFRwfloLwjvZ2CabsLe@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Sounds @ Sky Sox Sounds @ Sky Sox

Follow on MiLB First Pitch  https //stza.co/+wmGU-2w

Shop  https //stza.co/+wmGU-E

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Sounds @ Sky Sox
END:VALARM
DTSTART:20180502T004000Z
DTEND:20180502T034000Z
UID:gryyxoFRwfloLwjvZ2CabsLe@stanza.co
SUMMARY:Sounds @ Sky Sox
DESCRIPTION:Sounds @ Sky Sox\n\nFollow on MiLB First Pitch: https://stza.co/+wmGU-2w\n\nShop: https://stza.co/+wmGU-E\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Sounds @ Sky Sox
<2018-05-02 Wed 12:05-15:05>
:PROPERTIES:
:ID:       88gwYBRDnoK7r3NbATAdPddY@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Sounds @ Sky Sox Sounds @ Sky Sox

Follow on MiLB First Pitch  https //stza.co/+wmGV-1$

Shop  https //stza.co/+wmGV-G

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Sounds @ Sky Sox
END:VALARM
DTSTART:20180502T170500Z
DTEND:20180502T200500Z
UID:88gwYBRDnoK7r3NbATAdPddY@stanza.co
SUMMARY:Sounds @ Sky Sox
DESCRIPTION:Sounds @ Sky Sox\n\nFollow on MiLB First Pitch: https://stza.co/+wmGV-1$\n\nShop: https://stza.co/+wmGV-G\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Sounds @ Sky Sox
<2018-05-03 Thu 12:05-15:05>
:PROPERTIES:
:ID:       F0PSU6cNkgssVS9PJNQTpy82@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Sounds @ Sky Sox Sounds @ Sky Sox

Follow on MiLB First Pitch  https //stza.co/+wmGW-1b

Shop  https //stza.co/+wmGW-37

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Sounds @ Sky Sox
END:VALARM
DTSTART:20180503T170500Z
DTEND:20180503T200500Z
UID:F0PSU6cNkgssVS9PJNQTpy82@stanza.co
SUMMARY:Sounds @ Sky Sox
DESCRIPTION:Sounds @ Sky Sox\n\nFollow on MiLB First Pitch: https://stza.co/+wmGW-1b\n\nShop: https://stza.co/+wmGW-37\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Sounds vs. Redbirds
<2018-05-04 Fri 18:35-21:35>
:PROPERTIES:
:ID:       IOu5s-tt5Ec8feKhzRuNaWIq@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Sounds vs. Redbirds Sounds vs. Redbirds

Follow on MiLB First Pitch  https //stza.co/+whGB-3d

Shop  https //stza.co/+whGB-2V

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Sounds vs. Redbirds
END:VALARM
DTSTART:20180504T233500Z
DTEND:20180505T023500Z
UID:IOu5s-tt5Ec8feKhzRuNaWIq@stanza.co
SUMMARY:Sounds vs. Redbirds
DESCRIPTION:Sounds vs. Redbirds\n\nFollow on MiLB First Pitch: https://stza.co/+whGB-3d\n\nShop: https://stza.co/+whGB-2V\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Sounds vs. Redbirds
<2018-05-05 Sat 18:35-21:35>
:PROPERTIES:
:ID:       HV4V4Lw1oR2G2Q4CzzvONEaZ@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Sounds vs. Redbirds Sounds vs. Redbirds

Follow on MiLB First Pitch  https //stza.co/+whGD-B

Shop  https //stza.co/+whGD-T

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Sounds vs. Redbirds
END:VALARM
DTSTART:20180505T233500Z
DTEND:20180506T023500Z
UID:HV4V4Lw1oR2G2Q4CzzvONEaZ@stanza.co
SUMMARY:Sounds vs. Redbirds
DESCRIPTION:Sounds vs. Redbirds\n\nFollow on MiLB First Pitch: https://stza.co/+whGD-B\n\nShop: https://stza.co/+whGD-T\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Sounds vs. Redbirds
<2018-05-06 Sun 14:05-17:05>
:PROPERTIES:
:ID:       Mdr7ipfqNNlMXOI67Bro_FsB@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Sounds vs. Redbirds Sounds vs. Redbirds

Follow on MiLB First Pitch  https //stza.co/+whGF-1p

Shop  https //stza.co/+whGF-2X

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Sounds vs. Redbirds
END:VALARM
DTSTART:20180506T190500Z
DTEND:20180506T220500Z
UID:Mdr7ipfqNNlMXOI67Bro_FsB@stanza.co
SUMMARY:Sounds vs. Redbirds
DESCRIPTION:Sounds vs. Redbirds\n\nFollow on MiLB First Pitch: https://stza.co/+whGF-1p\n\nShop: https://stza.co/+whGF-2X\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Sounds vs. Redbirds
<2018-05-07 Mon 12:05-15:05>
:PROPERTIES:
:ID:       1vG1Ayjt9eC9DCaLTx_LVLKl@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Sounds vs. Redbirds Sounds vs. Redbirds

Follow on MiLB First Pitch  https //stza.co/+whGG-3V

Shop  https //stza.co/+whGG-K

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Sounds vs. Redbirds
END:VALARM
DTSTART:20180507T170500Z
DTEND:20180507T200500Z
UID:1vG1Ayjt9eC9DCaLTx_LVLKl@stanza.co
SUMMARY:Sounds vs. Redbirds
DESCRIPTION:Sounds vs. Redbirds\n\nFollow on MiLB First Pitch: https://stza.co/+whGG-3V\n\nShop: https://stza.co/+whGG-K\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Sounds vs. Sky Sox
<2018-05-08 Tue 18:35-21:35>
:PROPERTIES:
:ID:       V-isxc6UtBRBtdzLLyzGEbmr@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Sounds vs. Sky Sox Sounds vs. Sky Sox

Follow on MiLB First Pitch  https //stza.co/+whGJ-1F

Shop  https //stza.co/+whGJ-Z

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Sounds vs. Sky Sox
END:VALARM
DTSTART:20180508T233500Z
DTEND:20180509T023500Z
UID:V-isxc6UtBRBtdzLLyzGEbmr@stanza.co
SUMMARY:Sounds vs. Sky Sox
DESCRIPTION:Sounds vs. Sky Sox\n\nFollow on MiLB First Pitch: https://stza.co/+whGJ-1F\n\nShop: https://stza.co/+whGJ-Z\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Sounds vs. Sky Sox
<2018-05-09 Wed 18:35-21:35>
:PROPERTIES:
:ID:       mP2VVmwRUlIDb_B2gTrzUNTL@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Sounds vs. Sky Sox Sounds vs. Sky Sox

Follow on MiLB First Pitch  https //stza.co/+whGL-27

Shop  https //stza.co/+whGL-3M

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Sounds vs. Sky Sox
END:VALARM
DTSTART:20180509T233500Z
DTEND:20180510T023500Z
UID:mP2VVmwRUlIDb_B2gTrzUNTL@stanza.co
SUMMARY:Sounds vs. Sky Sox
DESCRIPTION:Sounds vs. Sky Sox\n\nFollow on MiLB First Pitch: https://stza.co/+whGL-27\n\nShop: https://stza.co/+whGL-3M\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Sounds vs. Sky Sox
<2018-05-10 Thu 18:35-21:35>
:PROPERTIES:
:ID:       uTSaAIxJs6O-PhTF4TzWyS0O@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Sounds vs. Sky Sox Sounds vs. Sky Sox

Follow on MiLB First Pitch  https //stza.co/+whGO-r

Shop  https //stza.co/+whGO-20

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Sounds vs. Sky Sox
END:VALARM
DTSTART:20180510T233500Z
DTEND:20180511T023500Z
UID:uTSaAIxJs6O-PhTF4TzWyS0O@stanza.co
SUMMARY:Sounds vs. Sky Sox
DESCRIPTION:Sounds vs. Sky Sox\n\nFollow on MiLB First Pitch: https://stza.co/+whGO-r\n\nShop: https://stza.co/+whGO-20\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Sounds vs. Sky Sox
<2018-05-11 Fri 18:35-21:35>
:PROPERTIES:
:ID:       j_FHYZIYhwUylk58kfo-zAh1@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Sounds vs. Sky Sox Sounds vs. Sky Sox

Follow on MiLB First Pitch  https //stza.co/+whGP-3k

Shop  https //stza.co/+whGP-24

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Sounds vs. Sky Sox
END:VALARM
DTSTART:20180511T233500Z
DTEND:20180512T023500Z
UID:j_FHYZIYhwUylk58kfo-zAh1@stanza.co
SUMMARY:Sounds vs. Sky Sox
DESCRIPTION:Sounds vs. Sky Sox\n\nFollow on MiLB First Pitch: https://stza.co/+whGP-3k\n\nShop: https://stza.co/+whGP-24\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Sounds @ Redbirds
<2018-05-12 Sat 18:35-21:35>
:PROPERTIES:
:ID:       IN8ar8dXYg7cPJmV0RAeHZb8@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Sounds @ Redbirds Sounds @ Redbirds

Follow on MiLB First Pitch  https //stza.co/+wmH2-23

Shop  https //stza.co/+wmH2-3I

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Sounds @ Redbirds
END:VALARM
DTSTART:20180512T233500Z
DTEND:20180513T023500Z
UID:IN8ar8dXYg7cPJmV0RAeHZb8@stanza.co
SUMMARY:Sounds @ Redbirds
DESCRIPTION:Sounds @ Redbirds\n\nFollow on MiLB First Pitch: https://stza.co/+wmH2-23\n\nShop: https://stza.co/+wmH2-3I\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Sounds @ Redbirds
<2018-05-13 Sun 14:05-17:05>
:PROPERTIES:
:ID:       9dUmChjJ42pdort2LcT0L7cd@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Sounds @ Redbirds Sounds @ Redbirds

Follow on MiLB First Pitch  https //stza.co/+wmH3-37

Shop  https //stza.co/+wmH3-3M

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Sounds @ Redbirds
END:VALARM
DTSTART:20180513T190500Z
DTEND:20180513T220500Z
UID:9dUmChjJ42pdort2LcT0L7cd@stanza.co
SUMMARY:Sounds @ Redbirds
DESCRIPTION:Sounds @ Redbirds\n\nFollow on MiLB First Pitch: https://stza.co/+wmH3-37\n\nShop: https://stza.co/+wmH3-3M\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Sounds @ Redbirds
<2018-05-14 Mon 11:05-14:05>
:PROPERTIES:
:ID:       bFZrcp5OleyOmUfeDa9LTYei@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Sounds @ Redbirds Sounds @ Redbirds

Follow on MiLB First Pitch  https //stza.co/+wmH4-1b

Shop  https //stza.co/+wmH4-22

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Sounds @ Redbirds
END:VALARM
DTSTART:20180514T160500Z
DTEND:20180514T190500Z
UID:bFZrcp5OleyOmUfeDa9LTYei@stanza.co
SUMMARY:Sounds @ Redbirds
DESCRIPTION:Sounds @ Redbirds\n\nFollow on MiLB First Pitch: https://stza.co/+wmH4-1b\n\nShop: https://stza.co/+wmH4-22\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Sounds @ Redbirds
<2018-05-15 Tue 11:05-14:05>
:PROPERTIES:
:ID:       8r5dAgim3bNxHO0t-fRtK_J4@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Sounds @ Redbirds Sounds @ Redbirds

Follow on MiLB First Pitch  https //stza.co/+wmH5-2l

Shop  https //stza.co/+wmH5-8

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Sounds @ Redbirds
END:VALARM
DTSTART:20180515T160500Z
DTEND:20180515T190500Z
UID:8r5dAgim3bNxHO0t-fRtK_J4@stanza.co
SUMMARY:Sounds @ Redbirds
DESCRIPTION:Sounds @ Redbirds\n\nFollow on MiLB First Pitch: https://stza.co/+wmH5-2l\n\nShop: https://stza.co/+wmH5-8\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Sounds @ Dodgers
<2018-05-17 Thu 19:05-22:05>
:PROPERTIES:
:ID:       L0CRfTfkpXkdyIaciC4hUAdC@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Sounds @ Dodgers Sounds @ Dodgers

Follow on MiLB First Pitch  https //stza.co/+v$MB-31

Shop  https //stza.co/+v$MB-

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Sounds @ Dodgers
END:VALARM
DTSTART:20180518T000500Z
DTEND:20180518T030500Z
UID:L0CRfTfkpXkdyIaciC4hUAdC@stanza.co
SUMMARY:Sounds @ Dodgers
DESCRIPTION:Sounds @ Dodgers\n\nFollow on MiLB First Pitch: https://stza.co/+v$MB-31\n\nShop: https://stza.co/+v$MB-\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Sounds @ Dodgers
<2018-05-18 Fri 19:05-22:05>
:PROPERTIES:
:ID:       DJvI0-IGq-6d1yHcCHT0G7lw@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Sounds @ Dodgers Sounds @ Dodgers

Follow on MiLB First Pitch  https //stza.co/+v$MC-C

Shop  https //stza.co/+v$MC-l

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Sounds @ Dodgers
END:VALARM
DTSTART:20180519T000500Z
DTEND:20180519T030500Z
UID:DJvI0-IGq-6d1yHcCHT0G7lw@stanza.co
SUMMARY:Sounds @ Dodgers
DESCRIPTION:Sounds @ Dodgers\n\nFollow on MiLB First Pitch: https://stza.co/+v$MC-C\n\nShop: https://stza.co/+v$MC-l\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Sounds @ Dodgers
<2018-05-19 Sat 19:05-22:05>
:PROPERTIES:
:ID:       CufjXLBBd_TxVlt384SYFn9E@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Sounds @ Dodgers Sounds @ Dodgers

Follow on MiLB First Pitch  https //stza.co/+v$MD-3r

Shop  https //stza.co/+v$MD-L

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Sounds @ Dodgers
END:VALARM
DTSTART:20180520T000500Z
DTEND:20180520T030500Z
UID:CufjXLBBd_TxVlt384SYFn9E@stanza.co
SUMMARY:Sounds @ Dodgers
DESCRIPTION:Sounds @ Dodgers\n\nFollow on MiLB First Pitch: https://stza.co/+v$MD-3r\n\nShop: https://stza.co/+v$MD-L\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Sounds @ Dodgers
<2018-05-20 Sun 14:05-17:05>
:PROPERTIES:
:ID:       ezyZ-pEQ0MfX9GKz_u5xtDGG@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Sounds @ Dodgers Sounds @ Dodgers

Follow on MiLB First Pitch  https //stza.co/+v$ME-2u

Shop  https //stza.co/+v$ME-32

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Sounds @ Dodgers
END:VALARM
DTSTART:20180520T190500Z
DTEND:20180520T220500Z
UID:ezyZ-pEQ0MfX9GKz_u5xtDGG@stanza.co
SUMMARY:Sounds @ Dodgers
DESCRIPTION:Sounds @ Dodgers\n\nFollow on MiLB First Pitch: https://stza.co/+v$ME-2u\n\nShop: https://stza.co/+v$ME-32\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Sounds vs. Sky Sox
<2018-05-21 Mon 18:35-21:35>
:PROPERTIES:
:ID:       HEAbjnQv_5iP_mVjmpclaLnd@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Sounds vs. Sky Sox Sounds vs. Sky Sox

Follow on MiLB First Pitch  https //stza.co/+whGR-2$

Shop  https //stza.co/+whGR-27

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Sounds vs. Sky Sox
END:VALARM
DTSTART:20180521T233500Z
DTEND:20180522T023500Z
UID:HEAbjnQv_5iP_mVjmpclaLnd@stanza.co
SUMMARY:Sounds vs. Sky Sox
DESCRIPTION:Sounds vs. Sky Sox\n\nFollow on MiLB First Pitch: https://stza.co/+whGR-2$\n\nShop: https://stza.co/+whGR-27\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Sounds vs. Sky Sox
<2018-05-22 Tue 18:35-21:35>
:PROPERTIES:
:ID:       qtHVjXBz_piefWT_N2cQw2gq@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Sounds vs. Sky Sox Sounds vs. Sky Sox

Follow on MiLB First Pitch  https //stza.co/+whGU-33

Shop  https //stza.co/+whGU-3G

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Sounds vs. Sky Sox
END:VALARM
DTSTART:20180522T233500Z
DTEND:20180523T023500Z
UID:qtHVjXBz_piefWT_N2cQw2gq@stanza.co
SUMMARY:Sounds vs. Sky Sox
DESCRIPTION:Sounds vs. Sky Sox\n\nFollow on MiLB First Pitch: https://stza.co/+whGU-33\n\nShop: https://stza.co/+whGU-3G\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Sounds vs. Sky Sox
<2018-05-23 Wed 18:35-21:35>
:PROPERTIES:
:ID:       f5e8cBmaB5v56k5lsFGVyXna@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Sounds vs. Sky Sox Sounds vs. Sky Sox

Follow on MiLB First Pitch  https //stza.co/+whGW-3C

Shop  https //stza.co/+whGW-1I

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Sounds vs. Sky Sox
END:VALARM
DTSTART:20180523T233500Z
DTEND:20180524T023500Z
UID:f5e8cBmaB5v56k5lsFGVyXna@stanza.co
SUMMARY:Sounds vs. Sky Sox
DESCRIPTION:Sounds vs. Sky Sox\n\nFollow on MiLB First Pitch: https://stza.co/+whGW-3C\n\nShop: https://stza.co/+whGW-1I\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Sounds vs. Sky Sox
<2018-05-24 Thu 18:35-21:35>
:PROPERTIES:
:ID:       ZbPzowxrG34buX8IH4MA8L7X@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Sounds vs. Sky Sox Sounds vs. Sky Sox

Follow on MiLB First Pitch  https //stza.co/+whGY-2M

Shop  https //stza.co/+whGY-1N

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Sounds vs. Sky Sox
END:VALARM
DTSTART:20180524T233500Z
DTEND:20180525T023500Z
UID:ZbPzowxrG34buX8IH4MA8L7X@stanza.co
SUMMARY:Sounds vs. Sky Sox
DESCRIPTION:Sounds vs. Sky Sox\n\nFollow on MiLB First Pitch: https://stza.co/+whGY-2M\n\nShop: https://stza.co/+whGY-1N\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Sounds vs. Dodgers
<2018-05-25 Fri 18:35-21:35>
:PROPERTIES:
:ID:       4LAb_hRtDUk9ZTabUtCdCyli@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Sounds vs. Dodgers Sounds vs. Dodgers

Follow on MiLB First Pitch  https //stza.co/+whG_-7

Shop  https //stza.co/+whG_-13

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Sounds vs. Dodgers
END:VALARM
DTSTART:20180525T233500Z
DTEND:20180526T023500Z
UID:4LAb_hRtDUk9ZTabUtCdCyli@stanza.co
SUMMARY:Sounds vs. Dodgers
DESCRIPTION:Sounds vs. Dodgers\n\nFollow on MiLB First Pitch: https://stza.co/+whG_-7\n\nShop: https://stza.co/+whG_-13\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Sounds vs. Dodgers
<2018-05-26 Sat 18:35-21:35>
:PROPERTIES:
:ID:       meYnFVti5761IYALkRs06YU4@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Sounds vs. Dodgers Sounds vs. Dodgers

Follow on MiLB First Pitch  https //stza.co/+whH0-1p

Shop  https //stza.co/+whH0-2A

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Sounds vs. Dodgers
END:VALARM
DTSTART:20180526T233500Z
DTEND:20180527T023500Z
UID:meYnFVti5761IYALkRs06YU4@stanza.co
SUMMARY:Sounds vs. Dodgers
DESCRIPTION:Sounds vs. Dodgers\n\nFollow on MiLB First Pitch: https://stza.co/+whH0-1p\n\nShop: https://stza.co/+whH0-2A\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Sounds vs. Dodgers
<2018-05-27 Sun 18:35-21:35>
:PROPERTIES:
:ID:       mWDbj6p-dYi8gUVM6EZ1kfqt@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Sounds vs. Dodgers Sounds vs. Dodgers

Follow on MiLB First Pitch  https //stza.co/+whH1-30

Shop  https //stza.co/+whH1-1y

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Sounds vs. Dodgers
END:VALARM
DTSTART:20180527T233500Z
DTEND:20180528T023500Z
UID:mWDbj6p-dYi8gUVM6EZ1kfqt@stanza.co
SUMMARY:Sounds vs. Dodgers
DESCRIPTION:Sounds vs. Dodgers\n\nFollow on MiLB First Pitch: https://stza.co/+whH1-30\n\nShop: https://stza.co/+whH1-1y\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Sounds vs. Dodgers
<2018-05-28 Mon 12:05-15:05>
:PROPERTIES:
:ID:       Fwk-YUwSGUluUDYrE-SCW6-Y@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Sounds vs. Dodgers Sounds vs. Dodgers

Follow on MiLB First Pitch  https //stza.co/+whH4-1P

Shop  https //stza.co/+whH4-2V

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Sounds vs. Dodgers
END:VALARM
DTSTART:20180528T170500Z
DTEND:20180528T200500Z
UID:Fwk-YUwSGUluUDYrE-SCW6-Y@stanza.co
SUMMARY:Sounds vs. Dodgers
DESCRIPTION:Sounds vs. Dodgers\n\nFollow on MiLB First Pitch: https://stza.co/+whH4-1P\n\nShop: https://stza.co/+whH4-2V\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Sounds vs. Dodgers
<2018-05-29 Tue 18:35-21:35>
:PROPERTIES:
:ID:       yWkWfst6W-hhCYo2WLI_VIWy@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Sounds vs. Dodgers Sounds vs. Dodgers

Follow on MiLB First Pitch  https //stza.co/+whH6-18

Shop  https //stza.co/+whH6-1G

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Sounds vs. Dodgers
END:VALARM
DTSTART:20180529T233500Z
DTEND:20180530T023500Z
UID:yWkWfst6W-hhCYo2WLI_VIWy@stanza.co
SUMMARY:Sounds vs. Dodgers
DESCRIPTION:Sounds vs. Dodgers\n\nFollow on MiLB First Pitch: https://stza.co/+whH6-18\n\nShop: https://stza.co/+whH6-1G\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Sounds @ Express
<2018-05-30 Wed 19:05-22:05>
:PROPERTIES:
:ID:       aY4XCJtDT7T74NRW3ASqTzVZ@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Sounds @ Express Sounds @ Express

Follow on MiLB First Pitch  https //stza.co/+v29L-1o

Shop  https //stza.co/+v29L-R

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Sounds @ Express
END:VALARM
DTSTART:20180531T000500Z
DTEND:20180531T030500Z
UID:aY4XCJtDT7T74NRW3ASqTzVZ@stanza.co
SUMMARY:Sounds @ Express
DESCRIPTION:Sounds @ Express\n\nFollow on MiLB First Pitch: https://stza.co/+v29L-1o\n\nShop: https://stza.co/+v29L-R\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Sounds @ Express
<2018-05-31 Thu 19:05-22:05>
:PROPERTIES:
:ID:       OPc6OCwLHhtKglglVQfRsmLP@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Sounds @ Express Sounds @ Express

Follow on MiLB First Pitch  https //stza.co/+v29X-1H

Shop  https //stza.co/+v29X-L

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Sounds @ Express
END:VALARM
DTSTART:20180601T000500Z
DTEND:20180601T030500Z
UID:OPc6OCwLHhtKglglVQfRsmLP@stanza.co
SUMMARY:Sounds @ Express
DESCRIPTION:Sounds @ Express\n\nFollow on MiLB First Pitch: https://stza.co/+v29X-1H\n\nShop: https://stza.co/+v29X-L\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Sounds @ Express
<2018-06-01 Fri 19:05-22:05>
:PROPERTIES:
:ID:       38TDSUK-dZzRYYA175hDYJSY@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Sounds @ Express Sounds @ Express

Follow on MiLB First Pitch  https //stza.co/+v2a3-3F

Shop  https //stza.co/+v2a3-32

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Sounds @ Express
END:VALARM
DTSTART:20180602T000500Z
DTEND:20180602T030500Z
UID:38TDSUK-dZzRYYA175hDYJSY@stanza.co
SUMMARY:Sounds @ Express
DESCRIPTION:Sounds @ Express\n\nFollow on MiLB First Pitch: https://stza.co/+v2a3-3F\n\nShop: https://stza.co/+v2a3-32\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Sounds @ Express
<2018-06-02 Sat 19:05-22:05>
:PROPERTIES:
:ID:       6hb9WrOYX1HVnWWo-Ym4CHFK@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Sounds @ Express Sounds @ Express

Follow on MiLB First Pitch  https //stza.co/+v2ae-1C

Shop  https //stza.co/+v2ae-2k

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Sounds @ Express
END:VALARM
DTSTART:20180603T000500Z
DTEND:20180603T030500Z
UID:6hb9WrOYX1HVnWWo-Ym4CHFK@stanza.co
SUMMARY:Sounds @ Express
DESCRIPTION:Sounds @ Express\n\nFollow on MiLB First Pitch: https://stza.co/+v2ae-1C\n\nShop: https://stza.co/+v2ae-2k\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Sounds @ Express
<2018-06-03 Sun 13:05-16:05>
:PROPERTIES:
:ID:       uYawKhb0GSn7OrhQw2hvwvPN@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Sounds @ Express Sounds @ Express

Follow on MiLB First Pitch  https //stza.co/+v2ao-T

Shop  https //stza.co/+v2ao-2R

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Sounds @ Express
END:VALARM
DTSTART:20180603T180500Z
DTEND:20180603T210500Z
UID:uYawKhb0GSn7OrhQw2hvwvPN@stanza.co
SUMMARY:Sounds @ Express
DESCRIPTION:Sounds @ Express\n\nFollow on MiLB First Pitch: https://stza.co/+v2ao-T\n\nShop: https://stza.co/+v2ao-2R\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Sounds vs. Aces
<2018-06-05 Tue 19:05-22:05>
:PROPERTIES:
:ID:       CVjwa4nquerapaxI7X8rdbB5@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Sounds vs. Aces Sounds vs. Aces

Follow on MiLB First Pitch  https //stza.co/+whH8-3O

Shop  https //stza.co/+whH8-3s

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Sounds vs. Aces
END:VALARM
DTSTART:20180606T000500Z
DTEND:20180606T030500Z
UID:CVjwa4nquerapaxI7X8rdbB5@stanza.co
SUMMARY:Sounds vs. Aces
DESCRIPTION:Sounds vs. Aces\n\nFollow on MiLB First Pitch: https://stza.co/+whH8-3O\n\nShop: https://stza.co/+whH8-3s\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Sounds vs. Aces
<2018-06-06 Wed 19:05-22:05>
:PROPERTIES:
:ID:       kPzkOkQESM53T3uHzWwdlbY2@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Sounds vs. Aces Sounds vs. Aces

Follow on MiLB First Pitch  https //stza.co/+whH9-2Z

Shop  https //stza.co/+whH9-17

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Sounds vs. Aces
END:VALARM
DTSTART:20180607T000500Z
DTEND:20180607T030500Z
UID:kPzkOkQESM53T3uHzWwdlbY2@stanza.co
SUMMARY:Sounds vs. Aces
DESCRIPTION:Sounds vs. Aces\n\nFollow on MiLB First Pitch: https://stza.co/+whH9-2Z\n\nShop: https://stza.co/+whH9-17\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Sounds vs. Aces
<2018-06-07 Thu 19:05-22:05>
:PROPERTIES:
:ID:       bSGXvg-yfV9NTeafn3jo3oa1@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Sounds vs. Aces Sounds vs. Aces

Follow on MiLB First Pitch  https //stza.co/+whHb-27

Shop  https //stza.co/+whHb-1_

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Sounds vs. Aces
END:VALARM
DTSTART:20180608T000500Z
DTEND:20180608T030500Z
UID:bSGXvg-yfV9NTeafn3jo3oa1@stanza.co
SUMMARY:Sounds vs. Aces
DESCRIPTION:Sounds vs. Aces\n\nFollow on MiLB First Pitch: https://stza.co/+whHb-27\n\nShop: https://stza.co/+whHb-1_\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Sounds vs. Rainiers
<2018-06-08 Fri 19:05-22:05>
:PROPERTIES:
:ID:       hSBIDIwk2iDPD-tumWyVAQgU@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Sounds vs. Rainiers Sounds vs. Rainiers

Follow on MiLB First Pitch  https //stza.co/+whHd-q

Shop  https //stza.co/+whHd-A

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Sounds vs. Rainiers
END:VALARM
DTSTART:20180609T000500Z
DTEND:20180609T030500Z
UID:hSBIDIwk2iDPD-tumWyVAQgU@stanza.co
SUMMARY:Sounds vs. Rainiers
DESCRIPTION:Sounds vs. Rainiers\n\nFollow on MiLB First Pitch: https://stza.co/+whHd-q\n\nShop: https://stza.co/+whHd-A\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Sounds vs. Rainiers
<2018-06-09 Sat 19:05-22:05>
:PROPERTIES:
:ID:       9TEdbAAc05OWkmWqjInK4cPN@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Sounds vs. Rainiers Sounds vs. Rainiers

Follow on MiLB First Pitch  https //stza.co/+whHg-4

Shop  https //stza.co/+whHg-10

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Sounds vs. Rainiers
END:VALARM
DTSTART:20180610T000500Z
DTEND:20180610T030500Z
UID:9TEdbAAc05OWkmWqjInK4cPN@stanza.co
SUMMARY:Sounds vs. Rainiers
DESCRIPTION:Sounds vs. Rainiers\n\nFollow on MiLB First Pitch: https://stza.co/+whHg-4\n\nShop: https://stza.co/+whHg-10\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Sounds vs. Rainiers
<2018-06-10 Sun 18:15-21:15>
:PROPERTIES:
:ID:       ahPv_GQr068kcgUNCTLhMEif@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Sounds vs. Rainiers Sounds vs. Rainiers

Follow on MiLB First Pitch  https //stza.co/+whHh-2P

Shop  https //stza.co/+whHh-2b

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Sounds vs. Rainiers
END:VALARM
DTSTART:20180610T231500Z
DTEND:20180611T021500Z
UID:ahPv_GQr068kcgUNCTLhMEif@stanza.co
SUMMARY:Sounds vs. Rainiers
DESCRIPTION:Sounds vs. Rainiers\n\nFollow on MiLB First Pitch: https://stza.co/+whHh-2P\n\nShop: https://stza.co/+whHh-2b\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Sounds vs. Rainiers
<2018-06-11 Mon 19:05-22:05>
:PROPERTIES:
:ID:       r8zWlmMepAG79YbPVhVLWY2j@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Sounds vs. Rainiers Sounds vs. Rainiers

Follow on MiLB First Pitch  https //stza.co/+whHk-g

Shop  https //stza.co/+whHk-3A

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Sounds vs. Rainiers
END:VALARM
DTSTART:20180612T000500Z
DTEND:20180612T030500Z
UID:r8zWlmMepAG79YbPVhVLWY2j@stanza.co
SUMMARY:Sounds vs. Rainiers
DESCRIPTION:Sounds vs. Rainiers\n\nFollow on MiLB First Pitch: https://stza.co/+whHk-g\n\nShop: https://stza.co/+whHk-3A\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Sounds @ Chihuahuas
<2018-06-13 Wed 20:05-23:05>
:PROPERTIES:
:ID:       FkIyn7wo5wmaA6EPo_eWtSdt@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Sounds @ Chihuahuas Sounds @ Chihuahuas

Follow on MiLB First Pitch  https //stza.co/+wmG$-39

Shop  https //stza.co/+wmG$-1_

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Sounds @ Chihuahuas
END:VALARM
DTSTART:20180614T010500Z
DTEND:20180614T040500Z
UID:FkIyn7wo5wmaA6EPo_eWtSdt@stanza.co
SUMMARY:Sounds @ Chihuahuas
DESCRIPTION:Sounds @ Chihuahuas\n\nFollow on MiLB First Pitch: https://stza.co/+wmG$-39\n\nShop: https://stza.co/+wmG$-1_\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Sounds @ Chihuahuas
<2018-06-14 Thu 20:05-23:05>
:PROPERTIES:
:ID:       LQPG56WD1kHd1qd7j1ahYd7S@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Sounds @ Chihuahuas Sounds @ Chihuahuas

Follow on MiLB First Pitch  https //stza.co/+wmH0-1j

Shop  https //stza.co/+wmH0-w

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Sounds @ Chihuahuas
END:VALARM
DTSTART:20180615T010500Z
DTEND:20180615T040500Z
UID:LQPG56WD1kHd1qd7j1ahYd7S@stanza.co
SUMMARY:Sounds @ Chihuahuas
DESCRIPTION:Sounds @ Chihuahuas\n\nFollow on MiLB First Pitch: https://stza.co/+wmH0-1j\n\nShop: https://stza.co/+wmH0-w\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Sounds @ Chihuahuas
<2018-06-15 Fri 20:05-23:05>
:PROPERTIES:
:ID:       tLp0nWnfFpaOIy8SE5VSjfoC@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Sounds @ Chihuahuas Sounds @ Chihuahuas

Follow on MiLB First Pitch  https //stza.co/+wmH1-2l

Shop  https //stza.co/+wmH1-2c

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Sounds @ Chihuahuas
END:VALARM
DTSTART:20180616T010500Z
DTEND:20180616T040500Z
UID:tLp0nWnfFpaOIy8SE5VSjfoC@stanza.co
SUMMARY:Sounds @ Chihuahuas
DESCRIPTION:Sounds @ Chihuahuas\n\nFollow on MiLB First Pitch: https://stza.co/+wmH1-2l\n\nShop: https://stza.co/+wmH1-2c\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Sounds @ Isotopes
<2018-06-16 Sat 19:35-22:35>
:PROPERTIES:
:ID:       otprQaRK1Qbm5D1kq0FLPfj6@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Sounds @ Isotopes Sounds @ Isotopes

Follow on MiLB First Pitch  https //stza.co/+whG4-3_

Shop  https //stza.co/+whG4-38

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Sounds @ Isotopes
END:VALARM
DTSTART:20180617T003500Z
DTEND:20180617T033500Z
UID:otprQaRK1Qbm5D1kq0FLPfj6@stanza.co
SUMMARY:Sounds @ Isotopes
DESCRIPTION:Sounds @ Isotopes\n\nFollow on MiLB First Pitch: https://stza.co/+whG4-3_\n\nShop: https://stza.co/+whG4-38\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Sounds @ Isotopes
<2018-06-17 Sun 19:05-22:05>
:PROPERTIES:
:ID:       Qfzh2J1nYUN52YY2mF8kFih_@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Sounds @ Isotopes Sounds @ Isotopes

Follow on MiLB First Pitch  https //stza.co/+whG5-U

Shop  https //stza.co/+whG5-1v

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Sounds @ Isotopes
END:VALARM
DTSTART:20180618T000500Z
DTEND:20180618T030500Z
UID:Qfzh2J1nYUN52YY2mF8kFih_@stanza.co
SUMMARY:Sounds @ Isotopes
DESCRIPTION:Sounds @ Isotopes\n\nFollow on MiLB First Pitch: https://stza.co/+whG5-U\n\nShop: https://stza.co/+whG5-1v\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Sounds @ Isotopes
<2018-06-18 Mon 19:35-22:35>
:PROPERTIES:
:ID:       JBsyuk9Ehc6qadAo6EOgAtPJ@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Sounds @ Isotopes Sounds @ Isotopes

Follow on MiLB First Pitch  https //stza.co/+whG7-21

Shop  https //stza.co/+whG7-3k

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Sounds @ Isotopes
END:VALARM
DTSTART:20180619T003500Z
DTEND:20180619T033500Z
UID:JBsyuk9Ehc6qadAo6EOgAtPJ@stanza.co
SUMMARY:Sounds @ Isotopes
DESCRIPTION:Sounds @ Isotopes\n\nFollow on MiLB First Pitch: https://stza.co/+whG7-21\n\nShop: https://stza.co/+whG7-3k\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Sounds @ Isotopes
<2018-06-19 Tue 13:05-16:05>
:PROPERTIES:
:ID:       VhxhmllDtI07H1ThzlfDGgTh@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Sounds @ Isotopes Sounds @ Isotopes

Follow on MiLB First Pitch  https //stza.co/+whG8-3z

Shop  https //stza.co/+whG8-3

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Sounds @ Isotopes
END:VALARM
DTSTART:20180619T180500Z
DTEND:20180619T210500Z
UID:VhxhmllDtI07H1ThzlfDGgTh@stanza.co
SUMMARY:Sounds @ Isotopes
DESCRIPTION:Sounds @ Isotopes\n\nFollow on MiLB First Pitch: https://stza.co/+whG8-3z\n\nShop: https://stza.co/+whG8-3\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Sounds vs. Express
<2018-06-21 Thu 19:05-22:05>
:PROPERTIES:
:ID:       QZrscAhePklT29T6jheaX0ml@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Sounds vs. Express Sounds vs. Express

Follow on MiLB First Pitch  https //stza.co/+whHm-Q

Shop  https //stza.co/+whHm-n

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Sounds vs. Express
END:VALARM
DTSTART:20180622T000500Z
DTEND:20180622T030500Z
UID:QZrscAhePklT29T6jheaX0ml@stanza.co
SUMMARY:Sounds vs. Express
DESCRIPTION:Sounds vs. Express\n\nFollow on MiLB First Pitch: https://stza.co/+whHm-Q\n\nShop: https://stza.co/+whHm-n\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Sounds vs. Express
<2018-06-22 Fri 19:05-22:05>
:PROPERTIES:
:ID:       rV4aX4z9ao2mfMIAjl1GikN_@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Sounds vs. Express Sounds vs. Express

Follow on MiLB First Pitch  https //stza.co/+whHo-3K

Shop  https //stza.co/+whHo-3m

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Sounds vs. Express
END:VALARM
DTSTART:20180623T000500Z
DTEND:20180623T030500Z
UID:rV4aX4z9ao2mfMIAjl1GikN_@stanza.co
SUMMARY:Sounds vs. Express
DESCRIPTION:Sounds vs. Express\n\nFollow on MiLB First Pitch: https://stza.co/+whHo-3K\n\nShop: https://stza.co/+whHo-3m\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Sounds vs. Express
<2018-06-23 Sat 19:05-22:05>
:PROPERTIES:
:ID:       1EiHTv2yKSw3zGVRCa1DMu6y@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Sounds vs. Express Sounds vs. Express

Follow on MiLB First Pitch  https //stza.co/+whHq-3q

Shop  https //stza.co/+whHq-3j

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Sounds vs. Express
END:VALARM
DTSTART:20180624T000500Z
DTEND:20180624T030500Z
UID:1EiHTv2yKSw3zGVRCa1DMu6y@stanza.co
SUMMARY:Sounds vs. Express
DESCRIPTION:Sounds vs. Express\n\nFollow on MiLB First Pitch: https://stza.co/+whHq-3q\n\nShop: https://stza.co/+whHq-3j\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Sounds vs. Express
<2018-06-24 Sun 18:15-21:15>
:PROPERTIES:
:ID:       87A3zXm9Z4Q5X5PbjiItIR_i@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Sounds vs. Express Sounds vs. Express

Follow on MiLB First Pitch  https //stza.co/+whHs-P

Shop  https //stza.co/+whHs-1z

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Sounds vs. Express
END:VALARM
DTSTART:20180624T231500Z
DTEND:20180625T021500Z
UID:87A3zXm9Z4Q5X5PbjiItIR_i@stanza.co
SUMMARY:Sounds vs. Express
DESCRIPTION:Sounds vs. Express\n\nFollow on MiLB First Pitch: https://stza.co/+whHs-P\n\nShop: https://stza.co/+whHs-1z\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Sounds @ Dodgers
<2018-06-25 Mon 19:05-22:05>
:PROPERTIES:
:ID:       zkzagm_CZh0xBgvQDX3CuJCB@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Sounds @ Dodgers Sounds @ Dodgers

Follow on MiLB First Pitch  https //stza.co/+v$MF-2S

Shop  https //stza.co/+v$MF-2V

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Sounds @ Dodgers
END:VALARM
DTSTART:20180626T000500Z
DTEND:20180626T030500Z
UID:zkzagm_CZh0xBgvQDX3CuJCB@stanza.co
SUMMARY:Sounds @ Dodgers
DESCRIPTION:Sounds @ Dodgers\n\nFollow on MiLB First Pitch: https://stza.co/+v$MF-2S\n\nShop: https://stza.co/+v$MF-2V\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Sounds @ Dodgers
<2018-06-26 Tue 19:05-22:05>
:PROPERTIES:
:ID:       KJRRkoIzuO0Ag0HR_zO81UPl@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Sounds @ Dodgers Sounds @ Dodgers

Follow on MiLB First Pitch  https //stza.co/+v$MG-22

Shop  https //stza.co/+v$MG-m

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Sounds @ Dodgers
END:VALARM
DTSTART:20180627T000500Z
DTEND:20180627T030500Z
UID:KJRRkoIzuO0Ag0HR_zO81UPl@stanza.co
SUMMARY:Sounds @ Dodgers
DESCRIPTION:Sounds @ Dodgers\n\nFollow on MiLB First Pitch: https://stza.co/+v$MG-22\n\nShop: https://stza.co/+v$MG-m\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Sounds @ Dodgers
<2018-06-27 Wed 19:05-22:05>
:PROPERTIES:
:ID:       Sml9yfqWxaYWeWnLDeMCwAdE@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Sounds @ Dodgers Sounds @ Dodgers

Follow on MiLB First Pitch  https //stza.co/+v$MH-3

Shop  https //stza.co/+v$MH-3h

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Sounds @ Dodgers
END:VALARM
DTSTART:20180628T000500Z
DTEND:20180628T030500Z
UID:Sml9yfqWxaYWeWnLDeMCwAdE@stanza.co
SUMMARY:Sounds @ Dodgers
DESCRIPTION:Sounds @ Dodgers\n\nFollow on MiLB First Pitch: https://stza.co/+v$MH-3\n\nShop: https://stza.co/+v$MH-3h\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Sounds @ Dodgers
<2018-06-28 Thu 19:05-22:05>
:PROPERTIES:
:ID:       JM6pRmLYh_X3bh1nWfAoVM6r@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Sounds @ Dodgers Sounds @ Dodgers

Follow on MiLB First Pitch  https //stza.co/+v$MI-3r

Shop  https //stza.co/+v$MI-3I

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Sounds @ Dodgers
END:VALARM
DTSTART:20180629T000500Z
DTEND:20180629T030500Z
UID:JM6pRmLYh_X3bh1nWfAoVM6r@stanza.co
SUMMARY:Sounds @ Dodgers
DESCRIPTION:Sounds @ Dodgers\n\nFollow on MiLB First Pitch: https://stza.co/+v$MI-3r\n\nShop: https://stza.co/+v$MI-3I\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Sounds @ Storm Chasers
<2018-06-29 Fri 19:05-22:05>
:PROPERTIES:
:ID:       sGUDMmKWZtdY5jB2yfU8of9j@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Sounds @ Storm Chasers Sounds @ Storm Chasers

Follow on MiLB First Pitch  https //stza.co/+whIF-v

Shop  https //stza.co/+whIF-18

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Sounds @ Storm Chasers
END:VALARM
DTSTART:20180630T000500Z
DTEND:20180630T030500Z
UID:sGUDMmKWZtdY5jB2yfU8of9j@stanza.co
SUMMARY:Sounds @ Storm Chasers
DESCRIPTION:Sounds @ Storm Chasers\n\nFollow on MiLB First Pitch: https://stza.co/+whIF-v\n\nShop: https://stza.co/+whIF-18\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Sounds @ Storm Chasers
<2018-06-30 Sat 19:05-22:05>
:PROPERTIES:
:ID:       JrPl6HZrLQ4faNrDWd50M-De@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Sounds @ Storm Chasers Sounds @ Storm Chasers

Follow on MiLB First Pitch  https //stza.co/+whIG-y

Shop  https //stza.co/+whIG-15

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Sounds @ Storm Chasers
END:VALARM
DTSTART:20180701T000500Z
DTEND:20180701T030500Z
UID:JrPl6HZrLQ4faNrDWd50M-De@stanza.co
SUMMARY:Sounds @ Storm Chasers
DESCRIPTION:Sounds @ Storm Chasers\n\nFollow on MiLB First Pitch: https://stza.co/+whIG-y\n\nShop: https://stza.co/+whIG-15\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Sounds @ Storm Chasers
<2018-07-01 Sun 14:05-17:05>
:PROPERTIES:
:ID:       -IuaQ9023CofzzNB7eR7Eq1c@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Sounds @ Storm Chasers Sounds @ Storm Chasers

Follow on MiLB First Pitch  https //stza.co/+whIH-2e

Shop  https //stza.co/+whIH-r

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Sounds @ Storm Chasers
END:VALARM
DTSTART:20180701T190500Z
DTEND:20180701T220500Z
UID:-IuaQ9023CofzzNB7eR7Eq1c@stanza.co
SUMMARY:Sounds @ Storm Chasers
DESCRIPTION:Sounds @ Storm Chasers\n\nFollow on MiLB First Pitch: https://stza.co/+whIH-2e\n\nShop: https://stza.co/+whIH-r\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Sounds @ Storm Chasers
<2018-07-02 Mon 19:05-22:05>
:PROPERTIES:
:ID:       1yBVnlkmdIxfAJm-SMv5SYRA@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Sounds @ Storm Chasers Sounds @ Storm Chasers

Follow on MiLB First Pitch  https //stza.co/+whII-1Y

Shop  https //stza.co/+whII-3m

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Sounds @ Storm Chasers
END:VALARM
DTSTART:20180703T000500Z
DTEND:20180703T030500Z
UID:1yBVnlkmdIxfAJm-SMv5SYRA@stanza.co
SUMMARY:Sounds @ Storm Chasers
DESCRIPTION:Sounds @ Storm Chasers\n\nFollow on MiLB First Pitch: https://stza.co/+whII-1Y\n\nShop: https://stza.co/+whII-3m\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Sounds @ Storm Chasers
<2018-07-03 Tue 19:05-22:05>
:PROPERTIES:
:ID:       zpV9ZU9UjE5eza1KxrEoBsZK@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Sounds @ Storm Chasers Sounds @ Storm Chasers

Follow on MiLB First Pitch  https //stza.co/+whIJ-2F

Shop  https //stza.co/+whIJ-J

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Sounds @ Storm Chasers
END:VALARM
DTSTART:20180704T000500Z
DTEND:20180704T030500Z
UID:zpV9ZU9UjE5eza1KxrEoBsZK@stanza.co
SUMMARY:Sounds @ Storm Chasers
DESCRIPTION:Sounds @ Storm Chasers\n\nFollow on MiLB First Pitch: https://stza.co/+whIJ-2F\n\nShop: https://stza.co/+whIJ-J\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Sounds vs. Cubs
<2018-07-04 Wed 19:05-22:05>
:PROPERTIES:
:ID:       QupXuGKf4VaWkPqsqlYk2G4B@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Sounds vs. Cubs Sounds vs. Cubs

Follow on MiLB First Pitch  https //stza.co/+whHu-2i

Shop  https //stza.co/+whHu-3r

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Sounds vs. Cubs
END:VALARM
DTSTART:20180705T000500Z
DTEND:20180705T030500Z
UID:QupXuGKf4VaWkPqsqlYk2G4B@stanza.co
SUMMARY:Sounds vs. Cubs
DESCRIPTION:Sounds vs. Cubs\n\nFollow on MiLB First Pitch: https://stza.co/+whHu-2i\n\nShop: https://stza.co/+whHu-3r\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Sounds vs. Cubs
<2018-07-05 Thu 19:05-22:05>
:PROPERTIES:
:ID:       8jR92ZvOqhxrRruzfrHYduAi@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Sounds vs. Cubs Sounds vs. Cubs

Follow on MiLB First Pitch  https //stza.co/+whHv-3M

Shop  https //stza.co/+whHv-2

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Sounds vs. Cubs
END:VALARM
DTSTART:20180706T000500Z
DTEND:20180706T030500Z
UID:8jR92ZvOqhxrRruzfrHYduAi@stanza.co
SUMMARY:Sounds vs. Cubs
DESCRIPTION:Sounds vs. Cubs\n\nFollow on MiLB First Pitch: https://stza.co/+whHv-3M\n\nShop: https://stza.co/+whHv-2\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Sounds vs. Cubs
<2018-07-06 Fri 19:05-22:05>
:PROPERTIES:
:ID:       psqD14wL5f_2PmCbrdZr_8Kd@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Sounds vs. Cubs Sounds vs. Cubs

Follow on MiLB First Pitch  https //stza.co/+whHy-3C

Shop  https //stza.co/+whHy-2$

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Sounds vs. Cubs
END:VALARM
DTSTART:20180707T000500Z
DTEND:20180707T030500Z
UID:psqD14wL5f_2PmCbrdZr_8Kd@stanza.co
SUMMARY:Sounds vs. Cubs
DESCRIPTION:Sounds vs. Cubs\n\nFollow on MiLB First Pitch: https://stza.co/+whHy-3C\n\nShop: https://stza.co/+whHy-2$\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Sounds vs. Cubs
<2018-07-07 Sat 19:05-22:05>
:PROPERTIES:
:ID:       pXHMEdrBvJZGuKObVwSre-al@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Sounds vs. Cubs Sounds vs. Cubs

Follow on MiLB First Pitch  https //stza.co/+whHA-1I

Shop  https //stza.co/+whHA-1X

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Sounds vs. Cubs
END:VALARM
DTSTART:20180708T000500Z
DTEND:20180708T030500Z
UID:pXHMEdrBvJZGuKObVwSre-al@stanza.co
SUMMARY:Sounds vs. Cubs
DESCRIPTION:Sounds vs. Cubs\n\nFollow on MiLB First Pitch: https://stza.co/+whHA-1I\n\nShop: https://stza.co/+whHA-1X\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Sounds vs. Cubs
<2018-07-08 Sun 18:15-21:15>
:PROPERTIES:
:ID:       a7Q3nIRTc-k66tqd-Cv06JML@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Sounds vs. Cubs Sounds vs. Cubs

Follow on MiLB First Pitch  https //stza.co/+whHB-3K

Shop  https //stza.co/+whHB-V

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Sounds vs. Cubs
END:VALARM
DTSTART:20180708T231500Z
DTEND:20180709T021500Z
UID:a7Q3nIRTc-k66tqd-Cv06JML@stanza.co
SUMMARY:Sounds vs. Cubs
DESCRIPTION:Sounds vs. Cubs\n\nFollow on MiLB First Pitch: https://stza.co/+whHB-3K\n\nShop: https://stza.co/+whHB-V\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Sounds @ Cubs
<2018-07-12 Thu 19:08-22:08>
:PROPERTIES:
:ID:       g19UI2Ztr3hVUyshmjiGABPZ@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Sounds @ Cubs Sounds @ Cubs

Follow on MiLB First Pitch  https //stza.co/+vKJ9-q

Shop  https //stza.co/+vKJ9-3J

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Sounds @ Cubs
END:VALARM
DTSTART:20180713T000800Z
DTEND:20180713T030800Z
UID:g19UI2Ztr3hVUyshmjiGABPZ@stanza.co
SUMMARY:Sounds @ Cubs
DESCRIPTION:Sounds @ Cubs\n\nFollow on MiLB First Pitch: https://stza.co/+vKJ9-q\n\nShop: https://stza.co/+vKJ9-3J\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Sounds @ Cubs
<2018-07-13 Fri 19:08-22:08>
:PROPERTIES:
:ID:       5CqVyGeVlhV2k5d7biALL-J3@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Sounds @ Cubs Sounds @ Cubs

Follow on MiLB First Pitch  https //stza.co/+vKJa-26

Shop  https //stza.co/+vKJa-1m

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Sounds @ Cubs
END:VALARM
DTSTART:20180714T000800Z
DTEND:20180714T030800Z
UID:5CqVyGeVlhV2k5d7biALL-J3@stanza.co
SUMMARY:Sounds @ Cubs
DESCRIPTION:Sounds @ Cubs\n\nFollow on MiLB First Pitch: https://stza.co/+vKJa-26\n\nShop: https://stza.co/+vKJa-1m\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Sounds @ Cubs
<2018-07-14 Sat 19:08-22:08>
:PROPERTIES:
:ID:       kZVLcWSYWMIrpYLbgsdODQHt@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Sounds @ Cubs Sounds @ Cubs

Follow on MiLB First Pitch  https //stza.co/+vKJb-2q

Shop  https //stza.co/+vKJb-1S

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Sounds @ Cubs
END:VALARM
DTSTART:20180715T000800Z
DTEND:20180715T030800Z
UID:kZVLcWSYWMIrpYLbgsdODQHt@stanza.co
SUMMARY:Sounds @ Cubs
DESCRIPTION:Sounds @ Cubs\n\nFollow on MiLB First Pitch: https://stza.co/+vKJb-2q\n\nShop: https://stza.co/+vKJb-1S\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Sounds @ Cubs
<2018-07-15 Sun 13:08-16:08>
:PROPERTIES:
:ID:       2ZGhlfLLqnOUQZ6dWmw5wonz@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Sounds @ Cubs Sounds @ Cubs

Follow on MiLB First Pitch  https //stza.co/+vKJc-3C

Shop  https //stza.co/+vKJc-16

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Sounds @ Cubs
END:VALARM
DTSTART:20180715T180800Z
DTEND:20180715T210800Z
UID:2ZGhlfLLqnOUQZ6dWmw5wonz@stanza.co
SUMMARY:Sounds @ Cubs
DESCRIPTION:Sounds @ Cubs\n\nFollow on MiLB First Pitch: https://stza.co/+vKJc-3C\n\nShop: https://stza.co/+vKJc-16\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Sounds vs. Storm Chasers
<2018-07-16 Mon 19:05-22:05>
:PROPERTIES:
:ID:       tULWSrbz6XM6omhcMkaQOaJ8@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Sounds vs. Storm Chasers Sounds vs. Storm Chasers

Follow on MiLB First Pitch  https //stza.co/+whHE-1m

Shop  https //stza.co/+whHE-1u

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Sounds vs. Storm Chasers
END:VALARM
DTSTART:20180717T000500Z
DTEND:20180717T030500Z
UID:tULWSrbz6XM6omhcMkaQOaJ8@stanza.co
SUMMARY:Sounds vs. Storm Chasers
DESCRIPTION:Sounds vs. Storm Chasers\n\nFollow on MiLB First Pitch: https://stza.co/+whHE-1m\n\nShop: https://stza.co/+whHE-1u\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Sounds vs. Storm Chasers
<2018-07-17 Tue 19:05-22:05>
:PROPERTIES:
:ID:       mWjF4alK0en6_WtuGzE6f1Mp@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Sounds vs. Storm Chasers Sounds vs. Storm Chasers

Follow on MiLB First Pitch  https //stza.co/+whHG-1b

Shop  https //stza.co/+whHG-10

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Sounds vs. Storm Chasers
END:VALARM
DTSTART:20180718T000500Z
DTEND:20180718T030500Z
UID:mWjF4alK0en6_WtuGzE6f1Mp@stanza.co
SUMMARY:Sounds vs. Storm Chasers
DESCRIPTION:Sounds vs. Storm Chasers\n\nFollow on MiLB First Pitch: https://stza.co/+whHG-1b\n\nShop: https://stza.co/+whHG-10\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Sounds vs. Storm Chasers
<2018-07-18 Wed 19:05-22:05>
:PROPERTIES:
:ID:       LwOjLLKW4ujZp5_9ZOHvJ6Ok@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Sounds vs. Storm Chasers Sounds vs. Storm Chasers

Follow on MiLB First Pitch  https //stza.co/+whHJ-11

Shop  https //stza.co/+whHJ-3v

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Sounds vs. Storm Chasers
END:VALARM
DTSTART:20180719T000500Z
DTEND:20180719T030500Z
UID:LwOjLLKW4ujZp5_9ZOHvJ6Ok@stanza.co
SUMMARY:Sounds vs. Storm Chasers
DESCRIPTION:Sounds vs. Storm Chasers\n\nFollow on MiLB First Pitch: https://stza.co/+whHJ-11\n\nShop: https://stza.co/+whHJ-3v\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Sounds vs. Storm Chasers
<2018-07-19 Thu 19:05-22:05>
:PROPERTIES:
:ID:       L7Z8pxkSNMtqHtT6nMEfVdIb@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Sounds vs. Storm Chasers Sounds vs. Storm Chasers

Follow on MiLB First Pitch  https //stza.co/+whHK-1h

Shop  https //stza.co/+whHK-3w

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Sounds vs. Storm Chasers
END:VALARM
DTSTART:20180720T000500Z
DTEND:20180720T030500Z
UID:L7Z8pxkSNMtqHtT6nMEfVdIb@stanza.co
SUMMARY:Sounds vs. Storm Chasers
DESCRIPTION:Sounds vs. Storm Chasers\n\nFollow on MiLB First Pitch: https://stza.co/+whHK-1h\n\nShop: https://stza.co/+whHK-3w\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Sounds vs. Dodgers
<2018-07-20 Fri 19:05-22:05>
:PROPERTIES:
:ID:       Ie98gJL3REAlOK-le6JPAP-e@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Sounds vs. Dodgers Sounds vs. Dodgers

Follow on MiLB First Pitch  https //stza.co/+whHN-1A

Shop  https //stza.co/+whHN-2p

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Sounds vs. Dodgers
END:VALARM
DTSTART:20180721T000500Z
DTEND:20180721T030500Z
UID:Ie98gJL3REAlOK-le6JPAP-e@stanza.co
SUMMARY:Sounds vs. Dodgers
DESCRIPTION:Sounds vs. Dodgers\n\nFollow on MiLB First Pitch: https://stza.co/+whHN-1A\n\nShop: https://stza.co/+whHN-2p\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Sounds vs. Dodgers
<2018-07-21 Sat 19:05-22:05>
:PROPERTIES:
:ID:       tOltSDS0dIqn6F2p-tLfuYaJ@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Sounds vs. Dodgers Sounds vs. Dodgers

Follow on MiLB First Pitch  https //stza.co/+whHP-10

Shop  https //stza.co/+whHP-17

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Sounds vs. Dodgers
END:VALARM
DTSTART:20180722T000500Z
DTEND:20180722T030500Z
UID:tOltSDS0dIqn6F2p-tLfuYaJ@stanza.co
SUMMARY:Sounds vs. Dodgers
DESCRIPTION:Sounds vs. Dodgers\n\nFollow on MiLB First Pitch: https://stza.co/+whHP-10\n\nShop: https://stza.co/+whHP-17\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Sounds vs. Dodgers
<2018-07-22 Sun 18:15-21:15>
:PROPERTIES:
:ID:       VslSxgX8xHUcHbklBu3_SYYy@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Sounds vs. Dodgers Sounds vs. Dodgers

Follow on MiLB First Pitch  https //stza.co/+whHQ-1v

Shop  https //stza.co/+whHQ-1c

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Sounds vs. Dodgers
END:VALARM
DTSTART:20180722T231500Z
DTEND:20180723T021500Z
UID:VslSxgX8xHUcHbklBu3_SYYy@stanza.co
SUMMARY:Sounds vs. Dodgers
DESCRIPTION:Sounds vs. Dodgers\n\nFollow on MiLB First Pitch: https://stza.co/+whHQ-1v\n\nShop: https://stza.co/+whHQ-1c\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Sounds @ 51s
<2018-07-24 Tue 21:05>--<2018-07-25 Wed 00:05>
:PROPERTIES:
:ID:       7n6eBuzovYy00Aph7u34atSK@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Sounds @ 51s Sounds @ 51s

Follow on MiLB First Pitch  https //stza.co/+vKJd-1M

Shop  https //stza.co/+vKJd-3Q

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Sounds @ 51s
END:VALARM
DTSTART:20180725T020500Z
DTEND:20180725T050500Z
UID:7n6eBuzovYy00Aph7u34atSK@stanza.co
SUMMARY:Sounds @ 51s
DESCRIPTION:Sounds @ 51s\n\nFollow on MiLB First Pitch: https://stza.co/+vKJd-1M\n\nShop: https://stza.co/+vKJd-3Q\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Sounds @ 51s
<2018-07-25 Wed 21:05>--<2018-07-26 Thu 00:05>
:PROPERTIES:
:ID:       OtU_y9JzZbXDzl4NSRlH0QE0@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Sounds @ 51s Sounds @ 51s

Follow on MiLB First Pitch  https //stza.co/+vKJe-3y

Shop  https //stza.co/+vKJe-31

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Sounds @ 51s
END:VALARM
DTSTART:20180726T020500Z
DTEND:20180726T050500Z
UID:OtU_y9JzZbXDzl4NSRlH0QE0@stanza.co
SUMMARY:Sounds @ 51s
DESCRIPTION:Sounds @ 51s\n\nFollow on MiLB First Pitch: https://stza.co/+vKJe-3y\n\nShop: https://stza.co/+vKJe-31\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Sounds @ 51s
<2018-07-26 Thu 21:05>--<2018-07-27 Fri 00:05>
:PROPERTIES:
:ID:       Uvb1fo4b34BiHvRC_lSLOtGf@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Sounds @ 51s Sounds @ 51s

Follow on MiLB First Pitch  https //stza.co/+vKJf-3_

Shop  https //stza.co/+vKJf-1r

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Sounds @ 51s
END:VALARM
DTSTART:20180727T020500Z
DTEND:20180727T050500Z
UID:Uvb1fo4b34BiHvRC_lSLOtGf@stanza.co
SUMMARY:Sounds @ 51s
DESCRIPTION:Sounds @ 51s\n\nFollow on MiLB First Pitch: https://stza.co/+vKJf-3_\n\nShop: https://stza.co/+vKJf-1r\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Sounds @ Bees
<2018-07-27 Fri 19:35-22:35>
:PROPERTIES:
:ID:       dK44tMcFJmcn_Jn_AOeRYjzx@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Sounds @ Bees Sounds @ Bees

Follow on MiLB First Pitch  https //stza.co/+wmHc-C

Shop  https //stza.co/+wmHc-3Q

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Sounds @ Bees
END:VALARM
DTSTART:20180728T003500Z
DTEND:20180728T033500Z
UID:dK44tMcFJmcn_Jn_AOeRYjzx@stanza.co
SUMMARY:Sounds @ Bees
DESCRIPTION:Sounds @ Bees\n\nFollow on MiLB First Pitch: https://stza.co/+wmHc-C\n\nShop: https://stza.co/+wmHc-3Q\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Sounds @ Bees
<2018-07-28 Sat 19:35-22:35>
:PROPERTIES:
:ID:       WA66BRRDCg7Vmg_Fbp0o4Jr9@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Sounds @ Bees Sounds @ Bees

Follow on MiLB First Pitch  https //stza.co/+wmHd-35

Shop  https //stza.co/+wmHd-1W

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Sounds @ Bees
END:VALARM
DTSTART:20180729T003500Z
DTEND:20180729T033500Z
UID:WA66BRRDCg7Vmg_Fbp0o4Jr9@stanza.co
SUMMARY:Sounds @ Bees
DESCRIPTION:Sounds @ Bees\n\nFollow on MiLB First Pitch: https://stza.co/+wmHd-35\n\nShop: https://stza.co/+wmHd-1W\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Sounds @ Bees
<2018-07-29 Sun 19:05-22:05>
:PROPERTIES:
:ID:       FCa-yCeczqitESrx84fDeXX-@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Sounds @ Bees Sounds @ Bees

Follow on MiLB First Pitch  https //stza.co/+wmHe-36

Shop  https //stza.co/+wmHe-3B

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Sounds @ Bees
END:VALARM
DTSTART:20180730T000500Z
DTEND:20180730T030500Z
UID:FCa-yCeczqitESrx84fDeXX-@stanza.co
SUMMARY:Sounds @ Bees
DESCRIPTION:Sounds @ Bees\n\nFollow on MiLB First Pitch: https://stza.co/+wmHe-36\n\nShop: https://stza.co/+wmHe-3B\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Sounds @ Bees
<2018-07-30 Mon 20:05-23:05>
:PROPERTIES:
:ID:       zG7jky6QDtlYnSS46DrIr1pi@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Sounds @ Bees Sounds @ Bees

Follow on MiLB First Pitch  https //stza.co/+wmHf-3B

Shop  https //stza.co/+wmHf-1f

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Sounds @ Bees
END:VALARM
DTSTART:20180731T010500Z
DTEND:20180731T040500Z
UID:zG7jky6QDtlYnSS46DrIr1pi@stanza.co
SUMMARY:Sounds @ Bees
DESCRIPTION:Sounds @ Bees\n\nFollow on MiLB First Pitch: https://stza.co/+wmHf-3B\n\nShop: https://stza.co/+wmHf-1f\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Sounds vs. Grizzlies
<2018-08-01 Wed 19:05-22:05>
:PROPERTIES:
:ID:       HHtfLmInTgr2FGAA8a7lbLhC@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Sounds vs. Grizzlies Sounds vs. Grizzlies

Follow on MiLB First Pitch  https //stza.co/+whHS-25

Shop  https //stza.co/+whHS-1e

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Sounds vs. Grizzlies
END:VALARM
DTSTART:20180802T000500Z
DTEND:20180802T030500Z
UID:HHtfLmInTgr2FGAA8a7lbLhC@stanza.co
SUMMARY:Sounds vs. Grizzlies
DESCRIPTION:Sounds vs. Grizzlies\n\nFollow on MiLB First Pitch: https://stza.co/+whHS-25\n\nShop: https://stza.co/+whHS-1e\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Sounds vs. Grizzlies
<2018-08-02 Thu 19:05-22:05>
:PROPERTIES:
:ID:       DRFicjhcbxulv8LQAzmFbo4K@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Sounds vs. Grizzlies Sounds vs. Grizzlies

Follow on MiLB First Pitch  https //stza.co/+whHU-37

Shop  https //stza.co/+whHU-35

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Sounds vs. Grizzlies
END:VALARM
DTSTART:20180803T000500Z
DTEND:20180803T030500Z
UID:DRFicjhcbxulv8LQAzmFbo4K@stanza.co
SUMMARY:Sounds vs. Grizzlies
DESCRIPTION:Sounds vs. Grizzlies\n\nFollow on MiLB First Pitch: https://stza.co/+whHU-37\n\nShop: https://stza.co/+whHU-35\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Sounds vs. Grizzlies
<2018-08-03 Fri 19:05-22:05>
:PROPERTIES:
:ID:       pEYx8BL7E1Qoa5a8CeOhgnmG@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Sounds vs. Grizzlies Sounds vs. Grizzlies

Follow on MiLB First Pitch  https //stza.co/+whHX-3O

Shop  https //stza.co/+whHX-1W

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Sounds vs. Grizzlies
END:VALARM
DTSTART:20180804T000500Z
DTEND:20180804T030500Z
UID:pEYx8BL7E1Qoa5a8CeOhgnmG@stanza.co
SUMMARY:Sounds vs. Grizzlies
DESCRIPTION:Sounds vs. Grizzlies\n\nFollow on MiLB First Pitch: https://stza.co/+whHX-3O\n\nShop: https://stza.co/+whHX-1W\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Sounds vs. River Cats
<2018-08-04 Sat 19:05-22:05>
:PROPERTIES:
:ID:       USYs5FcPmL5nJNI9MJ20-gWx@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Sounds vs. River Cats Sounds vs. River Cats

Follow on MiLB First Pitch  https //stza.co/+whHY-1A

Shop  https //stza.co/+whHY-1N

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Sounds vs. River Cats
END:VALARM
DTSTART:20180805T000500Z
DTEND:20180805T030500Z
UID:USYs5FcPmL5nJNI9MJ20-gWx@stanza.co
SUMMARY:Sounds vs. River Cats
DESCRIPTION:Sounds vs. River Cats\n\nFollow on MiLB First Pitch: https://stza.co/+whHY-1A\n\nShop: https://stza.co/+whHY-1N\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Sounds vs. River Cats
<2018-08-05 Sun 18:15-21:15>
:PROPERTIES:
:ID:       2xYPMYJxl7JTKt1R9gQ5-o72@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Sounds vs. River Cats Sounds vs. River Cats

Follow on MiLB First Pitch  https //stza.co/+whH$-2Y

Shop  https //stza.co/+whH$-1R

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Sounds vs. River Cats
END:VALARM
DTSTART:20180805T231500Z
DTEND:20180806T021500Z
UID:2xYPMYJxl7JTKt1R9gQ5-o72@stanza.co
SUMMARY:Sounds vs. River Cats
DESCRIPTION:Sounds vs. River Cats\n\nFollow on MiLB First Pitch: https://stza.co/+whH$-2Y\n\nShop: https://stza.co/+whH$-1R\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Sounds vs. River Cats
<2018-08-06 Mon 19:05-22:05>
:PROPERTIES:
:ID:       BBLXpduSS4fd2L56u8UOnHQy@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Sounds vs. River Cats Sounds vs. River Cats

Follow on MiLB First Pitch  https //stza.co/+whI1-1K

Shop  https //stza.co/+whI1-3v

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Sounds vs. River Cats
END:VALARM
DTSTART:20180807T000500Z
DTEND:20180807T030500Z
UID:BBLXpduSS4fd2L56u8UOnHQy@stanza.co
SUMMARY:Sounds vs. River Cats
DESCRIPTION:Sounds vs. River Cats\n\nFollow on MiLB First Pitch: https://stza.co/+whI1-1K\n\nShop: https://stza.co/+whI1-3v\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Sounds vs. River Cats
<2018-08-07 Tue 19:05-22:05>
:PROPERTIES:
:ID:       Bg0oBELgzP42leIwkrZhV_fN@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Sounds vs. River Cats Sounds vs. River Cats

Follow on MiLB First Pitch  https //stza.co/+whI3-21

Shop  https //stza.co/+whI3-1J

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Sounds vs. River Cats
END:VALARM
DTSTART:20180808T000500Z
DTEND:20180808T030500Z
UID:Bg0oBELgzP42leIwkrZhV_fN@stanza.co
SUMMARY:Sounds vs. River Cats
DESCRIPTION:Sounds vs. River Cats\n\nFollow on MiLB First Pitch: https://stza.co/+whI3-21\n\nShop: https://stza.co/+whI3-1J\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Sounds @ Sky Sox
<2018-08-09 Thu 19:40-22:40>
:PROPERTIES:
:ID:       kR9BsvLexvqRiU4zgH3KFdjz@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Sounds @ Sky Sox Sounds @ Sky Sox

Follow on MiLB First Pitch  https //stza.co/+wmGX-2F

Shop  https //stza.co/+wmGX-3S

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Sounds @ Sky Sox
END:VALARM
DTSTART:20180810T004000Z
DTEND:20180810T034000Z
UID:kR9BsvLexvqRiU4zgH3KFdjz@stanza.co
SUMMARY:Sounds @ Sky Sox
DESCRIPTION:Sounds @ Sky Sox\n\nFollow on MiLB First Pitch: https://stza.co/+wmGX-2F\n\nShop: https://stza.co/+wmGX-3S\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Sounds @ Sky Sox
<2018-08-10 Fri 19:40-22:40>
:PROPERTIES:
:ID:       yZmMDgZWUFYE7p-K5zniPE39@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Sounds @ Sky Sox Sounds @ Sky Sox

Follow on MiLB First Pitch  https //stza.co/+wmGY-2L

Shop  https //stza.co/+wmGY-1x

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Sounds @ Sky Sox
END:VALARM
DTSTART:20180811T004000Z
DTEND:20180811T034000Z
UID:yZmMDgZWUFYE7p-K5zniPE39@stanza.co
SUMMARY:Sounds @ Sky Sox
DESCRIPTION:Sounds @ Sky Sox\n\nFollow on MiLB First Pitch: https://stza.co/+wmGY-2L\n\nShop: https://stza.co/+wmGY-1x\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Sounds @ Sky Sox
<2018-08-11 Sat 19:00-22:00>
:PROPERTIES:
:ID:       rWg89X6-1oLCrBCLiGEs71lA@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Sounds @ Sky Sox Sounds @ Sky Sox

Follow on MiLB First Pitch  https //stza.co/+wmGZ-1m

Shop  https //stza.co/+wmGZ-s

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Sounds @ Sky Sox
END:VALARM
DTSTART:20180812T000000Z
DTEND:20180812T030000Z
UID:rWg89X6-1oLCrBCLiGEs71lA@stanza.co
SUMMARY:Sounds @ Sky Sox
DESCRIPTION:Sounds @ Sky Sox\n\nFollow on MiLB First Pitch: https://stza.co/+wmGZ-1m\n\nShop: https://stza.co/+wmGZ-s\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Sounds @ Sky Sox
<2018-08-12 Sun 14:30-17:30>
:PROPERTIES:
:ID:       rDGI_F9ZnZLgOK5qVlwxwnAy@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Sounds @ Sky Sox Sounds @ Sky Sox

Follow on MiLB First Pitch  https //stza.co/+wmG_-U

Shop  https //stza.co/+wmG_-3v

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Sounds @ Sky Sox
END:VALARM
DTSTART:20180812T193000Z
DTEND:20180812T223000Z
UID:rDGI_F9ZnZLgOK5qVlwxwnAy@stanza.co
SUMMARY:Sounds @ Sky Sox
DESCRIPTION:Sounds @ Sky Sox\n\nFollow on MiLB First Pitch: https://stza.co/+wmG_-U\n\nShop: https://stza.co/+wmG_-3v\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Sounds vs. Express
<2018-08-13 Mon 19:05-22:05>
:PROPERTIES:
:ID:       BkTiOcODdN4muc3VYnSugMNV@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Sounds vs. Express Sounds vs. Express

Follow on MiLB First Pitch  https //stza.co/+whI5-2u

Shop  https //stza.co/+whI5-3p

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Sounds vs. Express
END:VALARM
DTSTART:20180814T000500Z
DTEND:20180814T030500Z
UID:BkTiOcODdN4muc3VYnSugMNV@stanza.co
SUMMARY:Sounds vs. Express
DESCRIPTION:Sounds vs. Express\n\nFollow on MiLB First Pitch: https://stza.co/+whI5-2u\n\nShop: https://stza.co/+whI5-3p\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Sounds vs. Express
<2018-08-14 Tue 19:05-22:05>
:PROPERTIES:
:ID:       k6TyU9tJdaqcWr8OObrEXLzm@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Sounds vs. Express Sounds vs. Express

Follow on MiLB First Pitch  https //stza.co/+whI7-2V

Shop  https //stza.co/+whI7-3t

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Sounds vs. Express
END:VALARM
DTSTART:20180815T000500Z
DTEND:20180815T030500Z
UID:k6TyU9tJdaqcWr8OObrEXLzm@stanza.co
SUMMARY:Sounds vs. Express
DESCRIPTION:Sounds vs. Express\n\nFollow on MiLB First Pitch: https://stza.co/+whI7-2V\n\nShop: https://stza.co/+whI7-3t\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Sounds vs. Express
<2018-08-15 Wed 19:05-22:05>
:PROPERTIES:
:ID:       YqTu7J3T2l3GL5gFfBxNXaI6@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Sounds vs. Express Sounds vs. Express

Follow on MiLB First Pitch  https //stza.co/+whI9-V

Shop  https //stza.co/+whI9-I

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Sounds vs. Express
END:VALARM
DTSTART:20180816T000500Z
DTEND:20180816T030500Z
UID:YqTu7J3T2l3GL5gFfBxNXaI6@stanza.co
SUMMARY:Sounds vs. Express
DESCRIPTION:Sounds vs. Express\n\nFollow on MiLB First Pitch: https://stza.co/+whI9-V\n\nShop: https://stza.co/+whI9-I\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Sounds vs. Express
<2018-08-16 Thu 19:05-22:05>
:PROPERTIES:
:ID:       N1G-yTqnB4zPTckWB__wnKYR@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Sounds vs. Express Sounds vs. Express

Follow on MiLB First Pitch  https //stza.co/+whIb-2K

Shop  https //stza.co/+whIb-1n

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Sounds vs. Express
END:VALARM
DTSTART:20180817T000500Z
DTEND:20180817T030500Z
UID:N1G-yTqnB4zPTckWB__wnKYR@stanza.co
SUMMARY:Sounds vs. Express
DESCRIPTION:Sounds vs. Express\n\nFollow on MiLB First Pitch: https://stza.co/+whIb-2K\n\nShop: https://stza.co/+whIb-1n\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Sounds vs. Baby Cakes
<2018-08-17 Fri 19:05-22:05>
:PROPERTIES:
:ID:       6x0emPSGFZ91C4Y5kJT63P8-@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Sounds vs. Baby Cakes Sounds vs. Baby Cakes

Follow on MiLB First Pitch  https //stza.co/+whIe-2x

Shop  https //stza.co/+whIe-2T

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Sounds vs. Baby Cakes
END:VALARM
DTSTART:20180818T000500Z
DTEND:20180818T030500Z
UID:6x0emPSGFZ91C4Y5kJT63P8-@stanza.co
SUMMARY:Sounds vs. Baby Cakes
DESCRIPTION:Sounds vs. Baby Cakes\n\nFollow on MiLB First Pitch: https://stza.co/+whIe-2x\n\nShop: https://stza.co/+whIe-2T\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Sounds vs. Baby Cakes
<2018-08-18 Sat 19:05-22:05>
:PROPERTIES:
:ID:       KKt2e8StZ2n_8VEOiqdQmRMJ@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Sounds vs. Baby Cakes Sounds vs. Baby Cakes

Follow on MiLB First Pitch  https //stza.co/+whIg-3B

Shop  https //stza.co/+whIg-a

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Sounds vs. Baby Cakes
END:VALARM
DTSTART:20180819T000500Z
DTEND:20180819T030500Z
UID:KKt2e8StZ2n_8VEOiqdQmRMJ@stanza.co
SUMMARY:Sounds vs. Baby Cakes
DESCRIPTION:Sounds vs. Baby Cakes\n\nFollow on MiLB First Pitch: https://stza.co/+whIg-3B\n\nShop: https://stza.co/+whIg-a\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Sounds vs. Baby Cakes
<2018-08-19 Sun 18:15-21:15>
:PROPERTIES:
:ID:       fBAqupxKEQiYBocM3eHfloeD@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Sounds vs. Baby Cakes Sounds vs. Baby Cakes

Follow on MiLB First Pitch  https //stza.co/+whIh-1_

Shop  https //stza.co/+whIh-38

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Sounds vs. Baby Cakes
END:VALARM
DTSTART:20180819T231500Z
DTEND:20180820T021500Z
UID:fBAqupxKEQiYBocM3eHfloeD@stanza.co
SUMMARY:Sounds vs. Baby Cakes
DESCRIPTION:Sounds vs. Baby Cakes\n\nFollow on MiLB First Pitch: https://stza.co/+whIh-1_\n\nShop: https://stza.co/+whIh-38\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Sounds @ Express
<2018-08-21 Tue 19:05-22:05>
:PROPERTIES:
:ID:       iU_3WUNKcS2v6UL8IT8L3WyA@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Sounds @ Express Sounds @ Express

Follow on MiLB First Pitch  https //stza.co/+v2ay-i

Shop  https //stza.co/+v2ay-1c

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Sounds @ Express
END:VALARM
DTSTART:20180822T000500Z
DTEND:20180822T030500Z
UID:iU_3WUNKcS2v6UL8IT8L3WyA@stanza.co
SUMMARY:Sounds @ Express
DESCRIPTION:Sounds @ Express\n\nFollow on MiLB First Pitch: https://stza.co/+v2ay-i\n\nShop: https://stza.co/+v2ay-1c\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Sounds @ Express
<2018-08-22 Wed 19:05-22:05>
:PROPERTIES:
:ID:       t_i963prMGcUJPj0cSFM0kWJ@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Sounds @ Express Sounds @ Express

Follow on MiLB First Pitch  https //stza.co/+v2aG-3U

Shop  https //stza.co/+v2aG-3

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Sounds @ Express
END:VALARM
DTSTART:20180823T000500Z
DTEND:20180823T030500Z
UID:t_i963prMGcUJPj0cSFM0kWJ@stanza.co
SUMMARY:Sounds @ Express
DESCRIPTION:Sounds @ Express\n\nFollow on MiLB First Pitch: https://stza.co/+v2aG-3U\n\nShop: https://stza.co/+v2aG-3\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Sounds @ Express
<2018-08-23 Thu 19:05-22:05>
:PROPERTIES:
:ID:       H5KCOUKr3CqFVTOFeN_uWOgp@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Sounds @ Express Sounds @ Express

Follow on MiLB First Pitch  https //stza.co/+v2aP-3l

Shop  https //stza.co/+v2aP-3h

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Sounds @ Express
END:VALARM
DTSTART:20180824T000500Z
DTEND:20180824T030500Z
UID:H5KCOUKr3CqFVTOFeN_uWOgp@stanza.co
SUMMARY:Sounds @ Express
DESCRIPTION:Sounds @ Express\n\nFollow on MiLB First Pitch: https://stza.co/+v2aP-3l\n\nShop: https://stza.co/+v2aP-3h\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Sounds @ Redbirds
<2018-08-24 Fri 19:05-22:05>
:PROPERTIES:
:ID:       5tc7WF5j7VqkqFJnaeCj2zTd@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Sounds @ Redbirds Sounds @ Redbirds

Follow on MiLB First Pitch  https //stza.co/+wmH6-3O

Shop  https //stza.co/+wmH6-1b

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Sounds @ Redbirds
END:VALARM
DTSTART:20180825T000500Z
DTEND:20180825T030500Z
UID:5tc7WF5j7VqkqFJnaeCj2zTd@stanza.co
SUMMARY:Sounds @ Redbirds
DESCRIPTION:Sounds @ Redbirds\n\nFollow on MiLB First Pitch: https://stza.co/+wmH6-3O\n\nShop: https://stza.co/+wmH6-1b\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Sounds @ Redbirds
<2018-08-25 Sat 18:35-21:35>
:PROPERTIES:
:ID:       ktqerttjPHK67P_4f0_zLNQ2@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Sounds @ Redbirds Sounds @ Redbirds

Follow on MiLB First Pitch  https //stza.co/+wmH7-2K

Shop  https //stza.co/+wmH7-13

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Sounds @ Redbirds
END:VALARM
DTSTART:20180825T233500Z
DTEND:20180826T023500Z
UID:ktqerttjPHK67P_4f0_zLNQ2@stanza.co
SUMMARY:Sounds @ Redbirds
DESCRIPTION:Sounds @ Redbirds\n\nFollow on MiLB First Pitch: https://stza.co/+wmH7-2K\n\nShop: https://stza.co/+wmH7-13\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Sounds @ Redbirds
<2018-08-26 Sun 14:05-17:05>
:PROPERTIES:
:ID:       9UHFfgyxkzZBsw_jugOeDrQA@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Sounds @ Redbirds Sounds @ Redbirds

Follow on MiLB First Pitch  https //stza.co/+wmH8-3r

Shop  https //stza.co/+wmH8-3L

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Sounds @ Redbirds
END:VALARM
DTSTART:20180826T190500Z
DTEND:20180826T220500Z
UID:9UHFfgyxkzZBsw_jugOeDrQA@stanza.co
SUMMARY:Sounds @ Redbirds
DESCRIPTION:Sounds @ Redbirds\n\nFollow on MiLB First Pitch: https://stza.co/+wmH8-3r\n\nShop: https://stza.co/+wmH8-3L\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Sounds @ Redbirds
<2018-08-27 Mon 18:35-21:35>
:PROPERTIES:
:ID:       mrC4YyVW8KYDGeil5K_2B_ga@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Sounds @ Redbirds Sounds @ Redbirds

Follow on MiLB First Pitch  https //stza.co/+wmH9-X

Shop  https //stza.co/+wmH9-1l

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Sounds @ Redbirds
END:VALARM
DTSTART:20180827T233500Z
DTEND:20180828T023500Z
UID:mrC4YyVW8KYDGeil5K_2B_ga@stanza.co
SUMMARY:Sounds @ Redbirds
DESCRIPTION:Sounds @ Redbirds\n\nFollow on MiLB First Pitch: https://stza.co/+wmH9-X\n\nShop: https://stza.co/+wmH9-1l\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Sounds @ Baby Cakes
<2018-08-28 Tue 19:00-22:00>
:PROPERTIES:
:ID:       qM-CczFuZwRAB0hYvtV2S_JZ@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Sounds @ Baby Cakes Sounds @ Baby Cakes

Follow on MiLB First Pitch  https //stza.co/+whIy-3l

Shop  https //stza.co/+whIy-3

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Sounds @ Baby Cakes
END:VALARM
DTSTART:20180829T000000Z
DTEND:20180829T030000Z
UID:qM-CczFuZwRAB0hYvtV2S_JZ@stanza.co
SUMMARY:Sounds @ Baby Cakes
DESCRIPTION:Sounds @ Baby Cakes\n\nFollow on MiLB First Pitch: https://stza.co/+whIy-3l\n\nShop: https://stza.co/+whIy-3\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Sounds @ Baby Cakes
<2018-08-29 Wed 19:00-22:00>
:PROPERTIES:
:ID:       htUJLJEaLbpyA1Ot2cNrQYJt@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Sounds @ Baby Cakes Sounds @ Baby Cakes

Follow on MiLB First Pitch  https //stza.co/+whIz-1H

Shop  https //stza.co/+whIz-3P

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Sounds @ Baby Cakes
END:VALARM
DTSTART:20180830T000000Z
DTEND:20180830T030000Z
UID:htUJLJEaLbpyA1Ot2cNrQYJt@stanza.co
SUMMARY:Sounds @ Baby Cakes
DESCRIPTION:Sounds @ Baby Cakes\n\nFollow on MiLB First Pitch: https://stza.co/+whIz-1H\n\nShop: https://stza.co/+whIz-3P\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Sounds @ Baby Cakes
<2018-08-30 Thu 19:00-22:00>
:PROPERTIES:
:ID:       Gza31JNf_g2FcqOGUN8wO0S-@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Sounds @ Baby Cakes Sounds @ Baby Cakes

Follow on MiLB First Pitch  https //stza.co/+whIA-31

Shop  https //stza.co/+whIA-2R

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Sounds @ Baby Cakes
END:VALARM
DTSTART:20180831T000000Z
DTEND:20180831T030000Z
UID:Gza31JNf_g2FcqOGUN8wO0S-@stanza.co
SUMMARY:Sounds @ Baby Cakes
DESCRIPTION:Sounds @ Baby Cakes\n\nFollow on MiLB First Pitch: https://stza.co/+whIA-31\n\nShop: https://stza.co/+whIA-2R\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Sounds vs. Redbirds
<2018-08-31 Fri 19:05-22:05>
:PROPERTIES:
:ID:       SIelejngh_AYY6TKepQLBkZ_@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Sounds vs. Redbirds Sounds vs. Redbirds

Follow on MiLB First Pitch  https //stza.co/+whIk-1M

Shop  https //stza.co/+whIk-R

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Sounds vs. Redbirds
END:VALARM
DTSTART:20180901T000500Z
DTEND:20180901T030500Z
UID:SIelejngh_AYY6TKepQLBkZ_@stanza.co
SUMMARY:Sounds vs. Redbirds
DESCRIPTION:Sounds vs. Redbirds\n\nFollow on MiLB First Pitch: https://stza.co/+whIk-1M\n\nShop: https://stza.co/+whIk-R\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Sounds vs. Redbirds
<2018-09-01 Sat 19:05-22:05>
:PROPERTIES:
:ID:       NjKVjyybwAqiBf8z9Sz47Cg_@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Sounds vs. Redbirds Sounds vs. Redbirds

Follow on MiLB First Pitch  https //stza.co/+whIl-1I

Shop  https //stza.co/+whIl-V

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Sounds vs. Redbirds
END:VALARM
DTSTART:20180902T000500Z
DTEND:20180902T030500Z
UID:NjKVjyybwAqiBf8z9Sz47Cg_@stanza.co
SUMMARY:Sounds vs. Redbirds
DESCRIPTION:Sounds vs. Redbirds\n\nFollow on MiLB First Pitch: https://stza.co/+whIl-1I\n\nShop: https://stza.co/+whIl-V\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Sounds vs. Redbirds
<2018-09-02 Sun 18:15-21:15>
:PROPERTIES:
:ID:       nFGniRCoAZihW_n3Dz2d2gXL@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Sounds vs. Redbirds Sounds vs. Redbirds

Follow on MiLB First Pitch  https //stza.co/+whIo-1s

Shop  https //stza.co/+whIo-2o

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Sounds vs. Redbirds
END:VALARM
DTSTART:20180902T231500Z
DTEND:20180903T021500Z
UID:nFGniRCoAZihW_n3Dz2d2gXL@stanza.co
SUMMARY:Sounds vs. Redbirds
DESCRIPTION:Sounds vs. Redbirds\n\nFollow on MiLB First Pitch: https://stza.co/+whIo-1s\n\nShop: https://stza.co/+whIo-2o\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
* Sounds vs. Redbirds
<2018-09-03 Mon 12:05-15:05>
:PROPERTIES:
:ID:       mtn8m6aSo-NS6vvuIWWeONyG@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Sounds vs. Redbirds Sounds vs. Redbirds

Follow on MiLB First Pitch  https //stza.co/+whIp-2t

Shop  https //stza.co/+whIp-3e

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Sounds vs. Redbirds
END:VALARM
DTSTART:20180903T170500Z
DTEND:20180903T200500Z
UID:mtn8m6aSo-NS6vvuIWWeONyG@stanza.co
SUMMARY:Sounds vs. Redbirds
DESCRIPTION:Sounds vs. Redbirds\n\nFollow on MiLB First Pitch: https://stza.co/+whIp-2t\n\nShop: https://stza.co/+whIp-3e\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144546Z
LAST-MODIFIED:20180213T144546Z
TRANSP:OPAQUE
END:VEVENT
