#+TITLE:       Main Google calendar entries
#+AUTHOR:      Eric S Fraga
#+EMAIL:       e.fraga@ucl.ac.uk
#+DESCRIPTION: converted using the ical2org awk script
#+CATEGORY:    google
#+STARTUP:     hidestars
#+STARTUP:     overview

* COMMENT original iCal preamble

* Raptors @ Chukars
<2018-06-15 Fri 20:15-23:15>
:PROPERTIES:
:ID:       1eShaRtXPpRZLKey2hOlQNJ6@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Raptors @ Chukars Raptors @ Chukars

Follow on MiLB First Pitch  https //stza.co/+xZW2-2z

Shop  https //stza.co/+xZW2-s

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Raptors @ Chukars
END:VALARM
DTSTART:20180616T011500Z
DTEND:20180616T041500Z
UID:1eShaRtXPpRZLKey2hOlQNJ6@stanza.co
SUMMARY:Raptors @ Chukars
DESCRIPTION:Raptors @ Chukars\n\nFollow on MiLB First Pitch: https://stza.co/+xZW2-2z\n\nShop: https://stza.co/+xZW2-s\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144548Z
LAST-MODIFIED:20180213T144548Z
TRANSP:OPAQUE
END:VEVENT
* Raptors @ Chukars
<2018-06-16 Sat 20:15-23:15>
:PROPERTIES:
:ID:       hbQyG9MChCXxI2G30szezgJy@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Raptors @ Chukars Raptors @ Chukars

Follow on MiLB First Pitch  https //stza.co/+xZW3-b

Shop  https //stza.co/+xZW3-11

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Raptors @ Chukars
END:VALARM
DTSTART:20180617T011500Z
DTEND:20180617T041500Z
UID:hbQyG9MChCXxI2G30szezgJy@stanza.co
SUMMARY:Raptors @ Chukars
DESCRIPTION:Raptors @ Chukars\n\nFollow on MiLB First Pitch: https://stza.co/+xZW3-b\n\nShop: https://stza.co/+xZW3-11\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144548Z
LAST-MODIFIED:20180213T144548Z
TRANSP:OPAQUE
END:VEVENT
* Raptors @ Chukars
<2018-06-17 Sun 17:00-20:00>
:PROPERTIES:
:ID:       og0rGenXaa4Lo3JHXH6ja0Ka@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Raptors @ Chukars Raptors @ Chukars

Follow on MiLB First Pitch  https //stza.co/+xZW4-1K

Shop  https //stza.co/+xZW4-2g

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Raptors @ Chukars
END:VALARM
DTSTART:20180617T220000Z
DTEND:20180618T010000Z
UID:og0rGenXaa4Lo3JHXH6ja0Ka@stanza.co
SUMMARY:Raptors @ Chukars
DESCRIPTION:Raptors @ Chukars\n\nFollow on MiLB First Pitch: https://stza.co/+xZW4-1K\n\nShop: https://stza.co/+xZW4-2g\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144548Z
LAST-MODIFIED:20180213T144548Z
TRANSP:OPAQUE
END:VEVENT
* Raptors @ Chukars
<2018-06-18 Mon 20:15-23:15>
:PROPERTIES:
:ID:       ZKJCRn51BeR0Ja3M-Yjoyl8e@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Raptors @ Chukars Raptors @ Chukars

Follow on MiLB First Pitch  https //stza.co/+xZW5-3E

Shop  https //stza.co/+xZW5-28

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Raptors @ Chukars
END:VALARM
DTSTART:20180619T011500Z
DTEND:20180619T041500Z
UID:ZKJCRn51BeR0Ja3M-Yjoyl8e@stanza.co
SUMMARY:Raptors @ Chukars
DESCRIPTION:Raptors @ Chukars\n\nFollow on MiLB First Pitch: https://stza.co/+xZW5-3E\n\nShop: https://stza.co/+xZW5-28\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144548Z
LAST-MODIFIED:20180213T144548Z
TRANSP:OPAQUE
END:VEVENT
* Raptors vs. Owlz
<2018-06-19 Tue 20:00-23:00>
:PROPERTIES:
:ID:       q3ICJpfX2CiCfk--1vpl8Aqx@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Raptors vs. Owlz Raptors vs. Owlz

Follow on MiLB First Pitch  https //stza.co/+x$8e-2o

Shop  https //stza.co/+x$8e-2l

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Raptors vs. Owlz
END:VALARM
DTSTART:20180620T010000Z
DTEND:20180620T040000Z
UID:q3ICJpfX2CiCfk--1vpl8Aqx@stanza.co
SUMMARY:Raptors vs. Owlz
DESCRIPTION:Raptors vs. Owlz\n\nFollow on MiLB First Pitch: https://stza.co/+x$8e-2o\n\nShop: https://stza.co/+x$8e-2l\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144548Z
LAST-MODIFIED:20180213T144548Z
TRANSP:OPAQUE
END:VEVENT
* Raptors vs. Owlz
<2018-06-20 Wed 20:00-23:00>
:PROPERTIES:
:ID:       VgqINnFTn8S1B2xpdVpk5vYU@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Raptors vs. Owlz Raptors vs. Owlz

Follow on MiLB First Pitch  https //stza.co/+x$8g-3s

Shop  https //stza.co/+x$8g-2c

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Raptors vs. Owlz
END:VALARM
DTSTART:20180621T010000Z
DTEND:20180621T040000Z
UID:VgqINnFTn8S1B2xpdVpk5vYU@stanza.co
SUMMARY:Raptors vs. Owlz
DESCRIPTION:Raptors vs. Owlz\n\nFollow on MiLB First Pitch: https://stza.co/+x$8g-3s\n\nShop: https://stza.co/+x$8g-2c\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144548Z
LAST-MODIFIED:20180213T144548Z
TRANSP:OPAQUE
END:VEVENT
* Raptors @ Owlz
<2018-06-21 Thu 20:05-23:05>
:PROPERTIES:
:ID:       nEuWVV9JKY_dY_ZZXpeheM7w@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Raptors @ Owlz Raptors @ Owlz

Follow on MiLB First Pitch  https //stza.co/+xPBu-2P

Shop  https //stza.co/+xPBu-Z

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Raptors @ Owlz
END:VALARM
DTSTART:20180622T010500Z
DTEND:20180622T040500Z
UID:nEuWVV9JKY_dY_ZZXpeheM7w@stanza.co
SUMMARY:Raptors @ Owlz
DESCRIPTION:Raptors @ Owlz\n\nFollow on MiLB First Pitch: https://stza.co/+xPBu-2P\n\nShop: https://stza.co/+xPBu-Z\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144548Z
LAST-MODIFIED:20180213T144548Z
TRANSP:OPAQUE
END:VEVENT
* Raptors @ Owlz
<2018-06-22 Fri 20:05-23:05>
:PROPERTIES:
:ID:       YrPFNSw6JKES6O7lwTw0HH10@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Raptors @ Owlz Raptors @ Owlz

Follow on MiLB First Pitch  https //stza.co/+xPBv-3R

Shop  https //stza.co/+xPBv-2x

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Raptors @ Owlz
END:VALARM
DTSTART:20180623T010500Z
DTEND:20180623T040500Z
UID:YrPFNSw6JKES6O7lwTw0HH10@stanza.co
SUMMARY:Raptors @ Owlz
DESCRIPTION:Raptors @ Owlz\n\nFollow on MiLB First Pitch: https://stza.co/+xPBv-3R\n\nShop: https://stza.co/+xPBv-2x\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144548Z
LAST-MODIFIED:20180213T144548Z
TRANSP:OPAQUE
END:VEVENT
* Raptors vs. Rockies
<2018-06-23 Sat 20:00-23:00>
:PROPERTIES:
:ID:       LzdPkOwkaMbi0uFCsLMwulx-@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Raptors vs. Rockies Raptors vs. Rockies

Follow on MiLB First Pitch  https //stza.co/+x$8i-2x

Shop  https //stza.co/+x$8i-36

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Raptors vs. Rockies
END:VALARM
DTSTART:20180624T010000Z
DTEND:20180624T040000Z
UID:LzdPkOwkaMbi0uFCsLMwulx-@stanza.co
SUMMARY:Raptors vs. Rockies
DESCRIPTION:Raptors vs. Rockies\n\nFollow on MiLB First Pitch: https://stza.co/+x$8i-2x\n\nShop: https://stza.co/+x$8i-36\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144548Z
LAST-MODIFIED:20180213T144548Z
TRANSP:OPAQUE
END:VEVENT
* Raptors vs. Rockies
<2018-06-24 Sun 17:00-20:00>
:PROPERTIES:
:ID:       humxOkEK7SB9k2BrMBfd48AG@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Raptors vs. Rockies Raptors vs. Rockies

Follow on MiLB First Pitch  https //stza.co/+x$8k-2K

Shop  https //stza.co/+x$8k-1K

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Raptors vs. Rockies
END:VALARM
DTSTART:20180624T220000Z
DTEND:20180625T010000Z
UID:humxOkEK7SB9k2BrMBfd48AG@stanza.co
SUMMARY:Raptors vs. Rockies
DESCRIPTION:Raptors vs. Rockies\n\nFollow on MiLB First Pitch: https://stza.co/+x$8k-2K\n\nShop: https://stza.co/+x$8k-1K\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144548Z
LAST-MODIFIED:20180213T144548Z
TRANSP:OPAQUE
END:VEVENT
* Raptors vs. Rockies
<2018-06-25 Mon 20:00-23:00>
:PROPERTIES:
:ID:       uPj_g3Wqs654XuEnZCfqI8kZ@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Raptors vs. Rockies Raptors vs. Rockies

Follow on MiLB First Pitch  https //stza.co/+x$8m-D

Shop  https //stza.co/+x$8m-3Q

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Raptors vs. Rockies
END:VALARM
DTSTART:20180626T010000Z
DTEND:20180626T040000Z
UID:uPj_g3Wqs654XuEnZCfqI8kZ@stanza.co
SUMMARY:Raptors vs. Rockies
DESCRIPTION:Raptors vs. Rockies\n\nFollow on MiLB First Pitch: https://stza.co/+x$8m-D\n\nShop: https://stza.co/+x$8m-3Q\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144548Z
LAST-MODIFIED:20180213T144548Z
TRANSP:OPAQUE
END:VEVENT
* Raptors vs. Owlz
<2018-06-26 Tue 20:00-23:00>
:PROPERTIES:
:ID:       UMjEUTDm27aCTft_Unfe9Srd@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Raptors vs. Owlz Raptors vs. Owlz

Follow on MiLB First Pitch  https //stza.co/+x$8o-2b

Shop  https //stza.co/+x$8o-3A

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Raptors vs. Owlz
END:VALARM
DTSTART:20180627T010000Z
DTEND:20180627T040000Z
UID:UMjEUTDm27aCTft_Unfe9Srd@stanza.co
SUMMARY:Raptors vs. Owlz
DESCRIPTION:Raptors vs. Owlz\n\nFollow on MiLB First Pitch: https://stza.co/+x$8o-2b\n\nShop: https://stza.co/+x$8o-3A\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144548Z
LAST-MODIFIED:20180213T144548Z
TRANSP:OPAQUE
END:VEVENT
* Raptors vs. Owlz
<2018-06-27 Wed 20:00-23:00>
:PROPERTIES:
:ID:       sul5quJKnl1ZvOaqQX1Dh40V@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Raptors vs. Owlz Raptors vs. Owlz

Follow on MiLB First Pitch  https //stza.co/+x$8q-28

Shop  https //stza.co/+x$8q-3d

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Raptors vs. Owlz
END:VALARM
DTSTART:20180628T010000Z
DTEND:20180628T040000Z
UID:sul5quJKnl1ZvOaqQX1Dh40V@stanza.co
SUMMARY:Raptors vs. Owlz
DESCRIPTION:Raptors vs. Owlz\n\nFollow on MiLB First Pitch: https://stza.co/+x$8q-28\n\nShop: https://stza.co/+x$8q-3d\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144548Z
LAST-MODIFIED:20180213T144548Z
TRANSP:OPAQUE
END:VEVENT
* Raptors @ Owlz
<2018-06-28 Thu 20:05-23:05>
:PROPERTIES:
:ID:       dLnelPcXEMt1StjkQEzV5coa@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Raptors @ Owlz Raptors @ Owlz

Follow on MiLB First Pitch  https //stza.co/+xPBw-15

Shop  https //stza.co/+xPBw-2c

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Raptors @ Owlz
END:VALARM
DTSTART:20180629T010500Z
DTEND:20180629T040500Z
UID:dLnelPcXEMt1StjkQEzV5coa@stanza.co
SUMMARY:Raptors @ Owlz
DESCRIPTION:Raptors @ Owlz\n\nFollow on MiLB First Pitch: https://stza.co/+xPBw-15\n\nShop: https://stza.co/+xPBw-2c\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144548Z
LAST-MODIFIED:20180213T144548Z
TRANSP:OPAQUE
END:VEVENT
* Raptors @ Owlz
<2018-06-29 Fri 20:05-23:05>
:PROPERTIES:
:ID:       W1pSq1V8UMGpoYmwaxtJY_0V@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Raptors @ Owlz Raptors @ Owlz

Follow on MiLB First Pitch  https //stza.co/+xPBx-1b

Shop  https //stza.co/+xPBx-3d

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Raptors @ Owlz
END:VALARM
DTSTART:20180630T010500Z
DTEND:20180630T040500Z
UID:W1pSq1V8UMGpoYmwaxtJY_0V@stanza.co
SUMMARY:Raptors @ Owlz
DESCRIPTION:Raptors @ Owlz\n\nFollow on MiLB First Pitch: https://stza.co/+xPBx-1b\n\nShop: https://stza.co/+xPBx-3d\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144548Z
LAST-MODIFIED:20180213T144548Z
TRANSP:OPAQUE
END:VEVENT
* Raptors vs. Chukars
<2018-06-30 Sat 20:00-23:00>
:PROPERTIES:
:ID:       iFDvExKmzTzsQ3VWZ-4KMYV2@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Raptors vs. Chukars Raptors vs. Chukars

Follow on MiLB First Pitch  https //stza.co/+x$8r-3D

Shop  https //stza.co/+x$8r-E

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Raptors vs. Chukars
END:VALARM
DTSTART:20180701T010000Z
DTEND:20180701T040000Z
UID:iFDvExKmzTzsQ3VWZ-4KMYV2@stanza.co
SUMMARY:Raptors vs. Chukars
DESCRIPTION:Raptors vs. Chukars\n\nFollow on MiLB First Pitch: https://stza.co/+x$8r-3D\n\nShop: https://stza.co/+x$8r-E\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144548Z
LAST-MODIFIED:20180213T144548Z
TRANSP:OPAQUE
END:VEVENT
* Raptors vs. Chukars
<2018-07-01 Sun 17:00-20:00>
:PROPERTIES:
:ID:       XaBkZeOzbUIG5ceXE7FaDH1e@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Raptors vs. Chukars Raptors vs. Chukars

Follow on MiLB First Pitch  https //stza.co/+x$8u-2m

Shop  https //stza.co/+x$8u-1M

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Raptors vs. Chukars
END:VALARM
DTSTART:20180701T220000Z
DTEND:20180702T010000Z
UID:XaBkZeOzbUIG5ceXE7FaDH1e@stanza.co
SUMMARY:Raptors vs. Chukars
DESCRIPTION:Raptors vs. Chukars\n\nFollow on MiLB First Pitch: https://stza.co/+x$8u-2m\n\nShop: https://stza.co/+x$8u-1M\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144548Z
LAST-MODIFIED:20180213T144548Z
TRANSP:OPAQUE
END:VEVENT
* Raptors vs. Chukars
<2018-07-02 Mon 20:00-23:00>
:PROPERTIES:
:ID:       T1KkZBkI2L7QB2Nsro5IPNcO@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Raptors vs. Chukars Raptors vs. Chukars

Follow on MiLB First Pitch  https //stza.co/+x$8w-2n

Shop  https //stza.co/+x$8w-1s

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Raptors vs. Chukars
END:VALARM
DTSTART:20180703T010000Z
DTEND:20180703T040000Z
UID:T1KkZBkI2L7QB2Nsro5IPNcO@stanza.co
SUMMARY:Raptors vs. Chukars
DESCRIPTION:Raptors vs. Chukars\n\nFollow on MiLB First Pitch: https://stza.co/+x$8w-2n\n\nShop: https://stza.co/+x$8w-1s\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144548Z
LAST-MODIFIED:20180213T144548Z
TRANSP:OPAQUE
END:VEVENT
* Raptors vs. Chukars
<2018-07-03 Tue 20:00-23:00>
:PROPERTIES:
:ID:       aANdglu9QLGSSDqGwuS14AFJ@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Raptors vs. Chukars Raptors vs. Chukars

Follow on MiLB First Pitch  https //stza.co/+x$8x-2i

Shop  https //stza.co/+x$8x-24

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Raptors vs. Chukars
END:VALARM
DTSTART:20180704T010000Z
DTEND:20180704T040000Z
UID:aANdglu9QLGSSDqGwuS14AFJ@stanza.co
SUMMARY:Raptors vs. Chukars
DESCRIPTION:Raptors vs. Chukars\n\nFollow on MiLB First Pitch: https://stza.co/+x$8x-2i\n\nShop: https://stza.co/+x$8x-24\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144548Z
LAST-MODIFIED:20180213T144548Z
TRANSP:OPAQUE
END:VEVENT
* Raptors @ Rockies
<2018-07-04 Wed 19:40-22:40>
:PROPERTIES:
:ID:       zU4cUaqyw9eF1GyWhTJ6TFD4@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Raptors @ Rockies Raptors @ Rockies

Follow on MiLB First Pitch  https //stza.co/+xJ8p-1E

Shop  https //stza.co/+xJ8p-1l

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Raptors @ Rockies
END:VALARM
DTSTART:20180705T004000Z
DTEND:20180705T034000Z
UID:zU4cUaqyw9eF1GyWhTJ6TFD4@stanza.co
SUMMARY:Raptors @ Rockies
DESCRIPTION:Raptors @ Rockies\n\nFollow on MiLB First Pitch: https://stza.co/+xJ8p-1E\n\nShop: https://stza.co/+xJ8p-1l\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144548Z
LAST-MODIFIED:20180213T144548Z
TRANSP:OPAQUE
END:VEVENT
* Raptors @ Rockies
<2018-07-05 Thu 19:40-22:40>
:PROPERTIES:
:ID:       1libH8Q_Eix-4Y0GGK_nE1jw@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Raptors @ Rockies Raptors @ Rockies

Follow on MiLB First Pitch  https //stza.co/+xJ8q-18

Shop  https //stza.co/+xJ8q-1T

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Raptors @ Rockies
END:VALARM
DTSTART:20180706T004000Z
DTEND:20180706T034000Z
UID:1libH8Q_Eix-4Y0GGK_nE1jw@stanza.co
SUMMARY:Raptors @ Rockies
DESCRIPTION:Raptors @ Rockies\n\nFollow on MiLB First Pitch: https://stza.co/+xJ8q-18\n\nShop: https://stza.co/+xJ8q-1T\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144548Z
LAST-MODIFIED:20180213T144548Z
TRANSP:OPAQUE
END:VEVENT
* Raptors @ Rockies
<2018-07-06 Fri 19:40-22:40>
:PROPERTIES:
:ID:       Cv6RaGCHZtIdCLSMhMLUPq95@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Raptors @ Rockies Raptors @ Rockies

Follow on MiLB First Pitch  https //stza.co/+xJ8r-2x

Shop  https //stza.co/+xJ8r-2y

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Raptors @ Rockies
END:VALARM
DTSTART:20180707T004000Z
DTEND:20180707T034000Z
UID:Cv6RaGCHZtIdCLSMhMLUPq95@stanza.co
SUMMARY:Raptors @ Rockies
DESCRIPTION:Raptors @ Rockies\n\nFollow on MiLB First Pitch: https://stza.co/+xJ8r-2x\n\nShop: https://stza.co/+xJ8r-2y\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144548Z
LAST-MODIFIED:20180213T144548Z
TRANSP:OPAQUE
END:VEVENT
* Raptors @ Rockies
<2018-07-07 Sat 19:40-22:40>
:PROPERTIES:
:ID:       aiytkGqEW5YxYk9Ri9Eapqsx@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Raptors @ Rockies Raptors @ Rockies

Follow on MiLB First Pitch  https //stza.co/+xJ8s-2k

Shop  https //stza.co/+xJ8s-31

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Raptors @ Rockies
END:VALARM
DTSTART:20180708T004000Z
DTEND:20180708T034000Z
UID:aiytkGqEW5YxYk9Ri9Eapqsx@stanza.co
SUMMARY:Raptors @ Rockies
DESCRIPTION:Raptors @ Rockies\n\nFollow on MiLB First Pitch: https://stza.co/+xJ8s-2k\n\nShop: https://stza.co/+xJ8s-31\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144548Z
LAST-MODIFIED:20180213T144548Z
TRANSP:OPAQUE
END:VEVENT
* Raptors @ Rockies
<2018-07-08 Sun 18:00-21:00>
:PROPERTIES:
:ID:       hCRT27yKT-QndWbfz5pDNMT-@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Raptors @ Rockies Raptors @ Rockies

Follow on MiLB First Pitch  https //stza.co/+xJ8t-2u

Shop  https //stza.co/+xJ8t-3B

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Raptors @ Rockies
END:VALARM
DTSTART:20180708T230000Z
DTEND:20180709T020000Z
UID:hCRT27yKT-QndWbfz5pDNMT-@stanza.co
SUMMARY:Raptors @ Rockies
DESCRIPTION:Raptors @ Rockies\n\nFollow on MiLB First Pitch: https://stza.co/+xJ8t-2u\n\nShop: https://stza.co/+xJ8t-3B\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144548Z
LAST-MODIFIED:20180213T144548Z
TRANSP:OPAQUE
END:VEVENT
* Raptors vs. Osprey
<2018-07-10 Tue 20:00-23:00>
:PROPERTIES:
:ID:       NcdLfRgCV_KXq5A6McmqIMjX@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Raptors vs. Osprey Raptors vs. Osprey

Follow on MiLB First Pitch  https //stza.co/+x$8z-2t

Shop  https //stza.co/+x$8z-3E

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Raptors vs. Osprey
END:VALARM
DTSTART:20180711T010000Z
DTEND:20180711T040000Z
UID:NcdLfRgCV_KXq5A6McmqIMjX@stanza.co
SUMMARY:Raptors vs. Osprey
DESCRIPTION:Raptors vs. Osprey\n\nFollow on MiLB First Pitch: https://stza.co/+x$8z-2t\n\nShop: https://stza.co/+x$8z-3E\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144548Z
LAST-MODIFIED:20180213T144548Z
TRANSP:OPAQUE
END:VEVENT
* Raptors vs. Osprey
<2018-07-11 Wed 20:00-23:00>
:PROPERTIES:
:ID:       xd2pVun-QBcgvBYdh7ZHyYbV@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Raptors vs. Osprey Raptors vs. Osprey

Follow on MiLB First Pitch  https //stza.co/+x$8C-2i

Shop  https //stza.co/+x$8C-2e

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Raptors vs. Osprey
END:VALARM
DTSTART:20180712T010000Z
DTEND:20180712T040000Z
UID:xd2pVun-QBcgvBYdh7ZHyYbV@stanza.co
SUMMARY:Raptors vs. Osprey
DESCRIPTION:Raptors vs. Osprey\n\nFollow on MiLB First Pitch: https://stza.co/+x$8C-2i\n\nShop: https://stza.co/+x$8C-2e\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144548Z
LAST-MODIFIED:20180213T144548Z
TRANSP:OPAQUE
END:VEVENT
* Raptors vs. Osprey
<2018-07-12 Thu 20:00-23:00>
:PROPERTIES:
:ID:       6V54GanIV_dmHK8WlucX1yIM@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Raptors vs. Osprey Raptors vs. Osprey

Follow on MiLB First Pitch  https //stza.co/+x$8E-1d

Shop  https //stza.co/+x$8E-3q

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Raptors vs. Osprey
END:VALARM
DTSTART:20180713T010000Z
DTEND:20180713T040000Z
UID:6V54GanIV_dmHK8WlucX1yIM@stanza.co
SUMMARY:Raptors vs. Osprey
DESCRIPTION:Raptors vs. Osprey\n\nFollow on MiLB First Pitch: https://stza.co/+x$8E-1d\n\nShop: https://stza.co/+x$8E-3q\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144548Z
LAST-MODIFIED:20180213T144548Z
TRANSP:OPAQUE
END:VEVENT
* Raptors vs. Osprey
<2018-07-13 Fri 20:00-23:00>
:PROPERTIES:
:ID:       BFtpnms2QCz6GY233N8wzd4P@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Raptors vs. Osprey Raptors vs. Osprey

Follow on MiLB First Pitch  https //stza.co/+x$8G-18

Shop  https //stza.co/+x$8G-2t

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Raptors vs. Osprey
END:VALARM
DTSTART:20180714T010000Z
DTEND:20180714T040000Z
UID:BFtpnms2QCz6GY233N8wzd4P@stanza.co
SUMMARY:Raptors vs. Osprey
DESCRIPTION:Raptors vs. Osprey\n\nFollow on MiLB First Pitch: https://stza.co/+x$8G-18\n\nShop: https://stza.co/+x$8G-2t\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144548Z
LAST-MODIFIED:20180213T144548Z
TRANSP:OPAQUE
END:VEVENT
* Raptors vs. Brewers
<2018-07-14 Sat 20:00-23:00>
:PROPERTIES:
:ID:       iyGIdCOfOczTJJam7Q_XWrRQ@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Raptors vs. Brewers Raptors vs. Brewers

Follow on MiLB First Pitch  https //stza.co/+x$8I-2D

Shop  https //stza.co/+x$8I-1I

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Raptors vs. Brewers
END:VALARM
DTSTART:20180715T010000Z
DTEND:20180715T040000Z
UID:iyGIdCOfOczTJJam7Q_XWrRQ@stanza.co
SUMMARY:Raptors vs. Brewers
DESCRIPTION:Raptors vs. Brewers\n\nFollow on MiLB First Pitch: https://stza.co/+x$8I-2D\n\nShop: https://stza.co/+x$8I-1I\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144548Z
LAST-MODIFIED:20180213T144548Z
TRANSP:OPAQUE
END:VEVENT
* Raptors vs. Brewers
<2018-07-15 Sun 17:00-20:00>
:PROPERTIES:
:ID:       6F31GZnYS1E9RRBp2waEjGaI@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Raptors vs. Brewers Raptors vs. Brewers

Follow on MiLB First Pitch  https //stza.co/+x$8K-V

Shop  https //stza.co/+x$8K-8

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Raptors vs. Brewers
END:VALARM
DTSTART:20180715T220000Z
DTEND:20180716T010000Z
UID:6F31GZnYS1E9RRBp2waEjGaI@stanza.co
SUMMARY:Raptors vs. Brewers
DESCRIPTION:Raptors vs. Brewers\n\nFollow on MiLB First Pitch: https://stza.co/+x$8K-V\n\nShop: https://stza.co/+x$8K-8\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144548Z
LAST-MODIFIED:20180213T144548Z
TRANSP:OPAQUE
END:VEVENT
* Raptors vs. Brewers
<2018-07-16 Mon 20:00-23:00>
:PROPERTIES:
:ID:       mFNoi_GVGZQFUqOhItPsC-hR@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Raptors vs. Brewers Raptors vs. Brewers

Follow on MiLB First Pitch  https //stza.co/+x$8M-2B

Shop  https //stza.co/+x$8M-T

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Raptors vs. Brewers
END:VALARM
DTSTART:20180717T010000Z
DTEND:20180717T040000Z
UID:mFNoi_GVGZQFUqOhItPsC-hR@stanza.co
SUMMARY:Raptors vs. Brewers
DESCRIPTION:Raptors vs. Brewers\n\nFollow on MiLB First Pitch: https://stza.co/+x$8M-2B\n\nShop: https://stza.co/+x$8M-T\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144548Z
LAST-MODIFIED:20180213T144548Z
TRANSP:OPAQUE
END:VEVENT
* Raptors @ Osprey
<2018-07-18 Wed>--<2018-07-17 Tue>
:PROPERTIES:
:ID:       2woXhabg2oRDr2QQhVuwGEV_@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Raptors @ Osprey Raptors @ Osprey

Follow on MiLB First Pitch  https //stza.co/+xCBr-17

Shop  https //stza.co/+xCBr-K

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Raptors @ Osprey
END:VALARM
DTSTART;VALUE=DATE:20180718
DTEND;VALUE=DATE:20180718
UID:2woXhabg2oRDr2QQhVuwGEV_@stanza.co
SUMMARY:Raptors @ Osprey
DESCRIPTION:Raptors @ Osprey\n\nFollow on MiLB First Pitch: https://stza.co/+xCBr-17\n\nShop: https://stza.co/+xCBr-K\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144548Z
LAST-MODIFIED:20180213T144548Z
TRANSP:OPAQUE
END:VEVENT
* Raptors @ Osprey
<2018-07-19 Thu>--<2018-07-18 Wed>
:PROPERTIES:
:ID:       j8YDLY6Q38l1GTKcZLT7OsK3@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Raptors @ Osprey Raptors @ Osprey

Follow on MiLB First Pitch  https //stza.co/+xCBs-1Y

Shop  https //stza.co/+xCBs-G

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Raptors @ Osprey
END:VALARM
DTSTART;VALUE=DATE:20180719
DTEND;VALUE=DATE:20180719
UID:j8YDLY6Q38l1GTKcZLT7OsK3@stanza.co
SUMMARY:Raptors @ Osprey
DESCRIPTION:Raptors @ Osprey\n\nFollow on MiLB First Pitch: https://stza.co/+xCBs-1Y\n\nShop: https://stza.co/+xCBs-G\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144548Z
LAST-MODIFIED:20180213T144548Z
TRANSP:OPAQUE
END:VEVENT
* Raptors @ Osprey
<2018-07-20 Fri>--<2018-07-19 Thu>
:PROPERTIES:
:ID:       IrH7r9VimMzJrdQTZE9hnhtl@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Raptors @ Osprey Raptors @ Osprey

Follow on MiLB First Pitch  https //stza.co/+xCBt-1e

Shop  https //stza.co/+xCBt-3p

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Raptors @ Osprey
END:VALARM
DTSTART;VALUE=DATE:20180720
DTEND;VALUE=DATE:20180720
UID:IrH7r9VimMzJrdQTZE9hnhtl@stanza.co
SUMMARY:Raptors @ Osprey
DESCRIPTION:Raptors @ Osprey\n\nFollow on MiLB First Pitch: https://stza.co/+xCBt-1e\n\nShop: https://stza.co/+xCBt-3p\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144548Z
LAST-MODIFIED:20180213T144548Z
TRANSP:OPAQUE
END:VEVENT
* Raptors @ Brewers
<2018-07-21 Sat>--<2018-07-20 Fri>
:PROPERTIES:
:ID:       UlO9x03pFmH7BfTKK_QSoLyl@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Raptors @ Brewers Raptors @ Brewers

Follow on MiLB First Pitch  https //stza.co/+xCBa-1J

Shop  https //stza.co/+xCBa-1V

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Raptors @ Brewers
END:VALARM
DTSTART;VALUE=DATE:20180721
DTEND;VALUE=DATE:20180721
UID:UlO9x03pFmH7BfTKK_QSoLyl@stanza.co
SUMMARY:Raptors @ Brewers
DESCRIPTION:Raptors @ Brewers\n\nFollow on MiLB First Pitch: https://stza.co/+xCBa-1J\n\nShop: https://stza.co/+xCBa-1V\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144548Z
LAST-MODIFIED:20180213T144548Z
TRANSP:OPAQUE
END:VEVENT
* Raptors @ Brewers
<2018-07-22 Sun>--<2018-07-21 Sat>
:PROPERTIES:
:ID:       G3q5sNwMT9zxY8pNsZBLYN7q@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Raptors @ Brewers Raptors @ Brewers

Follow on MiLB First Pitch  https //stza.co/+xCBb-2$

Shop  https //stza.co/+xCBb-3a

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Raptors @ Brewers
END:VALARM
DTSTART;VALUE=DATE:20180722
DTEND;VALUE=DATE:20180722
UID:G3q5sNwMT9zxY8pNsZBLYN7q@stanza.co
SUMMARY:Raptors @ Brewers
DESCRIPTION:Raptors @ Brewers\n\nFollow on MiLB First Pitch: https://stza.co/+xCBb-2$\n\nShop: https://stza.co/+xCBb-3a\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144548Z
LAST-MODIFIED:20180213T144548Z
TRANSP:OPAQUE
END:VEVENT
* Raptors @ Brewers
<2018-07-23 Mon>--<2018-07-22 Sun>
:PROPERTIES:
:ID:       fiK0g4XKMqprxApuqKn9Jb4T@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Raptors @ Brewers Raptors @ Brewers

Follow on MiLB First Pitch  https //stza.co/+xCBc-1P

Shop  https //stza.co/+xCBc-1W

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Raptors @ Brewers
END:VALARM
DTSTART;VALUE=DATE:20180723
DTEND;VALUE=DATE:20180723
UID:fiK0g4XKMqprxApuqKn9Jb4T@stanza.co
SUMMARY:Raptors @ Brewers
DESCRIPTION:Raptors @ Brewers\n\nFollow on MiLB First Pitch: https://stza.co/+xCBc-1P\n\nShop: https://stza.co/+xCBc-1W\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144548Z
LAST-MODIFIED:20180213T144548Z
TRANSP:OPAQUE
END:VEVENT
* Raptors @ Brewers
<2018-07-24 Tue>--<2018-07-23 Mon>
:PROPERTIES:
:ID:       XYKzZTkMf8baNi_pYX-PLi4W@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Raptors @ Brewers Raptors @ Brewers

Follow on MiLB First Pitch  https //stza.co/+xCBe-23

Shop  https //stza.co/+xCBe-3h

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Raptors @ Brewers
END:VALARM
DTSTART;VALUE=DATE:20180724
DTEND;VALUE=DATE:20180724
UID:XYKzZTkMf8baNi_pYX-PLi4W@stanza.co
SUMMARY:Raptors @ Brewers
DESCRIPTION:Raptors @ Brewers\n\nFollow on MiLB First Pitch: https://stza.co/+xCBe-23\n\nShop: https://stza.co/+xCBe-3h\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144548Z
LAST-MODIFIED:20180213T144548Z
TRANSP:OPAQUE
END:VEVENT
* Raptors vs. Rockies
<2018-07-25 Wed 20:00-23:00>
:PROPERTIES:
:ID:       MpXbcZc4fWoQWA5bLcXpb_Aa@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Raptors vs. Rockies Raptors vs. Rockies

Follow on MiLB First Pitch  https //stza.co/+x$8N-38

Shop  https //stza.co/+x$8N-B

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Raptors vs. Rockies
END:VALARM
DTSTART:20180726T010000Z
DTEND:20180726T040000Z
UID:MpXbcZc4fWoQWA5bLcXpb_Aa@stanza.co
SUMMARY:Raptors vs. Rockies
DESCRIPTION:Raptors vs. Rockies\n\nFollow on MiLB First Pitch: https://stza.co/+x$8N-38\n\nShop: https://stza.co/+x$8N-B\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144548Z
LAST-MODIFIED:20180213T144548Z
TRANSP:OPAQUE
END:VEVENT
* Raptors vs. Rockies
<2018-07-26 Thu 20:00-23:00>
:PROPERTIES:
:ID:       8sAZ8dp6dkx2i5yTp631P4yq@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Raptors vs. Rockies Raptors vs. Rockies

Follow on MiLB First Pitch  https //stza.co/+x$8Q-1U

Shop  https //stza.co/+x$8Q-10

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Raptors vs. Rockies
END:VALARM
DTSTART:20180727T010000Z
DTEND:20180727T040000Z
UID:8sAZ8dp6dkx2i5yTp631P4yq@stanza.co
SUMMARY:Raptors vs. Rockies
DESCRIPTION:Raptors vs. Rockies\n\nFollow on MiLB First Pitch: https://stza.co/+x$8Q-1U\n\nShop: https://stza.co/+x$8Q-10\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144548Z
LAST-MODIFIED:20180213T144548Z
TRANSP:OPAQUE
END:VEVENT
* Raptors vs. Rockies
<2018-07-27 Fri 20:00-23:00>
:PROPERTIES:
:ID:       37iJTnco1arJd_HzMgRohA13@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Raptors vs. Rockies Raptors vs. Rockies

Follow on MiLB First Pitch  https //stza.co/+x$8R-1S

Shop  https //stza.co/+x$8R-1t

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Raptors vs. Rockies
END:VALARM
DTSTART:20180728T010000Z
DTEND:20180728T040000Z
UID:37iJTnco1arJd_HzMgRohA13@stanza.co
SUMMARY:Raptors vs. Rockies
DESCRIPTION:Raptors vs. Rockies\n\nFollow on MiLB First Pitch: https://stza.co/+x$8R-1S\n\nShop: https://stza.co/+x$8R-1t\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144548Z
LAST-MODIFIED:20180213T144548Z
TRANSP:OPAQUE
END:VEVENT
* Raptors vs. Chukars
<2018-07-28 Sat 20:00-23:00>
:PROPERTIES:
:ID:       hNUWy5WhOhp4X92EyDAQ8GCQ@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Raptors vs. Chukars Raptors vs. Chukars

Follow on MiLB First Pitch  https //stza.co/+x$8U-Y

Shop  https //stza.co/+x$8U-1t

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Raptors vs. Chukars
END:VALARM
DTSTART:20180729T010000Z
DTEND:20180729T040000Z
UID:hNUWy5WhOhp4X92EyDAQ8GCQ@stanza.co
SUMMARY:Raptors vs. Chukars
DESCRIPTION:Raptors vs. Chukars\n\nFollow on MiLB First Pitch: https://stza.co/+x$8U-Y\n\nShop: https://stza.co/+x$8U-1t\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144548Z
LAST-MODIFIED:20180213T144548Z
TRANSP:OPAQUE
END:VEVENT
* Raptors vs. Chukars
<2018-07-29 Sun 17:00-20:00>
:PROPERTIES:
:ID:       pL1cElqvt9rYtGk9LOjKJ-1b@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Raptors vs. Chukars Raptors vs. Chukars

Follow on MiLB First Pitch  https //stza.co/+x$8V-3x

Shop  https //stza.co/+x$8V-1W

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Raptors vs. Chukars
END:VALARM
DTSTART:20180729T220000Z
DTEND:20180730T010000Z
UID:pL1cElqvt9rYtGk9LOjKJ-1b@stanza.co
SUMMARY:Raptors vs. Chukars
DESCRIPTION:Raptors vs. Chukars\n\nFollow on MiLB First Pitch: https://stza.co/+x$8V-3x\n\nShop: https://stza.co/+x$8V-1W\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144548Z
LAST-MODIFIED:20180213T144548Z
TRANSP:OPAQUE
END:VEVENT
* Raptors @ Rockies
<2018-07-30 Mon 19:40-22:40>
:PROPERTIES:
:ID:       9cty2FahLHD_qJNHX4Gdct5D@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Raptors @ Rockies Raptors @ Rockies

Follow on MiLB First Pitch  https //stza.co/+xJ8u-2Q

Shop  https //stza.co/+xJ8u-F

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Raptors @ Rockies
END:VALARM
DTSTART:20180731T004000Z
DTEND:20180731T034000Z
UID:9cty2FahLHD_qJNHX4Gdct5D@stanza.co
SUMMARY:Raptors @ Rockies
DESCRIPTION:Raptors @ Rockies\n\nFollow on MiLB First Pitch: https://stza.co/+xJ8u-2Q\n\nShop: https://stza.co/+xJ8u-F\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144548Z
LAST-MODIFIED:20180213T144548Z
TRANSP:OPAQUE
END:VEVENT
* Raptors @ Rockies
<2018-07-31 Tue 19:40-22:40>
:PROPERTIES:
:ID:       h6wK4rNoxqvQnzh8w2DMBvFa@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Raptors @ Rockies Raptors @ Rockies

Follow on MiLB First Pitch  https //stza.co/+xJ8v-M

Shop  https //stza.co/+xJ8v-3o

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Raptors @ Rockies
END:VALARM
DTSTART:20180801T004000Z
DTEND:20180801T034000Z
UID:h6wK4rNoxqvQnzh8w2DMBvFa@stanza.co
SUMMARY:Raptors @ Rockies
DESCRIPTION:Raptors @ Rockies\n\nFollow on MiLB First Pitch: https://stza.co/+xJ8v-M\n\nShop: https://stza.co/+xJ8v-3o\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144548Z
LAST-MODIFIED:20180213T144548Z
TRANSP:OPAQUE
END:VEVENT
* Raptors @ Rockies
<2018-08-01 Wed 19:40-22:40>
:PROPERTIES:
:ID:       7qE0deaB0Jn9RkQ73fqgDAi0@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Raptors @ Rockies Raptors @ Rockies

Follow on MiLB First Pitch  https //stza.co/+xJ8w-1w

Shop  https //stza.co/+xJ8w-2L

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Raptors @ Rockies
END:VALARM
DTSTART:20180802T004000Z
DTEND:20180802T034000Z
UID:7qE0deaB0Jn9RkQ73fqgDAi0@stanza.co
SUMMARY:Raptors @ Rockies
DESCRIPTION:Raptors @ Rockies\n\nFollow on MiLB First Pitch: https://stza.co/+xJ8w-1w\n\nShop: https://stza.co/+xJ8w-2L\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144548Z
LAST-MODIFIED:20180213T144548Z
TRANSP:OPAQUE
END:VEVENT
* Raptors vs. Owlz
<2018-08-02 Thu 20:00-23:00>
:PROPERTIES:
:ID:       QJvK3p3yhnb0gvxXwgm2XmR6@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Raptors vs. Owlz Raptors vs. Owlz

Follow on MiLB First Pitch  https //stza.co/+x$8X-9

Shop  https //stza.co/+x$8X-15

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Raptors vs. Owlz
END:VALARM
DTSTART:20180803T010000Z
DTEND:20180803T040000Z
UID:QJvK3p3yhnb0gvxXwgm2XmR6@stanza.co
SUMMARY:Raptors vs. Owlz
DESCRIPTION:Raptors vs. Owlz\n\nFollow on MiLB First Pitch: https://stza.co/+x$8X-9\n\nShop: https://stza.co/+x$8X-15\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144548Z
LAST-MODIFIED:20180213T144548Z
TRANSP:OPAQUE
END:VEVENT
* Raptors vs. Owlz
<2018-08-03 Fri 20:00-23:00>
:PROPERTIES:
:ID:       4lyBUMli8oz2GC0Bznv-3utg@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Raptors vs. Owlz Raptors vs. Owlz

Follow on MiLB First Pitch  https //stza.co/+x$8Z-i

Shop  https //stza.co/+x$8Z-2c

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Raptors vs. Owlz
END:VALARM
DTSTART:20180804T010000Z
DTEND:20180804T040000Z
UID:4lyBUMli8oz2GC0Bznv-3utg@stanza.co
SUMMARY:Raptors vs. Owlz
DESCRIPTION:Raptors vs. Owlz\n\nFollow on MiLB First Pitch: https://stza.co/+x$8Z-i\n\nShop: https://stza.co/+x$8Z-2c\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144548Z
LAST-MODIFIED:20180213T144548Z
TRANSP:OPAQUE
END:VEVENT
* Raptors vs. Owlz
<2018-08-04 Sat 20:00-23:00>
:PROPERTIES:
:ID:       fUP2UDR4TmuaiuEuTv1gx42u@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Raptors vs. Owlz Raptors vs. Owlz

Follow on MiLB First Pitch  https //stza.co/+x$90-1G

Shop  https //stza.co/+x$90-2M

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Raptors vs. Owlz
END:VALARM
DTSTART:20180805T010000Z
DTEND:20180805T040000Z
UID:fUP2UDR4TmuaiuEuTv1gx42u@stanza.co
SUMMARY:Raptors vs. Owlz
DESCRIPTION:Raptors vs. Owlz\n\nFollow on MiLB First Pitch: https://stza.co/+x$90-1G\n\nShop: https://stza.co/+x$90-2M\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144548Z
LAST-MODIFIED:20180213T144548Z
TRANSP:OPAQUE
END:VEVENT
* Raptors vs. Owlz
<2018-08-05 Sun 17:00-20:00>
:PROPERTIES:
:ID:       em7yIojqcz4utivr9qnkYFT7@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Raptors vs. Owlz Raptors vs. Owlz

Follow on MiLB First Pitch  https //stza.co/+x$91-2e

Shop  https //stza.co/+x$91-W

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Raptors vs. Owlz
END:VALARM
DTSTART:20180805T220000Z
DTEND:20180806T010000Z
UID:em7yIojqcz4utivr9qnkYFT7@stanza.co
SUMMARY:Raptors vs. Owlz
DESCRIPTION:Raptors vs. Owlz\n\nFollow on MiLB First Pitch: https://stza.co/+x$91-2e\n\nShop: https://stza.co/+x$91-W\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144548Z
LAST-MODIFIED:20180213T144548Z
TRANSP:OPAQUE
END:VEVENT
* Raptors @ Mustangs
<2018-08-09 Thu 20:05-23:05>
:PROPERTIES:
:ID:       -NewJSvLp0mYcWfl-fpu7lAw@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Raptors @ Mustangs Raptors @ Mustangs

Follow on MiLB First Pitch  https //stza.co/+xSOV-1l

Shop  https //stza.co/+xSOV-3E

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Raptors @ Mustangs
END:VALARM
DTSTART:20180810T010500Z
DTEND:20180810T040500Z
UID:-NewJSvLp0mYcWfl-fpu7lAw@stanza.co
SUMMARY:Raptors @ Mustangs
DESCRIPTION:Raptors @ Mustangs\n\nFollow on MiLB First Pitch: https://stza.co/+xSOV-1l\n\nShop: https://stza.co/+xSOV-3E\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144548Z
LAST-MODIFIED:20180213T144548Z
TRANSP:OPAQUE
END:VEVENT
* Raptors @ Mustangs
<2018-08-10 Fri 20:05-23:05>
:PROPERTIES:
:ID:       tKSiMzGGl190KAUeqwhiC_tN@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Raptors @ Mustangs Raptors @ Mustangs

Follow on MiLB First Pitch  https //stza.co/+xSOW-1x

Shop  https //stza.co/+xSOW-2N

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Raptors @ Mustangs
END:VALARM
DTSTART:20180811T010500Z
DTEND:20180811T040500Z
UID:tKSiMzGGl190KAUeqwhiC_tN@stanza.co
SUMMARY:Raptors @ Mustangs
DESCRIPTION:Raptors @ Mustangs\n\nFollow on MiLB First Pitch: https://stza.co/+xSOW-1x\n\nShop: https://stza.co/+xSOW-2N\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144548Z
LAST-MODIFIED:20180213T144548Z
TRANSP:OPAQUE
END:VEVENT
* Raptors @ Mustangs
<2018-08-11 Sat 19:05-22:05>
:PROPERTIES:
:ID:       HALcBrXI3lB14zXe_4SseOr1@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Raptors @ Mustangs Raptors @ Mustangs

Follow on MiLB First Pitch  https //stza.co/+xSOX-6

Shop  https //stza.co/+xSOX-1G

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Raptors @ Mustangs
END:VALARM
DTSTART:20180812T000500Z
DTEND:20180812T030500Z
UID:HALcBrXI3lB14zXe_4SseOr1@stanza.co
SUMMARY:Raptors @ Mustangs
DESCRIPTION:Raptors @ Mustangs\n\nFollow on MiLB First Pitch: https://stza.co/+xSOX-6\n\nShop: https://stza.co/+xSOX-1G\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144548Z
LAST-MODIFIED:20180213T144548Z
TRANSP:OPAQUE
END:VEVENT
* Raptors @ Mustangs
<2018-08-12 Sun 14:05-17:05>
:PROPERTIES:
:ID:       JLcahydNhFkkRyGfI17H3ebR@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Raptors @ Mustangs Raptors @ Mustangs

Follow on MiLB First Pitch  https //stza.co/+xSOY-1a

Shop  https //stza.co/+xSOY-1h

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Raptors @ Mustangs
END:VALARM
DTSTART:20180812T190500Z
DTEND:20180812T220500Z
UID:JLcahydNhFkkRyGfI17H3ebR@stanza.co
SUMMARY:Raptors @ Mustangs
DESCRIPTION:Raptors @ Mustangs\n\nFollow on MiLB First Pitch: https://stza.co/+xSOY-1a\n\nShop: https://stza.co/+xSOY-1h\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144548Z
LAST-MODIFIED:20180213T144548Z
TRANSP:OPAQUE
END:VEVENT
* Raptors @ Voyagers
<2018-08-13 Mon>--<2018-08-12 Sun>
:PROPERTIES:
:ID:       PCxTSDcHJ_1LkuX82Kc2A-zy@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Raptors @ Voyagers Raptors @ Voyagers

Follow on MiLB First Pitch  https //stza.co/+xCCR-

Shop  https //stza.co/+xCCR-3w

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Raptors @ Voyagers
END:VALARM
DTSTART;VALUE=DATE:20180813
DTEND;VALUE=DATE:20180813
UID:PCxTSDcHJ_1LkuX82Kc2A-zy@stanza.co
SUMMARY:Raptors @ Voyagers
DESCRIPTION:Raptors @ Voyagers\n\nFollow on MiLB First Pitch: https://stza.co/+xCCR-\n\nShop: https://stza.co/+xCCR-3w\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144548Z
LAST-MODIFIED:20180213T144548Z
TRANSP:OPAQUE
END:VEVENT
* Raptors @ Voyagers
<2018-08-14 Tue>--<2018-08-13 Mon>
:PROPERTIES:
:ID:       eZcJEDD6tWFMFKz_cJtCgxDc@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Raptors @ Voyagers Raptors @ Voyagers

Follow on MiLB First Pitch  https //stza.co/+xCCS-1b

Shop  https //stza.co/+xCCS-3q

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Raptors @ Voyagers
END:VALARM
DTSTART;VALUE=DATE:20180814
DTEND;VALUE=DATE:20180814
UID:eZcJEDD6tWFMFKz_cJtCgxDc@stanza.co
SUMMARY:Raptors @ Voyagers
DESCRIPTION:Raptors @ Voyagers\n\nFollow on MiLB First Pitch: https://stza.co/+xCCS-1b\n\nShop: https://stza.co/+xCCS-3q\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144548Z
LAST-MODIFIED:20180213T144548Z
TRANSP:OPAQUE
END:VEVENT
* Raptors @ Voyagers
<2018-08-15 Wed>--<2018-08-14 Tue>
:PROPERTIES:
:ID:       uj0cZmKkfM3SJ2aZZgO3nopg@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Raptors @ Voyagers Raptors @ Voyagers

Follow on MiLB First Pitch  https //stza.co/+xCCT-i

Shop  https //stza.co/+xCCT-3j

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Raptors @ Voyagers
END:VALARM
DTSTART;VALUE=DATE:20180815
DTEND;VALUE=DATE:20180815
UID:uj0cZmKkfM3SJ2aZZgO3nopg@stanza.co
SUMMARY:Raptors @ Voyagers
DESCRIPTION:Raptors @ Voyagers\n\nFollow on MiLB First Pitch: https://stza.co/+xCCT-i\n\nShop: https://stza.co/+xCCT-3j\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144548Z
LAST-MODIFIED:20180213T144548Z
TRANSP:OPAQUE
END:VEVENT
* Raptors vs. Mustangs
<2018-08-17 Fri 20:00-23:00>
:PROPERTIES:
:ID:       4xJSFVf57XbZUDNO6el1GU5Y@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Raptors vs. Mustangs Raptors vs. Mustangs

Follow on MiLB First Pitch  https //stza.co/+x$94-12

Shop  https //stza.co/+x$94-2t

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Raptors vs. Mustangs
END:VALARM
DTSTART:20180818T010000Z
DTEND:20180818T040000Z
UID:4xJSFVf57XbZUDNO6el1GU5Y@stanza.co
SUMMARY:Raptors vs. Mustangs
DESCRIPTION:Raptors vs. Mustangs\n\nFollow on MiLB First Pitch: https://stza.co/+x$94-12\n\nShop: https://stza.co/+x$94-2t\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144548Z
LAST-MODIFIED:20180213T144548Z
TRANSP:OPAQUE
END:VEVENT
* Raptors vs. Mustangs
<2018-08-18 Sat 20:00-23:00>
:PROPERTIES:
:ID:       _n0e__U1Jt8q7U_OkjkVEho1@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Raptors vs. Mustangs Raptors vs. Mustangs

Follow on MiLB First Pitch  https //stza.co/+x$96-3C

Shop  https //stza.co/+x$96-2F

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Raptors vs. Mustangs
END:VALARM
DTSTART:20180819T010000Z
DTEND:20180819T040000Z
UID:_n0e__U1Jt8q7U_OkjkVEho1@stanza.co
SUMMARY:Raptors vs. Mustangs
DESCRIPTION:Raptors vs. Mustangs\n\nFollow on MiLB First Pitch: https://stza.co/+x$96-3C\n\nShop: https://stza.co/+x$96-2F\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144548Z
LAST-MODIFIED:20180213T144548Z
TRANSP:OPAQUE
END:VEVENT
* Raptors vs. Mustangs
<2018-08-19 Sun 17:00-20:00>
:PROPERTIES:
:ID:       vy211joEz2Wa3zxa5u5GxUnJ@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Raptors vs. Mustangs Raptors vs. Mustangs

Follow on MiLB First Pitch  https //stza.co/+x$98-33

Shop  https //stza.co/+x$98-2g

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Raptors vs. Mustangs
END:VALARM
DTSTART:20180819T220000Z
DTEND:20180820T010000Z
UID:vy211joEz2Wa3zxa5u5GxUnJ@stanza.co
SUMMARY:Raptors vs. Mustangs
DESCRIPTION:Raptors vs. Mustangs\n\nFollow on MiLB First Pitch: https://stza.co/+x$98-33\n\nShop: https://stza.co/+x$98-2g\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144548Z
LAST-MODIFIED:20180213T144548Z
TRANSP:OPAQUE
END:VEVENT
* Raptors vs. Voyagers
<2018-08-20 Mon 19:30-22:30>
:PROPERTIES:
:ID:       jt5xutXNJRT647WwpMG0zbsO@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Raptors vs. Voyagers Raptors vs. Voyagers

Follow on MiLB First Pitch  https //stza.co/+x$9a-3Y

Shop  https //stza.co/+x$9a-1X

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Raptors vs. Voyagers
END:VALARM
DTSTART:20180821T003000Z
DTEND:20180821T033000Z
UID:jt5xutXNJRT647WwpMG0zbsO@stanza.co
SUMMARY:Raptors vs. Voyagers
DESCRIPTION:Raptors vs. Voyagers\n\nFollow on MiLB First Pitch: https://stza.co/+x$9a-3Y\n\nShop: https://stza.co/+x$9a-1X\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144548Z
LAST-MODIFIED:20180213T144548Z
TRANSP:OPAQUE
END:VEVENT
* Raptors vs. Voyagers
<2018-08-21 Tue 19:30-22:30>
:PROPERTIES:
:ID:       cDBoCNH0yuPp131dbI5lDQ0o@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Raptors vs. Voyagers Raptors vs. Voyagers

Follow on MiLB First Pitch  https //stza.co/+x$9c-2k

Shop  https //stza.co/+x$9c-c

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Raptors vs. Voyagers
END:VALARM
DTSTART:20180822T003000Z
DTEND:20180822T033000Z
UID:cDBoCNH0yuPp131dbI5lDQ0o@stanza.co
SUMMARY:Raptors vs. Voyagers
DESCRIPTION:Raptors vs. Voyagers\n\nFollow on MiLB First Pitch: https://stza.co/+x$9c-2k\n\nShop: https://stza.co/+x$9c-c\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144548Z
LAST-MODIFIED:20180213T144548Z
TRANSP:OPAQUE
END:VEVENT
* Raptors vs. Voyagers
<2018-08-22 Wed 19:30-22:30>
:PROPERTIES:
:ID:       IgI7xgTTFh4nraRjM7twoTn7@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Raptors vs. Voyagers Raptors vs. Voyagers

Follow on MiLB First Pitch  https //stza.co/+x$9e-2Z

Shop  https //stza.co/+x$9e-1k

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Raptors vs. Voyagers
END:VALARM
DTSTART:20180823T003000Z
DTEND:20180823T033000Z
UID:IgI7xgTTFh4nraRjM7twoTn7@stanza.co
SUMMARY:Raptors vs. Voyagers
DESCRIPTION:Raptors vs. Voyagers\n\nFollow on MiLB First Pitch: https://stza.co/+x$9e-2Z\n\nShop: https://stza.co/+x$9e-1k\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144548Z
LAST-MODIFIED:20180213T144548Z
TRANSP:OPAQUE
END:VEVENT
* Raptors vs. Voyagers
<2018-08-23 Thu 19:30-22:30>
:PROPERTIES:
:ID:       BGhl5QnqjMY6BXMwI2-x3qnH@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Raptors vs. Voyagers Raptors vs. Voyagers

Follow on MiLB First Pitch  https //stza.co/+x$9f-v

Shop  https //stza.co/+x$9f-G

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Raptors vs. Voyagers
END:VALARM
DTSTART:20180824T003000Z
DTEND:20180824T033000Z
UID:BGhl5QnqjMY6BXMwI2-x3qnH@stanza.co
SUMMARY:Raptors vs. Voyagers
DESCRIPTION:Raptors vs. Voyagers\n\nFollow on MiLB First Pitch: https://stza.co/+x$9f-v\n\nShop: https://stza.co/+x$9f-G\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144548Z
LAST-MODIFIED:20180213T144548Z
TRANSP:OPAQUE
END:VEVENT
* Raptors @ Owlz
<2018-08-24 Fri 19:35-22:35>
:PROPERTIES:
:ID:       EwUpe_81RJKjZL8mzMuS8IbU@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Raptors @ Owlz Raptors @ Owlz

Follow on MiLB First Pitch  https //stza.co/+xPBy-g

Shop  https //stza.co/+xPBy-2N

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Raptors @ Owlz
END:VALARM
DTSTART:20180825T003500Z
DTEND:20180825T033500Z
UID:EwUpe_81RJKjZL8mzMuS8IbU@stanza.co
SUMMARY:Raptors @ Owlz
DESCRIPTION:Raptors @ Owlz\n\nFollow on MiLB First Pitch: https://stza.co/+xPBy-g\n\nShop: https://stza.co/+xPBy-2N\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144548Z
LAST-MODIFIED:20180213T144548Z
TRANSP:OPAQUE
END:VEVENT
* Raptors @ Owlz
<2018-08-25 Sat 19:35-22:35>
:PROPERTIES:
:ID:       qSHd1yA8ON69CMY2PQtwuAe9@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Raptors @ Owlz Raptors @ Owlz

Follow on MiLB First Pitch  https //stza.co/+xPBz-1K

Shop  https //stza.co/+xPBz-25

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Raptors @ Owlz
END:VALARM
DTSTART:20180826T003500Z
DTEND:20180826T033500Z
UID:qSHd1yA8ON69CMY2PQtwuAe9@stanza.co
SUMMARY:Raptors @ Owlz
DESCRIPTION:Raptors @ Owlz\n\nFollow on MiLB First Pitch: https://stza.co/+xPBz-1K\n\nShop: https://stza.co/+xPBz-25\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144548Z
LAST-MODIFIED:20180213T144548Z
TRANSP:OPAQUE
END:VEVENT
* Raptors @ Owlz
<2018-08-27 Mon 19:35-22:35>
:PROPERTIES:
:ID:       EIN3ncxLOQt5zTXepLljiZdJ@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Raptors @ Owlz Raptors @ Owlz

Follow on MiLB First Pitch  https //stza.co/+xPBA-D

Shop  https //stza.co/+xPBA-1p

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Raptors @ Owlz
END:VALARM
DTSTART:20180828T003500Z
DTEND:20180828T033500Z
UID:EIN3ncxLOQt5zTXepLljiZdJ@stanza.co
SUMMARY:Raptors @ Owlz
DESCRIPTION:Raptors @ Owlz\n\nFollow on MiLB First Pitch: https://stza.co/+xPBA-D\n\nShop: https://stza.co/+xPBA-1p\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144548Z
LAST-MODIFIED:20180213T144548Z
TRANSP:OPAQUE
END:VEVENT
* Raptors @ Owlz
<2018-08-28 Tue 19:35-22:35>
:PROPERTIES:
:ID:       LIMIe457F-aUyvVmRJ6H-021@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Raptors @ Owlz Raptors @ Owlz

Follow on MiLB First Pitch  https //stza.co/+xPBB-36

Shop  https //stza.co/+xPBB-3T

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Raptors @ Owlz
END:VALARM
DTSTART:20180829T003500Z
DTEND:20180829T033500Z
UID:LIMIe457F-aUyvVmRJ6H-021@stanza.co
SUMMARY:Raptors @ Owlz
DESCRIPTION:Raptors @ Owlz\n\nFollow on MiLB First Pitch: https://stza.co/+xPBB-36\n\nShop: https://stza.co/+xPBB-3T\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144548Z
LAST-MODIFIED:20180213T144548Z
TRANSP:OPAQUE
END:VEVENT
* Raptors vs. Chukars
<2018-08-29 Wed 19:30-22:30>
:PROPERTIES:
:ID:       uxSwb-raiY2WpV2s_ModCee6@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Raptors vs. Chukars Raptors vs. Chukars

Follow on MiLB First Pitch  https //stza.co/+x$9h-2X

Shop  https //stza.co/+x$9h-3o

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Raptors vs. Chukars
END:VALARM
DTSTART:20180830T003000Z
DTEND:20180830T033000Z
UID:uxSwb-raiY2WpV2s_ModCee6@stanza.co
SUMMARY:Raptors vs. Chukars
DESCRIPTION:Raptors vs. Chukars\n\nFollow on MiLB First Pitch: https://stza.co/+x$9h-2X\n\nShop: https://stza.co/+x$9h-3o\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144548Z
LAST-MODIFIED:20180213T144548Z
TRANSP:OPAQUE
END:VEVENT
* Raptors vs. Chukars
<2018-08-30 Thu 19:30-22:30>
:PROPERTIES:
:ID:       RiD7tZyvlClzKTqXvS5f4pZE@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Raptors vs. Chukars Raptors vs. Chukars

Follow on MiLB First Pitch  https //stza.co/+x$9j-3l

Shop  https //stza.co/+x$9j-2O

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Raptors vs. Chukars
END:VALARM
DTSTART:20180831T003000Z
DTEND:20180831T033000Z
UID:RiD7tZyvlClzKTqXvS5f4pZE@stanza.co
SUMMARY:Raptors vs. Chukars
DESCRIPTION:Raptors vs. Chukars\n\nFollow on MiLB First Pitch: https://stza.co/+x$9j-3l\n\nShop: https://stza.co/+x$9j-2O\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144548Z
LAST-MODIFIED:20180213T144548Z
TRANSP:OPAQUE
END:VEVENT
* Raptors vs. Rockies
<2018-08-31 Fri 19:30-22:30>
:PROPERTIES:
:ID:       26ksI3SKd_ryEqv-RrLLWXAp@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Raptors vs. Rockies Raptors vs. Rockies

Follow on MiLB First Pitch  https //stza.co/+x$9m-3G

Shop  https //stza.co/+x$9m-3b

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Raptors vs. Rockies
END:VALARM
DTSTART:20180901T003000Z
DTEND:20180901T033000Z
UID:26ksI3SKd_ryEqv-RrLLWXAp@stanza.co
SUMMARY:Raptors vs. Rockies
DESCRIPTION:Raptors vs. Rockies\n\nFollow on MiLB First Pitch: https://stza.co/+x$9m-3G\n\nShop: https://stza.co/+x$9m-3b\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144548Z
LAST-MODIFIED:20180213T144548Z
TRANSP:OPAQUE
END:VEVENT
* Raptors vs. Rockies
<2018-09-01 Sat 19:30-22:30>
:PROPERTIES:
:ID:       ba1nw7rSvLfKMchC7Fw5c00W@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Raptors vs. Rockies Raptors vs. Rockies

Follow on MiLB First Pitch  https //stza.co/+x$9o-1e

Shop  https //stza.co/+x$9o-15

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Raptors vs. Rockies
END:VALARM
DTSTART:20180902T003000Z
DTEND:20180902T033000Z
UID:ba1nw7rSvLfKMchC7Fw5c00W@stanza.co
SUMMARY:Raptors vs. Rockies
DESCRIPTION:Raptors vs. Rockies\n\nFollow on MiLB First Pitch: https://stza.co/+x$9o-1e\n\nShop: https://stza.co/+x$9o-15\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144548Z
LAST-MODIFIED:20180213T144548Z
TRANSP:OPAQUE
END:VEVENT
* Raptors @ Chukars
<2018-09-03 Mon 17:00-20:00>
:PROPERTIES:
:ID:       TxKsISgT7DINA7qwzEKsfMvE@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Raptors @ Chukars Raptors @ Chukars

Follow on MiLB First Pitch  https //stza.co/+xZW6-b

Shop  https //stza.co/+xZW6-2B

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Raptors @ Chukars
END:VALARM
DTSTART:20180903T220000Z
DTEND:20180904T010000Z
UID:TxKsISgT7DINA7qwzEKsfMvE@stanza.co
SUMMARY:Raptors @ Chukars
DESCRIPTION:Raptors @ Chukars\n\nFollow on MiLB First Pitch: https://stza.co/+xZW6-b\n\nShop: https://stza.co/+xZW6-2B\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144548Z
LAST-MODIFIED:20180213T144548Z
TRANSP:OPAQUE
END:VEVENT
* Raptors @ Chukars
<2018-09-04 Tue 20:15-23:15>
:PROPERTIES:
:ID:       Ax3qkkqAO2hasoAFc-tMTMXu@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Raptors @ Chukars Raptors @ Chukars

Follow on MiLB First Pitch  https //stza.co/+xZW7-1h

Shop  https //stza.co/+xZW7-3X

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Raptors @ Chukars
END:VALARM
DTSTART:20180905T011500Z
DTEND:20180905T041500Z
UID:Ax3qkkqAO2hasoAFc-tMTMXu@stanza.co
SUMMARY:Raptors @ Chukars
DESCRIPTION:Raptors @ Chukars\n\nFollow on MiLB First Pitch: https://stza.co/+xZW7-1h\n\nShop: https://stza.co/+xZW7-3X\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144548Z
LAST-MODIFIED:20180213T144548Z
TRANSP:OPAQUE
END:VEVENT
* Raptors @ Chukars
<2018-09-05 Wed 20:15-23:15>
:PROPERTIES:
:ID:       U-bF567WPdKibkh-HM39Oyss@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Raptors @ Chukars Raptors @ Chukars

Follow on MiLB First Pitch  https //stza.co/+xZW8-3P

Shop  https //stza.co/+xZW8-1w

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Raptors @ Chukars
END:VALARM
DTSTART:20180906T011500Z
DTEND:20180906T041500Z
UID:U-bF567WPdKibkh-HM39Oyss@stanza.co
SUMMARY:Raptors @ Chukars
DESCRIPTION:Raptors @ Chukars\n\nFollow on MiLB First Pitch: https://stza.co/+xZW8-3P\n\nShop: https://stza.co/+xZW8-1w\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144548Z
LAST-MODIFIED:20180213T144548Z
TRANSP:OPAQUE
END:VEVENT
* Raptors @ Chukars
<2018-09-06 Thu 20:15-23:15>
:PROPERTIES:
:ID:       DfccDt1Zd7eqwXnF7THS4u1d@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Raptors @ Chukars Raptors @ Chukars

Follow on MiLB First Pitch  https //stza.co/+xZW9-1T

Shop  https //stza.co/+xZW9-1R

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Raptors @ Chukars
END:VALARM
DTSTART:20180907T011500Z
DTEND:20180907T041500Z
UID:DfccDt1Zd7eqwXnF7THS4u1d@stanza.co
SUMMARY:Raptors @ Chukars
DESCRIPTION:Raptors @ Chukars\n\nFollow on MiLB First Pitch: https://stza.co/+xZW9-1T\n\nShop: https://stza.co/+xZW9-1R\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144548Z
LAST-MODIFIED:20180213T144548Z
TRANSP:OPAQUE
END:VEVENT
