#+TITLE:       Main Google calendar entries
#+AUTHOR:      Eric S Fraga
#+EMAIL:       e.fraga@ucl.ac.uk
#+DESCRIPTION: converted using the ical2org awk script
#+CATEGORY:    google
#+STARTUP:     hidestars
#+STARTUP:     overview

* COMMENT original iCal preamble

* Osprey @ Mustangs
<2018-06-15 Fri 20:05-23:05>
:PROPERTIES:
:ID:       nbKFRpjWa1T3KQ2FfYEg_SdM@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Osprey @ Mustangs Osprey @ Mustangs

Follow on MiLB First Pitch  https //stza.co/+xSON-3j

Shop  https //stza.co/+xSON-3K

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Osprey @ Mustangs
END:VALARM
DTSTART:20180616T010500Z
DTEND:20180616T040500Z
UID:nbKFRpjWa1T3KQ2FfYEg_SdM@stanza.co
SUMMARY:Osprey @ Mustangs
DESCRIPTION:Osprey @ Mustangs\n\nFollow on MiLB First Pitch: https://stza.co/+xSON-3j\n\nShop: https://stza.co/+xSON-3K\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144544Z
LAST-MODIFIED:20180213T144544Z
TRANSP:OPAQUE
END:VEVENT
* Osprey @ Mustangs
<2018-06-16 Sat 19:05-22:05>
:PROPERTIES:
:ID:       67gHhsFuLM0NLdHXKLErWqUo@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Osprey @ Mustangs Osprey @ Mustangs

Follow on MiLB First Pitch  https //stza.co/+xSOO-3X

Shop  https //stza.co/+xSOO-3d

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Osprey @ Mustangs
END:VALARM
DTSTART:20180617T000500Z
DTEND:20180617T030500Z
UID:67gHhsFuLM0NLdHXKLErWqUo@stanza.co
SUMMARY:Osprey @ Mustangs
DESCRIPTION:Osprey @ Mustangs\n\nFollow on MiLB First Pitch: https://stza.co/+xSOO-3X\n\nShop: https://stza.co/+xSOO-3d\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144544Z
LAST-MODIFIED:20180213T144544Z
TRANSP:OPAQUE
END:VEVENT
* Osprey @ Mustangs
<2018-06-17 Sun 14:05-17:05>
:PROPERTIES:
:ID:       G6JWng-ANKOsTzMGe_fxAX14@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Osprey @ Mustangs Osprey @ Mustangs

Follow on MiLB First Pitch  https //stza.co/+xSOP-1s

Shop  https //stza.co/+xSOP-o

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Osprey @ Mustangs
END:VALARM
DTSTART:20180617T190500Z
DTEND:20180617T220500Z
UID:G6JWng-ANKOsTzMGe_fxAX14@stanza.co
SUMMARY:Osprey @ Mustangs
DESCRIPTION:Osprey @ Mustangs\n\nFollow on MiLB First Pitch: https://stza.co/+xSOP-1s\n\nShop: https://stza.co/+xSOP-o\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144544Z
LAST-MODIFIED:20180213T144544Z
TRANSP:OPAQUE
END:VEVENT
* Osprey @ Mustangs
<2018-06-18 Mon 20:05-23:05>
:PROPERTIES:
:ID:       LUjJPUgTqW6p2UppYW_V7CT3@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Osprey @ Mustangs Osprey @ Mustangs

Follow on MiLB First Pitch  https //stza.co/+xSOQ-N

Shop  https //stza.co/+xSOQ-2J

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Osprey @ Mustangs
END:VALARM
DTSTART:20180619T010500Z
DTEND:20180619T040500Z
UID:LUjJPUgTqW6p2UppYW_V7CT3@stanza.co
SUMMARY:Osprey @ Mustangs
DESCRIPTION:Osprey @ Mustangs\n\nFollow on MiLB First Pitch: https://stza.co/+xSOQ-N\n\nShop: https://stza.co/+xSOQ-2J\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144544Z
LAST-MODIFIED:20180213T144544Z
TRANSP:OPAQUE
END:VEVENT
* Osprey vs. Brewers
<2018-06-19 Tue>--<2018-06-18 Mon>
:PROPERTIES:
:ID:       YGyTzjJf0JWE5tFRpHksDeBL@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Osprey vs. Brewers Osprey vs. Brewers

Follow on MiLB First Pitch  https //stza.co/+xCzG-3l

Shop  https //stza.co/+xCzG-2E

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Osprey vs. Brewers
END:VALARM
DTSTART;VALUE=DATE:20180619
DTEND;VALUE=DATE:20180619
UID:YGyTzjJf0JWE5tFRpHksDeBL@stanza.co
SUMMARY:Osprey vs. Brewers
DESCRIPTION:Osprey vs. Brewers\n\nFollow on MiLB First Pitch: https://stza.co/+xCzG-3l\n\nShop: https://stza.co/+xCzG-2E\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144544Z
LAST-MODIFIED:20180213T144544Z
TRANSP:OPAQUE
END:VEVENT
* Osprey vs. Brewers
<2018-06-20 Wed>--<2018-06-19 Tue>
:PROPERTIES:
:ID:       p42-3QBdtemQra900LH89V9Z@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Osprey vs. Brewers Osprey vs. Brewers

Follow on MiLB First Pitch  https //stza.co/+xCzH-2F

Shop  https //stza.co/+xCzH-7

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Osprey vs. Brewers
END:VALARM
DTSTART;VALUE=DATE:20180620
DTEND;VALUE=DATE:20180620
UID:p42-3QBdtemQra900LH89V9Z@stanza.co
SUMMARY:Osprey vs. Brewers
DESCRIPTION:Osprey vs. Brewers\n\nFollow on MiLB First Pitch: https://stza.co/+xCzH-2F\n\nShop: https://stza.co/+xCzH-7\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144544Z
LAST-MODIFIED:20180213T144544Z
TRANSP:OPAQUE
END:VEVENT
* Osprey vs. Brewers
<2018-06-21 Thu>--<2018-06-20 Wed>
:PROPERTIES:
:ID:       aezCsiX2MF_ofaAbLtO7lllO@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Osprey vs. Brewers Osprey vs. Brewers

Follow on MiLB First Pitch  https //stza.co/+xCzK-31

Shop  https //stza.co/+xCzK-3t

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Osprey vs. Brewers
END:VALARM
DTSTART;VALUE=DATE:20180621
DTEND;VALUE=DATE:20180621
UID:aezCsiX2MF_ofaAbLtO7lllO@stanza.co
SUMMARY:Osprey vs. Brewers
DESCRIPTION:Osprey vs. Brewers\n\nFollow on MiLB First Pitch: https://stza.co/+xCzK-31\n\nShop: https://stza.co/+xCzK-3t\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144544Z
LAST-MODIFIED:20180213T144544Z
TRANSP:OPAQUE
END:VEVENT
* Osprey vs. Voyagers
<2018-06-22 Fri>--<2018-06-21 Thu>
:PROPERTIES:
:ID:       kWlFwFKnpLOjlq5rCf1oUdCl@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Osprey vs. Voyagers Osprey vs. Voyagers

Follow on MiLB First Pitch  https //stza.co/+xCzL-19

Shop  https //stza.co/+xCzL-2g

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Osprey vs. Voyagers
END:VALARM
DTSTART;VALUE=DATE:20180622
DTEND;VALUE=DATE:20180622
UID:kWlFwFKnpLOjlq5rCf1oUdCl@stanza.co
SUMMARY:Osprey vs. Voyagers
DESCRIPTION:Osprey vs. Voyagers\n\nFollow on MiLB First Pitch: https://stza.co/+xCzL-19\n\nShop: https://stza.co/+xCzL-2g\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144544Z
LAST-MODIFIED:20180213T144544Z
TRANSP:OPAQUE
END:VEVENT
* Osprey vs. Voyagers
<2018-06-23 Sat>--<2018-06-22 Fri>
:PROPERTIES:
:ID:       9F6S-YdIQa9DuBzKKAlBDrRg@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Osprey vs. Voyagers Osprey vs. Voyagers

Follow on MiLB First Pitch  https //stza.co/+xCzN-J

Shop  https //stza.co/+xCzN-5

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Osprey vs. Voyagers
END:VALARM
DTSTART;VALUE=DATE:20180623
DTEND;VALUE=DATE:20180623
UID:9F6S-YdIQa9DuBzKKAlBDrRg@stanza.co
SUMMARY:Osprey vs. Voyagers
DESCRIPTION:Osprey vs. Voyagers\n\nFollow on MiLB First Pitch: https://stza.co/+xCzN-J\n\nShop: https://stza.co/+xCzN-5\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144544Z
LAST-MODIFIED:20180213T144544Z
TRANSP:OPAQUE
END:VEVENT
* Osprey vs. Voyagers
<2018-06-24 Sun>--<2018-06-23 Sat>
:PROPERTIES:
:ID:       RXwGJXOk5wNHj1oInzxAV2yh@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Osprey vs. Voyagers Osprey vs. Voyagers

Follow on MiLB First Pitch  https //stza.co/+xCzQ-3Q

Shop  https //stza.co/+xCzQ-1z

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Osprey vs. Voyagers
END:VALARM
DTSTART;VALUE=DATE:20180624
DTEND;VALUE=DATE:20180624
UID:RXwGJXOk5wNHj1oInzxAV2yh@stanza.co
SUMMARY:Osprey vs. Voyagers
DESCRIPTION:Osprey vs. Voyagers\n\nFollow on MiLB First Pitch: https://stza.co/+xCzQ-3Q\n\nShop: https://stza.co/+xCzQ-1z\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144544Z
LAST-MODIFIED:20180213T144544Z
TRANSP:OPAQUE
END:VEVENT
* Osprey @ Brewers
<2018-06-25 Mon>--<2018-06-24 Sun>
:PROPERTIES:
:ID:       Mz4JYmj8nr_Gn_bmefqUSSrR@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Osprey @ Brewers Osprey @ Brewers

Follow on MiLB First Pitch  https //stza.co/+xCzl-17

Shop  https //stza.co/+xCzl-1m

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Osprey @ Brewers
END:VALARM
DTSTART;VALUE=DATE:20180625
DTEND;VALUE=DATE:20180625
UID:Mz4JYmj8nr_Gn_bmefqUSSrR@stanza.co
SUMMARY:Osprey @ Brewers
DESCRIPTION:Osprey @ Brewers\n\nFollow on MiLB First Pitch: https://stza.co/+xCzl-17\n\nShop: https://stza.co/+xCzl-1m\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144544Z
LAST-MODIFIED:20180213T144544Z
TRANSP:OPAQUE
END:VEVENT
* Osprey @ Brewers
<2018-06-26 Tue>--<2018-06-25 Mon>
:PROPERTIES:
:ID:       I-xoI4enlWD-m-l38bNsCkNL@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Osprey @ Brewers Osprey @ Brewers

Follow on MiLB First Pitch  https //stza.co/+xCzm-2P

Shop  https //stza.co/+xCzm-3f

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Osprey @ Brewers
END:VALARM
DTSTART;VALUE=DATE:20180626
DTEND;VALUE=DATE:20180626
UID:I-xoI4enlWD-m-l38bNsCkNL@stanza.co
SUMMARY:Osprey @ Brewers
DESCRIPTION:Osprey @ Brewers\n\nFollow on MiLB First Pitch: https://stza.co/+xCzm-2P\n\nShop: https://stza.co/+xCzm-3f\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144544Z
LAST-MODIFIED:20180213T144544Z
TRANSP:OPAQUE
END:VEVENT
* Osprey @ Brewers
<2018-06-27 Wed>--<2018-06-26 Tue>
:PROPERTIES:
:ID:       qY4t8YwJO37m7TYv0YKMxV5o@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Osprey @ Brewers Osprey @ Brewers

Follow on MiLB First Pitch  https //stza.co/+xCzn-15

Shop  https //stza.co/+xCzn-3n

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Osprey @ Brewers
END:VALARM
DTSTART;VALUE=DATE:20180627
DTEND;VALUE=DATE:20180627
UID:qY4t8YwJO37m7TYv0YKMxV5o@stanza.co
SUMMARY:Osprey @ Brewers
DESCRIPTION:Osprey @ Brewers\n\nFollow on MiLB First Pitch: https://stza.co/+xCzn-15\n\nShop: https://stza.co/+xCzn-3n\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144544Z
LAST-MODIFIED:20180213T144544Z
TRANSP:OPAQUE
END:VEVENT
* Osprey @ Voyagers
<2018-06-28 Thu>--<2018-06-27 Wed>
:PROPERTIES:
:ID:       Sp5oKm10WHad8QfYz7P5rXOC@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Osprey @ Voyagers Osprey @ Voyagers

Follow on MiLB First Pitch  https //stza.co/+xCB0-2g

Shop  https //stza.co/+xCB0-f

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Osprey @ Voyagers
END:VALARM
DTSTART;VALUE=DATE:20180628
DTEND;VALUE=DATE:20180628
UID:Sp5oKm10WHad8QfYz7P5rXOC@stanza.co
SUMMARY:Osprey @ Voyagers
DESCRIPTION:Osprey @ Voyagers\n\nFollow on MiLB First Pitch: https://stza.co/+xCB0-2g\n\nShop: https://stza.co/+xCB0-f\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144544Z
LAST-MODIFIED:20180213T144544Z
TRANSP:OPAQUE
END:VEVENT
* Osprey @ Voyagers
<2018-06-29 Fri>--<2018-06-28 Thu>
:PROPERTIES:
:ID:       MeEjDW4TtA2GHI_JlVDqwPJ_@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Osprey @ Voyagers Osprey @ Voyagers

Follow on MiLB First Pitch  https //stza.co/+xCB1-P

Shop  https //stza.co/+xCB1-30

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Osprey @ Voyagers
END:VALARM
DTSTART;VALUE=DATE:20180629
DTEND;VALUE=DATE:20180629
UID:MeEjDW4TtA2GHI_JlVDqwPJ_@stanza.co
SUMMARY:Osprey @ Voyagers
DESCRIPTION:Osprey @ Voyagers\n\nFollow on MiLB First Pitch: https://stza.co/+xCB1-P\n\nShop: https://stza.co/+xCB1-30\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144544Z
LAST-MODIFIED:20180213T144544Z
TRANSP:OPAQUE
END:VEVENT
* Osprey vs. Mustangs
<2018-06-30 Sat>--<2018-06-29 Fri>
:PROPERTIES:
:ID:       mClILYxZ8S5NrndiHsP70Udg@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Osprey vs. Mustangs Osprey vs. Mustangs

Follow on MiLB First Pitch  https //stza.co/+xCzR-3y

Shop  https //stza.co/+xCzR-j

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Osprey vs. Mustangs
END:VALARM
DTSTART;VALUE=DATE:20180630
DTEND;VALUE=DATE:20180630
UID:mClILYxZ8S5NrndiHsP70Udg@stanza.co
SUMMARY:Osprey vs. Mustangs
DESCRIPTION:Osprey vs. Mustangs\n\nFollow on MiLB First Pitch: https://stza.co/+xCzR-3y\n\nShop: https://stza.co/+xCzR-j\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144544Z
LAST-MODIFIED:20180213T144544Z
TRANSP:OPAQUE
END:VEVENT
* Osprey vs. Mustangs
<2018-07-01 Sun>--<2018-06-30 Sat>
:PROPERTIES:
:ID:       qRda-E1p-8conOCnT9R6AA3F@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Osprey vs. Mustangs Osprey vs. Mustangs

Follow on MiLB First Pitch  https //stza.co/+xCzU-2J

Shop  https //stza.co/+xCzU-30

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Osprey vs. Mustangs
END:VALARM
DTSTART;VALUE=DATE:20180701
DTEND;VALUE=DATE:20180701
UID:qRda-E1p-8conOCnT9R6AA3F@stanza.co
SUMMARY:Osprey vs. Mustangs
DESCRIPTION:Osprey vs. Mustangs\n\nFollow on MiLB First Pitch: https://stza.co/+xCzU-2J\n\nShop: https://stza.co/+xCzU-30\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144544Z
LAST-MODIFIED:20180213T144544Z
TRANSP:OPAQUE
END:VEVENT
* Osprey vs. Mustangs
<2018-07-02 Mon>--<2018-07-01 Sun>
:PROPERTIES:
:ID:       UJXX6no9JFdWiIfZb_IfqwnQ@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Osprey vs. Mustangs Osprey vs. Mustangs

Follow on MiLB First Pitch  https //stza.co/+xCzW-2l

Shop  https //stza.co/+xCzW-3f

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Osprey vs. Mustangs
END:VALARM
DTSTART;VALUE=DATE:20180702
DTEND;VALUE=DATE:20180702
UID:UJXX6no9JFdWiIfZb_IfqwnQ@stanza.co
SUMMARY:Osprey vs. Mustangs
DESCRIPTION:Osprey vs. Mustangs\n\nFollow on MiLB First Pitch: https://stza.co/+xCzW-2l\n\nShop: https://stza.co/+xCzW-3f\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144544Z
LAST-MODIFIED:20180213T144544Z
TRANSP:OPAQUE
END:VEVENT
* Osprey vs. Mustangs
<2018-07-03 Tue>--<2018-07-02 Mon>
:PROPERTIES:
:ID:       xQXBLQ0PLJu6ftWbNzqIzYWh@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Osprey vs. Mustangs Osprey vs. Mustangs

Follow on MiLB First Pitch  https //stza.co/+xCzY-37

Shop  https //stza.co/+xCzY-2z

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Osprey vs. Mustangs
END:VALARM
DTSTART;VALUE=DATE:20180703
DTEND;VALUE=DATE:20180703
UID:xQXBLQ0PLJu6ftWbNzqIzYWh@stanza.co
SUMMARY:Osprey vs. Mustangs
DESCRIPTION:Osprey vs. Mustangs\n\nFollow on MiLB First Pitch: https://stza.co/+xCzY-37\n\nShop: https://stza.co/+xCzY-2z\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144544Z
LAST-MODIFIED:20180213T144544Z
TRANSP:OPAQUE
END:VEVENT
* Osprey @ Voyagers
<2018-07-04 Wed>--<2018-07-03 Tue>
:PROPERTIES:
:ID:       biF4JTE1HueeKadz9O3tSlyf@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Osprey @ Voyagers Osprey @ Voyagers

Follow on MiLB First Pitch  https //stza.co/+xCB2-1v

Shop  https //stza.co/+xCB2-1a

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Osprey @ Voyagers
END:VALARM
DTSTART;VALUE=DATE:20180704
DTEND;VALUE=DATE:20180704
UID:biF4JTE1HueeKadz9O3tSlyf@stanza.co
SUMMARY:Osprey @ Voyagers
DESCRIPTION:Osprey @ Voyagers\n\nFollow on MiLB First Pitch: https://stza.co/+xCB2-1v\n\nShop: https://stza.co/+xCB2-1a\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144544Z
LAST-MODIFIED:20180213T144544Z
TRANSP:OPAQUE
END:VEVENT
* Osprey @ Voyagers
<2018-07-05 Thu>--<2018-07-04 Wed>
:PROPERTIES:
:ID:       ZXXMfvxJbKfR2Vmlo0Z8gmJq@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Osprey @ Voyagers Osprey @ Voyagers

Follow on MiLB First Pitch  https //stza.co/+xCB3-38

Shop  https //stza.co/+xCB3-1z

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Osprey @ Voyagers
END:VALARM
DTSTART;VALUE=DATE:20180705
DTEND;VALUE=DATE:20180705
UID:ZXXMfvxJbKfR2Vmlo0Z8gmJq@stanza.co
SUMMARY:Osprey @ Voyagers
DESCRIPTION:Osprey @ Voyagers\n\nFollow on MiLB First Pitch: https://stza.co/+xCB3-38\n\nShop: https://stza.co/+xCB3-1z\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144544Z
LAST-MODIFIED:20180213T144544Z
TRANSP:OPAQUE
END:VEVENT
* Osprey @ Voyagers
<2018-07-06 Fri>--<2018-07-05 Thu>
:PROPERTIES:
:ID:       0Q3bycLVIqWyQkQVj-DusbEC@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Osprey @ Voyagers Osprey @ Voyagers

Follow on MiLB First Pitch  https //stza.co/+xCB4-3b

Shop  https //stza.co/+xCB4-2_

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Osprey @ Voyagers
END:VALARM
DTSTART;VALUE=DATE:20180706
DTEND;VALUE=DATE:20180706
UID:0Q3bycLVIqWyQkQVj-DusbEC@stanza.co
SUMMARY:Osprey @ Voyagers
DESCRIPTION:Osprey @ Voyagers\n\nFollow on MiLB First Pitch: https://stza.co/+xCB4-3b\n\nShop: https://stza.co/+xCB4-2_\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144544Z
LAST-MODIFIED:20180213T144544Z
TRANSP:OPAQUE
END:VEVENT
* Osprey vs. Voyagers
<2018-07-07 Sat>--<2018-07-06 Fri>
:PROPERTIES:
:ID:       1-QPC_lLzwMyTeoFntGOLr3Z@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Osprey vs. Voyagers Osprey vs. Voyagers

Follow on MiLB First Pitch  https //stza.co/+xCz_-C

Shop  https //stza.co/+xCz_-3P

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Osprey vs. Voyagers
END:VALARM
DTSTART;VALUE=DATE:20180707
DTEND;VALUE=DATE:20180707
UID:1-QPC_lLzwMyTeoFntGOLr3Z@stanza.co
SUMMARY:Osprey vs. Voyagers
DESCRIPTION:Osprey vs. Voyagers\n\nFollow on MiLB First Pitch: https://stza.co/+xCz_-C\n\nShop: https://stza.co/+xCz_-3P\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144544Z
LAST-MODIFIED:20180213T144544Z
TRANSP:OPAQUE
END:VEVENT
* Osprey vs. Voyagers
<2018-07-08 Sun>--<2018-07-07 Sat>
:PROPERTIES:
:ID:       5gh3knHyv9gMijTabbg271Uv@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Osprey vs. Voyagers Osprey vs. Voyagers

Follow on MiLB First Pitch  https //stza.co/+xCz$-38

Shop  https //stza.co/+xCz$-3P

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Osprey vs. Voyagers
END:VALARM
DTSTART;VALUE=DATE:20180708
DTEND;VALUE=DATE:20180708
UID:5gh3knHyv9gMijTabbg271Uv@stanza.co
SUMMARY:Osprey vs. Voyagers
DESCRIPTION:Osprey vs. Voyagers\n\nFollow on MiLB First Pitch: https://stza.co/+xCz$-38\n\nShop: https://stza.co/+xCz$-3P\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144544Z
LAST-MODIFIED:20180213T144544Z
TRANSP:OPAQUE
END:VEVENT
* Osprey @ Raptors
<2018-07-10 Tue 20:00-23:00>
:PROPERTIES:
:ID:       7-JVSfRn1ALkjFQTfnjD8Nx2@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Osprey @ Raptors Osprey @ Raptors

Follow on MiLB First Pitch  https //stza.co/+x$89-1O

Shop  https //stza.co/+x$89-E

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Osprey @ Raptors
END:VALARM
DTSTART:20180711T010000Z
DTEND:20180711T040000Z
UID:7-JVSfRn1ALkjFQTfnjD8Nx2@stanza.co
SUMMARY:Osprey @ Raptors
DESCRIPTION:Osprey @ Raptors\n\nFollow on MiLB First Pitch: https://stza.co/+x$89-1O\n\nShop: https://stza.co/+x$89-E\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144544Z
LAST-MODIFIED:20180213T144544Z
TRANSP:OPAQUE
END:VEVENT
* Osprey @ Raptors
<2018-07-11 Wed 20:00-23:00>
:PROPERTIES:
:ID:       oLfGy2omUIUVJrZLjQfRA-k3@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Osprey @ Raptors Osprey @ Raptors

Follow on MiLB First Pitch  https //stza.co/+x$8a-2G

Shop  https //stza.co/+x$8a-1l

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Osprey @ Raptors
END:VALARM
DTSTART:20180712T010000Z
DTEND:20180712T040000Z
UID:oLfGy2omUIUVJrZLjQfRA-k3@stanza.co
SUMMARY:Osprey @ Raptors
DESCRIPTION:Osprey @ Raptors\n\nFollow on MiLB First Pitch: https://stza.co/+x$8a-2G\n\nShop: https://stza.co/+x$8a-1l\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144544Z
LAST-MODIFIED:20180213T144544Z
TRANSP:OPAQUE
END:VEVENT
* Osprey @ Raptors
<2018-07-12 Thu 20:00-23:00>
:PROPERTIES:
:ID:       ZscZGSAFPh38rCT7GcAWgfl7@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Osprey @ Raptors Osprey @ Raptors

Follow on MiLB First Pitch  https //stza.co/+x$8b-2W

Shop  https //stza.co/+x$8b-3q

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Osprey @ Raptors
END:VALARM
DTSTART:20180713T010000Z
DTEND:20180713T040000Z
UID:ZscZGSAFPh38rCT7GcAWgfl7@stanza.co
SUMMARY:Osprey @ Raptors
DESCRIPTION:Osprey @ Raptors\n\nFollow on MiLB First Pitch: https://stza.co/+x$8b-2W\n\nShop: https://stza.co/+x$8b-3q\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144544Z
LAST-MODIFIED:20180213T144544Z
TRANSP:OPAQUE
END:VEVENT
* Osprey @ Raptors
<2018-07-13 Fri 20:00-23:00>
:PROPERTIES:
:ID:       qrXkxjNTbthHwZj0-53PgcSA@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Osprey @ Raptors Osprey @ Raptors

Follow on MiLB First Pitch  https //stza.co/+x$8c-2O

Shop  https //stza.co/+x$8c-1Y

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Osprey @ Raptors
END:VALARM
DTSTART:20180714T010000Z
DTEND:20180714T040000Z
UID:qrXkxjNTbthHwZj0-53PgcSA@stanza.co
SUMMARY:Osprey @ Raptors
DESCRIPTION:Osprey @ Raptors\n\nFollow on MiLB First Pitch: https://stza.co/+x$8c-2O\n\nShop: https://stza.co/+x$8c-1Y\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144544Z
LAST-MODIFIED:20180213T144544Z
TRANSP:OPAQUE
END:VEVENT
* Osprey @ Chukars
<2018-07-14 Sat 20:15-23:15>
:PROPERTIES:
:ID:       r48Mq0t-yOCOEy9lcYW2On0Z@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Osprey @ Chukars Osprey @ Chukars

Follow on MiLB First Pitch  https //stza.co/+xZV$-y

Shop  https //stza.co/+xZV$-2o

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Osprey @ Chukars
END:VALARM
DTSTART:20180715T011500Z
DTEND:20180715T041500Z
UID:r48Mq0t-yOCOEy9lcYW2On0Z@stanza.co
SUMMARY:Osprey @ Chukars
DESCRIPTION:Osprey @ Chukars\n\nFollow on MiLB First Pitch: https://stza.co/+xZV$-y\n\nShop: https://stza.co/+xZV$-2o\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144544Z
LAST-MODIFIED:20180213T144544Z
TRANSP:OPAQUE
END:VEVENT
* Osprey @ Chukars
<2018-07-15 Sun 17:00-20:00>
:PROPERTIES:
:ID:       4eNBpZCbO161w6WSNXZQBX3V@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Osprey @ Chukars Osprey @ Chukars

Follow on MiLB First Pitch  https //stza.co/+xZW0-e

Shop  https //stza.co/+xZW0-3z

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Osprey @ Chukars
END:VALARM
DTSTART:20180715T220000Z
DTEND:20180716T010000Z
UID:4eNBpZCbO161w6WSNXZQBX3V@stanza.co
SUMMARY:Osprey @ Chukars
DESCRIPTION:Osprey @ Chukars\n\nFollow on MiLB First Pitch: https://stza.co/+xZW0-e\n\nShop: https://stza.co/+xZW0-3z\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144544Z
LAST-MODIFIED:20180213T144544Z
TRANSP:OPAQUE
END:VEVENT
* Osprey @ Chukars
<2018-07-16 Mon 20:15-23:15>
:PROPERTIES:
:ID:       gtDccA2soBkvh_bUBGaoLb-I@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Osprey @ Chukars Osprey @ Chukars

Follow on MiLB First Pitch  https //stza.co/+xZW1-2S

Shop  https //stza.co/+xZW1-1V

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Osprey @ Chukars
END:VALARM
DTSTART:20180717T011500Z
DTEND:20180717T041500Z
UID:gtDccA2soBkvh_bUBGaoLb-I@stanza.co
SUMMARY:Osprey @ Chukars
DESCRIPTION:Osprey @ Chukars\n\nFollow on MiLB First Pitch: https://stza.co/+xZW1-2S\n\nShop: https://stza.co/+xZW1-1V\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144544Z
LAST-MODIFIED:20180213T144544Z
TRANSP:OPAQUE
END:VEVENT
* Osprey vs. Raptors
<2018-07-18 Wed>--<2018-07-17 Tue>
:PROPERTIES:
:ID:       NA5UJbRmq_eA1qC5r6zb50bZ@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Osprey vs. Raptors Osprey vs. Raptors

Follow on MiLB First Pitch  https //stza.co/+xCA1-3h

Shop  https //stza.co/+xCA1-3d

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Osprey vs. Raptors
END:VALARM
DTSTART;VALUE=DATE:20180718
DTEND;VALUE=DATE:20180718
UID:NA5UJbRmq_eA1qC5r6zb50bZ@stanza.co
SUMMARY:Osprey vs. Raptors
DESCRIPTION:Osprey vs. Raptors\n\nFollow on MiLB First Pitch: https://stza.co/+xCA1-3h\n\nShop: https://stza.co/+xCA1-3d\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144544Z
LAST-MODIFIED:20180213T144544Z
TRANSP:OPAQUE
END:VEVENT
* Osprey vs. Raptors
<2018-07-19 Thu>--<2018-07-18 Wed>
:PROPERTIES:
:ID:       m_sslNIlY62cE49emU0L8oEu@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Osprey vs. Raptors Osprey vs. Raptors

Follow on MiLB First Pitch  https //stza.co/+xCA4-2r

Shop  https //stza.co/+xCA4-3Z

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Osprey vs. Raptors
END:VALARM
DTSTART;VALUE=DATE:20180719
DTEND;VALUE=DATE:20180719
UID:m_sslNIlY62cE49emU0L8oEu@stanza.co
SUMMARY:Osprey vs. Raptors
DESCRIPTION:Osprey vs. Raptors\n\nFollow on MiLB First Pitch: https://stza.co/+xCA4-2r\n\nShop: https://stza.co/+xCA4-3Z\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144544Z
LAST-MODIFIED:20180213T144544Z
TRANSP:OPAQUE
END:VEVENT
* Osprey vs. Raptors
<2018-07-20 Fri>--<2018-07-19 Thu>
:PROPERTIES:
:ID:       OXIb90v_iQowid-KWCapTBx2@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Osprey vs. Raptors Osprey vs. Raptors

Follow on MiLB First Pitch  https //stza.co/+xCA6-3O

Shop  https //stza.co/+xCA6-3V

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Osprey vs. Raptors
END:VALARM
DTSTART;VALUE=DATE:20180720
DTEND;VALUE=DATE:20180720
UID:OXIb90v_iQowid-KWCapTBx2@stanza.co
SUMMARY:Osprey vs. Raptors
DESCRIPTION:Osprey vs. Raptors\n\nFollow on MiLB First Pitch: https://stza.co/+xCA6-3O\n\nShop: https://stza.co/+xCA6-3V\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144544Z
LAST-MODIFIED:20180213T144544Z
TRANSP:OPAQUE
END:VEVENT
* Osprey vs. Chukars
<2018-07-21 Sat>--<2018-07-20 Fri>
:PROPERTIES:
:ID:       RUTNKPnaZ5p92NAeQXvlrg8P@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Osprey vs. Chukars Osprey vs. Chukars

Follow on MiLB First Pitch  https //stza.co/+xCA7-A

Shop  https //stza.co/+xCA7-2X

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Osprey vs. Chukars
END:VALARM
DTSTART;VALUE=DATE:20180721
DTEND;VALUE=DATE:20180721
UID:RUTNKPnaZ5p92NAeQXvlrg8P@stanza.co
SUMMARY:Osprey vs. Chukars
DESCRIPTION:Osprey vs. Chukars\n\nFollow on MiLB First Pitch: https://stza.co/+xCA7-A\n\nShop: https://stza.co/+xCA7-2X\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144544Z
LAST-MODIFIED:20180213T144544Z
TRANSP:OPAQUE
END:VEVENT
* Osprey vs. Chukars
<2018-07-22 Sun>--<2018-07-21 Sat>
:PROPERTIES:
:ID:       NnSc_z1gXai8X3KburQ5jQ1_@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Osprey vs. Chukars Osprey vs. Chukars

Follow on MiLB First Pitch  https //stza.co/+xCAa-2j

Shop  https //stza.co/+xCAa-1z

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Osprey vs. Chukars
END:VALARM
DTSTART;VALUE=DATE:20180722
DTEND;VALUE=DATE:20180722
UID:NnSc_z1gXai8X3KburQ5jQ1_@stanza.co
SUMMARY:Osprey vs. Chukars
DESCRIPTION:Osprey vs. Chukars\n\nFollow on MiLB First Pitch: https://stza.co/+xCAa-2j\n\nShop: https://stza.co/+xCAa-1z\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144544Z
LAST-MODIFIED:20180213T144544Z
TRANSP:OPAQUE
END:VEVENT
* Osprey vs. Chukars
<2018-07-23 Mon>--<2018-07-22 Sun>
:PROPERTIES:
:ID:       J4O_gWHEifgVlR4QouvOPOt9@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Osprey vs. Chukars Osprey vs. Chukars

Follow on MiLB First Pitch  https //stza.co/+xCAb-3I

Shop  https //stza.co/+xCAb-S

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Osprey vs. Chukars
END:VALARM
DTSTART;VALUE=DATE:20180723
DTEND;VALUE=DATE:20180723
UID:J4O_gWHEifgVlR4QouvOPOt9@stanza.co
SUMMARY:Osprey vs. Chukars
DESCRIPTION:Osprey vs. Chukars\n\nFollow on MiLB First Pitch: https://stza.co/+xCAb-3I\n\nShop: https://stza.co/+xCAb-S\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144544Z
LAST-MODIFIED:20180213T144544Z
TRANSP:OPAQUE
END:VEVENT
* Osprey vs. Chukars
<2018-07-24 Tue>--<2018-07-23 Mon>
:PROPERTIES:
:ID:       aM5-dcZvy2_EeSLwupu-Etx-@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Osprey vs. Chukars Osprey vs. Chukars

Follow on MiLB First Pitch  https //stza.co/+xCAd-2z

Shop  https //stza.co/+xCAd-K

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Osprey vs. Chukars
END:VALARM
DTSTART;VALUE=DATE:20180724
DTEND;VALUE=DATE:20180724
UID:aM5-dcZvy2_EeSLwupu-Etx-@stanza.co
SUMMARY:Osprey vs. Chukars
DESCRIPTION:Osprey vs. Chukars\n\nFollow on MiLB First Pitch: https://stza.co/+xCAd-2z\n\nShop: https://stza.co/+xCAd-K\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144544Z
LAST-MODIFIED:20180213T144544Z
TRANSP:OPAQUE
END:VEVENT
* Osprey @ Mustangs
<2018-07-26 Thu 20:05-23:05>
:PROPERTIES:
:ID:       jYqFjEdsFaTqr9PxaLBaD6ka@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Osprey @ Mustangs Osprey @ Mustangs

Follow on MiLB First Pitch  https //stza.co/+xSOR-1j

Shop  https //stza.co/+xSOR-1e

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Osprey @ Mustangs
END:VALARM
DTSTART:20180727T010500Z
DTEND:20180727T040500Z
UID:jYqFjEdsFaTqr9PxaLBaD6ka@stanza.co
SUMMARY:Osprey @ Mustangs
DESCRIPTION:Osprey @ Mustangs\n\nFollow on MiLB First Pitch: https://stza.co/+xSOR-1j\n\nShop: https://stza.co/+xSOR-1e\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144544Z
LAST-MODIFIED:20180213T144544Z
TRANSP:OPAQUE
END:VEVENT
* Osprey @ Mustangs
<2018-07-27 Fri 20:05-23:05>
:PROPERTIES:
:ID:       KfF3WVzxtpZIMPzfA2Zc2I5O@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Osprey @ Mustangs Osprey @ Mustangs

Follow on MiLB First Pitch  https //stza.co/+xSOS-2$

Shop  https //stza.co/+xSOS-34

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Osprey @ Mustangs
END:VALARM
DTSTART:20180728T010500Z
DTEND:20180728T040500Z
UID:KfF3WVzxtpZIMPzfA2Zc2I5O@stanza.co
SUMMARY:Osprey @ Mustangs
DESCRIPTION:Osprey @ Mustangs\n\nFollow on MiLB First Pitch: https://stza.co/+xSOS-2$\n\nShop: https://stza.co/+xSOS-34\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144544Z
LAST-MODIFIED:20180213T144544Z
TRANSP:OPAQUE
END:VEVENT
* Osprey @ Mustangs
<2018-07-28 Sat 19:05-22:05>
:PROPERTIES:
:ID:       FfqlYn_iyv7hXFh0_NmSSYbQ@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Osprey @ Mustangs Osprey @ Mustangs

Follow on MiLB First Pitch  https //stza.co/+xSOT-8

Shop  https //stza.co/+xSOT-2c

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Osprey @ Mustangs
END:VALARM
DTSTART:20180729T000500Z
DTEND:20180729T030500Z
UID:FfqlYn_iyv7hXFh0_NmSSYbQ@stanza.co
SUMMARY:Osprey @ Mustangs
DESCRIPTION:Osprey @ Mustangs\n\nFollow on MiLB First Pitch: https://stza.co/+xSOT-8\n\nShop: https://stza.co/+xSOT-2c\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144544Z
LAST-MODIFIED:20180213T144544Z
TRANSP:OPAQUE
END:VEVENT
* Osprey @ Mustangs
<2018-07-29 Sun 14:05-17:05>
:PROPERTIES:
:ID:       MjRNnNOC1WduFaZusrplJW4o@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Osprey @ Mustangs Osprey @ Mustangs

Follow on MiLB First Pitch  https //stza.co/+xSOU-k

Shop  https //stza.co/+xSOU-1k

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Osprey @ Mustangs
END:VALARM
DTSTART:20180729T190500Z
DTEND:20180729T220500Z
UID:MjRNnNOC1WduFaZusrplJW4o@stanza.co
SUMMARY:Osprey @ Mustangs
DESCRIPTION:Osprey @ Mustangs\n\nFollow on MiLB First Pitch: https://stza.co/+xSOU-k\n\nShop: https://stza.co/+xSOU-1k\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144544Z
LAST-MODIFIED:20180213T144544Z
TRANSP:OPAQUE
END:VEVENT
* Osprey @ Brewers
<2018-07-30 Mon>--<2018-07-29 Sun>
:PROPERTIES:
:ID:       BQxiyzaTLnof-GmsWAiKSX_U@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Osprey @ Brewers Osprey @ Brewers

Follow on MiLB First Pitch  https //stza.co/+xCzo-3t

Shop  https //stza.co/+xCzo-3G

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Osprey @ Brewers
END:VALARM
DTSTART;VALUE=DATE:20180730
DTEND;VALUE=DATE:20180730
UID:BQxiyzaTLnof-GmsWAiKSX_U@stanza.co
SUMMARY:Osprey @ Brewers
DESCRIPTION:Osprey @ Brewers\n\nFollow on MiLB First Pitch: https://stza.co/+xCzo-3t\n\nShop: https://stza.co/+xCzo-3G\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144544Z
LAST-MODIFIED:20180213T144544Z
TRANSP:OPAQUE
END:VEVENT
* Osprey @ Brewers
<2018-07-31 Tue>--<2018-07-30 Mon>
:PROPERTIES:
:ID:       YzD3bXIEzeC3pDz1sgNmEsw5@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Osprey @ Brewers Osprey @ Brewers

Follow on MiLB First Pitch  https //stza.co/+xCzp-2G

Shop  https //stza.co/+xCzp-1e

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Osprey @ Brewers
END:VALARM
DTSTART;VALUE=DATE:20180731
DTEND;VALUE=DATE:20180731
UID:YzD3bXIEzeC3pDz1sgNmEsw5@stanza.co
SUMMARY:Osprey @ Brewers
DESCRIPTION:Osprey @ Brewers\n\nFollow on MiLB First Pitch: https://stza.co/+xCzp-2G\n\nShop: https://stza.co/+xCzp-1e\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144544Z
LAST-MODIFIED:20180213T144544Z
TRANSP:OPAQUE
END:VEVENT
* Osprey vs. Brewers
<2018-08-01 Wed>--<2018-07-31 Tue>
:PROPERTIES:
:ID:       rB2ZyKJgwvCIKzZFfbhIOZJ0@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Osprey vs. Brewers Osprey vs. Brewers

Follow on MiLB First Pitch  https //stza.co/+xCAf-1P

Shop  https //stza.co/+xCAf-3A

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Osprey vs. Brewers
END:VALARM
DTSTART;VALUE=DATE:20180801
DTEND;VALUE=DATE:20180801
UID:rB2ZyKJgwvCIKzZFfbhIOZJ0@stanza.co
SUMMARY:Osprey vs. Brewers
DESCRIPTION:Osprey vs. Brewers\n\nFollow on MiLB First Pitch: https://stza.co/+xCAf-1P\n\nShop: https://stza.co/+xCAf-3A\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144544Z
LAST-MODIFIED:20180213T144544Z
TRANSP:OPAQUE
END:VEVENT
* Osprey vs. Brewers
<2018-08-02 Thu>--<2018-08-01 Wed>
:PROPERTIES:
:ID:       Bl62i0GotJDDzX6VPJwEh6gI@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Osprey vs. Brewers Osprey vs. Brewers

Follow on MiLB First Pitch  https //stza.co/+xCAh-3L

Shop  https //stza.co/+xCAh-20

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Osprey vs. Brewers
END:VALARM
DTSTART;VALUE=DATE:20180802
DTEND;VALUE=DATE:20180802
UID:Bl62i0GotJDDzX6VPJwEh6gI@stanza.co
SUMMARY:Osprey vs. Brewers
DESCRIPTION:Osprey vs. Brewers\n\nFollow on MiLB First Pitch: https://stza.co/+xCAh-3L\n\nShop: https://stza.co/+xCAh-20\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144544Z
LAST-MODIFIED:20180213T144544Z
TRANSP:OPAQUE
END:VEVENT
* Osprey vs. Voyagers
<2018-08-03 Fri>--<2018-08-02 Thu>
:PROPERTIES:
:ID:       _dL8DcFLMxNVlKzDglsMgPZ6@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Osprey vs. Voyagers Osprey vs. Voyagers

Follow on MiLB First Pitch  https //stza.co/+xCAj-1r

Shop  https //stza.co/+xCAj-d

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Osprey vs. Voyagers
END:VALARM
DTSTART;VALUE=DATE:20180803
DTEND;VALUE=DATE:20180803
UID:_dL8DcFLMxNVlKzDglsMgPZ6@stanza.co
SUMMARY:Osprey vs. Voyagers
DESCRIPTION:Osprey vs. Voyagers\n\nFollow on MiLB First Pitch: https://stza.co/+xCAj-1r\n\nShop: https://stza.co/+xCAj-d\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144544Z
LAST-MODIFIED:20180213T144544Z
TRANSP:OPAQUE
END:VEVENT
* Osprey vs. Voyagers
<2018-08-04 Sat>--<2018-08-03 Fri>
:PROPERTIES:
:ID:       dIR7BPmf-f-gDi9AumrOJ7QI@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Osprey vs. Voyagers Osprey vs. Voyagers

Follow on MiLB First Pitch  https //stza.co/+xCAl-2P

Shop  https //stza.co/+xCAl-I

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Osprey vs. Voyagers
END:VALARM
DTSTART;VALUE=DATE:20180804
DTEND;VALUE=DATE:20180804
UID:dIR7BPmf-f-gDi9AumrOJ7QI@stanza.co
SUMMARY:Osprey vs. Voyagers
DESCRIPTION:Osprey vs. Voyagers\n\nFollow on MiLB First Pitch: https://stza.co/+xCAl-2P\n\nShop: https://stza.co/+xCAl-I\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144544Z
LAST-MODIFIED:20180213T144544Z
TRANSP:OPAQUE
END:VEVENT
* Osprey vs. Voyagers
<2018-08-05 Sun>--<2018-08-04 Sat>
:PROPERTIES:
:ID:       gBNGCwlSDA3gh6sN7Ug3HG23@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Osprey vs. Voyagers Osprey vs. Voyagers

Follow on MiLB First Pitch  https //stza.co/+xCAo-3q

Shop  https //stza.co/+xCAo-1r

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Osprey vs. Voyagers
END:VALARM
DTSTART;VALUE=DATE:20180805
DTEND;VALUE=DATE:20180805
UID:gBNGCwlSDA3gh6sN7Ug3HG23@stanza.co
SUMMARY:Osprey vs. Voyagers
DESCRIPTION:Osprey vs. Voyagers\n\nFollow on MiLB First Pitch: https://stza.co/+xCAo-3q\n\nShop: https://stza.co/+xCAo-1r\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144544Z
LAST-MODIFIED:20180213T144544Z
TRANSP:OPAQUE
END:VEVENT
* Osprey @ Owlz
<2018-08-09 Thu 20:05-23:05>
:PROPERTIES:
:ID:       yRH43BpzA1KRMn7WhWCbmM7R@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Osprey @ Owlz Osprey @ Owlz

Follow on MiLB First Pitch  https //stza.co/+xPBq-3j

Shop  https //stza.co/+xPBq-2c

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Osprey @ Owlz
END:VALARM
DTSTART:20180810T010500Z
DTEND:20180810T040500Z
UID:yRH43BpzA1KRMn7WhWCbmM7R@stanza.co
SUMMARY:Osprey @ Owlz
DESCRIPTION:Osprey @ Owlz\n\nFollow on MiLB First Pitch: https://stza.co/+xPBq-3j\n\nShop: https://stza.co/+xPBq-2c\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144544Z
LAST-MODIFIED:20180213T144544Z
TRANSP:OPAQUE
END:VEVENT
* Osprey @ Owlz
<2018-08-10 Fri 20:05-23:05>
:PROPERTIES:
:ID:       VpNxRXTlL0o4lA37p3lQtVLR@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Osprey @ Owlz Osprey @ Owlz

Follow on MiLB First Pitch  https //stza.co/+xPBr-13

Shop  https //stza.co/+xPBr-3u

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Osprey @ Owlz
END:VALARM
DTSTART:20180811T010500Z
DTEND:20180811T040500Z
UID:VpNxRXTlL0o4lA37p3lQtVLR@stanza.co
SUMMARY:Osprey @ Owlz
DESCRIPTION:Osprey @ Owlz\n\nFollow on MiLB First Pitch: https://stza.co/+xPBr-13\n\nShop: https://stza.co/+xPBr-3u\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144544Z
LAST-MODIFIED:20180213T144544Z
TRANSP:OPAQUE
END:VEVENT
* Osprey @ Owlz
<2018-08-11 Sat 20:05-23:05>
:PROPERTIES:
:ID:       qqAZ0LK2si-8bMyny8vh7Kmb@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Osprey @ Owlz Osprey @ Owlz

Follow on MiLB First Pitch  https //stza.co/+xPBs-P

Shop  https //stza.co/+xPBs-2X

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Osprey @ Owlz
END:VALARM
DTSTART:20180812T010500Z
DTEND:20180812T040500Z
UID:qqAZ0LK2si-8bMyny8vh7Kmb@stanza.co
SUMMARY:Osprey @ Owlz
DESCRIPTION:Osprey @ Owlz\n\nFollow on MiLB First Pitch: https://stza.co/+xPBs-P\n\nShop: https://stza.co/+xPBs-2X\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144544Z
LAST-MODIFIED:20180213T144544Z
TRANSP:OPAQUE
END:VEVENT
* Osprey @ Owlz
<2018-08-12 Sun 17:05-20:05>
:PROPERTIES:
:ID:       UdvHeXUQufqHNSkdmou34Zfv@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Osprey @ Owlz Osprey @ Owlz

Follow on MiLB First Pitch  https //stza.co/+xPBt-O

Shop  https //stza.co/+xPBt-2U

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Osprey @ Owlz
END:VALARM
DTSTART:20180812T220500Z
DTEND:20180813T010500Z
UID:UdvHeXUQufqHNSkdmou34Zfv@stanza.co
SUMMARY:Osprey @ Owlz
DESCRIPTION:Osprey @ Owlz\n\nFollow on MiLB First Pitch: https://stza.co/+xPBt-O\n\nShop: https://stza.co/+xPBt-2U\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144544Z
LAST-MODIFIED:20180213T144544Z
TRANSP:OPAQUE
END:VEVENT
* Osprey @ Rockies
<2018-08-13 Mon 19:40-22:40>
:PROPERTIES:
:ID:       bgLSI9eJnt1sGZDJjHHmuAEV@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Osprey @ Rockies Osprey @ Rockies

Follow on MiLB First Pitch  https //stza.co/+xJ8k-1Z

Shop  https //stza.co/+xJ8k-1L

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Osprey @ Rockies
END:VALARM
DTSTART:20180814T004000Z
DTEND:20180814T034000Z
UID:bgLSI9eJnt1sGZDJjHHmuAEV@stanza.co
SUMMARY:Osprey @ Rockies
DESCRIPTION:Osprey @ Rockies\n\nFollow on MiLB First Pitch: https://stza.co/+xJ8k-1Z\n\nShop: https://stza.co/+xJ8k-1L\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144544Z
LAST-MODIFIED:20180213T144544Z
TRANSP:OPAQUE
END:VEVENT
* Osprey @ Rockies
<2018-08-14 Tue 19:40-22:40>
:PROPERTIES:
:ID:       SOQpUhxVYyIYzBFYZx5y6l2d@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Osprey @ Rockies Osprey @ Rockies

Follow on MiLB First Pitch  https //stza.co/+xJ8l-3z

Shop  https //stza.co/+xJ8l-3o

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Osprey @ Rockies
END:VALARM
DTSTART:20180815T004000Z
DTEND:20180815T034000Z
UID:SOQpUhxVYyIYzBFYZx5y6l2d@stanza.co
SUMMARY:Osprey @ Rockies
DESCRIPTION:Osprey @ Rockies\n\nFollow on MiLB First Pitch: https://stza.co/+xJ8l-3z\n\nShop: https://stza.co/+xJ8l-3o\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144544Z
LAST-MODIFIED:20180213T144544Z
TRANSP:OPAQUE
END:VEVENT
* Osprey @ Rockies
<2018-08-15 Wed 19:40-22:40>
:PROPERTIES:
:ID:       h0HntSXeA_vIzxpPnt9t1ebC@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Osprey @ Rockies Osprey @ Rockies

Follow on MiLB First Pitch  https //stza.co/+xJ8m-1$

Shop  https //stza.co/+xJ8m-3v

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Osprey @ Rockies
END:VALARM
DTSTART:20180816T004000Z
DTEND:20180816T034000Z
UID:h0HntSXeA_vIzxpPnt9t1ebC@stanza.co
SUMMARY:Osprey @ Rockies
DESCRIPTION:Osprey @ Rockies\n\nFollow on MiLB First Pitch: https://stza.co/+xJ8m-1$\n\nShop: https://stza.co/+xJ8m-3v\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144544Z
LAST-MODIFIED:20180213T144544Z
TRANSP:OPAQUE
END:VEVENT
* Osprey vs. Owlz
<2018-08-17 Fri>--<2018-08-16 Thu>
:PROPERTIES:
:ID:       y384eWabEALjRfQuEdP56UWf@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Osprey vs. Owlz Osprey vs. Owlz

Follow on MiLB First Pitch  https //stza.co/+xCAq-1g

Shop  https //stza.co/+xCAq-12

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Osprey vs. Owlz
END:VALARM
DTSTART;VALUE=DATE:20180817
DTEND;VALUE=DATE:20180817
UID:y384eWabEALjRfQuEdP56UWf@stanza.co
SUMMARY:Osprey vs. Owlz
DESCRIPTION:Osprey vs. Owlz\n\nFollow on MiLB First Pitch: https://stza.co/+xCAq-1g\n\nShop: https://stza.co/+xCAq-12\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144544Z
LAST-MODIFIED:20180213T144544Z
TRANSP:OPAQUE
END:VEVENT
* Osprey vs. Owlz
<2018-08-18 Sat>--<2018-08-17 Fri>
:PROPERTIES:
:ID:       aES-yvUHkEcot4ys165ADyB0@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Osprey vs. Owlz Osprey vs. Owlz

Follow on MiLB First Pitch  https //stza.co/+xCAr-1q

Shop  https //stza.co/+xCAr-3A

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Osprey vs. Owlz
END:VALARM
DTSTART;VALUE=DATE:20180818
DTEND;VALUE=DATE:20180818
UID:aES-yvUHkEcot4ys165ADyB0@stanza.co
SUMMARY:Osprey vs. Owlz
DESCRIPTION:Osprey vs. Owlz\n\nFollow on MiLB First Pitch: https://stza.co/+xCAr-1q\n\nShop: https://stza.co/+xCAr-3A\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144544Z
LAST-MODIFIED:20180213T144544Z
TRANSP:OPAQUE
END:VEVENT
* Osprey vs. Owlz
<2018-08-19 Sun>--<2018-08-18 Sat>
:PROPERTIES:
:ID:       iQsTW4BNY3qGskkdVjaiHtTM@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Osprey vs. Owlz Osprey vs. Owlz

Follow on MiLB First Pitch  https //stza.co/+xCAu-28

Shop  https //stza.co/+xCAu-1R

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Osprey vs. Owlz
END:VALARM
DTSTART;VALUE=DATE:20180819
DTEND;VALUE=DATE:20180819
UID:iQsTW4BNY3qGskkdVjaiHtTM@stanza.co
SUMMARY:Osprey vs. Owlz
DESCRIPTION:Osprey vs. Owlz\n\nFollow on MiLB First Pitch: https://stza.co/+xCAu-28\n\nShop: https://stza.co/+xCAu-1R\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144544Z
LAST-MODIFIED:20180213T144544Z
TRANSP:OPAQUE
END:VEVENT
* Osprey vs. Rockies
<2018-08-20 Mon>--<2018-08-19 Sun>
:PROPERTIES:
:ID:       U37_f28NwvPJy8HwidjJiiFM@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Osprey vs. Rockies Osprey vs. Rockies

Follow on MiLB First Pitch  https //stza.co/+xCAv-1l

Shop  https //stza.co/+xCAv-2o

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Osprey vs. Rockies
END:VALARM
DTSTART;VALUE=DATE:20180820
DTEND;VALUE=DATE:20180820
UID:U37_f28NwvPJy8HwidjJiiFM@stanza.co
SUMMARY:Osprey vs. Rockies
DESCRIPTION:Osprey vs. Rockies\n\nFollow on MiLB First Pitch: https://stza.co/+xCAv-1l\n\nShop: https://stza.co/+xCAv-2o\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144544Z
LAST-MODIFIED:20180213T144544Z
TRANSP:OPAQUE
END:VEVENT
* Osprey vs. Rockies
<2018-08-21 Tue>--<2018-08-20 Mon>
:PROPERTIES:
:ID:       NhDlPiId8-G61Uk3oNtl_WxI@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Osprey vs. Rockies Osprey vs. Rockies

Follow on MiLB First Pitch  https //stza.co/+xCAy-3V

Shop  https //stza.co/+xCAy-3k

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Osprey vs. Rockies
END:VALARM
DTSTART;VALUE=DATE:20180821
DTEND;VALUE=DATE:20180821
UID:NhDlPiId8-G61Uk3oNtl_WxI@stanza.co
SUMMARY:Osprey vs. Rockies
DESCRIPTION:Osprey vs. Rockies\n\nFollow on MiLB First Pitch: https://stza.co/+xCAy-3V\n\nShop: https://stza.co/+xCAy-3k\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144544Z
LAST-MODIFIED:20180213T144544Z
TRANSP:OPAQUE
END:VEVENT
* Osprey vs. Rockies
<2018-08-22 Wed>--<2018-08-21 Tue>
:PROPERTIES:
:ID:       u3cen5eZAFRUltXvHG5ySdYw@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Osprey vs. Rockies Osprey vs. Rockies

Follow on MiLB First Pitch  https //stza.co/+xCAA-

Shop  https //stza.co/+xCAA-b

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Osprey vs. Rockies
END:VALARM
DTSTART;VALUE=DATE:20180822
DTEND;VALUE=DATE:20180822
UID:u3cen5eZAFRUltXvHG5ySdYw@stanza.co
SUMMARY:Osprey vs. Rockies
DESCRIPTION:Osprey vs. Rockies\n\nFollow on MiLB First Pitch: https://stza.co/+xCAA-\n\nShop: https://stza.co/+xCAA-b\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144544Z
LAST-MODIFIED:20180213T144544Z
TRANSP:OPAQUE
END:VEVENT
* Osprey vs. Rockies
<2018-08-23 Thu>--<2018-08-22 Wed>
:PROPERTIES:
:ID:       NZPsbWw6ZMTyd2si3VeQta97@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Osprey vs. Rockies Osprey vs. Rockies

Follow on MiLB First Pitch  https //stza.co/+xCAE-1j

Shop  https //stza.co/+xCAE-1e

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Osprey vs. Rockies
END:VALARM
DTSTART;VALUE=DATE:20180823
DTEND;VALUE=DATE:20180823
UID:NZPsbWw6ZMTyd2si3VeQta97@stanza.co
SUMMARY:Osprey vs. Rockies
DESCRIPTION:Osprey vs. Rockies\n\nFollow on MiLB First Pitch: https://stza.co/+xCAE-1j\n\nShop: https://stza.co/+xCAE-1e\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144544Z
LAST-MODIFIED:20180213T144544Z
TRANSP:OPAQUE
END:VEVENT
* Osprey @ Voyagers
<2018-08-25 Sat>--<2018-08-24 Fri>
:PROPERTIES:
:ID:       fkKO_yDJPQQ8cR2PXBUiYwQ5@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Osprey @ Voyagers Osprey @ Voyagers

Follow on MiLB First Pitch  https //stza.co/+xCB5-Y

Shop  https //stza.co/+xCB5-1a

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Osprey @ Voyagers
END:VALARM
DTSTART;VALUE=DATE:20180825
DTEND;VALUE=DATE:20180825
UID:fkKO_yDJPQQ8cR2PXBUiYwQ5@stanza.co
SUMMARY:Osprey @ Voyagers
DESCRIPTION:Osprey @ Voyagers\n\nFollow on MiLB First Pitch: https://stza.co/+xCB5-Y\n\nShop: https://stza.co/+xCB5-1a\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144544Z
LAST-MODIFIED:20180213T144544Z
TRANSP:OPAQUE
END:VEVENT
* Osprey @ Voyagers
<2018-08-26 Sun>--<2018-08-25 Sat>
:PROPERTIES:
:ID:       6MbVhiGG58NRU4e1UbDrJCkl@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Osprey @ Voyagers Osprey @ Voyagers

Follow on MiLB First Pitch  https //stza.co/+xCB6-v

Shop  https //stza.co/+xCB6-13

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Osprey @ Voyagers
END:VALARM
DTSTART;VALUE=DATE:20180826
DTEND;VALUE=DATE:20180826
UID:6MbVhiGG58NRU4e1UbDrJCkl@stanza.co
SUMMARY:Osprey @ Voyagers
DESCRIPTION:Osprey @ Voyagers\n\nFollow on MiLB First Pitch: https://stza.co/+xCB6-v\n\nShop: https://stza.co/+xCB6-13\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144544Z
LAST-MODIFIED:20180213T144544Z
TRANSP:OPAQUE
END:VEVENT
* Osprey @ Voyagers
<2018-08-27 Mon>--<2018-08-26 Sun>
:PROPERTIES:
:ID:       fPCr925Y-YBc3T1pjIMYf0mK@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Osprey @ Voyagers Osprey @ Voyagers

Follow on MiLB First Pitch  https //stza.co/+xCB7-r

Shop  https //stza.co/+xCB7-2_

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Osprey @ Voyagers
END:VALARM
DTSTART;VALUE=DATE:20180827
DTEND;VALUE=DATE:20180827
UID:fPCr925Y-YBc3T1pjIMYf0mK@stanza.co
SUMMARY:Osprey @ Voyagers
DESCRIPTION:Osprey @ Voyagers\n\nFollow on MiLB First Pitch: https://stza.co/+xCB7-r\n\nShop: https://stza.co/+xCB7-2_\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144544Z
LAST-MODIFIED:20180213T144544Z
TRANSP:OPAQUE
END:VEVENT
* Osprey vs. Mustangs
<2018-08-28 Tue>--<2018-08-27 Mon>
:PROPERTIES:
:ID:       qMKGmespfZ50Piu3RbiSMjK8@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Osprey vs. Mustangs Osprey vs. Mustangs

Follow on MiLB First Pitch  https //stza.co/+xCAG-3j

Shop  https //stza.co/+xCAG-2r

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Osprey vs. Mustangs
END:VALARM
DTSTART;VALUE=DATE:20180828
DTEND;VALUE=DATE:20180828
UID:qMKGmespfZ50Piu3RbiSMjK8@stanza.co
SUMMARY:Osprey vs. Mustangs
DESCRIPTION:Osprey vs. Mustangs\n\nFollow on MiLB First Pitch: https://stza.co/+xCAG-3j\n\nShop: https://stza.co/+xCAG-2r\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144544Z
LAST-MODIFIED:20180213T144544Z
TRANSP:OPAQUE
END:VEVENT
* Osprey vs. Mustangs
<2018-08-29 Wed>--<2018-08-28 Tue>
:PROPERTIES:
:ID:       8VNJIHAvlglNNbqKesfVK3s9@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Osprey vs. Mustangs Osprey vs. Mustangs

Follow on MiLB First Pitch  https //stza.co/+xCAH-8

Shop  https //stza.co/+xCAH-2i

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Osprey vs. Mustangs
END:VALARM
DTSTART;VALUE=DATE:20180829
DTEND;VALUE=DATE:20180829
UID:8VNJIHAvlglNNbqKesfVK3s9@stanza.co
SUMMARY:Osprey vs. Mustangs
DESCRIPTION:Osprey vs. Mustangs\n\nFollow on MiLB First Pitch: https://stza.co/+xCAH-8\n\nShop: https://stza.co/+xCAH-2i\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144544Z
LAST-MODIFIED:20180213T144544Z
TRANSP:OPAQUE
END:VEVENT
* Osprey vs. Mustangs
<2018-08-30 Thu>--<2018-08-29 Wed>
:PROPERTIES:
:ID:       tFItKZBh6OoRk3U6QpsXUvx-@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Osprey vs. Mustangs Osprey vs. Mustangs

Follow on MiLB First Pitch  https //stza.co/+xCAJ-2Q

Shop  https //stza.co/+xCAJ-3P

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Osprey vs. Mustangs
END:VALARM
DTSTART;VALUE=DATE:20180830
DTEND;VALUE=DATE:20180830
UID:tFItKZBh6OoRk3U6QpsXUvx-@stanza.co
SUMMARY:Osprey vs. Mustangs
DESCRIPTION:Osprey vs. Mustangs\n\nFollow on MiLB First Pitch: https://stza.co/+xCAJ-2Q\n\nShop: https://stza.co/+xCAJ-3P\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144544Z
LAST-MODIFIED:20180213T144544Z
TRANSP:OPAQUE
END:VEVENT
* Osprey vs. Mustangs
<2018-08-31 Fri>--<2018-08-30 Thu>
:PROPERTIES:
:ID:       MpSl-zuRz2gSGsin5_9Vedr-@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Osprey vs. Mustangs Osprey vs. Mustangs

Follow on MiLB First Pitch  https //stza.co/+xCAM-1

Shop  https //stza.co/+xCAM-3A

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Osprey vs. Mustangs
END:VALARM
DTSTART;VALUE=DATE:20180831
DTEND;VALUE=DATE:20180831
UID:MpSl-zuRz2gSGsin5_9Vedr-@stanza.co
SUMMARY:Osprey vs. Mustangs
DESCRIPTION:Osprey vs. Mustangs\n\nFollow on MiLB First Pitch: https://stza.co/+xCAM-1\n\nShop: https://stza.co/+xCAM-3A\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144544Z
LAST-MODIFIED:20180213T144544Z
TRANSP:OPAQUE
END:VEVENT
* Osprey @ Brewers
<2018-09-01 Sat>--<2018-08-31 Fri>
:PROPERTIES:
:ID:       oFm6KxtxoqCZMb0oEyrRnKk6@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Osprey @ Brewers Osprey @ Brewers

Follow on MiLB First Pitch  https //stza.co/+xCzq-p

Shop  https //stza.co/+xCzq-L

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Osprey @ Brewers
END:VALARM
DTSTART;VALUE=DATE:20180901
DTEND;VALUE=DATE:20180901
UID:oFm6KxtxoqCZMb0oEyrRnKk6@stanza.co
SUMMARY:Osprey @ Brewers
DESCRIPTION:Osprey @ Brewers\n\nFollow on MiLB First Pitch: https://stza.co/+xCzq-p\n\nShop: https://stza.co/+xCzq-L\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144544Z
LAST-MODIFIED:20180213T144544Z
TRANSP:OPAQUE
END:VEVENT
* Osprey @ Brewers
<2018-09-02 Sun>--<2018-09-01 Sat>
:PROPERTIES:
:ID:       pUNAPSFkeXbCeP7hyVnm5jdV@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Osprey @ Brewers Osprey @ Brewers

Follow on MiLB First Pitch  https //stza.co/+xCzr-3h

Shop  https //stza.co/+xCzr-

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Osprey @ Brewers
END:VALARM
DTSTART;VALUE=DATE:20180902
DTEND;VALUE=DATE:20180902
UID:pUNAPSFkeXbCeP7hyVnm5jdV@stanza.co
SUMMARY:Osprey @ Brewers
DESCRIPTION:Osprey @ Brewers\n\nFollow on MiLB First Pitch: https://stza.co/+xCzr-3h\n\nShop: https://stza.co/+xCzr-\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144544Z
LAST-MODIFIED:20180213T144544Z
TRANSP:OPAQUE
END:VEVENT
* Osprey @ Brewers
<2018-09-03 Mon>--<2018-09-02 Sun>
:PROPERTIES:
:ID:       FusywJiSC6a5-R6WhYSI4HVq@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Osprey @ Brewers Osprey @ Brewers

Follow on MiLB First Pitch  https //stza.co/+xCzs-2v

Shop  https //stza.co/+xCzs-U

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Osprey @ Brewers
END:VALARM
DTSTART;VALUE=DATE:20180903
DTEND;VALUE=DATE:20180903
UID:FusywJiSC6a5-R6WhYSI4HVq@stanza.co
SUMMARY:Osprey @ Brewers
DESCRIPTION:Osprey @ Brewers\n\nFollow on MiLB First Pitch: https://stza.co/+xCzs-2v\n\nShop: https://stza.co/+xCzs-U\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144544Z
LAST-MODIFIED:20180213T144544Z
TRANSP:OPAQUE
END:VEVENT
* Osprey vs. Brewers
<2018-09-04 Tue>--<2018-09-03 Mon>
:PROPERTIES:
:ID:       NaqSLN65Dr6x-ZbHQ7JlC2Eo@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Osprey vs. Brewers Osprey vs. Brewers

Follow on MiLB First Pitch  https //stza.co/+xCAN-V

Shop  https //stza.co/+xCAN-E

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Osprey vs. Brewers
END:VALARM
DTSTART;VALUE=DATE:20180904
DTEND;VALUE=DATE:20180904
UID:NaqSLN65Dr6x-ZbHQ7JlC2Eo@stanza.co
SUMMARY:Osprey vs. Brewers
DESCRIPTION:Osprey vs. Brewers\n\nFollow on MiLB First Pitch: https://stza.co/+xCAN-V\n\nShop: https://stza.co/+xCAN-E\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144544Z
LAST-MODIFIED:20180213T144544Z
TRANSP:OPAQUE
END:VEVENT
* Osprey vs. Brewers
<2018-09-05 Wed>--<2018-09-04 Tue>
:PROPERTIES:
:ID:       dET5mWnDdT_xIKs32BMzwtsT@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Osprey vs. Brewers Osprey vs. Brewers

Follow on MiLB First Pitch  https //stza.co/+xCAQ-14

Shop  https //stza.co/+xCAQ-a

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Osprey vs. Brewers
END:VALARM
DTSTART;VALUE=DATE:20180905
DTEND;VALUE=DATE:20180905
UID:dET5mWnDdT_xIKs32BMzwtsT@stanza.co
SUMMARY:Osprey vs. Brewers
DESCRIPTION:Osprey vs. Brewers\n\nFollow on MiLB First Pitch: https://stza.co/+xCAQ-14\n\nShop: https://stza.co/+xCAQ-a\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144544Z
LAST-MODIFIED:20180213T144544Z
TRANSP:OPAQUE
END:VEVENT
* Osprey vs. Brewers
<2018-09-06 Thu>--<2018-09-05 Wed>
:PROPERTIES:
:ID:       ag67nL7odHl_wkbOjYCCWkQh@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Osprey vs. Brewers Osprey vs. Brewers

Follow on MiLB First Pitch  https //stza.co/+xCAR-2I

Shop  https //stza.co/+xCAR-1p

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Osprey vs. Brewers
END:VALARM
DTSTART;VALUE=DATE:20180906
DTEND;VALUE=DATE:20180906
UID:ag67nL7odHl_wkbOjYCCWkQh@stanza.co
SUMMARY:Osprey vs. Brewers
DESCRIPTION:Osprey vs. Brewers\n\nFollow on MiLB First Pitch: https://stza.co/+xCAR-2I\n\nShop: https://stza.co/+xCAR-1p\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144544Z
LAST-MODIFIED:20180213T144544Z
TRANSP:OPAQUE
END:VEVENT
