#+TITLE:       Main Google calendar entries
#+AUTHOR:      Eric S Fraga
#+EMAIL:       e.fraga@ucl.ac.uk
#+DESCRIPTION: converted using the ical2org awk script
#+CATEGORY:    google
#+STARTUP:     hidestars
#+STARTUP:     overview

* COMMENT original iCal preamble

* Yard Goats vs. Fisher Cats
<2018-04-05 Thu 18:05-21:05>
:PROPERTIES:
:ID:       e-Km_F9ZSni_lWVl2NYEGKrV@stanza.co
:LOCATION: Atlas FIreworks
:STATUS:   CONFIRMED
:END:

Yard Goats vs. Fisher Cats 





Buy tickets here  https //stza.co/~vLks

Follow on MiLB First Pitch  https //stza.co/+vLks-L

Shop  https //stza.co/+vLks-3y

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Yard Goats vs. Fisher Cats
END:VALARM
DTSTART:20180405T230500Z
DTEND:20180406T020500Z
UID:e-Km_F9ZSni_lWVl2NYEGKrV@stanza.co
SUMMARY:Yard Goats vs. Fisher Cats
DESCRIPTION:\n\n\n\n\n\nBuy tickets here: https://stza.co/~vLks\n\nFollow on MiLB First Pitch: https://stza.co/+vLks-L\n\nShop: https://stza.co/+vLks-3y\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Atlas FIreworks
STATUS:CONFIRMED
CREATED:20180213T144531Z
LAST-MODIFIED:20180213T144531Z
TRANSP:OPAQUE
END:VEVENT
* Yard Goats vs. Fisher Cats
<2018-04-06 Fri 18:05-21:05>
:PROPERTIES:
:ID:       nVjIQ2UAaf4OMZPl5SJaD6hn@stanza.co
:LOCATION: Swipe to get tickets for the game tonight. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Yard Goats vs. Fisher Cats Yard Goats vs. Fisher Cats

Buy tickets here  https //stza.co/~vLku

Follow on MiLB First Pitch  https //stza.co/+vLku-3H

Shop  https //stza.co/+vLku-2b

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Yard Goats vs. Fisher Cats
END:VALARM
DTSTART:20180406T230500Z
DTEND:20180407T020500Z
UID:nVjIQ2UAaf4OMZPl5SJaD6hn@stanza.co
SUMMARY:Yard Goats vs. Fisher Cats
DESCRIPTION:Yard Goats vs. Fisher Cats\n\nBuy tickets here: https://stza.co/~vLku\n\nFollow on MiLB First Pitch: https://stza.co/+vLku-3H\n\nShop: https://stza.co/+vLku-2b\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Swipe to get tickets for the game tonight. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144531Z
LAST-MODIFIED:20180213T144531Z
TRANSP:OPAQUE
END:VEVENT
* Yard Goats vs. Fisher Cats
<2018-04-07 Sat 17:05-20:05>
:PROPERTIES:
:ID:       IT3VHJ7vwldNQer3w36YwIbN@stanza.co
:LOCATION: Atlas Fireworks
:STATUS:   CONFIRMED
:END:

Yard Goats vs. Fisher Cats 



Buy tickets here  https //stza.co/~vLkw

Follow on MiLB First Pitch  https //stza.co/+vLkw-2p

Shop  https //stza.co/+vLkw-1$

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Yard Goats vs. Fisher Cats
END:VALARM
DTSTART:20180407T220500Z
DTEND:20180408T010500Z
UID:IT3VHJ7vwldNQer3w36YwIbN@stanza.co
SUMMARY:Yard Goats vs. Fisher Cats
DESCRIPTION:\n\n\n\nBuy tickets here: https://stza.co/~vLkw\n\nFollow on MiLB First Pitch: https://stza.co/+vLkw-2p\n\nShop: https://stza.co/+vLkw-1$\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Atlas Fireworks
STATUS:CONFIRMED
CREATED:20180213T144531Z
LAST-MODIFIED:20180213T144531Z
TRANSP:OPAQUE
END:VEVENT
* Yard Goats vs. Fisher Cats
<2018-04-08 Sun 12:05-15:05>
:PROPERTIES:
:ID:       OzxweHo095bSwCRJWccGoW22@stanza.co
:LOCATION: Home Run for Autism Day
:STATUS:   CONFIRMED
:END:

Yard Goats vs. Fisher Cats 





Buy tickets here  https //stza.co/~vLky

Follow on MiLB First Pitch  https //stza.co/+vLky-B

Shop  https //stza.co/+vLky-3p

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Yard Goats vs. Fisher Cats
END:VALARM
DTSTART:20180408T170500Z
DTEND:20180408T200500Z
UID:OzxweHo095bSwCRJWccGoW22@stanza.co
SUMMARY:Yard Goats vs. Fisher Cats
DESCRIPTION:\n\n\n\n\n\nBuy tickets here: https://stza.co/~vLky\n\nFollow on MiLB First Pitch: https://stza.co/+vLky-B\n\nShop: https://stza.co/+vLky-3p\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Home Run for Autism Day
STATUS:CONFIRMED
CREATED:20180213T144531Z
LAST-MODIFIED:20180213T144531Z
TRANSP:OPAQUE
END:VEVENT
* Yard Goats vs. Flying Squirrels
<2018-04-09 Mon 18:05-21:05>
:PROPERTIES:
:ID:       Jju27aZJGg3t3rHUH0MfLnzx@stanza.co
:LOCATION: Umbrella Giveaway
:STATUS:   CONFIRMED
:END:

Yard Goats vs. Flying Squirrels 



Buy tickets here  https //stza.co/~vLkz

Follow on MiLB First Pitch  https //stza.co/+vLkz-15

Shop  https //stza.co/+vLkz-2q

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Yard Goats vs. Flying Squirrels
END:VALARM
DTSTART:20180409T230500Z
DTEND:20180410T020500Z
UID:Jju27aZJGg3t3rHUH0MfLnzx@stanza.co
SUMMARY:Yard Goats vs. Flying Squirrels
DESCRIPTION:\n\n\n\nBuy tickets here: https://stza.co/~vLkz\n\nFollow on MiLB First Pitch: https://stza.co/+vLkz-15\n\nShop: https://stza.co/+vLkz-2q\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Umbrella Giveaway
STATUS:CONFIRMED
CREATED:20180213T144531Z
LAST-MODIFIED:20180213T144531Z
TRANSP:OPAQUE
END:VEVENT
* Yard Goats vs. Flying Squirrels
<2018-04-10 Tue 18:05-21:05>
:PROPERTIES:
:ID:       so0c8FPTca9YABpQ6pDHA0zU@stanza.co
:LOCATION: Most Improved Student Night
:STATUS:   CONFIRMED
:END:

Yard Goats vs. Flying Squirrels 

Play BINGO while watching the Yard Goats play baseball and win great prizes!

Buy tickets here  https //stza.co/~vLkC

Follow on MiLB First Pitch  https //stza.co/+vLkC-

Shop  https //stza.co/+vLkC-1l

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Yard Goats vs. Flying Squirrels
END:VALARM
DTSTART:20180410T230500Z
DTEND:20180411T020500Z
UID:so0c8FPTca9YABpQ6pDHA0zU@stanza.co
SUMMARY:Yard Goats vs. Flying Squirrels
DESCRIPTION:\n\nPlay BINGO while watching the Yard Goats play baseball and win great prizes!\n\nBuy tickets here: https://stza.co/~vLkC\n\nFollow on MiLB First Pitch: https://stza.co/+vLkC-\n\nShop: https://stza.co/+vLkC-1l\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Most Improved Student Night
STATUS:CONFIRMED
CREATED:20180213T144531Z
LAST-MODIFIED:20180213T144531Z
TRANSP:OPAQUE
END:VEVENT
* Yard Goats vs. Flying Squirrels
<2018-04-11 Wed 18:05-21:05>
:PROPERTIES:
:ID:       NwHHd-tlWeRBcYIEKaowbYbY@stanza.co
:LOCATION: Baseball Cap Giveaway
:STATUS:   CONFIRMED
:END:

Yard Goats vs. Flying Squirrels 



Buy tickets here  https //stza.co/~vLkE

Follow on MiLB First Pitch  https //stza.co/+vLkE-H

Shop  https //stza.co/+vLkE-3l

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Yard Goats vs. Flying Squirrels
END:VALARM
DTSTART:20180411T230500Z
DTEND:20180412T020500Z
UID:NwHHd-tlWeRBcYIEKaowbYbY@stanza.co
SUMMARY:Yard Goats vs. Flying Squirrels
DESCRIPTION:\n\n\n\nBuy tickets here: https://stza.co/~vLkE\n\nFollow on MiLB First Pitch: https://stza.co/+vLkE-H\n\nShop: https://stza.co/+vLkE-3l\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Baseball Cap Giveaway
STATUS:CONFIRMED
CREATED:20180213T144531Z
LAST-MODIFIED:20180213T144531Z
TRANSP:OPAQUE
END:VEVENT
* Yard Goats @ Fisher Cats
<2018-04-13 Fri 17:35-20:35>
:PROPERTIES:
:ID:       9T9mN9YuxyHApqjNk2KjCxCx@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Yard Goats @ Fisher Cats Yard Goats @ Fisher Cats

Follow on MiLB First Pitch  https //stza.co/+vLmD-1d

Shop  https //stza.co/+vLmD-1v

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Yard Goats @ Fisher Cats
END:VALARM
DTSTART:20180413T223500Z
DTEND:20180414T013500Z
UID:9T9mN9YuxyHApqjNk2KjCxCx@stanza.co
SUMMARY:Yard Goats @ Fisher Cats
DESCRIPTION:Yard Goats @ Fisher Cats\n\nFollow on MiLB First Pitch: https://stza.co/+vLmD-1d\n\nShop: https://stza.co/+vLmD-1v\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144531Z
LAST-MODIFIED:20180213T144531Z
TRANSP:OPAQUE
END:VEVENT
* Yard Goats @ Fisher Cats
<2018-04-14 Sat 17:35-20:35>
:PROPERTIES:
:ID:       iOHcVBNgatjA0t0UJJvHb3YV@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Yard Goats @ Fisher Cats Yard Goats @ Fisher Cats

Follow on MiLB First Pitch  https //stza.co/+vLmE-2a

Shop  https //stza.co/+vLmE-3q

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Yard Goats @ Fisher Cats
END:VALARM
DTSTART:20180414T223500Z
DTEND:20180415T013500Z
UID:iOHcVBNgatjA0t0UJJvHb3YV@stanza.co
SUMMARY:Yard Goats @ Fisher Cats
DESCRIPTION:Yard Goats @ Fisher Cats\n\nFollow on MiLB First Pitch: https://stza.co/+vLmE-2a\n\nShop: https://stza.co/+vLmE-3q\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144531Z
LAST-MODIFIED:20180213T144531Z
TRANSP:OPAQUE
END:VEVENT
* Yard Goats @ Fisher Cats
<2018-04-15 Sun 12:35-15:35>
:PROPERTIES:
:ID:       ff7tJUqssP6WegsSeBguXg7c@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Yard Goats @ Fisher Cats Yard Goats @ Fisher Cats

Follow on MiLB First Pitch  https //stza.co/+vLmF-3O

Shop  https //stza.co/+vLmF-P

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Yard Goats @ Fisher Cats
END:VALARM
DTSTART:20180415T173500Z
DTEND:20180415T203500Z
UID:ff7tJUqssP6WegsSeBguXg7c@stanza.co
SUMMARY:Yard Goats @ Fisher Cats
DESCRIPTION:Yard Goats @ Fisher Cats\n\nFollow on MiLB First Pitch: https://stza.co/+vLmF-3O\n\nShop: https://stza.co/+vLmF-P\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144531Z
LAST-MODIFIED:20180213T144531Z
TRANSP:OPAQUE
END:VEVENT
* Yard Goats @ Sea Dogs
<2018-04-16 Mon 17:00-20:00>
:PROPERTIES:
:ID:       2wYmtgbxajM_-DaqwnBB9cDR@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Yard Goats @ Sea Dogs Yard Goats @ Sea Dogs

Buy tickets here  https //stza.co/~vLmO

Follow on MiLB First Pitch  https //stza.co/+vLmO-9

Shop  https //stza.co/+vLmO-3D

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Yard Goats @ Sea Dogs
END:VALARM
DTSTART:20180416T220000Z
DTEND:20180417T010000Z
UID:2wYmtgbxajM_-DaqwnBB9cDR@stanza.co
SUMMARY:Yard Goats @ Sea Dogs
DESCRIPTION:Yard Goats @ Sea Dogs\n\nBuy tickets here: https://stza.co/~vLmO\n\nFollow on MiLB First Pitch: https://stza.co/+vLmO-9\n\nShop: https://stza.co/+vLmO-3D\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144531Z
LAST-MODIFIED:20180213T144531Z
TRANSP:OPAQUE
END:VEVENT
* Yard Goats @ Sea Dogs
<2018-04-17 Tue 17:00-20:00>
:PROPERTIES:
:ID:       G5JYuIYZ9CSIFVPLCc700Nh1@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Yard Goats @ Sea Dogs Yard Goats @ Sea Dogs

Buy tickets here  https //stza.co/~vLmP

Follow on MiLB First Pitch  https //stza.co/+vLmP-T

Shop  https //stza.co/+vLmP-38

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Yard Goats @ Sea Dogs
END:VALARM
DTSTART:20180417T220000Z
DTEND:20180418T010000Z
UID:G5JYuIYZ9CSIFVPLCc700Nh1@stanza.co
SUMMARY:Yard Goats @ Sea Dogs
DESCRIPTION:Yard Goats @ Sea Dogs\n\nBuy tickets here: https://stza.co/~vLmP\n\nFollow on MiLB First Pitch: https://stza.co/+vLmP-T\n\nShop: https://stza.co/+vLmP-38\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144531Z
LAST-MODIFIED:20180213T144531Z
TRANSP:OPAQUE
END:VEVENT
* Yard Goats @ Sea Dogs
<2018-04-18 Wed 17:00-20:00>
:PROPERTIES:
:ID:       Gf-dKUO_T1yO8wNF_A6jQsIZ@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Yard Goats @ Sea Dogs Yard Goats @ Sea Dogs

Buy tickets here  https //stza.co/~vLmQ

Follow on MiLB First Pitch  https //stza.co/+vLmQ-3M

Shop  https //stza.co/+vLmQ-2U

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Yard Goats @ Sea Dogs
END:VALARM
DTSTART:20180418T220000Z
DTEND:20180419T010000Z
UID:Gf-dKUO_T1yO8wNF_A6jQsIZ@stanza.co
SUMMARY:Yard Goats @ Sea Dogs
DESCRIPTION:Yard Goats @ Sea Dogs\n\nBuy tickets here: https://stza.co/~vLmQ\n\nFollow on MiLB First Pitch: https://stza.co/+vLmQ-3M\n\nShop: https://stza.co/+vLmQ-2U\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144531Z
LAST-MODIFIED:20180213T144531Z
TRANSP:OPAQUE
END:VEVENT
* Yard Goats @ Sea Dogs
<2018-04-19 Thu 11:00-14:00>
:PROPERTIES:
:ID:       IKKA28yqCHVPs1RBn0fqM8Wo@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Yard Goats @ Sea Dogs Yard Goats @ Sea Dogs

Buy tickets here  https //stza.co/~vLmR

Follow on MiLB First Pitch  https //stza.co/+vLmR-30

Shop  https //stza.co/+vLmR-2v

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Yard Goats @ Sea Dogs
END:VALARM
DTSTART:20180419T160000Z
DTEND:20180419T190000Z
UID:IKKA28yqCHVPs1RBn0fqM8Wo@stanza.co
SUMMARY:Yard Goats @ Sea Dogs
DESCRIPTION:Yard Goats @ Sea Dogs\n\nBuy tickets here: https://stza.co/~vLmR\n\nFollow on MiLB First Pitch: https://stza.co/+vLmR-30\n\nShop: https://stza.co/+vLmR-2v\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144531Z
LAST-MODIFIED:20180213T144531Z
TRANSP:OPAQUE
END:VEVENT
* Yard Goats vs. Senators
<2018-04-20 Fri 18:05-21:05>
:PROPERTIES:
:ID:       bW-YXn0rR78J6YcJwIZQPnFG@stanza.co
:LOCATION: Swipe for last minute tickets for tonight's game. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Yard Goats vs. Senators Yard Goats vs. Senators

Buy tickets here  https //stza.co/~vLkF

Follow on MiLB First Pitch  https //stza.co/+vLkF-S

Shop  https //stza.co/+vLkF-3X

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Yard Goats vs. Senators
END:VALARM
DTSTART:20180420T230500Z
DTEND:20180421T020500Z
UID:bW-YXn0rR78J6YcJwIZQPnFG@stanza.co
SUMMARY:Yard Goats vs. Senators
DESCRIPTION:Yard Goats vs. Senators\n\nBuy tickets here: https://stza.co/~vLkF\n\nFollow on MiLB First Pitch: https://stza.co/+vLkF-S\n\nShop: https://stza.co/+vLkF-3X\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Swipe for last minute tickets for tonight's game. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144531Z
LAST-MODIFIED:20180213T144531Z
TRANSP:OPAQUE
END:VEVENT
* Yard Goats vs. Senators
<2018-04-21 Sat 17:05-20:05>
:PROPERTIES:
:ID:       xzZj5EDJC7kX0KdLfTL8V14U@stanza.co
:LOCATION: Ready for the game? Swipe for tickets and more information.
:STATUS:   CONFIRMED
:END:

Yard Goats vs. Senators Yard Goats vs. Senators

Buy tickets here  https //stza.co/~vLkI

Follow on MiLB First Pitch  https //stza.co/+vLkI-2m

Shop  https //stza.co/+vLkI-1G

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Yard Goats vs. Senators
END:VALARM
DTSTART:20180421T220500Z
DTEND:20180422T010500Z
UID:xzZj5EDJC7kX0KdLfTL8V14U@stanza.co
SUMMARY:Yard Goats vs. Senators
DESCRIPTION:Yard Goats vs. Senators\n\nBuy tickets here: https://stza.co/~vLkI\n\nFollow on MiLB First Pitch: https://stza.co/+vLkI-2m\n\nShop: https://stza.co/+vLkI-1G\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Swipe for tickets and more information.
STATUS:CONFIRMED
CREATED:20180213T144531Z
LAST-MODIFIED:20180213T144531Z
TRANSP:OPAQUE
END:VEVENT
* Yard Goats vs. Senators
<2018-04-22 Sun 12:05-15:05>
:PROPERTIES:
:ID:       RYKnFz2a6POBMi8V_v_cUk-_@stanza.co
:LOCATION: Healthy Kids Baseball Summit
:STATUS:   CONFIRMED
:END:

Yard Goats vs. Senators 



Buy tickets here  https //stza.co/~vLkJ

Follow on MiLB First Pitch  https //stza.co/+vLkJ-r

Shop  https //stza.co/+vLkJ-D

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Yard Goats vs. Senators
END:VALARM
DTSTART:20180422T170500Z
DTEND:20180422T200500Z
UID:RYKnFz2a6POBMi8V_v_cUk-_@stanza.co
SUMMARY:Yard Goats vs. Senators
DESCRIPTION:\n\n\n\nBuy tickets here: https://stza.co/~vLkJ\n\nFollow on MiLB First Pitch: https://stza.co/+vLkJ-r\n\nShop: https://stza.co/+vLkJ-D\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Healthy Kids Baseball Summit
STATUS:CONFIRMED
CREATED:20180213T144531Z
LAST-MODIFIED:20180213T144531Z
TRANSP:OPAQUE
END:VEVENT
* Yard Goats vs. Sea Dogs
<2018-04-23 Mon 18:05-21:05>
:PROPERTIES:
:ID:       hMvlaGhKqj68oxtw-BYJbVv3@stanza.co
:LOCATION: Looking for something to do tonight? Get tickets here for tonight’s game and view promotions.
:STATUS:   CONFIRMED
:END:

Yard Goats vs. Sea Dogs Yard Goats vs. Sea Dogs

Buy tickets here  https //stza.co/~vLkM

Follow on MiLB First Pitch  https //stza.co/+vLkM-3H

Shop  https //stza.co/+vLkM-1X

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Yard Goats vs. Sea Dogs
END:VALARM
DTSTART:20180423T230500Z
DTEND:20180424T020500Z
UID:hMvlaGhKqj68oxtw-BYJbVv3@stanza.co
SUMMARY:Yard Goats vs. Sea Dogs
DESCRIPTION:Yard Goats vs. Sea Dogs\n\nBuy tickets here: https://stza.co/~vLkM\n\nFollow on MiLB First Pitch: https://stza.co/+vLkM-3H\n\nShop: https://stza.co/+vLkM-1X\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Looking for something to do tonight? Get tickets here for tonight’s game and view promotions.
STATUS:CONFIRMED
CREATED:20180213T144531Z
LAST-MODIFIED:20180213T144531Z
TRANSP:OPAQUE
END:VEVENT
* Yard Goats vs. Sea Dogs
<2018-04-24 Tue 18:05-21:05>
:PROPERTIES:
:ID:       QVT7lDex9i2tKwsYDW8RjQan@stanza.co
:LOCATION: Baseball BINGO
:STATUS:   CONFIRMED
:END:

Yard Goats vs. Sea Dogs Play BINGO while watching the Yard Goats play baseball and win great prizes!

Buy tickets here  https //stza.co/~vLkN

Follow on MiLB First Pitch  https //stza.co/+vLkN-C

Shop  https //stza.co/+vLkN-3Q

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Yard Goats vs. Sea Dogs
END:VALARM
DTSTART:20180424T230500Z
DTEND:20180425T020500Z
UID:QVT7lDex9i2tKwsYDW8RjQan@stanza.co
SUMMARY:Yard Goats vs. Sea Dogs
DESCRIPTION:Play BINGO while watching the Yard Goats play baseball and win great prizes!\n\nBuy tickets here: https://stza.co/~vLkN\n\nFollow on MiLB First Pitch: https://stza.co/+vLkN-C\n\nShop: https://stza.co/+vLkN-3Q\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Baseball BINGO
STATUS:CONFIRMED
CREATED:20180213T144531Z
LAST-MODIFIED:20180213T144531Z
TRANSP:OPAQUE
END:VEVENT
* Yard Goats vs. Sea Dogs
<2018-04-25 Wed 18:05-21:05>
:PROPERTIES:
:ID:       xdEykpAfnZ-lbUOhax_Z41sa@stanza.co
:LOCATION: Great seats still available for tonight’s game. Purchase them here.
:STATUS:   CONFIRMED
:END:

Yard Goats vs. Sea Dogs Yard Goats vs. Sea Dogs

Buy tickets here  https //stza.co/~vLkQ

Follow on MiLB First Pitch  https //stza.co/+vLkQ-3h

Shop  https //stza.co/+vLkQ-o

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Yard Goats vs. Sea Dogs
END:VALARM
DTSTART:20180425T230500Z
DTEND:20180426T020500Z
UID:xdEykpAfnZ-lbUOhax_Z41sa@stanza.co
SUMMARY:Yard Goats vs. Sea Dogs
DESCRIPTION:Yard Goats vs. Sea Dogs\n\nBuy tickets here: https://stza.co/~vLkQ\n\nFollow on MiLB First Pitch: https://stza.co/+vLkQ-3h\n\nShop: https://stza.co/+vLkQ-o\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Great seats still available for tonight’s game. Purchase them here.
STATUS:CONFIRMED
CREATED:20180213T144531Z
LAST-MODIFIED:20180213T144531Z
TRANSP:OPAQUE
END:VEVENT
* Yard Goats @ Flying Squirrels
<2018-04-27 Fri 18:05-21:05>
:PROPERTIES:
:ID:       QKpel31zCCiO59BffO_v09kC@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Yard Goats @ Flying Squirrels Yard Goats @ Flying Squirrels

Follow on MiLB First Pitch  https //stza.co/+v9ma-r

Shop  https //stza.co/+v9ma-n

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Yard Goats @ Flying Squirrels
END:VALARM
DTSTART:20180427T230500Z
DTEND:20180428T020500Z
UID:QKpel31zCCiO59BffO_v09kC@stanza.co
SUMMARY:Yard Goats @ Flying Squirrels
DESCRIPTION:Yard Goats @ Flying Squirrels\n\nFollow on MiLB First Pitch: https://stza.co/+v9ma-r\n\nShop: https://stza.co/+v9ma-n\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144531Z
LAST-MODIFIED:20180213T144531Z
TRANSP:OPAQUE
END:VEVENT
* Yard Goats @ Flying Squirrels
<2018-04-28 Sat 17:05-20:05>
:PROPERTIES:
:ID:       9ENR4lztkbt1YQRz_M_KA0AJ@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Yard Goats @ Flying Squirrels Yard Goats @ Flying Squirrels

Follow on MiLB First Pitch  https //stza.co/+v9mb-3U

Shop  https //stza.co/+v9mb-3E

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Yard Goats @ Flying Squirrels
END:VALARM
DTSTART:20180428T220500Z
DTEND:20180429T010500Z
UID:9ENR4lztkbt1YQRz_M_KA0AJ@stanza.co
SUMMARY:Yard Goats @ Flying Squirrels
DESCRIPTION:Yard Goats @ Flying Squirrels\n\nFollow on MiLB First Pitch: https://stza.co/+v9mb-3U\n\nShop: https://stza.co/+v9mb-3E\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144531Z
LAST-MODIFIED:20180213T144531Z
TRANSP:OPAQUE
END:VEVENT
* Yard Goats @ Flying Squirrels
<2018-04-29 Sun 12:05-15:05>
:PROPERTIES:
:ID:       LAIyA27-2_W12L2e0p0xwxUt@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Yard Goats @ Flying Squirrels Yard Goats @ Flying Squirrels

Follow on MiLB First Pitch  https //stza.co/+v9mc-J

Shop  https //stza.co/+v9mc-1H

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Yard Goats @ Flying Squirrels
END:VALARM
DTSTART:20180429T170500Z
DTEND:20180429T200500Z
UID:LAIyA27-2_W12L2e0p0xwxUt@stanza.co
SUMMARY:Yard Goats @ Flying Squirrels
DESCRIPTION:Yard Goats @ Flying Squirrels\n\nFollow on MiLB First Pitch: https://stza.co/+v9mc-J\n\nShop: https://stza.co/+v9mc-1H\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144531Z
LAST-MODIFIED:20180213T144531Z
TRANSP:OPAQUE
END:VEVENT
* Yard Goats @ Senators
<2018-04-30 Mon 17:30-20:30>
:PROPERTIES:
:ID:       15AvS-o90OLvBNpLRtfgLjh8@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Yard Goats @ Senators Yard Goats @ Senators

Follow on MiLB First Pitch  https //stza.co/+vLkh-1k

Shop  https //stza.co/+vLkh-2n

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Yard Goats @ Senators
END:VALARM
DTSTART:20180430T223000Z
DTEND:20180501T013000Z
UID:15AvS-o90OLvBNpLRtfgLjh8@stanza.co
SUMMARY:Yard Goats @ Senators
DESCRIPTION:Yard Goats @ Senators\n\nFollow on MiLB First Pitch: https://stza.co/+vLkh-1k\n\nShop: https://stza.co/+vLkh-2n\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144531Z
LAST-MODIFIED:20180213T144531Z
TRANSP:OPAQUE
END:VEVENT
* Yard Goats @ Senators
<2018-05-01 Tue 17:30-20:30>
:PROPERTIES:
:ID:       Qg_4kANq3z4HE9H-QA3LBlF9@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Yard Goats @ Senators Yard Goats @ Senators

Follow on MiLB First Pitch  https //stza.co/+vLki-33

Shop  https //stza.co/+vLki-3H

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Yard Goats @ Senators
END:VALARM
DTSTART:20180501T223000Z
DTEND:20180502T013000Z
UID:Qg_4kANq3z4HE9H-QA3LBlF9@stanza.co
SUMMARY:Yard Goats @ Senators
DESCRIPTION:Yard Goats @ Senators\n\nFollow on MiLB First Pitch: https://stza.co/+vLki-33\n\nShop: https://stza.co/+vLki-3H\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144531Z
LAST-MODIFIED:20180213T144531Z
TRANSP:OPAQUE
END:VEVENT
* Yard Goats @ Senators
<2018-05-02 Wed 09:30-12:30>
:PROPERTIES:
:ID:       sBhhH9txvodcKj26C_csI9CK@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Yard Goats @ Senators Yard Goats @ Senators

Follow on MiLB First Pitch  https //stza.co/+vLkj-2h

Shop  https //stza.co/+vLkj-3P

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Yard Goats @ Senators
END:VALARM
DTSTART:20180502T143000Z
DTEND:20180502T173000Z
UID:sBhhH9txvodcKj26C_csI9CK@stanza.co
SUMMARY:Yard Goats @ Senators
DESCRIPTION:Yard Goats @ Senators\n\nFollow on MiLB First Pitch: https://stza.co/+vLkj-2h\n\nShop: https://stza.co/+vLkj-3P\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144531Z
LAST-MODIFIED:20180213T144531Z
TRANSP:OPAQUE
END:VEVENT
* Yard Goats vs. Sea Dogs
<2018-05-03 Thu 18:05-21:05>
:PROPERTIES:
:ID:       QEpgA4o5hse1vA4dACMLit2V@stanza.co
:LOCATION: Need something fun to do tonight? Get Yard Goats tickets here.
:STATUS:   CONFIRMED
:END:

Yard Goats vs. Sea Dogs Yard Goats vs. Sea Dogs

Buy tickets here  https //stza.co/~vLkS

Follow on MiLB First Pitch  https //stza.co/+vLkS-1

Shop  https //stza.co/+vLkS-19

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Yard Goats vs. Sea Dogs
END:VALARM
DTSTART:20180503T230500Z
DTEND:20180504T020500Z
UID:QEpgA4o5hse1vA4dACMLit2V@stanza.co
SUMMARY:Yard Goats vs. Sea Dogs
DESCRIPTION:Yard Goats vs. Sea Dogs\n\nBuy tickets here: https://stza.co/~vLkS\n\nFollow on MiLB First Pitch: https://stza.co/+vLkS-1\n\nShop: https://stza.co/+vLkS-19\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Need something fun to do tonight? Get Yard Goats tickets here.
STATUS:CONFIRMED
CREATED:20180213T144531Z
LAST-MODIFIED:20180213T144531Z
TRANSP:OPAQUE
END:VEVENT
* Yard Goats vs. Sea Dogs
<2018-05-04 Fri 18:05-21:05>
:PROPERTIES:
:ID:       bDI3NYeJQIxkSLlDr3X0T4Jc@stanza.co
:LOCATION: Don’t miss out! Yard Goats tickets still available here.
:STATUS:   CONFIRMED
:END:

Yard Goats vs. Sea Dogs Yard Goats vs. Sea Dogs

Buy tickets here  https //stza.co/~vLkT

Follow on MiLB First Pitch  https //stza.co/+vLkT-3L

Shop  https //stza.co/+vLkT-3w

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Yard Goats vs. Sea Dogs
END:VALARM
DTSTART:20180504T230500Z
DTEND:20180505T020500Z
UID:bDI3NYeJQIxkSLlDr3X0T4Jc@stanza.co
SUMMARY:Yard Goats vs. Sea Dogs
DESCRIPTION:Yard Goats vs. Sea Dogs\n\nBuy tickets here: https://stza.co/~vLkT\n\nFollow on MiLB First Pitch: https://stza.co/+vLkT-3L\n\nShop: https://stza.co/+vLkT-3w\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don’t miss out! Yard Goats tickets still available here.
STATUS:CONFIRMED
CREATED:20180213T144531Z
LAST-MODIFIED:20180213T144531Z
TRANSP:OPAQUE
END:VEVENT
* Yard Goats vs. Sea Dogs
<2018-05-05 Sat 17:05-20:05>
:PROPERTIES:
:ID:       RJmX8WJa0msxlgKJhWbN8M40@stanza.co
:LOCATION: Atlas Fireworks
:STATUS:   CONFIRMED
:END:

Yard Goats vs. Sea Dogs 

Come out to the game with your Boy Scout Troop and camp out on the field after the game. 

With pre-game player forum.

Buy tickets here  https //stza.co/~vLkV

Follow on MiLB First Pitch  https //stza.co/+vLkV-1y

Shop  https //stza.co/+vLkV-3n

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Yard Goats vs. Sea Dogs
END:VALARM
DTSTART:20180505T220500Z
DTEND:20180506T010500Z
UID:RJmX8WJa0msxlgKJhWbN8M40@stanza.co
SUMMARY:Yard Goats vs. Sea Dogs
DESCRIPTION:\n\nCome out to the game with your Boy Scout Troop and camp out on the field after the game. \n\nWith pre-game player forum.\n\nBuy tickets here: https://stza.co/~vLkV\n\nFollow on MiLB First Pitch: https://stza.co/+vLkV-1y\n\nShop: https://stza.co/+vLkV-3n\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Atlas Fireworks
STATUS:CONFIRMED
CREATED:20180213T144531Z
LAST-MODIFIED:20180213T144531Z
TRANSP:OPAQUE
END:VEVENT
* Yard Goats vs. Sea Dogs
<2018-05-06 Sun 12:05-15:05>
:PROPERTIES:
:ID:       HWDpbeSg7npd5FLKVIgw1w6v@stanza.co
:LOCATION: Swipe to get tickets for the game tonight. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Yard Goats vs. Sea Dogs Yard Goats vs. Sea Dogs

Buy tickets here  https //stza.co/~vLkX

Follow on MiLB First Pitch  https //stza.co/+vLkX-3R

Shop  https //stza.co/+vLkX-2_

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Yard Goats vs. Sea Dogs
END:VALARM
DTSTART:20180506T170500Z
DTEND:20180506T200500Z
UID:HWDpbeSg7npd5FLKVIgw1w6v@stanza.co
SUMMARY:Yard Goats vs. Sea Dogs
DESCRIPTION:Yard Goats vs. Sea Dogs\n\nBuy tickets here: https://stza.co/~vLkX\n\nFollow on MiLB First Pitch: https://stza.co/+vLkX-3R\n\nShop: https://stza.co/+vLkX-2_\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Swipe to get tickets for the game tonight. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144531Z
LAST-MODIFIED:20180213T144531Z
TRANSP:OPAQUE
END:VEVENT
* Yard Goats vs. Rumble Ponies
<2018-05-07 Mon 18:05-21:05>
:PROPERTIES:
:ID:       CvuLg94pcRuGzf9y7VsEQxk-@stanza.co
:LOCATION: Fancy Pants Goat Bobblehead Giveaway
:STATUS:   CONFIRMED
:END:

Yard Goats vs. Rumble Ponies Everyone's favorite goat, Fancy Pants!

Buy tickets here  https //stza.co/~vLkZ

Follow on MiLB First Pitch  https //stza.co/+vLkZ-3a

Shop  https //stza.co/+vLkZ-1O

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Yard Goats vs. Rumble Ponies
END:VALARM
DTSTART:20180507T230500Z
DTEND:20180508T020500Z
UID:CvuLg94pcRuGzf9y7VsEQxk-@stanza.co
SUMMARY:Yard Goats vs. Rumble Ponies
DESCRIPTION:Everyone's favorite goat, Fancy Pants!\n\nBuy tickets here: https://stza.co/~vLkZ\n\nFollow on MiLB First Pitch: https://stza.co/+vLkZ-3a\n\nShop: https://stza.co/+vLkZ-1O\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Fancy Pants Goat Bobblehead Giveaway
STATUS:CONFIRMED
CREATED:20180213T144531Z
LAST-MODIFIED:20180213T144531Z
TRANSP:OPAQUE
END:VEVENT
* Yard Goats vs. Rumble Ponies
<2018-05-08 Tue 18:05-21:05>
:PROPERTIES:
:ID:       P_Gwd0ooPg0Ti28c03s7xFtV@stanza.co
:LOCATION: Baseball BINGO
:STATUS:   CONFIRMED
:END:

Yard Goats vs. Rumble Ponies Play BINGO while watching the Yard Goats play baseball and win great prizes!

Buy tickets here  https //stza.co/~vLl0

Follow on MiLB First Pitch  https //stza.co/+vLl0-3I

Shop  https //stza.co/+vLl0-3z

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Yard Goats vs. Rumble Ponies
END:VALARM
DTSTART:20180508T230500Z
DTEND:20180509T020500Z
UID:P_Gwd0ooPg0Ti28c03s7xFtV@stanza.co
SUMMARY:Yard Goats vs. Rumble Ponies
DESCRIPTION:Play BINGO while watching the Yard Goats play baseball and win great prizes!\n\nBuy tickets here: https://stza.co/~vLl0\n\nFollow on MiLB First Pitch: https://stza.co/+vLl0-3I\n\nShop: https://stza.co/+vLl0-3z\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Baseball BINGO
STATUS:CONFIRMED
CREATED:20180213T144531Z
LAST-MODIFIED:20180213T144531Z
TRANSP:OPAQUE
END:VEVENT
* Yard Goats vs. Rumble Ponies
<2018-05-09 Wed 09:35-12:35>
:PROPERTIES:
:ID:       Tl3iARu06TblfoTGCexfqLNz@stanza.co
:LOCATION: Baseball in Education
:STATUS:   CONFIRMED
:END:

Yard Goats vs. Rumble Ponies Come to the ballpark on a field trip with your school and learn while watching a baseball game. 

Buy tickets here  https //stza.co/~vLl1

Follow on MiLB First Pitch  https //stza.co/+vLl1-2K

Shop  https //stza.co/+vLl1-w

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Yard Goats vs. Rumble Ponies
END:VALARM
DTSTART:20180509T143500Z
DTEND:20180509T173500Z
UID:Tl3iARu06TblfoTGCexfqLNz@stanza.co
SUMMARY:Yard Goats vs. Rumble Ponies
DESCRIPTION:Come to the ballpark on a field trip with your school and learn while watching a baseball game. \n\nBuy tickets here: https://stza.co/~vLl1\n\nFollow on MiLB First Pitch: https://stza.co/+vLl1-2K\n\nShop: https://stza.co/+vLl1-w\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Baseball in Education
STATUS:CONFIRMED
CREATED:20180213T144531Z
LAST-MODIFIED:20180213T144531Z
TRANSP:OPAQUE
END:VEVENT
* Yard Goats @ Baysox
<2018-05-10 Thu 17:35-20:35>
:PROPERTIES:
:ID:       Zm4ccMpL2bkyLL2N9vYuoKPF@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Yard Goats @ Baysox Yard Goats @ Baysox

Follow on MiLB First Pitch  https //stza.co/+vLka-1n

Shop  https //stza.co/+vLka-35

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Yard Goats @ Baysox
END:VALARM
DTSTART:20180510T223500Z
DTEND:20180511T013500Z
UID:Zm4ccMpL2bkyLL2N9vYuoKPF@stanza.co
SUMMARY:Yard Goats @ Baysox
DESCRIPTION:Yard Goats @ Baysox\n\nFollow on MiLB First Pitch: https://stza.co/+vLka-1n\n\nShop: https://stza.co/+vLka-35\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144531Z
LAST-MODIFIED:20180213T144531Z
TRANSP:OPAQUE
END:VEVENT
* Yard Goats @ Baysox
<2018-05-11 Fri 18:05-21:05>
:PROPERTIES:
:ID:       7nJa_4hfqX1AK8S_4ADrjuHD@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Yard Goats @ Baysox Yard Goats @ Baysox

Follow on MiLB First Pitch  https //stza.co/+vLkb-4

Shop  https //stza.co/+vLkb-I

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Yard Goats @ Baysox
END:VALARM
DTSTART:20180511T230500Z
DTEND:20180512T020500Z
UID:7nJa_4hfqX1AK8S_4ADrjuHD@stanza.co
SUMMARY:Yard Goats @ Baysox
DESCRIPTION:Yard Goats @ Baysox\n\nFollow on MiLB First Pitch: https://stza.co/+vLkb-4\n\nShop: https://stza.co/+vLkb-I\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144531Z
LAST-MODIFIED:20180213T144531Z
TRANSP:OPAQUE
END:VEVENT
* Yard Goats @ Baysox
<2018-05-12 Sat 17:35-20:35>
:PROPERTIES:
:ID:       nCPnjGhHfuJ6TSyJpyKlbwaI@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Yard Goats @ Baysox Yard Goats @ Baysox

Follow on MiLB First Pitch  https //stza.co/+vLkc-1W

Shop  https //stza.co/+vLkc-2O

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Yard Goats @ Baysox
END:VALARM
DTSTART:20180512T223500Z
DTEND:20180513T013500Z
UID:nCPnjGhHfuJ6TSyJpyKlbwaI@stanza.co
SUMMARY:Yard Goats @ Baysox
DESCRIPTION:Yard Goats @ Baysox\n\nFollow on MiLB First Pitch: https://stza.co/+vLkc-1W\n\nShop: https://stza.co/+vLkc-2O\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144531Z
LAST-MODIFIED:20180213T144531Z
TRANSP:OPAQUE
END:VEVENT
* Yard Goats @ Baysox
<2018-05-13 Sun 12:35-15:35>
:PROPERTIES:
:ID:       dBy3EBBXE6V7q9PDZdeEvLY7@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Yard Goats @ Baysox Yard Goats @ Baysox

Follow on MiLB First Pitch  https //stza.co/+vLkd-25

Shop  https //stza.co/+vLkd-M

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Yard Goats @ Baysox
END:VALARM
DTSTART:20180513T173500Z
DTEND:20180513T203500Z
UID:dBy3EBBXE6V7q9PDZdeEvLY7@stanza.co
SUMMARY:Yard Goats @ Baysox
DESCRIPTION:Yard Goats @ Baysox\n\nFollow on MiLB First Pitch: https://stza.co/+vLkd-25\n\nShop: https://stza.co/+vLkd-M\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144531Z
LAST-MODIFIED:20180213T144531Z
TRANSP:OPAQUE
END:VEVENT
* Yard Goats vs. Fisher Cats
<2018-05-14 Mon 18:05-21:05>
:PROPERTIES:
:ID:       sy7CgHEwDi0AVBX-xYUV3hxu@stanza.co
:LOCATION: Swipe for last minute tickets for tonight's game. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Yard Goats vs. Fisher Cats Yard Goats vs. Fisher Cats

Buy tickets here  https //stza.co/~vLl4

Follow on MiLB First Pitch  https //stza.co/+vLl4-c

Shop  https //stza.co/+vLl4-5

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Yard Goats vs. Fisher Cats
END:VALARM
DTSTART:20180514T230500Z
DTEND:20180515T020500Z
UID:sy7CgHEwDi0AVBX-xYUV3hxu@stanza.co
SUMMARY:Yard Goats vs. Fisher Cats
DESCRIPTION:Yard Goats vs. Fisher Cats\n\nBuy tickets here: https://stza.co/~vLl4\n\nFollow on MiLB First Pitch: https://stza.co/+vLl4-c\n\nShop: https://stza.co/+vLl4-5\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Swipe for last minute tickets for tonight's game. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144531Z
LAST-MODIFIED:20180213T144531Z
TRANSP:OPAQUE
END:VEVENT
* Yard Goats vs. Fisher Cats
<2018-05-15 Tue 18:05-21:05>
:PROPERTIES:
:ID:       cUedGcijWr-WTII9jtsLdgOl@stanza.co
:LOCATION: Appearance by Police Pup and Fire Dog
:STATUS:   CONFIRMED
:END:

Yard Goats vs. Fisher Cats 

Play BINGO while watching the Yard Goats play baseball and win great prizes!

Buy tickets here  https //stza.co/~vLl5

Follow on MiLB First Pitch  https //stza.co/+vLl5-32

Shop  https //stza.co/+vLl5-j

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Yard Goats vs. Fisher Cats
END:VALARM
DTSTART:20180515T230500Z
DTEND:20180516T020500Z
UID:cUedGcijWr-WTII9jtsLdgOl@stanza.co
SUMMARY:Yard Goats vs. Fisher Cats
DESCRIPTION:\n\nPlay BINGO while watching the Yard Goats play baseball and win great prizes!\n\nBuy tickets here: https://stza.co/~vLl5\n\nFollow on MiLB First Pitch: https://stza.co/+vLl5-32\n\nShop: https://stza.co/+vLl5-j\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Appearance by Police Pup and Fire Dog
STATUS:CONFIRMED
CREATED:20180213T144531Z
LAST-MODIFIED:20180213T144531Z
TRANSP:OPAQUE
END:VEVENT
* Yard Goats vs. Fisher Cats
<2018-05-16 Wed 09:35-12:35>
:PROPERTIES:
:ID:       dWOybgLk6gz5hHCdpxjo5cGK@stanza.co
:LOCATION: Baseball in Education
:STATUS:   CONFIRMED
:END:

Yard Goats vs. Fisher Cats Come to the ballpark on a field trip with your school and learn while watching a baseball game. 

Buy tickets here  https //stza.co/~vLl8

Follow on MiLB First Pitch  https //stza.co/+vLl8-3I

Shop  https //stza.co/+vLl8-1W

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Yard Goats vs. Fisher Cats
END:VALARM
DTSTART:20180516T143500Z
DTEND:20180516T173500Z
UID:dWOybgLk6gz5hHCdpxjo5cGK@stanza.co
SUMMARY:Yard Goats vs. Fisher Cats
DESCRIPTION:Come to the ballpark on a field trip with your school and learn while watching a baseball game. \n\nBuy tickets here: https://stza.co/~vLl8\n\nFollow on MiLB First Pitch: https://stza.co/+vLl8-3I\n\nShop: https://stza.co/+vLl8-1W\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Baseball in Education
STATUS:CONFIRMED
CREATED:20180213T144531Z
LAST-MODIFIED:20180213T144531Z
TRANSP:OPAQUE
END:VEVENT
* Yard Goats vs. RubberDucks
<2018-05-17 Thu 18:05-21:05>
:PROPERTIES:
:ID:       BheCsFUb9_KFzS6Wq6byQf9t@stanza.co
:LOCATION: Baseball Cap Giveaway
:STATUS:   CONFIRMED
:END:

Yard Goats vs. RubberDucks 

Join the Yard Goats in wearing pink and  supporting Susan G. Komen New England. 

Buy tickets here  https //stza.co/~vLla

Follow on MiLB First Pitch  https //stza.co/+vLla-2X

Shop  https //stza.co/+vLla-3Q

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Yard Goats vs. RubberDucks
END:VALARM
DTSTART:20180517T230500Z
DTEND:20180518T020500Z
UID:BheCsFUb9_KFzS6Wq6byQf9t@stanza.co
SUMMARY:Yard Goats vs. RubberDucks
DESCRIPTION:\n\nJoin the Yard Goats in wearing pink and  supporting Susan G. Komen New England. \n\nBuy tickets here: https://stza.co/~vLla\n\nFollow on MiLB First Pitch: https://stza.co/+vLla-2X\n\nShop: https://stza.co/+vLla-3Q\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Baseball Cap Giveaway
STATUS:CONFIRMED
CREATED:20180213T144531Z
LAST-MODIFIED:20180213T144531Z
TRANSP:OPAQUE
END:VEVENT
* Yard Goats vs. RubberDucks
<2018-05-18 Fri 18:05-21:05>
:PROPERTIES:
:ID:       L6nnUtYagoGSug9HRVEDAAG_@stanza.co
:LOCATION: Atlas Fireworks
:STATUS:   CONFIRMED
:END:

Yard Goats vs. RubberDucks 



Buy tickets here  https //stza.co/~vLlc

Follow on MiLB First Pitch  https //stza.co/+vLlc-30

Shop  https //stza.co/+vLlc-c

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Yard Goats vs. RubberDucks
END:VALARM
DTSTART:20180518T230500Z
DTEND:20180519T020500Z
UID:L6nnUtYagoGSug9HRVEDAAG_@stanza.co
SUMMARY:Yard Goats vs. RubberDucks
DESCRIPTION:\n\n\n\nBuy tickets here: https://stza.co/~vLlc\n\nFollow on MiLB First Pitch: https://stza.co/+vLlc-30\n\nShop: https://stza.co/+vLlc-c\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Atlas Fireworks
STATUS:CONFIRMED
CREATED:20180213T144531Z
LAST-MODIFIED:20180213T144531Z
TRANSP:OPAQUE
END:VEVENT
* Yard Goats vs. RubberDucks
<2018-05-19 Sat 17:05-20:05>
:PROPERTIES:
:ID:       W5p-rVT-7K49FzEdQOwyPYKb@stanza.co
:LOCATION: Atlas Fireworks
:STATUS:   CONFIRMED
:END:

Yard Goats vs. RubberDucks 





Buy tickets here  https //stza.co/~vLle

Follow on MiLB First Pitch  https //stza.co/+vLle-1H

Shop  https //stza.co/+vLle-3c

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Yard Goats vs. RubberDucks
END:VALARM
DTSTART:20180519T220500Z
DTEND:20180520T010500Z
UID:W5p-rVT-7K49FzEdQOwyPYKb@stanza.co
SUMMARY:Yard Goats vs. RubberDucks
DESCRIPTION:\n\n\n\n\n\nBuy tickets here: https://stza.co/~vLle\n\nFollow on MiLB First Pitch: https://stza.co/+vLle-1H\n\nShop: https://stza.co/+vLle-3c\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Atlas Fireworks
STATUS:CONFIRMED
CREATED:20180213T144531Z
LAST-MODIFIED:20180213T144531Z
TRANSP:OPAQUE
END:VEVENT
* Yard Goats vs. RubberDucks
<2018-05-20 Sun 12:05-15:05>
:PROPERTIES:
:ID:       jOW2wzKXwZArR2vpHvmJSk21@stanza.co
:LOCATION: Ready for the game? Swipe for tickets and more information.
:STATUS:   CONFIRMED
:END:

Yard Goats vs. RubberDucks Yard Goats vs. RubberDucks

Buy tickets here  https //stza.co/~vLlf

Follow on MiLB First Pitch  https //stza.co/+vLlf-3N

Shop  https //stza.co/+vLlf-9

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Yard Goats vs. RubberDucks
END:VALARM
DTSTART:20180520T170500Z
DTEND:20180520T200500Z
UID:jOW2wzKXwZArR2vpHvmJSk21@stanza.co
SUMMARY:Yard Goats vs. RubberDucks
DESCRIPTION:Yard Goats vs. RubberDucks\n\nBuy tickets here: https://stza.co/~vLlf\n\nFollow on MiLB First Pitch: https://stza.co/+vLlf-3N\n\nShop: https://stza.co/+vLlf-9\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Swipe for tickets and more information.
STATUS:CONFIRMED
CREATED:20180213T144531Z
LAST-MODIFIED:20180213T144531Z
TRANSP:OPAQUE
END:VEVENT
* Yard Goats @ Sea Dogs
<2018-05-22 Tue 17:00-20:00>
:PROPERTIES:
:ID:       pDg59aNBwKLSofJmxlOWk601@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Yard Goats @ Sea Dogs Yard Goats @ Sea Dogs

Buy tickets here  https //stza.co/~vLmS

Follow on MiLB First Pitch  https //stza.co/+vLmS-M

Shop  https //stza.co/+vLmS-p

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Yard Goats @ Sea Dogs
END:VALARM
DTSTART:20180522T220000Z
DTEND:20180523T010000Z
UID:pDg59aNBwKLSofJmxlOWk601@stanza.co
SUMMARY:Yard Goats @ Sea Dogs
DESCRIPTION:Yard Goats @ Sea Dogs\n\nBuy tickets here: https://stza.co/~vLmS\n\nFollow on MiLB First Pitch: https://stza.co/+vLmS-M\n\nShop: https://stza.co/+vLmS-p\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144531Z
LAST-MODIFIED:20180213T144531Z
TRANSP:OPAQUE
END:VEVENT
* Yard Goats @ Sea Dogs
<2018-05-23 Wed 17:00-20:00>
:PROPERTIES:
:ID:       qmV8EpMd_uE2J7VZyesPWuac@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Yard Goats @ Sea Dogs Yard Goats @ Sea Dogs

Buy tickets here  https //stza.co/~vLmT

Follow on MiLB First Pitch  https //stza.co/+vLmT-1i

Shop  https //stza.co/+vLmT-13

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Yard Goats @ Sea Dogs
END:VALARM
DTSTART:20180523T220000Z
DTEND:20180524T010000Z
UID:qmV8EpMd_uE2J7VZyesPWuac@stanza.co
SUMMARY:Yard Goats @ Sea Dogs
DESCRIPTION:Yard Goats @ Sea Dogs\n\nBuy tickets here: https://stza.co/~vLmT\n\nFollow on MiLB First Pitch: https://stza.co/+vLmT-1i\n\nShop: https://stza.co/+vLmT-13\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144531Z
LAST-MODIFIED:20180213T144531Z
TRANSP:OPAQUE
END:VEVENT
* Yard Goats @ Sea Dogs
<2018-05-24 Thu 10:00-13:00>
:PROPERTIES:
:ID:       QxDHlt7epGRpOFtTF9J4iaCI@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Yard Goats @ Sea Dogs Yard Goats @ Sea Dogs

Buy tickets here  https //stza.co/~vLmU

Follow on MiLB First Pitch  https //stza.co/+vLmU-3k

Shop  https //stza.co/+vLmU-2U

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Yard Goats @ Sea Dogs
END:VALARM
DTSTART:20180524T150000Z
DTEND:20180524T180000Z
UID:QxDHlt7epGRpOFtTF9J4iaCI@stanza.co
SUMMARY:Yard Goats @ Sea Dogs
DESCRIPTION:Yard Goats @ Sea Dogs\n\nBuy tickets here: https://stza.co/~vLmU\n\nFollow on MiLB First Pitch: https://stza.co/+vLmU-3k\n\nShop: https://stza.co/+vLmU-2U\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144531Z
LAST-MODIFIED:20180213T144531Z
TRANSP:OPAQUE
END:VEVENT
* Yard Goats @ Fisher Cats
<2018-05-25 Fri 17:35-20:35>
:PROPERTIES:
:ID:       afaoonxPXTwUfqgeT9uI_YUU@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Yard Goats @ Fisher Cats Yard Goats @ Fisher Cats

Follow on MiLB First Pitch  https //stza.co/+vLmG-2L

Shop  https //stza.co/+vLmG-A

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Yard Goats @ Fisher Cats
END:VALARM
DTSTART:20180525T223500Z
DTEND:20180526T013500Z
UID:afaoonxPXTwUfqgeT9uI_YUU@stanza.co
SUMMARY:Yard Goats @ Fisher Cats
DESCRIPTION:Yard Goats @ Fisher Cats\n\nFollow on MiLB First Pitch: https://stza.co/+vLmG-2L\n\nShop: https://stza.co/+vLmG-A\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144531Z
LAST-MODIFIED:20180213T144531Z
TRANSP:OPAQUE
END:VEVENT
* Yard Goats @ Fisher Cats
<2018-05-26 Sat 17:35-20:35>
:PROPERTIES:
:ID:       evRvakdaJrfv5S5yLtA2JDkQ@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Yard Goats @ Fisher Cats Yard Goats @ Fisher Cats

Follow on MiLB First Pitch  https //stza.co/+vLmH-1z

Shop  https //stza.co/+vLmH-m

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Yard Goats @ Fisher Cats
END:VALARM
DTSTART:20180526T223500Z
DTEND:20180527T013500Z
UID:evRvakdaJrfv5S5yLtA2JDkQ@stanza.co
SUMMARY:Yard Goats @ Fisher Cats
DESCRIPTION:Yard Goats @ Fisher Cats\n\nFollow on MiLB First Pitch: https://stza.co/+vLmH-1z\n\nShop: https://stza.co/+vLmH-m\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144531Z
LAST-MODIFIED:20180213T144531Z
TRANSP:OPAQUE
END:VEVENT
* Yard Goats @ Fisher Cats
<2018-05-27 Sun 12:35-15:35>
:PROPERTIES:
:ID:       iVTklut_HwJSiNNFnGw-P-Ow@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Yard Goats @ Fisher Cats Yard Goats @ Fisher Cats

Follow on MiLB First Pitch  https //stza.co/+vLmI-u

Shop  https //stza.co/+vLmI-7

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Yard Goats @ Fisher Cats
END:VALARM
DTSTART:20180527T173500Z
DTEND:20180527T203500Z
UID:iVTklut_HwJSiNNFnGw-P-Ow@stanza.co
SUMMARY:Yard Goats @ Fisher Cats
DESCRIPTION:Yard Goats @ Fisher Cats\n\nFollow on MiLB First Pitch: https://stza.co/+vLmI-u\n\nShop: https://stza.co/+vLmI-7\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144531Z
LAST-MODIFIED:20180213T144531Z
TRANSP:OPAQUE
END:VEVENT
* Yard Goats @ Fisher Cats
<2018-05-28 Mon 12:35-15:35>
:PROPERTIES:
:ID:       osX-Y8v-Qgh1hIpBHT8vROrK@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Yard Goats @ Fisher Cats Yard Goats @ Fisher Cats

Follow on MiLB First Pitch  https //stza.co/+vLmJ-7

Shop  https //stza.co/+vLmJ-3g

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Yard Goats @ Fisher Cats
END:VALARM
DTSTART:20180528T173500Z
DTEND:20180528T203500Z
UID:osX-Y8v-Qgh1hIpBHT8vROrK@stanza.co
SUMMARY:Yard Goats @ Fisher Cats
DESCRIPTION:Yard Goats @ Fisher Cats\n\nFollow on MiLB First Pitch: https://stza.co/+vLmJ-7\n\nShop: https://stza.co/+vLmJ-3g\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144531Z
LAST-MODIFIED:20180213T144531Z
TRANSP:OPAQUE
END:VEVENT
* Yard Goats vs. Senators
<2018-05-29 Tue 18:05-21:05>
:PROPERTIES:
:ID:       oNJYDuEzas_T7qojPfpQ5-l7@stanza.co
:LOCATION: Seasons Magazine Game
:STATUS:   CONFIRMED
:END:

Yard Goats vs. Senators 

Play BINGO while watching the Yard Goats play baseball and win great prizes!

Buy tickets here  https //stza.co/~vLlh

Follow on MiLB First Pitch  https //stza.co/+vLlh-1J

Shop  https //stza.co/+vLlh-2L

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Yard Goats vs. Senators
END:VALARM
DTSTART:20180529T230500Z
DTEND:20180530T020500Z
UID:oNJYDuEzas_T7qojPfpQ5-l7@stanza.co
SUMMARY:Yard Goats vs. Senators
DESCRIPTION:\n\nPlay BINGO while watching the Yard Goats play baseball and win great prizes!\n\nBuy tickets here: https://stza.co/~vLlh\n\nFollow on MiLB First Pitch: https://stza.co/+vLlh-1J\n\nShop: https://stza.co/+vLlh-2L\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Seasons Magazine Game
STATUS:CONFIRMED
CREATED:20180213T144531Z
LAST-MODIFIED:20180213T144531Z
TRANSP:OPAQUE
END:VEVENT
* Yard Goats vs. Senators
<2018-05-30 Wed 18:05-21:05>
:PROPERTIES:
:ID:       0-arCqT8w6HcvzdMDKc5VdeF@stanza.co
:LOCATION: Looking for something to do tonight? Get tickets here for tonight’s game and view promotions.
:STATUS:   CONFIRMED
:END:

Yard Goats vs. Senators Yard Goats vs. Senators

Buy tickets here  https //stza.co/~vLlk

Follow on MiLB First Pitch  https //stza.co/+vLlk-1f

Shop  https //stza.co/+vLlk-f

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Yard Goats vs. Senators
END:VALARM
DTSTART:20180530T230500Z
DTEND:20180531T020500Z
UID:0-arCqT8w6HcvzdMDKc5VdeF@stanza.co
SUMMARY:Yard Goats vs. Senators
DESCRIPTION:Yard Goats vs. Senators\n\nBuy tickets here: https://stza.co/~vLlk\n\nFollow on MiLB First Pitch: https://stza.co/+vLlk-1f\n\nShop: https://stza.co/+vLlk-f\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Looking for something to do tonight? Get tickets here for tonight’s game and view promotions.
STATUS:CONFIRMED
CREATED:20180213T144531Z
LAST-MODIFIED:20180213T144531Z
TRANSP:OPAQUE
END:VEVENT
* Yard Goats vs. Senators
<2018-05-31 Thu 09:35-12:35>
:PROPERTIES:
:ID:       91Z11P4OMZEFxy8NrRcwiXS8@stanza.co
:LOCATION: Baseball in Education
:STATUS:   CONFIRMED
:END:

Yard Goats vs. Senators Come to the ballpark on a field trip with your school and learn while watching a baseball game. 

Buy tickets here  https //stza.co/~vLlm

Follow on MiLB First Pitch  https //stza.co/+vLlm-1W

Shop  https //stza.co/+vLlm-3A

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Yard Goats vs. Senators
END:VALARM
DTSTART:20180531T143500Z
DTEND:20180531T173500Z
UID:91Z11P4OMZEFxy8NrRcwiXS8@stanza.co
SUMMARY:Yard Goats vs. Senators
DESCRIPTION:Come to the ballpark on a field trip with your school and learn while watching a baseball game. \n\nBuy tickets here: https://stza.co/~vLlm\n\nFollow on MiLB First Pitch: https://stza.co/+vLlm-1W\n\nShop: https://stza.co/+vLlm-3A\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Baseball in Education
STATUS:CONFIRMED
CREATED:20180213T144531Z
LAST-MODIFIED:20180213T144531Z
TRANSP:OPAQUE
END:VEVENT
* Yard Goats vs. Curve
<2018-06-01 Fri 18:05-21:05>
:PROPERTIES:
:ID:       EFVQvmo-leol_TJM2dCqCE1s@stanza.co
:LOCATION: May the force be with you! Come check out Stars Wars Night at the park
:STATUS:   CONFIRMED
:END:

Yard Goats vs. Curve 

Come to the ballpark dressed as your favorite Star Wars Character. 



Buy tickets here  https //stza.co/~vLlo

Follow on MiLB First Pitch  https //stza.co/+vLlo-1y

Shop  https //stza.co/+vLlo-p

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Yard Goats vs. Curve
END:VALARM
DTSTART:20180601T230500Z
DTEND:20180602T020500Z
UID:EFVQvmo-leol_TJM2dCqCE1s@stanza.co
SUMMARY:Yard Goats vs. Curve
DESCRIPTION:\n\nCome to the ballpark dressed as your favorite Star Wars Character. \n\n\n\nBuy tickets here: https://stza.co/~vLlo\n\nFollow on MiLB First Pitch: https://stza.co/+vLlo-1y\n\nShop: https://stza.co/+vLlo-p\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:May the force be with you! Come check out Stars Wars Night at the park
STATUS:CONFIRMED
CREATED:20180213T144531Z
LAST-MODIFIED:20180213T144531Z
TRANSP:OPAQUE
END:VEVENT
* Yard Goats vs. Curve
<2018-06-02 Sat 17:05-20:05>
:PROPERTIES:
:ID:       LlTgY4dIc5eKGYLlxe3L0BCG@stanza.co
:LOCATION: Atlas Fireworks
:STATUS:   CONFIRMED
:END:

Yard Goats vs. Curve 



Buy tickets here  https //stza.co/~vLlq

Follow on MiLB First Pitch  https //stza.co/+vLlq-1c

Shop  https //stza.co/+vLlq-V

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Yard Goats vs. Curve
END:VALARM
DTSTART:20180602T220500Z
DTEND:20180603T010500Z
UID:LlTgY4dIc5eKGYLlxe3L0BCG@stanza.co
SUMMARY:Yard Goats vs. Curve
DESCRIPTION:\n\n\n\nBuy tickets here: https://stza.co/~vLlq\n\nFollow on MiLB First Pitch: https://stza.co/+vLlq-1c\n\nShop: https://stza.co/+vLlq-V\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Atlas Fireworks
STATUS:CONFIRMED
CREATED:20180213T144531Z
LAST-MODIFIED:20180213T144531Z
TRANSP:OPAQUE
END:VEVENT
* Yard Goats vs. Curve
<2018-06-03 Sun 12:05-15:05>
:PROPERTIES:
:ID:       hfbloLWYWy86OMR6HrjpHHKE@stanza.co
:LOCATION: Dairy Day
:STATUS:   CONFIRMED
:END:

Yard Goats vs. Curve 



Buy tickets here  https //stza.co/~vLls

Follow on MiLB First Pitch  https //stza.co/+vLls-24

Shop  https //stza.co/+vLls-A

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Yard Goats vs. Curve
END:VALARM
DTSTART:20180603T170500Z
DTEND:20180603T200500Z
UID:hfbloLWYWy86OMR6HrjpHHKE@stanza.co
SUMMARY:Yard Goats vs. Curve
DESCRIPTION:\n\n\n\nBuy tickets here: https://stza.co/~vLls\n\nFollow on MiLB First Pitch: https://stza.co/+vLls-24\n\nShop: https://stza.co/+vLls-A\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Dairy Day
STATUS:CONFIRMED
CREATED:20180213T144531Z
LAST-MODIFIED:20180213T144531Z
TRANSP:OPAQUE
END:VEVENT
* Yard Goats @ SeaWolves
<2018-06-05 Tue 18:05-21:05>
:PROPERTIES:
:ID:       O-0srcxB9ivS3ON-MdKQH3oy@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Yard Goats @ SeaWolves Yard Goats @ SeaWolves

Follow on MiLB First Pitch  https //stza.co/+vLke-2q

Shop  https //stza.co/+vLke-1h

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Yard Goats @ SeaWolves
END:VALARM
DTSTART:20180605T230500Z
DTEND:20180606T020500Z
UID:O-0srcxB9ivS3ON-MdKQH3oy@stanza.co
SUMMARY:Yard Goats @ SeaWolves
DESCRIPTION:Yard Goats @ SeaWolves\n\nFollow on MiLB First Pitch: https://stza.co/+vLke-2q\n\nShop: https://stza.co/+vLke-1h\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144531Z
LAST-MODIFIED:20180213T144531Z
TRANSP:OPAQUE
END:VEVENT
* Yard Goats @ SeaWolves
<2018-06-06 Wed 18:05-21:05>
:PROPERTIES:
:ID:       -y7OlEdMXpSE-G_beo6aTy00@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Yard Goats @ SeaWolves Yard Goats @ SeaWolves

Follow on MiLB First Pitch  https //stza.co/+vLkf-36

Shop  https //stza.co/+vLkf-B

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Yard Goats @ SeaWolves
END:VALARM
DTSTART:20180606T230500Z
DTEND:20180607T020500Z
UID:-y7OlEdMXpSE-G_beo6aTy00@stanza.co
SUMMARY:Yard Goats @ SeaWolves
DESCRIPTION:Yard Goats @ SeaWolves\n\nFollow on MiLB First Pitch: https://stza.co/+vLkf-36\n\nShop: https://stza.co/+vLkf-B\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144531Z
LAST-MODIFIED:20180213T144531Z
TRANSP:OPAQUE
END:VEVENT
* Yard Goats @ SeaWolves
<2018-06-07 Thu 18:05-21:05>
:PROPERTIES:
:ID:       neRMh95HgLkMHTRXudmhVRGo@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Yard Goats @ SeaWolves Yard Goats @ SeaWolves

Follow on MiLB First Pitch  https //stza.co/+vLkg-2Z

Shop  https //stza.co/+vLkg-Q

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Yard Goats @ SeaWolves
END:VALARM
DTSTART:20180607T230500Z
DTEND:20180608T020500Z
UID:neRMh95HgLkMHTRXudmhVRGo@stanza.co
SUMMARY:Yard Goats @ SeaWolves
DESCRIPTION:Yard Goats @ SeaWolves\n\nFollow on MiLB First Pitch: https://stza.co/+vLkg-2Z\n\nShop: https://stza.co/+vLkg-Q\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144531Z
LAST-MODIFIED:20180213T144531Z
TRANSP:OPAQUE
END:VEVENT
* Yard Goats @ Curve
<2018-06-08 Fri 18:00-21:00>
:PROPERTIES:
:ID:       W7C81ynpbklKMgUj0v67UX6M@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Yard Goats @ Curve Yard Goats @ Curve

Follow on MiLB First Pitch  https //stza.co/+vLk1-u

Shop  https //stza.co/+vLk1-2Y

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Yard Goats @ Curve
END:VALARM
DTSTART:20180608T230000Z
DTEND:20180609T020000Z
UID:W7C81ynpbklKMgUj0v67UX6M@stanza.co
SUMMARY:Yard Goats @ Curve
DESCRIPTION:Yard Goats @ Curve\n\nFollow on MiLB First Pitch: https://stza.co/+vLk1-u\n\nShop: https://stza.co/+vLk1-2Y\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144531Z
LAST-MODIFIED:20180213T144531Z
TRANSP:OPAQUE
END:VEVENT
* Yard Goats @ Curve
<2018-06-09 Sat 17:00-20:00>
:PROPERTIES:
:ID:       62AycGRDAhXpvKms8XCpQ3Vx@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Yard Goats @ Curve Yard Goats @ Curve

Follow on MiLB First Pitch  https //stza.co/+vLk2-o

Shop  https //stza.co/+vLk2-2i

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Yard Goats @ Curve
END:VALARM
DTSTART:20180609T220000Z
DTEND:20180610T010000Z
UID:62AycGRDAhXpvKms8XCpQ3Vx@stanza.co
SUMMARY:Yard Goats @ Curve
DESCRIPTION:Yard Goats @ Curve\n\nFollow on MiLB First Pitch: https://stza.co/+vLk2-o\n\nShop: https://stza.co/+vLk2-2i\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144531Z
LAST-MODIFIED:20180213T144531Z
TRANSP:OPAQUE
END:VEVENT
* Yard Goats @ Curve
<2018-06-10 Sun 13:00-16:00>
:PROPERTIES:
:ID:       RhVHOOdJvgKJ-mU1mHeV5mya@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Yard Goats @ Curve Yard Goats @ Curve

Follow on MiLB First Pitch  https //stza.co/+vLk3-1Z

Shop  https //stza.co/+vLk3-1t

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Yard Goats @ Curve
END:VALARM
DTSTART:20180610T180000Z
DTEND:20180610T210000Z
UID:RhVHOOdJvgKJ-mU1mHeV5mya@stanza.co
SUMMARY:Yard Goats @ Curve
DESCRIPTION:Yard Goats @ Curve\n\nFollow on MiLB First Pitch: https://stza.co/+vLk3-1Z\n\nShop: https://stza.co/+vLk3-1t\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144531Z
LAST-MODIFIED:20180213T144531Z
TRANSP:OPAQUE
END:VEVENT
* Yard Goats vs. SeaWolves
<2018-06-12 Tue 18:05-21:05>
:PROPERTIES:
:ID:       uYkaskd4Hy3PuXhngSaTBY5l@stanza.co
:LOCATION: Peanut Free Day
:STATUS:   CONFIRMED
:END:

Yard Goats vs. SeaWolves 

Play BINGO while watching the Yard Goats play baseball and win great prizes!

Buy tickets here  https //stza.co/~vLlu

Follow on MiLB First Pitch  https //stza.co/+vLlu-2D

Shop  https //stza.co/+vLlu-2L

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Yard Goats vs. SeaWolves
END:VALARM
DTSTART:20180612T230500Z
DTEND:20180613T020500Z
UID:uYkaskd4Hy3PuXhngSaTBY5l@stanza.co
SUMMARY:Yard Goats vs. SeaWolves
DESCRIPTION:\n\nPlay BINGO while watching the Yard Goats play baseball and win great prizes!\n\nBuy tickets here: https://stza.co/~vLlu\n\nFollow on MiLB First Pitch: https://stza.co/+vLlu-2D\n\nShop: https://stza.co/+vLlu-2L\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Peanut Free Day
STATUS:CONFIRMED
CREATED:20180213T144531Z
LAST-MODIFIED:20180213T144531Z
TRANSP:OPAQUE
END:VEVENT
* Yard Goats vs. SeaWolves
<2018-06-13 Wed 18:05-21:05>
:PROPERTIES:
:ID:       CBKXogv3NCsijWkeXuEMCI1o@stanza.co
:LOCATION: Great seats still available for tonight’s game. Purchase them here.
:STATUS:   CONFIRMED
:END:

Yard Goats vs. SeaWolves Yard Goats vs. SeaWolves

Buy tickets here  https //stza.co/~vLlw

Follow on MiLB First Pitch  https //stza.co/+vLlw-j

Shop  https //stza.co/+vLlw-3q

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Yard Goats vs. SeaWolves
END:VALARM
DTSTART:20180613T230500Z
DTEND:20180614T020500Z
UID:CBKXogv3NCsijWkeXuEMCI1o@stanza.co
SUMMARY:Yard Goats vs. SeaWolves
DESCRIPTION:Yard Goats vs. SeaWolves\n\nBuy tickets here: https://stza.co/~vLlw\n\nFollow on MiLB First Pitch: https://stza.co/+vLlw-j\n\nShop: https://stza.co/+vLlw-3q\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Great seats still available for tonight’s game. Purchase them here.
STATUS:CONFIRMED
CREATED:20180213T144531Z
LAST-MODIFIED:20180213T144531Z
TRANSP:OPAQUE
END:VEVENT
* Yard Goats vs. SeaWolves
<2018-06-14 Thu 18:05-21:05>
:PROPERTIES:
:ID:       MsWVqjyHyuxrNCLY_KD-b_KZ@stanza.co
:LOCATION: Need something fun to do tonight? Get Yard Goats tickets here.
:STATUS:   CONFIRMED
:END:

Yard Goats vs. SeaWolves Yard Goats vs. SeaWolves

Buy tickets here  https //stza.co/~vLlx

Follow on MiLB First Pitch  https //stza.co/+vLlx-N

Shop  https //stza.co/+vLlx-Y

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Yard Goats vs. SeaWolves
END:VALARM
DTSTART:20180614T230500Z
DTEND:20180615T020500Z
UID:MsWVqjyHyuxrNCLY_KD-b_KZ@stanza.co
SUMMARY:Yard Goats vs. SeaWolves
DESCRIPTION:Yard Goats vs. SeaWolves\n\nBuy tickets here: https://stza.co/~vLlx\n\nFollow on MiLB First Pitch: https://stza.co/+vLlx-N\n\nShop: https://stza.co/+vLlx-Y\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Need something fun to do tonight? Get Yard Goats tickets here.
STATUS:CONFIRMED
CREATED:20180213T144531Z
LAST-MODIFIED:20180213T144531Z
TRANSP:OPAQUE
END:VEVENT
* Yard Goats vs. Rumble Ponies
<2018-06-15 Fri 18:05-21:05>
:PROPERTIES:
:ID:       oSjLp7oJOgURtDhgMDO2YWNe@stanza.co
:LOCATION: Atlas Fireworks
:STATUS:   CONFIRMED
:END:

Yard Goats vs. Rumble Ponies 

Come to the ballpark with your Girl Scout Troop and camp out on the field after the game.

Buy tickets here  https //stza.co/~vLlA

Follow on MiLB First Pitch  https //stza.co/+vLlA-3y

Shop  https //stza.co/+vLlA-2X

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Yard Goats vs. Rumble Ponies
END:VALARM
DTSTART:20180615T230500Z
DTEND:20180616T020500Z
UID:oSjLp7oJOgURtDhgMDO2YWNe@stanza.co
SUMMARY:Yard Goats vs. Rumble Ponies
DESCRIPTION:\n\nCome to the ballpark with your Girl Scout Troop and camp out on the field after the game.\n\nBuy tickets here: https://stza.co/~vLlA\n\nFollow on MiLB First Pitch: https://stza.co/+vLlA-3y\n\nShop: https://stza.co/+vLlA-2X\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Atlas Fireworks
STATUS:CONFIRMED
CREATED:20180213T144531Z
LAST-MODIFIED:20180213T144531Z
TRANSP:OPAQUE
END:VEVENT
* Yard Goats vs. Rumble Ponies
<2018-06-16 Sat 17:05-20:05>
:PROPERTIES:
:ID:       ehLUhPn1ZcMXqna6KwdrtxID@stanza.co
:LOCATION: Atlas Fireworks
:STATUS:   CONFIRMED
:END:

Yard Goats vs. Rumble Ponies 



Buy tickets here  https //stza.co/~vLlB

Follow on MiLB First Pitch  https //stza.co/+vLlB-U

Shop  https //stza.co/+vLlB-1d

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Yard Goats vs. Rumble Ponies
END:VALARM
DTSTART:20180616T220500Z
DTEND:20180617T010500Z
UID:ehLUhPn1ZcMXqna6KwdrtxID@stanza.co
SUMMARY:Yard Goats vs. Rumble Ponies
DESCRIPTION:\n\n\n\nBuy tickets here: https://stza.co/~vLlB\n\nFollow on MiLB First Pitch: https://stza.co/+vLlB-U\n\nShop: https://stza.co/+vLlB-1d\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Atlas Fireworks
STATUS:CONFIRMED
CREATED:20180213T144531Z
LAST-MODIFIED:20180213T144531Z
TRANSP:OPAQUE
END:VEVENT
* Yard Goats vs. Rumble Ponies
<2018-06-17 Sun 16:05-19:05>
:PROPERTIES:
:ID:       NStk3pkiVdS-fMrIHUoEF3vr@stanza.co
:LOCATION: Baseball Cap Giveaway
:STATUS:   CONFIRMED
:END:

Yard Goats vs. Rumble Ponies 







Buy tickets here  https //stza.co/~vLlD

Follow on MiLB First Pitch  https //stza.co/+vLlD-3R

Shop  https //stza.co/+vLlD-18

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Yard Goats vs. Rumble Ponies
END:VALARM
DTSTART:20180617T210500Z
DTEND:20180618T000500Z
UID:NStk3pkiVdS-fMrIHUoEF3vr@stanza.co
SUMMARY:Yard Goats vs. Rumble Ponies
DESCRIPTION:\n\n\n\n\n\n\n\nBuy tickets here: https://stza.co/~vLlD\n\nFollow on MiLB First Pitch: https://stza.co/+vLlD-3R\n\nShop: https://stza.co/+vLlD-18\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Baseball Cap Giveaway
STATUS:CONFIRMED
CREATED:20180213T144531Z
LAST-MODIFIED:20180213T144531Z
TRANSP:OPAQUE
END:VEVENT
* Yard Goats @ RubberDucks
<2018-06-19 Tue 18:05-21:05>
:PROPERTIES:
:ID:       tVzERgKtaD5pNWNcshn3AQH9@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Yard Goats @ RubberDucks Yard Goats @ RubberDucks

Follow on MiLB First Pitch  https //stza.co/+vLj_-m

Shop  https //stza.co/+vLj_-p

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Yard Goats @ RubberDucks
END:VALARM
DTSTART:20180619T230500Z
DTEND:20180620T020500Z
UID:tVzERgKtaD5pNWNcshn3AQH9@stanza.co
SUMMARY:Yard Goats @ RubberDucks
DESCRIPTION:Yard Goats @ RubberDucks\n\nFollow on MiLB First Pitch: https://stza.co/+vLj_-m\n\nShop: https://stza.co/+vLj_-p\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144531Z
LAST-MODIFIED:20180213T144531Z
TRANSP:OPAQUE
END:VEVENT
* Yard Goats @ RubberDucks
<2018-06-20 Wed 18:05-21:05>
:PROPERTIES:
:ID:       _A4fPN3T5RzZEG0CCJgXwvpm@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Yard Goats @ RubberDucks Yard Goats @ RubberDucks

Follow on MiLB First Pitch  https //stza.co/+vLj$-2p

Shop  https //stza.co/+vLj$-o

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Yard Goats @ RubberDucks
END:VALARM
DTSTART:20180620T230500Z
DTEND:20180621T020500Z
UID:_A4fPN3T5RzZEG0CCJgXwvpm@stanza.co
SUMMARY:Yard Goats @ RubberDucks
DESCRIPTION:Yard Goats @ RubberDucks\n\nFollow on MiLB First Pitch: https://stza.co/+vLj$-2p\n\nShop: https://stza.co/+vLj$-o\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144531Z
LAST-MODIFIED:20180213T144531Z
TRANSP:OPAQUE
END:VEVENT
* Yard Goats @ RubberDucks
<2018-06-21 Thu 18:05-21:05>
:PROPERTIES:
:ID:       bk_TvYIq457vIxJalWsEFxE6@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Yard Goats @ RubberDucks Yard Goats @ RubberDucks

Follow on MiLB First Pitch  https //stza.co/+vLk0-38

Shop  https //stza.co/+vLk0-1G

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Yard Goats @ RubberDucks
END:VALARM
DTSTART:20180621T230500Z
DTEND:20180622T020500Z
UID:bk_TvYIq457vIxJalWsEFxE6@stanza.co
SUMMARY:Yard Goats @ RubberDucks
DESCRIPTION:Yard Goats @ RubberDucks\n\nFollow on MiLB First Pitch: https://stza.co/+vLk0-38\n\nShop: https://stza.co/+vLk0-1G\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144531Z
LAST-MODIFIED:20180213T144531Z
TRANSP:OPAQUE
END:VEVENT
* Yard Goats @ Rumble Ponies
<2018-06-22 Fri 18:05-21:05>
:PROPERTIES:
:ID:       IhfcYRgoMGV-KV1e0dy_rKad@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Yard Goats @ Rumble Ponies Yard Goats @ Rumble Ponies

Follow on MiLB First Pitch  https //stza.co/+vLk4-O

Shop  https //stza.co/+vLk4-W

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Yard Goats @ Rumble Ponies
END:VALARM
DTSTART:20180622T230500Z
DTEND:20180623T020500Z
UID:IhfcYRgoMGV-KV1e0dy_rKad@stanza.co
SUMMARY:Yard Goats @ Rumble Ponies
DESCRIPTION:Yard Goats @ Rumble Ponies\n\nFollow on MiLB First Pitch: https://stza.co/+vLk4-O\n\nShop: https://stza.co/+vLk4-W\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144531Z
LAST-MODIFIED:20180213T144531Z
TRANSP:OPAQUE
END:VEVENT
* Yard Goats @ Rumble Ponies
<2018-06-23 Sat 17:05-20:05>
:PROPERTIES:
:ID:       nnhLsXh7sJcM5jqAPz98ZuV6@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Yard Goats @ Rumble Ponies Yard Goats @ Rumble Ponies

Follow on MiLB First Pitch  https //stza.co/+vLk5-13

Shop  https //stza.co/+vLk5-3q

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Yard Goats @ Rumble Ponies
END:VALARM
DTSTART:20180623T220500Z
DTEND:20180624T010500Z
UID:nnhLsXh7sJcM5jqAPz98ZuV6@stanza.co
SUMMARY:Yard Goats @ Rumble Ponies
DESCRIPTION:Yard Goats @ Rumble Ponies\n\nFollow on MiLB First Pitch: https://stza.co/+vLk5-13\n\nShop: https://stza.co/+vLk5-3q\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144531Z
LAST-MODIFIED:20180213T144531Z
TRANSP:OPAQUE
END:VEVENT
* Yard Goats @ Rumble Ponies
<2018-06-24 Sun 13:05-16:05>
:PROPERTIES:
:ID:       sTQYrYKbbsQtLTJaHP3Q-x0I@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Yard Goats @ Rumble Ponies Yard Goats @ Rumble Ponies

Follow on MiLB First Pitch  https //stza.co/+vLk6-2$

Shop  https //stza.co/+vLk6-14

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Yard Goats @ Rumble Ponies
END:VALARM
DTSTART:20180624T180500Z
DTEND:20180624T210500Z
UID:sTQYrYKbbsQtLTJaHP3Q-x0I@stanza.co
SUMMARY:Yard Goats @ Rumble Ponies
DESCRIPTION:Yard Goats @ Rumble Ponies\n\nFollow on MiLB First Pitch: https://stza.co/+vLk6-2$\n\nShop: https://stza.co/+vLk6-14\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144531Z
LAST-MODIFIED:20180213T144531Z
TRANSP:OPAQUE
END:VEVENT
* Yard Goats vs. Flying Squirrels
<2018-06-25 Mon 18:05-21:05>
:PROPERTIES:
:ID:       Z_zN8zGZEj1XB0i2AW550eLq@stanza.co
:LOCATION: Puzzle Giveaway
:STATUS:   CONFIRMED
:END:

Yard Goats vs. Flying Squirrels 



Buy tickets here  https //stza.co/~vLlG

Follow on MiLB First Pitch  https //stza.co/+vLlG-3G

Shop  https //stza.co/+vLlG-1D

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Yard Goats vs. Flying Squirrels
END:VALARM
DTSTART:20180625T230500Z
DTEND:20180626T020500Z
UID:Z_zN8zGZEj1XB0i2AW550eLq@stanza.co
SUMMARY:Yard Goats vs. Flying Squirrels
DESCRIPTION:\n\n\n\nBuy tickets here: https://stza.co/~vLlG\n\nFollow on MiLB First Pitch: https://stza.co/+vLlG-3G\n\nShop: https://stza.co/+vLlG-1D\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Puzzle Giveaway
STATUS:CONFIRMED
CREATED:20180213T144531Z
LAST-MODIFIED:20180213T144531Z
TRANSP:OPAQUE
END:VEVENT
* Yard Goats vs. Flying Squirrels
<2018-06-26 Tue 18:05-21:05>
:PROPERTIES:
:ID:       0HRX4ZcJDR1MyF2R4jyj33hS@stanza.co
:LOCATION: You Can Play Night
:STATUS:   CONFIRMED
:END:

Yard Goats vs. Flying Squirrels 

Play BINGO while watching the Yard Goats play baseball and win great prizes!

Buy tickets here  https //stza.co/~vLlI

Follow on MiLB First Pitch  https //stza.co/+vLlI-10

Shop  https //stza.co/+vLlI-1k

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Yard Goats vs. Flying Squirrels
END:VALARM
DTSTART:20180626T230500Z
DTEND:20180627T020500Z
UID:0HRX4ZcJDR1MyF2R4jyj33hS@stanza.co
SUMMARY:Yard Goats vs. Flying Squirrels
DESCRIPTION:\n\nPlay BINGO while watching the Yard Goats play baseball and win great prizes!\n\nBuy tickets here: https://stza.co/~vLlI\n\nFollow on MiLB First Pitch: https://stza.co/+vLlI-10\n\nShop: https://stza.co/+vLlI-1k\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:You Can Play Night
STATUS:CONFIRMED
CREATED:20180213T144531Z
LAST-MODIFIED:20180213T144531Z
TRANSP:OPAQUE
END:VEVENT
* Yard Goats vs. Flying Squirrels
<2018-06-27 Wed 18:05-21:05>
:PROPERTIES:
:ID:       fvV5v7MYHdGU58IEB8uTJShe@stanza.co
:LOCATION: Don’t miss out! Yard Goats tickets still available here.
:STATUS:   CONFIRMED
:END:

Yard Goats vs. Flying Squirrels Yard Goats vs. Flying Squirrels

Buy tickets here  https //stza.co/~vLlJ

Follow on MiLB First Pitch  https //stza.co/+vLlJ-2i

Shop  https //stza.co/+vLlJ-1c

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Yard Goats vs. Flying Squirrels
END:VALARM
DTSTART:20180627T230500Z
DTEND:20180628T020500Z
UID:fvV5v7MYHdGU58IEB8uTJShe@stanza.co
SUMMARY:Yard Goats vs. Flying Squirrels
DESCRIPTION:Yard Goats vs. Flying Squirrels\n\nBuy tickets here: https://stza.co/~vLlJ\n\nFollow on MiLB First Pitch: https://stza.co/+vLlJ-2i\n\nShop: https://stza.co/+vLlJ-1c\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don’t miss out! Yard Goats tickets still available here.
STATUS:CONFIRMED
CREATED:20180213T144531Z
LAST-MODIFIED:20180213T144531Z
TRANSP:OPAQUE
END:VEVENT
* Yard Goats vs. Flying Squirrels
<2018-06-28 Thu 18:05-21:05>
:PROPERTIES:
:ID:       qp0_r06ShBKkIqnBn4IL1srQ@stanza.co
:LOCATION: Baseball Cap Giveaway
:STATUS:   CONFIRMED
:END:

Yard Goats vs. Flying Squirrels 

What if we became the Hartford Whirly Birds instead of the Hartford Yard Goats?

Buy tickets here  https //stza.co/~vLlM

Follow on MiLB First Pitch  https //stza.co/+vLlM-2V

Shop  https //stza.co/+vLlM-j

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Yard Goats vs. Flying Squirrels
END:VALARM
DTSTART:20180628T230500Z
DTEND:20180629T020500Z
UID:qp0_r06ShBKkIqnBn4IL1srQ@stanza.co
SUMMARY:Yard Goats vs. Flying Squirrels
DESCRIPTION:\n\nWhat if we became the Hartford Whirly Birds instead of the Hartford Yard Goats?\n\nBuy tickets here: https://stza.co/~vLlM\n\nFollow on MiLB First Pitch: https://stza.co/+vLlM-2V\n\nShop: https://stza.co/+vLlM-j\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Baseball Cap Giveaway
STATUS:CONFIRMED
CREATED:20180213T144531Z
LAST-MODIFIED:20180213T144531Z
TRANSP:OPAQUE
END:VEVENT
* Yard Goats @ Fightin Phils
<2018-06-29 Fri 18:05-21:05>
:PROPERTIES:
:ID:       xPpU6ses5vKLohJVyGxHTcq8@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Yard Goats @ Fightin Phils Yard Goats @ Fightin Phils

Buy tickets here  https //stza.co/~vLmZ

Follow on MiLB First Pitch  https //stza.co/+vLmZ-9

Shop  https //stza.co/+vLmZ-1u

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Yard Goats @ Fightin Phils
END:VALARM
DTSTART:20180629T230500Z
DTEND:20180630T020500Z
UID:xPpU6ses5vKLohJVyGxHTcq8@stanza.co
SUMMARY:Yard Goats @ Fightin Phils
DESCRIPTION:Yard Goats @ Fightin Phils\n\nBuy tickets here: https://stza.co/~vLmZ\n\nFollow on MiLB First Pitch: https://stza.co/+vLmZ-9\n\nShop: https://stza.co/+vLmZ-1u\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144531Z
LAST-MODIFIED:20180213T144531Z
TRANSP:OPAQUE
END:VEVENT
* Yard Goats @ Fightin Phils
<2018-06-30 Sat 17:35-20:35>
:PROPERTIES:
:ID:       cKHF3H2CWlBZF7wPLXgMfCby@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Yard Goats @ Fightin Phils Yard Goats @ Fightin Phils

Buy tickets here  https //stza.co/~vLm_

Follow on MiLB First Pitch  https //stza.co/+vLm_-11

Shop  https //stza.co/+vLm_-2C

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Yard Goats @ Fightin Phils
END:VALARM
DTSTART:20180630T223500Z
DTEND:20180701T013500Z
UID:cKHF3H2CWlBZF7wPLXgMfCby@stanza.co
SUMMARY:Yard Goats @ Fightin Phils
DESCRIPTION:Yard Goats @ Fightin Phils\n\nBuy tickets here: https://stza.co/~vLm_\n\nFollow on MiLB First Pitch: https://stza.co/+vLm_-11\n\nShop: https://stza.co/+vLm_-2C\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144531Z
LAST-MODIFIED:20180213T144531Z
TRANSP:OPAQUE
END:VEVENT
* Yard Goats @ Fightin Phils
<2018-07-01 Sun 16:05-19:05>
:PROPERTIES:
:ID:       Nd9SMPAcEGQHHbgeg6i6hdKz@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Yard Goats @ Fightin Phils Yard Goats @ Fightin Phils

Buy tickets here  https //stza.co/~v9m4

Follow on MiLB First Pitch  https //stza.co/+v9m4-1j

Shop  https //stza.co/+v9m4-o

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Yard Goats @ Fightin Phils
END:VALARM
DTSTART:20180701T210500Z
DTEND:20180702T000500Z
UID:Nd9SMPAcEGQHHbgeg6i6hdKz@stanza.co
SUMMARY:Yard Goats @ Fightin Phils
DESCRIPTION:Yard Goats @ Fightin Phils\n\nBuy tickets here: https://stza.co/~v9m4\n\nFollow on MiLB First Pitch: https://stza.co/+v9m4-1j\n\nShop: https://stza.co/+v9m4-o\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144531Z
LAST-MODIFIED:20180213T144531Z
TRANSP:OPAQUE
END:VEVENT
* Yard Goats @ Fightin Phils
<2018-07-02 Mon 18:05-21:05>
:PROPERTIES:
:ID:       YYW1pnsc1OhtLpfHh3LAaq5X@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Yard Goats @ Fightin Phils Yard Goats @ Fightin Phils

Buy tickets here  https //stza.co/~v9m5

Follow on MiLB First Pitch  https //stza.co/+v9m5-2X

Shop  https //stza.co/+v9m5-19

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Yard Goats @ Fightin Phils
END:VALARM
DTSTART:20180702T230500Z
DTEND:20180703T020500Z
UID:YYW1pnsc1OhtLpfHh3LAaq5X@stanza.co
SUMMARY:Yard Goats @ Fightin Phils
DESCRIPTION:Yard Goats @ Fightin Phils\n\nBuy tickets here: https://stza.co/~v9m5\n\nFollow on MiLB First Pitch: https://stza.co/+v9m5-2X\n\nShop: https://stza.co/+v9m5-19\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144531Z
LAST-MODIFIED:20180213T144531Z
TRANSP:OPAQUE
END:VEVENT
* Yard Goats @ Fightin Phils
<2018-07-03 Tue 18:05-21:05>
:PROPERTIES:
:ID:       SHrVkqs-wV-GoSxQJ90vb4WE@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Yard Goats @ Fightin Phils Yard Goats @ Fightin Phils

Buy tickets here  https //stza.co/~v9m6

Follow on MiLB First Pitch  https //stza.co/+v9m6-3z

Shop  https //stza.co/+v9m6-1X

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Yard Goats @ Fightin Phils
END:VALARM
DTSTART:20180703T230500Z
DTEND:20180704T020500Z
UID:SHrVkqs-wV-GoSxQJ90vb4WE@stanza.co
SUMMARY:Yard Goats @ Fightin Phils
DESCRIPTION:Yard Goats @ Fightin Phils\n\nBuy tickets here: https://stza.co/~v9m6\n\nFollow on MiLB First Pitch: https://stza.co/+v9m6-3z\n\nShop: https://stza.co/+v9m6-1X\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144531Z
LAST-MODIFIED:20180213T144531Z
TRANSP:OPAQUE
END:VEVENT
* Yard Goats vs. Sea Dogs
<2018-07-04 Wed 15:05-18:05>
:PROPERTIES:
:ID:       H2sj_55CfKEoQL_c3Vr48CBc@stanza.co
:LOCATION: Swipe to get tickets for the game tonight. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Yard Goats vs. Sea Dogs Yard Goats vs. Sea Dogs

Buy tickets here  https //stza.co/~vLlN

Follow on MiLB First Pitch  https //stza.co/+vLlN-3P

Shop  https //stza.co/+vLlN-3F

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Yard Goats vs. Sea Dogs
END:VALARM
DTSTART:20180704T200500Z
DTEND:20180704T230500Z
UID:H2sj_55CfKEoQL_c3Vr48CBc@stanza.co
SUMMARY:Yard Goats vs. Sea Dogs
DESCRIPTION:Yard Goats vs. Sea Dogs\n\nBuy tickets here: https://stza.co/~vLlN\n\nFollow on MiLB First Pitch: https://stza.co/+vLlN-3P\n\nShop: https://stza.co/+vLlN-3F\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Swipe to get tickets for the game tonight. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144531Z
LAST-MODIFIED:20180213T144531Z
TRANSP:OPAQUE
END:VEVENT
* Yard Goats vs. Sea Dogs
<2018-07-05 Thu 18:05-21:05>
:PROPERTIES:
:ID:       wDuGGAzazKkpXjbmBYhjNqvH@stanza.co
:LOCATION: Appearance by Shimmer and Shine
:STATUS:   CONFIRMED
:END:

Yard Goats vs. Sea Dogs Come to the ballpark early and meet Shimmer and Shine in the concourse. 



Buy tickets here  https //stza.co/~vLlP

Follow on MiLB First Pitch  https //stza.co/+vLlP-M

Shop  https //stza.co/+vLlP-17

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Yard Goats vs. Sea Dogs
END:VALARM
DTSTART:20180705T230500Z
DTEND:20180706T020500Z
UID:wDuGGAzazKkpXjbmBYhjNqvH@stanza.co
SUMMARY:Yard Goats vs. Sea Dogs
DESCRIPTION:Come to the ballpark early and meet Shimmer and Shine in the concourse. \n\n\n\nBuy tickets here: https://stza.co/~vLlP\n\nFollow on MiLB First Pitch: https://stza.co/+vLlP-M\n\nShop: https://stza.co/+vLlP-17\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Appearance by Shimmer and Shine
STATUS:CONFIRMED
CREATED:20180213T144531Z
LAST-MODIFIED:20180213T144531Z
TRANSP:OPAQUE
END:VEVENT
* Yard Goats vs. Sea Dogs
<2018-07-06 Fri 18:05-21:05>
:PROPERTIES:
:ID:       -wwjRgY6WIr1iCFZbjqvNtME@stanza.co
:LOCATION: Atlas Fireworks
:STATUS:   CONFIRMED
:END:

Yard Goats vs. Sea Dogs 



Buy tickets here  https //stza.co/~vLlS

Follow on MiLB First Pitch  https //stza.co/+vLlS-u

Shop  https //stza.co/+vLlS-2g

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Yard Goats vs. Sea Dogs
END:VALARM
DTSTART:20180706T230500Z
DTEND:20180707T020500Z
UID:-wwjRgY6WIr1iCFZbjqvNtME@stanza.co
SUMMARY:Yard Goats vs. Sea Dogs
DESCRIPTION:\n\n\n\nBuy tickets here: https://stza.co/~vLlS\n\nFollow on MiLB First Pitch: https://stza.co/+vLlS-u\n\nShop: https://stza.co/+vLlS-2g\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Atlas Fireworks
STATUS:CONFIRMED
CREATED:20180213T144531Z
LAST-MODIFIED:20180213T144531Z
TRANSP:OPAQUE
END:VEVENT
* Yard Goats vs. Sea Dogs
<2018-07-07 Sat 17:05-20:05>
:PROPERTIES:
:ID:       viVQalqRwdtuvsxY65JzdD0l@stanza.co
:LOCATION: Atlas Fireworks
:STATUS:   CONFIRMED
:END:

Yard Goats vs. Sea Dogs 



Buy tickets here  https //stza.co/~vLlU

Follow on MiLB First Pitch  https //stza.co/+vLlU-3a

Shop  https //stza.co/+vLlU-12

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Yard Goats vs. Sea Dogs
END:VALARM
DTSTART:20180707T220500Z
DTEND:20180708T010500Z
UID:viVQalqRwdtuvsxY65JzdD0l@stanza.co
SUMMARY:Yard Goats vs. Sea Dogs
DESCRIPTION:\n\n\n\nBuy tickets here: https://stza.co/~vLlU\n\nFollow on MiLB First Pitch: https://stza.co/+vLlU-3a\n\nShop: https://stza.co/+vLlU-12\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Atlas Fireworks
STATUS:CONFIRMED
CREATED:20180213T144531Z
LAST-MODIFIED:20180213T144531Z
TRANSP:OPAQUE
END:VEVENT
* Yard Goats vs. Sea Dogs
<2018-07-08 Sun 12:05-15:05>
:PROPERTIES:
:ID:       ytcbjQw396Dk2A8ViuN0_aRw@stanza.co
:LOCATION: Chew Chew's Birthday Party
:STATUS:   CONFIRMED
:END:

Yard Goats vs. Sea Dogs Come out and help Chew Chew's celebrate her birthday!



Buy tickets here  https //stza.co/~vLlV

Follow on MiLB First Pitch  https //stza.co/+vLlV-2g

Shop  https //stza.co/+vLlV-3r

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Yard Goats vs. Sea Dogs
END:VALARM
DTSTART:20180708T170500Z
DTEND:20180708T200500Z
UID:ytcbjQw396Dk2A8ViuN0_aRw@stanza.co
SUMMARY:Yard Goats vs. Sea Dogs
DESCRIPTION:Come out and help Chew Chew's celebrate her birthday!\n\n\n\nBuy tickets here: https://stza.co/~vLlV\n\nFollow on MiLB First Pitch: https://stza.co/+vLlV-2g\n\nShop: https://stza.co/+vLlV-3r\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Chew Chew's Birthday Party
STATUS:CONFIRMED
CREATED:20180213T144531Z
LAST-MODIFIED:20180213T144531Z
TRANSP:OPAQUE
END:VEVENT
* Yard Goats @ Senators
<2018-07-12 Thu 18:00-21:00>
:PROPERTIES:
:ID:       FR4KBagaPk4rbU3DcAOwk9hw@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Yard Goats @ Senators Yard Goats @ Senators

Follow on MiLB First Pitch  https //stza.co/+vLkk-3g

Shop  https //stza.co/+vLkk-3B

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Yard Goats @ Senators
END:VALARM
DTSTART:20180712T230000Z
DTEND:20180713T020000Z
UID:FR4KBagaPk4rbU3DcAOwk9hw@stanza.co
SUMMARY:Yard Goats @ Senators
DESCRIPTION:Yard Goats @ Senators\n\nFollow on MiLB First Pitch: https://stza.co/+vLkk-3g\n\nShop: https://stza.co/+vLkk-3B\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144531Z
LAST-MODIFIED:20180213T144531Z
TRANSP:OPAQUE
END:VEVENT
* Yard Goats @ Senators
<2018-07-13 Fri 18:00-21:00>
:PROPERTIES:
:ID:       B2SVG1m72LulOLFvNzfLWxAP@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Yard Goats @ Senators Yard Goats @ Senators

Follow on MiLB First Pitch  https //stza.co/+vLkl-3I

Shop  https //stza.co/+vLkl-1E

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Yard Goats @ Senators
END:VALARM
DTSTART:20180713T230000Z
DTEND:20180714T020000Z
UID:B2SVG1m72LulOLFvNzfLWxAP@stanza.co
SUMMARY:Yard Goats @ Senators
DESCRIPTION:Yard Goats @ Senators\n\nFollow on MiLB First Pitch: https://stza.co/+vLkl-3I\n\nShop: https://stza.co/+vLkl-1E\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144531Z
LAST-MODIFIED:20180213T144531Z
TRANSP:OPAQUE
END:VEVENT
* Yard Goats @ Senators
<2018-07-14 Sat 17:00-20:00>
:PROPERTIES:
:ID:       Vhm4FtkIh037eSOTMfwZKgNN@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Yard Goats @ Senators Yard Goats @ Senators

Follow on MiLB First Pitch  https //stza.co/+vLkm-1J

Shop  https //stza.co/+vLkm-3g

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Yard Goats @ Senators
END:VALARM
DTSTART:20180714T220000Z
DTEND:20180715T010000Z
UID:Vhm4FtkIh037eSOTMfwZKgNN@stanza.co
SUMMARY:Yard Goats @ Senators
DESCRIPTION:Yard Goats @ Senators\n\nFollow on MiLB First Pitch: https://stza.co/+vLkm-1J\n\nShop: https://stza.co/+vLkm-3g\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144531Z
LAST-MODIFIED:20180213T144531Z
TRANSP:OPAQUE
END:VEVENT
* Yard Goats @ Senators
<2018-07-15 Sun 12:30-15:30>
:PROPERTIES:
:ID:       w2gvzx-UlCPzMMFPUgysfe-2@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Yard Goats @ Senators Yard Goats @ Senators

Follow on MiLB First Pitch  https //stza.co/+vLkn-2P

Shop  https //stza.co/+vLkn-3H

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Yard Goats @ Senators
END:VALARM
DTSTART:20180715T173000Z
DTEND:20180715T203000Z
UID:w2gvzx-UlCPzMMFPUgysfe-2@stanza.co
SUMMARY:Yard Goats @ Senators
DESCRIPTION:Yard Goats @ Senators\n\nFollow on MiLB First Pitch: https://stza.co/+vLkn-2P\n\nShop: https://stza.co/+vLkn-3H\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144531Z
LAST-MODIFIED:20180213T144531Z
TRANSP:OPAQUE
END:VEVENT
* Yard Goats vs. Fightin Phils
<2018-07-16 Mon 18:05-21:05>
:PROPERTIES:
:ID:       BQd94wMSjfyZM62b4Iw5lbpK@stanza.co
:LOCATION: Swipe for last minute tickets for tonight's game. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Yard Goats vs. Fightin Phils Yard Goats vs. Fightin Phils

Buy tickets here  https //stza.co/~vLlX

Follow on MiLB First Pitch  https //stza.co/+vLlX-2F

Shop  https //stza.co/+vLlX-1f

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Yard Goats vs. Fightin Phils
END:VALARM
DTSTART:20180716T230500Z
DTEND:20180717T020500Z
UID:BQd94wMSjfyZM62b4Iw5lbpK@stanza.co
SUMMARY:Yard Goats vs. Fightin Phils
DESCRIPTION:Yard Goats vs. Fightin Phils\n\nBuy tickets here: https://stza.co/~vLlX\n\nFollow on MiLB First Pitch: https://stza.co/+vLlX-2F\n\nShop: https://stza.co/+vLlX-1f\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Swipe for last minute tickets for tonight's game. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144531Z
LAST-MODIFIED:20180213T144531Z
TRANSP:OPAQUE
END:VEVENT
* Yard Goats vs. Fightin Phils
<2018-07-17 Tue 18:05-21:05>
:PROPERTIES:
:ID:       jvLuAQ_y5kdQnpHc_H9QDhaM@stanza.co
:LOCATION: Baseball BINGO
:STATUS:   CONFIRMED
:END:

Yard Goats vs. Fightin Phils Play BINGO while watching the Yard Goats play baseball and win great prizes!

Buy tickets here  https //stza.co/~vLlZ

Follow on MiLB First Pitch  https //stza.co/+vLlZ-3m

Shop  https //stza.co/+vLlZ-3J

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Yard Goats vs. Fightin Phils
END:VALARM
DTSTART:20180717T230500Z
DTEND:20180718T020500Z
UID:jvLuAQ_y5kdQnpHc_H9QDhaM@stanza.co
SUMMARY:Yard Goats vs. Fightin Phils
DESCRIPTION:Play BINGO while watching the Yard Goats play baseball and win great prizes!\n\nBuy tickets here: https://stza.co/~vLlZ\n\nFollow on MiLB First Pitch: https://stza.co/+vLlZ-3m\n\nShop: https://stza.co/+vLlZ-3J\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Baseball BINGO
STATUS:CONFIRMED
CREATED:20180213T144531Z
LAST-MODIFIED:20180213T144531Z
TRANSP:OPAQUE
END:VEVENT
* Yard Goats vs. Fightin Phils
<2018-07-18 Wed 11:05-14:05>
:PROPERTIES:
:ID:       mGIfWBJgRG-2lUUDa1Yna587@stanza.co
:LOCATION: Ready for the game? Swipe for tickets and more information.
:STATUS:   CONFIRMED
:END:

Yard Goats vs. Fightin Phils Yard Goats vs. Fightin Phils

Buy tickets here  https //stza.co/~vLm0

Follow on MiLB First Pitch  https //stza.co/+vLm0-U

Shop  https //stza.co/+vLm0-13

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Yard Goats vs. Fightin Phils
END:VALARM
DTSTART:20180718T160500Z
DTEND:20180718T190500Z
UID:mGIfWBJgRG-2lUUDa1Yna587@stanza.co
SUMMARY:Yard Goats vs. Fightin Phils
DESCRIPTION:Yard Goats vs. Fightin Phils\n\nBuy tickets here: https://stza.co/~vLm0\n\nFollow on MiLB First Pitch: https://stza.co/+vLm0-U\n\nShop: https://stza.co/+vLm0-13\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Swipe for tickets and more information.
STATUS:CONFIRMED
CREATED:20180213T144531Z
LAST-MODIFIED:20180213T144531Z
TRANSP:OPAQUE
END:VEVENT
* Yard Goats @ Sea Dogs
<2018-07-19 Thu 18:00-21:00>
:PROPERTIES:
:ID:       ngEJem9Oe09PHO2FJVNByaNQ@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Yard Goats @ Sea Dogs Yard Goats @ Sea Dogs

Buy tickets here  https //stza.co/~vLmV

Follow on MiLB First Pitch  https //stza.co/+vLmV-2v

Shop  https //stza.co/+vLmV-5

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Yard Goats @ Sea Dogs
END:VALARM
DTSTART:20180719T230000Z
DTEND:20180720T020000Z
UID:ngEJem9Oe09PHO2FJVNByaNQ@stanza.co
SUMMARY:Yard Goats @ Sea Dogs
DESCRIPTION:Yard Goats @ Sea Dogs\n\nBuy tickets here: https://stza.co/~vLmV\n\nFollow on MiLB First Pitch: https://stza.co/+vLmV-2v\n\nShop: https://stza.co/+vLmV-5\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144531Z
LAST-MODIFIED:20180213T144531Z
TRANSP:OPAQUE
END:VEVENT
* Yard Goats @ Sea Dogs
<2018-07-20 Fri 18:00-21:00>
:PROPERTIES:
:ID:       5UinIknqjMxVyGbpRnfNswXr@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Yard Goats @ Sea Dogs Yard Goats @ Sea Dogs

Buy tickets here  https //stza.co/~vLmW

Follow on MiLB First Pitch  https //stza.co/+vLmW-1_

Shop  https //stza.co/+vLmW-_

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Yard Goats @ Sea Dogs
END:VALARM
DTSTART:20180720T230000Z
DTEND:20180721T020000Z
UID:5UinIknqjMxVyGbpRnfNswXr@stanza.co
SUMMARY:Yard Goats @ Sea Dogs
DESCRIPTION:Yard Goats @ Sea Dogs\n\nBuy tickets here: https://stza.co/~vLmW\n\nFollow on MiLB First Pitch: https://stza.co/+vLmW-1_\n\nShop: https://stza.co/+vLmW-_\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144531Z
LAST-MODIFIED:20180213T144531Z
TRANSP:OPAQUE
END:VEVENT
* Yard Goats @ Sea Dogs
<2018-07-21 Sat 17:00-20:00>
:PROPERTIES:
:ID:       now09Y8rseOahvIguD4UpqBy@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Yard Goats @ Sea Dogs Yard Goats @ Sea Dogs

Buy tickets here  https //stza.co/~vLmX

Follow on MiLB First Pitch  https //stza.co/+vLmX-d

Shop  https //stza.co/+vLmX-2d

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Yard Goats @ Sea Dogs
END:VALARM
DTSTART:20180721T220000Z
DTEND:20180722T010000Z
UID:now09Y8rseOahvIguD4UpqBy@stanza.co
SUMMARY:Yard Goats @ Sea Dogs
DESCRIPTION:Yard Goats @ Sea Dogs\n\nBuy tickets here: https://stza.co/~vLmX\n\nFollow on MiLB First Pitch: https://stza.co/+vLmX-d\n\nShop: https://stza.co/+vLmX-2d\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144531Z
LAST-MODIFIED:20180213T144531Z
TRANSP:OPAQUE
END:VEVENT
* Yard Goats @ Sea Dogs
<2018-07-22 Sun 12:00-15:00>
:PROPERTIES:
:ID:       EBqYYBbt3gq8S7IjNupXWQIZ@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Yard Goats @ Sea Dogs Yard Goats @ Sea Dogs

Buy tickets here  https //stza.co/~vLmY

Follow on MiLB First Pitch  https //stza.co/+vLmY-L

Shop  https //stza.co/+vLmY-3b

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Yard Goats @ Sea Dogs
END:VALARM
DTSTART:20180722T170000Z
DTEND:20180722T200000Z
UID:EBqYYBbt3gq8S7IjNupXWQIZ@stanza.co
SUMMARY:Yard Goats @ Sea Dogs
DESCRIPTION:Yard Goats @ Sea Dogs\n\nBuy tickets here: https://stza.co/~vLmY\n\nFollow on MiLB First Pitch: https://stza.co/+vLmY-L\n\nShop: https://stza.co/+vLmY-3b\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144531Z
LAST-MODIFIED:20180213T144531Z
TRANSP:OPAQUE
END:VEVENT
* Yard Goats @ Thunder
<2018-07-23 Mon 18:00-21:00>
:PROPERTIES:
:ID:       PTuNSczqeysLjWsky2Ukkptt@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Yard Goats @ Thunder Yard Goats @ Thunder

Follow on MiLB First Pitch  https //stza.co/+v9mg-2

Shop  https //stza.co/+v9mg-3W

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Yard Goats @ Thunder
END:VALARM
DTSTART:20180723T230000Z
DTEND:20180724T020000Z
UID:PTuNSczqeysLjWsky2Ukkptt@stanza.co
SUMMARY:Yard Goats @ Thunder
DESCRIPTION:Yard Goats @ Thunder\n\nFollow on MiLB First Pitch: https://stza.co/+v9mg-2\n\nShop: https://stza.co/+v9mg-3W\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144531Z
LAST-MODIFIED:20180213T144531Z
TRANSP:OPAQUE
END:VEVENT
* Yard Goats @ Thunder
<2018-07-24 Tue 18:00-21:00>
:PROPERTIES:
:ID:       SDvXm1jaIlZTEQ-OZiDh7cra@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Yard Goats @ Thunder Yard Goats @ Thunder

Follow on MiLB First Pitch  https //stza.co/+v9mh-3d

Shop  https //stza.co/+v9mh-X

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Yard Goats @ Thunder
END:VALARM
DTSTART:20180724T230000Z
DTEND:20180725T020000Z
UID:SDvXm1jaIlZTEQ-OZiDh7cra@stanza.co
SUMMARY:Yard Goats @ Thunder
DESCRIPTION:Yard Goats @ Thunder\n\nFollow on MiLB First Pitch: https://stza.co/+v9mh-3d\n\nShop: https://stza.co/+v9mh-X\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144531Z
LAST-MODIFIED:20180213T144531Z
TRANSP:OPAQUE
END:VEVENT
* Yard Goats @ Thunder
<2018-07-25 Wed 10:00-13:00>
:PROPERTIES:
:ID:       -ljZ3_xKUCUEN2-pqnxAeaNA@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Yard Goats @ Thunder Yard Goats @ Thunder

Follow on MiLB First Pitch  https //stza.co/+v9mi-3f

Shop  https //stza.co/+v9mi-1Z

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Yard Goats @ Thunder
END:VALARM
DTSTART:20180725T150000Z
DTEND:20180725T180000Z
UID:-ljZ3_xKUCUEN2-pqnxAeaNA@stanza.co
SUMMARY:Yard Goats @ Thunder
DESCRIPTION:Yard Goats @ Thunder\n\nFollow on MiLB First Pitch: https://stza.co/+v9mi-3f\n\nShop: https://stza.co/+v9mi-1Z\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144531Z
LAST-MODIFIED:20180213T144531Z
TRANSP:OPAQUE
END:VEVENT
* Yard Goats vs. Fisher Cats
<2018-07-26 Thu 18:05-21:05>
:PROPERTIES:
:ID:       e_DyZnRUdEebpV4I8dxxsNnz@stanza.co
:LOCATION: Human Cannonball Appearance
:STATUS:   CONFIRMED
:END:

Yard Goats vs. Fisher Cats 

Come to the ballpark dressed as your favorite princess or pirate!

Buy tickets here  https //stza.co/~vLm2

Follow on MiLB First Pitch  https //stza.co/+vLm2-3V

Shop  https //stza.co/+vLm2-1L

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Yard Goats vs. Fisher Cats
END:VALARM
DTSTART:20180726T230500Z
DTEND:20180727T020500Z
UID:e_DyZnRUdEebpV4I8dxxsNnz@stanza.co
SUMMARY:Yard Goats vs. Fisher Cats
DESCRIPTION:\n\nCome to the ballpark dressed as your favorite princess or pirate!\n\nBuy tickets here: https://stza.co/~vLm2\n\nFollow on MiLB First Pitch: https://stza.co/+vLm2-3V\n\nShop: https://stza.co/+vLm2-1L\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Human Cannonball Appearance
STATUS:CONFIRMED
CREATED:20180213T144531Z
LAST-MODIFIED:20180213T144531Z
TRANSP:OPAQUE
END:VEVENT
* Yard Goats vs. Fisher Cats
<2018-07-27 Fri 18:05-21:05>
:PROPERTIES:
:ID:       6jHhZggbfjOGJVGaVMd-Ho7L@stanza.co
:LOCATION: Atlas Fireworks
:STATUS:   CONFIRMED
:END:

Yard Goats vs. Fisher Cats 



Buy tickets here  https //stza.co/~vLm4

Follow on MiLB First Pitch  https //stza.co/+vLm4-2i

Shop  https //stza.co/+vLm4-1J

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Yard Goats vs. Fisher Cats
END:VALARM
DTSTART:20180727T230500Z
DTEND:20180728T020500Z
UID:6jHhZggbfjOGJVGaVMd-Ho7L@stanza.co
SUMMARY:Yard Goats vs. Fisher Cats
DESCRIPTION:\n\n\n\nBuy tickets here: https://stza.co/~vLm4\n\nFollow on MiLB First Pitch: https://stza.co/+vLm4-2i\n\nShop: https://stza.co/+vLm4-1J\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Atlas Fireworks
STATUS:CONFIRMED
CREATED:20180213T144531Z
LAST-MODIFIED:20180213T144531Z
TRANSP:OPAQUE
END:VEVENT
* Yard Goats vs. Fisher Cats
<2018-07-28 Sat 17:05-20:05>
:PROPERTIES:
:ID:       0qqG9drPnKVFw8_ve_gK5C1o@stanza.co
:LOCATION: Atlas Fireworks
:STATUS:   CONFIRMED
:END:

Yard Goats vs. Fisher Cats 

Come for when the gates open and meet former Whalers during a pre-game autograph session in the concourse.



Buy tickets here  https //stza.co/~vLm5

Follow on MiLB First Pitch  https //stza.co/+vLm5-2o

Shop  https //stza.co/+vLm5-34

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Yard Goats vs. Fisher Cats
END:VALARM
DTSTART:20180728T220500Z
DTEND:20180729T010500Z
UID:0qqG9drPnKVFw8_ve_gK5C1o@stanza.co
SUMMARY:Yard Goats vs. Fisher Cats
DESCRIPTION:\n\nCome for when the gates open and meet former Whalers during a pre-game autograph session in the concourse.\n\n\n\nBuy tickets here: https://stza.co/~vLm5\n\nFollow on MiLB First Pitch: https://stza.co/+vLm5-2o\n\nShop: https://stza.co/+vLm5-34\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Atlas Fireworks
STATUS:CONFIRMED
CREATED:20180213T144531Z
LAST-MODIFIED:20180213T144531Z
TRANSP:OPAQUE
END:VEVENT
* Yard Goats vs. Fisher Cats
<2018-07-29 Sun 16:05-19:05>
:PROPERTIES:
:ID:       rigBuWHB2M_ahth4iB9xQfve@stanza.co
:LOCATION: Hockey Puck Giveaway
:STATUS:   CONFIRMED
:END:

Yard Goats vs. Fisher Cats 





Buy tickets here  https //stza.co/~vLm7

Follow on MiLB First Pitch  https //stza.co/+vLm7-3u

Shop  https //stza.co/+vLm7-2q

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Yard Goats vs. Fisher Cats
END:VALARM
DTSTART:20180729T210500Z
DTEND:20180730T000500Z
UID:rigBuWHB2M_ahth4iB9xQfve@stanza.co
SUMMARY:Yard Goats vs. Fisher Cats
DESCRIPTION:\n\n\n\n\n\nBuy tickets here: https://stza.co/~vLm7\n\nFollow on MiLB First Pitch: https://stza.co/+vLm7-3u\n\nShop: https://stza.co/+vLm7-2q\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Hockey Puck Giveaway
STATUS:CONFIRMED
CREATED:20180213T144531Z
LAST-MODIFIED:20180213T144531Z
TRANSP:OPAQUE
END:VEVENT
* Yard Goats @ Rumble Ponies
<2018-07-31 Tue 17:35-20:35>
:PROPERTIES:
:ID:       D0UK3TRndlRVE1x1jmjNZWc2@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Yard Goats @ Rumble Ponies Yard Goats @ Rumble Ponies

Follow on MiLB First Pitch  https //stza.co/+vLk7-3y

Shop  https //stza.co/+vLk7-3w

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Yard Goats @ Rumble Ponies
END:VALARM
DTSTART:20180731T223500Z
DTEND:20180801T013500Z
UID:D0UK3TRndlRVE1x1jmjNZWc2@stanza.co
SUMMARY:Yard Goats @ Rumble Ponies
DESCRIPTION:Yard Goats @ Rumble Ponies\n\nFollow on MiLB First Pitch: https://stza.co/+vLk7-3y\n\nShop: https://stza.co/+vLk7-3w\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144531Z
LAST-MODIFIED:20180213T144531Z
TRANSP:OPAQUE
END:VEVENT
* Yard Goats @ Rumble Ponies
<2018-08-01 Wed 17:35-20:35>
:PROPERTIES:
:ID:       QhVkt9Zpe5yDRaqUTI8-I6pk@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Yard Goats @ Rumble Ponies Yard Goats @ Rumble Ponies

Follow on MiLB First Pitch  https //stza.co/+vLk8-2Y

Shop  https //stza.co/+vLk8-E

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Yard Goats @ Rumble Ponies
END:VALARM
DTSTART:20180801T223500Z
DTEND:20180802T013500Z
UID:QhVkt9Zpe5yDRaqUTI8-I6pk@stanza.co
SUMMARY:Yard Goats @ Rumble Ponies
DESCRIPTION:Yard Goats @ Rumble Ponies\n\nFollow on MiLB First Pitch: https://stza.co/+vLk8-2Y\n\nShop: https://stza.co/+vLk8-E\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144531Z
LAST-MODIFIED:20180213T144531Z
TRANSP:OPAQUE
END:VEVENT
* Yard Goats @ Rumble Ponies
<2018-08-02 Thu 17:35-20:35>
:PROPERTIES:
:ID:       Y_Q8Uhr7eok9SjMmjs-9uHGE@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Yard Goats @ Rumble Ponies Yard Goats @ Rumble Ponies

Follow on MiLB First Pitch  https //stza.co/+vLk9-1m

Shop  https //stza.co/+vLk9-1_

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Yard Goats @ Rumble Ponies
END:VALARM
DTSTART:20180802T223500Z
DTEND:20180803T013500Z
UID:Y_Q8Uhr7eok9SjMmjs-9uHGE@stanza.co
SUMMARY:Yard Goats @ Rumble Ponies
DESCRIPTION:Yard Goats @ Rumble Ponies\n\nFollow on MiLB First Pitch: https://stza.co/+vLk9-1m\n\nShop: https://stza.co/+vLk9-1_\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144531Z
LAST-MODIFIED:20180213T144531Z
TRANSP:OPAQUE
END:VEVENT
* Yard Goats vs. Thunder
<2018-08-03 Fri 18:05-21:05>
:PROPERTIES:
:ID:       3YVM0gR87l53qJiRLpzXZNOa@stanza.co
:LOCATION: Atlas Fireworks
:STATUS:   CONFIRMED
:END:

Yard Goats vs. Thunder 





Buy tickets here  https //stza.co/~vLma

Follow on MiLB First Pitch  https //stza.co/+vLma-L

Shop  https //stza.co/+vLma-2z

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Yard Goats vs. Thunder
END:VALARM
DTSTART:20180803T230500Z
DTEND:20180804T020500Z
UID:3YVM0gR87l53qJiRLpzXZNOa@stanza.co
SUMMARY:Yard Goats vs. Thunder
DESCRIPTION:\n\n\n\n\n\nBuy tickets here: https://stza.co/~vLma\n\nFollow on MiLB First Pitch: https://stza.co/+vLma-L\n\nShop: https://stza.co/+vLma-2z\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Atlas Fireworks
STATUS:CONFIRMED
CREATED:20180213T144531Z
LAST-MODIFIED:20180213T144531Z
TRANSP:OPAQUE
END:VEVENT
* Yard Goats vs. Thunder
<2018-08-04 Sat 17:05-20:05>
:PROPERTIES:
:ID:       ZnjvAgNmhtwPqU-t-ibbkGlC@stanza.co
:LOCATION: Atlas Fireworks
:STATUS:   CONFIRMED
:END:

Yard Goats vs. Thunder 



Come out to the game with your Boy Scout Troop and camp out on the field after the game. 

Buy tickets here  https //stza.co/~vLmc

Follow on MiLB First Pitch  https //stza.co/+vLmc-2w

Shop  https //stza.co/+vLmc-1D

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Yard Goats vs. Thunder
END:VALARM
DTSTART:20180804T220500Z
DTEND:20180805T010500Z
UID:ZnjvAgNmhtwPqU-t-ibbkGlC@stanza.co
SUMMARY:Yard Goats vs. Thunder
DESCRIPTION:\n\n\n\nCome out to the game with your Boy Scout Troop and camp out on the field after the game. \n\nBuy tickets here: https://stza.co/~vLmc\n\nFollow on MiLB First Pitch: https://stza.co/+vLmc-2w\n\nShop: https://stza.co/+vLmc-1D\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Atlas Fireworks
STATUS:CONFIRMED
CREATED:20180213T144531Z
LAST-MODIFIED:20180213T144531Z
TRANSP:OPAQUE
END:VEVENT
* Yard Goats vs. Thunder
<2018-08-05 Sun 16:05-19:05>
:PROPERTIES:
:ID:       LiGDxObEXv6sr40zKlZl-FqT@stanza.co
:LOCATION: Golden Snitch Theme Baseball
:STATUS:   CONFIRMED
:END:

Yard Goats vs. Thunder 





Buy tickets here  https //stza.co/~vLme

Follow on MiLB First Pitch  https //stza.co/+vLme-X

Shop  https //stza.co/+vLme-5

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Yard Goats vs. Thunder
END:VALARM
DTSTART:20180805T210500Z
DTEND:20180806T000500Z
UID:LiGDxObEXv6sr40zKlZl-FqT@stanza.co
SUMMARY:Yard Goats vs. Thunder
DESCRIPTION:\n\n\n\n\n\nBuy tickets here: https://stza.co/~vLme\n\nFollow on MiLB First Pitch: https://stza.co/+vLme-X\n\nShop: https://stza.co/+vLme-5\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Golden Snitch Theme Baseball
STATUS:CONFIRMED
CREATED:20180213T144531Z
LAST-MODIFIED:20180213T144531Z
TRANSP:OPAQUE
END:VEVENT
* Yard Goats @ Senators
<2018-08-07 Tue 17:30-20:30>
:PROPERTIES:
:ID:       5cN1T8pZQI-NLPmUmzSvzdxF@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Yard Goats @ Senators Yard Goats @ Senators

Follow on MiLB First Pitch  https //stza.co/+vLko-2j

Shop  https //stza.co/+vLko-3_

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Yard Goats @ Senators
END:VALARM
DTSTART:20180807T223000Z
DTEND:20180808T013000Z
UID:5cN1T8pZQI-NLPmUmzSvzdxF@stanza.co
SUMMARY:Yard Goats @ Senators
DESCRIPTION:Yard Goats @ Senators\n\nFollow on MiLB First Pitch: https://stza.co/+vLko-2j\n\nShop: https://stza.co/+vLko-3_\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144531Z
LAST-MODIFIED:20180213T144531Z
TRANSP:OPAQUE
END:VEVENT
* Yard Goats @ Senators
<2018-08-08 Wed 17:30-20:30>
:PROPERTIES:
:ID:       zWaNUC3tuigbSM4R1ZPBADON@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Yard Goats @ Senators Yard Goats @ Senators

Follow on MiLB First Pitch  https //stza.co/+vLkp-2N

Shop  https //stza.co/+vLkp-10

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Yard Goats @ Senators
END:VALARM
DTSTART:20180808T223000Z
DTEND:20180809T013000Z
UID:zWaNUC3tuigbSM4R1ZPBADON@stanza.co
SUMMARY:Yard Goats @ Senators
DESCRIPTION:Yard Goats @ Senators\n\nFollow on MiLB First Pitch: https://stza.co/+vLkp-2N\n\nShop: https://stza.co/+vLkp-10\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144531Z
LAST-MODIFIED:20180213T144531Z
TRANSP:OPAQUE
END:VEVENT
* Yard Goats @ Senators
<2018-08-09 Thu 18:00-21:00>
:PROPERTIES:
:ID:       ch2U6sQ2cX6npAYoFNeL0bh6@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Yard Goats @ Senators Yard Goats @ Senators

Follow on MiLB First Pitch  https //stza.co/+vLkq-3S

Shop  https //stza.co/+vLkq-

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Yard Goats @ Senators
END:VALARM
DTSTART:20180809T230000Z
DTEND:20180810T020000Z
UID:ch2U6sQ2cX6npAYoFNeL0bh6@stanza.co
SUMMARY:Yard Goats @ Senators
DESCRIPTION:Yard Goats @ Senators\n\nFollow on MiLB First Pitch: https://stza.co/+vLkq-3S\n\nShop: https://stza.co/+vLkq-\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144531Z
LAST-MODIFIED:20180213T144531Z
TRANSP:OPAQUE
END:VEVENT
* Yard Goats vs. Baysox
<2018-08-10 Fri 18:05-21:05>
:PROPERTIES:
:ID:       EQ6ua9ohq6ETx_m8bbvTMmSA@stanza.co
:LOCATION: Atlas Fireworks
:STATUS:   CONFIRMED
:END:

Yard Goats vs. Baysox 

 To benefit Pancreatic Cancer  

Buy tickets here  https //stza.co/~vLmg

Follow on MiLB First Pitch  https //stza.co/+vLmg-G

Shop  https //stza.co/+vLmg-H

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Yard Goats vs. Baysox
END:VALARM
DTSTART:20180810T230500Z
DTEND:20180811T020500Z
UID:EQ6ua9ohq6ETx_m8bbvTMmSA@stanza.co
SUMMARY:Yard Goats vs. Baysox
DESCRIPTION:\n\n To benefit Pancreatic Cancer  \n\nBuy tickets here: https://stza.co/~vLmg\n\nFollow on MiLB First Pitch: https://stza.co/+vLmg-G\n\nShop: https://stza.co/+vLmg-H\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Atlas Fireworks
STATUS:CONFIRMED
CREATED:20180213T144531Z
LAST-MODIFIED:20180213T144531Z
TRANSP:OPAQUE
END:VEVENT
* Yard Goats vs. Baysox
<2018-08-11 Sat 17:05-20:05>
:PROPERTIES:
:ID:       sKz9stDCEASboHRaEHXopNg6@stanza.co
:LOCATION: Atlas Fireworks
:STATUS:   CONFIRMED
:END:

Yard Goats vs. Baysox 





Buy tickets here  https //stza.co/~vLmh

Follow on MiLB First Pitch  https //stza.co/+vLmh-3Q

Shop  https //stza.co/+vLmh-Y

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Yard Goats vs. Baysox
END:VALARM
DTSTART:20180811T220500Z
DTEND:20180812T010500Z
UID:sKz9stDCEASboHRaEHXopNg6@stanza.co
SUMMARY:Yard Goats vs. Baysox
DESCRIPTION:\n\n\n\n\n\nBuy tickets here: https://stza.co/~vLmh\n\nFollow on MiLB First Pitch: https://stza.co/+vLmh-3Q\n\nShop: https://stza.co/+vLmh-Y\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Atlas Fireworks
STATUS:CONFIRMED
CREATED:20180213T144531Z
LAST-MODIFIED:20180213T144531Z
TRANSP:OPAQUE
END:VEVENT
* Yard Goats vs. Baysox
<2018-08-12 Sun 16:05-19:05>
:PROPERTIES:
:ID:       tHGMVMFtmwD3wTYfENNRRlek@stanza.co
:LOCATION: Steamed Cheeseburger Night
:STATUS:   CONFIRMED
:END:

Yard Goats vs. Baysox 



Buy tickets here  https //stza.co/~vLmj

Follow on MiLB First Pitch  https //stza.co/+vLmj-3U

Shop  https //stza.co/+vLmj-1

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Yard Goats vs. Baysox
END:VALARM
DTSTART:20180812T210500Z
DTEND:20180813T000500Z
UID:tHGMVMFtmwD3wTYfENNRRlek@stanza.co
SUMMARY:Yard Goats vs. Baysox
DESCRIPTION:\n\n\n\nBuy tickets here: https://stza.co/~vLmj\n\nFollow on MiLB First Pitch: https://stza.co/+vLmj-3U\n\nShop: https://stza.co/+vLmj-1\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Steamed Cheeseburger Night
STATUS:CONFIRMED
CREATED:20180213T144531Z
LAST-MODIFIED:20180213T144531Z
TRANSP:OPAQUE
END:VEVENT
* Yard Goats @ Fightin Phils
<2018-08-14 Tue 18:05-21:05>
:PROPERTIES:
:ID:       d-d1XeY1IPa27iNXuY3ULOQL@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Yard Goats @ Fightin Phils Yard Goats @ Fightin Phils

Buy tickets here  https //stza.co/~v9m7

Follow on MiLB First Pitch  https //stza.co/+v9m7-3f

Shop  https //stza.co/+v9m7-$

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Yard Goats @ Fightin Phils
END:VALARM
DTSTART:20180814T230500Z
DTEND:20180815T020500Z
UID:d-d1XeY1IPa27iNXuY3ULOQL@stanza.co
SUMMARY:Yard Goats @ Fightin Phils
DESCRIPTION:Yard Goats @ Fightin Phils\n\nBuy tickets here: https://stza.co/~v9m7\n\nFollow on MiLB First Pitch: https://stza.co/+v9m7-3f\n\nShop: https://stza.co/+v9m7-$\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144531Z
LAST-MODIFIED:20180213T144531Z
TRANSP:OPAQUE
END:VEVENT
* Yard Goats @ Fightin Phils
<2018-08-15 Wed 18:05-21:05>
:PROPERTIES:
:ID:       oYoPGj87JlMzsd-ujfgbemd1@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Yard Goats @ Fightin Phils Yard Goats @ Fightin Phils

Buy tickets here  https //stza.co/~v9m8

Follow on MiLB First Pitch  https //stza.co/+v9m8-s

Shop  https //stza.co/+v9m8-g

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Yard Goats @ Fightin Phils
END:VALARM
DTSTART:20180815T230500Z
DTEND:20180816T020500Z
UID:oYoPGj87JlMzsd-ujfgbemd1@stanza.co
SUMMARY:Yard Goats @ Fightin Phils
DESCRIPTION:Yard Goats @ Fightin Phils\n\nBuy tickets here: https://stza.co/~v9m8\n\nFollow on MiLB First Pitch: https://stza.co/+v9m8-s\n\nShop: https://stza.co/+v9m8-g\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144531Z
LAST-MODIFIED:20180213T144531Z
TRANSP:OPAQUE
END:VEVENT
* Yard Goats @ Fightin Phils
<2018-08-16 Thu 18:05-21:05>
:PROPERTIES:
:ID:       tfx_zbB4YZ7na1z_yAZ6C7rp@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Yard Goats @ Fightin Phils Yard Goats @ Fightin Phils

Buy tickets here  https //stza.co/~v9m9

Follow on MiLB First Pitch  https //stza.co/+v9m9-29

Shop  https //stza.co/+v9m9-3I

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Yard Goats @ Fightin Phils
END:VALARM
DTSTART:20180816T230500Z
DTEND:20180817T020500Z
UID:tfx_zbB4YZ7na1z_yAZ6C7rp@stanza.co
SUMMARY:Yard Goats @ Fightin Phils
DESCRIPTION:Yard Goats @ Fightin Phils\n\nBuy tickets here: https://stza.co/~v9m9\n\nFollow on MiLB First Pitch: https://stza.co/+v9m9-29\n\nShop: https://stza.co/+v9m9-3I\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144531Z
LAST-MODIFIED:20180213T144531Z
TRANSP:OPAQUE
END:VEVENT
* Yard Goats @ Flying Squirrels
<2018-08-17 Fri 18:05-21:05>
:PROPERTIES:
:ID:       FwEoFw-EnyOWIsyi8sIsiP1e@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Yard Goats @ Flying Squirrels Yard Goats @ Flying Squirrels

Follow on MiLB First Pitch  https //stza.co/+v9md-2w

Shop  https //stza.co/+v9md-1o

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Yard Goats @ Flying Squirrels
END:VALARM
DTSTART:20180817T230500Z
DTEND:20180818T020500Z
UID:FwEoFw-EnyOWIsyi8sIsiP1e@stanza.co
SUMMARY:Yard Goats @ Flying Squirrels
DESCRIPTION:Yard Goats @ Flying Squirrels\n\nFollow on MiLB First Pitch: https://stza.co/+v9md-2w\n\nShop: https://stza.co/+v9md-1o\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144531Z
LAST-MODIFIED:20180213T144531Z
TRANSP:OPAQUE
END:VEVENT
* Yard Goats @ Flying Squirrels
<2018-08-18 Sat 17:05-20:05>
:PROPERTIES:
:ID:       WMqHVpH27mazmEmiozbA8-zf@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Yard Goats @ Flying Squirrels Yard Goats @ Flying Squirrels

Follow on MiLB First Pitch  https //stza.co/+v9me-2H

Shop  https //stza.co/+v9me-t

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Yard Goats @ Flying Squirrels
END:VALARM
DTSTART:20180818T220500Z
DTEND:20180819T010500Z
UID:WMqHVpH27mazmEmiozbA8-zf@stanza.co
SUMMARY:Yard Goats @ Flying Squirrels
DESCRIPTION:Yard Goats @ Flying Squirrels\n\nFollow on MiLB First Pitch: https://stza.co/+v9me-2H\n\nShop: https://stza.co/+v9me-t\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144531Z
LAST-MODIFIED:20180213T144531Z
TRANSP:OPAQUE
END:VEVENT
* Yard Goats @ Flying Squirrels
<2018-08-19 Sun 12:05-15:05>
:PROPERTIES:
:ID:       Y3h7Hjlf0_d84_eOoP0cIJrx@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Yard Goats @ Flying Squirrels Yard Goats @ Flying Squirrels

Follow on MiLB First Pitch  https //stza.co/+v9mf-21

Shop  https //stza.co/+v9mf-1U

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Yard Goats @ Flying Squirrels
END:VALARM
DTSTART:20180819T170500Z
DTEND:20180819T200500Z
UID:Y3h7Hjlf0_d84_eOoP0cIJrx@stanza.co
SUMMARY:Yard Goats @ Flying Squirrels
DESCRIPTION:Yard Goats @ Flying Squirrels\n\nFollow on MiLB First Pitch: https://stza.co/+v9mf-21\n\nShop: https://stza.co/+v9mf-1U\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144531Z
LAST-MODIFIED:20180213T144531Z
TRANSP:OPAQUE
END:VEVENT
* Yard Goats @ Thunder
<2018-08-20 Mon 18:00-21:00>
:PROPERTIES:
:ID:       3fRG1e_eiJwNHzXaYbGStlBr@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Yard Goats @ Thunder Yard Goats @ Thunder

Follow on MiLB First Pitch  https //stza.co/+v9mj-1k

Shop  https //stza.co/+v9mj-1Q

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Yard Goats @ Thunder
END:VALARM
DTSTART:20180820T230000Z
DTEND:20180821T020000Z
UID:3fRG1e_eiJwNHzXaYbGStlBr@stanza.co
SUMMARY:Yard Goats @ Thunder
DESCRIPTION:Yard Goats @ Thunder\n\nFollow on MiLB First Pitch: https://stza.co/+v9mj-1k\n\nShop: https://stza.co/+v9mj-1Q\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144531Z
LAST-MODIFIED:20180213T144531Z
TRANSP:OPAQUE
END:VEVENT
* Yard Goats @ Thunder
<2018-08-21 Tue 18:00-21:00>
:PROPERTIES:
:ID:       -LZ4HGyPd23pIznbTWvJUavr@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Yard Goats @ Thunder Yard Goats @ Thunder

Follow on MiLB First Pitch  https //stza.co/+v9mk-19

Shop  https //stza.co/+v9mk-2p

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Yard Goats @ Thunder
END:VALARM
DTSTART:20180821T230000Z
DTEND:20180822T020000Z
UID:-LZ4HGyPd23pIznbTWvJUavr@stanza.co
SUMMARY:Yard Goats @ Thunder
DESCRIPTION:Yard Goats @ Thunder\n\nFollow on MiLB First Pitch: https://stza.co/+v9mk-19\n\nShop: https://stza.co/+v9mk-2p\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144531Z
LAST-MODIFIED:20180213T144531Z
TRANSP:OPAQUE
END:VEVENT
* Yard Goats vs. Rumble Ponies
<2018-08-22 Wed 18:05-21:05>
:PROPERTIES:
:ID:       DlN_8fL578qoV6t8G_guxB3q@stanza.co
:LOCATION: Eat Well Night
:STATUS:   CONFIRMED
:END:

Yard Goats vs. Rumble Ponies 



Buy tickets here  https //stza.co/~vLmm

Follow on MiLB First Pitch  https //stza.co/+vLmm-d

Shop  https //stza.co/+vLmm-3J

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Yard Goats vs. Rumble Ponies
END:VALARM
DTSTART:20180822T230500Z
DTEND:20180823T020500Z
UID:DlN_8fL578qoV6t8G_guxB3q@stanza.co
SUMMARY:Yard Goats vs. Rumble Ponies
DESCRIPTION:\n\n\n\nBuy tickets here: https://stza.co/~vLmm\n\nFollow on MiLB First Pitch: https://stza.co/+vLmm-d\n\nShop: https://stza.co/+vLmm-3J\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Eat Well Night
STATUS:CONFIRMED
CREATED:20180213T144531Z
LAST-MODIFIED:20180213T144531Z
TRANSP:OPAQUE
END:VEVENT
* Yard Goats vs. Rumble Ponies
<2018-08-23 Thu 18:05-21:05>
:PROPERTIES:
:ID:       C5Dwo30tdA_KETHAf-yJVnpH@stanza.co
:LOCATION: ZOOperstars! Appearance
:STATUS:   CONFIRMED
:END:

Yard Goats vs. Rumble Ponies 





Buy tickets here  https //stza.co/~vLmo

Follow on MiLB First Pitch  https //stza.co/+vLmo-2t

Shop  https //stza.co/+vLmo-2q

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Yard Goats vs. Rumble Ponies
END:VALARM
DTSTART:20180823T230500Z
DTEND:20180824T020500Z
UID:C5Dwo30tdA_KETHAf-yJVnpH@stanza.co
SUMMARY:Yard Goats vs. Rumble Ponies
DESCRIPTION:\n\n\n\n\n\nBuy tickets here: https://stza.co/~vLmo\n\nFollow on MiLB First Pitch: https://stza.co/+vLmo-2t\n\nShop: https://stza.co/+vLmo-2q\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:ZOOperstars! Appearance
STATUS:CONFIRMED
CREATED:20180213T144531Z
LAST-MODIFIED:20180213T144531Z
TRANSP:OPAQUE
END:VEVENT
* Yard Goats vs. Thunder
<2018-08-24 Fri 18:05-21:05>
:PROPERTIES:
:ID:       r3jM2poXmsjioyBCAiuNuGQx@stanza.co
:LOCATION: Atlas Fireworks
:STATUS:   CONFIRMED
:END:

Yard Goats vs. Thunder 



Buy tickets here  https //stza.co/~vLmq

Follow on MiLB First Pitch  https //stza.co/+vLmq-2E

Shop  https //stza.co/+vLmq-1y

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Yard Goats vs. Thunder
END:VALARM
DTSTART:20180824T230500Z
DTEND:20180825T020500Z
UID:r3jM2poXmsjioyBCAiuNuGQx@stanza.co
SUMMARY:Yard Goats vs. Thunder
DESCRIPTION:\n\n\n\nBuy tickets here: https://stza.co/~vLmq\n\nFollow on MiLB First Pitch: https://stza.co/+vLmq-2E\n\nShop: https://stza.co/+vLmq-1y\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Atlas Fireworks
STATUS:CONFIRMED
CREATED:20180213T144531Z
LAST-MODIFIED:20180213T144531Z
TRANSP:OPAQUE
END:VEVENT
* Yard Goats vs. Thunder
<2018-08-25 Sat 17:05-20:05>
:PROPERTIES:
:ID:       NkPT5jKBw1OzQfkIoGV9dFXQ@stanza.co
:LOCATION: Atlas Fireworks
:STATUS:   CONFIRMED
:END:

Yard Goats vs. Thunder 

With pre-game player forum.

Buy tickets here  https //stza.co/~vLmr

Follow on MiLB First Pitch  https //stza.co/+vLmr-1Y

Shop  https //stza.co/+vLmr-1a

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Yard Goats vs. Thunder
END:VALARM
DTSTART:20180825T220500Z
DTEND:20180826T010500Z
UID:NkPT5jKBw1OzQfkIoGV9dFXQ@stanza.co
SUMMARY:Yard Goats vs. Thunder
DESCRIPTION:\n\nWith pre-game player forum.\n\nBuy tickets here: https://stza.co/~vLmr\n\nFollow on MiLB First Pitch: https://stza.co/+vLmr-1Y\n\nShop: https://stza.co/+vLmr-1a\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Atlas Fireworks
STATUS:CONFIRMED
CREATED:20180213T144531Z
LAST-MODIFIED:20180213T144531Z
TRANSP:OPAQUE
END:VEVENT
* Yard Goats vs. Thunder
<2018-08-26 Sun 12:05-15:05>
:PROPERTIES:
:ID:       YQ1TZ9T40074HiiXAMe3kIZB@stanza.co
:LOCATION: Faith and Family Day
:STATUS:   CONFIRMED
:END:

Yard Goats vs. Thunder 



Buy tickets here  https //stza.co/~vLmu

Follow on MiLB First Pitch  https //stza.co/+vLmu-1j

Shop  https //stza.co/+vLmu-2t

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Yard Goats vs. Thunder
END:VALARM
DTSTART:20180826T170500Z
DTEND:20180826T200500Z
UID:YQ1TZ9T40074HiiXAMe3kIZB@stanza.co
SUMMARY:Yard Goats vs. Thunder
DESCRIPTION:\n\n\n\nBuy tickets here: https://stza.co/~vLmu\n\nFollow on MiLB First Pitch: https://stza.co/+vLmu-1j\n\nShop: https://stza.co/+vLmu-2t\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Faith and Family Day
STATUS:CONFIRMED
CREATED:20180213T144531Z
LAST-MODIFIED:20180213T144531Z
TRANSP:OPAQUE
END:VEVENT
* Yard Goats vs. Rumble Ponies
<2018-08-27 Mon 18:05-21:05>
:PROPERTIES:
:ID:       0jNEBytxh3-vuLrwZfPz1FKy@stanza.co
:LOCATION: Looking for something to do tonight? Get tickets here for tonight’s game and view promotions.
:STATUS:   CONFIRMED
:END:

Yard Goats vs. Rumble Ponies Yard Goats vs. Rumble Ponies

Buy tickets here  https //stza.co/~vLmw

Follow on MiLB First Pitch  https //stza.co/+vLmw-2I

Shop  https //stza.co/+vLmw-30

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Yard Goats vs. Rumble Ponies
END:VALARM
DTSTART:20180827T230500Z
DTEND:20180828T020500Z
UID:0jNEBytxh3-vuLrwZfPz1FKy@stanza.co
SUMMARY:Yard Goats vs. Rumble Ponies
DESCRIPTION:Yard Goats vs. Rumble Ponies\n\nBuy tickets here: https://stza.co/~vLmw\n\nFollow on MiLB First Pitch: https://stza.co/+vLmw-2I\n\nShop: https://stza.co/+vLmw-30\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Looking for something to do tonight? Get tickets here for tonight’s game and view promotions.
STATUS:CONFIRMED
CREATED:20180213T144531Z
LAST-MODIFIED:20180213T144531Z
TRANSP:OPAQUE
END:VEVENT
* Yard Goats vs. Rumble Ponies
<2018-08-28 Tue 18:05-21:05>
:PROPERTIES:
:ID:       vJd08ErIgNmrutdQl0bIIlnA@stanza.co
:LOCATION: Power of Ability Night
:STATUS:   CONFIRMED
:END:

Yard Goats vs. Rumble Ponies 

Play BINGO while watching the Yard Goats play baseball and win great prizes!

Buy tickets here  https //stza.co/~vLmx

Follow on MiLB First Pitch  https //stza.co/+vLmx-Z

Shop  https //stza.co/+vLmx-2Z

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Yard Goats vs. Rumble Ponies
END:VALARM
DTSTART:20180828T230500Z
DTEND:20180829T020500Z
UID:vJd08ErIgNmrutdQl0bIIlnA@stanza.co
SUMMARY:Yard Goats vs. Rumble Ponies
DESCRIPTION:\n\nPlay BINGO while watching the Yard Goats play baseball and win great prizes!\n\nBuy tickets here: https://stza.co/~vLmx\n\nFollow on MiLB First Pitch: https://stza.co/+vLmx-Z\n\nShop: https://stza.co/+vLmx-2Z\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Power of Ability Night
STATUS:CONFIRMED
CREATED:20180213T144531Z
LAST-MODIFIED:20180213T144531Z
TRANSP:OPAQUE
END:VEVENT
* Yard Goats vs. Rumble Ponies
<2018-08-29 Wed 18:05-21:05>
:PROPERTIES:
:ID:       RT1UFFjQ8z_n2jRf6ZDQE3k5@stanza.co
:LOCATION: Kid's Lunch Box Giveaway
:STATUS:   CONFIRMED
:END:

Yard Goats vs. Rumble Ponies 



Buy tickets here  https //stza.co/~vLmA

Follow on MiLB First Pitch  https //stza.co/+vLmA-2m

Shop  https //stza.co/+vLmA-v

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Yard Goats vs. Rumble Ponies
END:VALARM
DTSTART:20180829T230500Z
DTEND:20180830T020500Z
UID:RT1UFFjQ8z_n2jRf6ZDQE3k5@stanza.co
SUMMARY:Yard Goats vs. Rumble Ponies
DESCRIPTION:\n\n\n\nBuy tickets here: https://stza.co/~vLmA\n\nFollow on MiLB First Pitch: https://stza.co/+vLmA-2m\n\nShop: https://stza.co/+vLmA-v\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Kid's Lunch Box Giveaway
STATUS:CONFIRMED
CREATED:20180213T144531Z
LAST-MODIFIED:20180213T144531Z
TRANSP:OPAQUE
END:VEVENT
* Yard Goats vs. Rumble Ponies
<2018-08-30 Thu 18:05-21:05>
:PROPERTIES:
:ID:       ziGIJvv1Dhryk_mCI6Wi9cTZ@stanza.co
:LOCATION: Great seats still available for tonight’s game. Purchase them here.
:STATUS:   CONFIRMED
:END:

Yard Goats vs. Rumble Ponies Yard Goats vs. Rumble Ponies

Buy tickets here  https //stza.co/~vLmB

Follow on MiLB First Pitch  https //stza.co/+vLmB-3K

Shop  https //stza.co/+vLmB-23

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Yard Goats vs. Rumble Ponies
END:VALARM
DTSTART:20180830T230500Z
DTEND:20180831T020500Z
UID:ziGIJvv1Dhryk_mCI6Wi9cTZ@stanza.co
SUMMARY:Yard Goats vs. Rumble Ponies
DESCRIPTION:Yard Goats vs. Rumble Ponies\n\nBuy tickets here: https://stza.co/~vLmB\n\nFollow on MiLB First Pitch: https://stza.co/+vLmB-3K\n\nShop: https://stza.co/+vLmB-23\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Great seats still available for tonight’s game. Purchase them here.
STATUS:CONFIRMED
CREATED:20180213T144531Z
LAST-MODIFIED:20180213T144531Z
TRANSP:OPAQUE
END:VEVENT
* Yard Goats @ Fisher Cats
<2018-08-31 Fri 18:05-21:05>
:PROPERTIES:
:ID:       MFGzALsotFdgkk-PeNjuKjmn@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Yard Goats @ Fisher Cats Yard Goats @ Fisher Cats

Follow on MiLB First Pitch  https //stza.co/+vLmK-U

Shop  https //stza.co/+vLmK-3E

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Yard Goats @ Fisher Cats
END:VALARM
DTSTART:20180831T230500Z
DTEND:20180901T020500Z
UID:MFGzALsotFdgkk-PeNjuKjmn@stanza.co
SUMMARY:Yard Goats @ Fisher Cats
DESCRIPTION:Yard Goats @ Fisher Cats\n\nFollow on MiLB First Pitch: https://stza.co/+vLmK-U\n\nShop: https://stza.co/+vLmK-3E\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144531Z
LAST-MODIFIED:20180213T144531Z
TRANSP:OPAQUE
END:VEVENT
* Yard Goats @ Fisher Cats
<2018-09-01 Sat 18:05-21:05>
:PROPERTIES:
:ID:       8_dJmC7dZNyHoHdW4-vGe2lv@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Yard Goats @ Fisher Cats Yard Goats @ Fisher Cats

Follow on MiLB First Pitch  https //stza.co/+vLmL-3p

Shop  https //stza.co/+vLmL-4

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Yard Goats @ Fisher Cats
END:VALARM
DTSTART:20180901T230500Z
DTEND:20180902T020500Z
UID:8_dJmC7dZNyHoHdW4-vGe2lv@stanza.co
SUMMARY:Yard Goats @ Fisher Cats
DESCRIPTION:Yard Goats @ Fisher Cats\n\nFollow on MiLB First Pitch: https://stza.co/+vLmL-3p\n\nShop: https://stza.co/+vLmL-4\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144531Z
LAST-MODIFIED:20180213T144531Z
TRANSP:OPAQUE
END:VEVENT
* Yard Goats @ Fisher Cats
<2018-09-02 Sun 12:35-15:35>
:PROPERTIES:
:ID:       7ZWaSKNcOBtC2Y7UTzrpO2xY@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Yard Goats @ Fisher Cats Yard Goats @ Fisher Cats

Follow on MiLB First Pitch  https //stza.co/+vLmM-12

Shop  https //stza.co/+vLmM-1N

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Yard Goats @ Fisher Cats
END:VALARM
DTSTART:20180902T173500Z
DTEND:20180902T203500Z
UID:7ZWaSKNcOBtC2Y7UTzrpO2xY@stanza.co
SUMMARY:Yard Goats @ Fisher Cats
DESCRIPTION:Yard Goats @ Fisher Cats\n\nFollow on MiLB First Pitch: https://stza.co/+vLmM-12\n\nShop: https://stza.co/+vLmM-1N\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144531Z
LAST-MODIFIED:20180213T144531Z
TRANSP:OPAQUE
END:VEVENT
* Yard Goats @ Fisher Cats
<2018-09-03 Mon 12:35-15:35>
:PROPERTIES:
:ID:       s22mCA7v8xh4qo2R-be_bCB6@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Yard Goats @ Fisher Cats Yard Goats @ Fisher Cats

Follow on MiLB First Pitch  https //stza.co/+vLmN-_

Shop  https //stza.co/+vLmN-2d

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Yard Goats @ Fisher Cats
END:VALARM
DTSTART:20180903T173500Z
DTEND:20180903T203500Z
UID:s22mCA7v8xh4qo2R-be_bCB6@stanza.co
SUMMARY:Yard Goats @ Fisher Cats
DESCRIPTION:Yard Goats @ Fisher Cats\n\nFollow on MiLB First Pitch: https://stza.co/+vLmN-_\n\nShop: https://stza.co/+vLmN-2d\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144531Z
LAST-MODIFIED:20180213T144531Z
TRANSP:OPAQUE
END:VEVENT
