#+TITLE:       Main Google calendar entries
#+AUTHOR:      Eric S Fraga
#+EMAIL:       e.fraga@ucl.ac.uk
#+DESCRIPTION: converted using the ical2org awk script
#+CATEGORY:    google
#+STARTUP:     hidestars
#+STARTUP:     overview

* COMMENT original iCal preamble

* Miracle vs. Stone Crabs
<2018-04-05 Thu 18:00-21:00>
:PROPERTIES:
:ID:       Y1lWqyXkgC_CdBpq1GCG-7OH@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Miracle vs. Stone Crabs Miracle vs. Stone Crabs

Follow on MiLB First Pitch  https //stza.co/+xMaQ-1c

Shop  https //stza.co/+xMaQ-1t

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Miracle vs. Stone Crabs
END:VALARM
DTSTART:20180405T230000Z
DTEND:20180406T020000Z
UID:Y1lWqyXkgC_CdBpq1GCG-7OH@stanza.co
SUMMARY:Miracle vs. Stone Crabs
DESCRIPTION:Miracle vs. Stone Crabs\n\nFollow on MiLB First Pitch: https://stza.co/+xMaQ-1c\n\nShop: https://stza.co/+xMaQ-1t\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144525Z
LAST-MODIFIED:20180213T144525Z
TRANSP:OPAQUE
END:VEVENT
* Miracle vs. Stone Crabs
<2018-04-06 Fri 18:00-21:00>
:PROPERTIES:
:ID:       4h5-STnejPRb3yqGNrLhOtGm@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Miracle vs. Stone Crabs Miracle vs. Stone Crabs

Follow on MiLB First Pitch  https //stza.co/+xMaR-1O

Shop  https //stza.co/+xMaR-1i

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Miracle vs. Stone Crabs
END:VALARM
DTSTART:20180406T230000Z
DTEND:20180407T020000Z
UID:4h5-STnejPRb3yqGNrLhOtGm@stanza.co
SUMMARY:Miracle vs. Stone Crabs
DESCRIPTION:Miracle vs. Stone Crabs\n\nFollow on MiLB First Pitch: https://stza.co/+xMaR-1O\n\nShop: https://stza.co/+xMaR-1i\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144525Z
LAST-MODIFIED:20180213T144525Z
TRANSP:OPAQUE
END:VEVENT
* Miracle @ Stone Crabs
<2018-04-07 Sat 17:05-20:05>
:PROPERTIES:
:ID:       qiQZr0I6G_UYhNznvjI0Rm8w@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Miracle @ Stone Crabs Miracle @ Stone Crabs

Follow on MiLB First Pitch  https //stza.co/+wYo7-2y

Shop  https //stza.co/+wYo7-2a

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Miracle @ Stone Crabs
END:VALARM
DTSTART:20180407T220500Z
DTEND:20180408T010500Z
UID:qiQZr0I6G_UYhNznvjI0Rm8w@stanza.co
SUMMARY:Miracle @ Stone Crabs
DESCRIPTION:Miracle @ Stone Crabs\n\nFollow on MiLB First Pitch: https://stza.co/+wYo7-2y\n\nShop: https://stza.co/+wYo7-2a\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144525Z
LAST-MODIFIED:20180213T144525Z
TRANSP:OPAQUE
END:VEVENT
* Miracle @ Stone Crabs
<2018-04-08 Sun 11:35-14:35>
:PROPERTIES:
:ID:       FMd_c4Uc3ByPL1NGKrQHgx01@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Miracle @ Stone Crabs Miracle @ Stone Crabs

Follow on MiLB First Pitch  https //stza.co/+wYo8-25

Shop  https //stza.co/+wYo8-3G

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Miracle @ Stone Crabs
END:VALARM
DTSTART:20180408T163500Z
DTEND:20180408T193500Z
UID:FMd_c4Uc3ByPL1NGKrQHgx01@stanza.co
SUMMARY:Miracle @ Stone Crabs
DESCRIPTION:Miracle @ Stone Crabs\n\nFollow on MiLB First Pitch: https://stza.co/+wYo8-25\n\nShop: https://stza.co/+wYo8-3G\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144525Z
LAST-MODIFIED:20180213T144525Z
TRANSP:OPAQUE
END:VEVENT
* Miracle vs. Fire Frogs
<2018-04-09 Mon 18:00-21:00>
:PROPERTIES:
:ID:       hH9YyvMP05-LOpbryw4z5ivw@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Miracle vs. Fire Frogs Miracle vs. Fire Frogs

Follow on MiLB First Pitch  https //stza.co/+xMaT-q

Shop  https //stza.co/+xMaT-3s

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Miracle vs. Fire Frogs
END:VALARM
DTSTART:20180409T230000Z
DTEND:20180410T020000Z
UID:hH9YyvMP05-LOpbryw4z5ivw@stanza.co
SUMMARY:Miracle vs. Fire Frogs
DESCRIPTION:Miracle vs. Fire Frogs\n\nFollow on MiLB First Pitch: https://stza.co/+xMaT-q\n\nShop: https://stza.co/+xMaT-3s\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144525Z
LAST-MODIFIED:20180213T144525Z
TRANSP:OPAQUE
END:VEVENT
* Miracle vs. Fire Frogs
<2018-04-10 Tue 18:00-21:00>
:PROPERTIES:
:ID:       pzjh1U4U0Zc36TNQGT-gTr_n@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Miracle vs. Fire Frogs Miracle vs. Fire Frogs

Follow on MiLB First Pitch  https //stza.co/+xMaV-3M

Shop  https //stza.co/+xMaV-6

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Miracle vs. Fire Frogs
END:VALARM
DTSTART:20180410T230000Z
DTEND:20180411T020000Z
UID:pzjh1U4U0Zc36TNQGT-gTr_n@stanza.co
SUMMARY:Miracle vs. Fire Frogs
DESCRIPTION:Miracle vs. Fire Frogs\n\nFollow on MiLB First Pitch: https://stza.co/+xMaV-3M\n\nShop: https://stza.co/+xMaV-6\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144525Z
LAST-MODIFIED:20180213T144525Z
TRANSP:OPAQUE
END:VEVENT
* Miracle vs. Fire Frogs
<2018-04-11 Wed 18:00-21:00>
:PROPERTIES:
:ID:       Z1O8Hx-89lnRcEb6qvGT443O@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Miracle vs. Fire Frogs Miracle vs. Fire Frogs

Follow on MiLB First Pitch  https //stza.co/+xMaY-1g

Shop  https //stza.co/+xMaY-m

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Miracle vs. Fire Frogs
END:VALARM
DTSTART:20180411T230000Z
DTEND:20180412T020000Z
UID:Z1O8Hx-89lnRcEb6qvGT443O@stanza.co
SUMMARY:Miracle vs. Fire Frogs
DESCRIPTION:Miracle vs. Fire Frogs\n\nFollow on MiLB First Pitch: https://stza.co/+xMaY-1g\n\nShop: https://stza.co/+xMaY-m\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144525Z
LAST-MODIFIED:20180213T144525Z
TRANSP:OPAQUE
END:VEVENT
* Miracle vs. Fire Frogs
<2018-04-12 Thu 18:00-21:00>
:PROPERTIES:
:ID:       oswze5NnAzURXSv0HwH-x74H@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Miracle vs. Fire Frogs Miracle vs. Fire Frogs

Follow on MiLB First Pitch  https //stza.co/+xMa_-v

Shop  https //stza.co/+xMa_-1X

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Miracle vs. Fire Frogs
END:VALARM
DTSTART:20180412T230000Z
DTEND:20180413T020000Z
UID:oswze5NnAzURXSv0HwH-x74H@stanza.co
SUMMARY:Miracle vs. Fire Frogs
DESCRIPTION:Miracle vs. Fire Frogs\n\nFollow on MiLB First Pitch: https://stza.co/+xMa_-v\n\nShop: https://stza.co/+xMa_-1X\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144525Z
LAST-MODIFIED:20180213T144525Z
TRANSP:OPAQUE
END:VEVENT
* Miracle vs. Tarpons
<2018-04-13 Fri 18:00-21:00>
:PROPERTIES:
:ID:       O3bZ4muB-gM1DmkrBaDKN1Xf@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Miracle vs. Tarpons Miracle vs. Tarpons

Follow on MiLB First Pitch  https //stza.co/+xMa$-2F

Shop  https //stza.co/+xMa$-x

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Miracle vs. Tarpons
END:VALARM
DTSTART:20180413T230000Z
DTEND:20180414T020000Z
UID:O3bZ4muB-gM1DmkrBaDKN1Xf@stanza.co
SUMMARY:Miracle vs. Tarpons
DESCRIPTION:Miracle vs. Tarpons\n\nFollow on MiLB First Pitch: https://stza.co/+xMa$-2F\n\nShop: https://stza.co/+xMa$-x\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144525Z
LAST-MODIFIED:20180213T144525Z
TRANSP:OPAQUE
END:VEVENT
* Miracle vs. Tarpons
<2018-04-14 Sat 17:00-20:00>
:PROPERTIES:
:ID:       vEQ_1lJP-Q2fjNnt9Y5hNcZp@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Miracle vs. Tarpons Miracle vs. Tarpons

Follow on MiLB First Pitch  https //stza.co/+xMb1-

Shop  https //stza.co/+xMb1-y

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Miracle vs. Tarpons
END:VALARM
DTSTART:20180414T220000Z
DTEND:20180415T010000Z
UID:vEQ_1lJP-Q2fjNnt9Y5hNcZp@stanza.co
SUMMARY:Miracle vs. Tarpons
DESCRIPTION:Miracle vs. Tarpons\n\nFollow on MiLB First Pitch: https://stza.co/+xMb1-\n\nShop: https://stza.co/+xMb1-y\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144525Z
LAST-MODIFIED:20180213T144525Z
TRANSP:OPAQUE
END:VEVENT
* Miracle vs. Tarpons
<2018-04-15 Sun 15:00-18:00>
:PROPERTIES:
:ID:       ipPwLBhfWoiOYTfHc33x20f_@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Miracle vs. Tarpons Miracle vs. Tarpons

Follow on MiLB First Pitch  https //stza.co/+xMb4-1

Shop  https //stza.co/+xMb4-V

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Miracle vs. Tarpons
END:VALARM
DTSTART:20180415T200000Z
DTEND:20180415T230000Z
UID:ipPwLBhfWoiOYTfHc33x20f_@stanza.co
SUMMARY:Miracle vs. Tarpons
DESCRIPTION:Miracle vs. Tarpons\n\nFollow on MiLB First Pitch: https://stza.co/+xMb4-1\n\nShop: https://stza.co/+xMb4-V\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144525Z
LAST-MODIFIED:20180213T144525Z
TRANSP:OPAQUE
END:VEVENT
* Miracle @ Blue Jays
<2018-04-17 Tue 17:30-20:30>
:PROPERTIES:
:ID:       gsDw4rxQqrViRvaD138H6mMJ@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Miracle @ Blue Jays Miracle @ Blue Jays

Follow on MiLB First Pitch  https //stza.co/+y0Jt-1O

Shop  https //stza.co/+y0Jt-1_

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Miracle @ Blue Jays
END:VALARM
DTSTART:20180417T223000Z
DTEND:20180418T013000Z
UID:gsDw4rxQqrViRvaD138H6mMJ@stanza.co
SUMMARY:Miracle @ Blue Jays
DESCRIPTION:Miracle @ Blue Jays\n\nFollow on MiLB First Pitch: https://stza.co/+y0Jt-1O\n\nShop: https://stza.co/+y0Jt-1_\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144525Z
LAST-MODIFIED:20180213T144525Z
TRANSP:OPAQUE
END:VEVENT
* Miracle @ Blue Jays
<2018-04-18 Wed 17:30-20:30>
:PROPERTIES:
:ID:       7H6YxCOtrX-NfSMjucChWQc1@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Miracle @ Blue Jays Miracle @ Blue Jays

Follow on MiLB First Pitch  https //stza.co/+y0Jv-2f

Shop  https //stza.co/+y0Jv-z

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Miracle @ Blue Jays
END:VALARM
DTSTART:20180418T223000Z
DTEND:20180419T013000Z
UID:7H6YxCOtrX-NfSMjucChWQc1@stanza.co
SUMMARY:Miracle @ Blue Jays
DESCRIPTION:Miracle @ Blue Jays\n\nFollow on MiLB First Pitch: https://stza.co/+y0Jv-2f\n\nShop: https://stza.co/+y0Jv-z\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144525Z
LAST-MODIFIED:20180213T144525Z
TRANSP:OPAQUE
END:VEVENT
* Miracle @ Blue Jays
<2018-04-19 Thu 17:30-20:30>
:PROPERTIES:
:ID:       UW1R3sb5awthpj0dCjVQtcz6@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Miracle @ Blue Jays Miracle @ Blue Jays

Follow on MiLB First Pitch  https //stza.co/+y0Jx-1H

Shop  https //stza.co/+y0Jx-1P

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Miracle @ Blue Jays
END:VALARM
DTSTART:20180419T223000Z
DTEND:20180420T013000Z
UID:UW1R3sb5awthpj0dCjVQtcz6@stanza.co
SUMMARY:Miracle @ Blue Jays
DESCRIPTION:Miracle @ Blue Jays\n\nFollow on MiLB First Pitch: https://stza.co/+y0Jx-1H\n\nShop: https://stza.co/+y0Jx-1P\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144525Z
LAST-MODIFIED:20180213T144525Z
TRANSP:OPAQUE
END:VEVENT
* Miracle @ Marauders
<2018-04-20 Fri 17:30-20:30>
:PROPERTIES:
:ID:       Ho2O1S1dN_ynXBTFo_7FmKWn@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Miracle @ Marauders Miracle @ Marauders

Follow on MiLB First Pitch  https //stza.co/+vMq$-1c

Shop  https //stza.co/+vMq$-2D

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Miracle @ Marauders
END:VALARM
DTSTART:20180420T223000Z
DTEND:20180421T013000Z
UID:Ho2O1S1dN_ynXBTFo_7FmKWn@stanza.co
SUMMARY:Miracle @ Marauders
DESCRIPTION:Miracle @ Marauders\n\nFollow on MiLB First Pitch: https://stza.co/+vMq$-1c\n\nShop: https://stza.co/+vMq$-2D\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144525Z
LAST-MODIFIED:20180213T144525Z
TRANSP:OPAQUE
END:VEVENT
* Miracle @ Marauders
<2018-04-21 Sat 17:30-20:30>
:PROPERTIES:
:ID:       sxmQMxWeRgfE1pjBbApvdgQ_@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Miracle @ Marauders Miracle @ Marauders

Follow on MiLB First Pitch  https //stza.co/+vMr0-v

Shop  https //stza.co/+vMr0-c

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Miracle @ Marauders
END:VALARM
DTSTART:20180421T223000Z
DTEND:20180422T013000Z
UID:sxmQMxWeRgfE1pjBbApvdgQ_@stanza.co
SUMMARY:Miracle @ Marauders
DESCRIPTION:Miracle @ Marauders\n\nFollow on MiLB First Pitch: https://stza.co/+vMr0-v\n\nShop: https://stza.co/+vMr0-c\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144525Z
LAST-MODIFIED:20180213T144525Z
TRANSP:OPAQUE
END:VEVENT
* Miracle @ Marauders
<2018-04-22 Sun 12:00-15:00>
:PROPERTIES:
:ID:       zYE2MeuRzGqWP16z_xpWwzoN@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Miracle @ Marauders Miracle @ Marauders

Follow on MiLB First Pitch  https //stza.co/+vMr1-3K

Shop  https //stza.co/+vMr1-_

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Miracle @ Marauders
END:VALARM
DTSTART:20180422T170000Z
DTEND:20180422T200000Z
UID:zYE2MeuRzGqWP16z_xpWwzoN@stanza.co
SUMMARY:Miracle @ Marauders
DESCRIPTION:Miracle @ Marauders\n\nFollow on MiLB First Pitch: https://stza.co/+vMr1-3K\n\nShop: https://stza.co/+vMr1-_\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144525Z
LAST-MODIFIED:20180213T144525Z
TRANSP:OPAQUE
END:VEVENT
* Miracle @ Threshers
<2018-04-23 Mon 18:00-21:00>
:PROPERTIES:
:ID:       jegw3bRIRUJTUHYvFP00524P@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Miracle @ Threshers Miracle @ Threshers

Follow on MiLB First Pitch  https //stza.co/+xBeq-m

Shop  https //stza.co/+xBeq-13

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Miracle @ Threshers
END:VALARM
DTSTART:20180423T230000Z
DTEND:20180424T020000Z
UID:jegw3bRIRUJTUHYvFP00524P@stanza.co
SUMMARY:Miracle @ Threshers
DESCRIPTION:Miracle @ Threshers\n\nFollow on MiLB First Pitch: https://stza.co/+xBeq-m\n\nShop: https://stza.co/+xBeq-13\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144525Z
LAST-MODIFIED:20180213T144525Z
TRANSP:OPAQUE
END:VEVENT
* Miracle @ Threshers
<2018-04-24 Tue 18:00-21:00>
:PROPERTIES:
:ID:       DJiKf0CdPXkR0-_jsNswqz4J@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Miracle @ Threshers Miracle @ Threshers

Follow on MiLB First Pitch  https //stza.co/+xBer-15

Shop  https //stza.co/+xBer-25

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Miracle @ Threshers
END:VALARM
DTSTART:20180424T230000Z
DTEND:20180425T020000Z
UID:DJiKf0CdPXkR0-_jsNswqz4J@stanza.co
SUMMARY:Miracle @ Threshers
DESCRIPTION:Miracle @ Threshers\n\nFollow on MiLB First Pitch: https://stza.co/+xBer-15\n\nShop: https://stza.co/+xBer-25\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144525Z
LAST-MODIFIED:20180213T144525Z
TRANSP:OPAQUE
END:VEVENT
* Miracle @ Threshers
<2018-04-25 Wed 11:00-14:00>
:PROPERTIES:
:ID:       NndEAlDGXmRvY5vn2u21jHeg@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Miracle @ Threshers Miracle @ Threshers

Follow on MiLB First Pitch  https //stza.co/+xBes-2b

Shop  https //stza.co/+xBes-3K

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Miracle @ Threshers
END:VALARM
DTSTART:20180425T160000Z
DTEND:20180425T190000Z
UID:NndEAlDGXmRvY5vn2u21jHeg@stanza.co
SUMMARY:Miracle @ Threshers
DESCRIPTION:Miracle @ Threshers\n\nFollow on MiLB First Pitch: https://stza.co/+xBes-2b\n\nShop: https://stza.co/+xBes-3K\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144525Z
LAST-MODIFIED:20180213T144525Z
TRANSP:OPAQUE
END:VEVENT
* Miracle vs. Tortugas
<2018-04-26 Thu 18:00-21:00>
:PROPERTIES:
:ID:       H3rRCXzJP-X3H4KAdeJ3mePg@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Miracle vs. Tortugas Miracle vs. Tortugas

Follow on MiLB First Pitch  https //stza.co/+xMb6-2C

Shop  https //stza.co/+xMb6-1U

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Miracle vs. Tortugas
END:VALARM
DTSTART:20180426T230000Z
DTEND:20180427T020000Z
UID:H3rRCXzJP-X3H4KAdeJ3mePg@stanza.co
SUMMARY:Miracle vs. Tortugas
DESCRIPTION:Miracle vs. Tortugas\n\nFollow on MiLB First Pitch: https://stza.co/+xMb6-2C\n\nShop: https://stza.co/+xMb6-1U\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144525Z
LAST-MODIFIED:20180213T144525Z
TRANSP:OPAQUE
END:VEVENT
* Miracle vs. Tortugas
<2018-04-27 Fri 18:00-21:00>
:PROPERTIES:
:ID:       H2n9mXz3NnKqsnipKBeoJ2Xw@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Miracle vs. Tortugas Miracle vs. Tortugas

Follow on MiLB First Pitch  https //stza.co/+xMb8-3a

Shop  https //stza.co/+xMb8-36

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Miracle vs. Tortugas
END:VALARM
DTSTART:20180427T230000Z
DTEND:20180428T020000Z
UID:H2n9mXz3NnKqsnipKBeoJ2Xw@stanza.co
SUMMARY:Miracle vs. Tortugas
DESCRIPTION:Miracle vs. Tortugas\n\nFollow on MiLB First Pitch: https://stza.co/+xMb8-3a\n\nShop: https://stza.co/+xMb8-36\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144525Z
LAST-MODIFIED:20180213T144525Z
TRANSP:OPAQUE
END:VEVENT
* Miracle vs. Tortugas
<2018-04-28 Sat 17:00-20:00>
:PROPERTIES:
:ID:       CXODFUN9GsEAgPBcgYaun3rf@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Miracle vs. Tortugas Miracle vs. Tortugas

Follow on MiLB First Pitch  https //stza.co/+xMba-2Q

Shop  https //stza.co/+xMba-V

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Miracle vs. Tortugas
END:VALARM
DTSTART:20180428T220000Z
DTEND:20180429T010000Z
UID:CXODFUN9GsEAgPBcgYaun3rf@stanza.co
SUMMARY:Miracle vs. Tortugas
DESCRIPTION:Miracle vs. Tortugas\n\nFollow on MiLB First Pitch: https://stza.co/+xMba-2Q\n\nShop: https://stza.co/+xMba-V\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144525Z
LAST-MODIFIED:20180213T144525Z
TRANSP:OPAQUE
END:VEVENT
* Miracle vs. Tortugas
<2018-04-29 Sun 15:00-18:00>
:PROPERTIES:
:ID:       XSzPhnCh2CNECc_YG40k08L5@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Miracle vs. Tortugas Miracle vs. Tortugas

Follow on MiLB First Pitch  https //stza.co/+xMbd-2n

Shop  https //stza.co/+xMbd-1K

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Miracle vs. Tortugas
END:VALARM
DTSTART:20180429T200000Z
DTEND:20180429T230000Z
UID:XSzPhnCh2CNECc_YG40k08L5@stanza.co
SUMMARY:Miracle vs. Tortugas
DESCRIPTION:Miracle vs. Tortugas\n\nFollow on MiLB First Pitch: https://stza.co/+xMbd-2n\n\nShop: https://stza.co/+xMbd-1K\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144525Z
LAST-MODIFIED:20180213T144525Z
TRANSP:OPAQUE
END:VEVENT
* Miracle @ Tarpons
<2018-05-01 Tue>--<2018-04-30 Mon>
:PROPERTIES:
:ID:       jX5AVEPa369GodKx8bGn4l46@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Miracle @ Tarpons Miracle @ Tarpons

Follow on MiLB First Pitch  https //stza.co/+vMub-2T

Shop  https //stza.co/+vMub-q

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Miracle @ Tarpons
END:VALARM
DTSTART;VALUE=DATE:20180501
DTEND;VALUE=DATE:20180501
UID:jX5AVEPa369GodKx8bGn4l46@stanza.co
SUMMARY:Miracle @ Tarpons
DESCRIPTION:Miracle @ Tarpons\n\nFollow on MiLB First Pitch: https://stza.co/+vMub-2T\n\nShop: https://stza.co/+vMub-q\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144525Z
LAST-MODIFIED:20180213T144525Z
TRANSP:OPAQUE
END:VEVENT
* Miracle @ Tarpons
<2018-05-02 Wed>--<2018-05-01 Tue>
:PROPERTIES:
:ID:       nSzrAz28GdnvRCxGFG0h3L5T@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Miracle @ Tarpons Miracle @ Tarpons

Follow on MiLB First Pitch  https //stza.co/+vkLu-9

Shop  https //stza.co/+vkLu-1F

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Miracle @ Tarpons
END:VALARM
DTSTART;VALUE=DATE:20180502
DTEND;VALUE=DATE:20180502
UID:nSzrAz28GdnvRCxGFG0h3L5T@stanza.co
SUMMARY:Miracle @ Tarpons
DESCRIPTION:Miracle @ Tarpons\n\nFollow on MiLB First Pitch: https://stza.co/+vkLu-9\n\nShop: https://stza.co/+vkLu-1F\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144525Z
LAST-MODIFIED:20180213T144525Z
TRANSP:OPAQUE
END:VEVENT
* Miracle @ Tarpons
<2018-05-03 Thu>--<2018-05-02 Wed>
:PROPERTIES:
:ID:       4yK5K7TgbUErqQW76AqDsmO7@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Miracle @ Tarpons Miracle @ Tarpons

Follow on MiLB First Pitch  https //stza.co/+vkLA-3A

Shop  https //stza.co/+vkLA-u

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Miracle @ Tarpons
END:VALARM
DTSTART;VALUE=DATE:20180503
DTEND;VALUE=DATE:20180503
UID:4yK5K7TgbUErqQW76AqDsmO7@stanza.co
SUMMARY:Miracle @ Tarpons
DESCRIPTION:Miracle @ Tarpons\n\nFollow on MiLB First Pitch: https://stza.co/+vkLA-3A\n\nShop: https://stza.co/+vkLA-u\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144525Z
LAST-MODIFIED:20180213T144525Z
TRANSP:OPAQUE
END:VEVENT
* Miracle vs. Hammerheads
<2018-05-04 Fri 18:00-21:00>
:PROPERTIES:
:ID:       mHI_GDEGjDX50sxWIP8_u1uP@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Miracle vs. Hammerheads Miracle vs. Hammerheads

Follow on MiLB First Pitch  https //stza.co/+xMbf-2r

Shop  https //stza.co/+xMbf-19

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Miracle vs. Hammerheads
END:VALARM
DTSTART:20180504T230000Z
DTEND:20180505T020000Z
UID:mHI_GDEGjDX50sxWIP8_u1uP@stanza.co
SUMMARY:Miracle vs. Hammerheads
DESCRIPTION:Miracle vs. Hammerheads\n\nFollow on MiLB First Pitch: https://stza.co/+xMbf-2r\n\nShop: https://stza.co/+xMbf-19\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144525Z
LAST-MODIFIED:20180213T144525Z
TRANSP:OPAQUE
END:VEVENT
* Miracle vs. Hammerheads
<2018-05-05 Sat 17:00-20:00>
:PROPERTIES:
:ID:       vDgAU7Vj8ctVKSCOt7sc02EB@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Miracle vs. Hammerheads Miracle vs. Hammerheads

Follow on MiLB First Pitch  https //stza.co/+xMbh-3G

Shop  https //stza.co/+xMbh-3d

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Miracle vs. Hammerheads
END:VALARM
DTSTART:20180505T220000Z
DTEND:20180506T010000Z
UID:vDgAU7Vj8ctVKSCOt7sc02EB@stanza.co
SUMMARY:Miracle vs. Hammerheads
DESCRIPTION:Miracle vs. Hammerheads\n\nFollow on MiLB First Pitch: https://stza.co/+xMbh-3G\n\nShop: https://stza.co/+xMbh-3d\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144525Z
LAST-MODIFIED:20180213T144525Z
TRANSP:OPAQUE
END:VEVENT
* Miracle vs. Hammerheads
<2018-05-06 Sun 15:00-18:00>
:PROPERTIES:
:ID:       ObvWb7m4IYLECb7uRq9x5mPh@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Miracle vs. Hammerheads Miracle vs. Hammerheads

Follow on MiLB First Pitch  https //stza.co/+xMbj-3P

Shop  https //stza.co/+xMbj-1$

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Miracle vs. Hammerheads
END:VALARM
DTSTART:20180506T200000Z
DTEND:20180506T230000Z
UID:ObvWb7m4IYLECb7uRq9x5mPh@stanza.co
SUMMARY:Miracle vs. Hammerheads
DESCRIPTION:Miracle vs. Hammerheads\n\nFollow on MiLB First Pitch: https://stza.co/+xMbj-3P\n\nShop: https://stza.co/+xMbj-1$\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144525Z
LAST-MODIFIED:20180213T144525Z
TRANSP:OPAQUE
END:VEVENT
* Miracle vs. Stone Crabs
<2018-05-07 Mon 18:00-21:00>
:PROPERTIES:
:ID:       sYOYm1H3trG2nByZzeTeTXDY@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Miracle vs. Stone Crabs Miracle vs. Stone Crabs

Follow on MiLB First Pitch  https //stza.co/+xMbl-2Y

Shop  https //stza.co/+xMbl-1R

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Miracle vs. Stone Crabs
END:VALARM
DTSTART:20180507T230000Z
DTEND:20180508T020000Z
UID:sYOYm1H3trG2nByZzeTeTXDY@stanza.co
SUMMARY:Miracle vs. Stone Crabs
DESCRIPTION:Miracle vs. Stone Crabs\n\nFollow on MiLB First Pitch: https://stza.co/+xMbl-2Y\n\nShop: https://stza.co/+xMbl-1R\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144525Z
LAST-MODIFIED:20180213T144525Z
TRANSP:OPAQUE
END:VEVENT
* Miracle vs. Stone Crabs
<2018-05-08 Tue 18:00-21:00>
:PROPERTIES:
:ID:       Er6GbiqA4NRkk7kkCq_XZ7ZL@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Miracle vs. Stone Crabs Miracle vs. Stone Crabs

Follow on MiLB First Pitch  https //stza.co/+xMbn-3d

Shop  https //stza.co/+xMbn-T

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Miracle vs. Stone Crabs
END:VALARM
DTSTART:20180508T230000Z
DTEND:20180509T020000Z
UID:Er6GbiqA4NRkk7kkCq_XZ7ZL@stanza.co
SUMMARY:Miracle vs. Stone Crabs
DESCRIPTION:Miracle vs. Stone Crabs\n\nFollow on MiLB First Pitch: https://stza.co/+xMbn-3d\n\nShop: https://stza.co/+xMbn-T\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144525Z
LAST-MODIFIED:20180213T144525Z
TRANSP:OPAQUE
END:VEVENT
* Miracle vs. Stone Crabs
<2018-05-09 Wed 18:00-21:00>
:PROPERTIES:
:ID:       CxU_NvwwNfs1u44nHyMaxVls@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Miracle vs. Stone Crabs Miracle vs. Stone Crabs

Follow on MiLB First Pitch  https //stza.co/+xMbp-3a

Shop  https //stza.co/+xMbp-1A

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Miracle vs. Stone Crabs
END:VALARM
DTSTART:20180509T230000Z
DTEND:20180510T020000Z
UID:CxU_NvwwNfs1u44nHyMaxVls@stanza.co
SUMMARY:Miracle vs. Stone Crabs
DESCRIPTION:Miracle vs. Stone Crabs\n\nFollow on MiLB First Pitch: https://stza.co/+xMbp-3a\n\nShop: https://stza.co/+xMbp-1A\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144525Z
LAST-MODIFIED:20180213T144525Z
TRANSP:OPAQUE
END:VEVENT
* Miracle @ Blue Jays
<2018-05-10 Thu 17:30-20:30>
:PROPERTIES:
:ID:       bYQPzVHxGKOb69mpSyBFDWr4@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Miracle @ Blue Jays Miracle @ Blue Jays

Follow on MiLB First Pitch  https //stza.co/+y0Jy-3Z

Shop  https //stza.co/+y0Jy-19

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Miracle @ Blue Jays
END:VALARM
DTSTART:20180510T223000Z
DTEND:20180511T013000Z
UID:bYQPzVHxGKOb69mpSyBFDWr4@stanza.co
SUMMARY:Miracle @ Blue Jays
DESCRIPTION:Miracle @ Blue Jays\n\nFollow on MiLB First Pitch: https://stza.co/+y0Jy-3Z\n\nShop: https://stza.co/+y0Jy-19\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144525Z
LAST-MODIFIED:20180213T144525Z
TRANSP:OPAQUE
END:VEVENT
* Miracle @ Blue Jays
<2018-05-11 Fri 17:30-20:30>
:PROPERTIES:
:ID:       aMqBNg1j3T5M-AaqpBS174sJ@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Miracle @ Blue Jays Miracle @ Blue Jays

Follow on MiLB First Pitch  https //stza.co/+y0Jz-1B

Shop  https //stza.co/+y0Jz-c

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Miracle @ Blue Jays
END:VALARM
DTSTART:20180511T223000Z
DTEND:20180512T013000Z
UID:aMqBNg1j3T5M-AaqpBS174sJ@stanza.co
SUMMARY:Miracle @ Blue Jays
DESCRIPTION:Miracle @ Blue Jays\n\nFollow on MiLB First Pitch: https://stza.co/+y0Jz-1B\n\nShop: https://stza.co/+y0Jz-c\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144525Z
LAST-MODIFIED:20180213T144525Z
TRANSP:OPAQUE
END:VEVENT
* Miracle @ Blue Jays
<2018-05-12 Sat 17:30-20:30>
:PROPERTIES:
:ID:       SrPt1ya-p_k65glPnTQxbz-E@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Miracle @ Blue Jays Miracle @ Blue Jays

Follow on MiLB First Pitch  https //stza.co/+y0JA-3b

Shop  https //stza.co/+y0JA-1m

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Miracle @ Blue Jays
END:VALARM
DTSTART:20180512T223000Z
DTEND:20180513T013000Z
UID:SrPt1ya-p_k65glPnTQxbz-E@stanza.co
SUMMARY:Miracle @ Blue Jays
DESCRIPTION:Miracle @ Blue Jays\n\nFollow on MiLB First Pitch: https://stza.co/+y0JA-3b\n\nShop: https://stza.co/+y0JA-1m\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144525Z
LAST-MODIFIED:20180213T144525Z
TRANSP:OPAQUE
END:VEVENT
* Miracle @ Hammerheads
<2018-05-14 Mon>--<2018-05-13 Sun>
:PROPERTIES:
:ID:       Fs4OiuS39QKyyvFD2fNDW6JZ@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Miracle @ Hammerheads Miracle @ Hammerheads

Buy tickets here  https //stza.co/~vMtN

Follow on MiLB First Pitch  https //stza.co/+vMtN-K

Shop  https //stza.co/+vMtN-Y

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Miracle @ Hammerheads
END:VALARM
DTSTART;VALUE=DATE:20180514
DTEND;VALUE=DATE:20180514
UID:Fs4OiuS39QKyyvFD2fNDW6JZ@stanza.co
SUMMARY:Miracle @ Hammerheads
DESCRIPTION:Miracle @ Hammerheads\n\nBuy tickets here: https://stza.co/~vMtN\n\nFollow on MiLB First Pitch: https://stza.co/+vMtN-K\n\nShop: https://stza.co/+vMtN-Y\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144525Z
LAST-MODIFIED:20180213T144525Z
TRANSP:OPAQUE
END:VEVENT
* Miracle @ Hammerheads
<2018-05-15 Tue>--<2018-05-14 Mon>
:PROPERTIES:
:ID:       gYywKTscX3N1ZuFehHroVNKA@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Miracle @ Hammerheads Miracle @ Hammerheads

Buy tickets here  https //stza.co/~vMtO

Follow on MiLB First Pitch  https //stza.co/+vMtO-2f

Shop  https //stza.co/+vMtO-2E

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Miracle @ Hammerheads
END:VALARM
DTSTART;VALUE=DATE:20180515
DTEND;VALUE=DATE:20180515
UID:gYywKTscX3N1ZuFehHroVNKA@stanza.co
SUMMARY:Miracle @ Hammerheads
DESCRIPTION:Miracle @ Hammerheads\n\nBuy tickets here: https://stza.co/~vMtO\n\nFollow on MiLB First Pitch: https://stza.co/+vMtO-2f\n\nShop: https://stza.co/+vMtO-2E\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144525Z
LAST-MODIFIED:20180213T144525Z
TRANSP:OPAQUE
END:VEVENT
* Miracle @ Hammerheads
<2018-05-16 Wed>--<2018-05-15 Tue>
:PROPERTIES:
:ID:       oH4FHmGh5yW1KckTSYkxIqAF@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Miracle @ Hammerheads Miracle @ Hammerheads

Buy tickets here  https //stza.co/~vMtP

Follow on MiLB First Pitch  https //stza.co/+vMtP-2T

Shop  https //stza.co/+vMtP-I

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Miracle @ Hammerheads
END:VALARM
DTSTART;VALUE=DATE:20180516
DTEND;VALUE=DATE:20180516
UID:oH4FHmGh5yW1KckTSYkxIqAF@stanza.co
SUMMARY:Miracle @ Hammerheads
DESCRIPTION:Miracle @ Hammerheads\n\nBuy tickets here: https://stza.co/~vMtP\n\nFollow on MiLB First Pitch: https://stza.co/+vMtP-2T\n\nShop: https://stza.co/+vMtP-I\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144525Z
LAST-MODIFIED:20180213T144525Z
TRANSP:OPAQUE
END:VEVENT
* Miracle @ Hammerheads
<2018-05-17 Thu>--<2018-05-16 Wed>
:PROPERTIES:
:ID:       r4cMHKwEs_ycCgzQeGxEmeNA@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Miracle @ Hammerheads Miracle @ Hammerheads

Buy tickets here  https //stza.co/~vMtQ

Follow on MiLB First Pitch  https //stza.co/+vMtQ-1p

Shop  https //stza.co/+vMtQ-2N

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Miracle @ Hammerheads
END:VALARM
DTSTART;VALUE=DATE:20180517
DTEND;VALUE=DATE:20180517
UID:r4cMHKwEs_ycCgzQeGxEmeNA@stanza.co
SUMMARY:Miracle @ Hammerheads
DESCRIPTION:Miracle @ Hammerheads\n\nBuy tickets here: https://stza.co/~vMtQ\n\nFollow on MiLB First Pitch: https://stza.co/+vMtQ-1p\n\nShop: https://stza.co/+vMtQ-2N\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144525Z
LAST-MODIFIED:20180213T144525Z
TRANSP:OPAQUE
END:VEVENT
* Miracle vs. Mets
<2018-05-18 Fri 18:00-21:00>
:PROPERTIES:
:ID:       rXS_Xp-NVuSKPRZGhnH9Qu8M@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Miracle vs. Mets Miracle vs. Mets

Follow on MiLB First Pitch  https //stza.co/+xMbq-1H

Shop  https //stza.co/+xMbq-7

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Miracle vs. Mets
END:VALARM
DTSTART:20180518T230000Z
DTEND:20180519T020000Z
UID:rXS_Xp-NVuSKPRZGhnH9Qu8M@stanza.co
SUMMARY:Miracle vs. Mets
DESCRIPTION:Miracle vs. Mets\n\nFollow on MiLB First Pitch: https://stza.co/+xMbq-1H\n\nShop: https://stza.co/+xMbq-7\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144525Z
LAST-MODIFIED:20180213T144525Z
TRANSP:OPAQUE
END:VEVENT
* Miracle vs. Mets
<2018-05-19 Sat 17:00-20:00>
:PROPERTIES:
:ID:       MV-Pf42lr4XIBdW-QyJWVNnV@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Miracle vs. Mets Miracle vs. Mets

Follow on MiLB First Pitch  https //stza.co/+xMbt-2L

Shop  https //stza.co/+xMbt-e

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Miracle vs. Mets
END:VALARM
DTSTART:20180519T220000Z
DTEND:20180520T010000Z
UID:MV-Pf42lr4XIBdW-QyJWVNnV@stanza.co
SUMMARY:Miracle vs. Mets
DESCRIPTION:Miracle vs. Mets\n\nFollow on MiLB First Pitch: https://stza.co/+xMbt-2L\n\nShop: https://stza.co/+xMbt-e\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144525Z
LAST-MODIFIED:20180213T144525Z
TRANSP:OPAQUE
END:VEVENT
* Miracle vs. Mets
<2018-05-20 Sun 15:00-18:00>
:PROPERTIES:
:ID:       YAlKa21AptaaUurJf2ymTXan@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Miracle vs. Mets Miracle vs. Mets

Follow on MiLB First Pitch  https //stza.co/+xMbv-l

Shop  https //stza.co/+xMbv-3H

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Miracle vs. Mets
END:VALARM
DTSTART:20180520T200000Z
DTEND:20180520T230000Z
UID:YAlKa21AptaaUurJf2ymTXan@stanza.co
SUMMARY:Miracle vs. Mets
DESCRIPTION:Miracle vs. Mets\n\nFollow on MiLB First Pitch: https://stza.co/+xMbv-l\n\nShop: https://stza.co/+xMbv-3H\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144525Z
LAST-MODIFIED:20180213T144525Z
TRANSP:OPAQUE
END:VEVENT
* Miracle vs. Marauders
<2018-05-21 Mon 18:00-21:00>
:PROPERTIES:
:ID:       WZenKbzp3C1-VAI48OUZ217A@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Miracle vs. Marauders Miracle vs. Marauders

Follow on MiLB First Pitch  https //stza.co/+xMbx-2A

Shop  https //stza.co/+xMbx-32

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Miracle vs. Marauders
END:VALARM
DTSTART:20180521T230000Z
DTEND:20180522T020000Z
UID:WZenKbzp3C1-VAI48OUZ217A@stanza.co
SUMMARY:Miracle vs. Marauders
DESCRIPTION:Miracle vs. Marauders\n\nFollow on MiLB First Pitch: https://stza.co/+xMbx-2A\n\nShop: https://stza.co/+xMbx-32\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144525Z
LAST-MODIFIED:20180213T144525Z
TRANSP:OPAQUE
END:VEVENT
* Miracle vs. Marauders
<2018-05-22 Tue 10:00-13:00>
:PROPERTIES:
:ID:       aw-FUZv2KwoGX4YDAPuVf9tl@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Miracle vs. Marauders Miracle vs. Marauders

Follow on MiLB First Pitch  https //stza.co/+xMbz-25

Shop  https //stza.co/+xMbz-$

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Miracle vs. Marauders
END:VALARM
DTSTART:20180522T150000Z
DTEND:20180522T180000Z
UID:aw-FUZv2KwoGX4YDAPuVf9tl@stanza.co
SUMMARY:Miracle vs. Marauders
DESCRIPTION:Miracle vs. Marauders\n\nFollow on MiLB First Pitch: https://stza.co/+xMbz-25\n\nShop: https://stza.co/+xMbz-$\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144525Z
LAST-MODIFIED:20180213T144525Z
TRANSP:OPAQUE
END:VEVENT
* Miracle vs. Marauders
<2018-05-23 Wed 11:00-14:00>
:PROPERTIES:
:ID:       Ep-HNsv4CScsso4P1JVLw3wj@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Miracle vs. Marauders Miracle vs. Marauders

Follow on MiLB First Pitch  https //stza.co/+xMbA-8

Shop  https //stza.co/+xMbA-a

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Miracle vs. Marauders
END:VALARM
DTSTART:20180523T160000Z
DTEND:20180523T190000Z
UID:Ep-HNsv4CScsso4P1JVLw3wj@stanza.co
SUMMARY:Miracle vs. Marauders
DESCRIPTION:Miracle vs. Marauders\n\nFollow on MiLB First Pitch: https://stza.co/+xMbA-8\n\nShop: https://stza.co/+xMbA-a\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144525Z
LAST-MODIFIED:20180213T144525Z
TRANSP:OPAQUE
END:VEVENT
* Miracle @ Stone Crabs
<2018-05-24 Thu 17:35-20:35>
:PROPERTIES:
:ID:       c7lxeCK5snLGdEPvumFnwF_J@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Miracle @ Stone Crabs Miracle @ Stone Crabs

Follow on MiLB First Pitch  https //stza.co/+wYo9-o

Shop  https //stza.co/+wYo9-w

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Miracle @ Stone Crabs
END:VALARM
DTSTART:20180524T223500Z
DTEND:20180525T013500Z
UID:c7lxeCK5snLGdEPvumFnwF_J@stanza.co
SUMMARY:Miracle @ Stone Crabs
DESCRIPTION:Miracle @ Stone Crabs\n\nFollow on MiLB First Pitch: https://stza.co/+wYo9-o\n\nShop: https://stza.co/+wYo9-w\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144525Z
LAST-MODIFIED:20180213T144525Z
TRANSP:OPAQUE
END:VEVENT
* Miracle @ Stone Crabs
<2018-05-25 Fri 17:35-20:35>
:PROPERTIES:
:ID:       TSt51cfleDuyrLnBp4sdvNhC@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Miracle @ Stone Crabs Miracle @ Stone Crabs

Follow on MiLB First Pitch  https //stza.co/+wYoa-23

Shop  https //stza.co/+wYoa-1i

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Miracle @ Stone Crabs
END:VALARM
DTSTART:20180525T223500Z
DTEND:20180526T013500Z
UID:TSt51cfleDuyrLnBp4sdvNhC@stanza.co
SUMMARY:Miracle @ Stone Crabs
DESCRIPTION:Miracle @ Stone Crabs\n\nFollow on MiLB First Pitch: https://stza.co/+wYoa-23\n\nShop: https://stza.co/+wYoa-1i\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144525Z
LAST-MODIFIED:20180213T144525Z
TRANSP:OPAQUE
END:VEVENT
* Miracle @ Stone Crabs
<2018-05-26 Sat 17:05-20:05>
:PROPERTIES:
:ID:       cyjdCtmLJv18-ClZ0OIMU4yh@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Miracle @ Stone Crabs Miracle @ Stone Crabs

Follow on MiLB First Pitch  https //stza.co/+wYob-1q

Shop  https //stza.co/+wYob-$

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Miracle @ Stone Crabs
END:VALARM
DTSTART:20180526T220500Z
DTEND:20180527T010500Z
UID:cyjdCtmLJv18-ClZ0OIMU4yh@stanza.co
SUMMARY:Miracle @ Stone Crabs
DESCRIPTION:Miracle @ Stone Crabs\n\nFollow on MiLB First Pitch: https://stza.co/+wYob-1q\n\nShop: https://stza.co/+wYob-$\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144525Z
LAST-MODIFIED:20180213T144525Z
TRANSP:OPAQUE
END:VEVENT
* Miracle @ Stone Crabs
<2018-05-27 Sun 11:35-14:35>
:PROPERTIES:
:ID:       MXEr9ok1O-L1UoHDOem8sYO5@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Miracle @ Stone Crabs Miracle @ Stone Crabs

Follow on MiLB First Pitch  https //stza.co/+wYoc-3m

Shop  https //stza.co/+wYoc-20

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Miracle @ Stone Crabs
END:VALARM
DTSTART:20180527T163500Z
DTEND:20180527T193500Z
UID:MXEr9ok1O-L1UoHDOem8sYO5@stanza.co
SUMMARY:Miracle @ Stone Crabs
DESCRIPTION:Miracle @ Stone Crabs\n\nFollow on MiLB First Pitch: https://stza.co/+wYoc-3m\n\nShop: https://stza.co/+wYoc-20\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144525Z
LAST-MODIFIED:20180213T144525Z
TRANSP:OPAQUE
END:VEVENT
* Miracle @ Threshers
<2018-05-29 Tue 18:00-21:00>
:PROPERTIES:
:ID:       0aVFbJGLhbQnpJlesDRG5FH7@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Miracle @ Threshers Miracle @ Threshers

Follow on MiLB First Pitch  https //stza.co/+xBet-S

Shop  https //stza.co/+xBet-i

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Miracle @ Threshers
END:VALARM
DTSTART:20180529T230000Z
DTEND:20180530T020000Z
UID:0aVFbJGLhbQnpJlesDRG5FH7@stanza.co
SUMMARY:Miracle @ Threshers
DESCRIPTION:Miracle @ Threshers\n\nFollow on MiLB First Pitch: https://stza.co/+xBet-S\n\nShop: https://stza.co/+xBet-i\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144525Z
LAST-MODIFIED:20180213T144525Z
TRANSP:OPAQUE
END:VEVENT
* Miracle @ Threshers
<2018-05-30 Wed 11:00-14:00>
:PROPERTIES:
:ID:       NPo-FrQeMVj-LNCDLPw9gKGa@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Miracle @ Threshers Miracle @ Threshers

Follow on MiLB First Pitch  https //stza.co/+xBeu-2R

Shop  https //stza.co/+xBeu-2I

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Miracle @ Threshers
END:VALARM
DTSTART:20180530T160000Z
DTEND:20180530T190000Z
UID:NPo-FrQeMVj-LNCDLPw9gKGa@stanza.co
SUMMARY:Miracle @ Threshers
DESCRIPTION:Miracle @ Threshers\n\nFollow on MiLB First Pitch: https://stza.co/+xBeu-2R\n\nShop: https://stza.co/+xBeu-2I\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144525Z
LAST-MODIFIED:20180213T144525Z
TRANSP:OPAQUE
END:VEVENT
* Miracle @ Threshers
<2018-05-31 Thu 18:00-21:00>
:PROPERTIES:
:ID:       aX7XR_mfVhyLUKkAn5c4wH0z@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Miracle @ Threshers Miracle @ Threshers

Follow on MiLB First Pitch  https //stza.co/+xBev-1l

Shop  https //stza.co/+xBev-2_

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Miracle @ Threshers
END:VALARM
DTSTART:20180531T230000Z
DTEND:20180601T020000Z
UID:aX7XR_mfVhyLUKkAn5c4wH0z@stanza.co
SUMMARY:Miracle @ Threshers
DESCRIPTION:Miracle @ Threshers\n\nFollow on MiLB First Pitch: https://stza.co/+xBev-1l\n\nShop: https://stza.co/+xBev-2_\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144525Z
LAST-MODIFIED:20180213T144525Z
TRANSP:OPAQUE
END:VEVENT
* Miracle @ Mets
<2018-06-01 Fri 17:30-20:30>
:PROPERTIES:
:ID:       dGK9tXaEc2TgFnuA0aoKWOmK@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Miracle @ Mets Miracle @ Mets

Follow on MiLB First Pitch  https //stza.co/+vMu5-2X

Shop  https //stza.co/+vMu5-2u

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Miracle @ Mets
END:VALARM
DTSTART:20180601T223000Z
DTEND:20180602T013000Z
UID:dGK9tXaEc2TgFnuA0aoKWOmK@stanza.co
SUMMARY:Miracle @ Mets
DESCRIPTION:Miracle @ Mets\n\nFollow on MiLB First Pitch: https://stza.co/+vMu5-2X\n\nShop: https://stza.co/+vMu5-2u\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144525Z
LAST-MODIFIED:20180213T144525Z
TRANSP:OPAQUE
END:VEVENT
* Miracle @ Mets
<2018-06-02 Sat 17:30-20:30>
:PROPERTIES:
:ID:       6bqpxWdcyTZCHp0S9rxklawa@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Miracle @ Mets Miracle @ Mets

Follow on MiLB First Pitch  https //stza.co/+vMu6-2P

Shop  https //stza.co/+vMu6-2i

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Miracle @ Mets
END:VALARM
DTSTART:20180602T223000Z
DTEND:20180603T013000Z
UID:6bqpxWdcyTZCHp0S9rxklawa@stanza.co
SUMMARY:Miracle @ Mets
DESCRIPTION:Miracle @ Mets\n\nFollow on MiLB First Pitch: https://stza.co/+vMu6-2P\n\nShop: https://stza.co/+vMu6-2i\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144525Z
LAST-MODIFIED:20180213T144525Z
TRANSP:OPAQUE
END:VEVENT
* Miracle @ Mets
<2018-06-03 Sun 11:00-14:00>
:PROPERTIES:
:ID:       EFtSyqeBb9c4nBqeB8eQUIQd@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Miracle @ Mets Miracle @ Mets

Follow on MiLB First Pitch  https //stza.co/+vMu7-1t

Shop  https //stza.co/+vMu7-2h

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Miracle @ Mets
END:VALARM
DTSTART:20180603T160000Z
DTEND:20180603T190000Z
UID:EFtSyqeBb9c4nBqeB8eQUIQd@stanza.co
SUMMARY:Miracle @ Mets
DESCRIPTION:Miracle @ Mets\n\nFollow on MiLB First Pitch: https://stza.co/+vMu7-1t\n\nShop: https://stza.co/+vMu7-2h\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144525Z
LAST-MODIFIED:20180213T144525Z
TRANSP:OPAQUE
END:VEVENT
* Miracle vs. Cardinals
<2018-06-04 Mon 18:00-21:00>
:PROPERTIES:
:ID:       osD4jMaYA5PE_PolTgFK3kN7@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Miracle vs. Cardinals Miracle vs. Cardinals

Follow on MiLB First Pitch  https //stza.co/+xMbD-3E

Shop  https //stza.co/+xMbD-1F

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Miracle vs. Cardinals
END:VALARM
DTSTART:20180604T230000Z
DTEND:20180605T020000Z
UID:osD4jMaYA5PE_PolTgFK3kN7@stanza.co
SUMMARY:Miracle vs. Cardinals
DESCRIPTION:Miracle vs. Cardinals\n\nFollow on MiLB First Pitch: https://stza.co/+xMbD-3E\n\nShop: https://stza.co/+xMbD-1F\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144525Z
LAST-MODIFIED:20180213T144525Z
TRANSP:OPAQUE
END:VEVENT
* Miracle vs. Cardinals
<2018-06-05 Tue 18:00-21:00>
:PROPERTIES:
:ID:       xW34BA8n1V2q0eQq_82NipY1@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Miracle vs. Cardinals Miracle vs. Cardinals

Follow on MiLB First Pitch  https //stza.co/+xMbG-3h

Shop  https //stza.co/+xMbG-15

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Miracle vs. Cardinals
END:VALARM
DTSTART:20180605T230000Z
DTEND:20180606T020000Z
UID:xW34BA8n1V2q0eQq_82NipY1@stanza.co
SUMMARY:Miracle vs. Cardinals
DESCRIPTION:Miracle vs. Cardinals\n\nFollow on MiLB First Pitch: https://stza.co/+xMbG-3h\n\nShop: https://stza.co/+xMbG-15\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144525Z
LAST-MODIFIED:20180213T144525Z
TRANSP:OPAQUE
END:VEVENT
* Miracle vs. Cardinals
<2018-06-06 Wed 18:00-21:00>
:PROPERTIES:
:ID:       VHmfBCBcqFtBvIG4nfBAFkyY@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Miracle vs. Cardinals Miracle vs. Cardinals

Follow on MiLB First Pitch  https //stza.co/+xMbH-3m

Shop  https //stza.co/+xMbH-2a

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Miracle vs. Cardinals
END:VALARM
DTSTART:20180606T230000Z
DTEND:20180607T020000Z
UID:VHmfBCBcqFtBvIG4nfBAFkyY@stanza.co
SUMMARY:Miracle vs. Cardinals
DESCRIPTION:Miracle vs. Cardinals\n\nFollow on MiLB First Pitch: https://stza.co/+xMbH-3m\n\nShop: https://stza.co/+xMbH-2a\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144525Z
LAST-MODIFIED:20180213T144525Z
TRANSP:OPAQUE
END:VEVENT
* Miracle vs. Cardinals
<2018-06-07 Thu 18:00-21:00>
:PROPERTIES:
:ID:       sGNsYbNcqiNuMBJaYrTXlJhc@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Miracle vs. Cardinals Miracle vs. Cardinals

Follow on MiLB First Pitch  https //stza.co/+xMbJ-2x

Shop  https //stza.co/+xMbJ-11

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Miracle vs. Cardinals
END:VALARM
DTSTART:20180607T230000Z
DTEND:20180608T020000Z
UID:sGNsYbNcqiNuMBJaYrTXlJhc@stanza.co
SUMMARY:Miracle vs. Cardinals
DESCRIPTION:Miracle vs. Cardinals\n\nFollow on MiLB First Pitch: https://stza.co/+xMbJ-2x\n\nShop: https://stza.co/+xMbJ-11\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144525Z
LAST-MODIFIED:20180213T144525Z
TRANSP:OPAQUE
END:VEVENT
* Miracle vs. Blue Jays
<2018-06-08 Fri 18:00-21:00>
:PROPERTIES:
:ID:       hiTrofLcqQ3HoeEUwDCKLdeG@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Miracle vs. Blue Jays Miracle vs. Blue Jays

Follow on MiLB First Pitch  https //stza.co/+xMbL-2N

Shop  https //stza.co/+xMbL-k

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Miracle vs. Blue Jays
END:VALARM
DTSTART:20180608T230000Z
DTEND:20180609T020000Z
UID:hiTrofLcqQ3HoeEUwDCKLdeG@stanza.co
SUMMARY:Miracle vs. Blue Jays
DESCRIPTION:Miracle vs. Blue Jays\n\nFollow on MiLB First Pitch: https://stza.co/+xMbL-2N\n\nShop: https://stza.co/+xMbL-k\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144525Z
LAST-MODIFIED:20180213T144525Z
TRANSP:OPAQUE
END:VEVENT
* Miracle vs. Blue Jays
<2018-06-09 Sat 17:00-20:00>
:PROPERTIES:
:ID:       i0ZqOg9vtqLgBCYpOrgQB6sb@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Miracle vs. Blue Jays Miracle vs. Blue Jays

Follow on MiLB First Pitch  https //stza.co/+xMbO-t

Shop  https //stza.co/+xMbO-2C

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Miracle vs. Blue Jays
END:VALARM
DTSTART:20180609T220000Z
DTEND:20180610T010000Z
UID:i0ZqOg9vtqLgBCYpOrgQB6sb@stanza.co
SUMMARY:Miracle vs. Blue Jays
DESCRIPTION:Miracle vs. Blue Jays\n\nFollow on MiLB First Pitch: https://stza.co/+xMbO-t\n\nShop: https://stza.co/+xMbO-2C\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144525Z
LAST-MODIFIED:20180213T144525Z
TRANSP:OPAQUE
END:VEVENT
* Miracle vs. Blue Jays
<2018-06-10 Sun 15:00-18:00>
:PROPERTIES:
:ID:       2s4792IFAFNYtaYHqkednWxt@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Miracle vs. Blue Jays Miracle vs. Blue Jays

Follow on MiLB First Pitch  https //stza.co/+xMbP-3u

Shop  https //stza.co/+xMbP-1E

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Miracle vs. Blue Jays
END:VALARM
DTSTART:20180610T200000Z
DTEND:20180610T230000Z
UID:2s4792IFAFNYtaYHqkednWxt@stanza.co
SUMMARY:Miracle vs. Blue Jays
DESCRIPTION:Miracle vs. Blue Jays\n\nFollow on MiLB First Pitch: https://stza.co/+xMbP-3u\n\nShop: https://stza.co/+xMbP-1E\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144525Z
LAST-MODIFIED:20180213T144525Z
TRANSP:OPAQUE
END:VEVENT
* Miracle @ Cardinals
<2018-06-11 Mon>--<2018-06-10 Sun>
:PROPERTIES:
:ID:       o6-v2GhUA3bts24L_lAjnWtw@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Miracle @ Cardinals Miracle @ Cardinals

Buy tickets here  https //stza.co/~vMt_

Follow on MiLB First Pitch  https //stza.co/+vMt_-38

Shop  https //stza.co/+vMt_-u

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Miracle @ Cardinals
END:VALARM
DTSTART;VALUE=DATE:20180611
DTEND;VALUE=DATE:20180611
UID:o6-v2GhUA3bts24L_lAjnWtw@stanza.co
SUMMARY:Miracle @ Cardinals
DESCRIPTION:Miracle @ Cardinals\n\nBuy tickets here: https://stza.co/~vMt_\n\nFollow on MiLB First Pitch: https://stza.co/+vMt_-38\n\nShop: https://stza.co/+vMt_-u\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144525Z
LAST-MODIFIED:20180213T144525Z
TRANSP:OPAQUE
END:VEVENT
* Miracle @ Cardinals
<2018-06-12 Tue>--<2018-06-11 Mon>
:PROPERTIES:
:ID:       2sNutnb9ATlM1Fzk8Qk13fYJ@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Miracle @ Cardinals Miracle @ Cardinals

Buy tickets here  https //stza.co/~vMt$

Follow on MiLB First Pitch  https //stza.co/+vMt$-2H

Shop  https //stza.co/+vMt$-3o

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Miracle @ Cardinals
END:VALARM
DTSTART;VALUE=DATE:20180612
DTEND;VALUE=DATE:20180612
UID:2sNutnb9ATlM1Fzk8Qk13fYJ@stanza.co
SUMMARY:Miracle @ Cardinals
DESCRIPTION:Miracle @ Cardinals\n\nBuy tickets here: https://stza.co/~vMt$\n\nFollow on MiLB First Pitch: https://stza.co/+vMt$-2H\n\nShop: https://stza.co/+vMt$-3o\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144525Z
LAST-MODIFIED:20180213T144525Z
TRANSP:OPAQUE
END:VEVENT
* Miracle @ Cardinals
<2018-06-13 Wed>--<2018-06-12 Tue>
:PROPERTIES:
:ID:       g5HTBlp7-IzLLmCVSL8__-8I@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Miracle @ Cardinals Miracle @ Cardinals

Buy tickets here  https //stza.co/~vMu0

Follow on MiLB First Pitch  https //stza.co/+vMu0-R

Shop  https //stza.co/+vMu0-3K

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Miracle @ Cardinals
END:VALARM
DTSTART;VALUE=DATE:20180613
DTEND;VALUE=DATE:20180613
UID:g5HTBlp7-IzLLmCVSL8__-8I@stanza.co
SUMMARY:Miracle @ Cardinals
DESCRIPTION:Miracle @ Cardinals\n\nBuy tickets here: https://stza.co/~vMu0\n\nFollow on MiLB First Pitch: https://stza.co/+vMu0-R\n\nShop: https://stza.co/+vMu0-3K\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144525Z
LAST-MODIFIED:20180213T144525Z
TRANSP:OPAQUE
END:VEVENT
* Miracle @ Cardinals
<2018-06-14 Thu>--<2018-06-13 Wed>
:PROPERTIES:
:ID:       K_MiB3b1ZUY6XhEfvP_82eoN@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Miracle @ Cardinals Miracle @ Cardinals

Buy tickets here  https //stza.co/~vMu1

Follow on MiLB First Pitch  https //stza.co/+vMu1-n

Shop  https //stza.co/+vMu1-b

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Miracle @ Cardinals
END:VALARM
DTSTART;VALUE=DATE:20180614
DTEND;VALUE=DATE:20180614
UID:K_MiB3b1ZUY6XhEfvP_82eoN@stanza.co
SUMMARY:Miracle @ Cardinals
DESCRIPTION:Miracle @ Cardinals\n\nBuy tickets here: https://stza.co/~vMu1\n\nFollow on MiLB First Pitch: https://stza.co/+vMu1-n\n\nShop: https://stza.co/+vMu1-b\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144525Z
LAST-MODIFIED:20180213T144525Z
TRANSP:OPAQUE
END:VEVENT
* Miracle vs. Tarpons
<2018-06-18 Mon 18:00-21:00>
:PROPERTIES:
:ID:       KSKgumLG2WiCmEPP6clV0cLs@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Miracle vs. Tarpons Miracle vs. Tarpons

Follow on MiLB First Pitch  https //stza.co/+xMbS-3F

Shop  https //stza.co/+xMbS-g

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Miracle vs. Tarpons
END:VALARM
DTSTART:20180618T230000Z
DTEND:20180619T020000Z
UID:KSKgumLG2WiCmEPP6clV0cLs@stanza.co
SUMMARY:Miracle vs. Tarpons
DESCRIPTION:Miracle vs. Tarpons\n\nFollow on MiLB First Pitch: https://stza.co/+xMbS-3F\n\nShop: https://stza.co/+xMbS-g\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144525Z
LAST-MODIFIED:20180213T144525Z
TRANSP:OPAQUE
END:VEVENT
* Miracle vs. Tarpons
<2018-06-19 Tue 18:00-21:00>
:PROPERTIES:
:ID:       izDqz-i6I29zm0svYqhac4MF@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Miracle vs. Tarpons Miracle vs. Tarpons

Follow on MiLB First Pitch  https //stza.co/+xMbT-W

Shop  https //stza.co/+xMbT-s

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Miracle vs. Tarpons
END:VALARM
DTSTART:20180619T230000Z
DTEND:20180620T020000Z
UID:izDqz-i6I29zm0svYqhac4MF@stanza.co
SUMMARY:Miracle vs. Tarpons
DESCRIPTION:Miracle vs. Tarpons\n\nFollow on MiLB First Pitch: https://stza.co/+xMbT-W\n\nShop: https://stza.co/+xMbT-s\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144525Z
LAST-MODIFIED:20180213T144525Z
TRANSP:OPAQUE
END:VEVENT
* Miracle vs. Tarpons
<2018-06-20 Wed 11:00-14:00>
:PROPERTIES:
:ID:       f6bhmFxyFRUiry-Ml6AumgXf@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Miracle vs. Tarpons Miracle vs. Tarpons

Follow on MiLB First Pitch  https //stza.co/+xMbW-i

Shop  https //stza.co/+xMbW-1s

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Miracle vs. Tarpons
END:VALARM
DTSTART:20180620T160000Z
DTEND:20180620T190000Z
UID:f6bhmFxyFRUiry-Ml6AumgXf@stanza.co
SUMMARY:Miracle vs. Tarpons
DESCRIPTION:Miracle vs. Tarpons\n\nFollow on MiLB First Pitch: https://stza.co/+xMbW-i\n\nShop: https://stza.co/+xMbW-1s\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144525Z
LAST-MODIFIED:20180213T144525Z
TRANSP:OPAQUE
END:VEVENT
* Miracle @ Marauders
<2018-06-21 Thu 17:30-20:30>
:PROPERTIES:
:ID:       HwFUTkVyU9FE76r8OXTL3M1F@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Miracle @ Marauders Miracle @ Marauders

Follow on MiLB First Pitch  https //stza.co/+vMr2-2c

Shop  https //stza.co/+vMr2-7

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Miracle @ Marauders
END:VALARM
DTSTART:20180621T223000Z
DTEND:20180622T013000Z
UID:HwFUTkVyU9FE76r8OXTL3M1F@stanza.co
SUMMARY:Miracle @ Marauders
DESCRIPTION:Miracle @ Marauders\n\nFollow on MiLB First Pitch: https://stza.co/+vMr2-2c\n\nShop: https://stza.co/+vMr2-7\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144525Z
LAST-MODIFIED:20180213T144525Z
TRANSP:OPAQUE
END:VEVENT
* Miracle @ Marauders
<2018-06-22 Fri 17:30-20:30>
:PROPERTIES:
:ID:       Bne2X5HS6K-A0Si1NQpVbJMD@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Miracle @ Marauders Miracle @ Marauders

Follow on MiLB First Pitch  https //stza.co/+vMr3-1M

Shop  https //stza.co/+vMr3-17

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Miracle @ Marauders
END:VALARM
DTSTART:20180622T223000Z
DTEND:20180623T013000Z
UID:Bne2X5HS6K-A0Si1NQpVbJMD@stanza.co
SUMMARY:Miracle @ Marauders
DESCRIPTION:Miracle @ Marauders\n\nFollow on MiLB First Pitch: https://stza.co/+vMr3-1M\n\nShop: https://stza.co/+vMr3-17\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144525Z
LAST-MODIFIED:20180213T144525Z
TRANSP:OPAQUE
END:VEVENT
* Miracle @ Marauders
<2018-06-23 Sat 17:30-20:30>
:PROPERTIES:
:ID:       RdTRi0_3F0uKhgQUg7vkZvpB@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Miracle @ Marauders Miracle @ Marauders

Follow on MiLB First Pitch  https //stza.co/+vMr4-35

Shop  https //stza.co/+vMr4-2r

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Miracle @ Marauders
END:VALARM
DTSTART:20180623T223000Z
DTEND:20180624T013000Z
UID:RdTRi0_3F0uKhgQUg7vkZvpB@stanza.co
SUMMARY:Miracle @ Marauders
DESCRIPTION:Miracle @ Marauders\n\nFollow on MiLB First Pitch: https://stza.co/+vMr4-35\n\nShop: https://stza.co/+vMr4-2r\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144525Z
LAST-MODIFIED:20180213T144525Z
TRANSP:OPAQUE
END:VEVENT
* Miracle @ Marauders
<2018-06-24 Sun 12:00-15:00>
:PROPERTIES:
:ID:       oQs7ia9TRNOfbgSnsQtUHU3z@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Miracle @ Marauders Miracle @ Marauders

Follow on MiLB First Pitch  https //stza.co/+vMr5-3y

Shop  https //stza.co/+vMr5-9

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Miracle @ Marauders
END:VALARM
DTSTART:20180624T170000Z
DTEND:20180624T200000Z
UID:oQs7ia9TRNOfbgSnsQtUHU3z@stanza.co
SUMMARY:Miracle @ Marauders
DESCRIPTION:Miracle @ Marauders\n\nFollow on MiLB First Pitch: https://stza.co/+vMr5-3y\n\nShop: https://stza.co/+vMr5-9\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144525Z
LAST-MODIFIED:20180213T144525Z
TRANSP:OPAQUE
END:VEVENT
* Miracle @ Tarpons
<2018-06-26 Tue>--<2018-06-25 Mon>
:PROPERTIES:
:ID:       1cXzGgdJwTXx3m1n1oMHQaX8@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Miracle @ Tarpons Miracle @ Tarpons

Follow on MiLB First Pitch  https //stza.co/+vkLF-3A

Shop  https //stza.co/+vkLF-3B

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Miracle @ Tarpons
END:VALARM
DTSTART;VALUE=DATE:20180626
DTEND;VALUE=DATE:20180626
UID:1cXzGgdJwTXx3m1n1oMHQaX8@stanza.co
SUMMARY:Miracle @ Tarpons
DESCRIPTION:Miracle @ Tarpons\n\nFollow on MiLB First Pitch: https://stza.co/+vkLF-3A\n\nShop: https://stza.co/+vkLF-3B\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144525Z
LAST-MODIFIED:20180213T144525Z
TRANSP:OPAQUE
END:VEVENT
* Miracle @ Tarpons
<2018-06-27 Wed>--<2018-06-26 Tue>
:PROPERTIES:
:ID:       Kt9hywzHzgfut-Y7Ht1m_zBW@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Miracle @ Tarpons Miracle @ Tarpons

Follow on MiLB First Pitch  https //stza.co/+vkLM-1Q

Shop  https //stza.co/+vkLM-1w

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Miracle @ Tarpons
END:VALARM
DTSTART;VALUE=DATE:20180627
DTEND;VALUE=DATE:20180627
UID:Kt9hywzHzgfut-Y7Ht1m_zBW@stanza.co
SUMMARY:Miracle @ Tarpons
DESCRIPTION:Miracle @ Tarpons\n\nFollow on MiLB First Pitch: https://stza.co/+vkLM-1Q\n\nShop: https://stza.co/+vkLM-1w\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144525Z
LAST-MODIFIED:20180213T144525Z
TRANSP:OPAQUE
END:VEVENT
* Miracle @ Tarpons
<2018-06-28 Thu>--<2018-06-27 Wed>
:PROPERTIES:
:ID:       Xgdh4Pa8TzLMQ32Uw6yVF_j7@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Miracle @ Tarpons Miracle @ Tarpons

Follow on MiLB First Pitch  https //stza.co/+vjKk-3F

Shop  https //stza.co/+vjKk-1t

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Miracle @ Tarpons
END:VALARM
DTSTART;VALUE=DATE:20180628
DTEND;VALUE=DATE:20180628
UID:Xgdh4Pa8TzLMQ32Uw6yVF_j7@stanza.co
SUMMARY:Miracle @ Tarpons
DESCRIPTION:Miracle @ Tarpons\n\nFollow on MiLB First Pitch: https://stza.co/+vjKk-3F\n\nShop: https://stza.co/+vjKk-1t\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144525Z
LAST-MODIFIED:20180213T144525Z
TRANSP:OPAQUE
END:VEVENT
* Miracle vs. Flying Tigers
<2018-06-29 Fri 18:00-21:00>
:PROPERTIES:
:ID:       dlOOuNj9-IH20lgxhhGui5OK@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Miracle vs. Flying Tigers Miracle vs. Flying Tigers

Follow on MiLB First Pitch  https //stza.co/+xMbX-1m

Shop  https //stza.co/+xMbX-y

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Miracle vs. Flying Tigers
END:VALARM
DTSTART:20180629T230000Z
DTEND:20180630T020000Z
UID:dlOOuNj9-IH20lgxhhGui5OK@stanza.co
SUMMARY:Miracle vs. Flying Tigers
DESCRIPTION:Miracle vs. Flying Tigers\n\nFollow on MiLB First Pitch: https://stza.co/+xMbX-1m\n\nShop: https://stza.co/+xMbX-y\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144525Z
LAST-MODIFIED:20180213T144525Z
TRANSP:OPAQUE
END:VEVENT
* Miracle vs. Flying Tigers
<2018-06-30 Sat 17:00-20:00>
:PROPERTIES:
:ID:       XFwdsejYER8J-Fx1vdOsmokw@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Miracle vs. Flying Tigers Miracle vs. Flying Tigers

Follow on MiLB First Pitch  https //stza.co/+xMb_-3t

Shop  https //stza.co/+xMb_-1Z

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Miracle vs. Flying Tigers
END:VALARM
DTSTART:20180630T220000Z
DTEND:20180701T010000Z
UID:XFwdsejYER8J-Fx1vdOsmokw@stanza.co
SUMMARY:Miracle vs. Flying Tigers
DESCRIPTION:Miracle vs. Flying Tigers\n\nFollow on MiLB First Pitch: https://stza.co/+xMb_-3t\n\nShop: https://stza.co/+xMb_-1Z\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144525Z
LAST-MODIFIED:20180213T144525Z
TRANSP:OPAQUE
END:VEVENT
* Miracle vs. Flying Tigers
<2018-07-01 Sun 15:00-18:00>
:PROPERTIES:
:ID:       -v20l8TjI2fogElsa6OsWyF_@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Miracle vs. Flying Tigers Miracle vs. Flying Tigers

Follow on MiLB First Pitch  https //stza.co/+xMb$-h

Shop  https //stza.co/+xMb$-3S

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Miracle vs. Flying Tigers
END:VALARM
DTSTART:20180701T200000Z
DTEND:20180701T230000Z
UID:-v20l8TjI2fogElsa6OsWyF_@stanza.co
SUMMARY:Miracle vs. Flying Tigers
DESCRIPTION:Miracle vs. Flying Tigers\n\nFollow on MiLB First Pitch: https://stza.co/+xMb$-h\n\nShop: https://stza.co/+xMb$-3S\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144525Z
LAST-MODIFIED:20180213T144525Z
TRANSP:OPAQUE
END:VEVENT
* Miracle @ Stone Crabs
<2018-07-02 Mon 17:35-20:35>
:PROPERTIES:
:ID:       7l4o5YyNowSvmjolk9bxNXGc@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Miracle @ Stone Crabs Miracle @ Stone Crabs

Follow on MiLB First Pitch  https //stza.co/+wYod-H

Shop  https //stza.co/+wYod-3p

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Miracle @ Stone Crabs
END:VALARM
DTSTART:20180702T223500Z
DTEND:20180703T013500Z
UID:7l4o5YyNowSvmjolk9bxNXGc@stanza.co
SUMMARY:Miracle @ Stone Crabs
DESCRIPTION:Miracle @ Stone Crabs\n\nFollow on MiLB First Pitch: https://stza.co/+wYod-H\n\nShop: https://stza.co/+wYod-3p\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144525Z
LAST-MODIFIED:20180213T144525Z
TRANSP:OPAQUE
END:VEVENT
* Miracle @ Stone Crabs
<2018-07-03 Tue 17:35-20:35>
:PROPERTIES:
:ID:       RE5DrxelMazaRfYTqXCtRxRO@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Miracle @ Stone Crabs Miracle @ Stone Crabs

Follow on MiLB First Pitch  https //stza.co/+wYog-1$

Shop  https //stza.co/+wYog-13

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Miracle @ Stone Crabs
END:VALARM
DTSTART:20180703T223500Z
DTEND:20180704T013500Z
UID:RE5DrxelMazaRfYTqXCtRxRO@stanza.co
SUMMARY:Miracle @ Stone Crabs
DESCRIPTION:Miracle @ Stone Crabs\n\nFollow on MiLB First Pitch: https://stza.co/+wYog-1$\n\nShop: https://stza.co/+wYog-13\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144525Z
LAST-MODIFIED:20180213T144525Z
TRANSP:OPAQUE
END:VEVENT
* Miracle vs. Blue Jays
<2018-07-04 Wed 18:00-21:00>
:PROPERTIES:
:ID:       ttD4XeU5eGng2I7WF9VY0uCB@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Miracle vs. Blue Jays Miracle vs. Blue Jays

Follow on MiLB First Pitch  https //stza.co/+xMc2-1E

Shop  https //stza.co/+xMc2-9

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Miracle vs. Blue Jays
END:VALARM
DTSTART:20180704T230000Z
DTEND:20180705T020000Z
UID:ttD4XeU5eGng2I7WF9VY0uCB@stanza.co
SUMMARY:Miracle vs. Blue Jays
DESCRIPTION:Miracle vs. Blue Jays\n\nFollow on MiLB First Pitch: https://stza.co/+xMc2-1E\n\nShop: https://stza.co/+xMc2-9\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144525Z
LAST-MODIFIED:20180213T144525Z
TRANSP:OPAQUE
END:VEVENT
* Miracle vs. Blue Jays
<2018-07-05 Thu 18:00-21:00>
:PROPERTIES:
:ID:       Y5Bnijd0DyYg2NINrksKBx_t@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Miracle vs. Blue Jays Miracle vs. Blue Jays

Follow on MiLB First Pitch  https //stza.co/+xMc4-2A

Shop  https //stza.co/+xMc4-3w

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Miracle vs. Blue Jays
END:VALARM
DTSTART:20180705T230000Z
DTEND:20180706T020000Z
UID:Y5Bnijd0DyYg2NINrksKBx_t@stanza.co
SUMMARY:Miracle vs. Blue Jays
DESCRIPTION:Miracle vs. Blue Jays\n\nFollow on MiLB First Pitch: https://stza.co/+xMc4-2A\n\nShop: https://stza.co/+xMc4-3w\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144525Z
LAST-MODIFIED:20180213T144525Z
TRANSP:OPAQUE
END:VEVENT
* Miracle @ Marauders
<2018-07-06 Fri 17:30-20:30>
:PROPERTIES:
:ID:       twDOhZ65rtdw1caFqn0HbBuz@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Miracle @ Marauders Miracle @ Marauders

Follow on MiLB First Pitch  https //stza.co/+vMr6-B

Shop  https //stza.co/+vMr6-2Q

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Miracle @ Marauders
END:VALARM
DTSTART:20180706T223000Z
DTEND:20180707T013000Z
UID:twDOhZ65rtdw1caFqn0HbBuz@stanza.co
SUMMARY:Miracle @ Marauders
DESCRIPTION:Miracle @ Marauders\n\nFollow on MiLB First Pitch: https://stza.co/+vMr6-B\n\nShop: https://stza.co/+vMr6-2Q\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144525Z
LAST-MODIFIED:20180213T144525Z
TRANSP:OPAQUE
END:VEVENT
* Miracle @ Marauders
<2018-07-07 Sat 17:30-20:30>
:PROPERTIES:
:ID:       sjWz2WEe6sEe5wh_EwXzvZTD@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Miracle @ Marauders Miracle @ Marauders

Follow on MiLB First Pitch  https //stza.co/+vMr7-1z

Shop  https //stza.co/+vMr7-L

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Miracle @ Marauders
END:VALARM
DTSTART:20180707T223000Z
DTEND:20180708T013000Z
UID:sjWz2WEe6sEe5wh_EwXzvZTD@stanza.co
SUMMARY:Miracle @ Marauders
DESCRIPTION:Miracle @ Marauders\n\nFollow on MiLB First Pitch: https://stza.co/+vMr7-1z\n\nShop: https://stza.co/+vMr7-L\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144525Z
LAST-MODIFIED:20180213T144525Z
TRANSP:OPAQUE
END:VEVENT
* Miracle @ Marauders
<2018-07-08 Sun 12:00-15:00>
:PROPERTIES:
:ID:       uUU0ztLh81eghNL1ZquNy6I_@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Miracle @ Marauders Miracle @ Marauders

Follow on MiLB First Pitch  https //stza.co/+vMr8-1p

Shop  https //stza.co/+vMr8-2Q

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Miracle @ Marauders
END:VALARM
DTSTART:20180708T170000Z
DTEND:20180708T200000Z
UID:uUU0ztLh81eghNL1ZquNy6I_@stanza.co
SUMMARY:Miracle @ Marauders
DESCRIPTION:Miracle @ Marauders\n\nFollow on MiLB First Pitch: https://stza.co/+vMr8-1p\n\nShop: https://stza.co/+vMr8-2Q\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144525Z
LAST-MODIFIED:20180213T144525Z
TRANSP:OPAQUE
END:VEVENT
* Miracle vs. Cardinals
<2018-07-09 Mon 18:00-21:00>
:PROPERTIES:
:ID:       TfUTOg03oyh_gV30cInAzLic@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Miracle vs. Cardinals Miracle vs. Cardinals

Follow on MiLB First Pitch  https //stza.co/+xMc5-2k

Shop  https //stza.co/+xMc5-34

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Miracle vs. Cardinals
END:VALARM
DTSTART:20180709T230000Z
DTEND:20180710T020000Z
UID:TfUTOg03oyh_gV30cInAzLic@stanza.co
SUMMARY:Miracle vs. Cardinals
DESCRIPTION:Miracle vs. Cardinals\n\nFollow on MiLB First Pitch: https://stza.co/+xMc5-2k\n\nShop: https://stza.co/+xMc5-34\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144525Z
LAST-MODIFIED:20180213T144525Z
TRANSP:OPAQUE
END:VEVENT
* Miracle vs. Cardinals
<2018-07-10 Tue 18:00-21:00>
:PROPERTIES:
:ID:       w8yiK-OLusXKwm5Yp2bT1ZdV@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Miracle vs. Cardinals Miracle vs. Cardinals

Follow on MiLB First Pitch  https //stza.co/+xMc7-i

Shop  https //stza.co/+xMc7-1_

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Miracle vs. Cardinals
END:VALARM
DTSTART:20180710T230000Z
DTEND:20180711T020000Z
UID:w8yiK-OLusXKwm5Yp2bT1ZdV@stanza.co
SUMMARY:Miracle vs. Cardinals
DESCRIPTION:Miracle vs. Cardinals\n\nFollow on MiLB First Pitch: https://stza.co/+xMc7-i\n\nShop: https://stza.co/+xMc7-1_\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144525Z
LAST-MODIFIED:20180213T144525Z
TRANSP:OPAQUE
END:VEVENT
* Miracle vs. Cardinals
<2018-07-11 Wed 18:00-21:00>
:PROPERTIES:
:ID:       aUG3Ynrruxz_S2OR_CEicoHm@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Miracle vs. Cardinals Miracle vs. Cardinals

Follow on MiLB First Pitch  https //stza.co/+xMc9-N

Shop  https //stza.co/+xMc9-36

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Miracle vs. Cardinals
END:VALARM
DTSTART:20180711T230000Z
DTEND:20180712T020000Z
UID:aUG3Ynrruxz_S2OR_CEicoHm@stanza.co
SUMMARY:Miracle vs. Cardinals
DESCRIPTION:Miracle vs. Cardinals\n\nFollow on MiLB First Pitch: https://stza.co/+xMc9-N\n\nShop: https://stza.co/+xMc9-36\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144525Z
LAST-MODIFIED:20180213T144525Z
TRANSP:OPAQUE
END:VEVENT
* Miracle vs. Cardinals
<2018-07-12 Thu 18:00-21:00>
:PROPERTIES:
:ID:       p9IuuPcTyZl8N9fZjgpNG3o1@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Miracle vs. Cardinals Miracle vs. Cardinals

Follow on MiLB First Pitch  https //stza.co/+xMcb-5

Shop  https //stza.co/+xMcb-27

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Miracle vs. Cardinals
END:VALARM
DTSTART:20180712T230000Z
DTEND:20180713T020000Z
UID:p9IuuPcTyZl8N9fZjgpNG3o1@stanza.co
SUMMARY:Miracle vs. Cardinals
DESCRIPTION:Miracle vs. Cardinals\n\nFollow on MiLB First Pitch: https://stza.co/+xMcb-5\n\nShop: https://stza.co/+xMcb-27\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144525Z
LAST-MODIFIED:20180213T144525Z
TRANSP:OPAQUE
END:VEVENT
* Miracle @ Flying Tigers
<2018-07-13 Fri 17:30-20:30>
:PROPERTIES:
:ID:       XpnanBd8Yf99j4D5JysZjX8n@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Miracle @ Flying Tigers Miracle @ Flying Tigers

Follow on MiLB First Pitch  https //stza.co/+wKNl-1h

Shop  https //stza.co/+wKNl-37

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Miracle @ Flying Tigers
END:VALARM
DTSTART:20180713T223000Z
DTEND:20180714T013000Z
UID:XpnanBd8Yf99j4D5JysZjX8n@stanza.co
SUMMARY:Miracle @ Flying Tigers
DESCRIPTION:Miracle @ Flying Tigers\n\nFollow on MiLB First Pitch: https://stza.co/+wKNl-1h\n\nShop: https://stza.co/+wKNl-37\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144525Z
LAST-MODIFIED:20180213T144525Z
TRANSP:OPAQUE
END:VEVENT
* Miracle @ Flying Tigers
<2018-07-14 Sat 17:00-20:00>
:PROPERTIES:
:ID:       5blOcHFKfNiGgr116Ae0X3gK@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Miracle @ Flying Tigers Miracle @ Flying Tigers

Follow on MiLB First Pitch  https //stza.co/+wKNm-x

Shop  https //stza.co/+wKNm-1v

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Miracle @ Flying Tigers
END:VALARM
DTSTART:20180714T220000Z
DTEND:20180715T010000Z
UID:5blOcHFKfNiGgr116Ae0X3gK@stanza.co
SUMMARY:Miracle @ Flying Tigers
DESCRIPTION:Miracle @ Flying Tigers\n\nFollow on MiLB First Pitch: https://stza.co/+wKNm-x\n\nShop: https://stza.co/+wKNm-1v\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144525Z
LAST-MODIFIED:20180213T144525Z
TRANSP:OPAQUE
END:VEVENT
* Miracle @ Flying Tigers
<2018-07-15 Sun 12:00-15:00>
:PROPERTIES:
:ID:       wxBLOXcLi_gXwFNtGMJFk1J_@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Miracle @ Flying Tigers Miracle @ Flying Tigers

Follow on MiLB First Pitch  https //stza.co/+wKNn-33

Shop  https //stza.co/+wKNn-2_

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Miracle @ Flying Tigers
END:VALARM
DTSTART:20180715T170000Z
DTEND:20180715T200000Z
UID:wxBLOXcLi_gXwFNtGMJFk1J_@stanza.co
SUMMARY:Miracle @ Flying Tigers
DESCRIPTION:Miracle @ Flying Tigers\n\nFollow on MiLB First Pitch: https://stza.co/+wKNn-33\n\nShop: https://stza.co/+wKNn-2_\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144525Z
LAST-MODIFIED:20180213T144525Z
TRANSP:OPAQUE
END:VEVENT
* Miracle vs. Mets
<2018-07-16 Mon 18:00-21:00>
:PROPERTIES:
:ID:       bmW9j4Jt0a8ZlhP06iZmmjAl@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Miracle vs. Mets Miracle vs. Mets

Follow on MiLB First Pitch  https //stza.co/+xMcd-3R

Shop  https //stza.co/+xMcd-1y

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Miracle vs. Mets
END:VALARM
DTSTART:20180716T230000Z
DTEND:20180717T020000Z
UID:bmW9j4Jt0a8ZlhP06iZmmjAl@stanza.co
SUMMARY:Miracle vs. Mets
DESCRIPTION:Miracle vs. Mets\n\nFollow on MiLB First Pitch: https://stza.co/+xMcd-3R\n\nShop: https://stza.co/+xMcd-1y\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144525Z
LAST-MODIFIED:20180213T144525Z
TRANSP:OPAQUE
END:VEVENT
* Miracle vs. Mets
<2018-07-17 Tue 18:00-21:00>
:PROPERTIES:
:ID:       LrtE1QKnpKxN6gLDBZQoLkPK@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Miracle vs. Mets Miracle vs. Mets

Follow on MiLB First Pitch  https //stza.co/+xMcf-35

Shop  https //stza.co/+xMcf-3K

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Miracle vs. Mets
END:VALARM
DTSTART:20180717T230000Z
DTEND:20180718T020000Z
UID:LrtE1QKnpKxN6gLDBZQoLkPK@stanza.co
SUMMARY:Miracle vs. Mets
DESCRIPTION:Miracle vs. Mets\n\nFollow on MiLB First Pitch: https://stza.co/+xMcf-35\n\nShop: https://stza.co/+xMcf-3K\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144525Z
LAST-MODIFIED:20180213T144525Z
TRANSP:OPAQUE
END:VEVENT
* Miracle vs. Mets
<2018-07-18 Wed 18:00-21:00>
:PROPERTIES:
:ID:       SAdxTjiEVTEoI0_ibu1FDCA2@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Miracle vs. Mets Miracle vs. Mets

Follow on MiLB First Pitch  https //stza.co/+xMci-2j

Shop  https //stza.co/+xMci-1h

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Miracle vs. Mets
END:VALARM
DTSTART:20180718T230000Z
DTEND:20180719T020000Z
UID:SAdxTjiEVTEoI0_ibu1FDCA2@stanza.co
SUMMARY:Miracle vs. Mets
DESCRIPTION:Miracle vs. Mets\n\nFollow on MiLB First Pitch: https://stza.co/+xMci-2j\n\nShop: https://stza.co/+xMci-1h\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144525Z
LAST-MODIFIED:20180213T144525Z
TRANSP:OPAQUE
END:VEVENT
* Miracle vs. Flying Tigers
<2018-07-19 Thu 18:00-21:00>
:PROPERTIES:
:ID:       xrwqkZVWatb4tajRwt59uCKb@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Miracle vs. Flying Tigers Miracle vs. Flying Tigers

Follow on MiLB First Pitch  https //stza.co/+xMcj-3c

Shop  https //stza.co/+xMcj-2y

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Miracle vs. Flying Tigers
END:VALARM
DTSTART:20180719T230000Z
DTEND:20180720T020000Z
UID:xrwqkZVWatb4tajRwt59uCKb@stanza.co
SUMMARY:Miracle vs. Flying Tigers
DESCRIPTION:Miracle vs. Flying Tigers\n\nFollow on MiLB First Pitch: https://stza.co/+xMcj-3c\n\nShop: https://stza.co/+xMcj-2y\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144525Z
LAST-MODIFIED:20180213T144525Z
TRANSP:OPAQUE
END:VEVENT
* Miracle vs. Flying Tigers
<2018-07-20 Fri 18:00-21:00>
:PROPERTIES:
:ID:       rW_A1UmDaT1Evh8FWweZZdcD@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Miracle vs. Flying Tigers Miracle vs. Flying Tigers

Follow on MiLB First Pitch  https //stza.co/+xMcm-2t

Shop  https //stza.co/+xMcm-1L

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Miracle vs. Flying Tigers
END:VALARM
DTSTART:20180720T230000Z
DTEND:20180721T020000Z
UID:rW_A1UmDaT1Evh8FWweZZdcD@stanza.co
SUMMARY:Miracle vs. Flying Tigers
DESCRIPTION:Miracle vs. Flying Tigers\n\nFollow on MiLB First Pitch: https://stza.co/+xMcm-2t\n\nShop: https://stza.co/+xMcm-1L\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144525Z
LAST-MODIFIED:20180213T144525Z
TRANSP:OPAQUE
END:VEVENT
* Miracle vs. Flying Tigers
<2018-07-21 Sat 17:00-20:00>
:PROPERTIES:
:ID:       wS6GBKwkukhDW4ebglVAivAC@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Miracle vs. Flying Tigers Miracle vs. Flying Tigers

Follow on MiLB First Pitch  https //stza.co/+xMcn-2x

Shop  https //stza.co/+xMcn-2R

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Miracle vs. Flying Tigers
END:VALARM
DTSTART:20180721T220000Z
DTEND:20180722T010000Z
UID:wS6GBKwkukhDW4ebglVAivAC@stanza.co
SUMMARY:Miracle vs. Flying Tigers
DESCRIPTION:Miracle vs. Flying Tigers\n\nFollow on MiLB First Pitch: https://stza.co/+xMcn-2x\n\nShop: https://stza.co/+xMcn-2R\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144525Z
LAST-MODIFIED:20180213T144525Z
TRANSP:OPAQUE
END:VEVENT
* Miracle @ Hammerheads
<2018-07-23 Mon>--<2018-07-22 Sun>
:PROPERTIES:
:ID:       wIHiwP0vaPehhtkdB3AgFUbs@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Miracle @ Hammerheads Miracle @ Hammerheads

Buy tickets here  https //stza.co/~vMtR

Follow on MiLB First Pitch  https //stza.co/+vMtR-2g

Shop  https //stza.co/+vMtR-a

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Miracle @ Hammerheads
END:VALARM
DTSTART;VALUE=DATE:20180723
DTEND;VALUE=DATE:20180723
UID:wIHiwP0vaPehhtkdB3AgFUbs@stanza.co
SUMMARY:Miracle @ Hammerheads
DESCRIPTION:Miracle @ Hammerheads\n\nBuy tickets here: https://stza.co/~vMtR\n\nFollow on MiLB First Pitch: https://stza.co/+vMtR-2g\n\nShop: https://stza.co/+vMtR-a\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144525Z
LAST-MODIFIED:20180213T144525Z
TRANSP:OPAQUE
END:VEVENT
* Miracle @ Hammerheads
<2018-07-24 Tue>--<2018-07-23 Mon>
:PROPERTIES:
:ID:       Zrpyg8kvcXc8tqc-iXro93vD@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Miracle @ Hammerheads Miracle @ Hammerheads

Buy tickets here  https //stza.co/~vMtS

Follow on MiLB First Pitch  https //stza.co/+vMtS-3E

Shop  https //stza.co/+vMtS-1s

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Miracle @ Hammerheads
END:VALARM
DTSTART;VALUE=DATE:20180724
DTEND;VALUE=DATE:20180724
UID:Zrpyg8kvcXc8tqc-iXro93vD@stanza.co
SUMMARY:Miracle @ Hammerheads
DESCRIPTION:Miracle @ Hammerheads\n\nBuy tickets here: https://stza.co/~vMtS\n\nFollow on MiLB First Pitch: https://stza.co/+vMtS-3E\n\nShop: https://stza.co/+vMtS-1s\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144525Z
LAST-MODIFIED:20180213T144525Z
TRANSP:OPAQUE
END:VEVENT
* Miracle @ Hammerheads
<2018-07-25 Wed>--<2018-07-24 Tue>
:PROPERTIES:
:ID:       8y604OetGCvCv9PilyY5er5h@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Miracle @ Hammerheads Miracle @ Hammerheads

Buy tickets here  https //stza.co/~vMtT

Follow on MiLB First Pitch  https //stza.co/+vMtT-l

Shop  https //stza.co/+vMtT-1

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Miracle @ Hammerheads
END:VALARM
DTSTART;VALUE=DATE:20180725
DTEND;VALUE=DATE:20180725
UID:8y604OetGCvCv9PilyY5er5h@stanza.co
SUMMARY:Miracle @ Hammerheads
DESCRIPTION:Miracle @ Hammerheads\n\nBuy tickets here: https://stza.co/~vMtT\n\nFollow on MiLB First Pitch: https://stza.co/+vMtT-l\n\nShop: https://stza.co/+vMtT-1\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144525Z
LAST-MODIFIED:20180213T144525Z
TRANSP:OPAQUE
END:VEVENT
* Miracle @ Tortugas
<2018-07-26 Thu 18:05-21:05>
:PROPERTIES:
:ID:       wKcsLdh4Nejf5rFUbmo4zzH5@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Miracle @ Tortugas Miracle @ Tortugas

Follow on MiLB First Pitch  https //stza.co/+vMrn-3u

Shop  https //stza.co/+vMrn-2V

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Miracle @ Tortugas
END:VALARM
DTSTART:20180726T230500Z
DTEND:20180727T020500Z
UID:wKcsLdh4Nejf5rFUbmo4zzH5@stanza.co
SUMMARY:Miracle @ Tortugas
DESCRIPTION:Miracle @ Tortugas\n\nFollow on MiLB First Pitch: https://stza.co/+vMrn-3u\n\nShop: https://stza.co/+vMrn-2V\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144525Z
LAST-MODIFIED:20180213T144525Z
TRANSP:OPAQUE
END:VEVENT
* Miracle @ Tortugas
<2018-07-27 Fri 18:05-21:05>
:PROPERTIES:
:ID:       K4nj0a_96Bnkz0-WAECHyM8Z@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Miracle @ Tortugas Miracle @ Tortugas

Follow on MiLB First Pitch  https //stza.co/+vMro-28

Shop  https //stza.co/+vMro-2W

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Miracle @ Tortugas
END:VALARM
DTSTART:20180727T230500Z
DTEND:20180728T020500Z
UID:K4nj0a_96Bnkz0-WAECHyM8Z@stanza.co
SUMMARY:Miracle @ Tortugas
DESCRIPTION:Miracle @ Tortugas\n\nFollow on MiLB First Pitch: https://stza.co/+vMro-28\n\nShop: https://stza.co/+vMro-2W\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144525Z
LAST-MODIFIED:20180213T144525Z
TRANSP:OPAQUE
END:VEVENT
* Miracle @ Tortugas
<2018-07-28 Sat 18:05-21:05>
:PROPERTIES:
:ID:       dDJTVUehbTWjmZ5zZDqBVNo_@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Miracle @ Tortugas Miracle @ Tortugas

Follow on MiLB First Pitch  https //stza.co/+vMrp-a

Shop  https //stza.co/+vMrp-1M

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Miracle @ Tortugas
END:VALARM
DTSTART:20180728T230500Z
DTEND:20180729T020500Z
UID:dDJTVUehbTWjmZ5zZDqBVNo_@stanza.co
SUMMARY:Miracle @ Tortugas
DESCRIPTION:Miracle @ Tortugas\n\nFollow on MiLB First Pitch: https://stza.co/+vMrp-a\n\nShop: https://stza.co/+vMrp-1M\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144525Z
LAST-MODIFIED:20180213T144525Z
TRANSP:OPAQUE
END:VEVENT
* Miracle @ Tortugas
<2018-07-29 Sun 16:35-19:35>
:PROPERTIES:
:ID:       8MZZYz9K0tdPeo1q0auvKG06@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Miracle @ Tortugas Miracle @ Tortugas

Follow on MiLB First Pitch  https //stza.co/+vMrq-i

Shop  https //stza.co/+vMrq-1g

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Miracle @ Tortugas
END:VALARM
DTSTART:20180729T213500Z
DTEND:20180730T003500Z
UID:8MZZYz9K0tdPeo1q0auvKG06@stanza.co
SUMMARY:Miracle @ Tortugas
DESCRIPTION:Miracle @ Tortugas\n\nFollow on MiLB First Pitch: https://stza.co/+vMrq-i\n\nShop: https://stza.co/+vMrq-1g\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144525Z
LAST-MODIFIED:20180213T144525Z
TRANSP:OPAQUE
END:VEVENT
* Miracle vs. Hammerheads
<2018-07-31 Tue 18:00-21:00>
:PROPERTIES:
:ID:       C8s9ihBb5OG4MPzUHgdt_ch0@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Miracle vs. Hammerheads Miracle vs. Hammerheads

Follow on MiLB First Pitch  https //stza.co/+xMcp-2A

Shop  https //stza.co/+xMcp-1t

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Miracle vs. Hammerheads
END:VALARM
DTSTART:20180731T230000Z
DTEND:20180801T020000Z
UID:C8s9ihBb5OG4MPzUHgdt_ch0@stanza.co
SUMMARY:Miracle vs. Hammerheads
DESCRIPTION:Miracle vs. Hammerheads\n\nFollow on MiLB First Pitch: https://stza.co/+xMcp-2A\n\nShop: https://stza.co/+xMcp-1t\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144525Z
LAST-MODIFIED:20180213T144525Z
TRANSP:OPAQUE
END:VEVENT
* Miracle vs. Hammerheads
<2018-08-01 Wed 18:00-21:00>
:PROPERTIES:
:ID:       ysryXP5ATNT5hq91zNrb9o9R@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Miracle vs. Hammerheads Miracle vs. Hammerheads

Follow on MiLB First Pitch  https //stza.co/+xMcs-2r

Shop  https //stza.co/+xMcs-W

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Miracle vs. Hammerheads
END:VALARM
DTSTART:20180801T230000Z
DTEND:20180802T020000Z
UID:ysryXP5ATNT5hq91zNrb9o9R@stanza.co
SUMMARY:Miracle vs. Hammerheads
DESCRIPTION:Miracle vs. Hammerheads\n\nFollow on MiLB First Pitch: https://stza.co/+xMcs-2r\n\nShop: https://stza.co/+xMcs-W\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144525Z
LAST-MODIFIED:20180213T144525Z
TRANSP:OPAQUE
END:VEVENT
* Miracle vs. Hammerheads
<2018-08-02 Thu 18:00-21:00>
:PROPERTIES:
:ID:       OzvqMhqFS2tiXPs5-BX0yiHz@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Miracle vs. Hammerheads Miracle vs. Hammerheads

Follow on MiLB First Pitch  https //stza.co/+xMcu-3K

Shop  https //stza.co/+xMcu-A

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Miracle vs. Hammerheads
END:VALARM
DTSTART:20180802T230000Z
DTEND:20180803T020000Z
UID:OzvqMhqFS2tiXPs5-BX0yiHz@stanza.co
SUMMARY:Miracle vs. Hammerheads
DESCRIPTION:Miracle vs. Hammerheads\n\nFollow on MiLB First Pitch: https://stza.co/+xMcu-3K\n\nShop: https://stza.co/+xMcu-A\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144525Z
LAST-MODIFIED:20180213T144525Z
TRANSP:OPAQUE
END:VEVENT
* Miracle vs. Fire Frogs
<2018-08-03 Fri 18:00-21:00>
:PROPERTIES:
:ID:       sANu328zKVbFaNfER6w5LOyt@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Miracle vs. Fire Frogs Miracle vs. Fire Frogs

Follow on MiLB First Pitch  https //stza.co/+xMcw-3C

Shop  https //stza.co/+xMcw-3W

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Miracle vs. Fire Frogs
END:VALARM
DTSTART:20180803T230000Z
DTEND:20180804T020000Z
UID:sANu328zKVbFaNfER6w5LOyt@stanza.co
SUMMARY:Miracle vs. Fire Frogs
DESCRIPTION:Miracle vs. Fire Frogs\n\nFollow on MiLB First Pitch: https://stza.co/+xMcw-3C\n\nShop: https://stza.co/+xMcw-3W\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144525Z
LAST-MODIFIED:20180213T144525Z
TRANSP:OPAQUE
END:VEVENT
* Miracle vs. Fire Frogs
<2018-08-04 Sat 17:00-20:00>
:PROPERTIES:
:ID:       7WevEqj-IC696O4Wd0VOlKew@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Miracle vs. Fire Frogs Miracle vs. Fire Frogs

Follow on MiLB First Pitch  https //stza.co/+xMcy-1g

Shop  https //stza.co/+xMcy-2

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Miracle vs. Fire Frogs
END:VALARM
DTSTART:20180804T220000Z
DTEND:20180805T010000Z
UID:7WevEqj-IC696O4Wd0VOlKew@stanza.co
SUMMARY:Miracle vs. Fire Frogs
DESCRIPTION:Miracle vs. Fire Frogs\n\nFollow on MiLB First Pitch: https://stza.co/+xMcy-1g\n\nShop: https://stza.co/+xMcy-2\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144525Z
LAST-MODIFIED:20180213T144525Z
TRANSP:OPAQUE
END:VEVENT
* Miracle vs. Fire Frogs
<2018-08-05 Sun 15:00-18:00>
:PROPERTIES:
:ID:       ltQzxI3VDCJIQvFWmuNRtHP2@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Miracle vs. Fire Frogs Miracle vs. Fire Frogs

Follow on MiLB First Pitch  https //stza.co/+xMcA-2O

Shop  https //stza.co/+xMcA-7

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Miracle vs. Fire Frogs
END:VALARM
DTSTART:20180805T200000Z
DTEND:20180805T230000Z
UID:ltQzxI3VDCJIQvFWmuNRtHP2@stanza.co
SUMMARY:Miracle vs. Fire Frogs
DESCRIPTION:Miracle vs. Fire Frogs\n\nFollow on MiLB First Pitch: https://stza.co/+xMcA-2O\n\nShop: https://stza.co/+xMcA-7\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144525Z
LAST-MODIFIED:20180213T144525Z
TRANSP:OPAQUE
END:VEVENT
* Miracle @ Flying Tigers
<2018-08-06 Mon 17:30-20:30>
:PROPERTIES:
:ID:       CltQJLYDe-fo5DN8IwJwBRzH@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Miracle @ Flying Tigers Miracle @ Flying Tigers

Follow on MiLB First Pitch  https //stza.co/+wKNo-3T

Shop  https //stza.co/+wKNo-1G

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Miracle @ Flying Tigers
END:VALARM
DTSTART:20180806T223000Z
DTEND:20180807T013000Z
UID:CltQJLYDe-fo5DN8IwJwBRzH@stanza.co
SUMMARY:Miracle @ Flying Tigers
DESCRIPTION:Miracle @ Flying Tigers\n\nFollow on MiLB First Pitch: https://stza.co/+wKNo-3T\n\nShop: https://stza.co/+wKNo-1G\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144525Z
LAST-MODIFIED:20180213T144525Z
TRANSP:OPAQUE
END:VEVENT
* Miracle @ Flying Tigers
<2018-08-07 Tue 17:30-20:30>
:PROPERTIES:
:ID:       NLtIH722X_S_KY6b5QPvCfN2@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Miracle @ Flying Tigers Miracle @ Flying Tigers

Follow on MiLB First Pitch  https //stza.co/+wKNp-X

Shop  https //stza.co/+wKNp-z

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Miracle @ Flying Tigers
END:VALARM
DTSTART:20180807T223000Z
DTEND:20180808T013000Z
UID:NLtIH722X_S_KY6b5QPvCfN2@stanza.co
SUMMARY:Miracle @ Flying Tigers
DESCRIPTION:Miracle @ Flying Tigers\n\nFollow on MiLB First Pitch: https://stza.co/+wKNp-X\n\nShop: https://stza.co/+wKNp-z\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144525Z
LAST-MODIFIED:20180213T144525Z
TRANSP:OPAQUE
END:VEVENT
* Miracle @ Flying Tigers
<2018-08-08 Wed 17:30-20:30>
:PROPERTIES:
:ID:       xE4wzK1W7qY5zVOMuwYu6flV@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Miracle @ Flying Tigers Miracle @ Flying Tigers

Follow on MiLB First Pitch  https //stza.co/+wKNq-$

Shop  https //stza.co/+wKNq-u

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Miracle @ Flying Tigers
END:VALARM
DTSTART:20180808T223000Z
DTEND:20180809T013000Z
UID:xE4wzK1W7qY5zVOMuwYu6flV@stanza.co
SUMMARY:Miracle @ Flying Tigers
DESCRIPTION:Miracle @ Flying Tigers\n\nFollow on MiLB First Pitch: https://stza.co/+wKNq-$\n\nShop: https://stza.co/+wKNq-u\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144525Z
LAST-MODIFIED:20180213T144525Z
TRANSP:OPAQUE
END:VEVENT
* Miracle @ Fire Frogs
<2018-08-09 Thu 17:31-20:31>
:PROPERTIES:
:ID:       CB0oHljuIxsZLuKlI__ThH_8@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Miracle @ Fire Frogs Miracle @ Fire Frogs

Buy tickets here  https //stza.co/~xWN8

Follow on MiLB First Pitch  https //stza.co/+xWN8-3d

Shop  https //stza.co/+xWN8-3L

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Miracle @ Fire Frogs
END:VALARM
DTSTART:20180809T223100Z
DTEND:20180810T013100Z
UID:CB0oHljuIxsZLuKlI__ThH_8@stanza.co
SUMMARY:Miracle @ Fire Frogs
DESCRIPTION:Miracle @ Fire Frogs\n\nBuy tickets here: https://stza.co/~xWN8\n\nFollow on MiLB First Pitch: https://stza.co/+xWN8-3d\n\nShop: https://stza.co/+xWN8-3L\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144525Z
LAST-MODIFIED:20180213T144525Z
TRANSP:OPAQUE
END:VEVENT
* Miracle @ Fire Frogs
<2018-08-10 Fri 17:31-20:31>
:PROPERTIES:
:ID:       TGfvtwMdltihVw0eSOF33maY@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Miracle @ Fire Frogs Miracle @ Fire Frogs

Buy tickets here  https //stza.co/~xWN9

Follow on MiLB First Pitch  https //stza.co/+xWN9-9

Shop  https //stza.co/+xWN9-3Z

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Miracle @ Fire Frogs
END:VALARM
DTSTART:20180810T223100Z
DTEND:20180811T013100Z
UID:TGfvtwMdltihVw0eSOF33maY@stanza.co
SUMMARY:Miracle @ Fire Frogs
DESCRIPTION:Miracle @ Fire Frogs\n\nBuy tickets here: https://stza.co/~xWN9\n\nFollow on MiLB First Pitch: https://stza.co/+xWN9-9\n\nShop: https://stza.co/+xWN9-3Z\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144525Z
LAST-MODIFIED:20180213T144525Z
TRANSP:OPAQUE
END:VEVENT
* Miracle @ Fire Frogs
<2018-08-11 Sat 17:31-20:31>
:PROPERTIES:
:ID:       675FQdXJaq49mEqzQRvNOpjG@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Miracle @ Fire Frogs Miracle @ Fire Frogs

Buy tickets here  https //stza.co/~xWNa

Follow on MiLB First Pitch  https //stza.co/+xWNa-2v

Shop  https //stza.co/+xWNa-1y

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Miracle @ Fire Frogs
END:VALARM
DTSTART:20180811T223100Z
DTEND:20180812T013100Z
UID:675FQdXJaq49mEqzQRvNOpjG@stanza.co
SUMMARY:Miracle @ Fire Frogs
DESCRIPTION:Miracle @ Fire Frogs\n\nBuy tickets here: https://stza.co/~xWNa\n\nFollow on MiLB First Pitch: https://stza.co/+xWNa-2v\n\nShop: https://stza.co/+xWNa-1y\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144525Z
LAST-MODIFIED:20180213T144525Z
TRANSP:OPAQUE
END:VEVENT
* Miracle @ Fire Frogs
<2018-08-12 Sun 10:00-13:00>
:PROPERTIES:
:ID:       h1j3U9B9vfy-miYGanmVADQ5@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Miracle @ Fire Frogs Miracle @ Fire Frogs

Buy tickets here  https //stza.co/~xWNb

Follow on MiLB First Pitch  https //stza.co/+xWNb-p

Shop  https //stza.co/+xWNb-1F

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Miracle @ Fire Frogs
END:VALARM
DTSTART:20180812T150000Z
DTEND:20180812T180000Z
UID:h1j3U9B9vfy-miYGanmVADQ5@stanza.co
SUMMARY:Miracle @ Fire Frogs
DESCRIPTION:Miracle @ Fire Frogs\n\nBuy tickets here: https://stza.co/~xWNb\n\nFollow on MiLB First Pitch: https://stza.co/+xWNb-p\n\nShop: https://stza.co/+xWNb-1F\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144525Z
LAST-MODIFIED:20180213T144525Z
TRANSP:OPAQUE
END:VEVENT
* Miracle vs. Stone Crabs
<2018-08-13 Mon 18:00-21:00>
:PROPERTIES:
:ID:       oKjt5aeH5ZLiSHkpFY7SHLgB@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Miracle vs. Stone Crabs Miracle vs. Stone Crabs

Follow on MiLB First Pitch  https //stza.co/+xMcC-1S

Shop  https //stza.co/+xMcC-3_

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Miracle vs. Stone Crabs
END:VALARM
DTSTART:20180813T230000Z
DTEND:20180814T020000Z
UID:oKjt5aeH5ZLiSHkpFY7SHLgB@stanza.co
SUMMARY:Miracle vs. Stone Crabs
DESCRIPTION:Miracle vs. Stone Crabs\n\nFollow on MiLB First Pitch: https://stza.co/+xMcC-1S\n\nShop: https://stza.co/+xMcC-3_\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144525Z
LAST-MODIFIED:20180213T144525Z
TRANSP:OPAQUE
END:VEVENT
* Miracle vs. Stone Crabs
<2018-08-14 Tue 18:00-21:00>
:PROPERTIES:
:ID:       MDXrZSCoSn9uqew-1gP7Cgx5@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Miracle vs. Stone Crabs Miracle vs. Stone Crabs

Follow on MiLB First Pitch  https //stza.co/+xMcE-2o

Shop  https //stza.co/+xMcE-K

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Miracle vs. Stone Crabs
END:VALARM
DTSTART:20180814T230000Z
DTEND:20180815T020000Z
UID:MDXrZSCoSn9uqew-1gP7Cgx5@stanza.co
SUMMARY:Miracle vs. Stone Crabs
DESCRIPTION:Miracle vs. Stone Crabs\n\nFollow on MiLB First Pitch: https://stza.co/+xMcE-2o\n\nShop: https://stza.co/+xMcE-K\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144525Z
LAST-MODIFIED:20180213T144525Z
TRANSP:OPAQUE
END:VEVENT
* Miracle vs. Stone Crabs
<2018-08-15 Wed 18:00-21:00>
:PROPERTIES:
:ID:       Dzpdb9eX2sYN8AxZmpz2ZgQ-@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Miracle vs. Stone Crabs Miracle vs. Stone Crabs

Follow on MiLB First Pitch  https //stza.co/+xMcG-1D

Shop  https //stza.co/+xMcG-23

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Miracle vs. Stone Crabs
END:VALARM
DTSTART:20180815T230000Z
DTEND:20180816T020000Z
UID:Dzpdb9eX2sYN8AxZmpz2ZgQ-@stanza.co
SUMMARY:Miracle vs. Stone Crabs
DESCRIPTION:Miracle vs. Stone Crabs\n\nFollow on MiLB First Pitch: https://stza.co/+xMcG-1D\n\nShop: https://stza.co/+xMcG-23\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144525Z
LAST-MODIFIED:20180213T144525Z
TRANSP:OPAQUE
END:VEVENT
* Miracle vs. Stone Crabs
<2018-08-16 Thu 18:00-21:00>
:PROPERTIES:
:ID:       lhkKSa8sP939nTegMfML6WX5@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Miracle vs. Stone Crabs Miracle vs. Stone Crabs

Follow on MiLB First Pitch  https //stza.co/+xMcH-1h

Shop  https //stza.co/+xMcH-17

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Miracle vs. Stone Crabs
END:VALARM
DTSTART:20180816T230000Z
DTEND:20180817T020000Z
UID:lhkKSa8sP939nTegMfML6WX5@stanza.co
SUMMARY:Miracle vs. Stone Crabs
DESCRIPTION:Miracle vs. Stone Crabs\n\nFollow on MiLB First Pitch: https://stza.co/+xMcH-1h\n\nShop: https://stza.co/+xMcH-17\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144525Z
LAST-MODIFIED:20180213T144525Z
TRANSP:OPAQUE
END:VEVENT
* Miracle vs. Threshers
<2018-08-17 Fri 18:00-21:00>
:PROPERTIES:
:ID:       qbWEz7JtRg7XPSMsHX-ppY3n@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Miracle vs. Threshers Miracle vs. Threshers

Follow on MiLB First Pitch  https //stza.co/+xMcK-2b

Shop  https //stza.co/+xMcK-B

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Miracle vs. Threshers
END:VALARM
DTSTART:20180817T230000Z
DTEND:20180818T020000Z
UID:qbWEz7JtRg7XPSMsHX-ppY3n@stanza.co
SUMMARY:Miracle vs. Threshers
DESCRIPTION:Miracle vs. Threshers\n\nFollow on MiLB First Pitch: https://stza.co/+xMcK-2b\n\nShop: https://stza.co/+xMcK-B\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144525Z
LAST-MODIFIED:20180213T144525Z
TRANSP:OPAQUE
END:VEVENT
* Miracle vs. Threshers
<2018-08-18 Sat 17:00-20:00>
:PROPERTIES:
:ID:       enqvRQ2INI0c8T-YOoGdeKkW@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Miracle vs. Threshers Miracle vs. Threshers

Follow on MiLB First Pitch  https //stza.co/+xMcM-1H

Shop  https //stza.co/+xMcM-36

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Miracle vs. Threshers
END:VALARM
DTSTART:20180818T220000Z
DTEND:20180819T010000Z
UID:enqvRQ2INI0c8T-YOoGdeKkW@stanza.co
SUMMARY:Miracle vs. Threshers
DESCRIPTION:Miracle vs. Threshers\n\nFollow on MiLB First Pitch: https://stza.co/+xMcM-1H\n\nShop: https://stza.co/+xMcM-36\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144525Z
LAST-MODIFIED:20180213T144525Z
TRANSP:OPAQUE
END:VEVENT
* Miracle vs. Threshers
<2018-08-19 Sun 15:00-18:00>
:PROPERTIES:
:ID:       NwwKifWFtyvQ5RhpJUbPeENu@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Miracle vs. Threshers Miracle vs. Threshers

Follow on MiLB First Pitch  https //stza.co/+xMcN-2Q

Shop  https //stza.co/+xMcN-18

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Miracle vs. Threshers
END:VALARM
DTSTART:20180819T200000Z
DTEND:20180819T230000Z
UID:NwwKifWFtyvQ5RhpJUbPeENu@stanza.co
SUMMARY:Miracle vs. Threshers
DESCRIPTION:Miracle vs. Threshers\n\nFollow on MiLB First Pitch: https://stza.co/+xMcN-2Q\n\nShop: https://stza.co/+xMcN-18\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144525Z
LAST-MODIFIED:20180213T144525Z
TRANSP:OPAQUE
END:VEVENT
* Miracle @ Cardinals
<2018-08-21 Tue>--<2018-08-20 Mon>
:PROPERTIES:
:ID:       zU4_Y_fJ5NNGPP0DuAwA1-p0@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Miracle @ Cardinals Miracle @ Cardinals

Buy tickets here  https //stza.co/~vMu2

Follow on MiLB First Pitch  https //stza.co/+vMu2-1i

Shop  https //stza.co/+vMu2-17

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Miracle @ Cardinals
END:VALARM
DTSTART;VALUE=DATE:20180821
DTEND;VALUE=DATE:20180821
UID:zU4_Y_fJ5NNGPP0DuAwA1-p0@stanza.co
SUMMARY:Miracle @ Cardinals
DESCRIPTION:Miracle @ Cardinals\n\nBuy tickets here: https://stza.co/~vMu2\n\nFollow on MiLB First Pitch: https://stza.co/+vMu2-1i\n\nShop: https://stza.co/+vMu2-17\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144525Z
LAST-MODIFIED:20180213T144525Z
TRANSP:OPAQUE
END:VEVENT
* Miracle @ Cardinals
<2018-08-22 Wed>--<2018-08-21 Tue>
:PROPERTIES:
:ID:       XAK7w_NkzgawVmQJmCOFz0JI@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Miracle @ Cardinals Miracle @ Cardinals

Buy tickets here  https //stza.co/~vMu3

Follow on MiLB First Pitch  https //stza.co/+vMu3-39

Shop  https //stza.co/+vMu3-20

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Miracle @ Cardinals
END:VALARM
DTSTART;VALUE=DATE:20180822
DTEND;VALUE=DATE:20180822
UID:XAK7w_NkzgawVmQJmCOFz0JI@stanza.co
SUMMARY:Miracle @ Cardinals
DESCRIPTION:Miracle @ Cardinals\n\nBuy tickets here: https://stza.co/~vMu3\n\nFollow on MiLB First Pitch: https://stza.co/+vMu3-39\n\nShop: https://stza.co/+vMu3-20\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144525Z
LAST-MODIFIED:20180213T144525Z
TRANSP:OPAQUE
END:VEVENT
* Miracle @ Cardinals
<2018-08-23 Thu>--<2018-08-22 Wed>
:PROPERTIES:
:ID:       w1ip85WqgcuHLO8wSjQyAgG-@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Miracle @ Cardinals Miracle @ Cardinals

Buy tickets here  https //stza.co/~vMu4

Follow on MiLB First Pitch  https //stza.co/+vMu4-1S

Shop  https //stza.co/+vMu4-13

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Miracle @ Cardinals
END:VALARM
DTSTART;VALUE=DATE:20180823
DTEND;VALUE=DATE:20180823
UID:w1ip85WqgcuHLO8wSjQyAgG-@stanza.co
SUMMARY:Miracle @ Cardinals
DESCRIPTION:Miracle @ Cardinals\n\nBuy tickets here: https://stza.co/~vMu4\n\nFollow on MiLB First Pitch: https://stza.co/+vMu4-1S\n\nShop: https://stza.co/+vMu4-13\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144525Z
LAST-MODIFIED:20180213T144525Z
TRANSP:OPAQUE
END:VEVENT
* Miracle @ Mets
<2018-08-24 Fri 17:30-20:30>
:PROPERTIES:
:ID:       06XlC9YD8yAHJiN-4m9utC4B@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Miracle @ Mets Miracle @ Mets

Follow on MiLB First Pitch  https //stza.co/+vMu8-2q

Shop  https //stza.co/+vMu8-4

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Miracle @ Mets
END:VALARM
DTSTART:20180824T223000Z
DTEND:20180825T013000Z
UID:06XlC9YD8yAHJiN-4m9utC4B@stanza.co
SUMMARY:Miracle @ Mets
DESCRIPTION:Miracle @ Mets\n\nFollow on MiLB First Pitch: https://stza.co/+vMu8-2q\n\nShop: https://stza.co/+vMu8-4\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144525Z
LAST-MODIFIED:20180213T144525Z
TRANSP:OPAQUE
END:VEVENT
* Miracle @ Mets
<2018-08-25 Sat 17:30-20:30>
:PROPERTIES:
:ID:       69U4m_iaIk1jcdkhIMxTQ2Ln@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Miracle @ Mets Miracle @ Mets

Follow on MiLB First Pitch  https //stza.co/+vMu9-2P

Shop  https //stza.co/+vMu9-1p

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Miracle @ Mets
END:VALARM
DTSTART:20180825T223000Z
DTEND:20180826T013000Z
UID:69U4m_iaIk1jcdkhIMxTQ2Ln@stanza.co
SUMMARY:Miracle @ Mets
DESCRIPTION:Miracle @ Mets\n\nFollow on MiLB First Pitch: https://stza.co/+vMu9-2P\n\nShop: https://stza.co/+vMu9-1p\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144525Z
LAST-MODIFIED:20180213T144525Z
TRANSP:OPAQUE
END:VEVENT
* Miracle @ Mets
<2018-08-26 Sun 11:00-14:00>
:PROPERTIES:
:ID:       m2UpSCNZMiFJC2tCTxRMPqva@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Miracle @ Mets Miracle @ Mets

Follow on MiLB First Pitch  https //stza.co/+widj-2e

Shop  https //stza.co/+widj-1N

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Miracle @ Mets
END:VALARM
DTSTART:20180826T160000Z
DTEND:20180826T190000Z
UID:m2UpSCNZMiFJC2tCTxRMPqva@stanza.co
SUMMARY:Miracle @ Mets
DESCRIPTION:Miracle @ Mets\n\nFollow on MiLB First Pitch: https://stza.co/+widj-2e\n\nShop: https://stza.co/+widj-1N\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144525Z
LAST-MODIFIED:20180213T144525Z
TRANSP:OPAQUE
END:VEVENT
* Miracle vs. Marauders
<2018-08-27 Mon 18:00-21:00>
:PROPERTIES:
:ID:       D4lvxSmLt2wFzAFZSqlNBhI9@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Miracle vs. Marauders Miracle vs. Marauders

Follow on MiLB First Pitch  https //stza.co/+xMcQ-2N

Shop  https //stza.co/+xMcQ-2L

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Miracle vs. Marauders
END:VALARM
DTSTART:20180827T230000Z
DTEND:20180828T020000Z
UID:D4lvxSmLt2wFzAFZSqlNBhI9@stanza.co
SUMMARY:Miracle vs. Marauders
DESCRIPTION:Miracle vs. Marauders\n\nFollow on MiLB First Pitch: https://stza.co/+xMcQ-2N\n\nShop: https://stza.co/+xMcQ-2L\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144525Z
LAST-MODIFIED:20180213T144525Z
TRANSP:OPAQUE
END:VEVENT
* Miracle vs. Marauders
<2018-08-28 Tue 18:00-21:00>
:PROPERTIES:
:ID:       ZGu257Yf28oUSzZfpHtspFLC@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Miracle vs. Marauders Miracle vs. Marauders

Follow on MiLB First Pitch  https //stza.co/+xMcR-1b

Shop  https //stza.co/+xMcR-i

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Miracle vs. Marauders
END:VALARM
DTSTART:20180828T230000Z
DTEND:20180829T020000Z
UID:ZGu257Yf28oUSzZfpHtspFLC@stanza.co
SUMMARY:Miracle vs. Marauders
DESCRIPTION:Miracle vs. Marauders\n\nFollow on MiLB First Pitch: https://stza.co/+xMcR-1b\n\nShop: https://stza.co/+xMcR-i\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144525Z
LAST-MODIFIED:20180213T144525Z
TRANSP:OPAQUE
END:VEVENT
* Miracle vs. Marauders
<2018-08-29 Wed 18:00-21:00>
:PROPERTIES:
:ID:       8h3EyDkO97_9TYrL6jMPoQbE@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Miracle vs. Marauders Miracle vs. Marauders

Follow on MiLB First Pitch  https //stza.co/+xMcT-2n

Shop  https //stza.co/+xMcT-3a

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Miracle vs. Marauders
END:VALARM
DTSTART:20180829T230000Z
DTEND:20180830T020000Z
UID:8h3EyDkO97_9TYrL6jMPoQbE@stanza.co
SUMMARY:Miracle vs. Marauders
DESCRIPTION:Miracle vs. Marauders\n\nFollow on MiLB First Pitch: https://stza.co/+xMcT-2n\n\nShop: https://stza.co/+xMcT-3a\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144525Z
LAST-MODIFIED:20180213T144525Z
TRANSP:OPAQUE
END:VEVENT
* Miracle vs. Marauders
<2018-08-30 Thu 18:00-21:00>
:PROPERTIES:
:ID:       XHDEXNRx1HdUdmuBFyxTNIZR@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Miracle vs. Marauders Miracle vs. Marauders

Follow on MiLB First Pitch  https //stza.co/+xMcV-1x

Shop  https //stza.co/+xMcV-3R

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Miracle vs. Marauders
END:VALARM
DTSTART:20180830T230000Z
DTEND:20180831T020000Z
UID:XHDEXNRx1HdUdmuBFyxTNIZR@stanza.co
SUMMARY:Miracle vs. Marauders
DESCRIPTION:Miracle vs. Marauders\n\nFollow on MiLB First Pitch: https://stza.co/+xMcV-1x\n\nShop: https://stza.co/+xMcV-3R\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144525Z
LAST-MODIFIED:20180213T144525Z
TRANSP:OPAQUE
END:VEVENT
* Miracle vs. Threshers
<2018-08-31 Fri 18:00-21:00>
:PROPERTIES:
:ID:       6BHWSfm1H2Tz7l__cI0CP3fF@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Miracle vs. Threshers Miracle vs. Threshers

Follow on MiLB First Pitch  https //stza.co/+xMcX-2X

Shop  https //stza.co/+xMcX-1l

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Miracle vs. Threshers
END:VALARM
DTSTART:20180831T230000Z
DTEND:20180901T020000Z
UID:6BHWSfm1H2Tz7l__cI0CP3fF@stanza.co
SUMMARY:Miracle vs. Threshers
DESCRIPTION:Miracle vs. Threshers\n\nFollow on MiLB First Pitch: https://stza.co/+xMcX-2X\n\nShop: https://stza.co/+xMcX-1l\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144525Z
LAST-MODIFIED:20180213T144525Z
TRANSP:OPAQUE
END:VEVENT
* Miracle vs. Threshers
<2018-09-01 Sat 17:00-20:00>
:PROPERTIES:
:ID:       949idq0nu0wvmjDCS3bH4XP4@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Miracle vs. Threshers Miracle vs. Threshers

Follow on MiLB First Pitch  https //stza.co/+xMc_-14

Shop  https //stza.co/+xMc_-3j

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Miracle vs. Threshers
END:VALARM
DTSTART:20180901T220000Z
DTEND:20180902T010000Z
UID:949idq0nu0wvmjDCS3bH4XP4@stanza.co
SUMMARY:Miracle vs. Threshers
DESCRIPTION:Miracle vs. Threshers\n\nFollow on MiLB First Pitch: https://stza.co/+xMc_-14\n\nShop: https://stza.co/+xMc_-3j\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144525Z
LAST-MODIFIED:20180213T144525Z
TRANSP:OPAQUE
END:VEVENT
* Miracle vs. Threshers
<2018-09-02 Sun 11:00-14:00>
:PROPERTIES:
:ID:       hB36RJKA3zjW37iZopOu5oz8@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Miracle vs. Threshers Miracle vs. Threshers

Follow on MiLB First Pitch  https //stza.co/+xMc$-l

Shop  https //stza.co/+xMc$-1K

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Miracle vs. Threshers
END:VALARM
DTSTART:20180902T160000Z
DTEND:20180902T190000Z
UID:hB36RJKA3zjW37iZopOu5oz8@stanza.co
SUMMARY:Miracle vs. Threshers
DESCRIPTION:Miracle vs. Threshers\n\nFollow on MiLB First Pitch: https://stza.co/+xMc$-l\n\nShop: https://stza.co/+xMc$-1K\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144525Z
LAST-MODIFIED:20180213T144525Z
TRANSP:OPAQUE
END:VEVENT
