#+TITLE:       Main Google calendar entries
#+AUTHOR:      Eric S Fraga
#+EMAIL:       e.fraga@ucl.ac.uk
#+DESCRIPTION: converted using the ical2org awk script
#+CATEGORY:    google
#+STARTUP:     hidestars
#+STARTUP:     overview

* COMMENT original iCal preamble

* Canadians @ Emeralds
<2018-06-15 Fri 21:05>--<2018-06-16 Sat 00:05>
:PROPERTIES:
:ID:       kVxGgIYQoxQs_MhTqkthDGjd@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Canadians @ Emeralds Canadians @ Emeralds

Follow on MiLB First Pitch  https //stza.co/+xWPD-3D

Shop  https //stza.co/+xWPD-1F

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Canadians @ Emeralds
END:VALARM
DTSTART:20180616T020500Z
DTEND:20180616T050500Z
UID:kVxGgIYQoxQs_MhTqkthDGjd@stanza.co
SUMMARY:Canadians @ Emeralds
DESCRIPTION:Canadians @ Emeralds\n\nFollow on MiLB First Pitch: https://stza.co/+xWPD-3D\n\nShop: https://stza.co/+xWPD-1F\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144603Z
LAST-MODIFIED:20180213T144603Z
TRANSP:OPAQUE
END:VEVENT
* Canadians @ Emeralds
<2018-06-16 Sat 21:05>--<2018-06-17 Sun 00:05>
:PROPERTIES:
:ID:       CEqZCpbhA3Je8Q4tbyaVQrYh@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Canadians @ Emeralds Canadians @ Emeralds

Follow on MiLB First Pitch  https //stza.co/+xWPE-1k

Shop  https //stza.co/+xWPE-29

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Canadians @ Emeralds
END:VALARM
DTSTART:20180617T020500Z
DTEND:20180617T050500Z
UID:CEqZCpbhA3Je8Q4tbyaVQrYh@stanza.co
SUMMARY:Canadians @ Emeralds
DESCRIPTION:Canadians @ Emeralds\n\nFollow on MiLB First Pitch: https://stza.co/+xWPE-1k\n\nShop: https://stza.co/+xWPE-29\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144603Z
LAST-MODIFIED:20180213T144603Z
TRANSP:OPAQUE
END:VEVENT
* Canadians @ Emeralds
<2018-06-17 Sun 19:05-22:05>
:PROPERTIES:
:ID:       dZlRf2AZQC22ddJrGUoNioLE@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Canadians @ Emeralds Canadians @ Emeralds

Follow on MiLB First Pitch  https //stza.co/+xWPF-3K

Shop  https //stza.co/+xWPF-k

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Canadians @ Emeralds
END:VALARM
DTSTART:20180618T000500Z
DTEND:20180618T030500Z
UID:dZlRf2AZQC22ddJrGUoNioLE@stanza.co
SUMMARY:Canadians @ Emeralds
DESCRIPTION:Canadians @ Emeralds\n\nFollow on MiLB First Pitch: https://stza.co/+xWPF-3K\n\nShop: https://stza.co/+xWPF-k\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144603Z
LAST-MODIFIED:20180213T144603Z
TRANSP:OPAQUE
END:VEVENT
* Canadians @ Emeralds
<2018-06-18 Mon 21:05>--<2018-06-19 Tue 00:05>
:PROPERTIES:
:ID:       LCGjEyOT_3BvVBMyRxrE_gqc@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Canadians @ Emeralds Canadians @ Emeralds

Follow on MiLB First Pitch  https //stza.co/+xWPG-38

Shop  https //stza.co/+xWPG-1z

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Canadians @ Emeralds
END:VALARM
DTSTART:20180619T020500Z
DTEND:20180619T050500Z
UID:LCGjEyOT_3BvVBMyRxrE_gqc@stanza.co
SUMMARY:Canadians @ Emeralds
DESCRIPTION:Canadians @ Emeralds\n\nFollow on MiLB First Pitch: https://stza.co/+xWPG-38\n\nShop: https://stza.co/+xWPG-1z\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144603Z
LAST-MODIFIED:20180213T144603Z
TRANSP:OPAQUE
END:VEVENT
* Canadians @ Emeralds
<2018-06-19 Tue 21:05>--<2018-06-20 Wed 00:05>
:PROPERTIES:
:ID:       xIlVtRZGaEBHmXxoTxlaAnut@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Canadians @ Emeralds Canadians @ Emeralds

Follow on MiLB First Pitch  https //stza.co/+xWPH-1J

Shop  https //stza.co/+xWPH-1

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Canadians @ Emeralds
END:VALARM
DTSTART:20180620T020500Z
DTEND:20180620T050500Z
UID:xIlVtRZGaEBHmXxoTxlaAnut@stanza.co
SUMMARY:Canadians @ Emeralds
DESCRIPTION:Canadians @ Emeralds\n\nFollow on MiLB First Pitch: https://stza.co/+xWPH-1J\n\nShop: https://stza.co/+xWPH-1\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144603Z
LAST-MODIFIED:20180213T144603Z
TRANSP:OPAQUE
END:VEVENT
* Canadians vs. AquaSox
<2018-06-20 Wed 21:05>--<2018-06-21 Thu 00:05>
:PROPERTIES:
:ID:       lwf5jA7GrHYvZnckJCQcEDK1@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Canadians vs. AquaSox Canadians vs. AquaSox

Follow on MiLB First Pitch  https //stza.co/+xXVo-2_

Shop  https //stza.co/+xXVo-Q

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Canadians vs. AquaSox
END:VALARM
DTSTART:20180621T020500Z
DTEND:20180621T050500Z
UID:lwf5jA7GrHYvZnckJCQcEDK1@stanza.co
SUMMARY:Canadians vs. AquaSox
DESCRIPTION:Canadians vs. AquaSox\n\nFollow on MiLB First Pitch: https://stza.co/+xXVo-2_\n\nShop: https://stza.co/+xXVo-Q\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144603Z
LAST-MODIFIED:20180213T144603Z
TRANSP:OPAQUE
END:VEVENT
* Canadians vs. AquaSox
<2018-06-21 Thu 21:05>--<2018-06-22 Fri 00:05>
:PROPERTIES:
:ID:       Wt97j-m3TTiXGsPhnd5JNTEY@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Canadians vs. AquaSox Canadians vs. AquaSox

Follow on MiLB First Pitch  https //stza.co/+xXVq-3K

Shop  https //stza.co/+xXVq-3v

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Canadians vs. AquaSox
END:VALARM
DTSTART:20180622T020500Z
DTEND:20180622T050500Z
UID:Wt97j-m3TTiXGsPhnd5JNTEY@stanza.co
SUMMARY:Canadians vs. AquaSox
DESCRIPTION:Canadians vs. AquaSox\n\nFollow on MiLB First Pitch: https://stza.co/+xXVq-3K\n\nShop: https://stza.co/+xXVq-3v\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144603Z
LAST-MODIFIED:20180213T144603Z
TRANSP:OPAQUE
END:VEVENT
* Canadians vs. AquaSox
<2018-06-22 Fri 15:05-18:05>
:PROPERTIES:
:ID:       X45EAKBxxeuuNSc5K5BxoJrR@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Canadians vs. AquaSox Canadians vs. AquaSox

Follow on MiLB First Pitch  https //stza.co/+xXVs-1i

Shop  https //stza.co/+xXVs-14

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Canadians vs. AquaSox
END:VALARM
DTSTART:20180622T200500Z
DTEND:20180622T230500Z
UID:X45EAKBxxeuuNSc5K5BxoJrR@stanza.co
SUMMARY:Canadians vs. AquaSox
DESCRIPTION:Canadians vs. AquaSox\n\nFollow on MiLB First Pitch: https://stza.co/+xXVs-1i\n\nShop: https://stza.co/+xXVs-14\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144603Z
LAST-MODIFIED:20180213T144603Z
TRANSP:OPAQUE
END:VEVENT
* Canadians @ Indians
<2018-06-23 Sat 20:30-23:30>
:PROPERTIES:
:ID:       WX7fVEVUWJmj9Epl3x0SyUqj@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Canadians @ Indians Canadians @ Indians

Follow on MiLB First Pitch  https //stza.co/+xCdM-3_

Shop  https //stza.co/+xCdM-N

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Canadians @ Indians
END:VALARM
DTSTART:20180624T013000Z
DTEND:20180624T043000Z
UID:WX7fVEVUWJmj9Epl3x0SyUqj@stanza.co
SUMMARY:Canadians @ Indians
DESCRIPTION:Canadians @ Indians\n\nFollow on MiLB First Pitch: https://stza.co/+xCdM-3_\n\nShop: https://stza.co/+xCdM-N\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144603Z
LAST-MODIFIED:20180213T144603Z
TRANSP:OPAQUE
END:VEVENT
* Canadians @ Indians
<2018-06-24 Sun 17:30-20:30>
:PROPERTIES:
:ID:       _c0y77IafunpLuC4nRsIHnw_@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Canadians @ Indians Canadians @ Indians

Follow on MiLB First Pitch  https //stza.co/+xCdP-2u

Shop  https //stza.co/+xCdP-3W

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Canadians @ Indians
END:VALARM
DTSTART:20180624T223000Z
DTEND:20180625T013000Z
UID:_c0y77IafunpLuC4nRsIHnw_@stanza.co
SUMMARY:Canadians @ Indians
DESCRIPTION:Canadians @ Indians\n\nFollow on MiLB First Pitch: https://stza.co/+xCdP-2u\n\nShop: https://stza.co/+xCdP-3W\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144603Z
LAST-MODIFIED:20180213T144603Z
TRANSP:OPAQUE
END:VEVENT
* Canadians @ Indians
<2018-06-25 Mon 20:30-23:30>
:PROPERTIES:
:ID:       iM3x7iLTDeCrrKt63LBWkK2p@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Canadians @ Indians Canadians @ Indians

Follow on MiLB First Pitch  https //stza.co/+xCdS-j

Shop  https //stza.co/+xCdS-2B

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Canadians @ Indians
END:VALARM
DTSTART:20180626T013000Z
DTEND:20180626T043000Z
UID:iM3x7iLTDeCrrKt63LBWkK2p@stanza.co
SUMMARY:Canadians @ Indians
DESCRIPTION:Canadians @ Indians\n\nFollow on MiLB First Pitch: https://stza.co/+xCdS-j\n\nShop: https://stza.co/+xCdS-2B\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144603Z
LAST-MODIFIED:20180213T144603Z
TRANSP:OPAQUE
END:VEVENT
* Canadians vs. Dust Devils
<2018-06-26 Tue 21:05>--<2018-06-27 Wed 00:05>
:PROPERTIES:
:ID:       _-HYMFO8rCZyCH4YggzX6r5K@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Canadians vs. Dust Devils Canadians vs. Dust Devils

Follow on MiLB First Pitch  https //stza.co/+xXVt-f

Shop  https //stza.co/+xXVt-i

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Canadians vs. Dust Devils
END:VALARM
DTSTART:20180627T020500Z
DTEND:20180627T050500Z
UID:_-HYMFO8rCZyCH4YggzX6r5K@stanza.co
SUMMARY:Canadians vs. Dust Devils
DESCRIPTION:Canadians vs. Dust Devils\n\nFollow on MiLB First Pitch: https://stza.co/+xXVt-f\n\nShop: https://stza.co/+xXVt-i\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144603Z
LAST-MODIFIED:20180213T144603Z
TRANSP:OPAQUE
END:VEVENT
* Canadians vs. Dust Devils
<2018-06-27 Wed 21:05>--<2018-06-28 Thu 00:05>
:PROPERTIES:
:ID:       Oq3BXQzHL4Oz1D0Bkb-CTFIk@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Canadians vs. Dust Devils Canadians vs. Dust Devils

Follow on MiLB First Pitch  https //stza.co/+xXVv-3h

Shop  https //stza.co/+xXVv-1Q

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Canadians vs. Dust Devils
END:VALARM
DTSTART:20180628T020500Z
DTEND:20180628T050500Z
UID:Oq3BXQzHL4Oz1D0Bkb-CTFIk@stanza.co
SUMMARY:Canadians vs. Dust Devils
DESCRIPTION:Canadians vs. Dust Devils\n\nFollow on MiLB First Pitch: https://stza.co/+xXVv-3h\n\nShop: https://stza.co/+xXVv-1Q\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144603Z
LAST-MODIFIED:20180213T144603Z
TRANSP:OPAQUE
END:VEVENT
* Canadians vs. Dust Devils
<2018-06-28 Thu 15:05-18:05>
:PROPERTIES:
:ID:       mX3yY-CtnCOZ6b9vv-LZVmIf@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Canadians vs. Dust Devils Canadians vs. Dust Devils

Follow on MiLB First Pitch  https //stza.co/+xXVx-K

Shop  https //stza.co/+xXVx-1s

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Canadians vs. Dust Devils
END:VALARM
DTSTART:20180628T200500Z
DTEND:20180628T230500Z
UID:mX3yY-CtnCOZ6b9vv-LZVmIf@stanza.co
SUMMARY:Canadians vs. Dust Devils
DESCRIPTION:Canadians vs. Dust Devils\n\nFollow on MiLB First Pitch: https://stza.co/+xXVx-K\n\nShop: https://stza.co/+xXVx-1s\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144603Z
LAST-MODIFIED:20180213T144603Z
TRANSP:OPAQUE
END:VEVENT
* Canadians vs. Volcanoes
<2018-06-29 Fri 21:05>--<2018-06-30 Sat 00:05>
:PROPERTIES:
:ID:       fZv5gBkg1CSRoDIBZPPABN69@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Canadians vs. Volcanoes Canadians vs. Volcanoes

Follow on MiLB First Pitch  https //stza.co/+xXVA-2G

Shop  https //stza.co/+xXVA-N

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Canadians vs. Volcanoes
END:VALARM
DTSTART:20180630T020500Z
DTEND:20180630T050500Z
UID:fZv5gBkg1CSRoDIBZPPABN69@stanza.co
SUMMARY:Canadians vs. Volcanoes
DESCRIPTION:Canadians vs. Volcanoes\n\nFollow on MiLB First Pitch: https://stza.co/+xXVA-2G\n\nShop: https://stza.co/+xXVA-N\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144603Z
LAST-MODIFIED:20180213T144603Z
TRANSP:OPAQUE
END:VEVENT
* Canadians vs. Volcanoes
<2018-06-30 Sat 21:05>--<2018-07-01 Sun 00:05>
:PROPERTIES:
:ID:       BFvQK37Gm1dz6LzmJ5PeJWJe@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Canadians vs. Volcanoes Canadians vs. Volcanoes

Follow on MiLB First Pitch  https //stza.co/+xXVC-2Q

Shop  https //stza.co/+xXVC-n

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Canadians vs. Volcanoes
END:VALARM
DTSTART:20180701T020500Z
DTEND:20180701T050500Z
UID:BFvQK37Gm1dz6LzmJ5PeJWJe@stanza.co
SUMMARY:Canadians vs. Volcanoes
DESCRIPTION:Canadians vs. Volcanoes\n\nFollow on MiLB First Pitch: https://stza.co/+xXVC-2Q\n\nShop: https://stza.co/+xXVC-n\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144603Z
LAST-MODIFIED:20180213T144603Z
TRANSP:OPAQUE
END:VEVENT
* Canadians vs. Volcanoes
<2018-07-01 Sun 15:05-18:05>
:PROPERTIES:
:ID:       hGvFcF7JXUSO3BbDprjAFj_S@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Canadians vs. Volcanoes Canadians vs. Volcanoes

Follow on MiLB First Pitch  https //stza.co/+xXVE-31

Shop  https //stza.co/+xXVE-1K

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Canadians vs. Volcanoes
END:VALARM
DTSTART:20180701T200500Z
DTEND:20180701T230500Z
UID:hGvFcF7JXUSO3BbDprjAFj_S@stanza.co
SUMMARY:Canadians vs. Volcanoes
DESCRIPTION:Canadians vs. Volcanoes\n\nFollow on MiLB First Pitch: https://stza.co/+xXVE-31\n\nShop: https://stza.co/+xXVE-1K\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144603Z
LAST-MODIFIED:20180213T144603Z
TRANSP:OPAQUE
END:VEVENT
* Canadians vs. Volcanoes
<2018-07-02 Mon 15:05-18:05>
:PROPERTIES:
:ID:       4dKSvB6ATkH7ty0ABn9DXilf@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Canadians vs. Volcanoes Canadians vs. Volcanoes

Follow on MiLB First Pitch  https //stza.co/+xXVG-w

Shop  https //stza.co/+xXVG-E

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Canadians vs. Volcanoes
END:VALARM
DTSTART:20180702T200500Z
DTEND:20180702T230500Z
UID:4dKSvB6ATkH7ty0ABn9DXilf@stanza.co
SUMMARY:Canadians vs. Volcanoes
DESCRIPTION:Canadians vs. Volcanoes\n\nFollow on MiLB First Pitch: https://stza.co/+xXVG-w\n\nShop: https://stza.co/+xXVG-E\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144603Z
LAST-MODIFIED:20180213T144603Z
TRANSP:OPAQUE
END:VEVENT
* Canadians vs. Volcanoes
<2018-07-03 Tue 21:05>--<2018-07-04 Wed 00:05>
:PROPERTIES:
:ID:       9jB6SGj7TOBjPXEViIoHiYfQ@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Canadians vs. Volcanoes Canadians vs. Volcanoes

Follow on MiLB First Pitch  https //stza.co/+xXVI-P

Shop  https //stza.co/+xXVI-1X

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Canadians vs. Volcanoes
END:VALARM
DTSTART:20180704T020500Z
DTEND:20180704T050500Z
UID:9jB6SGj7TOBjPXEViIoHiYfQ@stanza.co
SUMMARY:Canadians vs. Volcanoes
DESCRIPTION:Canadians vs. Volcanoes\n\nFollow on MiLB First Pitch: https://stza.co/+xXVI-P\n\nShop: https://stza.co/+xXVI-1X\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144603Z
LAST-MODIFIED:20180213T144603Z
TRANSP:OPAQUE
END:VEVENT
* Canadians @ AquaSox
<2018-07-04 Wed 21:05>--<2018-07-05 Thu 00:05>
:PROPERTIES:
:ID:       gEiSg-LWp2kwgB9ozYftXs8r@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Canadians @ AquaSox Canadians @ AquaSox

Follow on MiLB First Pitch  https //stza.co/+vOgp-1y

Shop  https //stza.co/+vOgp-t

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Canadians @ AquaSox
END:VALARM
DTSTART:20180705T020500Z
DTEND:20180705T050500Z
UID:gEiSg-LWp2kwgB9ozYftXs8r@stanza.co
SUMMARY:Canadians @ AquaSox
DESCRIPTION:Canadians @ AquaSox\n\nFollow on MiLB First Pitch: https://stza.co/+vOgp-1y\n\nShop: https://stza.co/+vOgp-t\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144603Z
LAST-MODIFIED:20180213T144603Z
TRANSP:OPAQUE
END:VEVENT
* Canadians @ AquaSox
<2018-07-05 Thu 21:05>--<2018-07-06 Fri 00:05>
:PROPERTIES:
:ID:       2f8hKQrMdgkUhS0FDGIpwT2n@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Canadians @ AquaSox Canadians @ AquaSox

Follow on MiLB First Pitch  https //stza.co/+vOgq-1H

Shop  https //stza.co/+vOgq-3B

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Canadians @ AquaSox
END:VALARM
DTSTART:20180706T020500Z
DTEND:20180706T050500Z
UID:2f8hKQrMdgkUhS0FDGIpwT2n@stanza.co
SUMMARY:Canadians @ AquaSox
DESCRIPTION:Canadians @ AquaSox\n\nFollow on MiLB First Pitch: https://stza.co/+vOgq-1H\n\nShop: https://stza.co/+vOgq-3B\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144603Z
LAST-MODIFIED:20180213T144603Z
TRANSP:OPAQUE
END:VEVENT
* Canadians @ AquaSox
<2018-07-06 Fri 21:05>--<2018-07-07 Sat 00:05>
:PROPERTIES:
:ID:       S24isvsn8kURt1eeNfSF6xKs@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Canadians @ AquaSox Canadians @ AquaSox

Follow on MiLB First Pitch  https //stza.co/+vOgr-B

Shop  https //stza.co/+vOgr-j

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Canadians @ AquaSox
END:VALARM
DTSTART:20180707T020500Z
DTEND:20180707T050500Z
UID:S24isvsn8kURt1eeNfSF6xKs@stanza.co
SUMMARY:Canadians @ AquaSox
DESCRIPTION:Canadians @ AquaSox\n\nFollow on MiLB First Pitch: https://stza.co/+vOgr-B\n\nShop: https://stza.co/+vOgr-j\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144603Z
LAST-MODIFIED:20180213T144603Z
TRANSP:OPAQUE
END:VEVENT
* Canadians vs. Indians
<2018-07-07 Sat 21:05>--<2018-07-08 Sun 00:05>
:PROPERTIES:
:ID:       Q-04elLuQkUZTIj6d3k-kjCL@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Canadians vs. Indians Canadians vs. Indians

Follow on MiLB First Pitch  https //stza.co/+xXVJ-31

Shop  https //stza.co/+xXVJ-1V

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Canadians vs. Indians
END:VALARM
DTSTART:20180708T020500Z
DTEND:20180708T050500Z
UID:Q-04elLuQkUZTIj6d3k-kjCL@stanza.co
SUMMARY:Canadians vs. Indians
DESCRIPTION:Canadians vs. Indians\n\nFollow on MiLB First Pitch: https://stza.co/+xXVJ-31\n\nShop: https://stza.co/+xXVJ-1V\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144603Z
LAST-MODIFIED:20180213T144603Z
TRANSP:OPAQUE
END:VEVENT
* Canadians vs. Indians
<2018-07-08 Sun 15:05-18:05>
:PROPERTIES:
:ID:       yXAjcYHyu9v2oLOkrlKeqB1D@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Canadians vs. Indians Canadians vs. Indians

Follow on MiLB First Pitch  https //stza.co/+xXVL-k

Shop  https //stza.co/+xXVL-2S

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Canadians vs. Indians
END:VALARM
DTSTART:20180708T200500Z
DTEND:20180708T230500Z
UID:yXAjcYHyu9v2oLOkrlKeqB1D@stanza.co
SUMMARY:Canadians vs. Indians
DESCRIPTION:Canadians vs. Indians\n\nFollow on MiLB First Pitch: https://stza.co/+xXVL-k\n\nShop: https://stza.co/+xXVL-2S\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144603Z
LAST-MODIFIED:20180213T144603Z
TRANSP:OPAQUE
END:VEVENT
* Canadians vs. Indians
<2018-07-09 Mon 21:05>--<2018-07-10 Tue 00:05>
:PROPERTIES:
:ID:       L6NLZEGakucdei-hMhCS8yx_@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Canadians vs. Indians Canadians vs. Indians

Follow on MiLB First Pitch  https //stza.co/+xXVN-12

Shop  https //stza.co/+xXVN-q

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Canadians vs. Indians
END:VALARM
DTSTART:20180710T020500Z
DTEND:20180710T050500Z
UID:L6NLZEGakucdei-hMhCS8yx_@stanza.co
SUMMARY:Canadians vs. Indians
DESCRIPTION:Canadians vs. Indians\n\nFollow on MiLB First Pitch: https://stza.co/+xXVN-12\n\nShop: https://stza.co/+xXVN-q\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144603Z
LAST-MODIFIED:20180213T144603Z
TRANSP:OPAQUE
END:VEVENT
* Canadians @ Hawks
<2018-07-11 Wed 20:15-23:15>
:PROPERTIES:
:ID:       OsYdV96nR8OhTFpMusNMoYWK@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Canadians @ Hawks Canadians @ Hawks

Follow on MiLB First Pitch  https //stza.co/+xCdv-1m

Shop  https //stza.co/+xCdv-26

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Canadians @ Hawks
END:VALARM
DTSTART:20180712T011500Z
DTEND:20180712T041500Z
UID:OsYdV96nR8OhTFpMusNMoYWK@stanza.co
SUMMARY:Canadians @ Hawks
DESCRIPTION:Canadians @ Hawks\n\nFollow on MiLB First Pitch: https://stza.co/+xCdv-1m\n\nShop: https://stza.co/+xCdv-26\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144603Z
LAST-MODIFIED:20180213T144603Z
TRANSP:OPAQUE
END:VEVENT
* Canadians @ Hawks
<2018-07-12 Thu 20:15-23:15>
:PROPERTIES:
:ID:       ZYLXlaPYbwTvqGzGobZ_x_uD@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Canadians @ Hawks Canadians @ Hawks

Follow on MiLB First Pitch  https //stza.co/+xCdx-3i

Shop  https //stza.co/+xCdx-3U

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Canadians @ Hawks
END:VALARM
DTSTART:20180713T011500Z
DTEND:20180713T041500Z
UID:ZYLXlaPYbwTvqGzGobZ_x_uD@stanza.co
SUMMARY:Canadians @ Hawks
DESCRIPTION:Canadians @ Hawks\n\nFollow on MiLB First Pitch: https://stza.co/+xCdx-3i\n\nShop: https://stza.co/+xCdx-3U\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144603Z
LAST-MODIFIED:20180213T144603Z
TRANSP:OPAQUE
END:VEVENT
* Canadians @ Hawks
<2018-07-13 Fri 20:15-23:15>
:PROPERTIES:
:ID:       EgL8qawKP2xssOn5PS-LNwF0@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Canadians @ Hawks Canadians @ Hawks

Follow on MiLB First Pitch  https //stza.co/+xCdA-20

Shop  https //stza.co/+xCdA-2a

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Canadians @ Hawks
END:VALARM
DTSTART:20180714T011500Z
DTEND:20180714T041500Z
UID:EgL8qawKP2xssOn5PS-LNwF0@stanza.co
SUMMARY:Canadians @ Hawks
DESCRIPTION:Canadians @ Hawks\n\nFollow on MiLB First Pitch: https://stza.co/+xCdA-20\n\nShop: https://stza.co/+xCdA-2a\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144603Z
LAST-MODIFIED:20180213T144603Z
TRANSP:OPAQUE
END:VEVENT
* Canadians @ Hawks
<2018-07-14 Sat 20:15-23:15>
:PROPERTIES:
:ID:       QsL_ZH8Sp8J6KNVGjIndllPt@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Canadians @ Hawks Canadians @ Hawks

Follow on MiLB First Pitch  https //stza.co/+xCdB-V

Shop  https //stza.co/+xCdB-1u

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Canadians @ Hawks
END:VALARM
DTSTART:20180715T011500Z
DTEND:20180715T041500Z
UID:QsL_ZH8Sp8J6KNVGjIndllPt@stanza.co
SUMMARY:Canadians @ Hawks
DESCRIPTION:Canadians @ Hawks\n\nFollow on MiLB First Pitch: https://stza.co/+xCdB-V\n\nShop: https://stza.co/+xCdB-1u\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144603Z
LAST-MODIFIED:20180213T144603Z
TRANSP:OPAQUE
END:VEVENT
* Canadians @ Hawks
<2018-07-15 Sun 18:15-21:15>
:PROPERTIES:
:ID:       m80lb2iliUTqs-43-wG7w2Y6@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Canadians @ Hawks Canadians @ Hawks

Follow on MiLB First Pitch  https //stza.co/+xCdG-1w

Shop  https //stza.co/+xCdG-1A

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Canadians @ Hawks
END:VALARM
DTSTART:20180715T231500Z
DTEND:20180716T021500Z
UID:m80lb2iliUTqs-43-wG7w2Y6@stanza.co
SUMMARY:Canadians @ Hawks
DESCRIPTION:Canadians @ Hawks\n\nFollow on MiLB First Pitch: https://stza.co/+xCdG-1w\n\nShop: https://stza.co/+xCdG-1A\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144603Z
LAST-MODIFIED:20180213T144603Z
TRANSP:OPAQUE
END:VEVENT
* Canadians @ Dust Devils
<2018-07-16 Mon 21:15>--<2018-07-17 Tue 00:15>
:PROPERTIES:
:ID:       DlSM2uGVTeWAyre6Lme6amLr@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Canadians @ Dust Devils Canadians @ Dust Devils

Follow on MiLB First Pitch  https //stza.co/+vOgL-1r

Shop  https //stza.co/+vOgL-1Q

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Canadians @ Dust Devils
END:VALARM
DTSTART:20180717T021500Z
DTEND:20180717T051500Z
UID:DlSM2uGVTeWAyre6Lme6amLr@stanza.co
SUMMARY:Canadians @ Dust Devils
DESCRIPTION:Canadians @ Dust Devils\n\nFollow on MiLB First Pitch: https://stza.co/+vOgL-1r\n\nShop: https://stza.co/+vOgL-1Q\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144603Z
LAST-MODIFIED:20180213T144603Z
TRANSP:OPAQUE
END:VEVENT
* Canadians @ Dust Devils
<2018-07-17 Tue 21:15>--<2018-07-18 Wed 00:15>
:PROPERTIES:
:ID:       -SVuI2ne2yRaFvKA-See6Pat@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Canadians @ Dust Devils Canadians @ Dust Devils

Follow on MiLB First Pitch  https //stza.co/+vOgM-30

Shop  https //stza.co/+vOgM-15

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Canadians @ Dust Devils
END:VALARM
DTSTART:20180718T021500Z
DTEND:20180718T051500Z
UID:-SVuI2ne2yRaFvKA-See6Pat@stanza.co
SUMMARY:Canadians @ Dust Devils
DESCRIPTION:Canadians @ Dust Devils\n\nFollow on MiLB First Pitch: https://stza.co/+vOgM-30\n\nShop: https://stza.co/+vOgM-15\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144603Z
LAST-MODIFIED:20180213T144603Z
TRANSP:OPAQUE
END:VEVENT
* Canadians @ Dust Devils
<2018-07-18 Wed 21:15>--<2018-07-19 Thu 00:15>
:PROPERTIES:
:ID:       F3DPl4NqX_bHWEh4M8ydN2aw@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Canadians @ Dust Devils Canadians @ Dust Devils

Follow on MiLB First Pitch  https //stza.co/+vOgN-1R

Shop  https //stza.co/+vOgN-1L

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Canadians @ Dust Devils
END:VALARM
DTSTART:20180719T021500Z
DTEND:20180719T051500Z
UID:F3DPl4NqX_bHWEh4M8ydN2aw@stanza.co
SUMMARY:Canadians @ Dust Devils
DESCRIPTION:Canadians @ Dust Devils\n\nFollow on MiLB First Pitch: https://stza.co/+vOgN-1R\n\nShop: https://stza.co/+vOgN-1L\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144603Z
LAST-MODIFIED:20180213T144603Z
TRANSP:OPAQUE
END:VEVENT
* Canadians vs. Hops
<2018-07-19 Thu 21:05>--<2018-07-20 Fri 00:05>
:PROPERTIES:
:ID:       cznCU6Xfi2i38nWa_zhdsjDM@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Canadians vs. Hops Canadians vs. Hops

Follow on MiLB First Pitch  https //stza.co/+xXVQ-2J

Shop  https //stza.co/+xXVQ-3x

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Canadians vs. Hops
END:VALARM
DTSTART:20180720T020500Z
DTEND:20180720T050500Z
UID:cznCU6Xfi2i38nWa_zhdsjDM@stanza.co
SUMMARY:Canadians vs. Hops
DESCRIPTION:Canadians vs. Hops\n\nFollow on MiLB First Pitch: https://stza.co/+xXVQ-2J\n\nShop: https://stza.co/+xXVQ-3x\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144603Z
LAST-MODIFIED:20180213T144603Z
TRANSP:OPAQUE
END:VEVENT
* Canadians vs. Hops
<2018-07-20 Fri 15:05-18:05>
:PROPERTIES:
:ID:       foEYRbWF_WaakVZGTPHgaeym@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Canadians vs. Hops Canadians vs. Hops

Follow on MiLB First Pitch  https //stza.co/+xXVR-1B

Shop  https //stza.co/+xXVR-3n

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Canadians vs. Hops
END:VALARM
DTSTART:20180720T200500Z
DTEND:20180720T230500Z
UID:foEYRbWF_WaakVZGTPHgaeym@stanza.co
SUMMARY:Canadians vs. Hops
DESCRIPTION:Canadians vs. Hops\n\nFollow on MiLB First Pitch: https://stza.co/+xXVR-1B\n\nShop: https://stza.co/+xXVR-3n\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144603Z
LAST-MODIFIED:20180213T144603Z
TRANSP:OPAQUE
END:VEVENT
* Canadians vs. Hops
<2018-07-21 Sat 21:05>--<2018-07-22 Sun 00:05>
:PROPERTIES:
:ID:       OjmiACCFei1rN8WnWVsk2scJ@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Canadians vs. Hops Canadians vs. Hops

Follow on MiLB First Pitch  https //stza.co/+xXVU-3s

Shop  https //stza.co/+xXVU-24

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Canadians vs. Hops
END:VALARM
DTSTART:20180722T020500Z
DTEND:20180722T050500Z
UID:OjmiACCFei1rN8WnWVsk2scJ@stanza.co
SUMMARY:Canadians vs. Hops
DESCRIPTION:Canadians vs. Hops\n\nFollow on MiLB First Pitch: https://stza.co/+xXVU-3s\n\nShop: https://stza.co/+xXVU-24\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144603Z
LAST-MODIFIED:20180213T144603Z
TRANSP:OPAQUE
END:VEVENT
* Canadians vs. Hops
<2018-07-22 Sun 15:05-18:05>
:PROPERTIES:
:ID:       Sqyms6oGQTsZYBi3LztLD3dV@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Canadians vs. Hops Canadians vs. Hops

Follow on MiLB First Pitch  https //stza.co/+xXVV-e

Shop  https //stza.co/+xXVV-B

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Canadians vs. Hops
END:VALARM
DTSTART:20180722T200500Z
DTEND:20180722T230500Z
UID:Sqyms6oGQTsZYBi3LztLD3dV@stanza.co
SUMMARY:Canadians vs. Hops
DESCRIPTION:Canadians vs. Hops\n\nFollow on MiLB First Pitch: https://stza.co/+xXVV-e\n\nShop: https://stza.co/+xXVV-B\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144603Z
LAST-MODIFIED:20180213T144603Z
TRANSP:OPAQUE
END:VEVENT
* Canadians vs. Hops
<2018-07-23 Mon 21:05>--<2018-07-24 Tue 00:05>
:PROPERTIES:
:ID:       dZapYGXTkXmxMD57WqLc6796@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Canadians vs. Hops Canadians vs. Hops

Follow on MiLB First Pitch  https //stza.co/+xXVY-3b

Shop  https //stza.co/+xXVY-3h

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Canadians vs. Hops
END:VALARM
DTSTART:20180724T020500Z
DTEND:20180724T050500Z
UID:dZapYGXTkXmxMD57WqLc6796@stanza.co
SUMMARY:Canadians vs. Hops
DESCRIPTION:Canadians vs. Hops\n\nFollow on MiLB First Pitch: https://stza.co/+xXVY-3b\n\nShop: https://stza.co/+xXVY-3h\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144603Z
LAST-MODIFIED:20180213T144603Z
TRANSP:OPAQUE
END:VEVENT
* Canadians @ AquaSox
<2018-07-24 Tue 21:05>--<2018-07-25 Wed 00:05>
:PROPERTIES:
:ID:       9bqlv3ioWM4QKvRmVo5PnH_d@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Canadians @ AquaSox Canadians @ AquaSox

Follow on MiLB First Pitch  https //stza.co/+vOgs-1V

Shop  https //stza.co/+vOgs-13

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Canadians @ AquaSox
END:VALARM
DTSTART:20180725T020500Z
DTEND:20180725T050500Z
UID:9bqlv3ioWM4QKvRmVo5PnH_d@stanza.co
SUMMARY:Canadians @ AquaSox
DESCRIPTION:Canadians @ AquaSox\n\nFollow on MiLB First Pitch: https://stza.co/+vOgs-1V\n\nShop: https://stza.co/+vOgs-13\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144603Z
LAST-MODIFIED:20180213T144603Z
TRANSP:OPAQUE
END:VEVENT
* Canadians @ AquaSox
<2018-07-25 Wed 21:05>--<2018-07-26 Thu 00:05>
:PROPERTIES:
:ID:       PZZUj-_Gr5XxQI5vs8wl04__@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Canadians @ AquaSox Canadians @ AquaSox

Follow on MiLB First Pitch  https //stza.co/+vOgt-x

Shop  https //stza.co/+vOgt-29

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Canadians @ AquaSox
END:VALARM
DTSTART:20180726T020500Z
DTEND:20180726T050500Z
UID:PZZUj-_Gr5XxQI5vs8wl04__@stanza.co
SUMMARY:Canadians @ AquaSox
DESCRIPTION:Canadians @ AquaSox\n\nFollow on MiLB First Pitch: https://stza.co/+vOgt-x\n\nShop: https://stza.co/+vOgt-29\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144603Z
LAST-MODIFIED:20180213T144603Z
TRANSP:OPAQUE
END:VEVENT
* Canadians @ AquaSox
<2018-07-26 Thu 13:05-16:05>
:PROPERTIES:
:ID:       MMLfbvQvFl_3TqnAMIietVHp@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Canadians @ AquaSox Canadians @ AquaSox

Follow on MiLB First Pitch  https //stza.co/+vOgu-2d

Shop  https //stza.co/+vOgu-2Y

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Canadians @ AquaSox
END:VALARM
DTSTART:20180726T180500Z
DTEND:20180726T210500Z
UID:MMLfbvQvFl_3TqnAMIietVHp@stanza.co
SUMMARY:Canadians @ AquaSox
DESCRIPTION:Canadians @ AquaSox\n\nFollow on MiLB First Pitch: https://stza.co/+vOgu-2d\n\nShop: https://stza.co/+vOgu-2Y\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144603Z
LAST-MODIFIED:20180213T144603Z
TRANSP:OPAQUE
END:VEVENT
* Canadians vs. Emeralds
<2018-07-27 Fri 21:05>--<2018-07-28 Sat 00:05>
:PROPERTIES:
:ID:       SloS3HWcVSjtVJw7y2uq3TzS@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Canadians vs. Emeralds Canadians vs. Emeralds

Follow on MiLB First Pitch  https //stza.co/+xXV_-1v

Shop  https //stza.co/+xXV_-3r

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Canadians vs. Emeralds
END:VALARM
DTSTART:20180728T020500Z
DTEND:20180728T050500Z
UID:SloS3HWcVSjtVJw7y2uq3TzS@stanza.co
SUMMARY:Canadians vs. Emeralds
DESCRIPTION:Canadians vs. Emeralds\n\nFollow on MiLB First Pitch: https://stza.co/+xXV_-1v\n\nShop: https://stza.co/+xXV_-3r\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144603Z
LAST-MODIFIED:20180213T144603Z
TRANSP:OPAQUE
END:VEVENT
* Canadians vs. Emeralds
<2018-07-28 Sat 21:05>--<2018-07-29 Sun 00:05>
:PROPERTIES:
:ID:       5gKwHVsJFzYi5US4fbbAKpmz@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Canadians vs. Emeralds Canadians vs. Emeralds

Follow on MiLB First Pitch  https //stza.co/+xXW0-17

Shop  https //stza.co/+xXW0-3N

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Canadians vs. Emeralds
END:VALARM
DTSTART:20180729T020500Z
DTEND:20180729T050500Z
UID:5gKwHVsJFzYi5US4fbbAKpmz@stanza.co
SUMMARY:Canadians vs. Emeralds
DESCRIPTION:Canadians vs. Emeralds\n\nFollow on MiLB First Pitch: https://stza.co/+xXW0-17\n\nShop: https://stza.co/+xXW0-3N\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144603Z
LAST-MODIFIED:20180213T144603Z
TRANSP:OPAQUE
END:VEVENT
* Canadians vs. Emeralds
<2018-07-29 Sun 15:05-18:05>
:PROPERTIES:
:ID:       k77Rx_02O8O8m-CtXtWmLzGb@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Canadians vs. Emeralds Canadians vs. Emeralds

Follow on MiLB First Pitch  https //stza.co/+xXW2-2Y

Shop  https //stza.co/+xXW2-1U

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Canadians vs. Emeralds
END:VALARM
DTSTART:20180729T200500Z
DTEND:20180729T230500Z
UID:k77Rx_02O8O8m-CtXtWmLzGb@stanza.co
SUMMARY:Canadians vs. Emeralds
DESCRIPTION:Canadians vs. Emeralds\n\nFollow on MiLB First Pitch: https://stza.co/+xXW2-2Y\n\nShop: https://stza.co/+xXW2-1U\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144603Z
LAST-MODIFIED:20180213T144603Z
TRANSP:OPAQUE
END:VEVENT
* Canadians vs. Emeralds
<2018-07-30 Mon 21:05>--<2018-07-31 Tue 00:05>
:PROPERTIES:
:ID:       as0jUrAAEIcb7ZIDrAzLrLKe@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Canadians vs. Emeralds Canadians vs. Emeralds

Follow on MiLB First Pitch  https //stza.co/+xXW3-3I

Shop  https //stza.co/+xXW3-2n

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Canadians vs. Emeralds
END:VALARM
DTSTART:20180731T020500Z
DTEND:20180731T050500Z
UID:as0jUrAAEIcb7ZIDrAzLrLKe@stanza.co
SUMMARY:Canadians vs. Emeralds
DESCRIPTION:Canadians vs. Emeralds\n\nFollow on MiLB First Pitch: https://stza.co/+xXW3-3I\n\nShop: https://stza.co/+xXW3-2n\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144603Z
LAST-MODIFIED:20180213T144603Z
TRANSP:OPAQUE
END:VEVENT
* Canadians vs. Emeralds
<2018-07-31 Tue 21:05>--<2018-08-01 Wed 00:05>
:PROPERTIES:
:ID:       1xezFBhOhP6ZdAdHUBNrRgWB@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Canadians vs. Emeralds Canadians vs. Emeralds

Follow on MiLB First Pitch  https //stza.co/+xXW5-3J

Shop  https //stza.co/+xXW5-1E

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Canadians vs. Emeralds
END:VALARM
DTSTART:20180801T020500Z
DTEND:20180801T050500Z
UID:1xezFBhOhP6ZdAdHUBNrRgWB@stanza.co
SUMMARY:Canadians vs. Emeralds
DESCRIPTION:Canadians vs. Emeralds\n\nFollow on MiLB First Pitch: https://stza.co/+xXW5-3J\n\nShop: https://stza.co/+xXW5-1E\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144603Z
LAST-MODIFIED:20180213T144603Z
TRANSP:OPAQUE
END:VEVENT
* Canadians @ Hops
<2018-08-01 Wed 21:05>--<2018-08-02 Thu 00:05>
:PROPERTIES:
:ID:       UfxFhcomNBHr9feotQaoipPl@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Canadians @ Hops Canadians @ Hops

Follow on MiLB First Pitch  https //stza.co/+vOgv-2C

Shop  https //stza.co/+vOgv-F

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Canadians @ Hops
END:VALARM
DTSTART:20180802T020500Z
DTEND:20180802T050500Z
UID:UfxFhcomNBHr9feotQaoipPl@stanza.co
SUMMARY:Canadians @ Hops
DESCRIPTION:Canadians @ Hops\n\nFollow on MiLB First Pitch: https://stza.co/+vOgv-2C\n\nShop: https://stza.co/+vOgv-F\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144603Z
LAST-MODIFIED:20180213T144603Z
TRANSP:OPAQUE
END:VEVENT
* Canadians @ Hops
<2018-08-02 Thu 21:05>--<2018-08-03 Fri 00:05>
:PROPERTIES:
:ID:       QDObl5QR80RuJ0DJJuYRFftC@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Canadians @ Hops Canadians @ Hops

Follow on MiLB First Pitch  https //stza.co/+vOgw-Q

Shop  https //stza.co/+vOgw-1k

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Canadians @ Hops
END:VALARM
DTSTART:20180803T020500Z
DTEND:20180803T050500Z
UID:QDObl5QR80RuJ0DJJuYRFftC@stanza.co
SUMMARY:Canadians @ Hops
DESCRIPTION:Canadians @ Hops\n\nFollow on MiLB First Pitch: https://stza.co/+vOgw-Q\n\nShop: https://stza.co/+vOgw-1k\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144603Z
LAST-MODIFIED:20180213T144603Z
TRANSP:OPAQUE
END:VEVENT
* Canadians @ Hops
<2018-08-03 Fri 21:05>--<2018-08-04 Sat 00:05>
:PROPERTIES:
:ID:       u63r-V2YGK9-sn6qOCBcFB00@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Canadians @ Hops Canadians @ Hops

Follow on MiLB First Pitch  https //stza.co/+vOgx-2S

Shop  https //stza.co/+vOgx-1U

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Canadians @ Hops
END:VALARM
DTSTART:20180804T020500Z
DTEND:20180804T050500Z
UID:u63r-V2YGK9-sn6qOCBcFB00@stanza.co
SUMMARY:Canadians @ Hops
DESCRIPTION:Canadians @ Hops\n\nFollow on MiLB First Pitch: https://stza.co/+vOgx-2S\n\nShop: https://stza.co/+vOgx-1U\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144603Z
LAST-MODIFIED:20180213T144603Z
TRANSP:OPAQUE
END:VEVENT
* Canadians @ Hops
<2018-08-04 Sat 21:05>--<2018-08-05 Sun 00:05>
:PROPERTIES:
:ID:       wi-d2mAjhjrzA1zOu_i83Xjk@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Canadians @ Hops Canadians @ Hops

Follow on MiLB First Pitch  https //stza.co/+vOgy-N

Shop  https //stza.co/+vOgy-1g

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Canadians @ Hops
END:VALARM
DTSTART:20180805T020500Z
DTEND:20180805T050500Z
UID:wi-d2mAjhjrzA1zOu_i83Xjk@stanza.co
SUMMARY:Canadians @ Hops
DESCRIPTION:Canadians @ Hops\n\nFollow on MiLB First Pitch: https://stza.co/+vOgy-N\n\nShop: https://stza.co/+vOgy-1g\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144603Z
LAST-MODIFIED:20180213T144603Z
TRANSP:OPAQUE
END:VEVENT
* Canadians @ Hops
<2018-08-05 Sun 18:05-21:05>
:PROPERTIES:
:ID:       1tWvm_BVG80K1a_zNkSEnfIl@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Canadians @ Hops Canadians @ Hops

Follow on MiLB First Pitch  https //stza.co/+vOgz-1V

Shop  https //stza.co/+vOgz-36

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Canadians @ Hops
END:VALARM
DTSTART:20180805T230500Z
DTEND:20180806T020500Z
UID:1tWvm_BVG80K1a_zNkSEnfIl@stanza.co
SUMMARY:Canadians @ Hops
DESCRIPTION:Canadians @ Hops\n\nFollow on MiLB First Pitch: https://stza.co/+vOgz-1V\n\nShop: https://stza.co/+vOgz-36\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144603Z
LAST-MODIFIED:20180213T144603Z
TRANSP:OPAQUE
END:VEVENT
* Canadians @ Volcanoes
<2018-08-09 Thu>--<2018-08-08 Wed>
:PROPERTIES:
:ID:       KeggKoMtkH3K1a5pW3KseTEt@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Canadians @ Volcanoes Canadians @ Volcanoes

Follow on MiLB First Pitch  https //stza.co/+vOgA-1p

Shop  https //stza.co/+vOgA-1t

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Canadians @ Volcanoes
END:VALARM
DTSTART;VALUE=DATE:20180809
DTEND;VALUE=DATE:20180809
UID:KeggKoMtkH3K1a5pW3KseTEt@stanza.co
SUMMARY:Canadians @ Volcanoes
DESCRIPTION:Canadians @ Volcanoes\n\nFollow on MiLB First Pitch: https://stza.co/+vOgA-1p\n\nShop: https://stza.co/+vOgA-1t\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144603Z
LAST-MODIFIED:20180213T144603Z
TRANSP:OPAQUE
END:VEVENT
* Canadians @ Volcanoes
<2018-08-10 Fri>--<2018-08-09 Thu>
:PROPERTIES:
:ID:       _x3KIAfRn2tlGU0QInJuZW-h@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Canadians @ Volcanoes Canadians @ Volcanoes

Follow on MiLB First Pitch  https //stza.co/+vOgB-W

Shop  https //stza.co/+vOgB-3_

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Canadians @ Volcanoes
END:VALARM
DTSTART;VALUE=DATE:20180810
DTEND;VALUE=DATE:20180810
UID:_x3KIAfRn2tlGU0QInJuZW-h@stanza.co
SUMMARY:Canadians @ Volcanoes
DESCRIPTION:Canadians @ Volcanoes\n\nFollow on MiLB First Pitch: https://stza.co/+vOgB-W\n\nShop: https://stza.co/+vOgB-3_\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144603Z
LAST-MODIFIED:20180213T144603Z
TRANSP:OPAQUE
END:VEVENT
* Canadians @ Volcanoes
<2018-08-11 Sat>--<2018-08-10 Fri>
:PROPERTIES:
:ID:       XNmkk1KyVhYrrYBhxRBgOZ2p@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Canadians @ Volcanoes Canadians @ Volcanoes

Follow on MiLB First Pitch  https //stza.co/+vOgC-1r

Shop  https //stza.co/+vOgC-1w

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Canadians @ Volcanoes
END:VALARM
DTSTART;VALUE=DATE:20180811
DTEND;VALUE=DATE:20180811
UID:XNmkk1KyVhYrrYBhxRBgOZ2p@stanza.co
SUMMARY:Canadians @ Volcanoes
DESCRIPTION:Canadians @ Volcanoes\n\nFollow on MiLB First Pitch: https://stza.co/+vOgC-1r\n\nShop: https://stza.co/+vOgC-1w\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144603Z
LAST-MODIFIED:20180213T144603Z
TRANSP:OPAQUE
END:VEVENT
* Canadians @ Volcanoes
<2018-08-12 Sun>--<2018-08-11 Sat>
:PROPERTIES:
:ID:       sIjmXhdt95ppKnUu1fo7fMlv@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Canadians @ Volcanoes Canadians @ Volcanoes

Follow on MiLB First Pitch  https //stza.co/+vOgD-2E

Shop  https //stza.co/+vOgD-3r

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Canadians @ Volcanoes
END:VALARM
DTSTART;VALUE=DATE:20180812
DTEND;VALUE=DATE:20180812
UID:sIjmXhdt95ppKnUu1fo7fMlv@stanza.co
SUMMARY:Canadians @ Volcanoes
DESCRIPTION:Canadians @ Volcanoes\n\nFollow on MiLB First Pitch: https://stza.co/+vOgD-2E\n\nShop: https://stza.co/+vOgD-3r\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144603Z
LAST-MODIFIED:20180213T144603Z
TRANSP:OPAQUE
END:VEVENT
* Canadians @ Volcanoes
<2018-08-13 Mon>--<2018-08-12 Sun>
:PROPERTIES:
:ID:       x63Z0hktBKA_EhMGvsE3cQe4@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Canadians @ Volcanoes Canadians @ Volcanoes

Follow on MiLB First Pitch  https //stza.co/+vOgE-3X

Shop  https //stza.co/+vOgE-A

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Canadians @ Volcanoes
END:VALARM
DTSTART;VALUE=DATE:20180813
DTEND;VALUE=DATE:20180813
UID:x63Z0hktBKA_EhMGvsE3cQe4@stanza.co
SUMMARY:Canadians @ Volcanoes
DESCRIPTION:Canadians @ Volcanoes\n\nFollow on MiLB First Pitch: https://stza.co/+vOgE-3X\n\nShop: https://stza.co/+vOgE-A\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144603Z
LAST-MODIFIED:20180213T144603Z
TRANSP:OPAQUE
END:VEVENT
* Canadians vs. Dust Devils
<2018-08-14 Tue 21:05>--<2018-08-15 Wed 00:05>
:PROPERTIES:
:ID:       1_rEZ1bfSP-_CEZTGf-40qwn@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Canadians vs. Dust Devils Canadians vs. Dust Devils

Follow on MiLB First Pitch  https //stza.co/+xXW8-2a

Shop  https //stza.co/+xXW8-2T

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Canadians vs. Dust Devils
END:VALARM
DTSTART:20180815T020500Z
DTEND:20180815T050500Z
UID:1_rEZ1bfSP-_CEZTGf-40qwn@stanza.co
SUMMARY:Canadians vs. Dust Devils
DESCRIPTION:Canadians vs. Dust Devils\n\nFollow on MiLB First Pitch: https://stza.co/+xXW8-2a\n\nShop: https://stza.co/+xXW8-2T\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144603Z
LAST-MODIFIED:20180213T144603Z
TRANSP:OPAQUE
END:VEVENT
* Canadians vs. Dust Devils
<2018-08-15 Wed 21:05>--<2018-08-16 Thu 00:05>
:PROPERTIES:
:ID:       -zS42DZu-t9p0phkLUCZbEic@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Canadians vs. Dust Devils Canadians vs. Dust Devils

Follow on MiLB First Pitch  https //stza.co/+xXWa-2I

Shop  https //stza.co/+xXWa-m

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Canadians vs. Dust Devils
END:VALARM
DTSTART:20180816T020500Z
DTEND:20180816T050500Z
UID:-zS42DZu-t9p0phkLUCZbEic@stanza.co
SUMMARY:Canadians vs. Dust Devils
DESCRIPTION:Canadians vs. Dust Devils\n\nFollow on MiLB First Pitch: https://stza.co/+xXWa-2I\n\nShop: https://stza.co/+xXWa-m\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144603Z
LAST-MODIFIED:20180213T144603Z
TRANSP:OPAQUE
END:VEVENT
* Canadians vs. Dust Devils
<2018-08-16 Thu 15:05-18:05>
:PROPERTIES:
:ID:       rDLaduv4wGf20Cc2O6WW__No@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Canadians vs. Dust Devils Canadians vs. Dust Devils

Follow on MiLB First Pitch  https //stza.co/+xXWc-2J

Shop  https //stza.co/+xXWc-2f

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Canadians vs. Dust Devils
END:VALARM
DTSTART:20180816T200500Z
DTEND:20180816T230500Z
UID:rDLaduv4wGf20Cc2O6WW__No@stanza.co
SUMMARY:Canadians vs. Dust Devils
DESCRIPTION:Canadians vs. Dust Devils\n\nFollow on MiLB First Pitch: https://stza.co/+xXWc-2J\n\nShop: https://stza.co/+xXWc-2f\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144603Z
LAST-MODIFIED:20180213T144603Z
TRANSP:OPAQUE
END:VEVENT
* Canadians vs. Indians
<2018-08-17 Fri 21:05>--<2018-08-18 Sat 00:05>
:PROPERTIES:
:ID:       EcZoOMXExpxHoDpQfw2wBSYA@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Canadians vs. Indians Canadians vs. Indians

Follow on MiLB First Pitch  https //stza.co/+xXWf-T

Shop  https //stza.co/+xXWf-2n

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Canadians vs. Indians
END:VALARM
DTSTART:20180818T020500Z
DTEND:20180818T050500Z
UID:EcZoOMXExpxHoDpQfw2wBSYA@stanza.co
SUMMARY:Canadians vs. Indians
DESCRIPTION:Canadians vs. Indians\n\nFollow on MiLB First Pitch: https://stza.co/+xXWf-T\n\nShop: https://stza.co/+xXWf-2n\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144603Z
LAST-MODIFIED:20180213T144603Z
TRANSP:OPAQUE
END:VEVENT
* Canadians vs. Indians
<2018-08-18 Sat 21:05>--<2018-08-19 Sun 00:05>
:PROPERTIES:
:ID:       3r_nSVye05xdV5B5KMt_VJbD@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Canadians vs. Indians Canadians vs. Indians

Follow on MiLB First Pitch  https //stza.co/+xXWh-2c

Shop  https //stza.co/+xXWh-3j

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Canadians vs. Indians
END:VALARM
DTSTART:20180819T020500Z
DTEND:20180819T050500Z
UID:3r_nSVye05xdV5B5KMt_VJbD@stanza.co
SUMMARY:Canadians vs. Indians
DESCRIPTION:Canadians vs. Indians\n\nFollow on MiLB First Pitch: https://stza.co/+xXWh-2c\n\nShop: https://stza.co/+xXWh-3j\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144603Z
LAST-MODIFIED:20180213T144603Z
TRANSP:OPAQUE
END:VEVENT
* Canadians vs. Indians
<2018-08-19 Sun 15:05-18:05>
:PROPERTIES:
:ID:       6LN447uH83oljuzCo1OMmfcf@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Canadians vs. Indians Canadians vs. Indians

Follow on MiLB First Pitch  https //stza.co/+xXWi-C

Shop  https //stza.co/+xXWi-21

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Canadians vs. Indians
END:VALARM
DTSTART:20180819T200500Z
DTEND:20180819T230500Z
UID:6LN447uH83oljuzCo1OMmfcf@stanza.co
SUMMARY:Canadians vs. Indians
DESCRIPTION:Canadians vs. Indians\n\nFollow on MiLB First Pitch: https://stza.co/+xXWi-C\n\nShop: https://stza.co/+xXWi-21\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144603Z
LAST-MODIFIED:20180213T144603Z
TRANSP:OPAQUE
END:VEVENT
* Canadians @ Dust Devils
<2018-08-20 Mon 21:15>--<2018-08-21 Tue 00:15>
:PROPERTIES:
:ID:       gTLMJltlSzBamta74JpgB1T2@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Canadians @ Dust Devils Canadians @ Dust Devils

Follow on MiLB First Pitch  https //stza.co/+vOgO-18

Shop  https //stza.co/+vOgO-10

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Canadians @ Dust Devils
END:VALARM
DTSTART:20180821T021500Z
DTEND:20180821T051500Z
UID:gTLMJltlSzBamta74JpgB1T2@stanza.co
SUMMARY:Canadians @ Dust Devils
DESCRIPTION:Canadians @ Dust Devils\n\nFollow on MiLB First Pitch: https://stza.co/+vOgO-18\n\nShop: https://stza.co/+vOgO-10\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144603Z
LAST-MODIFIED:20180213T144603Z
TRANSP:OPAQUE
END:VEVENT
* Canadians @ Dust Devils
<2018-08-21 Tue 21:15>--<2018-08-22 Wed 00:15>
:PROPERTIES:
:ID:       gLgVYIUPbj8USHitsRysuvZM@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Canadians @ Dust Devils Canadians @ Dust Devils

Follow on MiLB First Pitch  https //stza.co/+vOgP-1g

Shop  https //stza.co/+vOgP-2a

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Canadians @ Dust Devils
END:VALARM
DTSTART:20180822T021500Z
DTEND:20180822T051500Z
UID:gLgVYIUPbj8USHitsRysuvZM@stanza.co
SUMMARY:Canadians @ Dust Devils
DESCRIPTION:Canadians @ Dust Devils\n\nFollow on MiLB First Pitch: https://stza.co/+vOgP-1g\n\nShop: https://stza.co/+vOgP-2a\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144603Z
LAST-MODIFIED:20180213T144603Z
TRANSP:OPAQUE
END:VEVENT
* Canadians @ Dust Devils
<2018-08-22 Wed 21:15>--<2018-08-23 Thu 00:15>
:PROPERTIES:
:ID:       fOQEF1BY8y6P7mSPlH7VA0s9@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Canadians @ Dust Devils Canadians @ Dust Devils

Follow on MiLB First Pitch  https //stza.co/+vOgQ-2d

Shop  https //stza.co/+vOgQ-j

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Canadians @ Dust Devils
END:VALARM
DTSTART:20180823T021500Z
DTEND:20180823T051500Z
UID:fOQEF1BY8y6P7mSPlH7VA0s9@stanza.co
SUMMARY:Canadians @ Dust Devils
DESCRIPTION:Canadians @ Dust Devils\n\nFollow on MiLB First Pitch: https://stza.co/+vOgQ-2d\n\nShop: https://stza.co/+vOgQ-j\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144603Z
LAST-MODIFIED:20180213T144603Z
TRANSP:OPAQUE
END:VEVENT
* Canadians vs. Hawks
<2018-08-23 Thu 21:05>--<2018-08-24 Fri 00:05>
:PROPERTIES:
:ID:       BN39S2ij_4-zD10xIIwd03Ka@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Canadians vs. Hawks Canadians vs. Hawks

Follow on MiLB First Pitch  https //stza.co/+xXWl-L

Shop  https //stza.co/+xXWl-3R

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Canadians vs. Hawks
END:VALARM
DTSTART:20180824T020500Z
DTEND:20180824T050500Z
UID:BN39S2ij_4-zD10xIIwd03Ka@stanza.co
SUMMARY:Canadians vs. Hawks
DESCRIPTION:Canadians vs. Hawks\n\nFollow on MiLB First Pitch: https://stza.co/+xXWl-L\n\nShop: https://stza.co/+xXWl-3R\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144603Z
LAST-MODIFIED:20180213T144603Z
TRANSP:OPAQUE
END:VEVENT
* Canadians vs. Hawks
<2018-08-24 Fri 15:05-18:05>
:PROPERTIES:
:ID:       cDa8sIQB7E-a9t9VRqp2m9sO@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Canadians vs. Hawks Canadians vs. Hawks

Follow on MiLB First Pitch  https //stza.co/+xXWm-20

Shop  https //stza.co/+xXWm-2f

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Canadians vs. Hawks
END:VALARM
DTSTART:20180824T200500Z
DTEND:20180824T230500Z
UID:cDa8sIQB7E-a9t9VRqp2m9sO@stanza.co
SUMMARY:Canadians vs. Hawks
DESCRIPTION:Canadians vs. Hawks\n\nFollow on MiLB First Pitch: https://stza.co/+xXWm-20\n\nShop: https://stza.co/+xXWm-2f\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144603Z
LAST-MODIFIED:20180213T144603Z
TRANSP:OPAQUE
END:VEVENT
* Canadians vs. Hawks
<2018-08-25 Sat 21:05>--<2018-08-26 Sun 00:05>
:PROPERTIES:
:ID:       sIncyg0yQkVnCLaM9ywszMlt@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Canadians vs. Hawks Canadians vs. Hawks

Follow on MiLB First Pitch  https //stza.co/+xXWp-34

Shop  https //stza.co/+xXWp-m

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Canadians vs. Hawks
END:VALARM
DTSTART:20180826T020500Z
DTEND:20180826T050500Z
UID:sIncyg0yQkVnCLaM9ywszMlt@stanza.co
SUMMARY:Canadians vs. Hawks
DESCRIPTION:Canadians vs. Hawks\n\nFollow on MiLB First Pitch: https://stza.co/+xXWp-34\n\nShop: https://stza.co/+xXWp-m\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144603Z
LAST-MODIFIED:20180213T144603Z
TRANSP:OPAQUE
END:VEVENT
* Canadians vs. Hawks
<2018-08-26 Sun 15:05-18:05>
:PROPERTIES:
:ID:       IB73kPAwufNBLTiPxfmMyErf@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Canadians vs. Hawks Canadians vs. Hawks

Follow on MiLB First Pitch  https //stza.co/+xXWr-x

Shop  https //stza.co/+xXWr-2p

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Canadians vs. Hawks
END:VALARM
DTSTART:20180826T200500Z
DTEND:20180826T230500Z
UID:IB73kPAwufNBLTiPxfmMyErf@stanza.co
SUMMARY:Canadians vs. Hawks
DESCRIPTION:Canadians vs. Hawks\n\nFollow on MiLB First Pitch: https://stza.co/+xXWr-x\n\nShop: https://stza.co/+xXWr-2p\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144603Z
LAST-MODIFIED:20180213T144603Z
TRANSP:OPAQUE
END:VEVENT
* Canadians vs. Hawks
<2018-08-27 Mon 21:05>--<2018-08-28 Tue 00:05>
:PROPERTIES:
:ID:       WunyNIKNz7n-Ua9zz3uCXWlS@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Canadians vs. Hawks Canadians vs. Hawks

Follow on MiLB First Pitch  https //stza.co/+xXWt-f

Shop  https //stza.co/+xXWt-2d

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Canadians vs. Hawks
END:VALARM
DTSTART:20180828T020500Z
DTEND:20180828T050500Z
UID:WunyNIKNz7n-Ua9zz3uCXWlS@stanza.co
SUMMARY:Canadians vs. Hawks
DESCRIPTION:Canadians vs. Hawks\n\nFollow on MiLB First Pitch: https://stza.co/+xXWt-f\n\nShop: https://stza.co/+xXWt-2d\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144603Z
LAST-MODIFIED:20180213T144603Z
TRANSP:OPAQUE
END:VEVENT
* Canadians vs. AquaSox
<2018-08-29 Wed 21:05>--<2018-08-30 Thu 00:05>
:PROPERTIES:
:ID:       FJRIGBrbxaKwlMlHKQ1b2RT5@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Canadians vs. AquaSox Canadians vs. AquaSox

Follow on MiLB First Pitch  https //stza.co/+xXWu-2N

Shop  https //stza.co/+xXWu-2b

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Canadians vs. AquaSox
END:VALARM
DTSTART:20180830T020500Z
DTEND:20180830T050500Z
UID:FJRIGBrbxaKwlMlHKQ1b2RT5@stanza.co
SUMMARY:Canadians vs. AquaSox
DESCRIPTION:Canadians vs. AquaSox\n\nFollow on MiLB First Pitch: https://stza.co/+xXWu-2N\n\nShop: https://stza.co/+xXWu-2b\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144603Z
LAST-MODIFIED:20180213T144603Z
TRANSP:OPAQUE
END:VEVENT
* Canadians vs. AquaSox
<2018-08-30 Thu 21:05>--<2018-08-31 Fri 00:05>
:PROPERTIES:
:ID:       Bzg7RmBUPiTA9SPlkDea7voS@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Canadians vs. AquaSox Canadians vs. AquaSox

Follow on MiLB First Pitch  https //stza.co/+xXWw-v

Shop  https //stza.co/+xXWw-2D

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Canadians vs. AquaSox
END:VALARM
DTSTART:20180831T020500Z
DTEND:20180831T050500Z
UID:Bzg7RmBUPiTA9SPlkDea7voS@stanza.co
SUMMARY:Canadians vs. AquaSox
DESCRIPTION:Canadians vs. AquaSox\n\nFollow on MiLB First Pitch: https://stza.co/+xXWw-v\n\nShop: https://stza.co/+xXWw-2D\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144603Z
LAST-MODIFIED:20180213T144603Z
TRANSP:OPAQUE
END:VEVENT
* Canadians vs. AquaSox
<2018-08-31 Fri 15:05-18:05>
:PROPERTIES:
:ID:       qIBuUxlI7w3YMyows_1J3MVT@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Canadians vs. AquaSox Canadians vs. AquaSox

Follow on MiLB First Pitch  https //stza.co/+xXWy-22

Shop  https //stza.co/+xXWy-3D

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Canadians vs. AquaSox
END:VALARM
DTSTART:20180831T200500Z
DTEND:20180831T230500Z
UID:qIBuUxlI7w3YMyows_1J3MVT@stanza.co
SUMMARY:Canadians vs. AquaSox
DESCRIPTION:Canadians vs. AquaSox\n\nFollow on MiLB First Pitch: https://stza.co/+xXWy-22\n\nShop: https://stza.co/+xXWy-3D\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144603Z
LAST-MODIFIED:20180213T144603Z
TRANSP:OPAQUE
END:VEVENT
* Canadians @ Indians
<2018-09-01 Sat 20:30-23:30>
:PROPERTIES:
:ID:       xsUy8v0EOivLaeRBP60kTpLR@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Canadians @ Indians Canadians @ Indians

Follow on MiLB First Pitch  https //stza.co/+xCdU-8

Shop  https //stza.co/+xCdU-1W

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Canadians @ Indians
END:VALARM
DTSTART:20180902T013000Z
DTEND:20180902T043000Z
UID:xsUy8v0EOivLaeRBP60kTpLR@stanza.co
SUMMARY:Canadians @ Indians
DESCRIPTION:Canadians @ Indians\n\nFollow on MiLB First Pitch: https://stza.co/+xCdU-8\n\nShop: https://stza.co/+xCdU-1W\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144603Z
LAST-MODIFIED:20180213T144603Z
TRANSP:OPAQUE
END:VEVENT
* Canadians @ Indians
<2018-09-02 Sun 17:30-20:30>
:PROPERTIES:
:ID:       j9KqFaOUg3s889YCpQOXgwbw@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Canadians @ Indians Canadians @ Indians

Follow on MiLB First Pitch  https //stza.co/+xCdV-r

Shop  https //stza.co/+xCdV-2q

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Canadians @ Indians
END:VALARM
DTSTART:20180902T223000Z
DTEND:20180903T013000Z
UID:j9KqFaOUg3s889YCpQOXgwbw@stanza.co
SUMMARY:Canadians @ Indians
DESCRIPTION:Canadians @ Indians\n\nFollow on MiLB First Pitch: https://stza.co/+xCdV-r\n\nShop: https://stza.co/+xCdV-2q\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144603Z
LAST-MODIFIED:20180213T144603Z
TRANSP:OPAQUE
END:VEVENT
* Canadians @ Indians
<2018-09-03 Mon 20:30-23:30>
:PROPERTIES:
:ID:       65TK2vKUF3DPdF7wxAymq8Vq@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Canadians @ Indians Canadians @ Indians

Follow on MiLB First Pitch  https //stza.co/+xCdZ-36

Shop  https //stza.co/+xCdZ-6

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Canadians @ Indians
END:VALARM
DTSTART:20180904T013000Z
DTEND:20180904T043000Z
UID:65TK2vKUF3DPdF7wxAymq8Vq@stanza.co
SUMMARY:Canadians @ Indians
DESCRIPTION:Canadians @ Indians\n\nFollow on MiLB First Pitch: https://stza.co/+xCdZ-36\n\nShop: https://stza.co/+xCdZ-6\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144603Z
LAST-MODIFIED:20180213T144603Z
TRANSP:OPAQUE
END:VEVENT
