#+TITLE:       Main Google calendar entries
#+AUTHOR:      Eric S Fraga
#+EMAIL:       e.fraga@ucl.ac.uk
#+DESCRIPTION: converted using the ical2org awk script
#+CATEGORY:    google
#+STARTUP:     hidestars
#+STARTUP:     overview

* COMMENT original iCal preamble

* Kernels @ River Bandits
<2018-04-05 Thu 18:35-21:35>
:PROPERTIES:
:ID:       ZY1a2FD22LQ5qinfswuA7i3f@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Kernels @ River Bandits Kernels @ River Bandits

Follow on MiLB First Pitch  https //stza.co/+wxmN-1z

Shop  https //stza.co/+wxmN-3t

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Kernels @ River Bandits
END:VALARM
DTSTART:20180405T233500Z
DTEND:20180406T023500Z
UID:ZY1a2FD22LQ5qinfswuA7i3f@stanza.co
SUMMARY:Kernels @ River Bandits
DESCRIPTION:Kernels @ River Bandits\n\nFollow on MiLB First Pitch: https://stza.co/+wxmN-1z\n\nShop: https://stza.co/+wxmN-3t\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144951Z
LAST-MODIFIED:20180213T144951Z
TRANSP:OPAQUE
END:VEVENT
* Kernels @ River Bandits
<2018-04-06 Fri 18:35-21:35>
:PROPERTIES:
:ID:       SC-UANY12POcuFInepGd0Eyl@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Kernels @ River Bandits Kernels @ River Bandits

Follow on MiLB First Pitch  https //stza.co/+wxmO-9

Shop  https //stza.co/+wxmO-2r

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Kernels @ River Bandits
END:VALARM
DTSTART:20180406T233500Z
DTEND:20180407T023500Z
UID:SC-UANY12POcuFInepGd0Eyl@stanza.co
SUMMARY:Kernels @ River Bandits
DESCRIPTION:Kernels @ River Bandits\n\nFollow on MiLB First Pitch: https://stza.co/+wxmO-9\n\nShop: https://stza.co/+wxmO-2r\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144951Z
LAST-MODIFIED:20180213T144951Z
TRANSP:OPAQUE
END:VEVENT
* Kernels vs. River Bandits
<2018-04-07 Sat 17:05-20:05>
:PROPERTIES:
:ID:       zETO6vdtLXnrEUEvy6j1eRvu@stanza.co
:LOCATION: Swipe to get tickets for the game tonight. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Kernels vs. River Bandits Kernels vs. River Bandits

Buy tickets here  https //stza.co/~vMUq

Follow on MiLB First Pitch  https //stza.co/+vMUq-3r

Shop  https //stza.co/+vMUq-1Y

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Kernels vs. River Bandits
END:VALARM
DTSTART:20180407T220500Z
DTEND:20180408T010500Z
UID:zETO6vdtLXnrEUEvy6j1eRvu@stanza.co
SUMMARY:Kernels vs. River Bandits
DESCRIPTION:Kernels vs. River Bandits\n\nBuy tickets here: https://stza.co/~vMUq\n\nFollow on MiLB First Pitch: https://stza.co/+vMUq-3r\n\nShop: https://stza.co/+vMUq-1Y\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Swipe to get tickets for the game tonight. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144951Z
LAST-MODIFIED:20180213T144951Z
TRANSP:OPAQUE
END:VEVENT
* Kernels vs. River Bandits
<2018-04-08 Sun 14:05-17:05>
:PROPERTIES:
:ID:       HtQRRw6CrrVv98sS9pNlFXW0@stanza.co
:LOCATION: Swipe for last minute tickets for tonight's game. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Kernels vs. River Bandits Kernels vs. River Bandits

Buy tickets here  https //stza.co/~vMUt

Follow on MiLB First Pitch  https //stza.co/+vMUt-1c

Shop  https //stza.co/+vMUt-1D

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Kernels vs. River Bandits
END:VALARM
DTSTART:20180408T190500Z
DTEND:20180408T220500Z
UID:HtQRRw6CrrVv98sS9pNlFXW0@stanza.co
SUMMARY:Kernels vs. River Bandits
DESCRIPTION:Kernels vs. River Bandits\n\nBuy tickets here: https://stza.co/~vMUt\n\nFollow on MiLB First Pitch: https://stza.co/+vMUt-1c\n\nShop: https://stza.co/+vMUt-1D\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Swipe for last minute tickets for tonight's game. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144951Z
LAST-MODIFIED:20180213T144951Z
TRANSP:OPAQUE
END:VEVENT
* Kernels @ Chiefs
<2018-04-09 Mon 18:30-21:30>
:PROPERTIES:
:ID:       h6fGCQQVBtXTKLvIxMJHNeWz@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Kernels @ Chiefs Kernels @ Chiefs

Follow on MiLB First Pitch  https //stza.co/+xBpR-u

Shop  https //stza.co/+xBpR-24

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Kernels @ Chiefs
END:VALARM
DTSTART:20180409T233000Z
DTEND:20180410T023000Z
UID:h6fGCQQVBtXTKLvIxMJHNeWz@stanza.co
SUMMARY:Kernels @ Chiefs
DESCRIPTION:Kernels @ Chiefs\n\nFollow on MiLB First Pitch: https://stza.co/+xBpR-u\n\nShop: https://stza.co/+xBpR-24\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144951Z
LAST-MODIFIED:20180213T144951Z
TRANSP:OPAQUE
END:VEVENT
* Kernels @ Chiefs
<2018-04-10 Tue 11:00-14:00>
:PROPERTIES:
:ID:       Inreo_V_qso6yu_9hNsswJbP@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Kernels @ Chiefs Kernels @ Chiefs

Follow on MiLB First Pitch  https //stza.co/+xAub-7

Shop  https //stza.co/+xAub-1E

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Kernels @ Chiefs
END:VALARM
DTSTART:20180410T160000Z
DTEND:20180410T190000Z
UID:Inreo_V_qso6yu_9hNsswJbP@stanza.co
SUMMARY:Kernels @ Chiefs
DESCRIPTION:Kernels @ Chiefs\n\nFollow on MiLB First Pitch: https://stza.co/+xAub-7\n\nShop: https://stza.co/+xAub-1E\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144951Z
LAST-MODIFIED:20180213T144951Z
TRANSP:OPAQUE
END:VEVENT
* Kernels @ Chiefs
<2018-04-11 Wed 18:30-21:30>
:PROPERTIES:
:ID:       -dPshasuS6k5AKdqYRSf8DSR@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Kernels @ Chiefs Kernels @ Chiefs

Follow on MiLB First Pitch  https //stza.co/+xAuc-Y

Shop  https //stza.co/+xAuc-

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Kernels @ Chiefs
END:VALARM
DTSTART:20180411T233000Z
DTEND:20180412T023000Z
UID:-dPshasuS6k5AKdqYRSf8DSR@stanza.co
SUMMARY:Kernels @ Chiefs
DESCRIPTION:Kernels @ Chiefs\n\nFollow on MiLB First Pitch: https://stza.co/+xAuc-Y\n\nShop: https://stza.co/+xAuc-\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144951Z
LAST-MODIFIED:20180213T144951Z
TRANSP:OPAQUE
END:VEVENT
* Kernels @ Chiefs
<2018-04-12 Thu 18:30-21:30>
:PROPERTIES:
:ID:       bvvPXyEkH3zKjDd2_04vVCem@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Kernels @ Chiefs Kernels @ Chiefs

Follow on MiLB First Pitch  https //stza.co/+xAud-34

Shop  https //stza.co/+xAud-37

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Kernels @ Chiefs
END:VALARM
DTSTART:20180412T233000Z
DTEND:20180413T023000Z
UID:bvvPXyEkH3zKjDd2_04vVCem@stanza.co
SUMMARY:Kernels @ Chiefs
DESCRIPTION:Kernels @ Chiefs\n\nFollow on MiLB First Pitch: https://stza.co/+xAud-34\n\nShop: https://stza.co/+xAud-37\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144951Z
LAST-MODIFIED:20180213T144951Z
TRANSP:OPAQUE
END:VEVENT
* Kernels vs. LumberKings
<2018-04-13 Fri 18:35-21:35>
:PROPERTIES:
:ID:       LuoM0V8mGH0qiWJlbaDGs6S7@stanza.co
:LOCATION: Ready for the game? Swipe for tickets and more information.
:STATUS:   CONFIRMED
:END:

Kernels vs. LumberKings Kernels vs. LumberKings

Buy tickets here  https //stza.co/~vMUv

Follow on MiLB First Pitch  https //stza.co/+vMUv-o

Shop  https //stza.co/+vMUv-3O

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Kernels vs. LumberKings
END:VALARM
DTSTART:20180413T233500Z
DTEND:20180414T023500Z
UID:LuoM0V8mGH0qiWJlbaDGs6S7@stanza.co
SUMMARY:Kernels vs. LumberKings
DESCRIPTION:Kernels vs. LumberKings\n\nBuy tickets here: https://stza.co/~vMUv\n\nFollow on MiLB First Pitch: https://stza.co/+vMUv-o\n\nShop: https://stza.co/+vMUv-3O\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Swipe for tickets and more information.
STATUS:CONFIRMED
CREATED:20180213T144951Z
LAST-MODIFIED:20180213T144951Z
TRANSP:OPAQUE
END:VEVENT
* Kernels vs. LumberKings
<2018-04-14 Sat 17:05-20:05>
:PROPERTIES:
:ID:       AjckyT64KhQPlkh6e_qboQro@stanza.co
:LOCATION: Looking for something to do tonight? Get tickets here for tonight’s game and view promotions.
:STATUS:   CONFIRMED
:END:

Kernels vs. LumberKings Kernels vs. LumberKings

Buy tickets here  https //stza.co/~vMUx

Follow on MiLB First Pitch  https //stza.co/+vMUx-12

Shop  https //stza.co/+vMUx-3Z

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Kernels vs. LumberKings
END:VALARM
DTSTART:20180414T220500Z
DTEND:20180415T010500Z
UID:AjckyT64KhQPlkh6e_qboQro@stanza.co
SUMMARY:Kernels vs. LumberKings
DESCRIPTION:Kernels vs. LumberKings\n\nBuy tickets here: https://stza.co/~vMUx\n\nFollow on MiLB First Pitch: https://stza.co/+vMUx-12\n\nShop: https://stza.co/+vMUx-3Z\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Looking for something to do tonight? Get tickets here for tonight’s game and view promotions.
STATUS:CONFIRMED
CREATED:20180213T144951Z
LAST-MODIFIED:20180213T144951Z
TRANSP:OPAQUE
END:VEVENT
* Kernels vs. LumberKings
<2018-04-15 Sun 14:05-17:05>
:PROPERTIES:
:ID:       a0mOVAp8iSdNWxn_OafhdNI2@stanza.co
:LOCATION: Great seats still available for tonight’s game. Purchase them here.
:STATUS:   CONFIRMED
:END:

Kernels vs. LumberKings Kernels vs. LumberKings

Buy tickets here  https //stza.co/~vMUy

Follow on MiLB First Pitch  https //stza.co/+vMUy-1s

Shop  https //stza.co/+vMUy-12

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Kernels vs. LumberKings
END:VALARM
DTSTART:20180415T190500Z
DTEND:20180415T220500Z
UID:a0mOVAp8iSdNWxn_OafhdNI2@stanza.co
SUMMARY:Kernels vs. LumberKings
DESCRIPTION:Kernels vs. LumberKings\n\nBuy tickets here: https://stza.co/~vMUy\n\nFollow on MiLB First Pitch: https://stza.co/+vMUy-1s\n\nShop: https://stza.co/+vMUy-12\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Great seats still available for tonight’s game. Purchase them here.
STATUS:CONFIRMED
CREATED:20180213T144951Z
LAST-MODIFIED:20180213T144951Z
TRANSP:OPAQUE
END:VEVENT
* Kernels @ Snappers
<2018-04-17 Tue 18:30-21:30>
:PROPERTIES:
:ID:       YJmJO6tagxzBVm65J_F56cxQ@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Kernels @ Snappers Kernels @ Snappers

Follow on MiLB First Pitch  https //stza.co/+wSL2-L

Shop  https //stza.co/+wSL2-3g

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Kernels @ Snappers
END:VALARM
DTSTART:20180417T233000Z
DTEND:20180418T023000Z
UID:YJmJO6tagxzBVm65J_F56cxQ@stanza.co
SUMMARY:Kernels @ Snappers
DESCRIPTION:Kernels @ Snappers\n\nFollow on MiLB First Pitch: https://stza.co/+wSL2-L\n\nShop: https://stza.co/+wSL2-3g\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144951Z
LAST-MODIFIED:20180213T144951Z
TRANSP:OPAQUE
END:VEVENT
* Kernels @ Snappers
<2018-04-18 Wed 18:30-21:30>
:PROPERTIES:
:ID:       GOaBDmQ8a93VUA2M5rSuGAiA@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Kernels @ Snappers Kernels @ Snappers

Follow on MiLB First Pitch  https //stza.co/+wSL4-3R

Shop  https //stza.co/+wSL4-1N

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Kernels @ Snappers
END:VALARM
DTSTART:20180418T233000Z
DTEND:20180419T023000Z
UID:GOaBDmQ8a93VUA2M5rSuGAiA@stanza.co
SUMMARY:Kernels @ Snappers
DESCRIPTION:Kernels @ Snappers\n\nFollow on MiLB First Pitch: https://stza.co/+wSL4-3R\n\nShop: https://stza.co/+wSL4-1N\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144951Z
LAST-MODIFIED:20180213T144951Z
TRANSP:OPAQUE
END:VEVENT
* Kernels @ Snappers
<2018-04-19 Thu 18:30-21:30>
:PROPERTIES:
:ID:       C17iHqK3p9n7NhcsqLUAzACD@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Kernels @ Snappers Kernels @ Snappers

Follow on MiLB First Pitch  https //stza.co/+wSL5-G

Shop  https //stza.co/+wSL5-Z

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Kernels @ Snappers
END:VALARM
DTSTART:20180419T233000Z
DTEND:20180420T023000Z
UID:C17iHqK3p9n7NhcsqLUAzACD@stanza.co
SUMMARY:Kernels @ Snappers
DESCRIPTION:Kernels @ Snappers\n\nFollow on MiLB First Pitch: https://stza.co/+wSL5-G\n\nShop: https://stza.co/+wSL5-Z\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144951Z
LAST-MODIFIED:20180213T144951Z
TRANSP:OPAQUE
END:VEVENT
* Kernels vs. Cougars
<2018-04-20 Fri 18:35-21:35>
:PROPERTIES:
:ID:       vd7quE8jIwifSMDt-mCnnFkm@stanza.co
:LOCATION: Need something fun to do tonight? Get Kernels tickets here.
:STATUS:   CONFIRMED
:END:

Kernels vs. Cougars Kernels vs. Cougars

Buy tickets here  https //stza.co/~vMUA

Follow on MiLB First Pitch  https //stza.co/+vMUA-d

Shop  https //stza.co/+vMUA-t

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Kernels vs. Cougars
END:VALARM
DTSTART:20180420T233500Z
DTEND:20180421T023500Z
UID:vd7quE8jIwifSMDt-mCnnFkm@stanza.co
SUMMARY:Kernels vs. Cougars
DESCRIPTION:Kernels vs. Cougars\n\nBuy tickets here: https://stza.co/~vMUA\n\nFollow on MiLB First Pitch: https://stza.co/+vMUA-d\n\nShop: https://stza.co/+vMUA-t\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Need something fun to do tonight? Get Kernels tickets here.
STATUS:CONFIRMED
CREATED:20180213T144951Z
LAST-MODIFIED:20180213T144951Z
TRANSP:OPAQUE
END:VEVENT
* Kernels vs. Cougars
<2018-04-21 Sat 17:05-20:05>
:PROPERTIES:
:ID:       KclBZTk4ksPEfKN2QnFjSd17@stanza.co
:LOCATION: Don’t miss out! Kernels tickets still available here.
:STATUS:   CONFIRMED
:END:

Kernels vs. Cougars Kernels vs. Cougars

Buy tickets here  https //stza.co/~vMUD

Follow on MiLB First Pitch  https //stza.co/+vMUD-1V

Shop  https //stza.co/+vMUD-3y

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Kernels vs. Cougars
END:VALARM
DTSTART:20180421T220500Z
DTEND:20180422T010500Z
UID:KclBZTk4ksPEfKN2QnFjSd17@stanza.co
SUMMARY:Kernels vs. Cougars
DESCRIPTION:Kernels vs. Cougars\n\nBuy tickets here: https://stza.co/~vMUD\n\nFollow on MiLB First Pitch: https://stza.co/+vMUD-1V\n\nShop: https://stza.co/+vMUD-3y\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don’t miss out! Kernels tickets still available here.
STATUS:CONFIRMED
CREATED:20180213T144951Z
LAST-MODIFIED:20180213T144951Z
TRANSP:OPAQUE
END:VEVENT
* Kernels vs. Cougars
<2018-04-22 Sun 14:05-17:05>
:PROPERTIES:
:ID:       Xuj4y4z_wHlFe8yIitfuUdfy@stanza.co
:LOCATION: Swipe to get tickets for the game tonight. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Kernels vs. Cougars Kernels vs. Cougars

Buy tickets here  https //stza.co/~vMUF

Follow on MiLB First Pitch  https //stza.co/+vMUF-1O

Shop  https //stza.co/+vMUF-2l

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Kernels vs. Cougars
END:VALARM
DTSTART:20180422T190500Z
DTEND:20180422T220500Z
UID:Xuj4y4z_wHlFe8yIitfuUdfy@stanza.co
SUMMARY:Kernels vs. Cougars
DESCRIPTION:Kernels vs. Cougars\n\nBuy tickets here: https://stza.co/~vMUF\n\nFollow on MiLB First Pitch: https://stza.co/+vMUF-1O\n\nShop: https://stza.co/+vMUF-2l\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Swipe to get tickets for the game tonight. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144951Z
LAST-MODIFIED:20180213T144951Z
TRANSP:OPAQUE
END:VEVENT
* Kernels vs. Bees
<2018-04-23 Mon 18:35-21:35>
:PROPERTIES:
:ID:       sH0AQGowbcF3rxcm6D_rQyCh@stanza.co
:LOCATION: Swipe for last minute tickets for tonight's game. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Kernels vs. Bees Kernels vs. Bees

Buy tickets here  https //stza.co/~vMUH

Follow on MiLB First Pitch  https //stza.co/+vMUH-3p

Shop  https //stza.co/+vMUH-1h

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Kernels vs. Bees
END:VALARM
DTSTART:20180423T233500Z
DTEND:20180424T023500Z
UID:sH0AQGowbcF3rxcm6D_rQyCh@stanza.co
SUMMARY:Kernels vs. Bees
DESCRIPTION:Kernels vs. Bees\n\nBuy tickets here: https://stza.co/~vMUH\n\nFollow on MiLB First Pitch: https://stza.co/+vMUH-3p\n\nShop: https://stza.co/+vMUH-1h\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Swipe for last minute tickets for tonight's game. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144951Z
LAST-MODIFIED:20180213T144951Z
TRANSP:OPAQUE
END:VEVENT
* Kernels vs. Bees
<2018-04-24 Tue 18:35-21:35>
:PROPERTIES:
:ID:       2gPng0owaMyMUyup2xW8ZWlJ@stanza.co
:LOCATION: Ready for the game? Swipe for tickets and more information.
:STATUS:   CONFIRMED
:END:

Kernels vs. Bees Kernels vs. Bees

Buy tickets here  https //stza.co/~vMUJ

Follow on MiLB First Pitch  https //stza.co/+vMUJ-2H

Shop  https //stza.co/+vMUJ-L

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Kernels vs. Bees
END:VALARM
DTSTART:20180424T233500Z
DTEND:20180425T023500Z
UID:2gPng0owaMyMUyup2xW8ZWlJ@stanza.co
SUMMARY:Kernels vs. Bees
DESCRIPTION:Kernels vs. Bees\n\nBuy tickets here: https://stza.co/~vMUJ\n\nFollow on MiLB First Pitch: https://stza.co/+vMUJ-2H\n\nShop: https://stza.co/+vMUJ-L\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Swipe for tickets and more information.
STATUS:CONFIRMED
CREATED:20180213T144951Z
LAST-MODIFIED:20180213T144951Z
TRANSP:OPAQUE
END:VEVENT
* Kernels vs. Bees
<2018-04-25 Wed 18:35-21:35>
:PROPERTIES:
:ID:       rHPl7Eyt8cjW0BNCLOCJv72i@stanza.co
:LOCATION: Looking for something to do tonight? Get tickets here for tonight’s game and view promotions.
:STATUS:   CONFIRMED
:END:

Kernels vs. Bees Kernels vs. Bees

Buy tickets here  https //stza.co/~vMUL

Follow on MiLB First Pitch  https //stza.co/+vMUL-1L

Shop  https //stza.co/+vMUL-3K

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Kernels vs. Bees
END:VALARM
DTSTART:20180425T233500Z
DTEND:20180426T023500Z
UID:rHPl7Eyt8cjW0BNCLOCJv72i@stanza.co
SUMMARY:Kernels vs. Bees
DESCRIPTION:Kernels vs. Bees\n\nBuy tickets here: https://stza.co/~vMUL\n\nFollow on MiLB First Pitch: https://stza.co/+vMUL-1L\n\nShop: https://stza.co/+vMUL-3K\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Looking for something to do tonight? Get tickets here for tonight’s game and view promotions.
STATUS:CONFIRMED
CREATED:20180213T144951Z
LAST-MODIFIED:20180213T144951Z
TRANSP:OPAQUE
END:VEVENT
* Kernels vs. Bees
<2018-04-26 Thu 18:35-21:35>
:PROPERTIES:
:ID:       38933Zl2o81owca18DN8AuEx@stanza.co
:LOCATION: Great seats still available for tonight’s game. Purchase them here.
:STATUS:   CONFIRMED
:END:

Kernels vs. Bees Kernels vs. Bees

Buy tickets here  https //stza.co/~vMUN

Follow on MiLB First Pitch  https //stza.co/+vMUN-2u

Shop  https //stza.co/+vMUN-1j

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Kernels vs. Bees
END:VALARM
DTSTART:20180426T233500Z
DTEND:20180427T023500Z
UID:38933Zl2o81owca18DN8AuEx@stanza.co
SUMMARY:Kernels vs. Bees
DESCRIPTION:Kernels vs. Bees\n\nBuy tickets here: https://stza.co/~vMUN\n\nFollow on MiLB First Pitch: https://stza.co/+vMUN-2u\n\nShop: https://stza.co/+vMUN-1j\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Great seats still available for tonight’s game. Purchase them here.
STATUS:CONFIRMED
CREATED:20180213T144951Z
LAST-MODIFIED:20180213T144951Z
TRANSP:OPAQUE
END:VEVENT
* Kernels @ River Bandits
<2018-04-27 Fri 18:35-21:35>
:PROPERTIES:
:ID:       513YvKR-wI_vuusMiptszdtl@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Kernels @ River Bandits Kernels @ River Bandits

Follow on MiLB First Pitch  https //stza.co/+wxmP-B

Shop  https //stza.co/+wxmP-P

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Kernels @ River Bandits
END:VALARM
DTSTART:20180427T233500Z
DTEND:20180428T023500Z
UID:513YvKR-wI_vuusMiptszdtl@stanza.co
SUMMARY:Kernels @ River Bandits
DESCRIPTION:Kernels @ River Bandits\n\nFollow on MiLB First Pitch: https://stza.co/+wxmP-B\n\nShop: https://stza.co/+wxmP-P\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144951Z
LAST-MODIFIED:20180213T144951Z
TRANSP:OPAQUE
END:VEVENT
* Kernels @ River Bandits
<2018-04-28 Sat 13:15-16:15>
:PROPERTIES:
:ID:       ogdGvGrnPEfSQ-9mTrX02KnI@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Kernels @ River Bandits Kernels @ River Bandits

Follow on MiLB First Pitch  https //stza.co/+wxmQ-24

Shop  https //stza.co/+wxmQ-m

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Kernels @ River Bandits
END:VALARM
DTSTART:20180428T181500Z
DTEND:20180428T211500Z
UID:ogdGvGrnPEfSQ-9mTrX02KnI@stanza.co
SUMMARY:Kernels @ River Bandits
DESCRIPTION:Kernels @ River Bandits\n\nFollow on MiLB First Pitch: https://stza.co/+wxmQ-24\n\nShop: https://stza.co/+wxmQ-m\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144951Z
LAST-MODIFIED:20180213T144951Z
TRANSP:OPAQUE
END:VEVENT
* Kernels @ River Bandits
<2018-04-29 Sun 13:15-16:15>
:PROPERTIES:
:ID:       T5rOKu646zlKYUuTC7kEEi7K@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Kernels @ River Bandits Kernels @ River Bandits

Follow on MiLB First Pitch  https //stza.co/+wxmR-F

Shop  https //stza.co/+wxmR-U

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Kernels @ River Bandits
END:VALARM
DTSTART:20180429T181500Z
DTEND:20180429T211500Z
UID:T5rOKu646zlKYUuTC7kEEi7K@stanza.co
SUMMARY:Kernels @ River Bandits
DESCRIPTION:Kernels @ River Bandits\n\nFollow on MiLB First Pitch: https://stza.co/+wxmR-F\n\nShop: https://stza.co/+wxmR-U\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144951Z
LAST-MODIFIED:20180213T144951Z
TRANSP:OPAQUE
END:VEVENT
* Kernels vs. Cubs
<2018-05-01 Tue 18:35-21:35>
:PROPERTIES:
:ID:       yVINXk8fe5TH1Abh7wCnDwVv@stanza.co
:LOCATION: Need something fun to do tonight? Get Kernels tickets here.
:STATUS:   CONFIRMED
:END:

Kernels vs. Cubs Kernels vs. Cubs

Buy tickets here  https //stza.co/~vMUP

Follow on MiLB First Pitch  https //stza.co/+vMUP-4

Shop  https //stza.co/+vMUP-O

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Kernels vs. Cubs
END:VALARM
DTSTART:20180501T233500Z
DTEND:20180502T023500Z
UID:yVINXk8fe5TH1Abh7wCnDwVv@stanza.co
SUMMARY:Kernels vs. Cubs
DESCRIPTION:Kernels vs. Cubs\n\nBuy tickets here: https://stza.co/~vMUP\n\nFollow on MiLB First Pitch: https://stza.co/+vMUP-4\n\nShop: https://stza.co/+vMUP-O\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Need something fun to do tonight? Get Kernels tickets here.
STATUS:CONFIRMED
CREATED:20180213T144951Z
LAST-MODIFIED:20180213T144951Z
TRANSP:OPAQUE
END:VEVENT
* Kernels vs. Cubs
<2018-05-02 Wed 18:35-21:35>
:PROPERTIES:
:ID:       y4U4zvzAgphrZcIV4RDlLliq@stanza.co
:LOCATION: Don’t miss out! Kernels tickets still available here.
:STATUS:   CONFIRMED
:END:

Kernels vs. Cubs Kernels vs. Cubs

Buy tickets here  https //stza.co/~vMUQ

Follow on MiLB First Pitch  https //stza.co/+vMUQ-3c

Shop  https //stza.co/+vMUQ-2R

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Kernels vs. Cubs
END:VALARM
DTSTART:20180502T233500Z
DTEND:20180503T023500Z
UID:y4U4zvzAgphrZcIV4RDlLliq@stanza.co
SUMMARY:Kernels vs. Cubs
DESCRIPTION:Kernels vs. Cubs\n\nBuy tickets here: https://stza.co/~vMUQ\n\nFollow on MiLB First Pitch: https://stza.co/+vMUQ-3c\n\nShop: https://stza.co/+vMUQ-2R\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don’t miss out! Kernels tickets still available here.
STATUS:CONFIRMED
CREATED:20180213T144951Z
LAST-MODIFIED:20180213T144951Z
TRANSP:OPAQUE
END:VEVENT
* Kernels vs. Cubs
<2018-05-03 Thu 18:35-21:35>
:PROPERTIES:
:ID:       GPi0puWkL8ZPPykneLUhgtuh@stanza.co
:LOCATION: Swipe to get tickets for the game tonight. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Kernels vs. Cubs Kernels vs. Cubs

Buy tickets here  https //stza.co/~vMUS

Follow on MiLB First Pitch  https //stza.co/+vMUS-3W

Shop  https //stza.co/+vMUS-1M

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Kernels vs. Cubs
END:VALARM
DTSTART:20180503T233500Z
DTEND:20180504T023500Z
UID:GPi0puWkL8ZPPykneLUhgtuh@stanza.co
SUMMARY:Kernels vs. Cubs
DESCRIPTION:Kernels vs. Cubs\n\nBuy tickets here: https://stza.co/~vMUS\n\nFollow on MiLB First Pitch: https://stza.co/+vMUS-3W\n\nShop: https://stza.co/+vMUS-1M\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Swipe to get tickets for the game tonight. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144951Z
LAST-MODIFIED:20180213T144951Z
TRANSP:OPAQUE
END:VEVENT
* Kernels vs. Whitecaps
<2018-05-04 Fri 18:35-21:35>
:PROPERTIES:
:ID:       7kDd-cDx3SHd9Hk68xwYcx3S@stanza.co
:LOCATION: Swipe for last minute tickets for tonight's game. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Kernels vs. Whitecaps Kernels vs. Whitecaps

Buy tickets here  https //stza.co/~vMUV

Follow on MiLB First Pitch  https //stza.co/+vMUV-25

Shop  https //stza.co/+vMUV-j

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Kernels vs. Whitecaps
END:VALARM
DTSTART:20180504T233500Z
DTEND:20180505T023500Z
UID:7kDd-cDx3SHd9Hk68xwYcx3S@stanza.co
SUMMARY:Kernels vs. Whitecaps
DESCRIPTION:Kernels vs. Whitecaps\n\nBuy tickets here: https://stza.co/~vMUV\n\nFollow on MiLB First Pitch: https://stza.co/+vMUV-25\n\nShop: https://stza.co/+vMUV-j\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Swipe for last minute tickets for tonight's game. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144951Z
LAST-MODIFIED:20180213T144951Z
TRANSP:OPAQUE
END:VEVENT
* Kernels vs. Whitecaps
<2018-05-05 Sat 18:35-21:35>
:PROPERTIES:
:ID:       8ZtvwdIM9-dgf2JiXmtazma9@stanza.co
:LOCATION: Ready for the game? Swipe for tickets and more information.
:STATUS:   CONFIRMED
:END:

Kernels vs. Whitecaps Kernels vs. Whitecaps

Buy tickets here  https //stza.co/~vMUW

Follow on MiLB First Pitch  https //stza.co/+vMUW-1_

Shop  https //stza.co/+vMUW-1l

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Kernels vs. Whitecaps
END:VALARM
DTSTART:20180505T233500Z
DTEND:20180506T023500Z
UID:8ZtvwdIM9-dgf2JiXmtazma9@stanza.co
SUMMARY:Kernels vs. Whitecaps
DESCRIPTION:Kernels vs. Whitecaps\n\nBuy tickets here: https://stza.co/~vMUW\n\nFollow on MiLB First Pitch: https://stza.co/+vMUW-1_\n\nShop: https://stza.co/+vMUW-1l\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Swipe for tickets and more information.
STATUS:CONFIRMED
CREATED:20180213T144951Z
LAST-MODIFIED:20180213T144951Z
TRANSP:OPAQUE
END:VEVENT
* Kernels vs. Whitecaps
<2018-05-06 Sun 14:05-17:05>
:PROPERTIES:
:ID:       gAFL1dL-mZQ1n_1BrBrTdwe-@stanza.co
:LOCATION: Looking for something to do tonight? Get tickets here for tonight’s game and view promotions.
:STATUS:   CONFIRMED
:END:

Kernels vs. Whitecaps Kernels vs. Whitecaps

Buy tickets here  https //stza.co/~vMUZ

Follow on MiLB First Pitch  https //stza.co/+vMUZ-4

Shop  https //stza.co/+vMUZ-23

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Kernels vs. Whitecaps
END:VALARM
DTSTART:20180506T190500Z
DTEND:20180506T220500Z
UID:gAFL1dL-mZQ1n_1BrBrTdwe-@stanza.co
SUMMARY:Kernels vs. Whitecaps
DESCRIPTION:Kernels vs. Whitecaps\n\nBuy tickets here: https://stza.co/~vMUZ\n\nFollow on MiLB First Pitch: https://stza.co/+vMUZ-4\n\nShop: https://stza.co/+vMUZ-23\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Looking for something to do tonight? Get tickets here for tonight’s game and view promotions.
STATUS:CONFIRMED
CREATED:20180213T144951Z
LAST-MODIFIED:20180213T144951Z
TRANSP:OPAQUE
END:VEVENT
* Kernels @ Dragons
<2018-05-07 Mon 18:00-21:00>
:PROPERTIES:
:ID:       uckAvU5x0nZcjJ303ra83NH3@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Kernels @ Dragons Kernels @ Dragons

Follow on MiLB First Pitch  https //stza.co/+vMWI-3X

Shop  https //stza.co/+vMWI-D

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Kernels @ Dragons
END:VALARM
DTSTART:20180507T230000Z
DTEND:20180508T020000Z
UID:uckAvU5x0nZcjJ303ra83NH3@stanza.co
SUMMARY:Kernels @ Dragons
DESCRIPTION:Kernels @ Dragons\n\nFollow on MiLB First Pitch: https://stza.co/+vMWI-3X\n\nShop: https://stza.co/+vMWI-D\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144951Z
LAST-MODIFIED:20180213T144951Z
TRANSP:OPAQUE
END:VEVENT
* Kernels @ Dragons
<2018-05-08 Tue 18:00-21:00>
:PROPERTIES:
:ID:       BtKIgpPBJ93ws_ZqFqOE5TXW@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Kernels @ Dragons Kernels @ Dragons

Follow on MiLB First Pitch  https //stza.co/+vMWJ-2N

Shop  https //stza.co/+vMWJ-3d

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Kernels @ Dragons
END:VALARM
DTSTART:20180508T230000Z
DTEND:20180509T020000Z
UID:BtKIgpPBJ93ws_ZqFqOE5TXW@stanza.co
SUMMARY:Kernels @ Dragons
DESCRIPTION:Kernels @ Dragons\n\nFollow on MiLB First Pitch: https://stza.co/+vMWJ-2N\n\nShop: https://stza.co/+vMWJ-3d\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144951Z
LAST-MODIFIED:20180213T144951Z
TRANSP:OPAQUE
END:VEVENT
* Kernels @ Dragons
<2018-05-09 Wed 18:00-21:00>
:PROPERTIES:
:ID:       P6b1JXMtcS9ogj5bTUMDem-f@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Kernels @ Dragons Kernels @ Dragons

Follow on MiLB First Pitch  https //stza.co/+vMWK-8

Shop  https //stza.co/+vMWK-1i

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Kernels @ Dragons
END:VALARM
DTSTART:20180509T230000Z
DTEND:20180510T020000Z
UID:P6b1JXMtcS9ogj5bTUMDem-f@stanza.co
SUMMARY:Kernels @ Dragons
DESCRIPTION:Kernels @ Dragons\n\nFollow on MiLB First Pitch: https://stza.co/+vMWK-8\n\nShop: https://stza.co/+vMWK-1i\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144951Z
LAST-MODIFIED:20180213T144951Z
TRANSP:OPAQUE
END:VEVENT
* Kernels @ Hot Rods
<2018-05-10 Thu 18:35-21:35>
:PROPERTIES:
:ID:       NJHSUUchf1pAKXSf-f3g0AOc@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Kernels @ Hot Rods Kernels @ Hot Rods

Follow on MiLB First Pitch  https //stza.co/+vMUg-2C

Shop  https //stza.co/+vMUg-3H

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Kernels @ Hot Rods
END:VALARM
DTSTART:20180510T233500Z
DTEND:20180511T023500Z
UID:NJHSUUchf1pAKXSf-f3g0AOc@stanza.co
SUMMARY:Kernels @ Hot Rods
DESCRIPTION:Kernels @ Hot Rods\n\nFollow on MiLB First Pitch: https://stza.co/+vMUg-2C\n\nShop: https://stza.co/+vMUg-3H\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144951Z
LAST-MODIFIED:20180213T144951Z
TRANSP:OPAQUE
END:VEVENT
* Kernels @ Hot Rods
<2018-05-11 Fri 18:35-21:35>
:PROPERTIES:
:ID:       lQz5P9OXGnB9VCPVCllwjNoD@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Kernels @ Hot Rods Kernels @ Hot Rods

Follow on MiLB First Pitch  https //stza.co/+vMUh-28

Shop  https //stza.co/+vMUh-3s

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Kernels @ Hot Rods
END:VALARM
DTSTART:20180511T233500Z
DTEND:20180512T023500Z
UID:lQz5P9OXGnB9VCPVCllwjNoD@stanza.co
SUMMARY:Kernels @ Hot Rods
DESCRIPTION:Kernels @ Hot Rods\n\nFollow on MiLB First Pitch: https://stza.co/+vMUh-28\n\nShop: https://stza.co/+vMUh-3s\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144951Z
LAST-MODIFIED:20180213T144951Z
TRANSP:OPAQUE
END:VEVENT
* Kernels @ Hot Rods
<2018-05-12 Sat 18:35-21:35>
:PROPERTIES:
:ID:       JewoJxgI4hiidR_vplHNX8O4@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Kernels @ Hot Rods Kernels @ Hot Rods

Follow on MiLB First Pitch  https //stza.co/+vMUi-3w

Shop  https //stza.co/+vMUi-1h

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Kernels @ Hot Rods
END:VALARM
DTSTART:20180512T233500Z
DTEND:20180513T023500Z
UID:JewoJxgI4hiidR_vplHNX8O4@stanza.co
SUMMARY:Kernels @ Hot Rods
DESCRIPTION:Kernels @ Hot Rods\n\nFollow on MiLB First Pitch: https://stza.co/+vMUi-3w\n\nShop: https://stza.co/+vMUi-1h\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144951Z
LAST-MODIFIED:20180213T144951Z
TRANSP:OPAQUE
END:VEVENT
* Kernels vs. River Bandits
<2018-05-14 Mon 18:35-21:35>
:PROPERTIES:
:ID:       kLgni6R1LWeSCne9nonwQOni@stanza.co
:LOCATION: Great seats still available for tonight’s game. Purchase them here.
:STATUS:   CONFIRMED
:END:

Kernels vs. River Bandits Kernels vs. River Bandits

Buy tickets here  https //stza.co/~vMU_

Follow on MiLB First Pitch  https //stza.co/+vMU_-2h

Shop  https //stza.co/+vMU_-1E

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Kernels vs. River Bandits
END:VALARM
DTSTART:20180514T233500Z
DTEND:20180515T023500Z
UID:kLgni6R1LWeSCne9nonwQOni@stanza.co
SUMMARY:Kernels vs. River Bandits
DESCRIPTION:Kernels vs. River Bandits\n\nBuy tickets here: https://stza.co/~vMU_\n\nFollow on MiLB First Pitch: https://stza.co/+vMU_-2h\n\nShop: https://stza.co/+vMU_-1E\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Great seats still available for tonight’s game. Purchase them here.
STATUS:CONFIRMED
CREATED:20180213T144951Z
LAST-MODIFIED:20180213T144951Z
TRANSP:OPAQUE
END:VEVENT
* Kernels vs. River Bandits
<2018-05-15 Tue 18:35-21:35>
:PROPERTIES:
:ID:       DE1hUe1j6pSFB7uBaKw3BdmG@stanza.co
:LOCATION: Need something fun to do tonight? Get Kernels tickets here.
:STATUS:   CONFIRMED
:END:

Kernels vs. River Bandits Kernels vs. River Bandits

Buy tickets here  https //stza.co/~vMV0

Follow on MiLB First Pitch  https //stza.co/+vMV0-2K

Shop  https //stza.co/+vMV0-1_

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Kernels vs. River Bandits
END:VALARM
DTSTART:20180515T233500Z
DTEND:20180516T023500Z
UID:DE1hUe1j6pSFB7uBaKw3BdmG@stanza.co
SUMMARY:Kernels vs. River Bandits
DESCRIPTION:Kernels vs. River Bandits\n\nBuy tickets here: https://stza.co/~vMV0\n\nFollow on MiLB First Pitch: https://stza.co/+vMV0-2K\n\nShop: https://stza.co/+vMV0-1_\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Need something fun to do tonight? Get Kernels tickets here.
STATUS:CONFIRMED
CREATED:20180213T144951Z
LAST-MODIFIED:20180213T144951Z
TRANSP:OPAQUE
END:VEVENT
* Kernels vs. River Bandits
<2018-05-16 Wed 00:05-03:05>
:PROPERTIES:
:ID:       L_SX-aHuzvLDnoIZTCkFUBWX@stanza.co
:LOCATION: Don’t miss out! Kernels tickets still available here.
:STATUS:   CONFIRMED
:END:

Kernels vs. River Bandits Kernels vs. River Bandits

Buy tickets here  https //stza.co/~w0NP

Follow on MiLB First Pitch  https //stza.co/+w0NP-3q

Shop  https //stza.co/+w0NP-2E

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Kernels vs. River Bandits
END:VALARM
DTSTART:20180516T050500Z
DTEND:20180516T080500Z
UID:L_SX-aHuzvLDnoIZTCkFUBWX@stanza.co
SUMMARY:Kernels vs. River Bandits
DESCRIPTION:Kernels vs. River Bandits\n\nBuy tickets here: https://stza.co/~w0NP\n\nFollow on MiLB First Pitch: https://stza.co/+w0NP-3q\n\nShop: https://stza.co/+w0NP-2E\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don’t miss out! Kernels tickets still available here.
STATUS:CONFIRMED
CREATED:20180213T144951Z
LAST-MODIFIED:20180213T144951Z
TRANSP:OPAQUE
END:VEVENT
* Kernels vs. River Bandits
<2018-05-17 Thu 18:35-21:35>
:PROPERTIES:
:ID:       sR2k0p7OKYNMk7P56-BuQW-0@stanza.co
:LOCATION: Swipe to get tickets for the game tonight. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Kernels vs. River Bandits Kernels vs. River Bandits

Buy tickets here  https //stza.co/~w0NR

Follow on MiLB First Pitch  https //stza.co/+w0NR-3F

Shop  https //stza.co/+w0NR-y

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Kernels vs. River Bandits
END:VALARM
DTSTART:20180517T233500Z
DTEND:20180518T023500Z
UID:sR2k0p7OKYNMk7P56-BuQW-0@stanza.co
SUMMARY:Kernels vs. River Bandits
DESCRIPTION:Kernels vs. River Bandits\n\nBuy tickets here: https://stza.co/~w0NR\n\nFollow on MiLB First Pitch: https://stza.co/+w0NR-3F\n\nShop: https://stza.co/+w0NR-y\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Swipe to get tickets for the game tonight. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144951Z
LAST-MODIFIED:20180213T144951Z
TRANSP:OPAQUE
END:VEVENT
* Kernels @ LumberKings
<2018-05-18 Fri 18:30-21:30>
:PROPERTIES:
:ID:       XUjwa4uuxwjmx2498b-KkiOD@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Kernels @ LumberKings Kernels @ LumberKings

Follow on MiLB First Pitch  https //stza.co/+vMWC-2f

Shop  https //stza.co/+vMWC-1M

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Kernels @ LumberKings
END:VALARM
DTSTART:20180518T233000Z
DTEND:20180519T023000Z
UID:XUjwa4uuxwjmx2498b-KkiOD@stanza.co
SUMMARY:Kernels @ LumberKings
DESCRIPTION:Kernels @ LumberKings\n\nFollow on MiLB First Pitch: https://stza.co/+vMWC-2f\n\nShop: https://stza.co/+vMWC-1M\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144951Z
LAST-MODIFIED:20180213T144951Z
TRANSP:OPAQUE
END:VEVENT
* Kernels @ LumberKings
<2018-05-19 Sat 18:30-21:30>
:PROPERTIES:
:ID:       4X30sPtsZteb9jXehnu51WLl@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Kernels @ LumberKings Kernels @ LumberKings

Follow on MiLB First Pitch  https //stza.co/+vMWD-2M

Shop  https //stza.co/+vMWD-3j

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Kernels @ LumberKings
END:VALARM
DTSTART:20180519T233000Z
DTEND:20180520T023000Z
UID:4X30sPtsZteb9jXehnu51WLl@stanza.co
SUMMARY:Kernels @ LumberKings
DESCRIPTION:Kernels @ LumberKings\n\nFollow on MiLB First Pitch: https://stza.co/+vMWD-2M\n\nShop: https://stza.co/+vMWD-3j\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144951Z
LAST-MODIFIED:20180213T144951Z
TRANSP:OPAQUE
END:VEVENT
* Kernels @ LumberKings
<2018-05-20 Sun 14:00-17:00>
:PROPERTIES:
:ID:       Nh9Bnxyqf3lCTDHPwhD9Hg65@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Kernels @ LumberKings Kernels @ LumberKings

Follow on MiLB First Pitch  https //stza.co/+vMWE-1$

Shop  https //stza.co/+vMWE-1E

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Kernels @ LumberKings
END:VALARM
DTSTART:20180520T190000Z
DTEND:20180520T220000Z
UID:Nh9Bnxyqf3lCTDHPwhD9Hg65@stanza.co
SUMMARY:Kernels @ LumberKings
DESCRIPTION:Kernels @ LumberKings\n\nFollow on MiLB First Pitch: https://stza.co/+vMWE-1$\n\nShop: https://stza.co/+vMWE-1E\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144951Z
LAST-MODIFIED:20180213T144951Z
TRANSP:OPAQUE
END:VEVENT
* Kernels @ Cougars
<2018-05-21 Mon 18:30-21:30>
:PROPERTIES:
:ID:       b4RrE4UigOwxkS9yTXBbgZSV@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Kernels @ Cougars Kernels @ Cougars

Follow on MiLB First Pitch  https //stza.co/+xBpA-13

Shop  https //stza.co/+xBpA-2L

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Kernels @ Cougars
END:VALARM
DTSTART:20180521T233000Z
DTEND:20180522T023000Z
UID:b4RrE4UigOwxkS9yTXBbgZSV@stanza.co
SUMMARY:Kernels @ Cougars
DESCRIPTION:Kernels @ Cougars\n\nFollow on MiLB First Pitch: https://stza.co/+xBpA-13\n\nShop: https://stza.co/+xBpA-2L\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144951Z
LAST-MODIFIED:20180213T144951Z
TRANSP:OPAQUE
END:VEVENT
* Kernels @ Cougars
<2018-05-22 Tue 12:00-15:00>
:PROPERTIES:
:ID:       vz1uOk9p2gSYg9ww9VyI-Nnx@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Kernels @ Cougars Kernels @ Cougars

Follow on MiLB First Pitch  https //stza.co/+xBpD-3s

Shop  https //stza.co/+xBpD-3O

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Kernels @ Cougars
END:VALARM
DTSTART:20180522T170000Z
DTEND:20180522T200000Z
UID:vz1uOk9p2gSYg9ww9VyI-Nnx@stanza.co
SUMMARY:Kernels @ Cougars
DESCRIPTION:Kernels @ Cougars\n\nFollow on MiLB First Pitch: https://stza.co/+xBpD-3s\n\nShop: https://stza.co/+xBpD-3O\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144951Z
LAST-MODIFIED:20180213T144951Z
TRANSP:OPAQUE
END:VEVENT
* Kernels @ Cougars
<2018-05-23 Wed 11:00-14:00>
:PROPERTIES:
:ID:       pdMUec5f76wI3moc6PZy_JTP@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Kernels @ Cougars Kernels @ Cougars

Follow on MiLB First Pitch  https //stza.co/+xBpE-1H

Shop  https //stza.co/+xBpE-2w

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Kernels @ Cougars
END:VALARM
DTSTART:20180523T160000Z
DTEND:20180523T190000Z
UID:pdMUec5f76wI3moc6PZy_JTP@stanza.co
SUMMARY:Kernels @ Cougars
DESCRIPTION:Kernels @ Cougars\n\nFollow on MiLB First Pitch: https://stza.co/+xBpE-1H\n\nShop: https://stza.co/+xBpE-2w\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144951Z
LAST-MODIFIED:20180213T144951Z
TRANSP:OPAQUE
END:VEVENT
* Kernels @ Cougars
<2018-05-24 Thu 18:30-21:30>
:PROPERTIES:
:ID:       FfG8oP5-4e4afATsOLdrameT@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Kernels @ Cougars Kernels @ Cougars

Follow on MiLB First Pitch  https //stza.co/+xBpF-1a

Shop  https //stza.co/+xBpF-2t

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Kernels @ Cougars
END:VALARM
DTSTART:20180524T233000Z
DTEND:20180525T023000Z
UID:FfG8oP5-4e4afATsOLdrameT@stanza.co
SUMMARY:Kernels @ Cougars
DESCRIPTION:Kernels @ Cougars\n\nFollow on MiLB First Pitch: https://stza.co/+xBpF-1a\n\nShop: https://stza.co/+xBpF-2t\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144951Z
LAST-MODIFIED:20180213T144951Z
TRANSP:OPAQUE
END:VEVENT
* Kernels vs. LumberKings
<2018-05-25 Fri 18:35-21:35>
:PROPERTIES:
:ID:       M-cmEs_bumTB7BrZd6l61Xtj@stanza.co
:LOCATION: Swipe for last minute tickets for tonight's game. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Kernels vs. LumberKings Kernels vs. LumberKings

Buy tickets here  https //stza.co/~vMV6

Follow on MiLB First Pitch  https //stza.co/+vMV6-3p

Shop  https //stza.co/+vMV6-3e

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Kernels vs. LumberKings
END:VALARM
DTSTART:20180525T233500Z
DTEND:20180526T023500Z
UID:M-cmEs_bumTB7BrZd6l61Xtj@stanza.co
SUMMARY:Kernels vs. LumberKings
DESCRIPTION:Kernels vs. LumberKings\n\nBuy tickets here: https://stza.co/~vMV6\n\nFollow on MiLB First Pitch: https://stza.co/+vMV6-3p\n\nShop: https://stza.co/+vMV6-3e\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Swipe for last minute tickets for tonight's game. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144951Z
LAST-MODIFIED:20180213T144951Z
TRANSP:OPAQUE
END:VEVENT
* Kernels vs. LumberKings
<2018-05-26 Sat 18:35-21:35>
:PROPERTIES:
:ID:       Br2y68ptYA7zK1sMO620szwX@stanza.co
:LOCATION: Ready for the game? Swipe for tickets and more information.
:STATUS:   CONFIRMED
:END:

Kernels vs. LumberKings Kernels vs. LumberKings

Buy tickets here  https //stza.co/~vMV9

Follow on MiLB First Pitch  https //stza.co/+vMV9-E

Shop  https //stza.co/+vMV9-3Y

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Kernels vs. LumberKings
END:VALARM
DTSTART:20180526T233500Z
DTEND:20180527T023500Z
UID:Br2y68ptYA7zK1sMO620szwX@stanza.co
SUMMARY:Kernels vs. LumberKings
DESCRIPTION:Kernels vs. LumberKings\n\nBuy tickets here: https://stza.co/~vMV9\n\nFollow on MiLB First Pitch: https://stza.co/+vMV9-E\n\nShop: https://stza.co/+vMV9-3Y\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Swipe for tickets and more information.
STATUS:CONFIRMED
CREATED:20180213T144951Z
LAST-MODIFIED:20180213T144951Z
TRANSP:OPAQUE
END:VEVENT
* Kernels vs. LumberKings
<2018-05-27 Sun 14:05-17:05>
:PROPERTIES:
:ID:       kJewFUWlv6bYm8kUT1iYQWq0@stanza.co
:LOCATION: Looking for something to do tonight? Get tickets here for tonight’s game and view promotions.
:STATUS:   CONFIRMED
:END:

Kernels vs. LumberKings Kernels vs. LumberKings

Buy tickets here  https //stza.co/~vMVb

Follow on MiLB First Pitch  https //stza.co/+vMVb-C

Shop  https //stza.co/+vMVb-3V

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Kernels vs. LumberKings
END:VALARM
DTSTART:20180527T190500Z
DTEND:20180527T220500Z
UID:kJewFUWlv6bYm8kUT1iYQWq0@stanza.co
SUMMARY:Kernels vs. LumberKings
DESCRIPTION:Kernels vs. LumberKings\n\nBuy tickets here: https://stza.co/~vMVb\n\nFollow on MiLB First Pitch: https://stza.co/+vMVb-C\n\nShop: https://stza.co/+vMVb-3V\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Looking for something to do tonight? Get tickets here for tonight’s game and view promotions.
STATUS:CONFIRMED
CREATED:20180213T144951Z
LAST-MODIFIED:20180213T144951Z
TRANSP:OPAQUE
END:VEVENT
* Kernels vs. LumberKings
<2018-05-28 Mon 12:05-15:05>
:PROPERTIES:
:ID:       W9IHE7W55MBeyOmL9GoYC8z7@stanza.co
:LOCATION: Great seats still available for tonight’s game. Purchase them here.
:STATUS:   CONFIRMED
:END:

Kernels vs. LumberKings Kernels vs. LumberKings

Buy tickets here  https //stza.co/~w0NT

Follow on MiLB First Pitch  https //stza.co/+w0NT-3B

Shop  https //stza.co/+w0NT-1o

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Kernels vs. LumberKings
END:VALARM
DTSTART:20180528T170500Z
DTEND:20180528T200500Z
UID:W9IHE7W55MBeyOmL9GoYC8z7@stanza.co
SUMMARY:Kernels vs. LumberKings
DESCRIPTION:Kernels vs. LumberKings\n\nBuy tickets here: https://stza.co/~w0NT\n\nFollow on MiLB First Pitch: https://stza.co/+w0NT-3B\n\nShop: https://stza.co/+w0NT-1o\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Great seats still available for tonight’s game. Purchase them here.
STATUS:CONFIRMED
CREATED:20180213T144951Z
LAST-MODIFIED:20180213T144951Z
TRANSP:OPAQUE
END:VEVENT
* Kernels vs. Timber Rattlers
<2018-05-29 Tue 18:35-21:35>
:PROPERTIES:
:ID:       tI9DFQa3lBEj8JNoeThGwyjK@stanza.co
:LOCATION: Need something fun to do tonight? Get Kernels tickets here.
:STATUS:   CONFIRMED
:END:

Kernels vs. Timber Rattlers Kernels vs. Timber Rattlers

Buy tickets here  https //stza.co/~vMVe

Follow on MiLB First Pitch  https //stza.co/+vMVe-2L

Shop  https //stza.co/+vMVe-2G

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Kernels vs. Timber Rattlers
END:VALARM
DTSTART:20180529T233500Z
DTEND:20180530T023500Z
UID:tI9DFQa3lBEj8JNoeThGwyjK@stanza.co
SUMMARY:Kernels vs. Timber Rattlers
DESCRIPTION:Kernels vs. Timber Rattlers\n\nBuy tickets here: https://stza.co/~vMVe\n\nFollow on MiLB First Pitch: https://stza.co/+vMVe-2L\n\nShop: https://stza.co/+vMVe-2G\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Need something fun to do tonight? Get Kernels tickets here.
STATUS:CONFIRMED
CREATED:20180213T144951Z
LAST-MODIFIED:20180213T144951Z
TRANSP:OPAQUE
END:VEVENT
* Kernels vs. Timber Rattlers
<2018-05-30 Wed 12:05-15:05>
:PROPERTIES:
:ID:       LaG-km_sF6NX3b1MmZzz8rin@stanza.co
:LOCATION: Don’t miss out! Kernels tickets still available here.
:STATUS:   CONFIRMED
:END:

Kernels vs. Timber Rattlers Kernels vs. Timber Rattlers

Buy tickets here  https //stza.co/~w0NU

Follow on MiLB First Pitch  https //stza.co/+w0NU-3s

Shop  https //stza.co/+w0NU-8

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Kernels vs. Timber Rattlers
END:VALARM
DTSTART:20180530T170500Z
DTEND:20180530T200500Z
UID:LaG-km_sF6NX3b1MmZzz8rin@stanza.co
SUMMARY:Kernels vs. Timber Rattlers
DESCRIPTION:Kernels vs. Timber Rattlers\n\nBuy tickets here: https://stza.co/~w0NU\n\nFollow on MiLB First Pitch: https://stza.co/+w0NU-3s\n\nShop: https://stza.co/+w0NU-8\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don’t miss out! Kernels tickets still available here.
STATUS:CONFIRMED
CREATED:20180213T144951Z
LAST-MODIFIED:20180213T144951Z
TRANSP:OPAQUE
END:VEVENT
* Kernels vs. Timber Rattlers
<2018-05-31 Thu 18:35-21:35>
:PROPERTIES:
:ID:       nqOdBu1iAS5TkCS3dVy2LX9d@stanza.co
:LOCATION: Swipe to get tickets for the game tonight. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Kernels vs. Timber Rattlers Kernels vs. Timber Rattlers

Buy tickets here  https //stza.co/~vMVj

Follow on MiLB First Pitch  https //stza.co/+vMVj-3f

Shop  https //stza.co/+vMVj-2g

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Kernels vs. Timber Rattlers
END:VALARM
DTSTART:20180531T233500Z
DTEND:20180601T023500Z
UID:nqOdBu1iAS5TkCS3dVy2LX9d@stanza.co
SUMMARY:Kernels vs. Timber Rattlers
DESCRIPTION:Kernels vs. Timber Rattlers\n\nBuy tickets here: https://stza.co/~vMVj\n\nFollow on MiLB First Pitch: https://stza.co/+vMVj-3f\n\nShop: https://stza.co/+vMVj-2g\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Swipe to get tickets for the game tonight. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144951Z
LAST-MODIFIED:20180213T144951Z
TRANSP:OPAQUE
END:VEVENT
* Kernels @ Bees
<2018-06-01 Fri 18:30-21:30>
:PROPERTIES:
:ID:       LsiLx5ZiTINBs_4aEV7iD3pl@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Kernels @ Bees Kernels @ Bees

Follow on MiLB First Pitch  https //stza.co/+xBp2-3B

Shop  https //stza.co/+xBp2-n

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Kernels @ Bees
END:VALARM
DTSTART:20180601T233000Z
DTEND:20180602T023000Z
UID:LsiLx5ZiTINBs_4aEV7iD3pl@stanza.co
SUMMARY:Kernels @ Bees
DESCRIPTION:Kernels @ Bees\n\nFollow on MiLB First Pitch: https://stza.co/+xBp2-3B\n\nShop: https://stza.co/+xBp2-n\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144951Z
LAST-MODIFIED:20180213T144951Z
TRANSP:OPAQUE
END:VEVENT
* Kernels @ Bees
<2018-06-02 Sat 18:30-21:30>
:PROPERTIES:
:ID:       gdq0CeQMFzeDMyHqFu2C6uRJ@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Kernels @ Bees Kernels @ Bees

Follow on MiLB First Pitch  https //stza.co/+xBp3-

Shop  https //stza.co/+xBp3-2t

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Kernels @ Bees
END:VALARM
DTSTART:20180602T233000Z
DTEND:20180603T023000Z
UID:gdq0CeQMFzeDMyHqFu2C6uRJ@stanza.co
SUMMARY:Kernels @ Bees
DESCRIPTION:Kernels @ Bees\n\nFollow on MiLB First Pitch: https://stza.co/+xBp3-\n\nShop: https://stza.co/+xBp3-2t\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144951Z
LAST-MODIFIED:20180213T144951Z
TRANSP:OPAQUE
END:VEVENT
* Kernels @ Bees
<2018-06-03 Sun 14:00-17:00>
:PROPERTIES:
:ID:       cvQsdRuRtUZ0vNw9GaN_9F7b@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Kernels @ Bees Kernels @ Bees

Follow on MiLB First Pitch  https //stza.co/+xBp4-Y

Shop  https //stza.co/+xBp4-3b

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Kernels @ Bees
END:VALARM
DTSTART:20180603T190000Z
DTEND:20180603T220000Z
UID:cvQsdRuRtUZ0vNw9GaN_9F7b@stanza.co
SUMMARY:Kernels @ Bees
DESCRIPTION:Kernels @ Bees\n\nFollow on MiLB First Pitch: https://stza.co/+xBp4-Y\n\nShop: https://stza.co/+xBp4-3b\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144951Z
LAST-MODIFIED:20180213T144951Z
TRANSP:OPAQUE
END:VEVENT
* Kernels vs. Snappers
<2018-06-05 Tue 18:35-21:35>
:PROPERTIES:
:ID:       CKtyW025dlpwWir0VUZmQ0pK@stanza.co
:LOCATION: Swipe for last minute tickets for tonight's game. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Kernels vs. Snappers Kernels vs. Snappers

Buy tickets here  https //stza.co/~vMVl

Follow on MiLB First Pitch  https //stza.co/+vMVl-2j

Shop  https //stza.co/+vMVl-2i

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Kernels vs. Snappers
END:VALARM
DTSTART:20180605T233500Z
DTEND:20180606T023500Z
UID:CKtyW025dlpwWir0VUZmQ0pK@stanza.co
SUMMARY:Kernels vs. Snappers
DESCRIPTION:Kernels vs. Snappers\n\nBuy tickets here: https://stza.co/~vMVl\n\nFollow on MiLB First Pitch: https://stza.co/+vMVl-2j\n\nShop: https://stza.co/+vMVl-2i\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Swipe for last minute tickets for tonight's game. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144951Z
LAST-MODIFIED:20180213T144951Z
TRANSP:OPAQUE
END:VEVENT
* Kernels vs. Snappers
<2018-06-06 Wed 12:05-15:05>
:PROPERTIES:
:ID:       ALE4D_De5EdOc21NxrEsyXlw@stanza.co
:LOCATION: Ready for the game? Swipe for tickets and more information.
:STATUS:   CONFIRMED
:END:

Kernels vs. Snappers Kernels vs. Snappers

Buy tickets here  https //stza.co/~w0NX

Follow on MiLB First Pitch  https //stza.co/+w0NX-5

Shop  https //stza.co/+w0NX-13

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Kernels vs. Snappers
END:VALARM
DTSTART:20180606T170500Z
DTEND:20180606T200500Z
UID:ALE4D_De5EdOc21NxrEsyXlw@stanza.co
SUMMARY:Kernels vs. Snappers
DESCRIPTION:Kernels vs. Snappers\n\nBuy tickets here: https://stza.co/~w0NX\n\nFollow on MiLB First Pitch: https://stza.co/+w0NX-5\n\nShop: https://stza.co/+w0NX-13\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Swipe for tickets and more information.
STATUS:CONFIRMED
CREATED:20180213T144951Z
LAST-MODIFIED:20180213T144951Z
TRANSP:OPAQUE
END:VEVENT
* Kernels vs. Snappers
<2018-06-07 Thu 18:35-21:35>
:PROPERTIES:
:ID:       Cvo5RtoeiUBJ-aUyqn_F53B8@stanza.co
:LOCATION: Looking for something to do tonight? Get tickets here for tonight’s game and view promotions.
:STATUS:   CONFIRMED
:END:

Kernels vs. Snappers Kernels vs. Snappers

Buy tickets here  https //stza.co/~vMVp

Follow on MiLB First Pitch  https //stza.co/+vMVp-1O

Shop  https //stza.co/+vMVp-e

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Kernels vs. Snappers
END:VALARM
DTSTART:20180607T233500Z
DTEND:20180608T023500Z
UID:Cvo5RtoeiUBJ-aUyqn_F53B8@stanza.co
SUMMARY:Kernels vs. Snappers
DESCRIPTION:Kernels vs. Snappers\n\nBuy tickets here: https://stza.co/~vMVp\n\nFollow on MiLB First Pitch: https://stza.co/+vMVp-1O\n\nShop: https://stza.co/+vMVp-e\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Looking for something to do tonight? Get tickets here for tonight’s game and view promotions.
STATUS:CONFIRMED
CREATED:20180213T144951Z
LAST-MODIFIED:20180213T144951Z
TRANSP:OPAQUE
END:VEVENT
* Kernels @ Timber Rattlers
<2018-06-08 Fri 19:05-22:05>
:PROPERTIES:
:ID:       T23ZcmM6YHWKD5cYWtMwznVw@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Kernels @ Timber Rattlers Kernels @ Timber Rattlers

Follow on MiLB First Pitch  https //stza.co/+vMXg-30

Shop  https //stza.co/+vMXg-2

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Kernels @ Timber Rattlers
END:VALARM
DTSTART:20180609T000500Z
DTEND:20180609T030500Z
UID:T23ZcmM6YHWKD5cYWtMwznVw@stanza.co
SUMMARY:Kernels @ Timber Rattlers
DESCRIPTION:Kernels @ Timber Rattlers\n\nFollow on MiLB First Pitch: https://stza.co/+vMXg-30\n\nShop: https://stza.co/+vMXg-2\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144951Z
LAST-MODIFIED:20180213T144951Z
TRANSP:OPAQUE
END:VEVENT
* Kernels @ Timber Rattlers
<2018-06-09 Sat 18:35-21:35>
:PROPERTIES:
:ID:       9fo4paQkZrdpLv_tja8AW_u3@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Kernels @ Timber Rattlers Kernels @ Timber Rattlers

Follow on MiLB First Pitch  https //stza.co/+vMXh-1w

Shop  https //stza.co/+vMXh-b

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Kernels @ Timber Rattlers
END:VALARM
DTSTART:20180609T233500Z
DTEND:20180610T023500Z
UID:9fo4paQkZrdpLv_tja8AW_u3@stanza.co
SUMMARY:Kernels @ Timber Rattlers
DESCRIPTION:Kernels @ Timber Rattlers\n\nFollow on MiLB First Pitch: https://stza.co/+vMXh-1w\n\nShop: https://stza.co/+vMXh-b\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144951Z
LAST-MODIFIED:20180213T144951Z
TRANSP:OPAQUE
END:VEVENT
* Kernels @ Timber Rattlers
<2018-06-10 Sun 13:05-16:05>
:PROPERTIES:
:ID:       oB33_4Mu6Uchi5Ku7Xo0RCIK@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Kernels @ Timber Rattlers Kernels @ Timber Rattlers

Follow on MiLB First Pitch  https //stza.co/+vMXi-3e

Shop  https //stza.co/+vMXi-2Q

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Kernels @ Timber Rattlers
END:VALARM
DTSTART:20180610T180500Z
DTEND:20180610T210500Z
UID:oB33_4Mu6Uchi5Ku7Xo0RCIK@stanza.co
SUMMARY:Kernels @ Timber Rattlers
DESCRIPTION:Kernels @ Timber Rattlers\n\nFollow on MiLB First Pitch: https://stza.co/+vMXi-3e\n\nShop: https://stza.co/+vMXi-2Q\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144951Z
LAST-MODIFIED:20180213T144951Z
TRANSP:OPAQUE
END:VEVENT
* Kernels @ Timber Rattlers
<2018-06-11 Mon 12:05-15:05>
:PROPERTIES:
:ID:       wcoQp9tsetd2_oziLkeW_YXu@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Kernels @ Timber Rattlers Kernels @ Timber Rattlers

Follow on MiLB First Pitch  https //stza.co/+vMXj-3s

Shop  https //stza.co/+vMXj-3k

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Kernels @ Timber Rattlers
END:VALARM
DTSTART:20180611T170500Z
DTEND:20180611T200500Z
UID:wcoQp9tsetd2_oziLkeW_YXu@stanza.co
SUMMARY:Kernels @ Timber Rattlers
DESCRIPTION:Kernels @ Timber Rattlers\n\nFollow on MiLB First Pitch: https://stza.co/+vMXj-3s\n\nShop: https://stza.co/+vMXj-3k\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144951Z
LAST-MODIFIED:20180213T144951Z
TRANSP:OPAQUE
END:VEVENT
* Kernels @ Cougars
<2018-06-12 Tue 18:30-21:30>
:PROPERTIES:
:ID:       AarwC50BRiRjZSvDMFUXSRRY@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Kernels @ Cougars Kernels @ Cougars

Follow on MiLB First Pitch  https //stza.co/+xBpG-1B

Shop  https //stza.co/+xBpG-2x

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Kernels @ Cougars
END:VALARM
DTSTART:20180612T233000Z
DTEND:20180613T023000Z
UID:AarwC50BRiRjZSvDMFUXSRRY@stanza.co
SUMMARY:Kernels @ Cougars
DESCRIPTION:Kernels @ Cougars\n\nFollow on MiLB First Pitch: https://stza.co/+xBpG-1B\n\nShop: https://stza.co/+xBpG-2x\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144951Z
LAST-MODIFIED:20180213T144951Z
TRANSP:OPAQUE
END:VEVENT
* Kernels @ Cougars
<2018-06-13 Wed 11:00-14:00>
:PROPERTIES:
:ID:       bXvbFGg62BC2dUqprqWdwc2u@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Kernels @ Cougars Kernels @ Cougars

Follow on MiLB First Pitch  https //stza.co/+xBpH-3e

Shop  https //stza.co/+xBpH-A

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Kernels @ Cougars
END:VALARM
DTSTART:20180613T160000Z
DTEND:20180613T190000Z
UID:bXvbFGg62BC2dUqprqWdwc2u@stanza.co
SUMMARY:Kernels @ Cougars
DESCRIPTION:Kernels @ Cougars\n\nFollow on MiLB First Pitch: https://stza.co/+xBpH-3e\n\nShop: https://stza.co/+xBpH-A\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144951Z
LAST-MODIFIED:20180213T144951Z
TRANSP:OPAQUE
END:VEVENT
* Kernels @ Cougars
<2018-06-14 Thu 18:30-21:30>
:PROPERTIES:
:ID:       x80PfY7-UZ0lLTuha9UAz0nu@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Kernels @ Cougars Kernels @ Cougars

Follow on MiLB First Pitch  https //stza.co/+xBpI-3r

Shop  https //stza.co/+xBpI-3U

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Kernels @ Cougars
END:VALARM
DTSTART:20180614T233000Z
DTEND:20180615T023000Z
UID:x80PfY7-UZ0lLTuha9UAz0nu@stanza.co
SUMMARY:Kernels @ Cougars
DESCRIPTION:Kernels @ Cougars\n\nFollow on MiLB First Pitch: https://stza.co/+xBpI-3r\n\nShop: https://stza.co/+xBpI-3U\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144951Z
LAST-MODIFIED:20180213T144951Z
TRANSP:OPAQUE
END:VEVENT
* Kernels vs. Chiefs
<2018-06-15 Fri 18:35-21:35>
:PROPERTIES:
:ID:       M-lSThZQA0e4v57HGdChiil7@stanza.co
:LOCATION: Great seats still available for tonight’s game. Purchase them here.
:STATUS:   CONFIRMED
:END:

Kernels vs. Chiefs Kernels vs. Chiefs

Buy tickets here  https //stza.co/~vMVr

Follow on MiLB First Pitch  https //stza.co/+vMVr-2F

Shop  https //stza.co/+vMVr-1j

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Kernels vs. Chiefs
END:VALARM
DTSTART:20180615T233500Z
DTEND:20180616T023500Z
UID:M-lSThZQA0e4v57HGdChiil7@stanza.co
SUMMARY:Kernels vs. Chiefs
DESCRIPTION:Kernels vs. Chiefs\n\nBuy tickets here: https://stza.co/~vMVr\n\nFollow on MiLB First Pitch: https://stza.co/+vMVr-2F\n\nShop: https://stza.co/+vMVr-1j\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Great seats still available for tonight’s game. Purchase them here.
STATUS:CONFIRMED
CREATED:20180213T144951Z
LAST-MODIFIED:20180213T144951Z
TRANSP:OPAQUE
END:VEVENT
* Kernels vs. Chiefs
<2018-06-16 Sat 18:35-21:35>
:PROPERTIES:
:ID:       SE0EtZZEVuOtJkZDFPw9b859@stanza.co
:LOCATION: Need something fun to do tonight? Get Kernels tickets here.
:STATUS:   CONFIRMED
:END:

Kernels vs. Chiefs Kernels vs. Chiefs

Buy tickets here  https //stza.co/~vMVs

Follow on MiLB First Pitch  https //stza.co/+vMVs-30

Shop  https //stza.co/+vMVs-1u

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Kernels vs. Chiefs
END:VALARM
DTSTART:20180616T233500Z
DTEND:20180617T023500Z
UID:SE0EtZZEVuOtJkZDFPw9b859@stanza.co
SUMMARY:Kernels vs. Chiefs
DESCRIPTION:Kernels vs. Chiefs\n\nBuy tickets here: https://stza.co/~vMVs\n\nFollow on MiLB First Pitch: https://stza.co/+vMVs-30\n\nShop: https://stza.co/+vMVs-1u\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Need something fun to do tonight? Get Kernels tickets here.
STATUS:CONFIRMED
CREATED:20180213T144951Z
LAST-MODIFIED:20180213T144951Z
TRANSP:OPAQUE
END:VEVENT
* Kernels vs. Chiefs
<2018-06-17 Sun 14:05-17:05>
:PROPERTIES:
:ID:       AZm3Zws9pf2m0n3u_oMermxA@stanza.co
:LOCATION: Don’t miss out! Kernels tickets still available here.
:STATUS:   CONFIRMED
:END:

Kernels vs. Chiefs Kernels vs. Chiefs

Buy tickets here  https //stza.co/~vMVv

Follow on MiLB First Pitch  https //stza.co/+vMVv-10

Shop  https //stza.co/+vMVv-2A

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Kernels vs. Chiefs
END:VALARM
DTSTART:20180617T190500Z
DTEND:20180617T220500Z
UID:AZm3Zws9pf2m0n3u_oMermxA@stanza.co
SUMMARY:Kernels vs. Chiefs
DESCRIPTION:Kernels vs. Chiefs\n\nBuy tickets here: https://stza.co/~vMVv\n\nFollow on MiLB First Pitch: https://stza.co/+vMVv-10\n\nShop: https://stza.co/+vMVv-2A\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don’t miss out! Kernels tickets still available here.
STATUS:CONFIRMED
CREATED:20180213T144951Z
LAST-MODIFIED:20180213T144951Z
TRANSP:OPAQUE
END:VEVENT
* Kernels vs. Timber Rattlers
<2018-06-21 Thu 18:35-21:35>
:PROPERTIES:
:ID:       1FCFVytgjQIOVD78oQ9YUFwT@stanza.co
:LOCATION: Swipe to get tickets for the game tonight. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Kernels vs. Timber Rattlers Kernels vs. Timber Rattlers

Buy tickets here  https //stza.co/~vMVx

Follow on MiLB First Pitch  https //stza.co/+vMVx-1f

Shop  https //stza.co/+vMVx-1A

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Kernels vs. Timber Rattlers
END:VALARM
DTSTART:20180621T233500Z
DTEND:20180622T023500Z
UID:1FCFVytgjQIOVD78oQ9YUFwT@stanza.co
SUMMARY:Kernels vs. Timber Rattlers
DESCRIPTION:Kernels vs. Timber Rattlers\n\nBuy tickets here: https://stza.co/~vMVx\n\nFollow on MiLB First Pitch: https://stza.co/+vMVx-1f\n\nShop: https://stza.co/+vMVx-1A\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Swipe to get tickets for the game tonight. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144951Z
LAST-MODIFIED:20180213T144951Z
TRANSP:OPAQUE
END:VEVENT
* Kernels vs. Timber Rattlers
<2018-06-22 Fri 18:35-21:35>
:PROPERTIES:
:ID:       0dirClM9ejQyInUieJWd-kq1@stanza.co
:LOCATION: Swipe for last minute tickets for tonight's game. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Kernels vs. Timber Rattlers Kernels vs. Timber Rattlers

Buy tickets here  https //stza.co/~vMVy

Follow on MiLB First Pitch  https //stza.co/+vMVy-1_

Shop  https //stza.co/+vMVy-3C

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Kernels vs. Timber Rattlers
END:VALARM
DTSTART:20180622T233500Z
DTEND:20180623T023500Z
UID:0dirClM9ejQyInUieJWd-kq1@stanza.co
SUMMARY:Kernels vs. Timber Rattlers
DESCRIPTION:Kernels vs. Timber Rattlers\n\nBuy tickets here: https://stza.co/~vMVy\n\nFollow on MiLB First Pitch: https://stza.co/+vMVy-1_\n\nShop: https://stza.co/+vMVy-3C\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Swipe for last minute tickets for tonight's game. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144951Z
LAST-MODIFIED:20180213T144951Z
TRANSP:OPAQUE
END:VEVENT
* Kernels vs. Timber Rattlers
<2018-06-23 Sat 18:35-21:35>
:PROPERTIES:
:ID:       gIzzcrW4qMlOtq2XmvXEehxQ@stanza.co
:LOCATION: Ready for the game? Swipe for tickets and more information.
:STATUS:   CONFIRMED
:END:

Kernels vs. Timber Rattlers Kernels vs. Timber Rattlers

Buy tickets here  https //stza.co/~vMVB

Follow on MiLB First Pitch  https //stza.co/+vMVB-1v

Shop  https //stza.co/+vMVB-3d

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Kernels vs. Timber Rattlers
END:VALARM
DTSTART:20180623T233500Z
DTEND:20180624T023500Z
UID:gIzzcrW4qMlOtq2XmvXEehxQ@stanza.co
SUMMARY:Kernels vs. Timber Rattlers
DESCRIPTION:Kernels vs. Timber Rattlers\n\nBuy tickets here: https://stza.co/~vMVB\n\nFollow on MiLB First Pitch: https://stza.co/+vMVB-1v\n\nShop: https://stza.co/+vMVB-3d\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Swipe for tickets and more information.
STATUS:CONFIRMED
CREATED:20180213T144951Z
LAST-MODIFIED:20180213T144951Z
TRANSP:OPAQUE
END:VEVENT
* Kernels vs. Timber Rattlers
<2018-06-24 Sun 14:05-17:05>
:PROPERTIES:
:ID:       1QERUxF8u9OmjdWpZi3tGl_r@stanza.co
:LOCATION: Looking for something to do tonight? Get tickets here for tonight’s game and view promotions.
:STATUS:   CONFIRMED
:END:

Kernels vs. Timber Rattlers Kernels vs. Timber Rattlers

Buy tickets here  https //stza.co/~vMVD

Follow on MiLB First Pitch  https //stza.co/+vMVD-3E

Shop  https //stza.co/+vMVD-5

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Kernels vs. Timber Rattlers
END:VALARM
DTSTART:20180624T190500Z
DTEND:20180624T220500Z
UID:1QERUxF8u9OmjdWpZi3tGl_r@stanza.co
SUMMARY:Kernels vs. Timber Rattlers
DESCRIPTION:Kernels vs. Timber Rattlers\n\nBuy tickets here: https://stza.co/~vMVD\n\nFollow on MiLB First Pitch: https://stza.co/+vMVD-3E\n\nShop: https://stza.co/+vMVD-5\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Looking for something to do tonight? Get tickets here for tonight’s game and view promotions.
STATUS:CONFIRMED
CREATED:20180213T144951Z
LAST-MODIFIED:20180213T144951Z
TRANSP:OPAQUE
END:VEVENT
* Kernels vs. Snappers
<2018-06-25 Mon 18:35-21:35>
:PROPERTIES:
:ID:       kaDbSw3D5CnY0O7CKpbFFu20@stanza.co
:LOCATION: Great seats still available for tonight’s game. Purchase them here.
:STATUS:   CONFIRMED
:END:

Kernels vs. Snappers Kernels vs. Snappers

Buy tickets here  https //stza.co/~vMVF

Follow on MiLB First Pitch  https //stza.co/+vMVF-22

Shop  https //stza.co/+vMVF-38

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Kernels vs. Snappers
END:VALARM
DTSTART:20180625T233500Z
DTEND:20180626T023500Z
UID:kaDbSw3D5CnY0O7CKpbFFu20@stanza.co
SUMMARY:Kernels vs. Snappers
DESCRIPTION:Kernels vs. Snappers\n\nBuy tickets here: https://stza.co/~vMVF\n\nFollow on MiLB First Pitch: https://stza.co/+vMVF-22\n\nShop: https://stza.co/+vMVF-38\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Great seats still available for tonight’s game. Purchase them here.
STATUS:CONFIRMED
CREATED:20180213T144951Z
LAST-MODIFIED:20180213T144951Z
TRANSP:OPAQUE
END:VEVENT
* Kernels vs. Snappers
<2018-06-26 Tue 18:35-21:35>
:PROPERTIES:
:ID:       TbNX6ogPorq5pas5RRVGdafW@stanza.co
:LOCATION: Need something fun to do tonight? Get Kernels tickets here.
:STATUS:   CONFIRMED
:END:

Kernels vs. Snappers Kernels vs. Snappers

Buy tickets here  https //stza.co/~vMVH

Follow on MiLB First Pitch  https //stza.co/+vMVH-1P

Shop  https //stza.co/+vMVH-3W

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Kernels vs. Snappers
END:VALARM
DTSTART:20180626T233500Z
DTEND:20180627T023500Z
UID:TbNX6ogPorq5pas5RRVGdafW@stanza.co
SUMMARY:Kernels vs. Snappers
DESCRIPTION:Kernels vs. Snappers\n\nBuy tickets here: https://stza.co/~vMVH\n\nFollow on MiLB First Pitch: https://stza.co/+vMVH-1P\n\nShop: https://stza.co/+vMVH-3W\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Need something fun to do tonight? Get Kernels tickets here.
STATUS:CONFIRMED
CREATED:20180213T144951Z
LAST-MODIFIED:20180213T144951Z
TRANSP:OPAQUE
END:VEVENT
* Kernels vs. Snappers
<2018-06-27 Wed 12:05-15:05>
:PROPERTIES:
:ID:       pJV_3gKwrG-7FQg96MC2Jsqz@stanza.co
:LOCATION: Don’t miss out! Kernels tickets still available here.
:STATUS:   CONFIRMED
:END:

Kernels vs. Snappers Kernels vs. Snappers

Buy tickets here  https //stza.co/~w0NY

Follow on MiLB First Pitch  https //stza.co/+w0NY-2o

Shop  https //stza.co/+w0NY-G

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Kernels vs. Snappers
END:VALARM
DTSTART:20180627T170500Z
DTEND:20180627T200500Z
UID:pJV_3gKwrG-7FQg96MC2Jsqz@stanza.co
SUMMARY:Kernels vs. Snappers
DESCRIPTION:Kernels vs. Snappers\n\nBuy tickets here: https://stza.co/~w0NY\n\nFollow on MiLB First Pitch: https://stza.co/+w0NY-2o\n\nShop: https://stza.co/+w0NY-G\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don’t miss out! Kernels tickets still available here.
STATUS:CONFIRMED
CREATED:20180213T144951Z
LAST-MODIFIED:20180213T144951Z
TRANSP:OPAQUE
END:VEVENT
* Kernels @ Bees
<2018-06-28 Thu 18:30-21:30>
:PROPERTIES:
:ID:       e-KZeIHuU2yN7NCtWZXFF9LR@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Kernels @ Bees Kernels @ Bees

Follow on MiLB First Pitch  https //stza.co/+xBp5-3e

Shop  https //stza.co/+xBp5-1F

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Kernels @ Bees
END:VALARM
DTSTART:20180628T233000Z
DTEND:20180629T023000Z
UID:e-KZeIHuU2yN7NCtWZXFF9LR@stanza.co
SUMMARY:Kernels @ Bees
DESCRIPTION:Kernels @ Bees\n\nFollow on MiLB First Pitch: https://stza.co/+xBp5-3e\n\nShop: https://stza.co/+xBp5-1F\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144951Z
LAST-MODIFIED:20180213T144951Z
TRANSP:OPAQUE
END:VEVENT
* Kernels @ Bees
<2018-06-29 Fri 18:30-21:30>
:PROPERTIES:
:ID:       fZY9l53E0VfLuN2ktmqw_KLV@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Kernels @ Bees Kernels @ Bees

Follow on MiLB First Pitch  https //stza.co/+xBp7-e

Shop  https //stza.co/+xBp7-34

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Kernels @ Bees
END:VALARM
DTSTART:20180629T233000Z
DTEND:20180630T023000Z
UID:fZY9l53E0VfLuN2ktmqw_KLV@stanza.co
SUMMARY:Kernels @ Bees
DESCRIPTION:Kernels @ Bees\n\nFollow on MiLB First Pitch: https://stza.co/+xBp7-e\n\nShop: https://stza.co/+xBp7-34\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144951Z
LAST-MODIFIED:20180213T144951Z
TRANSP:OPAQUE
END:VEVENT
* Kernels @ Bees
<2018-06-30 Sat 18:30-21:30>
:PROPERTIES:
:ID:       Bb-Y6iTYjWIvTLNkI_RDOZaR@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Kernels @ Bees Kernels @ Bees

Follow on MiLB First Pitch  https //stza.co/+xBp8-3K

Shop  https //stza.co/+xBp8-U

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Kernels @ Bees
END:VALARM
DTSTART:20180630T233000Z
DTEND:20180701T023000Z
UID:Bb-Y6iTYjWIvTLNkI_RDOZaR@stanza.co
SUMMARY:Kernels @ Bees
DESCRIPTION:Kernels @ Bees\n\nFollow on MiLB First Pitch: https://stza.co/+xBp8-3K\n\nShop: https://stza.co/+xBp8-U\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144951Z
LAST-MODIFIED:20180213T144951Z
TRANSP:OPAQUE
END:VEVENT
* Kernels @ Bees
<2018-07-01 Sun 14:00-17:00>
:PROPERTIES:
:ID:       IbzjZhlF_7MMEkAdDPvl-YgT@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Kernels @ Bees Kernels @ Bees

Follow on MiLB First Pitch  https //stza.co/+xBp9-1L

Shop  https //stza.co/+xBp9-2h

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Kernels @ Bees
END:VALARM
DTSTART:20180701T190000Z
DTEND:20180701T220000Z
UID:IbzjZhlF_7MMEkAdDPvl-YgT@stanza.co
SUMMARY:Kernels @ Bees
DESCRIPTION:Kernels @ Bees\n\nFollow on MiLB First Pitch: https://stza.co/+xBp9-1L\n\nShop: https://stza.co/+xBp9-2h\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144951Z
LAST-MODIFIED:20180213T144951Z
TRANSP:OPAQUE
END:VEVENT
* Kernels @ Timber Rattlers
<2018-07-02 Mon 19:05-22:05>
:PROPERTIES:
:ID:       YJHEEln4F325_IigOmDemaza@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Kernels @ Timber Rattlers Kernels @ Timber Rattlers

Follow on MiLB First Pitch  https //stza.co/+vp60-3U

Shop  https //stza.co/+vp60-12

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Kernels @ Timber Rattlers
END:VALARM
DTSTART:20180703T000500Z
DTEND:20180703T030500Z
UID:YJHEEln4F325_IigOmDemaza@stanza.co
SUMMARY:Kernels @ Timber Rattlers
DESCRIPTION:Kernels @ Timber Rattlers\n\nFollow on MiLB First Pitch: https://stza.co/+vp60-3U\n\nShop: https://stza.co/+vp60-12\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144951Z
LAST-MODIFIED:20180213T144951Z
TRANSP:OPAQUE
END:VEVENT
* Kernels @ Timber Rattlers
<2018-07-03 Tue 18:35-21:35>
:PROPERTIES:
:ID:       ssofnlamJW1SiXY6yiyfO3b8@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Kernels @ Timber Rattlers Kernels @ Timber Rattlers

Follow on MiLB First Pitch  https //stza.co/+vp62-3n

Shop  https //stza.co/+vp62-1T

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Kernels @ Timber Rattlers
END:VALARM
DTSTART:20180703T233500Z
DTEND:20180704T023500Z
UID:ssofnlamJW1SiXY6yiyfO3b8@stanza.co
SUMMARY:Kernels @ Timber Rattlers
DESCRIPTION:Kernels @ Timber Rattlers\n\nFollow on MiLB First Pitch: https://stza.co/+vp62-3n\n\nShop: https://stza.co/+vp62-1T\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144951Z
LAST-MODIFIED:20180213T144951Z
TRANSP:OPAQUE
END:VEVENT
* Kernels vs. Timber Rattlers
<2018-07-04 Wed 17:05-20:05>
:PROPERTIES:
:ID:       3YT0b0dSElP0puXFosXMO0Hy@stanza.co
:LOCATION: Swipe to get tickets for the game tonight. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Kernels vs. Timber Rattlers Kernels vs. Timber Rattlers

Buy tickets here  https //stza.co/~vMVL

Follow on MiLB First Pitch  https //stza.co/+vMVL-u

Shop  https //stza.co/+vMVL-1U

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Kernels vs. Timber Rattlers
END:VALARM
DTSTART:20180704T220500Z
DTEND:20180705T010500Z
UID:3YT0b0dSElP0puXFosXMO0Hy@stanza.co
SUMMARY:Kernels vs. Timber Rattlers
DESCRIPTION:Kernels vs. Timber Rattlers\n\nBuy tickets here: https://stza.co/~vMVL\n\nFollow on MiLB First Pitch: https://stza.co/+vMVL-u\n\nShop: https://stza.co/+vMVL-1U\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Swipe to get tickets for the game tonight. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144951Z
LAST-MODIFIED:20180213T144951Z
TRANSP:OPAQUE
END:VEVENT
* Kernels vs. Timber Rattlers
<2018-07-05 Thu 18:35-21:35>
:PROPERTIES:
:ID:       QttThZUsPIQilZ6Uf7E-cnHn@stanza.co
:LOCATION: Swipe for last minute tickets for tonight's game. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Kernels vs. Timber Rattlers Kernels vs. Timber Rattlers

Buy tickets here  https //stza.co/~vMVN

Follow on MiLB First Pitch  https //stza.co/+vMVN-3T

Shop  https //stza.co/+vMVN-y

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Kernels vs. Timber Rattlers
END:VALARM
DTSTART:20180705T233500Z
DTEND:20180706T023500Z
UID:QttThZUsPIQilZ6Uf7E-cnHn@stanza.co
SUMMARY:Kernels vs. Timber Rattlers
DESCRIPTION:Kernels vs. Timber Rattlers\n\nBuy tickets here: https://stza.co/~vMVN\n\nFollow on MiLB First Pitch: https://stza.co/+vMVN-3T\n\nShop: https://stza.co/+vMVN-y\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Swipe for last minute tickets for tonight's game. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144951Z
LAST-MODIFIED:20180213T144951Z
TRANSP:OPAQUE
END:VEVENT
* Kernels @ Cougars
<2018-07-06 Fri 18:30-21:30>
:PROPERTIES:
:ID:       9zX44UeebycwStX4eOwUjQf7@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Kernels @ Cougars Kernels @ Cougars

Follow on MiLB First Pitch  https //stza.co/+xBpM-2g

Shop  https //stza.co/+xBpM-1F

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Kernels @ Cougars
END:VALARM
DTSTART:20180706T233000Z
DTEND:20180707T023000Z
UID:9zX44UeebycwStX4eOwUjQf7@stanza.co
SUMMARY:Kernels @ Cougars
DESCRIPTION:Kernels @ Cougars\n\nFollow on MiLB First Pitch: https://stza.co/+xBpM-2g\n\nShop: https://stza.co/+xBpM-1F\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144951Z
LAST-MODIFIED:20180213T144951Z
TRANSP:OPAQUE
END:VEVENT
* Kernels @ Cougars
<2018-07-07 Sat 18:30-21:30>
:PROPERTIES:
:ID:       ResSrr9ZMCKCPJeXC4eax0aD@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Kernels @ Cougars Kernels @ Cougars

Follow on MiLB First Pitch  https //stza.co/+xBpO-3i

Shop  https //stza.co/+xBpO-t

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Kernels @ Cougars
END:VALARM
DTSTART:20180707T233000Z
DTEND:20180708T023000Z
UID:ResSrr9ZMCKCPJeXC4eax0aD@stanza.co
SUMMARY:Kernels @ Cougars
DESCRIPTION:Kernels @ Cougars\n\nFollow on MiLB First Pitch: https://stza.co/+xBpO-3i\n\nShop: https://stza.co/+xBpO-t\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144951Z
LAST-MODIFIED:20180213T144951Z
TRANSP:OPAQUE
END:VEVENT
* Kernels @ Cougars
<2018-07-08 Sun 13:00-16:00>
:PROPERTIES:
:ID:       d4cKPtPpK3gLfIxwSzJyuwlb@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Kernels @ Cougars Kernels @ Cougars

Follow on MiLB First Pitch  https //stza.co/+xBpP-1d

Shop  https //stza.co/+xBpP-u

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Kernels @ Cougars
END:VALARM
DTSTART:20180708T180000Z
DTEND:20180708T210000Z
UID:d4cKPtPpK3gLfIxwSzJyuwlb@stanza.co
SUMMARY:Kernels @ Cougars
DESCRIPTION:Kernels @ Cougars\n\nFollow on MiLB First Pitch: https://stza.co/+xBpP-1d\n\nShop: https://stza.co/+xBpP-u\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144951Z
LAST-MODIFIED:20180213T144951Z
TRANSP:OPAQUE
END:VEVENT
* Kernels @ Cougars
<2018-07-09 Mon 12:00-15:00>
:PROPERTIES:
:ID:       NYX_XMnqz_K_sn_yk4WH9LrR@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Kernels @ Cougars Kernels @ Cougars

Follow on MiLB First Pitch  https //stza.co/+xBpQ-3k

Shop  https //stza.co/+xBpQ-35

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Kernels @ Cougars
END:VALARM
DTSTART:20180709T170000Z
DTEND:20180709T200000Z
UID:NYX_XMnqz_K_sn_yk4WH9LrR@stanza.co
SUMMARY:Kernels @ Cougars
DESCRIPTION:Kernels @ Cougars\n\nFollow on MiLB First Pitch: https://stza.co/+xBpQ-3k\n\nShop: https://stza.co/+xBpQ-35\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144951Z
LAST-MODIFIED:20180213T144951Z
TRANSP:OPAQUE
END:VEVENT
* Kernels vs. TinCaps
<2018-07-11 Wed 18:35-21:35>
:PROPERTIES:
:ID:       At1SkxdZC7sso4BLuC1hNa5N@stanza.co
:LOCATION: Ready for the game? Swipe for tickets and more information.
:STATUS:   CONFIRMED
:END:

Kernels vs. TinCaps Kernels vs. TinCaps

Buy tickets here  https //stza.co/~vMVO

Follow on MiLB First Pitch  https //stza.co/+vMVO-15

Shop  https //stza.co/+vMVO-1B

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Kernels vs. TinCaps
END:VALARM
DTSTART:20180711T233500Z
DTEND:20180712T023500Z
UID:At1SkxdZC7sso4BLuC1hNa5N@stanza.co
SUMMARY:Kernels vs. TinCaps
DESCRIPTION:Kernels vs. TinCaps\n\nBuy tickets here: https://stza.co/~vMVO\n\nFollow on MiLB First Pitch: https://stza.co/+vMVO-15\n\nShop: https://stza.co/+vMVO-1B\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Swipe for tickets and more information.
STATUS:CONFIRMED
CREATED:20180213T144951Z
LAST-MODIFIED:20180213T144951Z
TRANSP:OPAQUE
END:VEVENT
* Kernels vs. TinCaps
<2018-07-12 Thu 18:35-21:35>
:PROPERTIES:
:ID:       wKoeYB9L6HyQosjLnyJVzTpv@stanza.co
:LOCATION: Looking for something to do tonight? Get tickets here for tonight’s game and view promotions.
:STATUS:   CONFIRMED
:END:

Kernels vs. TinCaps Kernels vs. TinCaps

Buy tickets here  https //stza.co/~vMVR

Follow on MiLB First Pitch  https //stza.co/+vMVR-34

Shop  https //stza.co/+vMVR-3H

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Kernels vs. TinCaps
END:VALARM
DTSTART:20180712T233500Z
DTEND:20180713T023500Z
UID:wKoeYB9L6HyQosjLnyJVzTpv@stanza.co
SUMMARY:Kernels vs. TinCaps
DESCRIPTION:Kernels vs. TinCaps\n\nBuy tickets here: https://stza.co/~vMVR\n\nFollow on MiLB First Pitch: https://stza.co/+vMVR-34\n\nShop: https://stza.co/+vMVR-3H\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Looking for something to do tonight? Get tickets here for tonight’s game and view promotions.
STATUS:CONFIRMED
CREATED:20180213T144951Z
LAST-MODIFIED:20180213T144951Z
TRANSP:OPAQUE
END:VEVENT
* Kernels vs. TinCaps
<2018-07-13 Fri 18:35-21:35>
:PROPERTIES:
:ID:       -kV9-ufn9v2WMZ7cVh4XJuux@stanza.co
:LOCATION: Great seats still available for tonight’s game. Purchase them here.
:STATUS:   CONFIRMED
:END:

Kernels vs. TinCaps Kernels vs. TinCaps

Buy tickets here  https //stza.co/~vMVT

Follow on MiLB First Pitch  https //stza.co/+vMVT-2Y

Shop  https //stza.co/+vMVT-2W

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Kernels vs. TinCaps
END:VALARM
DTSTART:20180713T233500Z
DTEND:20180714T023500Z
UID:-kV9-ufn9v2WMZ7cVh4XJuux@stanza.co
SUMMARY:Kernels vs. TinCaps
DESCRIPTION:Kernels vs. TinCaps\n\nBuy tickets here: https://stza.co/~vMVT\n\nFollow on MiLB First Pitch: https://stza.co/+vMVT-2Y\n\nShop: https://stza.co/+vMVT-2W\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Great seats still available for tonight’s game. Purchase them here.
STATUS:CONFIRMED
CREATED:20180213T144951Z
LAST-MODIFIED:20180213T144951Z
TRANSP:OPAQUE
END:VEVENT
* Kernels vs. Captains
<2018-07-14 Sat 18:35-21:35>
:PROPERTIES:
:ID:       HvG8ISTekz8Xf61dqGxpMpU0@stanza.co
:LOCATION: Need something fun to do tonight? Get Kernels tickets here.
:STATUS:   CONFIRMED
:END:

Kernels vs. Captains Kernels vs. Captains

Buy tickets here  https //stza.co/~vMVU

Follow on MiLB First Pitch  https //stza.co/+vMVU-3b

Shop  https //stza.co/+vMVU-3m

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Kernels vs. Captains
END:VALARM
DTSTART:20180714T233500Z
DTEND:20180715T023500Z
UID:HvG8ISTekz8Xf61dqGxpMpU0@stanza.co
SUMMARY:Kernels vs. Captains
DESCRIPTION:Kernels vs. Captains\n\nBuy tickets here: https://stza.co/~vMVU\n\nFollow on MiLB First Pitch: https://stza.co/+vMVU-3b\n\nShop: https://stza.co/+vMVU-3m\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Need something fun to do tonight? Get Kernels tickets here.
STATUS:CONFIRMED
CREATED:20180213T144951Z
LAST-MODIFIED:20180213T144951Z
TRANSP:OPAQUE
END:VEVENT
* Kernels vs. Captains
<2018-07-15 Sun 14:05-17:05>
:PROPERTIES:
:ID:       XN3V1YY4Hvf5gbeXXHIHOAWt@stanza.co
:LOCATION: Don’t miss out! Kernels tickets still available here.
:STATUS:   CONFIRMED
:END:

Kernels vs. Captains Kernels vs. Captains

Buy tickets here  https //stza.co/~vMVX

Follow on MiLB First Pitch  https //stza.co/+vMVX-1I

Shop  https //stza.co/+vMVX-4

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Kernels vs. Captains
END:VALARM
DTSTART:20180715T190500Z
DTEND:20180715T220500Z
UID:XN3V1YY4Hvf5gbeXXHIHOAWt@stanza.co
SUMMARY:Kernels vs. Captains
DESCRIPTION:Kernels vs. Captains\n\nBuy tickets here: https://stza.co/~vMVX\n\nFollow on MiLB First Pitch: https://stza.co/+vMVX-1I\n\nShop: https://stza.co/+vMVX-4\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don’t miss out! Kernels tickets still available here.
STATUS:CONFIRMED
CREATED:20180213T144951Z
LAST-MODIFIED:20180213T144951Z
TRANSP:OPAQUE
END:VEVENT
* Kernels vs. Captains
<2018-07-16 Mon 11:05-14:05>
:PROPERTIES:
:ID:       ftz1VqmGNdk5eeeWdESZQeof@stanza.co
:LOCATION: Swipe to get tickets for the game tonight. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Kernels vs. Captains Kernels vs. Captains

Buy tickets here  https //stza.co/~vMVZ

Follow on MiLB First Pitch  https //stza.co/+vMVZ-1f

Shop  https //stza.co/+vMVZ-7

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Kernels vs. Captains
END:VALARM
DTSTART:20180716T160500Z
DTEND:20180716T190500Z
UID:ftz1VqmGNdk5eeeWdESZQeof@stanza.co
SUMMARY:Kernels vs. Captains
DESCRIPTION:Kernels vs. Captains\n\nBuy tickets here: https://stza.co/~vMVZ\n\nFollow on MiLB First Pitch: https://stza.co/+vMVZ-1f\n\nShop: https://stza.co/+vMVZ-7\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Swipe to get tickets for the game tonight. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144951Z
LAST-MODIFIED:20180213T144951Z
TRANSP:OPAQUE
END:VEVENT
* Kernels @ Loons
<2018-07-18 Wed 18:05-21:05>
:PROPERTIES:
:ID:       3rurlRvvq_cNUYTs3STTj0Dx@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Kernels @ Loons Kernels @ Loons

Follow on MiLB First Pitch  https //stza.co/+vMWL-z

Shop  https //stza.co/+vMWL-2d

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Kernels @ Loons
END:VALARM
DTSTART:20180718T230500Z
DTEND:20180719T020500Z
UID:3rurlRvvq_cNUYTs3STTj0Dx@stanza.co
SUMMARY:Kernels @ Loons
DESCRIPTION:Kernels @ Loons\n\nFollow on MiLB First Pitch: https://stza.co/+vMWL-z\n\nShop: https://stza.co/+vMWL-2d\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144951Z
LAST-MODIFIED:20180213T144951Z
TRANSP:OPAQUE
END:VEVENT
* Kernels @ Loons
<2018-07-19 Thu 18:05-21:05>
:PROPERTIES:
:ID:       7DgznrTvHr-aXQYDFdvTy_by@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Kernels @ Loons Kernels @ Loons

Follow on MiLB First Pitch  https //stza.co/+vMWM-2i

Shop  https //stza.co/+vMWM-2B

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Kernels @ Loons
END:VALARM
DTSTART:20180719T230500Z
DTEND:20180720T020500Z
UID:7DgznrTvHr-aXQYDFdvTy_by@stanza.co
SUMMARY:Kernels @ Loons
DESCRIPTION:Kernels @ Loons\n\nFollow on MiLB First Pitch: https://stza.co/+vMWM-2i\n\nShop: https://stza.co/+vMWM-2B\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144951Z
LAST-MODIFIED:20180213T144951Z
TRANSP:OPAQUE
END:VEVENT
* Kernels @ Loons
<2018-07-20 Fri 18:05-21:05>
:PROPERTIES:
:ID:       uUl-RUli94-72g8J2pdODscd@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Kernels @ Loons Kernels @ Loons

Follow on MiLB First Pitch  https //stza.co/+vMWN-1i

Shop  https //stza.co/+vMWN-d

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Kernels @ Loons
END:VALARM
DTSTART:20180720T230500Z
DTEND:20180721T020500Z
UID:uUl-RUli94-72g8J2pdODscd@stanza.co
SUMMARY:Kernels @ Loons
DESCRIPTION:Kernels @ Loons\n\nFollow on MiLB First Pitch: https://stza.co/+vMWN-1i\n\nShop: https://stza.co/+vMWN-d\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144951Z
LAST-MODIFIED:20180213T144951Z
TRANSP:OPAQUE
END:VEVENT
* Kernels @ Lugnuts
<2018-07-21 Sat 18:05-21:05>
:PROPERTIES:
:ID:       vf1FpeVnLYJmCHgPjz231XoY@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Kernels @ Lugnuts Kernels @ Lugnuts

Follow on MiLB First Pitch  https //stza.co/+vMWZ-3I

Shop  https //stza.co/+vMWZ-3p

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Kernels @ Lugnuts
END:VALARM
DTSTART:20180721T230500Z
DTEND:20180722T020500Z
UID:vf1FpeVnLYJmCHgPjz231XoY@stanza.co
SUMMARY:Kernels @ Lugnuts
DESCRIPTION:Kernels @ Lugnuts\n\nFollow on MiLB First Pitch: https://stza.co/+vMWZ-3I\n\nShop: https://stza.co/+vMWZ-3p\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144951Z
LAST-MODIFIED:20180213T144951Z
TRANSP:OPAQUE
END:VEVENT
* Kernels @ Lugnuts
<2018-07-22 Sun 12:05-15:05>
:PROPERTIES:
:ID:       225JE9jmwclGlKhNaWYDgpAw@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Kernels @ Lugnuts Kernels @ Lugnuts

Follow on MiLB First Pitch  https //stza.co/+vMW_-2s

Shop  https //stza.co/+vMW_-2u

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Kernels @ Lugnuts
END:VALARM
DTSTART:20180722T170500Z
DTEND:20180722T200500Z
UID:225JE9jmwclGlKhNaWYDgpAw@stanza.co
SUMMARY:Kernels @ Lugnuts
DESCRIPTION:Kernels @ Lugnuts\n\nFollow on MiLB First Pitch: https://stza.co/+vMW_-2s\n\nShop: https://stza.co/+vMW_-2u\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144951Z
LAST-MODIFIED:20180213T144951Z
TRANSP:OPAQUE
END:VEVENT
* Kernels @ Lugnuts
<2018-07-23 Mon 11:05-14:05>
:PROPERTIES:
:ID:       Sc9AGG46HGxb6-YaWnuTwQNd@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Kernels @ Lugnuts Kernels @ Lugnuts

Follow on MiLB First Pitch  https //stza.co/+vMW$-26

Shop  https //stza.co/+vMW$-3n

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Kernels @ Lugnuts
END:VALARM
DTSTART:20180723T160500Z
DTEND:20180723T190500Z
UID:Sc9AGG46HGxb6-YaWnuTwQNd@stanza.co
SUMMARY:Kernels @ Lugnuts
DESCRIPTION:Kernels @ Lugnuts\n\nFollow on MiLB First Pitch: https://stza.co/+vMW$-26\n\nShop: https://stza.co/+vMW$-3n\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144951Z
LAST-MODIFIED:20180213T144951Z
TRANSP:OPAQUE
END:VEVENT
* Kernels vs. LumberKings
<2018-07-25 Wed 18:35-21:35>
:PROPERTIES:
:ID:       muwZf8nriNaS9t4qU938boAw@stanza.co
:LOCATION: Swipe for last minute tickets for tonight's game. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Kernels vs. LumberKings Kernels vs. LumberKings

Buy tickets here  https //stza.co/~vMV$

Follow on MiLB First Pitch  https //stza.co/+vMV$-37

Shop  https //stza.co/+vMV$-3E

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Kernels vs. LumberKings
END:VALARM
DTSTART:20180725T233500Z
DTEND:20180726T023500Z
UID:muwZf8nriNaS9t4qU938boAw@stanza.co
SUMMARY:Kernels vs. LumberKings
DESCRIPTION:Kernels vs. LumberKings\n\nBuy tickets here: https://stza.co/~vMV$\n\nFollow on MiLB First Pitch: https://stza.co/+vMV$-37\n\nShop: https://stza.co/+vMV$-3E\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Swipe for last minute tickets for tonight's game. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144951Z
LAST-MODIFIED:20180213T144951Z
TRANSP:OPAQUE
END:VEVENT
* Kernels vs. LumberKings
<2018-07-26 Thu 18:35-21:35>
:PROPERTIES:
:ID:       CXmBh3MRmdefXSuuzMa0D8XZ@stanza.co
:LOCATION: Ready for the game? Swipe for tickets and more information.
:STATUS:   CONFIRMED
:END:

Kernels vs. LumberKings Kernels vs. LumberKings

Buy tickets here  https //stza.co/~vMW1

Follow on MiLB First Pitch  https //stza.co/+vMW1-25

Shop  https //stza.co/+vMW1-2g

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Kernels vs. LumberKings
END:VALARM
DTSTART:20180726T233500Z
DTEND:20180727T023500Z
UID:CXmBh3MRmdefXSuuzMa0D8XZ@stanza.co
SUMMARY:Kernels vs. LumberKings
DESCRIPTION:Kernels vs. LumberKings\n\nBuy tickets here: https://stza.co/~vMW1\n\nFollow on MiLB First Pitch: https://stza.co/+vMW1-25\n\nShop: https://stza.co/+vMW1-2g\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Swipe for tickets and more information.
STATUS:CONFIRMED
CREATED:20180213T144951Z
LAST-MODIFIED:20180213T144951Z
TRANSP:OPAQUE
END:VEVENT
* Kernels vs. LumberKings
<2018-07-27 Fri 18:35-21:35>
:PROPERTIES:
:ID:       e0Bz21xC25XBcskzziBP8P8m@stanza.co
:LOCATION: Looking for something to do tonight? Get tickets here for tonight’s game and view promotions.
:STATUS:   CONFIRMED
:END:

Kernels vs. LumberKings Kernels vs. LumberKings

Buy tickets here  https //stza.co/~vMW3

Follow on MiLB First Pitch  https //stza.co/+vMW3-4

Shop  https //stza.co/+vMW3-3C

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Kernels vs. LumberKings
END:VALARM
DTSTART:20180727T233500Z
DTEND:20180728T023500Z
UID:e0Bz21xC25XBcskzziBP8P8m@stanza.co
SUMMARY:Kernels vs. LumberKings
DESCRIPTION:Kernels vs. LumberKings\n\nBuy tickets here: https://stza.co/~vMW3\n\nFollow on MiLB First Pitch: https://stza.co/+vMW3-4\n\nShop: https://stza.co/+vMW3-3C\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Looking for something to do tonight? Get tickets here for tonight’s game and view promotions.
STATUS:CONFIRMED
CREATED:20180213T144951Z
LAST-MODIFIED:20180213T144951Z
TRANSP:OPAQUE
END:VEVENT
* Kernels vs. River Bandits
<2018-07-28 Sat 18:35-21:35>
:PROPERTIES:
:ID:       eyGVGABxOrIoT-Q1lFEw96qS@stanza.co
:LOCATION: Great seats still available for tonight’s game. Purchase them here.
:STATUS:   CONFIRMED
:END:

Kernels vs. River Bandits Kernels vs. River Bandits

Buy tickets here  https //stza.co/~vMW5

Follow on MiLB First Pitch  https //stza.co/+vMW5-1l

Shop  https //stza.co/+vMW5-2l

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Kernels vs. River Bandits
END:VALARM
DTSTART:20180728T233500Z
DTEND:20180729T023500Z
UID:eyGVGABxOrIoT-Q1lFEw96qS@stanza.co
SUMMARY:Kernels vs. River Bandits
DESCRIPTION:Kernels vs. River Bandits\n\nBuy tickets here: https://stza.co/~vMW5\n\nFollow on MiLB First Pitch: https://stza.co/+vMW5-1l\n\nShop: https://stza.co/+vMW5-2l\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Great seats still available for tonight’s game. Purchase them here.
STATUS:CONFIRMED
CREATED:20180213T144951Z
LAST-MODIFIED:20180213T144951Z
TRANSP:OPAQUE
END:VEVENT
* Kernels vs. River Bandits
<2018-07-29 Sun 14:05-17:05>
:PROPERTIES:
:ID:       -p0EAJOY4SIT356ts-k4DRIm@stanza.co
:LOCATION: Need something fun to do tonight? Get Kernels tickets here.
:STATUS:   CONFIRMED
:END:

Kernels vs. River Bandits Kernels vs. River Bandits

Buy tickets here  https //stza.co/~vMW6

Follow on MiLB First Pitch  https //stza.co/+vMW6-1W

Shop  https //stza.co/+vMW6-1K

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Kernels vs. River Bandits
END:VALARM
DTSTART:20180729T190500Z
DTEND:20180729T220500Z
UID:-p0EAJOY4SIT356ts-k4DRIm@stanza.co
SUMMARY:Kernels vs. River Bandits
DESCRIPTION:Kernels vs. River Bandits\n\nBuy tickets here: https://stza.co/~vMW6\n\nFollow on MiLB First Pitch: https://stza.co/+vMW6-1W\n\nShop: https://stza.co/+vMW6-1K\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Need something fun to do tonight? Get Kernels tickets here.
STATUS:CONFIRMED
CREATED:20180213T144951Z
LAST-MODIFIED:20180213T144951Z
TRANSP:OPAQUE
END:VEVENT
* Kernels @ River Bandits
<2018-07-30 Mon 18:35-21:35>
:PROPERTIES:
:ID:       wowRT-j3LIac5B2Q4B7Sffep@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Kernels @ River Bandits Kernels @ River Bandits

Follow on MiLB First Pitch  https //stza.co/+wxmS-8

Shop  https //stza.co/+wxmS-2

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Kernels @ River Bandits
END:VALARM
DTSTART:20180730T233500Z
DTEND:20180731T023500Z
UID:wowRT-j3LIac5B2Q4B7Sffep@stanza.co
SUMMARY:Kernels @ River Bandits
DESCRIPTION:Kernels @ River Bandits\n\nFollow on MiLB First Pitch: https://stza.co/+wxmS-8\n\nShop: https://stza.co/+wxmS-2\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144951Z
LAST-MODIFIED:20180213T144951Z
TRANSP:OPAQUE
END:VEVENT
* Kernels @ River Bandits
<2018-07-31 Tue 18:35-21:35>
:PROPERTIES:
:ID:       bYn0wLW1TyV18jrfQynVPi0v@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Kernels @ River Bandits Kernels @ River Bandits

Follow on MiLB First Pitch  https //stza.co/+wxmT-3D

Shop  https //stza.co/+wxmT-2o

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Kernels @ River Bandits
END:VALARM
DTSTART:20180731T233500Z
DTEND:20180801T023500Z
UID:bYn0wLW1TyV18jrfQynVPi0v@stanza.co
SUMMARY:Kernels @ River Bandits
DESCRIPTION:Kernels @ River Bandits\n\nFollow on MiLB First Pitch: https://stza.co/+wxmT-3D\n\nShop: https://stza.co/+wxmT-2o\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144951Z
LAST-MODIFIED:20180213T144951Z
TRANSP:OPAQUE
END:VEVENT
* Kernels @ Chiefs
<2018-08-01 Wed 19:00-22:00>
:PROPERTIES:
:ID:       IK60-uRkon2U6z1ZLcM2ueMp@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Kernels @ Chiefs Kernels @ Chiefs

Follow on MiLB First Pitch  https //stza.co/+xAue-1p

Shop  https //stza.co/+xAue-3l

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Kernels @ Chiefs
END:VALARM
DTSTART:20180802T000000Z
DTEND:20180802T030000Z
UID:IK60-uRkon2U6z1ZLcM2ueMp@stanza.co
SUMMARY:Kernels @ Chiefs
DESCRIPTION:Kernels @ Chiefs\n\nFollow on MiLB First Pitch: https://stza.co/+xAue-1p\n\nShop: https://stza.co/+xAue-3l\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144951Z
LAST-MODIFIED:20180213T144951Z
TRANSP:OPAQUE
END:VEVENT
* Kernels @ Chiefs
<2018-08-02 Thu 19:00-22:00>
:PROPERTIES:
:ID:       LPKof4hoXRwgpdL6CUwEX4h-@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Kernels @ Chiefs Kernels @ Chiefs

Follow on MiLB First Pitch  https //stza.co/+xAuf-3y

Shop  https //stza.co/+xAuf-r

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Kernels @ Chiefs
END:VALARM
DTSTART:20180803T000000Z
DTEND:20180803T030000Z
UID:LPKof4hoXRwgpdL6CUwEX4h-@stanza.co
SUMMARY:Kernels @ Chiefs
DESCRIPTION:Kernels @ Chiefs\n\nFollow on MiLB First Pitch: https://stza.co/+xAuf-3y\n\nShop: https://stza.co/+xAuf-r\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144951Z
LAST-MODIFIED:20180213T144951Z
TRANSP:OPAQUE
END:VEVENT
* Kernels @ Chiefs
<2018-08-03 Fri 19:00-22:00>
:PROPERTIES:
:ID:       vb8bmf0ug-ayytoOr0sgsw4F@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Kernels @ Chiefs Kernels @ Chiefs

Follow on MiLB First Pitch  https //stza.co/+xAuh-2G

Shop  https //stza.co/+xAuh-I

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Kernels @ Chiefs
END:VALARM
DTSTART:20180804T000000Z
DTEND:20180804T030000Z
UID:vb8bmf0ug-ayytoOr0sgsw4F@stanza.co
SUMMARY:Kernels @ Chiefs
DESCRIPTION:Kernels @ Chiefs\n\nFollow on MiLB First Pitch: https://stza.co/+xAuh-2G\n\nShop: https://stza.co/+xAuh-I\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144951Z
LAST-MODIFIED:20180213T144951Z
TRANSP:OPAQUE
END:VEVENT
* Kernels vs. Snappers
<2018-08-04 Sat 18:35-21:35>
:PROPERTIES:
:ID:       KSLQE0acrNu4XWvi1m0_8tYP@stanza.co
:LOCATION: Don’t miss out! Kernels tickets still available here.
:STATUS:   CONFIRMED
:END:

Kernels vs. Snappers Kernels vs. Snappers

Buy tickets here  https //stza.co/~vMW8

Follow on MiLB First Pitch  https //stza.co/+vMW8-2w

Shop  https //stza.co/+vMW8-3v

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Kernels vs. Snappers
END:VALARM
DTSTART:20180804T233500Z
DTEND:20180805T023500Z
UID:KSLQE0acrNu4XWvi1m0_8tYP@stanza.co
SUMMARY:Kernels vs. Snappers
DESCRIPTION:Kernels vs. Snappers\n\nBuy tickets here: https://stza.co/~vMW8\n\nFollow on MiLB First Pitch: https://stza.co/+vMW8-2w\n\nShop: https://stza.co/+vMW8-3v\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don’t miss out! Kernels tickets still available here.
STATUS:CONFIRMED
CREATED:20180213T144951Z
LAST-MODIFIED:20180213T144951Z
TRANSP:OPAQUE
END:VEVENT
* Kernels vs. Snappers
<2018-08-05 Sun 14:05-17:05>
:PROPERTIES:
:ID:       tZchnqRYcVxwvdxS3x-5A9sd@stanza.co
:LOCATION: Swipe to get tickets for the game tonight. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Kernels vs. Snappers Kernels vs. Snappers

Buy tickets here  https //stza.co/~vMWb

Follow on MiLB First Pitch  https //stza.co/+vMWb-1j

Shop  https //stza.co/+vMWb-2D

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Kernels vs. Snappers
END:VALARM
DTSTART:20180805T190500Z
DTEND:20180805T220500Z
UID:tZchnqRYcVxwvdxS3x-5A9sd@stanza.co
SUMMARY:Kernels vs. Snappers
DESCRIPTION:Kernels vs. Snappers\n\nBuy tickets here: https://stza.co/~vMWb\n\nFollow on MiLB First Pitch: https://stza.co/+vMWb-1j\n\nShop: https://stza.co/+vMWb-2D\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Swipe to get tickets for the game tonight. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144951Z
LAST-MODIFIED:20180213T144951Z
TRANSP:OPAQUE
END:VEVENT
* Kernels vs. Snappers
<2018-08-06 Mon 12:05-15:05>
:PROPERTIES:
:ID:       LpdQufdzkwnJKdiuqaVo7OmU@stanza.co
:LOCATION: Swipe for last minute tickets for tonight's game. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Kernels vs. Snappers Kernels vs. Snappers

Buy tickets here  https //stza.co/~w0N$

Follow on MiLB First Pitch  https //stza.co/+w0N$-1B

Shop  https //stza.co/+w0N$-2D

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Kernels vs. Snappers
END:VALARM
DTSTART:20180806T170500Z
DTEND:20180806T200500Z
UID:LpdQufdzkwnJKdiuqaVo7OmU@stanza.co
SUMMARY:Kernels vs. Snappers
DESCRIPTION:Kernels vs. Snappers\n\nBuy tickets here: https://stza.co/~w0N$\n\nFollow on MiLB First Pitch: https://stza.co/+w0N$-1B\n\nShop: https://stza.co/+w0N$-2D\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Swipe for last minute tickets for tonight's game. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144951Z
LAST-MODIFIED:20180213T144951Z
TRANSP:OPAQUE
END:VEVENT
* Kernels @ LumberKings
<2018-08-08 Wed 18:30-21:30>
:PROPERTIES:
:ID:       6_L5ylHOpw-ZphWvDzqHJ7Kn@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Kernels @ LumberKings Kernels @ LumberKings

Follow on MiLB First Pitch  https //stza.co/+vMWF-3D

Shop  https //stza.co/+vMWF-2K

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Kernels @ LumberKings
END:VALARM
DTSTART:20180808T233000Z
DTEND:20180809T023000Z
UID:6_L5ylHOpw-ZphWvDzqHJ7Kn@stanza.co
SUMMARY:Kernels @ LumberKings
DESCRIPTION:Kernels @ LumberKings\n\nFollow on MiLB First Pitch: https://stza.co/+vMWF-3D\n\nShop: https://stza.co/+vMWF-2K\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144951Z
LAST-MODIFIED:20180213T144951Z
TRANSP:OPAQUE
END:VEVENT
* Kernels @ LumberKings
<2018-08-09 Thu 18:30-21:30>
:PROPERTIES:
:ID:       fV_HCqaXf3rTVabuxm7a23sf@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Kernels @ LumberKings Kernels @ LumberKings

Follow on MiLB First Pitch  https //stza.co/+vMWG-1n

Shop  https //stza.co/+vMWG-L

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Kernels @ LumberKings
END:VALARM
DTSTART:20180809T233000Z
DTEND:20180810T023000Z
UID:fV_HCqaXf3rTVabuxm7a23sf@stanza.co
SUMMARY:Kernels @ LumberKings
DESCRIPTION:Kernels @ LumberKings\n\nFollow on MiLB First Pitch: https://stza.co/+vMWG-1n\n\nShop: https://stza.co/+vMWG-L\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144951Z
LAST-MODIFIED:20180213T144951Z
TRANSP:OPAQUE
END:VEVENT
* Kernels @ LumberKings
<2018-08-10 Fri 18:30-21:30>
:PROPERTIES:
:ID:       lcQ9V7kRZvPKW_ik7R27hFER@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Kernels @ LumberKings Kernels @ LumberKings

Follow on MiLB First Pitch  https //stza.co/+vMWH-3r

Shop  https //stza.co/+vMWH-3u

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Kernels @ LumberKings
END:VALARM
DTSTART:20180810T233000Z
DTEND:20180811T023000Z
UID:lcQ9V7kRZvPKW_ik7R27hFER@stanza.co
SUMMARY:Kernels @ LumberKings
DESCRIPTION:Kernels @ LumberKings\n\nFollow on MiLB First Pitch: https://stza.co/+vMWH-3r\n\nShop: https://stza.co/+vMWH-3u\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144951Z
LAST-MODIFIED:20180213T144951Z
TRANSP:OPAQUE
END:VEVENT
* Kernels @ River Bandits
<2018-08-11 Sat 18:35-21:35>
:PROPERTIES:
:ID:       ZhTR3QR7VQ3Hq4j-EF2cKJAY@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Kernels @ River Bandits Kernels @ River Bandits

Follow on MiLB First Pitch  https //stza.co/+wxmU-1K

Shop  https //stza.co/+wxmU-3H

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Kernels @ River Bandits
END:VALARM
DTSTART:20180811T233500Z
DTEND:20180812T023500Z
UID:ZhTR3QR7VQ3Hq4j-EF2cKJAY@stanza.co
SUMMARY:Kernels @ River Bandits
DESCRIPTION:Kernels @ River Bandits\n\nFollow on MiLB First Pitch: https://stza.co/+wxmU-1K\n\nShop: https://stza.co/+wxmU-3H\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144951Z
LAST-MODIFIED:20180213T144951Z
TRANSP:OPAQUE
END:VEVENT
* Kernels @ River Bandits
<2018-08-12 Sun 17:15-20:15>
:PROPERTIES:
:ID:       UktirdrGxfk4DoNx7KgWe57S@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Kernels @ River Bandits Kernels @ River Bandits

Follow on MiLB First Pitch  https //stza.co/+wxmV-17

Shop  https //stza.co/+wxmV-1T

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Kernels @ River Bandits
END:VALARM
DTSTART:20180812T221500Z
DTEND:20180813T011500Z
UID:UktirdrGxfk4DoNx7KgWe57S@stanza.co
SUMMARY:Kernels @ River Bandits
DESCRIPTION:Kernels @ River Bandits\n\nFollow on MiLB First Pitch: https://stza.co/+wxmV-17\n\nShop: https://stza.co/+wxmV-1T\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144951Z
LAST-MODIFIED:20180213T144951Z
TRANSP:OPAQUE
END:VEVENT
* Kernels vs. River Bandits
<2018-08-13 Mon 18:35-21:35>
:PROPERTIES:
:ID:       HmV7IT8rpnaMN2b6o38IfgsM@stanza.co
:LOCATION: Ready for the game? Swipe for tickets and more information.
:STATUS:   CONFIRMED
:END:

Kernels vs. River Bandits Kernels vs. River Bandits

Buy tickets here  https //stza.co/~vMWf

Follow on MiLB First Pitch  https //stza.co/+vMWf-36

Shop  https //stza.co/+vMWf-W

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Kernels vs. River Bandits
END:VALARM
DTSTART:20180813T233500Z
DTEND:20180814T023500Z
UID:HmV7IT8rpnaMN2b6o38IfgsM@stanza.co
SUMMARY:Kernels vs. River Bandits
DESCRIPTION:Kernels vs. River Bandits\n\nBuy tickets here: https://stza.co/~vMWf\n\nFollow on MiLB First Pitch: https://stza.co/+vMWf-36\n\nShop: https://stza.co/+vMWf-W\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Swipe for tickets and more information.
STATUS:CONFIRMED
CREATED:20180213T144951Z
LAST-MODIFIED:20180213T144951Z
TRANSP:OPAQUE
END:VEVENT
* Kernels vs. River Bandits
<2018-08-14 Tue 18:35-21:35>
:PROPERTIES:
:ID:       pLXsMMakKN3TR1NCScMiFBt6@stanza.co
:LOCATION: Looking for something to do tonight? Get tickets here for tonight’s game and view promotions.
:STATUS:   CONFIRMED
:END:

Kernels vs. River Bandits Kernels vs. River Bandits

Buy tickets here  https //stza.co/~vMWh

Follow on MiLB First Pitch  https //stza.co/+vMWh-3A

Shop  https //stza.co/+vMWh-s

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Kernels vs. River Bandits
END:VALARM
DTSTART:20180814T233500Z
DTEND:20180815T023500Z
UID:pLXsMMakKN3TR1NCScMiFBt6@stanza.co
SUMMARY:Kernels vs. River Bandits
DESCRIPTION:Kernels vs. River Bandits\n\nBuy tickets here: https://stza.co/~vMWh\n\nFollow on MiLB First Pitch: https://stza.co/+vMWh-3A\n\nShop: https://stza.co/+vMWh-s\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Looking for something to do tonight? Get tickets here for tonight’s game and view promotions.
STATUS:CONFIRMED
CREATED:20180213T144951Z
LAST-MODIFIED:20180213T144951Z
TRANSP:OPAQUE
END:VEVENT
* Kernels vs. Chiefs
<2018-08-15 Wed 18:35-21:35>
:PROPERTIES:
:ID:       gUI-tBQUYKeMsqNHOtef-rNB@stanza.co
:LOCATION: Great seats still available for tonight’s game. Purchase them here.
:STATUS:   CONFIRMED
:END:

Kernels vs. Chiefs Kernels vs. Chiefs

Buy tickets here  https //stza.co/~vMWj

Follow on MiLB First Pitch  https //stza.co/+vMWj-2o

Shop  https //stza.co/+vMWj-2j

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Kernels vs. Chiefs
END:VALARM
DTSTART:20180815T233500Z
DTEND:20180816T023500Z
UID:gUI-tBQUYKeMsqNHOtef-rNB@stanza.co
SUMMARY:Kernels vs. Chiefs
DESCRIPTION:Kernels vs. Chiefs\n\nBuy tickets here: https://stza.co/~vMWj\n\nFollow on MiLB First Pitch: https://stza.co/+vMWj-2o\n\nShop: https://stza.co/+vMWj-2j\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Great seats still available for tonight’s game. Purchase them here.
STATUS:CONFIRMED
CREATED:20180213T144951Z
LAST-MODIFIED:20180213T144951Z
TRANSP:OPAQUE
END:VEVENT
* Kernels vs. Chiefs
<2018-08-16 Thu 18:35-21:35>
:PROPERTIES:
:ID:       VdFfYsG7MxNFjGZSbdIEM2gk@stanza.co
:LOCATION: Need something fun to do tonight? Get Kernels tickets here.
:STATUS:   CONFIRMED
:END:

Kernels vs. Chiefs Kernels vs. Chiefs

Buy tickets here  https //stza.co/~vMWl

Follow on MiLB First Pitch  https //stza.co/+vMWl-1z

Shop  https //stza.co/+vMWl-2o

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Kernels vs. Chiefs
END:VALARM
DTSTART:20180816T233500Z
DTEND:20180817T023500Z
UID:VdFfYsG7MxNFjGZSbdIEM2gk@stanza.co
SUMMARY:Kernels vs. Chiefs
DESCRIPTION:Kernels vs. Chiefs\n\nBuy tickets here: https://stza.co/~vMWl\n\nFollow on MiLB First Pitch: https://stza.co/+vMWl-1z\n\nShop: https://stza.co/+vMWl-2o\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Need something fun to do tonight? Get Kernels tickets here.
STATUS:CONFIRMED
CREATED:20180213T144951Z
LAST-MODIFIED:20180213T144951Z
TRANSP:OPAQUE
END:VEVENT
* Kernels vs. Chiefs
<2018-08-17 Fri 18:35-21:35>
:PROPERTIES:
:ID:       ls8Pt0qpDclhca3KXdqcpw0L@stanza.co
:LOCATION: Don’t miss out! Kernels tickets still available here.
:STATUS:   CONFIRMED
:END:

Kernels vs. Chiefs Kernels vs. Chiefs

Buy tickets here  https //stza.co/~vMWn

Follow on MiLB First Pitch  https //stza.co/+vMWn-1_

Shop  https //stza.co/+vMWn-2v

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Kernels vs. Chiefs
END:VALARM
DTSTART:20180817T233500Z
DTEND:20180818T023500Z
UID:ls8Pt0qpDclhca3KXdqcpw0L@stanza.co
SUMMARY:Kernels vs. Chiefs
DESCRIPTION:Kernels vs. Chiefs\n\nBuy tickets here: https://stza.co/~vMWn\n\nFollow on MiLB First Pitch: https://stza.co/+vMWn-1_\n\nShop: https://stza.co/+vMWn-2v\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don’t miss out! Kernels tickets still available here.
STATUS:CONFIRMED
CREATED:20180213T144951Z
LAST-MODIFIED:20180213T144951Z
TRANSP:OPAQUE
END:VEVENT
* Kernels @ Timber Rattlers
<2018-08-18 Sat 18:35-21:35>
:PROPERTIES:
:ID:       PUz815dY9UnnreO7v53tnBDF@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Kernels @ Timber Rattlers Kernels @ Timber Rattlers

Follow on MiLB First Pitch  https //stza.co/+vp67-2H

Shop  https //stza.co/+vp67-1c

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Kernels @ Timber Rattlers
END:VALARM
DTSTART:20180818T233500Z
DTEND:20180819T023500Z
UID:PUz815dY9UnnreO7v53tnBDF@stanza.co
SUMMARY:Kernels @ Timber Rattlers
DESCRIPTION:Kernels @ Timber Rattlers\n\nFollow on MiLB First Pitch: https://stza.co/+vp67-2H\n\nShop: https://stza.co/+vp67-1c\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144951Z
LAST-MODIFIED:20180213T144951Z
TRANSP:OPAQUE
END:VEVENT
* Kernels @ Timber Rattlers
<2018-08-19 Sun 13:05-16:05>
:PROPERTIES:
:ID:       bl3AkuCC7BiG4megt7-I1lqm@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Kernels @ Timber Rattlers Kernels @ Timber Rattlers

Follow on MiLB First Pitch  https //stza.co/+vow7-i

Shop  https //stza.co/+vow7-38

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Kernels @ Timber Rattlers
END:VALARM
DTSTART:20180819T180500Z
DTEND:20180819T210500Z
UID:bl3AkuCC7BiG4megt7-I1lqm@stanza.co
SUMMARY:Kernels @ Timber Rattlers
DESCRIPTION:Kernels @ Timber Rattlers\n\nFollow on MiLB First Pitch: https://stza.co/+vow7-i\n\nShop: https://stza.co/+vow7-38\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144951Z
LAST-MODIFIED:20180213T144951Z
TRANSP:OPAQUE
END:VEVENT
* Kernels @ Timber Rattlers
<2018-08-20 Mon 12:05-15:05>
:PROPERTIES:
:ID:       xYw8vOXHyqG_Qy_F548bTE38@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Kernels @ Timber Rattlers Kernels @ Timber Rattlers

Follow on MiLB First Pitch  https //stza.co/+vowh-1a

Shop  https //stza.co/+vowh-L

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Kernels @ Timber Rattlers
END:VALARM
DTSTART:20180820T170500Z
DTEND:20180820T200500Z
UID:xYw8vOXHyqG_Qy_F548bTE38@stanza.co
SUMMARY:Kernels @ Timber Rattlers
DESCRIPTION:Kernels @ Timber Rattlers\n\nFollow on MiLB First Pitch: https://stza.co/+vowh-1a\n\nShop: https://stza.co/+vowh-L\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144951Z
LAST-MODIFIED:20180213T144951Z
TRANSP:OPAQUE
END:VEVENT
* Kernels @ Snappers
<2018-08-21 Tue 19:00-22:00>
:PROPERTIES:
:ID:       nBTfq38icva-8VQ70dcMHBmI@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Kernels @ Snappers Kernels @ Snappers

Follow on MiLB First Pitch  https //stza.co/+wSL6-2y

Shop  https //stza.co/+wSL6-

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Kernels @ Snappers
END:VALARM
DTSTART:20180822T000000Z
DTEND:20180822T030000Z
UID:nBTfq38icva-8VQ70dcMHBmI@stanza.co
SUMMARY:Kernels @ Snappers
DESCRIPTION:Kernels @ Snappers\n\nFollow on MiLB First Pitch: https://stza.co/+wSL6-2y\n\nShop: https://stza.co/+wSL6-\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144951Z
LAST-MODIFIED:20180213T144951Z
TRANSP:OPAQUE
END:VEVENT
* Kernels @ Snappers
<2018-08-22 Wed 19:00-22:00>
:PROPERTIES:
:ID:       zB8EgouCSTG2KX_RmYuFIOPk@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Kernels @ Snappers Kernels @ Snappers

Follow on MiLB First Pitch  https //stza.co/+wSL7-3b

Shop  https //stza.co/+wSL7-W

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Kernels @ Snappers
END:VALARM
DTSTART:20180823T000000Z
DTEND:20180823T030000Z
UID:zB8EgouCSTG2KX_RmYuFIOPk@stanza.co
SUMMARY:Kernels @ Snappers
DESCRIPTION:Kernels @ Snappers\n\nFollow on MiLB First Pitch: https://stza.co/+wSL7-3b\n\nShop: https://stza.co/+wSL7-W\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144951Z
LAST-MODIFIED:20180213T144951Z
TRANSP:OPAQUE
END:VEVENT
* Kernels @ Snappers
<2018-08-23 Thu 19:00-22:00>
:PROPERTIES:
:ID:       qYm0x9i5YlYVQZuE1rpLcFu9@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Kernels @ Snappers Kernels @ Snappers

Follow on MiLB First Pitch  https //stza.co/+wSL8-2g

Shop  https //stza.co/+wSL8-1X

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Kernels @ Snappers
END:VALARM
DTSTART:20180824T000000Z
DTEND:20180824T030000Z
UID:qYm0x9i5YlYVQZuE1rpLcFu9@stanza.co
SUMMARY:Kernels @ Snappers
DESCRIPTION:Kernels @ Snappers\n\nFollow on MiLB First Pitch: https://stza.co/+wSL8-2g\n\nShop: https://stza.co/+wSL8-1X\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144951Z
LAST-MODIFIED:20180213T144951Z
TRANSP:OPAQUE
END:VEVENT
* Kernels vs. Cougars
<2018-08-24 Fri 18:35-21:35>
:PROPERTIES:
:ID:       -eJELXguimqvbwbO1T15eRMM@stanza.co
:LOCATION: Swipe to get tickets for the game tonight. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Kernels vs. Cougars Kernels vs. Cougars

Buy tickets here  https //stza.co/~vMWp

Follow on MiLB First Pitch  https //stza.co/+vMWp-3u

Shop  https //stza.co/+vMWp-1Y

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Kernels vs. Cougars
END:VALARM
DTSTART:20180824T233500Z
DTEND:20180825T023500Z
UID:-eJELXguimqvbwbO1T15eRMM@stanza.co
SUMMARY:Kernels vs. Cougars
DESCRIPTION:Kernels vs. Cougars\n\nBuy tickets here: https://stza.co/~vMWp\n\nFollow on MiLB First Pitch: https://stza.co/+vMWp-3u\n\nShop: https://stza.co/+vMWp-1Y\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Swipe to get tickets for the game tonight. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144951Z
LAST-MODIFIED:20180213T144951Z
TRANSP:OPAQUE
END:VEVENT
* Kernels vs. Cougars
<2018-08-25 Sat 18:35-21:35>
:PROPERTIES:
:ID:       n_zAoF9FEfQ9vhyKGz_VI1vg@stanza.co
:LOCATION: Swipe for last minute tickets for tonight's game. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Kernels vs. Cougars Kernels vs. Cougars

Buy tickets here  https //stza.co/~vMWr

Follow on MiLB First Pitch  https //stza.co/+vMWr-2k

Shop  https //stza.co/+vMWr-2L

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Kernels vs. Cougars
END:VALARM
DTSTART:20180825T233500Z
DTEND:20180826T023500Z
UID:n_zAoF9FEfQ9vhyKGz_VI1vg@stanza.co
SUMMARY:Kernels vs. Cougars
DESCRIPTION:Kernels vs. Cougars\n\nBuy tickets here: https://stza.co/~vMWr\n\nFollow on MiLB First Pitch: https://stza.co/+vMWr-2k\n\nShop: https://stza.co/+vMWr-2L\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Swipe for last minute tickets for tonight's game. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144951Z
LAST-MODIFIED:20180213T144951Z
TRANSP:OPAQUE
END:VEVENT
* Kernels vs. Cougars
<2018-08-26 Sun 14:05-17:05>
:PROPERTIES:
:ID:       4suEnGBnHHJJgbmwb5OlWNl_@stanza.co
:LOCATION: Ready for the game? Swipe for tickets and more information.
:STATUS:   CONFIRMED
:END:

Kernels vs. Cougars Kernels vs. Cougars

Buy tickets here  https //stza.co/~vMWt

Follow on MiLB First Pitch  https //stza.co/+vMWt-W

Shop  https //stza.co/+vMWt-1G

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Kernels vs. Cougars
END:VALARM
DTSTART:20180826T190500Z
DTEND:20180826T220500Z
UID:4suEnGBnHHJJgbmwb5OlWNl_@stanza.co
SUMMARY:Kernels vs. Cougars
DESCRIPTION:Kernels vs. Cougars\n\nBuy tickets here: https://stza.co/~vMWt\n\nFollow on MiLB First Pitch: https://stza.co/+vMWt-W\n\nShop: https://stza.co/+vMWt-1G\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Swipe for tickets and more information.
STATUS:CONFIRMED
CREATED:20180213T144951Z
LAST-MODIFIED:20180213T144951Z
TRANSP:OPAQUE
END:VEVENT
* Kernels vs. Cougars
<2018-08-27 Mon 18:35-21:35>
:PROPERTIES:
:ID:       uSkLF3MQ0Z44r6hwTgv-LIK5@stanza.co
:LOCATION: Looking for something to do tonight? Get tickets here for tonight’s game and view promotions.
:STATUS:   CONFIRMED
:END:

Kernels vs. Cougars Kernels vs. Cougars

Buy tickets here  https //stza.co/~vMWv

Follow on MiLB First Pitch  https //stza.co/+vMWv-t

Shop  https //stza.co/+vMWv-1

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Kernels vs. Cougars
END:VALARM
DTSTART:20180827T233500Z
DTEND:20180828T023500Z
UID:uSkLF3MQ0Z44r6hwTgv-LIK5@stanza.co
SUMMARY:Kernels vs. Cougars
DESCRIPTION:Kernels vs. Cougars\n\nBuy tickets here: https://stza.co/~vMWv\n\nFollow on MiLB First Pitch: https://stza.co/+vMWv-t\n\nShop: https://stza.co/+vMWv-1\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Looking for something to do tonight? Get tickets here for tonight’s game and view promotions.
STATUS:CONFIRMED
CREATED:20180213T144951Z
LAST-MODIFIED:20180213T144951Z
TRANSP:OPAQUE
END:VEVENT
* Kernels vs. Bees
<2018-08-29 Wed 18:35-21:35>
:PROPERTIES:
:ID:       jHN20Z7YGhOmYiR8Ghd4rgN5@stanza.co
:LOCATION: Great seats still available for tonight’s game. Purchase them here.
:STATUS:   CONFIRMED
:END:

Kernels vs. Bees Kernels vs. Bees

Buy tickets here  https //stza.co/~vMWw

Follow on MiLB First Pitch  https //stza.co/+vMWw-1T

Shop  https //stza.co/+vMWw-2U

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Kernels vs. Bees
END:VALARM
DTSTART:20180829T233500Z
DTEND:20180830T023500Z
UID:jHN20Z7YGhOmYiR8Ghd4rgN5@stanza.co
SUMMARY:Kernels vs. Bees
DESCRIPTION:Kernels vs. Bees\n\nBuy tickets here: https://stza.co/~vMWw\n\nFollow on MiLB First Pitch: https://stza.co/+vMWw-1T\n\nShop: https://stza.co/+vMWw-2U\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Great seats still available for tonight’s game. Purchase them here.
STATUS:CONFIRMED
CREATED:20180213T144951Z
LAST-MODIFIED:20180213T144951Z
TRANSP:OPAQUE
END:VEVENT
* Kernels vs. Bees
<2018-08-30 Thu 18:35-21:35>
:PROPERTIES:
:ID:       rYBA8D336RaNP273lTL4ESeE@stanza.co
:LOCATION: Need something fun to do tonight? Get Kernels tickets here.
:STATUS:   CONFIRMED
:END:

Kernels vs. Bees Kernels vs. Bees

Buy tickets here  https //stza.co/~vMWz

Follow on MiLB First Pitch  https //stza.co/+vMWz-1Z

Shop  https //stza.co/+vMWz-1R

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Kernels vs. Bees
END:VALARM
DTSTART:20180830T233500Z
DTEND:20180831T023500Z
UID:rYBA8D336RaNP273lTL4ESeE@stanza.co
SUMMARY:Kernels vs. Bees
DESCRIPTION:Kernels vs. Bees\n\nBuy tickets here: https://stza.co/~vMWz\n\nFollow on MiLB First Pitch: https://stza.co/+vMWz-1Z\n\nShop: https://stza.co/+vMWz-1R\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Need something fun to do tonight? Get Kernels tickets here.
STATUS:CONFIRMED
CREATED:20180213T144951Z
LAST-MODIFIED:20180213T144951Z
TRANSP:OPAQUE
END:VEVENT
* Kernels vs. Bees
<2018-08-31 Fri 18:35-21:35>
:PROPERTIES:
:ID:       9yuhNXhXeZPWf5frGaUJK8Ei@stanza.co
:LOCATION: Don’t miss out! Kernels tickets still available here.
:STATUS:   CONFIRMED
:END:

Kernels vs. Bees Kernels vs. Bees

Buy tickets here  https //stza.co/~vMWA

Follow on MiLB First Pitch  https //stza.co/+vMWA-3r

Shop  https //stza.co/+vMWA-F

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Kernels vs. Bees
END:VALARM
DTSTART:20180831T233500Z
DTEND:20180901T023500Z
UID:9yuhNXhXeZPWf5frGaUJK8Ei@stanza.co
SUMMARY:Kernels vs. Bees
DESCRIPTION:Kernels vs. Bees\n\nBuy tickets here: https://stza.co/~vMWA\n\nFollow on MiLB First Pitch: https://stza.co/+vMWA-3r\n\nShop: https://stza.co/+vMWA-F\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don’t miss out! Kernels tickets still available here.
STATUS:CONFIRMED
CREATED:20180213T144951Z
LAST-MODIFIED:20180213T144951Z
TRANSP:OPAQUE
END:VEVENT
* Kernels @ Snappers
<2018-09-01 Sat 19:00-22:00>
:PROPERTIES:
:ID:       jC14t4BbhVQeziCk5Yo24fps@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Kernels @ Snappers Kernels @ Snappers

Follow on MiLB First Pitch  https //stza.co/+wSL9-3G

Shop  https //stza.co/+wSL9-3n

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Kernels @ Snappers
END:VALARM
DTSTART:20180902T000000Z
DTEND:20180902T030000Z
UID:jC14t4BbhVQeziCk5Yo24fps@stanza.co
SUMMARY:Kernels @ Snappers
DESCRIPTION:Kernels @ Snappers\n\nFollow on MiLB First Pitch: https://stza.co/+wSL9-3G\n\nShop: https://stza.co/+wSL9-3n\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144951Z
LAST-MODIFIED:20180213T144951Z
TRANSP:OPAQUE
END:VEVENT
* Kernels @ Snappers
<2018-09-02 Sun 14:00-17:00>
:PROPERTIES:
:ID:       nPiZ7j9lGwwsk2MOS9dDv33i@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Kernels @ Snappers Kernels @ Snappers

Follow on MiLB First Pitch  https //stza.co/+wSLa-C

Shop  https //stza.co/+wSLa-2q

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Kernels @ Snappers
END:VALARM
DTSTART:20180902T190000Z
DTEND:20180902T220000Z
UID:nPiZ7j9lGwwsk2MOS9dDv33i@stanza.co
SUMMARY:Kernels @ Snappers
DESCRIPTION:Kernels @ Snappers\n\nFollow on MiLB First Pitch: https://stza.co/+wSLa-C\n\nShop: https://stza.co/+wSLa-2q\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144951Z
LAST-MODIFIED:20180213T144951Z
TRANSP:OPAQUE
END:VEVENT
* Kernels @ Snappers
<2018-09-03 Mon 14:00-17:00>
:PROPERTIES:
:ID:       4ZwNTIwRMl_gB8k5f6dn5Loh@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Kernels @ Snappers Kernels @ Snappers

Follow on MiLB First Pitch  https //stza.co/+wSLb-3v

Shop  https //stza.co/+wSLb-2k

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Kernels @ Snappers
END:VALARM
DTSTART:20180903T190000Z
DTEND:20180903T220000Z
UID:4ZwNTIwRMl_gB8k5f6dn5Loh@stanza.co
SUMMARY:Kernels @ Snappers
DESCRIPTION:Kernels @ Snappers\n\nFollow on MiLB First Pitch: https://stza.co/+wSLb-3v\n\nShop: https://stza.co/+wSLb-2k\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144951Z
LAST-MODIFIED:20180213T144951Z
TRANSP:OPAQUE
END:VEVENT
