#+TITLE:       Main Google calendar entries
#+AUTHOR:      Eric S Fraga
#+EMAIL:       e.fraga@ucl.ac.uk
#+DESCRIPTION: converted using the ical2org awk script
#+CATEGORY:    google
#+STARTUP:     hidestars
#+STARTUP:     overview

* COMMENT original iCal preamble

* Rockies vs. Owlz
<2018-06-15 Fri 19:40-22:40>
:PROPERTIES:
:ID:       HAkz7Sxn51ScMw3LTcPrtbr9@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Rockies vs. Owlz Rockies vs. Owlz

Follow on MiLB First Pitch  https //stza.co/+xJ6U-3n

Shop  https //stza.co/+xJ6U-3D

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Rockies vs. Owlz
END:VALARM
DTSTART:20180616T004000Z
DTEND:20180616T034000Z
UID:HAkz7Sxn51ScMw3LTcPrtbr9@stanza.co
SUMMARY:Rockies vs. Owlz
DESCRIPTION:Rockies vs. Owlz\n\nFollow on MiLB First Pitch: https://stza.co/+xJ6U-3n\n\nShop: https://stza.co/+xJ6U-3D\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144528Z
LAST-MODIFIED:20180213T144528Z
TRANSP:OPAQUE
END:VEVENT
* Rockies vs. Owlz
<2018-06-16 Sat 19:40-22:40>
:PROPERTIES:
:ID:       HeAATfhkBrejPzGYMOoVfYO-@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Rockies vs. Owlz Rockies vs. Owlz

Follow on MiLB First Pitch  https //stza.co/+xJ6W-1

Shop  https //stza.co/+xJ6W-2t

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Rockies vs. Owlz
END:VALARM
DTSTART:20180617T004000Z
DTEND:20180617T034000Z
UID:HeAATfhkBrejPzGYMOoVfYO-@stanza.co
SUMMARY:Rockies vs. Owlz
DESCRIPTION:Rockies vs. Owlz\n\nFollow on MiLB First Pitch: https://stza.co/+xJ6W-1\n\nShop: https://stza.co/+xJ6W-2t\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144528Z
LAST-MODIFIED:20180213T144528Z
TRANSP:OPAQUE
END:VEVENT
* Rockies vs. Owlz
<2018-06-17 Sun 18:00-21:00>
:PROPERTIES:
:ID:       7QlGz6PbhBs8zIpP8L1zbIxB@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Rockies vs. Owlz Rockies vs. Owlz

Follow on MiLB First Pitch  https //stza.co/+xJ6Y-3C

Shop  https //stza.co/+xJ6Y-3Y

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Rockies vs. Owlz
END:VALARM
DTSTART:20180617T230000Z
DTEND:20180618T020000Z
UID:7QlGz6PbhBs8zIpP8L1zbIxB@stanza.co
SUMMARY:Rockies vs. Owlz
DESCRIPTION:Rockies vs. Owlz\n\nFollow on MiLB First Pitch: https://stza.co/+xJ6Y-3C\n\nShop: https://stza.co/+xJ6Y-3Y\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144528Z
LAST-MODIFIED:20180213T144528Z
TRANSP:OPAQUE
END:VEVENT
* Rockies vs. Owlz
<2018-06-18 Mon 19:40-22:40>
:PROPERTIES:
:ID:       9cgkF-ZClJ4LhvPI3BQoABIQ@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Rockies vs. Owlz Rockies vs. Owlz

Follow on MiLB First Pitch  https //stza.co/+xJ6$-1Y

Shop  https //stza.co/+xJ6$-3v

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Rockies vs. Owlz
END:VALARM
DTSTART:20180619T004000Z
DTEND:20180619T034000Z
UID:9cgkF-ZClJ4LhvPI3BQoABIQ@stanza.co
SUMMARY:Rockies vs. Owlz
DESCRIPTION:Rockies vs. Owlz\n\nFollow on MiLB First Pitch: https://stza.co/+xJ6$-1Y\n\nShop: https://stza.co/+xJ6$-3v\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144528Z
LAST-MODIFIED:20180213T144528Z
TRANSP:OPAQUE
END:VEVENT
* Rockies vs. Chukars
<2018-06-19 Tue 19:40-22:40>
:PROPERTIES:
:ID:       E_79rueAKDM_yvmBCPUeD6bg@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Rockies vs. Chukars Rockies vs. Chukars

Follow on MiLB First Pitch  https //stza.co/+xJ71-L

Shop  https //stza.co/+xJ71-2Y

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Rockies vs. Chukars
END:VALARM
DTSTART:20180620T004000Z
DTEND:20180620T034000Z
UID:E_79rueAKDM_yvmBCPUeD6bg@stanza.co
SUMMARY:Rockies vs. Chukars
DESCRIPTION:Rockies vs. Chukars\n\nFollow on MiLB First Pitch: https://stza.co/+xJ71-L\n\nShop: https://stza.co/+xJ71-2Y\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144528Z
LAST-MODIFIED:20180213T144528Z
TRANSP:OPAQUE
END:VEVENT
* Rockies vs. Chukars
<2018-06-20 Wed 19:40-22:40>
:PROPERTIES:
:ID:       QLlBduiFYNWI-iHaesdLTjaH@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Rockies vs. Chukars Rockies vs. Chukars

Follow on MiLB First Pitch  https //stza.co/+xJ72-3S

Shop  https //stza.co/+xJ72-c

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Rockies vs. Chukars
END:VALARM
DTSTART:20180621T004000Z
DTEND:20180621T034000Z
UID:QLlBduiFYNWI-iHaesdLTjaH@stanza.co
SUMMARY:Rockies vs. Chukars
DESCRIPTION:Rockies vs. Chukars\n\nFollow on MiLB First Pitch: https://stza.co/+xJ72-3S\n\nShop: https://stza.co/+xJ72-c\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144528Z
LAST-MODIFIED:20180213T144528Z
TRANSP:OPAQUE
END:VEVENT
* Rockies vs. Chukars
<2018-06-21 Thu 19:40-22:40>
:PROPERTIES:
:ID:       aPc6pjs9tL1uSVRzPOpHJcOM@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Rockies vs. Chukars Rockies vs. Chukars

Follow on MiLB First Pitch  https //stza.co/+xJ74-F

Shop  https //stza.co/+xJ74-3n

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Rockies vs. Chukars
END:VALARM
DTSTART:20180622T004000Z
DTEND:20180622T034000Z
UID:aPc6pjs9tL1uSVRzPOpHJcOM@stanza.co
SUMMARY:Rockies vs. Chukars
DESCRIPTION:Rockies vs. Chukars\n\nFollow on MiLB First Pitch: https://stza.co/+xJ74-F\n\nShop: https://stza.co/+xJ74-3n\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144528Z
LAST-MODIFIED:20180213T144528Z
TRANSP:OPAQUE
END:VEVENT
* Rockies vs. Chukars
<2018-06-22 Fri 19:40-22:40>
:PROPERTIES:
:ID:       K4nt4u_Is4Ann9O7kDEIs849@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Rockies vs. Chukars Rockies vs. Chukars

Follow on MiLB First Pitch  https //stza.co/+xJ77-2X

Shop  https //stza.co/+xJ77-1k

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Rockies vs. Chukars
END:VALARM
DTSTART:20180623T004000Z
DTEND:20180623T034000Z
UID:K4nt4u_Is4Ann9O7kDEIs849@stanza.co
SUMMARY:Rockies vs. Chukars
DESCRIPTION:Rockies vs. Chukars\n\nFollow on MiLB First Pitch: https://stza.co/+xJ77-2X\n\nShop: https://stza.co/+xJ77-1k\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144528Z
LAST-MODIFIED:20180213T144528Z
TRANSP:OPAQUE
END:VEVENT
* Rockies @ Raptors
<2018-06-23 Sat 20:00-23:00>
:PROPERTIES:
:ID:       PUUTM7eVou3fFPDCTlRrhzu-@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Rockies @ Raptors Rockies @ Raptors

Follow on MiLB First Pitch  https //stza.co/+x$7O-6

Shop  https //stza.co/+x$7O-1L

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Rockies @ Raptors
END:VALARM
DTSTART:20180624T010000Z
DTEND:20180624T040000Z
UID:PUUTM7eVou3fFPDCTlRrhzu-@stanza.co
SUMMARY:Rockies @ Raptors
DESCRIPTION:Rockies @ Raptors\n\nFollow on MiLB First Pitch: https://stza.co/+x$7O-6\n\nShop: https://stza.co/+x$7O-1L\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144528Z
LAST-MODIFIED:20180213T144528Z
TRANSP:OPAQUE
END:VEVENT
* Rockies @ Raptors
<2018-06-24 Sun 17:00-20:00>
:PROPERTIES:
:ID:       qXppb1IoHTrUNlDMkWTDeWY7@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Rockies @ Raptors Rockies @ Raptors

Follow on MiLB First Pitch  https //stza.co/+x$7P-3l

Shop  https //stza.co/+x$7P-1G

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Rockies @ Raptors
END:VALARM
DTSTART:20180624T220000Z
DTEND:20180625T010000Z
UID:qXppb1IoHTrUNlDMkWTDeWY7@stanza.co
SUMMARY:Rockies @ Raptors
DESCRIPTION:Rockies @ Raptors\n\nFollow on MiLB First Pitch: https://stza.co/+x$7P-3l\n\nShop: https://stza.co/+x$7P-1G\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144528Z
LAST-MODIFIED:20180213T144528Z
TRANSP:OPAQUE
END:VEVENT
* Rockies @ Raptors
<2018-06-25 Mon 20:00-23:00>
:PROPERTIES:
:ID:       Hm5C312fCwza5y3ffocOdn9e@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Rockies @ Raptors Rockies @ Raptors

Follow on MiLB First Pitch  https //stza.co/+x$7Q-3y

Shop  https //stza.co/+x$7Q-14

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Rockies @ Raptors
END:VALARM
DTSTART:20180626T010000Z
DTEND:20180626T040000Z
UID:Hm5C312fCwza5y3ffocOdn9e@stanza.co
SUMMARY:Rockies @ Raptors
DESCRIPTION:Rockies @ Raptors\n\nFollow on MiLB First Pitch: https://stza.co/+x$7Q-3y\n\nShop: https://stza.co/+x$7Q-14\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144528Z
LAST-MODIFIED:20180213T144528Z
TRANSP:OPAQUE
END:VEVENT
* Rockies @ Chukars
<2018-06-26 Tue 20:15-23:15>
:PROPERTIES:
:ID:       hez-wUXpF_vpGV8eKmsh50o1@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Rockies @ Chukars Rockies @ Chukars

Follow on MiLB First Pitch  https //stza.co/+xZUA-Y

Shop  https //stza.co/+xZUA-d

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Rockies @ Chukars
END:VALARM
DTSTART:20180627T011500Z
DTEND:20180627T041500Z
UID:hez-wUXpF_vpGV8eKmsh50o1@stanza.co
SUMMARY:Rockies @ Chukars
DESCRIPTION:Rockies @ Chukars\n\nFollow on MiLB First Pitch: https://stza.co/+xZUA-Y\n\nShop: https://stza.co/+xZUA-d\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144528Z
LAST-MODIFIED:20180213T144528Z
TRANSP:OPAQUE
END:VEVENT
* Rockies @ Chukars
<2018-06-27 Wed 20:15-23:15>
:PROPERTIES:
:ID:       PkJK00qxEK96RyLeyyO6GsyN@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Rockies @ Chukars Rockies @ Chukars

Follow on MiLB First Pitch  https //stza.co/+xZUB-J

Shop  https //stza.co/+xZUB-O

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Rockies @ Chukars
END:VALARM
DTSTART:20180628T011500Z
DTEND:20180628T041500Z
UID:PkJK00qxEK96RyLeyyO6GsyN@stanza.co
SUMMARY:Rockies @ Chukars
DESCRIPTION:Rockies @ Chukars\n\nFollow on MiLB First Pitch: https://stza.co/+xZUB-J\n\nShop: https://stza.co/+xZUB-O\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144528Z
LAST-MODIFIED:20180213T144528Z
TRANSP:OPAQUE
END:VEVENT
* Rockies @ Chukars
<2018-06-28 Thu 20:15-23:15>
:PROPERTIES:
:ID:       vlK5KEbWuGkgZvhKeiJIxuIq@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Rockies @ Chukars Rockies @ Chukars

Follow on MiLB First Pitch  https //stza.co/+xZUC-o

Shop  https //stza.co/+xZUC-1g

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Rockies @ Chukars
END:VALARM
DTSTART:20180629T011500Z
DTEND:20180629T041500Z
UID:vlK5KEbWuGkgZvhKeiJIxuIq@stanza.co
SUMMARY:Rockies @ Chukars
DESCRIPTION:Rockies @ Chukars\n\nFollow on MiLB First Pitch: https://stza.co/+xZUC-o\n\nShop: https://stza.co/+xZUC-1g\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144528Z
LAST-MODIFIED:20180213T144528Z
TRANSP:OPAQUE
END:VEVENT
* Rockies @ Chukars
<2018-06-29 Fri 20:15-23:15>
:PROPERTIES:
:ID:       uBGGyleJ7iSLTwy7svkXEADS@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Rockies @ Chukars Rockies @ Chukars

Follow on MiLB First Pitch  https //stza.co/+xZUD-2f

Shop  https //stza.co/+xZUD-2_

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Rockies @ Chukars
END:VALARM
DTSTART:20180630T011500Z
DTEND:20180630T041500Z
UID:uBGGyleJ7iSLTwy7svkXEADS@stanza.co
SUMMARY:Rockies @ Chukars
DESCRIPTION:Rockies @ Chukars\n\nFollow on MiLB First Pitch: https://stza.co/+xZUD-2f\n\nShop: https://stza.co/+xZUD-2_\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144528Z
LAST-MODIFIED:20180213T144528Z
TRANSP:OPAQUE
END:VEVENT
* Rockies @ Owlz
<2018-06-30 Sat 20:05-23:05>
:PROPERTIES:
:ID:       jBB6G8AVLCaU6yXiO7uArX9X@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Rockies @ Owlz Rockies @ Owlz

Follow on MiLB First Pitch  https //stza.co/+xPB4-P

Shop  https //stza.co/+xPB4-2N

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Rockies @ Owlz
END:VALARM
DTSTART:20180701T010500Z
DTEND:20180701T040500Z
UID:jBB6G8AVLCaU6yXiO7uArX9X@stanza.co
SUMMARY:Rockies @ Owlz
DESCRIPTION:Rockies @ Owlz\n\nFollow on MiLB First Pitch: https://stza.co/+xPB4-P\n\nShop: https://stza.co/+xPB4-2N\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144528Z
LAST-MODIFIED:20180213T144528Z
TRANSP:OPAQUE
END:VEVENT
* Rockies @ Owlz
<2018-07-01 Sun 17:05-20:05>
:PROPERTIES:
:ID:       rpxaAtghYO7WP2ic_0MrcKAK@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Rockies @ Owlz Rockies @ Owlz

Follow on MiLB First Pitch  https //stza.co/+xPB5-1H

Shop  https //stza.co/+xPB5-2h

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Rockies @ Owlz
END:VALARM
DTSTART:20180701T220500Z
DTEND:20180702T010500Z
UID:rpxaAtghYO7WP2ic_0MrcKAK@stanza.co
SUMMARY:Rockies @ Owlz
DESCRIPTION:Rockies @ Owlz\n\nFollow on MiLB First Pitch: https://stza.co/+xPB5-1H\n\nShop: https://stza.co/+xPB5-2h\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144528Z
LAST-MODIFIED:20180213T144528Z
TRANSP:OPAQUE
END:VEVENT
* Rockies @ Owlz
<2018-07-02 Mon 20:05-23:05>
:PROPERTIES:
:ID:       LZexXAhN39UGdlD4T-1PP27W@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Rockies @ Owlz Rockies @ Owlz

Follow on MiLB First Pitch  https //stza.co/+xPB6-2u

Shop  https //stza.co/+xPB6-2c

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Rockies @ Owlz
END:VALARM
DTSTART:20180703T010500Z
DTEND:20180703T040500Z
UID:LZexXAhN39UGdlD4T-1PP27W@stanza.co
SUMMARY:Rockies @ Owlz
DESCRIPTION:Rockies @ Owlz\n\nFollow on MiLB First Pitch: https://stza.co/+xPB6-2u\n\nShop: https://stza.co/+xPB6-2c\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144528Z
LAST-MODIFIED:20180213T144528Z
TRANSP:OPAQUE
END:VEVENT
* Rockies @ Owlz
<2018-07-03 Tue 20:05-23:05>
:PROPERTIES:
:ID:       9bnYK3gdt7ZKrVOir09-99LD@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Rockies @ Owlz Rockies @ Owlz

Follow on MiLB First Pitch  https //stza.co/+xPB7-A

Shop  https //stza.co/+xPB7-t

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Rockies @ Owlz
END:VALARM
DTSTART:20180704T010500Z
DTEND:20180704T040500Z
UID:9bnYK3gdt7ZKrVOir09-99LD@stanza.co
SUMMARY:Rockies @ Owlz
DESCRIPTION:Rockies @ Owlz\n\nFollow on MiLB First Pitch: https://stza.co/+xPB7-A\n\nShop: https://stza.co/+xPB7-t\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144528Z
LAST-MODIFIED:20180213T144528Z
TRANSP:OPAQUE
END:VEVENT
* Rockies vs. Raptors
<2018-07-04 Wed 19:40-22:40>
:PROPERTIES:
:ID:       aZJdYZeIB16zJcm3vlmi6qzp@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Rockies vs. Raptors Rockies vs. Raptors

Follow on MiLB First Pitch  https //stza.co/+xJ79-d

Shop  https //stza.co/+xJ79-2P

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Rockies vs. Raptors
END:VALARM
DTSTART:20180705T004000Z
DTEND:20180705T034000Z
UID:aZJdYZeIB16zJcm3vlmi6qzp@stanza.co
SUMMARY:Rockies vs. Raptors
DESCRIPTION:Rockies vs. Raptors\n\nFollow on MiLB First Pitch: https://stza.co/+xJ79-d\n\nShop: https://stza.co/+xJ79-2P\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144528Z
LAST-MODIFIED:20180213T144528Z
TRANSP:OPAQUE
END:VEVENT
* Rockies vs. Raptors
<2018-07-05 Thu 19:40-22:40>
:PROPERTIES:
:ID:       9ds5WFA9oopzZ5YNWV6FO0zm@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Rockies vs. Raptors Rockies vs. Raptors

Follow on MiLB First Pitch  https //stza.co/+xJ7a-2c

Shop  https //stza.co/+xJ7a-l

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Rockies vs. Raptors
END:VALARM
DTSTART:20180706T004000Z
DTEND:20180706T034000Z
UID:9ds5WFA9oopzZ5YNWV6FO0zm@stanza.co
SUMMARY:Rockies vs. Raptors
DESCRIPTION:Rockies vs. Raptors\n\nFollow on MiLB First Pitch: https://stza.co/+xJ7a-2c\n\nShop: https://stza.co/+xJ7a-l\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144528Z
LAST-MODIFIED:20180213T144528Z
TRANSP:OPAQUE
END:VEVENT
* Rockies vs. Raptors
<2018-07-06 Fri 19:40-22:40>
:PROPERTIES:
:ID:       zSMTI28E0yOxpyM4c5ScXVg0@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Rockies vs. Raptors Rockies vs. Raptors

Follow on MiLB First Pitch  https //stza.co/+xJ7d-2W

Shop  https //stza.co/+xJ7d-3i

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Rockies vs. Raptors
END:VALARM
DTSTART:20180707T004000Z
DTEND:20180707T034000Z
UID:zSMTI28E0yOxpyM4c5ScXVg0@stanza.co
SUMMARY:Rockies vs. Raptors
DESCRIPTION:Rockies vs. Raptors\n\nFollow on MiLB First Pitch: https://stza.co/+xJ7d-2W\n\nShop: https://stza.co/+xJ7d-3i\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144528Z
LAST-MODIFIED:20180213T144528Z
TRANSP:OPAQUE
END:VEVENT
* Rockies vs. Raptors
<2018-07-07 Sat 19:40-22:40>
:PROPERTIES:
:ID:       9cFCHC3G2wBf_MKr9gZrIUbl@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Rockies vs. Raptors Rockies vs. Raptors

Follow on MiLB First Pitch  https //stza.co/+xJ7f-G

Shop  https //stza.co/+xJ7f-2O

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Rockies vs. Raptors
END:VALARM
DTSTART:20180708T004000Z
DTEND:20180708T034000Z
UID:9cFCHC3G2wBf_MKr9gZrIUbl@stanza.co
SUMMARY:Rockies vs. Raptors
DESCRIPTION:Rockies vs. Raptors\n\nFollow on MiLB First Pitch: https://stza.co/+xJ7f-G\n\nShop: https://stza.co/+xJ7f-2O\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144528Z
LAST-MODIFIED:20180213T144528Z
TRANSP:OPAQUE
END:VEVENT
* Rockies vs. Raptors
<2018-07-08 Sun 18:00-21:00>
:PROPERTIES:
:ID:       PfcRToITFT9fYskAMYi9n2ye@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Rockies vs. Raptors Rockies vs. Raptors

Follow on MiLB First Pitch  https //stza.co/+xJ7g-1q

Shop  https //stza.co/+xJ7g-3v

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Rockies vs. Raptors
END:VALARM
DTSTART:20180708T230000Z
DTEND:20180709T020000Z
UID:PfcRToITFT9fYskAMYi9n2ye@stanza.co
SUMMARY:Rockies vs. Raptors
DESCRIPTION:Rockies vs. Raptors\n\nFollow on MiLB First Pitch: https://stza.co/+xJ7g-1q\n\nShop: https://stza.co/+xJ7g-3v\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144528Z
LAST-MODIFIED:20180213T144528Z
TRANSP:OPAQUE
END:VEVENT
* Rockies @ Mustangs
<2018-07-10 Tue 20:05-23:05>
:PROPERTIES:
:ID:       tqVF-BG-5G-RBvUfwU4pSpk4@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Rockies @ Mustangs Rockies @ Mustangs

Follow on MiLB First Pitch  https //stza.co/+xSOq-3T

Shop  https //stza.co/+xSOq-q

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Rockies @ Mustangs
END:VALARM
DTSTART:20180711T010500Z
DTEND:20180711T040500Z
UID:tqVF-BG-5G-RBvUfwU4pSpk4@stanza.co
SUMMARY:Rockies @ Mustangs
DESCRIPTION:Rockies @ Mustangs\n\nFollow on MiLB First Pitch: https://stza.co/+xSOq-3T\n\nShop: https://stza.co/+xSOq-q\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144528Z
LAST-MODIFIED:20180213T144528Z
TRANSP:OPAQUE
END:VEVENT
* Rockies @ Mustangs
<2018-07-11 Wed 20:05-23:05>
:PROPERTIES:
:ID:       DlCSktd3qPi5Ny-JNx4jf7B9@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Rockies @ Mustangs Rockies @ Mustangs

Follow on MiLB First Pitch  https //stza.co/+xSOr-2

Shop  https //stza.co/+xSOr-17

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Rockies @ Mustangs
END:VALARM
DTSTART:20180712T010500Z
DTEND:20180712T040500Z
UID:DlCSktd3qPi5Ny-JNx4jf7B9@stanza.co
SUMMARY:Rockies @ Mustangs
DESCRIPTION:Rockies @ Mustangs\n\nFollow on MiLB First Pitch: https://stza.co/+xSOr-2\n\nShop: https://stza.co/+xSOr-17\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144528Z
LAST-MODIFIED:20180213T144528Z
TRANSP:OPAQUE
END:VEVENT
* Rockies @ Mustangs
<2018-07-12 Thu 20:05-23:05>
:PROPERTIES:
:ID:       pA5SRoSYiDQNK2Gjrr3eUoC9@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Rockies @ Mustangs Rockies @ Mustangs

Follow on MiLB First Pitch  https //stza.co/+xSOs-1l

Shop  https //stza.co/+xSOs-37

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Rockies @ Mustangs
END:VALARM
DTSTART:20180713T010500Z
DTEND:20180713T040500Z
UID:pA5SRoSYiDQNK2Gjrr3eUoC9@stanza.co
SUMMARY:Rockies @ Mustangs
DESCRIPTION:Rockies @ Mustangs\n\nFollow on MiLB First Pitch: https://stza.co/+xSOs-1l\n\nShop: https://stza.co/+xSOs-37\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144528Z
LAST-MODIFIED:20180213T144528Z
TRANSP:OPAQUE
END:VEVENT
* Rockies @ Mustangs
<2018-07-13 Fri 20:05-23:05>
:PROPERTIES:
:ID:       XNVveEgZGDvD-Z0zI08qUb-s@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Rockies @ Mustangs Rockies @ Mustangs

Follow on MiLB First Pitch  https //stza.co/+xSOt-18

Shop  https //stza.co/+xSOt-1D

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Rockies @ Mustangs
END:VALARM
DTSTART:20180714T010500Z
DTEND:20180714T040500Z
UID:XNVveEgZGDvD-Z0zI08qUb-s@stanza.co
SUMMARY:Rockies @ Mustangs
DESCRIPTION:Rockies @ Mustangs\n\nFollow on MiLB First Pitch: https://stza.co/+xSOt-18\n\nShop: https://stza.co/+xSOt-1D\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144528Z
LAST-MODIFIED:20180213T144528Z
TRANSP:OPAQUE
END:VEVENT
* Rockies @ Voyagers
<2018-07-14 Sat>--<2018-07-13 Fri>
:PROPERTIES:
:ID:       iGAsXFQ8tvtJg3_VlsDlNK9a@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Rockies @ Voyagers Rockies @ Voyagers

Follow on MiLB First Pitch  https //stza.co/+xCnU-8

Shop  https //stza.co/+xCnU-31

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Rockies @ Voyagers
END:VALARM
DTSTART;VALUE=DATE:20180714
DTEND;VALUE=DATE:20180714
UID:iGAsXFQ8tvtJg3_VlsDlNK9a@stanza.co
SUMMARY:Rockies @ Voyagers
DESCRIPTION:Rockies @ Voyagers\n\nFollow on MiLB First Pitch: https://stza.co/+xCnU-8\n\nShop: https://stza.co/+xCnU-31\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144528Z
LAST-MODIFIED:20180213T144528Z
TRANSP:OPAQUE
END:VEVENT
* Rockies @ Voyagers
<2018-07-15 Sun>--<2018-07-14 Sat>
:PROPERTIES:
:ID:       jZpROPZM54gAB0sHcIXZ7QUz@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Rockies @ Voyagers Rockies @ Voyagers

Follow on MiLB First Pitch  https //stza.co/+xCnX-t

Shop  https //stza.co/+xCnX-2X

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Rockies @ Voyagers
END:VALARM
DTSTART;VALUE=DATE:20180715
DTEND;VALUE=DATE:20180715
UID:jZpROPZM54gAB0sHcIXZ7QUz@stanza.co
SUMMARY:Rockies @ Voyagers
DESCRIPTION:Rockies @ Voyagers\n\nFollow on MiLB First Pitch: https://stza.co/+xCnX-t\n\nShop: https://stza.co/+xCnX-2X\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144528Z
LAST-MODIFIED:20180213T144528Z
TRANSP:OPAQUE
END:VEVENT
* Rockies @ Voyagers
<2018-07-16 Mon>--<2018-07-15 Sun>
:PROPERTIES:
:ID:       2lckXTeen7j1C4xARfn6CMjX@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Rockies @ Voyagers Rockies @ Voyagers

Follow on MiLB First Pitch  https //stza.co/+xCn$-c

Shop  https //stza.co/+xCn$-u

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Rockies @ Voyagers
END:VALARM
DTSTART;VALUE=DATE:20180716
DTEND;VALUE=DATE:20180716
UID:2lckXTeen7j1C4xARfn6CMjX@stanza.co
SUMMARY:Rockies @ Voyagers
DESCRIPTION:Rockies @ Voyagers\n\nFollow on MiLB First Pitch: https://stza.co/+xCn$-c\n\nShop: https://stza.co/+xCn$-u\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144528Z
LAST-MODIFIED:20180213T144528Z
TRANSP:OPAQUE
END:VEVENT
* Rockies vs. Mustangs
<2018-07-18 Wed 19:40-22:40>
:PROPERTIES:
:ID:       Gjo0cck5dV94rflKdgAedPVp@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Rockies vs. Mustangs Rockies vs. Mustangs

Follow on MiLB First Pitch  https //stza.co/+xJ7j-N

Shop  https //stza.co/+xJ7j-2r

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Rockies vs. Mustangs
END:VALARM
DTSTART:20180719T004000Z
DTEND:20180719T034000Z
UID:Gjo0cck5dV94rflKdgAedPVp@stanza.co
SUMMARY:Rockies vs. Mustangs
DESCRIPTION:Rockies vs. Mustangs\n\nFollow on MiLB First Pitch: https://stza.co/+xJ7j-N\n\nShop: https://stza.co/+xJ7j-2r\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144528Z
LAST-MODIFIED:20180213T144528Z
TRANSP:OPAQUE
END:VEVENT
* Rockies vs. Mustangs
<2018-07-19 Thu 19:40-22:40>
:PROPERTIES:
:ID:       gkkE_qSHd3mi6gO_aMqyVBzY@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Rockies vs. Mustangs Rockies vs. Mustangs

Follow on MiLB First Pitch  https //stza.co/+xJ7l-12

Shop  https //stza.co/+xJ7l-2a

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Rockies vs. Mustangs
END:VALARM
DTSTART:20180720T004000Z
DTEND:20180720T034000Z
UID:gkkE_qSHd3mi6gO_aMqyVBzY@stanza.co
SUMMARY:Rockies vs. Mustangs
DESCRIPTION:Rockies vs. Mustangs\n\nFollow on MiLB First Pitch: https://stza.co/+xJ7l-12\n\nShop: https://stza.co/+xJ7l-2a\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144528Z
LAST-MODIFIED:20180213T144528Z
TRANSP:OPAQUE
END:VEVENT
* Rockies vs. Mustangs
<2018-07-20 Fri 19:40-22:40>
:PROPERTIES:
:ID:       gDPWk6kSiLVqPh4ND4Rf1o4M@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Rockies vs. Mustangs Rockies vs. Mustangs

Follow on MiLB First Pitch  https //stza.co/+xJ7m-i

Shop  https //stza.co/+xJ7m-2i

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Rockies vs. Mustangs
END:VALARM
DTSTART:20180721T004000Z
DTEND:20180721T034000Z
UID:gDPWk6kSiLVqPh4ND4Rf1o4M@stanza.co
SUMMARY:Rockies vs. Mustangs
DESCRIPTION:Rockies vs. Mustangs\n\nFollow on MiLB First Pitch: https://stza.co/+xJ7m-i\n\nShop: https://stza.co/+xJ7m-2i\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144528Z
LAST-MODIFIED:20180213T144528Z
TRANSP:OPAQUE
END:VEVENT
* Rockies vs. Voyagers
<2018-07-21 Sat 19:40-22:40>
:PROPERTIES:
:ID:       A89-xdJhY1G3knCkfHRPrVXi@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Rockies vs. Voyagers Rockies vs. Voyagers

Follow on MiLB First Pitch  https //stza.co/+xJ7p-3l

Shop  https //stza.co/+xJ7p-2a

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Rockies vs. Voyagers
END:VALARM
DTSTART:20180722T004000Z
DTEND:20180722T034000Z
UID:A89-xdJhY1G3knCkfHRPrVXi@stanza.co
SUMMARY:Rockies vs. Voyagers
DESCRIPTION:Rockies vs. Voyagers\n\nFollow on MiLB First Pitch: https://stza.co/+xJ7p-3l\n\nShop: https://stza.co/+xJ7p-2a\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144528Z
LAST-MODIFIED:20180213T144528Z
TRANSP:OPAQUE
END:VEVENT
* Rockies vs. Voyagers
<2018-07-22 Sun 18:00-21:00>
:PROPERTIES:
:ID:       Aq8QxZPOMxvv1IhfJ6ZBAzXa@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Rockies vs. Voyagers Rockies vs. Voyagers

Follow on MiLB First Pitch  https //stza.co/+xJ7q-1u

Shop  https //stza.co/+xJ7q-2o

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Rockies vs. Voyagers
END:VALARM
DTSTART:20180722T230000Z
DTEND:20180723T020000Z
UID:Aq8QxZPOMxvv1IhfJ6ZBAzXa@stanza.co
SUMMARY:Rockies vs. Voyagers
DESCRIPTION:Rockies vs. Voyagers\n\nFollow on MiLB First Pitch: https://stza.co/+xJ7q-1u\n\nShop: https://stza.co/+xJ7q-2o\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144528Z
LAST-MODIFIED:20180213T144528Z
TRANSP:OPAQUE
END:VEVENT
* Rockies vs. Voyagers
<2018-07-23 Mon 19:40-22:40>
:PROPERTIES:
:ID:       akUR16ROT27dIUOWk867avm_@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Rockies vs. Voyagers Rockies vs. Voyagers

Follow on MiLB First Pitch  https //stza.co/+xJ7s-6

Shop  https //stza.co/+xJ7s-1b

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Rockies vs. Voyagers
END:VALARM
DTSTART:20180724T004000Z
DTEND:20180724T034000Z
UID:akUR16ROT27dIUOWk867avm_@stanza.co
SUMMARY:Rockies vs. Voyagers
DESCRIPTION:Rockies vs. Voyagers\n\nFollow on MiLB First Pitch: https://stza.co/+xJ7s-6\n\nShop: https://stza.co/+xJ7s-1b\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144528Z
LAST-MODIFIED:20180213T144528Z
TRANSP:OPAQUE
END:VEVENT
* Rockies vs. Voyagers
<2018-07-24 Tue 19:40-22:40>
:PROPERTIES:
:ID:       3GX03H-cZpRJmueMkoVlt-BY@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Rockies vs. Voyagers Rockies vs. Voyagers

Follow on MiLB First Pitch  https //stza.co/+xJ7v-3m

Shop  https //stza.co/+xJ7v-19

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Rockies vs. Voyagers
END:VALARM
DTSTART:20180725T004000Z
DTEND:20180725T034000Z
UID:3GX03H-cZpRJmueMkoVlt-BY@stanza.co
SUMMARY:Rockies vs. Voyagers
DESCRIPTION:Rockies vs. Voyagers\n\nFollow on MiLB First Pitch: https://stza.co/+xJ7v-3m\n\nShop: https://stza.co/+xJ7v-19\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144528Z
LAST-MODIFIED:20180213T144528Z
TRANSP:OPAQUE
END:VEVENT
* Rockies @ Raptors
<2018-07-25 Wed 20:00-23:00>
:PROPERTIES:
:ID:       S6kcC6HPem_UH63Z9nzSVFnb@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Rockies @ Raptors Rockies @ Raptors

Follow on MiLB First Pitch  https //stza.co/+x$7R-2I

Shop  https //stza.co/+x$7R-8

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Rockies @ Raptors
END:VALARM
DTSTART:20180726T010000Z
DTEND:20180726T040000Z
UID:S6kcC6HPem_UH63Z9nzSVFnb@stanza.co
SUMMARY:Rockies @ Raptors
DESCRIPTION:Rockies @ Raptors\n\nFollow on MiLB First Pitch: https://stza.co/+x$7R-2I\n\nShop: https://stza.co/+x$7R-8\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144528Z
LAST-MODIFIED:20180213T144528Z
TRANSP:OPAQUE
END:VEVENT
* Rockies @ Raptors
<2018-07-26 Thu 20:00-23:00>
:PROPERTIES:
:ID:       ZEaJHNuo00YHALOnZ-RHFojp@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Rockies @ Raptors Rockies @ Raptors

Follow on MiLB First Pitch  https //stza.co/+x$7S-1n

Shop  https //stza.co/+x$7S-34

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Rockies @ Raptors
END:VALARM
DTSTART:20180727T010000Z
DTEND:20180727T040000Z
UID:ZEaJHNuo00YHALOnZ-RHFojp@stanza.co
SUMMARY:Rockies @ Raptors
DESCRIPTION:Rockies @ Raptors\n\nFollow on MiLB First Pitch: https://stza.co/+x$7S-1n\n\nShop: https://stza.co/+x$7S-34\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144528Z
LAST-MODIFIED:20180213T144528Z
TRANSP:OPAQUE
END:VEVENT
* Rockies @ Raptors
<2018-07-27 Fri 20:00-23:00>
:PROPERTIES:
:ID:       NsfN66v3xt6IzEDCuknGUZdV@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Rockies @ Raptors Rockies @ Raptors

Follow on MiLB First Pitch  https //stza.co/+x$7T-2h

Shop  https //stza.co/+x$7T-B

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Rockies @ Raptors
END:VALARM
DTSTART:20180728T010000Z
DTEND:20180728T040000Z
UID:NsfN66v3xt6IzEDCuknGUZdV@stanza.co
SUMMARY:Rockies @ Raptors
DESCRIPTION:Rockies @ Raptors\n\nFollow on MiLB First Pitch: https://stza.co/+x$7T-2h\n\nShop: https://stza.co/+x$7T-B\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144528Z
LAST-MODIFIED:20180213T144528Z
TRANSP:OPAQUE
END:VEVENT
* Rockies vs. Owlz
<2018-07-28 Sat 19:40-22:40>
:PROPERTIES:
:ID:       QufIceht41xzvfzza0wYEmJ_@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Rockies vs. Owlz Rockies vs. Owlz

Follow on MiLB First Pitch  https //stza.co/+xJ7w-V

Shop  https //stza.co/+xJ7w-G

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Rockies vs. Owlz
END:VALARM
DTSTART:20180729T004000Z
DTEND:20180729T034000Z
UID:QufIceht41xzvfzza0wYEmJ_@stanza.co
SUMMARY:Rockies vs. Owlz
DESCRIPTION:Rockies vs. Owlz\n\nFollow on MiLB First Pitch: https://stza.co/+xJ7w-V\n\nShop: https://stza.co/+xJ7w-G\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144528Z
LAST-MODIFIED:20180213T144528Z
TRANSP:OPAQUE
END:VEVENT
* Rockies vs. Owlz
<2018-07-29 Sun 18:00-21:00>
:PROPERTIES:
:ID:       _tFcZ01HJhzdYNstluB1K1jJ@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Rockies vs. Owlz Rockies vs. Owlz

Follow on MiLB First Pitch  https //stza.co/+xJ7z-15

Shop  https //stza.co/+xJ7z-19

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Rockies vs. Owlz
END:VALARM
DTSTART:20180729T230000Z
DTEND:20180730T020000Z
UID:_tFcZ01HJhzdYNstluB1K1jJ@stanza.co
SUMMARY:Rockies vs. Owlz
DESCRIPTION:Rockies vs. Owlz\n\nFollow on MiLB First Pitch: https://stza.co/+xJ7z-15\n\nShop: https://stza.co/+xJ7z-19\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144528Z
LAST-MODIFIED:20180213T144528Z
TRANSP:OPAQUE
END:VEVENT
* Rockies vs. Raptors
<2018-07-30 Mon 19:40-22:40>
:PROPERTIES:
:ID:       956pwYLWEYSg6x8HiE-s11WF@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Rockies vs. Raptors Rockies vs. Raptors

Follow on MiLB First Pitch  https //stza.co/+xJ7B-1q

Shop  https //stza.co/+xJ7B-I

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Rockies vs. Raptors
END:VALARM
DTSTART:20180731T004000Z
DTEND:20180731T034000Z
UID:956pwYLWEYSg6x8HiE-s11WF@stanza.co
SUMMARY:Rockies vs. Raptors
DESCRIPTION:Rockies vs. Raptors\n\nFollow on MiLB First Pitch: https://stza.co/+xJ7B-1q\n\nShop: https://stza.co/+xJ7B-I\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144528Z
LAST-MODIFIED:20180213T144528Z
TRANSP:OPAQUE
END:VEVENT
* Rockies vs. Raptors
<2018-07-31 Tue 19:40-22:40>
:PROPERTIES:
:ID:       nr4zgi00xBrev764kBFM9uJh@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Rockies vs. Raptors Rockies vs. Raptors

Follow on MiLB First Pitch  https //stza.co/+xJ7C-Q

Shop  https //stza.co/+xJ7C-10

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Rockies vs. Raptors
END:VALARM
DTSTART:20180801T004000Z
DTEND:20180801T034000Z
UID:nr4zgi00xBrev764kBFM9uJh@stanza.co
SUMMARY:Rockies vs. Raptors
DESCRIPTION:Rockies vs. Raptors\n\nFollow on MiLB First Pitch: https://stza.co/+xJ7C-Q\n\nShop: https://stza.co/+xJ7C-10\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144528Z
LAST-MODIFIED:20180213T144528Z
TRANSP:OPAQUE
END:VEVENT
* Rockies vs. Raptors
<2018-08-01 Wed 19:40-22:40>
:PROPERTIES:
:ID:       Nj-msVKXhh3jN4L8h1nG0v5r@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Rockies vs. Raptors Rockies vs. Raptors

Follow on MiLB First Pitch  https //stza.co/+xJ7E-23

Shop  https //stza.co/+xJ7E-10

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Rockies vs. Raptors
END:VALARM
DTSTART:20180802T004000Z
DTEND:20180802T034000Z
UID:Nj-msVKXhh3jN4L8h1nG0v5r@stanza.co
SUMMARY:Rockies vs. Raptors
DESCRIPTION:Rockies vs. Raptors\n\nFollow on MiLB First Pitch: https://stza.co/+xJ7E-23\n\nShop: https://stza.co/+xJ7E-10\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144528Z
LAST-MODIFIED:20180213T144528Z
TRANSP:OPAQUE
END:VEVENT
* Rockies @ Chukars
<2018-08-02 Thu 20:15-23:15>
:PROPERTIES:
:ID:       Uvlm48oWON0OqMhPHU_Ai6BI@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Rockies @ Chukars Rockies @ Chukars

Follow on MiLB First Pitch  https //stza.co/+xZUE-2U

Shop  https //stza.co/+xZUE-28

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Rockies @ Chukars
END:VALARM
DTSTART:20180803T011500Z
DTEND:20180803T041500Z
UID:Uvlm48oWON0OqMhPHU_Ai6BI@stanza.co
SUMMARY:Rockies @ Chukars
DESCRIPTION:Rockies @ Chukars\n\nFollow on MiLB First Pitch: https://stza.co/+xZUE-2U\n\nShop: https://stza.co/+xZUE-28\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144528Z
LAST-MODIFIED:20180213T144528Z
TRANSP:OPAQUE
END:VEVENT
* Rockies @ Chukars
<2018-08-03 Fri 20:15-23:15>
:PROPERTIES:
:ID:       KVk6hO-N66W-8MI9yx9Sux0Q@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Rockies @ Chukars Rockies @ Chukars

Follow on MiLB First Pitch  https //stza.co/+xZUF-2t

Shop  https //stza.co/+xZUF-2H

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Rockies @ Chukars
END:VALARM
DTSTART:20180804T011500Z
DTEND:20180804T041500Z
UID:KVk6hO-N66W-8MI9yx9Sux0Q@stanza.co
SUMMARY:Rockies @ Chukars
DESCRIPTION:Rockies @ Chukars\n\nFollow on MiLB First Pitch: https://stza.co/+xZUF-2t\n\nShop: https://stza.co/+xZUF-2H\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144528Z
LAST-MODIFIED:20180213T144528Z
TRANSP:OPAQUE
END:VEVENT
* Rockies @ Chukars
<2018-08-04 Sat 20:15-23:15>
:PROPERTIES:
:ID:       rDDv4wflndHCV2lAjtW03Vd8@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Rockies @ Chukars Rockies @ Chukars

Follow on MiLB First Pitch  https //stza.co/+xZUG-1n

Shop  https //stza.co/+xZUG-1E

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Rockies @ Chukars
END:VALARM
DTSTART:20180805T011500Z
DTEND:20180805T041500Z
UID:rDDv4wflndHCV2lAjtW03Vd8@stanza.co
SUMMARY:Rockies @ Chukars
DESCRIPTION:Rockies @ Chukars\n\nFollow on MiLB First Pitch: https://stza.co/+xZUG-1n\n\nShop: https://stza.co/+xZUG-1E\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144528Z
LAST-MODIFIED:20180213T144528Z
TRANSP:OPAQUE
END:VEVENT
* Rockies @ Chukars
<2018-08-05 Sun 17:00-20:00>
:PROPERTIES:
:ID:       x0nf-gkLgeb9XILhvFbtNAUC@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Rockies @ Chukars Rockies @ Chukars

Follow on MiLB First Pitch  https //stza.co/+xZUH-1P

Shop  https //stza.co/+xZUH-2n

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Rockies @ Chukars
END:VALARM
DTSTART:20180805T220000Z
DTEND:20180806T010000Z
UID:x0nf-gkLgeb9XILhvFbtNAUC@stanza.co
SUMMARY:Rockies @ Chukars
DESCRIPTION:Rockies @ Chukars\n\nFollow on MiLB First Pitch: https://stza.co/+xZUH-1P\n\nShop: https://stza.co/+xZUH-2n\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144528Z
LAST-MODIFIED:20180213T144528Z
TRANSP:OPAQUE
END:VEVENT
* Rockies vs. Brewers
<2018-08-09 Thu 19:40-22:40>
:PROPERTIES:
:ID:       7WuUHkhzJuyej0q2uwo0BXyZ@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Rockies vs. Brewers Rockies vs. Brewers

Follow on MiLB First Pitch  https //stza.co/+xJ7G-O

Shop  https //stza.co/+xJ7G-

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Rockies vs. Brewers
END:VALARM
DTSTART:20180810T004000Z
DTEND:20180810T034000Z
UID:7WuUHkhzJuyej0q2uwo0BXyZ@stanza.co
SUMMARY:Rockies vs. Brewers
DESCRIPTION:Rockies vs. Brewers\n\nFollow on MiLB First Pitch: https://stza.co/+xJ7G-O\n\nShop: https://stza.co/+xJ7G-\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144528Z
LAST-MODIFIED:20180213T144528Z
TRANSP:OPAQUE
END:VEVENT
* Rockies vs. Brewers
<2018-08-10 Fri 19:40-22:40>
:PROPERTIES:
:ID:       TcZUbWHaaqjQVue9y9MlN7zl@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Rockies vs. Brewers Rockies vs. Brewers

Follow on MiLB First Pitch  https //stza.co/+xJ7I-1P

Shop  https //stza.co/+xJ7I-3w

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Rockies vs. Brewers
END:VALARM
DTSTART:20180811T004000Z
DTEND:20180811T034000Z
UID:TcZUbWHaaqjQVue9y9MlN7zl@stanza.co
SUMMARY:Rockies vs. Brewers
DESCRIPTION:Rockies vs. Brewers\n\nFollow on MiLB First Pitch: https://stza.co/+xJ7I-1P\n\nShop: https://stza.co/+xJ7I-3w\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144528Z
LAST-MODIFIED:20180213T144528Z
TRANSP:OPAQUE
END:VEVENT
* Rockies vs. Brewers
<2018-08-11 Sat 19:40-22:40>
:PROPERTIES:
:ID:       LFEvWHIl7-x50rC-ibNTOQYC@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Rockies vs. Brewers Rockies vs. Brewers

Follow on MiLB First Pitch  https //stza.co/+xJ7K-2E

Shop  https //stza.co/+xJ7K-2y

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Rockies vs. Brewers
END:VALARM
DTSTART:20180812T004000Z
DTEND:20180812T034000Z
UID:LFEvWHIl7-x50rC-ibNTOQYC@stanza.co
SUMMARY:Rockies vs. Brewers
DESCRIPTION:Rockies vs. Brewers\n\nFollow on MiLB First Pitch: https://stza.co/+xJ7K-2E\n\nShop: https://stza.co/+xJ7K-2y\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144528Z
LAST-MODIFIED:20180213T144528Z
TRANSP:OPAQUE
END:VEVENT
* Rockies vs. Brewers
<2018-08-12 Sun 18:00-21:00>
:PROPERTIES:
:ID:       wBi26BZgj76UkwqS6YeBlLr0@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Rockies vs. Brewers Rockies vs. Brewers

Follow on MiLB First Pitch  https //stza.co/+xJ7N-21

Shop  https //stza.co/+xJ7N-3i

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Rockies vs. Brewers
END:VALARM
DTSTART:20180812T230000Z
DTEND:20180813T020000Z
UID:wBi26BZgj76UkwqS6YeBlLr0@stanza.co
SUMMARY:Rockies vs. Brewers
DESCRIPTION:Rockies vs. Brewers\n\nFollow on MiLB First Pitch: https://stza.co/+xJ7N-21\n\nShop: https://stza.co/+xJ7N-3i\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144528Z
LAST-MODIFIED:20180213T144528Z
TRANSP:OPAQUE
END:VEVENT
* Rockies vs. Osprey
<2018-08-13 Mon 19:40-22:40>
:PROPERTIES:
:ID:       6WGMK5gmrW_WvFQ5ioVdERSP@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Rockies vs. Osprey Rockies vs. Osprey

Follow on MiLB First Pitch  https //stza.co/+xJ7P-3B

Shop  https //stza.co/+xJ7P-1z

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Rockies vs. Osprey
END:VALARM
DTSTART:20180814T004000Z
DTEND:20180814T034000Z
UID:6WGMK5gmrW_WvFQ5ioVdERSP@stanza.co
SUMMARY:Rockies vs. Osprey
DESCRIPTION:Rockies vs. Osprey\n\nFollow on MiLB First Pitch: https://stza.co/+xJ7P-3B\n\nShop: https://stza.co/+xJ7P-1z\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144528Z
LAST-MODIFIED:20180213T144528Z
TRANSP:OPAQUE
END:VEVENT
* Rockies vs. Osprey
<2018-08-14 Tue 19:40-22:40>
:PROPERTIES:
:ID:       rd02gaKDNnqcnSEmE28v89Mk@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Rockies vs. Osprey Rockies vs. Osprey

Follow on MiLB First Pitch  https //stza.co/+xJ7R-1r

Shop  https //stza.co/+xJ7R-1V

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Rockies vs. Osprey
END:VALARM
DTSTART:20180815T004000Z
DTEND:20180815T034000Z
UID:rd02gaKDNnqcnSEmE28v89Mk@stanza.co
SUMMARY:Rockies vs. Osprey
DESCRIPTION:Rockies vs. Osprey\n\nFollow on MiLB First Pitch: https://stza.co/+xJ7R-1r\n\nShop: https://stza.co/+xJ7R-1V\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144528Z
LAST-MODIFIED:20180213T144528Z
TRANSP:OPAQUE
END:VEVENT
* Rockies vs. Osprey
<2018-08-15 Wed 19:40-22:40>
:PROPERTIES:
:ID:       -o81u9COyhXuCc-4EMPE7-Tz@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Rockies vs. Osprey Rockies vs. Osprey

Follow on MiLB First Pitch  https //stza.co/+xJ7S-3f

Shop  https //stza.co/+xJ7S-9

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Rockies vs. Osprey
END:VALARM
DTSTART:20180816T004000Z
DTEND:20180816T034000Z
UID:-o81u9COyhXuCc-4EMPE7-Tz@stanza.co
SUMMARY:Rockies vs. Osprey
DESCRIPTION:Rockies vs. Osprey\n\nFollow on MiLB First Pitch: https://stza.co/+xJ7S-3f\n\nShop: https://stza.co/+xJ7S-9\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144528Z
LAST-MODIFIED:20180213T144528Z
TRANSP:OPAQUE
END:VEVENT
* Rockies @ Brewers
<2018-08-17 Fri>--<2018-08-16 Thu>
:PROPERTIES:
:ID:       hpfDTAmSnP-UigOcwz3QYQJb@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Rockies @ Brewers Rockies @ Brewers

Follow on MiLB First Pitch  https //stza.co/+xCmg-3b

Shop  https //stza.co/+xCmg-2N

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Rockies @ Brewers
END:VALARM
DTSTART;VALUE=DATE:20180817
DTEND;VALUE=DATE:20180817
UID:hpfDTAmSnP-UigOcwz3QYQJb@stanza.co
SUMMARY:Rockies @ Brewers
DESCRIPTION:Rockies @ Brewers\n\nFollow on MiLB First Pitch: https://stza.co/+xCmg-3b\n\nShop: https://stza.co/+xCmg-2N\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144528Z
LAST-MODIFIED:20180213T144528Z
TRANSP:OPAQUE
END:VEVENT
* Rockies @ Brewers
<2018-08-18 Sat>--<2018-08-17 Fri>
:PROPERTIES:
:ID:       nFHhsvo1tUHDzpHmsr8K0Li7@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Rockies @ Brewers Rockies @ Brewers

Follow on MiLB First Pitch  https //stza.co/+xCmi-2i

Shop  https //stza.co/+xCmi-1V

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Rockies @ Brewers
END:VALARM
DTSTART;VALUE=DATE:20180818
DTEND;VALUE=DATE:20180818
UID:nFHhsvo1tUHDzpHmsr8K0Li7@stanza.co
SUMMARY:Rockies @ Brewers
DESCRIPTION:Rockies @ Brewers\n\nFollow on MiLB First Pitch: https://stza.co/+xCmi-2i\n\nShop: https://stza.co/+xCmi-1V\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144528Z
LAST-MODIFIED:20180213T144528Z
TRANSP:OPAQUE
END:VEVENT
* Rockies @ Brewers
<2018-08-19 Sun>--<2018-08-18 Sat>
:PROPERTIES:
:ID:       dw3yeTNFAWuVD3Zjg3gZJii7@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Rockies @ Brewers Rockies @ Brewers

Follow on MiLB First Pitch  https //stza.co/+xCmk-9

Shop  https //stza.co/+xCmk-1g

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Rockies @ Brewers
END:VALARM
DTSTART;VALUE=DATE:20180819
DTEND;VALUE=DATE:20180819
UID:dw3yeTNFAWuVD3Zjg3gZJii7@stanza.co
SUMMARY:Rockies @ Brewers
DESCRIPTION:Rockies @ Brewers\n\nFollow on MiLB First Pitch: https://stza.co/+xCmk-9\n\nShop: https://stza.co/+xCmk-1g\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144528Z
LAST-MODIFIED:20180213T144528Z
TRANSP:OPAQUE
END:VEVENT
* Rockies @ Osprey
<2018-08-20 Mon>--<2018-08-19 Sun>
:PROPERTIES:
:ID:       RY2ZP5_HiGjnw-x9kGxtyiSi@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Rockies @ Osprey Rockies @ Osprey

Follow on MiLB First Pitch  https //stza.co/+xCno-2H

Shop  https //stza.co/+xCno-3a

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Rockies @ Osprey
END:VALARM
DTSTART;VALUE=DATE:20180820
DTEND;VALUE=DATE:20180820
UID:RY2ZP5_HiGjnw-x9kGxtyiSi@stanza.co
SUMMARY:Rockies @ Osprey
DESCRIPTION:Rockies @ Osprey\n\nFollow on MiLB First Pitch: https://stza.co/+xCno-2H\n\nShop: https://stza.co/+xCno-3a\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144528Z
LAST-MODIFIED:20180213T144528Z
TRANSP:OPAQUE
END:VEVENT
* Rockies @ Osprey
<2018-08-21 Tue>--<2018-08-20 Mon>
:PROPERTIES:
:ID:       sq6Y9LtuKa5VPgFQ_vh35Ivh@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Rockies @ Osprey Rockies @ Osprey

Follow on MiLB First Pitch  https //stza.co/+xCnq-2x

Shop  https //stza.co/+xCnq-2b

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Rockies @ Osprey
END:VALARM
DTSTART;VALUE=DATE:20180821
DTEND;VALUE=DATE:20180821
UID:sq6Y9LtuKa5VPgFQ_vh35Ivh@stanza.co
SUMMARY:Rockies @ Osprey
DESCRIPTION:Rockies @ Osprey\n\nFollow on MiLB First Pitch: https://stza.co/+xCnq-2x\n\nShop: https://stza.co/+xCnq-2b\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144528Z
LAST-MODIFIED:20180213T144528Z
TRANSP:OPAQUE
END:VEVENT
* Rockies @ Osprey
<2018-08-22 Wed>--<2018-08-21 Tue>
:PROPERTIES:
:ID:       dWyWqOwrYvGLuDOIkb5X1Bpz@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Rockies @ Osprey Rockies @ Osprey

Follow on MiLB First Pitch  https //stza.co/+xCns-3p

Shop  https //stza.co/+xCns-3W

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Rockies @ Osprey
END:VALARM
DTSTART;VALUE=DATE:20180822
DTEND;VALUE=DATE:20180822
UID:dWyWqOwrYvGLuDOIkb5X1Bpz@stanza.co
SUMMARY:Rockies @ Osprey
DESCRIPTION:Rockies @ Osprey\n\nFollow on MiLB First Pitch: https://stza.co/+xCns-3p\n\nShop: https://stza.co/+xCns-3W\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144528Z
LAST-MODIFIED:20180213T144528Z
TRANSP:OPAQUE
END:VEVENT
* Rockies @ Osprey
<2018-08-23 Thu>--<2018-08-22 Wed>
:PROPERTIES:
:ID:       pC5rIjIv4SprpNIy80Gsmjer@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Rockies @ Osprey Rockies @ Osprey

Follow on MiLB First Pitch  https //stza.co/+xCnu-g

Shop  https //stza.co/+xCnu-6

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Rockies @ Osprey
END:VALARM
DTSTART;VALUE=DATE:20180823
DTEND;VALUE=DATE:20180823
UID:pC5rIjIv4SprpNIy80Gsmjer@stanza.co
SUMMARY:Rockies @ Osprey
DESCRIPTION:Rockies @ Osprey\n\nFollow on MiLB First Pitch: https://stza.co/+xCnu-g\n\nShop: https://stza.co/+xCnu-6\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144528Z
LAST-MODIFIED:20180213T144528Z
TRANSP:OPAQUE
END:VEVENT
* Rockies vs. Chukars
<2018-08-25 Sat 19:40-22:40>
:PROPERTIES:
:ID:       AgdP2PkZlMAEz2eSMQ5nX4rZ@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Rockies vs. Chukars Rockies vs. Chukars

Follow on MiLB First Pitch  https //stza.co/+xJ7V-2t

Shop  https //stza.co/+xJ7V-3T

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Rockies vs. Chukars
END:VALARM
DTSTART:20180826T004000Z
DTEND:20180826T034000Z
UID:AgdP2PkZlMAEz2eSMQ5nX4rZ@stanza.co
SUMMARY:Rockies vs. Chukars
DESCRIPTION:Rockies vs. Chukars\n\nFollow on MiLB First Pitch: https://stza.co/+xJ7V-2t\n\nShop: https://stza.co/+xJ7V-3T\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144528Z
LAST-MODIFIED:20180213T144528Z
TRANSP:OPAQUE
END:VEVENT
* Rockies vs. Chukars
<2018-08-26 Sun 18:00-21:00>
:PROPERTIES:
:ID:       D2F61ln0aj9vdo44Atr5Kc3s@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Rockies vs. Chukars Rockies vs. Chukars

Follow on MiLB First Pitch  https //stza.co/+xJ7W-1d

Shop  https //stza.co/+xJ7W-2b

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Rockies vs. Chukars
END:VALARM
DTSTART:20180826T230000Z
DTEND:20180827T020000Z
UID:D2F61ln0aj9vdo44Atr5Kc3s@stanza.co
SUMMARY:Rockies vs. Chukars
DESCRIPTION:Rockies vs. Chukars\n\nFollow on MiLB First Pitch: https://stza.co/+xJ7W-1d\n\nShop: https://stza.co/+xJ7W-2b\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144528Z
LAST-MODIFIED:20180213T144528Z
TRANSP:OPAQUE
END:VEVENT
* Rockies vs. Chukars
<2018-08-27 Mon 19:40-22:40>
:PROPERTIES:
:ID:       plq35EnxLlK4FbdG0oHrdusX@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Rockies vs. Chukars Rockies vs. Chukars

Follow on MiLB First Pitch  https //stza.co/+xJ7Y-5

Shop  https //stza.co/+xJ7Y-2$

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Rockies vs. Chukars
END:VALARM
DTSTART:20180828T004000Z
DTEND:20180828T034000Z
UID:plq35EnxLlK4FbdG0oHrdusX@stanza.co
SUMMARY:Rockies vs. Chukars
DESCRIPTION:Rockies vs. Chukars\n\nFollow on MiLB First Pitch: https://stza.co/+xJ7Y-5\n\nShop: https://stza.co/+xJ7Y-2$\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144528Z
LAST-MODIFIED:20180213T144528Z
TRANSP:OPAQUE
END:VEVENT
* Rockies vs. Chukars
<2018-08-28 Tue 19:40-22:40>
:PROPERTIES:
:ID:       DqNxxVcJQ3hOABFDpbzdYOeY@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Rockies vs. Chukars Rockies vs. Chukars

Follow on MiLB First Pitch  https //stza.co/+xJ7$-3M

Shop  https //stza.co/+xJ7$-1o

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Rockies vs. Chukars
END:VALARM
DTSTART:20180829T004000Z
DTEND:20180829T034000Z
UID:DqNxxVcJQ3hOABFDpbzdYOeY@stanza.co
SUMMARY:Rockies vs. Chukars
DESCRIPTION:Rockies vs. Chukars\n\nFollow on MiLB First Pitch: https://stza.co/+xJ7$-3M\n\nShop: https://stza.co/+xJ7$-1o\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144528Z
LAST-MODIFIED:20180213T144528Z
TRANSP:OPAQUE
END:VEVENT
* Rockies @ Owlz
<2018-08-29 Wed 19:35-22:35>
:PROPERTIES:
:ID:       8UrXOWcyU9GOMG5msbk5ki6W@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Rockies @ Owlz Rockies @ Owlz

Follow on MiLB First Pitch  https //stza.co/+xPB8-21

Shop  https //stza.co/+xPB8-a

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Rockies @ Owlz
END:VALARM
DTSTART:20180830T003500Z
DTEND:20180830T033500Z
UID:8UrXOWcyU9GOMG5msbk5ki6W@stanza.co
SUMMARY:Rockies @ Owlz
DESCRIPTION:Rockies @ Owlz\n\nFollow on MiLB First Pitch: https://stza.co/+xPB8-21\n\nShop: https://stza.co/+xPB8-a\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144528Z
LAST-MODIFIED:20180213T144528Z
TRANSP:OPAQUE
END:VEVENT
* Rockies @ Owlz
<2018-08-30 Thu 19:35-22:35>
:PROPERTIES:
:ID:       eCVkPYx1xSR6e8FSHl1cQnwD@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Rockies @ Owlz Rockies @ Owlz

Follow on MiLB First Pitch  https //stza.co/+xPB9-9

Shop  https //stza.co/+xPB9-37

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Rockies @ Owlz
END:VALARM
DTSTART:20180831T003500Z
DTEND:20180831T033500Z
UID:eCVkPYx1xSR6e8FSHl1cQnwD@stanza.co
SUMMARY:Rockies @ Owlz
DESCRIPTION:Rockies @ Owlz\n\nFollow on MiLB First Pitch: https://stza.co/+xPB9-9\n\nShop: https://stza.co/+xPB9-37\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144528Z
LAST-MODIFIED:20180213T144528Z
TRANSP:OPAQUE
END:VEVENT
* Rockies @ Raptors
<2018-08-31 Fri 19:30-22:30>
:PROPERTIES:
:ID:       wfcwD3iOLueBwWcWUBLQGend@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Rockies @ Raptors Rockies @ Raptors

Follow on MiLB First Pitch  https //stza.co/+x$7U-1G

Shop  https //stza.co/+x$7U-a

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Rockies @ Raptors
END:VALARM
DTSTART:20180901T003000Z
DTEND:20180901T033000Z
UID:wfcwD3iOLueBwWcWUBLQGend@stanza.co
SUMMARY:Rockies @ Raptors
DESCRIPTION:Rockies @ Raptors\n\nFollow on MiLB First Pitch: https://stza.co/+x$7U-1G\n\nShop: https://stza.co/+x$7U-a\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144528Z
LAST-MODIFIED:20180213T144528Z
TRANSP:OPAQUE
END:VEVENT
* Rockies @ Raptors
<2018-09-01 Sat 19:30-22:30>
:PROPERTIES:
:ID:       O8wXCBLA1MSuubgrOX5yiMIc@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Rockies @ Raptors Rockies @ Raptors

Follow on MiLB First Pitch  https //stza.co/+x$7V-1G

Shop  https //stza.co/+x$7V-2L

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Rockies @ Raptors
END:VALARM
DTSTART:20180902T003000Z
DTEND:20180902T033000Z
UID:O8wXCBLA1MSuubgrOX5yiMIc@stanza.co
SUMMARY:Rockies @ Raptors
DESCRIPTION:Rockies @ Raptors\n\nFollow on MiLB First Pitch: https://stza.co/+x$7V-1G\n\nShop: https://stza.co/+x$7V-2L\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144528Z
LAST-MODIFIED:20180213T144528Z
TRANSP:OPAQUE
END:VEVENT
* Rockies vs. Owlz
<2018-09-03 Mon 19:40-22:40>
:PROPERTIES:
:ID:       Lr539gWANEs25yT5CLub3XCF@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Rockies vs. Owlz Rockies vs. Owlz

Follow on MiLB First Pitch  https //stza.co/+xJ81-1D

Shop  https //stza.co/+xJ81-l

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Rockies vs. Owlz
END:VALARM
DTSTART:20180904T004000Z
DTEND:20180904T034000Z
UID:Lr539gWANEs25yT5CLub3XCF@stanza.co
SUMMARY:Rockies vs. Owlz
DESCRIPTION:Rockies vs. Owlz\n\nFollow on MiLB First Pitch: https://stza.co/+xJ81-1D\n\nShop: https://stza.co/+xJ81-l\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144528Z
LAST-MODIFIED:20180213T144528Z
TRANSP:OPAQUE
END:VEVENT
* Rockies vs. Owlz
<2018-09-04 Tue 19:40-22:40>
:PROPERTIES:
:ID:       CNVfeEmvaCn-edFZu1DX16JY@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Rockies vs. Owlz Rockies vs. Owlz

Follow on MiLB First Pitch  https //stza.co/+xJ83-3g

Shop  https //stza.co/+xJ83-2U

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Rockies vs. Owlz
END:VALARM
DTSTART:20180905T004000Z
DTEND:20180905T034000Z
UID:CNVfeEmvaCn-edFZu1DX16JY@stanza.co
SUMMARY:Rockies vs. Owlz
DESCRIPTION:Rockies vs. Owlz\n\nFollow on MiLB First Pitch: https://stza.co/+xJ83-3g\n\nShop: https://stza.co/+xJ83-2U\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144528Z
LAST-MODIFIED:20180213T144528Z
TRANSP:OPAQUE
END:VEVENT
* Rockies @ Owlz
<2018-09-05 Wed 19:35-22:35>
:PROPERTIES:
:ID:       seq5osuG--5Wc-Cmk2FtpS5u@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Rockies @ Owlz Rockies @ Owlz

Follow on MiLB First Pitch  https //stza.co/+xPBa-3u

Shop  https //stza.co/+xPBa-2s

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Rockies @ Owlz
END:VALARM
DTSTART:20180906T003500Z
DTEND:20180906T033500Z
UID:seq5osuG--5Wc-Cmk2FtpS5u@stanza.co
SUMMARY:Rockies @ Owlz
DESCRIPTION:Rockies @ Owlz\n\nFollow on MiLB First Pitch: https://stza.co/+xPBa-3u\n\nShop: https://stza.co/+xPBa-2s\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144528Z
LAST-MODIFIED:20180213T144528Z
TRANSP:OPAQUE
END:VEVENT
* Rockies @ Owlz
<2018-09-06 Thu 19:35-22:35>
:PROPERTIES:
:ID:       FtZvWsv8HSWp9R3uhJviBvri@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Rockies @ Owlz Rockies @ Owlz

Follow on MiLB First Pitch  https //stza.co/+xPBb-2W

Shop  https //stza.co/+xPBb-1h

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Rockies @ Owlz
END:VALARM
DTSTART:20180907T003500Z
DTEND:20180907T033500Z
UID:FtZvWsv8HSWp9R3uhJviBvri@stanza.co
SUMMARY:Rockies @ Owlz
DESCRIPTION:Rockies @ Owlz\n\nFollow on MiLB First Pitch: https://stza.co/+xPBb-2W\n\nShop: https://stza.co/+xPBb-1h\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144528Z
LAST-MODIFIED:20180213T144528Z
TRANSP:OPAQUE
END:VEVENT
