#+TITLE:       Main Google calendar entries
#+AUTHOR:      Eric S Fraga
#+EMAIL:       e.fraga@ucl.ac.uk
#+DESCRIPTION: converted using the ical2org awk script
#+CATEGORY:    google
#+STARTUP:     hidestars
#+STARTUP:     overview

* COMMENT original iCal preamble

* Braves vs. Smokies
<2018-04-05 Thu 19:00-22:00>
:PROPERTIES:
:ID:       YksccKaCIOWliSeU4KSf8LfG@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Braves vs. Smokies Braves vs. Smokies

Follow on MiLB First Pitch  https //stza.co/+vLJ6-1F

Shop  https //stza.co/+vLJ6-30

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Braves vs. Smokies
END:VALARM
DTSTART:20180406T000000Z
DTEND:20180406T030000Z
UID:YksccKaCIOWliSeU4KSf8LfG@stanza.co
SUMMARY:Braves vs. Smokies
DESCRIPTION:Braves vs. Smokies\n\nFollow on MiLB First Pitch: https://stza.co/+vLJ6-1F\n\nShop: https://stza.co/+vLJ6-30\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144544Z
LAST-MODIFIED:20180213T144544Z
TRANSP:OPAQUE
END:VEVENT
* Braves vs. Smokies
<2018-04-06 Fri 19:00-22:00>
:PROPERTIES:
:ID:       CcLH6L3sXYzRSXIMVyx5sP-d@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Braves vs. Smokies Braves vs. Smokies

Follow on MiLB First Pitch  https //stza.co/+vLJ8-14

Shop  https //stza.co/+vLJ8-28

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Braves vs. Smokies
END:VALARM
DTSTART:20180407T000000Z
DTEND:20180407T030000Z
UID:CcLH6L3sXYzRSXIMVyx5sP-d@stanza.co
SUMMARY:Braves vs. Smokies
DESCRIPTION:Braves vs. Smokies\n\nFollow on MiLB First Pitch: https://stza.co/+vLJ8-14\n\nShop: https://stza.co/+vLJ8-28\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144544Z
LAST-MODIFIED:20180213T144544Z
TRANSP:OPAQUE
END:VEVENT
* Braves vs. Smokies
<2018-04-07 Sat 18:00-21:00>
:PROPERTIES:
:ID:       09Ozvy4ACMvyUGIb0qjEjiSG@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Braves vs. Smokies Braves vs. Smokies

Follow on MiLB First Pitch  https //stza.co/+vLJb-W

Shop  https //stza.co/+vLJb-2e

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Braves vs. Smokies
END:VALARM
DTSTART:20180407T230000Z
DTEND:20180408T020000Z
UID:09Ozvy4ACMvyUGIb0qjEjiSG@stanza.co
SUMMARY:Braves vs. Smokies
DESCRIPTION:Braves vs. Smokies\n\nFollow on MiLB First Pitch: https://stza.co/+vLJb-W\n\nShop: https://stza.co/+vLJb-2e\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144544Z
LAST-MODIFIED:20180213T144544Z
TRANSP:OPAQUE
END:VEVENT
* Braves vs. Smokies
<2018-04-08 Sun 13:00-16:00>
:PROPERTIES:
:ID:       xj19uga7B3x6-fq4zTJRLSSD@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Braves vs. Smokies Braves vs. Smokies

Follow on MiLB First Pitch  https //stza.co/+vLJd-k

Shop  https //stza.co/+vLJd-3k

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Braves vs. Smokies
END:VALARM
DTSTART:20180408T180000Z
DTEND:20180408T210000Z
UID:xj19uga7B3x6-fq4zTJRLSSD@stanza.co
SUMMARY:Braves vs. Smokies
DESCRIPTION:Braves vs. Smokies\n\nFollow on MiLB First Pitch: https://stza.co/+vLJd-k\n\nShop: https://stza.co/+vLJd-3k\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144544Z
LAST-MODIFIED:20180213T144544Z
TRANSP:OPAQUE
END:VEVENT
* Braves vs. Smokies
<2018-04-09 Mon 10:35-13:35>
:PROPERTIES:
:ID:       rH36w71U3a5bzN3GfasyQt60@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Braves vs. Smokies Braves vs. Smokies

Follow on MiLB First Pitch  https //stza.co/+vLJf-F

Shop  https //stza.co/+vLJf-6

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Braves vs. Smokies
END:VALARM
DTSTART:20180409T153500Z
DTEND:20180409T183500Z
UID:rH36w71U3a5bzN3GfasyQt60@stanza.co
SUMMARY:Braves vs. Smokies
DESCRIPTION:Braves vs. Smokies\n\nFollow on MiLB First Pitch: https://stza.co/+vLJf-F\n\nShop: https://stza.co/+vLJf-6\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144544Z
LAST-MODIFIED:20180213T144544Z
TRANSP:OPAQUE
END:VEVENT
* Braves @ Shuckers
<2018-04-11 Wed 18:35-21:35>
:PROPERTIES:
:ID:       LrAlJu7uwN3b6NlUTkB6hurt@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Braves @ Shuckers Braves @ Shuckers

Follow on MiLB First Pitch  https //stza.co/+vLIv-q

Shop  https //stza.co/+vLIv-2z

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Braves @ Shuckers
END:VALARM
DTSTART:20180411T233500Z
DTEND:20180412T023500Z
UID:LrAlJu7uwN3b6NlUTkB6hurt@stanza.co
SUMMARY:Braves @ Shuckers
DESCRIPTION:Braves @ Shuckers\n\nFollow on MiLB First Pitch: https://stza.co/+vLIv-q\n\nShop: https://stza.co/+vLIv-2z\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144544Z
LAST-MODIFIED:20180213T144544Z
TRANSP:OPAQUE
END:VEVENT
* Braves @ Shuckers
<2018-04-12 Thu 18:35-21:35>
:PROPERTIES:
:ID:       NxbYXG42s79kFWsJREUAW41D@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Braves @ Shuckers Braves @ Shuckers

Follow on MiLB First Pitch  https //stza.co/+vLIw-3Y

Shop  https //stza.co/+vLIw-23

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Braves @ Shuckers
END:VALARM
DTSTART:20180412T233500Z
DTEND:20180413T023500Z
UID:NxbYXG42s79kFWsJREUAW41D@stanza.co
SUMMARY:Braves @ Shuckers
DESCRIPTION:Braves @ Shuckers\n\nFollow on MiLB First Pitch: https://stza.co/+vLIw-3Y\n\nShop: https://stza.co/+vLIw-23\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144544Z
LAST-MODIFIED:20180213T144544Z
TRANSP:OPAQUE
END:VEVENT
* Braves @ Shuckers
<2018-04-13 Fri 18:35-21:35>
:PROPERTIES:
:ID:       YlCSGB9-_2tXG5GXO2RaD95G@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Braves @ Shuckers Braves @ Shuckers

Follow on MiLB First Pitch  https //stza.co/+vLIx-2_

Shop  https //stza.co/+vLIx-7

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Braves @ Shuckers
END:VALARM
DTSTART:20180413T233500Z
DTEND:20180414T023500Z
UID:YlCSGB9-_2tXG5GXO2RaD95G@stanza.co
SUMMARY:Braves @ Shuckers
DESCRIPTION:Braves @ Shuckers\n\nFollow on MiLB First Pitch: https://stza.co/+vLIx-2_\n\nShop: https://stza.co/+vLIx-7\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144544Z
LAST-MODIFIED:20180213T144544Z
TRANSP:OPAQUE
END:VEVENT
* Braves @ Shuckers
<2018-04-14 Sat 18:35-21:35>
:PROPERTIES:
:ID:       Car4Z2zk4-65vq-m98VoUGxT@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Braves @ Shuckers Braves @ Shuckers

Follow on MiLB First Pitch  https //stza.co/+vLIy-R

Shop  https //stza.co/+vLIy-26

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Braves @ Shuckers
END:VALARM
DTSTART:20180414T233500Z
DTEND:20180415T023500Z
UID:Car4Z2zk4-65vq-m98VoUGxT@stanza.co
SUMMARY:Braves @ Shuckers
DESCRIPTION:Braves @ Shuckers\n\nFollow on MiLB First Pitch: https://stza.co/+vLIy-R\n\nShop: https://stza.co/+vLIy-26\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144544Z
LAST-MODIFIED:20180213T144544Z
TRANSP:OPAQUE
END:VEVENT
* Braves @ Shuckers
<2018-04-15 Sun 14:05-17:05>
:PROPERTIES:
:ID:       wU9_HVfzCt25Jh3tlxUSk7uZ@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Braves @ Shuckers Braves @ Shuckers

Follow on MiLB First Pitch  https //stza.co/+vLIz-1x

Shop  https //stza.co/+vLIz-1Y

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Braves @ Shuckers
END:VALARM
DTSTART:20180415T190500Z
DTEND:20180415T220500Z
UID:wU9_HVfzCt25Jh3tlxUSk7uZ@stanza.co
SUMMARY:Braves @ Shuckers
DESCRIPTION:Braves @ Shuckers\n\nFollow on MiLB First Pitch: https://stza.co/+vLIz-1x\n\nShop: https://stza.co/+vLIz-1Y\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144544Z
LAST-MODIFIED:20180213T144544Z
TRANSP:OPAQUE
END:VEVENT
* Braves vs. Blue Wahoos
<2018-04-16 Mon 19:00-22:00>
:PROPERTIES:
:ID:       XIv2IWA-CmvY7WLcAY9XIZrU@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Braves vs. Blue Wahoos Braves vs. Blue Wahoos

Follow on MiLB First Pitch  https //stza.co/+vLJh-3Y

Shop  https //stza.co/+vLJh-3Z

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Braves vs. Blue Wahoos
END:VALARM
DTSTART:20180417T000000Z
DTEND:20180417T030000Z
UID:XIv2IWA-CmvY7WLcAY9XIZrU@stanza.co
SUMMARY:Braves vs. Blue Wahoos
DESCRIPTION:Braves vs. Blue Wahoos\n\nFollow on MiLB First Pitch: https://stza.co/+vLJh-3Y\n\nShop: https://stza.co/+vLJh-3Z\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144544Z
LAST-MODIFIED:20180213T144544Z
TRANSP:OPAQUE
END:VEVENT
* Braves vs. Blue Wahoos
<2018-04-17 Tue 19:00-22:00>
:PROPERTIES:
:ID:       ImWzo2uVMsY1wMZjMGccuzZ1@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Braves vs. Blue Wahoos Braves vs. Blue Wahoos

Follow on MiLB First Pitch  https //stza.co/+vLJi-2N

Shop  https //stza.co/+vLJi-2e

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Braves vs. Blue Wahoos
END:VALARM
DTSTART:20180418T000000Z
DTEND:20180418T030000Z
UID:ImWzo2uVMsY1wMZjMGccuzZ1@stanza.co
SUMMARY:Braves vs. Blue Wahoos
DESCRIPTION:Braves vs. Blue Wahoos\n\nFollow on MiLB First Pitch: https://stza.co/+vLJi-2N\n\nShop: https://stza.co/+vLJi-2e\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144544Z
LAST-MODIFIED:20180213T144544Z
TRANSP:OPAQUE
END:VEVENT
* Braves vs. Blue Wahoos
<2018-04-18 Wed 10:35-13:35>
:PROPERTIES:
:ID:       Ejfgy6ED-gUHeAMvITVdXurJ@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Braves vs. Blue Wahoos Braves vs. Blue Wahoos

Follow on MiLB First Pitch  https //stza.co/+vLJl-E

Shop  https //stza.co/+vLJl-2T

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Braves vs. Blue Wahoos
END:VALARM
DTSTART:20180418T153500Z
DTEND:20180418T183500Z
UID:Ejfgy6ED-gUHeAMvITVdXurJ@stanza.co
SUMMARY:Braves vs. Blue Wahoos
DESCRIPTION:Braves vs. Blue Wahoos\n\nFollow on MiLB First Pitch: https://stza.co/+vLJl-E\n\nShop: https://stza.co/+vLJl-2T\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144544Z
LAST-MODIFIED:20180213T144544Z
TRANSP:OPAQUE
END:VEVENT
* Braves vs. Blue Wahoos
<2018-04-19 Thu 19:00-22:00>
:PROPERTIES:
:ID:       gBiLOytXiX5Lup1WsOxS4qNx@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Braves vs. Blue Wahoos Braves vs. Blue Wahoos

Follow on MiLB First Pitch  https //stza.co/+vLJm-3m

Shop  https //stza.co/+vLJm-1r

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Braves vs. Blue Wahoos
END:VALARM
DTSTART:20180420T000000Z
DTEND:20180420T030000Z
UID:gBiLOytXiX5Lup1WsOxS4qNx@stanza.co
SUMMARY:Braves vs. Blue Wahoos
DESCRIPTION:Braves vs. Blue Wahoos\n\nFollow on MiLB First Pitch: https://stza.co/+vLJm-3m\n\nShop: https://stza.co/+vLJm-1r\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144544Z
LAST-MODIFIED:20180213T144544Z
TRANSP:OPAQUE
END:VEVENT
* Braves vs. Blue Wahoos
<2018-04-20 Fri 19:00-22:00>
:PROPERTIES:
:ID:       ws_wxMf6YSRYiY81jUuGexJ-@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Braves vs. Blue Wahoos Braves vs. Blue Wahoos

Follow on MiLB First Pitch  https //stza.co/+vLJp-2Y

Shop  https //stza.co/+vLJp-w

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Braves vs. Blue Wahoos
END:VALARM
DTSTART:20180421T000000Z
DTEND:20180421T030000Z
UID:ws_wxMf6YSRYiY81jUuGexJ-@stanza.co
SUMMARY:Braves vs. Blue Wahoos
DESCRIPTION:Braves vs. Blue Wahoos\n\nFollow on MiLB First Pitch: https://stza.co/+vLJp-2Y\n\nShop: https://stza.co/+vLJp-w\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144544Z
LAST-MODIFIED:20180213T144544Z
TRANSP:OPAQUE
END:VEVENT
* Braves @ BayBears
<2018-04-21 Sat 19:05-22:05>
:PROPERTIES:
:ID:       5qEkRAURcX843o2d1TuVxIqK@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Braves @ BayBears Braves @ BayBears

Follow on MiLB First Pitch  https //stza.co/+v$PX-Z

Shop  https //stza.co/+v$PX-U

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Braves @ BayBears
END:VALARM
DTSTART:20180422T000500Z
DTEND:20180422T030500Z
UID:5qEkRAURcX843o2d1TuVxIqK@stanza.co
SUMMARY:Braves @ BayBears
DESCRIPTION:Braves @ BayBears\n\nFollow on MiLB First Pitch: https://stza.co/+v$PX-Z\n\nShop: https://stza.co/+v$PX-U\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144544Z
LAST-MODIFIED:20180213T144544Z
TRANSP:OPAQUE
END:VEVENT
* Braves @ BayBears
<2018-04-22 Sun 14:05-17:05>
:PROPERTIES:
:ID:       ns-ZX9BxameawIalYn2E6hzb@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Braves @ BayBears Braves @ BayBears

Follow on MiLB First Pitch  https //stza.co/+v$PY-3h

Shop  https //stza.co/+v$PY-1K

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Braves @ BayBears
END:VALARM
DTSTART:20180422T190500Z
DTEND:20180422T220500Z
UID:ns-ZX9BxameawIalYn2E6hzb@stanza.co
SUMMARY:Braves @ BayBears
DESCRIPTION:Braves @ BayBears\n\nFollow on MiLB First Pitch: https://stza.co/+v$PY-3h\n\nShop: https://stza.co/+v$PY-1K\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144544Z
LAST-MODIFIED:20180213T144544Z
TRANSP:OPAQUE
END:VEVENT
* Braves @ BayBears
<2018-04-23 Mon 18:35-21:35>
:PROPERTIES:
:ID:       _nV-PS5M9krHrxslm1RAXk2T@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Braves @ BayBears Braves @ BayBears

Follow on MiLB First Pitch  https //stza.co/+v$PZ-24

Shop  https //stza.co/+v$PZ-3V

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Braves @ BayBears
END:VALARM
DTSTART:20180423T233500Z
DTEND:20180424T023500Z
UID:_nV-PS5M9krHrxslm1RAXk2T@stanza.co
SUMMARY:Braves @ BayBears
DESCRIPTION:Braves @ BayBears\n\nFollow on MiLB First Pitch: https://stza.co/+v$PZ-24\n\nShop: https://stza.co/+v$PZ-3V\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144544Z
LAST-MODIFIED:20180213T144544Z
TRANSP:OPAQUE
END:VEVENT
* Braves @ BayBears
<2018-04-24 Tue 18:35-21:35>
:PROPERTIES:
:ID:       w5LfPJe_mUBamLwd38H4wFTU@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Braves @ BayBears Braves @ BayBears

Follow on MiLB First Pitch  https //stza.co/+v$P_-2G

Shop  https //stza.co/+v$P_-3g

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Braves @ BayBears
END:VALARM
DTSTART:20180424T233500Z
DTEND:20180425T023500Z
UID:w5LfPJe_mUBamLwd38H4wFTU@stanza.co
SUMMARY:Braves @ BayBears
DESCRIPTION:Braves @ BayBears\n\nFollow on MiLB First Pitch: https://stza.co/+v$P_-2G\n\nShop: https://stza.co/+v$P_-3g\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144544Z
LAST-MODIFIED:20180213T144544Z
TRANSP:OPAQUE
END:VEVENT
* Braves @ BayBears
<2018-04-25 Wed 11:05-14:05>
:PROPERTIES:
:ID:       tJgZjuwIX_PJuMqAQDS9WeWP@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Braves @ BayBears Braves @ BayBears

Follow on MiLB First Pitch  https //stza.co/+v$P$-2A

Shop  https //stza.co/+v$P$-n

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Braves @ BayBears
END:VALARM
DTSTART:20180425T160500Z
DTEND:20180425T190500Z
UID:tJgZjuwIX_PJuMqAQDS9WeWP@stanza.co
SUMMARY:Braves @ BayBears
DESCRIPTION:Braves @ BayBears\n\nFollow on MiLB First Pitch: https://stza.co/+v$P$-2A\n\nShop: https://stza.co/+v$P$-n\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144544Z
LAST-MODIFIED:20180213T144544Z
TRANSP:OPAQUE
END:VEVENT
* Braves vs. Generals
<2018-04-26 Thu 19:00-22:00>
:PROPERTIES:
:ID:       vmVcsQi8Gzq12ZCLhPWxUPeP@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Braves vs. Generals Braves vs. Generals

Follow on MiLB First Pitch  https //stza.co/+vLJr-3C

Shop  https //stza.co/+vLJr-10

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Braves vs. Generals
END:VALARM
DTSTART:20180427T000000Z
DTEND:20180427T030000Z
UID:vmVcsQi8Gzq12ZCLhPWxUPeP@stanza.co
SUMMARY:Braves vs. Generals
DESCRIPTION:Braves vs. Generals\n\nFollow on MiLB First Pitch: https://stza.co/+vLJr-3C\n\nShop: https://stza.co/+vLJr-10\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144544Z
LAST-MODIFIED:20180213T144544Z
TRANSP:OPAQUE
END:VEVENT
* Braves vs. Generals
<2018-04-27 Fri 19:00-22:00>
:PROPERTIES:
:ID:       bm4-XUHMIRL7t8ZOpU_Tzw7-@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Braves vs. Generals Braves vs. Generals

Follow on MiLB First Pitch  https //stza.co/+vLJt-w

Shop  https //stza.co/+vLJt-3v

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Braves vs. Generals
END:VALARM
DTSTART:20180428T000000Z
DTEND:20180428T030000Z
UID:bm4-XUHMIRL7t8ZOpU_Tzw7-@stanza.co
SUMMARY:Braves vs. Generals
DESCRIPTION:Braves vs. Generals\n\nFollow on MiLB First Pitch: https://stza.co/+vLJt-w\n\nShop: https://stza.co/+vLJt-3v\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144544Z
LAST-MODIFIED:20180213T144544Z
TRANSP:OPAQUE
END:VEVENT
* Braves vs. Generals
<2018-04-28 Sat 18:00-21:00>
:PROPERTIES:
:ID:       IN5B3HJc1D7nN_-9rZacTK0q@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Braves vs. Generals Braves vs. Generals

Follow on MiLB First Pitch  https //stza.co/+vLJv-1c

Shop  https //stza.co/+vLJv-20

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Braves vs. Generals
END:VALARM
DTSTART:20180428T230000Z
DTEND:20180429T020000Z
UID:IN5B3HJc1D7nN_-9rZacTK0q@stanza.co
SUMMARY:Braves vs. Generals
DESCRIPTION:Braves vs. Generals\n\nFollow on MiLB First Pitch: https://stza.co/+vLJv-1c\n\nShop: https://stza.co/+vLJv-20\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144544Z
LAST-MODIFIED:20180213T144544Z
TRANSP:OPAQUE
END:VEVENT
* Braves vs. Generals
<2018-04-29 Sun 13:00-16:00>
:PROPERTIES:
:ID:       2cC4gmslgpDEpRTVkuTIOQxB@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Braves vs. Generals Braves vs. Generals

Follow on MiLB First Pitch  https //stza.co/+vLJx-3e

Shop  https //stza.co/+vLJx-29

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Braves vs. Generals
END:VALARM
DTSTART:20180429T180000Z
DTEND:20180429T210000Z
UID:2cC4gmslgpDEpRTVkuTIOQxB@stanza.co
SUMMARY:Braves vs. Generals
DESCRIPTION:Braves vs. Generals\n\nFollow on MiLB First Pitch: https://stza.co/+vLJx-3e\n\nShop: https://stza.co/+vLJx-29\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144544Z
LAST-MODIFIED:20180213T144544Z
TRANSP:OPAQUE
END:VEVENT
* Braves vs. Generals
<2018-04-30 Mon 10:35-13:35>
:PROPERTIES:
:ID:       Yzy7qt8tymo1H-BCV63Zpfcb@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Braves vs. Generals Braves vs. Generals

Follow on MiLB First Pitch  https //stza.co/+vLJy-25

Shop  https //stza.co/+vLJy-8

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Braves vs. Generals
END:VALARM
DTSTART:20180430T153500Z
DTEND:20180430T183500Z
UID:Yzy7qt8tymo1H-BCV63Zpfcb@stanza.co
SUMMARY:Braves vs. Generals
DESCRIPTION:Braves vs. Generals\n\nFollow on MiLB First Pitch: https://stza.co/+vLJy-25\n\nShop: https://stza.co/+vLJy-8\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144544Z
LAST-MODIFIED:20180213T144544Z
TRANSP:OPAQUE
END:VEVENT
* Braves @ Blue Wahoos
<2018-05-02 Wed 18:35-21:35>
:PROPERTIES:
:ID:       kAiH8es9S_qd-h-kngs86SEg@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Braves @ Blue Wahoos Braves @ Blue Wahoos

Follow on MiLB First Pitch  https //stza.co/+wx8B-b

Shop  https //stza.co/+wx8B-3r

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Braves @ Blue Wahoos
END:VALARM
DTSTART:20180502T233500Z
DTEND:20180503T023500Z
UID:kAiH8es9S_qd-h-kngs86SEg@stanza.co
SUMMARY:Braves @ Blue Wahoos
DESCRIPTION:Braves @ Blue Wahoos\n\nFollow on MiLB First Pitch: https://stza.co/+wx8B-b\n\nShop: https://stza.co/+wx8B-3r\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144544Z
LAST-MODIFIED:20180213T144544Z
TRANSP:OPAQUE
END:VEVENT
* Braves @ Blue Wahoos
<2018-05-03 Thu 18:35-21:35>
:PROPERTIES:
:ID:       b5aTcVEMALpXHPRIfUnynEeL@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Braves @ Blue Wahoos Braves @ Blue Wahoos

Follow on MiLB First Pitch  https //stza.co/+wx8C-N

Shop  https //stza.co/+wx8C-j

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Braves @ Blue Wahoos
END:VALARM
DTSTART:20180503T233500Z
DTEND:20180504T023500Z
UID:b5aTcVEMALpXHPRIfUnynEeL@stanza.co
SUMMARY:Braves @ Blue Wahoos
DESCRIPTION:Braves @ Blue Wahoos\n\nFollow on MiLB First Pitch: https://stza.co/+wx8C-N\n\nShop: https://stza.co/+wx8C-j\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144544Z
LAST-MODIFIED:20180213T144544Z
TRANSP:OPAQUE
END:VEVENT
* Braves @ Blue Wahoos
<2018-05-04 Fri 18:35-21:35>
:PROPERTIES:
:ID:       sVs9eH0xHXWaNs9J61b4XZVy@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Braves @ Blue Wahoos Braves @ Blue Wahoos

Follow on MiLB First Pitch  https //stza.co/+wx8D-29

Shop  https //stza.co/+wx8D-6

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Braves @ Blue Wahoos
END:VALARM
DTSTART:20180504T233500Z
DTEND:20180505T023500Z
UID:sVs9eH0xHXWaNs9J61b4XZVy@stanza.co
SUMMARY:Braves @ Blue Wahoos
DESCRIPTION:Braves @ Blue Wahoos\n\nFollow on MiLB First Pitch: https://stza.co/+wx8D-29\n\nShop: https://stza.co/+wx8D-6\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144544Z
LAST-MODIFIED:20180213T144544Z
TRANSP:OPAQUE
END:VEVENT
* Braves @ Blue Wahoos
<2018-05-05 Sat 18:05-21:05>
:PROPERTIES:
:ID:       MUWnKq1jfs7EjIniIfH2wNXp@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Braves @ Blue Wahoos Braves @ Blue Wahoos

Follow on MiLB First Pitch  https //stza.co/+wx8E-1G

Shop  https //stza.co/+wx8E-3u

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Braves @ Blue Wahoos
END:VALARM
DTSTART:20180505T230500Z
DTEND:20180506T020500Z
UID:MUWnKq1jfs7EjIniIfH2wNXp@stanza.co
SUMMARY:Braves @ Blue Wahoos
DESCRIPTION:Braves @ Blue Wahoos\n\nFollow on MiLB First Pitch: https://stza.co/+wx8E-1G\n\nShop: https://stza.co/+wx8E-3u\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144544Z
LAST-MODIFIED:20180213T144544Z
TRANSP:OPAQUE
END:VEVENT
* Braves @ Blue Wahoos
<2018-05-06 Sun 13:05-16:05>
:PROPERTIES:
:ID:       2s9JL3ay-pwVcPE0TsZyTBpa@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Braves @ Blue Wahoos Braves @ Blue Wahoos

Follow on MiLB First Pitch  https //stza.co/+wx8F-3E

Shop  https //stza.co/+wx8F-m

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Braves @ Blue Wahoos
END:VALARM
DTSTART:20180506T180500Z
DTEND:20180506T210500Z
UID:2s9JL3ay-pwVcPE0TsZyTBpa@stanza.co
SUMMARY:Braves @ Blue Wahoos
DESCRIPTION:Braves @ Blue Wahoos\n\nFollow on MiLB First Pitch: https://stza.co/+wx8F-3E\n\nShop: https://stza.co/+wx8F-m\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144544Z
LAST-MODIFIED:20180213T144544Z
TRANSP:OPAQUE
END:VEVENT
* Braves vs. BayBears
<2018-05-07 Mon 19:00-22:00>
:PROPERTIES:
:ID:       VQ3SI7H1W8F8aUs3n_KRV6c0@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Braves vs. BayBears Braves vs. BayBears

Follow on MiLB First Pitch  https //stza.co/+vLJA-2J

Shop  https //stza.co/+vLJA-1E

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Braves vs. BayBears
END:VALARM
DTSTART:20180508T000000Z
DTEND:20180508T030000Z
UID:VQ3SI7H1W8F8aUs3n_KRV6c0@stanza.co
SUMMARY:Braves vs. BayBears
DESCRIPTION:Braves vs. BayBears\n\nFollow on MiLB First Pitch: https://stza.co/+vLJA-2J\n\nShop: https://stza.co/+vLJA-1E\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144544Z
LAST-MODIFIED:20180213T144544Z
TRANSP:OPAQUE
END:VEVENT
* Braves vs. BayBears
<2018-05-08 Tue 19:00-22:00>
:PROPERTIES:
:ID:       whf0P2qivb8hJLRioNC1F1zG@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Braves vs. BayBears Braves vs. BayBears

Follow on MiLB First Pitch  https //stza.co/+vLJC-3U

Shop  https //stza.co/+vLJC-2U

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Braves vs. BayBears
END:VALARM
DTSTART:20180509T000000Z
DTEND:20180509T030000Z
UID:whf0P2qivb8hJLRioNC1F1zG@stanza.co
SUMMARY:Braves vs. BayBears
DESCRIPTION:Braves vs. BayBears\n\nFollow on MiLB First Pitch: https://stza.co/+vLJC-3U\n\nShop: https://stza.co/+vLJC-2U\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144544Z
LAST-MODIFIED:20180213T144544Z
TRANSP:OPAQUE
END:VEVENT
* Braves vs. BayBears
<2018-05-09 Wed 10:35-13:35>
:PROPERTIES:
:ID:       DQnbz7hmgvI0e7WlVzqq4dQs@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Braves vs. BayBears Braves vs. BayBears

Follow on MiLB First Pitch  https //stza.co/+vLJF-2Z

Shop  https //stza.co/+vLJF-3T

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Braves vs. BayBears
END:VALARM
DTSTART:20180509T153500Z
DTEND:20180509T183500Z
UID:DQnbz7hmgvI0e7WlVzqq4dQs@stanza.co
SUMMARY:Braves vs. BayBears
DESCRIPTION:Braves vs. BayBears\n\nFollow on MiLB First Pitch: https://stza.co/+vLJF-2Z\n\nShop: https://stza.co/+vLJF-3T\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144544Z
LAST-MODIFIED:20180213T144544Z
TRANSP:OPAQUE
END:VEVENT
* Braves vs. BayBears
<2018-05-10 Thu 19:00-22:00>
:PROPERTIES:
:ID:       FcHBC2BlcqRxCGR-aglePsUg@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Braves vs. BayBears Braves vs. BayBears

Follow on MiLB First Pitch  https //stza.co/+vLJG-3j

Shop  https //stza.co/+vLJG-m

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Braves vs. BayBears
END:VALARM
DTSTART:20180511T000000Z
DTEND:20180511T030000Z
UID:FcHBC2BlcqRxCGR-aglePsUg@stanza.co
SUMMARY:Braves vs. BayBears
DESCRIPTION:Braves vs. BayBears\n\nFollow on MiLB First Pitch: https://stza.co/+vLJG-3j\n\nShop: https://stza.co/+vLJG-m\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144544Z
LAST-MODIFIED:20180213T144544Z
TRANSP:OPAQUE
END:VEVENT
* Braves vs. BayBears
<2018-05-11 Fri 19:00-22:00>
:PROPERTIES:
:ID:       aouPh2mCHTzeFt8VxEdD8uTS@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Braves vs. BayBears Braves vs. BayBears

Follow on MiLB First Pitch  https //stza.co/+vLJJ-3S

Shop  https //stza.co/+vLJJ-3k

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Braves vs. BayBears
END:VALARM
DTSTART:20180512T000000Z
DTEND:20180512T030000Z
UID:aouPh2mCHTzeFt8VxEdD8uTS@stanza.co
SUMMARY:Braves vs. BayBears
DESCRIPTION:Braves vs. BayBears\n\nFollow on MiLB First Pitch: https://stza.co/+vLJJ-3S\n\nShop: https://stza.co/+vLJJ-3k\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144544Z
LAST-MODIFIED:20180213T144544Z
TRANSP:OPAQUE
END:VEVENT
* Braves @ Generals
<2018-05-12 Sat 18:05-21:05>
:PROPERTIES:
:ID:       u8sOwlWYDL0tC2Fsazq7trOu@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Braves @ Generals Braves @ Generals

Follow on MiLB First Pitch  https //stza.co/+wCR7-2e

Shop  https //stza.co/+wCR7-2q

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Braves @ Generals
END:VALARM
DTSTART:20180512T230500Z
DTEND:20180513T020500Z
UID:u8sOwlWYDL0tC2Fsazq7trOu@stanza.co
SUMMARY:Braves @ Generals
DESCRIPTION:Braves @ Generals\n\nFollow on MiLB First Pitch: https://stza.co/+wCR7-2e\n\nShop: https://stza.co/+wCR7-2q\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144544Z
LAST-MODIFIED:20180213T144544Z
TRANSP:OPAQUE
END:VEVENT
* Braves @ Generals
<2018-05-13 Sun 14:05-17:05>
:PROPERTIES:
:ID:       fyT7SJTbVIQGQKP3e_2JTzKZ@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Braves @ Generals Braves @ Generals

Follow on MiLB First Pitch  https //stza.co/+wCR9-k

Shop  https //stza.co/+wCR9-32

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Braves @ Generals
END:VALARM
DTSTART:20180513T190500Z
DTEND:20180513T220500Z
UID:fyT7SJTbVIQGQKP3e_2JTzKZ@stanza.co
SUMMARY:Braves @ Generals
DESCRIPTION:Braves @ Generals\n\nFollow on MiLB First Pitch: https://stza.co/+wCR9-k\n\nShop: https://stza.co/+wCR9-32\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144544Z
LAST-MODIFIED:20180213T144544Z
TRANSP:OPAQUE
END:VEVENT
* Braves @ Generals
<2018-05-14 Mon 18:05-21:05>
:PROPERTIES:
:ID:       AV95nFuPCaWnhmC0TkrUkBDl@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Braves @ Generals Braves @ Generals

Follow on MiLB First Pitch  https //stza.co/+wCRb-1N

Shop  https //stza.co/+wCRb-2I

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Braves @ Generals
END:VALARM
DTSTART:20180514T230500Z
DTEND:20180515T020500Z
UID:AV95nFuPCaWnhmC0TkrUkBDl@stanza.co
SUMMARY:Braves @ Generals
DESCRIPTION:Braves @ Generals\n\nFollow on MiLB First Pitch: https://stza.co/+wCRb-1N\n\nShop: https://stza.co/+wCRb-2I\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144544Z
LAST-MODIFIED:20180213T144544Z
TRANSP:OPAQUE
END:VEVENT
* Braves @ Generals
<2018-05-15 Tue 18:05-21:05>
:PROPERTIES:
:ID:       48JDsmacd69eO6r_7kBTQCmY@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Braves @ Generals Braves @ Generals

Follow on MiLB First Pitch  https //stza.co/+wCRd-3V

Shop  https //stza.co/+wCRd-2W

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Braves @ Generals
END:VALARM
DTSTART:20180515T230500Z
DTEND:20180516T020500Z
UID:48JDsmacd69eO6r_7kBTQCmY@stanza.co
SUMMARY:Braves @ Generals
DESCRIPTION:Braves @ Generals\n\nFollow on MiLB First Pitch: https://stza.co/+wCRd-3V\n\nShop: https://stza.co/+wCRd-2W\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144544Z
LAST-MODIFIED:20180213T144544Z
TRANSP:OPAQUE
END:VEVENT
* Braves @ Generals
<2018-05-16 Wed 12:05-15:05>
:PROPERTIES:
:ID:       pxSAYUirP5ZG6ufGCZ-dd7y0@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Braves @ Generals Braves @ Generals

Follow on MiLB First Pitch  https //stza.co/+wCRe-a

Shop  https //stza.co/+wCRe-24

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Braves @ Generals
END:VALARM
DTSTART:20180516T170500Z
DTEND:20180516T200500Z
UID:pxSAYUirP5ZG6ufGCZ-dd7y0@stanza.co
SUMMARY:Braves @ Generals
DESCRIPTION:Braves @ Generals\n\nFollow on MiLB First Pitch: https://stza.co/+wCRe-a\n\nShop: https://stza.co/+wCRe-24\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144544Z
LAST-MODIFIED:20180213T144544Z
TRANSP:OPAQUE
END:VEVENT
* Braves @ Smokies
<2018-05-17 Thu 10:30-13:30>
:PROPERTIES:
:ID:       qyGa0MjYCkgEYbZNDEANVAZP@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Braves @ Smokies Braves @ Smokies

Follow on MiLB First Pitch  https //stza.co/+xVTB-2Z

Shop  https //stza.co/+xVTB-C

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Braves @ Smokies
END:VALARM
DTSTART:20180517T153000Z
DTEND:20180517T183000Z
UID:qyGa0MjYCkgEYbZNDEANVAZP@stanza.co
SUMMARY:Braves @ Smokies
DESCRIPTION:Braves @ Smokies\n\nFollow on MiLB First Pitch: https://stza.co/+xVTB-2Z\n\nShop: https://stza.co/+xVTB-C\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144544Z
LAST-MODIFIED:20180213T144544Z
TRANSP:OPAQUE
END:VEVENT
* Braves @ Smokies
<2018-05-18 Fri 18:00-21:00>
:PROPERTIES:
:ID:       PxXv-0QS4gC3uF7JjOEUTci-@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Braves @ Smokies Braves @ Smokies

Follow on MiLB First Pitch  https //stza.co/+xVTC-T

Shop  https //stza.co/+xVTC-H

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Braves @ Smokies
END:VALARM
DTSTART:20180518T230000Z
DTEND:20180519T020000Z
UID:PxXv-0QS4gC3uF7JjOEUTci-@stanza.co
SUMMARY:Braves @ Smokies
DESCRIPTION:Braves @ Smokies\n\nFollow on MiLB First Pitch: https://stza.co/+xVTC-T\n\nShop: https://stza.co/+xVTC-H\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144544Z
LAST-MODIFIED:20180213T144544Z
TRANSP:OPAQUE
END:VEVENT
* Braves @ Smokies
<2018-05-19 Sat 18:00-21:00>
:PROPERTIES:
:ID:       _JvGU8g-cVDKISPvjpE4zFk6@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Braves @ Smokies Braves @ Smokies

Follow on MiLB First Pitch  https //stza.co/+xVTD-1d

Shop  https //stza.co/+xVTD-E

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Braves @ Smokies
END:VALARM
DTSTART:20180519T230000Z
DTEND:20180520T020000Z
UID:_JvGU8g-cVDKISPvjpE4zFk6@stanza.co
SUMMARY:Braves @ Smokies
DESCRIPTION:Braves @ Smokies\n\nFollow on MiLB First Pitch: https://stza.co/+xVTD-1d\n\nShop: https://stza.co/+xVTD-E\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144544Z
LAST-MODIFIED:20180213T144544Z
TRANSP:OPAQUE
END:VEVENT
* Braves @ Smokies
<2018-05-20 Sun 13:00-16:00>
:PROPERTIES:
:ID:       fLeFXnts4OsLbj9Jke3SYzU1@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Braves @ Smokies Braves @ Smokies

Follow on MiLB First Pitch  https //stza.co/+xVTE-3a

Shop  https //stza.co/+xVTE-36

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Braves @ Smokies
END:VALARM
DTSTART:20180520T180000Z
DTEND:20180520T210000Z
UID:fLeFXnts4OsLbj9Jke3SYzU1@stanza.co
SUMMARY:Braves @ Smokies
DESCRIPTION:Braves @ Smokies\n\nFollow on MiLB First Pitch: https://stza.co/+xVTE-3a\n\nShop: https://stza.co/+xVTE-36\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144544Z
LAST-MODIFIED:20180213T144544Z
TRANSP:OPAQUE
END:VEVENT
* Braves @ Smokies
<2018-05-21 Mon 11:00-14:00>
:PROPERTIES:
:ID:       zc1k1mZBsMRMUVxgGITGHOZc@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Braves @ Smokies Braves @ Smokies

Follow on MiLB First Pitch  https //stza.co/+xVTF-35

Shop  https //stza.co/+xVTF-2X

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Braves @ Smokies
END:VALARM
DTSTART:20180521T160000Z
DTEND:20180521T190000Z
UID:zc1k1mZBsMRMUVxgGITGHOZc@stanza.co
SUMMARY:Braves @ Smokies
DESCRIPTION:Braves @ Smokies\n\nFollow on MiLB First Pitch: https://stza.co/+xVTF-35\n\nShop: https://stza.co/+xVTF-2X\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144544Z
LAST-MODIFIED:20180213T144544Z
TRANSP:OPAQUE
END:VEVENT
* Braves vs. Jumbo Shrimp
<2018-05-23 Wed 19:00-22:00>
:PROPERTIES:
:ID:       yI0_L3W6otRy7SsuvdfsBMN-@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Braves vs. Jumbo Shrimp Braves vs. Jumbo Shrimp

Follow on MiLB First Pitch  https //stza.co/+vLJK-1q

Shop  https //stza.co/+vLJK-x

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Braves vs. Jumbo Shrimp
END:VALARM
DTSTART:20180524T000000Z
DTEND:20180524T030000Z
UID:yI0_L3W6otRy7SsuvdfsBMN-@stanza.co
SUMMARY:Braves vs. Jumbo Shrimp
DESCRIPTION:Braves vs. Jumbo Shrimp\n\nFollow on MiLB First Pitch: https://stza.co/+vLJK-1q\n\nShop: https://stza.co/+vLJK-x\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144544Z
LAST-MODIFIED:20180213T144544Z
TRANSP:OPAQUE
END:VEVENT
* Braves vs. Jumbo Shrimp
<2018-05-24 Thu 19:00-22:00>
:PROPERTIES:
:ID:       TRpTZbdLBwwUFu9sv9Ss2esX@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Braves vs. Jumbo Shrimp Braves vs. Jumbo Shrimp

Follow on MiLB First Pitch  https //stza.co/+vLJN-1n

Shop  https //stza.co/+vLJN-w

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Braves vs. Jumbo Shrimp
END:VALARM
DTSTART:20180525T000000Z
DTEND:20180525T030000Z
UID:TRpTZbdLBwwUFu9sv9Ss2esX@stanza.co
SUMMARY:Braves vs. Jumbo Shrimp
DESCRIPTION:Braves vs. Jumbo Shrimp\n\nFollow on MiLB First Pitch: https://stza.co/+vLJN-1n\n\nShop: https://stza.co/+vLJN-w\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144544Z
LAST-MODIFIED:20180213T144544Z
TRANSP:OPAQUE
END:VEVENT
* Braves vs. Jumbo Shrimp
<2018-05-25 Fri 19:00-22:00>
:PROPERTIES:
:ID:       olmE0Zl6ow00HNhxlFizcbjG@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Braves vs. Jumbo Shrimp Braves vs. Jumbo Shrimp

Follow on MiLB First Pitch  https //stza.co/+vLJP-2

Shop  https //stza.co/+vLJP-2s

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Braves vs. Jumbo Shrimp
END:VALARM
DTSTART:20180526T000000Z
DTEND:20180526T030000Z
UID:olmE0Zl6ow00HNhxlFizcbjG@stanza.co
SUMMARY:Braves vs. Jumbo Shrimp
DESCRIPTION:Braves vs. Jumbo Shrimp\n\nFollow on MiLB First Pitch: https://stza.co/+vLJP-2\n\nShop: https://stza.co/+vLJP-2s\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144544Z
LAST-MODIFIED:20180213T144544Z
TRANSP:OPAQUE
END:VEVENT
* Braves vs. Jumbo Shrimp
<2018-05-26 Sat 18:00-21:00>
:PROPERTIES:
:ID:       cS5oC-6wu_e4k8TcUPIEOMFb@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Braves vs. Jumbo Shrimp Braves vs. Jumbo Shrimp

Follow on MiLB First Pitch  https //stza.co/+vLJR-1q

Shop  https //stza.co/+vLJR-1S

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Braves vs. Jumbo Shrimp
END:VALARM
DTSTART:20180526T230000Z
DTEND:20180527T020000Z
UID:cS5oC-6wu_e4k8TcUPIEOMFb@stanza.co
SUMMARY:Braves vs. Jumbo Shrimp
DESCRIPTION:Braves vs. Jumbo Shrimp\n\nFollow on MiLB First Pitch: https://stza.co/+vLJR-1q\n\nShop: https://stza.co/+vLJR-1S\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144544Z
LAST-MODIFIED:20180213T144544Z
TRANSP:OPAQUE
END:VEVENT
* Braves vs. Jumbo Shrimp
<2018-05-27 Sun 13:00-16:00>
:PROPERTIES:
:ID:       e1w8GoKfEikwFOTiln8sCIDO@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Braves vs. Jumbo Shrimp Braves vs. Jumbo Shrimp

Follow on MiLB First Pitch  https //stza.co/+vLJT-1s

Shop  https //stza.co/+vLJT-1a

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Braves vs. Jumbo Shrimp
END:VALARM
DTSTART:20180527T180000Z
DTEND:20180527T210000Z
UID:e1w8GoKfEikwFOTiln8sCIDO@stanza.co
SUMMARY:Braves vs. Jumbo Shrimp
DESCRIPTION:Braves vs. Jumbo Shrimp\n\nFollow on MiLB First Pitch: https://stza.co/+vLJT-1s\n\nShop: https://stza.co/+vLJT-1a\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144544Z
LAST-MODIFIED:20180213T144544Z
TRANSP:OPAQUE
END:VEVENT
* Braves @ Shuckers
<2018-05-29 Tue 18:35-21:35>
:PROPERTIES:
:ID:       B3kqG9CFqif26gdEJPdoubdr@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Braves @ Shuckers Braves @ Shuckers

Follow on MiLB First Pitch  https //stza.co/+vLIA-2K

Shop  https //stza.co/+vLIA-2c

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Braves @ Shuckers
END:VALARM
DTSTART:20180529T233500Z
DTEND:20180530T023500Z
UID:B3kqG9CFqif26gdEJPdoubdr@stanza.co
SUMMARY:Braves @ Shuckers
DESCRIPTION:Braves @ Shuckers\n\nFollow on MiLB First Pitch: https://stza.co/+vLIA-2K\n\nShop: https://stza.co/+vLIA-2c\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144544Z
LAST-MODIFIED:20180213T144544Z
TRANSP:OPAQUE
END:VEVENT
* Braves @ Shuckers
<2018-05-30 Wed 18:35-21:35>
:PROPERTIES:
:ID:       B4zT4AiCcXR1qlr-S4zEchbE@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Braves @ Shuckers Braves @ Shuckers

Follow on MiLB First Pitch  https //stza.co/+vLIB-1Q

Shop  https //stza.co/+vLIB-b

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Braves @ Shuckers
END:VALARM
DTSTART:20180530T233500Z
DTEND:20180531T023500Z
UID:B4zT4AiCcXR1qlr-S4zEchbE@stanza.co
SUMMARY:Braves @ Shuckers
DESCRIPTION:Braves @ Shuckers\n\nFollow on MiLB First Pitch: https://stza.co/+vLIB-1Q\n\nShop: https://stza.co/+vLIB-b\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144544Z
LAST-MODIFIED:20180213T144544Z
TRANSP:OPAQUE
END:VEVENT
* Braves @ Shuckers
<2018-05-31 Thu 18:35-21:35>
:PROPERTIES:
:ID:       mbTWNctnNAWTpEvWJF3GPdyc@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Braves @ Shuckers Braves @ Shuckers

Follow on MiLB First Pitch  https //stza.co/+vLIC-k

Shop  https //stza.co/+vLIC-2E

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Braves @ Shuckers
END:VALARM
DTSTART:20180531T233500Z
DTEND:20180601T023500Z
UID:mbTWNctnNAWTpEvWJF3GPdyc@stanza.co
SUMMARY:Braves @ Shuckers
DESCRIPTION:Braves @ Shuckers\n\nFollow on MiLB First Pitch: https://stza.co/+vLIC-k\n\nShop: https://stza.co/+vLIC-2E\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144544Z
LAST-MODIFIED:20180213T144544Z
TRANSP:OPAQUE
END:VEVENT
* Braves @ Shuckers
<2018-06-01 Fri 18:35-21:35>
:PROPERTIES:
:ID:       dOqC0BxDJRq6MsTz8mIXADzG@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Braves @ Shuckers Braves @ Shuckers

Follow on MiLB First Pitch  https //stza.co/+vLID-35

Shop  https //stza.co/+vLID-j

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Braves @ Shuckers
END:VALARM
DTSTART:20180601T233500Z
DTEND:20180602T023500Z
UID:dOqC0BxDJRq6MsTz8mIXADzG@stanza.co
SUMMARY:Braves @ Shuckers
DESCRIPTION:Braves @ Shuckers\n\nFollow on MiLB First Pitch: https://stza.co/+vLID-35\n\nShop: https://stza.co/+vLID-j\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144544Z
LAST-MODIFIED:20180213T144544Z
TRANSP:OPAQUE
END:VEVENT
* Braves @ Shuckers
<2018-06-02 Sat 18:35-21:35>
:PROPERTIES:
:ID:       7zLvA3wzWRaE8NjqDcRTpiS8@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Braves @ Shuckers Braves @ Shuckers

Follow on MiLB First Pitch  https //stza.co/+vLIE-3C

Shop  https //stza.co/+vLIE-1F

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Braves @ Shuckers
END:VALARM
DTSTART:20180602T233500Z
DTEND:20180603T023500Z
UID:7zLvA3wzWRaE8NjqDcRTpiS8@stanza.co
SUMMARY:Braves @ Shuckers
DESCRIPTION:Braves @ Shuckers\n\nFollow on MiLB First Pitch: https://stza.co/+vLIE-3C\n\nShop: https://stza.co/+vLIE-1F\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144544Z
LAST-MODIFIED:20180213T144544Z
TRANSP:OPAQUE
END:VEVENT
* Braves vs. Biscuits
<2018-06-03 Sun 17:00-20:00>
:PROPERTIES:
:ID:       42pKZ4Cm6PVRKbFcbyefUmMZ@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Braves vs. Biscuits Braves vs. Biscuits

Follow on MiLB First Pitch  https //stza.co/+vLJU-3R

Shop  https //stza.co/+vLJU-O

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Braves vs. Biscuits
END:VALARM
DTSTART:20180603T220000Z
DTEND:20180604T010000Z
UID:42pKZ4Cm6PVRKbFcbyefUmMZ@stanza.co
SUMMARY:Braves vs. Biscuits
DESCRIPTION:Braves vs. Biscuits\n\nFollow on MiLB First Pitch: https://stza.co/+vLJU-3R\n\nShop: https://stza.co/+vLJU-O\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144544Z
LAST-MODIFIED:20180213T144544Z
TRANSP:OPAQUE
END:VEVENT
* Braves vs. Biscuits
<2018-06-04 Mon 19:00-22:00>
:PROPERTIES:
:ID:       JQcjkiu8Z6QypTGD1zrjSGDi@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Braves vs. Biscuits Braves vs. Biscuits

Follow on MiLB First Pitch  https //stza.co/+vLJW-1u

Shop  https //stza.co/+vLJW-2S

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Braves vs. Biscuits
END:VALARM
DTSTART:20180605T000000Z
DTEND:20180605T030000Z
UID:JQcjkiu8Z6QypTGD1zrjSGDi@stanza.co
SUMMARY:Braves vs. Biscuits
DESCRIPTION:Braves vs. Biscuits\n\nFollow on MiLB First Pitch: https://stza.co/+vLJW-1u\n\nShop: https://stza.co/+vLJW-2S\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144544Z
LAST-MODIFIED:20180213T144544Z
TRANSP:OPAQUE
END:VEVENT
* Braves vs. Biscuits
<2018-06-05 Tue 19:00-22:00>
:PROPERTIES:
:ID:       e_YI_KiYY6vSisGJX1rWqp3W@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Braves vs. Biscuits Braves vs. Biscuits

Follow on MiLB First Pitch  https //stza.co/+vLJZ-1u

Shop  https //stza.co/+vLJZ-d

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Braves vs. Biscuits
END:VALARM
DTSTART:20180606T000000Z
DTEND:20180606T030000Z
UID:e_YI_KiYY6vSisGJX1rWqp3W@stanza.co
SUMMARY:Braves vs. Biscuits
DESCRIPTION:Braves vs. Biscuits\n\nFollow on MiLB First Pitch: https://stza.co/+vLJZ-1u\n\nShop: https://stza.co/+vLJZ-d\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144544Z
LAST-MODIFIED:20180213T144544Z
TRANSP:OPAQUE
END:VEVENT
* Braves vs. Biscuits
<2018-06-06 Wed 19:00-22:00>
:PROPERTIES:
:ID:       yquXT0L275pIgr8faEn-Qd2c@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Braves vs. Biscuits Braves vs. Biscuits

Follow on MiLB First Pitch  https //stza.co/+vLJ$-20

Shop  https //stza.co/+vLJ$-2N

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Braves vs. Biscuits
END:VALARM
DTSTART:20180607T000000Z
DTEND:20180607T030000Z
UID:yquXT0L275pIgr8faEn-Qd2c@stanza.co
SUMMARY:Braves vs. Biscuits
DESCRIPTION:Braves vs. Biscuits\n\nFollow on MiLB First Pitch: https://stza.co/+vLJ$-20\n\nShop: https://stza.co/+vLJ$-2N\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144544Z
LAST-MODIFIED:20180213T144544Z
TRANSP:OPAQUE
END:VEVENT
* Braves vs. Biscuits
<2018-06-07 Thu 19:00-22:00>
:PROPERTIES:
:ID:       1v-GSfhYVLlPF0bR5e9XhyJm@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Braves vs. Biscuits Braves vs. Biscuits

Follow on MiLB First Pitch  https //stza.co/+vLK1-3w

Shop  https //stza.co/+vLK1-2X

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Braves vs. Biscuits
END:VALARM
DTSTART:20180608T000000Z
DTEND:20180608T030000Z
UID:1v-GSfhYVLlPF0bR5e9XhyJm@stanza.co
SUMMARY:Braves vs. Biscuits
DESCRIPTION:Braves vs. Biscuits\n\nFollow on MiLB First Pitch: https://stza.co/+vLK1-3w\n\nShop: https://stza.co/+vLK1-2X\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144544Z
LAST-MODIFIED:20180213T144544Z
TRANSP:OPAQUE
END:VEVENT
* Braves vs. Blue Wahoos
<2018-06-08 Fri 19:00-22:00>
:PROPERTIES:
:ID:       eRh_tC0P8IN5yczd3THj79RI@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Braves vs. Blue Wahoos Braves vs. Blue Wahoos

Follow on MiLB First Pitch  https //stza.co/+vLK3-2B

Shop  https //stza.co/+vLK3-Q

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Braves vs. Blue Wahoos
END:VALARM
DTSTART:20180609T000000Z
DTEND:20180609T030000Z
UID:eRh_tC0P8IN5yczd3THj79RI@stanza.co
SUMMARY:Braves vs. Blue Wahoos
DESCRIPTION:Braves vs. Blue Wahoos\n\nFollow on MiLB First Pitch: https://stza.co/+vLK3-2B\n\nShop: https://stza.co/+vLK3-Q\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144544Z
LAST-MODIFIED:20180213T144544Z
TRANSP:OPAQUE
END:VEVENT
* Braves vs. Blue Wahoos
<2018-06-09 Sat 18:00-21:00>
:PROPERTIES:
:ID:       2CxVebfl9coZtRc_vqlpsCt5@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Braves vs. Blue Wahoos Braves vs. Blue Wahoos

Follow on MiLB First Pitch  https //stza.co/+vLK4-38

Shop  https //stza.co/+vLK4-2A

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Braves vs. Blue Wahoos
END:VALARM
DTSTART:20180609T230000Z
DTEND:20180610T020000Z
UID:2CxVebfl9coZtRc_vqlpsCt5@stanza.co
SUMMARY:Braves vs. Blue Wahoos
DESCRIPTION:Braves vs. Blue Wahoos\n\nFollow on MiLB First Pitch: https://stza.co/+vLK4-38\n\nShop: https://stza.co/+vLK4-2A\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144544Z
LAST-MODIFIED:20180213T144544Z
TRANSP:OPAQUE
END:VEVENT
* Braves vs. Blue Wahoos
<2018-06-10 Sun 17:00-20:00>
:PROPERTIES:
:ID:       ywUNPbOVnAwnp_pyKS87l-X7@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Braves vs. Blue Wahoos Braves vs. Blue Wahoos

Follow on MiLB First Pitch  https //stza.co/+vLK7-n

Shop  https //stza.co/+vLK7-3Q

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Braves vs. Blue Wahoos
END:VALARM
DTSTART:20180610T220000Z
DTEND:20180611T010000Z
UID:ywUNPbOVnAwnp_pyKS87l-X7@stanza.co
SUMMARY:Braves vs. Blue Wahoos
DESCRIPTION:Braves vs. Blue Wahoos\n\nFollow on MiLB First Pitch: https://stza.co/+vLK7-n\n\nShop: https://stza.co/+vLK7-3Q\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144544Z
LAST-MODIFIED:20180213T144544Z
TRANSP:OPAQUE
END:VEVENT
* Braves vs. Blue Wahoos
<2018-06-11 Mon 19:00-22:00>
:PROPERTIES:
:ID:       oySdmHQ8jVqwbQihz3MFFggl@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Braves vs. Blue Wahoos Braves vs. Blue Wahoos

Follow on MiLB First Pitch  https //stza.co/+vLK9-2i

Shop  https //stza.co/+vLK9-1r

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Braves vs. Blue Wahoos
END:VALARM
DTSTART:20180612T000000Z
DTEND:20180612T030000Z
UID:oySdmHQ8jVqwbQihz3MFFggl@stanza.co
SUMMARY:Braves vs. Blue Wahoos
DESCRIPTION:Braves vs. Blue Wahoos\n\nFollow on MiLB First Pitch: https://stza.co/+vLK9-2i\n\nShop: https://stza.co/+vLK9-1r\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144544Z
LAST-MODIFIED:20180213T144544Z
TRANSP:OPAQUE
END:VEVENT
* Braves vs. Blue Wahoos
<2018-06-12 Tue 19:00-22:00>
:PROPERTIES:
:ID:       BYKPk91Q07b_fWgVsIHw84wi@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Braves vs. Blue Wahoos Braves vs. Blue Wahoos

Follow on MiLB First Pitch  https //stza.co/+vLKb-3H

Shop  https //stza.co/+vLKb-31

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Braves vs. Blue Wahoos
END:VALARM
DTSTART:20180613T000000Z
DTEND:20180613T030000Z
UID:BYKPk91Q07b_fWgVsIHw84wi@stanza.co
SUMMARY:Braves vs. Blue Wahoos
DESCRIPTION:Braves vs. Blue Wahoos\n\nFollow on MiLB First Pitch: https://stza.co/+vLKb-3H\n\nShop: https://stza.co/+vLKb-31\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144544Z
LAST-MODIFIED:20180213T144544Z
TRANSP:OPAQUE
END:VEVENT
* Braves @ Shuckers
<2018-06-13 Wed 18:35-21:35>
:PROPERTIES:
:ID:       p36Mb0_atOQRm_acPCB0dQB9@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Braves @ Shuckers Braves @ Shuckers

Follow on MiLB First Pitch  https //stza.co/+vLIF-1F

Shop  https //stza.co/+vLIF-2u

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Braves @ Shuckers
END:VALARM
DTSTART:20180613T233500Z
DTEND:20180614T023500Z
UID:p36Mb0_atOQRm_acPCB0dQB9@stanza.co
SUMMARY:Braves @ Shuckers
DESCRIPTION:Braves @ Shuckers\n\nFollow on MiLB First Pitch: https://stza.co/+vLIF-1F\n\nShop: https://stza.co/+vLIF-2u\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144544Z
LAST-MODIFIED:20180213T144544Z
TRANSP:OPAQUE
END:VEVENT
* Braves @ Shuckers
<2018-06-14 Thu 18:35-21:35>
:PROPERTIES:
:ID:       SsPpJDZD0WKcO2OJjGLf0kAl@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Braves @ Shuckers Braves @ Shuckers

Follow on MiLB First Pitch  https //stza.co/+vLIG-3R

Shop  https //stza.co/+vLIG-3K

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Braves @ Shuckers
END:VALARM
DTSTART:20180614T233500Z
DTEND:20180615T023500Z
UID:SsPpJDZD0WKcO2OJjGLf0kAl@stanza.co
SUMMARY:Braves @ Shuckers
DESCRIPTION:Braves @ Shuckers\n\nFollow on MiLB First Pitch: https://stza.co/+vLIG-3R\n\nShop: https://stza.co/+vLIG-3K\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144544Z
LAST-MODIFIED:20180213T144544Z
TRANSP:OPAQUE
END:VEVENT
* Braves @ Shuckers
<2018-06-15 Fri 18:35-21:35>
:PROPERTIES:
:ID:       OdCq0s1fmmRmNCPlmv97q8Am@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Braves @ Shuckers Braves @ Shuckers

Follow on MiLB First Pitch  https //stza.co/+vLIH-k

Shop  https //stza.co/+vLIH-r

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Braves @ Shuckers
END:VALARM
DTSTART:20180615T233500Z
DTEND:20180616T023500Z
UID:OdCq0s1fmmRmNCPlmv97q8Am@stanza.co
SUMMARY:Braves @ Shuckers
DESCRIPTION:Braves @ Shuckers\n\nFollow on MiLB First Pitch: https://stza.co/+vLIH-k\n\nShop: https://stza.co/+vLIH-r\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144544Z
LAST-MODIFIED:20180213T144544Z
TRANSP:OPAQUE
END:VEVENT
* Braves @ Shuckers
<2018-06-16 Sat 18:35-21:35>
:PROPERTIES:
:ID:       JjZtbBEKWfL1Yj5-zHM3fyUe@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Braves @ Shuckers Braves @ Shuckers

Follow on MiLB First Pitch  https //stza.co/+vLII-1N

Shop  https //stza.co/+vLII-2M

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Braves @ Shuckers
END:VALARM
DTSTART:20180616T233500Z
DTEND:20180617T023500Z
UID:JjZtbBEKWfL1Yj5-zHM3fyUe@stanza.co
SUMMARY:Braves @ Shuckers
DESCRIPTION:Braves @ Shuckers\n\nFollow on MiLB First Pitch: https://stza.co/+vLII-1N\n\nShop: https://stza.co/+vLII-2M\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144544Z
LAST-MODIFIED:20180213T144544Z
TRANSP:OPAQUE
END:VEVENT
* Braves @ Shuckers
<2018-06-17 Sun 16:05-19:05>
:PROPERTIES:
:ID:       FgLsRBwPpuDj6gwDbLJQG0UA@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Braves @ Shuckers Braves @ Shuckers

Follow on MiLB First Pitch  https //stza.co/+vLIJ-1U

Shop  https //stza.co/+vLIJ-32

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Braves @ Shuckers
END:VALARM
DTSTART:20180617T210500Z
DTEND:20180618T000500Z
UID:FgLsRBwPpuDj6gwDbLJQG0UA@stanza.co
SUMMARY:Braves @ Shuckers
DESCRIPTION:Braves @ Shuckers\n\nFollow on MiLB First Pitch: https://stza.co/+vLIJ-1U\n\nShop: https://stza.co/+vLIJ-32\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144544Z
LAST-MODIFIED:20180213T144544Z
TRANSP:OPAQUE
END:VEVENT
* Braves vs. Jumbo Shrimp
<2018-06-21 Thu 19:00-22:00>
:PROPERTIES:
:ID:       0ke-Y-T_DY9WgwTxpyVPZ9J_@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Braves vs. Jumbo Shrimp Braves vs. Jumbo Shrimp

Follow on MiLB First Pitch  https //stza.co/+vLKc-c

Shop  https //stza.co/+vLKc-n

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Braves vs. Jumbo Shrimp
END:VALARM
DTSTART:20180622T000000Z
DTEND:20180622T030000Z
UID:0ke-Y-T_DY9WgwTxpyVPZ9J_@stanza.co
SUMMARY:Braves vs. Jumbo Shrimp
DESCRIPTION:Braves vs. Jumbo Shrimp\n\nFollow on MiLB First Pitch: https://stza.co/+vLKc-c\n\nShop: https://stza.co/+vLKc-n\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144544Z
LAST-MODIFIED:20180213T144544Z
TRANSP:OPAQUE
END:VEVENT
* Braves vs. Jumbo Shrimp
<2018-06-22 Fri 19:00-22:00>
:PROPERTIES:
:ID:       YTtLxTRn04ymEZ5FxgudD4vM@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Braves vs. Jumbo Shrimp Braves vs. Jumbo Shrimp

Follow on MiLB First Pitch  https //stza.co/+vLKf-3O

Shop  https //stza.co/+vLKf-3u

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Braves vs. Jumbo Shrimp
END:VALARM
DTSTART:20180623T000000Z
DTEND:20180623T030000Z
UID:YTtLxTRn04ymEZ5FxgudD4vM@stanza.co
SUMMARY:Braves vs. Jumbo Shrimp
DESCRIPTION:Braves vs. Jumbo Shrimp\n\nFollow on MiLB First Pitch: https://stza.co/+vLKf-3O\n\nShop: https://stza.co/+vLKf-3u\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144544Z
LAST-MODIFIED:20180213T144544Z
TRANSP:OPAQUE
END:VEVENT
* Braves vs. Jumbo Shrimp
<2018-06-23 Sat 18:00-21:00>
:PROPERTIES:
:ID:       Q6i9JmmVWkuV6ap0As3BKxeQ@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Braves vs. Jumbo Shrimp Braves vs. Jumbo Shrimp

Follow on MiLB First Pitch  https //stza.co/+vLKh-1Q

Shop  https //stza.co/+vLKh-2I

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Braves vs. Jumbo Shrimp
END:VALARM
DTSTART:20180623T230000Z
DTEND:20180624T020000Z
UID:Q6i9JmmVWkuV6ap0As3BKxeQ@stanza.co
SUMMARY:Braves vs. Jumbo Shrimp
DESCRIPTION:Braves vs. Jumbo Shrimp\n\nFollow on MiLB First Pitch: https://stza.co/+vLKh-1Q\n\nShop: https://stza.co/+vLKh-2I\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144544Z
LAST-MODIFIED:20180213T144544Z
TRANSP:OPAQUE
END:VEVENT
* Braves vs. Jumbo Shrimp
<2018-06-24 Sun 17:00-20:00>
:PROPERTIES:
:ID:       hDbuBGsKaloLDwvFHQJd2gIL@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Braves vs. Jumbo Shrimp Braves vs. Jumbo Shrimp

Follow on MiLB First Pitch  https //stza.co/+vLKj-2V

Shop  https //stza.co/+vLKj-38

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Braves vs. Jumbo Shrimp
END:VALARM
DTSTART:20180624T220000Z
DTEND:20180625T010000Z
UID:hDbuBGsKaloLDwvFHQJd2gIL@stanza.co
SUMMARY:Braves vs. Jumbo Shrimp
DESCRIPTION:Braves vs. Jumbo Shrimp\n\nFollow on MiLB First Pitch: https://stza.co/+vLKj-2V\n\nShop: https://stza.co/+vLKj-38\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144544Z
LAST-MODIFIED:20180213T144544Z
TRANSP:OPAQUE
END:VEVENT
* Braves vs. Jumbo Shrimp
<2018-06-25 Mon 19:00-22:00>
:PROPERTIES:
:ID:       4Af1xcHib4Yl-lEebRc9YToJ@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Braves vs. Jumbo Shrimp Braves vs. Jumbo Shrimp

Follow on MiLB First Pitch  https //stza.co/+vLKl-b

Shop  https //stza.co/+vLKl-2j

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Braves vs. Jumbo Shrimp
END:VALARM
DTSTART:20180626T000000Z
DTEND:20180626T030000Z
UID:4Af1xcHib4Yl-lEebRc9YToJ@stanza.co
SUMMARY:Braves vs. Jumbo Shrimp
DESCRIPTION:Braves vs. Jumbo Shrimp\n\nFollow on MiLB First Pitch: https://stza.co/+vLKl-b\n\nShop: https://stza.co/+vLKl-2j\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144544Z
LAST-MODIFIED:20180213T144544Z
TRANSP:OPAQUE
END:VEVENT
* Braves vs. Jumbo Shrimp
<2018-06-26 Tue 19:00-22:00>
:PROPERTIES:
:ID:       0MVxFAOpkxiKjteqT0gckvkz@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Braves vs. Jumbo Shrimp Braves vs. Jumbo Shrimp

Follow on MiLB First Pitch  https //stza.co/+vLKn-2S

Shop  https //stza.co/+vLKn-3z

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Braves vs. Jumbo Shrimp
END:VALARM
DTSTART:20180627T000000Z
DTEND:20180627T030000Z
UID:0MVxFAOpkxiKjteqT0gckvkz@stanza.co
SUMMARY:Braves vs. Jumbo Shrimp
DESCRIPTION:Braves vs. Jumbo Shrimp\n\nFollow on MiLB First Pitch: https://stza.co/+vLKn-2S\n\nShop: https://stza.co/+vLKn-3z\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144544Z
LAST-MODIFIED:20180213T144544Z
TRANSP:OPAQUE
END:VEVENT
* Braves @ Blue Wahoos
<2018-06-28 Thu 18:35-21:35>
:PROPERTIES:
:ID:       GH_qe42FO0yf01xSesnpKZ6H@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Braves @ Blue Wahoos Braves @ Blue Wahoos

Follow on MiLB First Pitch  https //stza.co/+wx8G-1P

Shop  https //stza.co/+wx8G-2a

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Braves @ Blue Wahoos
END:VALARM
DTSTART:20180628T233500Z
DTEND:20180629T023500Z
UID:GH_qe42FO0yf01xSesnpKZ6H@stanza.co
SUMMARY:Braves @ Blue Wahoos
DESCRIPTION:Braves @ Blue Wahoos\n\nFollow on MiLB First Pitch: https://stza.co/+wx8G-1P\n\nShop: https://stza.co/+wx8G-2a\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144544Z
LAST-MODIFIED:20180213T144544Z
TRANSP:OPAQUE
END:VEVENT
* Braves @ Blue Wahoos
<2018-06-29 Fri 18:35-21:35>
:PROPERTIES:
:ID:       vYy6l655ngl4Gh7CgfCymvO6@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Braves @ Blue Wahoos Braves @ Blue Wahoos

Follow on MiLB First Pitch  https //stza.co/+wx8H-w

Shop  https //stza.co/+wx8H-3t

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Braves @ Blue Wahoos
END:VALARM
DTSTART:20180629T233500Z
DTEND:20180630T023500Z
UID:vYy6l655ngl4Gh7CgfCymvO6@stanza.co
SUMMARY:Braves @ Blue Wahoos
DESCRIPTION:Braves @ Blue Wahoos\n\nFollow on MiLB First Pitch: https://stza.co/+wx8H-w\n\nShop: https://stza.co/+wx8H-3t\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144544Z
LAST-MODIFIED:20180213T144544Z
TRANSP:OPAQUE
END:VEVENT
* Braves @ Blue Wahoos
<2018-06-30 Sat 18:05-21:05>
:PROPERTIES:
:ID:       YpgEE3LhGLcktd16P5dvWMqB@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Braves @ Blue Wahoos Braves @ Blue Wahoos

Follow on MiLB First Pitch  https //stza.co/+wx8I-

Shop  https //stza.co/+wx8I-2e

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Braves @ Blue Wahoos
END:VALARM
DTSTART:20180630T230500Z
DTEND:20180701T020500Z
UID:YpgEE3LhGLcktd16P5dvWMqB@stanza.co
SUMMARY:Braves @ Blue Wahoos
DESCRIPTION:Braves @ Blue Wahoos\n\nFollow on MiLB First Pitch: https://stza.co/+wx8I-\n\nShop: https://stza.co/+wx8I-2e\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144544Z
LAST-MODIFIED:20180213T144544Z
TRANSP:OPAQUE
END:VEVENT
* Braves @ Blue Wahoos
<2018-07-01 Sun 17:05-20:05>
:PROPERTIES:
:ID:       BvGf5xJGIMNHXgNkIUc3Sk_2@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Braves @ Blue Wahoos Braves @ Blue Wahoos

Follow on MiLB First Pitch  https //stza.co/+wx8J-c

Shop  https //stza.co/+wx8J-2G

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Braves @ Blue Wahoos
END:VALARM
DTSTART:20180701T220500Z
DTEND:20180702T010500Z
UID:BvGf5xJGIMNHXgNkIUc3Sk_2@stanza.co
SUMMARY:Braves @ Blue Wahoos
DESCRIPTION:Braves @ Blue Wahoos\n\nFollow on MiLB First Pitch: https://stza.co/+wx8J-c\n\nShop: https://stza.co/+wx8J-2G\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144544Z
LAST-MODIFIED:20180213T144544Z
TRANSP:OPAQUE
END:VEVENT
* Braves @ Blue Wahoos
<2018-07-02 Mon 18:35-21:35>
:PROPERTIES:
:ID:       lXdHjrZbMuxoJRXR_nxZ7MlA@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Braves @ Blue Wahoos Braves @ Blue Wahoos

Follow on MiLB First Pitch  https //stza.co/+wx8K-1o

Shop  https //stza.co/+wx8K-2E

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Braves @ Blue Wahoos
END:VALARM
DTSTART:20180702T233500Z
DTEND:20180703T023500Z
UID:lXdHjrZbMuxoJRXR_nxZ7MlA@stanza.co
SUMMARY:Braves @ Blue Wahoos
DESCRIPTION:Braves @ Blue Wahoos\n\nFollow on MiLB First Pitch: https://stza.co/+wx8K-1o\n\nShop: https://stza.co/+wx8K-2E\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144544Z
LAST-MODIFIED:20180213T144544Z
TRANSP:OPAQUE
END:VEVENT
* Braves @ Blue Wahoos
<2018-07-03 Tue 18:35-21:35>
:PROPERTIES:
:ID:       dCaLAofHk1mE92hFGO6sSM4C@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Braves @ Blue Wahoos Braves @ Blue Wahoos

Follow on MiLB First Pitch  https //stza.co/+wx8L-N

Shop  https //stza.co/+wx8L-2Y

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Braves @ Blue Wahoos
END:VALARM
DTSTART:20180703T233500Z
DTEND:20180704T023500Z
UID:dCaLAofHk1mE92hFGO6sSM4C@stanza.co
SUMMARY:Braves @ Blue Wahoos
DESCRIPTION:Braves @ Blue Wahoos\n\nFollow on MiLB First Pitch: https://stza.co/+wx8L-N\n\nShop: https://stza.co/+wx8L-2Y\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144544Z
LAST-MODIFIED:20180213T144544Z
TRANSP:OPAQUE
END:VEVENT
* Braves vs. Shuckers
<2018-07-04 Wed 19:00-22:00>
:PROPERTIES:
:ID:       T1YwhsOXOPMcNKPyZPvAN2CM@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Braves vs. Shuckers Braves vs. Shuckers

Follow on MiLB First Pitch  https //stza.co/+vLKo-i

Shop  https //stza.co/+vLKo-3H

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Braves vs. Shuckers
END:VALARM
DTSTART:20180705T000000Z
DTEND:20180705T030000Z
UID:T1YwhsOXOPMcNKPyZPvAN2CM@stanza.co
SUMMARY:Braves vs. Shuckers
DESCRIPTION:Braves vs. Shuckers\n\nFollow on MiLB First Pitch: https://stza.co/+vLKo-i\n\nShop: https://stza.co/+vLKo-3H\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144544Z
LAST-MODIFIED:20180213T144544Z
TRANSP:OPAQUE
END:VEVENT
* Braves vs. Shuckers
<2018-07-05 Thu 19:00-22:00>
:PROPERTIES:
:ID:       QKF_q-crQE7Jmi_icpo_p6Bh@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Braves vs. Shuckers Braves vs. Shuckers

Follow on MiLB First Pitch  https //stza.co/+vLKq-1g

Shop  https //stza.co/+vLKq-2D

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Braves vs. Shuckers
END:VALARM
DTSTART:20180706T000000Z
DTEND:20180706T030000Z
UID:QKF_q-crQE7Jmi_icpo_p6Bh@stanza.co
SUMMARY:Braves vs. Shuckers
DESCRIPTION:Braves vs. Shuckers\n\nFollow on MiLB First Pitch: https://stza.co/+vLKq-1g\n\nShop: https://stza.co/+vLKq-2D\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144544Z
LAST-MODIFIED:20180213T144544Z
TRANSP:OPAQUE
END:VEVENT
* Braves vs. Shuckers
<2018-07-06 Fri 19:00-22:00>
:PROPERTIES:
:ID:       LpFr31FhO_3VID90hh3g9V09@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Braves vs. Shuckers Braves vs. Shuckers

Follow on MiLB First Pitch  https //stza.co/+vLKs-J

Shop  https //stza.co/+vLKs-u

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Braves vs. Shuckers
END:VALARM
DTSTART:20180707T000000Z
DTEND:20180707T030000Z
UID:LpFr31FhO_3VID90hh3g9V09@stanza.co
SUMMARY:Braves vs. Shuckers
DESCRIPTION:Braves vs. Shuckers\n\nFollow on MiLB First Pitch: https://stza.co/+vLKs-J\n\nShop: https://stza.co/+vLKs-u\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144544Z
LAST-MODIFIED:20180213T144544Z
TRANSP:OPAQUE
END:VEVENT
* Braves vs. Shuckers
<2018-07-07 Sat 18:00-21:00>
:PROPERTIES:
:ID:       wVcyP3-J4DuGqwam5PI_FL61@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Braves vs. Shuckers Braves vs. Shuckers

Follow on MiLB First Pitch  https //stza.co/+vLKv-1U

Shop  https //stza.co/+vLKv-23

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Braves vs. Shuckers
END:VALARM
DTSTART:20180707T230000Z
DTEND:20180708T020000Z
UID:wVcyP3-J4DuGqwam5PI_FL61@stanza.co
SUMMARY:Braves vs. Shuckers
DESCRIPTION:Braves vs. Shuckers\n\nFollow on MiLB First Pitch: https://stza.co/+vLKv-1U\n\nShop: https://stza.co/+vLKv-23\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144544Z
LAST-MODIFIED:20180213T144544Z
TRANSP:OPAQUE
END:VEVENT
* Braves @ Barons
<2018-07-08 Sun 18:00-21:00>
:PROPERTIES:
:ID:       BNJcbUO__o2tqRmOhE22G3Qd@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Braves @ Barons Braves @ Barons

Follow on MiLB First Pitch  https //stza.co/+wFXF-H

Shop  https //stza.co/+wFXF-3f

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Braves @ Barons
END:VALARM
DTSTART:20180708T230000Z
DTEND:20180709T020000Z
UID:BNJcbUO__o2tqRmOhE22G3Qd@stanza.co
SUMMARY:Braves @ Barons
DESCRIPTION:Braves @ Barons\n\nFollow on MiLB First Pitch: https://stza.co/+wFXF-H\n\nShop: https://stza.co/+wFXF-3f\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144544Z
LAST-MODIFIED:20180213T144544Z
TRANSP:OPAQUE
END:VEVENT
* Braves @ Barons
<2018-07-09 Mon 19:05-22:05>
:PROPERTIES:
:ID:       3NGLtmNH7f87sO-N0cdgJOkE@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Braves @ Barons Braves @ Barons

Follow on MiLB First Pitch  https //stza.co/+wFXG-T

Shop  https //stza.co/+wFXG-M

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Braves @ Barons
END:VALARM
DTSTART:20180710T000500Z
DTEND:20180710T030500Z
UID:3NGLtmNH7f87sO-N0cdgJOkE@stanza.co
SUMMARY:Braves @ Barons
DESCRIPTION:Braves @ Barons\n\nFollow on MiLB First Pitch: https://stza.co/+wFXG-T\n\nShop: https://stza.co/+wFXG-M\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144544Z
LAST-MODIFIED:20180213T144544Z
TRANSP:OPAQUE
END:VEVENT
* Braves @ Barons
<2018-07-10 Tue 19:05-22:05>
:PROPERTIES:
:ID:       B3Vib9LAc69M3b9Alx835fEz@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Braves @ Barons Braves @ Barons

Follow on MiLB First Pitch  https //stza.co/+wFXH-1P

Shop  https //stza.co/+wFXH-15

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Braves @ Barons
END:VALARM
DTSTART:20180711T000500Z
DTEND:20180711T030500Z
UID:B3Vib9LAc69M3b9Alx835fEz@stanza.co
SUMMARY:Braves @ Barons
DESCRIPTION:Braves @ Barons\n\nFollow on MiLB First Pitch: https://stza.co/+wFXH-1P\n\nShop: https://stza.co/+wFXH-15\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144544Z
LAST-MODIFIED:20180213T144544Z
TRANSP:OPAQUE
END:VEVENT
* Braves @ Barons
<2018-07-11 Wed 19:05-22:05>
:PROPERTIES:
:ID:       eLyKOldvVhHWgPs1qp0IwAFT@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Braves @ Barons Braves @ Barons

Follow on MiLB First Pitch  https //stza.co/+wFXI-32

Shop  https //stza.co/+wFXI-j

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Braves @ Barons
END:VALARM
DTSTART:20180712T000500Z
DTEND:20180712T030500Z
UID:eLyKOldvVhHWgPs1qp0IwAFT@stanza.co
SUMMARY:Braves @ Barons
DESCRIPTION:Braves @ Barons\n\nFollow on MiLB First Pitch: https://stza.co/+wFXI-32\n\nShop: https://stza.co/+wFXI-j\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144544Z
LAST-MODIFIED:20180213T144544Z
TRANSP:OPAQUE
END:VEVENT
* Braves vs. Blue Wahoos
<2018-07-12 Thu 19:00-22:00>
:PROPERTIES:
:ID:       LBrVxGCqngDDX-T8zjsTobIq@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Braves vs. Blue Wahoos Braves vs. Blue Wahoos

Follow on MiLB First Pitch  https //stza.co/+vLKx-3r

Shop  https //stza.co/+vLKx-H

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Braves vs. Blue Wahoos
END:VALARM
DTSTART:20180713T000000Z
DTEND:20180713T030000Z
UID:LBrVxGCqngDDX-T8zjsTobIq@stanza.co
SUMMARY:Braves vs. Blue Wahoos
DESCRIPTION:Braves vs. Blue Wahoos\n\nFollow on MiLB First Pitch: https://stza.co/+vLKx-3r\n\nShop: https://stza.co/+vLKx-H\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144544Z
LAST-MODIFIED:20180213T144544Z
TRANSP:OPAQUE
END:VEVENT
* Braves vs. Blue Wahoos
<2018-07-13 Fri 19:00-22:00>
:PROPERTIES:
:ID:       o_iFA4v6cXEFcaPxVQBcN9qt@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Braves vs. Blue Wahoos Braves vs. Blue Wahoos

Follow on MiLB First Pitch  https //stza.co/+vLKy-34

Shop  https //stza.co/+vLKy-3v

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Braves vs. Blue Wahoos
END:VALARM
DTSTART:20180714T000000Z
DTEND:20180714T030000Z
UID:o_iFA4v6cXEFcaPxVQBcN9qt@stanza.co
SUMMARY:Braves vs. Blue Wahoos
DESCRIPTION:Braves vs. Blue Wahoos\n\nFollow on MiLB First Pitch: https://stza.co/+vLKy-34\n\nShop: https://stza.co/+vLKy-3v\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144544Z
LAST-MODIFIED:20180213T144544Z
TRANSP:OPAQUE
END:VEVENT
* Braves vs. Blue Wahoos
<2018-07-14 Sat 18:00-21:00>
:PROPERTIES:
:ID:       E6cQj0wKQwuBOEGrJoeX46kI@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Braves vs. Blue Wahoos Braves vs. Blue Wahoos

Follow on MiLB First Pitch  https //stza.co/+vLKB-3t

Shop  https //stza.co/+vLKB-2W

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Braves vs. Blue Wahoos
END:VALARM
DTSTART:20180714T230000Z
DTEND:20180715T020000Z
UID:E6cQj0wKQwuBOEGrJoeX46kI@stanza.co
SUMMARY:Braves vs. Blue Wahoos
DESCRIPTION:Braves vs. Blue Wahoos\n\nFollow on MiLB First Pitch: https://stza.co/+vLKB-3t\n\nShop: https://stza.co/+vLKB-2W\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144544Z
LAST-MODIFIED:20180213T144544Z
TRANSP:OPAQUE
END:VEVENT
* Braves vs. Blue Wahoos
<2018-07-15 Sun 17:00-20:00>
:PROPERTIES:
:ID:       Cg2WDviuHfBPm7gKkDJWnPF3@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Braves vs. Blue Wahoos Braves vs. Blue Wahoos

Follow on MiLB First Pitch  https //stza.co/+vLKD-w

Shop  https //stza.co/+vLKD-1N

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Braves vs. Blue Wahoos
END:VALARM
DTSTART:20180715T220000Z
DTEND:20180716T010000Z
UID:Cg2WDviuHfBPm7gKkDJWnPF3@stanza.co
SUMMARY:Braves vs. Blue Wahoos
DESCRIPTION:Braves vs. Blue Wahoos\n\nFollow on MiLB First Pitch: https://stza.co/+vLKD-w\n\nShop: https://stza.co/+vLKD-1N\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144544Z
LAST-MODIFIED:20180213T144544Z
TRANSP:OPAQUE
END:VEVENT
* Braves vs. Blue Wahoos
<2018-07-16 Mon 19:00-22:00>
:PROPERTIES:
:ID:       Gr4uxCsENEUiJHPICWA1RWcc@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Braves vs. Blue Wahoos Braves vs. Blue Wahoos

Follow on MiLB First Pitch  https //stza.co/+vLKF-2p

Shop  https //stza.co/+vLKF-1p

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Braves vs. Blue Wahoos
END:VALARM
DTSTART:20180717T000000Z
DTEND:20180717T030000Z
UID:Gr4uxCsENEUiJHPICWA1RWcc@stanza.co
SUMMARY:Braves vs. Blue Wahoos
DESCRIPTION:Braves vs. Blue Wahoos\n\nFollow on MiLB First Pitch: https://stza.co/+vLKF-2p\n\nShop: https://stza.co/+vLKF-1p\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144544Z
LAST-MODIFIED:20180213T144544Z
TRANSP:OPAQUE
END:VEVENT
* Braves @ Biscuits
<2018-07-18 Wed 18:35-21:35>
:PROPERTIES:
:ID:       NWn4umesxCCf8WwUm75M6SDV@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Braves @ Biscuits Braves @ Biscuits

Follow on MiLB First Pitch  https //stza.co/+vLLk-2f

Shop  https //stza.co/+vLLk-1D

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Braves @ Biscuits
END:VALARM
DTSTART:20180718T233500Z
DTEND:20180719T023500Z
UID:NWn4umesxCCf8WwUm75M6SDV@stanza.co
SUMMARY:Braves @ Biscuits
DESCRIPTION:Braves @ Biscuits\n\nFollow on MiLB First Pitch: https://stza.co/+vLLk-2f\n\nShop: https://stza.co/+vLLk-1D\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144544Z
LAST-MODIFIED:20180213T144544Z
TRANSP:OPAQUE
END:VEVENT
* Braves @ Biscuits
<2018-07-19 Thu 18:35-21:35>
:PROPERTIES:
:ID:       CMKGAfifv9LITAbithkYolqf@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Braves @ Biscuits Braves @ Biscuits

Follow on MiLB First Pitch  https //stza.co/+vLLl-1S

Shop  https //stza.co/+vLLl-2x

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Braves @ Biscuits
END:VALARM
DTSTART:20180719T233500Z
DTEND:20180720T023500Z
UID:CMKGAfifv9LITAbithkYolqf@stanza.co
SUMMARY:Braves @ Biscuits
DESCRIPTION:Braves @ Biscuits\n\nFollow on MiLB First Pitch: https://stza.co/+vLLl-1S\n\nShop: https://stza.co/+vLLl-2x\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144544Z
LAST-MODIFIED:20180213T144544Z
TRANSP:OPAQUE
END:VEVENT
* Braves @ Biscuits
<2018-07-20 Fri 18:35-21:35>
:PROPERTIES:
:ID:       llqF4egDfhyomG8Z6vZcSyO_@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Braves @ Biscuits Braves @ Biscuits

Follow on MiLB First Pitch  https //stza.co/+vLLm-3s

Shop  https //stza.co/+vLLm-1v

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Braves @ Biscuits
END:VALARM
DTSTART:20180720T233500Z
DTEND:20180721T023500Z
UID:llqF4egDfhyomG8Z6vZcSyO_@stanza.co
SUMMARY:Braves @ Biscuits
DESCRIPTION:Braves @ Biscuits\n\nFollow on MiLB First Pitch: https://stza.co/+vLLm-3s\n\nShop: https://stza.co/+vLLm-1v\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144544Z
LAST-MODIFIED:20180213T144544Z
TRANSP:OPAQUE
END:VEVENT
* Braves @ Biscuits
<2018-07-21 Sat 18:05-21:05>
:PROPERTIES:
:ID:       YDBXttJaJI0xjo7L-ldlODZC@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Braves @ Biscuits Braves @ Biscuits

Follow on MiLB First Pitch  https //stza.co/+vLLn-2e

Shop  https //stza.co/+vLLn-22

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Braves @ Biscuits
END:VALARM
DTSTART:20180721T230500Z
DTEND:20180722T020500Z
UID:YDBXttJaJI0xjo7L-ldlODZC@stanza.co
SUMMARY:Braves @ Biscuits
DESCRIPTION:Braves @ Biscuits\n\nFollow on MiLB First Pitch: https://stza.co/+vLLn-2e\n\nShop: https://stza.co/+vLLn-22\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144544Z
LAST-MODIFIED:20180213T144544Z
TRANSP:OPAQUE
END:VEVENT
* Braves @ Biscuits
<2018-07-22 Sun 17:05-20:05>
:PROPERTIES:
:ID:       RcTk7Z_nCiOBBu5PC7kukNv8@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Braves @ Biscuits Braves @ Biscuits

Follow on MiLB First Pitch  https //stza.co/+vLLo-2f

Shop  https //stza.co/+vLLo-3F

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Braves @ Biscuits
END:VALARM
DTSTART:20180722T220500Z
DTEND:20180723T010500Z
UID:RcTk7Z_nCiOBBu5PC7kukNv8@stanza.co
SUMMARY:Braves @ Biscuits
DESCRIPTION:Braves @ Biscuits\n\nFollow on MiLB First Pitch: https://stza.co/+vLLo-2f\n\nShop: https://stza.co/+vLLo-3F\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144544Z
LAST-MODIFIED:20180213T144544Z
TRANSP:OPAQUE
END:VEVENT
* Braves vs. BayBears
<2018-07-23 Mon 19:00-22:00>
:PROPERTIES:
:ID:       6fFFAg32h0ejxgJPDERACJu-@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Braves vs. BayBears Braves vs. BayBears

Follow on MiLB First Pitch  https //stza.co/+vLKH-1z

Shop  https //stza.co/+vLKH-2h

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Braves vs. BayBears
END:VALARM
DTSTART:20180724T000000Z
DTEND:20180724T030000Z
UID:6fFFAg32h0ejxgJPDERACJu-@stanza.co
SUMMARY:Braves vs. BayBears
DESCRIPTION:Braves vs. BayBears\n\nFollow on MiLB First Pitch: https://stza.co/+vLKH-1z\n\nShop: https://stza.co/+vLKH-2h\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144544Z
LAST-MODIFIED:20180213T144544Z
TRANSP:OPAQUE
END:VEVENT
* Braves vs. BayBears
<2018-07-24 Tue 19:00-22:00>
:PROPERTIES:
:ID:       10xS8Sdbb8bjkidWlJQfF4K-@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Braves vs. BayBears Braves vs. BayBears

Follow on MiLB First Pitch  https //stza.co/+vLKJ-37

Shop  https //stza.co/+vLKJ-2t

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Braves vs. BayBears
END:VALARM
DTSTART:20180725T000000Z
DTEND:20180725T030000Z
UID:10xS8Sdbb8bjkidWlJQfF4K-@stanza.co
SUMMARY:Braves vs. BayBears
DESCRIPTION:Braves vs. BayBears\n\nFollow on MiLB First Pitch: https://stza.co/+vLKJ-37\n\nShop: https://stza.co/+vLKJ-2t\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144544Z
LAST-MODIFIED:20180213T144544Z
TRANSP:OPAQUE
END:VEVENT
* Braves vs. BayBears
<2018-07-25 Wed 19:00-22:00>
:PROPERTIES:
:ID:       exW01YQR6KI6mBM8rGni-SEz@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Braves vs. BayBears Braves vs. BayBears

Follow on MiLB First Pitch  https //stza.co/+vLKL-y

Shop  https //stza.co/+vLKL-2D

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Braves vs. BayBears
END:VALARM
DTSTART:20180726T000000Z
DTEND:20180726T030000Z
UID:exW01YQR6KI6mBM8rGni-SEz@stanza.co
SUMMARY:Braves vs. BayBears
DESCRIPTION:Braves vs. BayBears\n\nFollow on MiLB First Pitch: https://stza.co/+vLKL-y\n\nShop: https://stza.co/+vLKL-2D\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144544Z
LAST-MODIFIED:20180213T144544Z
TRANSP:OPAQUE
END:VEVENT
* Braves vs. BayBears
<2018-07-26 Thu 19:00-22:00>
:PROPERTIES:
:ID:       -vhW0NNQq58J9WJm8TaKVqq8@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Braves vs. BayBears Braves vs. BayBears

Follow on MiLB First Pitch  https //stza.co/+vLKN-3H

Shop  https //stza.co/+vLKN-3k

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Braves vs. BayBears
END:VALARM
DTSTART:20180727T000000Z
DTEND:20180727T030000Z
UID:-vhW0NNQq58J9WJm8TaKVqq8@stanza.co
SUMMARY:Braves vs. BayBears
DESCRIPTION:Braves vs. BayBears\n\nFollow on MiLB First Pitch: https://stza.co/+vLKN-3H\n\nShop: https://stza.co/+vLKN-3k\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144544Z
LAST-MODIFIED:20180213T144544Z
TRANSP:OPAQUE
END:VEVENT
* Braves vs. BayBears
<2018-07-27 Fri 19:00-22:00>
:PROPERTIES:
:ID:       6uAIhgPGAFCe_OFHheDv5Wm-@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Braves vs. BayBears Braves vs. BayBears

Follow on MiLB First Pitch  https //stza.co/+vLKO-3j

Shop  https //stza.co/+vLKO-2i

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Braves vs. BayBears
END:VALARM
DTSTART:20180728T000000Z
DTEND:20180728T030000Z
UID:6uAIhgPGAFCe_OFHheDv5Wm-@stanza.co
SUMMARY:Braves vs. BayBears
DESCRIPTION:Braves vs. BayBears\n\nFollow on MiLB First Pitch: https://stza.co/+vLKO-3j\n\nShop: https://stza.co/+vLKO-2i\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144544Z
LAST-MODIFIED:20180213T144544Z
TRANSP:OPAQUE
END:VEVENT
* Braves vs. Barons
<2018-07-28 Sat 18:00-21:00>
:PROPERTIES:
:ID:       2rExyDSbLfkA9RdAHqYmRkPx@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Braves vs. Barons Braves vs. Barons

Follow on MiLB First Pitch  https //stza.co/+vLKQ-

Shop  https //stza.co/+vLKQ-2i

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Braves vs. Barons
END:VALARM
DTSTART:20180728T230000Z
DTEND:20180729T020000Z
UID:2rExyDSbLfkA9RdAHqYmRkPx@stanza.co
SUMMARY:Braves vs. Barons
DESCRIPTION:Braves vs. Barons\n\nFollow on MiLB First Pitch: https://stza.co/+vLKQ-\n\nShop: https://stza.co/+vLKQ-2i\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144544Z
LAST-MODIFIED:20180213T144544Z
TRANSP:OPAQUE
END:VEVENT
* Braves vs. Barons
<2018-07-29 Sun 17:00-20:00>
:PROPERTIES:
:ID:       ZmBrQvyf09S4m0377GqAlbSM@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Braves vs. Barons Braves vs. Barons

Follow on MiLB First Pitch  https //stza.co/+vLKT-1f

Shop  https //stza.co/+vLKT-1_

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Braves vs. Barons
END:VALARM
DTSTART:20180729T220000Z
DTEND:20180730T010000Z
UID:ZmBrQvyf09S4m0377GqAlbSM@stanza.co
SUMMARY:Braves vs. Barons
DESCRIPTION:Braves vs. Barons\n\nFollow on MiLB First Pitch: https://stza.co/+vLKT-1f\n\nShop: https://stza.co/+vLKT-1_\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144544Z
LAST-MODIFIED:20180213T144544Z
TRANSP:OPAQUE
END:VEVENT
* Braves vs. Barons
<2018-07-30 Mon 19:00-22:00>
:PROPERTIES:
:ID:       -BOuSW8mOBrlX65J85NTGUFM@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Braves vs. Barons Braves vs. Barons

Follow on MiLB First Pitch  https //stza.co/+vLKV-f

Shop  https //stza.co/+vLKV-1V

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Braves vs. Barons
END:VALARM
DTSTART:20180731T000000Z
DTEND:20180731T030000Z
UID:-BOuSW8mOBrlX65J85NTGUFM@stanza.co
SUMMARY:Braves vs. Barons
DESCRIPTION:Braves vs. Barons\n\nFollow on MiLB First Pitch: https://stza.co/+vLKV-f\n\nShop: https://stza.co/+vLKV-1V\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144544Z
LAST-MODIFIED:20180213T144544Z
TRANSP:OPAQUE
END:VEVENT
* Braves vs. Barons
<2018-07-31 Tue 19:00-22:00>
:PROPERTIES:
:ID:       KZ2_jUe7sAgpZlEW36fqJcc6@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Braves vs. Barons Braves vs. Barons

Follow on MiLB First Pitch  https //stza.co/+vLKW-2A

Shop  https //stza.co/+vLKW-p

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Braves vs. Barons
END:VALARM
DTSTART:20180801T000000Z
DTEND:20180801T030000Z
UID:KZ2_jUe7sAgpZlEW36fqJcc6@stanza.co
SUMMARY:Braves vs. Barons
DESCRIPTION:Braves vs. Barons\n\nFollow on MiLB First Pitch: https://stza.co/+vLKW-2A\n\nShop: https://stza.co/+vLKW-p\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144544Z
LAST-MODIFIED:20180213T144544Z
TRANSP:OPAQUE
END:VEVENT
* Braves vs. Barons
<2018-08-01 Wed 19:00-22:00>
:PROPERTIES:
:ID:       zNWiBZToGA8W1y7u_OAPChsq@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Braves vs. Barons Braves vs. Barons

Follow on MiLB First Pitch  https //stza.co/+vdqo-22

Shop  https //stza.co/+vdqo-$

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Braves vs. Barons
END:VALARM
DTSTART:20180802T000000Z
DTEND:20180802T030000Z
UID:zNWiBZToGA8W1y7u_OAPChsq@stanza.co
SUMMARY:Braves vs. Barons
DESCRIPTION:Braves vs. Barons\n\nFollow on MiLB First Pitch: https://stza.co/+vdqo-22\n\nShop: https://stza.co/+vdqo-$\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144544Z
LAST-MODIFIED:20180213T144544Z
TRANSP:OPAQUE
END:VEVENT
* Braves @ Lookouts
<2018-08-02 Thu 18:15-21:15>
:PROPERTIES:
:ID:       QSi9Wod8pHWq0Q9xpQrmSHOs@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Braves @ Lookouts Braves @ Lookouts

Follow on MiLB First Pitch  https //stza.co/+wKFf-C

Shop  https //stza.co/+wKFf-25

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Braves @ Lookouts
END:VALARM
DTSTART:20180802T231500Z
DTEND:20180803T021500Z
UID:QSi9Wod8pHWq0Q9xpQrmSHOs@stanza.co
SUMMARY:Braves @ Lookouts
DESCRIPTION:Braves @ Lookouts\n\nFollow on MiLB First Pitch: https://stza.co/+wKFf-C\n\nShop: https://stza.co/+wKFf-25\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144544Z
LAST-MODIFIED:20180213T144544Z
TRANSP:OPAQUE
END:VEVENT
* Braves @ Lookouts
<2018-08-03 Fri 18:15-21:15>
:PROPERTIES:
:ID:       t3hCFzipxE0LgONUTFAbLPl6@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Braves @ Lookouts Braves @ Lookouts

Follow on MiLB First Pitch  https //stza.co/+wKFg-28

Shop  https //stza.co/+wKFg-3m

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Braves @ Lookouts
END:VALARM
DTSTART:20180803T231500Z
DTEND:20180804T021500Z
UID:t3hCFzipxE0LgONUTFAbLPl6@stanza.co
SUMMARY:Braves @ Lookouts
DESCRIPTION:Braves @ Lookouts\n\nFollow on MiLB First Pitch: https://stza.co/+wKFg-28\n\nShop: https://stza.co/+wKFg-3m\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144544Z
LAST-MODIFIED:20180213T144544Z
TRANSP:OPAQUE
END:VEVENT
* Braves @ Lookouts
<2018-08-04 Sat 18:15-21:15>
:PROPERTIES:
:ID:       H0l8oLO8-DLW3oFw0LWa5ydV@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Braves @ Lookouts Braves @ Lookouts

Follow on MiLB First Pitch  https //stza.co/+wKFh-2L

Shop  https //stza.co/+wKFh-35

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Braves @ Lookouts
END:VALARM
DTSTART:20180804T231500Z
DTEND:20180805T021500Z
UID:H0l8oLO8-DLW3oFw0LWa5ydV@stanza.co
SUMMARY:Braves @ Lookouts
DESCRIPTION:Braves @ Lookouts\n\nFollow on MiLB First Pitch: https://stza.co/+wKFh-2L\n\nShop: https://stza.co/+wKFh-35\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144544Z
LAST-MODIFIED:20180213T144544Z
TRANSP:OPAQUE
END:VEVENT
* Braves @ Lookouts
<2018-08-05 Sun 13:15-16:15>
:PROPERTIES:
:ID:       CMOMT5LyJ-YjkvnOy-zifmfa@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Braves @ Lookouts Braves @ Lookouts

Follow on MiLB First Pitch  https //stza.co/+wKFi-Q

Shop  https //stza.co/+wKFi-F

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Braves @ Lookouts
END:VALARM
DTSTART:20180805T181500Z
DTEND:20180805T211500Z
UID:CMOMT5LyJ-YjkvnOy-zifmfa@stanza.co
SUMMARY:Braves @ Lookouts
DESCRIPTION:Braves @ Lookouts\n\nFollow on MiLB First Pitch: https://stza.co/+wKFi-Q\n\nShop: https://stza.co/+wKFi-F\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144544Z
LAST-MODIFIED:20180213T144544Z
TRANSP:OPAQUE
END:VEVENT
* Braves @ Lookouts
<2018-08-06 Mon 18:15-21:15>
:PROPERTIES:
:ID:       O1Q8RMGHbEIjL0_Wg29zXpBJ@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Braves @ Lookouts Braves @ Lookouts

Follow on MiLB First Pitch  https //stza.co/+wKFj-3z

Shop  https //stza.co/+wKFj-t

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Braves @ Lookouts
END:VALARM
DTSTART:20180806T231500Z
DTEND:20180807T021500Z
UID:O1Q8RMGHbEIjL0_Wg29zXpBJ@stanza.co
SUMMARY:Braves @ Lookouts
DESCRIPTION:Braves @ Lookouts\n\nFollow on MiLB First Pitch: https://stza.co/+wKFj-3z\n\nShop: https://stza.co/+wKFj-t\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144544Z
LAST-MODIFIED:20180213T144544Z
TRANSP:OPAQUE
END:VEVENT
* Braves @ Jumbo Shrimp
<2018-08-08 Wed 18:05-21:05>
:PROPERTIES:
:ID:       fpcUWrN9agNYMJFQPzur-YVe@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Braves @ Jumbo Shrimp Braves @ Jumbo Shrimp

Follow on MiLB First Pitch  https //stza.co/+vLIY-2X

Shop  https //stza.co/+vLIY-2R

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Braves @ Jumbo Shrimp
END:VALARM
DTSTART:20180808T230500Z
DTEND:20180809T020500Z
UID:fpcUWrN9agNYMJFQPzur-YVe@stanza.co
SUMMARY:Braves @ Jumbo Shrimp
DESCRIPTION:Braves @ Jumbo Shrimp\n\nFollow on MiLB First Pitch: https://stza.co/+vLIY-2X\n\nShop: https://stza.co/+vLIY-2R\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144544Z
LAST-MODIFIED:20180213T144544Z
TRANSP:OPAQUE
END:VEVENT
* Braves @ Jumbo Shrimp
<2018-08-09 Thu 18:05-21:05>
:PROPERTIES:
:ID:       hSoyEoPWoIRpXn9LNnaDsdVn@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Braves @ Jumbo Shrimp Braves @ Jumbo Shrimp

Follow on MiLB First Pitch  https //stza.co/+vLIZ-37

Shop  https //stza.co/+vLIZ-2t

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Braves @ Jumbo Shrimp
END:VALARM
DTSTART:20180809T230500Z
DTEND:20180810T020500Z
UID:hSoyEoPWoIRpXn9LNnaDsdVn@stanza.co
SUMMARY:Braves @ Jumbo Shrimp
DESCRIPTION:Braves @ Jumbo Shrimp\n\nFollow on MiLB First Pitch: https://stza.co/+vLIZ-37\n\nShop: https://stza.co/+vLIZ-2t\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144544Z
LAST-MODIFIED:20180213T144544Z
TRANSP:OPAQUE
END:VEVENT
* Braves @ Jumbo Shrimp
<2018-08-10 Fri 18:05-21:05>
:PROPERTIES:
:ID:       0Uw4J6SOjmM2QVYO3hltYirU@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Braves @ Jumbo Shrimp Braves @ Jumbo Shrimp

Follow on MiLB First Pitch  https //stza.co/+vLI_-1V

Shop  https //stza.co/+vLI_-2l

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Braves @ Jumbo Shrimp
END:VALARM
DTSTART:20180810T230500Z
DTEND:20180811T020500Z
UID:0Uw4J6SOjmM2QVYO3hltYirU@stanza.co
SUMMARY:Braves @ Jumbo Shrimp
DESCRIPTION:Braves @ Jumbo Shrimp\n\nFollow on MiLB First Pitch: https://stza.co/+vLI_-1V\n\nShop: https://stza.co/+vLI_-2l\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144544Z
LAST-MODIFIED:20180213T144544Z
TRANSP:OPAQUE
END:VEVENT
* Braves @ Jumbo Shrimp
<2018-08-11 Sat 17:35-20:35>
:PROPERTIES:
:ID:       p3GX4Ri5Ll-BMo3L__mLT0Xv@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Braves @ Jumbo Shrimp Braves @ Jumbo Shrimp

Follow on MiLB First Pitch  https //stza.co/+vLI$-3t

Shop  https //stza.co/+vLI$-3I

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Braves @ Jumbo Shrimp
END:VALARM
DTSTART:20180811T223500Z
DTEND:20180812T013500Z
UID:p3GX4Ri5Ll-BMo3L__mLT0Xv@stanza.co
SUMMARY:Braves @ Jumbo Shrimp
DESCRIPTION:Braves @ Jumbo Shrimp\n\nFollow on MiLB First Pitch: https://stza.co/+vLI$-3t\n\nShop: https://stza.co/+vLI$-3I\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144544Z
LAST-MODIFIED:20180213T144544Z
TRANSP:OPAQUE
END:VEVENT
* Braves @ Jumbo Shrimp
<2018-08-12 Sun 14:05-17:05>
:PROPERTIES:
:ID:       _sbTnGr0t7QCNii_rwGKWtUm@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Braves @ Jumbo Shrimp Braves @ Jumbo Shrimp

Follow on MiLB First Pitch  https //stza.co/+vLJ0-r

Shop  https //stza.co/+vLJ0-2T

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Braves @ Jumbo Shrimp
END:VALARM
DTSTART:20180812T190500Z
DTEND:20180812T220500Z
UID:_sbTnGr0t7QCNii_rwGKWtUm@stanza.co
SUMMARY:Braves @ Jumbo Shrimp
DESCRIPTION:Braves @ Jumbo Shrimp\n\nFollow on MiLB First Pitch: https://stza.co/+vLJ0-r\n\nShop: https://stza.co/+vLJ0-2T\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144544Z
LAST-MODIFIED:20180213T144544Z
TRANSP:OPAQUE
END:VEVENT
* Braves vs. Lookouts
<2018-08-14 Tue 19:00-22:00>
:PROPERTIES:
:ID:       Lo_4gMg1iCFQiby4R8QHmA6A@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Braves vs. Lookouts Braves vs. Lookouts

Follow on MiLB First Pitch  https //stza.co/+vdqq-3z

Shop  https //stza.co/+vdqq-3S

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Braves vs. Lookouts
END:VALARM
DTSTART:20180815T000000Z
DTEND:20180815T030000Z
UID:Lo_4gMg1iCFQiby4R8QHmA6A@stanza.co
SUMMARY:Braves vs. Lookouts
DESCRIPTION:Braves vs. Lookouts\n\nFollow on MiLB First Pitch: https://stza.co/+vdqq-3z\n\nShop: https://stza.co/+vdqq-3S\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144544Z
LAST-MODIFIED:20180213T144544Z
TRANSP:OPAQUE
END:VEVENT
* Braves vs. Lookouts
<2018-08-15 Wed 19:00-22:00>
:PROPERTIES:
:ID:       xpF9cDzckqlrwngxCS3NPsMS@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Braves vs. Lookouts Braves vs. Lookouts

Follow on MiLB First Pitch  https //stza.co/+vdqs-D

Shop  https //stza.co/+vdqs-_

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Braves vs. Lookouts
END:VALARM
DTSTART:20180816T000000Z
DTEND:20180816T030000Z
UID:xpF9cDzckqlrwngxCS3NPsMS@stanza.co
SUMMARY:Braves vs. Lookouts
DESCRIPTION:Braves vs. Lookouts\n\nFollow on MiLB First Pitch: https://stza.co/+vdqs-D\n\nShop: https://stza.co/+vdqs-_\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144544Z
LAST-MODIFIED:20180213T144544Z
TRANSP:OPAQUE
END:VEVENT
* Braves vs. Lookouts
<2018-08-16 Thu 19:00-22:00>
:PROPERTIES:
:ID:       BgpeYZ1ZV-H13dmAYsVkKNGN@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Braves vs. Lookouts Braves vs. Lookouts

Follow on MiLB First Pitch  https //stza.co/+vdqt-2Y

Shop  https //stza.co/+vdqt-1S

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Braves vs. Lookouts
END:VALARM
DTSTART:20180817T000000Z
DTEND:20180817T030000Z
UID:BgpeYZ1ZV-H13dmAYsVkKNGN@stanza.co
SUMMARY:Braves vs. Lookouts
DESCRIPTION:Braves vs. Lookouts\n\nFollow on MiLB First Pitch: https://stza.co/+vdqt-2Y\n\nShop: https://stza.co/+vdqt-1S\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144544Z
LAST-MODIFIED:20180213T144544Z
TRANSP:OPAQUE
END:VEVENT
* Braves vs. Lookouts
<2018-08-17 Fri 19:00-22:00>
:PROPERTIES:
:ID:       3Yj956BJWCwFiF12x5VtJfpc@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Braves vs. Lookouts Braves vs. Lookouts

Follow on MiLB First Pitch  https //stza.co/+vLKZ-1C

Shop  https //stza.co/+vLKZ-2W

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Braves vs. Lookouts
END:VALARM
DTSTART:20180818T000000Z
DTEND:20180818T030000Z
UID:3Yj956BJWCwFiF12x5VtJfpc@stanza.co
SUMMARY:Braves vs. Lookouts
DESCRIPTION:Braves vs. Lookouts\n\nFollow on MiLB First Pitch: https://stza.co/+vLKZ-1C\n\nShop: https://stza.co/+vLKZ-2W\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144544Z
LAST-MODIFIED:20180213T144544Z
TRANSP:OPAQUE
END:VEVENT
* Braves vs. Lookouts
<2018-08-18 Sat 18:00-21:00>
:PROPERTIES:
:ID:       KelrY5YofcJLmcpG-6bXNwHY@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Braves vs. Lookouts Braves vs. Lookouts

Follow on MiLB First Pitch  https //stza.co/+vLK$-3W

Shop  https //stza.co/+vLK$-j

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Braves vs. Lookouts
END:VALARM
DTSTART:20180818T230000Z
DTEND:20180819T020000Z
UID:KelrY5YofcJLmcpG-6bXNwHY@stanza.co
SUMMARY:Braves vs. Lookouts
DESCRIPTION:Braves vs. Lookouts\n\nFollow on MiLB First Pitch: https://stza.co/+vLK$-3W\n\nShop: https://stza.co/+vLK$-j\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144544Z
LAST-MODIFIED:20180213T144544Z
TRANSP:OPAQUE
END:VEVENT
* Braves @ BayBears
<2018-08-19 Sun 17:05-20:05>
:PROPERTIES:
:ID:       6lla5qTy4OQGQK-Vq698I7Ec@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Braves @ BayBears Braves @ BayBears

Follow on MiLB First Pitch  https //stza.co/+v$Q0-3m

Shop  https //stza.co/+v$Q0-3Z

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Braves @ BayBears
END:VALARM
DTSTART:20180819T220500Z
DTEND:20180820T010500Z
UID:6lla5qTy4OQGQK-Vq698I7Ec@stanza.co
SUMMARY:Braves @ BayBears
DESCRIPTION:Braves @ BayBears\n\nFollow on MiLB First Pitch: https://stza.co/+v$Q0-3m\n\nShop: https://stza.co/+v$Q0-3Z\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144544Z
LAST-MODIFIED:20180213T144544Z
TRANSP:OPAQUE
END:VEVENT
* Braves @ BayBears
<2018-08-20 Mon 18:35-21:35>
:PROPERTIES:
:ID:       JExl_cujLc4KdhlSwJW-4REG@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Braves @ BayBears Braves @ BayBears

Follow on MiLB First Pitch  https //stza.co/+v$Q1-3N

Shop  https //stza.co/+v$Q1-39

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Braves @ BayBears
END:VALARM
DTSTART:20180820T233500Z
DTEND:20180821T023500Z
UID:JExl_cujLc4KdhlSwJW-4REG@stanza.co
SUMMARY:Braves @ BayBears
DESCRIPTION:Braves @ BayBears\n\nFollow on MiLB First Pitch: https://stza.co/+v$Q1-3N\n\nShop: https://stza.co/+v$Q1-39\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144544Z
LAST-MODIFIED:20180213T144544Z
TRANSP:OPAQUE
END:VEVENT
* Braves @ BayBears
<2018-08-21 Tue 18:35-21:35>
:PROPERTIES:
:ID:       a9t3_HFSY__V_ffRuda8RaJN@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Braves @ BayBears Braves @ BayBears

Follow on MiLB First Pitch  https //stza.co/+v$Q2-2b

Shop  https //stza.co/+v$Q2-5

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Braves @ BayBears
END:VALARM
DTSTART:20180821T233500Z
DTEND:20180822T023500Z
UID:a9t3_HFSY__V_ffRuda8RaJN@stanza.co
SUMMARY:Braves @ BayBears
DESCRIPTION:Braves @ BayBears\n\nFollow on MiLB First Pitch: https://stza.co/+v$Q2-2b\n\nShop: https://stza.co/+v$Q2-5\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144544Z
LAST-MODIFIED:20180213T144544Z
TRANSP:OPAQUE
END:VEVENT
* Braves @ BayBears
<2018-08-22 Wed 18:35-21:35>
:PROPERTIES:
:ID:       fRtu8KareJTnzvVpIEfOCldC@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Braves @ BayBears Braves @ BayBears

Follow on MiLB First Pitch  https //stza.co/+v$Q3-1w

Shop  https //stza.co/+v$Q3-1D

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Braves @ BayBears
END:VALARM
DTSTART:20180822T233500Z
DTEND:20180823T023500Z
UID:fRtu8KareJTnzvVpIEfOCldC@stanza.co
SUMMARY:Braves @ BayBears
DESCRIPTION:Braves @ BayBears\n\nFollow on MiLB First Pitch: https://stza.co/+v$Q3-1w\n\nShop: https://stza.co/+v$Q3-1D\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144544Z
LAST-MODIFIED:20180213T144544Z
TRANSP:OPAQUE
END:VEVENT
* Braves @ BayBears
<2018-08-23 Thu 18:35-21:35>
:PROPERTIES:
:ID:       UPiaU1BTkgBqgvlvpw15rUZe@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Braves @ BayBears Braves @ BayBears

Follow on MiLB First Pitch  https //stza.co/+v$Q4-n

Shop  https //stza.co/+v$Q4-2A

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Braves @ BayBears
END:VALARM
DTSTART:20180823T233500Z
DTEND:20180824T023500Z
UID:UPiaU1BTkgBqgvlvpw15rUZe@stanza.co
SUMMARY:Braves @ BayBears
DESCRIPTION:Braves @ BayBears\n\nFollow on MiLB First Pitch: https://stza.co/+v$Q4-n\n\nShop: https://stza.co/+v$Q4-2A\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144544Z
LAST-MODIFIED:20180213T144544Z
TRANSP:OPAQUE
END:VEVENT
* Braves vs. Shuckers
<2018-08-24 Fri 19:00-22:00>
:PROPERTIES:
:ID:       cYKVdhOZKsEUNAJRG3UYTwxp@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Braves vs. Shuckers Braves vs. Shuckers

Follow on MiLB First Pitch  https //stza.co/+vLL0-3P

Shop  https //stza.co/+vLL0-2s

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Braves vs. Shuckers
END:VALARM
DTSTART:20180825T000000Z
DTEND:20180825T030000Z
UID:cYKVdhOZKsEUNAJRG3UYTwxp@stanza.co
SUMMARY:Braves vs. Shuckers
DESCRIPTION:Braves vs. Shuckers\n\nFollow on MiLB First Pitch: https://stza.co/+vLL0-3P\n\nShop: https://stza.co/+vLL0-2s\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144544Z
LAST-MODIFIED:20180213T144544Z
TRANSP:OPAQUE
END:VEVENT
* Braves vs. Shuckers
<2018-08-25 Sat 18:00-21:00>
:PROPERTIES:
:ID:       uLykWw5hlK25v2s0CeHjv8Tq@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Braves vs. Shuckers Braves vs. Shuckers

Follow on MiLB First Pitch  https //stza.co/+vLL2-1g

Shop  https //stza.co/+vLL2-3w

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Braves vs. Shuckers
END:VALARM
DTSTART:20180825T230000Z
DTEND:20180826T020000Z
UID:uLykWw5hlK25v2s0CeHjv8Tq@stanza.co
SUMMARY:Braves vs. Shuckers
DESCRIPTION:Braves vs. Shuckers\n\nFollow on MiLB First Pitch: https://stza.co/+vLL2-1g\n\nShop: https://stza.co/+vLL2-3w\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144544Z
LAST-MODIFIED:20180213T144544Z
TRANSP:OPAQUE
END:VEVENT
* Braves vs. Shuckers
<2018-08-26 Sun 17:00-20:00>
:PROPERTIES:
:ID:       vGL7PRvKcYkg9af_qblDZ39K@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Braves vs. Shuckers Braves vs. Shuckers

Follow on MiLB First Pitch  https //stza.co/+vLL4-3c

Shop  https //stza.co/+vLL4-3

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Braves vs. Shuckers
END:VALARM
DTSTART:20180826T220000Z
DTEND:20180827T010000Z
UID:vGL7PRvKcYkg9af_qblDZ39K@stanza.co
SUMMARY:Braves vs. Shuckers
DESCRIPTION:Braves vs. Shuckers\n\nFollow on MiLB First Pitch: https://stza.co/+vLL4-3c\n\nShop: https://stza.co/+vLL4-3\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144544Z
LAST-MODIFIED:20180213T144544Z
TRANSP:OPAQUE
END:VEVENT
* Braves vs. Shuckers
<2018-08-27 Mon 19:00-22:00>
:PROPERTIES:
:ID:       cqIKF_DyB7h--uK1kX_bqik8@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Braves vs. Shuckers Braves vs. Shuckers

Follow on MiLB First Pitch  https //stza.co/+vLL7-1d

Shop  https //stza.co/+vLL7-3D

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Braves vs. Shuckers
END:VALARM
DTSTART:20180828T000000Z
DTEND:20180828T030000Z
UID:cqIKF_DyB7h--uK1kX_bqik8@stanza.co
SUMMARY:Braves vs. Shuckers
DESCRIPTION:Braves vs. Shuckers\n\nFollow on MiLB First Pitch: https://stza.co/+vLL7-1d\n\nShop: https://stza.co/+vLL7-3D\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144544Z
LAST-MODIFIED:20180213T144544Z
TRANSP:OPAQUE
END:VEVENT
* Braves vs. Shuckers
<2018-08-28 Tue 12:00-15:00>
:PROPERTIES:
:ID:       f1yf5zHB3O57KI3t3-YoGRb-@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Braves vs. Shuckers Braves vs. Shuckers

Follow on MiLB First Pitch  https //stza.co/+xM66-v

Shop  https //stza.co/+xM66-16

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Braves vs. Shuckers
END:VALARM
DTSTART:20180828T170000Z
DTEND:20180828T200000Z
UID:f1yf5zHB3O57KI3t3-YoGRb-@stanza.co
SUMMARY:Braves vs. Shuckers
DESCRIPTION:Braves vs. Shuckers\n\nFollow on MiLB First Pitch: https://stza.co/+xM66-v\n\nShop: https://stza.co/+xM66-16\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144544Z
LAST-MODIFIED:20180213T144544Z
TRANSP:OPAQUE
END:VEVENT
* Braves @ Jumbo Shrimp
<2018-08-30 Thu 18:05-21:05>
:PROPERTIES:
:ID:       _bo333daNAAnuqqpA-cc3jSf@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Braves @ Jumbo Shrimp Braves @ Jumbo Shrimp

Follow on MiLB First Pitch  https //stza.co/+vLJ1-2G

Shop  https //stza.co/+vLJ1-16

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Braves @ Jumbo Shrimp
END:VALARM
DTSTART:20180830T230500Z
DTEND:20180831T020500Z
UID:_bo333daNAAnuqqpA-cc3jSf@stanza.co
SUMMARY:Braves @ Jumbo Shrimp
DESCRIPTION:Braves @ Jumbo Shrimp\n\nFollow on MiLB First Pitch: https://stza.co/+vLJ1-2G\n\nShop: https://stza.co/+vLJ1-16\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144544Z
LAST-MODIFIED:20180213T144544Z
TRANSP:OPAQUE
END:VEVENT
* Braves @ Jumbo Shrimp
<2018-08-31 Fri 18:05-21:05>
:PROPERTIES:
:ID:       GSzBbbSrU6mzPFDNwb8KtXxH@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Braves @ Jumbo Shrimp Braves @ Jumbo Shrimp

Follow on MiLB First Pitch  https //stza.co/+vLJ2-3l

Shop  https //stza.co/+vLJ2-4

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Braves @ Jumbo Shrimp
END:VALARM
DTSTART:20180831T230500Z
DTEND:20180901T020500Z
UID:GSzBbbSrU6mzPFDNwb8KtXxH@stanza.co
SUMMARY:Braves @ Jumbo Shrimp
DESCRIPTION:Braves @ Jumbo Shrimp\n\nFollow on MiLB First Pitch: https://stza.co/+vLJ2-3l\n\nShop: https://stza.co/+vLJ2-4\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144544Z
LAST-MODIFIED:20180213T144544Z
TRANSP:OPAQUE
END:VEVENT
* Braves @ Jumbo Shrimp
<2018-09-01 Sat 17:35-20:35>
:PROPERTIES:
:ID:       9pmfmuvyPhJUz4ocHm-Wphw2@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Braves @ Jumbo Shrimp Braves @ Jumbo Shrimp

Follow on MiLB First Pitch  https //stza.co/+vLJ3-B

Shop  https //stza.co/+vLJ3-1n

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Braves @ Jumbo Shrimp
END:VALARM
DTSTART:20180901T223500Z
DTEND:20180902T013500Z
UID:9pmfmuvyPhJUz4ocHm-Wphw2@stanza.co
SUMMARY:Braves @ Jumbo Shrimp
DESCRIPTION:Braves @ Jumbo Shrimp\n\nFollow on MiLB First Pitch: https://stza.co/+vLJ3-B\n\nShop: https://stza.co/+vLJ3-1n\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144544Z
LAST-MODIFIED:20180213T144544Z
TRANSP:OPAQUE
END:VEVENT
* Braves @ Jumbo Shrimp
<2018-09-02 Sun 17:05-20:05>
:PROPERTIES:
:ID:       COXPW7z4Gvpg32tVHR8eXc6_@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Braves @ Jumbo Shrimp Braves @ Jumbo Shrimp

Follow on MiLB First Pitch  https //stza.co/+vLJ4-M

Shop  https //stza.co/+vLJ4-1i

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Braves @ Jumbo Shrimp
END:VALARM
DTSTART:20180902T220500Z
DTEND:20180903T010500Z
UID:COXPW7z4Gvpg32tVHR8eXc6_@stanza.co
SUMMARY:Braves @ Jumbo Shrimp
DESCRIPTION:Braves @ Jumbo Shrimp\n\nFollow on MiLB First Pitch: https://stza.co/+vLJ4-M\n\nShop: https://stza.co/+vLJ4-1i\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144544Z
LAST-MODIFIED:20180213T144544Z
TRANSP:OPAQUE
END:VEVENT
* Braves @ Jumbo Shrimp
<2018-09-03 Mon 13:05-16:05>
:PROPERTIES:
:ID:       Wx9ztaXpy3YCxmWrsVc4bf4O@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Braves @ Jumbo Shrimp Braves @ Jumbo Shrimp

Follow on MiLB First Pitch  https //stza.co/+vLJ5-_

Shop  https //stza.co/+vLJ5-3s

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Braves @ Jumbo Shrimp
END:VALARM
DTSTART:20180903T180500Z
DTEND:20180903T210500Z
UID:Wx9ztaXpy3YCxmWrsVc4bf4O@stanza.co
SUMMARY:Braves @ Jumbo Shrimp
DESCRIPTION:Braves @ Jumbo Shrimp\n\nFollow on MiLB First Pitch: https://stza.co/+vLJ5-_\n\nShop: https://stza.co/+vLJ5-3s\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144544Z
LAST-MODIFIED:20180213T144544Z
TRANSP:OPAQUE
END:VEVENT
