#+TITLE:       Main Google calendar entries
#+AUTHOR:      Eric S Fraga
#+EMAIL:       e.fraga@ucl.ac.uk
#+DESCRIPTION: converted using the ical2org awk script
#+CATEGORY:    google
#+STARTUP:     hidestars
#+STARTUP:     overview

* COMMENT original iCal preamble

* Redbirds @ Express
<2018-04-05 Thu 19:05-22:05>
:PROPERTIES:
:ID:       byhW0O3WdTDBbEjNhNvzjHIR@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Redbirds @ Express Redbirds @ Express

Follow on MiLB First Pitch  https //stza.co/+v1Kc-1w

Shop  https //stza.co/+v1Kc-2G

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Redbirds @ Express
END:VALARM
DTSTART:20180406T000500Z
DTEND:20180406T030500Z
UID:byhW0O3WdTDBbEjNhNvzjHIR@stanza.co
SUMMARY:Redbirds @ Express
DESCRIPTION:Redbirds @ Express\n\nFollow on MiLB First Pitch: https://stza.co/+v1Kc-1w\n\nShop: https://stza.co/+v1Kc-2G\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144543Z
LAST-MODIFIED:20180213T144543Z
TRANSP:OPAQUE
END:VEVENT
* Redbirds @ Express
<2018-04-06 Fri 19:05-22:05>
:PROPERTIES:
:ID:       mEzb_h8mUrolhizL71OH-7TC@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Redbirds @ Express Redbirds @ Express

Follow on MiLB First Pitch  https //stza.co/+v1Kq-1L

Shop  https //stza.co/+v1Kq-2F

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Redbirds @ Express
END:VALARM
DTSTART:20180407T000500Z
DTEND:20180407T030500Z
UID:mEzb_h8mUrolhizL71OH-7TC@stanza.co
SUMMARY:Redbirds @ Express
DESCRIPTION:Redbirds @ Express\n\nFollow on MiLB First Pitch: https://stza.co/+v1Kq-1L\n\nShop: https://stza.co/+v1Kq-2F\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144543Z
LAST-MODIFIED:20180213T144543Z
TRANSP:OPAQUE
END:VEVENT
* Redbirds @ Express
<2018-04-07 Sat 18:05-21:05>
:PROPERTIES:
:ID:       XLw0neoK5yIQLg8f4rptOqt6@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Redbirds @ Express Redbirds @ Express

Follow on MiLB First Pitch  https //stza.co/+v1KG-37

Shop  https //stza.co/+v1KG-A

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Redbirds @ Express
END:VALARM
DTSTART:20180407T230500Z
DTEND:20180408T020500Z
UID:XLw0neoK5yIQLg8f4rptOqt6@stanza.co
SUMMARY:Redbirds @ Express
DESCRIPTION:Redbirds @ Express\n\nFollow on MiLB First Pitch: https://stza.co/+v1KG-37\n\nShop: https://stza.co/+v1KG-A\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144543Z
LAST-MODIFIED:20180213T144543Z
TRANSP:OPAQUE
END:VEVENT
* Redbirds @ Express
<2018-04-08 Sun 13:05-16:05>
:PROPERTIES:
:ID:       oPvJtdzLdXNE1NZaT-Xt3BAH@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Redbirds @ Express Redbirds @ Express

Follow on MiLB First Pitch  https //stza.co/+v1K_-1o

Shop  https //stza.co/+v1K_-c

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Redbirds @ Express
END:VALARM
DTSTART:20180408T180500Z
DTEND:20180408T210500Z
UID:oPvJtdzLdXNE1NZaT-Xt3BAH@stanza.co
SUMMARY:Redbirds @ Express
DESCRIPTION:Redbirds @ Express\n\nFollow on MiLB First Pitch: https://stza.co/+v1K_-1o\n\nShop: https://stza.co/+v1K_-c\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144543Z
LAST-MODIFIED:20180213T144543Z
TRANSP:OPAQUE
END:VEVENT
* Redbirds @ Express
<2018-04-09 Mon 19:05-22:05>
:PROPERTIES:
:ID:       Xh5f6j3CYoC36iFPiM0P74gu@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Redbirds @ Express Redbirds @ Express

Follow on MiLB First Pitch  https //stza.co/+v1Lf-3E

Shop  https //stza.co/+v1Lf-1T

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Redbirds @ Express
END:VALARM
DTSTART:20180410T000500Z
DTEND:20180410T030500Z
UID:Xh5f6j3CYoC36iFPiM0P74gu@stanza.co
SUMMARY:Redbirds @ Express
DESCRIPTION:Redbirds @ Express\n\nFollow on MiLB First Pitch: https://stza.co/+v1Lf-3E\n\nShop: https://stza.co/+v1Lf-1T\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144543Z
LAST-MODIFIED:20180213T144543Z
TRANSP:OPAQUE
END:VEVENT
* Redbirds vs. Storm Chasers
<2018-04-10 Tue 19:05-22:05>
:PROPERTIES:
:ID:       vuuGw5MHeeaZH4Rku9gM0SBM@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Redbirds vs. Storm Chasers Redbirds vs. Storm Chasers

Follow on MiLB First Pitch  https //stza.co/+wmEp-1x

Shop  https //stza.co/+wmEp-n

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Redbirds vs. Storm Chasers
END:VALARM
DTSTART:20180411T000500Z
DTEND:20180411T030500Z
UID:vuuGw5MHeeaZH4Rku9gM0SBM@stanza.co
SUMMARY:Redbirds vs. Storm Chasers
DESCRIPTION:Redbirds vs. Storm Chasers\n\nFollow on MiLB First Pitch: https://stza.co/+wmEp-1x\n\nShop: https://stza.co/+wmEp-n\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144543Z
LAST-MODIFIED:20180213T144543Z
TRANSP:OPAQUE
END:VEVENT
* Redbirds vs. Storm Chasers
<2018-04-11 Wed 11:05-14:05>
:PROPERTIES:
:ID:       TZ0zk1oIpisTQ0XU4Ma1HD9R@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Redbirds vs. Storm Chasers Redbirds vs. Storm Chasers

Follow on MiLB First Pitch  https //stza.co/+wmEr-2$

Shop  https //stza.co/+wmEr-1Q

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Redbirds vs. Storm Chasers
END:VALARM
DTSTART:20180411T160500Z
DTEND:20180411T190500Z
UID:TZ0zk1oIpisTQ0XU4Ma1HD9R@stanza.co
SUMMARY:Redbirds vs. Storm Chasers
DESCRIPTION:Redbirds vs. Storm Chasers\n\nFollow on MiLB First Pitch: https://stza.co/+wmEr-2$\n\nShop: https://stza.co/+wmEr-1Q\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144543Z
LAST-MODIFIED:20180213T144543Z
TRANSP:OPAQUE
END:VEVENT
* Redbirds vs. Storm Chasers
<2018-04-12 Thu 19:05-22:05>
:PROPERTIES:
:ID:       067hO9ph3K0NS7ATYxu-LKk_@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Redbirds vs. Storm Chasers Redbirds vs. Storm Chasers

Follow on MiLB First Pitch  https //stza.co/+wmEt-1f

Shop  https //stza.co/+wmEt-1j

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Redbirds vs. Storm Chasers
END:VALARM
DTSTART:20180413T000500Z
DTEND:20180413T030500Z
UID:067hO9ph3K0NS7ATYxu-LKk_@stanza.co
SUMMARY:Redbirds vs. Storm Chasers
DESCRIPTION:Redbirds vs. Storm Chasers\n\nFollow on MiLB First Pitch: https://stza.co/+wmEt-1f\n\nShop: https://stza.co/+wmEt-1j\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144543Z
LAST-MODIFIED:20180213T144543Z
TRANSP:OPAQUE
END:VEVENT
* Redbirds vs. Cubs
<2018-04-13 Fri 19:05-22:05>
:PROPERTIES:
:ID:       FnhUxg1lAwWwPAE4REHC6lcR@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Redbirds vs. Cubs Redbirds vs. Cubs

Follow on MiLB First Pitch  https //stza.co/+wmEu-d

Shop  https //stza.co/+wmEu-2v

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Redbirds vs. Cubs
END:VALARM
DTSTART:20180414T000500Z
DTEND:20180414T030500Z
UID:FnhUxg1lAwWwPAE4REHC6lcR@stanza.co
SUMMARY:Redbirds vs. Cubs
DESCRIPTION:Redbirds vs. Cubs\n\nFollow on MiLB First Pitch: https://stza.co/+wmEu-d\n\nShop: https://stza.co/+wmEu-2v\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144543Z
LAST-MODIFIED:20180213T144543Z
TRANSP:OPAQUE
END:VEVENT
* Redbirds vs. Cubs
<2018-04-14 Sat 18:35-21:35>
:PROPERTIES:
:ID:       eGEYhhHGIE7T6BPoqJFHf8za@stanza.co
:LOCATION: Postgame Fireworks
:STATUS:   CONFIRMED
:END:

Redbirds vs. Cubs Stick around after the game for an amazing fireworks spectacular, launched up close and personal from center field.

Follow on MiLB First Pitch  https //stza.co/+wmEw-2q

Shop  https //stza.co/+wmEw-2i

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Redbirds vs. Cubs
END:VALARM
DTSTART:20180414T233500Z
DTEND:20180415T023500Z
UID:eGEYhhHGIE7T6BPoqJFHf8za@stanza.co
SUMMARY:Redbirds vs. Cubs
DESCRIPTION:Stick around after the game for an amazing fireworks spectacular, launched up close and personal from center field.\n\nFollow on MiLB First Pitch: https://stza.co/+wmEw-2q\n\nShop: https://stza.co/+wmEw-2i\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Postgame Fireworks
STATUS:CONFIRMED
CREATED:20180213T144543Z
LAST-MODIFIED:20180213T144543Z
TRANSP:OPAQUE
END:VEVENT
* Redbirds vs. Cubs
<2018-04-15 Sun 14:05-17:05>
:PROPERTIES:
:ID:       3vekkKtDIzF0NMseH_HKYAwC@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Redbirds vs. Cubs Redbirds vs. Cubs

Follow on MiLB First Pitch  https //stza.co/+wmEy-Y

Shop  https //stza.co/+wmEy-1n

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Redbirds vs. Cubs
END:VALARM
DTSTART:20180415T190500Z
DTEND:20180415T220500Z
UID:3vekkKtDIzF0NMseH_HKYAwC@stanza.co
SUMMARY:Redbirds vs. Cubs
DESCRIPTION:Redbirds vs. Cubs\n\nFollow on MiLB First Pitch: https://stza.co/+wmEy-Y\n\nShop: https://stza.co/+wmEy-1n\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144543Z
LAST-MODIFIED:20180213T144543Z
TRANSP:OPAQUE
END:VEVENT
* Redbirds vs. Cubs
<2018-04-16 Mon 11:05-14:05>
:PROPERTIES:
:ID:       kxbMjziNI9x_m27tpgfJj6EK@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Redbirds vs. Cubs Redbirds vs. Cubs

Follow on MiLB First Pitch  https //stza.co/+wmEB-2i

Shop  https //stza.co/+wmEB-3Y

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Redbirds vs. Cubs
END:VALARM
DTSTART:20180416T160500Z
DTEND:20180416T190500Z
UID:kxbMjziNI9x_m27tpgfJj6EK@stanza.co
SUMMARY:Redbirds vs. Cubs
DESCRIPTION:Redbirds vs. Cubs\n\nFollow on MiLB First Pitch: https://stza.co/+wmEB-2i\n\nShop: https://stza.co/+wmEB-3Y\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144543Z
LAST-MODIFIED:20180213T144543Z
TRANSP:OPAQUE
END:VEVENT
* Redbirds @ Storm Chasers
<2018-04-17 Tue 18:35-21:35>
:PROPERTIES:
:ID:       lEL2IkcK_lq-Rx5wgZYemBZ_@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Redbirds @ Storm Chasers Redbirds @ Storm Chasers

Follow on MiLB First Pitch  https //stza.co/+whFJ-y

Shop  https //stza.co/+whFJ-2Y

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Redbirds @ Storm Chasers
END:VALARM
DTSTART:20180417T233500Z
DTEND:20180418T023500Z
UID:lEL2IkcK_lq-Rx5wgZYemBZ_@stanza.co
SUMMARY:Redbirds @ Storm Chasers
DESCRIPTION:Redbirds @ Storm Chasers\n\nFollow on MiLB First Pitch: https://stza.co/+whFJ-y\n\nShop: https://stza.co/+whFJ-2Y\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144543Z
LAST-MODIFIED:20180213T144543Z
TRANSP:OPAQUE
END:VEVENT
* Redbirds @ Storm Chasers
<2018-04-18 Wed 18:35-21:35>
:PROPERTIES:
:ID:       Sc0q4DY4p8RiDPGieBDgRK4B@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Redbirds @ Storm Chasers Redbirds @ Storm Chasers

Follow on MiLB First Pitch  https //stza.co/+whFK-1j

Shop  https //stza.co/+whFK-3o

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Redbirds @ Storm Chasers
END:VALARM
DTSTART:20180418T233500Z
DTEND:20180419T023500Z
UID:Sc0q4DY4p8RiDPGieBDgRK4B@stanza.co
SUMMARY:Redbirds @ Storm Chasers
DESCRIPTION:Redbirds @ Storm Chasers\n\nFollow on MiLB First Pitch: https://stza.co/+whFK-1j\n\nShop: https://stza.co/+whFK-3o\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144543Z
LAST-MODIFIED:20180213T144543Z
TRANSP:OPAQUE
END:VEVENT
* Redbirds @ Storm Chasers
<2018-04-19 Thu 18:35-21:35>
:PROPERTIES:
:ID:       GJKEe749ZALp4OiqmJ2pQ4jK@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Redbirds @ Storm Chasers Redbirds @ Storm Chasers

Follow on MiLB First Pitch  https //stza.co/+whFL-3c

Shop  https //stza.co/+whFL-1J

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Redbirds @ Storm Chasers
END:VALARM
DTSTART:20180419T233500Z
DTEND:20180420T023500Z
UID:GJKEe749ZALp4OiqmJ2pQ4jK@stanza.co
SUMMARY:Redbirds @ Storm Chasers
DESCRIPTION:Redbirds @ Storm Chasers\n\nFollow on MiLB First Pitch: https://stza.co/+whFL-3c\n\nShop: https://stza.co/+whFL-1J\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144543Z
LAST-MODIFIED:20180213T144543Z
TRANSP:OPAQUE
END:VEVENT
* Redbirds @ Storm Chasers
<2018-04-20 Fri 19:05-22:05>
:PROPERTIES:
:ID:       FwFrckg6Yh6vCs4jSRGW7k_C@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Redbirds @ Storm Chasers Redbirds @ Storm Chasers

Follow on MiLB First Pitch  https //stza.co/+whFN-3S

Shop  https //stza.co/+whFN-F

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Redbirds @ Storm Chasers
END:VALARM
DTSTART:20180421T000500Z
DTEND:20180421T030500Z
UID:FwFrckg6Yh6vCs4jSRGW7k_C@stanza.co
SUMMARY:Redbirds @ Storm Chasers
DESCRIPTION:Redbirds @ Storm Chasers\n\nFollow on MiLB First Pitch: https://stza.co/+whFN-3S\n\nShop: https://stza.co/+whFN-F\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144543Z
LAST-MODIFIED:20180213T144543Z
TRANSP:OPAQUE
END:VEVENT
* Redbirds @ Cubs
<2018-04-21 Sat 19:08-22:08>
:PROPERTIES:
:ID:       wuyZJY1EvVOxl6nYCbsUbFC7@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Redbirds @ Cubs Redbirds @ Cubs

Follow on MiLB First Pitch  https //stza.co/+v1Cz-1M

Shop  https //stza.co/+v1Cz-3L

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Redbirds @ Cubs
END:VALARM
DTSTART:20180422T000800Z
DTEND:20180422T030800Z
UID:wuyZJY1EvVOxl6nYCbsUbFC7@stanza.co
SUMMARY:Redbirds @ Cubs
DESCRIPTION:Redbirds @ Cubs\n\nFollow on MiLB First Pitch: https://stza.co/+v1Cz-1M\n\nShop: https://stza.co/+v1Cz-3L\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144543Z
LAST-MODIFIED:20180213T144543Z
TRANSP:OPAQUE
END:VEVENT
* Redbirds @ Cubs
<2018-04-22 Sun 13:08-16:08>
:PROPERTIES:
:ID:       HdlTX-fbwa-YbtuNpKdZIAb4@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Redbirds @ Cubs Redbirds @ Cubs

Follow on MiLB First Pitch  https //stza.co/+v1CA-j

Shop  https //stza.co/+v1CA-H

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Redbirds @ Cubs
END:VALARM
DTSTART:20180422T180800Z
DTEND:20180422T210800Z
UID:HdlTX-fbwa-YbtuNpKdZIAb4@stanza.co
SUMMARY:Redbirds @ Cubs
DESCRIPTION:Redbirds @ Cubs\n\nFollow on MiLB First Pitch: https://stza.co/+v1CA-j\n\nShop: https://stza.co/+v1CA-H\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144543Z
LAST-MODIFIED:20180213T144543Z
TRANSP:OPAQUE
END:VEVENT
* Redbirds @ Cubs
<2018-04-23 Mon 12:08-15:08>
:PROPERTIES:
:ID:       UgHZQkXWQgkHYuvGJ9NG8hLz@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Redbirds @ Cubs Redbirds @ Cubs

Follow on MiLB First Pitch  https //stza.co/+v1CB-2M

Shop  https //stza.co/+v1CB-2B

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Redbirds @ Cubs
END:VALARM
DTSTART:20180423T170800Z
DTEND:20180423T200800Z
UID:UgHZQkXWQgkHYuvGJ9NG8hLz@stanza.co
SUMMARY:Redbirds @ Cubs
DESCRIPTION:Redbirds @ Cubs\n\nFollow on MiLB First Pitch: https://stza.co/+v1CB-2M\n\nShop: https://stza.co/+v1CB-2B\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144543Z
LAST-MODIFIED:20180213T144543Z
TRANSP:OPAQUE
END:VEVENT
* Redbirds vs. Express
<2018-04-25 Wed 18:35-21:35>
:PROPERTIES:
:ID:       gPPDeEiMAkrpwddHhKa3w_W4@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Redbirds vs. Express Redbirds vs. Express

Follow on MiLB First Pitch  https //stza.co/+wmED-1P

Shop  https //stza.co/+wmED-3z

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Redbirds vs. Express
END:VALARM
DTSTART:20180425T233500Z
DTEND:20180426T023500Z
UID:gPPDeEiMAkrpwddHhKa3w_W4@stanza.co
SUMMARY:Redbirds vs. Express
DESCRIPTION:Redbirds vs. Express\n\nFollow on MiLB First Pitch: https://stza.co/+wmED-1P\n\nShop: https://stza.co/+wmED-3z\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144543Z
LAST-MODIFIED:20180213T144543Z
TRANSP:OPAQUE
END:VEVENT
* Redbirds vs. Express
<2018-04-26 Thu 19:05-22:05>
:PROPERTIES:
:ID:       xVfAPI6n7Q9tKyFTC-c6qixi@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Redbirds vs. Express Redbirds vs. Express

Follow on MiLB First Pitch  https //stza.co/+wmEF-k

Shop  https //stza.co/+wmEF-1B

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Redbirds vs. Express
END:VALARM
DTSTART:20180427T000500Z
DTEND:20180427T030500Z
UID:xVfAPI6n7Q9tKyFTC-c6qixi@stanza.co
SUMMARY:Redbirds vs. Express
DESCRIPTION:Redbirds vs. Express\n\nFollow on MiLB First Pitch: https://stza.co/+wmEF-k\n\nShop: https://stza.co/+wmEF-1B\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144543Z
LAST-MODIFIED:20180213T144543Z
TRANSP:OPAQUE
END:VEVENT
* Redbirds vs. Express
<2018-04-27 Fri 19:05-22:05>
:PROPERTIES:
:ID:       1ItvIA3Atqrt5k7GYr0_OzMO@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Redbirds vs. Express Redbirds vs. Express

Follow on MiLB First Pitch  https //stza.co/+wmEH-13

Shop  https //stza.co/+wmEH-F

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Redbirds vs. Express
END:VALARM
DTSTART:20180428T000500Z
DTEND:20180428T030500Z
UID:1ItvIA3Atqrt5k7GYr0_OzMO@stanza.co
SUMMARY:Redbirds vs. Express
DESCRIPTION:Redbirds vs. Express\n\nFollow on MiLB First Pitch: https://stza.co/+wmEH-13\n\nShop: https://stza.co/+wmEH-F\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144543Z
LAST-MODIFIED:20180213T144543Z
TRANSP:OPAQUE
END:VEVENT
* Redbirds vs. Express
<2018-04-28 Sat 18:35-21:35>
:PROPERTIES:
:ID:       Wb42aR9u4PrkckLE4nnwd7PT@stanza.co
:LOCATION: Postgame Fireworks
:STATUS:   CONFIRMED
:END:

Redbirds vs. Express Stick around after the game for an amazing fireworks spectacular, launched up close and personal from center field.

Follow on MiLB First Pitch  https //stza.co/+wmEI-2s

Shop  https //stza.co/+wmEI-1m

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Redbirds vs. Express
END:VALARM
DTSTART:20180428T233500Z
DTEND:20180429T023500Z
UID:Wb42aR9u4PrkckLE4nnwd7PT@stanza.co
SUMMARY:Redbirds vs. Express
DESCRIPTION:Stick around after the game for an amazing fireworks spectacular, launched up close and personal from center field.\n\nFollow on MiLB First Pitch: https://stza.co/+wmEI-2s\n\nShop: https://stza.co/+wmEI-1m\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Postgame Fireworks
STATUS:CONFIRMED
CREATED:20180213T144543Z
LAST-MODIFIED:20180213T144543Z
TRANSP:OPAQUE
END:VEVENT
* Redbirds vs. Express
<2018-04-29 Sun 14:05-17:05>
:PROPERTIES:
:ID:       BcNnhdiQt7P5VyD1Gttc4mED@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Redbirds vs. Express Redbirds vs. Express

Follow on MiLB First Pitch  https //stza.co/+wmEL-2Q

Shop  https //stza.co/+wmEL-35

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Redbirds vs. Express
END:VALARM
DTSTART:20180429T190500Z
DTEND:20180429T220500Z
UID:BcNnhdiQt7P5VyD1Gttc4mED@stanza.co
SUMMARY:Redbirds vs. Express
DESCRIPTION:Redbirds vs. Express\n\nFollow on MiLB First Pitch: https://stza.co/+wmEL-2Q\n\nShop: https://stza.co/+wmEL-35\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144543Z
LAST-MODIFIED:20180213T144543Z
TRANSP:OPAQUE
END:VEVENT
* Redbirds vs. Dodgers
<2018-04-30 Mon 18:35-21:35>
:PROPERTIES:
:ID:       jMZzmZ9d4utBAIM6uDMXKQ1S@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Redbirds vs. Dodgers Redbirds vs. Dodgers

Follow on MiLB First Pitch  https //stza.co/+wmEN-S

Shop  https //stza.co/+wmEN-3f

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Redbirds vs. Dodgers
END:VALARM
DTSTART:20180430T233500Z
DTEND:20180501T023500Z
UID:jMZzmZ9d4utBAIM6uDMXKQ1S@stanza.co
SUMMARY:Redbirds vs. Dodgers
DESCRIPTION:Redbirds vs. Dodgers\n\nFollow on MiLB First Pitch: https://stza.co/+wmEN-S\n\nShop: https://stza.co/+wmEN-3f\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144543Z
LAST-MODIFIED:20180213T144543Z
TRANSP:OPAQUE
END:VEVENT
* Redbirds vs. Dodgers
<2018-05-01 Tue 18:35-21:35>
:PROPERTIES:
:ID:       Q7wGcQpJA5y5UCkCmVRH7lNV@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Redbirds vs. Dodgers Redbirds vs. Dodgers

Follow on MiLB First Pitch  https //stza.co/+wmEP-3a

Shop  https //stza.co/+wmEP-I

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Redbirds vs. Dodgers
END:VALARM
DTSTART:20180501T233500Z
DTEND:20180502T023500Z
UID:Q7wGcQpJA5y5UCkCmVRH7lNV@stanza.co
SUMMARY:Redbirds vs. Dodgers
DESCRIPTION:Redbirds vs. Dodgers\n\nFollow on MiLB First Pitch: https://stza.co/+wmEP-3a\n\nShop: https://stza.co/+wmEP-I\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144543Z
LAST-MODIFIED:20180213T144543Z
TRANSP:OPAQUE
END:VEVENT
* Redbirds vs. Dodgers
<2018-05-02 Wed 18:35-21:35>
:PROPERTIES:
:ID:       qcVUKM_dtJJr27K5F8T14WJN@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Redbirds vs. Dodgers Redbirds vs. Dodgers

Follow on MiLB First Pitch  https //stza.co/+wmER-3t

Shop  https //stza.co/+wmER-14

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Redbirds vs. Dodgers
END:VALARM
DTSTART:20180502T233500Z
DTEND:20180503T023500Z
UID:qcVUKM_dtJJr27K5F8T14WJN@stanza.co
SUMMARY:Redbirds vs. Dodgers
DESCRIPTION:Redbirds vs. Dodgers\n\nFollow on MiLB First Pitch: https://stza.co/+wmER-3t\n\nShop: https://stza.co/+wmER-14\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144543Z
LAST-MODIFIED:20180213T144543Z
TRANSP:OPAQUE
END:VEVENT
* Redbirds vs. Dodgers
<2018-05-03 Thu 19:05-22:05>
:PROPERTIES:
:ID:       3pqfXeVkUevnmLiQiCN8ZEYD@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Redbirds vs. Dodgers Redbirds vs. Dodgers

Follow on MiLB First Pitch  https //stza.co/+wmET-1i

Shop  https //stza.co/+wmET-2A

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Redbirds vs. Dodgers
END:VALARM
DTSTART:20180504T000500Z
DTEND:20180504T030500Z
UID:3pqfXeVkUevnmLiQiCN8ZEYD@stanza.co
SUMMARY:Redbirds vs. Dodgers
DESCRIPTION:Redbirds vs. Dodgers\n\nFollow on MiLB First Pitch: https://stza.co/+wmET-1i\n\nShop: https://stza.co/+wmET-2A\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144543Z
LAST-MODIFIED:20180213T144543Z
TRANSP:OPAQUE
END:VEVENT
* Redbirds @ Sounds
<2018-05-04 Fri 18:35-21:35>
:PROPERTIES:
:ID:       pBkSfpgR3r33Op7KyMXFeUOn@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Redbirds @ Sounds Redbirds @ Sounds

Follow on MiLB First Pitch  https //stza.co/+whFo-1E

Shop  https //stza.co/+whFo-3Q

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Redbirds @ Sounds
END:VALARM
DTSTART:20180504T233500Z
DTEND:20180505T023500Z
UID:pBkSfpgR3r33Op7KyMXFeUOn@stanza.co
SUMMARY:Redbirds @ Sounds
DESCRIPTION:Redbirds @ Sounds\n\nFollow on MiLB First Pitch: https://stza.co/+whFo-1E\n\nShop: https://stza.co/+whFo-3Q\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144543Z
LAST-MODIFIED:20180213T144543Z
TRANSP:OPAQUE
END:VEVENT
* Redbirds @ Sounds
<2018-05-05 Sat 18:35-21:35>
:PROPERTIES:
:ID:       VHN3hQtyCzac0-FSymQ6Y-ze@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Redbirds @ Sounds Redbirds @ Sounds

Follow on MiLB First Pitch  https //stza.co/+whFr-3f

Shop  https //stza.co/+whFr-30

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Redbirds @ Sounds
END:VALARM
DTSTART:20180505T233500Z
DTEND:20180506T023500Z
UID:VHN3hQtyCzac0-FSymQ6Y-ze@stanza.co
SUMMARY:Redbirds @ Sounds
DESCRIPTION:Redbirds @ Sounds\n\nFollow on MiLB First Pitch: https://stza.co/+whFr-3f\n\nShop: https://stza.co/+whFr-30\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144543Z
LAST-MODIFIED:20180213T144543Z
TRANSP:OPAQUE
END:VEVENT
* Redbirds @ Sounds
<2018-05-06 Sun 14:05-17:05>
:PROPERTIES:
:ID:       498v5X8tsBU7_qpH_LIQTKzX@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Redbirds @ Sounds Redbirds @ Sounds

Follow on MiLB First Pitch  https //stza.co/+whFs-1D

Shop  https //stza.co/+whFs-2M

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Redbirds @ Sounds
END:VALARM
DTSTART:20180506T190500Z
DTEND:20180506T220500Z
UID:498v5X8tsBU7_qpH_LIQTKzX@stanza.co
SUMMARY:Redbirds @ Sounds
DESCRIPTION:Redbirds @ Sounds\n\nFollow on MiLB First Pitch: https://stza.co/+whFs-1D\n\nShop: https://stza.co/+whFs-2M\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144543Z
LAST-MODIFIED:20180213T144543Z
TRANSP:OPAQUE
END:VEVENT
* Redbirds @ Sounds
<2018-05-07 Mon 12:05-15:05>
:PROPERTIES:
:ID:       Zppot0osUlcKIDQCp0hdpKGj@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Redbirds @ Sounds Redbirds @ Sounds

Follow on MiLB First Pitch  https //stza.co/+whFt-1m

Shop  https //stza.co/+whFt-3D

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Redbirds @ Sounds
END:VALARM
DTSTART:20180507T170500Z
DTEND:20180507T200500Z
UID:Zppot0osUlcKIDQCp0hdpKGj@stanza.co
SUMMARY:Redbirds @ Sounds
DESCRIPTION:Redbirds @ Sounds\n\nFollow on MiLB First Pitch: https://stza.co/+whFt-1m\n\nShop: https://stza.co/+whFt-3D\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144543Z
LAST-MODIFIED:20180213T144543Z
TRANSP:OPAQUE
END:VEVENT
* Redbirds @ Dodgers
<2018-05-08 Tue 19:05-22:05>
:PROPERTIES:
:ID:       al3a1TSmx7WDgozoIA9opVIO@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Redbirds @ Dodgers Redbirds @ Dodgers

Follow on MiLB First Pitch  https //stza.co/+v$Mt-24

Shop  https //stza.co/+v$Mt-31

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Redbirds @ Dodgers
END:VALARM
DTSTART:20180509T000500Z
DTEND:20180509T030500Z
UID:al3a1TSmx7WDgozoIA9opVIO@stanza.co
SUMMARY:Redbirds @ Dodgers
DESCRIPTION:Redbirds @ Dodgers\n\nFollow on MiLB First Pitch: https://stza.co/+v$Mt-24\n\nShop: https://stza.co/+v$Mt-31\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144543Z
LAST-MODIFIED:20180213T144543Z
TRANSP:OPAQUE
END:VEVENT
* Redbirds @ Dodgers
<2018-05-09 Wed 11:05-14:05>
:PROPERTIES:
:ID:       S3jFB9DD2uKiQRhHVITAMmIy@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Redbirds @ Dodgers Redbirds @ Dodgers

Follow on MiLB First Pitch  https //stza.co/+v$Mu-3L

Shop  https //stza.co/+v$Mu-T

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Redbirds @ Dodgers
END:VALARM
DTSTART:20180509T160500Z
DTEND:20180509T190500Z
UID:S3jFB9DD2uKiQRhHVITAMmIy@stanza.co
SUMMARY:Redbirds @ Dodgers
DESCRIPTION:Redbirds @ Dodgers\n\nFollow on MiLB First Pitch: https://stza.co/+v$Mu-3L\n\nShop: https://stza.co/+v$Mu-T\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144543Z
LAST-MODIFIED:20180213T144543Z
TRANSP:OPAQUE
END:VEVENT
* Redbirds @ Dodgers
<2018-05-10 Thu 19:05-22:05>
:PROPERTIES:
:ID:       LzVeMkKN8GFUBi3XmzX_Zp8B@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Redbirds @ Dodgers Redbirds @ Dodgers

Follow on MiLB First Pitch  https //stza.co/+v$Mv-G

Shop  https //stza.co/+v$Mv-3s

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Redbirds @ Dodgers
END:VALARM
DTSTART:20180511T000500Z
DTEND:20180511T030500Z
UID:LzVeMkKN8GFUBi3XmzX_Zp8B@stanza.co
SUMMARY:Redbirds @ Dodgers
DESCRIPTION:Redbirds @ Dodgers\n\nFollow on MiLB First Pitch: https://stza.co/+v$Mv-G\n\nShop: https://stza.co/+v$Mv-3s\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144543Z
LAST-MODIFIED:20180213T144543Z
TRANSP:OPAQUE
END:VEVENT
* Redbirds @ Dodgers
<2018-05-11 Fri 19:05-22:05>
:PROPERTIES:
:ID:       kVNsCqrZ2bxbUqdIZZZmzekG@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Redbirds @ Dodgers Redbirds @ Dodgers

Follow on MiLB First Pitch  https //stza.co/+v$Mw-2a

Shop  https //stza.co/+v$Mw-3c

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Redbirds @ Dodgers
END:VALARM
DTSTART:20180512T000500Z
DTEND:20180512T030500Z
UID:kVNsCqrZ2bxbUqdIZZZmzekG@stanza.co
SUMMARY:Redbirds @ Dodgers
DESCRIPTION:Redbirds @ Dodgers\n\nFollow on MiLB First Pitch: https://stza.co/+v$Mw-2a\n\nShop: https://stza.co/+v$Mw-3c\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144543Z
LAST-MODIFIED:20180213T144543Z
TRANSP:OPAQUE
END:VEVENT
* Redbirds vs. Sounds
<2018-05-12 Sat 18:35-21:35>
:PROPERTIES:
:ID:       8RoRFq409GNrHs1yROLqZ8Bf@stanza.co
:LOCATION: Postgame Fireworks
:STATUS:   CONFIRMED
:END:

Redbirds vs. Sounds Stick around after the game for an amazing fireworks spectacular, launched up close and personal from center field.

Follow on MiLB First Pitch  https //stza.co/+wmEV-1G

Shop  https //stza.co/+wmEV-3V

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Redbirds vs. Sounds
END:VALARM
DTSTART:20180512T233500Z
DTEND:20180513T023500Z
UID:8RoRFq409GNrHs1yROLqZ8Bf@stanza.co
SUMMARY:Redbirds vs. Sounds
DESCRIPTION:Stick around after the game for an amazing fireworks spectacular, launched up close and personal from center field.\n\nFollow on MiLB First Pitch: https://stza.co/+wmEV-1G\n\nShop: https://stza.co/+wmEV-3V\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Postgame Fireworks
STATUS:CONFIRMED
CREATED:20180213T144543Z
LAST-MODIFIED:20180213T144543Z
TRANSP:OPAQUE
END:VEVENT
* Redbirds vs. Sounds
<2018-05-13 Sun 14:05-17:05>
:PROPERTIES:
:ID:       70r_4A92PwIeMv-XmB8dw9k0@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Redbirds vs. Sounds Redbirds vs. Sounds

Follow on MiLB First Pitch  https //stza.co/+wmEX-s

Shop  https //stza.co/+wmEX-Q

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Redbirds vs. Sounds
END:VALARM
DTSTART:20180513T190500Z
DTEND:20180513T220500Z
UID:70r_4A92PwIeMv-XmB8dw9k0@stanza.co
SUMMARY:Redbirds vs. Sounds
DESCRIPTION:Redbirds vs. Sounds\n\nFollow on MiLB First Pitch: https://stza.co/+wmEX-s\n\nShop: https://stza.co/+wmEX-Q\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144543Z
LAST-MODIFIED:20180213T144543Z
TRANSP:OPAQUE
END:VEVENT
* Redbirds vs. Sounds
<2018-05-14 Mon 11:05-14:05>
:PROPERTIES:
:ID:       xKmvScRB-HH4exK5_Oki-xim@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Redbirds vs. Sounds Redbirds vs. Sounds

Follow on MiLB First Pitch  https //stza.co/+wmEZ-3f

Shop  https //stza.co/+wmEZ-3p

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Redbirds vs. Sounds
END:VALARM
DTSTART:20180514T160500Z
DTEND:20180514T190500Z
UID:xKmvScRB-HH4exK5_Oki-xim@stanza.co
SUMMARY:Redbirds vs. Sounds
DESCRIPTION:Redbirds vs. Sounds\n\nFollow on MiLB First Pitch: https://stza.co/+wmEZ-3f\n\nShop: https://stza.co/+wmEZ-3p\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144543Z
LAST-MODIFIED:20180213T144543Z
TRANSP:OPAQUE
END:VEVENT
* Redbirds vs. Sounds
<2018-05-15 Tue 11:05-14:05>
:PROPERTIES:
:ID:       BFw_c6m_6WY0CZtp49QuSBpA@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Redbirds vs. Sounds Redbirds vs. Sounds

Follow on MiLB First Pitch  https //stza.co/+wmE_-Y

Shop  https //stza.co/+wmE_-2s

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Redbirds vs. Sounds
END:VALARM
DTSTART:20180515T160500Z
DTEND:20180515T190500Z
UID:BFw_c6m_6WY0CZtp49QuSBpA@stanza.co
SUMMARY:Redbirds vs. Sounds
DESCRIPTION:Redbirds vs. Sounds\n\nFollow on MiLB First Pitch: https://stza.co/+wmE_-Y\n\nShop: https://stza.co/+wmE_-2s\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144543Z
LAST-MODIFIED:20180213T144543Z
TRANSP:OPAQUE
END:VEVENT
* Redbirds @ Sky Sox
<2018-05-17 Thu 19:40-22:40>
:PROPERTIES:
:ID:       GjkG9DnPJ97vlzpL2ijvCHYT@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Redbirds @ Sky Sox Redbirds @ Sky Sox

Follow on MiLB First Pitch  https //stza.co/+wmEc-1V

Shop  https //stza.co/+wmEc-3r

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Redbirds @ Sky Sox
END:VALARM
DTSTART:20180518T004000Z
DTEND:20180518T034000Z
UID:GjkG9DnPJ97vlzpL2ijvCHYT@stanza.co
SUMMARY:Redbirds @ Sky Sox
DESCRIPTION:Redbirds @ Sky Sox\n\nFollow on MiLB First Pitch: https://stza.co/+wmEc-1V\n\nShop: https://stza.co/+wmEc-3r\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144543Z
LAST-MODIFIED:20180213T144543Z
TRANSP:OPAQUE
END:VEVENT
* Redbirds @ Sky Sox
<2018-05-18 Fri 19:40-22:40>
:PROPERTIES:
:ID:       0nl2XAR6rMt_zPbYPri_9FkX@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Redbirds @ Sky Sox Redbirds @ Sky Sox

Follow on MiLB First Pitch  https //stza.co/+wmEd-d

Shop  https //stza.co/+wmEd-2J

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Redbirds @ Sky Sox
END:VALARM
DTSTART:20180519T004000Z
DTEND:20180519T034000Z
UID:0nl2XAR6rMt_zPbYPri_9FkX@stanza.co
SUMMARY:Redbirds @ Sky Sox
DESCRIPTION:Redbirds @ Sky Sox\n\nFollow on MiLB First Pitch: https://stza.co/+wmEd-d\n\nShop: https://stza.co/+wmEd-2J\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144543Z
LAST-MODIFIED:20180213T144543Z
TRANSP:OPAQUE
END:VEVENT
* Redbirds @ Sky Sox
<2018-05-19 Sat 19:00-22:00>
:PROPERTIES:
:ID:       5fW8iUECV9uWmgNAiWDptM3R@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Redbirds @ Sky Sox Redbirds @ Sky Sox

Follow on MiLB First Pitch  https //stza.co/+wmEe-H

Shop  https //stza.co/+wmEe-23

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Redbirds @ Sky Sox
END:VALARM
DTSTART:20180520T000000Z
DTEND:20180520T030000Z
UID:5fW8iUECV9uWmgNAiWDptM3R@stanza.co
SUMMARY:Redbirds @ Sky Sox
DESCRIPTION:Redbirds @ Sky Sox\n\nFollow on MiLB First Pitch: https://stza.co/+wmEe-H\n\nShop: https://stza.co/+wmEe-23\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144543Z
LAST-MODIFIED:20180213T144543Z
TRANSP:OPAQUE
END:VEVENT
* Redbirds @ Sky Sox
<2018-05-20 Sun 14:00-17:00>
:PROPERTIES:
:ID:       cnZb2yQ4w0TGj_HcYISskyPR@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Redbirds @ Sky Sox Redbirds @ Sky Sox

Follow on MiLB First Pitch  https //stza.co/+xKKA-I

Shop  https //stza.co/+xKKA-2E

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Redbirds @ Sky Sox
END:VALARM
DTSTART:20180520T190000Z
DTEND:20180520T220000Z
UID:cnZb2yQ4w0TGj_HcYISskyPR@stanza.co
SUMMARY:Redbirds @ Sky Sox
DESCRIPTION:Redbirds @ Sky Sox\n\nFollow on MiLB First Pitch: https://stza.co/+xKKA-I\n\nShop: https://stza.co/+xKKA-2E\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144543Z
LAST-MODIFIED:20180213T144543Z
TRANSP:OPAQUE
END:VEVENT
* Redbirds vs. Dodgers
<2018-05-21 Mon 18:35-21:35>
:PROPERTIES:
:ID:       R1dzBI7QRFOKJJcj8RDBa1Tp@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Redbirds vs. Dodgers Redbirds vs. Dodgers

Follow on MiLB First Pitch  https //stza.co/+wmF0-o

Shop  https //stza.co/+wmF0-2f

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Redbirds vs. Dodgers
END:VALARM
DTSTART:20180521T233500Z
DTEND:20180522T023500Z
UID:R1dzBI7QRFOKJJcj8RDBa1Tp@stanza.co
SUMMARY:Redbirds vs. Dodgers
DESCRIPTION:Redbirds vs. Dodgers\n\nFollow on MiLB First Pitch: https://stza.co/+wmF0-o\n\nShop: https://stza.co/+wmF0-2f\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144543Z
LAST-MODIFIED:20180213T144543Z
TRANSP:OPAQUE
END:VEVENT
* Redbirds vs. Dodgers
<2018-05-22 Tue 11:05-14:05>
:PROPERTIES:
:ID:       6n4k9XTdihu4OGr6aAcZ_FAq@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Redbirds vs. Dodgers Redbirds vs. Dodgers

Follow on MiLB First Pitch  https //stza.co/+wmF2-18

Shop  https //stza.co/+wmF2-1P

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Redbirds vs. Dodgers
END:VALARM
DTSTART:20180522T160500Z
DTEND:20180522T190500Z
UID:6n4k9XTdihu4OGr6aAcZ_FAq@stanza.co
SUMMARY:Redbirds vs. Dodgers
DESCRIPTION:Redbirds vs. Dodgers\n\nFollow on MiLB First Pitch: https://stza.co/+wmF2-18\n\nShop: https://stza.co/+wmF2-1P\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144543Z
LAST-MODIFIED:20180213T144543Z
TRANSP:OPAQUE
END:VEVENT
* Redbirds vs. Dodgers
<2018-05-23 Wed 18:35-21:35>
:PROPERTIES:
:ID:       CS9hr7IQChcTwDhRCf08oMVU@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Redbirds vs. Dodgers Redbirds vs. Dodgers

Follow on MiLB First Pitch  https //stza.co/+wmF4-19

Shop  https //stza.co/+wmF4-1M

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Redbirds vs. Dodgers
END:VALARM
DTSTART:20180523T233500Z
DTEND:20180524T023500Z
UID:CS9hr7IQChcTwDhRCf08oMVU@stanza.co
SUMMARY:Redbirds vs. Dodgers
DESCRIPTION:Redbirds vs. Dodgers\n\nFollow on MiLB First Pitch: https://stza.co/+wmF4-19\n\nShop: https://stza.co/+wmF4-1M\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144543Z
LAST-MODIFIED:20180213T144543Z
TRANSP:OPAQUE
END:VEVENT
* Redbirds vs. Dodgers
<2018-05-24 Thu 19:05-22:05>
:PROPERTIES:
:ID:       jU3R5wFG9UAKzuIT1w_RRbFX@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Redbirds vs. Dodgers Redbirds vs. Dodgers

Follow on MiLB First Pitch  https //stza.co/+wmF7-M

Shop  https //stza.co/+wmF7-1B

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Redbirds vs. Dodgers
END:VALARM
DTSTART:20180525T000500Z
DTEND:20180525T030500Z
UID:jU3R5wFG9UAKzuIT1w_RRbFX@stanza.co
SUMMARY:Redbirds vs. Dodgers
DESCRIPTION:Redbirds vs. Dodgers\n\nFollow on MiLB First Pitch: https://stza.co/+wmF7-M\n\nShop: https://stza.co/+wmF7-1B\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144543Z
LAST-MODIFIED:20180213T144543Z
TRANSP:OPAQUE
END:VEVENT
* Redbirds vs. Sky Sox
<2018-05-25 Fri 19:05-22:05>
:PROPERTIES:
:ID:       igZxWJqvRBbx3WLeOImGBagl@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Redbirds vs. Sky Sox Redbirds vs. Sky Sox

Follow on MiLB First Pitch  https //stza.co/+wmF8-3S

Shop  https //stza.co/+wmF8-3I

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Redbirds vs. Sky Sox
END:VALARM
DTSTART:20180526T000500Z
DTEND:20180526T030500Z
UID:igZxWJqvRBbx3WLeOImGBagl@stanza.co
SUMMARY:Redbirds vs. Sky Sox
DESCRIPTION:Redbirds vs. Sky Sox\n\nFollow on MiLB First Pitch: https://stza.co/+wmF8-3S\n\nShop: https://stza.co/+wmF8-3I\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144543Z
LAST-MODIFIED:20180213T144543Z
TRANSP:OPAQUE
END:VEVENT
* Redbirds vs. Sky Sox
<2018-05-26 Sat 18:35-21:35>
:PROPERTIES:
:ID:       oKTMpn39raL8YSSBEsacOkH9@stanza.co
:LOCATION: Postgame Fireworks
:STATUS:   CONFIRMED
:END:

Redbirds vs. Sky Sox Stick around after the game for an amazing fireworks spectacular, launched up close and personal from center field.

Follow on MiLB First Pitch  https //stza.co/+wmFa-1h

Shop  https //stza.co/+wmFa-23

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Redbirds vs. Sky Sox
END:VALARM
DTSTART:20180526T233500Z
DTEND:20180527T023500Z
UID:oKTMpn39raL8YSSBEsacOkH9@stanza.co
SUMMARY:Redbirds vs. Sky Sox
DESCRIPTION:Stick around after the game for an amazing fireworks spectacular, launched up close and personal from center field.\n\nFollow on MiLB First Pitch: https://stza.co/+wmFa-1h\n\nShop: https://stza.co/+wmFa-23\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Postgame Fireworks
STATUS:CONFIRMED
CREATED:20180213T144543Z
LAST-MODIFIED:20180213T144543Z
TRANSP:OPAQUE
END:VEVENT
* Redbirds vs. Sky Sox
<2018-05-27 Sun 18:35-21:35>
:PROPERTIES:
:ID:       DwLzFe53N_xnCiUoV3HFCOKQ@stanza.co
:LOCATION: Memorial Day Postgame Fireworks
:STATUS:   CONFIRMED
:END:

Redbirds vs. Sky Sox Stick around after the game for a special Memorial Day fireworks spectacular, launched up close and personal from center field.

Follow on MiLB First Pitch  https //stza.co/+wmFd-$

Shop  https //stza.co/+wmFd-2v

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Redbirds vs. Sky Sox
END:VALARM
DTSTART:20180527T233500Z
DTEND:20180528T023500Z
UID:DwLzFe53N_xnCiUoV3HFCOKQ@stanza.co
SUMMARY:Redbirds vs. Sky Sox
DESCRIPTION:Stick around after the game for a special Memorial Day fireworks spectacular, launched up close and personal from center field.\n\nFollow on MiLB First Pitch: https://stza.co/+wmFd-$\n\nShop: https://stza.co/+wmFd-2v\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Memorial Day Postgame Fireworks
STATUS:CONFIRMED
CREATED:20180213T144543Z
LAST-MODIFIED:20180213T144543Z
TRANSP:OPAQUE
END:VEVENT
* Redbirds vs. Sky Sox
<2018-05-28 Mon 13:05-16:05>
:PROPERTIES:
:ID:       Jam3o360uqf3u2miqKo04JT9@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Redbirds vs. Sky Sox Redbirds vs. Sky Sox

Follow on MiLB First Pitch  https //stza.co/+wmFf-2F

Shop  https //stza.co/+wmFf-a

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Redbirds vs. Sky Sox
END:VALARM
DTSTART:20180528T180500Z
DTEND:20180528T210500Z
UID:Jam3o360uqf3u2miqKo04JT9@stanza.co
SUMMARY:Redbirds vs. Sky Sox
DESCRIPTION:Redbirds vs. Sky Sox\n\nFollow on MiLB First Pitch: https://stza.co/+wmFf-2F\n\nShop: https://stza.co/+wmFf-a\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144543Z
LAST-MODIFIED:20180213T144543Z
TRANSP:OPAQUE
END:VEVENT
* Redbirds vs. Sky Sox
<2018-05-29 Tue 12:05-15:05>
:PROPERTIES:
:ID:       L0xY--uZeMfVKXMt-15iJej5@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Redbirds vs. Sky Sox Redbirds vs. Sky Sox

Follow on MiLB First Pitch  https //stza.co/+wmFh-3e

Shop  https //stza.co/+wmFh-G

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Redbirds vs. Sky Sox
END:VALARM
DTSTART:20180529T170500Z
DTEND:20180529T200500Z
UID:L0xY--uZeMfVKXMt-15iJej5@stanza.co
SUMMARY:Redbirds vs. Sky Sox
DESCRIPTION:Redbirds vs. Sky Sox\n\nFollow on MiLB First Pitch: https://stza.co/+wmFh-3e\n\nShop: https://stza.co/+wmFh-G\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144543Z
LAST-MODIFIED:20180213T144543Z
TRANSP:OPAQUE
END:VEVENT
* Redbirds @ Baby Cakes
<2018-05-30 Wed 19:00-22:00>
:PROPERTIES:
:ID:       jr3ZEyKCIpygOccuoToNWxnw@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Redbirds @ Baby Cakes Redbirds @ Baby Cakes

Follow on MiLB First Pitch  https //stza.co/+whFB-3i

Shop  https //stza.co/+whFB-a

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Redbirds @ Baby Cakes
END:VALARM
DTSTART:20180531T000000Z
DTEND:20180531T030000Z
UID:jr3ZEyKCIpygOccuoToNWxnw@stanza.co
SUMMARY:Redbirds @ Baby Cakes
DESCRIPTION:Redbirds @ Baby Cakes\n\nFollow on MiLB First Pitch: https://stza.co/+whFB-3i\n\nShop: https://stza.co/+whFB-a\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144543Z
LAST-MODIFIED:20180213T144543Z
TRANSP:OPAQUE
END:VEVENT
* Redbirds @ Baby Cakes
<2018-05-31 Thu 19:00-22:00>
:PROPERTIES:
:ID:       6BLtNfBUhQ6o8HkXSP4H9MCH@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Redbirds @ Baby Cakes Redbirds @ Baby Cakes

Follow on MiLB First Pitch  https //stza.co/+whFC-1R

Shop  https //stza.co/+whFC-X

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Redbirds @ Baby Cakes
END:VALARM
DTSTART:20180601T000000Z
DTEND:20180601T030000Z
UID:6BLtNfBUhQ6o8HkXSP4H9MCH@stanza.co
SUMMARY:Redbirds @ Baby Cakes
DESCRIPTION:Redbirds @ Baby Cakes\n\nFollow on MiLB First Pitch: https://stza.co/+whFC-1R\n\nShop: https://stza.co/+whFC-X\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144543Z
LAST-MODIFIED:20180213T144543Z
TRANSP:OPAQUE
END:VEVENT
* Redbirds @ Baby Cakes
<2018-06-01 Fri 19:00-22:00>
:PROPERTIES:
:ID:       lyp3fYAGhh3ZR-GKbATomZJh@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Redbirds @ Baby Cakes Redbirds @ Baby Cakes

Follow on MiLB First Pitch  https //stza.co/+whFD-1t

Shop  https //stza.co/+whFD-Q

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Redbirds @ Baby Cakes
END:VALARM
DTSTART:20180602T000000Z
DTEND:20180602T030000Z
UID:lyp3fYAGhh3ZR-GKbATomZJh@stanza.co
SUMMARY:Redbirds @ Baby Cakes
DESCRIPTION:Redbirds @ Baby Cakes\n\nFollow on MiLB First Pitch: https://stza.co/+whFD-1t\n\nShop: https://stza.co/+whFD-Q\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144543Z
LAST-MODIFIED:20180213T144543Z
TRANSP:OPAQUE
END:VEVENT
* Redbirds @ Baby Cakes
<2018-06-02 Sat 18:00-21:00>
:PROPERTIES:
:ID:       wdhZry8D1Zau6FwGI1aZ_ReJ@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Redbirds @ Baby Cakes Redbirds @ Baby Cakes

Follow on MiLB First Pitch  https //stza.co/+whFE-C

Shop  https //stza.co/+whFE-r

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Redbirds @ Baby Cakes
END:VALARM
DTSTART:20180602T230000Z
DTEND:20180603T020000Z
UID:wdhZry8D1Zau6FwGI1aZ_ReJ@stanza.co
SUMMARY:Redbirds @ Baby Cakes
DESCRIPTION:Redbirds @ Baby Cakes\n\nFollow on MiLB First Pitch: https://stza.co/+whFE-C\n\nShop: https://stza.co/+whFE-r\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144543Z
LAST-MODIFIED:20180213T144543Z
TRANSP:OPAQUE
END:VEVENT
* Redbirds @ Baby Cakes
<2018-06-03 Sun 13:00-16:00>
:PROPERTIES:
:ID:       WmrFmjHYpfWJw8nALWx6pW4F@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Redbirds @ Baby Cakes Redbirds @ Baby Cakes

Follow on MiLB First Pitch  https //stza.co/+whFF-J

Shop  https //stza.co/+whFF-2

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Redbirds @ Baby Cakes
END:VALARM
DTSTART:20180603T180000Z
DTEND:20180603T210000Z
UID:WmrFmjHYpfWJw8nALWx6pW4F@stanza.co
SUMMARY:Redbirds @ Baby Cakes
DESCRIPTION:Redbirds @ Baby Cakes\n\nFollow on MiLB First Pitch: https://stza.co/+whFF-J\n\nShop: https://stza.co/+whFF-2\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144543Z
LAST-MODIFIED:20180213T144543Z
TRANSP:OPAQUE
END:VEVENT
* Redbirds vs. Rainiers
<2018-06-05 Tue 19:05-22:05>
:PROPERTIES:
:ID:       Vg9SUCjNR-tp642iL36ZI4nw@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Redbirds vs. Rainiers Redbirds vs. Rainiers

Follow on MiLB First Pitch  https //stza.co/+wmFj-34

Shop  https //stza.co/+wmFj-3a

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Redbirds vs. Rainiers
END:VALARM
DTSTART:20180606T000500Z
DTEND:20180606T030500Z
UID:Vg9SUCjNR-tp642iL36ZI4nw@stanza.co
SUMMARY:Redbirds vs. Rainiers
DESCRIPTION:Redbirds vs. Rainiers\n\nFollow on MiLB First Pitch: https://stza.co/+wmFj-34\n\nShop: https://stza.co/+wmFj-3a\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144543Z
LAST-MODIFIED:20180213T144543Z
TRANSP:OPAQUE
END:VEVENT
* Redbirds vs. Rainiers
<2018-06-06 Wed 19:05-22:05>
:PROPERTIES:
:ID:       9i2WWm7q48ukAwsEiyTQtuM9@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Redbirds vs. Rainiers Redbirds vs. Rainiers

Follow on MiLB First Pitch  https //stza.co/+wmFl-12

Shop  https //stza.co/+wmFl-1a

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Redbirds vs. Rainiers
END:VALARM
DTSTART:20180607T000500Z
DTEND:20180607T030500Z
UID:9i2WWm7q48ukAwsEiyTQtuM9@stanza.co
SUMMARY:Redbirds vs. Rainiers
DESCRIPTION:Redbirds vs. Rainiers\n\nFollow on MiLB First Pitch: https://stza.co/+wmFl-12\n\nShop: https://stza.co/+wmFl-1a\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144543Z
LAST-MODIFIED:20180213T144543Z
TRANSP:OPAQUE
END:VEVENT
* Redbirds vs. Rainiers
<2018-06-07 Thu 19:05-22:05>
:PROPERTIES:
:ID:       CIqOTlrDDEQVdtFMVBr8kyot@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Redbirds vs. Rainiers Redbirds vs. Rainiers

Follow on MiLB First Pitch  https //stza.co/+wmFo-n

Shop  https //stza.co/+wmFo-3A

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Redbirds vs. Rainiers
END:VALARM
DTSTART:20180608T000500Z
DTEND:20180608T030500Z
UID:CIqOTlrDDEQVdtFMVBr8kyot@stanza.co
SUMMARY:Redbirds vs. Rainiers
DESCRIPTION:Redbirds vs. Rainiers\n\nFollow on MiLB First Pitch: https://stza.co/+wmFo-n\n\nShop: https://stza.co/+wmFo-3A\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144543Z
LAST-MODIFIED:20180213T144543Z
TRANSP:OPAQUE
END:VEVENT
* Redbirds vs. Aces
<2018-06-08 Fri 19:05-22:05>
:PROPERTIES:
:ID:       oVjAhggUCKJkgTIJwTd38EdO@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Redbirds vs. Aces Redbirds vs. Aces

Follow on MiLB First Pitch  https //stza.co/+wmFq-3X

Shop  https //stza.co/+wmFq-3x

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Redbirds vs. Aces
END:VALARM
DTSTART:20180609T000500Z
DTEND:20180609T030500Z
UID:oVjAhggUCKJkgTIJwTd38EdO@stanza.co
SUMMARY:Redbirds vs. Aces
DESCRIPTION:Redbirds vs. Aces\n\nFollow on MiLB First Pitch: https://stza.co/+wmFq-3X\n\nShop: https://stza.co/+wmFq-3x\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144543Z
LAST-MODIFIED:20180213T144543Z
TRANSP:OPAQUE
END:VEVENT
* Redbirds vs. Aces
<2018-06-09 Sat 18:35-21:35>
:PROPERTIES:
:ID:       04ws5Ugt6lblgk_dXsTBRgD5@stanza.co
:LOCATION: Postgame Fireworks
:STATUS:   CONFIRMED
:END:

Redbirds vs. Aces Stick around after the game for an amazing fireworks spectacular, launched up close and personal from center field.

Follow on MiLB First Pitch  https //stza.co/+wmFs-1p

Shop  https //stza.co/+wmFs-1u

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Redbirds vs. Aces
END:VALARM
DTSTART:20180609T233500Z
DTEND:20180610T023500Z
UID:04ws5Ugt6lblgk_dXsTBRgD5@stanza.co
SUMMARY:Redbirds vs. Aces
DESCRIPTION:Stick around after the game for an amazing fireworks spectacular, launched up close and personal from center field.\n\nFollow on MiLB First Pitch: https://stza.co/+wmFs-1p\n\nShop: https://stza.co/+wmFs-1u\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Postgame Fireworks
STATUS:CONFIRMED
CREATED:20180213T144543Z
LAST-MODIFIED:20180213T144543Z
TRANSP:OPAQUE
END:VEVENT
* Redbirds vs. Aces
<2018-06-10 Sun 14:05-17:05>
:PROPERTIES:
:ID:       eS0hlADjCEROwuZQPRQn6BMU@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Redbirds vs. Aces Redbirds vs. Aces

Follow on MiLB First Pitch  https //stza.co/+wmFt-1C

Shop  https //stza.co/+wmFt-2T

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Redbirds vs. Aces
END:VALARM
DTSTART:20180610T190500Z
DTEND:20180610T220500Z
UID:eS0hlADjCEROwuZQPRQn6BMU@stanza.co
SUMMARY:Redbirds vs. Aces
DESCRIPTION:Redbirds vs. Aces\n\nFollow on MiLB First Pitch: https://stza.co/+wmFt-1C\n\nShop: https://stza.co/+wmFt-2T\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144543Z
LAST-MODIFIED:20180213T144543Z
TRANSP:OPAQUE
END:VEVENT
* Redbirds vs. Aces
<2018-06-11 Mon 12:05-15:05>
:PROPERTIES:
:ID:       F4KpVL0-LRWscR9pHEykJygI@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Redbirds vs. Aces Redbirds vs. Aces

Follow on MiLB First Pitch  https //stza.co/+wmFw-q

Shop  https //stza.co/+wmFw-1d

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Redbirds vs. Aces
END:VALARM
DTSTART:20180611T170500Z
DTEND:20180611T200500Z
UID:F4KpVL0-LRWscR9pHEykJygI@stanza.co
SUMMARY:Redbirds vs. Aces
DESCRIPTION:Redbirds vs. Aces\n\nFollow on MiLB First Pitch: https://stza.co/+wmFw-q\n\nShop: https://stza.co/+wmFw-1d\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144543Z
LAST-MODIFIED:20180213T144543Z
TRANSP:OPAQUE
END:VEVENT
* Redbirds @ Isotopes
<2018-06-13 Wed 19:35-22:35>
:PROPERTIES:
:ID:       DSc6MZdro1rV6uWN6JQR0IIx@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Redbirds @ Isotopes Redbirds @ Isotopes

Follow on MiLB First Pitch  https //stza.co/+whFj-1A

Shop  https //stza.co/+whFj-1y

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Redbirds @ Isotopes
END:VALARM
DTSTART:20180614T003500Z
DTEND:20180614T033500Z
UID:DSc6MZdro1rV6uWN6JQR0IIx@stanza.co
SUMMARY:Redbirds @ Isotopes
DESCRIPTION:Redbirds @ Isotopes\n\nFollow on MiLB First Pitch: https://stza.co/+whFj-1A\n\nShop: https://stza.co/+whFj-1y\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144543Z
LAST-MODIFIED:20180213T144543Z
TRANSP:OPAQUE
END:VEVENT
* Redbirds @ Isotopes
<2018-06-14 Thu 19:35-22:35>
:PROPERTIES:
:ID:       J5_6pJO4v8Li0K88jG5W1LmZ@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Redbirds @ Isotopes Redbirds @ Isotopes

Follow on MiLB First Pitch  https //stza.co/+whFk-1Y

Shop  https //stza.co/+whFk-3n

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Redbirds @ Isotopes
END:VALARM
DTSTART:20180615T003500Z
DTEND:20180615T033500Z
UID:J5_6pJO4v8Li0K88jG5W1LmZ@stanza.co
SUMMARY:Redbirds @ Isotopes
DESCRIPTION:Redbirds @ Isotopes\n\nFollow on MiLB First Pitch: https://stza.co/+whFk-1Y\n\nShop: https://stza.co/+whFk-3n\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144543Z
LAST-MODIFIED:20180213T144543Z
TRANSP:OPAQUE
END:VEVENT
* Redbirds @ Isotopes
<2018-06-15 Fri 19:35-22:35>
:PROPERTIES:
:ID:       MojwQdk3QWpiyoc4zj63thS7@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Redbirds @ Isotopes Redbirds @ Isotopes

Follow on MiLB First Pitch  https //stza.co/+whFl-1

Shop  https //stza.co/+whFl-1W

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Redbirds @ Isotopes
END:VALARM
DTSTART:20180616T003500Z
DTEND:20180616T033500Z
UID:MojwQdk3QWpiyoc4zj63thS7@stanza.co
SUMMARY:Redbirds @ Isotopes
DESCRIPTION:Redbirds @ Isotopes\n\nFollow on MiLB First Pitch: https://stza.co/+whFl-1\n\nShop: https://stza.co/+whFl-1W\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144543Z
LAST-MODIFIED:20180213T144543Z
TRANSP:OPAQUE
END:VEVENT
* Redbirds @ Chihuahuas
<2018-06-16 Sat 20:05-23:05>
:PROPERTIES:
:ID:       U_mgdiVQC5Sq1sFpqguU5UZC@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Redbirds @ Chihuahuas Redbirds @ Chihuahuas

Follow on MiLB First Pitch  https //stza.co/+wmEk-Z

Shop  https //stza.co/+wmEk-1r

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Redbirds @ Chihuahuas
END:VALARM
DTSTART:20180617T010500Z
DTEND:20180617T040500Z
UID:U_mgdiVQC5Sq1sFpqguU5UZC@stanza.co
SUMMARY:Redbirds @ Chihuahuas
DESCRIPTION:Redbirds @ Chihuahuas\n\nFollow on MiLB First Pitch: https://stza.co/+wmEk-Z\n\nShop: https://stza.co/+wmEk-1r\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144543Z
LAST-MODIFIED:20180213T144543Z
TRANSP:OPAQUE
END:VEVENT
* Redbirds @ Chihuahuas
<2018-06-17 Sun 19:05-22:05>
:PROPERTIES:
:ID:       tx5sOnXFBBkliEGFOGVRWlmC@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Redbirds @ Chihuahuas Redbirds @ Chihuahuas

Follow on MiLB First Pitch  https //stza.co/+wmEl-2a

Shop  https //stza.co/+wmEl-1t

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Redbirds @ Chihuahuas
END:VALARM
DTSTART:20180618T000500Z
DTEND:20180618T030500Z
UID:tx5sOnXFBBkliEGFOGVRWlmC@stanza.co
SUMMARY:Redbirds @ Chihuahuas
DESCRIPTION:Redbirds @ Chihuahuas\n\nFollow on MiLB First Pitch: https://stza.co/+wmEl-2a\n\nShop: https://stza.co/+wmEl-1t\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144543Z
LAST-MODIFIED:20180213T144543Z
TRANSP:OPAQUE
END:VEVENT
* Redbirds @ Chihuahuas
<2018-06-18 Mon 20:05-23:05>
:PROPERTIES:
:ID:       8A-w9WbHMXGRfXeouiaCLTcI@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Redbirds @ Chihuahuas Redbirds @ Chihuahuas

Follow on MiLB First Pitch  https //stza.co/+wmEm-1a

Shop  https //stza.co/+wmEm-3i

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Redbirds @ Chihuahuas
END:VALARM
DTSTART:20180619T010500Z
DTEND:20180619T040500Z
UID:8A-w9WbHMXGRfXeouiaCLTcI@stanza.co
SUMMARY:Redbirds @ Chihuahuas
DESCRIPTION:Redbirds @ Chihuahuas\n\nFollow on MiLB First Pitch: https://stza.co/+wmEm-1a\n\nShop: https://stza.co/+wmEm-3i\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144543Z
LAST-MODIFIED:20180213T144543Z
TRANSP:OPAQUE
END:VEVENT
* Redbirds @ Chihuahuas
<2018-06-19 Tue 20:05-23:05>
:PROPERTIES:
:ID:       e2XmOLLG3_wX2KF0L4KNFYoF@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Redbirds @ Chihuahuas Redbirds @ Chihuahuas

Follow on MiLB First Pitch  https //stza.co/+wmEn-1z

Shop  https //stza.co/+wmEn-J

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Redbirds @ Chihuahuas
END:VALARM
DTSTART:20180620T010500Z
DTEND:20180620T040500Z
UID:e2XmOLLG3_wX2KF0L4KNFYoF@stanza.co
SUMMARY:Redbirds @ Chihuahuas
DESCRIPTION:Redbirds @ Chihuahuas\n\nFollow on MiLB First Pitch: https://stza.co/+wmEn-1z\n\nShop: https://stza.co/+wmEn-J\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144543Z
LAST-MODIFIED:20180213T144543Z
TRANSP:OPAQUE
END:VEVENT
* Redbirds vs. Baby Cakes
<2018-06-21 Thu 19:05-22:05>
:PROPERTIES:
:ID:       XOjCd4WW-jq1rnLi9zcQuduw@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Redbirds vs. Baby Cakes Redbirds vs. Baby Cakes

Follow on MiLB First Pitch  https //stza.co/+wmFx-3b

Shop  https //stza.co/+wmFx-2C

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Redbirds vs. Baby Cakes
END:VALARM
DTSTART:20180622T000500Z
DTEND:20180622T030500Z
UID:XOjCd4WW-jq1rnLi9zcQuduw@stanza.co
SUMMARY:Redbirds vs. Baby Cakes
DESCRIPTION:Redbirds vs. Baby Cakes\n\nFollow on MiLB First Pitch: https://stza.co/+wmFx-3b\n\nShop: https://stza.co/+wmFx-2C\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144543Z
LAST-MODIFIED:20180213T144543Z
TRANSP:OPAQUE
END:VEVENT
* Redbirds vs. Baby Cakes
<2018-06-22 Fri 19:05-22:05>
:PROPERTIES:
:ID:       dLg1l9ezcJwd25nnImoudP2a@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Redbirds vs. Baby Cakes Redbirds vs. Baby Cakes

Follow on MiLB First Pitch  https //stza.co/+wmFA-27

Shop  https //stza.co/+wmFA-2R

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Redbirds vs. Baby Cakes
END:VALARM
DTSTART:20180623T000500Z
DTEND:20180623T030500Z
UID:dLg1l9ezcJwd25nnImoudP2a@stanza.co
SUMMARY:Redbirds vs. Baby Cakes
DESCRIPTION:Redbirds vs. Baby Cakes\n\nFollow on MiLB First Pitch: https://stza.co/+wmFA-27\n\nShop: https://stza.co/+wmFA-2R\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144543Z
LAST-MODIFIED:20180213T144543Z
TRANSP:OPAQUE
END:VEVENT
* Redbirds vs. Baby Cakes
<2018-06-23 Sat 18:35-21:35>
:PROPERTIES:
:ID:       EcJo9FkAmSIbMjCFIvoGMvv4@stanza.co
:LOCATION: Postgame Fireworks
:STATUS:   CONFIRMED
:END:

Redbirds vs. Baby Cakes Stick around after the game for an amazing fireworks spectacular, launched up close and personal from center field.

Follow on MiLB First Pitch  https //stza.co/+wmFC-o

Shop  https //stza.co/+wmFC-Q

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Redbirds vs. Baby Cakes
END:VALARM
DTSTART:20180623T233500Z
DTEND:20180624T023500Z
UID:EcJo9FkAmSIbMjCFIvoGMvv4@stanza.co
SUMMARY:Redbirds vs. Baby Cakes
DESCRIPTION:Stick around after the game for an amazing fireworks spectacular, launched up close and personal from center field.\n\nFollow on MiLB First Pitch: https://stza.co/+wmFC-o\n\nShop: https://stza.co/+wmFC-Q\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Postgame Fireworks
STATUS:CONFIRMED
CREATED:20180213T144543Z
LAST-MODIFIED:20180213T144543Z
TRANSP:OPAQUE
END:VEVENT
* Redbirds vs. Baby Cakes
<2018-06-24 Sun 14:05-17:05>
:PROPERTIES:
:ID:       8Vp9eSNhDKGf95nLiSqq9NTi@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Redbirds vs. Baby Cakes Redbirds vs. Baby Cakes

Follow on MiLB First Pitch  https //stza.co/+wmFD-3J

Shop  https //stza.co/+wmFD-2m

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Redbirds vs. Baby Cakes
END:VALARM
DTSTART:20180624T190500Z
DTEND:20180624T220500Z
UID:8Vp9eSNhDKGf95nLiSqq9NTi@stanza.co
SUMMARY:Redbirds vs. Baby Cakes
DESCRIPTION:Redbirds vs. Baby Cakes\n\nFollow on MiLB First Pitch: https://stza.co/+wmFD-3J\n\nShop: https://stza.co/+wmFD-2m\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144543Z
LAST-MODIFIED:20180213T144543Z
TRANSP:OPAQUE
END:VEVENT
* Redbirds @ Sky Sox
<2018-06-25 Mon 19:40-22:40>
:PROPERTIES:
:ID:       X6dDXkMLlBrcBMu3lDXnqYLV@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Redbirds @ Sky Sox Redbirds @ Sky Sox

Follow on MiLB First Pitch  https //stza.co/+wmEg-38

Shop  https //stza.co/+wmEg-Q

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Redbirds @ Sky Sox
END:VALARM
DTSTART:20180626T004000Z
DTEND:20180626T034000Z
UID:X6dDXkMLlBrcBMu3lDXnqYLV@stanza.co
SUMMARY:Redbirds @ Sky Sox
DESCRIPTION:Redbirds @ Sky Sox\n\nFollow on MiLB First Pitch: https://stza.co/+wmEg-38\n\nShop: https://stza.co/+wmEg-Q\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144543Z
LAST-MODIFIED:20180213T144543Z
TRANSP:OPAQUE
END:VEVENT
* Redbirds @ Sky Sox
<2018-06-26 Tue 19:40-22:40>
:PROPERTIES:
:ID:       lMCbQYRCgIM_nLDjFSW-Rla6@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Redbirds @ Sky Sox Redbirds @ Sky Sox

Follow on MiLB First Pitch  https //stza.co/+wmEh-3i

Shop  https //stza.co/+wmEh-29

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Redbirds @ Sky Sox
END:VALARM
DTSTART:20180627T004000Z
DTEND:20180627T034000Z
UID:lMCbQYRCgIM_nLDjFSW-Rla6@stanza.co
SUMMARY:Redbirds @ Sky Sox
DESCRIPTION:Redbirds @ Sky Sox\n\nFollow on MiLB First Pitch: https://stza.co/+wmEh-3i\n\nShop: https://stza.co/+wmEh-29\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144543Z
LAST-MODIFIED:20180213T144543Z
TRANSP:OPAQUE
END:VEVENT
* Redbirds @ Sky Sox
<2018-06-27 Wed 13:30-16:30>
:PROPERTIES:
:ID:       xbYNlVQM5xgHI-jBQtYDHt2O@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Redbirds @ Sky Sox Redbirds @ Sky Sox

Follow on MiLB First Pitch  https //stza.co/+wmEi-O

Shop  https //stza.co/+wmEi-1R

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Redbirds @ Sky Sox
END:VALARM
DTSTART:20180627T183000Z
DTEND:20180627T213000Z
UID:xbYNlVQM5xgHI-jBQtYDHt2O@stanza.co
SUMMARY:Redbirds @ Sky Sox
DESCRIPTION:Redbirds @ Sky Sox\n\nFollow on MiLB First Pitch: https://stza.co/+wmEi-O\n\nShop: https://stza.co/+wmEi-1R\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144543Z
LAST-MODIFIED:20180213T144543Z
TRANSP:OPAQUE
END:VEVENT
* Redbirds @ Sky Sox
<2018-06-28 Thu 19:40-22:40>
:PROPERTIES:
:ID:       dQx6D4F8HPgRaxOItV_4jH3D@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Redbirds @ Sky Sox Redbirds @ Sky Sox

Follow on MiLB First Pitch  https //stza.co/+wmEj-3W

Shop  https //stza.co/+wmEj-17

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Redbirds @ Sky Sox
END:VALARM
DTSTART:20180629T004000Z
DTEND:20180629T034000Z
UID:dQx6D4F8HPgRaxOItV_4jH3D@stanza.co
SUMMARY:Redbirds @ Sky Sox
DESCRIPTION:Redbirds @ Sky Sox\n\nFollow on MiLB First Pitch: https://stza.co/+wmEj-3W\n\nShop: https://stza.co/+wmEj-17\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144543Z
LAST-MODIFIED:20180213T144543Z
TRANSP:OPAQUE
END:VEVENT
* Redbirds @ Cubs
<2018-06-29 Fri 19:08-22:08>
:PROPERTIES:
:ID:       AJdnror899_AaylvXVl12tBc@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Redbirds @ Cubs Redbirds @ Cubs

Follow on MiLB First Pitch  https //stza.co/+v1CC-z

Shop  https //stza.co/+v1CC-e

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Redbirds @ Cubs
END:VALARM
DTSTART:20180630T000800Z
DTEND:20180630T030800Z
UID:AJdnror899_AaylvXVl12tBc@stanza.co
SUMMARY:Redbirds @ Cubs
DESCRIPTION:Redbirds @ Cubs\n\nFollow on MiLB First Pitch: https://stza.co/+v1CC-z\n\nShop: https://stza.co/+v1CC-e\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144543Z
LAST-MODIFIED:20180213T144543Z
TRANSP:OPAQUE
END:VEVENT
* Redbirds @ Cubs
<2018-06-30 Sat 19:08-22:08>
:PROPERTIES:
:ID:       u_pOBHmsxv2ndya7sa5Np5Se@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Redbirds @ Cubs Redbirds @ Cubs

Follow on MiLB First Pitch  https //stza.co/+v1CD-2R

Shop  https //stza.co/+v1CD-1E

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Redbirds @ Cubs
END:VALARM
DTSTART:20180701T000800Z
DTEND:20180701T030800Z
UID:u_pOBHmsxv2ndya7sa5Np5Se@stanza.co
SUMMARY:Redbirds @ Cubs
DESCRIPTION:Redbirds @ Cubs\n\nFollow on MiLB First Pitch: https://stza.co/+v1CD-2R\n\nShop: https://stza.co/+v1CD-1E\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144543Z
LAST-MODIFIED:20180213T144543Z
TRANSP:OPAQUE
END:VEVENT
* Redbirds @ Cubs
<2018-07-01 Sun 13:08-16:08>
:PROPERTIES:
:ID:       csYh7RjJnG1FGS5TX-IY6Emu@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Redbirds @ Cubs Redbirds @ Cubs

Follow on MiLB First Pitch  https //stza.co/+wHsQ-1W

Shop  https //stza.co/+wHsQ-2q

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Redbirds @ Cubs
END:VALARM
DTSTART:20180701T180800Z
DTEND:20180701T210800Z
UID:csYh7RjJnG1FGS5TX-IY6Emu@stanza.co
SUMMARY:Redbirds @ Cubs
DESCRIPTION:Redbirds @ Cubs\n\nFollow on MiLB First Pitch: https://stza.co/+wHsQ-1W\n\nShop: https://stza.co/+wHsQ-2q\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144543Z
LAST-MODIFIED:20180213T144543Z
TRANSP:OPAQUE
END:VEVENT
* Redbirds @ Cubs
<2018-07-02 Mon 19:08-22:08>
:PROPERTIES:
:ID:       PKIzu0q3Hi0Y2jHvW3lw3se0@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Redbirds @ Cubs Redbirds @ Cubs

Follow on MiLB First Pitch  https //stza.co/+v1CF-37

Shop  https //stza.co/+v1CF-31

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Redbirds @ Cubs
END:VALARM
DTSTART:20180703T000800Z
DTEND:20180703T030800Z
UID:PKIzu0q3Hi0Y2jHvW3lw3se0@stanza.co
SUMMARY:Redbirds @ Cubs
DESCRIPTION:Redbirds @ Cubs\n\nFollow on MiLB First Pitch: https://stza.co/+v1CF-37\n\nShop: https://stza.co/+v1CF-31\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144543Z
LAST-MODIFIED:20180213T144543Z
TRANSP:OPAQUE
END:VEVENT
* Redbirds @ Cubs
<2018-07-03 Tue 19:08-22:08>
:PROPERTIES:
:ID:       MFZeCordID5mhcQZmZypg02V@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Redbirds @ Cubs Redbirds @ Cubs

Follow on MiLB First Pitch  https //stza.co/+v1CG-K

Shop  https //stza.co/+v1CG-r

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Redbirds @ Cubs
END:VALARM
DTSTART:20180704T000800Z
DTEND:20180704T030800Z
UID:MFZeCordID5mhcQZmZypg02V@stanza.co
SUMMARY:Redbirds @ Cubs
DESCRIPTION:Redbirds @ Cubs\n\nFollow on MiLB First Pitch: https://stza.co/+v1CG-K\n\nShop: https://stza.co/+v1CG-r\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144543Z
LAST-MODIFIED:20180213T144543Z
TRANSP:OPAQUE
END:VEVENT
* Redbirds vs. Storm Chasers
<2018-07-04 Wed 18:35-21:35>
:PROPERTIES:
:ID:       kO0vFWgERA1pbOdRQqi1igsT@stanza.co
:LOCATION: Independence Day Postgame Fireworks
:STATUS:   CONFIRMED
:END:

Redbirds vs. Storm Chasers Stick around after the game for a special Independence Day fireworks spectacular, launched up close and personal from center field.

Follow on MiLB First Pitch  https //stza.co/+wmFG-3f

Shop  https //stza.co/+wmFG-_

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Redbirds vs. Storm Chasers
END:VALARM
DTSTART:20180704T233500Z
DTEND:20180705T023500Z
UID:kO0vFWgERA1pbOdRQqi1igsT@stanza.co
SUMMARY:Redbirds vs. Storm Chasers
DESCRIPTION:Stick around after the game for a special Independence Day fireworks spectacular, launched up close and personal from center field.\n\nFollow on MiLB First Pitch: https://stza.co/+wmFG-3f\n\nShop: https://stza.co/+wmFG-_\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Independence Day Postgame Fireworks
STATUS:CONFIRMED
CREATED:20180213T144543Z
LAST-MODIFIED:20180213T144543Z
TRANSP:OPAQUE
END:VEVENT
* Redbirds vs. Storm Chasers
<2018-07-05 Thu 19:05-22:05>
:PROPERTIES:
:ID:       iHT-FyFDrDX0qOG6gU4WCf0u@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Redbirds vs. Storm Chasers Redbirds vs. Storm Chasers

Follow on MiLB First Pitch  https //stza.co/+wmFI-3e

Shop  https //stza.co/+wmFI-2o

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Redbirds vs. Storm Chasers
END:VALARM
DTSTART:20180706T000500Z
DTEND:20180706T030500Z
UID:iHT-FyFDrDX0qOG6gU4WCf0u@stanza.co
SUMMARY:Redbirds vs. Storm Chasers
DESCRIPTION:Redbirds vs. Storm Chasers\n\nFollow on MiLB First Pitch: https://stza.co/+wmFI-3e\n\nShop: https://stza.co/+wmFI-2o\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144543Z
LAST-MODIFIED:20180213T144543Z
TRANSP:OPAQUE
END:VEVENT
* Redbirds vs. Storm Chasers
<2018-07-06 Fri 19:05-22:05>
:PROPERTIES:
:ID:       BlouadYZuBvq-2fp3gIVDCWK@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Redbirds vs. Storm Chasers Redbirds vs. Storm Chasers

Follow on MiLB First Pitch  https //stza.co/+wmFK-14

Shop  https //stza.co/+wmFK-1y

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Redbirds vs. Storm Chasers
END:VALARM
DTSTART:20180707T000500Z
DTEND:20180707T030500Z
UID:BlouadYZuBvq-2fp3gIVDCWK@stanza.co
SUMMARY:Redbirds vs. Storm Chasers
DESCRIPTION:Redbirds vs. Storm Chasers\n\nFollow on MiLB First Pitch: https://stza.co/+wmFK-14\n\nShop: https://stza.co/+wmFK-1y\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144543Z
LAST-MODIFIED:20180213T144543Z
TRANSP:OPAQUE
END:VEVENT
* Redbirds vs. Storm Chasers
<2018-07-07 Sat 18:35-21:35>
:PROPERTIES:
:ID:       W7qjD6-uPaWt5D5-13Y03_vJ@stanza.co
:LOCATION: Postgame Fireworks
:STATUS:   CONFIRMED
:END:

Redbirds vs. Storm Chasers Stick around after the game for an amazing fireworks spectacular, launched up close and personal from center field.

Follow on MiLB First Pitch  https //stza.co/+wmFL-3A

Shop  https //stza.co/+wmFL-3D

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Redbirds vs. Storm Chasers
END:VALARM
DTSTART:20180707T233500Z
DTEND:20180708T023500Z
UID:W7qjD6-uPaWt5D5-13Y03_vJ@stanza.co
SUMMARY:Redbirds vs. Storm Chasers
DESCRIPTION:Stick around after the game for an amazing fireworks spectacular, launched up close and personal from center field.\n\nFollow on MiLB First Pitch: https://stza.co/+wmFL-3A\n\nShop: https://stza.co/+wmFL-3D\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Postgame Fireworks
STATUS:CONFIRMED
CREATED:20180213T144543Z
LAST-MODIFIED:20180213T144543Z
TRANSP:OPAQUE
END:VEVENT
* Redbirds vs. Storm Chasers
<2018-07-08 Sun 14:05-17:05>
:PROPERTIES:
:ID:       2KjoFFP_IEN2MTrDmb-Luuuq@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Redbirds vs. Storm Chasers Redbirds vs. Storm Chasers

Follow on MiLB First Pitch  https //stza.co/+wmFO-6

Shop  https //stza.co/+wmFO-3B

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Redbirds vs. Storm Chasers
END:VALARM
DTSTART:20180708T190500Z
DTEND:20180708T220500Z
UID:2KjoFFP_IEN2MTrDmb-Luuuq@stanza.co
SUMMARY:Redbirds vs. Storm Chasers
DESCRIPTION:Redbirds vs. Storm Chasers\n\nFollow on MiLB First Pitch: https://stza.co/+wmFO-6\n\nShop: https://stza.co/+wmFO-3B\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144543Z
LAST-MODIFIED:20180213T144543Z
TRANSP:OPAQUE
END:VEVENT
* Redbirds @ Storm Chasers
<2018-07-12 Thu 19:05-22:05>
:PROPERTIES:
:ID:       xYOMC2hFeBcdJcfO19lCvCmJ@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Redbirds @ Storm Chasers Redbirds @ Storm Chasers

Follow on MiLB First Pitch  https //stza.co/+whFO-9

Shop  https //stza.co/+whFO-2D

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Redbirds @ Storm Chasers
END:VALARM
DTSTART:20180713T000500Z
DTEND:20180713T030500Z
UID:xYOMC2hFeBcdJcfO19lCvCmJ@stanza.co
SUMMARY:Redbirds @ Storm Chasers
DESCRIPTION:Redbirds @ Storm Chasers\n\nFollow on MiLB First Pitch: https://stza.co/+whFO-9\n\nShop: https://stza.co/+whFO-2D\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144543Z
LAST-MODIFIED:20180213T144543Z
TRANSP:OPAQUE
END:VEVENT
* Redbirds @ Storm Chasers
<2018-07-13 Fri 19:05-22:05>
:PROPERTIES:
:ID:       NT2FcAG4XGs6F_tUfRGy3Vnq@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Redbirds @ Storm Chasers Redbirds @ Storm Chasers

Follow on MiLB First Pitch  https //stza.co/+whFP-2j

Shop  https //stza.co/+whFP-2O

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Redbirds @ Storm Chasers
END:VALARM
DTSTART:20180714T000500Z
DTEND:20180714T030500Z
UID:NT2FcAG4XGs6F_tUfRGy3Vnq@stanza.co
SUMMARY:Redbirds @ Storm Chasers
DESCRIPTION:Redbirds @ Storm Chasers\n\nFollow on MiLB First Pitch: https://stza.co/+whFP-2j\n\nShop: https://stza.co/+whFP-2O\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144543Z
LAST-MODIFIED:20180213T144543Z
TRANSP:OPAQUE
END:VEVENT
* Redbirds @ Storm Chasers
<2018-07-14 Sat 19:05-22:05>
:PROPERTIES:
:ID:       NU9L-HFVf4Q68nYQ6zBkHxfz@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Redbirds @ Storm Chasers Redbirds @ Storm Chasers

Follow on MiLB First Pitch  https //stza.co/+whFQ-I

Shop  https //stza.co/+whFQ-25

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Redbirds @ Storm Chasers
END:VALARM
DTSTART:20180715T000500Z
DTEND:20180715T030500Z
UID:NU9L-HFVf4Q68nYQ6zBkHxfz@stanza.co
SUMMARY:Redbirds @ Storm Chasers
DESCRIPTION:Redbirds @ Storm Chasers\n\nFollow on MiLB First Pitch: https://stza.co/+whFQ-I\n\nShop: https://stza.co/+whFQ-25\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144543Z
LAST-MODIFIED:20180213T144543Z
TRANSP:OPAQUE
END:VEVENT
* Redbirds @ Storm Chasers
<2018-07-15 Sun 14:05-17:05>
:PROPERTIES:
:ID:       3pAlLFmgazi-JVB3oAv_bbUc@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Redbirds @ Storm Chasers Redbirds @ Storm Chasers

Follow on MiLB First Pitch  https //stza.co/+whFR-1J

Shop  https //stza.co/+whFR-1G

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Redbirds @ Storm Chasers
END:VALARM
DTSTART:20180715T190500Z
DTEND:20180715T220500Z
UID:3pAlLFmgazi-JVB3oAv_bbUc@stanza.co
SUMMARY:Redbirds @ Storm Chasers
DESCRIPTION:Redbirds @ Storm Chasers\n\nFollow on MiLB First Pitch: https://stza.co/+whFR-1J\n\nShop: https://stza.co/+whFR-1G\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144543Z
LAST-MODIFIED:20180213T144543Z
TRANSP:OPAQUE
END:VEVENT
* Redbirds vs. Cubs
<2018-07-16 Mon 19:05-22:05>
:PROPERTIES:
:ID:       wcElcdPMsEGTlkrYsU-Fp6Rr@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Redbirds vs. Cubs Redbirds vs. Cubs

Follow on MiLB First Pitch  https //stza.co/+wmFQ-Q

Shop  https //stza.co/+wmFQ-1b

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Redbirds vs. Cubs
END:VALARM
DTSTART:20180717T000500Z
DTEND:20180717T030500Z
UID:wcElcdPMsEGTlkrYsU-Fp6Rr@stanza.co
SUMMARY:Redbirds vs. Cubs
DESCRIPTION:Redbirds vs. Cubs\n\nFollow on MiLB First Pitch: https://stza.co/+wmFQ-Q\n\nShop: https://stza.co/+wmFQ-1b\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144543Z
LAST-MODIFIED:20180213T144543Z
TRANSP:OPAQUE
END:VEVENT
* Redbirds vs. Cubs
<2018-07-17 Tue 19:05-22:05>
:PROPERTIES:
:ID:       IBDPLh_vP7gH10vwthuc2IEa@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Redbirds vs. Cubs Redbirds vs. Cubs

Follow on MiLB First Pitch  https //stza.co/+wmFS-2Y

Shop  https //stza.co/+wmFS-2p

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Redbirds vs. Cubs
END:VALARM
DTSTART:20180718T000500Z
DTEND:20180718T030500Z
UID:IBDPLh_vP7gH10vwthuc2IEa@stanza.co
SUMMARY:Redbirds vs. Cubs
DESCRIPTION:Redbirds vs. Cubs\n\nFollow on MiLB First Pitch: https://stza.co/+wmFS-2Y\n\nShop: https://stza.co/+wmFS-2p\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144543Z
LAST-MODIFIED:20180213T144543Z
TRANSP:OPAQUE
END:VEVENT
* Redbirds vs. Cubs
<2018-07-18 Wed 19:05-22:05>
:PROPERTIES:
:ID:       kfTJpL9k1NbfcMWTJiR9b_ku@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Redbirds vs. Cubs Redbirds vs. Cubs

Follow on MiLB First Pitch  https //stza.co/+wmFU-6

Shop  https //stza.co/+wmFU-2D

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Redbirds vs. Cubs
END:VALARM
DTSTART:20180719T000500Z
DTEND:20180719T030500Z
UID:kfTJpL9k1NbfcMWTJiR9b_ku@stanza.co
SUMMARY:Redbirds vs. Cubs
DESCRIPTION:Redbirds vs. Cubs\n\nFollow on MiLB First Pitch: https://stza.co/+wmFU-6\n\nShop: https://stza.co/+wmFU-2D\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144543Z
LAST-MODIFIED:20180213T144543Z
TRANSP:OPAQUE
END:VEVENT
* Redbirds vs. Cubs
<2018-07-19 Thu 19:05-22:05>
:PROPERTIES:
:ID:       2W1JbV8shaC_xXPFQNp0cVTs@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Redbirds vs. Cubs Redbirds vs. Cubs

Follow on MiLB First Pitch  https //stza.co/+wmFW-3y

Shop  https //stza.co/+wmFW-2i

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Redbirds vs. Cubs
END:VALARM
DTSTART:20180720T000500Z
DTEND:20180720T030500Z
UID:2W1JbV8shaC_xXPFQNp0cVTs@stanza.co
SUMMARY:Redbirds vs. Cubs
DESCRIPTION:Redbirds vs. Cubs\n\nFollow on MiLB First Pitch: https://stza.co/+wmFW-3y\n\nShop: https://stza.co/+wmFW-2i\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144543Z
LAST-MODIFIED:20180213T144543Z
TRANSP:OPAQUE
END:VEVENT
* Redbirds vs. Sky Sox
<2018-07-20 Fri 19:05-22:05>
:PROPERTIES:
:ID:       6vlHjfuMvx_LRb5EuGEpv7Yd@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Redbirds vs. Sky Sox Redbirds vs. Sky Sox

Follow on MiLB First Pitch  https //stza.co/+wmFY-38

Shop  https //stza.co/+wmFY-19

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Redbirds vs. Sky Sox
END:VALARM
DTSTART:20180721T000500Z
DTEND:20180721T030500Z
UID:6vlHjfuMvx_LRb5EuGEpv7Yd@stanza.co
SUMMARY:Redbirds vs. Sky Sox
DESCRIPTION:Redbirds vs. Sky Sox\n\nFollow on MiLB First Pitch: https://stza.co/+wmFY-38\n\nShop: https://stza.co/+wmFY-19\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144543Z
LAST-MODIFIED:20180213T144543Z
TRANSP:OPAQUE
END:VEVENT
* Redbirds vs. Sky Sox
<2018-07-21 Sat 18:35-21:35>
:PROPERTIES:
:ID:       Vvu5xlXcz0gi0KCMBFiCdei4@stanza.co
:LOCATION: Postgame Fireworks
:STATUS:   CONFIRMED
:END:

Redbirds vs. Sky Sox Stick around after the game for an amazing fireworks spectacular, launched up close and personal from center field.

Follow on MiLB First Pitch  https //stza.co/+wmF_-3v

Shop  https //stza.co/+wmF_-Y

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Redbirds vs. Sky Sox
END:VALARM
DTSTART:20180721T233500Z
DTEND:20180722T023500Z
UID:Vvu5xlXcz0gi0KCMBFiCdei4@stanza.co
SUMMARY:Redbirds vs. Sky Sox
DESCRIPTION:Stick around after the game for an amazing fireworks spectacular, launched up close and personal from center field.\n\nFollow on MiLB First Pitch: https://stza.co/+wmF_-3v\n\nShop: https://stza.co/+wmF_-Y\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Postgame Fireworks
STATUS:CONFIRMED
CREATED:20180213T144543Z
LAST-MODIFIED:20180213T144543Z
TRANSP:OPAQUE
END:VEVENT
* Redbirds vs. Sky Sox
<2018-07-22 Sun 14:05-17:05>
:PROPERTIES:
:ID:       jjolDLKiMNC00SiziGp-Fuu4@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Redbirds vs. Sky Sox Redbirds vs. Sky Sox

Follow on MiLB First Pitch  https //stza.co/+wmG0-1j

Shop  https //stza.co/+wmG0-1r

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Redbirds vs. Sky Sox
END:VALARM
DTSTART:20180722T190500Z
DTEND:20180722T220500Z
UID:jjolDLKiMNC00SiziGp-Fuu4@stanza.co
SUMMARY:Redbirds vs. Sky Sox
DESCRIPTION:Redbirds vs. Sky Sox\n\nFollow on MiLB First Pitch: https://stza.co/+wmG0-1j\n\nShop: https://stza.co/+wmG0-1r\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144543Z
LAST-MODIFIED:20180213T144543Z
TRANSP:OPAQUE
END:VEVENT
* Redbirds @ Bees
<2018-07-24 Tue 19:35-22:35>
:PROPERTIES:
:ID:       TqCZS2HE0ow_l4d1ymRvh6d2@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Redbirds @ Bees Redbirds @ Bees

Follow on MiLB First Pitch  https //stza.co/+wmGD-3Q

Shop  https //stza.co/+wmGD-33

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Redbirds @ Bees
END:VALARM
DTSTART:20180725T003500Z
DTEND:20180725T033500Z
UID:TqCZS2HE0ow_l4d1ymRvh6d2@stanza.co
SUMMARY:Redbirds @ Bees
DESCRIPTION:Redbirds @ Bees\n\nFollow on MiLB First Pitch: https://stza.co/+wmGD-3Q\n\nShop: https://stza.co/+wmGD-33\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144543Z
LAST-MODIFIED:20180213T144543Z
TRANSP:OPAQUE
END:VEVENT
* Redbirds @ Bees
<2018-07-25 Wed 20:05-23:05>
:PROPERTIES:
:ID:       HzrpEXM5yC5-o8wUHMUsyzDq@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Redbirds @ Bees Redbirds @ Bees

Follow on MiLB First Pitch  https //stza.co/+wmGE-g

Shop  https //stza.co/+wmGE-2h

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Redbirds @ Bees
END:VALARM
DTSTART:20180726T010500Z
DTEND:20180726T040500Z
UID:HzrpEXM5yC5-o8wUHMUsyzDq@stanza.co
SUMMARY:Redbirds @ Bees
DESCRIPTION:Redbirds @ Bees\n\nFollow on MiLB First Pitch: https://stza.co/+wmGE-g\n\nShop: https://stza.co/+wmGE-2h\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144543Z
LAST-MODIFIED:20180213T144543Z
TRANSP:OPAQUE
END:VEVENT
* Redbirds @ Bees
<2018-07-26 Thu 20:05-23:05>
:PROPERTIES:
:ID:       Doqz1zFhqqJs1HUGNEs5hkXX@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Redbirds @ Bees Redbirds @ Bees

Follow on MiLB First Pitch  https //stza.co/+wmGF-2q

Shop  https //stza.co/+wmGF-3m

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Redbirds @ Bees
END:VALARM
DTSTART:20180727T010500Z
DTEND:20180727T040500Z
UID:Doqz1zFhqqJs1HUGNEs5hkXX@stanza.co
SUMMARY:Redbirds @ Bees
DESCRIPTION:Redbirds @ Bees\n\nFollow on MiLB First Pitch: https://stza.co/+wmGF-2q\n\nShop: https://stza.co/+wmGF-3m\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144543Z
LAST-MODIFIED:20180213T144543Z
TRANSP:OPAQUE
END:VEVENT
* Redbirds @ 51s
<2018-07-27 Fri 21:05>--<2018-07-28 Sat 00:05>
:PROPERTIES:
:ID:       ftq-LWW6NwyiIIFG8jjmfjD4@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Redbirds @ 51s Redbirds @ 51s

Follow on MiLB First Pitch  https //stza.co/+v1CH-a

Shop  https //stza.co/+v1CH-6

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Redbirds @ 51s
END:VALARM
DTSTART:20180728T020500Z
DTEND:20180728T050500Z
UID:ftq-LWW6NwyiIIFG8jjmfjD4@stanza.co
SUMMARY:Redbirds @ 51s
DESCRIPTION:Redbirds @ 51s\n\nFollow on MiLB First Pitch: https://stza.co/+v1CH-a\n\nShop: https://stza.co/+v1CH-6\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144543Z
LAST-MODIFIED:20180213T144543Z
TRANSP:OPAQUE
END:VEVENT
* Redbirds @ 51s
<2018-07-28 Sat 21:05>--<2018-07-29 Sun 00:05>
:PROPERTIES:
:ID:       oVDSKrlp9Wl68uaNFM9QvuM4@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Redbirds @ 51s Redbirds @ 51s

Follow on MiLB First Pitch  https //stza.co/+v1CI-i

Shop  https //stza.co/+v1CI-1o

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Redbirds @ 51s
END:VALARM
DTSTART:20180729T020500Z
DTEND:20180729T050500Z
UID:oVDSKrlp9Wl68uaNFM9QvuM4@stanza.co
SUMMARY:Redbirds @ 51s
DESCRIPTION:Redbirds @ 51s\n\nFollow on MiLB First Pitch: https://stza.co/+v1CI-i\n\nShop: https://stza.co/+v1CI-1o\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144543Z
LAST-MODIFIED:20180213T144543Z
TRANSP:OPAQUE
END:VEVENT
* Redbirds @ 51s
<2018-07-29 Sun 21:05>--<2018-07-30 Mon 00:05>
:PROPERTIES:
:ID:       X1eS8dDkBM943kEK9G9kazzJ@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Redbirds @ 51s Redbirds @ 51s

Follow on MiLB First Pitch  https //stza.co/+v1CJ-U

Shop  https //stza.co/+v1CJ-2L

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Redbirds @ 51s
END:VALARM
DTSTART:20180730T020500Z
DTEND:20180730T050500Z
UID:X1eS8dDkBM943kEK9G9kazzJ@stanza.co
SUMMARY:Redbirds @ 51s
DESCRIPTION:Redbirds @ 51s\n\nFollow on MiLB First Pitch: https://stza.co/+v1CJ-U\n\nShop: https://stza.co/+v1CJ-2L\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144543Z
LAST-MODIFIED:20180213T144543Z
TRANSP:OPAQUE
END:VEVENT
* Redbirds @ 51s
<2018-07-30 Mon 21:05>--<2018-07-31 Tue 00:05>
:PROPERTIES:
:ID:       qov8PSFwkIZA9CC4_8kiB_fS@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Redbirds @ 51s Redbirds @ 51s

Follow on MiLB First Pitch  https //stza.co/+v1CK-11

Shop  https //stza.co/+v1CK-3l

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Redbirds @ 51s
END:VALARM
DTSTART:20180731T020500Z
DTEND:20180731T050500Z
UID:qov8PSFwkIZA9CC4_8kiB_fS@stanza.co
SUMMARY:Redbirds @ 51s
DESCRIPTION:Redbirds @ 51s\n\nFollow on MiLB First Pitch: https://stza.co/+v1CK-11\n\nShop: https://stza.co/+v1CK-3l\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144543Z
LAST-MODIFIED:20180213T144543Z
TRANSP:OPAQUE
END:VEVENT
* Redbirds vs. River Cats
<2018-08-01 Wed 19:05-22:05>
:PROPERTIES:
:ID:       QQWViFmxcGzF2yajbZWYFKAy@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Redbirds vs. River Cats Redbirds vs. River Cats

Follow on MiLB First Pitch  https //stza.co/+wmG3-1v

Shop  https //stza.co/+wmG3-$

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Redbirds vs. River Cats
END:VALARM
DTSTART:20180802T000500Z
DTEND:20180802T030500Z
UID:QQWViFmxcGzF2yajbZWYFKAy@stanza.co
SUMMARY:Redbirds vs. River Cats
DESCRIPTION:Redbirds vs. River Cats\n\nFollow on MiLB First Pitch: https://stza.co/+wmG3-1v\n\nShop: https://stza.co/+wmG3-$\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144543Z
LAST-MODIFIED:20180213T144543Z
TRANSP:OPAQUE
END:VEVENT
* Redbirds vs. River Cats
<2018-08-02 Thu 19:05-22:05>
:PROPERTIES:
:ID:       gJ-7V7st6GwE_D8cl1v1-e3H@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Redbirds vs. River Cats Redbirds vs. River Cats

Follow on MiLB First Pitch  https //stza.co/+wmG5-2C

Shop  https //stza.co/+wmG5-k

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Redbirds vs. River Cats
END:VALARM
DTSTART:20180803T000500Z
DTEND:20180803T030500Z
UID:gJ-7V7st6GwE_D8cl1v1-e3H@stanza.co
SUMMARY:Redbirds vs. River Cats
DESCRIPTION:Redbirds vs. River Cats\n\nFollow on MiLB First Pitch: https://stza.co/+wmG5-2C\n\nShop: https://stza.co/+wmG5-k\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144543Z
LAST-MODIFIED:20180213T144543Z
TRANSP:OPAQUE
END:VEVENT
* Redbirds vs. River Cats
<2018-08-03 Fri 19:05-22:05>
:PROPERTIES:
:ID:       J3LLPFIGavIdIj_9ZgOUask1@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Redbirds vs. River Cats Redbirds vs. River Cats

Follow on MiLB First Pitch  https //stza.co/+wmG6-2W

Shop  https //stza.co/+wmG6-2i

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Redbirds vs. River Cats
END:VALARM
DTSTART:20180804T000500Z
DTEND:20180804T030500Z
UID:J3LLPFIGavIdIj_9ZgOUask1@stanza.co
SUMMARY:Redbirds vs. River Cats
DESCRIPTION:Redbirds vs. River Cats\n\nFollow on MiLB First Pitch: https://stza.co/+wmG6-2W\n\nShop: https://stza.co/+wmG6-2i\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144543Z
LAST-MODIFIED:20180213T144543Z
TRANSP:OPAQUE
END:VEVENT
* Redbirds vs. Grizzlies
<2018-08-04 Sat 18:35-21:35>
:PROPERTIES:
:ID:       TYrOJvq8qdHe4K4dTg2w5Lg2@stanza.co
:LOCATION: Postgame Fireworks
:STATUS:   CONFIRMED
:END:

Redbirds vs. Grizzlies Stick around after the game for an amazing fireworks spectacular, launched up close and personal from center field.

Follow on MiLB First Pitch  https //stza.co/+wmG8-2Z

Shop  https //stza.co/+wmG8-34

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Redbirds vs. Grizzlies
END:VALARM
DTSTART:20180804T233500Z
DTEND:20180805T023500Z
UID:TYrOJvq8qdHe4K4dTg2w5Lg2@stanza.co
SUMMARY:Redbirds vs. Grizzlies
DESCRIPTION:Stick around after the game for an amazing fireworks spectacular, launched up close and personal from center field.\n\nFollow on MiLB First Pitch: https://stza.co/+wmG8-2Z\n\nShop: https://stza.co/+wmG8-34\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Postgame Fireworks
STATUS:CONFIRMED
CREATED:20180213T144543Z
LAST-MODIFIED:20180213T144543Z
TRANSP:OPAQUE
END:VEVENT
* Redbirds vs. Grizzlies
<2018-08-05 Sun 14:05-17:05>
:PROPERTIES:
:ID:       s5kDXQAE9LZSAdOyTRTUDt2d@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Redbirds vs. Grizzlies Redbirds vs. Grizzlies

Follow on MiLB First Pitch  https //stza.co/+wmGa-3B

Shop  https //stza.co/+wmGa-2I

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Redbirds vs. Grizzlies
END:VALARM
DTSTART:20180805T190500Z
DTEND:20180805T220500Z
UID:s5kDXQAE9LZSAdOyTRTUDt2d@stanza.co
SUMMARY:Redbirds vs. Grizzlies
DESCRIPTION:Redbirds vs. Grizzlies\n\nFollow on MiLB First Pitch: https://stza.co/+wmGa-3B\n\nShop: https://stza.co/+wmGa-2I\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144543Z
LAST-MODIFIED:20180213T144543Z
TRANSP:OPAQUE
END:VEVENT
* Redbirds vs. Grizzlies
<2018-08-06 Mon 18:35-21:35>
:PROPERTIES:
:ID:       pGyoneiHf-sEVGhdsvTb6P6d@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Redbirds vs. Grizzlies Redbirds vs. Grizzlies

Follow on MiLB First Pitch  https //stza.co/+wmGc-2r

Shop  https //stza.co/+wmGc-33

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Redbirds vs. Grizzlies
END:VALARM
DTSTART:20180806T233500Z
DTEND:20180807T023500Z
UID:pGyoneiHf-sEVGhdsvTb6P6d@stanza.co
SUMMARY:Redbirds vs. Grizzlies
DESCRIPTION:Redbirds vs. Grizzlies\n\nFollow on MiLB First Pitch: https://stza.co/+wmGc-2r\n\nShop: https://stza.co/+wmGc-33\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144543Z
LAST-MODIFIED:20180213T144543Z
TRANSP:OPAQUE
END:VEVENT
* Redbirds vs. Grizzlies
<2018-08-07 Tue 18:35-21:35>
:PROPERTIES:
:ID:       mh9HeH9SJ4q9vxkiKqeTf1d7@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Redbirds vs. Grizzlies Redbirds vs. Grizzlies

Follow on MiLB First Pitch  https //stza.co/+wmGf-S

Shop  https //stza.co/+wmGf-2X

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Redbirds vs. Grizzlies
END:VALARM
DTSTART:20180807T233500Z
DTEND:20180808T023500Z
UID:mh9HeH9SJ4q9vxkiKqeTf1d7@stanza.co
SUMMARY:Redbirds vs. Grizzlies
DESCRIPTION:Redbirds vs. Grizzlies\n\nFollow on MiLB First Pitch: https://stza.co/+wmGf-S\n\nShop: https://stza.co/+wmGf-2X\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144543Z
LAST-MODIFIED:20180213T144543Z
TRANSP:OPAQUE
END:VEVENT
* Redbirds @ Dodgers
<2018-08-09 Thu 19:05-22:05>
:PROPERTIES:
:ID:       0mGf8W-aJtVdeRwUiSsKYnry@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Redbirds @ Dodgers Redbirds @ Dodgers

Follow on MiLB First Pitch  https //stza.co/+v$Mx-3H

Shop  https //stza.co/+v$Mx-E

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Redbirds @ Dodgers
END:VALARM
DTSTART:20180810T000500Z
DTEND:20180810T030500Z
UID:0mGf8W-aJtVdeRwUiSsKYnry@stanza.co
SUMMARY:Redbirds @ Dodgers
DESCRIPTION:Redbirds @ Dodgers\n\nFollow on MiLB First Pitch: https://stza.co/+v$Mx-3H\n\nShop: https://stza.co/+v$Mx-E\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144543Z
LAST-MODIFIED:20180213T144543Z
TRANSP:OPAQUE
END:VEVENT
* Redbirds @ Dodgers
<2018-08-10 Fri 19:05-22:05>
:PROPERTIES:
:ID:       rpW_NBKYz2DBGMP9VOFr_XGD@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Redbirds @ Dodgers Redbirds @ Dodgers

Follow on MiLB First Pitch  https //stza.co/+v$My-2K

Shop  https //stza.co/+v$My-2A

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Redbirds @ Dodgers
END:VALARM
DTSTART:20180811T000500Z
DTEND:20180811T030500Z
UID:rpW_NBKYz2DBGMP9VOFr_XGD@stanza.co
SUMMARY:Redbirds @ Dodgers
DESCRIPTION:Redbirds @ Dodgers\n\nFollow on MiLB First Pitch: https://stza.co/+v$My-2K\n\nShop: https://stza.co/+v$My-2A\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144543Z
LAST-MODIFIED:20180213T144543Z
TRANSP:OPAQUE
END:VEVENT
* Redbirds @ Dodgers
<2018-08-11 Sat 19:05-22:05>
:PROPERTIES:
:ID:       sJQBP3Ufk1caLWkT6lNAUO_u@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Redbirds @ Dodgers Redbirds @ Dodgers

Follow on MiLB First Pitch  https //stza.co/+v$Mz-2Z

Shop  https //stza.co/+v$Mz-1g

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Redbirds @ Dodgers
END:VALARM
DTSTART:20180812T000500Z
DTEND:20180812T030500Z
UID:sJQBP3Ufk1caLWkT6lNAUO_u@stanza.co
SUMMARY:Redbirds @ Dodgers
DESCRIPTION:Redbirds @ Dodgers\n\nFollow on MiLB First Pitch: https://stza.co/+v$Mz-2Z\n\nShop: https://stza.co/+v$Mz-1g\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144543Z
LAST-MODIFIED:20180213T144543Z
TRANSP:OPAQUE
END:VEVENT
* Redbirds @ Dodgers
<2018-08-12 Sun 18:05-21:05>
:PROPERTIES:
:ID:       Y8CQWKJ_5Eswqj5OeKFccBgT@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Redbirds @ Dodgers Redbirds @ Dodgers

Follow on MiLB First Pitch  https //stza.co/+v$MA-26

Shop  https //stza.co/+v$MA-1Y

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Redbirds @ Dodgers
END:VALARM
DTSTART:20180812T230500Z
DTEND:20180813T020500Z
UID:Y8CQWKJ_5Eswqj5OeKFccBgT@stanza.co
SUMMARY:Redbirds @ Dodgers
DESCRIPTION:Redbirds @ Dodgers\n\nFollow on MiLB First Pitch: https://stza.co/+v$MA-26\n\nShop: https://stza.co/+v$MA-1Y\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144543Z
LAST-MODIFIED:20180213T144543Z
TRANSP:OPAQUE
END:VEVENT
* Redbirds vs. Baby Cakes
<2018-08-13 Mon 18:35-21:35>
:PROPERTIES:
:ID:       BO-aJ4db3bE101BqQs9fUSxH@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Redbirds vs. Baby Cakes Redbirds vs. Baby Cakes

Follow on MiLB First Pitch  https //stza.co/+wmGg-3f

Shop  https //stza.co/+wmGg-K

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Redbirds vs. Baby Cakes
END:VALARM
DTSTART:20180813T233500Z
DTEND:20180814T023500Z
UID:BO-aJ4db3bE101BqQs9fUSxH@stanza.co
SUMMARY:Redbirds vs. Baby Cakes
DESCRIPTION:Redbirds vs. Baby Cakes\n\nFollow on MiLB First Pitch: https://stza.co/+wmGg-3f\n\nShop: https://stza.co/+wmGg-K\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144543Z
LAST-MODIFIED:20180213T144543Z
TRANSP:OPAQUE
END:VEVENT
* Redbirds vs. Baby Cakes
<2018-08-14 Tue 18:35-21:35>
:PROPERTIES:
:ID:       dK7wQ8b6jBDWGI51RRmYOsXi@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Redbirds vs. Baby Cakes Redbirds vs. Baby Cakes

Follow on MiLB First Pitch  https //stza.co/+wmGi-g

Shop  https //stza.co/+wmGi-h

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Redbirds vs. Baby Cakes
END:VALARM
DTSTART:20180814T233500Z
DTEND:20180815T023500Z
UID:dK7wQ8b6jBDWGI51RRmYOsXi@stanza.co
SUMMARY:Redbirds vs. Baby Cakes
DESCRIPTION:Redbirds vs. Baby Cakes\n\nFollow on MiLB First Pitch: https://stza.co/+wmGi-g\n\nShop: https://stza.co/+wmGi-h\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144543Z
LAST-MODIFIED:20180213T144543Z
TRANSP:OPAQUE
END:VEVENT
* Redbirds vs. Baby Cakes
<2018-08-15 Wed 18:35-21:35>
:PROPERTIES:
:ID:       DX5Jr3SdKJKoHqmmdOY_QEHG@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Redbirds vs. Baby Cakes Redbirds vs. Baby Cakes

Follow on MiLB First Pitch  https //stza.co/+wmGl-1V

Shop  https //stza.co/+wmGl-n

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Redbirds vs. Baby Cakes
END:VALARM
DTSTART:20180815T233500Z
DTEND:20180816T023500Z
UID:DX5Jr3SdKJKoHqmmdOY_QEHG@stanza.co
SUMMARY:Redbirds vs. Baby Cakes
DESCRIPTION:Redbirds vs. Baby Cakes\n\nFollow on MiLB First Pitch: https://stza.co/+wmGl-1V\n\nShop: https://stza.co/+wmGl-n\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144543Z
LAST-MODIFIED:20180213T144543Z
TRANSP:OPAQUE
END:VEVENT
* Redbirds vs. Baby Cakes
<2018-08-16 Thu 19:05-22:05>
:PROPERTIES:
:ID:       kd9C_peCmzqEASq_lZ4hIbUc@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Redbirds vs. Baby Cakes Redbirds vs. Baby Cakes

Follow on MiLB First Pitch  https //stza.co/+wmGn-3Q

Shop  https //stza.co/+wmGn-1L

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Redbirds vs. Baby Cakes
END:VALARM
DTSTART:20180817T000500Z
DTEND:20180817T030500Z
UID:kd9C_peCmzqEASq_lZ4hIbUc@stanza.co
SUMMARY:Redbirds vs. Baby Cakes
DESCRIPTION:Redbirds vs. Baby Cakes\n\nFollow on MiLB First Pitch: https://stza.co/+wmGn-3Q\n\nShop: https://stza.co/+wmGn-1L\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144543Z
LAST-MODIFIED:20180213T144543Z
TRANSP:OPAQUE
END:VEVENT
* Redbirds vs. Express
<2018-08-17 Fri 19:05-22:05>
:PROPERTIES:
:ID:       8nK7--UZVuXU2mZH6wVgjR9X@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Redbirds vs. Express Redbirds vs. Express

Follow on MiLB First Pitch  https //stza.co/+wmGp-G

Shop  https //stza.co/+wmGp-2t

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Redbirds vs. Express
END:VALARM
DTSTART:20180818T000500Z
DTEND:20180818T030500Z
UID:8nK7--UZVuXU2mZH6wVgjR9X@stanza.co
SUMMARY:Redbirds vs. Express
DESCRIPTION:Redbirds vs. Express\n\nFollow on MiLB First Pitch: https://stza.co/+wmGp-G\n\nShop: https://stza.co/+wmGp-2t\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144543Z
LAST-MODIFIED:20180213T144543Z
TRANSP:OPAQUE
END:VEVENT
* Redbirds vs. Express
<2018-08-18 Sat 18:35-21:35>
:PROPERTIES:
:ID:       wT5HMDxFxRrzx7ApwhGJJcXT@stanza.co
:LOCATION: Postgame Fireworks
:STATUS:   CONFIRMED
:END:

Redbirds vs. Express Stick around after the game for an amazing fireworks spectacular, launched up close and personal from center field.

Follow on MiLB First Pitch  https //stza.co/+wmGq-19

Shop  https //stza.co/+wmGq-b

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Redbirds vs. Express
END:VALARM
DTSTART:20180818T233500Z
DTEND:20180819T023500Z
UID:wT5HMDxFxRrzx7ApwhGJJcXT@stanza.co
SUMMARY:Redbirds vs. Express
DESCRIPTION:Stick around after the game for an amazing fireworks spectacular, launched up close and personal from center field.\n\nFollow on MiLB First Pitch: https://stza.co/+wmGq-19\n\nShop: https://stza.co/+wmGq-b\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Postgame Fireworks
STATUS:CONFIRMED
CREATED:20180213T144543Z
LAST-MODIFIED:20180213T144543Z
TRANSP:OPAQUE
END:VEVENT
* Redbirds vs. Express
<2018-08-19 Sun 14:05-17:05>
:PROPERTIES:
:ID:       OE4e_kv-fZCtgUv0WnWCFJp2@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Redbirds vs. Express Redbirds vs. Express

Follow on MiLB First Pitch  https //stza.co/+wmGt-7

Shop  https //stza.co/+wmGt-16

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Redbirds vs. Express
END:VALARM
DTSTART:20180819T190500Z
DTEND:20180819T220500Z
UID:OE4e_kv-fZCtgUv0WnWCFJp2@stanza.co
SUMMARY:Redbirds vs. Express
DESCRIPTION:Redbirds vs. Express\n\nFollow on MiLB First Pitch: https://stza.co/+wmGt-7\n\nShop: https://stza.co/+wmGt-16\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144543Z
LAST-MODIFIED:20180213T144543Z
TRANSP:OPAQUE
END:VEVENT
* Redbirds @ Baby Cakes
<2018-08-21 Tue 19:00-22:00>
:PROPERTIES:
:ID:       hM_pGgV6_HoMnWuaP7SwjhzS@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Redbirds @ Baby Cakes Redbirds @ Baby Cakes

Follow on MiLB First Pitch  https //stza.co/+whFG-H

Shop  https //stza.co/+whFG-R

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Redbirds @ Baby Cakes
END:VALARM
DTSTART:20180822T000000Z
DTEND:20180822T030000Z
UID:hM_pGgV6_HoMnWuaP7SwjhzS@stanza.co
SUMMARY:Redbirds @ Baby Cakes
DESCRIPTION:Redbirds @ Baby Cakes\n\nFollow on MiLB First Pitch: https://stza.co/+whFG-H\n\nShop: https://stza.co/+whFG-R\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144543Z
LAST-MODIFIED:20180213T144543Z
TRANSP:OPAQUE
END:VEVENT
* Redbirds @ Baby Cakes
<2018-08-22 Wed 19:00-22:00>
:PROPERTIES:
:ID:       XUskolZ-Vdwtc9WhhnzdphnR@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Redbirds @ Baby Cakes Redbirds @ Baby Cakes

Follow on MiLB First Pitch  https //stza.co/+whFH-3K

Shop  https //stza.co/+whFH-3S

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Redbirds @ Baby Cakes
END:VALARM
DTSTART:20180823T000000Z
DTEND:20180823T030000Z
UID:XUskolZ-Vdwtc9WhhnzdphnR@stanza.co
SUMMARY:Redbirds @ Baby Cakes
DESCRIPTION:Redbirds @ Baby Cakes\n\nFollow on MiLB First Pitch: https://stza.co/+whFH-3K\n\nShop: https://stza.co/+whFH-3S\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144543Z
LAST-MODIFIED:20180213T144543Z
TRANSP:OPAQUE
END:VEVENT
* Redbirds @ Baby Cakes
<2018-08-23 Thu 19:00-22:00>
:PROPERTIES:
:ID:       cm0AmiwSjtEVAclbX-RY2GxQ@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Redbirds @ Baby Cakes Redbirds @ Baby Cakes

Follow on MiLB First Pitch  https //stza.co/+whFI-2A

Shop  https //stza.co/+whFI-1r

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Redbirds @ Baby Cakes
END:VALARM
DTSTART:20180824T000000Z
DTEND:20180824T030000Z
UID:cm0AmiwSjtEVAclbX-RY2GxQ@stanza.co
SUMMARY:Redbirds @ Baby Cakes
DESCRIPTION:Redbirds @ Baby Cakes\n\nFollow on MiLB First Pitch: https://stza.co/+whFI-2A\n\nShop: https://stza.co/+whFI-1r\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144543Z
LAST-MODIFIED:20180213T144543Z
TRANSP:OPAQUE
END:VEVENT
* Redbirds vs. Sounds
<2018-08-24 Fri 19:05-22:05>
:PROPERTIES:
:ID:       ELrPencqmxFaYkNQJps1Ppm8@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Redbirds vs. Sounds Redbirds vs. Sounds

Follow on MiLB First Pitch  https //stza.co/+wmGv-2Z

Shop  https //stza.co/+wmGv-2T

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Redbirds vs. Sounds
END:VALARM
DTSTART:20180825T000500Z
DTEND:20180825T030500Z
UID:ELrPencqmxFaYkNQJps1Ppm8@stanza.co
SUMMARY:Redbirds vs. Sounds
DESCRIPTION:Redbirds vs. Sounds\n\nFollow on MiLB First Pitch: https://stza.co/+wmGv-2Z\n\nShop: https://stza.co/+wmGv-2T\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144543Z
LAST-MODIFIED:20180213T144543Z
TRANSP:OPAQUE
END:VEVENT
* Redbirds vs. Sounds
<2018-08-25 Sat 18:35-21:35>
:PROPERTIES:
:ID:       8x4dUwAZIigTcVeLDhB0Yj0R@stanza.co
:LOCATION: Postgame Fireworks
:STATUS:   CONFIRMED
:END:

Redbirds vs. Sounds Stick around after the game for an amazing fireworks spectacular, launched up close and personal from center field.

Follow on MiLB First Pitch  https //stza.co/+wmGw-2N

Shop  https //stza.co/+wmGw-m

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Redbirds vs. Sounds
END:VALARM
DTSTART:20180825T233500Z
DTEND:20180826T023500Z
UID:8x4dUwAZIigTcVeLDhB0Yj0R@stanza.co
SUMMARY:Redbirds vs. Sounds
DESCRIPTION:Stick around after the game for an amazing fireworks spectacular, launched up close and personal from center field.\n\nFollow on MiLB First Pitch: https://stza.co/+wmGw-2N\n\nShop: https://stza.co/+wmGw-m\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Postgame Fireworks
STATUS:CONFIRMED
CREATED:20180213T144543Z
LAST-MODIFIED:20180213T144543Z
TRANSP:OPAQUE
END:VEVENT
* Redbirds vs. Sounds
<2018-08-26 Sun 14:05-17:05>
:PROPERTIES:
:ID:       _QKi-ZYPZoqP1Sad4AKD103t@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Redbirds vs. Sounds Redbirds vs. Sounds

Follow on MiLB First Pitch  https //stza.co/+wmGz-y

Shop  https //stza.co/+wmGz-3j

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Redbirds vs. Sounds
END:VALARM
DTSTART:20180826T190500Z
DTEND:20180826T220500Z
UID:_QKi-ZYPZoqP1Sad4AKD103t@stanza.co
SUMMARY:Redbirds vs. Sounds
DESCRIPTION:Redbirds vs. Sounds\n\nFollow on MiLB First Pitch: https://stza.co/+wmGz-y\n\nShop: https://stza.co/+wmGz-3j\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144543Z
LAST-MODIFIED:20180213T144543Z
TRANSP:OPAQUE
END:VEVENT
* Redbirds vs. Sounds
<2018-08-27 Mon 18:35-21:35>
:PROPERTIES:
:ID:       wsCp77dlUYuu2qq1ynwgzmnx@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Redbirds vs. Sounds Redbirds vs. Sounds

Follow on MiLB First Pitch  https //stza.co/+wmGA-2T

Shop  https //stza.co/+wmGA-2C

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Redbirds vs. Sounds
END:VALARM
DTSTART:20180827T233500Z
DTEND:20180828T023500Z
UID:wsCp77dlUYuu2qq1ynwgzmnx@stanza.co
SUMMARY:Redbirds vs. Sounds
DESCRIPTION:Redbirds vs. Sounds\n\nFollow on MiLB First Pitch: https://stza.co/+wmGA-2T\n\nShop: https://stza.co/+wmGA-2C\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144543Z
LAST-MODIFIED:20180213T144543Z
TRANSP:OPAQUE
END:VEVENT
* Redbirds @ Express
<2018-08-28 Tue 19:05-22:05>
:PROPERTIES:
:ID:       qYr3aSe4eILvmuuCRMdTCwC_@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Redbirds @ Express Redbirds @ Express

Follow on MiLB First Pitch  https //stza.co/+v1Ly-1I

Shop  https //stza.co/+v1Ly-1Z

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Redbirds @ Express
END:VALARM
DTSTART:20180829T000500Z
DTEND:20180829T030500Z
UID:qYr3aSe4eILvmuuCRMdTCwC_@stanza.co
SUMMARY:Redbirds @ Express
DESCRIPTION:Redbirds @ Express\n\nFollow on MiLB First Pitch: https://stza.co/+v1Ly-1I\n\nShop: https://stza.co/+v1Ly-1Z\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144543Z
LAST-MODIFIED:20180213T144543Z
TRANSP:OPAQUE
END:VEVENT
* Redbirds @ Express
<2018-08-29 Wed 19:05-22:05>
:PROPERTIES:
:ID:       nb_ItQwcX0QsTY_v_Dc0t3Mf@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Redbirds @ Express Redbirds @ Express

Follow on MiLB First Pitch  https //stza.co/+v1LR-30

Shop  https //stza.co/+v1LR-20

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Redbirds @ Express
END:VALARM
DTSTART:20180830T000500Z
DTEND:20180830T030500Z
UID:nb_ItQwcX0QsTY_v_Dc0t3Mf@stanza.co
SUMMARY:Redbirds @ Express
DESCRIPTION:Redbirds @ Express\n\nFollow on MiLB First Pitch: https://stza.co/+v1LR-30\n\nShop: https://stza.co/+v1LR-20\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144543Z
LAST-MODIFIED:20180213T144543Z
TRANSP:OPAQUE
END:VEVENT
* Redbirds @ Express
<2018-08-30 Thu 19:05-22:05>
:PROPERTIES:
:ID:       3Ftw-pMBjHxuYQgCD2L1yhXg@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Redbirds @ Express Redbirds @ Express

Follow on MiLB First Pitch  https //stza.co/+v1M7-1c

Shop  https //stza.co/+v1M7-z

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Redbirds @ Express
END:VALARM
DTSTART:20180831T000500Z
DTEND:20180831T030500Z
UID:3Ftw-pMBjHxuYQgCD2L1yhXg@stanza.co
SUMMARY:Redbirds @ Express
DESCRIPTION:Redbirds @ Express\n\nFollow on MiLB First Pitch: https://stza.co/+v1M7-1c\n\nShop: https://stza.co/+v1M7-z\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144543Z
LAST-MODIFIED:20180213T144543Z
TRANSP:OPAQUE
END:VEVENT
* Redbirds @ Sounds
<2018-08-31 Fri 19:05-22:05>
:PROPERTIES:
:ID:       zC4SDZ6tLqlGYDs3qFJxkx2G@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Redbirds @ Sounds Redbirds @ Sounds

Follow on MiLB First Pitch  https //stza.co/+whFv-21

Shop  https //stza.co/+whFv-W

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Redbirds @ Sounds
END:VALARM
DTSTART:20180901T000500Z
DTEND:20180901T030500Z
UID:zC4SDZ6tLqlGYDs3qFJxkx2G@stanza.co
SUMMARY:Redbirds @ Sounds
DESCRIPTION:Redbirds @ Sounds\n\nFollow on MiLB First Pitch: https://stza.co/+whFv-21\n\nShop: https://stza.co/+whFv-W\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144543Z
LAST-MODIFIED:20180213T144543Z
TRANSP:OPAQUE
END:VEVENT
* Redbirds @ Sounds
<2018-09-01 Sat 19:05-22:05>
:PROPERTIES:
:ID:       QbPOuglK9kXP9MQ9ZSxUCLgr@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Redbirds @ Sounds Redbirds @ Sounds

Follow on MiLB First Pitch  https //stza.co/+whFw-k

Shop  https //stza.co/+whFw-2E

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Redbirds @ Sounds
END:VALARM
DTSTART:20180902T000500Z
DTEND:20180902T030500Z
UID:QbPOuglK9kXP9MQ9ZSxUCLgr@stanza.co
SUMMARY:Redbirds @ Sounds
DESCRIPTION:Redbirds @ Sounds\n\nFollow on MiLB First Pitch: https://stza.co/+whFw-k\n\nShop: https://stza.co/+whFw-2E\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144543Z
LAST-MODIFIED:20180213T144543Z
TRANSP:OPAQUE
END:VEVENT
* Redbirds @ Sounds
<2018-09-02 Sun 18:15-21:15>
:PROPERTIES:
:ID:       w5QZPUtsJdI71VV_DHXOw_Ph@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Redbirds @ Sounds Redbirds @ Sounds

Follow on MiLB First Pitch  https //stza.co/+whFx-1M

Shop  https //stza.co/+whFx-3s

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Redbirds @ Sounds
END:VALARM
DTSTART:20180902T231500Z
DTEND:20180903T021500Z
UID:w5QZPUtsJdI71VV_DHXOw_Ph@stanza.co
SUMMARY:Redbirds @ Sounds
DESCRIPTION:Redbirds @ Sounds\n\nFollow on MiLB First Pitch: https://stza.co/+whFx-1M\n\nShop: https://stza.co/+whFx-3s\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144543Z
LAST-MODIFIED:20180213T144543Z
TRANSP:OPAQUE
END:VEVENT
* Redbirds @ Sounds
<2018-09-03 Mon 12:05-15:05>
:PROPERTIES:
:ID:       43IL9AyZTt_yOxR_MQD71ek-@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Redbirds @ Sounds Redbirds @ Sounds

Follow on MiLB First Pitch  https //stza.co/+whFz-1E

Shop  https //stza.co/+whFz-9

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Redbirds @ Sounds
END:VALARM
DTSTART:20180903T170500Z
DTEND:20180903T200500Z
UID:43IL9AyZTt_yOxR_MQD71ek-@stanza.co
SUMMARY:Redbirds @ Sounds
DESCRIPTION:Redbirds @ Sounds\n\nFollow on MiLB First Pitch: https://stza.co/+whFz-1E\n\nShop: https://stza.co/+whFz-9\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144543Z
LAST-MODIFIED:20180213T144543Z
TRANSP:OPAQUE
END:VEVENT
