#+TITLE:       Main Google calendar entries
#+AUTHOR:      Eric S Fraga
#+EMAIL:       e.fraga@ucl.ac.uk
#+DESCRIPTION: converted using the ical2org awk script
#+CATEGORY:    google
#+STARTUP:     hidestars
#+STARTUP:     overview

* COMMENT original iCal preamble

* Sea Dogs @ Rumble Ponies
<2018-04-05 Thu 17:35-20:35>
:PROPERTIES:
:ID:       YB_J3ZhSyJY3_-9ioyD0xipv@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Sea Dogs @ Rumble Ponies Sea Dogs @ Rumble Ponies

Follow on MiLB First Pitch  https //stza.co/+vLq5-z

Shop  https //stza.co/+vLq5-2

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Sea Dogs @ Rumble Ponies
END:VALARM
DTSTART:20180405T223500Z
DTEND:20180406T013500Z
UID:YB_J3ZhSyJY3_-9ioyD0xipv@stanza.co
SUMMARY:Sea Dogs @ Rumble Ponies
DESCRIPTION:Sea Dogs @ Rumble Ponies\n\nFollow on MiLB First Pitch: https://stza.co/+vLq5-z\n\nShop: https://stza.co/+vLq5-2\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144551Z
LAST-MODIFIED:20180213T144551Z
TRANSP:OPAQUE
END:VEVENT
* Sea Dogs @ Rumble Ponies
<2018-04-06 Fri 18:05-21:05>
:PROPERTIES:
:ID:       4bWmT-gep1kFDR6ArC7pd8k7@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Sea Dogs @ Rumble Ponies Sea Dogs @ Rumble Ponies

Follow on MiLB First Pitch  https //stza.co/+vLq6-t

Shop  https //stza.co/+vLq6-2W

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Sea Dogs @ Rumble Ponies
END:VALARM
DTSTART:20180406T230500Z
DTEND:20180407T020500Z
UID:4bWmT-gep1kFDR6ArC7pd8k7@stanza.co
SUMMARY:Sea Dogs @ Rumble Ponies
DESCRIPTION:Sea Dogs @ Rumble Ponies\n\nFollow on MiLB First Pitch: https://stza.co/+vLq6-t\n\nShop: https://stza.co/+vLq6-2W\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144551Z
LAST-MODIFIED:20180213T144551Z
TRANSP:OPAQUE
END:VEVENT
* Sea Dogs @ Rumble Ponies
<2018-04-07 Sat 14:05-17:05>
:PROPERTIES:
:ID:       wvVubgmU9SDpr4woP7qZc9d6@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Sea Dogs @ Rumble Ponies Sea Dogs @ Rumble Ponies

Follow on MiLB First Pitch  https //stza.co/+vLq7-3r

Shop  https //stza.co/+vLq7-1

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Sea Dogs @ Rumble Ponies
END:VALARM
DTSTART:20180407T190500Z
DTEND:20180407T220500Z
UID:wvVubgmU9SDpr4woP7qZc9d6@stanza.co
SUMMARY:Sea Dogs @ Rumble Ponies
DESCRIPTION:Sea Dogs @ Rumble Ponies\n\nFollow on MiLB First Pitch: https://stza.co/+vLq7-3r\n\nShop: https://stza.co/+vLq7-1\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144551Z
LAST-MODIFIED:20180213T144551Z
TRANSP:OPAQUE
END:VEVENT
* Sea Dogs @ Rumble Ponies
<2018-04-08 Sun 13:05-16:05>
:PROPERTIES:
:ID:       uniC6otp5IiAtsd14YNRW0gj@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Sea Dogs @ Rumble Ponies Sea Dogs @ Rumble Ponies

Follow on MiLB First Pitch  https //stza.co/+vLq8-3d

Shop  https //stza.co/+vLq8-1F

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Sea Dogs @ Rumble Ponies
END:VALARM
DTSTART:20180408T180500Z
DTEND:20180408T210500Z
UID:uniC6otp5IiAtsd14YNRW0gj@stanza.co
SUMMARY:Sea Dogs @ Rumble Ponies
DESCRIPTION:Sea Dogs @ Rumble Ponies\n\nFollow on MiLB First Pitch: https://stza.co/+vLq8-3d\n\nShop: https://stza.co/+vLq8-1F\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144551Z
LAST-MODIFIED:20180213T144551Z
TRANSP:OPAQUE
END:VEVENT
* Sea Dogs @ Fightin Phils
<2018-04-09 Mon 17:35-20:35>
:PROPERTIES:
:ID:       0ChH4LGFV7y9RhywedVbqfi0@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Sea Dogs @ Fightin Phils Sea Dogs @ Fightin Phils

Buy tickets here  https //stza.co/~vLsZ

Follow on MiLB First Pitch  https //stza.co/+vLsZ-H

Shop  https //stza.co/+vLsZ-3Z

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Sea Dogs @ Fightin Phils
END:VALARM
DTSTART:20180409T223500Z
DTEND:20180410T013500Z
UID:0ChH4LGFV7y9RhywedVbqfi0@stanza.co
SUMMARY:Sea Dogs @ Fightin Phils
DESCRIPTION:Sea Dogs @ Fightin Phils\n\nBuy tickets here: https://stza.co/~vLsZ\n\nFollow on MiLB First Pitch: https://stza.co/+vLsZ-H\n\nShop: https://stza.co/+vLsZ-3Z\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144551Z
LAST-MODIFIED:20180213T144551Z
TRANSP:OPAQUE
END:VEVENT
* Sea Dogs @ Fightin Phils
<2018-04-10 Tue 17:35-20:35>
:PROPERTIES:
:ID:       sP6l0UB20Fcvmsyt3DKmaBh-@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Sea Dogs @ Fightin Phils Sea Dogs @ Fightin Phils

Buy tickets here  https //stza.co/~vLs_

Follow on MiLB First Pitch  https //stza.co/+vLs_-2f

Shop  https //stza.co/+vLs_-33

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Sea Dogs @ Fightin Phils
END:VALARM
DTSTART:20180410T223500Z
DTEND:20180411T013500Z
UID:sP6l0UB20Fcvmsyt3DKmaBh-@stanza.co
SUMMARY:Sea Dogs @ Fightin Phils
DESCRIPTION:Sea Dogs @ Fightin Phils\n\nBuy tickets here: https://stza.co/~vLs_\n\nFollow on MiLB First Pitch: https://stza.co/+vLs_-2f\n\nShop: https://stza.co/+vLs_-33\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144551Z
LAST-MODIFIED:20180213T144551Z
TRANSP:OPAQUE
END:VEVENT
* Sea Dogs @ Fightin Phils
<2018-04-11 Wed 12:05-15:05>
:PROPERTIES:
:ID:       e6cSKV5d3l_55af_VOpZBU_b@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Sea Dogs @ Fightin Phils Sea Dogs @ Fightin Phils

Buy tickets here  https //stza.co/~vLs$

Follow on MiLB First Pitch  https //stza.co/+vLs$-c

Shop  https //stza.co/+vLs$-3i

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Sea Dogs @ Fightin Phils
END:VALARM
DTSTART:20180411T170500Z
DTEND:20180411T200500Z
UID:e6cSKV5d3l_55af_VOpZBU_b@stanza.co
SUMMARY:Sea Dogs @ Fightin Phils
DESCRIPTION:Sea Dogs @ Fightin Phils\n\nBuy tickets here: https://stza.co/~vLs$\n\nFollow on MiLB First Pitch: https://stza.co/+vLs$-c\n\nShop: https://stza.co/+vLs$-3i\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144551Z
LAST-MODIFIED:20180213T144551Z
TRANSP:OPAQUE
END:VEVENT
* Sea Dogs vs. Rumble Ponies
<2018-04-13 Fri 17:00-20:00>
:PROPERTIES:
:ID:       GfyHWJ0-qfdP404IoyEgwKt_@stanza.co
:LOCATION: Swipe to get tickets for the game tonight. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Sea Dogs vs. Rumble Ponies Sea Dogs vs. Rumble Ponies

Buy tickets here  https //stza.co/~vLqN

Follow on MiLB First Pitch  https //stza.co/+vLqN-9

Shop  https //stza.co/+vLqN-3A

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Sea Dogs vs. Rumble Ponies
END:VALARM
DTSTART:20180413T220000Z
DTEND:20180414T010000Z
UID:GfyHWJ0-qfdP404IoyEgwKt_@stanza.co
SUMMARY:Sea Dogs vs. Rumble Ponies
DESCRIPTION:Sea Dogs vs. Rumble Ponies\n\nBuy tickets here: https://stza.co/~vLqN\n\nFollow on MiLB First Pitch: https://stza.co/+vLqN-9\n\nShop: https://stza.co/+vLqN-3A\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Swipe to get tickets for the game tonight. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144551Z
LAST-MODIFIED:20180213T144551Z
TRANSP:OPAQUE
END:VEVENT
* Sea Dogs vs. Rumble Ponies
<2018-04-14 Sat 12:00-15:00>
:PROPERTIES:
:ID:       5vUncYfRWERCLR2HN2GJkvbw@stanza.co
:LOCATION: Schedule Magnet Giveaway
:STATUS:   CONFIRMED
:END:

Sea Dogs vs. Rumble Ponies The first 2,500 fans to enter the ballpark will receive a 2018 Sea Dogs schedule magnet, courtesy of Paul G. White Interior Solutions.

The Portland Sea Dogs' mascot band; The Kastaways will be performing pre-game on the front plaza.



Buy tickets here  https //stza.co/~vLqQ

Follow on MiLB First Pitch  https //stza.co/+vLqQ-3o

Shop  https //stza.co/+vLqQ-3U

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Sea Dogs vs. Rumble Ponies
END:VALARM
DTSTART:20180414T170000Z
DTEND:20180414T200000Z
UID:5vUncYfRWERCLR2HN2GJkvbw@stanza.co
SUMMARY:Sea Dogs vs. Rumble Ponies
DESCRIPTION:The first 2,500 fans to enter the ballpark will receive a 2018 Sea Dogs schedule magnet, courtesy of Paul G. White Interior Solutions.\n\nThe Portland Sea Dogs' mascot band; The Kastaways will be performing pre-game on the front plaza.\n\n\n\nBuy tickets here: https://stza.co/~vLqQ\n\nFollow on MiLB First Pitch: https://stza.co/+vLqQ-3o\n\nShop: https://stza.co/+vLqQ-3U\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Schedule Magnet Giveaway
STATUS:CONFIRMED
CREATED:20180213T144551Z
LAST-MODIFIED:20180213T144551Z
TRANSP:OPAQUE
END:VEVENT
* Sea Dogs vs. Rumble Ponies
<2018-04-15 Sun 12:00-15:00>
:PROPERTIES:
:ID:       1z157OzU048RxBcaAnt8DBsM@stanza.co
:LOCATION: Kids run the bases for today's game. Bring out the family!
:STATUS:   CONFIRMED
:END:

Sea Dogs vs. Rumble Ponies On the anniversary of Jackie Robinson's first Major League game, the Sea Dogs will all be wearing #42 jerseys.  The first 500 fans to enter the ballpark will receive a Jackie Robinson photo.

Kids 16 and under can run the bases after the game, weather and field conditions permitting.

Buy tickets here  https //stza.co/~vLqR

Follow on MiLB First Pitch  https //stza.co/+vLqR-1j

Shop  https //stza.co/+vLqR-2h

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Sea Dogs vs. Rumble Ponies
END:VALARM
DTSTART:20180415T170000Z
DTEND:20180415T200000Z
UID:1z157OzU048RxBcaAnt8DBsM@stanza.co
SUMMARY:Sea Dogs vs. Rumble Ponies
DESCRIPTION:On the anniversary of Jackie Robinson's first Major League game, the Sea Dogs will all be wearing #42 jerseys.  The first 500 fans to enter the ballpark will receive a Jackie Robinson photo.\n\nKids 16 and under can run the bases after the game, weather and field conditions permitting.\n\nBuy tickets here: https://stza.co/~vLqR\n\nFollow on MiLB First Pitch: https://stza.co/+vLqR-1j\n\nShop: https://stza.co/+vLqR-2h\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Kids run the bases for today's game. Bring out the family!
STATUS:CONFIRMED
CREATED:20180213T144551Z
LAST-MODIFIED:20180213T144551Z
TRANSP:OPAQUE
END:VEVENT
* Sea Dogs vs. Yard Goats
<2018-04-16 Mon 17:00-20:00>
:PROPERTIES:
:ID:       J6cfAeY5-R-FRc0AuROKb6cQ@stanza.co
:LOCATION: Swipe for last minute tickets for tonight's game. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Sea Dogs vs. Yard Goats Sea Dogs vs. Yard Goats

Buy tickets here  https //stza.co/~vLqU

Follow on MiLB First Pitch  https //stza.co/+vLqU-13

Shop  https //stza.co/+vLqU-2k

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Sea Dogs vs. Yard Goats
END:VALARM
DTSTART:20180416T220000Z
DTEND:20180417T010000Z
UID:J6cfAeY5-R-FRc0AuROKb6cQ@stanza.co
SUMMARY:Sea Dogs vs. Yard Goats
DESCRIPTION:Sea Dogs vs. Yard Goats\n\nBuy tickets here: https://stza.co/~vLqU\n\nFollow on MiLB First Pitch: https://stza.co/+vLqU-13\n\nShop: https://stza.co/+vLqU-2k\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Swipe for last minute tickets for tonight's game. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144551Z
LAST-MODIFIED:20180213T144551Z
TRANSP:OPAQUE
END:VEVENT
* Sea Dogs vs. Yard Goats
<2018-04-17 Tue 17:00-20:00>
:PROPERTIES:
:ID:       xhnhDxUUKKtbL8noK5dlOdca@stanza.co
:LOCATION: Ready for the game? Swipe for tickets and more information.
:STATUS:   CONFIRMED
:END:

Sea Dogs vs. Yard Goats Sea Dogs vs. Yard Goats

Buy tickets here  https //stza.co/~vLqV

Follow on MiLB First Pitch  https //stza.co/+vLqV-m

Shop  https //stza.co/+vLqV-37

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Sea Dogs vs. Yard Goats
END:VALARM
DTSTART:20180417T220000Z
DTEND:20180418T010000Z
UID:xhnhDxUUKKtbL8noK5dlOdca@stanza.co
SUMMARY:Sea Dogs vs. Yard Goats
DESCRIPTION:Sea Dogs vs. Yard Goats\n\nBuy tickets here: https://stza.co/~vLqV\n\nFollow on MiLB First Pitch: https://stza.co/+vLqV-m\n\nShop: https://stza.co/+vLqV-37\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Swipe for tickets and more information.
STATUS:CONFIRMED
CREATED:20180213T144551Z
LAST-MODIFIED:20180213T144551Z
TRANSP:OPAQUE
END:VEVENT
* Sea Dogs vs. Yard Goats
<2018-04-18 Wed 17:00-20:00>
:PROPERTIES:
:ID:       XzkDO1ZUPhjbBUNSlBCgp5e-@stanza.co
:LOCATION: 25th Season Celebration
:STATUS:   CONFIRMED
:END:

Sea Dogs vs. Yard Goats On the anniversary of the Sea Dogs first home game, the Sea Dogs will celebrate their 25th season.  Details to be announced.

Buy tickets here  https //stza.co/~vLqY

Follow on MiLB First Pitch  https //stza.co/+vLqY-3P

Shop  https //stza.co/+vLqY-39

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Sea Dogs vs. Yard Goats
END:VALARM
DTSTART:20180418T220000Z
DTEND:20180419T010000Z
UID:XzkDO1ZUPhjbBUNSlBCgp5e-@stanza.co
SUMMARY:Sea Dogs vs. Yard Goats
DESCRIPTION:On the anniversary of the Sea Dogs first home game, the Sea Dogs will celebrate their 25th season.  Details to be announced.\n\nBuy tickets here: https://stza.co/~vLqY\n\nFollow on MiLB First Pitch: https://stza.co/+vLqY-3P\n\nShop: https://stza.co/+vLqY-39\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:25th Season Celebration
STATUS:CONFIRMED
CREATED:20180213T144551Z
LAST-MODIFIED:20180213T144551Z
TRANSP:OPAQUE
END:VEVENT
* Sea Dogs vs. Yard Goats
<2018-04-19 Thu 11:00-14:00>
:PROPERTIES:
:ID:       cNqigazGWlS8GZDSg-fgG1Nz@stanza.co
:LOCATION: Spirit Day
:STATUS:   CONFIRMED
:END:

Sea Dogs vs. Yard Goats Special 12 00 PM start time. Parks & Rec groups along with camps will participate in spirit day competitions throughout the game. 

Buy tickets here  https //stza.co/~vLq_

Follow on MiLB First Pitch  https //stza.co/+vLq_-3w

Shop  https //stza.co/+vLq_-y

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Sea Dogs vs. Yard Goats
END:VALARM
DTSTART:20180419T160000Z
DTEND:20180419T190000Z
UID:cNqigazGWlS8GZDSg-fgG1Nz@stanza.co
SUMMARY:Sea Dogs vs. Yard Goats
DESCRIPTION:Special 12:00 PM start time. Parks & Rec groups along with camps will participate in spirit day competitions throughout the game. \n\nBuy tickets here: https://stza.co/~vLq_\n\nFollow on MiLB First Pitch: https://stza.co/+vLq_-3w\n\nShop: https://stza.co/+vLq_-y\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Spirit Day
STATUS:CONFIRMED
CREATED:20180213T144551Z
LAST-MODIFIED:20180213T144551Z
TRANSP:OPAQUE
END:VEVENT
* Sea Dogs @ Thunder
<2018-04-20 Fri 18:00-21:00>
:PROPERTIES:
:ID:       rXC1HrFbewc6XGWrXJ9c_-mJ@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Sea Dogs @ Thunder Sea Dogs @ Thunder

Follow on MiLB First Pitch  https //stza.co/+vanV-2l

Shop  https //stza.co/+vanV-1E

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Sea Dogs @ Thunder
END:VALARM
DTSTART:20180420T230000Z
DTEND:20180421T020000Z
UID:rXC1HrFbewc6XGWrXJ9c_-mJ@stanza.co
SUMMARY:Sea Dogs @ Thunder
DESCRIPTION:Sea Dogs @ Thunder\n\nFollow on MiLB First Pitch: https://stza.co/+vanV-2l\n\nShop: https://stza.co/+vanV-1E\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144551Z
LAST-MODIFIED:20180213T144551Z
TRANSP:OPAQUE
END:VEVENT
* Sea Dogs @ Thunder
<2018-04-21 Sat 12:00-15:00>
:PROPERTIES:
:ID:       NVTAUo5eRb65tw3xF5V75RDP@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Sea Dogs @ Thunder Sea Dogs @ Thunder

Follow on MiLB First Pitch  https //stza.co/+vanW-1h

Shop  https //stza.co/+vanW-3w

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Sea Dogs @ Thunder
END:VALARM
DTSTART:20180421T170000Z
DTEND:20180421T200000Z
UID:NVTAUo5eRb65tw3xF5V75RDP@stanza.co
SUMMARY:Sea Dogs @ Thunder
DESCRIPTION:Sea Dogs @ Thunder\n\nFollow on MiLB First Pitch: https://stza.co/+vanW-1h\n\nShop: https://stza.co/+vanW-3w\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144551Z
LAST-MODIFIED:20180213T144551Z
TRANSP:OPAQUE
END:VEVENT
* Sea Dogs @ Thunder
<2018-04-22 Sun 12:00-15:00>
:PROPERTIES:
:ID:       -E38BzoNAxKHt7u5VQY8GAji@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Sea Dogs @ Thunder Sea Dogs @ Thunder

Follow on MiLB First Pitch  https //stza.co/+vanX-3E

Shop  https //stza.co/+vanX-o

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Sea Dogs @ Thunder
END:VALARM
DTSTART:20180422T170000Z
DTEND:20180422T200000Z
UID:-E38BzoNAxKHt7u5VQY8GAji@stanza.co
SUMMARY:Sea Dogs @ Thunder
DESCRIPTION:Sea Dogs @ Thunder\n\nFollow on MiLB First Pitch: https://stza.co/+vanX-3E\n\nShop: https://stza.co/+vanX-o\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144551Z
LAST-MODIFIED:20180213T144551Z
TRANSP:OPAQUE
END:VEVENT
* Sea Dogs @ Yard Goats
<2018-04-23 Mon 18:05-21:05>
:PROPERTIES:
:ID:       IdQdVlMyD1deF_-YphsSAx7_@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Sea Dogs @ Yard Goats Sea Dogs @ Yard Goats

Buy tickets here  https //stza.co/~vLqp

Follow on MiLB First Pitch  https //stza.co/+vLqp-$

Shop  https //stza.co/+vLqp-1C

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Sea Dogs @ Yard Goats
END:VALARM
DTSTART:20180423T230500Z
DTEND:20180424T020500Z
UID:IdQdVlMyD1deF_-YphsSAx7_@stanza.co
SUMMARY:Sea Dogs @ Yard Goats
DESCRIPTION:Sea Dogs @ Yard Goats\n\nBuy tickets here: https://stza.co/~vLqp\n\nFollow on MiLB First Pitch: https://stza.co/+vLqp-$\n\nShop: https://stza.co/+vLqp-1C\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144551Z
LAST-MODIFIED:20180213T144551Z
TRANSP:OPAQUE
END:VEVENT
* Sea Dogs @ Yard Goats
<2018-04-24 Tue 18:05-21:05>
:PROPERTIES:
:ID:       BKV1D5hk02hLQSk6x00dcWp5@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Sea Dogs @ Yard Goats Sea Dogs @ Yard Goats

Buy tickets here  https //stza.co/~vLqq

Follow on MiLB First Pitch  https //stza.co/+vLqq-2d

Shop  https //stza.co/+vLqq-1T

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Sea Dogs @ Yard Goats
END:VALARM
DTSTART:20180424T230500Z
DTEND:20180425T020500Z
UID:BKV1D5hk02hLQSk6x00dcWp5@stanza.co
SUMMARY:Sea Dogs @ Yard Goats
DESCRIPTION:Sea Dogs @ Yard Goats\n\nBuy tickets here: https://stza.co/~vLqq\n\nFollow on MiLB First Pitch: https://stza.co/+vLqq-2d\n\nShop: https://stza.co/+vLqq-1T\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144551Z
LAST-MODIFIED:20180213T144551Z
TRANSP:OPAQUE
END:VEVENT
* Sea Dogs @ Yard Goats
<2018-04-25 Wed 18:05-21:05>
:PROPERTIES:
:ID:       nUxCqP3-HenA4PbftEGQFN9p@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Sea Dogs @ Yard Goats Sea Dogs @ Yard Goats

Buy tickets here  https //stza.co/~vLqr

Follow on MiLB First Pitch  https //stza.co/+vLqr-1G

Shop  https //stza.co/+vLqr-2e

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Sea Dogs @ Yard Goats
END:VALARM
DTSTART:20180425T230500Z
DTEND:20180426T020500Z
UID:nUxCqP3-HenA4PbftEGQFN9p@stanza.co
SUMMARY:Sea Dogs @ Yard Goats
DESCRIPTION:Sea Dogs @ Yard Goats\n\nBuy tickets here: https://stza.co/~vLqr\n\nFollow on MiLB First Pitch: https://stza.co/+vLqr-1G\n\nShop: https://stza.co/+vLqr-2e\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144551Z
LAST-MODIFIED:20180213T144551Z
TRANSP:OPAQUE
END:VEVENT
* Sea Dogs vs. Fightin Phils
<2018-04-27 Fri 17:00-20:00>
:PROPERTIES:
:ID:       yPiw3LKXWPY2-39k8Ty2_uO2@stanza.co
:LOCATION: Looking for something to do tonight? Get tickets here for tonight’s game and view promotions.
:STATUS:   CONFIRMED
:END:

Sea Dogs vs. Fightin Phils Sea Dogs vs. Fightin Phils

Buy tickets here  https //stza.co/~vLr0

Follow on MiLB First Pitch  https //stza.co/+vLr0-32

Shop  https //stza.co/+vLr0-1f

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Sea Dogs vs. Fightin Phils
END:VALARM
DTSTART:20180427T220000Z
DTEND:20180428T010000Z
UID:yPiw3LKXWPY2-39k8Ty2_uO2@stanza.co
SUMMARY:Sea Dogs vs. Fightin Phils
DESCRIPTION:Sea Dogs vs. Fightin Phils\n\nBuy tickets here: https://stza.co/~vLr0\n\nFollow on MiLB First Pitch: https://stza.co/+vLr0-32\n\nShop: https://stza.co/+vLr0-1f\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Looking for something to do tonight? Get tickets here for tonight’s game and view promotions.
STATUS:CONFIRMED
CREATED:20180213T144551Z
LAST-MODIFIED:20180213T144551Z
TRANSP:OPAQUE
END:VEVENT
* Sea Dogs vs. Fightin Phils
<2018-04-28 Sat 12:00-15:00>
:PROPERTIES:
:ID:       DAHrcKaX4Vl-P7ICijS15LAT@stanza.co
:LOCATION: Autism Awareness Day
:STATUS:   CONFIRMED
:END:

Sea Dogs vs. Fightin Phils 

The Portland Sea Dogs' mascot band; The Kastaways will be performing pre-game on the front plaza.

Buy tickets here  https //stza.co/~vLr2

Follow on MiLB First Pitch  https //stza.co/+vLr2-3j

Shop  https //stza.co/+vLr2-2F

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Sea Dogs vs. Fightin Phils
END:VALARM
DTSTART:20180428T170000Z
DTEND:20180428T200000Z
UID:DAHrcKaX4Vl-P7ICijS15LAT@stanza.co
SUMMARY:Sea Dogs vs. Fightin Phils
DESCRIPTION:\n\nThe Portland Sea Dogs' mascot band; The Kastaways will be performing pre-game on the front plaza.\n\nBuy tickets here: https://stza.co/~vLr2\n\nFollow on MiLB First Pitch: https://stza.co/+vLr2-3j\n\nShop: https://stza.co/+vLr2-2F\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Autism Awareness Day
STATUS:CONFIRMED
CREATED:20180213T144551Z
LAST-MODIFIED:20180213T144551Z
TRANSP:OPAQUE
END:VEVENT
* Sea Dogs vs. Fightin Phils
<2018-04-29 Sun 12:00-15:00>
:PROPERTIES:
:ID:       XlxLiVpSCMAK0fM8-c_1LrOu@stanza.co
:LOCATION: Kids run the bases for today's game. Bring out the family!
:STATUS:   CONFIRMED
:END:

Sea Dogs vs. Fightin Phils Kids 16 and under can run the bases after the game, weather and field conditions permitting.

Buy tickets here  https //stza.co/~vLr4

Follow on MiLB First Pitch  https //stza.co/+vLr4-3f

Shop  https //stza.co/+vLr4-3u

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Sea Dogs vs. Fightin Phils
END:VALARM
DTSTART:20180429T170000Z
DTEND:20180429T200000Z
UID:XlxLiVpSCMAK0fM8-c_1LrOu@stanza.co
SUMMARY:Sea Dogs vs. Fightin Phils
DESCRIPTION:Kids 16 and under can run the bases after the game, weather and field conditions permitting.\n\nBuy tickets here: https://stza.co/~vLr4\n\nFollow on MiLB First Pitch: https://stza.co/+vLr4-3f\n\nShop: https://stza.co/+vLr4-3u\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Kids run the bases for today's game. Bring out the family!
STATUS:CONFIRMED
CREATED:20180213T144551Z
LAST-MODIFIED:20180213T144551Z
TRANSP:OPAQUE
END:VEVENT
* Sea Dogs vs. Thunder
<2018-04-30 Mon 17:00-20:00>
:PROPERTIES:
:ID:       RYmlmISSnLlTuCHREKJEVoZb@stanza.co
:LOCATION: Great seats still available for tonight’s game. Purchase them here.
:STATUS:   CONFIRMED
:END:

Sea Dogs vs. Thunder Sea Dogs vs. Thunder

Buy tickets here  https //stza.co/~vLr5

Follow on MiLB First Pitch  https //stza.co/+vLr5-3t

Shop  https //stza.co/+vLr5-3v

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Sea Dogs vs. Thunder
END:VALARM
DTSTART:20180430T220000Z
DTEND:20180501T010000Z
UID:RYmlmISSnLlTuCHREKJEVoZb@stanza.co
SUMMARY:Sea Dogs vs. Thunder
DESCRIPTION:Sea Dogs vs. Thunder\n\nBuy tickets here: https://stza.co/~vLr5\n\nFollow on MiLB First Pitch: https://stza.co/+vLr5-3t\n\nShop: https://stza.co/+vLr5-3v\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Great seats still available for tonight’s game. Purchase them here.
STATUS:CONFIRMED
CREATED:20180213T144551Z
LAST-MODIFIED:20180213T144551Z
TRANSP:OPAQUE
END:VEVENT
* Sea Dogs vs. Thunder
<2018-05-01 Tue 17:00-20:00>
:PROPERTIES:
:ID:       VgLzWTv1HS67vMCE8ztEc0pg@stanza.co
:LOCATION: Need something fun to do tonight? Get Sea Dogs tickets here.
:STATUS:   CONFIRMED
:END:

Sea Dogs vs. Thunder Sea Dogs vs. Thunder

Buy tickets here  https //stza.co/~vLr8

Follow on MiLB First Pitch  https //stza.co/+vLr8-17

Shop  https //stza.co/+vLr8-3d

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Sea Dogs vs. Thunder
END:VALARM
DTSTART:20180501T220000Z
DTEND:20180502T010000Z
UID:VgLzWTv1HS67vMCE8ztEc0pg@stanza.co
SUMMARY:Sea Dogs vs. Thunder
DESCRIPTION:Sea Dogs vs. Thunder\n\nBuy tickets here: https://stza.co/~vLr8\n\nFollow on MiLB First Pitch: https://stza.co/+vLr8-17\n\nShop: https://stza.co/+vLr8-3d\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Need something fun to do tonight? Get Sea Dogs tickets here.
STATUS:CONFIRMED
CREATED:20180213T144551Z
LAST-MODIFIED:20180213T144551Z
TRANSP:OPAQUE
END:VEVENT
* Sea Dogs vs. Thunder
<2018-05-02 Wed 17:00-20:00>
:PROPERTIES:
:ID:       Zsu1o9MGaYoaH7JwNf3BJYQE@stanza.co
:LOCATION: Don’t miss out! Sea Dogs tickets still available here.
:STATUS:   CONFIRMED
:END:

Sea Dogs vs. Thunder Sea Dogs vs. Thunder

Buy tickets here  https //stza.co/~vLra

Follow on MiLB First Pitch  https //stza.co/+vLra-2d

Shop  https //stza.co/+vLra-2W

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Sea Dogs vs. Thunder
END:VALARM
DTSTART:20180502T220000Z
DTEND:20180503T010000Z
UID:Zsu1o9MGaYoaH7JwNf3BJYQE@stanza.co
SUMMARY:Sea Dogs vs. Thunder
DESCRIPTION:Sea Dogs vs. Thunder\n\nBuy tickets here: https://stza.co/~vLra\n\nFollow on MiLB First Pitch: https://stza.co/+vLra-2d\n\nShop: https://stza.co/+vLra-2W\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don’t miss out! Sea Dogs tickets still available here.
STATUS:CONFIRMED
CREATED:20180213T144551Z
LAST-MODIFIED:20180213T144551Z
TRANSP:OPAQUE
END:VEVENT
* Sea Dogs @ Yard Goats
<2018-05-03 Thu 18:05-21:05>
:PROPERTIES:
:ID:       jogsiyYQsz-HMGSVNqh1c3vY@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Sea Dogs @ Yard Goats Sea Dogs @ Yard Goats

Buy tickets here  https //stza.co/~vLqs

Follow on MiLB First Pitch  https //stza.co/+vLqs-2o

Shop  https //stza.co/+vLqs-2J

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Sea Dogs @ Yard Goats
END:VALARM
DTSTART:20180503T230500Z
DTEND:20180504T020500Z
UID:jogsiyYQsz-HMGSVNqh1c3vY@stanza.co
SUMMARY:Sea Dogs @ Yard Goats
DESCRIPTION:Sea Dogs @ Yard Goats\n\nBuy tickets here: https://stza.co/~vLqs\n\nFollow on MiLB First Pitch: https://stza.co/+vLqs-2o\n\nShop: https://stza.co/+vLqs-2J\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144551Z
LAST-MODIFIED:20180213T144551Z
TRANSP:OPAQUE
END:VEVENT
* Sea Dogs @ Yard Goats
<2018-05-04 Fri 18:05-21:05>
:PROPERTIES:
:ID:       vWI_0ae9qG9XTu74aqRYnODY@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Sea Dogs @ Yard Goats Sea Dogs @ Yard Goats

Buy tickets here  https //stza.co/~vLqt

Follow on MiLB First Pitch  https //stza.co/+vLqt-1b

Shop  https //stza.co/+vLqt-1_

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Sea Dogs @ Yard Goats
END:VALARM
DTSTART:20180504T230500Z
DTEND:20180505T020500Z
UID:vWI_0ae9qG9XTu74aqRYnODY@stanza.co
SUMMARY:Sea Dogs @ Yard Goats
DESCRIPTION:Sea Dogs @ Yard Goats\n\nBuy tickets here: https://stza.co/~vLqt\n\nFollow on MiLB First Pitch: https://stza.co/+vLqt-1b\n\nShop: https://stza.co/+vLqt-1_\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144551Z
LAST-MODIFIED:20180213T144551Z
TRANSP:OPAQUE
END:VEVENT
* Sea Dogs @ Yard Goats
<2018-05-05 Sat 17:05-20:05>
:PROPERTIES:
:ID:       RKEXW8QEthcP4aFKkodPxEyT@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Sea Dogs @ Yard Goats Sea Dogs @ Yard Goats

Buy tickets here  https //stza.co/~vLqu

Follow on MiLB First Pitch  https //stza.co/+vLqu-2K

Shop  https //stza.co/+vLqu-1O

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Sea Dogs @ Yard Goats
END:VALARM
DTSTART:20180505T220500Z
DTEND:20180506T010500Z
UID:RKEXW8QEthcP4aFKkodPxEyT@stanza.co
SUMMARY:Sea Dogs @ Yard Goats
DESCRIPTION:Sea Dogs @ Yard Goats\n\nBuy tickets here: https://stza.co/~vLqu\n\nFollow on MiLB First Pitch: https://stza.co/+vLqu-2K\n\nShop: https://stza.co/+vLqu-1O\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144551Z
LAST-MODIFIED:20180213T144551Z
TRANSP:OPAQUE
END:VEVENT
* Sea Dogs @ Yard Goats
<2018-05-06 Sun 12:05-15:05>
:PROPERTIES:
:ID:       mFPAWB5AlL0-l2saJG8LwQJv@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Sea Dogs @ Yard Goats Sea Dogs @ Yard Goats

Buy tickets here  https //stza.co/~vLqv

Follow on MiLB First Pitch  https //stza.co/+vLqv-35

Shop  https //stza.co/+vLqv-2a

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Sea Dogs @ Yard Goats
END:VALARM
DTSTART:20180506T170500Z
DTEND:20180506T200500Z
UID:mFPAWB5AlL0-l2saJG8LwQJv@stanza.co
SUMMARY:Sea Dogs @ Yard Goats
DESCRIPTION:Sea Dogs @ Yard Goats\n\nBuy tickets here: https://stza.co/~vLqv\n\nFollow on MiLB First Pitch: https://stza.co/+vLqv-35\n\nShop: https://stza.co/+vLqv-2a\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144551Z
LAST-MODIFIED:20180213T144551Z
TRANSP:OPAQUE
END:VEVENT
* Sea Dogs @ Fisher Cats
<2018-05-07 Mon 17:35-20:35>
:PROPERTIES:
:ID:       EyFI4b5deH2TAp-CD6gMLmMp@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Sea Dogs @ Fisher Cats Sea Dogs @ Fisher Cats

Follow on MiLB First Pitch  https //stza.co/+vLqB-27

Shop  https //stza.co/+vLqB-F

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Sea Dogs @ Fisher Cats
END:VALARM
DTSTART:20180507T223500Z
DTEND:20180508T013500Z
UID:EyFI4b5deH2TAp-CD6gMLmMp@stanza.co
SUMMARY:Sea Dogs @ Fisher Cats
DESCRIPTION:Sea Dogs @ Fisher Cats\n\nFollow on MiLB First Pitch: https://stza.co/+vLqB-27\n\nShop: https://stza.co/+vLqB-F\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144551Z
LAST-MODIFIED:20180213T144551Z
TRANSP:OPAQUE
END:VEVENT
* Sea Dogs @ Fisher Cats
<2018-05-08 Tue 17:35-20:35>
:PROPERTIES:
:ID:       2mZX4D4rvbLMtdWUzWzybc9n@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Sea Dogs @ Fisher Cats Sea Dogs @ Fisher Cats

Follow on MiLB First Pitch  https //stza.co/+vLqC-3C

Shop  https //stza.co/+vLqC-2d

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Sea Dogs @ Fisher Cats
END:VALARM
DTSTART:20180508T223500Z
DTEND:20180509T013500Z
UID:2mZX4D4rvbLMtdWUzWzybc9n@stanza.co
SUMMARY:Sea Dogs @ Fisher Cats
DESCRIPTION:Sea Dogs @ Fisher Cats\n\nFollow on MiLB First Pitch: https://stza.co/+vLqC-3C\n\nShop: https://stza.co/+vLqC-2d\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144551Z
LAST-MODIFIED:20180213T144551Z
TRANSP:OPAQUE
END:VEVENT
* Sea Dogs @ Fisher Cats
<2018-05-09 Wed 17:35-20:35>
:PROPERTIES:
:ID:       2m6xmiDzQ0pSlsukoybcMZTV@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Sea Dogs @ Fisher Cats Sea Dogs @ Fisher Cats

Follow on MiLB First Pitch  https //stza.co/+vLqD-a

Shop  https //stza.co/+vLqD-27

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Sea Dogs @ Fisher Cats
END:VALARM
DTSTART:20180509T223500Z
DTEND:20180510T013500Z
UID:2m6xmiDzQ0pSlsukoybcMZTV@stanza.co
SUMMARY:Sea Dogs @ Fisher Cats
DESCRIPTION:Sea Dogs @ Fisher Cats\n\nFollow on MiLB First Pitch: https://stza.co/+vLqD-a\n\nShop: https://stza.co/+vLqD-27\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144551Z
LAST-MODIFIED:20180213T144551Z
TRANSP:OPAQUE
END:VEVENT
* Sea Dogs vs. Rumble Ponies
<2018-05-10 Thu 17:00-20:00>
:PROPERTIES:
:ID:       RhbWsBs5HnTMmHPybHlhk7ju@stanza.co
:LOCATION: College Fair
:STATUS:   CONFIRMED
:END:

Sea Dogs vs. Rumble Ponies The Sea Dogs will host a College Fair from 3 00-5 00 PM at Hadlock Field prior to the game.  Approximately 50 colleges will be in attendance.  Stay tuned for details or contact the Sea Dogs at 207-879-9500.

Buy tickets here  https //stza.co/~vLrb

Follow on MiLB First Pitch  https //stza.co/+vLrb-3M

Shop  https //stza.co/+vLrb-1U

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Sea Dogs vs. Rumble Ponies
END:VALARM
DTSTART:20180510T220000Z
DTEND:20180511T010000Z
UID:RhbWsBs5HnTMmHPybHlhk7ju@stanza.co
SUMMARY:Sea Dogs vs. Rumble Ponies
DESCRIPTION:The Sea Dogs will host a College Fair from 3:00-5:00 PM at Hadlock Field prior to the game.  Approximately 50 colleges will be in attendance.  Stay tuned for details or contact the Sea Dogs at 207-879-9500.\n\nBuy tickets here: https://stza.co/~vLrb\n\nFollow on MiLB First Pitch: https://stza.co/+vLrb-3M\n\nShop: https://stza.co/+vLrb-1U\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:College Fair
STATUS:CONFIRMED
CREATED:20180213T144551Z
LAST-MODIFIED:20180213T144551Z
TRANSP:OPAQUE
END:VEVENT
* Sea Dogs vs. Rumble Ponies
<2018-05-11 Fri 17:00-20:00>
:PROPERTIES:
:ID:       EpD23UnC0cw35Zt43bu4cDWl@stanza.co
:LOCATION: Swipe to get tickets for the game tonight. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Sea Dogs vs. Rumble Ponies Sea Dogs vs. Rumble Ponies

Buy tickets here  https //stza.co/~vLre

Follow on MiLB First Pitch  https //stza.co/+vLre-o

Shop  https //stza.co/+vLre-2c

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Sea Dogs vs. Rumble Ponies
END:VALARM
DTSTART:20180511T220000Z
DTEND:20180512T010000Z
UID:EpD23UnC0cw35Zt43bu4cDWl@stanza.co
SUMMARY:Sea Dogs vs. Rumble Ponies
DESCRIPTION:Sea Dogs vs. Rumble Ponies\n\nBuy tickets here: https://stza.co/~vLre\n\nFollow on MiLB First Pitch: https://stza.co/+vLre-o\n\nShop: https://stza.co/+vLre-2c\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Swipe to get tickets for the game tonight. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144551Z
LAST-MODIFIED:20180213T144551Z
TRANSP:OPAQUE
END:VEVENT
* Sea Dogs vs. Rumble Ponies
<2018-05-12 Sat 12:00-15:00>
:PROPERTIES:
:ID:       ShUINw73dHwVZKf9UnyEUHB_@stanza.co
:LOCATION: Portland Monthly Giveaway
:STATUS:   CONFIRMED
:END:

Sea Dogs vs. Rumble Ponies The first 300 fans to enter the ballpark will receive a copy of the May issue of Portland Monthly, courtesy of Portland Monthly.

The Portland Sea Dogs' mascot band; The Kastaways will be performing pre-game on the front plaza.



Buy tickets here  https //stza.co/~vLrf

Follow on MiLB First Pitch  https //stza.co/+vLrf-f

Shop  https //stza.co/+vLrf-1c

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Sea Dogs vs. Rumble Ponies
END:VALARM
DTSTART:20180512T170000Z
DTEND:20180512T200000Z
UID:ShUINw73dHwVZKf9UnyEUHB_@stanza.co
SUMMARY:Sea Dogs vs. Rumble Ponies
DESCRIPTION:The first 300 fans to enter the ballpark will receive a copy of the May issue of Portland Monthly, courtesy of Portland Monthly.\n\nThe Portland Sea Dogs' mascot band; The Kastaways will be performing pre-game on the front plaza.\n\n\n\nBuy tickets here: https://stza.co/~vLrf\n\nFollow on MiLB First Pitch: https://stza.co/+vLrf-f\n\nShop: https://stza.co/+vLrf-1c\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Portland Monthly Giveaway
STATUS:CONFIRMED
CREATED:20180213T144551Z
LAST-MODIFIED:20180213T144551Z
TRANSP:OPAQUE
END:VEVENT
* Sea Dogs vs. Rumble Ponies
<2018-05-13 Sun 12:00-15:00>
:PROPERTIES:
:ID:       OseUEBY6ZJ6FsvbmneQ8Nj-R@stanza.co
:LOCATION: Kids run the bases for today's game. Bring out the family!
:STATUS:   CONFIRMED
:END:

Sea Dogs vs. Rumble Ponies The Sea Dogs will be wearing pink jerseys for breast cancer awareness.  Fans are encouraged to wear pink to the park!

Kids 16 and under can run the bases after the game, weather and field conditions permitting.

Buy tickets here  https //stza.co/~vLrh

Follow on MiLB First Pitch  https //stza.co/+vLrh-3B

Shop  https //stza.co/+vLrh-h

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Sea Dogs vs. Rumble Ponies
END:VALARM
DTSTART:20180513T170000Z
DTEND:20180513T200000Z
UID:OseUEBY6ZJ6FsvbmneQ8Nj-R@stanza.co
SUMMARY:Sea Dogs vs. Rumble Ponies
DESCRIPTION:The Sea Dogs will be wearing pink jerseys for breast cancer awareness.  Fans are encouraged to wear pink to the park!\n\nKids 16 and under can run the bases after the game, weather and field conditions permitting.\n\nBuy tickets here: https://stza.co/~vLrh\n\nFollow on MiLB First Pitch: https://stza.co/+vLrh-3B\n\nShop: https://stza.co/+vLrh-h\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Kids run the bases for today's game. Bring out the family!
STATUS:CONFIRMED
CREATED:20180213T144551Z
LAST-MODIFIED:20180213T144551Z
TRANSP:OPAQUE
END:VEVENT
* Sea Dogs @ Fightin Phils
<2018-05-14 Mon 17:35-20:35>
:PROPERTIES:
:ID:       _tiKo6sbT93aAVqSv8q7mi0B@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Sea Dogs @ Fightin Phils Sea Dogs @ Fightin Phils

Buy tickets here  https //stza.co/~vanM

Follow on MiLB First Pitch  https //stza.co/+vanM-2D

Shop  https //stza.co/+vanM-20

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Sea Dogs @ Fightin Phils
END:VALARM
DTSTART:20180514T223500Z
DTEND:20180515T013500Z
UID:_tiKo6sbT93aAVqSv8q7mi0B@stanza.co
SUMMARY:Sea Dogs @ Fightin Phils
DESCRIPTION:Sea Dogs @ Fightin Phils\n\nBuy tickets here: https://stza.co/~vanM\n\nFollow on MiLB First Pitch: https://stza.co/+vanM-2D\n\nShop: https://stza.co/+vanM-20\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144551Z
LAST-MODIFIED:20180213T144551Z
TRANSP:OPAQUE
END:VEVENT
* Sea Dogs @ Fightin Phils
<2018-05-15 Tue 10:35-13:35>
:PROPERTIES:
:ID:       -TbJrxXCdp40UreiJz_eAAFu@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Sea Dogs @ Fightin Phils Sea Dogs @ Fightin Phils

Buy tickets here  https //stza.co/~vanN

Follow on MiLB First Pitch  https //stza.co/+vanN-3S

Shop  https //stza.co/+vanN-2w

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Sea Dogs @ Fightin Phils
END:VALARM
DTSTART:20180515T153500Z
DTEND:20180515T183500Z
UID:-TbJrxXCdp40UreiJz_eAAFu@stanza.co
SUMMARY:Sea Dogs @ Fightin Phils
DESCRIPTION:Sea Dogs @ Fightin Phils\n\nBuy tickets here: https://stza.co/~vanN\n\nFollow on MiLB First Pitch: https://stza.co/+vanN-3S\n\nShop: https://stza.co/+vanN-2w\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144551Z
LAST-MODIFIED:20180213T144551Z
TRANSP:OPAQUE
END:VEVENT
* Sea Dogs @ Fightin Phils
<2018-05-16 Wed 10:35-13:35>
:PROPERTIES:
:ID:       dyajHe_9eV8w-z3y1Rdelt8q@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Sea Dogs @ Fightin Phils Sea Dogs @ Fightin Phils

Buy tickets here  https //stza.co/~vanO

Follow on MiLB First Pitch  https //stza.co/+vanO-3n

Shop  https //stza.co/+vanO-n

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Sea Dogs @ Fightin Phils
END:VALARM
DTSTART:20180516T153500Z
DTEND:20180516T183500Z
UID:dyajHe_9eV8w-z3y1Rdelt8q@stanza.co
SUMMARY:Sea Dogs @ Fightin Phils
DESCRIPTION:Sea Dogs @ Fightin Phils\n\nBuy tickets here: https://stza.co/~vanO\n\nFollow on MiLB First Pitch: https://stza.co/+vanO-3n\n\nShop: https://stza.co/+vanO-n\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144551Z
LAST-MODIFIED:20180213T144551Z
TRANSP:OPAQUE
END:VEVENT
* Sea Dogs @ Curve
<2018-05-17 Thu 17:00-20:00>
:PROPERTIES:
:ID:       gKWgrYqo49xvO0Hkgu1AYC3A@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Sea Dogs @ Curve Sea Dogs @ Curve

Follow on MiLB First Pitch  https //stza.co/+vLq1-1w

Shop  https //stza.co/+vLq1-2H

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Sea Dogs @ Curve
END:VALARM
DTSTART:20180517T220000Z
DTEND:20180518T010000Z
UID:gKWgrYqo49xvO0Hkgu1AYC3A@stanza.co
SUMMARY:Sea Dogs @ Curve
DESCRIPTION:Sea Dogs @ Curve\n\nFollow on MiLB First Pitch: https://stza.co/+vLq1-1w\n\nShop: https://stza.co/+vLq1-2H\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144551Z
LAST-MODIFIED:20180213T144551Z
TRANSP:OPAQUE
END:VEVENT
* Sea Dogs @ Curve
<2018-05-18 Fri 17:00-20:00>
:PROPERTIES:
:ID:       7J5fP1gEmUpM-B2-F3dVJHio@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Sea Dogs @ Curve Sea Dogs @ Curve

Follow on MiLB First Pitch  https //stza.co/+vLq2-3f

Shop  https //stza.co/+vLq2-2F

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Sea Dogs @ Curve
END:VALARM
DTSTART:20180518T220000Z
DTEND:20180519T010000Z
UID:7J5fP1gEmUpM-B2-F3dVJHio@stanza.co
SUMMARY:Sea Dogs @ Curve
DESCRIPTION:Sea Dogs @ Curve\n\nFollow on MiLB First Pitch: https://stza.co/+vLq2-3f\n\nShop: https://stza.co/+vLq2-2F\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144551Z
LAST-MODIFIED:20180213T144551Z
TRANSP:OPAQUE
END:VEVENT
* Sea Dogs @ Curve
<2018-05-19 Sat 17:00-20:00>
:PROPERTIES:
:ID:       paEhtlQuOc25OD1Cnd3zPtA-@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Sea Dogs @ Curve Sea Dogs @ Curve

Follow on MiLB First Pitch  https //stza.co/+vLq3-2S

Shop  https //stza.co/+vLq3-l

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Sea Dogs @ Curve
END:VALARM
DTSTART:20180519T220000Z
DTEND:20180520T010000Z
UID:paEhtlQuOc25OD1Cnd3zPtA-@stanza.co
SUMMARY:Sea Dogs @ Curve
DESCRIPTION:Sea Dogs @ Curve\n\nFollow on MiLB First Pitch: https://stza.co/+vLq3-2S\n\nShop: https://stza.co/+vLq3-l\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144551Z
LAST-MODIFIED:20180213T144551Z
TRANSP:OPAQUE
END:VEVENT
* Sea Dogs @ Curve
<2018-05-20 Sun 13:00-16:00>
:PROPERTIES:
:ID:       Hc_EeOC_RpWTUcFxRUjelzZ4@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Sea Dogs @ Curve Sea Dogs @ Curve

Follow on MiLB First Pitch  https //stza.co/+vLq4-14

Shop  https //stza.co/+vLq4-1x

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Sea Dogs @ Curve
END:VALARM
DTSTART:20180520T180000Z
DTEND:20180520T210000Z
UID:Hc_EeOC_RpWTUcFxRUjelzZ4@stanza.co
SUMMARY:Sea Dogs @ Curve
DESCRIPTION:Sea Dogs @ Curve\n\nFollow on MiLB First Pitch: https://stza.co/+vLq4-14\n\nShop: https://stza.co/+vLq4-1x\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144551Z
LAST-MODIFIED:20180213T144551Z
TRANSP:OPAQUE
END:VEVENT
* Sea Dogs vs. Yard Goats
<2018-05-22 Tue 17:00-20:00>
:PROPERTIES:
:ID:       iki0-qzGQNuGONsNWCUdPkj5@stanza.co
:LOCATION: Swipe for last minute tickets for tonight's game. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Sea Dogs vs. Yard Goats Sea Dogs vs. Yard Goats

Buy tickets here  https //stza.co/~vLrj

Follow on MiLB First Pitch  https //stza.co/+vLrj-3

Shop  https //stza.co/+vLrj-1l

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Sea Dogs vs. Yard Goats
END:VALARM
DTSTART:20180522T220000Z
DTEND:20180523T010000Z
UID:iki0-qzGQNuGONsNWCUdPkj5@stanza.co
SUMMARY:Sea Dogs vs. Yard Goats
DESCRIPTION:Sea Dogs vs. Yard Goats\n\nBuy tickets here: https://stza.co/~vLrj\n\nFollow on MiLB First Pitch: https://stza.co/+vLrj-3\n\nShop: https://stza.co/+vLrj-1l\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Swipe for last minute tickets for tonight's game. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144551Z
LAST-MODIFIED:20180213T144551Z
TRANSP:OPAQUE
END:VEVENT
* Sea Dogs vs. Yard Goats
<2018-05-23 Wed 17:00-20:00>
:PROPERTIES:
:ID:       eN-a0K5yjMVQZRoPO5SpJl8b@stanza.co
:LOCATION: Ready for the game? Swipe for tickets and more information.
:STATUS:   CONFIRMED
:END:

Sea Dogs vs. Yard Goats Sea Dogs vs. Yard Goats

Buy tickets here  https //stza.co/~vLrl

Follow on MiLB First Pitch  https //stza.co/+vLrl-R

Shop  https //stza.co/+vLrl-S

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Sea Dogs vs. Yard Goats
END:VALARM
DTSTART:20180523T220000Z
DTEND:20180524T010000Z
UID:eN-a0K5yjMVQZRoPO5SpJl8b@stanza.co
SUMMARY:Sea Dogs vs. Yard Goats
DESCRIPTION:Sea Dogs vs. Yard Goats\n\nBuy tickets here: https://stza.co/~vLrl\n\nFollow on MiLB First Pitch: https://stza.co/+vLrl-R\n\nShop: https://stza.co/+vLrl-S\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Swipe for tickets and more information.
STATUS:CONFIRMED
CREATED:20180213T144551Z
LAST-MODIFIED:20180213T144551Z
TRANSP:OPAQUE
END:VEVENT
* Sea Dogs vs. Yard Goats
<2018-05-24 Thu 10:00-13:00>
:PROPERTIES:
:ID:       _W9TuDdU0NJpS1A7vw2PObxW@stanza.co
:LOCATION: Looking for something to do tonight? Get tickets here for tonight’s game and view promotions.
:STATUS:   CONFIRMED
:END:

Sea Dogs vs. Yard Goats Sea Dogs vs. Yard Goats

Buy tickets here  https //stza.co/~vLro

Follow on MiLB First Pitch  https //stza.co/+vLro-3j

Shop  https //stza.co/+vLro-3R

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Sea Dogs vs. Yard Goats
END:VALARM
DTSTART:20180524T150000Z
DTEND:20180524T180000Z
UID:_W9TuDdU0NJpS1A7vw2PObxW@stanza.co
SUMMARY:Sea Dogs vs. Yard Goats
DESCRIPTION:Sea Dogs vs. Yard Goats\n\nBuy tickets here: https://stza.co/~vLro\n\nFollow on MiLB First Pitch: https://stza.co/+vLro-3j\n\nShop: https://stza.co/+vLro-3R\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Looking for something to do tonight? Get tickets here for tonight’s game and view promotions.
STATUS:CONFIRMED
CREATED:20180213T144551Z
LAST-MODIFIED:20180213T144551Z
TRANSP:OPAQUE
END:VEVENT
* Sea Dogs vs. Fightin Phils
<2018-05-25 Fri 17:00-20:00>
:PROPERTIES:
:ID:       ipU2qmvqTqxkgalSZgOZWyUn@stanza.co
:LOCATION: Stick around after tonight's game for some spectacular fireworks!
:STATUS:   CONFIRMED
:END:

Sea Dogs vs. Fightin Phils Enjoy a fantastic post-game fireworks show, made possible by U.S. Cellular.

Buy tickets here  https //stza.co/~vLrp

Follow on MiLB First Pitch  https //stza.co/+vLrp-15

Shop  https //stza.co/+vLrp-2v

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Sea Dogs vs. Fightin Phils
END:VALARM
DTSTART:20180525T220000Z
DTEND:20180526T010000Z
UID:ipU2qmvqTqxkgalSZgOZWyUn@stanza.co
SUMMARY:Sea Dogs vs. Fightin Phils
DESCRIPTION:Enjoy a fantastic post-game fireworks show, made possible by U.S. Cellular.\n\nBuy tickets here: https://stza.co/~vLrp\n\nFollow on MiLB First Pitch: https://stza.co/+vLrp-15\n\nShop: https://stza.co/+vLrp-2v\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stick around after tonight's game for some spectacular fireworks!
STATUS:CONFIRMED
CREATED:20180213T144551Z
LAST-MODIFIED:20180213T144551Z
TRANSP:OPAQUE
END:VEVENT
* Sea Dogs vs. Fightin Phils
<2018-05-26 Sat 12:00-15:00>
:PROPERTIES:
:ID:       vSc0fuUSpOAwA777HZvAdm-f@stanza.co
:LOCATION: The Kastaways
:STATUS:   CONFIRMED
:END:

Sea Dogs vs. Fightin Phils The Portland Sea Dogs' mascot band; The Kastaways will be performing pre-game on the front plaza.

Buy tickets here  https //stza.co/~vLrs

Follow on MiLB First Pitch  https //stza.co/+vLrs-13

Shop  https //stza.co/+vLrs-$

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Sea Dogs vs. Fightin Phils
END:VALARM
DTSTART:20180526T170000Z
DTEND:20180526T200000Z
UID:vSc0fuUSpOAwA777HZvAdm-f@stanza.co
SUMMARY:Sea Dogs vs. Fightin Phils
DESCRIPTION:The Portland Sea Dogs' mascot band; The Kastaways will be performing pre-game on the front plaza.\n\nBuy tickets here: https://stza.co/~vLrs\n\nFollow on MiLB First Pitch: https://stza.co/+vLrs-13\n\nShop: https://stza.co/+vLrs-$\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:The Kastaways
STATUS:CONFIRMED
CREATED:20180213T144551Z
LAST-MODIFIED:20180213T144551Z
TRANSP:OPAQUE
END:VEVENT
* Sea Dogs vs. Fightin Phils
<2018-05-27 Sun 12:00-15:00>
:PROPERTIES:
:ID:       qWJbtjka94ryC3ObfV82Snpm@stanza.co
:LOCATION: Kids run the bases for today's game. Bring out the family!
:STATUS:   CONFIRMED
:END:

Sea Dogs vs. Fightin Phils Come dressed as your favorite Superhero and participate in a pre-game Superhero parade.  Prizes for best kids and adult costumes.  Please arrive by 12 00 PM to participate.

Kids 16 and under can run the bases after the game, weather and field conditions permitting.

Buy tickets here  https //stza.co/~vLru

Follow on MiLB First Pitch  https //stza.co/+vLru-25

Shop  https //stza.co/+vLru-2K

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Sea Dogs vs. Fightin Phils
END:VALARM
DTSTART:20180527T170000Z
DTEND:20180527T200000Z
UID:qWJbtjka94ryC3ObfV82Snpm@stanza.co
SUMMARY:Sea Dogs vs. Fightin Phils
DESCRIPTION:Come dressed as your favorite Superhero and participate in a pre-game Superhero parade.  Prizes for best kids and adult costumes.  Please arrive by 12:00 PM to participate.\n\nKids 16 and under can run the bases after the game, weather and field conditions permitting.\n\nBuy tickets here: https://stza.co/~vLru\n\nFollow on MiLB First Pitch: https://stza.co/+vLru-25\n\nShop: https://stza.co/+vLru-2K\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Kids run the bases for today's game. Bring out the family!
STATUS:CONFIRMED
CREATED:20180213T144551Z
LAST-MODIFIED:20180213T144551Z
TRANSP:OPAQUE
END:VEVENT
* Sea Dogs vs. Fightin Phils
<2018-05-28 Mon 12:00-15:00>
:PROPERTIES:
:ID:       7x6ZQbU-vVZrNtIT1q3195Os@stanza.co
:LOCATION: Great seats still available for tonight’s game. Purchase them here.
:STATUS:   CONFIRMED
:END:

Sea Dogs vs. Fightin Phils Sea Dogs vs. Fightin Phils

Buy tickets here  https //stza.co/~vLrw

Follow on MiLB First Pitch  https //stza.co/+vLrw-s

Shop  https //stza.co/+vLrw-z

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Sea Dogs vs. Fightin Phils
END:VALARM
DTSTART:20180528T170000Z
DTEND:20180528T200000Z
UID:7x6ZQbU-vVZrNtIT1q3195Os@stanza.co
SUMMARY:Sea Dogs vs. Fightin Phils
DESCRIPTION:Sea Dogs vs. Fightin Phils\n\nBuy tickets here: https://stza.co/~vLrw\n\nFollow on MiLB First Pitch: https://stza.co/+vLrw-s\n\nShop: https://stza.co/+vLrw-z\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Great seats still available for tonight’s game. Purchase them here.
STATUS:CONFIRMED
CREATED:20180213T144551Z
LAST-MODIFIED:20180213T144551Z
TRANSP:OPAQUE
END:VEVENT
* Sea Dogs @ Fisher Cats
<2018-05-29 Tue 17:35-20:35>
:PROPERTIES:
:ID:       Glutr4LqKUywmU_i4FbclbZe@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Sea Dogs @ Fisher Cats Sea Dogs @ Fisher Cats

Follow on MiLB First Pitch  https //stza.co/+vLqE-1q

Shop  https //stza.co/+vLqE-3m

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Sea Dogs @ Fisher Cats
END:VALARM
DTSTART:20180529T223500Z
DTEND:20180530T013500Z
UID:Glutr4LqKUywmU_i4FbclbZe@stanza.co
SUMMARY:Sea Dogs @ Fisher Cats
DESCRIPTION:Sea Dogs @ Fisher Cats\n\nFollow on MiLB First Pitch: https://stza.co/+vLqE-1q\n\nShop: https://stza.co/+vLqE-3m\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144551Z
LAST-MODIFIED:20180213T144551Z
TRANSP:OPAQUE
END:VEVENT
* Sea Dogs @ Fisher Cats
<2018-05-30 Wed 17:35-20:35>
:PROPERTIES:
:ID:       lMalc9jtQ4b5S1IBgCR2mVC8@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Sea Dogs @ Fisher Cats Sea Dogs @ Fisher Cats

Follow on MiLB First Pitch  https //stza.co/+vLqF-3w

Shop  https //stza.co/+vLqF-1P

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Sea Dogs @ Fisher Cats
END:VALARM
DTSTART:20180530T223500Z
DTEND:20180531T013500Z
UID:lMalc9jtQ4b5S1IBgCR2mVC8@stanza.co
SUMMARY:Sea Dogs @ Fisher Cats
DESCRIPTION:Sea Dogs @ Fisher Cats\n\nFollow on MiLB First Pitch: https://stza.co/+vLqF-3w\n\nShop: https://stza.co/+vLqF-1P\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144551Z
LAST-MODIFIED:20180213T144551Z
TRANSP:OPAQUE
END:VEVENT
* Sea Dogs @ Fisher Cats
<2018-05-31 Thu 10:35-13:35>
:PROPERTIES:
:ID:       n7SSxMofANTlKY_eXfzBijyV@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Sea Dogs @ Fisher Cats Sea Dogs @ Fisher Cats

Follow on MiLB First Pitch  https //stza.co/+vLqG-H

Shop  https //stza.co/+vLqG-3w

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Sea Dogs @ Fisher Cats
END:VALARM
DTSTART:20180531T153500Z
DTEND:20180531T183500Z
UID:n7SSxMofANTlKY_eXfzBijyV@stanza.co
SUMMARY:Sea Dogs @ Fisher Cats
DESCRIPTION:Sea Dogs @ Fisher Cats\n\nFollow on MiLB First Pitch: https://stza.co/+vLqG-H\n\nShop: https://stza.co/+vLqG-3w\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144551Z
LAST-MODIFIED:20180213T144551Z
TRANSP:OPAQUE
END:VEVENT
* Sea Dogs @ Senators
<2018-06-01 Fri 18:00-21:00>
:PROPERTIES:
:ID:       n04GqO5ihq0piIxRL1Y9I5Ee@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Sea Dogs @ Senators Sea Dogs @ Senators

Follow on MiLB First Pitch  https //stza.co/+vLqm-p

Shop  https //stza.co/+vLqm-28

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Sea Dogs @ Senators
END:VALARM
DTSTART:20180601T230000Z
DTEND:20180602T020000Z
UID:n04GqO5ihq0piIxRL1Y9I5Ee@stanza.co
SUMMARY:Sea Dogs @ Senators
DESCRIPTION:Sea Dogs @ Senators\n\nFollow on MiLB First Pitch: https://stza.co/+vLqm-p\n\nShop: https://stza.co/+vLqm-28\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144551Z
LAST-MODIFIED:20180213T144551Z
TRANSP:OPAQUE
END:VEVENT
* Sea Dogs @ Senators
<2018-06-02 Sat 17:00-20:00>
:PROPERTIES:
:ID:       GW5d32FxmpQ5sX5JqNqQqX3k@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Sea Dogs @ Senators Sea Dogs @ Senators

Follow on MiLB First Pitch  https //stza.co/+vLqn-1W

Shop  https //stza.co/+vLqn-26

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Sea Dogs @ Senators
END:VALARM
DTSTART:20180602T220000Z
DTEND:20180603T010000Z
UID:GW5d32FxmpQ5sX5JqNqQqX3k@stanza.co
SUMMARY:Sea Dogs @ Senators
DESCRIPTION:Sea Dogs @ Senators\n\nFollow on MiLB First Pitch: https://stza.co/+vLqn-1W\n\nShop: https://stza.co/+vLqn-26\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144551Z
LAST-MODIFIED:20180213T144551Z
TRANSP:OPAQUE
END:VEVENT
* Sea Dogs @ Senators
<2018-06-03 Sun 14:30-17:30>
:PROPERTIES:
:ID:       Uoa-ZlE2atf-4LBTFdhquC6B@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Sea Dogs @ Senators Sea Dogs @ Senators

Follow on MiLB First Pitch  https //stza.co/+vLqo-2O

Shop  https //stza.co/+vLqo-3x

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Sea Dogs @ Senators
END:VALARM
DTSTART:20180603T193000Z
DTEND:20180603T223000Z
UID:Uoa-ZlE2atf-4LBTFdhquC6B@stanza.co
SUMMARY:Sea Dogs @ Senators
DESCRIPTION:Sea Dogs @ Senators\n\nFollow on MiLB First Pitch: https://stza.co/+vLqo-2O\n\nShop: https://stza.co/+vLqo-3x\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144551Z
LAST-MODIFIED:20180213T144551Z
TRANSP:OPAQUE
END:VEVENT
* Sea Dogs vs. Baysox
<2018-06-05 Tue 18:00-21:00>
:PROPERTIES:
:ID:       Ge2Hi9GtIr7XzmIZRmhjTvAM@stanza.co
:LOCATION: Need something fun to do tonight? Get Sea Dogs tickets here.
:STATUS:   CONFIRMED
:END:

Sea Dogs vs. Baysox Sea Dogs vs. Baysox

Buy tickets here  https //stza.co/~vLrx

Follow on MiLB First Pitch  https //stza.co/+vLrx-Y

Shop  https //stza.co/+vLrx-3n

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Sea Dogs vs. Baysox
END:VALARM
DTSTART:20180605T230000Z
DTEND:20180606T020000Z
UID:Ge2Hi9GtIr7XzmIZRmhjTvAM@stanza.co
SUMMARY:Sea Dogs vs. Baysox
DESCRIPTION:Sea Dogs vs. Baysox\n\nBuy tickets here: https://stza.co/~vLrx\n\nFollow on MiLB First Pitch: https://stza.co/+vLrx-Y\n\nShop: https://stza.co/+vLrx-3n\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Need something fun to do tonight? Get Sea Dogs tickets here.
STATUS:CONFIRMED
CREATED:20180213T144551Z
LAST-MODIFIED:20180213T144551Z
TRANSP:OPAQUE
END:VEVENT
* Sea Dogs vs. Baysox
<2018-06-06 Wed 18:00-21:00>
:PROPERTIES:
:ID:       39r5JBhXSpgxjEA1dZ-0YM1H@stanza.co
:LOCATION: Baseball & Brews
:STATUS:   CONFIRMED
:END:

Sea Dogs vs. Baysox Stay tuned for info or contact the Sea Dogs at 207-879-9500.

Buy tickets here  https //stza.co/~vLrA

Follow on MiLB First Pitch  https //stza.co/+vLrA-y

Shop  https //stza.co/+vLrA-v

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Sea Dogs vs. Baysox
END:VALARM
DTSTART:20180606T230000Z
DTEND:20180607T020000Z
UID:39r5JBhXSpgxjEA1dZ-0YM1H@stanza.co
SUMMARY:Sea Dogs vs. Baysox
DESCRIPTION:Stay tuned for info or contact the Sea Dogs at 207-879-9500.\n\nBuy tickets here: https://stza.co/~vLrA\n\nFollow on MiLB First Pitch: https://stza.co/+vLrA-y\n\nShop: https://stza.co/+vLrA-v\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Baseball & Brews
STATUS:CONFIRMED
CREATED:20180213T144551Z
LAST-MODIFIED:20180213T144551Z
TRANSP:OPAQUE
END:VEVENT
* Sea Dogs vs. Baysox
<2018-06-07 Thu 10:00-13:00>
:PROPERTIES:
:ID:       vTnoPPjqvnga5rhEhQoiXh8F@stanza.co
:LOCATION: Don’t miss out! Sea Dogs tickets still available here.
:STATUS:   CONFIRMED
:END:

Sea Dogs vs. Baysox Sea Dogs vs. Baysox

Buy tickets here  https //stza.co/~vLrC

Follow on MiLB First Pitch  https //stza.co/+vLrC-2h

Shop  https //stza.co/+vLrC-g

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Sea Dogs vs. Baysox
END:VALARM
DTSTART:20180607T150000Z
DTEND:20180607T180000Z
UID:vTnoPPjqvnga5rhEhQoiXh8F@stanza.co
SUMMARY:Sea Dogs vs. Baysox
DESCRIPTION:Sea Dogs vs. Baysox\n\nBuy tickets here: https://stza.co/~vLrC\n\nFollow on MiLB First Pitch: https://stza.co/+vLrC-2h\n\nShop: https://stza.co/+vLrC-g\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don’t miss out! Sea Dogs tickets still available here.
STATUS:CONFIRMED
CREATED:20180213T144551Z
LAST-MODIFIED:20180213T144551Z
TRANSP:OPAQUE
END:VEVENT
* Sea Dogs vs. RubberDucks
<2018-06-08 Fri 18:00-21:00>
:PROPERTIES:
:ID:       W5aNkI0MFtH_yhOP3pm9nVFM@stanza.co
:LOCATION: Swipe to get tickets for the game tonight. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Sea Dogs vs. RubberDucks Sea Dogs vs. RubberDucks

Buy tickets here  https //stza.co/~vLrE

Follow on MiLB First Pitch  https //stza.co/+vLrE-a

Shop  https //stza.co/+vLrE-

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Sea Dogs vs. RubberDucks
END:VALARM
DTSTART:20180608T230000Z
DTEND:20180609T020000Z
UID:W5aNkI0MFtH_yhOP3pm9nVFM@stanza.co
SUMMARY:Sea Dogs vs. RubberDucks
DESCRIPTION:Sea Dogs vs. RubberDucks\n\nBuy tickets here: https://stza.co/~vLrE\n\nFollow on MiLB First Pitch: https://stza.co/+vLrE-a\n\nShop: https://stza.co/+vLrE-\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Swipe to get tickets for the game tonight. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144551Z
LAST-MODIFIED:20180213T144551Z
TRANSP:OPAQUE
END:VEVENT
* Sea Dogs vs. RubberDucks
<2018-06-09 Sat 17:00-20:00>
:PROPERTIES:
:ID:       vXtBjj4RIzQz8nnGULWm4MZs@stanza.co
:LOCATION: The Kastaways
:STATUS:   CONFIRMED
:END:

Sea Dogs vs. RubberDucks The Portland Sea Dogs' mascot band; The Kastaways will be performing pre-game on the front plaza.

Buy tickets here  https //stza.co/~vLrF

Follow on MiLB First Pitch  https //stza.co/+vLrF-2J

Shop  https //stza.co/+vLrF-M

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Sea Dogs vs. RubberDucks
END:VALARM
DTSTART:20180609T220000Z
DTEND:20180610T010000Z
UID:vXtBjj4RIzQz8nnGULWm4MZs@stanza.co
SUMMARY:Sea Dogs vs. RubberDucks
DESCRIPTION:The Portland Sea Dogs' mascot band; The Kastaways will be performing pre-game on the front plaza.\n\nBuy tickets here: https://stza.co/~vLrF\n\nFollow on MiLB First Pitch: https://stza.co/+vLrF-2J\n\nShop: https://stza.co/+vLrF-M\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:The Kastaways
STATUS:CONFIRMED
CREATED:20180213T144551Z
LAST-MODIFIED:20180213T144551Z
TRANSP:OPAQUE
END:VEVENT
* Sea Dogs vs. RubberDucks
<2018-06-10 Sun 12:00-15:00>
:PROPERTIES:
:ID:       bgilopaUxGQ7_jaLGmuDxOVG@stanza.co
:LOCATION: Kids run the bases for today's game. Bring out the family!
:STATUS:   CONFIRMED
:END:

Sea Dogs vs. RubberDucks Fans are invited to come play catch on the field prior to the game from 10 00 AM to 11 15 AM.

The Sea Dogs will be wearing blue jerseys for prostate cancer awareness.

Kids 16 and under can run the bases after the game, weather and field conditions permitting.

Buy tickets here  https //stza.co/~vLrH

Follow on MiLB First Pitch  https //stza.co/+vLrH-T

Shop  https //stza.co/+vLrH-2h

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Sea Dogs vs. RubberDucks
END:VALARM
DTSTART:20180610T170000Z
DTEND:20180610T200000Z
UID:bgilopaUxGQ7_jaLGmuDxOVG@stanza.co
SUMMARY:Sea Dogs vs. RubberDucks
DESCRIPTION:Fans are invited to come play catch on the field prior to the game from 10:00 AM to 11:15 AM.\n\nThe Sea Dogs will be wearing blue jerseys for prostate cancer awareness.\n\nKids 16 and under can run the bases after the game, weather and field conditions permitting.\n\nBuy tickets here: https://stza.co/~vLrH\n\nFollow on MiLB First Pitch: https://stza.co/+vLrH-T\n\nShop: https://stza.co/+vLrH-2h\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Kids run the bases for today's game. Bring out the family!
STATUS:CONFIRMED
CREATED:20180213T144551Z
LAST-MODIFIED:20180213T144551Z
TRANSP:OPAQUE
END:VEVENT
* Sea Dogs @ Flying Squirrels
<2018-06-12 Tue 17:35-20:35>
:PROPERTIES:
:ID:       SLorn33fdWHm7ZDvXjQfuDen@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Sea Dogs @ Flying Squirrels Sea Dogs @ Flying Squirrels

Follow on MiLB First Pitch  https //stza.co/+vanS-3Z

Shop  https //stza.co/+vanS-3Q

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Sea Dogs @ Flying Squirrels
END:VALARM
DTSTART:20180612T223500Z
DTEND:20180613T013500Z
UID:SLorn33fdWHm7ZDvXjQfuDen@stanza.co
SUMMARY:Sea Dogs @ Flying Squirrels
DESCRIPTION:Sea Dogs @ Flying Squirrels\n\nFollow on MiLB First Pitch: https://stza.co/+vanS-3Z\n\nShop: https://stza.co/+vanS-3Q\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144551Z
LAST-MODIFIED:20180213T144551Z
TRANSP:OPAQUE
END:VEVENT
* Sea Dogs @ Flying Squirrels
<2018-06-13 Wed 17:35-20:35>
:PROPERTIES:
:ID:       VRBUU49x4FPgYow_aA2fNrlc@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Sea Dogs @ Flying Squirrels Sea Dogs @ Flying Squirrels

Follow on MiLB First Pitch  https //stza.co/+vanT-z

Shop  https //stza.co/+vanT-3i

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Sea Dogs @ Flying Squirrels
END:VALARM
DTSTART:20180613T223500Z
DTEND:20180614T013500Z
UID:VRBUU49x4FPgYow_aA2fNrlc@stanza.co
SUMMARY:Sea Dogs @ Flying Squirrels
DESCRIPTION:Sea Dogs @ Flying Squirrels\n\nFollow on MiLB First Pitch: https://stza.co/+vanT-z\n\nShop: https://stza.co/+vanT-3i\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144551Z
LAST-MODIFIED:20180213T144551Z
TRANSP:OPAQUE
END:VEVENT
* Sea Dogs @ Flying Squirrels
<2018-06-14 Thu 17:35-20:35>
:PROPERTIES:
:ID:       hBBpd8VPPlXrrii-Lvak0pWf@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Sea Dogs @ Flying Squirrels Sea Dogs @ Flying Squirrels

Follow on MiLB First Pitch  https //stza.co/+vanU-1w

Shop  https //stza.co/+vanU-1k

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Sea Dogs @ Flying Squirrels
END:VALARM
DTSTART:20180614T223500Z
DTEND:20180615T013500Z
UID:hBBpd8VPPlXrrii-Lvak0pWf@stanza.co
SUMMARY:Sea Dogs @ Flying Squirrels
DESCRIPTION:Sea Dogs @ Flying Squirrels\n\nFollow on MiLB First Pitch: https://stza.co/+vanU-1w\n\nShop: https://stza.co/+vanU-1k\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144551Z
LAST-MODIFIED:20180213T144551Z
TRANSP:OPAQUE
END:VEVENT
* Sea Dogs @ Baysox
<2018-06-15 Fri 18:05-21:05>
:PROPERTIES:
:ID:       _8tgordS3oaaK3T3p_nAGkxz@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Sea Dogs @ Baysox Sea Dogs @ Baysox

Follow on MiLB First Pitch  https //stza.co/+vLqg-21

Shop  https //stza.co/+vLqg-b

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Sea Dogs @ Baysox
END:VALARM
DTSTART:20180615T230500Z
DTEND:20180616T020500Z
UID:_8tgordS3oaaK3T3p_nAGkxz@stanza.co
SUMMARY:Sea Dogs @ Baysox
DESCRIPTION:Sea Dogs @ Baysox\n\nFollow on MiLB First Pitch: https://stza.co/+vLqg-21\n\nShop: https://stza.co/+vLqg-b\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144551Z
LAST-MODIFIED:20180213T144551Z
TRANSP:OPAQUE
END:VEVENT
* Sea Dogs @ Baysox
<2018-06-16 Sat 17:35-20:35>
:PROPERTIES:
:ID:       ywUPWvAiG9lxmSxQRsVbJYtK@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Sea Dogs @ Baysox Sea Dogs @ Baysox

Follow on MiLB First Pitch  https //stza.co/+vLqh-2P

Shop  https //stza.co/+vLqh-3m

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Sea Dogs @ Baysox
END:VALARM
DTSTART:20180616T223500Z
DTEND:20180617T013500Z
UID:ywUPWvAiG9lxmSxQRsVbJYtK@stanza.co
SUMMARY:Sea Dogs @ Baysox
DESCRIPTION:Sea Dogs @ Baysox\n\nFollow on MiLB First Pitch: https://stza.co/+vLqh-2P\n\nShop: https://stza.co/+vLqh-3m\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144551Z
LAST-MODIFIED:20180213T144551Z
TRANSP:OPAQUE
END:VEVENT
* Sea Dogs @ Baysox
<2018-06-17 Sun 12:35-15:35>
:PROPERTIES:
:ID:       oz_N3aQ2ct99-dlpaabOn4zl@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Sea Dogs @ Baysox Sea Dogs @ Baysox

Follow on MiLB First Pitch  https //stza.co/+vLqi-V

Shop  https //stza.co/+vLqi-3B

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Sea Dogs @ Baysox
END:VALARM
DTSTART:20180617T173500Z
DTEND:20180617T203500Z
UID:oz_N3aQ2ct99-dlpaabOn4zl@stanza.co
SUMMARY:Sea Dogs @ Baysox
DESCRIPTION:Sea Dogs @ Baysox\n\nFollow on MiLB First Pitch: https://stza.co/+vLqi-V\n\nShop: https://stza.co/+vLqi-3B\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144551Z
LAST-MODIFIED:20180213T144551Z
TRANSP:OPAQUE
END:VEVENT
* Sea Dogs vs. Fightin Phils
<2018-06-19 Tue 18:00-21:00>
:PROPERTIES:
:ID:       FDMup1HraeaKf4oUSs_fIfUh@stanza.co
:LOCATION: Jon Lester bobblehead giveaway
:STATUS:   CONFIRMED
:END:

Sea Dogs vs. Fightin Phils The first 1,000 fans to enter the ballpark will receive a Jon Lester bobblehead, courtesy of AAA.

Buy tickets here  https //stza.co/~vLrK

Follow on MiLB First Pitch  https //stza.co/+vLrK-Q

Shop  https //stza.co/+vLrK-3O

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Sea Dogs vs. Fightin Phils
END:VALARM
DTSTART:20180619T230000Z
DTEND:20180620T020000Z
UID:FDMup1HraeaKf4oUSs_fIfUh@stanza.co
SUMMARY:Sea Dogs vs. Fightin Phils
DESCRIPTION:The first 1,000 fans to enter the ballpark will receive a Jon Lester bobblehead, courtesy of AAA.\n\nBuy tickets here: https://stza.co/~vLrK\n\nFollow on MiLB First Pitch: https://stza.co/+vLrK-Q\n\nShop: https://stza.co/+vLrK-3O\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Jon Lester bobblehead giveaway
STATUS:CONFIRMED
CREATED:20180213T144551Z
LAST-MODIFIED:20180213T144551Z
TRANSP:OPAQUE
END:VEVENT
* Sea Dogs vs. Fightin Phils
<2018-06-20 Wed 18:00-21:00>
:PROPERTIES:
:ID:       MXeb_e5wZAuCWPTbNCUE0Xzp@stanza.co
:LOCATION: Goodwill Donation Drive
:STATUS:   CONFIRMED
:END:

Sea Dogs vs. Fightin Phils Goodwill Northern New England will be hosting a donation drive.  Fans are encouraged to bring bags of gently used clothing and household items to donate.

Celebrate the start of summer with the Sea Dogs.  Wear your Hawaiian Shirt to the game.  Tiki Thom and the Beach Band will be performing pre-game.

Buy tickets here  https //stza.co/~vLrM

Follow on MiLB First Pitch  https //stza.co/+vLrM-3c

Shop  https //stza.co/+vLrM-1y

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Sea Dogs vs. Fightin Phils
END:VALARM
DTSTART:20180620T230000Z
DTEND:20180621T020000Z
UID:MXeb_e5wZAuCWPTbNCUE0Xzp@stanza.co
SUMMARY:Sea Dogs vs. Fightin Phils
DESCRIPTION:Goodwill Northern New England will be hosting a donation drive.  Fans are encouraged to bring bags of gently used clothing and household items to donate.\n\nCelebrate the start of summer with the Sea Dogs.  Wear your Hawaiian Shirt to the game.  Tiki Thom and the Beach Band will be performing pre-game.\n\nBuy tickets here: https://stza.co/~vLrM\n\nFollow on MiLB First Pitch: https://stza.co/+vLrM-3c\n\nShop: https://stza.co/+vLrM-1y\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Goodwill Donation Drive
STATUS:CONFIRMED
CREATED:20180213T144551Z
LAST-MODIFIED:20180213T144551Z
TRANSP:OPAQUE
END:VEVENT
* Sea Dogs vs. Fightin Phils
<2018-06-21 Thu 17:00-20:00>
:PROPERTIES:
:ID:       gPbMBBvq12cEJ5wfyrlu5kSg@stanza.co
:LOCATION: Stick around after tonight's game for some spectacular fireworks!
:STATUS:   CONFIRMED
:END:

Sea Dogs vs. Fightin Phils After the game enjoy a fantastic fireworks show!

As part of our Throwback Thursday series, we're celebrating all things 1980's.  Come see the DeLorean Time Machine from Back to the Future.  Come dressed in your best 1980's costume!  It's going to be totally awesome!

Buy tickets here  https //stza.co/~vLrN

Follow on MiLB First Pitch  https //stza.co/+vLrN-w

Shop  https //stza.co/+vLrN-31

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Sea Dogs vs. Fightin Phils
END:VALARM
DTSTART:20180621T220000Z
DTEND:20180622T010000Z
UID:gPbMBBvq12cEJ5wfyrlu5kSg@stanza.co
SUMMARY:Sea Dogs vs. Fightin Phils
DESCRIPTION:After the game enjoy a fantastic fireworks show!\n\nAs part of our Throwback Thursday series, we're celebrating all things 1980's.  Come see the DeLorean Time Machine from Back to the Future.  Come dressed in your best 1980's costume!  It's going to be totally awesome!\n\nBuy tickets here: https://stza.co/~vLrN\n\nFollow on MiLB First Pitch: https://stza.co/+vLrN-w\n\nShop: https://stza.co/+vLrN-31\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stick around after tonight's game for some spectacular fireworks!
STATUS:CONFIRMED
CREATED:20180213T144551Z
LAST-MODIFIED:20180213T144551Z
TRANSP:OPAQUE
END:VEVENT
* Sea Dogs vs. Thunder
<2018-06-22 Fri 18:00-21:00>
:PROPERTIES:
:ID:       R0pNnWYZ8PyyHcPYcxGvVwk1@stanza.co
:LOCATION: Bark in the Park
:STATUS:   CONFIRMED
:END:

Sea Dogs vs. Thunder Take your dog out to the ballgame! Take in a game and help the Planet Dog Foundation raise money for an amazing cause.  Participate in a pre-game parade around the field led by Slugger. Tickets for you and your dog are required for this event.  Details and ticket info coming soon.



Pre-game ceremony to induct the newest members of the Teacher's Hall of Fame, presented by Unum.

Two lucky fans will win a new 32 inch T.V., courtesy of David Munster's T.V. Sales & Service

Buy tickets here  https //stza.co/~vLrQ

Follow on MiLB First Pitch  https //stza.co/+vLrQ-L

Shop  https //stza.co/+vLrQ-2L

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Sea Dogs vs. Thunder
END:VALARM
DTSTART:20180622T230000Z
DTEND:20180623T020000Z
UID:R0pNnWYZ8PyyHcPYcxGvVwk1@stanza.co
SUMMARY:Sea Dogs vs. Thunder
DESCRIPTION:Take your dog out to the ballgame! Take in a game and help the Planet Dog Foundation raise money for an amazing cause.  Participate in a pre-game parade around the field led by Slugger. Tickets for you and your dog are required for this event.  Details and ticket info coming soon.\n\n\n\nPre-game ceremony to induct the newest members of the Teacher's Hall of Fame, presented by Unum.\n\nTwo lucky fans will win a new 32 inch T.V., courtesy of David Munster's T.V. Sales & Service\n\nBuy tickets here: https://stza.co/~vLrQ\n\nFollow on MiLB First Pitch: https://stza.co/+vLrQ-L\n\nShop: https://stza.co/+vLrQ-2L\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Bark in the Park
STATUS:CONFIRMED
CREATED:20180213T144551Z
LAST-MODIFIED:20180213T144551Z
TRANSP:OPAQUE
END:VEVENT
* Sea Dogs vs. Thunder
<2018-06-23 Sat 17:00-20:00>
:PROPERTIES:
:ID:       b3ae4TZuJ58JUFEsv9oYfb-B@stanza.co
:LOCATION: The Kastaways
:STATUS:   CONFIRMED
:END:

Sea Dogs vs. Thunder The Portland Sea Dogs' mascot band; The Kastaways will be performing pre-game on the front plaza.



Buy tickets here  https //stza.co/~vLrS

Follow on MiLB First Pitch  https //stza.co/+vLrS-1U

Shop  https //stza.co/+vLrS-3c

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Sea Dogs vs. Thunder
END:VALARM
DTSTART:20180623T220000Z
DTEND:20180624T010000Z
UID:b3ae4TZuJ58JUFEsv9oYfb-B@stanza.co
SUMMARY:Sea Dogs vs. Thunder
DESCRIPTION:The Portland Sea Dogs' mascot band; The Kastaways will be performing pre-game on the front plaza.\n\n\n\nBuy tickets here: https://stza.co/~vLrS\n\nFollow on MiLB First Pitch: https://stza.co/+vLrS-1U\n\nShop: https://stza.co/+vLrS-3c\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:The Kastaways
STATUS:CONFIRMED
CREATED:20180213T144551Z
LAST-MODIFIED:20180213T144551Z
TRANSP:OPAQUE
END:VEVENT
* Sea Dogs vs. Thunder
<2018-06-24 Sun 12:00-15:00>
:PROPERTIES:
:ID:       EFdAs8XvTthCDU_sF8Ut1oSR@stanza.co
:LOCATION: Kids run the bases for today's game. Bring out the family!
:STATUS:   CONFIRMED
:END:

Sea Dogs vs. Thunder Yoga in the Outfield presented by Maine Yoga Fest-- Gates will open at 10 00 AM for all yogis participating in the 10 15-11 15, all-level yoga class, taught on Hadlock Field's outfield grass by Crisp Studio and MYF instructor Debbie Duryee. $12 ticket includes a spot for the yoga class, as well as a general admission ticket to that afternoon's 1 00 game vs. the Trenton Thunder. Contact the Ticket Office for more information.

Kids 16 and under can run the bases after the game, weather and field conditions permitting.

Buy tickets here  https //stza.co/~vLrU

Follow on MiLB First Pitch  https //stza.co/+vLrU-1w

Shop  https //stza.co/+vLrU-J

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Sea Dogs vs. Thunder
END:VALARM
DTSTART:20180624T170000Z
DTEND:20180624T200000Z
UID:EFdAs8XvTthCDU_sF8Ut1oSR@stanza.co
SUMMARY:Sea Dogs vs. Thunder
DESCRIPTION:Yoga in the Outfield presented by Maine Yoga Fest-- Gates will open at 10:00 AM for all yogis participating in the 10:15-11:15, all-level yoga class, taught on Hadlock Field's outfield grass by Crisp Studio and MYF instructor Debbie Duryee. $12 ticket includes a spot for the yoga class, as well as a general admission ticket to that afternoon's 1:00 game vs. the Trenton Thunder. Contact the Ticket Office for more information.\n\nKids 16 and under can run the bases after the game, weather and field conditions permitting.\n\nBuy tickets here: https://stza.co/~vLrU\n\nFollow on MiLB First Pitch: https://stza.co/+vLrU-1w\n\nShop: https://stza.co/+vLrU-J\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Kids run the bases for today's game. Bring out the family!
STATUS:CONFIRMED
CREATED:20180213T144551Z
LAST-MODIFIED:20180213T144551Z
TRANSP:OPAQUE
END:VEVENT
* Sea Dogs @ Fisher Cats
<2018-06-25 Mon 18:05-21:05>
:PROPERTIES:
:ID:       fgjXhhKNQMP5lEqsXrrGyvBs@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Sea Dogs @ Fisher Cats Sea Dogs @ Fisher Cats

Follow on MiLB First Pitch  https //stza.co/+vLqH-2p

Shop  https //stza.co/+vLqH-3l

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Sea Dogs @ Fisher Cats
END:VALARM
DTSTART:20180625T230500Z
DTEND:20180626T020500Z
UID:fgjXhhKNQMP5lEqsXrrGyvBs@stanza.co
SUMMARY:Sea Dogs @ Fisher Cats
DESCRIPTION:Sea Dogs @ Fisher Cats\n\nFollow on MiLB First Pitch: https://stza.co/+vLqH-2p\n\nShop: https://stza.co/+vLqH-3l\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144551Z
LAST-MODIFIED:20180213T144551Z
TRANSP:OPAQUE
END:VEVENT
* Sea Dogs @ Fisher Cats
<2018-06-26 Tue 18:05-21:05>
:PROPERTIES:
:ID:       Jfi0cd0wbJvGPQkvpI_M7Hpd@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Sea Dogs @ Fisher Cats Sea Dogs @ Fisher Cats

Follow on MiLB First Pitch  https //stza.co/+vLqI-F

Shop  https //stza.co/+vLqI-7

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Sea Dogs @ Fisher Cats
END:VALARM
DTSTART:20180626T230500Z
DTEND:20180627T020500Z
UID:Jfi0cd0wbJvGPQkvpI_M7Hpd@stanza.co
SUMMARY:Sea Dogs @ Fisher Cats
DESCRIPTION:Sea Dogs @ Fisher Cats\n\nFollow on MiLB First Pitch: https://stza.co/+vLqI-F\n\nShop: https://stza.co/+vLqI-7\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144551Z
LAST-MODIFIED:20180213T144551Z
TRANSP:OPAQUE
END:VEVENT
* Sea Dogs @ Fisher Cats
<2018-06-27 Wed 18:05-21:05>
:PROPERTIES:
:ID:       xaIFwLUNbCxo0mj3t-N4y9xA@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Sea Dogs @ Fisher Cats Sea Dogs @ Fisher Cats

Follow on MiLB First Pitch  https //stza.co/+vLqJ-38

Shop  https //stza.co/+vLqJ-1C

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Sea Dogs @ Fisher Cats
END:VALARM
DTSTART:20180627T230500Z
DTEND:20180628T020500Z
UID:xaIFwLUNbCxo0mj3t-N4y9xA@stanza.co
SUMMARY:Sea Dogs @ Fisher Cats
DESCRIPTION:Sea Dogs @ Fisher Cats\n\nFollow on MiLB First Pitch: https://stza.co/+vLqJ-38\n\nShop: https://stza.co/+vLqJ-1C\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144551Z
LAST-MODIFIED:20180213T144551Z
TRANSP:OPAQUE
END:VEVENT
* Sea Dogs @ Fisher Cats
<2018-06-28 Thu 18:05-21:05>
:PROPERTIES:
:ID:       cqnoT_OE__ZdYw-JrRf1jKYP@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Sea Dogs @ Fisher Cats Sea Dogs @ Fisher Cats

Follow on MiLB First Pitch  https //stza.co/+vLqK-2Z

Shop  https //stza.co/+vLqK-a

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Sea Dogs @ Fisher Cats
END:VALARM
DTSTART:20180628T230500Z
DTEND:20180629T020500Z
UID:cqnoT_OE__ZdYw-JrRf1jKYP@stanza.co
SUMMARY:Sea Dogs @ Fisher Cats
DESCRIPTION:Sea Dogs @ Fisher Cats\n\nFollow on MiLB First Pitch: https://stza.co/+vLqK-2Z\n\nShop: https://stza.co/+vLqK-a\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144551Z
LAST-MODIFIED:20180213T144551Z
TRANSP:OPAQUE
END:VEVENT
* Sea Dogs vs. Rumble Ponies
<2018-06-29 Fri 18:00-21:00>
:PROPERTIES:
:ID:       2tha7XdbN2hdkzCZ8sUnxSQ0@stanza.co
:LOCATION: Free T.V. Friday
:STATUS:   CONFIRMED
:END:

Sea Dogs vs. Rumble Ponies Two lucky fans will win a new 32 inch T.V., courtesy of David Munster's T.V. Sales & Service

Buy tickets here  https //stza.co/~vLrV

Follow on MiLB First Pitch  https //stza.co/+vLrV-32

Shop  https //stza.co/+vLrV-1P

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Sea Dogs vs. Rumble Ponies
END:VALARM
DTSTART:20180629T230000Z
DTEND:20180630T020000Z
UID:2tha7XdbN2hdkzCZ8sUnxSQ0@stanza.co
SUMMARY:Sea Dogs vs. Rumble Ponies
DESCRIPTION:Two lucky fans will win a new 32 inch T.V., courtesy of David Munster's T.V. Sales & Service\n\nBuy tickets here: https://stza.co/~vLrV\n\nFollow on MiLB First Pitch: https://stza.co/+vLrV-32\n\nShop: https://stza.co/+vLrV-1P\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Free T.V. Friday
STATUS:CONFIRMED
CREATED:20180213T144551Z
LAST-MODIFIED:20180213T144551Z
TRANSP:OPAQUE
END:VEVENT
* Sea Dogs vs. Rumble Ponies
<2018-06-30 Sat 17:00-20:00>
:PROPERTIES:
:ID:       aWDH8WcxfiBltbnET3VufYAi@stanza.co
:LOCATION: Tom Caron bobblehead giveaway
:STATUS:   CONFIRMED
:END:

Sea Dogs vs. Rumble Ponies The first 1,000 fans to enter the ballpark will receive a bobblehead of NESN personality and Maine native Tom Caron, courtesy of Newcastle Chrysler.

The Portland Sea Dogs' mascot band; The Kastaways will be performing pre-game on the front plaza.

Buy tickets here  https //stza.co/~vLrX

Follow on MiLB First Pitch  https //stza.co/+vLrX-

Shop  https //stza.co/+vLrX-I

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Sea Dogs vs. Rumble Ponies
END:VALARM
DTSTART:20180630T220000Z
DTEND:20180701T010000Z
UID:aWDH8WcxfiBltbnET3VufYAi@stanza.co
SUMMARY:Sea Dogs vs. Rumble Ponies
DESCRIPTION:The first 1,000 fans to enter the ballpark will receive a bobblehead of NESN personality and Maine native Tom Caron, courtesy of Newcastle Chrysler.\n\nThe Portland Sea Dogs' mascot band; The Kastaways will be performing pre-game on the front plaza.\n\nBuy tickets here: https://stza.co/~vLrX\n\nFollow on MiLB First Pitch: https://stza.co/+vLrX-\n\nShop: https://stza.co/+vLrX-I\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Tom Caron bobblehead giveaway
STATUS:CONFIRMED
CREATED:20180213T144551Z
LAST-MODIFIED:20180213T144551Z
TRANSP:OPAQUE
END:VEVENT
* Sea Dogs vs. Rumble Ponies
<2018-07-01 Sun 12:00-15:00>
:PROPERTIES:
:ID:       jD-gsiBbCEgqIK5O6ljk68Zi@stanza.co
:LOCATION: Kids run the bases for today's game. Bring out the family!
:STATUS:   CONFIRMED
:END:

Sea Dogs vs. Rumble Ponies Details to be announced

Kids 16 and under can run the bases after the game, weather and field conditions permitting.

Buy tickets here  https //stza.co/~vLrZ

Follow on MiLB First Pitch  https //stza.co/+vLrZ-1m

Shop  https //stza.co/+vLrZ-2o

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Sea Dogs vs. Rumble Ponies
END:VALARM
DTSTART:20180701T170000Z
DTEND:20180701T200000Z
UID:jD-gsiBbCEgqIK5O6ljk68Zi@stanza.co
SUMMARY:Sea Dogs vs. Rumble Ponies
DESCRIPTION:Details to be announced\n\nKids 16 and under can run the bases after the game, weather and field conditions permitting.\n\nBuy tickets here: https://stza.co/~vLrZ\n\nFollow on MiLB First Pitch: https://stza.co/+vLrZ-1m\n\nShop: https://stza.co/+vLrZ-2o\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Kids run the bases for today's game. Bring out the family!
STATUS:CONFIRMED
CREATED:20180213T144551Z
LAST-MODIFIED:20180213T144551Z
TRANSP:OPAQUE
END:VEVENT
* Sea Dogs vs. Rumble Ponies
<2018-07-02 Mon 18:00-21:00>
:PROPERTIES:
:ID:       1-QI_P8txL9EAPMh17Yncg8J@stanza.co
:LOCATION: Kevin Millar bobblehead giveaway
:STATUS:   CONFIRMED
:END:

Sea Dogs vs. Rumble Ponies The first 1,000 fans to enter the ballpark will receive a Kevin Millar bobblehead, made possible by U.S. Cellular.

Buy tickets here  https //stza.co/~vLs0

Follow on MiLB First Pitch  https //stza.co/+vLs0-3V

Shop  https //stza.co/+vLs0-2$

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Sea Dogs vs. Rumble Ponies
END:VALARM
DTSTART:20180702T230000Z
DTEND:20180703T020000Z
UID:1-QI_P8txL9EAPMh17Yncg8J@stanza.co
SUMMARY:Sea Dogs vs. Rumble Ponies
DESCRIPTION:The first 1,000 fans to enter the ballpark will receive a Kevin Millar bobblehead, made possible by U.S. Cellular.\n\nBuy tickets here: https://stza.co/~vLs0\n\nFollow on MiLB First Pitch: https://stza.co/+vLs0-3V\n\nShop: https://stza.co/+vLs0-2$\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Kevin Millar bobblehead giveaway
STATUS:CONFIRMED
CREATED:20180213T144551Z
LAST-MODIFIED:20180213T144551Z
TRANSP:OPAQUE
END:VEVENT
* Sea Dogs vs. Rumble Ponies
<2018-07-03 Tue 17:00-20:00>
:PROPERTIES:
:ID:       ZXaZhd9yivAY-6rNyqAdXo_T@stanza.co
:LOCATION: Stick around after tonight's game for some spectacular fireworks!
:STATUS:   CONFIRMED
:END:

Sea Dogs vs. Rumble Ponies Kick-off your Independance Day celebration with a baseball game and postgame fireworks, presented by Infinity Federal Credit Union.  Rene Rancourt will perform all four verses of the Star Spangled Banner.

Buy tickets here  https //stza.co/~vLs2

Follow on MiLB First Pitch  https //stza.co/+vLs2-2t

Shop  https //stza.co/+vLs2-1H

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Sea Dogs vs. Rumble Ponies
END:VALARM
DTSTART:20180703T220000Z
DTEND:20180704T010000Z
UID:ZXaZhd9yivAY-6rNyqAdXo_T@stanza.co
SUMMARY:Sea Dogs vs. Rumble Ponies
DESCRIPTION:Kick-off your Independance Day celebration with a baseball game and postgame fireworks, presented by Infinity Federal Credit Union.  Rene Rancourt will perform all four verses of the Star Spangled Banner.\n\nBuy tickets here: https://stza.co/~vLs2\n\nFollow on MiLB First Pitch: https://stza.co/+vLs2-2t\n\nShop: https://stza.co/+vLs2-1H\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stick around after tonight's game for some spectacular fireworks!
STATUS:CONFIRMED
CREATED:20180213T144551Z
LAST-MODIFIED:20180213T144551Z
TRANSP:OPAQUE
END:VEVENT
* Sea Dogs @ Yard Goats
<2018-07-04 Wed 15:05-18:05>
:PROPERTIES:
:ID:       V4x6xntPfzWoXKcbVGNXSTHK@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Sea Dogs @ Yard Goats Sea Dogs @ Yard Goats

Buy tickets here  https //stza.co/~vLqw

Follow on MiLB First Pitch  https //stza.co/+vLqw-N

Shop  https //stza.co/+vLqw-34

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Sea Dogs @ Yard Goats
END:VALARM
DTSTART:20180704T200500Z
DTEND:20180704T230500Z
UID:V4x6xntPfzWoXKcbVGNXSTHK@stanza.co
SUMMARY:Sea Dogs @ Yard Goats
DESCRIPTION:Sea Dogs @ Yard Goats\n\nBuy tickets here: https://stza.co/~vLqw\n\nFollow on MiLB First Pitch: https://stza.co/+vLqw-N\n\nShop: https://stza.co/+vLqw-34\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144551Z
LAST-MODIFIED:20180213T144551Z
TRANSP:OPAQUE
END:VEVENT
* Sea Dogs @ Yard Goats
<2018-07-05 Thu 18:05-21:05>
:PROPERTIES:
:ID:       uc231JT35MMzRs3Jvz9tvAHd@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Sea Dogs @ Yard Goats Sea Dogs @ Yard Goats

Buy tickets here  https //stza.co/~vLqx

Follow on MiLB First Pitch  https //stza.co/+vLqx-25

Shop  https //stza.co/+vLqx-1M

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Sea Dogs @ Yard Goats
END:VALARM
DTSTART:20180705T230500Z
DTEND:20180706T020500Z
UID:uc231JT35MMzRs3Jvz9tvAHd@stanza.co
SUMMARY:Sea Dogs @ Yard Goats
DESCRIPTION:Sea Dogs @ Yard Goats\n\nBuy tickets here: https://stza.co/~vLqx\n\nFollow on MiLB First Pitch: https://stza.co/+vLqx-25\n\nShop: https://stza.co/+vLqx-1M\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144551Z
LAST-MODIFIED:20180213T144551Z
TRANSP:OPAQUE
END:VEVENT
* Sea Dogs @ Yard Goats
<2018-07-06 Fri 18:05-21:05>
:PROPERTIES:
:ID:       i46dlp7hvMoGS9UVshPF0qHY@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Sea Dogs @ Yard Goats Sea Dogs @ Yard Goats

Buy tickets here  https //stza.co/~vLqy

Follow on MiLB First Pitch  https //stza.co/+vLqy-I

Shop  https //stza.co/+vLqy-2I

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Sea Dogs @ Yard Goats
END:VALARM
DTSTART:20180706T230500Z
DTEND:20180707T020500Z
UID:i46dlp7hvMoGS9UVshPF0qHY@stanza.co
SUMMARY:Sea Dogs @ Yard Goats
DESCRIPTION:Sea Dogs @ Yard Goats\n\nBuy tickets here: https://stza.co/~vLqy\n\nFollow on MiLB First Pitch: https://stza.co/+vLqy-I\n\nShop: https://stza.co/+vLqy-2I\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144551Z
LAST-MODIFIED:20180213T144551Z
TRANSP:OPAQUE
END:VEVENT
* Sea Dogs @ Yard Goats
<2018-07-07 Sat 17:05-20:05>
:PROPERTIES:
:ID:       RiNspLntCdC2crjlwEX0Pl6F@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Sea Dogs @ Yard Goats Sea Dogs @ Yard Goats

Buy tickets here  https //stza.co/~vLqz

Follow on MiLB First Pitch  https //stza.co/+vLqz-2k

Shop  https //stza.co/+vLqz-p

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Sea Dogs @ Yard Goats
END:VALARM
DTSTART:20180707T220500Z
DTEND:20180708T010500Z
UID:RiNspLntCdC2crjlwEX0Pl6F@stanza.co
SUMMARY:Sea Dogs @ Yard Goats
DESCRIPTION:Sea Dogs @ Yard Goats\n\nBuy tickets here: https://stza.co/~vLqz\n\nFollow on MiLB First Pitch: https://stza.co/+vLqz-2k\n\nShop: https://stza.co/+vLqz-p\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144551Z
LAST-MODIFIED:20180213T144551Z
TRANSP:OPAQUE
END:VEVENT
* Sea Dogs @ Yard Goats
<2018-07-08 Sun 12:05-15:05>
:PROPERTIES:
:ID:       _3B3v8_FCAm4DAHcuRTgsw4f@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Sea Dogs @ Yard Goats Sea Dogs @ Yard Goats

Buy tickets here  https //stza.co/~vLqA

Follow on MiLB First Pitch  https //stza.co/+vLqA-3s

Shop  https //stza.co/+vLqA-1b

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Sea Dogs @ Yard Goats
END:VALARM
DTSTART:20180708T170500Z
DTEND:20180708T200500Z
UID:_3B3v8_FCAm4DAHcuRTgsw4f@stanza.co
SUMMARY:Sea Dogs @ Yard Goats
DESCRIPTION:Sea Dogs @ Yard Goats\n\nBuy tickets here: https://stza.co/~vLqA\n\nFollow on MiLB First Pitch: https://stza.co/+vLqA-3s\n\nShop: https://stza.co/+vLqA-1b\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144551Z
LAST-MODIFIED:20180213T144551Z
TRANSP:OPAQUE
END:VEVENT
* Sea Dogs vs. Fisher Cats
<2018-07-12 Thu 18:00-21:00>
:PROPERTIES:
:ID:       WbPmBukh9OslFepwzA6T4SNg@stanza.co
:LOCATION: Gorham Community Night
:STATUS:   CONFIRMED
:END:

Sea Dogs vs. Fisher Cats Come enjoy a fun and exciting night at the ballpark, while recognizing individuals and organizations for their hard work and dedication to the Gorham Community

Buy tickets here  https //stza.co/~vLs4

Follow on MiLB First Pitch  https //stza.co/+vLs4-1R

Shop  https //stza.co/+vLs4-D

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Sea Dogs vs. Fisher Cats
END:VALARM
DTSTART:20180712T230000Z
DTEND:20180713T020000Z
UID:WbPmBukh9OslFepwzA6T4SNg@stanza.co
SUMMARY:Sea Dogs vs. Fisher Cats
DESCRIPTION:Come enjoy a fun and exciting night at the ballpark, while recognizing individuals and organizations for their hard work and dedication to the Gorham Community\n\nBuy tickets here: https://stza.co/~vLs4\n\nFollow on MiLB First Pitch: https://stza.co/+vLs4-1R\n\nShop: https://stza.co/+vLs4-D\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Gorham Community Night
STATUS:CONFIRMED
CREATED:20180213T144551Z
LAST-MODIFIED:20180213T144551Z
TRANSP:OPAQUE
END:VEVENT
* Sea Dogs vs. Fisher Cats
<2018-07-13 Fri 18:00-21:00>
:PROPERTIES:
:ID:       pVSn9yYYhp9gCSoM7xJCQHZc@stanza.co
:LOCATION: Field of Screams/ Halloween at Hadlock
:STATUS:   CONFIRMED
:END:

Sea Dogs vs. Fisher Cats The Sea Dogs will be turning the Field of Dreams into the Field of Screams for  Friday the 13th!  Fans are encouraged to come dressed in their favorite Halloween costume and participate in a pre-game Monster Mash around the field.  Prizes for best kids and adult costumes.

Two lucky fans will win a new 32 inch T.V., courtesy of David Munster's T.V. Sales & Service

Buy tickets here  https //stza.co/~vLs6

Follow on MiLB First Pitch  https //stza.co/+vLs6-2f

Shop  https //stza.co/+vLs6-2E

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Sea Dogs vs. Fisher Cats
END:VALARM
DTSTART:20180713T230000Z
DTEND:20180714T020000Z
UID:pVSn9yYYhp9gCSoM7xJCQHZc@stanza.co
SUMMARY:Sea Dogs vs. Fisher Cats
DESCRIPTION:The Sea Dogs will be turning the Field of Dreams into the Field of Screams for  Friday the 13th!  Fans are encouraged to come dressed in their favorite Halloween costume and participate in a pre-game Monster Mash around the field.  Prizes for best kids and adult costumes.\n\nTwo lucky fans will win a new 32 inch T.V., courtesy of David Munster's T.V. Sales & Service\n\nBuy tickets here: https://stza.co/~vLs6\n\nFollow on MiLB First Pitch: https://stza.co/+vLs6-2f\n\nShop: https://stza.co/+vLs6-2E\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Field of Screams/ Halloween at Hadlock
STATUS:CONFIRMED
CREATED:20180213T144551Z
LAST-MODIFIED:20180213T144551Z
TRANSP:OPAQUE
END:VEVENT
* Sea Dogs vs. Fisher Cats
<2018-07-14 Sat 17:00-20:00>
:PROPERTIES:
:ID:       f_yE2fd5dJmQ7bCqkI7ZkPZt@stanza.co
:LOCATION: The Kastaways
:STATUS:   CONFIRMED
:END:

Sea Dogs vs. Fisher Cats The Portland Sea Dogs' mascot band; The Kastaways will be performing pre-game on the front plaza.



Buy tickets here  https //stza.co/~vLs7

Follow on MiLB First Pitch  https //stza.co/+vLs7-2M

Shop  https //stza.co/+vLs7-1S

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Sea Dogs vs. Fisher Cats
END:VALARM
DTSTART:20180714T220000Z
DTEND:20180715T010000Z
UID:f_yE2fd5dJmQ7bCqkI7ZkPZt@stanza.co
SUMMARY:Sea Dogs vs. Fisher Cats
DESCRIPTION:The Portland Sea Dogs' mascot band; The Kastaways will be performing pre-game on the front plaza.\n\n\n\nBuy tickets here: https://stza.co/~vLs7\n\nFollow on MiLB First Pitch: https://stza.co/+vLs7-2M\n\nShop: https://stza.co/+vLs7-1S\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:The Kastaways
STATUS:CONFIRMED
CREATED:20180213T144551Z
LAST-MODIFIED:20180213T144551Z
TRANSP:OPAQUE
END:VEVENT
* Sea Dogs vs. Fisher Cats
<2018-07-15 Sun 12:00-15:00>
:PROPERTIES:
:ID:       3swGAHVdQEIoLeuzVVrbZEj7@stanza.co
:LOCATION: Kids run the bases for today's game. Bring out the family!
:STATUS:   CONFIRMED
:END:

Sea Dogs vs. Fisher Cats Kids 16 and under can run the bases after the game, weather and field conditions permitting.



Buy tickets here  https //stza.co/~vLs9

Follow on MiLB First Pitch  https //stza.co/+vLs9-F

Shop  https //stza.co/+vLs9-36

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Sea Dogs vs. Fisher Cats
END:VALARM
DTSTART:20180715T170000Z
DTEND:20180715T200000Z
UID:3swGAHVdQEIoLeuzVVrbZEj7@stanza.co
SUMMARY:Sea Dogs vs. Fisher Cats
DESCRIPTION:Kids 16 and under can run the bases after the game, weather and field conditions permitting.\n\n\n\nBuy tickets here: https://stza.co/~vLs9\n\nFollow on MiLB First Pitch: https://stza.co/+vLs9-F\n\nShop: https://stza.co/+vLs9-36\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Kids run the bases for today's game. Bring out the family!
STATUS:CONFIRMED
CREATED:20180213T144551Z
LAST-MODIFIED:20180213T144551Z
TRANSP:OPAQUE
END:VEVENT
* Sea Dogs @ Rumble Ponies
<2018-07-16 Mon 17:35-20:35>
:PROPERTIES:
:ID:       keGU_uVkpYxJy87aEK4sErrs@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Sea Dogs @ Rumble Ponies Sea Dogs @ Rumble Ponies

Follow on MiLB First Pitch  https //stza.co/+vLq9-k

Shop  https //stza.co/+vLq9-3i

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Sea Dogs @ Rumble Ponies
END:VALARM
DTSTART:20180716T223500Z
DTEND:20180717T013500Z
UID:keGU_uVkpYxJy87aEK4sErrs@stanza.co
SUMMARY:Sea Dogs @ Rumble Ponies
DESCRIPTION:Sea Dogs @ Rumble Ponies\n\nFollow on MiLB First Pitch: https://stza.co/+vLq9-k\n\nShop: https://stza.co/+vLq9-3i\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144551Z
LAST-MODIFIED:20180213T144551Z
TRANSP:OPAQUE
END:VEVENT
* Sea Dogs @ Rumble Ponies
<2018-07-17 Tue 17:35-20:35>
:PROPERTIES:
:ID:       H6OYnpB-eZUSk6i0MhrZTBgy@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Sea Dogs @ Rumble Ponies Sea Dogs @ Rumble Ponies

Follow on MiLB First Pitch  https //stza.co/+vLqa-3Y

Shop  https //stza.co/+vLqa-2T

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Sea Dogs @ Rumble Ponies
END:VALARM
DTSTART:20180717T223500Z
DTEND:20180718T013500Z
UID:H6OYnpB-eZUSk6i0MhrZTBgy@stanza.co
SUMMARY:Sea Dogs @ Rumble Ponies
DESCRIPTION:Sea Dogs @ Rumble Ponies\n\nFollow on MiLB First Pitch: https://stza.co/+vLqa-3Y\n\nShop: https://stza.co/+vLqa-2T\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144551Z
LAST-MODIFIED:20180213T144551Z
TRANSP:OPAQUE
END:VEVENT
* Sea Dogs @ Rumble Ponies
<2018-07-18 Wed 12:05-15:05>
:PROPERTIES:
:ID:       aRetvc0UJpxIV8LaYL8MSJ2s@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Sea Dogs @ Rumble Ponies Sea Dogs @ Rumble Ponies

Follow on MiLB First Pitch  https //stza.co/+vLqb-2M

Shop  https //stza.co/+vLqb-Q

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Sea Dogs @ Rumble Ponies
END:VALARM
DTSTART:20180718T170500Z
DTEND:20180718T200500Z
UID:aRetvc0UJpxIV8LaYL8MSJ2s@stanza.co
SUMMARY:Sea Dogs @ Rumble Ponies
DESCRIPTION:Sea Dogs @ Rumble Ponies\n\nFollow on MiLB First Pitch: https://stza.co/+vLqb-2M\n\nShop: https://stza.co/+vLqb-Q\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144551Z
LAST-MODIFIED:20180213T144551Z
TRANSP:OPAQUE
END:VEVENT
* Sea Dogs vs. Yard Goats
<2018-07-19 Thu 18:00-21:00>
:PROPERTIES:
:ID:       7OW_8qHY7htYLaAAUfE65BWv@stanza.co
:LOCATION: Brunswick Community Night
:STATUS:   CONFIRMED
:END:

Sea Dogs vs. Yard Goats Come enjoy a fun and exciting night at the ballpark, while recognizing individuals and organizations for their hard work and dedication to the Brunswick Community

Buy tickets here  https //stza.co/~vLsb

Follow on MiLB First Pitch  https //stza.co/+vLsb-7

Shop  https //stza.co/+vLsb-g

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Sea Dogs vs. Yard Goats
END:VALARM
DTSTART:20180719T230000Z
DTEND:20180720T020000Z
UID:7OW_8qHY7htYLaAAUfE65BWv@stanza.co
SUMMARY:Sea Dogs vs. Yard Goats
DESCRIPTION:Come enjoy a fun and exciting night at the ballpark, while recognizing individuals and organizations for their hard work and dedication to the Brunswick Community\n\nBuy tickets here: https://stza.co/~vLsb\n\nFollow on MiLB First Pitch: https://stza.co/+vLsb-7\n\nShop: https://stza.co/+vLsb-g\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Brunswick Community Night
STATUS:CONFIRMED
CREATED:20180213T144551Z
LAST-MODIFIED:20180213T144551Z
TRANSP:OPAQUE
END:VEVENT
* Sea Dogs vs. Yard Goats
<2018-07-20 Fri 18:00-21:00>
:PROPERTIES:
:ID:       78h4BxUqMsaS20ukoxTw-mac@stanza.co
:LOCATION: ZOOperstars!
:STATUS:   CONFIRMED
:END:

Sea Dogs vs. Yard Goats The hilarious ZOOperstars! will rock the house with comedic routines that fans of all ages will love!

Two lucky fans will win a new 32 inch T.V., courtesy of David Munster's T.V. Sales & Service



Buy tickets here  https //stza.co/~vLsd

Follow on MiLB First Pitch  https //stza.co/+vLsd-11

Shop  https //stza.co/+vLsd-2X

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Sea Dogs vs. Yard Goats
END:VALARM
DTSTART:20180720T230000Z
DTEND:20180721T020000Z
UID:78h4BxUqMsaS20ukoxTw-mac@stanza.co
SUMMARY:Sea Dogs vs. Yard Goats
DESCRIPTION:The hilarious ZOOperstars! will rock the house with comedic routines that fans of all ages will love!\n\nTwo lucky fans will win a new 32 inch T.V., courtesy of David Munster's T.V. Sales & Service\n\n\n\nBuy tickets here: https://stza.co/~vLsd\n\nFollow on MiLB First Pitch: https://stza.co/+vLsd-11\n\nShop: https://stza.co/+vLsd-2X\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:ZOOperstars!
STATUS:CONFIRMED
CREATED:20180213T144551Z
LAST-MODIFIED:20180213T144551Z
TRANSP:OPAQUE
END:VEVENT
* Sea Dogs vs. Yard Goats
<2018-07-21 Sat 17:00-20:00>
:PROPERTIES:
:ID:       IjCtPvA8xLKFuHi1IoEcfbjN@stanza.co
:LOCATION: Stick around after tonight's game for some spectacular fireworks!
:STATUS:   CONFIRMED
:END:

Sea Dogs vs. Yard Goats Enjoy a post-game fireworks show, brought to you by New England Ford.

The Portland Sea Dogs' mascot band; The Kastaways will be performing pre-game on the front plaza.

Buy tickets here  https //stza.co/~vLsf

Follow on MiLB First Pitch  https //stza.co/+vLsf-1e

Shop  https //stza.co/+vLsf-2b

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Sea Dogs vs. Yard Goats
END:VALARM
DTSTART:20180721T220000Z
DTEND:20180722T010000Z
UID:IjCtPvA8xLKFuHi1IoEcfbjN@stanza.co
SUMMARY:Sea Dogs vs. Yard Goats
DESCRIPTION:Enjoy a post-game fireworks show, brought to you by New England Ford.\n\nThe Portland Sea Dogs' mascot band; The Kastaways will be performing pre-game on the front plaza.\n\nBuy tickets here: https://stza.co/~vLsf\n\nFollow on MiLB First Pitch: https://stza.co/+vLsf-1e\n\nShop: https://stza.co/+vLsf-2b\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stick around after tonight's game for some spectacular fireworks!
STATUS:CONFIRMED
CREATED:20180213T144551Z
LAST-MODIFIED:20180213T144551Z
TRANSP:OPAQUE
END:VEVENT
* Sea Dogs vs. Yard Goats
<2018-07-22 Sun 12:00-15:00>
:PROPERTIES:
:ID:       qaMjdUX0o0Gmsy_qXnwxGOt-@stanza.co
:LOCATION: Kids run the bases for today's game. Bring out the family!
:STATUS:   CONFIRMED
:END:

Sea Dogs vs. Yard Goats Dress up as a princess or a pirate and participate in a pre-game tea party and parade around the field.  Please arrive by 12 00 PM to participate in the festivities.

Kids 16 and under can run the bases after the game, weather and field conditions permitting.

Buy tickets here  https //stza.co/~vLsh

Follow on MiLB First Pitch  https //stza.co/+vLsh-X

Shop  https //stza.co/+vLsh-1

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Sea Dogs vs. Yard Goats
END:VALARM
DTSTART:20180722T170000Z
DTEND:20180722T200000Z
UID:qaMjdUX0o0Gmsy_qXnwxGOt-@stanza.co
SUMMARY:Sea Dogs vs. Yard Goats
DESCRIPTION:Dress up as a princess or a pirate and participate in a pre-game tea party and parade around the field.  Please arrive by 12:00 PM to participate in the festivities.\n\nKids 16 and under can run the bases after the game, weather and field conditions permitting.\n\nBuy tickets here: https://stza.co/~vLsh\n\nFollow on MiLB First Pitch: https://stza.co/+vLsh-X\n\nShop: https://stza.co/+vLsh-1\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Kids run the bases for today's game. Bring out the family!
STATUS:CONFIRMED
CREATED:20180213T144551Z
LAST-MODIFIED:20180213T144551Z
TRANSP:OPAQUE
END:VEVENT
* Sea Dogs vs. Senators
<2018-07-23 Mon 18:00-21:00>
:PROPERTIES:
:ID:       8BqD8ho5lh8I3zSY3_jNHtKQ@stanza.co
:LOCATION: Dustin Pedroia bobblehead giveaway
:STATUS:   CONFIRMED
:END:

Sea Dogs vs. Senators The first 1,000 fans to enter the ballpark will receive a Dustin Pedroia bobblehead, courtesy of Bath Savings.

Buy tickets here  https //stza.co/~vLsk

Follow on MiLB First Pitch  https //stza.co/+vLsk-3J

Shop  https //stza.co/+vLsk-1A

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Sea Dogs vs. Senators
END:VALARM
DTSTART:20180723T230000Z
DTEND:20180724T020000Z
UID:8BqD8ho5lh8I3zSY3_jNHtKQ@stanza.co
SUMMARY:Sea Dogs vs. Senators
DESCRIPTION:The first 1,000 fans to enter the ballpark will receive a Dustin Pedroia bobblehead, courtesy of Bath Savings.\n\nBuy tickets here: https://stza.co/~vLsk\n\nFollow on MiLB First Pitch: https://stza.co/+vLsk-3J\n\nShop: https://stza.co/+vLsk-1A\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Dustin Pedroia bobblehead giveaway
STATUS:CONFIRMED
CREATED:20180213T144551Z
LAST-MODIFIED:20180213T144551Z
TRANSP:OPAQUE
END:VEVENT
* Sea Dogs vs. Senators
<2018-07-24 Tue 18:00-21:00>
:PROPERTIES:
:ID:       2BeS37H7xfvieKr6Rx8PHExZ@stanza.co
:LOCATION: Faith & Family Night
:STATUS:   CONFIRMED
:END:

Sea Dogs vs. Senators The Portland Sea Dogs are proud to present a special pre-game acoustic set with members of Central Worship, the worship band of Kennebec Community Church in Augusta, ME. The concert will be from 5 45-6 30 with the game to follow at 7 00 PM.



Buy tickets here  https //stza.co/~vLsm

Follow on MiLB First Pitch  https //stza.co/+vLsm-V

Shop  https //stza.co/+vLsm-1d

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Sea Dogs vs. Senators
END:VALARM
DTSTART:20180724T230000Z
DTEND:20180725T020000Z
UID:2BeS37H7xfvieKr6Rx8PHExZ@stanza.co
SUMMARY:Sea Dogs vs. Senators
DESCRIPTION:The Portland Sea Dogs are proud to present a special pre-game acoustic set with members of Central Worship, the worship band of Kennebec Community Church in Augusta, ME. The concert will be from 5:45-6:30 with the game to follow at 7:00 PM.\n\n\n\nBuy tickets here: https://stza.co/~vLsm\n\nFollow on MiLB First Pitch: https://stza.co/+vLsm-V\n\nShop: https://stza.co/+vLsm-1d\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Faith & Family Night
STATUS:CONFIRMED
CREATED:20180213T144551Z
LAST-MODIFIED:20180213T144551Z
TRANSP:OPAQUE
END:VEVENT
* Sea Dogs vs. Senators
<2018-07-25 Wed 11:00-14:00>
:PROPERTIES:
:ID:       eR_1_7I4rqf4jwrgawentIh5@stanza.co
:LOCATION: Spirit Day
:STATUS:   CONFIRMED
:END:

Sea Dogs vs. Senators Special 12 00 PM start time. Parks & Rec groups along with camps will participate in spirit day competitions throughout the game. 

Buy tickets here  https //stza.co/~vLsn

Follow on MiLB First Pitch  https //stza.co/+vLsn-2o

Shop  https //stza.co/+vLsn-3S

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Sea Dogs vs. Senators
END:VALARM
DTSTART:20180725T160000Z
DTEND:20180725T190000Z
UID:eR_1_7I4rqf4jwrgawentIh5@stanza.co
SUMMARY:Sea Dogs vs. Senators
DESCRIPTION:Special 12:00 PM start time. Parks & Rec groups along with camps will participate in spirit day competitions throughout the game. \n\nBuy tickets here: https://stza.co/~vLsn\n\nFollow on MiLB First Pitch: https://stza.co/+vLsn-2o\n\nShop: https://stza.co/+vLsn-3S\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Spirit Day
STATUS:CONFIRMED
CREATED:20180213T144551Z
LAST-MODIFIED:20180213T144551Z
TRANSP:OPAQUE
END:VEVENT
* Sea Dogs @ Thunder
<2018-07-26 Thu 18:00-21:00>
:PROPERTIES:
:ID:       RF2RvAt5Y0MPjuH2IFUYkdBn@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Sea Dogs @ Thunder Sea Dogs @ Thunder

Follow on MiLB First Pitch  https //stza.co/+vanY-34

Shop  https //stza.co/+vanY-1i

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Sea Dogs @ Thunder
END:VALARM
DTSTART:20180726T230000Z
DTEND:20180727T020000Z
UID:RF2RvAt5Y0MPjuH2IFUYkdBn@stanza.co
SUMMARY:Sea Dogs @ Thunder
DESCRIPTION:Sea Dogs @ Thunder\n\nFollow on MiLB First Pitch: https://stza.co/+vanY-34\n\nShop: https://stza.co/+vanY-1i\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144551Z
LAST-MODIFIED:20180213T144551Z
TRANSP:OPAQUE
END:VEVENT
* Sea Dogs @ Thunder
<2018-07-27 Fri 18:00-21:00>
:PROPERTIES:
:ID:       VY7NzUgAc7SgEzrWYPgdBI-h@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Sea Dogs @ Thunder Sea Dogs @ Thunder

Follow on MiLB First Pitch  https //stza.co/+vanZ-J

Shop  https //stza.co/+vanZ-2v

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Sea Dogs @ Thunder
END:VALARM
DTSTART:20180727T230000Z
DTEND:20180728T020000Z
UID:VY7NzUgAc7SgEzrWYPgdBI-h@stanza.co
SUMMARY:Sea Dogs @ Thunder
DESCRIPTION:Sea Dogs @ Thunder\n\nFollow on MiLB First Pitch: https://stza.co/+vanZ-J\n\nShop: https://stza.co/+vanZ-2v\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144551Z
LAST-MODIFIED:20180213T144551Z
TRANSP:OPAQUE
END:VEVENT
* Sea Dogs @ Thunder
<2018-07-28 Sat 18:00-21:00>
:PROPERTIES:
:ID:       Wq7lJOaHHL05pUeT1MbDjdZs@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Sea Dogs @ Thunder Sea Dogs @ Thunder

Follow on MiLB First Pitch  https //stza.co/+van_-1

Shop  https //stza.co/+van_-25

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Sea Dogs @ Thunder
END:VALARM
DTSTART:20180728T230000Z
DTEND:20180729T020000Z
UID:Wq7lJOaHHL05pUeT1MbDjdZs@stanza.co
SUMMARY:Sea Dogs @ Thunder
DESCRIPTION:Sea Dogs @ Thunder\n\nFollow on MiLB First Pitch: https://stza.co/+van_-1\n\nShop: https://stza.co/+van_-25\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144551Z
LAST-MODIFIED:20180213T144551Z
TRANSP:OPAQUE
END:VEVENT
* Sea Dogs @ Thunder
<2018-07-29 Sun 16:00-19:00>
:PROPERTIES:
:ID:       fd6PTywhw6VFNRBMYhPjQiQh@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Sea Dogs @ Thunder Sea Dogs @ Thunder

Follow on MiLB First Pitch  https //stza.co/+van$-P

Shop  https //stza.co/+van$-Q

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Sea Dogs @ Thunder
END:VALARM
DTSTART:20180729T210000Z
DTEND:20180730T000000Z
UID:fd6PTywhw6VFNRBMYhPjQiQh@stanza.co
SUMMARY:Sea Dogs @ Thunder
DESCRIPTION:Sea Dogs @ Thunder\n\nFollow on MiLB First Pitch: https://stza.co/+van$-P\n\nShop: https://stza.co/+van$-Q\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144551Z
LAST-MODIFIED:20180213T144551Z
TRANSP:OPAQUE
END:VEVENT
* Sea Dogs vs. SeaWolves
<2018-07-31 Tue 18:00-21:00>
:PROPERTIES:
:ID:       1KOhxedjqzBkeT5H-g2fQvEe@stanza.co
:LOCATION: Harry Potter Night
:STATUS:   CONFIRMED
:END:

Sea Dogs vs. SeaWolves Enjoy a magical day as you enter Hadlock's School of Witchcraft and Wizardry.  Make sure to wear your finest robes to participate in a pregame parade around the warning track.  Please arrive by 6 00 PM to participate in pre-game activities.

Buy tickets here  https //stza.co/~vLsq

Follow on MiLB First Pitch  https //stza.co/+vLsq-3g

Shop  https //stza.co/+vLsq-2Y

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Sea Dogs vs. SeaWolves
END:VALARM
DTSTART:20180731T230000Z
DTEND:20180801T020000Z
UID:1KOhxedjqzBkeT5H-g2fQvEe@stanza.co
SUMMARY:Sea Dogs vs. SeaWolves
DESCRIPTION:Enjoy a magical day as you enter Hadlock's School of Witchcraft and Wizardry.  Make sure to wear your finest robes to participate in a pregame parade around the warning track.  Please arrive by 6:00 PM to participate in pre-game activities.\n\nBuy tickets here: https://stza.co/~vLsq\n\nFollow on MiLB First Pitch: https://stza.co/+vLsq-3g\n\nShop: https://stza.co/+vLsq-2Y\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Harry Potter Night
STATUS:CONFIRMED
CREATED:20180213T144551Z
LAST-MODIFIED:20180213T144551Z
TRANSP:OPAQUE
END:VEVENT
* Sea Dogs vs. SeaWolves
<2018-08-01 Wed 18:00-21:00>
:PROPERTIES:
:ID:       ZmgIMxQG6MFAjlWgaJl0ja1M@stanza.co
:LOCATION: Rafael Devers bobblehead giveaway
:STATUS:   CONFIRMED
:END:

Sea Dogs vs. SeaWolves The first 1,000 fans to enter the ballpark will receive a Rafael Devers bobblehead, courtesy of Northeast Laboratory Services.



Buy tickets here  https //stza.co/~vLsr

Follow on MiLB First Pitch  https //stza.co/+vLsr-1m

Shop  https //stza.co/+vLsr-O

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Sea Dogs vs. SeaWolves
END:VALARM
DTSTART:20180801T230000Z
DTEND:20180802T020000Z
UID:ZmgIMxQG6MFAjlWgaJl0ja1M@stanza.co
SUMMARY:Sea Dogs vs. SeaWolves
DESCRIPTION:The first 1,000 fans to enter the ballpark will receive a Rafael Devers bobblehead, courtesy of Northeast Laboratory Services.\n\n\n\nBuy tickets here: https://stza.co/~vLsr\n\nFollow on MiLB First Pitch: https://stza.co/+vLsr-1m\n\nShop: https://stza.co/+vLsr-O\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Rafael Devers bobblehead giveaway
STATUS:CONFIRMED
CREATED:20180213T144551Z
LAST-MODIFIED:20180213T144551Z
TRANSP:OPAQUE
END:VEVENT
* Sea Dogs vs. SeaWolves
<2018-08-02 Thu 11:00-14:00>
:PROPERTIES:
:ID:       4cJPaR5rZNcH5WL_7HuA0IQ4@stanza.co
:LOCATION: Spirit Day
:STATUS:   CONFIRMED
:END:

Sea Dogs vs. SeaWolves Special 12 00 PM start time. Parks & Rec groups along with camps will participate in spirit day competitions throughout the game. 

Buy tickets here  https //stza.co/~vLst

Follow on MiLB First Pitch  https //stza.co/+vLst-1B

Shop  https //stza.co/+vLst-2v

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Sea Dogs vs. SeaWolves
END:VALARM
DTSTART:20180802T160000Z
DTEND:20180802T190000Z
UID:4cJPaR5rZNcH5WL_7HuA0IQ4@stanza.co
SUMMARY:Sea Dogs vs. SeaWolves
DESCRIPTION:Special 12:00 PM start time. Parks & Rec groups along with camps will participate in spirit day competitions throughout the game. \n\nBuy tickets here: https://stza.co/~vLst\n\nFollow on MiLB First Pitch: https://stza.co/+vLst-1B\n\nShop: https://stza.co/+vLst-2v\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Spirit Day
STATUS:CONFIRMED
CREATED:20180213T144551Z
LAST-MODIFIED:20180213T144551Z
TRANSP:OPAQUE
END:VEVENT
* Sea Dogs vs. Flying Squirrels
<2018-08-03 Fri 18:00-21:00>
:PROPERTIES:
:ID:       iKBOTKLnCDvmQNyxOfKPArx5@stanza.co
:LOCATION: Free T.V. Friday
:STATUS:   CONFIRMED
:END:

Sea Dogs vs. Flying Squirrels Two lucky fans will win a new 32 inch T.V., courtesy of David Munster's T.V. Sales & Service

Buy tickets here  https //stza.co/~vLsv

Follow on MiLB First Pitch  https //stza.co/+vLsv-Q

Shop  https //stza.co/+vLsv-1P

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Sea Dogs vs. Flying Squirrels
END:VALARM
DTSTART:20180803T230000Z
DTEND:20180804T020000Z
UID:iKBOTKLnCDvmQNyxOfKPArx5@stanza.co
SUMMARY:Sea Dogs vs. Flying Squirrels
DESCRIPTION:Two lucky fans will win a new 32 inch T.V., courtesy of David Munster's T.V. Sales & Service\n\nBuy tickets here: https://stza.co/~vLsv\n\nFollow on MiLB First Pitch: https://stza.co/+vLsv-Q\n\nShop: https://stza.co/+vLsv-1P\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Free T.V. Friday
STATUS:CONFIRMED
CREATED:20180213T144551Z
LAST-MODIFIED:20180213T144551Z
TRANSP:OPAQUE
END:VEVENT
* Sea Dogs vs. Flying Squirrels
<2018-08-04 Sat 17:00-20:00>
:PROPERTIES:
:ID:       UGZstMbjrIjGmZ1-tjjoLjD3@stanza.co
:LOCATION: May the force be with you! Come check out Stars Wars Night at the park
:STATUS:   CONFIRMED
:END:

Sea Dogs vs. Flying Squirrels The Sea Dogs will be wearing specially designed BB-8 jerseys that will be auctioned off to benefit Make-A-Wish Maine.  Special appearances by Star Wars characters from the Mandalorian Mercs Costuming Club-Wampa Clan and Paul's R2-D2.  Fans are encouraged to come dressed as their favorite Star Wars character and participate in a pre-game parade, please arrive by 5 00 PM to participate.  Prizes for best costumes.  Star Wars music, clips, trivia, and more!

The Portland Sea Dogs' mascot band; The Kastaways will be performing pre-game on the front plaza.

Buy tickets here  https //stza.co/~vLsy

Follow on MiLB First Pitch  https //stza.co/+vLsy-U

Shop  https //stza.co/+vLsy-32

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Sea Dogs vs. Flying Squirrels
END:VALARM
DTSTART:20180804T220000Z
DTEND:20180805T010000Z
UID:UGZstMbjrIjGmZ1-tjjoLjD3@stanza.co
SUMMARY:Sea Dogs vs. Flying Squirrels
DESCRIPTION:The Sea Dogs will be wearing specially designed BB-8 jerseys that will be auctioned off to benefit Make-A-Wish Maine.  Special appearances by Star Wars characters from the Mandalorian Mercs Costuming Club-Wampa Clan and Paul's R2-D2.  Fans are encouraged to come dressed as their favorite Star Wars character and participate in a pre-game parade, please arrive by 5:00 PM to participate.  Prizes for best costumes.  Star Wars music, clips, trivia, and more!\n\nThe Portland Sea Dogs' mascot band; The Kastaways will be performing pre-game on the front plaza.\n\nBuy tickets here: https://stza.co/~vLsy\n\nFollow on MiLB First Pitch: https://stza.co/+vLsy-U\n\nShop: https://stza.co/+vLsy-32\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:May the force be with you! Come check out Stars Wars Night at the park
STATUS:CONFIRMED
CREATED:20180213T144551Z
LAST-MODIFIED:20180213T144551Z
TRANSP:OPAQUE
END:VEVENT
* Sea Dogs vs. Flying Squirrels
<2018-08-05 Sun 12:00-15:00>
:PROPERTIES:
:ID:       xIGWuXpmJfRxTVK63IdHugfv@stanza.co
:LOCATION: Kids run the bases for today's game. Bring out the family!
:STATUS:   CONFIRMED
:END:

Sea Dogs vs. Flying Squirrels Fans are invited to come play catch on the field prior to the game from 10 00-11 15 AM.  A ticket to the August 5th game is required.

Kids 16 and under can run the bases after the game, weather and field conditions permitting.

Buy tickets here  https //stza.co/~vLsz

Follow on MiLB First Pitch  https //stza.co/+vLsz-31

Shop  https //stza.co/+vLsz-1G

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Sea Dogs vs. Flying Squirrels
END:VALARM
DTSTART:20180805T170000Z
DTEND:20180805T200000Z
UID:xIGWuXpmJfRxTVK63IdHugfv@stanza.co
SUMMARY:Sea Dogs vs. Flying Squirrels
DESCRIPTION:Fans are invited to come play catch on the field prior to the game from 10:00-11:15 AM.  A ticket to the August 5th game is required.\n\nKids 16 and under can run the bases after the game, weather and field conditions permitting.\n\nBuy tickets here: https://stza.co/~vLsz\n\nFollow on MiLB First Pitch: https://stza.co/+vLsz-31\n\nShop: https://stza.co/+vLsz-1G\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Kids run the bases for today's game. Bring out the family!
STATUS:CONFIRMED
CREATED:20180213T144551Z
LAST-MODIFIED:20180213T144551Z
TRANSP:OPAQUE
END:VEVENT
* Sea Dogs @ SeaWolves
<2018-08-07 Tue 18:05-21:05>
:PROPERTIES:
:ID:       pX_xVA0qi97rxg7PoW-W7s6h@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Sea Dogs @ SeaWolves Sea Dogs @ SeaWolves

Follow on MiLB First Pitch  https //stza.co/+vLqj-24

Shop  https //stza.co/+vLqj-V

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Sea Dogs @ SeaWolves
END:VALARM
DTSTART:20180807T230500Z
DTEND:20180808T020500Z
UID:pX_xVA0qi97rxg7PoW-W7s6h@stanza.co
SUMMARY:Sea Dogs @ SeaWolves
DESCRIPTION:Sea Dogs @ SeaWolves\n\nFollow on MiLB First Pitch: https://stza.co/+vLqj-24\n\nShop: https://stza.co/+vLqj-V\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144551Z
LAST-MODIFIED:20180213T144551Z
TRANSP:OPAQUE
END:VEVENT
* Sea Dogs @ SeaWolves
<2018-08-08 Wed 18:05-21:05>
:PROPERTIES:
:ID:       MEaoQaoTtd_BabPWks99m6NP@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Sea Dogs @ SeaWolves Sea Dogs @ SeaWolves

Follow on MiLB First Pitch  https //stza.co/+vLqk-3B

Shop  https //stza.co/+vLqk-2C

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Sea Dogs @ SeaWolves
END:VALARM
DTSTART:20180808T230500Z
DTEND:20180809T020500Z
UID:MEaoQaoTtd_BabPWks99m6NP@stanza.co
SUMMARY:Sea Dogs @ SeaWolves
DESCRIPTION:Sea Dogs @ SeaWolves\n\nFollow on MiLB First Pitch: https://stza.co/+vLqk-3B\n\nShop: https://stza.co/+vLqk-2C\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144551Z
LAST-MODIFIED:20180213T144551Z
TRANSP:OPAQUE
END:VEVENT
* Sea Dogs @ SeaWolves
<2018-08-09 Thu 18:05-21:05>
:PROPERTIES:
:ID:       Qw9smW8oNJ-cBsWgZn5MBv7F@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Sea Dogs @ SeaWolves Sea Dogs @ SeaWolves

Follow on MiLB First Pitch  https //stza.co/+vLql-1X

Shop  https //stza.co/+vLql-1H

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Sea Dogs @ SeaWolves
END:VALARM
DTSTART:20180809T230500Z
DTEND:20180810T020500Z
UID:Qw9smW8oNJ-cBsWgZn5MBv7F@stanza.co
SUMMARY:Sea Dogs @ SeaWolves
DESCRIPTION:Sea Dogs @ SeaWolves\n\nFollow on MiLB First Pitch: https://stza.co/+vLql-1X\n\nShop: https://stza.co/+vLql-1H\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144551Z
LAST-MODIFIED:20180213T144551Z
TRANSP:OPAQUE
END:VEVENT
* Sea Dogs @ RubberDucks
<2018-08-10 Fri 18:05-21:05>
:PROPERTIES:
:ID:       nej6hb3XeDEI7RSAOUtQ3GGg@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Sea Dogs @ RubberDucks Sea Dogs @ RubberDucks

Follow on MiLB First Pitch  https //stza.co/+vLp_-3q

Shop  https //stza.co/+vLp_-1I

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Sea Dogs @ RubberDucks
END:VALARM
DTSTART:20180810T230500Z
DTEND:20180811T020500Z
UID:nej6hb3XeDEI7RSAOUtQ3GGg@stanza.co
SUMMARY:Sea Dogs @ RubberDucks
DESCRIPTION:Sea Dogs @ RubberDucks\n\nFollow on MiLB First Pitch: https://stza.co/+vLp_-3q\n\nShop: https://stza.co/+vLp_-1I\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144551Z
LAST-MODIFIED:20180213T144551Z
TRANSP:OPAQUE
END:VEVENT
* Sea Dogs @ RubberDucks
<2018-08-11 Sat 18:05-21:05>
:PROPERTIES:
:ID:       3WDniAM2LC6BLRSKH7teirUv@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Sea Dogs @ RubberDucks Sea Dogs @ RubberDucks

Follow on MiLB First Pitch  https //stza.co/+vLp$-2a

Shop  https //stza.co/+vLp$-1v

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Sea Dogs @ RubberDucks
END:VALARM
DTSTART:20180811T230500Z
DTEND:20180812T020500Z
UID:3WDniAM2LC6BLRSKH7teirUv@stanza.co
SUMMARY:Sea Dogs @ RubberDucks
DESCRIPTION:Sea Dogs @ RubberDucks\n\nFollow on MiLB First Pitch: https://stza.co/+vLp$-2a\n\nShop: https://stza.co/+vLp$-1v\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144551Z
LAST-MODIFIED:20180213T144551Z
TRANSP:OPAQUE
END:VEVENT
* Sea Dogs @ RubberDucks
<2018-08-12 Sun 13:05-16:05>
:PROPERTIES:
:ID:       tX2l-O9Q_DZz-6QjkBXzs-vS@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Sea Dogs @ RubberDucks Sea Dogs @ RubberDucks

Follow on MiLB First Pitch  https //stza.co/+vLq0-1K

Shop  https //stza.co/+vLq0-1N

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Sea Dogs @ RubberDucks
END:VALARM
DTSTART:20180812T180500Z
DTEND:20180812T210500Z
UID:tX2l-O9Q_DZz-6QjkBXzs-vS@stanza.co
SUMMARY:Sea Dogs @ RubberDucks
DESCRIPTION:Sea Dogs @ RubberDucks\n\nFollow on MiLB First Pitch: https://stza.co/+vLq0-1K\n\nShop: https://stza.co/+vLq0-1N\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144551Z
LAST-MODIFIED:20180213T144551Z
TRANSP:OPAQUE
END:VEVENT
* Sea Dogs vs. Thunder
<2018-08-14 Tue 18:00-21:00>
:PROPERTIES:
:ID:       hZBkoeTJsAA_q21UNWZQjuNP@stanza.co
:LOCATION: Slugger bobblehead giveaway
:STATUS:   CONFIRMED
:END:

Sea Dogs vs. Thunder The first 1,000 fans to enter the ballpark will receive a Slugger bobblehead, courtesy of Dunkin' Donuts.

Buy tickets here  https //stza.co/~vLsC

Follow on MiLB First Pitch  https //stza.co/+vLsC-34

Shop  https //stza.co/+vLsC-2i

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Sea Dogs vs. Thunder
END:VALARM
DTSTART:20180814T230000Z
DTEND:20180815T020000Z
UID:hZBkoeTJsAA_q21UNWZQjuNP@stanza.co
SUMMARY:Sea Dogs vs. Thunder
DESCRIPTION:The first 1,000 fans to enter the ballpark will receive a Slugger bobblehead, courtesy of Dunkin' Donuts.\n\nBuy tickets here: https://stza.co/~vLsC\n\nFollow on MiLB First Pitch: https://stza.co/+vLsC-34\n\nShop: https://stza.co/+vLsC-2i\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Slugger bobblehead giveaway
STATUS:CONFIRMED
CREATED:20180213T144551Z
LAST-MODIFIED:20180213T144551Z
TRANSP:OPAQUE
END:VEVENT
* Sea Dogs vs. Thunder
<2018-08-15 Wed 18:00-21:00>
:PROPERTIES:
:ID:       __JiWLDcyxXpxhfIg16olw4p@stanza.co
:LOCATION: Swipe for last minute tickets for tonight's game. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Sea Dogs vs. Thunder Sea Dogs vs. Thunder

Buy tickets here  https //stza.co/~vLsD

Follow on MiLB First Pitch  https //stza.co/+vLsD-12

Shop  https //stza.co/+vLsD-I

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Sea Dogs vs. Thunder
END:VALARM
DTSTART:20180815T230000Z
DTEND:20180816T020000Z
UID:__JiWLDcyxXpxhfIg16olw4p@stanza.co
SUMMARY:Sea Dogs vs. Thunder
DESCRIPTION:Sea Dogs vs. Thunder\n\nBuy tickets here: https://stza.co/~vLsD\n\nFollow on MiLB First Pitch: https://stza.co/+vLsD-12\n\nShop: https://stza.co/+vLsD-I\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Swipe for last minute tickets for tonight's game. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144551Z
LAST-MODIFIED:20180213T144551Z
TRANSP:OPAQUE
END:VEVENT
* Sea Dogs vs. Thunder
<2018-08-16 Thu 11:00-14:00>
:PROPERTIES:
:ID:       xU2Ea5n7fzoGMLc6-hKf7W7L@stanza.co
:LOCATION: Spirit Day
:STATUS:   CONFIRMED
:END:

Sea Dogs vs. Thunder Special 12 00 PM start time. Parks & Rec groups along with camps will participate in spirit day competitions throughout the game. 

Buy tickets here  https //stza.co/~vLsG

Follow on MiLB First Pitch  https //stza.co/+vLsG-1u

Shop  https //stza.co/+vLsG-_

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Sea Dogs vs. Thunder
END:VALARM
DTSTART:20180816T160000Z
DTEND:20180816T190000Z
UID:xU2Ea5n7fzoGMLc6-hKf7W7L@stanza.co
SUMMARY:Sea Dogs vs. Thunder
DESCRIPTION:Special 12:00 PM start time. Parks & Rec groups along with camps will participate in spirit day competitions throughout the game. \n\nBuy tickets here: https://stza.co/~vLsG\n\nFollow on MiLB First Pitch: https://stza.co/+vLsG-1u\n\nShop: https://stza.co/+vLsG-_\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Spirit Day
STATUS:CONFIRMED
CREATED:20180213T144551Z
LAST-MODIFIED:20180213T144551Z
TRANSP:OPAQUE
END:VEVENT
* Sea Dogs vs. Curve
<2018-08-17 Fri 18:00-21:00>
:PROPERTIES:
:ID:       vkA_eSCEGrYrCQyf53j_3Oem@stanza.co
:LOCATION: Elvis Night
:STATUS:   CONFIRMED
:END:

Sea Dogs vs. Curve On the 41st anniversary of when Elvis was scheduled to play in Portland, the Sea Dogs will honor the King of Rock Roll at Hadlock.  Dana Z as Elvis will be performing pre-game on the front plaza.

Take your dog out to the ballgame!  Tickets for you and your dog are required. Participate in a pre-game parade led by Slugger.  Details & Ticket Info coming soon.

Two lucky fans will win a new 32 inch T.V., courtesy of David Munster's T.V. Sales & Service

Buy tickets here  https //stza.co/~vLsH

Follow on MiLB First Pitch  https //stza.co/+vLsH-2p

Shop  https //stza.co/+vLsH-3O

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Sea Dogs vs. Curve
END:VALARM
DTSTART:20180817T230000Z
DTEND:20180818T020000Z
UID:vkA_eSCEGrYrCQyf53j_3Oem@stanza.co
SUMMARY:Sea Dogs vs. Curve
DESCRIPTION:On the 41st anniversary of when Elvis was scheduled to play in Portland, the Sea Dogs will honor the King of Rock Roll at Hadlock.  Dana Z as Elvis will be performing pre-game on the front plaza.\n\nTake your dog out to the ballgame!  Tickets for you and your dog are required. Participate in a pre-game parade led by Slugger.  Details & Ticket Info coming soon.\n\nTwo lucky fans will win a new 32 inch T.V., courtesy of David Munster's T.V. Sales & Service\n\nBuy tickets here: https://stza.co/~vLsH\n\nFollow on MiLB First Pitch: https://stza.co/+vLsH-2p\n\nShop: https://stza.co/+vLsH-3O\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Elvis Night
STATUS:CONFIRMED
CREATED:20180213T144551Z
LAST-MODIFIED:20180213T144551Z
TRANSP:OPAQUE
END:VEVENT
* Sea Dogs vs. Curve
<2018-08-18 Sat 17:00-20:00>
:PROPERTIES:
:ID:       e7CRDwUTetDAATMaZky5tNCT@stanza.co
:LOCATION: The Kastaways
:STATUS:   CONFIRMED
:END:

Sea Dogs vs. Curve The Portland Sea Dogs' mascot band; The Kastaways will be performing pre-game on the front plaza.

Buy tickets here  https //stza.co/~vLsK

Follow on MiLB First Pitch  https //stza.co/+vLsK-2i

Shop  https //stza.co/+vLsK-b

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Sea Dogs vs. Curve
END:VALARM
DTSTART:20180818T220000Z
DTEND:20180819T010000Z
UID:e7CRDwUTetDAATMaZky5tNCT@stanza.co
SUMMARY:Sea Dogs vs. Curve
DESCRIPTION:The Portland Sea Dogs' mascot band; The Kastaways will be performing pre-game on the front plaza.\n\nBuy tickets here: https://stza.co/~vLsK\n\nFollow on MiLB First Pitch: https://stza.co/+vLsK-2i\n\nShop: https://stza.co/+vLsK-b\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:The Kastaways
STATUS:CONFIRMED
CREATED:20180213T144551Z
LAST-MODIFIED:20180213T144551Z
TRANSP:OPAQUE
END:VEVENT
* Sea Dogs vs. Curve
<2018-08-19 Sun 12:00-15:00>
:PROPERTIES:
:ID:       c78Gggw05RNvlPsoCkVN2hmm@stanza.co
:LOCATION: Kids run the bases for today's game. Bring out the family!
:STATUS:   CONFIRMED
:END:

Sea Dogs vs. Curve Kids 16 and under can run the bases after the game, weather and field conditions permitting.

Buy tickets here  https //stza.co/~vLsM

Follow on MiLB First Pitch  https //stza.co/+vLsM-1H

Shop  https //stza.co/+vLsM-2q

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Sea Dogs vs. Curve
END:VALARM
DTSTART:20180819T170000Z
DTEND:20180819T200000Z
UID:c78Gggw05RNvlPsoCkVN2hmm@stanza.co
SUMMARY:Sea Dogs vs. Curve
DESCRIPTION:Kids 16 and under can run the bases after the game, weather and field conditions permitting.\n\nBuy tickets here: https://stza.co/~vLsM\n\nFollow on MiLB First Pitch: https://stza.co/+vLsM-1H\n\nShop: https://stza.co/+vLsM-2q\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Kids run the bases for today's game. Bring out the family!
STATUS:CONFIRMED
CREATED:20180213T144551Z
LAST-MODIFIED:20180213T144551Z
TRANSP:OPAQUE
END:VEVENT
* Sea Dogs vs. Fisher Cats
<2018-08-20 Mon 18:00-21:00>
:PROPERTIES:
:ID:       ly1NXuimUujrSx9qlthT0lHT@stanza.co
:LOCATION: Ready for the game? Swipe for tickets and more information.
:STATUS:   CONFIRMED
:END:

Sea Dogs vs. Fisher Cats Sea Dogs vs. Fisher Cats

Buy tickets here  https //stza.co/~vLsO

Follow on MiLB First Pitch  https //stza.co/+vLsO-3h

Shop  https //stza.co/+vLsO-i

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Sea Dogs vs. Fisher Cats
END:VALARM
DTSTART:20180820T230000Z
DTEND:20180821T020000Z
UID:ly1NXuimUujrSx9qlthT0lHT@stanza.co
SUMMARY:Sea Dogs vs. Fisher Cats
DESCRIPTION:Sea Dogs vs. Fisher Cats\n\nBuy tickets here: https://stza.co/~vLsO\n\nFollow on MiLB First Pitch: https://stza.co/+vLsO-3h\n\nShop: https://stza.co/+vLsO-i\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Swipe for tickets and more information.
STATUS:CONFIRMED
CREATED:20180213T144551Z
LAST-MODIFIED:20180213T144551Z
TRANSP:OPAQUE
END:VEVENT
* Sea Dogs vs. Fisher Cats
<2018-08-21 Tue 17:00-20:00>
:PROPERTIES:
:ID:       R4SVo-eS2XEEuJ94EQz4FGSh@stanza.co
:LOCATION: Stick around after tonight's game for some spectacular fireworks!
:STATUS:   CONFIRMED
:END:

Sea Dogs vs. Fisher Cats Enjoy a fantastic post-game fireworks show, presented by Emerson Toyota.

Buy tickets here  https //stza.co/~vLsQ

Follow on MiLB First Pitch  https //stza.co/+vLsQ-3f

Shop  https //stza.co/+vLsQ-l

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Sea Dogs vs. Fisher Cats
END:VALARM
DTSTART:20180821T220000Z
DTEND:20180822T010000Z
UID:R4SVo-eS2XEEuJ94EQz4FGSh@stanza.co
SUMMARY:Sea Dogs vs. Fisher Cats
DESCRIPTION:Enjoy a fantastic post-game fireworks show, presented by Emerson Toyota.\n\nBuy tickets here: https://stza.co/~vLsQ\n\nFollow on MiLB First Pitch: https://stza.co/+vLsQ-3f\n\nShop: https://stza.co/+vLsQ-l\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stick around after tonight's game for some spectacular fireworks!
STATUS:CONFIRMED
CREATED:20180213T144551Z
LAST-MODIFIED:20180213T144551Z
TRANSP:OPAQUE
END:VEVENT
* Sea Dogs @ Fisher Cats
<2018-08-22 Wed 18:05-21:05>
:PROPERTIES:
:ID:       KQI9VS3FnYU0uW3azz0b53PA@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Sea Dogs @ Fisher Cats Sea Dogs @ Fisher Cats

Follow on MiLB First Pitch  https //stza.co/+vLqL-2D

Shop  https //stza.co/+vLqL-x

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Sea Dogs @ Fisher Cats
END:VALARM
DTSTART:20180822T230500Z
DTEND:20180823T020500Z
UID:KQI9VS3FnYU0uW3azz0b53PA@stanza.co
SUMMARY:Sea Dogs @ Fisher Cats
DESCRIPTION:Sea Dogs @ Fisher Cats\n\nFollow on MiLB First Pitch: https://stza.co/+vLqL-2D\n\nShop: https://stza.co/+vLqL-x\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144551Z
LAST-MODIFIED:20180213T144551Z
TRANSP:OPAQUE
END:VEVENT
* Sea Dogs @ Fisher Cats
<2018-08-23 Thu 18:05-21:05>
:PROPERTIES:
:ID:       WK28JKbOuo-wq3ud_Sw_2KRw@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Sea Dogs @ Fisher Cats Sea Dogs @ Fisher Cats

Follow on MiLB First Pitch  https //stza.co/+vLqM-$

Shop  https //stza.co/+vLqM-1F

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Sea Dogs @ Fisher Cats
END:VALARM
DTSTART:20180823T230500Z
DTEND:20180824T020500Z
UID:WK28JKbOuo-wq3ud_Sw_2KRw@stanza.co
SUMMARY:Sea Dogs @ Fisher Cats
DESCRIPTION:Sea Dogs @ Fisher Cats\n\nFollow on MiLB First Pitch: https://stza.co/+vLqM-$\n\nShop: https://stza.co/+vLqM-1F\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144551Z
LAST-MODIFIED:20180213T144551Z
TRANSP:OPAQUE
END:VEVENT
* Sea Dogs @ Fightin Phils
<2018-08-24 Fri 18:05-21:05>
:PROPERTIES:
:ID:       70-C-td5aNDxsA3afegL-9Lc@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Sea Dogs @ Fightin Phils Sea Dogs @ Fightin Phils

Buy tickets here  https //stza.co/~vanP

Follow on MiLB First Pitch  https //stza.co/+vanP-1B

Shop  https //stza.co/+vanP-2B

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Sea Dogs @ Fightin Phils
END:VALARM
DTSTART:20180824T230500Z
DTEND:20180825T020500Z
UID:70-C-td5aNDxsA3afegL-9Lc@stanza.co
SUMMARY:Sea Dogs @ Fightin Phils
DESCRIPTION:Sea Dogs @ Fightin Phils\n\nBuy tickets here: https://stza.co/~vanP\n\nFollow on MiLB First Pitch: https://stza.co/+vanP-1B\n\nShop: https://stza.co/+vanP-2B\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144551Z
LAST-MODIFIED:20180213T144551Z
TRANSP:OPAQUE
END:VEVENT
* Sea Dogs @ Fightin Phils
<2018-08-25 Sat 17:35-20:35>
:PROPERTIES:
:ID:       l2dAItazQfAlmkpxF_eK4a95@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Sea Dogs @ Fightin Phils Sea Dogs @ Fightin Phils

Buy tickets here  https //stza.co/~vanQ

Follow on MiLB First Pitch  https //stza.co/+vanQ-3

Shop  https //stza.co/+vanQ-2O

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Sea Dogs @ Fightin Phils
END:VALARM
DTSTART:20180825T223500Z
DTEND:20180826T013500Z
UID:l2dAItazQfAlmkpxF_eK4a95@stanza.co
SUMMARY:Sea Dogs @ Fightin Phils
DESCRIPTION:Sea Dogs @ Fightin Phils\n\nBuy tickets here: https://stza.co/~vanQ\n\nFollow on MiLB First Pitch: https://stza.co/+vanQ-3\n\nShop: https://stza.co/+vanQ-2O\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144551Z
LAST-MODIFIED:20180213T144551Z
TRANSP:OPAQUE
END:VEVENT
* Sea Dogs @ Fightin Phils
<2018-08-26 Sun 13:05-16:05>
:PROPERTIES:
:ID:       G4ll7OZQmLjy71T7Z8xda1Wu@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Sea Dogs @ Fightin Phils Sea Dogs @ Fightin Phils

Buy tickets here  https //stza.co/~vanR

Follow on MiLB First Pitch  https //stza.co/+vanR-p

Shop  https //stza.co/+vanR-1D

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Sea Dogs @ Fightin Phils
END:VALARM
DTSTART:20180826T180500Z
DTEND:20180826T210500Z
UID:G4ll7OZQmLjy71T7Z8xda1Wu@stanza.co
SUMMARY:Sea Dogs @ Fightin Phils
DESCRIPTION:Sea Dogs @ Fightin Phils\n\nBuy tickets here: https://stza.co/~vanR\n\nFollow on MiLB First Pitch: https://stza.co/+vanR-p\n\nShop: https://stza.co/+vanR-1D\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144551Z
LAST-MODIFIED:20180213T144551Z
TRANSP:OPAQUE
END:VEVENT
* Sea Dogs vs. Fisher Cats
<2018-08-27 Mon 18:00-21:00>
:PROPERTIES:
:ID:       qKZVPvZrN7zFXXbxPW9Y-3At@stanza.co
:LOCATION: Women in Sports Night
:STATUS:   CONFIRMED
:END:

Sea Dogs vs. Fisher Cats Details to be announced



Buy tickets here  https //stza.co/~vLsS

Follow on MiLB First Pitch  https //stza.co/+vLsS-3d

Shop  https //stza.co/+vLsS-15

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Sea Dogs vs. Fisher Cats
END:VALARM
DTSTART:20180827T230000Z
DTEND:20180828T020000Z
UID:qKZVPvZrN7zFXXbxPW9Y-3At@stanza.co
SUMMARY:Sea Dogs vs. Fisher Cats
DESCRIPTION:Details to be announced\n\n\n\nBuy tickets here: https://stza.co/~vLsS\n\nFollow on MiLB First Pitch: https://stza.co/+vLsS-3d\n\nShop: https://stza.co/+vLsS-15\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Women in Sports Night
STATUS:CONFIRMED
CREATED:20180213T144551Z
LAST-MODIFIED:20180213T144551Z
TRANSP:OPAQUE
END:VEVENT
* Sea Dogs vs. Fisher Cats
<2018-08-28 Tue 18:00-21:00>
:PROPERTIES:
:ID:       18_2v-Xyg1ANOS5wd1KPUumO@stanza.co
:LOCATION: Looking for something to do tonight? Get tickets here for tonight’s game and view promotions.
:STATUS:   CONFIRMED
:END:

Sea Dogs vs. Fisher Cats Sea Dogs vs. Fisher Cats

Buy tickets here  https //stza.co/~vLsU

Follow on MiLB First Pitch  https //stza.co/+vLsU-2M

Shop  https //stza.co/+vLsU-2I

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Sea Dogs vs. Fisher Cats
END:VALARM
DTSTART:20180828T230000Z
DTEND:20180829T020000Z
UID:18_2v-Xyg1ANOS5wd1KPUumO@stanza.co
SUMMARY:Sea Dogs vs. Fisher Cats
DESCRIPTION:Sea Dogs vs. Fisher Cats\n\nBuy tickets here: https://stza.co/~vLsU\n\nFollow on MiLB First Pitch: https://stza.co/+vLsU-2M\n\nShop: https://stza.co/+vLsU-2I\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Looking for something to do tonight? Get tickets here for tonight’s game and view promotions.
STATUS:CONFIRMED
CREATED:20180213T144551Z
LAST-MODIFIED:20180213T144551Z
TRANSP:OPAQUE
END:VEVENT
* Sea Dogs vs. Fisher Cats
<2018-08-29 Wed 18:00-21:00>
:PROPERTIES:
:ID:       qZHnJ0Bvk5LkX_SuozQXokdQ@stanza.co
:LOCATION: Field of Dreams
:STATUS:   CONFIRMED
:END:

Sea Dogs vs. Fisher Cats It's a scene right out of the movie as the Sea Dogs wear old tyme uniforms and emerge from a cornfield.

Buy tickets here  https //stza.co/~vLsV

Follow on MiLB First Pitch  https //stza.co/+vLsV-1u

Shop  https //stza.co/+vLsV-b

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Sea Dogs vs. Fisher Cats
END:VALARM
DTSTART:20180829T230000Z
DTEND:20180830T020000Z
UID:qZHnJ0Bvk5LkX_SuozQXokdQ@stanza.co
SUMMARY:Sea Dogs vs. Fisher Cats
DESCRIPTION:It's a scene right out of the movie as the Sea Dogs wear old tyme uniforms and emerge from a cornfield.\n\nBuy tickets here: https://stza.co/~vLsV\n\nFollow on MiLB First Pitch: https://stza.co/+vLsV-1u\n\nShop: https://stza.co/+vLsV-b\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Field of Dreams
STATUS:CONFIRMED
CREATED:20180213T144551Z
LAST-MODIFIED:20180213T144551Z
TRANSP:OPAQUE
END:VEVENT
* Sea Dogs vs. Fisher Cats
<2018-08-30 Thu 18:00-21:00>
:PROPERTIES:
:ID:       onamaN3RYKrTvz2U_c1QzqL2@stanza.co
:LOCATION: Team Awards
:STATUS:   CONFIRMED
:END:

Sea Dogs vs. Fisher Cats The 2018 team awards for MVP, Pitcher of the Year, 10th Player, and Citizen of the Year will be presented in a pre-game ceremony.

Buy tickets here  https //stza.co/~vLsX

Follow on MiLB First Pitch  https //stza.co/+vLsX-E

Shop  https //stza.co/+vLsX-I

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT240M
ACTION:DISPLAY
DESCRIPTION:Sea Dogs vs. Fisher Cats
END:VALARM
DTSTART:20180830T230000Z
DTEND:20180831T020000Z
UID:onamaN3RYKrTvz2U_c1QzqL2@stanza.co
SUMMARY:Sea Dogs vs. Fisher Cats
DESCRIPTION:The 2018 team awards for MVP, Pitcher of the Year, 10th Player, and Citizen of the Year will be presented in a pre-game ceremony.\n\nBuy tickets here: https://stza.co/~vLsX\n\nFollow on MiLB First Pitch: https://stza.co/+vLsX-E\n\nShop: https://stza.co/+vLsX-I\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Team Awards
STATUS:CONFIRMED
CREATED:20180213T144551Z
LAST-MODIFIED:20180213T144551Z
TRANSP:OPAQUE
END:VEVENT
* Sea Dogs @ Rumble Ponies
<2018-08-31 Fri 18:05-21:05>
:PROPERTIES:
:ID:       awxZHxfA2fLd_A8saiz8MaAt@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Sea Dogs @ Rumble Ponies Sea Dogs @ Rumble Ponies

Follow on MiLB First Pitch  https //stza.co/+vLqc-a

Shop  https //stza.co/+vLqc-b

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Sea Dogs @ Rumble Ponies
END:VALARM
DTSTART:20180831T230500Z
DTEND:20180901T020500Z
UID:awxZHxfA2fLd_A8saiz8MaAt@stanza.co
SUMMARY:Sea Dogs @ Rumble Ponies
DESCRIPTION:Sea Dogs @ Rumble Ponies\n\nFollow on MiLB First Pitch: https://stza.co/+vLqc-a\n\nShop: https://stza.co/+vLqc-b\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144551Z
LAST-MODIFIED:20180213T144551Z
TRANSP:OPAQUE
END:VEVENT
* Sea Dogs @ Rumble Ponies
<2018-09-01 Sat 17:05-20:05>
:PROPERTIES:
:ID:       7yIk041Q11JkgaSCVG37vjge@stanza.co
:LOCATION: Ready for the game? Follow along with MiLB First Pitch.
:STATUS:   CONFIRMED
:END:

Sea Dogs @ Rumble Ponies Sea Dogs @ Rumble Ponies

Follow on MiLB First Pitch  https //stza.co/+vLqd-26

Shop  https //stza.co/+vLqd-2H

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Sea Dogs @ Rumble Ponies
END:VALARM
DTSTART:20180901T220500Z
DTEND:20180902T010500Z
UID:7yIk041Q11JkgaSCVG37vjge@stanza.co
SUMMARY:Sea Dogs @ Rumble Ponies
DESCRIPTION:Sea Dogs @ Rumble Ponies\n\nFollow on MiLB First Pitch: https://stza.co/+vLqd-26\n\nShop: https://stza.co/+vLqd-2H\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Ready for the game? Follow along with MiLB First Pitch.
STATUS:CONFIRMED
CREATED:20180213T144551Z
LAST-MODIFIED:20180213T144551Z
TRANSP:OPAQUE
END:VEVENT
* Sea Dogs @ Rumble Ponies
<2018-09-02 Sun 17:35-20:35>
:PROPERTIES:
:ID:       Fot8lb97QzONKkzbT-HwtH_v@stanza.co
:LOCATION: Stay in the loop by following the action with MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Sea Dogs @ Rumble Ponies Sea Dogs @ Rumble Ponies

Follow on MiLB First Pitch  https //stza.co/+vLqe-1m

Shop  https //stza.co/+vLqe-11

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Sea Dogs @ Rumble Ponies
END:VALARM
DTSTART:20180902T223500Z
DTEND:20180903T013500Z
UID:Fot8lb97QzONKkzbT-HwtH_v@stanza.co
SUMMARY:Sea Dogs @ Rumble Ponies
DESCRIPTION:Sea Dogs @ Rumble Ponies\n\nFollow on MiLB First Pitch: https://stza.co/+vLqe-1m\n\nShop: https://stza.co/+vLqe-11\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Stay in the loop by following the action with MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144551Z
LAST-MODIFIED:20180213T144551Z
TRANSP:OPAQUE
END:VEVENT
* Sea Dogs @ Rumble Ponies
<2018-09-03 Mon 12:05-15:05>
:PROPERTIES:
:ID:       F4R_TvHfVywLuo0j3C_YkEqk@stanza.co
:LOCATION: Don't miss a minute of action. Follow along with the MiLB First Pitch app.
:STATUS:   CONFIRMED
:END:

Sea Dogs @ Rumble Ponies Sea Dogs @ Rumble Ponies

Follow on MiLB First Pitch  https //stza.co/+vLqf-6

Shop  https //stza.co/+vLqf-3X

Synced via Stanza - create your own live updating calendar (https //stanza.co?events)

For questions, check out Stanza’s FAQs page  https //stanza.co/faqs
** COMMENT original iCal entry
 
BEGIN:VEVENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT30M
ACTION:DISPLAY
DESCRIPTION:Sea Dogs @ Rumble Ponies
END:VALARM
DTSTART:20180903T170500Z
DTEND:20180903T200500Z
UID:F4R_TvHfVywLuo0j3C_YkEqk@stanza.co
SUMMARY:Sea Dogs @ Rumble Ponies
DESCRIPTION:Sea Dogs @ Rumble Ponies\n\nFollow on MiLB First Pitch: https://stza.co/+vLqf-6\n\nShop: https://stza.co/+vLqf-3X\n\nSynced via Stanza - create your own live updating calendar (https://stanza.co?events)\n\nFor questions, check out Stanza’s FAQs page: https://stanza.co/faqs
LOCATION:Don't miss a minute of action. Follow along with the MiLB First Pitch app.
STATUS:CONFIRMED
CREATED:20180213T144551Z
LAST-MODIFIED:20180213T144551Z
TRANSP:OPAQUE
END:VEVENT
